### PR TITLE
Curl - allow setting HTTP version

### PR DESCRIPTION
**Pull request by ghost**
### Description
Added allow for setting curl http version

### Fixed Issues (if relevant)
1. magento/magento2#19442: Magento/Framework/HTTP/Adapter/Curl.php doesn't allow setting HTTP version

### Manual testing scenarios (*)
1. Create new ZendClient $client
2. Set HTTP version $client->setConfig(['httpversion' => CURL_HTTP_VERSION_1_1])
3. Make a request $client->request()

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### Additional information
1. magento/magento2#19445: Recovered Pull Request

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @SikailoISM. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3710](https://jira.corp.magento.com/browse/ENGCOM-3710) has been created to process this Pull Request

**Comment by ryanreeves-taxjar** [comment]
Is it possible to bypass the Codacy/PR Quality Review?  It fails on the use of curl_setopt, but I don't think that guideline should apply since the write method already calls that function several times.

**Comment by sivaschenko** [comment]
Hi @ryanreeves-taxjar , yes, I think that codacy can be ignored in this particular case.

**Comment by perfpcs** [comment]
Can I get an update when this issue will be resolved? It seems like this will happen in 2,3.1, correct? What is the estimate time release for 2.3.1?

**Comment by sivaschenko** [comment]
Hi @SikailoISM , sorry for delays in processing and response, it will be soon merged to mainline

**Comment by YevSent** [comment]
This fix breaks existing functionality, `curl_setopt` with `CURLOPT_HTTP_VERSION` requires a digit `0-3` but not a string. See http://php.net/manual/en/function.curl-setopt.php

**Pull request merged**
