### PR TITLE
Set proper secure flag for JS based cookies

### PR DESCRIPTION
**Pull request by diwipl**
### Description (*)

Merge request replaces hardcoded `secure: false` property of Javascript cookie manager into dynamic one based on value returned by backend.

### Fixed Issues (if relevant)

1. magento/magento2#22272: Frontend cookies are not set with secure flag on https

### Manual testing scenarios (*)

1. Set up Magento with HTTPS enabled
2. Check if cookies set by Javascript contain secure flag

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22793) <br/>All committers have signed the CLA.

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-5146](https://jira.corp.magento.com/browse/ENGCOM-5146) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@diwipl thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VasylShvorak** [comment]
HI @diwipl I was able to check PR changes only if I set URL in both Base URLs and Base URLs (Secure) sections with prefix https:// . And in this case not all cookies were checked as Secure
#22793PR
@sivaschenko Could you check if it is expected behavior ?

**Comment by sivaschenko** [comment]
@melnikovi can you please take a look if the SVC failure can be approved for this PR (adding a public method to and API class)

**Comment by sidolov** [comment]
@diwipl , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by krzksz** [comment]
Hello everyone, we are checking the issue with `form_key` no being set as secure as this should be doable.

On the other hand the problem with all of the `mage-translation-*` cookies is that JavaScript files in translation system use jQuery Storage API extension that Magento provides which doesn't support setting a secure flag at all: https://github.com/julien-maurel/jQuery-Storage-API/blob/master/jquery.storageapi.js#L427

In your opinion, which approach should we take:
- Overwrite the implementation included in Magento to add support for `secure` flag.
- Leave it be, as translations should not contain any sensitive information anyway.

**Comment by twoatechguy** [comment]
> In your opinion, which approach should we take:
> 
> * Overwrite the implementation included in Magento to add support for `secure` flag.
> * Leave it be, as translations should not contain any sensitive information anyway.

I would vote for leaving translations as be, if Magento will pass PCI-DSS compliance testing. I am curious if the translation cookies would fail the testing requirements of 6.5.10:

6.5.10 Examine software development policies and procedures and interview responsible personnel to verify that broken authentication and session management are addressed via coding techniques that commonly include:
• Flagging session tokens (for example cookies) as “secure”
• Not exposing session IDs in the URL
• Incorporating appropriate time-outs and rotation of session IDs after a successful login.

**Comment by diwipl** [comment]
Closed in favor of: https://github.com/magento/magento2/commit/2d1f8ca5d13c626000b34002704de9e0a99d3d99

**Pull request closed without merging**
