### PR TITLE
Converted magento magento2 30090 2.3.7

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

This merge for create patch magento 2.3.x use fixes speedup SCD process pipelines
@ihor-sviziev can you share the patch link (if it's exist)

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
Further question
Is this cover deploy compact strategy ?

**Comment by mrtuvn** [comment]
See this note in 2.4.5 release details but i'm not sure what code changed in commit ?

> The bin/magento setup:static-content:deploy -s compact command now includes styles from child themes as expected. Previously, theme CSS files were not present on the storefront after deployment.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run WebAPI Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B, Integration Tests

**Comment by mrtuvn** [comment]
cc: @sidolov @sdzhepa

**Comment by ihor-sviziev** [comment]
Hi @mrtuvn,
In order to merge this pull request, all tests should be passed and description should be in special format. Example https://github.com/magento/magento2/pull/34529

**Comment by mrtuvn** [comment]
This one i think neccessary for old stores used below range 2.3.x to 2.4

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
Hey @mrtuvn 

Unfortunately we are unable to accept any Pull Requests to releases or branches other than current `2.4-develop` therefore I have to close this PR for now.

Please feel free to reopen this PR for current release branch if you think issue is still there.

**Comment by mrtuvn** [comment]
This one not create any changes to current repo. This port create patch to  https://github.com/magento/quality-patches
@ishakhsuvarov

**Pull request closed without merging**
