### PR TITLE
Datepicker not clear after filter#32456

### LINKED ISSUE #32456: Admin Grid date range filter not working as expected
### Preconditions (*)

1. Magento 2.4.1

### Steps to reproduce (*)

1. In Backend select "Sales/Orders".
2. Click on "Filters" and add a date range filter for "purchase date" and apply this filter. The filtered grid will appear as expected.
3. Click on "Clear all" to remove this filter
filter2

### Expected result (*)

After removing the filter the date range should be cleared when you click next time on "Filters". 

### Actual result (*)

The date range is still filled out. Even worse, if you click next time on "Apply filters" (without modifying the date range), this date range is not applied.

filter

- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by gixid192**
### Description (*)
Make sure the datepicker input get cleared after filtering in grid

### Fixed Issues (if relevant)
Fixes magento/magento2#32456

### Questions or comments
I only clear out the text input, so not sure what test should I put here. Please advise, thanks!

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by gixid192** [comment]
@magento run all tests

**Comment by gixid192** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by gixid192** [comment]
@magento give me test instance

**Comment by gixid192** [comment]
@magento-engcom-team Could you help checking those failing tests?
I followed the steps described in the test with Magento instance and it's working with my code. 

Here is the video: https://www.screencast.com/t/IuNJchy3rab1
In the video I first filter to check that my code is working as expected (both for invalid date and validate date). Then I restore to the original code to demonstrate that my code fixed the issue.

**Comment by danielrussob** [comment]
@magento give me test instance

**Comment by danielrussob** [comment]
@magento give me 2.4-develop instance

**Comment by eduard13** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by eduard13** [comment]
@magento run Functional Tests EE

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @gixid192, thank you for your contribution. Can you try to squash your commits, in order to have a clean commits history?

As about the test coverage, such cases can be easily covered by [MFTF](https://devdocs.magento.com/mftf/docs/getting-started.html). So could you please provide a MFTF test that is going to validate the expected result?

Thank you.

**Comment by gixid192** [comment]
@eduard13 I will check with squash commit. For MFTF, it doesn't work on my machine. Trying to figure out what's happening. Will cover the test as soon as possible.

**Comment by gixid192** [comment]
Hi @eduard13,
Here I add 2 new assertions into `ClearFiltersAdminDataGridActionGroup`. But even when the input is not empty, the test still pass, could you help take a look please?

I first try with my new code and then restore to the original, both green. I removed pub/static folder before testing, I don't know how to clear cache in browser when running the test. Not sure if cache causes this.

```
<actionGroups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:mftf:Test/etc/actionGroupSchema.xsd">
    <actionGroup name="ClearFiltersAdminDataGridActionGroup">
        <annotations>
            <description>Clicks on 'Clear Filters' on an Admin Grid page.</description>
        </annotations>

        <conditionalClick selector="{{AdminDataGridHeaderSection.clearFilters}}" dependentSelector="{{AdminDataGridHeaderSection.clearFilters}}" visible="true" stepKey="clearExistingOrderFilters"/>

        <!-- new code -->
        <seeInField selector="{{AdminLoginAsCustomerLogToolbarSection.DatePickerFrom}}" userInput="" stepKey="emptyFromDateInPlaceHolderAfterClearFilter"/>
        <seeInField selector="{{AdminLoginAsCustomerLogToolbarSection.DatePickerTo}}" userInput="" stepKey="emptyToDateInPlaceHolderAfterClearFilter"/>
        <!-- end new code -->
    </actionGroup>
</actionGroups>
```

**Comment by gixid192** [comment]
I just checked the selector again, it's the button that I was checking, not the input.

Could you confirm if I should write to that core's file (ClearFiltersAdminDataGridActionGroup) or just write to the current `AdminLoginAsCustomerLoggingFilterTest`?
The reason is there is no input selector in the core's action, only buttons. And also, as the group name suggested, I don't know if writing assertion into it is alright.

**Comment by eduard13** [comment]
Hi @gixid192, changing any core ActionGroup should be avoided. In your case, you may create a new Action Group that will check those 2 fields to be empty, like `AdminAssertEmptyDateGridFiltersActionGroup`.

Instead of hardcoding the `[name='time[from]']` selector, I'd suggest creating a more dynamical date selector `[name='{{fieldName}}[from]']`. As result, we'll have a dynamical input, that can be used for any from/to date fields:

- `<element name="dateFromFieldByName" type="input" selector=".admin__data-grid-filters input[name='{{name}}[from]']" parameterized="true"/>`
- `<element name="dateToFieldByName" type="input" selector=".admin__data-grid-filters input[name='{{name}}[to]']" parameterized="true"/>`

As for usage, we should be able to pass the attribute name as parameter, something like `{{Section.dateFromFieldByName('last_visit_at')}}` and `{{Section.dateToFieldByName('last_visit_at')}}`.

As result, you should have a new Test file and a new ActionGroup `AdminAssertEmptyDateGridFiltersActionGroup`, that will be using the above mentioned elements and will be asserting that the fields are empty.

Please let me know if there are any questions.

Thank you.

**Comment by eduard13** [comment]
Hi @gixid192, are there any updates or maybe some issues that you faced?
Thank you.

**Comment by gabrieldagama** [comment]
@magento run Functional Tests EE

**Comment by engcom-Foxtrot** [comment]
Hello, @gixid192. Unfortunately, I'm closing and re-creating this PR, as I was not able to push any changes to this PR branch. Please feel free to push any updates to https://github.com/magento/magento2/pull/33027.

**Pull request closed without merging**
