### PR TITLE
#26240: Fixed logic for getting option price index for selected swatch option

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description (*)
Fixed logic for getting option price index for selected swatch option.

### Fixed Issues (if relevant)
1. #26240 

### Manual testing scenarios (*)
1. Enable MAP (Store -> Configuration -> Sales -> Sales -> Minimum Advertised Price -> Enable MAP).

1. Create configurable product for attribute with 'swatch' (Visual Swatch, Text Swatch) type with assoshiated products:
-  simple A: price 1, MAP 11. (ex: 'black' color)
-  simple B: price 1, MAP 12. (ex: 'white' color)

Expected result

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lbajsarowicz — CHANGES_REQUESTED** [review]
Merge latest `2.4-develop` and fix static tests.

**Comment by sergiy-v** [comment]
> Merge latest `2.4-develop` and fix static tests.

Merged `2.4-develop` and fixed static tests, thanks.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6750](https://jira.corp.magento.com/browse/ENGCOM-6750) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Golf** [comment]
Failed Functional tests not related to changes in this PR, tests fail on 2.4-develop branch

**Comment by lbajsarowicz** [comment]
Already https://github.com/magento/magento2/pull/26608 to be addressed.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6750](https://jira.corp.magento.com/browse/ENGCOM-6750) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
