### PR TITLE
Fix ApiFunctional TestFramework GraphQL headers parsing

### LINKED ISSUE #26425: [BUG] ApiFunctional TestFramework GraphQL Client Parses Headers Improperly
### Preconditions (*)
Magento v2.3.3

### Steps to reproduce (*)
1. Make a call with the `GraphQlAbstract::graphQlQueryWithResponseHeaders`
2. Have a header in the response like: `Access-Control-Allow-Origin: https://www.example.com`
3. See that the header does NOT show up in the headers array

### Expected result (*)
1. Have a header in the headers array like: `['Access-Control-Allow-Origin'] => 'https://www.example.com'`

### Actual result (*)
See above.

This is due to a failed `preg_split` logic in:

https://github.com/magento/magento2/blame/6b4a82b8554917ba78f7bc84ada8ea05a85aca92/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/GraphQl/Client.php#L210

```php
/**
     * Parse response headers into associative array
     *
     * @param string $headers
     * @return array
     */
    private function processResponseHeaders(string $headers): array
    {
        $headersArray = [];

        $headerLines = preg_split('/((\r?\n)|(\r\n?))/', $headers);
        foreach ($headerLines as $headerLine) {
            $headerParts = preg_split('/: /', $headerLine);
            if (count($headerParts) == 2) {
                $headersArray[trim($headerParts[0])] = trim($headerParts[1]);
            } elseif (preg_match('/HTTP\/[\.0-9]+/', $headerLine)) {
                $headersArray[trim('Status-Line')] = trim($headerLine);
            }
        }

        return $headersArray;
    }
```

It should `preg_split` with a limit of `2`:

```php
$headerParts = preg_split('/: /', $headerLine, 2);
```

cc: @danielrenaud @danmooney2

### PR DESCRIPTION
**Pull request by michalderlatka**
### Description (*)

Change how headers are parsed in ApiFunctional TestFramework so header values including urls are parsed properly

### Fixed Issues (if relevant)
1. Fixes magento/magento2#26425

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by michalderlatka** [comment]
@magento run all tests

**Comment by rogyar** [comment]
@magento run Functional Tests B2B

**Comment by michalderlatka** [comment]
@magento run Functional Tests B2B

**Comment by michalderlatka** [comment]
@magento run Functional Tests B2B

**Review by rogyar — APPROVED** [review]
Error in the functional tests is not related to the current change

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7762](https://jira.corp.magento.com/browse/ENGCOM-7762) has been created to process this Pull Request

**Review by danielrenaud — APPROVED** [review]

**Review by cpartica — APPROVED** [review]

**Pull request merged**
