### PR TITLE
Patch 18812

### PR DESCRIPTION
**Pull request by ketan-krish**
### Description (*)

Unable to update simple product custom option in cart when quantity is 1

### Fixed Issues (if relevant)

1. #18812: Unable to update simple product custom option in cart when quantity is 1

### Manual testing scenarios (*)

1. Go to product page and select options and click add to cart.
2. Go to cart and select "Edit/Update Item"
3. Select different option from original and click update.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19651) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @ketan-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sidolov** [comment]
Hi @ketan-krish, please, take a look at failed tests, looks like a lot of failures caused by provided changes!

**Comment by ketan-krish** [comment]
Hello @sidolov,

Please assist me to resolve Travis errors.

**Comment by sidolov** [comment]
Hi @ketan-krish , Travis failures indicating that some cases are broken with the provided solution. Please, consider finding the new solution that's support all cases including scenarios from the tests

**Comment by sidolov** [comment]
Hi @ketan-krish , Travis builds still failing, will you continue work with PR?

**Comment by sidolov** [comment]
Hi @ketan-krish , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
