### PR TITLE
issue-22007

### PR DESCRIPTION
**Pull request by irajneeshgupta**
### Description (*)

If the function `getCustomAttribute` called on model in `catalog_product_save_before` then the multiselect custom attribute data was not saving previously. 
Using a local variable instead of overridden global `$this->_data` was eleminated in `initializeCustomAttributes` function.
### Fixed Issues (if relevant)

1. magento/magento2#22007: Issue 2.3.0 Product attribute not saving if getCustomAttribute / getCustomAttributes is called

### Manual testing scenarios (*)

1.Magento 2.3
2.Make sure getCustomAttribute or getCustomAttributes() is called on the model before Magento\Framework\EntityManager\Operation\Update is executed (for example in a catalog_product_save_before observer)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by irajneeshgupta** [comment]
#dmcdindia1

**Comment by sidolov** [comment]
@magento run all builds

**Comment by sidolov** [comment]
@magento run all tests

**Review by sidolov — CHANGES_REQUESTED** [review]
@irajneeshgupta , it's a little bit weird to not use the class property for data storing and a lot of failed tests are indicating the issue with the solution. 
Please, take a look at failed tests

**Comment by sidolov** [comment]
@irajneeshgupta , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
