### PR TITLE
Backport PR-1895 for Magento 2.1 - Fix relative template references in individual Magento modules

### PR DESCRIPTION
**Pull request by hostep**
### Description
This is a backport of https://github.com/magento/magento2/pull/1895 for Magento 2.1
I started with cherry picking this commit: https://github.com/magento/magento2/commit/a4341625abdf4321849b4c318abd20eece843856 (since it contains some extra fixes above the PR referenced above) and fixed a bunch of merge conflicts.
Then ran the new static test introduced in the above commit, which revealed two more files which needed fixing, and fixed those two in a separate commit (curiously enough they were fixed in the initial PR by @davidalger, but were not included in the merge commit from @vrann)

Please be very careful when reviewing this, a lot of files have changed!
I'm not exactly sure about the changes in the `composer.json` files, but since they were included in the commit from @vrann, I also included them.

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/7273: Remember me template is not loaded from the original module
2. https://github.com/magento/magento2/issues/1287: setting target Module Name when generating a block
3. https://github.com/magento/magento2/pull/11004: fix for lost template when creating a preference for Magento\Checkout\Block\Cart\Item\Renderer
...

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by dmanners** [comment]
Hi @hostep, thanks for this pull request.

Could you take a look at the static test failures for me.

```
1) Magento\Test\Php\LiveCodeTest::testCodeStylePsr2
PHP Code Sniffer has found 6 error(s): 
FILE: ...integration/testsuite/Magento/Framework/View/Model/Layout/MergeTest.php
--------------------------------------------------------------------------------
FOUND 6 ERROR(S) AFFECTING 6 LINE(S)
--------------------------------------------------------------------------------
 34 | ERROR | Opening parenthesis of a multi-line function call must be the
    |       | last content on the line
 39 | ERROR | Closing parenthesis of a multi-line function call must be on a
    |       | line by itself
 52 | ERROR | Opening parenthesis of a multi-line function call must be the
    |       | last content on the line
 57 | ERROR | Closing parenthesis of a multi-line function call must be on a
    |       | line by itself
 65 | ERROR | Opening parenthesis of a multi-line function call must be the
    |       | last content on the line
 68 | ERROR | Closing parenthesis of a multi-line function call must be on a
    |       | line by itself
--------------------------------------------------------------------------------
```

**Comment by hostep** [comment]
@dmanners: static test failures are fixed.

**Comment by dmanners** [comment]
Hi @hostep any chance you could have a look at these conflicting files?

**Comment by hostep** [comment]
@dmanners: ok done!

Just for information: conflicts where caused by https://github.com/magento/magento2/commit/db166c748957a161d9cdc79d0c110caa609857c7

I've rebased my branch on top of the latest `2.1-develop`, fixed conflicts (removed the same 4 lines in the xml files like in https://github.com/magento/magento2/commit/db166c748957a161d9cdc79d0c110caa609857c7), and force pushed.

Let's see how the tests are doing (can't seem to get them working properly at the moment on my local machine).

**Comment by dmanners** [comment]
Thanks @hostep I have never been able to get this branch behaving how I would like in the tests either. Hopefully I can sort this out now though.

**Comment by dmanners** [comment]
Hi @hostep as discussed via slack I will close this PR. For me this fix is already in newer versions of Magento and the release line 2.1 will no longer be available for contribution as of Monday the 17th of September. The decision to close 2.1 was made to increase focus on 2.2 and 2.3 release lines.

Thanks for your understanding.

**Pull request closed without merging**
