### PR TITLE
32911 fixed product import with url key with spaces

### LINKED ISSUE #32911: CSV product import does not format url key when `url_key` column is used
When I use the Magento default csv product import with an `url_key` field the value is not formatted/translit before being inserted into the database. This way I end up with spaces in the url key field. The rest of the system works ok with this except GraphQL which will output the `url_key` field directly from the database.

### Preconditions (*)
Magento 2.4.2 and probably all versions below.

### Steps to reproduce (*)
1. Create a product with sku: ABC
2. Import csv below:
```
"sku", "url_key"
"ABC", "Test ABC 1 2 3"
```

### Expected result (*)
1. `url_key` attribute being: `test-abc-1-2-3`

### Actual result (*)
1. `url_key` attribute being: `test abc 1 2 3`

---
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

## Patch

```
--- vendor/magento/module-catalog-import-export/Model/Import/Product.php
+++ vendor/magento/module-catalog-import-export/Model/Import/Product.php
@@ -3011,7 +3011,7 @@
     {
         if (!empty($rowData[self::URL_KEY])) {
             $urlKey = (string) $rowData[self::URL_KEY];
-            return trim(strtolower($urlKey));
+            return $this->productUrl->formatUrlKey($urlKey);
         }
 
         if (!empty($rowData[self::COL_NAME])
```

### PR DESCRIPTION
**Pull request by SilinMykola**
### Description (*)
I changed \Magento\CatalogImportExport\Model\Import\Product class as suggested in [issue](https://github.com/magento/magento2/issues/32911) and add integration test.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#32911

### Manual testing scenarios (*)
1. Create a product with sku: ABC
2. Create import file 
```
"sku", "url_key"
"ABC", "Test ABC 1 2 3"
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by SilinMykola** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @SilinMykola,
Could you review and fix the failing integration tests?

**Comment by SilinMykola** [comment]
@magento run all tests

**Comment by SilinMykola** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9103](https://jira.corp.magento.com/browse/ENGCOM-9103) has been created to process this Pull Request

**Comment by SilinMykola** [comment]
@magento run all tests

**Comment by SilinMykola** [comment]
@ihor-sviziev Hello! Sorry, I mistook and force pushed to wrong branch. I rollbacked all wrong changes and started all tests. Thanks for your time!

**Comment by SilinMykola** [comment]
@magento run Functional Tests EE, Unit Tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9103](https://jira.corp.magento.com/browse/ENGCOM-9103) has been created to process this Pull Request

**Comment by SilinMykola** [comment]
@magento Functional Tests EE

**Comment by SilinMykola** [comment]
@magento run Functional Tests EE

**Comment by SilinMykola** [comment]
@magento run Functional Tests EE

**Comment by SilinMykola** [comment]
@magento run Functional Tests EE

**Comment by SilinMykola** [comment]
@magento run Functional Tests EE

**Comment by SilinMykola** [comment]
@magento run Functional Tests EE

**Comment by SilinMykola** [comment]
@magento run Functional Tests EE

**Comment by Den4ik** [comment]
@magento run Functional Tests EE

**Comment by Den4ik** [comment]
Translit relate PR https://github.com/magento/magento2/pull/33060

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9103](https://jira.corp.magento.com/browse/ENGCOM-9103) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Thanks for the contribution @Reporter and @Reviewer!

I have tried reproducing the issue in 2.4-develop version before testing the given PR fix code. Issue is reproducible as per my understanding based on given issue/ PR description and below are the reproducible steps in detail:

1. Added a new simple product (namely- ABC) in the Admin>Catalog>Product page. (Mentioned SKU : ABC)

2. Exported the added file into csv and edited the CSV file content like: product name to _ABC2_ and  url_key to _ABC2 1 2 3_ .

3. Imported the edited CSV file.

4. Validated the ABC2 product in the Product page and its _url_key_ value


> **Expected:** 
> url_key should be updated like: _abc2-1-2-3_


> **Actual:**
> Updated the same imported input text ie _abc2 1 2 3_
> Here is the screenshot of the actual result
> image
> 


Kindly let me know if I have to add/modify anything in my reproducible steps.

I will be continuing with my further testing scenarios/ process.

**Comment by engcom-Alfa** [comment]
Tested the issue with PR updates and below are the scenario I have tried to test with.

1. **Imported with the simple product** keeping url_key with "simpprod 1 2 3", Noticed that the imported product is properly update to "simpprod-1-2-3"

2. **Imported with the configurable product** keeping url_key with "configprod 1 2 3", Noticed that the imported product is properly update to "configprod-1-2-3" (Associated simple products also not having any issues as such)

3. **Imported with the bundle product** keeping url_key with "bundprod 1 2 3", Noticed that the imported product is properly update to "bundprod-1-2-3" (Associated simple products also not having any issues as such)

4. **Imported with the downloadable product** keeping url_key with "downprod 1 2 3", Noticed that the imported product is properly update to "downprod-1-2-3" (Tried with attached file from device. Worked without any issues)

Completed my testing part, and there is no issue/ deviation I have noticed!

**Pull request merged**
