### PR TITLE
issue 37750: whitelisting *.google-analytics.com *.analytics.google.com

### LINKED ISSUE #37750: Google Analytics CSP Error https://region1.analytics.google.com
### Preconditions and environment

- Magento version
2.4.6-p1

### Steps to reproduce

Enable Google Analytics
View Website from the EU - Inspect and view CSP console errors.

### Expected result

No CSP errors

### Actual result

[Report Only] Refused to connect to 'https://region1.analytics.google.com/g/collect?v=28****** REMOVED ********' because it violates the following Content Security Policy directive: "connect-src www.google-analytics.com www.googleadservices.com analytics.google.com www.googletagmanager.com vimeo.com www.sandbox.paypal.com www.paypalobjects.com www.paypal.com pilot-payflowlink.paypal.com *.ideal-postcodes.co.uk *.doubleclick.net *.google-analytics.com 'self' 'unsafe-inline'".

### Additional information

See update from Google:
https://support.google.com/analytics/answer/12017362?sjid=7210281846540305633-EU

> EU data is collected in the EU
> Google Analytics 4 collects all data from EU-based devices (based on IP-geo lookup) through domains and on servers based in the EU before [forwarding traffic to Analytics servers for processing](https://support.google.com/analytics/answer/11598602).
> 
> If you currently use a [Content Security Policy (CSP)](https://developers.google.com/tag-platform/tag-manager/web/csp), update your configurations (img-src and connection-src directives) to allow the following domains used by Analytics:
> 
> *.google-analytics.com
> *.analytics.google.com

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by apedicdev**
Allowing *.google-analytics.com *.analytics.google.com to load needed scripts

Steps to reproduce as per the issue 37750
Enable Google Analytics
View Website from the EU - Inspect and view CSP console errors.

Expected result
No CSP errors

Actual result
```[Report Only] Refused to connect to 'https://region1.analytics.google.com/g/collect?v=28****** REMOVED ********' because it violates the following Content Security Policy directive: "connect-src www.google-analytics.com www.googleadservices.com analytics.google.com www.googletagmanager.com vimeo.com www.sandbox.paypal.com www.paypalobjects.com www.paypal.com pilot-payflowlink.paypal.com *.ideal-postcodes.co.uk *.doubleclick.net *.google-analytics.com 'self' 'unsafe-inline'".```

### CODE REVIEW

**Review by fredden — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi @apedicdev,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Enable Google Analytics
- View Website from the EU - Inspect and view CSP console errors


**Before:** :heavy_multiplication_x: 

Screenshot 2024-08-05 at 12 14 57




**After:** :heavy_check_mark: 


Screenshot 2024-08-05 at 13 20 23


Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

**Comment by apedicdev** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
@magento run Functional Tests B2B, Integration Tests, Static Tests

**Comment by engcom-November** [comment]
@magento run Functional Tests B2B

**Comment by engcom-November** [comment]
There are no repeating failures in Functional Tests B2B.

**Functional Tests B2B:**
**Run 1:**
image

**Run 2:**
image

Hence moving this to **Merge in progress**.

**Comment by engcom-Charlie** [comment]
Got some feedback on this PR's changes from @nathanjosiah, to look into those points moving this PR back to Extended Testing.

Feedback
image

@apedicdev, if possible, can you please look into this.

**Comment by apedicdev** [comment]
@engcom-Charlie I've checked the documentation, the img-src and connection-src directives should be changed so I'm going to updated the PR. Thanks @nathanjosiah for the heads up.

> EU data is collected in the EU
Google Analytics 4 collects all data from EU-based devices (based on IP-geo lookup) through domains and on servers based in the EU before [forwarding traffic to Analytics servers for processing](https://support.google.com/analytics/answer/11598602).

If you currently use a [Content Security Policy (CSP)](https://developers.google.com/tag-platform/tag-manager/web/csp), update your configurations (img-src and connection-src directives) to allow the following domains used by Analytics:

*.google-analytics.com
*.analytics.google.com

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
Got a green build so moving it to merge in progress.
image

**Pull request merged**
