### PR TITLE
URL rewrite fix while product website update using mass action

### PR DESCRIPTION
**Pull request by AnshuMishra17**
### Description
URL rewrite fix while product website update using mass action

### Fixed Issues
1. #21329: URL Rewrites are overwritten

### Manual testing scenarios
1. Added multiple websites.
2. Set URL key value at store level for any product.
3. Added the product in a new website using website update via mass action.
4. Removed product from a website using website update via mass action.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @AnshuMishra17. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by phoenix128 — APPROVED** [review]
Hello @AnshuMishra17 ,
thank you for your time and contribution.

**Comment by magento-engcom-team** [comment]
Hi @phoenix128, thank you for the review.
[ENGCOM-4386](https://jira.corp.magento.com/browse/ENGCOM-4386) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
✔️ QA passed

**Pull request merged**
