### PR TITLE
[Quote] API: Fixed issue "Can not update cart with a reserved order number like 000000651"

### PR DESCRIPTION
**Pull request by vasilii-b**
### Description (*)
Full description in magento/magento2#19101

### Fixed Issues (if relevant)
1. magento/magento2#19101

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
@vasilii-b would be *REALLY* nice to cover such case with api-functional test.

**Comment by vasilii-b** [comment]
Hey @orlangur,
you kinda force me to create functional test in the same PR ? 🤔 
Also, it's very interesting situation with this PR - has label Accept and you @orlangur requesting changes. How to understand that ?

**Comment by orlangur** [comment]
@vasilii-b,

> you kinda force me to create functional test in the same PR ? 🤔

what surprises you here?

This PR didn't get a single approve yet, so, `accept` label is set by mistake.

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Comment by vasilii-b** [comment]
Hi @magento-engcom-team, can you please describe why the Cleanup label was added ? This PR kinda fixes a serious bug when working with REST API. This "cleanup" allows developers to use the API as needed :)
Thank you!

**Pull request merged**
