### PR TITLE
Fixed issue #20030 :Customer EAV Decimal Attribute required allow 0

### PR DESCRIPTION
**Pull request by shikhamis11**
Fixed issue  #20030
Customer EAV Decimal Attribute required allow 0

**Preconditions (*)**

    Magento Version 2.2.6

**Steps to reproduce (*)**

    Create a new required customer attribute of type decimal with a default of 0 e.g.

'bal' => [
  'is_used_in_grid' => false,
  'is_visible_in_grid' => false,
  'is_filterable_in_grid' => false,
  'is_searchable_in_grid' => false,
  'type' => 'decimal',
  'label' => 'AR Balance',
  'input' => 'text',
  'required' => true,
  'default' => 0,
  'sort_order' => 202,
  'visible' => true,
  'system' => false,
  'validate_rules' => null,
  'position' => 202,
  'user_defined' => false,
  'frontend_class' => 'validate-number'
],

    Attempt to create a customer on front-end, or attempt to assign the value of 0 through the API.

**Expected result (*)**

    Customer attribute should be set with a 0 value.

**Actual result (*)**

    Both of these fail with [Attribute] is a required value.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by davidverholen** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @davidverholen. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @davidverholen, here is your [new Magento instance](https://pr-20130.instances.magento-community.engineering).
Admin access: [https://pr-20130.instances.magento-community.engineering/admin](https://pr-20130.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by davidverholen** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @davidverholen. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @davidverholen, here is your [Magento instance](https://i-20130-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20130-2-3-develop.instances.magento-community.engineering/admin](https://i-20130-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by davidverholen — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @davidverholen, thank you for the review.
[ENGCOM-3814](https://jira.corp.magento.com/browse/ENGCOM-3814) has been created to process this Pull Request

**Comment by davidverholen** [comment]
module for testing the change: [pr20130.tar.gz](https://github.com/magento/magento2/files/2739778/pr20130.tar.gz)

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
