### PR TITLE
Changes of GR(Greece) PostCode Pattern

### LINKED ISSUE #36676: Zip Code for Greece should not expect space
### Preconditions and environment

- Magento version
2.4.5

### Steps to reproduce

Go to cart or checkout, select Greece and insert postal code 12345

### Expected result

No warning

### Actual result

Zipcode gives warning

### Additional information

Solution (completely written out, just copy and paste!)

Replace zip countrycode NL with:

```
    <zip countryCode="GR">
        <codes>
            <code id="pattern_1" active="true" example="12345">^[0-9]{5}$</code>
        </codes>
    </zip>
```

in /app/code/Magento/Directory/etc/zip_codes.xml

### Release note

I'm 41 years old and I have never seen anyone write a zip code with a space in between here in Greece.
So getting an error/warning during ZIP Code input is definitely frustrating!
I have seen that several other countries face the same problem with this validation. For Greece I can ensure you that everybody writes the Zip code like this 12345 and not 123 45.
Even if you check the [wikipedia](https://el.wikipedia.org/wiki/%CE%9A%CE%B1%CF%84%CE%AC%CE%BB%CE%BF%CE%B3%CE%BF%CF%82_%CF%84%CE%B1%CF%87%CF%85%CE%B4%CF%81%CE%BF%CE%BC%CE%B9%CE%BA%CF%8E%CE%BD_%CE%BA%CF%89%CE%B4%CE%B9%CE%BA%CF%8E%CE%BD_%CF%84%CE%B7%CF%82_%CE%95%CE%BB%CE%BB%CE%AC%CE%B4%CE%B1%CF%82) you will see that actually there is a categorization defined by the first 2 digits and not 3, so in any case the current implementation is wrong. As far as I  know everybody writes all 5 digits together. You can check this also [here](https://www.taxidromikoskodikas.gr/tk/) which gives a list with all zip codes and they give them as continues 5 digit numbers.

I would like also to reference this issue which is similar and with the same solution.
#11898

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Vasudev-22**
### Description (*)

Change Pattern for GR PostCodes

### Related Pull Requests

Fixes for https://github.com/magento/magento2/issues/36676

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36676 Greece should allow zipcode without space

### Manual testing scenarios (*)

1. Buy Product
2. Go Checkout
3. Select Greece Country
4. Put PostCode: 12345 
Shopping-Cart-Error
Shopping-Cart

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Vasudev-22** [comment]
@magento run all tests

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by hostep** [comment]
@ishakhsuvarov: will this give issues for customers in Magento that already have stored addresses with zip codes in the old format if they want to check out again? Maybe this needs to be tested if it hasn't been yet before this gets approved?

It might be safer to allow both the old required format (with space) and the new format without space, so a regex like: `^[0-9]{3}\s?[0-9]{2}$`

Just my 2 cents, maybe my remark makes no sense...

**Comment by Vasudev-22** [comment]
> @ishakhsuvarov: will this give issues for customers in Magento that already have stored addresses with zip codes in the old format if they want to check out again? Maybe this needs to be tested if it hasn't been yet, before this gets approved?
> 
> It might be safer to allow both the old format (with space) and the new format (without space), so a regex like: `^[0-9]{3}\s?[0-9]{2}$`
> 
> Just my 2 cents, maybe my remark makes no sense...

@hostep , 
 Even the old customer need to show this warning/error message to update correctly.

**Comment by Vasudev-22** [comment]
> > Even the old customer need to show this warning/error message to update correctly.
> 
> Why? It might be annoying for existing customers if they see warnings even if their old orders worked perfectly fine with their old postcode.

Before it shown the postal-code in space format, that was an core issue and this is in wrong format of that country specific pin-code, so we correcting in our system, that's why we need to show them as warning to update it correctly as per your country pin-code.

**Comment by hostep** [comment]
I still would like to hear a second opinion on this, @ishakhsuvarov what do you think, or can you drag in somebody who knows a lot about this?

**Comment by cptX** [comment]
Hi, I have created the issue https://github.com/magento/magento2/issues/36676.
As a Greek, in my whole life I never say the PC written with a space. @hostep In my opinion we should not allow both with space and without to have a better and more consistent format across all customers.

**Comment by hostep** [comment]
Sure, I believe you guys, I was just concerned about causing potential problems/annoyances to existing customers of shops if they have entered their postal code in the old (wrong) format.

But it seems like nobody agrees here with my remarks, so feel free to continue with this PR 🙂

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**
- Buy Product
- Go Checkout
- Select Greece Country
- Put PostCode: 12345

**Before:** :heavy_multiplication_x: _Zipcode gives warning_
Screenshot 2023-06-16 at 2 09 45 PM



**After:** :heavy_check_mark:  _Now working fine_
Screenshot 2023-06-16 at 2 15 55 PM

Screenshot 2023-06-16 at 2 16 05 PM

Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by Vasudev-22** [comment]
@magento run all tests

**Comment by Vasudev-22** [comment]
@magento run Unit Tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
It looks like the bot had moved this PR from **Extended testing ** to **Ready for testing**. Hence, again moving this PR to 
 **Extended testing**

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Static Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Pull request merged**
