### PR TITLE
Issue/8382

### PR DESCRIPTION
**Pull request by PascalBrouwers**

### CODE REVIEW

**Comment by vrann** [comment]
@PascalBrouwers Thanks! can you please squash all commits and provide one commit with the meaningful description

**Comment by vrann** [comment]
@PascalBrouwers also, another discussion item. Can you change the version of monolog dependency in your project composer.json file? Should it really be done for all Magento application? My concern is that if some other Magento component depends on version 1.16, it will be broken with this change.

**Comment by PascalBrouwers** [comment]
Hi @vrann I'll squash those commits and edit the description. Let me check if any modules depend of 1.16 specifically.

**Comment by vrann** [comment]
@PascalBrouwers thank you for update. Magento works well with the new version. Accepting

**Comment by okorshenko** [comment]
@PascalBrouwers Thank you for your contribution to Magento 2 project! Your pull request has been successfully merged!

**Pull request merged**
