### PR TITLE
Resolve Shipping address information is lost in billing step & Updated new address not appear after add new at checkout payment method page issue22840 & 22112

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

Resolve : 
1. magento/magento2#22840: Updated new address not appear after add new at checkout payment method page
2. magento/magento2#22112: Shipping address information is lost in billing step

Solution: **validateFields** of Shipping Rate Validator should run in **Shipping Steps** only. Check the **div#shipping** is visible.
 
### Fixed Issues (if relevant)

1. magento/magento2#22840: Updated new address not appear after add new at checkout payment method page
2. magento/magento2#22112: Shipping address information is lost in billing step

### Manual testing scenarios (*)

1. Login to account >> Add some addresses in address book
2. Add product to cart
3. Checkout >> Shipping >> Select any address
4. Go to review and payment page
5. Payment method >> Uncheck the "My billing and shipping address are the same" checkbox
6. Select New address(Add New Address) from drop-down
7. Update address 
8. check the "My billing and shipping address are the same" check box

Results:
1. "Ship to" information is not modified
2. Billing address is displayed as the same shipping address

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-23757.instances.magento-community.engineering).
Admin access: [https://pr-23757.instances.magento-community.engineering/admin](https://pr-23757.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by lamasfoker** [comment]
I think this is the right way to fix the bug in shipping-rates-validator.js at line 148
`if (formPopUpState.isVisible()) {`
You have to rid of the esclamation mark, because is when the popup is displayed that must there be the validation

**Pull request closed without merging**
