### PR TITLE
optimized configurable product indexing

### LINKED ISSUE #14443: Final min_price and max_price calculation on configurable product with special price
### Preconditions

1. Magento 2.3 or Magento 2.1
2. Have a configurable product with all associated product prices 288 and add for each associated simple product special price 98. Set a special date from lower than current date.

### Steps to reproduce

1. Reindex catalog_product_price indexer
2. 
3. 

### Expected result

1. Sort by price should work on category page with product list

### Actual result

1. Sort by price doesn't work because it uses negative values from min_price column.
max_price column is broken too (-92 value)
SELECT * FROM `catalog_product_index_price` WHERE `entity_id` = [configurable product ID].

There is a weird line of code in:
vendor/magento/module-configurable-product/Model/ResourceModel/Product/Indexer/Price/Configurable.php,
function _applyConfigurableOption:

```
$select->columns(
            [
                'min_price' => new \Zend_Db_Expr('i.min_price - i.orig_price + io.min_price'),
                'max_price' => new \Zend_Db_Expr('i.max_price - i.orig_price + io.max_price'),
                'tier_price' => 'io.tier_price',
            ]
);
```

If I'm reading this:
final min price = min_price_1 + min_price_2 - normal/original price.
On my example min price = 98 + 98 - 288 = **- 92**

### LINKED ISSUE #15609: Magento 2.2.4 Product sorting list by price on category page wrong when configurable product has special price set by mass action.
### Preconditions

1.  Magento 2.2.4

### Steps to reproduce

1. Add a special price to configurable product using mass action.
2. Re-index price

### Expected result

1. It is expected that catalog category page show products sorted by price correctly, taking account that special price of the configurable product should not make difference to price indexer process

### Actual result

1. Indexer process is using configurable product special price to update `catalog_product_index_price` letting the category page sorting products in the wrong way.
issue_magento

### LINKED ISSUE #24535: Negative prices in layered navigation
### Preconditions (*)

1. 2.3.0

### Steps to reproduce (*)

1. Re-reporting https://github.com/magento/magento2/issues/14443 as this has been closed but is not fixed.
2. Multi store setup, different discounts for different stores.

### Expected result (*)

1. Layered navigation shows correct price ranges

### Actual result (*)

1. Layered navigation shows negative price ranges

```
mysql> select * from catalog_product_index_price where min_price < 0 limit 10;
+-----------+-------------------+------------+--------------+---------+-------------+-----------+-----------+------------+
| entity_id | customer_group_id | website_id | tax_class_id | price   | final_price | min_price | max_price | tier_price |
+-----------+-------------------+------------+--------------+---------+-------------+-----------+-----------+------------+
|     44489 |                 2 |          3 |            2 | 69.0000 |     30.5000 |   -8.0000 |   -8.0000 |    30.5000 |
|     44489 |                 6 |          3 |            2 | 69.0000 |     30.7200 |   -7.5600 |   -7.5600 |    30.7200 |
|     34227 |                 2 |          1 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
|     34227 |                 2 |          3 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
|     40003 |                 2 |          1 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
|     40003 |                 2 |          3 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
|     40005 |                 2 |          1 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
|     40005 |                 2 |          3 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
|     40011 |                 2 |          1 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
|     40011 |                 2 |          3 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
+-----------+-------------------+------------+--------------+---------+-------------+-----------+-----------+------------+
10 rows in set (0.01 sec)
```

### LINKED ISSUE #24953: Wrong price indexed for configurable/composite products
### Preconditions (*)
magento 2.3

1.
2.

### Steps to reproduce (*)

1. Edit `price` or `special_price` on configurable product from mass action grid or saving attribute via resource model `$this->productResource->saveAttribute($product, 'price');`  or 
`$this->productResource->saveAttribute($product, 'special_price');` 
2. Run reindex from cron (mb. CLI reindex as well)
3. See the price from attributes appeared on product grid 
4. See the price from attributes in columns `price` and `final_price` in the table `catalog_product_index_price`
5. Then save configurable product from admin edit page
6. See `null`  value saved for price attribute in `catalog_product_entity_decimal`
7. Wait for price reindex from cron (mb. CLI reindex as well)
8. Repeat step 4 and see `0` saved in columns `price` and `final_price` for edited configurable product

to find prices saved for configurable product use this SQL

```
SELECT decimal2.*
FROM catalog_product_entity
       inner join catalog_product_entity_decimal decimal2 on catalog_product_entity.entity_id = decimal2.entity_id and
                                                             attribute_id in (SELECT attribute_id
                                                                              from eav_attribute
                                                                              where attribute_code in
                                                                                    ('price', 'special_price'))
where type_id = 'configurable';
```

### Expected result (*)

1. Price never saved for a configurable product in `catalog_product_entity_decimal` table from any save point e.g. `resource model`, `repository`
2. Price indexed correctly in `catalog_product_index_price` (data for composite products should be calculated based on child products) e.g. final_price = min_price, price = max_price attribute values from `catalog_product_entity_decimal` should be ignored

### Actual result (*)

1. Still possible to save `price` and `special_price` for configurable/composite product in `catalog_product_entity_decimal` table
2. Wrong calculation of columns `price` and `final_price` in the `catalog_product_index_price` table

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

optimized configurable product indexing (Fixed Negative min_price and max_price issue after migration)
### Fixed Issues (if relevant)

Fixes #24535
Fixes #15609
Fixes #14443
Fixes #24953

### Manual testing scenarios (*)

1. 

### Questions or comments

Testing with sample data min_price equation calculate like this

min_price = i.min_price - i.price + io.min_price
which become 44 = 0 - 0 + 44 

i.max_price - i.price + io.max_price
44 = 0 - 0 + 44 
there is no meaning to  use configurable price and min_price in the calculation
(Magento2 Not allow to add price or special price it's by default 0 )

Fixed Negative min_price and max_price issue after migration
Magento1 allows adding price and special prices for the configurable product which create an issue for calculating min_price and max_price in Magento2

with the above solution, indexing becomes faster to reduce calculation for each product min and max price and fixed

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ravi-chandra3197** [comment]
Resolve this issue using single  PR #24535, #15609, #14443

Negative prices in layered navigation #24535


Magento 2.2.4 Product sorting list by price on category page wrong when configurable product has special price set by mass action. #15609


Final min_price and max_price calculation on configurable product with special price #14443

**Comment by dhorytskyi** [comment]
The mentioned expression doesn't result in "0 - 0 + X" every time, i.price field contains base product price, but i.min_price field contains base price plus price of required custom options.
With those changes, minimal price of configurable product will not contain price of required custom options. As a result, minimal price will not be actual minimal price of configurable product and it will be inconsistent with minimal price of other product types.

**Comment by ravi-chandra3197** [comment]
> The mentioned expression doesn't result in "0 - 0 + X" every time, i.price field contains base product price, but i.min_price field contains base price plus price of required custom options.
> With those changes, minimal price of configurable product will not contain price of required custom options. As a result, minimal price will not be actual minimal price of configurable product and it will be inconsistent with minimal price of other product types.

Hello @dhorytskyi 
in Magento2 there is no base price option for a configurable product, old expression conflict when the configurable product has a base price.
as a normal situation, the configurable product has no price option in M2 but when you migration with M1 Data it will create an issue.

step-1: create any configurable product in M1 set price and special price
step-2: perform migration in M2 so we get the same product in M2
step-3: run reindexing
step-4: check the 'catalog_product_index_price' table in the database it has a 
negative value for configurable products.
in frontend filter by price not working as expected due to negative price

negative-price

**Comment by MichaelThessel** [comment]
@akaplya, any chance you could review this? It would be great to get this resolved. 

At least in my case this resolved the issue (#24535)

**Comment by merance2000** [comment]
We are having the same issue - I thought it was because of M1 import but other items updated via api are also showing the issue .

**Comment by MichaelThessel** [comment]
This has been pending for 6 months now. Any chance this can be merged?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @ravi-chandra3197,

1. Could you review failing integration tests? 
According to test results - seems like your change does some regression in specific cases and solution should be improved.

2. After fixing failing existing tests, could you cover your changes with some kind of test?

**Comment by ravi-chandra3197** [comment]
Hello @ihor-sviziev 

I am working on failing integration tests

**Comment by ihor-sviziev** [comment]
@ravi-chandra3197 will you be able to update your PR? Or maybe you have some questions / need some help?

**Comment by ravi-chandra3197** [comment]
@ihor-sviziev I have need help to fix integration tests.

**Comment by ihor-sviziev** [comment]
@engcom-Charlie could you help with failing tests?

**Comment by engcom-Hotel** [comment]
Hello @ravi-chandra3197, will try to help you with Integration Tests.

**Comment by ihor-sviziev** [comment]
@engcom-Hotel make sure that these changes didn't break some functionality.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Hello @ravi-chandra3197 @ihor-sviziev.
I have checked the integration test and it is fine.
Unfortunately, the offered solution is not perfect. As a result prices calculation process doesn't work properly. It is quite risky optimization.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @ravi-chandra3197,
Could you update your solution to be compatible with the cases when tests are failing?

**Comment by sidolov** [comment]
`Risk: high` since the configurable indexation process os affected

**Comment by ihor-sviziev** [comment]
Looks like we have another PR that fixes the same issue. https://github.com/magento/magento2/pull/26810

**Comment by ihor-sviziev** [comment]
@ravi-chandra3197 will you be able to update your PR?

**Comment by ihor-sviziev** [comment]
@ravi-chandra3197  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
