### PR TITLE
The issue #6272 'Changing sample for downloadable product failure' ha…

### PR DESCRIPTION
**Pull request by sichensol**
…s been fixed

### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/6272

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14706) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=14706) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: rogyar<br/>:x: molneek

**Comment by rogyar** [comment]
@molneek Thank you for your contribution. Plase, consider also creating backports for 2.2 and 2.1 versions.

**Comment by rogyar** [comment]
Unfortunately, we have a failing API-functional test here. It's not being executed by travis but can be executed manually. 

```
1) Magento\Downloadable\Api\ProductRepositoryTest::testUpdateDownloadableProductSamplesWithNewFile
Exception: {"messages":{"error":[{"code":500,"message":"Server internal error. See details in report api\/577551418110"}]}}

"Fatal Error: 'Uncaught TypeError: Argument 1 passed to 
Magento\\Downloadable\\Model\\File\\ContentUploader::upload() 
must implement interface Magento\\Downloadable\\Api\\Data\\File\\ContentInterface, \null given, called in 
app\/code\/Magento\/Downloadable\/Model\/SampleRepository.php 
on line 233
```

**Comment by sichensol** [comment]
@rogyar Has been updated that code. Please run tests again

**Comment by rogyar** [comment]
Unfortunately, the API-functional tests are still failing but with another issue:

```
Magento\Downloadable\Api\ProductRepositoryTest::testUpdateDownloadableProductSamplesWithNewFile
Failed asserting that false is true.
```

**Comment by rogyar** [comment]
@molneek I'm closing this PR due to inactivity. Feel free to reopen it if you decide to proceed. Thank you

**Pull request closed without merging**
