### PR TITLE
[MFTF] Refactoring AdminSortingByWebsitesTest

### LINKED ISSUE #31442: [Issue] [MFTF] Refactoring AdminSortingByWebsitesTest
This issue is automatically created based on existing pull request: magento/magento2#31371: [MFTF] Refactoring AdminSortingByWebsitesTest

---------
### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
1. Create a custom website
2. Assign the created website to a product
3. Go to Catalog->Products
4. Sort the Products grid by the "Website" column asc
5. Check if the product in the first row is assigned to Main Website
6. Sort the Products grid by the "Website" column desc
7.  Check if the product in the first row the created custom website

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
1. Create a custom website
2. Assign the created website to a product
3. Go to Catalog->Products
4. Sort the Products grid by the "Website" column asc
5. Check if the product in the first row is assigned to Main Website
6. Sort the Products grid by the "Website" column desc
7.  Check if the product in the first row the created custom website

### Resolved issues:
1. [x] resolves magento/magento2#31442: [MFTF] Refactoring AdminSortingByWebsitesTest

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8583](https://jira.corp.magento.com/browse/ENGCOM-8583) has been created to process this Pull Request

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
QA not applicable

**Pull request merged**
