### PR TITLE
Enable sort order to product Custom options

### LINKED ISSUE #28153: Impossible to change sort order of custom option values over several pages in product edit view
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Create a new simple product in the backend
2. Add a custom option of type drop-down
3. Add 21 values, the last value appears on a new page.
4. Try to move the last value to another position on the first page.

### Expected result (*)

1. I would assume that it is possible to sort the values using the drag and drop functionality, even over several pages.

### Actual result (*)

1. It is not possible to move any value to another page using the drag and drop functionality.

### PR DESCRIPTION
**Pull request by Kannakiraj123**
### Description (*)
Change sort order of custom option values over several pages in product edit view

### Related Pull Requests
 Enabled the sort order field to custom option and custom option values.

### Fixed Issues (if relevant)
1. Fixes #28153 

### Manual testing scenarios (*)

1. Create a new simple product in the backend
3. Add a custom option of type drop-down
4. Add 21 values, the last value appears on a new page.
5. Try to move the last value to another position on the first page.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Kannakiraj123** [comment]
@magento run all tests

**Comment by Kannakiraj123** [comment]
@magento run all tests

**Comment by Kannakiraj123** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, WebAPI Tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @Kannakiraj123,

Thanks for the contribution!

It seems the build failures are due to PR changes. Please resolve them.

Thanks

**Comment by Kannakiraj123** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @Kannakiraj123,

Please look into the Functional test failures as well. It seems the fails are due to PR changes.

Thanks

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@Kannakiraj123 can you please have a look at functional build failure PR changes causing multiple build failure.
In order to move further please resolve all build failure.

**Comment by engcom-Echo** [comment]
@Kannakiraj123 Closing this PR for now as there are are multiple failure caused by PR changes.
In Order to move ahead we need green build.

Hence Closing for now.
Please feel free to reopen when you are ready

**Pull request closed without merging**
