### PR TITLE
[AC-6980] "Integration not secure" warning showing in list of integra…

### LINKED ISSUE #36407: "Integration not secure" warning showing in list of integration, if field values of "Callback URL" and "Identity link URL" are empty.
### Preconditions and environment

    Magento version 2.4.5
    PHP 8.1 (FPM)
    Apache2.4
    Ubuntu 20.04.5 LTS

### Steps to reproduce

1. Login to admin panel
2. Go to "System >> Extensions >> Integrations"
3. Add New Integration.
4. Fill up require fields but **fields "Callback URL" and "Identity link URL" leave empty** and Save.
5. Now error displaying as mentioned in below  attachment:
screenshot

### Expected result

No error on integration list page as both fields are empty and optional.

### Actual result

Error found on integration list page.

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by adamphh**
[AC-6980] "Integration not secure" warning showing in list of integration, if field values of "Callback URL" and "Identity link URL" are empty. #36407

### Fixed Issues (if relevant)

1. Fixes magento/magento2 #36407 

### Manual testing scenarios (*)

1. Login to admin panel
2. Go to "System >> Extensions >> Integrations"
3. Add New Integration.
4. Fill up require fields but fields "Callback URL" and "Identity link URL" leave empty and Save.
5. Now error displaying as mentioned in below attachment:
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by adamphh** [comment]
@magento give me test instance

**Comment by adamphh** [comment]
@magento run Unit Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @adamphh,

Thanks for the contribution!

Please cover the changes with some automated tests in accordance with [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1).

Thanks

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Comment by Den4ik** [comment]
@magento run Functional Tests CE

**Review by Den4ik — APPROVED** [review]
✅ Approved.
Changes looks ok.
Failed functional test is not related to the changes

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi @adamphh,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

1. Login to admin panel
2. Go to "System >> Extensions >> Integrations"
3. Add New Integration.
4. Fill up require fields but fields "Callback URL" and "Identity link URL" leave empty and Save.


**Before:** :heavy_multiplication_x: 

Screenshot 2023-11-03 at 12 17 39 PM



**After:** :heavy_check_mark:  


Screenshot 2023-11-03 at 2 28 54 PM



Builds are failed. Hence, moving this PR to **Extended Testing**.

**Comment by engcom-Charlie** [comment]
It seems bot moved the PR to Testing from Extended Testing hence moving it back.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE, Integration Tests, Static Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Static Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Static Tests

**Comment by engcom-Charlie** [comment]
The functional B2B test failures are different in recent 2 commits. The tests are not failing because of PR changes or affected by PR changes.

**Functional B2B Run1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36626/63d1d3baba07db5891cd7f7e946ca693/Functional/allure-report-b2b/index.html#categories
image

**Functional B2B Run2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36626/183d554fda534c1507350775fb6cfac9/Functional/allure-report-b2b/index.html#categories
image

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests, WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run WebAPI Tests, Integration Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE, Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B , Functional Tests EE

**Comment by engcom-Hotel** [comment]
Failed functional test EE seems flaky to me, the failures are different in 2 separate runs:

image

image

And for the failed static test, we have a discussion internally, this test should be disabled in one of the next PRs, so we may skip it for now.

Hence moving this PR further.

**Pull request merged**
