### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pardyalbert**
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24175) <br/>All committers have signed the CLA.

**Comment by pardyalbert** [comment]
I changed the Header text to header 1 and 3 Respectively

**Comment by kalpmehta** [comment]
Thanks @albannytechnologies for your contribution. May I know why this change was necessary?

**Comment by sidolov** [comment]
@albannytechnologies I'm closing this PR since we didn't see any reason to change headers in the README.MD file. Feel free to reopen PR if you wish to continue.

**Pull request closed without merging**
