### PR TITLE
[MFTF] use action group to click save button

### PR DESCRIPTION
**Pull request by Usik2203**
This PR uses `AdminProductFormSaveButtonClickActionGroup` to click to Save button of product form

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE
Functional Tests EE,
Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Review by lbajsarowicz — APPROVED** [review]
I really appreciate your great job! Thank you!

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7773](https://jira.corp.magento.com/browse/ENGCOM-7773) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
**Notice:** QA not applicable

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@magento Functional Tests CE

**Comment by slavvka** [comment]
@magento run Functional Tests CE

**Pull request merged**
