### PR TITLE
GraphQL cannot add product with customizable option to cart #37599

### LINKED ISSUE #37599: GraphQL cannot add product with customizable option to cart
### Steps to reproduce
1. Go to admin panel > Catalog > Products
1. Create a simple product (Joust Duffle bag)
1. Create a custom option for Joust Duffle Bag
1. Use next graphql queries
1.  Create a empty cart
```java
mutation {  createEmptyCart} 
```

Get product options information
```
{
  products(filter: {sku: {eq: "24-MB01"}}) {
    items {
      uid
      name
      sku
      __typename
      ... on CustomizableProductInterface {
        options {
          title
          required
          sort_order
          uid
          ... on CustomizableFieldOption {
            textField: value {
              sku
              price
            }
          }
          ... on CustomizableDropDownOption {
            dropDown: value {
              sku
              price
            } 
          }
        }
      }
    }
  }
}
```
Add product to cart using custom option
```
mutation {
  addProductsToCart(
    cartId: "`cart_id`"
    cartItems: <
      {
        quantity: 1
        sku: "24-MB01"
        entered_options: [{
          uid: "Y3VzdG9tLW9wdGlvbi8x"
          value: "some content here!"
        }]
      }
    ]
  ) {
    cart {
      items {
        product {
          name
          sku
        }
        ... on SimpleCartItem {
          customizable_options {
            customizable*option*uid
            label
            values {
              customizable*option_value*uid
              value
            }
          }
        }
        quantity
      }
    }
    user_errors {
      code
      message
    }
  }
} 
```

 ## Get the response returned

### Actual results

currently, customizable_options are empty

```
{
  "data": {
    "addProductsToCart": {
      "cart": {
        "items": [
          {
            "product": {
              "name": "Joust Duffle Bag",
              "sku": "24-MB01"
            },
            "customizable_options": [],
            "quantity": 1
          }
        ]
      },
      "user_errors": []
    }
  }
}
```
 
### Expected results

```
{
  "data": {
    "addProductsToCart": {
      "cart": {
        "items": [
          {
            "product": {
              "name": "Joust Duffle Bag",
              "sku": "24-MB01"
            },
            "customizable_options": [
              {
                "customizable*option*uid": "Y3VzdG9tLW9wdGlvbi8x",
                "label": "option test1",
                "values": [
                  {
                    "customizable*option_value*uid": "Y3VzdG9tLW9wdGlvbi8x",
                    "value": "some content here!"
                  }
                ]
              }
            ],
            "quantity": 1
          }
        ]
      },
      "user_errors": [>
    }
  }
}
```

### PR DESCRIPTION
**Pull request by shomiadarshlt**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#37599

### Manual testing scenarios (*)

- Go to admin panel > Catalog > Products
- Create a simple product (Joust Duffle bag)
- Create a custom option for Joust Duffle Bag
- Create a empty cart using graphql
mutation { 
  createEmptyCart
} 

- Get product options information
{
  products(filter: {sku: {eq: "24-MB01"}}) {
    items {
      uid
      name
      sku
      __typename
      ... on CustomizableProductInterface {
        options {
          title
          required
          sort_order
          uid
          ... on CustomizableFieldOption {
            textField: value {
              sku
              price
            }
          }
          ... on CustomizableDropDownOption {
            dropDown: value {
              sku
              price
            } 
          }
        }
      }
    }
  }
}

- Add product to cart using custom option
mutation {
  addProductsToCart(
    cartId: "62zbf0JBpn9s3U7C2iIze2sWidmMU6Es"
    cartItems: [
      {
        quantity: 1
        sku: "24-MB01"
        entered_options: [{
          uid: "Y3VzdG9tLW9wdGlvbi8y"
          value: "test"
        }]
      }
    ]
  ) {
    cart {
      items {
        product {
          name
          sku
        }
        ... on SimpleCartItem {
          customizable_options {
            customizable_option_uid
            label
            values {
              customizable_option_value_uid
              value
            }
          }
        }
        quantity
      }
    }
    user_errors {
      code
      message
    }
  }
}

- The response will have the array customizable_options fetched  with data 
{
    "data": {
        "addProductsToCart": {
            "cart": {
                "items": [
                    {
                        "product": {
                            "name": "Joust Duffle bag",
                            "sku": "24-MB01"
                        },
                        "customizable_options": [
                            {
                                "customizable_option_uid": "Y3VzdG9tLW9wdGlvbi8y",
                                "label": "test",
                                "values": [
                                    {
                                        "customizable_option_value_uid": "Y3VzdG9tLW9wdGlvbi8y",
                                        "value": "test"
                                    }
                                ]
                            }
                        ],
                        "quantity": 1
                    }
                ]
            },
            "user_errors": []
        }
    }
}

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by shomiadarshlt** [comment]
@magento run all tests

**Comment by shomiadarshlt** [comment]
https://github.com/magento run all tests

**Comment by shomiadarshlt** [comment]
@magento run all tests

**Comment by shomiadarshlt** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
This PR already merged and shouldn't have pending review status

**Pull request merged**
