### PR TITLE
magento#26745 add method setAdditionalInformation to OrderPaymentInte…

### LINKED ISSUE #13222: Magento\Sales\Api\Data\OrderPaymentInterface is missing a setter for 'additional_information' data
When trying to run a payed order through a \Magento\Framework\Webapi\ServiceOutputProcessor it will fail because the 'additional_information' data has no corresponding setter defined in the interface.

### Preconditions
1. PHP7
2. CE 2.2.2

### Steps to reproduce
1. Create a payed order
2. Try to process the order with a \Magento\Framework\Webapi\ServiceOutputProcessor: 

```php
$serviceOutputProcessor->process(
            $order,
            'Magento\Sales\Api\OrderRepositoryInterface',
            'get'
        );
```

### Expected result
1. You get don't get any errors

### Actual result
1. Exception is thrown:

`Property "AdditionalInformation" does not have corresponding setter in class "Magento\Sales\Api\Data\OrderPaymentInterface". `

The ServiceOutputProcessor tries to serialize the order object based on the (api) interfaces. When it reaches the serialization of the Payment object in the order the processor will fail when the object has data for 'additional_information' (normally this contains the payment method name).

The Magento\Sales\Api\Data\OrderPaymentInterface should contain a setAdditionalInformation function definition which will be implemented by the setAdditionalInformation function defined in Magento\Payment\Model\InfoInterface

### LINKED ISSUE #26745: OrderPaymentInterface is missing setAdditionalInformation()
### Summary
OrderPaymentInterface misses a setter for additional_information: this is an inconsistency between its schema declaration and the real properties accepted.

### Examples
If you declare an API interface that accepts as a parameter an object of the type OrderPaymentInterface, additional_information property should be accepted.
 The result is this error:
```Property "AdditionalInformation" does not have accessor method "setAdditionalInformation" in class "Magento\Sales\Api\Data\OrderPaymentInterface".```
Forcing developer to unset additional_information before sending this object

A validation of this schema can be triggered in this way:
- create an integration token in admin with permission over Sales > Order > Operation > Create
- use swagger interface to test this endpoint  salesOrderRepositoryV1SavePutBody
- the exception 
``` Property "AdditionalInformation" does not have accessor method "setAdditionalInformation" in class "Magento\Sales\Api\Data\OrderPaymentInterface".``` will be triggered due the fact that additional_information property is defined (getAdditionalInformation() exists and swagger use that to define its sample call).

### Proposed solution
Implement a setter setAdditionalInformation() in OrderPaymentInterface: model using this interface have already got this method.

### PR DESCRIPTION
**Pull request by antoninobonumore**
### Description (*)
No setter for additional_information in OrderPaymentInterface is defined: this is an inconsistency between its schema declaration and the real properties accepted.

### Fixed Issues (if relevant)
- Fixes magento/magento2#26745: OrderPaymentInterface is missing setAdditionalInformation() 
- Fixes magento/magento2#13222: Magento\Sales\Api\Data\OrderPaymentInterface is missing a setter for 'additional_information' data

### Manual testing scenarios (*)
- create an API interface accepting OrderPaymentInterface
- try to set an object with a property additional_information with a value

### Questions or comments
IMO this looks like an elephant in the room since this definition is missing from a long time in the definition of this interface

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hostep** [comment]
Let's hope this one makes it in, [a previous attempt](https://github.com/magento/magento2/pull/13455) for fixing this got stopped because it would be backwards incompatible, but now the code for Magento 2.4 is still open, it can probably be accepted?

@rogyar ?

**Comment by antoninobonumore** [comment]
@hostep this is also because I implemented this on this release line rather than 2.2 and 2.3

**Comment by rogyar** [comment]
Hi. For 2.4 (as a minor version release) we may make backward-incompatible changes except changes to the functional structures marked as `@api`. We may not modify `@api` class or interfaces since such changes might be very critical for the existing setups.

**Comment by hostep** [comment]
@rogyar: The version 2.4 is not the correct one here, we should be talking about the version of the  Magento Sales module, which is at [version 102.0.4](https://github.com/magento/magento2/blob/2.3.4/app/code/Magento/Sales/composer.json#L51) in Magento 2.3.4
I'm assuming in Magento 2.4, that version will get bumped to 103.0.0, but I don't know that for certain?

**Comment by rogyar** [comment]
Hi @hostep. I don't have this information either. 

But the main point is adding public methods to interface/API implementations is prohibited for both patch and minor releases (so it's prohibited in any case).

**Comment by hostep** [comment]
@rogyar: A bump from 102.0.4 to 103.0.0 is a major version bump, right?

**Comment by hostep** [comment]
@rogyar: after asking around a bit in #appdesign on the Slack workspace of Magento, it looks like this should be no problem to merge into 2.4-develop.
According to https://devdocs.magento.com/guides/v2.3/extension-dev-guide/versioning/codebase-changes.html, adding a new method to an interface marked with `@api` can even be done within a MINOR version bump (102.0.4 => 102.1.0 for example).

So I would like to ask you to reconsider, thanks! 🙂

**Comment by drew7721** [comment]
I would suggest implementing the setter and getter for as public functions in the `Sales\Model\Order\Payment` class using the constant `OrderPaymentInterface::ADDITIONAL_INFORMATION` as it's done for all the others. Also, I would like to see the documentation related to the difference between `ADDITIONAL_DATA` and `ADDITIONAL_INFORMATION`

**Comment by rogyar** [comment]
Hi @hostep. After a recent discussion, I must admit that you are right. I'm approving this change. Thank you

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7037](https://jira.corp.magento.com/browse/ENGCOM-7037) has been created to process this Pull Request
:eight_spoked_asterisk: @rogyar, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:**
before

**After:**
after

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Comment by kanduvisla** [comment]
It's good to see that this property is added, but how can we deal with the discrepancies between the 2 different API's that describe this implementation?

If you look at `\Magento\Sales\Model\Order\Payment` it extends 2 interfaces: `\Magento\Payment\Model\InfoInterface` and `\Magento\Sales\Api\Data\OrderPaymentInterface` which both have a different `@api` setup for these methods:

`\Magento\Payment\Model\InfoInterface`:

    // @param string $key
    public function setAdditionalInformation($key, $value = null);
    public function getAdditionalInformation($key = null);

`\Magento\Sales\Api\Data\OrderPaymentInterface`:

    // @param string[] $additionalInformation
    public function setAdditionalInformation($additionalInformation);
    public function getAdditionalInformation();

This might require some attention because it's quote confusing now. It looks like the `InfoInterface` is the API that we wanted on the `OrderPaymentInterface` all along...

**Pull request merged**
