### PR TITLE
[Fixed-20788: Listing page no equal spacing in product in list view]

### PR DESCRIPTION
**Pull request by hitesh-wagento**
### Description (*)

Listing page no equal spacing in product in list view #20788

### Fixed Issues (if relevant)

1. magento/magento2#20788: Listing page no equal spacing in product in list view.

### Manual testing scenarios (*)

1. Frontend -> open any product category Listing page
2. Click on List view

### Expected result (*)

actual

### Actual result (*)

actual 1

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @hitendra-wagento. Thanks for collaboration. Please fix static tests.

**Comment by hitesh-wagento** [comment]
Hi @VladimirZaets 

Can you please suggest me how can I resolve Static Tests build issue and how to check in local.

Thanks

**Comment by hitesh-wagento** [comment]
Hi @VladimirZaets 

I have fixed static tests error.

Thanks

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5148](https://jira.corp.magento.com/browse/ENGCOM-5148) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Before:**

before

**After:**

after

**Pull request merged**
