### PR TITLE
Fixed Responsive Design, Footers bottom of screen on mobile devices

### PR DESCRIPTION
**Pull request by chirag-wagento**
### Description
Fixed Responsive Design in Footers bottom of screen on mobile devices.

### Fixed Issues (if relevant)

1. magento/magento2#15118: 
Responsive Design, Footers do not snap to bottom of screen on mobile devices 

### Manual testing scenarios

1. Check responsive footer

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @chirag-wagento. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on Pull Request changes
- `@magento-engcom-team give me new test instance` - deploy **NEW** test instance based on Pull Request changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy Vanilla Magento instance for Issue or Pull Request

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by orlangur** [comment]
Commit history is incorrect. Please check it prior to PR creation.

**Comment by chirag-wagento** [comment]
Hello @orlangur 

I was close my old PR and created new PR with new coding. Because  Some coding issue in my old  PR.
So sorry not getting you can you please explain me in brief.

Thanks

**Comment by DanielRuf** [comment]
You can create a new branch from 2.2-develop, run `git cherry-pick b42f77a327ddcd94bd4b1f7f45214721b66976a2` and push it.

This here looks like a wrong rebased branch with mixed histories.

**Comment by orlangur** [comment]
@chirag-wagento well, when you create pull request you can see that changes are incorrect (there are unrelated changes) and also there are a lot of useless merge commits.

I'm not sure what you trying to achieve by merging pull requests in your own fork but obviously it does not work well.

**Comment by DanielRuf** [comment]
I observe that other *-wagento accounts do the same. But this produces much overhead and extra work. Please just create your own PRs on 2.2-develop and do not try to back/forward migrate the PRs of others or do their work as many of your PRs are unclean and contain mixed histories.

**Pull request closed without merging**
