### PR TITLE
#16298 this sould fix the issue and fix a test fails on https://githu…

### PR DESCRIPTION
**Pull request by sichensol**
…b.com/fratob85/magento2/tree/fix-switch-to-incorrect-store

### Fixed Issues (if relevant)

1. magento/magento2#16298: Magento sometimes doesn't select the correct store if the scope code is null
2. Fixed PR https://github.com/fratob85/magento2/tree/fix-switch-to-incorrect-store

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=17975) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=17975) before we can accept your contribution.<br/><hr/>**Sergey Petrichenko** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by magento-engcom-team** [comment]
Hi @molneek. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
Hi @molneek. Please, sign the CLA so we can process your PR. Thank you.

**Comment by molneek** [comment]
Hi @rogyar, I've tried this several times, but cla was not signed

**Pull request closed without merging**
