### PR TITLE
Fixed: Login as customer opt-in checkbox not translatable

### LINKED ISSUE #32329: Login as customer opt-in checkbox not translatable
### Preconditions (*)

1. Have Magento 2.4.2 with multiple website and store view in different languages

### Steps to reproduce (*)

1. In back office >  Stores > Configuration >Customers > Login as Customer
2. Look at the scope for fields "Title for Login as Customer opt-in checkbox" and "Login as Customer checkbox tooltip" 

### Expected result (*)

1. Fields "Title for Login as Customer opt-in checkbox" and "Login as Customer checkbox tooltip" must be for scope "Store view" So you can translate for storeview

### Actual result (*)

1. Fields "Title for Login as Customer opt-in checkbox" and "Login as Customer checkbox tooltip" are for scope "Website" So you can't translate for storeview
image

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by ejaz-alam**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#32329

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by shikhamis11** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
Hi

I am closing this PR for now as it seems like it has become stale and still needs work.

Please feel free to reopen if you wish to continue.

Thanks!

**Comment by hostep** [comment]
It's really sad that this one got closed as it's a quick fix for a real problem. I don't agree with the hard requirement of adding functional tests to merge it in, it should just have been accepted as is in my opinion ...

**Comment by ejaz-alam** [comment]
> @ejaz-alam thank you for creating Pull Request.
> Please cover the changes with Functional Test

@shikhamis11 , need your help in this.

**Comment by hostep** [comment]
@ejaz-alam: we believe your PR needs some additional changes on these 2 lines:

- https://github.com/ejaz-alam/magento2/blob/b52c7692bd47ab996b95d988ed1cfb68adc536ff/app/code/Magento/LoginAsCustomerAssistance/Model/Config.php#L45
- https://github.com/ejaz-alam/magento2/blob/b52c7692bd47ab996b95d988ed1cfb68adc536ff/app/code/Magento/LoginAsCustomerAssistance/Model/Config.php#L56

That needs to be updated to `ScopeInterface::SCOPE_STORE`

And the 2 lines https://github.com/ejaz-alam/magento2/blob/b52c7692bd47ab996b95d988ed1cfb68adc536ff/app/code/Magento/LoginAsCustomerAssistance/etc/adminhtml/system.xml#L10-L11 needs to also get an `showInStore="1"` we think.

Thanks to colleague @radu-miron-baldwin for these additional findings

@ejaz-alam: could you update this PR with these additional changes and merge the latest `2.4-develop` branch in here?

@shikhamis11, @ishakhsuvarov, @ihor-sviziev: can we get this PR re-opened? So it can be further processed?

**Comment by shikhamis11** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Please review https://github.com/magento/magento2/pull/32359#issuecomment-1609421779

**Comment by ejaz-alam** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi @ejaz-alam,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- In back office > Stores > Configuration >Customers > Login as Customer
- Look at the scope for fields "Title for Login as Customer opt-in checkbox" and "Login as Customer checkbox tooltip"

**Before:** :heavy_multiplication_x: 

Screenshot 2024-09-16 at 11 46 25



**After:** :heavy_check_mark: 



Screenshot 2024-09-16 at 13 09 23



Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks

**Comment by engcom-Dash** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by engcom-Dash** [comment]
The Functional CE and B2B test failures are different in recent 2 successive builds. They neither part of PR nor failing because of the PR changes, hence moving it to Merge in Progress.

Functional Tests CE
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/32359/918b288898581e9c8d4351e9607cc8a5/Functional/allure-report-ce/index.html#categories/e8b15f8cfbd42aece12f3c623e953271/a51d51ca088dffd8/
image

Run2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/32359/23ec9f755ddfb617eb8d7ed74fa1f82b/Functional/allure-report-ce/index.html#categories/a644910ae0cb11e839a98baa21929b76/b0f43dc304044e0d/
image

Functional Tests B2B
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/32359/b02ff02c241075cbd8d79dde57ad8508/Functional/allure-report-b2b/index.html#categories/39002bb4b823f2d59e22404a186a7115/a7c0cbfbaa73975f/
image

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/32359/47915016be5edb20ee2611a13e7c01cb/Functional/allure-report-b2b/index.html#categories/e8b15f8cfbd42aece12f3c623e953271/d701eee54050f3c6/
image

**Comment by engcom-Dash** [comment]
We have seen static failures in mainline PR after merging this PR into that. Hence for now moving this PR to Extended testing.

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Pull request merged**
