### PR TITLE
Sort Orders not applied to Magento\Catalog\Model\CategoryList::getList result issue 23342

### LINKED ISSUE #23342: Sort Orders not applied to Magento\Catalog\Model\CategoryList::getList result
### Summary
`\Magento\Catalog\Model\CategoryList::getList` method does not respect searchCriteria sort orders.
This is due to calling `\Magento\Eav\Model\Entity\Collection\AbstractCollection::getAllIds` which calls `\Magento\Eav\Model\Entity\Collection\AbstractCollection::_getAllIdsSelect`.
`_getAllIdsSelect` resets the sort order and it is never again applied to the collection or search result.

### Preconditions (*)
1. Magento 2.3.1

### Steps to reproduce (*)
1. Create an instance of `\Magento\Framework\Api\SearchCriteria` with sort orders applied
2. Pass the instance as an argument to the `\Magento\Catalog\Model\CategoryList::getList` method.
3. Inspect the search results to see the items have not been sorted.

```php
public function getSortedCategories()
{
    $sortOrder = $this->sortOrderBuilder->setField('name')->setDirection('ASC')->create();
    $searchCriteria = $this->searchCriteriaBuilder
        ->setSortOrders([$sortOrder])
        ->create();
    
    /** On inspection we can see the sortOrder is applied to searchCriteria correctly */
        
    $categories = $this->categoryListInterface->getList($searchCriteria);
    
    /** Stepping through the getList method, we see the sortOrder is not respected
        once getAllIds is called and iterated through to get the category instances.
        The searchResult items property is filled with the unsorted result.
    */
    
    return $categories->getItems();
}
```

### Expected result (*)
1. Sort orders should be applied to the search result instance

### Actual result (*)
1. Sort orders are not applied, and the search result returns items by which order getAllIds was returned.

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#23342: Sort Orders not applied to Magento\Catalog\Model\CategoryList::getList result

Reason: `\Magento\Eav\Model\Entity\Collection\AbstractCollection::getAllIds` reset the sort order in `_getAllIdsSelect`

Solution: Use `getLoadedIds` to get the ids instead of `getAllIds`

### Fixed Issues (if relevant)

1. magento/magento2#23342: Sort Orders not applied to Magento\Catalog\Model\CategoryList::getList result

### Manual testing scenarios (*)

1. Create REST POST request to get the admin token:

http://[Magento 2 Domain]/rest/default/V1/integration/admin/token

```
{
  "username": "admin",
  "password": "admin123"
}
```

2. Method GET, Header **authorization** :  **Bearer [The token get from integration api]**

http://[Magento 2 Domain]/rest/default/V1/categories/list?searchCriteria[sortOrders][0][field]=entity_id&searchCriteria[sortOrders][0][direction]=DESC

**Result**: The item list have the order **(sort by ID DESC)**

"id": 2
"name": "Default Category"

Before:

"id": 1,
"name": "Root Catalog",

Another way to test,  create class and test like the issue magento/magento2#23342

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-23807.instances.magento-community.engineering).
Admin access: [https://pr-23807.instances.magento-community.engineering/admin](https://pr-23807.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by davidverholen** [comment]
@magento run all tests

**Comment by edenduong** [comment]
@magento run all tests

**Comment by edenduong** [comment]
Seems Magento fixed this issue. I will close this Pull Request.

**Pull request closed without merging**
