### PR TITLE
Do not use store code in URLs when site is in single store mode

### LINKED ISSUE #36831: [Issue] Do not use store code in URLs when site is in single store mode
This issue is automatically created based on existing pull request: magento/magento2#36414: Do not use store code in URLs when site is in single store mode

---------

### Description (*)
We have a store in single store mode. When we do setup:install, the config option `web/url/use_store` is enabled, which causes the store code to appear in the URL, even though there is only one storeview. This change makes sure the storecode does not appear in the URL when a store is in single store mode.

### Manual testing scenarios (*)

1. Set a store with one store view in Single Store Mode (`bin/magento config:set general/single_store_mode/enabled 1`) and enable store codes (`bin/magento config:set web/url/use_store 1`)
2. Visit the homepage
3. You can see the store code in the URL
4. Apply this patch
5. Visit the homepage
6. Store code is not there

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by peterjaap**
### Description (*)
We have a store in single store mode. When we do setup:install, the config option `web/url/use_store` is enabled, which causes the store code to appear in the URL, even though there is only one storeview. This change makes sure the storecode does not appear in the URL when a store is in single store mode.

### Manual testing scenarios (*)

1. Set a store with one store view in Single Store Mode (`bin/magento config:set general/single_store_mode/enabled 1`) and enable store codes (`bin/magento config:set web/url/use_store 1`)
2. Visit the homepage
3. You can see the store code in the URL
4. Apply this patch
5. Visit the homepage
6. Store code is not there

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36831: Do not use store code in URLs when site is in single store mode

### CODE REVIEW

**Comment by andrewbess** [comment]
@magento run all tests

**Review by andrewbess — CHANGES_REQUESTED** [review]
Hello @peterjaap 
Thank you for your contribution
Could you please fix tests
Thank you in advance.

**Comment by peterjaap** [comment]
@andrewbess failing tests are unrelated to this change.

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
> @andrewbess failing tests are unrelated to this change.

Perhaps integration tests failed due to your changes.
Please check again.
Thank you in advance.

**Comment by peterjaap** [comment]
@andrewbess I'd like to fix the test however it doesn't say which test it is that fails; https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36414/a7d89a27426ba404946195eef3c612c7/Integration/allure-report-ce/index.html#categories/605f6677ce1fac53542d2dad127029aa/db44db41d1327373/

**Comment by andrewbess** [comment]
> @andrewbess I'd like to fix the test however it doesn't say which test it is that fails; https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36414/a7d89a27426ba404946195eef3c612c7/Integration/allure-report-ce/index.html#categories/605f6677ce1fac53542d2dad127029aa/db44db41d1327373/

Hello @peterjaap 
Please check `Magento\Store\Model\StoreTest::testIsUseStoreInUrl`
Thank you in advance.

**Comment by peterjaap** [comment]
@andrewbess thanks, I updated the test

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Integration Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by peterjaap** [comment]
@andrewbess looks like the failing Functional Test is not relevant to this change; https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36414/78399dc8f9bbf0cbbf5771aa637692c5/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by peterjaap** [comment]
So everything's done and now we're waiting for someone to merge it?

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Lima** [comment]
@magento give me test instance

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento `2.4-develop`

**Manual testing scenario:**

1. Set a store with one store view in Single Store Mode (bin/magento config:set general/single_store_mode/enabled 1) and enable store codes (bin/magento config:set web/url/use_store 1)
2. Visit the homepage
3. You can see the store code in the URL
4. Apply this patch
5. Visit the homepage
6. Store code is not there

**Before:** :heavy_multiplication_x: Store code was visible.

Screenshot 2023-02-09 at 5 04 08 PM

Screenshot 2023-02-09 at 5 06 25 PM


**After:** :heavy_check_mark:  Now, store code is not visible.

Screenshot 2023-02-09 at 6 39 01 PM



**Addtionally tested:**

1. Created customer.
2. Placed order from customer.
3. Added product to the wishlist.
4. Placed order from guest.
5. Invoiced,shipped & credit memo.

No additional manual testing is required as a part of regression.
Builds are failed hence, moving this PR to extended testing.

**Comment by engcom-Echo** [comment]
Failing Functional Tests CE is related to currency converter api.

**Comment by peterjaap** [comment]
Woop, apparently this change is now available in 2.4.6 :raised_hands:

**Pull request merged**
