### PR TITLE
fixed issue #18458 : Alert widget gets close when click anywhere on screen #18576

### PR DESCRIPTION
**Pull request by Shubham0492**
### Description (*)
Description
In older version of magento 2.2.6 when we click delete button of minicart then alert widget display for confirm to delete item from cart.This popup was only close when click on "cancel", "ok" & "close" button.But earlier version of magento 2.2.6 it is closing click anywhere on screen.In this PR i have fixed this issue.

### Fixed Issues (if relevant)

1. #18458: Magento version 2.2.6 Alert widget gets close when click anywhere on screen

### Manual testing scenarios (*)

1 - Add product into cart.
2- Click on cart logo and delete item from cart.
3 - Now popup will open for confirm.
4 - Click anywhere on screen.Now popup will not close.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by phoenix128 — APPROVED** [review]
Hello @Shubham-Webkul ,
thanks for your contribution and for your time.

**Comment by magento-engcom-team** [comment]
Hi @phoenix128, thank you for the review.
[ENGCOM-3306](https://jira.corp.magento.com/browse/ENGCOM-3306) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Comment by VladimirZaets** [comment]
Alert widget extend modal widget and modal widget has "clickableOverlay" configuration option.
This option is responsible for allow or prevent close modal action when we click on the overlay. As default, this option has true value. All that you need if you want to change this behavior is the passing false value for the clickableOverlay option. So, this PR should be reverted.

**Pull request merged**
