### PR TITLE
fix for lost template when creating a preference for Magento\Checkout\Block\Cart\Item\Renderer

### PR DESCRIPTION
**Pull request by duckchip**
This fixes an issue with finding the template when creating a preference for Magento\Checkout\Block\Cart\Item\Renderer

### Manual testing scenarios

1. ... create a preference for Magento\Checkout\Block\Cart\Item\Renderer

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by dmanners** [comment]
Hi @duckchip thanks for this PR. From what I can see this change has already been made in the develop branch. Was this the desired branch or did you want to back port this fix to a particular version? https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/view/frontend/layout/checkout_cart_item_renderers.xml#L12

**Comment by dmanners** [comment]
Otherwise if you just need to update your fork have a look through the GitHub docs about keeping your fork up to day. https://help.github.com/articles/syncing-a-fork/ Just make sure you are on the right branch when doing merges.

**Comment by dmanners** [comment]
@duckchip, we are closing this PR as the changes are already on the develop branch. If you'd like to update it or change the target branch, please create a new pr with the updated code.

**Comment by hostep** [comment]
Just informational, the correct solution would be to backport https://github.com/magento/magento2/commit/b4005c505deb3d154e5a3244645d40b0012521da or use the same search-and-replace method @davidalger used, but then on the 2.1-develop branch to fix this properly.

If someone feels like doing this, be my guest :)

**Pull request closed without merging**
