### PR TITLE
Set proper text-aligh for the <th> element of the Subtotal column in the Creditmemo email

### PR DESCRIPTION
**Pull request by TomashKhamlai**
### Description

Change the markup of the template:art: or edit the styles:lipstick:?
I preferred to keep the semantics of the HTML document and change the styles.

### Fixed Issues (if relevant)

1. We definitely do not need this 

### Manual testing scenarios

1. Create an Invoice
2. Create a Credit Memo
3. Check the email that was sent to the Customer

**Expected result:**
screenshot_20180725_025329

**Actual result:**
screenshot_20180725_025205
The Luma and the Blank theme are affected
 
### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=17153) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by TomashKhamlai** [comment]
@magento-engcom-team give me test instance
I will wonder if these comments work automatically :open_mouth::bulb:

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai, here is your [new Magento instance](https://pr-17153.engcom.dev.magento.com).
Admin access: [https://pr-17153.engcom.dev.magento.com/admin](https://pr-17153.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
