### PR TITLE
Fixed Responsive Design, Footers bottom of screen on mobile devices 

### PR DESCRIPTION
**Pull request by chirag-wagento**
Fix footer responsive issue
### Fixed Issues (if relevant)

1. magento/magento2#15118: 
Responsive Design, Footers do not snap to bottom of screen on mobile devices 

### Manual testing scenarios

1. Check responsive footer

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @chirag-wagento. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by VladimirZaets** [comment]
Hi, @chirag-wagento , thank you for collaboration.
The `body` node can't have height:100% style.
Please look comments [here](https://github.com/magento/magento2/pull/15471)

**Comment by chirag-wagento** [comment]
@VladimirZaets  I have committed new cod with new changes now you can check it.
I can see 100%  `body` height. Now You can check it.
You can see attached screenshot
body-issue
 
Thanks

**Comment by DanielRuf** [comment]
Try to scroll down a bit, the body will not end at the end of the document.

**Comment by chirag-wagento** [comment]
@DanielRuf  Please review above comment and screenshot.
Can you give me issue screenshot.

My changes are in Branch **fix-footer-responsive-mobile**. You can check it.

Thanks

**Comment by chirag-wagento** [comment]
@VladimirZaets   

Any update in this PR?

Thanks

**Comment by VladimirZaets** [comment]
Hi @chirag-wagento Please scroll your page down and make the screenshot. You will see the bug if to do that.

**Comment by VladimirZaets** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, here is your [new Magento instance](https://pr-16323.engcom.dev.magento.com).
Admin access: [https://pr-16323.engcom.dev.magento.com/admin](https://pr-16323.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Please make sure you are PR **author** or **assignee** to access the instance.

**Comment by DanielRuf** [comment]
bildschirmfoto 2018-06-25 um 10 48 47
bildschirmfoto 2018-06-25 um 10 48 37

Should be (at least) `display:inline-block` + `width: 100%;`.

**Comment by DanielRuf** [comment]
inline is not for block elements like this one so this is still not correct ;-)

**Comment by chirag-wagento** [comment]
@DanielRuf  `inline-block` + `width: 100%` also incorrect because there are problem with content   as per this https://github.com/magento/magento2/pull/15471#issuecomment-399092565
So I will use `display: inline-grid`.

**Comment by chirag-wagento** [comment]
@DanielRuf  and @VladimirZaets   I have changed my code  please check.

Thanks

**Comment by VladimirZaets** [comment]
@chirag-wagento Please looks this example http://jsfiddle.net/webtiki/h9mHc/

**Comment by DanielRuf** [comment]
> @DanielRuf inline-block + width: 100% also incorrect because there are problem with content as per this #15471 (comment)

No, and inline-grid is not correct or supported by all browsers.

**Comment by chirag-wagento** [comment]
@DanielRuf   Ok  i will close my PR. You can do this.

**Pull request closed without merging**
