### PR TITLE
#25192 fixed

### PR DESCRIPTION
**Pull request by ghost**
### Fixed Issues (if relevant)

1. magento/magento2#25192: DHL Shipping

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by VladimirZaets** [comment]
Hi @vishalverma279. 
Thanks for collaboration. 
The processing of this PR will be after the issue will be confirmed.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Issue was already confirmed, removing "on hold" label

**Comment by lenaorobei** [comment]
@magento run all tests

**Review by sidolov — CHANGES_REQUESTED** [review]
@vishalverma279 please, cover changes with automated test

**Comment by engcom-Charlie** [comment]
Hi @sidolov, these changes was checked by unit test. With changes from PR test passed, without - failed(as expected).
If it's not enough what type of autotest would you suggest to cover this scenario?
Thank you.

**Comment by sidolov** [comment]
@engcom-Charlie you are right, unit test should be enough for such minor changes.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8077](https://jira.corp.magento.com/browse/ENGCOM-8077) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:** :heavy_multiplication_x: The Domestic express isn't presented in Non Documents Allowed Methods

Screenshot from 2020-09-01 14-37-57

**After:** :heavy_check_mark: The Domestic express is presented in Non Documents Allowed Methods

**Pull request merged**
