### PR TITLE
Design issue fixed in category page magento2#30397

### LINKED ISSUE #30397: Design issue in category page , in Shopping Options dropdown, the count value alignment is not right.
*Design issue in category page , in Shopping Options dropdown, the count value alignment is not right.*

### Preconditions (*)
1. PHP 7.4.11
2. magento2-2.4

### Steps to reproduce (*)
1) Open magento base url.
2) Go to category page.
3) Go to Shopping Options on left side of page.
4) Open any CATEGORY/PRICE dropdown.
5) Check count design.

### Expected result (*)
https://user-images.githubusercontent.com/50991251/95648439-c8acd500-0af4-11eb-9517-0108d76889f6.png

### Actual result (*)
https://user-images.githubusercontent.com/50991251/95648477-1d505000-0af5-11eb-956c-154f3bf1c189.png

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by saumya1998**
### Description (*)
**Fixed #30397 count design issue fixed**

Preconditions (*)
PHP 7.4.11
magento2-2.4

Manual testing scenarios (*)
1.Open magento base url.
2.Go to category page.
3.Go to Shopping Options on left side of page.
4.Open any CATEGORY/PRICE dropdown.
5.Check count design.

Expected result (*)
https://user-images.githubusercontent.com/50991251/95648439-c8acd500-0af4-11eb-9517-0108d76889f6.png

Actual result (*)
https://user-images.githubusercontent.com/50991251/95648477-1d505000-0af5-11eb-956c-154f3bf1c189.png

### CODE REVIEW

**Comment by vijay-wagento** [comment]
#dmcdindia2020

**Comment by saumya1998** [comment]
#dmcdindia2020

**Comment by mrtuvn** [comment]
Sorry but seem your fix not correctly solve to root cause. You should not try to align element with fixed value
I already have the fix related with this area 
See this https://github.com/magento/magento2/pull/30333

**Comment by ptylek** [comment]
I agree with @mrtuvn that this is not the correct approach. 

As this has been already solved and accepted in #30333 I am adding duplicate label and closing this PR.

**Pull request closed without merging**
