### PR TITLE
Fix Test Logger monolog compatibility

### LINKED ISSUE #35604: Monolog issue
### Preconditions and environment

- Magento version 2.4.4
- PHP8.1
- Install data-migration-tool
- Monolog 2.7.0

### Steps to reproduce

1. composer update
2. bin/magento setup:upgrade

### Expected result

Everything works fine

### Actual result

```
PHP Fatal error:  Declaration of Migration\Logger\Logger::addRecord(int $level, string $message, array $context = []): bool must be compatible with Monolog\Logger::addRecord(int $level, string $message, array $context = [], ?Monolog\DateTimeImmutable $datetime = null): bool in /var/www/html/vendor/magento/data-migration-tool/src/Migration/Logger/Logger.php on line 34
```

### Additional information

Monolog 2.7.0 has bee released yesterday, and have breaking changes.

Quick Solution : fix dependency to 2.6.0
Best Solution : fix compatibility issues

Note that everyone who upgrades to 2.4.4 from now will probably have this issue.

Quick solution for devs who don't want to wait for a fix & release : `composer require monolog/monolog:2.6.0`

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by convenient**
Not sure if this is the preferred approach, but one of our automated suites which builds magento with our module caught this today.

# System info
- Magento 2.4.4
- PHP 8.1

# To reproduce
1. Get a setup of 2.4.4 installed
2. See that in the constraints allow for an install of `monolog/monolog` at `2.7.0`
3. Try to run integration tests (https://devdocs.magento.com/guides/v2.4/test/integration/integration_test_execution.html)

# The error
Currently we get this error because the method signatures are different

```
PHP Fatal error:  Declaration of Magento\TestFramework\ErrorLog\Logger::addRecord(int $level, string $message, array $context = []): bool must be compatible with Monolog\Logger::addRecord(int $level, string $message, array $context = [], ?Monolog\DateTimeImmutable $datetime = null): bool in dev/tests/integration/framework/Magento/TestFramework/ErrorLog/Logger.php on line 69
```

# Root cause
This version of `monolog/monolog` was tagged about an hour ago https://github.com/Seldaek/monolog/releases/tag/2.7.0

See this entry
> Added $datetime parameter to Logger::addRecord as low level API to allow logging into the past or future (https://github.com/Seldaek/monolog/pull/1682)

Which goes along with this commit
https://github.com/Seldaek/monolog/commit/0ddba7342ff919990e1914d24db15e565f153676#diff-1e7fd545cec457de96f5ed6bd7249ba091cd9e699b4057db15ff1e2e0364025bR297

This changes the method signature of `addRecord` like so
```diff
-    public function addRecord(int|Level $level, string $message, array $context = []): bool
+    public function addRecord(int|Level $level, string $message, array $context = [], DateTimeImmutable $datetime = null): bool 
```

See the magento core logger is defined like this
https://github.com/magento/magento2/blob/a8543fed035d85c667195e95f69476d51f98381b/dev/tests/integration/framework/Magento/TestFramework/ErrorLog/Logger.php#L69-L73

The method signature needs to be updated to match `monolog/monolog` definition

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by convenient** [comment]
@magento run all tests

**Comment by convenient** [comment]
https://github.com/magento run all tests

**Comment by convenient** [comment]
@magento run all tests

**Comment by convenient** [comment]
```
PHPStan detected violation(s):
 ------ ------------------------------------------------------------------- 
  Line   integration/framework/Magento/TestFramework/ErrorLog/Logger.php    
 ------ ------------------------------------------------------------------- 
  82     Method Monolog\Logger::addRecord() invoked with 4 parameters, 2-3  
         required.                                                          
 ------ ------------------------------------------------------------------- 
```

I dont know how your static tests are bootstrapped but evidently not pulling in the new version of monolog.

When i do a `composer create project` they're definitely pulling it in

**Comment by convenient** [comment]
@magento run Unit Tests

**Comment by zrpnr** [comment]
Hi @convenient you'll probably want to add `use Monolog\DateTimeImmutable;` after line 11 in this Logger file.

If you look at Monolog they're using their own class for DateTimeImmutable
- https://github.com/Seldaek/monolog/tree/main/src/Monolog
We ran across this same problem in the Drupal monolog module: https://www.drupal.org/project/monolog/issues/3284825

**Comment by convenient** [comment]
Huh thanks @zrpnr 

I didn't spot that was just aiming for green tests 😅

**Comment by convenient** [comment]
@magento run all tests

**Comment by convenient** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by convenient** [comment]
Before I spend any time fighting test cases can I please have some feedback on the official monolog stance on what Magento is doing here, see https://github.com/Seldaek/monolog/issues/1684#issuecomment-1152874168

> Your PR works @convenient I guess but really I do wonder why Logger was extended here instead of adding a custom Handler to collect less-than-error records. That's what handlers are for, overriding addRecord for this is madness IMO. You could even do it with native handlers from monolog combining a FilterHandler and a TestHandler (or just the latter..) to gather records and access them again in the test.

Seems to me using a handler is the right thing to do here

**Comment by convenient** [comment]
This seems fixed in 2.4.5

**Comment by ihor-sviziev** [comment]
Looks like in Magento 2.4.5 we have a fix for this issue with the same changes https://github.com/magento/magento2/commit/360fd1ba9d6e67185b7fbd3e00223cd948bb896e
I believe soon the last release will be merged to 2.4-develop, so we'll see the conflict there.

**Comment by convenient** [comment]
Thanks for the fyi @ihor-sviziev . I did spot this in the pre release a week or so back.

In these scenarios I wonder why my commits aren't cherry picked or merged rather than doing new ones. attribution isn't a massive deal but I've clearly done the leg work here 

From identifying the issue (an hour or so after it appeared), to writing a bug report, speaking with the upstream developers, and trying to have a communication with Magento about a better way of fixing it than what was in this PR.

**Comment by ihor-sviziev** [comment]
@convenient true!
/CC @sidolov @sdzhepa @mahesh-singh-rajawat

**Comment by sdzhepa** [comment]
Hello @convenient and @ihor-sviziev 

Thank you for pointing out this situation! 

Unfortunately, I do not have a clear and transparent answer to "Why did it happen?" 
But I agree it is absolutely not acceptable.

We are working with teams and @mahesh-singh-rajawat to prevent this kind of situation in future


 Sorry for the incident and any inconveniences

cc: @sidolov

**Pull request closed without merging**
