### PR TITLE
Fix the reordering of dynamic rows for tables that don't have a `thead` element

### LINKED ISSUE #36129: Reordering bundle options does not work as expected
### Preconditions and environment

- Magento version 2.4.4.-p1

### Steps to reproduce

1. Create a new bundle product
2. Add at least two options
3. Try to reorder the options via drag and drop

### Expected result

Reordering the options does work via drag and drop.

### Actual result

Reordering the options does not work.

Touching the drag handle makes the options element to jump/snap to the left but it cannot be moved. 

### Additional information

If you collapse all the options and then try to drag an option, you can move that option down one position in the order.

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by densen45**
### Description (*)

The reordering of dynamic rows in adminhtml does not work as expected for tables that don't have a `thead` element. This pull request makes the reordering of rows work no matter if a table has a `thead` element or not.

The steps to reproduce for the issue are described here: https://github.com/magento/magento2/issues/36129

The reason for the issue is described here: https://github.com/magento/magento2/issues/36129#issuecomment-1243581243

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36129

### Manual testing scenarios (*)

1. Create a new bundle product
2. Add at least two options
3. Try to reorder the options via drag and drop (works due to this fix)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by densen45** [comment]
@magento give me test instance

**Comment by densen45** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@densen45 Thanks for your work. We already have PR with implemented fix https://github.com/magento/magento2/pull/36072

**Comment by densen45** [comment]
Oh too bad, I didn't find that one in my search. 
@Den4ik Thanks anyway for the link and the review!

**Comment by engcom-Hotel** [comment]
Duplicate of https://github.com/magento/magento2/pull/36072

**Pull request closed without merging**
