### PR TITLE
Fix: add to cart grouped product when exists a sold out option

### PR DESCRIPTION
**Pull request by gihovani**
### Description (*)
Fix to add to cart grouped product when exists a sold out option.

### Fixed Issues (if relevant)

1. magento/magento2#22304: [Grouped product] Can´t add simple products to cart if one other is out of stock 

### Manual testing scenarios (*)

1. enable the option allow to show products without stock
2. grouped product with more sub items
3. at least one sub items have to be without stock (quantity=0)
4. navigate to the PDS of the grouped product
5. add at least on item of any available sub item
6. add the item to the cart

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by gihovani** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @gihovani. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @gihovani, here is your [Magento instance](https://i-24955-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24955-2-3-develop.instances.magento-community.engineering/admin](https://i-24955-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by gihovani** [comment]
Hi,

i tested it at 2.3-develop and it is reproducible.

Grouped Product

**Review by osrecio — APPROVED** [review]
I tested with vanila Magento and with your changes and works properly

**Comment by magento-engcom-team** [comment]
Hi @osrecio, thank you for the review.
[ENGCOM-6115](https://jira.corp.magento.com/browse/ENGCOM-6115) has been created to process this Pull Request
:eight_spoked_asterisk: @osrecio, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@gihovani thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA passed

**Review by VladimirZaets — DISMISSED** [review]
Hi @gihovani. Thanks for collaboration. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

**Comment by gihovani** [comment]
> Hi @gihovani. Thanks for collaboration. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

@VladimirZaets, I dont know, how can i create this test... 
would you have a similar test for me to get inspired?

**Comment by slavvka** [comment]
@engcom-Foxtrot Could you please help @gihovani to cover the change with automated test?

**Comment by engcom-Golf** [comment]
I will take care of test coverage

**Comment by engcom-Golf** [comment]
@VladimirZaets Well, case covered by unit test.

**Comment by engcom-Golf** [comment]
@magento run all tests

**Pull request merged**
