### PR TITLE
AC-13325 Issue#39347 grouped product qty validation issue fix

### LINKED ISSUE #39347: Grouped Product Quantity Validation Displays Errors for All Inputs When One Input Is Invalid
### Preconditions and environment

- Magento Versions
I tested in Magento 2.4.7 and Magento 2.4.7-p2
 
- Description
On the grouped product page, entering a single invalid quantity (e.g., a negative value) causes error messages to appear for all quantity input fields, even if the other inputs have valid values. This behavior creates confusion for users who have correctly entered quantities.

### Steps to reproduce

1. Navigate to a grouped product page.
2. Enter a negative value (e.g., -10) in one of the quantity input fields.
3. Enter valid values (e.g., 6 or 9) in the other quantity input fields.
4. Observe the error messages displayed.

Cursor_and_Set_of_Sprite_Yoga_Straps

### Expected result

Only the input field with an invalid quantity should display an error message.

### Actual result

All input fields display an error message, even if their values are valid.

### Additional information

In Magento 2.4.5, the form validation is handled by `view/frontend/web/product/view/validation.js`, whereas in Magento 2.4.7, it is managed by `lib/web/mage/validation.js`.

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Mohamed-Asar**
### Description (*)

Fix for Grouped Product Quantity Validation Displays Errors for All Inputs When One Input Is Invalid

### Fixed Issues (if relevant)

1. Fixes #39347

### Manual testing scenarios (*)

1.  Go to grouped product PDP
2. Add invalid qty in any one of the simple product qty input
3. Verify the error message display below only invalid qty textbox.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Mohamed-Asar** [comment]
@magento run all tests

**Review by engcom-Hotel — COMMENTED** [review]
Hello @Mohamed-Asar,

Thanks for your contribution!

It seems the issue has been fixed already. We request you to please look into this https://github.com/magento/magento2/issues/39347#issuecomment-2484707659. 

Thanks

**Comment by Mohamed-Asar** [comment]
Hello @engcom-Hotel ,

No, Still the issue exists on the latest 2.4-develop, i verified in my local env 

image

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @Mohamed-Asar,

Thanks for the contribution!

Please cover the PR changes with some automated tests in accordance with [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/) and also please fix the build failures.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @Mohamed-Asar,

I would suggest you add an MFTF to verify the code changes.

for build failures lets try to re-run the tests, they might be flaky.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by Mohamed-Asar** [comment]
Sure @engcom-Hotel let me write MFTF for this change

**Comment by engcom-Hotel** [comment]
@magento run Static Tests, Functional Tests CE, Functional Tests B2B

**Comment by Mohamed-Asar** [comment]
@magento run all tests

**Comment by Mohamed-Asar** [comment]
@magento run all tests.

**Comment by Mohamed-Asar** [comment]
@magento run all tests

**Comment by Mohamed-Asar** [comment]
@magento run all tests

**Comment by Mohamed-Asar** [comment]
@engcom-Hotel I've added the MFTF Test case, Verified in my local env, but on the test results, its failed for both B2B and EE functional testing.

**Comment by engcom-Charlie** [comment]
> @engcom-Hotel The test case I added is failing in both EE and B2B environments. However, when I tested it locally in EE Version, it worked fine. Do you have any insights into what I might be missing?
> 
> image

Hi @Mohamed-Asar,

Thank you for your contribution!

I will look into this issue and get back to you.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE, Functional Tests B2B, Functional Tests CE

**Comment by engcom-Charlie** [comment]
Hi @engcom-Hotel, the mentioned test StoreFrontValidateGroupedProductQuantityInputErrorMessageTest [here](https://github.com/magento/magento2/pull/39377#issuecomment-2536553799), did not failed in recent 2 builds and the failed tests are not consistent in recent 2 build. Hence, requesting you for review.

Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39377/4be173f0bc6694e2f799dd1ddd14cbe2/Functional/allure-report-ee/index.html#categories
image


Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39377/f3a8cb834c57a9571f89c9c38c4eaf3e/Functional/allure-report-ee/index.html#categories

image

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Static Tests, Unit Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE, Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE, Static Tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi @Mohamed-Asar,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Go to grouped product PDP
- Add invalid qty in any one of the simple product qty input
- Verify the error message display below only invalid qty textbox.


**Before:** :heavy_multiplication_x: 


Grouppp-12-20-2024_09_22_AM






**After:** :heavy_check_mark: 


Grouppp-12-20-2024_09_33_AM





Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE, Integration Tests, Static Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE, Static Tests

**Comment by engcom-Charlie** [comment]
The Functional EE failures in recent 2 builds on same code are not consistent. Failure is neither part of PR nor failing because of the code changes.

**Run 1:** https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39377/37b7fdd34f6bbff04bdbca7380bc15d3/Functional/allure-report-ee/index.html#categories

image


**Run 2:** https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39377/8c711180a51292db3d75d57e167b7597/Functional/allure-report-ee/index.html#categories

image

**Comment by engcom-Charlie** [comment]
The **Static test failure** is not showing any error in allure report.  Checked Jenkin buil's console output, the error is a known issue. Its not part of PR.
https://jira.corp.adobe.com/browse/AC-13542

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
Hi @Mohamed-Asar,

Thank you for your contribution!

It seems that, the mentioned issue has been recently resolved in https://github.com/magento-commerce/magento2ce/commit/56463d5e7016d9f4c59c2ae00e77008c227088f5 under internal JIRA  https://jira.corp.adobe.com/browse/ACP2E-3469 

It's not reproducible now, hence closing it now. Please feel free to reopen for any further updates.

image

**Comment by Mohamed-Asar** [comment]
@engcom-Charlie @engcom-Hotel , 


This is the third time that both the internal team and I have worked on the same issue. Is there a way to avoid this duplication so that I don’t waste time on redundant efforts?

Regarding the code, I reviewed the commit on this [line](https://github.com/magento/magento2/commit/56463d5e7016d9f4c59c2ae00e77008c227088f5#diff-36dbe6cd3461b48b5f8b6924e2bf11510242126c67c1f0423b3181174b3a21f3R24) and noticed that the .each function is unnecessary because it loops through all the simple product inputs for every single product. Instead, we should only check the current one, as I’ve implemented in my changes.

Please refer to the screenshot below for verification in the 2.4-develop branch.

image

vs my branch 

image

**Comment by Mohamed-Asar** [comment]
> @engcom-Charlie @engcom-Hotel ,
> 
> This is the third time that both the internal team and I have worked on the same issue. Is there a way to avoid this duplication so that I don’t waste time on redundant efforts?
> 
> Regarding the code, I reviewed the commit on this [line](https://github.com/magento/magento2/commit/56463d5e7016d9f4c59c2ae00e77008c227088f5#diff-36dbe6cd3461b48b5f8b6924e2bf11510242126c67c1f0423b3181174b3a21f3R24) and noticed that the .each function is unnecessary because it loops through all the simple product inputs for every single product. Instead, we should only check the current one, as I’ve implemented in my changes.
> 
> If a grouped product contains 10 simple products, the quantity input for each simple product is validated 10 times instead of just once.
> 
> Please refer to the screenshot below for verification in the 2.4-develop branch.
> 
> image
> 
> vs my branch
> 
> image

@engcom-Hotel @engcom-Charlie did you get a chance to review this comment ?

**Comment by Mohamed-Asar** [comment]
@engcom-Hotel @engcom-Charlie did you get a chance to review the last comment ?

**Comment by engcom-Charlie** [comment]
Hi @Mohamed-Asar,

Thank you for your contribution!!

Regarding your query on internal team's PR implementation [here](https://github.com/magento/magento2/pull/39377#issuecomment-2565485291), we have reached out to the reviewer and following up with the team. Once we get any information on this, we will keep you posted.

Thank you!

**Comment by Mohamed-Asar** [comment]
Hi @engcom-Charlie, 
Thanks! Looking forward for your response

**Comment by Mohamed-Asar** [comment]
@engcom-Charlie is there any update from internal team ? if no update then please re-open the pr

**Comment by engcom-Charlie** [comment]
Hi @Mohamed-Asar, the internal team have considered the review comments mentioned by you in [comment](https://github.com/magento/magento2/pull/39377#issuecomment-2565485291). Team will be taking care of it under one of the internal [JIRA](https://jira.corp.adobe.com/browse/ACP2E-3710).

Thank you for your contribution!!

**Comment by Mohamed-Asar** [comment]
@engcom-Charlie 

Thanks for the update! I’m glad to hear that the team is considering my feedback. Since the solution is already included in this PR and has been tested and verified, they can simply cherry-pick the commit.

**Pull request closed without merging**
