### PR TITLE
Fixed issues-18534: 2 wysiwyg on catalog category edit page

### PR DESCRIPTION
**Pull request by mmatrafailo**
Fix for issue https://github.com/magento/magento2/issues/18534

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18535) <br/>All committers have signed the CLA.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3254](https://jira.corp.magento.com/browse/ENGCOM-3254) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@k1las thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @k1las. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
