### PR TITLE
UI Component grid indicates a wrong number of selections when removin…

### LINKED ISSUE #24348: UI Component grid indicates a wrong number of selections when removing keyword search
### Preconditions (*)
1. Seen on Magento 2.2.3, 2.3.2 and 2.3, 2.4-develop (7cf99d11e6a), so probably all M2 versions are affected

### Steps to reproduce (*)
1. Setup some vanilla Magento
1. Login to the backend
1. Create 3 customers: 'One One', 'Two Two' and 'Three Three':
 Screenshot 2019-08-28 at 20 05 17 **this is probably the main bug**, but it gets even worse
1. Select Actions => Delete
1. Notice that it says it will remove 1 record:
 [img width="692" alt="Screenshot 2019-08-28 at 20 06 36" src="https://user-images.githubusercontent.com/85479/63881616-87309780-c9d0-11e9-8a77-b37ebaea6768.png"]

1. Press OK
1. Notice that it now removed all records (3) instead of the 1 it claimed to delete before **yikes!**
 [img width="441" alt="Screenshot 2019-08-28 at 20 06 47" src="https://user-images.githubusercontent.com/85479/63881704-b6df9f80-c9d0-11e9-99d9-690560719c9e.png">

Note that the exact same thing can be reproduced with the product grid (and maybe other grids as well in Magento).
### Expected result (*)
1. After removing the keyword search, it should only keep 1 record selected, not all of them

### Actual result (*)
1. Shop owners calling in panic that they unintentionally removed all their customers/products somehow

### PR DESCRIPTION
**Pull request by ghost**
wrong number of selections(selected records) in ui component grid #24348

### Description (*)

After removing the full text search keyword the selected records and count mismatches. Which is fixed now.

### Fixed Issues (if relevant)

1. fixes magento/magento2#24348:UI Component grid indicates a wrong number of selections when removing keyword search
### Manual testing scenarios (*)

1. Setup some vanilla Magento
2. Login to the backend
3. Create 3 customers: 'One One', 'Two Two' and 'Three Three':
4. In the 'Search by keyword' box, enter 'one' and search
5. In the first column, choose the 'Select All' option
6. Notice that one record is selected: 
   I. Remove the 'one' keyword search by pressing the 'x' icon to the right of it.
   II. Notice that it now says that one record is selected, but visually all records have a checkmark:
7. Select Actions => Delete
8. Notice that it says it will remove 1 record:
9. Press OK
10. Notice that it now removed all records (3) instead of the 1 it claimed to delete before 
11. Press OK
12. Notice that it now removed all records (3) instead of the 1 it claimed to delete before 
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by krzksz** [comment]
Hey @prabhatrawat-webkul, please take a look at the failing tests.

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run all tests

**Review by sidolov — CHANGES_REQUESTED** [review]
@prabhatrawat-webkul solution looks good to me! Could you please fix JS static test failures and cover changes with automated test? Thank you!

**Comment by engcom-Charlie** [comment]
HI, @prabhatrawat-webkul Could you please fix `Static tests` failures and cover changes with an automated test?
Thank you.

**Comment by gabrieldagama** [comment]
Hi @prabhatrawat-webkul, thanks for your contribution. After looking at the issue and the possible solutions we've decided to proceed with this PR https://github.com/magento/magento2/pull/29968 that aims to fix the same issue. 

The approach that was chosen was to preserve the same behavior that we have with filters. So when a search tag is removed from filters the previous selection becomes invalid and it is dismissed. As result, we have the same behavior across multiple functionalities on the grid.

I will be closing this PR but feel free to reopen it anytime.

**Pull request closed without merging**
