### PR TITLE
"laminas/laminas-serializer" updated to ^2.10.1

### PR DESCRIPTION
**Pull request by khrystynastolbova**
### Description (*)

Update laminas/laminas-serializer to PHP 8 compatible version (2.10.1)

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/518

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32318

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by khrystynastolbova** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by sivaschenko** [comment]
@magento run Functional Tests CE

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@khrystynastolbova @sivaschenko Could you please resolve merge conflict

**Comment by khrystynastolbova** [comment]
> @khrystynastolbova @sivaschenko Could you please resolve merge conflict

Done

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run Unit Tests

**Pull request merged**
