### PR TITLE
Remove unnecessary scripts review summary

### LINKED ISSUE #37776: [Issue] Remove unnecessary scripts review summary
This issue is automatically created based on existing pull request: magento/magento2#34643: Remove unnecessary scripts review summary

---------
I don't see the need to use a script for the rating here I think with inline style that should be enough. This optimization avoids loading and executing JavaScript, which can result in faster page load time. In addition, the code is simplified and more readable because the CSS styles are specified directly in the HTML markup.

Ashampoo_Snap_Montag, 15  November 2021_21h08m18s_001_

On women/tops-women/jackets-women.html removes 12 script tags

Before:
before
before2

After:
after
after2

### PR DESCRIPTION
**Pull request by in-session**
I don't see the need to use a script for the rating here I think with inline style that should be enough. This optimization avoids loading and executing JavaScript, which can result in faster page load time. In addition, the code is simplified and more readable because the CSS styles are specified directly in the HTML markup.

Ashampoo_Snap_Montag, 15  November 2021_21h08m18s_001_

On women/tops-women/jackets-women.html removes 12 script tags

Before:
before
before2

After:
after
after2

### Resolved issues:
1. [x] resolves magento/magento2#37776: Remove unnecessary scripts review summary

### CODE REVIEW

**Comment by in-session** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
reason because it's rely on id . I think that why reason author use that approach
https://github.com/magento/magento2/commit/d2745c59c545dff90a371528dab648b1df021dce#diff-b2e9bb45b6102e1c93288b1f9b3a7e3a0a1c0da52296a441c0b805e32b0e8a58

**Comment by in-session** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@sidolov, could you provide some info on why this block was added in `MC-29420: Remove event handlers from CE` https://github.com/magento/magento2/commit/70ede03e5c2dc9e2c3bb23d0fc5c29cb03cbe7dd?

**Comment by sidolov** [comment]
Hi @ihor-sviziev , it was done in the scope of the story: "Move inline event handlers, styles to dedicated tags in phtml templates"

**Comment by ihor-sviziev** [comment]
Hi @in-session,
It looks like it's needed for the CSP.
Here is more details: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#violation_cases

**Comment by in-session** [comment]
Hi @ihor-sviziev

Sorry, I don't quite get it yet :-) 

Due to the changes in the files, a script is no longer needed to display the rating summary stars. 
Or does the problem only relate to the view.phtml?

**Comment by ihor-sviziev** [comment]
@in-session ifi got it correctly, the CSP rules in Magento disallows using inline styles, that's why it was added

**Review by andrewbess — CHANGES_REQUESTED** [review]
Hello @in-session 
Thank you for your contribution.
Could you please fix static tests
Thank you in advance.

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento give me test instance

**Review by andrewbess — APPROVED** [review]
Hello @in-session 
Thank you for fixes
approved ✔️

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, thank you for the review.
[ENGCOM-9346](https://jira.corp.magento.com/browse/ENGCOM-9346) has been created to process this Pull Request
:eight_spoked_asterisk: @andrewbess, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@in-session thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by sasha19957099** [comment]
@magento give me test instance

**Comment by mrtuvn** [comment]
@in-session can you take a look at conflicts when you have spare time ?

**Comment by in-session** [comment]
@mrtuvn When I have something I can look at it again. But will take some time, because we first have to build a new testinstant. We have said goodbye to the luma and have switched completely to hyva.

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento give me test instance

**Comment by in-session** [comment]
@magento give me 2.4-develop instance

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

**Comment by in-session** [comment]
@mrtuvn @ihor-sviziev @sidolov  it look like the test are not related to this pull?

**Comment by in-session** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

**Comment by in-session** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
@magento give me test instance

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

1. Disable the FPC in the backend and reload the category page.
2. Verify whether the script got removed or not.

**Before:** :heavy_multiplication_x: 
Screenshot 2023-07-20 at 5 43 59 PM

Screenshot 2023-07-20 at 5 41 38 PM

Screenshot 2023-07-20 at 5 51 58 PM

**After:** :heavy_check_mark:  

Screenshot 2023-07-20 at 5 44 30 PM
Screenshot 2023-07-20 at 5 50 43 PM
Screenshot 2023-07-20 at 5 51 58 PM

**Additionally tested:**
Verified the performance of page loading.

No additional manual test cases are required as part of regression as this PR is related to performance improvement.

Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Integration Tests, Static Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Static Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Charlie** [comment]
The functional B2B and EE tests failures in recent 2 builds are not consistent. The tests are not part of the PR or not failing because of the PR changes, considering them as flaky. Hence moving this PR to Merge in Progress.

**Functional B2B Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/34643/68daabc9e9d8a3d8719cd5c8fa5146bb/Functional/allure-report-b2b/index.html#categories

image


**Run 2**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/34643/d0715457acdbfd37ef6b5242b60b9b15/Functional/allure-report-b2b/index.html#categories

image


**Functional EE Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/34643/825f1663cc7d0bfc669e2e20bad92687/Functional/allure-report-ee/index.html#categories

image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/34643/da732050ff9b0397f4ad58e35896b02c/Functional/allure-report-ee/index.html#categories

image

**Pull request merged**
