### PR TITLE
Added default Expires header and enabled apache served files compression by default. 

### PR DESCRIPTION
**Pull request by miguelbalparda**
#1615

### CODE REVIEW

**Comment by miguelbalparda** [comment]
@magento-cicd2  I just signed the agreement with my github account but it still appears as unsigned.

**Comment by miguelbalparda** [comment]
@tanya-soroka @okorshenko can you take a look at this PR? Context here https://github.com/magento/magento2/pull/1615#issue-99072874 BTW I can't sign the CLA.

**Comment by pboisvert** [comment]
@miguelbalparda by your last comment do you mean that the UX will not allow you to sign the CLA or that you cannot sign the CLA for another reason?

**Comment by miguelbalparda** [comment]
Sorry my bad @pboisvert. I tried to sign the CLA several times and I'm always being redirected back here after accepting but it still says "Contributor License Agreement is not signed yet."

**Comment by pboisvert** [comment]
ok, thanks--we will check into that. Not sure what is happening with the CLA.

**Comment by miguelbalparda** [comment]
Good stuff, I tried Chrome and Firefox to rule out the browser. Same result.

**Comment by piotrekkaminski** [comment]
hey @miguelbalparda . This is now solved. There was a bug in CLA code that caused some signatures not to be reflected properly and we fixed those instances as well as implemented new version of CLA code that should work ok. Thanks for letting us know. cc @pboisvert @benmarks

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Added-default-Expires-header-and-enabled-apache-served-files/idi-p/45132).

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=4390) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=4390) before we can accept your contribution.<br/><hr/>**mbalparda** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by miguelbalparda** [comment]
Closing in favor of  #7505

**Pull request closed without merging**
