### PR TITLE
magento/magento2#28050 Get rid of ActionInterface plugins

### LINKED ISSUE #28050: Eliminate plugins for ActionInterface in Framework
### Summary (*)
Magento 2.4-develop
Eliminate plugins for `\Magento\Framework\App\ActionInterface` under `lib/internal/Magento/Framework/App/Action/Plugin`
Reason: plugins should be used to customize behavior of one module from another module. In this case, plugins that belong to Framework customize class behavior of the same Framework.

### Examples (*)

The problem is in the code and execution flow being more complex than it could be.

### Proposed solution

It is suggested to add desired behavior directly to the place where it's expected to execute. Consider `\Magento\Framework\App\FrontController::dispatch()` part of the framework as the place to inject necessary behavior.

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Response for #28050 request.

### Fixed Issues (if relevant)

1. fixes #28050

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
The integration tests were performed by calling `dispatch` on Action.
That is not going to work without decision about further steps.

On hold for now :facepalm:

**Comment by ihor-sviziev** [comment]
FYI this PR was moved to "oh hold" due to internal discussions, reason the same as there https://github.com/magento/magento2/pull/27538#issuecomment-624891873

**Review by buskamuza — DISMISSED** [review]

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Sorry, just clicked wrong button. Re-opened

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@lbajsarowicz please review and fix failing tests

**Comment by ihor-sviziev** [comment]
@lbajsarowicz,
Will you be able to update your PR?

**Comment by lbajsarowicz** [comment]
Yes

**Comment by lbajsarowicz** [comment]
@ihor-sviziev I'll try to finish that during the upcoming weekend.

**Comment by ihor-sviziev** [comment]
@lbajsarowicz will you continue working on this PR? 🐈

**Comment by ihor-sviziev** [comment]
@lbajsarowicz  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
