### PR TITLE
Update wikimedia/lessphp to v3

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Update to near stable version. Previously magento still use version 1.8.2
Valid version of this package will be >=3.0.0 <4.0.0
After this patch new version package will be 3.1.0 . From origin repo owner announcements new version support PHP8

This package magento used for server side compile less to css

Origin repo related
https://github.com/wikimedia/less.php/

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/455

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Run static content deploy verify without issue or error
2. Preview any page in frontend or admin verify no break layout

### Questions or comments

CC @krzksz @rogyar Your comments are welcome

Should magento add new feature with official parser less without need install/depend on 3rd-party package ?
Example built-in less/sass parser by php or even we don't use php parser at all. We can use js for compilation

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31761: Update wikimedia/lessphp to v3

### CODE REVIEW

**Comment by hostep** [comment]
Nice!

But why wouldn't we use the constraint `^3.0` instead of `~3.0.0`? Isn't the library versioned with [semver](https://semver.org/) in mind?
Because of this limited constraint, we're now missing out on release [3.1.0](https://github.com/wikimedia/less.php/releases/tag/v3.1.0) which should contain some small performance improvements for Magento: https://github.com/wikimedia/less.php/pull/14

Also, in my opinion, try to only update that specific package version in the `composer.lock` file, all those other package updates you've added are out of scope and not related. I'd run `composer update wikimedia/less.php` instead of `composer update`, no?

**Comment by mrtuvn** [comment]
Thanks you for advices

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Linked it to php8 project, as it going to bring php8 support

**Comment by mrtuvn** [comment]
Ok now we re-targeted to php8-develop

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Could you also update the dependency in the framework's composer.json file?
https://github.com/magento/magento2/blob/2196548ebc06fd42b0bcc2461460354c1400cdc7/lib/internal/Magento/Framework/composer.json#L43

**Comment by mrtuvn** [comment]
updated file composer.json in framework directory

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@sivaschenko, any thoughts on why static tests are failing?

**Comment by mrtuvn** [comment]
@magento run Static Tests, Integration Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by sivaschenko** [comment]
@ihor-sviziev no thoughts yet, figuring it out

**Comment by mrtuvn** [comment]
Just wonder if we could have built-in php parser less official instead depend on external package

**Comment by hostep** [comment]
@mrtuvn: Why not open issues for missing functionality or contribute with fixes to https://github.com/wikimedia/less.php/, that sounds like much less work than building a compiler from scratch again?

**Comment by sivaschenko** [comment]
@magento create issue

**Comment by sivaschenko** [comment]
@magento run Static Tests

**Comment by sivaschenko** [comment]
@ihor-sviziev @mrtuvn Static tests have been fixed. To achieve this I've updated composer.json file in EE repo and linked a related PR

**Comment by sivaschenko** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B,Integration Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B,Integration Tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Review by ihor-sviziev — APPROVED** [review]

**Pull request merged**
