### PR TITLE
Magento_Authorization model Rules/Role calling a resource model function update, that is not exist in resource model(Rules/Role)

### LINKED ISSUE #30756: Magento_Authorization model Rules/Role calling a resource model function update, that is not exist in resource model(Rules/Role)
### Preconditions (*)

Magento 2.4-develop

### Steps to reproduce (*)

Call `Magento\Authorization\Model\Rules::update` or `Magento\Authorization\Model\Role::update`method

[Magento\Authorization\Model\Role](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Authorization/Model/Role.php)
[Magento\Authorization\Model\Rules](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Authorization/Model/Rules.php)

### Actual result (*)
Fatal error. Update method is not defined.

### Expected result (*)
The update method for both Role and Rules should be marked as deprecated with see reference to save method.

```
@deprecated
@see \Magento\Authorization\Model\Rules::save
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by engcom-Charlie**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#30756
### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by shikhamis11 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, thank you for the review.
[ENGCOM-8791](https://jira.corp.magento.com/browse/ENGCOM-8791) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable
Method `update()` was marked as depricated

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Pull request merged**
