### PR TITLE
Use one format in all places for array_merge

### LINKED ISSUE #30005: [Issue] Use one format in all places for array_merge
This issue is automatically created based on existing pull request: magento/magento2#30002: Use one format in all places for array_merge

---------
Fix potential issues when no items in array
Convert all array_merge into single format

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ihor-sviziev**
Fix potential issues when no items in array
Convert all array_merge into single format, related to https://github.com/magento/magento-coding-standard/pull/195

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30005: Use one format in all places for array_merge

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@sidolov @naydav @lenaorobei could you add some info why integration & web api tests are failing?

**Comment by sidolov** [comment]
@ihor-sviziev I see an error in console
```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\TestFramework\Workaround\Override\Config\RelationsCollector::getRelations() must be of the type string, array given, called in /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Workaround/Override/Config/RelationsCollector.php on line 53 and defined in /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Workaround/Override/Config/RelationsCollector.php:47
```

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests, WebAPI Tests, Static Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@sidolov could you add some info why integration tests are failing? I don’t see any failures in test results

**Comment by sidolov** [comment]
@ihor-sviziev `Warning: array_replace(): Expected parameter 2 to be an array, null given in /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Annotation/AbstractDataFixture.php:71.`

**Comment by ihor-sviziev** [comment]
@sidolov do you have some additional info? on which magento version this fail happened? On which test case?

I can fix this specific issue, but it's not clear why my changes caused it, so potentially they might also break something else that isn't shown.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@ihor-sviziev unfortunately, the log does not contain the information about the test which triggered the error.

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

**Comment by lbajsarowicz** [comment]
@magento run all tests
✔️  @ihor-sviziev `Integration Tests` are green, I trigger all the tests run to have it all green.

**Comment by ihor-sviziev** [comment]
@lbajsarowicz I reverted few commits in order to find where it starts to fail, I’m going to bring back some changes in order to find root of the cause

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
I reverted all changes that were causing integration tests failures and extracted them to https://github.com/magento/magento2/pull/30153, will debug them separately.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by lbajsarowicz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-8261](https://jira.corp.magento.com/browse/ENGCOM-8261) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
QA not applicable

**Pull request merged**
