### PR TITLE
Replace repetitive actions with Action Groups in AdminCreateSimpleProductNegativePriceTest

### LINKED ISSUE #32505: [Issue] Replace repetitive actions with Action Groups in AdminCreateSimpleProductNegativePriceTest
This issue is automatically created based on existing pull request: magento/magento2#32467: Replace repetitive actions with Action Groups in AdminCreateSimpleProductNegativePriceTest

---------

### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run the test in the local environment and verified that it run successfully

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run the test in the local environment and verified that it run successfully

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32505: Replace repetitive actions with Action Groups in AdminCreateSimpleProductNegativePriceTest

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Integration Tests, Functional Tests EE, Functional Tests B2B

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests EE, Functional Tests B2B, WebAPI Tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8971](https://jira.corp.magento.com/browse/ENGCOM-8971) has been created to process this Pull Request

**Pull request merged**
