### PR TITLE
Fix wishlist/cart/compare race condition

### PR DESCRIPTION
**Pull request by LumavCommerce**
Currently Mage_Customer, is expecting to catch ajaxCompletes and submits, if it loads too late however it can't do that, causing the cache not to be invalidated and failing to update the required sections.

### CODE REVIEW

**Comment by adragus-inviqa** [comment]
Is it ok for a module from lib to depend on a module-specific module? Can't the dependency be declared in some other way?

**Comment by LumavCommerce** [comment]
You are correct, I think there might be some ordering option in requireJs.

**Comment by orlangur** [comment]
@adragus-inviqa,

> Is it ok for a module from lib to depend on a module-specific module?

Nope.

> Can't the dependency be declared in some other way?

Block `lib/web/mage/dataPost.js` execution until customer-data is loaded? I don't think so.

> Mage_Customer, is expecting to catch ajaxCompletes and submits, if it loads too late however it can't do that, causing the cache not to be invalidated and failing to update the required sections.

@AedesWeb, could you please provide more details on this? ajaxComplete and submit handlers will be attached as soon as DOM is ready. If there is some race condition in "wishlist/cart/compare" then those components should have dependency on customerData.

**Comment by LumavCommerce** [comment]
@orlangur 
The issue is that you can submit the form before the frontend cache(customerData), which has not yet been loaded can listen to the changes. 
In a perfect world I would refactor the customerData to the core(which actually makes sense since its the browser side cache manager, pretty much everything depends on it).
https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/view/frontend/web/js/customer-data.js#L361
https://github.com/magento/magento2/blob/develop/lib/web/mage/dataPost.js#L42

**Comment by orlangur** [comment]
> The issue is that you can submit the form before the frontend cache(customerData), which has not yet been loaded can listen to the changes. 

That's perfectly fine. It is working this way for any other event handler bindings.

If all scripts do not load and initialize within reasonable time, you should optimize your store instead of hacking core. Also in a particular case you can display form to user no earlier than everything important executed.

**Comment by LumavCommerce** [comment]
@orlangur Sadly for our customers, quality is above "evangelism", a race condition is unacceptable, even if it is 100-500ms.  This was a simple fix(it works).  However magento should refactor this.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Fix-wishlist-cart-compare-race-condition/idi-p/45111).

**Comment by orlangur** [comment]
@AedesWeb, I fully agree with "magento should refactor this" but I don't believe adding symptomatic fixes here and there is the way to go. It's not about evangelism.

Some UI elements are flickering currently due to design flaws in customer data. This needs to be solved in general and of course _any_ event handler bindings must occur with customer data mechanism taken into consideration.

Problem with suggested fix is that it adds implicit dependency on customer data implementation (in particular, `submit` event handler binding). Similar fix would be ok if, for example, a dependency on some event handlers registry (also used by `customer-data.js`) would be added. In such case it would be clear on which particular functionality we rely in both `lib/web/mage/dataPost.js` and `customer-data.js` and how they should play altogether.

**Comment by omiroshnichenko** [comment]
@orlangur is right. @AedesWeb You can`t add dependency on customer module from lib. Also, your solution not fix issue generally. Customer data initiated throw x-magento-init(magento2ce/app/code/Magento/Customer/view/frontend/templates/js/customer-data.phtml) mechanism that start parsing page when document ready. To fix this issue we need to change customer data initialize order or disable wishlist/cart/compare actions before customer data init.

**Pull request closed without merging**
