### PR TITLE
MAGETWO-86164 (Issue 12914) product Qty decimal related issues (both front-end and back-end)

### PR DESCRIPTION
**Pull request by vasilii-b**
## Description
All issues below are described in #12914 

#### Steps to reproduce:
1. Create new product/ edit existing one
2. Open **Advanced Inventory** pop-up  under  **Quantity**
3. Set **Qty Uses Decimals** to *Yes*
4. Set **Qty** value to decimal value
5. Set **Enable Qty Increments** to *Yes*
6. Set  **Qty Increments** a decimal value
7. Press DONE (may skip this step)
8. Open **Advanced Inventory** pop-up  under  **Quantity** (optional if 7 was skipped)
9. Set Set **Qty Uses Decimals** to *No*
10. Set **Qty** value to integer value
11. Set **Enable Qty Increments** to *No*
12. Press DONE or the X icon to close the button

#### Expected Result
Close the **Advanced Inventory** pop-up

#### Actual result
Pop-up not closed and no errors are visible

### [2] Product Tiered Pricing Issue

**Steps to reproduce**
1. Create Simple Product
2. Set Inventory to 100
3. Set "Qty Uses Decimals" in Advanced Inventory to "Yes"
4. Set Base Price to 3.99
5. Open Advanced Pricing tab
6. Set a Tiered Price for Qty of .5 and price of 2.99
7. Save

#### Steps to reproduce
1. Open Advanced Inventory
2. Set "Enable Qty Increments" to "Yes"
3. Set "Qty Increments" to ".5"
4. Save

#### Expected result
During each of the above scenarios (2,3), the product should save and allow tiered pricing and qty increments to work with decimal-based inventory

#### Actual result
Product does not save, admin user is given error stating "Please enter a valid number"

#### Steps to reproduce
1. Create Simple Product
2. Set Inventory to 100
3. Set "Qty Uses Decimals" in Advanced Inventory to "Yes"
4. Set Base Price to 3.99
5. Open Advanced Pricing tab
6. Set a Tiered Price for Qty of 1.5 and price of 2.99
7. Save
8. Open Advanced Pricing pop-up

#### Expected result
Tier price Qty is 1.5

#### Actual result
Tier price Qty is 1

#### Steps to reproduce
Use the same steps from [1] or [4]

#### Expected result
In cart popup, cart page, checkout cart summary product Qty appear with decimals (if applicable)

#### Actual result
In cart popup, cart page, checkout cart summary product Qty appear without decimals

### CODE REVIEW

**Comment by rogyar** [comment]
Hello @vasilii-b.
Since the issue is actual for 2.3 as well, please, create a pull request to the 2.3-develop branch as well. Thank you

**Comment by duffner** [comment]
@rogyar and @vasilii-b, will this be backported to  2.2.X?    If not, do we know when to expect the 2.3 release date ?

**Comment by vasilii-b** [comment]
@rogyar a new PR #13359 for `2.3-develop` was created.
Thank you!

@duffner I'm sorry I can't answer your question.

**Comment by rogyar** [comment]
Please, fix the failed tests. Thanks

**Comment by rogyar** [comment]
@duffner Yes, if current PR is accepted it will be merged into the 2.2 mainline.

**Comment by vasilii-b** [comment]
@rogyar,

Need your advice on [this unit test](https://travis-ci.org/magento/magento2/jobs/333152794):
I had a look on the test `Magento/Bundle/Test/Unit/Ui/DataProvider/Product/BundleDataProviderTest.php` ,`testGetData()` method and wonder if the way `$items` are defined is correct:
```
$items = ['testProduct1', 'testProduct2'];
```
Question: Shouldn't it be an array for each item with data like `entity_id`,  `sku`, `qty`, etc ?

Thank you in advance for help!

**Comment by rogyar** [comment]
Hi @vasilii-b. I don't think so 
`$this->getModel()->getData()` will return an instance of `\Magento\Bundle\Ui\DataProvider\Product\BundleDataProvider` which has `getData()` method that returns the following construction:

```php
return [
            'totalRecords' => $this->getCollection()->getSize(),
            'items' => array_values($items),
        ];
```

Also, `getSize()` of the collection is mocked in our case as well as `toArray()`. So, we basically assert the `$expectedData` which is mocked almost completely.

I would recommend running the test on a 2.2-develop branch in order to ensure that there's no issue.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=13284) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=13284) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: vasilii-b<br/>:x: Vasilii Burlacu<hr/>**Vasilii Burlacu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by rogyar** [comment]
@vasilii-b. I'm closing this issue due to inactivity. Feel free to reopen it when you decide to proceed. Thank you

**Pull request closed without merging**
