### PR TITLE
Fixed Layered Navigation Url not rewrite on home page

### LINKED ISSUE #16362: Layered Navigation Url not rewrite on home page
### Preconditions

1. Magento 2.4-develop
2.  PHP 7.3

Have 2 simple products assigned to a category (Id = 3 in my case);
### Steps to reproduce

1.  Go to STORES > Configuration > General > Web > Default Pages and set **Default Web URL** to `catalog/category/view/id/3`
2. Reindex data, flush cache;
3. Go to frontend -> Homepage;

### Expected result

Category showing on home page.
Layered Navigation Url should be
`http://local.test/consumer-electric.html?manufacturer=15`

### Actual result

Category showing on home page.
Layered Navigation Url not rewrite
`http://local.test/catalog/category/view/id/3/?manufacturer=15`

### PR DESCRIPTION
**Pull request by pusachev**
- added RequestPathProviderInterface and functionality that try found request_path by target_path
- added plugin that set request path to Request if request from homepage

### Fixed Issues (if relevant)

1. Fixes magento/magento2#16362 : Issue title Layered Navigation Url not rewrite on home page

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24751) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=24751) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: pusachev<br/>:x: Pavel Usachev<hr/>**Pavel Usachev** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by ihor-sviziev** [comment]
It's actually not clear why we need to make category as homepage.
Just raised question about use-case here:
https://github.com/magento/magento2/issues/16362#issuecomment-536429231

**Comment by ihor-sviziev** [comment]
I've put this PR on hold till expected result will be approved / defined by PO:
https://github.com/magento/magento2/issues/16362#issuecomment-585737671

**Comment by ihor-sviziev** [comment]
As we discussed with @lenaorobei on slack - this PR should be moved to "to approve" status.

What should be approved - is this really valid issue that have to be fixed? It's not going to my mind any use case where category could be used as homepage.

**Comment by lenaorobei** [comment]
Hi @pusachev, I've contacted our product team to confirm the use case. I will keep you in the loop regarding this.

**Comment by pusachev** [comment]
Hi @lenaorobei @ihor-sviziev 

Thanks for processing this PR. As I discuss with @ihor-sviziev and Yevhen Sentiabov  I will fix some point with my solution. I will fix this in 1 - 2 week.

Best Regards
Pavel

**Comment by ihor-sviziev** [comment]
@pusachev let's wait for confirmation that this is real issue and we need to fix it.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @pusachev,
According to feedback from PO https://github.com/magento/magento2/issues/16362#issuecomment-591549636 - we need to support this case, so we can accept your pr.
I just double checked - seems like updating routers isn’t correct solution here, looks like we need to fix part that generates url.
Could you update your PR?

**Comment by ihor-sviziev** [comment]
Hi @pusachev,
Will you be able to update your PR?

**Comment by pusachev** [comment]
Hi @ihor-sviziev Yep. Sory with the quarantine I have a lot of works. I try to update PR in next week 

Thanks.

**Comment by ihor-sviziev** [comment]
@pusachev sure, will wait 👍

**Comment by ihor-sviziev** [comment]
Hi @pusachev,
I'm closing this PR due to inactivity.
Feel free to re-open or just create new PR based on my feedback in https://github.com/magento/magento2/pull/24751#pullrequestreview-365104982?

Thank you so much for contribution!

**Pull request closed without merging**
