### PR TITLE
Update static block in nginx.conf.sample

### PR DESCRIPTION
**Pull request by jaideepghosh**
Update the 'nginx.conf.sample' to allow the browsers for accessing the static contents even in multi-site mode also.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @jaideepghosh. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by jaideepghosh** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @jaideepghosh. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @jaideepghosh, here is your [new Magento instance](https://pr-21045.instances.magento-community.engineering).
Admin access: [https://pr-21045.instances.magento-community.engineering/admin](https://pr-21045.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by jaideepghosh** [comment]
@magento-engcom-team help

**Comment by ihor-sviziev** [comment]
Hi @jaideepghosh,
What do you mean by "allow the browsers for accessing the static contents even in multi-site mode"? What the issue do you have?
It's not clear what are Steps to reproduce, Actual Expected result. Could you write them?

**Comment by jaideepghosh** [comment]
Hi @ihor-sviziev 
In the default repository, magento contains a file named: `nginx.conf.sample`. In this file the static block requires a simple fix.
The issue was: when we configured multi-site, all the sites were loading including the static file contents with status code `200` but the css were not applying in the frontend. So in order to fix such issue, we did the change in the `nginx.conf.sample` file.
Please have a look on the commit [here](https://github.com/jaideepghosh/magento2/commit/8ec9a3ab8bfe02aa7bb4da56249dfe493c7fb049).

**Comment by ihor-sviziev** [comment]
Hi @jaideepghosh,
Thank you! Will test it myself.

**Comment by jaideepghosh** [comment]
Hi @ihor-sviziev 
As I can see that the all checks has been passed, then why my Merge is Blocked.
Please help me merge the changes.

**Comment by ihor-sviziev** [comment]
Hi @jaideepghosh,
First of all one of maintainers need to approve your change, then it should be tested and only after that your change will be merged by EngCom team. No action items needed from your side, at least for now

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-4193](https://jira.corp.magento.com/browse/ENGCOM-4193) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@jaideepghosh thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by jaideepghosh** [comment]
Hey @ihor-sviziev 
Can you guide me to proceed next to merge this PR. I'm getting the following view:
screen shot 2019-02-11 at 11 52 02 am

**Comment by ihor-sviziev** [comment]
Hi @jaideepghosh,
It’s ok, people from magento will merge this PR

**Pull request merged**
