### PR TITLE
Issue30520

### LINKED ISSUE #30520: Status Payment Review is not visible in front of the store.
Our method reaches payment_review status, and can stay on it for up to 72 hours, on the store frontend the consumer sees the order as "processing".

This process is done here:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/Order/Config.php#L56

But I don't see any logical reason for that. I seek guidance as to why this is applied.

### Preconditions
1. Magento 2.2+
2. Our method reaches payment_review status, without being a "fraud" state.

### Steps to reproduce
1 .Implement a customized payment method that will reach the status of payment_review.
2. Make the purchase using this method.

### Expected result
1. In the customer's view, obtain the status "payment_review"

### Actual result
1. In the customer's view, the status is "processing"

### Possible solution
Delete the line. However, I would like to understand the possible impact of this.
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

### PR DESCRIPTION
**Pull request by elisei**
### Description
Orders with payment_review and state status other than "fraud" are visible on the store frontend as "processing".

### Fixed Issues
1. Fixes magento/magento2#30520

### Manual testing scenarios (*)
1. Implement a customized payment method that will reach the status of payment_review.
2. Make the purchase using this method.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by elisei** [comment]
@magento run all tests

**Review by orlangur — CHANGES_REQUESTED** [review]
Hey @elisei! Here is why this line was initially introduced: https://github.com/magento/magento2/commit/46aaef5098a90528c5a49935be547516a3707073

Do you think Payment Review state should be really shown to customer?

**Comment by elisei** [comment]
Hi @orlangur,

yes, this is really important for us, since in our Gateway payments can stay at this stage for up to 48 hours.

changing will have no impact in the event of fraud.

**Comment by elisei** [comment]
Hi @orlangur,

can we evolve in that fix?

**Comment by ishakhsuvarov** [comment]
Hi
I am closing this PR for now as it seems like it has become stale and still needs work.

Please feel free to reopen if you wish to continue.

Thanks!

**Pull request closed without merging**
