### PR TITLE
Update link to bug bounty program

### PR DESCRIPTION
**Pull request by fahu**
### Description (*)
The bug bounty program has moved from https://hackerone.com/magento to https://hackerone.com/adobe.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@fahu please, sign Adobe CLA

**Comment by engcom-Alfa** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B, Adobe CLA Signed?

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

This PR has one support file [SECURITY.md](https://github.com/magento/magento2/pull/35378/files#diff-f6ed156e4bf5c791680662464b94ea5d753f219ee816b385f67870e2c0d7d4c7) update, where the reference link has been updated.

Verified the newly replaced link and found it is the appropriate one!

There is **no other manual testing is required** in this case, and there is no impact of any other features.
Hence marking it with _Merge In Progress_.

Thanks for the contribution and collaboration @fahu 
Kindly conclude with the final step from your end [mentioned above](https://github.com/magento/magento2/pull/35378#issuecomment-1112401481).
Thanks

**Review by sdzhepa — CHANGES_REQUESTED** [review]
@fahu 
Please sign the "Adobe CLA" without it we are not able to deliver this PR.

**Comment by fahu** [comment]
Hello everyone, sorry for not signing the CLA and therefore keeping the PR open for so long. I switched phone and didn't receive push notifications. Anyways, it's updated now.

Big thanks to Eugene Shakhsuvarov for contacting me on Twitter, I really appreciate the extra effort.

**Comment by fahu** [comment]
As it's my first contribution to the Magento project: Is there anything else I need to do in order to get this completed?

**Comment by ishakhsuvarov** [comment]
@fahu I think nothing else is needed from you at this point. Getting it processed and delivered now.

**Pull request merged**
