### PR TITLE
Issue 33767: Product price updated using Manage Base Price API is not…

### LINKED ISSUE #33767: Product price updated using Manage Base Price API is not updating in Store front Catalog Search Results page and Admin panel
### Preconditions (*)
1. Magento 2.4-develop

### Steps to reproduce (*)

1. Generate Admin access token using POST request:  storeurl/rest/default/V1/integration/admin/token
2. Send POST API request for sync product: storeurl/rest/V1/products/base-prices. (Update Price using below Payload):
**Payload:**
```
{
  "prices": [
    {
      "price": 85.67,
      "store_id": 1,
      "sku": "Test PRice"
    }
  ]
}
```

3. Reindex and clear cache
4. Navigate to Front-end -> Verify Price in Search Results page and Product Details page 
**Issue 1:** Price updated through API is getting updated in Front-end Product Details page only but not getting updated in Catalog Search Results page and Admin - Products page
5. Navigate to Admin - Catalog - Products - Edit same Product - Update new price say ex: 90 and save
6. Reindex and clear cache
7. Navigate to front-end - Product Details page
**Issue 2:**  New Price updated from Admin panel is not getting updated in Front-end product details page (Old value saved using API is displayed in Front-end Product Details page)
### Expected result (*)
Base price should be updated in both Search Results page, Product Details page and Admin -> Catalog - > Products page

### Actual result (*)
**Issue 1**. Price updated through API is getting updated in Front-end Product Details page only but not getting updated in Catalog Search Results page and Admin - Products page
Admin PDP

Updated price through API : 85.67 is updated in Product Details page only
ProductDetailsPage

Products_Inventory

TestPrice_Prods

**Issue 2:**  New Price updated from Admin panel is not getting updated in Front-end product details page (Old value saved using API is displayed in Front-end Product Details page)
ProductsPage

TestPrice

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rogerdz**
### Description (*)

Price saved per store view when  Catalog Price Scope global

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33767

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Review by edenduong — CHANGES_REQUESTED** [review]
Hi @rogerdz ,
Thank you for your contribution. Could you please cover this PRs change by Unit Test?

**Comment by rogerdz** [comment]
Hi @edenduong,
I added unit test

**Comment by rogerdz** [comment]
@magento run all tests

**Review by edenduong — APPROVED** [review]
Thank you for your contribution !

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
Install fresh Magento `2.4-develop`

**Manual testing scenario:**
1. Generate Admin access token using POST request: `storeurl/rest/default/V1/integration/admin/token`
2. Send POST API request for sync product: `storeurl/rest/V1/products/base-prices`. (Update Price using below Payload):
**Payload:**
```
{
  "prices": [
    {
      "price": 85.67,
      "store_id": 1,
      "sku": "Test PRice"
    }
  ]
}
```
3. Reindex and clear cache
4. Navigate to Front-end -> Verify Price in Search Results page and Product Details page
**Issue 1:** Price updated through API is getting updated in Front-end Product Details page only but not getting updated in 
5. Catalog Search Results page and Admin - Products page
6. Navigate to Admin - Catalog - Products - Edit same Product - Update new price say ex: 90 and save
7. Reindex and clear cache
8. Navigate to front-end - Product Details page
**Issue 2:** New Price updated from Admin panel is not getting updated in Front-end product details page (Old value saved using API is displayed in Front-end Product Details page)
**In my case Issue 2 is not reproducible.**
**Before:** :heavy_multiplication_x: Price was not getting updatd in the frontend as well as in admin.
Screenshot 2022-09-21 at 1 27 35 PM

image


**After:** :heavy_check_mark:  
**Admin:**
image

**Product page:**
image

Since automation is covered no additional manual test case is required to be added.

**Comment by engcom-Lima** [comment]
Looking bot moved this ticket accidently from Merge In progress. Hence, moving back to merge in progress.

**Pull request merged**
