### PR TITLE
Issues 6729, 6457, 7362: Configurable product price options provider

### PR DESCRIPTION
**Pull request by simpleadm**
Fix for lowest price options provider to retrieve products with additional attributes

### Description
_LowestPriceOptionsProvider_ returns products without attributes which are used for price calculation (e.g. tax adjustment)

### Fixed Issues
1. magento/magento2#6729: Configurable product old price with taxes displayed wrong
2. magento/magento2#6457: Expired special_price is still shown for configurable products when no variant is selected
3. magento/magento2#7362: Special price vigency for configurable childs (simple products associated) doesn´t work

### Manual testing scenarios
1. Create configurable product with tax, price is defined for each sku (Stores > Configuration > Sales > Tax > Catalog Prices = Including Tax)
2. Create tax rule 25%
3. Apply this tax rule to the product
4. In tax settings set all values to display prices without tax (Stores > Configuration > Sales > Tax > Display Prices = Excluding Tax)
5. Check old configurable product price

### CODE REVIEW

**Comment by okorshenko** [comment]
Hi @simpleadm Thank you for your pull request. Could you please resolve the conflicts the double-check if the fix is still needed. Please check this commit: https://github.com/magento/magento2/commit/1ab9b26828cd4da268e9a7481d4969bffb1460c1

**Comment by simpleadm** [comment]
Hi @okorshenko.

Pull Request is still relevant. Commit: 1ab9b26 is fixing only 6457 and 7362 issues.
Conflicts were resolved, please take a look.

P.S. code style was changed to prevent "Line exceeds maximum limit of 120 characters; contains 122 characters" error.

**Comment by okorshenko** [comment]
Hi @simpleadm thank you for update

**Comment by ishakhsuvarov** [comment]
@simpleadm 
I have tried to reproduce the issue with and without the fix, but I do not notice any difference in the behavior. Could you please be more specific with the preconditions, steps to reproduce and actual/expected result?
Thanks!

**Comment by ishakhsuvarov** [comment]
Hi @simpleadm 
Are there any updates regarding manual testing steps?
Thanks!

**Comment by simpleadm** [comment]
Hi @ishakhsuvarov,

Please accept my apologies for the delayed response. 

Issue with price was fixed. But my pull request is still useful and i will try to explain use cases.

- Update tax configuration. Products price should include tax, but it should be displayed without tax (Stores > Configuration > Sales > Tax  [Catalog Prices = Including Tax, Display Product Prices In Catalog = Excluding Tax, Shopping Cart Display Settings = Excluding Tax, Orders, Invoices, Credit Memos Display Settings =  Excluding Tax]) - http://prntscr.com/fxhog8 http://prntscr.com/fxholh
- Create configurable product with tax, price is defined for each sku (e.g. 100$)
- Add special price for a child simple product (e.g. 60$) http://prntscr.com/fxhprq
- Create tax rule 25%
- Apply this tax rule to the product
- Check "Regular Price" will be displayed with taxes - http://prntscr.com/fxhrlu (_custom popup with product information_)

In earlier Magento builds regular price used to display on configurable products and it was wrong. Now it renders by JS. Also in product listing default magento doesn't display regular price (`<?php if (!$block->isProductList() && $block->hasSpecialPrice()): ?>` app/code/Magento/ConfigurableProduct/view/base/templates/product/price/final_price.phtml ) for configurable products (if it will display, the regular price will be wrong). 

But the bug can be very painful for third party developers. For example we need to have own block or widget with configurable product listing. So we will:

- extends from \Magento\Catalog\Block\Product\AbstractProduct
- create own template were use getProductPrice method `echo $block->getProductPrice($block->getProduct())`
- get wrong "Regular Price"

Hope now it's more clear:)
Thanks.

**Comment by okorshenko** [comment]
Hi @simpleadm could you please accept the invite on GitHub to join magento team?

**Comment by simpleadm** [comment]
Hi @okorshenko, invite have been accepted.
Thanks, i appreciate it.

**Pull request merged**
