### PR TITLE
Fix issue #26276 with clonning quote billing address street

### PR DESCRIPTION
**Pull request by yutv**
### Description (*)

Fixed cloning billing address to do it recursively including the street array.

### Fixed Issues (if relevant)

1. magento/magento2#26276: Checkout. Quote Address Street cloning issue

### Manual testing scenarios (*)

1. Register an customer account
2. Add an address and mark it **as billing and shipping**
3. Go to the **second** step of checkout
4. Run the following code in the developer console

        # Output and remember what is shipping address city and street
        require('Magento_Checkout/js/model/quote').shippingAddress().city
        require('Magento_Checkout/js/model/quote').shippingAddress().street[0]

        # change the billing address City and Street
        require('Magento_Checkout/js/model/quote').billingAddress().city = "Test"
        require('Magento_Checkout/js/model/quote').billingAddress().street[0] = "123 Main street"

        # Check if shipping address city and street are changed (they should not change after the fix)
        require('Magento_Checkout/js/model/quote').shippingAddress().city
        require('Magento_Checkout/js/model/quote').shippingAddress().street[0]

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by nuzil** [comment]
@yutv 
can you please sign CLA?

**Comment by yutv** [comment]
> @yutv
> can you please sign CLA?

Signed

**Review by nuzil — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-6615](https://jira.corp.magento.com/browse/ENGCOM-6615) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@yutv thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

**Before:**
after

**After:**
before

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
