### PR TITLE
Update languages.phtml

### LINKED ISSUE #27540: Magento Store Switch - 2 store views, 2 domains.  "The store that was requested wasn't found. Verify the store and try again."
### Preconditions (*)

1. Magento 2.3.4 (fresh installation, self hosted)
2. 2 different domains
3. 1 website, 1 store, 2 store views.
4. Store view "en" associated at domain example.com from Magento backend
5. Store view "it" associated at domain example.it from Magento backend
6. Apache 2.4.38 (Debian 10)
7. _.htaccess_ configurated like that:
        `SetEnvIf Host ^(.*)\.example\.com MAGE_RUN_CODE=en`
        `SetEnvIf Host ^(.*)\.example\.com MAGE_RUN_TYPE=store`
        `SetEnvIf Host ^(.*)\.example\.it MAGE_RUN_CODE=it`
        `SetEnvIf Host ^(.*)\.example\.it MAGE_RUN_TYPE=store`

### Steps to reproduce (*)

1. Go to _example.com/my-beautiful-product.html_
2. Switch store view from _en_ to _it_

### Expected result (*)

1. Switch to _it_ store view at example.it/my-beautiful-product.html

### Actual result (*)

1. Schermata 2020-03-10 alle 19 25 08

2. It takes me to _it_ store view home and it shows this error: **The store that was requested wasn't found. Verify the store and try again.**

3. I tried to hardcode the store view codes in */vendor/magento/module-store/Controller/Store/SwitchAction.php* at row 106 and the $requestedUrlToRedirect :

```
        ...
        public function execute()
        {
            $targetStoreCode = $this->_request->getParam(
                \Magento\Store\Model\StoreManagerInterface::PARAM_NAME
            );
            $fromStoreCode = $this->_request->getParam(
                '___from_store',
                $this->storeCookieManager->getStoreCodeFromCookie()
            );
    
            $requestedUrlToRedirect = 'https://example.it/my-beautiful-product.html';
            $redirectUrl = $requestedUrlToRedirect;
            // $requestedUrlToRedirect = $this->_redirect->getRedirectUrl();
            // $redirectUrl = $requestedUrlToRedirect;

            $error = null;
            try {
                $fromStore = $this->storeRepository->get('en');
                $targetStore = $this->storeRepository->getActiveStoreByCode('it');
                // $fromStore = $this->storeRepository->get($fromStoreCode);
                // $targetStore = $this->storeRepository->getActiveStoreByCode($targetStoreCode);
            } catch (StoreIsInactiveException $e) {
                $error = __('Requested store is inactive');
            } catch (NoSuchEntityException $e) {
                $error = __("The store that was requested wasn't found. Verify the store and try again.");
            }
            if ($error !== null) {
                $this->messageManager->addErrorMessage($error);
            } else {
                $redirectUrl = $this->storeSwitcher->switch($fromStore, $targetStore, $requestedUrlToRedirect);
            }

            $this->getResponse()->setRedirect($redirectUrl);
        }
        ...
```

Then I switched from Italian store view to the English one and **it worked!** So **it seems it does not able to get the correct values of $targetStoreCode, and $requestedUrlToRedirect**. Any ideas?

### PR DESCRIPTION
**Pull request by kamzata**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/27540 Store switch doesn't work correctly.

### Manual testing scenarios (*)

1. Tested on Magento CE 2.3.4

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Seems like this PR just reverts chsanges from https://github.com/magento/magento2/pull/15961

**Review by sidolov — CHANGES_REQUESTED** [review]
@kamzata initial fix was made to resolve the bug mentioned in https://github.com/magento/magento2/pull/15961. Looks like it will start reproducing after your fix. Could you please take a look? Most likely we need to find a better solution to fix both bugs.

**Comment by kamzata** [comment]
I cannot check anymore... now I'm running 2.4.0 and it works out of the box.

**Comment by ihor-sviziev** [comment]
Thank you ! In this caseI’m closing this PR

**Pull request closed without merging**
