### PR TITLE
Resolve Dupplicate Label in Sales->Transactions at Backend (issue 24040)

### LINKED ISSUE #24040: Dupplicate Label in Sales->Transactions at Backend
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Sales-> Transactions
3. Check the grid at "Payment Method"

image

### Expected result (*)

1. The label should be different 

### Actual result (*)

1. 
image

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#24040: Dupplicate Label in Sales->Transactions at Backend 

Solution: Title of the label in Paypal module should be different. 
=> Change in the config.xml

### Fixed Issues (if relevant)

1. magento/magento2#24040: Dupplicate Label in Sales->Transactions at Backend 

### Manual testing scenarios (*)

1. Go to backend
2. Sales-> Transactions
3. Check the grid at "Payment Method"

It should be different like this

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Stepa4man** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, here is your [Magento instance](https://i-24041-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24041-2-3-develop.instances.magento-community.engineering/admin](https://i-24041-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Stepa4man** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, here is your [new Magento instance](https://pr-24041.instances.magento-community.engineering).
Admin access: [https://pr-24041.instances.magento-community.engineering/admin](https://pr-24041.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by Stepa4man — APPROVED** [review]
Hi @edenduong, Thanks for your contribution.

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, thank you for the review.
[ENGCOM-5550](https://jira.corp.magento.com/browse/ENGCOM-5550) has been created to process this Pull Request
:eight_spoked_asterisk: @Stepa4man, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by edenduong** [comment]
@magento-engcom-team : Could I receive "Bug fix award" ? Thank you :)

**Pull request merged**
