### PR TITLE
Add suport of reading PNG JPEG Exif metadata

### LINKED ISSUE #1449: Create Exif reader
**Story** https://github.com/magento/adobe-stock-integration/issues/1183: Magento extracts image meta data from file

#### Implementation details
See: https://github.com/magento/adobe-stock-integration/wiki/Technical-Design:-Images-metadata-processing

### AC
- Covered with integration tests

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1449 Create Exif reader 

### Manual testing scenarios (*)

1. Upload image to th new media gallery from integration test fixtures exif_image.png or exif-image.jpeg
2. Discover in image details, metadata from exif segments exifst Title and Description

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magentor run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-8020](https://jira.corp.magento.com/browse/ENGCOM-8020) has been created to process this Pull Request

**Comment by Nazar65** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-8020](https://jira.corp.magento.com/browse/ENGCOM-8020) has been created to process this Pull Request

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed 
Metadata from exif segments exists in image details 
Screenshot_113

**Pull request merged**
