### PR TITLE
[Backport] Fix typo in database column comment

### PR DESCRIPTION
**Pull request by VitaliyBoyko**
Original PR: #13318

### Description
Fix typo in database column comment

### CODE REVIEW

**Review by DanielRuf — APPROVED** [review]

**Comment by VladimirZaets** [comment]
Hi, @VitaliyBoyko, Your fix introduce changes in the DB schema. Due to [Magento backward-compatible guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/backward-compatible-development/) we can't make changes to DB schema in 2.1 Magento version.

**Comment by DanielRuf** [comment]
@vladimir-k also not with `modifyColumn`?

I also see no mention of schema name changes (or what is the last parameter?).
https://devdocs.magento.com/guides/v2.1/contributor-guide/backward-compatible-development/#db-schema

**Comment by VladimirZaets** [comment]
@DanielRuf yes, you are right, the last parameter it's only comment. Our tests are failed on this fix, so I closed this PR, but in the current case I agree, we can merge it.

**Comment by magento-engcom-team** [comment]
Hi @VitaliyBoyko. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.1.15 release.

**Pull request merged**
