### PR TITLE
Use the correct way to make the page title translatable

### PR DESCRIPTION
**Pull request by arnoudhgz**
###Description
The page title always showed English, because the wrong method was being used to make it translatable.

Contribution checklist
### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)quest

#### Original Pull Request
Original PR was closed after being inactive and later could not be reopened again, therefore this new PR. Original PR: https://github.com/magento/magento2/pull/17643

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @arnoudhgz. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by arnoudhgz** [comment]
@VladimirZaets  I created the PR again after the original one (https://github.com/magento/magento2/pull/17643) was inactive for too long.

Could you please test the updated version? Thank you in advance.

**Review by larsroettig — APPROVED** [review]

**Review by larsroettig — CHANGES_REQUESTED** [review]
Please open this PR at 2.3 we don't accept direct  PR on  2.2.

**Comment by arnoudhgz** [comment]
@larsroettig Will do in the start of 2019.

**Comment by arnoudhgz** [comment]
@larsroettig my previous branch / fork were gone, but I created a new one: https://github.com/magento/magento2/pull/20940

**Pull request closed without merging**
