### PR TITLE
use UNDEFINED_OPTION_LABEL constant

### PR DESCRIPTION
**Pull request by Nolwennig**
use UNDEFINED_OPTION_LABEL constant instead of typed code

### Description (*)

use UNDEFINED_OPTION_LABEL constant instead of typed code

### Fixed Issues (if relevant)

no issue

### Manual testing scenarios (*)

1. use Magento\Sales\Model\Config\Source\Order\Status  as source_model in your system.xml 
2. go to your adminhtml page

### Questions or comments

get free to give me your feedback

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23183) <br/>All committers have signed the CLA.

**Comment by okorshenko** [comment]
@magento run Integration Tests build

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5248](https://jira.corp.magento.com/browse/ENGCOM-5248) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by sivaschenko** [comment]
Hi @Nolwennig thanks for the pull request! 

However, only literals are currently allowed as the first argument of __() method to make the phrases collection possible. So, unfortunately, we could not accept this contribution.

**Comment by Nolwennig** [comment]
**Thank you @sivaschenko for explanation!**

Sorry for the inconvenience. I haven't look https://github.com/magento/magento2/commit/842c92f97c72c42ec84854563530b7054df9f6e3#diff-2d8c7401b5c22e656b410c1ca1169c37 before ...

**So, I wonder what is the usefulness of `\Magento\Sales\Model\Config\Source\Order\Status::UNDEFINED_OPTION_LABEL` now ?**
_( If I refer to : https://github.com/magento/magento2/search?q=UNDEFINED_OPTION_LABEL this constants seems not used in magento2 scope )_

**Comment by sivaschenko** [comment]
@Nolwennig I think this constant should be marked as deprecated

**Comment by orlangur** [comment]
> this constant should be marked as deprecated

Strongly disagree 

> only literals are currently allowed as the first argument of `__()` method to make the phrases collection possible

To me it means nothing but that current poor implementation of phrase collector needs to be improved.

**Pull request closed without merging**
