### PR TITLE
Confirmation-pop-up-at-mobile-view-not-proper

### PR DESCRIPTION
**Pull request by priti2jcommerce**
### Fixed Issues (if relevant)

1. magento/magento2#20176 : Confirmation pop-up at mobile view not proper
2.

### Manual testing scenarios (*)

  1. Add product into cart
  2. remove product from minicart
  3. pop-up not showing proper at mobile view

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by irajneeshgupta** [comment]
This is dublicate PR ref -> https://github.com/magento/magento2/pull/20192/commits/2405145b09bc662bae632f17fc592e2978f29a96

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-20196.instances.magento-community.engineering).
Admin access: [https://pr-20196.instances.magento-community.engineering/admin](https://pr-20196.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-3966](https://jira.corp.magento.com/browse/ENGCOM-3966) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
