### PR TITLE
Spacing issue for Gift message section in my account

### PR DESCRIPTION
**Pull request by amjadm61**
### Description
Spacing issue for Gift message section in my account

### Fixed Issues (if relevant)

1. magento/magento2#22950: Spacing issue for Gift message section in my account

### Manual testing scenarios (*)

1. Admin: Add product with enable gift option
2. Front end: Add to cart product
3. Shopping cart: Add gift option data and place order
4. Review at my order gift option data

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23226) <br/>All committers have signed the CLA.

**Comment by amjadm61** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @amjadm61. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @amjadm61, here is your [new Magento instance](https://pr-23226.instances.magento-community.engineering).
Admin access: [https://pr-23226.instances.magento-community.engineering/admin](https://pr-23226.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hi @amjadm61,
looks like you made the commits from different accounts.
We won't be able to process your pull request if you don't sign the CLA from another account as well.

Please, squash all commits into a single one in order to clean up history.

Thank you!

**Comment by amjadm61** [comment]
@dmytro-ch i've signed the CLA from my committed account as well.

**Comment by dmytro-ch** [comment]
@amjadm61 , could you please, squash all commits into a single one, so the PR would not include the additional merge commits?

**Comment by amjadm61** [comment]
@dmytro-ch Squashed all commit to single one as per your suggestion

**Comment by amjadm61** [comment]
> @amjadm61 , could you please, squash all commits into a single one, so the PR would not include the additional merge commits?

@dmytro-ch could you please check?

**Comment by dmytro-ch** [comment]
@amacgregor, the merge commit still present in commits history.
Please make sure you pushed the changes to the remote repository.

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-5408](https://jira.corp.magento.com/browse/ENGCOM-5408) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
