### PR TITLE
#19846: Removed quote is_active check

### LINKED ISSUE #19846: REST API does not return items for inactive quotes
### Summary (*)
QuoteRepository and API quote requests do not return items or extension attributes for quotes that are not active. More specifically, QuoteRepository and API quote requests return all quote information **except** items and extension attributes, for quotes that are not active. The data should be returned whether the quote is active or not.

Verified on Magento 2.1.15; all versions 2.1.0 - 2.3.0 affected.

### Examples (*)
Steps to reproduce: 

1. Find or create an inactive quote: `select * from quote where is_active=0 limit 1;`
2. Query the API to fetch the inactive quote: `GET https://example.com/rest/V1/carts/2924`
3. See that the results indicate an item but contain no actual items.
```
{
    "id": 2924,
    "created_at": "2018-10-17 01:13:23",
    "updated_at": "2018-12-17 16:34:24",
    "is_active": false,
    "is_virtual": false,
    "items_count": 1,
    "items_qty": 1,
    "customer": {
...
```
4. Change the quote to active and repeat the API request. Note that it now contains the item(s):
```
{
    "id": 2924,
    "created_at": "2018-10-17 01:13:23",
    "updated_at": "2018-12-17 16:34:24",
    "is_active": true,
    "is_virtual": false,
    "items": [
        {
            "item_id": 4749,
            "sku": "ADDONS-USER-LICENSE-SUB",
            "qty": 1,
            "name": "Additional User License",
            "price": 500,
            "product_type": "simple",
            "quote_id": "2924"
        }
    ],
    "items_count": 1,
    "items_qty": 1,
    "customer": {
...
```

### Proposed solution
The issue is caused by this check in [\Magento\Quote\Model\QuoteRepository\LoadHandler->load()](https://github.com/magento/magento2/blob/2.3/app/code/Magento/Quote/Model/QuoteRepository/LoadHandler.php#L42):
```
    public function load(CartInterface $quote)
    {
        if (!$quote->getIsActive()) {
            return $quote;
        }
```

I suggest removing this if() statement entirely. The quote in question is already loaded and behaves normally otherwise, whether it is active or not. This active check and return *only* prevent the quote items and extension attributes from being assigned properly and returned with QuoteRepository and API requests. This results in unexpected behavior for inactive quotes compared to active ones.

### PR DESCRIPTION
**Pull request by ProcessEight**
- Removed quote is_active check from \Magento\Quote\Model\QuoteRepository\LoadHandler::load
- Will resolve #19846 
- See original ticket for manual testing details

### Description (*)

Remove if branch which checked whether the quote was active and if so, returned early from the method.
This will allow the QuoteRepository to return items and extension attributes for inactive quotes as well as active quotes.

### Fixed Issues (if relevant)

1. magento/magento2#19846: REST API does not return items for inactive quotes

### Manual testing scenarios (*)

Steps to reproduce:

1. Find or create an inactive quote: select * from quote where is_active=0 limit 1;
2. Query the API to fetch the inactive quote: GET https://example.com/rest/V1/carts/2924
3. Verify that the quote contains items and extension attributes.
4. Change the quote to active and repeat the API request. It should contain the same items.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23303) <br/>All committers have signed the CLA.

**Comment by dmytro-ch** [comment]
Hi @ProcessEight,
currently, the errors in tests indicate that there is some issue after changing the logic.
Please make sure your solution doesn't lead to additional issues for some specific cases by checking the failed tests.

Thank you!

**Comment by ProcessEight** [comment]
Hi @dmytro-ch 
I will review the failed tests and fix the issues.

**Comment by sidolov** [comment]
@ProcessEight , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
