### PR TITLE
fix QtyTest.php local failure

### LINKED ISSUE #31737: [Issue] fix QtyTest.php local failure
This issue is automatically created based on existing pull request: magento/magento2#31381: fix QtyTest.php local failure

---------

### Description (*)

composer version local run dev/tests/integration/testsuite/Magento/Catalog/Block/Adminhtml/Product/Composite/Fieldset/QtyTest.php failure

### Fixed Issues (if relevant)

No issues created

### Manual testing scenarios (*)

No manual testing required

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by engcom-Echo**
### Description (*)

composer version local run dev/tests/integration/testsuite/Magento/Catalog/Block/Adminhtml/Product/Composite/Fieldset/QtyTest.php failure

### Fixed Issues (if relevant)

No issues created

### Manual testing scenarios (*)

No manual testing required

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31737: fix QtyTest.php local failure

### CODE REVIEW

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8644](https://jira.corp.magento.com/browse/ENGCOM-8644) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by ihor-sviziev** [comment]
@engcom-Alfa does it works fine now on the composer based installation?

**Comment by engcom-Alfa** [comment]
Hi @engcom-Echo @ihor-sviziev.
Unfortunately, we are not able to reproduce the issue on a composer and git versions of Magento.

**Manual testing scenario:**
Run all integration tests from module Catalog

Actual Result: :heavy_check_mark: The _**QtyTest**_ test was successfully passed.


Perhaps this problem is better to consider the developers.

**Comment by ihor-sviziev** [comment]
@engcom-Alfa @engcom-Echo, are there any updates on testing this PR? It stuck for a month already.

**Comment by engcom-Foxtrot** [comment]
Closed as non-reproducible.

**Pull request closed without merging**
