### PR TITLE
Shipping Estimation: Prevent Quote Double Saving

### LINKED ISSUE #36648: [Issue] Shipping Estimation: Prevent Quote Double Saving
This issue is automatically created based on existing pull request: magento/magento2#35631: Shipping Estimation: Prevent Quote Double Saving

---------
### Description (*)
+ Removes a seemingly superfluous additional saving of the quote when estimating shipping
    + [The `Magento\Checkout\Model\Cart::save()` function also saves the quote in the same manner](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/Model/Cart.php#L593)
+ Only sets `collectShippingRates` once
    + [The `Magento\Checkout\Model\Cart::save()` function also sets this](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/Model/Cart.php#L591)

### Manual testing scenarios (*)
1. Install sample data
2. Add a product to the cart
3. Proceed to the cart page
4. Estimate shipping using valid address data
5. Ensure the available shipping methods are displayed
6. Ensure the selecting of a shipping method updates cart totals correctly

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by pykettk**
### Description (*)
+ Removes a seemingly superfluous additional saving of the quote when estimating shipping
    + [The `Magento\Checkout\Model\Cart::save()` function also saves the quote in the same manner](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/Model/Cart.php#L593)
+ Only sets `collectShippingRates` once
    + [The `Magento\Checkout\Model\Cart::save()` function also sets this](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/Model/Cart.php#L591)

### Manual testing scenarios (*)
1. Install sample data
2. Add a product to the cart
3. Proceed to the cart page
4. Estimate shipping using valid address data
5. Ensure the available shipping methods are displayed
6. Ensure the selecting of a shipping method updates cart totals correctly

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36648: Shipping Estimation: Prevent Quote Double Saving

### CODE REVIEW

**Comment by pykettk** [comment]
@magento run all tests

**Comment by pykettk** [comment]
@magento give me test instance

**Comment by pykettk** [comment]
@magento give me 2.4-develop instance

**Comment by pykettk** [comment]
Personal manual testing using the above instances presents the same (existing) behaviour.

#### 2.4 Develop Instance
2da598e733dcd48819a6848931afe176 instances magento-community engineering_checkout_cart_

#### PR Test Instance
7bc6b6cd1c80b4cb7a45ad4bf3a735b2 instances magento-community engineering_checkout_cart_

**Comment by pykettk** [comment]
@magento run all tests

**Comment by pykettk** [comment]
@magento run Functional Tests CE

**Comment by pykettk** [comment]
@magento run Static Tests

**Comment by pykettk** [comment]
@magento run all tests

**Comment by pykettk** [comment]
@magento run Static Tests

**Comment by pykettk** [comment]
@magento run Static Tests

**Comment by pykettk** [comment]
@magento run all tests

**Comment by pykettk** [comment]
Failing tests appear unrelated.

**Comment by pykettk** [comment]
@magento run all tests

**Comment by pykettk** [comment]
@magento run all tests

**Comment by pykettk** [comment]
@magento run Functional Tests EE

**Comment by engcom-Delta** [comment]
@magento create issue

**Pull request merged**
