### PR TITLE
Fixed : Getting error after dismiss admin notification

### LINKED ISSUE #36581: Magento 2.4.5CE - An error occurs when dismiss a task message
### Preconditions and environment

- Magento version 2.4.5CE

### Steps to reproduce

Example:
- Login Admin
- Go to Catalog > Products 
- Select one product
- Choose mass action Update attributes
- Update the Product Name and click Save
- At this point, new message will be added to top.
- Click X to dismiss the message > An error will be showed.

Video: https://www.loom.com/share/597167c0a4614a288ac636e8b804ed5e

### Expected result

Message is dismissed successfully

### Actual result

Message is dismissed successfully but an error still shows

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rshadab25**
### Description (*)
    This Pull Request fix error when if we dismiss any notification in admin panel

### Fixed Issues (if relevant)
1. Fixes magento/magento2#36581

### Manual testing scenarios (*)

1. Login Admin
2. Go to Catalog > Products
3. Choose mass action Update attributes
4. Update the Product Name and click Save
5. At this point, new message will be added to top.
6. Click X to dismiss the message > No error should occur

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rshadab25** [comment]
Already code merged so it is no more needed

**Comment by rshadab25** [comment]
Hi @ihor-sviziev 
I think we can close this PR, as I can see this issue is fixed in previous merges

**Comment by rshadab25** [comment]
https://github.com/magento/magento2/pull/36631/commits/9b8ae4e2d850aa9043073e4ae46c49b4d410d86a

**Comment by ihor-sviziev** [comment]
@rshadab25 this commit isn’t linked to any branch in this repository, so I think we should reopen pull request

**Comment by hostep** [comment]
@ihor-sviziev : I think it got fixed in scope of [ACP2E-1245: "Something went wrong" error is displayed when clearing the completed bulk tasks.](https://github.com/magento/magento2/search?q=ACP2E-1245&type=commits), I _think_ this is the merge commit: https://github.com/magento/magento2/commit/fb586ea689792a3f3c8a9f4b9e6230dc20dda9a6 (but not sure)

**Pull request closed without merging**
