### PR TITLE
[Fixed #26302] Product grid has quantity in decimals #26302

### LINKED ISSUE #26302: Product grid has quantity in decimals
### Preconditions (*)

1. Magento 2.3.3, 2.4-develop

### Steps to reproduce (*)

1. Install
2. Add product
3. Go to products grid

### Expected result (*)

Don't know about you, but we don't sell goods in fractions.

Show product quantity without decimals.

### Actual result (*)

Product quantity with decimals.

image

### PR DESCRIPTION
**Pull request by madhurajawat**
### Description (*)

Product grid has quantity in decimals #26302

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

Product grid has quantity in decimals #26302

### Manual testing scenarios (*)

1. Add product
2. Go to product Grid
3. Check qty value in Grid

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
Could you provide more descriptive title to your PR? For future reference, such as searching that is really helpful :-)

**Comment by mrtuvn** [comment]
@madhu-ranosys can you change files permissions back to correctly pls

**Comment by madhu-ranosys** [comment]
> @madhu-ranosys can you change files permissions back to correctly pls

Updated permission

**Comment by madhu-ranosys** [comment]
> Could you provide more descriptive title to your PR? For future references, such as searching that is really helpful :-)

Updated PR title.

**Comment by gwharton** [comment]
Quantity has always been float in magento.

**Comment by madhu-ranosys** [comment]
> Quantity has always been float in magento.

Yes, It is float in the database always.

**Comment by gwharton** [comment]
Commit also looks polluted with content from #27516

**Comment by madhu-ranosys** [comment]
> Commit also looks polluted with content from #27516

Should I need to update it?

**Comment by gwharton** [comment]
What happens for people who sell products in decimals. The grid should check the settings for each product to see if it is sold in decimals before converting qty to integer.

**Comment by gwharton** [comment]
And yes, remove the changes in this pr that are from your other pr.

**Comment by madhu-ranosys** [comment]
> And yes, remove the changes in this pr that are from your other pr.

Ok, will update

**Comment by madhu-ranosys** [comment]
> What happens for people who sell products in decimals. The grid should check the settings for each product to see if it is sold in decimals before converting qty to an integer.

Yes, There is a feature in admin to set qty in decimal. That will list in Integer in grid area.

**Comment by gwharton** [comment]
If the product is set to decimal qty in advanced inventory the grid should display decimal otherwise it should display integer in grid.

**Comment by gwharton** [comment]
Change should be made in cataloginventory not catalog where existing qty column is defined.

**Comment by gwharton** [comment]
Also use consistent xml style as per existing column definitions.

**Comment by madhu-ranosys** [comment]
Ok, I will update accordingly.

**Comment by lenaorobei** [comment]
Closing this PR since this is not the issue. Please see my comment https://github.com/magento/magento2/issues/26302#issuecomment-607418946

**Pull request closed without merging**
