### PR TITLE
Added regex for countryCode="IN"

### PR DESCRIPTION
**Pull request by manavluhar**
### Description (*)
Added regex for **countryCode="IN"** to accept `123 456` pattern.

- Reference: https://www.isro.gov.in/contact-us-0

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@manavluhar I don't see postal codes with space for India. https://worldpostalcode.com/india/
Are you sure that this is correct update?

**Comment by manavluhar** [comment]
Yes @Den4ik, There are two ways to write the same postal codes in India one with space and another is without space. You can See in the Reference site which i have mentioned.

**Comment by Den4ik** [comment]
@magento run Unit Tests, Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9176](https://jira.corp.magento.com/browse/ENGCOM-9176) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @reporter, @reviewer
Thanks for the collaboration & contribution!

:x: QA not Passed

**_Countr Code = IN_** should accept the zip code pattern _**123 456**_

**Manual Scenario Steps**

1. Have a Magento 2.4-develop version.
2. Login as customer in the front end and navigate to add Shipping address
3. Input India country's address along with India's zip code ex- 123 456 (There should be space between 3 digits)

**:heavy_check_mark: Expected result After Fix** 
- _123 456_ zip code pattern should be allowed legally without any warning messages

**:heavy_check_mark: Actual result After Fix** 
- _123 456_ zip code pattern is allowed legally without any warning messages



:x: **Found below issue after regressing; and it needs to be fixed; Kindly take a look**
1. Admin side: Create a tax rule with pin code range from 100000 - 999999 from _tax and zone_ section (shown in below screen shot)   
  image
2. Have a shipping address with India's zip code and state in the front end as customer.
3. Add a product to cart and navigate to checkout page.
4. Validate that the tax has been applied in the cart page

   **Observed Issue is:**
     > If we provide the zip code pattern ex- _**560093**_; the tax is getting applied.
     > If we provide the zip code pattern ex- _**560 093**_; the tax is not getting applied.
     > Below are the screenshots with both cases.
     > image
     > image
     > When we are fixing the 123 456 pattern to allow legally, the tax with zip code range should also be applied
   
   **Note:** While creating a tax with zip code range, the allowed pattern is _123456_; _123 456_ is not allowed! Below is the screenshot of it
     > image

**Comment by engcom-Bravo** [comment]
Hi @manavluhar 
Thank you for your contribution.
We go through your reference and then also check the same address on NRSC website  https://www.nrsc.gov.in/aboutus_campus_nrscblg?language_content_entity=en. Postal code is 6 digits without space. 
Postal codes with space is not used in India.

If you still feel to work on this, feel free to reopen this PR.
Thank you

**Pull request closed without merging**
