### PR TITLE
[2.3] Made logo clickable on home page

### PR DESCRIPTION
**Pull request by gwharton**
### Description (*)
Removed checks that prevent the logo being clickable on the home page. It is now clickable on all pages, including the home page (essentially refreshes the homepage)

### Fixed Issues (if relevant)
1. magento/magento2#19142: Home page store loge should be clickable to reload page

### Manual testing scenarios (*)
1. Go to home page, click logo, does page reload?
2. Go to any other page, click logo, does homepage load.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by gwharton** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @gwharton, here is your [new Magento instance](http://34.228.235.121/pr-19198/).
Admin access: [http://34.228.235.121/pr-19198//admin](http://34.228.235.121/pr-19198//admin)
Login: `admin` Password: `123123q`

**Comment by gwharton** [comment]
I can confirm changes work as planned on test instance.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3669](https://jira.corp.magento.com/browse/ENGCOM-3669) has been created to process this Pull Request

**Review by orlangur — DISMISSED** [review]
@gwharton it looks like after this change `\Magento\Theme\Block\Html\Header\Logo::isHomePage` method is not used anymore, please deprecate it mentioning this so that it can be later removed.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3669](https://jira.corp.magento.com/browse/ENGCOM-3669) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
