### PR TITLE
Issues 13769. Fix wrong info about sent email in order sender.

### PR DESCRIPTION
**Pull request by pawcioma**
### Description
Fixes wrong info about sent email in Order Sender. Order sender when send method got exception then checkAndSend should return false.

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/13769: Order Email Sender

### Manual testing scenarios
1. If we want check issue we should have wrong config sendmail in server.
2. We should place order.
3. We had wrong configuration in sendmail, so email not sent.
4. In database in sales_order we should have email_send and send_email as false.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=13878) <br/>All committers have signed the CLA.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-624](https://jira.corp.magento.com/browse/ENGCOM-624) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@pawcioma thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by TomashKhamlai** [comment]
Hello @pawcioma!
I tried to check if the issue is fixed and it looks like not. Considering that I have no rich experience with Sendmail I thought that it is a good idea to acquire some details from you. I tried this sequence of steps:

1. Uncomment any `MAILER` directive, for example, `MAILER(`local')dnl` and place any `FEATURE` directive below in config for example `FEATURE(`always_add_domain')dnl` [Why this should work](https://www.digitalocean.com/community/questions/problem-with-sendmail-config)
2. Create customer and place an order as an authorized customer
3. Check your inbox there shouldn't be sales notification
4. Check the database

:white_check_mark: Expected result:
 - before fixing
`mysql -uroot -p123123q -e"select entity_id,state,status,customer_email,email_sent,send_email from develop.sales_order;"`
```
mysql: [Warning] Using a password on the command line interface can be insecure.
+-----------+-------+---------+-------------------+------------+------------+
| entity_id | state | status  | customer_email    | email_sent | send_email |
+-----------+-------+---------+-------------------+------------+------------+
|         1 | new   | pending | yhiteca@gmail.com |          1 |          1 |
+-----------+-------+---------+-------------------+------------+------------+
```
 - after fixing
`mysql -uroot -p123123q -e"select entity_id,state,status,customer_email,email_sent,send_email from pr.sales_order;"`
```
mysql: [Warning] Using a password on the command line interface can be insecure.
+-----------+-------+---------+--------------------------+------------+------------+
| entity_id | state | status  | customer_email           | email_sent | send_email |
+-----------+-------+---------+--------------------------+------------+------------+
|         1 | new   | pending | tomash.khamlai@gmail.com |          0 |          0 |
+-----------+-------+---------+--------------------------+------------+------------+
```

:x: Actual result:
 - before fixing
`mysql -uroot -p123123q -e"select entity_id,state,status,customer_email,email_sent,send_email from develop.sales_order;"`
```
mysql: [Warning] Using a password on the command line interface can be insecure.
+-----------+-------+---------+-------------------+------------+------------+
| entity_id | state | status  | customer_email    | email_sent | send_email |
+-----------+-------+---------+-------------------+------------+------------+
|         1 | new   | pending | yhiteca@gmail.com |          1 |          1 |
+-----------+-------+---------+-------------------+------------+------------+
```
 - after fixing
`mysql -uroot -p123123q -e"select entity_id,state,status,customer_email,email_sent,send_email from pr.sales_order;"`
```
mysql: [Warning] Using a password on the command line interface can be insecure.
+-----------+-------+---------+--------------------------+------------+------------+
| entity_id | state | status  | customer_email           | email_sent | send_email |
+-----------+-------+---------+--------------------------+------------+------------+
|         1 | new   | pending | tomash.khamlai@gmail.com |          1 |          1 |
+-----------+-------+---------+--------------------------+------------+------------+
```

I see that there is no difference between before and after fixing: email_sent and send_email are equal to 1. Would you mind to share parts of your Sendmail configuration that makes the whole configuration to be broken?

**Comment by sidolov** [comment]
Hi @TomashKhamlai , one of the possible options how to broke mail service - invalid sendmail configuration in your php.ini: 
`sendmail_path=/invalid/path/to/sendmail`
after that fix, you can reproduce described behavior. 

@pawcioma , I verified your solution - it works as expected, thank you for your contribution!

**Comment by ihor-sviziev** [comment]
Hi @pawcioma, thank you for your contribution! Could you create new Pull Request to `2.3-develop` branch with the same changes?

**Comment by pawcioma** [comment]
@ihor-sviziev Ok I will prepare

**Pull request merged**
