### PR TITLE
[Backport] escape logo alt text and title

### PR DESCRIPTION
**Pull request by ghost**
### Original Pull Request
#19270: escape logo alt text and title

### Description
Backport from 2.3 to 2.2

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

Original pull request: https://github.com/magento/magento2/pull/19270

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @SikailoISM. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3590](https://jira.corp.magento.com/browse/ENGCOM-3590) has been created to process this Pull Request

**Review by orlangur — CHANGES_REQUESTED** [review]
@SikailoISM original commits author must be preserved: https://github.com/magento/magento2/pull/19270/commits

Also, there is no need to make a backport before original PR is merged. Maybe author will desire to do it himself.

**Comment by ghost** [comment]
Okay(

**Pull request closed without merging**
