### PR TITLE
[Checkout] Depend directives updated in failed payment email template

### LINKED ISSUE #32781: [Issue] [Checkout] Depend directives updated in failed payment email template
This issue is automatically created based on existing pull request: magento/magento2#32511: [Checkout] Depend directives updated in failed payment email template

---------
### Description (*)
Updated the depend directives in the failed payment email template. If the order is virtual doesn't require showing the shipping address and the shipping method.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
1. Create virtual product
2. Add trigger failed payment email logic in exception on any payment
3. Placed Order with wrong details
4. Receive failed payment email without shipping address & shipping method

### Questions or comments
Please let me know your feedback's to improve this PR.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by srsathish92**
### Description (*)
Updated the depend directives in the failed payment email template. If the order is virtual doesn't require showing the shipping address and the shipping method.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
1. Create virtual product
2. Add trigger failed payment email logic in exception on any payment
3. Placed Order with wrong details
4. Receive failed payment email without shipping address & shipping method

### Questions or comments
Please let me know your feedback's to improve this PR.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32781: [Checkout] Depend directives updated in failed payment email template

### CODE REVIEW

**Comment by srsathish92** [comment]
@magento run all tests

**Comment by srsathish92** [comment]
@magento run Functional Tests CE Functional Tests EE WebAPI Tests

**Comment by srsathish92** [comment]
@magento run Functional Tests CE,Functional Tests EE,WebAPI Tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved!

I believe we don't have any tests for emails, so marked tests as not required.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8969](https://jira.corp.magento.com/browse/ENGCOM-8969) has been created to process this Pull Request

**Comment by srsathish92** [comment]
@magento create issue

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-8969](https://jira.corp.magento.com/browse/ENGCOM-8969) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
Hi @srsathish92, thank you for your contribution. We tried to test this PR and we are able to reproduce this.But We are not clear about the expected result as we are getting the same email with or without PR changes.

Can you please let us know if we are missing something

**Comment by srsathish92** [comment]
@engcom-Delta please share the results that you have tried so that it will be helpful to point out. Thanks

**Comment by engcom-Delta** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** 

**Manual testing scenario:**

1.Create virtual product
2.Add trigger failed payment email logic in exception on any payment in Stores > Configuration > Sales > Checkout > 
   Payment Failed Emails
3.Login to Frontend
4.Place Order with wrong details
5.Receive failed payment email without shipping address & shipping method

**Before:** :heavy_multiplication_x: 


Screenshot 2024-03-14 at 10 01 32 PM

Screenshot 2024-03-14 at 10 01 40 PM

Screenshot 2024-03-14 at 11 05 39 PM

Screenshot 2024-03-14 at 11 12 39 PM

Screenshot 2024-03-14 at 11 24 52 PM

Screenshot 2024-03-14 at 11 25 02 PM

Screenshot 2024-03-14 at 11 26 58 PM

Screenshot 2024-03-14 at 11 27 08 PM

Screenshot 2024-03-14 at 11 27 54 PM

Screenshot 2024-03-14 at 11 28 02 PM

Screenshot 2024-03-14 at 11 54 02 PM


**After:** :heavy_check_mark:  


Screenshot 2024-03-14 at 10 01 32 PM

Screenshot 2024-03-14 at 10 01 40 PM

Screenshot 2024-03-14 at 11 05 39 PM

Screenshot 2024-03-14 at 11 12 39 PM

Screenshot 2024-03-14 at 11 24 52 PM

Screenshot 2024-03-14 at 11 25 02 PM

Screenshot 2024-03-14 at 11 26 58 PM

Screenshot 2024-03-14 at 11 27 08 PM

Screenshot 2024-03-14 at 11 31 59 PM

Screenshot 2024-03-14 at 11 54 25 PM



Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Static Tests, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Static Tests, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Some of the functional B2B failures in latest 2 builds are seems to be flaky and not part of this PR. 
eg. StorefrontUpdateCustomerAddressBelgiumTest

The rest of the test failures are having known issues.
1. [ACQE-6350](https://jira.corp.adobe.com/browse/ACQE-6350)- AdminCreateDraftQuoteFromQuoteGridPageWithMultipleStoresTest
2. [ACQE-6590](https://jira.corp.adobe.com/browse/ACQE-6590)- AdminCheckConfigurationForPayPalExpressCheckoutInUnitesStatesTest

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/32511/209eb3eddaa259a57a3af8b025e7b295/Functional/allure-report-b2b/index.html#categories

**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/32511/434c25b13af44d34c448537bce4eaf7f/Functional/allure-report-b2b/index.html#categories

**Comment by engcom-Charlie** [comment]
Some of the functional EE failures seems to be flaky and rest are the known issues.

Run 1:
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/32511/a59a13d47155402e0e5e0058de1532f7/Functional/allure-report-ee/index.html
image


Run 2: 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/32511/4a9f3d63236b10c04ff8c5188e7e527f/Functional/allure-report-ee/index.html
image

Known issues:
1. [ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331)-  StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest
2. [ACQE-6523](https://jira.corp.adobe.com/browse/ACQE-6523)-  AdminReorderWithCatalogPriceRuleDiscountTest

**Comment by engcom-Charlie** [comment]
Some of the WebAPI test failures are flaky  eg. testCmsSingleBlockResolverCacheAndInvalidationAsGuest. Its not related to this PR and rest of them are known failures. Hence moving the PR to Merge in Progress.

1. [#ACP2E-3082](https://jira.corp.adobe.com/browse/ACP2E-3082): testSendNegotiableQuoteCannotResend
2. [#ACP2E-3083](https://jira.corp.adobe.com/browse/ACP2E-3083): testGetCustomerDescendingSortedOrders

**Pull request merged**
