### PR TITLE
Fix incorrect translate mixin css

### PR DESCRIPTION
**Pull request by jbasoo**
### Description
`.translate()` mixin specifies translateY for some css rules. PR fixes this to support X and Y values.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. `.translate()` mixin used in [gallery.less](https://github.com/magento/magento2/blob/ab591597f860fdee5572d3894c649100e42d884c/lib/web/mage/gallery/gallery.less#L704) only supports Y value on some rules. After fix the css will be output correctly.
2. Horizontal ratio on gallery should be tested to confirm behaviour, as well as anywhere else that uses the `.translate` mixin

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Comment by Den4ik** [comment]
@jbasoo Please sign CLA

**Review by Den4ik — APPROVED** [review]
✅ Approved
Changes are correct.
Failed test are not related to changes in PR.

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9153](https://jira.corp.magento.com/browse/ENGCOM-9153) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@jbasoo thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @jbasoo,
Could you sign the adobe CLA?

**Comment by ihor-sviziev** [comment]
@sdzhepa, it's not the code cleanup. It's a bug fix. I'm pretty sure if we remove the WebKit prefix, it will break some places, for instance, gallery, as mentioned in the PR description.
Just curious, how it works correctly in the FireFox?

**Comment by ishakhsuvarov** [comment]
Hi

I am closing this PR for now as it seems like it has become stale and still needs work.

Please feel free to reopen if you wish to continue.

Thanks!

**Pull request closed without merging**
