### PR TITLE
Removed CliCacheFlushActionGroup usage for Wishlist module

### LINKED ISSUE #31962: [Issue] Removed CliCacheFlushActionGroup usage for Wishlist module
This issue is automatically created based on existing pull request: magento/magento2#31961: Removed CliCacheFlushActionGroup usage for Wishlist module

---------
### Description
Removed CliCacheFlushActionGroup usage (or changed value) for Wishlist, Swatches, Translation, UrlRewrite, Vault and Weee modules.

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Removed CliCacheFlushActionGroup usage (or changed value) for Wishlist, Swatches, Translation, UrlRewrite, Vault and Weee modules.

### Resolved issues:
1. [x] resolves magento/magento2#31962: Removed CliCacheFlushActionGroup usage for Wishlist module

### CODE REVIEW

**Comment by sergiy-v** [comment]
@magento create issue

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Semantic Version Checker

**Comment by rogyar** [comment]
Hi @sergiy-v. Thank you for your contribution. Please, consider checking the failing functional tests. Some of them (Swatches, etc) are related to your changes. 

Thanks.

**Comment by sergiy-v** [comment]
> Hi @sergiy-v. Thank you for your contribution. Please, consider checking the failing functional tests. Some of them (Swatches, etc) are related to your changes.
@rogyar thanks, I'll fix it.

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Semantic Version Checker

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Semantic Version Checker,Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run WebAPI Tests, Unit Tests, Static Tests, Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B, Magento Health Index, Integration Tests, Database Compare

**Comment by sergiy-v** [comment]
All tests are green, @rogyar please proceed with review.
Thanks.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8795](https://jira.corp.magento.com/browse/ENGCOM-8795) has been created to process this Pull Request
:eight_spoked_asterisk: @rogyar, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Bravo** [comment]
Manual QA not applicable. Moving the PR to _Extended Testing_ column

**Comment by sergiy-v** [comment]
@magento run all tests

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B, Sample Data Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Pull request merged**
