### PR TITLE
+: The possibility to use html in the translations

### LINKED ISSUE #5805: The possibility to use html in the translations
The translation module is converting special characters to HTML entities when saving the translations. By moving the converting method to a separate public function, it will be possible to create a plugin, if someone wants to use html code in the translations.

### PR DESCRIPTION
**Pull request by basselalaraaj**
fixes #5805

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=5806) <br/>All committers have signed the CLA.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/The-possibility-to-use-html-in-the-translations/idi-p/45061).

**Comment by vrann** [comment]
@basselalaraaj the repo does not exists, can you please re-create the PR?

**Comment by vrann** [comment]
@basselalaraaj closing, please re-create the PR once branch is available

**Pull request closed without merging**
