### PR TITLE
magento/magento2 #9196 - Products ordered report doesn't show simple (child) products of configurable products

### PR DESCRIPTION
**Pull request by vkranjith**
Products ordered report doesn't show simple (child) products of configurable products

### Description
Separated simple products of a configurable in product ordered report so that it shows the simple (child) product of a configurable product.

This was achieved by changing the following files.
1. Magento/Reports/view/adminhtml/layout/reports_report_product_sold_grid.xml
2. Magento/Reports/Model/ResourceModel/Product/Sold/Collection.php 

### Fixed Issues (if relevant)

1. magento/magento2#9196: Products ordered report doesn't show simple (child) products of configurable products

### Manual testing scenarios

1. Order two or more items of a configurable product with different configurations.
2. Log in to the Store Admin panel and go to Reports > Products > Ordered.
3. Give the appropriate filters and click on "Refresh" button to get the report.
4. Simple products would be listed with its configurable product name and the simple product SKU.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=9908) <br/>All committers have signed the CLA.

**Comment by vkranjith** [comment]
@magento-cicd2 

I am not able to get past the first screen that asks for "Sign in with GitHub". Everytime it gives me a blank agreement. Please see the attachment.
cla

**Comment by vherasymenko** [comment]
I check your PR and have next comment:

Steps which I execute:

1. Create configurable product with few options.
2. Create bundle(dynamic) product with few options.
3. Create bundle(fixed) product with few options.
4. Add all created product to cart with configured options, and place order.
5. Go to Admin side 'Reports > Product > Ordered' and generate report about product which were bought in previous step.

Actual Result: | Expected Result:
------------ | -------------
Configurable product displayed with child products. | It`s correct behavior
Bundle(dynamic) displayed with child products. | It`s correct behavior
Bundle(fixed) displayed without child products. | Should be displayed with child products

Could you please improve code for bundle(fixed) too ?

Thanks for your contribution.

Note: see attach screenshots:

configurable
bundle dynamic
bundle fixed

**Comment by vkranjith** [comment]
@K7Triton - Sure I will work on that.

**Comment by vkranjith** [comment]
Hi @K7Triton and @okorshenko 

I have used a new Grid\Column block file extending the Widget\Grid\Column to control rendering the correct SKU based on the data. I have also made few changes to the SQL to get the necessary SKU data for bundle products.

Below is the screenshot of a report for few different types of items ordered.
screen shot 2017-07-10 at 2 53 26 pm

Bundle Prod 1 is a fixed type bundle product. Here I am seeing an issue with the quantity. The item quantity for the Bundle Prod 1 (Fixed Type) and Bundle Prod 2 (Dynamic type) are "1" but the associated simple product's "Default Quantity" in backend was "100". So the actual quantity ordered should be "100" (coming from the associated simple product) not "1" (coming from the parent bundle product). 

Should this quantity issue also be fixed just like the SKU or is there any other business scenario to be taken care?

**Comment by okorshenko** [comment]
hi @vkranjith 
thank you for the fix. We requested PO feedback about proposed changes. 
Thank you

**Comment by tkacheva** [comment]
@vkranjith Is the solution to show SKU of bundle options in brackets? Like 
BundleFixedName ..... BundleFixedSKU( BundleFixedOption1, BundleFixedOption2, ....)

Since Magento have 2 types of bundle product and one of it is supposed to ignore its option SKU (fixed SKU) it's better to ignore BundleFixedOptionSKU and show only  BundleFixedSKU and its quantity:

BundleFixedName ..... BundleFixedSKU.......1

BundleFixed with its options SKU doesn't fit into the flat data structure.

**Comment by vkranjith** [comment]
@okorshenko and @tkacheva 

For BundleFixed product the option SKUs are within the brackets.

I am getting this info through a small customization to the existing MySQL query and a column block (specifically for fixed bundle) to render the value.

Let me know going forward what I should be doing.

**Comment by okorshenko** [comment]
HI @vkranjith 
1. Bundle fixed SKU - display the SKU of the Bundle product. Don't display option's SKUs
2. Bundle Dynamic - - display the SKU of the option. For example: BundleDynamicSKU-BundleOption1SKU-BundleOption2SKU
3. Display the amount of ordered bundle products (not the qty of the items)

Please, let me know if you have any questions

**Pull request merged**
