### PR TITLE
Fix title position on my account page

### PR DESCRIPTION
**Pull request by iGerchak**
### Description
Fix for https://github.com/magento/magento2/issues/16786

### Fixed Issues (if relevant)
1. magento/magento2#16786: Page title on the my account page moved to bottom

### Manual testing scenarios
1. see https://github.com/magento/magento2/issues/16786

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16787) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @iGerchak. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by orlangur** [comment]
New incarnation of https://github.com/magento/magento2/pull/10965, @ihor-sviziev knows the details and will try to assist with a proper fix (i.e. when layout element is first referenced and only then created as a part of `Magento_Theme` layout instructions, it's position is correct just like if `Magento_Theme` was declared first).

**Comment by orlangur** [comment]
@ihor-sviziev did you manage to move further on this?

**Comment by ihor-sviziev** [comment]
@orlangur unfortunately no :(

**Comment by ihor-sviziev** [comment]
As we discussed with @iGerchak  and @orlangur - it's not proper solution. We should implement fix that will prevent braking layout updates when sort order in config.php changes.
I'm closing this PR. Feel free to prepare another PR

**Pull request closed without merging**
