### PR TITLE
Update ListProduct.php

### LINKED ISSUE #32088: ArrayIterator incompatible method current() php 7.4
### Preconditions (*)

1. Version 2.4.1 and previous releases with support for php 7.4
2. Environment should use php >= 7.4

### Steps to reproduce (*)

1. Invoke the \Magento\Catalog\Block\Product\ListProduct::initializeProductCollection function on a product page with a product with categories
2. Following line will be executed: $this->setCategoryId(current($categories->getIterator())->getId()); 

### Expected result (*)

1. I expect the id from the first category from the product

### Actual result (*)

1. Error is returned because you call getId() on null.
2. From php >= 7.4 the current() method is no longer returning the first item from a ArrayIterator and instead returns null
3. More informations about this incompatible change can be found on phpdoc ( https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.spl )

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by mamsincl**
use `current()` method of ArrayIterator object instead of `current()` php function in _Magento\Catalog\Block\Product\ListProduct_
to prevent exception of **Call to a member function getId() on bool** using Magento 2.4.x with PHP7.4
### Description

ArrayIterator PHP object behaves differently under PHP7.4 and PHP7.3.
With the earlier version, native PHP array functions (including _current()_) can handle object as array, but not with PHP7.4
Using object's implemented method instead of native function.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32088

### Manual testing scenarios (*)

1. open previously broken PDP

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mamsincl** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
Can you check test results and coverage your change with auto tests

**Comment by mamsincl** [comment]
@magento run Functional Tests EE, Unit Tests, WebAPI Tests

**Comment by mamsincl** [comment]
I checked **All automated tests passed successfully (all builds are green)** checkbox, as the small modification of the PR does not introduce any new public method which requires any additional automated/functional/unit tests

The failed tests - might be caused by the general condition of branch 2.4-develop - are: 
- Functional Tests EE
- Unit Tests
- WebAPI Tests

**Comment by mamsincl** [comment]
@magento run all tests

**Comment by mamsincl** [comment]
Failed test re-triggered
@magento run Functional Tests EE, Functional Tests B2B

note: 
- previously succeeded Functional Tests B2B failed as **Admin user create Partial Invoice for order with Virtual product on Custom stock from Main Website** - _not related_
- Functional Tests EE failed as **Apply Catalog Price Rule in Magento EE** - _not related_

**Comment by mamsincl** [comment]
I am marking PR as all automated test passed successfully: Functional Tests EE failed a different reason this time, re-triggered again (and last time)

@magento run Functional Tests EE

note:
- Functional Tests EE failed as **MC-32285: Product Source Grid Verification for multiple product sources.**

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8906](https://jira.corp.magento.com/browse/ENGCOM-8906) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@mamsincl thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by brucemead** [comment]
Please add Ayko Partner label.

**Comment by ihor-sviziev** [comment]
@sidolov @gabrieldagama, could you check with author why partner label not assigned automatically?

**Comment by brucemead** [comment]
@ihor-sviziev I've just added @mamsincl to our team so that will be why

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8906](https://jira.corp.magento.com/browse/ENGCOM-8906) has been created to process this Pull Request

**Comment by engcom-Oscar** [comment]
@engcom-Foxtrot can you please check this PR, it require dev-experience.

**Comment by engcom-Foxtrot** [comment]
QA passed

**Pull request merged**
