### PR TITLE
- added new localized exception when block can't created

### PR DESCRIPTION
**Pull request by pusachev**
### Description (*)

Exception doesn't contain valid information

### Manual testing scenarios (*)

- 1. Create block class B
- 2. Rewrite block class A on block class B by di.xml preferences
- 3. Delete block class B 

**Expected error message:** 
Can't create block type B

**Actual result:**
Invalid block type: A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19008) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @pusachev. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by pusachev** [comment]
#mageconf

**Review by madbounce — APPROVED** [review]

**Comment by orlangur** [comment]
Current system behavior is perfectly valid. Facing with such error just check what is a real class behind taking into consideration DI.

**Pull request closed without merging**
