### PR TITLE
Covered admin cms block creatation with MFTF test

### PR DESCRIPTION
**Pull request by ajithkumar-maragathavel**
### Description (*)

Covered admin cms block creation with MFTF test.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lbajsarowicz — CHANGES_REQUESTED** [review]
1. Each MFTF Test should reside in separate file that reflects Test name
2. You should use existing Action Groups, if there's any missing - you should create one and Test should be made only with ActionGroups

**Comment by ajithkumar-maragathavel** [comment]
@lbajsarowicz As suggested, I have made changes to the MFTF test and commit the changes. Please review it. Also thanks for the suggestion to improve the code.

**Review by lbajsarowicz — APPROVED** [review]
Much better now. Thanks for your contribution.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-6687](https://jira.corp.magento.com/browse/ENGCOM-6687) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by ajithkumar-maragathavel** [comment]
@lbajsarowicz  Unfortunately, I deleted my Magento 2 fork from my account. 
So It is showing as **unknown repository** in the PR.

Please let me know if this PR can be merged or not. 
I appreciate your help.

Thanks.

**Pull request merged**
