### PR TITLE
2.3 Development: Clarify XSD for formElements allowed settings

### LINKED ISSUE #14140: UI component definition.map.xml overlooks XSD-valid nodes
### Preconditions

The issue was discovered in Magento 2.2.2 EE, but looks like it still exists in the 2.2-develop branch of this repository. 

### Steps to reproduce

1. Create and configure a new UI form component with the following XML definition:

```
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
  <!-- Include standard <argument>, <settings>, <dataSource> to create minimal form. -->
  <fieldset name="billing">
    <field name="shippingMethod" formElement="select">
      <formElements>
        <select>
          <settings>
            <options class="Magento\Shipping\Model\Config\Source\Allmethods" />
            <label>Shipping Method</label>
          </settings>
        </select>
      </formElements>
    </field>
  </fieldset>
</form>
```

### Expected result

1. The XML should validate with the provided XSD files. (It does.)
2. When viewing the form in the browser, a dropdown select box with the label "Shipping Method" should be shown and populated with the values defined in the `Allmethods` class.

**OR**

1. The XML should not validate with the provided XSD files, because the parser will not read the configuration correctly.

### Actual result

1. The XML validates.
2. The dropdown select box is populated correctly, but the label is not shown.

However, the following code does display the label in the generated markup:

```
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
  <!-- Include standard <argument>, <settings>, <dataSource> to create minimal form. -->
  <fieldset name="billing">
    <field name="shippingMethod" formElement="select">
      <settings>
        <label>Shipping Method</label>
      </settings>
      <formElements>
        <select>
          <settings>
            <options class="Magento\Shipping\Model\Config\Source\Allmethods" />
          </settings>
        </select>
      </formElements>
    </field>
  </fieldset>
</form>
```

The issue seems to be how `definition.map.xml` is written, specifically around [line 285](https://github.com/magento/magento2/blob/cb0954add41284de1b003fa378551b3e973b306c/app/code/Magento/Ui/view/base/ui_component/etc/definition.map.xml#L285) and [787](https://github.com/magento/magento2/blob/cb0954add41284de1b003fa378551b3e973b306c/app/code/Magento/Ui/view/base/ui_component/etc/definition.map.xml#L787). Settings such as `<label>`, which are common to many UI components, are read only from a top-level `<settings>` node, while component-specific settings such as `<options>` are read from the appropriate `<settings>` descendent of `<formElements>`. 

This constraint/decision is perfectly understandable, _but_ it is not represented in the corresponding XSD (see [line 271](https://github.com/magento/magento2/blob/cb0954add41284de1b003fa378551b3e973b306c/app/code/Magento/Ui/etc/ui_configuration.xsd#L271) of ui_configuration.xsd, and the corresponding `formElements` group). Any child from the `abstractSettings` group (found [here](https://github.com/magento/magento2/blob/cb0954add41284de1b003fa378551b3e973b306c/app/code/Magento/Ui/view/base/ui_component/etc/definition/ui_settings.xsd#L866)) is allowed (valid) within the `<settings>` nodes that are descendents of `<formElements>`, but none of them are read by the configuration reader because they aren't specified in definition.map.xml.

### Potential Solutions

Depending on the architectural desires of the Magento team, this miscommunication could be fixed in a few ways:

1. Adding the appropriate xpath mappings for `abstractSettings` within every component-specific settings mapping.
2. Clarifying/constraining the XSD files to ensure that `abstractSettings` are only placed in top-level `<settings>` nodes, and component-specific settings remain isolated.

In short, the new UI component semantics function properly, but permit certain undefined behaviors that should be clarified in both the code itself and in documentation.

### PR DESCRIPTION
**Pull request by neillrobson**
### Description

In an attempt to resolve #14140, new complex types have been defined for every UI component specified in [`ui_settings.xsd` line 49](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Ui/view/base/ui_component/etc/definition/ui_settings.xsd#L49) (valid attribute codes for "formElement"). These complex types only include the `<settings>` child node, along with any grandchildren that pertain specifically to that form element (no `abstractSettings`). Finally, `ui_configuration.xsd` has been updated with a new group holding these complex types, and the corresponding validation for the `<formElements>` tag references this new group rather than the existing, more general group.

### Fixed Issues (if relevant)

1. magento/magento2#14140: UI component definition.map.xml overlooks XSD-valid nodes

**Note**: This pull request contains the same code changes and functionality from [PR 14170](https://github.com/magento/magento2/pull/14170), but this PR affects the `2.3-develop` branch rather than the old `2.2-develop` branch.

### CODE REVIEW

**Comment by VladimirZaets** [comment]
Hi, @RNanoware, thank you for collaboration. I will close PR to 2.2-develop.

**Comment by VladimirZaets** [comment]
Hi @RNanoware. Looks like in Magento 2.3 we add `imageUploader` as new `formElement` type.
Please add `imageUploader` to XSD, thanks.

**Comment by VladimirZaets** [comment]
@RNanoware thanks!

**Comment by magento-engcom-team** [comment]
Hi @RNanoware. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.3.0 release.

**Pull request merged**
