### PR TITLE
[Backport] fixed Notification page Select Visible items issue 

### PR DESCRIPTION
**Pull request by shikhamis11**
### Original Pull Request 
 https://github.com/magento/magento2/pull/19302
Fixed issue - magento#19285
On Notification page Select All and Select Visible both works same

### Description (*)
Fixed issue [#19285](https://github.com/magento/magento2/issues/19285) On Notification page Select All and Select Visible both works same

### Fixed Issues (if relevant)
[#19285](https://github.com/magento/magento2/issues/19285) On Notification page Select All and Select Visible both works same

### Manual testing scenarios (*)
1. Login to Magento Admin.
2. Select Notifications (Bell Icon from right top of the screen).
3. Click on "See All".
4. Default paging is set to 20 rows per page.
5. Make sure you have more than 20 notifications so that you can have paging available and some notification are on next pages.
6. Now from Mass Action dropdown select "Select All" action. This will select only visible notifications (currently 20, as 20 rows per page is setup) instead of all available records.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by VladimirZaets** [comment]
Hi @shikhamis11, thanks for collaboration. Please update `phpdocs` declaration how it was updated in the original PR.

**Comment by shikhamis11** [comment]
@VladimirZaets I have updated changes please check

**Review by sidolov — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3777](https://jira.corp.magento.com/browse/ENGCOM-3777) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.

**Pull request merged**
