### PR TITLE
Fix #20309 - URL Rewrites redirect loop

### LINKED ISSUE #20309: URL Rewrites redirect loop
### Preconditions (*)

1. PHP 7.1
2.  Magento version 2.2.6

### Steps to reproduce (*)

1. Go To Admin Url rewrites.
2. Create New Url rewrite with request-path: **/** and target_path **/** with 301 or 302 redirect./

### Expected result (*)

1. Validation errors, that there will be infinite redirecion loop

### Actual result (*)
1. Browser error:
This page isn’t working. redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This is fix for #20309 - as @ihor-sviziev mentioned in https://github.com/magento/magento2/pull/25848#pullrequestreview-324731512 - adding validation for such redirect wouldn't fix the issue for i.e. existing stores. So I added check in url rewrite router, which doesn't allow to redirect if request path is equal to target path.

### Fixed Issues (if relevant)

1. magento/magento2#20309: URL Rewrites redirect loop

### Manual testing scenarios (*)

Please check fixed issue for steps to test

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@Bartlomiejsz,
Your changes looks good, but there is some nitration test failure. Could you fix it?

**Comment by Bartlomiejsz** [comment]
@ihor-sviziev done

**Review by ihor-sviziev — DISMISSED** [review]
@Bartlomiejsz,
URL rewrites it quite complex thing, and there is a lot of potential issues. Thank you so much for covering your changes with unit tests, but I think it's better to cover this change with integration tests. Will you be able to do that?

Recently there were fix for URL rewrites, it was covered by integration tests, I think it's good example. Use cases were defined here:
https://github.com/magento/magento2/issues/18717#issuecomment-553382269

I've did integration test coverage for such cases:
https://github.com/magento/magento2/pull/25603/commits/b1a2a29671de32d90dbc10a3b0ced6a3d71b2b72


Note: seems like there not just one case, there should be also checked cases with get params

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
See above

**Comment by Bartlomiejsz** [comment]
Hi @ihor-sviziev,
I don't really have experience with writing integration tests, so if that would be possible for you that would be great.
Otherwise it will take some time for me to prepare those but can try - just please let me know

**Comment by ihor-sviziev** [comment]
@Bartlomiejsz not sure if I'll have free time to help you. But actually integration tests are quire similar to and even maybe simpler than unit tests, but.

Please try following instruction:
https://devdocs.magento.com/guides/v2.3/test/integration/integration_test_execution.html

**Review by ihor-sviziev — DISMISSED** [review]

**Comment by ihor-sviziev** [comment]
@Bartlomiejsz Good job! Approved!

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6995](https://jira.corp.magento.com/browse/ENGCOM-6995) has been created to process this Pull Request

**Review by engcom-Delta — CHANGES_REQUESTED** [review]
@Bartlomiejsz , @ihor-sviziev this PR implements only one point from [#25848 (review)](https://github.com/magento/magento2/pull/25848#pullrequestreview-324731512):

- `adjust logic to do NOT perform redirect in case of target path equal to request path`

But there is no implemented `patch that will find & delete all such incorrect URL` and no validation for same `request-path` and `target_path` in admin.
Now behavior with PR is next:
- Url Rewrite with request-path: foo and target_path foo with 301 or 302 redirect is successfully created 
- Getting `404 Page not found` error when such url was requested
image

Is this expected behavior of PR?

**Comment by Bartlomiejsz** [comment]
Hi @engcom-Delta, as @ihor-sviziev mentioned there, those two options, and I'm pretty sure the one implemented in current PR makes second not needed. Because even with those rewrites being still in database, no issue should be spotted on FE.
And for your example - I'm pretty sure this is correct. Please verify clean 2.4-develop for same case, you  should receive `ERR_TOO_MANY_REDIRECTS` error. And with the fix, it redirects only if target_path is different then url on which you are currently.
So there is 404 if there is no such page, and if you will add rewrite with existing url (like `contact` -> `contact`) this should just show you the `contact` page

**Comment by ihor-sviziev** [comment]
@engcom-Delta i totally agree with @Bartlomiejsz . What you’ve shown - expected result. What you said - it could be improved, but main issue is fixed by this PR

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6995](https://jira.corp.magento.com/browse/ENGCOM-6995) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
