### PR TITLE
Refactor Category Link: Replace deprecated interface, clean the code

### LINKED ISSUE #29679: [Issue] Refactor Category Link: Replace deprecated interface, clean the code
This issue is automatically created based on existing pull request: magento/magento2#29564: Refactor Category Link: Replace deprecated interface, clean the code

---------
### Description (*)
That is a little change that needs to be approved by Magento Community Engineering team as it changes the Interface used.
I decided to isolate that, as it's going to take months to get the approval :-)

This is a part of https://github.com/magento/magento2/pull/29376 process.

### Fixed Issues (if relevant)
1. Continuation of https://github.com/magento/magento2/pull/29376

### Manual testing scenarios (*)
N/A

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
That is a little change that needs to be approved by Magento Community Engineering team as it changes the Interface used.
I decided to isolate that, as it's going to take months to get the approval :-)

This is a part of https://github.com/magento/magento2/pull/29376 process.

### Fixed Issues (if relevant)
1. Continuation of https://github.com/magento/magento2/pull/29376

### Manual testing scenarios (*)
N/A

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29679: Refactor Category Link: Replace deprecated interface, clean the code

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

Go home, Magento. You are drunk.

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8016](https://jira.corp.magento.com/browse/ENGCOM-8016) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

Was checked Category Link functionality and everything works as previous (expected).

**Comment by engcom-Charlie** [comment]
@magento create issue

**Pull request merged**
