### PR TITLE
Cart item Price should be the converted (with quote currency) value (…

### LINKED ISSUE #29994: GraphQL Cart Item Price
When switching to other currency, cart price is not updated (the row total is working fine)

### Preconditions (*)
Magento 2.4.0
Store with 2 currency options

### Steps to reproduce (*)

Send the "Content-Currency" header with a value that's different from the default currency.

### Expected result (*)

1. The value to be right
Screenshot at Sep 11 14-20-45

### Actual result (*)

1. The value is still calculated by default currency

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by codynguyen1**
Cart item Price should be the converted (with quote currency) value (like row_total, row_total_including_tax, and total_item_discount that's already the right value).

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29994

### Manual testing scenarios (*)

Send the "Content-Currency" header with a value that's different from the default currency.

### Contribution checklist (*)
 - [v] Pull request has a meaningful description of its purpose
 - [v] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by codynguyen1** [comment]
@magento run all tests

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @codynguyen1. Very good point. Thank you for your collaboration.
Could I ask you to cover your fix with an API-functional test, please? According to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes/fixes should be covered by autotests. 

Thank you!

**Comment by codynguyen1** [comment]
Hi @rogyar , I'm sorry I missed the test checkbox while submitting the PR, the quote item information API was already covered by api-funtion test before.

**Comment by codynguyen1** [comment]
@magento run Functional Tests B2B 
@magento run Static Tests

**Comment by codynguyen1** [comment]
@magento run Static Tests

**Comment by mauragcyrus** [comment]
hi @codynguyen1 can this also "Please consider a scenario when store view has more currencies configured and "Content-Currency" header value is one of the allowed currencies but neither base_currency or default_display_currency"?

**Comment by codynguyen1** [comment]
@magento run all tests
@mauragcyrus Thank you for your feedback, I have added a function for that scenario.

**Comment by codynguyen1** [comment]
@mauragcyrus The erors from test are from another source, could you please help me with that?
Thanks!

**Comment by codynguyen1** [comment]
@magento run all tests

**Comment by codynguyen1** [comment]
@magento run Functional Tests CE
@magento run WebAPI Tests

**Comment by engcom-Hotel** [comment]
Will have a look at the failed tests.

**Comment by engcom-Hotel** [comment]
Hello @codynguyen1 ,
Please check your changes in the test, it gives the error 'Wrong store code specified for cart'.
How to test it locally you may find here: https://devdocs.magento.com/guides/v2.4/get-started/web-api-functional-testing.html

**Comment by codynguyen1** [comment]
@magento run all tests

**Comment by codynguyen1** [comment]
@mauragcyrus @engcom-Hotel I have updated fixture and function test to pass it, please help me review this, thanks!

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8335](https://jira.corp.magento.com/browse/ENGCOM-8335) has been created to process this Pull Request

**Comment by mauragcyrus** [comment]
@codynguyen1 and @rogyar I think this needed to be tested with the non-default currency (I think the code is missing the changes that will make that work). it looks like this case was covered by another PR. Apologies for the back and forth here. I believe we can close this now.

**Comment by rogyar** [comment]
Hi @mauragcyrus. Thanks for the hint. Could I ask you for a link with the mentioned PR that covers this issue, please? I'm asking because I still can reproduce the issue with the current mainline.

Thanks.

**Comment by mauragcyrus** [comment]
Hi @rogyar, @cspruiell is working on this in an internal ticket. There's not a PR yet bc there's another fix that went into 2.4.1 that is conflicting with the current fix. We are looking into the original 2.4.1 fix to see if there is an alternate solution. We'll update soon.

**Comment by engcom-Alfa** [comment]
Hi @codynguyen1 and @rogyar , Thanks for your contribution and collaboration
This PR has no details about the issue in detail and linked [issue description](https://github.com/magento/magento2/issues/29994#issue-698948908) in also needs more information.
Kindly provide me the below details in order to process it please.

**Q1.** Description says, **_stores with 2 currency options_**: We can basically have one default display currency as shown in below screenshot. Can you please explain more about where and what configurations you are doing to have such currency setup?
image

**Q2.** Description says, **_Send the "Content-Currency" header with a value that's different from the default currency_**: Means, I am assuming that, we have GraphQl request in which header parameters are used "Content-Currency=VND" Is my understanding correct? Also, **_header with a value that's different from the default currency_** what is exactly you meant here? can you please elaborate?

**Q3.** You have used an GraphQL mutation in the attached screenshot of issue description, Can you please provide me that request body content?

**Request 1:** Since this issue picked later due to various reasons, can you please re-test it once in latest '2.4-develop' instance and let us know if the issue is still existing with all the above queries and more information possibly?
**Request 2:** If so, please resolve the merge conflicts, so that, it will help us in testing the PR changes.

Thanks in advance!

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
As I discussed with @codynguyen1 today in the slack, we will get updates from him sometime later; Hence moving it to Changes requested!

**Pull request closed without merging**
