### PR TITLE
Fixed issue #22767: Not clear logic for loading CMS Pages with setStoreId function

### LINKED ISSUE #22767: Not clear logic for loading CMS Pages with setStoreId function
### Preconditions (*)

1. 2.1.x
2. 2.2.x
3. 2.3.x

### Steps to reproduce (*)

1. Create some class that will load CMS Page:
```
 /**
     * Constructor.
     */
    public function __construct(
        \Magento\Cms\Model\PageFactory $pageFactory
    ) {
        $this->pageFactory = $pageFactory;
    }

/** @var \Magento\Cms\Model\Page $page */
$page = $this->pageFactory->create();
$page->setStoreId([2]);
$page->load($identifier, Page::IDENTIFIER);
```
2. According to description for magic function **setStoreId** must be array in Magento\Cms\Model\Page:
` * @method Page setStoreId(array $storeId)`

[Link](https://github.com/magento/magento2/blob/bd82ed4ecd5c7d66c819711a2a4425d46c232583/app/code/Magento/Cms/Model/Page.php#L19)

3. But in Magento\Cms\Model\ResourceModel\Page in method **_getLoadSelect** you have this part of code:
```
 if ($object->getStoreId()) {
            $storeIds = [
                Store::DEFAULT_STORE_ID,
                (int)$object->getStoreId(),
            ];
......
}
```
[Link](https://github.com/magento/magento2/blob/bd82ed4ecd5c7d66c819711a2a4425d46c232583/app/code/Magento/Cms/Model/ResourceModel/Page.php#L200)

4. If you will provide array it will be just 1 and not merged with provided array. 

### Expected result (*)

1. If description correct and **store_id** must be array, then in Resource Model must be changed logic for merging array
2. If it must be just **int**, then it must be changed description for magic function in Magento\Cms\Model\Page

### Actual result (*)

1. See steps

### PR DESCRIPTION
**Pull request by mahesh-rajawat**
Fixed: Not clear logic for loading CMS Pages with setStoreId function.
### Description (*)

In this PR, i have fixed #22767 issue.
### Fixed Issues (if relevant)

1. magento/magento2#22767
2. ...

### Manual testing scenarios (*)

1. Tested it by programmatically. 
2. 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5147](https://jira.corp.magento.com/browse/ENGCOM-5147) has been created to process this Pull Request

**Comment by soleksii** [comment]
Hi @maheshWebkul721 !
Could you please make changes and for Block model (Magento\Cms\Model\Block) too?!
screen
**Thanks!**

**Comment by mahesh-rajawat** [comment]
@stoleksiy , Fixed it for `Magento\Cms\Model\Block` .

**Comment by soleksii** [comment]
> @stoleksiy , Fixed it for `Magento\Cms\Model\Block` .

Thanks!

**Review by sidolov — APPROVED** [review]

**Review by orlangur — CHANGES_REQUESTED** [review]
Please squash changes into a single commit so that we have perfectly clean history 😉

**Comment by mahesh-rajawat** [comment]
> Please squash changes into a single commit so that we have perfectly clean history

@orlangur, All commits squashed

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
