### PR TITLE
[BUGFIX] Solve invalid GraphQl schema by updating sequence

### PR DESCRIPTION
**Pull request by lewisvoncken**
### Description (*)

Added sequence for the QuoteGraphQl module to solve errors like: `Type "CartItemInput" not found in document.`

### Manual testing scenarios (*)

1. Install Google Chrome Plugin - https://chrome.google.com/webstore/detail/chromeiql/fkkiamalmpiidkljmicmjfbieiclmeij
2. Try to make request to /graphql
3. Error is shown `Type "CartItemInput" not found in document.`
4. After applying changes the error will be solved.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @lewisvoncken, thanks for collaboration. I cannot reproduce this issue, can you please provide additional details

**Comment by lewisvoncken** [comment]
@VladimirZaets the type 'CartItemInput' is used within the schema of the ConfigurableProductGraphQl module which is originally from the schema of the QuoteGraphQl module. Also some other types from this schema are used within this module.

When a type of a different module is used in the schema it should be added to the sequence. In my case the QuoteGraphQl module was loaded after the ConfigurableProductGraphQl module. After applying the change of this PR the following diff in the app/etc/config.php was applied

```
         'Magento_GoogleAdwords' => 1,
         'Magento_GoogleAnalytics' => 1,
         'Magento_Ui' => 1,
-        'Magento_ConfigurableProductGraphQl' => 1,
+        'Magento_QuoteGraphQl' => 1,
         'Magento_PageCache' => 1,
         'Magento_GroupedProduct' => 1,
         'Magento_GroupedImportExport' => 1,
@@ -138,7 +138,7 @@ return [
         'Magento_ProductVideo' => 1,
         'Magento_CheckoutAgreements' => 1,
         'Magento_QuoteAnalytics' => 1,
-        'Magento_QuoteGraphQl' => 1,
+        'Magento_ConfigurableProductGraphQl' => 1,
         'Magento_ReleaseNotification' => 1,
         'Magento_Reports' => 1,
         'Magento_RequireJs' => 1,
```

Let me know if you have any questions.

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-5403](https://jira.corp.magento.com/browse/ENGCOM-5403) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by TomashKhamlai** [comment]
Please check again this PR
```json
{
	"0": "Type \"ProductInterface\" not found in document.",
	"1": "<pre>#1 GraphQL\\Utils\\ASTDefinitionBuilder->internalBuildType('ProductInterface', &GraphQL\\Language\\AST\\NamedTypeNode#0000000077ff38ff0000000035f8ddfe#) called at [vendor\/webonyx\/graphql-php\/src\/Utils\/ASTDefinitionBuilder.php:165]\n#2 GraphQL\\Utils\\ASTDefinitionBuilder->buildType(&GraphQL\\Language\\AST\\NamedTypeNode#0000000077ff38ff0000000035f8ddfe#) called at [vendor\/webonyx\/graphql-php\/src\/Utils\/ASTDefinitionBuilder.php:175]\n#3 GraphQL\\Utils\\ASTDefinitionBuilder->internalBuildWrappedType(&GraphQL\\Language\\AST\\NonNullTypeNode#0000000077ff38f60000000035f8ddfe#) called at [vendor\/webonyx\/graphql-php\/src\/Utils\/ASTDefinitionBuilder.php:198]\n#4 GraphQL\\Utils\\ASTDefinitionBuilder->buildField(&GraphQL\\Language\\AST\\FieldDefinitionNode#0000000077ff38ec0000000035f8ddfe#) called at [vendor\/webonyx\/graphql-php\/src\/Utils\/ASTDefinitionBuilder.php:277]\n#5 GraphQL\\Utils\\ASTDefinitionBuilder->GraphQL\\Utils\\{closure}(&GraphQL\\Language\\AST\\FieldDefinitionNode#0000000077ff38ec0000000035f8ddfe#) called at [vendor\/webonyx\/graphql-php\/src\/Utils\/Utils.php:209]\n#6 GraphQL\\Utils\\Utils::keyValMap(&GraphQL\\Language\\AST\\NodeList#0000000077ff3b020000000035f8ddfe#, &Closure#0000000077ff0bb10000000035f8ddfe#, &Closure#0000000077ff0bb60000000035f8ddfe#) called at [vendor\/webonyx\/graphql-php\/src\/Utils\/ASTDefinitionBuilder.php:278]\n#7 GraphQL\\Utils\\ASTDefinitionBuilder->makeFieldDefMap(&GraphQL\\Language\\AST\\InterfaceTypeDefinitionNode#0000000077ff38e80000000035f8ddfe#) called at [vendor\/webonyx\/graphql-php\/src\/Utils\/ASTDefinitionBuilder.php:329]\n#8 GraphQL\\Utils\\ASTDefinitionBuilder->GraphQL\\Utils\\{closure}() called at [vendor\/webonyx\/graphql-php\/src\/Type\/Definition\/FieldDefinition.php:80]\n#9 GraphQL\\Type\\Definition\\FieldDefinition::defineFieldMap(&GraphQL\\Type\\Definition\\InterfaceType#0000000077ff2c540000000035f8ddfe#, &Closure#0000000077ff0b5a0000000035f8ddfe#) called at [vendor\/webonyx\/graphql-php\/src\/Type\/Definition\/InterfaceType.php:70]\n#10 GraphQL\\Type\\Definition\\InterfaceType->getFields() called at [vendor\/webonyx\/graphql-php\/src\/Utils\/TypeInfo.php:124]\n#11 GraphQL\\Utils\\TypeInfo::extractTypes(&GraphQL\\Type\\Definition\\InterfaceType#0000000077ff2c540000000035f8ddfe#, array('Query' => &GraphQL\\Type\\Definition\\ObjectType#0000000077ff2d650000000035f8ddfe#, 'String' => &GraphQL\\Type\\Definition\\StringType#0000000077ff2f040000000035f8ddfe#, 'Cart' => &GraphQL\\Type\\Definition\\ObjectType#0000000077ff2c0a0000000035f8ddfe#, 'CartItemInterfac...' => &GraphQL\\Type\\Definition\\InterfaceType#0000000077ff2c540000000035f8ddfe#)) called at [vendor\/webonyx\/graphql-php\/src\/Utils\/TypeInfo.php:94]\n#12 GraphQL\\Utils\\TypeInfo::extractTypes(&GraphQL\\Type\\Definition\\ListOfType#0000000077ff0b610000000035f8ddfe#, array('Query' => &GraphQL\\Type\\Definition\\ObjectType#0000000077ff2d650000000035f8ddfe#, 'String' => &GraphQL\\Type\\Definition\\StringType#0000000077ff2f040000000035f8ddfe#, 'Cart' => &GraphQL\\Type\\Definition\\ObjectType#0000000077ff2c0a0000000035f8ddfe#)) called at [vendor\/webonyx\/graphql-php\/src\/Utils\/TypeInfo.php:138]\n#13 GraphQL\\Utils\\TypeInfo::extractTypes(&GraphQL\\Type\\Definition\\ListOfType#0000000077ff0b610000000035f8ddfe#, array('Query' => &GraphQL\\Type\\Definition\\ObjectType#0000000077ff2d650000000035f8ddfe#, 'String' => &GraphQL\\Type\\Definition\\StringType#0000000077ff2f040000000035f8ddfe#, 'Cart' => &GraphQL\\Type\\Definition\\ObjectType#0000000077ff2c0a0000000035f8ddfe#)) called at [vendor\/webonyx\/graphql-php\/src\/Utils\/TypeInfo.php:138]\n#14 GraphQL\\Utils\\TypeInfo::extractTypes(&GraphQL\\Type\\Definition\\ObjectType#0000000077ff2c0a0000000035f8ddfe#, array('Query' => &GraphQL\\Type\\Definition\\ObjectType#0000000077ff2d650000000035f8ddfe#, 'String' => &GraphQL\\Type\\Definition\\StringType#0000000077ff2f040000000035f8ddfe#)) called at [vendor\/webonyx\/graphql-php\/src\/Type\/Schema.php:228]\n#15 GraphQL\\Type\\Schema->collectAllTypes() called at [vendor\/webonyx\/graphql-php\/src\/Type\/Schema.php:196]\n#16 GraphQL\\Type\\Schema->getTypeMap() called at [lib\/internal\/Magento\/Framework\/GraphQlSchemaStitching\/GraphQlReader.php:109]\n#17 Magento\\Framework\\GraphQlSchemaStitching\\GraphQlReader->readPartialTypes('type Query {\\n   ...') called at [lib\/internal\/Magento\/Framework\/GraphQlSchemaStitching\/GraphQlReader.php:86]\n#18 Magento\\Framework\\GraphQlSchemaStitching\\GraphQlReader->read('global') called at [lib\/internal\/Magento\/Framework\/GraphQlSchemaStitching\/Common\/Reader.php:41]\n#19 Magento\\Framework\\GraphQlSchemaStitching\\Common\\Reader->read() called at [lib\/internal\/Magento\/Framework\/Config\/Data.php:104]\n#20 Magento\\Framework\\Config\\Data->initData() called at [lib\/internal\/Magento\/Framework\/Config\/Data.php:92]\n#21 Magento\\Framework\\Config\\Data->__construct(&Magento\\Framework\\GraphQlSchemaStitching\\Common\\Reader#0000000077ff2fb40000000035f8ddfe#, &Magento\\Framework\\App\\Cache\\Type\\Config#0000000077ff2ec60000000035f8ddfe#, 'Magento_Framewor...', NULL) called at [lib\/internal\/Magento\/Framework\/ObjectManager\/Factory\/AbstractFactory.php:116]\n#22 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Magento\\Framewor...', array(&Magento\\Framework\\GraphQlSchemaStitching\\Common\\Reader#0000000077ff2fb40000000035f8ddfe#, &Magento\\Framework\\App\\Cache\\Type\\Config#0000000077ff2ec60000000035f8ddfe#, 'Magento_Framewor...', NULL)) called at [lib\/internal\/Magento\/Framework\/ObjectManager\/Factory\/Compiled.php:108]\n#23 Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\Framewor...') called at [lib\/internal\/Magento\/Framework\/ObjectManager\/Factory\/Compiled.php:150]\n#24 Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Magento\\Framewor...') called at [lib\/internal\/Magento\/Framework\/ObjectManager\/Factory\/Compiled.php:79]\n#25 Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\Framewor...') called at [lib\/internal\/Magento\/Framework\/ObjectManager\/Factory\/Compiled.php:150]\n#26 Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Magento\\Framewor...') called at [lib\/internal\/Magento\/Framework\/ObjectManager\/Factory\/Compiled.php:79]\n#27 Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\Framewor...') called at [lib\/internal\/Magento\/Framework\/ObjectManager\/Factory\/Compiled.php:150]\n#28 Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('Magento\\Framewor...') called at [lib\/internal\/Magento\/Framework\/ObjectManager\/Factory\/Compiled.php:79]\n#29 Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('Magento\\GraphQl\\...') called at [lib\/internal\/Magento\/Framework\/ObjectManager\/ObjectManager.php:70]\n#30 Magento\\Framework\\ObjectManager\\ObjectManager->get('Magento\\GraphQl\\...') called at [lib\/internal\/Magento\/Framework\/App\/Http.php:136]\n#31 Magento\\Framework\\App\\Http->launch() called at [lib\/internal\/Magento\/Framework\/App\/Bootstrap.php:260]\n#32 Magento\\Framework\\App\\Bootstrap->run(&Magento\\Framework\\App\\Http\\Interceptor#0000000077ff2e580000000035f8ddfe#) called at [index.php:39]\n<\/pre>",
	"url": "\/graphql",
	"script_name": "\/index.php"
}
```

image

**Comment by lewisvoncken** [comment]
@TomashKhamlai 
Are you having the same problem or is the pr giving you issues?

**Comment by TomashKhamlai** [comment]
I believe that the problem is on this PR. There were several times in the past when I've forgotten to perform `setup:di:compile`. But now I have a script for an automatic code fetching from PRs. Mr. Lewis @lewisvoncken, I would kindly ask you to request a review from @lenaorobei, we discussed this problem on one of the PRs in [magento/graphql-ce](https://github.com/magento/graphql-ce) that is why I am sure she can help with this. If she is on vacation then I will ask @naydav to do this, he is already notified. We need to wait for them for a few hours as they both work in another timezone.

**Review by sivaschenko — CHANGES_REQUESTED** [review]
@naydav @lenaorobei can you please review this PR and consider the comments above.

**Comment by lenaorobei** [comment]
We've had the same issue with bundled products https://github.com/magento/graphql-ce/pull/396 and sequence really matters. Consider also adding `composer.json` dependencies.
```
"magento/module-quote": "*",
"magento/module-quote-graph-ql": "*"
```
Thank you.

**Comment by sivaschenko** [comment]
@lewisvoncken can you please update `composer.json` and check failed tests

**Comment by sidolov** [comment]
@lewisvoncken , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
