### PR TITLE
Chore: Grouped Product - Replace Block Escaping with Escaper

### LINKED ISSUE #37171: [Issue] Chore: Grouped Product - Replace Block Escaping with Escaper
This issue is automatically created based on existing pull request: magento/magento2#37160: Chore: Grouped Product - Replace Block Escaping with Escaper

---------
### Description (*)
Refactors the `Magento_GroupedProduct` module to replace `$block` escaping functions with `$escaper` escaping functions.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37095: Chore: Admin Analytics - Replace Block Escaping with Escaper

### PR DESCRIPTION
**Pull request by pykettk**
### Description (*)
Refactors the `Magento_GroupedProduct` module to replace `$block` escaping functions with `$escaper` escaping functions.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37171: Chore: Grouped Product - Replace Block Escaping with Escaper

### CODE REVIEW

**Comment by pykettk** [comment]
@magento create issue

**Review by leonhelmus — APPROVED** [review]
Looks good!

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**
Verify in the `Magento_GroupedProduct` module to replaces `$block` escaping functions with `$escaper` escaping functions after applying the PR changes.

**Before:** :heavy_multiplication_x: 
Screenshot 2023-03-20 at 4 33 27 PM


**After:** :heavy_check_mark:  
Screenshot 2023-03-20 at 4 47 26 PM

**Additonally tested:**

1. Created the group product and assigned simple product.
2. After creation verified on frontend by enabling and disabling it.
3. Created order from the frontend.
4. Added to the wishlist and added to the cart.

No additional manual test case is required in regression cycle as this PR is related to the refactoring of the codes.

As builds are failed hence, moving this PR to Extended Testing.

**Pull request closed without merging**
