### PR TITLE
Fixed #23460 Changed empty to isset so that the region will be update…

### LINKED ISSUE #23460: Region doesn't updates after changing country and leaving region select unselected
### Preconditions
1. Create user
2. Create user address with country "_United States_" and region "_Alabama_"

### Steps to reproduce
1. Go to created customer page
2. Go to address customer address tab 
3. Hit edit action for the created address at the addresses grid
4. Change the country to France
5. Don't choose any region
6. Save address
7. Run in browser console `jQuery('[data-index="region_id_input"]').show()` to display hidden State/Province field (second field with the same label)

### Expected result (*)
1. Second State/Province input is empty

### Actual result (*)
1. Second State/Province input has value Alabama (which is saved to db after hitting Save button)

### Additional
The same issue is applicable for source edit page because the main point here is Region UI component which doesn't empty hidden region input with Region label for the described case.

###Env
Mac OS
Valet+ (PHP7.1, NGINX, MYSQL)
Magento 2.3-develop branch

### PR DESCRIPTION
**Pull request by deiserh**
### Description
When a customer address is created with the first region and the address will be edited, a change of the country set the region id to zero. The region it self will not be changed.

### Fixed Issues
1. magento/magento2#23460: Region doesn't updates after changing country and leaving region select unselected

### Manual testing scenarios
1. Create a customer with an address in United States and the Region Alabama
2. Save the address
3. Edit the address again and change the country to France
4. Save the address again
5. **Result** The region will be emptied.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24690) <br/>All committers have signed the CLA.

**Review by orlangur — CHANGES_REQUESTED** [review]
@deiserh please fix failed tests and write a new integration test for a fixed case.

**Comment by Stepa4man** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, here is your [new Magento instance](https://pr-24690.instances.magento-community.engineering).
Admin access: [https://pr-24690.instances.magento-community.engineering/admin](https://pr-24690.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sidolov** [comment]
@deiserh  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
