### PR TITLE
MC-41439:  7.3 compatibility fix.

### LINKED ISSUE #32647: [Issue] MC-41439:  7.3 compatibility fix.
This issue is automatically created based on existing pull request: magento/magento2#32646: MC-41439:  7.3 compatibility fix.

---------

### Description (*)

\Magento\GroupedImportExport\Plugin\CatalogImportExport\Model\StockItemImporter\UpdateGroupedProductStockStatusPlugin breaks compatibility with PHP 7.3

### Fixed Issues (if relevant)

1. None

### Manual testing scenarios (*)

1. Switch to production mode with PHP 7.3 used for CLI.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by engcom-Foxtrot**
### Description (*)

\Magento\GroupedImportExport\Plugin\CatalogImportExport\Model\StockItemImporter\UpdateGroupedProductStockStatusPlugin breaks compatibility with PHP 7.3

### Fixed Issues (if relevant)

1. None

### Manual testing scenarios (*)

1. Switch to production mode with PHP 7.3 used for CLI.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32647: MC-41439:  7.3 compatibility fix.

### CODE REVIEW

**Comment by engcom-Foxtrot** [comment]
@magento create issue

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@gabrieldagama, aren't we running PHP 7.3-7.4 compatibility tests on all Pull requests that getting merged, including internal? For sure, it supposes to fail. If it wasn't failing - let's double-check that, there should be some issue.

**Comment by engcom-Oscar** [comment]
:heavy_check_mark: QA passed

Was checked case from Manual testing scenarios 
### Manual testing scenarios (*)

1. Switch to production mode with PHP 7.3 used for CLI.


:x: **Before:**
Screenshot from 2021-04-02 16-59-36

:heavy_check_mark: **After:**
Screenshot from 2021-04-02 16-58-39

**Pull request merged**
