### PR TITLE
Fixed typo issue

### PR DESCRIPTION
**Pull request by AfreenScarlet**
Fixed typo issue

### Description (*)
Fixed typo issue

### Fixed Issues (if relevant)
Fixed typo issue

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22594) <br/>All committers have signed the CLA.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-5023](https://jira.corp.magento.com/browse/ENGCOM-5023) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@AfreenScarlet thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by soleksii** [comment]
QA not applicable

**Pull request merged**
