### PR TITLE
Fix WebApi test to be compatible with php8

### PR DESCRIPTION
**Pull request by anzin**
### Description (*)

Stabilisation of WebApi Tests to be compatible both with PHP7 and PHP8.

### Related Issues
1. magento/magento2#34196

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by anzin** [comment]
@magento run WebAPI Tests with env PHP 8.0

**Comment by andrewbess** [comment]
@magento run all tests with env PHP 8.0

**Comment by andrewbess** [comment]
@magento run all tests

**Review by andrewbess — COMMENTED** [review]
Hello @anzin 
Thank you for your contribution here.

**Pull request merged**
