### PR TITLE
Close prompt immediately after click ok instead of wait ajax request

### LINKED ISSUE #840: Alert appears twice when the folder creation is not successful
### Preconditions (*)

1. M 2.3.3
2. Adobe Stock is configured

### Steps to reproduce (*)

1. On CMS edit page open media gallery
2. Load 5 images from Adobe Stock. One by one without page reload.
Every next save of the image will drastically decrease performance. (Memory leak suspected)
3. Click "Create Folder"
4. Type in "папка"
5. Click "OK"
6. When alert with a message "Please rename the folder Please rename the folder using only letters, numbers, underscores and dashes." appears, click "OK"
7. Click anywhere on the dark overlay

### Expected result (*)

1. Alert appears only once

### Actual result (*)

1. The same alert second time

### PR DESCRIPTION
**Pull request by Nazar65**
### Description (*)

The prompt need to be closed after press ok button instead of wait ajax request, because after unsuccessful response there is conflict with alert prompt

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/adobe-stock-integration/issues/840

### Manual testing scenarios (*)
1. On CMS edit page open media gallery
2. Load 5 images from Adobe Stock. One by one without page reload.
Every next save of the image will drastically decrease performance. (Memory leak suspected)
3. Click "Create Folder"
4. Type in "Folder"
5. Click "OK"
6. When alert with a message "Please rename the folder Please rename the folder using only letters, numbers, underscores and dashes." appears, click "OK"
7. Click anywhere on the dark overlay

### Expected result (*)

1. Alert appears only once
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
Already covered by mftf test app/code/Magento/Cms/Test/Mftf/Test/AdminCheckCreateFolderEscapeAndEnterHandlesForWYSIWYGBlockTest.xml

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7690](https://jira.corp.magento.com/browse/ENGCOM-7690) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
