### PR TITLE
Format the javascript code

### PR DESCRIPTION
**Pull request by yogeshsuhagiya**
### Description
Format the javascript code in the template file.

### Fixed Issues (if relevant)
1. N/A

### Manual testing scenarios
1. N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by VladimirZaets** [comment]
Hi @Yogeshks , thank you for collaboration. Use javascript inside *.phtml file it's legacy code that we try to refactor according to Magento way. 

For that we have [<script type="text/x-magento-init" />](http://devdocs.magento.com/guides/v2.2/javascript-dev-guide/javascript/js_init.html) tag, where we declare path to JS file and pass paramets if they are needed.

Please make refactoring according to Magento way.
If you have some questions we will glad to help you.

**Comment by yogeshsuhagiya** [comment]
Hi @VladimirZaets 
Thank you for guidance, I really like to refactor JS code.  Do I have to create a new JS component for that which a returns callback function?

**Comment by VladimirZaets** [comment]
Hi @Yogeshks , yes, you should create new JS file/component with the callback function, [as example](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/CatalogSearch/view/frontend/web/js/search-terms-log.js) and use ` <script type="text/x-magento-init" />` to call it, [as example ](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Catalog/view/adminhtml/templates/catalog/category/edit.phtml)

**Comment by yogeshsuhagiya** [comment]
Hi @VladimirZaets 
I've added JS component, please verify updates

**Comment by VladimirZaets** [comment]
Hi @Yogeshks. Updates look good, thanks. I took your PR into processing.

**Comment by magento-engcom-team** [comment]
Hi @Yogeshks. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

**Pull request merged**
