### PR TITLE
Krishna221993 patch 1 typo fixed

### PR DESCRIPTION
**Pull request by krishna221993**
### Fixed Issues (if relevant)

1. Fixed Typo of app/code/Magento/Ui/view/base/web/js/lib/core/collection.js
2. Fixed Typo of app/code/Magento/CatalogSearch/Model/ResourceModel/Advanced/Collection.php

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20775) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @krishna221993. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by VladimirZaets** [comment]
Hi @krishna221993 , please, sign CLA, otherwise, we can't process your pull request

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4048](https://jira.corp.magento.com/browse/ENGCOM-4048) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@krishna221993 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request merged**
