### PR TITLE
Fix issue with possibly colliding form-fields

### PR DESCRIPTION
**Pull request by heiglandreas**
### Description (*)

It is possible for modules to extend the form-fields within a grid. Therefore it can happen that other formfields - especially hidden fields - are added to a grid so that the query does not only return checkboxes but also other form-fields. And then the first form-field is not necessary the checkbox we want in this case.

This change alters the selector that is used to query for the first checkbox by actually only requesting checkbox-fields. So the chances are much higher that the checkbox-field we want is actually the first item of the list.

### Fixed Issues (if relevant)

1. There was not yet an issue (AFAIK)

### Manual testing scenarios (*)

1. Add a hidden field before the checkbox in the grid of products of a category
2. Try to add or remove a product to or from the category

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21508) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @heiglandreas. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by mhauri — APPROVED** [review]

**Comment by mhauri** [comment]
Thank you @heiglandreas for your Contribution.

**Comment by magento-engcom-team** [comment]
Hi @mhauri, thank you for the review.
[ENGCOM-4404](https://jira.corp.magento.com/browse/ENGCOM-4404) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@heiglandreas thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VasylShvorak** [comment]
Hi @heiglandreas I cannot reproduce issue on 2.3-develop. Could you look and provide more information how reproduce issue?

**Comment by sidolov** [comment]
@heiglandreas , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
