### PR TITLE
magento/magento2#35009: Fixed creating product in single store mode if website id != 1

### LINKED ISSUE #35009: Cannot add product in admin if single store mode website id != 1
I'm not able to add any products from admin. My Magento is in single store mode with website id = 2.
Saving a new product fails with Integrity constraint violation.
Editing and saving an existing product works fine. I am also able to create new products using the import feature.
The issue was reproduced on a clean Magento instance.

### Preconditions (*)

1. Magento Open Source 2.4.3-p1
2. php 7.4
3. MariaDB 10.4

### Steps to reproduce (*)

1. Install a clean version of Magento version 2.4.3-p1
2. Add a new website, store and store view, and make this the default
 * In Stores -> All Stores:
 
	 * Create new website (`new_website`)
	 * Create new store (`new_store`) under new_website
	 * Create new store view (`new_store_view`)  under new_store
 * Open `new_website` again, and set this as default. Save.

3. Delete the preinstalled website (`base`)
4. Verify your website db entries. The default website should be 2:

    ```
    SELECT * FROM store_website;
    +------------+-------------+-------------+------------+------------------+------------+
    | website_id | code        | name        | sort_order | default_group_id | is_default |
    +------------+-------------+-------------+------------+------------------+------------+
    |          0 | admin       | Admin       |          0 |                0 |          0 |
    |          2 | new_website | New Website |          0 |                2 |          1 |
    +------------+-------------+-------------+------------+------------------+------------+
    
    ```
5. In Stores -> Configuration -> General -> SIngle-Store Mode
 * Enable Single-store Mode. Save.
6. Verify your Single-store configuration:

   ```
   bin/magento config:show general/single_store_mode/enabled
   ```
   Should return 1
7. In Catalog -> Products
 * Add Product
 * Populate name, sku and price. Save.

### Expected result (*)

1. The product should save successfully

### Actual result (*)

1. The save action fails, with the following message:

```
`SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`denuhabsxr`.`catalog_product_website`, CONSTRAINT `CATALOG_PRODUCT_WEBSITE_WEBSITE_ID_STORE_WEBSITE_WEBSITE_ID` FOREIGN KEY (`website_id`) REFERENCES `store_website` (`website_id`) ON DELETE ), query was: INSERT INTO `catalog_product_website` (`product_id`,`website_id`) VALUES (?, ?)`
```

### PR DESCRIPTION
**Pull request by hutychivan**
### Description (*)

Unable to create a product if website id != 1 and enabled single store mode.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35009

### Manual testing scenarios (*)

1. Install a clean version of Magento version 2.4-develop
2. Add a new website, store and store view, and make this the default
3. In Stores -> All Stores:
4. Create new website (new_website)
5. Create new store (new_store) under new_website
6. Create new store view (new_store_view) under new_store
7. Open new_website again, and set this as default.
8. Save the website
9. Delete the preinstalled website (base)
10. In Stores -> Configuration -> General -> SIngle-Store Mode (Enable Single-store Mode -> Save)
11. In Catalog -> Products (Add Product .Populate name, sku and price. Save.)

### Questions or comments

It is not possible to create a product because it is not possible to create a link between the product and the website. \Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper::filterWebsiteIds - always sets the value to 1 in single store mode, but this is an error and the function description is not correct 
image
Now we have key 2 (website id) and value 1. But later when creating links we use value not key \Magento\Catalog\Model\ResourceModel\Product\Website\Link::updateProductWebsite
image
Here are some more examples of the input array
image
image
image
There is an error in the description of the function and we do not get 1 in the selected websites, but we get their id. It has been fixed that the value 1 was always set for single store mode

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hutychivan** [comment]
@magento run all tests

**Comment by hutychivan** [comment]
@magento run all tests

**Comment by hutychivan** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Integration Tests, Unit Tests

**Comment by hutychivan** [comment]
@magento run Functional Tests CE, Unit Tests

**Comment by hutychivan** [comment]
@magento run Functional Tests CE

**Comment by hutychivan** [comment]
@magento run Functional Tests CE

**Comment by eduard13** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Sample Data Tests B2B,Sample Data Tests CE,Sample Data Tests EE

**Comment by eduard13** [comment]
@magento run Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE, Functional Tests B2B

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @hutychivan,

Thanks for the contribution!

It seems some integration tests are failing due to changes. Please resolve them.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE

**Comment by hutychivan** [comment]
Hello @engcom-Echo,
I think my changes cannot affect the tests, so I will restart them and see in which places the tests are failing. Up until this point, all tests have passed.
Thanks

**Comment by hutychivan** [comment]
@magento run Functional Tests B2B, Sample Data Tests CE, Sample Data Tests EE, Sample Data Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by eduard13** [comment]
@magento run Functional Tests B2B

**Comment by hutychivan** [comment]
@magento run Functional Tests B2B

**Comment by hutychivan** [comment]
@magento run Functional Tests B2B

**Review by engcom-Hotel — APPROVED** [review]
Hello @hutychivan,

The failed tests seem flaky to me. Both the time, the reason of failures is different:

[Allure Report 1](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37292/fdad31d60172f1a7abe3f8520d46bfc2/Functional/allure-report-b2b/index.html#categories/56bfb88f8331953afd05f2f23b44d990/e9b1c3ca01c484d9/)
image

[Allure Report 2](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37292/2b7209df91ad9b6bb1a5dc4d775c5ac3/Functional/allure-report-b2b/index.html#categories/400e27cb28395b6ee51a18ca97ee1f5b/dbd4fe3aee07b3a1/)
image


Hence approving the PR.

Thanks

**Review by eduard13 — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

1. Install a clean version of Magento version 2.4-develop
2. Add a new website, store and store view, and make this the default
3. In Stores -> All Stores:
4. Create new website (new_website)
5. Create new store (new_store) under new_website
6. Create new store view (new_store_view) under new_store
7. Open new_website again, and set this as default.
8. Save the website
9. Delete the preinstalled website (base)
10. In `Stores -> Configuration -> General -> SIngle-Store Mode (Enable Single-store Mode -> Save)`
11. In `Catalog -> Products (Add Product .Populate name, sku and price. Save.)`

**Before:** :heavy_multiplication_x: Getting error while creating product.
Screenshot 2023-05-09 at 2 43 22 PM

Screenshot 2023-05-09 at 2 43 54 PM


**After:** :heavy_check_mark:  Now able to create the product
Screenshot 2023-05-09 at 3 22 40 PM

Referring above [comment](https://github.com/magento/magento2/pull/37292#pullrequestreview-1416609071)  Moving this PR to **Merge in progress.**

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by hutychivan** [comment]
@engcom-Echo I noticed that my changes are already in the develop branch, but the pull request is still open with empty changes. https://github.com/magento/magento2/commit/91b959b7f7c8afec63b1438c1292512fc342634a

**Comment by engcom-Charlie** [comment]
> @engcom-Echo I noticed that my changes are already in the develop branch, but the pull request is still open with empty changes. [91b959b](https://github.com/magento/magento2/commit/91b959b7f7c8afec63b1438c1292512fc342634a)

Hi @hutychivan,

As after adding this this PR into mainline PR, we have added one commit of merging 2.4-dev into this, that is the reason it is still showing as in Open status

Thank you!

**Comment by hutychivan** [comment]
@engcom-Charlie Thanks for reply. Could you merge this PR, for our Partner Contribution to be counted?

**Comment by engcom-Charlie** [comment]
> @engcom-Charlie Thanks for reply. Could you merge this PR, for our Partner Contribution to be counted?

The PR is already merge as I have mentioned. 

> @engcom-Charlie Thanks for reply. Could you merge this PR, for our Partner Contribution to be counted?

This PR is already merged in [d4a9791](https://github.com/magento/magento2/commit/d4a9791d0f589ee1006beba25c240a39a59d50e9). Why it is in open status after that too, that I have explained it. 

As its merged, we have already moved this PR in Recently merge as you can see

Thank you!

**Comment by ihor-sviziev** [comment]
the changes from this PR was already merged in https://github.com/magento/magento2/commit/c7402729868f9753f6d7a4e48c4a47d6a78f06be

**Pull request closed without merging**
