### PR TITLE
Fix document elements check to prevent WYSIWYG error on IE

### LINKED ISSUE #13209: Wysiwyg editor fails on IE11
Install a clean magento. I am using 2.1.9 but the same thing happens in 2.2.2 and will happen on any version that still uses tinyMce 3.4.7

## Preconditions

Magento Version 2.*
## Steps to reproduce

Go to magento backend and edit any wysiwyg field using IE11. Select a text and click the link button. Or just click the wysiwyg html button.
## Expected result

Inserted link should be attached to selected text or I can see the html source of the wysiwyg content
## Actual result

Selected text gets deselected when click link button. Html source is empty when clicking html button

### PR DESCRIPTION
**Pull request by krzksz**
### Description (*)

When creating a document using `DomParser`'s `parseFromString` method from an empty string, IE 11 returns a document which both `head` and `body` elements are `null`, which caused the errors.

Fixes https://github.com/magento/magento2/issues/13209

### Fixed Issues (if relevant)

1. magento/magento2#13209: Wysiwyg editor fails on IE11

### Manual testing scenarios (*)

1. Open Magento admin panel on Internet Explorer 11.
2. Go to any WYSIWYG editor field, e.g. CMS page content editor.
3. Start typing.
4. No error popup is displayed.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by krzksz** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @krzksz. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @krzksz, here is your [new Magento instance](https://pr-25693.instances.magento-community.engineering).
Admin access: [https://pr-25693.instances.magento-community.engineering/admin](https://pr-25693.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by lbajsarowicz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-6310](https://jira.corp.magento.com/browse/ENGCOM-6310) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Bravo** [comment]
Hello @lbajsarowicz. Would You please add an appropriate [label](https://github.com/magento/magento2/pull/25693#issuecomment-557378572) to this PR. Thank You.

**Comment by lbajsarowicz** [comment]
> Hello @lbajsarowicz. Would You please add an appropriate [label](https://github.com/magento/magento2/pull/25693#issuecomment-557378572) to this PR. Thank You.

Label added.

**Comment by engcom-Bravo** [comment]
Hello @krzksz. Thank You for Your contribution. Please cover Your PR with the appropriate Auto-Tests in order for us to be able to process it further. Thank You.

**Comment by krzksz** [comment]
Alright, I'm up for the challenge! 😄

**Comment by krzksz** [comment]
So I tried to prepare tests for this scenario but there are 2 issues with covering it:
1. MFTF documentation states that `A Selenium web driver cannot enter data to fields with WYSIWYG.` so I am not able to test it.
2. Even if I where then I believe tests are not executed on IE, where error occurs.

**Comment by krzksz** [comment]
@engcom-Bravo I believe this can be picked up for QA and merge now.

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
