### PR TITLE
fix custom design applied on product/category page

### LINKED ISSUE #7503: Category design / theme update not inheriting correctly on product pages
### Preconditions

1. Magento 2.1.2, PHP 7.0.6, MySQL 14.14
2. Environment: [hypernode-vagrant](https://github.com/ByteInternet/hypernode-vagrant) & production [Hypernode](https://hypernode.com/)
3. Happens in both developer and production mode

### Steps to reproduce

1. Set the theme for a specific storeview to **Magento Blank** via Content > Design > Configuration > Edit.
2. Create and install a theme that inherits from **Magento Luma**. Add some layout changes. For this example, I created a theme that removes the `logo` block through `default.xml`: [theme-frontend-test](https://github.com/pascaladriaansen/theme-frontend-test)
3. Deploy static content for the 'LAB51 Test' theme: 
`bin/magento setup:static-content:deploy --theme="LAB51/test" en_US`
4. Apply the 'LAB51 Test' theme to a category via Products > Categories > Design > Theme. Be sure to check the "Apply Design to Products" checkbox.

### Expected result

1. When checking the category or a product page, you should not see the logo. It should look like the Luma theme was applied (e.g. the grey top bar and nav bar).

### Actual result

1. On the category page, the logo is removed correctly and it also looks like Luma. 
However on the product page, we see the Luma logo. We also see some links in the top right of the header, that should not be there, since the 'LAB51 Test' theme inherits from Magento Luma, and Luma removes these links. The copyright bar in the footer also looks like a combination of the Blank copyright bar and the Luma copyright bar.

### LINKED ISSUE #8333: Magento v2.1.2 - Choosing a child theme for product page
The Magento only pulls through the styles from the child theme, and not the layouts. The XML files are pulled from the parent theme wich is wrong.

### Preconditions
1. Install Magento 2.1.2 , PHP 5.6.29, MySQL 5.6

### Steps to reproduce

1. Trying to setup a child theme specifically for some products. However, this doesn't contribute. Magento does not pull layout from the "child theme".
2. See the theme catalog structure:
Master_theme
    -- theme
        -- Magento_Catalog
            -- layout
                -- catalog_product_view.xml
Child_theme
    -- theme
        -- Magento_Catalog
            -- layout
                -- catalog_product_view.xml

Magento pulls the "catalog_product_view.xml" from the parent theme instead of child.
That is the problem!

### Expected result
1. Magento pulls the "catalog_product_view.xml" from the child theme.

### Actual result
1. admin panel --> product edit --> select design tab --> new theme --> select "child theme"
http://dl3.joxi.net/drive/2017/01/30/0019/0670/1295006/06/d588e67506.jpg
I chose the theme needed and save. But it does not help pulling layouts.

### Additional information
Exactly the same bug was described here - http://magento.stackexchange.com/questions/145687/magento-2-v2-1-2-choosing-separate-theme-for-product-page
And the solution was not found.

### LINKED ISSUE #26295: Magento v2.3 - Choosing a child theme for product .. layout xml doesn't work nor does the layout update
### Preconditions (*)

1. Magento 2.3.x & 2.4-develop
2. PHP 7.2

### Steps to reproduce (*)
When you apply *ThemeC* on a product, then only the (extended) layout of *ThemeB* will be taken in the following scenario:

```
VendorA
  |__/ThemeA (parent: Magento/blank)
    |__/Magento_Catalog
      |__/layout
        |--catalog_product_view.xml

VendorB
  |__/ThemeB (parent: VendorA/ThemeA; applied theme for store)
    |__/Magento_Catalog
      |__/layout
        |--catalog_product_view.xml
  |__/ThemeC (parent: VendorB/ThemeB)
    |__/Magento_Catalog
      |__/layout
        |--catalog_product_view.xml
```

I don't know if there is any difference when all themes are by the same vendor, but at least this is my setup.
Even tough above setup describes extending layouts I've also tried to override the layout with the same effect.

**Expected result**
Magento pulls the "catalog_product_view.xml" from the child theme(theme C).

**Actual result**
Magento pulls the "catalog_product_view.xml" from the theme B.

-----------------------------------------------
**Additional information**
Currently I have fixed the issue with this [patch provided by kirmorozov](https://github.com/magento/magento2/issues/8333#issuecomment-363814837).

### PR DESCRIPTION
**Pull request by AurelienLavorel**
Fix custom design applied on product/category page

### Description (*)

Change design from backoffice for one product or category make a merge of both themes. 

### Fixed Issues (if relevant)

1. Fixes magento/magento2#26295
1. Fixes magento/magento2#8333
1. Fixes magento/magento2#7503

### Manual testing scenarios (*)

1. Put Luma as a default theme
2. Put blank theme on a product page
3. Navigate to the product
4. Blank theme is applied

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
Can you cover changes with automation tests ? Unit Tests may be suitable for such case.

**Comment by mrtuvn** [comment]
Seem you steps reproduce not same as author reported in ticket 26295
cc @PaulWatt

**Comment by ihor-sviziev** [comment]
@mrtuvn, I think this PR related to https://github.com/magento/magento2/pull/31929, maybe you're even trying to fix the same issue

**Comment by mrtuvn** [comment]
Yes seem both modify at same file. But i think may difference use-case reproduce problem. In this PR link to 3 issues but only one remain open with clear steps. But i don't check that case yet. Let's see author response

**Comment by AurelienLavorel** [comment]
I don't know if I can make a test for that, will take a look.

My business use case:
1. Apply Luma theme globally
2. Create a new theme "Example" (from Hyva here)
3. Change the design from the backoffice for a product to "Example"
4. Go to the product page
Without that fix, you'll see that the Luma's css/js is still loaded, so you got 404 errors and a break frontend
With that fix, you'll have the same design as if you apply "Example" globally

But it take too much time to test so I reduce the steps

**Comment by bgorski** [comment]
@AurelienLavorel from what you described, I think you would be better off with an integration test instead of a unit test. If you have any issues with creating one, ping me on the community engineering slack, perhaps I'll be able to help you with that.

**Comment by bgorski** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
Not sure but i thought we already fixed issue in this commit https://github.com/magento/magento2/commit/76825d1b61cd18ac91683f615c31de163a472f89! 
Is possible we missed some cases

**Comment by AurelienLavorel** [comment]
@mrtuvn thank you, it's fine with that commit, I don't know how I miss it

**Pull request closed without merging**
