### PR TITLE
Fix of invalid price for integer currencies when amount less than group size

### PR DESCRIPTION
**Pull request by vkublytskyi**
### Description

This is backported magento/magento2#16588 and related to magento/magento2#15909.

After correct fixes in magento/magento2#15909 (magento/magento2#15540) client-side formatting starts corrupt prices in currencies without minor units if price amount is less then number group size (usually equal to 3 numbers).

### Fixed Issues (if relevant)

1. magento/magento2#11717: Wrong price amount on a product page

### Manual testing scenarios

STR:
1. Install Magento
2. Set USD as a base currency
3. Set JPY as display currency (it also should be enabled as available currency)
4. Add product with price 0.01 USD
5. Add currency rate as 110 JPY for 1 USD
6. Open product page

AC: price 0,001 is displayed (wrongly added 0 to have group separator visible)

ER: price 1 is displayed (no decimal part, no preceding 0)

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @vkublytskyi. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by orlangur — APPROVED** [review]

**Comment by orlangur** [comment]
@vkublytskyi please pay attention that `2.2.x` is current release line.

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-2213](https://jira.corp.magento.com/browse/ENGCOM-2213) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @vkublytskyi. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.6. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
