### PR TITLE
Fix zoom on search input #27506

### PR DESCRIPTION
**Pull request by ptylek**
### Description (*)

When you click the search box, the browser zooms on the input. This happens on devices using Safari (tablet and mobile) and on both Blank and Luma theme.
This happens because the browser will zoom if the font-size is less than 16px.

The easiest fix is to use font-size of 16px instead of base 14px for that input.

### Fixed Issues (if relevant)

1. magento/magento2#27506: Viewport resizing on search input focus on iphone

### Manual testing scenarios (*)

1. Click search icon
2. Click search input
3. With changes from this PR, the browser won't zoom on the input

Repeat for Blank and Luma theme.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-7289](https://jira.corp.magento.com/browse/ENGCOM-7289) has been created to process this Pull Request
:eight_spoked_asterisk: @miguelbalparda, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [new Magento instance](https://pr-27603.instances.magento-community.engineering).
Admin access: [https://pr-27603.instances.magento-community.engineering/admin_45a8](https://pr-27603.instances.magento-community.engineering/admin_45a8)
Login: `900ff395` Password: `f6edd0458b54`
Instance will be terminated in up to 3 hours.

**Review by engcom-Alfa — COMMENTED** [review]
Hi @ptylek 

Unfortunate, we are not able to reproduce the issue on the fresh 2.4-develop instance

**Preconditions:**
Luma theme
Safari browser
iPhone 6
OS v. 12.4.5

**Actual Result:**
ezgif com-video-to-gif

Or are we doing something wrong?
@ptylek Could you take a look?

Thanks!

**Comment by ptylek** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ptylek. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ptylek, here is your [Magento instance](https://i-27603-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27603-2-4-develop.instances.magento-community.engineering/admin_5f70](https://i-27603-2-4-develop.instances.magento-community.engineering/admin_5f70)
Login: `a0dd0067` Password: `0a467347abf2`
Instance will be terminated in up to 3 hours.

**Comment by ptylek** [comment]
@engcom-Alfa I think you used test instance based on PR changes. I just checked it on 2.4 vanilla test instance.

RPReplay_Final1586526462

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [Magento instance](https://i-27603-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27603-2-4-develop.instances.magento-community.engineering/admin_be19](https://i-27603-2-4-develop.instances.magento-community.engineering/admin_be19)
Login: `444138f2` Password: `9a4c7ad3d1d0`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

Go to Storefront -> :mag: 

**Before:**
ezgif com-video-to-gif (1)


**After:**
ezgif com-video-to-gif

**Pull request merged**
