### PR TITLE
Newsletter subscription emails should also use paragraph tags

### LINKED ISSUE #28166: [Issue] Newsletter subscription emails should also use paragraph tags
### Description (*)

Other emails (also subscription confirmation email in the same module) are using proper html tags for their content.
```
<p>{{trans "To begin receiving the newsletter, you must first confirm your subscription by clicking on the following link:"}}</p>
```
The same should apply for newsletter subscription and unsubscription emails.

This will help in keeping same email styling.

### Steps to reproduce
1. As a logged in user go to User Area - Newsletter section and subscribe / unsubscribe to the newsletter.
2. Go to your email box and check those emails

### PR DESCRIPTION
**Pull request by ptylek**
### Description (*)

Other emails (also subscription confirmation email in the same module) are using proper html tags for their content.
```
<p>{{trans "To begin receiving the newsletter, you must first confirm your subscription by clicking on the following link:"}}</p>
```
The same should apply for newsletter subscription and unsubscription emails.

This will help in keeping same email styling.

### Fixed Issues (if relevant)

Couldn't find issue.

### Manual testing scenarios (*)

1. As a logged in user go to User Area - Newsletter section and subscribe / unsubscribe to the newsletter.
2. Go to your email box and check those emails

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28166: Newsletter subscription emails should also use paragraph tags

### CODE REVIEW

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @ptylek. Thank you for your collaboration. 

Please, take a look at the failing functional tests

**Comment by ptylek** [comment]
@rogyar , I don't think these failing tests are related. I will run them again.

**Comment by rogyar** [comment]
Hi @ptylek. Sorry, my fault. I meant integration tests. It does look like the integration tests use the old email body in the assertion. And the subscribe/unsubscribe tests are failing because of that. 

So we need to modify the assertion expectation to match our change. 

Thank you.

**Comment by ptylek** [comment]
@magento run Database Compare, Integration Tests

**Comment by ptylek** [comment]
@rogyar just wanted to confirm if this PR is also going to be merged? As tests for this PR have received `Progress: accept` label

**Comment by rogyar** [comment]
Hi @ptylek. We still have the integration tests failing. So the integration tests need to be fixed before the PR merge. 

Thank you

**Comment by ptylek** [comment]
@rogyar Only database test is failing, however I think this is not related to this PR.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7522](https://jira.corp.magento.com/browse/ENGCOM-7522) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Delta. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Delta, here is your [new Magento instance](https://pr-27357.instances.magento-community.engineering).
Admin access: [https://pr-27357.instances.magento-community.engineering/admin_ffce](https://pr-27357.instances.magento-community.engineering/admin_ffce)
Login: `c987044d` Password: `8526dea33eaf`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Before:
image

image

After:
image

image

**Comment by engcom-Echo** [comment]
@magento Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by slavvka** [comment]
@magento create issue

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @ptylek. Thanks for collaboration. I think this case can be covered by MFTF tests, can you please do it?

**Comment by ptylek** [comment]
> Hi @ptylek. Thanks for collaboration. I think this case can be covered by MFTF tests, can you please do it?

@lbajsarowicz provided integration tests for this PR -> https://github.com/magento/magento2/pull/27609. Aren't these sufficient?

All other e-mails use proper html tags and there aren't any MFTF tests for that. This is a small fix to add html tag in e-mail template that misses them.

**Comment by VladimirZaets** [comment]
Hi @ptylek. Integration test is ok for this case, thank you, I missed PR with coverage

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7522](https://jira.corp.magento.com/browse/ENGCOM-7522) has been created to process this Pull Request

**Pull request merged**
