### PR TITLE
2.3.3 Fix multiple copy to email recipients

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)
This PR partially reverts a change introduced in https://github.com/magento/magento2/commit/a3d86cd8af0a529dc494fb0c055888a2b30afe61#diff-fd5e8d031335fde4387c31484dfcb308 to address this error message
```
TypeError: Argument 1 passed to Magento\Email\Model\Template\Interceptor::setVars() must be of the type array, null given, called in /var/www/vendor/magento/framework/Mail/Template/TransportBuilder.php on line 368
```
when trying to send multiple copies of the same email. 

When `getTransport()` is called it will reset template vars at the end. The `configureEmailTemplate()` needs to be part of the loop to repopulate that information.

```
    public function getTransport()
    {
        $this->prepareMessage();
        $mailTransport = $this->mailTransportFactory->create(['message' => clone $this->message]);
        $this->reset();
        return $mailTransport;
    }
    /**
     * Reset object state
     *
     * @return $this
     */
    protected function reset()
    {
        $this->message = $this->messageFactory->create();
        $this->templateIdentifier = null;
        $this->templateVars = null;
        $this->templateOptions = null;
        return $this;
    }
```

```
    protected function configureEmailTemplate()
    {
        $this->transportBuilder->setTemplateIdentifier($this->templateContainer->getTemplateId());
        $this->transportBuilder->setTemplateOptions($this->templateContainer->getTemplateOptions());
        $this->transportBuilder->setTemplateVars($this->templateContainer->getTemplateVars());
        $this->transportBuilder->setFromByScope(
            $this->identityContainer->getEmailIdentity(),
            $this->identityContainer->getStore()->getId()
        );
    }
```

### Fixed Issues (if relevant)
1. none added

### Manual testing scenarios (*)

1. Configure Sales Emails to send two copies of the invoice confirmation as per the below screenshot
image
2. Create an invoice for an order in the admin with "Email Copy of Invoice" ticked
image
3. Note no fatal error ` "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Email\Model\Template\Interceptor::setVars() must be of the type array, null given, called in /var/www/vendor/magento/framework/Mail/Template/TransportBuilder.php on line 368 and defined in /var/www/generated/code/Magento/Email/Model/Template/Interceptor.php:189`

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-6001](https://jira.corp.magento.com/browse/ENGCOM-6001) has been created to process this Pull Request

**Comment by kalpmehta** [comment]
@fooman Thanks for your contribution! Can you please cover the changes with automated tests?

**Comment by fooman** [comment]
@kalpmehta adding tests for this would take a while as I am currently busy with getting my extensions ready (this change set is reverting to what was working prior to 2.3.3) and I was hoping we can get this fixed before 2.3.3 gets publicly released

**Comment by fooman** [comment]
Also to do email testing properly some additional infrastructure would be needed (currently all emails are suppressed during integration tests). We spin up an instance of mailhog in our tests [here](https://github.com/fooman/emailattachments-implementation-m2/blob/develop/tests/integration/testsuite/Fooman/EmailAttachments/Observer/Common.php) and then query it's api to confirm the email is correct.

**Comment by kalpmehta** [comment]
@fooman Ok I am approving the changes, if you get a chance feel free to add the tests later.

**Review by kalpmehta — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, thank you for the review.
[ENGCOM-6001](https://jira.corp.magento.com/browse/ENGCOM-6001) has been created to process this Pull Request

**Review by engcom-Golf — DISMISSED** [review]

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-6001](https://jira.corp.magento.com/browse/ENGCOM-6001) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
