### PR TITLE
REST products update category_ids cannot be removed

### PR DESCRIPTION
**Pull request by ygyryn**
Fixed issue with not correct updating products category_ids through /rest/ for custom_attribute { 'category_ids } data.

### Description (*)
Added call of assignProductToCategories method in \Magento\Catalog\Model\ProductRepository::save
in case when a product currently don't have extension attributes.
This is needed to fix a problem with not correct updating category_ids  when try to update the product with /rest/all/V1/products/ through custom_attribute { 'category_ids': '['10127', '10048'] },

### Fixed Issues
magento/magento2#20481: REST products update category_ids cannot be removed

### Manual testing scenarios (*)
1. Open in swagger catalogProductRepositoryV1 and call PUT: /V1/products/{sku} 

2. Use test product with such test case:
    "custom_attributes": [
      {
        "attribute_code": "category_ids",
        "value": [
          "1", "2", "3", "4"
        ]
      }
    ]
testcase

Result will be such: all category_ids with provided id's "1", "2", "3", "4" will be assigned to product.

3. Then try to remove some categories:  
    "custom_attributes": [
      {
        "attribute_code": "category_ids",
        "value": [
          "1", "3"
        ]
      }
    ]
Result will be such:  category_ids with provided id's "1", "3" will be assigned to product. 
Other category_ids, that where before, will be unassigned from product, as expected.

So now category_ids are updated correct!

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20842) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @ygyryn. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-20842.instances.magento-community.engineering).
Admin access: [https://pr-20842.instances.magento-community.engineering/admin](https://pr-20842.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by dmytro-ch** [comment]
Hi @ygyryn, thank you for your contribution!

There are couple of test failures with the current solution in `Magento\Catalog\Test\Unit\Model\ProductRepositoryTest`.
Could you please check and update Unit tests for product repository according to the latest changes in code?

Thank you.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4173](https://jira.corp.magento.com/browse/ENGCOM-4173) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@ygyryn thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by siliconalchemy** [comment]
As of Magento 2.3.3, this problem is NOT fixed.  Assigning a reduced list of category_ids does not correctly remove remaining category_ids that should no longer be there.

**Pull request merged**
