### PR TITLE
Fix for #21491 performance toolkit enhancements

### PR DESCRIPTION
**Pull request by Stoyvo**
### Description (*)
Implement sales_invoice data fixtures for performance toolkit.
For more context as to why this is important, please review the issue this addresses:
https://github.com/magento/magento2/issues/21491

### Fixed Issues (if relevant)
1. magento/magento2#21491: Performance ToolKit missing Invoices

### Manual testing scenarios (*)
1. `bin/magento setup:performance:generate-fixtures -s setup/performance-toolkit/profiles/ce/medium.xml`

### Contribution checklist (*)
 - [ X ] Pull request has a meaningful description of its purpose
 - [ X ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21492) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @Stoyvo. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by Stoyvo** [comment]
Found issue with %firstname% %lastname% change, will address and push change.

**Comment by Stoyvo** [comment]
Issue with pull request fixed.

**Comment by slavvka** [comment]
@magento run all tests

**Comment by aloupfor** [comment]
I was looking for a way to have some orders with invoice loaded and found this pull request (thank you for it).

I made the following changes as some values seemed wrong:
```
$ git diff
diff --git a/setup/src/Magento/Setup/Fixtures/_files/orders_fixture_data.json b/setup/src/Magento/Setup/Fixtures/_files/orders_fixture_data.json
index c774b1e..07ad9dc 100644
--- a/setup/src/Magento/Setup/Fixtures/_files/orders_fixture_data.json
+++ b/setup/src/Magento/Setup/Fixtures/_files/orders_fixture_data.json
@@ -19,7 +19,7 @@
     "customer_id": "NULL",
     "base_discount_amount": -1.7000,
     "base_discount_canceled": "NULL",
-    "base_discount_invoiced": "NULL",
+    "base_discount_invoiced": -1.7000,
     "base_discount_refunded": "NULL",
     "base_grand_total": 25.3000,
     "base_shipping_amount": 10.0000,
@@ -214,7 +214,7 @@
     "no_discount": "'0'",
     "qty_backordered": "NULL",
     "qty_canceled": 0.0000,
-    "qty_invoiced": 0.0000,
+    "qty_invoiced": 1.0000,
     "qty_ordered": 1.0000,
     "qty_refunded": 0.0000,
     "qty_shipped": 0.0000,
@@ -231,14 +231,14 @@
     "discount_percent": 10.0000,
     "discount_amount": 0.8500,
     "base_discount_amount": 0.8500,
-    "discount_invoiced": 0.0000,
-    "base_discount_invoiced": 0.0000,
+    "discount_invoiced": 0.8500,
+    "base_discount_invoiced": 0.8500,
     "amount_refunded": 0.0000,
     "base_amount_refunded": 0.0000,
     "row_total": 8.5000,
     "base_row_total": 8.5000,
-    "row_invoiced": 0.0000,
-    "base_row_invoiced": 0.0000,
+    "row_invoiced": 8.5000,
+    "base_row_invoiced": 8.5000,
     "row_weight": 1.0000,
     "base_tax_before_discount": "NULL",
     "tax_before_discount": "NULL",
@@ -612,10 +612,6 @@
     "discount_description": "NULL",
     "customer_note": "NULL",
     "customer_note_notify": 1,
-    "base_customer_balance_amount": "NULL",
-    "customer_balance_amount": "NULL",
-    "base_gift_cards_amount": "NULL",
-    "gift_cards_amount": "NULL",
     "_resource": "Magento\\Sales\\Model\\ResourceModel\\Order\\Invoice"
   },
   "sales_invoice_grid": {
```

With:
```
    "base_customer_balance_amount": "NULL",
    "customer_balance_amount": "NULL",
    "base_gift_cards_amount": "NULL",
    "gift_cards_amount": "NULL",
```
when running `bin/magento setup:perf:generate-fixtures` I have the following error:
> SQLSTATE[42S22]: Column not found: 1054 Unknown column

Is this related to a difference between Magento 2 CE/EE ?

**Comment by sivaschenko** [comment]
Hi @Stoyvo any update on this pull request? Are you going to continue progress on it?

**Comment by slavvka** [comment]
Hey @Stoyvo. I am closing this PR due to inactivity. Please feel free to reopen it once you decide to proceed.

**Pull request closed without merging**
