### PR TITLE
XSD URN format

### LINKED ISSUE #30552: [Issue] XSD URN format
This issue is automatically created based on existing pull request: magento/magento2#30530: XSD URN format

---------

### Description (*)
Updated XSD URN format in XML files.

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Questions or comments
N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by mage2pratik**
### Description (*)
Updated XSD URN format in XML files.

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Questions or comments
N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30552: XSD URN format

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Integration Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Integration Tests, Performance Acceptance Tests

**Comment by sidolov** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
Seems like test failures are not related to changes from this PR. Let's wait a bit

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Integration Tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8360](https://jira.corp.magento.com/browse/ENGCOM-8360) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run Performance Acceptance Tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
