### PR TITLE
Remove unused requirejs alias defined

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Remove unused resources defined
### Fixed Issues (if relevant)

1. magento/magento2#26963: Missing JS file (critical-css-loader) in Magento 2.3.4

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

Seem js files defined before in previous commits but never been used in anywhere in codebase
### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
The error on **Functional Tests B2B** is not related to the changes introduced.

**Comment by mrtuvn** [comment]
Hi any update on this ?

**Review by lbajsarowicz — APPROVED** [review]
I'm sorry. I've been waiting for tests to pass. Reviewed once again if aliases are not being used - accept.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7065](https://jira.corp.magento.com/browse/ENGCOM-7065) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
