### PR TITLE
Fix minicart not cleared after order completion

### LINKED ISSUE #1461: Cart Items are not deleted after success checkout
Is this new feature or is a bug?
screen shot 2015-07-09 at 09 56 14

### LINKED ISSUE #4416: Mini cart shows old values when customer session is over
## Steps to reproduce
1. Magento 2.0.2, all cache types are disabled
2. go to frontend, do not log in
3. add few products to shopping cart
4. wait until session is over (1 hour by default)
5. go to shopping cart page
## Expected result
1. shopping cart and mini shopping cart should show the same values - zero in our case
## Actual result
1. shopping cart is empty, but mini shopping cart has added products https://drive.google.com/file/d/0B6jlEIvY3J2OM0dpaEx5azM5RkU/view

### LINKED ISSUE #4460: shipping cart is empty than also minicart display item [ Magento 2.0.0 ]
i have install magento 2.0.0 on live server

when i have remove items from shipping cart, minicart not updated.

now i refresh page few times, than also minicart display item.

### LINKED ISSUE #4969: minicart not cleared after order completion
I'm facing the issue of minicart not cleared after order completion using our custom payment method.

This is the same issue as:
[Cart Items are not deleted after success checkout #1461](https://github.com/magento/magento2/issues/1461)

As we're creating extension for payment method, we've limitation to not to override, modify or inject our content to any view or layout (like onepage/success) after order completion.
i.e; all the process is working on server end in our action controller.

### PR DESCRIPTION
**Pull request by AntonEvers**
Fixes #4460 Fixes #4416 Fixes #1461 Fixes #4969 Fixes MAGETWO-52593

### CODE REVIEW

**Comment by Ctucker9233** [comment]
when is this going to be merged?

**Review by lucscu — APPROVED** [review]
great, it works

**Review by maqlec — APPROVED** [review]

**Comment by SerhiyShkolyarenko** [comment]
@ajpevers thank you for taking part in development. All the issues you mentioned seem to be fixed by internal changes, aren't they? Is any of them still reproducible for you on develop branch or 2.0.9 release?

**Comment by PieterCappelle** [comment]
@SerhiyShkolyarenko Are you sure? I don't think so. If you compare https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/view/frontend/templates/success.phtml (develop branch) with this PR (https://github.com/ajpevers/magento2/blob/9093ce9c2f5a4ba8c60ef0dd0769e620b4ce6f18/app/code/Magento/Checkout/view/frontend/templates/success.phtml).

The problem still exists in 2.1.2.

**Comment by Ctucker9233** [comment]
@PieterCappelle is correct. These changes do not appear in 2.1.2.

**Comment by AntonEvers** [comment]
There might be another solution to this problem, so I think only a functional test can tell. I haven't had the time yet to do this.

**Comment by Silarn** [comment]
Running 2.1.2, the minicart does not clear on order place. Testing this fix.

**Comment by chinthu** [comment]
Running 2.1.2, the minicart issue is still there and its not clearing after success checkout

**Comment by mamsincl** [comment]
Nobody mentioned before, but looks like the issue happens with guest checkout only (v2.1.2)

**Comment by sumanta-cn** [comment]
@mamsincl No, the issue is also occurring for registered customers. I got it at magento version 2.1.2

**Comment by kanduvisla** [comment]
This bug still occurs in M2.1.3. Can anyone confirm that this patch also solves this issue there?

**Comment by Ctucker9233** [comment]
@SerhiyShkolyarenko Any plans to still merge this pull request? Any idea what release version it will be in?

**Comment by redelschaap** [comment]
@SerhiyShkolyarenko Any update on this? Issue still exists in 2.1.5.

**Comment by jwittorf** [comment]
Still having the issue in 2.1.6

**Comment by surfer190** [comment]
I can confirm that this fix works for Magento 2.1.5. I am unsure what is the hold up in merging this into the repo.
Clearly a common issue.

**Comment by nntoan** [comment]
@surfer190 This is what hold up this merging:
```
Uncaught TypeError: Cannot read property 'sectionLoadUrl' of undefined
    at Object.getFromServer (customer-data.js:89)
    at Object.reload (customer-data.js:306)
    at (index):525
    at Object.execCb (require.js:1650)
    at Module.check (require.js:866)
    at Module.<anonymous> (require.js:1113)
    at require.js:132
    at require.js:1156
    at each (require.js:57)
    at Module.emit (require.js:1155)
```

**Comment by dnadle** [comment]
That error implies that the js/customer-data constructor was called with null settings. Some kind of requirejs or config failure?

I have tried to work around this cart problem by overriding `Magento_Checkout/view/frontend/web/js/view/payment/default.js`, adding `Magento_Customer/js/customer-data` to the requirements, and adding the `invalidate` and `reload` lines to the `afterPlaceOrder` function. I don't appear to be getting any Javascript errors after checkout. (I also don't know if it's doing anything because I've never personally been able to reproduce the bug. We've had beta testers report it only once.)

**Comment by nntoan** [comment]
@dnadle That is what exactly I'm doing for my own troubles. Instead of insert new inline javascript to `success.phtml` or `noItems.phtml`, we need to add `Magento_Customer/js/customer-data` into the payment method renderer and inside `.done()` or `.always()`, we use this:

```
customerData.invalidate(['cart']);
```

Reload section may leads to some potential issue with cache (!)

**Comment by AntonEvers** [comment]
I think a more elegant solution is to invalidate sections the same way as in https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/view/frontend/web/js/customer-data.js#L346 and https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/view/frontend/web/js/customer-data.js#L368.

These invalidations work based on the sections.xml files in modules but they only apply to form submits and post|put|delete calls.
If we can add the visiting of the success page to that list it would be more in line with the current approach.

**Comment by erikhansen** [comment]
UPDATE 10/11/2017 - It appears that this fix actually did fix the issue. Disregard comment below.

I applied the contents of this patch to a Magento EE 2.1.5 site and pushed it to a server running in production mode. The fix only works intermittently, but for the majority of checkouts, the minicart still shows items on the checkout confirmation page. So I would say that this PR does NOT work and an alternative solution should be used, such as [the one that @ajpevers just suggested](https://github.com/magento/magento2/pull/5807#issuecomment-301803260).

**Comment by dnadle** [comment]
The actual placement of the order and redirect after success happens in payment/default.js, and there is an afterPlaceOrder callback method defined. I don't understand the resistance to putting the cache invalidation there rather than listening for a get on the success page.

**Comment by ishakhsuvarov** [comment]
@ajpevers Is this PR still valid? Internal tickets show it as fixed in the `develop` branch.

**Comment by AntonEvers** [comment]
@ishakhsuvarov close this PR please. I cannot reproduce this issue in the `develop` branch. You are right.

**Comment by diazwatson** [comment]
Anybody advise the status of this issue MAGETWO-52593?

**Comment by george-vlahakis** [comment]
I am also getting it on 2.1.7 CE

**Comment by systemsixtyfour** [comment]
It's not working on 2.1.7 EE

**Comment by GuidoHub** [comment]
Still not works on 2.1.8

**Comment by twistedatrocity** [comment]
These changes are not in 2.1.9 either.

**Comment by arnoudhgz** [comment]
Bug still exists in 2.1.10 EE

**Comment by winterk80** [comment]
Changes are not in 2.1.8 EE, bug still exists

**Pull request closed without merging**
