### PR TITLE
magento/magento2#: Add a new index for `cron_schedule` table

### LINKED ISSUE #29601: [Issue] magento/magento2#: Add a new index for `cron_schedule` table
This issue is automatically created based on existing pull request: magento/magento2#27391: magento/magento2#: Add a new index for `cron_schedule` table

---------

### Preconditions(*)

[Magento\Cron\Model\ResourceModel\Schedule::trySetJobStatusAtomic()](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Cron/Model/ResourceModel/Schedule.php#L37) executes an UPDATE SQL with an additional `status` parameter:

```
 UPDATE `cron_schedule` SET `status` = ? WHERE (schedule_id = ?) AND (status = ?) 
```

UPDATE is a hard query and New Relic report about this:

PR adds an additional index based on

- schedule_id
- status 

fields.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Expected Result: (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by atwixfirster**
### Description (*)

[Magento\Cron\Model\ResourceModel\Schedule::trySetJobStatusAtomic()](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Cron/Model/ResourceModel/Schedule.php#L37) executes an UPDATE SQL with an additional `status` parameter:

```
 UPDATE `cron_schedule` SET `status` = ? WHERE (schedule_id = ?) AND (status = ?) 
```

UPDATE is a hard query and New Relic report about this:

PR adds an additional index based on

- schedule_id
- status 

fields.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29601: magento/magento2#: Add a new index for `cron_schedule` table

### CODE REVIEW

**Comment by kandy** [comment]
Query that you show use "where" condition  on primary keys and so  should run  with a millisecond performance

See

```
mysql> UPDATE `cron_schedule` SET `status` = 'run' WHERE (schedule_id = 1153)  AND (status = 'pending');
Query OK, 1 row affected (0.02 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> DESC UPDATE `cron_schedule` SET `status` = 'pending' WHERE (schedule_id = 1)  AND (status = 'pending');
+----+-------------+---------------+------------+-------+---------------+---------+---------+-------+------+----------+-------------+
| id | select_type | table         | partitions | type  | possible_keys | key     | key_len | ref   | rows | filtered | Extra       |
+----+-------------+---------------+------------+-------+---------------+---------+---------+-------+------+----------+-------------+
|  1 | UPDATE      | cron_schedule | NULL       | range | PRIMARY       | PRIMARY | 4       | const |    1 |   100.00 | Using where |
+----+-------------+---------------+------------+-------+---------------+---------+---------+-------+------+----------+-------------+
1 row in set (0.00 sec)
```

Can you  add database version and  explain for this query ?

**Review by kandy — CHANGES_REQUESTED** [review]
Can you  add database version and  explain for this query ?

**Comment by atwixfirster** [comment]
> Can you add database version and explain for this query ?

Magento Cloud environment.

DB version = `10.0.38-MariaDB-1~jessie-wsrep`

`cron_schedule` contains ~15 000 records.

**Review by kandy — DISMISSED** [review]

**Comment by engcom-Alfa** [comment]
Hi @kandy . Could you put an appropriate label for test coverage?
Thanks!

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @atwixfirster . We have some problems with checkout to your branch.  Could you update it?
Thanks!

**Comment by atwixfirster** [comment]
> Hi @atwixfirster . We have some problems with checkout to your branch. Could you update it?
> Thanks!

**updated**

Thank you!

**Comment by atwixfirster** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Comment by engcom-Charlie** [comment]
Hi, @sidolov can you please review this PR?
Thank you.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8164](https://jira.corp.magento.com/browse/ENGCOM-8164) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

A  new index for `cron_schedule` table was successfully added and everything works as expected.

**Comment by hostep** [comment]
Before this gets merged, can somebody confirm that this won't conflict with https://github.com/magento/magento2/pull/28007 ?

**Comment by kandy** [comment]
I can confirm that it will conflict as it duplicate to #28007?

**Comment by ihor-sviziev** [comment]
@sidolov i believe this should be reverted in favor to https://github.com/magento/magento2/pull/28007 that does the same and was approved more than 2 weeks ago

**Pull request merged**
