### PR TITLE
26896 issue with only X product left for configurable products

### LINKED ISSUE #26896: Only X left Threshold is not working in configurable product
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Stores --> catalog --> inventory --> Stock options : Only X left Threshold= 3
### Expected result (*)

1.It is working with a simple product but not working with configurable product
stock-left

2. It is not working with the configurable product where stock is less than 2
stock-left-01

### Actual result (*)

1. In configurable product, if we have selected the size if it is less then 3 than it has to show quantity left

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

Fixed #26896 issue

### Fixed Issues (if relevant)

1. magento/magento2#26896: Only X left Threshold is not working in configurable product

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Usik2203. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Usik2203, here is your [new Magento instance](https://pr-27030.instances.magento-community.engineering).
Admin access: [https://pr-27030.instances.magento-community.engineering/admin_1391](https://pr-27030.instances.magento-community.engineering/admin_1391)
Login: `84adc1ae` Password: `bed1ad7e84ee`
Instance will be terminated in up to 3 hours.

**Comment by Usik2203** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Usik2203. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Usik2203, here is your [new Magento instance](https://pr-27030.instances.magento-community.engineering).
Admin access: [https://pr-27030.instances.magento-community.engineering/admin_aa47](https://pr-27030.instances.magento-community.engineering/admin_aa47)
Login: `65e898aa` Password: `b7f0e7ace8f8`
Instance will be terminated in up to 3 hours.

**Comment by Usik2203** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Usik2203. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Usik2203, here is your [new Magento instance](https://pr-27030.instances.magento-community.engineering).
Admin access: [https://pr-27030.instances.magento-community.engineering/admin_141d](https://pr-27030.instances.magento-community.engineering/admin_141d)
Login: `d4d8d09e` Password: `97471bfd52ed`
Instance will be terminated in up to 3 hours.

**Review by VladimirZaets — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7614](https://jira.corp.magento.com/browse/ENGCOM-7614) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @Usik2203 

During testing, we faced the issue.

**_Problem:_** Wrong alignment of items in the box on mobile (Luma theme)

**Actual Result:**
screenshot_33


And in the Blank theme, on the product page, the elements are always displayed

**Actual Result:**
screenshot_34
@VladimirZaets Is this the correct behavior?

@Usik2203 Could you take a look? 

Thanks!

**Comment by dmytro-ch** [comment]
Hi @Usik2203, I have to close this PR due to inactivity.
Please reopen and update if you wish to continue.
Thank you!

**Comment by engcom-Hotel** [comment]
Hello @Usik2203,
I will help with it.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento give me test instance

**Comment by engcom-Hotel** [comment]
This issue is fixed on MSI and it should be transferred to CE in the next minor release.

**Pull request closed without merging**
