### PR TITLE
Fixed 26469 issue with products position

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)
We have four products and we  are expecting that "Orange" must be first and "Banana" must be second
Screenshot 2020-02-19 at 10 30 43
Screenshot 2020-02-19 at 13 18 49
**Result Before FIX**
Screenshot 2020-02-19 at 13 18 22
**Result After FIX**
Screenshot 2020-02-19 at 13 21 34

 
### Fixed Issues (if relevant)

1. magento/magento2#26469 : New Product in the first position at the category product list

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Usik2203. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Usik2203, here is your [new Magento instance](https://pr-26927.instances.magento-community.engineering).
Admin access: [https://pr-26927.instances.magento-community.engineering/admin_63f4](https://pr-26927.instances.magento-community.engineering/admin_63f4)
Login: `0b2bc9aa` Password: `798714b4fb08`
Instance will be terminated in up to 3 hours.

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run all tests

**Pull request closed without merging**
