### PR TITLE
Fix wording of filter item on layered navigation

### LINKED ISSUE #38789: [Issue] Fix wording of filter item on layered navigation
This issue is automatically created based on existing pull request: magento/magento2#37852: Fix wording of filter item on layered navigation

---------

### Description (*)
The words `item` and `items` are incorrectly used in the layered navigation filter item.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by yogesh-valiya**
### Description (*)
The words `item` and `items` are incorrectly used in the layered navigation filter item.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38789: Fix wording of filter item on layered navigation

### CODE REVIEW

**Comment by yogesh-valiya** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Review by Den4ik — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
@magento create issue

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by engcom-Charlie** [comment]
Few test failures in recent 2 runs of functional B2B are different. Below 2 failures are constant in both the builds but these are the known issues.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37852/626cb629076b182295ded290aa873a2a/Functional/allure-report-b2b/index.html#categories/fcae19c49786395b97729f5a28dfab07/a6562602c85b49ed/
image

**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37852/9500b19ae8a3baf081af3e18fb11460b/Functional/allure-report-b2b/index.html#categories/e89a2ef77b192fa659586970627a6e4a/dd470d803b3cf64c/
image

Known Issues:
1. AdminReorderWithCatalogPriceRuleDiscountTest:  [ACQE-6523](https://jira.corp.adobe.com/browse/ACQE-6523)
2. StorefrontUpdateCustomerAddressBelgiumTest: [ACQE-6648](https://jira.corp.adobe.com/browse/ACQE-6648)

**Comment by engcom-Charlie** [comment]
Few test failures in recent 2 runs of functional EE are different. Below 2 failures are constant in both the builds but these are the known issues. Hence moving this PR to Merge in Progress.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37852/637586a93d6c47f9e43100b6012b9959/Functional/allure-report-ee/index.html#categories
image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37852/416043f374b5f8029ed4d74b7e125768/Functional/allure-report-ee/index.html#categories
image

Known Issues:
1. StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest: [ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331)
2. AdminReorderWithCatalogPriceRuleDiscountTest:  [ACQE-6523](https://jira.corp.adobe.com/browse/ACQE-6523)

**Pull request merged**
