### PR TITLE
Fix for save_rewrites_history flag for products bunch that contains m…

### PR DESCRIPTION
**Pull request by danilkrasnorudskyi**

### CODE REVIEW

**Comment by VladimirZaets** [comment]
Hi @danilkrasnorudskyi  , thanks for collaboration. Please, sign CLA, otherwise, we can't process your pull request. Also please provide a clear description for your PR

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @danilkrasnorudskyi , thanks for collaboration. Please, sign CLA, otherwise, we can't process your pull request. Also please provide a clear description for your PR

**Comment by engcom-Charlie** [comment]
Hi @danilkrasnorudskyi, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Comment by hostep** [comment]
@VladimirZaets: can we reopen this PR, or should we create a new one to move this forwards?

We can confirm that this fixes a bug where if you import more than 1 product and use the `save_rewrites_history` flag in the import data, that it does create 301 redirects if the product url changes.
When only importing one product, Magento already did the right thing, but not when importing more than 1 product.

Seen on Magento 2.3.6-p1

**Comment by hostep** [comment]
See https://github.com/magento/magento2/commit/af8d6f4736cb38d0ad619ad1e353700797063b4a#r38859984 for more explanation why this is needed.

**Comment by hostep** [comment]
New PR created: https://github.com/magento/magento2/pull/32640

**Pull request closed without merging**
