### PR TITLE
MFTF: Extract Action Groups to separate files - magento/module-reports

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Extract each Action Group to separate file, to follow MFTF Best Practices.

### Fixed Issues (if relevant)
1. magento/magento2#22853

### Questions or comments
Had to extract the changes per-module. The previous try failed, because of conflicts.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6359](https://jira.corp.magento.com/browse/ENGCOM-6359) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by ihor-sviziev** [comment]
@lbajsarowicz 
Maybe we can create some static test that will check if action group is one in file?

**Comment by lbajsarowicz** [comment]
@ihor-sviziev Definitely after cleaning up the mess that we already have - we should have such. This should also check if the filename corresponds with the only test name inside.

**Comment by ihor-sviziev** [comment]
@lbajsarowicz could you report an issue for that, just in order not to miss it

**Comment by lbajsarowicz** [comment]
Yes, I'll do it for both `magento2` repository and `magento-functional-tests-migration`

**Comment by ihor-sviziev** [comment]
Thank you!

**Comment by lbajsarowicz** [comment]
@VladimirZaets Could you explain why this Pull Request cannot be merged to 2.3? There are no backward incompatible changes.

**Pull request merged**
