### PR TITLE
24696 invalid input date time format

### LINKED ISSUE #24696: Invalid input datetime format of value in Others locale 2.3.2
### Preconditions (*)

1.Magento 2.3.2 & 2.3-develop
2.Japen or China locale in admin 
* Backend-> Admin -> change the Backend admin panel language to Chinese

### Steps to reproduce (*)

1.Create or edit product
2.Change date field for new from to anything
3.Click Save

### Expected result (*)

1. Product Saves with new from date

### Actual result (*)

1.Error occurs stating "Invalid input datetime format of value '2019/9/24'
image

If choose EN is working, but in others locale, like JP showing chinese will be error.

### Additional information
https://github.com/magento/magento2/issues/24696#issuecomment-534514561

> Not a local options,
> Please follow this step ;
> Backend-> Admin -> change the Backend admin panel language to Chinese (Taiwan,hongkong,China) or Japanese and then go to product > add or edit product > add a “special price or new product”date time, it will be showing “xxxx年xx月xx日” not a xxxx/xx/xx.

### PR DESCRIPTION
**Pull request by Digisha-97**
Invalid Date Time Format issue for other locale
parterres-contribution  Partner: CommercePundit

### Description (*)

Date Time format is working properly for US only but when we change it to China or any other locale. Its throwing error on products save when we are adding values for  **Set Product as New From**. 

Reason it is not changing date format according configured locale.

Currently added solution for it, so now when we will change locale from configuration it will work fine.

Changed the filter method, as here system is not getting proper value to change according to selected locale.

 `$value = $this->_localeDate->formatDateTime($value, \IntlDateFormatter::SHORT, \IntlDateFormatter::SHORT, $useCode, null, null);`

the value in filter method was not coming proper for other locale. so updated it as above. Also for China its returning  **zh_Hans_CN** but we need **zh_CN** for proper date format added same comment in file as well.

I have checked this fix on **Magento 2.3.2 and 2.3.3**

### Fixed Issues (if relevant)

1. fixes magento/magento2#24696: Invalid input datetime format of value in Others locale 2.3.2 #24696

### Manual testing scenarios (*)

1. Change locale to China from admin  > Stores > Configuration > General > Locale Options 
    here change **Locale** option to China 
    and change **Timezone** to China Standard Time (Asia/Shanghai)
2. On top right corner admin menu click on Account Settings(admin)
    here change **Interface Locale** to China 
3. Navigate to Catalog  > Products 
    Select any product to edit it
    here add value for **Set Product as New From** for product and click on Save button

### Questions or comments

This is my first contribution , so please let me know if I missed anything or any correction require from my  #side.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by slavvka** [comment]
@magento run all tests

**Comment by Digisha-97** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Digisha-97. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Digisha-97, here is your [new Magento instance](https://pr-25363.instances.magento-community.engineering).
Admin access: [https://pr-25363.instances.magento-community.engineering/admin](https://pr-25363.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by Digisha-97** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Digisha-97. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Digisha-97, here is your [Magento instance](https://i-25363-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25363-2-3-develop.instances.magento-community.engineering/admin](https://i-25363-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Digisha-97** [comment]
Hi ,

Applied solution is working on 
Admin access: https://pr-25363.instances.magento-community.engineering/admin
Login: admin Password: 123123q

Its not working on 
Admin access: https://i-25363-2-3-develop.instances.magento-community.engineering/admin
Login: admin Password: 123123q

so now what I need to do ?

**Comment by sidolov** [comment]
Closing as duplicate of https://github.com/magento/magento2/pull/25372

**Pull request closed without merging**
