### PR TITLE
check static test for inheritdoc 

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

check static test for inheritdoc for #22306 PR
https://github.com/magento/magento2/pull/22306
### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
Hi @ravi-chandra3197 thanks for the contribution. Why do you think it is a typographical error?

**Comment by ravi-chandra3197** [comment]
Hello @sivaschenko
Any suggestion?

**Comment by sivaschenko** [comment]
@ravi-chandra3197 no suggestions, I saw both variants of "eCommerce" here and there, so I'm not sure which one is correct. That's why I would like to know what is your variant based on.

**Comment by ravi-chandra3197** [comment]
Hello @sivaschenko 
can you review it.

**Comment by ravi-chandra3197** [comment]
Hello @sivaschenko
I have updated my code can review it.

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3711](https://jira.corp.magento.com/browse/ENGCOM-3711) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @ravi-chandra3197  thanks for your contribution! As I can see those corrections are already merged in https://github.com/magento/magento2/pull/19684, so closing as duplicate. Thanks.

**Pull request closed without merging**
