### PR TITLE
Code improvement

### PR DESCRIPTION
**Pull request by mage2pratik**
### Description
Code improvement as per coding standard

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios

N/A
### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by sidolov** [comment]
@magento-engcom-team combine 16818 16837 16826

**Comment by magento-engcom-team** [comment]
Hi @sidolov. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
@mage2pratik all pull requests have been successfully combined together: 
 - merged https://github.com/magento/magento2/pull/16818: Fixed a spelling mistake
 - merged https://github.com/magento/magento2/pull/16837: Removed space from return statement
 - merged https://github.com/magento/magento2/pull/16826: Removed unnecessary label tags

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.6. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
