### PR TITLE
Remove references to files from extjs which got removed in e1ccdb…

### LINKED ISSUE #38960: [Issue] Remove references to files from extjs which got removed in e1ccdb…
This issue is automatically created based on existing pull request: magento/magento2#38951: Remove references to files from extjs which got removed in e1ccdb…

---------
…83e7e312572038c476d0695300700db849

### Description (*)
While running Magento 2.4-develop locally, I noticed some errors both in my brower's console and the `var/log/system.log` file:

```
[2024-07-18T14:31:10.013255+00:00] main.ERROR: Compilation from source: LESS file is empty: adminhtml/Magento/backend/en_US/extjs/resources/css/ytheme-magento.less [] []
[2024-07-18T14:31:10.013254+00:00] main.ERROR: Compilation from source: LESS file is empty: adminhtml/Magento/backend/en_US/extjs/resources/css/ext-all.less [] []
```

After some searching around, it looks like the entire directory `lib/web/extjs` got removed in e1ccdb83e7e312572038c476d0695300700db849

It looks like @Atul-glo35265 didn't notice there were still references to some of those files in the codebase, which were still being used in the backoffice.

This PR cleans up those references.

The removal of the phtml file is because it also referenced extjs, so it would also no longer work, and it seems the file is not being used (at least not in Magento OS).
From [the commit message](https://github.com/magento/magento2/commit/698ab5c4ccc) that introduced the file, I think this may have been used in Adobe Commerce since they mention a Banner Rotation Widget, which doesn't exist in Magento OS. But since this commit is 9 years old, I have no idea if that still exists. And maybe it was also refactored recently in Adobe Commerce to no longer use the extjs files?
Maybe somebody with access to Adobe Commerce source code can double check this?

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
1. Open the backoffice
2. See if there are errors in your browsers console about trying to load css files from extjs
3. See in your `var/log/system.log` if there are errors about empty less files from extjs

### Questions or comments
Preferably, this PR should be included in whatever next Magento release (2.4.8?) together with the changes from e1ccdb83e7e312572038c476d0695300700db849

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by hostep**
…83e7e312572038c476d0695300700db849

### Description (*)
While running Magento 2.4-develop locally, I noticed some errors both in my brower's console and the `var/log/system.log` file:

```
[2024-07-18T14:31:10.013255+00:00] main.ERROR: Compilation from source: LESS file is empty: adminhtml/Magento/backend/en_US/extjs/resources/css/ytheme-magento.less [] []
[2024-07-18T14:31:10.013254+00:00] main.ERROR: Compilation from source: LESS file is empty: adminhtml/Magento/backend/en_US/extjs/resources/css/ext-all.less [] []
```

After some searching around, it looks like the entire directory `lib/web/extjs` got removed in e1ccdb83e7e312572038c476d0695300700db849

It looks like @Atul-glo35265 didn't notice there were still references to some of those files in the codebase, which were still being used in the backoffice.

This PR cleans up those references.

The removal of the phtml file is because it also referenced extjs, so it would also no longer work, and it seems the file is not being used (at least not in Magento OS).
From [the commit message](https://github.com/magento/magento2/commit/698ab5c4ccc) that introduced the file, I think this may have been used in Adobe Commerce since they mention a Banner Rotation Widget, which doesn't exist in Magento OS. But since this commit is 9 years old, I have no idea if that still exists. And maybe it was also refactored recently in Adobe Commerce to no longer use the extjs files?
Maybe somebody with access to Adobe Commerce source code can double check this?

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
1. Open the backoffice
2. See if there are errors in your browsers console about trying to load css files from extjs
3. See in your `var/log/system.log` if there are errors about empty less files from extjs

### Questions or comments
Preferably, this PR should be included in whatever next Magento release (2.4.8?) together with the changes from e1ccdb83e7e312572038c476d0695300700db849

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38960: Remove references to files from extjs which got removed in e1ccdb…

### CODE REVIEW

**Comment by hostep** [comment]
@magento run all tests

**Comment by hostep** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento create issue

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

**Review by engcom-Hotel — APPROVED** [review]
Thanks @hostep for the contribution!

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi @hostep,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**


- Open the backoffice
- See if there are errors in your browsers console about trying to load css files from extjs
- See in your var/log/system.log if there are errors about empty less files from extjs


**Before:** :heavy_multiplication_x: 


```
[2024-07-26T04:36:42.080133+00:00] main.CRITICAL: Compilation from source: LESS file is empty: adminhtml/Magento/backend/en_US/extjs/resources/css/ytheme-magento.less [] []
[2024-07-26T04:36:42.080143+00:00] main.CRITICAL: Compilation from source: LESS file is empty: adminhtml/Magento/backend/en_US/extjs/resources/css/ext-all.less [] []
```


Screenshot 2024-07-26 at 10 07 57



**After:** :heavy_check_mark: 


Screenshot 2024-07-26 at 10 15 32


There were no errors in `var/log/system.log` about empty less files from extjs.

Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Integration Tests, Unit Tests, Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
Failed **Functional B2B** failures in recent 2 builds are same and they are known issues. 

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38951/d3ba4fa571a1175eb56a5d7d8404e5a8/Functional/allure-report-b2b/index.html
image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38951/bb53943d0e44a3831b43688083144907/Functional/allure-report-b2b/index.html#categories/4a30a3b2be47054fe298171c561ed23f/ef1c838bdc8e02b1/
image

**Known issues in B2B:**
1. TierPricingWhenPriceScopeIsWebsiteWorkingProperlyWithMultipleCurrenciesConfiguredTest: [#ACQE-6695](https://jira.corp.adobe.com/browse/ACQE-6695)
2. StorefrontLoginFormCheckDuplicateValidateMessageTest: [#AC-12714](https://jira.corp.adobe.com/browse/AC-12714)

**Comment by engcom-Charlie** [comment]
Some failed **Functional CE** failures in recent 2 builds are same and they are known issues, one seems to be flaky.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38951/33feac4c2a3ead86ab8aa81f868161dc/Functional/allure-report-ce/index.html#categories
image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38951/a4d4f8b10a9a8347a59eb26187cc71c7/Functional/allure-report-ce/index.html#categories
image

**Known issues in CE:**
1. TierPricingWhenPriceScopeIsWebsiteWorkingProperlyWithMultipleCurrenciesConfiguredTest: [#ACQE-6695](https://jira.corp.adobe.com/browse/ACQE-6695)
2. StorefrontLoginFormCheckDuplicateValidateMessageTest: [#AC-12714](https://jira.corp.adobe.com/browse/AC-12714)

**Comment by engcom-Charlie** [comment]
Some failed **Functional EE** failures in recent 2 builds are same and they are known issues, one seems to be flaky. Hence moving to Merge in Progress.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38951/cd87085084e2da12e3ff6a1e47ec0a93/Functional/allure-report-ee/index.html#categories
image



**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38951/2201fb503e62604ea8979a0d65639e64/Functional/allure-report-ee/index.html#categories/f93a7a9b599d4febdcf8e4f426aebd1e/43e4a838674da0af/
image


**Known issues in EE:**
1. TierPricingWhenPriceScopeIsWebsiteWorkingProperlyWithMultipleCurrenciesConfiguredTest: [#ACQE-6695](https://jira.corp.adobe.com/browse/ACQE-6695)
2. StorefrontLoginFormCheckDuplicateValidateMessageTest: [#AC-12714](https://jira.corp.adobe.com/browse/AC-12714)
3.  StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest: [#ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331)

**Pull request merged**
