### PR TITLE
Fix fetching quote item by id

### PR DESCRIPTION
**Pull request by mladenilic**
### Description
Quote item without id (not yet saved) can be added to the collection. Even after being saved, it's still not possible to fetch it `$this->getItemsCollection()->getItemById($itemId);` as it was added before having the id.

### Fixed Issues
1. magento/magento2#9445: Cart 860 does not contain item 1204

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=10059) <br/>All committers have signed the CLA.

**Comment by okorshenko** [comment]
Hi @mladenilic 
Thank you for your contribution. Could you please cover you fix with integration test so that we can analyze the use case?

**Comment by okorshenko** [comment]
Hi @mladenilic.  Could you please cover you fix with integration test so that we can analyze the use case and proceed with PR acceptance? Thank you

**Comment by mladenilic** [comment]
@okorshenko: Sure! Sorry, for not covering the change with the test initially.

I'll make sure I add the integration test later today.

Best,
Mladen

**Pull request merged**
