### PR TITLE
Backport of MAGETWO-59256 for 2.1: Custom composer modules break Component Manager #6718

### PR DESCRIPTION
**Pull request by JTimNolan**
### Description
Backport of issue MAGETWO-59256 for 2.1
Cherry picked commits from develop, rebased, and squashed. Then removed some code from farther up the branch to make compatible with 2.1
First time making a PR for this so if I need to make changes/fix let me know.

Commits from the develop branch:
- https://github.com/magento/magento2/commit/fc99447f6aa1abfc1003f4181cea916c1616ea9e
- https://github.com/magento/magento2/commit/a9697c672e371f4484bb6ab0307d59bc346e8625
- https://github.com/magento/magento2/commit/7352b7cc7616b4b0de0ee3109983ec64abb7ccd8
- https://github.com/magento/magento2/commit/e8712764a918c0814c789b57d892963ac63305c5
- https://github.com/magento/magento2/commit/01f1f42b2431c8ce0b23c260a1af0261c02cb81c
- https://github.com/magento/magento2/commit/e072d65045ce8a3063ce07a164a06f7d3c09b0ac

### Fixed Issues (if relevant)
1. magento/magento2#6718: Custom composer modules break Component Manager

### Manual testing scenarios
1. Ensure Magento Marketplace keys have been added to system manager
2. Require a module with composer (I used semaio/magento2-configimportexport)
3. Go to /setup/index.php#/component-grid
4. AJAX request to /setup/index.php/componentGrid/components no longer has an error

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=9692) <br/>All committers have signed the CLA.

**Comment by JTimNolan** [comment]
@shiftedreality Could you take a look at this? In reference to #6718 which you closed.

**Comment by shiftedreality** [comment]
@JTimNolan thanks for pointing this.
Assigned to Community Engineering member for PR proessing

**Comment by JTimNolan** [comment]
@shiftedreality @maghamed Do we have an ETA for this?

**Pull request merged**
