### PR TITLE
[32018] Marked GraphQl, ImportExport, Indexer, Integration and LoginAsCustomer interfaces as API

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixes https://github.com/magento/magento2/issues/32018
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/32018

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run WebAPI Tests, Integration Tests, Functional Tests EE, Functional Tests B2B

**Review by eduard13 — CHANGES_REQUESTED** [review]
@Usik2203 we should mark `\Magento\Indexer\Model\DimensionModes` as `api` as well. Could you please implement these changes?

**Comment by eduard13** [comment]
@magento run Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@Usik2203 please mark the `Magento\Framework\App\HttpRequestInterface` as well, as it's being used in `\Magento\Indexer\Model\DimensionModes` model.

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run WebAPI Tests

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8827](https://jira.corp.magento.com/browse/ENGCOM-8827) has been created to process this Pull Request

**Comment by gabrieldagama** [comment]
Closed in favour of https://github.com/magento/magento2/pull/32727

**Pull request closed without merging**
