### PR TITLE
magento/partners-magento2ce#31112: Customer Order Totals missing gift…

### LINKED ISSUE #31112: [GraphQL] Customer Order Totals missing gift card amount
During PWA development, it was discovered that gift card amounts are missing from the order total responses. This leads to us having to render an order total of $0 with no real explanation why. If it followed the same structure as the cart, we would maybe find a new gift_cards field instead, not sure how it would need structured since it's somewhat treated like a payment method.

Repro:
1. Create an account, login, place an order and pay with a gift card (gift card covers entire order)
1. Makes a customer query for customer.orders.items.total

Expected: total_giftcard field available
 Actual: No gift card related fields are available

Reproducible:

Yes, the issue can be observed when doing a `customer` GraphQL request. We hope to display something similar to our cart view, where we have access to a field like [applied*gift*cards](https://devdocs.magento.com/guides/v2.4/graphql/queries/cart.html#AppliedGiftCard).

image

### PR DESCRIPTION
**Pull request by sasha19957099**
### Description (*)

Added order model to resolve the total gift card amount for this order

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/440

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/31112

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sasha19957099** [comment]
@magento run all tests

**Review by cpartica — APPROVED** [review]

**Comment by dthampy** [comment]
@sasha19957099 , I have a question regarding what we expect to be returned as part of the  customer.orders. items. total.
Right now, in Luma , when you query for the customer's order, it shows applied gift card as a line item .
image
However, I don't see a way to get the applied gift card on the order via grapQl.  Let me know if I am missing something.
I used the below query : Since I couldn't find "applied_gift_card" field , without which how do we show the applied gift card amount in the order.items.total?
`{
     customer {
       email
       orders(filter:{number:{eq:"000000001"}}) {
        
         total_count
         items {
           id
           number
           order_date
           status
           items{product_name product_sku quantity_ordered discounts {amount{value currency} label}}
           total {
             base_grand_total{value currency}
             grand_total{value currency}             
             total_tax{value}
             subtotal { value currency }
            # taxes {amount{value currency} title rate}
            # discounts {amount{value currency} label}
             total_shipping{value}
             shipping_handling
             {
               amount_including_tax{value}
               amount_excluding_tax{value}
               total_amount{value currency}
              # taxes {amount{value} title rate}
              # discounts {amount{value currency}}
            }      }     }        }      }    }`

**Comment by sasha19957099** [comment]
@dthampy please see https://github.com/magento/partners-magento2ee/pull/440 
I've added a field order.items.total.total_giftcard.

**Comment by maddumarala** [comment]
Seems like same issue happening to Customer invoice totals.

**Pull request merged**
