### PR TITLE
MFTF: Newsletter Guest Subscription With Disallowed Option Test

### LINKED ISSUE #29039: [Issue] MFTF: Newsletter Guest Subscription With Disallowed Option Test
This issue is automatically created based on existing pull request: magento/magento2#28872: MFTF: Newsletter Guest Subscription With Disallowed Option Test

---------
This PR contains MFTF test for guest newsletter subscription with disallowed option in configs
**Deprecated** `VerifyRegistredLinkDisplayedForGuestSubscriptionNoTest` due to inconsistency with the best practices
**Deprecated** `StorefrontCreateNewSubscriberActionGroup` due to inconsistency with the best practices

### Preconditions (*)
Magento 2.4-develop

### Steps to reproduce (*)
1 - Disallow guest subscription in configs
2 - Subscribe as guest on storefront
3 - Perform assertions

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

### PR DESCRIPTION
**Pull request by DmitryTsymbal**
This PR contains MFTF test for guest newsletter subscription with disallowed option in configs
**Deprecated** `VerifyRegistredLinkDisplayedForGuestSubscriptionNoTest` due to inconsistency with the best practices
**Deprecated** `StorefrontCreateNewSubscriberActionGroup` due to inconsistency with the best practices

**Steps to reproduce:**
1 - Disallow guest subscription in configs
2 - Subscribe as guest on storefront
3 - Perform assertions

### Resolved issues:
1. [x] resolves magento/magento2#29039: MFTF: Newsletter Guest Subscription With Disallowed Option Test

### CODE REVIEW

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7739](https://jira.corp.magento.com/browse/ENGCOM-7739) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by dmytro-ch** [comment]
@magento run all tests

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7739](https://jira.corp.magento.com/browse/ENGCOM-7739) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
**Notice:** QA not applicable

**Comment by engcom-Delta** [comment]
@magento create issue

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Pull request merged**
