### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
UI Components are not easy to use - for an intro see http://alanstorm.com/magento_2_introducing_ui_components

### CODE REVIEW

**Comment by paales** [comment]
😂

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Update-README-md/idi-p/45013).

**Comment by vasiliyseleznev** [comment]
Hi @fooman,

Thanks for pointing to this. Words "easily", "simply", "basically" etc are in a list to avoid in technical documentation. Your PR will be accepted.

Thanks!
Vasiliy

**Comment by vasiliyseleznev** [comment]
Internal ticket: MAGETWO-59866

**Comment by Ctucker9233** [comment]
@mmansoorebay Will this PR be included in 2.1.3?

**Pull request merged**
