### PR TITLE
Shipping method values becomes zero when apply a cart price rule in checkout

### LINKED ISSUE #21832: Shipping method values becomes zero when apply a cart price rule in checkout
### Preconditions (*)
1. Magento 2.2.5

### Steps to reproduce (*)
1. Enable Free shipping, table rates and flat rates from admin->configurations ->shipping methods.
1. Create a Cart price rule to discount a specific shipping amount.
Marketing -> Cart price rule.

https://user-images.githubusercontent.com/34059011/54592574-abb43b00-4a52-11e9-8f32-5b32957a377a.png
https://user-images.githubusercontent.com/34059011/54592624-c71f4600-4a52-11e9-8b64-59ba1070725a.png
https://user-images.githubusercontent.com/34059011/54592662-dbfbd980-4a52-11e9-9f2c-d17e24ee6cc9.png
https://user-images.githubusercontent.com/34059011/54592686-e61dd800-4a52-11e9-9776-65881fabdd3c.png

1. Apply the discount code by selecting the flat rate from the checkout shipping methods
1. Go to home page and come back to the checkout page

### Expected result (*)
1. After going to the homepage and come to Checkout flat rate shipping method should be 0 but table rate shipping method should be a value set in the table rate matrix.

### Actual result (*)
1. After going to the homepage and come to Checkout flat rate shipping method is 0 and table rate shipping method also became 0 .
https://user-images.githubusercontent.com/34059011/54593111-c89d3e00-4a53-11e9-84de-a475f6597a3e.png

### PR DESCRIPTION
**Pull request by zakdma**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/21832

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by zakdma** [comment]
@magento run all tests

**Comment by zakdma** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by zakdma** [comment]
@magento run Functional Tests B2B

**Comment by zakdma** [comment]
@magento run Functional Tests B2B

**Comment by zakdma** [comment]
@magento run Functional Tests B2B

**Comment by zakdma** [comment]
@magento run Functional Tests B2B

**Comment by zakdma** [comment]
@magento run Functional Tests B2B

**Comment by zakdma** [comment]
@magento run Functional Tests B2B

**Comment by zakdma** [comment]
@magento run Functional Tests B2B

**Comment by aleron75** [comment]
@magento give me test instance

**Comment by aleron75** [comment]
I tested the scenario and the issue appears solved with the submitted code.

image

**Review by aleron75 — APPROVED** [review]
Thank you @zakdma for your contribution!

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-9096](https://jira.corp.magento.com/browse/ENGCOM-9096) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-33058`.

**Comment by dmitriyprime** [comment]
:heavy_check_mark: QA passed

**Before:**
before

**After:**
after

**Pull request merged**
