### PR TITLE
Updated composer dependencies

### LINKED ISSUE #34533: Add fixes to make `elasticsearch/elasticsearch` composer dependency compatible with PHP 8.1
### Description (*)
Some problems have been found in `elasticsearch/elasticsearch` composer dependency during work on the adding a compatibility Magento with PHP 8.1.
We need to deliver our changes to extension repository via making PR [there](https://github.com/elastic/elasticsearch-php).

### LINKED ISSUE #34591: Add fixes to make `fgrosse/phpasn1` composer dependency compatible with PHP 8.1
### Description (*)
Some problems have been found in `fgrosse/phpasn1` composer dependency during work on the adding a compatibility Magento with PHP 8.1.
We need to deliver our changes to extension repository via making PR [there](https://github.com/FGrosse/PHPASN1).

### LINKED ISSUE #34751: Make aws-sdk-php compatible with PHP8.1
aws-sdk-php is a magento dependency that needs to be updated to be compatible with PHP8.1

This will unblock PHP8.1 support in Magento

Problematic places:
```java
/var/www/html/vendor/aws/aws-sdk-php/src/ResultPaginator.php:104
/var/www/html/vendor/aws/aws-sdk-php/src/ResultPaginator.php:109
/var/www/html/vendor/aws/aws-sdk-php/src/ResultPaginator.php:114
/var/www/html/vendor/aws/aws-sdk-php/src/ResultPaginator.php:119
/var/www/html/vendor/aws/aws-sdk-php/src/ResultPaginator.php:137
```

### PR DESCRIPTION
**Pull request by karyna-t**
### Description (*)

This pull request (PR) provides the update of the released composer dependencies to the latest versions
- updated restriction for `elasticsearch/elasticsearch` to latest version
- updated `aws/aws-sdk-php`
- updated `fgrosse/phpasn1`
- updated all composer dependencies using `composer update`

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/667

### Fixed Issues (if relevant)

1. Fixes magento/magento2#34751
1. Fixes magento/magento2#34533 
1. Fixes magento/magento2#34591

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by andrewbess — APPROVED** [review]
Hello @karyna-tsymbal-atwix 
Thank you for your contribution here and 3rd-party extension
Great work ✔️

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, thank you for the review.
[ENGCOM-9364](https://jira.corp.magento.com/browse/ENGCOM-9364) has been created to process this Pull Request
:eight_spoked_asterisk: @andrewbess, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by xmav** [comment]
pending delivery https://github.com/magento-commerce/magento2ce/pull/7303

**Pull request merged**
