### PR TITLE
Fixed regex for validate action in admin menu

### PR DESCRIPTION
**Pull request by diegocpires**
### Description (*)
Validator for action menu doesn't accept "-".

### Fixed Issues (if relevant)

1. magento/magento2#25635: Bug when create a new admin route wirh hyphen

### Manual testing scenarios (*)

1. Create a new route for Admin with "-"
2. Create a new menu for Admin with "-" in action.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by diegocpires** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @diegocpires. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @diegocpires, here is your [new Magento instance](https://pr-25612.instances.magento-community.engineering).
Admin access: [https://pr-25612.instances.magento-community.engineering/admin](https://pr-25612.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by GDauer** [comment]
@magento give me 2.3 instance

**Review by rodrigowebjump — APPROVED** [review]
Hi @diegocpires 

Thanks for your contribution

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-6347](https://jira.corp.magento.com/browse/ENGCOM-6347) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@diegocpires thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
