### PR TITLE
Category filters - Fix notice on incorrect price param

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
See details in #25911 

### Fixed Issues (if relevant)
1. magento/magento2#25911 : Category - Notice on incorrect price filter GET param

### Manual testing scenarios (*)
1. See details in #25911 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by krzksz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-6424](https://jira.corp.magento.com/browse/ENGCOM-6424) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
Hello @ihor-sviziev. Thank You for Your contribution. Would You please take a look at the following gif:
category
The system.log also does not contain any main.criticals. So it is that ether the issue this PR is going to fix is not reproduced on 2.4-develop or we miss or misunderstand something when trying to reproduce it. If the true one is the second please help us to reproduce it. Thank You.

**Comment by engcom-Bravo** [comment]
@ihor-sviziev, we have immediately found the cause we were not able to reproduce the issue. In order to have it reproduced "for instance https://example.com/my-category/?price=-100%27[0]" should be replaced with "for instance https://example.com/my-category?price=-100%27[0]" - the "/" before the ? should be removed. I believe in 2.3 version Your reported the issue on it was reproduced with that slash, but as far as I remember there was a commit that brought some changes to category url behavior depending on presence of such a slash in it. So probably that is the reason the issue needs now to have category url be without slash before request part (before ?) in order to get reproduced. So we are proceeding with testing Your PR.

**Comment by engcom-Bravo** [comment]
@ihor-sviziev, everyting works fine, sorry for disturbing You. :heavy_check_mark: QA Passed.

**Comment by MTheProgrammer** [comment]
Hello, this is still an issue in Magento 2.4.2:
```
[2021-08-17 02:41:49] main.CRITICAL: Warning: A non-numeric value encountered in XXXX/vendor/magento/module-catalog-search/Model/Layer/Filter/Price.php on line 194 [] []
```

Type in the url non-numeric value for the price filter:
```https://magento.domain/category.html?price=c-d```

**Comment by ihor-sviziev** [comment]
@magento give me 2.4-develop instance

**Comment by ihor-sviziev** [comment]
Hi @MTheProgrammer,
I can't reproduce the issue on the 2.4-develop issue both on the test instance and on the local machine.
If you are still able to reproduce it - please create a separate issue with steps to reproduce.
Thank you!

**Pull request merged**
