### PR TITLE
[Backport] Make State/Province required field in checkout view based on settings

### PR DESCRIPTION
**Pull request by Igloczek**
It's the backport of changes present on `develop` branch, to fix issues described in #9077 also on 2.1.x.

Related commits and issues:
- https://github.com/magento/magento2/commit/1b4ba9f9f071bfc539602fe2da399ad0a235b232
- https://github.com/magento/magento2/commit/4f2fa65f990edc196ca4314d6e0a5dbd832fbca6
- https://github.com/magento/magento2/issues/5279
- https://github.com/magento/magento2/issues/2946

### CODE REVIEW

**Comment by orlangur** [comment]
Will this cover https://github.com/magento/magento2/issues/10897 case?

**Comment by Igloczek** [comment]
@orlangur Yup, it will cover this case too.

**Comment by vrann** [comment]
@Igloczek thank you for the backport!
We notice one issue which still has to be resolved: when the State/Province is a required field, it is validated on PHP side, but the frontend does not display it as a required for the countries other than USA (i.e. India).

This is how it looks like on 2.1 after the fix:
susp-03

This is how it looks like on develop
develop

**Comment by Igloczek** [comment]
To be completely honest with you, I'm afraid that it has to be merged in the current state or rejected, because I don't have time to investigate, especially while we have 2.2 up and backport isn't a crucial thing, because users can just make an upgrade.

**Comment by ishakhsuvarov** [comment]
@Igloczek I am closing this now per your comment.
Please reopen if you feel like continuing with this one in the future.

**Pull request closed without merging**
