### PR TITLE
30924 billing address parameter same as shipping cause error

### LINKED ISSUE #30924: Billing address parameter 'same_as_shipping' cause error 'The shipping method is missing'
### Issue

Error after place order: The shipping method is missing. Select the shipping method and try again
### Steps to reproduce
1. Logged in customer
1. Run mutations setShippingAddressesOnCart and setShippingMethodsOnCart
1. Check database table `quote_address` - shipping method is selected for quote address
1. Run mutation setBillingAddressOnCart with `same*as*shipping = true`
1. Check shipping method - shipping method is not selected now

### Reason for issue

I think we have an issue in logic after these changes
 [Replace use*for_shipping with same_as*shipping](https://github.com/magento/graphql-ce/issues/903)

It can not be a simple rename - `use*for_shipping` to `same_as*shipping` as we have in this commit <https://github.com/magento/magento2/commit/bb25f9a9809cd08573f71adefaf18ddcdeec9197>
 because these options have a different logic:
 - `use*for*shipping` - set **shipping* address *based on billing** address
 - `same*as*shipping` - set **billing* address *based on shipping** address

Class [Magento\QuoteGraphQl\Model\Cart\SetBillingAddressOnCart](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/QuoteGraphQl/Model/Cart/SetBillingAddressOnCart.php#L81)
 `
 $this->assignBillingAddressToCart->execute($cart, $billingAddress, $sameAsShipping);
 `

finally, it calls a function `assign($cartId, \Magento\Quote\Api\Data\AddressInterface $address, $useForShipping = false) `in class [Magento\Quote\Model\BillingAddressManagement ](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Quote/Model/BillingAddressManagement.php#L75)which waiting for `use*for_shipping` parameter instead of `same_as*shipping`

*The implementation needs to be updated to reflect this change in logic for the GraphQL call. The logic should now ignore the passed address if `same_as_shipping` is `true` and use the shipping address instead.* ** 
### Possible fixes

I can see 2 variants of how we can resolve it:

**Variant 1**
 We can remove `same*as_shipping` from [GraphQl schema](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L106) as it does not make sense for backend logic - we do not have a field in database table `quote*address` for this option. 
 We have the field `same*as_billing` in `quote*address` table (we use it when we place an order from the admin panel and fill the billing address first).
 So, the checkbox on checkout 'My billing and shipping address are the same' will be used only for frontend logic in javascript (as on standard checkout on Luma theme) and do not use in mutation.
 `use*for*shipping` can be removerd from [GraphQl schema](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/QuoteGraphQl/etc/schema.graphqls#L105) too.

**Variant 2**
 Add logic for `same*as_shipping` on the backend side. In this case, we should do `billing_address` in `setBillingAddressOnCart` mutation as not required when we set `same_as_shipping=true` as it does not make sense. We will check `same_as*shipping` in resolver and if it's "true" - load shipping address from the quote and save to billing address.

As for me, variant 1 is a more correct way.
### Acceptance Criteria
* The implementation for the `setBillingAddressToCart` mutation is updated to correctly use the `same*as*shipping` input correctly: to set the billing address to match the shipping address, not vice versa.
* All existing non-GraphQL flows (admin order checkout, REST calls, etc) are not impacted
* The new implementation does not have the reported bug of a missing shipping method after execution (this should be eliminated as a consequence of refactoring the implementation)

### Test Plan
* Use input billing address
 **Input**: valid billing address, `same*as*shipping` = `false`
 **Expected Result**: billing address is set to input address

* Use shipping address
 **Input**: empty billing address, `same*as*shipping` = `true`
 **Expected Result**: billing address matches shipping address

* Use shipping address, ignore input billing address
 **Input**: valid billing address, `same*as*shipping` = `true`
 **Expected Result**: billing address matches shipping address

* No provided address
 **Input**: empty billing address, `same*as*shipping` = `false`
 **Expected Result**: GraphQlInputException

* No existing shipping address
 **Input**: any billing address, `same*as*shipping` = `true` and no existing shipping address
 **Expected Result**: GraphQlInputException

### PR DESCRIPTION
**Pull request by chiranjeevi-cj**
### Description (*)

1. Before removing the shipping address I assign the shipping method to the billing address. 
2. So that shipping address will be removed from the database but the shipping method won't.

`$address = $address->setShippingMethod($quote->getShippingAddress()->getShippingMethod());`

### Fixed Issues (if relevant)
1. Fixes magento/magento2#30924

### Manual testing scenarios (*)
1. Run setShippingAddressesOnCart mutation.

mutation {
  setShippingAddressesOnCart(
    input: {
      cart_id: "zovZapgQN7fyRpAiL7rmga8w3tliC80S"
      shipping_addresses: [
        {
          address: {
            firstname: "Bob"
            lastname: "Roll"
            company: "cj Magento"
            street: ["Shipping Address", "Main Street"]
            city: "Austin"
            region: "TX"
            postcode: "78758"
            country_code: "US"
            telephone: "8675309"
            save_in_address_book: false
          },
          pickup_location_code: "",         
        }
      ]     
    }
  ) {
    cart { ....}}
}

2. Run setShippingMethodsOnCart mutation.

mutation {
  setShippingMethodsOnCart(
    input: {
      cart_id: "zovZapgQN7fyRpAiL7rmga8w3tliC80S",
      shipping_methods: [
        {
          carrier_code: "flatrate"
          method_code: "flatrate"
        }
      ]
    }
  ) {cart { ... }}
}

3. Run setBillingAddressOnCart mutation with setting same_as_shipping attribute to true.

mutation {
  setBillingAddressOnCart(
    input: {
      cart_id: "zovZapgQN7fyRpAiL7rmga8w3tliC80S"
      billing_address: {
        address: {
          firstname: "Bob"
          lastname: "Roll"
          company: "Magento"
          street: ["Billing Address", "Main Street"]
          city: "Austin"
          region: "TX"
          postcode: "78758"
          country_code: "US"
          telephone: "8675309"
          save_in_address_book: true
        }
        same_as_shipping: true
      }
    }
  ) {
    cart { ... }}
}

### Database screen shot

Screenshot from 2020-11-25 19-41-09

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by chiranjeevi-cj** [comment]
@magento run all tests

**Comment by chiranjeevi-cj** [comment]
@magento run all tests

**Comment by chiranjeevi-cj** [comment]
@magento run all tests

**Comment by chiranjeevi-cj** [comment]
@magento run all tests

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @chiranjeevi-cj. Thank you for your collaboration. Let's reflect on this topic a bit. The main idea of same_as_shipping flag is to set both billing and shipping addresses using `SetBillingAddressOnCart` mutation. 

I believe the problem is not in the GraphQl logic but in Quote module domain logic. If we take a look at the following implementation

https://github.com/magento/magento2/blob/e60d3a2d8ff3964510ecaa0f7617fa9e482236c4/app/code/Magento/Quote/Model/ShippingAddressAssignment.php#L45

We see that the previous shipping address is being removed if the flag set. As the result, the shipping method might be removed as well. 

I would suggest adjusting the Quote module logic for having a possibility to set both addresses using one mutation (performance-wise feature) instead of removing this feature completely. 

Thanks

**Comment by chiranjeevi-cj** [comment]
@magento run all tests

**Comment by chiranjeevi-cj** [comment]
@rogyar Can you assist me to resolve those failures?

**Comment by rogyar** [comment]
Hi @chiranjeevi-cj. Most of the failing tests are not related to your changes. However, removing the line of code that is responsible of deleting the address is not an optimal solution. The main reason of that, every time we have the 'same_as_shipping' flag set, we have an extra address record in the database, which is redundant. Ideally, we should assign the previously selected shipping method to the billing address somehow.

**Comment by chiranjeevi-cj** [comment]
@rogyar Thanks for your heads up. Changed my logic. Before removing the shipping address I assign the shipping method to the billing address. So that shipping address will be removed from the database but the shipping method won't. 

`$address = $address->setShippingMethod($quote->getShippingAddress()->getShippingMethod());`.

Can you please review my code and let us know if anything needs an update. 
Thank you.

**Comment by chiranjeevi-cj** [comment]
@magento run all tests

**Comment by chiranjeevi-cj** [comment]
@magento run all tests

**Comment by rogyar** [comment]
Hi @chiranjeevi-cj. Looks much better, thanks. Could you, please, take a look at the failing unit tests (other failing tests are not related to your change)? 
Also, according to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html), all changes should be covered by auto-tests. Could I ask you to extend any of the existing API-functional tests, please (this one for example https://github.com/magento/magento2/blob/f4db7d458884bcfc3d21b35b41f4fbe8e91bcb0f/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/SetBillingAddressOnCartTest.php#L17).

Thanks.

**Comment by chiranjeevi-cj** [comment]
@magento run all tests

**Comment by chiranjeevi-cj** [comment]
@magento run all tests

**Comment by chiranjeevi-cj** [comment]
@magento run all tests

**Comment by chiranjeevi-cj** [comment]
@magento run all tests

**Comment by chiranjeevi-cj** [comment]
@magento run all tests

**Comment by chiranjeevi-cj** [comment]
@magento stop all tests

**Comment by chiranjeevi-cj** [comment]
@magento run all tests

**Comment by chiranjeevi-cj** [comment]
@magento run all tests

**Comment by chiranjeevi-cj** [comment]
Hello @rogyar, I have written tests for code I changed and updated the PR. Can you please verify it?
Thank you.

**Comment by rogyar** [comment]
Hi @chiranjeevi-cj. Good job!

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8523](https://jira.corp.magento.com/browse/ENGCOM-8523) has been created to process this Pull Request
:eight_spoked_asterisk: @rogyar, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Alfa** [comment]
Hi @chiranjeevi-cj & @rogyar Thanks for your contribution and collaboration here!

I tried to test the issue by taking PR code changes into my Magento `2.4-dev` code, and below are the steps I followed.

1. With the GraphQL Requests, got the customer token and followed by created a empty cart, and then added a product to the cart using GraphQL requests only.
2. Set the shipping address using the mutation: `mutation {
  setShippingAddressesOnCart(
    input: {
      cart_id: "{{CustomerCart}}"
      shipping_addresses: [
        {
          address: {
            firstname: "Bob1"
            lastname: "Roll1"
            company: "Magento"
            street: ["Magento Pkwy", "Main Street"]
            city: "Austin"
            region: "TX"
            postcode: "78758"
            country_code: "US"
            telephone: "8675309"
            save_in_address_book: false
          }
        }
      ]
    }
  ) {
    cart {
      shipping_addresses {
        firstname
        lastname
        company
        street
        city
        region {
          code
          label
        }
        postcode
        telephone
        country {
          code
          label
        }
      }
    }
  }
}
`
3. Set the shipping method using the mutation: `mutation {
  setShippingMethodsOnCart(
    input: {
      cart_id: "{{CustomerCart}}",
      shipping_methods: [
        {
          carrier_code: "flatrate"
          method_code: "flatrate"
        }
      ]
    }
  ) {
    cart {
      shipping_addresses {
        selected_shipping_method {
          carrier_code
          carrier_title
          method_code
          method_title
          amount {
            value
            currency
          }
        }
      }
    }
  }
}
`
4. Set the billing address using the mutation: `mutation {
  setBillingAddressOnCart(
    input: {
      cart_id: "{{CustomerCart}}"
      billing_address: {
        address: {
          firstname: "Bob1"
          lastname: "Roll1"
          company: "Magento"
          street: ["Magento Pkwy", "Main Street"]
          city: "Austin"
          region: "TX"
          postcode: "78758"
          country_code: "US"
          telephone: "8675309"
          save_in_address_book: true
        }
        same_as_shipping: true
      }
    }
  ) {
    cart {
      billing_address {
        firstname
        lastname
        company
        street
        city
        region{
          code
          label
        }
        postcode
        telephone
        country{
          code
          label
        }
      }
    }
  }
}
` where _same_as_shipping:_ set to _true_ only!
5. Opened the table `quote_address` from the database and checked the `same_as_billing` column if it has set to 1. 
     image




**Observation:** Even after taking this PR file changes, still noticed the value set to **0** only. In fact, after taking PR changes, I created a new customer and followed all the above steps. Still found the same issue.

1. Since the issue is still noticeable, I am currently moving this to On Hold, and kindly request you to take a look on this again please. If you are going to update the code, once after updating, please inform here in the comment section, and request for review.
2. Also make sure all the auto-test jobs are getting passed please.
3. In case, my understanding is wrong in terms of reproducing the issue, kindly guide me to correct it. So that i will re-check.

Thanks in advance!

**Comment by ishakhsuvarov** [comment]
Unfortunately it looks like this PR has not seen any updates after a failed manual verification. I am closing this for now due to inactivity.

Please feel free to reopen if you wish to continue

**Pull request closed without merging**
