### PR TITLE
magento/magento2#?: Mark not used downloadable blocks, tests, layout updates and templates as deprecated.

### PR DESCRIPTION
**Pull request by swnsma**
### Description (*)
Investigated and mark as deprecated blocks, layout updates, templates.
Mark as deprecated corresponding unit and integration tests. 

### Fixed Issues (if relevant)

1. No corresponding issue.

### Manual testing scenarios (*)

1. Crash or delete any file from pull request (brake xml or php code).
2. Visit Product Edit Page in Admin panel.
#### Expected result
1. Page crashed or downloadable setting tab is missing.
#### Actual result
1. Changes have no effect.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @swnsma. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — APPROVED** [review]

**Comment by orlangur** [comment]
QA note: please run as much automated tests as possible with all the deprecated files from this PR removed.

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3705](https://jira.corp.magento.com/browse/ENGCOM-3705) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @swnsma thanks for your contribution, should `\Magento\Downloadable\Controller\Adminhtml\Downloadable\Product\Edit\Form` be marked as deprecated as well? Since it depends on `Magento\Downloadable\Block\Adminhtml\Catalog\Product\Edit\Tab\Downloadable`

**Comment by swnsma** [comment]
Hi @sivaschenko,
Thank you for your review!
Yes indeed.
I have also marked this class as deprecated.

P.S. will check product controllers more properly in future, look like there are also some legacy:)

**Comment by magento-engcom-team** [comment]
Hi @swnsma. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
