### PR TITLE
Fix default_sort_by attribute type

### PR DESCRIPTION
**Pull request by tkotosz**
### Description (*)
The default_sort_by attribute of the category entity handled as singe value (string) everywhere but expected as an array in the Category API. Because of this issue default_sort_by cannot be set/updated for categories through the Magento REST API.

If you provide it as string then it fails with the following error:
```
Error occurred during "custom_attributes" processing. Attribute "default_sort_by" has invalid value. The "string" value's type is invalid. The "string[]" type was expected. Verify and try again.
```

If you provide it as an array containing 1 string element then it fails with the following error:
```
Default Product Listing Sort by does not exist in Available Product Listing Sort By.
```
Since the `Magento\Catalog\Model\Category\Attribute\Backend\Sortby` backend model assumes that the value is a string and not an array.

### Manual testing scenarios (*)
1. Call the Magento REST API with the following:
endpoint: rest/V1/categories
method: POST
payload:
```
{
    "category": {
        "position": 0,
        "available_sort_by": [
            "name",
            "price",
            "position"
        ],
        "parent_id": 0,
        "name": "Test",
        "is_active": true,
        "include_in_menu": true,
        "custom_attributes": [
            {
                "attribute_code": "default_sort_by",
                "value": "name"
            },
            {
                "attribute_code": "description",
                "value": ""
            },
            {
                "attribute_code": "meta_description",
                "value": ""
            },
            {
                "attribute_code": "meta_keywords",
                "value": ""
            },
            {
                "attribute_code": "meta_title",
                "value": ""
            },
            {
                "attribute_code": "display_mode",
                "value": "PRODUCTS"
            },
            {
                "attribute_code": "image",
                "value": ""
            }
        ]
    }
}
```
2. Result:
```
Error occurred during "custom_attributes" processing. Attribute "default_sort_by" has invalid value. The "string" value's type is invalid. The "string[]" type was expected. Verify and try again.
```

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by tkotosz** [comment]
@magento give me 2.3.1 instance

**Comment by magento-engcom-team** [comment]
Hi @tkotosz. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by magento-engcom-team** [comment]
Hi @tkotosz, here is your [Magento instance](https://i-23228-2-3-1.instances.magento-community.engineering).
Admin access: [https://i-23228-2-3-1.instances.magento-community.engineering/admin](https://i-23228-2-3-1.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5322](https://jira.corp.magento.com/browse/ENGCOM-5322) has been created to process this Pull Request

**Review by sidolov — CHANGES_REQUESTED** [review]
@tkotosz , please, take a look at failed tests

**Comment by sidolov** [comment]
@tkotosz , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by shankar15498** [comment]
Is this issue solved?

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Hey @tkotosz. Are you still up to working on this PR?
If yes, could you please sign CLA.

**Comment by lenaorobei** [comment]
Closing this PR due to inactivity. Please feel free to reopen if you are going to continue working on it.
Thank you.

**Pull request closed without merging**
