### PR TITLE
[Backport] A non-numeric value encountered on mass product update when..

### PR DESCRIPTION
**Pull request by Nazar65**
**Original PR** #19095
### Description (*)
1. On developer environment a exception: Exception #0 (Exception): Warning: A non-numeric value encountered in /var/www/html/vendor/magento/module-catalog/view/adminhtml/templates/catalog/product/edit/action/inventory.phtml on line 109 is presen

### Fixed Issues (if relevant)
1. magento/magento2#21073: A non-numeric value encountered on mass product update when Minimum Qty Allowed in Shopping Cart is used
2. ...

### Manual testing scenarios (*)
* Set Minimum Qty Allowed in Shopping Cart in System -> Configuration for values for different Customer Groups
* Try access Mass product update attributes action

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Nazar65. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4182](https://jira.corp.magento.com/browse/ENGCOM-4182) has been created to process this Pull Request

**Comment by sidolov** [comment]
Hi @Nazar65 , unfortunately, changes in the original PR were refactored due to backward incompatible changes (introduced new public method in the class marked as @api). You may view these changes in scope of commit: https://github.com/magento/magento2/commit/0fd425ff31a0e1afd76ba583246cbb9c1b265788#diff-7cf271ccff40947cf32660a3f0d76e70
Please, adopt current implementation according to changes in 2.3 release line. 
Thank you!

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-4182](https://jira.corp.magento.com/browse/ENGCOM-4182) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
