### PR TITLE
Removing ie-class-fixer.js

### PR DESCRIPTION
**Pull request by in-session**
It looks like Magento doesn't support IE11, so we can remove it.
https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#supported-browsers

Related to https://github.com/magento/magento2/issues/33686

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@in-session, even more - it looks like Magento doesn't support IE11, so we can remove it.
https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#supported-browsers

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Oh... I just tried to look at...
https://github.com/magento/magento2/search?q=ie11
https://github.com/magento/magento2/search?q=ie10
https://github.com/magento/magento2/search?q=ie9
https://github.com/magento/magento2/search?q=ie8
https://github.com/magento/magento2/search?q=ie7
https://github.com/magento/magento2/search?q=ie6

It feels like we can remove a huge amount of garbage!

**Comment by in-session** [comment]
> Oh... I just tried to look at... https://github.com/magento/magento2/search?q=ie11 https://github.com/magento/magento2/search?q=ie10 https://github.com/magento/magento2/search?q=ie9 https://github.com/magento/magento2/search?q=ie8 https://github.com/magento/magento2/search?q=ie7 https://github.com/magento/magento2/search?q=ie6
> 
> It feels like we can remove a huge amount of garbage!

This will take a while, maybe I can do it next week.

**Comment by ihor-sviziev** [comment]
@sidolov @sivaschenko, such improvement will have a small performance improvement. Can we set the priority to P2 in this case?

Can we do a code cleanup from ie11, ie10, ie9, ie8, ie7, ie6 related code/styles? I think the combination of these two ideas will have a noticeable performance frontend improvement.

Any thoughts?

**Comment by ihor-sviziev** [comment]
It's good to see that this PR got P2 priority. Let's try to finalize it

@magento run Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
Moving back this PR in Changes Requested as it seems that bot moved it in other status.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Review by ishakhsuvarov — APPROVED** [review]

**Pull request merged**
