### PR TITLE
add support for loading etc/adminhtml/system.xml for modules outside …

### PR DESCRIPTION
**Pull request by Flyingmana**
…app/code

also likely to solve the problem for other etc files of a module

### CODE REVIEW

**Comment by Flyingmana** [comment]
fix for `unit` and `static_annotation` Suite will come in a few days. 

the others iam currently not sure if broken by me.

a little bit of Feedback about the made change would still be great. Especially if such kind of change has a chance for getting accepted.

**Comment by Vinai** [comment]
I think this PR has been made obsolete by the recent updates to the module directory initialization. What do you think @Flyingmana ?

**Comment by Flyingmana** [comment]
are the changes already in `1.0.0-beta6`? If yes I will test it trough.

**Comment by Vinai** [comment]
I haven't compared the PR code to the code in the code, but I have used a system.xml file in a module within vendor two weeks ago or so. It just was a very small test file, but it was being parsed. Can you check, too?

**Comment by Flyingmana** [comment]
My question was not about the code of this PR.
To explain, I dont have much time to maintain multiple dev setups, so I only use the one I work with. This is based on a composer install using the multiple packages on packages.magento.com. I currenlty use `1.0.0-beta6` which has not all latest changes from dev.
I can check it there, but seeing that the xml namespaces still use relative urls, and not the `urn:magento:...` ones, I expect the result to be negative.

**Comment by Vinai** [comment]
Same, so lets wait until release and your dev setup contains the latest changes.

**Comment by Flyingmana** [comment]
I close this PR, as the change is not needed anymore.
But the Issue is still not completely fixed, it just moved to another place of the framework, which currently only allows modules inside the Project root, not outside of it.

**Pull request closed without merging**
