### PR TITLE
Issue 35154: Catalog price rule and product custom option price bug w…

### LINKED ISSUE #35154: magento 2.4.3-p1 - catalog price rule and product custom option price bug when convert currency
### Preconditions (*)
1. Magento version 2.4.3-p1
1. PHP 7.4

### Steps to reproduce (*)

1. Setup fresh Magento website with 1 website, 1 store and 2 store views. Base currency EUR, first store view has display currency = EUR,  second store view has display currency = NOK.   Setup currency rate 1 EUR = 10 NOK
1. Create simple product with price = 100 EUR, add custom option of type checkbox for that product with price = fixed price 10 EUR. 
1. Create catalog price rule for customer group General, discount set as apply to percentage to orginal price 15%
1. Create new customer account of group general, login to checkout price on NOK store view

### Expected result (*)
1. custom option price = 85 NOK (8.5 EUR x 10)  after discount

### Actual result (*)
1. custom option price = 850 NOK  (100 times)  --> look like currency is convert twice.
## 

- <x> Severity: **S0**

### PR DESCRIPTION
**Pull request by rogerdz**
### Description (*)

Custom option price convert twice

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35154

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Review by edenduong — CHANGES_REQUESTED** [review]
Hi @rogerdz ,
Thank you for your contribution. Could you please cover your change by Unit Test or Integration Test?

**Comment by engcom-Hotel** [comment]
Hello @rogerdz,

Thanks for the contribution!

It seems that the internal team already addressed and fixed the issue. The related PR is in `Merge in progress`. Once it will merge with the development branch ie 2.4-develop, we will notify you here for the same.

Hence for now we are closing this PR.

Thanks

**Pull request closed without merging**
