### PR TITLE
Fixed the issue 25930

### PR DESCRIPTION
**Pull request by divyajyothi5321**
### Fixed Issues (if relevant)

1. magento/magento2#25930: Integration Success Message Text Overflow Issue in Admin

### Manual testing scenarios (*)

1. Go to admin->System->Extenstions->Integrations
2. Add new integration name with 255 characters and save the integration
3. Now the text overflow issue is fixed as shown in below screencast.

integrations

4. When we delete, edit and duplicate the integration name we can also find this text overflow issue. By this fix we can resolve all these issues.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ptylek — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-6458](https://jira.corp.magento.com/browse/ENGCOM-6458) has been created to process this Pull Request
:eight_spoked_asterisk: @ptylek, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by kanthy-i95dev — APPROVED** [review]

**Comment by engcom-Charlie** [comment]
Hello @divyajyothi5321 
I am not able to reproduce this issue on the Magento 2.4-develop.

**Testing scenario:**

1. Go to admin->System->Extenstions->Integrations
2. Add new integration name with 255 characters and save the integration

**Result:**
Success message is not disturbing the page
image

**Review by krzksz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-6458](https://jira.corp.magento.com/browse/ENGCOM-6458) has been created to process this Pull Request

**Comment by krzksz** [comment]
Hello @engcom-Charlie, the issue is reproductible:
obraz
It seems like either your screen is too wide or integration name is not long enough. It is a corner case, but still...

**Comment by engcom-Charlie** [comment]
@krzksz yes, you are right. 
image

Thank you for contribution and collaboration!

**Comment by engcom-Charlie** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
