### PR TITLE
Fix Undefined index: option_value in GraphQL for configurable products

### LINKED ISSUE #28860: Magento 2.3.4 graphql Notice: Undefined index: option_value in /var/www/html/mg234/vendor/magento/module-configurable-product-graph-ql/Model/Resolver/ConfigurableCartItemOptions.php on line 62
### Preconditions (*)

1. Magento 2.3.4
2. Config product with custom options

### Steps to reproduce (*)

1. Create config product with custom options
2. Add product to cart (addConfigurableProductsToCart) using this mutation

```
mutation {
  addConfigurableProductsToCart(
    input: {
      cart_id: "IkzvsoUeXwvb6g2jrdqVNmuXPqmznAqI"
      cart_items: [
        {
          parent_sku: "config-sku"
          data: {
            quantity: 1
            sku: "config-sku-White"
          }
        customizable_options:[	
          {
            id:2
            value_string:"4"
          }
        ]        }      ]
    }
  ) {
    cart {
      items {
        id
        quantity
        product {
          name
          sku
        }
        ... on ConfigurableCartItem {
          configurable_options {
            option_label
            value_label
            value_id
          }
         customizable_options {
            label
            values {
              value
            }
          }        }      }
    }
  }
}
```

### Expected result (*)

1. Configurable product will add to cart

### Actual result (*)

1. 
```
{
  "errors": [
    {
      "debugMessage": "Notice: Undefined index: option_value in /var/www/html/oxygen/vendor/magento/module-configurable-product-graph-ql/Model/Resolver/ConfigurableCartItemOptions.php on line 62",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 36,
          "column": 11
        }
      ],
      "path": [
        "addConfigurableProductsToCart",
        "cart",
        "items",
        0,
        "configurable_options"
      ]
    }
  ],
  "data": {
    "addConfigurableProductsToCart": {
      "cart": {
        "items": [
          null
        ]
      }
    }
  }
}

```

### PR DESCRIPTION
**Pull request by peterjaap**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/28860

### Manual testing scenarios (*)

1. See https://github.com/magento/magento2/issues/28860

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rodrigowebjump** [comment]
Hi @peterjaap Please could you check the Adobe CLA Sign?

Thanks

**Comment by rodrigowebjump** [comment]
@magento run all tests

**Comment by peterjaap** [comment]
@rodrigowebjump done

**Comment by gabrieldagama** [comment]
@magento run all tests

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @peterjaap, thanks for contributing! Can you cover this PR changes with automated tests? We can't proceed with delivery and approval without it.

Thank you!

**Comment by peterjaap** [comment]
@gabrieldagama no thanks. I just needed the patchfile.

**Comment by engcom-Bravo** [comment]
Hi @peterjaap 
Thank you for your contribution,

We tried to reproduce the same on `2.4-develop`, But its not reproducible.

Here the my GraphQL Request

`mutation {
  addConfigurableProductsToCart(
    input: {
      cart_id: "hURmijr3leRFknQb4hZ2Ddugqjf6Bvoy"
      cart_items: [
        {
          parent_sku: "MH01"
          data: {
            quantity: 1
            sku: "MH01-XS-Black"
          }
          customizable_options: [
            {
              id: 2,
              value_string: "3"
            }
          ]
        }
      ]
    }
  ) {
    cart {
      items {
        uid
        quantity
        product {
          name
          sku
        }
        ... on ConfigurableCartItem {
          customizable_options {
            label
            values {
              value
            }
          }
          configurable_options {
            option_label
            value_label
            value_id
          }
        }
      }
    }
  }
}`
Response
`{
  "data": {
    "addConfigurableProductsToCart": {
      "cart": {
        "items": [
          {
            "uid": "Nw==",
            "quantity": 1,
            "product": {
              "name": "Chaz Kangeroo Hoodie",
              "sku": "MH01"
            },
            "customizable_options": [
              {
                "label": "Options",
                "values": [
                  {
                    "value": "3"
                  }
                ]
              }
            ],
            "configurable_options": [
              {
                "option_label": "Color",
                "value_label": "Black",
                "value_id": 49
              },
              {
                "option_label": "Size",
                "value_label": "XS",
                "value_id": 166
              }
            ]
          }
        ]
      }
    }
  }
}`

Hence closing this PR

You can try the same on mainline `2.4-develop`, If still its reproducible, Please reopen and update if you wish to continue.

Thanks

**Pull request closed without merging**
