### PR TITLE
Backport MAGETWO-57796 and MAGETWO-66885 for Magento 2.1

### PR DESCRIPTION
**Pull request by hostep**
### Description
This fixes an issue in the tinymce editor when editing a wysiwyg field on the product edit form pages, where inserted images would get an incorrect url. (not sure if this also fixes the same issue on the category edit form, didn't test this)

I've included MAGETWO-66885 because MAGETWO-57796 introduced a new bug: https://github.com/magento/magento2/issues/9452

See the commit messages to see from which commits I cherry-picked this.

Be aware, some of these issues mention MAGETWO-59690 as the internal ticket number for backporting this to 2.1, if this has already been done, you can close this PR.

### Fixed Issues (not 100% sure about all these, and I might have missed some)
1. https://github.com/magento/magento2/issues/6138: inserted image in product description got broken on front end
2. https://github.com/magento/magento2/issues/6088: inserted image in product description got broken on front end
3. https://github.com/magento/magento2/issues/7306: Images in Product description disappear
4. https://github.com/magento/magento2/issues/7215: Dynamic Media URLs in Products not working properly
5. https://github.com/magento/magento2/issues/7393: images added with WYSIWYG in category description are uploaded into admin-directory
6. https://github.com/magento/magento2/issues/7618: WYSIWYG is not working and removes images in product
7. https://github.com/magento/magento2/issues/9292: Wysiwyg editor image upload not working in magento 2
8. https://github.com/magento/magento2/issues/5444: Magento CE 2.1 Catalog Admin Page cannot parse media url in html content
9. https://github.com/magento/magento2/issues/6851: Using the WYSIWYG removes URL in the description
10. https://github.com/magento/magento2/pull/10131: Image link broken on product Description and short description part.

(Completely offtopic: is there any way for the community to know what you guys already backported to 2.1? Why aren't you using the 2.1-develop branch for this? It looks like only community contributions go to that branch. It would be highly appreciated if we could see what Magento is backporting themselves, that would help out tremendously.)

### CODE REVIEW

**Comment by ishakhsuvarov** [comment]
Hi @hostep 
Unfortunately we can not accept this PR at the moment because issue is already fixed internally and is currently staged for `2.1.8` release. 
I can see, that fix was not published to the `2.1-develop` branch by Magento development team, therefore not available on the GitHub.
Based on this experience we are currently working out a better branching strategy which would eliminate possibility of this happening again. 

Please feel free to comment on the PR or reach us directly in the Community Engineering slack channel if you have any questions. 
Thank you for collaboration.

**Comment by korostii** [comment]
> eliminate possibility of this happening again

IMHO keeping the status of corresponding GitHub issues up to date with your internal tasks and branches would help a lot: 
- just setting either a milestone like `2.1.8` or an assignee to the issue, if the backport is being actively worked on, and\or is staged for a certain release internally already, etc,
- an `up for grabs` label otherwise

**Comment by ishakhsuvarov** [comment]
@korostii I agree. We are going to implement one of the solutions asap.

**Comment by hostep** [comment]
@ishakhsuvarov: now that you guys have opened up the 2.1.8-preview branch (which is awesome, thanks for that!), I can see you backported MAGETWO-57796 but **not** MAGETWO-66885.
Can you make sure you don't forget that, as it contains a very very annoying bug: #9452
This line should be removed: https://github.com/magento/magento2/blob/c5ea1ba/lib/web/mage/adminhtml/wysiwyg/tiny_mce/setup.js#L350

Thanks!

**Comment by hostep** [comment]
@ishakhsuvarov: can you confirm you read my last comment? So this bug doens't make it in the final 2.1.8 version. Otherwise there will be a lot of new issues being opened around this bug after 2.1.8 was released I'm afraid.

//cc @okorshenko

**Comment by okorshenko** [comment]
Hi @hostep MAGETWO-66885 was backported as a MAGETWO-59690: [Backport] - [GitHub] Inserted image in product description got broken on front end #6138 - for 2.1 in https://github.com/magento/magento2/commit/0acbc575fd1c92e1620a43e69bbf8402e8691eb5
Also see https://github.com/magento/magento2ce/pull/1101/commits/ba6612462c260da7cc534b6365623993a6fe4311

**Comment by hostep** [comment]
Yes, what I'm reporting is that MAGETWO-59690 contains a bug which MAGETWO-66885 fixes, but MAGETWO-66885 hasn't been backported yet, that's what I'm trying to say ;)
See: https://github.com/magento/magento2/blob/c5ea1ba/lib/web/mage/adminhtml/wysiwyg/tiny_mce/setup.js#L350
This line shouldn't exist.

**Comment by okorshenko** [comment]
Hi @hostep backport ticket for MAGETWO-66885 will be MAGETWO-68810. It is in our backlog. I will inform our POs about this issue one more time. Thank you

**Comment by hostep** [comment]
Ok thanks! :)

**Comment by okorshenko** [comment]
Hi @hostep 
I talked to 2.1.8 release team. They will try to include this fix based on your request. I will be following this issue till 2.1.8
Thank you for pushing this

**Comment by ishakhsuvarov** [comment]
@hostep Fix should now be available in the `2.1.8-preview` branch.

**Comment by hostep** [comment]
Thank @ishakhsuvarov, looks good! :)

**Pull request closed without merging**
