### PR TITLE
Replace sort callbacks to spaceship operator

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description
Small change to improve overall readability of Shipping Methods sorting

### Manual testing scenarios
1. Add multiple shipping methods with different Sort Orders
2. Proceed to checkout, compare shipping methods with expected ones

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16788) <br/>All committers have signed the CLA.

**Review by orlangur — APPROVED** [review]
Nice finding @lbajsarowicz! 👍

**Comment by lbajsarowicz** [comment]
I've found 3 more, to have it replaced globally.

**Review by orlangur — APPROVED** [review]
@lbajsarowicz big thanks for not making it as 4 separate PRs 👍

**Comment by lbajsarowicz** [comment]
Do I have to do anything to get this merged. 
@orlangur

**Comment by orlangur** [comment]
@lbajsarowicz no, you don't AFAIK.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-2613](https://jira.corp.magento.com/browse/ENGCOM-2613) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
