### PR TITLE
Admin controller product set save refactor

### PR DESCRIPTION
**Pull request by AnshuMishra17**
Description
Remove direct use of object manager for admin attribute set save controller using constructor based dependency injection.

Manual testing scenarios
Created a new attribute set in admin under Stores -> Attribute Set -> Add Attribute Set.
Edit an existing attribute set under Stores -> Attribute Set

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @AnshuMishra17. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on Pull Request changes
- `@magento-engcom-team give me new test instance` - deploy **NEW** test instance based on Pull Request changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy Vanilla Magento instance for Issue or Pull Request

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by hitesh-wagento** [comment]
Hi @ihor-sviziev 

Can I create Forwardport and Backport again for this PR ?

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
Hi @hitesh-wagento,
Let's wait when this PR will be merged, also author might want to do it himself

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-2093](https://jira.corp.magento.com/browse/ENGCOM-2093) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @AnshuMishra17. Thank you for your contribution. 
The changes from your Pull Request should be available with the upcoming 2.2.6 release. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
