### PR TITLE
Lossless compression

### PR DESCRIPTION
**Pull request by MathiasReker**
Lossless compression of images.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @MathiasReker. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by orlangur** [comment]
@MathiasReker which is the tool used here?

**Comment by MathiasReker** [comment]
yarn prettier

**Comment by MathiasReker** [comment]
- AdvanceCOMP 2.10 - https://github.com/amadvance/advancecomp
- APNG Optimizer 1.4 - http://sourceforge.net/projects/apng/
- Coherent PDF Command Line Tools (cpdf) 2.2 Patchlevel 1 - http://community.coherentpdf.com
- CSSTidy 1.3 - http://csstidy.sourceforge.net/download.php
- DeflOpt 2.07 - http://www.walbeehm.com/download/
- defluff 0.3.2 - http://j-o.users.sourceforge.net
- Document Press Version 6.01 - http://encode.ru/threads/336-Document-Press-6-01
- ECT 0.8.3.47 (g4a45c139e86) - https://github.com/fhanau/Efficient-Compression-Tool
- ffmpeg 4.1.0 - http://ffmpeg.zeranoe.com/builds/
- FLAC 1.3.2 - https://xiph.org/flac/
- FLACOUT 07/03/2014 - http://advsys.net/ken/utils.htm
- Flasm 1.62 - http://flasm.sourceforge.net
- flexiGIF 2018.11a - https://create.stephan-brumme.com/flexigif-lossless-gif-lzw-optimization/
- Gifsicle 1.91 - http://www.lcdf.org/gifsicle/
- Gifsicle Lossy 1.91 - https://kornel.ski/lossygif
- Ghostscript 9.26 - http://www.ghostscript.com
- GNU Strip 2.30 - https://sourceforge.net/projects/mingw-w64/
- Guetzli 1.0.1 - https://github.com/google/guetzli
- ImageMagick 7.0.8.15 - http://www.imagemagick.org
- ImageWorsener 1.3.3 - http://entropymine.com/imageworsener
- jhead 3.02 - http://www.sentex.net/~mwandel/jhead/
- jpeg-archive 2.1.1 - https://github.com/danielgtaylor/jpeg-archive
- jpegoptim 1.4.6 - http://www.kokkonen.net/tjko/projects.html
- jpegtran 9b - http://jpegclub.org/jpegtran/
- jsmin 2013-03-29 - http://www.crockford.com/javascript/jsmin.html
- Leanify 0.4.3.224 - https://github.com/JayXon/Leanify (https://ci.appveyor.com/project/JayXon/leanify)
- libdeflate 0.8 - https://github.com/ebiggers/libdeflate
- libwebp 1.0.1 - https://storage.googleapis.com/downloads.webmproject.org/releases/webp/index.html
- m7zRepacker 1.0.32.319 - https://encode.ru/threads/1201-m7zRepacker
- mkclean 0.8.10 - http://www.matroska.org/downloads/mkclean.html
- mozjpeg 3.3.1-3 - https://github.com/garyzyg/mozjpeg-windows/
- MP3packer 2.04 - http://omion.dyndns.org/mp3packer/mp3packer.html
- mp4v2 4.0.1 - https://github.com/TechSmith/mp4v2
- mutool 1.14 - http://mupdf.com/downloads/
- OptiPNG 0.7.7 - http://optipng.sourceforge.net
- PETrim 4.00 beta - http://pecompact.com/pesuite.php
- pingo 0.98.46 - http://css-ig.net/pingo
- PngOptimizer 2.5 - http://psydk.org/PngOptimizer
- PNGOUT 02/13/2015 - http://advsys.net/ken/utils.htm
- pngquant 2.12.0 - http://www.pngquant.org
- pngrewrite 1.4.0 - http://entropymine.com/jason/pngrewrite
- pngwolf-zopli 1.1.2 - https://github.com/jibsen/pngwolf-zopfli
- rehuff - http://wiki.xiph.org/Rehuff
- shntool 3.0.10 - http://www.etree.org/shnutils/shntool/
- Tidy 5.6.0 - http://www.html-tidy.org
- TruePNG 0.6.2.5 - http://x128.ho.ua/pngutils.html
- UPX 3.95 - https://upx.github.io
- ZLib 1.2.8 - http://www.zlib.net
- zRecompress 2.12 - http://nikkhokkho.sourceforge.net/static.php?page=zRecompress

**Comment by orlangur** [comment]
@MathiasReker do you have a CLI command maybe? :) Or some gist to apply them

**Comment by MathiasReker** [comment]
I run everything from console, yes.

**Comment by MathiasReker** [comment]
The libraries are built in into my shell script.

**Comment by orlangur** [comment]
@MathiasReker without such script provided we cannot evaluate these changes.

**Pull request closed without merging**
