### PR TITLE
Change misleading class method name

### PR DESCRIPTION
**Pull request by walterdolce**
### Purpose

Enhance code clarity
### Background

In Magento\Framework\Filesystem\DirectoryList#L130 the private method has a name that doesn't reflect what the method actually does. It does not filter paths, but it performs a conversion (the doc block suggests that as well).
### Reason for this PR

This PR changes the method name from 'filterPath' to 'convertPathSlashes' to improve code clarity and understanding.

### CODE REVIEW

**Comment by Vinai** [comment]
<3

**Comment by antonkril** [comment]
Method names should not describe what exactly happens. If additional string transformation is added in that method, we will have to change the name of that method.

**Comment by Vinai** [comment]
But `filter`is indeed miss-leading. How about `normalizePath()`?

**Comment by antonkril** [comment]
Sounds good

**Comment by walterdolce** [comment]
> Method names should not describe what exactly happens.

I don't fully agree on this @antonkril. I think that at any given point in time, given a context, a method should always describe what it's going to do. It could not go into detail, like i.e. `replaceBackslashesWithForwardSlashes`, but it should give a generic and clear understanding of its purpose.

But yeah, `normalisePath` sounds good :+1: 

cc @Vinai

**Comment by mlopes** [comment]
Method names should describe exactly what happens from a functional point of view, not from the implementation perspective. That way if the implementation changes, the method name stays the same, as its implementation is a back box. If new behaviour is needed, then it should go somewhere else, as per the open/closed principle, and single responsibility principle.

**Comment by danielkmariam** [comment]
+1 @mlopes

**Comment by magento-cicd** [comment]
We have automated a Magento Contributor License Agreement verifier for contributions sent to our GitHub projects.
Please see the CLA agreement in the Pull Request comments.

**Comment by walterdolce** [comment]
I don't see any mention in this PR.

I would also suggest to let the bot provide a link to the CLA.

**Comment by joanhe** [comment]
@walterdolce Thanks for your contribution. I am going to process this pull request. Could you please check CLA https://cla.dev.magento.com/magento/magento2?pullRequest=1486 if you agree and make sure your change pass Travis CI build?

**Comment by walterdolce** [comment]
@joanhe done CLA, thank you.For the failing tests I have updated the branch with the latest `develop` changes. I don't think the previous failure was caused by the changes as I only changed a `private` method name.

**Comment by walterdolce** [comment]
Merged latest `develop`. Lights are green.

**Comment by vancoz** [comment]
Hi @walterdolce, thank you for your contribution!
Internal ticket number is MAGETWO-47811

**Pull request merged**
