### PR TITLE
Adjustment stale-bot configuration with Severity Labels

### PR DESCRIPTION
**Pull request by sdzhepa**
### Description (*)

1. Added Severity labels to the exception for stale-bot.
-- If an issue has "Severity 0" or "Severity 1" stale-bot will not close it as stale 

2. Increased values for for `daysUntilStale` and `daysUntilClose`

### CODE REVIEW

**Comment by hostep** [comment]
Great, some kind of progress! But it will still not be enough. The stalebot is causing way too much frustration to contributors and is scaring them away from wanting to submit new issues or send in PR's.
It's sad to see that so many issues receive no attention whatsoever even if they sound important from their description.

Maybe also consider doubling the `daysUntilStale` and `daysUntilClose` settings?
Even though that's just a workaround, the real solution is to have more **knowledgable** people investigating opened issues. And not only considering new issues that are opened in the last day or so but also look at issues that have been open for a long time.

**Review by gabrieldagama — APPROVED** [review]

**Comment by sdzhepa** [comment]
Agree with your point @hostep 
The solution for this problem is to have more people interesting in issue verification, confirmation, and processing.

And yes, it makes sense to increase the time for `daysUntilStale` and daysUntilClose`.

@gabrieldagama  please do not process this PR, I will add new commit

**Review by Den4ik — APPROVED** [review]
👏 Thats great

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9117](https://jira.corp.magento.com/browse/ENGCOM-9117) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Pull request merged**
