### PR TITLE
Fixed widget template rendering issue while rewriting widget block.

### PR DESCRIPTION
**Pull request by sanganinamrata**
### Description

Fixed template notation for **Magento_CatalogWidget** module.

### Fixed Issues (if relevant)

Magento version **2.2.x**
1. magento/magento2#16529: Rewriting product listing widget block breaks its template rendering.2. ...

### Manual testing scenarios

N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @sanganinamrata. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by miguelbalparda** [comment]
@sanganinamrata can you please check the [failing tests](https://travis-ci.org/magento/magento2/jobs/399969941)?

**Comment by sanganinamrata** [comment]
@miguelbalparda - Ok I'll check the failing tests soon and get back to you.

**Comment by sanganinamrata** [comment]
@gelanivishal Thanks for the quick fix.

**Comment by sanganinamrata** [comment]
@miguelbalparda : Failing test is fixed, Please have a look.

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-2211](https://jira.corp.magento.com/browse/ENGCOM-2211) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @sanganinamrata. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.6. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
