### PR TITLE
ISSUE #23042: Update stock status on CSV Product import if quantity is 0

### PR DESCRIPTION
**Pull request by kristiancharb**
### Description (*)
If the is_in_stock field is not present in a particular row in the
CSV file and the qty field is set to 0, the default is_in_stock value
is overridden from 1 to 0.

### Fixed Issues (if relevant)

1. magento/magento2#23042: Magento2 CSV product import automatic stock status broken 

### Manual testing scenarios (*)

1. Create a Product with a positive quantity and "In Stock" status
2. Create a CSV file to update the product from step 1
3. In the CSV file, set the qty field to 0 and omit the is_in_stock field altogether
4. Import CSV file 
5. Stock status should change to "Out of Stock"

### Questions or comments

Based on the Product.php class, it seems that the stock status being set to 1 by default if is_in_stock is omitted is intentional and not an issue. However, the additional if statement in this PR should fix the issue as described.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24053) <br/>All committers have signed the CLA.

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @kristiancharb , please, sign CLA, otherwise, we can't process your pull request. Thanks

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5702](https://jira.corp.magento.com/browse/ENGCOM-5702) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@kristiancharb thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
@kristiancharb thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request merged**
