### PR TITLE
issues/36800 - Can't create credit memo with free shipping

### LINKED ISSUE #36800: Can't create credit memo - free shipping related (Division by zero exception)
### Preconditions and environment

- Magento version Commerce 2.4.6-beta2

### Steps to reproduce

1. Enable free shipping from Stores > Configuration > Sales > Delivery Methods.
2. Use the following Tax calculation settings:
calulation settings
4. Use the following display settings (required):
display settings
6. Flush cache
7. Login on the frontend and place an order with Free shipping.
8. Create the invoice
9. Attempt to create the credit memo.

### Expected result

Credit memo created

### Actual result

The CollectTotals throws the exception "Division by zero".
vendor/magento/module-sales/Model/Order/Creditmemo/Total/Tax.php
Line 139

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by yogesh-valiya**
### Description (*)

The `if` statement was missing `$orderShippingAmount` validation, which was resulting in `DivisionByZeroError` result on line `app/code/Magento/Sales/Model/Order/Creditmemo/Total/Tax.php:140`. 

It's safe to say that if the `$orderShippingAmount` is 0 then totals won't get affected by shipping amount, so we can adjust `if` statement accordingly.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36800

### Manual testing scenarios (*)

1. Try to reproduce issue with steps provided in issue description - https://github.com/magento/magento2/issues/36800#issue-1568681549
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by yogesh-valiya** [comment]
@magento run all tests

**Comment by yogesh-valiya** [comment]
@magento run Integration Tests

**Comment by yogesh-valiya** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

**Comment by yogesh-valiya** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by yogesh-valiya** [comment]
@magento run Functional Tests B2B

**Comment by yogesh-valiya** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by yogesh-valiya** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by yogesh-valiya** [comment]
@magento run Functional Tests EE

**Comment by yogesh-valiya** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by yogesh-valiya** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by jeroen-hso** [comment]
Why is this patch not released in 2.4.6-p1?

**Comment by hostep** [comment]
@jeroen-hso: because 2.4.6-p1 is supposed to only fix security issues, not bug fixes.

Anyway, but it appears that Adobe released a quality patch for this: [ACSD-50814](https://github.com/magento/quality-patches/blob/b0065b97798f98f5f46a2ab2be8463f08cf01f06/patches/os/ACSD-50814_2.4.6.patch), with the following [description](https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/support-tools/patches/v1-1-30/acsd-50814-an-admin-user-is-not-able-to-create-credit-memo.html?lang=en)

**Comment by jeroen-hso** [comment]
@hostep Thanks!

**Comment by LucScu** [comment]
@hostep not included in 2.4.6-p3 right?
Should it be included in 2.4.7?

**Comment by hostep** [comment]
That's correct

**Pull request merged**
