### PR TITLE
Fix product gallery jump during page load

### LINKED ISSUE #32315: Product gallery jumps while loading
It seems like after https://github.com/magento/magento2/pull/27871 we have a bit jumpy gallery again. My investigation shown that it's happening because of not hiding the thumbnails below the big image.

/CC @krzksz 

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1. Open frontend in chrome, open developer tools 
2. In the "source tab" set a breakpoint on the following line: https://github.com/magento/magento2/blob/15860ab3ab274e1b0df007b5cdb8bf30b52fe515/lib/web/mage/gallery/gallery.js#L307
3. refresh the page
4. When the script will stop on breakpoint switch to the elements tab and find the `.fotorama-item` item

### Expected result (*)

1. There should be no jumps during gallery load

### Actual result (*)

1. fotorama-items eats some space that causes not expected layout shifts:
**Dev tools:**
image
**Desktop:**
image
**Mobile:**
image

https://user-images.githubusercontent.com/1873745/109507971-fbf1ff80-7aa7-11eb-8182-9c3bfcdb3fe5.mp4

2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
- Position absolute will prevent page jumping
- Move logic from JS to css  (position absolute + z-index=-1 will render gallery on background)

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/32315

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Static Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
@magento run Database Compare, Integration Tests, Magento Health Index, Sample Data Tests B2B, Sample Data Tests CE , Sample Data Tests EE, Semantic Version Checker, Unit Tests, WebAPI Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Review by Den4ik — APPROVED** [review]
@ihor-sviziev Thanks for your work.
Reproduced described steps in issue and fix locally. All looks good.

**Comment by ihor-sviziev** [comment]
These changes were already merged in another pull request https://github.com/magento/magento2/pull/33265#issuecomment-1774582770

**Pull request closed without merging**
