### PR TITLE
#28431 issue fixed

### LINKED ISSUE #28431: REST API Bundle Product Details Price Issue
### Description
Bundle products have a price in the store and admin interface, but not in the Products Details REST API. 

### Preconditions
1. Magento 2.3.3

### Steps to reproduce
1. Create a bundle product and assign simple products to it.
image

2. Enable 'Allow Anonymous Guest Access'  from Store -> Configuration -> Services -> Magento Web API

3. GET /rest/V1/products/{sku} to get a details of bundle product.

### Expected result
1. Children products must have price in response 

### Actual result
1. Price is 'null' of children products.
```
{
  "id": 1203,
  "sku": "Bundle Product",
  "name": "Bundle Product",
  "attribute_set_id": 4,
  "price": 0,
  "status": 1,
  "visibility": 4,
  "type_id": "bundle",
  "created_at": "2020-05-27 11:02:38",
  "updated_at": "2020-05-27 11:02:38",
  "weight": 0,
  "extension_attributes": {
    "website_ids": [
      1
    ],
    "bundle_product_options": [
      {
        "option_id": 1,
        "title": "option 1",
        "required": true,
        "type": "select",
        "position": 1,
        "sku": "Bundle Product",
        "product_links": [
          {
            "id": "1",
            "sku": "product_dynamic_3",
            "option_id": 1,
            "qty": 1,
            "position": 1,
            "is_default": false,
            "price": null, // Price is null
            "price_type": null,
            "can_change_quantity": 0
          },
          {
            "id": "2",
            "sku": "product_dynamic_4",
            "option_id": 1,
            "qty": 1,
            "position": 2,
            "is_default": false,
            "price": null, // Price is null
            "price_type": null,
            "can_change_quantity": 0
          }
        ]
      }
    ]
  },
  "product_links": [],
  "options": [],
  "media_gallery_entries": [],
  "tier_prices": [],
  ....
}
```

---

- [X] Severity: **S0**

### PR DESCRIPTION
**Pull request by syed-ziffity**
### Description (*)
When we get the bundle product through REST API we get the null values for all child products. Because of conditions. 
### Finding
They have checked the Product type in the first step of the ternary operator. If product type is dynamic it will return "0" and the second step they consider the selected products. in this case, there is no selected product so it will return "0". So the condition returns false. in this case null value return for all child products. 

Fixes: https://github.com/magento/magento2/issues/28431

### Manual testing scenarios (*)
1. Create a bundle product and assign simple products to it.
2. Enable 'Allow Anonymous Guest Access' from Store -> Configuration -> Services -> Magento Web API.
3. GET /rest/V1/products/{sku} to get details of bundle products.
```{
    "id": 46,
    "sku": "24-WG080",
    "name": "Sprite Yoga Companion Kit",
    "attribute_set_id": 11,
    "price": 0,
    "status": 1,
    "visibility": 4,
    "type_id": "bundle",
    "created_at": "2020-06-01 06:43:20",
    "updated_at": "2020-06-11 13:59:36",
    "weight": 0,
    "extension_attributes": {
        "website_ids": [
            1
        ],
        "category_links": [
            {
                "position": 0,
                "category_id": "3"
            },
            {
                "position": 0,
                "category_id": "5"
            }
        ],
        "bundle_product_options": [
            {
                "option_id": 1,
                "title": "Sprite Stasis Ball",
                "required": true,
                "type": "radio",
                "position": 1,
                "sku": "24-WG080",
                "product_links": [
                    {
                        "id": "1",
                        "sku": "24-WG081-blue",
                        "option_id": 1,
                        "qty": 1,
                        "position": 1,
                        "is_default": true,
                        "price": 23,  \\Price
                        "price_type": null,
                        "can_change_quantity": 1
                    },
                    {
                        "id": "2",
                        "sku": "24-WG082-blue",
                        "option_id": 1,
                        "qty": 1,
                        "position": 2,
                        "is_default": false,
                        "price": 27,  \\Price
                        "price_type": null,
                        "can_change_quantity": 1
                    },
                    {
                        "id": "3",
                        "sku": "24-WG083-blue",
                        "option_id": 1,
                        "qty": 1,
                        "position": 3,
                        "is_default": false,
                        "price": 32,  \\Price
                        "price_type": null,
                        "can_change_quantity": 1
                    }
                ]
            },
            {
                "option_id": 2,
                "title": "Sprite Foam Yoga Brick",
                "required": true,
                "type": "radio",
                "position": 2,
                "sku": "24-WG080",
                "product_links": [
                    {
                        "id": "4",
                        "sku": "24-WG084",
                        "option_id": 2,
                        "qty": 1,
                        "position": 1,
                        "is_default": true,
                        "price": 5,  \\Price
                        "price_type": null,
                        "can_change_quantity": 1
                    }
                ]
            },
            {
                "option_id": 3,
                "title": "Sprite Yoga Strap",
                "required": true,
                "type": "radio",
                "position": 3,
                "sku": "24-WG080",
                "product_links": [
                    {
                        "id": "5",
                        "sku": "24-WG085",
                        "option_id": 3,
                        "qty": 1,
                        "position": 1,
                        "is_default": true,
                        "price": 14,  \\Price
                        "price_type": null,
                        "can_change_quantity": 1
                    },
                    {
                        "id": "6",
                        "sku": "24-WG086",
                        "option_id": 3,
                        "qty": 1,
                        "position": 2,
                        "is_default": false,
                        "price": 17,  \\Price
                        "price_type": null,
                        "can_change_quantity": 1
                    },
                    {
                        "id": "7",
                        "sku": "24-WG087",
                        "option_id": 3,
                        "qty": 1,
                        "position": 3,
                        "is_default": false,
                        "price": 21,  \\Price
                        "price_type": null,
                        "can_change_quantity": 1
                    }
                ]
            },
            {
                "option_id": 4,
                "title": "Sprite Foam Roller",
                "required": true,
                "type": "radio",
                "position": 4,
                "sku": "24-WG080",
                "product_links": [
                    {
                        "id": "8",
                        "sku": "24-WG088",
                        "option_id": 4,
                        "qty": 1,
                        "position": 1,
                        "is_default": true,
                        "price": 19,  \\Price
                        "price_type": null,
                        "can_change_quantity": 1
                    }
                ]
            }
        ]
    },
    "product_links": [],
    "options": [],
    "media_gallery_entries": [
        {
            "id": 52,
            "media_type": "image",
            "label": "Image",
            "position": 1,
            "disabled": false,
            "types": [
                "image",
                "small_image",
                "thumbnail"
            ],
            "file": "/l/u/luma-yoga-kit-2.jpg"
        }
    ],
    "tier_prices": [],
    "custom_attributes": [
        {
            "attribute_code": "image",
            "value": "/l/u/luma-yoga-kit-2.jpg"
        },
        {
            "attribute_code": "shipment_type",
            "value": "0"
        },
        {
            "attribute_code": "small_image",
            "value": "/l/u/luma-yoga-kit-2.jpg"
        },
        {
            "attribute_code": "thumbnail",
            "value": "/l/u/luma-yoga-kit-2.jpg"
        },
        {
            "attribute_code": "options_container",
            "value": "container2"
        },
        {
            "attribute_code": "msrp_display_actual_price_type",
            "value": "0"
        },
        {
            "attribute_code": "url_key",
            "value": "sprite-yoga-companion-kit"
        },
        {
            "attribute_code": "gift_message_available",
            "value": "0"
        },
        {
            "attribute_code": "price_view",
            "value": "0"
        },
        {
            "attribute_code": "required_options",
            "value": "1"
        },
        {
            "attribute_code": "has_options",
            "value": "1"
        },
        {
            "attribute_code": "image_label",
            "value": "Image"
        },
        {
            "attribute_code": "small_image_label",
            "value": "Image"
        },
        {
            "attribute_code": "thumbnail_label",
            "value": "Image"
        },
        {
            "attribute_code": "sku_type",
            "value": "0"
        },
        {
            "attribute_code": "price_type",
            "value": "0"
        },
        {
            "attribute_code": "tax_class_id",
            "value": "2"
        },
        {
            "attribute_code": "weight_type",
            "value": "0"
        },
        {
            "attribute_code": "category_ids",
            "value": [
                "3",
                "5"
            ]
        },
        {
            "attribute_code": "description",
            "value": "<p>A well-rounded yoga workout takes more than a mat. The Sprite Yoga Companion Kit helps stock your studio with the basics you need for a full-range workout. The kit is composed of four best-selling Luma Sprite accessories in one easy bundle: statis ball, foam block, yoga strap, and foam roller. Choose sizes and colors and leave the rest to us. The kit includes:</p>\n<ul>\n<li> Sprite Statis Ball\n<li> Sprite Foam Yoga Brick\n<li> Sprite Yoga Strap\n<li> Sprite Foam Roller\n</ul>"
        },
        {
            "attribute_code": "activity",
            "value": "8,11"
        },
        {
            "attribute_code": "gender",
            "value": "80,81,84"
        },
        {
            "attribute_code": "category_gear",
            "value": "87"
        },
        {
            "attribute_code": "eco_collection",
            "value": "0"
        },
        {
            "attribute_code": "performance_fabric",
            "value": "0"
        },
        {
            "attribute_code": "erin_recommends",
            "value": "0"
        },
        {
            "attribute_code": "new",
            "value": "0"
        },
        {
            "attribute_code": "sale",
            "value": "0"
        }
    ]
}
```
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sidolov** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sidolov. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sidolov, here is your [new Magento instance](https://pr-28689.instances.magento-community.engineering).
Admin access: [https://pr-28689.instances.magento-community.engineering/admin_3dbd](https://pr-28689.instances.magento-community.engineering/admin_3dbd)
Login: `1a80bfbb` Password: `546c6d3bde9c`
Instance will be terminated in up to 3 hours.

**Comment by syed-ziffity** [comment]
@magento run all tests

**Comment by syed-ziffity** [comment]
@magento run static, Database Compare

**Comment by syed-ziffity** [comment]
@magento run Static Tests

**Comment by syed-ziffity** [comment]
@magento run Static Tests

**Comment by syed-ziffity** [comment]
@magento run all tests

**Review by sidolov — CHANGES_REQUESTED** [review]
@syed-ziffity could you please cover changes with web API test?

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8131](https://jira.corp.magento.com/browse/ENGCOM-8131) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Create a bundle product and assign simple products to it.
2. Enable 'Allow Anonymous Guest Access' from Store -> Configuration -> Services -> Magento Web API.
3. **GET** `/rest/V1/products/{sku}` to get details of bundle products.

**Before:** :heavy_multiplication_x:  Prices for child's products are null



**After:** :heavy_check_mark: Children products have a correct price in the response

**Pull request merged**
