### PR TITLE
improve NonComposerComponentRegistration

### LINKED ISSUE #29308: [Issue] improve NonComposerComponentRegistration
This issue is automatically created based on existing pull request: magento/magento2#28975: improve NonComposerComponentRegistration

---------
### Description (*)
Magento 2.4-develop
enable strict mode and added typeHint, this changes make execution of code more secure.
remove useless assignation `$main`.

### Additional information
 Manual testing scenarios not necessary, if CI passes this code is good, it's only technical improvement.

### PR DESCRIPTION
**Pull request by rvitaliy**
### Description (*)
enable strict mode and added typeHint, this changes make execution of code more secure.
remove useless assignation `$main`.

### Related Pull Requests
none

### Fixed Issues
none

### Manual testing scenarios (*)
not necessary, if CI passes this code is good, it's only technical improvement.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29308: improve NonComposerComponentRegistration

### CODE REVIEW

**Comment by rvitaliy** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7781](https://jira.corp.magento.com/browse/ENGCOM-7781) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@rvitaliy thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Delta** [comment]
**Notice:** QA not applicable

**Comment by engcom-Delta** [comment]
@magento create issue

**Comment by VladimirZaets** [comment]
@magento create issue

**Pull request merged**
