### PR TITLE
Fix #7679: Quote Item - Duplicate sku in same quote

### LINKED ISSUE #7679: Quote Item - Duplicate sku in same quote
### Preconditions (*)
1. Magento 2.4-develop branch

### Steps to reproduce (*)
1. Create an account on frontend and log in to this account on frontent
2. Go to category page, click "♥" icon for product1 (just simple product) to add it to wishlist
3. On the wishlist page click **"Add to cart"** button on the product (NOTE: use button add to cart for single item. NOT ADD ALL TO CART).
4. Open developer console and remove "PHPSESSID" cookie (to emulate that session cookie already expired)
5. Go to the same category as in step 2, add to cart product 1
6. Click "Log In" and login to the same account as in step 1

### Expected result (*)
You should see in cart one product with qty 2:
image

### Actual result (*)
You see in cart two exactly the same products in cart, each with qty 1:
image

### Additional info:
@princeantil90 provided video for reproducing this issue https://nimb.ws/wcJX67

### PR DESCRIPTION
**Pull request by princeantil90**
### Fixed Issues (if relevant)

1. #7679: Quote Issue - Duplicate item in a different row during the customer quote merge

### Manual testing scenarios (*)

1. Log in as a user on the frontend. 
2. Add one product to the wishlist by clicking the wishlist icon. 
3. From the wishlist page, Add that item to cart. (NOTE: Use button Add to cart from the item card. NOT ADD ALL TO CART).
4. Clear cookies or session id. 
5. Go to category page and Add the SAME product to the cart.
6. Log in as a user on the frontend. 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by princeantil90** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @princeantil90. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @princeantil90, here is your [Magento instance](https://i-27548-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27548-2-4-develop.instances.magento-community.engineering/admin_3262](https://i-27548-2-4-develop.instances.magento-community.engineering/admin_3262)
Login: `86ee9120` Password: `5985dff7c6c3`
Instance will be terminated in up to 3 hours.

**Comment by princeantil90** [comment]
@magento Please check this issue and merge my pull request.

**Comment by ihor-sviziev** [comment]
Hi @princeantil90,
I just checked the issue description - looks like additional info was added not relevant, I just replied to it.

Could you give us more info how to reproduce the issue, maybe some additional steps or some screenshots / video of how to reproduce it?

Thank you!

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @princeantil90,
We’re you able to reproduce the issue on test instance?

I just checked the issue description - looks like additional info was added not relevant, I just replied to it.

Could you give us more info how to reproduce the issue on clean magento installation, maybe some additional steps or some screenshots / video of how to reproduce it?

Thank you!

**Comment by princeantil90** [comment]
> Hi @princeantil90,
> We’re you able to reproduce the issue on test instance?
> 
> I just checked the issue description - looks like additional info was added not relevant, I just replied to it.
> 
> Could you give us more info how to reproduce the issue on clean magento installation, maybe some additional steps or some screenshots / video of how to reproduce it?
> 
> Thank you!

Please review this video. This is how you can replicate it on Magento 2.3.4 latest version. 

https://nimb.ws/wcJX67

Kind regards,
Prince

**Comment by ihor-sviziev** [comment]
@princeantil90 thank you so much for detailed video! I was able to reproduce this issue on test instance and confirmed the issue!

**Comment by ihor-sviziev** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, here is your [new Magento instance](https://pr-27548.instances.magento-community.engineering).
Admin access: [https://pr-27548.instances.magento-community.engineering/admin_ab04](https://pr-27548.instances.magento-community.engineering/admin_ab04)
Login: `aa5e0e97` Password: `78d2923eacda`
Instance will be terminated in up to 3 hours.

**Comment by ihor-sviziev** [comment]
✔ I've checked - on this PR issue isn't reproducing:
image

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @princeantil90,
Thank you so much for details how to reproduce this issue and the fix!
Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered with automated tests.

Could you cover your changes with MFTF test?

Thank you!

**Comment by ihor-sviziev** [comment]
Hi @princeantil90,
Will you be able to cover your changes with MFTF test?

**Comment by engcom-Kilo** [comment]
Working on MFTF test.

**Comment by engcom-Kilo** [comment]
@princeantil90 @ihor-sviziev 
Can not reproduce with fresh Magento ver. dev-2.4-develop

**Comment by princeantil90** [comment]
Hi @engcom-Kilo 

Yes, this issue was fixed with ver. 2.4-develop

**Comment by ihor-sviziev** [comment]
Hi @princeantil90 ,
Thank you for confirming. As this issue isn’t reproducing anymore I just closed the issue and closing this PR. 
Thank you so much for contribution !

**Comment by princeantil90** [comment]
> Hi @princeantil90 ,
> Thank you for confirming. As this issue isn’t reproducing anymore I just closed the issue and closing this PR.
> Thank you so much for contribution !

Hi @ihor-sviziev 

This issue was fixed by my commit in 2.4-develop but not merged. Also, my contributions are not showing anywhere. Can you please guide why it has happened?

**Comment by ihor-sviziev** [comment]
@princeantil90 could you give me a link to commit that fixed this issue in 2.4-develop?

**Comment by princeantil90** [comment]
> @princeantil90 could you give me a link to commit that fixed this issue in 2.4-develop?

Hi @ihor-sviziev 

This pull request is created for this issue.

You've also checked and verified my fix in your comment in this PR above https://github.com/magento/magento2/pull/27548#pullrequestreview-387987720

This is my commit link: https://github.com/magento/magento2/pull/27548/commits/0450f864bd8e06830c25fc3fbd574dc467d4dd11

**Comment by ihor-sviziev** [comment]
Hi @princeantil90,
This commit isn’t in 2.4-develop branch.
I just checked the same file you’ve changed - looks like following commit fixed the issue https://github.com/magento/magento2/commit/0621f4f5179b5a42c81c8ba7eac779d1b1efb0f3

**Comment by princeantil90** [comment]
> Hi @princeantil90,
> This commit isn’t in 2.4-develop branch.
> I just checked the same file you’ve changed - looks like following commit fixed the issue [0621f4f](https://github.com/magento/magento2/commit/0621f4f5179b5a42c81c8ba7eac779d1b1efb0f3)

Hi @ihor-sviziev 

Thanks for sharing but I would like to know that why my commit was not merged as my changes also fixed the same issue when this commit https://github.com/magento/magento2/commit/0621f4f5179b5a42c81c8ba7eac779d1b1efb0f3 was not there. You've confirmed it on your own above.

**Comment by ihor-sviziev** [comment]
> > Hi @princeantil90,
> > This commit isn’t in 2.4-develop branch.
> > I just checked the same file you’ve changed - looks like following commit fixed the issue [0621f4f](https://github.com/magento/magento2/commit/0621f4f5179b5a42c81c8ba7eac779d1b1efb0f3)
> 
> Hi @ihor-sviziev
> 
> Thanks for sharing but I would like to know that why my commit was not merged as my changes also fixed the same issue when this commit [0621f4f](https://github.com/magento/magento2/commit/0621f4f5179b5a42c81c8ba7eac779d1b1efb0f3) was not there. You've confirmed it on your own above.

Unfortunately we weren’t able to test and accept your PR earlier as it wasn’t covered by automatic test. Later @engcom-Kilo wanted to help with covering this PR with auto test in order to push it forward, but found that issue already was fixed. So now we can’t  accept your solution as the issue was already fixed.
Thank for for understanding.

**Pull request closed without merging**
