### PR TITLE
[MFTF] Coverage for the 30256 Unexpected unchecking of "Append Comments" check-box issue

### LINKED ISSUE #32381: [Issue] WIP [MFTF] Coverage for the 30256 Unexpected unchecking of "Append Comments" check-box issue
This issue is automatically created based on existing pull request: magento/magento2#32226: WIP [MFTF] Coverage for the 30256 Unexpected unchecking of "Append Comments" check-box issue

---------
### Description (*)
The test covers [the 30256 Unexpected unchecking of "Append Comments" check-box issue](https://github.com/magento/magento2/issues/30256)

### Related Pull Requests
https://github.com/magento/magento2/pull/31422

### Manual testing scenarios (*)
1. Start order creating in Admin
2. Add product
3. Provide a comment
4. Assert if the "Append Comment" checkbox is checked
5. Select payment method
6. Select shipping method
7. Assert if the "Append Comment" checkbox is checked
8. Place the order
9. On the Order Details page check if a customer is notified of the comment

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
The test covers [the 30256 Unexpected unchecking of "Append Comments" check-box issue](https://github.com/magento/magento2/issues/30256)

### Related Pull Requests
https://github.com/magento/magento2/pull/31422

### Manual testing scenarios (*)
1. Start order creating in Admin
2. Add product
3. Provide a comment
4. Assert if the "Append Comment" checkbox is checked
5. Select payment method
6. Select shipping method
7. Assert if the "Append Comment" checkbox is checked
8. Place the order
9. On the Order Details page check if a customer is notified of the comment 

### Resolved issues:
1. [x] resolves magento/magento2#32381: WIP [MFTF] Coverage for the 30256 Unexpected unchecking of "Append Comments" check-box issue

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, Semantic Version Checker

**Review by shikhamis11 — CHANGES_REQUESTED** [review]
hi @AnnaAPak Thank you for the Pull Request. 
I believe to reproduce the issue you need to add a comment in order before selecting the shipping methods. 
so the steps will be like 

Start order creating in Admin
Add product
Provide shipping/billing information
Add Comment 
Assert if the "Append Comment" checkbox is checked
Select payment method
Select shipping method
Assert if the "Append Comment" checkbox is checked
Place the order
On the Order Details page check if a customer is notified of the comment

**Comment by AnnaAPak** [comment]
Hi @shikhamis11, 
thank you, I did miss the step with providing a comment (in the description, but in the test we have it) - corrected now.

**Comment by shikhamis11** [comment]
@AnnaAPak thank you for update. I would like you to add comment in order before selecting shipping method. As per the original issue , the append checkbox is unchecked while getting shipping rate if there is already comment added.

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, Semantic Version Checker

**Comment by shikhamis11** [comment]
hi @AnnaAPak 
Thank you for the update. 
can you add one more step to make sure if the append comment checkbox is checked after ` [provideComment]` step ? 
I have shared steps here https://github.com/magento/magento2/pull/32226#pullrequestreview-594732755

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Functional Tests EE

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by shikhamis11** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@AnnaAPak are you going to continue with this PR?

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by shikhamis11** [comment]
@magento run Functional Tests EE, WebAPI Tests

**Comment by AnnaAPak** [comment]
@engcom-Foxtrot sure, I will do my best to complete it till EOW. Thanks.

**Comment by shikhamis11** [comment]
@AnnaAPak can you check with the last commit of @engcom-Foxtrot the scrolling issue is fixed? 
also, remove `WIP` if it is completed

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, Semantic Version Checker

**Comment by shikhamis11** [comment]
@magento run Functional Tests B2B

**Review by shikhamis11 — APPROVED** [review]

**Comment by shikhamis11** [comment]
Failing tests are not related to this PR

**Comment by shikhamis11** [comment]
@magento run Functional Tests B2B

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, thank you for the review.
[ENGCOM-9137](https://jira.corp.magento.com/browse/ENGCOM-9137) has been created to process this Pull Request

**Comment by engcom-Charlie** [comment]
✔️ QA Passed

The provided MFTF test case is working fine and green in build. Please find the Allure report for the same.

image

image

**Pull request merged**
