### PR TITLE
Small fix in classes

### PR DESCRIPTION
**Pull request by iskolesnyk**
### Description (*)

Rename class properties

### Fixed Issues (if relevant)

Not relevant.

### Manual testing scenarios (*)

Not relevant.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19702) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @iskolesnyk. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
Hi @iskolesnyk thanks for the contribution. These changes are not backward compatible, can you please introduce new properties while keeping the existing ones and marking them as deprecated.

**Comment by orlangur** [comment]
@sivaschenko why do you think so? Accodring to code I see that `session` property is not used anywhere while `customerSession` was used before this change but not declared.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3667](https://jira.corp.magento.com/browse/ENGCOM-3667) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@iskolesnyk thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @iskolesnyk. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @iskolesnyk, here is your [Magento instance](https://i-19702-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19702-2-3-develop.instances.magento-community.engineering/admin](https://i-19702-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @iskolesnyk. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
