### PR TITLE
ASI handle custom product attributes which includes text field for used in functionality

### PR DESCRIPTION
**Pull request by Nazar65**
### Related Pull Requests
https://github.com/magento/adobe-stock-integration/pull/1460

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>
https://github.com/magento/adobe-stock-integration/issues/1420

### Manual testing scenarios (*)

1. Create a custom **Product Attribute**, type _Text Editor_
2. Create a new Product and add the previously created attribute 
3. From the added Attribute, insert an image from the Media Gallery and Save the Product
4. Go to Standalone Media Gallery and view the Image Details of the previously used image
 
**The image Used in Product should be displayed**

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
The decision was made to require adding any custom attributes that require synchronization to the configuration of the synchronizer. I.e. DI configuration of `Magento\MediaContentSynchronizationCatalog\Model\Synchronizer\Category` for category custom attributes

**Pull request closed without merging**
