### PR TITLE
delete code which doesn't have any sense here

### PR DESCRIPTION
**Pull request by AndreyChorniy**
### Description (*)
This PR delete unused code from template `Magento/Catalog/view/frontend/templates/product/listing.phtml`

### Fixed Issues (if relevant)

1. magento/magento2#25715: Product listing time taken profiling dump

### Manual testing scenarios (*)

1. Go to the category page (it should load properly, without issues) 
2. Go to the search result page (it should load properly, without issues)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-6345](https://jira.corp.magento.com/browse/ENGCOM-6345) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@AndreyChorniy thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed.

**Review by krzksz — COMMENTED** [review]
In my optinion this commit violates the following point of [Contribution Requirements:](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#requirements)
> 4. Commits must be accompanied by meaningful commit messages.

**Pull request merged**
