### PR TITLE
[Integration] Refactoring CheckoutAgreements fixtures

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR refactores CheckoutAgreements fixtures

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved!
Failing integration test looks not related to changes in this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7615](https://jira.corp.magento.com/browse/ENGCOM-7615) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Pull request merged**
