### PR TITLE
Prevent secure key failures if route front name is not equal to route ID

### PR DESCRIPTION
**Pull request by flancer64**
See https://github.com/magento/magento2/issues/7557

### CODE REVIEW

**Comment by dmanners** [comment]
Hi @flancer64 thank you for this PR. Before we process this further could you please check the failures in the travis build.

**Comment by flancer64** [comment]
Sorry guys, I checked errors but there are a lot of inappropriate usage of route ID instead of route front name and vice versa. I tried to fix them simply but I failed.

The best solution I found - don't use different route ID & front name. You can leave it "as is" and use "the best solution" too.

**Comment by dmanners** [comment]
@flancer64 thanks for the update. I will check here what the best option is to progress this and get back to you.

**Comment by dmanners** [comment]
@flancer64 unfortunately we cannot accept this in the current state. With all the tests failing and also there will need to be a lot of updates to the code base. Feel free to open a new PR if you have the time to make the updates required.

**Pull request closed without merging**
