### PR TITLE
Region field visible for Country when "Allow to Choose State if It is Optional for Country" is disabled

### LINKED ISSUE #30747: Region field visible for Country when "Allow to Choose State if It is Optional for Country" is disabled
### Preconditions (*)
1. Magento 2.4.1 and 2.4-develop
1. PHP 7.4

### Steps to reproduce (*)
1. In General Settings configure **Default Country** that doesn't support States (eg. Czech Republic)
1. In General Settings configure **Allowed countries** same as Default Country
1. Make sure that your Default Country isn't selected in **State is Required for** field
1. In General Settings configure **Allow to Choose State if It is Optional for Country* to *NO**
1. Navigate to storefront as a guest and add product to cart.
1. Go to Checkout page.

### Expected result (*)
1. Default Country is automatically selected in shipping address form and region field is hidden.

### Actual result (*)
1. Default Country is automatically selected in shipping address form but region input field is visible.

### Additional info from Engcom
According to the [documentation](https://docs.magento.com/user-guide/stores/state-options.html), when *Allow to Choose State if It is Optional for Country* is set to **No** - In countries where the state field is not required, omits the State field.

1. In General Settings set country that doesn't support States for Default Country and Allowed countries settings (eg. Czech Republic)
Default and allow
1. Make sure that your Default Country isn't selected in State is Required for field
state as required
1. In General Settings set Allow to Choose State if It is Optional for Country to NO
Allow to choose
1. Navigate to storefront as a guest and add product to cart.
1. Go to Checkout page.

**Actual result**
Default Country is automatically selected in shipping address form but region input field is visible.
Store

### PR DESCRIPTION
**Pull request by engcom-Kilo**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#30747

### Manual testing scenarios (*)

1. see magento/magento2#30747

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8428](https://jira.corp.magento.com/browse/ENGCOM-8428) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

### Manual testing scenario
1. In General Settings set country that doesn't support States for Default Country and Allowed countries settings (eg. Czech Republic)
Default and allow
2. Make sure that your Default Country isn't selected in State is Required for field
state as required
3. In General Settings set Allow to Choose State if It is Optional for Country to NO
Allow to choose
4. Navigate to storefront as a guest and add product to cart.
5. Go to Checkout page.

**Before** applying changes provided in this PR
Default Country is automatically selected in shipping address form but region input field is visible.
Store

**After** switching to the PR
Default Country is automatically selected in shipping address form and region field is hidden.
Region

**Comment by engcom-Kilo** [comment]
@magento import pull request to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@engcom-Kilo the pull request successfully imported.

**Pull request merged**
