### PR TITLE
[Backport] Fix documentation grammar errors and typos in actions.js

### PR DESCRIPTION
**Pull request by lewisvoncken**
### Original Pull Request 
 https://github.com/magento/magento2/pull/17462

### Description

Fix multiple errors in js docblocks for actions.js

### Fixed Issues (if relevant)

1. Improved docblock grammar and removed typos.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by okorshenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, thank you for the review.
[ENGCOM-3115](https://jira.corp.magento.com/browse/ENGCOM-3115) has been created to process this Pull Request

**Comment by okorshenko** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [Magento instance](https://i-18429-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-18429-2-3-develop.engcom.dev.magento.com/admin](https://i-18429-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by okorshenko** [comment]
Hi @lewisvoncken Thank you for code cleanup. The code looks better now 👍 
Please consider this comment for future contributions. Thank you!

https://github.com/magento/magento2/pull/18426#issuecomment-427636897

**Comment by lewisvoncken** [comment]
@okorshenko 

Thank you for your comment and I totally understand and will only sent it in from now on for the latest release line.

**Comment by magento-engcom-team** [comment]
Hi @lewisvoncken. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
