### PR TITLE
Add Customer Token Lifetime to graphql

### PR DESCRIPTION
**Pull request by codynguyen1**
### Description (*)
Add Customer Token Lifetime to graphQl

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. Create graphql storeConfig query
2. add oauth_access_token_lifetime_customer

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Hi @codynguyen1. Could you please add use case for this? Why lifetime is needed for client?

**Comment by codynguyen1** [comment]
Hi @lenaorobei  PWA are getting token to authorize customer, but the token's deadline is now 3600 seconds because the is no information sent from server, that would cause some problem (like cart is not authorized (invalid state change, etc..))

**Comment by lenaorobei** [comment]
Could you please open issue first?
We cannot understand the use case here. Why deadline is 3600 seconds?

**Comment by lenaorobei** [comment]
Closing this PR due to inactivity. Please feel free to reopen if you are going to continue working on it.
Thank you.

**Pull request closed without merging**
