### PR TITLE
Fix error on logo upload for Transactional Emails (#20091)

### PR DESCRIPTION
**Pull request by chaplynsky**
### Description (*)

Changed "fileUploader" to "imageUploader" on line 16.

### Fixed Issues (if relevant)

1. magento/magento2#20091: Fix error on logo upload for Transactional Emails

### Manual testing scenarios (*)

1. Go to Content>Theme>Design>Configuration>edit any theme>Transactional Emails
2. Upload logo

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20092) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @chaplynsky. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by davidverholen** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @davidverholen. Thank you for your request. I'm working on Magento instance for you

**Comment by davidverholen** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @davidverholen. Thank you for your request. I'm working on Magento instance for you

**Review by davidverholen — APPROVED** [review]

**Review by davidverholen — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @davidverholen, thank you for the review.
[ENGCOM-3799](https://jira.corp.magento.com/browse/ENGCOM-3799) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@chaplynsky thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by sivaschenko** [comment]
Hi @chaplynsky thank you for the contribution. There is an issue on the PR codebase:

Steps to reproduce:

- Log in to Admin panel;
- Go to Content->Design->Configuration;
- Click 'Edit' link in grid ;
- Click on "Transactional Emails" tab and select "Select from Gallery" button;
- Select any image and click on "Add Selected" button;
- Click "Save Configuration" button;

Actual Result:

Error: "email_logo does not contain field 'file'"

image

**Comment by chaplynsky** [comment]
@sivaschenko, I encounter issues with Select from Gallery elsewhere in the Admin panel, may actually open an Issue for that too... Can you check if this same issue exists in the stock 2.3 codebase? The upload didn't work at all before the change I committed, so this issue may not be caused by the PR codebase.

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [new Magento instance](https://pr-20092.instances.magento-community.engineering).
Admin access: [https://pr-20092.instances.magento-community.engineering/admin](https://pr-20092.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sivaschenko** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [Magento instance](https://i-20092-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20092-2-3-develop.instances.magento-community.engineering/admin](https://i-20092-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sivaschenko** [comment]
Hi @chaplynsky thanks for your response. Indeed, this problem affect all imageUploader fields and should be addressed in separate issue. We will process this pull request further.

**Comment by sivaschenko** [comment]
The problem with selecting from gallery is reported as a separate issue: https://github.com/magento/magento2/issues/21032

**Comment by chaplynsky** [comment]
@sivaschenko thanks for looking into this. Please let me know why the Travis CI build is failing. I'm not sure how to handle that, because this is my first pull request.

**Comment by davidverholen** [comment]
> 1) Magento\Ups\Model\CarrierTest::testCollectFreeRates
PHPUnit\Framework\Exception: Notice: Undefined index: GND in /home/travis/build/magento/magento2/dev/tests/integration/testsuite/Magento/Ups/Model/CarrierTest.php:84.

I've seen this error before, It should not be related to this pr

**Comment by sivaschenko** [comment]
@chadbean @davidverholen is right, Travis build fail is not related to the PR

**Pull request merged**
