### PR TITLE
Add a module manager to the Magento Framework API

### PR DESCRIPTION
**Pull request by navarr**
This is a useful addition for feature detection and enablement for third party modules (such as "activate this functionality if such and such GiftCard extension exists"

This is an update to PR #12677 to be based on 2.3

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @navarr. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by navarr** [comment]
#squashtoberfest

**Review by aleron75 — DISMISSED** [review]
We are encouraged to use strict typing. Thus, I suggest adding parameter type and return value for the `isEnabled()` method.

**Review by aleron75 — APPROVED** [review]
good job!

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-3260](https://jira.corp.magento.com/browse/ENGCOM-3260) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
@nvarr we would like to discuss this pull request on the public architecture discussion meeting on [May 29](https://github.com/magento/architecture/issues/165), it would be great if you can join and present the solution

**Comment by navarr** [comment]
@sivaschenko Alright.  I typically attend so that shouldn't be an issue.

**Comment by sivaschenko** [comment]
Pull request was approved to be merged to 2.3-develop at Public Architectural Discussion meeting https://github.com/magento/architecture/issues/165#issuecomment-497011809

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3260](https://jira.corp.magento.com/browse/ENGCOM-3260) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
