### PR TITLE
Fixed calling non exists order address->getCountry to getCountryId

### PR DESCRIPTION
**Pull request by krejcif**
Problem occurs when Authorize.net AVS is checking card holder against country which is blank.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=6974) <br/>All committers have signed the CLA.

**Comment by YevSent** [comment]
Hi, @magexo, thanks for your fix.
Could you cover your changes in `\Magento\Authorizenet\Model\Directpost::capture` and `\Magento\Authorizenet\Model\Directpost\Request::setDataFromOrder` by integration tests?

**Comment by krejcif** [comment]
Sorry, there are no resources for that.

**Comment by Ctucker9233** [comment]
Still not included in 2.1.10

**Pull request merged**
