### PR TITLE
MFTF: Refactoring AdminUrlRewritesForProductInAnchorCategoriesTest

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
AdminUrlRewritesForProductInAnchorCategoriesTest is refactored according to the best practices followed by MFTF.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)
Run AdminUrlRewritesForProductInAnchorCategoriesTest in the local environment and verified the test runs successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by dmytro-ch** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-28408.instances.magento-community.engineering).
Admin access: [https://pr-28408.instances.magento-community.engineering/admin_b1b0](https://pr-28408.instances.magento-community.engineering/admin_b1b0)
Login: `b7ae5747` Password: `83fc2154e154`
Instance will be terminated in up to 3 hours.

**Comment by dmytro-ch** [comment]
@magento run all tests

**Review by lbajsarowicz — DISMISSED** [review]
:heavy_check_mark: Thank you for your contribution

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7596](https://jira.corp.magento.com/browse/ENGCOM-7596) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello @kate-kyzyma.
Looks like there is an issue with one of the ancestor test.
Could you please evaluate and apply the appropriate changes if necessary?
`AdminUrlRewritesForProductInAnchorCategoriesTestAllStoreViewTest`.

```
[NOTE] Merge Error - Step could not be found in either TestXML or DeltaXML.                                          
 !                      Test: 'AdminUrlRewritesForProductInAnchorCategoriesTestAllStoreViewTest'        TestStep:                   
 !        'goToCategoryPage'    LinkedStep: 'seeValue4' in Test                                                            
 !        "AdminUrlRewritesForProductInAnchorCategoriesTestAllStoreViewTest"                                            
 !        /Users/kate/Sites/magento2/app/code/Magento/UrlRewrite/Test/Mftf/Test/AdminUrlRewritesForProductInAnchorCatego
 !        riesTest/AdminUrlRewritesForProductInAnchorCategoriesTestAllStoreViewTest.xml                                 
 !        Test configuration:                                                                                           
 !        {"tests":["AdminUrlRewritesForProductInAnchorCategoriesTestAllStoreViewTest"],"suites":null} 
```

Thank you!

**Comment by kate-kyzyma** [comment]
Hi @dmytro-ch 
I have updated the child test to fix the issue. Please, check.

Thanks.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7596](https://jira.corp.magento.com/browse/ENGCOM-7596) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
