### PR TITLE
[CMS] Improving the uploaded images styling view

### PR DESCRIPTION
**Pull request by eduard13**
### Description (*)

This PR fixes the styling issue for uploaded images.

### Fixed Issues (if relevant)

1. magento/magento2#20786: [CMS] File upload preview style issue
2. ...

### Manual testing scenarios (*)
1. Open a CMS page or block
2. Click on the Insert Image from the content field
3. Upload a new image or check the existing ones

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by eduard13** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @eduard13, here is your [new Magento instance](https://pr-20787.instances.magento-community.engineering).
Admin access: [https://pr-20787.instances.magento-community.engineering/admin](https://pr-20787.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-20787.instances.magento-community.engineering).
Admin access: [https://pr-20787.instances.magento-community.engineering/admin](https://pr-20787.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4051](https://jira.corp.magento.com/browse/ENGCOM-4051) has been created to process this Pull Request

**Pull request merged**
