### PR TITLE
Resolve Mass Delete Widget should have "Confirmation Modal"

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

 Mass Delete Widget should have "Confirmation Modal" like that:

image

We can see it is already in Functional Test (dev/tests/functional/tests/app/Magento/Widget/Test/TestCase/DeleteWidgetEntityTest.php), but it doesn't have the code to do the business.

image

=> We should open Confirmation Modal when delete widget by mass action.

### Manual testing scenarios (*)

1. Go to backend, create some widget
2. Select and choose mass action Delete widget.
3. Check the modal:

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by VladimirZaets** [comment]
Hi @edenduong. Thanks for collaboration. Why this test is green if it should already check this case?

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-6384](https://jira.corp.magento.com/browse/ENGCOM-6384) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @edenduong. Thank you for collaboration. I think we should cover it with functional tests (or update an existing one)

**Comment by edenduong** [comment]
@VladimirZaets : Thank you for reviewing. I will update functional test soon.

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@VladimirZaets  MFTF test added. Please review.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6384](https://jira.corp.magento.com/browse/ENGCOM-6384) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by slavvka** [comment]
@magento run Functional Tests EE

**Pull request merged**
