### PR TITLE
Avoid binding magnifier events in duplicate on resize

### LINKED ISSUE #30788: [Issue] Avoid binding magnifier events in duplicate on resize
This issue is automatically created based on existing pull request: magento/magento2#30695: Avoid binding magnifier events in duplicate on resize

---------
### Description
A browser resize event will trigger the magnifier to be re-initialised. This includes binding a fresh set of event listeners to the image so that the magnifier will show as expected (on click or hover). However, there is no mechanism to unbind the old event listeners, so each time the browser triggers a resize event these will stack.
This is made worse by the 'hover' event type triggering the 'mouseover' event immediately after adding a listener for the same. This means that each resize event will consume progressively more CPU, without any additional value.

### Related Pull Requests
*None*

### Fixed Issues
*None*

### Manual testing scenarios
1. Visit a product page with magnifier in use and configured for hover events
1. Observe the resting CPU usage of the page
1. Resize the viewport (either height or width)
1. Observe a spike in CPU usage, which subsides
1. Resize the viewport several times
1. Observe a progressively longer spike in CPU usage
1. Continue resizing the viewport and notice that CPU eventually (after \~8 resizes in my experience) caps out at 100% for an unacceptable amount of time (several minutes), rendering the page useless.

<details><summary>Before & after pictures from JavaScript profiler</summary>

Before:
Screenshot_2020-10-28_15-46-27

After:
Screenshot_2020-10-28_16-38-10

</details>

### Questions or comments
*None*

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fredden**
### Description
A browser resize event will trigger the magnifier to be re-initialised. This includes binding a fresh set of event listeners to the image so that the magnifier will show as expected (on click or hover). However, there is no mechanism to unbind the old event listeners, so each time the browser triggers a resize event these will stack.
This is made worse by the 'hover' event type triggering the 'mouseover' event immediately after adding a listener for the same. This means that each resize event will consume progressively more CPU, without any additional value.

### Related Pull Requests
*None*

### Fixed Issues
*None*

### Manual testing scenarios
1. Visit a product page with magnifier in use and configured for hover events
1. Observe the resting CPU usage of the page
1. Resize the viewport (either height or width)
1. Observe a spike in CPU usage, which subsides
1. Resize the viewport several times
1. Observe a progressively longer spike in CPU usage
1. Continue resizing the viewport and notice that CPU eventually (after \~8 resizes in my experience) caps out at 100% for an unacceptable amount of time (several minutes), rendering the page useless.

<details><summary>Before & after pictures from JavaScript profiler</summary>

Before:
Screenshot_2020-10-28_15-46-27

After:
Screenshot_2020-10-28_16-38-10

</details>

### Questions or comments
*None*

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30788: Avoid binding magnifier events in duplicate on resize

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE, Functional Tests CE

**Comment by ihor-sviziev** [comment]
@fredden good catch! Looks like it will be too hard to cover with automated test, so I  put label "auto-tests: not required"

**Comment by fredden** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8407](https://jira.corp.magento.com/browse/ENGCOM-8407) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by engcom-Oscar** [comment]
:heavy_check_mark: QA passed

Was checked case from Manual testing scenarios 
1. Visit a product page with magnifier in use and configured for hover events
1. Observe the resting CPU usage of the page
1. Resize the viewport (either height or width)
1. Observe a spike in CPU usage, which subsides
1. Resize the viewport several times
1. Observe a progressively longer spike in CPU usage
1. Continue resizing the viewport and notice that CPU eventually (after \~8 resizes in my experience) caps out at 100% for an unacceptable amount of time (several minutes), rendering the page useless.

<details><summary>Before & after pictures from JavaScript profiler</summary>

Before:
Screenshot_2020-10-28_15-46-27

After:
:x: **Before:**

:heavy_check_mark: **After:**

**Pull request merged**
