### PR TITLE
Add default empty array in constructor

### LINKED ISSUE #38165: [Issue] Add default empty array in constructor
This issue is automatically created based on existing pull request: magento/magento2#38163: Add default empty array in constructor

---------
### Description (*)

This class its constructor argument `$tagGenerators` is empty by default in PHP, so that via DI argument types in `di.xml` files the array is filled automatically. This actually means that - without any runtime configuration of this argument - the PHP class has a required argument `$tagGenerators`.

In my cases, this is breaking DI compile when the modules `Magento_DirectoryGraphQl` and `Magento_StoreGraphQl` are disabled (and actually a lot of people will disable this module if they are not building a headless shop). This PR is a simple but required fix.

### Related Pull Requests
None

### Fixed Issues (if relevant)
None

### Manual testing scenarios (*)
Install Magento 2. Next, add a composer replacement of `magento/module-store-graph-ql` and `magento/module-directory-graph-ql` and run `composer update` to remove these dependencies. Alternatively, just disable the modules `Magento_DirectoryGraphQl` and `Magento_StoreGraphQl`. Next, run `bin/magento setup:di:compile`. It should fail. With this patch, it should work.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by jissereitsma**
### Description (*)

This class its constructor argument `$tagGenerators` is empty by default in PHP, so that via DI argument types in `di.xml` files the array is filled automatically. This actually means that - without any runtime configuration of this argument - the PHP class has a required argument `$tagGenerators`.

In my cases, this is breaking DI compile when the modules `Magento_DirectoryGraphQl` and `Magento_StoreGraphQl` are disabled (and actually a lot of people will disable this module if they are not building a headless shop). This PR is a simple but required fix.

### Related Pull Requests
None

### Fixed Issues (if relevant)
None

### Manual testing scenarios (*)
Install Magento 2. Next, add a composer replacement of `magento/module-store-graph-ql` and `magento/module-directory-graph-ql` and run `composer update` to remove these dependencies. Alternatively, just disable the modules `Magento_DirectoryGraphQl` and `Magento_StoreGraphQl`. Next, run `bin/magento setup:di:compile`. It should fail. With this patch, it should work.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38165: Add default empty array in constructor

### CODE REVIEW

**Comment by jissereitsma** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
@magento create issue

**Review by ihor-sviziev — APPROVED** [review]

**Review by lbajsarowicz — APPROVED** [review]

**Review by torhoehn — APPROVED** [review]

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Failed `Functional Tests CE` is not related to PR Changes. Please refer to the below screenshot:

image

:heavy_check_mark: QA Passed

**Preconditions:**
- Disable the below modules or remove them from the composer.json:
`Magento_DirectoryGraphQl` and `Magento_StoreGraphQl`

**Manual testing scenario:**
1. Install Magento 2.4-develop 
2. Disable the modules `Magento_DirectoryGraphQl` and `Magento_StoreGraphQl` via the below command:
`bin/magento module:disable Magento_DirectoryGraphQl Magento_StoreGraphQl`
3. Then run the `bin/magento setup:upgrade` command.

**Actual Result:** :heavy_check_mark:
The below error has occurred:
image

**Before:** :heavy_multiplication_x: 
image

**After:** :heavy_check_mark:  
image

**Tested all the manual scenarios, no impact on regression testing.**

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Pull request merged**
