### PR TITLE
Status of cache types changed after running setup:upgrade

### LINKED ISSUE #28186: Running bin/magento setup:upgrade re-enables layout, block_html and full_page caches
### Preconditions (*)
1.Magento 2.4-develop

### Steps to reproduce (*)
1. Disable the caches by running: `bin/magento cache:disable block_html full_page layout`
2. Run: `bin/magento setup:upgrade`

### Expected result (*)
1. After setup:upgrade completes execution, the `block_html`, `full_page`, and `layout` caches are still disabled

### Actual result (*)
1. An "enabling caches" message appears in the CLI output of setup:upgrade:
```
Enabling caches:
Current status:
Array
(
    [layout] => 1
    [block_html] => 1
    [full_page] => 1
)
```
2. Those caches are re-enabled:
```
magento235$ bin/magento cache:status
Current status:
                        config: 1
                        layout: 1
                    block_html: 1
                   collections: 1
                    reflection: 1
                        db_ddl: 1
               compiled_config: 1
                           eav: 1
         customer_notification: 1
            config_integration: 1
        config_integration_api: 1
                google_product: 1
                     full_page: 1
             config_webservice: 1
                     translate: 1
                        vertex: 1
```

### LINKED ISSUE #29588: [Issue] Status of cache types changed after running setup:upgrade
This issue is automatically created based on existing pull request: magento/magento2#28191: Status of cache types changed after running setup:upgrade

---------

### Description (*)
Fixed the issue that running `bin/magento setup:upgrade` re-enables layout, block_html and full_page caches.

### Related Pull Requests

 NA

### Manual testing scenarios (*)

1. Disable cache types layout, block_html and full_page by running `bin/magento cache:disable block_html full_page layout`.
2. Run `bin/magento s:up`.
3. Enabling caches message displays in cli output and layout, block_html and full_page caches are enabled.
4. Expected result is those cache types should be disabled.

`Enabling caches:
Current status:
Array
(
    [layout] => 1
    [block_html] => 1
    [full_page] => 1
)`

### Questions or comments

NA

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by chandru-199**
### Description (*)
Fixed the issue that running `bin/magento setup:upgrade` re-enables layout, block_html and full_page caches.

### Fixed Issues (if relevant)
- Fixes #28186
- Fixes #29588

### Related Pull Requests

 NA

### Manual testing scenarios (*)

1. Disable cache types layout, block_html and full_page by running `bin/magento cache:disable block_html full_page layout`.
2. Run `bin/magento s:up`.
3. Enabling caches message displays in cli output and layout, block_html and full_page caches are enabled.
4. Expected result is those cache types should be disabled.

`Enabling caches:
Current status:
Array
(
    [layout] => 1
    [block_html] => 1
    [full_page] => 1
)`

### Questions or comments

NA

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29588: Status of cache types changed after running setup:upgrade

### CODE REVIEW

**Comment by chandru-199** [comment]
@magento run all tests

**Comment by chandru-199** [comment]
@magento run all tests

**Comment by orthener** [comment]
How to create patch for this?

**Comment by sidolov** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Hi @chandru-199,
I found that we actually have another solution for the same issue https://github.com/magento/magento2/pull/28491 and it seems to me better. 
I'm closing this PR as we have better solution. Thank you for contribution!

**Pull request closed without merging**
