### PR TITLE
[MFTF] Add AdminOpenCurrencyRatesPageActionGroup

### LINKED ISSUE #30783: [Issue] [MFTF] Add AdminOpenCurrencyRatesPageActionGroup
This issue is automatically created based on existing pull request: magento/magento2#30777: [MFTF] Add AdminOpenCurrencyRatesPageActionGroup

---------
This PR provides new `AdminOpenCurrencyRatesPageActionGroup`

### PR DESCRIPTION
**Pull request by Usik2203**
This PR provides new `AdminOpenCurrencyRatesPageActionGroup`

### Resolved issues:
1. [x] resolves magento/magento2#30783: [MFTF] Add AdminOpenCurrencyRatesPageActionGroup

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8432](https://jira.corp.magento.com/browse/ENGCOM-8432) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Pull request merged**
