### PR TITLE
Fix deprecation issues on PHP 8.1 found by MFTF tests

### PR DESCRIPTION
**Pull request by karyna-t**
### Description (*)
Fix deprecation warnings for PHP 8.1. compatibility.

### Related Issues
1. magento/magento2#34778

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Release Note

### CODE REVIEW

**Comment by andrewbess** [comment]
@magento run all tests

**Review by andrewbess — APPROVED** [review]
Hello @karyna-tsymbal-atwix 
Thank you for your contribution
It look good for me ✔️

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, thank you for the review.
[ENGCOM-9369](https://jira.corp.magento.com/browse/ENGCOM-9369) has been created to process this Pull Request
:eight_spoked_asterisk: @andrewbess, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by xmav** [comment]
pending delivery https://github.com/magento-commerce/magento2ce/pull/7331

**Pull request merged**
