### PR TITLE
[Backport] Remove double semicolon from the style sheets.

### PR DESCRIPTION
**Pull request by gelanivishal**
### Original Pull Request
https://github.com/magento/magento2/pull/15795

### Description

Remove double semicolon from the style sheets.

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios

N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by sidolov** [comment]
@gelanivishal , please, make the same changes as an original PR, currently, your PR contains extra changes.

**Comment by gelanivishal** [comment]
@sidolov There is coding standard changes. I have just removed extra space and tab issue. Please check it.

Thank you.

**Comment by gelanivishal** [comment]
@sidolov Have you checked my message?

Thank you.

**Comment by sidolov** [comment]
Hi @gelanivishal , please, sort all CSS properties alphabetically according to our [LESS coding standards](https://devdocs.magento.com/guides/v2.2/coding-standards/code-standard-less.html#properties)

**Comment by gelanivishal** [comment]
@sidolov Is there any online tool?

**Comment by sidolov** [comment]
@gelanivishal , unfortunately, our team doesn't provide any tools for that case. You may find the tool by yourself or fix issues manually.

**Comment by gelanivishal** [comment]
@sidolov Please review the latest commit.

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your contribution. 
We will aim to release these changes as part of 2.1.15. 
Please check the release notes for final confirmation.

**Pull request merged**
