### PR TITLE
vimeo video move to oEmbed

### LINKED ISSUE #31753: Vimeo Product Video Not Found
### Preconditions (*)

1. It was previoulys working, tested in Magento 2.4.0. 

### Steps to reproduce (*)
1. So upgrade to 2.4.1. Do not upgrade and remain in 2.4.0 in another cloned enviroment
2. Go to product page
3. Insert a product video in product page using the regular insert video button. It previously worked. 
4. Few days later try to do it again. Vimeo returns 404 
5. Try to upload to another Vimeo account to check if a setting may be blocking. No, it returns 404
6. curl -i https://vimeo.com/videoId. It returns 200 and a response with json and ajax call
7. Try to get in browser Vimeo dowload a file a does not print information on client
8. Try the same in postman, it returns Json
9. Try to debug Magento
10. Check if it is Cors. Vimeo Cors is declared in Csp policy

### Expected result (*)

1.Insert url in Product Video and it is found
2. Video displays in fotorama

### Actual result (*)

1. Video not found. Unable to display Vimeo on Fotorama

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by omaxmo**
Vimeo Simple API is no longer maintained or supported

### Description (*)
Vimeo Simple API is no longer maintained or supported

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31753

### Manual testing scenarios (*)

1. Go to a product in adminpanel
2. Click Images And Videos 
3. Click Add video
4. Url - https://vimeo.com/76979871

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by omaxmo** [comment]
@magento run all tests

**Comment by omaxmo** [comment]
@magento run all tests

**Comment by omaxmo** [comment]
@magento run Functional Tests CE

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by zakdma** [comment]
Bug was fixed ins scope of internal jira ticket MC-40463

**Comment by ihor-sviziev** [comment]
FYI here is a commit that fixes this issue https://github.com/magento/magento2/commit/f2231f8d953bb650c3462a824716fd8972c6bb6c
As the internal team fixed the issue - I'm closing this PR as not relevant anymore

**Pull request closed without merging**
