### PR TITLE
Extend exception message

### PR DESCRIPTION
**Pull request by orozcodiaz**
Update exception messages to provide more detailed information on errors

### CODE REVIEW

**Review by pmclain — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @pmclain, thank you for the review.
[ENGCOM-6675](https://jira.corp.magento.com/browse/ENGCOM-6675) has been created to process this Pull Request
:eight_spoked_asterisk: @pmclain, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by pmclain — CHANGES_REQUESTED** [review]
Would you please update this translation string in https://github.com/magento/magento2/blob/959f9703dacaf7a2a73cf28fb7610434aad34e45/app/code/Magento/Analytics/i18n/en_US.csv#L10 to match?

**Comment by orozcodiaz** [comment]
> Would you please update this translation string in
> 
> https://github.com/magento/magento2/blob/959f9703dacaf7a2a73cf28fb7610434aad34e45/app/code/Magento/Analytics/i18n/en_US.csv#L10
> 
> to match?

Done

**Comment by ihor-sviziev** [comment]
I believe this could be tested with unit test.
@oroskodias will you be able to cover your changes with unit test?

**Comment by orozcodiaz** [comment]
> I believe this could be tested with unit test.
> @oroskodias will you be able to cover your changes with unit test?

Not sure I could do that. I don't have enough experience.

**Review by pmclain — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @pmclain, thank you for the review.
[ENGCOM-6675](https://jira.corp.magento.com/browse/ENGCOM-6675) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
