### PR TITLE
33160: Changed for using Null coalescing operator

### LINKED ISSUE #33160: Element translations per module do not work
### Preconditions (*)

1. Magento 2.4.2
2.

### Steps to reproduce (*)

According to documentation: _You can translate the same element in different ways for different modules:_ 
https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/translations/theme_dictionary.html

1. Create store view and set locale
2. Create translation file
3. Add:
```
"Add to Cart", "Translation Base"
"Add to Cart", "Translation 1", module, Magento_Catalog
"Add to Cart", "Translation 2", module, Magento_Wishlist
```

### Expected result (*)

1. 'Add to cart' string is translated as `Translation 1` on catalog pages and `Translation 1` on wishlist pages

### Actual result (*)

1. Always the last translation is taken into account
trans

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by AZiniukhin**
### Description (*)

I have rewritten some of the code to make PHP work more natively.
In the Csv class ( lib/internal/Magento/Framework/File/Csv.php ), duplicate translations are forcibly overwritten in the "getDataPairs" method, so the last translation in the queue will be displayed on the frontend. This functionality remains unchanged since Magento version 2.0.0, also requires Devdocs adjustment.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33160

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by AZiniukhin** [comment]
@magento run all tests

**Comment by AZiniukhin** [comment]
@magento run functional tests

**Comment by AZiniukhin** [comment]
@magento run all tests

**Comment by AZiniukhin** [comment]
@magento run functional tests

**Comment by AZiniukhin** [comment]
@magento run functional tests

**Review by Den4ik — CHANGES_REQUESTED** [review]
Please review and fix failed tests

**Comment by AZiniukhin** [comment]
Unfortunately, at the moment the tests do not work very correctly, and the line I changed does not change the functionality

**Comment by AZiniukhin** [comment]
@magento run functional tests

**Comment by AZiniukhin** [comment]
@magento run functional tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @AZiniukhin,

Thank you for your contribution!

Will check the review comments and work on it accordingly.

Thank You!

**Comment by engcom-Charlie** [comment]
Hi @AZiniukhin

The committed changes of this PR, it is not fixing the issue.

On PR branch we can still always see the last translation  eg. here “Translation 2”. Transaction 2 is getting displayed on Catalog as well as on Wishlist page.

Please confirm that are you working on the actual solution. 

Thank You in Advance!

**Comment by engcom-Charlie** [comment]
Hi @AZiniukhin,

Thank you for your contribution!

As I have mentioned in [comment](https://github.com/magento/magento2/pull/34093#issuecomment-937815225), this PR is not handling the fix for the mentioned fix [issue](https://github.com/magento/magento2/issues/33160).

As the code changes are not addressing the linked issue hence closing this PR. 

If you want to continue with these code modifications, please raise new PR and create separate new issue for it. 

Thank you!

**Pull request closed without merging**
