### PR TITLE
Remove deprecated framework interfaces

### PR DESCRIPTION
**Pull request by vlmed**
### Description (*)
I created a separate commits for each interface from issue. Since each interface had many dependencies that needed to be edited. In my opinion, it will be easier to review PR.
What done:
**1. `ilb/internal/Magento/Framework/App/Action/HttpHeadActionInterface.php`**
    - HttpHeadActionInterface was removed.
    - All dependency have been fixed.
**2. lib/internal/Magento/Framework/App/TemplateTypesInterface.php**
    - This interface implements 5 classes end extends  `Magento\Framework\Mail\TemplateInterface`.  And it has comment 
       `@deprecated 101.0.0 because of incorrect location`. 

According to the dependencies of  `lib/internal/Magento/Framework/App/TemplateTypesInterface.php` and comment I moved this interface to `Magento\Framework\Mail` namespace instead of removing.

**3. lib/internal/Magento/Framework/Filesystem/ExtendedDriverInterface.php**
    - `ExtendedDriverInterface` has been removed and implementation moved to `DriverInterface`.
    - **But the classes implementing `DriverInterface` were broken.**  Because this requires the implementation of the `getMetadata()` method.
  
**4. lib/internal/Magento/Framework/Image/Adapter/UploadConfigInterface.php** 
    - `UploadConfigInterface` has been removed.
    - `Magento\Framework\Image\Adapter\Config` implements this interface. So I removed unused deprecated methods `getMaxWidth()` and `getMaxHeight()` and unused deprecated contants from this class.
    - All dependencies have been fixed.
    

**5. `lib/internal/Magento/Framework/Module/Output/ConfigInterface.php`**
    - `ConfigInterface` has been removed;
    - `Magento\Framework\Module\Output\Config` is deprecated and implements this interface. So I removed it too. This class is using only in the class `Magento\Framework\Module\Manage`. 
    - I changed the behaviour of the deprecated method `Magento\Framework\Module\Manage::isOutputEnabled`. I removed the code belonging to the class `Magento\Framework\Module\Output\Config` from the `isOutputEnabled` method.
    

**6. `lib/internal/Magento/Framework/Option/ArrayInterface.php`**
    - `ArrayInterface.php` has been removed;
    - All dependencies have been fixed;

**7.  `lib/internal/Magento/Framework/Session/SidResolverInterface.php`**
    -  `SidResolverInterface` has been removed;
    -  `Magento\Framework\Session\SidResolver` is deprecated and implements this interface. SIDs in URLs are no longer used. So I removed this class too.
    -  I removed `Magento\Framework\Session\SidResolver` from all classes where it was
   

**8. **`lib/internal/Magento/Framework/View/Asset/Bundle/ConfigInterface.php`**
    -  `ConfigInterface` has been removed.
    -  I also removed deprecated unused classes that are associated with each other and this interface:
        - `Magento\Framework\View\Asset\Bundle\Config`
        - `Magento\Framework\View\Asset\Bundle\Manager`
        - `Magento\Framework\View\Asset\Bundle`
        - `Magento\Framework\View\Test\Unit\Asset\Bundle\ManagerTest`
        - `Magento\Framework\View\Test\Unit\Asset\BundleTest`
        
**9. `lib/internal/Magento/Framework/View/Element/UiComponent/Config/ManagerInterface.php`**
       - `ManagerInterface` has been removed;
       - `Magento\Ui\Model\Manager` is deprecated and implements this interface. So I removed it too. This class is using only in the class `Magento\Framework\View\Element\UiComponentFactory`. 
       - Some constants from `ManagerInterface` are using in the class  `Magento\Framework\View\Element\UiComponentFactory`. So i moved them to the class `UiComponentFactory`
       - All dependencies has been fixed;
      
**10. `lib/internal/Magento/Framework/MessageQueue/ConfigInterface.php` **
 In most cases this interface is only passed in the constructor and is not used.
   But there are a few places where it or its constants are still used.
Used in: 
 - `Magento\MessageQueue\Console\ConsumerListCommand`
 - `Magento\Framework\MessageQueue\Code\Generator\Config\RemoteServiceReader\MessageQueue` 
 - `Magento\Framework\MessageQueue\Config\Consumer\ConfigReaderPlugin`
 - `Magento\Framework\MessageQueue\Config\Publisher\ConfigReaderPlugin`
 - `Magento\Framework\MessageQueue\Config\Reader\Env\Validator`
 - `Magento\Framework\MessageQueue\Config\Reader\Xml\Converter\TopicConfig`
 - `Magento\Framework\MessageQueue\Config\Topology\ConfigReaderPlugin`

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/512
https://github.com/magento/partners-magento2b2b/pull/558
https://github.com/magento/inventory/pull/3294
https://github.com/magento/magento2-page-builder/pull/735
https://github.com/magento/magento2-page-builder-ee/pull/187

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32062

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by coderimus** [comment]
@magento run all tests

**Comment by coderimus** [comment]
@magento run all tests

**Comment by vlmed** [comment]
Hello @sivaschenko 
I faced with problem when some of the Interfaces have dependencies.
Please, also read description to PR, And write to me whether I'm moving in the right direction or not.

And I want to ask what to do in these cases

1. lib/internal/Magento/Framework/App/TemplateTypesInterface.php

Implements this interface:
 - `Magento\Email\ModelAbstractTemplate`
 - `Magento\Newsletter\Model\Queue`

And many classes use constants from this interface
I think we can move it to `Magento\Framework\Mail\` namespace

2. lib/internal/Magento/Framework/Filesystem/ExtendedDriverInterface.php

I moved `getMetadata()` method to `Magento\Framework\Exception\FileSystemException\DriverInterface`.
But the classes implementing `DriverInterface` were broken. 
Because this requires the implementation of the `getMetadata()` method.

3. lib/internal/Magento/Framework/MessageQueue/ConfigInterface.php
In most cases this interface is only passed in the constructor and is not used.
   But there are a few places where it or its constants are still used.
Used in: 
 - `Magento\MessageQueue\Console\ConsumerListCommand`
 - `Magento\Framework\MessageQueue\Code\Generator\Config\RemoteServiceReader\MessageQueue` 
 - `Magento\Framework\MessageQueue\Config\Consumer\ConfigReaderPlugin`
 - `Magento\Framework\MessageQueue\Config\Publisher\ConfigReaderPlugin`
 - `Magento\Framework\MessageQueue\Config\Reader\Env\Validator`
 - `Magento\Framework\MessageQueue\Config\Reader\Xml\Converter\TopicConfig`
 - `Magento\Framework\MessageQueue\Config\Topology\ConfigReaderPlugin`

**Comment by vlmed** [comment]
@magento run all tests

**Comment by vlmed** [comment]
@magento run all tests

**Comment by vlmed** [comment]
@magento run all tests

**Comment by vlmed** [comment]
@magento run all tests

**Pull request closed without merging**
