### PR TITLE
Fixed the prepare items method for configurable products

### PR DESCRIPTION
**Pull request by tephereth**
### Description

Trying to fix the issue of [MSI #1335](https://github.com/magento-engcom/msi/issues/1335) we discovered a problem related to the deleted order items in the `prepareItems()` method inside the `ShipmentFactory` class.
I've noticed that the range of deleted order items processed by the mentioned method was too wide because it's supposed to delete only virtual and bundle items with products not shipped separately.
The previous condition checked wether the product was virtual or had a parentId and not separately shipped, but this check deleted also simple products related to configurables introducing an issue with shipments for configurable products.
My proposed change would check if the product is virtual or bundle (not shipped seperately) to delete from processed items.
This issue doesn't have any consequence in 2.2 and 2.3 because the method `getAllItems()` of entity shipment is never used inside the core modules; but it will affect the MSI classes related to the `SourceDeductionProcessor` where this method is used to cycle the shipment items.
This is the backport of this PR https://github.com/magento/magento2/pull/16004 for the `2.3-develop`

### Fixed Issues (if relevant)

Fixed: [MSI #1335](https://github.com/magento-engcom/msi/issues/1335) with PR [MSI#1394](https://github.com/magento-engcom/msi/pull/1394)

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @tephereth. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by orlangur — APPROVED** [review]
@sidolov please check this logic also, as you changed it in https://github.com/tephereth/magento2/commit/a39941683a52e03a5feeb192ff261dd15dee3b02#diff-cac368f9ea0a41117d9d92385dce8fba as well.

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-2141](https://jira.corp.magento.com/browse/ENGCOM-2141) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@tephereth thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by sidolov** [comment]
Hi @tephereth , @orlangur, I found that we have several failed tests in EE functionality, especially in RMA (caused by incorrect filtering of items during preparation). I reviewed the issue from PR description, as I understand the problem is an incorrect fixture for integration test. Why we fixed the shipment factory instead of invalid fixture? 
Thank you!

**Comment by tephereth** [comment]
Hi @sidolov, in this particular case the problem wasn't in the fixture: the broken test, reported as issue in MSI, revealed a deeper problem involving the items filter for the stock in the shipping order of a configurable product.

**Pull request closed without merging**
