### PR TITLE
Unit test for SaveOrderAfterSubmitObserver

### PR DESCRIPTION
**Pull request by mmezhensky**
### Description (*)

This PR adds unit test that covers Magento\Paypal\Observer\SaveOrderAfterSubmitObserver

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6985](https://jira.corp.magento.com/browse/ENGCOM-6985) has been created to process this Pull Request

**Comment by dmytro-ch** [comment]
Please note, the Magento Health Index is relevant to the existing implementation of `Magento\Paypal\Observer\SaveOrderAfterSubmitObserver`.

**Comment by engcom-Delta** [comment]
**Notice:** QA not applicable

**Comment by engcom-Charlie** [comment]
The **Health index** check failed, it causes is a using `Magento\Framework\Registry` class. It needs to approve.

**Pull request closed without merging**
