### PR TITLE
MFTF: Add `<magentoCron` instruction - CatalogImportExport / CatalogInventory / CatalogRule

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Adding `<magentoCron` which triggers partial reindex to have the created products in the index.
That should fix most of the issues related to false-negatives in Functional Tests.

### Fixed Issues (if relevant)
1. magento/magento2#27320

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lenaorobei** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Wow... now we have too many conflicts here. Could you resolve conflict?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by lbajsarowicz** [comment]
I'm going to help with review of the failures, as there can be some hidden dependency on other cron group than just index

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @lbajsarowicz,
I see that now MFTF tests are constantly failing on this PR, seems like import/export module requires running message queue to process some files.

Please update your PR

**Comment by lbajsarowicz** [comment]
@ihor-sviziev You are right - for some of the tests it's related to the Queues.
I'm going to review them and change Cron job type from `index` to general Cron.

**Review by ihor-sviziev — APPROVED** [review]
Unit test failures are not related to changes from this PR

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7472](https://jira.corp.magento.com/browse/ENGCOM-7472) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
**Notice:** QA not applicable

**Comment by engcom-Echo** [comment]
@magento run Unit Tests

**Pull request merged**
