### PR TITLE
Update nginx.config.sample to exclude php5-fpm

### PR DESCRIPTION
**Pull request by sean-breeden**
### Description
M2.2.x is not compatible with php5.x so there's no reason to include it as an option in the nginx.config.sample. Refer to: https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html

### Fixed Issues (if relevant)
This does not fix any issues. However, it does prevent someone from thinking that M2.2.x is compatible with php5.

### Manual testing scenarios
No tests needed.

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16883) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @sean-wcb. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by miguelbalparda** [comment]
Thanks for your contribution @sean-wcb! I'll process this one and let you know if we have any questions.

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-2407](https://jira.corp.magento.com/browse/ENGCOM-2407) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@sean-wcb thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @sean-wcb. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.6. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
