### PR TITLE
ISSUE-39053 Move publish() call outside of open DB transaction, fix for operations to exists in DB before scheduling bulk

### LINKED ISSUE #39053: Magento\Framework\MessageQueue\PublisherInterface::publish() should never (ever) be called from code which is inside of active DB transaction
### Preconditions and environment

- Magento version: any version

### Steps to reproduce

If queue message is published inside of open DB transaction, and message consumer processes it faster then DB transaction is commited, then message consumer (which is separate process from publisher) has not consistent view on data in DB, which leads to bugs.

### Expected result

Queue messages can only be published, if calling code is NOT inside of active DB transaction.

### Actual result

Queue messages ARE published, when calling code IS inside of active DB transaction. 

Example: https://github.com/magento/magento2/blob/6f4805f82bb7511f72935daa493d48ebda3d9039/app/code/Magento/AsynchronousOperations/Model/BulkManagement.php#L131
```
            $this->entityManager->save($bulkSummary);

            $this->publishOperations($operations);

            $connection->commit();
```

### Additional information

Problem can be resolved (in ideal scenario) by adding before plugin on interface Magento\Framework\MessageQueue\PublisherInterface::publish(), which checks if getTransactionLevel() on any active DB connection is not greater than 0.

This would probably be backward-incompatible change.

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by pczerkas**
### Related Pull Requests

https://github.com/magento/magento2/commit/d096342f0d259e3bfca66d6d6c4ca3caef858a3b

### Fixed Issues (if relevant)

1. Fixes magento/magento2#39053

### CODE REVIEW

**Comment by pczerkas** [comment]
@magento run all tests

**Comment by 93kamikaze** [comment]
@magento run all tests

**Comment by pczerkas** [comment]
https://github.com/magento run all tests

**Comment by pczerkas** [comment]
@magento run all tests

**Comment by pczerkas** [comment]
@magento run all tests

**Comment by pczerkas** [comment]
@magento run all tests

**Comment by pczerkas** [comment]
@magento run all tests

**Comment by pczerkas** [comment]
@magento run all tests

**Pull request closed without merging**
