### PR TITLE
#32369 GraphQL: Order item should contain product images

### LINKED ISSUE #32369: Order item should contain product images
As a developer I want to have a convenient way to load product images of ordered product, so I don't have to do multiple queries and my PWA app is performant.

AC
* OrderItemInterface exposes product images

Note: I think we should add variant: ProductInterface field to an order item and do similar in other cases (wishlist, gift registry, purchase order, etc). Need to make sure Nishant and performance team are ok with this approach.

### PR DESCRIPTION
**Pull request by khrystynastolbova**
### Description (*)
ProductInterface field  was added to an order item

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32369

### Manual testing scenarios (*)

Query:
```
{
  customer {
    orders {
      items {
        items {
          id
          product {
            image {
              label
            }
            small_image {
              label
            }
          }
        }
      }
    }
  }
}
```
Знімок екрана 2021-03-11 о 08 50 54

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @khrystynastolbova,

Thanks for the contribution!

Please resolve the conflicts so that we can move further with the review process. Meanwhile we are moving this PR `On Hold`.

Thanks

**Comment by ckshen8** [comment]
@cpartica any updates around this commit?  My dev @khalilbensaid96 is trying to show product images in the order list but graphql isn't exposing the product images in that scenario.  Thanks.

**Comment by ckshen8** [comment]
@khrystynastolbova did you end up resolving the conflict and making it work?

**Comment by khrystynastolbova** [comment]
> @khrystynastolbova did you end up resolving the conflict and making it work?

Hello @ckshen8!
As I see these changes have already been merged from another commit https://github.com/magento/magento2/commit/da53de62afe5ba0afa91b1e60cca5b5b7c04fbb8
The changes should be available in version 2.4.7

**Comment by engcom-Dash** [comment]
As per https://github.com/magento/magento2/pull/32433#issuecomment-2108776851, Closing this PR since changes have already been merged from another commit https://github.com/magento/magento2/commit/da53de62afe5ba0afa91b1e60cca5b5b7c04fbb8

**Pull request closed without merging**
