### PR TITLE
Shipping radio button reorder#30257

### LINKED ISSUE #30257: [Clone MC-35417]Radio buttons are not displayed in the “Payment & Shipping Information” section in the case of reorder by Admin
**Preconditions:**
* Magento EE 2.3.6, EE 2.3.7-alpha2
* A Customer account with shipping address and a billing address is created
* A Simple Product is created
* Several delivery methods are configured
* At least one order is created

**Steps to Reproduce:**
* Go to Magento Admin panel > Sales > Orders
* Select the created order
* Click the “View” link
* Click the “Reorder” button
* Scroll down the page to the “Payment & Shipping Information” section
* Click the “Click to change shipping method”

**(/) Expected results:**

The list of delivery methods with radio buttons should appear
 image

*(see the attached EE 2.4.1-alpha4. ADMIN REORDER RADIO BUTTONS EXPECTED.png)*

**(x) Actual results:**

The list of delivery methods without radio buttons appears
 image

*(see the attached  EE 2.4.1-alpha4. ADMIN REORDER RADIO BUTTONS ACTUAL.png*
                                   *EE 2.4.1-alpha4. ADMIN REORDER RADIO BUTTONS.mp4)*

### PR DESCRIPTION
**Pull request by gixid192**
### Description (*)
In Admin, in reorder page, click the link/button `Click to change shipping method` doesn't show radio buttons to select shipping methods.

### Fixed Issues (if relevant)
Fixes magento/magento2#30257

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by gixid192** [comment]
@magento run all tests

**Comment by gixid192** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by eduard13** [comment]
@magento give me test instance

**Comment by gixid192** [comment]
Hi @eduard13 
The Functional Tests B2B failed but the error is from frontend, what I changed is in admin. Could you help take a look at this too?

**Comment by eduard13** [comment]
@magento run Functional Tests B2B

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @gixid192, thank you for your contribution. Due to [Magento Definition of Done](https://devdocs.magento.com/contributor-guide/contributing_dod.html#automated-tests) all new changes should be covered by tests, so could you also provide a [MFTF](https://devdocs.magento.com/mftf/docs/getting-started.html) test coverage for the provided fix?

Thank you.

**Comment by gixid192** [comment]
Hi @eduard13 
The root cause of this issue is the positions of the radio and label are different from the CSS.

I just move the code around to meet the requirement. This is core Magento code, I didn't add any new code. So I think it already has tests covered?

**Comment by eduard13** [comment]
Thank you for clarifying it. Let's wait for Functional Tests B2B results.

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8908](https://jira.corp.magento.com/browse/ENGCOM-8908) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@gixid192 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Oscar** [comment]
:heavy_check_mark: QA passed

Was checked case by next steps from Manual testing scenarios:
**Preconditions:**
* Magento EE 2.4.0, EE 2.4.1-alpha4, EE 2.4.2-beta1 is installed, should be actual for CE
* A Customer account with shipping address and a billing address is created
* A Simple Product is created
* Several delivery methods are configured
* At least one order is created
 
 **Steps to Reproduce:**
* Go to Magento Admin panel > Sales > Orders
* Select the created order
* Click the “View” link
* Click the “Reorder” button
* Scroll down the page to the “Payment & Shipping Information” section
* Click the “Click to change shipping method”

:x: **Before:**
The list of delivery methods appears without radio buttons 
Screenshot from 2021-03-09 13-44-45


:heavy_check_mark: **After:**
The list of delivery methods appears with radio buttons
Screenshot from 2021-03-09 14-16-45

**Pull request merged**
