### PR TITLE
Remove unused mixin code

### PR DESCRIPTION
**Pull request by Mayur1510**
### Description

Removed unused mixin code from core file(lib).

### Fixed Issues (if relevant)

1. magento/magento2#15060: .lib-layout-width mixin not available?

### Manual testing scenarios

N/A

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18219) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18219) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Mayur1510<br/>:x: Ravi Dudhara<hr/>**Ravi Dudhara** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by magento-engcom-team** [comment]
Hi @Mayur1510. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sidolov** [comment]
Hi @Mayur1510, looks like you made a commit with the different email than in your GitHub profile, please add email from the commit to your profile or make a new commit with an email from your GitHub profile and, please, sign CLA, otherwise, we can't process your pull request.

**Comment by sidolov** [comment]
Hi @Mayur1510 , will you fix the CLA issue in this PR? 
Thank you!

**Comment by sidolov** [comment]
Hi @Mayur1510 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
