### PR TITLE
magento/magento2#1838 customer export missing entity_id #44685

### PR DESCRIPTION
**Pull request by keyurshah070**
### Fixed Issues (if relevant)

1. magento/magento2#1838: customer export missing entity_id
2. Added customer entity_id on customer export

### Manual testing scenarios

1. Export with customer and its data and getting customer entity id in excel file

Please check attached sample screenshot of customer
customer_export_image

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by ishakhsuvarov** [comment]
Hi @keyurshah070 
I have checked the PR manually, and export file seems to contain the `entity_id` field as expected. 

However, this file can not be re-imported again, as there is not processing for this field. Error is returned to the user: `Column names: "_entity_id" are invalid`.

Could you please check this?
Thank you.

**Comment by keyurshah070** [comment]
Hi @ishakhsuvarov 

What do I need to do with this field on re-import? Any suggestions?

Thanks

**Comment by ishakhsuvarov** [comment]
@keyurshah070 As described in the initial ticket magento/magento2#1838 – it may be used to update customer information based on id.

**Comment by ishakhsuvarov** [comment]
@keyurshah070 We are closing this PR for now due to inactivity.  
Please reopen and update if you wish to continue working on it.
Thank you.

**Pull request closed without merging**
