### PR TITLE
Magento modules and theme less improvements.

### LINKED ISSUE #30716: [Issue] Magento modules and theme less improvements.
This issue is automatically created based on existing pull request: magento/magento2#30715: Magento modules and theme less improvements.

---------

### Description (*)

Magento modules and theme less improvements with proper mixin(`.lib-css()` and proper `@font-weight__XXXX` variable) usage available on magento defualt UI library at https://magento-devdocs.github.io/magento2-ui-library/typography.html#typography-variables.

### Related Pull Requests

N/A

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by pratiksangani**
### Description (*)

Magento modules and theme less improvements with proper mixin(`.lib-css()` and proper `@font-weight__XXXX` variable) usage available on magento defualt UI library at https://magento-devdocs.github.io/magento2-ui-library/typography.html#typography-variables.

### Related Pull Requests

N/A

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30716: Magento modules and theme less improvements.

### CODE REVIEW

**Comment by pratiksangani** [comment]
@magento create issue

**Comment by pratiksangani** [comment]
@magento run all tests

**Comment by pratiksangani** [comment]
Sure @ihor-sviziev,

The .lib-css() mixin is used to set any css property if there is a value passed to it by a variable. Also .lib-css() can add -ms-, -webkit- and -moz- prefixes if needed by passing third parameter as 1.
If the variable is set to false, the .lib-css() mixin will add nothing to the code. And with respect to my this PR, If I set available less variable instead of its direct value on any less, then It'll be easy for child theme modification by just changing that variable value. All affected usage will be updated automatically.

Magento have already defined default font-weight variables at <root>/lib/web/css/source/lib/variables/_typography.less:42
So I thought its better to use it only.

Reference: https://magento-devdocs.github.io/magento2-ui-library/utilities.html#libcss && 
Also find font-weight variables here: https://magento-devdocs.github.io/magento2-ui-library/variables.html

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8415](https://jira.corp.magento.com/browse/ENGCOM-8415) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @pratiksangani,
Could you explain what is the use case of using `lib-css`? 
AFAIK the font-weight is natively supported by all the browsers.

**Comment by ihor-sviziev** [comment]
@pratiksangani any updates?

**Comment by ihor-sviziev** [comment]
@pratiksangani  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
