### PR TITLE
Removed two time zlib.output_compression on section

### PR DESCRIPTION
**Pull request by samuel20miglia**
### Description (*)
in the .htaccess removed two times zlib.output_compression on section

### Fixed Issues (if relevant)
nothing

### Manual testing scenarios (*)
got to pub. folder
open the file .htaccess check if there is duplicate sections

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22026) <br/>All committers have signed the CLA.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4604](https://jira.corp.magento.com/browse/ENGCOM-4604) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@samuel20miglia thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by soleksii** [comment]
QA not applicable

**Pull request merged**
