### PR TITLE
Property "ShowDefaultNotificationMessage" does not have accessor method

### LINKED ISSUE #29707: [Issue] Property "ShowDefaultNotificationMessage" does not have accessor method
This issue is automatically created based on existing pull request: magento/magento2#26056: Property "ShowDefaultNotificationMessage" does not have accessor method

---------

### Description (*)

If you want create queue which will triggered whem you will save product in the admin (I created plugin afterSave for the Magento\Catalog\Model\ResourceModel\Product::save()), you will get critical error - Property "ShowDefaultNotificationMessage" does not have accessor method "setShowDefaultNotificationMessage" in class "Magento\CatalogInventory\Api\Data\StockItemInterface". Even if you do not use this interface in your extension, you still get an error.

### Manual testing scenarios (*)

1. Create simple rabbitmq queue extension
2. Create plugin afterSave for the Magento\Catalog\Model\ResourceModel\Product::save()
3. Set up consumer <consumer name="YourConsumerName" queue="name_product_save" connection="amqp" handler="Name\Queue\Model\Product\SaveConsumer::processMessage"/>
3. Save product in the admin panel
4. Run php bin/magento queue:consumers:start YourConsumerName
5. Got error)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ityetti**
### Description (*)

If you want create queue which will triggered whem you will save product in the admin (I created plugin afterSave for the Magento\Catalog\Model\ResourceModel\Product::save()), you will get critical error - Property "ShowDefaultNotificationMessage" does not have accessor method "setShowDefaultNotificationMessage" in class "Magento\CatalogInventory\Api\Data\StockItemInterface". Even if you do not use this interface in your extension, you still get an error.

### Manual testing scenarios (*)

1. Create simple rabbitmq queue extension
2. Create plugin afterSave for the Magento\Catalog\Model\ResourceModel\Product::save()
3. Set up consumer <consumer name="YourConsumerName" queue="name_product_save" connection="amqp" handler="Name\Queue\Model\Product\SaveConsumer::processMessage"/>
3. Save product in the admin panel
4. Run php bin/magento queue:consumers:start YourConsumerName
5. Got error)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29707: Property "ShowDefaultNotificationMessage" does not have accessor method

### CODE REVIEW

**Comment by lenaorobei** [comment]
@magento create issue

**Comment by lenaorobei** [comment]
@magento run all tests

**Review by lenaorobei — CHANGES_REQUESTED** [review]
@ityetti could you please sign CLA so we will be able to move forward with this PR. Thanks!

**Comment by ityetti** [comment]
@lenaorobei hello. Yeah, I'll do it ASAP.

**Comment by lenaorobei** [comment]
Closing this PR due to inactivity. 

@ityetti, please feel free to reopen if you are going to continue working on it.

Thank you!

**Review by ityetti — COMMENTED** [review]
Updated

**Comment by ityetti** [comment]
@magento run all tests

**Pull request closed without merging**
