### PR TITLE
Removing non RFC3986 authorized characters

### LINKED ISSUE #38355: [Issue] Removing non RFC3986 authorized characters
This issue is automatically created based on existing pull request: magento/magento2#37532: Removing non RFC3986 authorized characters

---------

### Description (*)

This pull request aims to fully remove the usage of non-compliant [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986.html).

### Related Pull Requests

https://github.com/magento/magento2/pull/35885
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Questions or comments

It was done and merged for the [Encoder](https://github.com/magento/magento2/pull/35885/files#diff-daa19047da7e9370f561c393b896178499a5e8a5e0e9aba9f027b6bf0711af81R18) but not for the Decoder yet

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by MeCapron**
### Description (*)

This pull request aims to fully remove the usage of non-compliant [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986.html).

### Related Pull Requests

https://github.com/magento/magento2/pull/35885
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Questions or comments

It was done and merged for the [Encoder](https://github.com/magento/magento2/pull/35885/files#diff-daa19047da7e9370f561c393b896178499a5e8a5e0e9aba9f027b6bf0711af81R18) but not for the Decoder yet

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38355: Removing non RFC3986 authorized characters

### CODE REVIEW

**Comment by MeCapron** [comment]
@magento run Sample Data Tests

**Comment by MeCapron** [comment]
@magento run Sample Data Tests B2B

**Comment by bgorski** [comment]
@magento run Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE

**Comment by bgorski** [comment]
@magento run Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE

**Comment by bgorski** [comment]
@magento run Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE

**Comment by bgorski** [comment]
@magento run all tests

**Comment by MeCapron** [comment]
@magento run all tests

**Comment by MeCapron** [comment]
@magento run all tests

**Comment by MeCapron** [comment]
@magent run Unit Tests

**Comment by MeCapron** [comment]
@magento run all tests

**Comment by MeCapron** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by MeCapron** [comment]
@magento run Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by MeCapron** [comment]
@magento run Functional Tests EE

**Comment by MeCapron** [comment]
@magento run Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE

**Comment by MeCapron** [comment]
@bgorski hello, do you have any idea why can't I run these tests?

**Comment by MeCapron** [comment]
@magento run Sample Data Tests B2B

**Comment by MeCapron** [comment]
@magento run Functional Tests EE

**Comment by MeCapron** [comment]
@magento run Functional Tests EE

**Comment by MeCapron** [comment]
@magento run Functional Tests EE

**Comment by MrBlueEyez** [comment]
Not sure where to mention this, but there is also a `Magento\Framework\Encryption\UrlCoder` which tries to decode urls for itself. This is still using the older `strtr($url, '-_,', '+/=')`.

Perhaps it is also good to update this pr to also change the urlCoder to use the UrlEncode and UrlDecode classes instead of trying to apply its own logic?

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @MeCapron,

Thanks for the collaboration!

The changes seems good to me, but I also agree with @MrBlueEyez comment here:
https://github.com/magento/magento2/pull/37532#issuecomment-1672725408

We can fix this for the `Magento\Framework\Encryption\UrlCoder::decode` method as well.

I request you to please make the changes.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE, Integration Tests

**Comment by engcom-Hotel** [comment]
We are picking up this PR for further development

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Hotel** [comment]
The failed Tests are flaky. The failures are different in 2 consecutive build runs. Please refer to the below screenshot for reference:

image

image

Hence moving this PR further.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Echo** [comment]
@MeCapron,

**Review by engcom-Echo — CHANGES_REQUESTED** [review]
@MeCapron 

According to Definition of Done, new changes should be covered with automated tests coverage. Can you please do the needful.

**Review by engcom-Echo — APPROVED** [review]

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** 

**Manual testing scenario:**
1. Verify Decoding Works as expected.
2. Use the URL : `http://magento2.adobe/encoding/with/longer/url/`
3. Encode this URL with the Magento\Framework\Url\Encoder::encode method
4. Decode the result from previous step using `Magento\Framework\Url\Decoder::decode` result should be `http://magento2.adobe/encoding/with/longer/url/`


**After:** :heavy_check_mark:  

Screenshot 2024-01-17 at 12 46 27 PM


Builds are failing. Hence moving it to `Extended Testing`

**Comment by engcom-Echo** [comment]
@magento create issue

**Review by andrewbess — APPROVED** [review]
Hello @MeCapron 
Thank you for your contribution
Looks nice for me
Approved

**Comment by engcom-Echo** [comment]
**Functional Tests B2B** build are green. **WebAPI Tests** failure are not related to PR
Functional Tests EE build failure are different on last two run on same commit.
Run1
Screenshot 2024-01-17 at 4 47 54 PM

Run2
Screenshot 2024-01-17 at 4 48 11 PM

**Pull request merged**
