### PR TITLE
Support cron expressions like `3/10 * * * *` and handle hyphen expres…

### LINKED ISSUE #29240: [Issue] Support cron expressions like `3/10 * * * *` and handle hyphen expres…
This issue is automatically created based on existing pull request: magento/magento2#28930: Support cron expressions like `3/10 * * * *` and handle hyphen expres…

---------

### Preconditions (*)

Cron expressions like `3/10 * * * *` are now not scheduled. They should be scheduled at every 10 minutes, starting at 3 minutes past the hour.

### Fixed Issues (if relevant)

1. PR #28930 

### Steps to reproduce: (*)

1. Plan a cron job with the expression `3/10 * * * *`
2. Run `bin/magento cron:run`
3. See how it does not get scheduled

**Actual Result:** :heavy_multiplication_x: cron task with expression `3/10 * * * *` was not scheduled 

**Expected Result:** :heavy_check_mark: They should be scheduled at every 10 minutes, starting at 3 minutes past the hour.

after applying the PR, it will get scheduled.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### PR DESCRIPTION
**Pull request by AntonEvers**
### Description (*)

Cron expressions like `3/10 * * * *` are now not scheduled. They should be scheduled at every 10 minutes, starting at 3 minutes past the hour.

### Fixed Issues (if relevant)

1. PR #28930 

### Manual testing scenarios (*)

1. Plan a cron job with the expression `3/10 * * * *`
2. Run `bin/magento cron:run`
3. See how it does not get scheduled

after applying the PR, it will get scheduled.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### Resolved issues:
1. [x] resolves magento/magento2#29240: Support cron expressions like `3/10 * * * *` and handle hyphen expres…

### CODE REVIEW

**Comment by AntonEvers** [comment]
@magento run Unit Tests

**Comment by rogyar** [comment]
@magento run all tests

**Comment by AntonEvers** [comment]
@rogyar I think we're good, right? The first 2 static tests seem to fail on every PR so I don't think they have anything to do with this addition.

**Comment by rogyar** [comment]
@magento run Functional Tests B2B

**Comment by rogyar** [comment]
It does look like a set of flaky tests, but let's double-check this fact

**Comment by AntonEvers** [comment]
> It does look like a set of flaky tests, but let's double-check this fact

I cannot imagine that this PR will have an effect on frontend HTML elements. So indeed, they look like flaky tests that come up due to me merging 2.4-develop

**Comment by AntonEvers** [comment]
@magento run all tests

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7863](https://jira.corp.magento.com/browse/ENGCOM-7863) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Plan a cron job with the expression `3/10 * * * *`
2. Run `bin/magento cron:run`. 

**Before:** :heavy_multiplication_x: cron task with expression `3/10 * * * *` was not scheduled 

**After:** :heavy_check_mark: cron task with expression `3/10 * * * *` was successfully scheduled .
They scheduled every 10 minutes, starting at 3 minutes past the hour.

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
Failed Functional Tests B2B not related to the changes in this PR.

**Pull request merged**
