### PR TITLE
[MFTF] Use StorefrontOpenCartPageActionGroup to go to Checkout page

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR uses `StorefrontOpenCartPageActionGroup` to go to Checkout page and removes this part of code 
`<amOnPage url="{{CheckoutCartPage.url}}" stepKey="onPageShoppingCart"/>`
        `<waitForPageLoad stepKey="waitForCartPageLoad"/>`

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
It's not hard requirements, but as I previously mentioned - could you change the naming to:
`StorefrontCartPageOpenActionGroup` ? This is because then you'll get hints on all the actions that can be performed on some specific area. For example: `StorefrontCart|` and then it shows all the actions one by another, not randomly mixed with `StorefrontConfigurableProductAddToCartActionGroup` :-)

**Comment by Usik2203** [comment]
Hi @lbajsarowicz . 
Thank you for remarking. I will try to choose names more carefully.

**Comment by lbajsarowicz** [comment]
@Usik2203 I'm glad that you improve such annoying parts of MFTF.

**Review by lbajsarowicz — APPROVED** [review]
Thank you!

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7408](https://jira.corp.magento.com/browse/ENGCOM-7408) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Pull request merged**
