### PR TITLE
Exclude JS from move JS code to the bottom of the page

### PR DESCRIPTION
**Pull request by in-session**
Currently there is no possibility to exclude global single files or inline scripts with the function "Move JS code to the bottom of the page". However, this is necessary in some areas, for example with the Google Tag Manager or other critical JS resources.

Configuration>Developer>JavaScript Settings>Move JS code to the bottom of the page

### CODE REVIEW

**Comment by in-session** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

**Review by Den4ik — CHANGES_REQUESTED** [review]
Hi @in-session.
Thanks for PR.
I believe that we can remove `data-move="false"` string from result context after detection.
What do you think?

**Comment by in-session** [comment]
> Hi @in-session. Thanks for PR. I believe that we can remove `data-move="false"` string from result context after detection. What do you think?

Do you have an idea for that? I am a bit overwhelmed with work right now.

**Comment by mrtuvn** [comment]
So if in file xml layout dev add file external/custom js files have attribute "data-move" equal false magento will act not move these files to bottom ?
Can you add some content for clarify idea of this improve?

From my experiences with requirejs in magento stack current if we require it somewhere in codebase you can remove it from layout. The only way for exclude is find place where it define and add some condition or remove it completely

**Comment by in-session** [comment]
> So if in file xml layout dev add specific file external/custom js files have attribute "data-move" equal false magento will act not move these files to bottom ? For very specific case i think the better option is instead excludition by code we can choose conditional include or load Can you add some content for clarify idea of this improve?
> 
> From my experiences with requirejs in magento stack current if we require it somewhere in js codebase you cannot remove it from layout. The only way for exclude is find place where it define and add some condition or remove it completely

Yes the idea behind it is to exclude scripts from moving 
For example with the use of third cookie consent tools or other libraries like workbox etc., these must not be loaded async and must be added on top, like:

```
<script src="https://privacy-proxy.usercentrics.eu/latest/uc-block.bundle.js" src_type="url" data-move="false" />
```

But of course this also refers to inline scripts which are integrated via phtml, like google tag manager:

```
<?php
$scriptTagManager = <<<SCRIPT
    (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-XXXXXX');
SCRIPT;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', ['data-cfasync'=>'false','data-move'=>'false'], $scriptTagManager, false) ?>
```

**Comment by vseager** [comment]
@in-session what is the status on this?

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
> e test has not gone through.

I would say no as it is better for frontend debugging to check the values.

**Comment by in-session** [comment]
> Hi @in-session. Thanks for PR. I believe that we can remove `data-move="false"` string from result context after detection. What do you think?

I would say no as it is better for frontend debugging to check the values.

**Comment by in-session** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@in-session Can you please resolved the conflicts?

**Comment by in-session** [comment]
@magento run all tests

**Pull request closed without merging**
