### PR TITLE
#1748: Some category grid columns are empty

### LINKED ISSUE #1748: Some category grid columns are empty
### Steps to reproduce (*)
1. Create a couple of categories
2. Go to `https://<host>/admin/media_gallery_catalog/category/index`

### Expected result (*)
"In menu" and Enabled columns should display a value

### Actual result (*)
image

### PR DESCRIPTION
**Pull request by joweecaquicla**
### Description (*)

This PR will introduce the fix to the empty In Menu and Enabled columns in category grid and the renderers for each column.
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/adobe-stock-integration/issues/1748: Some category grid columns are empty

### Manual testing scenarios (*)

1. Create a couple of categories
2. Go to `https://<host>/admin/media_gallery_catalog/category/index`
3. "In Menu" and "Enabled" columns should display a value

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by joweecaquicla** [comment]
@magento run all tests

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the pull request @joweecaquicla ! Can you please add the verification of these columns to the `AdminAssertCategoryGridPageDetailsActionGroup`

**Comment by joweecaquicla** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-8012](https://jira.corp.magento.com/browse/ENGCOM-8012) has been created to process this Pull Request

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed
Screenshot_104

**Pull request merged**
