### PR TITLE
MFTF: Applying Coupon Codes With Enabled Captcha

### PR DESCRIPTION
**Pull request by DmitryTsymbal**
This PR contains MFTF test for applying coupon codes on shopping cart page with enabled captcha

**Steps to reproduce:**

1 - Enable captcha on Applying codes form
2 - Create product
3 - Create customer
4 - Login as customer
5 - Navigate to created product
6 - Add product into shopping cart
7 - Navigate to shopping cart
8 - Apply coupon code with incorrect captcha values
0 - Apply coupon code with correct captcha values
9 - Perform assertions

### CODE REVIEW

**Comment by DmitryTsymbal** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run Database Compare, Functional Tests EE

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-9063](https://jira.corp.magento.com/browse/ENGCOM-9063) has been created to process this Pull Request

**Comment by dmitriyprime** [comment]
:heavy_check_mark:  QA passed

**Pull request merged**
