### PR TITLE
Resolve Send friend sender email should be static not user defined

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

magento/magento2#23646: Resolve Send friend sender email should be static not user defined

-Set From is the "General Contact" in the system
-Set Reply To is $sender['email'] and $sender['name']

### Fixed Issues (if relevant)

1. magento/magento2#23646: Resolve Send friend sender email should be static not user defined

### Manual testing scenarios (*)

1. On product page select email friend
2. Fill the form
3. Email is sent from the email configured as sender in configuration (backend).
From: General Contact. (static at backend)
Reply To: The sender at the frontend (user defined)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23684) <br/>All committers have signed the CLA.

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-23684.instances.magento-community.engineering).
Admin access: [https://pr-23684.instances.magento-community.engineering/admin](https://pr-23684.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by edenduong** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [Magento instance](https://i-23684-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23684-2-3-develop.instances.magento-community.engineering/admin](https://i-23684-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-23684.instances.magento-community.engineering).
Admin access: [https://pr-23684.instances.magento-community.engineering/admin](https://pr-23684.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-23684.instances.magento-community.engineering).
Admin access: [https://pr-23684.instances.magento-community.engineering/admin](https://pr-23684.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by gwharton** [comment]
Shouldnt this PR use transportBuilder->setFromByScope instead of setFrom to make it store specific. What happens if there are two websites, each of which has its own general contact email set. Please ensure any test cases cover multiple website setup.

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-23684.instances.magento-community.engineering).
Admin access: [https://pr-23684.instances.magento-community.engineering/admin](https://pr-23684.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by edenduong** [comment]
@gwharton: Thank you very much. setFrom is deprecated. So I changed it to setFromByScope

**Comment by edenduong** [comment]
Hi @orlangur : Could you please review my pull request?

**Comment by gwharton** [comment]
Quick Test Case on your PR

```
Backend
=======
Stores -> All Stores
Create Store View
      Store = Main Website Store
      Name = Default Store View 2
      Code = default_2
      Status = enabled
      Save Store View
Marketing -> Email Templates -> Add New Template
  Template = "Send Product Link to Friend" -> Load Template
      Template Name = Send Friend View 1
      Subject = Send Friend View 1
      Template Content = <<Leave unchanged>>
      Save Template
  Template = "Send Product Link to Friend" -> Load Template
      Template Name = Send Friend View 2
      Subject = Send Friend View 2
      Template Content = <<Leave unchanged>>
      Save Template
Store -> Configuration -> General -> Store Email Addresses
    General Contact
        Change Scope to Default Store View
          Sender Name = View 1 Owner
          Sender Email = view1ownerowner@lubefinder.com
          Save Config
        Change Scope to Default Store View 2
          Sender Name = View 2 Owner
          Sender Email = view2ownerowner@lubefinder.com
          Save Config
Store -> Configuration -> Catalog -> Email to a Friend
    Change Scope to Default Store View
      Select Email Template = Send Friend View 1
      Allow for Guests = Yes
      Save Config
    Change Scope to Default Store View 2
      Select Email Template = Send Friend View 2
      Allow for Guests = Yes
      Save Config
Catalog -> Products -> Add Product
    Product Name = Test
    Price = 111
    Quantity = 111
    New Category
        Name = TC
        Parent Category = Default Catgeory
        Create Category
    Save & Close
    
Frontend
========
Go to Test product on frontend
Ensure Store Switcher is set to Default Store View
Click Email button
    Name = TestBrowser1
    email = testbrowser1@lubefinder.com
    Message = Test 1
    Invitee
        Name = Friend 1
        Email = friend1@lubefinder.com
    Send Email
Ensure Store Switcher is set to Default Store View 2
Click Email button
    Name = TestBrowser2
    email = testbrowser2@lubefinder.com
    Message = Test 2
    Invitee
        Name = Friend 2
        Email = friend2@lubefinder.com
    Send Email
```
image

image

Looks good to me.

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-5571](https://jira.corp.magento.com/browse/ENGCOM-5571) has been created to process this Pull Request
:eight_spoked_asterisk: @swnsma, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [Magento instance](https://i-23684-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23684-2-3-develop.instances.magento-community.engineering/admin](https://i-23684-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

**Before:**
before

**After:**
after

**Pull request merged**
