### PR TITLE
magento#37308: converted cookieMessages to observable attribute

### LINKED ISSUE #37308: Cookie Messages is read-only and can not be manipulated
### Summary

Common customizations of Magento include creating a hide or close button for customer messages, and having it automatically disappear after a certain amount of seconds.

The right way to approach this is to modify the application state. In this case it would be necessary for developers to modify the messages array, which should cause the UI to be rerendered by Knockout's dual way data-binding. This is often done through a JS mixin that extends the `messages.js` UI Component.

At the moment this is not possible. The `cookieMessages` array is not an observable attribute and the UI does not react to any changes.

(Also see Example 1 in the official documentation: https://knockoutjs.com/documentation/foreach-binding.html)

My suggestion is convert the cookieMessages into an observable attribute, so that developers are able to manipulate the state causing a proper UI rerender.

### Examples

`messages-mixin.js`:

At the moment, manipulating the `cookieMesssages` attribute does not cause the UI to be updated.

```JS
define([
    'Magento_Customer/js/customer-data'
], function (customerData) {
    'use strict';

    return function (target) {
        return target.extend({

            initialize: function () {
                this._super();


                if (this.cookieMessages && this.cookieMessages.length > 0) {
                    setTimeout((function () {
                        this.cookieMessages = [];
                    }).bind(this), 5000);
                }
            },

        });
    }
});
```

However, in-line with Magento philosophy, we would like the state to be reflected in the UI by using an observable instead. This is expected behaviour:

`messages-mixin.js`:

```JS
define([
    'Magento_Customer/js/customer-data'
], function (customerData) {
    'use strict';

    return function (target) {
        return target.extend({

            initialize: function () {
                this._super();


                if (this.cookieMessages() && this.cookieMessages().length > 0) {
                    setTimeout((function () {
                        this.cookieMessages([]);
                    }).bind(this), 5000);
                }
            },

        });
    }
});
```

### Proposed solution

Convert cookieMessages into an observable. Unfortunately the fix for this will necessarily be backwards incompatible for merchants that have overwritten `vendor/magento/module-theme/view/frontend/templates/messages.phtml`.

I will create a PR.

edit: https://github.com/magento/magento2/pull/37309

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by erfanimani**
The UI will now stay in sync after manipulation of state.

### Description (*)

This is a developer experience improvement described in more detail in the related issue.

A summary:

Common customizations of Magento include creating a hide or close button for customer messages, and having it automatically disappear after a certain amount of seconds.

The right way to approach this is to modify the application state. In this case it would be necessary for developers to modify the messages array, which should cause the UI to be rerendered by Knockout's dual way data-binding. This is often done through a JS mixin that extends the `messages.js` UI Component.

At the moment this is not possible. The `cookieMessages` array is not an observable attribute and the UI does not react to any changes.

(Also see Example 1 in the official documentation: https://knockoutjs.com/documentation/foreach-binding.html)

My suggestion is convert the cookieMessages into an observable attribute, so that developers are able to manipulate the state causing a proper UI rerender.

### Examples

`messages-mixin.js`:

At the moment, manipulating the `cookieMesssages` attribute does not cause the UI to be updated.

```JS
define([
    'Magento_Customer/js/customer-data'
], function (customerData) {
    'use strict';

    return function (target) {
        return target.extend({

            initialize: function () {
                this._super();


                if (this.cookieMessages && this.cookieMessages.length > 0) {
                    setTimeout((function () {
                        this.cookieMessages = [];
                    }).bind(this), 5000);
                }
            },

        });
    }
});
```

However, in-line with Magento philosophy, we would like the state to be reflected in the UI by using an observable instead. This is expected behaviour:

`messages-mixin.js`:

```JS
define([
    'Magento_Customer/js/customer-data'
], function (customerData) {
    'use strict';

    return function (target) {
        return target.extend({

            initialize: function () {
                this._super();


                if (this.cookieMessages() && this.cookieMessages().length > 0) {
                    setTimeout((function () {
                        this.cookieMessages([]);
                    }).bind(this), 5000);
                }
            },

        });
    }
});
```

### Related Pull Requests

N/A

### Fixed Issues (if relevant)

1. Fixes magento/magento2#37308

### Manual testing scenarios (*)

See related issue.

### Questions or comments

This is a backwards incompatible change for merchants that have overwritten `vendor/magento/module-theme/view/frontend/templates/messages.phtml`.

Is it more correct to use the `tracks` attribute to define observables?

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @erfanimani,

Thanks for the contribution!

Changes look good to me. But please take care of the failed tests.

Thanks

**Comment by erfanimani** [comment]
Thanks @engcom-Hotel — I fixed the phpcs issue. I will check the rest of the tests.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Database Compare

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Comment by erfanimani** [comment]
Hi @engcom-Hotel, thanks for trying to reproduce it and the quick turnaround time — appreciate the transparency!

You're right in saying that we are able to manipulate the `cookieMessages` variable with a mixin. However, the issue is that this is not reflected on the UI (and therefore not useful). This is the intention of the PR to fix.

As I mentioned before:

> The right way to approach this is to modify the application state. In this case it would be necessary for developers to modify the messages array, which should cause the UI to be rerendered by Knockout's dual way data-binding. This is often done through a JS mixin that extends the messages.js UI Component.

> At the moment this is not possible. The cookieMessages array is not an observable attribute and the UI does not react to any changes.

**Comment by erfanimani** [comment]
@engcom-Hotel 

> Hello @erfanimani,
> 
> Thanks for the quick response!
> 
> Actually, we have followed this [#37308 (comment)](https://github.com/magento/magento2/issues/37308#issuecomment-1526888949) made by you for issue reproduction.
> 
> Now I am trying to reproduce the issue in UI, please suggest to us if you have any way to do that.
> 
> Thanks

Yes sorry — my bad. I've reworded it here:

Steps to reproduce:

* Developer wants to manipulate the content of the messages shown to the customer
* The state is encapsulated in the `cookieMessages` variable
* Developer creates a mixin and manipulates cookieMessages variable

Expected result:

* UI is updated to reflect the new state

Actual result:

* UI is not updated to reflect the new state; cookieMessages is not an observable. Developer insteadneeds to overwrite entire JS files.

Hope that clarifies it. It's a relatively simple process.

**Comment by engcom-Hotel** [comment]
Hello @erfanimani,

Thanks for the response!

We are still unable to reproduce the issue in the latest 2.4-develop branch. 

As per your comment, we have tried to manipulate the `cookieMessages` variable in the mixin and we can see the updated initialized value of the `cookieMessages` variable in the UI. Please refer to the below screenshot for the reference:

image

I am also attaching the updated custom module below, please let us know if we missed anything:

[Magz_2.zip](https://github.com/magento/magento2/files/11530702/Magz_2.zip)

Thanks

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @erfanimani,

Thanks for the contribution!

As per the discussion with @erfanimani on Slack, now the mentioned issue is reproducible and these PR changes are able to fix the issue. 

But the changes are backward incompatible. So we need to think of other ways for the implementation.

Thanks

**Comment by engcom-Hotel** [comment]
Sure @erfanimani, Sounds good to me. Let us know once done. 

Thanks

**Comment by engcom-Hotel** [comment]
Hello @erfanimani,

As the development is still going on this PR, hence marking this PR as a draft for now. 

Please let us know whenever you are ready with this PR, we will pick this again.

Thanks

**Comment by erfanimani** [comment]
Hi @engcom-Hotel , I've updated the PR with backwards compatibility. I've also tested this.

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

- Created a mixin on `app/code/Magento/Theme/view/frontend/web/js/view/messages.js` 
- Try to override the `this->cookieMessages`

**Before:** :heavy_multiplication_x: 

- Developer can't manipulate cookieMessages variable and instead need to overwrite entire JS files.

**After:** :heavy_check_mark:

- Developer creates a mixin and manipulates cookieMessages variable

Moving to Extended Testing as some tests are still fail.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Comment by engcom-Hotel** [comment]
Functional Test Failure seems flaky to me as the error shown in the Allure report is different in the last 2 times. Please refer to the below screenshots for reference:

Screenshot 1:



Screenshot 2:

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
The changes from this PR were merged in https://github.com/magento/magento2/commit/38b8b516489a6e436177c59f61ec5903cd8552c5.
I'm closing this PR

**Pull request closed without merging**
