### PR TITLE
#38671 - Fix sales rules when rule is applied only on shipping amount

### LINKED ISSUE #38671: [Issue] Sales Rules regression in 2.4.7
### Preconditions and environment

- Magento version 2.4.7

### Steps to reproduce

1. Create a sales rule with : 
   - Coupon code = test
   - No limitation
   - No conditions
   - Action = Fixed amount for whole cart, 1€ discount
   - Apply to Shipping Amount = yes
   - Product condition = name equals to "any_text_that_is_not_a_product_name"
 2. Apply 'test' coupon to a frontend cart with a shipping amount. 

### Expected result

Rule is applied. Discount of 1€ is applied on shipping amount

### Actual result

Cannot add coupon to cart (invalid coupon)

### Additional information

We had rules like this to add discount on shipping amount (and shipping amount only). It worked perfectly in previous versions, but does not work anymore in 2.4.7.

Regression happened in this commit : https://github.com/magento/magento2/commit/79d57b4eb7696bb0fc2ce3aad03f5d6bec1ae275 where line `$this->rulesApplier->maintainAddressCouponCode($address, $rule, $this->getCouponCode());` has been removed. @sivaschenko / @bl4de  : was there a reason ?

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Nuranto**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#38671

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Nuranto** [comment]
@magento run WebAPI Tests, Functional Tests EE, Functional Tests B2B

**Review by Den4ik — APPROVED** [review]
✅ I'm agree with rolling back this changes
@Nuranto Thanks for contribution

**Comment by Den4ik** [comment]
@magento run WebAPI Tests

**Comment by Den4ik** [comment]
@magento run WebAPI Tests

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-11876 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-11876&type=commits

Thanks

**Pull request closed without merging**
