### PR TITLE
Fix issue 38406

### PR DESCRIPTION
**Pull request by sheepfy**
Fix issue https://github.com/magento/magento2/issues/38406

### CODE REVIEW

**Comment by Den4ik** [comment]
@magento run all tests

**Review by Den4ik — CHANGES_REQUESTED** [review]
@sheepfy Could you please add tests for this changes?
Anyway changes looks correct.

**Comment by sheepfy** [comment]
> @sheepfy Could you please add tests for this changes? Anyway changes looks correct.

I'm not exactly sure what to do exactly. However, I see that the method "\Magento\Customer\Block\Address\Edit::_prepareLayout"  is protected, not public.

**Comment by Den4ik** [comment]
@sheepfy I mean to add unit tests

**Comment by sheepfy** [comment]
> @sheepfy I mean to add unit tests

I'm still now sure what tests to add for my change :)) I'm basically adding "null" like it's happening for the other line

'region_id' => isset($postedData['region_id']) ? $postedData['region_id'] : null,

**Review by Den4ik — APPROVED** [review]
✅ Approve. Failed tests are not related to changes.

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi @sheepfy,

Thanks for the collaboration & contribution!

:heavy_check_mark: QA Passed

**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Go to admin -> Customer Address attributes -> pick one, add some random validation (for example, length validation)
- Go to admin -> general -> state -> Set "Allow to Choose State if It is Optional for Country" to NO
- Go to my account, try to add/edit an address (i did with edit) that don't have the region field displayed. For example: Finland
- Inspect element and remove validation classes for the length validated attribute.
- Click save





**Before:** :heavy_multiplication_x: 



Screenshot 2024-04-23 at 12 04 51




Screenshot 2024-04-23 at 12 05 18








**After:** :heavy_check_mark:  



Screenshot 2024-04-23 at 12 28 08


There is No Exception while saving an address.

Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Integration Tests,Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
Functional Tests B2B,Functional Tests CE,Functional Tests B2B failure are known and different on last two run on same commit. 
Functional Tests B2B
Run1
38407-b2b

Run2
Screenshot 2024-05-16 at 12 51 09 PM

Functional Tests CE
Run1
38407-ce

Run2
Screenshot 2024-05-16 at 12 50 42 PM

Functional Tests EE
Run1
38407-ee
Run2
Screenshot 2024-05-16 at 12 39 39 PM

WebAPI Tests and Integration Tests failure are flaky not related to PR

Integration Tests
Screenshot 2024-05-16 at 12 51 58 PM

WebAPI Tests 
Screenshot 2024-05-16 at 12 52 05 PM

Moved to `merge in progress`

**Pull request merged**
