### PR TITLE
fixed issue regarding referer url of compare page during adding product to wishlist

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)

After Adding product to wishlist from compare page the Success Message link on the wishlist page has link to customer account instead of compare page url. As the referer url is hard coded to customer/account page, the uenc code generated is of customer account page and is redirected to this page only. 

### Fixed Issues (if relevant)

1. i didn't find any such issue raised on GIT.
2. ...

### Manual testing scenarios (*)

1. Add product to compare.
2. Goto compare page and then Add product to Wishlist.
3. On successful addition of product to wishlist, the page is redirected to Wishlist home page, with a success message.
4. In that success Message, a link is provided to go back to the page from where the product is adding to wishlist Stating Click here to continue shopping.
5. When you click this link it redirects to customer account page, rather going to compare page.
products comparison list magento commerce
my wish list
my account

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18637) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by ghost** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul, here is your [new Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-18637/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-18637//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-18637//admin)
Login: `admin` Password: `123123q`

**Comment by ghost** [comment]
#SQUASHTOBERFEST

**Review by phoenix128 — APPROVED** [review]
Thank you for your contribution

**Comment by magento-engcom-team** [comment]
Hi @phoenix128, thank you for the review.
[ENGCOM-3270](https://jira.corp.magento.com/browse/ENGCOM-3270) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@ayazwebkul thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
