### PR TITLE
Fix interception for virtual types in non global area

### LINKED ISSUE #17825: Plugins not called for Magento\Catalog\Block\Product\ListProduct in search page in developer mode
### Preconditions
1. Magento 2.2.5
2. PHP 7.1.9
3. MySQL 5.6.37

### Steps to reproduce
1. Set deploy mode to developer.
2. Create plugin for Magento\Catalog\Block\Product\ListProduct
3. Go to search page.

### Expected result
1. Magento\Catalog\Block\Product\ListProduct\Interceptor should be used to render the product list.

### Actual result
1. Magento\Catalog\Block\Product\ListProduct is used instead and therefore the plugin is not called.

image

Problem seems to stem from Magento\Framework\Interception\Config\Config. The $_omConfig doesn't contain virtualType for Magento\CatalogSearch\Block\SearchResult\ListProduct and is marked as not intercepted.

```
/**
     * Process interception inheritance
     *
     * @param string $type
     * @return bool
     */
    protected function _inheritInterception($type)
    {
        $type = ltrim($type, '\\');
        if (!isset($this->_intercepted[$type])) {
            $realType = $this->_omConfig->getOriginalInstanceType($type);
            if ($type !== $realType) {
                if ($this->_inheritInterception($realType)) {
                    $this->_intercepted[$type] = true;
                    return true;
                }
            } else {
                $parts = explode('\\', $type);
                if (!in_array(end($parts), $this->_serviceClassTypes) && $this->_relations->has($type)) {
                    $relations = $this->_relations->getParents($type);
                    foreach ($relations as $relation) {
                        if ($relation && $this->_inheritInterception($relation)) {
                            $this->_intercepted[$type] = true;
                            return true;
                        }
                    }
                }
            }
            $this->_intercepted[$type] = false;
        }
        return $this->_intercepted[$type];
    }
```

Later on Magento\Framework\Interception\ObjectManager\Config\Developer, this value is checked on hasPlugins function and it will return false.

```
/**
     * Retrieve instance type with interception processing
     *
     * @param string $instanceName
     * @return string
     */
    public function getInstanceType($instanceName)
    {
        $type = parent::getInstanceType($instanceName);
        if ($this->interceptionConfig && $this->interceptionConfig->hasPlugins($instanceName)
            && $this->interceptableValidator->validate($instanceName)
        ) {
            return $type . '\\Interceptor';
        }
        return $type;
    }
```

### PR DESCRIPTION
**Pull request by stkec**
Fixes #17825

### Description
When a VirtualType defined in di.xml located in non global area (e.g. frontend, adminhtml subfolder etc) the plugins for the Base class of such Virtual Type will not work.

This happens because at the moment Object Manager is configured, only Global area di.xml files are loaded:
*Magento/Framework/App/ObjectManager/Environment/Developer.php* Line 76:
```php
        $objectManager->configure(
            $objectManager
                ->get(\Magento\Framework\App\ObjectManager\ConfigLoader::class)
                ->load(Area::AREA_GLOBAL)
        );
        $objectManager->get(\Magento\Framework\Config\ScopeInterface::class)
            ->setCurrentScope('global');
        $diConfig->setInterceptionConfig(
            $objectManager->get(\Magento\Framework\Interception\Config\Config::class)
        );
```
The *Magento\Framework\Interception\Config\Config* Class in constructor will load configs from all scopes and generates *_intercepted* config array. However to support VirtualTypes it uses call:
```php
$this->_omConfig->getOriginalInstanceType($type)
```
Which relies on current ObjectManager Configuration. While at the moment we have only *Area::AREA_GLOBAL* loaded in ObjectManager.
As a result *Interception\Config* does not see any VirtualTypes defined in other Areas and marks classes as not intercepted.
```php
protected function _inheritInterception($type, $force = false)
    {
        $type = ltrim($type, '\\');
        if (!isset($this->_intercepted[$type]) || $force) {
            $realType = $this->_omConfig->getOriginalInstanceType($type);
            if ($type !== $realType) {
                if ($this->_inheritInterception($realType)) {
                    $this->_intercepted[$type] = true;
                    return true;
                }
            } else {
                $parts = explode('\\', $type);
                if (!in_array(end($parts), $this->_serviceClassTypes) && $this->_relations->has($type)) {
                    $relations = $this->_relations->getParents($type);
                    foreach ($relations as $relation) {
                        if ($relation && $this->_inheritInterception($relation)) {
                            $this->_intercepted[$type] = true;
                            return true;
                        }
                    }
                }
            }
            $this->_intercepted[$type] = false;
        }
        return $this->_intercepted[$type];
    }
```

### Fix

The idea is to add *extend()* function to *Magento\Framework\Interception\Config\Config* to be able to regenerate *_intercepted* array for the definitions loaded in the Application class.

This PR is not complete since it only calls *extend* in *Magento\Framework\App\Http* class.
Please feel free to use it as a reference or as a suggestion.

### Fixed Issues
1. magento/magento2[#17825](https://github.com/magento/magento2/issues/17825): Plugins not called for Magento\Catalog\Block\Product\ListProduct in search page in developer mode

### Manual testing scenarios
1. Define a VirtualType in any module 'frontend/di.xml'
2. Define a plugin for a base class of the virtualType (for ex. throw exception or log something in beforeToHtml).
3. Use VirtualType somewhere on frontend. (for ex. add as a Block in layout)
4. Open a page in browser which uses a class you defined plugin and VirtualType for.
5. See exception not thrown or log not written because plugin didn`t work.

**Expected result**
5. See exception thrown or log written in the plugin

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @stkec. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by k4emic** [comment]
@orlangur How come this PR is on hold?

**Comment by orlangur** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Hi @orlangur @sdzhepa @slavvka ,
Could you explain why this PR went to "on hold" almost 1 year ago?
What's wrong with it?

**Comment by slavvka** [comment]
@stkec Could you please resolve conflicts?

**Comment by ihor-sviziev** [comment]
@slavvka I just resolved conflicts, they were really not hard

**Comment by ihor-sviziev** [comment]
@slavvka @lenaorobei @orlangur,
Any updates since Jan 24? Why PR was moved back to "on hold" again?
It's clear to me that this is backward incompatible change, so it can be accepted only in 2.4.0 or 2.5.0, but there were no response at all.

**Comment by naydav** [comment]
@stkec @ihor-sviziev 
Guys, sorry I missed one point

> Define a plugin for a base class of the virtualType
Where is defined plugin? Is it frontend area too?

**Comment by VladimirZaets** [comment]
Hi @stkec, thanks for the collaboration. We rechecked functionality provided in the issue that you mentioned and currently, it works correctly. Due to it, I am closing this PR

**Pull request closed without merging**
