### PR TITLE
Introduced support of custom scalar types for GraphQL schema

### LINKED ISSUE #36877: [Issue] Introduced support of custom scalar types for GraphQL schema
This issue is automatically created based on existing pull request: magento/magento2#34651: Introduced support of custom scalar types for GraphQL schema

---------

### Support for GraphQL custom scalars

This PR adds support for custom scalar types to GraphQL.

 https://graphql.org/learn/schema/#scalar-types
https://webonyx.github.io/graphql-php/type-definitions/scalars/#writing-custom-scalar-types

 
After PR is merged a developer will be able to define custom scalar types and implementations by using Magento schema.

For example, the following declaration enables Json scalar type 
```
scalar Json
@implementation(class: "Magento\\MyModule\\Model\\JsonScalarType")
@doc(description:"Json type")
{}
```

Scalar type implementation should implement  new `Magento\Framework\GraphQl\Schema\Type\Scalar\CustomScalarInterface`

Something like:
```
class JsonScalarType implements \Magento\Framework\GraphQl\Schema\Type\Scalar\CustomScalarInterface
{

    public function serialize($value)
    {
        return json_decode($value);
    }

    public function parseValue($value)
    {
        return json_encode($value);
    }

    public function parseLiteral($valueNode, ?array $variables = null)
    {
        return $valueNode->value;
    }
}
```
For example, a query that accepts JSON as input and returns JSON as output and has a  resolver that returns you an argument that you just passed then you will see a picture similar to this:

Screenshot from 2021-11-16 16-41-42

This feature could be widely useful to express values that may have validation, like  HTML, emails, URLs, dates, etc., and for more advanced cases like EAV attributes, where value can be expressed as a single scalar or array of scalars.

 

 

 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by akaplya**
### Support for GraphQL custom scalars

This PR adds support for custom scalar types to GraphQL.

 https://graphql.org/learn/schema/#scalar-types
https://webonyx.github.io/graphql-php/type-definitions/scalars/#writing-custom-scalar-types

 
After PR is merged a developer will be able to define custom scalar types and implementations by using Magento schema.

For example, the following declaration enables Json scalar type 
```
scalar Json
@implementation(class: "Magento\\MyModule\\Model\\JsonScalarType")
@doc(description:"Json type")
{}
```

Scalar type implementation should implement  new `Magento\Framework\GraphQl\Schema\Type\Scalar\CustomScalarInterface`

Something like:
```
class JsonScalarType implements \Magento\Framework\GraphQl\Schema\Type\Scalar\CustomScalarInterface
{

    public function serialize($value)
    {
        return json_decode($value);
    }

    public function parseValue($value)
    {
        return json_encode($value);
    }

    public function parseLiteral($valueNode, ?array $variables = null)
    {
        return $valueNode->value;
    }
}
```
For example, a query that accepts JSON as input and returns JSON as output and has a  resolver that returns you an argument that you just passed then you will see a picture similar to this:

Screenshot from 2021-11-16 16-41-42

This feature could be widely useful to express values that may have validation, like  HTML, emails, URLs, dates, etc., and for more advanced cases like EAV attributes, where value can be expressed as a single scalar or array of scalars.

 

 

 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36877: Introduced support of custom scalar types for GraphQL schema

### CODE REVIEW

**Comment by akaplya** [comment]
@mageno run all tests

**Comment by convenient** [comment]
Just spotted this and this additional type will need to be considered when https://github.com/magento/magento2/pull/31879 is reviewed.

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-November** [comment]
Development team is currently working on this issue.
Thank you.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Need to take care of failed tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @akaplya,

Thank you for your contribution!

Can you please resolve the conflicts in order to proceed further.

Thank you!

**Comment by engcom-Charlie** [comment]
I have resolved the conflict and merge magento 2.4-develop

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @akaplya,

This PR is causing too many test failures. In order to proceed further, we need a green build. Can you please have a look into these.

**WebAPI:** https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/34651/c67291ebfb4d418767c7bf1df5836557/WebApi/console-error-logs.html

**Integration:** https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/34651/c9da274aebad33df5c4e347b3e1fb119/Integration/console-error-logs.html

**Static:**: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/34651/2e1bae68356dc6f570b633f2a3d70b5d/Statics/console-error-logs.html

**Functional CE**: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/34651/9ddfa7a7b205b50534946730552cb202/Functional/allure-report-ce/index.html

**Comment by engcom-Charlie** [comment]
@magento run WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run WebAPI Tests, Integration Tests, Static Tests

**Comment by engcom-Bravo** [comment]
Hello,

Internal team has started to work on it.

Thanks.

**Comment by engcom-Dash** [comment]
Hello @akaplya,

Thank you for your contribution!

Could you please resolve the conflicts so that we can proceed with this PR?

Thanks.

**Comment by engcom-Charlie** [comment]
As per [this](https://github.com/magento/magento2/pull/34651#issuecomment-2017691363) comment, moving it to On Hold.

**Comment by engcom-Hotel** [comment]
Moving this PR `On Hold` as per this https://github.com/magento/magento2/pull/34651#issuecomment-2017691363

**Pull request closed without merging**
