### PR TITLE
Comment add in translate.

### PR DESCRIPTION
**Pull request by pratikhmehta**
### Description (*)
I did add comment in translate attribute of `<Comment>`.

### CODE REVIEW

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Hi @pratikhmehta, please add these values to the translation file. Thanks.

**Comment by pratikhmehta** [comment]
> Hi @pratikhmehta, please add these values to the translation file. Thanks.

Yes, let me add it and again pull the request.

**Review by lenaorobei — APPROVED** [review]

**Comment by lenaorobei** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-6854](https://jira.corp.magento.com/browse/ENGCOM-6854) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by engcom-Charlie** [comment]
Failed functional test not related to the changes in this PR test fails in 2.4-develop with MSI modules.
image

**Pull request merged**
