### PR TITLE
Fixed typos in .less files

### PR DESCRIPTION
**Pull request by kalpmehta**
Fixed few typos in .less files.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15023) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
@kalpmehta thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by kalpmehta** [comment]
Thanks for the invitation, just joined.

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

**Pull request merged**
