### PR TITLE
#24555: Compare Function stop working for not salable products (mageno 2.3.2)

### PR DESCRIPTION
**Pull request by sudheers-kensium**
#24555: Compare Function stop working for not salable products (mageno 2.3.2) - fixed

### Description (*)

#24555: Compare Function stop working for not salable products (mageno 2.3.2)

### Fixed Issues (if relevant)

1. magento/magento2#24555: Compare Function stop working for not salable products (mageno 2.3.2)

### Manual testing scenarios (*)

1. Having a product that is visible in the product catalog but not salable
2. Add the product to the compare list
3. Product is added to compare list and showing message "You added product to the compare list."

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sudheers-kensium** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [new Magento instance](https://pr-24568.instances.magento-community.engineering).
Admin access: [https://pr-24568.instances.magento-community.engineering/admin](https://pr-24568.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sudheers-kensium** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-24568-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24568-2-3-develop.instances.magento-community.engineering/admin](https://i-24568-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Hey @sudheers-kensium!
Could you please update the branch with latest `2.4-develop` and sing Adobe CLA. 
Thank you!

**Comment by lenaorobei** [comment]
Need to close this PR since issue was fixed by internal team. Please see https://github.com/magento/magento2/issues/24555 for more details.

**Pull request closed without merging**
