### PR TITLE
magento/magento2:#29479:Returns GraphQL impementation

### LINKED ISSUE #29479: Returns :: GraphQL Implementation
As a developer,

I want to create a flexible returns schema that can be added to the customer's account

so 

the end customer can view and manage their returns.  

**Acceptance Criteria** 

The new schema accommodates flexible returns management.
An approved and merged architecture PR for the schema.
A merged and approve code PR(s).

**Schema PR**
https://github.com/magento/architecture/pull/397

**Schema Updates**
Please update the following type and change the field name from id to uid. 

EnteredCustomAttributeInput
Return
ReturnItem
CustomAttribute
ReturnComment
ReturnShippingCarrier
ReturnShippingTracking
Attribute
AttributeOption

### PR DESCRIPTION
**Pull request by sasha19957099**
### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/402
https://github.com/magento/partners-magento2-infrastructure/pull/50

### Fixed Issues (if relevant)
Fixes https://github.com/magento/magento2/issues/29479

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by cpartica** [comment]
@magento run all tests

**Comment by sasha19957099** [comment]
@magento run all tests

**Comment by sasha19957099** [comment]
@magento run all tests

**Comment by sasha19957099** [comment]
@magento run all tests

**Comment by sasha19957099** [comment]
@magento run Functional Tests B2B

**Comment by sasha19957099** [comment]
@magento run all tests

**Comment by sasha19957099** [comment]
@magento run Functional Tests B2B

**Comment by sasha19957099** [comment]
@magento run all tests

**Comment by sasha19957099** [comment]
@magento run Functional Tests EE

**Comment by sasha19957099** [comment]
@magento run WebAPI Tests

**Pull request merged**
