### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by nasanabri**
Fixed typo in Magento/Framework/Oauth/Oauth.php

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @nasanabri. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21843) <br/>All committers have signed the CLA.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-4536](https://jira.corp.magento.com/browse/ENGCOM-4536) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@nasanabri thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by soleksii** [comment]
Not for manual testing

**Pull request merged**
