### PR TITLE
Fix #13401 - Multi-Store: "Store View" sort order values are not reflected in front-end store-switcher

### LINKED ISSUE #13401: Multi-Store: "Store View" sort order values are not reflected in the admin or front-end store-switcher
### Preconditions

1. Magento 2.2.2 
2. PHP 7.0

### Steps to reproduce

1. Create one website, with three Store Groups Each with 1 store
2. Within the Store view 1, set priority of 0, Store View 2, priority of 10, Store View 3, priority of 20
3. Save 
4. Reviewing admin grid of stores, the sort order does not change.
5. Reviewing store switcher on front-end, sort order does not change 

screen shot 2018-01-28 at 1 40 37 am

### Expected result

1. When changing the sort order of stores in the admin, their new sort order should be reflected on the admin grid and main store switcher. 

### Actual result

1. Nothing changes 

This feature works as expected in Magento 1.14.x and 1.9.x.  The business case, I want to be able to arrange my stores in the store switcher drop down by popularity or other arbitrary value.  This is not possible as the sort order value does nothing.  Additionally, if I have 100 stores, I want to be able to sort them in a way that makes sense in the admin.

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This fixes #13401
However I only modified sort order on FE, since on admin grid it seems to be sorted alphabetically, and not sure if that should be changed. If yes, I can adjust PR.

### Fixed Issues (if relevant)

1. magento/magento2#13401: Multi-Store: "Store View" sort order values are not reflected in the admin or front-end store-switcher

### Manual testing scenarios (*)

1. Create one website, with three Store Groups Each with 1 store
2. Within the Store view 1, set priority of 0, Store View 2, priority of 10, Store View 3, priority of 20
3. Review store switcher on front-end, sort order should impact order of stores visible

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by aleron75** [comment]
Hello @Bartlomiejsz. Thanks for your pull request.
I'm re-running some functionale tests because they failed, meanwhile can you please take a look at the conflicts on `app/code/Magento/Store/Test/Unit/Block/SwitcherTest.php`?
My best,
Alessandro

**Comment by Bartlomiejsz** [comment]
Hi @aleron75, done

**Comment by aleron75** [comment]
> Hi @aleron75, done

Thanks! Unfortunately, some functional tests fail, may I ask you to take a look at them?

My best,
Alessandro

**Comment by Bartlomiejsz** [comment]
> > Hi @aleron75, done
> 
> Thanks! Unfortunately, some functional tests fail, may I ask you to take a look at them?
> 
> My best,
> Alessandro

I checked all of failed tests, and none of those seem to be related to store switcher, so doesn't seem to be caused by my changes...

**Comment by aleron75** [comment]
Hello,
I also asked internally to understand whether there are some issues with the functional testing suite.
I'll keep you posted.
My best.

**Review by aleron75 — DISMISSED** [review]
Hello @Bartlomiejsz, it seems that the functional tests that fail are flaky, so I proceed to approve this PR.

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-7543](https://jira.corp.magento.com/browse/ENGCOM-7543) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento instance for you

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @Bartlomiejsz.

Unfortunately, looks like your changes don't solve the issue #13401 

**Manual testing scenario:**

1. A website with 3 Stores each with 1 Store view;
Screenshot from 2020-05-14 10-27-45
 
2. Set sort order for store views:
- Default -> 0
- Second Store View -> 30
- Third Store View -> 20

3. Go to Storefront;

**Actual Result:** :heavy_multiplication_x: Sorting has not changed

screenshot_10

**Expected Result:** :heavy_check_mark:  The Third Store should be above the Second Store

@Bartlomiejsz Could you take a look?

Thanks!

**Comment by Bartlomiejsz** [comment]
Hi @engcom-Alfa, that's true, I believe I misread steps for reproducing and I modified only sort order for switcher in header (with store views from current store). Last change fixes sort order also in footer.

**Comment by aleron75** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @aleron75. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @aleron75, here is your [new Magento instance](https://pr-28163.instances.magento-community.engineering).
Admin access: [https://pr-28163.instances.magento-community.engineering/admin_5e69](https://pr-28163.instances.magento-community.engineering/admin_5e69)
Login: `5b2ebb4f` Password: `f8c6f7473aee`
Instance will be terminated in up to 3 hours.

**Comment by aleron75** [comment]
Now it looks ok to me


image

image

**Review by aleron75 — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-7543](https://jira.corp.magento.com/browse/ENGCOM-7543) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. A website with 3 Stores each with 1 Store view;
Screenshot from 2020-05-14 10-27-45
 
2. Set sort order for store views:
- Default -> 0
- Second Store View -> 30
- Third Store View -> 20

3. Go to Storefront;

**Before:** :heavy_multiplication_x: Sorting has not changed

screenshot_10

**After:** :heavy_check_mark: Stores have correct sorting

screenshot_14

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Failed functional tests not related to changes from this PR.

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @Bartlomiejsz. Thanks for collaboration. I think this case can be covered by MFTF test, can you please cover it?

**Comment by Bartlomiejsz** [comment]
Hi @VladimirZaets, currently I don't have much time for that so that might take a while. Is that necessary? Unit test is already checking if stores with `sort_order` set are sorted in correct way, which is the only fix introduced in this PR.

**Comment by VladimirZaets** [comment]
Hi @Bartlomiejsz . Thanks for collaboration. It's required to cover it by mftf if the scenario is not covered yet. We will try to cover it by our internal team, but we can't merge it without the required coverage.

**Comment by engcom-Echo** [comment]
I will take care of test coverage.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-7543](https://jira.corp.magento.com/browse/ENGCOM-7543) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. A website with 3 Stores (2 with 1 Store view and one with 3Store views);
Screenshot from 2020-08-21 11-32-34

 
2. Set sort order for store views:
- Default -> 0
- Second Store View -> 20
- Third Store View -> 10
- Third Store View (3) -> 11
- Third Store View (2) -> 12

3. Go to Storefront;

**Before:** :heavy_multiplication_x: Sorting has not changed

screenshot_10

**After:** :heavy_check_mark: Stores have correct sorting

screenshot_14

Screenshot from 2020-08-21 11-35-08

**Pull request merged**
