### PR TITLE
fix: handle case-insensitive file extensions in media uploader

### LINKED ISSUE #38831: [Bug] Magento 2.4.7 doesn't allow product photo's with capital letter file extension.
### Preconditions and environment

- Magento version 2.4.7

### Steps to reproduce

1. Create a new product
2. Try to upload a picture with e.g. filename `DSCN0018.JPG`. The upload will fail.
3. Change the filename to `DSCN0018.jpg`. The upload succeeds.

Screenshot 2024-06-14 at 18 47 20

### Expected result

Image uploads with capital letter file extensions don't cause an error.

### Actual result

After upgrading to 2.4.7, Image uploads with capital letter file extensions are refused.

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by monteshot**
Ensure the media uploader handles file extensions in a case-insensitive manner by converting them to lower case before validation.

### Description (*)
fix: handle case-insensitive file extensions in media uploader

Ensure the media uploader handles file extensions in a 
case-insensitive manner by converting them to lowercase before 
validation.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38831

### Manual testing scenarios (*)
1. Create a new product
2. Try to upload a picture with e.g. filename DSCN0018.JPG. The upload will fail.
3. Change the filename to DSCN0018.jpg. The upload succeeds.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by monteshot** [comment]
@magento run all tests

**Comment by monteshot** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hello,

Internal team has started to work on it.

Thanks.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
As per this https://github.com/magento/magento2/pull/38924#issuecomment-2227896027, we are moving this PR `On hold`.

Thanks

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-12167 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-12167&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta1.

Thanks

**Pull request merged**
