### PR TITLE
Fixed upgrade issue if manufacturer attribute not exist in the database

### PR DESCRIPTION
**Pull request by suneet64**
Fixed upgrade issue if manufacturer attribute not exist in the database

### Description (*)

A fatal error while setup:upgrade if you are upgrading to Magento v2.3 from an earlier version and manufacturer attribute not exist in the existing database.

### Manual testing scenarios (*)

1. Have a Magento v2.2.6 clean installation.
2. Remove manufacturer attribute from Stores > Attributes > Product as it is not a system attribute.
3. Upgrade the Magento to v2.3 using command line
4. Enable the display_errors from app/bootstrap.php file.
5. **Before:** Execute setup:upgrade and while upgrading data you will notice a fatal error because of missing manufacturer attribute.
**After:** The fatal error disappear in this fix.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19514) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @suneet64. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3603](https://jira.corp.magento.com/browse/ENGCOM-3603) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@suneet64 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by hostep** [comment]
Tnx @suneet64! Would be great if a similar fix could get backported to `2.2-develop` to fix: https://github.com/magento/magento2/issues/18134

**Comment by suneet64** [comment]
Hi @hostep, Just applied a fix for `2.2-develop` under https://github.com/magento/magento2/pull/19551. Hopefully, it get approved.

**Comment by sivaschenko** [comment]
Hi @suneet64 @suneet-magento can you please sign the [Contributor License Agreenment](https://cla.dev.magento.com/magento/magento2?pullRequest=19514) so that we can continue processing the PR.

**Comment by suneet64** [comment]
Hi @sivaschenko, the agreement has been signed. Please proceed further. Thanks!

**Comment by nickpiro** [comment]
Has this been fixed in 2.2.6?!

**Comment by sivaschenko** [comment]
Hi @nickpiro the fix to 2.2 ([here it is](https://github.com/magento/magento2/pull/19551)) will be processed after this pull request will be merged.

**Comment by magento-engcom-team** [comment]
Hi @suneet64. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
