### PR TITLE
MFTF: Replace redundant Action Group with proper one - magento/module-page-cache

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Remove one redundant Action Group 
Replace references to the right one.

@rogyar / @okolesnyk Please keep in mind that the tests there do not test anything!

### Fixed Issues (if relevant)
1. magento/magento2#22853

### Questions or comments
Had to extract the changes per-module. The previous try failed, because of conflicts.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hi @lbajsarowicz, could please also copy the `annotations/description` from the removed `clearPageCache ` action group to `ClearPageCacheActionGroup` one?

**Review by dmytro-ch — APPROVED** [review]
> could please also copy the annotations/description from the removed clearPageCache action group to ClearPageCacheActionGroup one?

Sorry, my mistake. It's already there.

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6362](https://jira.corp.magento.com/browse/ENGCOM-6362) has been created to process this Pull Request
:eight_spoked_asterisk: @dmytro-ch, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by lbajsarowicz** [comment]
@okolesnyk / @okorshenko / @dmytro-ch / @VladimirZaets 

Dear Maintainers, due to your concerns about **backward compatibility**, I provided the `_Deprecated_ActionGroup.xml` that provides the deprecated ActionGroups that will be loaded like before, but extra **comment** was added to notify about **depreciation**.

Hope that will let you merge that sooner than with `2.4`

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6362](https://jira.corp.magento.com/browse/ENGCOM-6362) has been created to process this Pull Request

**Pull request merged**
