### PR TITLE
Fix 27633 duplicate property style

### LINKED ISSUE #27633: Sales Order grid checkbox alignment issue in Admin
Sales Order grid checkbox alignment issue

### Preconditions (*)

1. Magento: 2.3.4

### Steps to reproduce (*)

1. Admin -> Sales -> Orders
2.

### Expected result (*)

1. checkbox vertical-alignIt should be top 
image

### Actual result (*)

1. checkbox vertical-alignIt is middle
image

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Just remove duplicate property line for checkbox element in grid.
Previously we have 2 declares with same property vertical-align in same element

### Fixed Issues (if relevant)

1. magento/magento2#27633: Sales Order grid checkbox alignment issue in Admin

### Manual testing scenarios (*)

1. Magento 2.3.4+
2. Go to backend and see any grid checkbox

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Seems like issue was added in https://github.com/magento/magento2/pull/20237

**Comment by mrtuvn** [comment]
@ihor-sviziev thanks for your reference link
This not high priority PR just clean up from my perspective view. We no need duplicate thing in code for do one job

**Comment by rogyar** [comment]
The failing tests are not related to the current fix

**Review by rogyar — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7281](https://jira.corp.magento.com/browse/ENGCOM-7281) has been created to process this Pull Request

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @mrtuvn 

During testing, we faced the issues

**Manual testing scenario:**

1. Go to Admin -> System -> Cache Management

**Actual Result:** :heavy_multiplication_x:  Checkboxes have the wrong position

Screenshot from 2020-04-10 14-06-10

2. Go to Admin -> System -> Index Management

**Actual Result:** :heavy_multiplication_x: The same result as with cache

Screenshot from 2020-04-10 14-08-32

@mrtuvn Could you take a look?

Thanks!

**Comment by mrtuvn** [comment]
@engcom-Alfa i will check that again. In fact we should make the checkbox align in middle of the box instead

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7281](https://jira.corp.magento.com/browse/ENGCOM-7281) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
