### PR TITLE
Add a link to the cart to the success message when adding a product (Magento 2.3)

### PR DESCRIPTION
**Pull request by avstudnitz**
Copy of https://github.com/magento/magento2/pull/13904 for the 2.3-branch.

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@sidolov you've merged original PR recently. Could you process also this PR?

**Comment by sidolov** [comment]
@ihor-sviziev , sure, I'm working on it now

**Comment by ihor-sviziev** [comment]
Hi @sidolov,
Looks like it stuck. Is there any issues with this PR?

**Comment by sidolov** [comment]
@ihor-sviziev , yes, you are right, this port cause performance build failures and several MFTF tests are broken due to message change

**Comment by ihor-sviziev** [comment]
@sidolov maybe @avstudnitz could update some tests if needed?

**Comment by avstudnitz** [comment]
Travis fails because it tries to run on PHP 7.0 while Magento 2.3 only supports PHP 7.1+. This is not something I can fix @sidolov @ihor-sviziev.
Where can I see the failed MFTF tests=

**Comment by magento-engcom-team** [comment]
Hi @avstudnitz. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Pull request merged**
