### PR TITLE
fixed creating admin Integrations

### LINKED ISSUE #28996: Royalmail Click & Drop Integrations Magento 2
The attempt to post data to consumer failed due to an unexpected error. Please try again later.

### Preconditions (*)

1. Magento 2.4-develop
2. 

### Steps to reproduce (*)

1. image
2. image
3. image
4. image

### Expected result (*)

1. No errors during integration

### Actual result (*)

1. Error when try to activate integration
image
image

### Additional information
Issue is reproducible on 2.4-develop locally according scenario from https://jira.corp.magento.com/browse/MAGETWO-79809

### PR DESCRIPTION
**Pull request by engcom-Charlie**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#28996

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by eduard13 — APPROVED** [review]
Thank you for the fix 👍

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8753](https://jira.corp.magento.com/browse/ENGCOM-8753) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:** :heavy_multiplication_x: 

Screenshot from 2021-02-11 10-04-14

**After:** :heavy_check_mark: 

Screenshot from 2021-02-11 10-22-40

**Pull request merged**
