### PR TITLE
fix function return type

### PR DESCRIPTION
**Pull request by maslii**
### Description (*)

Function getLastPageNumber supposed to return Integer type, but actual result most of the time is of type Float.

### Manual testing scenarios (*)

1. Any usage of method getLastPageNumber of Framework/Data/Collection class.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24142) <br/>All committers have signed the CLA.

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-5628](https://jira.corp.magento.com/browse/ENGCOM-5628) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@maslii thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5628](https://jira.corp.magento.com/browse/ENGCOM-5628) has been created to process this Pull Request

**Pull request merged**
