### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by orlangur**

### CODE REVIEW

**Comment by evgk** [comment]
According to this link:
https://www.quora.com/Which-is-the-correct-grammar-usage-a-unique-or-an-unique

It should be "a unique", actually

**Comment by orlangur** [comment]
Thanks @evgk,

> Use "an" before the words that start from vowels A, E, I, O, U. But that **is not** the 100% foolproof method.`

I didn't even try to google for it. Will force push a corrected version soon.

**Comment by orlangur** [comment]
Fixed and rebased against latest mainline.

**Comment by orlangur** [comment]
Any idea why such a simple change is processed for more than a month already?

**Comment by keradus** [comment]
:+1: :shipit:

**Comment by vrann** [comment]
@orlangur thank you, Vlad, merged.

**Pull request merged**
