### PR TITLE
Fix hard-code scope store string

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Clean up string scope store and also clean up file test 
### Fixed Issues (if relevant)

1. No issue available

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by omiroshnichenko — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
Hi, @mrtuvn. Could you fix failing tests?
Thanks!

**Comment by engcom-Alfa** [comment]
Hi @omiroshnichenko.
Could you review the latest changes? Thanks!

**Comment by mrtuvn** [comment]
> Hi, @mrtuvn. Could you fix failing tests?
> Thanks!

i have fixed test

**Review by omiroshnichenko — DISMISSED** [review]

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by mrtuvn** [comment]
also this PR quite long response ! Should i need extra test

**Comment by mrtuvn** [comment]
Can we have new process on this

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7282](https://jira.corp.magento.com/browse/ENGCOM-7282) has been created to process this Pull Request

**Pull request merged**
