### PR TITLE
Fixed Catalog Product - Customizable Options label alignment issue

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)

Catalog Product - Customizable Options 2nd and third label alignment issue
### Fixed Issues (if relevant)

1. magento/magento2#19492: Catalog Product - Customizable Options label alignment issue

### Manual testing scenarios (*)

1.Not Required for designing alignment issue

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @emiprotech. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
@emiprotech thanks for your contribution. Please take a look if this is a duplicate to https://github.com/magento/magento2/pull/19493

**Comment by ghost** [comment]
@sivaschenko,
but my changes and #19493 changes are different though is it a duplicate pull request ?

**Comment by VladimirZaets** [comment]
@emiprotech They are resolved the same issue

**Pull request closed without merging**
