### PR TITLE
Fix Add to Cart

### PR DESCRIPTION
**Pull request by quienti**
Issue :
https://github.com/magento/magento2/issues/5144
https://github.com/magento/magento2/issues/5266

Thank to @Zaylril for your fix !

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=5854) <br/>All committers have signed the CLA.

**Comment by minhluan259** [comment]
@quienti , I think you should change the code

```
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": true
            }
        }
    }
</script>
<?php endif; ?>
```

to

```
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": true
            }
        }
    }
</script>
<?php else : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php endif; ?>
```

It's better.

**Comment by vasilii-b** [comment]
Fixing code from @minhluan259 works great but page is still refreshed if you get a message like this: http://prntscr.com/c29gzw -> _We don't have as many --- as you requested._

**Comment by minhluan259** [comment]
@vasilii-b , Because you add qty product > qty in stock, that message will show.

**Comment by vasilii-b** [comment]
@minhluan259 yes, I understand this, BUT: why is the minicart updated to 0 items meanwhile I actually have items in cart ? :/

**Comment by adragus-inviqa** [comment]
@quienti - what happened?

**Comment by quienti** [comment]
Oops, I reopens a new pull request ! Sorry
Edit : I think it is fixed in last develp branch

**Comment by adragus-inviqa** [comment]
Yeah, I've seen some changes in there. Thanks for the PR anyway. 👍

**Comment by minhluan259** [comment]
@quienti 
The issue was fixed, Why has it still not been updated in magento version 2.1.4?

**Comment by quienti** [comment]
I don't know, but is fixed in develop branch, so for Magento 2.2

**Pull request closed without merging**
