### PR TITLE
Make page title in layout files translatable

### PR DESCRIPTION
**Pull request by AntonEvers**
### Description

Make it possible to translate page titles that are provided in the layout xml files.

### Fixed Issues (if relevant)

1. magento/magento2#6337: Not able to translate page layout head titles

### Manual testing scenarios

1. translate one of the page titles that have been altered in this pull request
2. flush the cache 
3. visit the page
4. see that the title is translated

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by miguelbalparda** [comment]
Hi @ajpevers, thanks for the PR! I just re run the tests and they appear to be all green now, will get back to you in case we have any questions.

**Comment by miguelbalparda** [comment]
@ajpevers from the internal automated testing we got

> Function __() is defined outside of the library and must not be used there. Replacement suggestion: new \Magento\Framework\Phrase()

Can you adapt this PR to that suggestion?
Thanks!

**Comment by AntonEvers** [comment]
Sure! I'm on a holiday right now but I will get back to you.

**Comment by okorshenko** [comment]
Hi @ajpevers we fixed this issue on our side. Thank you

**Pull request merged**
