### PR TITLE
use "Module_Name::template/path" format instead of using template/path i…

### PR DESCRIPTION
**Pull request by Jakhotiya**
…n Block class to ensure extensibility of the class. not doing so causes invalid template errors after extending the block class via preference

### Description
Often third party modules override core block classes. If the source block classes reference a template without specifying module name like "Vendor_Module::template_path" then block render fails with "nvalid template file: " error.

### Manual testing scenarios

1. Overide the \Magento\Review\Block\Product\ReviewRenderer Block in your custom module via di preference. Leave your custom class empty.
2.  Product details should work.

### Contribution checklist
 - [ x] Pull request has a meaningful description of its purpose
 - [ x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14946) <br/>All committers have signed the CLA.

**Review by larsroettig — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @larsroettig, thank you for the review.
[ENGCOM-1434](https://jira.corp.magento.com/browse/ENGCOM-1434) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@Jakhotiya thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by larsroettig** [comment]
Hi, @Jakhotiya, thank you for collaboration.

**Comment by magento-engcom-team** [comment]
Hi @Jakhotiya. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

**Pull request merged**
