### PR TITLE
Use version_compare to compare version strings correctly

### PR DESCRIPTION
**Pull request by schmengler**
### Description
Version numbers were compared with regular alphanumeric string comparison `<`, which results in `1.10 < 1.9`. Instead, `version_compare` should be used

### Manual testing scenarios
1. Update a module from version 1.9.0 to 1.10.0 and open the shop in the browser
2. Expected message: "run setup:upgrade", not "run composer install"

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18173) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18173) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
Hi @schmengler. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by ihor-sviziev** [comment]
Hi @schmengler,
Good catch!
Please sign CLA, otherwise we can't process your pull request

**Review by slavvka — APPROVED** [review]

**Comment by slavvka** [comment]
Hi @schmengler, we need the fix to be delivered also to 2.2-develop branch so please don't forget to port this PR to 2.2-develop; you can do it easily using the Porting Tool, https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool

**Comment by magento-engcom-team** [comment]
Hi @slavvka, thank you for the review.
[ENGCOM-3051](https://jira.corp.magento.com/browse/ENGCOM-3051) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @schmengler. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
