### PR TITLE
Random API migration

### PR DESCRIPTION
**Pull request by MathiasReker**
Replaces rand, srand, getrandmax functions calls with their mt_* analogs.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @MathiasReker. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by MathiasReker** [comment]
I closed all my PR's again.

**Comment by orlangur** [comment]
@MathiasReker just discovered such change does not make sense for PHP 7.1+: https://stackoverflow.com/a/28760905

**Comment by MathiasReker** [comment]
For PHP 7, you should you random_int() doc: http://php.net/manual/en/function.random-int.php

**Comment by orlangur** [comment]
@MathiasReker I don't see `random_int` used in this PR. Replacing `rand` to `mt_rand` does not make sense as in PHP 7.1+ `rand` is an alias for `mt_rand` (and this is a target version for 2.3: https://github.com/magento/magento2/blob/2.3-develop/composer.json#L14)

**Comment by MathiasReker** [comment]
I did not see that the repo was 7.1 +

**Pull request closed without merging**
