### PR TITLE
[MFTF] Add AssertStorefrontCartDiscountActionGroup 

### LINKED ISSUE #30784: [Issue] [MFTF] Add AssertStorefrontCartDiscountActionGroup
This issue is automatically created based on existing pull request: magento/magento2#30776: [MFTF] Add AssertStorefrontCartDiscountActionGroup 

---------
This PR provided new `AssertStorefrontCartDiscountActionGroup`

### PR DESCRIPTION
**Pull request by Usik2203**
This PR provided new `AssertStorefrontCartDiscountActionGroup` 

### Resolved issues:
1. [x] resolves magento/magento2#30784: [MFTF] Add AssertStorefrontCartDiscountActionGroup

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Review by rogyar — APPROVED** [review]
Hi @Usik2203. Good job. Next time it's not necessary to use the upper case for "Backward Compatibility" ;)

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8431](https://jira.corp.magento.com/browse/ENGCOM-8431) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@engcom-Hotel can you fix the conflicts, please? Thanks!

**Comment by engcom-Charlie** [comment]
@gabrieldagama I'll fix conflicts.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8431](https://jira.corp.magento.com/browse/ENGCOM-8431) has been created to process this Pull Request

**Pull request merged**
