### PR TITLE
remove static function for can add visibility with plugin

### PR DESCRIPTION
**Pull request by baudeval**
For add visibility values without override all model

### Description (*)
The objective of this Pull Request is remove static on getOptionArray method of visibility model for can add custom visibility values with plugin on method actually for add custom visibility it is necassary tu override the model and a lot of method like getAllOption... see https://magento.stackexchange.com/questions/203822/how-to-override-a-static-method-in-magento2 and this override is not realy good for the maintenace of the website.

### Fixed Issues (if relevant)
This Pull request resolve problem explain here https://magento.stackexchange.com/questions/203822/how-to-override-a-static-method-in-magento2

### Manual testing scenarios (*)

1. Create plugin after on method getOptionArray of file Magento\Catalog\Model\Product\Visibility and add your custom visibility values

### Questions or comments
This Pull request resolve problem explain here https://magento.stackexchange.com/questions/203822/how-to-override-a-static-method-in-magento2

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by baudeval** [comment]
@magento give me test instance

**Comment by baudeval** [comment]
@magento run all tests

**Comment by MeCapron** [comment]
@magento run all tests

**Comment by MeCapron** [comment]
@magento run all tests

**Comment by baudeval** [comment]
@magento run all tests

**Comment by MeCapron** [comment]
@magento run all tests

**Pull request closed without merging**
