### PR TITLE
Fix inability to place PayPal guest order when Automatic Assignment to Customer Group is enabled

### LINKED ISSUE #25399: Unable to place a guest order with PayPal Express when Enable Automatic Assignment to Customer Group is enabled
### Preconditions (*)

1. Magento 2.4-develop
2. PayPal Express payment method is enabled and configured
3. Option "Enable Automatic Assignment to Customer Group" is set to "Yes" in the Customers > Customer configuration settings section

### Steps to reproduce (*)
1. Make sure you are logged off from your Magento customer account
2. Put anything to the cart
3. Go to the cart and click "Checkout with PayPal" button
4. Login to your PayPal account, choose the payment instrument and other options if applicable
5. After being redirected back to the order review page, choose shipping method and click "Place order" button

### Expected result (*)
The payment is processed on PayPal gateway, the order is created in Magento, customer sees order thank-you page

### Actual result (*)
The payment is processed succesfully on PayPal gateway, but the order is not created in Magento because of "Failed address validation: %1" error, which is shown to the customer on the order review page, which the buyer is redirected to instead of the thank-you page

paypal_place_order_error

### PR DESCRIPTION
**Pull request by xylodev**
One of our shops reported that customers are unable to place a guest orders using the PayPal Express payment method. After some investigation it found out that this issue is caused by wiping out the customer email address from the quote model during the automatic assignment to the customer group. Moreover, the inability of placing the order is the case only when the PayPal is triggered from the cart by clicking "Checkout with PayPal" button. When one tries to make a guest order using PayPal in the payment method step in the checkout, the order is placed correctly due to the obvious reason, the e-mail address is explicitly set by the buyer during the 1st step of the checkout and thus it is correctly propagated to the corresponding customer object. This isn't the case when PayPal is started from the cart level.

### Description (*)
This PR implements setting an e-mail address on the customer object assigned to quote, which is prepared for the furthr processing by PayPal module when the checkout is recognized as a guest one. The e-mail address is set only when the corresponding customer object doesn't have it set yet.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#25399 : Unable to place a guest order with PayPal Express when Enable Automatic Assignment to Customer Group is enabled

### Manual testing scenarios (*)
1. Configure and enable PayPal Express payment method, especially make sure that the button is shown in the cart
2. In the Magento admin configuration, go to Customers > Customer Configuration and set Enable Automatic Assignment to Customer Group to Yes
3. Make sure you are NOT logged in to your Magento customer account
4. Put any product to the cart and go to the cart page
5. Click "Checkout with PayPal" button, next login to your PayPal account and select payment instrument
6. Once you are redirected back to the order review page, select a shipping method and click "Place Order" button
7. The expected result is the order success page and the payment correctly processed by PayPal

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by xylodev** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @xylodev. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @xylodev, here is your [new Magento instance](https://pr-25405.instances.magento-community.engineering).
Admin access: [https://pr-25405.instances.magento-community.engineering/admin](https://pr-25405.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by xylodev** [comment]
I can confirm that the issue is resolved on the provided test instance

**Comment by aleron75** [comment]
Hello @xylodev thank you for your contribution!

Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. 

For this specific case, you should cover your fix by automated tests with the scenario which leads to an issue. Tests should fail on the mainline and pass with your fix.

A starting point could be extending the `\Magento\Paypal\Test\Unit\Model\Express\CheckoutTest`.

Thank you again!

**Comment by askmikeyd** [comment]
I was having the same issue and I don't think the proposed solution is the way to go. This only solves it for Paypal but this issue exists when using other payment methods as a guest. A better solution needs to be done in the Magento Core. My fix for it was to set "Enable Automatic Assignment to Customer Group" to "Yes" at the website level as that is where my customer is created and set it to "No" at the store level which is what is checked when placing a guest order.

**Comment by sidolov** [comment]
@xylodev do you have plans to cover another checkout scenario? Looks like the issue is fixed for PayPal only.

**Comment by xylodev** [comment]
@sidolov I will review this issue next week and, depending on the review outcome, I will try to provide more general fix with the test coverage

**Review by sidolov — CHANGES_REQUESTED** [review]
Waiting for additional coverage of all scenarios.

**Comment by engcom-Charlie** [comment]
Hi @xylodev could you please provide a general fix with test coverage?
Thank you.

**Comment by engcom-Charlie** [comment]
@xylodev I'll continue with your PR.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by sidolov** [comment]
Pull request successfully imported to branch `imported-magento-magento2-25405` in the `magento-engcom/magento2ce` repository.

**Review by sidolov — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8173](https://jira.corp.magento.com/browse/ENGCOM-8173) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento give me test instance

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
@xylodev Could you resolve merge conflicts?
Thanks!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8173](https://jira.corp.magento.com/browse/ENGCOM-8173) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento give me test instance

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Configure and enable PayPal Express payment method, especially make sure that the button is shown in the cart;
2. In the Magento admin configuration, go to Customers > Customer Configuration and set Enable Automatic Assignment to Customer Group to Yes;
3. Make sure you are NOT logged in to your Magento customer account;
4. Put any product to the cart and go to the cart page;
5. Click the "Checkout with PayPal" button, next login to your PayPal account, and select payment instrument;
6. Once you are redirected back to the order review page, select a shipping method and click the "Place Order" button;

**Before:** :heavy_multiplication_x: The payment is processed successfully on PayPal gateway, but the order is not created in Magento because of "Failed address validation: %1" error

Screenshot from 2020-09-15 15-16-38

**After:** :heavy_check_mark: The payment correctly processed by PayPal and the order is successfully created

Screenshot from 2020-09-15 15-11-37

Also, was tested with disabled _Automatic Assignment to Customer Group_, placing an order from payment method step, from the cart page and everything works as expected.

**Pull request merged**
