### PR TITLE
Resolve "Send Payment Failed Email Copy To" field has no validate email issue24312

### LINKED ISSUE #24312: "Send Payment Failed Email Copy To" field has no validate email
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Store->Configurations
3. Sales->Checkout
4. In "Payment Failed Email"->"Send Payment Failed Email Copy To", fill "test"
5. Save

### Expected result (*)

1. Can not save because it is not email

### Actual result (*)

1. Save normally

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#24312:  "Send Payment Failed Email Copy To" field has no validate email 

Solution: Add "validate-emails" in app/code/Magento/Checkout/etc/adminhtml/system.xml

### Fixed Issues (if relevant)

1. magento/magento2#24312:  "Send Payment Failed Email Copy To" field has no validate email 
2. magento/magento2#24307: Many field has no validate number in Checkout settings
3. magento/magento2#24304: No validate "Proxy Port" in Paypal Module (Paypal Express, Paypal Payflow -Link, Pro, Advanced)
4. magento/magento2#24302: No validate "Day" in PayPal Express Checkout Settings

### Manual testing scenarios (*)

1. Go to backend
2. Store->Configurations
3. Sales->Checkout
4. In "Payment Failed Email"->"Send Payment Failed Email Copy To", fill "test"
5. Save

#### Expected result

1. Can not save because it is not email

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by swnsma — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-5710](https://jira.corp.magento.com/browse/ENGCOM-5710) has been created to process this Pull Request

**Review by dmytro-ch — DISMISSED** [review]
Hi @edenduong,
please, combine the pull requests with such improvements in one single pull request in order to make it easier to process these PRs by Community Engineering Team.
#24313
#24309
#24303 
#24305
Also, feel free to create pull requests for minor fixes and obvious improvements without opening the issues.

Thank you!

**Comment by edenduong** [comment]
> Hi @edenduong,
> please, combine the pull requests with such improvements in one single pull request in order to make it easier to process these PRs by Community Engineering Team.
> #24313
> #24309
> #24303
> #24305
> Also, feel free to create pull requests for minor fixes and obvious improvements without opening the issues.
> 
> Thank you!

Thank you for your suggestion. But I think They are **different Validation** and  different datatype and belong different module so I don't think we should merge it to one PR.

**Comment by dmytro-ch** [comment]
@edenduong, this approach looks like cheating.
Please combine the mentioned pull requests with minor changes in one PR.
Otherwise, I will have to mark them as cleanup.

Thank you!

**Comment by swnsma** [comment]
@magento combine 24313 24309 24303 24305

**Comment by dmytro-ch** [comment]
@magento combine 24309 24303 24305

**Comment by swnsma** [comment]
@magento combine 24309 24303 24305

**Comment by swnsma** [comment]
@magento combine 24309 24303 24305

**Comment by swnsma** [comment]
@magento combine 24309 24303 24305

**Comment by sidolov** [comment]
@magento combine 24309 24303 24305

**Comment by magento-engcom-team** [comment]
Hi @sidolov. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
@edenduong all pull requests have been successfully combined together: 
 - merged https://github.com/magento/magento2/pull/24309: Resolve Many field has no validate number in Checkout settings issue24307
 - merged https://github.com/magento/magento2/pull/24303: Resolve No validate "Day" in PayPal Express Checkout Settings issue24302
 - merged https://github.com/magento/magento2/pull/24305: Resolve No validate "Proxy Port" in Paypal Module (Paypal Express, Paypal Payflow -Link, Pro, Advanced) issue24304

**Review by sidolov — APPROVED** [review]

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5710](https://jira.corp.magento.com/browse/ENGCOM-5710) has been created to process this Pull Request

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5710](https://jira.corp.magento.com/browse/ENGCOM-5710) has been created to process this Pull Request

**Comment by edenduong** [comment]
> @edenduong, this approach looks like cheating.
> Please combine the mentioned pull requests with minor changes in one PR.
> Otherwise, I will have to mark them as cleanup.
> 
> Thank you!

image

OK , it shoud be merge. But Why you don't merge two PR? Thank you !

**Comment by edenduong** [comment]
> @edenduong, this approach looks like cheating.
> Please combine the mentioned pull requests with minor changes in one PR.
> Otherwise, I will have to mark them as cleanup.
> 
> Thank you!

image


image

image

image


OK , it shoud be merge. But Why you don't merge these PR? They are absolutely the **SAME** source code, the **same module**, and they are created **BEFORE** my PR .
And I think replace Deprecated Method absolutely is **CLEAN UP** . It is not fair  @dmytro-ch   @sidolov 

Thank you !

**Comment by edenduong** [comment]
> @edenduong, this approach looks like cheating.
> Please combine the mentioned pull requests with minor changes in one PR.
> Otherwise, I will have to mark them as cleanup.
> 
> Thank you!

image


image

image


OK , it shoud be merge. But Why you don't merge these PR? They are absolutely the **SAME** source code, the **same module**.
And I think replace Deprecated Method absolutely is **CLEAN UP** .  It is not fair for me and I am really sad for that.  @dmytro-ch   @sidolov 

The Validation Problem is absolutely **BUG**. It is bad thing if you save the **WRONG** data to database and **NO Warning** to the User.  If user can know what they need to fill in the form, you don't need validate anything. 

Thank you !

**Comment by engcom-Alfa** [comment]
Hi @edenduong 

It would be nice if you added description (for ex. "Please enter at least 0 and at most 65535") under "Proxy Port"  input fields, because in validation for proxy you used `digits-range-0-65535`. This will be clearer.

@edenduong Could you take a look, please?

Thanks!

**Comment by dmytro-ch** [comment]
@edenduong, these pull requests are still in progress.
We will check them and merge if it is reasonable.

Thank you!

**Comment by edenduong** [comment]
> Hi @edenduong
> 
> It would be nice if you added description (for ex. "Please enter at least 0 and at most 65535") under "Proxy Port" input fields, because in validation for proxy you used `digits-range-0-65535`. This will be clearer.
> 
> @edenduong Could you take a look, please?
> 
> Thanks!

@engcom-Alfa : Thank for your feedback. I have changed the source code. Please check it again. Thanks.
@dmytro-ch: Ok . You should ask  your colleague changed and it will be combined soon. It is not fair if they aren't combined and they are "improvement", only change Method name. They are Clean Up.

**Comment by sidolov** [comment]
@edenduong thank you for the input! PRs #24340 #24334 #24284 are combined to one now. 
Regarding the achievement - it still may be reconsidered before the delivery to the mainline branch, we are trying to be fair with all Magento contributors, thank you for your collaboration!

**Comment by dmytro-ch** [comment]
> It is not fair if they aren't combined and they are "improvement", only change Method name. They are Clean Up.

@edenduong, If you check the source code of those PRs, you will see that such refactoring requires much more efforts than it looks at first. (e.g. #24197,  #24340)
Please be polite and respect other contributors.

Thank you!

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5710](https://jira.corp.magento.com/browse/ENGCOM-5710) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
