### PR TITLE
Fix Issue #12202

### PR DESCRIPTION
**Pull request by nadeefit6**
Fix Issue #12202 M2.1.9 : Cannot make all address fields required in customer address edit page (frontend)

### Description
Edit  magento2/app/code/Magento/Customer/view/frontend/templates/address/edit.phtml

### Fixed Issues

1. magento/magento2#12202: Cannot make all address fields required in customer address edit page (frontend)

### Manual testing scenarios
1. Edit  magento2/app/code/Magento/Customer/view/frontend/templates/address/edit.phtml
2. Add required class for additional address fields
3. Check in frontend -> My account address edit page
4. Additional address fields should be validated as required

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15475) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=15475) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: vgelani<br/>:x: nadeefit6

**Comment by nadeefit6** [comment]
Issue is fixed in following commit
https://github.com/magento/magento2/commit/d09c832

**Comment by VladimirZaets** [comment]
Hi @nadeefit6, thank you for collaboration.
Currently, we have the PR with the more general solution to this problem.
Please look this [PR](https://github.com/magento/magento2/pull/15383)

**Comment by magento-engcom-team** [comment]
@nadeefit6 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VladimirZaets** [comment]
@nadeefit6, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Comment by hitesh-wagento** [comment]
Hi @VladimirZaets

Can I create new branch and do above changes again ?

**Pull request closed without merging**
