### PR TITLE
#26499 Always transliterate product url key

### LINKED ISSUE #26499: Product url key is not transliterated anymore if already set
### Preconditions (*)

1. Affected versions: 2.2.9, 2.3.3 (not verified by myself but responsible code is the same: 2.2.10, 2.4-develop)

### Steps to reproduce (*)

1. Edit a product and add "test url key" as url key
2. Save the product

This can be reproduced via rest API too by updating a product url key.

### Expected result (*)

1. Url key is transliterated to "test-url-key"

### Actual result (*)

1. Url key is still "test url key"

### Additional information

- This bug was introduced with this commit: 6f4f511822fbbcb743a7d4a8de6353d207d99429
- Responsible code in [\Magento\CatalogUrlRewrite\Model\ProductUrlPathGenerator::prepareProductUrlKey](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogUrlRewrite/Model/ProductUrlPathGenerator.php#L101)
- I am not sure if reverting the line back to `return $product->formatUrlKey($urlKey === '' || $urlKey === null ? $product->getName() : $urlKey);` will break arabic urls again so we might have to find a different solution.

### PR DESCRIPTION
**Pull request by DanieliMi**
### Description (*)

`\Magento\CatalogUrlRewrite\Model\ProductUrlPathGenerator::prepareProductUrlKey` will always call `\Magento\Catalog\Model\Product::formatUrlKey` in order to transliterate it and avoid spaces, non latin characters, etc. in url_key.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#26499 : Product url key is not transliterated anymore if already set

### Manual testing scenarios (*)

1. Edit a product and add "test url key" as url key
2. Save the product
3. Now the url key will be "test-url-key" as it behaved prior to 2.3.3 and 2.2.9

This can be reproduced via rest API too by updating a product url key.

### Questions or comments

It might conflict with the issue that has been fixed in 6f4f511822fbbcb743a7d4a8de6353d207d99429. If the tests fail we'll have to think of a different solution.
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento run all tests

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @DanieliMi.

Thank you for your collaboration. I would ask you to take a look at the failing functional tests. According to the screenshot, it looks like the system tries to open a testable product using the wrong URL after changes introduced in the current PR.

**Comment by DanieliMi** [comment]
Exactly it tries to visit the product page based on the product name with spaces in it. This PR aims to replace the spaces with '_'. I'll have to update the according tests.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by DanieliMi** [comment]
@rogyar I've had a look at the functional tests and fixed them. Currently static tests and database tests are failing.

The static tests fail due to a missing class description, I am not sure what it best could be since I only changed a line in the class do you have any ideas?

I am not sure how the database compare tests work and how to fix them could you assist me with them?

**Comment by engcom-Echo** [comment]
I will try fix it.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7064](https://jira.corp.magento.com/browse/ENGCOM-7064) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@DanieliMi thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
