### PR TITLE
Page title not showing on product page.

### PR DESCRIPTION
**Pull request by chirag-wagento**
### Description
Solve Page title issue on product page

### Fixed Issues (if relevant)

1. magento/magento2#16249: https://github.com/magento/magento2/issues/16249

### Manual testing scenarios

1. You can check on product detail page between title tags.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @chirag-wagento. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on Pull Request changes
- `@magento-engcom-team give me new test instance` - deploy **NEW** test instance based on Pull Request changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy Vanilla Magento instance for Issue or Pull Request

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by ishakhsuvarov** [comment]
Hi @chirag-wagento 
Some commits in this Pull Request seem to be unrelated to the item you are attempting to fix.
Please make sure you base your PR's on a clean branch.

Thanks

**Comment by chirag-wagento** [comment]
@ishakhsuvarov  fixed my commit pull requisite  changes.

Now you can check.

Thanks

**Comment by ishakhsuvarov** [comment]
@chirag-wagento It still seems to contain wrong commit history and unrelated files in a changeset.
It would be better to start with a clean branch and cherry pick commit with the actual fix

**Pull request closed without merging**
