### PR TITLE
Fix referenced to "store", changing to "scope" in Framework/Mail components

### PR DESCRIPTION
**Pull request by gwharton**
### Description (*)
Changes introduced in PR#18471 used references to "store" in framework components. This PR changes these references to "scope" instead. The same changes are being proposed to the 2.2-develop branch in PR #18472.

The setFromByStore function is deprecated and a new function setFromByScope is introduced.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-3969](https://jira.corp.magento.com/browse/ENGCOM-3969) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @gwharton thank you for the pull request, however, we cannot accept this contribution. We are not accepting new public methods to classes marked as API. I have to close this pull request.

Please feel free to contact me if you have any comments or questions.

**Comment by gwharton** [comment]
@ihor-sviziev can you let me know the way forward on this. The same changes are also proposed as part of #18472 and were requested by @buskamuza.

If this PR doesn't go through, then it doesn't affect the way magento works, its just a naming thing, but if it also holds up #18472 and we miss the 2.2.8 deadline, then the other changes in #18472 would not get applied and the 2.2 branch would go for another 2-3 months with broken email sender from addresses.

**Comment by ihor-sviziev** [comment]
Hi @gwharton,
Will contact @buskamuza and will decide what to do

**Comment by buskamuza** [comment]
The new method (`setFromByStore()`) has been added in https://github.com/magento/magento2/pull/18471 . This PR only renames it according to a previous discussion. This change does not impact backward compatibility, so it should be possible to merge it.

**Comment by sivaschenko** [comment]
Hi @gwharton , sorry for the confusion. Reopening as the backward incompatible change was approved by an architect. This pull request will be soon merged to mainline.

**Pull request merged**
