### PR TITLE
[Backport] view-order-price-subtotal-alignment-not-proper-mobile

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Original Pull Request 
 https://github.com/magento/magento2/pull/20466

### Fixed Issues (if relevant)

1. magento/magento2#20299: Order item details label not aligned in mobile view
2. ...

### Manual testing scenarios (*)

1. Open frontend and login as customer
2. Go to my account section
3. Click on My order link and open detail any order in mobile
4. You will issue as shown in screenshot

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4283](https://jira.corp.magento.com/browse/ENGCOM-4283) has been created to process this Pull Request

**Comment by sdzhepa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [new Magento instance](https://pr-21243.instances.magento-community.engineering).
Admin access: [https://pr-21243.instances.magento-community.engineering/admin](https://pr-21243.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sdzhepa** [comment]
Hello @amol2jcommerce 

Thank you for contribution and collaboration!

During testing, I found the issue was not fixed.
Could you please take a look and fix?

1. Tested in Google Chrome. 
**Actual result on the branch with PR:**
pr21243_gh
   
2. Tested on physical iPhone5
**Actual result on the branch with PR:**
pr21243

**Comment by amol2jcommerce** [comment]
Hi @sdzhepa branch updated. please review.

**Comment by sdzhepa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [new Magento instance](https://pr-21243.instances.magento-community.engineering).
Admin access: [https://pr-21243.instances.magento-community.engineering/admin](https://pr-21243.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Pull request merged**
