### PR TITLE
Removed unused construct parameters

### LINKED ISSUE #29531: [Issue] Removed unused construct parameters
This issue is automatically created based on existing pull request: magento/magento2#28653: Removed unused construct parameters

---------

### Description (*)

This PR removes some unused parameters in construct of the class

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR removes some unused parameters in construct of the class

### Resolved issues:
1. [x] resolves magento/magento2#29531: Removed unused construct parameters

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Review by lbajsarowicz — CHANGES_REQUESTED** [review]
Please fix static checks by removing
```
Class AdvancedPricing
 *
 * 
```

Also please remove empty lines between const declarations (you can actually keep them in groups), and when it's possible, add the visibility to the `const` elements.

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
Hi @lbajsarowicz 
I have fixed failed static test also removed empty lines between const declarations
Thanks

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento create issue

**Comment by Usik2203** [comment]
Hi @lbajsarowicz 
Could I kindly ask you to review this one . 
Thanks!

**Review by lbajsarowicz — APPROVED** [review]
✔️  Greenlight from my side.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked that Advanced Pricing import works as before

**Comment by engcom-Delta** [comment]
**Note:** All automation tests are passed

**Pull request merged**
