### PR TITLE
[32017][To 2.4-develop] Marked Directory, Downloadable, Eav and Elasticsearch interfaces as API

### LINKED ISSUE #32017: Mark Directory, Downloadable, Eav and Elasticsearch interfaces as API
The following interfaces should be marked as API in 2.4-develop branch
1. app/code/Magento/Directory/Model/Country/Postcode/ConfigInterface.php
1. app/code/Magento/Directory/Model/Country/Postcode/ValidatorInterface.php
1. app/code/Magento/Downloadable/Api/DomainManagerInterface.php
1. app/code/Magento/Downloadable/Pricing/Price/LinkPriceInterface.php
1. app/code/Magento/Eav/Model/Entity/Attribute/AttributeInterface.php
1. app/code/Magento/Eav/Model/Entity/Attribute/Backend/BackendInterface.php
1. app/code/Magento/Eav/Model/Entity/Attribute/Source/SpecificSourceInterface.php
1. app/code/Magento/Eav/Model/Entity/Attribute/UniqueValidationInterface.php
1. app/code/Magento/Eav/Model/Entity/AttributeLoaderInterface.php
1. app/code/Magento/Eav/Model/Entity/Setup/PropertyMapperInterface.php
1. app/code/Magento/Eav/Model/ResourceModel/Attribute/DefaultEntityAttributes/ProviderInterface.php
1. app/code/Magento/Elasticsearch/Model/Adapter/FieldMapper/Product/FieldProvider/FieldIndex/ConverterInterface.php
1. app/code/Magento/Elasticsearch/Model/Adapter/FieldMapper/Product/FieldProvider/FieldIndex/ResolverInterface.php
1. app/code/Magento/Elasticsearch/Model/Adapter/FieldMapper/Product/FieldProvider/FieldName/ResolverInterface.php
1. app/code/Magento/Elasticsearch/Model/Adapter/FieldMapper/Product/FieldProvider/FieldType/ResolverInterface.php
1. app/code/Magento/Elasticsearch/Model/Adapter/FieldMapper/Product/FieldProviderInterface.php
1. app/code/Magento/Elasticsearch/Model/Adapter/FieldsMappingPreprocessorInterface.php
1. app/code/Magento/Elasticsearch/SearchAdapter/Query/ValueTransformerInterface.php
1. app/code/Magento/Elasticsearch/SearchAdapter/QueryAwareInterface.php

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixes #32017
### Related Pull Requests

https://github.com/magento/magento2/pull/32161

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32017>

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by danielrussob** [comment]
@magento run Integration Tests

**Comment by danielrussob** [comment]
I confirm that this PR is just a code cleanup / marked as API some class. We are waiting for tests.

**Comment by danielrussob** [comment]
I confirm that all files mentioned in issue (https://github.com/magento/magento2/issues/32017) are covered

**Comment by danielrussob** [comment]
Hi @Usik2203 , thank you for your review

Can you tell me why you have marked: app/code/Magento/Elasticsearch/Model/Adapter/FieldMapper/Product/AttributeAdapter.php as API?

It's not linked in: https://github.com/magento/magento2/issues/32017

**Comment by Usik2203** [comment]
> Hi @Usik2203 , thank you for your contribution
> 
> Can you tell me why you have marked: app/code/Magento/Elasticsearch/Model/Adapter/FieldMapper/Product/AttributeAdapter.php as API?
> 
> It's not linked in: #32017

Hi @danielrussob 
These class was marked based on this comment for preventing failed static test
https://github.com/magento/magento2/pull/32175#issuecomment-785755363
Thanks

**Review by danielrussob — APPROVED** [review]

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama the branch with code successfully imported into`magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-32726`.

**Pull request merged**
