### PR TITLE
Adding created_at, status and grand_total filters to customer Orders query and fixing multiple filters failure

### LINKED ISSUE #38392: Added created_at, status and grand_total filters to customer Orders query and fixed multiple filters failure
This issue is automatically created based on existing pull request: magento/magento2#36949: Adding created_at, status and grand_total filters to customer Orders query and fixing multiple filters failure

---------

### Description (*)

Added created_at, status, and grand_total filters to customer Orders query
Fixing multiple filters bug in this query, when adding one more filter in the array for filterGroupBuilder addFilters it doesn´t apply all filters

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Create an order with a customer
2. With the same customer, generate a customer token and call the customer Orders query
3. Create multiple orders to test filters
4. Use two or more filters to check if multiple are being applied

### Questions or comments

I did not find a unit test for this class, does it exist?

I used the same names from the output object to maintain the pattern

I accept any suggestions or critics, doing it you are helping me!

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by venchiarutti**
### Description (*)

Added created_at, status, and grand_total filters to customer Orders query
Fixing multiple filters bug in this query, when adding one more filter in the array for filterGroupBuilder addFilters it doesn´t apply all filters

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38392

### Manual testing scenarios (*)

1. Create an order with a customer
2. With the same customer, generate a customer token and call the customer Orders query
3. Create multiple orders to test filters
4. Use two or more filters to check if multiple are being applied

### Questions or comments

I did not find a unit test for this class, does it exist?

I used the same names from the output object to maintain the pattern

I accept any suggestions or critics, doing it you are helping me!

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by venchiarutti** [comment]
@magento run all tests

**Comment by venchiarutti** [comment]
@magento run all tests

**Comment by venchiarutti** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
Hello @venchiarutti 
Thank you for your collaboration
Could you please remove "and fixing multiple filters failure" from title and fixes.
Let's keep just `order_date`, `grand_total` and `status` fixes.
Thank you in advance.

**Review by andrewbess — CHANGES_REQUESTED** [review]
Hello @venchiarutti
Thank you for your collaboration
Waiting for tests and answers [on this question](https://github.com/magento/magento2/pull/38079#issuecomment-1905692920)

**Comment by andrewbess** [comment]
@magento run Static Tests

**Comment by engcom-Charlie** [comment]
@magento run Static Tests

**Comment by engcom-Charlie** [comment]
@magento create issue

**Review by andrewbess — APPROVED** [review]
Hello @venchiarutti 
Thank you for your contribution
Looks nice for me
Approved

**Comment by engcom-Charlie** [comment]
Hi @venchiarutti,

Thank you for your contribution!

In order to proceed further, can you please look into the Static test [failure](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36949/e6abb2104d0d904378639ea05534c3f3/Statics/console-error-logs.html).

Thank you!

**Comment by engcom-Charlie** [comment]
It seems that bot moved this PR to testing hence moving it back to Change Requested.

@venchiarutti, can you please have a look into [this](https://github.com/magento/magento2/pull/36949#issuecomment-1914452948) comment and do the needful.

Thank you!

**Comment by venchiarutti** [comment]
@magento run Static Tests

**Comment by venchiarutti** [comment]
I don't know what may be causing these errors in the tests, I would appreciate some help @engcom-Charlie

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Static Tests, Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Charlie** [comment]
The functional B2B and Functional EE test failures are different in recent 2 runs. It seems to be flaky. Hence moving this PR to testing.

**Functional B2B**
**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36949/d4a8ff37aa03dfb6987d30b2264a5268/Functional/allure-report-b2b/index.html#categories
image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36949/783d2df354d1f5891f44661b8136c7f9/Functional/allure-report-b2b/index.html#categories/3ae677d8e6673a8efa39994732ea996b/e4d89e84c1a662bd/
image

**Functional EE**
**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36949/c6e6aee0a48a64b0fe33c877033b1d27/Functional/allure-report-ee/index.html#categories
image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36949/0a5681974428b092ccbc5ded0d4501a1/Functional/allure-report-ee/index.html#categories

**Comment by engcom-Delta** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** 

**Manual testing scenario:**

1.Create an order with a customer
2.With the same customer, generate a customer token and call the customer Orders query
3.Create multiple orders to test filters
4.Use two or more filters to check if multiple are being applied


**Before:** :heavy_multiplication_x: 

Screenshot 2024-04-05 at 2 24 29 PM

Screenshot 2024-04-05 at 2 23 16 PM


**After:** :heavy_check_mark:  

Screenshot 2024-04-05 at 2 25 20 PM

Screenshot 2024-04-05 at 2 25 57 PM

Screenshot 2024-04-05 at 2 26 33 PM

Screenshot 2024-04-05 at 2 27 04 PM

Screenshot 2024-04-05 at 2 27 41 PM

Screenshot 2024-04-05 at 2 28 15 PM

Screenshot 2024-04-05 at 2 29 28 PM

Screenshot 2024-04-05 at 2 30 23 PM


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
The functional B2B failures except AdminAssignCompaniesTest and AdminCompanyRelationsInCompanyIndexGridTest are different in recent 2 builds. For these 2, there are open issues  [ACQE-6363](https://jira.corp.adobe.com/browse/ACQE-6363), [ACQE-6364](https://jira.corp.adobe.com/browse/ACQE-6364)

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36949/b0b53ee1a20af547cafe51557850f139/Functional/allure-report-b2b/index.html#categories
image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36949/c5bd3507dbdbfafb123d6980ad97e9fc/Functional/allure-report-b2b/index.html#categories/e847f4a0aaffc342329492c79cacfbad/f4a8a69b474f25f5/
image


2. Functional CE failures are different in recent 2 builds. Seems to be flaky.
**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36949/b8191553fb821607f8ccec58e3f9e147/Functional/allure-report-ce/index.html#categories
image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36949/3540509c851b511bcf235def01f86df1/Functional/allure-report-ce/index.html#categories
image

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
The functional EE failures are differnt in latest 2 builds except StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest. This bug its not occurring because of this PR and also there is an open [issue](https://jira.corp.adobe.com/browse/ACQE-6331) exists. Moving this PR to Merge in Progress now.


**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36949/8a5e351fb6e507c18fe127e5ae5ce933/Functional/allure-report-ee/index.html
image

**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36949/1297e6f1175a02d898c53c12b33c1e0d/Functional/allure-report-ee/index.html#categories
image

**Pull request merged**
