### PR TITLE
#2434 fix for quick add to cart

### PR DESCRIPTION
**Pull request by matiasnombarasco**
Updated template file to support quick add to cart from the category view without being redirected to the product page. This change also fixes the enterprise version. 

Bug related: https://github.com/magento/magento2/issues/2434

### CODE REVIEW

**Comment by Vinai** [comment]
Thank you for the PR! We are currently waiting for the travis builds to work again, which should happen in a few days. Once that is running and the tests are green we can continue to process your contribution.
In the mean time, can you please sign the contributor license agreement?

**Comment by matiasnombarasco** [comment]
Sure thing! I just did it. 

Cheers

Matias

**Comment by brankoajzele** [comment]
Hey Magento, any update on getting this into latest Magento 2.x? I have just manually patched it over Magento 2.0.2. Seems a bit irresponsible to have this open for so long, given the importance of it.

**Comment by Vinai** [comment]
@matiasnombarasco can you please sign the CLA agreement and check why the build is failing? Thank you!

**Comment by sivaschenko** [comment]
@matiasnombarasco @Vinai do you have any updates on this PR? This is a fix for critical UX issue.

**Comment by vrann** [comment]
@matiasnombarasco Since it is reported that #2434 is fixed in 2.1.5 is it fine to close the PR now?

**Comment by vrann** [comment]
@sivaschenko Hi, is  it still reproducible for you?

**Comment by vrann** [comment]
@matiasnombarasco unfortunately, we don't process PRs to 2.0 branch at the moment. Please re-create it against the develop branch.

**Pull request closed without merging**
