### PR TITLE
Issue-36051: Magento Admin Product Custom Options Not Movable / Dragg…

### LINKED ISSUE #36051: Magento Admin Product Custom Options Not Movable / Draggable in 2.4.4
### Preconditions and environment

-Magento 2.4.4
-jQuery 3.6.0

### Steps to reproduce

1. In a clean Magento 2.4.4 instance, create a product in the admin with 3 custom options.
2. Try to drag the second option up to the first position.

### Expected result

Custom option should drag and move to the first position while the first option should move down.

### Actual result

The dragging action stops and gets stuck, does not complete.

### Additional information

The issue comes from src/vendor/magento/module-ui/view/base/web/js/dynamic-rows/dnd.js:138 where the calculation is made:
```
drEl.minYpos =
                $table.offset().top - originRecord.offset().top + $table.children('thead').outerHeight();
```
jQuery updated the way it handles `outerHeight` function calls. Previously, in Magento 2.4.3-p1 which uses a jQuery version of 1.12.4, jQuery returned `Null` when `outerHeight` was called on a non-existent element. Then the `minYpos` value still returned a number value. This is why in the older Magento version, the drag and move action of custom options in Magento worked. This newer jQuery version used in the newer Magento version, however, returns `undefined`. Which is why the calculation referenced above returns `Nan` which breaks the drag and move action.

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rogerdz**
### Description (*)
Magento Admin Product Custom Options Not Movable / Draggable

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36051

### Manual testing scenarios (*)

1. In a clean Magento 2.4.4 instance, create a product in the admin with 3 custom options.
2. Try to drag the second option up to the first position.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento give me test instance

**Comment by Den4ik** [comment]
@magento give me test instance

**Review by Den4ik — APPROVED** [review]
✅ Approved

@rogerdz Thanks for contribution

**Comment by Den4ik** [comment]
Failed tests are not related to the changes

**Comment by jupiterhs** [comment]
@magento give me 2.4-develop instance

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run WebAPI Tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

1. Create a product in the admin with 3 custom options.
2. Try to drag the second option up to the first position(donot expand the custom options).

**Before:** :heavy_multiplication_x:  Options were not draggale from down to upside.
Screenshot 2023-03-07 at 2 22 20 PM


**After:** :heavy_check_mark:  Now draggable.
Screenshot 2023-03-07 at 2 23 04 PM

Builds are failed hence, moving this to **extended testing.**

**Comment by ihor-sviziev** [comment]
@engcom-Lima just wonder how did you perform testing, while there were conflicts... 🤔

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by engcom-Lima** [comment]
Hi @ihor-sviziev ,


> @engcom-Lima just wonder how did you perform testing, while there were conflicts... 🤔

I have tested it by doing  directly checkout in Rogerdz branch without merging in the mainline.

I have reverified this PR and it is working as expected as mentioned in the [comment](https://github.com/magento/magento2/pull/36072#issuecomment-1457936604).


Thanks

**Comment by engcom-Echo** [comment]
Functional Tests CE and Functional Tests B2B failure are different on last two run.
Function Test CE
1. Run1
ce-36072

2. Run2
ce-3

Functional Test B2B
1. Run1
b2b-36072

2. Run2
b2b-2

Hence Moving to `Merge In Progress`

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by SimonOnbelet** [comment]
There is a typo in the code on 139. 
drEl.minYpos = $table.offset().top - originRecord.offset().top + outerHight;

outerHight should be outerHeight. This error is shown when deEl.minYpos is console logged. I'm facing the same issue, but this solution doesn't fix the problem. It does solve the issue of the row snapping, but the rows are still not draggable.

**Comment by ihor-sviziev** [comment]
Looks like this pull request was merged without the latest merge commits, as a result, it wasn't marked as merged

**Pull request closed without merging**
