### PR TITLE
fix issue #24335

### PR DESCRIPTION
**Pull request by francescopis**
### Fixed Issues (if relevant)

1. magento/magento2#24335: Product collection filter not working with operator chars in eav attribute code

### Manual testing scenarios (*)

1. Create a product collection
2. $productCollection->addAttributeToFilter('ibm_plan-id', ['eq' => true]);
3. $productCollection->getItems();

No errors from mysql

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24344) <br/>All committers have signed the CLA.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5736](https://jira.corp.magento.com/browse/ENGCOM-5736) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@francescopis thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Delta** [comment]
Hi @francescopis I cannot reproduce issue by steps you described on 2.3-develop. Could you clarify how attribute 'ibm_plan-id' was created?
By default we can created attribute with **Attribute Code** that use only letters (a-z or A-Z), numbers (0-9) or underscore (_) and function addAttributeToFilter() use attribute code when it runs.

**Comment by francescopis** [comment]
@engcom-Delta the attribute was created with a datapatch which does a Magento\Eav\Setup\EavSetup-> addAttribute (...)"

**Comment by ihor-sviziev** [comment]
Hi @engcom-Delta,
Could you review following comment https://github.com/magento/magento2/pull/24344#issuecomment-527420191? 

Were you able to reproduce this issue now?

**Comment by engcom-Delta** [comment]
Hi @francescopis with PR changes I still have errors from mysql:
```
```SQLSTATE[42S22]: Column not found: 1054 Unknown column 'at_ibm_plan' in 'field list', query was: SELECT `e`.*, IF(at_ibm_plan-id.value_id > 0, at_ibm_plan-id.value, at_ibm_plan-id_default.value) AS `ibm_plan-id` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_product_entity_varchar` AS `at_ibm_plan-id_default` ON (`at_ibm_plan-id_default`.`entity_id` = `e`.`entity_id`) AND (`at_ibm_plan-id_default`.`attribute_id` = '135') AND `at_ibm_plan-id_default`.`store_id` = 0
 LEFT JOIN `catalog_product_entity_varchar` AS `at_ibm_plan-id` ON (`at_ibm_plan-id`.`entity_id` = `e`.`entity_id`) AND (`at_ibm_plan-id`.`attribute_id` = '135') AND (`at_ibm_plan-id`.`store_id` = 1) WHERE (IF(at_ibm_plan-id.value_id > 0, at_ibm_plan-id.value, at_ibm_plan-id_default.value) = '1')```
```

And I am not sure if such fix should be applied as there is [article](https://docs.magento.com/m2/ce/user_guide/stores/attributes-product.html) with Attribute Code description:

> The Attribute Code must begin with a letter, but can include a combination of lowercase letters (a-z) and numbers (0-9). The code must be less than thirty characters in length and cannot include any special characters or spaces, although an underscore (_) can be used to indicate a space.

@sidolov @ihor-sviziev

**Comment by ihor-sviziev** [comment]
> Hi @francescopis with PR changes I still have errors from mysql:
> `` SQLSTATE[42S22]: Column not found: 1054 Unknown column 'at_ibm_plan' in 'field list', query was: SELECT `e`.*, IF(at_ibm_plan-id.value_id > 0, at_ibm_plan-id.value, at_ibm_plan-id_default.value) AS `ibm_plan-id` FROM `catalog_product_entity` AS `e` INNER JOIN `catalog_product_entity_varchar` AS `at_ibm_plan-id_default` ON (`at_ibm_plan-id_default`.`entity_id` = `e`.`entity_id`) AND (`at_ibm_plan-id_default`.`attribute_id` = '135') AND `at_ibm_plan-id_default`.`store_id` = 0 LEFT JOIN `catalog_product_entity_varchar` AS `at_ibm_plan-id` ON (`at_ibm_plan-id`.`entity_id` = `e`.`entity_id`) AND (`at_ibm_plan-id`.`attribute_id` = '135') AND (`at_ibm_plan-id`.`store_id` = 1) WHERE (IF(at_ibm_plan-id.value_id > 0, at_ibm_plan-id.value, at_ibm_plan-id_default.value) = '1') ``
> 
> And I am not sure if such fix should be applied as there is [article](https://docs.magento.com/m2/ce/user_guide/stores/attributes-product.html) with Attribute Code description:
> 
> > The Attribute Code must begin with a letter, but can include a combination of lowercase letters (a-z) and numbers (0-9). The code must be less than thirty characters in length and cannot include any special characters or spaces, although an underscore (_) can be used to indicate a space.
> 
> @sidolov @ihor-sviziev

Hi @engcom-Delta,

I see that's table column escaping issue, I think we have to fix it. If this attribute codes not supported  - we could add validations somewhere, but it should not cause any SQL errors. Also I think this case should be covered with some tests in order to prevent similar issues in future.

@francescopis  Could you review comment from @engcom-Delta and adjust your PR?

Thank you!

**Comment by aredridel** [comment]
@ihor-sviziev Pardon? I'm not aware of being involved in this issue.

**Comment by ihor-sviziev** [comment]
> @ihor-sviziev Pardon? I'm not aware of being involved in this issue.

@aredridel 
Ah, sorry, autocomplete worked incorrect somehow, just updated my previous comment

**Comment by lenaorobei** [comment]
Hey @francescopis! Are you still up to finishing this PR? Please address comments from reviewers.

**Comment by francescopis** [comment]
i think the question now is what solution is best
as said by @ihor-sviziev if attributes with underscorre, or other special chars, are not allowed by docs we should introduce a validation
otherwise i can write down some tests and push it again

**Comment by lenaorobei** [comment]
@francescopis yes, please consider Ihor's suggestion.

**Comment by lenaorobei** [comment]
Closing this PR due to inactivity. Please feel free to reopen if you are going to continue working on it.
Thank you.

**Pull request closed without merging**
