### PR TITLE
Issue #18683 Fixed: quote_item_option.value column and sales_order_item.product_options column was not updating.

### PR DESCRIPTION
**Pull request by mahesh-rajawat**
**info_buyRequest** qty always set to 1 for products if add product from category view page and then
 try to change product quantity from minicart and cart page. In this PR i have fixed it.

### Description (*)

If we add product to cart from category view page and then if we change the quantity of cart item
from minicart or cart page, **quote_item_option.value** column and **sales_order_item.product_options** column was not updating. So if we get the order items quantity
 by **info_buyrequest** code it was incorrect. I have fixed it.

### Fixed Issues (if relevant)

1. #18683: Serialization of Quote To Order Serializes Simple Product Qty of Ordered Items as 1 Instead of Qty Ordered.

### Manual testing scenarios (*)

1. Created a new product.
2. Add this product into the cart from category page.
3. Try to change quantity from Minicart now its updating quote_item_option.value column value.
4. Try to change quantity from Cart page  now its updating **quote_item_option.value** column value.
5. Placed an order and checked in **sales_order_item** table now product_options column value also updated.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18740) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by mahesh-rajawat** [comment]
#SQUASHTOBERFEST

**Comment by sidolov** [comment]
Hi @maheshWebkul721  , looks like you made some commits with email different than in your GitHub profile, please, add email from commits to your profile!
Thank you!

**Comment by mahesh-rajawat** [comment]
@sidolov i have added the email address, update me if everything is correct now.

**Comment by sivaschenko** [comment]
Hi @maheshWebkul721 the first commit in this PR are still not associated with your account. Please see the commits tab:
image
I recommed you to reset your branch to the last commit before your changes, do a single commit with your correct github account and force push to the branch.

**Comment by mahesh-rajawat** [comment]
Commits restored.

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3434](https://jira.corp.magento.com/browse/ENGCOM-3434) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Pull request is causing MSI functional tests failures

**Comment by p-bystritsky** [comment]
Hello, @maheshWebkul721. Unfortunately, we cannot accept your PR, because it may break multiple Magento 2 extensions, as at some point it sets incorrect product quantity to quote item. See the video below.

Please update your PR.

**Comment by sidolov** [comment]
@maheshWebkul721 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
