### PR TITLE
Fixed Issue #23288 Message isn't displayed on the error after connection reset and placing order

### PR DESCRIPTION
**Pull request by gaurav-473**
Fixed Issue #23288 
Message isn't displayed on the error after connection reset and placing order

### Preconditions (*)

1. Magento 2.3.1
2. PHP 7.2.18

### Steps to reproduce (*)

1. Open the checkout page and fill in the data
2. Turn off the Internet / Make site inaccessible.
3. Click Place Order.

### Expected result (*)

User gets the error 'Something went wrong with your request. Please try again later.'

### Actual result (*)

User gets an error without text.
bug4

### CODE REVIEW

**Comment by gaurav-473** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @gauravagarwal1001. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @gauravagarwal1001, here is your [new Magento instance](https://pr-23364.instances.magento-community.engineering).
Admin access: [https://pr-23364.instances.magento-community.engineering/admin](https://pr-23364.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by gaurav-473** [comment]
> Hi @gauravagarwal1001, here is your [new Magento instance](https://pr-23364.instances.magento-community.engineering).
> Admin access: https://pr-23364.instances.magento-community.engineering/admin
> Login: `admin` Password: `123123q`

Issues fixed and tested on deploy test instance based on PR changes

**Review by orlangur — CHANGES_REQUESTED** [review]
Hi @gauravagarwal1001! Please take a look on failed builds.

**Comment by gaurav-473** [comment]
> Hi @gauravagarwal1001! Please take a look on failed builds.

@orlangur Please help I think these changes are not the reason of test failed. Please check and help why multiple tests are failed.

**Comment by orlangur** [comment]
@magento run all builds

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-5406](https://jira.corp.magento.com/browse/ENGCOM-5406) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Review by sivaschenko — CHANGES_REQUESTED** [review]
@gauravagarwal1001 I don't see changes in this PR. Were the exact same changes delivered to mainline already?

**Comment by gaurav-473** [comment]
> @gauravagarwal1001 I don't see changes in this PR. Were the exact same changes delivered to mainline already?

Sorry for delay in reply..
Yes same changes delivered to mainline .

**Comment by sivaschenko** [comment]
@gauravagarwal1001 Were changes delivered by another PR? Can we close this one?

**Pull request closed without merging**
