### PR TITLE
Add missing fluent interface for class ItemCreation

### PR DESCRIPTION
**Pull request by dyron**
### Description (*)
The current implementation of ItemCreation is missing the fluent interface.

### Manual testing scenarios (*)

1. Try to create invoice items with $this->invoiceItemCreationFactory->create()
2. Apply data with $this->invoiceItemCreationFactory->create()->setOrderItemId($orderItemId)->setQty($qty);

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @dyron. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21410) <br/>All committers have signed the CLA.

**Comment by orlangur** [comment]
Hi @dyron, need some time to check on this one in Slack as recently I met a recommendation to avoid fluent interface.

**Comment by orlangur** [comment]
@dyron see https://ocramius.github.io/blog/fluent-interfaces-are-evil/.

**Pull request closed without merging**
