### PR TITLE
26719: Applied fixes for incorrect customer group on order

### PR DESCRIPTION
**Pull request by swapnilT2jcommerce**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<26719>

### Manual testing scenarios (*)

1. Create 2 new customer groups i.e **VIP** and **Trade Customer**
2. Create new customer, assign it to Customer **VIP**
3. Create an order
4. Edit created customer and change it's customer group to **Trade Customer**
5. Create another order using "Reorder" feature in admin panel.
6. Newly created order have a new customer group assigned which is **Trade Customer**

Expected result (*)
   Newly created order should have a new customer group assigned

Please see the screenshot : -

before-applied-fixes

after-applied-fixes

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by swapnilT2jcommerce** [comment]
@magento run all tests

**Comment by swapnilT2jcommerce** [comment]
@magento give me test instance
--

**Comment by magento-engcom-team** [comment]
Hi @swapnilT2jcommerce. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @swapnilT2jcommerce, here is your [new Magento instance](https://pr-28667.instances.magento-community.engineering).
Admin access: [https://pr-28667.instances.magento-community.engineering/admin_e93e](https://pr-28667.instances.magento-community.engineering/admin_e93e)
Login: `2d00ad1d` Password: `b86f7743c0f0`
Instance will be terminated in up to 3 hours.

**Comment by swapnilT2jcommerce** [comment]
I have checked in test instance and it's working as excepted after applying fixes.

Test cases are failed due to existing issue not related with our fixes.

failed-test-case-abode-cli-1
failed-test-cases-adobe-cli-2

**Comment by swnsma** [comment]
@magento run all tests

**Review by swnsma — CHANGES_REQUESTED** [review]
Hi @swapnilT2jcommerce!
Thank you for your contribution!

Could you check failed static tests?
Also, as a part of the Definition of Done, I need to ask you to cover your changes with the Auto Test.
Will be you able to do so?

**Comment by engcom-Kilo** [comment]
@swapnilT2jcommerce 
Please grant access to branch for adding fix for Static test. Thanks.

**Comment by engcom-Charlie** [comment]
Hi @swapnilT2jcommerce, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
