### PR TITLE
Updated nginx.conf.sample for .well-known

### PR DESCRIPTION
**Pull request by LiamKarlMitchell**
A useful directory for enabling SSL via lets encrypt / cert bot or manually adding SSL certificates.
This was not served when using the sample as a config in Nginx.

Resolves certbot verification
Detail: Invalid response from
.. /.well-known/acme-challenge/RwtcM-....

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @LiamKarlMitchell. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21830) <br/>All committers have signed the CLA.

**Review by josefbehr — APPROVED** [review]

**Comment by josefbehr** [comment]
I think the failing tests are unrelated and can be ignored.

**Comment by magento-engcom-team** [comment]
Hi @josefbehr, thank you for the review.
[ENGCOM-4567](https://jira.corp.magento.com/browse/ENGCOM-4567) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@LiamKarlMitchell thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VasylShvorak** [comment]
Hi @LiamKarlMitchell could you resolve conflicting files?

**Comment by sidolov** [comment]
@LiamKarlMitchell , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
