### PR TITLE
Updated EAV Attribute code max lenght

### PR DESCRIPTION
**Pull request by okorshenko**
### Description
 - EAV attribute code will be transformed into column name for flat tables. MySQL does not support column name with more than 64 symbols

### Manual testing scenarios

1. Install magento 
2. enable flat mode for catalog
3. make sure that catalog works on the frontend

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by orlangur** [comment]
@okorshenko why do we need this change at all and not simply change back to old `30` value?

**Comment by okorshenko** [comment]
Hi @orlangur The value 30 was set based on some plans about Oracle support (which allows only 32 symbols). So Magento officially does not support Oracle DB. In MySQL limitation is 64.

**Comment by orlangur** [comment]
Ok, I thought it was business requirement (like from times when attribute_code was displayed in UI) and if something went wrong it's easier to revert if there is no clear motivation for length increase.

**Comment by Nolwennig** [comment]
When this update will integrate the Magento core?

**Comment by okovalov-commer** [comment]
When will this be released?

**Comment by okovalov-commer** [comment]
Hi guys, any updates here ? when it gets promoted live? thank you

**Comment by okorshenko** [comment]
This PR will be available with 2.3 release

**Pull request merged**
