### PR TITLE
magento/magento2#69:Read API :: Web-Api tests :: Magento\GraphQl\Cata…

### PR DESCRIPTION
**Pull request by aleksejsbaranovs10**
### Description (*)
resolve magento/catalog-storefront#69

### Related Pull Requests
N/A

### Manual testing scenarios (*)
N/A

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @aleksejsbaranovs10
Unfortunately, we only accept Pull Requests to the following branches: 2.2-develop, 2.3-develop, 2.4-develop, 1.2-develop.
Please create a new Pull Request and use one of those as a target.

Thank you.

**Comment by mslabko** [comment]
@aleksejsbaranovs10  
The root cause of this issue is changed order in \Magento\CatalogStorefrontGraphQl\Model\SearchCriteriaBuilder::collectSort (see commit:
https://github.com/magento/catalog-storefront/commit/d3780ac60105ae494589786fcd4cfe01b230527b#diff-c2d5b735e8b831aac041ac85f3f706feR231 )

@kokoc do we have a reason for change default order from ASC to DESC?

**Comment by mslabko** [comment]
@magento run WebAPI-Tests tests

**Comment by mslabko** [comment]
@magento run WebAPI Tests

**Comment by mslabko** [comment]
https://github.com/magento/catalog-storefront/issues/69#issuecomment-646301036

**Pull request closed without merging**
