### PR TITLE
Fixed error message related to message queue topic not including the topic name

### LINKED ISSUE #34246: [Issue] Fixed error message related to message queue topic not including the topic name
This issue is automatically created based on existing pull request: magento/magento2#34232: Fixed error message related to message queue topic not including the topic name

---------

### Description (*)

Now, if someone comes across this error, it's significantly quicker to determine the issue by knowing the particular topic that's causing the error.

I.e. https://magento.stackexchange.com/questions/284604/error-while-checking-if-topic-is-synchronous-on-setupupgrade

### Contribution checklist (*)
 - [x ] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by erfanimani**
### Description (*)

Now, if someone comes across this error, it's significantly quicker to determine the issue by knowing the particular topic that's causing the error.

I.e. https://magento.stackexchange.com/questions/284604/error-while-checking-if-topic-is-synchronous-on-setupupgrade

### Contribution checklist (*)
 - [x ] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#34246: Fixed error message related to message queue topic not including the topic name

### CODE REVIEW

**Comment by erfanimani** [comment]
@magento run all tests

**Review by edenduong — CHANGES_REQUESTED** [review]
HI,

Thank you for your contribution. Could you please cover your changes by the unit test? Thanks!

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by erfanimani** [comment]
Hi @edenduong , I've amended. my commit and included a unit test for that scenario.

Thanks

**Comment by erfanimani** [comment]
@magento run Unit Tests

**Review by edenduong — APPROVED** [review]

**Comment by erfanimani** [comment]
Any update on this one?

**Comment by glo05363** [comment]
we were not able to reproduce the issue with version upgrades as the issue was under 2.2.8 to 2.3.6 
https://magento.stackexchange.com/questions/284604/error-while-checking-if-topic-is-synchronous-on-setupupgrade

with latest versions issue is not present on upgrades.

However we have found out the PR changes are related to get the "Clear error message" : to make sure we get the topic name which is not available.

Before PR:
image

After PR: The given topic name is "an example"
image

We have tested the unit case as well.
image


The issue can be seen if the topic is not found and we will see the error on setup:upgrade

**Comment by engcom-Charlie** [comment]
As per above [comment](https://github.com/magento/magento2/pull/34232#issuecomment-1429852904), moving it to Merge in Progress now.

Thank you!

**Pull request merged**
