### PR TITLE
Don't hide exception stack trace on setup:upgrade and app:config:import

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
During working on creating a new website, dumping its config to the config.php file, and then re-deploying to the test environment - I got few issues, **that was really hard to debug** as no exception trace is shown:
1. The `php bin/magento setup:upgrade -vvv` command was failing with `Import failed: URL key for specified store already exists.`, but exception stack trace isn't shown, even I passed `-vvv` param. ❌
image

2. The `php bin/magento app:config:import -vvv` command failed in the same way, w/o exception stack trace❌
image

After my changes - the exception will be process in 
https://github.com/magento/magento2/blob/a31f4a35c018ad09654e5bd5871086b73fbd3d2d/bin/magento#L24-L32

As a result I got the exception trace, so I finally can understand where the issue happened and investigate why it's happening ✔
image

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)
1. 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests, Functional Tests B2B, Functional Tests EE

**Review by bgorski — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@bgorski, the tests are failing, it’s not ready for testing yet

**Comment by bgorski** [comment]
Right. Somehow I was sure I saw them passing, must have been some different PR. Going back one step with this. Thanks for noticing!

**Comment by ihor-sviziev** [comment]
Closing for now...

**Pull request closed without merging**
