### PR TITLE
[Backport] Assign with and, or, replaced by &&, ||

### PR DESCRIPTION
**Pull request by Dharmeshvaja91**
### Original Pull Request 
 https://github.com/magento/magento2/pull/20628
### Description (*)
It is recommended to use the &&, || operators, instead of and, or to prevent confusion.

I kept the integrity of the source code on the occurrences with xor that returns boolean , if we use ^ instead of xor it'll return integer.

### Fixed Issues (if relevant)
N/A

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Dharmeshvaja91. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-4278](https://jira.corp.magento.com/browse/ENGCOM-4278) has been created to process this Pull Request

**Comment by lfluvisotto** [comment]
@osrecio , @ihor-sviziev 

It was to be me who should have created this backport because I am the original author of PR.

**Comment by ihor-sviziev** [comment]
Hi @lfluvisotto,
You'll have 5 contribution points as you're author of original PR.
More info: https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#points

**Pull request merged**
