### PR TITLE
6712 Remove additional margin for footer links widget; prevents layou…

### PR DESCRIPTION
**Pull request by fragdochkarl**
### Description
Add a CSS selector to remove an additional top-margin, rendered when adding a link widget to the footer in luma theme.

### Fixed Issues (if relevant)

1. magento/magento2#6712: Footer Links Widget CSS Issue

### Manual testing scenarios
1. Follow instructions of Issue

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=11063) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=11063) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: paliarush<br/>:x: viktym<br/>:x: sandrowagner

**Comment by okorshenko** [comment]
Hi @fragdochkarl  could you please sign CLA?

**Comment by fragdochkarl** [comment]
I did sign the CLA. When I click on it again it says "Thank you for signing the CLA" and redirects back to github... :smile_cat:

**Comment by vrann** [comment]
@fragdochkarl thanks, seems like our tools are crazy because the branch base history diverges. Should be fixed soon.

**Pull request merged**
