### PR TITLE
Fixed Typo Issue

### PR DESCRIPTION
**Pull request by jitendra-cedcoss**
Fixed Typo Issue

### Description (*)
Fixed Typo Issue

### Fixed Issues 
Fixed Typo Issue

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5057](https://jira.corp.magento.com/browse/ENGCOM-5057) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento-engcom-team combine 22719 22721

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
We got some errors while combining pull requests:
 - https://github.com/magento/magento2/pull/22721 : Contributor must be the same for target and source pull request

**Comment by ihor-sviziev** [comment]
@magento-engcom-team combine 22719 22727

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
@jitendra-cedcoss all pull requests have been successfully combined together: 
 - merged https://github.com/magento/magento2/pull/22719: Fixed Typo Issue
 - merged https://github.com/magento/magento2/pull/22727: Fixed Typo Issue

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5057](https://jira.corp.magento.com/browse/ENGCOM-5057) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento-engcom-team combine 22668 22669 22670 22674 22693 22708

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
@jitendra-cedcoss all pull requests have been successfully combined together: 
 - merged https://github.com/magento/magento2/pull/22668: Fixed Typo Issue
 - merged https://github.com/magento/magento2/pull/22669:  Fixed Typo Issue 
 - merged https://github.com/magento/magento2/pull/22670: Fixed Typo Issue
 - merged https://github.com/magento/magento2/pull/22674: Fixed Typo Issue
 - merged https://github.com/magento/magento2/pull/22693: Fixed Typo Issue
 - merged https://github.com/magento/magento2/pull/22708: Fixed Typo Issue

**Comment by ihor-sviziev** [comment]
@magento-engcom-team combine 22713

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
@jitendra-cedcoss all pull requests have been successfully combined together: 
 - merged https://github.com/magento/magento2/pull/22713: Fixed Typo Issue

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5057](https://jira.corp.magento.com/browse/ENGCOM-5057) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
**Notice:** QA not applicable

**Pull request merged**
