### PR TITLE
[Integration] Refactoring some customer fixtures 

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR refactores some customer fixtures for Integration Tests

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run Static Tests

**Comment by Usik2203** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7617](https://jira.corp.magento.com/browse/ENGCOM-7617) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Pull request merged**
