### PR TITLE
[CurrencySymbol] Fixing the redirect after saving the currency symbols

### PR DESCRIPTION
**Pull request by eduard13**
### Description (*)
This PR fixes the redirect path after saving the currency rates.

### Fixed Issues (if relevant)

1. Navigate to `Stores / Currency Symbols`
2. Save symbols
3. You're redirected to Dashboard with the Success message ❌ 

### Manual testing scenarios (*)

1. Navigate to `Stores / Currency Symbols`
2. Save symbols
3. You should stay on the same submitted page ✅ 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-26311.instances.magento-community.engineering).
Admin access: [https://pr-26311.instances.magento-community.engineering/admin](https://pr-26311.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rogyar** [comment]
Hi @eduard13. Thank you for the fix. Good catch!

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-6563](https://jira.corp.magento.com/browse/ENGCOM-6563) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by engcom-Echo** [comment]
@magento run all tests

**Pull request merged**
