### PR TITLE
Fixing issue related to select all option in admin grid in review sec…

### LINKED ISSUE #12594: Couldn't select all items on Review grid
I couldn't select all items on review grid.
### Preconditions

1. Magento 2.2.1
2. PHP 7.1.12

### Steps to reproduce

1. login Magento admin
2. from main menu, select `MARKETING -> User Content -> Reviews`
3. select `Select All` under `Actions` checkbox

### Expected result

1. it should show <code>346 records found (<b>346</b> selected)</code>

### Actual result

1. it should show <code>346 records found (<b>20</b> selected)</code>

### PR DESCRIPTION
**Pull request by webkul-ratnesh**
### Description (*)

Fixing issue related to select all option in admin grid in review section even by this fix all the grid's select all issue will be fixed #12594
### Fixed Issues (if relevant)

1. magento/magento2#12594: Couldn't select all items on Review grid

### Manual testing scenarios (*)

1. Goto Marketing -> User Content -> All Reviews
2. Try selecting all items in grid for mass updating status.
3. It should select all items exist in grid not only visible items

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by webkul-ratnesh** [comment]
@paliarush Hello,
Can you please explain what exactly issue this PR has, as there is nothing details mentioned in allure.

**Review by lenaorobei — CHANGES_REQUESTED** [review]
In order to properly fix this issue please consider rewriting this grid with UI components.
See issue thread for more details.

**Comment by engcom-Charlie** [comment]
Hi @webkul-ratnesh could you please take a look at the https://github.com/magento/magento2/pull/25234#pullrequestreview-468658810?
Thank you.

**Comment by sidolov** [comment]
@webkul-ratnesh  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
