### PR TITLE
Chore: Store - Replace Block Escaping with Escaper

### LINKED ISSUE #37138: [Issue] Chore: Store - Replace Block Escaping with Escaper
This issue is automatically created based on existing pull request: magento/magento2#37051: Chore: Store - Replace Block Escaping with Escaper

---------
### Description (*)
Refactors the `Magento_Store` module to replace `$block` escaping functions with `$escaper` escaping functions.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by pykettk**
### Description (*)
Refactors the `Magento_Store` module to replace `$block` escaping functions with `$escaper` escaping functions.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37138: Chore: Store - Replace Block Escaping with Escaper

### CODE REVIEW

**Comment by pykettk** [comment]
@magento create issue

**Review by andrewbess — APPROVED** [review]
Hello @pykettk 
Thank you for your contribution here.

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

- In `Magento_Store` module  verify `$block` escaping functions replaces with `$escaper` escaping functions.

**Before:** :heavy_multiplication_x: 

Screenshot 2023-03-13 at 4 36 42 PM


**After:** :heavy_check_mark:  
Screenshot 2023-03-13 at 4 36 03 PM

**Additionally verified:**

1. Created multiple store view.
2. Ordered from multiple store view.
3. Invoiced, shipped and generate credit memo from admin.

No additional manual test cases is required as part of regression cycle as this PR is related to the refactoring of the Store module.

As multiple builds are failed. Hence, moving this PR to "Extended Testing".

**Comment by engcom-Echo** [comment]
@magento run all tests

**Pull request closed without merging**
