### PR TITLE
Static font name for loading fonts

### LINKED ISSUE #29515: [Issue] Static font name for loading fonts
This issue is automatically created based on existing pull request: magento/magento2#29210: Static font name for loading fonts

---------

### Description (*)

The variable `@font-family-name__base` shouldn't be used when loading the Open Sans font because it's not really something that should change, since the source will still point to the Open Sans font. Using the variable here (can) cause issues when you change the base font (e.g. in a child theme).

#### Example 1:
If your custom theme extends from the Blank Theme and you change the base font with:
```
@font-family-name__base: 'Trenda';
```
This will be the compiled CSS:

Screenshot 2020-07-20 at 10 24 57

Which is already wrong, but doesn't directly lead to problems since 'Trenda' is a custom font and you'll probably do something like this in your theme:
```
.lib-font-face(
    @family-name: 'Trenda',
    @font-path: '@{baseDir}fonts/trenda/Trenda-Regular',
    @font-weight: @font-weight__regular,
    @font-style: normal,
    @font-display: swap
);
```
In which case this @font-face block will be included in the compiled CSS later, and your browser will only 'use' this one. However, if you only load the font in regular font-weight here, and you want to show text in **bold**, the browser will show that text in Open Sans (bold). 

#### Example 2:
If your custom theme extends from the Blank Theme and you want to switch to a 'websafe' font, for example Times New Roman:
```
@font-family-name__base: 'Times New Roman';
```
Text won't be displayed in the real Times New Roman but in Open Sans because that is loaded under the name 'Times New Roman'.

### Manual testing scenarios (*)

1. Change `@font-family-name__base` to `'Times New Roman'` (either temporary in Blank Theme or in a theme that extends from Blank)
2. Text should be shown in 'Times New Roman' (serif), not in Open Sans (sans-serif).
3. Check the compiled CSS and see if the open sans is properly loaded (name and src of @font-face block should still be of Open Sans)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by woutk88**
### Description (*)

The variable `@font-family-name__base` shouldn't be used when loading the Open Sans font because it's not really something that should change, since the source will still point to the Open Sans font. Using the variable here (can) cause issues when you change the base font (e.g. in a child theme).

#### Example 1:
If your custom theme extends from the Blank Theme and you change the base font with:
```
@font-family-name__base: 'Trenda';
```
This will be the compiled CSS:

Screenshot 2020-07-20 at 10 24 57

Which is already wrong, but doesn't directly lead to problems since 'Trenda' is a custom font and you'll probably do something like this in your theme:
```
.lib-font-face(
    @family-name: 'Trenda',
    @font-path: '@{baseDir}fonts/trenda/Trenda-Regular',
    @font-weight: @font-weight__regular,
    @font-style: normal,
    @font-display: swap
);
```
In which case this @font-face block will be included in the compiled CSS later, and your browser will only 'use' this one. However, if you only load the font in regular font-weight here, and you want to show text in **bold**, the browser will show that text in Open Sans (bold). 

#### Example 2:
If your custom theme extends from the Blank Theme and you want to switch to a 'websafe' font, for example Times New Roman:
```
@font-family-name__base: 'Times New Roman';
```
Text won't be displayed in the real Times New Roman but in Open Sans because that is loaded under the name 'Times New Roman'.

### Manual testing scenarios (*)

1. Change `@font-family-name__base` to `'Times New Roman'` (either temporary in Blank Theme or in a theme that extends from Blank)
2. Text should be shown in 'Times New Roman' (serif), not in Open Sans (sans-serif).
3. Check the compiled CSS and see if the open sans is properly loaded (name and src of @font-face block should still be of Open Sans)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29515: Static font name for loading fonts

### CODE REVIEW

**Comment by mrtuvn** [comment]
this is not actually a bug in my opinion
If you change font family name you also need to change font path

In css/source/_variables.less change font here is correct but not enough
You need to define font path too

In css/source/_typography.less
you also need redefine font path for new @font-family-name__base redefined in _variables.less

**Comment by mrtuvn** [comment]
https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/css-topics/using-fonts.html

**Comment by woutk88** [comment]
Ok, sure it makes sense to override `web/css/source/_typography.less` if you would want to switch to a different custom font and not use Open Sans at all.

But what if you want to switch to a websafe font which doesn't require any loading of fonts with @font-face? I would simply want to do `@font-family-name__base: 'Helvetica';`, but that is currently not enough because @font-family-name__base is used for loading Open Sans, which I think is not really in line with the documentation.

Or if you change the base font but still wants to use Open Sans for headings. You should be able to do this by only setting `@heading__font-family__base: 'Open Sans';`, but that won't work if the value of `@font-family-name__base` has changed.

Therefore I think, regardless of the way or the place you load and set/change your fonts, `@font-family-name__base` shouldn't be used for loading the Open Sans font.

**Comment by mrtuvn** [comment]
why not define fonts like this
In file css/source/_variables.less

//  Fonts
@font-family-name__base: 'Trenda';
@font-family-name__second: 'Helvetica';
@font-family-name__third: 'Open Sans';

In css/source/_typography.less
Import all your fonts here

So if you need use heading font somewhere
Just call font-family: @font-family-name__third

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7901](https://jira.corp.magento.com/browse/ENGCOM-7901) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@mrtuvn I think it's an issue, as the font path is already defined as open sans, and not getting from some variable

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
We found some time ago following code in styles-m.css file on the frontend:
```css
@font-face {
    font-family: 'MyCustomFont';
    src: url('../fonts/opensans/light/opensans-300.woff2') format('woff2'), url('../fonts/opensans/light/opensans-300.woff') format('woff');
    font-weight: 300;
    font-style: normal;
    font-display: swap
}

@font-face {
    font-family: 'MyCustomFont';
    src: url('../fonts/opensans/regular/opensans-400.woff2') format('woff2'), url('../fonts/opensans/regular/opensans-400.woff') format('woff');
    font-weight: 400;
    font-style: normal;
    font-display: swap
}

@font-face {
    font-family: 'MyCustomFont';
    src: url('../fonts/opensans/semibold/opensans-600.woff2') format('woff2'), url('../fonts/opensans/semibold/opensans-600.woff') format('woff');
    font-weight: 600;
    font-style: normal;
    font-display: swap
}

@font-face {
    font-family: 'MyCustomFont';
    src: url('../fonts/opensans/bold/opensans-700.woff2') format('woff2'), url('../fonts/opensans/bold/opensans-700.woff') format('woff');
    font-weight: 700;
    font-style: normal;
    font-display: swap
}
```

As result when you're trying to use some custom font by changing variable `@font-family-name__base: 'MyCustomFont';` - you're getting this issue.

I thing we need to change severity to S2

**Comment by ihor-sviziev** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Precondition:**

A custom theme that extends from Blank

**Manual testing scenario:**

1. Change `@font-family-name__base` to `'Times New Roman'`
2. The text should be shown in 'Times New Roman' (serif), not in Open Sans (sans-serif).
3. Check the compiled CSS and see if the open sans is properly loaded (name and src of @font-face block should still be of Open Sans)

**Before:** :heavy_multiplication_x:  The text is shown in `Open Sans` font



compiled CSS. :heavy_multiplication_x: Name changed to `'Times New Roman'`

Screenshot from 2020-08-18 16-12-23


**Before:** :heavy_multiplication_x:  The text is shown in `Times New Roman` font



compiled CSS. :heavy_check_mark: Name and src of the @ font-face block remain Open Sans

Screenshot from 2020-08-18 16-30-05

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@woutk88 
Please update your branch with mainline. Seems code it outdated.
Or also can grant permission to branch.
Thanks

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Pull request merged**
