### PR TITLE
Reports module has no place modifying CMS homepage

### LINKED ISSUE #37782: [Issue] Reports module has no place modifying CMS homepage
This issue is automatically created based on existing pull request: magento/magento2#37777: Reports module has no place modifying CMS homepage

---------
### Description

Today I learned (through conversation with a colleague) that the Magento_Reports module has a set-up script which modifies the CMS homepage of Magento. This feels like over-reach. The specific change uses a deprecated feature where each CMS block/page can have layout XML specified in the database. It adds some comments which look like they should be layout instructions, but without any context nor direction for developers.

This pull request removes the modification from future websites. This will have no impact to existing websites as the data patch will have already been applied. I have specifically separated the intended change from the commit where coding standards are applied.

### Manual testing scenarios
1. Install Magento
1. Review layout configuration of `home` CMS page in the database.

### Contribution checklist

 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fredden**
### Description

Today I learned (through conversation with a colleague) that the Magento_Reports module has a set-up script which modifies the CMS homepage of Magento. This feels like over-reach. The specific change uses a deprecated feature where each CMS block/page can have layout XML specified in the database. It adds some comments which look like they should be layout instructions, but without any context nor direction for developers.

This pull request removes the modification from future websites. This will have no impact to existing websites as the data patch will have already been applied. I have specifically separated the intended change from the commit where coding standards are applied.

### Manual testing scenarios
1. Install Magento
1. Review layout configuration of `home` CMS page in the database.
   There should be no custom layout configuration set for this page in the database.

### Contribution checklist

 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37782: Reports module has no place modifying CMS homepage

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
@magento create issue

**Comment by fredden** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE, Static Tests, WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @fredden,

Thanks for the contribution!

The changes seems good to me but please fix the static test failures. And also please provide more details on the manual testing scenario.

Thanks

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Charlie** [comment]
Hi @fredden,

Thank you for your contribution!

We are in discussion with Product Owner on this PR as its tagged as feature request in [here](https://github.com/magento/magento2/issues/37782#issuecomment-1665496070). Once we will get input, we have a look at it, till then moving it to On Hold.

Thank you!

**Comment by engcom-Charlie** [comment]
> Hi @fredden,
> 
> Thank you for your contribution!
> 
> We are in discussion with Product Owner on this PR as its tagged as feature request in [here](https://github.com/magento/magento2/issues/37782#issuecomment-1665496070). Once we will get input, we have a look at it, till then moving it to On Hold.
> 
> Thank you!

Hi @fredden,

Can you please mention the area/impact of this change or any error/scenario you have came across to raise this issue. I can see that we are removing layout_update_xml field's data into this PR. It will be really helpful, if you please mention the Expected result in Manual testing scenario.

Thank you!

**Comment by engcom-Charlie** [comment]
Hi @fredden,

Did you get a chance to check [this](https://github.com/magento/magento2/pull/37777#issuecomment-2482163624) comment.

Thank you!

**Comment by fredden** [comment]
> Can you please mention the area/impact of this change or any error/scenario you have came across to raise this issue. I can see that we are removing layout_update_xml field's data into this PR.

I'm not sure what more you want than what I've already provided in the initial pull request description. Can you give an example of what you are expecting to see?

> It will be really helpful, if you please mention the Expected result in Manual testing scenario.

I have updated this part of the pull request description to say that there should no layout configuration changes from the reports module in a CMS page.

**Comment by engcom-Charlie** [comment]
As we not seeing or taking care any functional or a dev experience issue in this PR description, we are not proceeding ahead with modifying the source code. Unfortunately, we are closing this PR for now. Please feel free to reopen it for any further updates.

**Pull request closed without merging**
