### PR TITLE
[Backport]2.2 develop pr port 20224

### PR DESCRIPTION
**Pull request by nainesh2jcommerce**
### Fixed Issues (if relevant)

1. magento/magento2#20221: add your review text is not show uniformly in Mobile view
2. 

### Manual testing scenarios (*)

1. product listing on home page and on listing page
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by nainesh2jcommerce** [comment]
Hi @magento-engcom-team,
Any news on this PR?

Thanks!

**Comment by nainesh2jcommerce** [comment]
Original PR https://github.com/magento/magento2/pull/20257, closing this one.

**Comment by ghost** [comment]
Hi @nainesh2jcommerce, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+magento2+20606), it will take less than a minute. </br>Your feedback will help us to improve contribution process.

**Pull request closed without merging**
