### PR TITLE
Fix rest api update cart item error

### PR DESCRIPTION
**Pull request by ProkopovVitaliy**
### Fixed Issues (if relevant)

1. magento/magento2#28162: Rest api update cart item error!

### Manual testing scenarios (*)

1. try to update qty for cart item via API  `POST /V1/carts/mine/items`
2. request body must contain `custom_options` params

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @ProkopovVitaliy. Could I kindly ask you to cover your change with an API-functional test, please? 

Thank you!

**Comment by ProkopovVitaliy** [comment]
@magento run all tests

**Comment by rogyar** [comment]
Hi @ProkopovVitaliy. Would you check the failing static tests, please? 
Thank you

**Comment by ProkopovVitaliy** [comment]
@magento run all tests

**Comment by ProkopovVitaliy** [comment]
@magento run all tests

**Review by rogyar — DISMISSED** [review]
The failing tests are not related to the changes presented in the current PR.

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7598](https://jira.corp.magento.com/browse/ENGCOM-7598) has been created to process this Pull Request

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @ProkopovVitaliy @rogyar 

During testing, we faced the issue. The expected behavior when adding one product to the cart several times via **POST** is to increment quantity, not overwrite. See [comment](https://github.com/magento/magento2/issues/28162#issuecomment-631621530) from the issue.
[devdocs](https://devdocs.magento.com/guides/v2.3/rest/tutorials/orders/order-add-items.html)

**Manual testing scenario:**

1. Create a Simple product with customizable options;
2. Add created the product to cart with **qty = 2** for example;
3. Try to add qty for cart item via API POST **/V1/carts/mine/items**  (**qty: 4** for example);
Screenshot from 2020-05-29 16-13-10
4. request body must contain custom_options params;

**Actual Result:** :heavy_multiplication_x: The product qty in the Cart is **4**

Screenshot from 2020-06-01 11-20-31

**Expected Result:** The product qty in the Cart should be 6 (2+4)

_Note:_ The PUT request is responsible for overwriting the previously created element

@ProkopovVitaliy @rogyar Could you take a look?

Thanks!

**Comment by ProkopovVitaliy** [comment]
@rogyar Hi. 
I investigated that without my changes and found some weird thing. 
Request:
`POST /V1/carts/mine/items`  

```
{
	"cart_item": {
		"item_id": 24,
		"quote_id": 10,
		"sku": "Testsimple",
		"qty": 2,
		"product_option": {
	              "extension_attributes": {
	                   "custom_options": [
	                    {
	                    "option_id": "21",
	                    "option_value": "41"
	                    }
	                ]
	            }
    	       }
	}
}
```
If called several times - each time overwrite previously created item. 

`PUT /V1/carts/mine/items/24`  

```
{
	"cart_item": {
		"item_id": 24,
		"quote_id": 10,
		"sku": "Testsimple",
		"qty": 2,
		"product_option": {
	              "extension_attributes": {
	                   "custom_options": [
	                    {
	                    "option_id": "21",
	                    "option_value": "41"
	                    }
	                ]
	            }
    	       }
	}
}
```
Works as prev `POST` example (If called several times - each time overwrite previously created item). But if remove `item_id`  from body request: 
```
{
	"cart_item": {
		"quote_id": 10,
		"sku": "Testsimple",
		"qty": 2,
		"product_option": {
	              "extension_attributes": {
	                   "custom_options": [
	                    {
	                    "option_id": "21",
	                    "option_value": "41"
	                    }
	                ]
	            }
    	       }
	}
}
```
If called several times - incremented Qty.  

My changes fix the problem when the query receives an incorrect error for overwritten previously created item as was described in the issue. 
I could not reproduce the behavior described in the [comment](https://github.com/magento/magento2/issues/28162#issuecomment-631621530) in branch 2.4-develop , I received the results described by me above.
So i believe that the error just found needs to be fixed in the context of the new issue.

**Comment by rogyar** [comment]
Hi @ProkopovVitaliy. Please, feel free to create a new PR with the fix mentioned by you in the recent comment. 

Thank you.

**Comment by engcom-Charlie** [comment]
Hi @ProkopovVitaliy, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
