### PR TITLE
move breakpoint by -1px to make nav work correctly at viewport 768

### PR DESCRIPTION
**Pull request by bobemoe**
### Description (*)

The issue fixed in https://github.com/magento/magento2/issues/8298 made huge improvement however there is still a 1px gap where the nav functionality breaks. This is especially obvious on iPad where viewport is exactly 768px. This patch fixes the functionality by moving the breakpoint by 1px.

### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/8298

### Manual testing scenarios (*)

1. Clean install with sample data
2. Open front page in a browser with specific width control (e.g firefox in responsive design mode)
3. Set viewport width to 767: see main nav is hidden and mobile/burger menu is visible (GOOD)
4. Set viewport width to 769: see main nav is visible and mobile/burger menu is hidden, dropdowns work on hover. (GOOD)
5. Set viewport width to 768: see main nav is visible and mobile/burger menu is hidden (GOOD, but:)
    1. without this patch: at 768 the dropdowns do not work on hover, and they contain the "All {category}" items that are only meant to be added on the burger/mobile nav.
    2. with this patch: at 768 the nav functions as expected, dropdown on hover and not including the "All {category}" items.

### Questions or comments
I do see 768 hard coded again in the menu.js file further down I tried changing this too but didn't see any affect. I don't know what that does or why its not using the `mediaBreakpoint` variable, so I left it alone.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23528) <br/>All committers have signed the CLA.

**Comment by bobemoe** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @bobemoe. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @bobemoe, here is your [new Magento instance](https://pr-23528.instances.magento-community.engineering).
Admin access: [https://pr-23528.instances.magento-community.engineering/admin](https://pr-23528.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by bobemoe** [comment]
Tested on the test instance and working fine :)

**Comment by bobemoe** [comment]
Would be good to backport this to 2.2.x? Do I do a separate PR?

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-5386](https://jira.corp.magento.com/browse/ENGCOM-5386) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@bobemoe thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by sivaschenko** [comment]
@bobemoe yes, a PR to 2.2-develop branch should be created to backport this fix. Also, please consider that pull request processing will be soon closed for 2.2-develop as we are moving forward.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by magento-engcom-team** [comment]
@bobemoe thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request merged**
