### PR TITLE
Update sortOrder load for async css plugin

### LINKED ISSUE #30882: [Issue] Update sortOrder load for async css plugin
This issue is automatically created based on existing pull request: magento/magento2#30871: Update sortOrder load for async css plugin

---------

### Description (*)

Magento 2.4-develop
This update made for sure load async css plugin first before JsFooterPlugin load. We use lower order for let magento run AsyncCssPlugin first then run into JsFooterPlugin. After all that is cache plugins will be run

Before this PR
Order plugins
JsFooterPlugin < BuiltinPlugin(PageCache) < VarnishPlugin(PageCache) < AsyncCssPlugin

After this PR
Order plugins now will be
AsyncCssPlugin < JsFooterPlugin < BuiltinPlugin(PageCache) < VarnishPlugin(PageCache)

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Setup site magento 2.4 with code base 2.4-develop
2. Cache types all enabled
3. Enable async css  
Stores > Configuration > Advanced > Developer > Css setttings > Use CSS critical path: YES
4. Clear cache page + config

### Questions or comments

CC: @Henkun @sidolov @krzksz @brightonmike Feel free give to me any suggest or comments
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

This update made for sure load async css plugin first before JsFooterPlugin load. We use lower order for let magento run AsyncCssPlugin first then run into JsFooterPlugin. After all that is cache plugins will be run
And we need sure AsyncCssPlugin (If it enabled) run before page cache plugin magento run (Fullpage or varnish)

When enabled CSS critical path
Before this PR
Order plugins
JsFooterPlugin < BuiltinPlugin(PageCache) < VarnishPlugin(PageCache) < AsyncCssPlugin

After this PR
Order plugins now will be
AsyncCssPlugin < JsFooterPlugin < BuiltinPlugin(PageCache) < VarnishPlugin(PageCache)

When not enable CSS critical path

 JsFooterPlugin < BuiltinPlugin(PageCache) < VarnishPlugin(PageCache)

If not enable (Move js to bottom page)
default magento will run below order
 BuiltinPlugin(PageCache) < VarnishPlugin(PageCache)

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30882

### Manual testing scenarios (*)

1. Setup site magento 2.4 with code base 2.4-develop
2. Cache types all enabled
3. Enable async css  
Stores > Configuration > Advanced > Developer > Css setttings > Use CSS critical path: YES
4. Clear cache page + config

### Questions or comments

CC: @Henkun @sidolov @krzksz @brightonmike Feel free give to me any suggest or comments
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30882: Update sortOrder load for async css plugin

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento create issue

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8451](https://jira.corp.magento.com/browse/ENGCOM-8451) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
I checked - changes are still the same, just were rebased on top of recent changes in 2.4-develop branch, so PR still approved from my side.

@magento run Functional Tests B2B

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B, Integration Tests, WebAPI Tests

**Comment by mrtuvn** [comment]
rebased
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests, Unit Tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE

**Comment by mrtuvn** [comment]
Can we have new proceed on this ?

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8451](https://jira.corp.magento.com/browse/ENGCOM-8451) has been created to process this Pull Request

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8451](https://jira.corp.magento.com/browse/ENGCOM-8451) has been created to process this Pull Request

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE

**Comment by mrtuvn** [comment]
Can we have update higher priority on this ? @ihor-sviziev @sivaschenko

**Comment by sivaschenko** [comment]
@mrtuvn can you please describe the actual functional issue we run into without this change. That may help with prioritization.

cc @sidolov

**Comment by mrtuvn** [comment]
Previous without this change deferJsToFooter plugin may run before asyncCssLoad async plugin

**Comment by HenKun** [comment]
> 
> 
> Previous without this change deferJsToFooter plugin may run before asyncCssLoad async plugin. But in real flow css should run process before js

I think this misses my initial point. The main reason for this change is that the result of the asyncCSS plugin is not cached, hence, if the cached page is served, async CSS has no effect at all, since it is never called. It only has effect on the first visit when the cache is not hit. With this change, the async css algorithm happens before the caching plugin. If it happens before or after the JS plugin doe not matter in my opinion.

**Comment by sivaschenko** [comment]
I will add this issue to the agenda of the next [public triage meeting](https://opensource.magento.com/community-calendar) for discussion

**Comment by sivaschenko** [comment]
We have discussed the issue and decided to increase priority to P2 and severity to S1

**Comment by mrtuvn** [comment]
Rebased branch with mainline magento branch. No change!

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Note: @mrtuvn just rebased his changes, no changes since my approval -> my approval still valid.

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Manual testing scenario:**

- Cache types all enabled
- Enable async css
- Stores > Configuration > Advanced > Developer > Css setttings > Use CSS critical path: YES
- Add logger to each plugin, like:
`$logger->critical('AsyncCssPlugin is called');`
- Clear cache page + config
- Refresh page
- Check logs

**Before:**
:x: Order plugins:
- JsFooterPlugin < BuiltinPlugin(PageCache) < VarnishPlugin(PageCache) < AsyncCssPlugin

image

**After:**
:heavy_check_mark: Order plugins:
- AsyncCssPlugin < JsFooterPlugin < BuiltinPlugin(PageCache) < VarnishPlugin(PageCache)

image

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Pull request merged**
