### PR TITLE
Update laminas/laminas-validator dependency to PHP 8 compatible version

### PR DESCRIPTION
**Pull request by vlmed**
### Description (*)
Updated `laminas/laminas-validator` dependency version.

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/456

### Fixed Issues (if relevant)

Fixes https://github.com/magento/magento2/issues/31781

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by vlmed** [comment]
@magento run all tests

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @vlmed thanks for the pull request! Can you please also update composer lock file in https://github.com/magento/partners-magento2ee as well and link the EE pull request using the [related PR section](https://devdocs.magento.com/contributor-guide/pull-request-tests.html#related-pull-requests).

**Comment by vlmed** [comment]
@magento run all tests

**Comment by coderimus** [comment]
Hello @sivaschenko ,
We have related PR with the test passed :) https://github.com/magento/partners-magento2ee/pull/456#pullrequestreview-576534870 What is our next step here? Please, assist with this.

**Comment by sivaschenko** [comment]
@coderimus @vlmed php8-develop branch was updated today from 2.4-develop with test fixes, let's update the branch and rerun tests. (I don't think there have been any tests launched in ee PR, but it's ok to run tests only on CE since PRs are linked)

**Comment by sivaschenko** [comment]
Update balances and linked the related PR

@magento run all tests

**Comment by coderimus** [comment]
@magento run Functional Tests EE

**Comment by coderimus** [comment]
@sivaschenko related PR is ready for testing

**Comment by sivaschenko** [comment]
@vlmed The versions in CE and EE pull requests are different (2.14.2 and 2.14.0). Can you please update both composer.locks

**Comment by vlmed** [comment]
Hello @sivaschenko . I have upgraded composer.lock and fix merge conflicts.

**Comment by vlmed** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Pull request merged**
