### PR TITLE
Improve performance of getData retrieval

### LINKED ISSUE #36912: [Issue] Improve performance of getData retrieval
This issue is automatically created based on existing pull request: magento/magento2#36321: Improve performance of getData retrieval

---------
The getData() method is called hundred of thousand of times on PLP's without block_cache. Even when everything is cached without FPC, this method can be called thousands of times. A more direct retrieval of data and avoiding extra function calls benefits performance quite a bit. The following performance gains are monitored from a local environment in production mode:

Former setup PLP without block_html:
TIMER: 448.403317 ms
COUNT AMOUNT: 284881x

New setup PLP without block_html:
TIMER: 251.413533 ms
COUNT AMOUNT: 284881x

Former setup PLP with block_html
TIMER: 31.084917 ms
COUNT AMOUNT: 16310x

New setup PLP with block_html:
TIMER: 13.384665 ms
COUNT AMOUNT: 16310x

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by igorwulff**
The getData() method is called hundred of thousand of times on PLP's without block_cache. Even when everything is cached without FPC, this method can be called thousands of times. A more direct retrieval of data and avoiding extra function calls benefits performance quite a bit. The following performance gains are monitored from a local environment in production mode:

Former setup PLP without block_html:
TIMER: 448.403317 ms
COUNT AMOUNT: 284881x

New setup PLP without block_html:
TIMER: 251.413533 ms
COUNT AMOUNT: 284881x

Former setup PLP with block_html
TIMER: 31.084917 ms
COUNT AMOUNT: 16310x

New setup PLP with block_html:
TIMER: 13.384665 ms
COUNT AMOUNT: 16310x

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36912: Improve performance of getData retrieval

### CODE REVIEW

**Comment by igorwulff** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests look not related to changes from this PR.

**Comment by igorwulff** [comment]
@ihor-sviziev thanks, I assume this will get tested further and merged if ok? 

I'm also looking into other segments of this DataObject class and see more room for improvement especially the magic __call class, which is called a lot and costs quite a bit of performance. But I think we shold move that to a different potential PR? I'm just curious how you think about these potential changes (since they are a bit radical):

```
Index: vendor/magento/framework/DataObject.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vendor/magento/framework/DataObject.php b/vendor/magento/framework/DataObject.php
--- a/vendor/magento/framework/DataObject.php	
+++ b/vendor/magento/framework/DataObject.php	(date 1666202240469)
@@ -57,7 +57,7 @@
         }
 
         foreach ($arr as $index => $value) {
-            $this->setData($index, $value);
+            $this->_data[$index] = $value;
         }
         return $this;
     }
@@ -386,22 +386,26 @@
      */
     public function __call($method, $args)
     {
-        switch (substr($method, 0, 3)) {
-            case 'get':
-                $key = $this->_underscore(substr($method, 3));
-                $index = isset($args[0]) ? $args[0] : null;
-                return $this->getData($key, $index);
-            case 'set':
-                $key = $this->_underscore(substr($method, 3));
-                $value = isset($args[0]) ? $args[0] : null;
-                return $this->setData($key, $value);
-            case 'uns':
-                $key = $this->_underscore(substr($method, 3));
-                return $this->unsetData($key);
-            case 'has':
-                $key = $this->_underscore(substr($method, 3));
-                return isset($this->_data[$key]);
+        switch($method[0]) {
+            case 'g':
+                return $this->_data[
+                    self::$_underscoreCache[$method] ?? $this->_underscore($method)
+                ] ?? null;
+            case 's':
+                $this->_data[
+                    self::$_underscoreCache[$method] ?? $this->_underscore($method)
+                ] = $args[0] ?? null;
+                return $this;
+            case 'u':
+                return $this->unsetData(self::$_underscoreCache[$method] ?? $this->_underscore($method));
+            case 'h':
+                return isset(
+                    $this->_data[
+                        self::$_underscoreCache[$method] ?? $this->_underscore($method)
+                    ]
+                );
         }
+
         throw new \Magento\Framework\Exception\LocalizedException(
             new \Magento\Framework\Phrase('Invalid method %1::%2', [get_class($this), $method])
         );
@@ -434,7 +438,16 @@
         if (isset(self::$_underscoreCache[$name])) {
             return self::$_underscoreCache[$name];
         }
-        $result = strtolower(trim(preg_replace('/([A-Z]|[0-9]+)/', "_$1", $name), '_'));
+        $result = strtolower(
+            trim(
+                preg_replace(
+                    '/([A-Z]|[0-9]+)/', "_$1",
+                    lcfirst(substr($name, 3))
+                ),
+                '_'
+            )
+        );
+
         self::$_underscoreCache[$name] = $result;
         return $result;
     }

```

**Comment by ihor-sviziev** [comment]
@igorwulff, pls create a new PR for that changes, and I'll provide feedback about it.

**Comment by engcom-Echo** [comment]
@igorwulff @ihor-sviziev 
Thanks for the collaboration & contribution!


:heavy_check_mark: QA Passed
Improve performance of getData retrieval

**Manual Scenario Steps**
1. Set magento on production mode with block_html disabled and enabled.
2. check the load time of PLP with sample data/without sample data

**Before:** :heavy_multiplication_x: 
Verified with sample data on different PLP

with block_html enabled
```
Pants women - 1.05s        
Tees men - 326ms
Watches -  792ms
Tees-women - 4.54s     
```

with block_html disabled 
```
Pants women - 1.97s
Watches - 1.96s
Tees-women - 1.21s
```

**After:** :heavy_check_mark: 
Verified with sample data on different PLP
with block_html enabled
```
Pants women - 868ms       
Tees men - 126ms
Watches -  463ms
Tees-women - 3.25s     
```

with block_html disabled 
```
Pants women - 1.79s
Watches -  698ms
Tees-women - 1.04s   
```
Hence moving to `Merge In Progress`

**Comment by engcom-Echo** [comment]
@magento create issue

**Pull request merged**
