### PR TITLE
[MFTF] CreateInvoiceAndCheckInvoiceOrderTest refactoring

### PR DESCRIPTION
**Pull request by AnnaAPak**
This PR is to refactor CreateInvoiceAndCheckInvoiceOrderTest according to the best practices

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by AnnaAPak** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by sidolov** [comment]
@magento run Functional Tests CE,Functional Tests EE

**Comment by AnnaAPak** [comment]
@magento run  Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Review by sidolov — APPROVED** [review]

**Comment by AnnaAPak** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B, Semantic Version Checker

**Pull request merged**
