### PR TITLE
15259 : Unable to disable without providing Industry value

### PR DESCRIPTION
**Pull request by sunilit42**
Issue :- https://github.com/magento/magento2/issues/15259

Description:- 
Solved By:- Adding dependency on the Enabled or disabled field.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15366) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=15366) before we can accept your contribution.<br/>

**Comment by sidolov** [comment]
Hi @sunilit42  , please, sign CLA, otherwise, we can't process your pull request

**Comment by sunilit42** [comment]
@sidolov 
yes i did please check it

**Comment by sunilit42** [comment]
@sidolov 
let me know if any issue.

**Comment by magento-engcom-team** [comment]
Similar Pull Request: https://github.com/magento/magento2/pull/15402

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-2271](https://jira.corp.magento.com/browse/ENGCOM-2271) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @sunilit42. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
