### PR TITLE
Update attributes.phtml

### PR DESCRIPTION
**Pull request by springimport**
Fix ";"

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=8397) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=8397) before we can accept your contribution.<br/>

**Comment by okorshenko** [comment]
Hi @springimport 

Could you please sign Contributor License Agreement so that we can process this Pull Request?
Thank you for your contribution!

**Review by okorshenko — APPROVED** [review]

**Comment by okorshenko** [comment]
Hi @springimport
Could you please sign Contributor License Agreement so that we can process this Pull Request?

**Comment by okorshenko** [comment]
Hi @springimport 
I hope you are doing great! 
Could you please sign Contributor License Agreement so that we can process this Pull Request?
This PR is super simple, but we can't accept it without CLA.
Thank you

**Comment by okorshenko** [comment]
Hi @springimport
Could you please sign Contributor License Agreement so that we can process this Pull Request?

**Comment by okorshenko** [comment]
@springimport we fixed this issue in magento code. Thank you for this PR.

**Pull request closed without merging**
