### PR TITLE
Can't translate FPT text on checkout/cart page

### LINKED ISSUE #5477: 2.0.7 : Can't translate FPT text on checkout/cart page
**Preconditions:**

Magento 2.4-develop
Php v 7.3

**Steps to reproduce**

1. Enable FPT in admin; (Go to Admin->Stores->Configuration->Sales->Tax->Fixed Product Taxes);
2. Change translate to FPT `FPT,FPT(translate)` for example (app/code/Magento/Weee/i18n/en_US.csv);
3. Create simple product with FPT attribute and set value for it;
Screenshot from 2020-04-30 12-05-32
4. Go to Storefront;
5. Add created before the product to Cart;
6. Go to Shopping Cart;

:heavy_check_mark: The FPT has been translated
screenshot
7. Proceed to Checkout;
8. Fill all required fields and go to **Review&Payment** step;

**Actual Result:**

:heavy_multiplication_x: The FPT was not translated
screenshot_1

**Expected Result:** 

:heavy_check_mark:  The FPT must be translated

I try to translate the text 'FPT' in the checkout page but nothing seems to work:
I try with a language pack in `app/i18n/Vendor/nl_nl/nl_NL.csv` (the rest of the translations of this pack work so it is loaded):
```
"FPT","Verwijderingsbijdrage",module,Magento_Weee
"Magento_Weee::FPT","Verwijderingsbijdrage",module,Magento_Weee
```
I try with the file `app/design/frontend/Vendor/Theme/i18n/nl_NL.csv`:
```
"FPT","Verwijderingsbijdrage"
"Magento_Weee::FPT","Verwijderingsbijdrage"
```
I try with the file `app/code/Magento/Weee/i18n/nl_NL.csv`:
```
FPT,Verwijderingsbijdrage
```
I try by adding an entry to the 'translation'-table in the database (even had to manually check the crc_string):
```
key_id  string  store_id    translate               locale  crc_string
2       FPT     0           Verwijderingsbijdrage   nl_NL   1575739609
```
All with no success.
I'm running out of options. Is there any spot I missed where I need to put my translation? Can anyone confirm / try if the text 'FPT' in the checkout/cart page is translatable?

### PR DESCRIPTION
**Pull request by engcom-Charlie**
### Description (*)

Added translate

### Fixed Issues (if relevant)

1. magento/magento2#5477: Can't translate FPT text on checkout/cart page

### Manual testing scenarios (*)

Please see https://github.com/magento/magento2/issues/5477

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Hi @engcom-Charlie,
Do you think it will be too hard to cover this change by some integration test?

**Comment by engcom-Charlie** [comment]
Hi @ihor-sviziev,
I don't think it makes sense to write a test for such a small change and complexity of writing a test doesn't match the severity of the issue.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7521](https://jira.corp.magento.com/browse/ENGCOM-7521) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Enable FPT in admin; (Go to Admin->Stores->Configuration->Sales->Tax->Fixed Product Taxes);
2. Change translate to FPT `FPT,FPT(translate)` for example (app/code/Magento/Weee/i18n/en_US.csv);
3. Create simple product with FPT attribute and set value for it;
Screenshot from 2020-04-30 12-05-32
4. Go to Storefront;
5. Add created before the product to Cart;
6. Go to Shopping Cart;
7. Proceed to Checkout;
8. Fill all required fields and go to **Review&Payment** step;

**Before:**

:heavy_multiplication_x: The FPT was not translated
screenshot_1

**After:** 
:heavy_check_mark:  The FPT phrase has been translated
screenshot

**Comment by engcom-Echo** [comment]
@magento run  Functional Tests B2B,  Functional Tests CE,  Functional Tests EE

**Review by sdzhepa — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, thank you for the review.
[ENGCOM-7521](https://jira.corp.magento.com/browse/ENGCOM-7521) has been created to process this Pull Request

**Pull request merged**
