### PR TITLE
Product\Attribute\Repository:save() check product attribute by code i…

### LINKED ISSUE #22391: Rest API Magento 2.3.1 update product attribute not working as expected / documented
### Preconditions (*)
1. Magento 2.3.1
2. Product attribute with attribute code "test_attribute" exists with the default frontend label "Test"

### Steps to reproduce (*)
1. Call the url https://domain.tld/rest/V1/products/attributes/test_attribute with a PUT request containing the following data:
{
  "attribute": {
    "default_frontend_label": "Test2"
  }
}

### Expected result (*)

1. The default frontend label should be changed to "Test2"

### Actual result (*)

1. Get an 400 Bad Request, saying something about missing the frontend_input
2. The default frontend label still is set to "Test"
3. If the frontend_input is supplied it states the attribute already exist

### Workaround 
Also supply the attribute_id in your data like:

{
  "attribute": {
    "attribute_id": 138,
    "default_frontend_label": "Test2"
  }
}

But this is kind of strange because we already supplied the attribute code in the URL to identify what attribute we like to change. Also in our case forcing me to first fire an extra GET request to get the attribute id from the Magento installation.

### PR DESCRIPTION
**Pull request by gomencal**
Product\Attribute\Repository:save() check product attribute by code instead of attribute Id

### Description (*)
Product\Attribute\Repository:save() check product attribute by code instead of attribute Id

### Fixed Issues (if relevant)
Fixes https://github.com/magento/magento2/issues/22391

### Manual testing scenarios (*)
1. Product attribute with attribute code "test_attribute" exists with the default frontend label "Test"
Steps to reproduce (*)
2. Call the url https://domain.tld/rest/V1/products/attributes/test_attribute with a PUT request containing the following data:
```{
"attribute": {
"default_frontend_label": "Test2"
}
}
```
3. Attribute default frontend label must be changed to "Test2"

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @gomencal,
Could you resolve conflicts and cover your changes with integration or web api test as unit test isn't effective for such cases?

**Comment by gabrieldagama** [comment]
The risk was set to`low` due to: the suggested changes shouldn't affect other areas.

**Comment by ihor-sviziev** [comment]
Hi @gomencal,
Will you be able to update your PR with requested changes?

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@sidolov the pull request successfully imported.

**Comment by engcom-Hotel** [comment]
Hello @gomencal.
Unfortunately, your fix breaks products attribute creation.
Could you please update your solution to be compatible with the cases when tests are failing?

**Comment by engcom-Hotel** [comment]
Risk: medium since the attributes of the product are affected.

**Comment by ihor-sviziev** [comment]
@gomencal  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
