### PR TITLE
Added language translation in template files

### PR DESCRIPTION
**Pull request by RahulKachhadia**
### Description

Added language translation for labels in `Magento_Braintree`, `Magento_Multishipping` and `Magento_Paypal` extensions

### Fixed Issues (if relevant)

1. N/A

### Manual testing scenarios

1. N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by mzeis — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @mzeis, thank you for the review.
[ENGCOM-1591](https://jira.corp.magento.com/browse/ENGCOM-1591) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @rahul-kachhadiya. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

Please, consider porting this solution across release lines.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Comment by RahulKachhadia** [comment]
@vijay-wagento Thank you for creating [Forwardport] PR for 2.3-develop branch. 

Porting tool giving an error in [Backport] PR for 2.1-develop branch. Do you know how to resolve that error? 

Thank you.

**Comment by vijay-wagento** [comment]
Hello @rahul-kachhadiya 
If it throws the error for backport then you can download log also from porting tool.
That will help you to understand what causes that error.
Let me know if you need more info,

**Comment by RahulKachhadia** [comment]
Hi @vijay-wagento 
I tried to understand error by downloading log from porting tool but not getting. Can you please take a look? So, it will help me next time.

**Comment by vijay-wagento** [comment]
Hello @rahul-kachhadiya 
Can you please attach here or send me over slack?

**Comment by RahulKachhadia** [comment]
Hello @vijay-wagento 
I'm attaching error log here: 
[_artifacts_logs_rahul-kachhadiya_magento2_2.1-develop_1528179361.4596_15371.log](https://github.com/magento/magento2/files/2071163/_artifacts_logs_rahul-kachhadiya_magento2_2.1-develop_1528179361.4596_15371.log)

Please take a look and let me know if you getting an issue.

**Comment by vijay-wagento** [comment]
Hello @rahul-kachhadiya 
I checked one file and I found that you removed one line which is not matching with the line in 2.1, so the patch cannot apply automatically.  This is my guess.
Please find attached image.
pr
You can create Backport manually for this kind of issue. I just provided one file as an example. You can check for other files also.

Let me know if you have any other question,

**Pull request merged**
