### PR TITLE
Fixed VAT Number verification error message should be in red color #20311

### PR DESCRIPTION
**Pull request by surabhisrivastava09**
### Description (*)
Fixed VAT Number verification error message should be in red color #20311

### Manual testing scenarios (*)
1. Goto admin >> stores >> configuration >> general >> store information >> click on "Validate VAT Number"
 2. Showing error message like "Error during VAT Number verification."

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Surabhi-Cedcoss. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3865](https://jira.corp.magento.com/browse/ENGCOM-3865) has been created to process this Pull Request

**Comment by sidolov** [comment]
Hi @Surabhi-Cedcoss we found that provided changes does not fix the whole problem: 

Testing scenario:

1. Navigate to Stores->Configuration->General->Store Information
2. Click Validate VAT Number
2. Validation message color isn't red

**Comment by sidolov** [comment]
@Surabhi-Cedcoss , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
