### PR TITLE
typo-fixes: Remove duplicate "the".

### PR DESCRIPTION
**Pull request by pratikhmehta**
### Description (*)

Removed duplicate "the" in XML file.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24749) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=24749) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: pratikhmehta<br/>:x: Pratik Mehta<hr/>**Pratik Mehta** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Review by VladimirZaets — APPROVED** [review]

**Comment by pratikhmehta** [comment]
@buskamuza , @akaplya Still pending?

**Comment by sdzhepa** [comment]
Hello @pratikhmehta 

Could you please sign a new Adobe CLA?
Without it, we cannot able to process the PR.
You can easily вш it by next steps
- Scroll down to the GitHub checks section(bottom of the page)
- Find check with the title "Adobe CLA Signed?"
- and click the [Details ](https://github.com/magento/magento2/pull/24749/checks?check_run_id=252596023)link

**Comment by pratikhmehta** [comment]
@sdzhepa I have successfully signed in into Adobe CLA.

**Comment by pratikhmehta** [comment]
licence/cla Pending — Contributor License Agreement is not signed yet.[Details](https://cla.dev.magento.com/magento/magento2?pullRequest=24749) link is not working.

**Comment by VladimirZaets** [comment]
Hi @pratikhmehta. Thanks for collaboration.
Those fixes already delivered to mainline in the scope of commit 1e209aad6f9d3b9cce90421728e4641b6f567429.

**Pull request closed without merging**
