### PR TITLE
Issue 19456

### PR DESCRIPTION
**Pull request by mahendra1988**
### Fixed Issues (if relevant)

1. magento/magento2#19456 : Admin Sub-Menu Navigation Feature

### Manual testing scenarios (*)

1. Go to admin > you can see the submenu have icons that will indicate the sub-menu

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19459) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=19459) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: mahendra1988<br/>:x: advanipunit

**Comment by magento-engcom-team** [comment]
Hi @mahendra1988. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by VladimirZaets** [comment]
Hi @mahendra1988 , please, sign CLA, otherwise, we can't process your pull request

**Comment by mahendra1988** [comment]
> Hi @mahendra1988 , please, sign CLA, otherwise, we can't process your pull request

Done

**Comment by sidolov** [comment]
Hi @mahendra1988  , looks like you made some commits with email different than in your GitHub profile, please, add email from commits to your profile!
Thank you!

**Comment by VladimirZaets** [comment]
@mahendra1988, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Pull request closed without merging**
