### PR TITLE
Cms page/block eventprefix fix issue 9900

### PR DESCRIPTION
**Pull request by convenient**
Fix issue https://github.com/magento/magento2/issues/9900 by defining `eventPrefix` and `eventObject` against collections.

This issue is fixed in the `develop` branch by https://github.com/magento/magento2/pull/11046

This PR cherry-picks those commits into the `2.2-develop` branch.
```bash
$ git cherry-pick a15f4cc7e77b672b94657620e7e961265160d103 bf0dbee9cc4483f212b9c5643f3e50df7a2214cd d782c711321a10879f4b0d24e6400a45ac04bed8 a87f1cfdc5907eac0185316636ebe99b800a1ac4
[cms-page-eventprefix-fix-issue-9900 08491d33e99] Add EventPrefix to CMS Page/Block Collection
 Author: Oscar Recio <oscar.recio@interactiv4.com>
 Date: Tue Sep 26 11:17:51 2017 +0200
 2 files changed, 14 insertions(+)
[cms-page-eventprefix-fix-issue-9900 bc6180ca862] Add EventPrefix to CMS Page/Block Collection
 Author: Oscar Recio <oscar.recio@interactiv4.com>
 Date: Tue Sep 26 11:29:20 2017 +0200
 1 file changed, 1 insertion(+), 1 deletion(-)
[cms-page-eventprefix-fix-issue-9900 e110196da16] Add EventObject to CMS Page/Block Collection
 Author: Oscar Recio <oscar.recio@interactiv4.com>
 Date: Tue Sep 26 11:52:56 2017 +0200
 2 files changed, 15 insertions(+), 1 deletion(-)
[cms-page-eventprefix-fix-issue-9900 ce93e40ae2d] Add EventObject to CMS Page/Block Collection
 Author: Oscar Recio <oscar.recio@interactiv4.com>
 Date: Tue Sep 26 11:54:08 2017 +0200
 1 file changed, 2 insertions(+), 2 deletions(-)
```

I'll see how this runs against travis, if it passes I'd consider this a success.

#SQUASHTOBERFEST 

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by okorshenko** [comment]
Hi @convenient
could you please accept invite from magento-team on the GitHub?

**Comment by convenient** [comment]
@okorshenko 
>You now have view access to the magento/magento2 repository.

What changed?

**Comment by okorshenko** [comment]
@convenient now we can assign issues to you
Please check this https://twitter.com/maksek_ua/status/915572031005057025

**Comment by convenient** [comment]
@okorshenko thanks! That's what I get for pushing code before reading the associated documentation 😅

**Pull request merged**
