### PR TITLE
[BackPort] resolve typos and correct variable names

### PR DESCRIPTION
**Pull request by viral-wagento**
### Description

Fixed typos and added proper variable names in below files:
Original PR: #19288 

app/code/Magento/Sales/Model/Order.php
app/code/Magento/Sales/etc/adminhtml/system.xml

### Manual testing scenarios

1. app/code/Magento/Sales/Model/Order.php
Line:668 - replaced $hasActinFlag to $hasActionFlag
Line:688 - replaced $dueAmountCondition to $hasDueAmount
Line:690 - replaced $creditmemos to $creditMemos

2. app/code/Magento/Sales/etc/adminhtml/system.xml
Line:52 - replaced Allow Zero GrandTotal to Allow Zero GrandTotal for Credit Memos
Line:54 - replaced Allow Zero GrandTotal for Creditmemo to Allow Zero GrandTotal for Credit Memos 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by sivaschenko** [comment]
Hi @viral-wagento thanks for your contribution, can you please forwardport this pull request to 2.3 as well.

Original pull request https://github.com/magento/magento2/pull/16005

**Comment by VladimirZaets** [comment]
Hi @viral-wagento. Thanks for the collaboration. Please add the translation for "Allow Zero GrandTotal for Credit Memos" and "Allow Zero GrandTotal for Credit Memos" phrases to `en_US.csv`

**Comment by orlangur** [comment]
Unfortunately, we can't accept such Pull Requests to 2.2 release line, all code cleanup like typos, spelling mistakes, etc should be delivered to 2.3 release line. For more information, please, refer to [Magento Code Contributions Guide](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#rules).

**Comment by VladimirZaets** [comment]
Hi @viral-wagento. As @orlangur said above firstly PR should be delivered to 2.3 Magento branch. Please create PR to 2.3 Magento branch.

**Comment by orlangur** [comment]
@VladimirZaets it is already merged to 2.3 in https://github.com/magento/magento2/pull/19288.

I would accept this one to 2.2 as it contains not just typo fixes but also missing translations.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3677](https://jira.corp.magento.com/browse/ENGCOM-3677) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @viral-wagento. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.

**Comment by viral-wagento** [comment]
@magento-engcom-team @sidolov 
This has already been developed and merged in 2.3 release line.
https://github.com/magento/magento2/pull/19288
Thanks!!

**Pull request merged**
