### PR TITLE
Fix the issue when Shopping cart is emptied after reset password procedure #14530

### PR DESCRIPTION
**Pull request by maximbaibakov**
Fix the issue when Shopping cart is emptied after reset password procedure

### Description
Removed a code which were destroying session for current customer rather then for customer who requesting password reset

### Fixed Issues (if relevant)
1. magento/magento2#14530

### Manual testing scenarios
1. As a guest, put some items in shopping cart
2. Login -> Forgot Password
3. Enter Email, press "Reset Password" button
4. From mail press "Set a new password"
5. On "Forgot Password" page input new password. Shopping cart is still have items in it.
6. Press button "Set a new password"
7. Shopping cart not empty after setting new password.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=17517) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @maximbaibakov. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
@maximbaibakov please check if https://github.com/magento/magento2/commit/bc8d3d5d0ead9779cb22d19201cd731719a79b0c will do the trick.

**Comment by orlangur** [comment]
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

**Comment by hryvinskyi** [comment]
The same error on Magento 2.2.7
This commit: https://github.com/magento/magento2/commit/bc8d3d5d0ead9779cb22d19201cd731719a79b0c  does not fix this error

**Comment by VladimirZaets** [comment]
@maximbaibakov, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Pull request closed without merging**
