### PR TITLE
Adobe stock integration Issue-761: Highlight the selected image in the grid

### PR DESCRIPTION
**Pull request by serhiyzhovnir**
This PR adds styles to a selected image in the grid.
Screen Shot 2019-12-01 at 08 59 27
Screen Shot 2019-12-01 at 08 59 13

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#761: Highlight the selected image in the grid

### Manual testing scenarios (*)

1. Login to admin panel
2. Open Magento Media Gallery (i.e. go to Cms -> Pages, edit the page and insert image)
3. Click "Search Adobe Stock" button to open images grid
4. Click on any image to expand image preview

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the PR @serhiyzhovnir ! Can you please cover the added method with a jasmine test?

**Comment by slavvka** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
Hi @serhiyzhovnir. Thanks for collaboration. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

**Comment by sivaschenko** [comment]
@VladimirZaets this PR is improving the opening image preview functionality that is covered by MFTF tests: https://github.com/magento/adobe-stock-integration/tree/1.1-develop/AdobeStockImageAdminUi/Test/Mftf/Test

**Review by sivaschenko — APPROVED** [review]

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
