### PR TITLE
Fix Adapter\Pdo\Mysql::closeConnection on non-default ports

### PR DESCRIPTION
**Pull request by JacobBrownAustin**
### Description (*)

Fixing Magento\Framework\DB\Adapter\Pdo\Mysql::closeConnection when the port is a non-default port.  When we are using a non-default port for the database,  and closeConnection() method is called,  this prevents automatic reconnection from working.  This is because during the connection,  we move the port into $this->_config['port'].

The closeConnection() is not called in normal Magento usage.  However,  it is always called when running the integration tests.  This means that that you cannot use integration tests with a Mysql server on a non-default port.

### Manual testing scenarios (*)

Steps to reproduce the error that this bugs fixes:

1. Configure a Mysql server using a custom port.
2. Configure Magento integration tests to use this database.
3. Try to run integration tests.

Expected Result:  Integration tests pass.

Actual Result:  Integration tests fail with errors because they use closeConnection() which loses the port configuration.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5445](https://jira.corp.magento.com/browse/ENGCOM-5445) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@JacobBrownAustin thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the pull request @JacobBrownAustin ! I think the `port` should be added to the `host` in `_connect` method as well (as that was the initial purpose of deleted code block according to comment).

**Comment by JacobBrownAustin** [comment]
> Thanks for the pull request @JacobBrownAustin ! I think the `port` should be added to the `host` in `_connect` method as well (as that was the initial purpose of deleted code block according to comment).

I don't know why,  but the _connect() method requires the port to be specified in the host.  Magento doesn't have a separate port field in the env.php file.
You can see this in the documentation for setup:install https://devdocs.magento.com/guides/v2.3/install-gde/install/cli/install-cli-install.html under "--db-host" section.
"Note: You can optionally specify the database server port in its hostname like www.example.com:9000"

In order to not break backwards compatibility,  my pull request does not change this functionality.  It only provides a way for it to continue working if the closeConnection() method is called.

To better understand current functionality,  I will explain it here.

(This use-case is for when using non-default port.)
1.  port is configured by user to be added to the host when configured,  separated by a ':' character.  (Either by setup:install or manually editing env.php)
2.  _connect() method checks if the $this->_config['port'] exists,  and errors if it does.
3. _connect() splits $this->_config['host'] into $this->_config['host'] and $this->_config['port']
4. If $this->closeConnection() is called,  and then connection is later used, it fails during reconnection because $this->_config['port'] now exists.  (Note:  The only time I've seen closeConnection() called is when running integration tests.  It seems to always call this somewhere, maybe between tests.)

So,  my solution is to move the work-around code that currently exists in query() method here to an overridden method of closeConnection().  https://github.com/magento/magento2/pull/23428/files#diff-2b5067e3a6c0d21915ae0431519dcc76L574

This way,  we do not break any code or tests that depends on the port being required to be part of the host.

**Review by sivaschenko — APPROVED** [review]
@JacobBrownAustin Got it, thank you!

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-5445](https://jira.corp.magento.com/browse/ENGCOM-5445) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by sivaschenko** [comment]
@magento run all tests

**Pull request merged**
