### PR TITLE
Ensured the Page cache identifier is read in the same way and checking and saving the cache identifier

### LINKED ISSUE #38626: Built-in FPC cache is broken in 2.4.7 for some configurations
### Preconditions and environment

- Magento version: 2.4.7
- Use built in FPC
- Have a`MAGE_RUN_CODE` parameter set

### Steps to reproduce

1. Enable built-in FPC
2. Have a **MAGE_RUN_CODE** parameter in your **$_SERVER** array
3. Load a frontend page
4. Load the same page again

### Expected result

Page is cached, and in developer mode a header `X-Magento-Cache-Debug: HIT` is set

### Actual result

Page is  uncached, and in developer mode a header `X-Magento-Cache-Debug: MISS` is set

### Additional information

In 2.4.7 the identifier for saving a page to cache was decoupled from the fetching identifier:

https://github.com/magento/magento2/blob/725b6483932b4bbbbd9f463de80c82914346643d/app/code/Magento/PageCache/Model/App/Request/Http/IdentifierForSave.php#L18

However the fetching identifier has plugins on it that prepend the cache key with some parameters:

https://github.com/magento/magento2/blob/725b6483932b4bbbbd9f463de80c82914346643d/app/code/Magento/PageCache/Model/App/CacheIdentifierPlugin.php#L67

That plugin is not added to the saving part, hence the key will always mismatch if there are additional parameters 

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by digitalrisedorset**
### Ensured the Page cache identifier is read in the same way and checking and saving the cache identifier
The change consists using a new model that pulls the design + store cache parameters. This model is injected in both places that needs these cache information. This has meant a plugin was removed in favour of this model. 

### Description (*)
When the page gets loaded, the FPC checks if the page cache identifier is already saved in the cache. This reading checks the server environment variables (eg: PARAM_RUN_CODE). 
When the page has been rendered, the page cache identifier is saved to prevent the same page to be reloaded the next loads the same version for it. The identifier was currently saved differently to the identifier created in the reading phase and that was breaking the cache

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38626
#### Test 1: Backward compatibility - The FPC works 
Setup the Magento store with no environment variable `PARAM_RUN_CODE`, `PARAM_RUN_TYPE`, ensure the Full page cache is enabled and set the developer mode active, load a page twice and verify the second load is cached by checking the header `X-Magento-Cache-Debug`
#### Test 2: Test the fault - The FPC works with environment variables
Setup the Magento store with some environment variables `PARAM_RUN_CODE`, `PARAM_RUN_TYPE`, ensure the Full page cache is enabled and set the developer mode active, load a page twice and verify the second load is cached by checking the header `X-Magento-Cache-Debug`

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by digitalrisedorset** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi,

Internal team has started to work on it

Thanks.

**Comment by hostep** [comment]
For some reason, this PR wasn't marked as merged, even though (some of) the code was merged (via cherry-picks) recently as part of this bigger merge: https://github.com/magento/magento2/commit/0c53bbf7b6712c9b979a1c7ee71594ce523d78e3

**Comment by Bhavik-kumar** [comment]
Hi @magnto 

When is it expected that this problem will be included in control release 2.4.7-p1?
People have been certifying 2.4.7 for a few days now. 

Is this same issue resolve for Varnish?

Bhavik

**Pull request closed without merging**
