### PR TITLE
31782 - Update laminas/laminas-log package

### PR DESCRIPTION
**Pull request by AndreyChorniy**
### Description (*)
This PR for update package laminas/laminas-log package

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/524

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31782

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Changes looks good to me. Let's wait for test results

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Pull request merged**
