### PR TITLE
Removed unwanted interface implementation

### PR DESCRIPTION
**Pull request by vishal-7037**
### Description (*)

Fixed 404 error issue on dashboard at Magento admin when clicked on **Most viewed products** tab
### Fixed Issues (if relevant)

1. magento/magento2#22001: Magento backend dashboard: Most viewed products tabs gives 404 error in console.

### Manual testing scenarios (*)

1. Login to Magento admin
2. Click on **Most viewed products** tabs, a spinner will be loading continuously.
3. Open developer console, you will get 404 error.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @vishal-7037. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — APPROVED** [review]
@nmalevanec could you please look into this, change was introduced in https://github.com/magento/magento2/commit/5103b8eee5700dfe457a5d138f7c7af838b72dcb

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4601](https://jira.corp.magento.com/browse/ENGCOM-4601) has been created to process this Pull Request

**Comment by nmalevanec** [comment]
> @nmalevanec could you please look into this, change was introduced in [5103b8e](https://github.com/magento/magento2/commit/5103b8eee5700dfe457a5d138f7c7af838b72dcb)

@orlangur, wrong interface has been introduced by mistake.  Have changed it to correct one https://github.com/magento/magento2/pull/22002/commits/192833fcda8553f4d85b01d1713783cd7f2dbfa9

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4601](https://jira.corp.magento.com/browse/ENGCOM-4601) has been created to process this Pull Request

**Review by orlangur — CHANGES_REQUESTED** [review]
@nmalevanec could you please squash your commits into a single one?

**Comment by nmalevanec** [comment]
@orlangur, done.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4601](https://jira.corp.magento.com/browse/ENGCOM-4601) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed 

**Before:**

before

**After:**

after

**Pull request merged**
