### PR TITLE
[Customer] Fixed customer module related mftf tests

### LINKED ISSUE #32656: [Issue] [Customer] Fixed customer module related mftf tests
This issue is automatically created based on existing pull request: magento/magento2#32606: [Customer] Fixed customer module related mftf tests

---------

### Description (*)

1. 
```
Field by name, label, CSS or XPath element with //input[contains(@name, 'customer[dob]')] was not found.
```
2.
```
Field by name, label, CSS or XPath element with //select[contains(@name, 'customer[gender]')] was not found.
```
3.
```
CSS or XPath element with //td[@class='data-grid-checkbox-cell'] was not found.
```

Tests crashing by:
1. DOB config could be disabled in configs
2. Gender config could be disabled in configs
3. Show prefix config could be disabled in configs

### Related Pull Requests
https://github.com/magento/magento2/pull/32090

### Manual testing scenarios (*)

1. Run AdminCheckDateOfBirthValidationForFranceDateFormatTest tests with disabled `Show DOB` config
2. Run AdminChangeCustomerGenderInCustomersGridTest tests with disabled `Show Gender` config
3. Run AdminCreateCustomerWithPrefixTest with disabled `Show Prefix` config

### Questions or comments

This PR is not directly related to https://github.com/magento/magento2/pull/32090 but made for taking Complete MFTF

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by Den4ik**
### Description (*)

1. 
```
Field by name, label, CSS or XPath element with //input[contains(@name, 'customer[dob]')] was not found.
```
2.
```
Field by name, label, CSS or XPath element with //select[contains(@name, 'customer[gender]')] was not found.
```
3.
```
CSS or XPath element with //td[@class='data-grid-checkbox-cell'] was not found.
```

Tests crashing by:
1. DOB config could be disabled in configs
2. Gender config could be disabled in configs
3. Show prefix config could be disabled in configs

### Related Pull Requests
https://github.com/magento/magento2/pull/32090

### Manual testing scenarios (*)

1. Run AdminCheckDateOfBirthValidationForFranceDateFormatTest tests with disabled `Show DOB` config
2. Run AdminChangeCustomerGenderInCustomersGridTest tests with disabled `Show Gender` config
3. Run AdminCreateCustomerWithPrefixTest with disabled `Show Prefix` config

### Questions or comments

This PR is not directly related to https://github.com/magento/magento2/pull/32090 but made for taking Complete MFTF

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32656: [Customer] Fixed customer module related mftf tests

### CODE REVIEW

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run WebAPI Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B, Database Compare

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Unit Tests, Functional Tests EE, Functional Tests B2B

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run WebAPI Tests, Functional Tests EE, Functional Tests B2B

**Comment by Den4ik** [comment]
@magento run Functional Tests EE

**Comment by Den4ik** [comment]
@magento run Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento create issue

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8982](https://jira.corp.magento.com/browse/ENGCOM-8982) has been created to process this Pull Request

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @Den4ik thanks for contributing!

Can we try to run the tests without clearing cache and reindexing?

**Comment by Den4ik** [comment]
> Hi @Den4ik thanks for contributing!
> 
> Can we try to run the tests without clearing cache and reindexing?

Hi @gabrieldagama 
I hope cache clearing could be skipped, but reindex required because after changing configs customer_grid index marked as invalid and saving of customer don't trigger grid update. As result grid contain not actual customer data

**Comment by gabrieldagama** [comment]
Hi @Den4ik, these tests are passing currently on our test suite, I believe it is because they are asserting things on Admin area and the configuration itself does not affect that area, the DOB, Gender and Prefix will be visible anyway.

Closing this PR for now, please let me know if we need to reopen it.

Thanks

**Comment by Den4ik** [comment]
Hi @gabrieldagama 
This tests failed on clear 2.4-develop when I run it locally.
Are you sure that it's ok?

**Comment by Den4ik** [comment]
Hi @gabrieldagama 
In my opinion PR should be reopened
Customer attribute visibility by default is `false` - https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/Setup/CustomerSetup.php#L240
AttributeResolver that hide field - https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/Model/AttributeMetadataResolver.php#L159-L162

So on clear installation of 2.4-develop without sample data this test fail. Also the failed on #32090

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9024](https://jira.corp.magento.com/browse/ENGCOM-9024) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
As we discussed in Slack with @Den4ik, these tests start failing if we have hidden these fields (this is the default behavior), so basically, we should show them for the correct work of these tests, not depending on which tests were running in the past.

The reason why these tests weren't failing - not enough test isolation, and some of the tests were running before and were setting these settings. But now, for some reason, in https://github.com/magento/magento2/pull/32090, the order of executed tests has changed, and that caused a test failure.

**Comment by Den4ik** [comment]
As we discussed in Slack with @gabrieldagama Admin form should contain all customer fields independently from configs.
Failed tests in https://github.com/magento/magento2/pull/32090 related to removed `reverseMetadataMerge` flag.

So, there is no issue. I'm closing this PR

**Pull request closed without merging**
