### PR TITLE
[MFTF] Fixed file name violations

### LINKED ISSUE #28305: [Issue] [MFTF] Fixed file name violations
This issue is automatically created based on existing pull request: magento/magento2#27839: [MFTF] Fixed file name violations

---------
### Description

Small file name fixes, based on MFTF conventions.

https://devdocs.magento.com/mftf/docs/best-practices.html#file-names

### PR DESCRIPTION
**Pull request by elevinskii**
### Description

Small file name fixes, based on MFTF conventions.

https://devdocs.magento.com/mftf/docs/best-practices.html#file-names

### Resolved issues:
1. [x] resolves magento/magento2#28305: [MFTF] Fixed file name violations

### CODE REVIEW

**Review by lbajsarowicz — DISMISSED** [review]
Amazing! Thank you!

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7343](https://jira.corp.magento.com/browse/ENGCOM-7343) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi, @elevinskii. Could you resolve merge conflicts?

**Comment by elevinskii** [comment]
> Hi, @elevinskii. Could you resolve merge conflicts?

Sure, the branch is updated, thanks!

**Review by VladimirZaets — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7343](https://jira.corp.magento.com/browse/ENGCOM-7343) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
QA not applicable

**Review by slavvka — CHANGES_REQUESTED** [review]
@elevinskii please resolve the conflicts and re-run tests after upgrade to PHP 7.4

**Comment by elevinskii** [comment]
@lbajsarowicz Thanks for the update!

@slavvka The functional tests were failed, but I'm completely sure it's not because of my changes.

**Comment by elevinskii** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by slavvka** [comment]
@magento run all tests

**Review by slavvka — APPROVED** [review]

**Comment by slavvka** [comment]
@magento create issue

**Comment by magento-engcom-team** [comment]
Hi @slavvka, thank you for the review.
[ENGCOM-7343](https://jira.corp.magento.com/browse/ENGCOM-7343) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA not applicable

**Comment by engcom-Charlie** [comment]
Failed functional test not related to changes from this PR.

**Comment by engcom-Charlie** [comment]
Failed tests not related to changes from this PR.

**Pull request merged**
