### PR TITLE
Organizing setup command files and namespaces

### PR DESCRIPTION
**Pull request by steverobbins**
This PRs aims to improve the organization of the setup commands.

Currently [they all "live" in one folder](https://github.com/magento/magento2/tree/98fd5b97220a8e568c35a184d9e9a5708a0611cf/setup/src/Magento/Setup/Console/Command).  As more commands are added this will become cluttered and hard to manage.

I've organized the commands into logical folders and namespaces based on their command names, e.g.
- `setup:performance:generate-fixtures` -> `Setup\Performance\GenerateFixturesCommand`
- `maintenance:enable` -> `Maintenance\EnableCommand`

etc.

A similar organization strategy was applied to tests for these commands.

This doesn't change the name or behavior of any commands.

### CODE REVIEW

**Comment by Vinai** [comment]
Thank you for the PR! We are currently waiting for the travis builds to work again, which should happen in a few days. Once that is running and the tests are green we can continue to process your contribution.

**Comment by mazhalai** [comment]
@steverobbins thank you for your PR, however, we do not anticipate adding new commands to the setup namespace. Each module can add their own commands in `Console/Command` as in https://github.com/magento/magento2/tree/2.0/app/code/Magento/Backend/Console/Command. Other than from a code management perspective can you explain why this change is necessary.

**Comment by steverobbins** [comment]
It's just for organization.

**Comment by mazhalai** [comment]
@steverobbins please sync with develop branch and re-run tests. Tests for PHP7 are missing

**Comment by steverobbins** [comment]
Rebased on `develop`

**Comment by steverobbins** [comment]
Having trouble debugging why this is failing (well, I know why but I can't test locally).

In `integration_part_2` it references [`phpunit.xml.travis2`](https://github.com/magento/magento2/blob/develop/.travis.yml#L67), but I don't see this file in the repo.  @mazhalai, I see you wrote this line, maybe you could shed some light on this?

Also on the topic of organization, does it makes sense to have command tests in _both_
- `setup/src/Magento/Setup/Test/Unit/Console/Command/` and
- `dev/tests/integration/testsuite/Magento/Setup/Console/Command`?

**Comment by steverobbins** [comment]
More organization comments now that I'm looking at this again...  I realize I'm being picky, just trying to hammer down what will become standard convention before it's too late (i.e. M1's [`getAllOptions` vs `toOptionArray`](http://stackoverflow.com/q/20804365/763468)).

---
- `setup/src/Magento/Setup/Console/Command/Admin/User/CreateCommand.php`
- `setup/src/Magento/Setup/Test/Unit/Console/Command/Admin/User/CreateCommandTest.php`

These are not related to setup commands (no `setup:` prefix).  Do they (and others like it) belong here?  Wouldn't it make more sense for this command to be part of the `Magento\Authorization` module?

---

Using

```
namespace Magento\Setup\Test\Unit\Console\Command\Admin\User;
```

is inconsistent with those of `integration_part_2`, which uses

```
namespace Magento\Setup\Console\Command;
```

I think it's better for the former to follow the latter, e.g.

```
namespace Magento\Setup\Console\Command\Admin\User;
```

since it elemenates an extra `use Magento\Setup\Console\Command\Admin\User\CreateCommand;`.

**Comment by mazhalai** [comment]
@steverobbins 
- Travis has a limit of 1 hour for tests and our integration tests longer than that, so they are split into 2 parts, and phpunit.xml.travis1 and phpunit.xml.travis2 are created during run time, using this [bash command](https://github.com/magento/magento2/blob/develop/dev/tests/integration/IntegationTestsForTravis.sh)
- the integration tests are failing with the following fatal errors:

```
PHP Fatal error:  Class 'Magento\Setup\Console\Command\DependenciesShowFrameworkCommand' not found in /home/travis/build/magento/magento2/dev/tests/integration/testsuite/Magento/Setup/Console/Command/DependenciesShowFrameworkCommandTest.php on line 54
Fatal error: Class 'Magento\Setup\Console\Command\DependenciesShowFrameworkCommand' not found in /home/travis/build/magento/magento2/dev/tests/integration/testsuite/Magento/Setup/Console/Command/DependenciesShowFrameworkCommandTest.php on line 54
```
- Yes ideally admin user would be in authorization, but we need to create a default admin user during install, and it should not be dependent on the state of Magento application, which could be missing modules, or have the authorization module disabled.

**Comment by steverobbins** [comment]
Rebased on develop.

**Comment by vrann** [comment]
@steverobbins Too many commands had changed since this PR, so I'm closing it, but feel free to create a new one if this change still makes sense to you.

The only thing I'd like to highlight is that commands in Setup are the special case: this were all the commands which should not rely on the application being installed or thos which does not belong to the particular module. We are moving away from this approach and add more and more commands like this to the Developer module. So having them in one folder is not a precedent in any way to follow the same pattern with the other comments

**Pull request closed without merging**
