### PR TITLE
Avoid divide-by-zero fatal error

### LINKED ISSUE #37804: [Issue] Avoid divide-by-zero fatal error
This issue is automatically created based on existing pull request: magento/magento2#37479: Avoid divide-by-zero fatal error

---------
### Description
While working on https://github.com/Ethan3600/magento2-CronjobManager/issues/122, I noticed that providing asking Magento to validate a cron expression which contains `/0` resulted in a Fatal error, rather than an exception which I could catch. This pull request fixes the divide-by-zero bug and instead produces a sensible exception. Includes unit test.

### Manual testing scenarios
1. Call `\Magento\Cron\Model\Schedule::matchCronExpression('0/0', 0)`

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fredden**
### Description
While working on https://github.com/Ethan3600/magento2-CronjobManager/issues/122, I noticed that providing asking Magento to validate a cron expression which contains `/0` resulted in a Fatal error, rather than an exception which I could catch. This pull request fixes the divide-by-zero bug and instead produces a sensible exception. Includes unit test.

### Manual testing scenarios
1. Call `\Magento\Cron\Model\Schedule::matchCronExpression('0/0', 0)`

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37804: Avoid divide-by-zero fatal error

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Unit Tests ,Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Static Tests,Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento create issue

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests

**Comment by engcom-Echo** [comment]
Failing test does not  seems to be related to PR changes. Hence moving it to `merge in progress`

**Comment by engcom-Echo** [comment]
@magento run all test

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run  Functional Tests EE , Functional Tests CE, Functional Tests B2B, Integration Tests,Unit Tests

**Comment by engcom-Echo** [comment]
Functional Tests EE,Functional Tests CE Failures are different on last two run on same commit.Other Build Failure are not related to PR changes.
Functional Tests EE
Run1
37479-ee

Run2
Screenshot 2023-08-18 at 2 35 48 PM

Functional Tests CE
Run1
37479-ce

Run2
Screenshot 2023-08-18 at 2 35 35 PM

**Pull request merged**
