### PR TITLE
magento/magento2#: Replace deprecated addError, addSuccess, addException methods in Magento/Customer/Controller/Account/CreatePost.php

### PR DESCRIPTION
**Pull request by atwixfirster**
### Description (*)

Pull request replaces deprecated `addError`, `addSuccess`, `addException` methods in `Magento/Customer/Controller/Account/CreatePost.php` of `Magento_Customer` module:

addError -> addErrorMessage
addSuccess -> addSuccessMessage
addException -> addExceptionMessage

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

Thank you!

### CODE REVIEW

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
@atwixfirster , could you please check the failed integration tests.
There is a difference in expected results due to escaped characters after using the new methods.

**Comment by atwixfirster** [comment]
> @atwixfirster , could you please check the failed integration tests.

**done**

@dmytro-ch, could you please review?

Thank you!

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5730](https://jira.corp.magento.com/browse/ENGCOM-5730) has been created to process this Pull Request
:eight_spoked_asterisk: @dmytro-ch, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Review by sidolov — CHANGES_REQUESTED** [review]
@atwixfirster looks like the simple implementation with just messages became a really complex, could you please clarify why we need to use additional templates for simple messages that can be inlined and used in `addSuccessMessage` method?

**Comment by atwixfirster** [comment]
> @atwixfirster looks like the simple implementation with just messages became a really complex, could you please clarify why we need to use additional templates for simple messages that can be inlined and used in `addSuccessMessage` method?

Hi, @sidolov !

I will try to explain on the following example.

**Preconditions:**
1. Go to `CUSTOMERS` > `Customer Configuration` > `Create New Account Options` on the back-end side
2. Set option `Require Emails Confirmation` = `Yes`

**Steps to reproduce:**
1. Register a new customer on FE side
2. With `addComplexSuccessMessage` you will get:




3. With `addSuccessMessage` output result will be a slightly different:



Thank you!

**Comment by atwixfirster** [comment]
> @atwixfirster looks like the simple implementation with just messages became a really complex,...

@sidolov , you can see the same implementations in the `Magento_Wishlist` module:

- https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Wishlist/etc/frontend/di.xml#L38
- https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Wishlist/Controller/Index/Add.php#L134

Thank you!

**Pull request merged**
