### PR TITLE
Fix count SQL on products sold collection

### PR DESCRIPTION
**Pull request by jameshalsall**

### CODE REVIEW

**Comment by avoelkl** [comment]
Hi @jameshalsall!
Thanks for the PR!
Actually I was trying to reproduce what your PR solves, can you tell me where/in which cases you had an issue?
It seems the Ordered Quantity works correctly?

**Comment by jameshalsall** [comment]
If you use `Magento\Reports\Model\ResourceModel\Product\Sold\Collection` to fetch the most sold products anywhere in user land code, it breaks on the count SQL as the table alias is incorrect.

Example code from my project:

```php
<?php

use Magento\Reports\Model\ResourceModel\Product\Sold\CollectionFactory as ProductsSoldCollectionFactory;

class MostPurchasedProductSkuProvider
{
    private $collectionFactory;
    private $storeManager;

    public function __construct(ProductsSoldCollectionFactory $productsSoldCollectionFactory)
    {
        $this->collectionFactory = $productsSoldCollectionFactory;
    }

    public function getSkus(int $limit, \DateTimeInterface $from, \DateTimeInterface $to): array
    {
        if ($limit < 1) {
            return [];
        }

        $collection = $this->collectionFactory->create();

        $collection->addOrderedQty($from->format('Y-m-d H:i:s'), $to->format('Y-m-d H:i:s'));
        $collection->setOrder('ordered_qty');
        $collection->setPageSize($limit);

        $collection->getSelect()->columns('order_items.sku');

        $skus = [];
        foreach ($collection as $item) {
            $skus[] = $item['sku'];
        }

        return $skus;
    }
}

**Comment by avoelkl** [comment]
Thanks for the update @jameshalsall!
Mind to add a test as well, like in `Magento\Reports\Test\Unit\Model\ResourceModel\Report\Quote\CollectionTest` for example? That would be supercool. Let me know if you need help.

**Comment by jameshalsall** [comment]
No problem. I'll add one later

**Comment by jameshalsall** [comment]
I've added a test to cover this functionality now.

**Comment by vrann** [comment]
@jameshalsall Thank you for the contribution!

**Pull request merged**
