### PR TITLE
[FEATURE] Added replace and saveMultiple to the CategoryLink function…

### PR DESCRIPTION
**Pull request by lewisvoncken**
…ality

### Description

This features makes it easier to assign multiple products through the API so there only needs te be done one API call instead of for every single product.

### Manual testing scenarios

1. Create several Products
2. Assign Multiple Products to a Category through a single API Request

New API endpoints:
image

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by larsroettig — CHANGES_REQUESTED** [review]
Hi @lewisvoncken, can change you the target branch to 2.3 because your change is not acceptable in 2.2 see:  https://devdocs.magento.com/guides/v2.2/extension-dev-guide/versioning/codebase-changes.html 
https://devdocs.magento.com/guides/v2.0/contributor-guide/backward-compatible-development/#introduction-of-a-method-to-a-class-or-interface

Also i would recommend more tests to cover the new Feature.

best regards, 

Lars

**Comment by lewisvoncken** [comment]
@larsroettig I have updated the cod according to the backward compatible article and created a new pull request for 2.3-develop https://github.com/magento/magento2/pull/15064

And I will try to add Unit Tests after it is approved for 2.3-develop

**Comment by lewisvoncken** [comment]
@larsroettig Did you had time to check the changes?

**Review by larsroettig — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @larsroettig, thank you for the review.
[ENGCOM-1562](https://jira.corp.magento.com/browse/ENGCOM-1562) has been created to process this Pull Request

**Comment by lewisvoncken** [comment]
@larsroettig why was this pull request closed after the update based on the backward compatible article?

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15027) <br/>All committers have signed the CLA.

**Comment by sidolov** [comment]
Hi @lewisvoncken , I'm closing this PR because original PR: https://github.com/magento/magento2/pull/15064 was closed due to inactivity.
Please, reopen it if you wish to continue.
Thank you!

**Pull request closed without merging**
