### PR TITLE
Fixed the customer rp token invalid issue.

### LINKED ISSUE #29663: [Issue] Fixed the customer rp token invalid issue.
This issue is automatically created based on existing pull request: magento/magento2#28704: Fixed the customer rp token invalid issue.

---------
Steps To reproduce :

Step 1 : Hit the api for getting the customer rp token.
Setp 2 : Use the rp token.
Step 3 : Again use that rp token for resetting password, in this case 500 server error is get instead of no such rp token.

Explanation. 

When the token got expired and it is hit through the api. Then since there is no throw statement it does not throw exception rather it goes down below to the line $found->getItems()[0] giving the null because there is no such token and the error has not been thrown, it is just created. Since this function returns the CustomerInterface due to type casting it is giving off the 500 internal server error "Fatal Error: 'Uncaught TypeError: Return value of Magento\Customer\Model\ForgotPasswordToken\GetCustomerByToken::execute() must implement interface Magento\Customer\Api\Data\CustomerInterface, null".

### PR DESCRIPTION
**Pull request by sagar2009kumar**
Steps To reproduce :

Step 1 : Hit the api for getting the customer rp token.
Setp 2 : Use the rp token.
Step 3 : Again use that rp token for resetting password, in this case 500 server error is get instead of no such rp token.

Explanation. 

When the token got expired and it is hit through the api. Then since there is no throw statement it does not throw exception rather it goes down below to the line $found->getItems()[0] giving the null because there is no such token and the error has not been thrown, it is just created. Since this function returns the CustomerInterface due to type casting it is giving off the 500 internal server error "Fatal Error: 'Uncaught TypeError: Return value of Magento\Customer\Model\ForgotPasswordToken\GetCustomerByToken::execute() must implement interface Magento\Customer\Api\Data\CustomerInterface, null".

### Resolved issues:
1. [x] resolves magento/magento2#29663: Fixed the customer rp token invalid issue.

### CODE REVIEW

**Comment by rogyar** [comment]
@magento run all tests

**Comment by sagar2009kumar** [comment]
@rogyar All the checks has been run by the magento and it was showing 14/14 checks successful. But then there was the option of update branch and i click that and then all the checks status has been changed to Expected (required). Do i need to do something from my side ? I have not contributed to magento before, so i don't know the process. Please guide me.

**Comment by rogyar** [comment]
@magento run all tests

**Comment by rogyar** [comment]
Hi @sagar2009kumar. Thank you for your collaboration. According to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered by automated tests. In this particular case I would recommend creating a unit test that will check if the exception is thrown if total tokens count is zero. Feel free to cover other cases of this class as well if you wish. 

Thank you!

**Comment by sagar2009kumar** [comment]
HI @rogyar , I will create the unit test for this class and let you know when done. Thanks for the guidance.

**Comment by sidolov** [comment]
@magento create issue

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8036](https://jira.corp.magento.com/browse/ENGCOM-8036) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@sagar2009kumar thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by rogyar — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
Hi @sagar2009kumar. Thank you for your contribution!

The problem has already been fixed by PR #27269 .
So, we have to close it.

Thanks!

**Pull request closed without merging**
