### PR TITLE
Removed translate=“true” from definition.map.xml fixes crowdin from showing those strings

### PR DESCRIPTION
**Pull request by paales**
Crowdin is showing all sorts of strings that shouldn't be translated:
https://crowdin.com/translate/magento-2/1374/enus-nl#q=settings%2F

If those strings are translated it will potentially cause problems.

### CODE REVIEW

**Comment by fooman** [comment]
thanks for this contribution @paales - the changes make sense to me but it has tripped a couple of existing tests on travis. Would you mind taking a look at fixing those as part of this pull request.

**Comment by paales** [comment]
Got no idea how to fix the Integration tests the errors are counterintuitive and don't know what to change to solve the issue. If someone else can fix the integration tests..

**Comment by okorshenko** [comment]
Hi @paales could you please look at `\Magento\Ui\Config\Argument\Parser\XpathType::parse`
`translate="true"` attribute only make sense for `type='string'`
`xsi:type="xpath"` means that we will read the value by xpath and translate the value, but not xpath itself. Please, let me know if there is an issue in this logic. Otherwise, we need to reject this PR.

**Comment by paales** [comment]
@okorshenko Alright that makes sense. I was creating the PR because in the past translations caused bugs because some strings were translated that shouldn't have been. In this case all those paths end up in crowdin.. They shoudn't be there..

**Comment by okorshenko** [comment]
@paales I'm closing this PR. Thank you for research

**Pull request closed without merging**
