### PR TITLE
magento/magento2#20032: Download links don't work when checking out a…

### PR DESCRIPTION
**Pull request by max-tkachuk**
…s guest.

Observer switched to other event.

### Description (*)
Download links don't work when checking out as guest,
even when Downloadable Product Options -> Order Item Status To Enable Downloads is set to pending

### Fixed Issues (if relevant)
 magento/magento2#20032: Download links don't work when checking out as guest

### Manual testing scenarios (*)
1. Make a downloadable product with shareable links
2. Set Admin -> Stores -> Configuration -> Catalog -> Downloadable Product Options -> Shareable to Yes
3. Set Admin -> Stores -> Configuration -> Catalog -> Downloadable Product Options -> Disable Guest Checkout if Cart Contains Downloadable Items to No.
4. Set Admin -> System -> Configuration -> Catalog -> Downloadable Product Options -> Order Item Status To Enable Downloads to 'Pending.'
5. Clear cache
6. Open a browser in incognito mode and add the downloadable product to your cart without logging in
7. Checkout as guest with a valid email address
8. Click on the link or links sent in the confirmation email

### Contribution checklist (*)
 - [*] Pull request has a meaningful description of its purpose
 - [*] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21971) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=21971) before we can accept your contribution.<br/>**7** out of **8** committers have signed the CLA.<br/><br/>:white_check_mark: magento-engcom-team<br/>:white_check_mark: ihor-sviziev<br/>:white_check_mark: novikor<br/>:white_check_mark: orlangur<br/>:white_check_mark: Nazar65<br/>:white_check_mark: nmalevanec<br/>:white_check_mark: sivaschenko<br/>:x: serhii-balko

**Comment by magento-engcom-team** [comment]
Hi @m-a-x-i-m. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by dmytro-ch** [comment]
Hi @m-a-x-i-m, 
thank you for your contribution!

Please [sign Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=21971), otherwise, we won't be able to process your pull request.

**Comment by cram412** [comment]
Hi @m-a-x-i-m 
I've also investigated this issue, it happens because Magento introduced separate file `Magento\Framework\Mail\Template\TransportBuilderByStore` and used it to add mail sender. But in the `Magento\Framework\Mail\Template\TransportBuilder` constructor creates two instances of the Message object what is wrong

Check this screenshot https://pasteboard.co/I7GfCCu.png

Another bug is that Magento ignores sender name
Everywhere in code i found this usage 
```
$this->message->setFrom($result['email'], $result['name']);
```
Actually `Magento\Framework\Mail\MessageInterface::setFrom()` appies only one parameter.  See method declaration
```
namespace Magento\Framework\Mail;

/**
 * Mail Message interface
 *
 * @api
 */
interface MessageInterface
{

    ...

    /**
     * Set from address
     *
     * @param string|array $fromAddress
     * @return $this
     */
    public function setFrom($fromAddress);
}
```

This can be fixed with passing this params as array `->setFrom([$result['email'] => $result['name']])`

Kinda regards,
Oleg Kraminsky
Magento developer

**Comment by sidolov** [comment]
Hi @m-a-x-i-m  looks like you made some commits with email different than in your GitHub profile, please, add email from commits to your profile!
Thank you!

**Comment by sidolov** [comment]
@m-a-x-i-m , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by max-tkachuk** [comment]
email added to profile

**Pull request closed without merging**
