### PR TITLE
Fixed #24400 Issues Found on Grid Multi-Select Column

### LINKED ISSUE #24400: Issues Found on Grid Multi-Select Column
### Preconditions (*)

1. Magento 2.3-develop and Magento 2.3.2
2.

### Steps to reproduce (*)

**Issue First:** 
1. Open any grid having some records.
2. Click on Header Checkbox to select all record on current page. https://prnt.sc/p09pr0
3. Now unselect some record, on click particular row: https://prnt.sc/p09pya
4. Again click on Header Checkbox, here is the issue.
5. Now you will see all records are unselected but header checkbox is selected. https://prnt.sc/p09qh6

**Issue Second**
1.  Now Select the per page record to 1 https://prnt.sc/p09rfr
2. And select all record on current page by clicking header checkbox. https://prnt.sc/p09rrj
3. Go to second page you will see that the header checkbox is selected on all remaining pages.
https://prnt.sc/p09s42 

### Expected result (*)

1. https://prnt.sc/p09qof
2.

### Actual result (*)

1. https://prnt.sc/p09qh6
2.

### PR DESCRIPTION
**Pull request by shikhamis11**
Fixed #24400 Issues Found on Grid Multi-Select Column

### Preconditions (*)

1. Magento 2.3-develop and Magento 2.3.2
2.

### Steps to reproduce (*)

**Issue First:** 
1. Open any grid having some records.
2. Click on Header Checkbox to select all record on current page. https://prnt.sc/p09pr0
3. Now unselect some record, on click particular row: https://prnt.sc/p09pya
4. Again click on Header Checkbox, here is the issue.
5. Now you will see all records are unselected but header checkbox is selected. https://prnt.sc/p09qh6

**Issue Second**
1.  Now Select the per page record to 1 https://prnt.sc/p09rfr
2. And select all record on current page by clicking header checkbox. https://prnt.sc/p09rrj
3. Go to second page you will see that the header checkbox is selected on all remaining pages.
https://prnt.sc/p09s42 

### Expected result (*)

1. https://prnt.sc/p09qof
2.

### Actual result (*)

1. https://prnt.sc/p09qh6
2.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by novikor** [comment]
@shikhamis11, thank you for your contribution.
Please fix the static tests

**Review by novikor — CHANGES_REQUESTED** [review]
```
disallowTrailingWhitespace: Illegal trailing whitespace at app/code/Magento/Ui/view/base/web/js/grid/columns/multiselect.js :
   236 |        */
   237 |        togglePage: function () {
   238 |            return this.isPageSelected() && !this.excluded().length 
---------------------------------------------------------------------------^
   239 |                ? this.deselectPage() : this.selectPage();
   240 |        },


requireOperatorBeforeLineBreak: Operator ? should not be on a new line at app/code/Magento/Ui/view/base/web/js/grid/columns/multiselect.js :
   236 |        */
   237 |        togglePage: function () {
   238 |            return this.isPageSelected() && !this.excluded().length 
---------------------------------------------------------------------------^
   239 |                ? this.deselectPage() : this.selectPage();
   240 |        },
```

**Comment by novikor** [comment]
@magento run Functional Tests B2B

**Review by novikor — APPROVED** [review]
Good job! Thank you for your contribution.

**Comment by magento-engcom-team** [comment]
Hi @novikor, thank you for the review.
[ENGCOM-6841](https://jira.corp.magento.com/browse/ENGCOM-6841) has been created to process this Pull Request
:eight_spoked_asterisk: @novikor, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
HI @shikhamis11 , seems like there is still issue with header checkbox
#26626PR


Could you take a look?

**Comment by shikhamis11** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [new Magento instance](https://pr-26626.instances.magento-community.engineering).
Admin access: [https://pr-26626.instances.magento-community.engineering/admin_e772](https://pr-26626.instances.magento-community.engineering/admin_e772)
Login: `2bf4bdef` Password: `bfe103d4e9ac`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
thanks for the update @engcom-Delta 
I will check it further
It seems this issue reproduced in 2.4-dev instance recently .. I checked fix is working fine at 2.3.3 and 2.4 instances

**Comment by shikhamis11** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [new Magento instance](https://pr-26626.instances.magento-community.engineering).
Admin access: [https://pr-26626.instances.magento-community.engineering/admin_04a4](https://pr-26626.instances.magento-community.engineering/admin_04a4)
Login: `ba885a7a` Password: `44bd7427c53e`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
Hi @engcom-Delta & @novikor 
I installed 2.4-develop instance at my local and checked the issue .. 
there I am not able to reproduce this error there fix seems to be working fine .. can you please check at your end too ?

**Comment by engcom-Delta** [comment]
Hi @shikhamis11 I rechecked and this [issue](https://github.com/magento/magento2/pull/26626#issuecomment-584097940) is also present on 2.4-develop and seems like not related to PR.
So results are next:

- I cannot reproduce **Issue First** scenario on 2.4-develop:

#26626PRCase1


- **Issue Second** scenario is reproducible on 2.4-develop but it is not fixed by PR

#26626PRCase2


Is there any additional steps that I missed?

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [Magento instance](https://i-26626-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26626-2-4-develop.instances.magento-community.engineering/admin_f080](https://i-26626-2-4-develop.instances.magento-community.engineering/admin_f080)
Login: `ab66e3c2` Password: `90a0f683f78c`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment]
hi @engcom-Delta 
I am confused with the random behaviour at instances .. yesterday only I cloned 2.4-develop instance at my local and there the previous issue was present 


screencast-demo cedcommerce com-2020 02 13-18_16_00

**Comment by engcom-Kilo** [comment]
Will add MFTF test

**Comment by engcom-Kilo** [comment]
@shikhamis11 Added MFTF Test

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
Hi @shikhamis11 , I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
