### PR TITLE
magento/magento2#: GraphQl. RevokeCustomerToken. Test coverage.

### PR DESCRIPTION
**Pull request by atwixfirster**
### Description (*)

Pull request adds a unit test for `\Magento\CustomerGraphQl\Model\Resolver\RevokeCustomerToken` class.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

Thank you!

### CODE REVIEW

**Review by dmytro-ch — APPROVED** [review]

**Comment by engcom-Delta** [comment]
**Notice:** QA not applicable

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6637](https://jira.corp.magento.com/browse/ENGCOM-6637) has been created to process this Pull Request

**Comment by lenaorobei** [comment]
This mutation is already covered by `\Magento\GraphQl\Customer\RevokeCustomerTokenTest`. If some cases are not covered please consider adding it to the `api-functional` test. 
Thanks.

**Comment by atwixfirster** [comment]
> This mutation is already covered by \Magento\GraphQl\Customer\RevokeCustomerTokenTest

@lenaorobei , could you please clarify. For which GraphQl modules **unit tests** are applicable?

Thank you!

**Comment by dmytro-ch** [comment]
@atwixfirster I guess, @lenaorobei meant that the unit tests are useless for GraphQl in general. It's better to add an API-functional test if you wish to cover some logic. :)
Thank you!

**Comment by atwixfirster** [comment]
> @atwixfirster I guess, @lenaorobei meant that the unit tests are useless for GraphQl in general. It's better to add an API-functional test if you wish to cover some logic. :)
> Thank you!

Thank you, @dmytro-ch , for the explanation. 

However, I would like to know an official Magento position about Unit Tests. Because some GraphQl modules already covered by Unit and API-functional tests. 

For example, `Magento\WishlistGraphQl\Model\Resolver\CustomerWishlistResolver` covered by 
- [Magento\WishlistGraphQl\Test\Unit\CustomerWishlistResolverTest](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/WishlistGraphQl/Test/Unit/CustomerWishlistResolverTest.php)(Unit Test)
- [Magento\GraphQl\Wishlist\WishlistTest](https://github.com/magento/magento2/blob/2.3.3/dev/tests/api-functional/testsuite/Magento/GraphQl/Wishlist/WishlistTest.php) (API-functional test)

So, I want to understand why Unit tests are good for some GraphQl classes and what is the difference between `\Magento\WishlistGraphQl\Test\Unit\CustomerWishlistResolverTest` and my one - `\Magento\CustomerGraphQl\Model\Resolver\RevokeCustomerToken`. 

Also good to know for which GraphQl classes we can create Unit Tests.

@lenaorobei , could you please clarify?

Thank you so much!

**Comment by lenaorobei** [comment]
Hi @atwixfirster,

Yes, @dmytro-ch is correct about the value of unit tests. They make sense only in the development phase. 

I left the same comment in PRs with unit tests you've mentioned https://github.com/magento/magento2/pull/26125#issuecomment-567551302 and asked @lbajsarowicz to not contribute more in this.

> Also good to know for which GraphQl classes we can create Unit Tests.

There are no such classes. Positive and negative scenarios for queries and mutations should be covered with API functional tests. For more information please refer to the [Magento definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html).

**Comment by atwixfirster** [comment]
Understood

Thank you very much, @lenaorobei !

**Pull request merged**
