### PR TITLE
Added company & vat id fields value to shipping & billing address renderers

### LINKED ISSUE #31252: [Issue] Added company & vat id fields value to shipping & billing address renderers
This issue is automatically created based on existing pull request: magento/magento2#28998: Added company & vat id fields value to shipping & billing address renderers

---------

### Description (*)

The company name & Vat ID were not being shown on address blocks on checkout. These blocks are

1. "Ship To" section in the summary sidebar on the checkout page 
2. "Billing Address" section under "Review & payments" step
3. "Address List" of a logged-in customer under "Shipping" step on the checkout

### Related Pull Requests

None

### Fixed Issues (if relevant)

None

### Manual testing scenarios (*)

1. Add any product to cart and go to the checkout
2. Fill shipping address details including the company name & Vat ID
3. Notice address in the "Ship To" section, the company name & Vat ID will be displayed with this pull request changes.

### Questions or comments

None

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by rav-redchamps**
### Description (*)

The company name & Vat ID were not being shown on address blocks on checkout. These blocks are

1. "Ship To" section in the summary sidebar on the checkout page 
2. "Billing Address" section under "Review & payments" step
3. "Address List" of a logged-in customer under "Shipping" step on the checkout

### Related Pull Requests

None

### Fixed Issues (if relevant)

None

### Manual testing scenarios (*)

1. Add any product to cart and go to the checkout
2. Fill shipping address details including the company name & Vat ID
3. Notice address in the "Ship To" section, the company name & Vat ID will be displayed with this pull request changes.

### Questions or comments

None

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31252: Added company & vat id fields value to shipping & billing address renderers

### CODE REVIEW

**Comment by rav-redchamps** [comment]
@magento run Unit Tests

**Comment by rav-redchamps** [comment]
@magento run all tests

**Comment by rav-redchamps** [comment]
The error in "Functional Tests B2B" doesn't seem to be related to the changes on the pull request.

**Comment by hostep** [comment]
Nice!

We should probably also do the same for the `vatId` field on those addresses, no?

**Comment by rav-redchamps** [comment]
Yes, definitely. But what should be its position? Like company name displays after customer's name

**Comment by hostep** [comment]
Underneath the company name or next to it?

**Comment by rav-redchamps** [comment]
> Underneath the company name or next to it?

Done ✅ Added underneath the company name

**Comment by orlangur** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento create issue

**Comment by hostep** [comment]
This can probably be closed now that https://github.com/magento/magento2/pull/31425 is almost finished, no?

**Comment by eduard13** [comment]
Thank you @rav-redchamps for contributing but I'm closing this PR in favour of #31425.

Thanks.

**Pull request closed without merging**
