### PR TITLE
Minicart Qty update button not aligned proper #25081 fixed

### LINKED ISSUE #25081: Minicart Qty update button not aligned proper
Minicart Qty update button not aligned proper

### Preconditions (*)
1. php 7.2 
2. Magento 2.3.x

### Steps to reproduce (*)
1. Open Frontend 
2. Add any product in cart 
3. Make screen mobile view 
4. Now click on mini cart and update quantity (Like: from 1 to 2) update button will see there now
compare with screenshot 

### Expected result (*)
image

### Actual result (*)
image

### PR DESCRIPTION
**Pull request by cedarvinda**
Fixed #25081  Minicart Qty update button not aligned proper
Preconditions (*)

    php 7.2
    Magento 2.3.x

Steps to reproduce (*)

1. Open Frontend
2. Add any product in cart
3.  Make screen mobile view
4.  Now click on mini cart and update quantity (Like: from 1 to 2) update button will see there now
    compare with screenshot

### Expected result (*)
image

### Actual result (*)
image

### CODE REVIEW

**Comment by XxXgeoXxX** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX, here is your [new Magento instance](https://pr-25082.instances.magento-community.engineering).
Admin access: [https://pr-25082.instances.magento-community.engineering/admin](https://pr-25082.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by XxXgeoXxX — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX, thank you for the review.
[ENGCOM-6107](https://jira.corp.magento.com/browse/ENGCOM-6107) has been created to process this Pull Request
:eight_spoked_asterisk: @XxXgeoXxX, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @cedarvinda 

During testing, we faced the issue.
The "Update" button should not cover the action buttons.

**Actual Result:**
after2

@cedarvinda Could you take a look?

Thanks!

**Comment by cedarvinda** [comment]
> 
> 
> Hi @cedarvinda
> 
> During testing, we faced the issue.
> The "Update" button should not cover the action buttons.
> 
> **Actual Result:**
> after2
> 
> @cedarvinda Could you take a look?
> 
> Thanks!

Yes sure ...I am looking in to this and updating.

**Comment by cedarvinda** [comment]
> 
> 
> > Hi @cedarvinda
> > During testing, we faced the issue.
> > The "Update" button should not cover the action buttons.
> > **Actual Result:**
> > after2
> > @cedarvinda Could you take a look?
> > Thanks!
> 
> Yes sure ...I am looking in to this and updating.

@engcom-Alfa I have updated the issue now it looking like this (screenshot)
image

**Comment by dmytro-ch** [comment]
Please note, the issue has already been fixed by #25206 
Thank you!

**Comment by cedarvinda** [comment]
> 
> 
> Please note, the issue has already been fixed by #25206
> Thank you!

@dmytro-ch I think My first PR was fine because any customer has set his/her mind to update cart quantity then why he need to see these action button (edit and delete) User experience ? After that update or before the update action link already visible in single line.

**Comment by VladimirZaets** [comment]
Hi @cedarvinda. Sorry, but otherwise, this issue is already fixed and no sense merges your PR, according to it I closed this PR. 

If you have any concerns feel free to reopen and discuss it

**Comment by cedarvinda** [comment]
> 
> 
> Hi @cedarvinda. Sorry, but otherwise, this issue is already fixed and no sense merges your PR, according to it I closed this PR.
> 
> If you have any concerns feel free to reopen and discuss it

@VladimirZaets No problem to close PR if already fixed, but if customer has set his/her mind to update cart quantity then why he need to see these action button (edit and delete) User experience ?

**Pull request closed without merging**
