### PR TITLE
Fix bulk action log clean error on admin dashboard

### LINKED ISSUE #36255: "Something went wrong" error is displayed when clearing the completed bulk tasks.
**Issue:**
"Something went wrong" error is displayed when clearing the completed bulk tasks.

 

**Steps to reproduce:**
* Perform a bulk operation (eg: Bulk update product attributes).
* Make the operation completed (eg: run {{{}bin/magento queue:consumer:start product*action*attribute.update{}}})
* Click on the "Dismiss All Completed Tasks" link after expanding the admin notification section.

**Actual result:**
"Something went wrong" error is displayed

**Expected result:**
The "Something went wrong" error should not be displayed while clearing the completed tasks.

**Additional information:**
* Completed tasks are getting cleared regardless of the error message. This can be checked by refreshing the page or navigating to a different page in the admin.

### PR DESCRIPTION
**Pull request by texboy**
### Description (*)

This pull request fixes the error that happens when the admin user clicks the "Dismiss All Completed Tasks", preventing the tasks notice from being cleaned.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36255

### Manual testing scenarios (*)

Steps to reproduce:

1. Log as an admin user.
2. Perform a Bulk update product attributes: 
  a. Catalog -> Products -> Select a N number of prodcuts and select the "Update Attributes" action. Update any number of attributes and submit the action.
3. Make the operation completed (eg: run `bin/magento queue:consumer:start product_action_attribute.update`)
4. Go back to the dashboard and click on the "Dismiss All Completed Tasks" link after expanding the admin notification section.
image
5. The messages should be cleared successfully with no error messages or popups.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by texboy** [comment]
https://github.com/magento run all tests

**Comment by texboy** [comment]
@magento run all tests

**Comment by veloraven** [comment]
@texboy thank you for picking up this issue.
Please be aware that the fix should follow Definition of Done:
https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/

Currently you have some builds failing.
Some of them looks like random fails and should go away after you re-run them:
* Functional Tests B2B
* Integration Tests
* WebAPI Tests
But two builds fail because of your fix:
* Static Tests
* Unit Tests

You need to make some updates in the code to fix it. As having all green builds is a part of DoD as well as fix covered with the test. 
As we already have a unit test for this code, you need update it. The file is _DismissTest.php_ Currently it fails because mock in the test knows nothing about 'setData' method you are adding.
And to fix static tests you need to update _Dismiss.php_ file:
* remove curled braces on line 46 
* add 'implements HttpPostActionInterface' on line 16
* add 'use Magento\Framework\App\Action\HttpPostActionInterface;' so that previous update works.

You can easily find all this in builds reports.

**Comment by veloraven** [comment]
@texboy Are there any updates on this issue?

**Comment by veloraven** [comment]
Hello @texboy !

Thank you for your contribution and collaboration!

To speed up the delivery process of this fix, the internal Adobe team will take this fix in progress, complete all other work according to the Definition of Done and deliver the fix using internal workflow.

The fix for this issue will be done in the scope of the internal Jira ticket ACP2E-1245.

**Comment by hostep** [comment]
Looks like some commits got added referencing [ACP2E-1245](https://github.com/magento/magento2/search?q=ACP2E-1245&type=commits), so this issue can probably be closed now?

**Comment by ishakhsuvarov** [comment]
@veloraven Please confirm if this PR can be closed or not. I would expect it to be closed automatically if process would have been executred correctly though.

**Comment by andrewbess** [comment]
This PR already merged and shouldn't have pending review status

**Pull request merged**
