### PR TITLE
magento/magento2#20906: Magento backend catalog "Cost" without curren…

### PR DESCRIPTION
**Pull request by jtomka**
…cy symbol

### Fixed Issues (if relevant)

1. magento/magento2#20906: Magento backend catalog "Cost" without currency symbol
2. magento/magento2#20472: Special Price shown without currency symbol in magento backoffice

### Manual testing scenarios (*)

Use original steps from the issues.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21122) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @jtomka. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by jtomka** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @jtomka. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @jtomka, here is your [new Magento instance](https://pr-21122.instances.magento-community.engineering).
Admin access: [https://pr-21122.instances.magento-community.engineering/admin](https://pr-21122.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by orlangur — CHANGES_REQUESTED** [review]
@jtomka columns must not be added to grid.

**Comment by jtomka** [comment]
> @jtomka columns must not be added to grid.

I believe this was fixed and pulled upstream from https://github.com/magento/magento2/pull/20907

It looks like columns were added to the grid in that one, too.

**Comment by orlangur** [comment]
Thanks @jtomka! This is incorrect, I left a comment. Please elaborate a proper fix.

**Comment by orlangur** [comment]
Another example is https://github.com/magento/magento2/pull/21911.

**Comment by sidolov** [comment]
@jtomka , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by rohitkundale** [comment]
i am working on this at #dmcdindia19

**Pull request closed without merging**
