### PR TITLE
Table name fix - rule_customer to salesrule_customer

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
This is the fix for #5205

### CODE REVIEW

**Comment by NadiyaS** [comment]
Hi @Bartlomiejsz ,
thank you for your contribution. Internal ticket MAGETWO-54781 was created to process your PR

**Comment by Bartlomiejsz** [comment]
@vkorotun @NadiyaS any feedback? This pr was created over 4 months ago and it is only one line fix.

**Comment by Ctucker9233** [comment]
@vkorotun @NadiyaS Seconding @Bartlomiejsz. Any plans to merge this soon?

**Comment by ishakhsuvarov** [comment]
@Bartlomiejsz @Ctucker9233 PR has now been merged.
Thank you for contribution!

**Pull request merged**
