### PR TITLE
[Catalog] [MediaStorage] Fix watermark in media application

### PR DESCRIPTION
**Pull request by progreg**
### Description (*)
While media request Magento doesn't process watermarks. Also while `catalog:images:resize` watermarks are not processing for base catalog images. Watermark process was added in resize image function to fix media get request and console catalog images resize process.

### Fixed Issues (if relevant)

1. magento/magento2#21154: 2.3.0 Watermark not showing on images

### Manual testing scenarios (*)

* Create categories
* Create products
* Upload a watermark
* Set image opacity to 10, image size to 40x50, image position to tile, and saved configuration.
* Tap the Cache Management link in the system message. Then, refresh the invalid cache & catalog media cache

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @progreg. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by progreg** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @progreg. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @progreg, here is your [Magento instance](https://i-21338-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21338-2-3-develop.instances.magento-community.engineering/admin](https://i-21338-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by josefbehr — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @josefbehr, thank you for the review.
[ENGCOM-4378](https://jira.corp.magento.com/browse/ENGCOM-4378) has been created to process this Pull Request

**Pull request merged**
