### PR TITLE
products-in-category-checkbox-not-align-properly

### PR DESCRIPTION
**Pull request by priti2jcommerce**
### Fixed Issues (if relevant)

1. magento/magento2#21021
2. ...

### Manual testing scenarios (*)

1. Go to admin >> Catalog >> Categories
2. Select any category having product

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-21022.instances.magento-community.engineering).
Admin access: [https://pr-21022.instances.magento-community.engineering/admin](https://pr-21022.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by dmytro-ch** [comment]
Hi @priti2jcommerce,
thank you for your contribution!

It does not seem to be a bug.
screen shot 2019-02-06 at 3 30 21 pm

As for me, it even look better before aupplying the fixes.
Thank you.

**Comment by priti2jcommerce** [comment]
* @magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce, here is your [Magento instance](https://i-21022-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21022-2-3-develop.instances.magento-community.engineering/admin](https://i-21022-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by priti2jcommerce** [comment]
@dmytro-ch 
I have checked and found the bug on the testing instance and you have checked on pr instance with fixes,thats why it look proper.
image

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-21022.instances.magento-community.engineering).
Admin access: [https://pr-21022.instances.magento-community.engineering/admin](https://pr-21022.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by dmytro-ch** [comment]
Hi @priti2jcommerce,
sure I know that there is the current solution on my screenshot.
I just wanted to mention that it still looks strange a little bit, event after the fixes.
Nevertheless, it's a matter of taste. :)

Could you please check the issue appeared after the latest changes.
The following areas are not clickable:
screen shot 2019-02-07 at 8 43 02 am

It should be possible to select the item by clicking the row.
Looks like there was same not clickable area previously, but it was not so large.
screen shot 2019-02-07 at 8 42 16 am

Thank you!

**Comment by priti2jcommerce** [comment]
Hi @dmytro-ch ,

Thanks for the update, made the changes for this.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4174](https://jira.corp.magento.com/browse/ENGCOM-4174) has been created to process this Pull Request

**Pull request merged**
