### PR TITLE
Fix issue thumbnail image too big in order summary checkout

### LINKED ISSUE #28634: Thumbnail product image in checkout page order summary too big
### Preconditions (*)

1. 2.4.0
2. sample data installed

### Steps to reproduce (*)

1. Add product to cart
2. Go to checkout page

### Expected result (*)

1. [Screenshots, logs or description]
2. Image size idealy will be 75x75

### Actual result (*)

1. [Screenshots, logs or description]
2. Image size 150x150

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

This fix bring the fix for image thumbnail in order summary area in checkout page
Previous image too big visible
#1 Recheck styles visual for all (mobile | ipad | desktop) view
since this review https://github.com/magento/magento2/pull/20856#pullrequestreview-198771046 from @VladimirZaets 

### Related Pull Requests

https://github.com/magento/magento2/pull/20856
### Fixed Issues (if relevant)

1. Fixes magento/magento2#28634

### Manual testing scenarios (*)

1.Add any product type to cart
2.Go to checkout page
3.Open area order summary

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sdzhepa** [comment]
Hello @mrtuvn 

Thank you for the fix!
Please review the comment https://github.com/magento/magento2/issues/28634#issuecomment-642338036 and update your PR(I see you have fixed 2 issues)

**Comment by mrtuvn** [comment]
@sdzhepa reverted my change so this PR will not conflict with changes in https://github.com/magento/magento2/pull/28546
Only add new clean code in styles

**Comment by mrtuvn** [comment]
@VladimirZaets can you recheck review

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
Hi @mrtuvn. Thanks for collaboration. I reran the build but due to changes only in styles I can approve it right now

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7670](https://jira.corp.magento.com/browse/ENGCOM-7670) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
Hi any update on this

**Review by engcom-Delta — CHANGES_REQUESTED** [review]
@VladimirZaets  Could you review last commit?

**Comment by mrtuvn** [comment]
@engcom-Delta is this commit cherry pick or merge to 2.4-develop ?
https://github.com/magento/magento2/pull/28644#issuecomment-642338655

**Review by VladimirZaets — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7670](https://jira.corp.magento.com/browse/ENGCOM-7670) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by mrtuvn** [comment]
Nice We got pick commit  #28546 https://github.com/magento/magento2/blob/2.4.0/app/code/Magento/Checkout/view/frontend/web/template/summary/item/details/thumbnail.html
in latest code
@engcom-Delta

**Comment by mrtuvn** [comment]
@magento run all tests

**Review by engcom-Delta — CHANGES_REQUESTED** [review]
Hi @mrtuvn I have checked PR with latest [commit](https://github.com/mrtuvn/magento2/commit/80d0157a80179d33a06bd81715531b969d3f4f46) and issue still exist 
**Tablet view:**
image
**Destop view:**
image
image

Could you take a look?

**Comment by mrtuvn** [comment]
@engcom-Delta here is my screen in local setup with latest commit show summary area 
Screenshot from 2020-07-30 17-04-32

**Comment by mrtuvn** [comment]
Here is desktop view 
Screenshot from 2020-07-30 17-07-13

**Comment by mrtuvn** [comment]
@engcom-Delta just synced my PR branch with 2.4-develop code

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
Hi @mrtuvn. Thanks for collaboration. The issue is closed due that it was fixed by internal team in the scope of 2.4.0 release. The details and screenshots you can see in the issue. Feel free to reopen your PR if the issue is still reproducible

**Pull request closed without merging**
