### PR TITLE
Add INT types in some WHERE IN (?) expressions

### LINKED ISSUE #31135: [Issue] Add INT types in some WHERE IN (?) expressions
This issue is automatically created based on existing pull request: magento/magento2#31098: Add INT types in some WHERE IN (?) expressions

---------

### Description (*)

Numeric values in the WHERE IN expressions should be cast as number, not as string.
It improves queries time on same MariaDB versions
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ilnytskyi**
### Description (*)

Numeric values in the WHERE IN expressions should be cast as number, not as string.
It improves queries time on same MariaDB versions
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31135: Add INT types in some WHERE IN (?) expressions

### CODE REVIEW

**Comment by ilnytskyi** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
just curious Is this missing part happen in other modules ? Not only in catalog like your patch

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @ilnytskyi,
Could you fix failing unit tests?

**Comment by ilnytskyi** [comment]
@ihor-sviziev yes

**Comment by ilnytskyi** [comment]
@magento run Unit Tests

**Comment by ilnytskyi** [comment]
@magento run Unit Tests

**Comment by sidolov** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
@magento run Unit Tests

**Comment by ihor-sviziev** [comment]
@magento run all test

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Unit Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8510](https://jira.corp.magento.com/browse/ENGCOM-8510) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
QA not applicable. Moving the PR to the _Extended Testing_ column

**Pull request merged**
