### PR TITLE
magento/partners-magento2b2b#325: Automate Currency availability test for Company Credit

### PR DESCRIPTION
**Pull request by sagar1dahiwala**
### Description (*)

- Added data fixture and its rollback for base currency of second website
- This is required to Automate MC-27116

### Related Pull Requests

https://github.com/magento/partners-magento2b2b/pull/420

### Fixed Issues (if relevant)

1. Fixes magento/partners-magento2b2b#325

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @sagar1dahiwala. Good job. Could you double-check, please, that the rates added via the fixture are being removed after the rollback? Thanks.

**Comment by rogyar** [comment]
@magento run Integration Tests

**Comment by sagar1dahiwala** [comment]
Hi, @rogyar Thanks for pointing out. Seems like it's not being rollback. Let me update it.

**Comment by sagar1dahiwala** [comment]
Hi, @rogyar After closely look I think that rates are additional for that fixture at this point so I removed it from the fixture it self. Instead of removing it from the rollback. Let me know if you find something. Thanks.

**Comment by sagar1dahiwala** [comment]
@magento run Integration Tests

**Review by rogyar — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8327](https://jira.corp.magento.com/browse/ENGCOM-8327) has been created to process this Pull Request

**Review by danmooney2 — DISMISSED** [review]

**Review by rogyar — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8327](https://jira.corp.magento.com/browse/ENGCOM-8327) has been created to process this Pull Request

**Comment by danmooney2** [comment]
@magento run Static Tests, Integration Tests

**Comment by danmooney2** [comment]
@magento run Static Tests, Integration Tests

**Review by rogyar — APPROVED** [review]

**Comment by danmooney2** [comment]
Thanks just waiting on the B2B PR

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8327](https://jira.corp.magento.com/browse/ENGCOM-8327) has been created to process this Pull Request

**Review by joanhe — APPROVED** [review]

**Pull request merged**
