### PR TITLE
Item should be updated if there is a buyRequest

### LINKED ISSUE #35907: Webapi: Configurable product can not be updated
### Preconditions and environment

Magento version `>= 2.4.4-p1`

### Steps to reproduce

1. Create a Configurable Product with 2 simples (configurations), called option A and B. 
2. Create a Cart containing the Configurable Product using option A
3. Update the Cart Item to use option B using the REST API without updating the quantity (`PUT guest-carts/{cartId}/items/{itemId}`) *
4. The Cart Item is still using option A

_* Example PUT content_
```
{
   "cartItem":{
      "quote_id":1,
      "qty":1,
      "product_option":{
         "extension_attributes":{
            "configurable_item_options":[
               {
                  "option_id":"1",
                  "option_value":"2"
               }
            ]
         }
      }
   }
}
```

### Expected result

The cart item is being updated

### Actual result

The cart item is unaffected

### Additional information

**Cause**
The BuyRequest is being filtered on updated quantity, see commit:
https://github.com/magento/magento2/commit/5478c03cfe34030ad377594c7e6398836d304477

**Suggested fix**
Rollback this commit, the original issue should be fixed some other way.

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by pmzandbergen**
Fixes #35907

### CODE REVIEW

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Functional Tests EE

**Comment by Den4ik** [comment]
@magento run Functional Tests EE

**Review by Den4ik — APPROVED** [review]
@pmzandbergen Thanks for your contribution.
✅ Approved. I'm agree that ACP2E-74 should be fixed in different way

**Comment by Den4ik** [comment]
@magento run Functional Tests EE

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
Install fresh Magento.

**Manual testing scenario:**
1.Create admin token using endpoint: `/rest/default/V1/integration/admin/token/`
Payload
```
{
"username": "admin",
"password": "admin@123"
}
```
Using admin token you can use in header as bearer token.

2. Create a empty cart(post) in rest api endpoint: `/index.php/rest/V1/guest-carts/`
It will give you cart id in response

3. Using post method add product to cart(configurable product): `/rest/V1/guest-carts/{cartid}/items
Payload
```
{
"cartItem": {
"sku": "config_test",
"qty": 1,
"quote_id": "21",(take from DB)
"product_option": {
"extension_attributes": {
"configurable_item_options": [
{
"option_id": "93",
"option_value": 4
}
]
}
},
"extension_attributes": {}
}
}

```
In response you will get item id
4. Using put method update cart `/rest/V1/guest-carts/RutltjLiQzylAEu8L1jsHBI7YS58qWp7/items/{itemid}`

```
{
"cartItem": {
"sku": "config_test",
"qty": 1,
"quote_id": "21",
"product_option": {
"extension_attributes": {
"configurable_item_options": [
{
"option_id": "93",
"option_value": 5
}
]
}
},
"extension_attributes": {}
}
}

```
**Before:** :heavy_multiplication_x: Cart was not getting updated
Screenshot from 2022-08-26 14-21-58

**After:** :heavy_check_mark:  Cart items got updated.
Screenshot from 2022-08-26 15-28-29

Hence, moving it to MIP

Thanks

**Comment by Den4ik** [comment]
@pmzandbergen Could you please resolve merge conflict

**Comment by pmzandbergen** [comment]
@Den4ik it seems @mahesh-singh-rajawat fixed it with AC-5986:
https://github.com/magento/magento2/commit/eb02e7a4715169bc24261159da9bb0573fdb0ab2

I guess we could close this PR.

**Comment by Den4ik** [comment]
@pmzandbergen Yep, it's already fixed. Thanks for your work

**Pull request closed without merging**
