### PR TITLE
Bug/git 39159 fedex rates diff

### LINKED ISSUE #39159: Magento 2 new FedEx api not getting the right price
### Preconditions and environment

- Magento version: 2.4.7-p2
- FedEx negotiated rates

### Steps to reproduce

1. Navigate to store as guest
2. Place order
3. Get FedEx Shipping rates

### Expected result

Get our special deal prices

### Actual result

Get "normal price

### Additional information

Hello,

I just upgraded to 2.4.7-p2 to get the new FedEx api working.

Connection works fine but I'm not getting the right prices for our account.

FedEx tells us that we have a wrong param in the request :
`"rateRequestType": [
    "LIST"
],`
Should be
`"rateRequestType": [
    "PREFERRED"
],`

I could not see this option in admin.
Should it not figure there?

I tried to change this directly in vendor/magento/module-fedex/Model/Carrier.php and it seems to do the job.
But I also tried to override the Model to avoid update issues without luck.

Any idea on how I could get this fixed please?

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Mohamed-Asar**
### Description (*)
Fedex Rest api response return list rates instead of customer rates

### Fixed Issues (if relevant)

1. Fixes magento/magento2#39159

### Manual testing scenarios (*)

1. Configure REST API for fedex
2. Navigate to checkout page
3. Compare the REST API shipping rates against the SOAP Method response for the same address and product.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Mohamed-Asar** [comment]
@magento run all tests

**Comment by Mohamed-Asar** [comment]
As mentioned on this [comment](https://github.com/magento/magento2/issues/39159#issuecomment-2488428737), There is no need to pass **LIST** Type

**Comment by engcom-Hotel** [comment]
Hello @Mohamed-Asar,
Thanks for the contribution.

However, as per this [comment](https://github.com/magento/magento2/issues/39159#issuecomment-2490037168), the issue seems to have been resolved. Hence, we are closing this PR.

Thanks Again

**Comment by Mohamed-Asar** [comment]
Hi @engcom-Hotel can you check the above [comment](https://github.com/magento/magento2/pull/39234#issuecomment-2495363864), There is no need to pass LIST Type, That's why i kept this PR as open.

**Comment by engcom-Hotel** [comment]
Yes @Mohamed-Asar, but we have closed this issue according to its attached [issue](https://github.com/magento/magento2/issues/39159#issuecomment-2490037168). The related commit is also mentioned there.

Please let us know if we need to recheck the issue in any other way.

thanks

**Comment by Mohamed-Asar** [comment]
@engcom-Hotel Yes, the issue is resolved. However, passing the LIST type still includes its rates in the response. These rates are unnecessary and should not be included if we are only using the ACCOUNT rates.

**Pull request closed without merging**
