### PR TITLE
Fix issues with Customer Data when form contains element with name `method`

### LINKED ISSUE #38484: [Issue] Fix issues with Customer Data when form contains element with name `method`
This issue is automatically created based on existing pull request: magento/magento2#38449: Fix issues with Customer Data when form contains element with name `method`

---------
### Description (*)

The path to verify `<form method="">` value in `customer-data.js` (`Magento_Customer`) is glitchy and when there's an element with `name="method"` in the submitted form, the `event.target.method` refers to element, not attribute.

image

### Fixed Issues (if relevant)

Please create one.

### Manual testing scenarios (*)
1. Open any form (e.g. Customer Registration form),
2. Open Browser console and replace `name=""` of any element (e.g. "Remember me") to `name="method"`.
3. Set breakpoint at `customer-data.min.js` line after `$(document).on('submit', function(event) {`. 
4. Expect that `if ()` section (1 line below) uses `<form method="">`  - not just created element.

### Questions or comments

We noticed the issue while troubleshooting Paradoxlabs Firstdata extension issues.

image

CC @rhoerr 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)

The path to verify `<form method="">` value in `customer-data.js` (`Magento_Customer`) is glitchy and when there's an element with `name="method"` in the submitted form, the `event.target.method` refers to element, not attribute.

image

### Fixed Issues (if relevant)

Please create one.

### Manual testing scenarios (*)
1. Open any form (e.g. Customer Registration form),
2. Open Browser console and replace `name=""` of any element (e.g. "Remember me") to `name="method"`.
3. Set breakpoint at `customer-data.min.js` line after `$(document).on('submit', function(event) {`. 
4. Expect that `if ()` section (1 line below) uses `<form method="">`  - not just created element.

### Questions or comments

We noticed the issue while troubleshooting Paradoxlabs Firstdata extension issues.

image

CC @rhoerr 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38484: Fix issues with Customer Data when form contains element with name `method`

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

@ihor-sviziev Would you mind performing Code Review?

**Comment by ihor-sviziev** [comment]
https://github.com/magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE

**Comment by lbajsarowicz** [comment]
@magento run all tests

Here we go again with tests, as I added extra file responsible for the issue.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Review by andrewbess — APPROVED** [review]
Hello @lbajsarowicz 
Thank you for your contribution
This is nice fix and looks nice for me
Approved

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Sample Data Tests CE, Sample Data Tests B2B, Sample Data Tests EE

**Comment by andrewbess** [comment]
Hello @lbajsarowicz 
It is not required to run the Sample Data tests.
It doesn't work now ))

**Comment by lbajsarowicz** [comment]
Oh, thanks @andrewbess, I wasn't aware

**Comment by andrewbess** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Delta** [comment]
@magento create issue

**Comment by engcom-Echo** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**
 We have followed steps from [comment](https://github.com/magento/magento2/pull/38449#issue-2139238026)

**Before:** :heavy_multiplication_x: 
Screenshot 2024-03-06 at 11 11 47 AM


**After:** :heavy_check_mark:  
Screenshot 2024-03-06 at 11 21 58 AM

Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE,Functional Tests B2B

**Pull request merged**
