### PR TITLE
Save product using repository in adminhtml controller

### PR DESCRIPTION
**Pull request by Jeroenll**
### Description (*)
Save product in `Magento\Catalog\Controller\Adminhtml\Product\Save` using Repository. Will be much easier to customize the flow if a plugin can be created on the `Repository::save()` method.

### Fixed Issues (if relevant)
1. None I could find.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @JeroenVanLeusden. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — APPROVED** [review]
Not sure if it will pass the builds but let's try. A bit surprised `$saveOptions` is not used anymore.

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3337](https://jira.corp.magento.com/browse/ENGCOM-3337) has been created to process this Pull Request

**Review by orlangur — CHANGES_REQUESTED** [review]
@JeroenVanLeusden please check tests failing on Travis CI.

**Comment by sivaschenko** [comment]
@orlangur @JacobBrownAustin I don't think Travis fails are related to the PR

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [new Magento instance](https://pr-18950.instances.magento-community.engineering).
Admin access: [https://pr-18950.instances.magento-community.engineering/admin](https://pr-18950.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by p-bystritsky** [comment]
@JeroenVanLeusden this improvement is incorrect, as ProductRepository currently is trying to load product by sku before saving it.
https://github.com/magento/magento2/blob/6cc68c64c91aee7bc1f4a66a3892b94843df78a6/app/code/Magento/Catalog/Model/ProductRepository.php#L578
So creating new product with existing sku will just override existing one instead of creating new with the modified sku.
You can try to fix this bug or wait until https://github.com/magento-engcom/import-export-improvements/pull/119 would be merged, as this PR may resolve this problem.

**Comment by Jeroenll** [comment]
@p-bystritsky I can wait till that PR is merged. Does that mean I have to wait till the fixed is merged into main line and re-submit the PR?

**Comment by p-bystritsky** [comment]
@JeroenVanLeusden, no, just wait.

**Pull request closed without merging**
