### PR TITLE
Resolve Many field has no validate number in Checkout settings issue24307

### LINKED ISSUE #24307: Many field has no validate number in Checkout settings
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Store->Configurations
3. Sales->Checkout
4. 

Maximum Number of Items to Display in Order Summary
Quote Lifetime (days)
Number of Items to Display Pager
Number of Items to Display Scrollbar
Maximum Number of Items to Display

5. Fill "one"
6. Save

### Expected result (*)

1. Can not save because it is not number

### Actual result (*)

1. Save normally

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#24307: Many field has no validate number in Checkout settings

Solution: add "validate-zero-or-greater validate-digits" to app/code/Magento/Checkout/etc/adminhtml/system.xml

### Fixed Issues (if relevant)

1. magento/magento2#24307: Many field has no validate number in Checkout settings

### Manual testing scenarios (*)

1. Go to backend
2. Store->Configurations
3. Sales->Checkout
4. 

Maximum Number of Items to Display in Order Summary
Quote Lifetime (days)
Number of Items to Display Pager
Number of Items to Display Scrollbar
Maximum Number of Items to Display

5. Fill "one"
6. Save

#### Expected result

1. Can not save because it is not number

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-5711](https://jira.corp.magento.com/browse/ENGCOM-5711) has been created to process this Pull Request

**Comment by dmytro-ch** [comment]
Hi @edenduong,
please, combine the pull requests with such improvements in one single pull request on order make it easier to process these PRs by Community Engineering Team.
#24313
#24309
#24303 
#24305
Also, feel free to create pull requests for minor fixes and obvious improvements without opening the issues.

Thank you!

**Comment by swnsma** [comment]
@magento combine 24313 24303 24305

**Comment by magento-engcom-team** [comment]
Hi @edenduong
Thank you for your contribution. This pull request has been combined (merged) with https://github.com/magento/magento2/pull/24313 to optimize pull requests queue on magento/magento2 repository
Closing this pull request.

**Pull request closed without merging**
