### PR TITLE
33641 UrlRewriteGraphQl::resolve - lack of rtrim url before processin…

### LINKED ISSUE #33641: Wrong redirectCode returned by urlResolver() GraphQL endpoint
### Preconditions (*)

1. Magento 2.4.2 CE
2. docker-php-fpm:7.4-0.0.1

### Steps to reproduce (*)

1. Make request:
image

### Expected result (*)

1. "redirectCode" in response should be "0"

### Actual result (*)

1. "redirectCode" in response is "301"

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

### PR DESCRIPTION
**Pull request by kvydiuk**
### Description (*)

Unexpected redirectCode returned by urlResolver() GraphQL endpoint in case if url ends with "/" character.

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/33641

### Manual testing scenarios (*)

1. Make request:
image
2. "redirectCode" in response should be "0"

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by kirillvidyuk** [comment]
@magento run all tests

**Comment by kirillvidyuk** [comment]
Hi @shikhamis11,

Could you help please.
I see there are some errors in tests and seems they are not relates to my code changes.
Am I should fix these errors?

Examples:
# https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/33652/7179780a8a70abd735a7ee285603ff46/Unit/console-error-logs.html
image
# https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/33652/c5da2284bf77292f0d7800e4a60b4e6c/WebApi/console-error-logs.html
image

**Comment by sidolov** [comment]
@kirillvidyuk could you please describe the real use case for the issue? I believe if you have URL without tailing '/' and requesting it using tailing '/' - you should be redirected to the URL without tailing '/'.

**Comment by kirillvidyuk** [comment]
Hi @sidolov, 
Thank you, now I got the point - that's PWA issue, not GraphQL API. 
Precedent: https://drive.google.com/file/d/112ZwbmWUuunLemLOwVJAG74j-njXO9tQ/view?usp=sharing
I'll open and issue in PWA repository

**Pull request closed without merging**
