### PR TITLE
Chore: Widget - Replace Block Escaping with Escaper

### LINKED ISSUE #37146: [Issue] Chore: Widget - Replace Block Escaping with Escaper
This issue is automatically created based on existing pull request: magento/magento2#37043: Chore: Widget - Replace Block Escaping with Escaper

---------
### Description (*)
Refactors the `Magento_Widget` module to replace `$block` escaping functions with `$escaper` escaping functions.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by pykettk**
### Description (*)
Refactors the `Magento_Widget` module to replace `$block` escaping functions with `$escaper` escaping functions.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37146: Chore: Widget - Replace Block Escaping with Escaper

### CODE REVIEW

**Comment by pykettk** [comment]
@magento create issue

**Review by andrewbess — APPROVED** [review]
Hello @pykettk 
Thank you for your contribution here.

**Review by leonhelmus — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**
- Create Widget in the admin panel and verify it in frontend.
- Verify created widget is getting displayed in the admin panel.
- Delete the widget.

**After:** :heavy_check_mark:  
Screenshot 2023-06-05 at 7 07 17 PM

No additional manual test cases is required as a part of regression cycle as this is related to the refactoring of the `Magento_Widget` module to replace $block escaping functions with $escaper escaping functions.

Moving this PR to **Extended Testing** as builds are failed.

**Comment by pykettk** [comment]
@sidolov Why have all of these PRs been closed?

**Pull request closed without merging**
