### PR TITLE
View details toggle arrow not in single line for config product check…

### PR DESCRIPTION
**Pull request by cedarvinda**
…out page > minicart #25366 issue fixed

View details toggle arrow not in single line for config product checkout page > minicart #25366 issue fixed

### Manual testing scenarios (*)
1. Open frontent 
2. Add to cart any configurable product 
3. Go to mini cart and click in Proceed to Checkout button 
4. Now resize the page the window to 320 and click cart summary link 
and now refer screenshot 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rodrigowebjump** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [new Magento instance](https://pr-25368.instances.magento-community.engineering).
Admin access: [https://pr-25368.instances.magento-community.engineering/admin](https://pr-25368.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rodrigowebjump — APPROVED** [review]
Hi @cedarvinda 

Thanks for your contribution.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
