### PR TITLE
Fix product import sku field data type bug

### LINKED ISSUE #7904: Product import updates wrong product
### Preconditions

1. Magento 2.1.1

### Steps to reproduce

1. Two existing products with sku 13020663105 (db entity_id = 2) and 13020663105SL (db entity_id = 1)
2. Use magento product import/update
3. Try to update name for 13020663105

### Expected result

1. Name changed for 13020663105

### Actual result

1. Name changed for 13020663105SL

This is because of Magento\CatalogImportExport\Model\Import\Product function _saveProductAttributes(array $attributesData).

It creates select: 
`SELECT `catalog_product_entity`.*, `catalog_product_entity`.`entity_id` FROM `catalog_product_entity` WHERE (sku = 13020663105)`

This will return two rows and fetchOne will select first one.

Should be: 
`SELECT `catalog_product_entity`.*, `catalog_product_entity`.`entity_id` FROM `catalog_product_entity` WHERE (sku = '13020663105')`

### PR DESCRIPTION
**Pull request by jurgisl**
Fixes #7904. Always convert SKU to string.

Without the quotes SKU field on the left is being converted to numeric so it drops trailing characters. Then the numeric comparison sees the 13020663105 and 13020663105SL as the same numbers.

This happens because earlier SKUs are being used as array keys, and array keys, if it is possible, are converted to integer by PHP  http://php.net/manual/en/language.types.array.php:

> Strings containing valid integers will be cast to the integer type. E.g. the key "8" will actually be stored under 8. On the other hand "08" will not be cast, as it isn't a valid decimal integer.

So if the function is using these keys, they must be manually cast to string (because all SKUs should always be treated as string?).

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=7961) <br/>All committers have signed the CLA.

**Review by antonkril — APPROVED** [review]

**Comment by driskell** [comment]
I can see this conflicts as it is now fixed in develop:

https://github.com/magento/magento2/commit/c2c8abb6df15a0ee6ac2b08850e2966eec081896

**Comment by maghamed** [comment]
Closed as fix for this issue already delivered into [mainline](https://github.com/magento/magento2/commit/c2c8abb6df15a0ee6ac2b08850e2966eec081896)

**Comment by tkn98** [comment]
Ack.

**Pull request closed without merging**
