### PR TITLE
Store longer X-Forwarded-For header

### LINKED ISSUE #28693: IPv6 values of X_FORWARDED_FOR in sales orders are truncated to 32 characters.
### Preconditions (*)

1. Magento 2.4-develop
2. When customer is using IPV6 address, the x_forwarded_for IP might get saved only partially into sales_order and quote tables depending on the address str length.  Problem appears to be in the x_forwarded_for column length which currently is VARCHAR(32)
3. This seems to be a version of the error descripted in #10395 for REMOTE_IP
4. Known to exist in our version 2.3.5-p1 but I suspect it probably pre-exists all the way back to at least 2.1.x

### Steps to reproduce (*)

1.Customer creates order from an IPv6 address that is longer than 32 characters when 
IPv6 addresses can be up to 45 characters.

### Expected result (*)

1. Veiw order for Placed from IP	2600:1700:ec11:1a40:f829:8829:139c:d85f (2600:1700:ec11:1a40:f829:8829:139c:d85f)
2.

### Actual result (*)

1. Placed from IP	2600:1700:ec11:1a40:f829:8829:139c:d85f (2600:1700:ec11:1a40:f829:8829:13)
2. Note the truncated value in () is 32 characters long.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ S1] Severity: **S1** _- A recently installed fraud detection tool used for analyzing the order is detecting that the actual IP and the forwarded IP don't match, and further their API is throwing an error because the forwarded IPv6 value is malformed and thus invalid.  Since nearly a third of the traffic coming to our website is IPv6, this issue is hindering our ability to detect fraudulent orders.

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
Header X-Forwarded-For could contains multiple IPs
This PR allow to store longer values

For instance in my DB I had value like this:
`4x.xxx.xx.xx, 1xx.xxx.xx.xx, 10.`, where xxx - masked IP address of customer, while last IP address was just cut due to limit on the field in DB.

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
Fixes #28693

### Manual testing scenarios (*)
1. Install Magento behind reverse proxy and Varnish
2. Go to website and place order
3. Go to admin > Sales > Orders
4. Navigate to your order, see data in field "Placed from IP"

**Actual result:**
X-Forwarded-For header is cut

**Expected result:**
It shouldn't be cut

### Questions or comments
Ma

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Nice catch, @ihor-sviziev!
The issue is relevant and must be fixed.

I guess this change can be covered by an integration test. We can either update an [existing fixture](https://github.com/magento/magento2/blob/2.4-develop/dev/tests/integration/testsuite/Magento/Sales/_files/order.php) or create a new one.
What do you think?

Thank you!

**Comment by ihor-sviziev** [comment]
Will check it little bit later

**Comment by ihor-sviziev** [comment]
Unfortunately I don't have free time for implementing tests for my change.

@engcom-Golf @engcom-Charlie could you help with test coverage?

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@engcom-Charlie maybe it's better to have more real value, like IPV6 address, or multiple ipv4 IPs?

**Comment by engcom-Charlie** [comment]
@ihor-sviziev, In my opinion, it doesn't matter if there are IP addresses or symbols, because the PR change is the length of characters in the column.

**Comment by ihor-sviziev** [comment]
@dmytro-ch could you review again this pr?

**Review by dmytro-ch — APPROVED** [review]
The changes look good to me. Thank you!

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7756](https://jira.corp.magento.com/browse/ENGCOM-7756) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked value longer than 32 symbols is saved in `x_forwarded_for` in database
#27221PR

**Pull request merged**
