### PR TITLE
#20463 Fix order summary view details label misalign

### PR DESCRIPTION
**Pull request by mfickers**
### Description (*)

This fixes possible misalignment of "View Details" label for configurable products in the order summary, which happens on tablet-sized screens, especially just above the mobile breakpoint (width of 769px).

### Fixed Issues (if relevant)

1. magento/magento2#20463: On order sumary view details label misalign on tablet

### Manual testing scenarios (*)

1. Add configurable product to cart
2. Go to checkout shipping step
3. "View Details" label of order summary items should not misalign on desktop screens of varying screen widths, especially 769px.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by krzksz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-6348](https://jira.corp.magento.com/browse/ENGCOM-6348) has been created to process this Pull Request
:eight_spoked_asterisk: @krzksz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by krzksz — CHANGES_REQUESTED** [review]
I see you did changes for Luma theme, does it look ok in Blank?

**Comment by mfickers** [comment]
I updated the PR to also include a similar fix for the same issue on Blank theme.

**Review by krzksz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-6348](https://jira.corp.magento.com/browse/ENGCOM-6348) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

**Before:**
before

**After:**
after

The same results and in the Blank theme.

**Pull request merged**
