### PR TITLE
In admin, url params may get url encoded more than once

### PR DESCRIPTION
**Pull request by 4lexvav**
### Description
The parent method `getUrl` should be called only once. For this purpose, I have moved a call to the `parent::getUrl()` method under the if condition, so now it's getting called only once. And as the result URL parameters no longer encoded more than once.

### Fixed Issues (if relevant)

1. magento/magento2#11478: In admin, url params may get url encoded more than once
2. magento/magento2#11343: Search term in admin grid column filter is replaced with unicode characters

### Manual testing scenarios
1. Go to Attribute Set grid in Admin Panel and try to filter by name.
2. Change sorting direction.
3. URL parameters no longer encoded multiple times and everything works correctly.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=12733) <br/>All committers have signed the CLA.

**Comment by vkublytskyi** [comment]
@4lexvav your fix changes resulting URL (see failed integration tests). It would be perfect to fix state modification in `getUrl` method. Order of methods call should not have an impact on a result as well as a count of method execution. The side effects are the reals source of an issue and this logic would be always buggy if not fix it.

**Comment by 4lexvav** [comment]
@vkublytskyi thanks for your notes, I see, will try to investigate it further

**Comment by sidolov** [comment]
Hi @4lexvav , will you continue progress with PR?

**Comment by 4lexvav** [comment]
Hi @sidolov, sorry, I think we can close this PR for now.

**Comment by sidolov** [comment]
@4lexvav , thank you for the collaboration!
If you wish to continue, please, reopen the pull request.

**Pull request closed without merging**
