### PR TITLE
Add possibility to disable the admin notification window and toolbar

### PR DESCRIPTION
**Pull request by tdgroot**
### Description (*)
Add possibility to disable the admin notification window (the popup about Magento 2.X release after logging in) and toolbar (the notification icon with message count in the header).

### Fixed Issues (if relevant)
None that I know of.

### Manual testing scenarios (*)

1. Have items in your admin notification inbox and make sure you see the notification window after logging in.
2. Set configuration **Show notification window after logging in** to **No**. 
3. Log out and log back in. The notification window should not appear.
4. Set configuration **Show notifications in toolbar** to **No**.
5. The notification icon in the header should not appear.

### Questions or comments
This is kind of a short feature request/addition to the current feature set. The Magento 2 notifications can be relevant to merchants, but in many situations they are prone to be 'spammy' and 'irrelevant'. It should be possible to disable these notifications showing up.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by miguelbalparda** [comment]
How about just disabling the entire AdminNotification module to achieve the same result?

**Comment by tdgroot** [comment]
I tried that, but that also disabled system notifications like index management, cache management and tax settings.

**Comment by okorshenko** [comment]
@magento run Integration Tests build

**Comment by okorshenko** [comment]
@magento run Semantic Version Checker build, Integration Tests build

**Comment by okorshenko** [comment]
@magento run all tests

**Comment by okorshenko** [comment]
Hi @tdgroot 
This is an interesting feature. We will need to double-check this behavior with Magento PO

**Comment by okorshenko** [comment]
Just sent a request to Magento PO for approval

**Comment by tdgroot** [comment]
> Just sent a request to Magento PO for approval

@okorshenko have you heard from the PO yet?

**Comment by tdgroot** [comment]
@okorshenko I see the release line has been changed to 2.4. What's the current status of the pull request?

**Comment by chernenm** [comment]
Hello @tdgroot,

We have discussed the enhancement you proposing and agreed that currently we cannot merge this contribution, due to Magento uses this pop-up and notification toolbar to communicate critical messages about Magento updates to our on prem merchants and we do want these messages to read, so we need them to be visible. Anyway, thank you for your contribution we really appreciate your involvement.

**Comment by okorshenko** [comment]
Thank you @chernenm for sharing Magento PM vision. 
We are closing this PR for now

**Pull request closed without merging**
