### PR TITLE
[Catalog|Eav] Revert change of PR magento/magento2#13302 not included into revert commit

### PR DESCRIPTION
**Pull request by Den4ik**
### Description (*)

This PR provide revert change of PR magento/magento2#13302 not included into revert commit https://github.com/magento/magento2/commit/06019a6215ea31982494708d55745ae0b9622696

### Fixed Issues (if relevant)

Reverted Catalog collection and eav test 
 not included into https://github.com/magento/magento2/commit/06019a6215ea31982494708d55745ae0b9622696

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by orlangur — CHANGES_REQUESTED** [review]
@Den4ik please add more details - which PR are you referring to and how changes can be verified.

**Comment by Den4ik** [comment]
@orlangur 
ENGCOM-3502: Introduce resource model pool to replace UniversalFactory #13302
- Merge Pull Request magento/magento2#13302 from schmengler/magento2:resource-model-pool

**Comment by Den4ik** [comment]
and revert commit "MC-15995: Revert change of PR 3766" 
https://github.com/magento/magento2/commit/06019a6215ea31982494708d55745ae0b9622696

**Comment by Den4ik** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [Magento instance](https://i-22561-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22561-2-3-develop.instances.magento-community.engineering/admin](https://i-22561-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by orlangur** [comment]
@Den4ik please reflect correct PR number in commit message then (preferable form should contain `magento/magento2#NUMBER`). Please add some insight in that PR why it was reverted and some steps to description of this PR how to test changes.

**Comment by Den4ik** [comment]
@orlangur 
Original PR https://github.com/magento/magento2/pull/13302
I see that all relations for ResourceModelPoolInterface removed but forgot about product collection
Currently I have receiving "Class Magento\Framework\Model\ResourceModel\ResourceModelPoolInterface does not exist" for setup:di:compile

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-4872](https://jira.corp.magento.com/browse/ENGCOM-4872) has been created to process this Pull Request

**Review by orlangur — CHANGES_REQUESTED** [review]
Commit message and issue summary does not contain appropriate information, @Den4ik please fix.

**Comment by Den4ik** [comment]
@orlangur commit message updated

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-4872](https://jira.corp.magento.com/browse/ENGCOM-4872) has been created to process this Pull Request

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4872](https://jira.corp.magento.com/browse/ENGCOM-4872) has been created to process this Pull Request

**Pull request merged**
