### PR TITLE
[Forwardport] Fix false cache_lifetime usage in xml layouts

### PR DESCRIPTION
**Pull request by mageprince**
### Original Pull Request 
 https://github.com/magento/magento2/pull/16086

Fix cache_lifetime usage with false value
### Description

Fix
`<argument name="cache_lifetime" xsi:type="boolean">false</argument>`
Usage eg in
Magento/Swatches/view/frontend/layout/checkout_cart_configure_type_configurable.xml

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

Reproduced in 2.2 and 2.1 version
1. Add configurable product to cart
2. Move to cart
2. Edit Configurable product

**Expected result**
Configurable product options should be preselected

**Actual result:**
Configurable product options are not preselected

It happens because there is a check in
View/Element/AbstractBlock.php
`
protected function _loadCache() { 
if ($this->getCacheLifetime() === null || !$this->_cacheState->isEnabled(self::CACHE_GROUP)) { return false; }
`

### Contribution checklist
 - [x ] Pull request has a meaningful description of its purpose
 - [x ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mageprince. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-2217](https://jira.corp.magento.com/browse/ENGCOM-2217) has been created to process this Pull Request

**Comment by sidolov** [comment]
Hi @mageprince , please, take a look at failed tests

**Comment by sidolov** [comment]
@mageprince , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
