### PR TITLE
Fixed remaining failed Integration Tests for PHP 8.1. compatibility

### PR DESCRIPTION
**Pull request by karyna-t**
### Description (*)
Fix for tests that remain failed after main 8.1 compatibility fixes
- dev/tests/integration/testsuite/Magento/AdvancedCheckout/Model/CartTest.php
- dev/tests/api-functional/testsuite/Magento/Webapi/WsdlGenerationFromDataObjectTest.php

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by xmav** [comment]
@magento run Static Tests, Integration Tests, Functional Tests EE

**Comment by xmav** [comment]
@magento import code to Magento-trigger/magento2ce

**Comment by m2-github-services** [comment]
@xmav the branch with the code is successfully imported into the `Magento-trigger/magento2ce` repository. Branch name: `imported-karyna-tsymbal-atwix-magento2-34617`.

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by xmav** [comment]
FT failure is not related to changes in this PR

**Comment by xmav** [comment]
@magento import code to Magento-trigger/magento2ce

**Comment by m2-github-services** [comment]
@xmav the branch with the code is successfully imported into the `Magento-trigger/magento2ce` repository. Branch name: `imported-karyna-tsymbal-atwix-magento2-34617`.

**Pull request merged**
