### PR TITLE
[GraphQl] The fields that described below has been deprecated

### LINKED ISSUE #30625: GraphQl public catalog endpoints expose some data that should not be visible
### Preconditions (*)
1. Magento installation with `CatalogGraphQl` module enabled

### Steps to reproduce (*)
Take a look at the [ProductInterface](https://github.com/magento/magento2/blob/8c4de4d793590a4ca5282e4afb986205c7b773b4/app/code/Magento/CatalogGraphQl/etc/schema.graphqls#L85)

It allows retrieving some data for the non-authorized users that we usually expose neither on the standard storefront nor with the REST API.  

For example, the following fields
- `special_from_date`
- `special_to_date` 

are not supposed to be visible for a non-authorized client since this data exposes information about sales period that should be hidden by default.

The same about 

- `created_at`
- `updated_at` 
- `websites`
- `attribute_set_id`

### Expected result (*)
1. Only data that is required for rendering product details on the storefront is available

### Actual result (*)
1. Product data that is supposed to be visible for admin only is visible for non-authorized users

### Proposed solution

At least, remove the following fields from the schema

- `special_from_date`
- `special_to_date` 

The other fields mentioned in the issue need to be discussed

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by andrewbess**
### Description (*)

This pull request (PR) adds the `@deprecated` directive to the fields that described below according to requirements issue #30625 

ProductInterface
- special_from_date
- attribute_set_id
- new_from_date
- new_to_date
- created_at
- updated_at

CategoryInterface
- created_at
- updated_at

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30625: GraphQl public catalog endpoints expose some data that should not be visible

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by andrewbess** [comment]
@magento run all tests

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @andrewbess.
Please, check the failing tests. 
Thank you

**Comment by andrewbess** [comment]
Hello @rogyar
Thank you for your review.
The QueryComplexityLimiterTest tests have been fixed.
Waiting for finish.

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by nrkapoor** [comment]
@akaplya @cpartica @mauragcyrus Can we prioritize this issue?

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run Static Tests

**Comment by andrewbess** [comment]
@magento run WebAPI Tests

**Comment by andrewbess** [comment]
@magento run Unit Tests, Semantic Version Checker, Database Compare, Integration Tests, Magento Health Index, Sample Data Tests CE, Sample Data Tests EE, Sample Data Tests B2B

**Comment by andrewbess** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by andrewbess** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8430](https://jira.corp.magento.com/browse/ENGCOM-8430) has been created to process this Pull Request

**Review by cpartica — APPROVED** [review]

**Pull request merged**
