### PR TITLE
Issue #27925, moved the submit button to the inside of the <form>

### LINKED ISSUE #27925: Checkout: Placing an order using the enter key causes a redirect to the checkout
### Preconditions (*)

1. Tested on Magento 2.3.2, 2.3.3, 2.3.4 and 2.3.5
2. At least one product enabled
3. Enable "Purchase Order" as a payment method, or any other payment method where one or more input fields needs to be filled out

### Steps to reproduce (*)

1. Add a product to the cart and proceed to the checkout
2. Enter your shipping details and proceed to "Review & Payments"
3. Select "Purchase Order" as your payment of choice
4. Enter a random "Purchase Order Number"
5. Press enter while the focus is still on the "Purchase Order Numer" field

### Expected result (*)

1. form should be submitted (and validated) on keyboard Enter. Order is placed

### Actual result (*)

1. The checkout page reloads
magento-issue--27925

### PR DESCRIPTION
**Pull request by vestman**
### Description (*)

Placing the submit button inside the `<form id="purchaseorder-form"...></form>` makes implicit submission[1] possible without altering any JS.
[1] - https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission

### Related Pull Requests
https://github.com/magento/partners-magento2b2b/pull/417

### Fixed Issues (if relevant)

1. Fixes magento/magento2#27925: Checkout: Placing an order using the enter key causes a redirect to the checkout

### Manual testing scenarios (*)

1. Add a product to the cart and proceed to the checkout
2. Enter your shipping details and proceed to "Review & Payments"
3. Select "Purchase Order" as your payment of choice
4. Enter a random "Purchase Order Number"
5. Press enter while the focus is still on the "Purchase Order Numer" field

#### Expected result
The form should be submitted (and validated) on keyboard Enter. Order is placed.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by vestman** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @vestman. Thank you for your request. I'm working on Magento instance for you

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello @vestman, thank you for your contribution. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) the changes should be covered by tests. Could you please cover your fix by an automated test? I think in this particular case the Functional test is preferable.
Thank you!

**Comment by engcom-Kilo** [comment]
Working on MFTF test

**Comment by engcom-Kilo** [comment]
Added MFTF tests.

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by vestman** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8091](https://jira.corp.magento.com/browse/ENGCOM-8091) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@vestman thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Precondition:**

Enable "Purchase Order" as a payment method

**Manual testing scenario:**

1. Add a product to the cart and proceed to the checkout
2. Enter your shipping details and proceed to "Review & Payments"
3. Select "Purchase Order" as your payment of choice
4. Enter a random "Purchase Order Number"
5. Press enter while the focus is still on the "Purchase Order Numer" field

**Before:** :heavy_multiplication_x: The checkout page reloads

Peek 2020-08-31 12-06

**After:** :heavy_check_mark: The form is submitted on the Enter keyboard and the order is placed

Peek 2020-08-31 12-11

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by engcom-Charlie — CHANGES_REQUESTED** [review]
Hi @vestman your test `StorefrontCheckoutWithPurchaseOrderNumberPressKeyEnterTest` constantly falls on B2B. Could you please take a look?
Thank you.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
Risk set to low since the changes shouldn't affect other areas.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8091](https://jira.corp.magento.com/browse/ENGCOM-8091) has been created to process this Pull Request

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Precondition:**

Enable "Purchase Order" as a payment method

**Manual testing scenario:**

1. Add a product to the cart and proceed to the checkout
2. Enter your shipping details and proceed to "Review & Payments"
3. Select "Purchase Order" as your payment of choice
4. Enter a random "Purchase Order Number"
5. Press enter while the focus is still on the "Purchase Order Numer" field

**After:** :heavy_check_mark: The form is submitted on the Enter keyboard and the order is placed

Peek 2020-10-13 14-03

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8091](https://jira.corp.magento.com/browse/ENGCOM-8091) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@gabrieldagama seems like now we have incorrect status

**Pull request merged**
