### PR TITLE
Update AddDataForIndia.php

### LINKED ISSUE #33698: [Issue] Update AddDataForIndia.php
This issue is automatically created based on existing pull request: magento/magento2#33172: Update AddDataForIndia.php

---------
### Description (*)

Admin Section
1. On Add/Update Address page from Customer Information >> Address section
2. Edit the Billing and Shipping Address from the Order view page
4. Also in all the above sections, Ladakh is not coming under country India 

**Before:** :heavy_multiplication_x: Ladakh was not getting display in State dropdown

image

image

image

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by manavluhar**
Added **Ladakh** Union Territory, Reference: https://en.wikipedia.org/wiki/Ladakh

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#33698: Update AddDataForIndia.php

### CODE REVIEW

**Comment by manavluhar** [comment]
@magento run all tests

**Review by danielrussob — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @danielrussob, thank you for the review.
[ENGCOM-9164](https://jira.corp.magento.com/browse/ENGCOM-9164) has been created to process this Pull Request
:eight_spoked_asterisk: @danielrussob, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-9164](https://jira.corp.magento.com/browse/ENGCOM-9164) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Charlie** [comment]
@magento create issue

**Comment by engcom-Charlie** [comment]
:heavy_check_mark: QA Passed

Tested this PR with multiple scenarios. Checked for Ladakh option in State dropdown for India country in below sections.

**Manual testing scenario:**

Store front 
1. Create an Account
2. My Account >> Address Book : Tried to update the Default billing and shipping address
3. On Shipping Address page after click on Proceed to checkout with guest customer
4. On Add new address section
5. Also in all above sections, tested that Ladakh is not coming under any other country than India

Back Office/Admin Section
1. On Add/Update Address page from Customer Information >> Address section
2. Edit the Billing and Shipping Address from Order view page
3. Add New Tax Rate Section
4. Also in all above sections, tested that Ladakh is not coming under any other country than India 


**Before:** :heavy_multiplication_x: Ladakh was getting display in State dropdown

image

image

image

**After:** :heavy_check_mark: Ladakh is getting displayed in State dropdown for Country India.
image

image

image

image

**Tested for other country**

image

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @manavluhar,
This change won't work for upgraded Magento instances. Could you create a new data upgrade script instead?

**Comment by xmav** [comment]
@manavluhar Please be aware that original implementation is reverted as it cause issue in upgrade. This was noted before by @ihor-sviziev and confirmed by failed DB compare test.
Please implement in another way.

**Comment by ihor-sviziev** [comment]
@xmav, thx for the update

**Pull request merged**
