### PR TITLE
[MFTF] Refactoring AdminOrdersReleaseInUnholdStatusTest

### LINKED ISSUE #31521: [Issue] [MFTF] Refactoring AdminOrdersReleaseInUnholdStatusTest
This issue is automatically created based on existing pull request: magento/magento2#31487: [MFTF] Refactoring AdminOrdersReleaseInUnholdStatusTest

---------
### Description (*)
The test is refactored to improve execution time

### Manual testing scenarios (*)

1. Create an order
2. Hold the order
3. Unhold the order from the Orders grid
4. Make assertions

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
The test is refactored to improve execution time

### Manual testing scenarios (*)

1. Create an order
2. Hold the order
3. Unhold the order from the Orders grid
4. Make assertions

### Resolved issues:
1. [x] resolves magento/magento2#31521: [MFTF] Refactoring AdminOrdersReleaseInUnholdStatusTest

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8592](https://jira.corp.magento.com/browse/ENGCOM-8592) has been created to process this Pull Request

**Comment by sidolov** [comment]
@magento create issue

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** Functional Tests B2B and Functional Tests CE are failed

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
