### PR TITLE
Add missing return in resolveShippingRates

### PR DESCRIPTION
**Pull request by GordonLesti**
In the function [resolveShippingRates](https://github.com/magento/magento2/blob/2.1.0/app/code/Magento/Checkout/view/frontend/web/js/model/checkout-data-resolver.js#L169) is a missing `return` statement after `selectShippingMethodAction`. Without this statement it can happen, that `selectShippingMethodAction` is called second time.
~~This leads to the point that `selectShippingMethodAction` is called with the parameter `true` and that for example [shipping.js](https://github.com/magento/magento2/blob/2.1.0/app/code/Magento/Checkout/view/frontend/web/js/view/summary/shipping.js#L25) returns `undefined - undefined` as carrier title and method title of the shipping method.~~

This behavior can be reproduced with
- more than one available shipping method so that [ratesData.length](https://github.com/magento/magento2/blob/2.1.0/app/code/Magento/Checkout/view/frontend/web/js/model/checkout-data-resolver.js#L147) is bigger than `1`
- select a shipping method in the checkout so that [window.checkoutConfig.selectedShippingMethod](https://github.com/magento/magento2/blob/2.1.0/app/code/Magento/Checkout/view/frontend/web/js/model/checkout-data-resolver.js#L167) exists
- go back to cart
- the shipping method in `cart-totals` will be rendered twice ~~and the second time with `Shipping (undefined - undefined)`~~

## Edit
Since commit [e72482c9fd7eeaac29f9710b6c39c9eafe5ed0b0](https://github.com/magento/magento2/commit/e72482c9fd7eeaac29f9710b6c39c9eafe5ed0b0) the code
```javascript
if (!availableRate && window.checkoutConfig.selectedShippingMethod) {
    availableRate = true;
    selectShippingMethodAction(window.checkoutConfig.selectedShippingMethod);
}
```
has changed to
```javascript
if (!availableRate && window.checkoutConfig.selectedShippingMethod) {
    availableRate = window.checkoutConfig.selectedShippingMethod;
    selectShippingMethodAction(window.checkoutConfig.selectedShippingMethod);
}
```
and the `undefined - undefined` problem doesn't occur anymore, but without the `return` statement the function `selectShippingMethodAction` is called twice with the same argument and the shipping method is rendered twice without any reason.

### CODE REVIEW

**Comment by vrann** [comment]
@GordonLesti please update the code with the latest mainline

**Comment by GordonLesti** [comment]
@vrann code is updated with latest mainline.

**Comment by vrann** [comment]
@GordonLesti successfully merged, thank you!

**Comment by GordonLesti** [comment]
@vrann thank you

**Pull request merged**
