### PR TITLE
Fix issue 7075

### PR DESCRIPTION
**Pull request by rmsundar1**
Fixed low stock CSV/XML export issue.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=7148) <br/>All committers have signed the CLA.

**Comment by stevenvdp** [comment]
Applied this fix in my local 2.1.5 installation and it works, thx @rmsundar1 !
@magento-team  can you merge this PR so it's available in the next release?

**Comment by okorshenko** [comment]
@rmsundar1 could you please provide some testing info? What issue you are trying to fix and how to verify it. Thank you

cc: @stevenvdp

**Comment by magento-team** [comment]
@rmsundar1 thank you for your contribution. Your Pull Request has been successfully merged

**Pull request merged**
