### PR TITLE
ISSUE-14747 Newsletter subscription confirmation message does not dis…

### PR DESCRIPTION
**Pull request by KaushikChavda**
### Fixed Issues (if relevant)

1. magento/magento2#14747: Newsletter subscription confirmation message does not display after clicking link in email

### Manual testing scenarios

1. I've tested with my local environment and its working fine.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by VladimirZaets** [comment]
Hi, @kaushik-chavda , I took your PR into processing, thank you for collaboration.

**Comment by VladimirZaets** [comment]
Hi @KaushikChavda  , please, sign CLA, otherwise, we can't process your pull request

**Comment by VladimirZaets** [comment]
@KaushikChavda Thanks

**Comment by KaushikChavda** [comment]
@VladimirZaets  is there anything pending at my-end?

**Comment by magento-engcom-team** [comment]
Hi @KaushikChavda. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

Please, consider porting this solution across release lines.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
