### PR TITLE
[Backport] Secure errors directory

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Original Pull Request 
 https://github.com/magento/magento2/pull/20212

### Description (*)

**For Apache:** deny access to XML and PHTML files within errors directory (pub/errors/.htaccess)
**For Nginx:** deny access to PHTML files in general and XML files within errors directory (nginx.conf.sample)

### Fixed Issues (if relevant)

1. magento/magento2#20209: errors/local.xml and error page templates are publicly accessible

### Manual testing scenarios (*)

See issue #20209 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by amol2jcommerce** [comment]
Hi @orlangur, please review.

**Comment by orlangur** [comment]
@amol2jcommerce you could've notice I put in `on hold`. Will be reviewed soon.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4657](https://jira.corp.magento.com/browse/ENGCOM-4657) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Before:**

before

**After:**

after

**Pull request merged**
