### PR TITLE
Replace JSON serializer with JSON Hex Tag (User module)

### LINKED ISSUE #31377: [Issue] Replace JSON serializer with JSON Hex Tag (User module)
This issue is automatically created based on existing pull request: magento/magento2#31359: Replace JSON serializer with JSON Hex Tag (User module)

---------
### Description (*)
The serializer injected into the View Model is being used to serialize data for the Store views. 
When trying to use the data serialized with a regular Serializer, it ends up on crash when you have unescaped elements in your contents. That is why JsonHexTag class was introduced. 

The goal of this PR is to replace the JSON serializer with the more useful/accurate one.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
The serializer injected into the View Model is being used to serialize data for the Store views. 
When trying to use the data serialized with a regular Serializer, it ends up on crash when you have unescaped elements in your contents. That is why JsonHexTag class was introduced. 

The goal of this PR is to replace the JSON serializer with the more useful/accurate one.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31377: Replace JSON serializer with JSON Hex Tag (User module)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Could you cover this change with some kind of test?

**Comment by ihor-sviziev** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
@lbajsarowicz will you be able to cover your change with any type of test?

**Comment by lbajsarowicz** [comment]
@ihor-sviziev Yes, I need few more days - sorry.

**Comment by ihor-sviziev** [comment]
@lbajsarowicz any updates on this?

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Hello @ihor-sviziev,

This is to inform you that, the test is already added for the below method:

https://github.com/magento/magento2/blob/ab0c0b54309d61d5bc207c73efad214e35516189/app/code/Magento/User/ViewModel/JsonSerializer.php#L36-L39

Please refer to the test below:

https://github.com/magento/magento2/blob/ab0c0b54309d61d5bc207c73efad214e35516189/app/code/Magento/Customer/Test/Unit/ViewModel/Customer/JsonSerializerTest.php#L47-L65

Which has been added after this PR, Please refer to the below commit:

https://github.com/magento/magento2/commit/12391182fde6afda79aa89f82db029bb71e00cca

And the failed test seems flaky to me, hence moving this PR further for testing.

Thanks

**Comment by engcom-Lima** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**
- Verified JSON serializer is updated with JSON Hex tag  in `app/code/Magento/User/ViewModel/JsonSerializer.php` file.
- Created multiple store views and placed orders from all of them.
- Verified the functionality of store views in the Order page.

No additional manual test cases are required as part of regression as this PR is related to the replacement of the JSON serializer with JSON hex tag.

Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

**Comment by engcom-Echo** [comment]
Functional Tests CE Failures are not related to PR changes.
Hence moving it to `Merge in progress`

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

**Comment by engcom-Echo** [comment]
Functional Tests CE failures are different on last two run on same commit.
Run1
Screenshot 2023-09-13 at 9 11 00 AM

Run2
Screenshot 2023-09-13 at 9 11 05 AM

**Integration Tests** Failure is known failure not related to this PR. Hence moving it to `merge in progress`

**Pull request merged**
