### PR TITLE
[Backport] Time-fields-misaligned-in-iPad-landscape-view ::Time fields misaligne…

### PR DESCRIPTION
**Pull request by irajneeshgupta**
### Original Pull Request 
 https://github.com/magento/magento2/pull/20581
…d in iPad landscape view (1024 x 768)

### Fixed Issues (if relevant)

1. magento/magento2 #20580: Time fields misaligned in iPad landscape view (1024 x 768)

### Manual testing scenarios (*)

In Admin Stores >> Configuration >> General >> Advanced Reporting >> Time of day to send data

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by amol2jcommerce** [comment]
Duplicate #20602

**Comment by irajneeshgupta** [comment]
@amol2jcommerce 
your backport is not preserving original author commits , hence do not add anything in my PR.
Thanks.

**Comment by miguelbalparda** [comment]
Closing as duplicate.

**Comment by ghost** [comment]
Hi @irajneeshgupta, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+magento2+20978), it will take less than a minute. </br>Your feedback will help us to improve contribution process.

**Pull request closed without merging**
