### PR TITLE
Allow shipment update emails to be disabled

### LINKED ISSUE #33165: Cannot disable shipment update emails
### Preconditions

1. Magento 2.4.2;

### Steps to reproduce

1. In the admin panel, go to Stores > Configuration > Sales > Sales Emails and disable the Shipment comments;
2. Open a shipment view in the admin panel;

### Expected result

1. No `Notify Customer by Email` checkbox;

### Actual result (*)

1. Checkbox is still there:

Screenshot from 2021-06-07 15-36-36

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by kassner**
### Description

Already in place for invoices and creditmemos:

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/view/adminhtml/layout/sales_order_invoice_view.xml#L26-L30

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/view/adminhtml/layout/sales_order_creditmemo_view.xml#L25-L29

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33165

### Manual testing scenarios

See #33165

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by eduard13** [comment]
@magento run all tests

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @kassner, thank you for your contribution. Could you please cover this fix by any automated tests (MFTF, integration)?

**Optionally**, may I ask you for a minor adjustment, to move the `admin__field admin__field-option` div to if condition?
https://github.com/magento/magento2/blob/8599e3c03e766fb9664e15019966def5f113748e/app/code/Magento/Sales/view/adminhtml/templates/order/view/history.phtml#L44-L55

ℹ️ The current failed builds aren't related to your changes.

Thank you.

**Comment by kassner** [comment]
> Could you please cover this fix by any automated tests (MFTF, integration)?

Oh. No. I was expecting this to be a quick fix. Setting up MFTF is way out of my league :(

**Comment by eduard13** [comment]
Hi @kassner, I understand, indeed it's a quick one, however to avoid happening in the future, it's better to have it covered by some tests. So, no worries about that. 
@kate-kyzyma may you help us covering this fix by a MFTF test?

**Comment by kate-kyzyma** [comment]
@eduard13 I have added the MFTF test for current changes. Please, check it.

Thanks.

**Comment by eduard13** [comment]
@magento run WebAPI Tests, Functional Tests B2B

**Comment by eduard13** [comment]
@magento run WebAPI Tests, Functional Tests B2B

**Review by eduard13 — APPROVED** [review]
Thank you @kassner for your contribution.

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-9123](https://jira.corp.magento.com/browse/ENGCOM-9123) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed


**Manual testing scenario:**

1. In the admin panel, go to Stores > Configuration > Sales > Sales Emails > Shipment comments - disable it;

2. Open a shipment view (Sales > Shipments > view any shipment from grid) in the admin panel;
 

**Before:** :heavy_multiplication_x: `Notify Customer by Email` checkbox was being active in the UI.

> image


**After:** :heavy_check_mark: `Notify Customer by Email` checkbox is not displayed at all in the UI

> image


Tried enabling and disabling the flag a couple of times, and the issue the feature worked appropriately.

**Comment by engcom-Alfa** [comment]
As per the latest edited details in the [Comment](https://github.com/magento/magento2/pull/33166#issuecomment-877102299) , moving the PR fix for next step.

**Pull request closed without merging**
