### PR TITLE
Use '.min' in filenames of already minified js files in the Swagger module so they aren't getting minified again in production, fixes #16927 - for Magento 2.2

### LINKED ISSUE #16927: 2.2.5 Swagger: With JS minification enabled, the swagger-ui-bundle.js becomes corrupted
### Preconditions
1. Magento 2.2.5
2. PHP 7.1

### Steps to reproduce
1. Enable JS minification
2. Deploy a fresh copy of the static content
3. Visit the Swagger page

### Expected result
The swagger page loads and is usable

### Actual result
The swagger page fails because the swagger-ui-bundle.js throws an error
image

The JS works fine when minification is disabled and the files redeployed.

### PR DESCRIPTION
**Pull request by hostep**
**Please: do not forwardport this PR to 2.3, ~the solution for 2.3 is different and much cleaner, and~, it already exists: https://github.com/magento/magento2/pull/17627**

### Description
The Magento Swagger module contains already minified js files:
- https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Swagger/view/frontend/web/swagger-ui/js/swagger-ui-bundle.js
- https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Swagger/view/frontend/web/swagger-ui/js/swagger-ui-standalone-preset.js

~This PR marks them to not be minified again during static content deploy, because they get changed in a way that they are no longer valid JS.~
This PR renames them so they contain `.min` and reference them as such from the layout xml file as well. This way they don't get minified again in production mode when minification is enabled.

I've already gone ahead and created a fix for Magento 2.3 as well ~, since the solution is very different and much cleaner, this is due to https://github.com/magento/magento2/pull/13687 which only exists in 2.3~
PR for Magento 2.3: https://github.com/magento/magento2/pull/17627

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/16927: 2.2.5 Swagger: With JS minification enabled, the swagger-ui-bundle.js becomes corrupted

### Manual testing scenarios
1. Set up a clean Magento 2.2.5 installation
2. Run: `bin/magento config:set dev/js/minify_files 1`
3. Run: `bin/magento deploy:mode:set production`
4. Go to: https://myinstallation.domain/swagger
5. See JS errors: `Uncaught SyntaxError: Invalid regular expression flag` & `Uncaught ReferenceError: SwaggerUIBundle is not defined`

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @hostep. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by miguelbalparda** [comment]
Both codacy and Travis are complaining about the same, care to check @hostep?

**Comment by hostep** [comment]
@miguelbalparda: I took a completely different approach now, I think it's a better solution and easier to maintain. I've amended my previous commit and force pushed my branch. I also updated the description and title in the opening post so it makes more sense with this new solution. Sorry for the mess! :)

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-2837](https://jira.corp.magento.com/browse/ENGCOM-2837) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @hostep. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
