### PR TITLE
Add filter for `NOT FIND_IN_SET` sql conditions

### PR DESCRIPTION
**Pull request by mageprince**
### Description (*)

Add a filter on a collection for condition NOT FIND_IN_SET. This cannot be be done via addAttributeToFilter or addFieldToFilter because the method Magento\Framework\DB\Adapter\Pdo\Mysql::prepareSqlCondition does not contain a map item for NOT FIND_IN_SET.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mageprince. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by nainesh2jcommerce** [comment]
Hi @mageprince, i think you have added my PR #20606 in reference by mistake, can you please edit.

thanks!

**Comment by mageprince** [comment]
> Hi @mageprince, i think you have added my PR #20606 in reference by mistake, can you please edit.
> 
> Thanks @nainesh2jcommerce I just edit my PR.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-4062](https://jira.corp.magento.com/browse/ENGCOM-4062) has been created to process this Pull Request

**Pull request merged**
