### PR TITLE
Fix issue causing attribute not loading when using getList

### PR DESCRIPTION
**Pull request by teganbold**
### Description (*)
As specified in issue #17759, `CustomerRepository::getList()` is unexpectedly returning `NULL`, when `CustomerRepository::get()` is correctly returning the value. Specifying the attribute as `billing_company` instead of `company` removes the conflict.

### Fixed Issues (if relevant)

1. magento/magento2#17759: M2.2.5 : CustomerRepository::getList() does not load custom attribute if the name is "company" 

### Manual testing scenarios (*)

1. Create/Install two custom `varchar` customer attributes, one with the code `company`.
2. Log the data when loading with `getbyId()`:
    `$customerById = $customerRepository->getbyId(x);`
3. Log the data when loading with `getList()`:
    `$customerByList = $customerRepository->getList($searchCriteria->addFilter('x, y')->create());`

Previously, under custom attributes, both attributes were loading correctly for `getbyId()`, but `company` would pull `NULL` when using `getList()`

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19620) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @Militree. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by teganbold** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Militree. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Militree, here is your [new Magento instance](https://pr-19620.instances.magento-community.engineering).
Admin access: [https://pr-19620.instances.magento-community.engineering/admin](https://pr-19620.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3655](https://jira.corp.magento.com/browse/ENGCOM-3655) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@Militree thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @Militree. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
