### PR TITLE
Fix #12256 #13263 - add Serbian Latin language and change language lists to show script

### LINKED ISSUE #12256: Option to select durring instalation Serbian Latin or Serbian Cyrilic
Hi Magento community,

During installation when selecting default language for magento as
Serbian Language the default language store sr_Cyrl_RS "
general/locale/code - sr_Cyrl_RS" .
This ok but we should have two option Serbian@Latin and Serbian@Cyrilic

Here are the patches.

```
/zendframework1/library/Zend/Locale/Data/likelySubtags.xml.orig
898,899d897
<               <likelySubtag from="sr_latin" to="sr_Latn_RS"/>
<               <!--{ Serbian; ?; ? } => { Serbian; Latin; Serbia }-->
```

This the Config.php

```
magento/framework/Locale/Config.php.orig
90,91c90
<         'sr_Cyrl_RS', /*Serbian Cyrillic (Serbia)*/
<         'sr_Latn_RS', /*Serbian Latin (Serbia)*/
---
>         'sr_Cyrl_RS', /*Serbian (Serbia)*/
```

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This PR adds Serbian Latin language and allows to distinguish which locale is Latin and which is Cyrillic.
Second change is to display script in locale name, so user can select correct language he wants. Before change both **sr_Cyrl_RS** and **sr_Latn_RS** would be displayed as **Serbian (Serbia)**. Now those are **Serbian (Cyrillic, Serbia)** and **Serbian (Latin, Serbia)**.

### Fixed Issues (if relevant)

1. magento/magento2#12256: Option to select durring instalation Serbian Latin or Serbian Cyrilic
2. magento/magento2#13263: In the magenta (all versions) there is no option to choose Serbian-Latin

### Manual testing scenarios (*)

1. Go to MBO
2. Go to Stores -> Configuration -> General -> General -> Locale Options -> Locale
3. See both **Serbian (Cyrillic, Serbia)** and **Serbian (Latin, Serbia)** locales

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by orlangur** [comment]
Hi @Bartlomiejsz, I looked into your pull request but noticed it requires some time to comprehend logic :) Will review this week.

**Comment by Bartlomiejsz** [comment]
@orlangur great, thank you :)

**Comment by Bartlomiejsz** [comment]
Hi @orlangur, any news regarding this one?

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
Hi @Bartlomiejsz , could you please fix static tests and cover introduced changes with automated tests? Thank you!

**Comment by Bartlomiejsz** [comment]
Hi @sidolov, I will work on it

**Comment by Bartlomiejsz** [comment]
Hi @sidolov, done, please review :)

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5972](https://jira.corp.magento.com/browse/ENGCOM-5972) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
