### PR TITLE
MC-39470: issue with dynamicRows component

### LINKED ISSUE #31059: issue with dynamicRows component
### Preconditions (*)

1. Magento 2.4-develop
2. Magento  2.3.4-p2 
3. Sample Data 

### Steps to reproduce (*)

1.Go to Admin -> Catalog -> Product;
2. Chose any product and go to edit form;
3. Go to Related Products, Up-Sells, and Cross-Sells section.
4. Add more than 70 product to Up-Sell or Related products
5. Save the product.
6. Go to the Related Products, Up-Sells, and Cross-Sells section and go to 2,3 and 4 pages

**Actual Result:** :heavy_check_mark:  All 70 products are displayed in the grid

Peek 2020-11-27 15-53

6.1 Change per page value to 5, and try to repeat the previous step(6).

### Expected result (*)
:heavy_check_mark:  When per page value was changed to 5, the total pages count should be updated

### Actual result (*)

:heavy_multiplication_x: We have 70 up-sell products and if we change per page value to 5, then 5 products will be shown and the total pages count won't be updated. 
As a result, we will be able to see only 20 products ( 5 products on 4 pages)

Peek 2020-11-27 15-59

---
S2

### PR DESCRIPTION
**Pull request by SmVladyslav**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#31059 (MC-39470)

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by SmVladyslav** [comment]
@magento run all tests

**Review by engcom-Kilo — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

### Manual testing scenario
1. From the Admin Panel, go to _Catalog - Products_
2. **Edit** any product
3. Expand _Related Products, Up-Sells, and Cross-Sells_
4. Click **Add Related Products** (also tested with _Up-Sell Products_ and _Cross-Sell Products_)
5. Select for example 60-70 products and click **Add Selected Products** from the _Add Related Products_ window
6. Switch the **per page** to **5**

**BEFORE** applying changes provided in the PR, the number of pages, _<Prevous_ _Next>_ has not been updated
number_of
upp_sell

**AFTER** switching to the PR, the number of pages is updated correctly and Admin has access to all products
Peek 2020-12-31 15-45

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31492`.

**Pull request merged**
