### PR TITLE
magento/magento2: fixes PHPDocs for module Magento_reports

### PR DESCRIPTION
**Pull request by andrewbess**
### Description (*)

This PR fixes the wrong types in PHPDocs and adds the necessary throws

### Questions or comments

- The wrong types in the PHPDocs can be confusing for the developer

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
Failing tests are not related to the change provided in the current PR

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7182](https://jira.corp.magento.com/browse/ENGCOM-7182) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Echo** [comment]
Failed static tests not related to the changes in this PR

**Pull request merged**
