### PR TITLE
14882 product types xml doesn t allow numbers in model instance

### PR DESCRIPTION
**Pull request by lisovyievhenii**
### Description 
The files ``product_types_base.xsd``, ``product_options.xsd``, ``import.xsd``, ``export.xsd`` doesn't allow modules with the numbers in the name.

### Fixed Issues
1. magento/magento2#14882: product_types.xml doesn't allow numbers in modelInstance

### Manual testing scenarios (*)
1. Have a module with numbers in Vendor's or module's name.
2. Create ``product_types.xml`` or any other file, mentioned above.

AR: XSD validation error that modelName is invalid.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @lisovyievhenii. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by novikor — APPROVED** [review]

**Review by novikor — CHANGES_REQUESTED** [review]
image


Please improve your regular expressions:
At the moment, it passes classes which start with a number in case name starts with `\`

**Review by novikor — APPROVED** [review]
Good job

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-4065](https://jira.corp.magento.com/browse/ENGCOM-4065) has been created to process this Pull Request

**Pull request merged**
