### PR TITLE
magento/magento2#30894: Unit test testGetLocaleList fails for non en_…

### LINKED ISSUE #30894: Unit test testGetLocaleList fails for non en_US php default locale
### Preconditions (*)

1. Magento version 2.4.0
2. set intl.default_locale to 'de-DE' in php.ini

### Steps to reproduce (*)

1. run unit test testGetLocaleList in Magento\Framework\Setup\Test\Unit\ListsTest

### Expected result (*)

1. Test passes

### Actual result (*)

1. Test fails with error: Failed asserting that two arrays are equal.

Expected | Actual
------------- | ---------
'en_US' => 'English (United States)' | 'en_US' => 'English (United States)'
'en_GB' => 'English (United Kingdom)' | 'en_GB' => 'English (United Kingdom)'
'uk_UA' => 'Ukrainian (Ukraine)' | 'uk_UA' => 'Ukrainian (Ukraine)'
'de_DE' => 'German (Germany)' | 'de_DE' => 'German (Germany)'
'sr_Cyrl_RS' => 'Serbian (Cyrillic, Serbia)' |
'sr_Latn_RS' => 'Serbian (Latin, Serbia)' |

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by ochnygosch**
…US php default locale

- Use same default locale when getting script name.

### Description (*)

Provide Resolver::DEFAULT_LOCALE to getDisplayScript to use default locale regardless of configured locale

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30894

### Manual testing scenarios (*)

1. Set intl.default_locale to 'de-DE' in php.ini
2. Run all unit tests

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ochnygosch** [comment]
@magento run Unit Tests

**Comment by ochnygosch** [comment]
@magento run all tests

**Comment by ochnygosch** [comment]
@magento run all tests

**Comment by ochnygosch** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @ochnygosch,
As you changed the implementation, not a unit test itself, some use case isn't covered with a unit test.
Could you cover your changes with a unit test?

**Comment by ihor-sviziev** [comment]
Hi @ochnygosch,
I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
