### PR TITLE
Add field to filter to collection

### PR DESCRIPTION
**Pull request by dverkade**
Currently the setup upgrade is looping truth all order addresses and is the checking if the quote_address_id is empty. Changed this so that the collection contains only addresses where the quote_address_id is NULL.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@dverkade thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by orlangur — CHANGES_REQUESTED** [review]
Hi @dverkade, changed code is a one-time operation, do you have any numbers to compare before/after the change on a real store?

Just to be sure there is really some kind of bottleneck here.

**Comment by dverkade** [comment]
Hi @orlangur,

No exact numbers. But when upgrading an Magento instance the upgrade got stuck around this code (store with quite a few orders in it). So when you run the upgrade again it will process all orders which where already processed again, which is not necessary. 

As far as I can see the "quote_address_id" field was always present in the installation schema, so this field might already be filed with data and it's unnecessary to loop truth those records as well. 

And above all the code is more clear and clean.

**Comment by dverkade** [comment]
Hi @orlangur,

Have you been able to review this?

**Comment by magento-engcom-team** [comment]
Hi @dverkade. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.6 release.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
