### PR TITLE
Fix shipping address in BillingAddressManagement

### PR DESCRIPTION
**Pull request by houssems**
set billing address in shipping address.

### CODE REVIEW

**Comment by adragus-inviqa** [comment]
What's this fixing again? Also, what does "Master" mean?

**Comment by houssems** [comment]
It's just to set default address as shipping address if variable ($useForShipping) is set to true in BillingAddressManagement.

**Comment by adragus-inviqa** [comment]
Yes, I saw, but why? Have you stumbled on some weird behaviour/bug?

**Comment by houssems** [comment]
I want it to assign same address as billing, so i found $useForShipping variable in assign function. I didn't found any implementation for this variable, so i added new implementation for this to get it work.

**Comment by aakimov** [comment]
Hello @houssems,

Please sign **Contributor License Agreement** so we can start processing of your pull request.

Thank you for understanding and interest in Magento.

**Comment by houssems** [comment]
Hello aakimov,
When i click to "Sign in with GitHub to agree", it redirect me to github but status of CLA still not signed.

**Comment by aakimov** [comment]
Hello @houssems,

Your **Contributor License Agreement** has been successfully signed.

Returning to your fix, there is definitely a bug in **\Magento\Quote\Model\BillingAddressManagement::assign** method (as you noticed $useForShipping is not taken into account).
Unfortunately your fix does not cover all use cases. Shipping address was supposed to be handled in **\Magento\Quote\Model\Quote\Address\BillingAddressPersister::save** (during quote save), but currently this logic does not work.

We reported internal ticket MAGETWO-57856 for this issue and will fix it properly.
This pull request will be closed.
Thank you for your understanding and your help.

**Pull request closed without merging**
