### PR TITLE
 Fix typo on product details causing Validation error. 

### PR DESCRIPTION
**Pull request by BezV8**
### Description

Fixes a typo on the aria-labeleledby attribute on the product page causing a W3C Validation error.

### Manual testing scenarios

1. Navigate to the view page of any product.
2. Check the code on the W3C html validator.
3. Currently product pages return a "Attribute aria-labeledby not allowed on element div at this point." error as there is a typo in  app/code/Magento/Catalog/view/frontend/templates/product/view/details.phtml

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18522) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
@BezV8 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by nuzil — APPROVED** [review]
Thanks for your contribution

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-3162](https://jira.corp.magento.com/browse/ENGCOM-3162) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @BezV8. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
