### PR TITLE
Fix setup:di:compile failure

### LINKED ISSUE #33595: Updating symfony/console causing setup:di:compile failure
### Preconditions (*)

1.2.4.2-p1
2.Centos 8
3.php 7.4

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.Incompatible argument type: Required type: int. Actual type: string
The name of the upgrade package is not remembered
The following error occurred during compilation
image

### Workaround
The `symfony/console` released version 4.4.29 as a hotfix for Magento issue.
For now, you can run `composer update symfony/console`

Note: the root cause of this issue still not resolved yet

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by ihor-sviziev**
This issue happened when `@param` is not declared for all
parameters of a function

The issue was fixed in the lamias/laminas-code, so we just update it.

Notes:
The research was described here: https://github.com/magento/magento2/issues/33595#issuecomment-888893385
The issue itself was fixed in https://github.com/laminas/laminas-code/pull/95 and released in the https://github.com/laminas/laminas-code/releases/tag/4.4.3

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/614

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/33595

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Review by orlangur — CHANGES_REQUESTED** [review]
Changes LGTM 👍 

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

**Comment by ihor-sviziev** [comment]
Static tests are passing, so I rebased and squashed all changes to single commit.
@magento run all tests

**Review by andrewbess — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, thank you for the review.
[ENGCOM-9227](https://jira.corp.magento.com/browse/ENGCOM-9227) has been created to process this Pull Request
:eight_spoked_asterisk: @andrewbess, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9227](https://jira.corp.magento.com/browse/ENGCOM-9227) has been created to process this Pull Request

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-9227](https://jira.corp.magento.com/browse/ENGCOM-9227) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento give me test instance

**Comment by engcom-Alfa** [comment]
Hi @ihor-sviziev Thanks for your contribution and collaboration!
As discussed, there are conflicts in the PR code, Kindly resolve the conflicts and bring it back to _Ready for testing_ please.
Thanks in advance!

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Due to merge conflicts _Requesting changes_ please!

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@andrewbess, could you help to resolve conflict in the EE repo where I don't have access?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@ihor-sviziev Could you please resolve conflict

**Comment by ihor-sviziev** [comment]
@magento run all tests
@andrewbess, the conflict has been fixed

**Review by andrewbess — APPROVED** [review]

**Pull request merged**
