### PR TITLE
Cleanup ObjectManager usage - Magento_Deploy

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This PR cleanups ObjectManager usage in Magento_Deploy, by removing object manager instantiation from non-api classes

### Fixed Issues (if relevant)

N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
Please note that the 1 of May was a code freeze date for the 2.4.0 release. We should be aware of backward-incompatible changes.

**Comment by Bartlomiejsz** [comment]
Hi @rogyar, I can modify my object manager cleanup PRs to exclude such changes (not sure if this PR will be needed in that case), but I believe according to https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/ such changes are treated as backward-incompatible only for classes marked with `@api`.
In that case, when pointing into 2.4.1 should I not modify constructor arguments in non-api classes, or is it allowed?

**Comment by slavvka** [comment]
For functional CE:
```
15:18:20 [Build Functional CE] + docker exec d4eaf843db8cc653bac4dd6a8a72bfb6e366d7eb46cd2efbd23cb17c32db4c77 /bin/bash -c 'chmod 770 /var/www/html; chown -R magento:magento /var/www/html; cd /var/www/html; sudo -E -u magento find . -type d -exec chmod g+ws {} \; && find . -type f -exec chmod g+w {} \; && chmod u+x bin/magento; sudo -E -u magento /usr/bin/php -f /var/www/html/bin/magento setup:install -vvv --language=en_US --timezone=America/Los_Angeles --currency=USD --db-host=127.0.0.1 --db-name=magento2_prod --db-user=magento --db-password=magento --use-secure=0 --use-secure-admin=0 --use-rewrites=1 --admin-lastname=User --admin-firstname=Admin --admin-email=noreply@magento.com --admin-use-security-key=0 --base-url=http://extfat.devops.magento.com/ --base-url-secure=https://extfat.devops.magento.com/ --backend-frontname=admin --admin-user=admin --admin-password=123123q; sudo -E -u magento bin/magento module:status; sudo -E -u magento rm -f /var/www/html/auth.json; '
15:19:33 [Build Functional CE] 
15:19:33 [Build Functional CE] In Application.php line 597:
15:19:33 [Build Functional CE]                                                                     
15:19:33 [Build Functional CE]   [Symfony\Component\Console\Exception\NamespaceNotFoundException]  
15:19:33 [Build Functional CE]   There are no commands defined in the "setup" namespace.           
15:19:33 [Build Functional CE]                                                                     
15:19:33 [Build Functional CE] 
15:19:33 [Build Functional CE] Exception trace:
15:19:33 [Build Functional CE]   at /var/www/html/vendor/symfony/console/Application.php:597
15:19:33 [Build Functional CE]  Symfony\Component\Console\Application->findNamespace() at /var/www/html/vendor/symfony/console/Application.php:650
15:19:33 [Build Functional CE]  Symfony\Component\Console\Application->find() at /var/www/html/vendor/symfony/console/Application.php:235
15:19:33 [Build Functional CE]  Symfony\Component\Console\Application->doRun() at /var/www/html/lib/internal/Magento/Framework/Console/Cli.php:115
15:19:33 [Build Functional CE]  Magento\Framework\Console\Cli->doRun() at /var/www/html/vendor/symfony/console/Application.php:147
15:19:33 [Build Functional CE]  Symfony\Component\Console\Application->run() at /var/www/html/bin/magento:23
15:19:33 [Build Functional CE] 
15:19:33 [Build Functional CE] 
15:19:33 [Build Functional CE]                                                             
15:19:33 [Build Functional CE]   There are no commands defined in the "module" namespace.  
15:19:33 [Build Functional CE]                                                             
15:19:33 [Build Functional CE] 
[Pipeline] [Build Functional CE] sh
15:19:34 [Build Functional CE] + docker exec d4eaf843db8cc653bac4dd6a8a72bfb6e366d7eb46cd2efbd23cb17c32db4c77 /bin/bash -c 'sudo -E -u magento /var/www/html/bin/magento deploy:mode:set production'
15:19:34 [Build Functional CE] 
15:19:34 [Build Functional CE]                                                                  
15:19:34 [Build Functional CE]   There are no commands defined in the "deploy:mode" namespace.  
15:19:34 [Build Functional CE]                                                                  
15:19:34 [Build Functional CE] 
[Pipeline] [Build Functional CE] sh
15:19:34 [Build Functional CE] + docker exec d4eaf843db8cc653bac4dd6a8a72bfb6e366d7eb46cd2efbd23cb17c32db4c77 /bin/bash -c 'if [ -f /var/www/html/var/log/system.log ]; then sudo -E -u magento cat /var/www/html/var/log/system.log ; fi'
15:19:34 [Build Functional CE] [2020-04-30 20:19:33] main.ERROR: There are no commands defined in the "setup" namespace.
15:19:34 [Build Functional CE] #0 /var/www/html/vendor/symfony/console/Application.php(650): Symfony\Component\Console\Application->findNamespace('setup')
15:19:34 [Build Functional CE] #1 /var/www/html/vendor/symfony/console/Application.php(235): Symfony\Component\Console\Application->find('setup:install')
15:19:34 [Build Functional CE] #2 /var/www/html/lib/internal/Magento/Framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
15:19:34 [Build Functional CE] #3 /var/www/html/vendor/symfony/console/Application.php(147): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
15:19:34 [Build Functional CE] #4 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
15:19:34 [Build Functional CE] #5 {main} [] []
15:19:34 [Build Functional CE] [2020-04-30 20:19:33] main.ERROR: There are no commands defined in the "module" namespace.
15:19:34 [Build Functional CE] #0 /var/www/html/vendor/symfony/console/Application.php(650): Symfony\Component\Console\Application->findNamespace('module')
15:19:34 [Build Functional CE] #1 /var/www/html/vendor/symfony/console/Application.php(235): Symfony\Component\Console\Application->find('module:status')
15:19:34 [Build Functional CE] #2 /var/www/html/lib/internal/Magento/Framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
15:19:34 [Build Functional CE] #3 /var/www/html/vendor/symfony/console/Application.php(147): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
15:19:34 [Build Functional CE] #4 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
15:19:34 [Build Functional CE] #5 {main} [] []
15:19:34 [Build Functional CE] [2020-04-30 20:19:34] main.ERROR: There are no commands defined in the "deploy:mode" namespace.
15:19:34 [Build Functional CE] #0 /var/www/html/vendor/symfony/console/Application.php(650): Symfony\Component\Console\Application->findNamespace('deploy:mode')
15:19:34 [Build Functional CE] #1 /var/www/html/vendor/symfony/console/Application.php(235): Symfony\Component\Console\Application->find('deploy:mode:set')
15:19:34 [Build Functional CE] #2 /var/www/html/lib/internal/Magento/Framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
15:19:34 [Build Functional CE] #3 /var/www/html/vendor/symfony/console/Application.php(147): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
15:19:34 [Build Functional CE] #4 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
15:19:34 [Build Functional CE] #5 {main} [] []
```

**Comment by VladimirZaets** [comment]
Hi, @Bartlomiejsz , thanks for collaboration. Those type of changes (cleanup object manager usage) is not allowed for a patch release. In general, you are right, our strict rule is backward compatibility in @api classes, but we try to do is save as possible, to don't break our customers. It was the decision to deliver this type of change to 2.4.0 (to minor release), cause this type of refactoring really not very valuable, but it is a potential case to break customers. Sorry for that, but we can't accept this PR. If you want to discuss it in more detail feel free to chat me

**Comment by Bartlomiejsz** [comment]
Hi @VladimirZaets, I understand that, I was just wondering which approach is correct but in that case I'll not introduce such changes in PRs sooner than for 2.5.0, thank you

**Pull request closed without merging**
