### PR TITLE
Removed leading backslash in xml

### LINKED ISSUE #29614: [Issue] Removed leading backslash in xml
This issue is automatically created based on existing pull request: magento/magento2#26948: Removed leading backslash in xml

---------
### Description (*)
Removed leading backslash in namespace & class in XML 

`xsi:type="object">\Magento\...
xsi:type="string">\Magento\...
xsi:type="const">\Magento\...
<type name="\Magento\...
type="\Magento\...
<virtualType name="\Magento\...
for="\Magento\...`

is replaced to

`xsi:type="object">Magento\..
xsi:type="string">Magento\...
xsi:type="const">Magento\...
<type name="Magento\...
type="Magento\...
<virtualType name="Magento\...
for="Magento\...`

### Questions or comments
If any please let me know your feedback's

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by srsathish92**
### Description (*)
Removed leading backslash in namespace & class in XML 

`xsi:type="object">\Magento\...
xsi:type="string">\Magento\...
xsi:type="const">\Magento\...
<type name="\Magento\...
type="\Magento\...
<virtualType name="\Magento\...
for="\Magento\...`

is replaced to

`xsi:type="object">Magento\..
xsi:type="string">Magento\...
xsi:type="const">Magento\...
<type name="Magento\...
type="Magento\...
<virtualType name="Magento\...
for="Magento\...`

### Questions or comments
If any please let me know your feedback's

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29614: Removed leading backslash in xml

### CODE REVIEW

**Review by ihor-sviziev — DISMISSED** [review]
Please test on test instance the cases that fails on functional tests, seems that your changes break functionality somehow. It requires additional debug to explain why

**Comment by srsathish92** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @srsathish92. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @srsathish92, here is your [new Magento instance](https://pr-26948.instances.magento-community.engineering).
Admin access: [https://pr-26948.instances.magento-community.engineering/admin_ee88](https://pr-26948.instances.magento-community.engineering/admin_ee88)
Login: `490a6f0a` Password: `62684c25c79d`
Instance will be terminated in up to 3 hours.

**Review by ihor-sviziev — DISMISSED** [review]

**Comment by ihor-sviziev** [comment]
Waiting approval for SVC failure

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7013](https://jira.corp.magento.com/browse/ENGCOM-7013) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @srsathish92,
Could you resolve  merge conflict?

**Comment by srsathish92** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @srsathish92. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @srsathish92, here is your [new Magento instance](https://pr-26948.instances.magento-community.engineering).
Admin access: [https://pr-26948.instances.magento-community.engineering/admin_f6a0](https://pr-26948.instances.magento-community.engineering/admin_f6a0)
Login: `ab6863a8` Password: `3687e8ceb76c`
Instance will be terminated in up to 3 hours.

**Review by ihor-sviziev — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7013](https://jira.corp.magento.com/browse/ENGCOM-7013) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Comment by engcom-Echo** [comment]
Removed only leading backslash

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Oops. closed PR by mistake, re-openede

**Review by ihor-sviziev — DISMISSED** [review]

**Comment by ihor-sviziev** [comment]
Need approval due to SVC failure

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7727](https://jira.corp.magento.com/browse/ENGCOM-7727) has been created to process this Pull Request

**Comment by sidolov** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by sidolov** [comment]
Hi @srsathish92 ! What's the benefits of making such changes? We definitely have `trim($value, '\')` function call during config processing to handle cases with a backslash. On the other side the names of virtual types are changed and anyone who used them may be broken. Maybe I missing something and such changes will improve the dev experience somehow, could you please clarify? Thanks!

**Comment by ihor-sviziev** [comment]
@sidolov I think it’s just a cleanup to have consistency across the platform, as in some places we have backslash, in others we don’t. Also AFAIK different declaration with and without backslash on different scopes has some issues

**Comment by ihor-sviziev** [comment]
@magento run Semantic Version Checker, Functional Tests EE

**Comment by Den4ik** [comment]
@srsathish92 Could you please resolve conflicts

**Comment by srsathish92** [comment]
@Den4ik @ihor-sviziev I have resolved the conflicts, Could you guys please review now.

**Comment by srsathish92** [comment]
@magento run all tests

**Comment by srsathish92** [comment]
@magento run Functional Tests EE, Functional Tests B2B, Semantic Version Checker

**Comment by Den4ik** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by srsathish92** [comment]
@magento run Functional Tests B2B

**Comment by Den4ik** [comment]
@magento run Functional Tests B2B

**Comment by srsathish92** [comment]
@Den4ik @ihor-sviziev Seems Functional Tests B2B frequently got failure and not related to this PR, Can you please have a look?

**Comment by Den4ik** [comment]
@srsathish92 Looks like tests crashed on ajax request and it would be good check response data for place order request.
I'm don't see reasons why it could be related to PR, but it would be good to have details.

@gabrieldagama who could assist with running this tests locally and check response.

**Review by Den4ik — APPROVED** [review]
✅ Approved

Just looked at another PR and see same issue.
Semantic Version Check could be ignored in this case

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-7727](https://jira.corp.magento.com/browse/ENGCOM-7727) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Semantic Version Checker

**Comment by srsathish92** [comment]
@magento run Semantic Version Checker

**Comment by Den4ik** [comment]
I believe that Failed Semantic Version check could be ignored for ES module

**Comment by Den4ik** [comment]
@ihor-sviziev Do you mean merge during prepare Magento release or merging of xml files during app execution?

**Comment by srsathish92** [comment]
> Hi @srsathish92, I did additional research, and it seems like removing leading backslash from the XML files in general - is a good practice, but it might lead to unexpected issues during the upgrade. Reason - in the XML - two nodes
> 
> ```
>     <type name="Magento\AdvancedSearch\Model\Client\ClientResolver">
>         <arguments>
>             <argument name="path" xsi:type="const">Magento\CatalogSearch\Model\ResourceModel\EngineInterface::CONFIG_ENGINE_PATH</argument>
>             <argument name="scopeType" xsi:type="const">Magento\Store\Model\ScopeInterface::SCOPE_STORE</argument>
>         </arguments>
>     </type>
> ```
> 
> and
> 
> ```
>     <type name="\Magento\AdvancedSearch\Model\Client\ClientResolver">
>         <arguments>
>             <argument name="path" xsi:type="const">Some\Another\Path::CONFIG_ENGINE_PATH</argument>
>         </arguments>
>     </type>
> ```
> 
> Will be just merged to something like this (instead of overriding the value):
> 
> ```
>     <type name="Magento\AdvancedSearch\Model\Client\ClientResolver">
>         <arguments>
>             <argument name="path" xsi:type="const">Magento\CatalogSearch\Model\ResourceModel\EngineInterface::CONFIG_ENGINE_PATH</argument>
>             <argument name="scopeType" xsi:type="const">Magento\Store\Model\ScopeInterface::SCOPE_STORE</argument>
>         </arguments>
>     </type>
>     <type name="\Magento\AdvancedSearch\Model\Client\ClientResolver">
>         <arguments>
>             <argument name="path" xsi:type="const">Some\Another\Path::CONFIG_ENGINE_PATH</argument>
>         </arguments>
>     </type>
> ```
> 
> In this case, Magento will use only one of these sections that might lead to unexpected results.
> 
> It's a limitation of XML, so I think it's better not to touch these lines to prevent breaking backward compatibility rather than do this cleanup. I'm closing this Pull Request.
> 
> Thank you so much for your contribution!

@ihor-sviziev Did you tried the viceversa? What will be output? - If it is the same behaviour as aforementioned then we need to update the document somewhere.

**Pull request closed without merging**
