### PR TITLE
Trim all import data

### PR DESCRIPTION
**Pull request by amenk**
### Description

Nobody wants whitespaces in import files. So we rim it.

### Fixed Issues (if relevant)

no reported

### Manual testing scenarios (*)

* import data with whitespaces
* data is trimmed

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by amenk** [comment]
By the way: I tried to accomplish that via a Plugin, but [it is not possible](https://magento.stackexchange.com/questions/272593/i-cant-seem-to-write-an-plugin-for-magento-importexport-model-import-abstractso/272594#272594).

Then I thought, that this should better happen in the, as most data is anyways trimmed at various places.

**Comment by orlangur** [comment]
@amenk this is not needed. Invalid data should be fixed instead (for example, by a custom script trimming all cells beforehand).

**Comment by amenk** [comment]
@orlangur but why?

Spaces do cause problems and there are tons of trim calls in the import. But not everywhere.. so I thought it is good to clean it at the source.

Next, I cannot make a plug-in for the source class. So the other approach would be to plug-in-enable the import source classes. Shall we work towards such a solution instead? I thought it would be Overkill...

**Comment by orlangur** [comment]
@amenk I saw your linked report, I believe instead of hiding a problem by trims here and there it would be nice to add appropriate validations.

**Pull request closed without merging**
