### PR TITLE
[PSR-2 Compliance] The Great @codingStandardsIgnoreFile Massacre

### PR DESCRIPTION
**Pull request by orlangur**
This PR fixes mistake introduced in https://github.com/magento/magento2/commit/004c9bb917b250ae2d6515ec3b96d4099b6f9c2e which resulted in hundreds of files with coding style violations.

### Description

As pointed out in https://github.com/magento/magento2/pull/9251#issuecomment-294478242 manual fixing would take too much time and developer/reviewer efforts. Thus I did exactly what was described in https://github.com/magento/magento2/pull/7166#issuecomment-287712529 to get maximum profit out of existing automated tools.

### Review Notes
Manual commits: https://github.com/orlangur/magento2/commit/a1f9e1adbafc54c981a5d1e18bf68d87db9a1a8c, https://github.com/magento/magento2/commit/40ba673f56e2f45cd05564a0e01b127a9ad4476a, https://github.com/magento/magento2/commit/c87c521bb06696b35f789d595b3e8a4f452e29bc
Automated commits (just repeat steps from commit message instead of manual review): https://github.com/orlangur/magento2/commit/b51681c5db4b639c6996fc1c22fdc642391165ad, https://github.com/magento/magento2/commit/4dc56e0b1d3116821a5e81545f41686c59277be1, https://github.com/magento/magento2/commit/c6194044c158abf8747ea3c5e9699439cbae8278, https://github.com/magento/magento2/commit/d8139743b4888a9d95c3e7a0951f09fe392adf8e
PHPMD on Travis CI was not able to complete within 10 minutes limit thus I checked static tests in two chunks (modules only and all but modules in whitelist): https://travis-ci.org/orlangur/magento2/builds/224861865, https://travis-ci.org/orlangur/magento2/builds/224861991

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by orlangur** [comment]
Now synced and green: https://travis-ci.org/orlangur/magento2/builds/232866106 (integration test failure seems unrelated as it passed in previous run and main branch run), https://travis-ci.org/orlangur/magento2/builds/232587786

**Comment by orlangur** [comment]
@ishakhsuvarov @okorshenko please share your thoughts on current changes.

I'll do re-apply over latest mainline, so that there will be no merge commits, but will preserve old manual commits and any additional required changes will come in separate commits on top of that.

**Comment by okorshenko** [comment]
Hi @orlangur 
Unfortunately it is very hard to verify such big changes. I was trying to stabilize this branch few times, but it is still failing.

Let's do the next. Please, separate each module and each framework component into individual PR. They will be smaller and easier for review and stabilization. 

I will close this PR and will wait for series of PRs based on these changes. Thank you for collaboration.

**Comment by orlangur** [comment]
@okorshenko it was stable at the moment of publishing and I believe it would be pretty easy to re-apply and stabilize again at any moment.

Quote from description:
### Review Notes
Manual commits: https://github.com/orlangur/magento2/commit/a1f9e1adbafc54c981a5d1e18bf68d87db9a1a8c, https://github.com/magento/magento2/commit/40ba673f56e2f45cd05564a0e01b127a9ad4476a, https://github.com/magento/magento2/commit/c87c521bb06696b35f789d595b3e8a4f452e29bc
Automated commits (just repeat steps from commit message instead of manual review): https://github.com/orlangur/magento2/commit/b51681c5db4b639c6996fc1c22fdc642391165ad, https://github.com/magento/magento2/commit/4dc56e0b1d3116821a5e81545f41686c59277be1, https://github.com/magento/magento2/commit/c6194044c158abf8747ea3c5e9699439cbae8278, https://github.com/magento/magento2/commit/d8139743b4888a9d95c3e7a0951f09fe392adf8e

Do you have any concerns regarding manual changes mentioned?

**Comment by okorshenko** [comment]
@orlangur it is almost impossible to review 4k changed files, despite these changes were done automatically. We must to make sure that all changes are secure. I understand your concern, but it will be better to deliver such big changes partially to 2.2 release. Otherwise they will go to 2.3 :(

**Comment by orlangur** [comment]
Hmmm, why need to review automated changes with bare eyes and not just repeat the same commands and then do `git diff`? Used tools are open source and unlikely to contain backdoors or something. 

That was the whole point of my optimization - maximum automatization which minimize code review efforts :) If there is some requirement to review changes manually, such approach simply does not work.

Please correct me if I'm wrong - https://github.com/magento/magento2/pull/8685 had to be fully reviewed manually?

Thanks for the quick feedback, will do my best to get this merged into mainline to the earliest possible release, just want to understand the circumstances.

**Comment by okorshenko** [comment]
@orlangur we created the tool to verify #8685. Some issues were detected by our tool and were fixed manually. Unfortunately, we can't validate this PR in the same way, so it is too risky to accept it without verification. Unfortunately, open source tool are also buggy

**Comment by okorshenko** [comment]
Hi @orlangur 
Would like to proceed with these changes? Please let me know if you are interested in these changes so that we can define the strategy how we can do this together. Thank you

**Comment by okorshenko** [comment]
Here is a good example how we can do this:
https://github.com/magento/magento2/pull/2204#issuecomment-313802145 . As an option that can be a shell file with all required commands inside. So we can run the script per module and deliver changes by small batches
Also we can have you as an author of commits for the future references and history

**Comment by orlangur** [comment]
@okorshenko thanks, at first sight it looks like some commands applied all over the code base (not module batching), please tell me if I'm wrong.

I still believe it can be done pretty easily without small batching (what I would like to avoid: apply `phpcbf` and then `php-cs-fixer` for only some specifically mentioned modules; UPD: sorry, stupid me, we can apply changes all over the codebase but then commit only a part of changes). Also, to avoid massive code changes ever I was thinking of test enforcing `php-cs-fixer` rules similar to `phpcs` one.

I'm going to repeat massacre this weekend, please share if possible whether it fits into 2.2.0 release plan so that efforts are not wasted.

**Comment by okorshenko** [comment]
Hi @orlangur 
I'm not sure that it will go to 2.2 at this time, but that can be a part of 2.3 for sure
We will be able to do this in 2.2.1 as well

**Pull request closed without merging**
