### PR TITLE
[32032][To 2.4-develop] Marked framework interfaces as API part 6

### LINKED ISSUE #32032: Mark framework interfaces as API part 6
The following interfaces should be marked as API in 2.4-develop branch

1. lib/internal/Magento/Framework/Profiler/Driver/Standard/OutputInterface.php
1. lib/internal/Magento/Framework/Search/Adapter/Aggregation/AggregationResolverInterface.php
1. lib/internal/Magento/Framework/Search/Adapter/OptionsInterface.php
1. lib/internal/Magento/Framework/Search/Adapter/Preprocessor/PreprocessorInterface.php
1. lib/internal/Magento/Framework/Search/AdapterInterface.php
1. lib/internal/Magento/Framework/Search/Dynamic/Algorithm/AlgorithmInterface.php
1. lib/internal/Magento/Framework/Search/Request/Aggregation/StatusInterface.php
1. lib/internal/Magento/Framework/Search/Request/IndexScopeResolverInterface.php
1. lib/internal/Magento/Framework/Search/ResponseInterface.php
1. lib/internal/Magento/Framework/Search/SearchEngine/ConfigInterface.php
1. lib/internal/Magento/Framework/Search/SearchEngineInterface.php
1. lib/internal/Magento/Framework/Session/Config/ConfigInterface.php
1. lib/internal/Magento/Framework/Session/SaveHandlerInterface.php
1. lib/internal/Magento/Framework/Session/StorageInterface.php
1. lib/internal/Magento/Framework/Session/ValidatorInterface.php

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixes #32032
### Related Pull Requests

https://github.com/magento/magento2/pull/32172
### Fixed Issues (if relevant)

1. Fixes magento/magento2#32032>

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by danielrussob** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by danielrussob** [comment]
I confirm that this PR is just a code cleanup / marked as API some class. We are waiting for tests.

**Comment by danielrussob** [comment]
I confirm that all files mentioned in issue (https://github.com/magento/magento2/issues/32032) are covered

**Comment by danielrussob** [comment]
Hi @Usik2203 , thank you for your contribution

Can you tell me why you have marked: lib/internal/Magento/Framework/Profiler/Driver/Standard/Stat.php  as API?

It's not linked in: https://github.com/magento/magento2/issues/32032

**Comment by Usik2203** [comment]
> Hi @Usik2203 , thank you for your contribution
> 
> Can you tell me why you have marked: lib/internal/Magento/Framework/Profiler/Driver/Standard/Stat.php as API?
> 
> It's not linked in: #32032
 
Hi @danielrussob  @aleron75 
This class was marked based on this comment 
https://github.com/magento/magento2/pull/32172#pullrequestreview-593490771

Also could i kindly ask you to remove Cleanup label based on this comment
#32735 (comment)

Thanks

**Comment by danielrussob** [comment]
Failed tests are fake positive

**Review by danielrussob — APPROVED** [review]

**Review by aleron75 — APPROVED** [review]

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama the branch with code successfully imported into`magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-32732`.

**Pull request merged**
