### PR TITLE
magento/magento2#: Add better explanation for the “Images File Directory” option

### PR DESCRIPTION
**Pull request by atwixfirster**
### Description (*)

Pull request removes incorrect `<Magento installation>` part from the **Images File Directory** annotation 

and adds more information how to use this option:

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. https://github.com/magento/merchdocs/issues/71

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6161](https://jira.corp.magento.com/browse/ENGCOM-6161) has been created to process this Pull Request
:eight_spoked_asterisk: @dmytro-ch, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @atwixfirster. Could you refresh the information into the translation file? Thanks!

**Comment by atwixfirster** [comment]
> Hi @atwixfirster. Could you refresh the information into the translation file? Thanks!

**done**

Thanks, @engcom-Alfa

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6161](https://jira.corp.magento.com/browse/ENGCOM-6161) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by VladimirZaets** [comment]
Covered in the scope of https://github.com/magento/magento2/pull/25853

**Pull request merged**
