### PR TITLE
Fixed issue 27051: Saving an attribute with backend_type static

### LINKED ISSUE #27051: Saving an attribute with backend_type 'static' will remove the content of the 'frontend_class' field.
### Preconditions (*)

1. Magento Open Source 2.3.3

### Steps to reproduce (*)

1. Navigate to Stores > Attributes > Product
2. Click an attribute with **backend_type** = **static**. Example: **sku** or **category_ids**
3. On the attribute edit page, you can either modify some fields or not modify any field at all.
4. Click "Save and continue edit".

### Expected result (*)

1.**frontend_class** should have the same value as before saving.
2. 
sku-before

### Actual result (*)

1. **frontend_class** is NULL
2. sku-after

### PR DESCRIPTION
**Pull request by jiten-patel**
### Description (*)
Fixed  'frontend_class' field issue while saving an attribute with backend_type 'static'.

### Fixed Issues (if relevant)

1. fixes magento/magento2#27051: Saving an attribute with backend_type 'static' will remove the content of the 'frontend_class' field.

### Manual testing scenarios (*)

1. Navigate to Stores > Attributes > Product
2. Click an attribute with backend_type = static. Example: sku or category_ids
3. On the attribute edit page, you can either modify some fields or not modify any field at all.
4. Click "Save and continue edit".
5. Open Database and select **eav_attribute** table
6. Check **frontend_class** for that attribute

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by jiten-patel** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @jiten-patel. Thank you for your request. I'm working on Magento instance for you

**Review by edenduong — CHANGES_REQUESTED** [review]
Hi @jiten-patel, could you please cover your changes by Unit/Integration Tests? Thank you very much !

**Comment by engcom-Echo** [comment]
I will take care of test coverage.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Review by edenduong — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @edenduong, thank you for the review.
[ENGCOM-7511](https://jira.corp.magento.com/browse/ENGCOM-7511) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@jiten-patel thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Manual testing scenario** from #27051

- Navigate to Stores > Attributes > Product
- Click an attribute with backend_type = static. Example: sku
- On the attribute edit page, you can either modify some fields or not modify any field at all.
- Click "Save and continue edit".

**Result:**

- frontend_class has the same value as before saving

image

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Review by slavvka — CHANGES_REQUESTED** [review]
@jiten-patel please resolve the conflicts and re-run the tests after the upgrade to PHP 7.4

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Review by edenduong — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @edenduong, thank you for the review.
[ENGCOM-7511](https://jira.corp.magento.com/browse/ENGCOM-7511) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@jiten-patel thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Navigate to Stores > Attributes > Product;
2. Click an attribute with backend_type = static. Example: **SKU**;
3. On the attribute edit page, you can either modify some fields or not modify any field at all;
4. Click "**Save**";
5. Open Database and select `eav_attribute` table;
6. Check `frontend_class` for that attribute;

**Before:** `frontend_class` has value NULL

screenshot_26

**After:** :heavy_check_mark: `frontend_class` has the same value as before saving

screenshot_25

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Pull request merged**
