### PR TITLE
Remove X-Frame-Options from pub/.htaccess

### LINKED ISSUE #29728: [Issue] Remove X-Frame-Options from pub/.htaccess
This issue is automatically created based on existing pull request: magento/magento2#29716: Remove X-Frame-Options from pub/.htaccess

---------
### Description (*)
+ Removed due to duplicate headers
+ Got removed from .htaccess in https://github.com/magento/magento2/commit/f831931213b8e55d275c17a76a21a4a53a671eeb#diff-8052c42ab3b8aa06a3f5f788a4ddccc2
+ Is being set by the app, configured in env.php https://devdocs.magento.com/guides/v2.4/config-guide/secy/secy-xframe.html#implement-x-frame-options

### Manual testing scenarios (*)
1. Configure X-Frame-Options in `env.php`
2. Run `curl -I -v --location-trusted '<your Magento storefront URL>'`
3. Search for `X-Frame-Options` 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by Ig0r-M-magic42**
### Description (*)
+ Removed due to duplicate headers
+ Got removed from .htaccess in https://github.com/magento/magento2/commit/f831931213b8e55d275c17a76a21a4a53a671eeb#diff-8052c42ab3b8aa06a3f5f788a4ddccc2
+ Is being set by the app, configured in env.php https://devdocs.magento.com/guides/v2.4/config-guide/secy/secy-xframe.html#implement-x-frame-options

### Manual testing scenarios (*)
1. Configure X-Frame-Options in `env.php`
2. Run `curl -I -v --location-trusted '<your Magento storefront URL>'`
3. Search for `X-Frame-Options` 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29728: Remove X-Frame-Options from pub/.htaccess

### CODE REVIEW

**Comment by Ig0r-M-magic42** [comment]
> Hi @Ig0r-M-magic42. Thank you for your contribution. I'm not sure we can easily remove this setting from .htaccess without bringing potential issues. Some existing server configurations may rely on this setting (the mentioned configurations don't have X-Frame-Options set in the `env.php`). As a result, the security of such setups will be compromised.

Hello @rogyar, given it was removed from `.htaccess` then i supposed it's safe to remove from `pub/.htaccess` as well, though your comment makes sense as well. Do you think it is still unsafe to merge this work into `2.4-develop` branch ? Maybe it's worth over-viewing how application sets it in `env.php` in the first place and update functionality to enforce it to safe in `env.php` ?

**Comment by rogyar** [comment]
Hi @Ig0r-M-magic42. By this modification, we are changing the default system behavior. Such changes might be introduced for a minor version (i.e. 2.5). Let's leave this decision for POs.

I'm going to change the status of this PR correspondingly. We will need to wait for a response for some time. 

Thank you!

**Comment by sidolov** [comment]
@magento create issue

**Comment by rogyar** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-29716.instances.magento-community.engineering).
Admin access: [https://pr-29716.instances.magento-community.engineering/admin_9e8f](https://pr-29716.instances.magento-community.engineering/admin_9e8f)
Login: `4aff1741` Password: `888ef9b35853`
Instance will be terminated in up to 3 hours.

**Comment by Ig0r-M-magic42** [comment]
closing due to both inactivity and i do believe this was actioned.

**Pull request closed without merging**
