### PR TITLE
Fix #13652. Mini cart - fix issue in product title with special chars.

### LINKED ISSUE #13652: Issue in product title with special chars in mini cart
### Preconditions

1. Magento 2.2.2 version
2. Php version 7, Linux
3. default Luma theme

### Steps to reproduce

1. create a product titled Fusion Backpack &trade;
2. go to front end the product title comes up correctly as Fusion Backpack ™ then add it to cart
3. in the mini cart it shows it as Fusion Backpack &trade; and not converting &trade; to ™

### Expected result

1. Mini cart should also show the correct product title after converting the html equivalent to characters

### Actual result

1. errr

### PR DESCRIPTION
**Pull request by afirlejczyk**
Fix showing product name with special chars in mini cart.

### Description

This code was used in html template to show product name  
```
<a data-bind="attr: {href: product_url}, text: product_name"></a>
```

I replaced it with:
```
<a data-bind="attr: {href: product_url}, html: product_name"></a>
```

### Fixed Issues (if relevant)
1. magento/magento2#13652: Issue in product title with special chars in mini cart

### Manual testing scenarios
<ol>
<li>Create a product titled Fusion Backpack &trade;</li>
<li>Go to frontend, the product title comes up correctly as Fusion Backpack ™ then add it to cart</li>
<li>Open the mini cart - product title should be display correctly as Fusion Backpack ™ </li>
</ol>

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=13802) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
@afirlejczyk thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by dmanners** [comment]
Hi @afirlejczyk thank you for this pull request. Could you please have a look through the docs on adding new constructor arguments. http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/index.html#adding-a-constructor-parameter

For your example I think that escaper should be an optional parameter and also be the last item in the constructor so as to not break any other code that already extends this class.

```
public function __construct(
    \Magento\Catalog\Helper\Image $imageHelper,
    \Magento\Msrp\Helper\Data $msrpHelper,
    \Magento\Framework\UrlInterface $urlBuilder,
    \Magento\Catalog\Helper\Product\ConfigurationPool $configurationPool,
    \Magento\Checkout\Helper\Data $checkoutHelper,
    \Magento\Framework\Escaper $escaper = null
) {
$this->escaper = $escaper ?: \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\Escaper::class);
```

**Review by dmanners — CHANGES_REQUESTED** [review]
Please update the new constructor parameter to make our guidelines http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/index.html#adding-a-constructor-parameter

**Comment by afirlejczyk** [comment]
Hi @dmanners 
Thank you for the review.

I've updated the code, but I have one question.
Should I only update constructor in app/code/Magento/Checkout/CustomerData/DefaultItem.php  ?

I also update constructor in classes which extends DefaultItem.php class (app/code/Magento/GroupedProduct/CustomerData/GroupedItem.php, app/code/Magento/ConfigurableProduct/CustomerData/ConfigurableItem.php) but in this case it is not necessary.

I don't know which solution would be best.

**Comment by dmanners** [comment]
Hi @afirlejczyk thank you for this update.

I would update all the constructors like you have done. This means in a future major release we can update them so they are required constructor and the code will already be in place to handle such a change.

**Review by dmanners — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmanners, thank you for the review.
[ENGCOM-861](https://jira.corp.magento.com/browse/ENGCOM-861) has been created to process this Pull Request

**Pull request merged**
