### PR TITLE
Fix issue #24635: Use of undefined constant GLOB_BRACE in dependency …

### PR DESCRIPTION
**Pull request by vidyli**
Fix issue #24635: Use of undefined constant GLOB_BRACE in dependency …

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magneto run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @vidyli,
From the first look - everything looks good. Let's wait for the test results.
Could you meanwhile accept Adobe CLA, otherwise unfortunately we will not be able to accept your PR?

Also, could you update the composer.lock file using composer update?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by vidyli** [comment]
@ihor-sviziev, sure, 1 moment.

**Comment by vidyli** [comment]
@ihor-sviziev,  sorry, force pushed, I have to create another one.

**Pull request closed without merging**
