### PR TITLE
RequireJS resolver sometimes fails to detect blocked resources

### LINKED ISSUE #28116: RequireJS resolver sometimes fails to detect blocked resources
### Preconditions (*)
1. Magento `2.3.5-p1`. Most likely any recent release would be affected.

### Steps to reproduce (*)
1. Create a custom [RequireJS config](https://requirejs.org/docs/api.html#config) which defines a component complete with its url and [fallback path](https://requirejs.org/docs/api.html#pathsfallbacks). For example:
```js
var config = {
    paths: {
        a: ['https://example.com/advertisement.js', 'Custom_Module/js/noop']
    }
};
```
2. Include this component on Checkout (may be reproducible elsewhere)
<details>

```html
<!-- Something simple like this would work: -->
<script type="text/x-magento-init">
    {
        "*": {
            "a": {}
        }
    }
</script>
```

</details>

3. Use a browser with any aggressive Ad Blocker extension which would block the required url
4. Open Checkout page

### Expected result (*)
1. ✅ Ad Blocker extension blocks the script download from the url stated in RequireJS config (`https://example.com/advertisement.js`) 
1. ✅ Checkout page loads and renders just fine

### Actual result (*)
1. ✅ Ad Blocker Extension blocks script download from the original url
2. ℹ️ RequireJS uses [path fallback](https://requirejs.org/docs/api.html#pathsfallbacks) mechanism to load a resource from second url, therefore not triggering an error.
3. ℹ️ Magento's [RequireJS resolver](https://github.com/magento/magento2/blob/6b6f428c4b938c209658eb5d75d84b72503cbce0/lib/web/mage/requirejs/resolver.js#L36) cannot keep track of such events and continues to wait for original resource to load (as no error was produced), therefore not calling any of the [callbacks](https://github.com/magento/magento2/blob/6b6f428c4b938c209658eb5d75d84b72503cbce0/app/code/Magento/Checkout/view/frontend/web/js/checkout-loader.js#L26).
4. ❌ Checkout page is displaying 2 spinning loaders and a fully rendered page under it as resolver does not track components which were loaded via fallbacks.

### PR DESCRIPTION
**Pull request by ishakhsuvarov**
### Description (*)
Under certain circumstances Magento's RequireJS resolver would not correctly detect that all resources on the page were loaded or handled appropriately and cause "infinite loader" conditions. This can possibly be reproduced on Checkout

Also, it's sometimes possible to reproduce this condition by having `magento/module-data-services` module installed and using `uBlock origin` adblocker.

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
Fixes magento/magento2#28116

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by slavvka** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @ishakhsuvarov,
Your changes looks good to me. Could you fix static tests and cover your change with js unit test?

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@ishakhsuvarov will you be able to update your PR?

**Comment by ihor-sviziev** [comment]
@engcom-Charlie @engcom-Kilo @engcom-Golf could you help with test coverage, it seems to me as really important fix.

Thank you!

**Comment by ihor-sviziev** [comment]
@engcom-Kilo any updates on it?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7914](https://jira.corp.magento.com/browse/ENGCOM-7914) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

A manual scenario was used to test the issue #28116

**Before:** 

:heavy_check_mark: Ad Blocker Extension blocks script download from the original url

:heavy_multiplication_x: Checkout page is displaying 2 spinning loaders and a fully rendered page under it as resolver does not track components which were loaded via fallbacks.

Peek 2020-09-21 10-19

**After:**

:heavy_check_mark:  Ad Blocker extension blocks the script download from the url stated in RequireJS config (`https://example.com/advertisement.js`)

:heavy_check_mark:  Checkout page loads and renders just fine

Peek 2020-09-21 10-27

**Pull request merged**
