### PR TITLE
31489-shopping cart rules do not applied fix

### LINKED ISSUE #31489: ShippingCartAddress available_shipping_methods wrong amount (shopping cart rules do not applied)
### Precondition:

- Magento 2.4.1.
- Sample data.
- Cart Price Rule "Spend $50 or more - shipping is free!" is active.
- Shipping method "Table Rate" is enabled
(vanilla Magento with sample data is configured as well)

### Steps to reproduce
1. mutation createEmptyCart

2. mutation addSimpleProductsToCart
```
  addSimpleProductsToCart(
    input: {
      cart_id: <CART_ID>
      cart_items: [
        {
          data: {
            quantity: 2
            sku: "24-MB04"
          }
        }
      ]
    }
  ) {...}

```
3. mutation setShippingAddressesOnCart
```
  setShippingAddressesOnCart(
    input: {
      cart_id: <CART_ID>
      shipping_addresses: [
        {
          address: {
            firstname: "Bob"
            lastname: "Roll"
            company: "Magento"
            street: ["Magento Pkwy", "Main Street"]
            city: "Austin"
            region: "TX"
            postcode: "78758"
            country_code: "US"
            telephone: "8675309"
            save_in_address_book: false
          }
        }
      ]
    }
  ) {...}
}
```

4. Get available shipping methods list 
```
  query cart(cart_id: <CART_ID>) {
    shipping_addresses {
      available_shipping_methods {
        available
        carrier_code
        carrier_title
        error_message
        method_code
        method_title
        amount {
          currency
          value
        }
        price_excl_tax {
          value
          currency
        }
        price_incl_tax {
          value
          currency
        }
      }
    }
  }
```

### Expected result
The shipping amount for "Table Rate" method should be $0 as on Luma theme
Shopping-Cart

### Actual result
"Table Rate" method amount is $15
Desktop-screenshot

### Possible fix
It works well for me when I add row:
```
$address = $cart->getShippingAddress();
```
before line https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/QuoteGraphQl/Model/Resolver/ShippingAddress/AvailableShippingMethods.php#L74

### PR DESCRIPTION
**Pull request by KrishnaK-Z**
### Description (*)

ShippingCartAddress available_shipping_methods wrong amount (shopping cart rules do not applied)

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31489

### Manual testing scenarios (*)

1. Sample data.
2. Cart Price Rule "Spend $50 or more - shipping is free!" is active.
3. Shipping method "Table Rate" is enabled.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by KrishnaK-Z** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
Hi, @KrishnaK-Z @OleksiyOleksiyovych can you confirm this issue still reproducible on 2.4.2?

Thanks!

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests B2B

**Comment by ishakhsuvarov** [comment]
@magento run WebAPI Tests

**Pull request closed without merging**
