### PR TITLE
Category 'image' attribute type implementation to work with any attribute code

### PR DESCRIPTION
**Pull request by allanpaiste**
Currently it's not possible to create an 'image' EAV attribute for category as the code in many places has been hardcoded to talk only with attribute that is explicitly been named 'image'.

This PR addresses that problem by steering the code towards more generic approach to the whole situation by detecting all matching attributes via backendModel check.

Related issue: https://github.com/magento/magento2/issues/5438

### CODE REVIEW

**Comment by ashishjob0424** [comment]
Great job allanpaiste, vkorotun thanks for the update.

**Comment by aeno** [comment]
@allanpaiste, how could I apply this patch in an existing Magento 2.1 install?

**Comment by allanpaiste** [comment]
add this to your composer json:

``` json
{

    "require": {
        "cweagans/composer-patches": "~1.4.0",
    },

    "extra": {
        "patches": {
            "magento/module-catalog": {
                "Fix: https://github.com/magento/magento2/issues/5438": "patches/Patch-Magento_Catalog-M2.1.0-image-attribute-backend-model-hardcoded-attribute-code-removal.patch"
            },
            "magento/module-ui": {
                "Fix: https://github.com/magento/magento2/issues/5438": "patches/Patch-Magento_Ui-M2.1.0-allow-backend-to-know-the-origin-input-of-the-upload-request.patch"
            },
        }
    }

}
```

And add these ...
1. https://github.com/allanpaiste/magento2-patches/blob/master/Patch-Magento_Catalog-M2.1.0-image-attribute-backend-model-hardcoded-attribute-code-removal.patch
2. https://github.com/allanpaiste/magento2-patches/blob/master/Patch-Magento_Ui-M2.1.0-allow-backend-to-know-the-origin-input-of-the-upload-request.patch

... to your <project_root>/patches folder

**Comment by aeno** [comment]
Thanks, that worked. :+1:

**Comment by malviyaharishankar** [comment]
@allanpaiste Can you please tell me the steps to apply the patches or can provide reference from where i can implement it on my setup.

**Comment by allanpaiste** [comment]
The patches have been created to be used for composer M2 projects.

So if you have used steps described at http://devdocs.magento.com/guides/v2.0/install-gde/prereq/integrator_install.html, you should have a M2 project that has composer.json at it's core that dicrates which packages are installed.
1. In project root folder: composer require cweagans/composer-patches=~1.4.0
2. Copy the patches you want to use under /patches
3. the project composer.json should also already have an "extra" key defined. if you add new sub-key there called "patches" (see above), then the next time you do "composer update", the modules that have patches defined will be re-installed and patches applied. Patches have file-target paths that are relative to composer packages which means that the context defined in composer.json is pretty important and patches are not directly appliable in context on magento/magento2 repository, but they're ripe to be used for composer project.

**Comment by ashishjob0424** [comment]
@allanpaiste Patch works for me also, only changes i need to make in my composer is 

```
"extra": {
        "patches": {
            "magento/module-catalog": {
                "Fix: https://github.com/magento/magento2/issues/5438": "patches/Patch-Magento_Catalog-M2.1.0-image-attribute-backend-model-hardcoded-attribute-code-removal.patch"
            },
            "magento/module-ui": {
                "Fix: https://github.com/magento/magento2/issues/5438": "patches/Patch-Magento_Ui-M2.1.0-allow-backend-to-know-the-origin-input-of-the-upload-request.patch"
            }
        },
    }
```

Position of "," is changed as compared to your code.

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Category-image-attribute-type-implementation-to-work-with-any/idi-p/45023).

**Comment by allanpaiste** [comment]
Funny how a fully-working pull-request fix with references to issue report that clearly indicates that this is a bug got moved to clunky-looking "Feature request" forum. Is "being able to use 'image' attribute type for other attributes than just for attribute with code 'image'" really a feature?

C'mon core team.

**Comment by alessandrozucca** [comment]
I'm having the same issue on Magento EE 2.1.1. I'll try your patch @allanpaiste

**Comment by rzwinge** [comment]
I have running 2.1.2
After composer update, i get following log

Gathering patches for root package.
Removing package magento/module-ui so that it can be re-installed and re-patched.
  - Removing magento/module-ui (100.1.1)
Removing package magento/module-catalog so that it can be re-installed and re-patched.
  - Removing magento/module-catalog (101.0.2)
Loading composer repositories with package information
Updating dependencies (including require-dev)                                                    
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Installing magento/module-ui (100.1.1)
    Loading from cache

  - Applying patches for magento/module-ui
    patches/Patch-Magento_Ui-M2.1.0-allow-backend-to-know-the-origin-input-of-the-upload-request.patch (Fix: https://github.com/magento/magento2/issues/5438)
   Could not apply patch! Skipping.

  - Installing magento/module-catalog (101.0.2)
    Loading from cache

  - Applying patches for magento/module-catalog
    patches/Patch-Magento_Catalog-M2.1.0-image-attribute-backend-model-hardcoded-attribute-code-removal.patch (Fix: https://github.com/magento/magento2/issues/5438)
   Could not apply patch! Skipping.

It skips the patches. Any idea?

Thanks for help.

**Comment by rzwinge** [comment]
Hello,
i installed the patches.
But i get the same error in the backend.
I use 2.1.2
Here my files:

category_form.yml
`<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    <fieldset name="extended">
        <argument name="data" xsi:type="array">
            <item name="config" xsi:type="array">
                <item name="label" xsi:type="string">Erweitert</item>
                <item name="collapsible" xsi:type="boolean">true</item>
            </item>
        </argument>
        <field name="image_small_category">
          <argument name="data" xsi:type="array">
            <item name="config" xsi:type="array">
                <item name="dataType" xsi:type="string">string</item>
                <item name="source" xsi:type="string">category</item>
                <item name="label" xsi:type="string" translate="true">Kleines Bild</item>
                <item name="visible" xsi:type="boolean">true</item>
                <item name="formElement" xsi:type="string">fileUploader</item>
                <item name="elementTmpl" xsi:type="string">ui/form/element/uploader/uploader</item>
                <item name="previewTmpl" xsi:type="string">Magento_Catalog/image-preview</item>
                <item name="required" xsi:type="boolean">false</item>
                <item name="sortOrder" xsi:type="number">41</item>
                <item name="uploaderConfig" xsi:type="array">
                    <item name="url" xsi:type="url" path="catalog/category_image/upload"/>
                </item>
            </item>
          </argument>
        </field>
        <field name="image_logo_category">
          <argument name="data" xsi:type="array">
            <item name="config" xsi:type="array">
                <item name="dataType" xsi:type="string">string</item>
                <item name="source" xsi:type="string">category</item>
                <item name="label" xsi:type="string" translate="true">Logo Bild</item>
                <item name="visible" xsi:type="boolean">true</item>
                <item name="formElement" xsi:type="string">fileUploader</item>
                <item name="elementTmpl" xsi:type="string">ui/form/element/uploader/uploader</item>
                <item name="previewTmpl" xsi:type="string">Magento_Catalog/image-preview</item>
                <item name="required" xsi:type="boolean">false</item>
                <item name="sortOrder" xsi:type="number">42</item>
                <item name="uploaderConfig" xsi:type="array">
                    <item name="url" xsi:type="url" path="catalog/category_image/upload"/>
                </item>
            </item>
          </argument>
        </field>
    </fieldset>
</form>
`

Install.php
`public function install(ModuleDataSetupInterface $setup, ModuleContextInterface $context) {
        $setup->startSetup();

        $eavSetup = $this->eavSetupFactory->create(['setup' => $setup]);

        $eavSetup->addAttribute(
            \Magento\Catalog\Model\Category::ENTITY,
            'image_small_category',
            [
                'type' => 'varchar',
                'label' => 'Kleines Bild',
                'input' => 'image',
                'backend' => 'Magento\Catalog\Model\Category\Attribute\Backend\Image',
                'sort_order' => 100,
                'global' => \Magento\Catalog\Model\ResourceModel\Eav\Attribute::SCOPE_GLOBAL,
                'group' => 'Extended',
                'visible'      => true,
                'required'     => false,
                'user_defined' => false
            ]
        );
        $eavSetup->addAttribute(
            \Magento\Catalog\Model\Category::ENTITY,
            'image_logo_category',
            [
                'type' => 'varchar',
                'label' => 'Logo Bild',
                'input' => 'image',
                'backend' => 'Magento\Catalog\Model\Category\Attribute\Backend\Image',
                'sort_order' => 110,
                'global' => \Magento\Catalog\Model\ResourceModel\Eav\Attribute::SCOPE_GLOBAL,
                'group' => 'Extended',
                'visible'      => true,
                'required'     => false,
                'user_defined' => false
            ]
        );

        $setup->endSetup();
    }`

**Comment by benathey** [comment]
when i run composer update, applying patches fails. It says "Could not apply patch! Skipping." for the the two patches. Need help.

**Comment by baldwin-romania** [comment]
@allanpaiste I set the patches as you suggested, but when i try to upload my custom image attribute for category it returns a 404 response on the POST

**Comment by danny-balance** [comment]
Hi, will this be fixed in the next release?

**Comment by allanpaiste** [comment]
I'm not sure if I find the time to keep up with the changes done to the master branch. I'm not sure if I'm even all that motivated when there's no real guarantee that it will ever be merged :/

**Comment by kilis** [comment]
Installed patch and it worked sort of. Wanted to add upload ui component in product_form
I am getting this error now on version 2.1.3
> Notice: Undefined index: in vendor/magento/framework/File/Uploader.php on line 545

**Comment by allanpaiste** [comment]
Hi. Have not tested it on product page as it's Category/Attribute type - I would not have high hopes on it working with products without any modifications + considering that the model itself belongs to category entity - it probably should not be allowed to work. The undefined index error is still quite saddening though :( Seems to be happening when the code iterates through $_FILES

**Comment by kilis** [comment]
Interesting. Looking at the core even image upload isn't made with ui_component product_form.xml and it's implemented differently.

**Comment by maghamed** [comment]
Current pull request has been processed and merged into 2.2 mainline branch
@allanpaiste  thanks for collaboration!

**Review by maghamed — APPROVED** [review]

**Comment by mzenner1** [comment]
I'm a little fuzzy on the comment above saying that this pull request has been processed and merged into 2.2 mainline branch.  Does this mean that the patch will be included in Magento 2.2 (whenever it's released)?

Also, I'm running 2.1.6 and the patch is not applying.  Saying this:

Deprecation Notice: The callback cweagans\Composer\Patches::postInstall declared at /var/www/vhosts/acespirits.com/httpdocs/vendor/cweagans/composer-patches/src/Patches.php accepts a Composer\Script\PackageEvent but post-package-install events use a Composer\Installer\PackageEvent instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///usr/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:320

Any ideas on how to apply this patch to 2.1.6?

**Comment by judaschwartz** [comment]
will this ever be implemented? how can i patch it on to an existing magneto 2.1.6 store?

**Comment by Ruko2010** [comment]
I try to apply this patch to 2.1.7, but composer says "Could not apply patch! Skipping." Any help on that??

**Pull request closed without merging**
