### PR TITLE
composer version updated as suggested in #19529

### PR DESCRIPTION
**Pull request by milindsingh1**
### Description (*)

Composer version updated with "^" to support the latest version as in magento 2.3

### Fixed Issues (if relevant)

1. magento/magento2#19529: Issue resolved

### Manual testing scenarios (*)

1. Installation and update check via composer.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19538) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @milindsingh1. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
@milindsingh1 `composer.lock` must be updated as well, isn't it?

Also, please use constraint similar to one in `2.3-develop` and squash changes into a single commit.

**Comment by milindsingh1** [comment]
@orlangur I have updated the composer.lock as suggested via composer
.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3613](https://jira.corp.magento.com/browse/ENGCOM-3613) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@milindsingh1 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by orlangur — CHANGES_REQUESTED** [review]
@milindsingh1, please check if such changes actually fix the problem.

QA report:
```
PR doesn't fix issue #19529
Manual testing scenario:

Install magento
Run
composer require symfony/filesystem:^4.0
 Package installation failed
```

**Comment by orlangur** [comment]
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

**Pull request closed without merging**
