### PR TITLE
Password Reset: Fix 'Notice: Undefined offset: 0'

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
This Pull Request resolves a common issue reported for different environments by Sentry:
```
ErrorException: Notice: Undefined offset: 0
  File "/cache/vendor/magento/module-customer/Model/ForgotPasswordToken/GetCustomerByToken.php", line 87, in Magento\Customer\Model\ForgotPasswordToken\GetCustomerByToken::execute
    return $found->getItems()[0];
  File "/cache/vendor/magento/module-customer/Model/AccountManagement.php", line 1203, in Magento\Customer\Model\AccountManagement::validateResetPasswordToken
```

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)

1. Create a new Customer
2. Request new Password Reset
3. Enter link in the email message

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
Actually, after the Code Review, I can see:
1. `setPageSize(1)` (so we should never get more than 1 result)
2. `if(getTotalCount() > 1)` (so it expects more than 1 result)
3. `if($found->getTotalCount() === 0)` (but Magento cannot in proper types - see `\Magento\Framework\Api\Search\SearchResult::getTotalCount` -- no casting!)

https://github.com/magento/magento2/blob/89e83e9a1a72e336d851d9819e630546844e8eb0/app/code/Magento/Customer/Model/ForgotPasswordToken/GetCustomerByToken.php#L60-L85

So it does not matter if more than one token match found, or there's no match -- This always gets to the last step.

**Comment by ihor-sviziev** [comment]
As we agreed, @lbajsarowicz will cover this case with integration test, as it's not really clear why it fails.

**Comment by ihor-sviziev** [comment]
@lbajsarowicz any updates?

**Comment by ishakhsuvarov** [comment]
I have to close this for now as it has not been updated for a long time. 

Please reopen when you start working on it again.

**Pull request closed without merging**
