### PR TITLE
Single backslash in double-quotes

### PR DESCRIPTION
**Pull request by flancer64**
This is wrong string I suppose:

```
"Magento\Framework\Model\AbstractModel"
```

should be 

```
'Magento\Framework\Model\AbstractModel'
```

or 

```
"Magento\\Framework\\Model\\AbstractModel"
```

### CODE REVIEW

**Comment by paales** [comment]
It should be

``` PHP
Magento\Framework\Model\AbstractModel::class
```

**Comment by flancer64** [comment]
Yes, it is much better (y) Thanks @paales

**Comment by paales** [comment]
:)

**Comment by paliarush** [comment]
@flancer64 Thanks for contributing. After recent changes all literal class names were replaced with "::class" usage, not it is the only allowed format and is enforced by static tests.
See cdfbcbdd47597a8752e9765ddb38b9573c417277

**Pull request closed without merging**
