### PR TITLE
[ Wishlist] Fixing the default value when wishlist item quantity isn't defined

### PR DESCRIPTION
**Pull request by eduard13**
### Description (*)
This PR is a follow up of the magento/partners-magento2ee/pull/248, where the quantity may not be passed as an input argument.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)

1. Try adding a product to Wish list without specifying the quantity argument.
2. No error should be thrown

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lenaorobei** [comment]
Hi @eduard13. Should this PR be delivered with magento/partners-magento2ee#248?

**Comment by eduard13** [comment]
Hi @lenaorobei, yes.
Added the related PR.

**Comment by lenaorobei** [comment]
I see that WebAPI Tests are failing and it is definitely related to this change.
Please add `ee` PR as `related` if needed (Related Pull requests section of description).

**Comment by eduard13** [comment]
@lenaorobei the failed WebAPI test is related directly to the `ee` PR (as I ran these tests from there). I may run the tests without the related PR, to have all the builds green.

**Review by BarnyShergold — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @BarnyShergold, thank you for the review.
[ENGCOM-8148](https://jira.corp.magento.com/browse/ENGCOM-8148) has been created to process this Pull Request
:eight_spoked_asterisk: @BarnyShergold, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by BarnyShergold** [comment]
Auto-Tests: Covered

**Pull request merged**
