### PR TITLE
My-account-page-title-extra-space-on-mobile

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Fixed Issues (if relevant)

1. magento/magento2#20723: My account page title extra space on mobile

### Manual testing scenarios (*)

1. My Account page title in mobile view
2. Magento 2.3.x

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sdzhepa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [new Magento instance](https://pr-20725.instances.magento-community.engineering).
Admin access: [https://pr-20725.instances.magento-community.engineering/admin](https://pr-20725.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sdzhepa** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-20725-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20725-2-3-develop.instances.magento-community.engineering/admin](https://i-20725-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
Hello @amol2jcommerce 

During testing, I faced a new issue.
Could you please have a look and fix it?


- **Problem:** _My Account page title loads with extra space but after 3-4 sec jumps to the new position_

**Manual testing scenario:**
1. Go to Storefront on mobile (used real iPhone 5 device)
2. Create new Customer and go to My Account page

**Actual Result:** 
- Title is load with old space
- After several second Title is changing position

See the attached video for more details(using physical device resultat the same)
pr_20725_gif

Thank you for contribution and collaboration!

**Comment by amol2jcommerce** [comment]
Hi @sdzhepa thanks for review.
Please review once I sorted above mention issues.

**Comment by amol2jcommerce** [comment]
Hi @sdzhepa please review.

**Comment by sdzhepa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [new Magento instance](https://pr-20725.instances.magento-community.engineering).
Admin access: [https://pr-20725.instances.magento-community.engineering/admin](https://pr-20725.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by sdzhepa — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, thank you for the review.
[ENGCOM-4028](https://jira.corp.magento.com/browse/ENGCOM-4028) has been created to process this Pull Request

**Comment by sdzhepa** [comment]
Hello @amol2jcommerce 

I have reviewed this PR and put into a delivery queue.


Thank you for quick feedback and contribution!

**Comment by amol2jcommerce** [comment]
Thanks @sdzhepa

**Pull request merged**
