### PR TITLE
sort TranslatedLists by local conventions

### LINKED ISSUE #30670: [Issue] sort TranslatedLists by local conventions
This issue is automatically created based on existing pull request: magento/magento2#30661: sort TranslatedLists by local conventions

---------
### Description (*)
Make locales sorted by locale order.

### Manual testing scenarios (*)
1. Use a German locale
2. Consult any list of countries
3. Find _Österreich_ (Austria): it should be sorted with Oman, not at the bottom

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by Crissov**
### Description (*)
Make locales sorted by locale order.

### Manual testing scenarios (*)
1. Use a German locale
2. Consult any list of countries
3. Find _Österreich_ (Austria): it should be sorted with Oman, not at the bottom

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30670: sort TranslatedLists by local conventions

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Comment by Crissov** [comment]
@magento give me test instance

**Comment by Crissov** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @Crissov,
Could you fix failing static tests and cover your change with any type of automated test?

**Comment by Crissov** [comment]
@magento run Functional Tests EE,Static Tests

**Comment by Crissov** [comment]
@ihor-sviziev I've only added a standard parameter (`SORT_LOCALE_STRING`) to a single call to a standard PHP sorting function (`asort()`). I don't know how I would add any automated tests for that.

**Comment by ihor-sviziev** [comment]
Hi @Crissov,
We need to have test coverage in order not to have this issue again in future. I would recommend to use unit test here if possible.

**Comment by Crissov** [comment]
Testing is necessary. Automated tests are good. This is a trivial change, though, and requiring dedicated tests for it would be absurd.

**Comment by ihor-sviziev** [comment]
Ok, @Crissov, could you at least fix failing static tests for changed files?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by Crissov** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@engcom-Charlie could you help with covering changes with automated test?

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8420](https://jira.corp.magento.com/browse/ENGCOM-8420) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@Crissov thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Comment by Crissov** [comment]
@magento run Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Comment by Crissov** [comment]
oops, sorry, I thought I could safely rename a branch in the web interface

**Comment by Crissov** [comment]
@magento run Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
Hi @Crissov ,@ihor-sviziev 

Thanks for the collaboration & contribution!

### :x: QA not Passed

Österreich (Austria): it should be sorted with Oman, not at the bottom

**Manual Scenario Steps**

1.Use a German locale
2.Consult any list of countries
3.Find Österreich (Austria): it should be sorted with Oman, not at the bottom

**:heavy_check_mark: Expected result After Fix** 

Österreich (Austria) should be sorted with Oman, not at the bottom

**:x: Actual result After Fix** 

Screenshot 2024-03-14 at 8 57 05 PM

Screenshot 2024-03-14 at 8 57 13 PM

**Review by engcom-Delta — CHANGES_REQUESTED** [review]
Österreich (Austria) is not sorted with Oman, it is still at the bottom

**Pull request closed without merging**
