### PR TITLE
Update varnish6.vcl

### PR DESCRIPTION
**Pull request by jonashrem**
move encoding block to the top

### Description (*)
The encoding block inside the varnish vcl should be at the top.

The reason is, that exceptions from varnish are often placed very high. If the exception contains ESI requests, this will fail, if the backend is sending an encoding not understood by varnish (like brotli)

### Related Pull Requests
/

### Fixed Issues (if relevant)
/

### Manual testing scenarios (*)
* enable brotli on webserver
* use an ESI block in a page  wich does not go through the encoding vcl block (like   "/customer"  or "/checkout") 
* 

### Questions or comments
/

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hostep** [comment]
Similar PR from somebody who worked at the Varnish company some years ago: https://github.com/magento/magento2/pull/28894

**Comment by jonashrem** [comment]
@magento run all tests

**Comment by jonashrem** [comment]
> Similar PR from somebody who worked at the Varnish company some years ago: #28894

that one is removing the header logic completely. 

At that time brotli was not spread, but nowdays I wouldn'to go that way.

**Comment by in-session** [comment]
I'm not a Varnish pro but shouldn't an accept encoding for Brotli be included?
https://magento.stackexchange.com/questions/361302/varnish-with-brotli-missing-esi-handling-filtering

**Comment by peterjaap** [comment]
@in-session @jonashrem @hostep this PR proposes to remove it altogether; https://github.com/magento/magento2/pull/28894

**Comment by in-session** [comment]
> @in-session @jonashrem @hostepdiese PR schlägt vor, sie vollständig zu entfernen; #28894

@peterjaap I had already tested the but does not give the Brotli through.

**Comment by jonashrem** [comment]
It would also break ESI when backend is returning brotli completely (it might also work when configuring mod brotli instead)

**Comment by jonashrem** [comment]
@magento run all tests

**Comment by jonashrem** [comment]
@magento run Functional Tests CE

**Comment by jonashrem** [comment]
https://github.com/magento run Functional Tests EE

**Comment by jonashrem** [comment]
@magento run WebAPI Tests

**Comment by jonashrem** [comment]
@magento run Functional Tests EE

**Comment by ihor-sviziev** [comment]
This part was fully removed in https://github.com/magento/magento2/pull/38211, so we can close this task.

**Pull request closed without merging**
