### PR TITLE
REST API multiselect attribute BC break betwen 2.1.8 and 2.3.0

### LINKED ISSUE #21364: REST API multiselect attribute BC break between 2.1.8 and 2.3.0
### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Have a multiselect attribute
2. Update the product data through the REST API and pass an array of IDs as a value for this multiselect attribute

### Expected result (*)

1. Attribute is updated (as it worked in 2.1.8)

### Actual result (*)

1. Error message is returned:

```
{
    "message": "Error occurred during \"custom_attributes\" processing. Attribute \"equipment\" has invalid value. The \"array\" value's type is invalid. The \"string\" type was expected. Verify and try again.",
    "trace": null
}
```

### Workaround
Implode the ids and send them as a string. But it makes your code incompatible with Magento 2.1.8 as it expects an array of ids.

I guess that it is some kind of BC break, because Magento 2.1.8 works in a completely opposite way - it requires an array of IDs and rejects string with a message: `{"message":"Error occurred during \"custom_attributes\" processing. Attribute \"equipment\" has invalid value. Invalid type for value: \"string\". Expected Type: \"string[]\"."}`

Related issue: #6120

### PR DESCRIPTION
**Pull request by engcom-Charlie**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#21364

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Functional Tests B2B

**Review by eduard13 — APPROVED** [review]
Thank you @engcom-Charlie for the fix. Looks good 👍

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**
1.  Create a multi-select attribute

2. Update the product data through the REST API and pass an array of IDs as a value for this multi-select attribute

**Before:** :heavy_multiplication_x: Error occurred during \"custom_attributes\" processing.

Screenshot from 2021-02-04 15-14-13

**After:** :heavy_check_mark: Attribute is updated

Screenshot from 2021-02-04 14-58-21

**Pull request closed without merging**
