### PR TITLE
Fix URL passed to static.php in PHP in-development server

### PR DESCRIPTION
**Pull request by nieltg**
Unresolved static assets are generated by passing some part of URL as `resource=` parameter to `pub/static.php`. But PHP in-development server's router, `router.php`, wrongly passes the parameter.

Instead of `frontend/Magento/luma/en_US/images/logo.svg`, PHP in-development server's router uses `static/frontend/Magento/luma/en_US/images/logo.svg` for `resource=` parameter.

Because of that, resources can't be resolved when Magento runs on PHP in-development server.

### Description

This pull request removes `static/` string from the `resource=` parameter, so `static.php` can generate the specified resource correctly.

This pull request also changes command to start PHP in-development server in the documentation. The previous command in the documentation is:
```
$ php -S 127.0.0.1:8082 -t ./pub/ ./phpserver/router.php
```
which results an error because PHP is unable to find `router.php`.
```
PHP 7.1.13 Development Server started at Thu Jan 25 19:50:01 2018
Listening on http://127.0.0.1:8082
Document root is /mnt/d/Projects/Magento/magento2/pub
Press Ctrl-C to quit.
[Thu Jan 25 19:50:07 2018] PHP Warning:  Unknown: failed to open stream: No such file or directory in Unknown on line 0
[Thu Jan 25 19:50:07 2018] PHP Fatal error:  Unknown: Failed opening required '/mnt/d/Projects/Magento/magento2/pub/./phpserver/router.php' (include_path='.:') in Unknown on line 0
```

### Manual testing scenarios

1. Get a freshly cloned Magento repository.
2. Run `composer install`.
3. Setup Magento using `php bin/magento setup:install` as specified in [the documentation](https://github.com/nieltg/magento2/blob/c4fbc5c115d79b5d69f9ae909700e446422e9976/phpserver/README.md).
4. Start PHP in-development server using `php -S 127.0.0.1:8082 -t ./pub/ ../phpserver/router.php`.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=13361) <br/>All committers have signed the CLA.

**Comment by miguelbalparda** [comment]
This is quite interesting, I'll give it a try tomorrow. Have you seen any reported bugs related to this?

**Comment by nieltg** [comment]
Thank you @miguelbalparda!
Sorry, I haven't checked any reported bugs yet about this problem.

I've just been trying to run Magento on PHP in-development server and found some issues to be fixed. :grin:

**Comment by miguelbalparda** [comment]
pub and phpserver folders are at the same level, why do you use 2 different paths in php -S 127.0.0.1:8082 -t ./pub/ ../phpserver/router.php?

**Comment by miguelbalparda** [comment]
I see what you mean now, my bad.

**Comment by miguelbalparda** [comment]
This seems to be present in 2.2 and 2.1 but removed in https://github.com/magento/magento2/commit/f05a32f3812cd64e22e29ab57d04939aa83d9fa3
Do you remember the reason for the removal @aredridel?

**Comment by magento-engcom-team** [comment]
@nieltg thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by nieltg** [comment]
@magento-engcom-team 
Woah, really? Thank you very much.

**Comment by aredridel** [comment]
@miguelbalparda Removal of what?

**Comment by miguelbalparda** [comment]
Isn't [this](https://github.com/magento/magento2/commit/f05a32f3812cd64e22e29ab57d04939aa83d9fa3#diff-8d04479f90b3e7c0df03bef7067bd2b5L89) you @aredridel?

**Pull request merged**
