### PR TITLE
[Backport 2.1-develop] Remove hardcoding for Magento_Backend::admin in ACL tree

### PR DESCRIPTION
**Pull request by navarr**
This backports a removal of the hardcoding the array index of
Magento_Backend::admin in the resources ACL tree

Original commit 66d19602e9627b2c446dd5445ff62bfbc2eea2b6

### CODE REVIEW

**Comment by navarr** [comment]
cc @paliarush who was assigned to the original ticket

**Comment by dmanners** [comment]
@navarr thanks for this PR. Is there a set of testing steps someplace for this fix?

**Comment by navarr** [comment]
Not straightforward but yes.  If you create a module that has an ACL tree starting with Magento_Adminhtml (instead of Magento_Backend), then edit or create a role - the tree will be empty.

After this patch, the tree will appear.  I had the original PR in the title but changed the title - that would be #4396

**Comment by dmanners** [comment]
Thanks @navarr will try to process this for you.

**Review by dmanners — APPROVED** [review]

**Pull request merged**
