### PR TITLE
magento/magneto2#27570: fixed issue withsue with store id for cash on…

### PR DESCRIPTION
**Pull request by ledian-hymetllari**
### Description (*)

Fixed the issue with store view for cash and delivery method

### Fixed Issues (if relevant)
https://github.com/magento/magento2/issues/27570

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by nuzil — CHANGES_REQUESTED** [review]
Hi @ledian-hymetllari 
1) Can you please check failed tests?
2) Can you please cover this fix with additional test?

**Comment by VladimirZaets** [comment]
Hi @ledian-hymetllari. Thanks for collaboration. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

**Comment by ledian-hymetllari** [comment]
@VladimirZaets can you help me to fix these code tests please?

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
@ledian-hymetllari of course, I rerun tests to see what happens with them. What problem do you need?

**Comment by ledian-hymetllari** [comment]
@VladimirZaets is taking a look into this, as this is not failing due to my changes.

**Comment by ledian-hymetllari** [comment]
@VladimirZaets  any info about this one please?

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7639](https://jira.corp.magento.com/browse/ENGCOM-7639) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
Hi, @VladimirZaets. Could you put an appropriate label for test coverage? Thanks!

**Review by nuzil — CHANGES_REQUESTED** [review]
Hihi
Sorry but I have to ask you to cover with tests this change.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by ledian-hymetllari** [comment]
@nuzil looks like you need to approve this PR to be able to merge it. Could you please check it, please? thank you

**Review by nuzil — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-7639](https://jira.corp.magento.com/browse/ENGCOM-7639) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @nuzil What is the current status of this PR?
Thanks!

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-7639](https://jira.corp.magento.com/browse/ENGCOM-7639) has been created to process this Pull Request

**Review by nuzil — APPROVED** [review]
@swnsma thanks for catch it. Super strange that I do not getting any emails when new comments are appearing

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-7639](https://jira.corp.magento.com/browse/ENGCOM-7639) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

Magento multi-store setup (Main Website Store, Second Website Store)
'Cache on delivery' payment method is enabled

**Manual testing scenario:**

1. Go to Admin->Stores -> Config -> Sales Methods -> Payment Methods -> Cache On Delivery and Change 'Cache on Delivery' method title in the scope of Second Website configurations;
Screenshot from 2020-08-03 11-22-27

2. Place the Order with 'cache on delivery' in the scope of Second Website Store.

Screenshot from 2020-08-03 11-24-25

3. Open order details in Admin Panel

**Before:** :heavy_multiplication_x: The Payment Method name is being used from Default Store scope



**After:** :heavy_check_mark: The Payment Method name is being used from Order Store scope

**Pull request merged**
