### PR TITLE
Fix issue 19796 - Sales Order invoice Update Qty's Button is misaligned

### PR DESCRIPTION
**Pull request by SyntaxKay**
### Description (*)

Magento 2.3-develop
Sales Order invoice Update Qty's Button is misaligned 
### Fixed Issues (if relevant)

1.magento/magento2#19796: Sales Order invoice Update Qty's Button is misaligned

### Manual testing scenarios (*)

1.Login to backend-> Order -> View order
2.Generate Invoice -> Items to Invoice -> Check Update Qty's Button

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by aleron75 — COMMENTED** [review]
With the proposed change, the total column count b/w header (8) and footer(9) differs. 
Is it intentional?

**Comment by SyntaxKay** [comment]
@aleron75 
I was mistaken with column (9) in footer. I just resolved it

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3735](https://jira.corp.magento.com/browse/ENGCOM-3735) has been created to process this Pull Request

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3735](https://jira.corp.magento.com/browse/ENGCOM-3735) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
