### PR TITLE
Changed logic so that _scrollToTopIfVisible is called only if element is in viewport. Previously it was called only when the element was outside it.

### PR DESCRIPTION
**Pull request by oskarolaussen**
### Description (*)
Noticed that _scrollToTopIfVisible was called only if changing element was outside of viewport and thus wasn't working as intended.

### Manual testing scenarios (*)

On product page scroll so that .product.data.items is partially visible.
 Change tab. The whole .product.data.items should scroll into view.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23390) <br/>All committers have signed the CLA.

**Comment by sidolov** [comment]
Hi @oskarolaussen  , looks like you made some commits with email different than in your GitHub profile, please, add email from commits to your profile!
Thank you!

**Comment by oskarolaussen** [comment]
Hi @sidolov! Commits should now be correctly attributed to me.

**Comment by oskarolaussen** [comment]
I reverted _isElementOutOfViewport to how it was originally as it worked correctly. I had my coordinate system mixed up. Sorry! Edited the title and description accordingly.

But the fix for _scrollToTopIfVisible should still be valid.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5362](https://jira.corp.magento.com/browse/ENGCOM-5362) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@oskarolaussen thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by Karlasa** [comment]
@magento-engcom-team I think this PR should be reverted. 
1) It was working as intended before. No need to position screen with each element change. (maybe just function name is odd)
2) fix for this PR introduces more issues on page load with collapsible element that has default state open.

**Comment by vovayatsyuk** [comment]
I'm not happy with this update too.

Now the whole page is jumping each time I click the tab :confused: 
Layered navigation is affected too (As well as all other collapsible elements).

Tabs | Filters
-----|--------
Peek 2019-10-09 11-39 | Peek 2019-10-09 11-41

I think that the `_scrollToTopIfVisible` was written as `_scrollToTopIfNotVisible` intentionally (It was just an invalidly named function). I can't imagine why you would need to scroll the page if the content is already visible.

**Comment by vovayatsyuk** [comment]
p.s. Do you realize that now scroll will not work when the element is outside of the viewport?

**Comment by oskarolaussen** [comment]
I encountered a situation where the previous function caused undesired behaviour and since the name didn't match the logic I decided to "fix" it. As it seems to cause more problems than it fixes I'm fully onboard with reverting this PR. Sorry about the inconvenience.

**Pull request merged**
