### PR TITLE
Refactor massactionView, remove adobe-stock references

### LINKED ISSUE #1733: Remove adobe-stock references from magento2 media-gallery modules
Remove adobe-stock references from magento2 media-gallery modules:
 - app/code/Magento/MediaGalleryUi/view/adminhtml/web/css/source/_module.less
 - app/code/Magento/MediaGalleryUi/view/adminhtml/web/js/grid/massaction/massactionView.js
 - app/code/Magento/MediaGalleryUi/view/adminhtml/web/template/grid/columns/image.html
 - app/code/Magento/MediaGalleryUi/view/adminhtml/web/template/image/image-details.html

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1.Fixes  https://github.com/magento/adobe-stock-integration/issues/1733: Remove adobe-stock references from magento2 media-gallery modules 

### Manual testing scenarios (*)
1. Verify mass action mode from slide panel media gallery and standalone page

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-7975](https://jira.corp.magento.com/browse/ENGCOM-7975) has been created to process this Pull Request

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

Mass action mode works correctly  

Test on Cucumber Studio - https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/3962787

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Pull request merged**
