### PR TITLE
Fix incorrect less escape

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Small changes correct less escape for width element

Before fix can lead to such case

output
width: calc(100% - 13px) <= incorrect value we intend to use

After fix

output
width: calc(100% - 33px) <= correct value
width: calc(100% - (23px + 10px)) 

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Enable date of birth field for customer (require option => optional or required)
2. Go to customer create account at frontend page
3. Check visual UI date input
4. Compare both case static content deploy php vs grunt less compile

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE, Functional Tests CE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9170](https://jira.corp.magento.com/browse/ENGCOM-9170) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@mrtuvn just wonder, why did you close the Pull Request?

**Comment by mrtuvn** [comment]
maybe this changes will duplicate with someone works. @ihor-sviziev

**Pull request closed without merging**
