### PR TITLE
[MFTF] Refactoring AdminValidateShippingTrackingNumberTest

### LINKED ISSUE #31520: [Issue] [MFTF] Refactoring AdminValidateShippingTrackingNumberTest
This issue is automatically created based on existing pull request: magento/magento2#31488: [MFTF] Refactoring AdminValidateShippingTrackingNumberTest

---------
### Description (*)
The test is refactored to improve execution time

### Manual testing scenarios (*)
1. Create an order
2. Create a shipment
3. Add tracking number for the shipment
4. Make assertions

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
The test is refactored to improve execution time

### Manual testing scenarios (*)
1. Create an order
2. Create a shipment
3. Add tracking number for the shipment
4. Make assertions

### Resolved issues:
1. [x] resolves magento/magento2#31520: [MFTF] Refactoring AdminValidateShippingTrackingNumberTest

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8593](https://jira.corp.magento.com/browse/ENGCOM-8593) has been created to process this Pull Request

**Comment by sidolov** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run Functional Tests EE

**Comment by gabrieldagama** [comment]
@magento run Functional Tests EE, Integration Tests

**Comment by gabrieldagama** [comment]
@magento run Functional Tests EE

**Comment by gabrieldagama** [comment]
@magento run Functional Tests EE

**Pull request merged**
