### PR TITLE
#17890: show correct text swatch values per store view

### PR DESCRIPTION
**Pull request by magicaner**
### Description

Show correct text swatches values per store view. 

### Fixed Issues (if relevant)

1. magento/magento2#17890: Magento 2.2.5 Product swatches does not shows correct value for related store view

### Manual testing scenarios

1. Install fresh magento with default simple data
2. Edit swatch values for `size` attribute. 
3. Change value for default store to `XS D`. And for admin store set `XS A`  
image
4. Run bin/magento index:reindex to reindex all indexes
5. Run bin/magento cache:clean block_html full_page
6. Open product view page on frontend SKU=MH01
7. Value of `size` attribute should have `XS D` value instead of `XS A`
image

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=17891) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @magicaner. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-engcom-team** [comment]
@magicaner thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by nuzil — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-2912](https://jira.corp.magento.com/browse/ENGCOM-2912) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @magicaner. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
