### PR TITLE
Add xml declaration for catalog_widget_product_list.xml file

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

Added tag `<?xml version="1.0"?>` to `app/code/Magento/CatalogWidget/view/frontend/layout/catalog_widget_product_list.xml `

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — APPROVED** [review]
The failing tests are not related to the modified code comments

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7176](https://jira.corp.magento.com/browse/ENGCOM-7176) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Pull request merged**
