### PR TITLE
Refactor: Introduce ProductRepositoryInterface

### LINKED ISSUE #29873: [Issue] Refactor: Introduce ProductRepositoryInterface
This issue is automatically created based on existing pull request: magento/magento2#29793: Refactor: Introduce ProductRepositoryInterface

---------

### Description (*)
1. Refactor: Replace `Product` Model factory, then `->load($id)` with `ProductRepository` to follow Magento's Best Practices.
2. Adjust Unit Test
3. Improve Code Style to follow Magento ruleset.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
1. Refactor: Replace `Product` Model factory, then `->load($id)` with `ProductRepository` to follow Magento's Best Practices.
2. Adjust Unit Test
3. Improve Code Style to follow Magento ruleset.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29873: Refactor: Introduce ProductRepositoryInterface

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Unit Tests

**Comment by lbajsarowicz** [comment]
@magento run all tests
@ihor-sviziev As we have all tests green, I'm re-running all the tests to have green on the last commit.

**Review by ihor-sviziev — DISMISSED** [review]
Approved ✔

Note for QA: please compare performance before & after these changes, as using product repository usually adds quite big overhead

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8097](https://jira.corp.magento.com/browse/ENGCOM-8097) has been created to process this Pull Request

**Comment by sidolov** [comment]
@magento create issue

**Review by engcom-Delta — CHANGES_REQUESTED** [review]
Hi @lbajsarowicz . During testing PR I found the issue - images for configurations are not shown on category page.
**Manual testing scenario:**
- Create configurable product with visual swatch attribute
image
image
- Add images to each variation for configurable product
image
- Go to category page
- Click on product swatches

**Result:**
:x: Image is not loaded for product on category page
Peek 2020-09-07 12-26


Could you take a look?

**Comment by lbajsarowicz** [comment]
Yes, I'll handle that next weekend.

**Comment by gabrieldagama** [comment]
The risk was set to`low` due to: the suggested changes shouldn't affect other areas.

**Comment by ihor-sviziev** [comment]
@lbajsarowicz any updates?

**Comment by lbajsarowicz** [comment]
I'm unable to get time to finish that, sorry.

**Pull request closed without merging**
