### PR TITLE
Fixed loading product for specific store by product repository

### PR DESCRIPTION
**Pull request by Tomasz18**
### Description (*)
Added checking if product exists for given store in product resource. If product not exists for given store, product repository will throw an appropriate exception.

### Fixed Issues (if relevant)
1. magento/magento2#23583: \Magento\Catalog\Model\ProductRepository does not respect store scope

### Manual testing scenarios (*)

1. Create two websites - W1 and W2
2. Create two stores (one for each created website) - SW1 and SW2
3. Create two store views (one for each created store) - SVW1 and SVW2
4. Create new product and assign it to website W1
5. In code try to load created product for store view SVW2
```
/** @var ProductRepository $repo */
$repo = ObjectManager::getInstance()->get(ProductRepository::class); // or inject via constructor
$productId = 1; // newly created product ID
$storeId = 3; // SVW2 store ID
$repo->getById($productId, false, $storeId);
```
6. \Magento\Framework\Exception\NoSuchEntityException is thrown

Alternatively
1. Create two websites - W1 and W2
2. Create two stores (one for each created website) - SW1 and SW2
3. Create two store views (one for each created store) - SVW1 and SVW2
4. Create new product and assign it to website W1
5. Go to product edit page (Catalog -> Products -> Edit)
6. Select scope as store view SVW1
7. Change store ID param in URL to SVW2 ID (e.g. https://contribution.local/admin_svusgv/catalog/product/edit/key/69a4e080b5cb7657ba71e1f1f4f8b4bae83a9f95144fdbb0f7342d7c4c0ae11b/id/1/store/3/)
8. See "This product doesn't exist." error message in product listing

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — CHANGES_REQUESTED** [review]
@Tomasz18 could you please sign Adobe CLA and cover changes with automated tests?

**Comment by engcom-Charlie** [comment]
Hi @Tomasz18, can you please look through failed tests and cover your changes automated tests? Otherwise, we can't proceed with your PR.
Thank you.

**Comment by Tomasz18** [comment]
Hi, currently I'm unable to work on this PR, so you can close it for now

**Comment by sidolov** [comment]
@Tomasz18 thank you for your response! Please, feel free to reopen PR in case you want to continue!

**Pull request closed without merging**
