### PR TITLE
[FEATURE] Performance optimisation large shopping carts by preventing…

### LINKED ISSUE #39292: [Issue] [FEATURE] Performance optimisation large shopping carts by preventing…
This issue is automatically created based on existing pull request: magento/magento2#39290: [FEATURE] Performance optimisation large shopping carts by preventing…

---------
… call duplicate getActions

### Description (*)

When you have for example 25 items in your shopping cart and 1 shopping cart rule the getActions is called 26 times but after this update it is called only once.

### Manual testing scenarios (*)

1. Create a Shopping Cart with multiple items
2. Retrieve through GraphQL

```
curl --location 'https://example.com/graphql' \
--header 'store: nl_1' \
--header 'Content-Type: application/json' \
--data '{"query":"query getCartDetails($cartId: String!) {\n                  cart(cart_id: $cartId) {\n                      id\n                      ...CartMinimumFragment\n                  }\n              }\n              \n    fragment CartMinimumFragment on Cart {\n        id\n        total_quantity\n        is_virtual\n        email\n        ...PriceSummaryFragment\n        ...CartItemsFragment\n        ...AppliedCouponsFragment\n    }\n    \n    fragment PriceSummaryFragment on Cart {\n        items {\n            id\n            quantity\n        }\n        ...ShippingFragment\n        prices {\n            ...TaxSummaryFragment\n            ...DiscountSummaryFragment\n            ...GrandTotalFragment\n            subtotal_excluding_tax {\n                currency\n                value\n            }\n            subtotal_with_discount_excluding_tax {\n                currency\n                value\n            }\n            subtotal_including_tax {\n                currency\n                value\n            }\n        }\n    }\n    \n    fragment ShippingFragment on Cart {\n        shipping_addresses {\n            firstname\n            middlename\n            lastname\n            country {\n                code\n            }\n            street\n            city\n            region {\n                code\n            }\n            postcode\n            telephone\n            addressId: customer_address_id\n            selected_shipping_method {\n                carrier_code\n                carrier_title\n                method_code\n                method_title\n                amount {\n                    currency\n                    value\n                }\n            }\n            \n\n        }\n    }\n\n    \n    fragment GrandTotalFragment on CartPrices {\n        grand_total {\n            currency\n            value\n        }\n    }\n\n    \n    fragment TaxSummaryFragment on CartPrices {\n        applied_taxes {\n            amount {\n                currency\n                value\n            }\n            label\n        }\n    }\n\n    \n    fragment DiscountSummaryFragment on CartPrices {\n        discounts {\n            amount {\n                currency\n                value\n            }\n            label\n        }\n    }\n\n\n    \n    fragment CartItemsFragment on Cart {\n        items {\n            id\n            uid\n            errors {\n                code\n                message\n            }\n            product {\n                id\n                name\n                url_key\n                url_suffix\n                sku\n                type_id\n                stock_status\n                product_labels {\n                    code\n                    color\n                    image\n                    label\n                }\n                small_image {\n                    url\n                    label\n                }\n                categories {\n                    name\n                }\n                price {\n                    regularPrice {\n                        amount {\n                            currency\n                            value\n                        }\n                    }\n                }\n                price_tiers {\n                    quantity\n                    final_price {\n                        currency\n                        value\n                        __typename\n                    }\n                    discount {\n                        percent_off\n                        __typename\n                    }\n                    __typename\n                }\n                price_range {\n                    minimum_price {\n                        regular_price {\n                            value\n                            currency\n                        }\n                        final_price {\n                            currency\n                            value\n                        }\n                    }\n                }\n            }\n            prices {\n                price {\n                    currency\n                    value\n                }\n                row_total_including_tax {\n                    currency\n                    value\n                }\n            }\n            quantity\n            ... on ConfigurableCartItem {\n                id\n                options: configurable_options {\n                    id\n                    option_label\n                    value_id\n                    value_label\n                }\n            }\n            ... on GiftCardCartItem {\n                sender_name\n                sender_email\n                recipient_name\n                recipient_email\n                amount {\n                    currency\n                    value\n                }\n                message\n            }\n            ... on BundleCartItem {\n                id\n                bundle_options {\n                    id\n                    label\n                    type\n                    values {\n                        id\n                        label\n                        price\n                        quantity\n                    }\n                }\n            }\n        }\n    }\n\n    \n    fragment AppliedCouponsFragment on Cart {\n        applied_coupons {\n            code\n        }\n    }","variables":{"cartId":"XXXXXXX"}}'
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://gihub.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by lewisvoncken**
… call duplicate getActions

### Description (*)

When you have for example 25 items in your shopping cart and 1 shopping cart rule the getActions is called 26 times but after this update it is called only once.

### Manual testing scenarios (*)

1. Create a Shopping Cart with multiple items
2. Retrieve through GraphQL

```
curl --location 'https://example.com/graphql' \
--header 'store: nl_1' \
--header 'Content-Type: application/json' \
--data '{"query":"query getCartDetails($cartId: String!) {\n                  cart(cart_id: $cartId) {\n                      id\n                      ...CartMinimumFragment\n                  }\n              }\n              \n    fragment CartMinimumFragment on Cart {\n        id\n        total_quantity\n        is_virtual\n        email\n        ...PriceSummaryFragment\n        ...CartItemsFragment\n        ...AppliedCouponsFragment\n    }\n    \n    fragment PriceSummaryFragment on Cart {\n        items {\n            id\n            quantity\n        }\n        ...ShippingFragment\n        prices {\n            ...TaxSummaryFragment\n            ...DiscountSummaryFragment\n            ...GrandTotalFragment\n            subtotal_excluding_tax {\n                currency\n                value\n            }\n            subtotal_with_discount_excluding_tax {\n                currency\n                value\n            }\n            subtotal_including_tax {\n                currency\n                value\n            }\n        }\n    }\n    \n    fragment ShippingFragment on Cart {\n        shipping_addresses {\n            firstname\n            middlename\n            lastname\n            country {\n                code\n            }\n            street\n            city\n            region {\n                code\n            }\n            postcode\n            telephone\n            addressId: customer_address_id\n            selected_shipping_method {\n                carrier_code\n                carrier_title\n                method_code\n                method_title\n                amount {\n                    currency\n                    value\n                }\n            }\n            \n\n        }\n    }\n\n    \n    fragment GrandTotalFragment on CartPrices {\n        grand_total {\n            currency\n            value\n        }\n    }\n\n    \n    fragment TaxSummaryFragment on CartPrices {\n        applied_taxes {\n            amount {\n                currency\n                value\n            }\n            label\n        }\n    }\n\n    \n    fragment DiscountSummaryFragment on CartPrices {\n        discounts {\n            amount {\n                currency\n                value\n            }\n            label\n        }\n    }\n\n\n    \n    fragment CartItemsFragment on Cart {\n        items {\n            id\n            uid\n            errors {\n                code\n                message\n            }\n            product {\n                id\n                name\n                url_key\n                url_suffix\n                sku\n                type_id\n                stock_status\n                product_labels {\n                    code\n                    color\n                    image\n                    label\n                }\n                small_image {\n                    url\n                    label\n                }\n                categories {\n                    name\n                }\n                price {\n                    regularPrice {\n                        amount {\n                            currency\n                            value\n                        }\n                    }\n                }\n                price_tiers {\n                    quantity\n                    final_price {\n                        currency\n                        value\n                        __typename\n                    }\n                    discount {\n                        percent_off\n                        __typename\n                    }\n                    __typename\n                }\n                price_range {\n                    minimum_price {\n                        regular_price {\n                            value\n                            currency\n                        }\n                        final_price {\n                            currency\n                            value\n                        }\n                    }\n                }\n            }\n            prices {\n                price {\n                    currency\n                    value\n                }\n                row_total_including_tax {\n                    currency\n                    value\n                }\n            }\n            quantity\n            ... on ConfigurableCartItem {\n                id\n                options: configurable_options {\n                    id\n                    option_label\n                    value_id\n                    value_label\n                }\n            }\n            ... on GiftCardCartItem {\n                sender_name\n                sender_email\n                recipient_name\n                recipient_email\n                amount {\n                    currency\n                    value\n                }\n                message\n            }\n            ... on BundleCartItem {\n                id\n                bundle_options {\n                    id\n                    label\n                    type\n                    values {\n                        id\n                        label\n                        price\n                        quantity\n                    }\n                }\n            }\n        }\n    }\n\n    \n    fragment AppliedCouponsFragment on Cart {\n        applied_coupons {\n            code\n        }\n    }","variables":{"cartId":"XXXXXXX"}}'
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://gihub.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#39292: [FEATURE] Performance optimisation large shopping carts by preventing…

### CODE REVIEW

**Comment by engcom-Hotel** [comment]
@magento create issue

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
Hi @lewisvoncken,

Thanks for the collaboration & contribution!

✔️ QA Passed
Preconditions:
- Install fresh Magento 2.4-develop

Steps to reproduce
- As per the PR description

Before: ✖️ 
The `$rule->getActions()` method was being called multiple times for each item, even though the result was the same for a given rule.

After: ✔️
The `$rule->getActions()` method is now called only once per rule, by moving the call to the outer loop. This reduces redundant calls and improves performance.

Builds are failed. Hence, moving this PR to Extended Testing.

Thanks

**Comment by engcom-Dash** [comment]
@magento run Static Tests, Integration Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by lewisvoncken** [comment]
@engcom-Dash 
The copyright has been updated

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by lewisvoncken** [comment]
@engcom-Dash 

You must be kidding right?

I have removed the whitespace!

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Unit Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by engcom-Dash** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Dash** [comment]
@magento run Functional Tests CE

**Comment by engcom-Dash** [comment]
@magento run Functional Tests CE

**Comment by engcom-Dash** [comment]
@magento run Functional Tests CE

**Pull request merged**
