### PR TITLE
Fix refund notification registration

### PR DESCRIPTION
**Pull request by schurter-wallee**
The `registerRefundNotification(...)` method tries to register a credit memo, but the `register()` method does not longer exist in the `\Magento\Sales\Model\Order\Creditmemo` class.

### CODE REVIEW

**Comment by Vinai** [comment]
Thank you for the PR! We are currently waiting for the travis builds to work again, which should happen in a few days. Once that is running and the tests are green we can continue to process your contribution. Until then, can you please sign the contributor license agreement?

**Comment by KrystynaKabannyk** [comment]
hello @schurter-cw, can you please update code of the PR and cover it by Travis tests?

**Comment by rikterbeek** [comment]
Hi @Vinai 

Could you please accept the pull request from @schurter-cw  this will solve issues for us as well.

It is difficult to create a credit memo programmatically because the prepareCreditMemo is a protected function what is the best method to use ?

Regards,
Rik

**Comment by rikterbeek** [comment]
@NadiyaS Could you look at my question above ?

**Comment by stevenvdp** [comment]
The travis build is still disabled? Our build server gives this message:

```
Magento\Sales\Test\Unit\Model\Order\PaymentTest::testRegisterRefundNotification
Expectation failed for method name is equal to <string:register> when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.
```

@schurter-cw perhaps you should also update the test in your PR.

**Comment by NadiyaS** [comment]
Hi @schurter-cw, @rikterbeek 
thank you for contribution and we are sorry for delay.
Internal ticket for processing your PR is MAGETWO-47123.

**Comment by alena-marchenko** [comment]
The fix has been delivered to develop branch.
Thank you for contribution!

**Pull request closed without merging**
