### PR TITLE
Fix spelling mistake in AddressTest.php

### PR DESCRIPTION
**Pull request by GitHamo**
Added the T to customer which shouldn't affect the test unit as it sets the customer ID later (Line: 88) but it's better to correct the spelling mistake.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=10806) <br/>All committers have signed the CLA.

**Comment by miguelbalparda** [comment]
Hi @GitHamo! Thank you for your contribution, would you mind signing the CLA so we can process this one?

**Comment by GitHamo** [comment]
Thank you very much for your comments. I wonder how can i include similar changes to enterprise edition?

**Comment by miguelbalparda** [comment]
Are you asking about this very same change or did you find something different in the EE codebase?

**Comment by GitHamo** [comment]
I actually found the issue in EE, confirmed and did the changes to CE.

**Comment by miguelbalparda** [comment]
Very well, thank you very much for that. If I recall correctly there is no direct way to create a PR for the EE code, but I'll ask around and report back.

**Pull request merged**
