### PR TITLE
MC-34456: Related Products can not be added to the Shopping Cart from a Wish List

### LINKED ISSUE #32274: Related Products can not be added to the Shopping Cart from a Wish List
**Preconditions:**

• Magento EE 2.3.5, EE 2.4.0-alpha3{color}  installed
 • A Customer account is created
 • A Configurable Product is created
 • Several Simple products are created and added to the Configurable Product “Related Products”

**Steps to Reproduce:**

• Go to storefront as the created customer
 • Add the Configurable Product to Wish List 
 • Go to the Wish List 
 • Click “Add to Cart” button
 • Choose the Configurable Product’s options
 • Click the {color:#0747a6}“select all” link of the “Related Products” section
 • Click the “Add to Cart” button

**(/) Expected results:**

The Configurable Product and all its related products should be added to the Shopping Cart

**(x) Actual results:**

Only the Configurable Product is added to the Shopping Cart

### PR DESCRIPTION
**Pull request by SmVladyslav**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#32274

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by SmVladyslav** [comment]
@magento run all tests

**Comment by shikhamis11** [comment]
@magento run all tests

**Comment by ankurvr** [comment]
@magento give me 2.4-develop instance

**Comment by SmVladyslav** [comment]
@magento run Functional Tests CE

**Comment by SmVladyslav** [comment]
@magento run Functional Tests EE

**Review by zakdma — APPROVED** [review]

**Review by shikhamis11 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, thank you for the review.
[ENGCOM-8816](https://jira.corp.magento.com/browse/ENGCOM-8816) has been created to process this Pull Request
:eight_spoked_asterisk: @shikhamis11, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by dmitriyprime** [comment]
@magento I am working on this

**Comment by dmitriyprime** [comment]
:heavy_check_mark:  QA passed

**Before:**
before

**After:**
after

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-32275`.

**Pull request merged**
