### PR TITLE
magento/magento2#4389 Widget cache error

### PR DESCRIPTION
**Pull request by AlexandrKozyr**
- fixed CacheKey assignment

### Fixed Issues (if relevant)

1. magento/magento2#4389: Widget cache error

### Manual testing scenarios

1. Install Magento from develop branch.
2. Add two widgets of type 'Catalog Product List' to the 'CMS homepage' at location content.bottom with different titles, but the same conditions. For example, condition could be product price is greater than 0
3. Refresh cache and visit homepage

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=12764) <br/>All committers have signed the CLA.

**Comment by dmanners** [comment]
Thank you for this pull request @AlexandrKozyr I am just wondering if there was any particular reason you went for the template and title rather than using the widget id for the cache key?

**Comment by ishakhsuvarov** [comment]
Hi @AlexandrKozyr 
I am closing this PR for now due to inactivity. Please reopen if you wish to continue at any time.

**Comment by AlexandrKozyr** [comment]
Hi @dmanners. thank u for ur review and remark. I have double checked case and possibility to use id for the widget and found out that there is no separate identity created in the persistent layer with. there are 4 params that creates widgets inside cms block - 
> {{widget type="Magento\CatalogWidget\Block\Product\ProductsList" title="Speciaal geselecteerd" products_count="6" template="product/widget/content/gridspecial.phtml" conditions_encoded="a:2:[i:1;a:4:[s:4:`type`;s:50:`Magento|CatalogWidget|Model|Rule|Condition|Combine`;s:10:`aggregator`;s:3:`all`;s:5:`value`;s:1:`1`;s:9:`new_child`;s:0:``;]s:4:`1--1`;a:4:[s:4:`type`;s:50:`Magento|CatalogWidget|Model|Rule|Condition|Product`;s:9:`attribute`;s:12:`category_ids`;s:8:`operator`;s:2:`==`;s:5:`value`;s:3:`742`;]]"}}

but for some reasons title and template are not inside cahce key. my fix add them as th last possible params for uqiness identification of cache file.

**Comment by magento-engcom-team** [comment]
Hi @AlexandrKozyr. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

**Comment by abhaykhatariya** [comment]
Magento 2.2.5 have same problem with widget cache error. same widget showing twice.

**Comment by ihor-sviziev** [comment]
Hi @abhaykhatariya,
For some reasons these changes weren't added to release 2.2.5. Probably they will be added to on of next releases.
As for now you could apply these changes using composer patches

**Comment by abhaykhatariya** [comment]
@ihor-sviziev Where is the patch ? can you please send me link for that patch
same problem into magento 2.2.5 when we add cms static block using widget

**Comment by ihor-sviziev** [comment]
@abhaykhatariya You can use https://github.com/cweagans/composer-patches or https://github.com/vaimo/composer-patches for applyting patch. In case of this PR you can use following URL as a patch: https://github.com/magento/magento2/pull/12764.patch

**Pull request merged**
