### PR TITLE
Pass empty string if null - Fixes EAV reindex not possible

### LINKED ISSUE #35319: [2.4.4] Product with Salable Qty of 0 shows 'In Stock' on product page
FIX:
A quick non-official hack/fix was posted further below by @loic-paquin and @jas8522 [here](https://github.com/magento/magento2/issues/35319#issuecomment-1111842395)

### Preconditions (*)
1. Upgraded from Magento 2.4.3-p1 to 2.4.4
2. Default Luma Theme or 3rd Party
3. Have backorders turned off (screenshot attached for confirmation that my settings are correct - though they did not change from 2.4.3-p1 where this was not a problem)

### Steps to reproduce (*)
1. Have a product with 0 salable quantity (configurable product)
2. Go to frontend product page and check a variation/configuration (by selecting it)
3. You can click "Add to Cart"

### Expected result (*)
1. It should say "Out of Stock" above SKU and/or you should not be able to select or click the variation swatch.
2. Should not be able to click "Add to Cart" for an "Out of Stock" product (with 0 salable qty).

### Actual result (*)
1. It will allow you to click/select a swatch of an "out of stock" variation
2. It will say "In Stock"
3. Clicking "Add to Cart" it will reload page with error: "There are no source items with the in stock status"
4. The "X in Stock" feature (only X left threshold) shows correctly when it is under my threshold, but does not show on a product that is really out of stock (with selecting the variation). So that function knows not to show because there are 0 in stock. 
5. Running re-index through CLI, I receive the following error (not sure if it's related - **_UPDATE:_** found this to not be related) and made no difference for this problem:

`Product EAV index process error during indexation process: Deprecated Functionality: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /home/********/public_html/vendor/magento/module-catalog/Model/ResourceModel/Product/Indexer/Eav/Source.php on line 444`

My previous installation of 2.4.3-p1 that I just upgraded from, this worked as intended (out of stock variations could not be selected/clicked. It showed a cross-through of the variation that was out of stock). It now does not do this, after upgrading to 2.4.4. 

Below are screenshots of the product page as well as the admin/backend showing 0 for default stock quantity. This example is shown on the stock Magento Luma theme.

magento-244-frontend-instock-bug-product_view
magento-244-frontend-instock-bug-backend_settings

**_EDIT/UPDATE:_**
The original report of EAV indexing (using CLI) failing might be related, was incorrect. It is not related and made no difference for the bug of "Product with Salable Qty of 0 shows 'In Stock' on product page" - they are separate issues.

**Additional Information:**
https://github.com/magento/magento2/issues/35319#issuecomment-1101209973

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by DanieliMi**
### Description (*)

In PHP 8.1 passing `null` as second parameter to `explode()` has been deprecated and stops the EAV index from indexing. This pull request makes sure an empty string is passed instead of null.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35319

### Manual testing scenarios (*)

Precondition: PHP 8.1

1. Create a multiselect attribute
2. Select values for it on a product
3. Save the product
4. Remove the values again
5. Save the product
6. Reindex in cli

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by manavadobe** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Looks like the issue was already fixed in https://github.com/magento/magento2/commit/d255ba3fb31db0bea0f8b9fea96d33a85cf5e091

**Comment by ihor-sviziev** [comment]
Since we didn't get any response and the issue seems to be fixed, I'm closing this PR.

**Pull request closed without merging**
