### PR TITLE
Widget-left-navigation-block

### PR DESCRIPTION
**Pull request by dipti2jcommerce**
In Admin configuration Widget left navigation block not proper in tablet landscape view #20492

### Description (*)
1.Go to CONTENT->Widget->Add new widget
2.While filling form ,left navigation block have design issue in tablet view

### Fixed Issues (if relevant)
In Admin configuration Widget left navigation block not proper in tablet landscape view #20492

### Manual testing scenarios (*)
screenshot-i-20487-2-3-develop instances magento-community engineering-2019-01-23-13-57-41

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @dipti2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sdzhepa** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-20493-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20493-2-3-develop.instances.magento-community.engineering/admin](https://i-20493-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [new Magento instance](https://pr-20493.instances.magento-community.engineering).
Admin access: [https://pr-20493.instances.magento-community.engineering/admin](https://pr-20493.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by sdzhepa — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, thank you for the review.
[ENGCOM-4052](https://jira.corp.magento.com/browse/ENGCOM-4052) has been created to process this Pull Request

**Pull request merged**
