### PR TITLE
Open separate page when click 'View' in CMS pages(Grid)

### PR DESCRIPTION
**Pull request by dominicfernando**
Goto -> Admin -> Content -> Pages and click 'View' in grid.
The preview page will open in a separate view.

Selection_078

### CODE REVIEW

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @dominicfernando, thank you for the improvement. According to the last updates to the definition of done all changes should be covered by automated tests. 

I suggest trying to update the following unit test `Magento\Cms\Test\Unit\Ui\Component\Listing\Column\PageActionsTest` by including your case.
Thank you.

**Comment by dominicfernando** [comment]
> Hi @dominicfernando, thank you for the improvement. According to the last updates to the definition of done all changes should be covered by automated tests.
> 
> I suggest trying to update the following unit test `Magento\Cms\Test\Unit\Ui\Component\Listing\Column\PageActionsTest` by including your case.
> Thank you.

**Comment by cspruiell** [comment]
@tkacheva Please provide product approval for this change.

**Review by cspruiell — APPROVED** [review]

**Review by tkacheva — APPROVED** [review]

**Comment by eduard13** [comment]
Hi @dominicfernando, looks like the opening the page in a new tab is causing the functional tests failing. May I ask you to adjust the MFTF tests accordingly to your changes and also fix the static tests?
You may try using the following action:
`<switchToNextTab stepKey="switchToNextTab"/>`

Thank you.

**Comment by engcom-Echo** [comment]
I will try to fix tests

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-7001](https://jira.corp.magento.com/browse/ENGCOM-7001) has been created to process this Pull Request
:eight_spoked_asterisk: @eduard13, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
