### PR TITLE
[Multishipping] Providing test coverage for correctly rendering the customer create page on multiple shipping

### LINKED ISSUE #32643: [Issue] [Multishipping] Providing test coverage for correctly rendering the customer create page on multiple shipping
This issue is automatically created based on existing pull request: magento/magento2#32638: [Multishipping] Providing test coverage for correctly rendering the customer create page on multiple shipping

---------

### Description (*)
This PR aims to provide a test coverage for #32634 PR.

Coverage for: https://github.com/magento/magento2/pull/32634

### Related Pull Requests
https://github.com/magento/magento2/pull/32634

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by eduard13**
### Description (*)
This PR aims to provide a test coverage for #32634 PR.

Coverage for: https://github.com/magento/magento2/pull/32634

### Related Pull Requests
https://github.com/magento/magento2/pull/32634

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32643: [Multishipping] Providing test coverage for correctly rendering the customer create page on multiple shipping

### CODE REVIEW

**Comment by eduard13** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8979](https://jira.corp.magento.com/browse/ENGCOM-8979) has been created to process this Pull Request

**Comment by engcom-Oscar** [comment]
@magento create issue

**Comment by eduard13** [comment]
@magento run WebAPI Tests, Functional Tests B2B

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE

**Comment by ihor-sviziev** [comment]
The functional ce test fails because in this PR no changes that fixes the issue. It will work fine if we'll merge these PRs together

**Comment by ihor-sviziev** [comment]
Hi,

The issue was already fixed in https://github.com/magento/magento2/commit/461509df6db50edf65de181ecb7decc27519a748, also it was covered with mftf test. I'm closing this PR as it's not relevant anymore

**Pull request closed without merging**
