### PR TITLE
Credit Memo with Zero Total: Order Status "Complete" and not "Closed"

### LINKED ISSUE #22762: Credit Memo with Zero Total: Order Status "Complete" and not "Closed"
### Preconditions (*)

1. Magento 2.3.1
2. PHP7.2

### Steps to reproduce (*)

1. Create order with zero Amount (all Grand Total, Total Paid, Total Refunded, Total Due, Subtotal, Shipping & Handling, Tax are zero ) in status = "Pending" and 1 SKU qty = 1.
2. Create Invoice and now Order is status = "Processing"
3. Ship Order -> now Orderstatus is = "Complete"
4. Now create Credit memo and refund and return product

### Expected result (*)

1. The order status should be "Closed"

### Actual result (*)

1. Order Status is "Complete"

### Additional information
- [Order Status Workflow](https://docs.magento.com/user-guide/sales/order-status-workflow.html)

### PR DESCRIPTION
**Pull request by engcom-Echo**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#22762

### Manual testing scenarios (*)

See: Fixes magento/magento2#22762

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by rogyar — APPROVED** [review]
The failing tests are not related to the current change. The same tests are being failed for other recent PRs

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7798](https://jira.corp.magento.com/browse/ENGCOM-7798) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Create order with zero Amount (all Grand Total, Total Paid, Total Refunded, Total Due, Subtotal, Shipping & Handling, Tax are zero ) in status = "Pending" and 1 SKU qty = 1;
2. Create Invoice and now Order is status = "Processing";
3. Ship Order -> now Order status is = "Complete";
4. Now create Credit memo and refund and return a product;

**Before:** :heavy_multiplication_x: Order Status is "Complete"



**After:** :heavy_check_mark: Order Status is "Closed"

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by simonmaass** [comment]
would be great if this makes it in 2.4

**Review by slavvka — CHANGES_REQUESTED** [review]
@engcom-Echo Please fix the failing MFTF static checks that were recently introduced:
```
Test AdminCreateCreditMemoWithZeroPriceCheckOrderStatusTest is missing the required annotations: stories, severity
```

**Comment by slavvka** [comment]
@magento run Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7798](https://jira.corp.magento.com/browse/ENGCOM-7798) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
