### PR TITLE
[WIP] Initialize authentication popup only when guest checkout is disabled

### PR DESCRIPTION
**Pull request by krzksz**
### Description (*)
This PR is a part of my effort to improve Magento 2 frontend performance.

Authentication popup was always a mystery for me. It was like this "Turbo" button in old PC cases that almost nobody knew what it was doing, yet it was there. One day I decided this situation cannot go on forever and so I dived into its frontend logic to see when it is actually used.

As it turns out there is a general logic which guards the showing of authentication popup only if guest checkout is disabled: https://github.com/krzksz/magento2/blob/fbedc73b4942c7ea5ea00a09a6b3d3cd76ac1f42/app/code/Magento/Checkout/view/frontend/web/js/sidebar.js#L66

You may imagine how happy I was when I finally saw this component for the first time, yet it is already time to say goodbye. In this PR I'm trying to adjust the whole frontend logic to load and initialize this component only when guest checkout is disabled. 

#### Performance improvement
Tested on Magento 2.4-develop with Luma and sample data.
- 202 → 185 JS requests (-8.42%).
- 763.65kB → 789.09kB JS transferred (-3.22%).

### Manual testing scenarios (*)

1. When guest checkout is enabled:
  a. No authentication popup JS and HTML files are loaded.
2. When guest checkout is disabled:
  a. Authentication popup is downloaded and initialized and shows up when guest is trying to go to the checkout.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@krzksz your changes looks good to me, but I see that there are too many test failures, so probably solution should be improved.
Could you let me know when I can review this PR?

**Comment by krzksz** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @krzksz. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @krzksz, here is your [new Magento instance](https://pr-27686.instances.magento-community.engineering).
Admin access: [https://pr-27686.instances.magento-community.engineering/admin_6a54](https://pr-27686.instances.magento-community.engineering/admin_6a54)
Login: `bc54cd2a` Password: `28193b6e1825`
Instance will be terminated in up to 3 hours.

**Comment by krzksz** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @krzksz. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @krzksz, here is your [new Magento instance](https://pr-27686.instances.magento-community.engineering).
Admin access: [https://pr-27686.instances.magento-community.engineering/admin_49c1](https://pr-27686.instances.magento-community.engineering/admin_49c1)
Login: `3de31825` Password: `c5e8de827ffc`
Instance will be terminated in up to 3 hours.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @krzksz,
Some MFTF still fails, looks like tests should be adjusted, or maybe your changes broke some functionality.
Could you check it?

**Comment by ihor-sviziev** [comment]
Hi @krzksz,
Will you be able to update your PR?

**Comment by krzksz** [comment]
@magento run all tests

**Comment by krzksz** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by krzksz** [comment]
@magento run Functional Tests EE,Functional Tests CE

**Comment by krzksz** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @krzksz. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @krzksz, here is your [new Magento instance](https://pr-27686.instances.magento-community.engineering).
Admin access: [https://pr-27686.instances.magento-community.engineering/admin_060a](https://pr-27686.instances.magento-community.engineering/admin_060a)
Login: `6bfdd576` Password: `6a958ae2f237`
Instance will be terminated in up to 3 hours.

**Comment by krzksz** [comment]
@magento run Functional Tests EE,Functional Tests CE

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@krzksz,
What if we'll add loading indicator while auithentication popup is loading? and once it shown - disable loading indicator? So I think it will be more clear to customers that something happening right now.
Also in the tests we could add waiting for the form to appear.

What do you thing?

**Comment by krzksz** [comment]
I think loading indicator is quite easy to be done, but I'm not sure what's wrong with those 2 tests. I asked @lbajsarowicz to check what is happening during this failing step and I'm waiting until he has some spare time.

**Comment by ihor-sviziev** [comment]
@krzksz as I understood - test continuing running for filling "login" form in the popup without wait until it will load and appear. Earlier it was immediately as this popup was already preloaded.

**Comment by krzksz** [comment]
But this test is not disabling guest checkout so the popup should not appear or I am missing something. My understanding was that it is trying to fill the login form at the top of shipping step but it is somehow not redirected to the checkout after clicking place order button.

**Comment by krzksz** [comment]
I am unable to set up `2.4-develop` with MFTF for now, but I wanted to see what is happening at that moment without my changes so if somebody is able to check it would be super helpful.

**Comment by ihor-sviziev** [comment]
As we discussed in slack - seems like functional test that fails written incorrectly as we weren't able to find where is guest checkout is disabling, seems like it tried to fill the authentication popup even when it's not appeared.

@lbajsarowicz could you help with it?

**Comment by krzksz** [comment]
@magento run Functional Tests CE

**Comment by krzksz** [comment]
@ihor-sviziev FYI: we have managed to pinpoint the issue we are having in this PR and it is more complicated then I initially thought. It turns out, that authentication popup should also show when user has downloadable products in their cart.

Because it is session-specific, we are not able to use the backend logic to tell if authentication popup should be initialized or not... I'll try to come up with some frontend-only solution but I don't have any obvious ideas right now.

**Comment by ihor-sviziev** [comment]
@krzksz wow. it's not obvious at all. 
Thank you for update!
I think there should be introduced some small "proxy", similar to proxy classes in magento on for php classes.

**Comment by ihor-sviziev** [comment]
Hi @krzksz,
Are you going to continue working on this PR? Or we can close it for now till you'll find time on finalizing it?

**Comment by ihor-sviziev** [comment]
Hi @krzksz,
I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
