### PR TITLE
Issue 36272: fix coupon report in admin

### LINKED ISSUE #36272: When trying to use certain multi-selects within the Magento admin for coupon report, they don't always work as intended.
**Preconditions**
Install Magento 2.4 to develop with sample data.

Create 2-3 more cart rules and place an order for each.

**Issue** 
When trying to use certain multi-selects within the Magento admin for coupon reports, they don't always work as intended.

**Steps To Reproduce**

Go to Admin-> Reports > Sales > Coupons

Apply filter as below 
Date Used = Order Created
Period = Day
From = Any previous date
To = Today
Order Status = Any
Empty Rows = No
Cart Price Rule = Specified

Make sure to select a few different coupon rules

Select "Show Report"

**Expected result**
Display results for selected cart rule and preserve value which was selected in the multi-select box 

**Actual result**
The report will only return the values for the first selection from the multi-select and any additional selections will now be unselected

 

Here I have selected Test and Test2, the result shows only for test, and Test2 is unselected from multi-select.

### PR DESCRIPTION
**Pull request by rogerdz**
### Description (*)

Update logic get data of multi-select field.
Fix same issue for Order Status in Admin-> Reports > Sales > Shipping

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36272

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run Unit Tests, Integration Tests, Functional Tests EE, Functional Tests CE

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @rogerdz,
It looks like the issue was already fixed in https://github.com/magento/magento2/commit/74e68576c01a5f9c1c758c240d30394d4c7f7355.
Could you please confirm that?

**Comment by engcom-Charlie** [comment]
As per above [comments](https://github.com/magento/magento2/pull/36311#issuecomment-1427995074) closing this PR

Thank you!

**Pull request closed without merging**
