### PR TITLE
[Forwardport] 'customer-login-page-input-field-are-short-width-on-tablet-view' :: a…

### PR DESCRIPTION
**Pull request by nainesh2jcommerce**
…dd changes for On customer login page input field are short width on tablet view

### Original Pull Request
https://github.com/magento/magento2/pull/20369

### Fixed Issues (if relevant)

1. magento/magento2#20172 
2. ...

### Manual testing scenarios (*)

1. go to customer login page
2. and check input fields in tablet view

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3824](https://jira.corp.magento.com/browse/ENGCOM-3824) has been created to process this Pull Request

**Comment by sdzhepa** [comment]
Hello @nainesh2jcommerce 

During testing our QA engineer faced an issue.
Could you please have a look and fix it?

Please see the quote of QA comment after testing on branch with the PR:
**Problem:** _PR doesn't fix #20172 for Luma theme._

1. Apply Luma theme.
2. Apply tablet view
3. Go to Customer Login Page

**Actual Result:** not OK, Width of Email and Password fields are short



Thank you for contribution and collaboration!

**Comment by nainesh2jcommerce** [comment]
Hi @sdzhepa 
I have already commits changes for Luma Theme yesterday

https://github.com/magento/magento2/pull/20173/commits/3f6c2c84db3ae61231c646361c6876d000cb8ec9

Thanks!

**Comment by nainesh2jcommerce** [comment]
Hi @magento-engcom-team 
I have already commits changes for luma theme few days ago
https://github.com/magento/magento2/commit/3f6c2c84db3ae61231c646361c6876d000cb8ec9

Thanks!

**Comment by nainesh2jcommerce** [comment]
Hi @magento-engcom-team,
Is any further update needed from my end?

**Comment by nainesh2jcommerce** [comment]
Hi @VladimirZaets,
Any news on this PR?

**Comment by Nazar65** [comment]
Hi @nainesh2jcommerce, your changes broke login form on blank theme 
DeepinScreenshot_select-area_20190312172522

**Pull request merged**
