### PR TITLE
Prevent page scroll jumping when product gallery loads

### PR DESCRIPTION
**Pull request by krzksz**
### Description (*)

During the investigation of the issue linked below I was able to pinpoint the exact moment of scroll jumping to fotorama's `that.resize` function which for some reason resets all of its major elements' width and height dimensions. I analysed the code and concluded that since current element height seems to be completely ignored in the whole script and is only set either based on settings or its width and ratio, the code that resets it can be removed. Please not that this can be also true for width but I left it here just to be safe as it doesn't contribute to page jumping.

In addition, `min-height` was added to prevent initial jump of the gallery when static image is being replaced by fotorama's HTML.

### Fixed Issues (if relevant)

1. magento/magento2#10518: Mobile product page image jumps
2. magento/magento2#21717: Product view page scrolls up randomly on mobile device

### Manual testing scenarios (*)

1. Open product page with images in the gallery in mobile view.
2. Scroll to the middle of the static image before gallery loads.
3. Page should no longer jump to the top once gallery initializes.

### Questions or comments
Please be sure to test this change on multiple browsers and devices including resizing the window through different resolutions as fotorama's configuration changes between breakpoins.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rodrigowebjump** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [new Magento instance](https://pr-25385.instances.magento-community.engineering).
Admin access: [https://pr-25385.instances.magento-community.engineering/admin](https://pr-25385.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rodrigowebjump** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [Magento instance](https://i-25385-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25385-2-3-develop.instances.magento-community.engineering/admin](https://i-25385-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by rodrigowebjump — APPROVED** [review]
Hi @krzksz 

Thanks for your contribution

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-6376](https://jira.corp.magento.com/browse/ENGCOM-6376) has been created to process this Pull Request
:eight_spoked_asterisk: @rodrigowebjump, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by krzksz** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
Hi @krzksz Please cover your fix with unit test

**Comment by engcom-Golf** [comment]
I will take care of test coverage

**Comment by engcom-Golf** [comment]
@magento run all tests

**Review by rodrigowebjump — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-6376](https://jira.corp.magento.com/browse/ENGCOM-6376) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
