### PR TITLE
Clean leading backslash and remove duplicate define preference

### LINKED ISSUE #28017: Multiple `app/etc/di.xml` overridding preferences
### Preconditions (*)
Magento 2.4-develop
Magento OOTB should provide only 1 preference for each Interface in `app/etc/di.xml` as it's "base config"

### Steps to reproduce (*)
Verify the contents of `app/etc/di.xml`

### Expected result (*)
Only 1 preference for 1 Interface

### Actual result (*)
https://github.com/magento/magento2/blob/960a51f7afa371e444842b953f0b5493d2255b13/app/etc/di.xml#L46
overridden by
https://github.com/magento/magento2/blob/960a51f7afa371e444842b953f0b5493d2255b13/app/etc/di.xml#L116

Possible that there are other issues like that. We need to add some kind of validation for `di.xml` to avoid such situations in future (CC: @lenaorobei )

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Clean unneccessary leading backslash and remove duplicate preference related with `Magento\Framework\Setup\ModuleDataSetupInterface`

### Fixed Issues (if relevant)

1. Fixes magento/magento2#28017

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Den4ik** [comment]
@magento run all tests

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-8768](https://jira.corp.magento.com/browse/ENGCOM-8768) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
Seems like does the same as https://github.com/magento/magento2/pull/26948

**Comment by mrtuvn** [comment]
I think this pr should be include first

**Comment by slavvka** [comment]
@magento give me test instance

**Comment by engcom-Bravo** [comment]
Hi @mrtuvn,

We are closing this PR.The PR is in Draft since longtime.

Once you are ready Please feel free to reopen it to process the PR further.

Thanks

**Pull request closed without merging**
