### PR TITLE
magento/magento2#16198: Category image remain after deleted.

### PR DESCRIPTION
**Pull request by p-bystritsky**
### Fixed Issues (if relevant)

1. magento/magento2#16198: Category image remain after deleted.

### Manual testing scenarios

1. Go to Admin > Catalog > Categories
2. Upload image via field Category Image under Content section > Save
3. Click on trash icon to remove image > Save
4. Image under pub\media\catalog\category should be removed

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @p-bystritsky. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sivaschenko — APPROVED** [review]

**Comment by sivaschenko** [comment]
Hi @p-bystritsky thanks for the contribution, can you please also port this PR to 2.3-develop branch to ensure it will be merged there as well.

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3826](https://jira.corp.magento.com/browse/ENGCOM-3826) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @p-bystritsky. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.

**Comment by p-bystritsky** [comment]
Port to 2.3 is not needed as issue is not reproducible on 2.3-develop branch.

**Pull request merged**
