### PR TITLE
Added swatches for new product widget

### LINKED ISSUE #14134: Swatches not showing on homepage New products widget
Create New products via magento's default widget and call on homepage

### Preconditions
1. Magento 2.4-develop

### Steps to reproduce

1. Create a widget and call New products on hompage 
2. Add to list any configurable product

### Expected result
1. Swatches should be visible on homepage 

### Actual result
1. No swatches coming on homepage
#14134issue

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixes issue #14134: Swatches not showing on homepage New products widget
Screenshot 2020-03-19 at 17 18 57

### Fixed Issues (if relevant)

1. Fixes magento/magento2#14134: Swatches not showing on homepage New products widget

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Usik2203. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Usik2203, here is your [Magento instance](https://i-27362-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27362-2-4-develop.instances.magento-community.engineering/admin_e7bc](https://i-27362-2-4-develop.instances.magento-community.engineering/admin_e7bc)
Login: `625f5276` Password: `c019cf667110`
Instance will be terminated in up to 3 hours.

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run Functional Tests CE

**Comment by Usik2203** [comment]
@magento run all tests

**Pull request closed without merging**
