### PR TITLE
Add custom attribute values to the origData property to prevent unnecessary db inserts and updates when saving the customer entity

### LINKED ISSUE #38753: Non-Static Customer Custom Attribute Are Always Updated When Using Customer Repository to Save
### Preconditions and environment

- 2.4.7
- At least one non-static custom attribute for the customer entity

### Steps to reproduce

1. Create a non-static customer custom attribute (e.g. `my_custom_attribute`)
2. Set `my_custom_attribute` to any value and save
3. Enable DB profiling
4. Load up the customer using the Customer Repository (`\Magento\Customer\Api\CustomerRepositoryInterface`)
5. Without changing any value save the customer using the Customer Repository (`\Magento\Customer\Api\CustomerRepositoryInterface::save()`)
6. Check DB profiling results
7. Notice a query to insert the value that was already saved and set for your custom attribute `my_custom_attribute` even though the original value does not differ from the new value

### Expected result

DB query to insert/update the value of the custom attribute is not created or ran because the value has not changed.

### Actual result

DB query to insert/update the value of the custom attribute is created and ran even though the value does not differ.

### Additional information

This can end up causing database deadlocks when the unnecessary insert/update query is ran which locks the row. 

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by NateSwanson7**
### Description (*)
Prevents the creation and execution of unnecessary db inserts/updates when saving a customer entity when non-static customer custom attribute exist.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#38753

### Manual testing scenarios (*)
1. Create a non-static customer custom attribute (e.g. `my_custom_attribute`)
2. Set `my_custom_attribute` to any value and save
3. Enable DB profiling
4. Load up the customer using the Customer Repository (`\Magento\Customer\Api\CustomerRepositoryInterface`)
5. Without changing any value save the customer using the Customer Repository (`\Magento\Customer\Api\CustomerRepositoryInterface::save()`)
6. Check DB profiling results
7. Notice there is no longer a query to insert the value that was already saved and set for your custom attribute `my_custom_attribute` since the original value does not differ from the new value

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by NateSwanson7** [comment]
@magento run all tests

**Comment by NateSwanson7** [comment]
@magento run all tests

**Comment by NateSwanson7** [comment]
@magento run all tests

**Comment by NateSwanson7** [comment]
@magento run all tests

**Comment by NateSwanson7** [comment]
@magento run all tests

**Comment by NateSwanson7** [comment]
@magento run all tests

**Comment by NateSwanson7** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
Closing this pr as the linked issue is been closed.

**Pull request closed without merging**
