### PR TITLE
32855: upgrade to the latest moment-timezone-with-data.js

### PR DESCRIPTION
**Pull request by karyna-t**
### Description (*)
Upgraded version of moment-timezone-with-data.js library (from 0.5.5 to 0.5.33).

### Fixed Issues (if relevant)
1. Fixes magento/magento2#32855: Investigate upgrade to the latest moment-timezone-with-data.js

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by karyna-tsymbal-atwix** [comment]
@magento run all tests

**Comment by karyna-tsymbal-atwix** [comment]
@magento run Functional Tests EE

**Comment by karyna-tsymbal-atwix** [comment]
@magento run Functional Tests EE

**Comment by karyna-tsymbal-atwix** [comment]
@magento run Functional Tests B2B

**Comment by karyna-tsymbal-atwix** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes from this PR.

**Comment by hostep** [comment]
Hmm, this is a minified js file, we should either:
- use the non-minified js file (so it's easier to understand the diff when it gets updated again in the future)
- if a non-minified js file is not available, indicate this is a minified js file by making sure the filename ends on `.min.js` so Magento's JS minifier does not try to minify it again in the SCD process (which can [sometimes](https://github.com/magento/magento2/issues/16927#issuecomment-409693343) lead to unexpected bugs)

This remark does not only count for this PR, but for all PR's that are touching JS libraries (which seem to be quite popular these last few weeks, maybe @ihor-sviziev can try to communicate this to the people who are involved with this process?). Reasoning is explained briefly in https://github.com/magento/magento2/pull/33427#issuecomment-874991028

Does this remark make sense?

**Comment by ihor-sviziev** [comment]
@hostep, I Absolutely agree with you!

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Would you please adjust your PR according to the requested changes in https://github.com/magento/magento2/pull/33476#issuecomment-880020668 ?

**Comment by karyna-tsymbal-atwix** [comment]
@hostep @ihor-sviziev  Thank you for the notice! I'll keep it in mind.
I've update PR with a non-minified version of the file.

**Comment by andrewbess** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Review by Den4ik — CHANGES_REQUESTED** [review]
@karyna-tsymbal-atwix Could you please update file from minified version?

**Review by Den4ik — APPROVED** [review]
I missed the comment https://github.com/magento/magento2/pull/33476#issuecomment-880020668 and it's really make sense.
@karyna-tsymbal-atwix Thanks for contribution

**Review by andrewbess — APPROVED** [review]

**Pull request merged**
