### PR TITLE
Improvements to the CONTRIBUTING.md document

### PR DESCRIPTION
**Pull request by RebeccaBrocton**
### Description
Wording changes & link updates to CONTRIBUTING.md.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15460) <br/>All committers have signed the CLA.

**Comment by avoelkl** [comment]
Hi @RebeccaBrocton!
Thanks or your pull request! Let's get this processed :)

**Review by avoelkl — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @avoelkl, thank you for the review.
[ENGCOM-1658](https://jira.corp.magento.com/browse/ENGCOM-1658) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@RebeccaBrocton thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @RebeccaBrocton. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

Please, consider porting this solution across release lines.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
