### PR TITLE
[Forwardport] fixed Quote Item Prices are NULL in cart related events. #18685

### PR DESCRIPTION
**Pull request by edenduong**
### Original Pull Request 
 https://github.com/magento/magento2/pull/18808

### Description (*)
before these two observers checkout_cart_product_add_after, checkout_cart_product_update_after cart item is not saved into the database the object is only created and in the object price was not set but custom price was set so there was no issue of custom price, we could have added the price in the item from two files:
app/code/Magento/Quote/Model/Quote/Item/Processor.php and
app/code/Magento/Quote/Model/Quote.php
I have added the price in this file app/code/Magento/Quote/Model/Quote/Item/Processor.php

### Fixed Issues (if relevant)

1. magento/magento2#18685: Quote Item Prices are NULL in cart related events

### Manual testing scenarios (*)

1. create a module which has observers for these two events checkout_cart_product_add_after, checkout_cart_product_update_after cart
2. now in the observer try to get the added item price by calling $observer->getEvent()->getQuoteItem()->getPrice()

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by edenduong** [comment]
Close.

**Comment by edenduong** [comment]
Forward Port From 2.2 to 2.3

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-5521](https://jira.corp.magento.com/browse/ENGCOM-5521) has been created to process this Pull Request
:eight_spoked_asterisk: @swnsma, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
