### PR TITLE
removed redundant and clean code less

### LINKED ISSUE #29857: [Issue] removed redundant and clean code less
This issue is automatically created based on existing pull request: magento/magento2#29856: removed redundant and clean code less

Clean and remove redundant code less in configurable product module
flex-direction row is initial so don't need re-declare it

### Preconditions (*)
1. Magento 2.4

### Steps to reproduce (*)
Clean and remove redundant code less in configurable product module
flex-direction row is initial so don't need re-declare it

### Expected result (*)
Clean and remove redundant code less in configurable product module
flex-direction row is initial so don't need re-declare it

### Actual result (*)
flex-direction row is initial so don't need re-declare it

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Clean and remove redundant code less in configurable product module inside backend theme
flex-direction row is initial so don't need re-declare it

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29857: removed redundant and clean code less

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento create issue

**Review by ptylek — APPROVED** [review]
Failed tests seem not related to this change.

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-8112](https://jira.corp.magento.com/browse/ENGCOM-8112) has been created to process this Pull Request

**Review by ihor-sviziev — APPROVED** [review]
Agree, just wanted to wait till tests will not be failing :)

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8112](https://jira.corp.magento.com/browse/ENGCOM-8112) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked currency and price field for configurable product variations are displayed as before
**Result:**
**Before:**
image

**After:**
image

**Pull request merged**
