### PR TITLE
#13685: Upgrading jQuery to 3.3.1

### PR DESCRIPTION
**Pull request by kirmorozov**
* Updating jQuery to 3.3.1 (originally from npm)
* Updating jQuery Migrate 3.0.1 (originally from npm)

### Description
Upgrading initial jQuery and jQuery Migrate

### Fixed Issues (if relevant)

1. magento/magento2#13685: Incompatibilies with jQuery 3
2. ...

### Manual testing scenarios
1. I can checkout without any problems
2. I can use admin without any problems

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by kirmorozov** [comment]
The jqXHR.success(), jqXHR.error(), and jqXHR.complete() callback methods are removed as of jQuery 3.0. You can use jqXHR.done(), jqXHR.fail(), and jqXHR.always() instead.
Latest

**Comment by okorshenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [test Magento instance](http://pr-14556.engcom.dev.magento.com)

**Comment by okorshenko** [comment]
backend access: /admin   admin @ 123123q

**Comment by okorshenko** [comment]
Hi @kirmorozov thank you for PR. Unfortunately we can not accept this PR as is. We are in the middle for 2.3 regression + this is a backward incompatible change for us. It is ok to update usages for done fail always but without upgrading the library. Once all code is updated, we will be able to update the lib in 2.4. Could you please revert lib update?

**Review by omiroshnichenko — CHANGES_REQUESTED** [review]
Pay attention on https://github.com/magento/magento2/pull/14556#issuecomment-379043381.

**Comment by kirmorozov** [comment]
@okorshenko Thanks for information PR can wait until you create 2.4-develop branch.
I have few more tests to fix.
And yes this it getting forwards to use 2 year old jQuery API.

**Comment by kirmorozov** [comment]
@okobchenko @omiroshnichenko There are backward incompatible changes regarding ajax.
Following commits are compatible with 2.3 and do not break backward compatibility:
https://github.com/magento/magento2/pull/14556/commits/ccfdcbb0b25d78cec9120f399cf72dc9c07a5c0e
https://github.com/magento/magento2/pull/14556/commits/f9069b974952655cce5d28ad8ef391126a05878c
https://github.com/magento/magento2/pull/14556/commits/c4c93aafd3b4deae85f39ce52aa551e73f756346

Others are backward incompatible changes in jQuery 3.x.

**Comment by kirmorozov** [comment]
Compatible code is cherry-picked in this pull request:
https://github.com/magento/magento2/pull/14637

**Comment by ishakhsuvarov** [comment]
Hi @kirmorozov 
We are closing this PR now, due to reasons described in https://github.com/magento/magento2/pull/14556#issuecomment-379043381.
Thank you for providing compatible change set with #14637

**Comment by kirmorozov** [comment]
@ishakhsuvarov 
Please provide 2.4-develop branch.

**Comment by ishakhsuvarov** [comment]
@kirmorozov `2.4-develop` will be available based on internal schedule.

**Pull request closed without merging**
