### PR TITLE
#31168 fix for customer which have more than two subscriptions

### LINKED ISSUE #31168: REST endpoint /customers/search not working for multi-store newsletter subscriptions
### Preconditions (*)

1. Magento version 2.4.1
2. Magento 2.4-develop
3. Admin -> Stores -> Configuration -> Customers -> Customer Configuration -> Account Sharing Options and set S**hare Customer Accounts** to **Global**

Screenshot from 2020-12-07 12-59-48

4. Multiple-store views setup in Magento

Screenshot from 2020-12-07 12-56-25

5. Have one customer ( _test@example.com_ for ex.);

### Steps to reproduce (*)

1. Go to _Admin -> Customers -> All Customers_ and open customer for edit;
2. On left side, select _Newsletter_, to have the Newsletter Informaiton panel where all stores views are displayed.
3. Select more than 1 checkbox to subscriber customer to the store's newsletter and save customer 
(at this point, in Newsletter Subscribers view, customer is subscribed to newsletter for multiple-store views)

Screenshot from 2020-12-07 13-04-43

4. Use REST to call **GET** `/V1/customers/search` to retrieve the customer 

V1/customers/search?searchCriteria[filterGroups][0][filters][0][field]=email&searchCriteria[filterGroups][0][filters][0][value]=test@example.com&searchCriteria[filterGroups][0][filters][0][conditionType]=eq

Screenshot from 2020-12-07 13-06-15

### Expected result (*)

1. Customer details are returned correctly

### Actual result (*)

1. Exception occurs.
{
    "message": "Internal Error. Details are available in Magento log file. Report ID: webapi-xxx"
}

Screenshot from 2020-12-07 13-06-26

2. And in the **_exception.log_** file: 

`
[2020-12-07 10:36:54] main.CRITICAL: Report ID: webapi-5fce05c67a1e6; Message: Item (Magento\Customer\Model\Customer\Interceptor) with the same ID "1" already exists. {"exception":"[object] (Exception(code: 0): Report ID: webapi-5fce05c67a1e6; Message: Item (Magento\\Customer\\Model\\Customer\\Interceptor) with the same ID \"1\" already exists. at /var/www/html/magento24/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php:208, Exception(code: 0): Item (Magento\\Customer\\Model\\Customer\\Interceptor) with the same ID \"1\" already exists. at /var/www/html/magento24/lib/internal/Magento/Framework/Data/Collection.php:408)"} []
`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by korovitskyi**
### Description (*)
Rolled back updating `is_subscribed`  Extension attribute at `Magento\Customer\Api\Data\CustomerInterface`.
And test for this case was added.
Column `reference_field` must be unique to avoid exceptions on **getList**  method. 

Fixed Issues 
Fixes magento/magento2#31168.

### Manual testing scenarios (*)
1. Create customer.
2. Add several(more then one) newsletter subscriptions for this customer.
4. Get this customer by `\Magento\Customer\Api\CustomerRepositoryInterface::getList` method.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by swnsma — CHANGES_REQUESTED** [review]
Hi @korovitskyi!
Thank you for your contribution.
I am afraid that such changes could be considered backward-incompatible for those who are using the 'is_subscribed' extension attribute.

With new behavior, we will receive a list of customers without these values.
My suggestion is to adjust logic inside 'app/code/Magento/Newsletter/Model/Plugin/CustomerPlugin' by using a subscribers collection to fill the required data.
What do you think about this?

**Comment by engcom-Charlie** [comment]
Hi @korovitskyi could you please look at https://github.com/magento/magento2/pull/31261#pullrequestreview-550032240?
Thank you.

**Comment by korovitskyi** [comment]
Hi, @swnsma, @engcom-Charlie.
Thanks for notice.
Changes was sent. 
Please, let me know if you have some notes.

**Comment by swnsma** [comment]
@magento run all tests

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-8551](https://jira.corp.magento.com/browse/ENGCOM-8551) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Admin -> Stores -> Configuration -> Customers -> Customer Configuration -> Account Sharing Options and set S**hare Customer Accounts** to **Global**

Screenshot from 2020-12-07 12-59-48


2. Multiple-store views setup in Magento

Screenshot from 2020-12-07 12-56-25

3. Have one customer ( _test@example.com_ for ex.);


### Steps to reproduce (*)

1. Go to _Admin -> Customers -> All Customers_ and open customer for edit;
2. On left side, select _Newsletter_, to have the Newsletter Informaiton panel where all stores views are displayed.
3. Select more than 1 checkbox to subscriber customer to the store's newsletter and save customer 
(at this point, in Newsletter Subscribers view, customer is subscribed to newsletter for multiple-store views)

Screenshot from 2020-12-07 13-04-43


4. Use REST to call **GET** `/V1/customers/search` to retrieve the customer 

V1/customers/search?searchCriteria[filterGroups][0][filters][0][field]=email&searchCriteria[filterGroups][0][filters][0][value]=test@example.com&searchCriteria[filterGroups][0][filters][0][conditionType]=eq

Screenshot from 2020-12-07 13-06-15


**Before:** :heavy_multiplication_x:  Exception occurs.

Screenshot from 2020-12-18 10-47-27

And in the _exception.log_ file:

Screenshot from 2020-12-18 10-48-07

**After:** :heavy_check_mark:  Customer details are returned correctly

Screenshot from 2020-12-18 10-55-29

**Comment by robbie-thompson** [comment]
@korovitskyi we just ran into this error, thanks for fixing this! 🙌

**Pull request merged**
