### PR TITLE
Fix Magento Unit Tests to be compatible with PHP 8.1

### PR DESCRIPTION
**Pull request by anzin**
### Description (*)

Fixed deprecations function php 8.1 to pass Unit Tests

### Related Issues (if relevant)
1. magento/magento2#34441

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by andrewbess — APPROVED** [review]
Hello @anzin 
Thank you for your contribution
Approved ✔️

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, thank you for the review.
[ENGCOM-9359](https://jira.corp.magento.com/browse/ENGCOM-9359) has been created to process this Pull Request
:eight_spoked_asterisk: @andrewbess, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by xmav** [comment]
@magento run all tests

**Comment by anzin** [comment]
@magento run all tests

**Review by xmav — APPROVED** [review]

**Comment by xmav** [comment]
pending delivery https://github.com/magento-commerce/magento2ce/pull/7255

**Pull request merged**
