### PR TITLE
Batch products together during catalog rule indexer calculation to improve performance

### LINKED ISSUE #34784: Very slow `catalogrule_product` index even when no catalog rule exists
On a Magento 2.4.3 instance:
- I don't have any catalog rule
- I have ~100k products, mostly configurable
- I have 4 websites
- Have almost all my indexes setup on scheduled mode

### Steps to reproduce (*)

1. Add some ids (or update some product attributes) into `catalogrule_product_cl` table.
2. Run `indexer_update_all_views` CRON job.

### Expected result (*)

1. Product ids quantity should not have that big impact in index processing time.
2. The index process should end in a reasonable time.

### Actual result (*)

1. Product ids quantity is brutally impacting execution time.
2. Index process should end in a moment, when no catalog rule is set.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by aligent-lturner**
### Description (*)
Improves performance of the Catalog Rule scheduled indexer by batching products together.
Currently, products are processed one by one. In the case of a large number of product changes, this can take a long time to process, even if there are no catalog rules present, as there will need to be at least 2 * number of products database queries (so with 10k products to process, there are at least 20k queries being performed).

This PR introduces a new class, `ReindexRuleProductsPrice` to be used in place of `ReindexRuleProductPrice`. Additionally, `RuleProductsSelectBuilder` has been modified to handle multiple products instead of a single one.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#34784

### Manual testing scenarios (*)
1. Process catalog rule indexers (`indexer_update_all_views` cron job) with a large number of products in the backlog (performance test)
2. Ensure indexed data is the same with or without this PR

### Questions or comments
I introduced a new class, rather than modifying the existing `ReindexRuleProductPrice` class. I could have potentially added a new function there to handle the case with multiple products, but it would have been a little messy in terms of updating associated tests.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by aligent-lturner** [comment]
There was a previous PR for this issue (https://github.com/magento/magento2/pull/34785), but it has since been closed, and the changes are no longer visible. Based on the description and comments, it was handling a specific case where there are no active rules. This PR is a more general performance improvement, and should help regardless of how many rules are present/active.

**Comment by aligent-lturner** [comment]
@magento run all tests

**Comment by aligent-lturner** [comment]
@magento run all tests

**Comment by aligent-lturner** [comment]
@magento run all tests

**Comment by aligent-lturner** [comment]
@magento run all tests

**Comment by aligent-lturner** [comment]
@magento run all tests

**Comment by aligent-lturner** [comment]
@magento run all tests

**Comment by aligent-lturner** [comment]
@magento run all tests

**Comment by aligent-lturner** [comment]
@magento run all tests

**Comment by aligent-lturner** [comment]
@magento run all tests

**Comment by aligent-lturner** [comment]
@magento run all tests

**Comment by aligent-lturner** [comment]
@magento run all tests

**Comment by aligent-lturner** [comment]
@magento run all tests

**Comment by aligent-lturner** [comment]
There is a single integration test that is failing that is unrelated to my changes.
The unit tests also report an error for the overall status, but there are no actual errors reported when viewing the details.

**Comment by aligent-lturner** [comment]
@magento run Sample Data Tests B2B

**Comment by aligent-lturner** [comment]
@magento run Unit Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE, Static Tests, WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Comment by andrewbess** [comment]
Hello @aligent-lturner 
Thank you for your collaboration.
Looks good for me.
Let's wait for passing tests.

**Comment by andrewbess** [comment]
@magento run Sample Data Tests CE, Sample Data Tests EE, Sample Data Tests B2B

**Review by engcom-Hotel — APPROVED** [review]
Thanks @aligent-lturner for your contribution!

:heavy_check_mark: Approving the PR

**Review by andrewbess — APPROVED** [review]
✔️ Approved

**Comment by andrewbess** [comment]
@magento run Sample Data Tests CE, Sample Data Tests EE, Sample Data Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
Setup Magento with a good amount of products

**Manual testing scenario:**

1. Process catalog rule indexers (indexer_update_all_views cron job) with a large number of products in the backlog (performance test)
2. Ensure indexed data is the same with or without this PR

**Actual Result:** :heavy_check_mark:
`indexer_update_all_views` Should complete with batch products together.

**After:** :heavy_check_mark: 

After PR changes the indexer took less time. Please refer to the below screenshot from cron.log file:

image

**Before:** :heavy_multiplication_x:

It took comparatively more time
image

**Tested all the manual scenarios, no impact on regression testing.**

As some tests are still failing hence moving this PR in `Extended Testing`.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Integration Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
In 2 consecutive build runs, it was found that the build failures were flaky. Please refer to the below screenshots:

**Functional Tests CE**
_[Build Run 1](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37889/299626843aa71ff0fbe9801b0b0c2a24/Functional/allure-report-ce/index.html#categories)_
image

_[Build Run 2](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37889/5f065f2717b64f01dbd632afb63a3590/Functional/allure-report-ce/index.html#categories)_
image

**Functional Tests B2b**
_[Build Run 1](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37889/d3a9c2c308cba3134a4a1eaabc961485/Functional/allure-report-b2b/index.html#categories/bdf97e77bcffd7f38cbdda1b230ce01d/c89238d369358f55/)_
image

_[Build Run 2](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37889/b9219365d44a940d01517f9ea9ef7b5f/Functional/allure-report-b2b/index.html#categories/6ca9d315ebd9ab54dbe1fb9148ebdc1f/d05a0d1832967007/)_
image

Hence moving this PR in `merge in progress`.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE, Integration Tests, WebAPI Tests

**Comment by andrewbess** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE

**Comment by kamilmaliszewski** [comment]
Hey @aligent-lturner I've created patch from your changes and applied it for our M2 instance. There is almost no benefit in scope of catalog-rule reindex.

We have 500k products and there is 1 686 929 records in catalog_rule_product. 

Catalog Rule Product index has been rebuilt successfully in 01:16:59 with this patch
vs
Catalog Rule Product index has been rebuilt successfully in 01:18:04 without this patch... 

Have u tested your changes? Have u had better results?

**Comment by aligent-lturner** [comment]
> Hey @aligent-lturner I've created patch from your changes and applied it for our M2 instance. There is almost no benefit in scope of catalog-rule reindex.
> 
> We have 500k products and there is 1 686 929 records in catalog_rule_product.
> 
> Catalog Rule Product index has been rebuilt successfully in 01:16:59 with this patch vs Catalog Rule Product index has been rebuilt successfully in 01:18:04 without this patch...
> 
> Have u tested your changes? Have u had better results?

Hi @kamilmaliszewski
In my limited testing, this patch actually produces a bigger benefit for instances where catalog price rules are not used (but there are a lot of products). The reason for this is that the existing code still processes products one at a time, so for n products, there are at least n database queries still. We have seen instances of the catalog price rule indexer taking upwards of 20 minutes to run, even when there are no catalog price rules at all!.

I have not done extensive performance testing of various scenarios, but I cannot imagine there is any realistic scenario where performance is not improved, even if the improvement is small.

**Comment by kamilmaliszewski** [comment]
Yeah @aligent-lturner. It helps, but profit is not a big. Unfortunately it is not solution for catalog-rule problem of Magento with big catalog and many customer groups. I was debugging this catalog-rule and it seems that for existing catalog-rule the biggest problem is method `$rule->getMatchingProductIds()` which needs to be processed at every reindex. When customer create a huge condition here, then this time is growing. 

if I understand this logic correctly, then when the catalog-rule it empty it seems that simple solution like 
``` 
protected function doReindexFull()
{
   $rules = $this->getAllRules();
   if (empty($rules) {
       return;
   }
.....
}
```
should solve the problem.

**Comment by aligent-lturner** [comment]
> Yeah @aligent-lturner. It helps, but profit is not a big. Unfortunately it is not solution for catalog-rule problem of Magento with big catalog and many customer groups. I was debugging this catalog-rule and it seems that for existing catalog-rule the biggest problem is method `$rule->getMatchingProductIds()` which needs to be processed at every reindex. When customer create a huge condition here, then this time is growing.
> 
> if I understand this logic correctly, then when the catalog-rule it empty it seems that simple solution like
> 
> ```
> protected function doReindexFull()
> {
>    $rules = $this->getAllRules();
>    if (empty($rules) {
>        return;
>    }
> .....
> }
> ```
> 
> should solve the problem.

Yes, that would solve that particular issue, but would still result in very poor performance in many other similar situations. I'm not suggesting this PR is a panacea for all catalog price rule performance issues - only that it will improve performance in general.

**Pull request merged**
