### PR TITLE
Simplify product list

### PR DESCRIPTION
**Pull request by slackerzz**
Following the KISS principle we can save some CPU cycles

### CODE REVIEW

**Comment by dverkade** [comment]
Hi Slackerzz,

What a great find! :-) I see there are a total of 16 instances of this code in different templates. Any change you want to fix them as well?

**Comment by slackerzz** [comment]
Ok, i'm going to "fix 'em all"

**Comment by vrann** [comment]
@slackerzz can you please synchronize your branch with the latest develop?

**Comment by slackerzz** [comment]
@vrann i've just opened a new pull request #9019 based on current develop branch (i've accidentally deleted the old fork with this branch)

**Pull request closed without merging**
