### PR TITLE
FIX show visual swatches in admin - product attribute 

### PR DESCRIPTION
**Pull request by enriquei4**
### Description
Visual swatch wasn't shown full menu, I only fix some CSS to show full menu. Now the menu is showed correctly.

### Fixed Issues (if relevant)
Values of Visual Swatch Attribute drop down is not work correct https://github.com/magento/magento2/issues/11534

### Manual testing scenarios

1. Go to Admin
2. Open Stores > Attributes > Product
3. Add New Attribute with Catalog Input Type for Store Owner: Visual Swatch
4. In Tab Manage Swatch (Values of Your Attribute) click Add Swatch button
5. Press to chose color or file
6. Now is fixed to rendered the menu with all items.

BEFORE:
screen shot 2017-10-24 at 08 50 41

NOW:
screen shot 2017-10-24 at 08 45 55

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [X] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by okorshenko** [comment]
Hi @enriquei4 thank you for your contribution. It would very helpful if you will add screenshots BEFORE and AFTER
Thank you!

**Comment by enriquei4** [comment]
I've attached 2 screenshots on 2.3-develop.  This fix should be applied also on 2.2.

**Comment by okorshenko** [comment]
Hi @enriquei4 our UX team requested to change the styles. In current implementation the height of the row is changing when you click the color select. Can we make it on top of the row layer and do not change row height to prevent the jumping effect on the page?

**Comment by enriquei4** [comment]
Edited, now it shows:
screen shot 2017-10-24 at 20 24 18

**Comment by enriquei4** [comment]
@okobchenko codacy is still analysing :( do you know if could i restart the analysis ?

**Comment by okorshenko** [comment]
don't worry 
I will take it

**Pull request merged**
