### PR TITLE
Code to pass hostname to Varnish and optimally only purge the current domain.

### PR DESCRIPTION
**Pull request by pynej**
https://github.com/magento/magento2/issues/4871

### CODE REVIEW

**Comment by okorshenko** [comment]
HI @pynej Unfortunately we can not accept this PR. In current implementation it is incompatible with latest changes in develop branch. Please reopen this PR once ready for delivery. Thank you

**Comment by pynej** [comment]
Yah, I'm not going to be doing that as I reported the issues and patch over  year ago.

**Comment by woutersamaey** [comment]
Another community powered improvement gone to waste.

**Comment by okorshenko** [comment]
Hi @woutersamaey as I said we can not accept broken code to mainline. This is good improvement, but it must work. Please, let us know If you would like to proceed with this PR. We will do our best to help you. Thank you.

**Comment by woutersamaey** [comment]
I understand you have a process in place @okorshenko, but it's just not working. 
I see a lot of important improvements just lying around for over a year. This is no exception. 

Essential stuff, you should care about. But instead you want us to do all the work. It's just not a group effort.

Now assume that @pynej fixes this issue, you may or may not accept the PR. And when it is finally accepted, it may still be another year before we see it in a release and can actually benefit from his work.

At least this is the impression that I got from many essential improvements and bug fixes lying around. 

The current process is not working as it should be. You should put developers on these issues to help out, work we contribute should end up in a release no more than 3 months after it was made and you should publish statistics so that people can actually see the community and process work and regain confidence. 

When we start out a project, we run into issues. Old issues, that have been fixed most of the time already. Instead, we keep fighting old fights, which is downright depressing. 

There's also a reason i say 3 months, because most projects take this long. When we contribute, we should get our own improvements in a timely fashion.

Now, we're disconnecting, losing interest like @pynej

Don't forget it's the developers that make the community.

Ps: Sorry for going on like this. I'm very passionate about Magento and would love to see improvements in this key area.

**Pull request closed without merging**
