### PR TITLE
Cleanup search api di

### PR DESCRIPTION
**Pull request by thomas-kl1**
I was debugging stuff when I see some code duplication and/or the module should not be responsible for.

### Description (*)
- Magento_Cms: unused virtual type: not used in Magento 2 vanilla code, should not be used by third party developers, but we never know..

- Magento_Sales & Magento_Search: same configuration for the FilterPool class result in duplication:
The following code is only UiComponent related, so I guess it can be easily moved to Magento_Ui without harm.
```xml
    <type name="Magento\Framework\View\Element\UiComponent\DataProvider\FilterPool">
        <arguments>
            <argument name="appliers" xsi:type="array">
                <item name="regular" xsi:type="object">Magento\Framework\View\Element\UiComponent\DataProvider\RegularFilter</item>
                <item name="fulltext" xsi:type="object">Magento\Framework\View\Element\UiComponent\DataProvider\FulltextFilter</item>
            </argument>
        </arguments>
    </type>
```

- Magento_Ui: Magento\Ui\Component\Filter\FilterPool does not exists and is never used. Remove from di.xml

### Manual testing scenarios (*)
Fulltext search in admin grid should works as usual.

### Questions or comments
It's juste a concern of me. If all of this was purposely done, let me know :)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6340](https://jira.corp.magento.com/browse/ENGCOM-6340) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by sdzhepa** [comment]
@magento run all tests

**Comment by slavvka** [comment]
The architectural approval is granted. Proceeding with the delivery

**Pull request merged**
