### PR TITLE
Fix for adding more then one configurable product

### LINKED ISSUE #30948: Graphql - issue adding multiple configurable products to cart
### Preconditions (*)

1. magento 2.3.4

### Steps to reproduce (*)

create a mutation for addConfigurableProductsToCart with multiple configurable products

### Expected result (*)

1. products added to cart

### Actual result (*)
{
  "errors": [
    {
      "message": "You need to choose options for your item.",
      "extensions": {
        "category": "graphql-input"
      },
      "locations": [
        {
          "line": 25,
          "column": 3
        }
      ],
      "path": [
        "addConfigurableProductsToCart"
      ]
    }
  ],
  "data": {
    "addConfigurableProductsToCart": null
  }
}
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by nige-one**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#30948

### Manual testing scenarios (*)

1. see magento/magento2#30948

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by nige-one** [comment]
@magento run all tests

**Comment by nige-one** [comment]
The failing Functional Tests do not seems to be related to this MR.

**Review by bgorski — COMMENTED** [review]
@nige-one thank you for your contribution! Could you cover your bugfix with an API Functional test? I think you could modify the testAddMultipleConfigurableProductToCart() method from the \Magento\GraphQl\ConfigurableProduct\AddConfigurableProductToCartTest test class by using the Magento/ConfigurableProduct/_files/configurable_products.php fixture instead of Magento/ConfigurableProduct/_files/product_configurable.php and adjusting the method body accordingly. Just be aware that we currently have a bug with running API Functional tests mentioned in https://github.com/magento/magento2/issues/32252 - but the proposed solution mentioned there works as a workaround.

**Comment by bgorski** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by bgorski** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Review by bgorski — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @bgorski, thank you for the review.
[ENGCOM-9076](https://jira.corp.magento.com/browse/ENGCOM-9076) has been created to process this Pull Request

**Comment by bgorski** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
Hi @kassner , @orlangur 
Thanks for the collaboration & contribution!

:x: QA not Passed

_By adding a configurable product to the cart, getting an API response as `You need to choose options for your item.`_

**Manual Scenario Steps**

1. Used the fresh Magento instance having an sample data setup; Created a customer account in the front end.
2. Received the customer token using a POST call _rest/default/V1/integration/customer/token_
3. Checked the empty cart using GET call _rest/default/V1/carts/mine_
4. Posted a simple product into the cart using POST call _/rest/default/V1/carts/mine/items_; Below is the payload -
> {
>   "cartItem": {
>     "sku": "24-MB01",
>     "qty": 1,
>     "quote_id": "4"
>   }
> }
5. Posted a configurable product into the cart using POST call _/rest/default/V1/carts/mine/items_; Below is the payload (Used as per the [RefDoc](https://devdocs.magento.com/guides/v2.4/rest/tutorials/orders/order-add-items.html#add-configurable)) -
> {
>   "cartItem": {
>     "sku": "MH01",
>     "qty": 1,
>     "quote_id": "4",
>     "product_option": {
>       "extension_attributes": {
>         "configurable_item_options": [
>           {
>             "option_id": "93",
>             "option_value": 52
>           },
>           {
>             "option_id": "141",
>             "option_value": 168
>           }
>         ]
>       }
>     },
>     "extension_attributes": {}
>   }
> }

**:x: Got the response 400 Bad Request with below message**
> {
>     "message": "You need to choose options for your item."
> }
> 

**:heavy_check_mark: Expected result**
- We should receive successful response
- If we GET call _rest/default/V1/carts/mine_; It should respond with updated cart items.

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests EE

**Comment by engcom-Alfa** [comment]
@magento run WebAPI Tests

**Comment by bgorski** [comment]
@engcom-Alfa Manjunath, I noticed that those tests that made QA to fail a few months ago were done using the REST API instead of GraphQL. You can try the following steps:
1. Precondition #1: Create an empty cart via graphql:
```
mutation { 
    createEmptyCart
}
```
2. Precondition #2: Use the following mutation to test that you can add one configurable product to that cart:
```
mutation {
  addConfigurableProductsToCart(
    input: {
      cart_id: "{{cart_id}}"
      cart_items: [
        {
          data: {
            quantity: 1
            sku: "Colors-1-Red"
          },
          parent_sku: "Colors-1"
            
        }
      ]
    }
  ) {
    cart {
      items {
        id
        product {
          sku
          stock_status
        }
        quantity
      }
    }
  }
}
```
I used some product that was available on my test instance, you need to replace `sku` and `parent_sku`
3. Precondition #3: Repeat the mutation above for a different single configurable product (what's important here is that it has to be a completely different one - both the child sku and parent sku need to be different). 
4. Now that we know that both configurable products can be added to cart separetely, modify the mutation to add them both at once (the cart can be the same - in which case just the quantities should increase):
```
mutation {
  addConfigurableProductsToCart(
    input: {
      cart_id: "{{cart_id}}"
      cart_items: [
        {
          data: {
            quantity: 1
            sku: "Colors-1-Red"
          },
          parent_sku: "Colors-1"
            
        },
        {
          parent_sku: "Colors"
          data:{
            quantity: 1
            sku: "Colors-Black"
          }
          
        }
      ]
    }
  ) {
    cart {
      items {
        id
        product {
          sku
          stock_status
        }
        quantity
      }
    }
  }
}
```
This mutation should fail before the fix and work after the fix is applied.

You can test that and in the meantime I'll try to prepare some GraphQL API Functional test myself.

**Comment by bgorski** [comment]
@magento run all tests

**Comment by bgorski** [comment]
Removed the 'ready for testing' label the bot added and added 'testing in progress' because it is in progress for some time already

**Comment by bgorski** [comment]
I noticed the test I added is failing. I'll fix it this week.

**Comment by bgorski** [comment]
@magento run WebAPI Tests

**Comment by bgorski** [comment]
@magento run WebAPI Tests

**Comment by bgorski** [comment]
@magento run Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Magento Health Index, Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE, Semantic Version Checker, Static Tests, Unit Tests

**Comment by bgorski** [comment]
@magento run Functional Tests CE

**Comment by bgorski** [comment]
I believe that the "Progress: needs update" tag was left here by the bot by mistake as a result of moving the task between columns on the board. Removing it.

**Comment by bgorski** [comment]
@engcom-Alfa hey, please check my comment above. If you did leave that tag for a reason, please add it back and let us know what changes are requested. Thanks!

**Comment by bgorski** [comment]
I think what just happened was also not intentional. Reverting.

**Comment by engcom-Alfa** [comment]
HI @bgorski , Thanks for all the above updates, I will re-test and update my observations here again.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Install Magento 2 fresh instance with sample data


**Manual testing scenario:**

1. Follow the execution steps from [Comment](https://github.com/magento/magento2/pull/31654#issuecomment-901019463)

2. Validate the GraphQL response of adding multiple products into the cart.


**Before:** :heavy_multiplication_x: Responding with "No Stocks" error message even after the availability.  

image


**After:** :heavy_check_mark:  Multiple configurable products got added to the cart successfully.

image


The functional testing of it has been covered in automation part if the same PR, and there is no additional regression testing is required

**Pull request merged**
