### PR TITLE
\Magento\CatalogInventory\Model\Stock\Status->getStockId() to return correct value

### PR DESCRIPTION
**Pull request by fe-lix-**
\Magento\CatalogInventory\Model\Stock\Status->getStockId() is returning the website id instead of the stock id.

### CODE REVIEW

**Comment by alena-marchenko** [comment]
Hi @fe-lix- 

We've created MAGETWO-58941 internal ticket regarding this.
Thank you!

**Comment by Ctucker9233** [comment]
@alena-marchenko @mmansoorebay was this merge included in 2.1.2?

**Comment by flancer64** [comment]
@alena-marchenko @mmansoorebay @Ctucker9233 This issue is still actual for composer based installation at least. 

I suppose `84b456b70f2868d080f50610073746f5fbf5d455` is a revision:

```
alex@vm-ubuntu-mate-64:~/.composer/cache/files/magento/module-catalog-inventory$ ls -lh 
total 540K
-rw-rw-r-- 1 alex alex 180K dec 15 15:49 84b456b70f2868d080f50610073746f5fbf5d455.zip
...
```

This zip contains wrong version:
```
    public function getStockId()
    {
        return $this->getData(self::KEY_WEBSITE_ID);
    }
```

**Comment by flancer64** [comment]
Magento-CE-2_1_3_tar_bz2-2016-12-13-09-10-13.tar.bz2 also contains wrong version of the "\Magento\CatalogInventory\Model\Stock\Status::getStockId"

**Comment by flancer64** [comment]
@vkublytskyi, please take into attention this issue. @alena-marchenko @mmansoorebay have no activity on github in the last months.

**Comment by flancer64** [comment]
@MomotenkoNatalia, please take a look at this issue.

**Comment by flancer64** [comment]
Version 2.1.4 contains the same bug. Is it a feature?

**Comment by fe-lix-** [comment]
The ticket MAGETWO-58941 is closed and looks like that this fix is targeted for version 2.2.0.

**Comment by flancer64** [comment]
Good news, @fe-lix- ! Thanks. I feared that this fix is targeted for M3.

**Comment by Ctucker9233** [comment]
@fe-lix- Do you have commit numbers handy for those who can't wait for 2.2. ?

**Comment by fe-lix-** [comment]
@Ctucker9233 it's in the branch `develop`, here is the commit of the merge : 

https://github.com/magento/magento2/commit/a1a3c72fc27ff492d8a0eb85647d2a5817609306#diff-e642aff4a57735e359f4d8de80b3996e

**Comment by flancer64** [comment]
Commit a1a3c72 was  on Sep 26, 2016, the last changes for `/app/code/Magento/CatalogInventory/Model/Stock/Status.php` were on Jan 5, 2017. `develop` branch has a [right code](https://github.com/magento/magento2/blob/develop/app/code/Magento/CatalogInventory/Model/Stock/Status.php#L103).

Version Magento 2.1.4  was appeared at Feb 7, 2017 and this version has the [bug](https://github.com/magento/magento2/blob/6891ccaa675b399b3d3cf299dda5e645290ae4fc/app/code/Magento/CatalogInventory/Model/Stock/Status.php#L102). `Status.php` file was changed 11 months ago (on Mar 17, 2016). Probably @okorshenko can explain this?

**Comment by okorshenko** [comment]
@flancer64 the code from develop branch will be released in 2.2.0. 
All releases 2.1.x go from branch 2.1
That is the reason why this fix is not included in 2.1.4

**Comment by flancer64** [comment]
Thanks for the answer, @okorshenko. Does it mean that this fix will never be included in 2.1.x releases?

**Comment by okorshenko** [comment]
@flancer64 I will discuss this issue with our Product Owners to include it to some patch release.

**Comment by flancer64** [comment]
Congrats, guys! It's fixed in 2.1.6.

**Comment by adragus-inviqa** [comment]
Why congrats? This has been fixed almost a year ago. :/

**Comment by flancer64** [comment]
@adragus-inviqa , why congrats? Try to download "Magento-CE-2.1.5", for example, from https://magento.com/tech-resources/download ("Release Archive" tab), extract it and open file `vendor/magento/module-catalog-inventory/Model/Stock/Status.php`. Find method `getStockId()` and look inside:
```php
    public function getStockId()
    {
        return $this->getData(self::KEY_WEBSITE_ID);
    }
```

Do the same with version 2.1.6 and you will see:

```php
    public function getStockId()
    {
        return $this->getData(self::KEY_STOCK_ID);
    }
```

So, congrats!

**Pull request merged**
