### PR TITLE
fixed issue 22527 wishlist and compare icon alignment

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)
Wishlist and compare icons were not aligned in the middle with "Add to Cart" on the Catagory and Search page. I have fixed the issue by adding vertical-align:middle; 

### Fixed Issues (if relevant)
1. magento/magento2#22527: Wishlist and compare icon align issue in product listing page

### Manual testing scenarios (*)
1. Click on Category name to open the catalog category view page.
2. Hover over a product to check the alignment.
3. Search a product to open the catalog search page.
4. Hover over a product to check the alignment.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22532) <br/>All committers have signed the CLA.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4840](https://jira.corp.magento.com/browse/ENGCOM-4840) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@sanjaychouhan-webkul thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
