### PR TITLE
33194: Update Swagger UI to 3.51.1 version and configure security definitions

### LINKED ISSUE #33194: Swagger UI is out of date (version 3 is latest)
### Preconditions
1. Magento 2.x

### Steps to reproduce
1. Open /swagger route using browser

### Expected result
1. Swagger UI is using version 3

### Actual result
1. Swagger UI is using version 2

##  

Is there any plans to upgrade swagger UI, or anything blocking this currently? See comment here: <https://github.com/magento/magento2/pull/7446#issuecomment-350105915>

**Original Report**: <https://github.com/magento/magento2/issues/12595> by @careys7

### PR DESCRIPTION
**Pull request by mmezhensky**
### Description (*)

Updating Swagger UI to last version 3.51.1

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33194

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by andrewbess** [comment]
@magento run Unit Tests

**Comment by mmezhensky** [comment]
@magento run Unit Tests

**Comment by hostep** [comment]
Hi @mmezhensky

Could you rename the 2 new javascript files (`swagger-ui-es-bundle.js` & `swagger-ui-es-bundle-core.js`) and use `.min.js` in their filenames?

It appears these two files are already minified. When using `.min.js` as filenames it will prevent Magento from trying to minify them again during the static content deploy phase.

We already needed [to do this in the past](https://github.com/magento/magento2/pull/17627) explicitly for the swagger js files to fix [an issue](https://github.com/magento/magento2/issues/16927) with the minifier.

Thanks!

**Comment by mmezhensky** [comment]
@magento run Unit Tests

**Comment by mmezhensky** [comment]
@hostep
I added these changes.
Thank you so much for being so helpful.

**Comment by mmezhensky** [comment]
@magento run all tests

**Comment by mmezhensky** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run WebAPI Tests

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Review by andrewbess — APPROVED** [review]
Hello @mmezhensky 
Thank you for your contribution.
The changes are approved.

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, thank you for the review.
[ENGCOM-9145](https://jira.corp.magento.com/browse/ENGCOM-9145) has been created to process this Pull Request
:eight_spoked_asterisk: @andrewbess, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run WebAPI Tests

**Comment by andrewbess** [comment]
@magento run Functional Tests B2B

**Comment by Den4ik** [comment]
@magento run Functional Tests B2B

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9145](https://jira.corp.magento.com/browse/ENGCOM-9145) has been created to process this Pull Request

**Pull request merged**
