### PR TITLE
Update zip_codes.xml

### LINKED ISSUE #29984: [Issue] Update zip_codes.xml
This issue is automatically created based on existing pull request: magento/magento2#29972: Update zip_codes.xml

---------
Changed regex for zipcodes from Brazil. All zipcode must have 8 positions, with or without dash

### Preconditions: (*)
Magento 2.4-develop
Changed the regex to force 8 digits for zipcode in Brazil

### Related Pull Requests
n/a

### Fixed Issues (if relevant)
Didn't found issue but a lot of people asking for help in forums

### Steps to reproduce: (*)
Format of zipcodes in Brazil: 99999-999 or 99999999
1. Put any number less than 8 digits (ex: 01001) - ERROR
2. Put a number with 8 digits, without dash (ex: 01001-001) - OK
3. Put a number with 5 digits, a dash and more 3 digits (ex: 01001-001) - OK

**Actual Result:** :heavy_multiplication_x: It possible to use 5 digits ZIP code

Screenshot from 2020-09-21 16-25-31

**Expected Result:** :heavy_check_mark: all zip codes for Brazil must have 8 digits

### Questions or comments
First contribution to Magento, please let me know if I need to provide more info

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [N/A] All new or changed code is covered with unit/integration tests (if applicable)
 - [N/A] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by marcostrama**
Changed regex for zipcodes from Brazil. All zipcode must have 8 positions, with or without dash

### Description (*)
Changed the regex to force 8 digits for zipcode in Brazil

### Related Pull Requests
n/a

### Fixed Issues (if relevant)
Didn't found issue but a lot of people asking for help in foruns

### Manual testing scenarios (*)
Format of zipcodes in Brazil: 99999-999 or 99999999
1. Put any number less than 8 digits (ex: 01001) - ERROR
2. Put a number with 8 digits, without dash (ex: 01001-001) - OK
3. Put a number with 5 digits, a dash and more 3 digits (ex: 01001-001) - OK

### Questions or comments
First contribution to Magento, please let me know if I need to provide more info

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [N/A] All new or changed code is covered with unit/integration tests (if applicable)
 - [N/A] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29984: Update zip_codes.xml

### CODE REVIEW

**Comment by sidolov** [comment]
Hi  @marcostrama , please, sign Adobe CLA, otherwise, we can't process your pull request

**Comment by sidolov** [comment]
@magento create issue

**Comment by marcostrama** [comment]
@sidolov just signed, thanks

**Comment by sidolov** [comment]
@magento run all tests

**Review by sidolov — CHANGES_REQUESTED** [review]
@marcostrama please, take a look a failed integration test, it's related to the changes

**Comment by marcostrama** [comment]
@magento run all tests

**Comment by marcostrama** [comment]
Hi @sidolov can you give a help here? Functional tests failed with a message:

```
SUITE PRECONDITION FAILED:
Waited for 60 secs but text 'auth[code=' still not found
```

Appears to not be related with my changes, maybe some authentication failed for the test. I'm new at this project and I don't now how to proceed. thanks

**Comment by sidolov** [comment]
Hi @marcostrama , failures did not cause by your changes, looks like the problem with ASI tests. There is no action required from your side!

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8220](https://jira.corp.magento.com/browse/ENGCOM-8220) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@marcostrama thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

Put any number less than 8 digits 

**Before:** :x: Format of zipcodes in Brazil: 99999-999 or 99999

Screenshot from 2020-09-21 16-25-31

**After:** :heavy_check_mark: Format of zipcodes in Brazil: 99999-999 or 99999999

**Comment by engcom-Alfa** [comment]
@magento run all tests

**Pull request merged**
