### PR TITLE
Fix error implementing getStreetLine3 and getStreetLine4 methods

### LINKED ISSUE #29593: [Issue] Fix error implementing getStreetLine3 and getStreetLine4 methods
This issue is automatically created based on existing pull request: magento/magento2#27947: Fix error implementing getStreetLine3 and getStreetLine4 methods

---------
### Description (*)
Fix error implementing getStreetLine3 and getStreetLine4 methods.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by TadeuRodrigues**
### Description (*)
Fix error implementing getStreetLine3 and getStreetLine4 methods.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29593: Fix error implementing getStreetLine3 and getStreetLine4 methods

### CODE REVIEW

**Comment by bradleybrecher** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @bradleybrecher. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @bradleybrecher, here is your [Magento instance](https://i-27947-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27947-2-4-develop.instances.magento-community.engineering/admin_4727](https://i-27947-2-4-develop.instances.magento-community.engineering/admin_4727)
Login: `73a464d1` Password: `187b62aacd87`
Instance will be terminated in up to 3 hours.

**Comment by sidolov** [comment]
@magento create issue

**Review by lenaorobei — CHANGES_REQUESTED** [review]
@TadeuRodrigues, Could you please shed some light what stays behind this change? What is the business case for it?

If additional multiple street lines are required, they should be implemented in customization/extension. Core supports 2 street lines only.

**Comment by TadeuRodrigues** [comment]
@lenaorobei I didint understand, core supports 2 street lines only to payment but 4 to customer register?? I submitted that code to fix this problem, I use 4 street lines to customer register but I receive only 2 to payment gateway.

**Comment by lenaorobei** [comment]
@magento give me test instance

**Comment by lenaorobei** [comment]
@magento give me 2.4-develop instance

**Comment by lenaorobei** [comment]
@magento give me 2.4-develop instance

**Comment by lenaorobei** [comment]
@TadeuRodrigues, I've tried to both - create user and manage address book and guest checkout. Both flows shows 2 street lines.

Screen Shot 2020-09-15 at 7 45 06 AM
Screen Shot 2020-09-15 at 7 48 23 AM

Could you please provide steps to reproduce, how I can see 4 street lines?

You can use test instance from https://github.com/magento/magento2/pull/27947#issuecomment-692755424

**Comment by TadeuRodrigues** [comment]
Thanks @lenaorobei but you can change how many lines you will use to customer.

Stores > Configuration > Customers > Customer Configuration > Name and Address Options

Captura de tela de 2020-09-15 14-32-08

**Comment by lenaorobei** [comment]
@TadeuRodrigues got it, thanks. I checked the current implementation and it looks to me, that payment flow needs to support this configuration and use user specified value instead of hardcoded method names.

**Comment by TadeuRodrigues** [comment]
@lenaorobei what do you think to use as parameter??

For example:
getStreetLine(1)

**Comment by lenaorobei** [comment]
I think, it should be consistent with customer address implementation.

**Pull request closed without merging**
