### PR TITLE
magento/magento2#27500 - Replace deprecated constructs from Payment P…

### PR DESCRIPTION
**Pull request by cristiano-pacheco**
…HPUnit.

This PR is about the issue magento/magento2#27500 on item app/code/Magento/Payment

### Description (*)
Changes were made to the payment module to be compatible with PHPunit in version 8.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by cristiano-pacheco** [comment]
Hi @lbajsarowicz  could you review this PR? please.

I made the changes for the tests of the Magento_Payment module, and tests of other modules are broken and therefore this PR did not pass.

How can I solve this?

**Comment by lbajsarowicz** [comment]
Please take a look at Static Tests.
There you have information about line length exceeded and lack of annotations.

I will take care about CustomerBalance module.
That is actually strange, that something there depends on your Unit Tests.

**Comment by slavvka** [comment]
@engcom-Foxtrot could you please taske a look at the failing Unit tests

**Review by slavvka — CHANGES_REQUESTED** [review]
@engcom-Foxtrot could you please taske a look at the failing Unit tests

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@cristiano-pacheco Could you please resolve the conflicts

**Comment by slavvka** [comment]
@cristiano-pacheco I am closing it since it was implemented in another PR.  Thank you for your efforts!

**Pull request closed without merging**
