### PR TITLE
Improve category url integrity 

### LINKED ISSUE #38627: Category URL Path issue in multi-store
### Preconditions and environment

- Magento version 2.4.6 & 2.4.7

### Steps to reproduce

1. Create 2 stores ( default = 1, other_store = 2), same category root assigned.
2. Create this category tree : 
    - Cat A (url key = `a` in default view. url key = `other_a` in store 2)
         -  Cat AB (url key = `b` in default view)
3. Check `catalog_category_entity_varchar` table where attribute_id = `(ID of url_path)` and category_id = `(ID of cat AB)`. You should see : `a/b` for store 0 and `other-a/b` for store 2.
4. Check frontend canonical url for store2 - AB category page. You should see `https://.../other-a/b`
5. Change url_key for cat AB, in default view, for `b2`
6. Check again `catalog_category_entity_varchar` table where attribute_id in `(ID of url_path)` and category_id = (ID of cat AB). 
7. Check again canonical url for store2 AB category page.

### Expected result

- `a/b2` for store 0 and `other-a/b2` for store 2.
- Url of category = `https://.../other-a/b2`, Canonical : `https://.../other-a/b2`

### Actual result

- `a/b2` for store 0 and `other-a/b` for store 2.
- Url of category = `https://.../other-a/b2`, Canonical : `https://.../other-a/b`

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by digitalrisedorset**
When the category is saved in Magento backend and particularly when the scope is a custom store, some use cases leave some url key or url path with data that break features like the canonical url in the category page on the frontend. 

### Description (*)
The changes are twofold:

1. ensure the url path is valid for the global scope and for all the store scope when a category url key is changed
2. ensure the url path is removed for a store scope if the category does not have custom url key for the store scope

### Fixed Issues (if relevant)
1. Fixes magento/magento2#38627

### Manual testing scenarios (*)
**use case 1:** the category url key is set for the global scope and a different value is set for the store scope 2
```
global scope: store id = 0, url path: cat1
custom scope: store id = 2, url path: cat1_2
```
- we want to validate the custom url path is removed correctly if the the custom store scope is reverted to use the global scope

**use case 2:** starting with a parent category like the above (with 2 scope set), the child category url key is set for the global scope and the category url key is not set for either of the default store or custom store: only store 0 has a url key

`global scope: store id = 0, url path: cat1/cat12`
- we want to validate the custom url path for the store 2 is removed when the parent category custom scope is reverted

**use case 3:** the child category uses a url key for the global scope (store 0) and uses a custom url key (cat12_2) for the custom store (store 2)

```
global scope: store id = 0, url path: cat1/cat12
custom store scope: store id = 2, url path: cat1/cat12_2
```

**use case 4:** the child category uses a url key for the default store scope (store = 1) (cat12_1) and uses no custom url key for the custom store (store 2)

```
global scope: store id = 0, url path: cat1/cat12
default store scope: store id = 1, url path: cat1/cat12_1
```

**use case 5:** the child category uses a custom url key (cat12_1) for the global scope and uses a custom url key (cat12_2) for the custom store (store 2)

```
global scope: store id = 0, url path: cat1/cat12
default store scope: store id = 1, url path: cat1/cat12_1
custom store scope: store id = 2, url path: cat1/cat12_2
```

### Questions or comments
The PR changes resolve the issue with canonical url being invalid. However, if the parent category url is changed afterwards, it does break the category path. I have attempted to add integration tests but this attempt was shortlived once I realised the category save process cannot be triggered by a single method but rather by using a list of events/plugins and resources. If we wanted this area of the system bug free, we'd need this area (category backend save controller) to be refactored

The changes duplicate existing snippets to try to keep the other logic to work like before as much as possible. 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by digitalrisedorset** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hello,

Internal team has started to work on it

Thanks

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
As internal team is started working on this PR. We are moving this PR `On Hold` till the further updates.

**Comment by engcom-Bravo** [comment]
Hi @digitalrisedorset,

Thanks for your Contribution!!.

Internal Team analysed the issue and this is adobe commerce default behaviour and not a bug. We discussed this internally with the product owner and confirmed that this is working as expected. We will not be modifying the functionality at this time.

Thank You.

**Pull request closed without merging**
