### PR TITLE
magento/magento2#: Add i18 translations for Reset password GraphQL mutations

### LINKED ISSUE #29548: [Issue] magento/magento2#: Add i18 translations for Reset password GraphQL mutations
This issue is automatically created based on existing pull request: magento/magento2#28865: magento/magento2#: Add i18 translations for Reset password GraphQL mutations

---------

### Description (*)

PR adds `i18` translations for the reset password GraphQl mutations created in https://github.com/magento/magento2/pull/27876.

### Related Pull Requests

- https://github.com/magento/magento2/pull/27876

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by atwixfirster**
### Description (*)

PR adds `i18` translations for the reset password GraphQl mutations created in https://github.com/magento/magento2/pull/27876.

### Related Pull Requests

- https://github.com/magento/magento2/pull/27876

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29548: magento/magento2#: Add i18 translations for Reset password GraphQL mutations

### CODE REVIEW

**Comment by rogyar** [comment]
@magento run WebAPI Tests

**Comment by sidolov** [comment]
@magento create issue

**Comment by rogyar** [comment]
@atwixfirster could you merge the mainline into your branch and resolve the conflicts, please? Thank you!

**Comment by atwixfirster** [comment]
@magento run all tests

**Review by rogyar — APPROVED** [review]
The failing tests do not seem to be related to the current changeset

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8046](https://jira.corp.magento.com/browse/ENGCOM-8046) has been created to process this Pull Request

**Comment by sidolov** [comment]
Pull request successfully imported to branch `imported-magento-magento2-28865` in the `magento-engcom/magento2ce` repository.

**Comment by sidolov** [comment]
Pull request successfully imported into `magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-28865`.

**Comment by nrkapoor** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
This PR is duplicate of [PR](https://github.com/magento/magento2/pull/28950) .Hence, closing this PR.

**Pull request closed without merging**
