### PR TITLE
Cleanup ObjectManager usage - Magento_Bundle

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This PR cleanups ObjectManager usage in Magento_Bundle, adds additional dependencies with backward compatibility to api classes, and removes object manager instantiation from non-api classes

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Bartlomiejsz** [comment]
@magento-engcom-team not sure why Unit Tests are marked as failing since there are no failures in Allure report for neither CE, EE or B2B

**Comment by ihor-sviziev** [comment]
@magento run Unit Tests

**Comment by ihor-sviziev** [comment]
@Bartlomiejsz I believe it's already ready for review?

**Comment by Bartlomiejsz** [comment]
Hi @ihor-sviziev to be honest I'm not sure, I'll try to verify later today if there are any other occurrences to be fixed in this module and will let you know

**Comment by Bartlomiejsz** [comment]
Hi @ihor-sviziev, I added some additional changes, once the tests are passed will be ready for review

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7170](https://jira.corp.magento.com/browse/ENGCOM-7170) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Echo** [comment]
Failed unit tests not related to the changes in this PR

**Pull request merged**
