### PR TITLE
fix: remove unused ID

### PR DESCRIPTION
**Pull request by DanielRuf**
### Description

The ID is totally unused so we do not have to use Knockout here and do not even need this ID.

### Fixed Issues (if relevant)

1. 

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by orlangur** [comment]
Unfortunately, we can't accept such Pull Requests to 2.2 release line, all code cleanup like typos, spelling mistakes, etc should be delivered to 2.3 release line. For more information, please, refer to [Magento Code Contributions Guide](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#rules).

**Comment by DanielRuf** [comment]
> Unfortunately, we can't accept such Pull Requests to 2.2 release line, all code cleanup like typos, spelling mistakes, etc should be delivered to 2.3 release line

Isn't this the case with forward ports? Some weeks ago I could still create PRs for such things and I saw them merged and now this?

**Comment by orlangur** [comment]
@DanielRuf this is pretty new

> hey `@here`, yesterday we updated Code contribution docs (https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html),

> The main changes made in “Accepted pull requests and ported code” section, we defined few new rules for different submission types

**Comment by DanielRuf** [comment]
In general the change of another contributor was to set the ID with knockout, which does the same like mine PR does- fix the duplicate ID issue.

But the current code has a big drawback: knockout / JS for a trivial issue which is only because of an unused ID (it is actually not used at all) which impacts the performance of the DOM. This is not how it should have been "fixed" as it is not good for the performance.

**Comment by DanielRuf** [comment]
> @DanielRuf this is pretty new

Se my last comment about performance and the impact on the DOM. In general it should have been reverted and the ID removed. I was just one week late as I saw this last week to but thought it would have been correctly fixed and checked if we really need the ID (which is not the case).

**Comment by DanielRuf** [comment]
But to be exact, this is not a code cleanup but a fix, the right fix.

**Comment by DanielRuf** [comment]
See https://github.com/magento/magento2/issues/17061

**Comment by orlangur** [comment]
@DanielRuf thanks, totally makes sense to me as it was introduced recently and it's better to redo fix.

https://github.com/DanielRuf/magento2/commit/d78fd0c7a9907cf14a0ff48d3bb6007392a7ba9e
Here @VladimirZaets introduced unneeded CSS class which violates Code Demarcation Standard. Could you please remove this class, add data attribute like `data-form="billing-new-address"` and change selector in functional test accordingly?

**Comment by DanielRuf** [comment]
> Here @VladimirZaets introduced unneeded CSS class which violates Code Demarcation Standard. Could you please remove this class, add data attribute like data-form="billing-new-address" and change selector in functional test accordingly?

Done.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-2619](https://jira.corp.magento.com/browse/ENGCOM-2619) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
