### PR TITLE
fix Rest-API updating product stock_item deletes downloadable product data

### LINKED ISSUE #21811: Rest-API updating product stock_item deletes downloadable_product_links
### Preconditions (*)

1. Magento 2.4-develop
2. Create regular downloadable product, upload downloadable content

### Steps to reproduce (*)

1. Update product stock_item values using a PUT call. For example: {"product": {"sku": "Download1", "status": "1", "name": "Test Name", "price": "11.99", "type_id": "downloadable", "extension_attributes": {"stock_item": {"manage_stock": false}}}}

### Expected result (*)

1. The stock_item data would be updated and downloadable product links and samples are preserved since they're not included in the extension_attributes being sent in the update.

### Actual result (*)

1. After update product has no links to download content (no downloadable information). This is similar to https://github.com/magento/magento2/issues/15923 except that didn't resolve being able to post a subset of extension_attributes.
image

### PR DESCRIPTION
**Pull request by engcom-Charlie**
### Description (*)

Fixed and covered by test

### Fixed Issues (if relevant)

1. Fixes magento/magento2#21811

### Manual testing scenarios (*)

See #21811

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Charlie** [comment]
@magento run Integration Tests

**Comment by engcom-Charlie** [comment]
@magento run WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Review by Stepa4man — CHANGES_REQUESTED** [review]
Hi @engcom-Charlie 
Thanks for your contribution

Please add to all changed files
```php
    declare(strict_types=1);
```

You can read more [here](https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html#1-basic-programming-principles)

I would also ask you to add type declaration everywhere in files you changed and replace object declaration with a more precise type.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by Stepa4man — APPROVED** [review]

**Comment by Stepa4man** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, thank you for the review.
[ENGCOM-7715](https://jira.corp.magento.com/browse/ENGCOM-7715) has been created to process this Pull Request
:eight_spoked_asterisk: @Stepa4man, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Manual testing scenario:**

- Create regular downloadable product, upload downloadable content
- Update product stock_item values using a PUT call: `V1/products/{sku}`
`{
    "product": {
        "sku": "Download1",
        "status": "1",
        "name": "Test Name",
        "price": "99.99",
        "type_id": "downloadable",
        "extension_attributes": {
            "stock_item": {
                "manage_stock": false
            }
        }
    }
}`
- Go to downloadable product in admin panel

:x: **Before:**

- product has no links to download content (no downloadable information)

#28799Main
Response:
```{
    "id": 1,
    "sku": "Download1",
    "name": "Test Name",
    "attribute_set_id": 4,
    "price": 9.99,
    "status": 1,
    "visibility": 4,
    "type_id": "downloadable",
    "created_at": "2020-06-25 12:36:24",
    "updated_at": "2020-06-25 13:15:53",
    "extension_attributes": {
        "website_ids": [
            1
        ],
        "category_links": [
            {
                "position": 0,
                "category_id": "3"
            }
        ],
        "stock_item": {
            "item_id": 1,
            "product_id": 1,
            "stock_id": 1,
            "qty": 1000,
            "is_in_stock": true,
            "is_qty_decimal": false,
            "show_default_notification_message": false,
            "use_config_min_qty": true,
            "min_qty": 0,
            "use_config_min_sale_qty": 1,
            "min_sale_qty": 1,
            "use_config_max_sale_qty": true,
            "max_sale_qty": 10000,
            "use_config_backorders": true,
            "backorders": 0,
            "use_config_notify_stock_qty": true,
            "notify_stock_qty": 1,
            "use_config_qty_increments": true,
            "qty_increments": 0,
            "use_config_enable_qty_inc": true,
            "enable_qty_increments": false,
            "use_config_manage_stock": true,
            "manage_stock": true,
            "low_stock_date": null,
            "is_decimal_divided": false,
            "stock_status_changed_auto": 0
        }
    },
    "options": [],
    "media_gallery_entries": [],
    "custom_attributes": [
        {
            "attribute_code": "options_container",
            "value": "container2"
        },
        {
            "attribute_code": "url_key",
            "value": "download1"
        },
        {
            "attribute_code": "msrp_display_actual_price_type",
            "value": "0"
        },
        {
            "attribute_code": "gift_message_available",
            "value": "2"
        },
        {
            "attribute_code": "required_options",
            "value": "0"
        },
        {
            "attribute_code": "has_options",
            "value": "0"
        },
        {
            "attribute_code": "meta_title",
            "value": "Download1"
        },
        {
            "attribute_code": "meta_keyword",
            "value": "Download1"
        },
        {
            "attribute_code": "meta_description",
            "value": "Download1 "
        },
        {
            "attribute_code": "tax_class_id",
            "value": "2"
        },
        {
            "attribute_code": "category_ids",
            "value": [
                "3"
            ]
        },
        {
            "attribute_code": "links_purchased_separately",
            "value": "0"
        },
        {
            "attribute_code": "samples_title",
            "value": "Samples"
        },
        {
            "attribute_code": "links_title",
            "value": "Links"
        }
    ]
}
```


:heavy_check_mark: **After:**

- downloadable product links and samples are preserved

#28799PR
Response:
```{
    "id": 1,
    "sku": "Download1",
    "name": "Test Name",
    "attribute_set_id": 4,
    "price": 99.99,
    "status": 1,
    "visibility": 4,
    "type_id": "downloadable",
    "created_at": "2020-06-25 12:36:24",
    "updated_at": "2020-06-25 13:02:08",
    "extension_attributes": {
        "website_ids": [
            1
        ],
        "category_links": [
            {
                "position": 0,
                "category_id": "3"
            }
        ],
        "stock_item": {
            "item_id": 1,
            "product_id": 1,
            "stock_id": 1,
            "qty": 1000,
            "is_in_stock": true,
            "is_qty_decimal": false,
            "show_default_notification_message": false,
            "use_config_min_qty": true,
            "min_qty": 0,
            "use_config_min_sale_qty": 1,
            "min_sale_qty": 1,
            "use_config_max_sale_qty": true,
            "max_sale_qty": 10000,
            "use_config_backorders": true,
            "backorders": 0,
            "use_config_notify_stock_qty": true,
            "notify_stock_qty": 1,
            "use_config_qty_increments": true,
            "qty_increments": 0,
            "use_config_enable_qty_inc": true,
            "enable_qty_increments": false,
            "use_config_manage_stock": true,
            "manage_stock": true,
            "low_stock_date": null,
            "is_decimal_divided": false,
            "stock_status_changed_auto": 0
        },
        "downloadable_product_links": [
            {
                "id": 2,
                "title": "Test Link",
                "sort_order": 1,
                "is_shareable": 1,
                "price": 0,
                "number_of_downloads": 0,
                "link_type": "file",
                "link_file": "/t/e/test.txt",
                "sample_type": "file",
                "sample_file": "/t/e/test.txt"
            }
        ]
    },
    "options": [],
    "media_gallery_entries": [],
    "custom_attributes": [
        {
            "attribute_code": "options_container",
            "value": "container2"
        },
        {
            "attribute_code": "url_key",
            "value": "download1"
        },
        {
            "attribute_code": "msrp_display_actual_price_type",
            "value": "0"
        },
        {
            "attribute_code": "gift_message_available",
            "value": "2"
        },
        {
            "attribute_code": "required_options",
            "value": "0"
        },
        {
            "attribute_code": "has_options",
            "value": "0"
        },
        {
            "attribute_code": "meta_title",
            "value": "Download1"
        },
        {
            "attribute_code": "meta_keyword",
            "value": "Download1"
        },
        {
            "attribute_code": "meta_description",
            "value": "Download1 "
        },
        {
            "attribute_code": "tax_class_id",
            "value": "2"
        },
        {
            "attribute_code": "category_ids",
            "value": [
                "3"
            ]
        },
        {
            "attribute_code": "links_purchased_separately",
            "value": "0"
        },
        {
            "attribute_code": "samples_title",
            "value": "Samples"
        },
        {
            "attribute_code": "links_title",
            "value": "Links"
        }
    ]
}
```

**Pull request merged**
