### PR TITLE
Add preload support for images/fetch via XML/Priority Hints Support

### PR DESCRIPTION
**Pull request by in-session**
fetch: Resource to be accessed by a fetch or XHR request, such as an ArrayBuffer or JSON file. If a critical area is made via Ajax call, it can also be triggered earlier via perload. This can affect different pages, so this should be controllable via XMl.

Referencing: 
https://web.dev/preload-responsive-images/#preload-overview
https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload#including_media

### CODE REVIEW

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by in-session** [comment]
@magento run Functional Tests B2B

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE, Functional Tests EE, Integration Tests, Unit Tests

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento run Functional Semantic Version Checker, Functional Tests EE, Unit Tests

**Comment by in-session** [comment]
@magento run Semantic Version Checker, Functional Tests EE

**Pull request closed without merging**
