### PR TITLE
Fix issue where a zero price in tiered pricing would display price in…

### PR DESCRIPTION
**Pull request by BernardRobbins**
…stead, but cart would reflect correct price of 0.

### Fixed Issues (if relevant)
None found.

### Manual testing scenarios (*)
1. Create product
2. Set Product price > 0
3. Advanced Pricing -> Price -> Create Customer Group Price with All Websites, All Groups, 1 quantity, Fixed Price, 0 cost.

Without fix, product price will display, with fix correct price of 0. Cart will display correct price of 0 in either case.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18677) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @BernardRobbins. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rodrigowebjump** [comment]
Hi @BernardRobbins 
Thanks for your PR, but there is an already approved change in PR #18631 that also fix this issue.
So I am closing yours.

**Comment by BernardRobbins** [comment]
Hi @rodrigowebjump, 

That's great that someone else has gotten this. I apologize about not finding it when I searched. Not sure why their fix didn't show. 

I don't believe that Mahesh's fix solves the issue properly. I feel that checking that the value is numeric instead of anything not bool false would be a better way to go in that it better conveys what we are truly testing for. Let me know if there is a formal way of requesting this change to the pull request.

**Pull request closed without merging**
