### PR TITLE
Best sellers sort and auto move out of stock products to the bottom

### PR DESCRIPTION
**Pull request by winterk80**
I would like to submit a feature request. Problem exists in 2.1.7+ and also 2.2.2

Magento lacks proper inventory management of out of stock products. Out of stock products should automatically move to the bottom of the product listing page and then automatically move back up to the top when they come back in stock. This should be independent of the visual merchandiser position for the product. This should be a global move out of stocks products to bottom of product listing option.

Magento should also allow for sorting sort order by bestsellers in the visual merchandiser clients. It is very cumbersome how it is currently. Bestsellers should be based upon number of orders that the item exists in not based upon quantity in each order. This is because if you have an item that is typically ordered in multiples it will throw off the bestseller ranking.

Additionally showing 90 day sales for each product while visually merchandising would be very very powerful for merchandisers.

Being able to sort by user defined product attributes when adding products in visual merchandiser would be extremely helpful. For example we have a user-defined variable for discontinued. We would like to filter those products out when adding products to categories so they don't get accidentally added

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=13699) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=13699) before we can accept your contribution.<br/>**4** out of **11** committers have signed the CLA.<br/><br/>:white_check_mark: okorshenko<br/>:white_check_mark: gil--<br/>:white_check_mark: omiroshnichenko<br/>:white_check_mark: ishakhsuvarov<br/>:x: aakimov<br/>:x: slopukhov<br/>:x: mslabko<br/>:x: magento-cicd2<br/>:x: zakdma<br/>:x: RuslanKostiv1<br/>:x: rganin

**Comment by orlangur** [comment]
@winterk80 please edit this PR so that it targets `2.2-develop` using a proper branch from your fork.

**Comment by winterk80** [comment]
2.2-develop is not an option

**Comment by orlangur** [comment]
@winterk80 however, `2.2` branch cannot be targeted. Please check http://devdocs.magento.com/guides/v2.0/contributor-guide/contributing.html#pull_request and create a new pull request targeting proper branch.

**Comment by clion007** [comment]
> 2.2-develop is not an option
Do you have any solution for the issue you said? I have the same problem and when I sort by bestseller through plugin toolbar class use joinleft method of select class as below, the product connection item count not work well.

$toolbarCollection
                     ->getSelect()
                     ->joinLeft(
                        'sales_order_item',
                        'e.entity_id = sales_order_item.product_id and sales_order_item.store_id=cat_index.store_id',
                         array('qty_ordered'=>'SUM(sales_order_item.qty_ordered)'))
                    ->group('e.entity_id')
                    ->order('qty_ordered desc');

I want to know the right solution to sort products by bestseller. Is there anyone can tell me.

**Pull request closed without merging**
