### PR TITLE
fix for pub/static/versionXXXX path

### PR DESCRIPTION
**Pull request by hidonet**
fix for pub/static/versionXXXX path

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=10446) <br/>All committers have signed the CLA.

**Comment by okorshenko** [comment]
Hi @hidonet could you please provide more details about the issue you fixed? How to reproduce it? Thank you

**Comment by hidonet** [comment]
I've installed magento 2.1.7 and deployed static files. System created urls like pub/static/versionXXXXXX/. I've used your nginx.conf sample and nginx not rewrited file paths. I've changed your static path rewrite and added to conf. Static path rewrites fixed after that.

**Comment by vherasymenko** [comment]
@hidonet Hi.

**Can`t reproduce issue:**

**Steps which were executed:**

1. Install Magento from develop branch
2. Change line in nginx.conf.sample "root $MAGE_ROOT/pub;" to "root $MAGE_ROOT;"
3. Run command setup:static-content:deploy for generating new static files
4. Flush cache using php bin/magento cache:flush
5. And clean browser cookies and data.
6. Check frontend side

**Actual Result: Static files not displayed**

**Expected Result: Static files should be displayed**

Note: Tried with your PR and nothing changed after it.

Could you provide more details about your environment, and if you can attach your nginx and nginx.conf.sample files.

**Comment by okorshenko** [comment]
Hi @hidonet 
Could you please provide more details? Please, see comment from @vherasymenko

**Comment by hidonet** [comment]
You can close this pull request. This is my mistake. I've used root directory without root.

**Pull request closed without merging**
