### PR TITLE
GraphQL product attribute added by admin showed DEPRECATED in ProductInterface #36037

### LINKED ISSUE #36037: GraphQL product attribute added by admin showed DEPRECATED in ProductInterface
### Preconditions and environment

- Magento version 2.4.5

### Steps to reproduce

1. Add new product attribute from admin
2. Set Storefront properties Visible on Catalog Pages on Storefront to Yes to expose it on api
3. Verify the new field in ProductInterface with a GraphQL client (I use Altair GraphQL Client)
Ex: Run the graphql [query](https://devdocs.magento.com/guides/v2.4/graphql/interfaces/simple-product.html) with "custom_attributes" Ref [devdocs](https://devdocs.magento.com/guides/v2.4/graphql/interfaces/product-interface.html)
### Expected result

The field hasn't to be DEPRECATED

### Actual result

The field result DEPRECATED and show the message below.

DEPRECATED:
Use the custom_attributes field instead.

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by shomiadarshlt**
### Description (*)

GraphQL product attribute added by admin showed DEPRECATED in ProductInterface

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36037

### Manual testing scenarios (*)

1. Add new product attribute from admin.
2. Set Storefront properties Visible on Catalog Pages on Storefront to Yes to expose it on api.
3. Verify the new field in ProductInterface with a GraphQL client .Now there is no warning of "**DEPRECATED:
Use the custom_attributes field instead.**" for the new attribute created 

Screenshot 2022-12-21 at 6 01 44 PM

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by shomiadarshlt** [comment]
@magento run all tests

**Comment by shomiadarshlt** [comment]
@magento run all tests

**Comment by shomiadarshlt** [comment]
@adobe/open-source-office The Adobe CLA has been signed and received the confirmation email for the same but yet its not reflected in the Pull request .

**Comment by shomiadarshlt** [comment]
https://github.com/magento run all tests

**Comment by shomiadarshlt** [comment]
https://github.com/magento run all tests

**Comment by engcom-November** [comment]
Development team is currently working on this issue.
Thank you.

**Comment by engcom-Bravo** [comment]
Hello,

We got the reply from PM as follows,

this ticket should be closed and we can't merge this PR because it would contradict our direction with custom attributes

the recommendation provided by [Daniel Mooney](https://jira.corp.adobe.com/secure/ViewProfile.jspa?name=dmooney) is valid, except that we are consolidating that same code into core,

Hence we are closing this issue.

Thanks.

**Pull request closed without merging**
