### PR TITLE
TYPO: Fix annoying typo in Quantity word

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Annoying to refer using stepKey with typo :-)

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by eduard13 — APPROVED** [review]
Totally agree 👍

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-7093](https://jira.corp.magento.com/browse/ENGCOM-7093) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Charlie** [comment]
Failed functional tests not related to the changes in this PR

**Pull request merged**
