### PR TITLE
[MFTF] add new  AdminOpenGeneralConfigurationPageActionGroup

### LINKED ISSUE #29847: [Issue] [MFTF] add new  AdminOpenGeneralConfigurationPageActionGroup
This issue is automatically created based on existing pull request: magento/magento2#29828: [MFTF] add new  AdminOpenGeneralConfigurationPageActionGroup

---------
This PR add new `AdminOpenGeneralConfigurationPageActionGroup` and uses this one instead 
`<amOnPage url="{{GeneralConfigurationPage.url}}" stepKey="goToGeneralConfig"/>`
       ` <waitForPageLoad stepKey="waitForConfigPage"/>`

### PR DESCRIPTION
**Pull request by Usik2203**
This PR add new `AdminOpenGeneralConfigurationPageActionGroup` and uses this one instead 
`<amOnPage url="{{GeneralConfigurationPage.url}}" stepKey="goToGeneralConfig"/>`
       ` <waitForPageLoad stepKey="waitForConfigPage"/>`

### Resolved issues:
1. [x] resolves magento/magento2#29847: [MFTF] add new  AdminOpenGeneralConfigurationPageActionGroup

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by lbajsarowicz — APPROVED** [review]
✔️  Thank you for your contribution

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-8114](https://jira.corp.magento.com/browse/ENGCOM-8114) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by sidolov — APPROVED** [review]

**Pull request merged**
