### PR TITLE
Use compiled config for generated data instead of general config

### LINKED ISSUE #38785: [Issue] Use compiled config for generated data instead of general config
This issue is automatically created based on existing pull request: magento/magento2#29954: Use compiled config for generated data instead of general config

---------

### Description (*)

When we used multi-container ASG we noticed that magento loads a lot of data from shared cache instance (Redis).
That during deploys of new containers leads to downtime or unstable behavior during containers swapping.
We decided to move instance-sensetive cache types such as compiled DI, events, to containers itself.
That prevents cache overriding in shared instance while old container is alive a few minutes after deploy.
```
...
            'compiled_config' => [
                'frontend' => 'file_cache'
            ],
...
```
So we checked what caches lead to such result, and moved some core classes from using shared config type to compiled_config because this data is instance-sensitive and not necessary should be shared.
This also reduses excessive network transfer and overhead of data that depended on certain version of code.

`Magento\Framework\Interception\PluginList\PluginList` - if new plugin cached in the shared config, the instance with older version can be down if did not find a new class. New instance may not execude the new code if this cache key was overriden by older container.
`Magento\Framework\Event\Config\Data` - as above, related to adding new events/observers
`Magento\Framework\App\Router\ActionList` - as above but related to adding new routes and controllers
`Magento\Ui\Config\Reader\Definition\Data` - related to new Ui components

Once those caches are generated, they are the same until you deploy new version of code.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Cache keys **event_config_cache**, **ui_component_configuration_definition_data**, **app_action_list**,**plugins** are stored in compiled config instance.
2. Running two servers with different code version and isolated compiled config does not lead to cache overriding or application downtime or unexpected behavior caused by using the cache from different app version.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ilnytskyi**
### Description (*)

When we used multi-container ASG we noticed that magento loads a lot of data from shared cache instance (Redis).
That during deploys of new containers leads to downtime or unstable behavior during containers swapping.
We decided to move instance-sensetive cache types such as compiled DI, events, to containers itself.
That prevents cache overriding in shared instance while old container is alive a few minutes after deploy.
```
...
            'compiled_config' => [
                'frontend' => 'file_cache'
            ],
...
```
So we checked what caches lead to such result, and moved some core classes from using shared config type to compiled_config because this data is instance-sensitive and not necessary should be shared.
This also reduses excessive network transfer and overhead of data that depended on certain version of code.

`Magento\Framework\Interception\PluginList\PluginList` - if new plugin cached in the shared config, the instance with older version can be down if did not find a new class. New instance may not execude the new code if this cache key was overriden by older container.
`Magento\Framework\Event\Config\Data` - as above, related to adding new events/observers
`Magento\Framework\App\Router\ActionList` - as above but related to adding new routes and controllers
`Magento\Ui\Config\Reader\Definition\Data` - related to new Ui components

Once those caches are generated, they are the same until you deploy new version of code.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Cache keys **event_config_cache**, **ui_component_configuration_definition_data**, **app_action_list**,**plugins** are stored in compiled config instance.
2. Running two servers with different code version and isolated compiled config does not lead to cache overriding or application downtime or unexpected behavior caused by using the cache from different app version.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38785: Use compiled config for generated data instead of general config

### CODE REVIEW

**Comment by ilnytskyi** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by mrtuvn** [comment]
CC @sivaschenko look great with final results

**Comment by ilnytskyi** [comment]
up

**Comment by ilnytskyi** [comment]
up

**Comment by ilnytskyi** [comment]
up, it's going to be 3 years for this small change
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento create issue

**Review by engcom-Hotel — APPROVED** [review]
Hello @ilnytskyi,

Thanks for the contribution! 

The changes seem good to me, hence approving the PR.

Thanks

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @ilnytskyi,

Thank you for your valuable contribution!

Can you please elaborate more on the Steps to reproduce. Kindly mention detailed steps in order to reproduce this issue as well as test the given solution in PR.

Thank you!

**Comment by ilnytskyi** [comment]
@engcom-Charlie 
As mentioned in the description.
The following cache keys **event_config_cache, ui_component_configuration_definition_data, app_action_list,plugins** will be stored in compiled config instance.

In case of changing the storage for that case from redis to files in env.php
```
'compiled_config' => [
                'frontend' => 'file_cache'
            ],
            ```
            
Related keys will be stored on disk instead of redis

**Comment by engcom-November** [comment]
@ilnytskyi,

As you have added the compiledConfig classes in the di.xml for the instance-sensetive cache. This PR can be verified by looking at the cache generated in the var/cache directory.
As it will have the cache instance of the class for which you have injected the dependency.

Please let us know if we can proceed with this approach.

**Comment by ilnytskyi** [comment]
@engcom-November yes I think your suggested approach is also viable

**Comment by engcom-November** [comment]
Hello @ilnytskyi,

Thank you for the collaboration and contribution.

### ✔️ QA Passed

As the instance-sensetive cache is moved to compiled config, this can be verified by looking at the cache generated at var/cache directory. As it will have the cache instance of the class.

**Before: ✖️**
There is no cache instance for the respective class.
image

**After: ✔️**
It can be seen that CompiledCache instance is present for the respective class.
image

This can be seen with all the four classes that has been moved to compiled config.

Thank you.

**Comment by engcom-November** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-November** [comment]
The repeating failures in Functional tests B2B, CE and EE are flaky and are known issues.

**Functional Tests B2B**
**Run 1:**
image

**Run 2:**
image

**Functional Tests CE**
**Run 1:**
image

**Run 2:**
image

**Functional Tests EE**
**Run 1:**
image

**Run 2:**
image

Known issues:
[ACQE-6856](https://jira.corp.adobe.com/browse/ACQE-6856) - SlideItemValidateVideoBackgroundVideoURLs
[ACQE-6774](https://jira.corp.adobe.com/browse/ACQE-6774) - StorefrontCashOnDeliveryPaymentForSpecificCountryTest
[ACQE-6695](https://jira.corp.adobe.com/browse/ACQE-6695) - TierPricingWhenPriceScopeIsWebsiteWorkingProperlyWithMultipleCurrenciesConfiguredTest
[ACQE-6799](https://jira.corp.adobe.com/browse/ACQE-6799) - StorefrontLoginFormCheckDuplicateValidateMessageTest
[ACQE-6786](https://jira.corp.adobe.com/browse/ACQE-6786) - StorefrontAddBundleDynamicProductToShoppingCartWithDisableMiniCartSidebarTest

Hence moving it to **Merge In Progress**

**Pull request merged**
