### PR TITLE
remove extra dot on "How to run Magento" docs in phpserver/README.md

### PR DESCRIPTION
**Pull request by amritms**
removes extra dot on "How to run Magento"

While following the steps in readme file, I encountered a error (extra dot) in "How to run Magento" section. This PR removes that extra dot.

### Description (*)
This change reduces the number of errors in documentation/readme files.

### Manual testing scenarios (*)
This only removes an extra dot in php run magento command. I have manually tested on my local machine.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20018) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @amritms. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by VladimirZaets** [comment]
Hi @amritms , please, sign CLA, otherwise, we can't process your pull request

**Comment by amritms** [comment]
@VladimirZaets why do i get fail in travis-ci test. I have only changed the docs.
filed test

**Comment by DanielRuf** [comment]
> @VladimirZaets why do i get fail in travis-ci test. I have only changed the docs.

Probably just a flaky test. Try to rebase to get the latest from 2.3-develop.

**Comment by DanielRuf** [comment]
Don't add another space.
Just do `git commit --allow-empty -m 'Trigger new build'`

**Comment by DanielRuf** [comment]
I have restarted the failing job.

**Comment by DanielRuf** [comment]
Please revert the last change.

**Comment by amritms** [comment]
@DanielRuf All checks have passed, could you merge this PR

**Review by DanielRuf — APPROVED** [review]

**Comment by DanielRuf** [comment]
Please wait until the maintainers merge it. I'm just one of many contributors.

**Review by VladimirZaets — APPROVED** [review]

**Comment by VladimirZaets** [comment]
Hi @amritms. Thanks for the collaboration. We already take your PR in progress.

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3905](https://jira.corp.magento.com/browse/ENGCOM-3905) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@amritms thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @amritms. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
