### PR TITLE
Resolve Incorrect Quantity Displayed In Admin Area when used 'Qty s Decimals' issue 23940

### LINKED ISSUE #23940: Incorrect Quantity Displayed In Admin Area when used 'Qty Uses Decimals'
###### Preconditions (*)

1. Magento 2.3-develop
###### Steps to reproduce (*)
1. Create a product with the following configurations
Minimum Qty Allowed in Shopping Cart = 2.14
Qty Uses Decimals = Yes
Qty Increments = 2.14
1. Navigate to Storefront and add created simple product to cart with qty = 2.14
1. Navigate to Checkout and verify, qty still = 2.14
1. Place order.
1. Navigate to admin area order page.
1. Verify 'Items Ordered' tab
1. Create Shipment
1. Open Order details page on the fronend.
1. Open "Order Shipments" tab
1. Check "Qty shipped" 

###### Expected result (*)

1. Column 'Qty' has 'Ordered 2.14' value
###### Actual result (*)

1. Column 'Qty Shipped' = 2

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#23940: Incorrect Quantity Displayed In Admin Area when used 'Qty s Decimals'

Solution: The qty should have the type 'Float' instead of 'Int' 

### Fixed Issues (if relevant)

1. magento/magento2#23940: Incorrect Quantity Displayed In Admin Area when used 'Qty s Decimals'
### Manual testing scenarios (*)

1. Create simple product with enabled 'Qty Uses Decimals' in Advanced Inventory Tab 
2. Navigate to Storefront and add created simple product to cart with qty = 1.5
3. Navigate to Checkout and verify, qty still  = 1.5
4. Place order.
5. Navigate to admin area order page.
6. Verify 'Items Ordered' tab
**=> Column 'Qty' has 'Ordered 1.5' value**

**Another steps to reproduce**
1. Create simple product with enabled 'Qty Uses Decimals' in Advanced Inventory Tab 
2. Start creating order from admin area
3. Try to add product with qty = 1.5
**=> After adding product to order qty in items grid should be 1.5**

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-5511](https://jira.corp.magento.com/browse/ENGCOM-5511) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by nmalevanec — APPROVED** [review]

**Comment by engcom-Delta** [comment]
Hi @edenduong I have tested PR changes and found that Quantity is incorrectly displayed also in Invoice, Credit Memo and order confirmation email( Quantity should be 2.5 )
**Invoice:**
#23943Invoice

**Credit Memo:**
#23943CreditMemo

**Email:**
#23943PrEmail

Could you take a look?

**Comment by edenduong** [comment]
Hi @engcom-Delta  : I have just changed the source code. (Invoice, Credit Memo and order confirmation email)
Hi @aleron75: you can review again.

Thanks.

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-5511](https://jira.corp.magento.com/browse/ENGCOM-5511) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by edenduong** [comment]
@magento-engcom-team, @aleron75: Could I receive “bugfix award” :) Thanks.

**Comment by edenduong** [comment]
@sivaschenko : Could I receive “bugfix award” :) Thanks.

**Comment by edenduong** [comment]
@sidolov , @VladimirZaets : Could you please add the "bugfix award" so I can receive points from that :) Thanks!

**Pull request merged**
