### PR TITLE
#26698 Fix Fatal error region getId() on NULL collection in Paypal Nvp API

### PR DESCRIPTION
**Pull request by jonatanrdsantos**
### Description (*)

To fix the problem `PHP Fatal error: Uncaught Error: Call to a member function getId()` I add a validation on region collection before using `$region->getId()` 

### Fixed Issues (if relevant)

1. magento/magento2#26698: Paypal issue with region on 2.3.4

### Manual testing scenarios (*)

1. Enable paypal w/o review (haven't tried with review)
2. Add product to cart as guest or logged in (doesn't matter)
3. Go to checkout
4. Enter your shipping address to be in UK for example and enter some state, I used Nottinghamshire
5. Place order, confirm from paypal side
6. You will get a success page 

### Questions or comments

N/A
### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by joridos** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @joridos. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @joridos, here is your [new Magento instance](https://pr-26744.instances.magento-community.engineering).
Admin access: [https://pr-26744.instances.magento-community.engineering/admin_cd85](https://pr-26744.instances.magento-community.engineering/admin_cd85)
Login: `0fa0000a` Password: `dd5d9ccc38a2`
Instance will be terminated in up to 3 hours.

**Comment by joridos** [comment]
Tested on vanilla magento instance from this PR:

**Comment by joridos** [comment]
Anyone can help me why the `Static Tests` is failing? I looked on the error but is on a method that I haven't changed.

**Comment by lenaorobei** [comment]
@joridos here are test results https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/26744/8a94bd64877a19a1f398312d3e4f3fcc/Statics/allure-report-b2b/index.html#suites/51d3ab4d5d77a0bc6a7ea344e9e7e6be/180b0c904c912a21/

```
PHPStan detected violation(s):
 ------ ---------------------------------------------------------------------- 
  Line   app/code/Magento/Paypal/Model/Api/Nvp.php                             
 ------ ---------------------------------------------------------------------- 
  1618   Method Magento\Paypal\Model\Api\Nvp::_filterPeriodUnit() should       
         return string but return statement is missing.                        
  1653   Method Magento\Paypal\Model\Api\Nvp::_filterBillingAgreementStatus()  
         should return string but return statement is missing.                 
  1672   Method                                                                
         Magento\Paypal\Model\Api\Nvp::_filterPaymentStatusFromNvpToInfo()     
         should return string|null but return statement is missing.            
  1712   Method Magento\Paypal\Model\Api\Nvp::_filterPaymentReviewAction()     
         should return string|null but return statement is missing.            
 ------ ---------------------------------------------------------------------- 

 [ERROR] Found 4 errors                                                         
```

**Comment by viktym** [comment]
Hi @joridos 
Please look at released patches for 2.3 https://github.com/magento/magento2/issues/26698#issuecomment-585669358
There you can find how to fix failed a static test and additional fix for region query using region collection (fixed filter by country)

**Comment by sidolov** [comment]
@joridos looks like the issue was fixed in commits:
 - [8a73e53ee369b24b95e3c94bc379ce48856ee8ca](https://github.com/magento/magento2/commit/8a73e53ee369b24b95e3c94bc379ce48856ee8ca)
 - [9948da7e013245ec3af6f6e7633ffa08a12b4ad9](https://github.com/magento/magento2/commit/9948da7e013245ec3af6f6e7633ffa08a12b4ad9)
I'm closing PR as not relevant, feel free to reopen it in case the issue will reproducing.

**Pull request closed without merging**
