### PR TITLE
\Magento\Framework\App\Helper\AbstractHelper leaking undeclared property

### PR DESCRIPTION
**Pull request by nevvermind**
/cc https://github.com/magento/magento2/issues/2103

### CODE REVIEW

**Comment by nevvermind** [comment]
Erm..

```
The command "sh -c "if [ '$TEST_SUITE' = 'integration_part_1' ] || [ '$TEST_SUITE' = 'integration_part_2' ]; then cd dev/tests/integration/; bash IntegationTestsForTravis.sh 2; fi"" exited with 0.

34.02s$ sh -c "if [ '$TEST_SUITE' = 'integration_part_1' ]; then cd dev/tests/integration/; ./../../../vendor/bin/phpunit -c phpunit.xml.travis1; fi"

PHP Parse error:  syntax error, unexpected '.', expecting ',' or ';' in /home/travis/build/magento/magento2/dev/tests/integration/testsuite/Magento/Framework/Search/Adapter/Mysql/AdapterTest.php on line 39

Parse error: syntax error, unexpected '.', expecting ',' or ';' in /home/travis/build/magento/magento2/dev/tests/integration/testsuite/Magento/Framework/Search/Adapter/Mysql/AdapterTest.php on line 39
```

How did that get in there?

**Comment by paliarush** [comment]
Internal ticket was created: MAGETWO-52561

**Comment by piotrekkaminski** [comment]
@paliarush can we merge now? Build is green.

**Pull request merged**
