### PR TITLE
#19575 magentoDataFixture should allow to use Module Prefix - Integrations Test 

### PR DESCRIPTION
**Pull request by larsroettig**
### Fixed Issues (if relevant)

1. magento/magento2#19575

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @larsroettig. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
Hi @larsroettig , thanks for your contribution. There is a static test fail. As this is an exceptional case and if there is no backward compatible way to retrive the required component registrar without static call, I think we should add a `@SuppressWarnings(PHPMD.StaticAccess)` annotation

**Comment by larsroettig** [comment]
@sivaschenko done 👍

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3657](https://jira.corp.magento.com/browse/ENGCOM-3657) has been created to process this Pull Request

**Pull request merged**
