### PR TITLE
MC-41887: Validation Messages - CustomerData messages not showing up

### PR DESCRIPTION
**Pull request by Den4ik**
Port  https://github.com/magento/magento2/commit/1827f09bbf2d34efd3fcb9ff5a155b0b777749f1 to 2.3.7

### Description (*)

This is a backport patch for "MC-41887: Validation Messages - CustomerData messages not showing up"

### Release Notes
Fixed issue with don't visible messages for sites hosted on subdirectories due to cookie restriction

### Categories
Bug Fix
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by Den4ik** [comment]
@magento run Functional Tests CE

**Comment by ihor-sviziev** [comment]
@Den4ik could you add Release Notes and Categories sections to the PR description, similar to https://github.com/magento/magento2/pull/34528?

**Comment by Den4ik** [comment]
> @Den4ik could you add Release Notes and Categories sections to the PR description, similar to #34528?

Done

**Review by ihor-sviziev — DISMISSED** [review]

**Review by ihor-sviziev — APPROVED** [review]

**Comment by m2-github-services** [comment]
@ihor-sviziev thank you for the review! We have changed pull request base branch in order to provide ability to merge current pull request and schedule quality patch delivery job.

**Comment by m2-github-services** [comment]
@ihor-sviziev quality patch delivery job is successfully scheduled! Link to the quality patch tool pull request will be provided as soon as it's created

**Comment by m2-github-services** [comment]
Pull request with quality patch was successfully created, available by the link: magento/quality-patches#64

**Comment by engcom-Lima** [comment]
Since this PR is already merged hence, moving this PR forward.

**Pull request merged**
