### PR TITLE
Fix issuse uncheck default value category rest api

### LINKED ISSUE #30047: Updating a category through the REST API  will uncheck "Use Default Value" on a bunch of attributes
### Preconditions (*)
- using Magento 2.4
- Mysql 8.0
- php-fpm 7.4
- nginx 1.18
- require 1 website with more than 1 store view
- Create some sub categories under default category at default store
- Using Admin token

### Steps to reproduce (*)
Call REST API with below script, replace the parameter for your own environment 

```
curl --location --request PUT 'https://{your domain}/rest/{your store code}/V1/categories/{your sub category id}' \
--header 'Authorization: Bearer {your admin token}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "category": {
        "name": "ENG NAME",
    }
}'

```
### Expected result (*)
When you access the category detail in admin and switch to related store view 

Expect only name field will uncheck "Use Default Value"

### Actual result (*)
Below fields will also uncheck "Use Default Value"
-  Enable Category
-  Include in Menu
-  URL Key

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

### PR DESCRIPTION
**Pull request by crabbynguyen**
### Description (*)
app/code/Magento/Catalog/Model/CategoryRepository.php: Use saveAttribute instead of save Category model entirely

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30047

### Manual testing scenarios (*)

Please execute the "Steps to reproduce" from the magento/magento2#30047

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by crabbynguyen** [comment]
@magento run Unit Tests

**Comment by crabbynguyen** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests.
This looks not really clear why we should use save attribute instead of saving through repository, I think it might cause not expected issues for instance when new product is added to category/removed from category, or product position changed. Let’s see for test results

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @crabbynguyen,
Could you review & fix failing tests?

**Comment by crabbynguyen** [comment]
@ihor-sviziev I am working on it

**Comment by crabbynguyen** [comment]
@magento run Static Tests

**Comment by crabbynguyen** [comment]
@magento run all tests

**Comment by crabbynguyen** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@crabbynguyen looks the issue was already fixed. Could you please confirm that?
Thank you.

**Comment by ihor-sviziev** [comment]
@crabbynguyen,
I see that issue was already fixed by internal team. More details https://github.com/magento/magento2/issues/30047#issuecomment-715498108.

I'm closing this PR as not relevant anymore.
In case if the issue still reproducing for you - please drop a comment here about that.

**Pull request closed without merging**
