### PR TITLE
MFTF: Deprecate ActionGroup that should no longer be used

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
This PR deprecated ActionGroup that should not be used (is not used in Magento itself), as it's duplicate for existing `AdminLoginActionGroup`, but not following Magento Best Practices.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run Database Compare

Normal issue when tests are running close to midnight :-(

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7633](https://jira.corp.magento.com/browse/ENGCOM-7633) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Pull request merged**
