### PR TITLE
Backend: Fixed checkbox alignment

### PR DESCRIPTION
**Pull request by suryakant-krish**
### Description (*)

Checkbox alignment issue backend. 
### Fixed Issues (if relevant)

1. magento/magento2#19630: Checkbox alignment issue backend. 

### Manual testing scenarios (*)

1. Login into admin panel > System > Export > checkbox alignment issue "Fields Enclosure".

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3642](https://jira.corp.magento.com/browse/ENGCOM-3642) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @suryakant-krish these changes were already contributed by you in https://github.com/magento/magento2/pull/19413 . Please ensure no additional changes needed and close this PR and corresponding issue as duplicates.

**Comment by suryakant-krish** [comment]
@sivaschenko,

Please review this PR.

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [new Magento instance](https://pr-19631.instances.magento-community.engineering).
Admin access: [https://pr-19631.instances.magento-community.engineering/admin](https://pr-19631.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sivaschenko** [comment]
Thanks @suryakant-krish , I can consider this pull request as a cleanup of original solution

**Pull request merged**
