### PR TITLE
Fixed customer back redirect navigate from edit product review

### LINKED ISSUE #29318: [Issue] Incorrect redirect navigate on the review edit page
This issue is automatically created based on existing pull request: magento/magento2#27983: Fixed customer back redirect navigate from edit product review

---------

### Preconditions: (*)

1. Have at least 1 product;
2. Create a new customer;

Fixed customer back redirect navigate from edit product review
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: N/A

### Steps to reproduce: (*)

1. Log in as Customer on Storefront;
2. Leave a review on the product;
1. Go to Admin -> Marketing -> All Reviews;
2. edit the created before review -> edit any customer;
3. click on the back button;

### Expected result (*)
:heavy_check_mark: should redirect to the edit review page

### Actual result (*)
:heavy_multiplication_x: Redirected to the customers grid page

Peek 2020-07-29 15-16

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

Fixed customer back redirect navigate from edit product review
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: N/A

### Manual testing scenarios (*)

1. Admin -> Marketing -> All Reviews
2. edit any review -> edit any customer
3. click on back redirect

### Expected result (*)
back redirect to edit review

### Actual result (*)
back redirect to  customer/index/index

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29318: Fixed customer back redirect navigate from edit product review

### CODE REVIEW

**Review by VladimirZaets — APPROVED** [review]

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @ravi-chandra3197. Thanks for collaboration. Can you please fix failed tests?

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7516](https://jira.corp.magento.com/browse/ENGCOM-7516) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Kilo** [comment]
Working on MFTF Test.

**Comment by engcom-Kilo** [comment]
Added MFTF test

**Comment by engcom-Kilo** [comment]
@magento run Functional Tests CE

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Kilo** [comment]
Hi @ravi-chandra3197, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
