### PR TITLE
#14367 Fix issue with export products

### PR DESCRIPTION
**Pull request by vdubyna**
https://github.com/magento/magento2/issues/14367

Fix the issue with export products per store views

### Description
Collection of products should be loaded by store but is not reset properly as a result verification (isLoaded) in abstract, prevents reload of the collection.

### Fixed Issues (if relevant)
1. magento/magento2#14367: Export products action does not see the store views differences.

### Manual testing scenarios
1. Set different product names per store view 
2. Export products
3. In the file we should see all names per store 

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14372) <br/>All committers have signed the CLA.

**Comment by orlangur** [comment]
@vdubyna `2.2-develop` should be used as a target branch and please sign CLA also.

**Comment by dmanners** [comment]
Hi @vdubyna Thank you for this pull requests. Once you have signed the CLA then we can progress this pull request.

**Comment by magento-engcom-team** [comment]
@vdubyna thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by sidolov** [comment]
Hi @vdubyna , looks like this issue was fixed in commit 12cb7fc32036641eba87e74479c41709879649e2
Please, merge latest changes from 2.2-develop to your branch

**Comment by vdubyna** [comment]
Correct, I see it is already fixed in develop
So, you can close my pull request and issue

Just wonder, why the fix was not included in 2.2.3 release.

I assume it will be added to 2.2.4 - correct?

-- 
Volodymyr Dubyna
Sent with Airmail

On March 29, 2018 at 18:17:11, Stanislav Idolov (notifications@github.com)
wrote:

Hi @vdubyna <https://github.com/vdubyna> , looks like this issue was fixed
in commit 12cb7fc
<https://github.com/magento/magento2/commit/12cb7fc32036641eba87e74479c41709879649e2>
Please, merge latest changes from 2.2-develop to your branch

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/magento/magento2/pull/14372#issuecomment-377269393>,
or mute
the thread

**Comment by dmanners** [comment]
Hi @vdubyna 

2.2.3 was a security release so the changes that made it in have been limited. These changes should be in 2.2.4 though.

I will close this pr now then. Thanks for your time.

**Pull request closed without merging**
