### PR TITLE
[2.2] return $this from setters in Analytics/ReportXml/DB/SelectBuilder.php

### PR DESCRIPTION
**Pull request by TBlindaruk**
### Description
When setters return `this` then we can call methods in the chain,

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=17945) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @TBlindaruk. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by mhauri — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @mhauri, thank you for the review.
[ENGCOM-2926](https://jira.corp.magento.com/browse/ENGCOM-2926) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@TBlindaruk thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @TBlindaruk. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
