### PR TITLE
Implement ActionInterface for /robots/index/index

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This is a part of the process of introducing implementations of `ActionInterface`.

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lbajsarowicz — APPROVED** [review]
Awesome! Thank you for your contribution.
You can also try to introduce `strict_types`

_(Failing tests not related to changes)_

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7178](https://jira.corp.magento.com/browse/ENGCOM-7178) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Kilo** [comment]
Failed functional tests not related to the changes in this PR

**Pull request merged**
