### PR TITLE
Page title not showing on product page.

### PR DESCRIPTION
**Pull request by chirag-wagento**
### Description
Solve Page title issue on product page

### Fixed Issues (if relevant)

1. magento/magento2#16249: https://github.com/magento/magento2/issues/16249

### Manual testing scenarios

1. You can check on product detail page between title tags.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @chirag-wagento. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on Pull Request changes
- `@magento-engcom-team give me new test instance` - deploy **NEW** test instance based on Pull Request changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy Vanilla Magento instance for Issue or Pull Request

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by ishakhsuvarov** [comment]
@chirag-wagento 
Thanks for updating

**Review by orlangur — CHANGES_REQUESTED** [review]
Implementation is not correct. You simply reverted what was done intentionally: https://github.com/magento/magento2/commit/60f2ea68cdf402fbd2425e1dc63623a7eaed6c03#diff-77708c79ee8f28599f00ad2b644b7c02 https://github.com/magento/magento2/commit/41838e02e33fad4496a5de05148ea1d3f5322e6a#diff-77708c79ee8f28599f00ad2b644b7c02

Please figure out the way is was supposed to work and fix it properly.

**Comment by chirag-wagento** [comment]
@orlangur  I have committed with new changes please check it.

Thanks

**Comment by orlangur** [comment]
@chirag-wagento breadcrumbs block initialization was intentionally removed in https://github.com/magento/magento2/commit/41838e02e33fad4496a5de05148ea1d3f5322e6a#diff-77708c79ee8f28599f00ad2b644b7c02, please do not re-introduce it.

**Comment by chirag-wagento** [comment]
@orlangur  Removed breadcrumbs block now can you please check.

Thanks

**Comment by orlangur** [comment]
@chirag-wagento could you please check that fix actually works?

**Comment by chirag-wagento** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @chirag-wagento. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @chirag-wagento, here is your [new Magento instance](https://pr-16263.engcom.dev.magento.com).
Admin access: [https://pr-16263.engcom.dev.magento.com/admin](https://pr-16263.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Please make sure you are PR **author** or **assignee** to access the instance.

**Comment by chirag-wagento** [comment]
@orlangur  I have checked It is working fine you can see attached screenshot.
page-title

Thanks

**Comment by orlangur** [comment]
@chirag-wagento it means that issue is irrelevant for `2.2-develop` already as your PR currently contains `Files changed 0`. Thanks for checking!

**Pull request closed without merging**
