### PR TITLE
Update Travis CI build status image in Readme

### PR DESCRIPTION
**Pull request by didactic-umbrella**
### Description
Current Travis CI build status image link leads to the obsolete `develop` branch. Updated to `2.3-develop`.

### Fixed Issues (if relevant)
1. None

### Manual testing scenarios
1. None

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=13912) <br/>All committers have signed the CLA.

**Review by okorshenko — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, thank you for the review.
[ENGCOM-656](https://jira.corp.magento.com/browse/ENGCOM-656) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@didactic-umbrella thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by okorshenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, thank you for the review.
[ENGCOM-656](https://jira.corp.magento.com/browse/ENGCOM-656) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@didactic-umbrella thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request merged**
