### PR TITLE
Unit Test for \Magento\Directory\Block\Adminhtml\Frontend\Currency\Base

### PR DESCRIPTION
**Pull request by karyna-t**
### Description (*)
Covers Magento\Directory\Block\Adminhtml\Frontend\Currency\Base wit a unit test.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by novikor — COMMENTED** [review]
Hi, @karyna-tsymbal-atwix! Thank you for your contribution.
Seems fine, - I'll put the PR on hold until the Functional tests build are green (there is a problem with 2.4-develop currently), and approve then.

**Review by novikor — APPROVED** [review]
The plans have changed)

**Comment by magento-engcom-team** [comment]
Hi @novikor, thank you for the review.
[ENGCOM-6868](https://jira.corp.magento.com/browse/ENGCOM-6868) has been created to process this Pull Request
:eight_spoked_asterisk: @novikor, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by karyna-tsymbal-atwix** [comment]
@novikor thank you!

**Pull request merged**
