### PR TITLE
Correct spelling

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

correct spelling
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3656](https://jira.corp.magento.com/browse/ENGCOM-3656) has been created to process this Pull Request

**Comment by orlangur** [comment]
@ravi-chandra3197 please do not produce useless merge commits.

**Comment by ravi-chandra3197** [comment]
Hello @orlangur 
Any suggestion for how to remove merge commits.

**Comment by orlangur** [comment]
@ravi-chandra3197 sure, here is simple way: https://coderwall.com/p/ysor6a/git-merge-squash-for-merging-without-commit-history

**Comment by ravi-chandra3197** [comment]
@orlangur Thanks for the response but my concern is how to remove commit from an existing branch or rewrite branch history.

**Comment by orlangur** [comment]
@ravi-chandra3197 simply squash all changes into single commit and force push as provided article shows.

**Comment by ravi-chandra3197** [comment]
Hello, @orlangur I have removed merge commits. can review it.

**Comment by orlangur** [comment]
@ravi-chandra3197 very nice, thank you! 👍

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
