### PR TITLE
[MFTF] Added AdminClickAddOptionForBundleItemsActionGroup

### LINKED ISSUE #30857: [Issue] [MFTF] Added AdminClickAddOptionForBundleItemsActionGroup
This issue is automatically created based on existing pull request: magento/magento2#30838: [MFTF] Added AdminClickAddOptionForBundleItemsActionGroup

---------
This PR provides new `AdminClickAddOptionForBundleItemsActionGroup`

### PR DESCRIPTION
**Pull request by Usik2203**
This PR provides new `AdminClickAddOptionForBundleItemsActionGroup`

### Resolved issues:
1. [x] resolves magento/magento2#30857: [MFTF] Added AdminClickAddOptionForBundleItemsActionGroup

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE ,Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Comment by Usik2203** [comment]
Hi @rogyar 
 Could I kindly ask you take a look on this one ?  ⬆️ 
Thank you.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8456](https://jira.corp.magento.com/browse/ENGCOM-8456) has been created to process this Pull Request
:eight_spoked_asterisk: @rogyar, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
Functional Tests B2B failure are different on last two run 
Run 1
image

Run 2
image

Hence moving to `Merge In Progress`

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
As the PR got moved to merge in progress a year ago, moving it to Extended Testing again.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by engcom-Charlie** [comment]
The functional CE failures are differnt in recent 2 runs with the same code. They seems to be flaky.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/30838/192f8262d61c937ab1001cad2b1ad01d/Functional/allure-report-ce/index.html#categories
image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/30838/778b967678ae4439f114884fe6083be9/Functional/allure-report-ce/index.html#categories
image

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by engcom-Charlie** [comment]
The Functional B2B failures are different in recent 2 runs with the same code. They seems to be flaky.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/30838/ebff09305a2070361790d2f8263fc4ef/Functional/allure-report-b2b/index.html#categories
image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/30838/9117cdbb99b93c41f198ed97fcd57e01/Functional/allure-report-b2b/index.html#categories
image

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
The web API failures are different in recent 2 runs with the same code. They seems to be flaky.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/30838/834cde2dce5cfb60106d5d4d9fae0b45/WebApi/console-error-logs.html
image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/30838/4ab650f2b5dae68f90cbb55a2ea7dd69/WebApi/console-error-logs.html
image

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
In recent 2 builds, the functional EE failure StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest is only constant rest seems to be flaky.

About StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest, there is a internal [JIRA](https://jira.corp.adobe.com/browse/ACQE-6331) present to fix the issue. The error is not coming because of this PR change hence moving it to Merge in Progress.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/30838/3bffc15c8f2981d446aa7203f1508597/Functional/allure-report-ee/index.html#categories
image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/30838/7967fb938e7082b60b4dd71c9136be67/Functional/allure-report-ee/index.html#categories
image

**Pull request merged**
