### PR TITLE
store_view_code-column-has-empty-values-in-csv-17784.

### PR DESCRIPTION
**Pull request by Valant13**
### Description (*)
Moved ->clear();

### Fixed Issues (if relevant)

1. magento/magento2#17784: store_view_code column has empty values in csv
2. magento/magento2#19786: Can only export default store view items when upgrade to 2.3.0

### Manual testing scenarios (*)

1. Go to Back Office
2. System > Data Transfer > Export
3. Choose:
3.1. Entity Type = Products
3.2. Export File Format = CSV
4. Press 'Continue" button at the botom of the page
5. store_view_code column should contain data from product chosen store.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19395) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @Valant13. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — APPROVED** [review]

**Comment by sivaschenko** [comment]
@Valant13 please sign the [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=19395) for us to be able to process this pull request further

**Comment by orlangur** [comment]
@sivaschenko no need to duplicate what the bot is saying ;)

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3993](https://jira.corp.magento.com/browse/ENGCOM-3993) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@Valant13 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request merged**
