### PR TITLE
Fixed issue 17764 - Edit order page has the same billing and shipping address even when original order has different addresses for Guest

### PR DESCRIPTION
**Pull request by Dharmeshvaja91**
### Description (*)
When you edit an order which has different shipping and billing address, new order contains only billing address and shipping address is set as same as billing address.

### Fixed Issues (if relevant)

1. magento/magento2#17764:Edit order page has the same billing and shipping address even when original order has different addresses for Guest

### Manual testing scenarios (*)
1. Create an order with different shipping and billing addresses for **Guest account**
2. Open that order in admin and click Edit to open edit order page
3. Order will have shipping and billing addresses same and Same As Billing Address checkbox is checked.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Dharmeshvaja91. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by swnsma** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @swnsma. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @swnsma, here is your [new Magento instance](https://pr-21377.instances.magento-community.engineering).
Admin access: [https://pr-21377.instances.magento-community.engineering/admin](https://pr-21377.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by swnsma — CHANGES_REQUESTED** [review]
Hi @Dharmeshvaja91,
I have tried to reproduce this issue on instance, based on your PR and, unfortunately, I am able to reproduce behavior, described in the issue.
Could you please re-check if your changes fix the issue?
The order:
selection_027
The order during order edit:
selection_026

**Review by swnsma — CHANGES_REQUESTED** [review]
Please check my previous review.

**Comment by sivaschenko** [comment]
Hi @Dharmeshvaja91 , do you have any updates on this pull request? Also, it would be good to squash 12 commits into a single one.

**Comment by Dharmeshvaja91** [comment]
> Hi @Dharmeshvaja91 , do you have any updates on this pull request? Also, it would be good to squash 12 commits into a single one.

okk i will ASAP

**Comment by sidolov** [comment]
@Dharmeshvaja91 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
