### PR TITLE
Issue Fixed: #8086: Multiline admin field is broken

### PR DESCRIPTION
**Pull request by vivekkumarcedcoss**
### Fixed Issues (if relevant)

1. magento/magento2#8086: Multiline admin field is broken
2. magento/magento2#18115

### Manual testing scenarios (*)

1. Add field type="multiline" in system config in admin.
2. Save values in multiple fields

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @vivekkumarcedcoss. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by aleron75 — APPROVED** [review]

**Comment by aleron75** [comment]
Hello @vivekkumarcedcoss thanks for your contribution.

Once merged, don't forget you can easily port this PR (if needed) to other branches with the Porting Tool, [read more here](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#porting-tool).

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-3924](https://jira.corp.magento.com/browse/ENGCOM-3924) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@vivekkumarcedcoss thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request merged**
