### PR TITLE
[Backport] Fixed magento text swatch switches product image even if attribute feature is disabled

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Original Pull Request 
https://github.com/magento/magento2/pull/19184

### Description (*)

Fixed magento text swatch switches product image even if attribute feature is disabled #16446
### Fixed Issues (if relevant)

1. magento/magento2#16446: Fixed magento text swatch switches product image even if attribute feature is disabled 

### Manual testing scenarios (*)

N/A
### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @ravi-chandra3197, thanks for collaboration. Why the code in your PR is different from origin PR?

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5301](https://jira.corp.magento.com/browse/ENGCOM-5301) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @ravi-chandra3197.

 I've checked PR changes and I'm not sure about the correct behavior of the magento after fix

**Manual testing scenario:**

1. Create Text Swatch attribute "**test**" with "**Update Product Preview Image**" set to **NO**;
2. Create configurable product with some variations for "**test**";
3. Add image to configurable product;
4. Add image to associated simple products;
5. Go to category with this product on Storefront;

**Actual result:**  :heavy_check_mark: product preview image does not change
screen1

6. Go to product page:

**Actual result:** :heavy_multiplication_x: Images for child products are not displayed

screen2

@ravi-chandra3197 Is it the correct behavior?

Thanks!

**Comment by ravi-chandra3197** [comment]
> Hi @ravi-chandra3197.
> 
> I've checked PR changes and I'm not sure about the correct behavior of the magento after fix
> 
> **Manual testing scenario:**
> 
> 1. Create Text Swatch attribute "**test**" with "**Update Product Preview Image**" set to **NO**;
> 2. Create configurable product with some variations for "**test**";
> 3. Add image to configurable product;
> 4. Add image to associated simple products;
> 5. Go to category with this product on Storefront;
> 
> **Actual result:**   product preview image does not change
> screen1
> 
> 1. Go to product page:
> 
> **Actual result:**  Images for child products are not displayed
> 
> screen2
> 
> @ravi-chandra3197 Is it the correct behavior?
> 
> Thanks!

Hello @engcom-Alfa 
can you check this https://github.com/magento/magento2/pull/19184#issuecomment-486707622

**Comment by engcom-Alfa** [comment]
Hi @piotrekkaminski!

During testing, we faced an issue. We're not sure about the correct behavior of the magento after fix.

_Problem_:  There are no child images on the **product page** when "Update Product Preview Image" option is set to NO

**Manual testing scenario:**

1. Create Text Swatch attribute "test" with "Update Product Preview Image" set to NO;
2. Create configurable product with some variations for "test";
3. Add image to configurable product;
4. Add image to associated virtual products;
5. Go to category with this product on Storefront;

**Actual Result:**

:heavy_check_mark: On catalog page child images are not displayed

screen1

6. Go to product page;

**Actual Result:**

:heavy_multiplication_x:  On product page child images are not displayed too

screen2

**Note:** According to the comment to the attribute "Update Product Preview Image" it only applies to **catalog page**
screen

**What is the correct behavior?**

**Thanks!**

**Comment by VladimirZaets** [comment]
@ravi-chandra3197, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Comment by sivaschenko** [comment]
@ravi-chandra3197, to be honest, I think we should update the comment as this setting meant to work for all Magento pages, in my opinion. But I would like to confirm with @piotrekkaminski to be sure

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-5427](https://jira.corp.magento.com/browse/ENGCOM-5427) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
@engcom-Alfa the behaviour described in https://github.com/magento/magento2/pull/22510#issuecomment-505828743 is ok in my opinion

**Pull request merged**
