### PR TITLE
Fixed issue - Generate coupon code with code lth

### LINKED ISSUE #23414: Generate coupon code with code length
### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Create new Cart Price Rule
image
image
2. Click on Save and Continue Edit button
3. Open Manage Coupon Codes tab
4. Choose Generate coupon code with **Coupon Qty=99**, **Code Length=2**, **Code format=Numeric**
5. Run `cron:run` twice
6. Reload page

### Expected result (*)

1. Result is 99 coupon codes with series from 00 (or 01) to 99 with code length is 2: 01, 02, 03, .., 99

### Actual result (*)

1. Result is 99 random coupon codes with 3 character not 2: 500, 700, 232, 432, ....
image

**Note:** **Coupon Qty=9**, **Code Length=2**, **Code format=Numeric**.
:heavy_check_mark: It works. Result is 9 random coupon code with 2 character.
image

### PR DESCRIPTION
**Pull request by parasl0**
### Description (*)

Generate coupon code with code length
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/23414 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23475) <br/>All committers have signed the CLA.

**Comment by sivaschenko** [comment]
@tkacheva can you please take a look at the issue and the solution provided in the pull request. 
Are there any requirements for the max probability of guessing and max generate attempts for the coupon codes generation.

**Comment by tkacheva** [comment]
@parasl0 Thanks for your contribution! Could you confirm the actual behavior after your fix? Does the system generates the codes by adding +1 to the number now (not random as it was before)?

**Comment by sivaschenko** [comment]
@tkacheva the generation algorithm was not changed

**Comment by sidolov** [comment]
@sivaschenko what is the progress on this? Can we proceed with changes since the algorithm didn't change?

**Comment by sivaschenko** [comment]
@tkacheva are you ok with accepting these changes?

**Comment by ihor-sviziev** [comment]
@sivaschenko is there any updates?

**Comment by VladimirZaets** [comment]
@magento run all tests

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @parasl0 , please, sign CLA, otherwise, we can't process your pull request

**Comment by engcom-Echo** [comment]
Hi @parasl0 , I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
