### PR TITLE
Popout `count` function from `for` loop

### PR DESCRIPTION
**Pull request by yogeshsuhagiya**
Count the size of array outside for loop and passed the result to for loop.

### Fixed Issues (if relevant)
N/A
### Manual testing scenarios
N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by miguelbalparda** [comment]
Hi @Yogeshks! I checked the code and it seems to be a minor fix to improve readability. Is this correct or I'm missing something else?

**Comment by orlangur** [comment]
Hi @Yogeshks, according to https://stackoverflow.com/questions/4566314/php-what-is-the-complexity-i-e-o1-on-of-the-function-count such optimization seems to be irrelevant in PHP world.

**Comment by yogeshsuhagiya** [comment]
Hi @miguelbalparda,
You're right, it just a minor fix.

**Comment by yogeshsuhagiya** [comment]
Hi @orlangur

I've reviewed your referral link and I agree with you but isn't it best practice to use function outside loops?

**Comment by orlangur** [comment]
@Yogeshks,

>  isn't it best practice to use function outside loops?

No, it is only relevant in case we have some heavy operation, like `O(N)` counting of array elements, some invariant `strpos` etc.

Thanks for quick response and collaboration!

**Pull request closed without merging**
