### PR TITLE
[2.3] Alternative fix for Multi Store Emails issue, Fix Async Emails issues, Fix Multiple Email issues

### PR DESCRIPTION
**Pull request by gwharton**
### Description
This PR removes the previously introduced transportBuilderByStore class that was introduced in 2.2.4 to fix issue #11740 as this implementation caused unwanted regression/bug when sending multiple emails/async emails.

### Fixed Issues (if relevant)
1. magento/magento2#11740:Sending emails from Admin in Multi-Store Environment defaults to Primary Store
2. magento/magento2#14952:Confirmation emails have no FROM or FROM email address 2.2.4
3. magento/magento2#14945:Store Email Addresses are not used anymore
4. magento/magento2#16355:Magento 2.2.4 not sending from sales sender
5. magento/magento2#18470:Store emails have correct from address but do not have a from name

### Manual testing scenarios
Scenareo 1
- Single store
- Setup store email addresses
- Complete checkout
- Verify from address in confirmation email

Scenareo 2
- Multiple store
- Setup store email addresses for Store 1
- Setup store email addresses for Store 2
- Complete checkout on Store 1- Verify from address in confirmation email
- Complete checkout on Store 2- Verify from address in confirmation email

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by gwharton** [comment]
ok, someone else will have to pick this one up.

**Comment by sreichel** [comment]
Can you please reopen?

**Comment by gwharton** [comment]
sreichel. Magento made it clear in the 2.2 version of this pr that this fix isnt a goer im afraid. The way they want it done is way too complicated for me to implement.

**Comment by gwharton** [comment]
Note, in testing 2.3-develop, emails will not have a from name set. This is due to bug #18470.

**Comment by ihor-sviziev** [comment]
Hi @gwharton,
Let me know once you'll add all needed changes. I'll review them all together

**Comment by gwharton** [comment]
Just waiting on travis to pass and I should be done. I know there are lots of usages of the now deprecated function within the magento codebase, but I'm not proposing to update any of them in these PRs. Seems a little beyond scope and also a testing nightmare to change all in one go. I can audit the codebase and compile a list of areas that could do with looking at in the future if that would help.

**Comment by ihor-sviziev** [comment]
Hi @gwharton,

Unfortunately this change will not be included in 2.3.0, so as part of 2.3.x release line - it's not backward change. Could you do the same changes as I requested for 2.2.x release line?

Sorry for confusing you.

Thank you

**Comment by gwharton** [comment]
@ihor-sviziev All done.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-3225](https://jira.corp.magento.com/browse/ENGCOM-3225) has been created to process this Pull Request

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-3225](https://jira.corp.magento.com/browse/ENGCOM-3225) has been created to process this Pull Request

**Comment by gwharton** [comment]
Thanks @ihor-sviziev 

Its a shame this can't be fast tracked to 2.3.0 as without it 2.3.0 will be launched without store email from addresses.

**Comment by gwharton** [comment]
@ihor-sviziev Is it too late to make a change to this PR.

In 2.3-develop, the call to set the from name is broken. I was going to do a separate PR for the from name, but it makes sense to do both together. This would fix #18470 which is present in 2.3 only.

**Comment by MoT3rror** [comment]
Didn't want to hijack the pull request but added the fix for the from name in this pull request to get this overall fix sooner.

**Comment by gwharton** [comment]
@MoT3rror Thanks for the commit, however I've already tried that resolution elsewhere and it was rejected. The problem is that 2.3.0 has already been baselined, therefore any changes in this PR will be due in 2.3.1 The change you suggested is not backwards compatible as it will break installations that have overridden the setFrom function.

I know its a pain, and I believe that the solution you have proposed is the correct one, however it has to be implemented by introducing a new function and deprecating the old one.

I'll revert your change and push my changes that I had waiting that will fix the issue in a way that will be acceptable to Magento.

Sorry to waste your time :(

**Comment by gwharton** [comment]
@ihor-sviziev Apologies as this PR had already been approved and is in testing, but additional changes have been pushed which fix issue #18470 in addition to the others. It is right that these changes are all processed together as otherwise 2.3 will have broken email problems until 2.3.2+

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-3225](https://jira.corp.magento.com/browse/ENGCOM-3225) has been created to process this Pull Request

**Comment by iget-esoares** [comment]
More then 2 months since this PR was openend and 1 month from last commit, and it was not merged yet? :disappointed:

**Comment by hazzan3li** [comment]
Hi 
how to edit composer json file to fit for patching problem 18471
 "extra": {
    "composer-exit-on-patch-failure": true,
    "patches": {
        "?????": {
            "??????????????????": "patches/composer/18471.diff"
        }
    }
}

**Comment by PathToLife** [comment]
```
"patches": {
        "magento/module-sales": {
            "PR-18472: Alternative fix for Multi Store Emails issue, Fix Async Emails issues, Fix Multiple Email issues": "PR-18472-Sales.diff"
        },
        "magento/framework": {
            "PR-18472: Alternative fix for Multi Store Emails issue, Fix Async Emails issues, Fix Multiple Email issues": "PR-18472-Framework.diff"
        }
```
 Hurry up and merge already. People are using composer to get the patches themselves. On holiday are we? 😅😅
https://github.com/magento/magento2/issues/14952#issuecomment-449823307

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Comment by JoostWan** [comment]
You can use [cweagans/composer-patches](https://github.com/cweagans/composer-patches/) and below patches for Magento 2.3.0

```
"patches": {
            "magento/module-sales": {
                "PR-18471: Alternative fix for Multi Store Emails issue, Fix Async Emails issues, Fix Multiple Email issues": "patches/composer/PR-18471-Sales.diff"
            },
            "magento/framework": {
                "PR-18471: Alternative fix for Multi Store Emails issue, Fix Async Emails issues, Fix Multiple Email issues": "patches/composer/PR-18471-Framework.diff"
            }
        }

```
[patches.zip](https://github.com/magento/magento2/files/2772092/patches.zip)

**Comment by rishabhchd19** [comment]
> You can use [cweagans/composer-patches](https://github.com/cweagans/composer-patches/) and below patches for Magento 2.3.0
> 
> ```
> "patches": {
>             "magento/module-sales": {
>                 "PR-18471: Alternative fix for Multi Store Emails issue, Fix Async Emails issues, Fix Multiple Email issues": "patches/composer/PR-18471-Sales.diff"
>             },
>             "magento/framework": {
>                 "PR-18471: Alternative fix for Multi Store Emails issue, Fix Async Emails issues, Fix Multiple Email issues": "patches/composer/PR-18471-Framework.diff"
>             }
>         }
> ```
> [patches.zip](https://github.com/magento/magento2/files/2772092/patches.zip)

This isn't working to my system as no file is being updated when I put the zip files in folder patches/composer/ . I ran setup:di:compile & setup:static-content:deploy -f after setup:upgrade but neither it is patching up files with http://mydomain.com/patches/composer/PR-18471-Sales.diff  nor with the path patches/composer/PR-18471-Sales.diff. Problem with both the patches.

**Comment by hostep** [comment]
@rishabhchd19 : you need to put the `patches` & `composer-exit-on-patch-failure` sections in your `extra` section in your `composer.json` file, make sure you read [the documentation](https://github.com/cweagans/composer-patches/#usage) very carefully :)

After that, you can run `composer install` which should apply the patches. After they are applied, you need to put them in your `composer.lock` file as well, which you can automatically update using `composer update --lock`

There's also some information over [here](https://support.magento.com/hc/en-us/articles/360005484154-Create-a-patch-for-a-Magento-2-Composer-installation-from-a-GitHub-commit) ("Apply a patch" section) which more or less tells you the same.

**Comment by rishabhchd19** [comment]
yeah...silly mistake. Got your point. Thanks @hostep

**Comment by ladle3000** [comment]
I apply this patch to 2.3 and then mageplaza smtp gives this error on test send

Zend\Mail\Transport\Smtp transport expects either a Sender or at least one From address in the Message; none provided

**Comment by ihor-sviziev** [comment]
Hi @snoroozi,
I don't think it's caused by these changes, or you applied patch incorrectly somehow.
You can create an issue for https://github.com/mageplaza/magento-2-smtp

**Comment by Lukas-G21** [comment]
Does this patch work for 2.3? Because on my 2.3 version I applied these patches correctly. On composer -v install it changed the code with diff. Ran setup:upgrade, cache:clean, setup:di:compile, setup:static:content:deploy. Still emails sender is www-data. I checked Magento 2.3-develop brach and code is different than on patch. It uses setFromByScope https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Sales/Model/Order/Email/SenderBuilder.php Does anyone have working patch for 2.3?

**Comment by gwharton** [comment]
The change to setfrombyscope was just a wording change.

Are you using any third party email modules that could be overriding core functions?

**Comment by Lukas-G21** [comment]
None of 3rd party modules override these core functions. Also cleared these : rm -rf var/cache/* var/page_cache/* var/di/* var/generation/* var/view_preprocessed/* pub/static/* generated/code/*
and redid whole process. Still same sender www-data. I used PR-18471.zip

**Comment by gwharton** [comment]
I don't know what else to suggest.

I've just redeployed 2.3-develop and tested sending newsletter emails, sending sales email in synchronous mode, and sending sales emails in asynchronous mode. All set the correct sender details.

Either the patches aren't applied correctly, or something is overriding core where you arent expecting it.

try as a double check.

`grep -r 'Sales\\Model\\Order\\Email\\SenderBuilder\|Framework\\Mail\\Message\|Framework\\Mail\\Template\\TransportBuilder' * | grep di.xml`

Are you able to reproduce in a dev environment. Can you debug using xdebug? How about disabling all modules and see if issue is still there. If not reintroduce modules a few at a time. All ways in which I've tracked down unexpected behaviour in the past.

**Comment by Lukas-G21** [comment]
Heres how I applied patch:

in project directory **patches/composer/** added:
**PR-18471-Framework.diff
PR-18471-Sales.diff**
then **composer require cweagans/composer-patches** and in composer.json in "extra" added:
`"composer-exit-on-patch-failure": true,
    "patches": {
      "magento/module-sales": {
        "PR-18471: Alternative fix for Multi Store Emails issue, Fix Async Emails issues, Fix Multiple Email issues": "patches/composer/PR-18471-Sales.diff"
      },
      "magento/framework": {
        "PR-18471: Alternative fix for Multi Store Emails issue, Fix Async Emails issues, Fix Multiple Email issues": "patches/composer/PR-18471-Framework.diff"
      }
    }`

Then ran composer -v install and composer update --lock.  Then 
`rm -rf var/cache/* var/page_cache/* var/di/* var/generation/* var/view_preprocessed/* pub/static/* generated/code/*
` and cli commands for cache clean, setup upgrade, di:compile and static content compilation.

Also none of the 3rd party modules extend patch function and 
`grep -r 'Sales\\Model\\Order\\Email\\SenderBuilder\|Framework\\Mail\\Message\|Framework\\Mail\\Template\\TransportBuilder' * | grep di.xml`
 returns 
`vendor/magento/module-email/etc/di.xml:    <preference for="Magento\Framework\Mail\MessageInterface" type="Magento\Framework\Mail\Message" />
vendor/dotmailer/dotmailer-magento2-extension/etc/di.xml:    <type name="Magento\Framework\Mail\Template\TransportBuilder">
vendor/dotmailer/dotmailer-magento2-extension/etc/di.xml:    <type name="Magento\Framework\Mail\MessageInterface">
`
 this module is turned off though.
Patch does not work locally nor on staging server on 2.3

UPDATE: 
When debugging **/vendor/zendframework/zend-mail/src/Transport/Sendmail::mailHandler()** $result headers has correct parameters, but when email arrives it is www-data

**Comment by ladle3000** [comment]
@trenox2121 I never got this patch to work either and also correctly applied.  Would love to see someone package it up more simply

**Comment by Lukas-G21** [comment]
@snoroozi, @gwharton  after debugging I didn't find any problems in code. Then reconfigured sendmail locally, email headers are correct now. So this patch does work.

**Comment by lgrassini** [comment]
Magento 2.3.1 still implementing setFromByScope instead of setFromByStore in Framework/Mail/Template/TransportBuilder.php causing some other emails, like Recover Password email, not being sent.

```    
   public function setFrom($from)
    {
        return $this->setFromByScope($from, null);
    }
```

See: https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Mail/Template/TransportBuilder.php

@gwharton Any idea why the Magento team didn't fully implemented the proposed PR ?

**Comment by gwharton** [comment]
SetFrom and setFrombyStore are deprecated and call the framework function setFrombyScope. Anything that used setFrom or setfrombystore should still work. New code shoukd use setfrombyscope.

The initial fix of setfrombystore was renamed to setfrombyscope as framework functions should not be store aware. (Renamed via deprecation)

**Comment by gwharton** [comment]
Oh hang on. I see. The deprecated function setfrombystore has been removed. Yes i imagine this would break things!!!

**Comment by sreichel** [comment]
... on the other hand rejection non-B/C breaking changes ... muppets :)

**Comment by helefa** [comment]
is there a way to backport this to 2.2.4?

**Comment by ihor-sviziev** [comment]
> is there a way to backport this to 2.2.4?

You can look at https://github.com/magento/magento2/pull/18472

**Comment by LiamKarlMitchell** [comment]
Will this fix Magento 2.3.0 seemingly just exiting the script when trying to notify Invoice & Shipping emails?

**Pull request merged**
