### PR TITLE
Fixed Dependency on Backup Settings Configuration

### PR DESCRIPTION
**Pull request by keyurk-emipro**
### Description (*)

Fixed Dependency on Backup Settings Configuration
### Fixed Issues (if relevant)

1. magento/magento2#22474: Incomplete Dependency on Backup Settings Configuration
2. ...

### Manual testing scenarios (*)

1. Go to Store > Configuration > System > Advanced > Backup Settings
2. Enable Backup => Yes
3. Enable Scheduled Backup => Yes
4. Enable Backup => No
5. Now all fields are hidden with proper dependencies.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by keyurk-emipro** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @keyuremipro. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @keyuremipro, here is your [new Magento instance](https://pr-22475.instances.magento-community.engineering).
Admin access: [https://pr-22475.instances.magento-community.engineering/admin](https://pr-22475.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4815](https://jira.corp.magento.com/browse/ENGCOM-4815) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
