### PR TITLE
It is not possible to choose only width or height within the image property in the view.xml

### LINKED ISSUE #31747: It is not possible to choose only width or height within the image property in the view.xml
### Preconditions (*)

1. Magento version 2.3.6
2. Only add width or height in the image property of the view.xml file, not both

### Steps to reproduce (*)

1. Create a view.xml and add an image tag with id **product_base_image** and type **image** . within this image tag, add a width tag but **not** a height tag
2. Go to the frontend of the Magento shop and go to a PDP

### Expected result (*)

1. Webpage should load in and should show the product images

### Actual result (*)

1. Fatal error: Uncaught TypeError: Argument 2 passed to Magento\Catalog\Block\Product\ImageFactory::getRatio() must be of the type int, null given

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Alainvdz99**
### Description (*)

If you now choose only one of width or height in the image property in the view.xml, you will get a type error that the width or height cant be null. This fix will make sure you will also be able to only choose one of width or height. 
### Fixed Issues (if relevant)

1. Fixes magento/magento2#31747.

### Manual testing scenarios (*)

1. Create a view.xml and add an image tag with id product_base_image and type image . within this image tag, add a width tag but not a height tag
2. Go to the frontend of the Magento shop and go to a PDP

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Alainvdz99** [comment]
@magento give me test instance

**Comment by Alainvdz99** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @Alainvdz99,
Could you cover your changes with an automated test?

**Comment by engcom-Alfa** [comment]
Hi @Alainvdz99 @ihor-sviziev 
Unfortunately, we are not able to reproduce the issue on fresh 2.4-develop. Everything works as expected.
 Looks like the problem has already been fixed by commit 806b4f9dfa63b5319fa3891c9bab911516b21747.
https://github.com/magento/magento2/issues/26973
So, we have to close it.
Thanks!

**Pull request closed without merging**
