### PR TITLE
issue with store name into graph ql has been resolved

### PR DESCRIPTION
**Pull request by yogeshkarodiya**
This pull request is for solve issue number 27952

Description (*)
Magento 2.3 into GraphQl query store_name is coming null even if store name given under store configuration setting into Store Information 

Fixed Issues (if relevant)
#27952 : Missing store_name in GraphQl Resolver

### Manual testing scenarios (*)
Please follow steps for manual testing
1. Enter Store Name under configuration setting 
Genernal > Store Information > Store Name

2. Run graph ql with below query
{
  storeConfig {
    id
    code
    website_id
    locale
    base_currency_code
    default_display_currency_code
    timezone
    weight_unit
    base_url
    base_link_url
    base_static_url
    base_media_url
    secure_base_url
    secure_base_link_url
    secure_base_static_url
    store_name
    secure_base_media_url
  }
}
3> Now store name will not null
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by yogeshkarodiya — COMMENTED** [review]
changed app/code/Magento/StoreGraphQl/etc/graphql/di.xml

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @yogeshkarodiya. Thanks for collaboration. Can you please look and fix failed tests?

**Comment by yogeshkarodiya** [comment]
> Hi @yogeshkarodiya. Thanks for collaboration. Can you please look and fix failed tests?

Hello I have checked but these test case is not related to my change could you please help me for this.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
Hi @yogeshkarodiya, this issue has been fixed on this PR https://github.com/magento/magento2/pull/28855

I will be closing this PR, but please, feel free to reopen it if necessary.

**Pull request closed without merging**
