### PR TITLE
11615: Fix UrlRewriteGenerator for anchor categories

### PR DESCRIPTION
**Pull request by obuchowski**
A commit itself is pretty straightforward. Need to pass storeId param to category repository so resulted category has a correct url path.

### Description (*)
For not default stores adding a category for a product may result in wrong url rewrite for a product in category's anchor parent .
result
### Fixed Issues (if relevant)

1.  [#11615](https://github.com/magento/magento2/issues/11615)

### Manual testing scenarios (*)
1. Enable this 
config
2. Change url key of some anchor category in a specific (NOT DEFAULT) store 
key
3. add a product to a child category from a product form
product
Note that there is a correct result if a product is added from a category form.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20826) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @obuchowski. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by hostep** [comment]
Let's also link to the corresponding PR for 2.2-develop: https://github.com/magento/magento2/pull/14344

**Comment by obuchowski** [comment]
Thank you @hostep 
Sorry, I found a related issue and existing pull request right before I finished a creation of this one.
Anyway, I find it ridiculous that this issue is living for 15 months and a solution was provided almost a year ago.
 The business logic as well as fix itself are very clear.
code

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4076](https://jira.corp.magento.com/browse/ENGCOM-4076) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@obuchowski thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by obuchowski** [comment]
@VladimirZaets  thank you guys. Pull requests accepting process has significantly accelerated compared with previous years. Great work.

**Comment by VasylShvorak** [comment]
✔️ QA passed

**Comment by sidolov** [comment]
Hi @obuchowski , we found huge performance degradation on the scenario:: `Get category via API` with provided changes, can you take a look? 
Thank you!

**Comment by hostep** [comment]
@sidolov: how can this change have influence on getting category data? Are url rewrites being generated while just getting category data? That wouldn't make any sense?

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-4076](https://jira.corp.magento.com/browse/ENGCOM-4076) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Comment by hostep** [comment]
Folks, what's the deal with this PR? This is taking way too long without any explanation. Why is it currently on hold again?

I've been waiting on a fix like this since I first attempted to fix it [back in 2016](https://github.com/magento/magento2/pull/7667)...

**Comment by ihor-sviziev** [comment]
Hey @sidolov @sivaschenko @engcom-Foxtrot,
Could you add some info why this PR wasn't merged yet? Is there any issues?

**Comment by sivaschenko** [comment]
@igor-sviziev @hostep this pull request causes performance tests failure. We are working to find the solution to keep the performance on the same level or approve the PAT fail

**Comment by hostep** [comment]
Thanks for the update @sivaschenko.
I think it is expected to see a small decrease in performance since it needs to load category data per store view, whereas before it only loaded it for the current storeview (I think) which means less queries to the db.
I'm more in favor of accepting a bug fix for a very annoying problem, over a small performance decrease and fix the performance problem later on. Unless someone can quickly find a decent solution for the performance problems?

**Comment by ihor-sviziev** [comment]
PR https://github.com/magento/magento2/pull/14344 with the same changes to 2.2-develop was finally merged 2 days ago! 🎉
I think this one will be merged soon too

**Comment by ihor-sviziev** [comment]
Hi @sivaschenko @sidolov,
Could you add some info why this PR still wasn't merged?

Thx

**Comment by hostep** [comment]
Hi @VladimirZaets, @sivaschenko, @sidolov: can you give us an update on the status here?

Thanks!

**Comment by sidolov** [comment]
Hi @hostep , @ihor-sviziev we found performance degradation with the provided solution and trying to figure out how to fix it or at least approve degradation with our performance team

**Comment by ihor-sviziev** [comment]
Hi @sidolov,
Could you add more info in which case we got performance degradation?

What if we'll load only needed data from CategoryCollection, outside of the loop (and cache these categories in private variable it if needed)?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @obuchowski,
In order to improve performance of this part - could you do following changes?
1. In one loop iterate `$productCategories->getList()` and collect all anchorCategoryIds for all categories
2. Using category collection (collections usually doing much less work, for instance they're not loading extension attributes, that we don't really use there) find all neede categories for needed store view
3. In 2nd loop iterate $productCategories->getList()` again and get categories from already loaded from category collection.

Doing it in this way should improve performance of this solution and I think it could be accepted.

**Comment by VladimirZaets** [comment]
@obuchowski, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Comment by hostep** [comment]
Closing this is ridiculous, I'm reopening.

**Comment by sivaschenko** [comment]
@obuchowski please sign the Adobe CLA so that we can further process this PR

**Comment by ihor-sviziev** [comment]
Hi @obuchowski,
Will you be able to sign Adobe CLA?

**Comment by lenaorobei** [comment]
@obuchowski unfortunately, we will not be able to process this PR without signed CLA.

**Comment by lenaorobei** [comment]
I run performance tests on this branch, everything is ✅
The only thing is missing - CLA.

**Comment by hostep** [comment]
@lenaorobei: so why has this ticket taken sooo long to get processed, first Magento staff is complaining that it causes performance issues and refuses to merge it, and now all of the sudden there's no problem anymore?
The CLA [was already signed before](https://github.com/magento/magento2/pull/20826#issuecomment-459116283), it's just the new CLA which was introduced some months ago which isn't signed yet.

If that's the only thing blocking this PR from merging, I'll create a new one in a couple of days.

**Comment by lenaorobei** [comment]
@hostep it's not an excuse, but the reason is a huge amount of open PRs. CLA is the only thing. Sorry about that and I hope for your understanding.

**Comment by hostep** [comment]
Added a new PR: https://github.com/magento/magento2/pull/26784

Unless @obuchowski starts responding again, we can probably close this one?

**Comment by ihor-sviziev** [comment]
Hi @obuchowski,
I’m closing this PR due to inactivity and now we have another PR #26784  that doing the same without this issue.
Thank you for contribution!

**Pull request closed without merging**
