### PR TITLE
[2.1-backport] Fix Login Popup broken on iPad portrait

### PR DESCRIPTION
**Pull request by ihor-sviziev**
My [pull request](https://github.com/magento/magento2/pull/6452) was already merged to develop branch.

This pull request fixes issue https://github.com/magento/magento2/issues/6451 for Magento 2.1.x

### CODE REVIEW

**Comment by magento-team** [comment]
@ihor-sviziev thank you for your contribution. Your Pull Request has been successfully merged

**Comment by maksek** [comment]
Hi @ihor-sviziev, can you provide me your email, so I can contact you regarding your PR.

**Comment by ihor-sviziev** [comment]
You can ask there if you have any questions

**Comment by maksek** [comment]
@ihor-sviziev, want to ask your shipment address, to send you some swag as a reward for the PR in 2.1.8 release.

**Comment by ihor-sviziev** [comment]
@maksek svizev.igor@gmail.com

**Pull request merged**
