### PR TITLE
[MFTF] use actionGroup click next button on checkout

### PR DESCRIPTION
**Pull request by Usik2203**
This PR use `StorefrontCheckoutClickNextOnShippingStepActionGroup` for click Next button on checkout

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests EE , Functional Tests B2B

**Comment by eduard13** [comment]
@magento run all tests

**Review by eduard13 — APPROVED** [review]
Thank you for your contribution 👍

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-7872](https://jira.corp.magento.com/browse/ENGCOM-7872) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Pull request merged**
