### PR TITLE
Infinite redirects in Magento admin #21454

### PR DESCRIPTION
**Pull request by Jitheesh**
### Description (*)

Magento admin 404 urls are ends on redirect loop if we try to access non existing Magento admin path without security keys.
### Fixed Issues (if relevant)

1. magento/magento2#21454: Infinite redirects in Magento admin

### Manual testing scenarios (*)

1.  Navigate to Stores > Configuration > Advanced > Admin > Security. > Add Secret Key to URLs > Yes
2.   Login to Magento Admin panel
2.1  After login admin user will redirected to start-up page. ex: http://shop.dev.magento.com/admin/admin/dashboard/index/key/0edc1d2ff54b4e7e3f7f71e880cee6543870c355f876fddd7b41748355bb7017/
3. Try to access non existing admin path, ex: http://shop.dev.magento.com/admin/xxx
3.1 User should redirected to start-up page

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Jitheesh. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by Jitheesh** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Jitheesh. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Jitheesh, here is your [new Magento instance](https://pr-21455.instances.magento-community.engineering).
Admin access: [https://pr-21455.instances.magento-community.engineering/admin](https://pr-21455.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-4397](https://jira.corp.magento.com/browse/ENGCOM-4397) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
✔️ QA passed

**Pull request merged**
