### PR TITLE
Fix - 36409:- Update disable_auto_group_change in Customer Import

### LINKED ISSUE #36409: Customer Import: update to `disable_auto_group_change` ignored
### Preconditions and environment

1.Magento 2.3.5-p2
2.Customer exists

### Steps to reproduce

1. Go to System > Import/Export > Export
2. Select type: Customer Main File
3. Export Customer record
4. In downloaded file, strip out all non-required fields except for `disable_auto_group_change`
5. Change `disable_auto_group_change` value(if the customer already has the disable auto group change checked in their customer record, switch the 1 above to 0)
6. Go to System > Import/Export > Import
7. Select Type: Customer Main File
8. Select Import Behavior: Add/Update Complex Data
9. Upload File
10. Check Data
11. Import File

### Expected result

1. Customer record shows change in 'Disable Automatic Group Change Based on VAT ID' setting.

### Actual result

1. No changes in 'Disable Automatic Group Change Based on VAT ID' setting.

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Vasudev-22**
### Description (*)

1. `disable_auto_group_change` attribute is missed in customer import functionality.
2. Added in `Magento/CustomerImportExport/Model/Import/Customer.php`

### Related Pull Requests
Fixes Update disable_auto_group_change in Customer Import(https://github.com/magento/magento2/issues/36409) 

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36409 

### Manual testing scenarios (*)

1. Tested by the customer data by importing and exporting  the values.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Vasudev-22** [comment]
@magento run all tests

**Comment by Vasudev-22** [comment]
@magento run all tests

**Comment by Vasudev-22** [comment]
@magento run Semantic Version Checker

**Comment by Vasudev-22** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hello,

The internal team has started working on the issue.

Thanks.

**Comment by andrewbess** [comment]
This PR already merged and shouldn't have pending review status

**Pull request merged**
