### PR TITLE
magento/magento2#8171: Price not saved when creating product via REST API

### LINKED ISSUE #13639: 2.4 : When saving a product using the product repository, the price is not saved
I'm trying to programmatically create a product, but upon the first save, the price is not saved, thus returning 'NULL'. On a second save (with the identical object), the price gets saved.

### Preconditions

1. Magento 2.4-develop
2. php v 7.2

### Steps to reproduce

    /** @var \Magento\Catalog\Model\Product $product */
    $product = $this->productFactory->create();
    $product->setSku('abc');
    $product->setName('Name');
    $product->setPrice(9.95);
    $product->setAttributeSetId(4);

    // Save once, the price does not get saved:
    $this->productRepository->save($product);

    // Check if the product is saved:
    $product = $this->productRepository->get('abc');
    $this->assertEquals('abc', $product->getSku());          // passes
    $this->assertEquals('Name', $product->getName());  // passes
    $this->assertEquals(9.95, $product->getPrice());  // fails (null does not equal 9.95

When I add an extra `save()`-instruction it works:

    // Save twice, the price gets saved:
    $this->productRepository->save($product);
    $this->productRepository->save($product);

### Expected result

The price should be saved in the first run

### Actual result

The price only gets saved the second time the `save()`-method is executed

### LINKED ISSUE #29504: [Issue] magento/magento2#8171: Price not saved when creating product via REST API
This issue is automatically created based on existing pull request: magento/magento2#24606: magento/magento2#8171: Price not saved when creating product via REST API

---------

### Description (*)

The change covers adding a default typeId set to **simple** for new products created if no other is sent in post request.

### Fixed Issues (if relevant)

1. magento/magento2#8171: Price not saved when creating product via REST API

### Preconditions (*)

1. Magento 2.4 CE

### Steps to reproduce (*)

1. Do a POST request to rest/V1/products? with a minimum payload to create a product.

{
"product": {
"sku": "test",
"name": "test",
"price": 12.5,
"attribute_set_id": 4
}
}

### Expected result (*)

1.Created product should have visible and set price.

### Actual result (*)

1. [Screenshots, logs or description]
image

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### LINKED ISSUE #30487: Price not saved when creating product via REST API
### Preconditions

1. Magento 2.1.2

### Steps to reproduce

1. Do a POST request to /products with a minimum payload to create a product.

{
  "product": {
    "sku": "test",
    "name": "test",
    "price": 12.5,
    "attribute_set_id": 4
  }
}

### Expected result

1. Product is returned with all given fields filled in.

### Actual result

1. Product is returned without the price. Saving (updating) the product via the same request does save the price.

### PR DESCRIPTION
**Pull request by jarzebowsky**
### Description (*)

The change covers adding a default typeId set to **simple** for new products created if no other is sent in post request.

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/345
https://github.com/magento/partners-magento2b2b/pull/349

### Fixed Issues (if relevant)

1. magento/magento2#8171: Price not saved when creating product via REST API
2. Fixes https://github.com/magento/magento2/issues/13639
2. Fixes https://github.com/magento/magento2/issues/30487

### Manual testing scenarios (*)

1. Do a POST request to /products with a minimum payload to create a product.
```
{
"product": {
"sku": "test",
"name": "test",
"price": 12.5,
"attribute_set_id": 4
}
}
```
2. Created product should have visible and set price.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29504: magento/magento2#8171: Price not saved when creating product via REST API

### CODE REVIEW

**Comment by miguelbalparda** [comment]
Hi @Jarzebowsky I just realized I can't process this PR because you haven't signed the CLA, you mind doing it so we can move forward? Thanks!

**Comment by jarzebowsky** [comment]
Hi @miguelbalparda I'm not able to get into license page as I saw you were doing some changes there. Could you please provide steps to make it go thru? :)

**Comment by sidolov** [comment]
@Jarzebowsky please, use `Adobe CLA Signed?` to sign the agreement.

**Review by novikor — CHANGES_REQUESTED** [review]
Hi, @Jarzebowsky ! Thank you for your contribution.
Please fix the static tests

**Review by novikor — APPROVED** [review]
Good job!

**Comment by magento-engcom-team** [comment]
Hi @novikor, thank you for the review.
[ENGCOM-6911](https://jira.corp.magento.com/browse/ENGCOM-6911) has been created to process this Pull Request
:eight_spoked_asterisk: @novikor, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by novikor — CHANGES_REQUESTED** [review]
Hi, @Jarzebowsky . 
Don't you mind to cover the PR with WebAPI tests? Just forgot about this before approval, my bad

**Comment by engcom-Golf** [comment]
I will cover changes with automated tests

**Comment by engcom-Golf** [comment]
Hi @novikor could you please review test coverage ?

**Review by novikor — DISMISSED** [review]
@engcom-Golf , thank you!

**Comment by magento-engcom-team** [comment]
Hi @novikor, thank you for the review.
[ENGCOM-6911](https://jira.corp.magento.com/browse/ENGCOM-6911) has been created to process this Pull Request

**Comment by engcom-Golf** [comment]
Hi @novikor could you please  approve it one more time ? :)

**Review by novikor — DISMISSED** [review]
@engcom-Golf , - here it is :)

**Comment by magento-engcom-team** [comment]
Hi @novikor, thank you for the review.
[ENGCOM-6911](https://jira.corp.magento.com/browse/ENGCOM-6911) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by slavvka** [comment]
Performance tests are failing here. Need to get an approval.
```
2020/02/25 16:01:04 ERROR - jmeter.protocol.http.sampler.HTTPJavaImpl: readResponse: java.io.IOException: Server returned HTTP response code: 400 for URL: http://localhost/builds/rest/default/V1/products 
2020/02/25 16:01:04 ERROR - jmeter.protocol.http.sampler.HTTPJavaImpl: Cause: java.io.IOException: Server returned HTTP response code: 400 for URL: http://localhost/builds/rest/default/V1/products 
2020/02/25 16:01:04 INFO  - jmeter.protocol.http.sampler.HTTPJavaImpl: Error Response Code: 400 

2020/02/25 16:01:04 ERROR - jmeter.protocol.http.sampler.HTTPJavaImpl: readResponse: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost/builds/rest/default/V1/products//stockItems/ 
2020/02/25 16:01:04 ERROR - jmeter.protocol.http.sampler.HTTPJavaImpl: Cause: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost/builds/rest/default/V1/products//stockItems/ 

2020/02/25 16:01:04 INFO  - jmeter.protocol.http.sampler.HTTPJavaImpl: Error Response Code: 500 
2020/02/25 16:01:04 ERROR - jmeter.protocol.http.sampler.HTTPJavaImpl: readResponse: java.io.IOException: Server returned HTTP response code: 400 for URL: http://localhost/builds/rest/default/V1/products/ 
2020/02/25 16:01:04 ERROR - jmeter.protocol.http.sampler.HTTPJavaImpl: Cause: java.io.IOException: Server returned HTTP response code: 400 for URL: http://localhost/builds/rest/default/V1/products/ 
2020/02/25 16:01:04 INFO  - jmeter.protocol.http.sampler.HTTPJavaImpl: Error Response Code: 400 
```

**Comment by sidolov** [comment]
@magento create issue

**Comment by sidolov** [comment]
@Jarzebowsky did you have a chance to take a look at the [comment above](https://github.com/magento/magento2/pull/24606#issuecomment-591487084)?

**Review by sidolov — CHANGES_REQUESTED** [review]
Waiting for reporter

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
> Performance tests are failing here. Looks like API is failing. @Jarzebowsky could you please check if these API endpoints are working after your fix?
> 
> ```
> 2020/02/25 16:01:04 ERROR - jmeter.protocol.http.sampler.HTTPJavaImpl: readResponse: java.io.IOException: Server returned HTTP response code: 400 for URL: http://localhost/builds/rest/default/V1/products 
> 2020/02/25 16:01:04 ERROR - jmeter.protocol.http.sampler.HTTPJavaImpl: Cause: java.io.IOException: Server returned HTTP response code: 400 for URL: http://localhost/builds/rest/default/V1/products 
> 2020/02/25 16:01:04 INFO  - jmeter.protocol.http.sampler.HTTPJavaImpl: Error Response Code: 400 
> 
> 2020/02/25 16:01:04 ERROR - jmeter.protocol.http.sampler.HTTPJavaImpl: readResponse: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost/builds/rest/default/V1/products//stockItems/ 
> 2020/02/25 16:01:04 ERROR - jmeter.protocol.http.sampler.HTTPJavaImpl: Cause: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost/builds/rest/default/V1/products//stockItems/ 
> 2020/02/25 16:01:04 INFO  - jmeter.protocol.http.sampler.HTTPJavaImpl: Error Response Code: 500 
> 
> 2020/02/25 16:01:04 ERROR - jmeter.protocol.http.sampler.HTTPJavaImpl: readResponse: java.io.IOException: Server returned HTTP response code: 400 for URL: http://localhost/builds/rest/default/V1/products/ 
> 2020/02/25 16:01:04 ERROR - jmeter.protocol.http.sampler.HTTPJavaImpl: Cause: java.io.IOException: Server returned HTTP response code: 400 for URL: http://localhost/builds/rest/default/V1/products/ 
> 2020/02/25 16:01:04 INFO  - jmeter.protocol.http.sampler.HTTPJavaImpl: Error Response Code: 400 
> ```

PAT failures should be fixed by https://github.com/magento/magento2/pull/24606/commits/25c37b57a83354a9b1c38fd06a56ebd2b9bb5aec

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
This PR changes the behavior of an API, previously products were created on payloads without price, now they will fail. Since this is BIC we will aim to deliver this on 2.5.

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Pull request closed without merging**
