### PR TITLE
Use table alias for qty field

### PR DESCRIPTION
**Pull request by mikekeilty**
This was an issue with joining tables to the collection used for the lowstock report grid, as the qty field was ambiguous.

This allows Magento to use a table prefix for the qty field, enabling other tables to be joined easily.

### CODE REVIEW

**Comment by kokoc** [comment]
@mikekeilty Thank you for the contribution!

:white_check_mark: CR: passed
:white_check_mark: Resolution: Ready to merge
:white_check_mark: Builds: Green
:white_check_mark: Internal reference: MAGETWO-36413

**Comment by mikekeilty** [comment]
You're welcome!

**Comment by mikekeilty** [comment]
I don't know how that merge commit got attached to this pull request, but it was a mistake.

**Comment by kokoc** [comment]
@mikekeilty your pull request is merged in 0.74.0-beta10. Thank you very much for your contribution and continued support to Magento 2!

**Pull request merged**
