### PR TITLE
[MFTF] Adding AdminClickAddNewPageOnPagesGridActionGroup

### LINKED ISSUE #31627: [Issue] [MFTF] Adding AdminClickAddNewPageOnPagesGridActionGroup
This issue is automatically created based on existing pull request: magento/magento2#31595: [MFTF] Adding AdminClickAddNewPageOnPagesGridActionGroup

---------
### Description (*)
Tests have been updated with AdminClickAddNewPageOnPagesGridActionGroup

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
Tests have been updated with AdminClickAddNewPageOnPagesGridActionGroup

### Resolved issues:
1. [x] resolves magento/magento2#31627: [MFTF] Adding AdminClickAddNewPageOnPagesGridActionGroup

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Review by rogyar — APPROVED** [review]
Hi @AnnaAPak. Good job. I would recommend focusing on more complex refactoring than replacing clicks with separate action groups. This particular activity might be postponed to the "very end".

Thanks

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8613](https://jira.corp.magento.com/browse/ENGCOM-8613) has been created to process this Pull Request

**Comment by sidolov** [comment]
@magento create issue

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** Functional Tests B2B , Functional Tests CE and Functional Tests EE are failed

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
