### PR TITLE
MC-40678: Cart page subtotal shows wrong when we back from multishipping

### LINKED ISSUE #31889: Cart page subtotal shows wrong when we back from multishipping
### Preconditions (*)
1. Magento V2.4.1
1. PHP 7.3.24

### Steps to reproduce (*)
1. Add 2 or more items to the basket then go to the Multiple Addresses selection page
Like I have added 5 qty on the same product and selected the 1st address for 3 qty and 2nd address for 2 qty.
1. From the Address selection page I'm going to the next step of the shipping method selection.
1. Now go to the back on the cart page and check the summary subtotal and it shows the subtotal of 1st address and it's wrong.

### Expected result (*)
1. Need to show correct subtotal after come back from multi shipping

### Actual result (*)
1. It's showing the wrong subtotal on the cart page. The subtotal needs to calculate of Address 1 + Address 2 but it's only showing the Address 1 subtotal.
## 

Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as a Reporter. This information will help during Confirmation and Issue triage processes.

- <x] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- [ > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

### PR DESCRIPTION
**Pull request by engcom-Golf**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#31889

### Manual testing scenarios (*)

1. Login as a customer
2. Add 2 simple products to the cart
3. Navigate to the cart page
4. Click checkout with multiple addresses
5. select for 2 products different addresses
6. click update Qty and Addresses
7. Go back to the cart page
Expected result:
See correct totals price in totals block
Multi-shipping deactivated and multiple addresses reset to a single one

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Golf** [comment]
@magento run all tests

**Review by zakdma — APPROVED** [review]

**Comment by dmitriyprime** [comment]
@magento i am working on it

**Comment by dmitriyprime** [comment]
:heavy_check_mark: QA passed
Was checked case from Manual testing scenario

:x: Before:
image


:heavy_check_mark: After:
image

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31925`.

**Pull request merged**
