### PR TITLE
Clean up `catalogrule_product_price_replica` table

### LINKED ISSUE #31752: Partial Catalog Product Price Indexing not removing old price date and is extremely slow if store has many products (above 200k)
### Preconditions (*)

1. Magento 2.4.1 + PHP 7.4.10 + MySQL 8.0.22
2. At least 200k simple products
3. Have at least 8 catalog price rules

### Steps to reproduce (*)

1. Set indexes to update by schedule and wait for indexing to complete.
2. Manually run **catalogrule_apply_all** cron job. (this is automatically run at 1am)

### Expected result (*)

1. Once the `partialUpdateCatalogRuleProductPrice` in `Magento\CatalogRule\Model\Indexer\PartialIndex.php` finishes `$this->indexBuilder->reindexFull();` the next code should take little time but the opposite is true.
2. Once the partial indexing is done rules older than yesterday should be removed from table `catalogrule_product_price_replica`

### Actual result (*)

1. Rules with `rule_date` dating back many months are present in `catalogrule_product_price_replica` essentially causing the next problem even worse over time
2. The code below from `partialUpdateCatalogRuleProductPrice` in `Magento\CatalogRule\Model\Indexer\PartialIndex.php` makes MySQL hang for many hours:
```
        $this->connection->query(
            $this->connection->insertFromSelect(
                $selectFields,
                $this->resource->getTableName('catalogrule_product_price_replica'),
                [
                    'rule_date',
                    'customer_group_id',
                    'product_id',
                    'rule_price',
                    'website_id',
                    'latest_start_date',
                    'earliest_end_date',
                ],
                AdapterInterface::INSERT_ON_DUPLICATE
            )
        );
```
Store admin has to also truncate `catalogrule_product_price_replica` once a while to remove old data.
  
It is my understanding from MySQL Workbench that the code will cause many table scans and each insert will fire a trigger that will compare the new data. This statement will put a hold on `catalog_product_price_cl`. This will cause additional cron tasks to get to waiting state and causes additional RAM usage.
A workaround is to disable using `catalogrule_product_price_replica` for partial indexing and perform full price index instead. This is especially true if one is using multithreaded indexing by setting `MAGE_INDEXER_THREADS_COUNT`.

On our store with 1 million simple products it caused cron to crash every afternoon from many cron threads waiting for `catalog_product_price_cl` lock.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by fredden**
### Description

There was a bug which caused the `catalogrule_product_price_replica` table to become unnecessarily large. The bug causing the growth has been resolved in Magento version `2.4.4` - see https://github.com/magento/magento2/issues/31752#issuecomment-996971105.

This schema patch cleans up the damage done by that bug on existing websites. Deleting all entries from this table is safe.

See https://github.com/magento/magento2/issues/31752 for details.

### Related Pull Requests

- These were added directly without using a pull request: https://github.com/magento/magento2/search?q=MC-41807&type=commits - https://github.com/magento/magento2/commit/6e6fff2a87221cd71f0f9e347a1cf35b3460d13f, https://github.com/magento/magento2/commit/6a9f4474fb3a79612799db23c2a1543fc14fbd2f

### Fixed Issues
- Fixes https://github.com/magento/magento2/issues/31752

### Manual testing scenarios
There should be no change to any functionality after applying these changes. This is a data clean-up task.

### Questions or comments
*None*

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Hi @engcom-Hotel,
I think such change should have P2 priority as it's basically wasn't fully fixed in https://github.com/magento/magento2/issues/31752#issuecomment-996971105.

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Magento Health Index, Unit Tests

PS: I think adding a new data patch shouldn't cause MHI failure, so that I would treat it as a false positive.

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests look not related to changes from this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9399](https://jira.corp.magento.com/browse/ENGCOM-9399) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B, Magento Health Index

**Comment by engcom-Alfa** [comment]
@magento run Magento Health Index

**Comment by engcom-Alfa** [comment]
@magento run Magento Health Index

**Comment by fredden** [comment]
Hi @engcom-Alfa. Thanks for your input. Per [the documentation on schema patches](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/declarative-schema/data-patches.html), you will need to run `bin/magento setup:upgrade` (or `bin/magento setup:db-schema:upgrade` may also work). Note that the patch will apply only once, so if you've already run this (or want to test it again), you can remove the relevant entry from the `patch_list` database table.

When applied, the changes in this pull request should remove all data / rows / entries / values from the `catalogrule_product_price_replica` database table.

**Comment by engcom-Alfa** [comment]
@magento run Magento Health Index

**Comment by engcom-Alfa** [comment]
@magento run Magento Health Index

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Have Magento installed.


**Manual testing scenario:**

1. Add one new record into the DB table - **_catalogrule_product_price_replica_**

2. If there are entries existing in the **_patch_list_** DB table, delete the records.
 
3. Run the command from Magento root  - **_bin/magento setup:db-schema:upgrade_**


**Before:** :heavy_multiplication_x: **_catalogrule_product_price_replica_** table records were not getting deleted

image


**After:** :heavy_check_mark: **_catalogrule_product_price_replica_** table records are getting deleted

image


Since it is a new set of cleanup activity added, there is no additional regression is required as it has no impact on any other functionality.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests, Magento Health Index

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE,

**Comment by fredden** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by fredden** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Magento Health Index , Functional Tests B2B , Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B , Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B , Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B , Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Magento Health Index,Functional Tests B2B , Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Modified the patch as per Magento standards, and also fixed few static test failure.

The patch is working fine as per the expectation.

The Functional test cases which are failing in build are not part of PR or not failing because of any changes made in this PR.

Related to Magento Health Index test, working on some internal approval process. Once got the approval we can move this PR further. Till then moving it to Tp Approve status.

Thank you!

**Comment by engcom-Charlie** [comment]
Raise internal JIRA ticket for false positive case of Magento Health Index test. Waiting for the approvals.

**Comment by engcom-Alfa** [comment]
We have Request Approval Ticket - https://jira.corp.magento.com/browse/MC-43350

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by hostep** [comment]
Hi guys, what would be the status here? Would love to see this being merged. But it's been pretty quiet here since a few months 🙂

**Comment by fredden** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@hostep Trying to get it updated and going again.

Still needs a Health Check build figured out so will definitely take extra time.

**Comment by engcom-Charlie** [comment]
Got required approvals for [JIRA](https://jira.corp.magento.com/browse/MC-43350) hence moving it to Merge in Progress.

Thank you!

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run Functional Tests CE

**Pull request merged**
