### PR TITLE
Handle the error properly when LESS source file is empty or having compilation error, and make the error message clear and clean.

### PR DESCRIPTION
**Pull request by Hailong**
### Description (*)

Sometimes developer may want to put a `<css src=...` reference in the layout xml file first to get it ready, while leave an empty LESS source file (or with some comments) there to work later on.

Now the `setup:static-content:deploy` command would fail and print a full callstack of exception, while the callstack doesn't really show the real problem. Moreover, the deployment is actually moving on, until it gets a PHP error that failed to open CSS file, which it should never try since its LESS source is empty already.

This fix is to address such issue, print a clear error message, and to avoid the final PHP open file error. It covers the following two conditions:

1. LESS file is empty.
2. LESS file has compilation errors.

### Fixed Issues (if relevant)

1. magento/magento2#22183: Empty LESS source file causes setup:static-content:deploy command fail
### Manual testing scenarios (*)

1. Clone the 2.3-develop branch, and install a new site.
2. Add a LESS file to `app/design/frontend/Magento/blank/web/css/test-empty.less`, which has NO content or just some comments.
3. Add `<css src="css/test-empty.css"/>` to `app/design/frontend/Magento/blank/Magento_Theme/layout/default_head_blocks.xml`
4. Now run the `setup:static-content:deploy` command to compile.
5. We should be able to see the error message, and the compilation should complete with no other errors.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by josefbehr — APPROVED** [review]

**Comment by josefbehr** [comment]
@Hailong great PR, thank you. Not sure why the travis build failed, error message had nothing to do with this change, I'll trigger the build again and approve.

**Comment by magento-engcom-team** [comment]
Hi @josefbehr, thank you for the review.
[ENGCOM-5612](https://jira.corp.magento.com/browse/ENGCOM-5612) has been created to process this Pull Request
:eight_spoked_asterisk: @josefbehr, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @Hailong !

During testing we faced the issue

**_Problem:_** When LESS file is empty, compilation stops with error message

**Steps to reproduce:**

1. Clone the 2.3-develop branch;
2. Add a LESS file to `app/design/frontend/Magento/blank/web/css/test-empty.less`, which has **NO** content
3. Add `<css src="css/test-empty.css"/>` to `app/design/frontend/Magento/blank/Magento_Theme/layout/default_head_blocks.xml`
4. Now run the setup:static-content:deploy command to compile.

**Actual Result:**
after2

@Hailong Is it correct message?

If we add some comments to `test-empty.less` then it will display correct message and continue compilation
after

@Hailong Could you take a look, please?

Thanks!

**Comment by Hailong** [comment]
Hi @engcom-Alfa , yes your first screenshot is the error message I want to remove with this pull request. While I think no matter there is comment in the empty file, we would get the first screenshot as I described in the [issue report](https://github.com/magento/magento2/issues/22183).

**Comment by engcom-Alfa** [comment]
Hi @Hailong , the error message from first screenshot occurs on branch with PR changes when `test-empty.css` file still empty, but if we add some comments to this file we got the result from second screenshot.

Could you take a look?

Thanks!

**Comment by Hailong** [comment]
Hi @engcom-Alfa , I have updated the code so that it prints the error message properly in both of these two cases.

**Comment by josefbehr** [comment]
@Hailong Thank you. It seems tests have to be adapted, too. Can you do this?

**Comment by Hailong** [comment]
Hi @josefbehr , I have adapted the tests accordingly.

**Review by josefbehr — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @josefbehr, thank you for the review.
[ENGCOM-5612](https://jira.corp.magento.com/browse/ENGCOM-5612) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
