### PR TITLE
[Backport] Fixed #19605 Don't static compile disabled modules

### LINKED ISSUE #19605: Don't static compile disabled modules
### Summary (*)

When running static-content:deploy, there are disabled module content in pub/static.

### Examples (*)

Disable modules that have frontend resources.
Run `bin/magento setup:static-content:deploy`
Observe that `pub/static/...` contains the resources.

### Proposed solution

Check the disabled modules and skip them when compiling static content

### PR DESCRIPTION
**Pull request by shikhamis11**
### Original Pull Request 
 https://github.com/magento/magento2/pull/19751
Fixed issue #19605 Don't static compile disabled modules

**Summary** 
 When running static-content:deploy, there are disabled module content in pub/static.

**Examples** 

Disable modules that have frontend resources.
Run bin/magento setup:static-content:deploy
Observe that pub/static/... contains the resources.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3756](https://jira.corp.magento.com/browse/ENGCOM-3756) has been created to process this Pull Request

**Review by orlangur — APPROVED** [review]
From https://github.com/magento/magento2/commit/a557683a0c1ec47fb7797758fccd3686bbec4bba#diff-5d7224ff8a7eb9c1bba99ebdde05119f it looks like static tests failures are going to be fixed by internal team.

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3756](https://jira.corp.magento.com/browse/ENGCOM-3756) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.

**Pull request merged**
