### PR TITLE
Bringing menu items to one style - plural

### PR DESCRIPTION
**Pull request by nja78**
While translating have noticed that menu items styles differs.
Example for Marketing -> Promotions:
current
- Catalog Price Rule
- Cart Price Rules

new
- Catalog Price Rules
- Cart Price Rules

Same for acl titles and main grid.

### CODE REVIEW

**Comment by magento-cicd** [comment]
We have automated a Magento Contributor License Agreement verifier for contributions sent to our GitHub projects.
Please see the CLA agreement in the Pull Request comments.

**Comment by vzabaznov** [comment]
@nja78 thank you for contributing, please could you update your code and resolve conflicts

**Comment by KrystynaKabannyk** [comment]
The internal ticket is created MAGETWO-50776.

**Comment by vrann** [comment]
@nja78 While this is a good change, I have concerns accepting it. String literals translated via ``__()`` is a subject of backward compatibility rules, because translation packages depend on the exact value of the string. Having little severance of this issue but the potential damage to translation packages, I would reject it.

But regardless, thank you for participation in the Magento community!

**Pull request closed without merging**
