### PR TITLE
magento/magento2#18990: Shipping address is not validated in checkout…

### PR DESCRIPTION
**Pull request by StasKozar**
https://github.com/magento/magento2/issues/18990

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19038) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @StasKozar. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3386](https://jira.corp.magento.com/browse/ENGCOM-3386) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @StasKozar. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
