### PR TITLE
#19623 :: Error message for the website admin when trying to add a re…

### PR DESCRIPTION
**Pull request by irshad-sheikh**
…view Magento 2.3

### Description (*)
Magento 2.3 admin receives an error message when trying to add a review and the stars rating is unavailable. I have fixed this issue, now review is getting added properly from the megento admin.

### Fixed Issues (if relevant)
1. magento/magento2 #19623: Error message for the website admin when trying to add a review Magento 2.3

### Manual testing scenarios (*)
1. Sign in to Magento backend.
2. Marketing > Reviews > New Review
3. Select a product to review
4. Add review details and click 'Save Review' button

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @irshad-sheikh. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by osrecio** [comment]
@magento-engcom-team give me test instance
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @osrecio. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @osrecio, here is your [new Magento instance](https://pr-20266.instances.magento-community.engineering).
Admin access: [https://pr-20266.instances.magento-community.engineering/admin](https://pr-20266.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by osrecio** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @osrecio. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @osrecio, here is your [new Magento instance](https://pr-20266.instances.magento-community.engineering).
Admin access: [https://pr-20266.instances.magento-community.engineering/admin](https://pr-20266.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by osrecio** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @osrecio. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @osrecio, here is your [Magento instance](https://i-20266-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20266-2-3-develop.instances.magento-community.engineering/admin](https://i-20266-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by osrecio — APPROVED** [review]
Hi @irshad-sheikh ,

I tested in automatized environments and my local environment and works fine.

Thanks for your contribution!

**Comment by magento-engcom-team** [comment]
Hi @osrecio, thank you for the review.
[ENGCOM-3908](https://jira.corp.magento.com/browse/ENGCOM-3908) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@irshad-sheikh thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by sivaschenko** [comment]
Hi @irshad-sheikh , the `JsonProductInfo` controller is used to retrive information without changing the system state, so it should be accessed using `GET` method. The issue is fixed on client side in this pull request: https://github.com/magento/magento2/pull/20146 .

I am closing this pull request as duplicate, please contact me in case of any questions or comments.

**Pull request closed without merging**
