### PR TITLE
[View] Removed extra space in link and script tag

### LINKED ISSUE #32920: [Issue] [View] Removed extra space in link and script tag
This issue is automatically created based on existing pull request: magento/magento2#32919: [View] Removed extra space in link and script tag

---------
### Description (*)
This PR helps to change extra spaces into single space in `<link>` and `<script>` tag.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
1. `./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist lib/internal/Magento/Framework/View/Test/Unit/Page/Config/RendererTest.php`
2. Open the store and see `<link>` and `<script>` tag using view source code.
3. `<link>` and `<script>` should be without double spaces between attributes.

**Actual Result:**
w_extraspace

**Excepted Result:**
wo_extraspace

### Questions or comments
Please let me your suggestions if any

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by srsathish92**
### Description (*)
This PR helps to change extra spaces into single space in `<link>` and `<script>` tag.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
1. `./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist lib/internal/Magento/Framework/View/Test/Unit/Page/Config/RendererTest.php`
2. Open the store and see `<link>` and `<script>` tag using view source code.
3. `<link>` and `<script>` should be without double spaces between attributes.

**Actual Result:**
w_extraspace

**Excepted Result:**
wo_extraspace

### Questions or comments
Please let me your suggestions if any

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32920: [View] Removed extra space in link and script tag

### CODE REVIEW

**Comment by srsathish92** [comment]
@magento run all tests

**Comment by srsathish92** [comment]
@magento create issue

**Comment by Den4ik** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by srsathish92** [comment]
@magento run Functional Tests B2B

**Comment by srsathish92** [comment]
@magento run Functional Tests B2B

**Review by Den4ik — APPROVED** [review]
Hi @srsathish92 Thanks for your contribution

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9060](https://jira.corp.magento.com/browse/ENGCOM-9060) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by ptylek — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-9060](https://jira.corp.magento.com/browse/ENGCOM-9060) has been created to process this Pull Request

**Comment by Den4ik** [comment]
I'm not sure that usage of multiple spaces in attributes is a good practice and useful use case

**Review by engcom-Delta — CHANGES_REQUESTED** [review]
Please resolve the conflicts on this PR

**Comment by srsathish92** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
@magento run Static Tests, Integration Tests, Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by engcom-November** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by engcom-November** [comment]
For functional tests, repeating failures are known issues and are flaky.

**Functional Tests B2B:**
**1st Run:**
image

**2nd Run:**
image

Known issues:
[ACQE-6523](https://jira.corp.adobe.com/browse/ACQE-6523) - AdminReorderWithCatalogPriceRuleDiscountTest


**Functional Tests CE:**
**1st Run:**
image

**2nd Run:**
image

Known issues:
[ACQE-6590](https://jira.corp.adobe.com/browse/ACQE-6590) - AdminCheckConfigurationForPayPalExpressCheckoutInUnitesStatesTest


**Functional Tests EE:**
**1st Run:**
image

**2nd Run:**
image

Known issues:
[ACQE-6523](https://jira.corp.adobe.com/browse/ACQE-6523) - AdminReorderWithCatalogPriceRuleDiscountTest
[ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331) - StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest

**Comment by engcom-November** [comment]
WebAPI repeating failure is known issue and is flaky.

**1st Run:**
image

**2nd Run:**
image

Known issue:
[ACP2E-3082](https://jira.corp.adobe.com/browse/ACP2E-3082) - testSendNegotiableQuoteCannotResend

Hence moving this to **Merge in Progress**

**Pull request merged**
