### PR TITLE
Fix iterate on null

### LINKED ISSUE #30830: [Issue] Fix iterate on null
This issue is automatically created based on existing pull request: magento/magento2#30822: Fix iterate on null

---------
### Preconditions (*)
Magento 2.4-develop
If there is no carriers available on the store (no carriers modules), an iteration on null occurs.

### Steps to reproduce
- Disable shipping modules:
image
- Create simple product
- Go to storefront
- Add product to cart
- Go to checkout page

### Expected result (*)
1. No errors is shown on checkout shipping page
image
2. Message "Sorry, no quotes are available for this order at this time" is shown
image

### Actual result (*)
1. Blank checkout page
2. Error "array_keys() expects parameter 1 to be array, null given" is recorded into exception.log
image

### PR DESCRIPTION
**Pull request by thomas-kl1**
If there is no carriers available on the store (no carriers modules), an iteration on null occurs.

### Resolved issues:
1. [x] resolves magento/magento2#30830: Fix iterate on null

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Review by sidolov — CHANGES_REQUESTED** [review]
@thomas-kl1 please cover changes at least with the unit test to avoid such issues in the future. Thank you!

**Comment by engcom-Charlie** [comment]
@thomas-kl1 I'll take care of test coverage.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8469](https://jira.corp.magento.com/browse/ENGCOM-8469) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Manual testing scenario:**

- Disable shipping modules:
image
- Create simple product
- Go to storefront
- Add product to cart
- Go to checkout page

**Before:**
:x: Blank checkout page
:x: Error "array_keys() expects parameter 1 to be array, null given" is recorded into exception.log
image


**After:**
:heavy_check_mark: No errors is shown on checkout shipping page
image
:heavy_check_mark: Message "Sorry, no quotes are available for this order at this time" is shown
image

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Pull request merged**
