### PR TITLE
Exclude CMS pages from sitemap by URL key not configuration value

### LINKED ISSUE #35001: Sitemap contains utility pages in multi store setup
### Preconditions (*)

1. Magento 2.4.2-p2

### Steps to reproduce (*)

1. Create second store view
2. Duplicate "home" (or "enable-cookies" or "no-route") cms page 
3. Set "Page in websites" of original page to default store view and for the duplicate page to second store view
4. Change autogenerated url key of the duplicated page to the same url key like the original page (may be optional)
5. Assign original page as "CMS Home page" for default store view (Configuration > General > Web > Default pages)
6. Assign duplicate as "CMS Home page" for second store view
7. Create & generate Sitemaps for both store views

### Expected result (*)

1. Sitemaps of both store views doesn't contain the assigned default pages

### Actual result (*)

1. Sitemap of second store view contains the assigned default pages (because \Magento\Cms\Model\GetUtilityPageIdentifiers::execute() returns the page identifiers of second store view with appended | (pipe) and page id and these identifiers dont match the identifier of the duplicate page)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by fredden**
### Description
- When generating a sitemap, special care is taken to exclude the three 'utility' CMS pages: `home`, `no-route`, `enable-cookies`.
- When the same URL key exists for multiple CMS pages (which is perfectly valid when these are scoped to different stores), the configuration option for these utility pages stores `url-key|ID` (eg `home|6` or `no-route|771`).

These two features were not compatible with one another. This was raised in https://github.com/magento/magento2/issues/35001. This pull request makes these two features compatible, so that utility pages are no longer included in sitemaps as intended.

### Fixed Issues
1. Fixes https://github.com/magento/magento2/issues/35001

### Manual testing scenarios
See 'steps to reproduce' on https://github.com/magento/magento2/issues/35001

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @fredden,

Thanks for the contribution!

Please take care of the failed tests.

Thanks

**Comment by fredden** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests look not related to changes from this PR.

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**
- Create second store view
- Duplicate "home" (or "enable-cookies" or "no-route") cms page
- Set "Page in websites" of original page to default store view and for the duplicate page to second store view
- Change autogenerated url key of the duplicated page to the same url key like the original page.
- Assign original page as "CMS Home page" for default store view (Configuration > General > Web > Default pages)
- Assign duplicate as "CMS Home page" for second store view
- Create & generate Sitemaps for both store views

**Before:** :heavy_multiplication_x: 
Screenshot 2023-06-13 at 1 14 30 PM


**After:** :heavy_check_mark:  
Screenshot 2023-06-13 at 1 19 18 PM


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
Functional Tests EE,Functional Tests CE,Functional Tests B2B failures are different on last run.

Functional Tests CE
Run1
image

Run2
image

Functional Tests EE
Run1
image

Run2
image

Functional Tests B2B
Run1
image

Run2
image

Hence moving to `Merge In Progress`

**Comment by hostep** [comment]
It looks like this PR got merged in 2.4-develop recently via: https://github.com/magento/magento2/commit/d4a9791d0f589ee1006beba25c240a39a59d50e9

But this PR is not marked as merged, which is quite strange? I've found at least 2 other PR's where the same thing happened, any idea what's going on here? A bug in github? A mistake made by Adobe? Something else? ...

**Comment by engcom-Charlie** [comment]
> It looks like this PR got merged in 2.4-develop recently via: [d4a9791](https://github.com/magento/magento2/commit/d4a9791d0f589ee1006beba25c240a39a59d50e9)
> 
> But this PR is not marked as merged, which is quite strange? I've found at least 3 other PR's where the same thing happened, any idea what's going on here? A bug in github? A mistake made by Adobe? Something else? ...

Hi @hostep,

It is not a bug, after adding this this PR into mainline PR we have added one commit of merging 2.4-dev into this, that is the reason it is still showing as in Open status

Thank you!

**Comment by ihor-sviziev** [comment]
Closing this PR due to it was already merged in https://github.com/magento/magento2/pull/35156#issuecomment-1636784101, but left only the merge commit

**Pull request closed without merging**
