### PR TITLE
Translation in backend/validation.js

### PR DESCRIPTION
**Pull request by sIiiS**
added $.mage.__

### CODE REVIEW

**Comment by vkublytskyi** [comment]
@sIiiS, thank you for contribution. Would you combine your PRs #5252, #5253 and #5254 into single one?

**Comment by quienti** [comment]
https://github.com/magento/magento2/pull/4705/

**Comment by sIiiS** [comment]
@vkublytskyi : yes please combine them if possible

**Comment by dvynograd** [comment]
@vkublytskyi Please take a look into that PR #5725

**Comment by vkorotun** [comment]
Internal ticket: MAGETWO-56548

**Comment by VladimirZaets** [comment]
Hello, @sIiiS. Thank you for contribution,the fix that you suggest is already merged in scope PR  https://github.com/magento/magento2/pull/5725. Please get back to us if you have any questions regarding it. Thanks.

**Pull request closed without merging**
