### PR TITLE
Replace 'static::' with 'self::' when accessing private const.

### LINKED ISSUE #30781: [Issue] Replace 'static::' with 'self::' when accessing private const.
This issue is automatically created based on existing pull request: magento/magento2#30774: Replace 'static::' with 'self::' when accessing private const.

---------
# Description
Magento 2.4 -develop

This PR prevents 'Undefined class constant' error if a plugin will be added for one of these classes. Example: 

### Related Pull Requests
https://github.com/magento/magento2/pull/28797
https://github.com/magento/magento2/pull/29925

### Case 1 

Create a plugin for : `Magento\Backend\ViewModel\ChartDisabled` class

**Actual Result:** :heavy_multiplication_x: error occurs

Screenshot from 2020-11-05 13-20-42

### Case 2

Create a plugin for : `Magento\Catalog\Model\Config\LayerCategoryConfig` class

**Actual Result:** :heavy_multiplication_x: error occurs

Screenshot from 2020-11-05 14-43-46

### Case 3

Create a plugin for : `Magento\DownloadableImportExport\Model\Import\Product\Type\Downloadable` class

**Actual Result:** :heavy_multiplication_x: error occurs

**Expected Result:** :heavy_check_mark: No errors when plugins are called

### Related Issues
1. https://github.com/magento/magento-coding-standard/issues/197

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by vovayatsyuk**
# Description

This PR prevents 'Undefined class constant' error if a plugin will be added for one of these classes. Example: 

### Related Pull Requests
https://github.com/magento/magento2/pull/28797
https://github.com/magento/magento2/pull/29925

### Related Issues
1. https://github.com/magento/magento-coding-standard/issues/197

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30781: Replace 'static::' with 'self::' when accessing private const.

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Hi @vovayatsyuk,
Will you be able to contribute static test for such case in order not to have such new cases in future?

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento create issue

**Comment by vovayatsyuk** [comment]
Yes, sure. I'll try in a few days.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@vovayatsyuk cool! For now I'm approving this PR, please create static test as a separate PR, I'll try to review it ASAP

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8425](https://jira.corp.magento.com/browse/ENGCOM-8425) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

### Case 1 

Create a plugin for : `Magento\Backend\ViewModel\ChartDisabled` class

**Before:** :heavy_multiplication_x: error occurs

Screenshot from 2020-11-05 13-20-42

**After:** :heavy_check_mark: No errors when plugin is called



### Case 2

Create a plugin for : `Magento\Catalog\Model\Config\LayerCategoryConfig` class

**Before:** :heavy_multiplication_x: error occurs

Screenshot from 2020-11-05 14-43-46

**After:** :heavy_check_mark: No errors when plugin is called



### Case 3

Create a plugin for : `Magento\DownloadableImportExport\Model\Import\Product\Type\Downloadable` class

**Before:** :heavy_multiplication_x: error occurs



**After:** :heavy_check_mark: No errors when plugin is called

Screenshot from 2020-11-05 15-30-53

**Pull request merged**
