### PR TITLE
Resolved issue of 'Widget sort order category pages'

### LINKED ISSUE #8755: Widget sort order category pages
Sort order of widgets does not work when having some widgets displayed for all categories and some widgets for specific categories. On a category page the widget for that specific category is placed after the widgets for all categories, despite sort_order is lower

### Preconditions

1. Magento 2.4-develop

### Steps to reproduce

1. Add a Static Block widget
1.1 Set priority 20
1.2 Set "display on" to "Anchor categories
1.3 Choose "All categories"

2. Add a second Static Block widget
2.1 Set priority 10
2.2 Set "Display on" to "Anchor categories"
2.3 set "Categories" to "Specific Categories"
2.4 Choose a category

### Expected result

Second widget should display before first widget, because sort order is lower.

### Actual result

Second widget appears after first widget

### PR DESCRIPTION
**Pull request by bichukaleh**
### Description (*)
Sort order of widgets does not work when having some widgets displayed for all categories and some widgets for specific categories. On a category page the widget for that specific category is placed after the widgets for all categories, despite sort_order is lower

### Fixed Issues (if relevant)

1. fixes magento/magento2#8755: Widget sort order category pages

### Manual testing scenarios (*)

1. Add a Static Block widget
1.1 Set priority 20
1.2 Set "display on" to "Anchor categories
1.3 Choose "All categories"

2. Add a second Static Block widget
2.1 Set priority 10
2.2 Set "Display on" to "Anchor categories"
2.3 set "Categories" to "Specific Categories"
2.4 Choose a category

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento run all tests

**Comment by bichukaleh** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @bichukaleh. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @bichukaleh, here is your [new Magento instance](https://pr-27108.instances.magento-community.engineering).
Admin access: [https://pr-27108.instances.magento-community.engineering/admin_a147](https://pr-27108.instances.magento-community.engineering/admin_a147)
Login: `786805e2` Password: `c4c94fe95fd9`
Instance will be terminated in up to 3 hours.

**Comment by rogyar** [comment]
Hi @bichukaleh. Thank you for your collaboration.

Can I ask you to cover your change using MFTF test, please? According to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered by automated tests. 

Thank you!

**Comment by sidolov** [comment]
@bichukaleh  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
