### PR TITLE
ChangeQuoteControl minor refactor

### LINKED ISSUE #29673: [Issue] ChangeQuoteControl minor refactor
This issue is automatically created based on existing pull request: magento/magento2#29669: ChangeQuoteControl minor refactor

---------
### Description (*)
Just a minor refactor to improve readability and Coding Standard
Unit Tests were ✔️ . I just removed redundant annotations (method names are perfectly descriptive) and replaced deprecated ObjectManager with `new` syntax.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Just a minor refactor to improve readability and Coding Standard
Unit Tests were ✔️ . I just removed redundant annotations (method names are perfectly descriptive) and replaced deprecated ObjectManager with `new` syntax.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29673: ChangeQuoteControl minor refactor

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8028](https://jira.corp.magento.com/browse/ENGCOM-8028) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

The general functionality with creation of the order by the customer and the guest was checked, and everything works as previous  (expected).

**Pull request merged**
