### PR TITLE
Remove unnecesary "header" block redeclaration

### PR DESCRIPTION
**Pull request by samuel27m**
### Description (*)
Removed because the "header" block was already created in module Magento_Theme, so this redeclaration is just unnecesary

### Fixed Issues (if relevant)

None found on the Magento 2 issues

### Manual testing scenarios (*)

1. Create new module.
2. Create new default.xml and try to use referenceBlock to set the template. Example:
` <referenceBlock name="header">
            <arguments>
                <argument name="template" xsi:type="string">Samuel27m_Welcome::html/header.phtml</argument>
            </arguments>
        </referenceBlock>`

3. Doesn't work, because Luma theme XML files are compiled after all modules and overrides the custom module modifications.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18772) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @samuel27m. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by samuel27m** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @samuel27m. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @samuel27m, here is your [new Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-18772/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-18772//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-18772//admin)
Login: `admin` Password: `123123q`

**Comment by samuel27m** [comment]
As you can see on the created instance, "header" block is still there and working fine. This redeclaration of the block for the Luma theme is unnecessary.

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-3273](https://jira.corp.magento.com/browse/ENGCOM-3273) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@samuel27m thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by samuel27m** [comment]
@magento-engcom-team Accepted the invitation. Thanks

**Comment by samuel27m** [comment]
@miguelbalparda We could backport this fix to the 2.2-develop branch, should I do that myself?

**Comment by miguelbalparda** [comment]
All yours @samuel27m, thanks for the help!!!

**Comment by magento-engcom-team** [comment]
Hi @samuel27m. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
