### PR TITLE
Issue 36273: Vault payment method appears in admin checkout

### LINKED ISSUE #36273: Customer has no any vault token save, but vault payment method appears in admin checkout
**Issue:**
Customer has no any vault token save, but vault payment method appears in admin checkout

**Steps to reproduce:**
1). Go to Magento Admin panel
2). Setup "Payflow Pro" payment method and enable vault payment (Stores - Configuration - Sales - Payment Methods - Configure "Payflow Pro" - 
Enable this Solution : Yes, Vault Enabled : Yes)
3). Clear cache
4). Admin - Sales - Orders - Create new Order - Create New Customer / or Select any existing customer
5). Add Products
6). Payment Method section - Issue: "Stored Cards (Payflow Pro)" Payment option is getting displayed
Select this payment method option and other required options and fields to place the order
Submit Order: Issue: "Order saving error: Public hash should be defined" error message is displayed to the user.

**Expected result:**
If customer has no token saved, than Vault Payment should not be shown in Payment section of Admin Order creation page

**Actual result:**
Vault Payment option is available for the user even though user has not any token saved
Order saving error: Public hash should be defined" error message is displayed to the user.

### PR DESCRIPTION
**Pull request by rogerdz**
### Description (*)

Create plugin in admin to check vault tokens of customer. If customer does not have a vault token, disable vault payment method

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36273

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run Static Tests

**Comment by engcom-Lima** [comment]
@magento run Static Tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:*
Install fresh Magento `2.4-develop`

**Manual testing scenario:**
1). Go to Magento Admin panel
2). Setup "Payflow Pro" payment method and enable vault payment (Stores - Configuration - Sales - Payment Methods - Configure "Payflow Pro" -
Enable this Solution : Yes, Vault Enabled : Yes)
3). Clear cache
4). Admin - Sales - Orders - Create new Order - Create New Customer / or Select any existing customer
5). Add Products
6). Payment Method section - Issue: "Stored Cards (Payflow Pro)" Payment option is getting displayed
Select this payment method option and other required options and fields to place the order
Submit Order: Issue: "Order saving error: Public hash should be defined" error message is displayed to the user.

**Before:** :heavy_multiplication_x: 
Screenshot 2022-10-19 at 3 51 19 PM


**After:** :heavy_check_mark:  
Screenshot 2022-10-19 at 4 09 36 PM

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
It seems that bot has moved this PR from Extended Testing (optional) to Ready for Testing hence moving it back to Extended Testing.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
It seems that bot moved this PR in Merge in Progress on changing the board hence moving it back to Extended Testing.

Thank you!

**Comment by engcom-Charlie** [comment]
This issue has been taken care by internal team in [JIRA](https://jira.corp.adobe.com/browse/ACP2E-1215). Once it will get merged will notify it here. Till that time, moving it to On Hold.

Thank you!

**Comment by engcom-Bravo** [comment]
Hello,

As per this https://github.com/magento/magento2/issues/36273#issuecomment-1460528832 the issue has been fixed with the mentioned commit.

Thanks.

**Pull request closed without merging**
