### PR TITLE
MFTF: Admin Unlock Admin User Via CLI Test

### PR DESCRIPTION
**Pull request by DmitryTsymbal**
This PR contains a test for unlocking admin user via CLI

**Steps to reproduce:**

1 - Create Admin user

2 - Lock Admin User

3 - Unlock Admin User via Magento CLI

4 - Perform Assertions

### CODE REVIEW

**Comment by DmitryTsymbal** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run Functional Tests CE , Functional Tests B2B , Integration Tests

**Comment by dmytro-ch** [comment]
@magento run Functional Tests CE , Integration Tests

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-9032](https://jira.corp.magento.com/browse/ENGCOM-9032) has been created to process this Pull Request

**Comment by dmitriyprime** [comment]
:heavy_check_mark:  QA passed

after

**Pull request merged**
