### PR TITLE
Products in cart report error when we have grouped or bundle product

### PR DESCRIPTION
**Pull request by mihaifaget**
## Description
Changed inner join with left join for prices because bundle and grouped products don't have prices and report generates error if we have them in cart.

## Fixed Issues
magento/magento2#12079:Products in cart report error when we have grouped or bundle product

### Manual testing scenarios
1. Add a grouped or a bundle product to cart.
2. Go to admin->Reports->Marketing->Products in cart and loop through pages or export to csv/excel
3. Looping through pages or exporting should no longer generate error 

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=12082) <br/>All committers have signed the CLA.

**Comment by ishakhsuvarov** [comment]
Hi @mihaifaget
Could you please take a look at the failed tests on Travis CI? 
Thanks

**Comment by mihaifaget** [comment]
Hi @ishakhsuvarov 
Saw the failed test, but doesn't make sense to me, the only thing I changed was joinInner with joinLeft and I already have it functional on a project.

**Comment by ishakhsuvarov** [comment]
@mihaifaget We can not accept Pull Requests with failed builds, please fix the error or let us know if you need help with this.

**Comment by mihaifaget** [comment]
ok, I closed it

**Comment by ishakhsuvarov** [comment]
@mihaifaget I updated the failing test and will proceed with the merge.
Thanks.

**Pull request merged**
