### PR TITLE
#22224 Attribute set remove 404 fixed.

### PR DESCRIPTION
**Pull request by mahesh-rajawat**
There was 404 error on deleting Attribute Set, Fixed in this PR 

### Fixed Issues (if relevant)

1. #22224 
2. ...

### Manual testing scenarios (*)

1. Created a new attribute set.
2. Try to delete it, no 404 now.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by orlangur — APPROVED** [review]
@nmalevanec what do you think? Should we split it into two controllers maybe?

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4709](https://jira.corp.magento.com/browse/ENGCOM-4709) has been created to process this Pull Request

**Comment by nmalevanec** [comment]
> @nmalevanec what do you think? Should we split it into two controllers maybe?

@orlangur, I believe delete action controller should be restricted only for post requests. And controller clients should be changed to use only post requests.

**Comment by VasylShvorak** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @VasylShvorak. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @VasylShvorak, here is your [Magento instance](https://i-22225-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22225-2-3-develop.instances.magento-community.engineering/admin](https://i-22225-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by VasylShvorak** [comment]
Hi @maheshWebkul721 I cannot reproduce issue [#22224](https://github.com/magento/magento2/issues/22224) on 2.3-develop.

**Comment by orlangur** [comment]
@nmalevanec thanks, that's what I was thinking about - CQRS, etc. Just not sure whether we allowed to do such kind of changes from BC perspective.

**Comment by nmalevanec** [comment]
@orlangur, yes, I thought about BC, and to maintain compatibility implementing get interface is good decision. But BiC has been already introduced by core team

**Comment by sidolov** [comment]
@maheshWebkul721 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by orlangur** [comment]
@maheshWebkul721 are you actually able to reproduce this issue on `2.3-develop`? Please provide additional details.

Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

**Pull request closed without merging**
