### PR TITLE
Deprecate document_root_is_pub from env.php

### PR DESCRIPTION
**Pull request by torhoehn**
### Description

Since the `index.php` has been removed from Magento root, all installations have to be served via `pub` directory. 

### Manual testing scenarios

1. Install Magento
2. Following code will not be written to `env.php` anymore:
```
    'directories' => [
        'document_root_is_pub' => true
    ],
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by torhoehn** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
I think it's not backward compatible change, it's better to deprecate it first

**Comment by torhoehn** [comment]
> I think it's not backward compatible change, it's better to deprecate it first

What case you're thinking about? I didn't find any class that depends on this config and since 2.4.2 there is not an option to run Magento outside of `pub` directory.

**Comment by Stepa4man** [comment]
@torhoehn I think we have to take care about usages of this constant:
image

**Comment by ihor-sviziev** [comment]
That's not only about the Magento core but about 3rt party extensions as well. There might be cases when someone used this constant somewhere.

**Comment by torhoehn** [comment]
> That's not only about the Magento core but about 3rt party extensions as well. There might be cases when someone used this constant somewhere.

@ihor-sviziev So I just should mark the classes and constants as deprecated, right?

**Comment by ihor-sviziev** [comment]
@torhoehn yes, please
PS: class was already deprecated :)

**Comment by torhoehn** [comment]
@ihor-sviziev Okay, will do that. The good thing is that the tests tell me where I have to deprecate something. 😀

**Comment by torhoehn** [comment]
@ihor-sviziev Updated this PR.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Pull request closed without merging**
