### PR TITLE
Removed CliIndexerReindexActionGroup action group usage for CatalogSearch module

### LINKED ISSUE #31628: [Issue] [WIP] Removed CliIndexerReindexActionGroup action group usage for CatalogSearch module
This issue is automatically created based on existing pull request: magento/magento2#31592: [WIP] Removed CliIndexerReindexActionGroup action group usage for CatalogSearch module

---------
### Description
Remove CliIndexerReindexActionGroup action group usage from tests to improve execution time for the CatalogSearch module.

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Remove CliIndexerReindexActionGroup action group usage from tests to improve execution time for the CatalogSearch module.

### Resolved issues:
1. [x] resolves magento/magento2#31628: [WIP] Removed CliIndexerReindexActionGroup action group usage for CatalogSearch module

### CODE REVIEW

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B,Semantic Version Checker

**Comment by rogyar** [comment]
Hi @sergiy-v. It looks like the failing ElasticSearch functional tests might be related to your changes

**Comment by sergiy-v** [comment]
> Hi @sergiy-v. It looks like the failing ElasticSearch functional tests might be related to your changes

@rogyar thanks, will check it.

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B,Semantic Version Checker

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE

**Comment by sergiy-v** [comment]
All Functional tests are green.
@rogyar please proceed with checking.
Thank you.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8695](https://jira.corp.magento.com/browse/ENGCOM-8695) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** Some tests are waiting for status

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run all tests

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Pull request merged**
