### PR TITLE
Fix missing scope on isShippingCarrierAvailable

### LINKED ISSUE #36645: [Issue] Fix missing scope on isShippingCarrierAvailable
This issue is automatically created based on existing pull request: magento/magento2#35817: Fix missing scope on isShippingCarrierAvailable

---------

### Description (*)
The scope to isShippingCarrierAvailable is not applied from $request. This makes issues with shipping methods when quote is being created from backend via 3rd party modules.
This applies storeId scope directly from $request->getStoreId() to make sure scope is not lost when quote is created by admin.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by vo1**
### Description (*)
The scope to isShippingCarrierAvailable is not applied from $request. This makes issues with shipping methods when quote is being created from backend via 3rd party modules.
This applies storeId scope directly from $request->getStoreId() to make sure scope is not lost when quote is created by admin.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36645: Fix missing scope on isShippingCarrierAvailable

### CODE REVIEW

**Comment by vo1** [comment]
@magento give me test instance

**Comment by vo1** [comment]
@magento run all tests

**Comment by vo1** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
@magento create issue

**Pull request merged**
