### PR TITLE
Cli config show returns `Configuration ... doesn't exist` if value is 0 or empty string

### LINKED ISSUE #23290: ./bin/magento config:show returns "Configuration for path: '...' doesn't exist" if config value equals to 0 or empty string
### Preconditions (*)
1. Magento 2.4-develop
2. Create module `Vendor_Module`
3. Create `etc/config.xml` in created module `Vendor_Module` with new config path `default/vendor_module/general/value` with value `0` or `''` (empty string)

### Steps to reproduce (*)
1. Open magento cli and run command `./bin/magento config:show vendor_module/general/value`

### Expected result (*)
1. Should return `0` or `''` (empty string)

### Actual result (*)
1. Command returns `Configuration for path: "vendor_module/general/value" doesn't exist`

I think it happens because there `<magento_root>/vendor/magento/module-config/Console/Command/ConfigShowCommand.php:153` magento checks if value is empty and if it actualy is the error message is shown. But empty value does not mean that path does not exist. So we should check if path exist in different method.

### PR DESCRIPTION
**Pull request by engcom-Charlie**
### Description (*)

Fixed and covered by test.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#23290

### Manual testing scenarios (*)

1. Set any config to `0` or `''` (empty string)
2. Check value cli `bin/magento config:show {{path}}`

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by aleron75 — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-7629](https://jira.corp.magento.com/browse/ENGCOM-7629) has been created to process this Pull Request

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @engcom-Charlie . 

During testing, we faced the issue.

**Manual testing scenario:**

1. Run in console command: `./bin/magento config:set analytics/subscription/enabled '' 
` for example;
:heavy_check_mark: Value was saved
Screenshot from 2020-06-09 11-39-56

2. Run command: `./bin/magento config:show analytics/subscription/enabled`

**Actual Result:** :heavy_multiplication_x: Configuration for path doesn't exist..

Screenshot from 2020-06-09 11-40-50

_Note:_ In `core_config_data` table config was saved with value "**NULL**"

screenshot_46

@engcom-Charlie Could you take a look?
Thanks!

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7629](https://jira.corp.magento.com/browse/ENGCOM-7629) has been created to process this Pull Request

**Comment by engcom-Charlie** [comment]
@magento run Integration Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by aleron75 — APPROVED** [review]
The failing functional test doesn't seem related to this PR; furthermore, I don't understand the code mess checker that complains about too many dependencies which I don't see in the constructor. Thus I approve.

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-7629](https://jira.corp.magento.com/browse/ENGCOM-7629) has been created to process this Pull Request

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
> The failing functional test doesn't seem related to this PR; furthermore, I don't understand the code mess checker that complains about too many dependencies which I don't see in the constructor. Thus I approve.

Code mess checker was fallen due to the number of classes in `use`. So I suppress this warning.
Please approve it.

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-7629](https://jira.corp.magento.com/browse/ENGCOM-7629) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
:x: **Before:**
#28549MAin

:heavy_check_mark: **After:**
#28549PR

**Pull request merged**
