### PR TITLE
Product CSV import error report file missing

### LINKED ISSUE #28420: Product CSV import error report file missing
### Preconditions (*)
1. Magento 2.3.5-p1
2.

### Steps to reproduce (*)
1. Import a product CSV which will generate errors like a not existing path to an image. 
2. 

### Expected result (*)
1. An error_report.csv file with the errors generated in the import.
2.

### Actual result (*)
1. No file..... the file is generated, but will be removed after the application ends.
2.

The following causes this problem, see my comment in the destructor.
https://github.com/magento/magento2/commit/bc06501851838ca9a07a3fc437b778c46366b4e9?diff=split#r39524421

### Additional information
- detailed steps during confirmation on 2.4-develop https://github.com/magento/magento2/issues/28420#issuecomment-635893447
- https://github.com/magento/magento2/issues/28420#issuecomment-635900690
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by engcom-Charlie**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#28420

### Manual testing scenarios (*)

See #28420

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by eduard13 — APPROVED** [review]
Thank you for the fix ✔️

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-7616](https://jira.corp.magento.com/browse/ENGCOM-7616) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

Import a product CSV which will generate errors like a not existing path to an image

**Before:** :heavy_multiplication_x: file is generated, but will be removed after the application ends.

Peek 2020-06-04 10-05

**After:** :heavy_check_mark: An error_report.csv file with the errors generated in the import.

Peek 2020-06-04 10-34

**Comment by Parakoopa** [comment]
Hi, any chance you could also provide this for 2.3?

**Comment by RaphaelBronsveld** [comment]
```
diff --git a/Model/Export/Adapter/Csv.php b/Model/Export/Adapter/Csv.php
index 580695d0..085d24ca 100644
--- a/Model/Export/Adapter/Csv.php
+++ b/Model/Export/Adapter/Csv.php
@@ -55,6 +55,19 @@ class Csv extends AbstractAdapter
     {
         if (is_object($this->_fileHandler)) {
             $this->_fileHandler->close();
+            $this->resolveDestination();
+        }
+    }
+
+    /**
+     * Remove temporary destination
+     *
+     * @return void
+     */
+    private function resolveDestination(): void
+    {
+        // only temporary file located directly in var folder
+        if (strpos($this->_destination, '/') === false) {
             $this->_directoryHandle->delete($this->_destination);
         }
     }

```

Patch above works fine for us at version 2.3.5-p1.

**Pull request merged**
