### PR TITLE
[MFTF] created ActionGroup to go to AdminSystemStorePage

### PR DESCRIPTION
**Pull request by Usik2203**
Following Best practices of MFTF this PR creates new  `AdminSystemStoreOpenPageActionGroup`  for navigation to system store page

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by rogyar** [comment]
@Usik2203 could you check the failing test for B2B and EE, please? It does look like something is wrong on the tests build phase.

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Review by lbajsarowicz — APPROVED** [review]
:heavy_check_mark: Good idea to introduce that.
(Sorry @rogyar I haven't noticed that you are already assigned to this PR)

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7843](https://jira.corp.magento.com/browse/ENGCOM-7843) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by Usik2203** [comment]
@rogyar  Seems it was temporary issue with B2B and EE failed tests. Now everything is ok.
Thanks!

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7843](https://jira.corp.magento.com/browse/ENGCOM-7843) has been created to process this Pull Request
:eight_spoked_asterisk: @rogyar, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Pull request merged**
