### PR TITLE
Category\Collection::joinUrlRewrite should use the store set on the collection

### PR DESCRIPTION
**Pull request by alepane21**
The problem is that Magento\Catalog\Model\ResourceModel\Category\Collection::joinUrlRewrite always use the store id from the store manager. I think that it should instead use the storeId set on the actual collection.

### Description

Now joinUrlRewrite uses directly the storeManager, but if a store is set directly on the collection, it should use the store set, and not the default passed by the store manager.
The method getStoreId(), if not set, already goes on fallback to the store manager and get the default, so it should be safe to directly use getStoreId().

### Fixed Issues (if relevant)

1. magento/magento2#13704: Category\Collection::joinUrlRewrite should use the store set on the collection

### Manual testing scenarios

I already provided an automated unit test. There is an code example in the related issue magento/magento2#13704.
It's my first automated test here, so I hope it's ok :)

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=13716) <br/>All committers have signed the CLA.

**Comment by dmanners** [comment]
Hi @alepane21 thanks for this pull request. I will have a look at processing it now.

**Comment by magento-engcom-team** [comment]
@alepane21 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by dmanners** [comment]
Hi @alepane21 thank you for this PR. Would you be able to also add in an integration test to cover this change also?

For an example I would suggest looking at `app/code/Magento/Catalog/Model/ResourceModel/Category/Collection.php::testJoinTable`

**Comment by alepane21** [comment]
Well, if you need it I think I can do it. But you'll have to wait this weekend.

**Comment by alepane21** [comment]
Hi @dmanners, done. There is an error in codacy but I think it's unrelated.

**Comment by dmanners** [comment]
Thank you @alepane21 for your hard work. I will take another look over this.

**Review by dmanners — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmanners, thank you for the review.
[MAGETWO-88107](https://jira.corp.magento.com/browse/MAGETWO-88107) has been created to process this Pull Request

**Pull request merged**
