### PR TITLE
Add webapi route to delete bulk by bulkUuid

### PR DESCRIPTION
**Pull request by anvasiliev**
### Description (*)
In current implementation bulk tables magento_bulk and magento_operation cleaned once per month and it can be changed to other, e.g. once per week or day. But in case of big data processing via bulk, mysql bulk tables can use all disk space. Route to remove bulk will allow for client to remove bulk when it's needed, example when bulk was processed by magento consumers and cleanup not needed data from magento_bulk and magento_operation tables so it will save space used by mysql.
 
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sidolov** [comment]
@magento run Static Tests,WebAPI Tests

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@anvasiliev looks like the changes caused failures related to the token generation, could you please take a look? Thanks!

**Comment by anvasiliev** [comment]
@magento run all tests

**Comment by anvasiliev** [comment]
@magento run all tests

**Comment by nuzil** [comment]
@magento run all tests

**Comment by nuzil** [comment]
@magento run all tests

**Comment by nuzil** [comment]
@magento run all tests

**Comment by nuzil** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
Hi @anvasiliev 

Unfortunately we are unable to accept Pull requests to any branches or releases other than current `2.4-develop` therefore I have to close this PR now.

Please feel free to reopen same PR into current branch if you think that issue persists.

Thanks.

**Pull request closed without merging**
