### PR TITLE
Fix dependency security issues

### PR DESCRIPTION
**Pull request by shanethehat**
As described in https://github.com/magento/magento2/issues/1669, the monolog and zend-http package versions currently in use contain security vulnerabilities. This PR bumps their versions to the minimum acceptable version, and additionally uses a pessimistic operator to ensure patch version increases can be pulled in without editing the composer.json file.

### CODE REVIEW

**Comment by joanhe** [comment]
Thanks for the contribution! internal ticket MAGETWO-41576 is created for processing this pull request.

**Comment by kassner** [comment]
We could use [this package](https://github.com/Roave/SecurityAdvisories), it prevents packages with known security vulnerabilities and is well maintained.

**Comment by shanethehat** [comment]
@kassner I've added the Roave security package, then I ran an uncommitted `composer update` which showed no further issues.

**Comment by joanhe** [comment]
@shanethehat I cannot accept commit 6aa84f because package Roave security is not a release version, the minimum-stability requirement is alpha in Magento 2. I will accept your last couple commits. Thanks for your contribution.

**Comment by shanethehat** [comment]
@joanhe I'll rebase the PR for you...

**Comment by kassner** [comment]
@joanhe `roave/security-advisories` does not have any version on purpose, so every time it's checked again. I saw a link stating this somewhere, let me find it.

**Comment by shanethehat** [comment]
@joanhe I've rebased with all three commits intact to resolve the merge conflict. The comment @kassner is referring to is https://github.com/Roave/SecurityAdvisories#stability. If you don't want to have a package that updates constantly as a core dependency is could maybe be moved to the `require-dev` section, otherwise I'll happily rebase that commit away.

**Comment by Ocramius** [comment]
As mentioned by @kassner, there is no such thing as versioning security constraints :-)

**Comment by piotrekkaminski** [comment]
We internally run scans using https://security.sensiolabs.org/ as part of our CICD process and report issues to bump up the versions.  I would rather not add additional dependency on the Roave repository. The sensiolabs scan seems to be using same security information as Roave.

**Comment by shanethehat** [comment]
@piotrekkaminski I've removed the Roave commit

**Comment by magento-cicd** [comment]
We have automated a Magento Contributor License Agreement verifier for contributions sent to our GitHub projects.
Please see the CLA agreement in the Pull Request comments.

**Comment by Ocramius** [comment]
I still disagree with relying on the internal CICD for this: users downloading magento and running `composer update` on their own (after having customized the software, for whatever reason) will have security issues on their own.

**Comment by piotrekkaminski** [comment]
@Ocramius i understand your concern. However Magento is tested only with specific versions of components. So assuming we add checks on every update with this repository, what if you find an issue with specific component? will you update your local version, potentially breaking your installation (it is not theoretical, for example Zend Framework security updates were breaking Magento before)? Or better to wait for Magento to provide updated version, tested against the updated library. 

You can do such checks on your own but this is not something we can recommend to all our users. I'm open to other points of view here as well.

**Comment by alankent** [comment]
As further expansion on what Piotr is saying, we want known stable versions of code. We want repeatability. It is not acceptable general or security practice that if I run `composer update` then run it again 5 minutes later I cannot set up my system to ensure I always get the same result. This would make penetration testing or other such security auditing unreliable. For example, what if a new change was introduced with a bug (or change in behavior that we depended on). It would instantly break any site that tried to rebuild. Having stable repeatable builds is crucial - not having release numbers of code prohibits this. The better approach is to release new versions frequently following semantic versioning policies. That way you can release new things without breaking applications using your library. That is what semantic versioning is for.

Thanks for the feedback and contributions though!

**Comment by shanethehat** [comment]
Based on Alan's comment, this PR need rework. It currently uses the pessimistic operator, but if your goal is repeatability then it needs to stick to definitive versions. I'll remove that operator and rebase to resolve the conflicts soon.

**Comment by shanethehat** [comment]
Hmm... actually all this is already in develop now, so this PR is rather pointless!

**Pull request closed without merging**
