### PR TITLE
Mark Factories classes as  API

### PR DESCRIPTION
**Pull request by vlmed**
### Description (*)
The following factories marked as AP:

1. app/code/Magento/Catalog/Block/Product/ImageFactory.php
2. app/code/Magento/Catalog/Model/Product/Type/Price/Factory.php
3. app/code/Magento/Config/Block/System/Config/Form/Field/Factory.php
4. app/code/Magento/Config/Block/System/Config/Form/Fieldset/Factory.php
5. app/code/Magento/Customer/Model/Metadata/FormFactory.php
6. app/code/Magento/ImportExport/Model/Export/Factory.php
7. app/code/Magento/Quote/Model/Quote/Address/RateCollectorInterfaceFactory.php
8. app/code/Magento/Quote/Model/Quote/Address/TotalFactory.php
9. app/code/Magento/Sales/Model/Order/CreditmemoFactory.php
10. app/code/Magento/Sales/Model/ResourceModel/Order/Collection/Factory.php
11. app/code/Magento/Ui/Component/Form/Fieldset/Factory.php
12. lib/internal/Magento/Framework/Acl/AclResourceFactory.php
13. lib/internal/Magento/Framework/AclFactory.php
14. lib/internal/Magento/Framework/Amqp/ConfigFactory.php
15. lib/internal/Magento/Framework/Api/ExtensionAttribute/JoinDataInterfaceFactory.php
16. lib/internal/Magento/Framework/Api/Search/DocumentFactory.php
17. lib/internal/Magento/Framework/Api/Search/SearchCriteriaFactory.php
18. lib/internal/Magento/Framework/App/Config/ValueFactory.php
19. lib/internal/Magento/Framework/Config/Data/ConfigDataFactory.php
20. lib/internal/Magento/Framework/Config/ViewFactory.php
21. lib/internal/Magento/Framework/Controller/Result/JsonFactory.php
22. lib/internal/Magento/Framework/DB/Adapter/Pdo/MysqlFactory.php
23. lib/internal/Magento/Framework/DB/Ddl/TriggerFactory.php
24. lib/internal/Magento/Framework/Data/FormFactory.php
25. lib/internal/Magento/Framework/Data/Tree/NodeFactory.php
26. lib/internal/Magento/Framework/Data/TreeFactory.php
27. lib/internal/Magento/Framework/DataObject/Factory.php
28. lib/internal/Magento/Framework/Event/ObserverFactory.php
29. lib/internal/Magento/Framework/EventFactory.php
30. lib/internal/Magento/Framework/File/UploaderFactory.php
31. lib/internal/Magento/Framework/Filesystem/Directory/ReadFactory.php
32. lib/internal/Magento/Framework/Mail/TransportInterfaceFactory.php
33. lib/internal/Magento/Framework/Message/CollectionFactory.php
34. lib/internal/Magento/Framework/Module/Setup/MigrationFactory.php
35. lib/internal/Magento/Framework/Setup/Declaration/Schema/Diff/DiffFactory.php
36. lib/internal/Magento/Framework/ValidatorFactory.php
37. lib/internal/Magento/Framework/View/Asset/File/FallbackContextFactory.php
38. lib/internal/Magento/Framework/View/Asset/FileFactory.php
39. lib/internal/Magento/Framework/View/Layout/Generator/ContextFactory.php
40. lib/internal/Magento/Framework/View/Layout/Reader/ContextFactory.php
41. lib/internal/Magento/Framework/View/Page/ConfigFactory.php

**Marked as API to fix static test**
42. lib/internal/Magento/Framework/Api/ExtensionAttribute/JoinData.php
43. lib/internal/Magento/Framework/DB/LoggerInterface.php

### Dependent Pull Requests
https://github.com/magento/magento2/pull/32156

### Fixed Issues (if relevant)
1. Fixes magento/magento2#32041

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by coderimus — CHANGES_REQUESTED** [review]
@vlmed thank you for the adjustments. There is one point explained to me: the @since will be set automatically during the merge. So, please, remove it :)

**Comment by vlmed** [comment]
@coderimus  Thanks for the explanation. `@since` sections removed

**Review by coderimus — APPROVED** [review]
Thank you @vlmed for the adjustments. Approve 👍

**Comment by magento-engcom-team** [comment]
Hi @coderimus, thank you for the review.
[ENGCOM-8759](https://jira.corp.magento.com/browse/ENGCOM-8759) has been created to process this Pull Request

**Comment by vlmed** [comment]
@magento run Static Tests

**Comment by vlmed** [comment]
@magento run Static Tests

**Comment by vlmed** [comment]
Hi @sivaschenko. To fix static tests, I also need to mark it as Api `lib/internal/Magento/Framework/DB/LoggerInterface.php`.
But this interface is marked as API in  https://github.com/magento/magento2/pull/32156.
What to do in this case?

**Comment by mrtuvn** [comment]
I'm not sure but i got same case as your experiences. One maintainer tell me need to update PR related in description section

**Comment by vlmed** [comment]
@magento run Static Tests

**Comment by vlmed** [comment]
@magento run Static Tests

**Comment by vlmed** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
Closed in favour of https://github.com/magento/magento2/pull/32661

**Pull request closed without merging**
