### PR TITLE
[Backport]-issue-195196  Images in XML sitemap are always linked to base store in multistore on Schedule

### PR DESCRIPTION
**Pull request by Nazar65**
### Description (*)
Images in XML sitemap are always linked to base store in multistore on Schedule

### Fixed Issues (if relevant)
1. magento/magento2#19596: Images in XML sitemap are always linked to base store in multistore on Schedule
2. ...

### Manual testing scenarios (*)
Website URL 1: https://my_website.com
Website URL 2: https://my_website.co.uk

Got to Stores->Configuration->Catalog->XML Sitemap->General Settings:
2.Set to Enable, Start Time, Frequency Daily etc...
TIP: I've set to a few minutes before checking!

Website 1 should have images url referencing Website 1 domain = https://my_website.com

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Nazar65. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-4264](https://jira.corp.magento.com/browse/ENGCOM-4264) has been created to process this Pull Request

**Comment by Nazar65** [comment]
HI @sivaschenko after hour of debugging i'm found why this not proper work on 2.3-develop, so i decided, that we dont need to use Environment emulation we just need to add in https://github.com/magento/magento2/blob/a5330a77625445ebc4552eaf3e7c34d44b26d2b2/app/code/Magento/Sitemap/Model/ResourceModel/Catalog/Product.php#L390 this `$this->_storeManager->setCurrentStore($storeId);` 

In 2.2-develop "i was tested" and this issue does not exist because they use deprecated method `collectSitemapItems`https://github.com/magento/magento2/blob/13b0fe9236d855bb961d07efdb24b9429d44cf6d/app/code/Magento/Sitemap/Model/Sitemap.php#L271
wich have the same `$this->_storeManager->setCurrentStore($storeId);`  
and in 2.3-develop this method no uses any more, and we have new one wich forgot to set storeId when load a collection. Do we need to remove Enviroument emulation and add this missed line on 2.3-develop ?

**Comment by sivaschenko** [comment]
Hi @Nazar65 you are right, the issue was fixed on 2.2 in https://github.com/magento/magento2/commit/8e426fe9a0b4e5dcaba084224d0b0a98c82e5e07 Yes, I believe that approach is straight and clear and also looks better from the performance and point of view, it would be good to adjust the functionality on 2.3-develop accordingly!

Considering that the issue is fixed on 2.2-develop, I believe this backport can be closed.

**Comment by Nazar65** [comment]
@sivaschenko thanks,  i'm closing this PR.

**Pull request closed without merging**
