### PR TITLE
magento2/magento:Non UTF-8/Unicode characters #19935

### PR DESCRIPTION
**Pull request by XxXgeoXxX**
### Preconditions
Magento 2.3

### Fixed issues
1. magento/magento2#19935

### Steps to reproduce
Check file;
magento2/app/code/Magento/Tinymce3/view/base/web/tiny_mce/plugins/spellchecker/editor_plugin_src.js

Line 170 in f4c1d75

 var re = '', i, str = this.editor.getParam('spellchecker_word_separator_chars', '\\s!"#$%&()*+,-./:;<=>?@[\]^_{|}����������������\u201d\u201c'); 
### Expected result
UTF-8/unicode characters
### Actual result
var re = '', i, str = this.editor.getParam('spellchecker_word_separator_chars', '\\s!"#$%&()*+,-./:;<=>?@[\]^_{|}����������������\u201d\u201c');

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rodrigowebjump** [comment]
Hi @XxXgeoXxX  thank you for your PR,
The issue was closed.
Since this is not a Magento issue (the original file of TinyMCE has the invalid char), we can't fix the file only in Magento core.

Please update/reopen the issue.

**Comment by XxXgeoXxX** [comment]
@rodrigowebjump
I asked ua-community. And got proposition add this PR and create another for update Tinymce3

**Comment by sivaschenko** [comment]
@XxXgeoXxX sorry for the confusion, I didn't realize the change is in tinymce code. I completely agree with @rodrigowebjump comment https://github.com/magento/magento2/pull/19937#issuecomment-462699336

**Pull request closed without merging**
