### PR TITLE
Fixed #27874 Vat Validation URL for EU Vat numbers changed.

### LINKED ISSUE #27874: Vat Validation URL for EU Vat numbers changed. (Vies Service)
An Vat Validation is not possible anymore because in the file:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/Model/Vat.php

On line 47 the is the following code available
` const VAT_VALIDATION_WSDL_URL = 'http://ec.europa.eu/taxation_customs/vies/services/checkVatService?wsdl';`

This url is not working anymore and should be changed to the new one to get it working again:
[http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl]

New Code
' const VAT_VALIDATION_WSDL_URL = 'http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl';

**Preconditions (*)**

Steps to reproduce (*)

**Expected result (*)**

    [Screenshots, logs or description]

**Actual result (*)**

    [Screenshots, logs or description]

### PR DESCRIPTION
**Pull request by shikhamis11**
Fixed #27874 Vat Validation URL for EU Vat numbers changed.

An Vat Validation is not possible anymore because in the file:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/Model/Vat.php

On line 47 the is the following code available
const VAT_VALIDATION_WSDL_URL = 'http://ec.europa.eu/taxation_customs/vies/services/checkVatService?wsdl';

This url is not working anymore and should be changed to the new one to get it working again:
[http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl]

New Code
' const VAT_VALIDATION_WSDL_URL = 'http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl';

For Testing purpose you can check 
**VAT Number : AT U38420507**
https://ec.europa.eu/taxation_customs/vies/viesquer.do?selectedLanguage=PL&ms=AT&iso=AT&vat=U38420507&name=&companyType=&street1=&postcode=&city=&requesterMs=&requesterIso=&requesterVat=

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lbajsarowicz — APPROVED** [review]
Thank you. Very important change.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7458](https://jira.corp.magento.com/browse/ENGCOM-7458) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**
1. Go to Admin -> Stores -> Configuration;
2. Enter the value (**AT U38420507** for example) in the **VAT Number** input field;

**Before:** 
:heavy_multiplication_x: Error during VAT Number verification.
Screenshot from 2020-04-21 15-27-49
Screenshot from 2020-04-21 15-30-11
Screenshot from 2020-04-21 15-31-23


**After:** :heavy_check_mark: VAT Number is valid.
Screenshot from 2020-04-21 15-51-23

**Comment by mowny** [comment]
This is also needed for previous magento2 versions, not only 2.4.

The EU server even has a redirect for the old url, but they botched it and redirect to a server name that is not in public DNS: http://taxudp92.cc.cec.eu.int:7174/taxation_customs/vies/checkVatService.wsdl
So another way to solve this issue would be to poke the EU server's admin to fix the redirect.
But they might have done this on purpose since the new url has been around for a while.

**Comment by hostep** [comment]
Yeah, this might warrant an official hotfix from Magento which can be applied to all Magento 2.0, 2.1, 2.2, 2.3 shops (believe me there are still 2.0 & 2.1 shops around which are also running into this issue)

**Comment by drinkingsouls** [comment]
In Magento 2.4.4 I see this fix is included, yet we still cannot validate VAT.
"Error during VAT Number verification." persists.

**Comment by engcom-Alfa** [comment]
hi @drinkingsouls 
Thanks for identifying incomplete fix and pointing out the issue.
Can you please help us with your issue description, exact reproducible steps, pre-conditions if there is any, also error screenshots or screen recordings.
Request you to, please report as a new PR/ Issue if possible.
Thanks in advance!

**Pull request merged**
