### PR TITLE
'view-details-label-issue' :: On order sumary view details label misa…

### PR DESCRIPTION
**Pull request by nainesh2jcommerce**
…lign on tablet

### Fixed Issues (if relevant)

1. magento/magento2#20463: On order sumary view details label misalign on tablet 
2. ...

### Manual testing scenarios (*)

1. Add configurable product to cart
2. and check view details label on order summary

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by Karlasa — COMMENTED** [review]
IMO: I would keep @indent__xs; for after element as it's easier to change variable value from 5 to 4px in child themes. 

For .toggle padding I would go wild and fix .abs-toggling-title padding at first (as it should not be that big anywhere) and then look if I could only change padding that is needed to change not all 4 of them ;)

**Comment by Karlasa** [comment]
@priti2jcommerce 
Thanks for adding me as review ;) 
It was just my opinion about it.

Cheers,

**Comment by priti2jcommerce** [comment]
Hi @Karlasa ,

there is not the default variable for 4px, this changes fine  for me.
Thanks!!

**Review by priti2jcommerce — APPROVED** [review]

**Comment by Karlasa** [comment]
@priti2jcommerce 
There isn't but why should it be 4px? 
Design guide suggests to use indents and the smallest is 5px so it should be like that :) As it could be easier to change for child themes where smallest can even be 10px if someone want and then it will be changed with variable in everywhere.

**Comment by nainesh2jcommerce** [comment]
Hi @magento-engcom-team,
Any news on this PR? thanks!

**Comment by nainesh2jcommerce** [comment]
Hi @Karlasa,

I have made it to 4px, because with 5px toggle arrow went to next line of label which looks mess. With 4px its appearing in same line and looking proper.

Thanks!

**Comment by nainesh2jcommerce** [comment]
Hi @magento-engcom-team, please review.

**Comment by nainesh2jcommerce** [comment]
Hi @magento-engcom-team please review this PR

**Comment by nainesh2jcommerce** [comment]
Hi @magento-engcom-team please review this PR

**Comment by nainesh2jcommerce** [comment]
Hi @magento-engcom-team please review this PR

**Comment by nainesh2jcommerce** [comment]
@magento-engcom-team any news on this PR?

**Comment by nainesh2jcommerce** [comment]
Hi @dmytro-ch, can you please review this PR.

**Comment by dmytro-ch** [comment]
Hi @nainesh2jcommerce @priti2jcommerce.
I totally agree that we must keep using variables.
There's something wrong in our solution if we use some specific value instead of predefined theme variables. Please check the recommendation from @Karlasa:

> Design guide suggests to use indents and the smallest is 5px so it should be like that :) As it could be easier to change for child themes where smallest can even be 10px if someone want and then it will be changed with variable in everywhere.

This is not a solution:

> I have made it to 4px, because with 5px toggle arrow went to next line of label which looks mess. With 4px its appearing in same line and looking proper.

Also, this PR does not look as a bugfix for me, considering such "fixes" are tuned only per specific case. What happens if the "View Details" title changes to a longer text for other languages (at least for one letter)?

The minicart block still looks flattened on tablet view:
screen shot 2019-02-11 at 8 54 01 pm

I would recommend changing the approach of how the content is rendered on the tablet view by applying a universal solution.

Thank you!

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Please check my latest comment.

**Comment by dmytro-ch** [comment]
Closing this PR now due to inactivity.
Feel free to reopen and update if you wish to continue.
Thank you!

**Pull request closed without merging**
