### PR TITLE
Issue 36274: Duplicate orders with 2 parallel GraphQL requests

### LINKED ISSUE #36274: Duplicate orders with 2 parallel GraphQL requests
#### Precondition
As a Guest user follow steps by GraphQL checkout tutorial to step 10 Place order https://devdocs.magento.com/guides/v2.4/graphql/tutorials/checkout/index.html

#### Steps
Execute Place the order mutation in parallel in 2 browsers (I did it in Postman) . 
```
mutation {
  placeOrder(input: {cart*id: "{ CART*ID }"}) {
    order {
      order_number
    }
  }
}
```

#### (x) Actual result
2 orders created

#### (/) Expected result
1 order created

### PR DESCRIPTION
**Pull request by rogerdz**
### Description (*)

Lock cart in 60s before place order

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36274

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
We have absolutely the same issue using default checkout (through REST API) https://github.com/magento/magento2/pull/35139, so I think we should think about fixing both cases.

**Comment by rogerdz** [comment]
I updated fix duplicate order for default checkout through REST API
Result:

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@ihor-sviziev I added unit test

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run Unit Tests, Integration Tests, Functional Tests EE, Functional Tests B2B, Static Tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests look not related to changes from this PR.

**Comment by engcom-Lima** [comment]
@magento run Integration Tests ,Static Tests,Unit Tests

**Comment by engcom-Lima** [comment]
Hi @rogerdz ,

Thanks for your contribution and collaboration.

I would like to inform you that we are closing this PR as internal team is working on it and it is fixed as per the[ jira ticket ](https://jira.corp.adobe.com/browse/ACP2E-1194) comment.


Thanks

**Comment by jonathanribas** [comment]
Hi @ihor-sviziev, do you have news regarding this issue?

We are still experiencing it on 2.4.5-p1 :(

It's creating a bad user experience, refunds processed manually by ouf customer service, customers frustration... Lot of manual work for several collaborators.

Thanks for your help.

**Comment by ihor-sviziev** [comment]
@jonathanribas, as is written above, the internal team has fixed the issue, but the changes weren't included in any release yet. You can find related commits here https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-1194&type=commits

**Comment by jonathanribas** [comment]
@ihor-sviziev, no chance to have a Quality Patch for this topic? It's very common to happen in headless integrations...

**Comment by ihor-sviziev** [comment]
@jonathanribas, sorry, I don't really know. Usually, I'm applying fixes as a custom patch using https://github.com/vaimo/composer-patches 
Maybe @sidolov can help with it?

**Pull request closed without merging**
