### PR TITLE
[Forwardport] Validate that the PO Number is set on the payment instance.

### PR DESCRIPTION
**Pull request by mage2pratik**
### Original Pull Request 
 https://github.com/magento/magento2/pull/14393

### Description
Validate that the `po_number` is set on the info instance.

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/6585

### Manual testing scenarios

1. Available on the issue description.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sidolov** [comment]
Please, add changes from commit: `1d833da2d152bfbc1d1cac27fae00ea1529bc9ea` to this port. Mentioned commit fixes functional tests.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-2954](https://jira.corp.magento.com/browse/ENGCOM-2954) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Pull request merged**
