### PR TITLE
Added 'target' attribute to the allowed attributes array for link block

### PR DESCRIPTION
**Pull request by facundocapua**
Added the 'target' property to the $allowedAttributes array, so it can be changed from the layout, like the following example:

``` xml
 <block class="Magento\Framework\View\Element\Html\Link" name="a-blank-page-link">
    <arguments>
        <argument name="path" xsi:type="string">a-blank-page.html</argument>
        <argument name="target" xsi:type="string">_blank</argument>
        <argument name="label" xsi:type="string" translate="true">A blank page</argument>
    </arguments>
</block>
```

### CODE REVIEW

**Comment by magento-cicd** [comment]
We have automated a Magento Contributor License Agreement verifier for contributions sent to our GitHub projects.
Please see the CLA agreement in the Pull Request comments below.

**Comment by KrystynaKabannyk** [comment]
Hello @fcapua-summa, can you please update the code and cover it by Travis tests?

**Comment by facundocapua** [comment]
It seems that they are still failing, should I try restarting it again?

**Comment by vkorotun** [comment]
Internal ticket: MAGETWO-58372

**Pull request merged**
