### PR TITLE
Replace repetitive actions with Action Groups in AdminDeleteCatalogPriceRuleTest

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
 The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run the test in the local environment and verified that it run successfully

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B, @magento run Functional Tests CE

**Comment by dmytro-ch** [comment]
@magento run Functional Tests CE

**Comment by dmytro-ch** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Comment by dmytro-ch** [comment]
@magento run Functional Tests CE

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-8915](https://jira.corp.magento.com/browse/ENGCOM-8915) has been created to process this Pull Request

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by dmytro-ch** [comment]
@magento run Adobe CLA Signed?

**Comment by dmytro-ch** [comment]
@magento run Adobe CLA Signed

**Comment by dmytro-ch** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B , WebAPI Tests

**Comment by dmytro-ch** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run all tests

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-8915](https://jira.corp.magento.com/browse/ENGCOM-8915) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
Hi @kate-kyzyma, Thanks for your contribution.Please resolve the conflicts to move ahead on this PR

**Comment by engcom-Dash** [comment]
Closing this PR since it has not been updated for a long time. Please feel free to reopen it if needed.

**Pull request closed without merging**
