### PR TITLE
Made Topmenu HTML Editable

### PR DESCRIPTION
**Pull request by sprankhub**

### CODE REVIEW

**Comment by vigentocommerce** [comment]
image

**Comment by vpelipenko** [comment]
@sprankhub, could you specify in the description what kind of issue are you trying to resolve? It will help us to understand the fix and its valuable.

**Comment by alankent** [comment]
I assume its so event hook can replace the HTML (by updating the transport object). Otherwise the events can see the HTML, but not replace it.

**Comment by sprankhub** [comment]
Exactly @alankent. This is a pattern used in other places in Magento in order to allow the observer to update something (the HTML output of the topmenu in this case). IMHO, the current implementation does not really make sense, because it says "hey, I give you an event with which you can have a look at the HTML, but you cannot do anything with it". This has also been discussed in [this Magento SE thread](https://magento.stackexchange.com/questions/634/how-can-i-alter-a-string-passed-by-an-event).

**Comment by vpelipenko** [comment]
CR: passed
Builds: green
Resolution: OK to merge
Ticket: MAGETWO-32828

**Pull request merged**
