### PR TITLE
add product to product save event

### PR DESCRIPTION
**Pull request by danslo**
Seems useful to pass the product object when dispatching a product save event.

### CODE REVIEW

**Comment by magento-cicd** [comment]
We have automated a Magento Contributor License Agreement verifier for contributions sent to our GitHub projects.
Please see the CLA agreement in the Pull Request comments.

**Comment by daim2k5** [comment]
Hi @danslo please accept the CLA also you broke a test. Maybe you have time to fix your PR?

**Comment by danslo** [comment]
Signed the CLA. Test seem unrelated to my PR? Can we kick them off again somehow?

**Comment by daim2k5** [comment]
@danslo maybe you can rebase? and we start the test again?

**Comment by danslo** [comment]
Done. All lights appear to be green.

**Comment by daim2k5** [comment]
@danslo Thanks

**Comment by danslo** [comment]
Don't want to be impatient, but this is a 1 line change that has been open for nearly 4 months now... :)

**Comment by yaronish** [comment]
@danslo Thank you for your contribution. This Pull Request will be merged soon in the scope of `MAGETWO-47772`

**Pull request merged**
