### PR TITLE
 Passed value has correct type 

### LINKED ISSUE #35652: [Issue]  Passed value has correct type
This issue is automatically created based on existing pull request: magento/magento2#35352:  Passed value has correct type 

---------

### Description (*)

This PR fix wrong type for value which was passed to `setReloadAclFlag`  https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/User/Model/User.php#L28

int value should be passed

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fix wrong type for value which was passed to `setReloadAclFlag`  https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/User/Model/User.php#L28

int value should be passed

### Resolved issues:
1. [x] resolves magento/magento2#35652:  Passed value has correct type

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests B2B

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests B2B

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests B2B

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by Usik2203** [comment]
Hello @engcom-Alfa @engcom-Lima  
Unfortunately i don't have scenario for reproducing error. 
My changes was do based on code analyze.

Thank you !

**Pull request merged**
