### PR TITLE
Move test file to correct location

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)

In https://github.com/magento/magento2/commit/49cc6126973cc21cc179e1483616d684be37a50c was added API test that was placed to the wrong directory: dev/tests/Magento/GraphQl... instead of dev/tests/**api-functional/testsuite**/Magento/GraphQl....

Because of wrong file location, this test won't be executed

This Pull Request moves this task to correct folder.
/CC @svera @bl4de

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@svera please look on the test failures, looks like delivered changes doesn't work as expected

**Comment by bl4de** [comment]
Hi @ihor-sviziev, thank you for the heads up, we're looking into this.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Charlie** [comment]
Hi @ihor-sviziev,

Thank you for you input and contribution!

As discussed and confirmed with @bl4de, the mentioned file was created and committed into the wrong directory. Now it got moved and renamed to the correct location (and renamed).  dev/tests/api-functional/testsuite/Magento/GraphQl/GraphQl/DisableSessionSetCookieTest.php is the new file.

As the issue is resolved and the fix is available on the Magento 2.4 develop hence closing this PR now. Please feel free to reopen for any other updates.

Thank you!

**Pull request closed without merging**
