### PR TITLE
Resolve Refresh Statistics: Updated At = Null should be display as "Never" instead of "undefined". issue25931

### LINKED ISSUE #25931: Refresh Statistics: Updated At = Null should be display as "Never" instead of "undefined".
Updated At if Null should be display as "Never" instead of "undefined".

Please see the index management:

image

**But:**

In refresh statistics:

image

### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Go to backend
2. Reports-> Refresh Statistics
3. Please see:

image

### Expected result (*)

image

### Actual result (*)

image

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#25931: Refresh Statistics: Updated At = Null should be display as "Never" instead of "undefined".

### Fixed Issues (if relevant)

1. magento/magento2#25931: Refresh Statistics: Updated At = Null should be display as "Never" instead of "undefined".

### Manual testing scenarios (*)

1. Go to backend
2. Reports-> Refresh Statistics

#### Expected result

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @edenduong
Unfortunately, we only accept Pull Requests to the following branches: 2.2-develop, 2.3-develop.
Please create a new Pull Request and use one of those as a target.

Thank you.

**Review by krzksz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-6427](https://jira.corp.magento.com/browse/ENGCOM-6427) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @edenduong   .
     Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.
Thanks!

**Comment by edenduong** [comment]
@krzksz  @engcom-Alfa : I have just covered it with Integration Test. Please check it.
Thank you very much!

**Review by krzksz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-6427](https://jira.corp.magento.com/browse/ENGCOM-6427) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

**Before:**
before

**After:**
after

**Pull request merged**
