### PR TITLE
MFTF: Refactoring AdminDeleteRootCategoryTest and AdminDeleteRootSubCategor…

### PR DESCRIPTION
**Pull request by kate-kyzyma**
…yTest

### Description (*)
AdminDeleteRootCategoryTest and AdminDeleteRootSubCategotyTest are refactored according to the best practices followed by MFTF.

### Fixed Issues (if relevant)
<!---
N/A

### Manual testing scenarios (*)
Run AdminDeleteRootCategoryTest and AdminDeleteRootSubCategotyTest in the local environment and verified the test runs successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Review by dmytro-ch — APPROVED** [review]

**Comment by dmytro-ch** [comment]
@magento run Functional Tests CE Functional Tests EE Functional Tests B2B

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7676](https://jira.corp.magento.com/browse/ENGCOM-7676) has been created to process this Pull Request

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by dmytro-ch** [comment]
@magento run Database Compare, Integration Tests, Magento Health Index, Sample Data Tests CE, Sample Data Tests EE, Sample Data Tests B2B, Static Tests, Unit Tests, WebAPI Tests

**Comment by dmytro-ch** [comment]
@magento run Semantic Version Checker

**Comment by engcom-Delta** [comment]
**Notice:** QA not applicable

**Pull request merged**
