### PR TITLE
Cannot pass a different date & time format for order created_at #13072

### PR DESCRIPTION
**Pull request by devamitbera**
#13072

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21391) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @devamitbera. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by devamitbera** [comment]
@magento-engcom-team give me test instance- deploy test instance based on PR changes
@magento-engcom-team give me 2.3-develop instance - deploy vanilla Magento instance

**Comment by magento-engcom-team** [comment]
Hi @devamitbera. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @devamitbera, here is your [new Magento instance](https://pr-21391.instances.magento-community.engineering).
Admin access: [https://pr-21391.instances.magento-community.engineering/admin](https://pr-21391.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by devamitbera** [comment]
@magento-engcom-team ,is mail server not working at test instance?

Is there any way to access  SSh of that server?

Note:Even,don't get customer new creation mail.

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-4364](https://jira.corp.magento.com/browse/ENGCOM-4364) has been created to process this Pull Request

**Comment by aleron75** [comment]
> Is there any way to access SSh of that server?

AFAIK it's not possible to access it just like it's not possible to run CLI commands.

Thanks for your contribution, don't forget you can easily port this PR (if needed) to other branches with the Porting Tool, [read more here](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#porting-tool). 

Cheers

**Comment by devamitbera** [comment]
@aleron75  & @magento-engcom-team  thanks for your help.

But I am trying to create the pull from porting.engcom.dev.magento.com for develop 2.2 branch .

But unable to do that getting below message
`Sorry, you can't create port for not merged pull request.`
Can you please guide me, how to create pull for also 2.2  version

**Comment by aleron75** [comment]
> `Sorry, you can't create port for not merged pull request.`

It is necessary to wait for this PR to be merged on 2.3 before it can be ported to another branch.

Cheers

**Comment by devamitbera** [comment]
@aleron75, thanks for your help.I am waiting for pull merge.

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @devamitbera thanks for the pull request. However, we cannot change the method signatures of api classes. I believe there are easy workarounds for getting the `created_at` time formatted correctly.

I have to close this pull request due to stated aboove. Please contact me in case you have any questions or comments.

**Comment by devamitbera** [comment]
@sivaschenko, Sorry I don't understand why this  PR is closed.Can you please explain.

If  adding an extract parameter to` public function getCreatedAtFormatted($dateFormat, $timeFormat = \IntlDateFormatter::MEDIUM)` ,Is the reason  of closing this PR  then i believe  that 

https://github.com/magento/magento2/issues/13072  should  be closed as  this issue main purpose is . `getCreatedAtFormatted() ` can support  different date & time format.

Another solution for this case, I can introduce an  method which can different date & time format for return of  created_at value..

Kindly put your valuable view on this issue

**Comment by sivaschenko** [comment]
@devamitbera I'm sorry I had to close this pull request, however, for backward compatibility puroses the public method signatures cannot be changed. See more details in [Backward Compatible Delvelopment Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

**Comment by devamitbera** [comment]
@sivaschenko  thanks for your reply. Can we discuss about this issue #13072 at slack channel?

**Comment by sivaschenko** [comment]
@devamitbera sure! Feel free to drop me a message on slack: @Sergii Ivashchenko

**Pull request closed without merging**
