### PR TITLE
[Forwardport] 17968 Fix Customer custom attributes lost after save

### PR DESCRIPTION
**Pull request by Thundar**
### Description

Up porting https://github.com/magento/magento2/pull/17968

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @Thundar. I'm putting this PR on hold. We need to wait until the original PR is merged. Thank you

**Comment by Thundar** [comment]
@rogyar Ok, thank you. I have a question: static test failed for other method descriptions. Am I supposed to fix them, or not (as it improves the chance of a later manual merge conflicts to be done)?

**Comment by Thundar** [comment]
A test failed on PHP docs that are not depending by this PR. To avoid conflicts, I submitted a different PR to fix them: https://github.com/magento/magento2/pull/18386

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3350](https://jira.corp.magento.com/browse/ENGCOM-3350) has been created to process this Pull Request

**Comment by sidolov** [comment]
Hi @Thundar , looks like we merged another port of original PR first: https://github.com/magento/magento2/pull/18571 but don't worry, you have already received points for ported PR made by the other contributor according to our rules. 
I'm sorry about that, we will try to avoid such situations in the future. 
Thank you for your contribution!

**Pull request closed without merging**
