### PR TITLE
Apply discount to price based on customer group

### PR DESCRIPTION
**Pull request by somat211**
### Description (*)

Apply discount to price based on customer group
### Fixed Issues (if relevant)

1. magento/magento2#10009: Cannot apply discount to price based on customer group

### Manual testing scenarios (*)

1. Set prices for a product for two customer group via tiered pricing
2. Create a catalog rule discount that applies to product
3. Apply rule and now everything working fine.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @somat211. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sidolov** [comment]
@somat211 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by josefbehr** [comment]
@sidolov why did you remove "needs update" label? According to @rguedes this does not yet fix the issue.

**Comment by sidolov** [comment]
Hi @josefbehr , PR was closed due to inactivity and reopened, so, I decided that we should review it once again. But I can't see any activity from contributor after reopen. 
@somat211 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
