### PR TITLE
Issue 36207: Validation messages are duplicated on customer registrat…

### LINKED ISSUE #36201: Mage error component is duplicating error warnings on form inputs
### Preconditions and environment

- Magento 2.4.5
- The error can be reproduced in any form (ex: login form)

### Steps to reproduce

1. Submit blank login form;
2. Fill the email input and submit again;
3. Remove the email and submit blank form again;
4. Click one more time on submit button.

### Expected result

There should only be one error warning.

### Actual result

Two error warnings appear.

image

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### LINKED ISSUE #36207: Validation messages are duplicated on customer registration form and other input forms
**Preconditions**
Install Magento 2.4 develop with sample data.

**Issue** 
On all the pages which has the form, validate message are duplicated.

**Steps To Reproduce**
1. Open Storefront.
2. Click "Create Account" link.
3. Fill in form data, leave the Last Name and Email field blank -> Click Submit button.
4. Fill in Last Name field -> Click submit button again.
5. Remove data on the Last Name field again, then click Submit button 2 times.

**Expected result**
Validation message should not be duplicated.

**Actual result**
Validation message is duplicated.

### PR DESCRIPTION
**Pull request by rogerdz**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#36207
2. Fixes magento/magento2#36201

### Manual testing scenarios (*)

1. ...
3. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run Unit Tests, Integration Tests

**Comment by rogerdz** [comment]
@magento run Unit Tests, Integration Tests

**Comment by rogerdz** [comment]
@magento run all tests

**Review by edenduong — CHANGES_REQUESTED** [review]
Thank you for your contribution. Could you please cover this change by Mftf test?

**Comment by rogerdz** [comment]
Hi @edenduong, thank you for your review. 
I added mftf test

**Comment by rogerdz** [comment]
@magento run all tests

**Review by edenduong — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
Install fresh Magento `2.4-develop`

**Manual testing scenario:**
**Issue 1:**
1. Submit blank login form;
2. Fill the email input and submit again;
3. Remove the email and submit blank form again;
4. Click one more time on submit button.

**Issue 2:**
1. Open Storefront.
2. Click "Create Account" link.
3. Fill in form data, leave the Last Name and Email field blank -> Click Submit button.
4. Fill in Last Name field -> Click submit button again.
6. Remove data on the Last Name field again, then click Submit button 2 times.

**Before:** :heavy_multiplication_x: Validation messages are duplicated.
Screenshot 2022-10-26 at 12 09 25 PM

Screenshot 2022-10-26 at 12 03 31 PM


**After:** :heavy_check_mark:  Now fine.
Screenshot 2022-10-26 at 1 03 47 PM

Screenshot 2022-10-26 at 2 43 12 PM


No additional manual test case is required part of regression as MFTF is covered.

**Pull request merged**
