### PR TITLE
Adding functionality to pre-select attributes by URL, selecting by the attribute text value 

### PR DESCRIPTION
**Pull request by Rus0**
### Description (*)
 Adding functionality to pre-select attributes by URL, selecting by the attribute text value:

https://release-dev-rxvv2iq-zddsyhrdimyra.us-4.magentosite.cloud/index.php/juno-sweater.html#fashion_color=20
https://release-dev-rxvv2iq-zddsyhrdimyra.us-4.magentosite.cloud/index.php/juno-sweater.html#fashion_color=Lilac
https://release-dev-rxvv2iq-zddsyhrdimyra.us-4.magentosite.cloud/index.php/juno-sweater.html#178=20
https://release-dev-rxvv2iq-zddsyhrdimyra.us-4.magentosite.cloud/index.php/juno-sweater.html#178=Lilac
### Manual testing scenarios (*)

1. Load configurable products with the attribute id and attribute value id
2. Load configurable products with the attribute id and attribute string value
3. Load configurable products with the attribute code and attribute value id
4. Load configurable products with the attribute code and attribute string value

### Contribution checklist (*)
 - [x ] Pull request has a meaningful description of its purpose
 - [x ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Rus0. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by Rus0** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Rus0. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Rus0, here is your [new Magento instance](https://pr-21607.instances.magento-community.engineering).
Admin access: [https://pr-21607.instances.magento-community.engineering/admin](https://pr-21607.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rogyar** [comment]
Hi @Rus0. Thank you for your collaboration. Could you provide more details about the business use-cases of this implementation, please?

**Comment by Rus0** [comment]
> Hi @Rus0. Thank you for your collaboration. Could you provide more details about the business use-cases of this implementation, please?

Hey @rogyar , the point is the capability of making a more seo-friendly url, instead of using the attribute option id, it will use the actual value, for example, ?color=1 can be used like: ?color=red

It will still work with color=1, so we can make sure old urls are still available.

Thanks for the review ;)

**Comment by rogyar** [comment]
Hi @Rus0 I see your point, thank you. But do we have an existing functionality that uses the new "SEO-friendly" approach? 
My point is the following. If we introduce an improvement into the existing flow, it should be complete. So, for example, we can introduce a new method's parameter if it's required within a scope of some flow. But if we introduce the new parameter "just in case", we make the system more and more complex, introducing new conditions, etc. 
I really like your solution but in this case, we should probably change other parts of the system to use the new approach (and keep in mind the backward compatibility).

**Comment by sidolov** [comment]
@Rus0 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
