### PR TITLE
Fix year format

### PR DESCRIPTION
**Pull request by likemusic**
There is no needs to have full year (4 digits) year on frontend always.
It fix issue when initial rendered date in input value-attribute with current locale format (in \Magento\Framework\Data\Form\Element\Date::getElementHtml) (in my case 'M/d/yy' becomes "10/30/18") but when it changed by calendar year format changed to 4-digit value ("11/30/2018").

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14547) <br/>All committers have signed the CLA.

**Comment by likemusic** [comment]
Seems that  _convertFormat() may not convert as expected formats with multiple repeated tokens like 'YYYYYYYY-DDDDDDDD'.

**Comment by magento-engcom-team** [comment]
@likemusic thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by likemusic** [comment]
Maybe it can help.
https://docs.google.com/spreadsheets/d/1YvhfmrgDPWd-8NQT_27DM4xI33yJdJ4KW45FTe5TfTg/edit?usp=sharing - date formats table for ICU, jQuery Datepicker Widget, MomentJs

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-1264](https://jira.corp.magento.com/browse/ENGCOM-1264) has been created to process this Pull Request

**Comment by VladimirZaets** [comment]
Hi @likemusic , thank you for collaboration, but currently, we can't accept your changes due to the backward compatibility reason. Your changes are right, but display format will be changed in all places where we use `calendar.js`. We should fix this problem in more complex way, without changing behavior for our customers.

**Comment by likemusic** [comment]
@VladimirZaets, why pull-request closed if changes are right?
Opened pull-request indicates about some exists issues. By default search in github аpplicable for opened issue. And most peoples when have troubles with magento search in opened issues and pull-requests.

I think it would be better to keep this pull-request (and possible many other) opened, or add some label to closed pull-request, that indicated that pull-request should be improved.

Some days ago I found closed pull-request witch fix real issue in magento. But it was closed just because it hadn't test coverage. It sad me. Because there is no way to distinguish really bad pull-requests and that fix existing bugs in magento, but not well-decorated, or not fix bug сomprehensively.

**Comment by ishakhsuvarov** [comment]
Hi @likemusic 
Unfortunately, even though the changes you provided may be correct from the functional standpoint, it can unexpectedly break stores already relying on current behavior. 

Pull Request was closed, as specific proposed solution violates requirements which defined for all Magento core codebase. We consider [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) and [guidelines](https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html) not as decoration but as a crucial part of all code accepted to the core.

We are going to look for possible ways around the backward compatibility issue and let you know how to update the Pull Request, if you wish.

Thank you for collaboration!

**Comment by VladimirZaets** [comment]
Hi @likemusic Currently, we can make the workaround, add the ability to configure map. This way gives the ability to use correct format and saved the current calendar behavior.

For that, in `_create` method we should merge `this.dateTimeFormat` with `this.options.dateTimeFormat`.

Will be great if you do that, thanks.

**Comment by likemusic** [comment]
@VladimirZaets I would be glad to do this, but I'm not sure that I will have time for this in the near future.

**Comment by VladimirZaets** [comment]
Hi @likemusic, Unfortunately, we will close this PR. According to [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) and [guidelines](https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html) we can't accept PR in current state. 
Please reopen current PR or create a new one when you will provide the workaround that was described

**Pull request closed without merging**
