### PR TITLE
Add Generic type annotation to ObjectManagerInterface to improve autocompletion

### PR DESCRIPTION
**Pull request by antonkril**
The PR adds generic type annotation to ObjectManagerInterface
Generic PHPDoc syntax is described here: https://phpstan.org/blog/generics-in-php-using-phpdocs

### Description (*)
Currently objectManager `get` and `create` method return types are `mixed`. So objects created with ObjectManagerInterface directly do not have autocompletion in editors. This PR fixes it.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @antonkril,
Your changes looks good.
Could you please sign Adobe CLA?

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @antonkril,

Thank you for your contribution!

As mentioned [here](https://github.com/magento/magento2/pull/37911#pullrequestreview-1597710779), can you please sign the CLA in order to proceed further on this PR.

Thank you!

**Comment by engcom-Charlie** [comment]
Hi @antonkril,

As the CLA is not signed yet as mentioned [here](https://github.com/magento/magento2/pull/37911#issuecomment-1746994354) prior , we are closing this PR for now.

Please feel free to reopen once you are ready to sign.

Thank you!

**Pull request closed without merging**
