### PR TITLE
Add Magento\ConfigurableProduct\Pricing\Price\PriceResolverInterface to di.xml in issue23717

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

No Preference for Magento\ConfigurableProduct\Pricing\Price\PriceResolverInterface in di.xml
Solution: Just add to di.xml

### Fixed Issues (if relevant)

1. magento/magento2#23717: dependency injection fails for \Magento\ConfigurableProduct\Pricing\Price\PriceResolverInterface

### Manual testing scenarios (*)

1. Create a new module and a class
2. Add in the constructor the \Magento\ConfigurableProduct\Pricing\Price\PriceResolverInterface
e.g.
```

   public function __construct(
        ProductRepositoryInterface $productRepository,
        CategoryRepositoryInterface $categoryRepository,
        LoggerInterface $logger,
        SearchCriteriaBuilderFactory $searchCriteriaBuilderFactory,
        CollectionFactory $collectionFactory,
        Product $productModel,
        Data $helper,
        \Magento\Framework\Filesystem\DirectoryList $directoryList,
        StoreManagerInterface $storeManager,
        \Magento\ConfigurableProduct\Model\Product\Type\Configurable $configurableType,
        State $state,
        PriceResolverInterface $configurableRegularPrice
    )
```
Result :The dependency is injected correctly 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5462](https://jira.corp.magento.com/browse/ENGCOM-5462) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by orlangur** [comment]
@edenduong @ihor-sviziev is it not used in core?

**Comment by edenduong** [comment]
Hi Orlangur,  @orlangur 

Currently, the interface isn't injected to any class. But I think it is better if we add it in the di.xml and other modules can use the interface instead of the model PriceResolver (following to the Service Contract https://devdocs.magento.com/guides/v2.3/extension-dev-guide/service-contracts/service-contracts.html)

**Comment by edenduong** [comment]
And if we use the class: Magento\ConfigurableProduct\Pricing\Price\ConfigurablePriceResolver to other module, it don't think it can run. Because no preference but now it call the function of the inferface:

```
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

namespace Magento\ConfigurableProduct\Pricing\Price;

use Magento\ConfigurableProduct\Model\Product\Type\Configurable;
use Magento\Framework\App\ObjectManager;
use Magento\Framework\Pricing\PriceCurrencyInterface;

class ConfigurablePriceResolver implements PriceResolverInterface
{
    /**
     * @var \Magento\ConfigurableProduct\Pricing\Price\PriceResolverInterface
     */
    protected $priceResolver;

    /**
     * @var PriceCurrencyInterface
     * @deprecated 100.1.1
     */
    protected $priceCurrency;

    /**
     * @var Configurable
     * @deprecated 100.1.1
     */
    protected $configurable;

    /**
     * @var LowestPriceOptionsProviderInterface
     */
    private $lowestPriceOptionsProvider;

    /**
     * @param PriceResolverInterface $priceResolver
     * @param Configurable $configurable
     * @param PriceCurrencyInterface $priceCurrency
     * @param LowestPriceOptionsProviderInterface $lowestPriceOptionsProvider
     */
    public function __construct(
        PriceResolverInterface $priceResolver,
        Configurable $configurable,
        PriceCurrencyInterface $priceCurrency,
        LowestPriceOptionsProviderInterface $lowestPriceOptionsProvider = null
    ) {
        $this->priceResolver = $priceResolver;
        $this->configurable = $configurable;
        $this->priceCurrency = $priceCurrency;
        $this->lowestPriceOptionsProvider = $lowestPriceOptionsProvider ?:
            ObjectManager::getInstance()->get(LowestPriceOptionsProviderInterface::class);
    }

    /**
     * @param \Magento\Framework\Pricing\SaleableInterface|\Magento\Catalog\Model\Product $product
     * @return float
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function resolvePrice(\Magento\Framework\Pricing\SaleableInterface $product)
    {
        $price = null;

        foreach ($this->lowestPriceOptionsProvider->getProducts($product) as $subProduct) {
            $productPrice = $this->priceResolver->resolvePrice($subProduct);
            $price = isset($price) ? min($price, $productPrice) : $productPrice;
        }

        return (float)$price;
    }
}
```

**Comment by orlangur** [comment]
@edenduong thanks, that's what I was thinking about - it was injected by a concrete implementation and not by interface :(

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
