### PR TITLE
Opengraph product price  amount has wrong value

### PR DESCRIPTION
**Pull request by vshatylo**
### Description (*)

In html markup meta 'product:price:amount' has wrong price
### Fixed Issues (if relevant)

1. magento/magento2#13957
2. ...

### Manual testing scenarios (*)

1. update config:
  - sales -> tax -> calculation settings -> catalog prices  set value 'excluding tax'
  - sales -> tax -> price display settings -> display product prices in catalog  set value 'including tax'
2. configure tax rule (e.g. 21%)
3. visit product view page 
4. compare price displayed on frontend with price amount in html meta tag 'product:price:amount'

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @vshatylo. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4059](https://jira.corp.magento.com/browse/ENGCOM-4059) has been created to process this Pull Request

**Comment by milindsingh** [comment]
Duplicate https://github.com/magento/magento2/pull/20011

**Comment by tdgroot** [comment]
@vshatylo this fixes one part on the front-end, but I question if this is the right solution for the problem that I stated in issue #13957: product model prices are excluding tax when Magento is configured to enter prices excluding tag, but show them including tax on the frontend.

**Comment by vshatylo** [comment]
@tdgroot getFinalPrice method in Product model left from old Magento version for compatibility. 
New approach is to use pricing models for getting specific one e.g. final price, tier price

**Comment by irajneeshgupta** [comment]
@vshatylo I think a PR is already created for this issue fix. https://github.com/magento/magento2/pull/20011
This would be the correct fix.
`$block->getProduct()->getPriceInfo()->getPrice(\Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE)->getAmount()`

**Comment by sidolov** [comment]
Hi @vshatylo fix for such issue already provided in PR: https://github.com/magento/magento2/pull/20011
I'm closing this PR as duplicate. 
Thank you for the collaboration!

**Pull request closed without merging**
