### PR TITLE
Use current sore id for category runtime cache

### LINKED ISSUE #39310: [Issue] Use current sore id for category runtime cache
This issue is automatically created based on existing pull request: magento/magento2#36394: Use current sore id for category runtime cache

---------

### Description (*)
This is shorter PR version of https://github.com/magento/magento2/pull/34226/files that only fixes main issue and does not include suggested performance improvements.

When emulation is used or custom code saves the category in different stores, the object stored in runtime might be from wrong store to that causes data override.

### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/22063
2. https://github.com/magento/magento2/issues/32478

### Manual testing scenarios (*)

1. ...
3. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ilnytskyi**
### Description (*)
This is shorter PR version of https://github.com/magento/magento2/pull/34226/files that only fixes main issue and does not include suggested performance improvements.

When emulation is used or custom code saves the category in different stores, the object stored in runtime might be from wrong store to that causes data override.

### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/22063
2. https://github.com/magento/magento2/issues/32478

### Manual testing scenarios (*)

1. ...
3. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#39310: Use current sore id for category runtime cache

### CODE REVIEW

**Comment by ilnytskyi** [comment]
@magento run all tests

**Comment by ilnytskyi** [comment]
@magento run all tests

**Comment by ilnytskyi** [comment]
@magento run all tests

**Comment by ilnytskyi** [comment]
@magento run all tests

**Comment by ilnytskyi** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Unit Tests, Integration Tests, Functional Tests B2B

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @ilnytskyi,

It seems the failed integration test is due to the changes. Please fix them.

Thanks

**Comment by ilnytskyi** [comment]
@engcom-Hotel I think they can be ported from https://github.com/magento/magento2/pull/34226 or that PR can be processed instead

**Comment by engcom-Hotel** [comment]
Hello @ilnytskyi,

As I can see, the https://github.com/magento/magento2/pull/34226 PR has some performance improvements along with the fix for the main issue. But I can see the same failures on that PR as well.

And also this PR has been `Community Picked` so as per the process we need to process it, and we need a green build for the same. So I request you to please do the needful for this PR.

Thanks

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Integration Tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Static Tests, Integration Tests, Functional Tests B2B

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Dash** [comment]
Hello @ilnytskyi,

Thanks for your contributions!

I tried to replicate the issue by following the steps outlined in the [issue](https://github.com/magento/magento2/issues/32478), but it did not work. While I have reviewed the changes and they look good to me, could you please provide some manual testing steps to help reproduce the issue?

Thanks again!

**Comment by ilnytskyi** [comment]
@engcom-Dash They are covered in new tests from my extended PR: https://github.com/magento/magento2/pull/34226/files#diff-0c57d86ecc634a08c2d329ff07f105f94a34b55d7945804b31740fc21cd4c781

And described in description: https://github.com/magento/magento2/pull/34226

basically previously when custom code did something with category in multistore loop and did not provided store key to category repo. It was cached under `all` key. It could cause random data override including url generation. My change should fix it, as instead of taking random data from `all` key we take it form provided or currently emulated store

I think that Magento/CatalogUrlRewrite/Observer/CategoryUrlPathAutogeneratorObserverTest.php test might be failing due to not cleared runtime cache for category repository. As I see it was added before my changes, and might be affected by the original issue.

Maybe 
```
$this->categoryRepository = $this->objectManager->create(CategoryRepositoryInterface::class);
```

Should be used to isolate tests or removing shared instances in tearDown. I am not sure if AppIsolation works correctly.

**Comment by engcom-Dash** [comment]
Hello @ilnytskyi,

Thank you for your contributions!

✔️ QA Passed

I appreciate your efforts in addressing the issue. While it was challenging to replicate the original problem, I created a script for debugging. I found that when saving the same category without specifying a store, the functionality was fetching data from the array key 'all', leading to potential conflicts.
image


After your changes, I can confirm that the system now creates distinct store IDs as keys in the array. This ensures that the correct category data is retrieved for each store, even when a store ID is not specified.
image

Also I have 


Builds are failed, hence moving it to Extended Testing.

**Comment by engcom-Dash** [comment]
@magento run Integration Tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Unit Tests, Functional Tests B2B

**Comment by engcom-Dash** [comment]
Got a green build so I'm moving it to 'Merge in Progress.'
image

**Comment by engcom-Dash** [comment]
@magento create issue

**Pull request merged**
