### PR TITLE
Improve performance of Mysql::isTableExists()

### PR DESCRIPTION
**Pull request by schmengler**
### Description (*)

Replaces `showTableStatus()` with `getCreateTable()`, which is functionally equivalent for the desired case (return false if table does not exist).

This is especially relevant for `Magento\Indexer\Setup\Recurring`, where lots of repeated calls to `isTableExists()` happen during unsubscribing and subscribing the mviews.

- SHOW TABLE STATUS can take significantly longer than SHOW CREATE TABLE and we are not interested in status information
- getCreateTable() uses DDL cache

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Stepa4man** [comment]
@magento run tests

**Comment by Stepa4man** [comment]
@magento run all tests

**Comment by Stepa4man** [comment]
@schmengler thanks for your contribution.

**Comment by schmengler** [comment]
Looks like this breaks `setup:install` .. I wonder if turning off the DDL cache in this method would help

**Comment by schmengler** [comment]
Apparently not, so I'll have to test and debug before going on

**Comment by southerncomputer** [comment]
This breaks category_flat reindex. I believe it cannot scope to temporary tables.

**Comment by Stepa4man** [comment]
I'm closing this PR due to inactivity. If you are planning to continue work, please open it again. Thanks.

**Comment by schmengler** [comment]
If someone finds this, there is now a better solution at #28516

**Pull request closed without merging**
