### PR TITLE
Filter products in quote from another website

### PR DESCRIPTION
**Pull request by kenboy**
### Related Pull Requests
https://github.com/magento/partners-magento2b2b/pull/46

### Description (*)

The fix allows you to filter products from quote that do not belong to current website.
The call to the `addStoreFilter` method does not matter since `addOptionsToResult` method uploaded the results to the collection

### Manual testing scenarios (*)

1. Add product to cart
2. Remove product from website

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by nuzil — CHANGES_REQUESTED** [review]
Can you please check failed tests?

**Review by nuzil — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@kenboy Please take a look on the failed integration tests. Looks like your changes of fixtures affected MSI tests. Feel free to create a related PR in magento/inventory repo

**Comment by engcom-Charlie** [comment]
Hi @kenboy, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
