### PR TITLE
magento/magento2#37873 rename Swaziland -> Eswatini in the codebase

### LINKED ISSUE #37873: feat(directory): rename Swaziland -> Eswatini in the codebase
### Preconditions and environment

v2.4.7-beta1

### Steps to reproduce

Review the codebase for references to Swaziland

### Expected result

See `Eswatini` instead of `Swaziland`

### Actual result

I see various files which reference `Swaziland` instead of `Eswatini` 

 - [ ] https://github.com/magento/magento2/blob/0a834cce01c3d924d450c9a71123d9ac6de68b62/app/code/Magento/CustomerGraphQl/etc/schema.graphqls#L396

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by yegxr**
-rename Swaziland -> Eswatini in the codebase

### Description (*)

rename Swaziland -> Eswatini in the codebase
### Fixed Issues (if relevant)

1. Fixes magento/magento2#37873

### Manual testing scenarios (*)

1. Review the codebase for references to Swaziland
2. Found the names in the app/code/Magento/CatalogGraphQl/etc/schema.graphqls files
3. Changed the name of the country and put it in alphabetical order
4. I also found the country name in app/code/Magento/Dhl/etc/countries.xml and app/code/Magento/Dhl/Test/Unit/Model/_files/countries.xml and replaced the country name

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by yegxr** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Review by engcom-Hotel — APPROVED** [review]
:heavy_check_mark: Approved

Failed tests seem flaky. Hence moving this PR forward.

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE,Unit Tests,Functional Tests B2B

**Comment by engcom-Delta** [comment]
Format for QA pass comment-

### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

1. Review the codebase for references to Swaziland
2. Verify the names in the app/code/Magento/CatalogGraphQl/etc/schema.graphqls files
3. Verify the country name in app/code/Magento/Dhl/etc/countries.xml and  
    app/code/Magento/Dhl/Test/Unit/Model/_files/countries.xml 
5. Changed the name of the country and put it in alphabetical order

**Before:** :heavy_multiplication_x: 

app/code/Magento/CatalogGraphQl/etc/schema.graphqls files

Screenshot 2023-10-26 at 8 13 22 PM

app/code/Magento/Dhl/etc/countries.xml

Screenshot 2023-10-26 at 7 47 24 PM

 app/code/Magento/Dhl/Test/Unit/Model/_files/countries.xml 

Screenshot 2023-10-26 at 7 48 05 PM


**After:** :heavy_check_mark:  

app/code/Magento/CatalogGraphQl/etc/schema.graphqls files

Screenshot 2023-10-26 at 8 06 59 PM

app/code/Magento/Dhl/etc/countries.xml

Screenshot 2023-10-26 at 7 47 24 PM

app/code/Magento/Dhl/Test/Unit/Model/_files/countries.xml 

Screenshot 2023-10-26 at 7 48 05 PM


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
It seems that bot moved this PR to Ready for Testing, hence moving it back to Extended Testing.

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
The functional CE failures in recent 2 runs are different. Failures not seems to be part of or affected by PR changes. Hence moving to Merge in Progress.

Run 1:
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38071/53f4ac01781dc2850fb4c01525f48f0f/Functional/allure-report-ce/index.html#categories
image

Run 2:
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38071/8342c366acf1e503da5c4127d9dd13be/Functional/allure-report-ce/index.html#categories
image

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by Indraniks** [comment]
@magento run Functional Tests EE

**Pull request merged**
