### PR TITLE
Update NewActionHtml.php

### PR DESCRIPTION
**Pull request by WJdeBaas**
Accept custom "form_namespace" and "form" as request parameters like in Magento\SalesRule\Controller\Adminhtml\Promo\Quote\newConditionHtml

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21187) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @WJdeBaas. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by osrecio — CHANGES_REQUESTED** [review]
Please fill all the information related in the [PR_Template](https://raw.githubusercontent.com/magento/magento2/2.3-develop/.github/PULL_REQUEST_TEMPLATE.md). Thanks!

**Comment by VladimirZaets** [comment]
Hi @WJdeBaas. Thanks for collaboration. Please edit template according to our [standarts](https://raw.githubusercontent.com/magento/magento2/2.3-develop/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by WJdeBaas** [comment]
Never mind, I'll fix those idiotic errors & bugs with some rewrites.

**Pull request closed without merging**
