### PR TITLE
Resolve Scope icon and store view specific label text alignment issue (issue24440)

### LINKED ISSUE #24440: Scope icon and store view specific label text alignment issue
Scope icon and store view specific label text alignment issue

### Preconditions (*)
Magento 2.3.2

### Steps to reproduce (*)
1. Admin -> Store -> Settings ->  Order status -> Create new status

### Expected result (*)
Store View Specific Labels and scope (?) should aligned properly

### Actual result (*)
actual

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#24440: Scope icon and store view specific label text alignment issue

### Fixed Issues (if relevant)

1. magento/magento2#24440: Scope icon and store view specific label text alignment issue

### Manual testing scenarios (*)

1. Admin -> Store -> Settings ->  Order status -> Create new status

#### Expected result 
Store View Specific Labels and scope (?) should aligned properly

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-24449.instances.magento-community.engineering).
Admin access: [https://pr-24449.instances.magento-community.engineering/admin](https://pr-24449.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-24449.instances.magento-community.engineering).
Admin access: [https://pr-24449.instances.magento-community.engineering/admin](https://pr-24449.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-24449.instances.magento-community.engineering).
Admin access: [https://pr-24449.instances.magento-community.engineering/admin](https://pr-24449.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5784](https://jira.corp.magento.com/browse/ENGCOM-5784) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by sudheers-kensium — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
