### PR TITLE
Added fix for issue #3657

### PR DESCRIPTION
**Pull request by atishgoswami**
Fixed the issue regarding the click on auto suggest item

### CODE REVIEW

**Comment by atishgoswami** [comment]
Tests failing due to `MySQL server has gone away`

**Comment by davidalger** [comment]
@atishgoswami Please sync with latest develop. The failing PHP 5.5 tests have been fixed. If the mysql server has gone away affects the new test build, I can restart the job.

**Comment by davidalger** [comment]
Also, please accept the contributors license agreement so this PR can be further processed. This can be done by clicking the "Details" link next to the "license/cla" check below.

**Comment by atishgoswami** [comment]
Hi @davidalger 
- [x]  Sync with latest develop
- [x]  Accept the contributors license

**Comment by davidalger** [comment]
FTR - commit 905c32ae0a2dc57219e5cae50603ca3ada1ffdb5 was pushed by core team as a fix for #3657

**Pull request closed without merging**
