### PR TITLE
[FIXES] #20309: URL Rewrites redirect loop

### PR DESCRIPTION
**Pull request by mautz-et-tong**
### Description (*)
This adds a meaningful exception if request path equals target path on url rewrite edit page in admin

### Fixed Issues (if relevant)

1. magento/magento2#20309: URL Rewrites redirect loop

### Manual testing scenarios (*)

1. Go To Admin -> Marketing -> Url Rewrites.
2. Create a new Url Rewrite with request-path: foo and target_path foo with 301 or 302 redirect.
3. Click Save
4. An error message should appear with "The request path and the target path should differ to prevent an infinite redirecion loop."

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @mautz-et-tong,
Your changes looks good to me.

Could you cover your changes with some tests?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Actually I remembered that such PR we already had in https://github.com/magento/magento2/pull/20313#pullrequestreview-219384257.


With this solution we have few issues:
1. If such URL rewrite was created _before_ these changes introduced - issue will be persisted. In order to fix that  we have two options (or both?)
- create data patch that will find & delete all such incorrect URL rewrites
- adjust logic to do NOT perform redirect in case of target path equal to request path
2. URL rewrites could be created not only Magento admin, but also through custom modules, so would be better to move this validation into URL rewrite model itself.

Could you adjust your PR?

**Comment by mautz-et-tong** [comment]
Actually I would do everything:
1. create data patch that will find & delete all such incorrect URL rewrites (maybe moving to a working redirect with addition (-unique_hash) is better than a deletion?)
2. adjust logic to do NOT perform redirect in case of target path equal to request path (the PR you mentioned should be fair enough, isn't it?)
3. Create a model based validation to prevent this kind of redirects

**Comment by ihor-sviziev** [comment]
Hi @mautz-et-tong,
Do you have any estimates when you'll be able to update your PR?
Maybe do you have any issues?

**Comment by ihor-sviziev** [comment]
Hi @mautz-et-tong,
I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
