### PR TITLE
[MFTF] Adding AdminCheckOrderStatusInGridActionGroup

### LINKED ISSUE #33747: [Issue] [MFTF] Adding AdminCheckOrderStatusInGridActionGroup
This issue is automatically created based on existing pull request: magento/magento2#33727: [MFTF] Adding AdminCheckOrderStatusInGridActionGroup

---------
### Description (*)

New ActionGroup AdminCheckOrderStatusInGridActionGroup has been introduced  (existing tests have been updated as well)

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)

New ActionGroup AdminCheckOrderStatusInGridActionGroup has been introduced  (existing tests have been updated as well)

### Resolved issues:
1. [x] resolves magento/magento2#33747: [MFTF] Adding AdminCheckOrderStatusInGridActionGroup

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, Semantic Version Checker

**Comment by andrewbess** [comment]
@magento run Integration Tests

**Comment by eduard13** [comment]
@magento run Database Compare, Magento Health Index, Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE, Unit Tests, WebAPI Tests

**Comment by eduard13** [comment]
@magento create issue

**Comment by eduard13** [comment]
@magento run Static Tests

**Review by Den4ik — APPROVED** [review]
@AnnaAPak Changes looks good for me

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9181](https://jira.corp.magento.com/browse/ENGCOM-9181) has been created to process this Pull Request

**Comment by sidolov** [comment]
Hi @AnnaAPak. Thank you for your report. 
The issue has been fixed in magento/magento2#33793 by @AnnaAPak in 2.4-develop branch
Related commit(s):
 - [1439ec18c0a3aacd03e7b44f9a7e6e23c3c57ee9](https://github.com/magento/magento2/commit/1439ec18c0a3aacd03e7b44f9a7e6e23c3c57ee9)
 - [778c8ae0fb9d1bd71c62db75528c9e42bcb54504](https://github.com/magento/magento2/commit/778c8ae0fb9d1bd71c62db75528c9e42bcb54504)
 - [3b33ceb798c7ff114010c5f3685e510e91198e10](https://github.com/magento/magento2/commit/3b33ceb798c7ff114010c5f3685e510e91198e10)

The fix will be available with the upcoming release.

**Pull request merged**
