### PR TITLE
Fix missing jQuery widget dependency

### LINKED ISSUE #37683: [Issue] Fix missing jQuery widget dependency
This issue is automatically created based on existing pull request: magento/magento2#37302: Fix missing jQuery widget dependency

---------

### Description (*)

When the JS bundling is enabled, and the trim input js file isn't in the bundle, on the 1st page-view we're getting JS error caused by missing $.widget function.
image
```
bundle-common.min.js:1 TypeError: $.widget is not a function
    at trim-input.min.js:1:46
    at Object.execCb (require.min.js:117:195)
    at i.execCb (bundle-common.min.js:1:525685)
    at Module.check (require.min.js:59:418)
    at Module.enable (require.min.js:77:285)
    at Module.init (require.min.js:57:144)
    at callGetModule (require.min.js:78:238)
    at Object.completeLoad (require.min.js:110:1)
    at HTMLScriptElement.onScriptLoad (require.min.js:117:393)
```

My Pull Request fixes this issue by declaring a missing dependency to jquery widget.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)

When the JS bundling is enabled, and the trim input js file isn't in the bundle, on the 1st page-view we're getting JS error caused by missing $.widget function.
image
```
bundle-common.min.js:1 TypeError: $.widget is not a function
    at trim-input.min.js:1:46
    at Object.execCb (require.min.js:117:195)
    at i.execCb (bundle-common.min.js:1:525685)
    at Module.check (require.min.js:59:418)
    at Module.enable (require.min.js:77:285)
    at Module.init (require.min.js:57:144)
    at callGetModule (require.min.js:78:238)
    at Object.completeLoad (require.min.js:110:1)
    at HTMLScriptElement.onScriptLoad (require.min.js:117:393)
```

My Pull Request fixes this issue by declaring a missing dependency to jquery widget.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37683: Fix missing jQuery widget dependency

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
@engcom-Lima, as I said in the ticket description:
- enable js bundling (i'm using https://github.com/magesuite/magepack) 
- generate list of files that should be added to bundle
- remove from the list of files, the trim-input.js file (magepack.config.js file) 
- generate bundles
- Go to the homepage or login page in incognito mode with opened chrome developer console
Expected result: there shouldn't be type errors like shown on screenshots in the PR description
Actual result: there is a type error

**Comment by engcom-Lima** [comment]
Hi @ihor-sviziev ,

Thanks for your contribution and collaboration.

I have followed the below steps to reproduce the issue:
1. Install with npm:
`npm install -g magepack`
2. Install magepack module: `composer require creativestyle/magesuite-magepack`
3. Generate `magepack generate --cms-url="{{CMS_PAGE_URL}}" --category-url="{{CATEGORY_PAGE_URL}}" --product-url="{{PRODUCT_PAGE_URL}}"` && enable module >> `bin/magento config:set dev/js/enable_magepack_js_bundling 1` and clear cache.
4. Remove from the list of files, the trim-input.js file (magepack.config.js file) >> `'mage/trim-input': 'mage/trim-input',`
5. Generate bundles >> `magepack bundle` && 
6. Go to the homepage or login page in incognito mode with opened Chrome developer console.

But I have observed there is no error in the console: `"TypeError: $.widget is not a function" `. As you have mentioned in the notes that issue will be reproduced rarely. So, can you please provide us with any other way in order to reproduce the issue? 🙂
**Screenshot:**
image

Thanks

**Comment by ihor-sviziev** [comment]
@engcom-Lima, you've added screenshot of a product page. The issue coming when you have some input field that is processed by auto-trim functionality, for instance "subscribe to newsletter" block, or "email field" on login page, etc.
Did you check it on login page for instance?
TBH I'm not sure if we should check it manually, even if you can't reproduce it, because technically it should be absolutely clear that this JS file uses jquery widget is used in this file (`$.widget(...)`), and it's missing in the dependency list. So maybe we can just accept it as is.

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**
1. Install with npm:
`npm install -g magepack`
2. Install magepack module: `composer require creativestyle/magesuite-magepack`
3. Generate `magepack generate --cms-url="{{CMS_PAGE_URL}}" --category-url="{{CATEGORY_PAGE_URL}}" --product-url="{{PRODUCT_PAGE_URL}}"` && enable module >> `bin/magento config:set dev/js/enable_magepack_js_bundling 1` and clear cache.
4. Remove from the list of files, the trim-input.js file (magepack.config.js file) >> `'mage/trim-input': 'mage/trim-input',`
5. Generate bundles >> `magepack bundle` 
6. Go to the homepage or login page in incognito mode with opened Chrome developer console.


**After:** :heavy_check_mark:  No type error found in the console. Verified in login page, newsletter subscription page.
Screenshot 2023-07-05 at 7 55 26 PM

**Pull request merged**
