### PR TITLE
fixed-issue-Admin attributes Advanced Attribute Properties icon doesn't change while collapsing block #26022

### PR DESCRIPTION
**Pull request by abrarpathan19**
Admin attributes Advanced Attribute Properties icon doesn't change while collapsing block
### Fixed Issues (if relevant)

1. magento/magento2#26022: Admin attributes Advanced Attribute Properties icon doesn't change while collapsing block

### Manual testing scenarios (*)

1. Login to admin
2. Store -> Attributes -> products -> properties -> Advanced attribute properties
3. Check the icon of Advanced attribute properties block

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by eduard13** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @eduard13, here is your [new Magento instance](https://pr-27467.instances.magento-community.engineering).
Admin access: [https://pr-27467.instances.magento-community.engineering/admin_846c](https://pr-27467.instances.magento-community.engineering/admin_846c)
Login: `a2aef47b` Password: `723769288f01`
Instance will be terminated in up to 3 hours.

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @abrarpathan19, thank you for your contribution, however we should find the root issue instead of just adjusting the styles.
So please find why exactly this collapsible element doesn't work as expected.
Thank you.

**Comment by eduard13** [comment]
Hi @abrarpathan19, are you willing to continue the progress on this one?

**Comment by abrarpathan19** [comment]
> Hi @abrarpathan19, are you willing to continue the progress on this one?

Hello @eduard13 ,
Yes, I will find that root solution and update.
For now temporary basis  can we fix this issue with my current PR ?.

Kindly share your valuable feedback, 

Thanks,
Abrar

**Comment by eduard13** [comment]
Hi @abrarpathan19 fortunately this is not a critical issue to temporary fix it, that's why is better to find the root issue, and see why does it work differently than other collapsible blocks.
Moreover, the provided changes are breaking the other collapsible blocks which are correctly working.

Thank you.

**Comment by eduard13** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @eduard13, here is your [new Magento instance](https://pr-27467.instances.magento-community.engineering).
Admin access: [https://pr-27467.instances.magento-community.engineering/admin_b83a](https://pr-27467.instances.magento-community.engineering/admin_b83a)
Login: `0e71f18d` Password: `6173305a99cd`
Instance will be terminated in up to 3 hours.

**Comment by abrarpathan19** [comment]
Please review my recent commit 

There two type opposite classes are there
`.opened` and `._show`
So I have created separate  `CSS `code for `.opened `   Now it will not be reflected.

**Comment by eduard13** [comment]
@magento git me test instance

**Comment by eduard13** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @eduard13, here is your [new Magento instance](https://pr-27467.instances.magento-community.engineering).
Admin access: [https://pr-27467.instances.magento-community.engineering/admin_7158](https://pr-27467.instances.magento-community.engineering/admin_7158)
Login: `c601728b` Password: `fdeb99c32219`
Instance will be terminated in up to 3 hours.

**Comment by eduard13** [comment]
@magento run Database Compare, Functional Tests EE, WebAPI Tests

**Comment by eduard13** [comment]
@abrarpathan19, please double check, it still doesn't work correctly. Check other collapsible elements: e.g. **Manage Labels** Tab
image
Also, check the Static Tests and fix them.
Thanks.

**Comment by abrarpathan19** [comment]
> @abrarpathan19, please double check, it still doesn't work correctly. Check other collapsible elements: e.g. **Manage Labels** Tab
> image
> Also, check the Static Tests and fix them.
> Thanks.

Hello,

I have removed unnecessary code and double check all the scenarios.
Kindly review 

Thanks

**Comment by eduard13** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @eduard13, here is your [new Magento instance](https://pr-27467.instances.magento-community.engineering).
Admin access: [https://pr-27467.instances.magento-community.engineering/admin_2650](https://pr-27467.instances.magento-community.engineering/admin_2650)
Login: `fd845e30` Password: `10110446d103`
Instance will be terminated in up to 3 hours.

**Comment by eduard13** [comment]
@abrarpathan19 still doesn't work 😞. Please check it again.
Thanks.

**Comment by eduard13** [comment]
Closing due to inactivity. Please feel free to reopen it in case you’re willing continue the progress.

**Pull request closed without merging**
