### PR TITLE
Limit the php explode to 2 to prevent extra '=' sign content in the a…

### PR DESCRIPTION
**Pull request by dhoang89**
Limit the PHP explode to 2 to prevent extra '=' sign content in the attribute value being exploded to more than 2 elements in the result array.

### Fixed Issues (if relevant)

1. magento/magento2#25188: Import fails if configurable attribute has an equal sign in its value
### Manual testing scenarios (*)

1. Install a new Magento base on branch 2.3-develop
2. Setup sample data following this Docs: https://devdocs.magento.com/guides/v2.3/install-gde/install/sample-data-after-clone.html
3. Go to Magento's backend. Then go to STORES > Attributes > Product > Search for Attribute Size. Scroll down to tab Properties then on the right side select 'Manage Swatch (Values of Your Attribute)' Modify the value, add '=' to any value, let say SX=SX
4. Reindex: bin/magento indexer:reindex
5. Go to System > Export > Products
6. Use the file you got from step 5 to import back. System > Import > Products
7. The error message showup
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by swnsma — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
Hello @dhoang89. Thank You for Your contribution. In order to further process Your PR, please cover it with the appropriate auto-tests.

**Comment by dhoang89** [comment]
Hi @engcom-Bravo, can you show me how to create an auto-test for my PR? Thank you.

**Comment by swnsma** [comment]
Hi, @dhoang89,
There is already tests available:
`\Magento\ConfigurableImportExport\Model\Import\Product\Type\ConfigurableTest`
Could you please add test-case to check the issue which you have fixed?

**Comment by engcom-Golf** [comment]
I will take care of test coverage

**Comment by engcom-Golf** [comment]
HI @swnsma changes covered by unit test, could you please review ?

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by swnsma** [comment]
@magento run Unit Tests

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-6141](https://jira.corp.magento.com/browse/ENGCOM-6141) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
