### PR TITLE
Update underscore to latest version 

### PR DESCRIPTION
**Pull request by in-session**
### Description (*)
Updated to 1.13.2 version 16 Dec 2021 -- minor bugfixes and improved documentation

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by in-session** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9389](https://jira.corp.magento.com/browse/ENGCOM-9389) has been created to process this Pull Request

**Comment by mrtuvn** [comment]
Internal team already updated underscore to latest version. So i think we can close this one

**Comment by ihor-sviziev** [comment]
Fixed in https://github.com/magento/magento2/commit/df76a1ffe5537d0219d91f09113fd965c02d2a1e and https://github.com/magento/magento2/commit/5f56e0bd7a9d306aafd42d97a054570275b9421f

**Pull request closed without merging**
