### PR TITLE
Refactor: Use `$escaper` instead of deprecated `$block` escapers

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
It is nothing new that new Magento developers, as well as the experienced ones bring existing Magento code as a pattern to follow when developing new features / blocks / layouts and customization.

That is why I decided to replace deprecated calls to `$block->escape...` to `$escaper->escape...`. This way, we are slowly going to get rid of deprecated use of `$block` escapers, as well as start to educate developers that there is a correct way to approach that problem.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by hostep** [comment]
I'm highly opposed to such changes which affect so many files on the frontend.

It makes upgrades from a minor version 2.4.0 to 2.4.1 for example a lot harder for us since so many files have changes without much benefits. We always evaluate all changed files in between minor versions and try to apply the same changes to the customised theme.
If this PR gets approved, it will make our job of upgrading to a new minor version a lot harder since we will have to deal with a lot of changed files.

I'm more in favor of having the coding standard getting a rule for detecting this and when somebody touches one of these files in a PR, the static tests will complain and then you have to fix only this single file you touched.
Please don't update all these files in one go, it's very annoying to see this happening to so many files.

Should this PR get merged in 2.4.0, then it's fine for me, but if it's only getting into 2.4.1 then I'm opposed to it.

Just my 2 cents.

Thanks for the effort though!

**Comment by lbajsarowicz** [comment]
@hostep we can park that PR for 2.5

**Comment by hostep** [comment]
Indeed, that would be best I believe.

Fixing those static test failures in all these would make it even worse, so many non-relevant changes, just code cleanup. This is not necessary in my opinion in a minor release and gives a whole burden of extra overhead when verifying Magento upgrades.

**Comment by lbajsarowicz** [comment]
Posponed to `2.5-develop` branch.

**Pull request closed without merging**
