### PR TITLE
magento/magento2#14071: Not able to change a position of last two rel…

### PR DESCRIPTION
**Pull request by max-tkachuk**
…ated products in case of I've 20+ related products.

### Description
Added page size selector for dynamic rows template
which is used in back office product edit page Related Products, Up-Sells, and Cross-Sells lists

### Fixed Issues
fixes magento/magento2#14071: Not able to change a position of last two related products in case of I've 20+ related products.

### Manual testing scenarios
go to BO > Catalog > Products > Edit open "Related Products, Up-Sells, and Cross-Sells" collapsible tab
check page size selector near the pager

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22984) <br/>All committers have signed the CLA.

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @m-a-x-i-m , please, sign CLA, otherwise, we can't process your pull request

**Comment by max-tkachuk** [comment]
> Hi @m-a-x-i-m , please, sign CLA, otherwise, we can't process your pull request

already signed, proceed please

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5439](https://jira.corp.magento.com/browse/ENGCOM-5439) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@m-a-x-i-m thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
