### PR TITLE
Report cron error message where possible

### LINKED ISSUE #34941: [Issue] Report cron error message where possible
This issue is automatically created based on existing pull request: magento/magento2#34069: Report cron error message where possible

---------
### Description
This pull request adds the error message to the new exception created in the exception handler for cron jobs. Without this, the real error message is lost.

### Related Pull Requests

*None*

### Manual testing scenarios
1. Throw a generic exception with a helpful error message within a cron job.
1. Witness the helpful error message is not logged nor available anywhere.
1. Apply changes in this pull request.
1. Witness the helpful error message is preserved.

### Questions or comments
See also https://github.com/Ethan3600/magento2-CronjobManager/pull/164

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fredden**
### Description
This pull request adds the error message to the new exception created in the exception handler for cron jobs. Without this, the real error message is lost.

### Related Pull Requests

*None*

### Manual testing scenarios
1. Throw a generic exception with a helpful error message within a cron job.
1. Witness the helpful error message is not logged nor available anywhere.
1. Apply changes in this pull request.
1. Witness the helpful error message is preserved.

### Questions or comments
See also https://github.com/Ethan3600/magento2-CronjobManager/pull/164

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#34941: Report cron error message where possible

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

**Comment by BarnyShergold** [comment]
@magento run Functional Tests B2B,Functional Tests  EE

**Review by BarnyShergold — APPROVED** [review]
Just need to check why tests failing - re-running

**Comment by magento-engcom-team** [comment]
Hi @BarnyShergold, thank you for the review.
[ENGCOM-9219](https://jira.corp.magento.com/browse/ENGCOM-9219) has been created to process this Pull Request
:eight_spoked_asterisk: @BarnyShergold, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9219](https://jira.corp.magento.com/browse/ENGCOM-9219) has been created to process this Pull Request

**Comment by fredden** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9219](https://jira.corp.magento.com/browse/ENGCOM-9219) has been created to process this Pull Request

**Comment by slavvka** [comment]
@magento give me test instance

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Dash** [comment]
heavy_check_mark: QA Passed

**Manual testing scenario:**

1. I have generated a runtime error manually through code  at app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php on method "_runJob". 
2. Hence while running the cron with command  'php bin/magento cron:run' from magento cli it is throwing a runtime error.
3. In the cron.log I have received an error mentioning "Error when running a cron job" without any real error message
 

**Before:** :heavy_multiplication_x:  We are not getting the real error message point to actual error in cron.log file. 

Screenshot 2022-01-06 at 2 03 09 PM


**After:** :heavy_check_mark:  Along with the message 'Error when running a cron job', we are also getting the error because of which runtime exception happened.


Screenshot 2022-01-06 at 2 07 47 PM


Anything more if you have tested!

**Pull request merged**
