### PR TITLE
'Ship Here' in CamelCase as that's how it is written elsewhere

### LINKED ISSUE #28685: [Issue] 'Ship Here' in CamelCase as that's how it is written elsewhere
This issue is automatically created based on existing pull request: magento/magento2#28547: 'Ship Here' in CamelCase as that's how it is written elsewhere

---------

### Preconditions (*)

In the checkout shipping address modal the text in the primary button was written with a lowercase 'h'. On all other places, and in the translation files, it is written with a capital: 'Ship Here'. As a result, the button with the lowercase version 'Ship here' isn't translated.

1. Has a simple product;
2. Logged as Customer to Storefront with at least 1 saved address;

**Steps to reproduce:**
1. Add translation for "Ship Here" in translation file; ("Ship Here","Ship Here (translated)"  for ex.);
2. Add product to Cart;
3. Click on "**Proceed to Checkout**" button;
4. Click on "**+ New Address**" button;

**Actual Result:** :heavy_multiplication_x: The phrase was not translated

screenshot_47

**Expected Result:** :heavy_check_mark: The phrase was successfully translated

screenshot_48

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by woutk88**
### Description (*)

In the checkout shipping address modal the text in the primary button was written with a lowercase 'h'. On all other places, and in the translation files, it is written with a capital: 'Ship Here'. As a result, the button with the lowercase version 'Ship here' isn't translated.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28685: 'Ship Here' in CamelCase as that's how it is written elsewhere

### CODE REVIEW

**Comment by rogyar** [comment]
@magento run functional tests

**Comment by rogyar** [comment]
@magento run Functional Tests CE

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7631](https://jira.corp.magento.com/browse/ENGCOM-7631) has been created to process this Pull Request

**Review by ptylek — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-7631](https://jira.corp.magento.com/browse/ENGCOM-7631) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
1. Has a simple product;
2. Logged as Customer to Storefront with at least 1 saved address;

**Manual testing scenario:**
1. Add translation for "Ship Here" in translation file; ("Ship Here","Ship Here (translated)"  for ex.);
2. Add product to Cart;
3. Click on "**Proceed to Checkout**" button;
4. Click on "**+ New Address**" button;

**Before:** :heavy_multiplication_x: The phrase was not translated

screenshot_47

**After:** :heavy_check_mark: The phrase was successfully translated

screenshot_48

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
@magento create issue

**Pull request merged**
