### PR TITLE
Update requirejs to latest version

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Update requirejs to latest version
Previous: 2.1.11
Current: 2.3.6

New version come with some improvements, fixes

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33672

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run Unit Tests, Static Tests

**Comment by mrtuvn** [comment]
@magento run Unit Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Static Tests, Unit Tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Could you check the failing unit tests?

**Review by andrewbess — CHANGES_REQUESTED** [review]
Hello @mrtuvn 
Thank you for your contribution.
Could you please update your branch from https://github.com/magento/magento2/tree/platform-health?
Thank you in advance.

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
Seem update to latest version require some extra effort to refactor code. I have checked datepicker have some broken tests

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Unit Tests, Functional Tests B2B, Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run Unit Tests, Functional Tests EE, Functional Tests B2B

**Review by andrewbess — APPROVED** [review]
Hello @mrtuvn 
Thank you for your contribution.
We still have problems with datepicker.
Could you please fix these problems?
Thank you in advance.

**Review by andrewbess — CHANGES_REQUESTED** [review]
Sorry for approving.
It requires additional effort with datepicker.

**Comment by mrtuvn** [comment]
cc: @krzksz @denis-g
Do you know why put require in function scope cause undefined ?
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Ui/view/base/web/js/lib/knockout/bindings/datepicker.js#L91

**Comment by krzksz** [comment]
I don't see any drastic changes in exposing global `require` with the new version. There is some logic however that assigns to it so maybe we are landing in some corner case. You could try swapping `require` with `requirejs` and see what happens but I'm not sure why it only fails for the datepicker as other modules also call it dynamically.

Have you tried testing datepicker manually? Maybe it is only some issue with the unit test?

**Comment by mrtuvn** [comment]
requirejs 2.2.0 work perferctly
requirejs 2.3.6 failed at datepicker binding ko (only one that). This new one come with new define setTimeout as second parameter when compare with previous version

dpick

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B

**Comment by Den4ik** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]

**Comment by mrtuvn** [comment]
@magento give me test instance

**Comment by mrtuvn** [comment]
Screen Shot 2021-08-03 at 01 31 40
note here for recheck

**Comment by mrtuvn** [comment]
just curious why checkout have recaptcha enabled with undefined settings?

**Comment by mrtuvn** [comment]
https://github.com/magento/magento2/pull/33200/files
Maybe related. Seem default magento always load captcha js files by defaults even user not add any config or key

**Review by eduard13 — CHANGES_REQUESTED** [review]
@mrtuvn, instead of changing the library itself (removed the setTimeout), I suggest trying to find the root issue, that is related to the datepicker binding.
Thank you.

**Comment by eduard13** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Static Tests, Unit Tests

**Comment by eduard13** [comment]
@magento run Static Tests

**Comment by eduard13** [comment]
@magento run all tests

**Review by andrewbess — CHANGES_REQUESTED** [review]
Thank you @eduard13 for helping with this PR.
I will group all commits in one today evening.
Thank you again.

**Review by andrewbess — APPROVED** [review]
Hello @mrtuvn @eduard13 
Thank you all for your job.
The commits have been squashed.

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Integration Tests, WebAPI Tests, Functional Tests B2B

**Pull request merged**
