### PR TITLE
Display Wrong Data On Cart Update Page

### PR DESCRIPTION
**Pull request by nit-it**
If we add configurable product in cart with different options And We need to update 1st item from the cart. So we click edit icon and open Update Cart Page But Quantity and Options display wrong on this page.

### Description
This request proposes to set Product options and quantity by checking Item Id.

### Fixed Issues (if relevant)
1.
2. ...

### Manual testing scenarios
1. Create Configurable product.
2. Add that product in cart with Different options and Quantity.
3. Now Update 1st item.So click on update item icon.
4. Update Cart page open .
5. Quantity and selected option display wrong on this page.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14765) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
@nit-it thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VladimirZaets** [comment]
Hi, @nit-it  , I made changes in your code, to match with our code standards. 
[template-security](http://devdocs.magento.com/guides/v2.2/frontend-dev-guide/templates/template-security.html)
[JS code standart](http://devdocs.magento.com/guides/v2.2/coding-standards/code-standard-javascript.html)

**Comment by magento-engcom-team** [comment]
Hi @nit-it. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

**Pull request merged**
