### PR TITLE
DOBISSUE date format changed after customer tries to register with sa…

### PR DESCRIPTION
**Pull request by KaushikChavda**
### Description
When DOB is enabled on the registration page and existing customer tries to re-registration page, DOB format was changed. See the screenshot.
image

### Manual testing scenarios

1. Tested in my local environment and fixed issue.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-1625](https://jira.corp.magento.com/browse/ENGCOM-1625) has been created to process this Pull Request

**Comment by sidolov** [comment]
Hi @KaushikChavda , during QA activities we found issue with provided implementation, please, take a look: 

**Steps to reproduce:**

- Enable DOB: Stores->Configuration->Customers->Customer Configuration->Show Date of Birth=Optional
- Create new customer with DOB.
- Go to My Account->Account Information.

**Expected result:**
Correct DOB format

**Actual result:**
Incorrect DOB format.

15272brokendob

**Comment by KaushikChavda** [comment]
@sidolov Could you please provide me the magento version.

**Comment by sidolov** [comment]
@KaushikChavda sure, latest 2.2-develop

**Comment by KaushikChavda** [comment]
@sidolov I've fixed the issue.

**Comment by sidolov** [comment]
Hi @KaushikChavda , we found new issue with current solution: 

On Create New Customer Account page DOB field always contains default date "1/1/1970" instead of empty field.

**Steps to reproduce:**

Enable DOB: Stores->Configuration->Customers->Customer Configuration->Show Date of Birth=Optional(or Required)
Go to Create New Customer Account page

**Expected result:**
Empty DOB field

**Actual result:**
DOB field contains default date "1/1/1970".

**Comment by KaushikChavda** [comment]
@sidolov,

I've tested on latest Magento branch 2.2.6 and latest 2.2-develop its working fine.

**Comment by miguelbalparda** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, here is your [Magento instance](https://pr-15272.engcom.dev.magento.com).
Admin access: [https://pr-15272.engcom.dev.magento.com/admin](https://pr-15272.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Please make sure you are PR **author** or **assignee** to access the instance.

**Comment by miguelbalparda** [comment]
I was able to reproduce @sidolov issue in the test environment.

**Comment by magento-engcom-team** [comment]
Hi @KaushikChavda. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.6 release.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
