### PR TITLE
Cleanup ObjectManager usage - Magento_Sitemap

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This PR cleanups ObjectManager usage in Magento_Sitemap, adds additional dependencies with backward compatibility to api classes, and removes object manager instantiation from non-api classes

### Fixed Issues (if relevant)

N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]
Failing tests are not related to changes from this PR

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7173](https://jira.corp.magento.com/browse/ENGCOM-7173) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by engcom-Kilo** [comment]
Failed functional tests not related to the changes in this PR

**Pull request merged**
