### PR TITLE
[MFTF] AdminClickCreateOrderOnEditCustomerPageActionGroup adding 

### PR DESCRIPTION
**Pull request by AnnaAPak**
Tests have been updated with AdminClickCreateOrderOnEditCustomerPageActionGroup

### Related Pull Requests
https://github.com/magento/magento2/pull/34249

(!) Please, note: the test is dependent on https://github.com/magento/magento2/pull/34249 changes

### CODE REVIEW

**Comment by sidolov** [comment]
@magento run Functional Tests B2B

**Review by edenduong — APPROVED** [review]

**Review by sidolov — CHANGES_REQUESTED** [review]
@AnnaAPak please, resolve merge conflicts

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @AnnaAPak,

Thanks for the contribution!

I am looking into resolving conflicts.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
I have merged 2.4-develop into this PR branch and resolved all conflicts.

To look into the build failure, currently getting "No build report available" message in Details section.

Once will get the build failure report will resume work on this.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Unit Tests, Semantic Version Checker,Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
I have fixed the build failure issues and after running the tests again below are the observations.

1. Below 2 Functional test cases which are failing now are not part of this PR or not failing because of any changes made in this PR.
-app/code/Magento/Tax/Test/Mftf/Test/AdminCheckingTaxReportGridTest.xml
- app/code/Magento/Cms/Test/Mftf/Test/AdminCmsPageGridUrlFilterApplierTest.xml

2. The unit test failure, is also not because of this PR as the PR is covering new Action groups and refactoring of few existing MFTF test cases using them.

3. After looked into the related PR which is mentioned in description [34249](https://github.com/magento/magento2/pull/34249). This PR is in Merge in Progress status and found that both of these PRs(#34249, current PR #34260) are having some duplicate file creation. 
Eg. All below files are getting newly added . 
- app/code/Magento/Customer/Test/Mftf/ActionGroup/AdminClickCreateOrderOnEditCustomerPageActionGroup.xml
- app/code/Magento/Sales/Test/Mftf/ActionGroup/AdminAssertProductInItemsOrderedGridOnCreateOrderPageActionGroup.xml
- app/code/Magento/Sales/Test/Mftf/ActionGroup/AdminClickConfigureForRecentlyViewedProductActionGroup.xml
- app/code/Magento/Sales/Test/Mftf/ActionGroup/AdminClickOkOnConfigureProductSlidingModalActionGroup.xml
- app/code/Magento/Sales/Test/Mftf/ActionGroup/AdminSelectDropdownOptionOnConfigureProductSlidingModalActionGroup.xml

- Also  
app/code/Magento/Sales/Test/Mftf/Test/MoveRecentlyViewedBundleFixedProductOnOrderPageTest.xml file getting modified in same way in both of these PRs

Hence, in order to avoid the merge conflicts and other issues, currently keeping this current PR on hold until [34249](https://github.com/magento/magento2/pull/34249) gets merge on 2.4-develop.

Once [34249](https://github.com/magento/magento2/pull/34249) PR gets merged will resume work on this.

**Comment by engcom-Charlie** [comment]
As per this [comment](https://github.com/magento/magento2/pull/34260#issuecomment-1000191179) since the related [PR](https://github.com/magento/magento2/pull/34249) is merged to 2.4-develop so moving this PR back to Changes Requested column.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Semantic Version Checker

**Comment by engcom-Charlie** [comment]
@magento run Semantic Version Checker

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Semantic Version Checker, Functional Tests CE

**Comment by engcom-Charlie** [comment]
@magento run Semantic Version Checker, Functional Tests CE

**Comment by engcom-Charlie** [comment]
@magento run Semantic Version Checker

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @AnnaAPak,

The refactoring of 'click selector="{{AdminCustomerMainActionsSection.createOrderBtn}}" stepKey="clickCreateOrder"/>' by using any action group is already done on magento 2.4 with the help of “AdminClickCreateOrderButtonOnEditCustomerPageActionGroup” action group.

Since the intent of this PR is already been taken care in magento 2.4, hence closing this PR.

Please reopen and update if you wish to continue.

Thank you for your contribution!

**Comment by engcom-Charlie** [comment]
Hi @AnnaAPak,

The refactoring of 'click selector="{{AdminCustomerMainActionsSection.createOrderBtn}}" stepKey="clickCreateOrder"/>' by using any action group is already done on magento 2.4 with the help of “AdminClickCreateOrderButtonOnEditCustomerPageActionGroup” action group.

Since the intent of this PR is already been taken care in magento 2.4, hence closing this PR.

Please reopen and update if you wish to continue.

Thank you for your contribution!

**Pull request closed without merging**
