### PR TITLE
Change selected identifier

### LINKED ISSUE #29644: [Issue] Change selected identifier
This issue is automatically created based on existing pull request: magento/magento2#25627: Change selected identifier

---------

### Description (*)

magento can translate contents only when adding new blocks, assigned to different stores with the same identifier. when adding a cms block e.g. within a cms page a cms block widget can add the relation as {{widget .... }}. the id is chosen for the widget to load the block. this will break any translation possibility as one id can not contain multiple translations.
as the widget loads blocks by id or identifier without any further changes the identifier is now selected on selection.

### Manual testing scenarios (*)
1. go to a cms page
2. add a cms block widget
3. click show/hide editor
4. see if block identifier is chosen for the widgets attribute
5. go to cms page, see if block is correctly shown

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by brosenberger**
### Description (*)

magento can translate contents only when adding new blocks, assigned to different stores with the same identifier. when adding a cms block e.g. within a cms page a cms block widget can add the relation as {{widget .... }}. the id is chosen for the widget to load the block. this will break any translation possibility as one id can not contain multiple translations.
as the widget loads blocks by id or identifier without any further changes the identifier is now selected on selection.

### Manual testing scenarios (*)
1. go to a cms page
2. add a cms block widget
3. click show/hide editor
4. see if block identifier is chosen for the widgets attribute
5. go to cms page, see if block is correctly shown

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29644: Change selected identifier

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Review by sidolov — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8294](https://jira.corp.magento.com/browse/ENGCOM-8294) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @sidolov .
Could you put an appropriate label for test coverage?
Thanks!

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**
1. Go to Content -> Blocks -> Add New Block;
2. Fill all fields and Save;
Screenshot from 2020-10-02 16-09-19
3. Go to a cms page for edit (Home Page for ex.);
4. Add a cms block widget;
5. Click show/hide editor;

**Before:** :heavy_multiplication_x: 



**After:** :heavy_check_mark: 



6. Go to cms page, see if the block is correctly shown

Actual Result: :heavy_check_mark:  The block is shown correctly

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @brosenberger .  Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. 
Could you cover your changes by auto test?

**Comment by engcom-Charlie** [comment]
Hi @brosenberger, could you please cover your changes by some kind of autotest? Otherwise, we can't proceed with your PR.
Thank you.

**Comment by engcom-Charlie** [comment]
@brosenberger I'll take care of test coverage.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
I have merged latest magento 2.4-develop into this PR and also it seems that the review comments has been already taken care.

The automation test has been added. Hence moving it to Review.

 
Thank you!

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B ,Functional Tests EE, Functional Tests CE

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

1. Go to Content -> Blocks -> Add New Block;
2. Fill all fields and Save.
3. Go to a cms page for edit (Home Page for ex.);
4. Add a cms block widget.
5. Click show/hide editor.

**Before:** :heavy_multiplication_x: 
**CMS Block :**
Screenshot 2023-03-13 at 5 17 52 PM


**CMS Home page (Editor):**
Screenshot 2023-03-13 at 5 08 34 PM


**After:** :heavy_check_mark:  

Screenshot 2023-03-13 at 5 17 35 PM

Screenshot 2023-03-13 at 5 20 02 PM

Builds are failed. Hence, moving this PR to **Extended testing.**

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE

**Comment by engcom-Echo** [comment]
Functional Tests B2B Test Failure are different on last two run on same commit.
Run1
25627-b2b

Run2
25627-b2b2

**Pull request merged**
