### PR TITLE
magento/magento2#16887: [Forwardport] Fix blocked a frame with origin.

### PR DESCRIPTION
**Pull request by p-bystritsky**
Forwardport for https://github.com/magento/magento2/pull/16887

### Preconditions
1. Magento 2.2.3 or 2.2.4 or 2.2.5
2. Add  the following script to the product page: 
`<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`

### Steps to reproduce
1. Flush cache
2. Open dev-console in your browser
3. Reload page many times

### Expected result
Console without errors

### Actual result
1. Sometime we'll have this error:
console

### Tech notes
Time to time created iframe on following line: https://github.com/magento/magento2/blob/2.2-develop/lib/web/jquery.js#L3123

Our change add try-catch to this method, and when error appears - we just returning an empty array.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @p-bystritsky. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3440](https://jira.corp.magento.com/browse/ENGCOM-3440) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @p-bystritsky. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Comment by fbkaasa** [comment]
What about clients on 2.2.* ? Will there be provided a patch to fix this issue?

**Pull request merged**
