### PR TITLE
BeanShells are changed to correct using of variables

### PR DESCRIPTION
**Pull request by AnnaShepa**
Description (*)
 In loops to collect products in SetUp thread added variable declaration to avoid 500 error. As well as changed using of wrong variable in collection products for edit.

### Manual testing scenarios (*)
Run the SetUp thread - as the result jMeter return no 500 error "org.apache.jorphan.util.JMeterException: Error invoking bsh method: eval"

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22138) <br/>All committers have signed the CLA.

**Review by orlangur — CHANGES_REQUESTED** [review]
Please leave only meaningful changes.

**Comment by AnnaShepa** [comment]
@orlangur formatting updated

**Comment by orlangur** [comment]
@AnnaShepa thanks! Changes looks good to me.

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

**Comment by AnnaShepa** [comment]
@orlangur  done, squashed

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4680](https://jira.corp.magento.com/browse/ENGCOM-4680) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@AnnaShepa thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Performance tests are failing on the validation stage with the following message:

Any changes to the Performance Toolkit JMeter script (setup/performance-toolkit/benchmark.jmx), must be made in the jmx generator fragments (magento2-infrastructure/build/core_dev/performance/mpaf/tool/fragments).         The final version of the Performance Toolkit JMeter script (setup/performance-toolkit/benchmark.jmx) must be generated from fragments via perf.php (read documentation from magento2-infrastructure/build/core_dev/performance/mpaf/README.md)

@p-bystritsky could you please help to resolve this.

**Comment by p-bystritsky** [comment]
@sivaschenko done.

**Comment by sidolov** [comment]
Hi @p-bystritsky , performance build still failing due to scenario inconsistency. Could you please take a look?

**Comment by sivaschenko** [comment]
Performance Acceptance Tests are failing at the CE and B2B validation stage (passing for EE)

@p-bystritsky please check the error message, feel free contact me for any questions

    Any changes to the Performance Toolkit JMeter script (setup/performance-toolkit/benchmark.jmx), 
    must be made in the jmx generator fragments (magento2- 
    infrastructure/build/core_dev/performance/mpaf/tool/fragments).         The final version of the 
    Performance Toolkit JMeter script (setup/performance-toolkit/benchmark.jmx) must be generated 
    from fragments via perf.php (read documentation from magento2- 
    infrastructure/build/core_dev/performance/mpaf/README.md)

**Pull request merged**
