### PR TITLE
Mark Catalog interfaces as API

### LINKED ISSUE #32014: Mark Catalog interfaces as API
The following interfaces should be marked as API in 2.4-develop branch
1. app/code/Magento/Catalog/Block/Product/AwareInterface.php
1. app/code/Magento/Catalog/Block/Product/ReviewRendererInterface.php
1. app/code/Magento/Catalog/Controller/Adminhtml/Product/Initialization/Helper/HandlerInterface.php
1. app/code/Magento/Catalog/Controller/Product/View/ViewInterface.php
1. app/code/Magento/Catalog/Model/Attribute/LockValidatorInterface.php
1. app/code/Magento/Catalog/Model/Config/Source/ProductPriceOptionsInterface.php
1. app/code/Magento/Catalog/Model/Entity/Product/Attribute/Group/AttributeMapperInterface.php
1. app/code/Magento/Catalog/Model/Indexer/Product/Flat/TableDataInterface.php
1. app/code/Magento/Catalog/Model/Layer/CollectionFilterInterface.php
1. app/code/Magento/Catalog/Model/Layer/FilterableAttributeListInterface.php
1. app/code/Magento/Catalog/Model/Layer/ItemCollectionProviderInterface.php
1. app/code/Magento/Catalog/Model/Layer/StateKeyInterface.php
1. app/code/Magento/Catalog/Model/Product/Condition/ConditionInterface.php
1. app/code/Magento/Catalog/Model/Product/Configuration/Item/Option/OptionInterface.php
1. app/code/Magento/Catalog/Model/Product/Media/ConfigInterface.php
1. app/code/Magento/Catalog/Model/Product/Pricing/Renderer/SalableResolverInterface.php
1. app/code/Magento/Catalog/Model/ProductLink/CollectionProviderInterface.php
1. app/code/Magento/Catalog/Model/ProductLink/Converter/ConverterInterface.php
1. app/code/Magento/Catalog/Model/ProductLink/Data/ListCriteriaInterface.php
1. app/code/Magento/Catalog/Model/ProductLink/Data/ListResultInterface.php
1. app/code/Magento/Catalog/Model/ProductLink/MapProviderInterface.php
1. app/code/Magento/Catalog/Model/ProductOptions/ConfigInterface.php
1. app/code/Magento/Catalog/Model/ResourceModel/Product/Indexer/Price/PriceModifierInterface.php
1. app/code/Magento/Catalog/Model/ResourceModel/Product/LinkedProductSelectBuilderInterface.php
1. app/code/Magento/Catalog/Pricing/Price/ConfiguredPriceInterface.php
1. app/code/Magento/Catalog/Pricing/Price/MinimalPriceCalculatorInterface.php
1. app/code/Magento/Catalog/Pricing/Price/SpecialPriceInterface.php
1. app/code/Magento/Catalog/Ui/DataProvider/Product/Form/Modifier/Eav/WysiwygConfigDataProcessorInterface.php

### PR DESCRIPTION
**Pull request by vlmed**
### Description (*)
The following interfaces marked as API:

1. app/code/Magento/Catalog/Block/Product/AwareInterface.php
2. app/code/Magento/Catalog/Block/Product/ReviewRendererInterface.php
3. app/code/Magento/Catalog/Controller/Adminhtml/Product/Initialization/Helper/HandlerInterface.php
4. app/code/Magento/Catalog/Controller/Product/View/ViewInterface.php
5. app/code/Magento/Catalog/Model/Attribute/LockValidatorInterface.php
6. app/code/Magento/Catalog/Model/Config/Source/ProductPriceOptionsInterface.php
7. app/code/Magento/Catalog/Model/Entity/Product/Attribute/Group/AttributeMapperInterface.php
8. app/code/Magento/Catalog/Model/Indexer/Product/Flat/TableDataInterface.php
9. app/code/Magento/Catalog/Model/Layer/CollectionFilterInterface.php
10. app/code/Magento/Catalog/Model/Layer/FilterableAttributeListInterface.php
11. app/code/Magento/Catalog/Model/Layer/ItemCollectionProviderInterface.php
12. app/code/Magento/Catalog/Model/Layer/StateKeyInterface.php
13. app/code/Magento/Catalog/Model/Product/Condition/ConditionInterface.php
14. app/code/Magento/Catalog/Model/Product/Configuration/Item/Option/OptionInterface.php
15. app/code/Magento/Catalog/Model/Product/Media/ConfigInterface.php
16. app/code/Magento/Catalog/Model/Product/Pricing/Renderer/SalableResolverInterface.php
17. app/code/Magento/Catalog/Model/ProductLink/CollectionProviderInterface.php
18. app/code/Magento/Catalog/Model/ProductLink/Converter/ConverterInterface.php
19. app/code/Magento/Catalog/Model/ProductLink/Data/ListCriteriaInterface.php
20. app/code/Magento/Catalog/Model/ProductLink/Data/ListResultInterface.php
21. app/code/Magento/Catalog/Model/ProductLink/MapProviderInterface.php
22. app/code/Magento/Catalog/Model/ProductOptions/ConfigInterface.php
23. app/code/Magento/Catalog/Model/ResourceModel/Product/Indexer/Price/PriceModifierInterface.php
24. app/code/Magento/Catalog/Model/ResourceModel/Product/LinkedProductSelectBuilderInterface.php
25. app/code/Magento/Catalog/Pricing/Price/ConfiguredPriceInterface.php
26. app/code/Magento/Catalog/Pricing/Price/MinimalPriceCalculatorInterface.php
27. app/code/Magento/Catalog/Pricing/Price/SpecialPriceInterface.php
28. app/code/Magento/Catalog/Ui/DataProvider/Product/Form/Modifier/Eav/WysiwygConfigDataProcessorInterface.php

**Marked as API to fix static test**
29. app/code/Magento/Catalog/Model/ResourceModel/Product/Indexer/Price/IndexTableStructure.php
### Fixed Issues (if relevant)

1. Fixes magento/magento2#32014

### Questions or comments
@coderimus 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by vlmed** [comment]
@ihor-sviziev I have removed `@since` according to comment https://github.com/magento/magento2/pull/32085#pullrequestreview-587772693 in my another pull request with similar issue

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Unit Tests, Static Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by ihor-sviziev** [comment]
@sivaschenko any thoughs why static tests are failing?

**Comment by sivaschenko** [comment]
Hi @vlmed @ihor-sviziev , API interfaces should reference only API classes/interfaces.

In this case, `\Magento\Catalog\Model\ResourceModel\Product\Indexer\Price\IndexTableStructure` should be marked as API as well to fix the static tests

**Comment by vlmed** [comment]
@magento run Static Tests

**Comment by vlmed** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Integration Tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8811](https://jira.corp.magento.com/browse/ENGCOM-8811) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by gabrieldagama** [comment]
Closed in favour of https://github.com/magento/magento2/pull/32659

**Pull request closed without merging**
