### PR TITLE
[Forwardport] chore: checkout last 5 commits

### PR DESCRIPTION
**Pull request by mzeis**
### Original Pull Request 
 https://github.com/magento/magento2/pull/15032

### Description

By default Travis checks out the last 50 commits. This PR is meant to see the performance gain by checking out the last 5 commits.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by mzeis** [comment]
@VladimirZaets Sorry for creating the branch inside the Magento 2 repository. Should I create a new PR based on my fork or can you continue processing the PR?

**Comment by VladimirZaets** [comment]
@mzeis  we can't accept PR from the Magento repository, please fork Magento repository and create new PR from your fork.

**Comment by mzeis** [comment]
Done: #15134

**Comment by DanielRuf** [comment]
Hi there 👋 you forgot to delete the branch, this should be done for closed and merged PRs.
I did this for you now.

**Pull request closed without merging**
