### PR TITLE
Fixed - Mini cart View and Edit Cart link not in alignment issue

### LINKED ISSUE #27987: Mini cart  'View and Edit Cart" link not in alignment issue
### Preconditions (*)

1. Magento version 2.3.4 
2.

### Steps to reproduce (*)

1.Add product into cart 
2.click on mini cart button 

### Expected result (*)

1. "View and Edit Cart" link should be vertically aligned.  

2.
 minicart-fix

### Actual result (*)

1. 
minicart-issue

2.

### PR DESCRIPTION
**Pull request by madhurajawat**
Mini cart - "View and Edit Cart" link not in alignment issue

### Description (*)

Mini cart - "View and Edit Cart" link not in alignment issue

### Fixed Issues (if relevant)

1. Fixes magento/magento2#27987

### Manual testing scenarios (*)

1. Add product into the cart
2. Click on the mini cart button

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](https://i-29446-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29446-2-4-develop.instances.magento-community.engineering/admin_4e9b](https://i-29446-2-4-develop.instances.magento-community.engineering/admin_4e9b)
Login: `1a36ef93` Password: `1962c2f1e01c`
Instance will be terminated in up to 3 hours.

**Comment by rogyar** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-29446.instances.magento-community.engineering).
Admin access: [https://pr-29446.instances.magento-community.engineering/admin_0422](https://pr-29446.instances.magento-community.engineering/admin_0422)
Login: `19e7e1ab` Password: `51febdb36cc4`
Instance will be terminated in up to 3 hours.

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @madhurajawat. Thank you for your contribution. 
Unfortunately, the link is still not aligned. You may see it clearly when working with the minicart on mobile resolutions. Also, I would strongly recommend aligning this element using relative values with parent element instead of hardcoded margins. 

image

**Comment by mrtuvn** [comment]
@rogyar the real issue related with empty box (promotions) show. I think this problem not relate with css
see this image
https://user-images.githubusercontent.com/23085790/80589148-f0fab880-8a19-11ea-9c36-284f03b13de7.png
The box empty should not show if we didn't have region 'promotion', so we don't need to render it
Is there any docs relate with promotion so we can create in backend to show real data for test purpose in minicart

**Comment by rogyar** [comment]
Hi @mrtuvn. That totally makes sense. It looks like there are some elements in the "promotion" region out of the box that are not visible but still in the region. I assume that it might be something about the config element in the promotion region 

https://github.com/magento/magento2/blob/1b5dc60a263dcf8b29648b768f01123b065af551/app/code/Magento/Checkout/view/frontend/layout/default.xml#L51

but I might be wrong.

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@rogyar can we continue this closed PR https://github.com/magento/magento2/pull/28010 and cover changes with jasmine or MFTF tests ?
Previously changed related in commit https://github.com/magento/magento2/commit/20d3f40795e8c29aa1a307c55817f557698f2f8a by @mattijv

**Comment by rogyar** [comment]
Hi @mrtuvn. The mentioned solution makes sense but I see an unresolved comment in the old PR 

https://github.com/magento/magento2/pull/28010#pullrequestreview-453420494

**Comment by sidolov** [comment]
@madhurajawat  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
