### PR TITLE
Resolve Toggle icon not working in create configuration Product creation Page issue 22702

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. magento/magento2#22702: Resolve Toggle icon not working in create configuration Product creation Page issue 22702

Reason: No css for "active" class
Solution: Change the .less file to style the icon : @icon-expand-open__content in "active" title class.

### Fixed Issues (if relevant)

1. magento/magento2#22702: Toggle icon not working in create configuration Product creation Page issue 22702

### Manual testing scenarios (*)

1. Catalog > Products > New Product (Configurable) > Click Create Configuration.
2. Select Attributes > Attribute Values > Bulk Images & Price > Summary.
3. Check the Associated Products's **Toggle Icon** in both **opened and closed**

image

Check the Arrow when the collapse is opened or closed 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-23803.instances.magento-community.engineering).
Admin access: [https://pr-23803.instances.magento-community.engineering/admin](https://pr-23803.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-23803.instances.magento-community.engineering).
Admin access: [https://pr-23803.instances.magento-community.engineering/admin](https://pr-23803.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-23803.instances.magento-community.engineering).
Admin access: [https://pr-23803.instances.magento-community.engineering/admin](https://pr-23803.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-23803.instances.magento-community.engineering).
Admin access: [https://pr-23803.instances.magento-community.engineering/admin](https://pr-23803.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-23803.instances.magento-community.engineering).
Admin access: [https://pr-23803.instances.magento-community.engineering/admin](https://pr-23803.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-23803.instances.magento-community.engineering).
Admin access: [https://pr-23803.instances.magento-community.engineering/admin](https://pr-23803.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-5473](https://jira.corp.magento.com/browse/ENGCOM-5473) has been created to process this Pull Request
:eight_spoked_asterisk: @rogyar, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by rogyar** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-23803.instances.magento-community.engineering).
Admin access: [https://pr-23803.instances.magento-community.engineering/admin](https://pr-23803.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by sdzhepa** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Pull request merged**
