### PR TITLE
Add class for styling modal shipping-address

### LINKED ISSUE #36647: [Issue] Add class for styling modal shipping-address
This issue is automatically created based on existing pull request: magento/magento2#35656: Add class for styling modal shipping-address

---------

### Description (*)

Add class for able to styling modal form address shipping. Without specific class Frontend devs not able to complete style entire modal without impact to other modal in checkout (modal-footer/modal-header v.v..)

Before
```less
.modal-popup #opc-new-shipping-address {//some code}
.modal-popup .modal-inner-wrap {//some code but cannot select outer element of modal for styling}
.modal-popup {/*too generic class and impact to other element  modal*/}
```

After

```less
.modal-popup.new-shipping-address-modal {//some styles}
.new-shipping-address-modal {//styles }

.new-shipping-address-modal .modal-inner-wrap {//some styles}
.new-shipping-address-modal .modal-header {//styles}
.new-shipping-address-modal .modal-footer {//styles}

```
Target exactly modal without affects to other modal

evid
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Add class for able to styling modal form address shipping. Without specific class Frontend devs not able to complete style entire modal without impact to other modal in checkout (modal-footer/modal-header v.v..)

Before
```less
.modal-popup #opc-new-shipping-address {//some code}
.modal-popup .modal-inner-wrap {//some code but cannot select outer element of modal for styling}
.modal-popup {/*too generic class and impact to other element  modal*/}
```

After

```less
.modal-popup.new-shipping-address-modal {//some styles}
.new-shipping-address-modal {//styles }

.new-shipping-address-modal .modal-inner-wrap {//some styles}
.new-shipping-address-modal .modal-header {//styles}
.new-shipping-address-modal .modal-footer {//styles}

```
Target exactly modal without affects to other modal

evid
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36647: Add class for styling modal shipping-address

### CODE REVIEW

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Integration Tests

**Comment by engcom-Delta** [comment]
@magento create issue

**Comment by andrewbess** [comment]
This PR already merged and shouldn't have pending review status

**Pull request merged**
