### PR TITLE
Removed usage of CliIndexerReindexActionGroup action group for Catalog module

### LINKED ISSUE #31233: [Issue] Removed usage of CliIndexerReindexActionGroup action group for Catalog module
This issue is automatically created based on existing pull request: magento/magento2#31228: Removed usage of CliIndexerReindexActionGroup action group for Catalog module

---------
### Description
Remove usage or changed value of CliIndexerReindexActionGroup action group from tests to improve execution time for the Catalog module.

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Remove usage or changed value of CliIndexerReindexActionGroup action group from tests to improve execution time for the Catalog module.

### Resolved issues:
1. [x] resolves magento/magento2#31233: Removed usage of CliIndexerReindexActionGroup action group for Catalog module

### CODE REVIEW

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by rogyar** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
Hello @rogyar.
Looks like previous fails for 'Functional Tests B2B' are not related to the changes, please check PR.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8546](https://jira.corp.magento.com/browse/ENGCOM-8546) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
