### PR TITLE
Revert of #36041 PR.  Remove magento/module-grouped-product dependency

### LINKED ISSUE #37322: Revert 36041: created cyclic build graph
### Preconditions and environment

- Magento version (2.4-develop)

### Steps to reproduce

1. Look at v2.4-develop
2. Look at https://github.com/magento/magento2/pull/36041
3. See the modification to `module-catalog`'s composer.json
4. Consider the appropriate module dependencies.

### Expected result

No dependency on grouped-product.

### Actual result

Dependency on grouped product.

### Additional information

This is a completely ridiculous commit. It's criss-crossing packages. The entire thing needs to be reversed. The code itself is probably ok, but someone from arch needs to guide this process better (or we need a tool to protect the graph from this nonsense).

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

cc:@maghamed @sidolov

### PR DESCRIPTION
**Pull request by thecodecook14**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/37322

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by thecodecook14** [comment]
@magento run Unit Tests

**Comment by thecodecook14** [comment]
@magento run all Tests

**Comment by damienwebdev** [comment]
This code isn't enough. The original PR imports code in the wrong package ordering as well.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
As @damienwebdev said,
> This code isn't enough. The original PR imports code in the wrong package ordering as well.

**Comment by thecodecook14** [comment]
Hello @ihor-sviziev @damienwebdev,

Please elaborate more on this.

Thanks

**Comment by thecodecook14** [comment]
@magento run Functional Tests CE, Static Tests, WebAPI Tests

**Comment by thecodecook14** [comment]
@ihor-sviziev thanks for your reply!

In this case either we need to solve it in an another way or we need to add the dependency again. Am I right?

**Comment by ihor-sviziev** [comment]
@thecodecook14, right, we should solve it in another way, and then remove the dependency from composer.json file

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B,Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Echo** [comment]
Functional Tests B2B failure are different on last two run on same commit.
Run1 
image

Run2
image

**Comment by thecodecook14** [comment]
@magento run Functional Tests B2B

**Comment by thecodecook14** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
As per [this](https://github.com/magento/magento2/pull/37354#issuecomment-1519476343) comment, moving this PR to Merge in Progress.

Thank you!

**Pull request merged**
