### PR TITLE
#27089 Fix issue with returning non-available default limit

### LINKED ISSUE #27089: BUG: `getDefaultLimitPerPageValue` returns value that is not available
### Preconditions (*)
image

As a Store Administrator, you are able to provide the **Products per Page on Grid Allowed Values** and **Products per Page on Grid Default Value**. There is no verification, so you can accidentally set the default value to be one of the unavailable options.
 
### Steps to reproduce (*)
1. Change `catalog/frontend/grid_per_page_values` to `1,2,5` using CLI
1. Change `catalog/frontend/grid_per_page` to `12`
1. Get the value of `catalog/frontend/grid_per_page_values` in your Template

### Expected result (*)
1. Configuration should return only allowed values, so we expect to return one of the available values (`1`,`2` or `5`)

### Actual result (*)
1. Configuration returns value that is not allowed - value of `12`

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Fix issue related with returning default value of Limit that is not available

### Fixed Issues (if relevant)
1. magento/magento2#27089

### Manual testing scenarios (*)
N/A

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@ihor-sviziev We need manual approval for Semantic Version Checker, as I just fixed the return types for methods, from invalid ones. Static Tests fixed.

**Comment by ihor-sviziev** [comment]
Waiting for approval for SVC failure

**Comment by lenaorobei** [comment]
Approval request in progress [MC-32331](https://jira.corp.magento.com/browse/MC-32331).

**Comment by ihor-sviziev** [comment]
@lenaorobei still no updates in approval process?

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-7453](https://jira.corp.magento.com/browse/ENGCOM-7453) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@lenaorobei does it mean we got approval and this PR could be merged? If so - I think we need to move it in "merge in progress" status

**Comment by lenaorobei** [comment]
@ihor-sviziev, SVC failure was approved. Now this PR is moved to the testing stage. Once tested, we will take it for delivery.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

### Grid Mode

**Manual testing scenario:**
1. Change `catalog/frontend/grid_per_page_value`s to `1,2,5` using CLI
(Run in console: `php bin/magento config:set catalog/frontend/grid_per_page_values 1,2,5`);
2. Change `catalog/frontend/grid_per_page` to `12`
(Run in console: `php bin/magento config:set catalog/frontend/list_per_page 12`);
3. Get the value of `catalog/frontend/grid_per_page_values` in your Template

**Before:** 
:heavy_multiplication_x: **`getDefaultLimitPerPageValue('grid')`** returns **12**

**After:**
:heavy_check_mark: **`getDefaultLimitPerPageValue('grid')`** returns the lowest of the acceptable values **1**

### List Mode

**Manual testing scenario:**
1. Change `catalog/frontend/list_per_page_value`s to `3,7,9,13` using CLI
(Run in console: `php bin/magento config:set catalog/frontend/list_per_page_values 3,7,9,13`);
2. Change `catalog/frontend/list_per_page` to `11`
(Run in console: `php bin/magento config:set catalog/frontend/list_per_page 11`);
3. Get the value of `catalog/frontend/list_per_page_values` in your Template

**Before:** 
:heavy_multiplication_x: **`getDefaultLimitPerPageValue('list')`** returns **11**

**After:**
:heavy_check_mark: **`getDefaultLimitPerPageValue('list')`** returns the lowest of the acceptable values **3**

**Comment by engcom-Echo** [comment]
SVC failure was approved.

**Comment by okorshenko** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [Magento instance](https://i-27093-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27093-2-4-develop.instances.magento-community.engineering/admin_b727](https://i-27093-2-4-develop.instances.magento-community.engineering/admin_b727)
Login: `1e3133f8` Password: `a673e4b788bb`
Instance will be terminated in up to 3 hours.

**Comment by okorshenko** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [new Magento instance](https://pr-27093.instances.magento-community.engineering).
Admin access: [https://pr-27093.instances.magento-community.engineering/admin_c4f3](https://pr-27093.instances.magento-community.engineering/admin_c4f3)
Login: `ec9c82ce` Password: `f831b5cd3120`
Instance will be terminated in up to 3 hours.

**Pull request merged**
