### PR TITLE
[Backport] Fixed wrong url redirect when edit product review from Customer view page and product view page

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Original Pull Request 
https://github.com/magento/magento2/pull/22202
https://github.com/magento/magento2/pull/22426

### Description (*)

Fixed wrong URL redirect when edit product review from Customer view page and edit product page

### Fixed Issues (if relevant)

1. N/A

### Manual testing scenarios (*)

1. Catalog-> product-> Product Reviews
2. edit any review -> click on save

1.  customer -> Product Reviews
2. edit any review -> click on save

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by ravi-chandra3197** [comment]
Hello @orlangur 
I have update PR code can you review it.

**Comment by orlangur** [comment]
Hi @ravi-chandra3197, not sure why I assigned this one, let's backport together with https://github.com/magento/magento2/pull/22426 once the latter is merged.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-4822](https://jira.corp.magento.com/browse/ENGCOM-4822) has been created to process this Pull Request

**Review by orlangur — CHANGES_REQUESTED** [review]
@sidolov naah, too early :)

**Comment by ravi-chandra3197** [comment]
Hello @sidolov
can you review this PR.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-4822](https://jira.corp.magento.com/browse/ENGCOM-4822) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
