### PR TITLE
[MFTF] Refactoring of AdminApplyTierPriceToProductWithPercentageDiscountTest

### LINKED ISSUE #31153: [Issue] [MFTF] Refactoring of AdminApplyTierPriceToProductWithPercentageDiscountTest
This issue is automatically created based on existing pull request: magento/magento2#31147: [MFTF] Refactoring of AdminApplyTierPriceToProductWithPercentageDiscountTest

---------

### Description (*)
The test is refactored according to the best practices

### Manual testing scenarios (*)
1. Create a product
2. Set tier price with discount=fractional number
3. Go to STorefront and make assertions

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
The test is refactored according to the best practices

### Manual testing scenarios (*)
1. Create a product
2. Set tier price with discount=fractional number
3. Go to STorefront and make assertions

### Resolved issues:
1. [x] resolves magento/magento2#31153: [MFTF] Refactoring of AdminApplyTierPriceToProductWithPercentageDiscountTest

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Review by rogyar — APPROVED** [review]
The failing tests are not related to the current changes

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8522](https://jira.corp.magento.com/browse/ENGCOM-8522) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
QA not applicable. Moving this PR to Extended Testing

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Pull request merged**
