### PR TITLE
[Backport] Wrong currency on creditmemo_grid & sales_order_view > creditmemo grid

### PR DESCRIPTION
**Pull request by latenights**
### Description (*)

Added missing column `order_currency_code` to table `sales_creditmemo_grid`. Copying column `order_currency_code` to `sales_creditmemo_grid`. Price column rendering changed on  `sales_creditmemo_index` (Creditmemo grid) & `sales_order_view` - Creditmemo tab.

### Manual testing scenarios (*)

1. Create order in different currency as configured on default store view
2. Go to Backend > SALES > Credit Memos, create Credit Memo
3. Check *Refunded* column on Credit Memo grid. You should see price in currency configured on default store view.
4. Go to Backend > SALES > Orders > choose your order and check Credit Memo grid in Credit Memos tab. You should see price in currency configured on default store view.

sales_order_view:
image

sales_creditmemo_index:
image

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

Backport for: https://github.com/magento/magento2/pull/22123

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22114) <br/>All committers have signed the CLA.

**Comment by orlangur** [comment]
@latenights please report a bug report separately and fix in `2.3-develop` first if it is reproducible.

**Comment by latenights** [comment]
@orlangur In M2.3 is also messed up. Different currencies (base currency code & order currency code). M2.3 Pull request created https://github.com/magento/magento2/pull/22123

**Comment by orlangur** [comment]
@latenights surely. I mean please report an issue and just link it in both PRs so that this bug and its fix may be properly tracked.

**Comment by VladimirZaets** [comment]
Hi @latenights. The branch `2.2-develop` will be closed for contribution from **July 15, 2019**. Please finish all your Pull Requests till this date, otherwise, they will be closed.
Thanks for collaboration.

**Comment by orlangur** [comment]
Closing as 2.3 PR is still not merged.

**Pull request closed without merging**
