### PR TITLE
2.3 develop pr1

### PR DESCRIPTION
**Pull request by singhabhinay**
### Description (*)
fixed typo error

### Fixed Issues (if relevant)
fixed typo error

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22569) <br/>All committers have signed the CLA.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-5005](https://jira.corp.magento.com/browse/ENGCOM-5005) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@abhinay111222 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VasylShvorak** [comment]
**Notice:** QA not applicable

**Pull request merged**
