### PR TITLE
Replaced php7.4 deprecated function

### LINKED ISSUE #36718: [Issue] Replaced php7.4 deprecated function
This issue is automatically created based on existing pull request: magento/magento2#33878: Replaced php7.4 deprecated function

---------
Replaced array_key_exists (deprecated) with isset() to fix an error that happens when updating a product containing options with the /rest/all/V1/products/ endpoint. With array_key_exists, the update fails with the following error:

Deprecated Functionality: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in vendor/magento/module-catalog/Model/Product/Option/Repository.php on line 234.

Error is gone and operation completes successfully after replacing the array_key_exists function.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by sean-breeden**
Replaced array_key_exists (deprecated) with isset() to fix an error that happens when updating a product containing options with the /rest/all/V1/products/ endpoint. With array_key_exists, the update fails with the following error:

Deprecated Functionality: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in vendor/magento/module-catalog/Model/Product/Option/Repository.php on line 234.

Error is gone and operation completes successfully after replacing the array_key_exists function.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36718: Replaced php7.4 deprecated function

### CODE REVIEW

**Review by bgorski — APPROVED** [review]

**Comment by bgorski** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @bgorski, thank you for the review.
[ENGCOM-9189](https://jira.corp.magento.com/browse/ENGCOM-9189) has been created to process this Pull Request
:eight_spoked_asterisk: @bgorski, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9189](https://jira.corp.magento.com/browse/ENGCOM-9189) has been created to process this Pull Request

**Review by dudzio12 — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@andrewbess, can it be added to the platform health project? Feels like it's related

**Comment by ihor-sviziev** [comment]
@andrewbess @xmav ?

**Review by andrewbess — APPROVED** [review]
Hello @sean-breeden 
Thank you for your contribution
Approved ✔️

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, thank you for the review.
[ENGCOM-9189](https://jira.corp.magento.com/browse/ENGCOM-9189) has been created to process this Pull Request

**Review by andrewbess — CHANGES_REQUESTED** [review]
Hello @sean-breeden 
Could you please add additional test coverage here for WebApi tests?
Thank you in advance.

**Comment by bgorski** [comment]
@andrewbess hey, how about we push this one to testing without requiring any additional tests? This is a replace of one function, so a language-level thing, and no functional changes have been introduced, so we should be good.

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Static Tests

**Comment by engcom-Charlie** [comment]
As there is no functional change made as such in this PR, we can move this PR further with Auto-test: Not Required. Hence moving it further.

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-November** [comment]
Hi @sean-breeden ,
Verified the issue on Magento 2.4-develop instance but the issue is not reproducible with below payload used. Product with customizable options is getting updated as expected. Kindly recheck the behavior on Magento 2.4-develop instance and elaborate missing steps if the issue is still reproducible.
image
image
Payload used to update the product:
PUT request to /rest/all/V1/products/{sku}
_{
  "product": {
    "id": 2049,
    "sku": "dhfhgttb",
    "name": "dhfhgttb",
    "attribute_set_id": 4,
    "price": 0,
    "status": 1,
    "visibility": 4,
    "type_id": "configurable",
    "created_at": "2023-01-10 14:33:35",
    "updated_at": "2023-01-10 14:36:49",
    "weight": 100,
    "extension_attributes": {
        "website_ids": [
            1
        ],
        "category_links": [
            {
                "position": 0,
                "category_id": "2"
            },
            {
                "position": 0,
                "category_id": "3"
            },
            {
                "position": 0,
                "category_id": "4"
            }
        ],
        "stock_item": {
            "item_id": 2049,
            "product_id": 2049,
            "stock_id": 1,
            "qty": 0,
            "is_in_stock": true,
            "is_qty_decimal": false,
            "show_default_notification_message": false,
            "use_config_min_qty": true,
            "min_qty": 0,
            "use_config_min_sale_qty": 1,
            "min_sale_qty": 1,
            "use_config_max_sale_qty": true,
            "max_sale_qty": 10000,
            "use_config_backorders": true,
            "backorders": 0,
            "use_config_notify_stock_qty": true,
            "notify_stock_qty": 1,
            "use_config_qty_increments": true,
            "qty_increments": 0,
            "use_config_enable_qty_inc": true,
            "enable_qty_increments": false,
            "use_config_manage_stock": true,
            "manage_stock": true,
            "low_stock_date": null,
            "is_decimal_divided": false,
            "stock_status_changed_auto": 0
        },
        "configurable_product_options": [
            {
                "id": 296,
                "attribute_id": "93",
                "label": "Color",
                "position": 0,
                "values": [
                    {
                        "value_index": 49
                    },
                    {
                        "value_index": 52
                    }
                ],
                "product_id": 2049
            }
        ],
        "configurable_product_links": [
            2047,
            2048
        ]
    },
    "product_links": [],
    "options": [
        {
            "product_sku": "dhfhgttb",
            "option_id": 1,
            "title": "changed title",
            "type": "area",
            "sort_order": 1,
            "is_require": true,
            "price": 1000,
            "price_type": "fixed",
            "sku": "bjvnjvnfjdn",
            "max_characters": 0,
            "image_size_x": 0,
            "image_size_y": 0
        }
    ],
    "media_gallery_entries": [],
    "custom_attributes": [
      {
            "attribute_code": "page_layout",
            "value": "product-full-width"
        },
        {
            "attribute_code": "options_container",
            "value": "container2"
        },
        {
            "attribute_code": "url_key",
            "value": "dhfhgttb"
        },
        {
            "attribute_code": "msrp_display_actual_price_type",
            "value": "0"
        },
        {
            "attribute_code": "gift_message_available",
            "value": "2"
        },
        {
            "attribute_code": "required_options",
            "value": "1"
        },
        {
            "attribute_code": "has_options",
            "value": "1"
        },
        {
            "attribute_code": "meta_title",
            "value": "dhfhgttb"
        },
        {
            "attribute_code": "meta_keyword",
            "value": "dhfhgttb"
        },
        {
            "attribute_code": "meta_description",
            "value": "dhfhgttb "
        },
        {
            "attribute_code": "tax_class_id",
            "value": "2"
        },
        {
            "attribute_code": "category_ids",
            "value": [
                "2",
                "3",
                "4"
            ]
        }
    ]
  },
  "saveOptions": true
}_

**Comment by engcom-November** [comment]
Hi @sean-breeden , Please let us know if we are missing on anything [here](https://github.com/magento/magento2/pull/33878#issuecomment-1377419312)
Thank you.

**Comment by engcom-Lima** [comment]
Hi @sean-breeden ,

Thanks for your contribution and collaboration.

We are closing this PR as there is no update from long time. Please feel free to reopen this, if you are facing any issues.

Thank you

**Pull request closed without merging**
