### PR TITLE
32848: Upgraded script.aculo.us to the latest version 1.9.0 [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by anzin**
### Description (*)

I've upgraded version script.aculo.us from 1.8.2 to 1.9.0

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32848: Investigate upgrade to the latest script.aculo.us

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@anzin, from the official website,  "current version: script.aculo.us **1.9.0 as of December 23, 2010**"
It's definitely a pretty old thing that probably isn't needed. Could you check if it's used somewhere, maybe we can remove it?

**Comment by Den4ik** [comment]
> @anzin, from the official website, "current version: script.aculo.us **1.9.0 as of December 23, 2010**"
> It's definitely a pretty old thing that probably isn't needed. Could you check if it's used somewhere, maybe we can remove it?

I didn't find any real usage of this file and believe that we can remove it

**Comment by anzin** [comment]
Hello, @ihor-sviziev @Den4ik  thanks for your check, I was also thinking about removing this library, but I needed to investigate everything in more detail, you are right, I removed this library because I also didn't find places, where it is used.

Please check if everything is right.

Thank you.

**Review by andrewbess — APPROVED** [review]
Hello @anzin 
Thank you for your contribution.
BTW, this PR is related to https://github.com/magento/magento2/pull/33480.
The branch must be updated after merging the previous PR and file legacy-build should be regenerated.
cc @Den4ik @ihor-sviziev

**Comment by Den4ik** [comment]
@anzin I think we should also remove `<item type="directory">Lib::scriptaculous</item>` from `view.xml` files

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by anzin** [comment]
@magento run Functional Tests CE

**Comment by anzin** [comment]
@magento run all tests

**Review by Den4ik — APPROVED** [review]

**Comment by Den4ik** [comment]
@magento run WebAPI Tests, Unit Tests, Functional Tests CE, Functional Tests B2B, Functional Tests EE

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run Unit Tests

**Comment by Den4ik** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Please fix functional test failures

**Comment by Den4ik** [comment]
Failed "MC-6192: Checking results of color and other filters" Looks little bit strange for me, because I can't figure out how it's related to changes in PR

**Comment by Den4ik** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE

**Comment by eduard13** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE

**Comment by anzin** [comment]
Hello, I think we can't delete the library **lib/web/scriptaculous/effects.js** right now because it is used in the following libraries:
1. lib/web/prototype/prototype.js
2. lib/web/prototype/validation.js
3. lib/web/prototype/window.js
4. lib/web/extjs/ext-tree.js

It is not possible to delete all these libraries at this time, although they are also obsolete.
I suggest updating this library to the latest version **1.9.0**, and mark this library as deprecated.

@eduard13 Please close this MR, I will create a new one with an updated library.

Thank you.

**Pull request closed without merging**
