### PR TITLE
MFTF: Share wishlist with not valid email address

### LINKED ISSUE #28377: [Issue] MFTF: Share wishlist with not valid email address
This issue is automatically created based on existing pull request: magento/magento2#28330: MFTF: Share wishlist with not valid email address

---------
This PR contains MFTF test for Customer's WishList sharing with not valid email addresses.
PR contains **refactoring** of existed test for wishlist sharing (`StorefrontShareWishlistEntityTest`)
**Deprecated** `StorefrontCustomerShareWishlistActionGroup` due to hardcoded WishList Data Using.
**Announced new** `StorefrontShareCustomerWishlistActionGroup` due to best practices.
### Steps to reproduce (*)

1 - Login as a Customer
2 - Add product into WishList
3 - Fill in share info emails with invalid emails
4 - Click the "Share WishList" button
5 - Perform Assertions

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

### PR DESCRIPTION
**Pull request by DmitryTsymbal**
This PR contains MFTF test for Customer's WishList sharing with not valid email addresses.
PR contains **refactoring** of existed test for wishlist sharing (`StorefrontShareWishlistEntityTest`)
**Deprecated** `StorefrontCustomerShareWishlistActionGroup` due to hardcoded WishList Data Using.
**Announced new** `StorefrontShareCustomerWishlistActionGroup` due to best practices.

**Steps to reproduce:**
1 - Login as a Customer
2 - Add product into WishList
3 - Fill in share info emails with invalid emails
4 - Click the "Share WishList" button
5 - Perform Assertions

### Resolved issues:
1. [x] resolves magento/magento2#28377: MFTF: Share wishlist with not valid email address

### CODE REVIEW

**Comment by dmytro-ch** [comment]
@magento run all tests

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7580](https://jira.corp.magento.com/browse/ENGCOM-7580) has been created to process this Pull Request
:eight_spoked_asterisk: @dmytro-ch, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Charlie** [comment]
Failed test not related to changes from this PR.

**Comment by slavvka** [comment]
@magento create issue

**Pull request merged**
