### PR TITLE
Remove related products that not exist in map list.

### LINKED ISSUE #28892: Disable product that relate to another product make graphql break when query.
### Preconditions (*)

1. Magento Open Source 2.4-develop,  2.3.5-p1 fresh install

### Steps to reproduce (*)

1. Create first product (name: test-01).
2. Create another product (name: test-02). + Add test-01 as related products
3. Disable product test-01
4. Send graphql request to get relate product
```shell
curl -X POST \
  http://magento-2-fresh/graphql \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{"query":"  query productDetail {\n    productDetail: products(pageSize: 10, currentPage: 1, search: \"\") {\n      items {\n        id\n        sku\n        name\n        related_products {\n          id\n          sku\n          url_key\n        }\n      }\n    }\n  }","operationName":"productDetail"}'
```
* Graphql format
```
query productDetail {
  productDetail: products(pageSize: 10, currentPage: 1, search: "") {
    items {
      id
      sku
      name
      related_products {
        id
        sku
        url_key
      }
    }
  }
}
```

### Expected result (*)

1. json response with no error
```json
{
    "data": {
        "productDetail": {
            "items": [
                {
                    "id": 2,
                    "sku": "Test-02",
                    "name": "Test-02",
                    "related_products": []
                }
            ]
        }
    }
}
```

### Actual result (*)

```json
{
    "errors": [
        {
            "debugMessage": "Notice: Undefined offset: 1 in /app/vendor/magento/module-related-product-graph-ql/Model/Resolver/Batch/AbstractLikedProducts.php on line 115",
            "message": "Internal server error",
            "extensions": {
                "category": "internal"
            },
            "locations": [
                {
                    "line": 7,
                    "column": 9
                }
            ],
            "path": [
                "productDetail",
                "items",
                0,
                "related_products"
            ]
        }
    ],
    "data": {
        "productDetail": {
            "items": [
                {
                    "id": 2,
                    "sku": "Test-02",
                    "name": "Test-02",
                    "related_products": null
                }
            ]
        }
    }
}
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by forfin**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#28892

### Manual testing scenarios (*)

1. Create first product (name: test-01).
2. Create another product (name: test-02). + Add test-01 as related products
3. Disable product test-01
4. Send graphql request to get relate product
```
query productDetail {
  productDetail: products(pageSize: 10, currentPage: 1, search: "") {
    items {
      id
      sku
      name
      related_products {
        id
        sku
        url_key
      }
    }
  }
}
```
5. It return result with no error
```
{
    "data": {
        "productDetail": {
            "items": [
                {
                    "id": 2,
                    "sku": "Test-02",
                    "name": "Test-02",
                    "related_products": []
                }
            ]
        }
    }
}
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by gabrieldagama — COMMENTED** [review]
Hi @forfin thanks for the pull request, it looks great! All our contributions now have to be covered with tests, I believe we could cover this change with integration tests, let me know if you are available to cover this.

Thank you!

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Adding this to change state, it needs to be covered with tests.

**Comment by engcom-Echo** [comment]
I will take care of test coverage.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Seems failed functional tests not related to the changes in this PR

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8172](https://jira.corp.magento.com/browse/ENGCOM-8172) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@forfin thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed
Was checked according [Manual testing scenarios](https://github.com/magento/magento2/pull/28896#issue-440365073)
**Result:**
:x: **Before:**


:heavy_check_mark: **After:**
#28896PR

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked according [Manual testing scenarios](https://github.com/magento/magento2/pull/28896#issue-440365073)
**Result:**
:x: **Before:**


:heavy_check_mark: **After:**
#28896PR

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Pull request merged**
