### PR TITLE
Corrected the translation for comment tag

### PR DESCRIPTION
**Pull request by yogeshsuhagiya**
Corrected the translation for `<comment>` tag and added translation key
Goto: STORES > Configuration > Payment Methods > RECOMMENDED SOLUTIONS: > OTHER PAYPAL PAYMENT SOLUTIONS: > Payflow Pro > Required PayPal Settings > Payflow Pro and Express Checkout. > Enable PayPal Credit

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios
N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Yogeshks. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
Hi @yogeshsuhagiya thanks for the pull request! I will be able to process it once you sing the [CLA](https://cla.dev.magento.com/magento/magento2?pullRequest=21023)

**Comment by yogeshsuhagiya** [comment]
Hi @sivaschenko, I've signed CLA. Can you process ahead?

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-4171](https://jira.corp.magento.com/browse/ENGCOM-4171) has been created to process this Pull Request

**Comment by yogeshsuhagiya** [comment]
Hello @magento-engcom-team,  please take a look into this PR. And let me know if any modification requires.

**Comment by sivaschenko** [comment]
HI @yogeshsuhagiya can you please check the failed Travis build?

**Comment by yogeshsuhagiya** [comment]
Hi @sivaschenko , I've checked failed Travis build. It shows the following message. I didn't get it can you please help me to fix it?


There was 1 failure:
1) Magento\Paypal\Model\Config\Structure\Reader\ReaderTest::testXmlConvertedConfigurationAndCompereStructure
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
-                                    'translate' => 'label comment'
+                                    'translate' => 'label'
@@ @@
-                                                    'translate' => 'label'
+                                                    'translate' => 'label comment'
/home/travis/build/magento/magento2/dev/tests/integration/testsuite/Magento/Paypal/Model/Config/Structure/Reader/ReaderTest.php:113

**Comment by yogeshsuhagiya** [comment]
hello @magento-engcom-team, will you please let me know what I have to do next for this PR?

**Comment by yogeshsuhagiya** [comment]
Hello @magento-engcom-team, Almost 20+ days passed but still no progress.

**Comment by sivaschenko** [comment]
Hi @yogeshsuhagiya `Magento\Paypal\Model\Config\Structure\Reader\ReaderTest::testXmlConvertedConfigurationAndCompereStructure` is failing on this pull request. I will help you to fix it. Feel free to contanct me in slack if you'd like to disscuss it.

**Comment by yogeshsuhagiya** [comment]
Hi @sivaschenko, I like to discuss this issue with you in slack, will you please share your slack username? so I can ping you or you can also ping me on `yogeshsuhagiya` username.

**Comment by sivaschenko** [comment]
Failed integration test `Magento\Paypal\Model\Config\Structure\Reader\ReaderTest::testXmlConvertedConfigurationAndCompereStructure` is actually covering the `include` node processing by `Magento\Config\Model\Config\Structure\Reader`.
The test is using `app/code/Magento/Paypal/etc/adminhtml/system/paypal_payflowpro_with_express_checkout.xml` as part of test data. So changes to this file caused test to fail.

The test for `Magento\Config\Model\Config\Structure\Reader` should be removed from the `Magento_PayPal` module and moved to `Magento_Config` module. Sample test data added within integration tests scope should be used instead of actual paypal system.xml files.

**Comment by yogeshsuhagiya** [comment]
Hi @sivaschenko, any updates?

**Comment by sivaschenko** [comment]
Thanks for follow up @yogeshsuhagiya , the refactoring of the test in on our list, planning to do that soon.

**Comment by nmalevanec** [comment]
> Failed integration test `Magento\Paypal\Model\Config\Structure\Reader\ReaderTest::testXmlConvertedConfigurationAndCompereStructure` is actually covering the `include` node processing by `Magento\Config\Model\Config\Structure\Reader`.
> The test is using `app/code/Magento/Paypal/etc/adminhtml/system/paypal_payflowpro_with_express_checkout.xml` as part of test data. So changes to this file caused test to fail.
> 
> The test for `Magento\Config\Model\Config\Structure\Reader` should be removed from the `Magento_PayPal` module and moved to `Magento_Config` module. Sample test data added within integration tests scope should be used instead of actual paypal system.xml files.

@sivaschenko I've refactored mentioned above test and removed usage of actual config.

**Comment by yogeshsuhagiya** [comment]
Hi @sivaschenko, any updates? Passed 8 days more since last update

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-4171](https://jira.corp.magento.com/browse/ENGCOM-4171) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
@yogeshsuhagiya sorry for delay and thanks for the reminder!

**Comment by yogeshsuhagiya** [comment]
hello @sivaschenko Not an issue.

**Comment by VasylShvorak** [comment]
✔️ QA passed

**Pull request merged**
