### PR TITLE
Remove redundant getCacheTags method from the Topmenu class

### LINKED ISSUE #36643: [Issue] Remove redundant getCacheTags method from the Topmenu class
This issue is automatically created based on existing pull request: magento/magento2#35846: Remove redundant getCacheTags method from the Topmenu class

---------

### Description (*)
Remove redundant getCacheTags method from the Topmenu class as it is unneeded:
     The getCacheTags() method from Topmenu class:
     https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Theme/Block/Html/Topmenu.php#L365
     return `array_merge(parent::getCacheTags(), $this->getIdentities());` which already returned by the parent method:
     https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/View/Element/AbstractBlock.php#L1058

### Fixed Issues (if relevant)
1. N/A

### Manual testing scenarios (*)
1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by TuVanDev**
### Description (*)
Remove redundant getCacheTags method from the Topmenu class as it is unneeded:
     The getCacheTags() method from Topmenu class:
     https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Theme/Block/Html/Topmenu.php#L365
     return `array_merge(parent::getCacheTags(), $this->getIdentities());` which already returned by the parent method:
     https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/View/Element/AbstractBlock.php#L1058

### Fixed Issues (if relevant)
1. N/A

### Manual testing scenarios (*)
1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36643: Remove redundant getCacheTags method from the Topmenu class

### CODE REVIEW

**Comment by Viper9x** [comment]
@magento run all tests

**Comment by Viper9x** [comment]
@magento run all tests

**Comment by Viper9x** [comment]
@magento run Functional Tests B2B,Functional Tests CE

**Comment by Viper9x** [comment]
@magento run all tests

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by Viper9x** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento create issue

**Pull request merged**
