### PR TITLE
Store view label not in the middle of panel 

### PR DESCRIPTION
**Pull request by SyntaxKay**
### Description (*)

Store view label not in the middle of panel 
### Fixed Issues (if relevant)

1. magento/magento2#22924: Store view label not in the middle of panel 

### Manual testing scenarios (*)

1. Login to admin panel
2. Content -> Design -> Configuration -> Edit any theme

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — APPROVED** [review]

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @speedy008. Thanks for collaboration. Please fix static tests.

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5124](https://jira.corp.magento.com/browse/ENGCOM-5124) has been created to process this Pull Request

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5124](https://jira.corp.magento.com/browse/ENGCOM-5124) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
