### PR TITLE
[Forwardport]  Correct typo correction js files

### PR DESCRIPTION
**Pull request by hitesh-wagento**
Correct typo correction js files

### Fixed Issues (if relevant)
https://github.com/magento/magento2/pull/15888

N/A
### Manual testing scenarios

N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @hitesh-wagento. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on Pull Request changes
- `@magento-engcom-team give me new test instance` - deploy **NEW** test instance based on Pull Request changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy Vanilla Magento instance for Issue or Pull Request

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by hitesh-wagento** [comment]
@saurabh-aureate  why are you close my PR?

**Comment by VladimirZaets** [comment]
Hi @hitesh-wagento, thank you for collaboration, this PR contains more than typo correction js files, also, origin PR contains only two files with changes instead of nine in your PR.  Can you explain the reason?

**Comment by hitesh-wagento** [comment]
Hi @VladimirZaets 

I have done only below changes in two files 
https://github.com/magento/magento2/pull/16113/commits/f2976b2726f14c32aac07e4adf09014cfd6ddec3

**Comment by VladimirZaets** [comment]
@hitesh-wagento Please, have a look to the header of your PR. Currently, your branch contains 9 changed files. Please, actualizing changes in your branch.
screen shot 2018-06-15 at 11 34 28

**Comment by hitesh-wagento** [comment]
Hi @VladimirZaets

I don't know why it's showing 9 files changed.

**Comment by VladimirZaets** [comment]
@hitesh-wagento because your branch contains 25 commits. Please, create the new branch that will based on current Magento 2.3-develop branch and push your changes to it.

**Pull request closed without merging**
