### PR TITLE
mage_profiler error #7068

### PR DESCRIPTION
**Pull request by srepn**
Bugfixing #7068 (MAGE_PROFILER = 'firebug' error)

### Description

Bugfixing, based on the error message.

### Fixed Issues (if relevant)

1. magento/magento2#7068: MAGE_PROFILER = 'firebug' error

### Manual testing scenarios

1. turn on profile env MAGE_PROFILER = 'firebug';
2. reload php-fpm
3. reload site page

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=9098) <br/>All committers have signed the CLA.

**Comment by srepn** [comment]
Hi, everyone! How can I find the failed test or failure description?

**Comment by okorshenko** [comment]
Hi @serhiirepin 
This PR has empty changeset. Do we still need this PR?

**Comment by srepn** [comment]
Hi, @okorshenko, could you please review my first commit (aadef1d290a3cd713349b1cf419894b58d3071ad)?
Because I think there is no chance to pass CI tests. 
I mean, it seems that type hinting collision happened. 
So as a result either tests or method type declaration should be changed for solving the main issue (#7068). Thanks

**Comment by okorshenko** [comment]
@serhiirepin we would like to eliminate direct knowledge about Zend classed in Magento 2 code base. I would suggest to introduce adapter class for \Zend_Controller_Response_Http and use it in Magento core code instance of Zend classes. Later we will be able to update the component without changes in client code.
Please, see more details here: https://github.com/magento/magento2/issues/9203

**Comment by srepn** [comment]
Hi, @okorshenko, thanks for advice!

**Comment by orlangur** [comment]
This file and firebug mode of profiler output were removed in https://github.com/magento/magento2/pull/9622/files, I believe mentioned issue and this PR are not relevant anymore.

**Comment by srepn** [comment]
Yeah, It makes sense

**Comment by orlangur** [comment]
@serhiirepin thanks for quick response. Can we close this PR then? And I'll add a comment to corresponding issue.

**Comment by srepn** [comment]
@orlangur yeah for sure

**Comment by okorshenko** [comment]
Closing this PR. Thank you @orlangur and @serhiirepin for collaboration

**Pull request closed without merging**
