### PR TITLE
update admin configuration visibility

### LINKED ISSUE #38300: [Issue] update admin configuration visibility
This issue is automatically created based on existing pull request: magento/magento2#33361: update admin configuration visibility

---------

### Description (*)

update admin configuration as admin configuration tab not visible website and store wise
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. N/A

### Questions or comments

1. Issue summary
Admin configuration is a global level configuration so security configuration is not visible on the website and store wise, This PR remove security configuration to show in website and store as the admin section is not allowed to set configuration website wise.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

update admin configuration as admin configuration tab not visible website and store wise
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. N/A

### Questions or comments

1. Issue summary
Admin configuration is a global level configuration so security configuration is not visible on the website and store wise, This PR remove security configuration to show in website and store as the admin section is not allowed to set configuration website wise.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38300: update admin configuration visibility

### CODE REVIEW

**Comment by ravi-chandra3197** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests look not related to changes from this PR.

**Review by Den4ik — APPROVED** [review]

**Comment by Den4ik** [comment]
@magento run Functional Tests CE

**Review by Den4ik — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
Hi @ravi-chandra3197 Thanks for your contribution!
This PR has no details about the issue at all. Kindly provide me the below details in order to process it please.
1. Issue summary
2. Detailed description about the issue
3. Detailed steps to reproduce the issue
4. Expected result
5. Actual result
6. Any additional information if you can provide along with screenshots as such please

Thanks in advance!

**Comment by ravi-chandra3197** [comment]
Hello @engcom-Alfa 
Admin configuration is a global level configuration so security configuration is not visible on the website and store wise, This PR remove security configuration to show in website and store as the admin section is not allowed to set configuration website wise.
Here is the ref. snapshot for the same.
Configuration-Settings-Stores-Magento-Admin (1)

**Comment by ravi-chandra3197** [comment]
@magento run all tests

**Comment by ravi-chandra3197** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@ravi-chandra3197 , Please resolve the conflicts on the PR to proceed further.

Thanks,

**Comment by engcom-Delta** [comment]
@magento create issue

**Comment by ravi-chandra3197** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi @ravi-chandra3197,

Thanks for your contribution.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Please refer the screenshot.

Screenshot 2024-06-13 at 11 58 00


Hence We are closing this PR please feel free to reopen the PR.

Thanks.

**Pull request closed without merging**
