### PR TITLE
[MFTF] Adding AdminClickRefundOfflineOnNewMemoPageActionGroup

### LINKED ISSUE #31325: [Issue] [MFTF] Adding AdminClickRefundOfflineOnNewMemoPageActionGroup
This issue is automatically created based on existing pull request: magento/magento2#31323: [MFTF] Adding AdminClickRefundOfflineOnNewMemoPageActionGroup

---------
### Description (*)
Adding AdminClickRefundOfflineOnNewMemoPageActionGroup

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
Adding AdminClickRefundOfflineOnNewMemoPageActionGroup

### Resolved issues:
1. [x] resolves magento/magento2#31325: [MFTF] Adding AdminClickRefundOfflineOnNewMemoPageActionGroup

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by gabrieldagama** [comment]
@magento create issue

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8580](https://jira.corp.magento.com/browse/ENGCOM-8580) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, WebAPI Tests

**Comment by engcom-Bravo** [comment]
QA is not applicable for MFTF Refactoring PR-s. Moving this PR to _Extended Testing_ column

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Pull request merged**
