### PR TITLE
BugFix: UPS return request address part address line for one line, mu…

### PR DESCRIPTION
**Pull request by none-life**
### Description (*)
Issue while generating return shipping label using Carrier from UPS. While creating request its copy for shipping street line whole with new lines. That causes response with invalid request since it doesn't accept new lines in that field. 

### Related Pull Requests

None

### Fixed Issues (if relevant)

None

### Manual testing scenarios (*)

1. You would have to download some third party RMA for generation label for UPS, Adobe Commerce edition has one.
2. Fill configuration options for UPS test account.
3. Create order with shipping address that contains at least 2 lines, shipped it and create RMA request. 
4. Generate shipping Label using UPS and fill information to it while saving it will throw the error.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by danielrussob** [comment]
@magento give me 2.4.2 instante with edition ee

**Comment by danielrussob** [comment]
@magento give me 2.4.2 instance with edition ee

**Comment by Den4ik** [comment]
@magento run all tests

**Review by Den4ik — APPROVED** [review]
✅ Approved

@sidolov I see that composer installation has correct code for this case. Looks like something is not merged into this repository. Could you please coordinate this PR?

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9402](https://jira.corp.magento.com/browse/ENGCOM-9402) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@none-life thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by Den4ik** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by Den4ik** [comment]
https://github.com/magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests EE

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests EE

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests EE

**Comment by engcom-Alfa** [comment]
Hi @none-life and @Den4ik Thanks for your collaboration and contribution!
I tried to reproduce the issue first in Magento latest instance, and I am unable to follow the steps that you have specified in the above issue description. Below are the detailed steps I tried.

1. Admin>Stores>Configuration>Sales>Shipping Methods> Configured UPS shipping method successfully (Set Enabled for RMA - Yes) 
2. Created a simple product (Set Enable RMA - Yes).
3. Front end> Logged in as customer and set shipping and billing address with full details (Filled all address fields).
4. Placed an order using above created product.
5. Admin side: Sales> Orders > Viewed the above placed order and submitted the shipment.
6. Created a return successfully.

We usually don't see an option of Shipment Label creation post return creation. Can you please elaborate what exact steps you have followed later to reproduce the issue?
If there are deviations in the above followed steps, please correct me that as well.
Thanks in advance!

**Comment by none-life** [comment]
@engcom-Alfa 

Hey, there are more following steps to do with Return and it has be CE edition.

1. After creating the return, we have to apply the chosen items as Authorise and save it.
2. Then we get the CTA button with generation of Label and if we tried to created it will throw the error when we fill information about the package and line items.

Here are some screen shots,
Thanks
Screenshot 2022-03-14 at 15 51 56
Screenshot 2022-03-14 at 15 52 28

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests EE

**Comment by engcom-Alfa** [comment]
Hi @none-life 
I tried to connect with you in slack didn't find you in Community slack channel.
Can you please help me with **what free RMA extension you are using** and **what is the error** you are getting in the last?
Possibly can you please connect with me over the slack (My profile in community channel is - Manjunath KS ; I am a Engcom team QA lead)?
Thanks in advance!

**Comment by Den4ik** [comment]
https://github.com/magento run Functional Tests EE

**Comment by Den4ik** [comment]
@engcom-Alfa github repo code is not equal to release code available it composer. This PR is correct and I believe that we could merge it without delay

**Comment by Den4ik** [comment]
@magento run Functional Tests EE

**Comment by engcom-Alfa** [comment]
Hi @Den4ik thanks for your reply and and response in the slack

Composer available release code contain correct code. Only Github repository has this issue and that has been resolved.
No additional testing is required on this! Since all auto-tests are working fine, moving the ticket to _Merge In Progress_

**Pull request merged**
