### PR TITLE
Issue 36299: Item Qty Goes Negative When Using The Down Arrow Keyboar…

### LINKED ISSUE #36299: Item Qty Goes Negative When Using The Down Arrow Keyboard Key
**ISSUE:**

Item quantity on shopping cart page goes to a negative number when site visitor uses the arrow down key on their keyboard to change the quantity.

**STEPS TO REPLICATE:**
* Create simple product
* Add product to cart from the frontend
* Place the mouse cursor on quantity for any added item on MiniCart or in Shopping cart.
* Use the arrow down key on your keyboard or the scroll wheel on your mouse to change the qty

**Actual result:** It will go down to a negative number 

**Expected result:** No negative numbers in qty field.

### PR DESCRIPTION
**Pull request by rogerdz**
…d Key

### Description (*)

Set min="0" for input type=number

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36299

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run WebAPI Tests, Integration Tests

**Comment by rogerdz** [comment]
@magento run Integration Tests, Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by rogerdz** [comment]
@magento run Integration Tests, Functional Tests CE

**Review by ishakhsuvarov — APPROVED** [review]

**Pull request merged**
