### PR TITLE
Resolve Console error when clicking select all at "Newsletter Problems Report" (issue 24102)

### LINKED ISSUE #24102: Console error when clicking checkbox at "Newsletter Problems Report"
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Backend
2. Report -> Newsletter Problems Report
3. Make sure no record in the grid. Check the checkbox

When Click

image

### Expected result (*)

1. Should  no console error

### Actual result (*)

image

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#24102: Console error when clicking select all at "Newsletter Problems Report"

=> Can not select all 

Solution: 
- The selector is wrong , so need to change selector

### Fixed Issues (if relevant)

1. magento/magento2#24102: Console error when clicking select all  at "Newsletter Problems Report"

### Manual testing scenarios (*)

1. Go to Backend
2. Report -> Newsletter Problems Report
3. Make sure no record in the grid. Check the select all

=> No console error

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by Stepa4man — APPROVED** [review]
Hi, @edenduong 
Thanks for your contribution!

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, thank you for the review.
[ENGCOM-5590](https://jira.corp.magento.com/browse/ENGCOM-5590) has been created to process this Pull Request
:eight_spoked_asterisk: @Stepa4man, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @edenduong !

During testing we faced an issue.

I don't think that checkbox is useless, because when you have some problem reports in the grid, "Unsubscribe Selected" and "Delete Selected Problems" buttons appears. I think this buttons related with checkbox in the grid.
after

@edenduong Could you take a look, please?

Thanks!

**Comment by edenduong** [comment]
@engcom-Alfa : Thank you for your reply. I see. I will check it again. Because it has the Console Error when you click the checkbox (when no record).

**Comment by edenduong** [comment]
@engcom-Alfa: I have changed the purpose of this PR. I changed the source code to fix the problem about "Console error when clicking checkbox at "Newsletter Problems Report" (If grid has no record)".
@Stepa4man : Please review my new changes . Thank you very much :)

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5590](https://jira.corp.magento.com/browse/ENGCOM-5590) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @edenduong 

When we have some records, console errors occurs again

**Actual Result:**
after2

@edenduong  Could you take a look, please?

Thanks!

**Comment by edenduong** [comment]
@engcom-Alfa: I fixed it. Please check it again. Now the "select all" can run normally (it can not run before because of the Javascript errors)
@Stepa4man : Please review my new changes . Thank you very much :)

**Comment by Stepa4man** [comment]
@magento run all tests

**Comment by edenduong** [comment]
@Stepa4man , @sidolov : Could you please remove the "Need Update" so it can move to the "Testing" step? Thanks!

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5590](https://jira.corp.magento.com/browse/ENGCOM-5590) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Pull request merged**
