### PR TITLE
Resolve No margin between checkbox and icon when choose category in condition in Cart/Catalog Rule issue25596

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

Add css margin-left to separate checkbox and icon.

1. magento/magento2#25596: No margin between checkbox and icon when choose category in condition in Cart/Catalog Rule

### Fixed Issues (if relevant)

1. magento/magento2#25596: No margin between checkbox and icon when choose category in condition in Cart/Catalog Rule

### Manual testing scenarios (*)

1. Go to backend.
2. Marketing-> Catalog Price Rule
3. Create New
4. Go to conditions, choose rule category

image

#### Expected result 

1. Have margin
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-25597.instances.magento-community.engineering).
Admin access: [https://pr-25597.instances.magento-community.engineering/admin](https://pr-25597.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rodrigowebjump — APPROVED** [review]
Hi @edenduong 
Thanks for your contributtion.

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-6290](https://jira.corp.magento.com/browse/ENGCOM-6290) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
