### PR TITLE
Fix UK mobile number validation

### PR DESCRIPTION
**Pull request by unfunco**
The validation for UK mobile numbers is too restrictive on the third digit, my own phone number begins 074 and the current validator does not return a valid match, this loosens the restriction.

### CODE REVIEW

**Comment by unfunco** [comment]
See here for a complete list of phone number prefixes and their respective issuers.
http://www.area-codes.org.uk/mobile/

**Comment by adragus-inviqa** [comment]
Dear M2, _you cannot checkout with a 074 prefix_. Please label this `Checkout` and `OMG`. Thanks.

**Comment by unfunco** [comment]
I've deleted the fork and branch where I originally did this work, and since then there's now conflicts, let me know if I can be of assistance in resolving these.

**Comment by okorshenko** [comment]
@unfunco thank you for your contribution. Your pull request merged to develop branch

**Comment by unfunco** [comment]
I don't particularly care about this but I'm sure others will: merging multiple community pull requests into a single one and then merging them, thereby removing the original author from the contributions list, might ruffle a few feathers… You might lose a few contributors if you're not appropriately crediting them with fixing your bugs.

**Comment by ishakhsuvarov** [comment]
Hi @unfunco 
We usually merge all PRs keeping original commits and authors intact. 

Sadly, in this case the fork and branch were deleted, so in effort to speed things up I've used the patch, provided by github to merge the proposed fix. 
Commit [`701eb3a`](https://github.com/magento/magento2/commit/701eb3a) is associated to your account. It is not displayed in this PR history, since hash was changed as a result of conflict resolution.

**Pull request closed without merging**
