### PR TITLE
Pluralization

### PR DESCRIPTION
**Pull request by Nolwennig**
adminhtml pluralization : *record(s) found* mention near massaction selecter.

### CODE REVIEW

**Comment by vrann** [comment]
@Nolwennig thank you for the contribution!

The PR does not cover the case of 0 records, it should say: "0 records found". Can you please update your pull request to reflect this case?

**Comment by vrann** [comment]
@Nolwennig also, can you please squash all commits into one commit and add meaningful commit message?

**Comment by vrann** [comment]
@Nolwennig please let me know if any help needed.
I can make changes per my comments, but we will lose information about your contribution in git history :) will be great if you can help fix and squash it.

**Comment by Nolwennig** [comment]
@vrann thanks for your improving comments 

Right now, I have no time to cover the case of 0 records and properize git history :disappointed: 

_(In french language, zero can be considered like single or plural)_

You can make changes if you want :smile:

**Comment by vrann** [comment]
@Nolwennig thanks, I'll reject the pull request, feel free to re-open if code not fixed before that.

**Pull request closed without merging**
