### PR TITLE
fixes-customer-information-wishlist-bundle-product-options-alignment

### PR DESCRIPTION
**Pull request by priti2jcommerce**
### Description (*)
admin customer information wishlist bundle product options alignment issue while editing
Magento 2.3.0

### Manual testing scenarios (*)

1. Go to admin
2. In Customers >>All customers>> edit customer>>click on wishlist
3. Action Configure for bundle product added into wishlist

### Expected result (*)
2019-01-24_15-52_p d - customers - customers

### Actual result (*)
2019-01-24_15-53_p d - customers - customers

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by priti2jcommerce** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by priti2jcommerce** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce, here is your [Magento instance](https://i-20575-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20575-2-2-develop.instances.magento-community.engineering/admin](https://i-20575-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-4064](https://jira.corp.magento.com/browse/ENGCOM-4064) has been created to process this Pull Request

**Comment by sidolov** [comment]
Hi @priti2jcommerce , we cannot reproduce the described issue on the 2.3-develop vanilla instance. 

**Steps to reproduce:**
1. Create Bundle product with options;
2. Create new Customer and login in Storefront;
3. Add created before product to Wish list;
4. Login to Admin;
5. Go to Customers->All Customers;
6. Click on "Edit" link in the grid;
7. Click on "Wish List" button in the "CUSTOMER INFORMATION" tab;
8. Click on "Configure"link in the product grid
 
**Actual result:
before
**
Bundle options shown with correct alignment

**Comment by priti2jcommerce** [comment]
Hi @sidolov ,

Thanks for the update, May be that issue has been fixed, I have also checked on test instance and found that its fine.
Thank you!

**Comment by sidolov** [comment]
Hi @priti2jcommerce , thank you for the re-check, I'm closing this PR due to fixed issue. 
Thank you for your contribution!

**Pull request closed without merging**
