### PR TITLE
Fix - 'frame-ancestors' does not support ''unsafe-inline'

### LINKED ISSUE #33101: The Content-Security-Policy directive 'frame-ancestors' does not support the source expression ''unsafe-inline''
### Preconditions (*)

1. Magento 2.4.2-p1 with sample data
2. Chrome v91

### Steps to reproduce (*)

1. Open console in Google Chrome (F12)
2. Reload the homepage

### Expected result (*)

1. Console without error

### Actual result (*)

1. Console is displaying error: 
The Content-Security-Policy directive 'frame-ancestors' does not support the source expression ''unsafe-inline''

How to solve 'frame-ancestors' issue?

### PR DESCRIPTION
**Pull request by fireufo**
### Description (*)

The wrong setting will cause a Chrome console error: The Content-Security-Policy directive 'frame-ancestors' does not support the source expression ''unsafe-inline''.

> The frame-ancestors directive’s syntax is similar to a source list of other directives (e.g. default-src), but doesn't allow 'unsafe-eval' or 'unsafe-inline'.

Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors#sources

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33101

### Manual testing scenarios (*)

1. Newly installed Magento 2.4, go to homepage, open the Chrome(version 91) console, you will see the error msg: The Content-Security-Policy directive 'frame-ancestors' does not support the source expression ''unsafe-inline''.
2. After apply my changes, clear the Magento cache, refresh the homepage, the Chrome console error is gone.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by KeyShang** [comment]
@magento run all tests

**Comment by KeyShang** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by KeyShang** [comment]
> @magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

Hi, I signed the Abobe CLA, but it still said "No signed agreements were found. Please sign the Adobe CLA! Once signed, close and re-open your pull request".

**Comment by mrtuvn** [comment]
Make sure you use correct signed CLA account for pull request

**Comment by mrtuvn** [comment]
failed test Functional Tests CE seem not related with pull request update

**Comment by KeyShang** [comment]
> Make sure you use correct signed CLA account for pull request
You are right, it is working now, thanks.

**Comment by KeyShang** [comment]
> failed test Functional Tests CE seem not related with pull request update

Yes, the pull request is a small change about CSP, there shouldn't be any problem.

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-9125](https://jira.corp.magento.com/browse/ENGCOM-9125) has been created to process this Pull Request

**Comment by mrtuvn** [comment]
Hi @KeyShang Can you update pull resquest description and update issue ID related ?
See Fixed Issues (if relevant)

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE

**Comment by KeyShang** [comment]
> Hi @KeyShang Can you update pull resquest description and update issue ID related ?
> See Fixed Issues (if relevant)

Add it now.

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Comment by engcom-Hotel** [comment]
✔️ QA Passed

This PR has fix related to the error that comes in the console of Chrome V91 (or greater than) as below:

`The Content-Security-Policy directive 'frame-ancestors' does not support the source expression ''unsafe-inline''`

Before fix we are getting the above error, please find the screenshot below for reference:

Screenshot 2021-07-29 at 2 23 40 PM

After the fix, we are not getting such error in the console, please find the below screenshot for reference:

Screenshot 2021-07-29 at 2 26 47 PM

Thanks for the contribution @KeyShang

**Comment by hostep** [comment]
@lytesaber: One of the two lines that changed in this PR is part of 2.4.3-p1. If that's enough to fix this problem, I'm not sure though.
But it's mentioned on the [unpublished release notes for 2.4.3-p1](https://github.com/magento/devdocs/blob/50e9bbfd9da080c359d6335f0c918d0067890bdd/src/guides/v2.4/release-notes/2-4-3-p1.md)

So it sounds like it will be fixed in 2.4.3-p1, but best is probably to double check after it gets [released tomorrow](https://devdocs.magento.com/release/).

**Comment by khnaim** [comment]
The same issue still persists on 2.4.3-p1

**Pull request merged**
