### PR TITLE
Fix #21648 Checkout Agreements checkbox missing asterisk

### LINKED ISSUE #21648: Checkout Agreements checkbox missing asterisk
### Preconditions (*)

saw issue in both 2.2 and 2.3

### Steps to reproduce (*)

1. Create Terms and Conditions agreement 
2. Enable it with "manual" setting so checkbox would be shown
3. Go to checkout

### Expected result (*)

Agreement checkbox label should have red asterisk as it's required to check it

### Actual result (*)

Asterisk is missing and after pressing place order gives message that field is required

### PR DESCRIPTION
**Pull request by Karlasa**
### Fixed Issues (if relevant)

1. magento/magento2#21648 : missing asterisk in checkout Agreements

### Manual testing scenarios (*)
Create Terms and Conditions agreement
Enable it with "manual" setting so checkbox would be shown
Go to checkout
Expected result (*)
Agreement checkbox label should have red asterisk as it's required to check it

Actual result (*)
Asterisk is missing and after pressing place order gives message that field is required
### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Karlasa. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by Karlasa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Karlasa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Karlasa, here is your [new Magento instance](https://pr-21649.instances.magento-community.engineering).
Admin access: [https://pr-21649.instances.magento-community.engineering/admin](https://pr-21649.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by Karlasa** [comment]
double checked looks correct 👍

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-21649.instances.magento-community.engineering).
Admin access: [https://pr-21649.instances.magento-community.engineering/admin](https://pr-21649.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4475](https://jira.corp.magento.com/browse/ENGCOM-4475) has been created to process this Pull Request

**Comment by soleksii** [comment]
Hi @Karlasa! I've checked PR and found a problem.

**Manual testing scenario:**

1. Login to Admin;
2. Go to Stores -> Terms and Conditions, press button "Add New Condition";
3. Fill all required fields, select "manual" from "Applied" drop-down menu and Save it;
4. Enable "Terms and Conditions" ( Go to Stores->Configuration->Sales->Checkout->Checkout Options)
5. Change theme to Blank;
6. Go to Storefront;
7. Add any product to Cart and click "Proceed to Checkout";
8. Fill all required fields and click "Next" button;
:x: In "Review & Payments" page checkbox and asterisk has incorrect position;
problem

**Comment by Karlasa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Karlasa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Karlasa, here is your [new Magento instance](https://pr-21649.instances.magento-community.engineering).
Admin access: [https://pr-21649.instances.magento-community.engineering/admin](https://pr-21649.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by Karlasa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Karlasa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Karlasa, here is your [new Magento instance](https://pr-21649.instances.magento-community.engineering).
Admin access: [https://pr-21649.instances.magento-community.engineering/admin](https://pr-21649.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by Karlasa** [comment]
@stoleksiy  Thanks for finding that bug 👍 
added required changes. 
Screen Shot 2019-03-13 at 12 49 52
Screen Shot 2019-03-13 at 12 48 13

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-4475](https://jira.corp.magento.com/browse/ENGCOM-4475) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed 

Result (Luma):

after2

Result (Blank):

after1

**Pull request merged**
