### PR TITLE
Created plugin for prevent caching preloader product data

### PR DESCRIPTION
**Pull request by engcom-Echo**
### Description (*)

composer version - local run - \Magento\CatalogInventory\Model\StockItemSave\OnProductCreate\ByProductModel\ByQuantityAndStockStatusTest class failure

### Fixed Issues (if relevant)

No issues created

### Manual testing scenarios (*)

No manual testing required

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @engcom-Echo,
Please review & fix failing tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE, Integration Tests, Static Tests, WebAPI Tests

**Comment by ihor-sviziev** [comment]
@engcom-Echo will you be able to fix failing integration tests?

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Sample Data Tests EE, Integration Tests

**Comment by ihor-sviziev** [comment]
@engcom-Echo integration tests still failing. Any thoughts?

**Comment by ihor-sviziev** [comment]
@engcom-Echo  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
