### PR TITLE
Make database default foreign keys ON_DELETE consistent

### PR DESCRIPTION
**Pull request by samuel27m**
### Description (*)

Function `Magento\Framework\DB\Ddl\Table::addForeignKey` has onDelete parameter default to null which leads to be set in the table as NO ACTION

Function `Magento\Framework\DB\Adapter\AdapterInterface::addForeignKey` has onDelete parameters default which leads to be set in the table as CASCADE

This commit makes both to output same results

### Manual testing scenarios (*)

$connection is a `Magento\Framework\DB\Adapter\AdapterInterface` object in this example

`$connection->newTable('TEST')->addForeignKey('TEST_123', 'field', 'customer_entity', 'entity_id')`
vs 
`$connection->addForeignKey('TEST_123', 'TEST', 'field', 'customer_entity', 'entity_id')`

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @samuel27m. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
Please write an integration test to assure this behavior is consistent in eternity.

Is it a safe change for all the existing code?

@samuel27m, also, I don't think we are able to process contributions from an `unknown repository`.

**Comment by samuel27m** [comment]
@orlangur You're right, I forgot this pull request and I deleted the repo. Will recreate pull request with new repository

**Comment by orlangur** [comment]
@samuel27m thanks, feel free to assign me immediately when new PR is created.

**Pull request closed without merging**
