### PR TITLE
Move pieces of Magento_Review out of Magento_Customer

### PR DESCRIPTION
**Pull request by navarr**
### Description (*)

This moves the last few pieces of review functionality out of Magento_Customer.

**Please note**, this causes a breaking change to Magento_Customer, and adds an `@api` annotated class to Magento_Review.  I think it's too late for 2.3 and probably has to be part of 2.4

### Fixed Issues (if relevant)

1. magento/magento2#18302: Unable to disable module Magento_Review

### Manual testing scenarios (*)

1. Log in to the admin panel
2. View any customer record
3. Click the "Product Reviews" tab
4. Ensure a grid appears

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @navarr. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by navarr** [comment]
#squashtoberfest

**Comment by navarr** [comment]
#squashtoberfest

**Comment by orlangur** [comment]
Closing for now, there is still no `2.4-develop` available.

**Pull request closed without merging**
