### PR TITLE
Fix robots.txt not store specific

### LINKED ISSUE #28901: Sitemap in robots.txt not store specific
### Preconditions (*)

1. Magento CE 2.3.3
Magento 2.4 and 2.3.5-p1

### Steps to reproduce (*)

1. Create Second Web Site, Store and Store View
2. Go to Stores -> Configuration -> General -> Web 
3. Set "Add Store Code to Urls" = "Yes" -> Save
4. Go to Stores -> Configuration -> Catalog -> XML Sitemap
5. Expand "Generation Settings" section
6. Set "Enabled" = "Yes"
7. Expand "Search Engine Submission Settings" section
8. Set "Enable Submission to Robots.txt" = "Yes" -> Save
9. Run `php bin/magento cron:run` and `php bin/magento c:f`
10. Go to Marketing -> Site Map
11. Create 2 Site Maps (one for Default site and another one for second with different "Filename" 
Screenshot_14
12. Save & Generate
13. Run `php bin/magento cron:run` and `php bin/magento c:f`
14. Go to store view and open Default store (http://youredomain.local/robots.txt)
15. Then in new tab open Second store (http://youredomain.local/de/robots.txt)

### Expected result (*)

Site Maps should be different (because of different Filename)
 The Sitemap: property should be retrieved within the context of the store

### Actual result (*)

Site Maps are the same
Screenshot_13

### Proposed Solution
The Sitemap value is retrieved in Magento\Sitemap\Block\Robots::_toHtml() and within this function the \Magento\Store\Model\StoreManagerInterface::getDefaultStoreView() is called to get the list of store ids to generate the sitemap for, this results in the value for the default store only ever being returned.
[Here](https://github.com/magento/magento2/issues/28901#issuecomment-650195689) is comment with posible fix the issue

**Note** In Content -> Design -> Configuration you can configure the file settings robots.txt 

Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ X ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by engcom-Charlie**
### Description (*)

Fixed and covered by test

### Fixed Issues (if relevant)

1. Fixes magento/magento2#28901

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7924](https://jira.corp.magento.com/browse/ENGCOM-7924) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Create Second Web Site, Store and Store View
2. Go to Stores -> Configuration -> General -> Web 
3. Set "Add Store Code to Urls" = "Yes" -> Save
4. Go to Stores -> Configuration -> Catalog -> XML Sitemap
5. Expand "Generation Settings" section
6. Set "Enabled" = "Yes"
7. Expand "Search Engine Submission Settings" section
8. Set "Enable Submission to Robots.txt" = "Yes" -> Save
9. Run `php bin/magento cron:run` and `php bin/magento c:f`
10. Go to Marketing -> Site Map
11. Create 2 Site Maps (one for Default site and another one for second with different "Filename" 
Screenshot from 2020-07-31 11-34-38

13. Run `php bin/magento cron:run` and `php bin/magento c:f`
14. Go to store view and open Default store (http://youredomain.local/robots.txt)
15. Then in new tab open Second store (http://youredomain.local/second_website_store_view/robots.txt)

**Before:** :heavy_multiplication_x: Site maps are the same

 :heavy_check_mark:  _Default store view_



:heavy_multiplication_x: _Second Website Store View_




**After:**

 :heavy_check_mark:  _Default store view_



:heavy_check_mark:  _Second Website Store View_

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi, @ihor-sviziev can you please review test coverage?

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7924](https://jira.corp.magento.com/browse/ENGCOM-7924) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

**After:** heavy_check_mark Default store view

Screenshot from 2020-08-07 11-45-30

**After:** heavy_check_mark Second Website Store View

Screenshot from 2020-08-07 11-46-07

**Pull request merged**
