### PR TITLE
Fixed-Review-Details-Detailed-Rating-misaligned

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Fixed Issues (if relevant)

1. magento/magento2#20120: Review Details Detailed Rating misaligned
2. Magento 2.2.x

### Manual testing scenarios (*)

1. Go in Admin interface Marketing >> Reviews >> Review Details >> Detailed Rating
Rating stars are showing in-front of text
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by VladimirZaets** [comment]
Hi @amol2jcommerce. Please note that changes to 2.2-develop branch can be accepted only if these changes are present in the 2.3-develop branch (https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html). Please, create a pull request to the 2.3-develop branch and rename this one as backport.

**Comment by amol2jcommerce** [comment]
Hi @VladimirZaets 

Our pull request for 2.2-develop branch same changes are present in the 2.3-develop & pull request is #20132

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3903](https://jira.corp.magento.com/browse/ENGCOM-3903) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.

**Pull request merged**
