### PR TITLE
[Forwardport] 18858: Left Side Back End Menu Design fix 

### PR DESCRIPTION
**Pull request by suryakant-krish**
Original pull request: https://github.com/magento/magento2/pull/18858

### Description (*)

Fixed Left Side Back End Menu Design.

### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/18687: Forword Port Left Side Back End Menu Design fix

### Manual testing scenarios (*)

1. Added automatic scroll if the menu item is more.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [new Magento instance](https://pr-19560.instances.magento-community.engineering).
Admin access: [https://pr-19560.instances.magento-community.engineering/admin](https://pr-19560.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3636](https://jira.corp.magento.com/browse/ENGCOM-3636) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @suryakant-krish , there is a layout problem found by us while testing, please take a look at the close (cross) button:

image

Could the position of it be adjusted to the corner of the area?

**Comment by sidolov** [comment]
Hi @suryakant-krish , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
