### PR TITLE
Fix js errors in customer data when component not initialized

### LINKED ISSUE #31920: JS error in the customer data
Originally this issue was reported in https://github.com/magento/magento2/commit/5983e1733d56b1b2f15fb4f0e64094a3a4f3145d#commitcomment-44080850 by @HenKun.

The following commit https://github.com/magento/magento2/commit/5983e1733d56b1b2f15fb4f0e64094a3a4f3145d leads to similar issues described in https://github.com/magento/magento2/pull/24847.

### Preconditions (*)

1. Magento 2.4.1, or 2.4-develop

### Steps to reproduce (*)

1. Add the following code to the page on frontend:
```html
<script>
    require(['Magento_Customer/js/customer-data'], function (customerData) {
        console.log(customerData.getExpiredSectionNames());
    });
</script>
```
2. Go to the frontend, see the console

### Expected result (*)

1. In the console you should see an empty array, like this: 
image

### Actual result (*)

1. in the console we see the following error:
image

### Additional info from Engcom
Add the script to, for example, /app/code/Magento/Customer/view/frontend/templates/form/edit.phtml
script

1. In the Storefront, Sign In as a Customer
2. Go to _My Account_
3. Click **Edit** under _Contact Information_
4. Observe the dev console

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
This PR adds storage initialization with 1 day cookie lifetime (default value before https://github.com/magento/magento2/commit/6c5246a03d45e7f7a10c41fe857a96480142fc6c). Once the component initialized - the value for cookie lifetime is getting updated with new settings. 

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/31920

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Unit Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, WebAPI Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento run  Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Review by Den4ik — APPROVED** [review]
✅ Approved

Changes looks ok and work as expected

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9098](https://jira.corp.magento.com/browse/ENGCOM-9098) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by dmitriyprime** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
