### PR TITLE
added fix for the ticket #24210

### PR DESCRIPTION
**Pull request by sudheer-gajjala**
https://github.com/magento/magento2/issues/24210 this is the url of the issue

### Fixed Issues (if relevant)

1. magento/magento2#24210: Toggle functionality for admin menu

### Manual testing scenarios (*)

1. Go to Magento Admin
	Click on the Menu Item (Ex Reports) Menu opens
	Again click on the Menu Item (Ex	Reports) Menu closes
	
2. No need to click on the close button to close the Menu.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24211) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=24211) before we can accept your contribution.<br/><hr/>**Sudheer Kumar Gajjala** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Review by kanthy-i95dev — APPROVED** [review]

**Comment by ronak2ram** [comment]
@sudheer-gajjala  thank you for the fixes!
Could you please squash all commits into a single one in order to clean up history?

**Comment by sudheer-gajjala** [comment]
> @sudheer-gajjala thank you for the fixes!
> Could you please squash all commits into a single one in order to clean up history?
@ronak2ram completed squashing the commits.

**Comment by sudheer-gajjala** [comment]
squashed to this commit "added fix for the ticket #24210"  "fc87a57fffa759631f527be2831406779cc56f37"

**Review by ronak2ram — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ronak2ram, thank you for the review.
[ENGCOM-5695](https://jira.corp.magento.com/browse/ENGCOM-5695) has been created to process this Pull Request
:eight_spoked_asterisk: @ronak2ram, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@sudheer-gajjala thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by sudheer-gajjala** [comment]
@magento-engcom-team I am unable to sign "Contributor License Agreement" could you please help me in this.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
