### PR TITLE
[Backport] #6942 added check for page layout loaded from cache

### PR DESCRIPTION
**Pull request by mrIntegrator**
### Description
Under heavy traffic, some pages will become broken because the HTML `<head>` is not present. The only remedy is to disable layout cache.
When layout updates are loaded from cache, it's assumed that page layout will be loaded from cache as well. The problem is that when Redis reaches its maxmemory setting (as it might under heavy traffic), it will begin evicting keys. So if the page layout key is evicted while the layout key is not, the bug occurs. To fix this bug, we have to check for a successful load of both layout and page layout from the cache.

### Fixed Issues (if relevant)

1. magento/magento2#6942 (Title is wrong, but issue is real)

### Manual testing scenarios

1. Install Magento with Redis cache (I used db 0 for sessions, 1 for cache, 2 for FPC).
2. Navigate to a page not cached by FPC (I used customer/account/login).
3. Delete the page layout cache key in Redis. (Found by doing a var_dump of $cacheIdPageLayout in Magento\Framework\View\Model\Layout\Merge::load).
4. Refresh the page and behold the headlessness of your broken page.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### Original PR 
https://github.com/magento/magento2/pull/16428

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14129) <br/>All committers have signed the CLA.

**Comment by orlangur** [comment]
Hi @mrIntegrator, any changes should be applied to `2.2-develop` first: https://github.com/magento/magento2/blob/2.2-develop/lib/internal/Magento/Framework/View/Model/Layout/Merge.php#L433

Please create a separate PR and sign CLA.

**Comment by mrIntegrator** [comment]
Sorry about the confusion about the base branch. I had misread your comment. The 2.2-develop pull request has been created: https://github.com/magento/magento2/pull/16428. The only difference is in the integration test.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-2265](https://jira.corp.magento.com/browse/ENGCOM-2265) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@mrIntegrator thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by sidolov** [comment]
Hi @mrIntegrator , please, resolve merge conflict

**Comment by mrIntegrator** [comment]
Merge conflict resolved.

**Comment by ishakhsuvarov** [comment]
Hi @mrIntegrator 

Unfortunately, we can not accept this Pull Request to 2.1 release line, as it brings significant performance degradation. You may see attached file for the details.

We are closing this PR now, but you may continue working and improving the same submission for 2.2.

Thank you

[metrics-fail-degradation.log.txt](https://github.com/magento/magento2/files/2379634/metrics-fail-degradation.log.txt)

**Pull request closed without merging**
