### PR TITLE
Fix integer url key causing error in product import

### PR DESCRIPTION
**Pull request by robertsplorins**
### Description (*)

During product import, when checking duplicate URL keys, integer URL keys can potentially match to non-equal rows from url_rewrite table.

`SELECT * FROM url_rewrite WHERE request_path IN (5)` matches to request_path '5-test-product', which causes undefined index exception.

Query should be `SELECT * FROM url_rewrite WHERE request_path IN ('5')`. The change fixes this by converting all url keys to strings before passing them to where() function.

### Manual testing scenarios (*)

1. Create product with name '5 test product'
2. Import a product with url key '5', for example
[import_file.zip](https://github.com/magento/magento2/files/3550754/import_file.zip)
3. Error is shown: Notice: Undefined index: 5-test-product in /usr/src/app/vendor/magento/module-catalog-import-export/Model/Import/Product.php on line 2868
Screenshot 2019-08-28 at 15 09 28

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24338) <br/>All committers have signed the CLA.

**Comment by robertsplorins** [comment]
Hmm, test failing from code that was already there

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5735](https://jira.corp.magento.com/browse/ENGCOM-5735) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@robertsplorins thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
Hi @robertsplorins 

Unfortunately, I am not able to reproduce this issue providing by your steps on fresh 2.3-develop instance. All works correct. Could you please provide more details how to reproduce the problem?

Thanks!

**Comment by robertsplorins** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @robertsplorins. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @robertsplorins, here is your [Magento instance](https://i-24338-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24338-2-3-develop.instances.magento-community.engineering/admin](https://i-24338-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by robertsplorins** [comment]
Hmm, yes I cannot recreate it either

**Pull request closed without merging**
