### PR TITLE
magento/magento2#8871: Typo in Pull Request Template

### PR DESCRIPTION
**Pull request by tomislavsantek**
- Fixed the typo

### Description
Replaced occurrences of magetno with magento in the file PULL_REQUEST_TEMPLATE.md

### Fixed Issues (if relevant)
1. magento/magento2#8871: Typo in Pull Request Template

### Manual testing scenarios
1. check the file PULL_REQUEST_TEMPLATE for occurence of typo "magetno"

### CODE REVIEW

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=8908) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=8908) before we can accept your contribution.<br/>

**Comment by ishakhsuvarov** [comment]
Hi @tomislavsantek 
Please sign our Contributor License Agreement (CLA) so we can proceed with accepting your contribution.
Thanks!

**Comment by tomislavsantek** [comment]
@ishakhsuvarov CLA signed.

**Comment by ishakhsuvarov** [comment]
Hi @tomislavsantek
CLA check is still displayed as pending. Please make sure you have added your email address you used for the commit into github profile and try again.

Thank you!

**Comment by ishakhsuvarov** [comment]
@tomislavsantek Thank you for your contribution

**Pull request merged**
