### PR TITLE
MFTF: Replace fragile test `AdminLoginTest` with `AdminLoginSuccessfulTest`

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Verify that Admin is logged in successfully not by the URL, but by the User block in top right corner.

### Fixed Issues (if relevant)
1. Fragile tests when you change Admin Path or default dashboard page.

### Manual testing scenarios (*)
1. Run MFTF

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@okolesnyk I'd prefer to have own TestCaseID for the failure scenario if you have some?

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7081](https://jira.corp.magento.com/browse/ENGCOM-7081) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Charlie** [comment]
Failed functional tests not related to the changes in this PR.

**Pull request merged**
