### PR TITLE
Fix syntax error in .editorconfig, closes #37394

### LINKED ISSUE #37394: Space in editorconfig syntax breaks rule for [{composer,auth}.json]
### Preconditions and environment

- Magento version any version after commit -> https://github.com/magento/magento2/commit/c722790487631c0ce78d753d2dfe9d97c7606a18
- Anything else that would help a developer reproduce the bug, simple test the editorconfig in your IDEA or code editor that support the editorconfig

### Steps to reproduce

1. Open your editor, that supports the editorconfig.
2. View the composer or auth json file
3. See what the indent is for the composer and auth.json
4. See that configured size is now 2 instead of 4
5. Remove the space in the editorconfig for `[{composer, auth}.json]` to `[{composer,auth}.json]`
6. See that configured size is now 4 as intended

### Expected result

The composer and auth should have a indent of 4 spaces

### Actual result

It only has 2 spaces

### Additional information

_No response_

### Release note

Fix syntax error in editorconfig

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by GrimLink**
### Description (*)

This fixes the issue #37394 for the synatx error in the editorconfig

### Fixed Issues (if relevant)

1. Fixes magento/magento2#37394

### Manual testing scenarios (*)

1. Open your editor, that supports the editorconfig.
2. View the composer or auth json file
3. See what the indent is for the composer and auth.json
4. See that configured size is now 4 instead of 2

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by GrimLink** [comment]
@magento run all tests

**Review by fredden — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE

**Comment by engcom-Lima** [comment]
Hi @GrimLink ,

Thanks for your contribution and collaboration.

Kindly provide us more information asked in the [comment](https://github.com/magento/magento2/issues/37394#issuecomment-1517241149).

Thanks

**Comment by fredden** [comment]
@magento run Functional Tests B2B

**Comment by GrimLink** [comment]
https://github.com/magento run all tests

**Comment by GrimLink** [comment]
@magento run all tests

**Comment by GrimLink** [comment]
@fredden & @engcom-Lima what is the status on the review of this pull-request?

**Comment by fredden** [comment]
@GrimLink this pull request currently has the label of "Progress: ready for testing" which means that Adobe staff will pick this up and carry out functional testing. I don't know when that will happen.

**Comment by GrimLink** [comment]
Okay thanks @fredden

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
✔️ QA Passed
Fix syntax error in .editorconfig, closes

as there are build failure moving it to `Extended Testing`

**Comment by engcom-Echo** [comment]
@magento run Integration Tests,WebAPI Tests,Functional Tests B2B

**Pull request merged**
