### PR TITLE
Fixed #22052 Customer account confirmation is overwritten by backend customer save

### LINKED ISSUE #22052: Customer account confirmation is overwritten by backend customer save
### Preconditions (*)

1. Clean Magento setup 2.3.1
2. Set the account confirmation to **"Yes"** by visiting store > configuration > Customers > Customer Configuration > Create New Account Options > Require Emails Confirmation 

cuonfig

### Steps to reproduce (*)

1. Create a new customer account on frontend by visiting "Create a new account" link from header
2. Open Magento backend with valid credentials
3. Go to Customer > All Customers
4. Open the newly created customer and please notice the value of "Confirmed email:" is "Confirmation Required"
5. Now click on "Save and continue"
6. Now Please notice the value of "Confirmed email:" is "Confirmed"

**Customer account while opening customer**
require

**After saving customer**

confirm

### Expected result (*)

1. Customer account should confirm by email link not from by saving customer from backend

### Actual result (*)

1. Customer account is getting confirmed even customer did not click on email activation link

### PR DESCRIPTION
**Pull request by shikhamis11**
Fixed #22052 Customer account confirmation is overwritten by backend customer save

### Preconditions (*)

1. Clean Magento setup 2.3.1
2. Set the account confirmation to **"Yes"** by visiting store > configuration > Customers > Customer Configuration > Create New Account Options > Require Emails Confirmation 

cuonfig

### Steps to reproduce (*)

1. Create a new customer account on frontend by visiting "Create a new account" link from header
2. Open Magento backend with valid credentials
3. Go to Customer > All Customers
4. Open the newly created customer and please notice the value of "Confirmed email:" is "Confirmation Required"
5. Now click on "Save and continue"
6. Now Please notice the value of "Confirmed email:" is "Confirmed"

**Customer account while opening customer**
require

**After saving customer**

confirm

### Expected result (*)

1. Customer account should confirm by email link not from by saving customer from backend

### Actual result (*)

1. Customer account is getting confirmed even customer did not click on email activation link

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-22147.instances.magento-community.engineering).
Admin access: [https://pr-22147.instances.magento-community.engineering/admin](https://pr-22147.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by dmytro-ch** [comment]
Hi @shikhamis11,
thank you for your contribution!

There is a unit test failure with the current solution.
```
Magento\Customer\Test\Unit\Model\Customer\DataProviderWithDefaultAddressesTest::testGetData
```
Could you please update it?

Thank you.

**Comment by swnsma** [comment]
May be related #21394

**Comment by shikhamis11** [comment]
Hi @swnsma 
Thanks for your update . I checked that PR doesn't fix the current issue .

**Comment by shikhamis11** [comment]
@dmytro-ch I have fixed unit test failure Please check

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4678](https://jira.corp.magento.com/browse/ENGCOM-4678) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
