### PR TITLE
[Typo] Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by 4quaternion**
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15857) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=15857) before we can accept your contribution.<br/>

**Comment by okorshenko** [comment]
Hi @DanielRuf please don't close this one. I'm working on it. Testing new feature for contributor assistance

**Comment by magento-engcom-team** [comment]
Hi @4quaternion
Thank you for your contribution. This pull request has been combined (merged) with https://github.com/magento/magento2/pull/16197 to optimize pull requests queue on magento/magento2 repository
Closing this pull request.

**Comment by magento-engcom-team** [comment]
Hi @4quaternion
Thank you for your contribution. This pull request has been combined (merged) with https://github.com/magento/magento2/pull/16233 to optimize pull requests queue on magento/magento2 repository
Closing this pull request.

**Pull request closed without merging**
