### PR TITLE
FIX: blocky moving inside magnifier

### LINKED ISSUE #29076: Gallery inside magnifier moves blocky
### Preconditions (*)

The magnifier moves only when the cursor is leaving the magnifier area.
Causing a blocky movement.
This behavior only happens to the magnifier when the mode option is set to inside.

_Tested on a clean Magento 2.3.5 version._

### Steps to reproduce (*)

In the view.xml for any theme.
Enable the magnifier and set the mode to inside.

```xml
<var name="magnifier">
  <var name="enabled">true</var> <!-- Turn on/off magnifier (true/false) -->
  <var name="mode">inside</var> <!-- Zoom type (outside/inside) -->
</var>
```

### Expected result (*)

A smooth movement.
Where the magnifier moves with the mouse cursor.

Screen Recording 2020-07-10 at 22 15 23

### Actual result (*)

Blocky movement as seen on this image.

Screen Recording 2020-07-10 at 22 18 18

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by GrimLink**
### Description (*)

This fixes the blocky movement when using the magnifier with the mode set to inside.
The move function is part of and if statement where 1 of the conditions was only for the magnifier mode outside.

This bug was created in the [commit 3d34a3c](https://github.com/magento/magento2/commit/3d34a3c74d78929d76bdaa3944b6e371be147d09)

### Related Pull Requests

_None_

### Fixed Issues (if relevant)

Fixes magento/magento2#29076.

### Manual testing scenarios (*)

1. Copy the `lib/web/magnifier/magnifier.js` to you theme
2. Change the if statement found on line number 580

from:
  ```js
  if (inBounds && isOverThumb && gMode === 'outside') {
       $magnifierPreview.removeClass(MagnifyCls.magnifyHidden);
       move();
   }
  ```
to:
  ```js
  if (inBounds && isOverThumb) {
       if (gMode === 'outside') {
           $magnifierPreview.removeClass(MagnifyCls.magnifyHidden);
       }
       move();
   }
  ```

### Questions or comments

_None_

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by GrimLink** [comment]
@magento run all tests

**Comment by ptylek** [comment]
Seems that failing functional tests are not related to this PR. Nice find. Has to be tested manually.

**Review by ptylek — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-7826](https://jira.corp.magento.com/browse/ENGCOM-7826) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Magento 2.4-develop;
2. Sample Data;

**Manual testing scenario:**

1. In the **view.xml** for any theme. ( **_luma_** in this case)
`app/design/frontend/Magento/luma/etc/view.xml`
Enable the magnifier and set the mode to inside.

```xml
<var name="magnifier">
  <var name="enabled">true</var> <!-- Turn on/off magnifier (true/false) -->
  <var name="mode">inside</var> <!-- Zoom type (outside/inside) -->
</var>
```
2. Clean cache;
3. Go to any product page in Storefront;

**Before:** :heavy_multiplication_x: Blocky movement as seen on this image.

Peek 2020-07-14 12-55

**After:** :heavy_check_mark: A smooth movement.
Where the magnifier moves with the mouse cursor.

Peek 2020-07-14 13-14

Checked and on the **Blank** theme:

Actual Result: :heavy_check_mark: A smooth movement.

Peek 2020-07-14 13-40

Also, was checked if the mode is outside:

```xml
<var name="magnifier">
  <var name="enabled">true</var> <!-- Turn on/off magnifier (true/false) -->
  <var name="mode">outside</var> <!-- Zoom type (outside/inside) -->
</var>
```
Actual Result: :heavy_check_mark: A smooth movement.

Peek 2020-07-14 13-23

**Pull request merged**
