### PR TITLE
Fotorama gallery styles moved from lib/web to Blank theme

### PR DESCRIPTION
**Pull request by Igloczek**
`lib/web` directory seems to not be the best place to keep non-vendor code related only to frontend themes (it's the same story as `js` directory in M1 which contains everything and developers were scary to touch it), because it's not possible to change any styles on theme level and developers need to create dummy modules to overwrite styles or manually move all code to own theme.

It will be a breaking change for themes that use Fotorama gallery, but are not children of Blank theme.

---

It's exactly same PR as #11384, b/c it was closed due to misunderstanding. These changes are not related to failing JS unit tests, b/c I changed only styles and tests were failing also on develop branch.

### CODE REVIEW

**Comment by omiroshnichenko** [comment]
Hi, @Igloczek. I think, better to move this files not into app/design/frontend/Magento/blank/Magento_Catalog directory, but into app/design/frontend/Magento/blank/web. Because, someone can use gallery not only on catalog page.

**Comment by Igloczek** [comment]
@omiroshnichenko I'd suggest `Magento_Theme` instead, since this should be a place for things related to the whole theme.
At least from my point of view, the root `web` directory should be empty and things like `lib/web` shouldn't exist, b/c everything should be a module, "global scope" should be used only to combine all necessary stuff together.

**Comment by Igloczek** [comment]
Everything moved to `Magento_Theme`.
I had to wrap all styles into media queries, that's why there are more changes than before.

**Review by omiroshnichenko — APPROVED** [review]

**Comment by omiroshnichenko** [comment]
@Igloczek 
**Problems**: Broken storefront gallery on product page.

**Steps to reproduce**:

1. Create Configurable Product Conf1:
    - with unique image C1 as a base, unique image C2 & unique video C3 assigned
    - variations are based on "Visual Swatch" attribute:
        - variation B1 has unique image D1 as a base, unique image D2 & unique video D3 assigned
        - variation B2 has no media assigned
        - variation B3 has unique video E1 as a base, unique image E2 & unique video E3 assigned
2. Open Product Conf1 on Storefront

**Result**: Gallery styles is broken

**Comment by Igloczek** [comment]
I'll try to check this out, but please do not close it after 14 days, I'm kinda busy.

But at all this issue seems to be very strange according to my changes or is just possible to reproduce also on develop. I can't imagine how moving styles can break it...

**Comment by VladimirZaets** [comment]
Hi @Igloczek , I try to reproduce the scenario that was described by @omiroshnichenko. This scenario is reproduced and after the brief investigation, I remarked that styles from `_gallery.less` are not included. So, I think the problem with including `_gallery.less` to `_module.less`.

**Comment by VladimirZaets** [comment]
Hi @Igloczek  , any updates?

**Comment by Igloczek** [comment]
@VladimirZaets I'm on vacations now, will back to this in about two weeks.

**Comment by VladimirZaets** [comment]
@Igloczek ok, thanks

**Comment by VladimirZaets** [comment]
@Igloczek , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Pull request closed without merging**
