### PR TITLE
fix: Multishipping correct location of subtotal (excl tax) in order review page

### LINKED ISSUE #35477: Multishipping subtotal (Excl. Tax) is not displayed in the order review page
### Preconditions (*)

1. Magento 2.4.2

### Steps to reproduce (*)

1. Admin - Stores - Configuration - Sales - Tax - Set Price Display settings and Shopping cart display settings to - Including and excluding tax. Save
image
2.  Clear cache and login to Front end - Add multiple addresses
3. Add two items to cart.
image
3. Go to shopping cart page - Click on 'Checkout with Multiple Addresses'
4. Follow steps to the order review page

### Expected result (*)

image

### Actual result (*)

 image

The subtotal (Excl. Tax) is not correctly displayed, it is shifted from its place

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by mohaelmrabet**
### Description (*)

Correct location of subtotal (excl tax) in order review page

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35477

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mimou78** [comment]
@magento give me test instance

**Comment by mimou78** [comment]
@magento run all tests

**Comment by mimou78** [comment]
@magento run Functional Tests CE

**Comment by manavluhar** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by mimou78** [comment]
@magento run  Functional Tests EE

**Comment by mimou78** [comment]
@magento run all tests

**Pull request closed without merging**
