### PR TITLE
Resolve "Automatically Invoice All Items" is "Yes" but no invoice is created (Zero Subtotal Checkout)

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

magento/magento2#23211: Resolve "Automatically Invoice All Items" is "Yes" but no invoice is created (Zero Subtotal Checkout)

Solution: the default value display at the admin is "Yes" but actually, it have the value null. 
Fix by:  Need to set the default value match to the label 'yes' in config.xml (value = 'authorize_capture')

### Fixed Issues (if relevant)

1. magento/magento2#23211: Zero Subtotal Checkout erroneously says the default value for "Automatically Invoice All Items" is "Yes"
### Manual testing scenarios (*)

Cart Price rule that discounts products and shipping to 100% (use coupon code "FREE" to make life easier)
In Configuration for "Zero Subtotal Checkout", uncheck "Use system value" for "New Order Status" and set to "Processing"
NOTE but do not change "Automatically Invoice All Items." It should be readonly and should say "Yes". "Use system value" checkbox beside it should be checked.

1. On storefront, check out order with FREE coupon to make order $0
2. In admin panel, view the order just created and click on the Invoices tab
3. An invoice appears in the Invoice grid (backend)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-23688.instances.magento-community.engineering).
Admin access: [https://pr-23688.instances.magento-community.engineering/admin](https://pr-23688.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by Stepa4man — APPROVED** [review]
@edenduong, hi! Thanks for your contribution!

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, thank you for the review.
[ENGCOM-5443](https://jira.corp.magento.com/browse/ENGCOM-5443) has been created to process this Pull Request
:eight_spoked_asterisk: @Stepa4man, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@edenduong thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by Hav7979** [comment]
I have ver 2.3.6 and the option is not showing?

**Pull request merged**
