### PR TITLE
Update Persistor.php

### PR DESCRIPTION
**Pull request by Maddesto**
database persistor fix

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@Maddesto could you describe what issue are you going to fix with your changes?

**Comment by Maddesto** [comment]
My issue is fixing repository generator, arrays can be passed to array_flip function not by reference, currently $tempStack array will not be changed after applying array_flip

**Comment by ihor-sviziev** [comment]
@Maddesto unfortunately it still not clear what the issue are you facing, as result - I can't agree or disagree with your solution. Could you add steps to reproduce, actual and expected result?

**Comment by Maddesto** [comment]
please, see my code changes, it should be clear, what my code is doing

**Comment by ihor-sviziev** [comment]
@Maddesto I see what your code is doing, but it not clear what the **issue** have you had.

**Pull request closed without merging**
