### PR TITLE
Rework for PR #16222 .

### PR DESCRIPTION
**Pull request by phoenix128**
### Description
When running 'app:config:dump', admin fields get disabled, but clicking save from backend will process them anyway.
This behaivour causes a validation check on empty fields since the admin form fields are disabled and thus validation errors in many cases.

This PR checks when the field is read only and skips its save.

This is a more complete rework for PR https://github.com/magento/magento2/pull/16222 .

### Manual testing scenarios
1. Go to `Stores -> Configuration -> General -> Currency Setup`
2. Setup `Base Currency`, `Default Display Currency` and `Allowed Currencies` to whatever you like
3. Save
4. Run `bin/magento app:config:dump`
5. Go back to admin and refresh the page (fields are disabled).
6. Click on save
7. As result no errors should be displayed

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @phoenix128. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by bmxmale — APPROVED** [review]

**Comment by bmxmale** [comment]
I have checked your fix. It's working as expected. Thx for fast response :+1:

**Review by orlangur — APPROVED** [review]
LGTM 👍

**Comment by magento-engcom-team** [comment]
Hi @phoenix128. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.6. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
