### PR TITLE
magento/magento2#19071: Password strength indicator shows No Password…

### PR DESCRIPTION
**Pull request by dimasalamatov**
… even when a password is entered

### Description (*)

The password strength indicator shows "No Password" at times when there is a password entered and "Number of Required Character Classes" option has value "1". There is an situation when zxcvbn() method returns 0 score value and password is valid. In this case displayScore variable will be 0 and as result text "Password Strength: No Password" is visible despite the fact that "Password" field is filled.
Added additional condition that checks if zxcvbn() returns 0 and pass is valid, then  displayScore = 1 and 
"Password Strength: Weak"

Link to the same PR for 2.3-develop : https://github.com/magento/magento2/pull/19087

### Manual testing scenarios (*)

1. Goto AdminPanel->Stores->Configuration->Customers->Customer Configuration->Password Options
2. Set "Number of Required Character Classes" to 1
3. Go to "Create account" page
4. Type to "Password" field any words which have 8 lowercase letters like "password", "aaaaaaaa", etc
5. Check that "Password Strength:" not equal "No Password" in this case

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @dimasalamatov. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by sidolov** [comment]
Hi @dimasalamatov  , please, sign CLA, otherwise, we can't process your pull request

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](http://34.228.235.121/i-19073-2-3-develop/).
Admin access: [http://34.228.235.121/i-19073-2-3-develop//admin](http://34.228.235.121/i-19073-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rogyar** [comment]
Hi @dimasalamatov. Thank you for the contribution. According to the Code Contributions Guideline (https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#rules) we can accept the change to 2.2-develop branch only if it's present in 2.3-develop branch.
The issue is also reproducible on 2.3-develop branch. Please, consider creating the same PR for 2.3-develop branch and leave the reference to the newly created PR here (in the description).
Thank you.

**Comment by dimasalamatov** [comment]
Hi @rogyar 
Created PR with this fix for 2.3-develop branch. Added link to this PR in description

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3404](https://jira.corp.magento.com/browse/ENGCOM-3404) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @dimasalamatov. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

**Pull request merged**
