### PR TITLE
Changing Shipping Address does not change Billing Address at Checkout

### PR DESCRIPTION
**Pull request by neeta-wagento**
### Description

Go through the checkout as the guest user, on the second page of checkout, click the pencil to edit the shipping address, make changes on the shipping address, go to the second page, the billing address does not change unless you check the "My billing and shipping address are the same"

### Fixed Issues (if relevant)

1. magento/magento2#<12184>
2. Changing Shipping Address does NOT change Billing Address at Checkout #12184

### Manual testing scenarios

For reproduce the issue please follow the steps

1. Add Product to cart 
2. Go to Checkout s guest user 
3. Enter Shipping Address and Select Shipping Method and click on Next.
4. Right Side you can see the **Ship To** Heading and click the pencil to edit the shipping address, make changes on the shipping address, go to the second page, 

You can see that  the billing address does not change where as **Ship To** section is visible perfect

Please Refer the below Screen shots for Actual and Expected Result.

Expected result
Billing Address must be change as we edit the Shipping Address Using Ship To edit section.

Current Result:
checkout-billing-actual-result

Expected Result
checkout-billing-expected-result

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by sidolov** [comment]
Hi, it's expected behavior for billing address.
When you proceed to payment step billing address will be the same as shipping and saved in quote. So, if you go back to shipping step and change address, it will be different then already saved billing address and checkbox will be unchecked.

**Comment by neeta-wagento** [comment]
Hello @sidolov :  As we are editing address it should automatically applied to billing address. As user has to check once again on checkbox which increase user click  to apply the changes on Billing Address.

**Comment by sidolov** [comment]
@neeta-wagento, this behavior obvious and it's ok that customer must verify his billing address and click on checkbox once again if billing address must be as shipping. Customer may not expect to get his billing address changed automatically, we do not consider this to be a good UX pattern.
Also provided fix may affect scenario with virtual product when shipping address is absent.

**Comment by okorshenko** [comment]
Hi @neeta-wagento thank you for your contribution.
Unfortunately, we can not accept this pull request. @sidolov thank you for the investigation

**Pull request closed without merging**
