### PR TITLE
Update indexer.php

### PR DESCRIPTION
**Pull request by sebastian-ehrling**
Error in SQL Statement. By Using the mysql "in" statement in line 139 in table eav_attribute_option_value you will to much entries.

For Example
SELECT `t`.`option_id`, `t`.`value` FROM `eav_attribute_option_value` AS `t` 
WHERE (t.option_id IN ('45-683443')
);

RESULT:
option_id, value
45,TEXTVALUE
45,TEXTVALUE

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=12895) <br/>All committers have signed the CLA.

**Comment by miguelbalparda** [comment]
@ehrling thanks for your submission! Can you please edit the description of the PR and use the [template](https://github.com/magento/magento2/blob/2.2-develop/.github/PULL_REQUEST_TEMPLATE.md)?
Thanks!

**Comment by adrian-martinez-interactiv4** [comment]
Hi @ehrling , as @miguelbalparda said, thanks for your submission. We need more details to reproduce the issue and check if proposed solution is a valid one, if you can edit the description using the template linked in previous commit, it would be very useful for us.

Additionally, Travis is failing due to static tests:
```
PHP Code Sniffer has found 3 error(s): 
FILE: .../app/code/Magento/Catalog/Model/Indexer/Product/Flat/Action/Indexer.php
--------------------------------------------------------------------------------
FOUND 3 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 143 | ERROR | Expected "if (...) {\n"; found "if(...){\n"
 143 | ERROR | Expected 0 spaces after opening bracket; 1 found
 143 | ERROR | Expected 0 spaces before closing bracket; 1 found
--------------------------------------------------------------------------------
```

**Review by sebastian-ehrling — COMMENTED** [review]
remove spaces

**Comment by sidolov** [comment]
@ehrling , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration!

**Pull request closed without merging**
