### PR TITLE
[update] enhance performance on large catalog

### PR DESCRIPTION
**Pull request by AurelienLavorel**
### Description
On Magento update, if you have a big number of order (>100k for my case), you can't pass *setup:upgrade* step.
Instead of using Magento collection, it's a direct SQL request.
### Manual testing scenarios
Upgrade Magento from 2.2.2 to 2.2.5.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @AurelienLavorel. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by AurelienLavorel** [comment]
@magento-engcom-team ?

**Comment by ihor-sviziev** [comment]
Related Pull Request:
https://github.com/magento/magento2/pull/15097

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-2596](https://jira.corp.magento.com/browse/ENGCOM-2596) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
Result query will be following:
```sql
UPDATE sales_order_address
INNER JOIN sales_order ON sales_order_address.parent_id = sales_order.entity_id
INNER JOIN quote_address ON sales_order.quote_id = quote_address.quote_id
                            AND sales_order_address.address_type = quote_address.address_type
SET sales_order_address.quote_address_id = quote_address.address_id
WHERE sales_order_address.quote_address_id IS NULL
```

**Comment by magento-engcom-team** [comment]
Hi @AurelienLavorel. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Comment by rikwillems** [comment]
@magento-engcom-team this patch won't work with Enterprise Edition with split database setup.

**Comment by ihor-sviziev** [comment]
Hi @rikwillems,
Thank you for your feedback! I asked @engcom-backlog-nazar to re-check it.

**Comment by ihor-sviziev** [comment]
Hi @AurelienLavorel,
We verified issue reported by @rikwillems and actually change from this PR failing in Magento Commerce installation with split database setup.
image

In such configuration we have 2 split databases 
- quotes are located in "checkout" connection. Example:
https://github.com/magento/magento2/blob/a08f37830ac22ad5139e5a4a5586e67a8b10d7ff/app/code/Magento/Quote/Setup/UpgradeSchema.php#L21
https://github.com/magento/magento2/blob/a08f37830ac22ad5139e5a4a5586e67a8b10d7ff/app/code/Magento/Quote/Setup/UpgradeSchema.php#L130-L147
- Orders and addresssed are located in "sales" connection. Example:
https://github.com/magento/magento2/blob/a08f37830ac22ad5139e5a4a5586e67a8b10d7ff/app/code/Magento/Sales/Setup/UpgradeSchema.php#L20
https://github.com/magento/magento2/blob/a08f37830ac22ad5139e5a4a5586e67a8b10d7ff/app/code/Magento/Sales/Setup/UpgradeSchema.php#L154-L163

Could you prepare new PR that fixing this issue OR revert your changes?

**Comment by AurelienLavorel** [comment]
Yes, I'm mounting an environment with that set up to try.

**Comment by ihor-sviziev** [comment]
Hi @AurelienLavorel,
Thank you for working on it!

**Comment by rikwillems** [comment]
@ihor-sviziev Please see my PR as a fix for this issue.

**Pull request merged**
