### PR TITLE
Replace strval() function by using direct type casting to (string)

### PR DESCRIPTION
**Pull request by mage2pratik**
### Description

Direct type casting is **up to 6x faster** than using casting functions like `strval()`. So this pull request replaces the `strval()` functions by direct type casting to `(string)`.
### Fixed Issues (if relevant)

1. magento/magento2#16849: Replace strval() function by using direct type casting to (string)

### Manual testing scenarios

N/A

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sidolov** [comment]
@magento-engcom-team combine 17671

**Comment by magento-engcom-team** [comment]
Hi @sidolov. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
@mage2pratik all pull requests have been successfully combined together: 
 - merged https://github.com/magento/magento2/pull/17671: Fixed a couple of spelling mistakes

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Pull request merged**
