### PR TITLE
Add Concept of Numbers to camelCaseToSnakeCase

### PR DESCRIPTION
**Pull request by antbates91**
### Fixed Issues (if relevant)

1. magento/magento2#25490: Magento\Framework\Api\SimpleDataObjectConverter->camelCaseToSnakeCase has no concept of numbers 

### Manual testing scenarios (*)

1. Create a method for an object that contains a number at the end of the method name for example `getMondayWeek1`. This resolves to a db field `monday_week_1`.
2. Call `Magento\Framework\Api\ExtensibleDataObjectConverter`'s `toNestedArray` function passing in the interface data, and the data model.
3. Check the output of array properties after this method has executed
4. Property is correct as `monday_week_1`.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ronak2ram — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ronak2ram, thank you for the review.
[ENGCOM-6241](https://jira.corp.magento.com/browse/ENGCOM-6241) has been created to process this Pull Request
:eight_spoked_asterisk: @ronak2ram, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@antbates1991 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by antbates91** [comment]
@magento-engcom-team I can't accept that invitation, I guess this is because I am still part of the `Partner-JH` Team. You can remove me from that team as I no longer work for this partner.

**Comment by engcom-Bravo** [comment]
Hello, @antbates1991. Thank You for contribution. In order we can further process Your PR please cover it with the appropriate Auto-Tests.

**Comment by VladimirZaets** [comment]
@antbates1991, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Pull request closed without merging**
