### PR TITLE
[Search] Unit test for SynonymAnalyzer model

### PR DESCRIPTION
**Pull request by furseyev**
### Description

A phpunit test for the \Magento\Search\Model\SynonymAnalyzer class added

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @furseyev. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by furseyev** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @furseyev. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @furseyev, here is your [new Magento instance](https://pr-17801.engcom.dev.magento.com).
Admin access: [https://pr-17801.engcom.dev.magento.com/admin](https://pr-17801.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-2876](https://jira.corp.magento.com/browse/ENGCOM-2876) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @furseyev. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
