### PR TITLE
[MultiShipping CustomPrice] #31301 - Add custom price for quote addre…

### LINKED ISSUE #31301: [Multishipping] Custom Price issue
### Preconditions (*)

1. Magento version CE 2.3.6

### Steps to reproduce (*)

I don't know how reproduce natively with Luma Theme, but here the conditions to reproduce with few developments
1. Having Multi Shipping enabled
2. Having the One Page Checkout disabled
3. Add a simple product to cart
4. Having a development which sets a custom price and an original custom price to the quote item
5. Go to the Checkout

### Expected result (*)

1. The custom price set to the quote item is used for the quote address item. 

### Actual result (*)

1. [Screenshots, logs or description]
screenshot-magento-ce-2-3 lxc-2020 12 16-12_09_13
screenshot-magento-ce-2-3 lxc-2020 12 16-12_09_58
The custom price of the quote item is not used when the multi shipping is enabled. Everything works well when it is disabled.

### Solution
The issue is the following: in this case, we have:
vendor/magento/module-quote/Model/Quote/Address/Total/Subtotal.php l90 $item is an instanceof AddressItem, so we give a quote address item to vendor/magento/module-quote/Model/Quote/Address/Total/Subtotal.php::_calculateRowTotal . Then in vendor/magento/module-quote/Model/Quote/Item/AbstractItem.php::getCalculationPriceOriginal we don't have the original_custom_price data because it does not exist for quote address item.

The solution could be to add custom_price and original_custom_price to the table quote_address_item and 
edit the method vendor/magento/module-quote/Model/Quote/Address/Item.php::importQuoteItem to set the custom price of the quote item.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by PierreLeMaguer**
…ss item

### Description (*)

Add custom price fields to quote address item.

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/31301

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by PierreLeMaguer** [comment]
@magento run all tests

**Comment by PierreLeMaguer** [comment]
Is it possible to add the label 'Partner: Smile' ?

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @PierreLeMaguer,

Thanks for the contribution!

Code changes seem good the me. Please add some automated tests to cover the changes.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @PierreLeMaguer,

Thanks for the contribution!

We had a discussion internally on this PR and found that there are some Backward incompatibility changes are there as we are trying to create new columns via this PR.

I would like to suggest you use a different approach to fix this issue.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @PierreLeMaguer,

Have you got a chance to check this [comment](https://github.com/magento/magento2/pull/31309#pullrequestreview-1608878212)?

Thanks

**Comment by engcom-Hotel** [comment]
Hello @PierreLeMaguer,

Thank you for your contribution!

As we have been unable to get any reply from your side for a long time, we are closing this PR for now. 

Whenever you are ready to take this up please free to reopen it or ask us to reopen the same. We will be happy to do that.

Thanks again!

**Pull request closed without merging**
