### PR TITLE
Fix mistake in stale.yml file formatting

### PR DESCRIPTION
**Pull request by sdzhepa**
### Description (*)
Removed additional space symbol from https://github.com/magento/magento2/blob/2.4-develop/.github/stale.yml#L4
Due to this mistake, stale bot could not be able to read/parce yaml file

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sdzhepa** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-8357](https://jira.corp.magento.com/browse/ENGCOM-8357) has been created to process this Pull Request

**Review by sivaschenko — DISMISSED** [review]

**Comment by ihor-sviziev** [comment]
Just in case
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-8357](https://jira.corp.magento.com/browse/ENGCOM-8357) has been created to process this Pull Request

**Comment by sdzhepa** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Pull request merged**
