### PR TITLE
[TASK] Fixed undefined shipping method name in checkout summary

### PR DESCRIPTION
**Pull request by basvanpoppel**
### Description (*)

In checkout on the last step, the shipping method is displayed as 'undefined' when no name is set. The code in this PR makes sure the name is only displayed when it's defined.

There is a merged PR related to this, which didn't solve the issue completely (https://github.com/magento/magento2/pull/17697)

### Fixed Issues (if relevant)

1. magento/magento2#17492: "- undefined" displayed in checkout summary when shipping method name is not set

### Manual testing scenarios (*)

1. Add new or edit any existing shipping methods with Method name field left as a blank field.
2. Add any product to the cart and go through the checkout to the last step.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22365) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=22365) before we can accept your contribution.<br/><hr/>**Bas van Poppel** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Review by orlangur — CHANGES_REQUESTED** [review]
@basvanpoppel it is not a good idea to duplicate this code, please refactor.

**Review by Jensderond — COMMENTED** [review]
Using a dot notation for the objects makes the code easier to read.
See: https://eslint.org/docs/2.0.0/rules/dot-notation

**Comment by basvanpoppel** [comment]
> @basvanpoppel it is not a good idea to duplicate this code, please refactor.

Thank you for the reply, i will make a new commit later this week. I'm a bit uncertain about 'refactoring, but I have an idea what the best approach should be. 
For now I'm using this commit as a patch for current project - as it does fix the issue for all our Magento2 installations.

**Comment by orlangur** [comment]
@basvanpoppel basically we need one implementation used in two places: place with the old fix and the new one you performed.

**Comment by sidolov** [comment]
@basvanpoppel , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
