### PR TITLE
Binding to event collapsible scroll

### PR DESCRIPTION
**Pull request by danielgheoltan**
### Description (*)

The PDP description/reviews accordion in mobile is designed to jump to top of screen when user clicks on accordion anchor to open content (but necessarily to not top of accordion wrapper). This seems to only occur with phones using iOS.

### Manual testing scenarios (*)

Open pdp on mobile phone. http://mydomain.coma/impulse-duffle.html
Scroll down so that "More Information" is at the top of the phone screen and click on "More Information" accordion anchor.
Notice that the text is not shown on the screen and you need to scroll up to see it

EXPECTED RESULTS:
The text given when clicking on the "More Information" accordion anchor is able to be seen on the phone screen without having to scroll back up

ACTUAL RESULTS:
The text given when clicking on the "More Information" accordion anchor is unable to be seen on the phone screen and you need to scroll back up.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18609) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18609) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
Hi @danielgheoltan. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by danielgheoltan** [comment]
@cpartica helped with this one.

**Comment by miguelbalparda** [comment]
Hi @danielgheoltan! Can you please sign the CLA so we can process this? Thanks!!

**Comment by danielgheoltan** [comment]
@miguelbalparda I signed the CLA.

**Comment by slavvka** [comment]
@danielgheoltan no, you didn't sign the CLA. Please refer to the checks block in the end. You could also do that by clicking the link https://cla.dev.magento.com/magento/magento2?pullRequest=18609

**Comment by miguelbalparda** [comment]
@danielgheoltan any chance you can sign the CLA so we can process this? Thanks!

**Comment by danielgheoltan** [comment]
@miguelbalparda I signed again the CLA. I don't know what's wrong with the CLA.

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-3510](https://jira.corp.magento.com/browse/ENGCOM-3510) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@danielgheoltan thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @danielgheoltan. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
