### PR TITLE
#20755: Fix the cms page top spacing issue at mobile.

### PR DESCRIPTION
**Pull request by gauravkhatri99**
Issue was to fix the cms page top spacing issue at mobile. The issue Id is #20755.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21024) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @gauravkhatri99. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by dmytro-ch** [comment]
Hi @gauravkhatri99,
thank you for your contribution!
The PR for `2.3-develop` has been already created.
Closing this PR as a duplicate.

**Comment by amol2jcommerce** [comment]
Hi @gauravkhatri99 PR already created #20756

**Pull request closed without merging**
