### PR TITLE
PhpUnit 8 Migration - Amqp

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
This PR updates unit tests in Amqp module + contains framework fix from https://github.com/magento/magento2/pull/27519

Note: 
We have 3 warnings that can't be fixed because these new methods doesn't exists in phpunit 6:
```
1) Magento\Amqp\Test\Unit\Setup\ConfigOptionsListTest::testCreateConfig with data set #0 (array('host', 'port', 'user', 'password', 'virtual host', 'ssl', '{"ssl_option":"test"}'), array(array(array('host', 'port', 'user', 'password', 'virtual host', 'ssl', array('test')))))
assertInternalType() is deprecated and will be removed in PHPUnit 9. Refactor your test to use assertIsArray(), assertIsBool(), assertIsFloat(), assertIsInt(), assertIsNumeric(), assertIsObject(), assertIsResource(), assertIsString(), assertIsScalar(), assertIsCallable(), or assertIsIterable() instead.

2) Magento\Amqp\Test\Unit\Setup\ConfigOptionsListTest::testCreateConfig with data set #1 (array('host', '5672', 'user', 'password', 'virtual host', 'ssl', '{"ssl_option":"test"}'), array(array(array('host', '5672', 'user', 'password', 'virtual host', 'ssl', array('test')))))
assertInternalType() is deprecated and will be removed in PHPUnit 9. Refactor your test to use assertIsArray(), assertIsBool(), assertIsFloat(), assertIsInt(), assertIsNumeric(), assertIsObject(), assertIsResource(), assertIsString(), assertIsScalar(), assertIsCallable(), or assertIsIterable() instead.

3) Magento\Amqp\Test\Unit\Setup\ConfigOptionsListTest::testCreateConfig with data set #2 (array('', '5672', '', '', '/', ''), array())
assertInternalType() is deprecated and will be removed in PHPUnit 9. Refactor your test to use assertIsArray(), assertIsBool(), assertIsFloat(), assertIsInt(), assertIsNumeric(), assertIsObject(), assertIsResource(), assertIsString(), assertIsScalar(), assertIsCallable(), or assertIsIterable() instead.
```

### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/27500

### Manual testing scenarios (*)
1. Run tests in phpunit 6 (currently in 2.4-develop) using `vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist app/code/Magento/Amqp/`
2. Install phpunit 8, run tests using `vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist app/code/Magento/Amqp/`

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@lbajsarowicz all tests are passed, please do review

**Review by lbajsarowicz — APPROVED** [review]
Great, thank you!

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7291](https://jira.corp.magento.com/browse/ENGCOM-7291) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:**
Screenshot from 2020-04-13 10-33-32

**After:**
Screenshot from 2020-04-13 10-37-57

**Pull request merged**
