### PR TITLE
Fix typehint

### PR DESCRIPTION
**Pull request by amenk**
Typehinting is wrong in StoreManager interface

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by okorshenko** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [Magento instance](https://i-23011-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23011-2-3-develop.instances.magento-community.engineering/admin](https://i-23011-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by amenk** [comment]
"Properly transliterate German Umlauts  …" does not belong here, sorry

**Review by orlangur — CHANGES_REQUESTED** [review]
Please adjust https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Store/Model/StoreManager.php#L74 accordingly.

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

**Comment by amenk** [comment]
@orlangur thanks, done :)

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-5166](https://jira.corp.magento.com/browse/ENGCOM-5166) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
