### PR TITLE
Clean up lib reset

### PR DESCRIPTION
**Pull request by mrtuvn**
This PR aims to clean up lib css reset
#1 clean up code styles base  less magento standards
#2 remove incorrect usage of font-size-adjust: 100%; (This unneccesary)
value only accept number|none|initial|inherit. In my opinions we don't need that
#3 remove whitespace below image
remove white space below all image
Normal behavior image contain whitespace below image tag

Setting `vertical-align` removes the whitespace that appears under `img` elements when they are dropped into a page as-is. Safer alternative to using `display: block;`.

preserved previously changes, keep backward compatible

### Fixed Issues (if relevant)

No issue available

### Manual testing scenarios (*)

Go to category or product details for make sure all images should visual correct like before the changes
icon svg, logo, images should not distorted

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@krzksz can you give me a review on this

**Review by krzksz — APPROVED** [review]

**Comment by krzksz** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-7714](https://jira.corp.magento.com/browse/ENGCOM-7714) has been created to process this Pull Request

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run WebAPI Tests

**Comment by mrtuvn** [comment]
Can we have QA check on this

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by mrtuvn** [comment]
@engcom-Alfa @engcom-Charlie may i have some QA tester for this

**Comment by engcom-Delta** [comment]
Hi @mrtuvn . Could you add more details to `Manual testing scenarios` where styles from `_resets.less` are used?

**Comment by mrtuvn** [comment]
@engcom-Delta this file affect to all page. This is global styles for reset will be include from begin before all styles-l or styles-m
Just a few change for cleanup you can check around element like image or logo (svg)

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE

**Review by ptylek — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-7714](https://jira.corp.magento.com/browse/ENGCOM-7714) has been created to process this Pull Request

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by engcom-Bravo** [comment]
Hi @mrtuvn,

We are closing this PR.The PR is in Draft since longtime.

Once you are ready Please feel free to reopen it to process the PR further.

Thanks

**Pull request closed without merging**
