### PR TITLE
#25052 fixed

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)

Category page filter option issue - Magento 2.3.3
### Fixed Issues (if relevant)

1. magento/magento2#25052: Category page filter option issue
2. magento/magento2#25053: Product page tabs issue - Magento 2.3.3

### Manual testing scenarios (*)

1. On the category page, click on any filter option tab.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by dmytro-ch** [comment]
Hi @vishesh-webkul, what is the difference between current PR an #25238 ?
Both PRs provide exactly the same fix.

**Comment by eugene-shab** [comment]
@DrewML ,  please review.

**Comment by dmytro-ch** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-25239.instances.magento-community.engineering).
Admin access: [https://pr-25239.instances.magento-community.engineering/admin](https://pr-25239.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello @vishesh-webkul, unfortunately, this logic was added on purpose in scope of magento/magento2#23862.

I think this is an expected behavior to trigger scrolling if the expanded content is beyond the viewport.
Thus it would be better to extend the collapsible widget in order to provide an ability to disable scrolling during the initialization only when it's redundant, e.g. on Category page filter tabs.
But this feature should not be removed entirely.

Thank you!

**Comment by dmytro-ch** [comment]
Hi @vishesh-webkul, I'm closing this PR now due to inactivity.
Feel free to reopen and update if you wish to continue.
Thank you!

**Pull request closed without merging**
