### PR TITLE
graphql playground with arealist plugin

### PR DESCRIPTION
**Pull request by dani97**
Graphql Playground integration with magento 2.
Accessible in default mode and developer mode.
### Description (*)

Graphql Playground integration with magento 2.
Created a route with id graphql.
Accessible in default mode and developer mode as {BASE_URL/graphql} in modern browsers.
Removed all default magento styles from the page.
Implemented as independent module like swagger so can be removed or disabled in production.

### Related Pull Requests

https://github.com/magento/magento2/pull/26468
https://github.com/magento/graphql-ce/pull/992

### Fixed Issues (if relevant)

1. magento/graphql-ce#783

### Manual testing scenarios (*)

In developer or default mode access {BASE_URL}/graphql

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by dani97** [comment]
@lenaorobei  couldn't reopen the old pull request, please consider this. I have changed new Http App logic to a plugin to AreaList

**Comment by hnsr** [comment]
Hey @dani97, was this ever merged?

**Comment by dani97** [comment]
Nope, not likely in future too.

**Comment by hnsr** [comment]
I recently finally scratched this itch, because I needed something to easily debug Magento GraphQL calls using xdebug, for which I use the xdebug helper extension that sets a cookie.

I made a small Magento extension that embed [Apollo GraphQL sandbox](https://www.apollographql.com/docs/graphos/explorer/sandbox/), with the `includeCookies` setting that makes this work with the `fetch` calls it does under the hood: see https://github.com/ho-nl/magento2-ReachDigital_ApolloSandbox

**Pull request closed without merging**
