### PR TITLE
[Forwardport] 15319 : misleading data-container in product list

### PR DESCRIPTION
**Pull request by mageprince**
### Description

Change static data-container class "product-grid" to $viewMode

### Related issue

https://github.com/magento/magento2/issues/15319

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### Original PR 
https://github.com/magento/magento2/pull/15350

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mageprince. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by orlangur** [comment]
@mageprince please cherry-pick commit from https://github.com/magento/magento2/pull/15350 instead of doing a new commit and force push to your current branch.

**Comment by mageprince** [comment]
@orlangur Can you please explain why we need cherry-pick for this PR ?

**Comment by sidolov** [comment]
@mageprince , cherry-pick is needed because we are trying to keep the original author in new commits during porting PRs across release lines.

**Comment by mageprince** [comment]
@sidolov Thanks for the information. I have just do cherry-pick of the main commit.

**Comment by orlangur** [comment]
@mageprince branch history is incorrect. You need to have something like `sunilit42 authored and mageprince committed ` for all of the commits. Please rewrite history accordingly and force push into the same branch.

**Comment by orlangur** [comment]
@mageprince revert is not what I was asking for. Are you going to rewrite branch history properly and make a force push?

**Comment by sidolov** [comment]
Hi @mageprince , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
