### PR TITLE
Deleting CMS page via webapi/cron should remove related URL rewrites

### PR DESCRIPTION
**Pull request by unicoder88**
### Preconditions

1. Magento 2.2.3 Commerse edition - but any 2.2, I just have a fresh EE install to prove
2. Apache/2.4.27 (Ubuntu)
3. PHP 7.0.26-2+ubuntu17.10.1+deb.sury.org+2

### Steps to reproduce

1. Create new access token
  - System > Integrations > Add New Integration
  - set any name, give access to API resources Content > Elements > Pages https://prnt.sc/j6rek2, save
  - Click Activate > Allow on new integration, copy access token https://prnt.sc/j6reuq
2. We want to delete CMS page 'About US' https://prnt.sc/j6rf4o and free url_rewrite `about-us`. Check `url_rewrite` table has a record before deleting.
3. Make a REST API call `DELETE http://m22ee.local/rest/V1/cmsPage/8`, supply `Authorization: Bearer {token}` header. https://prnt.sc/j6rfk3
4. Check that the page is gone in admin https://prnt.sc/j6rfr3
5. Now check `url_rewrite` table. Old rewrite is *not deleted* https://prnt.sc/j6rfe3.
6. Now try to create a new CMS page with identifier `about-us` that should have become available. You get an error https://prnt.sc/j6rfyz.

### Expected result

1. After deleting CMS page via API or in crontab area, according URL rewrites should be removed.

### Actual result

1. Module Magento_CmsUrlRewrite declares plugin `cms_url_rewrite_plugin` only in `adminhtml` area, this should be moved to global area.
https://prnt.sc/j6rgtj

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14751) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
@unicoder88 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-1314](https://jira.corp.magento.com/browse/ENGCOM-1314) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @unicoder88. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

**Pull request merged**
