### PR TITLE
Fixed: Validation issue

### LINKED ISSUE #38229: [Issue] Solved bundle product validation error message with checkbox option i…
This issue is automatically created based on existing pull request: magento/magento2#38223: Solved bundle product validation error message with checkbox option i…

---------
### Title 
  Bundle product validation message issues with checkbox options

### Preconditions  (*)
 I have tested it only below mentioned magento versions,and issues are reproducible.
   Magento 2.4.6-p1
   Magento 2.4.6-p2

### Description (*)
**Scenario-1**
Validation error message is showing for the  required checkbox bundle option which is already checked (Screenshot-1)

**Screenshot-1**
image

**Scenario-2**
When we edit the bundle product from the cart and deselect all items from any  required bundle option and try to update the Cart then validation error messages are showing multiple times (Screenshot-2)

**Screenshot-2**
image

### Steps to reproduce for Issue  for scenario-1 (*)
1. Create bundle Product with multiple type of options and some   option should be required checkbox.

2. Go to frontend and open that bundle product.

3. Select variant from one of the checkbox option and don't  select any variant from  other checkbox option.

4. Try to add product to cart then observe.

### Steps to reproduce for Issue  for scenario-2(*)
1. Using the same bundle product from scenario one.

2. Go to frontend and open that bundle product.

3. Select all the required bundle options and add product to cart.

4. Edit product from minicart/cart.

5.  Uncheck one of the required checkbox option value and try to update the cart then observe.

### Expected Result(*)
Validation message should be shown below the unselected bundle option item, and single validation message should be shown when try to Update Cart.

### Actual Result(*)
Validation message is shown for the bundle option which is already checked, and  multiple validation messages shown when try to Update  Cart.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by aasim110**
### Description (*)

Resolved Validation issue on Checkbox fields bundle products

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38229

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by aasim110** [comment]
@magento run all tests

**Comment by aasim110** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by aasim110** [comment]
@magento run all tests

**Comment by aasim110** [comment]
@rogyar seems like failed test not related to this commit, kindly check in detail

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @aasim110,

Thanks for the contribution!

It seems the functional tests are failing due to the changes, please fix them.

And also please cover the changes with some automated tests.

Thanks

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by aasim110** [comment]
@magento run WebAPI Tests, Integration Tests

**Comment by aasim110** [comment]
@engcom-Hotel WebAPI Tests and Integration Tests succeed and functional tests are not related to the commit.

**Comment by engcom-Echo** [comment]
@aasim110 functional failure seems to be related to PR only.
Please check below test at your end once all are related to bundle product.
1. StorefrontEditBundleProductTest
2. StorefrontBundlePlaceOrderWithMultipleOptionsSuccessTest
3. StorefrontAssertFixedCartDiscountAmountForBundleProductTest
4. StorefrontAddBundleOptionsToCartTest

here is the build [report](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38262/dac3aebcfbf4156200805c3e557531d8/Functional/allure-report-ce/index.html#categories/928f1c8a6605aebe4b92e957f199352b/55d09c64af63996e/)

**Comment by rogyar** [comment]
Hi @aasim110. 
As it was mentioned, the failing tests most likely related to the changes. For example, let's check the `StorefrontAddBundleOptionsToCartTest`. As you can see from the [report](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38262/dac3aebcfbf4156200805c3e557531d8/Functional/allure-report-ce/index.html#suites/8187718e2fd144987673ef34ee62b41b/55d09c64af63996e/) the system expects the displayed subtotal of the bundle product as `1,968.00`. After your change, the displayed subtotal is `492`. That's the reason why the tests are failing. A similar case is with other functional tests mentioned above.

**Comment by rogyar** [comment]
Also, I see your point that the dependence between your chances and the cart page is not obvious, but there's a dependency. If some option wasn't checked on the product detail page, for example, it affects the subtotal in the cart of the added bundle. So, most likely, after your change, the added product is different (in terms of options). 

You may think in the same way to resolve issues with other tests.

Hope it's helpful.

**Comment by engcom-Echo** [comment]
@aasim110 we are moving `On Hold` this PR for now as PR need attention as per above [comment](https://github.com/magento/magento2/pull/38262#issuecomment-1881020422)

**Comment by engcom-Echo** [comment]
@aasim110 As the PR changes are causing build failure due to PR changes.
Hence we are closing for now. Once you are ready to proceed please feel free to reopen the PR.

**Pull request closed without merging**
