### PR TITLE
wrong javascript variable scope stripTags

### PR DESCRIPTION
**Pull request by bst2002git**
### Description (*)
New Email Template cannot be saved as TEXT-Template because of wrong javascript variable scope

### Manual testing scenarios (*)

1. Add new Template in Marketing -> Email Templates
2. Load some default Template to test
3. Click "Convert to Plain Text" and save
4. Template Type remains HTML and not TEXT

### CODE REVIEW

**Comment by bst2002git** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @bst2002git. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @bst2002git, here is your [new Magento instance](https://pr-28020.instances.magento-community.engineering).
Admin access: [https://pr-28020.instances.magento-community.engineering/admin_e77a](https://pr-28020.instances.magento-community.engineering/admin_e77a)
Login: `7f34d5c2` Password: `37ae47fa51f5`
Instance will be terminated in up to 3 hours.

**Comment by bst2002git** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @bst2002git. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @bst2002git, here is your [Magento instance](https://i-28020-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28020-2-4-develop.instances.magento-community.engineering/admin_cfb2](https://i-28020-2-4-develop.instances.magento-community.engineering/admin_cfb2)
Login: `d3adb889` Password: `8a0e70bff10f`
Instance will be terminated in up to 3 hours.

**Comment by bst2002git** [comment]
test instance with PR works as expected
2.4-develop vanilla instance does not save Email Template as type TEXT as expected

**Comment by slavvka** [comment]
@magento run all tests

**Review by orlangur — CHANGES_REQUESTED** [review]
Nice catch @bst2002git!

What about other occurrences of `this.typeChange`?

**Comment by bst2002git** [comment]
@orlangur others are ok

**Review by orlangur — DISMISSED** [review]
In the mean time there was another bugfix https://github.com/magento/magento2/commit/a8ff59ae2837d8a58111e7438eb1303f095c5d02 :)

But still it didn't fix template case.

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-7556](https://jira.corp.magento.com/browse/ENGCOM-7556) has been created to process this Pull Request
:eight_spoked_asterisk: @orlangur, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@bst2002git thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by bst2002git** [comment]
@orlangur 
What do you mean with "But still it didn't fix template case."

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @bst2002git  .
     Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by auto test.
Thanks!

**Comment by orlangur** [comment]
Raised this precedent in maintainers channel to find out what kind of tests we expect in this situation, please hold on without nay changes.

**Comment by sidolov** [comment]
@orlangur it's hard to catch such error by test since the email transport functionality is involved. JS unit tests also will not be useful in this case, looks like it's manual only.

**Review by sidolov — APPROVED** [review]

**Review by sidolov — CHANGES_REQUESTED** [review]
@bst2002git could you please sign Adobe CLA?

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-7556](https://jira.corp.magento.com/browse/ENGCOM-7556) has been created to process this Pull Request

**Comment by sidolov** [comment]
@bst2002git  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
