### PR TITLE
Fix typo in SQL join when joining custom option prices for price indexer

### PR DESCRIPTION
**Pull request by udovicic**
### Description (*)
In case where product has price variation for custom option per website, only default value (`store_id = 0`) is taken into an account due to typo in SQL statement.

### Fixed Issues (if relevant)

1. N/A

### Manual testing scenarios (*)

This one is pretty obvious from diff, but...
1. Create  scenario where simple product price is regulated per website and have at least two websites
2. Set default price to amount X
3. Set price of custom option (on default view) to amount to Y
4. Switch scope to another website and set price of custom option to be 0
5. Execute price indexer
6. Difference between min and max price should be visible only on one website, however all websites will have this difference

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @udovicic. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3616](https://jira.corp.magento.com/browse/ENGCOM-3616) has been created to process this Pull Request

**Review by orlangur — CHANGES_REQUESTED** [review]
@udovicic, QA report follows:

```
Not clear what issue should be caused by typo in DefaultPrice.php on 2.3-develop.
Manual testing scenario:

Create two websites: Main Website and Second
Set Catalog Price Scope=Website
Create simple product on both websites.
Add custom option:
Option Title=Option1
Option Type=Drop-Down
Title=Value
Price=10
Price Type=Fixed
Click Edit product
Change Store View to Second website store view
Set price of custom option to be 0
Execute price indexer: php bin/magento indexer:reindex catalog_product_price
Go to Product Page
 Product and custom option prices are correct displayed

Go to Product Page on another webiste
 Product and custom option prices are correct displayed
```

Please provide more details so that issue can be reproduced.

**Comment by udovicic** [comment]
Hi @orlangur ,

You are correct, I have tested on wrong version and therefore patched the wrong file. Apologize for that. Nevertheless, issue persist as the bug was just migrated to new file (not sure what the old one is for, but I left change there as well).

Hover, steps to reproduce are not entirely correct. When I said _"min and max price should be visible only on one website"_, I didn't mean on frontend but in the database in the table `catalog_product_index_price` actual `min_price` and `max_price` fields. Should have been more clear on that.

If you check the setup of that product you will see that only thing that influences price of product is a custom option. Therefore, for website where custom option has a price >0, `max_price` value in the database table `catalog_product_index_price` should be larger than `final_price`. In contrast to that, on website where custom option price is set to 0, there should be no difference between those two. Without the modifications in this PR, that is not the case but is expected result.

**Review by orlangur — APPROVED** [review]
@udovicic thanks, let's recheck.

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3616](https://jira.corp.magento.com/browse/ENGCOM-3616) has been created to process this Pull Request

**Pull request merged**
