### PR TITLE
Marks Belgium as a country with no required states.

### PR DESCRIPTION
**Pull request by hostep**
### Description (*)
This is a follow up to https://github.com/magento/magento2/commit/5cd7496e76773f953ffcad102aa3111d4d4747d6 and https://github.com/magento/magento2/pull/25160

I didn't notice it before, but when running the [`addCountryRegions` method](https://github.com/magento/magento2/blob/68d21376fa18895276e00931fe382c120d7a4e17/app/code/Magento/Directory/Setup/Patch/Data/AddDataForBelgium.php#L47-L50), it also [sets up the countries with required states again](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/Directory/Setup/DataInstaller.php#L63-L74).
That list [is generated](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/Directory/Model/ResourceModel/Country/Collection.php#L339-L343) based on some configuration values [in the xml](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/Directory/etc/di.xml#L33-L38).

As Belgium doesn't require states/regions/provinces in its postal service, this country should not be marked as a country with required states.

Same question as in https://github.com/magento/magento2/pull/25160: since 5cd7496 and https://github.com/magento/magento2/pull/25160 aren't part of a Magento release yet, is it ok to change this like this without creating a new database migration patch? If all these changes gets released in Magento 2.3.4, all should be fine in the database.

### Fixed Issues (if relevant)
None

### Manual testing scenarios (*)
1. Setup Magento based on this PR
2. In the frontend, register a new customer
3. In his address book, add a new address, pick country Belgium and the state field should be not required.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rodrigowebjump — APPROVED** [review]
Hi @hostep Thanks for your contribution

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-6182](https://jira.corp.magento.com/browse/ENGCOM-6182) has been created to process this Pull Request
:eight_spoked_asterisk: @rodrigowebjump, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @hostep 

During testing, we faced the issue.

**_Problem:_** Region/State for Belgium is still required in **Store Information**

**Manual testing scenario:**

1. Log in to Admin;
2. Go to Stores->Configuration->General->General->Store Information;
3. Fill all required fields;
3. Select **Belgium** from Country drop-down list and leave Region/State empty

**Actual Result:**
after

And Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

@hostep Could you take a look?

Thanks!

**Comment by hostep** [comment]
@engcom-Alfa : can you re-test but test directly with this PR applied and only then install the database? The database won't update itself if you go from 2.3-develop to this PR, that's what I meant with:
> Same question as in #25160: since 5cd7496 and #25160 aren't part of a Magento release yet, is it ok to change this like this without creating a new database migration patch? If all these changes gets released in Magento 2.3.4, all should be fine in the database.

As far as the tests go, are there already tests for verifying required states in certain countries? Would you be so kind to point me in the right direction, thanks!

**Comment by engcom-Alfa** [comment]
@hostep, thank you for clarification.
I've checked as you described in PR (switched to the branch with the fix and then installed Magento) and your changes solved the problem described in the testing scenario:

```
- Setup Magento based on this PR
- In the frontend, register a new customer
- In his address book, add a new address, pick country Belgium and the state field should be not required.
```
I came across another problem that I described in a previous post. But I'm not sure if this problem applies to this PR and whether this is a problem at all.

You can cover this scenario with the [MFTF](https://devdocs.magento.com/mftf/docs/introduction.html) test. 

_Note:_ In MFTF test add in the annotation 
`<testCaseId value="https://github.com/magento/magento2/pull/25316"/>` , please.

@hostep Could you take a look?

Thanks!

**Comment by hostep** [comment]
I'll have a look later this week. Never written an MFTF test before ...

I hope this won't miss the cut-off point of Magento 2.3.4, not sure when that is planned?

**Comment by engcom-Golf** [comment]
Hi @hostep   thank you for Pull Request I will take care of test coverage.

**Comment by hostep** [comment]
Thanks Nazar!

**Pull request merged**
