### PR TITLE
[FEATURE] - Adds source model on saving of multiselect attribute

### PR DESCRIPTION
**Pull request by rensieeee**
### Description (*)

When creating a multiselect product attribute, the source model is empty by default. This isn't necessary and can be replaced with the default Table source model (\Magento\Eav\Model\Entity\Attribute\Source\Table).

### Manual testing scenarios (*)

1. Create a multiselect product attribute in Magento. Notice it won't have a source_model class in the eav_attribute table.
2. Apply these changes. Create a new multiselect attribute in Magento. Notice it contains the source_model \Magento\Eav\Model\Entity\Attribute\Source\Table.
3. Create a boolean product attribute in Magento. Notice it still has the \Magento\Eav\Model\Entity\Attribute\Source\Boolean source model.
4. Create a text product attribute in Magento. Notice it won't have a source_model.
5. Update the source_model of the newly created multiselect attribute in the eav_attribute table (no Magento, just plain MySQL) to be empty.
6. Update the newly created multiselect attribute label. Notice the source_model is still empty. These changes change the default source_model, but still allow for customisation.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rensieeee** [comment]
@magento run all tests

**Comment by sdzhepa** [comment]
Hello @rensieeee 

Could you please provide more details about the use cases and business value of this issue or what dev experience it will improve and how?

We see the solution but we cannot understand what problem it solves

Thank you in advance

**Comment by rensieeee** [comment]
Hi @sdzhepa

It's possible to create product attributes using rest api. Multiselect attributes require source models to work, which usually are written in code together with the attribute. However, this fix allows to create multiselect attributes using rest api, using the basic Table eav source model, making the restapi functionality fully compatible with all attribute creations.

**Comment by hostep** [comment]
Following issue will need to be taken into account before this PR can be accepted I believe: https://github.com/magento/magento2/issues/13156 ([PR that fixed that](https://github.com/magento/magento2/pull/18244))

@rensieeee: does this PR write that source model to the database, or is it only used at runtime?

**Comment by rensieeee** [comment]
Hi @hostep,

Yes, this PR writes the source model to the database, but only on creation. It isn't reset or overwritten on save, so you can still alter it if you want to.

**Comment by rensieeee** [comment]
@magento run Static Tests, Integration Tests

**Review by andrewbess — CHANGES_REQUESTED** [review]
Hello @rensieeee 
Could you please fix failed integration and static tests

Thank you in advance

**Comment by ishakhsuvarov** [comment]
Hi

I am closing this PR for now as it seems like it has become stale and still needs work.

Please feel free to reopen if you wish to continue.

Thanks!

**Pull request closed without merging**
