### PR TITLE
Multishipping checkout agreements now are the same as default checkout agreements

### PR DESCRIPTION
**Pull request by samuel27m**
### Description (*)

Make multishipping checkout agreements template file to be the same as default checkout for consistency.

### Manual testing scenarios (*)

1. "Review Order" multishipping step now has the same template for checkout agreements that default checkout has.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @samuel27m. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by dmytro-ch** [comment]
Hi @samuel27m,
thank you for your contribution!

Unfortunately, we may not remove the templates due to the possible backward compatibility issues. Some third-party themes or extensions might use this template without overriding.

Could you please restore the `app/code/Magento/CheckoutAgreements/view/frontend/templates/multishipping_agreements.phtml` file?

Thank you!

**Comment by samuel27m** [comment]
Hi @dmytro-ch,

Thanks for noticing, I totally forgot about that.
Added new commit to restore the file.

Thank you!

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4526](https://jira.corp.magento.com/browse/ENGCOM-4526) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
✔️ QA passed

**Pull request merged**
