### PR TITLE
magento/magento2#14971: Improper Handling of Pagination SEO

### PR DESCRIPTION
**Pull request by benathomeofchampions**
This removes the p= query string parameter in pagination for the first page, when navigating back to page 1, to avoid duplicate content SEO issues.

### Description (*)
First page pagination links will still include the pagination query string (for example `p=1`) which causes a duplicate content SEO issue. 

### Fixed Issues (if relevant)

1. magento/magento2#14971: Improper Handling of Pagination SEO

### Manual testing scenarios (*)

1. Visit a category with more than 1 page
2. Use pagination to go to page 2
3. Return to page 1 via pagination and verify that the pagination query string parameter is not present in the URL

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23298) <br/>All committers have signed the CLA.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5625](https://jira.corp.magento.com/browse/ENGCOM-5625) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @benathomeofchampions 

During testing we faced the issue

**_Problem:_** Value `?p=1` appended when we add an additional parameter

**Steps to reproduce:**

1. Visit a category with more than 1 page;
2. Select list mode  
3. Use pagination to go to page 2;
4. Return to page 1 via pagination;

**Actual Result:**
after

@benathomeofchampions Could you take a look, please?

Thanks!

**Comment by sidolov** [comment]
@benathomeofchampions , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
