### PR TITLE
Remove loader mask that remains indefinitely if terms and conditions box is unchecked

### PR DESCRIPTION
**Pull request by g-anedda**
### Description (*)

resolution for this issue
https://github.com/magento/magento2/issues/26797

### Fixed Issues (if relevant)

1. magento/magento2#26797: Checkout loader mask remains indefinitely if terms and conditions box is unchecked

### Manual testing scenarios (*)

1. Have 3D Secure enabled on Braintree payment method
2. Fill all data for shipping and billing, leaving the Terms and Conditions checkbox unchecked
3. Try to place the order
4. The loader disappears and the checkbox is checkable

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @ganedda-softfobia, thank you for your contribution, however due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) the changes should be covered by tests.
Could you please cover this fix by a MFTF test?

Thank you.

**Comment by eduard13** [comment]
Hi @ganedda-softfobia, are you willing to continue working on this one?
Thank you.

**Comment by ganedda-softfobia** [comment]
> Hi @ganedda-softfobia, are you willing to continue working on this one?
> Thank you.

No, the functional tests CE passed, so can't see why EE and B2B did not

**Comment by eduard13** [comment]
@g-anedda, the failing tests aren't related to your changes.

**Comment by eduard13** [comment]
Hi @ganedda-softfobia, due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) all the changes have to be covered by some tests.
Could you please cover this fix by a MFTF test?

**Comment by engcom-Kilo** [comment]
Working with MFTF test

**Comment by engcom-Kilo** [comment]
@g-anedda Please resolve conflict with app/code/Magento/Braintree/view/frontend/web/js/view/payment/3d-secure.js

**Comment by g-anedda** [comment]
seems that the app/code/Magento/Braintree folder doesn't exist anymore at the moment in 2.4-develop, so this PR has no more meaning to exist.
The problem anyway persist on 2.3

**Pull request closed without merging**
