### PR TITLE
update button.phtml overcomplicated translation phrase. 

### PR DESCRIPTION
**Pull request by ChuckyK**
It has overcomplicated translation phrase. 
"<a href=""%1"" onclick=""this.target=\'_blank\'"" class=""print"">Print receipt</a>" 
vs
"Print receipt"

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=12106) <br/>All committers have signed the CLA.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by Jeroenll** [comment]
@ChuckyK Can you also update the translation string in .csv [here](https://github.com/magento/magento2/blob/2.1-develop/app/code/Magento/Checkout/i18n/en_US.csv#L65)?

Would be nice if you can also create a PR for the 2.2-develop branch 😄

**Comment by ihor-sviziev** [comment]
@ChuckyK could you create the same PRs also for ```2.2-develop``` and ```2.3-develop``` branches and update translations?

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ChuckyK** [comment]
#12155

**Pull request merged**
