### PR TITLE
[Fixed] - Resolve Color doesn't apply to Visual Swatches by clicking on page

### PR DESCRIPTION
**Pull request by niravkrish**
### Description (*)

I have added functionality to change the swatch color selection simultaneously on change of colorpicker.

### Fixed Issues (if relevant)

1. https://github.com/magento/community-features/issues/253: Color doesn't apply to Visual Swatches by clicking on page

### Manual testing scenarios (*)

1. Edit product attribute color.
2. Change existing color and save attribute as well as add new option and save attribute.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Could you please consider using `onHide` event and add some tests to verify this behaviour.

**Comment by niravkrish** [comment]
> Could you please consider using `onHide` event and add some tests to verify this behaviour.

Hello @lenaorobei 
I have tried to use **onhide** event but it is trigged on every drag leave and onhide does not provide the selected color value so we can not use it.
I fount best solution from available solutions is **onChange**.

- about test cases Actually I am not aware about how to create test cases and write it.
If someone help me then definitely I can.

Thank you,
Nirav Patel

**Comment by lenaorobei** [comment]
This solution looks like we are hacking the default color-picker functionality. I suggest using another library that is more extensible and already the part of Magento `lib/web/jquery/spectrum/spectrum.js`

**Comment by niravkrish** [comment]
> This solution looks like we are hacking the default color-picker functionality. I suggest using another library that is more extensible and already the part of Magento `lib/web/jquery/spectrum/spectrum.js`

Ok, I will try and change the colorpicker library to spectrum as you suggested.

Thank you for your suggestion.

**Comment by niravkrish** [comment]
Hello @lenaorobei ,

I have changed colorpicker library with spectrum.
Please review it.

Thank you,
Nirav Patel

**Comment by niravkrish** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @niravkrish. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @niravkrish, here is your [new Magento instance](https://pr-27461.instances.magento-community.engineering).
Admin access: [https://pr-27461.instances.magento-community.engineering/admin_a948](https://pr-27461.instances.magento-community.engineering/admin_a948)
Login: `d6661bab` Password: `98d1cf14e39c`
Instance will be terminated in up to 3 hours.

**Comment by lenaorobei** [comment]
Could you please address static build failure https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/27461/6090920c68b8b4cfb013e4a8ca4bb2eb/Statics/allure-report-b2b/index.html#suites/3a29d43e5c1686787ff8c2a77e590abb/35e83f7ab791fb29/

**Comment by niravkrish** [comment]
> Could you please address static build failure https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/27461/6090920c68b8b4cfb013e4a8ca4bb2eb/Statics/allure-report-b2b/index.html#suites/3a29d43e5c1686787ff8c2a77e590abb/35e83f7ab791fb29/

Hello @lenaorobei ,
I have updated code as per coding standards please check.

Thank you

**Comment by lenaorobei** [comment]
It looks like a lot of tests related to swatched are failing https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/27461/5fdcd2596a08aaf8b22a1187e05c31f9/Functional/allure-report-b2b/index.html#suites/8187718e2fd144987673ef34ee62b41b/cb518641b04d4ac/

**Comment by niravkrish** [comment]
> It looks like a lot of tests related to swatched are failing https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/27461/5fdcd2596a08aaf8b22a1187e05c31f9/Functional/allure-report-b2b/index.html#suites/8187718e2fd144987673ef34ee62b41b/cb518641b04d4ac/

I didn't got it.

I am not able to understand it.

could you please help me to do it resolve.

Thank you.

**Comment by lenaorobei** [comment]
I sent a link with failed MFTF tests that are related to this change.
Please have a look for example at `app/code/Magento/Swatches/Test/Mftf/Test/AdminDisablingSwatchTooltipsTest.xml` and the screenshot https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/27461/5fdcd2596a08aaf8b22a1187e05c31f9/Functional/allure-report-b2b/data/attachments/a16bd194b298882c.png

**Comment by niravkrish** [comment]
I have changed the code to resolve the issue.
Please review it.
Thank you for helping me.

**Comment by lenaorobei** [comment]
Tests with swatches continue failing. Please see here https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/27461/665925f6c957cef9c8684d460d62c052/Functional/allure-report-b2b/index.html#suites/8187718e2fd144987673ef34ee62b41b/2c5e974a3a1336d8/

Example: `Link or Button or CSS or XPath element with '#swatch-visual-options-panel table tbody tr:nth-of-type(1) button.delete-option' was not found.`

**Comment by lenaorobei** [comment]
Closing this PR due to inactivity. Please feel free to reopen if you are going to continue working on it.
Thank you.

**Comment by niravkrish** [comment]
@lenaorobei,
could you please help me to resolve the test case issue?

Because as you know the solution is perfect and suitable for the issue.
So please help me to make this PR merge and complete.

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
Updated branch and rerun builds. Let's see what failures will appear.

**Comment by niravkrish** [comment]
@magento run all tests

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Tests need to be adjusted to cover the applied change.
Please refer to the [MFTF documentation](https://devdocs.magento.com/mftf/docs/introduction.html).

**Comment by niravkrish** [comment]
I am working on it.

**Comment by gabrieldagama** [comment]
The risk was set to`medium` due to: the suggested changes may impact a critical functionality, it seems to perform a considerable refactor on visual.js.

**Comment by sidolov** [comment]
@niravkrish I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
