### PR TITLE
MC-13537: added default Country Id to checkout Config.

### PR DESCRIPTION
**Pull request by AleksLi**
### Description (*)
The reason of that bug is: the _DefaultCountryId_ sets from the config path tax/defaults/country and not from general/country/default of Magento 2 configuration. That's why when you're go to the checkout and that's your first time, session wasn't saved in browser, table rates are wrong. 

### Fixed Issues (if relevant)

1. magento/magento2#<[13537](https://github.com/magento/magento2/issues/13537)>: Magento 2.2.0 One page checkout initial postage calculation ignores "default country" using table rate shipping.

### Manual testing scenarios (*)

1. Set Default country to "United Kingdom".
2. Setup table rate shipping.
3. Add item to cart.
4. Proceed to one page checkout.
5. Default country is set automatically to "United Kingdom" as expected.
6. The initial shipping price displayed is that of the USA but should be the UK.
7. Deselect then reselect "United Kingdom" the shipping price refreshes correctly.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21280) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @AleksLi. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by swnsma — CHANGES_REQUESTED** [review]
I think providing new config to tax configs like `defaultTaxCountryId` without any future usage is not proper fix which we need.

**Comment by sidolov** [comment]
@AleksLi , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
