### PR TITLE
Issue 30286 - Fix widget layout update removal button to work for multiple layout updates

### LINKED ISSUE #30286: Can't remove seconde added Layout Update
**Steps to reproduce:**
1. Go to Content - Widget and "Add Widget"
1. Select any "Type", "Design Package/Theme" and click "Continue"
1. On Widget Storefront Properties click "Add Layout Update"
1. Select some item from "Display on" and "Container" dropdowns
1. Click "Add Layout Update"
1. Click "Remove Layout Update" button on previously added Layout

**(x) Actual result:**  Can't remove Layout Update

(/) **Expected result:**  Layout Update can be removed

### PR DESCRIPTION
**Pull request by zaximus84**
### Description (*)
When adding a widget in the Magento admin (Content > Widgets), the remove button (trash can icon) on layout updates doesn't work for any layout update but the first. This is because the current code relies on \Magento\Framework\View\Helper\SecureHtmlRenderer::renderEventListenerAsTag to generate the js click listeners, and that uses document.querySelector to establish the element. The element selector passed to querySelector is not unique because it comes from javascript templating, and it always selects the first matching element on the page. Every time the "Add Layout Button" is clicked, another layout row is added, but the click handler is just added to the first row again.

Using a widget block (PHP) class in combination with javascript templating to produce the click listeners doesn't work for this scenario, so this PR updates the remove buttons to use a standard onclick attribute. It also updates the new widget MFTF test to add and remove layout rows and confirm the resulting counts.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30286

### Manual testing scenarios (*)

1. In admin, go to Content > Widgets and click New Widget.
2. Select any widget type and design theme and click Continue.
3. Under Layout Updates, click Add Layout Update multiple times.
4. Click the trash can icon on any of the resulting rows and confirm that the intended row is removed.
5. Give special attention to removing a row other than the first when there are multiples (that was the original failure which prompted this PR).

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
good catch!. But seem a reason previously core team remove this code onclick in template that lead to this issue
@zaximus84 
CC @rogyar can you see this

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by bhaveshpp** [comment]
## Magento 2.4
I am facing the same issue in my project.
The console is clear there is no error in the console
https://drive.google.com/file/d/1EEhxFnAlPUu_-4srQGkQOP_iVtlLxIm6/view

Did anyone found any solution to this issue?

Thank you.

**Comment by zaximus84** [comment]
@bhaveshpp 
I have a PR open for this, though there's apparently a question about whether this would undo a change intentionally made in the past. You can apply my changes as a patch and see if they work for you without side effects:

https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/30992.diff

layout.phtml is the only file that really needs to be updated to fix the issue.

**Comment by rogyar** [comment]
@magento run all tests

**Comment by rogyar** [comment]
@magento run Functional Tests B2B

**Comment by mrtuvn** [comment]
@rogyar i think this patch from @zaximus84 is better fix and simplest . Can we have further check and approve this soon ?

**Review by rogyar — APPROVED** [review]
The failing tests are not related to the current changeset

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8502](https://jira.corp.magento.com/browse/ENGCOM-8502) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

### Manual testing scenario
1. From Admin, go to _Content - Widget_ click **Add Widget**
2. Select, for example, 
- **Type** - _CMS Page Link_ 
- **Design Theme** - _Magento Luma_
Click **Continue**
3. Using **Add Layout Update** button, Add 3 Layout Updates, for example
4. Try to remove the added Layouts using the **Remove Layout Update** (basket)

**BEFORE** applying changes provided in this PR, only the first Layout Update could be removed
Peek 2020-12-01 15-23

**AFTER** switching to the PR, all the Layout Updates can be removed
Peek 2020-12-01 15-43_after

The Widget can be saved successfully 
widget_save

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
