### PR TITLE
Fix Login Popup broken on iPad portrait

### LINKED ISSUE #6451: Login Popup broken on iPad portrait
Login popup is broken on iPad (portrait orientation) when using Magento/blank theme.
### Preconditions
1. Install Magento 2.1.1
2. Use Magento/blank OR Magento/luma theme
3. Disable checkout for guests ( Admin >> Stores >> Configuration >> Sales >> Checkout >> Checkout options >> Allow Guest Checkout  >> Set to "No" >> Save Config button)
4. Flush cache
### Steps to reproduce

1. Go to your website as guest
2. Add to cart any product
3. Click on "Cart icon" in header 
4. Click on "Go To Checkout" button
5. See login popup
### Expected result
1. Design should be same as for desktop (because menu also displaying from desktop)
   image
### Actual result

Design is broken (mix from mobile & desktop versions):

Magenco/blank theme:
image

Magento/luma theme:
image

### PR DESCRIPTION
**Pull request by ihor-sviziev**
This PR will fix #6451

### CODE REVIEW

**Comment by Ctucker9233** [comment]
What's the status on this?

**Comment by ihor-sviziev** [comment]
Any updates?

**Review by Igloczek — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@ishakhsuvarov @vrann @maghamed could you review my PR? It still wasn't processed

**Comment by ishakhsuvarov** [comment]
@ihor-sviziev Sorry for taking so long! Looking into it now.

**Comment by magento-team** [comment]
@ihor-sviziev Thank you for the contribution

**Comment by ihor-sviziev** [comment]
@ishakhsuvarov could you also review https://github.com/magento/magento2/pull/6473? It stuck "in review" for 21 day

**Pull request merged**
