### PR TITLE
MFTF: Checkout With Minimum Order Amount Option Enabled Test

### LINKED ISSUE #33460: [Issue] MFTF: Checkout With Minimum Order Amount Option Enabled Test
This issue is automatically created based on existing pull request: magento/magento2#33136: MFTF: Checkout With Minimum Order Amount Option Enabled Test

---------
This PR contains MFTF test for checkout with minimum order amount option enabled.

**Steps to reproduce:**

1 - Configure minimum order amount
2 - Add the product into shopping cart (minimum order amount is not reached)
3 - Add product into shopping cart second time, to reach minimum order amount
4 - Place order
5 - Perform Assertions

### PR DESCRIPTION
**Pull request by DmitryTsymbal**
This PR contains MFTF test for checkout with minimum order amount option enabled.

**Steps to reproduce:**

1 - Configure minimum order amount
2 - Add the product into shopping cart (minimum order amount is not reached)
3 - Add product into shopping cart second time, to reach minimum order amount
4 - Place order
5 - Perform Assertions

### Resolved issues:
1. [x] resolves magento/magento2#33460: MFTF: Checkout With Minimum Order Amount Option Enabled Test

### CODE REVIEW

**Comment by DmitryTsymbal** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by Den4ik** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Review by Den4ik — APPROVED** [review]
✅ All looks correctly fro me

@DmitryTsymbal Thanks for contribution

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9118](https://jira.corp.magento.com/browse/ENGCOM-9118) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Charlie** [comment]
@magento create issue

**Comment by engcom-Charlie** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Create category
2. Create Product
3. Enable Minimum order amount option from admin 

**Manual testing scenario:**

1 - Login to store front 
2-  Add a product with less than minimum order amount 
3-  Move to view and edit cart from mini shopping cart.  Message should gets display here as “Minimum order amount is (amount set in admin)” and Proceed to checkout button should be disable as the cart value is less than minimum order amount
4-  Add the product again with quantity so that cart amount is greater than minimum order amount
5-  Proceed to checkout button should be enable now
6-  Select flat rate as shipping rate and Money order as payment method 
7-  Place the order. User can place the order for cart with value more than minimum order amount value.
8 -  For above steps also run the StorefrontCheckoutWithEnabledMinimumOrderAmountOptionTest MFTF test 

**Actual Result:** :heavy_check_mark:
 
1. If minimum order amount is enable in admin then customer should be able to place an order only if cart reached to minimum order amount value
**After:** :heavy_check_mark:  

image

image

image

image


**Tested all the manual scenarios, no impact on regression testing.**

**Pull request merged**
