### PR TITLE
Allow items to be shipped with a qty > 0 and < 1

### LINKED ISSUE #35971: Unable to ship items with a qty > 0 and < 1
### Preconditions and environment

- 2.4.5 (and prior)
- Product must have qty uses decimals enabled and a minimum qty in cart below zero (i.e. 0.2)

### Steps to reproduce

1. Create simple product in admin
2. Enable qty uses decimals for the product
3. Set minimum qty in cart equal to 0.2
4. Create an order - adding a qty of 0.5 for the test product
5. Order / Invoice create correctly
6. Ship the order

### Expected result

Shipment is created with a qty of 0.5

### Actual result

Shipment "items" are blank and therefore, you cannot create shipment

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by ArronKing**
### Description (*)
Cast the qty to a float, rather than an int. The casted value is checked for <= 0, so anything > 0 and < 1 would be (incorrectly) cast to a 0. If this check fails, the item is not added to the shipment. By casting to a float, the validation is passed correctly and you can now ship items with a qty between 0 and 1.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35971

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Keglerass** [comment]
Copy of #35963

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Static Tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
Install fresh Magento `2.4-develop`

**Manual testing scenario:**
1. Create simple product in admin
2. Enable qty uses decimals for the product
3. Set minimum qty in cart equal to 0.2
4. Create an order - adding a qty of 0.5 for the test product
5. Order / Invoice create correctly
6. Ship the order

**Before:** :heavy_multiplication_x: Shipment "items" are blank and therefore, you cannot create shipment.
image

**After:** :heavy_check_mark:  Shipment is now getting created.
after_pr

Checks are failed ,hence, moving this PR to extended testing.

Thanks

**Comment by engcom-Delta** [comment]
@magento run Functional Tests B2B, Static Tests

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento run Integration Tests

**Comment by engcom-Delta** [comment]
Since the PR branch is blocked(Read only), Created a [new](https://github.com/magento/magento2/pull/36232/files) PR with the current changes along with fix for the bulid failures.Hence closing this PR

Thank you.

**Comment by Jilco** [comment]
Yes shipment can be made with qty lower than 1, but order will not change to "completed". So it stays "Processing" while shipment had been made...

**Pull request closed without merging**
