### PR TITLE
[Backport] Bundle-Product-add-to-cart-button-misaligned-on-tab-portrait ::Bundle…

### PR DESCRIPTION
**Pull request by irajneeshgupta**
### Original Pull Request 
 https://github.com/magento/magento2/pull/20195
… Product add to cart button misaligned on tab portrait view.

### Fixed Issues (if relevant)

1. magento/magento2#20193: Bundle Product add to cart button misaligned on tab portrait view
2. ...

### Manual testing scenarios (*)

1.In product detail page on "Bundle Product" click "Customize and Add to Cart" show bundle option check "add to cart" button.
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by amol2jcommerce** [comment]
Hi @irajneeshgupta 
PR already created #20554

**Comment by ghost** [comment]
Hi @irajneeshgupta, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+magento2+20557), it will take less than a minute. </br>Your feedback will help us to improve contribution process.

**Comment by irajneeshgupta** [comment]
@amol2jcommerce 
since your backport PR is not using original commit , do not close my backport.
Thank you.

**Comment by sidolov** [comment]
Hi @irajneeshgupta , I'm closing this PR as a duplicate for https://github.com/magento/magento2/pull/20554 since it was created earlier. 
Thank you!

**Pull request closed without merging**
