### PR TITLE
Fixed issue #20332 Changed sort order of country

### PR DESCRIPTION
**Pull request by GovindaSharma**
### Description (*)
Fixed issue #20332 Shipping address form City, State/Province, Zip/Postal Code, Country not in right Order in checkout

### Fixed Issues (if relevant)

1. magento/magento2 #20332: Issue title:Shipping address form City, State/Province, Zip/Postal Code, Country not in right Order in checkout

### Manual testing scenarios (*)

Step 1: Open frontend
Step 2: Add any product in cart
Step 3: Go to checkout and and see shipping address form

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-3878](https://jira.corp.magento.com/browse/ENGCOM-3878) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @GovindaSharma thanks for your contribution.

Unfortunately we were not able to confirm the fix, the fields order is still incorrect:
image

**Comment by GovindaSharma** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma, here is your [Magento instance](https://i-20334-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20334-2-3-develop.instances.magento-community.engineering/admin](https://i-20334-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by GovindaSharma** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma, here is your [new Magento instance](https://pr-20334.instances.magento-community.engineering).
Admin access: [https://pr-20334.instances.magento-community.engineering/admin](https://pr-20334.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by GovindaSharma** [comment]
Hi @sivaschenko ,if you go to checkout page for not logged in customer then you will find issue in sort order.Here is the screenshot of 2.3-develop instance
screenshot-i-20334-2-3-develop instances magento-community engineering-2019-01-18-11-06-43


And in test instance it is correct in order ,here is the screenshot for the same

screenshot-pr-20334 instances magento-community engineering-2019-01-18-11-29-29


Please have a look again on this.

Thank you

**Comment by sivaschenko** [comment]
Hi @GovindaSharma thanks for your updates. According to the expected result in issue description https://github.com/magento/magento2/issues/20332 the order should be: Country, State/Province, City, Zip/Postal Code fields

**Comment by GovindaSharma** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma, here is your [new Magento instance](https://pr-20334.instances.magento-community.engineering).
Admin access: [https://pr-20334.instances.magento-community.engineering/admin](https://pr-20334.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by GovindaSharma** [comment]
Hi @sivaschenko thanks for your update, now i have made changes and all sort order are are according to issue description.You can check screenshot here
screenshot-pr-20334 instances magento-community engineering-2019-01-19-15-36-56

Please have a look again.
Thank you

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3878](https://jira.corp.magento.com/browse/ENGCOM-3878) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @GovindaSharma this PR is introducing a bit of inconsistency to Magento forms. Should the order of fields be updated in other forms as well (i.e. checkout payment step - billing address, address froms in customer account)?

**Comment by GovindaSharma** [comment]
@sivaschenko since the ordering is defined in checkout page is from xml files and in other forms it is based on attribute sort order.to change ordering in other forms we need to change the attribute sort order.

**Comment by GovindaSharma** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma, here is your [new Magento instance](https://pr-20334.instances.magento-community.engineering).
Admin access: [https://pr-20334.instances.magento-community.engineering/admin](https://pr-20334.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by GovindaSharma** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma, here is your [new Magento instance](https://pr-20334.instances.magento-community.engineering).
Admin access: [https://pr-20334.instances.magento-community.engineering/admin](https://pr-20334.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by GovindaSharma** [comment]
Hi @sivaschenko , i have now made all address form consistent like billing step,customer account address form,checkout shipping address form.Please see my changes and update me on this.
thank You

**Comment by sivaschenko** [comment]
Hi @GovindaSharma can you please also change the fields order on admin panel customer edit page for consistency?

**Comment by GovindaSharma** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma, here is your [new Magento instance](https://pr-20334.instances.magento-community.engineering).
Admin access: [https://pr-20334.instances.magento-community.engineering/admin](https://pr-20334.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by GovindaSharma** [comment]
Hi @sivaschenko i have now updated the sort in customer edit page in admin side.Please check and update
thank you.

**Comment by sivaschenko** [comment]
Thank you @GovindaSharma !

**Comment by sivaschenko** [comment]
Hi @GovindaSharma during testing we found that fields order is incorrect while editing address for an existing order. Please take a look:
image

**Comment by GovindaSharma** [comment]
Hi @sivaschenko thanks for this update.I will fix it soon.

**Comment by GovindaSharma** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma, here is your [new Magento instance](https://pr-20334.instances.magento-community.engineering).
Admin access: [https://pr-20334.instances.magento-community.engineering/admin](https://pr-20334.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3878](https://jira.corp.magento.com/browse/ENGCOM-3878) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
Hi @GovindaSharma I have tested PR changes and found inconsistency in address form when Address Information is edited from view order page. Could you fix it too?
#20334OrderEditAddress

**Comment by sidolov** [comment]
@GovindaSharma , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
