### PR TITLE
Issue 36060: Can't place order for ordered qty less than 1 with guest…

### LINKED ISSUE #36060: Can't place order for ordered qty less than 1 with guest checkout
### Preconditions and environment

- Magento Open Source Ver. 2.4.5

### Steps to reproduce

1. In admin backend Catalog > Product > Joust Duffle Bag > Advanced Inventory, change qty to 96.75,  Minimum Qty Allowed in Shopping Cart  to 0.5,  Qty Uses Decimals  to Yes
2. In frontend add  Joust Duffle Bag to cart with qty 0.5
3. Go to checkout and place order 

### Expected result

Place order success

### Actual result

Show error message "Some of the products are disabled."

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rogerdz**
### Description (*)
Can't place order for ordered qty less than 1 with guest checkout

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36060

### Manual testing scenarios (*)

1. In admin backend Catalog > Product > Joust Duffle Bag > Advanced Inventory, change qty to 96.75, Minimum Qty Allowed in Shopping Cart to 0.5, Qty Uses Decimals to Yes
2. In frontend add Joust Duffle Bag to cart with qty 0.5
3. Go to checkout and place order

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by danghieu90** [comment]
@magento run Static Tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B, WebAPI Tests

**Comment by engcom-Lima** [comment]
@magento run WebAPI Tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
Install fresh Magento `2.4-develop`

**Manual testing scenario:**
1. In admin backend Catalog > Product > Edit any product > Advanced Inventory>>Minimum Qty Allowed in Shopping Cart to 0.5>>Qty Uses Decimals to Yes
2. In frontend add product to cart with qty 0.5
3. Go to checkout and place order

**Before:** :heavy_multiplication_x: Guest was not able to place an order.
Screenshot 2022-09-02 at 6 57 37 PM

**After:** :heavy_check_mark:  Guest is able to place an order.
Screenshot 2022-09-02 at 7 10 48 PM

Functional Tests B2B, Functional Tests EE checks are failed. Hence, moving this to extended testing.

Thanks

**Comment by engcom-Lima** [comment]
Looking like bot has moved this ticket accidently from Extended Testing to Ready for testing. Hence, moving back to Extended testing.

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento  run Unit Tests

**Comment by engcom-Delta** [comment]
@magento run Functional Tests CE

**Comment by engcom-Delta** [comment]
@magento run Functional Tests CE

**Comment by engcom-Delta** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by engcom-Delta** [comment]
@magento run Functional Tests CE

**Comment by engcom-Delta** [comment]
@magento run Functional Tests CE

**Comment by engcom-Delta** [comment]
@magento run Functional  Tests EE

**Comment by engcom-Delta** [comment]
@magento run Functional Tests EE

**Comment by engcom-Delta** [comment]
All the checks are passed, Hence the moving this PR to Merge in Progress. 

Thanks.

**Pull request merged**
