### PR TITLE
Show first day of the week in dob datepicker based on locale [backport]

### PR DESCRIPTION
**Pull request by joachimVT**
### Description
The frontend datepicker control for the DOB field is not localized: month names, day names and week start date are all using en_US. This pull request fixes this using the first day of the week set in the back office (core_config_data)

Backport for https://github.com/magento/magento2/pull/11057

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/6350

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by dmanners** [comment]
Thanks for the PR @joachimVT I will process this and let you know if I need anymore information.

**Review by dmanners — APPROVED** [review]
Looks good to me. I will process this PR now.

**Comment by dmanners** [comment]
@joachimVT I had an issue when processing this PR that the month and days are not translated as described in https://github.com/magento/magento2/issues/6350

**Comment by okorshenko** [comment]
Hi @joachimVT we are closing this PR due to inactivity. Please, reopen this PR once ready. Thank you

**Pull request closed without merging**
