### PR TITLE
Incorrect http method issue fix

### LINKED ISSUE #39261: 404 when exporting csv and excel in Ordered Products Report
### Preconditions and environment

- Magento 2.4.7-p3

### Steps to reproduce

1. Go to REPORTS > Products > Ordered
2. Select a date range for which the product was sold.
3. Click to Export csv or excel

### Expected result

Exported successfully

### Actual result

Return 404

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Mohamed-Asar**
### Description (*)
Incorrect http method class removed

### Fixed Issues (if relevant)

1. Fixes #39261 

### Manual testing scenarios (*)

1. Go to REPORTS > Products > Ordered
2. Select a date range for which the product was sold.
3. Click to Export csv or excel
4. Verify if the file is exported or not.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Mohamed-Asar** [comment]
@magento run all tests

**Comment by Mohamed-Asar** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
Looks like this issue was already fixed in https://github.com/magento/magento2/commit/7677eb61f8c672cfc0e8984d36e90ca5580e3a4f#diff-ecc0966d790b35f2e889233f04e3ae6d9fe46c4a361a6f67a2aaeb98f9623cf7 (merged to 2.4-develop branch)

**Comment by Mohamed-Asar** [comment]
@ihor-sviziev  Yes This issue was fixed by adobe team, I verified in my local instance with lates 2.4-develop branch

**Comment by hostep** [comment]
@ihor-sviziev: just a random remark, but I always learned that GET requests should only fetch data, never perform "actions". Some browsers sometimes pre-fetch GET requests without any user interaction, if a GET request actually triggers an action, unexpected things can happen without any interaction, which may be very bad.

So no idea if this fix here (or the one from Adobe), is actually a good idea ... As exports can now be triggered by a GET request?
Just my 2 cents.

**Comment by ihor-sviziev** [comment]
@hostep i fully agree with you, but it was like that for a long time. Unfortunately all actions are done with get method in Magento, that’s really stupid.
I would suggest reporting this issue separately, because it will require fixing many different places, both in JS and controllers

**Comment by ihor-sviziev** [comment]
Hi @Mohamed-Asar,
Thanks for confirming, so I’m closing this pull request now

**Pull request closed without merging**
