### PR TITLE
[33099] Set admin field as required while creating Visual Swatch attribute

### LINKED ISSUE #33099: Not showing error message when create attribute at product page
Admin is a required field when create attribute with type is swatch but not showing message when click save button.
### Preconditions (*)

1. Magento 2.4.2EE
2.

### Steps to reproduce (*)

1. Admin -> Catalog -> Product -> Add new product -> Add Attribute -> Create New Attribute
2. Fill Attribute Label -> Choose  Catalog Input Type for Store Owner is Vitual Swatch -> Manage Swatch -> Add Swatch -> Fill Default Store View -> Save Attribute
3. 

### Expected result (*)

1. Display error message: Admin is a required field in each row

### Actual result (*)

1. Not thing happened.
2. 
image

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

120062326-cdc29280-c08b-11eb-91ae-19264fe6c290

Based on exception in console with message` "Admin is a required field in each row"` admin is a required field. 
This PR set admin field as required 

### Actual result
Screenshot 2021-08-13 at 18 32 24

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/33099

### Manual testing scenarios (*)
1. Admin -> Catalog -> Product -> Add new product -> Add Attribute -> Create New Attribute
2. Fill Attribute Label -> Choose Catalog Input Type for Store Owner is Vitual Swatch -> Manage Swatch -> Add Swatch -> Fill Default Store View -> Save Attribute

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by shikhamis11** [comment]
@Usik2203 thank you for your Pull request. It seems a similar error message is showing for `Text Swatch` too, Would you mind fixing it for Text Swatches as well ? Also Please cover your changes with [MFTF](https://devdocs.magento.com/mftf/docs/introduction.html) test.

**Review by shikhamis11 — CHANGES_REQUESTED** [review]
https://github.com/magento/magento2/pull/33795#issuecomment-900382958

**Comment by engcom-Bravo** [comment]
@Usik2203  @shikhamis11  Thanks for your contribution!
@Usik2203 I am working on the requested changes.

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi @shikhamis11 ,

I have worked on the requested changes by you. 

Requesting you for review.

Thank You!

**Comment by shikhamis11** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Review by shikhamis11 — APPROVED** [review]
seems failing tests are not related to this PR

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, thank you for the review.
[ENGCOM-9218](https://jira.corp.magento.com/browse/ENGCOM-9218) has been created to process this Pull Request
:eight_spoked_asterisk: @shikhamis11, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-9218](https://jira.corp.magento.com/browse/ENGCOM-9218) has been created to process this Pull Request

**Comment by eduard13** [comment]
Thank you @engcom-Bravo for the test coverage. Just one remark, that in my opinion the most suitable place for these tests would be `Magento_Swatches` module, since the fixes are related to it. But let's leave them as they are, since I don't see any possible issues.

Thank you.

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Alfa** [comment]
Hi @Usik2203, @eduard13 & @shikhamis11 
Thanks for your contribution and collaboration!

As defined in this PR description I have tried to reproduce the issue and unable to do so! Below are the screenshots with executed steps. Kindly take a look and let me know if there is any other procedure I have to follow.

1. Admin -> Catalog -> Product -> Add new simple product -> Fill product name, sku, quantity, price etc.
2. Configurations section - Create configuration.
3. Create new attribute > Fill Attribute Label > Choose Catalog Input Type for Store Owner is Visual Swatch
4. Manage Swatch > Add Swatch > Fill Default Store View -> Save Attribute

According to the issue description - Attribute is going to be saved without any error message.

But, I found proper error message as shown in below screenshot.
image

Please tell me if my execution steps are deviated somewhere!

**Comment by shikhamis11** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment]
Since a automation test jobs are getting failed continuously. Kind request to update the ticket with the fixes of failures @Usik2203 . Hence moving it back to Changes Requested!

**Comment by engcom-Bravo** [comment]
Hi @engcom-Alfa,

Seems failing tests are not related to this PR.

**Comment by shikhamis11** [comment]
@magento give me test instance

**Comment by shikhamis11** [comment]
@engcom-Alfa as per original issue #33099 Please find below steps to reproduce the issue 

- Admin -> Catalog -> Product -> Add new product -> Add Attribute -> Create New Attribute
- Fill Attribute Label -> Choose Catalog Input Type for Store Owner is Vitual Swatch -> Manage Swatch -> Add Swatch -> Fill Default Store View -> Save Attribute

screen-capture

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Have a Magento latest instance installed with sample data


**Manual testing scenario:**

1. Admin - Catalog - Product - Click on Create a new simple product.

2. Click on "New Attribute" button from the Product form page.
 
3. Try to create new configuration attribute with the type "Text Swatch" or "Visual Swatch" keeping admin field empty.


**Before:** :heavy_multiplication_x: Admin field was not being validated while creating a new attribute from new product creation page
image


**After:** :heavy_check_mark:  Admin field is being validated while creating a new attribute from new product creation page

image


There is no impact on any other feature since it is relevant to a particular field validation in the UI. Also cross checked that the automation failures is not because of PR changes!

**Comment by engcom-Charlie** [comment]
The test case which is failing in this build is related to currency converter API. The build failure is not because of the PR changes and hence moving this to Merge in Progress.

Thank you!

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Pull request merged**
