### PR TITLE
#27091 Removed array print while setup upgrade

### LINKED ISSUE #27091: Magento 2.3.4 array print while setup upgrade
### Preconditions (*)

1. Install Magento 2.3.4 from GitHub.
2. After Install Magento, Execute command php bin/magento s:up

### Steps to reproduce (*)

1.Install Magento 2.3.4 from GitHub.
2.After Install Magento, Execute command php bin/magento s:up

### Expected result (*)

1. Setup Upgrade sucessfully without print array.

### Actual result (*)

1. Print array when setup upgrade.
image

### PR DESCRIPTION
**Pull request by srsathish92**
### Description (*)
This PR helps to remove array print while setup upgrade & installation.

### Fixed Issues (if relevant)
1. fixes magento/magento2#27091

### Manual testing scenarios (*)

1. php bin/magento s:up
2. we shouldn't see printed array content for caches (enabling/disabling)
removed-print-array
3. Check unit test by `vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist setup/src/Magento/Setup/Test/Unit/Model/InstallerTest.php`

### Questions or comments
If any please let me know your feedback

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by aleron75 — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-7265](https://jira.corp.magento.com/browse/ENGCOM-7265) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

Run in console: `php bin/magento setup:upgrade`

**Before:**
arraybefore

**After:**
Screenshot from 2020-04-08 13-46-52

**Review by slavvka — CHANGES_REQUESTED** [review]
@srsathish92 please resolve the conflicts and re-run tests after upgrade to PHP 7.4

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by slavvka — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @slavvka, thank you for the review.
[ENGCOM-7265](https://jira.corp.magento.com/browse/ENGCOM-7265) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

Run in console: `php bin/magento setup:upgrade`

**Before:** :heavy_multiplication_x: 
screenshot_17

**After:** :heavy_check_mark: 
screenshot_18

**Comment by engcom-Echo** [comment]
@magento run all tests

**Pull request merged**
