### PR TITLE
[TODO] Move getting order history logic from block to the separate model and divided it into methods

### PR DESCRIPTION
**Pull request by coderimus**
### Description
In the `Magento\Sales\Block\Adminhtml\Order\View\Tab\History` I found next TODO:
"TODO This method requires refactoring. Need to create separate model for comment history handling"
The simple model was made based on the code from the history block. Currently, it can return information about the shipments, invoices, trackings, credit memos and full history data which collect all of this info.

### Fixed Issues (if relevant)
Finish TODO

### Manual testing scenarios
N/A

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by coderimus** [comment]
Hello @orlangur ,
Can I ask you to review this PR? I would be grateful if you will have time and can check provided changes.
Looking forward to your reply,
Alex

**Comment by okorshenko** [comment]
Hi @Coderimus 
I would recommend submit this PR to 2.3-develop branch. It is not allowed to introduce new API in patch releases. In this case this PR will higher chances to be accepted.

**Comment by coderimus** [comment]
Hi @okorshenko 
Thank you for the response! I will transfer provided changes to the 2.3-develop ASAP (during the day 2018.02.08)

**Comment by coderimus** [comment]
Hi @okorshenko 
I submitted changes provided in this PR to the 2.3-develop branch - [#13565](https://github.com/magento/magento2/pull/13565) Should I close current PR or if new PR to the 2.3-develop branch will be approved I can backport it to the 2.2-develop using this one? Please, advise the best choice in this case. Thank you!

**Comment by okorshenko** [comment]
Hi @Coderimus 
We will review the PR for 2.3-develop branch, but we can not introduce new api in 2.2. So closing this PR

**Pull request closed without merging**
