### PR TITLE
Fix sitemap grid render incorrect base urls for multiple stores

### PR DESCRIPTION
**Pull request by nntoan**
### Description

In `Magento/Sitemap/Block/Adminhtml/Grid/Renderer/Link.php`, we've created new instance for `\Magento\Sitemap\Model\Sitemap`. That lead to `$sitemap->getStoreId()` is `NULL` all the time, the `sitemap.xml` generated still using correct store id because of we load `$sitemap` instance from the collection which retrieve data directly from the database.

So to fix this issue, we should set the store id for the current sitemap object based on store id retrieved from the current row.

### Fixed Issues (if relevant)

1. magento/magento2#17999: Sitemap grid display incorrect base URL in the grid if using multiple stores

### Manual testing scenarios

1. Setup multiple store views with different base urls, (default config base url must be different with all other store view base url)
2. Go to Marketing > SEO & Search > Site Map
3. Check if Actual Result in #17999 does not happen. It suppose to display something like this:
screenshot from 2018-09-10 17-04-44

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18000) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @nntoan. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by nntoan** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @nntoan. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @nntoan, here is your [new Magento instance](https://pr-18000.engcom.dev.magento.com).
Admin access: [https://pr-18000.engcom.dev.magento.com/admin](https://pr-18000.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3008](https://jira.corp.magento.com/browse/ENGCOM-3008) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@nntoan thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @nntoan. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
