### PR TITLE
[improvement] Added the ability for customers to set how much items to show per page in the shopping cart

### PR DESCRIPTION
**Pull request by vasilii-b**
### Description (*)

This PR adds the possibility to choose from the toolbar's pager limiter how many items to show per page on the shopping cart.

image

Previously this was not possible because of the limiter's options set to one value only
https://github.com/magento/magento2/blob/78bb169ff9721c8d05c35b4c29a4464fd45bccbe/app/code/Magento/Checkout/Block/Cart/Grid.php#L112-L119

**Affected functionality**
The PR adds changes to the shopping cart page (storefront), specifically the cart items toolbar.
Also, it adjusts the store system configuration for the shopping cart: _Stores -> Configuration -> Sales -> Checkout -> Shopping Cart_

image

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (before added changes) (*)

**Preconditions**
Magento 2.2 and upper with sample data

1. Open admin area
2. Go to _Stores -> Configuration -> Sales -> Checkout -> Shopping Cart -> Number of Items to Display Pager_ and set the value to 5
3. Go to the storefront
4. Add 6 or more products to the shopping cart
5. Go to the shopping cart
6. See the toolbar and the possibility to navigate through pages
7. See that there is no possibility to set how much items to show per page

### Manual testing scenarios (after added changes) (*)

**Preconditions**
Magento 2.2 and upper with sample data

1. Open admin area
2. Go to _Stores -> Configuration -> Sales -> Checkout -> Shopping Cart -> Items per Page Default Value_ and set the value to 10
3. Go to the storefront
4. Add 11 or more products to the shopping cart
5. Go to the shopping cart
6. See the toolbar and the possibility to navigate through pages
7. See that there is the possibility to set how much items to show per page, as defined in _Stores -> Configuration -> Sales -> Checkout -> Shopping Cart -> Items per Page Allowed Values_

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by vasilii-b** [comment]
**Update**: I'll adjust the Unit tests and prepare the MFTF test once the initial idea of the PR is approved.
Thank you!

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello, @vasilii-b great job!
I don't see any reasons why this improvement might be rejected.

Could you please proceed with test coverage and adjustments according to the static test report?

Thank you!

**Comment by vasilii-b** [comment]
Thanks @dmytro-ch,
I'll proceed with the MFTF and static tests fixes.

**Comment by vasilii-b** [comment]
Hi @dmytro-ch,
Could you please advise how to proceed here? The failed test doesn't seem related to the changes in the PR, as for me. Can you please have a look?
Thanks a lot!

**Review by dmytro-ch — DISMISSED** [review]
Hello, @vasilii-b, thank you for the updates!
The tests failures are not related to the current changes. Please ignore them.

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7190](https://jira.corp.magento.com/browse/ENGCOM-7190) has been created to process this Pull Request

**Review by engcom-Bravo — CHANGES_REQUESTED** [review]
There is a UI issue on the Storefront. 
If the number of items in Cart, is less than the _per page_ number, for example 12 items in Cart, 20 - _per page_,  the pages switcher _( **<** 1 2 **>** )_ disappear and there is no margin between _Show per page_ and the _horizontal line_
pr_27247_front

**Comment by vasilii-b** [comment]
Hi @engcom-Bravo, @dmytro-ch,
I've added needed changes to adjust the styles.
shopping-cart-top-toolbar-space-below

image


Could you please proceed with the review one more time?

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7190](https://jira.corp.magento.com/browse/ENGCOM-7190) has been created to process this Pull Request

**Review by engcom-Bravo — COMMENTED** [review]
:heavy_check_mark: QA Passed 
27242_cart

**Comment by engcom-Echo** [comment]
@magento run Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Echo** [comment]
@magento run Database Compare, Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Database Compare

**Comment by slavvka** [comment]
There's a performance degradation:
```
tideways-mysql-select-requests-count
Open Cart (Add To Cart By Customer): 12.6% (mainline = 111 | team = 125) -> DEGRADATION

   SQLs were removed from mainline: 
      
   SQLs were added to team: 
       SELECT COUNT(*) FROM `quote_item` AS `main_table` WHERE (`quote_id` = '88') AND (`parent_item_id` IS NULL)
       SELECT `main_table`.* FROM `quote_item` AS `main_table` WHERE (`quote_id` = '88') AND (`parent_item_id` IS NULL) LIMIT 20
       SELECT `e`.`entity_id` FROM `catalog_product_flat_1` AS `e` WHERE (e.entity_id IN(13, 21, 868))
       SELECT `main_table`.* FROM `quote_item_option` AS `main_table` WHERE (`item_id` IN(174, 175, 176))
       SELECT DISTINCT ea.attribute_code FROM `salesrule_product_attribute` AS `a` INNER JOIN `eav_attribute` AS `ea` ON ea.attribute_id = a.attribute_id
       SELECT 1 AS `status`, `e`.`entity_id`, `e`.`attribute_set_id`, `e`.`type_id`, `e`.`created_at`, `e`.`updated_at`, `e`.`sku`, `e`.`price_view`, `e`.`price_type`, `e`.`weight_type`, `e`.`sku_type`, `e`.`sku`, `e`.`type_id`, `e`.`name`, `e`.`visibility`, `e`.`price`, `e`.`weight`, `e`.`url_path`, `e`.`url_key`, `e`.`thumbnail`, `e`.`small_image`, `e`.`tax_class_id`, `e`.`special_from_date`, `e`.`special_to_date`, `e`.`special_price`, `e`.`cost`, `e`.`gift_message_available`, `e`.`msrp`, `e`.`msrp_display_actual_price_type`, `e`.`links_purchased_separately`, `e`.`links_title`, `e`.`giftcard_type`, `e`.`giftcard_amounts`, `e`.`allow_open_amount`, `e`.`open_amount_min`, `e`.`open_amount_max`, `e`.`use_config_lifetime`, `e`.`lifetime`, `e`.`use_config_is_redeemable`, `e`.`is_redeemable`, `e`.`use_config_email_template`, `e`.`email_template`, `e`.`gift_wrapping_available`, `e`.`gift_wrapping_price`, `product_entity`.`row_id` FROM `catalog_product_flat_1` AS `e` INNER JOIN `catalog_product_entity` AS `product_entity` ON product_entity.entity_id = e.entity_id AND (product_entity.created_in <= 1 AND product_entity.updated_in > 1) WHERE (e.entity_id IN(13, 21, 868, 13, 21, 868, 857))
       SELECT `catalog_category_product`.`product_id`, `catalog_category_product`.`category_id` FROM `catalog_category_product` WHERE (product_id IN (13, 21, 857, 868))
       SELECT `main_table`.*, `default_option_title`.`title` AS `default_title`, `store_option_title`.`title` AS `store_title`, IF(store_option_title.title IS NULL, default_option_title.title, store_option_title.title) AS `title`, `default_option_price`.`price` AS `default_price`, `default_option_price`.`price_type` AS `default_price_type`, `store_option_price`.`price` AS `store_price`, `store_option_price`.`price_type` AS `store_price_type`, IF(store_option_price.price IS NULL, default_option_price.price, store_option_price.price) AS `price`, IF(store_option_price.price_type IS NULL, default_option_price.price_type, store_option_price.price_type) AS `price_type` FROM `catalog_product_option` AS `main_table` INNER JOIN `catalog_product_entity` AS `cpe` ON cpe.row_id = main_table.product_id AND (cpe.created_in <= 1 AND cpe.updated_in > 1) INNER JOIN `catalog_product_option_title` AS `default_option_title` ON default_option_title.option_id = main_table.option_id LEFT JOIN `catalog_product_option_title` AS `store_option_title` ON store_option_title.option_id = main_table.option_id AND store_option_title.store_id = '1' LEFT JOIN `catalog_product_option_price` AS `default_option_price` ON default_option_price.option_id = main_table.option_id AND default_option_price.store_id = 0 LEFT JOIN `catalog_product_option_price` AS `store_option_price` ON store_option_price.option_id = main_table.option_id AND store_option_price.store_id = '1' WHERE (default_option_title.store_id = 0) AND (`product_id` IN(13, 21, 857, 868))
       SELECT `url_rewrite`.*, `relation`.`category_id`, `relation`.`product_id` FROM `url_rewrite` LEFT JOIN `catalog_url_rewrite_product_category` AS `relation` ON url_rewrite.url_rewrite_id = relation.url_rewrite_id WHERE (url_rewrite.entity_type IN ('product')) AND (url_rewrite.entity_id IN ('13', '21', '857', '868')) AND (url_rewrite.store_id IN (1)) AND (url_rewrite.is_autogenerated IN (1)) AND (relation.category_id IS NULL)
       SELECT `catalogrule_product_price`.`product_id`, `catalogrule_product_price`.`rule_price` FROM `catalogrule_product_price` WHERE (rule_date = '2020-04-02') AND (website_id = '1') AND (customer_group_id = '1') AND (product_id IN('13', '21', '857', '868'))
       SELECT `main_table`.*, `cp_table`.`type_id` FROM `cataloginventory_stock_item` AS `main_table` INNER JOIN `catalog_product_entity` AS `cp_table` ON main_table.product_id = cp_table.entity_id AND (cp_table.created_in <= 1 AND cp_table.updated_in > 1) WHERE (`main_table`.`product_id` IN(13, 21, 857, 868)) AND (`main_table`.`website_id` = '0')
       SELECT `main_table`.* FROM `catalog_product_super_attribute` AS `main_table` WHERE (((((`product_id` = '868'))))) ORDER BY position  ASC
       SELECT `def`.*, IF(store.use_default IS NULL, def.use_default, store.use_default) AS `use_default`, IF(store.value IS NULL, def.value, store.value) AS `label` FROM `catalog_product_super_attribute_label` AS `def` LEFT JOIN `catalog_product_super_attribute_label` AS `store` ON store.product_super_attribute_id = def.product_super_attribute_id AND store.store_id = 1 WHERE (def.product_super_attribute_id IN (16)) AND (def.store_id = 0)
       SELECT `entity`.`sku`, `product_entity`.`entity_id` AS `product_id`, `attribute`.`attribute_code`, `entity_value`.`value` AS `value_index`, `attribute_label`.`value` AS `super_attribute_label` FROM `catalog_product_super_attribute` AS `super_attribute` INNER JOIN `catalog_product_entity` AS `product_entity` ON product_entity.row_id = super_attribute.product_id AND (product_entity.created_in <= 1 AND product_entity.updated_in > 1) INNER JOIN `catalog_product_super_link` AS `product_link` ON product_link.parent_id = super_attribute.product_id INNER JOIN `eav_attribute` AS `attribute` ON attribute.attribute_id = super_attribute.attribute_id INNER JOIN `catalog_product_entity` AS `entity` ON entity.entity_id = product_link.product_id AND (entity.created_in <= 1 AND entity.updated_in > 1) INNER JOIN `catalog_product_entity_int` AS `entity_value` ON entity_value.attribute_id = super_attribute.attribute_id AND entity_value.store_id = 0 AND entity_value.row_id = entity.row_id LEFT JOIN `catalog_product_super_attribute_label` AS `attribute_label` ON super_attribute.product_super_attribute_id = attribute_label.product_super_attribute_id AND attribute_label.store_id = 0 LEFT JOIN `eav_attribute_option` AS `attribute_option` ON attribute_option.option_id = entity_value.value INNER JOIN `cataloginventory_stock_status` AS `stock` ON stock.product_id = entity.entity_id WHERE (super_attribute.product_id = 868) AND (attribute.attribute_id = '181') AND (stock.stock_status = 1) ORDER BY `attribute_option`.`sort_order` ASC
```

**Comment by vasilii-b** [comment]
Hi @slavvka,
Thanks for noting this. Interesting results.
As far as I understand, the results are based on the following preconditions:
1. use EE version
2. add products to cart with a logged-in customer
Is it correct?
How can I run the same tests on the local machine to check the "degradation"?
Doesn't it seem strange that only a `LIMIT 20` added to the query makes a degradation of 12.6%?
How would you recommend proceeding with this?
Thank you!

**Comment by slavvka** [comment]
Hi @vasilii-b. Yes the results are strange so that;t why we put it on hold.

**Comment by mslabko** [comment]
Hi @vasilii-b ,

You are right, tests performed on EE version with several products on Cart (2 simple and 1 configurable) 
You can see the whole scenario in https://github.com/magento/magento2ce/blob/2.4-develop/setup/performance-toolkit/benchmark.jmx

I agree that results are strange and here some clues which may help to investigate this:
We can enable query logging with trace and try to figure out when and why they happen:
```
bin/magento  dev:query-log:enable --query-time-threshold=0 --include-call-stack=true
```

Additionally, you can watch \Zend_Db_Adapter_Pdo_Abstract::query which we use to collect SQL queries "before" and "after" PR

**Comment by vasilii-b** [comment]
Hi @mslabko,
Thanks for the direction. Unfortunately, I cannot open the given link due to missing privileges most probably.

**Comment by slavvka** [comment]
@vasilii-b https://github.com/magento/magento2/blob/2.4-develop/setup/performance-toolkit/benchmark.jmx

**Comment by dmytro-ch** [comment]
Hello @vasilii-b, unfortunately, I have to close this PR due to inactivity.
Feel free to reopen and update if you wish to continue.
Thank you!

**Pull request closed without merging**
