### PR TITLE
Make the header switcher styles more flexible

### PR DESCRIPTION
**Pull request by vasilii-b**
### Description (*)
This PR aims to make the switcher styles in the header more specific: the desktop styles must not apply for mobile as well.

**description from the original (abandoned) PR**
The issue I encountered was related to the duplicated store switcher block for the mobile navigation, which is part of the navigation.sections.

The styling which is here added for the dropdown of the store switcher for the desktop variant, is currently also applied to the mobile variant when moved into the header-wrapper (to have the category navigation on Desktop between logo and other Header Parts)

### Related Pull Requests
1. https://github.com/magento/magento2/pull/26879 - make store switcher style more resistent

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
1. have a layout xml which moves the navigation.sectionsinto the `header-wrapper``
```xml
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <move element="navigation.sections" destination="header-wrapper" after="logo"/>
    </body>
</page>
```
2. reduce the Website to "mobile size" (320px or 375ox wide) and check the store switcher in the mobile navigation

### Result

The changes affect both _Blank_ and _Luma_ themes

**Blank**

| Desktop | Mobile |
| -------- | ------- |
| result-blank-desktop | result-blank-mobile |

**Luma**

| Desktop | Mobile |
| -------- | ------- |
| result-luma-desktop | result-luma-mobile |

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by VitaliyBoyko** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @VitaliyBoyko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @VitaliyBoyko, here is your [new Magento instance](https://pr-27495.instances.magento-community.engineering).
Admin access: [https://pr-27495.instances.magento-community.engineering/admin_29ed](https://pr-27495.instances.magento-community.engineering/admin_29ed)
Login: `ff85d71c` Password: `7774ea0a8785`
Instance will be terminated in up to 3 hours.

**Comment by VitaliyBoyko** [comment]
Looks good ✅ 
Switcher desktop:
image
Switcher mobile:
image

**Review by VitaliyBoyko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VitaliyBoyko, thank you for the review.
[ENGCOM-7226](https://jira.corp.magento.com/browse/ENGCOM-7226) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before (luma):**
Screenshot from 2020-03-31 12-28-19
**Before (blank):**
Screenshot from 2020-03-31 13-13-21

**After(luma):**
_mobile_
Screenshot from 2020-03-31 12-41-11
_desktop_
Screenshot from 2020-03-31 12-49-16

**After(blank):**
_mobile_
Screenshot from 2020-03-31 13-04-58

_desktop_
Screenshot from 2020-03-31 13-01-08

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Echo** [comment]
@magento run Unit tests

**Comment by engcom-Echo** [comment]
@magento run Unit Tests

**Pull request merged**
