### PR TITLE
#9439 Save region details in order address edit.

### PR DESCRIPTION
**Pull request by heyqule**
Region is missing in admin order view after order edit.  The reason is that the address only save region ID.

This fixes AddressSave controller to save region code and name.

### Manual testing scenarios
1. View pending/processing order in the admin panel
2. Edit billing or shipping address of the order
3. Change State/Region field by selecting it from dropdown menu
4. Save

State/Region should now changed to new region or keep existing region if there is no change.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=9511) <br/>All committers have signed the CLA.

**Comment by okorshenko** [comment]
@heyqule thank you for Pull Request. Could you please please fix class constructor following our backward Compatibility requirement: [Adding a constructor parameter](http://devdocs.magento.com/guides/v2.0/contributor-guide/backward-compatible-development/#adding-a-constructor-parameter)

Please, make new class property `private` 

Thank you

**Comment by heyqule** [comment]
@okorshenko  Hi.  Do you have a moment to review the update?

**Comment by okorshenko** [comment]
Hi @heyqule 
Thank you for you contribution. We verified the functionality on latest code from **develop** branch and this issue does not exists (following Manual testing scenarios). But the issues exists in **2.1-develop** branch. If you are interested in this fix, you may analyze how this was done in develop branch and backport the solution to 2.1-develop branch.

Closing this PR.

**Pull request closed without merging**
