### PR TITLE
Improve comment message

### PR DESCRIPTION
**Pull request by gelanivishal**
### Description
Added exception message in library.

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios

N/A
### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by avoelkl — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @avoelkl, thank you for the review.
[ENGCOM-2154](https://jira.corp.magento.com/browse/ENGCOM-2154) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.6. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Comment by arnoudhgz** [comment]
@magento-engcom-team this is already in `2.3-develop`

**Comment by nmalevanec** [comment]
No need for forwardport. Already been fixed in https://github.com/magento/magento2/pull/15498

**Pull request merged**
