### PR TITLE
Set first name and last name with Validated Rules working

### PR DESCRIPTION
**Pull request by RakeshJesadiya**
Resolved the default bug for the First name and last name attribute with minimum and maximum character length not working for Magento 2.3 version.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21560) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=21560) before we can accept your contribution.<br/>**4** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: XxXgeoXxX<br/>:white_check_mark: nmalevanec<br/>:white_check_mark: VitaliyBoyko<br/>:white_check_mark: magento-engcom-team<br/>:x: tomreece<br/>:x: cpartica<br/>:x: joanhe<br/>:x: magento-cicd2<br/>:x: naydav<br/>:x: kanair

**Comment by magento-engcom-team** [comment]
Hi @RakeshJesadiya

Unfortunately, we cannot accept Pull Requests from branches created in `magento2` repository.
Please use your own fork as a base for this Pull Request.

Thank you.

**Comment by magento-engcom-team** [comment]
Hi @RakeshJesadiya
Unfortunately, we only accept Pull Requests to the following branches: 2.2-develop, 2.3-develop.
Please create a new Pull Request and use one of those as a target.

Thank you.

**Comment by RakeshJesadiya** [comment]
Wrong PR

**Pull request closed without merging**
