### PR TITLE
Reduce unnecessary padding for page layout 2columns

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

This is small changes
We don't need to add extra spacing from both direction. If page layout 2-columns-left, padding from sidebar is enough for layout, no need spacing for main content area
Current we have green blur area (indicated for padding box) from left of main content area in 2columns-left layout
Remove that padding (left side) will give us extra space back for main content area

Screenshot from 2021-07-18 09-24-03

Before fix visual:
before-account

After fix visual:
after-account

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Unit Tests, Functional Tests CE, Functional Tests B2B

**Comment by mrtuvn** [comment]
@magento run Unit Tests, Functional Tests CE, Functional Tests B2B

**Comment by mrtuvn** [comment]
@magento run Unit Tests, Functional Tests CE

**Comment by mrtuvn** [comment]
@magento run Unit Tests, Functional Tests CE

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE

**Review by Den4ik — APPROVED** [review]
✅ Update looks good for me.
@mrtuvn Thanks for your work

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9162](https://jira.corp.magento.com/browse/ENGCOM-9162) has been created to process this Pull Request

**Pull request closed without merging**
