### PR TITLE
MFTF: Share Wishlist with Enabled Captcha Test

### PR DESCRIPTION
**Pull request by DmitryTsymbal**
This PR contains two MFTF tests for submitting share wishlist form with enabled captcha

**Steps to reproduce:**

1 - Enable captcha on  share wishlist form
2 - Create product
3 - Create customer
4 - Login as customer
5 - Add created product into wishlist
6 - Navigate to wishlist
7 - Share wishlist with incorrect captcha
8 - Share wishlist with correct captcha
9 - Perform assertions

### CODE REVIEW

**Comment by DmitryTsymbal** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by dmytro-ch** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B , Functional Tests CE , Functional Tests EE

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B , Functional Tests CE , Functional Tests EE

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello @DmitryTsymbal,
Thank you for your contribution!
Could you please check the failure for `StorefrontCaptchaOnShareWishlistFormTest`?

**Comment by DmitryTsymbal** [comment]
@magento run all tests

**Comment by DmitryTsymbal** [comment]
@magento run all tests

**Comment by DmitryTsymbal** [comment]
Hi @dmytro-ch . Thank you for review!
The root of issue was in impossibility click the "Share wishlist" button element, after notification about incorrect captcha appeared.

As a workaround I have added "scrollTo" attribute before clicking the element.
Could you please clarify if we are fine with this approach?
For now, we have only Functional Tests B2B failed, I'm not sure it's related to my changes.
Thanks!

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Dash** [comment]
Hello @DmitryTsymbal,

Thank you for your contributions!

Please resolve the conflict so we can proceed with this PR.

Thanks again!

**Comment by engcom-Dash** [comment]
Closing this PR since it has not been updated in a while. Please feel free to reopen if needed.

**Pull request closed without merging**
