### PR TITLE
[TEST PR] DO NOT PROCESS

### PR DESCRIPTION
**Pull request by super-user-test-tool**
### Description (*)

Pull request is created to demonstrate the new contribution model and patch delivery flow.

### Fixed Issues (if relevant)

1. None

### Release Notes

Release notes related to update readme.md file in order to demo new contribution model support

### Categories

Performance, Checkout

### Manual testing scenarios (*)

1. Step 1
2. Step 2

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Review by ihor-sviziev — DISMISSED** [review]

**Review by sidolov — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Review by sidolov — DISMISSED** [review]

**Comment by m2-github-services** [comment]
@sidolov thank you for the review! We have changed pull request base branch in order to provide ability to merge current pull request and schedule MQP patch delivery job.

**Comment by sidolov** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Review by sidolov — DISMISSED** [review]

**Review by gabrieldagama — DISMISSED** [review]

**Review by sivaschenko — DISMISSED** [review]

**Review by gabrieldagama — APPROVED** [review]

**Comment by m2-github-services** [comment]
@sidolov MQP patch delivery job is successfully scheduled! Link to the MQP pull request will be provided as soon as it's created

**Comment by m2-github-services** [comment]
Pull request with MQP patch was successfully created, available by the link: magento/quality-patches#54

**Pull request merged**
