### PR TITLE
#16273: [Backport] Fix bug in method getUrlInStore() of product model

### PR DESCRIPTION
**Pull request by vasilii-b**
### Original PR 
https://github.com/magento/magento2/pull/16468

### Description
This PR reference changes how/what is returned when `product` model method `getUrlInStore()` is called `$product->getUrlInStore()`.
Problem is in how the current store is checked and what is returned based on it.

### Fixed Issues
1. magento/magento2#16273
2. Having set _Add store code to URLs_ in Admin Configuration to _NO_, store code is still shown in the product URL.

### Manual testing scenarios

__For issue 1__ - please see the issue description.
__For issue 2__:

1. Go to Admin -> Stores -> Configuration -> Catalog -> Web -> Url Options -> Add Store Code to Urls and set it to NO.
2. In some `.phtml` file, list.phtml for example, call method `getUrlInStore()` for a product.

#### Expected Result
Store code is not added into product url
```
https://www.domain.com/my-product.html
```

#### Actual Result
Store code is added into product url
```
https://www.domain.com/my-product.html?___store=default
```

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by sidolov** [comment]
Hi @vasilii-b , please, take a look at failed unit tests

**Comment by vasilii-b** [comment]
Hi @sidolov, can you please help with failed test ? Is it possible to re-run them ? Thrown issues are not related to the current PR.
Thank you!

**Comment by sidolov** [comment]
Hi @vasilii-b , jobs restarted

**Comment by vasilii-b** [comment]
@sidolov please have a look on the tests again. It was failed again (only 1) with no-related PR issues. Thank you!

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your contribution. 
We will aim to release these changes as part of 2.1.16. 
Please check the release notes for final confirmation.

**Comment by apedicdev** [comment]
sorry but I'm confused about this functionality.
As per:
```
/**
     * Returns whether url forming scheme prepends url path with store view code
     *
     * @return boolean
     */
    public function isUseStoreInUrl()
    {
        return !($this->hasDisableStoreInUrl() && $this->getDisableStoreInUrl())
            && $this->getConfig(self::XML_PATH_STORE_IN_URL);
    }

```

and:
```
if (!$this->isUseStoreInUrl()) {
            $storeParsedQuery['___store'] = $this->getCode();
        }

```

when Use store in url is off then `___store` should be appended. Vice versa, if is on, then the store_code will be used as store_prefix. 
So, if I'm not wrong, the fix released in 2.2.6 is not correct.

**Pull request merged**
