### PR TITLE
Download link does not get rendered in invoice email

### PR DESCRIPTION
**Pull request by jaykobi**
Download link does not get rendered in invoice email

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=11024) <br/>All committers have signed the CLA.

**Comment by miguelbalparda** [comment]
This seems to be breaking some tests, can you check them and report back?

**Comment by miguelbalparda** [comment]
Also, could you please edit this PR description to use the correct template?

**Comment by dmanners** [comment]
@skymeissner it looks like the unit test is failing as you have updated the method called in the `getLinks` method and as such you will also need to update the method mocked in the `Magento\Downloadable\Test\Unit\Block\Sales\Order\Email\Items\DownloadableTest` class. Are you able to update this so we can progress with the pull request?

**Pull request merged**
