### PR TITLE
backport  #28137  to 2.3

### PR DESCRIPTION
**Pull request by jonashrem**
backports #24353  to Magento 2.3

### Description (*)
this backports the fix  #28137 for #24353 to Magento 2.3 as the issue can happen there  as well

### Related Pull Requests
https://github.com/magento-commerce/magento2-infrastructure/pull/1612

### Fixed Issues (if relevant)
1. #24353

### Release Notes

Fixes issue with Varnish 6 when 503 error was returned and VCL error Too many restarts in logs

### Categories

Payments

### Manual testing scenarios (*)
/

### Questions or comments
/
### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - x ] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — DISMISSED** [review]

**Comment by m2-github-services** [comment]
@ihor-sviziev thank you for the review! We have changed pull request base branch in order to provide ability to merge current pull request and schedule quality patch delivery job.

**Review by ihor-sviziev — DISMISSED** [review]

**Comment by m2-github-services** [comment]
@ihor-sviziev thank you for the review! We have changed pull request base branch in order to provide ability to merge current pull request and schedule quality patch delivery job.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by andrewbess — DISMISSED** [review]

**Comment by m2-github-services** [comment]
@andrewbess thank you for the review! We have changed pull request base branch in order to provide ability to merge current pull request and schedule quality patch delivery job.

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Comment by sidolov** [comment]
@magento run Static Tests

**Comment by sidolov** [comment]
@magento run Static Tests

**Comment by sidolov** [comment]
@magento run Static Tests

**Review by sidolov — DISMISSED** [review]

**Review by sidolov — APPROVED** [review]

**Pull request merged**
