### PR TITLE
[Forwardport] CSS load order incorrect using default_head_blocks.xml #1821

### PR DESCRIPTION
**Pull request by nmalevanec**
### Original Pull Request 
 https://github.com/magento/magento2/pull/14290

Added new attribute 'order' for set loading order .
Those attribute resolve issue about render files for some order.

### Fixed Issues (if relevant)
1. magento/magento2#1821: CSS load order incorrect using default_head_blocks.xml #1821

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @nmalevanec. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by osrecio — APPROVED** [review]
Thanks @nmalevanec for your PR. We will process your PR ASAP.

**Comment by magento-engcom-team** [comment]
Hi @osrecio, thank you for the review.
[ENGCOM-2891](https://jira.corp.magento.com/browse/ENGCOM-2891) has been created to process this Pull Request

**Review by williankeller — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @nmalevanec. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Pull request merged**
