### PR TITLE
Usps add new allowed methods

### PR DESCRIPTION
**Pull request by Franciscof-Serfe**
### Description (*)

USPS made significant changes to its API since July 9 where it proposes a new service "USPS - Ground Advantage" instead of "First Class Package Service"

image

So this PR is created in order to quickly activate the new shipping method proposed by USPS.

The deprecated methods can be used until September 2023.
Attached note sent by USPS
[USPS Grace Period.pdf](https://github.com/magento/magento2/files/12010384/USPS.Grace.Period.pdf)
[USPS Release Notes - Backwards Comp.pdf](https://github.com/magento/magento2/files/12010386/USPS.Release.Notes.-.Backwards.Comp.pdf)

Reference: 
API TOOL DOC: https://www.usps.com/business/web-tools-apis/2023-web-tools-release-notes.pdf

### Related Pull Requests

Reported Issue: [magento/magento2#37742]

### Fixed Issues (if relevant)

magento/magento2#37742
Related to MAGETWO-47504 commit: https://github.com/magento/magento2/commit/0932cd3cab435a1c4a051a7b5e4aefeef930d231

### Manual testing scenarios (*)

* You must have a test API in order to activate the USPS shipping method https://www.usps.com/business/web-tools-apis/#

1. From the backend > store > configuration > SALES > Delivery Methods > USPS > Allowed Methods
2. You will be able to select the new methods related to "USPS Ground Advantage"
3. With these methods selected and USPS enabled we can verify the frontend
4. Add to cart a product less than 70lbs in weight.
5. See in viewCart or Checkout, completing a real address, the active shipping methods should have "USPS Ground Advantage" among those enabled.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Franciscof-Serfe** [comment]
@magento run all tests

**Comment by Franciscof-Serfe** [comment]
@magento run all tests

**Comment by Franciscof-Serfe** [comment]
@magento give me test instance

**Comment by Abbey-Lubber** [comment]
possible duplicate line still in /i18n/en_US.csv leftover from deleting usps api '7' lines:

`"USPS Ground Advantage (up to 15.999 oz)","USPS Ground Advantage (up to 15.999 oz)"
"USPS Ground Advantage LIVES, Offshore","USPS Ground Advantage LIVES, Offshore"
"USPS Ground Advantage (up to 15.999 oz)","USPS Ground Advantage (up to 15.999 oz)"

**Comment by Abbey-Lubber** [comment]
After applying your code changes to a test website and selecting the new methods on the backend
image
I'm seeing this on my test website frontend
image
Am I forgetting some important step after patching?

**Comment by esteban-serfe** [comment]
Hi @Abbey-Lubber we are still working on the changes for this PR for a customer of our company...
Thanks for mentioning the translation element on the comments!

Will keep the comments updated here with the advances.

**Comment by stormearthfire** [comment]
Hi @Franciscof-Serfe any particular reason you dropped out "Media Mail" shipping method? If I'm not mistaken it should still be in use after all of this.

**Comment by esteban-serfe** [comment]
Hi @stormearthfire, we have updated the MR to have the option to list the new shipping methods and reverted the previous changes. The shipping method should be available on the new version.

**Comment by esteban-serfe** [comment]
@magento run all tests

**Comment by Abbey-Lubber** [comment]
Still testing but looks like you might have a working solution!
image

**Comment by Franciscof-Serfe** [comment]
@magento give me test instance
@magento run all tests

**Comment by Franciscof-Serfe** [comment]
Hi everyone,
  We have managed to fix the problem related to USPS not showing the shipping methods.
  
  This is what is validated in the generated test instance:
- [x] Backend view:
image

- [x] Shopping Cart view: 
image

- [x] Checkout view: 
image

- [x] Payment view: 
image

- [x] Backend order view: 
image

- [x] Print shipment view: 
image

I am finishing fixing what was reported by the tests so that the PR is ready.
Regards, 
Francisco

**Comment by Franciscof-Serfe** [comment]
@magento run all tests

**Comment by Franciscof-Serfe** [comment]
@magento I am working on this

**Comment by Franciscof-Serfe** [comment]
Hi @engcom-Hotel,
 I understand that the tests that are failing are not directly related to the changes made to this PR.

Could you confirm it so we can give a solution to those who use this delivery system?

Thank you so much!

**Comment by bmatiichak** [comment]
@Franciscof-Serfe can we use this fix, or is it not quite stable yet?

**Comment by Franciscof-Serfe** [comment]
Hi @bmatiichak ,
We are using this fix on live sites with no issues.
I leave you the composer patch so you can validate it quickly. [usps-add-new-methods.zip](https://github.com/magento/magento2/files/12240580/usps-add-new-methods.zip)

In this comment I left the validation performed on the Magento instance with the changes made. https://github.com/magento/magento2/pull/37745#issuecomment-1646083016

I await your verification.

**Comment by Franciscof-Serfe** [comment]
> I leave you the composer patch so you can validate it quickly. [usps-add-new-methods.zip](https://github.com/magento/magento2/files/12240580/usps-add-new-methods.zip)

**Great news everyone!**

Magento used my composer Patch to generate the official hotFix AC-9182:
https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/known-issues-patches-attached/usps-ground-advantage-shipping-method-support-hotfix-for-ac-9182.html

**Comment by seoradu** [comment]
guys, can any of you point me to find out the fix for magento 2.4.2?
Thank you

**Comment by esteban-serfe** [comment]
> guys, can any of you point me to find out the fix for magento 2.4.2? Thank you

Hi seoradu,

We've encountered a similar issue with Magento 2.4.2, and we were able to resolve it. If you'd like assistance or more information on the fix, feel free to reach out to us at https://www.serfe.com/en/contact-us
We'd be happy to help!

**Comment by andrewbess** [comment]
This PR already merged and shouldn't have review status

**Pull request merged**
