### PR TITLE
Issue #6924: Unmask exception message during product import

### PR DESCRIPTION
**Pull request by tim-bezhashvyly**
### Description
Probably a typo. Exception message was passed as a exception description argument instead of exception message. Artefact of optional parameters.

### Fixed Issues (if relevant)
1. magento/magento2#6924: Magento 2.1.0 - "General system exception happened" on Import .csv

### Manual testing scenarios
1. Import product CSV with broken encoding

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=11363) <br/>All committers have signed the CLA.

**Comment by tim-bezhashvyly** [comment]
Tests will most likely fail as Travis has issues today initializing test suites (see other builds).

**Comment by tim-bezhashvyly** [comment]
Re-opening pull request in order to re-run Travis build.

**Comment by iDevid** [comment]
Very useful!

Still an error on 2.2.0... Too hard to fix?

**Comment by TomashKhamlai** [comment]
@tim-bezhashvyly, @iDevid could you confirm that file attached in [comment](https://github.com/magento/magento2/issues/6924#issuecomment-254426727) produces general exception error? How can be created the import file with 'broken encoding'?

**Comment by iDevid** [comment]
@TomashKhamlai it gives me general error, I removed the line and then it gives me an Encoding error, so I encoded the csv in UTF-8 then it works!

**Comment by TomashKhamlai** [comment]
Excuse me @iDevid if I will ask a stupid question but I still do not understand how to produce a general exception error. Should I remove the first line, the last line or any of the lines in the import file that I am going to import? Or could you just attach the file that has 'broken encoding' and will cause the general exception error?

**Pull request merged**
