### PR TITLE
26375 braintree payment address issue

### PR DESCRIPTION
**Pull request by chris-pook**
Removing PrototypeJS dependency from this file which is the cause of issue #26375.

### Description (*)
This may require further refactoring as it is not clear if/where the Prototype library is being used here. Either way Prototype shouldn't be required.

### Fixed Issues (if relevant)
1. magento/magento2#26375

### Manual testing scenarios (*)
As per issue #26375 

1. Enable and configure Braintree module
2. Register a customer account
3. Add at least one address to the customer account
4. Add a product to cart
5. Go to checkout
6. Proceed to payment step
7. Untick "My billing and shipping address are the same"
8. Select an address from dropdown
9. Click "update"

### Questions or comments
Need to ensure PrototypeJS is not being used in the file and if it is refactor to fully remove the dependency.

### Contribution checklist (*)
 - [ x ] Pull request has a meaningful description of its purpose
 - [ x ] All commits are accompanied by meaningful commit messages
 - [ x ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ x ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by chris-pook** [comment]
Says "Functional Tests EE" failed, however the report shows no failures. I've tried a re-run.

**Comment by chris-pook** [comment]
FYI these automated test checks seem pretty flaky. Had to re-run numerous times as they incorrectly reported failures.

**Comment by nuzil** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @nuzil. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @nuzil, here is your [new Magento instance](https://pr-26378.instances.magento-community.engineering).
Admin access: [https://pr-26378.instances.magento-community.engineering/admin](https://pr-26378.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by nuzil — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-6606](https://jira.corp.magento.com/browse/ENGCOM-6606) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:**
before

**After:**
after

**Pull request merged**
