### PR TITLE
magento/magento2#33010: Sort of related products in GraphQL not implemented

### LINKED ISSUE #33010: Sort of related products in GraphQL not implemented
### Preconditions (*)

1. Magento 2.4.2

### Steps to reproduce (*)

1. Create a product and add some related products
2. Get product from de GraphQL endpoint

### Expected result (*)

1. Product data with related products sort by position

### Actual result (*)

1. Product data with related products without sort

### PR DESCRIPTION
**Pull request by serbynskyi**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#33010

### Manual testing scenarios (*)

1. Create a product and add some related products
2. Get product from de GraphQL endpoint
3. Product data with related products sort by position

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by serbynskyi** [comment]
@magento run all tests

**Comment by serbynskyi** [comment]
@magento run all tests

**Comment by serbynskyi** [comment]
@magento run all tests

**Comment by serbynskyi** [comment]
@magento run all tests

**Comment by serbynskyi** [comment]
@magento run all tests

**Comment by serbynskyi** [comment]
@magento run all tests

**Comment by serbynskyi** [comment]
@magento run all tests

**Comment by serbynskyi** [comment]
@magento run all tests

**Comment by serbynskyi** [comment]
@magento run Functional Tests B2B, Functional Tests СE

**Comment by serbynskyi** [comment]
@magento run Functional Tests B2B, Functional Tests СE

**Comment by serbynskyi** [comment]
@magento run Functional Tests B2B, Functional Tests СE

**Comment by serbynskyi** [comment]
@magento run Functional Tests СE

**Comment by serbynskyi** [comment]
@magento run Functional Tests СE

**Comment by serbynskyi** [comment]
@magento run Functional Tests СE

**Comment by serbynskyi** [comment]
@magento run Functional Tests СE

**Comment by serbynskyi** [comment]
@magento run Functional Tests СE

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @serbynskyi,

Please cover the changes in some automated tests like web API tests etc.

Thanks

**Comment by engcom-Charlie** [comment]
Hi @serbynskyi,

Thank you for your contribution!

@engcom-Hotel, I have checked the existing code and found that testQueryRelatedProducts() from RelatedProduct/GetRelatedProductsTest.php is the test coverage for the scenario in this PR too. 

As per my understanding, this test already taking care the assertions of sorting of related products of positions. Hence we no need to add one more new test. Can you please check once and proceed accordingly. 

Thank you!

**Comment by engcom-Hotel** [comment]
Hello @engcom-Charlie,

Thanks for looking into this!

As per our discussion, we need to add an automated test to check the sorting of the related products. So please do the needful.

Thanks

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @engcom-Hotel,

I have implemented the automation test coverage for the PR changes. Requesting for the review.

Thank you!

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B

**Pull request merged**
