### PR TITLE
Fix issue when db_prefix is used

### LINKED ISSUE #1374: SQL error is displayed in Media Gallery if Magento is installed with "table prefix"
### Steps to reproduce (*)
1. Install Magento with **table prefix**
table_prefix_install
2. Open admin page, go to **Content - Media Gallery** 

### Expected result (*)
Media Gallery is opened

### Actual result (*)
SQL error is displayed
sql_state_error_prefix

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

fixes https://github.com/magento/adobe-stock-integration/issues/1374

### Manual testing scenarios (*)
1. Install Magento with **table prefix**
table_prefix_install
2. Open admin page, go to **Content - Media Gallery** 

### Expected result (*)
Media Gallery is opened
View image details popup is opened

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
Covered by integration test `\Magento\MediaGallery\Model\ResourceModel\AssetKeywordsTest`

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-7567](https://jira.corp.magento.com/browse/ENGCOM-7567) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

Testing Scenario
Precondition:
1. Adobe Stock Integration branch cloned and required by the composer. (You can find the installation guide  [here](https://github.com/magento/adobe-stock-integration/wiki/Installation))
2. Install Magento with Table prefix
table_pre_mage installation

Steps:
1. Open Magento Admin page
2. Go to Content - Media Gallery
3. Click Upload Image and select any valid image file from your local machine. Click Open
4. Select the previously uploaded image from Media Gallery grid
5. Click on "three dots" near the image name
6. Select View Details 

Expected Result: 
Verify that "Image Details" page is opened, and no error message appeared

**Comment by chalov-anton** [comment]
Created a high-level test scenario on cucumber https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/4756410

**Pull request merged**
