### PR TITLE
FIx for Zip archive contains full directory path of file

### LINKED ISSUE #26262: Zip archive contains full directory path of file
### Preconditions (*)
Magento  2.3.3

### Steps to reproduce (*)
When use class `\Magento\Framework\Archive\Zip` for creating zip archive, archive will contain full directory path to file. Example,

    $objectManager = \Magento\Framework\ObjectManager\ObjectManager::getInstance();
    $zip = $objectManager->create(\Magento\Framework\Archive\Zip::class);
    $file = '{{ABSOLUTE PATH TO FILE}}';
    $archive = '{{ABSOLUTE PATH TO ARCHIVE FOR CREATION}}';
    $zip->pack($file, $archive);

https://i.imgur.com/7jNorP1.png

### Expected result (*)
Root of archive will contain files 

### Actual result (*)

Root of archive contain directory structure where file was on server.

To fix this issue need refactor function

    public function pack($source, $destination)
    {
        $zip = new \ZipArchive();
        $zip->open($destination, \ZipArchive::CREATE);
        $zip->addFile($source);
        $zip->close();
        return $destination;
    }
to
   

    public function pack($source, $destination)
    {
        $zip = new \ZipArchive();
        $zip->open($destination, \ZipArchive::CREATE);
        $zip->addFile($source, basename($source));
        $zip->close();
        return $destination;
    }

in file https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Archive/Zip.php

### PR DESCRIPTION
**Pull request by nemke82**
### Description (*)
https://github.com/magento/magento2/issues/26262

### Fixed Issues (if relevant)
Fixes https://github.com/magento/magento2/issues/26262

### Manual testing scenarios (*)
not needed

### Questions or comments
not needed

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lbajsarowicz — CHANGES_REQUESTED** [review]
1. Fix the static tests (missing space)
2. Add automated tests to cover change.

**Comment by fooman** [comment]
One thing to confirm would be if this change impacts backups created by Magento, as changing the paths could mean existing backup recovery mechanisms no longer work because the zip file directory structure is now different.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@fooman How about adding extra argument / flag to the class / command responsible for generating backups?
```
--absolute-path    Backup should not contain the full path to the directory
```

**Comment by fooman** [comment]
@lbajsarowicz yeap anything having the updated behaviour opt-in sounds great. Just being mindful of people having done a backup recovery trial run and then when they actually need it in a highly stressful situation being confronted with a subtle but important change (that likely will get missed in any M2 upgrades).

Having an added argument would solve for this.

**Comment by lbajsarowicz** [comment]
@nemke82 Are you able to deliver the adjustment for the above-mentioned flag?

**Comment by nemke82** [comment]
@lbajsarowicz - Yes, let me submit a new commit then, then you guys review. I will push this as soon as possible. Thanks!

**Comment by lbajsarowicz** [comment]
@nemke82 Closing due to inactivity. Please let me know if you decide to continue the improvement.

**Pull request closed without merging**
