### PR TITLE
ISSUE-9799: Show related products ordered by position

### PR DESCRIPTION
**Pull request by sheepfy**
Fix issue https://github.com/magento/magento2/issues/9799

### CODE REVIEW

**Comment by Stepa4man** [comment]
@magento run all tests

**Review by Stepa4man — APPROVED** [review]
Hi @sheepfy 
Thanks for your contribution

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, thank you for the review.
[ENGCOM-8830](https://jira.corp.magento.com/browse/ENGCOM-8830) has been created to process this Pull Request
:eight_spoked_asterisk: @Stepa4man, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by andrewbess** [comment]
This PR is merged.
Please reopen if it needed

**Comment by sheepfy** [comment]
@andrewbess 
Doesn't seem to be merged as the changes are missing from 2.4-develop latest

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/ProductLink/CollectionProvider/LinkedMapProvider.php

**Comment by Stepa4man** [comment]
@sheepfy Have no clue what's going on there;)
@andrewbess, bro, can you shed some light with us, please:)

**Comment by andrewbess** [comment]
Hello @sheepfy @Stepa4man 

Thank you guys for your attentiveness.
Github showed me that this PR was already merged.
Also, I cannot reopen it due to Github shows me the next message "**_The repository that submitted this pull request has been deleted._**"
Perhaps this is the problem.

Also, I think the main reason why this PR will not be take further is: "[issue is closed](https://github.com/magento/magento2/issues/9799)". Maybe we need to reproduce the problem and reopen it.

@sheepfy Could you please resolve the problems and open new PR?

Thank you in advance.

**Comment by sheepfy** [comment]
@andrewbess 
added new PR 
https://github.com/magento/magento2/pull/38380

**Pull request closed without merging**
