### PR TITLE
fix: correct plural string

### LINKED ISSUE #31215: [Issue] Correct plural string
This issue is automatically created based on existing pull request: magento/magento2#31207: Correct plural string

---------
### Description (*)
Just found it today, a mistyping somewhere :-)

Display correct plural strings under condition

### PR DESCRIPTION
**Pull request by Amadeco**
### Description (*)
Just found it today, a mistyping somewhere :-)

Display correct plural strings under condition

### Resolved issues:
1. [x] resolves magento/magento2#31215: Correct plural string

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @mageho,
Could you sign Adobe CLA? Unfortunately, without it, we can't accept any PR.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by mageho** [comment]
> Hi @mageho,
> Could you sign Adobe CLA? Unfortunately, without it, we can't accept any PR.

Done @ihor-sviziev

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Static Tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8700](https://jira.corp.magento.com/browse/ENGCOM-8700) has been created to process this Pull Request

**Review by idsergiu — APPROVED** [review]

**Comment by engcom-Dash** [comment]
@magento run all tests

**Pull request closed without merging**
