### PR TITLE
Minicart search logo not vertically aligned

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Description (*)

Minicart, search & logo not vertically aligned between 640 to767 device pixel.
### Fixed Issues (if relevant)

1. #20905: Minicart, search & logo not vertically aligned between 640 to767 device pixel.

### Manual testing scenarios (*)

1. Go to frontend -> resize screen (min width 640 and max width 767)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by Karlasa — APPROVED** [review]
It's re created PR for fixing CLA issue in #20955
Will approve it, as code is same and original PR passed testing.

**Comment by magento-engcom-team** [comment]
Hi @Karlasa, thank you for the review.
[ENGCOM-4457](https://jira.corp.magento.com/browse/ENGCOM-4457) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
