### PR TITLE
Fix #24656: allow "group" attribute on referenceBlock layout XML element

### LINKED ISSUE #24656: referenceBlock with group attribute not allowed in catalog_product_view.xml
I would like to change group attribute for certain referenceBlocks in _Magento_Catalog/layout/catalog_product_view.xml_. It is causing exceptions during XML validation.

### Preconditions (*)
1. Magento 2.3.2 & 2.3-develop

### Steps to reproduce (*)
1. Go to _Magento_Catalog/layout/catalog_product_view.xml_
2. Change group for below mentioned reference blocks:
```
<referenceBlock name="product.info.description" group="column_left">
    <arguments>
        <argument name="title" translate="true" xsi:type="string">Description</argument>
        <argument name="contain_content" xsi:type="boolean">false</argument>
        <argument name="sort_order" xsi:type="string">10</argument>
    </arguments>
</referenceBlock>

<referenceBlock name="product.attributes" group="column_right">
    <arguments>
        <argument name="contain_content" xsi:type="boolean">false</argument>
        <argument name="sort_order" xsi:type="string">20</argument>
    </arguments>
</referenceBlock>

<referenceBlock name="catalog.product.related" group="detailed_info">
    <arguments>
        <argument translate="true" name="title" xsi:type="string">Related products</argument>
        <argument name="sort_order" xsi:type="string">80</argument>
        <argument name="contain_content" xsi:type="boolean">false</argument>
        <argument name="include_headline" xsi:type="boolean">false</argument>
        <argument name="is_collapsible" xsi:type="boolean">false</argument>
        <argument name="view_mode" xsi:type="string">grid</argument>
    </arguments>
</referenceBlock>

<referenceBlock name="product.info.upsell" group="detailed_info">
    <arguments>
        <argument translate="true" name="title" xsi:type="string">You may be also interested in following products</argument>
        <argument name="sort_order" xsi:type="string">100</argument>
        <argument name="contain_content" xsi:type="boolean">false</argument>
        <argument name="include_headline" xsi:type="boolean">false</argument>
        <argument name="is_collapsible" xsi:type="boolean">false</argument>
        <argument name="in_nav" xsi:type="boolean">false</argument>
        <argument name="view_mode" xsi:type="string">grid</argument>
    </arguments>
</referenceBlock>
```

3. Go to Product Desciption Page in Developer Mode

### Expected result (*)

1. No errors thrown

### Actual result (*)

1. Exceptions:
```
1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceBlock', attribute 'group': The attribute 'group' is not allowed.
Line: 2883

Element 'referenceBlock', attribute 'group': The attribute 'group' is not allowed.
Line: 2890

Element 'referenceBlock', attribute 'group': The attribute 'group' is not allowed.
Line: 2915

Element 'referenceBlock', attribute 'group': The attribute 'group' is not allowed.
Line: 2924


Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceBlock', attribute 'group': The attribute 'group' is not allowed.
Line: 2883

Element 'referenceBlock', attribute 'group': The attribute 'group' is not allowed.
Line: 2890

Element 'referenceBlock', attribute 'group': The attribute 'group' is not allowed.
Line: 2915

Element 'referenceBlock', attribute 'group': The attribute 'group' is not allowed.
Line: 2924

#0 /var/www/vendor/magento/framework/Config/Dom.php(117): Magento\Framework\Config\Dom->_initDom('<layout xmlns:x...')
```

I tried adding _group_ attribute to `<move>` tag but it also caused errors.
How can _group_ attribute be changed for a referenceBlock?

### PR DESCRIPTION
**Pull request by korostii**
### Description (*)
Allow "group" attribute on referenceBlock layout XML element

### Fixed Issues (if relevant)
1. magento/magento2#24656: referenceBlock with group attribute not allowed in catalog_product_view.xml

### Manual testing scenarios (*)
Please see #24656 for detailed steps.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @korostii. Thank you for your contribution. According to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered by automated tests. 

You may create a simple integration test for this case. Please, use the following test as a reference

https://github.com/magento/magento2/blob/b0e60f77e9a4f0ec0a03c0b561fb419767382f27/dev/tests/integration/testsuite/Magento/Test/Integrity/Modular/IndexerConfigFilesTest.php#L37

(you don't need to create an XML class, you may provide the corresponding XML body directly in the test)

Thank you!

**Review by rogyar — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7278](https://jira.corp.magento.com/browse/ENGCOM-7278) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

Checked according to test scenario from issue #24656 

**Before:**
Screenshot from 2020-04-09 16-31-43

**After:**
Screenshot from 2020-04-09 16-43-19

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by korostii** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Integration Tests

**Comment by tim-breitenstein-it** [comment]
Issue still exists on Magento 2.4.2

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B, Integration Tests

**Comment by mrtuvn** [comment]
@tim-breitenstein-it magento have priority on each PR. Still have other pull requests have higher priority.

**Comment by korostii** [comment]
@magento-engcom-team @VladimirZaets @sidolov @slavvka I understand about the priorities and all, but it's been a full year since it's been marked "Progress: accept" and moved to "To Approve", the B2B tests keep failing for seemingly unrelated reasons and there are no unresolved comments\feedback from reviewers here.
Could someone please look at it and move it along somehow? It's a bit disheartening to see a small one-liner fix like this one being stuck in review hell for so long. 

Unironically, this is basically the main reason why I restrain myself from getting into more complex PRs with Magento: you never now if your PR will be quickly merged, or if it will be just lost and ignored for months with no end in sight.

Thanks for all your hard work @magento-engcom-team, I hope at least the priority PRs get some love these days.

**Comment by mrtuvn** [comment]
re-add label accepted when it's remove previously

QA tested passed here
https://github.com/magento/magento2/pull/27575#issuecomment-611540342

**Review by mrtuvn — APPROVED** [review]

**Comment by korostii** [comment]
@magento-engcom-team FYI neither of the tests (1 functional, 1 integration) seems to be related to the pull request iteslf:
image
image

**Comment by mrtuvn** [comment]
i think that not related with your change

**Pull request merged**
