### PR TITLE
downloadable product view layout fix (issue #20187)

### PR DESCRIPTION
**Pull request by melaxon**
Downloadable product view layout fix (issue #20187)

### Description (*)
1) This fixes only catalog product view layout of of downloadables.
The layout now is similar to simple or other types
2) Now the links are shown on frontend only if they sell separately or have samples. (Previously meaningless names of links also appeared)
3) Duplicate links title "Links" was removed as well.
The layout on wishlist and maybe somewhere else still pending

### Fixed Issues (if relevant)
ISSUE 20187

1. magento/magento2#20187: Issue title: Downloadable product view layout
2. ...

### Manual testing scenarios (*)

1. Install Magento 2.3.0
2 Setup one downloadable product and one simple product, both with custom options
3. in frontend open both products in different browser tabs to compare the layout

### Contribution checklist (*)
 - [x ] Pull request has a meaningful description of its purpose
 - [x ] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @melaxon. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by milindsingh** [comment]
Aready created https://github.com/magento/magento2/pull/20239

**Comment by melaxon** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @melaxon. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @melaxon, here is your [new Magento instance](https://pr-20254.instances.magento-community.engineering).
Admin access: [https://pr-20254.instances.magento-community.engineering/admin](https://pr-20254.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by melaxon** [comment]
Screenshots from Vanila test:
1) Simple product to compare with
2) Downloadable product
3) Downloadable with links purchased separately

**Comment by sidolov** [comment]
Hi @melaxon unfortunately, we can't accept pull requests with zero changeset. Please, update your pull request and reopen it if you wish to continue.

**Pull request closed without merging**
