### PR TITLE
Fixing the partial reindexation when cronjob indexer_update_all_views runs (Issue #35248)

### LINKED ISSUE #35248: Products Randomly Disappear from Category View on Storefront When Partial Indexation is Running
While the Catalog Search indexer is running, when it's set to run by a schedule by using the Mview architecture, there's a time when the products randomly disappear from the category pages. After a deeper investigation, I found out that the issue is on the ElasticSearch indexation by batch implementation.

Check the line:
https://github.com/magento/magento2/blob/a96f0f76c05778fd9400c04a0bdb9d31166c0d0d/app/code/Magento/CatalogSearch/Model/Indexer/Fulltext.php#L220

```php
        if ($saveHandler->isAvailable($dimensions)) {
            $saveHandler->deleteIndex($dimensions, new \ArrayIterator($productIds));
            $saveHandler->saveIndex($dimensions, $this->fullAction->rebuildStoreIndex($storeId, $productIds));
        }
```

It happens when the documents are deleted from ElasticSearch first to only after being processed and re-created. While this is happening the products are no longer available on ElasticSearch and, therefore, may cause some categories to show fewer or no products at all.

Since this indexation runs every time something is changed on the product data, this becomes totally random.

### Preconditions (*)

1. The Catalog Search (catalogsearch_fulltext) is set to Update by Schedule
2. Magento MUST be using ElasticSearch as a search engine

### Steps to reproduce (*)

This is really tricky to test because it only happens after Magento deletes the documents from ElasticSearch and before the documents are created again. It's totally random because this process may be triggered by a variety of other indexations or changes made to products. To test this you'll need some developer tools like: Postman, Xdebug

Before start:

1. Full Page Cache is disabled (for reproducing the issue)
2. Block cache is disabled (for reproducing the issue)

Now let's start:

1. Disable the cron so you can run it by yourself manually 
2. Make some changes to a few products
5. The catalogsearch_fulltext_cl table now should have some product IDs to be processed
6. On Postman, create a new request with the following configurations:

Request Type: `POST`
Request URL: `http://localhost:9200/magento2_product_1/document/_search` (where magento2_product_1 is the index name or alias)
Request Body:
```json
{
    "from": 0,
    "size": 100,
    "stored_fields": [
        "_id",
        "_score"
    ],
    "query": {
        "bool": {
            "must": [
                {
                    "terms": {
                        "category_ids": [
                            "4"
                        ]
                    }
                },
                {
                    "terms": {
                        "visibility": [
                            "2",
                            "4"
                        ]
                    }
                }
            ]
        }
    }
}
```
For the category ID, make sure to use a category ID related to the products that were changed so you can see that the products will disappear.

Tests:
```javascript
var jsonData = JSON.parse(responseBody);
let hits = jsonData.hits.total.value;
pm.test("Hits number is equals to 14 (" + hits + " hits).", () => {
    pm.expect(hits).to.be.equals(14);
});
```
Change the number 14 to the number of products for the selected category on the test. So, if your category has 25 products, the 14 must be switched by 25.

7. On Postman, use the runner to make this search each 500ms for 10000 requests. This way you can see the tests failing at the right moment.
8. Enable your Xdebug to run on every request:

```ini
xdebug.mode = debut
xdebug.start_with_request = yes
```
9. Start the Xdbug
10. Set a breakpoint on the following file and line: https://github.com/magento/magento2/blob/a96f0f76c05778fd9400c04a0bdb9d31166c0d0d/app/code/Magento/CatalogSearch/Model/Indexer/Fulltext.php#L221
11. When Xdebug stops on this line check the Postman runner failing the tests because the number of products is less than the number expected.
12. Go to the storefront and check the category page (without cache)
13. You can see there are fewer products or no products at all

I created a screencast showing the issue happening.
https://www.loom.com/share/a4790612971945508c50bb21e0f2523c

### Expected result (*)

1. The products are not deleted from ElasticSearch on the partial indexation (Mview)

### Actual result (*)

1. The documents (products) are removed from ElasticSearch before being re-created

### PR DESCRIPTION
**Pull request by tiagosampaio**
### Description (*)

While the Catalog Search indexer is running, when it's set to run by a schedule by using the Mview architecture, there's a time when the products randomly disappear from the category pages. After a deeper investigation, I found out that the issue is on the ElasticSearch indexation by batch implementation.

This Pull Request created a new way of indexing the products partially (when the index is not deleted from ElasticSearch, only the documents).

### Fixed Issues (if relevant)

1. Fixes [magento/magento2#35248](https://github.com/magento/magento2/issues/35248)

### Preconditions (*)

1. The Catalog Search (catalogsearch_fulltext) is set to Update by Schedule
2. Magento MUST be using ElasticSearch as a search engine

### Manual testing scenarios (*)
Provided on the issue

1. Disable the cron so you can run it by yourself manually 
2. Make some changes to a few products
5. The catalogsearch_fulltext_cl table now should have some product IDs to be processed
6. On Postman, create a new request with the following configurations:

Request Type: `POST`
Request URL: `http://localhost:9200/magento2_product_1/document/_search` (where magento2_product_1 is the index name or alias)
Request Body:
```json
{
    "from": 0,
    "size": 100,
    "stored_fields": [
        "_id",
        "_score"
    ],
    "query": {
        "bool": {
            "must": [
                {
                    "terms": {
                        "category_ids": [
                            "4"
                        ]
                    }
                },
                {
                    "terms": {
                        "visibility": [
                            "2",
                            "4"
                        ]
                    }
                }
            ]
        }
    }
}
```
For the category ID, make sure to use a category ID related to the products that were changed so you can see that the products will disappear.

Tests:
```javascript
var jsonData = JSON.parse(responseBody);
let hits = jsonData.hits.total.value;
pm.test("Hits number is equals to 14 (" + hits + " hits).", () => {
    pm.expect(hits).to.be.equals(14);
});
```
Change the number 14 to the number of products for the selected category on the test. So, if your category has 25 products, the 14 must be switched by 25.

7. On Postman, use the runner to make this search each 500ms for 10000 requests. This way you can see the tests failing at the right moment.
8. Enable your Xdebug to run on every request:

```ini
xdebug.mode = debut
xdebug.start_with_request = yes
```
9. Start the Xdebug
10. Set a breakpoint on the following file and line: https://github.com/magento/magento2/blob/a96f0f76c05778fd9400c04a0bdb9d31166c0d0d/app/code/Magento/CatalogSearch/Model/Indexer/Fulltext.php#L221
11. When Xdebug stops on this line check the Postman runner is no more failing because the products were not deleted from the ElasticSearch
12. Go to the storefront and check the category page (without cache)
13. The category page has the correct number of products

I created a screencast showing the issue happening.
https://www.loom.com/share/a4790612971945508c50bb21e0f2523c

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by tiagosampaio** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @tiagosampaio,
Could you please review and fix the failing tests?

**Comment by tiagosampaio** [comment]
@ihor-sviziev sure thing. I'll fix them.

**Comment by tiagosampaio** [comment]
Still working on it.

**Comment by duckchip** [comment]
hi @tiagosampaio any luck with fixing the tests? :)

**Comment by tiagosampaio** [comment]
@duckchip I believe we can close this out. It looks like it's an issue already addressed by the internal team on the latest release.

**Comment by ihor-sviziev** [comment]
Closing the Pull Request as the issue already addressed by the internal team.
https://github.com/magento/magento2/pull/35249#issuecomment-1170463573 https://github.com/magento/magento2/issues/35248#issuecomment-1134416880

**Pull request closed without merging**
