### PR TITLE
Simplify if else catalog search full text data provider

### PR DESCRIPTION
**Pull request by sankalpshekhar**
### Description (*)

This PR removes ELSE statement, and simplify the branching when setting the data.

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-5144](https://jira.corp.magento.com/browse/ENGCOM-5144) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@sankalpshekhar thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5144](https://jira.corp.magento.com/browse/ENGCOM-5144) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Review by orlangur — CHANGES_REQUESTED** [review]
Please squash changes into a single commit so that we have perfectly clean history 😉

**Comment by sankalpshekhar** [comment]
@orlangur I have tried adding the changes to a single commit (merging) them.

**Comment by orlangur** [comment]
@sankalpshekhar there are still 9 commits. Please try https://github.com/wprig/wprig/wiki/How-to-squash-commits.

**Review by orlangur — CHANGES_REQUESTED** [review]
Please squash changes into a single commit so that we have perfectly clean history 😉

**Comment by Nazar65** [comment]
Hi @sankalpshekhar you can do this as well 
1. git remote add upstream https://github.com/magento/magento2.git
2. git fetch upstream
3. git reset --soft upstream/2.3-develop
4. git add .
5. git commit -m"simplify-if-else-catalog-search-full-text-data-provider"
6.  git push --force

**Comment by sankalpshekhar** [comment]
@Nazar65 thank-you for your help here!

**Comment by orlangur** [comment]
@Nazar65 there is only one commit now authored by you which I believe is not correct :)

**Comment by Nazar65** [comment]
@orlangur yes :) @sankalpshekhar can you change author commit https://www.git-tower.com/learn/git/faq/change-author-name-email

**Comment by sankalpshekhar** [comment]
@orlangur Please check if this is good now, in the commits tab on the PR i see myself listed as the author.

**Comment by Nazar65** [comment]
@orlangur @sankalpshekhar  now all done :heavy_check_mark:

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-5144](https://jira.corp.magento.com/browse/ENGCOM-5144) has been created to process this Pull Request

**Pull request merged**
