### PR TITLE
Fixed data saving problem

### PR DESCRIPTION
**Pull request by Priya-V-Panchal**
### Description (*)

Fixed data saving problem
### Fixed Issues (if relevant)

1. magento/magento2#23354: Data saving problem error showing when leave blank qty and update it

### Manual testing scenarios (*)

N/A
### Questions or comments

N/A
### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23491) <br/>All committers have signed the CLA.

**Review by kalpmehta — COMMENTED** [review]
@Priya-V-Panchal Shouldn't this simply work instead of your change:
$allQty += (int) $data['qty'];
Can you please try?

**Review by kalpmehta — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, thank you for the review.
[ENGCOM-5382](https://jira.corp.magento.com/browse/ENGCOM-5382) has been created to process this Pull Request
:eight_spoked_asterisk: @kalpmehta, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@Priya-V-Panchal thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by kalpmehta — CHANGES_REQUESTED** [review]
@Priya-V-Panchal Apologies, I realized Qty can be decimal as well. Can you please change `(int)` to `(float)`? Thanks for your contribution!

**Comment by sidolov** [comment]
@Priya-V-Panchal , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
