### PR TITLE
Update FixerIo API Endpoints

### LINKED ISSUE #36010: Fixer IO API Endpoint changed
### Preconditions and environment

- Magento version: 2.4.5
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

> Simply if you now go to configure currency exchange using Fixer IO they will direct you to a new platform with a new API Endpoint https://apilayer.com/marketplace/fixer-api
> Admin - Stores - Currency Rates - Select - Fixex.io as Import service and click on Import

### Expected result

It imports currency rates successfully

### Actual result

The import is failing due to the new API keys only compatible with the new API Endpoint which must be updated/corrected from within M2

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by IbrahimS2**
This PR is to update the Fixer IO Currency Exchange API Endpoints to the new one
https://apilayer.com/marketplace/fixer-api

### Description (*)
I only updated the Fixer IO API Endpoint to the new platform, please refer to the URL below:

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36010

### Manual testing scenarios (*)

1. Add two or more currencies
2. Configure Fixer IO
3. Import rates from Fixer IO

### Questions or comments
I think we need to make a backward compatibility if there are some companies/individuals still using the new API Endpoints, not sure if it worth the time

### Contribution checklist (*)
 - [*] Pull request has a meaningful description of its purpose
 - [*] All commits are accompanied by meaningful commit messages
 - [*] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by IbrahimS2** [comment]
@adobe/open-source-office I already signed, please confirm.

**Comment by hostep** [comment]
Thanks @IbrahimS2

But it looks like somebody is trying to fix the same issue: https://github.com/magento/magento2/pull/35984 and it updates a test as well, so it's probably the better PR

**Comment by daniloargentiero** [comment]
Magento's test asks me to fix the currencyconverterapi api too. I'm working on it and I will push a new commit with it.

**Comment by sdzhepa** [comment]
Close as a duplicate of https://github.com/magento/magento2/pull/35984 and was created earlier

**Pull request closed without merging**
