### PR TITLE
[Backport] Advanced Search layout not proper

### PR DESCRIPTION
**Pull request by amol2jcommerce**
Advanced Search layout not proper
### Description (*)

#20809: Advanced Search layout not proper
### Fixed Issues (if relevant)

1. #21611: Advanced Search layout not proper

### Manual testing scenarios (*)

1. Click Advanced Search link in footer
2. Magento 2.2.x

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-21892.instances.magento-community.engineering).
Admin access: [https://pr-21892.instances.magento-community.engineering/admin](https://pr-21892.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4559](https://jira.corp.magento.com/browse/ENGCOM-4559) has been created to process this Pull Request

**Review by Karlasa — CHANGES_REQUESTED** [review]
styles should be kept under specific module. 
Please move changes under Magento_CatalogSearch as advanced search is part of that module

**Comment by amol2jcommerce** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce, here is your [new Magento instance](https://pr-21892.instances.magento-community.engineering).
Admin access: [https://pr-21892.instances.magento-community.engineering/admin](https://pr-21892.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by amol2jcommerce** [comment]
Hi @Karlasa, as per your suggestion update branch. please review.

**Review by Karlasa — APPROVED** [review]
@amol2jcommerce thanks for moving it under correct module folder

**Comment by magento-engcom-team** [comment]
Hi @Karlasa, thank you for the review.
[ENGCOM-4559](https://jira.corp.magento.com/browse/ENGCOM-4559) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
QA passed

**Pull request merged**
