### PR TITLE
Update Queue.php

### PR DESCRIPTION
**Pull request by ghost**
These 2 items were backwards.  After spending hours troubleshooting why my newsletter was being rejected by my mail host i tracked it back to this.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=7771) <br/>All committers have signed the CLA.

**Comment by ihor-sviziev** [comment]
@cbarsness Would be great to cover this case with unit test in order to prevent such situations in future

**Review by antonkril — APPROVED** [review]

**Comment by okorshenko** [comment]
Closing this pull request. Source branch was removed

**Comment by orlangur** [comment]
@okorshenko why?

It looks like bug is still present in `develop`: https://github.com/magento/magento2/blob/develop/app/code/Magento/Newsletter/Model/Queue.php#L239

Changes can be obtained with `git fetch mainline pull/7771/head:pr7771`, there is no matter whether source branch exists or not.

Of course, probability that PR author will make any changes if it is required is low when source branch is removed, my two cents is that it's better to pick and process good PR in its current state than just close.

**Comment by hostep** [comment]
Looks like this was recently fixed by https://github.com/magento/magento2/pull/6354

**Pull request closed without merging**
