### PR TITLE
Fix for issue when Product Import imports attributes for wrong SKU

### PR DESCRIPTION
**Pull request by comdiler**
In case of importing numeric SKUs, Magento can update wrong product. 
See examples on a screenshots.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=7089) <br/>All committers have signed the CLA.

**Comment by gorillagroup** [comment]
Fixes #7062 
@veloraven please reopen a ticket closed my mistake

**Comment by hostep** [comment]
I believe this PR may be closed, since it was already resolved like @maghamed says [over here](https://github.com/magento/magento2/pull/7961#issuecomment-280338391).

**Comment by vrann** [comment]
@comdiler thank you for the contribution, it is already fixed in the mainline.

**Pull request closed without merging**
