### PR TITLE
#34991 GraphQL Bundle Options generates wrong DB request and result: …

### LINKED ISSUE #34991: GraphQL Bundle Options  generates wrong DB request and result
The class `\Magento\BundleGraphQl\Model\Resolver\Options\Collection`  generates an erroneous query to the database.

Error in 2 parts of the code:

```
    public function addParentFilterData(int $parentId, int $parentEntityId, string $sku) : void
    {
        $this->skuMap[$parentId] = ['sku' => $sku, 'entity_id' => $parentEntityId];
    } 

```
and
```
        $optionsCollection->getSelect()->join(
            ['cpe' => $productTable],
            'cpe.'.$linkField.' = main_table.parent_id',
            []
        )->where(
            "cpe.entity_id IN (?)",
            $this->skuMap
        );
```
As a result, a query is generated:
bundle_gql

### Preconditions (*)

The error was repeated CE 2.3.6. In theory, the error is relevant for the latest version of magento. Mysql: 5.7.26

### Steps to reproduce (*)

1. create 2 products bundle
2. first product bundle has a sku that contains the id of the second product bundle. Example: first bundle: entity_id = 14, sku = 16D01-E, second bundle: entity_id = 16
 3. run graphql 

```query bundle($productSku:String){

  products(
    filter: { sku: { eq: $productSku } }
  ) {
    items {
      id
      type_id
      name
      sku
   ... on BundleProduct {
        items{
          option_id
        }
      }
    }  
 
  }
}
```

Variable: {"productSku":"16D01-E"}

### Expected result (*)

Graphql returns option list

### Actual result (*)

Retrieving bundle options via a module _BundleGraphQl_  returns an error:

`"debugMessage": "Notice: Undefined offset: 16 in vendor/magento/module-bundle-graph-ql/Model/Resolver/Options/Collection.php on line 130",`

S0

### PR DESCRIPTION
**Pull request by novakivskiy**
Fixes #34991

### CODE REVIEW

**Comment by nuzil** [comment]
@magento run all tests

**Comment by nuzil** [comment]
@novakivskiy 
Would be awesome if you can add GraphQL Api tests. is it something you can do?

**Review by nuzil — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-9393](https://jira.corp.magento.com/browse/ENGCOM-9393) has been created to process this Pull Request
:eight_spoked_asterisk: @nuzil, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests CE

**Comment by engcom-Delta** [comment]
Try to reproduce the issue without PR  code changes and able to replicate , below are the steps to reproduce.
Pre-Condtion:
1. Have fresh instance without sample data.
2. Have 10 Products (So that if you create new product , entity id will be in double digits )

Steps:
1. Go to Catalog --> Products
2. Note latest product entity ID Ex: 10 
3. Create new bundle product by name  12DE01-E & use same name for sku id ( Here the product name started with 12 and this value is calculated by incrementing 2 by value of step#2)
4  Make sure that bundle product has product options, Category selected, Product Images (which is created in step3)
5. Create second bundle product any name & sku id
6. Do Cache flush 
7. Do reindexing
8. Run Below graphql query by inputing product name 12DE01 which was created at step 3
9. Validate the response 

Expected issue:
Receiving response "Internal server error" 

Request:
`{products(
    filter: { sku: { eq: "14B01-B" } }
  ) {
    items {
      id
      type_id
      name
      sku
   ... on BundleProduct {
        items{
          option_id
        }
      }
    }  
 
  }
}`
Response:
`{
    "errors": [
        {
            "message": "Internal server error",
            "extensions": {
                "category": "internal"
            },
            "locations": [
                {
                    "line": 10,
                    "column": 9
                }
            ],
            "path": [
                "products",
                "items",
                0,
                "items"
            ]
        }
    ],
    "data": {
        "products": {
            "items": [
                {
                    "id": 13,
                    "type_id": "bundle",
                    "name": "14B01-B",
                    "sku": "14B01-B",
                    "items": null
                }
            ]
        }
    }
}`

**Comment by engcom-Delta** [comment]
After PR code Changes it works as expected and below is the working screenshot.
Screenshot 2022-01-28 at 4 32 46 PM

It is a Graphql ticket and it has no automation test case covered , I hope it is recommended to cover automation test for this scenario and Hence moving this ticket to 'Extended Testing' status.

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @novakivskiy Thanks much for your contribution over here!
But, since additionally we require an auto-test covered for this case, can you please help us covering that too?
Thanks in advance!

**Comment by engcom-Charlie** [comment]
Hi @novakivskiy,

Thank you for your contribution!

I am working on WebAPI test for this PR.

Thank you!

**Comment by engcom-Charlie** [comment]
Hi @engcom-Alfa,

I have merged 2.4-develop and added GraphQL Web API test for this scenario.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
[@magento](https://github.com/magento) run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
The Functional B2B test case which is getting failed in build is not part of this PR or not faling because of changes made in this PR.
- app/code/Magento/InventoryInStorePickupFrontend/Test/Mftf/Test/StorefrontGuestBillingAddressPreselectedTest.xml

Since we have covered auto test [here](https://github.com/magento/magento2/pull/34992#issuecomment-1041194745)  hence moving this PR to Merge in Progress.

Thank you!

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Pull request merged**
