### PR TITLE
Bump Sort Order

### PR DESCRIPTION
**Pull request by null93**
### Description (*)

Should be 45 instead of 40 since `export_button_version5` already has a sort order of 40. This makes it hard to add elements before and after each field.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by null93** [comment]
@magento run all tests

Signed CLA

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by null93** [comment]
@manavluhar Can we get this merged? It's a very simple change.

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by null93** [comment]
Crazy that such a small change can't be merged in... closing.

**Pull request closed without merging**
