### PR TITLE
Remove the copyright year from file headers

### PR DESCRIPTION
**Pull request by jameshalsall**
This removes the license years from all file headers and instead adds it to the COPYING.txt file, which is referenced from the file headers themselves.

This will prevent mass changes to files each year, as we will only need to update the year in COPYING.txt.

### CODE REVIEW

**Comment by orlangur** [comment]
It was planned to not ever change the header initially: https://github.com/magento/magento2/issues/1234#issuecomment-99093927 :(

Dunno who came up with an idea to bump copyright year once again and then do it on regular basis. Somehow many other products don't have legal issues which require years to be specified in each single file.

**Comment by okorshenko** [comment]
@jameshalsall thank you for your contribution. We are working right now on merging this PR. This will take some time due to a huge changeset. We are doing our best to process this PR as soon as possible. Please, do not rebase/change this branch. We will resolve existing conflicts on our side.
Thank you

**Comment by okorshenko** [comment]
@jameshalsall thank you for your contribution. Your pull request successfully merged to develop branch. 🎉 

@orlangur Dreams Come True!

**Comment by orlangur** [comment]
That's really impressive 👍 So, there will be separate micro-release with these changes or previous one could be reverted?

My best expectation was for it to be postponed till 2018 and then changed last time, I'm glad I was wrong :)

**Pull request merged**
