### PR TITLE
Fix Notice: Undefined property: Magento\Backend\Helper\Dashboard\Order::$_storeManager

### PR DESCRIPTION
**Pull request by bchatard**
Undefined property on Dashboard while Aggregated data is enabled

Step to reproduce: 
- install Magento 2 (2.0.0 - stable)
- install sample data (optional, but you need some orders - I think)
- active _Use Aggregated Data (beta)_ (_Stores_ > _Configuration_ > _Sales_ > _Sales_ > _Dashboard_)
- go to _Dashboard_

```
Notice: Undefined property: Magento\Backend\Helper\Dashboard\Order::$_storeManager in /var/www/magento/dev/vendor/magento/module-backend/Helper/Dashboard/Order.php on line 57
#0 /var/www/magento/dev/vendor/magento/module-backend/Helper/Dashboard/Order.php(57): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined prope...', '/var/www/magent...', 57, Array)
#1 /var/www/magento/dev/vendor/magento/module-backend/Helper/Dashboard/AbstractDashboard.php(33): Magento\Backend\Helper\Dashboard\Order->_initCollection()
#2 /var/www/magento/dev/vendor/magento/module-backend/Helper/Dashboard/AbstractDashboard.php(50): Magento\Backend\Helper\Dashboard\AbstractDashboard->getCollection()
#3 /var/www/magento/dev/vendor/magento/module-backend/Helper/Dashboard/AbstractDashboard.php(58): Magento\Backend\Helper\Dashboard\AbstractDashboard->getItems()
#4 /var/www/magento/dev/vendor/magento/module-backend/Block/Dashboard/AbstractDashboard.php(55): Magento\Backend\Helper\Dashboard\AbstractDashboard->getCount()
#5 /var/www/magento/dev/vendor/magento/module-backend/view/adminhtml/templates/dashboard/graph.phtml(26): Magento\Backend\Block\Dashboard\AbstractDashboard->getCount()
#6 /var/www/magento/dev/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/magent...')
#7 /var/www/magento/dev/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Backend\Block\Dashboard\Tab\Orders), '/var/www/magent...', Array)
#8 /var/www/magento/dev/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/var/www/magent...')
#9 /var/www/magento/dev/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#10 /var/www/magento/dev/vendor/magento/framework/View/Element/AbstractBlock.php(652): Magento\Backend\Block\Template->_toHtml()
#11 /var/www/magento/dev/vendor/magento/module-backend/Block/Dashboard/Diagrams.php(39): Magento\Framework\View\Element\AbstractBlock->toHtml()
#12 /var/www/magento/dev/vendor/magento/framework/View/Element/AbstractBlock.php(257): Magento\Backend\Block\Dashboard\Diagrams->_prepareLayout()
#13 /var/www/magento/dev/vendor/magento/framework/View/Layout.php(744): Magento\Framework\View\Element\AbstractBlock->setLayout(Object(Magento\Framework\View\Layout\Interceptor))
#14 /var/www/magento/dev/var/generation/Magento/Framework/View/Layout/Interceptor.php(349): Magento\Framework\View\Layout->createBlock('Magento\\Backend...', 'dashboard\\diagr...', Array)
#15 /var/www/magento/dev/vendor/magento/module-backend/Block/Dashboard.php(39): Magento\Framework\View\Layout\Interceptor->createBlock('Magento\\Backend...')
#16 /var/www/magento/dev/vendor/magento/framework/View/Element/AbstractBlock.php(257): Magento\Backend\Block\Dashboard->_prepareLayout()
#17 /var/www/magento/dev/vendor/magento/framework/View/Layout/Generator/Block.php(139): Magento\Framework\View\Element\AbstractBlock->setLayout(Object(Magento\Framework\View\Layout\Interceptor))
#18 /var/www/magento/dev/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#19 /var/www/magento/dev/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#20 /var/www/magento/dev/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#21 /var/www/magento/dev/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#22 /var/www/magento/dev/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#23 /var/www/magento/dev/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#24 /var/www/magento/dev/vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#25 /var/www/magento/dev/vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#26 /var/www/magento/dev/var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#27 /var/www/magento/dev/vendor/magento/module-backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#28 /var/www/magento/dev/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Backend...')
#29 /var/www/magento/dev/vendor/magento/module-backend/Controller/Adminhtml/Dashboard/Index.php(35): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Backend...')
#30 /var/www/magento/dev/var/generation/Magento/Backend/Controller/Adminhtml/Dashboard/Index/Interceptor.php(24): Magento\Backend\Controller\Adminhtml\Dashboard\Index->execute()
#31 /var/www/magento/dev/vendor/magento/framework/App/Action/Action.php(102): Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor->execute()
#32 /var/www/magento/dev/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#33 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#34 /var/www/magento/dev/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#35 /var/www/magento/dev/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor->___callParent('dispatch', Array)
#36 /var/www/magento/dev/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor), Array, 'adminAuthentica...')
#37 /var/www/magento/dev/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#38 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#39 /var/www/magento/dev/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#40 /var/www/magento/dev/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor), Array, 'designLoader')
#41 /var/www/magento/dev/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#42 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#43 /var/www/magento/dev/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#44 /var/www/magento/dev/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Backend...', 'dispatch', Object(Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor), Array, 'adminMassaction...')
#45 /var/www/magento/dev/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#46 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#47 /var/www/magento/dev/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#48 /var/www/magento/dev/var/generation/Magento/Backend/Controller/Adminhtml/Dashboard/Index/Interceptor.php(39): Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#49 /var/www/magento/dev/vendor/magento/framework/App/FrontController.php(55): Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#50 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#51 /var/www/magento/dev/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#52 /var/www/magento/dev/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#53 /var/www/magento/dev/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#54 /var/www/magento/dev/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#55 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#56 /var/www/magento/dev/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#57 /var/www/magento/dev/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'storeCookieVali...')
#58 /var/www/magento/dev/vendor/magento/module-store/Model/Plugin/StoreCookie.php(78): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#59 [internal function]: Magento\Store\Model\Plugin\StoreCookie->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#60 /var/www/magento/dev/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#61 /var/www/magento/dev/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#62 /var/www/magento/dev/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#63 /var/www/magento/dev/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#64 /var/www/magento/dev/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#65 {main}
```

NB: in developer mode

### CODE REVIEW

**Comment by mazhalai** [comment]
Please merge latest from develop and rerun builds.

**Comment by bchatard** [comment]
@mazhalai rebase from `develop` done, waiting Travis.

**Comment by bchatard** [comment]
@mazhalai I don't understand the link between the build failed and my work... It's not related. Or had I missing something?

**Comment by mazhalai** [comment]
@bchatard looks like the travis VMs were shut down. I just restarted them.

**Comment by Zatara7** [comment]
Hi @bchatard this issue has been fixed in scope of internal issue MAGETWO-47255. Thank you for your contribution.

**Comment by bchatard** [comment]
@Zatara7 ok, thanks

**Pull request closed without merging**
