### PR TITLE
[TASK] Remove translation of attribute store label in getAdditionalData

### PR DESCRIPTION
**Pull request by c-walter**
Attribute labels should be translated in magento admin setting correct translation for stores

Magento offers the possibility to set different labels for attributes in magento admin.
This commit solves the issue that some attribute-labels might get translated even if they are already translated, by setting correct value in magento admin.

### Description (*)

In \Magento\Catalog\Block\Product\View\Attributes::getAdditionalData an array of attributes will be returned.
Each array element contains 'code', 'value' and 'label'. 
Following the admin field in "stores -> attribtues -> products" select any attribute and there in "manage labels" tab
you are supposed to translate the attribute label for the specific languages / store-views in there.
But since the attribute-label will be translated again you might not get the result you set in magento admin, depending if you have a translation for the label you have chosen

### Manual testing scenarios (*)
Steps to reproduce
1. create a store-view using german as locale
2. create a translation file containing a translation for e.g. "Display","Anzeigen"
3. create a attribute with "Display" as a specific label for the store-view using german as locale
4. ensure the new attribute is shown in frontend ( on detail page)
5. check the detail-page while on the store-view ( with german as locale)
6. expected result would be "Display" as attribute label shown in frontend, current result will be "Anzeigen" because the label will be translated using the csv.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20482) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @c-walter. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by torhoehn — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @torhoehn, thank you for the review.
[ENGCOM-4374](https://jira.corp.magento.com/browse/ENGCOM-4374) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@c-walter thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request merged**
