### PR TITLE
Fixed The ui-component field validation error not opening accordion tab that owns the field (field does not get focused)

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

Fixed The ui-component field validation error not opening accordion tab that owns the field (field does not get focused)

### Fixed Issues (if relevant)

1. magento/magento2#17926: The ui-component field validation error not opening accordion tab that owns the field (field does not get focused)

### Manual testing scenarios (*)

1. N/A
### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by ravi-chandra3197** [comment]
Hello @slavvka 
I have updated my code can review it.

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3822](https://jira.corp.magento.com/browse/ENGCOM-3822) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @ravi-chandra3197 can you please squash this pull request to a single commit? (to remove unnecessary merge commits)

**Comment by sivaschenko** [comment]
Hi @ravi-chandra3197 I managed to remove the problematic merge commits from this pull request by changing base branch and changing it back. Looks like github issue

**Comment by ravi-chandra3197** [comment]
Hello @sivaschenko
Thank you very much for the help.

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Comment by aagasi** [comment]
Hi @ravi-chandra3197, your fix works as expected when editing a product in the admin. 

I'm wondering if there is also a similar fix for the admin configuration page (admin/admin/system_config/). That section contains collapsibles also, and it'll be very helpful to have your fix implemented there also.

Thanks,

**Pull request merged**
