### PR TITLE
Category image does not copy from catalog/tmp/category to catalog/category directory when saving category whilst using database storage method.

### LINKED ISSUE #11995: Category image does not copy from catalog/tmp/category to catalog/category directory when saving category whilst using database storage method
### Preconditions

1. Magento 2.4-develop

### Steps to reproduce

1. Set media storage to database
2. Upload category image in admin section
3. Save the category

### Expected result

1. The image row in media_storage_file_storage table should have directory `catalog/category` and correct `directory_id`

### Actual result

1. The image row in media_storage_file_storage table has directory `catalog/tmp/category`

I believe the problem lies with the `directory_id` not being changed in method `Magento\MediaStorage\Model\ResourceModel\File\Storage\Database::copyFile`

https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/MediaStorage/Model/ResourceModel/File/Storage/Database.php#L275

When I manually change the `directory_id` in `$data` from the `catalog/tmp/category` directory_id to the `catalog/category` directory_id before running the `$connection->insertOnDuplicate` method the file is correctly copied to another row with the correct data.

_As another note, should it not convert the existing row to simply change the `directory_id` and `directory` rather than copying to a new row..._

### PR DESCRIPTION
**Pull request by engcom-Kilo**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/11995

### Manual testing scenarios (*)

1. see https://github.com/magento/magento2/issues/11995

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by danielrussob** [comment]
@magento give me test instance

**Comment by danielrussob** [comment]
@magento give me 2.4-develop instance

**Comment by danielrussob** [comment]
issue reproduced on vanilla magento 2.4

**Comment by danielrussob** [comment]
issue solved on PR instance

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Review by aleron75 — COMMENTED** [review]
We are having some MFTF failures not directly related to this PR.
The team is working on fixing those, once that is done we can rerun the functional tests and make sure they are green.

**Review by danielrussob — APPROVED** [review]

**Comment by danielrussob** [comment]
According to Magento, we have a List of tests failing not related to this PR:
AdminAddRemoveDefaultVideoGiftCardProductTest
AdminAddRemoveDefaultVideoVirtualProductTest
AdminAddRemoveDefaultVideoBundleProductTest
StorefrontGalleryConfigurableProductWithVisualSwatchAttributePrependMediaTest
StorefrontGalleryConfigurableProductWithSeveralAttributesPrependMediaTest

**Comment by magento-engcom-team** [comment]
Hi @danielrussob, thank you for the review.
[ENGCOM-8674](https://jira.corp.magento.com/browse/ENGCOM-8674) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

### Manual testing scenario
1. From Admin Panel, go to _Catalog - Categories_
2. Select an existing Category
3. Expand **Content**
4. Under _Category Image_ click **Upload**
5. Open a valid image from local storage
6. Verify that the previously uploaded image appeared in Preview box
7. **Save** category
8. Open database table `media_storage_file_storage`
9. Observe _directory_ column

**BEFORE** applying changes provided in the PR, the path was _catalog/**tmp**/category_
tmp

**AFTER** switching to the PR, the category image is saved into the _catalog/category_ directory
tmp_after2

Tested with _Root_ and _Subcategories_

**Comment by aleron75** [comment]
@magento run Functional Tests CE

**Comment by aleron75** [comment]
@magento run Functional Tests EE, Functional Tests BB

**Comment by aleron75** [comment]
@magento run Functional Tests B2B

**Review by aleron75 — APPROVED** [review]
The failing B2B functional test doesn't seem related to the changes from this PR.

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-8674](https://jira.corp.magento.com/browse/ENGCOM-8674) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed
The result is the same as in the report above https://github.com/magento/magento2/pull/31646#issuecomment-764559591

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31646`.

**Pull request merged**
