### PR TITLE
Added constants to unit codes to make it easier to reuse it if necessary

### PR DESCRIPTION
**Pull request by tiagosampaio**
Added constants to unit codes to make it easier to reuse it if necessary.

### Description (*)

It's self explanatory.

### Fixed Issues (if relevant)

No issue is fixed with this PR.

### Manual testing scenarios (*)

No need for testing.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @tiagosampaio. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by nuzil — APPROVED** [review]
Thanks for your contribution

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-3774](https://jira.corp.magento.com/browse/ENGCOM-3774) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @tiagosampaio. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
