### PR TITLE
Set correct discount package value for tablerate

### LINKED ISSUE #30169: [Issue] Set correct discount package value for tablerate
This issue is automatically created based on existing pull request: magento/magento2#30167: Set correct discount package value for tablerate

---------

### Preconditions (*)

Magento 2.4-develop

This PR fixes the issue for the table rate carrier where the 'package value with discount' in the RateRequest is filled with the package value without the discount.

Currently, when you have a cart rule which sets a discount on the cart, the discount will not be used for the table rate.

Steps to reproduce:
1. Create a table rate based on subtotal, f.e. 5 euro from a subtotal of 0, free shipping from a subtotal of 100 euros.
2. Create a cart rule which sets a discount of 10% on cart, on subtotal only
3. Ensure you have an item in your cart which has the discount, with a value of between 105 euros.
4. The cart rule subtracts 10,5 from 105 - resulting in a total of 94,50. Shipping should be 5 euros as the subtotal now is below 100, but it's 0 because the price value without discount is used.

### Steps to reproduce: (*)

1. Create a table rate based on subtotal, f.e. 5 $ from a subtotal of 0, free shipping from a subtotal of 100 $.

Screenshot from 2020-10-06 15-10-32

2. Create a cart price rule which sets a discount of 10% on the cart, on subtotal only;
3. Ensure you have an item in your cart which has the discount, with a value of between 105 $;

Screenshot from 2020-10-07 16-01-22

**Actual Result:** :heavy_multiplication_x: Shipping amount is 0 because the price value without discount is used.

**Expected Result:** :heavy_check_mark: Shipping should be 5 euros

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by basvanpoppel**
### Description (*)

This PR fixes the issue for the table rate carrier where the 'package value with discount' in the RateRequest is filled with the package value without the discount.

Currently, when you have a cart rule which sets a discount on the cart, the discount will not be used for the table rate.

Steps to reproduce:
1. Create a table rate based on subtotal, f.e. 5 euro from a subtotal of 0, free shipping from a subtotal of 100 euros.
2. Create a cart rule which sets a discount of 10% on cart, on subtotal only
3. Ensure you have an item in your cart which has the discount, with a value of between 105 euros.
4. The cart rule subtracts 10,5 from 105 - resulting in a total of 94,50. Shipping should be 5 euros as the subtotal now is below 100, but it's 0 because the price value without discount is used.

### Manual testing scenarios (*)

1. Create a table rate based on subtotal, f.e. 5 euro from a subtotal of 0, free shipping from a subtotal of 100 euros.
2. Create a cart rule which sets a discount of 10% on cart, on subtotal only
3. Ensure you have an item in your cart which has the discount, with a value of between 105 euros.
4. The cart rule subtracts 10,5 from 105 - resulting in a total of 94,50. Shipping costs of 5 euros are applied, order total is 99,50.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30169: Set correct discount package value for tablerate

### CODE REVIEW

**Comment by swnsma** [comment]
Hi @basvanpoppel!
Thank you for your pull request!
Could you please sign Adobe CLA before we can start reviewing your pull request?

**Comment by basvanpoppel** [comment]
Hi @swnsma I've signed the CLA.

Please let me know if more information is needed, I'm happy to provide it.

**Review by swnsma — CHANGES_REQUESTED** [review]
Hi @basvanpoppel,

According to Magento Definition of Done all pull requests should have an auto tests coverage.
May I ask you to introduce an Integration or MFTF test scenario which could verify that bug in the PR can not be reproduced anymore?

**Comment by swnsma** [comment]
@magento run all tests

**Comment by basvanpoppel** [comment]
@magento run all tests

**Comment by basvanpoppel** [comment]
@magento run all tests

**Comment by basvanpoppel** [comment]
> Hi @basvanpoppel,
> 
> According to Magento Definition of Done all pull requests should have an auto tests coverage.
> May I ask you to introduce an Integration or MFTF test scenario which could verify that bug in the PR can not be reproduced anymore?

Hi @swnsma, 

I've written a MFTF test scenario to verify that the issue won't be reproduced anymore.

I've ran all tests. The reports don't mention any issues related to this pull request.

**Comment by swnsma** [comment]
@magento run all tests

**Comment by swnsma** [comment]
@magento run all tests

**Comment by swnsma** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by swnsma** [comment]
@magento run Functional Tests B2B

**Comment by swnsma** [comment]
@magento run Functional Tests B2B

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-8308](https://jira.corp.magento.com/browse/ENGCOM-8308) has been created to process this Pull Request

**Comment by swnsma** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Create a table rate based on subtotal, f.e. 5 $ from a subtotal of 0, free shipping from a subtotal of 100 $.

Screenshot from 2020-10-06 15-10-32

2. Create a cart price rule which sets a discount of 10% on the cart, on subtotal only;
3. Ensure you have an item in your cart which has the discount, with a value of between 105 $;

Screenshot from 2020-10-07 16-01-22

**Before:** :heavy_multiplication_x: Shipping amount is 0 because the price value without discount is used.




**After:** :heavy_check_mark: Shipping costs of 5 $ are applied

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Pull request merged**
