### PR TITLE
Load draggable and resizable jquery-ui chunks for dialog widget only if needed

### LINKED ISSUE #32810: [Issue] Load draggable and resizable jquery-ui chunks for dialog widget only if needed
This issue is automatically created based on existing pull request: magento/magento2#32802: Load draggable and resizable jquery-ui chunks for dialog widget only if needed

---------

### Description (*)
As in our shops we often struggle with huge javascript files, and quite a big amount of unused code, which lowers speed test results, I looked for some opportunity to remove not used code. Magento dropdownDialog widget (docs here: https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/widgets/widget_dialog.html) is based on dialog widget.  In dialog widget, there are available options: draggable and resizable, but in dropdown they are set to false and even not mentioned in the documentation or covered in tests. Besides dropdownDialog, dialog widget is also used in inline translation functionality, but this functionality is not used by end-users in the shop. 

To decrease the amount of unnecessary code I added dependency only for dialog widget that really needs resizable and draggable jquery-ui chunks.

### Manual testing scenarios (*)

1. Check if an element that uses dropdown widget (for example minicart) works as expected
2. Enable inline translations and check if you can move and resize translation dialog

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by martasiewierska**
### Description (*)
As in our shops we often struggle with huge javascript files, and quite a big amount of unused code, which lowers speed test results, I looked for some opportunity to remove not used code. Magento dropdownDialog widget (docs here: https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/widgets/widget_dialog.html) is based on dialog widget.  In dialog widget, there are available options: draggable and resizable, but in dropdown they are set to false and even not mentioned in the documentation or covered in tests. Besides dropdownDialog, dialog widget is also used in inline translation functionality, but this functionality is not used by end-users in the shop. 

To decrease the amount of unnecessary code I added dependency only for dialog widget that really needs resizable and draggable jquery-ui chunks.

### Manual testing scenarios (*)

1. Check if an element that uses dropdown widget (for example minicart) works as expected
2. Enable inline translations and check if you can move and resize translation dialog

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32810: Load draggable and resizable jquery-ui chunks for dialog widget only if needed

### CODE REVIEW

**Comment by martasiewierska** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
Nice fix thank you for such great improvements

**Comment by mrtuvn** [comment]
Just have a question ?
https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/widgets/widget_dropdown.html => This reference to dropdown widget used in codebase
dropdown widget seem only depend on jquery right ? i don't see reference to dialog (lib/mage/dialog.js)
Can you help clarify

**Comment by martasiewierska** [comment]
@mrtuvn Yes, I pasteed the wrong reference in the documentation, I am sorry. The proper one is: https://devdocs.magento.com/guides/v2.4/javascript-dev-guide/widgets/widget_dialog.html

So we have:
```
            'dropdownDialog':         'mage/dropdown',
            'dropdown':               'mage/dropdowns',
```

The first one is based on dialog.js and is used in minicart, msrp module and checkout sidebar (but is not resizable or draggable there) and the second one is much lighter and used in some other places. I will adjust the description.

**Comment by mrtuvn** [comment]
Thank you for response! And great improvements

**Comment by ptylek** [comment]
Looks good to me. I think this is the same scenario as in other [PR](https://github.com/magento/magento2/pull/32756) and it might be too hard to cover these changes with any test. What do you think @mrtuvn?

**Review by ptylek — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-9027](https://jira.corp.magento.com/browse/ENGCOM-9027) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@martasiewierska thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by mrtuvn** [comment]
Agreed with ptylek

**Comment by mrtuvn** [comment]
@magento create issue

**Pull request merged**
