### PR TITLE
[Backport] Orders-and-Returns-layout-not-proper

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Original Pull Request 
 https://github.com/magento/magento2/pull/20817

### Fixed Issues (if relevant)

1. magento/magento2#20816: Orders and Returns layout not proper
2. Magento 2.3

### Manual testing scenarios (*)

1. Click Orders and Returns link in footer

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by Karlasa — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Karlasa, thank you for the review.
[ENGCOM-4230](https://jira.corp.magento.com/browse/ENGCOM-4230) has been created to process this Pull Request

**Comment by Karlasa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Karlasa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Karlasa, here is your [new Magento instance](https://pr-21163.instances.magento-community.engineering).
Admin access: [https://pr-21163.instances.magento-community.engineering/admin](https://pr-21163.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Pull request merged**
