### PR TITLE
FIX #27299 Consecutive Requests in Integration Tests failing

### LINKED ISSUE #27299: Integration Tests: Consecutive `dispatch($uri)` on Test AbstractController fails
### Preconditions (*)
1. Integration Tests in Magento `2.4-develop`

### Steps to reproduce (*)
1. Create a test that uses `\Magento\TestFramework\TestCase\AbstractController::dispatch` for dispatching controller.
2. Add the second request to any other URI.

### Expected result (*)
1. Both requests are dispatched

### Actual result (*)
1. First request is dispatched
2. Second request throws `InvalidArgumentException: Invalid return type`

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Consecutive Requests in Integration Tests were failing due to the fact of Requests object being shared between dispatches. I am aware that some developers need to perform the same `dispatch` multiple times with the same object, so I haven't destroyed Request object after dispatch.

Under the hood, Magento was skipping Execution, as `isDispatched` was `true`, so the whole `dispatch()` was returning `null`

https://github.com/magento/magento2/blob/510310b9f98da9453b6d3bf33d51a6167f7e5926/lib/internal/Magento/Framework/App/FrontController.php#L85-L116

Instead - I just call `setDispatched(false)` before each `dispatch()`.
Additionally, I introduced `resetRequest` method that empties the state of Request.

### Fixed Issues (if relevant)
1. magento/magento2#27299

### Manual testing scenarios (*)
Described in #27299 

### Questions or comments
I had no time to investigate why implementing `resetRequest` with destroying old Request object and instantiating new one causes Fatal errors, but the current implementation is also correct.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

**Comment by lbajsarowicz** [comment]
As you can see - the issue was known before. This is extremely sad, that it was not fixed globally.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @lbajsarowicz,
Could you add some tests that checks that actual issue was fixed?

**Comment by lbajsarowicz** [comment]
I have this in separate PR but sure, I can copy some of them here. That's actually good idea.

**Comment by lbajsarowicz** [comment]
To make sure that Integration Test works, you can comment out:
`dev/tests/integration/framework/Magento/TestFramework/TestCase/AbstractController.php:112`

As a result you'll get:
```
$ vendor/bin/phpunit -c $(pwd)/dev/tests/integration/phpunit.xml $(pwd)/dev/tests/integration/testsuite/Magento/Backend/Controller/Adminhtml/ConsecutiveCallTest
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

EII                                                                                                                                                                                                                                                                                                                                                     3 / 3 (100%)

Time: 41.53 seconds, Memory: 101.00MB

There was 1 error:

1) Magento\Backend\Controller\Adminhtml\ConsecutiveCallTest::testConsecutiveBackendRequestFailsWhenRequestIsNotReset
InvalidArgumentException: Invalid return type

/var/www/html/lib/internal/Magento/Framework/App/Http.php:124
/var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php:24
/var/www/html/dev/tests/integration/framework/Magento/TestFramework/Application.php:449
/var/www/html/dev/tests/integration/framework/Magento/TestFramework/Helper/Bootstrap.php:117
/var/www/html/dev/tests/integration/framework/Magento/TestFramework/TestCase/AbstractController.php:121
/var/www/html/dev/tests/integration/testsuite/Magento/Backend/Controller/Adminhtml/ConsecutiveCallTest.php:20
/var/www/html/vendor/phpunit/phpunit/phpunit:53

ERRORS!
Tests: 3, Assertions: 0, Errors: 1, Incomplete: 2.
```

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7143](https://jira.corp.magento.com/browse/ENGCOM-7143) has been created to process this Pull Request

**Pull request merged**
