### PR TITLE
Test Management for Travis CI

### PR DESCRIPTION
**Pull request by munderseth**
### Description
We’ve made a few minor changes to demonstrate how [Testspace.com](https://www.testspace.com/) can be used by your team to better manage your **test results**. Note that there is **no** impact on the workflow and the product is **completely free** for open source.

YOUR TEST RESULTS from `our fork` at https://open.testspace.com/projects/TryTestspace:magento2.

Testspace Badge:

[Space Health](https://open.testspace.com/spaces/122535?utm_campaign=badge&utm_medium=referral&utm_source=test "Test Cases")

### Fixed Issues (if relevant)

NA

### Manual testing scenarios
None

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=17220) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @munderseth. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by orlangur** [comment]
Hi @munderseth, could you please add more details how is this useful compared to current Travis CI? I don't see all the test types and I don't see any useful metrics in https://open.testspace.com/spaces/122535/metrics.

**Comment by munderseth** [comment]
Hi @orlangur,  below are my responses to your questions. 

> add more details how is this useful compared to current Travis CI?

* Test Failures can be filtered on, speeding up the resolution process; versus using a `Travis Log`. It also filters on all failures across all of the jobs (matrix). This speeds up triaging, especially for your *new* contributors
* Represent all of your tests in an `organized fashion controlled by your source repo`. Also, it presents a visual hierarchy of what is actually running in Travis.   
* Detailed timing, stdout/stderr output, etc., even when not failing
* Can push other content such as code coverage, static analysis, HTML, log files, etc.

>  I don't see all the test types

Are you referring to the `integration tests`? If yes, we pushed the results [HERE](https://open.testspace.com/spaces/122535/schema/PHP-7.2/dev/tests/integration/testsuite/Magento) based on the test code source organization. This can be easily changed. 

If no, can you provide us the tests that were missed?

>  I don't see any useful metrics in https://open.testspace.com/spaces/122535/metrics.

First, there is only 1 Results set. If you have time, please take a look at https://demo.testspace.com. The content is from our own development (we use GitHub and Circle CI). There are lots of unique metrics, both at the branch level and the project (repo) level.

**Comment by orlangur** [comment]
@munderseth where I can see the jobs the same way like in https://travis-ci.org/magento/magento2/builds/409146891?utm_source=github_status&utm_medium=notification?

I mean unit, integration, functional and static tests separately.

> Test Failures can be filtered on, speeding up the resolution process

Please explain this a little more. PHPUnit log is perfect in terms of finding failed tests as to me.

> Represent all of your tests in an organized fashion controlled by your source repo

What? Tests are already well-organized.

> Detailed timing, stdout/stderr output, etc., even when not failing

How this can be useful? Only job total time really matters. PHPUnit plugins can be used in order to determine longest test or something.

> Can push other content such as code coverage, static analysis, HTML, log files, etc.

Code coverage would slow down jobs a lot and can be done on top of current Travis CI without any issues.

**Comment by munderseth** [comment]
> I mean unit, integration, functional and static tests separately.

* Here is a branch that is organized with the results based on the test type: https://open.testspace.com/spaces/122572/schema
* You can organize your results anyway you want, we just picked an approach.

> Please explain this a little more. PHPUnit log is perfect in terms of finding failed tests as to me.

When there are a lot of failures, or the log is very large, or the failures happen across a number of jobs, etc. it can be tedious to track them down. Testspace provides a flat list very quickly containing the stderr output, etc.

> What? Tests are already well-organized.

By presenting the test results such that they can be easily navigates by `others` -- managers, etc. -- makes the testing more visible. The type of testing, number of Suites, etc., it very difficult to determine from Travis Jobs. Testspace focus is on Test Management for CI. 

> Code coverage would slow down jobs a lot and can be done on top of current Travis CI without any issues.

 Sure, I agree. But having coverage published along with your test results provides visibility and tracking to others -- managers, etc. 

---

On another topic, some customers push CSV files and create custom metrics (profiling, memory usage, etc.). If you have any interest we have a help article on this - https://help.testspace.com/spaces:custom-metrics.

**Comment by ihor-sviziev** [comment]
I don't think we should add this service.
1. tests not for managers, they are for developers.
2. This service don't seems to me as user friendly and useful. Is there any **really useful example** what we will have with this service and don't have with Travis?

**Comment by orlangur** [comment]
Hi @munderseth, as per discussion here and in Slack it does not seem that proposed service integration bring any value to automated testing compared to vanilla Travis CI. Thanks for collaboration!

**Pull request closed without merging**
