### PR TITLE
Prevent side effect on category objects store_id and url_key on save

### LINKED ISSUE #29585: [Issue] Prevent side effect on category objects store_id and url_key on save
This issue is automatically created based on existing pull request: magento/magento2#28164: Prevent side effect on category objects store_id and url_key on save

---------

### Preconditions (*)

Magento 2.4-develop

Category URL rewrites are saved by an "after save" observer for categories. But if saved for global scope, the URL rewrite generator itself modifies the passed category object *for each assigned store* to generate URL rewrites for all stores. Afterwards, url_key, url_path and store_id have the values of the last processed store id. This has side effects on later observers or other code that works on the category object after saving it.

Since the default store (0) is always the first item of `$category->getStoreIds()` I chose to clone the category object only for the other stores, so that url_key and url_path for the global scope are still set to the original object.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Steps to reproduce (*)

Abbreviated test case

```
$category->setStoreId(0);
$category->setUrlKey('url-key-for-global-scope');
$categoryResource->save($category);
```
### Expected result (*)
`$category->getStoreId()` should return `0`

### Actual result (*)
`$category->getStoreId()` returns value of the last processed store id.
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by schmengler**
### Description (*)

Category URL rewrites are saved by an "after save" observer for categories. But if saved for global scope, the URL rewrite generator itself modifies the passed category object *for each assigned store* to generate URL rewrites for all stores. Afterwards, url_key, url_path and store_id have the values of the last processed store id. This has side effects on later observers or other code that works on the category object after saving it.

Since the default store (0) is always the first item of `$category->getStoreIds()` I chose to clone the category object only for the other stores, so that url_key and url_path for the global scope are still set to the original object.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

Abbreviated test case

```
$category->setStoreId(0);
$categoryResource->save($category);
$this->assertEquals(0, $category->getStoreid());
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29585: Prevent side effect on category objects store_id and url_key on save

### CODE REVIEW

**Comment by schmengler** [comment]
(I'm wating if the PR breaks the core test suite because of all the mocking before committing my own test)

**Comment by sidolov** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8030](https://jira.corp.magento.com/browse/ENGCOM-8030) has been created to process this Pull Request

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
:heavy_check_mark: QA Passed

**before** :heavy_multiplication_x::
image


**after** :heavy_check_mark::
image

**Pull request merged**
