### PR TITLE
Upgrade to the latest matchMedia.js

### LINKED ISSUE #32857: Investigate upgrade to the latest matchMedia.js
### Overview

For the matchMedia.js library we need to identify the following additional details:

- If this library is used on Admin UI or Storefront Luma or both
- What exact functionality is using this particular library
- What is a preliminary scope of work to migrate to the new version.
- Is it possible to migrate without introducing BIC into Luma
- Level of the impact of updating dependency in terms of BIC

### Investigation Outcome
A complete report of affected areas, ways to migrate code and level of BIC caused by migration.

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Update js to more recently version

Overview
For the matchMedia.js library we need to identify the following additional details:

If this library is used on Admin UI or Storefront Luma or both: Frontend only (Blank/Luma)
What exact functionality is using this particular library
What is a preliminary scope of work to migrate to the new version.
Is it possible to migrate without introducing BIC into Luma
Level of the impact of updating dependency in terms of BIC

Investigation Outcome
A complete report of affected areas, ways to migrate code and level of BIC caused by migration.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32857

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
looks like these changes are fully backward compatible, so we can easily update it

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9056](https://jira.corp.magento.com/browse/ENGCOM-9056) has been created to process this Pull Request

**Review by ptylek — APPROVED** [review]

**Review by Den4ik — APPROVED** [review]
@mrtuvn Thanks for contribution.
:heavy_check_mark: Approve

But I think that it's not P1 priority because in this update/fix was provided for jest tests only
> This allows us to use the polyfill when testing with Jest, which uses
jsdom under the hood.

https://github.com/paulirish/matchMedia.js/commit/6c0ba0112804f393439a1edc031b880766cc9765

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9056](https://jira.corp.magento.com/browse/ENGCOM-9056) has been created to process this Pull Request

**Comment by dmitriyprime** [comment]
:heavy_check_mark:  QA passed

**Pull request merged**
