### PR TITLE
Enable filter type extension in search request

### PR DESCRIPTION
**Pull request by markoweb**
Extending the filter type is not possible due to strict fields and methods restriction. Also would be better to use builders for creating the new filter instances with possibility to define filter types through dependency injection.

### CODE REVIEW

**Comment by maghamed** [comment]
In accordance with [Magento 2 technical vision](http://devdocs.magento.com/guides/v2.1/coding-standards/technical-guidelines/technical-guidelines.html) 

> 2.6. Inheritance SHOULD NOT be used. Composition SHOULD be used for code reuse.

We don't encourage to use Inheritance Based API, and strongly encourage to use composition instead

**Comment by maghamed** [comment]
The potential issue I see is that we don't have an interface for 
\Magento\Framework\Search\Request\Builder
to provide an ability substitute out of the box implementation with a custom one.
But could you please provide your use-case why do you want to make customization at this level?

**Comment by markoweb** [comment]
I have implemented a custom filter type for the Elasticsearch (EE) module (nested datatype). It implements the `\Magento\Framework\Search\Request\FilterInterface` interface.
The problem is that in the following places it will crash because of the unrecognized data type:
* https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Search/Request/Cleaner.php#L196
* https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Search/Request/Mapper.php#L233
E.g. there is a filter instance creation hardcoded for a predefined types in the switch. That could be solved by creating builders and defining them through the dependency injection.

**Comment by maghamed** [comment]
the problem with Filters why we don't have FilterBuilder as a part of the contract in Framework is that each specific filter is very different from others.
For example, we have such global Builder for MySQL implementations.
Which operates with existing filter Builders
https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Search/Adapter/Mysql/Filter/Builder.php

**Comment by maghamed** [comment]
@markoweb I agree that we have an architectural gap here, not providing the ability to introduce new Filters and throwing Exceptions if they added.
I will think about how that could be fixed. 
@markoweb are you interested to continue work on this issue if I'll provide more sophisticated but more robust solution from the M2 Architecture perspective?

**Comment by okorshenko** [comment]
Hi @markoweb 
Are you going to proceed with this PR or we should close it?
Thank you

**Comment by markoweb** [comment]
Hi @okorshenko 
We can close it

**Pull request closed without merging**
