### PR TITLE
HOTFIX: Invalid use of OpenOrderById

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
When order is created with API - just like in `Magento/Sales/Test/Mftf/Test/AdminReorderWithCatalogPriceTest.xml` - `entity_id` is being returned, not `increment_id`. As a result - trying to filter out the Order using `entity_id` that is *different* than `increment_id` - tests fail.

### Fixed Issues (if relevant)
All the Pull Requests for B2B / Magento EE.

### Manual testing scenarios (*)
Execute MFTF. 

### Questions or comments
Please do a quick merge to unlock the Magento EE / B2B tests.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
I agree that we need this clarification in order to avoid confusion. In the case of `entity_id` and `increment_id` we would need two action groups `...OpenByEntityId...` and `...OpenByIncrementId...` but not simply `...OpenById...` because ID is ambiguous in this naming.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-6549](https://jira.corp.magento.com/browse/ENGCOM-6549) has been created to process this Pull Request

**Comment by lbajsarowicz** [comment]
@rogyar That is right, but cleaning up ActionGroup names will be done as a separate PR, because that will be related with huge amount of discussions and "Backward Compatibility" workarounds, to not break the systems that currently rely on these ActionGroups.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by lbajsarowicz** [comment]
This PR still needs to be merged, as to fix delivered by @danmooney2 uses direct call to `<amOnPage` which is considered to be bad practice. Whole test should be rewritten using MFTF best practices to avoid using direct Action calls, to use ActionGroups only.

**Comment by VladimirZaets** [comment]
Hi @lbajsarowicz. Thanks for collaboration. Fix already provided in the 2.4-develop branch

**Pull request closed without merging**
