### PR TITLE
Use session proxy for checkout SuccessValidator

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
In the session constructor, we have session_start, so in order to speed up the object creation and not causing exceptions when they're not expected (during object creation), we should use Proxy for all sessions as a workaround.
More info about this issue https://github.com/magento/magento2/issues/17310#issuecomment-742422361

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by swnsma** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Comment by swnsma** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by swnsma** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Comment by gabrieldagama** [comment]
Hi @ihor-sviziev, thanks for your contribution. I've read your investigation and I guess proxy can be used as a workaround, I don't see a major problem with this.

Just to confirm, the changes in this PR aren't fixing #17310, just addressing a similar problem in another place, right?

If that is the case, can we create another issue for it? Thanks!

**Comment by ihor-sviziev** [comment]
@gabrieldagama sure! That's definitely should be another issue.

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-8548](https://jira.corp.magento.com/browse/ENGCOM-8548) has been created to process this Pull Request

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @ihor-sviziev .

It seems that the problem is not completely solved by changes in this PR.

**Manual testing scenario:**

1. Browse the order pages in the admin area;
2. Click on an order;
3. Reload the page several times (10 for ex)

**Actual Result:** :heavy_multiplication_x: session_start(): Failed to read session data...

Peek 2020-12-17 14-28

4. Go to Storefront -> My Account;
5. Open created before the order for the view;
6. Reload the page several times (10 for ex)

**Actual Result:** :heavy_multiplication_x: session_start(): Failed to read session data...

Peek 2020-12-17 14-59

@ihor-sviziev Could you take a look?
Thanks!

**Comment by ihor-sviziev** [comment]
As we discussed with @engcom-Charlie - it should be tested together with https://github.com/magento/magento2/pull/31263

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev
Thank you for your contribution. This pull request has been combined (merged) with https://github.com/magento/magento2/pull/31263 to optimize pull requests queue on magento/magento2 repository
Closing this pull request.

**Pull request closed without merging**
