### PR TITLE
#36636 - prevent ShippingAssignmentBuilder and ShippingBuilder from loading order when not needed.

### LINKED ISSUE #36636: [Performance] Loading order through repository loads the order multiple times from DB. (ShippingBuilder)
### Summary

Magento 2.4.5-p1

Loading order through repository loads the order three times from DB : 

```
$this->orderRepository->get($orderId);
```
Loads the order from database, then calls setShippingAssignments() which calls TaxManagement::getShippingAssignmentBuilderDependency() which loads the order from database again.

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/Order/ShippingBuilder.php#L79

and

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/Order/ShippingAssignmentBuilder.php#L79

### Examples

```
$this->orderRepository->get($orderId);
```

### Steps to reproduce
1. Login in frontend with the user which has atleast 1 order
2. Enable DB log
3. Add breakpoints in the below lines:
https://github.com/magento/magento2/blob/9ef88b46ff666673623e3f04d969c46ecf396cad/app/code/Magento/Sales/Model/OrderRepository.php#L137

https://github.com/magento/magento2/blob/9ef88b46ff666673623e3f04d969c46ecf396cad/app/code/Magento/Sales/Model/Order/ShippingAssignmentBuilder.php#L79

https://github.com/magento/magento2/blob/9ef88b46ff666673623e3f04d969c46ecf396cad/app/code/Magento/Sales/Model/Order/ShippingBuilder.php#L79
4. Try to access `My Account` page
5. The function `$this->orderFactory->create()->load($this->getOrderId())` is calling 3 times for order id `2`. Below is the MySQL query fetched from db.log:
```
SELECT `sales_order`.* FROM `sales_order` WHERE (`sales_order`.`entity_id`='2')
SELECT `sales_order`.* FROM `sales_order` WHERE (`sales_order`.`entity_id`='2')
SELECT `sales_order`.* FROM `sales_order` WHERE (`sales_order`.`entity_id`='2')
```

### Proposed solution

I guess line 
`$shippingAssignments->setOrderId($order->getEntityId());`
should be replaced somehow by
`$shippingAssignments->setOrder($order);`

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Nuranto**
### Description (*)

see magento/magento2#36636

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36636

### Manual testing scenarios (*)

see magento/magento2#36636

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Nuranto** [comment]
@magento run all tests

**Comment by Nuranto** [comment]
@magento run all tests

**Comment by Nuranto** [comment]
@magento run Integration Tests, Static Tests, WebAPI Tests

**Comment by Nuranto** [comment]
@magento run Static Tests, WebAPI Tests, Functional Tests CE, Functional Tests B2B

**Comment by andrewbess** [comment]
This PR already merged and shouldn't have pending review status

**Pull request merged**
