### PR TITLE
[Forwardport] Fix "Required parameter 'theme_dir' was not passed" error when emulating an environment inside an emulated area

### LINKED ISSUE #29100: [Issue] [Forwardport] Fix "Required parameter 'theme_dir' was not passed" error when emulating an environment inside an emulated area
This issue is automatically created based on existing pull request: magento/magento2#19287: [Forwardport] Fix "Required parameter 'theme_dir' was not passed" error when emulating an environment inside an emulated area

---------
### Original pull request
#17344 

### Description
Environment emulation inside an area emulation returns the error "Required parameter 'theme_dir' was not passed". The classes `\Magento\Theme\Model\View\Design` and `\Magento\Theme\Model\Theme` retrieve their area from the app state unless the area is emulated (see their `getArea()` method). When the environment is emulated inside an area emulation, the app state's area is used. This causes incorrect behaviour when the environment is being emulated.

### Manual testing scenarios

```php
use \Magento\Framework\App\Area;

class Emulation
{
    /**
     * @var \Magento\Store\Model\App\Emulation
     */
    protected $appEmulation;

    /**
     * @var \Magento\Framework\App\State
     */
    protected $appState;

    public function __construct(
        \Magento\Store\Model\App\Emulation $appEmulation,
        \Magento\Framework\App\State $appState
    ) {
        $this->appEmulation = $appEmulation;
        $this->appState = $appState;
    }

    public function execute()
    {
        $this->appState->emulateAreaCode(Area::AREA_ADMINHTML, function () {
            $this->appEmulation->startEnvironmentEmulation(1, Area::AREA_FRONTEND, true);
            $this->appEmulation->stopEnvironmentEmulation();
        });
    }
}
```

I've executed this class using a cronjob (the cache needs to be flushed before starting). I have a store with the id "1" (lets call this store "default"). The default store uses the theme `Magento/luma`. `startEnvironmentEmulation(..)` at some point tries to load the default store's theme. `\Magento\Theme\Model\Theme getFullPath()` gets invoked and returns `adminhtml/Magento/luma`. The theme's full path is wrong as the app state's area is being used instead of the environments area, because the app state is emulated. This then prevents the theme from being loaded and produces an error. I've added a method to also check if the environment is being emulated and used it to load the correct area. 

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### PR DESCRIPTION
**Pull request by dnsv**
Depends on https://github.com/magento/magento2/issues/21370

### Original pull request
#17344 

### Description
Environment emulation inside an area emulation returns the error "Required parameter 'theme_dir' was not passed". The classes `\Magento\Theme\Model\View\Design` and `\Magento\Theme\Model\Theme` retrieve their area from the app state unless the area is emulated (see their `getArea()` method). When the environment is emulated inside an area emulation, the app state's area is used. This causes incorrect behaviour when the environment is being emulated.

### Manual testing scenarios

```php
use \Magento\Framework\App\Area;

class Emulation
{
    /**
     * @var \Magento\Store\Model\App\Emulation
     */
    protected $appEmulation;

    /**
     * @var \Magento\Framework\App\State
     */
    protected $appState;

    public function __construct(
        \Magento\Store\Model\App\Emulation $appEmulation,
        \Magento\Framework\App\State $appState
    ) {
        $this->appEmulation = $appEmulation;
        $this->appState = $appState;
    }

    public function execute()
    {
        $this->appState->emulateAreaCode(Area::AREA_ADMINHTML, function () {
            $this->appEmulation->startEnvironmentEmulation(1, Area::AREA_FRONTEND, true);
            $this->appEmulation->stopEnvironmentEmulation();
        });
    }
}
```

I've executed this class using a cronjob (the cache needs to be flushed before starting). I have a store with the id "1" (lets call this store "default"). The default store uses the theme `Magento/luma`. `startEnvironmentEmulation(..)` at some point tries to load the default store's theme. `\Magento\Theme\Model\Theme getFullPath()` gets invoked and returns `adminhtml/Magento/luma`. The theme's full path is wrong as the app state's area is being used instead of the environments area, because the app state is emulated. This then prevents the theme from being loaded and produces an error. I've added a method to also check if the environment is being emulated and used it to load the correct area. 

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### Resolved issues:
1. [x] resolves magento/magento2#29100: [Forwardport] Fix "Required parameter 'theme_dir' was not passed" error when emulating an environment inside an emulated area

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @dnsv. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19287) <br/>All committers have signed the CLA.

**Comment by sivaschenko** [comment]
Hi @dnsv thanks for your contribution! Can you please sign the [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=19287) as we cannot process this pull request until it's signed.

**Comment by dnsv** [comment]
Hi @sivaschenko. I've signed the CLA.

**Comment by slavvka** [comment]
Hey @dnsv we detected that your fix is breaking the functionality.

**Failed manual scenario:**
1. Enable developer mode.
1. Clean static files. adminhtml specifically.
1. Navigate to admin login page.
1. Login.
1. Refresh the dashboard page after successful login.

✅ **Expected result:**
User stays on dashboard page.

⛔️ Actual result:
User is redirected on admin login page

Please consider fixing this issue as well

**Comment by dnsv** [comment]
Hi @slavvka. I've added in my initial changes a dependency to `Magento\Store\Model\App\EmulationInterface` inside `Magento\Theme\Model\Theme` and `Magento\Theme\Model\View\Design`. This seems to affect the user's admin session as it gets regenerated when a valid one already exists. 

The session is handled by the `Magento\Framework\Session\SessionManager` class. Its constructor calls its `start()` method, which checks if a session exists and otherwise creates one. `Magento\Framework\App\Area\EnvironmentEmulation` through its dependencies ( -> `Magento\Backend\Model\Locale\Resolver` -> `Magento\Backend\Model\Session`) instantiates the `SessionManager` and triggers the session check and its possible generation. 

When the user logins into the backend the session gets regenerated, which is expected. After that, additional resources are loaded using js and these requests require the classes `Theme` and `Design`, which through their dependencies trigger the session check. Because these requests are made using js, the `SessionManager` can't correctly check if a session already exists and thus creates a new one. The user is then redirected to the admin login page on his next request.

`Theme` and `Design` both have the same implementation for the `getArea()` method, which (with my changes) calls the `isEnvironmentEmulated()` method from `EmulationInterface`. It seems that the js requests call the `getArea()` method but never get to the `isEnvironmentEmulated()` part, so one possible solution would be to inject `EmulationInterface` as a proxy, consequently the class wouldn't get instantiated and no session check would occur, but this would just be a workaround. The session check on js requests should in my opinion be addressed as a separate bug.

**Comment by slavvka** [comment]
@dnsv you are probably right but cannot accept a PR that fixes one bug and introduces a new one. You have right to create another issue as well but it should be fixed as well before we approve this one. Does it make sense?

**Comment by dnsv** [comment]
@slavvka I've added the Issue #21370 to address the session bug.

**Comment by sidolov** [comment]
Hi @dnsv , will you continue progress with pull request? As far as I understand, we need to fix session related bug that was introduced by provided fixes.

**Comment by dnsv** [comment]
Hi @sidolov. I have added a separate issue (#21370) to address the session related bug. That issue was closed, but I have since then added further details, for which I am not sure if they were reviewed. It would be great if someone could reevaluate the issue as I am still convinced that the bug exists also outside this PR.

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
Hey @dnsv Sorry for the delay. The issue you created (#21370) is reopened and thus this PR can be processed separately. I have restarted all tests so let's see their state.

**Comment by slavvka** [comment]
@magento run Functional Tests build

**Comment by slavvka** [comment]
Hey @dnsv Please take a look and fix the failing tests

**Comment by dnsv** [comment]
Hi @slavvka Although this PR is now processed separately from the session related bug, it still heavily depends on it. I've described a possible workaround in the last paragraph of [this](https://github.com/magento/magento2/pull/19287#issuecomment-461181225) comment, otherwise, this PR has to wait for #21370 to be resolved.

**Comment by slavvka** [comment]
@dnsv Okay, Setting this PR on hold until #21370 is fixed.

**Comment by VladimirZaets** [comment]
@magento create issue

**Comment by gabrieldagama** [comment]
The risk was set to `medium` due to: even though the changes in this PR are small, they may affect several modules.

**Comment by hostep** [comment]
@Den4ik: perhaps. It might still fix https://github.com/magento/magento2/issues/17673 according to [my findings from a couple of years ago](https://github.com/magento/magento2/issues/17673#issuecomment-423804497)

**Comment by Den4ik** [comment]
@dnsv Could you please update branch with actual 2.4-develop

**Comment by maaarghk** [comment]
just came across an actual bug caused by this when adding pipeline deploy config to an existing project - exported the config from a copy of the database, which meant `flag` row was not generated on the dev site's database. Running `app:config:import` prompted `The following themes will be registered: adminhtml/Magento/blank, adminhtml/Magento/luma` because the theme full paths were generated inside adminhtml emulation ([here](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Deploy/Console/Command/App/ConfigImportCommand.php#L104) -> [here](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Theme/Model/Config/Importer.php#L129)). I just stuck a breakpoint [here](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Deploy/Model/DeploymentConfig/ChangeDetector.php#L75) and put the correct hash in the database manually.

I checked on some other sites and it does indeed seem updating themes by updating config.php is totally broken, I couldn't see any other issues along those lines (maybe related to #33479) but I just tried changing the name of a theme and I can't do it, it just wants to re-make all the themes under adminhtml "scope".

**Pull request closed without merging**
