### PR TITLE
MFTF: Replace invalid ActionGroup for AdminLogin

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
The ActionGroup for logging in as admin was declared in `module-cms-staging` that is completely ridiculous. I moved that as a legacy one to `backend` module, as we already have 3 action groups for such behavior :man_facepalming: After merging all related Pull Requests, that Action Group can be removed.

### Fixed Issues (if relevant)
1. https://github.com/magento/partners-magento2ee/pull/113
1. https://github.com/magento/magento2/issues/26331

### Questions or comments
Had to extract the changes per-module. The previous try failed, because of conflicts.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by dmytro-ch** [comment]
Hi @lbajsarowicz, unfortunately, I could not find the original action group in `2.4-develop` branch.
https://github.com/magento/magento2/tree/2.4-develop/app/code/Magento/Cms/Test/Mftf/ActionGroup
Have you already removed this action in the scope of another PR?

**Comment by lbajsarowicz** [comment]
CMS Staging module
Take a look into linked issue https://github.com/magento/partners-magento2ee/pull/113

-- Especially: https://github.com/magento/partners-magento2ee/pull/113/files#diff-1dc91bcc26d07540dece9d2a9931e2feL108

**Comment by dmytro-ch** [comment]
These action groups still have different names: `LoginAsAnyUserActionGroup` and `LoginAsAnyUser`.
Shouldn't we name it `LoginAsAnyUser` instead of `LoginAsAnyUserActionGroup` in this case?
Sorry for asking many questions, I just want to make sure I got the idea correctly. :)

**Comment by lbajsarowicz** [comment]
You are right. Thank you!

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6594](https://jira.corp.magento.com/browse/ENGCOM-6594) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Why would you mark it as deprecated instead of removing it?

**Comment by lbajsarowicz** [comment]
@lenaorobei this one is for sure used by lots of people that might be mad about removal

**Comment by lbajsarowicz** [comment]
More than perfect for me

**Comment by lenaorobei** [comment]
@lbajsarowicz are you still up to work on it?

**Comment by lbajsarowicz** [comment]
I've checked yesterday, that we don't have MFTF 2.6.0 on Magento 2.4-develop yet.
Waiting to proceed with my changes. Also waiting to CI be viable :-(

**Comment by lenaorobei** [comment]
@lbajsarowicz MFTF was updated. We can move forward with it.

**Comment by lbajsarowicz** [comment]
@lenaorobei I went really big with that change. :crossed_fingers: to get this pass.

**Comment by lbajsarowicz** [comment]
@magento run all tests

Complete blackout
image

**Review by lenaorobei — APPROVED** [review]

**Comment by lbajsarowicz** [comment]
image

:heavy_check_mark:  Lucky PR

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-6594](https://jira.corp.magento.com/browse/ENGCOM-6594) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Golf** [comment]
Hi @lbajsarowicz could you please resolve conflicts ?

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests CE
Flaky test

**Pull request merged**
