### PR TITLE
Attribute set delete was throwing the 404

### PR DESCRIPTION
**Pull request by jignesh26**
### Description (*)

When admin try to delete the attribute set it throwing the error 404 cause HttpGetActionInterface was missing.

### Manual testing scenarios (*)

1. Add new attribute set. 
2. try to delete that attribute set. 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @jignesh26. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by larsroettig** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @larsroettig. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @larsroettig, here is your [Magento instance](https://i-19682-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19682-2-3-develop.instances.magento-community.engineering/admin](https://i-19682-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by larsroettig** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @larsroettig. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @larsroettig, here is your [new Magento instance](https://pr-19682.instances.magento-community.engineering).
Admin access: [https://pr-19682.instances.magento-community.engineering/admin](https://pr-19682.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by larsroettig** [comment]
✔️ Issues Verified 
✔️ Review
✔️ Manual Testing

**Review by larsroettig — APPROVED** [review]

**Comment by sreichel** [comment]
FYI: there is another PR that adresses that issue .... https://github.com/magento/magento2/pull/19633

**Comment by sivaschenko** [comment]
Hi @jignesh26 thanks for your contribution! However, the fix for this issue is already provided earlier. Please see https://github.com/magento/magento2/pull/19633

Closing as a duplicate.

**Comment by jignesh26** [comment]
@sivaschenko , i think i have provided better solution rather then passing just empty data set to ajax request. i have changed the attribute set action interface and it also changing the Application state. 

Please feedback on this. 
Thank you.

**Comment by sivaschenko** [comment]
Hi @jignesh26 the delete operation should be done using POST method (as it does change the application state). The fix in https://github.com/magento/magento2/pull/19633 is ensuring the POST request.

Considering the above, the controller should not be marked by `HttpGetActionInterface `

**Comment by sivaschenko** [comment]
Closing this pull request as not actual: the issue https://github.com/magento/magento2/issues/19607 is already fixed

**Pull request closed without merging**
