### PR TITLE
[Backport] Fixed typo from filed to field

### PR DESCRIPTION
**Pull request by gelanivishal**
### Description

Fixed typo from filed to field

### Fixed Issues (if relevant)

None
### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### Original PR 
https://github.com/magento/magento2/pull/18505

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-3173](https://jira.corp.magento.com/browse/ENGCOM-3173) has been created to process this Pull Request

**Comment by sidolov** [comment]
Hi @gelanivishal  , we are trying to focus on the 2.3 release line and all code cleanup like typos, spelling mistakes, removing unused code, etc should be delivered to 2.3 release line.
Thank you!

**Comment by gelanivishal** [comment]
Hello @sidolov, I'll take care of next time while creating a new PR.

Thank you.

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
