### PR TITLE
Alternative fix for Multi Store Emails issue, Fix Async Emails issues, Fix Multiple Email issues.

### PR DESCRIPTION
**Pull request by gwharton**
### Description
This PR removes the previously introduced transportBuilderByStore class that was introduced in 2.2.4 to fix issue #11740 as this implementation caused unwanted regression/bug when sending multiple emails/async emails.
It adds new default parameter to setFrom method of transportBuilder class.

Possible sticking point, is this adds a new default parameter to public method of an API class.

### Fixed Issues (if relevant)
1. magento/magento2#11740:Sending emails from Admin in Multi-Store Environment defaults to Primary Store
2. magento/magento2#16165:Sales Emails Async Sending issue
3. magento/magento2#16203:New order notification is not sent to the admin
4. magento/magento2#14952:Confirmation emails have no FROM or FROM email address 2.2.4
5. magento/magento2#14945:Store Email Addresses are not used anymore
6. magento/magento2#16355:Magento 2.2.4 not sending from sales sender
7. magento/magento2#16509:Magento 2.2.4 Multishipping Order Confirmation Emails sent only for the first order
8. magento/magento2#14236:Sending multiple emails using the TransportBuilder class causes an Zend_Mail exception
9. magento/magento2#7739:"From Header set twice" when sending an email
10. magento/magento2#17781:Magento 2.2.5 Order Email Confirmation is not working

### Manual testing scenarios
Scenareo 1
- Single store
- Setup store email addresses
- Complete checkout
- Verify from address in confirmation email

Scenareo 2
- Multiple store
- Setup store email addresses for Store 1
- Setup store email addresses for Store 2
- Complete checkout on Store 1- Verify from address in confirmation email
- Complete checkout on Store 2- Verify from address in confirmation email

Scenareo 3
- Single Store
- Setup store email addresses
- Enable Async Email sending
- Disable cron job
- Complete checkout
- Complete checkout again
- Run cronjob once from command line
- Ensure both confirmation emails are received

Scenareo 4
- Single Store
- Setup store email addresses
- Add admin confirmation email address, using "separate email" as type.
- Complete checkout
- Ensure both confirmation and copy confirmation email are received.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16461) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by gwharton** [comment]
OK, to avoid over complicating things and to clean up, I will close down all other pull requests that are attempting to fix these issues. I have taken into account all other PR's and comments in this PR. Hopefully this will be the sum of all ideas. This is the PR that will go forward.

**Comment by gwharton** [comment]
Once approved and merged, I will forwardport the necessary changes to 2.3-develop to ensure both branches are consistent.

**Comment by RedAtRareCandy** [comment]
Experiencing this issue also. Originally had 2.2.3 then upgraded by command line to 2.2.4 and noticed that emails would come through to email as the hostname instead of the From set in Magento admin. I've upgraded to 2.2.5 by command line, tested this again, and this is still an issue.

The only way to get emails to send correctly is through the 3rd party MageFix_Misc module that was linked in one of the other threads.

**Comment by gwharton** [comment]
@RedAtRareCandy. A workaround for the issue you are having is to disable the amazon payments module. You don't need the magefix module.

**Comment by RedAtRareCandy** [comment]
@gwharton Appreciate the suggestion but that broke the one page checkout so I'm afraid that's not a workaround for me. MageFix_Misc works great though :)

**Comment by hostep** [comment]
@RedAtRareCandy : just FYI since you already have a solution (or for other people finding this):

The Amazon_Login module depends on the Amazon_Payment module and disabling only the latter will indeed cause the checkout to no longer work, so you have to disable both these modules by running:
`bin/magento module:disable Amazon_Login Amazon_Payment`

**Comment by RedAtRareCandy** [comment]
Thanks @hostep , that worked. Do you know why though? I don't want to have those modules disabled if they added functionality to the checkout - did they?

**Comment by hostep** [comment]
@RedAtRareCandy: just read the description on their github page to see what these modules are for: https://github.com/amzn/amazon-payments-magento-2-plugin/
If you don't need those functionalities, then just leave those modules disabled.

The [issue](https://github.com/amzn/amazon-payments-magento-2-plugin/issues/274) is going to get [fixed](https://github.com/amzn/amazon-payments-magento-2-plugin/pull/289) in an update of the Amazon module presumably, and also might get fixed in Magento itself by this PR (since that's probably the root cause). But I don't have any knowledge about time frames for those fixes.

**Comment by gwharton** [comment]
Whats the general view on this one inside Magento? is it a goer. Anything else I can do to help push forward?

**Comment by ihor-sviziev** [comment]
Hi,
Right now we have interal discussion about this issue. I'll send an update once we'll have some results

**Comment by matthewvolk** [comment]
Hi, 
I'm assuming this PR is not included in 2.2.6 then. Following up on the last discussion about an "internal discussion", do we know when we might be able to see this patch applied?

**Comment by gwharton** [comment]
Replaced with PR #18472. This PR has become detached from source repo somehow, so closing and opening new PR.

**Pull request closed without merging**
