### PR TITLE
magento/magento2#26245: Magento does not send an email about a refunded grouped product

### PR DESCRIPTION
**Pull request by atwixfirster**
### Fixed Issues (if relevant)

1. magento/magento2#26245: Magento does not send an email about a refunded grouped product

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

Thank you!

### CODE REVIEW

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello @atwixfirster, thank you for your contribution. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) the changes should be covered by tests. Could you please cover your fix by automated tests?
Thank you!

**Comment by atwixfirster** [comment]
> Hello @atwixfirster, thank you for your contribution. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) the changes should be covered by tests. Could you please cover your fix by automated tests?
> Thank you!

@dmytro-ch , can we deliver this fix without tests?

Thank you!

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
I will take care of test coverage.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6768](https://jira.corp.magento.com/browse/ENGCOM-6768) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

The Credit Memo is created and the e-mail is received 

created_credit_memo
credmemo_email

**Comment by engcom-Echo** [comment]
Failure of functional test, not related to the changes in this PR , test failing on 2.4-develop branch
image

**Comment by slavvka** [comment]
MCHI is approved since there was introduced a protected method in class whose parent has the same protected method

**Pull request merged**
