### PR TITLE
Make CSS minifying compatible with calc() CSS function

### PR DESCRIPTION
**Pull request by sambolek**
See magento/magento2#8552

### Description
Whitespace around "-" sign got removed during CSS minification due to regex done in tubalmartin/cssmin, which got fixed in https://github.com/tubalmartin/YUI-CSS-compressor-PHP-port/commit/59e5e8b0b8225244aea90da3cd5f81b1ba575da2#diff-80f11f7052c350cef68c3041a5479789R588

### Fixed Issues (if relevant)
1. magento/magento2#8552
2. magento/magento2#6822

### Manual testing scenarios
1. Set Magento in production mode (minify doesn't work on developer or default modes)
2. Extend Magento theme and use CSS calc() function in your less file. Example:
`body{width: calc((100% / 12 * 2) - 10px);}`
3. Turn Minify CSS on in admin
4. Observe results, whitespace arond "-" sign should not be removed

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=9027) <br/>All committers have signed the CLA.

**Comment by ishakhsuvarov** [comment]
Hi @sambolek 
Please look into integration tests failure on Travis CI.
Thanks!

**Comment by sambolek** [comment]
Fixed minification test. Also added a css class for scenario I mentioned in initial comment https://github.com/magento/magento2/pull/9027/files#diff-fc5a29319a5c4fcef6f8eb67024ebb20 which checks if calc is minified correctly.

**Comment by sambolek** [comment]
What about files like: 

-  https://github.com/magento/magento2/blob/develop/dev/tests/integration/testsuite/Magento/Framework/Composer/_files/testFromClone/composer.json#L37

- https://github.com/magento/magento2/blob/develop/dev/tests/integration/testsuite/Magento/Framework/Composer/_files/testFromClone/composer.lock#L736

- https://github.com/magento/magento2/blob/develop/dev/tests/integration/testsuite/Magento/Framework/Composer/_files/testFromCreateProject/composer.lock#L4688

- https://github.com/magento/magento2/blob/develop/dev/tests/integration/testsuite/Magento/Framework/Composer/_files/testSkeleton/composer.lock#L4668

- https://github.com/magento/magento2/blob/develop/dev/tests/integration/testsuite/Magento/Setup/Model/_files/testSkeleton/composer.lock#L4668

Should those be updated to reflect the version change too?

**Comment by sambolek** [comment]
Added test for issue #6822 , as this update would fix it as well.

**Comment by tubalmartin** [comment]
Just to let you know guys, as the maintainer of YUI-CSS-compressor-PHP-port, that I've just released v3.0.0 which is the most stable release to date. Updating to this version is strongly recommended.

**Comment by sambolek** [comment]
Hi Túbal,
library updated to v3.0.0 - thanks for your good work :)

@vrann @ishakhsuvarov 
Is this approach okay for replacing the library with a new psr-4 version, or should I implement a new css minify adapter and deprecate the current one?
https://github.com/magento/magento2/pull/9027/commits/d7266b3174d21a0d1a9bb2d47d08bfd8c86fa328#diff-afc0f5b51cca601618e0ba6fd13ca75c

Will look into tests once they're run. For some reason they don't even start for some time, once I push a few commits in - is that intended behavior on Travis CI?

**Comment by ishakhsuvarov** [comment]
@sambolek Looks good to me, however we need to verify that nothing was broken by version bump.

**Comment by sambolek** [comment]
Hi @ishakhsuvarov 
is there anything else I can help with here?

Could you please give some input about my comment above, do this files need changing. If so, that would be the process to update them?

https://github.com/magento/magento2/blob/develop/dev/tests/integration/testsuite/Magento/Framework/Composer/_files/testFromClone/composer.json#L37

https://github.com/magento/magento2/blob/develop/dev/tests/integration/testsuite/Magento/Framework/Composer/_files/testFromClone/composer.lock#L736

https://github.com/magento/magento2/blob/develop/dev/tests/integration/testsuite/Magento/Framework/Composer/_files/testFromCreateProject/composer.lock#L4688

https://github.com/magento/magento2/blob/develop/dev/tests/integration/testsuite/Magento/Framework/Composer/_files/testSkeleton/composer.lock#L4668

https://github.com/magento/magento2/blob/develop/dev/tests/integration/testsuite/Magento/Setup/Model/_files/testSkeleton/composer.lock#L4668

**Comment by ishakhsuvarov** [comment]
@sambolek I'll try to run the full functional tests suite for starters, then we will continue with the rest, if you are ok with it :)

**Comment by sambolek** [comment]
Sure.

**Comment by magento-team** [comment]
@sambolek Thank you for the contribution

**Pull request merged**
