### PR TITLE
Major Quote Bugfix

### PR DESCRIPTION
**Pull request by christopher-silvey**
Logged in customer was returning null for $customerId. See Issue #24391 for more details. Please also see closed PR Major Quote Bugfix #24465 which I closed in order to fix CLA issues.

### CODE REVIEW

**Review by kalpmehta — APPROVED** [review]

**Comment by kalpmehta** [comment]
@magentoman2009 Can you please add automated tests?

**Comment by christopher-silvey** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @magentoman2009. Thank you for your request. I'm working on Magento instance for you

**Comment by christopher-silvey** [comment]
@magento give me 2.3-develop instance - deploy vanilla Magento instance

**Comment by magento-engcom-team** [comment]
Hi @magentoman2009. Thank you for your request. I'm working on Magento 2.3-develop instance - deploy vanilla Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @magentoman2009, here is your [new Magento instance](https://pr-24685.instances.magento-community.engineering).
Admin access: [https://pr-24685.instances.magento-community.engineering/admin](https://pr-24685.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by christopher-silvey** [comment]
@magento give me test instance - deploy test instance based on PR changes

**Comment by magento-engcom-team** [comment]
Hi @magentoman2009. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @magentoman2009, here is your [new Magento instance](https://pr-24685.instances.magento-community.engineering).
Admin access: [https://pr-24685.instances.magento-community.engineering/admin](https://pr-24685.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by christopher-silvey** [comment]
> @magentoman2009 Can you please add automated tests?

Did I do it right? If not, what do I need to do? Sorry, I'm new to this process. Thanks!

**Comment by kalpmehta** [comment]
@magentoman2009 Please check this: https://devdocs.magento.com/guides/v2.3/test/testing.html
If you have not written tests before it's fine, I will go ahead and remove the label "needs update". It's highly encouraged to add tests when necessary, like in this case. 

Feel free to add the tests if you are able to. Thank you for your contribution!

**Comment by christopher-silvey** [comment]
@kalpmehta

Gotcha, thanks! We should be good to go now :)

**Comment by engcom-Alfa** [comment]
Hi @magentoman2009 

Unfortunately, we are not able to reproduce this issue on the fresh 2.3-develop instance.
 Could you take a look?

Thanks!

**Comment by VladimirZaets** [comment]
@magentoman2009 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Pull request closed without merging**
