### PR TITLE
[Backport]fixes-for-#21046-2-2

### PR DESCRIPTION
**Pull request by nainesh2jcommerce**
### Original Pull Request 
 https://github.com/magento/magento2/pull/21046

### Description (*)

Removed unwanted condition check. This check is not needed, Because always create a new instance

### Manual testing scenarios (*)

1.  Create "CMS Page" with "CMS Page Link" widget and browse in the frontend
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4314](https://jira.corp.magento.com/browse/ENGCOM-4314) has been created to process this Pull Request

**Comment by dmytro-ch** [comment]
@abrarpathan19, why did you close the PR from another developer?
This PR is already approved.

**Comment by abrarpathan19** [comment]
@dmytro-ch I am the author of this PR so I have the priority to backport my issue first.

**Comment by sivaschenko** [comment]
Hi @nainesh2jcommerce , thanks for the backport! 

However, the original pull request is marked as a cleanup. We cannot accept cleanup pull requests to 2.2-develop. 

See [Contribution Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for details.

**Pull request closed without merging**
