### PR TITLE
Fixed Help Tooltip extra space

### PR DESCRIPTION
**Pull request by abrarpathan19**
### Description (*)

I have fixed Help Tooltip extra space which is available on the entire Magento admin.  

### Fixed Issues (if relevant)

1. magento/magento2#23502: Help tooltip icon extra space issue

### Manual testing scenarios (*)

1. Login to Magento admin
2. Where help tooltip available in Magento admin

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-5380](https://jira.corp.magento.com/browse/ENGCOM-5380) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
Hi @abrarpathan19 Unfortunately I cannot reproduce issue described by PR on 2.3-develop
#23504Import

#23504Conf

**Comment by sidolov** [comment]
@abrarpathan19 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by sivaschenko** [comment]
@abrarpathan19 if the issue still reproducible on the latest codebase, can you please update the steps with the details to help us to confirm the issue.

**Comment by sidolov** [comment]
@abrarpathan19 I'm closing this PR since there is no activity for 5 days after reopen. 
Please, update your code and reopen PR if you wish to continue. 
Thank you for collaboration!

**Pull request closed without merging**
