### PR TITLE
[Forwardport 2.3] Captcha: Added integration test for checking admin login attempts cleanup

### PR DESCRIPTION
**Pull request by rogyar**
Original PR: https://github.com/magento/magento2/pull/16300

### Description
The integration test checks that the admin login attempts are being removed after a cuccessful login

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios
N/A

### CODE REVIEW

**Comment by orlangur** [comment]
@rogyar please start from `2.2-develop`.

**Comment by rogyar** [comment]
@orlangur done (https://github.com/magento/magento2/pull/16300). "Converted" this one to port. Thank you

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-2092](https://jira.corp.magento.com/browse/ENGCOM-2092) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.3.0 release.

**Pull request merged**
