### PR TITLE
Refactor code : remove direct use of object manager

### PR DESCRIPTION
**Pull request by AnshuMishra17**
### Description
Remove direct use of object manager for admin attribute set save controller using constructor based dependency injection.

### Manual testing scenarios
1. Created a new attribute set in admin under Stores -> Attribute Set -> Add Attribute Set.
2. Edit an existing attribute set under Stores -> Attribute Set

### CODE REVIEW

**Comment by AnshuMishra17** [comment]
@ihor-sviziev I am seeing error message "The class Save has a coupling between objects value of 13. Consider to reduce the number of dependencies under 13" in the failed test report. It will be helpful if you can make me understand what is meant by this error statement and how I can fix it

**Comment by ihor-sviziev** [comment]
@AnshuMishra17  you can add it to ignore. Here is example: https://github.com/magento/magento2/blob/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/lib/internal/Magento/Framework/Module/Setup/MigrationData.php#L11

**Comment by AnshuMishra17** [comment]
@ihor-sviziev I was trying to merge all commits into single commit, but now it is showing me that I have closed this PR. What steps I did wrong? It is show ing me to generate a new PR.

**Comment by ihor-sviziev** [comment]
@AnshuMishra17 looks like you did force push with branch that has no changes. As result  - PR was marked as closed. I think you could push your correct changes in the same branch and then reopen this pr

**Pull request closed without merging**
