### PR TITLE
Fix #30471 - Page layouts are hard-coded in Magento\Widget\Block\Adminhtml\Widget\Instance\Edit\Chooser\Container

### LINKED ISSUE #30471: Page layouts are hard-coded in Magento\Widget\Block\Adminhtml\Widget\Instance\Edit\Chooser\Container
### Preconditions (*)

Magento 2.3.5

### Steps to reproduce (*)

Have a look at the code source of `Magento\Widget\Block\Adminhtml\Widget\Instance\Edit\Chooser\Container`.

### Expected result (*)

The function `getPageLayouts()` should return the actual list of page layouts declared by the different modules.

### Actual result (*)

The function `getPageLayouts()` only returns the one provided by Magento_Theme, and they are hard-coded in the file:

```php
    /**#@+
     * Frontend page layouts
     */
    const PAGE_LAYOUT_1COLUMN = '1column-center';
    const PAGE_LAYOUT_2COLUMNS_LEFT = '2columns-left';
    const PAGE_LAYOUT_2COLUMNS_RIGHT = '2columns-right';
    const PAGE_LAYOUT_3COLUMNS = '3columns';
    /**#@-*/

   [...]

  /**
     * Retrieve page layouts
     *
     * @return array
     */
    protected function getPageLayouts()
    {
        return [
            self::PAGE_LAYOUT_1COLUMN,
            self::PAGE_LAYOUT_2COLUMNS_LEFT,
            self::PAGE_LAYOUT_2COLUMNS_RIGHT,
            self::PAGE_LAYOUT_3COLUMNS,
        ];
    }
```

### Workaround

I may be possible to override `Magento\Widget\Block\Adminhtml\Widget\Instance\Edit\Chooser\Container` and to inject an instance of `Magento\Framework\View\Model\PageLayout\Config\BuilderInterface` to grab the list of available page layouts from there. Untested though.

### Thoughts

Basically, it makes any container with Label declared in a non-Magento Theme page layout not selectable from the back-office to inject widgets. But the simple fact that Magento_Widget assumes that some page layouts exist is concerning. This concern is actually confirmed by the fact that one of the four hard-coded page layouts doesn't even exist: `1column-center`.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This is a fix for #30471 issue

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/465

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30471

### Manual testing scenarios (*)

Please check fixed issue for steps descrription

### Questions or comments

Not sure if any kind of tests would fit here

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Bartlomiejsz** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Unit Tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @Bartlomiejsz,
Could you fix failing unit tests?

**Comment by engcom-Hotel** [comment]
Hello @Bartlomiejsz,
I'll check unit tests.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Manual testing scenario:**

- Create custom theme with [layout](https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/layouts/layout-create.html): `3-columns-double-footer`
- Go to Content->Widgets
- Click Add Widget
- Select Type=Catalog Products List and Design Theme=<ThemeName>
- Click Continue
- Click Storefront Properties->Layout Updates->Add Layout Update
- Set Display On=All Page
- Check value `$pageLayouts` in `Magento\Widget\Block\Adminhtml\Widget\Instance\Edit\Chooser\Container`


**Before:**
:x:  The function `getPageLayouts()` only returns the one provided by Magento_Theme
Screenshot from 2021-02-02 11-33-38


**After:**
:heavy_check_mark: The function `getPageLayouts()` returns the actual list of page layouts declared by the different modules
Screenshot from 2021-02-02 11-41-04

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Integration Tests, WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run Integration Tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Pull request merged**
