### PR TITLE
URLs should not contains reserved characters according to RFC 3986

### LINKED ISSUE #36042: [Issue] URLs should not contains reserved characters according to RFC 3986
This issue is automatically created based on existing pull request: magento/magento2#35885: URLs should not contains reserved characters according to RFC 3986

---------

### Description (*)

This PR fixes the [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986.html) which forbids to use reserved characters in URLs such as a comma.

### Manual testing scenarios (*)

1. Use the URL : `http://magento2.adobe/encoding/with/longer/url/`
2. Encode this URL with the `Magento\Framework\Url\Encoder::encode` method
3. Note that the base64 encoded URL contains a comma : `aHR0cDovL21hZ2VudG8yLmFkb2JlL2VuY29kaW5nL3dpdGgvbG9uZ2VyL3VybC8,`
4. Use the native method [rawurlencode](https://www.php.net/manual/fr/function.rawurlencode.php) from PHP on the result : `aHR0cDovL21hZ2VudG8yLmFkb2JlL2VuY29kaW5nL3dpdGgvbG9uZ2VyL3VybC8%2C` (please notice the %2C character which is the hexadecimal value for a comma, which is **not allowed**.
5. Decode this URL back : `http://magento2.adobe/encoding/with/longer/url/6` (a `6` was added at the end of the URL because of the encoded value)

### Questions or comments

In my understanding of the RFC, an URL can't contain a comma (or whatever reserved characters). However, Magento uses such character in the `encode` method to remove the `=` character from the base64 encoded value.

https://github.com/magento/magento2/blob/c6aeb6aef1eaf849aadeeadedd63ac6cd3dc23fc/lib/internal/Magento/Framework/Url/Encoder.php#L18

This PR replaces the comma value by a tilde as this is an unreserved character allowed for an URL and which will not be transformed in the `rawurlencode` method.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by MeCapron**
### Description (*)

This PR fixes the [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986.html) which forbids to use reserved characters in URLs such as a comma.

### Manual testing scenarios (*)

1. Use the URL : `http://magento2.adobe/encoding/with/longer/url/`
2. Encode this URL with the `Magento\Framework\Url\Encoder::encode` method
3. Note that the base64 encoded URL contains a comma : `aHR0cDovL21hZ2VudG8yLmFkb2JlL2VuY29kaW5nL3dpdGgvbG9uZ2VyL3VybC8,`
4. Use the native method [rawurlencode](https://www.php.net/manual/fr/function.rawurlencode.php) from PHP on the result : `aHR0cDovL21hZ2VudG8yLmFkb2JlL2VuY29kaW5nL3dpdGgvbG9uZ2VyL3VybC8%2C` (please notice the %2C character which is the hexadecimal value for a comma, which is **not allowed**.
5. Decode this URL back : `http://magento2.adobe/encoding/with/longer/url/6` (a `6` was added at the end of the URL because of the encoded value)

### Questions or comments

In my understanding of the RFC, an URL can't contain a comma (or whatever reserved characters). However, Magento uses such character in the `encode` method to remove the `=` character from the base64 encoded value.

https://github.com/magento/magento2/blob/c6aeb6aef1eaf849aadeeadedd63ac6cd3dc23fc/lib/internal/Magento/Framework/Url/Encoder.php#L18

This PR replaces the comma value by a tilde as this is an unreserved character allowed for an URL and which will not be transformed in the `rawurlencode` method.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36042: URLs should not contains reserved characters according to RFC 3986

### CODE REVIEW

**Comment by MeCapron** [comment]
@magento run all tests

**Comment by MeCapron** [comment]
https://github.com/magento run all tests

**Comment by MeCapron** [comment]
@magento run all tests

**Comment by MeCapron** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Functional Tests EE, Functional Tests B2B, Functional Tests CE

**Comment by MeCapron** [comment]
https://github.com/magento run Functional Tests CE

**Comment by MeCapron** [comment]
@magento run Functional Tests CE

**Review by Den4ik — APPROVED** [review]
✅ Approved
@MeCapron Thanks for PR

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Lima** [comment]
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** branch.

**Description:**
URLs should not contains reserved characters according to RFC 3986

**Pre-requisite:**
Fresh magento `2.4-develop` should be installed.

**Steps to reproduce:**

1. Use the URL : http://magento2.adobe/encoding/with/longer/url/
2. Encode this URL with the Magento\Framework\Url\Encoder::encode method
3. Note that the base64 encoded URL contains a comma : aHR0cDovL21hZ2VudG8yLmFkb2JlL2VuY29kaW5nL3dpdGgvbG9uZ2VyL3VybC8,
4. Use the native method rawurlencode from PHP on the result : aHR0cDovL21hZ2VudG8yLmFkb2JlL2VuY29kaW5nL3dpdGgvbG9uZ2VyL3VybC8%2C (please notice the %2C character which is the hexadecimal value for a comma, which is not allowed.
5. Decode this URL back : http://magento2.adobe/encoding/with/longer/url/6 (a 6 was added at the end of the URL because of the encoded value)

**After PR changes:** This PR fixes the RFC 3986 which forbids to use reserved characters in URLs such as a comma.

**Additionally tested:**

- Created order from frontend.
- From admin, created invoice.
- Created shipping.
- Created credit memo,
- Reordered the product.

PR is working fine. Hence, moving it to Merge in progress.

**Comment by engcom-Lima** [comment]
@magento give me 2.4.4 instance

**Pull request merged**
