### PR TITLE
Remove requirement of always available SPL extension

### PR DESCRIPTION
**Pull request by carusogabriel**
### Description (*)
Since PHP 5.3.0, the SPL extension is always available and it can not be disabled.

Ref: https://php.net/manual/en/spl.installation.php
### Fixed Issues (if relevant)
None

### Manual testing scenarios (*)
Not necessary

### Questions or comments
None 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-6018](https://jira.corp.magento.com/browse/ENGCOM-6018) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@carusogabriel thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Delta** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Delta. Thank you for your request. I'm working on Magento instance for you

**Comment by engcom-Delta** [comment]
Hi @carusogabriel . Could you resolve merge conflicts?

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-6018](https://jira.corp.magento.com/browse/ENGCOM-6018) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
