### PR TITLE
Refactor: Improve Recurring Setup (Cron Jobs termination) class readability

### LINKED ISSUE #31375: [Issue] Refactor: Improve Recurring Setup (Cron Jobs termination) class readability
This issue is automatically created based on existing pull request: magento/magento2#31357: Refactor: Improve Recurring Setup (Cron Jobs termination) class readability

---------

### Description (*)
1. Added description
2. Improved readability of a class

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
1. Added description
2. Improved readability of a class

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31375: Refactor: Improve Recurring Setup (Cron Jobs termination) class readability

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@magento create issue

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8560](https://jira.corp.magento.com/browse/ENGCOM-8560) has been created to process this Pull Request

**Comment by lbajsarowicz** [comment]
This does not matter for the system.

**Pull request closed without merging**
