### PR TITLE
code cleanup (http to https)

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

code cleanup (http to https)
### Fixed Issues (if relevant)

1. N/A

### Manual testing scenarios (*)

1. N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4836](https://jira.corp.magento.com/browse/ENGCOM-4836) has been created to process this Pull Request

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hi @ravi-chandra3197,
thank you for your contribution!

Could you please also apply the same changes for other URLs like:
```http://docs.magento*```
There are around 20 occurrences.

**Comment by ravi-chandra3197** [comment]
Hello @dmytro-ch,
I have updated PR as per your suggestion, can you review it.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4836](https://jira.corp.magento.com/browse/ENGCOM-4836) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
