### PR TITLE
Fix wrong credit card type comparation

### LINKED ISSUE #35662: [Issue] Fix wrong credit card type comparation
This issue is automatically created based on existing pull request: magento/magento2#34775: Fix wrong credit card type comparation

---------
### Description 

Fix wrong credit card type comparation

`if (cardInfo.title == allowedTypes[i].type)` is incorrect comparation. `cardInfo.title` will be 'Visa', 'Master',.... but `allowedTypes[i].type` is VI, MC,...

### PR DESCRIPTION
**Pull request by ndlinh-celtic**
### Description 

Fix wrong credit card type comparation

`if (cardInfo.title == allowedTypes[i].type)` is incorrect comparation. `cardInfo.title` will be 'Visa', 'Master',.... but `allowedTypes[i].type` is VI, MC,...

### Resolved issues:
1. [x] resolves magento/magento2#35662: Fix wrong credit card type comparation

### CODE REVIEW

**Comment by ndlinh** [comment]
@magento run all tests

**Comment by bgorski** [comment]
@ndlinh-celtic can you provide information on how to trigger the incorrect behavior?

**Comment by engcom-Alfa** [comment]
@magento give me test instance

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance

**Comment by ndlinh-celtic** [comment]
@magento give me 2.4-develop instance

**Comment by bgorski** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by bgorski — APPROVED** [review]
There are some functional tests failing, but I reviewed them and they don't seem to have any connection to this particular scenario. Accepting.

**Comment by engcom-Lima** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Lima** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by engcom-Lima** [comment]
Hi @ndlinh-celtic 

Thanks for your contribution and collaboration.

I have gone to through yours [comment](https://github.com/magento/magento2/pull/34775#issuecomment-989885702)  _"Magento default doesn't have credit card payment form, so it's difficult to re-produce this problem with default magento instance."_
I have enabled PayPal in my local 2.4-develop, in frontend I got credit card payment form. 
Kindly assist me, How can I can reproduce this issue?
Below is the screenshot for your reference:
image

**Comment by engcom-Lima** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by engcom-Alfa** [comment]
Hi @ndlinh-celtic 
With the default Paypal payment methods credit card form, we are not able to see any JS errors as such in the console.

1. If it is specific by adding a new payment gateway with a new CC form including card validation, Ca you please confirm?
2. Can you please let us know step-by-step procedure you have followed to come up with a new payment gateway for better understanding?
3. Also, even after multiple tries, there are 3 auto-test jobs are getting failed, Can you help us with your fixes on this?

Thanks in advance!

**Comment by engcom-Alfa** [comment]
Hi @ndlinh-celtic 
I tried to reach you thru Slack channel, but could not find you there!
You are invited to join the [Magento Community Slack Channel](https://developer.adobe.com/open/magento/slack), please feel free to join the workspace.

**Comment by ndlinh-celtic** [comment]
@magento give me 2.4-develop instance

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @ndlinh ,
Looks like you are working on this as per my [above-comment.](https://github.com/magento/magento2/pull/34775#issuecomment-1173726926) Kindly revert us on it.
Thanks in advance!

**Pull request closed without merging**
