### PR TITLE
Implement ActionInterface for /translation/ajax (+ Unit Tests)

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
This is a part of the process of introducing implementations of `ActionInterface`.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @lbajsarowicz,
In general your changes looks good to me.
Could you review integration tests failure?

**Comment by lbajsarowicz** [comment]
@ihor-sviziev That was missing support of `GET` methods (Assumed that if there is `Request::getPost()`, this cannot be called with `GET`.

**Review by ihor-sviziev — DISMISSED** [review]
Functional test failures are not related to changes in this PR

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7206](https://jira.corp.magento.com/browse/ENGCOM-7206) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Translate Inline works as before fix

**Comment by lbajsarowicz** [comment]
@slavvka and @VladimirZaets The only time to introduce that kind of change is 2.3 -> 2.4 as it's strongly backwards-incompatible change. Please re-consider keeping that until 2.4.1

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
FYI this PR was moved to "oh hold" due to internal discussions, reason the same as here https://github.com/magento/magento2/pull/27538#issuecomment-624891873

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @lbajsarowicz ,
We finally have final decision, it clearly described here https://github.com/magento/magento2/pull/27296#pullrequestreview-418541438.

Could you bring back inheritance from abstract action?

**Comment by lbajsarowicz** [comment]
If anyone else wants to pick this, feel free to take my code and continue.
I won't be available to handle that in next 2 - 3 weeks.

**Pull request closed without merging**
