### PR TITLE
32320 - Update laminas/laminas-db package

### PR DESCRIPTION
**Pull request by AndreyChorniy**
### Description (*)

This PR created for update laminas/laminas-db package
### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/519

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32320

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by AndreyChorniy** [comment]
@magento run all tests

**Comment by AndreyChorniy** [comment]
@magento run Integration Tests Functional Tests B2B

**Comment by AndreyChorniy** [comment]
@magento run Integration Tests,Functional Tests B2B

**Comment by AndreyChorniy** [comment]
@magento run Functional Tests B2B

**Review by sivaschenko — APPROVED** [review]

**Comment by sivaschenko** [comment]
@magento run all tests

**Pull request merged**
