### PR TITLE
wishlist-patch : remove the comment from wishlist product.

### PR DESCRIPTION
**Pull request by khodu**
### Description (*)

if we try to remove the comment from wishlist product then the 'Comment' value is not deleted if we try to update it then updated.
### Fixed Issues (if relevant)

1. magento/magento2#20245: if we try to remove the comment from wishlist product then the 'Comment' value is not deleted if we try to update it then updated.

### Manual testing scenarios (*)

1. Create simple product
2. Create customer and Login in Storefront
3. Add product to wishlist
4. On 'My Wish List' page add Comment for product
5. Click 'Update Wish List' button
6. Remove the created comment
7. Click 'Update Wish List' button
now comment is removed.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @khodu. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-3922](https://jira.corp.magento.com/browse/ENGCOM-3922) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @khodu. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Comment by magento-engcom-team** [comment]
Hi @khodu. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
