### PR TITLE
Backport.  Success message is not showing when creating invoice & shipment simultaniously #

### PR DESCRIPTION
**Pull request by XxXgeoXxX**
### Preconditions (*)
Magento 2.3
PHP 7.1.3
#### Steps to reproduce (*)
Create order from admin panel.
View order at admin panel and Click "create invoice".
Check the checkbox "create shipment" and "Email copy of invoice" while generating invoice. and click submit invoice button.
#### Expected result (*)
Success message should show as "You created the invoice and shipment."
#### Actual result (*)
Invoice has been created but no success message is appearing.

### Fixed Issues (if relevant)
Backport for https://github.com/magento/magento2/pull/20391
### Manual testing scenarios (*)
Create order from admin panel.
View order at admin panel and Click "create invoice".
Check the checkbox "create shipment" and "Email copy of invoice" while generating invoice. and click submit invoice button.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sdzhepa** [comment]
Put `on hold` till #20391 will be merged

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4651](https://jira.corp.magento.com/browse/ENGCOM-4651) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
