### PR TITLE
Update _navigation.less

### PR DESCRIPTION
**Pull request by receter**
### Description
I had was a little confused by the naming of variables, I guess it should be like this.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=10777) <br/>All committers have signed the CLA.

**Comment by miguelbalparda** [comment]
Hi @receter! thank you for your contribution. This seems like a suggestion instead of a bug fix. Would you mind adding more details/sources to back up your suggestion?

**Comment by receter** [comment]
Hi,

sure. 

Variables are usually be named like this:
@_submenu-item__STATE__CSSPROPERTY

eg.
@_submenu-item__active__border-style: @submenu-desktop-item__active__border-style,
@_submenu-item__active__border-width: @submenu-desktop-item__active__border-width,

Some of the variables are named different which leads to inconsistent naming which might cause confusion.
eg.
@_submenu-item-color-active: @submenu-desktop-item__active__color

I just renamed them. The scope of all renamed variables is local.

**Comment by okorshenko** [comment]
Hi @receter 
Thank you for your fix. It makes sense. Unfortunately, we can not accept this Pull Request since it is [Prohibited Code Change](http://devdocs.magento.com/guides/v2.0/contributor-guide/backward-compatible-development/#cssless) from the Backward Compatibility point of view.

**Pull request closed without merging**
