### PR TITLE
Gif image throws error on frontend product page

### PR DESCRIPTION
**Pull request by bhoopatparmar**
### Preconditions
1. PHP 8.1
2. Magento 2.4.5-p1

### Description (*)
Gif image loading issue on the product page,  
imagecolorsforindex(): Argument #2 ($color) is out of range in /var/www/lib/Varien/Image/Adapter/Gd2.

### Steps to Reproduce (*)

1. Set the image below as a product image and save it.
test

2. Reindex the indexer and clear the cache
3. Open that particular product in frontend.

### Expected Result 
Product page must load properly

### Actual Result
```
ValueError: imagecolorsforindex(): Argument #2 ($color) is out of range in /var/www/public_html/vendor/magento/framework/Image/Adapter/Gd2.php:347
Stack trace:
#0 /var/www/public_html/vendor/magento/framework/Image/Adapter/Gd2.php(347): imagecolorsforindex(Object(GdImage), 255)
#1 /var/www/public_html/vendor/magento/framework/Image/Adapter/Gd2.php(288): Magento\Framework\Image\Adapter\Gd2->applyTransparency(Object(GdImage), 255)
#2 /var/www/public_html/vendor/magento/framework/Image/Adapter/Gd2.php(432): Magento\Framework\Image\Adapter\Gd2->fillBackgroundColor(Object(GdImage))
#3 /var/www/public_html/generated/code/Magento/Framework/Image/Adapter/Gd2/Interceptor.php(59): Magento\Framework\Image\Adapter\Gd2->resize(240, 300)
#4 /var/www/public_html/vendor/magento/framework/Image.php(115): Magento\Framework\Image\Adapter\Gd2\Interceptor->resize(240, 300)
```

### Solution 
When the product page loads some relevant gif image, it tries to resize it via Gd2 library of php with specific functionalities. It checks the transparency of the image and creates a new transparent background image according to the particular image if needed. In that, the color transparency index is returned by imagecolortransparent($imageResource) and it can be larger than the pallet size of the image in some cases.

The index of the transparency color is a property of the image. So it's possible that an image created with this index could be set outside the pallet size. 

The Gd2.php file located is at : `vendor/magento/framework/Image/Adapter`
**imagecolortransparent($imageResource)** should return -1 when the color transparency is greater than the pallet size of the image, which means that the image doesn't have any transparency
And when  it calls applyTransparency() function for gif image at line 341 with **$transparentIndex** got by **imagecolortransparent($imageResource)**, It checks the condition at line 346 where it checks
`if ($transparentIndex >= 0 && $transparentIndex <= imagecolorstotal($this->_imageHandler))` .

But the transparent color index returned by **imagecolortransparent()** must be less than the pallet size of the image for an appropriate result and it shouldn't be equal to or greater than the pallet size.
Therefore we need to change condition as : 
`if ($transparentIndex >= 0 && $transparentIndex < imagecolorstotal($this->_imageHandler))` 
And if the condition satisfies then only it can look to get the new identifier for transparent color.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mortenbirkelund** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Need to take care of the failed tests

**Comment by bhoopatparmar** [comment]
@sinhaparul I've deleted the previous fork repository by mistake, which closed this pull request. So, I've created a new pull request with the same details.  Can you please add a label to the new PR: [#37319](https://github.com/magento/magento2/pull/37319)

**Pull request closed without merging**
