### PR TITLE
Use inline elements for inline links

### PR DESCRIPTION
**Pull request by chicgeek**
The widgets for inserting product/category links into CMS blocks have a block or inline option. The inline version should use inline `span` elements instead of `div` elements.

This matches what is used for the category link inline template:
https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/view/frontend/templates/category/widget/link/link_inline.phtml

### CODE REVIEW

**Comment by magento-cicd** [comment]
We have automated a Magento Contributor License Agreement verifier for contributions sent to our GitHub projects.
Please see the CLA agreement in the Pull Request comments below.

**Comment by chicgeek** [comment]
This PR now has a massive merge commit to resync because it's been open for so long. Ping me if you would prefer a rebase.

**Comment by chicgeek** [comment]
@kandy What's the timeline on minor non-impactful changes such as this? There are many PRs with as minor or non-code changes that could possibly be fast tracked. Changes such as fixing typos in code comments.

Is this something I could help with?

**Comment by KrystynaKabannyk** [comment]
hello @chicgeek, thanks so much for your pull request, the proposed changes look good to us, and we plan to merge it in one of the nearest releases. However, we would highly appreciate if you update the code and cover it by automated tests (the checks circle has to be green), so we could merge it earlier.

**Comment by blongden** [comment]
Test is failing because of some unrelated reason `Magento\MemoryUsageTest::testAppReinitializationNoMemoryLeak`

**Comment by chicgeek** [comment]
Hi @KrystynaKabannyk. The test fails for an unrelated reason, as Ben mentions above.

I really don't see a useful way to write an automated test the change I made. I assume this is a bucket response to PRs with failing builds?

**Comment by vkorotun** [comment]
Internal ticket: MAGETWO-58371

**Comment by ihor-sviziev** [comment]
Looks like code was merged in https://github.com/magento/magento2/commit/2842e92f1540ace6a51e9582deb97112b68657dd

**Comment by Ctucker9233** [comment]
@vkorotun  @mmansoorebay Will MAGETWO-58371 be included in 2.1.3?

**Pull request merged**
