### PR TITLE
[MFTF] Updating with ClickPlaceOrderActionGroup

### LINKED ISSUE #31524: [Issue] [MFTF] Updating with ClickPlaceOrderActionGroup
This issue is automatically created based on existing pull request: magento/magento2#31449: [MFTF] Updating with ClickPlaceOrderActionGroup

---------
### Description (*)
Updating with ClickPlaceOrderActionGroup

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
Updating with ClickPlaceOrderActionGroup

### Resolved issues:
1. [x] resolves magento/magento2#31524: [MFTF] Updating with ClickPlaceOrderActionGroup

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8671](https://jira.corp.magento.com/browse/ENGCOM-8671) has been created to process this Pull Request

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Pull request merged**
