### PR TITLE
#21734 Error in JS validation rule

### PR DESCRIPTION
**Pull request by kisroman**
### Description (*)
Bug in "validate-per-page-value-list" validation.

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/21734

### Manual testing scenarios (*)
1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @kisroman. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hi @kisroman,
thank you for your contribution!

The only thing I have a concern about is that we also need to make sure there is no empty value.
However, according to current solution the empty value is condidered as valid.
Could you please fix it?

Thank you!

**Comment by kisroman** [comment]
Hi @dmytro-ch. I am not sured that this validation should return false if value is empty. For empty value we have other validation as "required". 
Also I found Github issue which confirms it https://github.com/magento/magento2/issues/16544. 
Thanks :)

**Comment by dmytro-ch** [comment]
@kisroman, thank you for the update.
It does make sense. 👍
In this case, we still need to make sure the `grid_per_page_values` and `list_per_page_values` system configs does not contain empty values.
So let's add the proper validation rules into `app/code/Magento/Catalog/etc/adminhtml/system.xml`.

Thank you!

**Comment by kisroman** [comment]
@dmytro-ch, agree. Added.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4546](https://jira.corp.magento.com/browse/ENGCOM-4546) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed 

**Result:**

after

**Pull request merged**
