### PR TITLE
PHP unit no expectation annotation

### PR DESCRIPTION
**Pull request by MathiasReker**
Usages of @expectedException* annotations MUST be replaced by ->setExpectedException* methods.
I can remove empty php doc in an other PR.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @MathiasReker. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by orlangur** [comment]
@MathiasReker please provide a source for such recommendation.

**Comment by MathiasReker** [comment]
Since PHPUnit32 it has been better practice. I don't have a link to docs.

**Comment by orlangur** [comment]
@MathiasReker I never heard of such recommendation, there were even some improvements in regards to exception annotation in PHPUnit5 or 6.

Unfortunately, without a proof link we cannot accept such contribution.

**Pull request closed without merging**
