### PR TITLE
32854: Upgraded moment.js to the latest version 2.29.1

### LINKED ISSUE #32854: Investigate upgrade to the latest moment.js
### Overview

For the moment.js library we need to identify the following additional details:

- If this library is used on Admin UI or Storefront Luma or both
- What exact functionality is using this particular library
- What is a preliminary scope of work to migrate to the new version.
- Is it possible to migrate without introducing BIC into Luma
- Level of the impact of updating dependency in terms of BIC

### Investigation Outcome
A complete report of affected areas, ways to migrate code, and level of BIC caused by migration.

### PR DESCRIPTION
**Pull request by anzin**
### Description (*)

I've upgraded version moment.js from 2.24.0 to 2.29.1

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32854: Investigate upgrade to the latest moment.js

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run Functional Tests EE

**Comment by anzin** [comment]
@magento run Functional Tests B2B

**Review by Den4ik — APPROVED** [review]
✅ Approved
Looks good for me. sha hash of updated file equal to hash for https://momentjs.com/downloads/moment.min.js

**Review by andrewbess — APPROVED** [review]

**Pull request merged**
