### PR TITLE
Code cleanup of module files

### PR DESCRIPTION
**Pull request by mage2pratik**
### Description

Just modify some code and make it cleaner more.

### Fixed Issues (if relevant)

1. magento/magento2#17337: Code cleanup of module files

### Manual testing scenarios

N/A

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by sidolov** [comment]
Hi @mage2pratik , please, take a look at failed tests

**Comment by orlangur** [comment]
@mage2pratik one more such PR is too much. In previous version I thought these are the only occurrences. Please provide an approach to do such transformation automatically as it does not make sense to review it manually.

**Comment by orlangur** [comment]
@mage2pratik please check my comment.

**Comment by orlangur** [comment]
@mage2pratik please provide an automated steps to apply such changes, unless this PR cannot be processed.

**Comment by sidolov** [comment]
Hi @mage2pratik , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
