### PR TITLE
[Forwardport] Replacing Usage of Deprecated Methods for Message Manager

### PR DESCRIPTION
**Pull request by gelanivishal**
### Original Pull Request
https://github.com/magento/magento2/pull/16924
https://github.com/magento/magento2/pull/16560

Replacing usage of deprecated methods for message manager.

### Description

Changes:

 - `addSuccess` -> `addSuccessMessage`;
 - `addError` -> `addErrorMessage`;
 - `addException` -> `addExceptionMessage`;
 - `addWarning` -> `addWarningMessage`;

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by sidolov** [comment]
@magentp-engcom-team combine 17141

**Comment by sidolov** [comment]
@magento-engcom-team combine 17141

**Comment by magento-engcom-team** [comment]
Hi @sidolov. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
@gelanivishal all pull requests have been successfully combined together: 
 - merged https://github.com/magento/magento2/pull/17141: [Forwardport] Admin user auth controller refactor

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Pull request merged**
