### PR TITLE
Turn on edit mode for product repository when adding children

### PR DESCRIPTION
**Pull request by pedrosousa13**
### Description (*)
This should fix the issue with the configurable products not having any options with Bulk and Async API. The product was being cached and its extension attributes were empty when trying to add children to a product via Bulk API.

### Fixed Issues (if relevant)
1. magento/magento2#20366: The parent product doesn't have configurable product options

### Manual testing scenarios (*)
1. Install Magento 2.3 with RabbitMQ
2. Add Sample data
3. Follow https://devdocs.magento.com/guides/v2.3/rest/tutorials/bulk-configurable-product/config-product-intro.html
4. If this fix is not there, when you do the step to add the product children, an error is produced saying that the product does not contain any configurable options.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @pedrosousa13. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21083) <br/>All committers have signed the CLA.

**Comment by pedrosousa13** [comment]
* @magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @pedrosousa13. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @pedrosousa13, here is your [Magento instance](https://i-21083-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21083-2-3-develop.instances.magento-community.engineering/admin](https://i-21083-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4188](https://jira.corp.magento.com/browse/ENGCOM-4188) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@pedrosousa13 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by pedrosousa13** [comment]
@VladimirZaets Is there anything else I need to do or is it out of my hands now?

**Comment by VladimirZaets** [comment]
Hi @pedrosousa13. Thanks for collaboration. We took in progress your PR. Our workflow a little bit difficult than merge PR directly here, on Github. Please wait and if we will need some additional steps from your side we will write. Thank you

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed 

**Before:**

before

**After:**

after

**Pull request merged**
