### PR TITLE
Fixed subscribe to newsletter if you already have an account issue #8952 -2.3 develop

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

Fixed subscribe to newsletter if you already have an account issue
### Fixed Issues (if relevant)

1. magento/magento2#8952: You can't subscribe to newsletter if you already have an account

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by ravi-chandra3197** [comment]
#18912 [Backport] Fixed subscribe to newsletter if you already have an account issue #18912

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3431](https://jira.corp.magento.com/browse/ENGCOM-3431) has been created to process this Pull Request

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3431](https://jira.corp.magento.com/browse/ENGCOM-3431) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
