### PR TITLE
Fixed #26792 category list API return some null values

### LINKED ISSUE #26792: category list API return some null values
Hello,
 when doing GET to /V1/categories?rootCategoryId=1 I've null fields in **is_active** (but the structure is correct)

```
{
  "id": 1,
  "parent_id": 0,
  "name": "Root Catalog",   
  "is_active": null,     #<---
  "position": 0,
  "level": 0,
  "product_count": 0,    
  "children_data": [
    {
      "id": 2,
      "parent_id": 1,
      "name": "Default Category",
      "is_active": true,
      "position": 1,
      "level": 1,
      "product_count": 1,
      "children_data": [
        {
          "id": 3,
          "parent_id": 2,
          "name": "Category",
          "is_active": true,
          "position": 1,
          "level": 2,
          "product_count": 2,
          "children_data": []
        }
      ]
    },
```
   
This problems happens only with search filter "rootCategoryId=1" that I use to get ALL the category trees. If I use "CategoryId=2" it works, But I need a way to get all category trees across all websites with one call. 

### Preconditions (*)
magento 2.3.2 and magento 2.3.3

### Steps to reproduce (*)
Simply make a GET to
https://<SHOP_HOSTNAME>/index.php/rest/V1/categories?rootCategoryId=1

### Expected result (*)
no null values

### Actual result (*)
The **is_active: null**
cat_response_body1

### PR DESCRIPTION
**Pull request by shikhamis11**
### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/152
https://github.com/magento/partners-magento2b2b/pull/55

Fixed #26792 category list API return some null values

Hello,
 when doing GET to /V1/categories?rootCategoryId=1 I've null fields in **is_active** (but the structure is correct)

```
{
  "id": 1,
  "parent_id": 0,
  "name": "Root Catalog",   
  "is_active": null,     #<---
  "position": 0,
  "level": 0,
  "product_count": 0,    
  "children_data": [
    {
      "id": 2,
      "parent_id": 1,
      "name": "Default Category",
      "is_active": true,
      "position": 1,
      "level": 1,
      "product_count": 1,
      "children_data": [
        {
          "id": 3,
          "parent_id": 2,
          "name": "Category",
          "is_active": true,
          "position": 1,
          "level": 2,
          "product_count": 2,
          "children_data": []
        }
      ]
    },
```
   
This problems happens only with search filter "rootCategoryId=1" that I use to get ALL the category trees. If I use "CategoryId=2" it works, But I need a way to get all category trees across all websites with one call. 

### Preconditions (*)
magento 2.3.2 and magento 2.3.3

### Steps to reproduce (*)
Simply make a GET to
https://<SHOP_HOSTNAME>/index.php/rest/V1/categories?rootCategoryId=1

### Expected result (*)
no null values

### Actual result (*)
The **is_active: null**
cat_response_body1
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by Stepa4man — CHANGES_REQUESTED** [review]
Hi @shikhamis11 
Thanks for your contribution

Please check the failed test.

Thanks

**Comment by shikhamis11** [comment]
@Stepa4man Please check I have fixed all integration test issues for Magento CE

**Comment by engcom-Golf** [comment]
@mageno run all tests

**Comment by engcom-Golf** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @shikhamis11,
Your fix will work for new installations, but existing installations will not get this fix.
Could you revert changes in the `InstallDefaultCategories.php` patch and create new data patch that will change "is active" attribute to root category?

**Comment by shikhamis11** [comment]
@ihor-sviziev thanks for the review I will update the changes

**Comment by ihor-sviziev** [comment]
@shikhamis11 I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
