### PR TITLE
small misspelling fixed

### PR DESCRIPTION
**Pull request by EmilyPepperman**
Small misspelling fixed... 
estiamtion changed to estimation

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=17469) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @EmilyPepperman. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by sidolov** [comment]
Hi @EmilyPepperman  , due to changes in [Magento Code Contributions Guide](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#rules) we can't accept such Pull Requests to 2.2 release line. All code cleanup like typos, spelling mistakes, removing unused code, etc should be delivered to 2.3 release line.
Thank you!

**Comment by EmilyPepperman** [comment]
Got it! Thank you. :-) @sidolov

**Pull request closed without merging**
