### PR TITLE
Add Magento\Framework\HTTP\ClientFactory to the public API

### PR DESCRIPTION
**Pull request by navarr**
I want to be able to grab a factory for HTTP ClientInterfaces, so please add ClientFactory to the API.

I first attempted to do this by grabbing a \Magento\Framework\HTTP\ClientInterfaceFactory, but there was no preference set for ClientInterface

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by mzeis** [comment]
Hi @navarr,

thanks for your contribution! I'll check with the core team whether we can add this class to the API.

**Comment by mzeis** [comment]
Hi @okorshenko,

please can you tell whether it's okay to add `@api` to this class (decision by an architect is required)?

Also, I guess we would introduce the new API in `2.3-develop` instead of `2.2-develop`?

Thanks!

**Comment by mzeis** [comment]
Hi @navarr, sorry for the slow response! We can add this class to the public API but we have to do this for `2.3-develop`. Would you like to do this?

**Comment by sidolov** [comment]
Hi @navarr , unfortunately, we can't accept this pull request because base repository was removed.
Please, create the new one if you wish to continue. 
Thank you for collaboration!

**Pull request closed without merging**
