### PR TITLE
[32033] Marked Framework Setup interfaces as API

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixes magento/magento2#32033

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32033

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Functional Tests B2B, Integration Tests, WebAPI Tests

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @Usik2203, please review and fix the Static Tests, by marking the classes used in `api` as api as well.

Thank you.

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Functional Tests EE

**Comment by eduard13** [comment]
@magento run Functional Tests B2B, WebAPI Tests

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8832](https://jira.corp.magento.com/browse/ENGCOM-8832) has been created to process this Pull Request

**Comment by gabrieldagama** [comment]
Closed in favour https://github.com/magento/magento2/pull/32733

**Pull request closed without merging**
