### PR TITLE
magento-issue-7852: Moved the review functionality from Magento_Custo…

### PR DESCRIPTION
**Pull request by ayangolenko**
…mer module to Magento_Review module for removing dependency of Customer module on Review module.

https://github.com/magento/magento2/issues/7852

### Description (*)
The block of the customer module which extended a block from review module was moved to the review module, also I moved the controller which call that block to the review module. All of these were did for removing the dependency of Customer module on the Review module.

### Questions or comments
I've removed the dependency of Customer module on Review module as it was required in the issue but that doesn't let to disable Magento_Review module by due to 2 others module have a dependency to Magento_Review module, it's Magento_Rerport and Magento_ReviewAnalytics. I think that we can disable Magento_Review with module together Magento_ReviewAnalytics module but the dependency of Magento_Rerport is another problem.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24758) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=24758) before we can accept your contribution.<br/>

**Comment by sidolov** [comment]
Hi @artyomyangolenko , please, sign CLA, otherwise, we can't process your pull request

**Comment by krzksz** [comment]
@magento run all tests

**Comment by krzksz** [comment]
Hi @artyomyangolenko, I am closing this PR now due to inactivity and CLA not being signed.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by drpayyne** [comment]
Hi @sidolov and @krzksz, may I submit the same PR on my behalf due to inactivity?

**Comment by krzksz** [comment]
Sure, go for it 👍

**Comment by drpayyne** [comment]
Hi @krzksz, please check https://github.com/magento/magento2/issues/7852#issuecomment-583008820. Thanks!

**Pull request closed without merging**
