### PR TITLE
Fix Arabic and Hebrew in invoices

### LINKED ISSUE #25769: Arabic invoice pdf issue Magento 2.3.0 showing as Arabic letters but not correct
### Preconditions (*)
Magento 2.3.0 & 2.3-develop
The store should be in Arabic

### Steps to reproduce (*)
1) Place an order in Arabic store 
2) Customer fill the address and name all in Arabic 
3) Login to the admin panel and open orders 
4) Create an invoice against the order 
5) Download the invoice pdf and compare the content in the admin side with the invoice pdf 

### Expected result (*)
same as content below 
eg: الإسم	ابو بدر المطيري 
image

### Actual result (*)
here it's showing in different data
eg : يريطملا ردب وبا 
image

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
I found fix that was reverted in https://github.com/magento/magento2/commit/1c0549eac90645e57bca159ec00f0b35703f1ce5 due to backward compatibility issues (from @lenaorobei). I just re-applied these changes again, extracted whole logic with working with [RTL  texts](https://en.wikipedia.org/wiki/Right-to-left) to the separate model, covered it with unit tests and used it during invoice generation, so now it should be fully backward compatible.

Also I found that that solution didn't worked fine with Hebrew, so I also fixed it.

Note: for preparing test data I used some sample data generation service.
### Fixed Issues (if relevant)

1. magento/magento2#25769

### Manual testing scenarios (*)
1. See magento/magento2#25769

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lbajsarowicz — APPROVED** [review]
Looks fine, nice catch :heavy_check_mark:

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7465](https://jira.corp.magento.com/browse/ENGCOM-7465) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was used phrase `الإسم ابو بدر المطيري` for all input fields
**Before:**
image
image

`الإسم ابو بدر المطيري` from admin side invoice **not equal** with `يريطملا ردب وبا مسإلا` from invoice pdf

**After:**
image
image

`الإسم ابو بدر المطيري` form admin side invoice is **equal** with `الإسم ابو بدر المطيري` from invoice pdf

**Comment by zezooo2** [comment]
@ihor-sviziev thank you i used your fix and it already make the text be from right to left but the words are separated ?!
like  أ ح م د
it must be أحمد
any help on that ? (magento 2.3.2)
thanx alot

**Comment by ihor-sviziev** [comment]
> @ihor-sviziev thank you i used your fix and it already make the text be from right to left but the words are separated ?!
> 
> like  أ ح م د
> 
> it must be أحمد
> 
> any help on that ? (magento 2.3.2)
> 
> thanx alot

As I said above - with the current library, we can't fix it. We need to use another library for that. So far, it's quite a significant effort to implement it.

**Comment by zezooo2** [comment]
@ihor-sviziev thanks alot i will try 👍

**Pull request merged**
