### PR TITLE
[MFTF] add Action Group for submit invoice

### PR DESCRIPTION
**Pull request by Usik2203**
This PR creates `AdminInvoiceClickSubmitActionGroup` for submit invoices

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Review by rogyar — APPROVED** [review]
The failing test is not related to the current change

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7807](https://jira.corp.magento.com/browse/ENGCOM-7807) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
Failed Functional Tests B2B, not related to changes in this Pull Request.

**Pull request merged**
