### PR TITLE
catch Throwable instead of Exception

### PR DESCRIPTION
**Pull request by rvitaliy**
### Description (*)
Provides possibility to catch `\Throwable` instead of `\Exception`.
This Interface is introduced in php 7.0
This change allow us to catch errors like `\Error`, `\TypeError`, etc...

### Related Pull Requests
none

### Fixed Issues
none

### Manual testing scenarios (*)

generate an exception `\Error`  in any point of related code and verify that catch is executed

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by orlangur — CHANGES_REQUESTED** [review]
Nice catch @rvitaliy!

Please enforce such change with a static test though.

**Comment by orlangur** [comment]
@rvitaliy, hm, and after reading https://stackoverflow.com/questions/2274102/difference-between-using-throwable-and-exception-in-a-try-catch I don't think it's a good idea to catch Throwable in any case. Please provide some reasoning.

**Comment by rvitaliy** [comment]
Yes, i agree, catch \Throwable instead of \Exception in any case is not a good idea. But in our case it is, at 99% of cases we try to catch something and log it as described on StackOverflow.
Probably is better to analize all this points of code to undestand if is better to catch \Throwable or \Exception.
Since it is very difficult to do this in a single task, I suggest to keep magento developers in mind to start using catch \Throwable instead of \Exception from now on and slowly migrate in a more targeted way.
Good luck!

**Comment by orlangur** [comment]
@rvitaliy yeah, totally makes sense, thank you!

Hope we already have them in main critical points, like "API call failed due to Fatal Error".

**Pull request closed without merging**
