### PR TITLE
Fixed style issue for select in admin grid

### LINKED ISSUE #35386: [Issue] Fixed style issue for select in admin grid
This issue is automatically created based on existing pull request: magento/magento2#35385: Fixed style issue for select in admin grid

---------

### Description (*)

**_Result Before Changes_**

https://user-images.githubusercontent.com/13517181/165555666-3f09aaf4-05bf-4617-9edb-6f151fca657e.mov

**_Result After Changes_**

https://user-images.githubusercontent.com/13517181/165555864-738818c7-a66a-4589-b555-609a56d3e50b.mov

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

**_Result Before Changes_**

https://user-images.githubusercontent.com/13517181/165555666-3f09aaf4-05bf-4617-9edb-6f151fca657e.mov

**_Result After Changes_**

https://user-images.githubusercontent.com/13517181/165555864-738818c7-a66a-4589-b555-609a56d3e50b.mov

### Resolved issues:
1. [x] resolves magento/magento2#35386: Fixed style issue for select in admin grid

### CODE REVIEW

**Comment by andrewbess** [comment]
@magento create issue

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Review by Den4ik — APPROVED** [review]
Hey @Usik2203 
Thanks for PR.
Failed Functional Tests are not related to the changes

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B,Functional Tests EE

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B,Functional Tests EE

**Comment by engcom-Lima** [comment]
@magento give me test instance

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
1. Install Magento of `2.4-Develop` with sample data.

**Manual testing scenario:**
1. Login as admin.
2. Go to Content >>Pages>>Select 2 per page using "Custom" .
3. Click on Select drop box of 2nd record in the grid and validate drop box options are visible .

**Before:** :heavy_multiplication_x: On clicking options were not visible.As shown in the below screenshot:
Screenshot from 2022-05-13 17-32-58

**After:** :heavy_check_mark: Options are now visible clearly.As shown below :
Screenshot from 2022-05-13 17-30-44

Additionally tested below scenarios:

1. Testing using others custom options.
2. Click on Edit and validated that navigated pages are appropriate.
3. Click on Delete and validated pages got deleted.
4. Clicked on View and validated page is getting displayed .

It is minor grid UI drop down box visibility fix and not required any additional test cases to be added as part of the regression cycle.

**Pull request merged**
