### PR TITLE
No update must be a boolean, int given for bin/magent sampledata:deploy|remove --no-update

### LINKED ISSUE #39344: bin/magento sampledata:deploy --no-update throws an exception
### Preconditions and environment

- Magento version 2.4.7-p3


### Steps to reproduce

- Install a clean version of Magento
- In the console try to run `bin/magento sampledata:deploy --no-update`


### Expected result

```
./composer.json has been updated                                                                                                                                                                                   
Sample data modules have been added via composer. Please run bin/magento setup:upgrade      
```

### Actual result


```
$ bin/magento sampledata:deploy --no-update
                                                                                                         
In PackageDiscoveryTrait.php line 90:                                                                                                                                                                              
                                                                                                                                                                                                                  
  [TypeError]                                                                                                                                                                                                     
  Composer\Command\RequireCommand::determineRequirements(): Argument #6 ($useBestVersionConstraint) must be of type bool, int given, called in /project/vendor/composer/composer/src/Composer/Command/RequireCom  
  mand.php on line 213                                                                                                                                                                                            
                                                                                                                                                                                                                  

Exception trace:
  at /project/vendor/composer/composer/src/Composer/Command/PackageDiscoveryTrait.php:90
 Composer\Command\RequireCommand->determineRequirements() at /project/vendor/composer/composer/src/Composer/Command/RequireCommand.php:213
 Composer\Command\RequireCommand->execute() at /project/vendor/symfony/console/Command/Command.php:326
 Symfony\Component\Console\Command\Command->run() at /project/vendor/symfony/console/Application.php:1078
 Symfony\Component\Console\Application->doRunCommand() at /project/vendor/symfony/console/Application.php:324
 Symfony\Component\Console\Application->doRun() at /project/vendor/composer/composer/src/Composer/Console/Application.php:394
 Composer\Console\Application->doRun() at /project/vendor/symfony/console/Application.php:175
 Symfony\Component\Console\Application->run() at /project/vendor/composer/composer/src/Composer/Console/Application.php:148
 Composer\Console\Application->run() at /project/vendor/magento/module-sample-data/Console/Command/SampleDataDeployCommand.php:106
 Magento\SampleData\Console\Command\SampleDataDeployCommand->execute() at /project/vendor/symfony/console/Command/Command.php:326
 Symfony\Component\Console\Command\Command->run() at /project/vendor/symfony/console/Application.php:1078
 Symfony\Component\Console\Application->doRunCommand() at /project/vendor/symfony/console/Application.php:324
 Symfony\Component\Console\Application->doRun() at /project/vendor/magento/framework/Console/Cli.php:118
 Magento\Framework\Console\Cli->doRun() at /project/vendor/symfony/console/Application.php:175
 Symfony\Component\Console\Application->run() at /project/bin/magento:23

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [-
-update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-
stable] [--prefer-lowest] [-m|--minimal-changes] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>.
..]                                                 

There is an error during sample data deployment. Composer file will be reverted.
```

### Additional information

`vendor/magento/module-sample-data/Console/Command/SampleDataDeployCommand.php:93`

```diff
-$commonArgs['--no-update'] =1;
+$commonArgs['--no-update'] = true;
```

### Release note

When using `--no-update` in the sampledata:deploy command an error was thrown because since newer PHP versions the argument must be a boolean, a int was given.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by JeroenBoersma**
### Description (*)
When adding or removing sample data you can tell the composer update command to not invoke the update command right away. Since newer versions type checking is set for this argument and it must be of type boolean instead of a integer.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#39344

### Manual testing scenarios (*)
1. Install a clean Magento 2 installation
2. Try to deploy sample data without directly updating `--no-update`
3. A error was thrown, not anymore

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by JeroenBoersma** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @JeroenBoersma,

Thanks for the collaboration!

The changes seems good to us but please fix the failed static test failures, the other failures seems flaky to me.

Thanks

**Comment by engcom-Dash** [comment]
> Hello @JeroenBoersma,
> 
> Thanks for the collaboration!
> 
> The changes seems good to us but please fix the failed static test failures, the other failures seems flaky to me.
> 
> Thanks

I have fixed the failed static tests. Moving it to "Pending Review".

cc: @JeroenBoersma

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Unit Tests

**Comment by engcom-Dash** [comment]
We got a green build, so I’m moving this to "Merge in Progress."
image

**Pull request merged**
