### PR TITLE
[Backport] Invoice grid shows wrong shipping & handling for partial items invoice. It shows order's shipping & handling instead if invoiced shipping& handling charge

### PR DESCRIPTION
**Pull request by gelanivishal**
### Original Pull Request
https://github.com/magento/magento2/pull/14795

### Preconditions

1. Magento Version : (2.1.6 | 2.2.0 | 2.2.2 | 2.2.3) (community-edition), (2.2.2 | 2.2.3) (enterprise-edition)
2. PHP : 7.0.24
3. MySQL : 5.7.21
4. Platform : MacOS High Sierra v10.13.4

### Fixed Issues

1. Invoice grid shows wrong shipping & handling for partial items invoice. It shows order's shipping & handling instead if invoiced shipping& handling charge

### Manual testing scenarios

1. Place order with multiple taxable items and shipping charge
2. Generate separate invoice for each items and shipping charge should be covered in first invoice. (In short generate multiple invoices for same order with different items)
3. Do check value of **Shipping & Handling** column value in Invoice grid.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by orlangur — CHANGES_REQUESTED** [review]
`Resolved conflicts` is not really meaningful commit message, especially if this is the only one commit in PR :) (I understand it was produced as a result of cherry-pick or merge with squash)

Please amend commit with some text like in https://github.com/magento/magento2/commits?author=ankurseepossible and do force push. Easiest way is to cherry=pick https://github.com/magento/magento2/commit/23f9209091f7db47f5bf05cb152124a3e6b0a4ae and https://github.com/magento/magento2/commit/1d988f8edae2fc37212801d4883c80e7699a751f separately.

**Comment by gelanivishal** [comment]
@orlangur I have updated commit message. Please check it https://github.com/magento/magento2/pull/16352/commits/346eed2ab0854d7279ba51836bf728e8d735e455

**Review by orlangur — APPROVED** [review]
@gelanivishal great job on rewriting branch history, thanks!

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-2136](https://jira.corp.magento.com/browse/ENGCOM-2136) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your contribution. 
The changes from your Pull Request should be available with the upcoming 2.1.15 release. 
Please check the release notes for final confirmation.

**Pull request merged**
