### PR TITLE
Fix Issue #19805 - Sales order Address Information edit form layout design improvement.

### PR DESCRIPTION
**Pull request by abrarpathan19**
### Description (*)

Magento 2.3-develop
 Sales order Address Information edit form layout design improvement.
### Fixed Issues (if relevant)

1.magento/magento2#19805:  Sales order Address Information edit form layout design improvement.

### Manual testing scenarios (*)

1.Magento admin -> Sales ->Invoices ->View any order -> Under Address Information tab -> Billing Address/Shipping Address click on Edit to open form layout design

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @abrarpathan19. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [new Magento instance](https://pr-19807.instances.magento-community.engineering).
Admin access: [https://pr-19807.instances.magento-community.engineering/admin](https://pr-19807.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sivaschenko** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [Magento instance](https://i-19807-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19807-2-3-develop.instances.magento-community.engineering/admin](https://i-19807-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sivaschenko** [comment]
Hi @abrarpathan19 thanks for your contribution! Please move the styles to Magento_Sales module of backend theme. Also, please use variables instead of hardcoded values whenever possible.

**Comment by abrarpathan19** [comment]
@sivaschenko 
Hello, thanks for the suggestion,
I have moved the styles to Magento_Sales module of backend theme,
Please review.

**Comment by sivaschenko** [comment]
Hi @abrarpathan19 thanks for updates! can you please update the branch and resolve conflicts?

**Comment by sivaschenko** [comment]
Hi @abrarpathan19 thanks for the update, the form styles update are specific to order address only, so I believe the CSS selectors changed should be specific to order address form, these changes should be done in Magento_Sales module.

**Comment by abrarpathan19** [comment]
Hello @sivaschenko 
I have push updated the changes, Kindly review my changes and let me know any suggestion regarding this

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @abrarpathan19 , thanks for the update. 

Considering that the fix is for specific sales form - the fix should be located in Magento_Sales module. 

Also, considering that the goal is to change the appearance of the form to be consistent with other forms in admin panel.

I don't think any less should be added to codebase (all the required styles are already there). In my opinion, to fix the form either from the HTML should be changed (to match selectors) or some Magento_Sales styles removed, or both.

No changes should be done in app/design/adminhtml/Magento/backend/web.

**Comment by abrarpathan19** [comment]
@sivaschenko I have added my code in " app/design/adminhtml/Magento/backend/Magento_Sales/web/css/source/module/_order.less" please review

**Comment by abrarpathan19** [comment]
Hello @sivaschenko 
Removed file as per instructions, please review

**Comment by abrarpathan19** [comment]
@sivaschenko can you please update?

**Comment by abrarpathan19** [comment]
@sivaschenko can you please update?

**Comment by sivaschenko** [comment]
@abrarpathan19 there are no updates from my side. The pull request will not be accepted until it contain Magento_Sales changes only and the fix is specific to Sales order Address Information edit form.

**Comment by abrarpathan19** [comment]
@magento-engcom-team 
I have fixed that issue with CSS code but reviewer wants to fix it without CSS code so I am going to close this issue.

**Pull request closed without merging**
