### PR TITLE
fix: do not forcefully set area in template if it is already set, fixes #14968, fixes #13530

### LINKED ISSUE #13530: "Template file 'header.html' is not found" error while trying to save Design Configuration.
### Preconditions
1. Magento `2.2-develop` branch, current commit: f18377b9e59
2. PHP 7.0.27

### Steps to reproduce
1. Setup a clean Magento from the `2.2-develop` using commit f18377b9e59
2. Go into the backend to Content => Design => Configuration
3. Open either the Global or Website scoped configuration
4. Click 'Save and Continue'

### Expected result
1. Configuration should be saved without errors

### Actual result
1. We are getting the error: `Something went wrong while saving this configuration: Template file 'header.html' is not found.`

### Discussion
Curiously enough, this only happens on the Global and Website scope, when trying the same on the Storeview scope, it works and we don't see this error.

### LINKED ISSUE #14968: Can't change the applied theme in 2.2.4
### Preconditions
1. Magento 2.2.4
2. PHP 7.1

### Steps to reproduce
1. Go to Content > Design > Configuration
2. Edit the Store View and try to change the "Applied theme" to another
3. Save Configuration

### Expected result
1. Change the theme

### Actual result
1. Appears the error: "Something went wrong while saving this configuration: Area is already set"

### PR DESCRIPTION
**Pull request by mageprince**
### Original Pull Request
[#15137](https://github.com/magento/magento2/pull/15137)
### Description
This reverts the addition of the enforced area in https://github.com/magento/magento2/commit/d3aef7c3eef658baa00d3233d0352b5fed0f1cbe which caused https://github.com/magento/magento2/issues/14968 and introduced this regression

### Fixed Issues (if relevant)

1. magento/magento2#14968: Can't change the applied theme in 2.2.4
2. magento/magento2#13530: "Template file 'header.html' is not found" error while trying to save Design Configuration.

### Manual testing scenarios

1. comment / disable line 117 in app/code/Magento/Theme/Model/Design/Config/Validator.php
2. change theme in store view

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mageprince. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by DanielRuf** [comment]
Sorry but this is already fixed / will be fixed in 2.3, there was a forward port. And there is no actual revert.

**Comment by DanielRuf** [comment]
Also this is not the correct change and no real forward port.

**Comment by DanielRuf** [comment]
Did you test if this is needed in 2.3? It does not seem so as there is no exception thrown.

**Comment by DanielRuf** [comment]
@magento-engcom-team give me develop-2.3 instance

**Comment by DanielRuf** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf, here is your [Magento instance](https://i-16661-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-16661-2-3-develop.engcom.dev.magento.com/admin](https://i-16661-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by DanielRuf** [comment]
Not reproducible in 2.3.

**Pull request closed without merging**
