### PR TITLE
Fix code style issues with php-cs-fixer

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description
Fixed code style issues with automatic tool.
Executed following commands:
```bash
./vendor/bin/php-cs-fixer -vvv fix ./app/code/
./vendor/bin/php-cs-fixer -vvv fix ./lib/internal/
```

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios
N/A

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Tests are failing, will update code

**Comment by ihor-sviziev** [comment]
After automatic fixes I also applied manual fixes because there were a lot of issues with "too long line" issues. Another issue I faced - phpmd static test runs only for changed files, so some files appeared because they hadn't suppression.

Right now if we're running php-cs-fixer for app/code and lib/internal - we have broken static tests for 9 lines, these files were fixed manually:
```
magento2/app/code/Magento/Bundle/Ui/DataProvider/Product/Form/Modifier/BundlePanel.php
magento2/app/code/Magento/Catalog/Test/Unit/Block/Adminhtml/Product/Edit/Button/AddAttributeTest.php
magento2/app/code/Magento/Catalog/Ui/DataProvider/Product/Form/Modifier/Categories.php
magento2/app/code/Magento/ConfigurableProduct/Test/Unit/Ui/DataProvider/Product/Form/Modifier/ConfigurablePriceTest.php
magento2/app/code/Magento/Paypal/Test/Unit/Model/Payflow/Service/Response/Handler/FraudHandlerTest.php
magento2/app/code/Magento/Paypal/Test/Unit/Model/CartTest.php
magento2/app/code/Magento/Weee/Test/Unit/Model/Total/Quote/WeeeTaxTest.php
magento2/lib/internal/Magento/Framework/Code/Test/Unit/_files/app/code/Magento/SomeModule/Model/SevenInterface.php
magento2/lib/internal/Magento/Framework/Code/Test/Unit/Generator/InterfaceGeneratorTest.php```

**Comment by ishakhsuvarov** [comment]
@ihor-sviziev Looks like it is not possible to easily refactor  `Magento/Ui/Component/Listing/Columns/Column`. Warning may be suppressed.

**Comment by orlangur** [comment]
One more time :D It will be pretty strange if this PR will be merged "as is" as it does not differ from other attempts.

- Does not make sense without `codingStandardsIgnoreFile` removal in `2.2-develop`
- Static test enforcing no `php-cs-fixer` violations shall be implemented as well

After branch is ready and green, please rewrite commits history in the way similar to https://github.com/magento/magento2/pull/9367 - manual changes which do not make sense in separate commit should be squashed.

Good luck!

**Comment by ishakhsuvarov** [comment]
@orlangur It is still a challenge, to process this kind of PR, same as all previous attempts :)

**Comment by ihor-sviziev** [comment]
As we discussed with @ishakhsuvarov in slack - these changes couldn't be added to next 2.2 patch release because of huge list of changes, so I will prepare these changes to 2.3-develop branch

**Comment by orlangur** [comment]
@ihor-sviziev there are no coding style issues in `2.3-develop` branch actually after a contribution by @sidolov :)

And if we just apply `php-cs-fixer` all over the codebase, besides test which would enforce it I believe it would be good to revise set of rules in `.php_cs` (expand to teh max I mean).

**Comment by ihor-sviziev** [comment]
Let's close this PR. I will prepare new PR once I'll have time for that to 2.3-develop branch

**Pull request closed without merging**
