### PR TITLE
Fixed Search Query Length Issue #17711 (magento 2.2.x)

### PR DESCRIPTION
**Pull request by ansari-ziyaurrahman**
Search Query Length Issue #17711 (magento 2.2.x)

### Description (*)
Fixed Search Query Length Issue #17711 (magento 2.2.x)

### Fixed Issues (if relevant)
1. magento/magento2#17711: Search Query Length Issue #17711

### Manual testing scenarios (*)

1. check with different serch keyword length

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19818) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
@ansari-krish as this is fixed in 2.3, please cherry-pick corresponding commits instead of a new fix.

**Comment by orlangur** [comment]
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

**Pull request closed without merging**
