### PR TITLE
[Backport][TASK] Changed the Customer Group Form to a Ui Component

### PR DESCRIPTION
**Pull request by lewisvoncken**
Original pull request: https://github.com/magento/magento2/pull/18516

### Description

This PR refactors the customer group form to use UI components.

### Manual testing scenarios

Before changes:
image

After changes:
image

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### Original PR 
https://github.com/magento/magento2/pull/18516

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18517) <br/>All committers have signed the CLA.

**Comment by lewisvoncken** [comment]
@sivaschenko This PR has been updated according to #18516

**Comment by sivaschenko** [comment]
Hi @lewisvoncken , thanks, we'll process this pull request when the orignal https://github.com/magento/magento2/pull/18516 will be merged. "on hold" until that time.

**Comment by sivaschenko** [comment]
Closing as original PR was closed

**Pull request closed without merging**
