### PR TITLE
Include 'name.xsd' in 'constraint.xsd'

### LINKED ISSUE #29586: [Issue] Include 'name.xsd' in 'constraint.xsd'
This issue is automatically created based on existing pull request: magento/magento2#28169: Include 'name.xsd' in 'constraint.xsd'

---------
```
    <xs:attributeGroup name="baseConstraint">
        ...
        <xs:attribute name="referenceId" type="referenceIdType" use="required" />
    </xs:attributeGroup>
```

`referenceIdType` is declared in `name.xsd` but `name.xsd` is not included. IDEA warns about it:
image

### PR DESCRIPTION
**Pull request by flancer64**
```
    <xs:attributeGroup name="baseConstraint">
        ...
        <xs:attribute name="referenceId" type="referenceIdType" use="required" />
    </xs:attributeGroup>
```

`referenceIdType` is declared in `name.xsd` but `name.xsd` is not included. IDEA warns about it:
image

### Resolved issues:
1. [x] resolves magento/magento2#29586: Include 'name.xsd' in 'constraint.xsd'

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
@magento run all tests

**Review by lenaorobei — DISMISSED** [review]

**Review by lenaorobei — COMMENTED** [review]
Could you please add more details that stay behind this change? And specifically the use case when this additional validation is needed.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Moving this PR to corresponding status as requested in https://github.com/magento/magento2/pull/28169#pullrequestreview-489829383

**Comment by sidolov** [comment]
@flancer64  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
