### PR TITLE
Changed invoice cancel condition

### PR DESCRIPTION
**Pull request by ghost**
### Description
Fixed problem: can't cancelled invoice if invoice state == STATE_PAID

### Fixed Issues
1. magento/magento2#18509: Can't cancelled invoice if invoice state == STATE_PAID

### Manual testing scenarios
1. Load a invoice programmatically where state == STATE_PAID
2. Call $invoice->cancel()

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19433) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @SikailoISM. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by VladimirZaets** [comment]
Hi @SikailoISM, please, sign CLA, otherwise, we can't process your pull request

**Comment by orlangur** [comment]
@VladimirZaets are you sure paid invoice is supposed to be cancellable?

**Comment by VladimirZaets** [comment]
@SikailoISM  As I see the button to cancel invoice is also available only in the case when status is open
@orlangur I asked our product owner about this case and I wait for the answer.

**Comment by VladimirZaets** [comment]
Hi @SikailoISM, thanks for collaboration. After discussion with our product owner, we decided that paid invoice can't be cancellable. According to it, the issue is invalid and functionality works correctly.

**Pull request closed without merging**
