### PR TITLE
Improve Interceptor generator

### LINKED ISSUE #28383: [Issue] Improve Interceptor generator
This issue is automatically created based on existing pull request: magento/magento2#27902: Improve Interceptor generator

---------
### Description (*)
1. Removed `} else {` from Interceptors
2. Replaced foreach with array_map

#### Performance difference
Running `setup:di:compile` before and after my changes compared.
image
**Means**: No performance degradation.

### Preconditions (*)

N/A

### Steps to reproduce (*)
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
1. Removed `} else {` from Interceptors
2. Replaced foreach with array_map

#### Performance difference
Running `setup:di:compile` before and after my changes compared.
image
**Means**: No performance degradation.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28383: Improve Interceptor generator

### CODE REVIEW

**Review by dmytro-ch — COMMENTED** [review]
Good job @lbajsarowicz 👍 
I briefly checked the results. It looks good to me.

**Review by dmytro-ch — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7483](https://jira.corp.magento.com/browse/ENGCOM-7483) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked `setup:di:compile` runs with custom modules as before without errors
Was checked `setup:di:compile` runs without custom modules as before without errors

**Review by orlangur — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-7483](https://jira.corp.magento.com/browse/ENGCOM-7483) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
**Notice:** No new changes since last testing

**Review by slavvka — CHANGES_REQUESTED** [review]
@lbajsarowicz please resolve the conflicts and re-run the tests after the upgrade to PHP 7.4

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-7483](https://jira.corp.magento.com/browse/ENGCOM-7483) has been created to process this Pull Request

**Review by orlangur — CHANGES_REQUESTED** [review]
@lbajsarowicz one thing, could you please squash changes into a single commit so that we have perfectly clean history 😉

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@ihor-sviziev That was actually my fault with... Unit Test :facepalm:

**Review by slavvka — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @slavvka, thank you for the review.
[ENGCOM-7483](https://jira.corp.magento.com/browse/ENGCOM-7483) has been created to process this Pull Request

**Comment by VladimirZaets** [comment]
@magento create issue

**Comment by VladimirZaets** [comment]
@magento run all tests

**Review by orlangur — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

Checked `php bin/magento setup:di:compile` run with and without custom modules

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Pull request merged**
