### PR TITLE
[32015] Marked Catalog*, Checkout, Cms, ConfigurableProduct interfaces as API 

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixes https://github.com/magento/magento2/issues/32015
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/32015

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Review by coderimus — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @coderimus, thank you for the review.
[ENGCOM-8766](https://jira.corp.magento.com/browse/ENGCOM-8766) has been created to process this Pull Request
:eight_spoked_asterisk: @coderimus, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by coderimus** [comment]
Hello @Usik2203 
Please, check static tests: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/32175/697155635c0dc2a76ad5be6e404e6032/Statics/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

For referenced errors where you will see `references following non-public types:` please, add @api notation. For example, you will see this error:

_Public type 'Magento\CatalogGraphQl\DataProvider\Product\LayeredNavigation\LayerBuilderInterface' references following non-public types:
Magento\Framework\Api\Search\AggregationInterface_

It means that the Magento\Framework\Api\Search\AggregationInterface should also be @api along with the LayerBuilderInterface

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
Closed in favour of https://github.com/magento/magento2/pull/32725

**Pull request closed without merging**
