### PR TITLE
Don't skip row on import if image not available.

### PR DESCRIPTION
**Pull request by Nazar65**
### Description (*)
In this commit d4d34ff830c6d65f8803536f950e3edd51ed36bf was added feature to skip rows on this condition (if empty UrlKey or if urlKey has duplicate, if attribute set is not valid , or if sku is empty) but we don't need to skip row if image was not available.

### Fixed Issues (if relevant)

1. magento/magento2#22355: Issue title

### Manual testing scenarios (*)
`Csv file to upload product, with column base_image and his value This image have to be not exist in folder`

1. Go to admin (System - Import - Products)
2. Upload csv
3. Check data
4. Import

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by orlangur — CHANGES_REQUESTED** [review]
@Nazar65 cover with test, please.

**Comment by Nazar65** [comment]
@orlangur ok

**Comment by Nazar65** [comment]
@orlangur done :heavy_check_mark:

**Review by orlangur — APPROVED** [review]
@Nazar65 perfect! 👍

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4772](https://jira.corp.magento.com/browse/ENGCOM-4772) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Comment by p-bystritsky** [comment]
@Nazar65 please fix failing integration tests.

**Pull request merged**
