### PR TITLE
Correct spelling

### PR DESCRIPTION
**Pull request by hugovk**
### Description

Correct spelling mistakes.

### Manual testing scenarios

1. Check tests pass with no regressions

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [n/a] All new or changed code is covered with unit/integration tests (if applicable)
 - [Pending] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by miguelbalparda** [comment]
Hi @hugovk! Can you please check the failing tests? Thank you!

**Comment by hugovk** [comment]
@miguelbalparda Will do. That's strange they didn't fail on my fork:

https://travis-ci.org/hugovk/magento2/builds/438317027

There's probably also some bug in the build scripts which meant it didn't fail when it should, compare:

https://travis-ci.org/magento/magento2/jobs/438331102#L948
https://travis-ci.org/hugovk/magento2/jobs/438317030#L938

**Comment by orlangur** [comment]
@hugovk, "Fix Code Sniffer using PHPCBF" - please avoid such changes or at least don't use rules not used in Magento, like PHPDoc alignment.

**Comment by hugovk** [comment]
Closing this, I didn't get time to tidy it up and it's since got to merge conflict hell, but at least some of it was merged in another PR.

**Pull request closed without merging**
