### PR TITLE
Move block head.additional to layout scope of Magento_Theme module

### LINKED ISSUE #32579: [Issue] Move block head.additional to layout scope of Magento_Theme module
This issue is automatically created based on existing pull request: magento/magento2#32576: Move block head.additional to layout scope of Magento_Theme module

---------

### Description (*)

Previously this block belong from module theme but defined in module Catalog. We should move it to place it's should stay

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Previously this block belong from module theme but defined in module Catalog. We should move it to place it's should stay

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32579: Move block head.additional to layout scope of Magento_Theme module

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@mrtuvn good catch!
@magento create issue
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing functional tests looks not related to changes from this PR. SVC failure looks also as false-positive.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8963](https://jira.corp.magento.com/browse/ENGCOM-8963) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Comment by Karlasa** [comment]
@magento give me 2.4-develop instance

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run Semantic Version Checker

**Comment by mrtuvn** [comment]
How to pass sematic version checker ? In specific case i think we safe for approve this change

**Comment by mrtuvn** [comment]
cc: @gabrieldagama

**Comment by mrtuvn** [comment]
Not allow remove block is too stricted check from automation tests

**Comment by mrtuvn** [comment]
@magento run Semantic Version Checker

**Comment by mrtuvn** [comment]
This one can be merge quickly. In my opinion it's not impact to other place
CC: @sidolov

**Comment by engcom-November** [comment]
:heavy_check_mark: QA Passed 
**Preconditions:** - Install fresh Magento **2.4-develop** and **PHP 8.2** 
**Manual testing scenario:** 
Applied PR changes in local Magento 2.4-develop instance and verified Front end operations:
Changed Magento Luma and Blank themes and verified Front end - PASS
Created sub-category, products and placed order from front-end - PASS
Changed Design - layout for products and verified on Store front - PASS
Builds are failed. Hence, moving this PR to Extended Testing.

**Comment by engcom-Lima** [comment]
Hi @mrtuvn ,

Thanks for your contribution and collaboration.

Can you please provide us with information about the steps to reproduce the issue along with screenshots?

Thanks

**Comment by mrtuvn** [comment]
actually this one clear obvious to merge without worry about broken. Same code and nothing changes after merge. Just inmy opinion for manage code tindy, consistency accross codebase

**Comment by engcom-Lima** [comment]
@magento run all tests

**Pull request closed without merging**
