### PR TITLE
Removed CliIndexerReindexActionGroup action group usage for CatalogRule module

### LINKED ISSUE #31575: [Issue] Removed CliIndexerReindexActionGroup action group usage for CatalogRule module
This issue is automatically created based on existing pull request: magento/magento2#31564: Removed CliIndexerReindexActionGroup action group usage for CatalogRule module

---------
### Description
Remove CliIndexerReindexActionGroup action group usage or change value for it from tests to improve execution time for the CatalogRule, Downloadable and Indexer modules.

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Remove CliIndexerReindexActionGroup action group usage or change value for it from tests to improve execution time for the CatalogRule, Downloadable and Indexer modules.

### Resolved issues:
1. [x] resolves magento/magento2#31575: Removed CliIndexerReindexActionGroup action group usage for CatalogRule module

### CODE REVIEW

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Semantic Version Checker

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE

**Comment by sidolov** [comment]
@magento create issue

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8608](https://jira.corp.magento.com/browse/ENGCOM-8608) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** Functional Tests CE is failed

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE

**Pull request merged**
