### PR TITLE
dev/tests/acceptance/pre-install.php refactoring.

### PR DESCRIPTION
**Pull request by likemusic**
### Description
 - Move classes to `pre-install' directory.
 - Inject `CliColors` class from `PreInstallCheck` constructor.
 - Move all code from constructor in `PreInstallCheck` class to new public method `run()`.
 - Made all methods `private` (excepts public `run()`).

### Fixed Issues (if relevant)
No

### Manual testing scenarios
No

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @likemusic. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by orlangur** [comment]
@okolesnyk could you please look into this?

**Comment by slavvka** [comment]
@okolesnyk Does you comment mean that this PR shouldn't be accepted and therefore should closed?

**Comment by sidolov** [comment]
Hi @likemusic , I'm closing this PR as not relevant according to the comment from @okolesnyk, `dev/tests/acceptance/pre-install.php` has been removed on the 2.2-develop branch

**Pull request closed without merging**
