### PR TITLE
"Scheduled Import Settings" should hide fields when "Enabled" is "No" issue25101

### LINKED ISSUE #25101: "Scheduled Import Settings" should hide fields when "Enabled" is "No"
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Store->Configuration
3. General-> Currency Setup
4. "Enabled" is "No"

### Expected result (*)

1. Hide the fields

### Actual result (*)

1. 
image

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#25101: "Scheduled Import Settings" should hide fields when "Enabled" is "No"

### Fixed Issues (if relevant)

1. magento/magento2#25101: "Scheduled Import Settings" should hide fields when "Enabled" is "No"

### Manual testing scenarios (*)

1. Go to backend
2. Store->Configuration
3. General-> Currency Setup
4. "Enabled" is "No"

#### Expected result 

1. Hide the fields

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by Stepa4man — APPROVED** [review]
Hi @edenduong 
Thanks for your contribution

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, thank you for the review.
[ENGCOM-6116](https://jira.corp.magento.com/browse/ENGCOM-6116) has been created to process this Pull Request
:eight_spoked_asterisk: @Stepa4man, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by VladimirZaets** [comment]
Covered by automated tests in PR https://github.com/magento/magento2/pull/25756

**Pull request merged**
