### PR TITLE
Fixed error DOT field with Portugal locale

### LINKED ISSUE #34130: Error DOB field with Locale PT
### Preconditions (*)

1. Fresh Magento 2.4.3
2. Set store-view locale to Portuguese(Portugal)

### Steps to reproduce (*)
Admin - Stores - Configuration - General - Locale Options - Set Locale to Portuguese(Portugal) and Save
Reindex and clear cache
Fornt-end - Create Account
Add DOB in customer create
GO to customer/account/create/

Expected result (*)

magento-DOB

Actual result (*)

**The actual page:**

Magento-error

**System.log Error:**

`main.CRITICAL: TypeError: Argument 1 passed to iterator_to_array() must implement interface Traversable, null given in /var/www/html/magento2/vendor/magento/module-customer/Block/Widget/Dob.php:425
Stack trace:
#0 /var/www/html/magento2/vendor/magento/module-customer/Block/Widget/Dob.php(425): iterator_to_array()
#1 /var/www/html/magento2/vendor/magento/module-customer/view/frontend/templates/widget/dob.phtml(27): Magento\Customer\Block\Widget\Dob->getTranslatedCalendarConfigJson()
#2 /var/www/html/magento2/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/html/m...')
#3 /var/www/html/magento2/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render()
#4 /var/www/html/magento2/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView()
#5 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1114): Magento\Framework\View\Element\Template->_toHtml()
#6 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1118): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#7 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(678): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#8 /var/www/html/magento2/vendor/magento/module-customer/view/frontend/templates/form/register.phtml(58): Magento\Framework\View\Element\AbstractBlock->toHtml()
#9 /var/www/html/magento2/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/html/m...')
#10 /var/www/html/magento2/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render()
#11 /var/www/html/magento2/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView()
#12 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1114): Magento\Framework\View\Element\Template->_toHtml()
#13 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1118): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#14 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(678): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#15 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#16 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#17 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#18 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#19 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#20 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#21 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#22 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#23 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#24 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#25 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#26 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#27 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#28 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#29 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#30 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#31 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#32 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#33 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#34 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#35 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#36 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout->renderElement()
#37 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#38 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#39 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#40 /var/www/html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#41 /var/www/html/magento2/vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#42 /var/www/html/magento2/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#43 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult()
#44 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent()
#45 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}()
#46 /var/www/html/magento2/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(23): Magento\Framework\View\Result\Page\Interceptor->___callPlugins()
#47 /var/www/html/magento2/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult()
#48 /var/www/html/magento2/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#49 /var/www/html/magento2/pub/index.php(29): Magento\Framework\App\Bootstrap->run()`

---
- [] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

### PR DESCRIPTION
**Pull request by AZiniukhin**
### Description (*)

When investigating this error, it was found that it occurs due to the absence of a "short" designation of days (`do, sg, te, qu, qi, sx, sb`) in the Potrugalia locale called in file `app/code/Magento/Customer/Block/Widget/Dob.php` 
`'dayNamesMin' => array_values(iterator_to_array($daysData['format']['short']))`.
This error is formed at the PHP level when an object is create "`new \ResourceBundle($locale, $path)`" called in file `lib/internal/Magento/Framework/Locale/Bundle/DataBundle.php` in "`createResourceBundle`" method that automatically returns this value without a "short" version of days.
Due to the impossibility of believing in the work of PHP, in the absence of a "short" version of the days of the week, I return them to a longer version (`dom, seg, ter, qua, qui, sex, sáb`).

### Fixed Issues (if relevant)

1. Fixes magento/magento2#34130

### Manual testing scenarios (*)

1. Admin - Stores - Configuration - General - Locale Options - Set Locale to Portuguese(Portugal) and Save
Screenshot 2021-09-23 at 12 01 01
2. Admin - Stores - Configuration - Customer - Customer Configuration - Name and Address Options - Set Show Date of Birth in Optional or Required and Save
Screenshot 2021-09-23 at 12 01 25
3. Reindex and Clear Cache
4. Front-end - Create Account
5. Add DOB in customer create
Screenshot 2021-09-23 at 12 01 50

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by BarnyShergold** [comment]
@magento run all tests

**Comment by AZiniukhin** [comment]
@magento run functional tests

**Comment by AZiniukhin** [comment]
@magento run functional tests

**Comment by BarnyShergold** [comment]
@magento run functional tests

**Review by sidolov — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests CE

**Comment by engcom-Alfa** [comment]
@magento run Static Tests

**Review by BarnyShergold — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
@magento run Static Tests

**Comment by engcom-Alfa** [comment]
@magento run Static Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Static Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE,Functional Tests CE

**Comment by engcom-Charlie** [comment]
I have merged the 2.4-develop branch in to this PR branch and fixed the failed static test case.

I have also checked that the few Functional test cases which are getting failed are not part of this PR and as also not affected because of the PR changes so moving it to Merge in Progress.

Thank you!

**Pull request merged**
