### PR TITLE
WIP: Upgrade PHPUnit

### PR DESCRIPTION
**Pull request by kassner**
**Work in progress**

### Description

Given Magento 2.3 supports only PHP 7.1+, we can upgrade PHPUnit to a supported version. This PR is an attempt to gather what is needed for this upgrade to be successful.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by orlangur — CHANGES_REQUESTED** [review]
@kassner I believe this will be done by core team at appropriate moment and cannot be done via GitHub due to lack of b2b/ee code access.

@buskamuza what do you think?

**Comment by buskamuza** [comment]
Actually, based on PHPUnit changelog, I don't think this upgrade impacts tests themselves. So the important part is fixing the framework (listeners) as it's done in this PR.
But core team (or somebody with access to ee/b2b code) is still needed to verify that no tests are broken indeed.

**Comment by sivaschenko** [comment]
Thanks for the nice initiative @kassner !

I think there might be a problem with https://github.com/magento/mtf as `phpunit-selenium 4.1` (current dependency) does not support `PHPUnit 7`. So we might need to update MTF first.

@okolesnyk what do you think?

**Comment by orlangur** [comment]
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

**Pull request closed without merging**
