### PR TITLE
Add close tag for some void elements

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Cleanup markup with self close tags for a bunch (input img br) tags

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Integration Tests, Functional Tests EE, Functional Tests B2B

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by sivaschenko** [comment]
Functional test failures are flaky and are not related to the code changes.

This contribution is beneficial for the jQuery upgrade to 3.6.0 as the new jQuery version requires correctly closing of self-closing tags and non-self closing tags

**Review by sivaschenko — APPROVED** [review]

**Pull request merged**
