### PR TITLE
[MFTF] Adding AssertAdminProductIsAssignedToCategoryActionGroup

### LINKED ISSUE #31250: [Issue] [MFTF] Adding AssertAdminProductIsAssignedToCategoryActionGroup
This issue is automatically created based on existing pull request: magento/magento2#31241: [MFTF] Adding AssertAdminProductIsAssignedToCategoryActionGroup

---------
### Description (*)
Adding AssertAdminProductIsAssignedToCategoryActionGroup

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
Adding AssertAdminProductIsAssignedToCategoryActionGroup

### Resolved issues:
1. [x] resolves magento/magento2#31250: [MFTF] Adding AssertAdminProductIsAssignedToCategoryActionGroup

### CODE REVIEW

**Comment by AnnaAPak** [comment]
magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Comment by rogyar** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by rogyar — APPROVED** [review]
We have the same set of failing functional tests for other PRs.

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Pull request merged**
