### PR TITLE
[MFTF] add new AdminOpenWebConfigurationPageActionGroup

### LINKED ISSUE #29846: [Issue] [MFTF] add new AdminOpenWebConfigurationPageActionGroup
This issue is automatically created based on existing pull request: magento/magento2#29829: [MFTF] add new AdminOpenWebConfigurationPageActionGroup

---------
This PR add new `AdminOpenWebConfigurationPageActionGroup` and uses this one instead 
` <amOnPage url="{{WebConfigurationPage.url}}" stepKey="navigateToWebConfigurationPage"/>`
      `  <waitForPageLoad stepKey="waitForPageLoad"/>`

### PR DESCRIPTION
**Pull request by Usik2203**
This PR add new `AdminOpenWebConfigurationPageActionGroup` and uses this one instead 
` <amOnPage url="{{WebConfigurationPage.url}}" stepKey="navigateToWebConfigurationPage"/>`
      `  <waitForPageLoad stepKey="waitForPageLoad"/>`

### Resolved issues:
1. [x] resolves magento/magento2#29846: [MFTF] add new AdminOpenWebConfigurationPageActionGroup

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8126](https://jira.corp.magento.com/browse/ENGCOM-8126) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Pull request merged**
