### PR TITLE
Fixed issue #31891: Order currency is used instead of bas currency in the shipping label form

### LINKED ISSUE #31891: Order currency is used instead of bas currency in the shipping label for form
When the store has multiple currencies and order is placed in any other currency rather than the base currency then this issue happens. The shipping label form uses order currency amounts instead of base currency amounts.
I checked further how different shipping carriers (checked in DHL, UPS, and FedEx) handles submitted custom amount. All of them treats received a custom amount as a base amount. I have faced this issue on Magento version 2.3.4 and 2.4-develop.

Here is the case,

- My order was like below. Order is placed in USD and the base currency is AED.

 !3jMDQab.png|thumbnail! 

-  On the shipping label form "Customs Value" has a suffix of AED (base currency) but values filled in automatically are in USD

 !uyUV2gR.png|thumbnail! 

- Hance shipping label has invalid values. (Label should have 113AED as shown in the first screenshot) 

 !WHIbjUT.png|thumbnail! 

### Preconditions (*)
1. Magento 2.4-develop
1. Store should have more than one currency.
1. Need any online shipping method enabled like DHL, FedEx, UPS, or any other.

### Steps to reproduce (*)
1. Open the frontend and switch to any currency different currency than the base currency.

1. Place an order with any online shipping carrier. (I used DHL)
1. Got to the order page and open the new shipment page.
1. Check the checkbox "Create Shipping Label" and then "Submit Shipment..." - [screenshot](https://i.imgur.com/70CGPHU.png)

### Expected result (*)
1. All amounts shown on the shipping label should be in the base currency.

### Actual result (*)
1. All amounts shown on the shipping label are in the order currency.

## 
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- < ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- [x] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- [ > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

### PR DESCRIPTION
**Pull request by yogesh-valiya**
### Description (*)

I have used the base amount of the sales order item so that the base amount will be used in the frontend recalculation logic and issue #31891 will be resolved.
### Fixed Issues (if relevant)

1. Fixes magento/magento2#31891

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by yvaliya** [comment]
@magento run Unit Tests

**Comment by yvaliya** [comment]
@magento run all tests

**Comment by yvaliya** [comment]
@magento run Functional Tests B2B

**Comment by yvaliya** [comment]
@magento run Functional Tests B2B

**Comment by yvaliya** [comment]
@magento run Functional Tests B2B

**Comment by yvaliya** [comment]
@magento run Functional Tests B2B

**Comment by aleron75** [comment]
Hello @yvaliya thanks for your contribution ant time.

The issue has already been addressed and resolved in [PR 31957](https://github.com/magento/magento2/pull/31957) not by using the item base price but using the order currency.

This is why I'm closing this PR.

**Pull request closed without merging**
