### PR TITLE
Fix regular expression comment on function isNameValid() in ImageContentValidator.php

### PR DESCRIPTION
**Pull request by nimbus2300**
### Description (*)
* This is a simple fix to a regular expression comment in the file ImageContentValidator.php
* The comment did not match the regular expression being used in the code.
* I've added the symbols that were missing.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
This is a change to a comment only, there are no changes to logic.

### Questions or comments
None.

### Contribution checklist (*)
 - [✓] Pull request has a meaningful description of its purpose
 - [✓] All commits are accompanied by meaningful commit messages
 - [N/A] All new or changed code is covered with unit/integration tests (if applicable)
 - [✓] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23840) <br/>All committers have signed the CLA.

**Review by pmclain — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @pmclain, thank you for the review.
[ENGCOM-5507](https://jira.corp.magento.com/browse/ENGCOM-5507) has been created to process this Pull Request
:eight_spoked_asterisk: @pmclain, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@nimbus2300 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
QA not applicable

**Pull request merged**
