### PR TITLE
{ASI} : SortBy component added

### PR DESCRIPTION
**Pull request by konarshankar07**
### Description (*)

Sortby component is developed for Adobe Stock Integration project
### Related Pull Requests

https://github.com/magento/adobe-stock-integration/pull/938

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,
Where we need to add the css code for this component?

**Comment by sivaschenko** [comment]
@konarshankar07 yes, please add it to the theme

**Comment by konarshankar07** [comment]
> @konarshankar07 yes, please add it to the theme

I mean which file `_data-grid.less` or `_masonry-grid.less` file?

**Comment by sivaschenko** [comment]
@konarshankar07 `_masonry-grid.less`, thanks

**Comment by konarshankar07** [comment]
@magento run all tests

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,
As I checked further, The CSS changes are not part of the magento repo so please start the code review and also help me to fix the B2B static test
Thanks

**Comment by sivaschenko** [comment]
Hi @konarshankar07 do you mean the component is properly styled even if it's used without adobe stock integration like in this example: https://github.com/sivaschenko/masonry-grid-example ?

**Comment by sivaschenko** [comment]
@magento run Static Tests

**Comment by konarshankar07** [comment]
Hello @sivaschenko ...
Sorry for the confusion regarding styling. Somehow I missed the styling for the sortBy component so now I've added the styling. Here is the screenshot
image
Thanks

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the updates @konarshankar07 , can you please fix the static tests?

**Review by sivaschenko — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-7210](https://jira.corp.magento.com/browse/ENGCOM-7210) has been created to process this Pull Request

**Review by engcom-Bravo — CHANGES_REQUESTED** [review]
:x: QA Failed

After switching to the current PR and to the dependent PR [938](https://github.com/magento/adobe-stock-integration/pull/938), there is NO Folder tree and **Search Adobe Stock** button in _Enhanced Media Gallery_ 
PR26736_no_button_folder

**Comment by konarshankar07** [comment]
Hello @engcom-Bravo ...
Sorry, I haven't updated https://github.com/magento/adobe-stock-integration/pull/938 PR previously. Can you please test now?
Thanks

**Review by engcom-Bravo — COMMENTED** [review]
@sivaschenko This PR must be in _Ready for testing_ so I could recheck it again.

**Review by sivaschenko — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-7210](https://jira.corp.magento.com/browse/ENGCOM-7210) has been created to process this Pull Request

**Review by engcom-Bravo — CHANGES_REQUESTED** [review]
:x: QA Failed

It seems like sorting by name sorts image names from Z to A.
sorting_MG

Please, change the images to be sorted from A --> Z.

**Comment by konarshankar07** [comment]
Hello @sivaschenko and @engcom-Bravo ....
I have fixed the sorting direction. Please review and test now
Thanks

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-7210](https://jira.corp.magento.com/browse/ENGCOM-7210) has been created to process this Pull Request

**Review by engcom-Bravo — COMMENTED** [review]
:heavy_check_mark: QA Passed

**Comment by chalov-anton** [comment]
@konarshankar07 
Can you please add _Sorting by_ **Uploaded date**? 
Thank you

**Pull request merged**
