### PR TITLE
Added cdata to comment

### PR DESCRIPTION
**Pull request by brunoroeder**
### Description (*)

Fixed a backend comment that wasn't translated by i18n

### Fixed Issues (if relevant)

1. #24721: Backend comment translate 2.3.2
2. #22169: Typo issue:Magento admin store configuration general web Base url place holder comment spelling mistake

### Manual testing scenarios (*)

1. Create an i18n other language to translate 
2. Translate the module  	module-backend
3. Translate the string "Specify URL or {{base_url}} placeholder.","Insert here the translation"
4. The given translation string will show

Screenshot at Oct 02 15-59-01

Screenshot at Oct 02 15-58-42

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hostep** [comment]
@brunoroeder: out of curiosity, does this also fixes https://github.com/magento/magento2/issues/22169?

**Comment by brunoroeder** [comment]
> @brunoroeder: out of curiosity, does this also fixes #22169?

Yes, I`ve update the PR to fix all {{placeholder}} strings.

**Comment by hostep** [comment]
Nice!
And thanks for adding it to your opening post 👍

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-6011](https://jira.corp.magento.com/browse/ENGCOM-6011) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
