### PR TITLE
Change the favicon file to the newer Magento logo

### PR DESCRIPTION
**Pull request by DMMundle**
### Description
 - remove white background
 - update orange to official color

### Manual testing scenarios

1. Validate the favicon on the setup and admin match the magento.com favicon

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16061) <br/>All committers have signed the CLA.

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-2015](https://jira.corp.magento.com/browse/ENGCOM-2015) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@DMMundle thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @DMMundle. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.3.0 release.

**Comment by DMMundle** [comment]
Thanks to @dmanners, @soumya-ashok, @miguelbalparda, @RebeccaBrocton, and anyone else involved on the @magento-engcom-team for helping me with this!

**Pull request merged**
