### PR TITLE
Removing "if" block and making code more legible

### PR DESCRIPTION
**Pull request by matheusgontijo**
### Description
Just removed "if" block and made code more legible for future maintenance

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22830) <br/>All committers have signed the CLA.

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-5100](https://jira.corp.magento.com/browse/ENGCOM-5100) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@matheusgontijo thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
