### PR TITLE
Fix incorrect alignment element in login container theme blank

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Some text and block display incorrect. Just modify to make it align again

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. Magento 2.3.4+
2. Theme magento blank
3. Go to customer login page in desktop

### Expected result
Screenshot from 2020-04-02 11-47-04

### Actual result
Screenshot from 2020-04-02 11-47-41

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-27544.instances.magento-community.engineering).
Admin access: [https://pr-27544.instances.magento-community.engineering/admin_0816](https://pr-27544.instances.magento-community.engineering/admin_0816)
Login: `c046dcc8` Password: `8dda5d040bb7`
Instance will be terminated in up to 3 hours.

**Review by edenduong — APPROVED** [review]
Thank you for your contribution !

**Comment by magento-engcom-team** [comment]
Hi @edenduong, thank you for the review.
[ENGCOM-7249](https://jira.corp.magento.com/browse/ENGCOM-7249) has been created to process this Pull Request
:eight_spoked_asterisk: @edenduong, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:**
Screenshot from 2020-04-03 10-43-01

**After:**
Screenshot from 2020-04-03 10-58-27

**Review by ptylek — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-7249](https://jira.corp.magento.com/browse/ENGCOM-7249) has been created to process this Pull Request

**Pull request merged**
