### PR TITLE
Fixing - Responsive Layout on footer

### PR DESCRIPTION
**Pull request by rodrigoobiassi**
I was showing the platform to a prospective client and noticed this problem. Broken responsive layout.

1 - test

2 - test2

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @rodrigoobiassi. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16981) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
@rodrigoobiassi thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by gwharton** [comment]
Please check if PR #17006 fixes this for you and close as necessary.

**Comment by sidolov** [comment]
@rodrigoobiassi , please, check comment above and take a look at merge conflict. 
Thank you!

**Comment by rodrigoobiassi** [comment]
Hi @sidolov, I just made the requested change. Thanks.

**Comment by gwharton** [comment]
@rodrigoobiassi Are you sure this PR is still required. PR #17006 made changes to the responsive layout for mobile devices, namely it made the mobile screens behave the same way as the desktop screens with respect to the footers. i.e that if the page/content is shorter than the screen, then the footer snaps to the bottom whereas if the page/content is longer than the screen, then the footer is pushed to the bottom of the content, and not the bottom of the screen.

It looks like this PR is in conflict with this resolution, i.e that it will cause the footer to always snap to the bottom of the screen regardless of the page/content size. This is not consistent with the desktop layout.

**Comment by sidolov** [comment]
Hi @rodrigoobiassi , please, read the comment from @gwharton , maybe the issue resolved and we can close this pr?

**Comment by sidolov** [comment]
Hi @rodrigoobiassi , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
