### PR TITLE
Fixed store view switcher issues when changing store view on product ...

### PR DESCRIPTION
**Pull request by thomasdom**
…and category pages.

### Description
Added a condition to check in Product and Category View controllers to check if URL is from store view switcher.

### Fixed Issues (if relevant)
1. magento/magento2#11963: Magento 2.2 language switching not working on catalog and Product Pages

### Manual testing scenarios

1. Set up a Magento 2 storefront with at least 2 Store Views (in my case, French and English)
2. Go on a product page view from any Store View.
3. Assert that when you change current Store View from switcher, the current Store View has actually changed.
4. Assert that when you change back to the original Store View from switcher, the current Store View has actually changed.
5. Go on a category page view from any store view.
6. Assert that when you change current Store View from switcher, the current Store View has actually changed.
7. Assert that when you change back to the original Store View from switcher, the current Store View has actually changed.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=13534) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
@thomasdom thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by thomasdom** [comment]
Updated pull request to fix code style issues related to my fixes.

**Comment by dmanners** [comment]
Thanks @thomasdom. I will take a look over this for you.

**Comment by koenner01** [comment]
If anybody tries to backport this to 2.1.11 you will need https://github.com/magento/magento2/commit/03fe593c691160208d553689372c8b4acaa8827a#diff-f803cfbf47677f2734d67e6d10e8451f

**Comment by okorshenko** [comment]
Hi @thomasdom 
The issue has been fixed in other PR. Please see the comment https://github.com/magento/magento2/issues/11963#issuecomment-366058497
Thank you for your contribution.

**Pull request closed without merging**
