### PR TITLE
Fixed checkout page product options alignment in order summary

### PR DESCRIPTION
**Pull request by mage2pratik**
### Description (*)

Fixed checkout page product options alignment in order summary.

### Fixed Issues (if relevant)

1. magento/magento2#20134: On checkout page product options is not align in order summary

### Manual testing scenarios (*)

1. add product to cart
2. and go to checkout page in order summary

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-3854](https://jira.corp.magento.com/browse/ENGCOM-3854) has been created to process this Pull Request

**Comment by sdzhepa** [comment]
Hello @mage2pratik 

Our QA engineer tested your fix and everything is OK.

But he found small inconsistency now between "Checkout Summary Block" and "Mini-Cart" after the fix.
example

Could you please apply the same fix to mini-cart as well?

Anyway, thank you for contribution and collaboration!

**Comment by mage2pratik** [comment]
Hi @sdzhepa : I've updated code related for Mini-Cart design.

**Comment by sdzhepa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [new Magento instance](https://pr-20138.instances.magento-community.engineering).
Admin access: [https://pr-20138.instances.magento-community.engineering/admin](https://pr-20138.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sdzhepa** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-20138-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20138-2-3-develop.instances.magento-community.engineering/admin](https://i-20138-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
Hi @mage2pratik 

While working on this PR I faced small new style issue in mini-cart.
Could you please have a look and fix it?


pr20138


Thank you for contribution and collaboration!

**Comment by sdzhepa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [new Magento instance](https://pr-20138.instances.magento-community.engineering).
Admin access: [https://pr-20138.instances.magento-community.engineering/admin](https://pr-20138.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by sdzhepa — APPROVED** [review]

**Comment by sdzhepa** [comment]
Hi @mage2pratik 

I have verified PR after last fix and can confirm issue is fixed.
I put PR into delivery queue.

Thank you for contribution and collaboration!

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, thank you for the review.
[ENGCOM-3854](https://jira.corp.magento.com/browse/ENGCOM-3854) has been created to process this Pull Request

**Pull request merged**
