### PR TITLE
Load appropriate slider widget on demand to improve performance

### LINKED ISSUE #28807: [Issue] Load appropriate slider widget on demand to improve performance
This issue is automatically created based on existing pull request: magento/magento2#27616: Load appropriate slider widget on demand to improve performance

---------

### Description (*)
This PR is a part of my effort to improve Magento 2 frontend performance.

Because of the fact that all Knockout bindings are registered on every load, there are many dependencies requested no matter if such binding is even used on the page. Changes in this PR include:

- Touch slider widget customization is moved to a separate file so it can be loaded only on compatible devices.
- Appropriate slider widget type is loaded on-demand, only when range binding is actually used on the page.

### Preconditions (*)

1.Magento 2.4-develop 

### Steps to reproduce (*)

1. Add the range slider widget to the page, e.g. by adding the following HTML to the CMS block: 
```html
<div class="timeline-scale"></div>
<div class="data-slider" data-bind="{"range":{
                "value": ko.observable(50),
                "min": 1,
                "max": 100,
                "step": 5
            }}">&nbsp;</div>
</div>
```
2. Validate that it works for both mouse and touch.

### Expected result (*)

1. Responsive:
Peek 2020-04-28 11-23PR
2 .Desktop:
Peek 2020-04-28 11-26PRDestktop

### Actual result (*)

1. [Screenshots, logs or description]
2.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by krzksz**
### Description (*)
This PR is a part of my effort to improve Magento 2 frontend performance.

Because of the fact that all Knockout bindings are registered on every load, there are many dependencies requested no matter if such binding is even used on the page. Changes in this PR include:

- Touch slider widget customization is moved to a separate file so it can be loaded only on compatible devices.
- Appropriate slider widget type is loaded on-demand, only when range binding is actually used on the page.

### Manual testing scenarios (*)

1. Add the range slider widget to the page, e.g. by adding the following HTML to the CMS block: 
```html
<div class="timeline-scale"></div>
<div class="data-slider" data-bind="{"range":{
                "value": ko.observable(50),
                "min": 1,
                "max": 100,
                "step": 5
            }}">&nbsp;</div>
</div>
```
2. Validate that it works for both mouse and touch.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28807: Load appropriate slider widget on demand to improve performance

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7290](https://jira.corp.magento.com/browse/ENGCOM-7290) has been created to process this Pull Request

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7290](https://jira.corp.magento.com/browse/ENGCOM-7290) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked the range slider widget works for both mouse and touch.
**Result:**
Responsive:
Peek 2020-04-28 11-23PR
Desktop:
Peek 2020-04-28 11-26PRDestktop

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento create issue

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Pull request merged**
