### PR TITLE
Update method 'afterConvert' of Magento\Tax\Model\Quote\ToOrderConverter to set order extension attributes type as declared in the extension_attributes.xml file

### PR DESCRIPTION
**Pull request by vasilii-b**
### Description (*)
Please check magento/magento2#6092 description

### Fixed Issues (if relevant)
1. magento/magento2#6092

### Manual testing scenarios (*)
Check issue description

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by slavvka — COMMENTED** [review]
@vasilii-b Thank you for the valuable contribution! But this solution changes the way how this extension attributes are stored in the Order. So could you please check all the places in the code where these attributes may be referred to in the old way. BTW the failing Unit, Integration and Functional tests may testify of that. Please look at them and fix.

**Comment by vasilii-b** [comment]
Thank you @slavvka , will definitely have a look on it!

**Comment by slavvka** [comment]
Hey @vasilii-b Are you going to proceed with this PR?

**Comment by vasilii-b** [comment]
Of course, @slavvka :) Already looking into the failing tests and possible places where additional changes are required.

**Comment by sivaschenko** [comment]
Hi @vasilii-b , would you like to continue work on this PR?

**Comment by vasilii-b** [comment]
Hi @sivaschenko, I'll submit fixes for failed tests in the nearest future. But if someone wants to grab it and fix them for me, I won't be against. Thank you!

**Comment by sidolov** [comment]
Hi @vasilii-b , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
