### PR TITLE
Implement ActionInterface for /checkout/account/delegatecreate (+ Unit Tests)

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
This is a part of the process of introducing implementations of `ActionInterface`.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — DISMISSED** [review]
Good job 👍

The failing tests are not related. We see the same red tests for all new PRs (youtube limit for videos and so on)

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7203](https://jira.corp.magento.com/browse/ENGCOM-7203) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Review by slavvka — CHANGES_REQUESTED** [review]
This tests `Magento\Checkout\Test\TestCase\OnePageCheckoutOfflinePaymentMethodsTest` is constantly failing for EE and B2B

**Comment by lbajsarowicz** [comment]
Could you provide the exception.log from the tested instance for this: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/27422/5e21c2c3d22dc36e88e549a1360978c3/Functional/allure-report-ee/index.html#categories/779d23dea3075a2db1ab0d4d207f20a9/ca978c1158881304/

**Comment by slavvka** [comment]
@lbajsarowicz Looks like `exception.log` is not stored for MTF tests in artifacts. Could you try to run it locally?

**Comment by lbajsarowicz** [comment]
I'm going to try by tomorrow :-)

**Comment by lbajsarowicz** [comment]
That test comes from the previous version of Functional Tests that I'm unable to run locally.
`dev/tests/functional/tests/app/Magento/Checkout/Test/TestCase/OnePageCheckoutOfflinePaymentMethodsTest.xml`

**Comment by slavvka** [comment]
@engcom-Foxtrot could you please assist @lbajsarowicz with that?

**Comment by lbajsarowicz** [comment]
The issue is being reported in PHP errors log, not in exception log. But I cannot reproduce the issue.

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
If anyone else wants to pick this, feel free to take my code and continue.
I won't be available to handle that in next 2 - 3 weeks.

**Pull request closed without merging**
