### PR TITLE
"New Tax Rate" missing validation => data is automatically changed when saving issue 23967

### LINKED ISSUE #23967: "New Tax Rate" missing  validation => data is automatically changed when saving
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Store -> Tax Zone and Rate
2. New Tax Rate
3. Fill: 12345678901 (over 10 character) in "Zip/Post Code"
4. Save
5. Back to the tax rate which is saved
6. See "Zip/Post Code"

### Expected result (*)

1. Don't allow to save

### Actual result (*)

1. Saved. But the "Zip/Post Code" cut to 1234567890

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

Resolve magento/magento2#23967: "New Tax Rate" missing validation => data is automatically changed when saving

Problem: Missing the "validate-length maximum-length" validate
Solution: Add to the class

### Fixed Issues (if relevant)

1. magento/magento2#23967: "New Tax Rate" missing validation => data is automatically changed when saving

### Manual testing scenarios (*)

1. Store -> Tax Zone and Rate
2. New Tax Rate
3. Fill: 12345678901 (over 10 character) in "Zip/Post Code"
4. Save
**=> Don't allow to save**

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by XxXgeoXxX — COMMENTED** [review]
Please, cover you change with mftf test.

**Comment by edenduong** [comment]
@XxXgeoXxX: I have covered it by MFTF. Please check it.

**Review by XxXgeoXxX — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX, thank you for the review.
[ENGCOM-5545](https://jira.corp.magento.com/browse/ENGCOM-5545) has been created to process this Pull Request
:eight_spoked_asterisk: @XxXgeoXxX, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
