### PR TITLE
Fix Adminhtml - Create order - no customer selected

### LINKED ISSUE #21603: Adminhtml - Create order - no customer selected
### Preconditions (*)

1. Fresh install of Magento 2 - 2.3.0
2. Deploy sample data

### Steps to reproduce (*)

1.  Sales -> Orders -> Create New Order
capture1
capture2
2.  F5 (browser refresh / reload page)

### Expected result (*)

1. At this stage no customer has been selected and I would expect the page to display the customer grid
2. 

### Actual result (*)

1. The order detail section is shown with no customer selected and no customer details entered.
2.
capture3

### PR DESCRIPTION
**Pull request by lampham2141993**
### Description (*)
On the admin panel, when creating new order but don't select customer.
After that refresh page, we can't select custom again.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#21603: Adminhtml - Create order - no customer selected

### Manual testing scenarios (*)

1. Unit test
2. Mftf

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lampham2141993** [comment]
Hi @magento-engcom-team ,

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @lampham2141993,
According to tests results - seems like your change broke reorder functionality.
Could you review tests failures and update your solution accordingly?

**Comment by engcom-Charlie** [comment]
Hi @lampham2141993, could you please look at https://github.com/magento/magento2/pull/27651#pullrequestreview-493158690?
Otherwise, we can't proceed with your PR.
Thank you.

**Comment by sidolov** [comment]
@lampham2141993  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
