### PR TITLE
Removed CliIndexerReindexActionGroup action group usage for modules (mix)

### LINKED ISSUE #31852: [Issue] Removed CliIndexerReindexActionGroup action group usage for modules (mix)
This issue is automatically created based on existing pull request: magento/magento2#31851: Removed CliIndexerReindexActionGroup action group usage for modules (mix)

---------
### Description
Removed usage or changed value of CliIndexerReindexActionGroup action group for the following modules: Elasticsearch, Elasticsearch6, LayeredNavigation, LoginAsCustomer, Newsletter, UrlRewrite, Weee, Wishlist

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Removed usage or changed value of CliIndexerReindexActionGroup action group for the following modules: Elasticsearch, Elasticsearch6, LayeredNavigation, LoginAsCustomer, Newsletter, UrlRewrite, Weee, Wishlist

### Resolved issues:
1. [x] resolves magento/magento2#31852: Removed CliIndexerReindexActionGroup action group usage for modules (mix)

### CODE REVIEW

**Comment by sergiy-v** [comment]
@magento create issue

**Comment by sergiy-v** [comment]
@magento run all tests

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE,Functional Tests B2B,Semantic Version Checker

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run WebAPI Tests, Unit Tests, Static Tests, Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B, Magento Health Index, Integration Tests, Database Compare

**Comment by sergiy-v** [comment]
Everything are green, @rogyar please proceed with review.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8796](https://jira.corp.magento.com/browse/ENGCOM-8796) has been created to process this Pull Request
:eight_spoked_asterisk: @rogyar, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
QA not applicable

**Pull request merged**
