### PR TITLE
Trim username on customer account login page

### PR DESCRIPTION
**Pull request by dankhrapiyush**
Trim email address on customer account login page generally when copy and paste.

### Description

Trim email address by remove leading or trailing space on the customer account login page email field.

### Fixed Issues (if relevant)

1. magento/magento2#6058: IE11 user login email validation fails if field has leading or trailing space

### Manual testing scenarios

1. Open customer account login page in Firefox or IE browser.
2. Try to add space before entering an email address in the Email field.
3. Copy `" johndoe@domain.com "` and paste in the Email field. It will automatically remove leading or trailing space.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15365) <br/>All committers have signed the CLA.

**Comment by dankhrapiyush** [comment]
Thanks @vgelani

**Comment by VladimirZaets** [comment]
Hi @dankhrapiyush, thank you for collaboration.
Can you please remove `trimUsername` declaration from `requirejs-config.js` and use path `Magento_Customer/js/trim-username` obviously inside `.phtml`.

**Comment by dankhrapiyush** [comment]
@VladimirZaets Removed trimUsername declaration from `requirejs-config.js` and used path `Magento_Customer/js/trim-username` inside `.phtml`.

I'm not getting why the Travis CI build could not complete.

Thank you.

**Comment by VladimirZaets** [comment]
@dankhrapiyush thanks. Currently, we have some problem with Travis. It isn't PR problem.

**Comment by dankhrapiyush** [comment]
@VladimirZaets Okay, Thank you.

**Comment by magento-engcom-team** [comment]
Hi @dankhrapiyush. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.6 release.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
