### PR TITLE
Replace repetitive actions with Action Groups in ProductsListWidgetTest

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run the test in the local environment and verified that it run successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B, Functional Tests CE,  Integration Tests, Unit Tests

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests EE

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B, Integration Tests

**Comment by Den4ik** [comment]
I believe that for this PR we can skip adding of multiple comments just for preventing fail semantic version checks.
Main tests that should be passed is Functional Tests.
I hope magento core team agree with me.

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B

**Comment by eduard13** [comment]
@Den4ik those comments are added in order to preserve the stepKeys that were removed, since removing any stepKey is a backward incompatible change, as there might be some 3rd party tests that can rely on some step keys. So, by not preserving them, it means to not provide support for those tests that extend the current ones.

Thanks.

**Comment by Den4ik** [comment]
@eduard13, thanks for your comment.
I just want provide my opinion on this case.
I suggested to remove comments by 2 reasons:
1. Comments are add unnecessary information to execution output additionally to output from action groups
2. I saw in git history PRs that contain same backward incompatible changes and was merged.

Do you have examples of 3rd modules that rely on step keys?
I agree with adding comments if PR contains only removing some of steps, but when we moving all steps from Test file to action group we don't missing anything. It's just my opinion.

**Comment by eduard13** [comment]
@Den4ik, I totally agree with you regarding the 1st point, there is no doubt about that. As about already delivered similar PRs, could you please share some if you still have a reference to them?

> Do you have examples of 3rd modules that rely on step keys?

Unfortunately not, but since MFTF allows this, then I don’t think we need to find some real examples. 

> but when we moving all steps from Test file to action group we don't missing anything.

In this case, the generated stepKey won’t be the same anymore, it will be suffixed(if I’m not wrong) by ActionGroup’s stepKey. So you’ll loose its reference. 

Thank you.

**Comment by Den4ik** [comment]
> could you please share some if you still have a reference to them?

First that I found in browser history https://github.com/magento/magento2/pull/28457

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-9064](https://jira.corp.magento.com/browse/ENGCOM-9064) has been created to process this Pull Request

**Comment by dmitriyprime** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
