### PR TITLE
[Typo] 4 README.md 4

### PR DESCRIPTION
**Pull request by 4quaternion**
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15859) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=15859) before we can accept your contribution.<br/>

**Comment by okorshenko** [comment]
Hi @DanielRuf please don't close this one. I'm working on it. Testing new feature for contributor assistance

**Comment by DanielRuf** [comment]
These PRs are not helpful at all. Can we not use real PRs? These changes produce much noise and I see no new contributor feature here.

**Comment by okorshenko** [comment]
I will close them soon

**Comment by DanielRuf** [comment]
Also without signing the CLA there will probably nothing start.

**Pull request closed without merging**
