### PR TITLE
Reverting javascript translation refactoring which broke javascript translation

### PR DESCRIPTION
**Pull request by mfickers**
### Description

This reverts commit 459ce25867fe931bdac856ec2cd275731e29640e.

The commit broke some javascript translations, because after javascript translation initialisation was refactored into its own file, the translation dictionary was not initialised early enough.

### Fixed Issues (if relevant)

1. magento/magento2#19705: Javascript translation issue on modal buttons when removing items from product compare page

### Manual testing scenarios (*)

1. Create a translation dictionary file for a storefront language
2. Translate the phrase "Cancel" in the dictionary file
3. Clear cache, deploy static content, ...
4. Click on the remove product link in minicart
5. Observe wether the cancel-button of the confirmation-popup is translated

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mfickers. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20109) <br/>All committers have signed the CLA.

**Comment by sivaschenko** [comment]
Hi @mfickers , thanks for the contribution! I would prefer to keep the refactored approach. Maybe there is a way to fix the issue by i.e. introducing dependency that will allow the translation dictionary to be initialised early enough?

**Comment by DrewML** [comment]
Seconding the comment from @sivaschenko - moving JS out of being inline in partials is a good thing, and would prefer to just move forward and fix the timing issue.

**Comment by DrewML** [comment]
Was the original PR that moved this code into an external file fixing a bug, or just an improvement? If it was just an improvement I'm in favor of a reverting for now and we can try the improvement again with some more testing later.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4073](https://jira.corp.magento.com/browse/ENGCOM-4073) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@mfickers thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request merged**
