### PR TITLE
Issue #20111 Fixed

### PR DESCRIPTION
**Pull request by mahesh-rajawat**
issue #20111 fixed in this PR.

### Fixed Issues (if relevant)

1. #20111 
2. ...

### Manual testing scenarios (*)

1. Edit a Email Template from  admin>>MARKETING>>Email Templates>>
2. Click on Insert Variable... button.
3. Able to insert variables from popup now.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
Hi @maheshWebkul721 , thanks for the contribution! Can you please fix the `Magento\Email\Test\Unit\Block\Adminhtml\Template\Edit\FormTest` that failed on Travis and then squash all the commits into a single one.

**Comment by mahesh-rajawat** [comment]
@sivaschenko i am trying to rebase all commits, i am getting lots of merge conflicts error.
Do i need to create new PR with the same change?

**Comment by sivaschenko** [comment]
@maheshWebkul721 there is no need to create a new PR, you can push whatever you'd like to the pull request branch.

I would do a soft reset of the branch to the clean 2.3-develop remote, then commit all changes in a single commit and then force push the branch.

**Pull request closed without merging**
