### PR TITLE
Update Magento logo & copyright to add Adobe

### PR DESCRIPTION
**Pull request by osrecio**
Add new Magento logo with Claim: "an Adobe company"
Add new Copyright with claim: "an Adobe company"

### Manual testing scenarios

1. Go to Admin
2. Check Logo
3. Check CopyRight
4. Change Theme for Blank
5. Check Logo

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @osrecio. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by osrecio** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @osrecio. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @osrecio, here is your [new Magento instance](https://pr-16322.engcom.dev.magento.com).
Admin access: [https://pr-16322.engcom.dev.magento.com/admin](https://pr-16322.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Please make sure you are PR **author** or **assignee** to access the instance.

**Comment by sidolov** [comment]
Hi @osrecio , unfortunately, we can't accept this pull request because we are waiting for more information from our legal teams regarding the final name and copyright details. We will reopen this pull request or make logo and copyrights changes by core team at a later date.
Thank you for the contribution!

**Pull request closed without merging**
