### PR TITLE
Resolve "Service->Oauth Settings" has no number validation issue24172

### LINKED ISSUE #24172: "Service->Oauth Settings" has no number validation
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Store->Configuration
3. Service-> Oauth
4. Fill all the Field as text (like "test")
5. Save config 

### Expected result (*)

1. Can not save because they are not number

### Actual result (*)

1. Save the invalid data

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#24172: "Service->Oauth Settings" has no number validation

Solution: Add the "validate" tag in app/code/Magento/Integration/etc/adminhtml/system.xml

### Fixed Issues (if relevant)

1. magento/magento2#24172: "Service->Oauth Settings" has no number validation

### Manual testing scenarios (*)

1. Go to backend
2. Store->Configuration
3. Service-> Oauth
4. Fill all the Field as text (like "test")
5. Save config 

#### Expected result 

1. Can not save because they are not number

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by kalpmehta** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, here is your [Magento instance](https://i-24173-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24173-2-3-develop.instances.magento-community.engineering/admin](https://i-24173-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kalpmehta** [comment]
@edenduong Sorry I just noticed you have assigned @swnsma as a reviewer after requesting test Magento instance from Magento. Is this something only he can test, or you want him only to test this?

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5659](https://jira.corp.magento.com/browse/ENGCOM-5659) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
