### PR TITLE
[MFTF] Refactoring AdminMassOrdersUpdateCancelPendingOrderTest

### LINKED ISSUE #31514: [Issue] [MFTF] Refactoring AdminMassOrdersUpdateCancelPendingOrderTest
This issue is automatically created based on existing pull request: magento/magento2#31512: [MFTF] Refactoring AdminMassOrdersUpdateCancelPendingOrderTest

---------
### Description (*)
The test is refactored to improve execution time

### Related Pull Requests
https://github.com/magento/magento2/pull/31509

### Manual testing scenarios (*)
1. Create an order
2. Go to the Orders Grid
3. Try to cancel the order via mass update
4. Verify the result

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
The test is refactored to improve execution time

### Related Pull Requests
https://github.com/magento/magento2/pull/31509

### Manual testing scenarios (*)
1. Create an order
2. Go to the Orders Grid
3. Try to cancel the order via mass update
4. Verify the result

### Resolved issues:
1. [x] resolves magento/magento2#31514: [MFTF] Refactoring AdminMassOrdersUpdateCancelPendingOrderTest

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Comment by rogyar** [comment]
Hi @AnnaAPak. Great job! Just small advice for the next time. Please, provide in the description short info on how exactly your changes reduce the execution time. It will speed up the PR review and delivery as the result. 

For this particular case, it will be something like the following.

> The changes introduced in the current PR invoke entities creation via API rather than entities creation via admin UI. 

Thank you!

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8602](https://jira.corp.magento.com/browse/ENGCOM-8602) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** Functional Tests B2B, EE, CE are failed

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Pull request merged**
