### PR TITLE
Shubham 18724

### PR DESCRIPTION
**Pull request by Shubham0492**
Description (*)
There was a issue in display tax percent if select any locale where comma(,) use instead of decimal (.) for an example Germany.

Fixed Issues (if relevant)
#18724 : Display tax percent in current locale number format

Manual testing scenarios (*)
1: login magento admin
2: Set in admin locale Germany or other European country where decimal character is comma
3: In Admin > Stores > Configuration > Sales > Tax > Shopping Cart Display Settings > Display Full Tax Summary = Yes and in the other section "Orders, Invoices, Credit Memos Display Settings"
4: Set a tax percent in admin with decimals like 50.1.
5: Add any product to cart and goto cart page.
6: Check order summary.

Contribution checklist (*)
  Pull request has a meaningful description of its purpose
  All commits are accompanied by meaningful commit messages
  All new or changed code is covered with unit/integration tests (if applicable)
  All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by Shubham0492** [comment]
#squashtoberfest

**Review by orlangur — DISMISSED** [review]
Nowadays all changes must be applied to `2.3-develop` first (see https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules). Please prepare a new pull request, this one should be `on hold` until the latter is merged.

**Comment by Shubham0492** [comment]
@orlangur I have made new pull request for 2.3-develop https://github.com/magento/magento2/pull/19177

**Comment by orlangur** [comment]
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

**Pull request closed without merging**
