### PR TITLE
#21789 Fix gallery event observer

### PR DESCRIPTION
**Pull request by Den4ik**
### Description (*)
This PR fix issue of opening gallery if moving mouse to image when clicking to another element of page

### Fixed Issues (if relevant)

1. magento/magento2#21789: [BUG] Product gallery opening by mistake

### Manual testing scenarios (*)

1. Open product page
2. Click to product qty move cursor to product image and up mouse button

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-4511](https://jira.corp.magento.com/browse/ENGCOM-4511) has been created to process this Pull Request

**Comment by shikhamis11** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [new Magento instance](https://pr-21790.instances.magento-community.engineering).
Admin access: [https://pr-21790.instances.magento-community.engineering/admin](https://pr-21790.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by VasylShvorak** [comment]
✔️ QA passed

**Comment by VladimirZaets** [comment]
Hi @Den4ik. Thanks for collaboration.
Currently, we [support](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements_browsers.html) IE 11 browser that not good supports ES6 features. 

We can't add es6 to eslint cause it's will mean that we fully support ES6 but currently, it isn't. 
Let and const declaration are already supported by IE11, but again, we should use all features of ES6 or don't use anything.

**Comment by Den4ik** [comment]
@VladimirZaets Can you please comment this file https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Rule/view/adminhtml/web/rules.js#L302

**Comment by Den4ik** [comment]
@magento/engcom-team-members Any comments for this PR?

**Comment by VladimirZaets** [comment]
Hi @Den4ik. According to [rules.js](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Rule/view/adminhtml/web/rules.js) file. It's our mistake, you can fix `rules.js` file according to our standarts and create the pull request.

**Comment by Den4ik** [comment]
@VladimirZaets 
Ok, I have reverted previous commits and added only js event fix. Please review

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4596](https://jira.corp.magento.com/browse/ENGCOM-4596) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
Hi @Den4ik Could you resolve conflicting files with 2.3-develop?

**Comment by Den4ik** [comment]
@VasylShvorak  Resolved

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-4596](https://jira.corp.magento.com/browse/ENGCOM-4596) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
✔️ QA passed

**Pull request merged**
