### PR TITLE
[FTR] Migrate from ZF2 components to Laminas components

### PR DESCRIPTION
**Pull request by Den4ik**
### Description (*)

This PR replace ZF2 components dependency to Laminas components

### Related Pull Requests

1. https://github.com/magento/magento2/pull/26436

### Fixed Issues (if relevant)

1. https://github.com/magento/community-features/issues/229
2. https://github.com/magento/magento2/issues/26335

### Questions or comments

Due to 2 weeks inactivity on original PR I opened this PR with resolved conflicts

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Den4ik** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [new Magento instance](https://pr-26883.instances.magento-community.engineering).
Admin access: [https://pr-26883.instances.magento-community.engineering/admin_f845](https://pr-26883.instances.magento-community.engineering/admin_f845)
Login: `0101802e` Password: `18905fb30f94`
Instance will be terminated in up to 3 hours.

**Comment by lenaorobei** [comment]
This improvement is already done in the scope of  https://github.com/magento/magento2/pull/26883

I think you should consider working with @ihor-sviziev if something is missing.

**Comment by Den4ik** [comment]
HI @lenaorobei 
Thanks for remark. But I opened this PR due to inactivity in original PR.
Unfortunately I don't have permissions for committing to @ihor-sviziev repository.
Please close this PR if updates will be provided at #26436

**Comment by ihor-sviziev** [comment]
Hi @Den4ik,
In my original PR all CE tests were passing and I hadn’t any issues. There were issues with b2b and EE versions, but as I don’t have access to them -  I can’t fix them.

**Comment by ihor-sviziev** [comment]
I just wrote an update in my PR to highlight the current status

**Pull request closed without merging**
