### PR TITLE
FIX whitespaces possible in product sku

### PR DESCRIPTION
**Pull request by wstnbrg**
### Description
Set trimmed sku (provided by post request) in Magento\Catalog\Controller\Adminhtml\Product\Save on line 131 to prevent whitespaces in sku like the autogenerate function does.

### Fixed Issues (if relevant)
1. magento/magento2#16572: Trim whitespace on SKU when saving product

### Manual testing scenarios
1. Added a product from Backend with a sku with whitespaces at beginning and end
2. Saved a product from Backend with a sku with whitespaces at beginning and end
3. ran "php bin/magento dev:tests:run" from Magento Root/Install dir

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18417) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18417) before we can accept your contribution.<br/><hr/>**Henning Westenberg** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by josefbehr** [comment]
@wstnbrg Thank you for your contribution. Can you please check why the integration tests are failing? In the best case, you could also provide new tests for the sku.

**Comment by sidolov** [comment]
Hi @wstnbrg , looks like you made some commits with email different than in your GitHub profile, please, add email from commits to your profile!
Thank you!

**Comment by sivaschenko** [comment]
Closed due to inactivity.

**Pull request closed without merging**
