### PR TITLE
[Forwardport] Fixing a Mistype Error

### PR DESCRIPTION
**Pull request by tiagosampaio**
Replacing the method proccessAdditionalValidation by processAdditionalValidation. It's was mistype error.

### Description

Fixed a mistype error in a method name.

### Fixed Issues (if relevant)

None.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### Original PR 
https://github.com/magento/magento2/pull/16414

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @tiagosampaio. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
Changes must be applied to `2.2-develop` first.

**Comment by tiagosampaio** [comment]
@orlangur the same pull request was applied to branch `2.2-develop` and it's already merged. Please check the pull request in #16414.

**Review by orlangur — APPROVED** [review]
@tiagosampaio true, thanks for pinging!

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-2338](https://jira.corp.magento.com/browse/ENGCOM-2338) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @tiagosampaio. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Pull request merged**
