### PR TITLE
FIXED validator -> Zend Email Validator replaced with egulias/EmailValidator

### PR DESCRIPTION
**Pull request by ivanrogar**
Zend Validator replaced with egulias/EmailValidator throughout the framework

### Description
Removed Zend Email Validation throughout the framework with "egulias/EmailValidator".

### Fixed Issues (if relevant)

1. magento/magetno2#4547: Support for new `.tech` TLD and others required

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=8920) <br/>All committers have signed the CLA.

**Comment by orlangur** [comment]
Any idea why we reinvent the wheel here instead of using robust approach like in https://github.com/magento/magento2/pull/8420/files#r99476657?

**Comment by ivanrogar** [comment]
@orlangur  This is meant to be a replacement for the obsolete Zend Email Validator. There has to be some form of replacement validation mechanism for email present. I've added the DNS check now besides the RFC check in the second commit (the first one has failed the build).

**Comment by orlangur** [comment]
> has to be some form of replacement validation mechanism

Did you read the link I posted? The article didn't convince you?

**Comment by okorshenko** [comment]
Closing this PR due to inactivity

**Comment by okorshenko** [comment]
Feel free to reopen it if you would like to proceed with this contribution. Thank you

**Pull request closed without merging**
