### PR TITLE
Add functionality to show parent product

### PR DESCRIPTION
**Pull request by orozcodiaz**
### Description (*)
This Pull Request contains the code allowing the admin user to go back to the parent product after he opens a simple one.

Screenshot 2020-01-24 12 04 37

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [-] All new or changed code is covered with unit/integration tests (if applicable)
 - [-] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by orozcodiaz** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @oroskodias. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @oroskodias, here is your [new Magento instance](https://pr-26530.instances.magento-community.engineering).
Admin access: [https://pr-26530.instances.magento-community.engineering/admin_02fd](https://pr-26530.instances.magento-community.engineering/admin_02fd)
Login: `bc9df330` Password: `aac41e7e00bf`
Instance will be terminated in up to 3 hours.

**Review by Stepa4man — CHANGES_REQUESTED** [review]
Hi @oroskodias
Thanks for your contribution 

How it will work if simple product participates in several configurable products?

**Comment by engcom-Charlie** [comment]
Hi @oroskodias, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
