### PR TITLE
magento/magento2#23386: Copy Service does not work properly for Entities which extends Data Object and implements ExtensibleDataInterface.

### PR DESCRIPTION
**Pull request by swnsma**
Provide fallback to copy Extension Attributes for classes which extends Data Object.

### Fixed Issues
1. magento/magento2#23386: Copy Service does not works properly for Entities which extends Data Object and implements ExtensibleDataInterface

### Manual testing scenarios
See in issue.

### CODE REVIEW

**Review by aleron75 — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-5352](https://jira.corp.magento.com/browse/ENGCOM-5352) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by aleron75** [comment]
@swnsma do you think that the unit test related to the updated class should be updated to reflect the change in fallback logic or is it already ok?

**Comment by swnsma** [comment]
Hi @aleron75,

I think the best is to cover this behavior with Integration Tests.
But due to this is no easy way to cover it due to Extension Attribute usage I prefer to skip it.

But I can try if you can share an example of how test can looks like.

E.G.
Source: Quote
Field: Extension Attribute -> Shipping Assignment
Target: ?
Field: Extension Attribute -> ?

**Comment by aleron75** [comment]
Hello @swnsma, I asked because I see there is already a unit test covering the class, it' `\Magento\Framework\DataObject\Test\Unit\CopyTest` so it would enough to take a look at that unit test and consider if it already covers the scenarios you extended or if it needs to be extended. That could be enough I think. Thanks!

**Comment by swnsma** [comment]
Hi @aleron75,
I have updated unit tests!

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-5352](https://jira.corp.magento.com/browse/ENGCOM-5352) has been created to process this Pull Request

**Pull request merged**
