### PR TITLE
Added declare(strict_type) statement as per the coding standard

### PR DESCRIPTION
**Pull request by manthandave**
Added a declare(strict_types=1); statement on the top of the file as per the defined coding standard.
### Description (*)

Added a strict types statement based on the coding standard - All new PHP files MUST have strict type mode enabled by starting with declare(strict_types=1);. All updated PHP files SHOULD have strict type mode enabled. PHP 
### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22254) <br/>All committers have signed the CLA.

**Comment by hostep** [comment]
@manthandave : please don't change the file permissions on these files:
> 100644 → 100755

Please revert these permissions back to 0644, thanks!

**Comment by manthandave** [comment]
> @manthandave : please don't change the file permissions on these files:
> 
> > 100644 → 100755
> 
> Please revert these permissions back to 0644, thanks!

Change Permissions back to 0644

**Review by orlangur — CHANGES_REQUESTED** [review]
@manthandave I don't think we need its added in two random files.

There should be some roadmap to add such in all files.

**Pull request closed without merging**
