### PR TITLE
[Fixed Compare Products section not showing in mobile view under 767px]

### PR DESCRIPTION
**Pull request by hitesh-wagento**
### Description (*)
Fixed Compare Products section not showing in mobile view under 767px

### Fixed Issues (if relevant)

1. magento/magento2#26416: Compare Products section not showing in mobile view under 767px

### Manual testing scenarios (*)

1. Go to the Category page
2. Add product to compare

### Expected result

expected

### Actual result

actual

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by ptylek — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-6622](https://jira.corp.magento.com/browse/ENGCOM-6622) has been created to process this Pull Request
:eight_spoked_asterisk: @ptylek, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by krzksz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-6622](https://jira.corp.magento.com/browse/ENGCOM-6622) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by hitesh-wagento** [comment]
Hello @magento-engcom-team 

Is there any update in this PR ?

Thanks

**Review by ptylek — APPROVED** [review]

**Comment by ptylek** [comment]
Please wait @hitesh-wagento, PR is in progress

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-6622](https://jira.corp.magento.com/browse/ENGCOM-6622) has been created to process this Pull Request

**Comment by hitesh-wagento** [comment]
Hello @magento-engcom-team

I have resolved conflicts

Thanks

**Comment by hitesh-wagento** [comment]
#MM20IN

**Comment by hitesh-wagento** [comment]
Hi @ptylek 

How can I resolve Functional Tests error?

**Comment by ptylek** [comment]
Hi @hitesh-wagento, there are some changes being done to functional tests and I don't think that they are related to this PR. Please hold until this is solved.

**Pull request merged**
