### PR TITLE
[26054-Do not duplicate SEO meta data when duplicating a product]

### PR DESCRIPTION
**Pull request by dasharath-wagento**
### Description (*)

we have add the below field will be empty after Product duplication from catalog Product Option
Meta title
Meta keywords
Meta description

### Fixed Issues (if relevant)

1. magento/magento2#26054: Do not duplicate SEO meta data when duplicating a product

### Manual testing scenarios (*)

1. Go to Backed -> Catalog -> Products -> Create a Duplicate From Existing Product & Review 
 You wold get a below field's values is empty
URL key => It is already generated with unique ID
Meta title => Should be empty
Meta keywords => Should be empty
Meta description => Should be empty

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento run all tests

**Comment by rogyar** [comment]
Hi @dasharath-wagento. Thank you for your contribution. Basically, I agree with the case of the original issue and the solution itself. By the final decision will be on the product owner.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-6785](https://jira.corp.magento.com/browse/ENGCOM-6785) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Golf** [comment]
Failed functional test not related to the changes in this PR, test fails on 2.4-develop branch.

**Comment by slavvka** [comment]
@dasharath-wagento Please resolve the conflicts before we can proceed with your PR

**Comment by engcom-Charlie** [comment]
Failed functional test not related to the changes in this PR test fails in 2.4-develop with MSI modules.
image

**Comment by rogyar** [comment]
Hi @slavvka, @engcom-Charlie. Does this PR still require an additional attention from the contributor/maintainer? 

Thank you.

**Comment by engcom-Charlie** [comment]
Hi, @slavvka I've resolved conflicts.

**Review by slavvka — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @slavvka, thank you for the review.
[ENGCOM-6785](https://jira.corp.magento.com/browse/ENGCOM-6785) has been created to process this Pull Request

**Pull request merged**
