### PR TITLE
Implement Asynchronous Operation status change based on a lookup key

### PR DESCRIPTION
**Pull request by nuzil**
Its a follow UP PR of this one: https://github.com/magento/magento2/pull/27916

Created cause of impossibility to manage another target branch

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by nuzil** [comment]
@magento run all tests

**Review by lenaorobei — APPROVED** [review]

**Comment by lenaorobei** [comment]
@nuzil please provide help our QA team with steps how to test this PR. Thanks.

**Comment by nuzil** [comment]
**QA**
- System has to have RabbitMQ connection configured
- Async of Async or Bulk request have to be executed
- consumer async.operatios.all have to be up and running

After executing of any Bulk / Async API requests, in Magento magento_operation table have to appear information about each operation of request with status == 4.

If fix for this bug works correctly, after consumer will pick up operation from queue, he have to change status for operation correctly.
So you have to see in magento_operation table status changed from default 4 to any other (depends from success of failure operation).

Screen Shot 2020-05-31 at 15 09 17

In addition following reporting API have to return correct data
https://devdocs.magento.com/guides/v2.3/rest/operation-status-endpoints.html

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Precondition:**

RabbitMQ connection configured

**Manual testing scenario:**
1. Install magento;
2. Run in console: `bin/magento queue:consumers:start async.operations.all`;
3. Go to API client ( **Talent API Tester** in my case);
4. Generate admin token;
5. Send **POST** request `/rest/default/async/bulk/V1/products` to create 2 products in my case (
one with correct data and another one with wrong "missing parameter **price**")
Screenshot from 2020-06-01 16-19-29

**Before:** :heavy_multiplication_x: In **magento_operation** table all operations have **4** status

Screenshot from 2020-06-01 16-23-13
Screenshot from 2020-06-01 16-24-54
screenshot_31


**After:** :heavy_check_mark:  In **magento_operation** table all operations have correct statuses: First product with the correct data has **1** status and second product with missing **price** parameter has **3** status

Screenshot from 2020-06-01 16-19-44
One product was succesfully created
Screenshot from 2020-06-01 16-20-24
screenshot_32

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@nuzil will be closed just after 2.4.0 release

**Comment by lenaorobei** [comment]
Was delivered to 2.4.0

**Pull request closed without merging**
