### PR TITLE
magento/magento2#7860: Invalid comment for the method __order in Mage…

### PR DESCRIPTION
**Pull request by mcspronko**
…nto\Sales\Model\Order\Payment.php

### CODE REVIEW

**Comment by okorshenko** [comment]
Hi @mcspronko 
Could you please resolve the code conflict so that we can process this RP?

**Comment by mcspronko** [comment]
@okorshenko please check updated version.

**Comment by okorshenko** [comment]
@mcspronko thank you. 
Does this PR include changes from https://github.com/magento/magento2/pull/8773 ?

**Comment by okorshenko** [comment]
Is a fix for magento/magento2#7860

**Comment by mcspronko** [comment]
@okorshenko yes, my mistake.

**Comment by okorshenko** [comment]
That is ok. Don't worry. We will accept it as is
Is a fix for https://github.com/magento/magento2/issues/8596

**Comment by ishakhsuvarov** [comment]
@mcspronko Thank you for contribution!

**Pull request merged**
