### PR TITLE
Fix acl.xml inconsistency. LoginAsCustomerAssistance

### LINKED ISSUE #30680: Magento upgrade 2.4.0 to 2.4.1 - Login As Customer acl.xml title attribute missing
### Preconditions (*)

1. Magento 2.4.0
2. LoginAsCustomer disabled
`'Magento_LoginAsCustomer' => 0,`
`'Magento_LoginAsCustomerAdminUi' => 0,`
`'Magento_LoginAsCustomerApi' => 0,`
`'Magento_LoginAsCustomerFrontendUi' => 0,`
`'Magento_LoginAsCustomerLog' => 0,`
`'Magento_LoginAsCustomerLogging' => 0,`
`'Magento_LoginAsCustomerPageCache' => 0,`
`'Magento_LoginAsCustomerQuote' => 0,`
`'Magento_LoginAsCustomerSales' => 0,`
`'Magento_LoginAsCustomerWebsiteRestriction' => 0,`

### Steps to reproduce (*)

1. Upgrade to Magento 2.4.1;
2. Try to access the admin.

### Expected result (*)

1. Acces to the admin dashboard with your user and password

### Actual result (*)

1. Blank page with this error
```
> Exception #0 (LogicException): Could not create an acl object: Invalid Document 
Element 'resource': The attribute 'title' is required but missing.
Line: 13
```

Screenshot from 2020-11-06 16-11-11

2. Only Magento_LoginAsCustomerAssistance enabled
`'Magento_LoginAsCustomer' => 0,`
`'Magento_LoginAsCustomerAdminUi' => 0,`
`'Magento_LoginAsCustomerApi' => 0,`
`'Magento_LoginAsCustomerAssistance' => 1,`
`'Magento_LoginAsCustomerFrontendUi' => 0,`
`'Magento_LoginAsCustomerLog' => 0,`
`'Magento_LoginAsCustomerLogging' => 0,`
`'Magento_LoginAsCustomerPageCache' => 0,`
`'Magento_LoginAsCustomerQuote' => 0,`
`'Magento_LoginAsCustomerSales' => 0,`
`'Magento_LoginAsCustomerWebsiteRestriction' => 0,`
3. When magento try yo merge all acl.xml the resource Magento_LoginAsCustomer::login stay without title attribute

### Workarround

Enable Magento_LoginAsCustomerAdminUi
or
Enable  Magento_LoginAsCustomerLog
or
Enable all Magento_LoginAsCustomer*
or
Disable Magento_LoginAsCustomerAssistance

- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

### PR DESCRIPTION
**Pull request by DiegoSana**
Fix acl.xml inconsistency when not all Magento_LoginAsCustomer* are enabled. See issue #30680

### Description (*)

Magento 2.4.1 instance.
When Magento_LoginAsCustomerAssistance is enable without Magento_LoginAsCustomerAdminUi or Magento_LoginAsCustomerLog enabled, the acl.xml generated by magento, leavs the resource Magento_LoginAsCustomer::login without title attribute. This produce a fatal error trying to access to the admin panel.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30680

### Manual testing scenarios (*)

1. Magento 2.4.1 instance
2. Magento_LoginAsCustomer* like this...
`'Magento_LoginAsCustomer' => 0,`
`'Magento_LoginAsCustomerAdminUi' => 0,`
`'Magento_LoginAsCustomerApi' => 0,`
`'Magento_LoginAsCustomerAssistance' => 1,`
`'Magento_LoginAsCustomerFrontendUi' => 0,`
`'Magento_LoginAsCustomerLog' => 0,`
`'Magento_LoginAsCustomerLogging' => 0,`
`'Magento_LoginAsCustomerPageCache' => 0,`
`'Magento_LoginAsCustomerQuote' => 0,`
`'Magento_LoginAsCustomerSales' => 0,`
`'Magento_LoginAsCustomerWebsiteRestriction' => 0,`
3. Login into the admin

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by DiegoSana** [comment]
@magento give me test instance

**Comment by DiegoSana** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @DiegoSana,
Could you sign Adobe CLA, otherwise we can't accept your PR?

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

**Review by sidolov — CHANGES_REQUESTED** [review]
Please, address requested changes

**Comment by DiegoSana** [comment]
@magento run Integration Tests

**Comment by DiegoSana** [comment]
> Hi @DiegoSana,
> Could you sign Adobe CLA, otherwise we can't accept your PR?

done it

**Comment by DiegoSana** [comment]
@sidolov is there something else that i need to do?
A few minutes ago all checka was green.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @DiegoSana,
Could you review and fix failing tests?

**Comment by DiegoSana** [comment]
@magento run all tests

**Comment by DiegoSana** [comment]
@magento run Functional Tests CE

**Comment by DiegoSana** [comment]
@magento run Functional Tests CE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]

**Comment by DiegoSana** [comment]
@magento run Functional Tests B2B

**Comment by DiegoSana** [comment]
@magento run Functional Tests B2B

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8405](https://jira.corp.magento.com/browse/ENGCOM-8405) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@DiegoSana thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Magento 2.4.0
2. LoginAsCustomer disabled
`'Magento_LoginAsCustomer' => 0,`
`'Magento_LoginAsCustomerAdminUi' => 0,`
`'Magento_LoginAsCustomerApi' => 0,`
`'Magento_LoginAsCustomerFrontendUi' => 0,`
`'Magento_LoginAsCustomerLog' => 0,`
`'Magento_LoginAsCustomerLogging' => 0,`
`'Magento_LoginAsCustomerPageCache' => 0,`
`'Magento_LoginAsCustomerQuote' => 0,`
`'Magento_LoginAsCustomerSales' => 0,`
`'Magento_LoginAsCustomerWebsiteRestriction' => 0,`

**Manual testing scenario:**

1. Upgrade to Magento 2.4.1;
2. Try to access to the admin;

**Before:** :heavy_multiplication_x: 

``` 
Exception #0 (LogicException): Could not create an acl object: Invalid Document 
Element 'resource': The attribute 'title' is required but missing.
Line: 13
```
Screenshot from 2020-11-06 16-11-11

**After:** :heavy_check_mark: Acces to the admin dashboard with your user and password

Screenshot from 2020-11-09 09-59-56

**Pull request merged**
