### PR TITLE
Experius 2.3 patch catalog flat

### PR DESCRIPTION
**Pull request by lewisvoncken**
### Description (*)

When the index type product flat is set to 'On Schedule' disabled products were not removed from the table until a full reindex.

### Manual testing scenarios (*)

1. Set the Flat Product to `On Schedule`
2. Disable the Test Product
3. Run the `indexer_update_all_views` cron with magerun2 or make sure the cron is running
4. As a result the product is still in the flat table
5. Apply changes
6. Enable the Test Product
7. Disable the Test Product
8. Run the `indexer_update_all_views` cron with magerun2 or make sure the cron is running
9. As a result the product is removed from the flat table

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@lewisvoncken,
Your changes looks good to me. Could you cover your changes with tests and fix static test failures?

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

**Comment by engcom-Charlie** [comment]
Hi @ihor-sviziev, I'll take care of the test coverage.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7019](https://jira.corp.magento.com/browse/ENGCOM-7019) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
