### PR TITLE
laminas/laminas-view updated to ~2.12.0  #31784

### PR DESCRIPTION
**Pull request by khrystynastolbova**
### Description (*)
Update laminas/laminas-view dependency from version "~2.11.2" to "~2.12.0"

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/520

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31784

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by coderimus** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run Integration Tests,WebAPI Tests

**Review by sivaschenko — APPROVED** [review]

**Pull request merged**
