### PR TITLE
Backport of PR #19679 - Implement Module Annotation

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)
Original PR https://github.com/magento/magento2/pull/19679 which would be great to have on all currently supported Magento branches.

### Fixed Issues (if relevant)
1. magento/magento2#19575

### Manual testing scenarios (*)

1. same as original

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by orlangur — APPROVED** [review]
Not sure if still acceptable for 2.2, but LGTM

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-5456](https://jira.corp.magento.com/browse/ENGCOM-5456) has been created to process this Pull Request
:eight_spoked_asterisk: @orlangur, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by VladimirZaets** [comment]
Hi @fooman.
The next 2.2 release will be the last of functional releases.
Due to it, we are closing 2.2-develop for contribution.
Thanks for collaboration.

**Comment by fooman** [comment]
@VladimirZaets if it is the last release it would be even better to have this change in I would say.

Also the change is not functional it's only a change for the integration testing framework. This change would allow extension developers to run integration tests across the latest 2.2 and 2.3 branch with this functionality.

Any chance this can be reconsidered?

**Pull request closed without merging**
