### PR TITLE
Invoice Sales Email not send

### PR DESCRIPTION
**Pull request by nadeefit6**
### Description (*)
send invoice email when orders are placed through paypal express.

### Fixed Issues (if relevant)

1. magento/magento2#13466: Invoice Sales Email not send
2. ...

### Manual testing scenarios (*)

1. Enable Paypal Express Checkout
2. Place Order using Paypal Express as Payment method
3. Check Invoice Email

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21930) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @nadeefit6. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
Hi @nadeefit6. Thank you for your contribution. According to the [Contributors Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) a solution needs to be delivered into 2.3-develop branch before it can be ported back to 2.2-develop.
Please, create a new pull request to the 2.3-develop branch and rename the current one as "backport".
Also, in the new PR, please, provide more information on how exactly your solution fixes the problem and why the change is only about guest invoice and order template.
Thank you.

**Comment by sidolov** [comment]
Hi @nadeefit6 , will you continue progress? Please, create pull request with the same changes for 2.3-develop

**Comment by sidolov** [comment]
@nadeefit6 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
