### PR TITLE
Fixed 18918 Asterisk sign display twice

### PR DESCRIPTION
**Pull request by suryakant-krish**
### Description (*)
1. Fixed Asterisk sign display twice.

### Fixed Issues (if relevant)

1. magento/magento2#18918: Asterisk sign display twice #18918

### Manual testing scenarios (*)

1. Check screenshot.
http://prntscr.com/lbpcto
http://prntscr.com/lbpcl6

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3324](https://jira.corp.magento.com/browse/ENGCOM-3324) has been created to process this Pull Request

**Comment by VladimirZaets** [comment]
Hi @suryakant-krish. We tried to apply your fix, but the problem still reproduces.

**Comment by suryakant-krish** [comment]
Please ignore this commit 7365f5f

I have added new commit c870f0d in this commit issue is fixed.

**Comment by suryakant-krish** [comment]
Can you please check I have commited all my latest changes.

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.

**Pull request merged**
