### PR TITLE
[MFTF]  Add new  AdminOpenIndexManagementPageActionGroup

### LINKED ISSUE #29825: [Issue] [MFTF]  Add new  AdminOpenIndexManagementPageActionGroup
This issue is automatically created based on existing pull request: magento/magento2#29822: [MFTF]  Add new  AdminOpenIndexManagementPageActionGroup

---------
This PR add new `AdminOpenIndexManagementPageActionGroup` for opening Index Management Page

### PR DESCRIPTION
**Pull request by Usik2203**
This PR add new `AdminOpenIndexManagementPageActionGroup` for opening Index Management Page 

### Resolved issues:
1. [x] resolves magento/magento2#29825: [MFTF]  Add new  AdminOpenIndexManagementPageActionGroup

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

Failed tests **are not related** with the changes and are actually flaky tests from Magento.

**Comment by Usik2203** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by sidolov — APPROVED** [review]

**Review by lbajsarowicz — APPROVED** [review]
✔️  Also green light from my side now.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-8123](https://jira.corp.magento.com/browse/ENGCOM-8123) has been created to process this Pull Request

**Pull request merged**
