### PR TITLE
Resolved Cannot create shipment for remaining items

### LINKED ISSUE #27141: Cannot create shipment for remaining items
### Preconditions (*)

1. Magento Open Source 2.3.3

### Steps to reproduce (*)

1. Create an order, where at least one product has a Quantity of 2. 
    - Example of order items : - 3 x product_1
                                              - 1 x product_2
                                              - 1 x product_3

2. Create an invoice, shipment and creditmemo for:
                                             -  2 x product_1 
                                             - 1 x product_2 
                                             - 1 x product_3

Example screenshot:
bug-m2

### Expected result (*)

1. It is possible to create a shipment for the remaining item.

### Actual result (*)

1. The Ship button disappeared, making it impossible to create a shipment for the remaining item.
bug-m

### PR DESCRIPTION
**Pull request by niravkrish**
### Steps to Reproduce (*)
Create an order, where at least one product has a Quantity of 2.

Example of order items : - 3 x product_1
- 1 x product_2
- 1 x product_3
Create an invoice, shipment and creditmemo for:
- 2 x product_1
- 1 x product_2
- 1 x product_3

### Fixed Issues (if relevant)

1. magento/magento2#27141: Cannot create shipment for remaining items

### Manual testing scenarios (*)

1. Manual testing

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Hi @niravkrish,

Thanks for your contribution. Please address builds failures and consider adding some tests to verify expected behaviour.

**Comment by niravkrish** [comment]
> Hi @niravkrish,
> 
> Thanks for your contribution. Please address builds failures and consider adding some tests to verify expected behaviour.

Hello @lenaorobei 
I have resolved unit testing.
can you please assist me how to solve rest of the failed test cases.
I am not able to figure out the failed test cases.

Thank you

**Comment by niravkrish** [comment]
I have added this functionality.
please check below PR.
https://github.com/magento/magento2/pull/27461

**Comment by ihor-sviziev** [comment]
@niravkrish I just fixed static test, looks like failing functional tests were false positives. I'll review this PR again when all tests will be finished

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved 

Failing tests looks not related to changes from this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7526](https://jira.corp.magento.com/browse/ENGCOM-7526) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**
1. Create Order with items (for ex.);

- _Product 1_ - 3 pcs.;
- _Product 2_ - 1 pcs.;
- _Product 3_ - 1 pcs.;

2. Create an invoice, shipment and credit memo for:

- _Product 1_ - 2 pcs.;
- _Product 2_ - 1 pcs.;
- _Product 3_ - 1 pcs.;

3. Try to create a shipment for remaining items;

**Before:** :heavy_multiplication_x: The **Ship** button disappeared

screenshot_19999

**After:** :heavy_check_mark: The **Ship** button appeared and it became possible to create a shipment for remaining items

**Comment by engcom-Charlie** [comment]
Failed functional tests not related to the changes in this PR

**Comment by slavvka** [comment]
@niravkrish @ihor-sviziev needs to be eretested after PHP 7.4 support is merged

**Review by ihor-sviziev — APPROVED** [review]
Failed tests not related to changes from this PR.
Approved ✔

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7526](https://jira.corp.magento.com/browse/ENGCOM-7526) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**
1. Create Order with items (for example);

- _Product 1_ - 3 pcs.;
- _Product 2_ - 1 pcs.;
- _Product 3_ - 1 pcs.;

2. Create an invoice, shipment and credit memo for:

- _Product 1_ - 2 pcs.;
- _Product 2_ - 1 pcs.;
- _Product 3_ - 1 pcs.;

3. Try to create a shipment for remaining items;

**Actual Result:** 

:heavy_check_mark: The **Ship** button appeared and it became possible to create a shipment for remaining items

**Comment by engcom-Charlie** [comment]
Failed test not related to changes from this PR.

**Pull request merged**
