### PR TITLE
Updating `squizlabs/php_codesniffer` composer dependency to the latest version

### LINKED ISSUE #33832: Update squizlabs/php_codesniffer, ramsey/uuid,  elasticsearch/elasticsearch composer dependencies to the latest versions
Update the following composer dependencies to the latest versions:
* squizlabs/php_codesniffer (<sub>3.6.0)
* ramsey/uuid (</sub>4.2.0)
* elasticsearch/elasticsearch (~7.14.0)

What needs to be done:
 - Review and list the backwards-incompatible changes of the new version (link the migration guide if available)
 - Update the dependency constraint
 - Perform the testing of affected areas after update (use automated tests if available)

### PR DESCRIPTION
**Pull request by eduard13**
### Description (*)
This PR aims to update the following composer dependencies to their latest versions:
- squizlabs/php_codesniffer (~3.6.0)

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/592

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33832

### Manual testing scenarios (*)
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by eduard13** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
Please resolve conflict

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
The Currency Converter Free API Server is down again
currency-converter-api-server-down

**Review by andrewbess — APPROVED** [review]

**Pull request merged**
