### PR TITLE
Fix error in graphql query

### LINKED ISSUE #36117: Fatal when using GraphQl query
### Preconditions and environment

- Magento 2.4.5
- Default Magento ElasticSearch7
- Not empty database prefix, for example "pref"

### Steps to reproduce

1. Run this graphQl query:
```
query {
  products(filter: {category_id: {eq: "2"}}, sort: {price:ASC}, currentPage: 1) {
    items {
      ...productAttributesForListing
      ... on ConfigurableProduct {
        variants {
          __typename
        }
      }
    }
  }
}

fragment productAttributesForListing on ProductInterface {
  categories {
    breadcrumbs {
      category_name
    }
  }
}
```

### Expected result

Results without error:
image

### Actual result

Fatal Error: 
image

### Additional information

This error happened because the subquery
`SELECT 1 FROM store_group WHERE cat_index.category_id IN (store_group.root_category_id`
 is missing a table prefix for `store_group`
 
 See `\Magento\CatalogGraphQl\Model\Resolver\Product\ProductCategories::getCategoryIdsByProduct`

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by DmitrySamushchenko**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#36117

### Manual testing scenarios (*)

Run this GraphQl query:
```
query {
  products(filter: {category_id: {eq: "2"}}, sort: {price:ASC}, currentPage: 1) {
    items {
      ...productAttributesForListing
      ... on ConfigurableProduct {
        variants {
          __typename
        }
      }
    }
  }
}

fragment productAttributesForListing on ProductInterface {
  categories {
    breadcrumbs {
      category_name
    }
  }
}
```

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Den4ik** [comment]
@magento run all tests

**Review by Den4ik — APPROVED** [review]
✅ Approved due to low risk and transparent changes.

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B ,Functional Tests EE , Integration Tests , Static Tests

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B ,Functional Tests EE , Integration Tests , Static Tests

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B ,Functional Tests EE , Integration Tests , Static Tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

- Install fresh Magento `2.4-develop`
- Create database with prefix.

**Manual testing scenario:**
Run this graphQl query:
```
query {
  products(filter: {category_id: {eq: "2"}}, sort: {price:ASC}, currentPage: 1) {
    items {
      ...productAttributesForListing
      ... on ConfigurableProduct {
        variants {
          __typename
        }
      }
    }
  }
}

fragment productAttributesForListing on ProductInterface {
  categories {
    breadcrumbs {
      category_name
    }
  }
}
```
**Before:** :heavy_multiplication_x: Getting SQL state error in logs as well as internal server error in response.
Screenshot 2022-09-16 at 3 19 02 PM

before

**After:** :heavy_check_mark:  No error.
after


Checks are failed ,hence, moving it to Extended testing.

Thanks

**Comment by engcom-Lima** [comment]
Looking like bot had moved this ticket to ready for testing . Hence, moving back to extended testing.

**Comment by engcom-Hotel** [comment]
The related issue has already been fixed and merged with the development branch. Please refer the below comment for more information:

https://github.com/magento/magento2/issues/36117#issuecomment-1352562750

Hence closing this PR.

thanks

**Pull request closed without merging**
