### PR TITLE
[Backport] Fix issue 21126 : Import design break issue resolved

### PR DESCRIPTION
**Pull request by SyntaxKay**
### Original Pull Request 
 https://github.com/magento/magento2/pull/21128

### Description (*)

Backend Import behavior design break
### Fixed Issues (if relevant)

1.magento/magento2#21126:  Import design break issue resolved

### Manual testing scenarios (*)

1.Login to backend > system > import
2.select any > Entity Type and without selecting any option click on check data

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-23611.instances.magento-community.engineering).
Admin access: [https://pr-23611.instances.magento-community.engineering/admin](https://pr-23611.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rogyar** [comment]
Hi @speedy008. Thank you for your contribution. Unfortunately, I cannot reproduce this issue on 2.2-develop branch. There's no tooltip in 2.2.x.

**Comment by VladimirZaets** [comment]
Hi @speedy008. The branch `2.2-develop` will be closed for contribution from **July 15, 2019**. Please finish all your Pull Requests till this date, otherwise, they will be closed.
Thanks for collaboration.

**Comment by Ctucker9233** [comment]
@VladimirZaets does that mean that 2.2 is EOL?

**Comment by VladimirZaets** [comment]
@Ctucker9233 yes

**Comment by orlangur** [comment]
Closing as this is not an issue for `2.2-develop`.

**Pull request closed without merging**
