### PR TITLE
#23346: 'Test Connection' button is over-spanned

### PR DESCRIPTION
**Pull request by konarshankar07**
### Fixed Issues (if relevant)

1. magento/magento2#23346: 'Test Connection' button is over-spanned

### Manual testing scenarios (*)

1. Navigate to Stores > Settings > Configuration > Catalog > Catalog > Catalog Search
2. Set Search Engine to any Elastic...
3. Find the Test Connection button and inspect it
4. Extra span has been removed

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by orlangur — APPROVED** [review]

**Comment by orlangur** [comment]
@konarshankar07 does it look the same way now?

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-5342](https://jira.corp.magento.com/browse/ENGCOM-5342) has been created to process this Pull Request
:eight_spoked_asterisk: @orlangur, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by konarshankar07** [comment]
Hello @orlangur
Sorry, I didn't get you.

**Comment by orlangur** [comment]
@konarshankar07 I mean after we change HTML markup do we need to change CSS styles also or it still looks the same?

**Comment by konarshankar07** [comment]
@orlangur 

It looks the same. Here is the screenshot
image

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
