### PR TITLE
[2.3-develop] [Forwardport Unit test] magento/magento2#17833:  Child theme does not inherit translations fr…

### PR DESCRIPTION
**Pull request by vpodorozh**
…om parent theme

- forward port unit tests from 2.2-develop branch

### Description ( #17833 )
Forward port unit test for `\Magento\Framework\Translate` from `2.2-develop` branch.
**Note:** current PR was created from this PR #19018 , changes were not submitted into #19018 because it was already accepted and merged.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @vpodorozh. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by vpodorozh** [comment]
Hey guys - what should I do in case Travis-ci has failed on Integration test due to: `The job exceeded the maximum time limit for jobs, and has been terminated.` ?
Just skip it?

**Comment by rogyar** [comment]
Yes, just skip it :)

**Comment by magento-engcom-team** [comment]
Hi @vpodorozh. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
