### PR TITLE
issue/26526 Fix orderRepository does not check if there are no extens…

### LINKED ISSUE #26526: orderRepository does not check if there are no extensionAttributes
### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Have an order which has no extensionAttributes
2. Try to load the order using orderRepository by `\Magento\Sales\Api\OrderRepositoryInterface::get`

### Expected result (*)

1. Order is loaded 

### Actual result (*)
1. Error: `Call to a member function setAppliedTaxes() on null`

Screenshot from 2020-09-14 10-07-52

### PR DESCRIPTION
**Pull request by PascalBrouwers**
…ionAttributes

### Fixed Issues (if relevant)

1. Fixes magento/magento2#26526: orderRepository does not check if there are no extensionAttributes

### Manual testing scenarios (*)

1. Have an order which has no extensionAttributes
2. Try to load the order using orderRepository

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — CHANGES_REQUESTED** [review]
@PascalBrouwers nice catch! Could you please cover the changes with any type of automated tests?

**Comment by engcom-Charlie** [comment]
Hi @PascalBrouwers can you please look at https://github.com/magento/magento2/issues/26526#issuecomment-681840513?
Thank you.

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8134](https://jira.corp.magento.com/browse/ENGCOM-8134) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Have an order which has no extensionAttributes
2. Try to load the order using orderRepository

**Before:** :heavy_multiplication_x: `Error: Call to a member function setAppliedTaxes() on null` in the **system.log** file

Screenshot from 2020-09-14 10-07-52

**After:** :heavy_check_mark: The order is successfully loaded

Screenshot from 2020-09-14 11-18-35

**Pull request merged**
