### PR TITLE
Make "validate-email" error string translatable - Update validation.js

### PR DESCRIPTION
**Pull request by Rickywils**
Make "validate-email" error string translatable

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=6140) <br/>All committers have signed the CLA.

**Comment by vkorotun** [comment]
Fixed in mainline within another PR.

**Comment by Ctucker9233** [comment]
@vkorotun What's the number of that other PR?

**Comment by AntonEvers** [comment]
@Ctucker9233 it's https://github.com/magento/magento2/pull/5725

**Comment by Ctucker9233** [comment]
@vkorotun Is this PR going to be included in 2.1.3?

**Pull request closed without merging**
