### PR TITLE
#17926 Fixing ui-component field validation error not opening accordion tab that owns the field.

### PR DESCRIPTION
**Pull request by FlaviuParau**
The issue of event not triggering properly on every call causes issues with Form Validation 'error' events where certain errors don't get properly highlighted when error message is not set properly or does not change. In case rest of the UI state around the error has been changed, the element that caused the actual error, no longer gets highlighted correctly.

Issue reported #17926

navigate to /admin and log in
[admin] Navigate to Content >> Pages
[admin] edit any page
[admin] open "Page in Websites" accordion
[admin] un-select all stores (hold down CMD on Mac and CTRL on Windows and RMB the items)
[admin] close the accordion
[admin] use "Save and Continue" or "Save" to save the page

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18827) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18827) before we can accept your contribution.<br/><hr/>**flaviublugento** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by magento-engcom-team** [comment]
Hi @FlaviuParau. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by FlaviuParau** [comment]
Hi, I already added 2 emails for this, but doesn't seems to change anything.

**Comment by orlangur** [comment]
```
Author: flaviublugento <flaviu.parau@yblugento.ro>
Author: flaviublugento <flaviu.parau@yblugento.ro>
```

@FlaviuParau at least first and last commits are made with the same email. Try to make a commit with correct email squashing all the changes and then force push.

**Comment by slavvka** [comment]
@FlaviuParau thank you for the contribution. Please sign License Agreement that we could process your PR further. You can do it by clicking the [link](https://cla.dev.magento.com/magento/magento2?pullRequest=18827)

**Comment by VladimirZaets** [comment]
Hi @FlaviuParau, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Pull request closed without merging**
