### PR TITLE
[Forwardport]Fixed - Default tax region/state appears in customer & order data

### PR DESCRIPTION
**Pull request by nirav-kadiya**
### Original Pull Request 

#18857 

### Description (*)
Fixed issue of default tax region/state appears in customer & order data

### Fixed Issues (if relevant)

1. magento/magento2#16684: Default tax region/state appears in customer & order data

### Manual testing scenarios (*)
1. Set a default tax region in Stores > Configuration > Sales > Tax
2. Complete an order

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ssp58bleuciel. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by nuzil — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
@ssp58bleuciel thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [new Magento instance](https://pr-19387.instances.magento-community.engineering).
Admin access: [https://pr-19387.instances.magento-community.engineering/admin](https://pr-19387.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sivaschenko** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [Magento instance](https://i-19387-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19387-2-3-develop.instances.magento-community.engineering/admin](https://i-19387-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sivaschenko** [comment]
This fix is changing the default applied tax on checkout when a region is not selected. Now instead of tax for default region - tax for a country ('*' region) will be applied.

**Comment by magento-engcom-team** [comment]
Hi @ssp58bleuciel. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
