### PR TITLE
Make the title of the "Show Password" checkbox translatable

### LINKED ISSUE #34857: [Issue] Make the title of the "Show Password" checkbox translatable
This issue is automatically created based on existing pull request: magento/magento2#34370: Make the title of the "Show Password" checkbox translatable

---------

### Description (*)

The title of the "Show Password" checkbox (Customer Login, Customer Registration, Customer Edit (Change Password section), Customer Set New Password) is not translatable. This pull request makes the title translatable.

### Manual testing scenarios (*)

1. Create an i18n translation for the string "Show Password".
2. Access the above mentioned pages.
3. Hover over the checkbox to see the title.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by densen45**
### Description (*)

The title of the "Show Password" checkbox (Customer Login, Customer Registration, Customer Edit (Change Password section), Customer Set New Password) is not translatable. This pull request makes the title translatable.

### Manual testing scenarios (*)

1. Create an i18n translation for the string "Show Password".
2. Access the above mentioned pages.
3. Hover over the checkbox to see the title.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#34857: Make the title of the "Show Password" checkbox translatable

### CODE REVIEW

**Comment by densen45** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Review by Den4ik — APPROVED** [review]

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
As per the above-comment the QA not passed, and so _changes requested_
Thanks

**Comment by Den4ik** [comment]
@engcom-Alfa Could you please check it again because and look at browser console. Looks like you have some problems with local installation and deploy because checkbox work correctly on instances provided by `magento` command.

2021-11-22-16-17-37@2x

**Comment by engcom-Alfa** [comment]
> @engcom-Alfa Could you please check it again because and look at browser console. Looks like you have some problems with local installation and deploy because checkbox work correctly on instances provided by `magento` command.
> 
> 2021-11-22-16-17-37@2x

Agreed @Den4ik , Thanks for the reply! But As I checked, the checkbox is getting invisible in case of fr_FR language.
I can see the checkbox visible with default english language!
Additional Info: I have a default store(_local.magento2.com_) set with English language and additionally French store(_local.magento2.fr_) set with French language.
So default store front end login displayed with _Show Password_ checkbox, whereas French store frontend login page is **not** displayed with _Show Password_ checkbox!
Screenshot 2021-11-22 at 7 14 22 PM

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
@engcom-Charlie Can you also take a look on this once please!

**Comment by Den4ik** [comment]
It could be another issue related to multistore

**Comment by densen45** [comment]
Hey @engcom-Alfa, I can't understand why the issue you describe is blocking this PR. Please help me, maybe I'm missing something.
The goal of this PR was to make the checkbox title translatable, not to fix the issue that the checkbox and the title are not displayed at all in some languages/multi language setups (before your comment I was not aware of this issue). For sure, that is a pity and should be fixed as well but I would suggest in another issue/PR.

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by Den4ik** [comment]
I don't see any problems with this PR and preferrer move it to merge in progress

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9266](https://jira.corp.magento.com/browse/ENGCOM-9266) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Have Magento latest installed.
2. Make sure to configure other language than English using the [GUIDE](https://github.com/mageplaza/magento-2-dutch-language-pack).
3. Make sure to have the relevant language .csv file saved into the <Magento root folder>/app/i18n directory.
4. Make sure to have the translated text of "Show Password" in the csv file.


**Manual testing scenario:**

1. Admin > Store > Configure > Locale Options > Set the Locale to Other language that is configured as per pre conditions

2. Open the Magento front end and Navigate to Login page.


**Before:** :heavy_multiplication_x: "Show Password" text was not getting translated to preferred language

Screenshot 2021-12-21 at 4 21 28 PM



**After:** :heavy_check_mark: "Show Password" text is getting translated to preferred language

Screenshot 2021-12-21 at 4 55 05 PM



Since it is specific case relavant text translation, there is no additional testing is required as part of regression.

**Pull request merged**
