### PR TITLE
Fix #17579 Typo in Gallery.php

### LINKED ISSUE #17579: Typo in vendor/magento/module-catalog/Block/Adminhtml/Product/Helper/Form/Gallery.php
Typo in file vendor/magento/module-catalog/Block/Adminhtml/Product/Helper/Form/Gallery.php
setMegiaGallery should be setMediaGallery on line 122

### Preconditions

1. Magento 2.2.4

### Steps to reproduce

1. Observe vendor/magento/module-catalog/Block/Adminhtml/Product/Helper/Form/Gallery.php

### Expected result

1. setMediaGallery method called in line 122

### Actual result

1. setMe**g**iaGallery method called in line 122

### PR DESCRIPTION
**Pull request by Spaggel**
### Description
This PR fixes a typo in Gallery.php, setMegiaGallery should be setMediaGallery.
### Fixed issue
see #17579

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Spaggel. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-2816](https://jira.corp.magento.com/browse/ENGCOM-2816) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@Spaggel thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by Spaggel** [comment]
@magento-engcom-team Done! Question: can you add me to the partner-guapa developer list so the partner-contribution labels get added? Thanks!

**Comment by sidolov** [comment]
Hi @Spaggel , please, contact engcom@magento.com with your corporate email and we will add your account to the team. 
Thank you!

**Comment by Spaggel** [comment]
@sidolov I accidentally pushed another commit to the same branch, I was going to open a new PR for it.. how should we proceed?

**Comment by sidolov** [comment]
Hi @Spaggel , just reset to the first commit and force push the branch and we will proceed with current PR

**Comment by Spaggel** [comment]
@sidolov done

**Comment by magento-engcom-team** [comment]
Hi @Spaggel. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Pull request merged**
