### PR TITLE
Fixed layout for customer authentication popup

### PR DESCRIPTION
**Pull request by rogyar**
Removed an unnecessary extra closing div tag in authentication popup layout. Nothing critical but might cause layout issues on some browsers.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=6280) <br/>All committers have signed the CLA.

**Comment by vasiliyseleznev** [comment]
Thanks for you contribution!
Internal ticket: MAGETWO-59867

**Comment by Ctucker9233** [comment]
@mmansoorebay @sevos1984 Will this PR Be included in 2.1.3?

**Comment by Ctucker9233** [comment]
Still not fixed in 2.1.10...

**Pull request merged**
