### PR TITLE
Fix bug on Eav ReadHandler (entity manager)

### PR DESCRIPTION
**Pull request by spipu**
Bug on MySQL "UNION ALL" usage : 

http://dev.mysql.com/doc/refman/5.6/en/union.html

> use of ORDER BY for individual SELECT statements implies nothing about the order in which the rows appear in the final result because UNION by default produces an unordered set of rows.

It is necessary to add a global "ORDER BY" on the global query (after UNION).

Another pb was the order : it must be ASC and not DESC because it take first the value for store_id 0, and then if it exist, it override it with the value for the store_id 1.

The pb is that you can only view this bug if you implement a new type of EAV object, that has only attributes in a specific BACKEND_TYPE (=> it does not make any UNION).

On products / categories / ... the bug does not appear because there is more than 1 backend type (varchar, int, ...) => the "order by" was not taking in account, and it was ordering by default on the value_id field.

My fix takes also in account eav models that does not use context.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=6646) <br/>All committers have signed the CLA.

**Comment by vrann** [comment]
@spipu can you please update your code with the latest develop branch?

**Comment by okorshenko** [comment]
@spipu can you please update your code with the latest develop branch?

**Comment by spipu** [comment]
updated

**Comment by okorshenko** [comment]
HI @spipu
Could you please cover your fix with integration test? This is a very low-level layer that must be covered with the tests.

**Comment by okorshenko** [comment]
Hi @spipu could you please review my previous comment?

**Comment by spipu** [comment]
I am in vacancy. No computer before 3 weeks

**Comment by okorshenko** [comment]
Hi @spipu 
Sure. Take your time. Have a good vacation! I'm closing this RP for now. Please, reopen it once ready. Thank you

**Pull request closed without merging**
