### PR TITLE
Add Tracking Parameters to Varnish Configuration

### LINKED ISSUE #35227: The Varnish configs do not strip Klaviyo marketing parameter
### Preconditions (*)
1. Any Magento version that includes a suggested Varnish VCL config.
2. Using Varnish along with a VCL that is included with Magento.
3. Usage of Klaviyo's marketing email services/modules.

### Steps to reproduce (*)
1. Use a VCL that is included with Magento.
2. Send a marketing email via Klaviyo.
3. Watch varnishlog.
4. Visit the site using a link that is included in a Klaviyo-generated email.
5. Visit the site using a similar link that does not include the `_kx` query parameter.
6. Compare the results shown by varnishlog.

### Expected result (*)
1. The `_kx` parameter should be stripped, ensuring that visitors using links with the `_kx` parameter are served the cached version of the requested page.

### Actual result (*)
1. Varnish does not strip the parameter, and since the value is unique per visitor, those requests will not match any hashes in Varnish's cache.
2. This also results in additional PHP load due to the request needing to be processed by Magento.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### LINKED ISSUE #38298: Varnish configuration does not exclude all marketing parameters
### Preconditions and environment

- Magento version: 2.4.6-p3

### Steps to reproduce

Export the varnish configuration in the Magento admin and search for the part in the generated VCL file to determine that not all marketing parameters are excluded. 

### Expected result

All marketing parameters are excluded

### Actual result

Common marketing parameters are not excluded for instance: 

- gad_source (https://support.google.com/google-ads/answer/13327296?hl=en ) 
- srsltid (https://support.google.com/analytics/answer/11479699?hl=en ) 
- msclkid (https://help.ads.microsoft.com/apex/index/3/en/60000 )

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by sprankhub**
### Description (*)
Add additional tracking parameters to the Varnish configuration, so that the same page will be cached independent of those tracking parameters.

### Related Pull Requests
https://github.com/magento/magento2/pull/38299
https://github.com/magento/magento2/pull/38302

### Fixed Issues (if relevant)
1. Fixes magento/magento2#38298
2. Fixes https://github.com/magento/magento2/issues/35227

### Manual testing scenarios (*)
1. Open the Magento backend
3. Open Stores > Configuration > Advanced > System > Full Page Cache
4. Export the Varnish configuration
5. Make sure the new tracking parameters are included

### Questions or comments
Previous PRs have not been merged and not been updated. Hence, here is another try to get this over the line.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sprankhub** [comment]
If you have doubts regarding the parameters, check https://github.com/mpchadwick/tracking-query-params-registry/blob/master/_data/params.csv, where all of them are mentioned including a reference.

**Comment by hostep** [comment]
It would be good to handle this PR together with https://github.com/magento/magento2/pull/35228 (`_kx` is also referenced in that csv file)

**Comment by sprankhub** [comment]
Thanks for the feedback, @hostep. I guess it would be easiest if I include the parameter here in this PR. Or should I try to cherry-pick that other commit to keep the author information? What do you think?

**Comment by hostep** [comment]
Yeah cherry-picking is probably the best, this PR has a lot more upvotes than the other and probably will be picked up sooner than the other, so having everything fixed in one PR is probably the fastest way to get everything in the core.

**Comment by sprankhub** [comment]
I now cherry-picked the changes from https://github.com/magento/magento2/pull/35228 and also applied the change to the Varnish 7 VCL.

**Review by bgorski — APPROVED** [review]
Great contribution, thanks! I don't think any tests are required in this case, since it's only about vcl file modifications, not about the core platform logic.

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi @sprankhub ,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Open the Magento backend
- Open Stores > Configuration > Advanced > System > Full Page Cache
- Export the Varnish configuration
- Make sure the new tracking parameters are included

**Before:** :heavy_multiplication_x: 


Screenshot 2024-10-16 at 10 11 00



**After:** :heavy_check_mark: 

Screenshot 2024-10-16 at 10 25 35



Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by Gelmo** [comment]
Cheers

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
The Functional EE test failures are not consistent in recent 2 builds on the same code. The tests are neither part of PR nor failing because of its changes, seems to be flaky.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39188/4651151eb184b68de3ad372419f1a23d/Functional/allure-report-ee/index.html#categories

image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39188/e54a1bee28f120d2e13548854311a981/Functional/allure-report-ee/index.html#categories

image

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
Few of the functional B2B test failures are not consistent and one of them is a known issue. Hence moving this PR in Merge in Progress now.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39188/924e8c6185564914f96a7e10bd139e31/Functional/allure-report-b2b/index.html#categories

image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39188/25d25e585bd56bfa9186d36dc9d7a0fa/Functional/allure-report-b2b/index.html#categories

image


**Known issues:**
[ACP2E-3314](https://jira.corp.adobe.com/browse/ACP2E-3314) - StorefrontPrintListItemsFromRequisitionListTest
[ACQE-6402](https://jira.corp.adobe.com/browse/ACQE-6402) - StorefrontVirtualQuotePurchaseOrderTest

**Pull request merged**
