### PR TITLE
Magento email template responsive in Iphone Mail application

### PR DESCRIPTION
**Pull request by abrarpathan19**
### Description (*)

**Magento email templates responsive in Iphone Mail application** 
Magento Email templates are responsive Browsers, Gmail app, but not responsive in Iphone web App. Please review below screenshots.

http://prntscr.com/ldvug2

Please review current screenshots : http://prntscr.com/ldvsf8
**Expected result screenshots :** http://prntscr.com/ldvumv

### Manual testing scenarios (*)

1. Magento Email templates are not responsive in  Iphone Email application 
http://prntscr.com/ldvug2

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @abrarpathan19. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by Karlasa — APPROVED** [review]

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3380](https://jira.corp.magento.com/browse/ENGCOM-3380) has been created to process this Pull Request

**Comment by sdzhepa** [comment]
Hello @abrarpathan19 

Unfortunately, our QA engineers are not able to reproduce this bug by the provided description on 2.2-develop(without code-changes from this PR)

Could you please provide more details? Like:
- Magento installation type
- Magento mode
- iPhone device/os version
- any other details that could clarify flow for the bug and steps to reproduce it

This information will help us to Process/Test this PR and merge it quicker

Please see QA comment for internal ticket:
reproiphoneissue


Thank you for collaboration!

**Comment by abrarpathan19** [comment]
Hello @Serhii Dzhepa,
Please let me check...

**Comment by abrarpathan19** [comment]
Hello @Serhii Dzhepa,
Yes, Now it is fixed in Magento ver. 2.2.7 but you have taken a long time to review it, almost I have posted this bug before two months ago, In the previous version it was not fixed I have already shared that screenshots you can also check this issue in the previous version.

**Comment by VladimirZaets** [comment]
Hi @abrarpathan19, thank for collaboration. We believe that this issue was reproduced in the previous version, but we can't merge this PR to the previous version. This bug is already fixed in the current Magento version, so this PR is redundant.

**Pull request closed without merging**
