### PR TITLE
"Admin Session Lifetime" should use JS validate (to optimize UI/UX)

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

"Admin Session Lifetime" in Store->Configuration, Advanced/Admin should use JS validate. Currently, it validates after user clicks "Save" 

Use: validate-digits validate-range range-60-31536000. 

### Manual testing scenarios (*)

1. Go to backend.
2. Store->Configuration, Advanced/Admin
3. "Admin Session Lifetime", fill 31536001
4. Save
=> Can not save
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by kalpmehta** [comment]
@edenduong I have only seen `validate-digits-range digits-range-x-xxxx` in core Magento code. Are you sure `validate-range range-60-31536000` works as expected? Thanks!

**Comment by edenduong** [comment]
@kalpmehta: Thank you for your suggestion. "validate-range range-60-31536000" can be running but it is better if we uses as your suggestion. I have changed the source code. You can check it again.

**Review by kalpmehta — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, thank you for the review.
[ENGCOM-5666](https://jira.corp.magento.com/browse/ENGCOM-5666) has been created to process this Pull Request
:eight_spoked_asterisk: @kalpmehta, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5666](https://jira.corp.magento.com/browse/ENGCOM-5666) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

**Before:**
before

**After:**
after

**Pull request merged**
