### PR TITLE
Issue #35676 Model/Import/Entity/AbstractEntity restricts import column names to a-z (lowercase)

### LINKED ISSUE #35676: Remove import column name character restrictions
### Summary (*)

Model/Import/Entity/AbstractEntity restricts import column names to a-z (lowercase), 0-9 or underscore and must start with a-z (lowercase). Why? What is the point/value of this restriction?

### Examples (*)

```
                    if (!$this->isAttributeParticular($columnName)) {
                        if (trim($columnName) == '') {
                            $emptyHeaderColumns[] = $columnNumber;
                        } elseif (!preg_match('/^[a-z][a-z0-9_]*$/', $columnName)) {
                            $invalidColumns[] = $columnName;
                        } elseif ($this->needColumnCheck && !in_array($columnName, $this->getValidColumnNames())) {
                            $invalidAttributes[] = $columnName;
                        }
                    }

```

### Proposed solution

Either: 
1. Remove it.
2. Make this more flexible so we can use a-z, A-Z, 0-9, spaces and whatever symbols we want.
3. Add getValidatorPrereg() that allows us to override with our own checks for custom imports.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by artskirk**
### Description (*)

Model/Import/Entity/AbstractEntity restricts import column names to a-z (lowercase), 0-9 or underscore and must start with a-z (lowercase). In that case if you are trying to import file with new column name like `Sku_1` it fails with error.

image

- Open `app/code/Magento/Catalog/etc/db_schema.xml` and add a new column with name Sku_1
- Run bin/magento setup:upgrade. This will create a new column with name Sku_1 in table catalog_product_entity.
- Try to upload the CSV by adding newly created column in the CSV file from `admin->System->Data Transfer->Import`
- The script will fail for the newly created column

**What I did**
I have updated column validation regular expression to be more flexible.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35676

### Manual testing scenarios (*)

1. Open `app/code/Magento/Catalog/etc/db_schema.xml` and add a new column with name Sku_1
2. Run bin/magento setup:upgrade. This will create a new column with name Sku_1 in table catalog_product_entity.
3. Try to upload the CSV by adding newly created column in the CSV file from `admin->System->Data Transfer->Import`
4. The script works without validation errors

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Functional Tests B2B

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Review by Den4ik — COMMENTED** [review]
Hey @artskirk
I have checked your changes and unfortunately could not agree with it by next reasons:
1. `\w` mean any word character and is equal to `[a-zA-Z0-9_]`
2. In fact you should create attribute with `static` type that will add column into entity table
3. I'm not sure that uppercase characters is as good idea for using in the attribute codes
4. Attribute code should start from `[a-z]`. Your expression allow start from digit or `_`
5. If you try to add attribute from admin panel with code start with `_` it will be trimmed.
6. If you try to add attribute from admin panel with code start digit `attr_` prefix will be added automatically

So I don't see any problems with current logic.
@sidolov Please correct me if I'm wrong

**Comment by hostep** [comment]
@Den4ik: from my testing, I was able to create an attribute with code `Sku_1` using the backoffice of Magento. So if you then want to import products using this code as a column, it should be supported, right?

I agree with most of your other remarks though.

This is the validation message you get in the backoffice when trying to create an invalid attribute code:
```
Please use only letters (a-z or A-Z), numbers (0-9) or underscore (_) in this field, and the first character should be a letter.
```

So I think the regex should be changed to `/^[a-zA-Z][a-z0-9_]*$/`

**Pull request closed without merging**
