### PR TITLE
#19710 Respect theme model for view configuration keep_frame check on…

### LINKED ISSUE #19710: Magento 2.3 images cache generation generates wrong hash for some images with a custom theme that has the keep_frame var set to 0
### Summary (*)
I just upgrade my Magento 2 project from 2.2.6 to 2.3. After the upgrade, some images in the catalog are showing placeholders instead of the images. I have regenerated the images cache with the catalog:images:resize but some images are still missing (swatch images in category pages and image thumbnail in category pages).

After some investigation, it seems that is it a problem with the hash used for the image cache directory. When generating the images cache in the CLI, all images have in their misc params used to build the hash a value of "keep_frame" => 1, although in the view.xml file of my custom theme, the param "product_image_white_borders" is set to 0. When generating the image path for the catalog pages, the keep frame param is 0. 

My investigation led me to the ParamsBuilder class (module-catalog/Model/Product/Image/ParamsBuilder) that uses its viewConfig property to get the value of the var "product_image_white_borders" in the "hasDefaultFrame" function. Seemingly, when running the CLI command, the view config that is injected in the ParamsBuilder is not the same that is used by the ImageResize command, and it has a wrong "product_image_white_borders" value of 1. It seems that it does not use the theme that the ImageResize command is currently processing, and its scope is global. 

### Environment
Magento 2.3 Open Source with custom frontend theme

### Examples (*)
Assign images to products in the catalog.
Set the value of the variable "product_image_white_borders" to 0 in your custom theme view.xml file.
Regenerate product images cache with the CLI command catalog:images:resize.

### Proposed solution
The product thumbnail in category pages should appear but instead the placeholder image is shown.

### PR DESCRIPTION
**Pull request by Tomasz-Silpion**
… image resize

Fix wrong image cache path issue with _keep_frame_ argument not respecting theme settings

### Description (*)

Image resize command doesn't respect _product_image_white_borders_ config for all themes causing wrong image display

### Fixed Issues (if relevant)

1.  Fixes magento/magento2#19710 
Magento 2.3 images cache generation generates wrong hash for some images with a custom theme that has the keep_frame var set to 0

### Manual testing scenarios (*)

1. Configure Magento 2 with two themes using opposite _product_image_white_borders_ config in etc/view.xml 
2. Run _catalog:image:resize_ command and check if proper paths to media/catalog/product/cache/ were generated

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [] All new or changed code is covered with unit/integration tests (if applicable)
 - [] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Tomasz-Silpion** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Tomasz-Silpion. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Tomasz-Silpion, here is your [new Magento instance](https://pr-27444.instances.magento-community.engineering).
Admin access: [https://pr-27444.instances.magento-community.engineering/admin_b276](https://pr-27444.instances.magento-community.engineering/admin_b276)
Login: `8c8a5af3` Password: `70be2f030e4e`
Instance will be terminated in up to 3 hours.

**Comment by sidolov** [comment]
@magento run all tests

**Review by sidolov — CHANGES_REQUESTED** [review]
@Tomasz-Silpion please, cover changes with automated tests

**Comment by engcom-Charlie** [comment]
Hi @Tomasz-Silpion can you fix failed tests and cover your changes automated tests? Otherwise, we can't proceed with your PR.
Thank you.

**Comment by engcom-Charlie** [comment]
Hi @Tomasz-Silpion, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
