### PR TITLE
Fixed undefined shipping method issue

### PR DESCRIPTION
**Pull request by gelanivishal**
### Description (*)
Fixed undefined shipping method issue on checkout and cart page.

### Fixed Issues (if relevant)

1. magento/magento2#19853: Shipping method undefined issue

### Manual testing scenarios (*)

1. Add new or edit any existing shipping methods with Method name field left as a blank field.
2. Add any product to the cart and go through the checkout to the last step.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by miguelbalparda** [comment]
Do you think this will cause any issues with existing shipping extensions?

**Comment by gelanivishal** [comment]
Yes, You can see in issue, If you didn't add shipping method name on configuration the It appear undefined method on checkout and cart page.

**Comment by miguelbalparda** [comment]
Sorry I meant if you foresee any issues in the future if we accept this.

**Comment by gelanivishal** [comment]
No, I don't think so.

**Comment by vasilii-b** [comment]
How is that even possible to save shipping method  with empty name!? Isn't that the main issue here? :thinking:

**Comment by gelanivishal** [comment]
@vasilii-b So you think that it is not any issue on undefined shipping method name?

**Comment by vasilii-b** [comment]
> @vasilii-b So you think that it is not any issue on undefined shipping method name?

I think, if you wouldn't be able to save a shipping method with empty name, there won't be the issue you're trying to fix. I believe this (saving shipping method with empty title) is the issue to be fixed here. If that is fixed, you should' get "undefined shipping method".

**Comment by tig-rikjonkmans** [comment]
@miguelbalparda,
> Sorry I meant if you foresee any issues in the future if we accept this.

I do not think so, most shipping extensions adding their carrier by extending from the \Magento\Shipping\Model\Carrier\AbstractCarrier. Where they setting the carrier and method title programmatically.  

However you can still empty these default values in the configuration of the carrier in the Magento backend. This will give you the 'undefined' title in the frontend, but it will contain the carrier code, which can not be emptied. Based on the carrier code Magento creates the shipment, which goos well without a method or carrier title.

**Review by miguelbalparda — APPROVED** [review]

**Comment by miguelbalparda** [comment]
Hey @gelanivishal sorry for the slow turnaround, would you mind checking the failing test?

**Comment by orlangur** [comment]
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

**Comment by davidverholen** [comment]
@gelanivishal I added a few code style changes and also a change that the dash is only shown, when both method name and carrier title are set.

Could you please rebase the branch and squash the commits

**Comment by orlangur** [comment]
@davidverholen nice collaboration but still it would be better to concentrate on open PRs first.

**Comment by davidverholen** [comment]
@orlangur it's still an open issue. And instead of creating a new PR I thought it's better to use what's already there

**Comment by orlangur** [comment]
@davidverholen surely, I'm talking about 300+ open PRs.

**Review by orlangur — CHANGES_REQUESTED** [review]
@gelanivishal @davidverholen @nmalevanec please squash changes into a single commit so that we have perfectly clean history 😉

**Comment by gelanivishal** [comment]
Let me do that

**Comment by gelanivishal** [comment]
@orlangur I have created a new https://github.com/magento/magento2/pull/22593 PR, Please check it.

**Comment by orlangur** [comment]
@gelanivishal this is not needed, please just force push into the same branch.

**Comment by gelanivishal** [comment]
@orlangur Can you please let me know how can I do that? I'm not aware of it :)

**Comment by orlangur** [comment]
@gelanivishal switch to `issue-19853-2` locally, remove `issue-19853` local branch and then create it again and force push

**Comment by gelanivishal** [comment]
@orlangur After performing your steps, It is closed PR. I'm performing those changes and creating a PR. Can you please open this PR?

**Comment by orlangur** [comment]
@gelanivishal before force pushing please assure your branch contains relevant changes. New branch should be created out of `issue-19853-2` which contained correct commit.

**Comment by gelanivishal** [comment]
@orlangur Yes, I have checked and committed.

**Review by orlangur — CHANGES_REQUESTED** [review]
@gelanivishal can we refactor it to avoid code duplication? Just have this logic in one place used twice.

**Comment by orlangur** [comment]
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

**Pull request closed without merging**
