### PR TITLE
"laminas/laminas-soap" updated to ^2.9.0

### PR DESCRIPTION
**Pull request by khrystynastolbova**
### Description (*)

Update laminas/laminas-soap dependency package to PHP 8 compatible version (2.9.0)

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/522

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32317

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by khrystynastolbova** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento give me php8-develop instance

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run WebAPI Tests

**Review by sivaschenko — APPROVED** [review]

**Pull request merged**
