### PR TITLE
Fix error message in StockItemValidator.php

### LINKED ISSUE #31107: [Issue] Fix error message in StockItemValidator.php
This issue is automatically created based on existing pull request: magento/magento2#31058: Fix error message in StockItemValidator.php

---------
This error message has previously been updated to misleading text and since then lacked the "greater". (see git history/blame)
According to validation logic of the enclosing "if", values of zero are not allowed and will throw this error.

Error got thrown when supplying stock item id with the value of zero during an API call and left the developer scratching his head.

### PR DESCRIPTION
**Pull request by ferdiusa**
This error message has previously been updated to misleading text and since then lacked the "greater". (see git history/blame)
According to validation logic of the enclosing "if", values of zero are not allowed and will throw this error.

Error got thrown when supplying stock item id with the value of zero during an API call and left the developer scratching his head.

### Resolved issues:
1. [x] resolves magento/magento2#31107: Fix error message in StockItemValidator.php

### CODE REVIEW

**Comment by rogyar** [comment]
@magento run all tests

**Comment by rogyar** [comment]
Hi @ferdiusa. Thank you for your work, the fix totally makes sense according to the condition. 

According to the definition of done, all changes need to be covered by auto tests. I don't think it's the case since we don't have a test that covers the validator so far. So writing a test for a phrase change purpose might not be efficient. However, @ferdiusa if you want to achieve additional points for this PR, you may cover it by a simple unit test. 

Thanks.

**Comment by ferdiusa** [comment]
@rogyar thank you for your assistance and feedback.
After submitting this tiny fix, the requirements for inclusion of the code scared me off - especially that Community Contributions Triage. Whilst understanding the necessity of such a secured process in the larger context, it is more like biting a bullet in this scenario.

I will not submit an unit test for a translatable error message that had been wrongly worded. Such a test would make more sense for the actual condition leading to the error - thus validating IF the error is thrown upon supplying wrong arguments. But this exceeds both my time currently available as well as my understanding of the code / context.

Thanks for trying the incentive of additional points though 😄. I hope you get my point, this correction will get included in an upcoming release and saves other (API-)developers a headache.

**Comment by rogyar** [comment]
Hi @ferdiusa. No worries, it was the matter of the intention, no obligations added ;) 

Thank you for your work.

**Review by rogyar — APPROVED** [review]
Approved. The failing tests are not related to the current changes.

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8491](https://jira.corp.magento.com/browse/ENGCOM-8491) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@ferdiusa thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:** :heavy_multiplication_x: incorrect error message



**After:** :heavy_check_mark: correct error message

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by abhattGlo** [comment]
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run run Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run all tests

**Pull request merged**
