### PR TITLE
resolved selected options are not showing on edit wish list page. #24389

### PR DESCRIPTION
**Pull request by rani-priya**
### Fixed Issues (if relevant)

1. magento/magento2#24389:  selected options are not showing on edit wish list page.

### Manual testing scenarios (*)

1. Create a configurable product with swatches
2. Navigate to product page at frontend
3. Select swatches options and to wish list
4. open wish list and click on edit

wishlist-selected-options
wishlist

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Hi @rani-webkul,

Could you describe more detailed how did you fixed the issue? Why do we need `cache_lifetime=false`?

**Comment by rani-priya** [comment]
Hi @ihor-sviziev I have added cache_lifetime=false in checkout_cart_configure_type_configurable.xml and wishlist_index_configure_type_configurable.xml to avoid showing cached swatches block content.

Without cache_lifetime=false I was facing issue on cart configure, wish list configure and catalogue product page.

Steps: 
1. From product page I have selected swatches and then added to wish list.
2. then edited that product from wish list
3. Again from product page selected swatches(different options than wish list) and then added to cart.
4.  then edited that product from cart
5. on cart configure page I was getting wish list options

**Comment by rani-priya** [comment]
Hi @ihor-sviziev, 
Did you looked into this PR?

**Comment by ihor-sviziev** [comment]
Hi @rani-webkul,
Changes not really easy to review, it will take some time. I think maximum in few days i'll review it and give you feedback

**Comment by rani-priya** [comment]
@ihor-sviziev, Okay Thank-you

**Comment by ihor-sviziev** [comment]
Hi @rani-webkul,
Unfortunately I don't have enough time for reviewing it. it's better to keep for review by someone else.
Removing my assigne...

**Comment by rani-priya** [comment]
@ihor-sviziev, no one is reviewing this PR. what should I do?

**Comment by ihor-sviziev** [comment]
Will try to review it myself

**Comment by josefbehr** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @josefbehr. Thank you for your request. I'm working on Magento instance for you

**Comment by josefbehr** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @josefbehr. Thank you for your request. I'm working on Magento instance for you

**Review by krzksz — CHANGES_REQUESTED** [review]
Hey @rani-webkul, can you take a look at failing functional test?

**Comment by rogyar** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
Closing this PR due to inactivity. Please feel free to reopen if you are going to continue working on it.
Thank you.

**Pull request closed without merging**
