### PR TITLE
Update devdocs ref. links

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

Update devdocs ref. links in README
### Related Pull Requests

N/A
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number> N/A

### Manual testing scenarios (*)

1. N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by bgorski — APPROVED** [review]
Good catch, thanks!

**Comment by bgorski** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @bgorski, thank you for the review.
[ENGCOM-9234](https://jira.corp.magento.com/browse/ENGCOM-9234) has been created to process this Pull Request
:eight_spoked_asterisk: @bgorski, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Have a Magento 2.4-develop instance

**Manual testing scenario:**

1. Open the file app/code/Magento/EavGraphQl/README.md and check the v2.3 link has been updated to 2.4

2. Open the file app/code/Magento/Indexer/README.md and check the v2.3 link has been updated to 2.4
 
3. Open the file app/code/Magento/QuoteAnalytics/README.md and check the v2.3 link has been updated to 2.4


**Before:** :heavy_multiplication_x: The v2.3 link was not updated to v2.4


**After:** :heavy_check_mark: The 2.4 link was not updated to v2.4


As per the updated documents, tested all the updated links relevant to 2.4 version, and all the links are valid and no issue in the hyperlink.

The PR just has an update relevant to the links updates in the README.md files, hence no other additional testing is required.

**Pull request merged**
