### PR TITLE
Convert GitHub issue templates to issue forms

### LINKED ISSUE #36651: [Issue] Convert GitHub issue templates to issue forms
This issue is automatically created based on existing pull request: magento/magento2#35990: Convert GitHub issue templates to issue forms

---------

### Description (*)

Converting the GitHub issue templates to issue forms for:
- Developer experience issue
- Feature request

### Related Pull Requests

None

### Fixed Issues (if relevant)

None.

### Manual testing scenarios (*)

1. Open the issue selector at https://github.com/magento-devdocs/magento2/issues/new/choose
1. Create a **Developer experience issue**. Review the text fields and behavior.
1. Create a **Feature request**. Review the text fields and behavior.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by dshevtsov**
### Description (*)

Converting the GitHub issue templates to issue forms for:
- Developer experience issue
- Feature request

### Related Pull Requests

None

### Fixed Issues (if relevant)

None.

### Manual testing scenarios (*)

1. Open the issue selector at https://github.com/magento-devdocs/magento2/issues/new/choose
1. Create a **Developer experience issue**. Review the text fields and behavior.
1. Create a **Feature request**. Review the text fields and behavior.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36651: Convert GitHub issue templates to issue forms

### CODE REVIEW

**Comment by dshevtsov** [comment]
@cpartica, is the GraphQL Story type of issue still relevant?
If not, I can remove the template in this PR.
And if it is still in use, I can convert it to issue forms.

**Review by sdzhepa — APPROVED** [review]
changes look OK for me

QA Note: This PR does NOT require manual testing and adding to the regression scope. Changes in this PR does not affect any application functionality

**Comment by sdzhepa** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento create issue

**Pull request merged**
