### PR TITLE
Fixed issue #25039 Product detail did not scroll to review tab after click on 'Review' anchor link

### PR DESCRIPTION
**Pull request by gaurav-473**
Fixed issue magento/magento2#25039
**Preconditions**
1. Magento 2.3.3

**Steps to reproduce**
1. Go to product detail page
2. Click on 'review' or 'add your review' link (http://prntscr.com/pj0bg6)

**Expected result**
1. Auto scroll  to review tab at bottom.

**Actual result**
1. Did not scroll to review tab and encountered javascript error (http://prntscr.com/pj0d4g)

**Suspect**
1. Code issue on line 51-72 of Magento_Review/js/process-reviews.js (http://prntscr.com/pj0djj)

### CODE REVIEW

**Review by VladimirZaets — APPROVED** [review]

**Review by sudheers-kensium — APPROVED** [review]

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6113](https://jira.corp.magento.com/browse/ENGCOM-6113) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
Hello @gauravagarwal1001. Thanks for Your contribution. We can not fully reproduce the issue Your PR is going to fix. There is no need to duplicate the whole issue information in order to show You what exactly we are not able to reproduce. The difference is only in Actual Results. So Your's one looks like this:

**Actual Result**
Did not scroll to review tab and encountered javascript error (http://prntscr.com/pj0d4g)

while what we've got is somewhat different and would look like this:

**Actual Result**
Did not scroll to review tab when clicking on "Reviews" link `but do scroll to that tab` when clicking on `"Add Your Review"` link. `No JavaScript errors in console` are present, ether for "Reviews" or for "Add Your Review".

What do You think on it?

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Comment by VladimirZaets** [comment]
Covered in the scope of https://github.com/magento/magento2/pull/25915

**Comment by adexandros** [comment]
This happens because there is a second script `ui-modules/tabs.js` that is loading after the first `mage/tabs.js`; so that when `$('.product.data.items').tabs('activate', index);` is invoked (webroot/vendor/magento/module-review/view/frontend/web/js/process-reviews.js  on line 62) is referencing that second script and not the first one; 
This seems to be requested by the page builder module

**Pull request merged**
