### PR TITLE
Improvement/CE-33709: Update PHPUnit to v9.5.8 (~9.5.0)

### LINKED ISSUE #33709: Update `phpunit/phpunit` composer dependency to version ~9.5.0 (STAGE 3)
This issue is a STAGE 3 of the magento/magento2#33596.
We need to upgrade `phpunit/phpunit` to version ~9.5.0 with fixes of the codebase of the Magento tests.

### Related issue (*)
1. magento/magento2#33596 - parent issue
2. magento/magento2#33707 - STAGE 1
3. magento/magento2#33708 - STAGE 2

### PR DESCRIPTION
**Pull request by bohdan-harniuk**
### Description (*)
This PR contains the final step with upgrading to PHPUnit v9.5.8.
In this stage of the upgrade was fixed next errors:
```
2) Magento\Catalog\Test\Unit\Model\Product\Type\PriceTest::testTierPrices with data set "global price scope" (0, 0)
PHPUnit\Framework\MockObject\CannotUseAddMethodsException: Trying to set mock method "getPercentageValue" with addMethods(), but it exists in class "Magento\Catalog\Api\Data\ProductTierPriceExtensionInterface". Use onlyMethods() for methods that exist in the class

3) Magento\Catalog\Test\Unit\Model\Product\Type\PriceTest::testTierPrices with data set "website price scope" (1, 2)
PHPUnit\Framework\MockObject\CannotUseAddMethodsException: Trying to set mock method "getPercentageValue" with addMethods(), but it exists in class "Magento\Catalog\Api\Data\ProductTierPriceExtensionInterface". Use onlyMethods() for methods that exist in the class

4) Magento\Catalog\Test\Unit\Model\Product\Type\PriceTest::testGetPricesWithPercentType
PHPUnit\Framework\MockObject\CannotUseAddMethodsException: Trying to set mock method "getPercentageValue" with addMethods(), but it exists in class "Magento\Catalog\Api\Data\ProductTierPriceExtensionInterface". Use onlyMethods() for methods that exist in the class

5) Magento\Checkout\Test\Unit\Model\ShippingInformationManagementTest::testSaveAddressInformationWithLocalizedException
PHPUnit\Framework\MockObject\CannotUseAddMethodsException: Trying to set mock method "getShippingAssignments" with addMethods(), but it exists in class "Magento\Quote\Api\Data\CartExtension". Use onlyMethods() for methods that exist in the class

6) Magento\Checkout\Test\Unit\Model\ShippingInformationManagementTest::testSaveAddressInformationIfCanNotSaveQuote
PHPUnit\Framework\MockObject\CannotUseAddMethodsException: Trying to set mock method "getShippingAssignments" with addMethods(), but it exists in class "Magento\Quote\Api\Data\CartExtension". Use onlyMethods() for methods that exist in the class

7) Magento\Checkout\Test\Unit\Model\ShippingInformationManagementTest::testSaveAddressInformationIfCarrierCodeIsInvalid
PHPUnit\Framework\MockObject\CannotUseAddMethodsException: Trying to set mock method "getShippingAssignments" with addMethods(), but it exists in class "Magento\Quote\Api\Data\CartExtension". Use onlyMethods() for methods that exist in the class

8) Magento\Checkout\Test\Unit\Model\ShippingInformationManagementTest::testSaveAddressInformation
PHPUnit\Framework\MockObject\CannotUseAddMethodsException: Trying to set mock method "getShippingAssignments" with addMethods(), but it exists in class "Magento\Quote\Api\Data\CartExtension". Use onlyMethods() for methods that exist in the class

9) Magento\Cms\Test\Unit\Model\Template\FilterProviderTest::testGetPageWrongInstance
PHPUnit\Framework\MockObject\UnknownTypeException: Class or interface "SomeClass" does not exist

10) Magento\Downloadable\Test\Unit\Model\Link\UpdateHandlerTest::testExecute
PHPUnit\Framework\MockObject\CannotUseAddMethodsException: Trying to set mock method "getDownloadableProductLinks" with addMethods(), but it exists in class "Magento\Catalog\Api\Data\ProductExtensionInterface". Use onlyMethods() for methods that exist in the class

11) Magento\Downloadable\Test\Unit\Model\Link\UpdateHandlerTest::testExecuteNonDownloadable
PHPUnit\Framework\MockObject\CannotUseAddMethodsException: Trying to set mock method "getDownloadableProductLinks" with addMethods(), but it exists in class "Magento\Catalog\Api\Data\ProductExtensionInterface". Use onlyMethods() for methods that exist in the class

12) Magento\Downloadable\Test\Unit\Model\Sample\UpdateHandlerTest::testExecute
PHPUnit\Framework\MockObject\CannotUseAddMethodsException: Trying to set mock method "getDownloadableProductSamples" with addMethods(), but it exists in class "Magento\Catalog\Api\Data\ProductExtensionInterface". Use onlyMethods() for methods that exist in the class

13) Magento\Downloadable\Test\Unit\Model\Sample\UpdateHandlerTest::testExecuteNonDownloadable
PHPUnit\Framework\MockObject\CannotUseAddMethodsException: Trying to set mock method "getDownloadableProductSamples" with addMethods(), but it exists in class "Magento\Catalog\Api\Data\ProductExtensionInterface". Use onlyMethods() for methods that exist in the class

14) Magento\Multishipping\Test\Unit\Model\DisableMultishippingTest::testExecuteWithMultishippingModeEnabled with data set "check_with_shipping_assignments" (true)
PHPUnit\Framework\MockObject\CannotUseAddMethodsException: Trying to set mock method "getShippingAssignments" with addMethods(), but it exists in class "Magento\Quote\Api\Data\CartExtensionInterface". Use onlyMethods() for methods that exist in the class

15) Magento\Multishipping\Test\Unit\Model\DisableMultishippingTest::testExecuteWithMultishippingModeEnabled with data set "check_without_shipping_assignments" (false)
PHPUnit\Framework\MockObject\CannotUseAddMethodsException: Trying to set mock method "getShippingAssignments" with addMethods(), but it exists in class "Magento\Quote\Api\Data\CartExtensionInterface". Use onlyMethods() for methods that exist in the class

16) Magento\Persistent\Test\Unit\Model\QuoteManagerTest::testSetGuest
PHPUnit\Framework\MockObject\CannotUseAddMethodsException: Trying to set mock method "setShippingAssignments" with addMethods(), but it exists in class "Magento\Quote\Api\Data\CartExtensionInterface". Use onlyMethods() for methods that exist in the class

17) Magento\ProductVideo\Test\Unit\Model\Product\Attribute\Media\ExternalVideoEntryConverterTest::testGetMediaEntryType
PHPUnit\Framework\MockObject\CannotUseAddMethodsException: Trying to set mock method "setVideoContent" with addMethods(), but it exists in class "Magento\Catalog\Api\Data\ProductAttributeMediaGalleryEntryExtension". Use onlyMethods() for methods that exist in the class

18) Magento\ProductVideo\Test\Unit\Model\Product\Attribute\Media\ExternalVideoEntryConverterTest::testConvertTo
PHPUnit\Framework\MockObject\CannotUseAddMethodsException: Trying to set mock method "setVideoContent" with addMethods(), but it exists in class "Magento\Catalog\Api\Data\ProductAttributeMediaGalleryEntryExtension". Use onlyMethods() for methods that exist in the class

19) Magento\ProductVideo\Test\Unit\Model\Product\Attribute\Media\ExternalVideoEntryConverterTest::testConvertFrom
PHPUnit\Framework\MockObject\CannotUseAddMethodsException: Trying to set mock method "setVideoContent" with addMethods(), but it exists in class "Magento\Catalog\Api\Data\ProductAttributeMediaGalleryEntryExtension". Use onlyMethods() for methods that exist in the class

20) Magento\Quote\Test\Unit\Model\ShippingAddressAssignmentTest::testSetAddressUseForShippingTrue
PHPUnit\Framework\MockObject\CannotUseAddMethodsException: Trying to set mock method "setShippingAssignments" with addMethods(), but it exists in class "Magento\Quote\Api\Data\CartExtension". Use onlyMethods() for methods that exist in the class

21) Magento\Quote\Test\Unit\Model\ShippingAddressAssignmentTest::testSetAddressUseForShippingFalse
PHPUnit\Framework\MockObject\CannotUseAddMethodsException: Trying to set mock method "setShippingAssignments" with addMethods(), but it exists in class "Magento\Quote\Api\Data\CartExtension". Use onlyMethods() for methods that exist in the class
```

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/593
https://github.com/magento/partners-magento2b2b/pull/580
https://github.com/magento/adobe-stock-integration/pull/1864
https://github.com/magento/partners-magento2-infrastructure/pull/59

### Fixed Issues (if relevant)
1. Fixes magento/magento2#33709

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by bohdan-harniuk** [comment]
@magento run all tests

**Comment by bohdan-harniuk** [comment]
@magento run Unit Tests

**Review by andrewbess — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@andrewbess, we have a lot of failed tests. Why did you approve it?

**Comment by andrewbess** [comment]
Hello @ihor-sviziev 
Thank you for your notice.
I know why builds are broken.
Finally, it will merged only after all passed tests.

**Comment by bohdan-harniuk** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by bohdan-harniuk** [comment]
@magento run all tests

**Comment by bohdan-harniuk** [comment]
@magento run Unit Tests

**Comment by bohdan-harniuk** [comment]
@magento run Unit Tests

**Comment by bohdan-harniuk** [comment]
@magento run Unit Tests

**Comment by bohdan-harniuk** [comment]
@magento run all tests

**Comment by bohdan-harniuk** [comment]
@magento run all tests

**Comment by bohdan-harniuk** [comment]
@magento run all tests

**Comment by bohdan-harniuk** [comment]
@magento run WebAPI Tests

**Comment by bohdan-harniuk** [comment]
@magento run Integration Tests

**Comment by bohdan-harniuk** [comment]
@magento run Unit Tests

**Comment by bohdan-harniuk** [comment]
@magento run all tests

**Comment by bohdan-harniuk** [comment]
@magento run Unit Tests, Integration Tests, WebAPI Tests

**Comment by bohdan-harniuk** [comment]
@magento run Integration Tests, WebAPI Tests

**Comment by bohdan-harniuk** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by bohdan-harniuk** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@bohdan-harniuk Please resolve merge conflict

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by bohdan-harniuk** [comment]
@run Functional Tests CE, Functional Tests EE

**Comment by eduard13** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run Database Compare, Functional Tests EE, Functional Tests B2B, Integration Tests, Magento Health Index, Sample Data Tests EE, Sample Data Tests B2B, Semantic Version Checker, Static Tests, Unit Tests, WebAPI Tests

**Review by andrewbess — APPROVED** [review]

**Review by eduard13 — APPROVED** [review]
Great job 👍

**Pull request merged**
