### PR TITLE
MFTF: Replace redundant Xpath for `@id` attribute with CSS selector

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Although there is no difference in performance, readability of CSS selectors is much better, especially when we have elements having it's unique ID attribute. That is why I want to encourage MFTF users to use CSS selectors instead of enforcing Xpath when it's not necessary.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7637](https://jira.corp.magento.com/browse/ENGCOM-7637) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Pull request merged**
