### PR TITLE
Deny all php except whitelisted files

### PR DESCRIPTION
**Pull request by andrewkett**
resolves issue with php files being downloaded as plain text. https://github.com/magento/magento2/issues/2317

### CODE REVIEW

**Comment by daim2k5** [comment]
@andrewkett please accept the CLA

**Comment by Vinai** [comment]
Thank you for your contribution!
Ready for review by the core team.

**Comment by andrewkett** [comment]
Not sure what I did here but I just noticed somehow this PR ended up with two of my commits in it when it was supposed to only be one. ee5d58159845b93619c06012d91e233b518526d4 should be in https://github.com/magento/magento2/pull/2323 only.

**Comment by mazhalai** [comment]
@andrewkett thank you for your contribution, we have created ticket MAGETWO-50083 to process this PR.

**Comment by akaneria** [comment]
@andrewkett , can you please fix the issue with unwanted commit so we can proceed further?

Thanks!

**Comment by mazhalai** [comment]
@andrewkett can you please sync with develop and also rebase so that only commit related to this issue is in this PR?

**Comment by ark99** [comment]
FYI...I have just merged commit 'a688d04f6a4c6a9cad0ccd63b732ebc7f2dfda26' under the scope of internal ticket MAGETWO-50083 for further processing.

Thanks!

**Comment by vancoz** [comment]
Hi @andrewkett, your PR is merged, thank you for contribution!

**Pull request closed without merging**
