### PR TITLE
#bug-30798 - fix to 2.3.x

### PR DESCRIPTION
**Pull request by jakwinkler**
### Fixed Issues (if relevant)

1. Fixes this bug in 2.3.x https://github.com/magento/magento2/issues/30798

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Hi @qsolutions-pl,
Thank you for your contribution! I’ll try to move this PR forward.
@sidolov could you help to understand why the tests failing without test results?

**Comment by ihor-sviziev** [comment]
@qsolutions-pl 
Oh.. I see you’re created PR to 2.3 branch. Unfortunately it’s already closed for contributions and the only changes from internal teams could be accepted.

For accepting any contribution please re-point your pull request to 2.4-develop branch (or create new PR, that probably will be easier). Could you do that? 

Fixes for 2.3 release lines are accepted only from internal teams, they’re usually porting only critical fixes from 2.4-develop branch

**Comment by qsolutions-pl** [comment]
Thanks @ihor-sviziev however I can get back to this in few days. I've seen this bug in 2.4 as well.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @qsolutions-pl,
As we discussed in Slack - unfortunately your solution will cause performance issue back that was fixed in https://github.com/magento/magento2/commit/2028ccd78cf71570490677377f8f86f25198d328.

Proper solution will be implementing something similar to https://github.com/magento/magento2/issues/30798#issuecomment-734239727 (thank you @IvanChepurnyi for good sample).

Could you try to update your solution to use this approach and re-target your PR to 2.4-develop branch?

**Comment by qsolutions-pl** [comment]
I'm closing this PR since it won't be merged anyway to 2.3.x

**Pull request closed without merging**
