### PR TITLE
[Magento 2.2] cannot create full datetime product attribute 4053

### PR DESCRIPTION
**Pull request by novikor**
### Description (*)
  -  Added time picker for product edit page (for attrobutes with `frontend_type` = `date`)

### Fixed Issues (if relevant)

1. magento/magento2#4053: Cannot create full datetime product attribute

### Manual testing scenarios (*)
1. Go to product edit page
2. Find any `date` attribute
3. Try to save date & time value
4. Make sure value is saved correctly
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @novikor. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
@novikor can you please [port](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting) this pull request to 2.3-develop branch, it should be merged to 2.3 first.

**Comment by sivaschenko** [comment]
Pull request to 2.3-develop: https://github.com/magento/magento2/pull/19385

**Comment by novikor** [comment]
@sivaschenko , the solution for both PRs (2.2 and 2.3) have been updated.
Please review.

**Comment by sidolov** [comment]
@novikor , I am closing this PR now due to inactivity in the original PR.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by drpayyne** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @drpayyne. Thank you for your request. I'm working on Magento instance for you

**Pull request closed without merging**
