### PR TITLE
25065 fixed address book tab selected

### PR DESCRIPTION
**Pull request by RonakParmar**
### Fixed Issues (if relevant)

1. magento/magento2#25065: Address Book Tab is not Active after Saving the Address at My Account Page

### Manual testing scenarios (*)

1. Do Login at Fronend
2. Go to My Account Page
3. Click on "Address Book", this tab is showing as selected.
4. Add New Address or Edit Address and save it.
5. Check the "Address Book" tab is not showing as selected.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by kalpmehta — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, thank you for the review.
[ENGCOM-6101](https://jira.corp.magento.com/browse/ENGCOM-6101) has been created to process this Pull Request
:eight_spoked_asterisk: @kalpmehta, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Bravo** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo, here is your [Magento instance](https://i-25066-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25066-2-3-develop.instances.magento-community.engineering/admin](https://i-25066-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Bravo** [comment]
Helo @RonakParmar. Thanks for contributing. As the issue this PR fixes is not reproduced on 2.3-develop but is supposed to be reproduced on 2.3.3 the PR is temporary moving to On Hold where it shall stay until 2.3.3 is merged into 2.3-develop.

**Comment by RonakParmar** [comment]
Hello @engcom-Bravo Okay, Thank you.

**Comment by engcom-Bravo** [comment]
@RonakParmar, we got information that 2.3.3 has been merged into 2.3-develop: https://github.com/magento/magento2/commit/0583fc3a88c948b2e95c6874c6dda1caaa4f9442
So we tried to retest the issue Your PR is going to fix but we are still not able to do that on fresh 2.3-develop. Thus it seems the merge haven't broke the correct behavior the 2.3-develop had possessed before merging. What do You think about it?. May Your PR be still actual in some respect? Thank You.

**Comment by RonakParmar** [comment]
@engcom-Delta  As the 2.3.3 now merged, Is anyone review this PR? Right now it is on hold.
Let me know if I have to do anything regarding this PR.

Thank you.

**Comment by sdzhepa** [comment]
Hello @RonakParmar and @kalpmehta, @engcom-Bravo 

The issue https://github.com/magento/magento2/issues/25065 has been re-verified on the current `2.3-develop` code base with merged changes from `2.3.3` release https://github.com/magento/magento2/commit/0583fc3a88c948b2e95c6874c6dda1caaa4f9442
We cannot reproduce it now by provided steps from the description Issue description https://github.com/magento/magento2/issues/25065 which means this issue has been fixed and not reproducible anymore.

This https://github.com/magento/magento2/issues/25065 and this  PR https://github.com/magento/magento2/pull/25066 should be closed.

**Pull request closed without merging**
