### PR TITLE
[Forwardport] Fixes saving product in single-store mode if website_id <> 1

### PR DESCRIPTION
**Pull request by eduard13**
### Original Pull Request 
 https://github.com/magento/magento2/pull/18001

### Description
This PR fixes the saving product in a single store mode, where the default website was removed, and a new one it is used instead.

### Fixed Issues (if relevant)
1. magento/magento2#13405: No such entity error when saving product in single-store mode if website_id <> 1

### Manual testing scenarios
1. Install a clean version of Magento version 2.2.2
2. Add a new website, store and store view, and make this the default
3. Delete the preinstalled website, store and store view
4. Add a new product and save it
5. Change the configurations to single-store mode
6. Open the product and save it again

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
Please, consider fixing the failing static tests. The issues might not be related directly to your changes but to files that were changed in general. If you need help with that, feel free to connect me in Slack

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18210) <br/>All committers have signed the CLA.

**Review by slavvka — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @slavvka, thank you for the review.
[ENGCOM-3078](https://jira.corp.magento.com/browse/ENGCOM-3078) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
