### PR TITLE
Fix #24575 Replace nested arrays in the layout processor in favor of using Array Manager

### LINKED ISSUE #24575: Replace nested arrays in the layout processor in favor of using Array Manager
### Summary (*)
There are several places with verbose code of checking and setting layout data that can be reduced.

### Examples (*)
Magento\Checkout\Block\Checkout\LayoutProcessor
```php
if (isset($jsLayout['components']['checkout']['children']['steps']['children']['shipping-step']['children']
    ['step-config']['children']['shipping-rates-validation']['children'])) {
    $jsLayout['components']['checkout']['children']['steps']['children']['shipping-step']['children']
    ['step-config']['children']['shipping-rates-validation']['children'] =
        $this->processShippingChildrenComponents(
            $jsLayout['components']['checkout']['children']['steps']['children']['shipping-step']['children']
            ['step-config']['children']['shipping-rates-validation']['children']
        );
}
```

### Proposed solution
```php
$path = 'components/checkout/children/steps/children/shipping-step/children/step-config/children/shipping-rates-validation/children';
if ($fields = $this->arrayManager->get($path, $jsLayout)) {
    $this->arrayManager->set(...);
}
```

### PR DESCRIPTION
**Pull request by roerlemans**
…in favor of using Array Manager

### Description (*)
There are several places with verbose code of checking and setting layout data that can be reduced.

### Fixed Issues (if relevant)
1. magento/magento2#24575: Replace nested arrays in the layout processor in favor of using Array Manager

### Manual testing scenarios (*)
1. Check if the checkout still works 

### Questions or comments
I't my first PR, I did sign the CLA. But still not member of your Organization.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by roerlemans** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @ronn0. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @ronn0, here is your [new Magento instance](https://pr-24836.instances.magento-community.engineering).
Admin access: [https://pr-24836.instances.magento-community.engineering/admin](https://pr-24836.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by ihor-sviziev — COMMENTED** [review]
Hi @ronn0,

Your change looks good from clear code understanding perspective, but from performance - looks like result will be really worse.

Could you check how many times this piece of code executed? From the method phpdoc block looks like it's executed for many blocks.

This code executed on checkout page, so I would prefer performance over clear code there

**Comment by roerlemans** [comment]
> Hi @ronn0,
> 
> Your change looks good from clear code understanding perspective, but from performance - looks like result will be really worse.
> 
> Could you check how many times this piece of code executed? From the method phpdoc block looks like it's executed for many blocks.
> 
> This code executed on checkout page, so I would prefer performance over clear code there

I agree, let me take a look on that. 👍

**Comment by ihor-sviziev** [comment]
Hi @ronn0,
Were you able to check how many times this code is executed?

**Comment by roerlemans** [comment]
Need some work before merging.. Sorry

**Pull request closed without merging**
