### PR TITLE
[MFTF] Repetitive elements replaced by AdminOpenNewProductFormPageActionGroup

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR replaces repetitive elements to `AdminOpenNewProductFormPageActionGroup`

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9394](https://jira.corp.magento.com/browse/ENGCOM-9394) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by Den4ik** [comment]
All looks good. Moving it to Merge in Progress due to passed tests

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
HI @Usik2203 and @Den4ik 
Thanks for your contribution and collaboration.

@Usik2203, in order to process the PR changes for merging, we should not have any merge conflicts. Can you please help us resolving the conflicts and update the PR again.
Thanks in advance!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Semantic Version Checker

**Comment by engcom-Charlie** [comment]
I have merged 2.4-develop into this branch and resolved all the conflicts.

Below failed/broken test cases in the build failures are not part of PR changes or not failing because of any change made in PR. Hence moving this to Merge in Progress.

Failed test cases are:
Functional Tests CE,
app/code/Magento/LoginAsCustomer/Test/Mftf/Test/AdminLoginAsCustomerLoggingFilterTest.xml

Functional EE:  broken
app/code/Magento/GiftCard/Test/Mftf/Test/StorefrontInstantPurchaseFunctionalityTest.xml
app/code/Magento/InstantPurchase/Test/Mftf/Test/StorefrontInstantPurchaseFunctionalityTest.xml

Thank you!

**Pull request merged**
