### PR TITLE
Update LinkedMapProvider.php

### LINKED ISSUE #38434: [Issue] Update LinkedMapProvider.php
This issue is automatically created based on existing pull request: magento/magento2#38380: Update LinkedMapProvider.php

---------
Related to https://github.com/magento/magento2/pull/32221
Fix issue https://github.com/magento/magento2/issues/9799

### PR DESCRIPTION
**Pull request by sheepfy**
Related to https://github.com/magento/magento2/pull/32221
Fix issue https://github.com/magento/magento2/issues/9799

### Resolved issues:
1. [x] resolves magento/magento2#38434: Update LinkedMapProvider.php

### CODE REVIEW

**Review by andrewbess — APPROVED** [review]
Hello @sheepfy 
Thank you for your contribution
Looks good for me
Approved

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

1. Go to app/code/Magento/Catalog/Model/ProductLink/CollectionProvider/LinkedMapProvider.php
2. Update LinkedMapProvider.php

**Before:** :heavy_multiplication_x: 

Screenshot 2024-02-09 at 4 49 33 PM

**After:** :heavy_check_mark:  

Screenshot 2024-02-09 at 4 58 37 PM


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE, Integration Tests, WebAPI Tests

**Comment by engcom-Charlie** [comment]
The functional CE failures are different in recent 2 runs, seems to be flacky.

Run 1:
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38380/c1b0481fe45413e0eb14b7bb0166922a/Functional/allure-report-ce/index.html#categories
image


Run 2:
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38380/19720d85ad3e9272045a5eb2115b8765/Functional/allure-report-ce/index.html#categories
image

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests, Integration Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by engcom-Bravo** [comment]
Hi @sheepfy,

Thanks for your contribution!

We have followed these steps described here https://github.com/magento/magento2/issues/9799 and we are not able to reproduce the issue in Latest 2.4-develop instance.

Please refer this https://github.com/magento/magento2/issues/9799#issuecomment-1333451739 if you are able to reproduce the issue and if we are missing anything please feel free to let us/reopen the PR.

Hence we are closing this PR.

Thanks.

**Pull request closed without merging**
