### PR TITLE
[Integration] Refactoring some fixtures for cms module

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR refactores some fixtures for CMS module

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @Usik2203,
Please review the test failures and update your changes accordingly.

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run WebAPI Tests

**Comment by Usik2203** [comment]
I can't see errors in `WebAPI Tests` and `Integration Tests` related with my changes.
Seems they are just failed, but without error messages 
Thanks

**Comment by ihor-sviziev** [comment]
@slavvka could you give some additional info why integration &  web api tests are failing?

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
Updated branch and rerun builds. Will monitor logs.

**Comment by lenaorobei** [comment]
Integration failure is not related to this PR. We are investigating this issue, it appears for every run.

WebAPI build failure is caused by:
```
09:29:55 [WebAPI GRAPHQL-Tests-CE] ..........................PHP Fatal error:  Uncaught Exception: Exception occurred when running the "\/var\/www\/html\/dev\/tests\/integration\/testsuite\/Magento\/Cms\/_files\/pages.php" fixture: 
09:29:55 [WebAPI GRAPHQL-Tests-CE] Notice: Undefined variable: objectManager in /var/www/html/dev/tests/integration/testsuite/Magento/Cms/_files/pages.php:18. in /var/www/html/dev/tests/api-functional/framework/Magento/TestFramework/Annotation/ApiDataFixture.php:114
```

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Wow. So files from integration tests are used in web api tests? 🤦‍♂️

**Comment by lenaorobei** [comment]
Yes, they are used fro both test types in order to avoid duplications.

**Comment by lenaorobei** [comment]
@ihor-sviziev that sounds like a good idea but it might require huge effort to update framework and fix all tests.

**Review by ihor-sviziev — APPROVED** [review]
✅ approved! Failing integration tests not related to changes from this PR

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7613](https://jira.corp.magento.com/browse/ENGCOM-7613) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Pull request merged**
