### PR TITLE
fix-getStoreId-type add check and cast on Order getStoreId function

### PR DESCRIPTION
**Pull request by fabiov**
getStoreId function of Order class can return string type, so can generate some errors when use strinct type.

Add type on getStoreId function of Order class

### CODE REVIEW

**Comment by petitgen** [comment]
@magento give me test instance

**Comment by fabiov** [comment]
@magento run all tests

**Comment by fabiov** [comment]
@magento run all tests

**Comment by fabiov** [comment]
Hi @petitgen @sidolov , what can I do to carry out the pull request?
I don't understand why the tests are failing, they seem unrelated to my PR.
Thanks.

**Pull request closed without merging**
