### PR TITLE
class docstring methods corrected

### LINKED ISSUE #30390: [Issue] class docstring methods corrected
This issue is automatically created based on existing pull request: magento/magento2#30389: class docstring methods corrected

---------

### Description (*)

It's a class docstring correction causing my PHPStorm showing wrong type hinting.

### Manual testing scenarios (*)

1. Check the type hints on any IDE which reads a class docstrings

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by milindsingh**
### Description (*)

It's a class docstring correction causing my PHPStorm showing wrong type hinting.

### Manual testing scenarios (*)

1. Check the type hints on any IDE which reads a class docstrings

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30390: class docstring methods corrected

### CODE REVIEW

**Comment by milindsingh** [comment]
@magento create issue

**Comment by milindsingh** [comment]
#dmcdindia2020

**Comment by rodrigowebjump** [comment]
Hi @milindsingh Thanks for your contribution.

**Comment by gabrieldagama** [comment]
@magento run all tests

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the pull request @milindsingh ! As the static tests are running for whole changed files the have been the following errors reported:

```
FILE: ...ww/html/app/code/Magento/Quote/Model/Quote/Item/AbstractItem.php
----------------------------------------------------------------------
FOUND 1 ERROR AND 1 WARNING AFFECTING 2 LINES
----------------------------------------------------------------------
  21 | WARNING | [ ] Abstract classes MUST NOT be marked as public
     |         |     @api.
 258 | ERROR   | [x] Tags visual alignment must be consistent
```

Could you please address them in the current PR

**Comment by sivaschenko** [comment]
@magento run Unit Tests,Functional Tests CE

**Comment by sivaschenko** [comment]
@magento give me test instance

**Comment by sivaschenko** [comment]
@magento give me test instance

**Comment by milindsingh** [comment]
@magento run Static Tests

**Comment by milindsingh** [comment]
@sivaschenko I fixed the static tests you mentioned, but few more errors are there `Public type 'Magento\OfflineShipping\Model\SalesRule\Calculator' references following non-public types:
Magento\Quote\Model\Quote\Item\AbstractItem`

Any idea how to fix them?

**Comment by ishakhsuvarov** [comment]
Hi

I am closing this PR for now as it seems like it has become stale and still needs work.

Please feel free to reopen if you wish to continue.

Thanks!

**Pull request closed without merging**
