### PR TITLE
Fixed critical error: The following tag(s) are not allowed: img

### LINKED ISSUE #29958: [Issue] Fixed critical error: The following tag(s) are not allowed: img
This issue is automatically created based on existing pull request: magento/magento2#29863: Fixed critical error: The following tag(s) are not allowed: img

---------

### Preconditions (*)

Magento 2.4-develop
My account -> My orders pages generates critical error logs
Details: https://github.com/magento/magento2/pull/25418#discussion_r478456345

### Steps to reproduce (*)

1. Place an order as a registered customer.
2. Go to My Account -> My Orders

### Expected result (*)
no errors

### Actual result (*)
All order pages (order, invoice, creditmemo, shipping) generates critical error in log
`The following tag(s) are not allowed: img`

### PR DESCRIPTION
**Pull request by themystery404**
### Description (*)

My account -> My orders pages generates critical error logs
Details: https://github.com/magento/magento2/pull/25418#discussion_r478456345

### Fixed Issues (if relevant)

1. Fixes magento/magento2#25418
### Manual testing scenarios (*)

1. Place an order as a registered customer.
2. Go to My Account -> My Orders

**Actual result:**
All order pages (order, invoice, creditmemo, shipping) generates critical error in log
`The following tag(s) are not allowed: img`

**Expected result:**
no errors

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29958: Fixed critical error: The following tag(s) are not allowed: img

### CODE REVIEW

**Review by torhoehn — APPROVED** [review]

**Comment by torhoehn** [comment]
@themystery404 Thanks for your first contribution!

**Comment by magento-engcom-team** [comment]
Hi @torhoehn, thank you for the review.
[ENGCOM-8118](https://jira.corp.magento.com/browse/ENGCOM-8118) has been created to process this Pull Request
:eight_spoked_asterisk: @torhoehn, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@themystery404 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by torhoehn** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked order pages (order, invoice, creditmemo, shipping) dont generate errors in log
**Before:**
:heavy_check_mark: image
:x: Error "main.CRITICAL: The following tag(s) are not allowed: img [] []" in log

**After:**
:heavy_check_mark: image
:heavy_check_mark: No errors in log

**Comment by engcom-Delta** [comment]
:warning: **Note:** Static Tests are failed

**Comment by torhoehn** [comment]
@themystery404 Could you please fix failing static test?

**Comment by engcom-Charlie** [comment]
@torhoehn I'll fix static tests.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by torhoehn — APPROVED** [review]

**Comment by torhoehn** [comment]
@engcom-Charlie Thanks for fixing static tests!

**Comment by magento-engcom-team** [comment]
Hi @torhoehn, thank you for the review.
[ENGCOM-8118](https://jira.corp.magento.com/browse/ENGCOM-8118) has been created to process this Pull Request
:eight_spoked_asterisk: @torhoehn, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
@magento create issue

**Comment by engcom-Delta** [comment]
**Note:** All tests are passed

**Pull request merged**
