### PR TITLE
[Forwardport] Cast products getStoreId() to int

### PR DESCRIPTION
**Pull request by sreichel**
### Description

Cast `getStoreId()` for products to int (like for categories).

Forwardport: https://github.com/magento/magento2/pull/18086

### Fixed Issues (if relevant)

1. magento/magento2#18079: 

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @sreichel. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3061](https://jira.corp.magento.com/browse/ENGCOM-3061) has been created to process this Pull Request

**Comment by sreichel** [comment]
@sidolov whats wrong with this test? I dont see any problems at mentioned lines.

**Comment by magento-engcom-team** [comment]
Hi @sreichel. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
