### PR TITLE
Fixed configurable product widget issue

### PR DESCRIPTION
**Pull request by gelanivishal**
### Description (*)
Fixed issue configurable products in widgets.

### Fixed Issues (if relevant)

1. magento/magento2#19315: Issue with configurable products in widgets, not added to cart

### Manual testing scenarios (*)

1. Create a product attribute, for example Size with several values (S, M and L). This attribute must have property "use in product listing" set to Yes.
2. Create a product that uses this attribute with a configuration setting. Define different quantities for each values. Set this product as new for the current month.
3. Create a block with a widget for new products (choose the grid template) and add this block at any page.
4. On this page click on Add to cart for this new product.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3516](https://jira.corp.magento.com/browse/ENGCOM-3516) has been created to process this Pull Request

**Review by jcourtei — CHANGES_REQUESTED** [review]
In new_default_list.phtml it should be $_product instead of $_item

**Comment by gelanivishal** [comment]
@jcourtei I have updated it.

**Review by jcourtei — APPROVED** [review]
@gelanivishal Thanks!

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
