### PR TITLE
fix 38200: Exception is not getting handled properly while adding a product to cart in the compare product page

### LINKED ISSUE #38200: Exception is not getting handled properly while adding a product to cart in the compare product page
### Preconditions and environment

- Magento version 2.4.6-p3
- PHP 8.1.18
- MySql  8.0.35-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))

### Steps to reproduce

- Login into the Magento using customer credentials
- Add a product to the compare list
- Got to my account page
- Click on compare
- Add the product to cart [In my case there was a Localized Exception thrown while adding it to the cart, there is a catch block in vendor/magento/module-checkout/Controller/Cart/Add.php line 164, but the exception is not caught and handled properly, instead JSON encoded page is returned]

### Expected result

The exception should be handled and a message manager message should be displayed in the controller.
image

### Actual result

image
The above-mentioned page is loaded with a JSON response

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rogerdz**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#38200

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
Hello @rogerdz 
Thank you for your contribution
The changes look nice for but let's wait for integration test results.
I've rerun it.

**Comment by andrewbess** [comment]
@magento run Integration Tests

**Comment by andrewbess** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Review by andrewbess — APPROVED** [review]
Approved

**Comment by engcom-Bravo** [comment]
Hello,

Internal team has started to work on it

Thanks.

**Comment by hostep** [comment]
For some reason, this PR wasn't marked as merged, even though the code was merged recently here: https://github.com/magento/magento2/commit/808253df82fcfa653e851ef0224ab33837b2ad65

**Comment by rogerdz** [comment]
> For some reason, this PR wasn't marked as merged, even though the code was merged recently here: [808253d](https://github.com/magento/magento2/commit/808253df82fcfa653e851ef0224ab33837b2ad65)

yes, it not first time :))

**Comment by engcom-Bravo** [comment]
@hostep Thanks for your contribution!!.

Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-10660 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-10660&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta1.

Thanks

**Pull request closed without merging**
