### PR TITLE
Fix for payment error with valid input data "Please enter a valid credit card expiration date." #4741

### PR DESCRIPTION
**Pull request by schogini**
Fix for the bug reported at https://github.com/magento/magento2/issues/4741

### CODE REVIEW

**Comment by mazhalai** [comment]
@schogini  please sync your branch with latest develop.

**Comment by schogini** [comment]
@mazhalai Done. Synced our branch with the latest develop

**Comment by schogini** [comment]
@mazhalai This is my first contribution to the code so, my questions will sound novice. Is there anything else that I need to do for this? It says "This branch has no conflicts with the base branch" and I have signed the License Agreement more than a few times. I am sure I am missing something obvious. Any guidance would be great. Thanks!

**Comment by dkvashninbay** [comment]
This is a bug in general CC model (created internal ticket to fix in next patch), as it depends on wrong DataObject structure (raw request, security vulnerable), instead of \Magento\Quote\Api\Data\PaymentInterface which gets passed to Checkout service.

All Payment Integrations which have own payload on checkout, should pass it in additional_data field and read this data from additional_data field of DataObject.

**Pull request closed without merging**
