### PR TITLE
Get sorted module name list by sequence

### PR DESCRIPTION
**Pull request by altdovydas**
Load and merge xml files by sequence.

### Description
Magento\Framework\Module\Dir getFiles
Use Magento/Framework/Module/ModuleList.php getNames

Which return enabled module list (sorted as they are in 'app/etc/config.php' file).

This fix return same list but sorted by sequence.

### Manual testing scenarios
1. Create module.
2. append etc/frontend/di.xml file with:
`    <type name="Magento\Framework\App\RouterList">
        <arguments>
            <argument name="routerList" xsi:type="array">
                <item name="urlrewrite" xsi:type="array">
                    <item name="class" xsi:type="string">Magento\UrlRewrite\Controller\Router</item>
                    <item name="disable" xsi:type="boolean">false</item>
                    <item name="sortOrder" xsi:type="string">1</item>
                </item>
            </argument>
        </arguments>
    </type>
`
3. append etc/module.xml with
`    <module name="Module_Name" setup_version="1.0.0">
        <sequence>
            <module name="Magento_UrlRewrite" />
        </sequence>
    </module>
`
4. Debug Magento\Framework\App\RouteList Line 39 variable $this->routerList

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=13160) <br/>All committers have signed the CLA.

**Comment by orlangur** [comment]
Hi @altdovydas,

Could you please add more insight on what are you trying to fix?

> Which return enabled module list (sorted as they are in 'app/etc/config.php' file).
> This fix return same list but sorted by sequence.

As far as I remember modules in `app/etc/config.php` do respect the order defined by sequence.

**Comment by altdovydas** [comment]
@orlangur After module was updated (added sequence). I need manual disable and enable module (to sort `app/etc/config.php` module list by sequence).

**Comment by orlangur** [comment]
@altdovydas this is how things are supposed to work. Sorting by sequence does not give an exact order of modules while `app/etc/config.php` makes XML files merging deterministic.

**Comment by orlangur** [comment]
Closing for now as Magento seems to be working as intended and there is nothing to fix actually here.

@altdovydas, feel free to continue discussion here or report a new issue describing system behavior which you believe is incorrect.

**Pull request closed without merging**
