### PR TITLE
17847 Fixed wrong state title

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

Fixed issue #17847
Screenshot 2020-01-28 at 23 32 23

### Fixed Issues (if relevant)

1. magento/magento2#17847: Wrong State Title, Displaying Status Label Rather than State

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Usik2203. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Usik2203, here is your [new Magento instance](https://pr-26569.instances.magento-community.engineering).
Admin access: [https://pr-26569.instances.magento-community.engineering/admin_03d0](https://pr-26569.instances.magento-community.engineering/admin_03d0)
Login: `89f57862` Password: `f95c9d210df4`
Instance will be terminated in up to 3 hours.

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-6786](https://jira.corp.magento.com/browse/ENGCOM-6786) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passe
"Suspected Froud" is changed to "Processing"
PR_processing

**Pull request merged**
