### PR TITLE
magento/magento2#: Replace deprecated functionality in “customer:hash:upgrade” command [WIP]

### LINKED ISSUE #29611: [Issue] Replace deprecated functionality in “customer:hash:upgrade” command
This issue is automatically created based on existing pull request: magento/magento2#27333: magento/magento2#: Replace deprecated functionality in “customer:hash:upgrade” command [WIP]

---------

### Description (*)

PR replaces deprecated `customer->load()`, `customer->save()` functionality in the 

```bin/magento customer:hash:upgrade```

command.

Original PR: https://github.com/magento/magento2/pull/24243

CC: @dmytro-ch @ihor-sviziev 

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by atwixfirster**
### Description (*)

PR replaces deprecated `customer->load()`, `customer->save()` functionality in the 

```bin/magento customer:hash:upgrade```

command.

Original PR: https://github.com/magento/magento2/pull/24243

CC: @dmytro-ch 

### Fixed Issues (if relevant)

1. Fixes #29611

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@slavvka @lenaorobei could you provide more details why we don't have any build reports? It's not looks logical at all in this case.

**Comment by slavvka** [comment]
Hey @ihor-sviziev @atwixfirster 
There is an error during Magento installation:
```
01:59:47 [Build Functional CE] Installing database schema:
01:59:55 [Build Functional CE] 
01:59:55 [Build Functional CE] In Mysql.php line 110:
01:59:55 [Build Functional CE]                                                                                
01:59:55 [Build Functional CE]   [Zend_Db_Statement_Exception (42)]                                           
01:59:55 [Build Functional CE]   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2_prod.ea  
01:59:55 [Build Functional CE]   v_entity_type' doesn't exist, query was: SELECT `main_table`.* FROM `eav_en  
01:59:55 [Build Functional CE]   tity_type` AS `main_table`                                                   
01:59:55 [Build Functional CE]                                                                                
01:59:55 [Build Functional CE] 
01:59:55 [Build Functional CE] Exception trace:
01:59:55 [Build Functional CE]   at /var/www/html/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php:110
01:59:55 [Build Functional CE]  Magento\Framework\DB\Statement\Pdo\Mysql->tryExecute() at /var/www/html/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php:92
01:59:55 [Build Functional CE]  Magento\Framework\DB\Statement\Pdo\Mysql->_execute() at /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Statement.php:303
01:59:55 [Build Functional CE]  Zend_Db_Statement->execute() at /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php:480
01:59:55 [Build Functional CE]  Zend_Db_Adapter_Abstract->query() at /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:238
01:59:55 [Build Functional CE]  Zend_Db_Adapter_Pdo_Abstract->query() at /var/www/html/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php:545
01:59:55 [Build Functional CE]  Magento\Framework\DB\Adapter\Pdo\Mysql->_query() at /var/www/html/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php:612
01:59:55 [Build Functional CE]  Magento\Framework\DB\Adapter\Pdo\Mysql->query() at /var/www/html/generated/code/Magento/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php:128
01:59:55 [Build Functional CE]  Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->query() at /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php:737
01:59:55 [Build Functional CE]  Zend_Db_Adapter_Abstract->fetchAll() at /var/www/html/generated/code/Magento/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php:1558
01:59:55 [Build Functional CE]  Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->fetchAll() at /var/www/html/lib/internal/Magento/Framework/Data/Collection/Db/FetchStrategy/Query.php:21
01:59:55 [Build Functional CE]  Magento\Framework\Data\Collection\Db\FetchStrategy\Query->fetchAll() at /var/www/html/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php:781
01:59:55 [Build Functional CE]  Magento\Framework\Data\Collection\AbstractDb->_fetchAll() at /var/www/html/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php:676
01:59:55 [Build Functional CE]  Magento\Framework\Data\Collection\AbstractDb->getData() at /var/www/html/app/code/Magento/Eav/Model/Config.php:387
01:59:55 [Build Functional CE]  Magento\Eav\Model\Config->_initEntityTypes() at /var/www/html/app/code/Magento/Eav/Model/Config.php:426
01:59:55 [Build Functional CE]  Magento\Eav\Model\Config->getEntityType() at /var/www/html/app/code/Magento/Eav/Model/Entity/AbstractEntity.php:322
01:59:55 [Build Functional CE]  Magento\Eav\Model\Entity\AbstractEntity->setType() at /var/www/html/generated/code/Magento/Customer/Model/ResourceModel/Customer/Interceptor.php:180
01:59:55 [Build Functional CE]  Magento\Customer\Model\ResourceModel\Customer\Interceptor->setType() at /var/www/html/app/code/Magento/Customer/Model/ResourceModel/Customer.php:87
01:59:55 [Build Functional CE]  Magento\Customer\Model\ResourceModel\Customer->__construct() at /var/www/html/generated/code/Magento/Customer/Model/ResourceModel/Customer/Interceptor.php:14
01:59:55 [Build Functional CE]  Magento\Customer\Model\ResourceModel\Customer\Interceptor->__construct() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:121
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:66
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:70
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:167
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:273
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:236
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:34
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:59
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:70
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/html/app/code/Magento/Customer/Console/Command/UpgradeHashAlgorithmCommand.php:62
01:59:55 [Build Functional CE]  Magento\Customer\Console\Command\UpgradeHashAlgorithmCommand->__construct() at /var/www/html/generated/code/Magento/Customer/Console/Command/UpgradeHashAlgorithmCommand/Interceptor.php:14
01:59:55 [Build Functional CE]  Magento\Customer\Console\Command\UpgradeHashAlgorithmCommand\Interceptor->__construct() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:121
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:66
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:70
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:203
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:179
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:273
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:236
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:34
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:59
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:56
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\ObjectManager->create() at /var/www/html/setup/src/Magento/Setup/Model/ObjectManagerProvider.php:78
01:59:55 [Build Functional CE]  Magento\Setup\Model\ObjectManagerProvider->createCliCommands() at /var/www/html/setup/src/Magento/Setup/Model/ObjectManagerProvider.php:64
01:59:55 [Build Functional CE]  Magento\Setup\Model\ObjectManagerProvider->get() at /var/www/html/setup/src/Magento/Setup/Model/Installer.php:828
01:59:55 [Build Functional CE]  Magento\Setup\Model\Installer->installSchema() at n/a:n/a
01:59:55 [Build Functional CE]  call_user_func_array() at /var/www/html/setup/src/Magento/Setup/Model/Installer.php:371
01:59:55 [Build Functional CE]  Magento\Setup\Model\Installer->install() at /var/www/html/setup/src/Magento/Setup/Console/Command/InstallCommand.php:221
01:59:55 [Build Functional CE]  Magento\Setup\Console\Command\InstallCommand->execute() at /var/www/html/vendor/symfony/console/Command/Command.php:255
01:59:55 [Build Functional CE]  Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/console/Application.php:1012
01:59:55 [Build Functional CE]  Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:272
01:59:55 [Build Functional CE]  Symfony\Component\Console\Application->doRun() at /var/www/html/lib/internal/Magento/Framework/Console/Cli.php:115
01:59:55 [Build Functional CE]  Magento\Framework\Console\Cli->doRun() at /var/www/html/vendor/symfony/console/Application.php:148
01:59:55 [Build Functional CE]  Symfony\Component\Console\Application->run() at /var/www/html/bin/magento:23
01:59:55 [Build Functional CE] 
01:59:55 [Build Functional CE] In Mysql.php line 91:
01:59:55 [Build Functional CE]                                                                                
01:59:55 [Build Functional CE]   [PDOException (42S02)]                                                       
01:59:55 [Build Functional CE]   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2_prod.ea  
01:59:55 [Build Functional CE]   v_entity_type' doesn't exist                                                 
01:59:55 [Build Functional CE]                                                                                
01:59:55 [Build Functional CE] 
01:59:55 [Build Functional CE] Exception trace:
01:59:55 [Build Functional CE]   at /var/www/html/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php:91
01:59:55 [Build Functional CE]  PDOStatement->execute() at /var/www/html/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php:91
01:59:55 [Build Functional CE]  Magento\Framework\DB\Statement\Pdo\Mysql->Magento\Framework\DB\Statement\Pdo\{closure}() at /var/www/html/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php:107
01:59:55 [Build Functional CE]  Magento\Framework\DB\Statement\Pdo\Mysql->tryExecute() at /var/www/html/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php:92
01:59:55 [Build Functional CE]  Magento\Framework\DB\Statement\Pdo\Mysql->_execute() at /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Statement.php:303
01:59:55 [Build Functional CE]  Zend_Db_Statement->execute() at /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php:480
01:59:55 [Build Functional CE]  Zend_Db_Adapter_Abstract->query() at /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php:238
01:59:55 [Build Functional CE]  Zend_Db_Adapter_Pdo_Abstract->query() at /var/www/html/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php:545
01:59:55 [Build Functional CE]  Magento\Framework\DB\Adapter\Pdo\Mysql->_query() at /var/www/html/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php:612
01:59:55 [Build Functional CE]  Magento\Framework\DB\Adapter\Pdo\Mysql->query() at /var/www/html/generated/code/Magento/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php:128
01:59:55 [Build Functional CE]  Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->query() at /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php:737
01:59:55 [Build Functional CE]  Zend_Db_Adapter_Abstract->fetchAll() at /var/www/html/generated/code/Magento/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php:1558
01:59:55 [Build Functional CE]  Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->fetchAll() at /var/www/html/lib/internal/Magento/Framework/Data/Collection/Db/FetchStrategy/Query.php:21
01:59:55 [Build Functional CE]  Magento\Framework\Data\Collection\Db\FetchStrategy\Query->fetchAll() at /var/www/html/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php:781
01:59:55 [Build Functional CE]  Magento\Framework\Data\Collection\AbstractDb->_fetchAll() at /var/www/html/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php:676
01:59:55 [Build Functional CE]  Magento\Framework\Data\Collection\AbstractDb->getData() at /var/www/html/app/code/Magento/Eav/Model/Config.php:387
01:59:55 [Build Functional CE]  Magento\Eav\Model\Config->_initEntityTypes() at /var/www/html/app/code/Magento/Eav/Model/Config.php:426
01:59:55 [Build Functional CE]  Magento\Eav\Model\Config->getEntityType() at /var/www/html/app/code/Magento/Eav/Model/Entity/AbstractEntity.php:322
01:59:55 [Build Functional CE]  Magento\Eav\Model\Entity\AbstractEntity->setType() at /var/www/html/generated/code/Magento/Customer/Model/ResourceModel/Customer/Interceptor.php:180
01:59:55 [Build Functional CE]  Magento\Customer\Model\ResourceModel\Customer\Interceptor->setType() at /var/www/html/app/code/Magento/Customer/Model/ResourceModel/Customer.php:87
01:59:55 [Build Functional CE]  Magento\Customer\Model\ResourceModel\Customer->__construct() at /var/www/html/generated/code/Magento/Customer/Model/ResourceModel/Customer/Interceptor.php:14
01:59:55 [Build Functional CE]  Magento\Customer\Model\ResourceModel\Customer\Interceptor->__construct() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:121
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:66
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:70
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:167
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:273
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:236
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:34
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:59
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:70
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/html/app/code/Magento/Customer/Console/Command/UpgradeHashAlgorithmCommand.php:62
01:59:55 [Build Functional CE]  Magento\Customer\Console\Command\UpgradeHashAlgorithmCommand->__construct() at /var/www/html/generated/code/Magento/Customer/Console/Command/UpgradeHashAlgorithmCommand/Interceptor.php:14
01:59:55 [Build Functional CE]  Magento\Customer\Console\Command\UpgradeHashAlgorithmCommand\Interceptor->__construct() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:121
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:66
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:70
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:203
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:179
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:273
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:236
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:34
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:59
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:56
01:59:55 [Build Functional CE]  Magento\Framework\ObjectManager\ObjectManager->create() at /var/www/html/setup/src/Magento/Setup/Model/ObjectManagerProvider.php:78
01:59:55 [Build Functional CE]  Magento\Setup\Model\ObjectManagerProvider->createCliCommands() at /var/www/html/setup/src/Magento/Setup/Model/ObjectManagerProvider.php:64
01:59:55 [Build Functional CE]  Magento\Setup\Model\ObjectManagerProvider->get() at /var/www/html/setup/src/Magento/Setup/Model/Installer.php:828
01:59:55 [Build Functional CE]  Magento\Setup\Model\Installer->installSchema() at n/a:n/a
01:59:55 [Build Functional CE]  call_user_func_array() at /var/www/html/setup/src/Magento/Setup/Model/Installer.php:371
01:59:55 [Build Functional CE]  Magento\Setup\Model\Installer->install() at /var/www/html/setup/src/Magento/Setup/Console/Command/InstallCommand.php:221
01:59:55 [Build Functional CE]  Magento\Setup\Console\Command\InstallCommand->execute() at /var/www/html/vendor/symfony/console/Command/Command.php:255
01:59:55 [Build Functional CE]  Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/console/Application.php:1012
01:59:55 [Build Functional CE]  Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:272
01:59:55 [Build Functional CE]  Symfony\Component\Console\Application->doRun() at /var/www/html/lib/internal/Magento/Framework/Console/Cli.php:115
01:59:55 [Build Functional CE]  Magento\Framework\Console\Cli->doRun() at /var/www/html/vendor/symfony/console/Application.php:148
01:59:55 [Build Functional CE]  Symfony\Component\Console\Application->run() at /var/www/html/bin/magento:23
```

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @atwixfirster,
Could you check test failure and fix it?

**Comment by ihor-sviziev** [comment]
@slavvka thank you!

**Comment by atwixfirster** [comment]
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2_prod.eav_entity_type' doesn't exist                                                 

I can not reproduce this error. But regarding to information from log we have the next situation:
- we run `bin/magento customer:hash:upgrade` command when `eav_entity_type` table does not exist. 

I am not sure how is it possible.

My opinion: there is a bug in the script which trigger `bin/magento customer:hash:upgrade`. My changes do not impact on the mentioned error.

Thanks!

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@atwixfirster,
As we discussed in Slack:
1. probably issue caused by dependencies, please declare using Proxy in di.xml file, it should solve the issue
2. Class isn't marked as `@api`, so new constructor arguments shouldn't be optional.

Please update your PR.

**Comment by ihor-sviziev** [comment]
@atwixfirster  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
