### PR TITLE
Fix for #20527 [Admin] Configurable product variations table cell labels wrong position

### PR DESCRIPTION
**Pull request by vasilii-b**
### Description (*)
Made configurable product variations table body cell label hidden, because they were positioned (absolute) all in on place above the table.
xnip2019-01-23_14-34-51

### Fixed Issues (if relevant)
1. magento/magento2#20527: [Admin] Configurable product variations table cell labels wrong position

### Manual testing scenarios (*)
Provided in the issue description.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-3963](https://jira.corp.magento.com/browse/ENGCOM-3963) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @vasilii-b , thanks for your contribution! Is it possible to remove the unneeded element instead of hiding it?

**Comment by vasilii-b** [comment]
Hi @sivaschenko,
I've changed the way labels are hidden. Can you please take a look ? Thank you!

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3963](https://jira.corp.magento.com/browse/ENGCOM-3963) has been created to process this Pull Request

**Pull request merged**
