### PR TITLE
fixed checker for strpos

### PR DESCRIPTION
**Pull request by oscarsanch**
### Fixed Issues (if relevant)

1. magento/magento2#12502: Admin controller redirects to frontend

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Hi @oscarsanch,
In general your changes looks good, and reasonable, but I'm not sure what 

Could you provide exact steps to reproduce?
Provided code in the issue:
```
$redirectUrl = $this->_redirect->getRedirectUrl($this->getUrl('*'));
$this->getResponse()->setRedirect($redirectUrl);
```

Controller action should return result object. Does it reproduces in such case?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @oscarsanch,
In general your changes looks good, and reasonable, but I'm not sure what 

Could you provide exact steps to reproduce?
Provided code in the issue is really outdated:
```
$redirectUrl = $this->_redirect->getRedirectUrl($this->getUrl('*'));
$this->getResponse()->setRedirect($redirectUrl);
```

Controller action should return result object. Does it reproduces in such case?

**Comment by ihor-sviziev** [comment]
Hi @oscarsanch,
There also test failures in unit, integration and functinal tests, looks like your change broke some functionality. Please double check it.

**Comment by VladimirZaets** [comment]
@oscarsanch, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Comment by VladimirZaets** [comment]
Hi @oscarsanch . Thanks for collaboration. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

**Comment by GuiltyNL** [comment]
I'm testing this pull request on my staging server and all seems to be working fine. It fixes the redirect issue and I'm not able to find something that is broken.

However the automated testing found something broken in the Wishlist part, but I'm not sure what should be broken. I'm manually testing the Wishlist behaviour and everything seems to be working like it should.

[This](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/25563/2ba4579fe434edfb7cf54fd3a7b01b09/Integration/allure-report-ce/index.html#suites/7bb6b6141696737e8cb4b1733d22336f/d7f87e2e40ceb4fa/) is the part of the test that mentions the issue.

Can @akaplya or @ihor-sviziev give me more information where to look for this failure?

And what about those 'Functional Tests' I see a lot of errors there, but on my staging server I don't see any errors at all.

@oscarsanch Thanks for this pull request. We were having a lot of redirect issues in our backend, making it difficult to work with when a module searched for a ReferralUrl. And with this fix we seem to be back on track.

**Comment by GuiltyNL** [comment]
In the mean while I did discover some issues related to redirects while the PR is applied.

For example, normally when you apply a cart discount code in a shopping cart, it applies and after that you stay in the cart. With the PR applied, I'm being redirected to the homepage of the shop.

The same for writing a product review for a product. Without the PR applied, after submitting the review, you stay on the product page. But with the PR applied you are being redirected to the homepage.

**Review by ihor-sviziev — DISMISSED** [review]
Hi @oscarsanch,
Looks like your fix is incorrect as it causes regression in some modules, for more details you could see following comment https://github.com/magento/magento2/pull/25563#issuecomment-590072690

Could you update your solution?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
See my prev. review

**Comment by ihor-sviziev** [comment]
@oscarsanch I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
