### PR TITLE
Fix Product Option Price Format

### PR DESCRIPTION
**Pull request by Stoyvo**
### Description (*)
TypeError: Unsupported operand types: int - string in /var/www/html/vendor/magento/module-catalog/Block/Product/View/Options/AbstractOptions.php:190

Sometimes $value['pricing_value'] is of value "" (many reasons as to why).

This function should practice defensive programming and not assume every value is numeric.

### Manual testing scenarios (*)

1. Add product option without price modified (default 0.00)
2. Product option price is still defined ""

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Stoyvo** [comment]
@magento run all tests

**Comment by asim-blueprintprep** [comment]
Is there anyone who can explain why the builds are failing?
All I get is a 404:
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36247/c2b2fd0281143bf1927edc6efa7c5b8c/Functional/allure-report-b2b/index.html

Will mark as complete for now.

**Comment by Stoyvo** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @Stoyvo,

Thanks for the contribution!

As part of the [Definition of Done](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1), please cover the changes with some automated tests.

Thanks

**Comment by Stoyvo** [comment]
> Hello @Stoyvo,
> 
> Thanks for the contribution!
> 
> As part of the [Definition of Done](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1), please cover the changes with some automated tests.
> 
> Thanks

Do any tests exist on the existing function?

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
Hello @Stoyvo
 
Thank you for your contribution!
 
I attempted to replicate the issue but was unable to do so. I followed the steps below:

- Created a product with options (e.g., Color).
- Viewed the product on the frontend(No error).
- Placed the order successfully (see attached screenshot).

Although I believe this change is important, could you please provide some manual testing steps to help me replicate the issue more accurately?
 
 
image
image

 
Thanks again for your assistance!

**Comment by engcom-Dash** [comment]
@Stoyvo- Closing this PR due to no response to the last https://github.com/magento/magento2/pull/36247#issuecomment-2337597085. Feel free to reopen it.

**Pull request closed without merging**
