### PR TITLE
Allow for referenceBlock to include template argument

### PR DESCRIPTION
**Pull request by jissereitsma**
Reference https://github.com/magento/magento2/issues/9771

### CODE REVIEW

**Comment by korostii** [comment]
This is a great suggestion! 
But shouldn't the element type be `xs:string` instead of `xs:boolean`?

**Comment by jissereitsma** [comment]
@korostii OMG, sure it needs to be `string` instead of `boolean`. Sorry for being so careless and thanks for spotting that glitch. Never make a PR after drinking 2 beers on a warm Sunday afternoon.

**Review by korostii — APPROVED** [review]

**Review by maghamed — APPROVED** [review]
Nice catch!

**Comment by fooman** [comment]
>Never make a PR after drinking 2 beers on a warm Sunday afternoon.

@jissereitsma where is the fun in that?

**Comment by magento-team** [comment]
@jissereitsma thank you for your contribution. Your Pull Request has been successfully merged

**Pull request merged**
