### PR TITLE
fix verticle spacing issue in minicart widget

### PR DESCRIPTION
**Pull request by rsatish1017**
### Preconditions (*)

1. Magento version 2.3.4

### Steps to reproduce (*)

1.Add product into cart
2.click on mini cart button

### Expected result

1. "View and Edit Cart" link should be vertically aligned.
minicart-fix

### Actual result (*)

minicart-issue

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
unit tests fails not related with changes

**Comment by mrtuvn** [comment]
@rsatish1017 Seem your PR remove bottom padding is not solve exactly problem.
If you inspect further you can see the div empty inside that cause increase height in minicart
Screenshot from 2020-04-29 17-39-42

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
@rsatish1017 Hi, thanks for collaboration, looks like your PR doesn't fix the problem? can you please check it?

**Comment by engcom-Charlie** [comment]
Hi @rsatish1017, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
