### PR TITLE
protect setUp(), abstract test-case

### LINKED ISSUE #2985: What is the rationale behind making BaseTestCase::setUp() public
In https://github.com/magento/magento2/blob/077584c99ebb8007cad176c3b9a0144a05c259cd/lib/internal/Magento/Framework/TestFramework/Unit/BaseTestCase.php#L23

the protected defined `setUp()` method is implemented as public.

What is the rationale of making it part of the public interface of the test-case type?

### PR DESCRIPTION
**Pull request by ktomk**
the setUp() method has been declared public previously. while this is not technically an error, there is no need in changing the visibility.

this commit addresses the issue by reverting test-cases setUp() methods visibility from public back to protected.

additionally the BaseTestCase in Magento\Framework\TestFramework\Unit is made abstract. this has been done because it would otherwise be identified as test-case with no tests while it's only an abstract one.

further additionally some docblocks are added to address code sniffer warnings.

fixes #2985

### CODE REVIEW

**Comment by vancoz** [comment]
Hi @ktomk, thank you for contribution, internal ticket number is MAGETWO-48212

**Comment by ktomk** [comment]
Just seeing you've got lot's of changes. I refresh my changes against the current development version and reviewed my changes again.

Previous Travis Build: https://travis-ci.org/magento/magento2/builds/103227264 

For reference: I us a slightly different command ([compared to here](https://github.com/magento/magento2/issues/2985#issuecomment-171602661)) to edit the test-files via sed as I'm using linux (differences in sed) and I also wanted to make it more explicitly and talkative (differences in find parameters):

```
find lib/internal app/code/Magento -type f -name '*.php' -path '*/Test/*' -print -exec sed -i -e 's/public function setUp(/protected function setUp(/' {} \;
```

To verfiy if all file have been covered I use:

```
find lib/internal app/code/Magento -type f -name '*.php' -path '*/Test/*' -exec grep -q 'function public function setUp(' {} \;  -print
```

**Comment by vancoz** [comment]
Hello @ktomk, can you please pull new code and review you changes again?
I'm ready to pick it up and proceed.

**Comment by vancoz** [comment]
@ktomk, I have merged it and right now marshaling it according to our internal flow.

**Comment by mazhalai** [comment]
@ktomk thank you for your contribution, your PR has been merged.

**Pull request merged**
