### PR TITLE
[Forwardport] Added checks to see if the payment is available

### PR DESCRIPTION
**Pull request by gelanivishal**
### Original Pull Request
https://github.com/magento/magento2/pull/15683

Fix an error while submitting an order without payment method.

### Description
When submitting an order using the rest api without an payment, you would get an exception/error report due to the fact there was not payment method.

### Fixed Issues (if relevant)
1. magento/magento2#15652: REST API create order POST /V1/orders

### Manual testing scenarios
1.  Send an POST request to the rest/V1/orders endpoint containing the following:
``
{ "entity": { "base_grand_total" : 100, "customer_email" : "user@domain.tld", "grand_total" : 100, "items" : [ { "sku" : "TESTSEB" } ] } }
``

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by sidolov** [comment]
Hi @gelanivishal , please, add following commit to this port: 7bc5df750b7b730804985af1ef217c5708bbee93
Thank you!

**Comment by gelanivishal** [comment]
@sidolov Added.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3156](https://jira.corp.magento.com/browse/ENGCOM-3156) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
