### PR TITLE
[MFTF] use action group go to attribute grid page

### PR DESCRIPTION
**Pull request by Usik2203**
This PR use `AdminOpenProductAttributePageActionGroup` to go to `ProductAttributeGridPage`

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Review by lbajsarowicz — APPROVED** [review]
Another great catch. Thank you.
If you don't mind, change the words order to have subject (product attribute page) first and then action (page open)

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7774](https://jira.corp.magento.com/browse/ENGCOM-7774) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by Usik2203** [comment]
Hi @lbajsarowicz 
Yes I can do it . But I think it's a backward-incompatible change since 3rd party modules may rely on this core action group. 
What do you think ?
Thanks.

**Comment by lbajsarowicz** [comment]
Yes, you are right :+1: I haven't noticed that was already there.

**Comment by engcom-Delta** [comment]
**Notice:** QA not applicable

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Pull request merged**
