### PR TITLE
category cms block to schema

### PR DESCRIPTION
**Pull request by danrcoull**
### Description (*)
This allows graphql for category to include cmsBlock as part of that query, returning a rendered static block if assigned to the category and called with landing_page

### Manual testing scenarios (*)
Install and configure pwa-studio, in graphql playground, you can open getCategory query  and add the following:

```
landing_page
    				categoryBlock {
              identifier
              content
            }
```
this will return an assigned static block.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21828) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @danrcoull. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
Hi @danrcoull. Thank you for your contribution.  I would suggest moving this PR to the GraphQl repository (https://github.com/magento/graphql-ce)

**Comment by danrcoull** [comment]
Grand will do

**Pull request closed without merging**
