### PR TITLE
Replace repetitive actions with Action Groups in AdminConfigurableProductChildrenOutOfStockTest

### LINKED ISSUE #32378: [Issue] Replace repetitive actions with Action Groups in AdminConfigurableProductChildrenOutOfStockTest
This issue is automatically created based on existing pull request: magento/magento2#32293: Replace repetitive actions with Action Groups in AdminConfigurableProductChildrenOutOfStockTest

---------

### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32378: Replace repetitive actions with Action Groups in AdminConfigurableProductChildrenOutOfStockTest

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests EE, Functional Tests B2B, Static Tests

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B

**Review by eduard13 — CHANGES_REQUESTED** [review]
Thank you @kate-kyzyma for the improvements. Can we implement the new ActionGroup through all the tests that have `<fillField selector="{{AdminProductFormSection.productQuantity}}"...`?
Thank you.

**Comment by engcom-Charlie** [comment]
Hi @kate-kyzyma, @eduard13,

Thanks for your contribution!

I am working on the requested changes. I will implement the new ActionGroup from this PR “AdminFillProductQtyOnProductFormActionGroup” through all the tests that have <fillField selector="{{AdminProductFormSection.productQuantity}}". 

Thank you!

**Comment by engcom-Charlie** [comment]
I have merged magento 2.4-develop branch in this PR repo.

**NOTE**: It has been found that "AdminFillProductQtyOnProductFormActionGroup" i.e. app/code/Magento/Catalog/Test/Mftf/ActionGroup/AdminFillProductQtyOnProductFormActionGroup.xml file is already present on magento 2.4-develop branch so it got removed from this PR changes after merge.

Now will use “AdminFillProductQtyOnProductFormActionGroup” through all the tests that have <fillField selector="{{AdminProductFormSection.productQuantity}}". Working on it.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @eduard13,

I have worked on the suggested review changes by you. Now we are using “AdminFillProductQtyOnProductFormActionGroup” through all the tests that have <fillField selector="{{AdminProductFormSection.productQuantity}}".

Requesting you for review.

Thank You!

**Review by eduard13 — APPROVED** [review]
Thank you @engcom-Charlie for the applied changes.

**Comment by eduard13** [comment]
@magento run all tests

**Pull request merged**
