### PR TITLE
Fix  #26083 - problem with unsAdditionalInformation in \Magento\Payment\Model\Info

### LINKED ISSUE #26083: Problem when trying to unset additional data in payment method.
### Preconditions (*)
1. Magento 2.3.2 & PHP 7.2.21

### Steps to reproduce (*)
1. You must use \Magento\Payment\Model\Info::setAdditionalInformation to add an additional information to a payment method;
2. Try to use \Magento\Payment\Model\Info::unsAdditionalInformation to remove the inserted additional data.

### Expected result (*)
1. \Magento\Payment\Model\Info::unsAdditionalInformation should remove an additional information from table quote_payment column additional_information after save the quote.

### Actual result (*)
1. \Magento\Payment\Model\Info::unsAdditionalInformation didn't remove the data in additional_information (column)

### PR DESCRIPTION
**Pull request by marcoaacoliveira**
### Description (*)
Fix problem with unsAdditionalInformation method in \Magento\Payment\Model\Info, it wasn't init data properly.

### Fixed Issues (if relevant)
1. #26083: Problem when trying to unset additional data in payment method

### Manual testing scenarios (*)
1. Method used
2. Quote saved
3. Additional information was successful removed from database. 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by aleron75** [comment]
Hello @marcoaacoliveira, thanks for your contribution.

Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. 

For this specific case, you should cover your fix by automated tests with the scenario which leads to the issue: tests should fail on the mainline and pass with your fix.

To answer the question _"which kind of tests should I write"_, the answer is:
pick the most lightweight (execution time-wise) test type that will provide sufficient coverage.

Thanks again!

**Comment by marcoaacoliveira** [comment]
@aleron75 thanks for reviewing, I'll work on it.

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-6524](https://jira.corp.magento.com/browse/ENGCOM-6524) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@marcoaacoliveira thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
