### PR TITLE
Fall back to parent directory if composer.json not found in module directory

### PR DESCRIPTION
**Pull request by schmengler**
### Description
This change allows modules to follow the [pds/skeleton](https://github.com/php-pds/skeleton) standard and have their source code in a `src` subdirectory of the repository.

### Manual testing scenarios

1. create a module with `composer.json` and `registration.php` in the root directory and source code in `src`

    registration.php
    ```
    \Magento\Framework\Component\ComponentRegistrar::register(
        \Magento\Framework\Component\ComponentRegistrar::MODULE,
        'Vendor_Module',
        __DIR__ . '/src'
    );
    ```

    composer.json
    ```
      "autoload": {
        "files": [
          "registration.php"
        ],
        "psr-4": {
          "Vendor\\Module\\": "src"
        }
      },
      "suggest": {
        "vendor/module-sample-data": "Sample Data version:1.0.0"
      },
    ```
2. call `bin/magento sampledata:deploy` and see if `vendor/module-sample-data` is going to be installed.

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by schmengler** [comment]
Another case where Magento reads `composer.json` files from modules is `\Magento\Framework\Module\PackageInfo`. This is a bit more complicated to change and test, so it would be a different PR

**Comment by fooman** [comment]
hey @schmengler love the direction of this PR. It is currently [already possible to have the code under src/](https://github.com/fooman/printorderpdf-m2) with the registration file sitting under `src/registration.php` and then reference it from a root `composer.json` file as `src/registration.php`. The only place where this falls over as you mentioned is in `\Magento\Framework\Module\PackageInfo` (I currently solve it by providing an alternative `src/composer.json` which is not ideal).

I had looked into this here https://github.com/magento/magento2/issues/3400. My current thought to solve this across the board would be to add a new optional param to `\Magento\Framework\Component\ComponentRegistrar::register()` which holds the `composer.json` file location which can then be used in `PackageInfo` to find the correct file. If empty it's assumed to be in the same folder as `registration.php` (aka current behaviour).

**Comment by schmengler** [comment]
@fooman Good idea with the optional parameter, that would give even more flexibility! Putting registration.php in `src` was my first approach too but I remember this caused trouble because of assumptions in Magento. Duplicating composer.json is a workaround but that cannot be the solution

**Comment by okorshenko** [comment]
Hi @schmengler thank you for your contribution. Could you please fix broken static tests. Also we are getting Fatal error with this changes. 
`PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\Framework\Filesystem\DriverInterface`
Could you please verify your changes. Thank you

**Comment by Ctucker9233** [comment]
@magento-team can this be ported to 2.2?

**Pull request merged**
