### PR TITLE
Updating with StorefrontSelectCustomizeAndAddToTheCartButtonActionGroup

### LINKED ISSUE #31437: [Issue] Updating with StorefrontSelectCustomizeAndAddToTheCartButtonActionGroup
This issue is automatically created based on existing pull request: magento/magento2#31436: Updating with StorefrontSelectCustomizeAndAddToTheCartButtonActionGroup

---------
### Description (*)
Updating test with StorefrontSelectCustomizeAndAddToTheCartButtonActionGroup

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
Updating test with StorefrontSelectCustomizeAndAddToTheCartButtonActionGroup

### Resolved issues:
1. [x] resolves magento/magento2#31437: Updating with StorefrontSelectCustomizeAndAddToTheCartButtonActionGroup

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8573](https://jira.corp.magento.com/browse/ENGCOM-8573) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** Functional Tests B2B and Functional Tests EE are failed

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
