### PR TITLE
[32018][To 2.4-develop] Marked GraphQl, ImportExport, Indexer, Integration and LoginAsCustomer interfaces as API

### LINKED ISSUE #32018: Mark GraphQl, ImportExport, Indexer, Integration and LoginAsCustomer interfaces as API
The following interfaces should be marked as API in 2.4-develop branch
1. app/code/Magento/GraphQl/Controller/HttpHeaderProcessorInterface.php
1. app/code/Magento/GraphQl/Controller/HttpRequestValidatorInterface.php
1. app/code/Magento/GraphQl/Model/Query/ContextInterface.php
1. app/code/Magento/GraphQl/Model/Query/ContextParametersInterface.php
1. app/code/Magento/GraphQl/Model/Query/ContextParametersProcessorInterface.php
1. app/code/Magento/ImportExport/Api/Data/ExtendedExportInfoInterface.php
1. app/code/Magento/ImportExport/Model/Report/ReportProcessorInterface.php
1. app/code/Magento/Indexer/Model/ModeSwitcherInterface.php
1. app/code/Magento/Indexer/Model/Source/DataInterface.php
1. app/code/Magento/Integration/Model/Oauth/Token/RequestLog/ReaderInterface.php
1. app/code/Magento/Integration/Model/Oauth/Token/RequestLog/WriterInterface.php
1. app/code/Magento/LoginAsCustomerApi/Api/Data/IsLoginAsCustomerEnabledForCustomerResultInterface.php
1. app/code/Magento/LoginAsCustomerApi/Api/GetLoggedAsCustomerAdminIdInterface.php
1. app/code/Magento/LoginAsCustomerApi/Api/GetLoggedAsCustomerCustomerIdInterface.php
1. app/code/Magento/LoginAsCustomerApi/Api/IsLoginAsCustomerEnabledForCustomerInterface.php
1. app/code/Magento/LoginAsCustomerApi/Api/SetLoggedAsCustomerAdminIdInterface.php
1. app/code/Magento/LoginAsCustomerApi/Api/SetLoggedAsCustomerCustomerIdInterface.php
1. app/code/Magento/LoginAsCustomerAssistance/Api/ConfigInterface.php
1. app/code/Magento/LoginAsCustomerAssistance/Api/IsAssistanceEnabledInterface.php
1. app/code/Magento/LoginAsCustomerAssistance/Api/SetAssistanceInterface.php

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixes #32018

### Related Pull Requests

https://github.com/magento/magento2/pull/32169

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32018>

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by danielrussob** [comment]
@magento run Integration Tests, Static Tests, Unit Tests

**Comment by aleron75** [comment]
Hello @Usik2203
I've verified that this PR contains all the changes requested in related issue #32018 plus the following:

- `app/code/Magento/Indexer/Model/DimensionModes.php`
- `lib/internal/Magento/Framework/App/HttpRequestInterface.php`

can you please explain where do these additional files come from?

Thanks!

**Comment by Usik2203** [comment]
> Hello @Usik2203
> I've verified that this PR contains all the changes requested in related issue #32018 plus the following:
> 
> * `app/code/Magento/Indexer/Model/DimensionModes.php`
> * `lib/internal/Magento/Framework/App/HttpRequestInterface.php`
> 
> can you please explain where do these additional files come from?
> 
> Thanks!

Hi @aleron75 
These classes were marked based on these comments
https://github.com/magento/magento2/pull/32169#pullrequestreview-595086095
https://github.com/magento/magento2/pull/32169#issuecomment-785919099

**Review by danielrussob — APPROVED** [review]

**Review by aleron75 — APPROVED** [review]

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama the branch with code successfully imported into`magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-32727`.

**Pull request merged**
