### PR TITLE
[backport] Special Price shown without currency symbol in magento backoffice

### PR DESCRIPTION
**Pull request by XxXgeoXxX**
Base issue: #20472

### Description (*)
Magento 2.3.X
Magento 2.2.X

#### Steps to reproduce (*)
Navigate to admin catalog product grid
Using "Columns" selection add 'Special Price' column in the grid

#### Expected result (*)
Special Price will be shown with currency code

#### Actual result (*)
Special Price showed without currency code.

### Fixed Issues (if relevant)
Backport for https://github.com/magento/magento2/pull/20474

### Manual testing scenarios (*)
Navigate to admin catalog product grid
Using "Columns" selection add 'Special Price' column in the grid

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by XxXgeoXxX** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX, here is your [new Magento instance](https://pr-20475.instances.magento-community.engineering).
Admin access: [https://pr-20475.instances.magento-community.engineering/admin](https://pr-20475.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by XxXgeoXxX** [comment]
merge conflict was resolved

**Comment by sidolov** [comment]
Hi @XxXgeoXxX , I'm closing this PR because original was closed due to inactivity. Please, reopen original PR if you wish to continue. 
Thank you!

**Pull request closed without merging**
