### PR TITLE
Reference pull request of #18604 for 2.3-develop

### PR DESCRIPTION
**Pull request by mahesh-rajawat**
Fixed issue of product with a special price of 0.00, this is not shown on the frontend. Not in the product listings and also not on the product detail page.

### Description (*)
Product Special Price is set to 0 then its not visible on product listing and Product View page, but when
we add product in cart, its price added to 0 in cart. In this pull request i have fixed this issue, now
Special price is displaying 0 as well. 

### Fixed Issues (if relevant)

1. magento/magento2#18268: Special price of 0.0000 is not shown on frontend, but is calculated in car

### Manual testing scenarios (*)

1. Created new product and set the special price 0 and saved it.
2. Open product in category page special price is displaying 0 as normal.
3. Open product in product view page special price is displaying 0.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

Port for: https://github.com/magento/magento2/pull/18604

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18631) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by rodrigowebjump — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-3194](https://jira.corp.magento.com/browse/ENGCOM-3194) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@maheshWebkul721 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by mahesh-rajawat** [comment]
#SQUASHTOBERFEST

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
