### PR TITLE
Properly transliterate German Umlauts

### PR DESCRIPTION
**Pull request by amenk**
In Germany, ö is transliterated oe and so on.

### Description (*)

Bälle becomes balle in URLs, but definitely should be "baelle"

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @amenk. Thanks for collaboration. Please fix static tests

**Comment by amenk** [comment]
@VladimirZaets I wish I could but I don't want too ;-)

Seriously, I did not introduce the problem highlighted in the static tests ... it's just occuring because I touched the file I think.
And I do not want to write a meaningless doc-block for the class, right now.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5153](https://jira.corp.magento.com/browse/ENGCOM-5153) has been created to process this Pull Request

**Comment by amenk** [comment]
I was told the swedish might not like this pull request ... we might need a transliteration by locale ...

**Comment by sdzhepa** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [new Magento instance](https://pr-22989.instances.magento-community.engineering).
Admin access: [https://pr-22989.instances.magento-community.engineering/admin](https://pr-22989.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sdzhepa** [comment]
✔ QA Passed

**Comment by hostep** [comment]
> I was told the swedish might not like this pull request ... we might need a transliteration by locale ...

Indeed, I was thinking about this as well.

Magento is working on url transliteration for Japanese over here: https://github.com/magento/magento2-jp/pull/77
Maybe this can be extended so it supports many languages... But that [`Transliterator`](https://www.php.net/manual/en/class.transliterator.php) class is pretty complex, has very little documentation, and I'm not sure if they support these "easier" languages like German or Swedish: https://3v4l.org/aWqOo

Alternatively, I also found [`voku/urlify`](https://packagist.org/packages/voku/urlify), and that one also seems to work pretty good.

For example:
```
composer require voku/urlify
```

```php
<?php

require_once('vendor/autoload.php');

use voku\helper\URLify;

echo 'de: ' . URLify::slug('Weiß Goldmann Göbel Weiss Göthe Goethe und Götz Ä Ö Ü ä ö ü', 'de', '-', true) . "\n";
echo 'sv: ' . URLify::slug('Weiß Goldmann Göbel Weiss Göthe Goethe und Götz Ä Ö Ü ä ö ü', 'sv', '-', true) . "\n";
echo 'fi: ' . URLify::slug('Weiß Goldmann Göbel Weiss Göthe Goethe und Götz Ä Ö Ü ä ö ü', 'fi', '-', true) . "\n";
```

Output:
```
de: weiss-goldmann-goebel-weiss-goethe-goethe-und-goetz-ae-oe-ue-ae-oe-ue
sv: weiss-goldmann-gobel-weiss-gothe-goethe-und-gotz-a-o-ue-a-o-ue
fi: weiss-goldmann-gobel-weiss-gothe-goethe-und-gotz-a-o-ue-a-o-ue
```

**Comment by orlangur** [comment]
> I was told the swedish might not like this pull request ... we might need a transliteration by locale ...

@sdzhepa @hostep so why is this merged?

**Comment by hostep** [comment]
I have no idea. This should probably be reverted.

We in Dutch also won't like this, we have words like for example `reünie` which we expect to see transliterated to `reunie` and not to `reuenie`

**Comment by sdzhepa** [comment]
Hello @orlangur, @hotstep and @amenk 

I put QA passed on this PR https://github.com/magento/magento2/pull/22989#issuecomment-496998652
And seems I understood this https://github.com/magento/magento2/pull/22989#issuecomment-495528177 in a wrong way. 
Not so critical as should...

Is it correct that we should rever this PR because it brings new issues into the current translations?

**Comment by orlangur** [comment]
@sdzhepa yep, please revert and let's report an issue in features repo or maybe somebody wants to propose locale-dependent transliteration into architecture repo.

**Pull request merged**
