### PR TITLE
Removes incorrect csp_whitelist.xml files

### LINKED ISSUE #30607: Somehow csp_whitelist.xml from Magento_Authorizenet ended up in Magento_CatalogUrlRewrite
### Summary (*)
Magento 2.4-develop

Somehow csp_whitelist.xml from Magento_Authorizenet ended up in Magento_CatalogUrlRewrite

csp_whitelist.xml for Magento_Authorizenet was added to app/code/Magento/Authorizenet/etc/csp_whitelist.xml in commit f4db9a422c331902b41a37f413706ec40168f6e9 but somehow ended up in wrong module in 2.4-develop. It is in https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogUrlRewrite/etc/csp_whitelist.xml

### Proposed solution
Delete file app/code/Magento/CatalogUrlRewrite/etc/csp_whitelist.xml since Magento_Authorizenet is not part of magento2 repository since https://docs.magento.com/user-guide/v2.3/payment/authorize-net-direct-post.html

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by hostep**
### Description (*)
Somehow 2 `csp_whitelist.xml` files were incorrectly renamed.
They previously existed in the Braintree and Authorizenet modules, but those modules no longer exist in Magento core, so they should have been removed instead of put in another module.

I assume these were incorrectly solved merge conflicts.

Commits which caused this:
- https://github.com/magento/magento2/commit/aec68c609ccc90f1a88e1c9ed55c50fe0ddecaed#diff-95fbf751fab0191251da0f2b611bd868fa0373bdeeb155d40e63c1cbbf95da24 (Authorizenet/etc/csp_whitelist.xml → CatalogUrlRewrite/etc/csp_whitelist.xml)
- https://github.com/magento/magento2/commit/35da140d4cf#diff-3efad9a9d36167d97a62982dd94834a346c7ddcd07bca440512af0ae3f898651 (Braintree/etc/csp_whitelist.xml → LoginAsCustomerAdminUi/etc/csp_whitelist.xml)

### Related Pull Requests
None

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/30607: Somehow csp_whitelist.xml from Magento_Authorizenet ended up in Magento_CatalogUrlRewrite

### Manual testing scenarios (*)
Not relevant, this is just a cleanup

### Questions or comments
Maybe somebody needs to review the two commits mentioned above to see if no other strange things happened in there?

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hostep** [comment]
@magento run all tests

**Comment by hostep** [comment]
If somebody knows the developers behind the Braintree module, can they redirect them to this comment: https://github.com/magento/magento2/issues/30607#issuecomment-715891995 so we are sure no regressions occur with their module?

**Comment by rogyar** [comment]
That's a really interesting issue. Thank you @hostep for addressing it.

**Comment by hostep** [comment]
Any updates here? Anything that needs to be done before this can move forwards? Thanks! 🙂

**Comment by rogyar** [comment]
@magento run all tests

**Review by rogyar — APPROVED** [review]
The failing tests are related to the date issue with the year change but no to the current changeset

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8600](https://jira.corp.magento.com/browse/ENGCOM-8600) has been created to process this Pull Request

**Comment by hostep** [comment]
Any updates here? PR has been open for almost half a year now 😉

**Comment by hostep** [comment]
Hi @Den4ik, it looks like you are quite active here lately and maybe you can help move this PR forward a bit?

Let me know if I should still do something here.

**Comment by Den4ik** [comment]
@magento run all tests

**Review by Den4ik — APPROVED** [review]
@hostep Totally agree with this changes

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-8600](https://jira.corp.magento.com/browse/ENGCOM-8600) has been created to process this Pull Request

**Comment by hostep** [comment]
One more month until the anniversary of this PR. I don't really understand why it takes so long to get processed?

**Comment by Den4ik** [comment]
Hi @hostep
On one of the community Hangouts core team said that currently they are looking only on high priority PRs. This PR has P3 priority that is not high and unfortunately I'm not sure that it will be merged soon

**Comment by hostep** [comment]
But that's not the way PR's should be handled. Priorities can apply to issues but shouldn't be applied to PR's, that's the wrong attitude.
Sure, super high prio PR's can have precedence, but you can't ignore PR's that have been open for many months, that's very discouraging to the contributors. You want contributors to come back to keep investing their precious free time into this open source product. Ignoring PR's is not encouraging at all to contributors. That's not they way you should treat your community.

And I'm not only talking about this PR, there are plenty of other PR's out there that have the same problem. So don't just now decide to merge this PR just to keep me from complaining while ignoring all the other long time open PR's please.

**Comment by Den4ik** [comment]
@hostep I'm totally agree with you

**Comment by hostep** [comment]
Thanks @Den4ik, can you maybe discuss this with the other community maintainers and try to change their minds with the current PR priority system?

This will probably be a problem of the past once [the new community organization driven fork](https://www.mage-os.community/blog/the-future-of-magento) comes into play somewhere in the future, but until that happens, we can try to improve the community relations as well over here I believe.

**Comment by hostep** [comment]
Thanks! 🙂

**Pull request merged**
