### PR TITLE
#13685: Upgrading jQuery to 3.3.1

### PR DESCRIPTION
**Pull request by kirmorozov**
* Updating jQuery to 3.3.1 (originally from npm)
* Updating jQuery Migrate 3.0.1 (originally from npm)
* jQuery Mobile 1.5.0-alpha.1, generated online

### Description
Upgrading initial jQuery and jQuery Migrate

In previous series:
https://github.com/magento/magento2/pull/14556 
https://github.com/magento/magento2/pull/14637

### Fixed Issues (if relevant)

1. magento/magento2#13685: Incompatibilies with jQuery 3
2. ...

### Manual testing scenarios
1. I can checkout without any problems
2. I can use admin without any problems

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@kirmorozov Closing and reopening Pull Request in order to trigger Travis CI build on it.

**Comment by kirmorozov** [comment]
Work in progress, resolving incompatibility problems with tabs in admin after jQuery-ui update.
from 1.9 to 1.12.

**Review by Igloczek — APPROVED** [review]

**Comment by kirmorozov** [comment]
@Igloczek Hi fellow, how many reviewers must approve to have it merged into the core?

**Comment by Igloczek** [comment]
@kirmorozov It's not defined, only community engineering team decide what should be merged.
The community can just give them advice if something looks good or not.

**Comment by kirmorozov** [comment]
@VladimirZaets let me know if there are any issues with complete regression.

**Comment by kirmorozov** [comment]
@okorshenko @VladimirZaets Do you need any help?

**Comment by kirmorozov** [comment]
@piotrekkaminski Can you merge it earlier to make sure vendors are compatible when release date comes?

**Comment by kirmorozov** [comment]
OK, there was only one bug:
MAGETWO-95280: Storefront Images Don't Scale Back To Original Size In Mobile
Easy one to kill.

**Comment by ihor-sviziev** [comment]
Hi,
Do you think it's a good idea to use "alpha" version of jquery mobile? I think it's better to use latest stable version

**Comment by sivaschenko** [comment]
The pull request was discussed on architecture meeting and it was decided to include it in major 2.4 release https://github.com/magento/architecture/issues/59#issue-395694087

**Comment by kirmorozov** [comment]
@ihor-sviziev As of jquery mobile, you can check difference yourself, no changes since forever.
https://github.com/jquery/jquery-mobile/compare/1.5.0-alpha.1...1.5.0-rc1

**Comment by kirmorozov** [comment]
Found issue with tabs in admin, resolved here for 2.3.1
https://github.com/morozov-group/magento2-edge/tree/2.3.1-jquery3
Feel free to try on your local
```bash
curl https://github.com/magento/magento2/compare/2.3.1...morozov-group:2.3.1-jquery3.patch |\
    sed 's#/app/code/Magento/Catalog/#/vendor/magento/module-catalog/#g' |\
    sed 's#/app/code/Magento/ConfigurableProduct/#/vendor/magento/module-configurable-product/#g' |\
    sed 's#/app/code/Magento/ProductVideo/#/vendor/magento/module-product-video/#g' |\
    sed 's#/app/code/Magento/Theme/#/vendor/magento/module-theme/#g' |\
    sed 's#/app/code/Magento/Ui/#/vendor/magento/module-ui/#g' |\
    sed 's#/app/code/Magento/User/#/vendor/magento/module-user/#g' > _jquery3.patch
patch -p1 --forward < _jquery3.patch
```

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @kirmorozov,
Finally branch 2.4-develop was created, now your PR could be merged! Could you resolve merge conflicts and update to the latest versions.

**Comment by BassemN** [comment]
@kirmorozov please upgrade to jQuery 3.4.1

**Review by krzksz — CHANGES_REQUESTED** [review]
I believe that since jQuery UI modules are now divided into separate files as of https://github.com/magento/magento2/commit/a5c67831e0b6d8974700e7cb134c054c6e9f3131, this PR has to be reworked.

**Comment by ihor-sviziev** [comment]
Hi @kirmorozov,
Are you interested in finalizing this pull request? 
It looks really amazing!

**Comment by ihor-sviziev** [comment]
@kirmorozov Unfortunately I need to close this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
