### PR TITLE
Add follow symlinks to support linked folders

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

https://github.com/magento/adobe-stock-integration/issues/1005

### Manual testing scenarios (*)
AdobeStock 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Sample data installed and linked from another folder

### Steps to reproduce (*)

1. Run command php bin/magento media-gallery:index
2. Open Media Gallery images grid

### Expected result (*)
1. Catalog folder with images

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @Nazar65. Would you, please, cover your change with an integration test? You may extend the [existing](https://github.com/magento/magento2/blob/66d2cbcfb0f2f8f1d83c515cdc869a7fbfafdd85/dev/tests/integration/testsuite/Magento/Framework/Filesystem/Driver/FileTest.php#L18) test. The [filedriver](https://github.com/magento/magento2/blob/66d2cbcfb0f2f8f1d83c515cdc869a7fbfafdd85/dev/tests/integration/testsuite/Magento/Framework/Filesystem/Driver/FileTest.php#L23) has a method for creating a symlink.

**Comment by Nazar65** [comment]
@rogyar dobe :heavy_check_mark:

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
Something strange going on CI tests "Database Compare tests" all green, and others not related to he changes in this pr

**Comment by rogyar** [comment]
The failing functional tests are not related to the current change

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7227](https://jira.corp.magento.com/browse/ENGCOM-7227) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

The subfolder appeared in folder tree
PR_27413_subfolder

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE, Functional Tests B2B, Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

**Pull request merged**
