### PR TITLE
Fix for magento/magento2#29315: \Magento\Config\Model\Config\Source\Email\Tem…

### LINKED ISSUE #29315: \Magento\Config\Model\Config\Source\Email\Template::toOptionArray throws error when setPath() is not called first
### Preconditions (*)

1. dev-2.4-develop

### Steps to reproduce (*)

1. Create a custom module, plugin, or Observer
2. Inject a concrete instance of \Magento\Framework\ObjectManagerInterface ($this->_objectManager) through the constructor
3. Execute the following:
```
$sourceModelObj = $this->_objectManager->create('\Magento\Config\Model\Config\Source\Email\Template');
$optionsArray = $sourceModelObj->toOptionArray();
```
4. Notice unhandled exception is written to the screen

### Expected result (*)

1. **Should not** throw an error
2. **Should** return default collection options

### Actual result (*)

```
Exception #0 (UnexpectedValueException): Email template '' is not defined.
<pre>#1 Magento\Email\Model\Template\Config->getTemplateLabel('') called at [vendor/magento/module-config/Model/Config/Source/Email/Template.php:64]
#2 Magento\Config\Model\Config\Source\Email\Template->toOptionArray() called at [app/code/Magesmith/ScopeExplorer/Block/Scopes.php:172]
#3 Magesmith\ScopeExplorer\Block\Scopes->getSourceModelValue('catalog_producta...') called at [app/code/Magesmith/ScopeExplorer/Block/Scopes.php:135]
#4 Magesmith\ScopeExplorer\Block\Scopes->getWebsiteScopeValue(&Magento\Store\Model\Website\Interceptor#00000000476d138d000000000886eb4d#) called at [app/code/Magesmith/ScopeExplorer/Block/Scopes.php:97]
#5 Magesmith\ScopeExplorer\Block\Scopes->hasScopeValue() called at [app/code/Magesmith/ScopeExplorer/view/adminhtml/templates/scopes.phtml:7]
#6 include('/mnt/f/www/local...') called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
#7 Magento\Framework\View\TemplateEngine\Php->render(&Magesmith\ScopeExplorer\Block\Scopes#00000000476d1f2e000000000886eb4d#, '/mnt/f/www/local...', array('csp' => &Magento\Csp\Helper\InlineUtil#00000000476d1d31000000000886eb4d#)) called at [vendor/magento/framework/Interception/Interceptor.php:58]
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by willwright**
### Description (*)

Adds a guard to `\Magento\Config\Model\Config\Source\Email\Template::toOptionArray` which protects against throwing an unhandled exception when a user has not called `$this->setPath()` before calling `toOptionArray()`

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29315

### Manual testing scenarios (*)

1. Create a custom module, plugin, or Observer
2. Inject a concrete instance of \Magento\Framework\ObjectManagerInterface ($this->_objectManager) through the constructor
3. Execute the following:
$sourceModelObj = $this->_objectManager->create('\Magento\Config\Model\Config\Source\Email\Template');
$optionsArray = $sourceModelObj->toOptionArray();
4. Notice unhandled exception is written to the screen

### Questions or comments

I included a Unit test in `app/code/Magento/Config/Test/Unit/Model/Config/Source/Email/TemplateTest.php` to illustrate the issue and test for it.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by willwright** [comment]
@magento run all tests

**Comment by rogyar** [comment]
Hi @willwright. Thank you for your collaboration. Please, take a look at the failing static tests. 
Thank you!

**Comment by willwright** [comment]
@magento run Static Tests

**Comment by willwright** [comment]
@magento run all tests

**Comment by willwright** [comment]
@rogyar Thanks for your comment.

I updated the branch and re-ran the tests.  Please let me know if you have any other questions.

**Comment by rogyar** [comment]
@magento run all tests

**Review by rogyar — APPROVED** [review]
The failing tests are not related to the current changeset

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7961](https://jira.corp.magento.com/browse/ENGCOM-7961) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@willwright thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Charlie** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario**:

1. Inject a concrete instance of \Magento\Framework\ObjectManagerInterface ($this->_objectManager) through the constructor
```
$sourceModelObj = $this->_objectManager->create('\Magento\Config\Model\Config\Source\Email\Template');
```
2. Execute the following:
```
$optionsArray = $sourceModelObj->toOptionArray();
```

**Before**: We see an exception message.
image

**After**: The exception wasn't thrown.

**Pull request merged**
