### PR TITLE
[Forwardport] Added 'title' attribute to 'img' tag in knockout template files.

### PR DESCRIPTION
**Pull request by sanganinamrata**
### Original Pull Request 
 https://github.com/magento/magento2/pull/16691

### Description

Added **title** attribute to **img** tag in **knockout template files**.

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios

N/A

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [X] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @sanganinamrata. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by ihor-sviziev** [comment]
Hi @sanganinamrata,
What is the benefit of adding title to the img tag? What the issue do you have?

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-2434](https://jira.corp.magento.com/browse/ENGCOM-2434) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @sanganinamrata. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Comment by YevSent** [comment]
@magento-engcom-team, these changes break Braintree PayPal integration on the checkout.
`{src: getPaymentAcceptanceMarkSrc(), alt: $t('Acceptance Mark')}, title: $t('Acceptance Mark')}` is incorrect and breaks knockout parsing, the `title` attribute should be inside `{}`.

**Comment by DanielRuf** [comment]
Exactly, it was forgotten to remove one `}`.

Shall I create another PR for all 3 branches?

**Comment by ihor-sviziev** [comment]
@DanielRuf sure, please create PRs for it.

**Comment by YevSent** [comment]
@bnugent, you don't need to provide the fix for 2.2-develop branch. I fixed it during fixing another bug.

**Comment by DanielRuf** [comment]
@joni-jones can you link the PR and create forward and backward PRs using the PR tool of the Magento engineering team?

**Comment by YevSent** [comment]
We will deliver the fix via in the internal PR, before merging to 2.2-develop the internal PRs can't be forward ported.

**Pull request merged**
