### PR TITLE
focus on empty payment field

### LINKED ISSUE #29550: [Issue] focus on empty payment field
### Preconditions (*)
1. Magento 2.4

### Steps to reproduce (*)
When you are going to the checkout and are filling in the shipping form and
then forget to fill out one of these inputs you will scroll to that input. 
Only when you are on the payment page and you want to change the address you will only get the red colored boxes but won't scroll to what is wrong. For mobile users this could be really annoying. Because they don't scroll to there invalid input and maybe think that the button is broken.

testing example:
image

Here you see the payment form. When I now want to update the form with an empty field it will scroll to those empty fields.

image
clicking on update (bewerken)

image
and scroll to te first invalid input

### Expected result (*)
It should navigate user to scroll to that input

### Actual result (*)
User not scroll to that input

### PR DESCRIPTION
**Pull request by kevinherwijnen**
When you are going to the checkout and are filling in the shipping form and then forget to fill out one of these inputs you will scroll to that input. Only when you are on the payment page and you want to change the address you will only get the red colored boxes but won't scroll to what is wrong. For mobile users this could be really annoying. Because they don't scroll to there invalid input and maybe think that the button is broken.

the changes I have made are in "app/code/Magento/Checkout/view/frontend/web/js/view/billing-address.js".
Here I edited line 166 and created an else statement just like already exist in shipping.js. In shipping .js you have the same functionality that is used in the shipping form.

testing example:
image

Here you see the payment form. When I now want to update the form with an empty field it will scroll to those empty fields.

image
clicking on update (bewerken)

image
and scroll to te first invalid input

### Resolved issues:
1. [x] resolves magento/magento2#29550: focus on empty payment field

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
Hi @kevinherwijnen,
Could you sign Adobe CLA?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @kevinherwijnen,
Your changes looks good to me.
Could you sign Adobe CLA and cover your changes with some kind of automated test?

**Comment by engcom-Charlie** [comment]
Hi @kevinherwijnen, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
