### PR TITLE
Fixed Issue #22924

### PR DESCRIPTION
**Pull request by imrandotftr**
### Description (*)
Store view label not in the middle of panel

### Fixed Issues (if relevant)

1. magento/magento2#22924: Store view label not in the middle of panel

### Manual testing scenarios (*)

1. Login to admin
2. Content -> Design -> Configuration -> Edit any theme
3. Check the vertical alignment of Scope.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22955) <br/>All committers have signed the CLA.

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @imrandotftr, please, sign CLA, otherwise, we can't process your pull request

**Comment by imrandotftr** [comment]
Hello @VladimirZaets ,

I have signed the CLA but still it's showing as not signed yet and in build section it's showing ok sign. I am confusing about it. Please check.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5142](https://jira.corp.magento.com/browse/ENGCOM-5142) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
Hi @imrandotftr thanks for the pull request! However, this issue was fixed earlier in [#22926](https://github.com/magento/magento2/pull/22926)

**Comment by VasylShvorak** [comment]
Closed as duplicate of [#22926](https://github.com/magento/magento2/pull/22926)

**Pull request closed without merging**
