### PR TITLE
Action Groups for Check exist/not exist Category in Category list on Product Edit page.

### LINKED ISSUE #28392: [Issue] Action Groups for Check exist/not exist Category in Category list on Product Edit page.
This issue is automatically created based on existing pull request: magento/magento2#28287: Action Groups for Check exist/not exist Category in Category list on Product Edit page.

---------

### Description (*)
Action Group for MFTF tests:

**AdminProductFormCategoryExistInCategoryListActionGroup**
Check if exist Category Name in Categories list on Product edit page.

**AdminProductFormCategoryNotExistInCategoryListActionGroup**
Check if exist Not Category Name in Categories list on Product edit page.

### Related Pull Requests

Action Groups for PullRequest with MFTF test:
https://github.com/magento/partners-magento2ee/pull/252 MFTF test AdminProductEditRestrictedWebsiteCategoriesTest.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by engcom-Kilo**
### Description (*)
Action Group for MFTF tests:

**AdminProductFormCategoryExistInCategoryListActionGroup**
Check if exist Category Name in Categories list on Product edit page.

**AdminProductFormCategoryNotExistInCategoryListActionGroup**
Check if exist Not Category Name in Categories list on Product edit page.

### Related Pull Requests

Action Groups for PullRequest with MFTF test:
https://github.com/magento/partners-magento2ee/pull/252 MFTF test AdminProductEditRestrictedWebsiteCategoriesTest.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28392: Action Groups for Check exist/not exist Category in Category list on Product Edit page.

### CODE REVIEW

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run all tests

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7591](https://jira.corp.magento.com/browse/ENGCOM-7591) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Charlie** [comment]
Failed functional tests not related to changes from this PR.

**Comment by slavvka** [comment]
@magento create issue

**Pull request merged**
