### PR TITLE
Fixed : Meta title issue on product page for Page title suffix

### LINKED ISSUE #37680: Page title suffix is included in "title" tag but not in "meta title" tag in product pages
### Preconditions and environment

- Magento version 2.4.6
- Anything else that would help a developer reproduce the bug
Setting Page title suffix in the theme configuration makes the system include the prefix in "title" tag but not in "meta title" tag for products. For standard pages and category pages it works correctly. Only in product pages is not included in meta title tag.

### Steps to reproduce

Go to Content > Design > Configuration > Global settings > HTML Head and add a Page Title Suffix.
Then check standard pages (eg. home page, about us, contact us etc) and category pages and you will see that is correctly included both in title and meta title tags.
Now go to a product page. You will see that is included in the title tag but not in meta title tag.

### Expected result

Page Title Suffix should be included also in meta title tag in product pages.

### Actual result

Page Title Suffix is not included in meta title tag in product pages.

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by aasim110**
Page title suffix is included in the "title" tag but not in the "meta title" tag on product pages

### Fixed Issues (if relevant)

1. Fixes magento/magento2#37680

### Manual testing scenarios (*)

1. Please follow the steps as provided here: https://github.com/magento/magento2/issues/37680#issuecomment-1629755931

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by aasim110** [comment]
@magento run all tests

**Comment by aasim110** [comment]
@magento run Static Tests

**Comment by aasim110** [comment]
@magento run all Tests

**Comment by aasim110** [comment]
@magento run Unit Tests

**Comment by aasim110** [comment]
https://github.com/magento run Unit Tests

**Comment by aasim110** [comment]
@magento run WebAPI Tests, Unit Tests, Integration Tests

**Comment by aasim110** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by aasim110** [comment]
@magento run Unit Tests, Functional Tests CE, Functional Tests EE

**Comment by aasim110** [comment]
@magento run Unit Tests, Functional Tests CE, Functional Tests EE

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @aasim110,

The code changes look good to me. But I think we can cover these changes with some automated tests like MFTF in accordance with the [definition of done](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1).

Thanks

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Integration Tests,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Integration Tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Integration Tests

**Comment by engcom-Echo** [comment]
Functional Tests B2B there are no test failures.
Functional Tests CE  and Functional Tests EE failure are different on last two run on same commit.
Functional Tests CE
Run1
Screenshot 2023-09-05 at 3 13 55 PM

Run2
Screenshot 2023-09-05 at 3 13 50 PM

Functional Tests EE
Run1
Screenshot 2023-09-05 at 3 13 42 PM

Run2
Screenshot 2023-09-05 at 3 13 38 PM


Moving it to `Pending Review` as all requested changes are covered.

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

1. Go to Content > Design > Configuration > Global settings > HTML Head and add a Page Title Suffix. Please add it as follows in order to make clear what is part of the suffix: **`| test_suffix`**
2. Then inspect the head of a product page that has nothing written in the **`"meta title"`** in Search engine optimization. You will see that the meta title will be exactly the same as the title of the page so it should include the suffix
3. Now edit this product and add the phrase **`"Custom meta title"`** in the **`"meta title"`** in Search engine optimization
4. Now inspect again the head of this product page and you will see that the meta title will show **`"Custom meta title"`** instead of **`"Custom meta title | test_suffix"`** , so the suffix is not added as it should.

**Before:** :heavy_multiplication_x: 
Screenshot 2023-09-05 at 6 10 41 PM


**After:** :heavy_check_mark:  
Screenshot 2023-09-06 at 11 26 26 AM
Screenshot 2023-09-06 at 11 29 51 AM

Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE,WebAPI Tests

**Comment by engcom-Echo** [comment]
Functional Tests CE failure are different on last two run on same commit.
Run1
Screenshot 2023-09-07 at 8 42 04 AM

Run2

Hence moving it to `merge in progress`
Screenshot 2023-09-07 at 8 42 04 AM

**Pull request merged**
