### PR TITLE
"Selected Attributes" lost selected value when filter (issue 23999)

### LINKED ISSUE #23999: "Selected Attributes" lost selected value when filter
### Preconditions (*)

1. Magento 2.3-develop
2. Created at least 2 dropdown attributes (color, size)

### Steps to reproduce (*)

Remember: **Created at least 2 dropdown attributes (color, size)**
1. Go to backend
2. Catalog -> Product -> Add Product
3. Fill require information
4. Click "Create Configurations"
5. In "Selected Attributes", select "color"
6. Go to filter, filter "size" in "Attribute Code"
7. Select "size"
8. View "**Selected Attributes**"

### Expected result (*)

1. Select "Color, Size"
image

### Actual result (*)

1. Select only "Size"
image

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#23999: "Selected Attributes" lost selected value when filter

Solution: Must add "preserveSelectionsOnFilter" is "true" in the xml

### Fixed Issues (if relevant)

1. magento/magento2#23999: "Selected Attributes" lost selected value when filter

### Manual testing scenarios (*)

Remember: **Created at least 2 dropdown attributes (color, size)**
1. Go to backend
2. Catalog -> Product -> Add Product
3. Fill require information
4. Click "Create Configurations"
5. In "Selected Attributes", select "color"
6. Go to filter, filter "size" in "Attribute Code"
7. Select "size"
8. View "**Selected Attributes**"

#### Expected result 
Select "Color, Size"
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
@sivaschenko 

Seems the "Fail" functional test doesn't related to my changes.

image

It create two values are the same => fail

So is it considered pass the automation test?

**Comment by sivaschenko** [comment]
@magento run Functional Tests build

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-5577](https://jira.corp.magento.com/browse/ENGCOM-5577) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by edenduong** [comment]
Hi @magento-engcom-team : Can I receive the "Bug fix award" for this Pull Request? Thanks :)

**Comment by edenduong** [comment]
@sidolov : Could I receive the "Bugfix award" for this PR? Thank you :)

**Pull request merged**
