### PR TITLE
Fixed order information in print order, invoice, credit memo and shipment is not proper aligned #24393

### PR DESCRIPTION
**Pull request by rani-priya**
Fixed order information in print order, invoice, credit memo and shipment is not proper aligned #24393

### Fixed Issues (if relevant)

1. magento/magento2#24393: order information in print order, invoice, credit memo and shipment is not proper aligned

### Manual testing scenarios (*)

1. Place an order
2. Go to customer account section and open that order
3. Click on print order link

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5783](https://jira.corp.magento.com/browse/ENGCOM-5783) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by rodrigowebjump — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-5783](https://jira.corp.magento.com/browse/ENGCOM-5783) has been created to process this Pull Request
:eight_spoked_asterisk: @rodrigowebjump, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
Hi @rani-webkul issue is still reproducible on invoice, shipment and refund pdf pages.
Invoice:
#24394PRInvoice

Shipment:
#24394PRShip

Refund:
#24394PRRefund


Could you take a look?

**Comment by rani-priya** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rani-webkul. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rani-webkul, here is your [new Magento instance](https://pr-24394.instances.magento-community.engineering).
Admin access: [https://pr-24394.instances.magento-community.engineering/admin](https://pr-24394.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rani-priya** [comment]
@engcom-Delta as I checked it's working fine on test (https://pr-24394.instances.magento-community.engineering/admin) instance.
customer: test@webkul.com password: Admin123
check order id 1

**Comment by rani-priya** [comment]
@engcom-Delta as I checked it's working fine on test. Please review again.

**Comment by engcom-Delta** [comment]
@rani-webkul On test instance same behavior as I described previously. Issue was fixed only for order page. If we click on Print Invoice, Print Shipment or Print Refund issue still exist

**Comment by rani-priya** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rani-webkul. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rani-webkul, here is your [new Magento instance](https://pr-24394.instances.magento-community.engineering).
Admin access: [https://pr-24394.instances.magento-community.engineering/admin](https://pr-24394.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rodrigowebjump — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-5783](https://jira.corp.magento.com/browse/ENGCOM-5783) has been created to process this Pull Request
:eight_spoked_asterisk: @rodrigowebjump, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by sivaschenko** [comment]
@magento run Functional Tests build

**Comment by rani-priya** [comment]
@ihor-sviziev could you please check that why this PR is not successfully passing the Functional Tests build ?

**Comment by ihor-sviziev** [comment]
> @ihor-sviziev could you please check that why this PR is not successfully passing the Functional Tests build ?

Hi @rani-webkul, according to results - it should pass, I think this is internal issue.

**Comment by rani-priya** [comment]
Hi @rodrigowebjump, could you please check why this PR is not passing though the extended testing?

**Comment by ihor-sviziev** [comment]
Hi @rani-webkul,
For now no action items required, probably @engcom-Foxtrot just need little bit more time than usual for checking if everything is fine

**Comment by engcom-Foxtrot** [comment]
Hello, @rani-webkul. This PR has a problem with AdminInlineTranslationOnCheckoutTest. You can see the report [here](https://testing-service.magento-community.engineering/reports/magento/magento2/pull/24394/0ed6e1b1be1e6b814ed521122737daf8/Functional/allure-report-ce/index.html#suites/8187718e2fd144987673ef34ee62b41b/4f4b53c6c14b1415/retries).

**Comment by rani-priya** [comment]
Hi @ihor-sviziev, This PR has a problem with AdminInlineTranslationOnCheckoutTest, could you please check what is the exact issue? I think this is not related to this PR.

**Comment by rani-priya** [comment]
Hi @sidolov,  This PR has a problem with AdminInlineTranslationOnCheckoutTest, could you please check what is the exact issue? I think this is not related to this PR.

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests build

**Comment by ihor-sviziev** [comment]
Hi @engcom-Foxtrot,
I just reviewed - looks like this test failure isn’t related to changes in this PR. Could you double check it?

**Comment by engcom-Foxtrot** [comment]
@rani-webkul @ihor-sviziev we are absolutely sure AdminInlineTranslationOnCheckoutTest failure is caused by this PR. We have restarted Functional Tests build multiple times, and this test is constantly failed, while it is passing on all other PRs.

**Pull request closed without merging**
