### PR TITLE
[MFTF] Refactoring CancelOrdersInOrderSalesReportTest

### LINKED ISSUE #31522: [Issue] [MFTF] Refactoring CancelOrdersInOrderSalesReportTest
This issue is automatically created based on existing pull request: magento/magento2#31458: [MFTF] Refactoring CancelOrdersInOrderSalesReportTest

---------
### Description (*)
The test is refactored to improve execution time

### Manual testing scenarios (*)
1. Place/invoice/ship an order
2. Place and cancel an order
3. Go to Reports->Sales->Orders
4. Generate reports for orders in all statuses except Canceled
5. Grab orders count
6. Generate reports for orders in any statuses
7. Grab orders count
8. Compare data

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
The test is refactored to improve execution time

### Manual testing scenarios (*)
1. Place/invoice/ship an order
2. Place and cancel an order
3. Go to Reports->Sales->Orders
4. Generate reports for orders in all statuses except Canceled
5. Grab orders count
6. Generate reports for orders in any statuses
7. Grab orders count
8. Compare data

### Resolved issues:
1. [x] resolves magento/magento2#31522: [MFTF] Refactoring CancelOrdersInOrderSalesReportTest

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by rogyar — APPROVED** [review]
The failing fluky tests are not related to the current changes

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8591](https://jira.corp.magento.com/browse/ENGCOM-8591) has been created to process this Pull Request

**Comment by sidolov** [comment]
@magento create issue

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** Functional Tests B2B, CE, EE are failed

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
