### PR TITLE
Fix Replace nestead query with separate queries in the entity filter processor

### LINKED ISSUE #1717: Replace nestead query with separate queries in the entity filter processor
Replace nestead query with separate queries in `\Magento\MediaGalleryUi\Model\SearchCriteria\CollectionProcessor\FilterProcessor\Entity::apply`

### PR DESCRIPTION
**Pull request by Nazar65**
…essor

### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration/issues/1717: Replace nestead query with separate queries in the entity filter processor 

### Manual testing scenarios (*)
- check the work of Used In filters
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-7974](https://jira.corp.magento.com/browse/ENGCOM-7974) has been created to process this Pull Request

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

Tested the work of Used In filters

Manual Testing Scenarios:
- https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/4930844 
- https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/4951850
- https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/4951848
- https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/4951846
- https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/4934276

**Pull request merged**
