### PR TITLE
Fiexed 22152 - Click on search icon it does not working on admin grid sticky header

### PR DESCRIPTION
**Pull request by niravkrish**
### Description (*)

Click on search icon it does not working on admin grid sticky header

### Fixed Issues (if relevant)

1. magento/magento2#22152: Click on search icon it does not working.

### Manual testing scenarios (*)

1. Manual Testing

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by orlangur — CHANGES_REQUESTED** [review]
LGTM.

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

**Comment by niravkrish** [comment]
> LGTM.
> 
> After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history

Hello @orlangur,

Can you please help me to remove unnecessary commits from this branch or PR?

Thanks
Nirav Patel

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4761](https://jira.corp.magento.com/browse/ENGCOM-4761) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
