### PR TITLE
#36346 Add regions for Czech Republic

### LINKED ISSUE #36346: Add Czechia regions
### Description (*)
Currently there are only few countries which have prefilled regions in Magento. This PR adds regions for Czech Republic

### Expected behavior (*)

ISO 3166 regions for Czech Republic would be added to `directory_country_region` table. There would be a possibility to select Czech regions from select on both frontend and backend.

### Benefits

This feature would allow to keep address hygiene and standardization for Czechia customers.

### PR DESCRIPTION
**Pull request by Tomasz-Silpion**
### Description (*)

Add regions for Czech Republic

### Resolved Issues

1. Resolves magento/magento2#36346

### Manual testing scenarios (*)

1. Install Magento
2. Check table directory_country_region for Czech regions.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [X] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Review by ishakhsuvarov — APPROVED** [review]
Functional test failures are unrelated to the Pull Request content.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
1. Have Magento latest version installed

**Manual testing scenario:**
1. Check table _directory_country_region_ for Czech regions
2. Go to DB > Select your database name.
3. Enter this query to verify- **_select * from directory_country_region where country_id like 'CZ';_**

**Before:** :heavy_multiplication_x: Regions for Czech Republic were not there
    image

**After:** :heavy_check_mark: We are getting Regions for Czech Republic now.
    image

**Additional Scenarios/ Info:**
1. Checked using GraphQL query as well and the response has all the valid data as shown in below screenshot
image

Since it is a update of some additional data into the database, we are no additional regression test case of part of testing!

**Comment by engcom-Alfa** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by engcom-Alfa** [comment]
@magento run WebAPI Tests

**Comment by engcom-Alfa** [comment]
@magento run WebAPI Tests

**Comment by engcom-Alfa** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests CE, Integration Tests

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests CE

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests CE

**Comment by engcom-Alfa** [comment]
As per the [above comment](https://github.com/magento/magento2/pull/36348#issuecomment-1315201063), QA already passed. Even after multiple tries, _Functional Test CE_ is getting failed every time.
Hence pushing the ticket for **_Extended Testing_**.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Pull request merged**
