### PR TITLE
Fixed tests for Magento\Framework\Stdlib\DateTime\DateTime

### PR DESCRIPTION
**Pull request by andrewbess**
### Description (*)

This PR fixes the tests for Magento\Framework\Stdlib\DateTime\DateTime. Daylight Saving Time was not considered there.
daylight-saving-time-is-not-effect
daylight-saving-time-is-in-effect

I have found it when changed my last PR. The first commit passed the tests well, but the second did not.
allure-report-error

### Related Pull Requests

https://github.com/magento/magento2/pull/27481 and the other futured after him

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by eduard13 — APPROVED** [review]
Thank you for the fix.

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-7224](https://jira.corp.magento.com/browse/ENGCOM-7224) has been created to process this Pull Request
:eight_spoked_asterisk: @eduard13, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @andrewbess,
Could you fix merge conflict?

**Comment by andrewbess** [comment]
> Hi @andrewbess,
> Could you fix merge conflict?

Hello @ihor-sviziev 
I have fixed the merge conflict.
Please check.
Thank you in advance

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-7224](https://jira.corp.magento.com/browse/ENGCOM-7224) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
