### PR TITLE
CSS load order incorrect using default_head_blocks.xml #1821

### PR DESCRIPTION
**Pull request by SerhiyDmytruk**
Added new attribute 'order' for set loading order .
Those attribute resolve issue about render files for some order.

### Fixed Issues (if relevant)
1. magento/magento2#1821: CSS load order incorrect using default_head_blocks.xml #1821

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14290) <br/>All committers have signed the CLA.

**Comment by larsroettig** [comment]
Hi @SergeyDmitruk, 
you PR have currently failed static test pls take look and fix this. 

Thank you best regards,
Lars

**Comment by magento-engcom-team** [comment]
Hi @SergeyDmitruk. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

**Comment by ihor-sviziev** [comment]
Hi @SergeyDmitruk,

I tried to create forwardport PR to 2.3-develop branch, but unfortunately it brakes swagger functionality, more details here: https://github.com/magento/magento2/pull/14815#issuecomment-386256743

Could you prepare forwardport PR with all needed changes to 2.3-develop branch, because it seems you know this context much better then me?

**Pull request merged**
