### PR TITLE
PHP 7.4 fix: use correct order of parameters for implode() in UnionExpression::__toString()

### LINKED ISSUE #28159: [Issue] PHP 7.4 fix: use correct order of parameters for implode() in UnionExpression::__toString()
This issue is automatically created based on existing pull request: magento/magento2#28131: PHP 7.4 fix: use correct order of parameters for implode() in UnionExpression::__toString()

---------
Fixes:
Deprecated Functionality: implode(): Passing glue string after array is deprecated. Swap the parameters in magento/vendor/magento/framework/DB/Sql/UnionExpression.php on line 55

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by marvinhinz**
Fixes:
Deprecated Functionality: implode(): Passing glue string after array is deprecated. Swap the parameters in magento/vendor/magento/framework/DB/Sql/UnionExpression.php on line 55

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28159: PHP 7.4 fix: use correct order of parameters for implode() in UnionExpression::__toString()

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @marvinhinz,
Your changes looks good. Could you cover your change with some test?

**Comment by marvinhinz** [comment]
Hi @ihor-sviziev,

Thanks for the quick reply! 
Do you mean a unit test? Im not really sure what should be tested, as this change cant break something, that was not already broken before. The functionality is exactly the same, it just doesn't trigger the deprecation warning anymore:

https://www.php.net/manual/en/function.implode.php

image

**Review by ihor-sviziev — APPROVED** [review]
Ah. I see. If it had the same result earlier - we don't need to have any unit test for it.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7524](https://jira.corp.magento.com/browse/ENGCOM-7524) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@marvinhinz thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by ihor-sviziev** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @marvinhinz, your fix already exists in the latest 2.4-develop. Please see https://github.com/magento/magento2/blob/9fa16c7e31e3e4f3b74ccd08ff2f7bc66dcc3c2e/lib/internal/Magento/Framework/DB/Sql/UnionExpression.php#L55
So I have to close your pr.

**Pull request closed without merging**
