### PR TITLE
fix create product with sku=0

### PR DESCRIPTION
**Pull request by dico1996**
### Description
Product with zero sku save and create on frontend and grid, but error on product page in admin panel.

### Manual testing scenarios
1. Go Catalog->Product->Add New Product
2. Create product with SKU=0
3. Save product.

Result: 
Product save and show on frontend and product grid in admin panel, but error on product page in admin panel.

True result: 
Product not created.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=12694) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=12694) before we can accept your contribution.<br/>

**Comment by orlangur** [comment]
> Product save and show on frontend and product grid in admin panel, but error on product page in admin panel.

Why forbid such product creation instead of fixing error in admin panel?

**Comment by orlangur** [comment]
Hello @dico1996, please sign CLA and check my earlier comment.

**Comment by orlangur** [comment]
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.

**Pull request closed without merging**
