### PR TITLE
Full Tax Summary display wrong numbers -Backport

### PR DESCRIPTION
**Pull request by hiren0241**
#20682
### Description (*)
The full tax summary is displaying total tax, instead of showing individual tax value.

### Fixed Issues (if relevant)

1. magento/magento2#19701: Magento 2.3 Shopping Cart Taxes Missing Calc Line
2. magento/magento2#11358: Full Tax Summary display wrong numbers.

### Manual testing scenarios (*)

1. Manual Testing

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @hiren0241. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4625](https://jira.corp.magento.com/browse/ENGCOM-4625) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
Hi @hiren0241 There are JS errors on the shopping cart page, can you please check it?

**Comment by hiren0241** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @hiren0241. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @hiren0241, here is your [new Magento instance](https://pr-21961.instances.magento-community.engineering).
Admin access: [https://pr-21961.instances.magento-community.engineering/admin](https://pr-21961.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by hiren0241** [comment]
@VasylShvorak Please recheck now. I have resolve the error. I have tested my code on test instance as well. Everything is good now. Please do have a look at below screenshot as well.
PR21961

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4625](https://jira.corp.magento.com/browse/ENGCOM-4625) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
