### PR TITLE
#22266 Allow GET method for products alerts

### PR DESCRIPTION
**Pull request by ilnytskyi**
### Description (*)
The classes
`\Magento\ProductAlert\Controller\Add\Stock`
`\Magento\ProductAlert\Controller\Add\Price`

Has been marked with `\Magento\Framework\App\Action\HttpPostActionInterface`
that caused 404 page issue after a redirect in `\Magento\Customer\Controller\Account\LoginPost`
### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/22266

### Manual testing scenarios (*)

1. Click subscribe for stock alert on product page
2. Log in
3. See product page and message about successful subscription for notification

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22284) <br/>All committers have signed the CLA.

**Review by orlangur — CHANGES_REQUESTED** [review]
@ilnytskyi GET must be implemented as separate action I believe.

Cc: @nmalevanec

**Comment by ilnytskyi** [comment]
@orlangur 
All actions in this module only receive requests to subscribe customer for notification, I am not sure what exactly has to be introduced in separate GET action. 
What was the reason to restrict this method to allow only POST ?
I belive the problem is here `Magento\Customer\Controller\Account\LoginPost::execute` that caused by setting up just a url to redirect here 
`\Magento\ProductAlert\Controller\Add::dispatch` btw then we could just mark this Add class with HttpPostActionInterface

**Comment by ilnytskyi** [comment]
Closed since similar changes were implemented in https://github.com/magento/magento2/pull/23218 by @ArjenMiedema 
and no answer was given in this topic

**Comment by korostii** [comment]
FYI as of 2.3.5 it still gives 404 - unless you either add both of those interfaces, ass suggested by this Pr (or, alternatively, remove them completely), IMO this should be reopened and merged in. Can this be picked up please @magento-engcom-team  ?

**Pull request closed without merging**
