### PR TITLE
[Backport][Downloadable] Bug fix for #21753

### PR DESCRIPTION
**Pull request by eduard13**
### Original Pull Request 
 https://github.com/magento/magento2/pull/22073

### Description (*)
Fixes the issue raised in #21753 by setting the initial downloadable item status to Available if \Magento\Downloadable\Model\Link\Purchased\Item::XML_PATH_ORDER_ITEM_STATUS is set to 'Pending.'

### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/21753

### Manual testing scenarios (*)
1. Login to the admin and set Stores -> Configuration -> Catalog -> Downloadable Product Options -> Order Item Status to Enable Downloads to "Pending"
2. Create a downloadable product in the admin
3. Create a user account on the frontend and login
4. Purchase a downloadable product. The product should be placed in the "available" state after successful completion of payment.
5. Login to the admin and set Stores -> Configuration -> Catalog -> Downloadable Product Options -> Order Item Status to Enable Downloads to "Invoiced"
6. Purchase the product again and note the second ordered item is in the "pending" status.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by eduard13** [comment]
Hi @orlangur, could you please clarify why you put it on Hold?
Thank you.

**Comment by orlangur** [comment]
@eduard13 just to wait if @crankycyclops wants to perform a backport by himself.

**Comment by crankycyclops** [comment]
> @eduard13 just to wait if @crankycyclops wants to perform a backport by himself.

I already opened a pull request for this at the same time as the one for 2.3. See: https://github.com/magento/magento2/pull/22072

**Comment by orlangur** [comment]
@crankycyclops wow, thanks for pointing out 👍

**Pull request closed without merging**
