### PR TITLE
[BAckport] Fix SKU limit in import new products

### PR DESCRIPTION
**Pull request by gelanivishal**
### Original PR
#18639 

### Description (*)

Fix SKU limit in import new product
### Fixed Issues (if relevant)

1. magento/magento2#17865: import new products via csv: products are created with empty value when strings are too long

### Manual testing scenarios (*)

1. prepare a correct csv to create new products via backend. Use short values (less then 71 characters) for name/sku for a few records, then use a longer strings ((more then 71 characters) for name/sku for other records.

2. go to system > import:
-- entity type = products
-- import behaviour = add/update, skip error entries
-- allow errors count = I tried with several numbers from 10 (default) to 500 but issue persists
-- field separator = ; (semicolon)
-- multiple value separator = , (comma, default)
-- field enclosure = unchecked (default)

3. Select the csv to import and run check data

4. when strings are too long, I expect to see an error after I run check data. I also expect that import get blocked until all error are fixed so no products gets created until the check data allows you to proceed with the import.
### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sidolov** [comment]
Hi @gelanivishal , changes in the original PR are different and should be adopted for current version

**Comment by gelanivishal** [comment]
@sidolov Please check now.

**Comment by sivaschenko** [comment]
@gelanivishal thanks for update, can you please fix the failing builds. According to the static tests report an empty line should be added to the end of app/code/Magento/CatalogImportExport/Model/Import/Product/Validator.php file. That should be done to comply with the [PSR2](https://www.php-fig.org/psr/psr-2/#22-files)

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3481](https://jira.corp.magento.com/browse/ENGCOM-3481) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @gelanivishal , thank you for your contribution, however, this pull request is a duplicate to https://github.com/magento/magento2/pull/18591 that is already merged, so I have to close it.

**Pull request closed without merging**
