### PR TITLE
Improve address save flow to allow to use custom validators

### PR DESCRIPTION
**Pull request by vovayatsyuk**
I'm facing an issue, that I cannot make some fields optional because of hardcoded
validation of address fields. Moreover, validation is made in private method, so I can't use plugin for it.

Hopefully, there is a [public validation method analogue](https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Model/Address/AbstractAddress.php#L561), available in address class, that can be extended with plugins.

### CODE REVIEW

**Comment by slavvka** [comment]
Hi @vovayatsyuk. Your contribution looks good but would you please also fix failed Travis Builds as well as cover changed functionality with tests?

**Comment by vovayatsyuk** [comment]
Just to clarify before fixing test with failed messages assertion.

How do you think, what is the best way to accomplish it?

 1. Change messages in asserting rules:

    ```
    firstname is a required field. => Please enter the first name.
    ```

 2. Change messages returned by public validate method:

    ```
    Please enter the first name. => firstname is a required field.
    ```

I'd like to change public validate method (option 2) in order to keep standard phrases for all fields. Additionally, `%fieldName is a required field` phrase is already used across Magento code.

**Comment by vovayatsyuk** [comment]
Hi @slavvka. I'm really stuck with following error:

```
Call to a member function getCountriesWithOptionalZip() on null in 
/home/travis/build/magento/magento2/app/code/Magento/Customer/Model/Address/AbstractAddress.php 
on line 584
```

The problem is `addressModel` is created inside [save method](https://github.com/vovayatsyuk/magento2/blob/801c121f0fb27fa09ad860d72c9c1ae0f180ec85/app/code/Magento/Customer/Model/ResourceModel/AddressRepository.php#L120) and we can't call it methods safely, because it does not have any required variables.

Sorry, but I don't have any experience with test writing, so if it could be fixed easily, can you guide me on how to :) ?

For now I'm really think that the save method should be rewritten to make it possible to write a test for it.

**Comment by aleksandrosadchiy** [comment]
Hi 
@vovayatsyuk. 

"2.Change messages returned by public validate method:
 Please enter the first name. => firstname is a required field."
In order, not to change the behavior of the system.

`Call to a member function getCountriesWithOptionalZip() on null in 
/home/travis/build/magento/magento2/app/code/Magento/Customer/Model/Address/AbstractAddress.php 
on line 584`
This error started to appear, due to the fact that you suggested to use 
`
        $errors = $addressModel->validate();
`
instead of private function _validate.
I adjusted the unit test. Your pull request has already been prepared and awaiting approval.
Number of internal ticket is MAGETWO-61725.

Thanks.

**Comment by vovayatsyuk** [comment]
Sorry, I've just screw up something :confused:. I will create another one PR for this issue.

**Comment by slavvka** [comment]
@vovayatsyuk, you didn't need to close it since it is already merged and fixed and will be delivered anyway. Please reopen it and don't create another PR.

**Pull request closed without merging**
