### PR TITLE
24025 add caching for magento product version

### PR DESCRIPTION
**Pull request by davidverholen**
fixes https://github.com/magento/magento2/issues/24025

### Description (*)

add caching for product version, to not utilize composer runtime on every request to the magento product version.

While this method is called rarely in the core, many 3rd party extensions rely on it to determine the magento version. This leads to many "real" projects having >100ms added to non cached requests

### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/24025

### Manual testing scenarios (*)

1. have a module installed that relies on the product version to determine e.g. feature compatibility
2. profile uncached requests

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by torhoehn — CHANGES_REQUESTED** [review]
@davidverholen Please fix failing tests. :)

**Comment by davidverholen** [comment]
@torhoehn do you have an idea why the database compare build fails? Results seem to be all green but still the check is failing

**Comment by torhoehn** [comment]
@davidverholen It's just a problem with the infrastructure. Seems okay for me. :)

**Review by torhoehn — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @torhoehn, thank you for the review.
[ENGCOM-5554](https://jira.corp.magento.com/browse/ENGCOM-5554) has been created to process this Pull Request
:eight_spoked_asterisk: @torhoehn, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by ihor-sviziev** [comment]
Test coverage was added in https://github.com/magento/magento2/pull/26001

**Pull request merged**
