### PR TITLE
32987 Don't load the captcha files on the storefront if it is disabled in the configurations

### LINKED ISSUE #32987: Disable captcha storefont config still load captcha js files
**Preconditions (*)**

- Magento Version - 2.4.2
- Default Magento Theme
- Captcha is disabled on Frontend 

**Steps to reproduce (*)**
- Do fresh Magento install - with or without demo Data
- Open developer tool, goto network tab
- Here you will see, unwanted js call for captcha  
image

**Expected result (*)**
- No Captcha related scripts should be called 

**My expected** 

- we don't need disable completely captcha module but if admin owner set config disable in backend both captcha blocks and js related may not visible in frontend

**Actual result (*)**
- 11 extra request of size 17.2 kB is getting called on page

### PR DESCRIPTION
**Pull request by khrystynastolbova**
### Description (*)

Don't load the captcha files on the storefront if it is disabled in the configurations

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32987

### Manual testing scenarios (*)

1. Enable captcha in the configs
Stores->Configuration->CUSTOMERS->Customer Configuration->CAPTCHA->Enable CAPTCHA on Storefront->**Yes**

**Home page**
Screenshot 2021-06-09 at 16 37 47

**Checkout page**
Screenshot 2021-06-09 at 16 53 57

2. Disable captcha in the configs
Stores->Configuration->CUSTOMERS->Customer Configuration->CAPTCHA->Enable CAPTCHA on Storefront->**No**

**Home page**
Screenshot 2021-06-09 at 13 51 52

**Checkout page**
Screenshot 2021-06-09 at 16 56 59

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
Can you resolve conflicts file xml

**Review by andrewbess — CHANGES_REQUESTED** [review]
Hello @khrystynastolbova 
Thank you for your contribution.
Could you please resolve the merge conflict?
Thank you in advance.

**Comment by mrtuvn** [comment]
Seem you need to do same solution for paypal captcha. This module maybe depend on captcha default with some extend behavior work for paypal flow

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by khrystynastolbova** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by mrtuvn** [comment]
Hi @khrystynastolbova Thanks for work on this ! Do you finish this development

**Comment by speedupmate** [comment]
great input 

but to solve this completely refer to https://github.com/magento/magento2/issues/15967 and note that some of those extensions define mixins that are not disabled until extensions are not disabled with` bin/magento module:disable `

```
vendor/magento/module-re-captcha-paypal/view/frontend/requirejs-config.js 
vendor/magento/module-re-captcha-webapi-ui/view/frontend/requirejs-config.js
vendor/magento/module-re-captcha-frontend-ui/view/frontend/requirejs-config.js
vendor/magento/module-re-captcha-checkout/view/frontend/requirejs-config.js
```

insted of defining mixins alternative is to get the mixed dependencies on uiComponent init from requirejs dependency injection or from uiregistry (async) and wrap whats needed , add the needed additional validators instead of place order mixins etc

**Comment by engcom-Alfa** [comment]
Hi @khrystynastolbova , @mrtuvn , @andrewbess and @speedupmate Thanks for your contribution and collaboration!

I have tried to reproduce the issue in `2.4-develop` version and the issue is still existing.
With the help of this PR changes, I have re-tested the issue has been fixed with the current changes as well.
But, based on the above comment, I can see that, we are still incomplete with the code updates.

Hi @khrystynastolbova 
1. Can you please confirm me that, current file changes are enough to take the ticket forward, or are you coming with the code changes as described in above comments.
2. We have this ticket _On Hold_, and checked in related other tickets including internal ticket, we have no reason for keeping it _on hold_. Looks like it is due to SVC failure. Can you please if there is any other reason?
3. I will wait for your reply, and in any case later, I will check with internal developers whether to consider or no, based on your reply.

Thanks in advance!

**Comment by ishakhsuvarov** [comment]
Closing this PR for now due to long inactivity.

Please feel free to reopen when ready

**Pull request closed without merging**
