### PR TITLE
[MFTF] Updating with AdminCheckFirstCheckboxInAddProductsToOptionPanelGridActionGroup

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
Tests have been updated with AdminCheckFirstCheckboxInAddProductsToOptionPanelGridActionGroup

https://github.com/magento/magento2/pull/33526

Please, note: the test is dependent on https://github.com/magento/magento2/pull/33526

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Semantic Version Checker, Functional Tests CE

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by AnnaAPak** [comment]
@magento run Semantic Version Checker

**Review by sidolov — CHANGES_REQUESTED** [review]
@AnnaAPak please, resolve merge conflicts

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
I have merged latest 2.4-develop into this PR branch.

The functional tests which are failing now, are not part of the PR changes or not failing because of any PR related change. Hence moving the PR in Merge in Progress.

Below tests are failing:
1. app/code/Magento/CurrencySymbol/Test/Mftf/Test/AdminCheckCurrencyConverterApiConfigurationTest.xml
2. app/code/Magento/InstantPurchase/Test/Mftf/Test/StorefrontInstantPurchaseFunctionalityTest.xml

Thank you!

**Pull request merged**
