### PR TITLE
[Backport]Fix issue 19472 - Advance Pricing - Customer Group Price , Select box and Text box alignment issue 

### PR DESCRIPTION
**Pull request by SyntaxKay**
### Original Pull Request
magento/magento2#19473

### Description (*)

Magento 2.2-develop branch
Advance Pricing - Customer Group Price , Select box and Text box alignment issue
### Fixed Issues (if relevant)

1. magento/magento2#19472:  Advance Pricing - Customer Group Price , Select box and Text box alignment issue 

### Manual testing scenarios (*)

1. N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by VladimirZaets** [comment]
Hi @speedy008. Thanks for collaboration. The PR will be processed after origin PR will be merged.

**Comment by sivaschenko** [comment]
Hi @speedy008 can you please remove the unnecessary merge commits from this pull request.

**Comment by SyntaxKay** [comment]
Hi @sivaschenko 
I have squash all commits to single commit

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3724](https://jira.corp.magento.com/browse/ENGCOM-3724) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @speedy008 , please take a look at the alignment in Advanced Pricing based on this PR:

image

**Comment by SyntaxKay** [comment]
@sivaschenko I am working on it

**Comment by sidolov** [comment]
Hi @speedy008 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
