### PR TITLE
Add --exclude-group to cron:run

### LINKED ISSUE #36628: [Issue] Add --exclude-group to cron:run
This issue is automatically created based on existing pull request: magento/magento2#34117: Add --exclude-group to cron:run

---------
### Description 

https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-cron.html#config-cli-cron-group-run

When you decide to split a single cron group with the `--group` flag it means you need to do so for every group in your instance.

It's pretty common for third party modules to define their own groups whenever they like, so we have to keep up to date with the defined groups in the instance to keep adding these to our crontab when new groups are added.

One of my instances currently has 11 groups to manage, more will come in the future and its just something I need to mentally keep an eye on, a bit annoying.

In my case I only really want to run the crons like

```
* * * * * bin/magento cron:run --exclude-group index
* * * * * flock -n index.lock bin/magento cron:run --group index
```

This will give me better granular control over the indexer crons which can be useful when your store reaches hundreds of thousands of SKUs. Any other random cron groups would then still be able to run by default like in normal operation.

For future proofing I've made the `--exclude-group` flag stackable so you can define it multiple times like
```
* * * * * bin/magento cron:run --exclude-group index --exclude-group consumers
```

### Manual testing scenarios (*)

1. Run cron with no params, all groups run
2. Run cron with --group, only that group runs
3. Run cron with --group and that group also in --exclude-group, no groups run
4. Run cron with --exclude-group, that group is excluded
5. Run cron with multiple --exclude-group, all defined groups are excluded

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by convenient**
### Description 

https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-cron.html#config-cli-cron-group-run

When you decide to split a single cron group with the `--group` flag it means you need to do so for every group in your instance.

It's pretty common for third party modules to define their own groups whenever they like, so we have to keep up to date with the defined groups in the instance to keep adding these to our crontab when new groups are added.

One of my instances currently has 11 groups to manage, more will come in the future and its just something I need to mentally keep an eye on, a bit annoying.

In my case I only really want to run the crons like

```
* * * * * bin/magento cron:run --exclude-group index
* * * * * flock -n index.lock bin/magento cron:run --group index
```

This will give me better granular control over the indexer crons which can be useful when your store reaches hundreds of thousands of SKUs. Any other random cron groups would then still be able to run by default like in normal operation.

For future proofing I've made the `--exclude-group` flag stackable so you can define it multiple times like
```
* * * * * bin/magento cron:run --exclude-group index --exclude-group consumers
```

### Manual testing scenarios (*)

1. Run cron with no params, all groups run
2. Run cron with --group, only that group runs
3. Run cron with --group and that group also in --exclude-group, no groups run
4. Run cron with --exclude-group, that group is excluded
5. Run cron with multiple --exclude-group, all defined groups are excluded

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36628: Add --exclude-group to cron:run

### CODE REVIEW

**Comment by convenient** [comment]
@magento run all tests

**Comment by convenient** [comment]
@magento run all tests

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
Not sure why the sniffer is complaining about the CronCommand.php file as those code elements have been there for sometime.

However the sniffer errors in the test file need to be fixed. If you search the code base for 'array_filter' you will see how the use of 'function' needs to be formatted.

Once the errors are fixed we can give it a proper review :)

**Comment by convenient** [comment]
@BarnyShergold Aye i spotted that as well. I think maybe `CronCommand.php` hasn't been touched in a while and the static analysis might only run on files changed?

Do you want me to address all static defects in `CronCommand.php`? 

I am on a few days annual leave now, will fix my dodgy `array_filter`s later in the week

**Comment by BarnyShergold** [comment]
> @BarnyShergold Aye i spotted that as well. I think maybe `CronCommand.php` hasn't been touched in a while and the static analysis might only run on files changed?
> 
> Do you want me to address all static defects in `CronCommand.php`?
> 
> I am on a few days annual leave now, will fix my dodgy `array_filter`s later in the week

if you can, that would be great - save any aggro :)

**Comment by convenient** [comment]
@magento run all tests

**Comment by convenient** [comment]
@BarnyShergold Two failures in [this test run](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/34117/12acf12370851f3ae146bd5f0be93dda/Statics/allure-report-b2b/index.html#suites/51d3ab4d5d77a0bc6a7ea344e9e7e6be/30912ad0ce8c7a73/) for the static analysis

```
PHP Code Sniffer detected 1 violation(s): 

FILE: /var/www/html/app/code/Magento/Cron/Console/Command/CronCommand.php
-------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
-------------------------------------------------------------------------
  67 | ERROR | If the @inheritdoc not inline it shouldn’t have braces
 102 | ERROR | {@inheritdoc} does not import parameter annotation
-------------------------------------------------------------------------
```

As per https://github.com/magento/magento-coding-standard/issues/154 I have no idea what to do with this issue. I've checked a bunch of different core console commands and they all look the same to me. Looking at https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#inheritdoc it says 
> The @inheritdoc tag SHOULD NOT be used.

So 🤷  not sure what I can do here. Please advise.


This one seems like a false alert to me, I didn't touch anything remotely near this area so not sure why its popping up.
```
PHP Copy/Paste Detector has found error(s):
<?xml version="1.0" encoding="UTF-8"?>
<pmd-cpd>
  <duplication lines="28" tokens="92">
    <file path="/var/www/html/app/code/Magento/Quote/Model/Quote/QuantityCollector.php" line="20"/>
    <file path="/var/www/html/app/code/Magento/Quote/Model/Quote/TotalsCollector.php" line="222"/>
    <codefragment>    public function collectItemsQtys(Quote $quote)
    {
        $quoteItems = $quote-&gt;getAllVisibleItems();
        $quote-&gt;setItemsCount(0);
        $quote-&gt;setItemsQty(0);
        $quote-&gt;setVirtualItemsQty(0);

        foreach ($quoteItems as $item) {
            if ($item-&gt;getParentItem()) {
                continue;
            }

            $children = $item-&gt;getChildren();
            if ($children &amp;&amp; $item-&gt;isShipSeparately()) {
                foreach ($children as $child) {
                    if ($child-&gt;getProduct()-&gt;getIsVirtual()) {
                        $quote-&gt;setVirtualItemsQty($quote-&gt;getVirtualItemsQty() + $child-&gt;getQty() * $item-&gt;getQty());
                    }
                }
            }

            if ($item-&gt;getProduct()-&gt;getIsVirtual()) {
                $quote-&gt;setVirtualItemsQty($quote-&gt;getVirtualItemsQty() + $item-&gt;getQty());
            }
            $quote-&gt;setItemsCount($quote-&gt;getItemsCount() + 1);
            $quote-&gt;setItemsQty((float)$quote-&gt;getItemsQty() + $item-&gt;getQty());
        }

</codefragment>
  </duplication>
</pmd-cpd>

Failed asserting that false is true.
```

**Comment by convenient** [comment]
@magento run all tests

**Comment by convenient** [comment]
@magento run Functional Tests CE

**Comment by BarnyShergold** [comment]
@magento run Static Tests

**Comment by convenient** [comment]
@BarnyShergold Yeah those two same failures again. what to do with the `inheritDoc` and that completely random unrelated failure 🤔

**Comment by hostep** [comment]
@convenient, about `inheritDoc`:

https://github.com/magento/magento-coding-standard/issues/113, brings me to https://github.com/magento/devdocs/pull/4425, which leads me to https://devdocs.magento.com/guides/v2.4/coding-standards/docblock-standard-general.html#inheritdoc

So I believe you should remove it 🙂

**Comment by convenient** [comment]
@BarnyShergold @hostep Focussing on this piece of the inheritdoc, the only way to make it green i can find is to manually define all the params etc and duplicate the parent doc. You need a PHPdoc and these are all I can think to do. 

What do you want me to do?

## Original Code

```php
    /**
     * Runs cron jobs if cron is not disabled in Magento configurations
     *
     * {@inheritdoc}
     */
    protected function execute(InputInterface $input, OutputInterface $output)
```

**Result** ⚠️ 

```
------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------------
 99 | ERROR | {@inheritdoc} does not import parameter annotation
------------------------------------------------------------------------------------------------------------------------------------------
```

## Attempt 1 - remove inheritdoc

```php
    /**
     * Runs cron jobs if cron is not disabled in Magento configurations
     */
    protected function execute(InputInterface $input, OutputInterface $output)
```

**Result** ⚠️ 

```
------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------------
 97 | ERROR | Missing @param for argument in method annotation
------------------------------------------------------------------------------------------------------------------------------------------
```

## Attempt 2 - define all params

```php
    /**
     * Runs cron jobs if cron is not disabled in Magento configurations
     *
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return int|void
     * @throws \Magento\Framework\Exception\FileSystemException
     * @throws \Magento\Framework\Exception\RuntimeException
     */
    protected function execute(InputInterface $input, OutputInterface $output)
```

**Result** ✅  no fails

**Comment by hostep** [comment]
Hmm, strange

Have you tried the following?

```
    /**
     * Runs cron jobs if cron is not disabled in Magento configurations
     *
     * @inheritdoc
     */
```

**Comment by convenient** [comment]
@hostep 

```php
    /**
     * Runs cron jobs if cron is not disabled in Magento configurations
     *
     * @inheritdoc
     */
    protected function execute(InputInterface $input, OutputInterface $output)
```

yields

```php
------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------------
 97 | ERROR | @inheritdoc imports only short description, annotation must have long description
------------------------------------------------------------------------------------------------------------------------------------------
```

I can also get it to pass by doing this so that it has both a short and a long description but it feels a bit garbage.

```php
    /**
     * Runs cron jobs
     *
     * Runs cron jobs if cron is not disabled in Magento configurations
     *
     * @inheritdoc
     */
    protected function execute(InputInterface $input, OutputInterface $output)
```

**Comment by Den4ik** [comment]
@convenient Thanks for PR. Please look at [DocBlock Standard](https://devdocs.magento.com/guides/v2.4/coding-standards/docblock-standard-general.html?itm_term=#inheritdoc) page. `@inheritdoc` should not be used

**Comment by convenient** [comment]
@Den4ik I think you may not have had a look at the previous discussions? This sniff fail is already preexisting and nothing to do with my code change, it's just I'm the first one to edit `CronCommand.php` since these sniffs went in and they only run on files changed.

Which of the valid two types of PHPDoc do you want me to work towards? The only ways I have managed to get the Magento2 coding standard to pass the docblock are detailed here https://github.com/magento/magento2/pull/34117#issuecomment-926432850 and https://github.com/magento/magento2/pull/34117#issuecomment-926451078 

Both of them have problems, one of them manually redefines all the parameters and one still has the inheritdoc but also needs a short description added. Can you please be explicit on what you expect me to do here?

**Comment by Den4ik** [comment]
@convenient Unfortunately Magento has files that fails on static tests and you will see failed result if change some of this files.

I prefer to use fully described doc block

```
    /**
     * Runs cron jobs if cron is not disabled in Magento configurations
     *
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return int|void
     * @throws \Magento\Framework\Exception\FileSystemException
     * @throws \Magento\Framework\Exception\RuntimeException
     */
    protected function execute(InputInterface $input, OutputInterface $output)
```

**Comment by convenient** [comment]
@magento run all tests

**Comment by convenient** [comment]
@magento run all tests

**Comment by convenient** [comment]
@magento run WebAPI Tests

**Comment by convenient** [comment]
@magento run Integration Tests

**Comment by convenient** [comment]
@BarnyShergold @Den4ik build has gone green after a few reruns 👍

**Review by Den4ik — APPROVED** [review]
✅ Look ok for me

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9233](https://jira.corp.magento.com/browse/ENGCOM-9233) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by convenient** [comment]
Accidentally clicked  "update branch" while browsing on my phone 🤦‍♂️

**Comment by convenient** [comment]
@magento run all tests

**Comment by convenient** [comment]
@magento run Functional Tests EE

**Review by BarnyShergold — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @BarnyShergold, thank you for the review.
[ENGCOM-9233](https://jira.corp.magento.com/browse/ENGCOM-9233) has been created to process this Pull Request

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento `2.4-develop`

**Manual testing scenario:**

1. Run cron with no params, all groups run
2. Run cron with --group, only that group runs
3. Run cron with --group and that group also in --exclude-group, no groups run
4. Run cron with --exclude-group, that group is excluded
5. Run cron with multiple --exclude-group, all defined groups are excluded

**Before:** :heavy_multiplication_x: Not able to run cron using "--exclude-group"
Screenshot 2022-12-15 at 3 51 43 PM

Screenshot 2022-12-15 at 3 50 38 PM


**After:** :heavy_check_mark:  Now its happening.
==========================================================================================
image
==========================================================================================
image
==========================================================================================

**Additionally tested:**
After running the cron executed below scenarios:
1. Created customer.
2. Placed order from the customer.
3. Placed order from the guest.
4. In admin side -Created new product.
5. Created invoice, creditmemo, reordered.

Since, branch having conflict. Hence, moving this PR to extended testing.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

**Comment by abhattGlo** [comment]
@magento run Integration Tests,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run all tests

**Pull request merged**
