### PR TITLE
fix Custom Admin Domain and Internal Redirects

### LINKED ISSUE #28943: Custom Admin Domain and Internal Redirects
The logic that checks if a redirect is "internal" is broken in the admin panel when using a custom admin domain, which causes a wide variety of admin redirects to redirect you to the homepage of the default store.

The issue is due to `Magento\Store\App\Response\Redirect::_isUrlInternal` using the default stores base url. When in the adminhtml area, this method should respect the config options `admin/url/use_custom` and `admin/url/custom`.

### Preconditions (*)
1. Magento 2.4-develop
2. Custom admin domain set under Stores > Configuration > Advanced > Admin > Admin Base Url > Custom Admin Url
image
3. **For local environment:** Create additional virtualhost for url `http://admin.magento2dev.loc` and add `admin.magento2dev.loc` to `hosts` file
```
<VirtualHost *:80>
    ServerName          magento2dev.loc
    ServerAlias magento2dev.loc
    DocumentRoot        /var/www/html/magento2dev
<Directory /var/www/html/magento2dev/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
Require all granted
</Directory>
 </VirtualHost>


<VirtualHost *:80>
    ServerName          admin.magento2dev.loc
    DocumentRoot        /var/www/html/magento2dev
<Directory /var/www/html/magento2dev/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
Require all granted
</Directory>
 </VirtualHost>
```

### Steps to reproduce (*)
1. Log in to an account with access to URL Rewrites
2. Navigate to Marketing > URL Rewrites
3. Click Add Url Rewrite
4. Enter `123456789` as the request path and `987654321` as the target path, then hit save.
5. Click Add Url Rewrite again
4. Enter `123456789` as the request path and `xyz` as the target path, then hit save.

### Expected result (*)
1. Expected to be redirected back to the URL Rewrite Edit page with an error message `Request Path for Specified Store already exists.`

### Actual result (*)
1. You're redirected to the homepage of the default store.
Peek 2020-07-07 13-21

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by engcom-Charlie**
### Description (*)

Fixed and covered by test

### Fixed Issues (if relevant)

1. Fixes magento/magento2#28943

### Manual testing scenarios (*)

1. see #28943

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]
Good job! Approved! ✔

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7820](https://jira.corp.magento.com/browse/ENGCOM-7820) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Custom admin domain set under Stores > Configuration > Advanced > Admin > Admin Base Url > Custom Admin Url

Screenshot from 2020-07-17 14-34-23

2. **For local environment:** Create additional virtualhost for url `http://admin.magento24.loc` and add `admin.magento24.loc` to `hosts` file
```
<VirtualHost *:80>
    ServerName          magento24.loc
    ServerAlias magento24.loc
    DocumentRoot        /var/www/html/magento24
<Directory /var/www/html/magento2dev/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
Require all granted
</Directory>
 </VirtualHost>


<VirtualHost *:80>
    ServerName          admin.magento24.loc
    DocumentRoot        /var/www/html/magento24
<Directory /var/www/html/magento24/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
Require all granted
</Directory>
 </VirtualHost>
```

### Steps to reproduce (*)
1. Log in to an account with access to URL Rewrites
2. Navigate to Marketing > URL Rewrites
3. Click Add Url Rewrite
4. Enter `123456789` as the request path and `987654321` as the target path, then hit save.
5. Click Add Url Rewrite again
4. Enter `123456789` as the request path and `xzc` as the target path, then hit save.

**Before:** :heavy_multiplication_x: You're redirected to the homepage of the default store.

Peek 2020-07-17 13-05

**After:** :heavy_check_mark: Was redirected back to the URL Rewrite Edit page with an error message `Request Path for Specified Store already exists.`

Peek 2020-07-17 13-58

**Pull request merged**
