### PR TITLE
 #25199 Remove quotes when not necessary

### LINKED ISSUE #25199: Catalog Category Indexing takes very long on MariaDB 10.3 with many products
### Description (*)

I know MariaDB 10.3 is not yet supported, as per dev docs, so I add this as feature requests, while it will manifest as a bug as soon as we support MariaDB 10.3

Magento should remove the quotes in the SELECT entity_id IN statement when creating indexes. The entity_ids are not strings, and this seems to confuse the optimizer.

### Steps to reproduce:

1. Change value for simple products to 50000 for example (setup/performance-toolkit/profiles/ce/small.xml);
2. Run in console: bin/magento setup:perf:generate-fixtures /var/www/html/magento24/setup/performance-toolkit/profiles/ce/small.xml for example

### Expected behavior (*)

Catalog Category Indexing should run quickly, on MariaDB 10.1 and on 10.3.18

### Benefits
Shop ownes can use MariaDB 10.3.18

### Additional information

See this answer on StackExchange: https://magento.stackexchange.com/a/293345/81

I took the full query which is run several times (for each store view) on the catalog category products indexer and extracted the select part

	SELECT 2 AS `category_id`, `cp`.`entity_id` AS `product_id`, IF(ccp.product_id IS NOT NULL, ccp.position, 0) AS `position`, IF(ccp.product_id IS NOT NULL, 1, 0) AS `is_parent`, 2 AS `store_id`, IFNULL(cpvs.value, cpvd.value) AS `visibility` FROM `catalog_product_entity` AS `cp`
	 INNER JOIN `catalog_product_website` AS `cpw` ON cpw.product_id = cp.entity_id
	 INNER JOIN `catalog_product_entity_int` AS `cpsd` ON cpsd.entity_id = cp.entity_id AND cpsd.store_id = 0 AND cpsd.attribute_id = 97
	 LEFT JOIN `catalog_product_entity_int` AS `cpss` ON cpss.entity_id = cp.entity_id AND cpss.attribute_id = cpsd.attribute_id AND cpss.store_id = 2
	 INNER JOIN `catalog_product_entity_int` AS `cpvd` ON cpvd.entity_id = cp.entity_id AND cpvd.store_id = 0 AND cpvd.attribute_id = 99
	 LEFT JOIN `catalog_product_entity_int` AS `cpvs` ON cpvs.entity_id = cp.entity_id AND cpvs.attribute_id = cpvd.attribute_id  AND cpvs.store_id = 2
	 LEFT JOIN `catalog_category_product` AS `ccp` ON ccp.product_id = cp.entity_id WHERE (cpw.website_id = '1') AND (IFNULL(cpss.value, cpsd.value) = 1) AND           (IFNULL(cpvs.value, cpvd.value) IN (2, 3, 4)) AND (cp.entity_id IN ('107280', '107281', '107282', '107283', '107284'
	    [... around 70 K entity IDs ...]
	    187965', '187966')) GROUP BY `cp`.`entity_id`;

This query alone runs 8 minutes on Maria DB 10.3

When I simply remove all the quotes via s/'//g in vi in the line with the "IN" statement I get

	SELECT 2 AS `category_id`, `cp`.`entity_id` AS `product_id`, IF(ccp.product_id IS NOT NULL, ccp.position, 0) AS `position`, IF(ccp.product_id IS NOT NULL, 1, 0) AS `is_parent`, 2 AS `store_id`, IFNULL(cpvs.value, cpvd.value) AS `visibility` FROM `catalog_product_entity` AS `cp`
	 INNER JOIN `catalog_product_website` AS `cpw` ON cpw.product_id = cp.entity_id
	 INNER JOIN `catalog_product_entity_int` AS `cpsd` ON cpsd.entity_id = cp.entity_id AND cpsd.store_id = 0 AND cpsd.attribute_id = 97
	 LEFT JOIN `catalog_product_entity_int` AS `cpss` ON cpss.entity_id = cp.entity_id AND cpss.attribute_id = cpsd.attribute_id AND cpss.store_id = 2
	 INNER JOIN `catalog_product_entity_int` AS `cpvd` ON cpvd.entity_id = cp.entity_id AND cpvd.store_id = 0 AND cpvd.attribute_id = 99
	 LEFT JOIN `catalog_product_entity_int` AS `cpvs` ON cpvs.entity_id = cp.entity_id AND cpvs.attribute_id = cpvd.attribute_id  AND cpvs.store_id = 2
	 LEFT JOIN `catalog_category_product` AS `ccp` ON ccp.product_id = cp.entity_id WHERE (cpw.website_id = '1') AND (IFNULL(cpss.value, cpsd.value) = 1) AND           (IFNULL(cpvs.value, cpvd.value) IN (2, 3, 4)) AND (cp.entity_id IN (107280, 107281, 107282, 107283, 107284
	    [... around 70 K entity IDs ...]
	    187965, 187966)) GROUP BY `cp`.`entity_id`;

### Next steps

I will try to provide a patch.

### PR DESCRIPTION
**Pull request by amenk**
see Ticket #25199

### CODE REVIEW

**Comment by amenk** [comment]
Actually the approach to threat all possible integers in all columns might cause problems for varchars.

Because of this behavior in MySQL: http://sqlfiddle.com/#!9/1c01c9/1/0

While my patch is fine for entity_id fields, now if Magento tries to match an SKU like (string) '1', my patch would convert this to a (int) 1 and match also SKUs like '1-2', '1-3' and so on.

**Comment by amenk** [comment]
Alternative patch:

vendor/magento/module-catalog/Model/Indexer/Category/Product/Action/Full.php:285


        foreach ($batchQueries as $query) {
            $this->connection->delete($this->tableMaintainer->getMainTmpTable((int)$store->getId()));
            $entityIds = $this->connection->fetchCol($query);
            foreach($entityIds as &$val) {  ##patch
                $val = (integer) $val; ## patch
            } ##patch
            $resultSelect = clone $basicSelect;
            $resultSelect->where($whereCondition, $entityIds);
            $this->connect

**Comment by mropanen** [comment]
Also strings like '23523523e2353253562356' are is_numeric == true ;)
I ended up doing this as a quick fix:
**if (is_numeric($val) && $val < INF) {**

**Comment by amenk** [comment]
@mropanen you have to be careful to not threat numeric SKUs as int. This can have the side effects I described.

**Comment by robert-scheck** [comment]
While the patch indeed solves the issue with "Category Products index", it doesn't address the (same?) issue at "Product Price index". Just ending up here with:

```
SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction, query was: DELETE FROM `catalog_product_index_website`
```

Aside of that, it feels like the patch makes the indexer slower (factor ~ 1.5) in general.

**Comment by ihor-sviziev** [comment]
Hi @amenk ,
I see that we have two solutions for fixing this issue. Just reviewed both of them and I see that following solution is better https://github.com/magento/magento2/pull/27129/files#diff-ffe9c9bcf0327071a617f8ba7bbfde56R285 as it's fixes root of the issue and not affecting almost all queries in the magento and custom extensions. 

As we have better solution - I'm closing this PR.
Thank you so much for contribution!

**Pull request closed without merging**
