### PR TITLE
Remove unused and invalid method

### PR DESCRIPTION
**Pull request by adragus-inviqa**
a) there is no `$this->_getDomConfigModel()` method
b) method is unused

### CODE REVIEW

**Comment by sivajik34** [comment]
@adragus-inviqa  may be we can add deprecated, without deleting the method.

**Comment by adragus-inviqa** [comment]
Yeah, I suppose we could, but I looked for its usage, and couldn't find one. If you deprecate it, it's still callable. But calling it would give you a fatal error, as there's no `$this->_getDomConfigModel()` method.

I'd rather we get rid of it.

**Comment by vrann** [comment]
@adragus-inviqa per our backward compatibility policy method should deprecate method first and then it will be removed in the next release. Please deprecate it.

**Comment by adragus-inviqa** [comment]
Ok, I will. But what about the fact that people can still call it, and trigger a fatal error? Shouldn't I remove the method body at least?

PS: Do you actually remove deprecated stuff in the subsequent release? 🤔

**Comment by vrann** [comment]
@adragus-inviqa ah, good point. If there is fatal exception from using it, then better to remove.

**Comment by magento-team** [comment]
@adragus-inviqa thank you for your contribution. Your Pull Request has been successfully merged

**Pull request merged**
