### PR TITLE
[Component Rule] Revert es6 variable declarations

### PR DESCRIPTION
**Pull request by Den4ik**
### Description (*)

> Currently, we support IE 11 browser that not good supports ES6 features.
> 
> We can't add es6 to eslint cause it's will mean that we fully support ES6 but currently, it isn't.
> Let and const declaration are already supported by IE11, but again, we should use all features of ES6 or don't use anything.

This PR revert es6 variable declaration via let/const

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4597](https://jira.corp.magento.com/browse/ENGCOM-4597) has been created to process this Pull Request

**Comment by orlangur** [comment]
Is IE11 support going to be dropped any soon?

**Comment by VasylShvorak** [comment]
✔️ QA passed

**Pull request merged**
