### PR TITLE
magento/magento2#: Fix storeId param type in the EmailNotification::newAccount, EmailNotificationInterface::newAccount methods

### PR DESCRIPTION
**Pull request by atwixfirster**
### Description (*)

Pull request fixes `$storeId` param type in the annotations of:
- Magento\Customer\Model\EmailNotificationInterface::newAccount()
- Magento\Customer\Model\EmailNotification::newAccount()

Previous declaration:
```
    /**
     * Send email with new account related information
     *
     * @param CustomerInterface $customer
     * @param string $type
     * @param string $backUrl
     * @param string $storeId
     * @param string $sendemailStoreId
     * @return void
     * @throws LocalizedException
     * @since 100.1.0
     */
    public function newAccount(
        CustomerInterface $customer,
        $type = self::NEW_ACCOUNT_EMAIL_REGISTERED,
        $backUrl = '',
        $storeId = 0,
        $sendemailStoreId = null
    );
```

Declaration after changes:
```
    /**
     * Send email with new account related information
     *
     * @param CustomerInterface $customer
     * @param string $type
     * @param string $backUrl
     * @param int $storeId
     * @param string $sendemailStoreId
     * @return void
     * @throws LocalizedException
     * @since 100.1.0
     */
    public function newAccount(
        CustomerInterface $customer,
        $type = self::NEW_ACCOUNT_EMAIL_REGISTERED,
        $backUrl = '',
        $storeId = 0,
        $sendemailStoreId = null
    );
```

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by fooman** [comment]
@atwixfirster I have just had a similar pull request merged - see here https://github.com/magento/magento2/pull/23351/files#diff-dc7f5c643169e7d452a451e9b2819d70R53. I believe all storeIds - at least how they are currently used are either null, int or a string when it gets back down to config level. Would it make sense to use 
`null|int|string` here as well?

**Comment by atwixfirster** [comment]
Hi, @fooman !

> Would it make sense to use
> `null|int|string` here as well?

No, because default value of `$storeId` set to `0` in the `Magento\Customer\Model\EmailNotificationInterface`::`newAccount()`:

```
    public function newAccount(
        CustomerInterface $customer,
        $type = self::NEW_ACCOUNT_EMAIL_REGISTERED,
        $backUrl = '',
        $storeId = 0,
        $sendemailStoreId = null
    );
```

So, it can not be `null` or `string`.

Thank you!

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5447](https://jira.corp.magento.com/browse/ENGCOM-5447) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5447](https://jira.corp.magento.com/browse/ENGCOM-5447) has been created to process this Pull Request

**Pull request merged**
