### PR TITLE
Can't able to delete/rename sitemap.xml in file system

### LINKED ISSUE #37468: [Issue] Can't able to delete/rename sitemap.xml in file system
This issue is automatically created based on existing pull request: magento/magento2#36323: Can't able to delete/rename sitemap.xml in file system

---------

### Description (*)
When we try to delete the generated sitemap, it is deleted from the admin side but not deleted from the file system. So, I have checked, and there is a Delete controller for deleting the sitemap from the admin side. Here is the file - 
> _**/vendor/magento/module-sitemap/Controller/Adminhtml/Sitemap/Delete.php**_

in the **execute()** function, the **`$directory`** is using the ROOT (base) directory instead of the PUB directory at line 54. So, it is checking the file in the root instead of the pub directory at line 72 as in the below image.

delete-controller-execute-method

The sitemap file is generated under the pub directory. So, it can't able to delete the sitemap file from the pub directory after deleting it from the admin side.

Also, if we rename the sitemap file and Save and Generate it. Then it will generate a new file and it will keep the old one also in the file system. There is a Save controller for saving the sitemap and here is the file -
> _**/vendor/magento/module-sitemap/Controller/Adminhtml/Sitemap/Save.php**_

in the **clearSiteMap()** function, doing the same thing as in the Delete controller like the **`$directory`** is using the ROOT (base) directory instead of the PUB directory at line 131. And that's why when the sitemap is renamed, it can't delete from the file system as in the below image.

save-controller-clearSiteMap-method

So, We need to use the PUB directory at both places.

### Related Pull Requests
None

### Fixed Issues (if relevant)
None

### Manual testing scenarios (*)

1. Go to Marketing -> Sitemap and create a sitemap.
2. Add a Sitemap by clicking on the 'Add Sitemap' button. And fill up the field like the attached image and save the sitemap.

New-Site-Map-Site-Admin

3. Now generate a sitemap from the grid by clicking on the generate link.
4. Sitemap is generated in the pub directory. Now open that sitemap on the admin side and delete it.
5. Check in the pub directory. The sitemap is still there.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by Dhaval410**
### Description (*)
When we try to delete the generated sitemap, it is deleted from the admin side but not deleted from the file system. So, I have checked, and there is a Delete controller for deleting the sitemap from the admin side. Here is the file - 
> _**/vendor/magento/module-sitemap/Controller/Adminhtml/Sitemap/Delete.php**_

in the **execute()** function, the **`$directory`** is using the ROOT (base) directory instead of the PUB directory at line 54. So, it is checking the file in the root instead of the pub directory at line 72 as in the below image.

delete-controller-execute-method

The sitemap file is generated under the pub directory. So, it can't able to delete the sitemap file from the pub directory after deleting it from the admin side.

Also, if we rename the sitemap file and Save and Generate it. Then it will generate a new file and it will keep the old one also in the file system. There is a Save controller for saving the sitemap and here is the file -
> _**/vendor/magento/module-sitemap/Controller/Adminhtml/Sitemap/Save.php**_

in the **clearSiteMap()** function, doing the same thing as in the Delete controller like the **`$directory`** is using the ROOT (base) directory instead of the PUB directory at line 131. And that's why when the sitemap is renamed, it can't delete from the file system as in the below image.

save-controller-clearSiteMap-method

So, We need to use the PUB directory at both places.

### Related Pull Requests
None

### Fixed Issues (if relevant)
None

### Manual testing scenarios (*)

1. Go to Marketing -> Sitemap and create a sitemap.
2. Add a Sitemap by clicking on the 'Add Sitemap' button. And fill up the field like the attached image and save the sitemap.

New-Site-Map-Site-Admin

3. Now generate a sitemap from the grid by clicking on the generate link.
4. Sitemap is generated in the pub directory. Now open that sitemap on the admin side and delete it.
5. Check in the pub directory. The sitemap is still there.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37468: Can't able to delete/rename sitemap.xml in file system

### CODE REVIEW

**Comment by Dhaval410** [comment]
@magento run all tests

**Comment by Dhaval410** [comment]
@magento run all tests

**Comment by Dhaval410** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @Dhaval410,

Changes looks good to me, please cover the changes with some automated test coverage.

Thanks

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@engcom-Hotel Automated test coverage is added. Requesting you to review.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B,Integration Tests

**Review by engcom-Hotel — APPROVED** [review]
Hello @Dhaval410,

Thanks for the contribution!

The failed test doesn’t seem to be related to this PR changes, hence approving this PR for further process.

Thanks

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

1. Go to Marketing -> Sitemap and create a sitemap.
2. Add a Sitemap by clicking on the 'Add Sitemap' button.
3. Now generate a sitemap from the grid by clicking on the generate link.
4. Sitemap is generated in the pub directory. Now open that sitemap on the admin side and delete it.
5. Check in the pub directory. The sitemap is still there.

**Before:** :heavy_multiplication_x: 
https://shared-assets.adobe.com/link/0d7d61e1-a52f-48cd-5c93-f0ffc9d99496

**After:** :heavy_check_mark:  
https://shared-assets.adobe.com/link/ad508a88-85fd-41df-60f8-f9ed485d768e

No additional manual test case is required as a part of regression as there is minor changes in this PR.

Builds are failed. Hence, moving this PR to **Extended Testing**

**Comment by engcom-Echo** [comment]
Functional Tests EE failures are different on last two run on same commit.
Run1
image


Run2
image

Hence moving to `Merge In Progress`

**Pull request merged**
