### PR TITLE
Allows configuring the setting 'Add Store Code to Urls' in website scope

### PR DESCRIPTION
**Pull request by hostep**
### Description (*)
We sometimes have to setup a url structure like this when working with multiple websites:

| Website       | Storeview    | Url          |
| ------------ | ---------- | ----------- |
| Example 1     | English      | https://www.example1.co.uk/    |
| Example 2     | French       | https://www.example2.be/fr/ |
| Example 2     | Dutch        | https://www.example2.be/nl/ |

Currently this isn't easily possible in Magento, because the configuration flag to add storeview codes to the url is global.

This PR changes this and makes it configurable in website scope, so we can choose to add storeview codes to the url for one website but not for another one.

We have this configuration setup on 2 Magento instances in development and it looks like this works perfectly fine, we haven't seen strange bugs with this so far.

### Related Pull Requests
None

### Fixed Issues (if relevant)
1. None that I could find

### Manual testing scenarios (*)
1. Create at least 2 websites, each having at least 1 storeview
2. Give the 2 websites a different base url (different domain name)
3. Enable the setting General > Web > Url Options > Add Store Code to Urls for one website but not for the other
4. On the frontend, verify that the url's for both websites are as expected: one website should not have a storeview code in the url and the other one should have one.

### Questions or comments
I haven't tested how this behaves if the websites have the exact same base url. That might give troubles, so we'd best test this and if it gives issues, we might need to add a warning to the setting explaining that you need to use different base url's if you want to use this setting in website scope.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hostep** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
That’s definitely what I wanted long time ago!
Will you be able to cover your changes with mftf test?

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE

**Comment by hostep** [comment]
@ihor-sviziev: exactly!

I have this idea to expand the functionality further, but it will require a lot more work.

We also sometimes have the need for these url structures to be assigned to two different storeviews:
- https://www.example1.com/nl/
- https://www.example2.com/nl/

Currently this also isn't possible, because the storeview codes need to be unique, so we would need yet another configuration option to add some sort of suffix to the base url which is configurable on storeview level. Changing the base url itself with this suffix didn't seem to work well when I tried this some months ago.
But that's for another day ...

Regarding the MFTF tests, I don't have time and very little experience with it, so if somebody from the engcom team could pick this up, that would be very much appreciated!

**Comment by ihor-sviziev** [comment]
@hostep would like to see that feature also!
Btw... what will be in case if I'll go to direct domain, without /nl/? It will redirect to default store view on the website?

**Review by ihor-sviziev — DISMISSED** [review]

**Comment by ihor-sviziev** [comment]
Just approved, hope someone on testing phase could help with covering with mftf test

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8369](https://jira.corp.magento.com/browse/ENGCOM-8369) has been created to process this Pull Request

**Comment by hostep** [comment]
@ihor-sviziev:
> Btw... what will be in case if I'll go to direct domain, without /nl/? Will it redirect to default store view on the website?

I suspect it will, but needs to be tested. In the shops where we are tying this out we can't test this due to us having a structure like this:
- https://www.website1.com/nl/
- https://www.website2-with-its-own-domain-name.com/
- https://www.website2-with-its-own-other-domain-name.com/

But that works at least :)

**Comment by ihor-sviziev** [comment]
@engcom-Bravo please check additionally cases when on global scope (all store views) this option is DISABLED, but for specific website it's ENABLED. I believe in some cases URL from the admin or from the cron to the frontend might be incorrect. Please check it additionally.

**Review by engcom-Bravo — CHANGES_REQUESTED** [review]
:x: QA failed

Works as expected when the **Add Store Code to Urls** is Set to:
**Yes** for _Default config_
**Yes** for _Site1_
**No** for _Site2_
In this case, the store code is shown for _Site1_ and not shown for _Site2_

But when the following values are set:
**No** for _Default config_
**Yes** for _Site1_
**No** for _Site2_
The store code for _Site1_ is NOT shown, despite that the **Add Store Code to Urls** is Set to **Yes**

**Comment by engcom-Bravo** [comment]
@ihor-sviziev Can you please add a Priority label? 
Thank you in advance

**Comment by ihor-sviziev** [comment]
@engcom-Bravo AFAIK priority labels could be set during triage meeting and not by maintainers.
@sidolov @gabrieldagama could you set some priority label?

**Comment by hostep** [comment]
We should probably close this and find a better way to do this, maybe something like I suggested in https://github.com/magento/magento2/pull/30605#issuecomment-714694912 ? So we can cover all kind of cases and make it work in all kind of scenario's.

The solution proposed in this PR seems to only work in very specific cases.

It's very easy to implement this in a custom module should you need it, you just need a couple of files:
```
.
├── etc
│   ├── adminhtml
│   │   └── system.xml
│   └── module.xml
└── registration.php
```

where the `system.xml` file looks like this:
```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Config:etc/system_file.xsd">
    <system>
        <section id="web">
            <group id="url">
                <!-- changed showInWebsite from 0 to 1 -->
                <field id="use_store" showInWebsite="1"/>
            </group>
        </section>
    </system>
</config>
```

Hope this can help others if they have this specific need.

I'm closing it, feel free to comment if you feel I shouldn't close this.

**Pull request closed without merging**
