### PR TITLE
[MFTF] Use AdminReindexAndFlushCacheActionGroup for Reindex and Flush Cache

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR uses `AdminReindexAndFlushCacheActionGroup` for reindex and flush code, 
instead such part of code 
`<magentoCLI command="indexer:reindex" stepKey="reindex"/>`
        `<magentoCLI command="cache:flush" stepKey="flushCache"/>`

### CODE REVIEW

**Review by lbajsarowicz — CHANGES_REQUESTED** [review]
I cannot approve that PR as both
```xml
        <magentoCLI command="indexer:reindex" stepKey="reindex2"/>
        <magentoCLI command="cache:flush" stepKey="flushCache2"/>
```
is a result of lack of basic knowledge about Magento of test authors.

`AdminReindexAdnFlushCacheActionGroup` should be never used!

1. When config has changed, only `<magentoCLI command="cache:clean config">` should be used.
2. When there were any product / category / assignment modifications, you should use `<magentoCron groups="index">`

The only reasonable case for `AdminReindexAdnFlushCacheActionGroup` is when you changed the Index type - eg. from MySQL to Elasticearch, then you need to reindex everything.

Just imagine that you run `cache:flush` and `index:reindex` on production every single time when you change price of single product, or add new product. This is unacceptable, but for test authors... answer yourself :-)

Highly recommended to watch https://www.youtube.com/watch?v=3ZvnBTK8uUM from @johnhughes1984 
Slides: https://docs.google.com/presentation/d/1NdtNz_LBxk-JsCBy8AvekZAkSPWOE0WCzE14Y9ki-5Q/edit?usp=sharing

**Comment by Usik2203** [comment]
Hi @lbajsarowicz .
I have applied changes which you recomended.
I checked failed test and I don't think it's related with my changes.
Thank you for advice.

**Comment by lbajsarowicz** [comment]
There are some leftovers after other people who believed that running Cron twice in a minute would change anything. Please replace that kind of occurrences to single corn :-)
* AdvanceCatalogSearchBundleByNameMysqlTest
  image
* AdvanceCatalogSearchBundleByPriceMysqlTest 
* AdvanceCatalogSearchBundleByShortDescriptionMysqlTest
* StorefrontAdvanceCatalogSearchBundleBySkuWithHyphenTest
* VerifyCategoryProductAndProductCategoryPartialReindexTest (remove `waitForReindex`)
* AdvanceCatalogSearchBundleByDescriptionTest
* AdvanceCatalogSearchBundleByNameTest

I'm sorry you have to fix it, I also faced the same issue while cleaning Action Groups, so I feel the pain.

I also reported issue to @okolesnyk :
`<assertEquals` is used as `Assert Contains` in test:
image

There is one more weird behaviour, that @sivaschenko 's contributors used some weird selector that gets `1920851 records found` instead of `1 records found` visible on the screen.

**Comment by Usik2203** [comment]
Hi @lbajsarowicz 
I changed places where Cron were running twice. Should I do something else ? 
Thank you for advices !

**Comment by lbajsarowicz** [comment]
I'm really sorry, we need to play a little bit more:

image

* AdvanceCatalogSearchBundleByPriceTest
* AdvanceCatalogSearchBundleByNameTest
* AdvanceCatalogSearchBundleByDescriptionTest
* AdvanceCatalogSearchBundleByShortDescriptionTest
* StorefrontAdvanceCatalogSearchBundleBySkuWithHyphenTest
* AdvanceCatalogSearchBundleByShortDescriptionMysqlTest
* AdvanceCatalogSearchBundleByPriceMysqlTest
* AdvanceCatalogSearchBundleByNameMysqlTest

I remember I've also had issues with these tests when I tried to refactor them to use single cron instead whole set of reindexers. But this time we'll make it together :-)

**Comment by VladimirZaets** [comment]
Hi @Usik2203, please resolve conflicts

**Pull request closed without merging**
