### PR TITLE
MC-21193: Renamed the class CollectionFactory to CollectionPool

### PR DESCRIPTION
**Pull request by AleksLi**
Renamed the class CollectionFactory to CollectionPool everywhere

### Description (*)

I found the reason for this. The class name `\Magento\Framework\View\Element\UiComponent\DataProvider\CollectionFactory` created new class every time and not merged all the collections set before. I had to rename this class to CollectionPool to fix this issue. 

### Fixed Issues (if relevant)

1. magento/magento2[#21193](https://github.com/magento/magento2/issues/21193): Types not merged for etc/di.xml etc/adminhtml/di.xml

### Manual testing scenarios (*)

- Do everything as described in the issue.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@AleksLi your change is not backward compatible and makes fails for many tests, so it make impossible to accept such changes without real need.

It seems to me that renaming class is just workaround for the issue. Could you debug deeper or explain if you already did why this issue not appearing if you rename class and starting reproducing with old name?

**Comment by ihor-sviziev** [comment]
@AleksLi I see that there were another trials to fix the issue https://github.com/magento/magento2/pull/20891 https://github.com/magento/magento2/pull/21796 but they were not merged due to backward compatibility issues. Maybe it will help with debug

**Comment by AleksLi** [comment]
The Factory itself is the type of classes that generates once per instance. So I tried to debug the issue and find any other explanation why the configuration in other di.xml files were not merged but it seems like the file name is the key problem here. 
Magento thinks that this is the FACTORY class and setting the latest instance of it without any updates of $collections variable. only the last one. 

But if you think there is another solution for this I will dig dipper to find it.

**Comment by ihor-sviziev** [comment]
@AleksLi I just looked on the object manager classes - i didn't found any special cases for factories.

It seems to me as issue with merging constructor arguments. Don't you think so?

**Comment by AleksLi** [comment]
The reason is not in the file name. I found the exact line where the config of Global DI.xml would be overridden by the local di.xml file.

`lib/internal/Magento/Framework/ObjectManager/Config/Config.php:248` _mergeConfiguration method. Replacing the old configuration with the new one.

**Pull request closed without merging**
