### PR TITLE
magento/magento2#: Remove oauthUserContext from app/code/Magento/GraphQl/etc/graphql/di.xml

### PR DESCRIPTION
**Pull request by atwixfirster**
### Description (*)

**Issue:**
With an active customer's cookies and empty Authorization token GraphQl uses cookies to retrieve a type of user and it's ID.

That's incorrect behavior because GraphQl should use an `Authorization token` ONLY to retrieve a type of user and it's ID.

**Technical details:** 
`Magento_Customer/etc/graphql/di.xml` adds [customerSessionUserContext](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/etc/graphql/di.xml#L12) into `\Magento\Authorization\Model\CompositeUserContext`. It allows to retrieves a customer ID from the session (cookies) wihtin GraphQl operations.

### Fixed Issues (if relevant)

1. magento/magento2#28040: GraphQl. Retrieve customer's shopping cart without an authorization token

### Manual testing scenarios (*)

**Preconditions:**
- Cloud environment
- PWA and Magento installed on the same <Magento_root> folder
- PWA and Magento are available for user per configured `Magento_UpwardConnector`

1. PWA storefront: login as registered user
2. PWA storefront: as a customer please add any product into shopping cart
3. Open a new tab in the same browser window and login as a registered customer in Magento standard storefront
4. PWA storefront: customer makes a logout
5. PWA storefront: verify Shopping cart. 

*Actual result:* guest sees a product which customer has been added into shopping cart. Current quote as a masked quote ID of registered customer.

*Expected result:* a new guest quote has been created after customer's logout.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by atwixfirster** [comment]
Failed **functional tests** are not tie to the PR changes.

Failed WebAPI tests also are not tie to PR changes. However, they report an error - `The store that was requested wasn't found. Verify the store and try again.` which can be reproduced if we run in the mainline:

- dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductInMultipleStoresTest.php::testProductFromSpecificAndDefaultStore()
- dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/GetCartTest.php::testGetCartWithNotExistingStore()
- dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/GetCartTest.php::testGetCartWithNotExistingStore()

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello @atwixfirster, thank you for your contribution!
Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) the changes should be covered by automated tests. Could you please cover this case by API functional test?
Thank you!

**Comment by atwixfirster** [comment]
> Could you please cover this case by API functional test?

**done**

Thank you, @dmytro-ch

**Comment by lenaorobei** [comment]
Confirmed with PO and team that using both - session and token is expected and was a requirement for initial implementation. I'm sorry, but I need to close this issue.

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Please see comment https://github.com/magento/magento2/issues/28040#issuecomment-621940365

Could you please remove `oauthUserContext` from the `ce/app/code/Magento/GraphQl/etc/graphql/di.xml:18` instead.

**Comment by atwixfirster** [comment]
> Could you please remove `oauthUserContext` from the `ce/app/code/Magento/GraphQl/etc/graphql/di.xml:18` instead.

@lenaorobei ,

**done**

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-7512](https://jira.corp.magento.com/browse/ENGCOM-7512) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by dthampy — APPROVED** [review]

**Comment by nrkapoor** [comment]
@danielrenaud @lenaorobei @paliarush Will this PR break the staging functionality in GraphQL?

**Pull request merged**
