### PR TITLE
Remove wrong tags

### LINKED ISSUE #30061: [Issue] Remove wrong tags
This issue is automatically created based on existing pull request: magento/magento2#29868: Remove wrong tags

---------
### Summary (*)

Magento 2.4-develop
This PR removes wrong tags
<pre>
Structure of documentation space
@author ,@category, @package, and @subpackage MUST NOT be used. Documentation is organized with the use of namespaces.
</pre>
Regarding https://devdocs.magento.com/guides/v2.4/coding-standards/docblock-standard-general.html#documentation-space

### PR DESCRIPTION
**Pull request by Usik2203**
This PR removes wrong tags
<pre>
Structure of documentation space
@author ,@category, @package, and @subpackage MUST NOT be used. Documentation is organized with the use of namespaces.
</pre>
Regarding https://devdocs.magento.com/guides/v2.4/coding-standards/docblock-standard-general.html#documentation-space

### Resolved issues:
1. [x] resolves magento/magento2#30061: Remove wrong tags

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@Usik2203 
Could you find all such places and remove them all at once in a single PR? I see 100 pages on github by looking for `author` and only few of them not related to this tag: https://github.com/magento/magento2/search?q=author&unscoped_q=author

**Comment by ihor-sviziev** [comment]
I believe https://github.com/magento/magento2/pull/29866 and https://github.com/magento/magento2/pull/29867 could be merged to this PR?

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
> @Usik2203
> Could you find all such places and remove them all at once in a single PR? I see 100 pages on github by looking for `author` and only few of them not related to this tag: https://github.com/magento/magento2/search?q=author&unscoped_q=author

Hi @ihor-sviziev 

Yes, I can find all places where wrong tags are. But I am not sure that we should deliver these changes in one PR. 

Because on the way we will face others Static issues like we have now . 
In this situation we will get Static issues for hundred files and it will require big efforts. 

I think we should deliver these changes step by step by creating individual PRs.

What do you think?

Thanks

**Comment by ihor-sviziev** [comment]
Ok, let’s split it to few PRs each with amount of files like this or has

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @Usik2203,
Could you fix failing static tests?

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8142](https://jira.corp.magento.com/browse/ENGCOM-8142) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
@magento create issue

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8142](https://jira.corp.magento.com/browse/ENGCOM-8142) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@Usik2203 will you be able to write some static test for this rule in order to prevent re-appearing this issue again, maybe as separate PR?

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Pull request merged**
