### PR TITLE
32019 - Mark interfaces as api

### PR DESCRIPTION
**Pull request by AndreyChorniy**
### Description (*)

This PR for mark interfaces as api.
### Fixed Issues (if relevant)

1. Fixes magento/magento2#32019

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by AndreyChorniy** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Database Compare, Functional Tests B2B

**Comment by eduard13** [comment]
@magento run Functional Tests B2B

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8798](https://jira.corp.magento.com/browse/ENGCOM-8798) has been created to process this Pull Request

**Comment by eduard13** [comment]
@magento run Functional Tests B2B

**Comment by eduard13** [comment]
@magento run Functional Tests B2B

**Comment by gabrieldagama** [comment]
Hi @AndreyChorniy can you recreate this PR to the `api-changes-develop` branch instead? Just make sure to create a new branch from this one and cherry pick your commit.

Thanks!

**Comment by gabrieldagama** [comment]
Closed in favour of https://github.com/magento/magento2/pull/33179

**Pull request closed without merging**
