### PR TITLE
Added action group for cms block duplication test

### PR DESCRIPTION
**Pull request by ajithkumar-maragathavel**
### Description (*)

Added new action group for existing cms block duplication test and replace test action with action groups.

### Questions or comments

The newly introduced action groups can be re-used for future tests.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lbajsarowicz — APPROVED** [review]
Great improvement!

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-6688](https://jira.corp.magento.com/browse/ENGCOM-6688) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by ajithkumar-maragathavel** [comment]
@lbajsarowicz  Unfortunately, I deleted my Magento 2 fork from my account. 
So It is showing as **unknown repository** in the PR.

Please let me know if this PR can be merged or not. 
I appreciate your help.

Thanks.

**Pull request merged**
