### PR TITLE
Fixed issue The js error when click on video thumbnail in product gallery fullscreen mode

### LINKED ISSUE #36456: The js error when click on video thumbnail in product gallery fullscreen mode
### Preconditions and environment

- Magento version: 2.4.4-p2

### Steps to reproduce

1) open on the storefront the product page which has video in product gallery
2) click on the product image to open the gallery fullscreen mode
3) click on the product video thumbnail

### Expected result

the product video will autoplay and no errors in browser console

### Actual result

the js error will appear in the browser console and video will not autoplay 
```
fotorama-add-video-events.js:605 
Uncaught TypeError: this.fotoramaItem.data(...).activeFrame.$stageFrame[0].trigger is not a function
    at $.<computed>.<computed>._checkForVideo (fotorama-add-video-events.js:605:79)
    at $.<computed>.<computed>._checkForVideo (widget.js:132:25)
    at $.<computed>.<computed>._startPrepareForPlayer (fotorama-add-video-events.js:567:18)
    at $.<computed>.<computed>._startPrepareForPlayer (widget.js:132:25)
    at $.<computed>.<computed>.<anonymous> (fotorama-add-video-events.js:545:22)
    at HTMLDivElement.proxy (jquery.js:10780:23)
    at HTMLDivElement.dispatch (jquery.js:5430:49)
    at elemData.handle (jquery.js:5234:47)
    at Object.trigger (jquery.js:8719:28)
    at HTMLDivElement.<anonymous> (jquery.js:8797:30)
```

### Additional information

image

the issue is caused by changes in the commit https://github.com/magento/magento2/commit/e7a06d34dd47d079081d9f007092e35078e36012#diff-5d428affd814bd350e233104b8fc3b769544ee7e6d04a9b21a8537473876ffadR605

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rostilos**
### Fixed Issues (if relevant)

1. Fixes #36456

### Manual testing scenarios (*)
1. open on the storefront the product page which has video in product gallery
2. click on the product image to open the gallery fullscreen mode
3. click on the product video thumbnail
4. the product video will autoplay and no errors in browser console

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rostilos** [comment]
@magento run all tests

**Comment by rostilos** [comment]
@magento run all tests

**Comment by rostilos** [comment]
@magento run WebAPI Tests

**Comment by rostilos** [comment]
@magento run Unit Tests

**Comment by mrtuvn** [comment]
i think this pull request one should have quite high priority when i can reproduced in 2.4.6 and also in lastest code base.
Should consider increase priority to P1

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
As per above request in comment increasing the priority of this PR to Priority2.

**Comment by rostilos** [comment]
@magento run Functional Tests EE

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
seems bot added the priority 2, hence removing the priority 2

**Comment by ihor-sviziev** [comment]
@glo80326, cool! So please pull the changes from this PR

**Comment by mrtuvn** [comment]
re-add label and correct priority label

**Comment by drinkingsouls** [comment]
There is no fix for playing videos on mobile when gallery is not in full screen mode?

**Comment by YoeriW** [comment]
> There is no fix for playing videos on mobile when gallery is not in full screen mode?

@drinkingsouls 
Change this:

`if (this.isFullscreen && this.fotoramaItem.data('fotorama').activeFrame.i === number) {
      this.fotoramaItem.data('fotorama').activeFrame.$stageFrame[0].trigger('click');
  }`
  
  to this:
  
`if (this.isFullscreen && this.fotoramaItem.data('fotorama').activeFrame.i === number) {
      this.fotoramaItem.data('fotorama').activeFrame.$stageFrame.trigger('click');
  }`
  
  Now the Product Video will start playing when you click on the thumbnail + the error will not be shown anymore.
  
  If you want to autoplay the videos without fullscreen on you could change the code to:
  
  `if (this.fotoramaItem.data('fotorama').activeFrame.i === number) {
      this.fotoramaItem.data('fotorama').activeFrame.$stageFrame.trigger('click');
  }`

**Pull request merged**
