### PR TITLE
Unifying REST API searches with the interface method getList() and http ...

### PR DESCRIPTION
**Pull request by SchumacherFM**
...method PUT.

 Deleted POST routes and merged them to a PUT route to be more consistent with all other getList implementations.

### CODE REVIEW

**Comment by SchumacherFM** [comment]
The two tests which are failing are not mine and some date tests:
```
1) Magento\Framework\Data\Form\Element\DateTest::testGetValue with data set #0 (array('short', 'short', 1420187502), '01/2/15 12:31 AM')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'01/2/15 12:31 AM'
+'1/2/15 12:31 AM'
```

**Comment by choukalos** [comment]
Link to internal issue ( MAGETWO-31679 ); Looks like builds are failing as API tests have been added into most recent builds - failing since POSTS have been changed to PUTS.  

Internally on this issue there's some debate between using PUT vs GET for search operations.  Do you-all prefer PUT given the complex search parameters that can be passed?

**Comment by Vinai** [comment]
Just on a side note, the test fail is not related to the POST -> PUT change but because of the issue fixed in PR #913.

**Comment by wsakaren** [comment]
There is a limit in Internet Explorer as I understand with GET requests - 2048 chars.  I'm not sure on how that applies to PUTs but know at WSA we use POST in some instances rather than GET for this and other reasons.

**Comment by avoelkl** [comment]
According to HTTP standards, GET is used to request a resource which - in my opinion - a search is.
PUT is used for storing new resources (or update them), POST to add sub-resources.
So the correct method would be GET.

**Comment by alankent** [comment]
Agreed - PUT is for creating new resources, not doing a search. GET is most correct semantically if you just have a URL, POST is necessary when the URL is not / cannot be used to pass in parameters. PUT is not appropriate if there are no side effects (e.g. no new database entity has been created, as in a search).

**Comment by SchumacherFM** [comment]
In that case (Alan) there needs to be more API routes changed from PUT to POST.
The search query can easily grow to more than 2048 chars so that GET could/would fail.

```
{
    "search_criteria": {
        "filter_groups": [
            {
                "filters": [
                    {
                        "field": "attribute_name",
                        "value": [string|int|float],
                        "condition_type": [string]; optional
                    }
                    more entries
                ]
            }
            more entries
        ],
        "current_page": [int] page number; optional
        "page_size": [int] number of items on a page; optional
        "sort_orders": [ optional
            {
                "field": "attribute_name",
                "direction": [int] -1 or 1
            }
            more entries
        ]
    }
}
```

**Comment by alankent** [comment]
Yep (SchumacherFM). They should definitely be all made consistent.

**Comment by TexanHogman** [comment]
Based upon some [research](http://stackoverflow.com/questions/3721034/how-long-an-url-can-internet-explorer-9-take) looks like IE9+ overcome 2048 limit.  We have an internal ticket opened to convert all REST search requests to GET.  Most importantly is getting them consistent.

**Comment by avoelkl** [comment]
+1 for making them consistent.

Would be great if we could make it to implement GET. That would be one of a few *really* correct implemented REST APIs.

**Comment by GordonLesti** [comment]
REST in my eyes:
* `POST` - create resource
* `GET` - returns resource
* `PUT` - edit resource
* `DELETE` - delete resource
A `search` isn't really part of REST in my eyes, but `GET` matches the most for me. Maybe `POST`, but not `PUT`.

**Comment by choukalos** [comment]
@SchumacherFM can you update the PR to 'GET' & address the travis build failure?  

Based on the feedback & discussion with our lead architect, @TexanHogman, this is the route we'd like to go because we call out IE9+ for full support right now in M1 ( 1.9 / EE 1.14 for responsive theme [link}http://www.magentocommerce.com/knowledge-base/entry/ee114-ce19-rwd-dev-guide#support] ).

Thanks

**Comment by SchumacherFM** [comment]
I will do. I'm closing this PR and send you a new one

**Pull request closed without merging**
