### PR TITLE
magento/magento2#18847: Cant delete the sample link

### PR DESCRIPTION
**Pull request by swnsma**
### Description (*)
Issue appears after the issue: MAGETWO-63321: Issue when deleting item from Product options grid containing more than 20 options
Removing of elements from record data:
https://github.com/magento/magento2/blob/072ef373a4bd2e17f8989878b396b15d927c3895/app/code/Magento/Ui/view/base/web/js/dynamic-rows/dynamic-rows.js#L638
Leads to missed records in request array.
But PHP expects to receive records in any case (with flag 'is_deleted' when it must be deleted). 

### Fixed Issues 
1. magento/magento2#18847: Cant delete the sample link
2. magento/magento2#19344: Sample Link Issue in Downloadable product

#### Pre-conditions:
1. Downloadable product
#### Steps to reproduce:
1. Create sample link for the product.
2. Press 'Save',
3. Delete all sample links.
4. Press 'Save',
#### Expected results:
1. Links were removed.
#### Actual results:
1. Links still exist.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @swnsma. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](http://34.228.235.121/i-19150-2-3-develop/).
Admin access: [http://34.228.235.121/i-19150-2-3-develop//admin](http://34.228.235.121/i-19150-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rogyar** [comment]
Hi @swnsma. Thank you for the contribution. I'm unable to reproduce this issue somehow. Have 25 sample links for a downloadable product (pagination of the links appears in this case). Still can remove a link without an issue. 
Could you provide a step by step directions how you are able to reproduce this issue? Since the description here and in the original issue does not contain enough information on how you can reproduce it. 
Thank you.

**Comment by swnsma** [comment]
Hello @rogyar.
Thank you for your review.
I have updated issues description.
This case also works for downloadable product links.

**BTW**
To clarify my comment, this problem was appears after solution, which was done in issue MAGETWO-63321 (found related in git history).
Could you provide details of this issue?
Looks like we need to provide another solution for MAGETWO-63321.
Otherwise, it will require big refactoring.

**Comment by agorbulin** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @agorbulin. Thank you for your request. I'm working on Magento instance for you

**Comment by orlangur** [comment]
@swnsma @rogyar please assure symmetric case is fixed also: https://github.com/magento/magento2/issues/19386

**Comment by ansari-ziyaurrahman** [comment]
#19344

**Pull request closed without merging**
