### PR TITLE
[MFTF] use AdminNavigateNewCustomerActionGroup to go to new customer page

### LINKED ISSUE #29287: [Issue] [MFTF] use AdminNavigateNewCustomerActionGroup to go to new customer page
This issue is automatically created based on existing pull request: magento/magento2#29134: [MFTF] use AdminNavigateNewCustomerActionGroup to go to new customer page

---------
This PR use `AdminNavigateNewCustomerActionGroup` to go to `AdminNewCustomerPage.url`

### PR DESCRIPTION
**Pull request by Usik2203**
This PR use `AdminNavigateNewCustomerActionGroup` to go to `AdminNewCustomerPage.url`

### Resolved issues:
1. [x] resolves magento/magento2#29287: [MFTF] use AdminNavigateNewCustomerActionGroup to go to new customer page

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE ,  Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by eduard13** [comment]
@magento run all tests

**Review by eduard13 — APPROVED** [review]
Thank you for your contribution 👍

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-7868](https://jira.corp.magento.com/browse/ENGCOM-7868) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
@magento create issue

**Pull request merged**
