### PR TITLE
Modified for Automatic Instock & Out of Stock Update - #dmcdindia1

### PR DESCRIPTION
**Pull request by mageshrdckap**
Product Stock Status Automatic Update 

**Description** (*)
Product Stock Status is updated based on the Quantity Available. If Quantity is 0 out of stock was automatically updated. But if Quantity is increased Instock was not updated. This pull request sorts this issue.

**Fixed Issues (if relevant)**
#22388 - Admin panel Product Stock status is not automatically getting updated from out of stock to in-stock 

**Manual testing scenarios (*)**
1. If quantity=0 stock status should be Out Of Stock
2. If quantity>0 stock status should be In Stock 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22685) <br/>All committers have signed the CLA.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5359](https://jira.corp.magento.com/browse/ENGCOM-5359) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @mageshrdckap !

During testing, we faced an issue.

_Problem:_ After fix, there was a complete dependence of "**Stock Status**" field on "**Quantity**" 

**Manual testing scenario:**

1. Login to Admin;
2. Go to Catalog-> Products -> Add Product;
3. Fill all required fields and set Quantity ( 5 for example);
4. Save product;
**Actual Result:** :heavy_check_mark:  "Stock Status": "In Stock"
5. Try to change "Stock Status" to " Out of Stock"
6. Save product;
**Expected Result:** 
:heavy_check_mark: "Stock Status": "Out of Stock"
**Actual Result:** 
:heavy_multiplication_x: "Stock Status" : " In Stock"

 I'm not sure that this is the right behavior.

@sidolov Could you take a look?

Thanks!

**Comment by sivaschenko** [comment]
@chernenm can you please help us to identify the correct desired behaviour of product stock controls

**Comment by sidolov** [comment]
@mageshrdckap , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
