### PR TITLE
magento/magento2#37796: Fixed issue with adding new country regions

### LINKED ISSUE #37796: Upgrading Magento resets general/region/state_required when new country with required state/region is added.
### Summary

When a new Country is added with required states (in 2.4.6 this was Czechia). The `general/region/state_required` gets reset to the default countries with a required state (or at the very least readds all those countries).  Which means that if you had modified this configuration and have some form of custom code that assumes region is disabled. This could break your shop.

### Examples

This is the Data patch for adding the Regions of Czechia.
```
    public function apply()
    {
        /** @var DataInstaller $dataInstaller */
        $dataInstaller = $this->dataInstallerFactory->create();
        $dataInstaller->addCountryRegions(
            $this->moduleDataSetup->getConnection(),
            $this->getDataForCzechia()
        );
        
        return $this;
    }
```
And this is the DataInstaller which adds the regions as expected. But then follows this up by resetting the state required countries.
```
    public function addCountryRegions(AdapterInterface $adapter, array $data)
    {
        /**
         * Fill table directory/country_region
         * Fill table directory/country_region_name for en_US locale
         */
        foreach ($data as $row) {
            $bind = ['country_id' => $row[0], 'code' => $row[1], 'default_name' => $row[2]];
            $adapter->insert($this->resourceConnection->getTableName('directory_country_region'), $bind);
            $regionId = $adapter->lastInsertId($this->resourceConnection->getTableName('directory_country_region'));
            $bind = ['locale' => 'en_US', 'region_id' => $regionId, 'name' => $row[2]];
            $adapter->insert($this->resourceConnection->getTableName('directory_country_region_name'), $bind);
        }
        /**
         * Upgrade core_config_data general/region/state_required field.
         */
        $countries = $this->data->getCountryCollection()->getCountriesWithRequiredStates();
        $adapter->update(
            $this->resourceConnection->getTableName('core_config_data'),
            [
                'value' => implode(',', array_keys($countries))
            ],
            [
                'scope="default"',
                'scope_id=0',
                'path=?' => \Magento\Directory\Helper\Data::XML_PATH_STATES_REQUIRED
            ]
        );
    }
```

### Proposed solution

Only add the modified country to `general/region/state_required`.

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by yaroslav-kozar**
Fixed issue when the configuration 'general/region/state_required' gets reset to the default countries with a required states.

### Description (*)
According to [#37796 ](https://github.com/magento/magento2/issues/37796) in \Magento\Directory\Setup\DataInstaller::class weren't declared proper logic of saving configuration 'general/region/state_required'. That could lead to problems for the web-site if you changed that configuration from the admin panel previously and then decided to add some new regions for some specific country. 
Based on that I've fixed the bug with the help of getting current configuration value before any DB updates, then I'm merging it with new data that should be added and finally updating the configuration with proper value.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#37796

### Manual testing scenarios (*)
1. Go to the admin panel and open Stores > Settings > Configuration > General > General > State Options
2. Unselect US from "State is Required for" and save configuration.
image
3.Then go to the project root and check with CLI command config value and make sure that US is not in there.
image
4.Then use this custom module to add Japan with regions to state_required config.
[RequiredVendor.zip](https://github.com/magento/magento2/files/12894168/RequiredVendor.zip)
5.In case if my fix is applied you would get a proper result for config - including JP but still excluding US.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Yaroslav1301** [comment]
@magento run all tests

**Comment by Yaroslav1301** [comment]
@magento run all tests

**Comment by shikhamis11** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @Yaroslav1301,

Thanks for the contribution!

Please check the static test failure.

Other, B2B and CE failures are different in 2 consecutive runs so they might be flaky.

Thanks

**Comment by Yaroslav1301** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Review by engcom-Hotel — APPROVED** [review]
:heavy_check_mark: Approving this PR for further processing.

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Echo** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

1. We have follow steps from [comment](https://github.com/magento/magento2/pull/38076#issue-1942011996)


**Before:** :heavy_multiplication_x: 
Screenshot 2023-11-09 at 12 47 41 PM



**After:** :heavy_check_mark:  
Screenshot 2023-11-09 at 1 06 25 PM



Hence moving it to `Merge In Progress`

**Comment by engcom-Charlie** [comment]
@magento run Integration Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Integration Tests,Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run Integration Tests,Functional Tests CE

**Comment by engcom-Charlie** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Integration Tests

**Comment by engcom-Charlie** [comment]
Hi @Yaroslav1301,

Thank you for your contribution!

We got functional and Integration test failures in this PR after pulling the latest magento 2.4-develop code into it.  As the build is failing we have removed this PR from merging. 

In order to move further, we need to fix the [Integration](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38076/8bc00c2293efde1fb8957554c485754f/Integration/console-error-logs.html) failure.  Moving into to Extended Testing.

Thank you!

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Integration Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests ,Unit Tests ,Integration Tests ,Functional Tests EE,Functional Tests CE ,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by Yaroslav1301** [comment]
@magento run Functional Tests CE,Functional Tests B2B,Functional Tests EE

**Comment by Yaroslav1301** [comment]
@magento run all tests

**Comment by Yaroslav1301** [comment]
@engcom-Charlie Hi!
1. Integration Tests: Magento\NegotiableQuote\Cron\ExpireQuoteTest::testExecute and Magento\NegotiableQuote\Model\History\LogInformationTest::testGetQuoteHistoryForCustomerCreatedQuote are not related to my PR.
2. Webapi Tests: Magento\GraphQl\Quote\Customer\SetBillingAddressOnCartTest::testSetBillingAddressIfCustomerIsNotOwnerOfAddress and Magento\GraphQl\Sales\RetrieveOrdersByOrderNumberTest::testGetCustomerDescendingSortedOrders and Magento\GraphQl\CmsGraphQl\Model\Resolver\BlockTest::testCmsMultipleBlockResolverCacheAndInvalidationAsGuest are not related to my PR
3. Functional Tests CE,Functional Tests EE,  Functional Tests B2B failures are different on last two run on same commit:

Run 1 Functional Tests B2B
image
Run 1 Functional Tests CE
image
Run 1 Functional Tests EE
image


Run 2 Functional Tests CE
Passed
Run 2 Functional Tests EE
image
Run 2 Functional Tests B2B
image

**Comment by engcom-Echo** [comment]
@Yaroslav1301 Functional Tests EE,Functional Tests B2B contains failure(**MC-20234: Update customer address on storefront with Belgium address**) which is repeating.

We are investigating further to make build green.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,WebAPI Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B,Functional Tests EE,Functional Tests CE,Integration Tests,WebAPI Tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B,WebAPI Tests

**Comment by engcom-Echo** [comment]
Functional Tests B2B,Functional Tests CE,Functional Tests EE contains known failure.

[ACQE-3807](https://jira.corp.adobe.com/browse/ACQE-3807) - AdminAdobeStockImagePreviewSameSeriesSeeMoreTest
[ACQE-6450](https://jira.corp.adobe.com/browse/ACQE-6450) - AdminAdobeStockImagePreviewSameModelSeeMoreTestz
[ACQE-6018](https://jira.corp.adobe.com/browse/ACQE-6018) - AdminCreateShipmentWithBundleAndSimpleProductsSingleStockModeTest
[ACQE-5677](https://jira.corp.adobe.com/browse/ACQE-5677) - StorefrontQuoteCanBeRenamedUntilLockedTest
[ACQE-6438](https://jira.corp.adobe.com/browse/ACQE-6438) - StorefrontPropertiesOfAProductAttributeTest
[ACQE-6454](https://jira.corp.adobe.com/browse/ACQE-6454) - AdminSeeMoreFromSeriesTest 
[ACQE-6349 ](https://jira.corp.adobe.com/browse/ACQE-6349 )- AdminContentHierarchyDisabledScopeWebsiteFilterTest
[ACQE-6438](https://jira.corp.adobe.com/browse/ACQE-6438) - StorefrontPropertiesOfAProductAttributeTest
[ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331) - StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest

Functional Tests EE
Run1
EE-1

Run2
EE-2

Functional Tests CE
Run1
CE-2

Run2
CE-1

Functional Tests B2B
Run1
B2B-1

Run2
Screenshot 2024-04-15 at 7 49 22 PM


Web Api failrue is not related to PR changes
Screenshot 2024-04-15 at 7 49 58 PM



Hence Moving it to `merge in progress`

**Pull request merged**
