### PR TITLE
Add Klaviyo query parameter to the list of stripped parameters in VCLs

### LINKED ISSUE #35227: The Varnish configs do not strip Klaviyo marketing parameter
### Preconditions (*)
1. Any Magento version that includes a suggested Varnish VCL config.
2. Using Varnish along with a VCL that is included with Magento.
3. Usage of Klaviyo's marketing email services/modules.

### Steps to reproduce (*)
1. Use a VCL that is included with Magento.
2. Send a marketing email via Klaviyo.
3. Watch varnishlog.
4. Visit the site using a link that is included in a Klaviyo-generated email.
5. Visit the site using a similar link that does not include the `_kx` query parameter.
6. Compare the results shown by varnishlog.

### Expected result (*)
1. The `_kx` parameter should be stripped, ensuring that visitors using links with the `_kx` parameter are served the cached version of the requested page.

### Actual result (*)
1. Varnish does not strip the parameter, and since the value is unique per visitor, those requests will not match any hashes in Varnish's cache.
2. This also results in additional PHP load due to the request needing to be processed by Magento.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Gelmo**
### Description (*)
- Related to Issue #35227
- Klaviyo's emails include the `_kx` query parameter.
- Klaviyo's services and modules are becoming more popular, so this query parameter should be stripped in the default Varnish configs provided with Magento.
- This PR adds `_kx` to the list of stripped parameters in the VCLs for Varnish 4, 5, and 6.

### Related Pull Requests
- None

### Fixed Issues (if relevant)
1. Fixes magento/magento2#35227

### Manual testing scenarios (*)
- Use a VCL that is included with Magento.
- Send a marketing email via Klaviyo.
- Watch varnishlog.
- Visit the site using a link that is included in a Klaviyo-generated email.
- Visit the site using a similar link that does not include the `_kx` query parameter.
- Compare the results shown by varnishlog.
- Without this change in place, the request with the `_kx` parameter is served an uncached page.
- With this change in place, the request with the `_kx` parameter is served a cached page.

### Questions or comments
- Our company (JetRails) has several clients that utilize Klaviyo's services for sending marketing emails. We noticed that visitors who came to the site from those emails were being served uncached pages. The adjustment in this PR has successfully resolved this issue for our clients.
- Klaviyo's services and modules are becoming more popular, so this query parameter should be stripped in the default Varnish configs provided with Magento.
- Please list myself and JetRails as the contributors once this has been merged.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Gelmo** [comment]
I am discussing the CLA with my employer, and I will re-create the PR as advised once the CLA has been read and signed.

**Comment by vasileuskidzmitry** [comment]
Hello @sdzhepa!
Could you please advise how to get this pull request and ticket off the ground?
I can take it upon myself and complete all the required steps.

**Comment by vasileuskidzmitry** [comment]
@magento run all tests

**Comment by vasileuskidzmitry** [comment]
@magento run Functional Tests CE

**Comment by vasileuskidzmitry** [comment]
@magento run Sample Data Tests CE, Sample Data Tests EE, Sample Data Tests B2B, Functional Tests CE

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
Hi @Gelmo ,

Thanks for the collaboration & contribution!

✔️ QA Passed
Preconditions:

Install fresh Magento 2.4-develop
Steps to reproduce
- As per the description or https://github.com/magento/magento2/issues/35227#issuecomment-1819258285

Before: ✖️ 
- Each request with the _kx parameter was served as uncached.

After: ✔️
- Each request with the _kx parameter is served from cache.

Got the green build, so moving it to merge in progress.

**Comment by hostep** [comment]
@engcom-Dash: it's probably better to continue with https://github.com/magento/magento2/pull/39188 instead, as that one contains the fix from here + a bunch of other extra parameters. The commit from this PR got cherry picked so the author is kept in git history.

**Comment by engcom-Dash** [comment]
Hello @Gelmo,

Thanks for your contributions.

As per https://github.com/magento/magento2/pull/35228#issuecomment-2417553377, we are putting this PR on hold since the changes have been cherry-picked into another [PR](https://github.com/magento/magento2/pull/39188/) with some additional code changes. We will update you here once the other PR is merged.

Thanks!

**Comment by ihor-sviziev** [comment]
Hi @Gelmo,
Thank you so much for your contribution!

I see that https://github.com/magento/magento2/pull/39188 was already merged, and it contained a cherry-picked commit from this PR (https://github.com/magento/magento2/pull/39188/commits/a3b85c917ad70146aeb1e4e5bc2561ec8f9fc4dc).

Since all changes have already been merged, I'm closing this PR.

**Pull request closed without merging**
