### PR TITLE
issue #22745 fixed: Wrong discount amount calculating for cart price rules if cart rule set to fixed amount 

### LINKED ISSUE #22745: Wrong discount amount calculating for cart price rules if cart rule set to fixed amount
### Steps to reproduce

1.  Create cart price rule with Fixed amount discount.
2. Add products to shopping cart.
3. Add discount coupon to cart, click on apply discount button and check for cart totals.

### Expected result

Mentioned Discount amount should apply to cart.

### Actual result

100% discount applying on subtotal.

### PR DESCRIPTION
**Pull request by mahesh-rajawat**
Fixed: Wrong discount amount calculating for cart price rules if cart rule set to fixed amount  in this PR
### Description (*)

Fixed: #22745 in this PR.
### Fixed Issues (if relevant)

1. magento/magento2#22745
2. ...

### Manual testing scenarios (*)

1. Create cart price rule with Fixed amount discount.
2. Add products to shopping cart.
3. Add discount coupon to cart, click on apply discount button and check for cart totals.
4. Correct discount getting applied now.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hi @maheshWebkul721,
thank you for your contribution!
Could you please cover the corresponding case with an automated test?

**Comment by mahesh-rajawat** [comment]
@dmytro-ch , do i need to complete Mftf or do i need to write Unit Test case?.

**Comment by dmytro-ch** [comment]
@maheshWebkul721 no, I mean the appropriate integration test
`\Magento\SalesRule\Model\Rule\Action\Discount\CartFixedTest`

**Comment by mahesh-rajawat** [comment]
> @maheshWebkul721 no, I mean the appropriate integration test
> `\Magento\SalesRule\Model\Rule\Action\Discount\CartFixedTest`

Ok @dmytro-ch , i will add the test case for this update.

**Comment by engcom-Golf** [comment]
@dmytro-ch test added.  Please review.

**Comment by dmytro-ch** [comment]
@engcom-Golf, thank you!

@maheshWebkul721, there also failing Functional Tests.
Please make sure the changes don't lead to additional issues for some specific cases by checking the failed tests.
Feel free to update the tests that are based on a wrong behavior of the cart price rules feature.

**Comment by sidolov** [comment]
@maheshWebkul721 functional tests still failing, could you take a look?

**Comment by sidolov** [comment]
@maheshWebkul721 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by mahesh-rajawat** [comment]
i am working on it.

**Comment by sidolov** [comment]
Hi @maheshWebkul721 , do you have any progress on the PR? It was reopened 11 days ago and still hasn't additional changes.

**Comment by sidolov** [comment]
@maheshWebkul721  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by evs-xsarus** [comment]
@maheshWebkul721 your PR isn't in the main branch yet, are you planning on updating it?

**Pull request closed without merging**
