### PR TITLE
fix disabling input field when selected Store View

### PR DESCRIPTION
**Pull request by amikitevich**

### CODE REVIEW

**Comment by davidalger** [comment]
@amikitevich Thanks for your contribution. Please sign the license CLA so this can be processed further.

**Comment by amikitevich** [comment]
Hello, I've signed the license CLA.

**Comment by Vinai** [comment]
Thank you for the PR! We are currently waiting for the travis builds to work again, which should happen in a few days. Once that is running and the tests are green we can continue to process your contribution. Unfortunately the License Agreement still shows as not signed. I'm aware that might be an issue with the system. Can you please try to sign again? Sorry for the inconvenience.

**Comment by amikitevich** [comment]
Hello, I've signed CLA again but it seems still shows as not signed.

**Comment by KrystynaKabannyk** [comment]
hello @amikitevich, can you please update code of the PR and cover it by Travis tests?

**Comment by KrystynaKabannyk** [comment]
Hello @amikitevich, since we didn't get a response from you I'm closing the PR. If you will have additional information regarding this PR please feel free to reopen it.

**Pull request closed without merging**
