### PR TITLE
"laminas/laminas-mime" updated to ^2.8.0

### PR DESCRIPTION
**Pull request by khrystynastolbova**
### Description (*)

Update laminas/laminas-mime to PHP 8 compatible version (2.8.0)

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/521

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32319

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by khrystynastolbova** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @khrystynastolbova,
Could you also update `laminas/laminas-mime
` in the Magento framework's composer.json file?
https://github.com/magento/magento2/blob/4f8d9c23f5a7a9787b3c2fadd8f0c6bbf8c87a0e/lib/internal/Magento/Framework/composer.json#L32

**Comment by khrystynastolbova** [comment]
> n the Magento framework's composer.json file

Done

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @khrystynastolbova,
Could you resolve conflicts?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Unit Tests

**Comment by sivaschenko** [comment]
@ihor-sviziev static tests are failing because of dependency was not updated in EE repository

**Comment by sivaschenko** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Pull request merged**
