### PR TITLE
prototype.js: check element has parent node before remove.

### LINKED ISSUE #35387: Wrong polyfill for HTMLElement.prototype.remove throw error in edge case.
### Preconditions (*)

Magento/2.4 (Enterprise)

### Steps to reproduce (*)

In javascript code, create an element without parent, then call `remove` function. For example:
`document.createElement('div').remove()` 

1. Browse to Magento 2.4 website.
2.  Open console
3. Run document.createElement('div').remove()

### Expected result (*)

Nothing happen.
### Actual result (*)

An exception thrown:
```
Uncaught TypeError: Cannot read properties of null (reading 'removeChild')
    at remove (legacy-build.min.js:formatted:1759:22)
    at HTMLDivElement._methodized [as remove] (legacy-build.min.js:formatted:396:22)
    at <anonymous>:1:31
```
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

### PR DESCRIPTION
**Pull request by EladHeller**
### Description (*)

Before call to `removeChild` on parent node, check that parent node is not null.
If the parent node is null, no action needed.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35387

### Manual testing scenarios (*)

1. Browse to Magento 2.4 website.
2. Open console
3. Run `document.createElement('div').remove()`
4. Expected result: nothing happen.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by EladHeller** [comment]
@magento give me test instance

**Comment by EladHeller** [comment]
@magento run all tests

**Comment by EladHeller** [comment]
@magento run B2B

**Comment by EladHeller** [comment]
@magento run Functional Tests B2B

**Comment by EladHeller** [comment]
@magento run Adobe CLA Signed?

**Comment by EladHeller** [comment]
@magento run Adobe CLA Signed

**Comment by sidolov** [comment]
@EladHeller please, click on the Adobe CLA check link and sign it, thanks!

**Comment by EladHeller** [comment]
No one take care of this PR. I give up.

**Pull request closed without merging**
