### PR TITLE
Fix issue 20232 : Backend order credit card detail check box misaligned

### PR DESCRIPTION
**Pull request by SyntaxKay**
### Description (*)

 Backend order credit card detail check box misaligned
### Fixed Issues (if relevant)

1. magento/magento2#20232:  Backend order credit card detail check box misaligned

### Manual testing scenarios (*)

1.Backend -> sale -> order -> create new order/reorder(Perticular order)
2.Under payment method -> credit card -> check save for later checkbox alignment

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](https://i-20233-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20233-2-3-develop.instances.magento-community.engineering/admin](https://i-20233-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
