### PR TITLE
Fixed #20631 for 2.3

### LINKED ISSUE #20631: Console error on checkout after changing the allowed countries from admin.
### Preconditions (*)

1. Magento 2.2.x
2. Magento 2.3.x

### Steps to reproduce (*)

1. Add a product to cart as guest.
2. Fill the shipping address and reload the page now shipping address must be filled already.
3. Go to Admin->Stores->configuration->General, Change allowed countries single one that is not filled on checkout. like i have filled United State at checkout and change allowed countries to Libya.
4. Now reload the checkout shipping page again. 

### Expected result (*)

1. 
screen shot 2019-01-26 at 5 23 49 pm

2.

### Actual result (*)

1. screen shot 2019-01-26 at 5 21 28 pm
2.

### PR DESCRIPTION
**Pull request by mahesh-rajawat**
Reference PR #20632.
Fixed #20631

### Fixed Issues (if relevant)

1. #20631 
2. ...

### Manual testing scenarios (*)

1. Add a product to cart as guest.
2. Fill the shipping address and reload the page now shipping address must be filled already.
3. Go to Admin->Stores->configuration->General, Change allowed countries single one that is not filled on checkout. like i have filled United State at checkout and change allowed countries to Libya.
4. Now reload the checkout shipping page again. 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by novikor** [comment]
@maheshWebkul721 , it seems you forgot to push your changes :smile:

**Comment by mahesh-rajawat** [comment]
@novikor changes added.

**Comment by swnsma** [comment]
Hi @maheshWebkul721 
Thank you for your pull request.
Please merge all your commits into one.

You can do it with next instruction:
- Open project in terminal
- Run `git rebase -i commit_hash`, where _commit_hash_ is Revision Number of commit from which your branch was created.
- You should see a list of commits, each commit starting with the word "pick".
- Make sure the first commit says "pick" and change the rest from "pick" to "squash". -- This will squash each commit into the previous commit, which will continue until every commit is squashed into the first commit.
- Save and close the editor.
- It will give you the opportunity to change the commit message.
- Save and close the editor again.
- Then you have to force push the final, squashed commit: git push -f

**Review by swnsma — CHANGES_REQUESTED** [review]
Hi @maheshWebkul721
Thank you for your pull request.
Please merge all your commits into one.

You can do it with next instruction:
- Open project in terminal
- Run git rebase -i commit_hash, where commit_hash is Revision Number of commit from which your branch was created.
- You should see a list of commits, each commit starting with the word "pick".
- Make sure the first commit says "pick" and change the rest from "pick" to "squash". -- This will squash each commit into the previous commit, which will continue until every commit is squashed into the first commit.
- Save and close the editor.
- It will give you the opportunity to change the commit message.
- Save and close the editor again.
- Then you have to force push the final, squashed commit: git push -f

**Comment by mahesh-rajawat** [comment]
Hi @swnsma , i have tried to do rebase it like:
i have created this branch from my fork project 2.3-develope. And on 2.3-develop branch latest commit
id is `103282cb113128ac4049cae98abc49001aea1fec`, so i did it like:
`git rebase -i 103282cb113128ac4049cae98abc49001aea1fec` i didn't see the list of commits on editor.
when i close editor, message says rebase successfully, then tried to push, now message is: everything 
up to date.

**Comment by swnsma** [comment]
Hi @maheshWebkul721,
You can try next:
- Checkout to your branch;
- Use `git log` in terminal to see history of commits;
- Scroll down to first commit which are not present in current pull request (so, last commit which was done without your changes).
- Copy commit hash and use it for rebase;

If it will not help, please sent me screenshot of the problem in your terminal.

**Comment by mahesh-rajawat** [comment]
Hi @swnsma , i think i did it, you are awesome :blush:
Thanks for your Help.

**Comment by swnsma** [comment]
Hi @maheshWebkul721 
Thank you for your contribution and for your time.
This issue already have been fixed  and merged in PR #20634.

**Pull request closed without merging**
