### PR TITLE
Add The Ability To Limit Autocomplete Results

### PR DESCRIPTION
**Pull request by mpchadwick**
### Description

Adds the ability to limit the number of results in the search autocomplete. Defaults to 8

image

### Manual testing scenarios

1. In the admin create a product called "Elephantawesomepants"
2. On the frontend search for "Ele", "Elep", "Eleph", etc... until you've passed the default limit
3. Notice that no more than the configured limit of search terms are displayed

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by vrann** [comment]
@mpchadwick Note from our QA:

It looks like something is broken after this fix.

I have these products: [catalog_product_20171024_082043.csv.zip](https://github.com/magento/magento2/files/1412104/catalog_product_20171024_082043.csv.zip)


image1

When I try to find 'ele' my autocomplete shows me that there are 10 products that match my search expression. We can type one mode letter and still should expect that there are 10 products that match my search expression, but autocomplete is not shown.
image2

And what is really weird is what we see on 2.3-develop:
image3

**Comment by mpchadwick** [comment]
@vrann 

I'm not sure that your QA understands how the search autocomplete functions. The search autocomplete shows suggestions by finding previously run queries that contain the string that the user entered. If a user previously searched "ele" and re-types "ele", "ele" will show in the search autocomplete. If the user types "elep" but a search for "elep" has never happened before it will not show "elep" in the search autocomplete. If that user executes the search for "elep" the next time someone types "elep" into the search bar, it will show as an autocomplete suggestion.

Regarding the screenshot you shared from the admin panel, my change is not targeted at the search feature in the admin panel (in 4 years of working with Magento I don't think I've used that once). I was able to reproduce the red error message from the screenshot...however it was not introduced by my code an I could reproduce it after reverting my changes. The following reproduces reliably for me every time...

1. Import the product set provided (catalog_product_20171024_082043.csv.zip)
2. Type "elep" into the search field in the admin panel
3. Delete "elep" and unfocus the form field

You will get the error at this point

**Comment by vrann** [comment]
@mpchadwick got it, makes sense. Thank you for the explanation!

**Comment by magento-engcom-team** [comment]
@mpchadwick thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by okorshenko** [comment]
Hi @mpchadwick 
Could you please resolve code conflicts so that we can proceed with the PR acceptance?

**Comment by mpchadwick** [comment]
@okorshenko done

**Pull request merged**
