### PR TITLE
Resolve Frontend Label For Custom Order Status not Editable in Magento Admin in Single Store Mode

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

magento/magento2#23654: Frontend Label For Custom Order Status not Editable in Magento Admin in Single Store Mode

Reason: 

        if (!$this->_storeManager->isSingleStoreMode()) {
            $this->_addStoresFieldset($model, $form);
        }

Should be changed. Currently, it only processes the False value. We need to process it if $this->_storeManager->isSingleStoreMode() is True also.

Solution: Use the "if" condition to check if the settings is in "Single Store Mode", it will add only one field "Frontend Label" to change the label for the frontend instead of the Store View Specific Labels

### Fixed Issues (if relevant)

1. magento/magento2#23654: Frontend Label For Custom Order Status not Editable in Magento Admin in Single Store Mode

### Manual testing scenarios (*)

1. Enable "single store mode" in Configuration->General->Single-Store Mode
2. Go to Stores -> Order Status
3. Select any status
=> There should be a field where we can modify the string for a status for the frontend only

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23681) <br/>All committers have signed the CLA.

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-23681.instances.magento-community.engineering).
Admin access: [https://pr-23681.instances.magento-community.engineering/admin](https://pr-23681.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by Stepa4man** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, here is your [new Magento instance](https://pr-23681.instances.magento-community.engineering).
Admin access: [https://pr-23681.instances.magento-community.engineering/admin](https://pr-23681.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by Stepa4man — APPROVED** [review]
Hi @edenduong, Thanks for your contribution!

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, thank you for the review.
[ENGCOM-5453](https://jira.corp.magento.com/browse/ENGCOM-5453) has been created to process this Pull Request
:eight_spoked_asterisk: @Stepa4man, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
