### PR TITLE
Added: SKU with configurable, group, bundle product Title

### LINKED ISSUE #36808: [2.4.5-p1] PayPal Express Checkout - Missing SKU & Full product [variation] title
### Preconditions and environment

- Magento 2.4.5-p1
- PHP8.1
- PayPal Express Checkout (Sandbox or Live) (the included extension)

### Steps to reproduce

1. Enable PayPal Express Checkout [sandbox or live, the result is the same so just do sandbox for this test]
2. Enable "Transfer Cart Line Items"
3. Enable "PayPal Guest Checkout"
4. Submit Order (by credit card using a test number provided [HERE](https://developer.paypal.com/api/rest/sandbox/card-testing)). It is the same end result using a PayPal personal account but for testing purposes just use a test credit card for easier testing.
5. Check PayPal transaction in PayPal sandbox account (not Magento)

### Expected result

When viewing the PayPal transaction in the PayPal account, it should say one of the following:

-Men's T-Shirt-Red, S
-Men's T-Shirt-Red, M
-Men's T-Shirt-Red, L
-Men's T-Shirt-Red, XL

For instance, it should say "SKU 12345678 | Men's T-Shirt-Red, M | QTY 5". It should also show (or have) the SKU included with the line item. 

Pretty sure WooCommerce does exactly that so I'm pretty certain PayPal is capable of taking that information.

### Actual result

Neither are there. What actually shows is this:

Men's T-Shirt QTY 5

That is it. I will attach a screenshot of what I mean. There is no SKU with the item nor is the correct/actual item listed. It simply lists the parent product (Men's T-Shirt) when it was one of it's variants that was purchased (like Red, M or Red, L, etc.). The Magento order transaction page shows all that. But it's like it's not sending it to PayPal?

I just noticed this important missing information. It's very important when it comes to transaction logs and doing taxes. As I am now just noticing this, I realize this is going to be a disaster when doing taxes as there is no real way of me knowing what the COGS was (having no SKU or proper product title I can't sync it to a costs sheet and figure out what my actual net revenue was).

magento-245p1-paypal-missing-sku-product-title-details-screenshot-1

### Additional information

I will test this on a 2.4-dev instance and see but I don't think it will change - it seems like it might have been like this for a long time now.

Thank you in advance. Hopefully someone can point me to a fix for this so I can get my transaction logs reporting correctly.

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by aasim110**
### Description (*)

Changed Magento/Paypal/Model/Cart.php file to add child product SKUs with the Parent product title to identify the product title with the child SKU. 
Check this screenshot for more information: https://prnt.sc/0VgjbwOg-omA

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36808

### Manual testing scenarios (*)

1. Enable PayPal Express Checkout [sandbox or live, the result is the same so just do sandbox for this test]
2. Enable "Transfer Cart Line Items"
3. Enable "PayPal Guest Checkout"
4. Submit the Order (by credit card using a test number provided [HERE](https://developer.paypal.com/api/rest/sandbox/card-testing)). It is the same end result using a PayPal personal account but for testing purposes just use a test credit card for easier testing.
5. Check PayPal transactions in the PayPal sandbox account (not Magento)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by aasim110** [comment]
@magento run all tests

**Comment by aasim110** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by aasim110** [comment]
@magento run Functional Tests EE

**Comment by aasim110** [comment]
@magento run Functional Tests CE

**Comment by aasim110** [comment]
@magento run Functional Tests B2B

**Comment by aasim110** [comment]
@magento run Functional Tests B2B

**Comment by aasim110** [comment]
@magento run Functional Tests B2B

**Comment by aasim110** [comment]
@magento run Functional Tests B2B

**Comment by aasim110** [comment]
@magento  run Functional Tests B2B

**Comment by aasim110** [comment]
@magento run Functional Tests B2B

**Comment by aasim110** [comment]
@magento run all Tests

**Comment by aasim110** [comment]
@magento run WebAPI Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by aasim110** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by aasim110** [comment]
@magento run all Tests

**Comment by aasim110** [comment]
@magento run all Tests

**Comment by aasim110** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by aasim110** [comment]
@magento run all Tests

**Comment by aasim110** [comment]
@magento run Integration Tests, Functional Tests EE, Functional Tests B2B

**Comment by aasim110** [comment]
@engcom-Hotel @engcom-Bravo I could be wrong, but it seems to me that the failed tests do not refer to edits from the PR.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @aasim110,

Thanks for the contribution and collaboration!

The changes seem fine for us but as part of the [definition of done](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1) please cover the changes with some automated tests.

And also please take care of the failed tests.

Thanks

**Comment by aasim110** [comment]
@magento run Unit Tests, WebAPI Tests

**Comment by aasim110** [comment]
@magento run WebAPI Tests

**Comment by aasim110** [comment]
@engcom-Hotel failed tests do not refer to edits from the PR, kindly check again.
Thanks!

**Comment by engcom-Hotel** [comment]
Hello @aasim110,

Thanks for the reply!

Yes, I checked it again and it seems the functional test failures are flaky. But please add some automated tests to cover this fix.

Thanks

**Comment by aasim110** [comment]
@engcom-Hotel there is no need to add automated tests for this case because this fix will update the product name with the child SKU and the product name is already available in Test cases.

**Comment by engcom-Hotel** [comment]
Hello @aasim110,

I agree with your point, we don't require any automated tests here. Hence moving this PR for testing.

Thanks

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:*

1. Enable PayPal Express Checkout [sandbox or live, the result is the same so just do sandbox for this test]
2. Enable "Transfer Cart Line Items"
3. Enable "PayPal Guest Checkout"
4. Submit the Order.
5. Check PayPal transactions in the PayPal sandbox account (not Magento)

**Before:** :heavy_multiplication_x: 

Screenshot 2023-07-13 at 12 12 54 PM
Screenshot 2023-07-13 at 12 37 50 PM

**After:** :heavy_check_mark:  

Screenshot 2023-07-13 at 2 06 26 PM

Builds are failed. Hence, moving this PR to **Extended Testing.**
Screenshot 2023-07-13 at 1 29 27 PM

Screenshot 2023-07-13 at 3 47 17 PM

Builds are failed. Hence, moving this PR to **Extended Testing**

**Comment by engcom-Echo** [comment]
@magento run Unit Tests, WebAPI Tests,Integration Tests,Functional Tests EE,Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Integration Tests,Unit Tests

**Comment by engcom-Echo** [comment]
Functional Tests CE, Functional Tests EE are different on last two run on same commit.
Functional Tests CE
Run1
image

Run2
image

Functional Tests EE
Run1
image

Run2
image

And Integration Tests failure are not related to the PR.
Hence moving it to `Merge In Progress`

**Pull request merged**
