### PR TITLE
Issue #13952 - Duplicate orders with same Quote Id at same time with few time difference.

### LINKED ISSUE #13952: Duplicate orders with same Quote Id at same time with few time difference.
**Preconditions**

1. Ability to process requests at same time. (in our case, we had use 2 different Client's system.)

**Steps to reproduce**
    

1. Login as a User
1. Add items to cart and proceed through checkout.
1. Select Any payment method. Not click on place order button
1. Now login to the same account in another system.
1. And proceed to checkout with the same items. Not click on place order button.
1. Now you have to click on place order at the same time with both the systems.
Observe order confirmation screen of both systems. **(usually first time you will get an error about constraint violations. Try to repeat steps 1-6 again. Issue reproduces 100% from the second attempt)**

Depending on your infrastructure, this bug may be challenging to reproduce. It requires all of the "Place order" button clicks to be processed concurrently by Magento. You will not see the bug if Magento is processing requests sequentially (as the second request will reference a cart ID that no longer exists).

**Expected result**
A single order has been placed.
Alternatively, if multiple requests are unavoidable: Only the first request to be processed.

**Actual result**
Two different orders have been placed with very few seconds as time difference with same quote Id.

### LINKED ISSUE #35833: [Issue] Issue #13952 - Duplicate orders with same Quote Id at same time with few time difference.
This issue is automatically created based on existing pull request: magento/magento2#35139: Issue #13952 - Duplicate orders with same Quote Id at same time with few time difference.

---------
### Description (*)
Two different orders have been placed with very few seconds as time difference with same quote Id.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#13952

### Manual testing scenarios (*)
1. Login as a User
2. Add items to cart and proceed through checkout.
3. Select Any payment method. Not click on place order button
4. Now login to the same account in another system.
5. And proceed to checkout with the same items. Not click on place order button.
6. Now you have to click on place order at the same time with both the systems.
7. one of the screen must return failed 
image

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fiko**
### Description (*)
Two different orders have been placed with very few seconds as time difference with same quote Id.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#13952

### Manual testing scenarios (*)
1. Login as a User
2. Add items to cart and proceed through checkout.
3. Select Any payment method. Not click on place order button
4. Now login to the same account in another system.
5. And proceed to checkout with the same items. Not click on place order button.
6. Now you have to click on place order at the same time with both the systems.
7. one of the screen must return failed 
image

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#35833: Issue #13952 - Duplicate orders with same Quote Id at same time with few time difference.

### CODE REVIEW

**Comment by fiko** [comment]
@magento give me test instance

**Comment by fiko** [comment]
@magento run Database Compare, Static Tests

**Comment by fiko** [comment]
@magento run all tests

**Comment by fiko** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by fiko** [comment]
@magento run Integration Tests

**Comment by amine-y** [comment]
@ihor-sviziev 
Why this ticket is not being taken seriously,
The problem is still happening in active Magento installations

**Comment by ihor-sviziev** [comment]
@sidolov, could you take a look?

**Comment by sdzhepa** [comment]
Hello @amine-y and @ihor-sviziev 

Thank you for raising this issue!

I do not know the reason but looks like this PR was missed because the related issue was closed: https://github.com/magento/magento2/issues/13952 

The issue has a huge thread of comments as I can see a patch was provided to fix it: https://github.com/magento/magento2/issues/13952#issuecomment-711439385.
But the overall situation is not clear is it actual for the current `2.4-develop` 


@engcom-Alfa and @engcom-Charlie  Could you please work together to investigate this problem?
Please review in detail the discussion/comments in  https://github.com/magento/magento2/issues/13952
Try to reproduce this issue by the steps from this PR.
If the problem still exists please create and confirm the new issue with all required details. Also please link a new issue with this PR and add all other links to comments if require

cc: @sidolov

**Comment by engcom-Alfa** [comment]
@magento give me test instance

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @fiko,
Please review and fix the test failures.

**Comment by fiko** [comment]
@magento run Unit Tests

**Comment by fiko** [comment]
@magento run WebAPI Tests

**Comment by fiko** [comment]
> @magento run Unit Tests

will try to investigate & fix them next week, last week Unit Test was failed, but it's just succeed.

**Comment by fiko** [comment]
@magento run WebAPI Tests

**Comment by amine-y** [comment]
@magento give me test instance

**Comment by nishant04412** [comment]
Hi @fiko,

This issue has been taken care in internal JIRA ticket. Once Internal PR will get merged, we will notify it here.

JIRA Ref: https://jira.corp.adobe.com/browse/AC-6057

Thank you!

**Comment by Denisof** [comment]
The fix is not  correct, in case of any quote errors $this->submitQuoteValidator->validateQuote($quote); a user loses active quote.

**Comment by engcom-Charlie** [comment]
Based on above [comment](https://github.com/magento/magento2/pull/35139#issuecomment-1314967271), closing this PR.

Thank you!

**Pull request closed without merging**
