### PR TITLE
Removed CliCacheFlushActionGroup usage for Catalog module

### LINKED ISSUE #31865: [Issue] Removed CliCacheFlushActionGroup usage for Catalog module
This issue is automatically created based on existing pull request: magento/magento2#31864: Removed CliCacheFlushActionGroup usage for Catalog module

---------
### Description
Removed CliCacheFlushActionGroup usage for Catalog module

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Removed CliCacheFlushActionGroup usage for Catalog module

### Resolved issues:
1. [x] resolves magento/magento2#31865: Removed CliCacheFlushActionGroup usage for Catalog module

### CODE REVIEW

**Comment by sergiy-v** [comment]
@magento create issue

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B,Semantic Version Checker

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE

**Comment by sergiy-v** [comment]
@magento run WebAPI Tests, Unit Tests, Static Tests, Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B, Magento Health Index, Integration Tests, Database Compare

**Comment by sergiy-v** [comment]
Everything are green, @eduard13 please proceed with review.

**Review by eduard13 — APPROVED** [review]
Good job 👍

**Comment by engcom-Alfa** [comment]
QA not applicable

**Pull request merged**
