### PR TITLE
Removed Wishlist Sidebar from Wishlist Page

### LINKED ISSUE #29674: [Issue] Remove wishlist sidebar for wishlist index page
This issue is automatically created based on existing pull request: magento/magento2#28441: Remove wishlist sidebar for wishlist index page

---------

### Description (*)

Remove wishlist sidebar for wishlist index page
### Fixed Issues (if relevant)

1. Fixes magento/magento2#N/A

### Manual testing scenarios (*)

1. Add product into a wishlist for registered customer
2. visit My wishlist page

### Expected result
After-My_Wish_List

### Actual result
before-My_Wish_List

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by monikav-dckap**
### Description (*)
This PR will remove the Wishlist Sidebar from the Wishlist Index page.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#29674

### Manual testing scenarios (*)
1. Log in as a registered user and add some products to the wishlist.
2. Navigate to the Wishlist page on the Account Dashboard.
3. Check the Wishlist Sidebar is removed from the page.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by monikav-dckap** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @monikav-dckap. Thank you for your request. I'm working on Magento instance for you

**Comment by monikav-dckap** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @monikav-dckap, here is your [new Magento instance](https://pr-29738.instances.magento-community.engineering).
Admin access: [https://pr-29738.instances.magento-community.engineering/admin_cb7e](https://pr-29738.instances.magento-community.engineering/admin_cb7e)
Login: `795aa36c` Password: `162be0212689`
Instance will be terminated in up to 3 hours.

**Comment by sidolov** [comment]
@monikav-dckap , mentioned issue is already fixed by PR https://github.com/magento/magento2/pull/28441
I'm closing this PR is duplicate. Thank you for the collaboration!

**Pull request closed without merging**
