### PR TITLE
#27500 Prepare Store module Tests for PHPUnit 8

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Preparing PHPUnit Tests to run with PHPUnit 8.
PRs for each module is separated to make tests easier to merge.

### Fixed Issues (if relevant)
1. magento/magento2#27500

### Manual testing scenarios (*)
N/A

### Questions or comments
PR #27701 needs to be merged first (otherwise PHPUnit tests fail)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7387](https://jira.corp.magento.com/browse/ENGCOM-7387) has been created to process this Pull Request

**Comment by rogyar** [comment]
Hi @lbajsarowicz. Looks like after the recent merges to the mainline we have some conflicting files.

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
Failure in SVC:
```
15:39:47 [SVC-Tests-B2B] In StaticAnalyzer.php line 73:
15:39:47 [SVC-Tests-B2B]                                                                                
15:39:47 [SVC-Tests-B2B]   Cannot use Magento\Framework\DB\Adapter\AdapterInterface as AdapterInterfac  
15:39:47 [SVC-Tests-B2B]   e because the name is already in use on line 16 /var/www/magento2ce/app/cod  
15:39:47 [SVC-Tests-B2B]   e/Magento/Store/Test/Unit/Model/ResourceModel/StoreTest.php 
```

**Review by slavvka — CHANGES_REQUESTED** [review]
Please fix the tests

**Pull request merged**
