### PR TITLE
typo error fixed

### PR DESCRIPTION
**Pull request by irshadcedcoss**
typo error fixed

### Description (*)
Typo error fixed

### Manual testing scenarios (*)

Typo error fixed in file lib/web/mage/utils/arrays.js

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22566) <br/>All committers have signed the CLA.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-5004](https://jira.corp.magento.com/browse/ENGCOM-5004) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@irshadcedcoss thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VasylShvorak** [comment]
**Notice:** QA not applicable

**Comment by orlangur** [comment]
@irshadcedcoss unfortunately we cannot process PRs from an `unknown repository`.

**Pull request closed without merging**
