### PR TITLE
Removing unused import.

### PR DESCRIPTION
**Pull request by tiagosampaio**
Removing unused import from class \Magento\Catalog\Model\Product\Copier.

### Fixed Issues (if relevant)

This change doesn't fix any issue.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by tiagosampaio** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run WebAPI Tests, Functional Tests B2B

**Comment by tiagosampaio** [comment]
@magento run WebAPI Tests

**Review by mrtuvn — APPROVED** [review]
change look good with me

**Comment by magento-engcom-team** [comment]
Hi @mrtuvn, thank you for the review.
[ENGCOM-9152](https://jira.corp.magento.com/browse/ENGCOM-9152) has been created to process this Pull Request

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9152](https://jira.corp.magento.com/browse/ENGCOM-9152) has been created to process this Pull Request

**Comment by mrtuvn** [comment]
Closed this one because internal team already fixed it in latest commit
See here https://github.com/magento/magento2/commit/3c5ff49c11eec2d4510b25571acf0d30b804cdf1

**Pull request closed without merging**
