### PR TITLE
Fixed: Incorrect discount amount for whole cart

### LINKED ISSUE #37496: Cart price rules - Incorrect discount amount when using fixed discount amount for whole cart
### Preconditions and environment

- Magento version: 2.3.*, 2.4.*

### Steps to reproduce

Create a Cart price rule:

1 - Marketing -> Promotions -> Cart Price Rules

Conditions:

Screenshot 2023-05-12 at 15 11 48

2 - Actions:

Screenshot 2023-05-12 at 15 13 27

It is important to be: **Fixed amount discount for whole cart**

3 - Create a plugin **afterGetPrice** for the class **Magento\Quote\Model\Quote\Item**. method **getPrice()**

<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">

    <type name="Magento\Quote\Model\Quote\Item">
        <plugin name="my_plugin_name" type="Vendor\Module\Plugin\GetPriceFromQuoteItemPlugin" />
    </type>

</config>

EXAMPLE:

`<?php

declare(strict_types=1);

namespace Vendor\Module\Plugin;

use Magento\Quote\Model\Quote\Item as QuoteItem;

class GetPriceFromQuoteItemPlugin
{

    public function afterGetPrice(QuoteItem $subject, $result): float
    {
        // ADD THE CHANGES HERE....
        
        $result = 1070.0;

        return $result;
    }
}`

Choose a configurable product, and add it to the cart. The price will be changed to the new one, after that, apply the coupon code:

Screenshot 2023-05-12 at 14 30 02

Check the discount value. 

### Expected result

It should be 500.00, not 250.00

### Actual result

It is 250.00

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by aasim110**
### Description (*)

Fixed: Incorrect discount amount when using fixed discount amount for the whole cart

### Fixed Issues (if relevant)

1. Fixes magento/magento2#37496

### Manual testing scenarios (*)

Check this steps for Manual testing : https://github.com/magento/magento2/issues/37496#issuecomment-1562503802

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by aasim110** [comment]
@magento run all tests

**Comment by aasim110** [comment]
@magento run WebAPI Tests, Static Tests

**Comment by aasim110** [comment]
@magento run all tests

**Comment by aasim110** [comment]
@magento run Database Compare

**Comment by aasim110** [comment]
@magento run Integration Tests

**Comment by aasim110** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by aasim110** [comment]
@magento run all tests

**Comment by aasim110** [comment]
@magento run WebAPI Tests, Integration Tests

**Comment by aasim110** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Comment by aasim110** [comment]
@magento run Functional Tests CE

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by aasim110** [comment]
@magento run WebAPI Tests, Unit Tests, Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by aasim110** [comment]
@magento run WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @aasim110,

Thanks for the contribution!

Build failures seem flaky to me and code seems good to me. But please cover the changes with some automated tests.

Thanks

**Comment by aasim110** [comment]
@magento run WebAPI Tests

**Comment by aasim110** [comment]
@magento run Unit Tests

**Comment by aasim110** [comment]
@engcom-Hotel test cases seem flaky to me as well, see screenshots for more information 
**Unit tests** 
image
 **Webapi tests**
image

**Comment by aasim110** [comment]
@magento run Unit Tests, WebAPI Tests

**Comment by engcom-Hotel** [comment]
Yes @aasim110 thats true, can you please add some automated tests as mentioned here https://github.com/magento/magento2/pull/37730#pullrequestreview-1557059603.

**Comment by aasim110** [comment]
@engcom-Hotel  There is no need to add automated tests in this case because the test case of **$this->model->initTotals($items, $this->addressMock)** is already included in the app/code/Magento/SalesRule/Test/Unit/Model/ValidatorTest.php. This test case takes care of the required consideration.

**Comment by engcom-Charlie** [comment]
As per [this](https://github.com/magento/magento2/pull/37730#issuecomment-1663324333) moving this PR to review.

Thank you!

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @aasim110,

Thanks for the reply here https://github.com/magento/magento2/pull/37730#issuecomment-1663324333!

But actually, I think we need an automated test here to cover this particular scenario, in which the discount amount is displaying incorrectly.

**Comment by aasim110** [comment]
@engcom-Hotel, I don't see any conceivable approach, as there's no requirement to include it for a specific scenario.

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**
Create a Cart price rule:

1 - Marketing -> Promotions -> Cart Price Rules

Conditions: Subtotal (excl Tax)equals or greater than 1000



2 - Actions:  Fixed amount discount for the whole cart
Discount amount 500

3 - Create a plugin afterGetPrice for the **class Magento\Quote\Model\Quote\Item. method getPrice()** or paste the Folder in the path `app/code`.
[Magz.zip](https://github.com/magento/magento2/files/12334822/Magz.zip)

4 - Choose a configurable product, and add it to the cart. The price will be changed to the new one, after that, apply the coupon code and Check the discount value.

**Before:** :heavy_multiplication_x: Discount was showing 250 instead of 500
Screenshot 2023-08-14 at 3 57 24 PM


**After:** :heavy_check_mark:  Now showing 500
Screenshot 2023-08-14 at 4 42 20 PM



Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
Failing test are not related to PR Hence moving it to `Merge In Progress`

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Unit Tests ,WebAPI Tests

**Comment by engcom-Echo** [comment]
@magento run Integration Tests,Functional Tests B2B

**Comment by engcom-Echo** [comment]
Functional Tests B2B,Functional Tests EE Failures are different on last two run on same commit. Other build failures are not related to PR changes.
Functional Tests B2B
Run1
37730-b2b

Run2
37330-b2b2

Functional Tests EE
Run1
37730-ee


Run2
Screenshot 2023-08-18 at 2 06 02 PM

**Pull request merged**
