### PR TITLE
Fixed Multi currency, wrong value of order total in Order Customer Tab

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

Fixed Multi currency, wrong value of order total in Order Customer Tab
### Fixed Issues (if relevant)

1. magento/magento2#6890: Multi currency, wrong value of order total in Order Customer Tab

### Manual testing scenarios (*)

1. N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by ravi-chandra3197** [comment]
Hello @slavvka 
I have updated my code can review it.

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3717](https://jira.corp.magento.com/browse/ENGCOM-3717) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @ravi-chandra3197 , we cannot reproduce the issue described in the PR on 2.3-develop:
Cannot reproduce issue described by PR on 2.3-develop.
Manual testing scenario:

 - Go to Admin->Stores->Configuration->General->Currency Setup
 - In 'Allowed Currencies' in addition to the default 'dollar' select another currency (Ex: Viet Nam Dong - đ).
 - Save changes
 - Go to Admin->Stores->Currency Rates
 - Import currency rate or fill  field by yourself
 - Create orders with different currencies
 - Login to Storefront->My Account->My Orders
 Value of Order Total is correct:
image

 - Go to Admin->Sales->Orders
 Order Total is displayed correctly:
image

Are there any steps we've missed?

**Comment by sidolov** [comment]
Hi @ravi-chandra3197 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
