### PR TITLE
Nomalize PHP unit test case method calls

### PR DESCRIPTION
**Pull request by MathiasReker**
Calls to PHPUnit\Framework\TestCase static methods must all be of the same type, either $this->, self:: or static::.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @MathiasReker. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
`$this->` is preferable according to PHPUnit author, thanks for choosing this variant.

@MathiasReker could you please provide an automated way to apply such changes? I suppose `php-cs-fixer` or something was used. Also, to avoid code base inconsistency a static test similar to running `phpcs` should be implemented.

**Comment by MathiasReker** [comment]
All my PR's are made from a custom shell script I wrote. I use different libraries and a lot of custom code.

**Comment by orlangur** [comment]
@MathiasReker I see, thanks for quick response. We cannot process PRs with hundreds of changed files without an automated way to reproduce your changeset.

Also, as few custom code as possible must be used, or at least such changes should be separated from ones obtained using well-known tools. 

Here is more details on static test which needs to be implemented: https://github.com/magento/magento2/pull/19311#issuecomment-441352672 So basically we want such code issues nevermore appear in codebase.

**Comment by MathiasReker** [comment]
Try to run this with php-cs-fixer: `php ../php-cs-fixer.phar fix ./ --using-cache="no" --rules='{"php_unit_test_case_static_method_calls": {"call_type": "this"}}' --allow-risky="yes"`

**Comment by orlangur** [comment]
@MathiasReker great, yeah, I supposed something like that exists in `php-cs-fixer` :)

So let's start from static test running `php-cs-fixer`, update https://github.com/magento/magento2/blob/2.3-develop/.php_cs.dist with all useful rules and then update code base in a single PR.

**Comment by MathiasReker** [comment]
I understand your point and I agree that it is the best way to do it. I can help you, but I can't work for free to that point. I don't use Magento, I just came by and though I could do a great work by letting my computer run a script overnight. :-)

**Comment by orlangur** [comment]
@MathiasReker I see. Unfortunately applying code changes is not the only part of work, they should be also reviewed by somebody and enforced with some automated test to avoid regressions.

There were attempts before to apply `php-cs-fixer`, but without proper test they does not make a lot of sense, ref https://github.com/magento/magento2/pull/12192#issuecomment-346798553

**Comment by orlangur** [comment]
@MathiasReker I closed PRs which seemed to be produced by `php-cs-fixer` to me. Those changes may be applied in a single PR as soon as we have the test to enforce changes.

**Pull request closed without merging**
