### PR TITLE
[Backport] Curl - allow setting HTTP version

### PR DESCRIPTION
**Pull request by ghost**
### Original Pull Request 
 https://github.com/magento/magento2/pull/19845
### Description
Added allow for setting curl http version

### Fixed Issues (if relevant)
1. magento/magento2#19442: Magento/Framework/HTTP/Adapter/Curl.php doesn't allow setting HTTP version

### Manual testing scenarios (*)
1. Create new ZendClient $client
2. Set HTTP version $client->setConfig(['httpversion' => CURL_HTTP_VERSION_1_1])
3. Make a request $client->request()

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @SikailoISM. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by osrecio — DISMISSED** [review]
Thanks for your contribution @SikailoISM .

We will process your PR and we will merge soon.

**Comment by magento-engcom-team** [comment]
Hi @osrecio, thank you for the review.
[ENGCOM-4274](https://jira.corp.magento.com/browse/ENGCOM-4274) has been created to process this Pull Request

**Comment by davidalger** [comment]
This PR should not be merged as the parent PR that was previously merged into 2.3-develop was flawed and not thoroughly tested, and the change it introduced reverted in commit 55b8bf813f4. The reason is the addition of the line of code in this PR is assuming the `$http_ver` argument is expecting the value of the curl constants when it is actually expecting the value of the constants on the Zend libraries. The `$http_ver` argument has a default value of `1.1` and as we can see, this does not line up with what the curl constants that are defined as:
```
define ('CURL_HTTP_VERSION_1_0', 1);
define ('CURL_HTTP_VERSION_1_1', 2);
define ('CURL_HTTP_VERSION_2_0', 3);
```

I have submitted a PR to `2.3-develop` with a proper fix for this underlying problem. See PR #21549. I'll be submitting a back port for it shortly.

**Comment by rogyar** [comment]
Putting it on hold since the original change has been reverted (https://github.com/magento/magento2/commit/55b8bf813f4e398a6c81e0725a8c16302612f745).

We have another PR with the modified implementation that seems to be working https://github.com/magento/magento2/pull/21549

**Comment by ghost** [comment]
gg

**Pull request closed without merging**
