### PR TITLE
Improve code in catalog module using null coalescing operator

### PR DESCRIPTION
**Pull request by mage2pratik**
### Description (*)

Improve code in catalog module using null coalescing operator
### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by orlangur** [comment]
@mage2pratik this should be done automatically all over the code instead of changes in some random module. Please elaborate such approach and apply it to all modules and library components in a single commit.

**Comment by orlangur** [comment]
@mage2pratik you can use `ternary_to_null_coalescing` rule from https://github.com/FriendsOfPHP/PHP-CS-Fixer.

It only covers ternary operators, so, I suggest making first manual commit introducing necessary ternary operators and second automated applying this rule.

**Comment by orlangur** [comment]
@mage2pratik there must be only one (in case of only automatic changes) or two commits.

**Review by orlangur — CHANGES_REQUESTED** [review]
@mage2pratik please check https://github.com/orlangur/magento2/commit/4e5f549511280ac40a944ff349dfadf754350400 and try to figure out why amount of changed files differs compared to your PR.

**Comment by orlangur** [comment]
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

**Pull request closed without merging**
