### PR TITLE
ExtensionAttributesProcessor::buildOutputDataArray: Add array keys

### PR DESCRIPTION
**Pull request by SchumacherFM**
Expected would be an output array including the array keys but keys get
lost. This PR fixes the issue.
More detailed information regarding the bug in the printscreen.

screen shot 2016-07-21 at 16 46 29

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=5767) <br/>All committers have signed the CLA.

**Comment by SchumacherFM** [comment]
Yay! Ready to merge ...

**Comment by SchumacherFM** [comment]
Any date when it's getting merged?

**Comment by SchumacherFM** [comment]
Any date when it's getting merged?

**Comment by SchumacherFM** [comment]
This bug has bitten us the 2nd time ... so any date to merge it into develop that we can at least work with the dev branch of 2.1?

**Comment by SchumacherFM** [comment]
I think I should close this PR as you're not interested in it.

**Comment by SchumacherFM** [comment]
wow 6 month old!

**Comment by vrann** [comment]
@SchumacherFM I'm sorry for such a delay on this PR!

It seems like the intent of this PR is to keep the array keys of the input data of array type. However, current behavior was intentional: for any strongly typed languages there is no such concept as the array with the keys, they should rather be implemented as a HashMaps. This method is heavily used in the Web API framework for the data serialization and doing that it should be compliant with what is expected by the external services. Such problems appear mostly for the SOAP, but REST might be affected in case of autogenerated code.

**Comment by SchumacherFM** [comment]
Dear @vrann thank you for the explanation! In this case ... I should refactor my code and we can close this PR.

**Pull request closed without merging**
