### PR TITLE
 Add optionnal parameter to cache:clean and cache:flush to exclude type(s)

### LINKED ISSUE #35847: Add optionnal parameter to cache:clean and cache:flush to exclude type(s)
### Description (*)

In some occasions (deployment of a new version for instance), we may want to purge all cache except Full page cache.
This forces us to run `cache:clean` or `cache:flush` with the list of all types except `full_page`. Would be nicer to be able to exclude a type in those commands.

### Benefits

Simpler syntax, no need to change deployment code when a new type of cache is added by some extension.

### Example

At the moment we use : 
`./magento cache:flush config layout block_html collections reflection db_ddl compiled_config eav customer_notification config_integration config_integration_api config_webservice translate adyen fishpig_wordpress`

This feature request would allow to use : 
`./magento cache:flush --exclude full_page`

### PR DESCRIPTION
**Pull request by sandy6666**
Provided the feature to exclude cache type while cleaning the cache.

Description (*)
In order to facilitate the admin to clear all caches excluding a particular cache, added an input option to take from the admin and exclude it from available types using the below command.

Getting the option from the admin
       `$this->addOption(self::EXCLUDE_KEY_TYPES, '-e', InputOption::VALUE_OPTIONAL);`

Excluding from cache type
`unset($cacheTypes[array_search($input->getOption(self::EXCLUDE_KEY_TYPES), $cacheTypes)]); $cacheTypes = array_values($cacheTypes);`

Fixed Issues (if relevant)
Fixes https://github.com/magento/magento2/issues/35847
Manual testing scenarios (*)
Run the command  `bin/magento c:c --exclude config` or shorthand notation using `bin/magento c:c -e config` to exclude the cache from not being cleared.

If you want to exclude multiple cache from being cleaned use this `bin/magento c:c --exclude config --exclude layout`

### Contribution checklist (*)
 - [*] Pull request has a meaningful description of its purpose
 - [*] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sandy6666** [comment]
@edenduong please review my code

@engcom-Lima please have a look on this updates

**Comment by sandy6666** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Hello @sandy6666,

Thanks for the contribution!

Currently, we are discussing this PR internally with PO. Till the time we are moving the PR in `On Hold` status.

We will keep you updated with the progress.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run WebAPI Tests

**Review by engcom-Hotel — APPROVED** [review]
Failed tests seem flaky to me, hence approving the PR.

**Comment by engcom-Lima** [comment]
Hi @sandy6666 ,

Thanks for your contribution and collaboration.

We are closing this PR as there is no latest update on it. Please feel free to reopen it.


Thanks

**Pull request closed without merging**
