### PR TITLE
#13685 Upgrade jquery.mobile.custom.js to be compatible with jQuery 3.x

### PR DESCRIPTION
**Pull request by kirmorozov**
### Description
Upgraded jQuery mobile, created same events+ scroll using builder.
http://jquerymobile.com/download-builder/

As of documentation it drops support of IE 10 and Android 4 browser
https://blog.jquerymobile.com/2017/05/11/jquery-mobile-1-5-0-alpha-1-released/

### Fixed Issues (if relevant)

1. magento/magento2#13685: Incompatibilies with jQuery 3

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by orlangur** [comment]
Hi @kirmorozov, why you think upgrading to alpha release is a good idea?

**Comment by kirmorozov** [comment]
And alpha release is more then 9 months old, looks like permanent solution, but called "alpha".
I would not expect major changes as there are no changes in repo since release.
https://github.com/jquery/jquery-mobile/compare/1.5.0-alpha.1...master

**Comment by kirmorozov** [comment]
I would even prefer to remove jQuery Mobile at all.

**Comment by orlangur** [comment]
Removal sounds much better to me as after your previous comment I've get familiar with https://blog.jquerymobile.com/2017/12/21/the-future-of-jquery-ui-and-jquery-mobile/ and taking into account https://blog.jquerymobile.com/2016/01/28/a-long-overdue-status-update/ this library development seems kinda dead.

**Pull request merged**
