### PR TITLE
view-order-price-subtotal-alignment-not-proper-mobile

### PR DESCRIPTION
**Pull request by priti2jcommerce**
### Fixed Issues (if relevant)

1. magento/magento2#20299: Order item details label not aligned in mobile view
2. ...

### Manual testing scenarios (*)

1. Open frontend and login as customer
2. Go to my account section
3. Click on My order link and open detail any order in mobile
4. You will issue as shown in screenshot

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sdzhepa** [comment]
Hello @priti2jcommerce 


As we can see initial issue #20299  has been fixed and closed
Delivered in the scope of PR #20301 by @cedarvinda in 2.3-develop branch
Please see more details about commits in this comment https://github.com/magento/magento2/issues/20299#issuecomment-456899153


Could you confirm this PR can be closed?


Thank you for contribution and collaboration!

**Comment by sivaschenko** [comment]
@sdzhepa I see that PR https://github.com/magento/magento2/pull/20301 fixes this issue only for luma theme. @priti2jcommerce can you please update your branch (to fetch changes introduced by merged PR) and provide the fix only for the blank theme in this PR.

**Comment by priti2jcommerce** [comment]
Hi @sdzhepa and @sivaschenko ,

thanks for the update, I will make the changes

**Comment by priti2jcommerce** [comment]
Hi @sdzhepa and @sidolov ,

I update branch now and provide the fix only for the blank theme in this PR.

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-4069](https://jira.corp.magento.com/browse/ENGCOM-4069) has been created to process this Pull Request

**Pull request merged**
