### PR TITLE
Menu does not work when you change from Mobile to Desktop mode #5402

### PR DESCRIPTION
**Pull request by emanuelarcos**
### Fixed Issues (if relevant)

1. magento/magento2#5402: Menu does not work when you change from Mobile to Desktop mode
2. ...

### Manual testing scenarios

1. Create Parent category, and sub-category as part of the parent in Admin
2. Navigate to frontend.
3. Observe newly created category on desktop browser.
4. Resize browser to be mobile (width < 760px)
5. Resize browser back to be show full menu.
6. Click on any of the top level category links from the menu.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=17990) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @emanuelarcos. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-engcom-team** [comment]
@emanuelarcos thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by okorshenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [new Magento instance](https://pr-17990.engcom.dev.magento.com).
Admin access: [https://pr-17990.engcom.dev.magento.com/admin](https://pr-17990.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-2938](https://jira.corp.magento.com/browse/ENGCOM-2938) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @emanuelarcos. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
