### PR TITLE
Fix Issue - Special Price > special_from_date

### PR DESCRIPTION
**Pull request by rodrigoobiassi**
### Issues on 2.3 version to!

- https://community.magento.com/t5/Magento-2-x-Technical-Issues/Re-HELP-special-price-not-working-Urgent-issue/td-p/117714
- https://github.com/magento/magento2/commit/14ab8ace12f0e95a476675548d0712d5ecaf9a26

### Manual testing scenarios (*)

1. Add some special price
2. Change special price value more than once
3. You'll see that the Special Price is not applying
4. If you check the database, you see the 'special_from_date' wrong because $dateFilter is deprecated and is not working well

### After Change 'special_from_date' is working!
Screen Shot 2019-09-16 at 23 43 02

Screen Shot 2019-09-16 at 23 43 09

Screen Shot 2019-09-16 at 23 43 17

Screen Shot 2019-09-16 at 23 43 28

Screen Shot 2019-09-16 at 23 45 13

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24624) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=24624) before we can accept your contribution.<br/><hr/>**biassi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by p-bystritsky** [comment]
Hello, @rodrigoobiassi. Please [sign CLA](https://github.com/magento/magento2/pull/24624#issuecomment-532056052). Also, other checks should pass. If you need some help with tests, feel free to ask.

**Comment by rodrigoobiassi** [comment]
> Hello, @rodrigoobiassi. Please [sign CLA](https://github.com/magento/magento2/pull/24624#issuecomment-532056052). Also, other checks should pass. If you need some help with tests, feel free to ask.

Hi, @p-bystritsky could you help me with tests, please? CLA is okay :) Thanks

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Please avoid the use of `private` functions in controllers. It is considered a bad practice in general.

**Comment by lenaorobei** [comment]
Closing this PR due to inactivity. @rodrigoobiassi feel free to reopen if you are going to work on it. Thank you.

**Pull request closed without merging**
