### PR TITLE
Fix return type of price currency format method

### PR DESCRIPTION
**Pull request by avstudnitz**
### Description
The `format` method always returns a string. This commit adjusts the return type declaration in the doc block so developers are not misleaded.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @avstudnitz. Thank you for your contribution. Considering the fact that the implementation may include HTML container, we definitely should have `string` here.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-5798](https://jira.corp.magento.com/browse/ENGCOM-5798) has been created to process this Pull Request

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5798](https://jira.corp.magento.com/browse/ENGCOM-5798) has been created to process this Pull Request

**Comment by slavvka** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@avstudnitz @engcom-Foxtrot I can see DBC failure just now and 3 months ago. Could you please take a look if something in the solution may affect DB differences?

**Comment by slavvka** [comment]
SVC failure is under architectural review

**Comment by slavvka** [comment]
@engcom-Foxtrot please take a look at Functional EE

**Comment by slavvka** [comment]
BIC is approved (https://jira.corp.magento.com/browse/MC-20179)

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by slavvka** [comment]
@engcom-Foxtrot What was the reason of moving it to Pending approval again?

**Pull request merged**
