### PR TITLE
Magento Framework - Performance improvements

### PR DESCRIPTION
**Pull request by andrey-legayev**
### Description (*)
I've run DI Compile process with XDebug Profiler enabled to see if performance can be improved.
There are fixes which I've implemented:
 - cache parents list in Code/Reader/ClassReader.php
 - replace array_key_exists() by isset() (2nd a bit faster, but that will change in PHP 7.4)

I'm submitting it separately, because it touches no just DI compile, but Magento framework in general. Quite dangerous fixes.

These changes were already tested and successfully deployed to our production servers.

### Fixed Issues (if relevant)
None

### Manual testing scenarios (*)
None

### Questions or comments
None

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6037](https://jira.corp.magento.com/browse/ENGCOM-6037) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Comment by buskamuza** [comment]
Could you please also measure memory impact of this change?

**Comment by andrey-legayev** [comment]
I measured it on our real project by adding debug log into ClassReader on dev machine.

Values for Shopping Cart page: 
- warm cache:
    - array count: 79
    - parents cache hits: 24
    - json export size: 9015 bytes
- after cache flush:
    - array count: 302
    - parents cache hits: 696
    - json export size: 37671 bytes


Debug code which I used for logging memory consumption:
```php
$message = "count=" . count($this->parentsCache) . "\t" .
    "size=" . strlen(json_encode($this->parentsCache)) . "\t".
    $_SERVER["REQUEST_URI"]."\n";

file_put_contents("parents_cache.log", $message, FILE_APPEND);
```

Spec:
 - PHP 7.2.23
 - Magento 2.3.2 + a lot of our and 3rd party modules

**Pull request merged**
