### PR TITLE
Allow to load base64 encoded images and fonts

### LINKED ISSUE #31170: [Issue] Allow to load base64 encoded images and fonts
This issue is automatically created based on existing pull request: magento/magento2#31162: Allow to load base64 encoded images and fonts

---------
### Description
Magento 2.4-develop

Current Content Security Policy setup doesn't allow to load images and fonts via `data:` scheme which is quite a popular method to load local resources (base64 encoded images). Additionally, it's used internally by the browser cache (Chrome) when you refresh the page.

### Manual testing scenarios (*)
1. Add Base64 image or font to Home page 
2. Open Luma homepage and open browser console.
3. Refresh the page to trigger resource loading from the browser cache.
4. Inspect errors in the console:
  Font errors in console
5. Apply the patch, and try again. No errors should appear in the log.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by vovayatsyuk**
### Description
Current Content Security Policy setup doesn't allow to load images and fonts via `data:` scheme which is quite a popular method to load local resources (base64 encoded images). Additionally, it's used internally by the browser cache (Chrome) when you refresh the page.

### Manual testing scenarios (*)
1. Open Luma homepage and open browser console.
2. Refresh the page to trigger resource loading from the browser cache.
3. Inspect errors in the console:
  Font errors in console
4. Apply the patch, and try again. No errors should appear in the log.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31170: Allow to load base64 encoded images and fonts

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Review by aleron75 — CHANGES_REQUESTED** [review]
Hi @vovayatsyuk thanks for your contribution.

Can you please take a look at the failing `\Magento\Csp\Model\Collector\ConfigCollectorTest` and fix it?

Thank you

**Comment by vovayatsyuk** [comment]
Done.

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Integration Tests

**Comment by engcom-Charlie** [comment]
@magento run Integration Tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8577](https://jira.corp.magento.com/browse/ENGCOM-8577) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Add Base64 encoded image to home page;
2. Open Luma homepage and open browser console.
3. Refresh the page to trigger resource loading from the browser cache.
4. Inspect errors in the console:

**Before:** :heavy_multiplication_x: Refuse to load the image...
Screenshot from 2020-12-24 10-14-08

**After:** :heavy_check_mark: Image and font uploaded successfully without any errors

Screenshot from 2020-12-24 10-22-06

**Pull request merged**
