### PR TITLE
Show customer_grid indexer as green when realtime

### LINKED ISSUE #34648: [Issue] Show customer_grid indexer as green when realtime
This issue is automatically created based on existing pull request: magento/magento2#34557: Show customer_grid indexer as green when realtime

---------
### Description
Magento recommends that all indexers be set in `schedule` mode ("Update by Schedule") except for `customer_grid` which should be in `realtime` mode ("Update on Save"). This is documented here in [the devdocs](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/indexing.html#m2devgde-indexing-modes) and the Site-Wide Analysis Tool reports this also.

<details><summary>Screen-shot of Site-Wide Analysis Tool</summary><hr />

Screenshot_2021-11-06_21-37-48

<hr /></details>

Currently Magento renders all indexers as 'green' when they are in `schedule` mode, including `customer_grid`. This is misleading as the `customer_grid` is not in the recommended state when set as `schedule` and shows in 'red' when in `realtime` mode which is its recommended state.

This pull request makes the colours match the recommended state for each indexer.

### Related Pull Requests

*None*

### Fixed Issues
*None*

### Manual testing scenarios
1. Set all indexers as `realtime` with: `php bin/magento indexer:set-mode realtime`
1. Observe colours for each indexer in admin (System -> Tools -> Index Management)
1. Set all indexers as `schedule` with: `php bin/magento indexer:set-mode schedule`
1. Observe colours for each indexer in admin (System -> Tools -> Index Management)
1. Set the `customer_grid` indexer as `realtime` with: `php bin/magento indexer:set-mode realtime customer_grid`
1. Observe colours for each indexer in admin (System -> Tools -> Index Management)

<details><summary>Screen-shot of indexers all set 'Update on Save'</summary>

Screenshot_2021-11-06_21-48-58

</details>
<details><summary>Screen-shot of indexers all set 'Update by Schedule'</summary>

Screenshot_2021-11-06_21-50-32

</details>
<details><summary>Screen-shot of indexers set to their recommended modes</summary>

Screenshot_2021-11-06_21-45-49

</details>

### Questions or comments
I have made the function which determines the preferred mode public to allow for extensibility with plugins.

Should the Design Config Grid indexer also be in this category of 'prefer realtime mode'?

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fredden**
### Description
Magento recommends that all indexers be set in `schedule` mode ("Update by Schedule") except for `customer_grid` which should be in `realtime` mode ("Update on Save"). This is documented here in [the devdocs](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/indexing.html#m2devgde-indexing-modes) and the Site-Wide Analysis Tool reports this also.

<details><summary>Screen-shot of Site-Wide Analysis Tool</summary><hr />

Screenshot_2021-11-06_21-37-48

<hr /></details>

Currently Magento renders all indexers as 'green' when they are in `schedule` mode, including `customer_grid`. This is misleading as the `customer_grid` is not in the recommended state when set as `schedule` and shows in 'red' when in `realtime` mode which is its recommended state.

This pull request makes the colours match the recommended state for each indexer.

### Related Pull Requests

*None*

### Fixed Issues
*None*

### Manual testing scenarios
1. Set all indexers as `realtime` with: `php bin/magento indexer:set-mode realtime`
1. Observe colours for each indexer in admin (System -> Tools -> Index Management)
1. Set all indexers as `schedule` with: `php bin/magento indexer:set-mode schedule`
1. Observe colours for each indexer in admin (System -> Tools -> Index Management)
1. Set the `customer_grid` indexer as `realtime` with: `php bin/magento indexer:set-mode realtime customer_grid`
1. Observe colours for each indexer in admin (System -> Tools -> Index Management)

<details><summary>Screen-shot of indexers all set 'Update on Save'</summary>

Screenshot_2021-11-06_21-48-58

</details>
<details><summary>Screen-shot of indexers all set 'Update by Schedule'</summary>

Screenshot_2021-11-06_21-50-32

</details>
<details><summary>Screen-shot of indexers set to their recommended modes</summary>

Screenshot_2021-11-06_21-45-49

</details>

### Questions or comments
I have made the function which determines the preferred mode public to allow for extensibility with plugins.

Should the Design Config Grid indexer also be in this category of 'prefer realtime mode'?

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#34648: Show customer_grid indexer as green when realtime

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento give me 2.4-develop instance

**Comment by hostep** [comment]
Can somebody please verify if the claim is actually correct? We have always had that indexer set to 'update by schedule' and I haven't heard any complaints about our clients that this customer grid is not being updated correctly...

**Comment by fredden** [comment]
> Can somebody please verify if the claim is actually correct?

Yes, please; I'd like confirmation too. I've not witnessed any real-world issues with this (in current versions of Magento) nor the Design Config Grid indexer, but both seem to use the 'dummy' materialised-view, so will never get anything in their (non-existent) changelog tables and therefore won't run an 'incremental' indexer update. I wonder why the Design Config Grid isn't marked as recommended in realtime mode too. This feels inconsistent.

<details><summary>Code samples showing 'dummy' mview</summary>

https://github.com/magento/magento2/blob/227cf9229152ed4332c607796cf476055ef9ec4f/app/code/Magento/Customer/etc/indexer.xml#L10

https://github.com/magento/magento2/blob/227cf9229152ed4332c607796cf476055ef9ec4f/app/code/Magento/Customer/etc/mview.xml#L9

https://github.com/magento/magento2/blob/227cf9229152ed4332c607796cf476055ef9ec4f/app/code/Magento/Theme/etc/indexer.xml#L10

https://github.com/magento/magento2/blob/227cf9229152ed4332c607796cf476055ef9ec4f/app/code/Magento/Theme/etc/mview.xml#L9

https://github.com/magento/magento2/blob/227cf9229152ed4332c607796cf476055ef9ec4f/lib/internal/Magento/Framework/Indexer/Action/Dummy.php#L11-L54

</details>

**Comment by fredden** [comment]
It looks like the customer grid indexer gets incremental updates inline within the same process that's doing the 'save' action. 

https://github.com/magento/magento2/blob/227cf9229152ed4332c607796cf476055ef9ec4f/app/code/Magento/Customer/Model/Customer.php#L1096-L1123

https://github.com/magento/magento2/blob/227cf9229152ed4332c607796cf476055ef9ec4f/app/code/Magento/Customer/Model/Address.php#L333-L363

https://github.com/magento/magento2/blob/227cf9229152ed4332c607796cf476055ef9ec4f/app/code/Magento/Customer/Model/Plugin/CustomerGridIndexAfterWebsiteDelete.php#L49-L60

And the Design Config Grid indexer does a full reindex every time something gets saved.

https://github.com/magento/magento2/blob/227cf9229152ed4332c607796cf476055ef9ec4f/app/code/Magento/Theme/Model/DesignConfigRepository.php#L84-L131

So the indexer mode ('realtime' versus 'schedule') shouldn't make any difference to the freshness of the data showing in the grid. Should we therefore mark the mode as neutral whatever it is, rather than preferring one state over the other?

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Unit Tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests, Unit Tests,Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Unit Tests,WebAPI Tests

**Comment by engcom-Echo** [comment]
@magento run Unit Tests,WebAPI Tests

**Comment by engcom-Echo** [comment]
Failing Test does not seems to be related to PR.
Hence moving it to `Merge In Progress`

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Unit Tests,Static Tests, Functional Tests B2B

**Comment by engcom-Echo** [comment]
Functional Tests B2B are different on last two run on same commit. Other failure are not related to PR.
Functional Tests B2B 
Run1
34557-b2b

Run2
Screenshot 2023-08-18 at 12 26 46 PM

**Pull request merged**
