### PR TITLE
Fixed #22484 Customer address States are duplicated in backend

### LINKED ISSUE #22484: Customer address States are duplicated in backend
### Preconditions (*)
Magento 2.3.1 

### Steps to reproduce (*)

1. Install fresh magento 2.3.1
2. create a customer 
3. go to backend and click new address 
4. select any country United States or Australia

### Expected result (*)

1. State province are not duplicated
### Actual result (*)

1. All the sates are duplicated with the same ID
image

### PR DESCRIPTION
**Pull request by shikhamis11**
Fixed #22484 Customer address States are duplicated in backend

### Preconditions (*)
Magento 2.3.1 

### Steps to reproduce (*)

1. Install fresh magento 2.3.1
2. create a customer 
3. go to backend and click new address 
4. select any country United States or Australia

### Expected result (*)

1. State province are not duplicated
### Actual result (*)

1. All the sates are duplicated with the same ID
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by shikhamis11** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, here is your [new Magento instance](https://pr-22637.instances.magento-community.engineering).
Admin access: [https://pr-22637.instances.magento-community.engineering/admin](https://pr-22637.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by ronak2ram — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ronak2ram, thank you for the review.
[ENGCOM-5048](https://jira.corp.magento.com/browse/ENGCOM-5048) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Comment by sivaschenko** [comment]
@magento run all tests

**Pull request merged**
