### PR TITLE
Fixed wrong customer group assign to order 26976

### PR DESCRIPTION
**Pull request by ProkopovVitaliy**
### Fixed Issues (if relevant)

1. magento/magento2#26976: Issue title: Wrong Customer Group assign to order

### Manual testing scenarios (*)

1. In admin configuration Enable Automatic Assignment to Customer Group set yes
2. login with different Customer Group then Default Group set in admin.
3. Place order

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by swnsma — CHANGES_REQUESTED** [review]
Hi @ProkopovVitaliy,

Could you check failed tests?
It seems that these tests related to changes introduced by your PR.

**Comment by engcom-Kilo** [comment]
Working with MFTF test

**Comment by engcom-Kilo** [comment]
@ProkopovVitaliy Please resolve branch conflicts.
Thanks

**Comment by engcom-Kilo** [comment]
@ProkopovVitaliy 
Please grant permission to write for GIT branch ProkopovVitaliy:fix-26976

Thanks

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
Added MFTF test

**Comment by ProkopovVitaliy** [comment]
@magento run all tests

**Comment by ProkopovVitaliy** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by swnsma** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Review by lenaorobei — APPROVED** [review]

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-8039](https://jira.corp.magento.com/browse/ENGCOM-8039) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by lenaorobei** [comment]
@engcom-Kilo, could you please check failed tests.

**Comment by engcom-Kilo** [comment]
@lenaorobei 
Seems OK with tests.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. In admin configuration Enable Automatic Assignment to Customer Group (Go to Admin -> Stores -> Configuration -> Customers -> Customer Configuration -> Create New Account Options and set Enable Automatic Assignment to Customer Group to Yes);
2. Login with different Customer Group then Default Group set in admin (**test** group for example);
3. Place order;

**Before:**  :heavy_multiplication_x: order displays customer group which set as default group in admin configuration



**After:** :heavy_check_mark: order displays correct customer group

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Pull request merged**
