### PR TITLE
Issue Fixed: #16806 Duplicate argument overwrites option language DeployStaticContentCommand 

### PR DESCRIPTION
**Pull request by milindsingh**
### Description (*)

Duplicate argument overwrites option language DeployStaticContentCommand
+ Preconditions
    - Magento 2.3-alpha
    - Not installed: no env.php present, no database available, build environment `(Not Important as same issue occurs after installation too.)`
+ Static content was deployed for default `en_US` even if language parameters are provided.

### Fixed Issues (if relevant)

1. magento/magento2#16806: Duplicate argument overwrites option language DeployStaticContentCommand

### Manual testing scenarios (*)

1. run `bin/magento setup:static-content:deploy -t Magento/blank -l nl_NL -f` and static content is deployed only for `nl_NL`.
2. run `bin/magento setup:static-content:deploy nl_NL`
3. run `bin/magento setup:static-content:deploy`
4. run `bin/magento deploy:mode:set production`

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3754](https://jira.corp.magento.com/browse/ENGCOM-3754) has been created to process this Pull Request

**Comment by VladimirZaets** [comment]
Hi @milindsingh. Thanks for collaboration. 

Your fix provides the next problem:

The command `bin/magento deploy:mode:set production` additionaly deploys static content for locale `all`.

**Comment by milindsingh** [comment]
@VladimirZaets I have updated and rechecked for all cases. Thanks

**Comment by VladimirZaets** [comment]
Hi @milindsingh. Thanks for collaboration.
PR code changes bring next problem - command `bin/magento deploy:mode:set production` additionaly deploys static content for locale `all`.

**Comment by sidolov** [comment]
@milindsingh , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
