### PR TITLE
[MFTF] Added new ActionGroup  for clicking AddToCart button 

### LINKED ISSUE #29823: [Issue] [MFTF] Added new ActionGroup  for clicking AddToCart button
This issue is automatically created based on existing pull request: magento/magento2#29820: [MFTF] Added new ActionGroup  for clicking AddToCart button 

---------
Added `StorefrontClickAddToCartButtonActionGroup` for click AddToCart button

### PR DESCRIPTION
**Pull request by Usik2203**
Added `StorefrontClickAddToCartButtonActionGroup` for click AddToCart button 

### Resolved issues:
1. [x] resolves magento/magento2#29823: [MFTF] Added new ActionGroup  for clicking AddToCart button

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Review by lbajsarowicz — APPROVED** [review]
image

✔️ Thank you for your contribution.

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Comment by Usik2203** [comment]
Hi @engcom-Echo 
I see  that Functional Tests B2B test  is failed in others my  PRs for example this one https://github.com/magento/magento2/pull/29833
Could I kindly ask you help me with reason of failed test ? 
Thanks!

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8113](https://jira.corp.magento.com/browse/ENGCOM-8113) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Pull request merged**
