### PR TITLE
Forword Port : Fixed-19379-Tax Rate Checkbox alignment issue #19383

### PR DESCRIPTION
**Pull request by suryakant-krish**
### Fixed Issues (if relevant)

1. magento/magento2#19379: Tax Rate Checkbox alignment issue

### Manual testing scenarios (*)

1. Login into admin panel > Stores > Tax Rules > Click on Add New Tax Rule > Click on Add New Tax Rate
2. Alignment Issue "Zip/Post is Range" Checkbox.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
2.2 PR https://github.com/magento/magento2/pull/19383

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](https://i-19413-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19413-2-3-develop.instances.magento-community.engineering/admin](https://i-19413-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-19413.instances.magento-community.engineering).
Admin access: [https://pr-19413.instances.magento-community.engineering/admin](https://pr-19413.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
