### PR TITLE
Fix for making subcategories appear in breadcrumbs (Backport)

### LINKED ISSUE #7967: Problems with breadcrumbs
### Preconditions
I have some problems with breadcrumbs .
Im using 
1. Magento ver. 2.1.1
2. PHP Version 7.1.0

### Steps to reproduce
1. Open Product from list page
  List page - http://prnt.sc/doeoxy

### Expected result
1. details page should contain breadcrumbs in this  format **Home -> Category name ->Product Name**

   **Home >  Proteasome Inhibitors  > MG-132**

### Actual result
1. **Home >  MG-132** -  Category missing
  Detail page - http://prnt.sc/doeqa2

Is it possible to get  full breadcrumb  with Magento 2 ?

### PR DESCRIPTION
**Pull request by Yamaha32088**
### Description (*)
The typo will break sub categories from appearing in the breadcrumbs

### Fixed Issues (if relevant)

1. magento/magento2#7967: Problems with breadcrumbs

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

Backport for: https://github.com/magento/magento2/pull/19781

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19760) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @Yamaha32088. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
Hi @Yamaha32088. Thank you for your contribution. According to the contributor guide (https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#rules) we cannot accept a change into 2.2-develop branch before the change is merged into 2.3-develop branch. Please, consider creating the same fix for 2.3-develop and rename the current pull request as backport. Thank you.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3697](https://jira.corp.magento.com/browse/ENGCOM-3697) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@Yamaha32088 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3697](https://jira.corp.magento.com/browse/ENGCOM-3697) has been created to process this Pull Request

**Comment by liquidia** [comment]
this still not fixed in 2.3.3 ?

**Comment by anil90** [comment]
i am also facing this issue with 2.3.2

**Comment by nicholasscottfish** [comment]
Any update on this issue? Still experiencing the missing breadcrumbs on 2.4.3-p1 :(

**Pull request merged**
