### PR TITLE
MAGETWO-70996 preselect default billing address if it exists in custo…

### PR DESCRIPTION
**Pull request by astyczen**
Pre-select default billing address if it is specified in customer address book.

### Description
Customer specifies a default billing address in their account page. During checking out the default billing address is pre-selected in the payment step and 'Billing same as shipping' checkbox is unchecked in such situation.
When default billing and shipping addresses are the same the checkbox is checked properly.
For not logged in users the default behaviour is to have the checkbox checked for billing same as shipping as most of the clients use the same address for both.

### Fixed Issues
1. magento/magento2#8777: Issue title Customer Address "default billing address" Attribute Not Used in Checkout 

### Manual testing scenarios
1. Logged in user with two different default addresses:
-- Create a user account on the frontend.
-- Go to Address Book and specify that an address is your default billing address.
-- Add second address and specify it as a default shipping address.
-- Checkout with a shippable item when logged in.
-- Leave preselected shipping address and select shipping method.
-- Go to payment step.
-- See that default billing address is displayed and same as shipping checkbox is unchecked. 
-- Place order to check if billing was set correctly.
2. Logged in user with same default address for billing and shipping:
-- Create a user account on the frontend.
-- Go to Address Book and specify that an address is your default billing and shipping address.
-- Checkout with a shippable item when logged in.
-- Leave preselected shipping address and select shipping method.
-- Go to payment step.
-- See that same address is displayed and checkbox is checked. 
-- Place order to check if billing was set correctly.
3. New user with without default address:
-- Checkout with a shippable item when not logged in.
-- Enter shipping address and customer details.
-- Go to payment step.
-- See that same address is displayed and checkbox is checked. 
-- Place order to check if billing was set correctly.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14310) <br/>All committers have signed the CLA.

**Review by miguelbalparda — CHANGES_REQUESTED** [review]
@astyczen can you please take a look at the failing tests?

**Comment by miguelbalparda** [comment]
Hi @astyczen! Were you able to check this?

**Comment by miguelbalparda** [comment]
Closing for lack of feedback, feel free to reopen if you have some time to work on this @astyczen.

**Pull request closed without merging**
