### PR TITLE
Added translation comment tags

### PR DESCRIPTION
**Pull request by yogeshsuhagiya**
### Description
Added translation for comment tags.
Removed unnecessary spaces from `<item>` tag

### Fixed Issues (if relevant)

1. N/A

### Manual testing scenarios

1. N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Yogeshks. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by sidolov** [comment]
@magento-engcom-team combine 17525 17521

**Comment by magento-engcom-team** [comment]
Hi @sidolov. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
We got some errors while combining pull requests:
 - https://github.com/magento/magento2/pull/17525 : Base branch must be the same for target and source pull request
 - https://github.com/magento/magento2/pull/17521 : Base branch must be the same for target and source pull request

**Comment by magento-engcom-team** [comment]
Hi @Yogeshks. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Pull request merged**
