### PR TITLE
FIX #27117 Invalid functional Test names

### LINKED ISSUE #27117: MFTF: Test names are not following Best Practices (`Test` suffix)
### Preconditions (*)
Test names should follow `{Area}` + `{What test does}` + `Test` pattern.
There are tests in Magento 2 that does not follow that pattern.

### Steps to reproduce (*)
N/A

### Expected result (*)
N/A

### Actual result (*)
N/A

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Fix the Test names, rename wrong files.
As a side effect, more tests can be run than previously.

### Related Pull Requests
* https://github.com/magento/partners-magento2b2b/pull/54
* https://github.com/magento/partners-magento2ee/pull/151

### Other Related
* https://github.com/magento/magento2-page-builder/pull/399
* https://github.com/magento/magento2-page-builder-ee/pull/114

### To be done later
* https://github.com/magento/inventory/pull/2857

### Fixed Issues (if relevant)
1. magento/magento2#27117

### Manual testing scenarios (*)
N/A

### Questions or comments
This change might cause hundreds of failures as previously ignored will be run now.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests
To run them for EE + B2B + Inventory + PageBuilder

**Comment by lbajsarowicz** [comment]
Tests are not being generated as `Inventory` had tests that were previously ignored by the runner.
Renaming them to correct pattern caused running them on CI.
As a result - tests that were not run - are not causing the issues with `stepKey` references.

**Comment by lbajsarowicz** [comment]
@magento run all tests

I disconnected Inventory, as it requires more work.

**Comment by lbajsarowicz** [comment]
@magento run all tests
Thanks @okolesnyk for help with finding this `TextTest` :man_facepalming:

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7040](https://jira.corp.magento.com/browse/ENGCOM-7040) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by lbajsarowicz** [comment]
@magento run all tests

Resolved conflicts to PB: https://github.com/magento/magento2-page-builder/pull/399

**Comment by lbajsarowicz** [comment]
@magento run all tests

Merged latest `-develop` branches to all related PRs

**Comment by lbajsarowicz** [comment]
@magento run all tests

Still getting false negatives.

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests
There was missing reference to PageBuilder EE

**Pull request merged**
