### PR TITLE
Allow ID and data-* tags in TinyMCE

### PR DESCRIPTION
**Pull request by PieterCappelle**
Allow ID-tag and data-* tag in HTML. 

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/10353

### Manual testing scenarios
1. CMS Pages / Blocks
2. Add image
3. Edit HTML
4. Add id-tag or data-*="tag"
5. Error will throw up

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by osrecio** [comment]
Same issue solved in this PR #11025 

I will test your solution ASAP.

**Comment by orlangur** [comment]
Why do you need ID attribute? It is forbidden for virtually any purpose, see http://devdocs.magento.com/guides/v2.2/coding-standards/code-standard-demarcation.html for details.

**Comment by PieterCappelle** [comment]
Why should ID be forbidden? If I want specifiek markup for one element.

**Comment by orlangur** [comment]
Because unique element today may become nonunique tomorrow. For example, `#login` on some pages occur more than once. Anyway, such discussion is out of scope for this PR, there is a standard which must be followed.

Please recreate branch from `2.2-develop` so that it contains only one commit with `data-*` only and force push it to the same branch.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=11053) <br/>All committers have signed the CLA.

**Comment by PieterCappelle** [comment]
@orlangur Done.

**Comment by orlangur** [comment]
@PieterCappelle during testing we found out that even if we do not allow ID explicitly multiple scenarios exist where merchant is still able to add ID to an element. So, while it would be good to enforce demarcation standard, it is not that easy, we would have to change some TinyMCE internals.

Please force push current branch without last commit so that both `id` and `data-*` attributes are allowed (just like you did the fix initially).

**Comment by PieterCappelle** [comment]
@orlangur No problem, changed the code.

**Comment by orlangur** [comment]
Ah, ok, could do a revert on our side, just wanted a cleaner history :) Thanks for understanding 👍

**Comment by PieterCappelle** [comment]
Should be okay, sorry for delay. :)

**Review by orlangur — APPROVED** [review]

**Comment by orlangur** [comment]
Ping @osrecio https://github.com/magento/magento2/pull/11053#issuecomment-332178964 did this fix work for you after all? Last time there was a report from QA engineer that initial issue appears in some cases, didn't try it in action by myself yet.

**Comment by osrecio** [comment]
I don't try to myself yet, I will test this afternoon. I will test with `2.2-develop` branch

**Comment by osrecio** [comment]
@orlangur don't works for me with `id`. 

If I put: `` get the pop-up error with this error: 
```
error: error in [unknown object].fireEvent(): event name: tinymceSaveContent error message: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
```
If I put: `` works fine.

**Comment by orlangur** [comment]
@osrecio thanks for checking!

@PieterCappelle could you please check the ID case?

**Comment by orlangur** [comment]
@PieterCappelle could you please check if this PR actually fixes mentioned issue? I didn't have a chance to check by myself yet but there are two independent persons which still observed "Failed to execute atob on Window".

**Comment by orlangur** [comment]
Closing for now as it seems like this change didn't fix initial issue completely, https://github.com/magento/magento2/pull/11025 is another attempt of fix.

Thanks @PieterCappelle for your endeavour!

**Pull request closed without merging**
