### PR TITLE
Fix price indexer for Configurable product with out of stock children

### LINKED ISSUE #27341: Category Price filter does not work for configurables with out of stock childs, when ShowOutOfStock Option is enabled
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Create an configurable product with two child products with a price of 100$ resp. 200$ and add the configurable to a category
Screenshot from 2020-08-06 19-27-11

2. Set the cheaper child product in the advanced inventory to manage stock -> true, but to be not in stock and save the product

3. Go to Admin->Stores->Configuration->Catalog->Inventory and Set Display Out of Stock Products to YES
4. Set the cheaper child product in the advanced inventory to manage_stock -> false (this does not change the value of is_in_stock in the database. This remains 0)

Screenshot from 2020-08-06 19-59-15
5. Go to the category and see, that the price for your configurable is displayed as starting from 100 $, as out of stock products shall be displayed according to your settings.
6. Try to filter for a range which includes 100$

### Expected result (*)

1. I would assume to see the configurable in the product collection

### Actual result (*)

1. I do not see the configurable in the product collection

Peek 2020-08-06 19-49

### PR DESCRIPTION
**Pull request by norgeindian**
### Description (*)
If a child product is out of stock, but out of stock products shall be shown, this check removes the child from the price indexer.
This way the min_price of the configurable is calculated as 0 if it has only childs, which are out of stock, even if they shall be shown.
So the price filter will not work correctly in this case.
That is why the check should be the other way round. The filter should only be applied, if out of stock products shall NOT be shown and so also not be used for the price calculation of the configurable.
See https://github.com/magento/magento2/commit/72f2b8a22d1cae2f023559e51a2fb88080c48a98#r33460279

### Fixed Issues (if relevant)

1. Fixes magento/magento2#27341 : Category Price filter does not work for configurables with out of stock childs, when ShowOutOfStock Option is enabled

### Manual testing scenarios (*)
1. Create an configurable product with two child products with a price of 100$ resp. 200$ and add the configurable to a category
2. Set the cheaper child product in the advanced inventory to manage stock -> true, but to be not in stock and save the product
3. Set cataloginventory/options/show_out_of_stock to YES
4. Set the cheaper child product in the advanced inventory to manage_stock -> false (this does not change the value of is_in_stock in the database. This remains 0)
5. Go to the category and see, that the price for your configurable is displayed as starting from 100 $, as out of stock products shall be displayed according to your settings.
6. Try to filter for a range which includes 100$
7. You would assume to see the configurable in the filtered collection, but you don't.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @norgeindian,
In general your changes looks good to me. Could you review the failed integration & web api tests? Please also cover your change with some kind of automated tests (maybe fixing integration /web api tests will be enough in this case)

**Comment by engcom-Charlie** [comment]
Hi @norgeindian, Could you review the failed Integration & WebAPI tests? Otherwise, we can't proceed with your PR.
Thank you.

**Comment by ihor-sviziev** [comment]
Hi @norgeindian,
Will you be able to update your PR with requested changes?

**Comment by sidolov** [comment]
@norgeindian  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
