### PR TITLE
Fix/styles priority media mobile mixin for extend file

### LINKED ISSUE #38136: [Issue] Fix/styles priority media mobile mixin for extend file
This issue is automatically created based on existing pull request: magento/magento2#38129: Fix/styles priority media mobile mixin for extend file

---------
### Description (*)
In the first implementation of the styles architecture in Magento 2, there were imported 3 files general files:

- `_module.less`
- `_widgets.less` (doesn't matter in this case)
- `_extend.less`

and only after them, the `_responsive.less` file has been imported:
- https://github.com/magento/magento2/blob/1cd6c174ab13ee0616ccff9bae502c16f670e14c/app/design/frontend/Magento/blank/web/css/styles-m.less
- https://github.com/magento/magento2/blob/1cd6c174ab13ee0616ccff9bae502c16f670e14c/app/design/frontend/Magento/blank/web/css/styles-l.less

but it was changed in the commit https://github.com/magento/magento2/commit/605b0212bd49f04895a769de128c05b6d10c54cf:
- https://github.com/magento/magento2/blob/605b0212bd49f04895a769de128c05b6d10c54cf/app/design/frontend/Magento/blank/web/css/styles-m.less#L45
- https://github.com/magento/magento2/blob/605b0212bd49f04895a769de128c05b6d10c54cf/app/design/frontend/Magento/blank/web/css/styles-l.less#L45

The `_extend.less` file has been moved to the end of both files. It looks like a minor change and probably it wasn't checked well, but for many years the media mobile styles inside the `max` mixin are broken for all the `_extend.less` files.

Let me show you 2 examples.

#### _module.less

```less
& when (@media-common = true) {
    body {
        &::before {
            content: '_module.less common';
        }
    }
}

.media-width(@extremum, @break) when (@extremum = 'max') and (@break = @screen__m) {
    body {
        &::before {
            content: '_module.less mobile mixin';
        }
    }
}

```

In this style structure we're expecting the next priority (from less to higher):
1. common styles
2. media query mixin

And we really have the expected result:
image

#### _extend.less

But let's try to do that with the `_extend.less` file. Just rename the file from `_module.less` to `_extend.less`. Add minor changes to the content:

```less
& when (@media-common = true) {
    body {
        &::before {
            content: '_extend.less common';
        }
    }
}

.media-width(@extremum, @break) when (@extremum = 'max') and (@break = @screen__m) {
    body {
        &::before {
            content: '_extend.less mobile mixin';
        }
    }
}
```

And re-compile styles again. Check the result:
image

As you can see, the priority has changed just by the renaming. 

The reason is the wrong order of the imported files in `styles-m.less` and `styles-l.less` files. The `_responsive.less` files and variables have to be always imported at the end of the files, especially after the `_extend.less` files.

So, my PR has to repair the expected logic, that media queries have to always have the higher priority, 'cause they're written after the common styles.

### Manual testing scenarios (*)
1. Choose the main branch.
2. Create a new theme.
3. Apply the theme in the admin panel.
4. Create a new styles file in the theme:
```
app/design/frontend/Vendor/theme/web/css/source/_module.less
```
5. Add the content from the description above for the `_module.less` file.
6. To make the result more clear, try to use the `empty` layout for the home page. Or just create a new file: 
```
app/design/frontend/Vendor/theme/Magento_Theme/layout/default.xml
```
With the content:
```xml
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd"
>
    <update handle="empty"/>
</page>

```
7. Clear all the static files and cache or just run the Grunt LESS compilation.
8. Check the result on the storefront. You have to see the same as in my first screenshot above.
9. Then rename the file from `_module.less` to `_extend.less` with the same content. Just rename the file name output inside.
10. Re-compile styles again.
11. Check the result.
12. Common styles have a higher priority then styles from the mobile query mixin.
13. Apply changes from the current PR.
15. Re-compile styles.
16. Check again, issue has to be fixed.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by serhii-chernenko**
### Description (*)
In the first implementation of the styles architecture in Magento 2, there were imported 3 files general files:

- `_module.less`
- `_widgets.less` (doesn't matter in this case)
- `_extend.less`

and only after them, the `_responsive.less` file has been imported:
- https://github.com/magento/magento2/blob/1cd6c174ab13ee0616ccff9bae502c16f670e14c/app/design/frontend/Magento/blank/web/css/styles-m.less
- https://github.com/magento/magento2/blob/1cd6c174ab13ee0616ccff9bae502c16f670e14c/app/design/frontend/Magento/blank/web/css/styles-l.less

but it was changed in the commit https://github.com/magento/magento2/commit/605b0212bd49f04895a769de128c05b6d10c54cf:
- https://github.com/magento/magento2/blob/605b0212bd49f04895a769de128c05b6d10c54cf/app/design/frontend/Magento/blank/web/css/styles-m.less#L45
- https://github.com/magento/magento2/blob/605b0212bd49f04895a769de128c05b6d10c54cf/app/design/frontend/Magento/blank/web/css/styles-l.less#L45

The `_extend.less` file has been moved to the end of both files. It looks like a minor change and probably it wasn't checked well, but for many years the media mobile styles inside the `max` mixin are broken for all the `_extend.less` files.

Let me show you 2 examples.

#### _module.less

```less
& when (@media-common = true) {
    body {
        &::before {
            content: '_module.less common';
        }
    }
}

.media-width(@extremum, @break) when (@extremum = 'max') and (@break = @screen__m) {
    body {
        &::before {
            content: '_module.less mobile mixin';
        }
    }
}

```

In this style structure we're expecting the next priority (from less to higher):
1. common styles
2. media query mixin

And we really have the expected result:
image

#### _extend.less

But let's try to do that with the `_extend.less` file. Just rename the file from `_module.less` to `_extend.less`. Add minor changes to the content:

```less
& when (@media-common = true) {
    body {
        &::before {
            content: '_extend.less common';
        }
    }
}

.media-width(@extremum, @break) when (@extremum = 'max') and (@break = @screen__m) {
    body {
        &::before {
            content: '_extend.less mobile mixin';
        }
    }
}
```

And re-compile styles again. Check the result:
image

As you can see, the priority has changed just by the renaming. 

The reason is the wrong order of the imported files in `styles-m.less` and `styles-l.less` files. The `_responsive.less` files and variables have to be always imported at the end of the files, especially after the `_extend.less` files.

So, my PR has to repair the expected logic, that media queries have to always have the higher priority, 'cause they're written after the common styles.

### Manual testing scenarios (*)
1. Choose the main branch.
2. Create a new theme.
3. Apply the theme in the admin panel.
4. Create a new styles file in the theme:
```
app/design/frontend/Vendor/theme/web/css/source/_module.less
```
5. Add the content from the description above for the `_module.less` file.
6. To make the result more clear, try to use the `empty` layout for the home page. Or just create a new file: 
```
app/design/frontend/Vendor/theme/Magento_Theme/layout/default.xml
```
With the content:
```xml
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd"
>
    <update handle="empty"/>
</page>

```
7. Clear all the static files and cache or just run the Grunt LESS compilation.
8. Check the result on the storefront. You have to see the same as in my first screenshot above.
9. Then rename the file from `_module.less` to `_extend.less` with the same content. Just rename the file name output inside.
10. Re-compile styles again.
11. Check the result.
12. Common styles have a higher priority then styles from the mobile query mixin.
13. Apply changes from the current PR.
15. Re-compile styles.
16. Check again, issue has to be fixed.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38136: Fix/styles priority media mobile mixin for extend file

### CODE REVIEW

**Comment by serhii-chernenko** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
@magento create issue

**Review by ihor-sviziev — APPROVED** [review]
Great job! Approved!
Note: failing tests look not related

**Comment by engcom-Hotel** [comment]
@magento run all test

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
Set up Magento and choose the main branch.

**Manual testing scenario:**

1. Choose the main branch.
2. Create a new theme.
3. Apply the theme in the admin panel.
4. Create a new styles file in the theme:
```
app/design/frontend/Vendor/theme/web/css/source/_module.less
```
5. Add the content from the description above for the `_module.less` file.
6. To make the result more clear, try to use the `empty` layout for the home page. Or just create a new file: 
```
app/design/frontend/Vendor/theme/Magento_Theme/layout/default.xml
```
With the content:
```xml
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd"
>
    <update handle="empty"/>
</page>

```
7. Clear all the static files and cache or just run the Grunt LESS compilation.
8. Check the result on the storefront. You have to see the same as in my first screenshot above.
9. Then rename the file from `_module.less` to `_extend.less` with the same content. Just rename the file name output inside.
10. Re-compile styles again.
11. Check the result.
12. Common styles have a higher priority than styles from the mobile query mixin.
13. Apply changes from the current PR.
15. Re-compile styles.
16. Check again, the issue has to be fixed.

**Actual Result:** :heavy_check_mark:
image

**After:** :heavy_check_mark:
image

**Before:** :heavy_multiplication_x: 

image

**_Note: Failed tests don’t seem to be related to PR Changes._**

**Tested all the manual scenarios, no impact on regression testing.**

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Unit Tests

**Comment by engcom-Charlie** [comment]
@engcom-Hotel please check the Unit test failures, till then moving it to Extended testing.

Thank you!

**Comment by engcom-Hotel** [comment]
@magento run Unit Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Integration Tests,Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
Functional Tests B2B failure are different on last two run on same commit.
Run1
Screenshot 2023-12-12 at 3 28 07 PM

Run2
Screenshot 2023-12-12 at 3 28 14 PM

Hence moving it to `Merge in progress`

**Comment by engcom-Charlie** [comment]
@magento run Semantic Version Checker

**Pull request merged**
