### PR TITLE
Replacing deprecated methods for Magento_Security module.

### PR DESCRIPTION
**Pull request by tiagosampaio**
Replacing deprecated methods for Magento_Security module.

### Description
No description needed.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @tiagosampaio. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by VladimirZaets** [comment]
@magento-engcom-team combine 17558 17555 17557

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
Hi @tiagosampaio
Thank you for your contribution. This pull request has been combined (merged) with https://github.com/magento/magento2/pull/17557 to optimize pull requests queue on magento/magento2 repository
Closing this pull request.

**Comment by VladimirZaets** [comment]
@magento-engcom-team combine 17558 17555

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
@tiagosampaio all pull requests have been successfully combined together: 
 - merged https://github.com/magento/magento2/pull/17558: Replacing deprecated methods for Magento_Search module.
 - merged https://github.com/magento/magento2/pull/17555: Replacing deprecated methods for Magento_Sitemap module.

**Comment by magento-engcom-team** [comment]
Hi @tiagosampaio. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Comment by miguelbalparda** [comment]
Some tests were failing in a port of this PR and checking I believe there might be an error in `https://travis-ci.org/magento/magento2/builds/415208348?utm_source=github_status&utm_medium=notification`.
> addSuccessMessageptionMessage

 seems to be missing a letter.

**Comment by tiagosampaio** [comment]
@miguelbalparda the fix was applied to the PR.

**Comment by miguelbalparda** [comment]
I think it’s also happening in this one that’s already merged.

**Comment by tiagosampaio** [comment]
@miguelbalparda I checked out the file in which this mistake was applied to and it seems to be fixed in `2.3-develop` branch.

**Pull request merged**
