### PR TITLE
Fix for issue 38703 deselect default attr options

### LINKED ISSUE #38703: Default Product Attribute Settings Issue
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug
Magento version 2.4.7 
When editing a product attribute if a default is selected there is no way of unselecting all, so there is always some default now for that option. Work around is whenever creating new parts manually turn off all attributes that are turned on by default

### Steps to reproduce

1. Go into admin view 
2. Select Stores in admin side panel 
3. Select product under attributes 

 Scenario 1:

4. Select an attribute to edit which has Catalog Input Type for Store Owner is Visual swatch or dropdown
5. If the "is default" option is selected, there is no way to set the attribute to no longer have a default option

Scenario 2:

6. Select an attribute to edit which has Catalog Input Type for Store Owner is Multiple Select
7. If you deselect the default option then save or save and continue it still is set as the default
8. If you select multiple options as default and deselect the default options then save or save and continue all the options 
    are selected as default

### Expected result

 Scenario 1: If a default is selected, there would be a way to unselect having a default set
 Scenario 2: If you deselect the default option then save or save and continue it should removed from default

### Actual result

Scenario 1: Once a default is set, there is no way to turn defaults off for that option
Scenario 2: Once a default is set, after we deselect it , its never saved

### Additional information

image
See how a default is set to the 1675 psi option, now this attribute will always have some default set and it cannot be changed to not be on by default

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rostilos**
### Description (*)

The ability to remove the default options under Visual, Text Swatch and Dropdown attributes has been added ( a separate button under the list )

And also - for multiselect attribute ( being finalized )

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38703

### Manual testing scenarios (*)

1.Described in the original issue

### Questions or comments

This is more as a suggested option, but I'd like to clarify implementation issues, perhaps the reviewers will suggest a better option

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @rostilos,

Thanks for the contribution!

The code changes look good to me, but please add some automated tests in accordance with the [Definition of Done (DOD)](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1).

And also please look into the build failures.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run Static Tests, Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE, Static Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
@magento give me test instance

**Comment by engcom-Bravo** [comment]
Hi @rostilos,

Thanks for the collaboration & contribution!

:x: QA not Passed


For the scenario 1 we got the button and we are able to reset the default option.


When we are selecting multiple options for Multi Select type attribute it is not saving all the options only some of the options got saved.

Please refer video :


https://github.com/user-attachments/assets/b36a6d17-1f2a-4105-885b-417950d09de9



Could you please let us know if we are missing anything.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @rostilos,

Could you please look into this comment https://github.com/magento/magento2/pull/38927#issuecomment-2309934462 and please let us know if we are missing anything.

Thanks.

**Comment by rostilos** [comment]
@engcom-Bravo 
Hi!
Yes, I will revise soon ( I think this bug is unrelated to edits and is reproduced on the current version, but I will double-check this and let you know or make fixes )

**Comment by engcom-Bravo** [comment]
Hi @rostilos,

Thanks for your update.

As per this comment https://github.com/magento/magento2/pull/38927#issuecomment-2340048989 We are moving this PR to `ON HOLD` till that time.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @rostilos,

Internal team has started to work on it

Thanks.

**Comment by rostilos** [comment]
@engcom-Bravo

Hi!
I have a small question regarding the process of reviewing PRs for contribution.
Our company occasionally makes contributions to the M2 repository, and I've repeatedly noticed messages under the pull-request “Internal team has started to work on it”.
This confuses me a bit, and I don't quite understand: in this case we should stop working on the PR, because the internal team is working on it, or we can continue working on it and the PR will be accepted in the future?

**Comment by engcom-Charlie** [comment]
> @engcom-Bravo
> 
> Hi! I have a small question regarding the process of reviewing PRs for contribution. Our company occasionally makes contributions to the M2 repository, and I've repeatedly noticed messages under the pull-request “Internal team has started to work on it”. This confuses me a bit, and I don't quite understand: in this case we should stop working on the PR, because the internal team is working on it, or we can continue working on it and the PR will be accepted in the future?

Hi @rostilos,

Thank you for your contribution!

Sorry, if we have created any confusion for you here. The intent to say "Internal team is working on it" is that, Magento core engineering team is working on the issue which you have addressed in this PR. Team will cherry pick the commits from your PR and may do further implementation to cover few more scenarios as needed. We will reach out to you if we need more information. For now, you can pause work on this PR.

Thank you once again!

**Pull request merged**
