### PR TITLE
Cleanup ObjectManager usage - Magento_Catalog Cron,CustomerData,Helper

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This PR cleanups ObjectManager usage in Magento_Catalog Cron and Helper, by removing object manager instantiation from non-api classes. This is second part of #27135 split into smaller chunks to proceed it easily.

### Fixed Issues (if relevant)

N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lbajsarowicz — DISMISSED** [review]
:heavy_check_mark: Thank you for your contribution.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7138](https://jira.corp.magento.com/browse/ENGCOM-7138) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, Integration Tests

**Review by engcom-Delta — CHANGES_REQUESTED** [review]
Hi @Bartlomiejsz could you update your branch? There are too many failed tests and I have problem with installing your branch locally

**Comment by lbajsarowicz** [comment]
@Bartlomiejsz Knock :-)

**Comment by Bartlomiejsz** [comment]
@lbajsarowicz done :)

**Comment by Bartlomiejsz** [comment]
@lbajsarowicz @engcom-Delta done :)

**Comment by Bartlomiejsz** [comment]
Closing for same reason as https://github.com/magento/magento2/pull/27855 - will be recreated for 2.5.0

**Pull request closed without merging**
