### PR TITLE
Feature australian regions

### PR DESCRIPTION
**Pull request by maximbaibakov**
Add Australian regions to Magento Vanila Install

### Description
Add Australian regions to be as a dropdown during address population

### Fixed Issues (if relevant)
1. magento/magento2#17514: Add Australian regions 

### Manual testing scenarios
1. Add product to cart
2. Go to checkout
3. Select Australia as shipping / billing country
4. I see Australian regions as a dropdown 

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=17516) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @maximbaibakov. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-2747](https://jira.corp.magento.com/browse/ENGCOM-2747) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@maximbaibakov thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by gwharton** [comment]
This will only add regions for new installs. You also need to implement the updatadata scripts so that existing installs will be altered too.

**Comment by VladimirZaets** [comment]
@gwharton thanks for the comment. 
Hi @maximbaibakov,  please create update data scripts to support already existing installs.

**Comment by maximbaibakov** [comment]
Hi @gwharton and @VladimirZaets 

Good point! I have updated the update data scripts to include Australian regions

Regards,
Maxim

**Comment by magento-engcom-team** [comment]
Hi @maximbaibakov. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
