### PR TITLE
Fixed duplicated ids to index by mview changelog

### LINKED ISSUE #30012: Asynchronous indexing can break large servers
Large stores with extremely active product databases can suffer many related problems with indexers not being kept up to date.  Products can disappear from the website, product data can be out of date on the website, excessive cache flushing can  cause huge server load spikes.

This is due to the manner in which triggers are created by the core magento code in https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/lib/internal/Magento/Framework/Mview/View/Subscription.php#L201

INSERT INTO  will insert a new record regardless of whether one exists or not.
REPLACE INTO will as the name says, replace a record - and in this case it will generate a new version_id since that is an auto_increment field.

### Preconditions (*)
1. An extremely large database.  Example 500,000 products
2. An active update schedule

### Steps to reproduce (*)
1.  Create a sample database with 500,000 products
2. Enable Asynchronous indexing
3. Reduce crons to every 10 minutes
4. Run a mass script to change the inventory for the products every 30 seconds.   So within 10 minutes, you will have made 10 million updates

### Expected result (*)
1. When the indexer runs, it will index the latest product information once for each index

### Actual result (*)
It will actually try to index each product 20 times, once for each update

### Additional information to reproduce the issue

1. Change the price of the product with SKU `24-MB01` 20 times via API `rest/all/V1/products/24-MB01`
2. Doing the price change data inserted in the table `catalog_product_price_cl`
3. Adjust the `DEFAULT_BATCH_SIZE` in file `lib/internal/Magento/Framework/Mview/View.php` with 10 from 1000.
4. Enable the DB logs via the `bin/magento dev:query-log:enable` command.
5. grep the text to get the SQL query on table `catalog_product_price_cl`. Please find attached the screenshot of db.log:

image

The query always returns `entity_id 1` each time.

In this case, it seems that entity_id 1 will process many times, instead of only 1 time, and should be on the latest one.
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

### PR DESCRIPTION
**Pull request by MateuszMesek**
### Description (*)
When we have a large number of records in changelog tables  (over 1000) then indexer called by mview action can process this same ids few times. 

`ChangeLogBatchWalker` is changed to use temporary table to collect unique ids to reindex it. List of ids is returns in batches by `Generator`.

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/30012

### Manual testing scenarios (*)
1. Set indexer in "On Scheduled" mode.
2. Insert to the changelog table related to your indexer over 1000 ids to reindex them. But in on each 1000 records your need have duplicated id. This can be a list of this same id duplicated over 1000x. 
3. Run `indexer_update_all_views` cron job.
4. You will see this same ids used few times by mview action.

In case when your changelog table will be filled by this same id (ex: 1) 10000x then you should see used this id (1) 10x by mview action.

### Related Pull Requests
https://github.com/magento-gl/magento2-infrastructure/pull/22

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by MateuszMesek** [comment]
@magento run all tests

**Comment by hostep** [comment]
This following issue sounds related to this fix: https://github.com/magento/magento2/issues/30012, can you confirm @MateuszMesek? If they are related, we should link this PR to that issue.

**Comment by slavvka** [comment]
@magento run all tests

**Comment by MateuszMesek** [comment]
@hostep yes, this PR is related to issue https://github.com/magento/magento2/issues/30012. I updated PR description.

**Comment by MateuszMesek** [comment]
@magento run all tests

**Comment by MateuszMesek** [comment]
@magento run Static Tests

**Comment by MateuszMesek** [comment]
@magento run Static Tests

**Comment by hostep** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @MateuszMesek
Thank you wu much for a great improvement! Could you please fix failing static tests?

**Comment by MateuszMesek** [comment]
@magento run all tests

**Comment by MateuszMesek** [comment]
@magento run Static Tests

**Comment by MateuszMesek** [comment]
@magento run Static Tests

**Comment by MateuszMesek** [comment]
@magento run static tests

**Comment by MateuszMesek** [comment]
@magento run all tests

**Comment by MateuszMesek** [comment]
Hi @ihor-sviziev, 
I resolved problems with static tests apart from one related with banned word "CHANGELOG"
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36155/83b9aa36f09c0bb9fa7e05f18e09f329/Statics/report-sanity-ce.html

Above problem is related with incorrect configuration of banned words?

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE, Static Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by iGerchak — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests, Static Tests, WebAPI Tests

**Comment by engcom-Charlie** [comment]
Functional B2B failure is different in latest 2 runs. Hence seems to be flaky and not related to this PR changes.

1. Run 1
image

3. Run 2
image

**Comment by engcom-Charlie** [comment]
@magento run Static Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Charlie** [comment]
The static tests are not related to this PR and not failing because of PR changes hence moving this PR to Merge In Progress.

Thank you!

**Comment by sebfie** [comment]
Can we have this fix ?!!

**Comment by engcom-Charlie** [comment]
@magento run Static Tests

**Comment by hostep** [comment]
@engcom-Charlie: if you're going to change the classnames and namespaces, you'll have to change the filenames and directory names as well...

**Comment by engcom-Charlie** [comment]
> @engcom-Charlie: if you're going to change the classnames and namespaces, you'll have to change the filenames and directory names as well...
> 
> _Update_: it looks like the static tests luckily report this problem as well

Yes @hostep

I am already working on it.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run Static Tests

**Comment by engcom-Charlie** [comment]
@magento run Static Tests

**Comment by ConradoSM** [comment]
Hi everyone, I was testing the PR and I get the following error:

image

Tnks in advance for the support.

**Comment by MateuszMesek** [comment]
@magento run Static Tests

**Comment by MateuszMesek** [comment]
@magento run Static Tests

**Comment by MateuszMesek** [comment]
@ConradoSM can you provide more details how to reproduce your issue?

Maybe problem is related with your module where you have available command `summa:cron:execute`.
Please try use `ethanyehuda/magento2-cronjobmanager`.

**Comment by engcom-Charlie** [comment]
As there are some static test failures, moving it back to Extended Testing.

Thank you!

**Comment by ConradoSM** [comment]
> @ConradoSM can you provide more details how to reproduce your issue?
> 
> Maybe problem is related with your module where you have available command `summa:cron:execute`. Please try use `ethanyehuda/magento2-cronjobmanager`.

@MateuszMesek PR implementation test doesn't work in magento cloud staging environment, in my local environment it works as expected. Magento version: 2.4.6-p1, the command summa:cron:execute is a custom module for run the magento crons and this is not a problem because when the partial reindex run in staging environment the logs get the same error.

**Comment by MateuszMesek** [comment]
@ConradoSM can you provide stack trace of your exception?

**Comment by ConradoSM** [comment]
@MateuszMesek yes of course:

`Next Zend_Db_Statement_Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'vxulksythc5nk_stg.catalog_product_attribute_cl__tmp64a6f80515a613_12170613' doesn't exist, query was: SELECT MAX(id) as max, COUNT(*) as cnt FROM (SELECT `catalog_product_attribute_cl__tmp64a6f80515a613_12170613`.* FROM `catalog_product_attribute_cl__tmp64a6f80515a613_12170613` WHERE (`catalog_product_attribute_cl__tmp64a6f80515a613_12170613`.`id` > '23') ORDER BY `catalog_product_attribute_cl__tmp64a6f80515a613_12170613`.`id` ASC
 LIMIT 1000) AS `t` in /app/vxulksythc5nk_stg/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:109
Stack trace:
#0 /app/vxulksythc5nk_stg/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(91): Magento\Framework\DB\Statement\Pdo\Mysql->tryExecute(Object(Closure))
#1 /app/vxulksythc5nk_stg/vendor/magento/zend-db/library/Zend/Db/Statement.php(313): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /app/vxulksythc5nk_stg/vendor/magento/zend-db/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /app/vxulksythc5nk_stg/vendor/magento/zend-db/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT MAX(id) ...', Array)
#4 /app/vxulksythc5nk_stg/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(564): Zend_Db_Adapter_Pdo_Abstract->query('SELECT MAX(id) ...', Array)
#5 /app/vxulksythc5nk_stg/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(634): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT MAX(id) ...', Array)
#6 /app/vxulksythc5nk_stg/vendor/magento/zend-db/library/Zend/Db/Adapter/Abstract.php(756): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#7 /app/vxulksythc5nk_stg/vendor/magento/module-resource-connections/DB/Adapter/Pdo/MysqlProxy.php(1309): Zend_Db_Adapter_Abstract->fetchRow(Object(Magento\Framework\DB\Select), Array, 2)
#8 /app/vxulksythc5nk_stg/vendor/magento/framework/DB/Query/BatchIterator.php(176): Magento\ResourceConnections\DB\Adapter\Pdo\MysqlProxy->fetchRow(Object(Magento\Framework\DB\Select))
#9 /app/vxulksythc5nk_stg/vendor/magento/framework/DB/Query/BatchIterator.php(116): Magento\Framework\DB\Query\BatchIterator->calculateBatchSize(Object(Magento\Framework\DB\Select))
#10 /app/vxulksythc5nk_stg/vendor/magento/framework/Mview/View/ChangeLogBatchWalker.php(111): Magento\Framework\DB\Query\BatchIterator->next()
#11 /app/vxulksythc5nk_stg/vendor/magento/framework/Mview/View.php(307): Magento\Framework\Mview\View\ChangeLogBatchWalker->walk(Object(Magento\Framework\Mview\View\Changelog), 5781329, 5781425, 1000)
#12 /app/vxulksythc5nk_stg/vendor/magento/framework/Mview/View.php(266): Magento\Framework\Mview\View->executeAction(Object(Magento\Catalog\Model\Indexer\Product\Eav\Interceptor), 5781329, 5781425)
#13 /app/vxulksythc5nk_stg/vendor/magento/framework/Mview/Processor.php(44): Magento\Framework\Mview\View->update()
#14 /app/vxulksythc5nk_stg/vendor/magento/module-indexer/Model/Processor.php(119): Magento\Framework\Mview\Processor->update('indexer')
#15 /app/vxulksythc5nk_stg/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Indexer\Model\Processor->updateMview()
#16 /app/vxulksythc5nk_stg/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Indexer\Model\Processor\Interceptor->___callParent('updateMview', Array)
#17 /app/vxulksythc5nk_stg/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Indexer\Model\Processor\Interceptor->Magento\Framework\Interception\{closure}()
#18 /app/vxulksythc5nk_stg/generated/code/Magento/Indexer/Model/Processor/Interceptor.php(32): Magento\Indexer\Model\Processor\Interceptor->___callPlugins('updateMview', Array, Array)
#19 /app/vxulksythc5nk_stg/vendor/magento/module-indexer/Cron/UpdateMview.php(31): Magento\Indexer\Model\Processor\Interceptor->updateMview()
#20 [internal function]: Magento\Indexer\Cron\UpdateMview->execute(Object(Magento\Cron\Model\Schedule))
#21 /app/vxulksythc5nk_stg/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(368): call_user_func_array(Array, Array)
#22 /app/vxulksythc5nk_stg/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(879): Magento\Cron\Observer\ProcessCronQueueObserver->_runJob(1688664060, 1688664068, Array, Object(Magento\Cron\Model\Schedule), 'index')
#23 /app/vxulksythc5nk_stg/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(840): Magento\Cron\Observer\ProcessCronQueueObserver->tryRunJob(1688664060, 1688664068, Array, Object(Magento\Cron\Model\Schedule), 'index')
#24 /app/vxulksythc5nk_stg/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(280): Magento\Cron\Observer\ProcessCronQueueObserver->processPendingJobs('index', Array, 1688664068)
#25 /app/vxulksythc5nk_stg/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\Cron\Observer\ProcessCronQueueObserver->execute(Object(Magento\Framework\Event\Observer))
#26 /app/vxulksythc5nk_stg/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Cron\Observer\ProcessCronQueueObserver), Object(Magento\Framework\Event\Observer))
#27 /app/vxulksythc5nk_stg/vendor/magento/module-staging/Model/Event/Manager.php(97): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#28 /app/vxulksythc5nk_stg/generated/code/Magento/Staging/Model/Event/Manager/Proxy.php(95): Magento\Staging\Model\Event\Manager->dispatch('default', Array)
#29 /app/vxulksythc5nk_stg/vendor/magento/framework/App/Cron.php(86): Magento\Staging\Model\Event\Manager\Proxy->dispatch('default')
#30 /app/vxulksythc5nk_stg/vendor/magento/module-cron/Console/Command/CronCommand.php(126): Magento\Framework\App\Cron->launch()
#31 /app/vxulksythc5nk_stg/vendor/symfony/console/Command/Command.php(298): Magento\Cron\Console\Command\CronCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /app/vxulksythc5nk_stg/vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /app/vxulksythc5nk_stg/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Cron\Console\Command\CronCommand\Interceptor->___callParent('run', Array)
#34 /app/vxulksythc5nk_stg/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cron\Console\Command\CronCommand\Interceptor->Magento\Framework\Interception\{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /app/vxulksythc5nk_stg/generated/code/Magento/Cron/Console/Command/CronCommand/Interceptor.php(23): Magento\Cron\Console\Command\CronCommand\Interceptor->___callPlugins('run', Array, Array)
#36 /app/vxulksythc5nk_stg/vendor/symfony/console/Application.php(1040): Magento\Cron\Console\Command\CronCommand\Interceptor->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /app/vxulksythc5nk_stg/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Cron\Console\Command\CronCommand\Interceptor), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /app/vxulksythc5nk_stg/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 /app/vxulksythc5nk_stg/vendor/symfony/console/Application.php(171): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 /app/vxulksythc5nk_stg/bin/magento(23): Symfony\Component\Console\Application->run()
#41 {main}`

**Comment by engcom-Hotel** [comment]
Hello @ConradoSM,

As per the error mentioned by you here https://github.com/magento/magento2/pull/36155#issuecomment-1622278207, it seems that it is related to some third-party module. 

We have tried to reproduce this issue in our local machine with the below command, but we are unable to reproduce this issue:

**Comment by MateuszMesek** [comment]
@ConradoSM  I can't reproduce your issue on my local, Magento Cloud and other environments where I have access.

Only idea what I have for you is try use InnoDB engine instead Memory engine.
Please remove this line https://github.com/magento/magento2/blob/879bbeaa0931230f3be512b3e56aa1fb16636303/lib/internal/Magento/Framework/Mview/View/ChangelogBatchWalker/IdsTableBuilder.php#L53 in your environment and check again.

**Comment by ConradoSM** [comment]
@engcom-Hotel @MateuszMesek My cloud environment has a problem with the mysql slave instance, but I think that the fix does not work at all since I activated a catalog rule and the price index is "in working" more than 15 minutes ago:

image

**Comment by ConradoSM** [comment]
@engcom-Hotel @MateuszMesek another print with the problem, 20 min stuck in working:

image

**Comment by MateuszMesek** [comment]
@ConradoSM  can you provide dump of your `catalog_product_price_cl` table?

**Comment by engcom-Echo** [comment]
Hi @MateuszMesek,

Thanks for the collaboration & contribution!

:heavy_check_mark: QA Passed

Fixed duplicated ids to index by mview changelog

**Manual Scenario Steps**

1. Change the price of the product 10 times via API rest/all/V1/products/<sku>
2. Doing step 1, data inserted in the table catalog_product_price_cl
3. Adjust the DEFAULT_BATCH_SIZE in file `lib/internal/Magento/Framework/Mview/View.php` with 2 from 1000.
4. Enable the DB logs via the `bin/magento dev:query-log:enable` command.
5. Run indexer via command `n98-magerun2 sys:cron:run indexer_update_all_views`
6. grep the text to get the SQL query on table catalog_product_price_cl. Please find attached the screenshot of db.log:

**Actual Result:** :heavy_check_mark:
- When the indexer runs, it will index the latest product information once for each index

**Before:** :heavy_multiplication_x:
Screenshot 2023-08-16 at 10 12 03 AM

**After:** :heavy_check_mark:
Screenshot 2023-08-16 at 10 13 20 AM

As there are build failure Hence moving it to `extended testing`.

Thanks

**Comment by engcom-Echo** [comment]
@magento run Static Tests

**Comment by engcom-Echo** [comment]
@magento run Static Tests,Unit Tests,WebAPI Tests,Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Unit Tests

**Comment by engcom-Echo** [comment]
Failing test does not seems to be related to PR changes. Hence moving it to `Merge In Progress`

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Unit Tests,Integration Tests,Functional Tests EE

**Comment by engcom-Echo** [comment]
Functional Tests EE failure are different on last two run on same commit. Other build failure are not related to PR changes.
Functional Tests EE
Run1
36155-ee

Run2
Screenshot 2023-08-18 at 12 36 47 PM

**Comment by dooblem** [comment]
We have 2 customers affected by this. One on m2cloud, the other on premise (community edition). Both version 2.4.6

The dev teams are working to apply this PR next week.

To be able to unlock the other indexes and pass the weekend without loosing products on the frontoffice. We are using this very quick and dirty workaround, issuing the following SQL query every 1min or 30s or so. Schedule by a cron or a while true loop in a screen : 
```
mysql --defaults-file=xxxx.cnf magento -e 'delete from catalog_product_price_cl;'
```

I also really cannot understand why there are so many duplicates in the changelog table : 
```
MariaDB [62k7efhsipvjs]> select * from catalog_product_price_cl;
+------------+-----------+
| version_id | entity_id |
+------------+-----------+
| 1349334317 |   2135411 |
...
| 1349438813 |   2144443 |
| 1349438816 |   2144443 |
| 1349438819 |   2144443 |
| 1349438822 |   2144443 |
+------------+-----------+
34801 rows in set (0.014 sec)
```

**Comment by Bar3nho** [comment]
@MateuszMesek have you tested this solution with different MAGE_INDEXER_THREADS_COUNT values? 

Locally I've tested it on 4 threads and it always ends with a series of "drop temporary table" that break the indexer.

**Comment by MateuszMesek** [comment]
> @MateuszMesek have you tested this solution with different MAGE_INDEXER_THREADS_COUNT values?
> 
> Locally I've tested it on 4 threads and it always ends with a series of "drop temporary table" that break the indexer.

@Bar3nho could you provide how you call mview via multi-thread or provide steps to replicate your issue?

`MAGE_INDEXER_THREADS_COUNT` is supported by `Magento\Indexer\Model\ProcessManager`. 
This manager is used only for full indexation, not for mview indexation.
https://github.com/search?q=repo%3Amagento%2Fmagento2%20processManager-%3Eexecute&type=code

**Comment by Bar3nho** [comment]
@MateuszMesek  I checked it once more and the problem is due to the fact that our custom mview indexer uses `Magento\Indexer\Model\ProcessManager`, which enables multithreading. The changes introduced in `ChangelogBatchWalker` mean that it is no longer possible to use multiple threads while doing just a partial reindex. Since Magento has never really taken advantage of multithreading in its partial indexers, this is not a bug but rather an inconvenience. I will point this out in my issue report, thank you for a good point.

**Comment by ilnytskyi** [comment]
As @Bar3nho mentioned. When using `Magento\Indexer\Model\ProcessManager` in a custom Mview for partial reindex it leads to strange behaviour.
I think it's due to combining `yield` and `finally` in one place.
Selection_1132

Our DB log shows that tmp table dropped multiple times. Then Select is running against that table, and then DROP again.
Selection_1131

I think the bug should be easily reproduceable with any  implementation for `\Magento\Framework\Mview\ActionInterface` that uses  `Magento\Indexer\Model\ProcessManager` . e.g. when data can be isolated per store and indexed in parallel.

**Pull request merged**
