### PR TITLE
Remove double semicolon from the style sheets.

### PR DESCRIPTION
**Pull request by sanganinamrata**
### Description

Remove double semicolon from the style sheets.

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios

N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15795) <br/>All committers have signed the CLA.

**Comment by sanganinamrata** [comment]
@vijay-wagento This pull request doesn't merge yet. Are you hurry to create forward/backword pull request? 
I will create forward/backword pull request after merge my this request.

**Comment by vijay-wagento** [comment]
Hello @NamrataChangani , if you know you can do it. I created because I found small change and that work in backward and forward version. Thanks for closing PR.

**Comment by magento-engcom-team** [comment]
Hi @NamrataChangani. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.6 release.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
