### PR TITLE
Adding is_active in Customer module #8540

### PR DESCRIPTION
**Pull request by roychandrasekhar**
+ Adding is_active in customer module

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15374) <br/>All committers have signed the CLA.

**Comment by gelanivishal** [comment]
@roychandrasekhar Can you please accept [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=15374) before we can accept your contribution.

**Comment by avoelkl** [comment]
Hi @roychandrasekhar,
Thanks for your PR!
I think it makes sense to have the is_active flag in the interface but I am not 100% sure if this should be in the 2.2 or 2.3 branch. Maybe @paliarush can help? :)

**Comment by VladimirZaets** [comment]
Hi, @roychandrasekhar, thank you for collaboration.
1) This fix cannot be merged to Magento 2.2 due to [Magento backward-compatible guide](http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/) we can't change interfaces and create new public methods
2) You should have methods `getIsActiv setIsActive` in the interface
3) In the customer model was implemented the methods that don't exist in the interface

Please use [extension attributes](https://devdocs.magento.com/guides/v2.2/extension-dev-guide/extension_attributes/adding-attributes.html) to realize this functionality.

**Pull request closed without merging**
