### PR TITLE
Multilanguage store specific baseurl

### PR DESCRIPTION
**Pull request by BlackIkeEagle**
We have a website for example http://magento2.dev/

We have 3 stores,
locale nl_NL; uses same base_url as website
locale fr_FR; uses http://magento2.dev/fr/
locale en_US; uses http://magento2.dev/en/

when we go to the homepage and switch the language everything seems to
work.

But for example when we go to a category page outside the "default site"
url we get a 404.

This is normal because we find no match in the routing.

if our category page is /category/subcategory we match in the
UrlRewriteRouter to /catalog/categroy/view/id/x .

When we are in a storeview where there is /fr or /en in the beginning of
the path, we match nothing and result in a 404.

### CODE REVIEW

**Comment by BlackIkeEagle** [comment]
I'll fix the 4 Failures in integration test 1

**Comment by KrystynaKabannyk** [comment]
hello @BlackIkeEagle, can you please update code of the PR and cover it by Travis tests?

**Comment by BlackIkeEagle** [comment]
@KrystynaKabannyk I currently lack a bit of time. I hope I can attend this issue within reasonable time.

**Comment by BlackIkeEagle** [comment]
There is a working update now, please verify.

**Comment by BlackIkeEagle** [comment]
The build failure has nothing to do with this change!

**Comment by okorshenko** [comment]
@BlackIkeEagle  Thank you for your contribution. Could you please fix cyclomatic complexity in method app/code/Magento/Store/App/Response/Redirect.php : _isUrlFromOtherStore() Thank you!

Please, see https://travis-ci.org/magento/magento2/jobs/125746121

**Comment by okorshenko** [comment]
Internal ticket: MAGETWO-52470

**Comment by BlackIkeEagle** [comment]
@okorshenko I'll try to address as soon as possible

**Comment by BlackIkeEagle** [comment]
@okorshenko the cyclomatic complexity issue should be fixed now. I'll rebase on current development too.

**Comment by adragus-inviqa** [comment]
So what does this do/fix?

**Comment by hshar7** [comment]
Hey @BlackIkeEagle thank you for fixing the cyclomatic complexity but unfortunately the integration tests are still broken.

**Comment by BlackIkeEagle** [comment]
@hshar7 yeah sorry I was a bit overly enthousiast and cut some corners

**Comment by BlackIkeEagle** [comment]
hmm PHP7 unittest failed because of: "The command "phpenv global 7.0" failed and exited with 1 during ."

**Comment by hshar7** [comment]
@BlackIkeEagle I ran that build again, seems to be working. Thanks for fixing those!

**Comment by hshar7** [comment]
@BlackIkeEagle if you have a minute could you please provide a brief description of this pr and its functionality?

**Comment by BlackIkeEagle** [comment]
@hshar7 

the first commit had the usefull information but it seems github did not pick it up

We have a website for example http://magento2.dev/

We have 3 stores,
locale nl_NL; uses same base_url as website
locale fr_FR; uses http://magento2.dev/fr/
locale en_US; uses http://magento2.dev/en/

when we go to the homepage and switch the language everything seems to
work.

But for example when we go to a category page outside the "default site"
url we get a 404.

This is normal because we find no match in the routing.

if our category page is /category/subcategory we match in the
UrlRewriteRouter to /catalog/categroy/view/id/x .

When we are in a storeview where there is /fr or /en in the beginning of
the path, we match nothing and result in a 404.

**Comment by hshar7** [comment]
Hi @BlackIkeEagle I sent you an email yesterday but I'm not sure if you received it. Please email me at hsharhan[At symbol]magento.com to discuss this since we have some questions about this pr and it would be easier to talk there.

**Comment by BlackIkeEagle** [comment]
@hshar7 was my mail sufficiently clear or are you waiting for a screencast too :)

**Comment by hshar7** [comment]
@BlackIkeEagle Yes thank you very much for the email it really did clear things up for me! In context of my reply I asked if we could close this as we do not think it is a bug. Is that okay?

**Comment by BlackIkeEagle** [comment]
@hshar7 Could you leave it open for now, I want to check some things first but I have other work to do at the moment. I still think its a bug since we had to update all our 2.0.x stites with this patch to avoid issues.

**Comment by BlackIkeEagle** [comment]
@hshar7 here a quick screenrecording where we get a 404 on the homepage without this patchset https://herecura.eu/files/recording-2016-06-01_12.35.23.webm

**Comment by hshar7** [comment]
@BlackIkeEagle Could you explain why you are adding the language codes to the base url? Instead of activating "add store codes to url" which would do the same and switching there would work correctly. These guys explain this pretty well: http://www.magestore.com/magento-2-tutorial/how-to-configure-store-urls-in-magento-2/

**Comment by BlackIkeEagle** [comment]
@hshar7 Because we were specifically instructed not to use the "add store codes to url" is the main reason.

**Comment by hshar7** [comment]
Why's that? because the store view switching used to be broken perhaps?

**Comment by hshar7** [comment]
@BlackIkeEagle Do you still want to keep this open?

**Comment by antonkril** [comment]
"Use store code in url" can't be used in this case because store code will be added to default store.

Use case from developer: Add store code to all stores except for default.

**Comment by okorshenko** [comment]
Hi @BlackIkeEagle 
Thank you for your Pull Request. I will review this PR as soon as possible. Sorry for delay

**Comment by BlackIkeEagle** [comment]
@okorshenko If something is not clear, or the intentions are not clear, let me know, I'll try to explain what we try to do.

**Comment by okorshenko** [comment]
@BlackIkeEagle could you please fix broken integration tests?

**Comment by BlackIkeEagle** [comment]
@okorshenko I can pick this branch back up and see if I can get this working on develop and then fix the tests

**Comment by okorshenko** [comment]
@BlackIkeEagle thank you. Please ping me once you will be ready for delivery.

**Comment by okorshenko** [comment]
@BlackIkeEagle thank you for your contribution. Please create new PR when ready. Closing this PR for now

**Pull request closed without merging**
