### PR TITLE
remove spaces caused patching problem in Product/View

### LINKED ISSUE #30601: [Issue] remove spaces caused patching problem in Product/View
This issue is automatically created based on existing pull request: magento/magento2#30198: remove spaces caused patching problem in Product/View

---------
It was impossible to apply patch to this file because whitespaces

### Description (*)

Code clean up 
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Create a patch for relative lines in PHPstorm
2. Apply patch
3. Patch is applied

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ilnytskyi**
It was impossible to apply patch to this file because whitespaces

### Description (*)

Code clean up 
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Create a patch for relative lines in PHPstorm
2. Apply patch
3. Patch is applied

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30601: remove spaces caused patching problem in Product/View

### CODE REVIEW

**Comment by ilnytskyi** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
I believe issue with patching goes from the IDE that you’re using or the git where you’re storing the patch. Anyways I’m ok with applying this small cleanup

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8273](https://jira.corp.magento.com/browse/ENGCOM-8273) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

Small improvement

1. Create a patch for relative lines in PHPstorm
2. Apply patch

**Actual Result:** :heavy_check_mark:  Patch successfully applied

**Pull request merged**
