### PR TITLE
[MFTF] Add StorefrontSelectFirstShippingMethodActionGroup

### LINKED ISSUE #33773: [Issue] [MFTF] Add StorefrontSelectFirstShippingMethodActionGroup
This issue is automatically created based on existing pull request: magento/magento2#30526: [MFTF] Add StorefrontSelectFirstShippingMethodActionGroup

---------
This PR add `StorefrontSelectFirstShippingMethodActionGroup`

### PR DESCRIPTION
**Pull request by Usik2203**
This PR add `StorefrontSelectFirstShippingMethodActionGroup`

### Resolved issues:
1. [x] resolves magento/magento2#33773: [MFTF] Add StorefrontSelectFirstShippingMethodActionGroup

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by rogyar** [comment]
Hi @Usik2203. Thanks for the refactoring. Good job! Since your edits contain backward-incompatible changes, the best way is to wait for `2.5-develop` branch. I'm putting this on hold for now. 

Thanks.

**Comment by rogyar** [comment]
Hi @Usik2203. Please, refer to my comment that explains a workaround for removing old steps and preserving BC

https://github.com/magento/magento2/pull/30223#discussion_r508492932

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests B2B

**Comment by Usik2203** [comment]
Hi @rogyar
I have applied your recommendations
Thanks

**Comment by rogyar** [comment]
Hi @Usik2203. Please, make sure you've adjusted this PR according to the following comment 

https://github.com/magento/magento2/pull/30525#discussion_r515237925

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
Hi @rogyar
I have applied your recommendations
Thanks :)

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8437](https://jira.corp.magento.com/browse/ENGCOM-8437) has been created to process this Pull Request

**Comment by Usik2203** [comment]
Hi @sidolov  
Could i kindly ask you remove `On hold` label 
This PR was approved but `On hold` label was added by Bot for some reason
Thanks!

**Comment by engcom-Bravo** [comment]
Manual QA not applicable. Moved to _Extended Testing_ column

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run all tests

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-8437](https://jira.corp.magento.com/browse/ENGCOM-8437) has been created to process this Pull Request

**Pull request merged**
