### PR TITLE
[Fixed] Checkout Section: Shipping step is getting skipped when customer hitting direct payment step URL

### PR DESCRIPTION
**Pull request by niravkrish**
### Description (*)

Checkout Section: Shipping step is getting skipped when customer hitting direct payment step URL

### Fixed Issues (if relevant)

1. magento/magento2#21596: Checkout Section: Shipping step is getting skipped when customer hitting direct payment step URL

### Manual testing scenarios (*)

1. Product Add To Cart and go to checkout page
2. hit payment url without adding shipping address

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4783](https://jira.corp.magento.com/browse/ENGCOM-4783) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4783](https://jira.corp.magento.com/browse/ENGCOM-4783) has been created to process this Pull Request

**Comment by sidolov** [comment]
@VasylShvorak please, verify case with virtual product (when shipping step is skipped).

**Comment by VasylShvorak** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @VasylShvorak. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @VasylShvorak, here is your [new Magento instance](https://pr-22405.instances.magento-community.engineering).
Admin access: [https://pr-22405.instances.magento-community.engineering/admin](https://pr-22405.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed
Result:
#22405PrVirtual

**Comment by cscd98** [comment]
Is this a replacement for https://github.com/magento/magento2/pull/21597?

**Comment by niravkrish** [comment]
> Is this a replacement for #21597?

Yes, @craigcarnell

**Comment by arunelangovan** [comment]
This will not work in case if only digital products in cart, When there is only digital products in cart and  you have to go to payment step by default. But this code sends them to shipping and which in-turn sends user to 404 page. I had experienced it on 2.2.9 and i have to remove this piece of code to accommodate digital orders through checkout.

@magento-engcom-team FYI

**Pull request merged**
