### PR TITLE
Enforce array type in DesignTheme config processor

### LINKED ISSUE #34440: [Issue] Enforce array type in DesignTheme config processor
This issue is automatically created based on existing pull request: magento/magento2#34092: Enforce array type in DesignTheme config processor

---------

### Description (*)

Without the type check, an empty config node like `<my_store />` in a `config.xml` breaks installation, as `null` is passed to the private method.

### Related Pull Requests

none

### Fixed Issues (if relevant)

none (can be created if desired)

### Manual testing scenarios (*)

1. create module with store specific configuration in `config.xml`
2. use empty node for one store, like `<my_store />`
3. run `bin/magento setup:install` or integration test suite

### Questions or comments

Since the changed method is private, this change is 100% backwards compatible. I'm not adding a test case since not having regressions should be a sufficient merge criteria when adding types.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by schmengler**
### Description (*)

Without the type check, an empty config node like `<my_store />` in a `config.xml` breaks installation, as `null` is passed to the private method.

### Related Pull Requests

none

### Fixed Issues (if relevant)

none (can be created if desired)

### Manual testing scenarios (*)

1. create module with store specific configuration in `config.xml`
2. use empty node for one store, like `<my_store />`
3. run `bin/magento setup:install` or integration test suite

### Questions or comments

Since the changed method is private, this change is 100% backwards compatible. I'm not adding a test case since not having regressions should be a sufficient merge criteria when adding types.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#34440: Enforce array type in DesignTheme config processor

### CODE REVIEW

**Comment by mrtuvn** [comment]
Can you add strict type to top php file and cover change with some kinds of automate test?
Thanks for your work

**Comment by schmengler** [comment]
> Can you add strict type to top php file and cover change with some kinds of automate test?

I'm afraid no. I would like to keep the change small and not break anything by making unrelated changes. One step at a time.

And as mentioned: I'm not adding a test case since not having regressions should be a sufficient merge criteria when adding types.

**Comment by schmengler** [comment]
@magento run all tests

**Comment by schmengler** [comment]
@magento run all tests

**Comment by schmengler** [comment]
@magento run all tests

**Comment by schmengler** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by schmengler** [comment]
@mrtuvn The failure in "Functional Tests B2B" seems to be unrelated, can you confirm?

**Comment by mrtuvn** [comment]
Changes look good to me 
What do you think @ihor-sviziev @orlangur

**Review by engcom-Hotel — APPROVED** [review]

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Echo** [comment]
:heavy_check_mark: QA Passed
Enforce array type in DesignTheme config processor

**Manual testing scenario:**

- create module with store specific configuration in config.xml
- use empty node for one store, like `<my_store />`
- run `bin/magento setup:install`

**Before:** :heavy_multiplication_x: 
breaks installation
Screenshot 2023-03-20 at 6 12 15 PM

**After:** :heavy_check_mark: 
Installation successful.
Screenshot 2023-03-20 at 6 13 45 PM

**Comment by engcom-Echo** [comment]
Functional Tests B2B failiures are different on last two run on same commit.
Run1
Screenshot 2023-03-21 at 11 36 00 AM

Run2
Screenshot 2023-03-21 at 11 35 50 AM

Hence Moving to `Merge In Progress`

**Pull request merged**
