### PR TITLE
33310 fix unsubscribe url in newsletter email template

### LINKED ISSUE #33310: unsubscribe link doesn't work anymore
Hello, I´m having an issue since I installed magento 2.4, and now still have the problem in magento 2.4.2-p1. The unsubscribe link doesn't work in the newsletter since magento 2.3.5.

The unsubscribe link for both is the same, {{var subscriber.getUnsubscriptionLink()}}

When I check over the unsubscribe link in a newsletter sent with magento 2.4.2 I get a blank page, as it fallows:

Before in magento 2.3.5, a link was generated to unsubscribe, as:

I've found some people with the same issue but nothing in concret to solve the problem.

Is this a bug already reported? Any solution?

Please find more details about the issue below:
https://github.com/magento/magento2/issues/33310#issuecomment-865098873

Best Regards,
Leonel Nunes

### PR DESCRIPTION
**Pull request by SilinMykola**
### Description (*)
I found out that the Resolver can't resolve the subscriber method `getUnsubscriptionLink()` and get a url. I changed it by adding property to subscriber before call transport to send email.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#33310

### Manual testing scenarios (*)
1. Magento Admin -> Customers -> All Customers -> Edit the Customer -> News Letter -> Subscribe to NewsLetter and save
2. Marketing -> News Letter Template -> Add new template
3. Marketing -> News Letter Template -> Actions -> Queue News Letter - edit and Save News Letter
4. News Letter should be triggered to the Customer email ID. If not triggered, run magento cron job: sudo php bin/magento cron:run, emails would be triggered automatically after running cron.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by andrewbess — CHANGES_REQUESTED** [review]
Hello @SilinMykola 
Thank you for your contribution.
Could you please fix failed unit tests?
Thank you in advance.

**Review by Den4ik — CHANGES_REQUESTED** [review]
Hi @SilinMykola 
Thanks for you contribution. Please pay attention to my comment.
This solution is not fully resolve the problem because any constructions `{{var object.getSomeMethod()}}` where `getSomeMethod` is real method ill not work.

Problem started here https://github.com/magento/magento2/commit/a009faa428eef44d806c3a8c59c91b28c4bd3d5c when changed default mode to strict.
In fact it's problem of strict resolver https://github.com/magento/magento2/blob/2.2/lib/internal/Magento/Framework/Filter/VariableResolver/StrictResolver.php#L102 that don't check and call real object methods.
Please compare with https://github.com/magento/magento2/blob/2.2/lib/internal/Magento/Framework/Filter/VariableResolver/LegacyResolver.php#L144

So I'm recommend to fix `\Magento\Framework\Filter\VariableResolver\StrictResolver` that solve all problems with method calls instead of solving one problem with newsletter

cc @ihor-sviziev @sivaschenko

**Comment by SilinMykola** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Hi @SilinMykola @Den4ik,
From the name, feels like it was specially introduced in order to prevent calling any methods.

https://github.com/magento/magento2/commit/efd77d3e7faf175c48bae45d3b1c237a00b37043

@sivaschenko @sidolov @gabrieldagama, could you provide the idea behind MC-19918?

**Comment by SilinMykola** [comment]
Hi @ihor-sviziev! it turns out that the first solution was correct? I think we can unite the both solutions.

**Comment by SilinMykola** [comment]
@magento run Integration Tests

**Comment by HenKun** [comment]
On https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/templates/template-email-migration.html it is shown how the strict filter works and what to do. the example is given with the newsletter confirmation link.

In order to work , they added some code in `vendor/magento/module-newsletter/Model/Subscriber.php` on line 497:

```
$vars = [
            'store' => $this->_storeManager->getStore($this->getStoreId()),
            'subscriber_data' => [
                'confirmation_link' => $this->getConfirmationLink(),
            ],
        ];
```

That enables calling the new way `{{var subscriber_data.confirmation_link}}` instead of the old way `{{var subscriber.getConfirmationLink()}}`

In order to adopt this method to the unsubsribe link, we need to add a custom template var somewhere in `vendor/magento/module-newsletter/Model/Queue.php` on line 261.

E.g. 

```
 )->setTemplateVars(
                [
                    'subscriber' => $item,
                    'subscriber_data' => [
                           'unsubscription_link' => $item->getUnsubscriptionLink(),
                   ]
               ]
```

We can then use the variable `{{var subscriber_data.unsubscription_link}}` in our newsletter template.


I am wondering this does not get more attention. It's a really critical issue!

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @SilinMykola,
Could you review the following comment https://github.com/magento/magento2/pull/33753#issuecomment-994779721 and the following article https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/templates/template-email-migration.html and adjust yours solution?

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
@magento run Unit Tests

**Comment by engcom-Bravo** [comment]
@magento run Functional Tests CE,Functional Tests B2B,WebAPI Tests,Database Compare

**Comment by engcom-Bravo** [comment]
@magento run Functional Tests CE,Functional Tests B2B

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
@magento run Functional Tests CE,Functional Tests EE

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests look not related to changes from this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9381](https://jira.corp.magento.com/browse/ENGCOM-9381) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
@magento run Functional Tests CE

**Comment by engcom-Alfa** [comment]
Hi @reporter, @reviewer
Thanks for the collaboration & contribution!

:x: QA not Passed

Unsubscribed link in the news letter email being absent
Pre-conditions :
1. Have Magento latest instance installed
2. Have a couple of customers added for the frontend login (Make sure to have a valid customer email id)

**Manual Scenario Steps**

1. Magento Admin -> Customers -> All Customers -> Edit any one existing Customer -> News Letter -> Subscribe to NewsLetter and save
2. Marketing -> News Letter Template -> Add new template with called subscription link in the html body
3. Marketing -> News Letter Template -> Actions -> Queue News Letter - edit and Save News Letter
4. News Letter should be triggered to the Customer email ID. If not triggered, run magento cron job: sudo php bin/magento cron:run, emails would be triggered automatically after running cron.
5. Or, Open the new letter, Preview New Letter


**:heavy_check_mark: Expected result After Fix** 
- Unsubscribe link should be existing in the news letter mail body content
- Screenshot from 2022-01-04 19-11-56


**:x: Actual result After Fix** 
- No subscription link found in the mail / preview template

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Based on the [above-comment](https://github.com/magento/magento2/pull/33753#issuecomment-1004852622), requesting changes!

**Comment by engcom-Charlie** [comment]
Hi @SilinMykola,

Thank you for your contribution!

I will look into the [issue](https://github.com/magento/magento2/pull/33753#issuecomment-1004852622) mentioned by @engcom-Alfa.

Thank you!

**Comment by SilinMykola** [comment]
@engcom-Charlie hi! I'm confused. What should I do? Thanks!

**Comment by engcom-Charlie** [comment]
Hi @SilinMykola,

It seems that there is some issue at @engcom-Alfa's PR branch so I looked into this PR.

@engcom-Alfa,

As per the Manual Testing Scenario mentioned in PR description as well as in [comment](https://github.com/magento/magento2/pull/33753#issuecomment-1004852622), I have checked the implemented functionality.

As per the expectation the "Unsubscribe link is getting display in the news letter mail body content in email as well as in preview template".

**:x: Before Fix** 

image

**:heavy_check_mark: Expected result After Fix** 

image

image

Could you please cross check once again and move the PR further accordingly. Moving this PR in Ready for Testing now.

Thank you!

**Comment by engcom-Alfa** [comment]
After following the [above steps](https://github.com/magento/magento2/pull/33753#issuecomment-1004852622), by looking into the [last-update](https://github.com/magento/magento2/pull/33753#issuecomment-1010937944), we are god to go. Hence moving the ticket to Merge In Progress.

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9381](https://jira.corp.magento.com/browse/ENGCOM-9381) has been created to process this Pull Request

**Pull request merged**
