### PR TITLE
[MFTF] Usage already defined action groups

### LINKED ISSUE #29420: [Issue] [MFTF] Usage already defined action groups
This issue is automatically created based on existing pull request: magento/magento2#29386: [MFTF] Usage already defined action groups

---------
This PR use already defined action groups `AdminSubmitAdvancedInventoryFormActionGroup` , `AdminClickOnAdvancedInventoryLinkActionGroup` `AdminSetStockStatusConfigActionGroup` inside tests  according to Best Practice

### PR DESCRIPTION
**Pull request by Usik2203**
This PR use already defined action groups `AdminSubmitAdvancedInventoryFormActionGroup` , `AdminClickOnAdvancedInventoryLinkActionGroup` `AdminSetStockStatusConfigActionGroup` inside tests  according to Best Practice

### Resolved issues:
1. [x] resolves magento/magento2#29420: [MFTF] Usage already defined action groups

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests B2B

**Comment by rogyar** [comment]
The failing functional test is not related to the current changeset. It's failing for other PRs as well.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7963](https://jira.corp.magento.com/browse/ENGCOM-7963) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento create issue

**Pull request merged**
