### PR TITLE
9130 remove the negative qty block.

### PR DESCRIPTION
**Pull request by saphaljha**
Original PR: https://github.com/magento/magento2/pull/19206

### Fixed Issues (if relevant)

1. magento/magento2#9130: If stock is bellow OutOfStock Threshold, a negative qty is displayed in Product List Page 

### Manual testing scenarios (*)

1. Set qty to 5 for a product, and Out of Stock threshold to 10. Save the product
When browsing that product in the frontend a "Only -5 left" is displayed under "Out of Stock" message.
2. Remove the block if qty is negative.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @saphaljha. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by orlangur** [comment]
QA note: not sure whether this change affects MSI or if it is working correctly when backorders are enabled, please verify thoroughly.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3832](https://jira.corp.magento.com/browse/ENGCOM-3832) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @saphaljha. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.

**Pull request merged**
