### PR TITLE
Allow only valid preferences during setup:di:compile

### LINKED ISSUE #38517: [Issue] Allow only valid preferences during setup:di:compile
This issue is automatically created based on existing pull request: magento/magento2#33161: Allow only valid preferences during setup:di:compile

---------
### Description
The `setup:di:compile` command has exclude lists to avoid loading / compiling dependency injection for 'test' classes. When preferences exist for these excluded classes, any plugins associated with the original classes are (potentially) rendered useless. This is because the child class (preference) can call the original class in a way which does not use Magento's plugin system (ie, `parent::methodName()`). And it's impossible to plugin a class that does not go through Magento's compilation process (to have interceptors created, etc). See https://github.com/magento/security-package/issues/296 for a real-world example of this problem in action.

This pull request began as a change to the regular expressions used to exclude classes, and has grown into expanding the exclude list to cover preferences. Changes include:
- Removal of invalid preferences already within the code-base.
- Alerting (exception) for preferences that do not exist.
- Alerting (exception) for preferences that do not exist because of the existing exclude lists.
- Various bug-fixes for `setup:di:compile`-related classes.

### Related Pull Requests
- https://github.com/magento/inventory/pull/3315
- https://github.com/magento-commerce/magento2-page-builder/pull/304

### Fixed Issues (if relevant)
1. https://github.com/magento/security-package/issues/296

### Manual testing scenarios
1. Create a preference for a class which does not exist. The "for" class can exist or not; the "type" class should not exist.
1. Create a preference for a class which is specifically excluded (like a "test" class). The "for" class can exist or not; the "type" class should exist, but not be eligible for dependency compilation - for example if the path includes `Test`.

Before this pull request, these would silently fail; after this pull request, an error is shown.

### Questions or comments
*None*

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fredden**
### Description
The `setup:di:compile` command has exclude lists to avoid loading / compiling dependency injection for 'test' classes. When preferences exist for these excluded classes, any plugins associated with the original classes are (potentially) rendered useless. This is because the child class (preference) can call the original class in a way which does not use Magento's plugin system (ie, `parent::methodName()`). And it's impossible to plugin a class that does not go through Magento's compilation process (to have interceptors created, etc). See https://github.com/magento/security-package/issues/296 for a real-world example of this problem in action.

This pull request began as a change to the regular expressions used to exclude classes, and has grown into expanding the exclude list to cover preferences. Changes include:
- Removal of invalid preferences already within the code-base.
- Alerting (exception) for preferences that do not exist.
- Alerting (exception) for preferences that do not exist because of the existing exclude lists.
- Various bug-fixes for `setup:di:compile`-related classes.

### Related Pull Requests
- https://github.com/magento/security-package/pull/297
- https://github.com/magento/inventory/pull/3315
- https://github.com/magento/magento2-page-builder/pull/743
  - Which Adobe duplicated to: https://github.com/magento-commerce/magento2-page-builder/pull/304

> Intentionally not using the magic comment which links pull requests together within the Adobe testing system, because these pull requests are related but not part of this change. Do not reinstate that magic comment.

### Fixed Issues (if relevant)
1. https://github.com/magento/security-package/issues/296
2. https://github.com/magento/magento2/issues/38517

### Manual testing scenarios
1. Create a preference for a class which does not exist. The "for" class can exist or not; the "type" class should not exist.
1. Create a preference for a class which is specifically excluded (like a "test" class). The "for" class can exist or not; the "type" class should exist, but not be eligible for dependency compilation - for example if the path includes `Test`.

Before this pull request, these would silently fail; after this pull request, an error is shown.

### Questions or comments
*None*

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38517: Allow only valid preferences during setup:di:compile

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Hi @fredden,
What is a use case for writing plugin on tests?

**Comment by fredden** [comment]
I can't think of a good reason to create a plugin for a class that should only be used in tests. Perhaps the change here should be to exclude Preferences that match these regular expressions as well. I'll investigate further to see if that's something we can include here.

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run Unit Tests

**Comment by fredden** [comment]
@magento run Unit Tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@ihor-sviziev you added the "needs update" label in July (https://github.com/magento/magento2/pull/33161#event-4977662971). What would you like to see updated / changed here?

**Comment by ihor-sviziev** [comment]
Hi @fredden,
I bet that is due to a vast number of failed tests.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
Hello @fredden 
Thank you for your contribution
I see you updated your repositories
I've rerun tests
Let's wait it

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Hello @fredden,

Thanks for the contribution!

Please update the PR branch with the base branch. We are unable to do so. After that, we will pick this PR for further processing.

Meanwhile, we are moving this PR `On Hold`.

Thanks

**Comment by fredden** [comment]
@engcom-Hotel it looks like you have already merged the destination branch into this branch in https://github.com/magento/magento2/pull/33161/commits/d42d631d7d284c4aa593faf8caf5943c1130ab39. What would you like me to do?

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Hello @fredden,

We are unable to run the automated test on this PR. So previously I thought it was due to an outdated PR branch. But it's not like that.

We are in discussion internally on this and will pick this PR whenever automated tests start running on this PR.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by orsinijose** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, WebAPI Tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @fredden,

Thanks for the collaboration!

The PR changes seems good to me, but please resolved the failed automated tests.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]
Approving this PR for further process.

Failed tests seems flaky to me

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
:x: QA not Passed

We have tried to reproduce the issue in the latest 2.4-develop branch with the [inventory](https://github.com/magento/inventory) module installed. But we can get the response from the plugin in production mode as well.

Please refer to the below screenshot:
image

Production Mode;
image

Please also find the custom module to reproduce the issue:
[Magz.zip](https://github.com/magento/magento2/files/14525054/Magz.zip)

Please let us know if we missed anything.

Thanks

**Comment by fredden** [comment]
@engcom-Hotel the reproduction steps listed won't work now that https://github.com/magento/security-package/issues/296 has been fixed (by https://github.com/magento/security-package/pull/297). I have written new reproduction steps which should help show/test the changes being introduced here.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Hello @fredden,

We have tried with the updated reproduction as well. We have made a `preference` with a non-existing class but after running with the PR changes, it is now showing any error while running `bin/magento setup:di:compile` in both `developer` and `production` mode.

Please review the steps, and also please find the custom module for reference:
[Magz.zip](https://github.com/magento/magento2/files/14537948/Magz.zip)

Let us know in case if we missed anything.

Thanks

**Comment by fredden** [comment]
@engcom-Hotel that sounds like you have successfully tested the changes being introduced in this pull request.

**Comment by fredden** [comment]
@engcom-Hotel thanks for letting me know via Slack that you edited your comment here. I have reviewed the module you attached and I can see what's going on. I have updated the testing steps in the pull request description to clarify the error conditions.

Using this example: 
```xml
<preference for="Magento\Customer\Controller\Account\LoginPost"
            type="Magz\Pr33161\Rewrite\Magento\Customer\Controller\Account\LoginPost"
            />
```
- `Magento\Customer\Controller\Account\LoginPost` can exist or not; no error is thrown when it does not exist.
- `Magz\Pr33161\Rewrite\Magento\Customer\Controller\Account\LoginPost` must exist and not be excluded; an error is thrown if that class cannot be found.

**Comment by engcom-Hotel** [comment]
@magento create issue

**Comment by engcom-Hotel** [comment]
Hello @fredden,

Thanks for updating the steps for reproducing the issue. Please find my findings below:

:heavy_check_mark: QA Passed

### Manual testing scenarios
1. Create a preference for a class that does not exist. The "for" class can exist or not; the "type" class should not exist.
2. Create a preference for a class that is specifically excluded (like a "test" class). The "for" class can exist or not; the "type" class should exist, but not be eligible for dependency compilation - for example if the path includes `Test`.

**Actual Result:** :heavy_check_mark:

Before this pull request, these would silently fail; after this pull request, an error is shown.

**After:** :heavy_check_mark: 

image

**Before:** :heavy_multiplication_x:
image

**Tested all the manual scenarios, no impact on regression testing.**

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE, Functional Tests B2B, Functional Tests CE

**Comment by engcom-Hotel** [comment]
Failed tests are flaky, hence moving the PR in `Merge in progress`:

image

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@engcom-Hotel please add successive 2 build result before moving to merge if the tests are flaky. Moving it to Extended testing.

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
Failed tests are different in 2 consecutive runs:

_**Run 1**_
image

_**Run 2**_
image

Hence moving PR to merge in progress

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
As after merging this PR into mainline PR, got PAT failures so merged latest code into this PR and currently we can see SVC, Magento Health Index, Functional and WebAPI tests are failing.. In order to move this PR further the build needs to green or with known issues only. Hence moving it back to Extended Testing.

**Comment by engcom-Hotel** [comment]
Hello @fredden,

I looked into the PR https://github.com/magento-commerce/magento2-page-builder/pull/304, according to its failures, it seems the failures are related to the PR https://github.com/magento/inventory/pull/3315, which is marked as `Related Pull Requests` in this PR. 

Please refer to the below-screenshot of failure for the reference:
image

> Perhaps there are some changes required in [magento-commerce/magento2-page-builder#304](https://github.com/magento-commerce/magento2-page-builder/pull/304) (which is private to Adobe).

As per the above comment, if some changes are required for the PageBuilder PR then you can create a new PR with all the changes in https://github.com/magento/magento2-page-builder repo. We will close this PR https://github.com/magento-commerce/magento2-page-builder/pull/304 and continue with you PR.


Please let us know if we missed anything here.

Thanks

**Comment by engcom-Hotel** [comment]
We are moving this PR `On Hold`, as per this https://github.com/magento/magento2/pull/33161#issuecomment-2154695080.

**Comment by engcom-Hotel** [comment]
Hello @fredden,

We have noticed that this PR has not been updated for a period of long time. Hence we are closing this PR for now.

Let us know when you are ready to work on it again, and we will be happy to re-open it. Thank you for your contribution!

Thanks

**Comment by fredden** [comment]
@engcom-Hotel please re-open this pull request.

**Comment by engcom-Hotel** [comment]
Hello @fredden,

Thank you for your message.

In my previous comment, I mentioned that if changes were required for the PageBuilder PR, a new PR should be created with all the necessary updates in the [magento2-page-builder](https://github.com/magento/magento2-page-builder) repository. We were waiting for this new PR, but since it was not created, we proceeded to close the existing PR.

Could you please go ahead and create the new PR as mentioned? Once it's ready, we'll review and proceed accordingly.

Thank you for your understanding and cooperation.

**Comment by fredden** [comment]
> if changes were required for the PageBuilder PR, a new PR should be created with all the necessary updates in the [magento2-page-builder](https://github.com/magento/magento2-page-builder) repository. We were waiting for this new PR, but since it was not created, we proceeded to close the existing PR.
> 
> Could you please go ahead and create the new PR as mentioned? Once it's ready, we'll review and proceed accordingly.

@engcom-Hotel I already created https://github.com/magento/magento2-page-builder/pull/743 which [you closed](https://github.com/magento/magento2-page-builder/pull/743#issuecomment-1968445112) and replaced with https://github.com/magento-commerce/magento2-page-builder/pull/304 (which I cannot see because it's private-to-Adobe).

As far as I can tell, https://github.com/magento/magento2-page-builder/pull/743/commits/87b8105ded8058d3f737d8cb09e856a0d1c5bf79 (still) contains all the necessary changes for the PageBuilder repository / modules. Please can you (@engcom-Hotel) organise to get this commit merged into the PageBuilder repository. That's what I tried to do in https://github.com/magento/magento2-page-builder/pull/743 which you closed.

I think the main problem with this situation is that the pre-requisites are being combined with this work. They should be merged in separately on their own merits. When they're merged in, I expect the tests to pass here.

**Comment by fredden** [comment]
> They should be merged in separately on their own merits

I have edited the pull request description to remove the magic comment which links pull requests together in the Adobe testing system.

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Hello @fredden,

As per the comment below, it seems that PageBuilder is a prerequisite for this PR. Therefore, we are placing this PR on hold for now and will proceed with it once the PageBuilder PR is merged:

> I think the main problem with this situation is that the pre-requisites are being combined with this work. They should be merged in separately on their own merits. When they're merged in, I expect the tests to pass here.

Thanks

**Comment by fredden** [comment]
@engcom-Hotel the PageBuilder changes have been merged in. Please can you organise for https://github.com/magento/inventory/pull/3315 to be merged in too?

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by fredden** [comment]
It looks like the prerequisite changes have been applied now. @engcom-Hotel please can you remove the 'on hold' label here and progress this through the process.

**Comment by engcom-Hotel** [comment]
We are moving it to `Extended Testing` for further processing.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Comment by engcom-Hotel** [comment]
Failed tests seem falky to me. The last 2 consecutive runs generate different errors. Hence moving this PR to `Merge in Progress`:
image

image

**Comment by engcom-Dash** [comment]
Moving this PR to extended testing since the copyright tag has not been updated in the mentioned files.

**Comment by engcom-Dash** [comment]
@magento run all test

**Comment by engcom-Dash** [comment]
Got a green build so moving it to merge in progress.
image

**Comment by ihor-sviziev** [comment]
Wow. Is it possible again to move PR from "merging in progress" to a real merge within four days? Great! Nice job!

**Pull request merged**
