### PR TITLE
Add missing php doc params to ConvertSerializedDataToJson class constructor

### PR DESCRIPTION
**Pull request by maddumarala**
### Description (*)
Add missing php doc params to ConvertSerializedDataToJson class constructor.
Number,type of parameters used in PHPDoc comment does not match with ones in respective function

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @maddumarala. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hi @maddumarala,
thank you for your contribution!

Could you please also remove the unused import `use Magento\Framework\App\ResourceConnection;` in `app/code/Magento/Quote/Setup/Patch/Data/ConvertSerializedDataToJson.php`.

And add missing `throws` tag for `\Magento\Ui\Model\UiComponentGenerator::generateUiComponent` method:
`@throws \Magento\Framework\Exception\LocalizedException`.

Thank you!

**Comment by maddumarala** [comment]
Hello @dmytro-ch ,
I've added the changes.Please check.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4169](https://jira.corp.magento.com/browse/ENGCOM-4169) has been created to process this Pull Request

**Pull request merged**
