### PR TITLE
#24999 fixed

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)

The action submenu must be align with the action button. As its right property is 0, it will always be at the right side of the screen. So the right property must be auto.

### Fixed Issues (if relevant)

1. magento/magento2#23024: Grid Action Column Design Issues
2. magento/magento2#24999: Action submenu css issue in customer group listing gird

### Manual testing scenarios (*)

1. Add new column in customer group listing grid.
2. Click on the action button.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ghost** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @vishesh-webkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @vishesh-webkul, here is your [Magento instance](https://i-25000-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25000-2-3-develop.instances.magento-community.engineering/admin](https://i-25000-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dmytro-ch** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-25000.instances.magento-community.engineering).
Admin access: [https://pr-25000.instances.magento-community.engineering/admin](https://pr-25000.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hi @vishesh-webkul,
please note the issue is still reproducible.

Screenshot 2019-10-17 at 11 55 17
Screenshot 2019-10-17 at 11 56 58

Thank you!

**Comment by ghost** [comment]
@dmytro-ch  Please confirm once if the css is loaded successfully or not.

**Comment by dmytro-ch** [comment]
There is no block matching the `.action-menu-items` selector.
The test instance is still active, feel free to check it yourself.

**Comment by ghost** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @vishesh-webkul. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @vishesh-webkul, here is your [new Magento instance](https://pr-25000.instances.magento-community.engineering).
Admin access: [https://pr-25000.instances.magento-community.engineering/admin](https://pr-25000.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by ghost** [comment]
As I can see the css is not loaded successfully, please check the given screenshot.

image

**Comment by ghost** [comment]
The right property is till set to 0.

**Comment by dmytro-ch** [comment]
> As I can see the css is not loaded successfully, please check the given screenshot.

It's not applied because there is no block matching the `.action-menu-items` selector.

**Comment by dmytro-ch** [comment]
Closing this PR now due to inactivity.
Feel free to reopen and update if you wish to continue.
Thank you!

**Pull request closed without merging**
