### PR TITLE
Issue/6869

### PR DESCRIPTION
**Pull request by PascalBrouwers**
See https://github.com/magento/magento2/issues/6869

### CODE REVIEW

**Comment by vrann** [comment]
@PascalBrouwers can you please sync the branch with the latest mainline

**Comment by PascalBrouwers** [comment]
Sure, removed all the merge commits and updated to latest develop branch.

**Comment by vrann** [comment]
The mentioned issue #6869 was fixed on the November 23, 2016 and delivered to the mainline. Does this fix still applicable?

**Comment by vrann** [comment]
@PascalBrouwers ^^

**Comment by PascalBrouwers** [comment]
I'll have to check if it's fixed in the develop branch

**Comment by vrann** [comment]
@PascalBrouwers please do, and we will decide on what to do with the PR.

**Comment by vrann** [comment]
@PascalBrouwers as far as I see it was fixed. Closing.

**Pull request closed without merging**
