### PR TITLE
Added observing event trigger "change"

### PR DESCRIPTION
**Pull request by harshvardhanmalpani**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Visit product page where $product->getTypeId()=="configurable"
2. In this page, jQuery can not detect "change" or bind it to hidden input element "selected_configurable_option" but with my changes, developers can observe the change and use it for various purposes

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by harshvardhanmalpani** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @okolesnyk. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @okolesnyk, here is your [Magento instance](https://i-29237-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29237-2-4-develop.instances.magento-community.engineering/admin_4e04](https://i-29237-2-4-develop.instances.magento-community.engineering/admin_4e04)
Login: `b2b5c1c1` Password: `9b43e29a3817`
Instance will be terminated in up to 3 hours.

**Comment by ptylek** [comment]
@harshvardhanmalpani As far as I know, hidden input does not trigger "change" event on change by default. I wouldn't add it.

If you want to observe attribute values being changed on DOM element, why don't you use [Mutation Observer](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver)?

**Comment by ptylek** [comment]
@harshvardhanmalpani I take this 'thumbs up' as a 'yes'.
As similar outcome can be achieved without proposed change in this PR and it is not needed in current implementation of configurable.js, I am closing this PR. 
In case some another solution is proposed in the future, it can be reopened.

**Pull request closed without merging**
