### PR TITLE
Resolve Searching "Categories" is wrong in New Product form when pressing 1 character issue 23697

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

magento/magento2#23697: Resolve Searching "Categories" is wrong in New Product form when pressing 1 character
Reason: 
```
             if (value && value.length < 2) {
                return false;
            }
```

in function filterOptionsList() of app/code/Magento/Ui/view/base/web/js/form/element/ui-select.js

Solution: Need to remove the code.

### Fixed Issues (if relevant)

1. magento/magento2#23697: Resolve Searching "Categories" is wrong in New Product form when pressing 1 character issue 23697

### Manual testing scenarios (*)

1. Add new product
2. Click "Select..." in Categories.
3. Enter the character like "l" or "j" (not match any categories)
4. Show "0 options"

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-23698.instances.magento-community.engineering).
Admin access: [https://pr-23698.instances.magento-community.engineering/admin](https://pr-23698.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-23698.instances.magento-community.engineering).
Admin access: [https://pr-23698.instances.magento-community.engineering/admin](https://pr-23698.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by edenduong** [comment]
Hi @orlangur : Could you please review my pull request?

**Comment by edenduong** [comment]
I believe we can not search "Attribute Set" by one character too.
This will fix for all searching UI-Select element. (Attribute Set, Categories, ...) and Third Party use this component.

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-5597](https://jira.corp.magento.com/browse/ENGCOM-5597) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
