### PR TITLE
Base url validation added in installation process in CLI

### PR DESCRIPTION
**Pull request by konarshankar07**
### Description (*)

This PR will fix the issue around the validation of the base url parameter while running the magento install command
### Manual testing scenarios (*)

1. Run following command
magento setup:install --db-host=localhost --db-name=magento --db-user=magento --db-password=magento \
--admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com \
--admin-user=admin --admin-password=admin123 --language=en_US \
--currency=USD --timezone=America/Chicago --use-rewrites=1 \
--search-engine=elasticsearch7 --elasticsearch-host=es-host.example.com \
--elasticsearch-port=9200

Please make sure base url is not passed as parameter

### Expected Result
Error should be thrown when the base url is missing

### Actual Result
Installation is successfully finished

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by konarshankar07** [comment]
@magento run all tests

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @konarshankar07. Thanks for your fix. What about the cases where the base URL is not set explicitly during installation but set as an environment variable? I.e. `$_ENV['CONFIG__DEFAULT__WEB__SECURE__BASE_URL']`

In this case, the error obviously should not be thrown (otherwise, we may kill a lot of existing CI/CD).

**Comment by konarshankar07** [comment]
Hello @rogyar ...
I'm not able to understand why we are not passing the base_url whilst installing the Magento via CI/CD (Sorry, I don't have any experience with CI/CD). But we can add the interactive question to inform the user that base_url is missing. let me know your thoughts
Thanks

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Hi @konarshankar07,
Now test results a bit improved, now you can see the real failure.

**Comment by rogyar** [comment]
Hi @konarshankar07. The very first thing that comes to my mind is to add an additional check if the URL is set as env. variable. 
If the URL is not set anywhere, throw the error. How does that sound?

**Comment by sidolov** [comment]
@konarshankar07  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
