### PR TITLE
Fixed issue: Add to Bag within "Click for price" popup not working.

### LINKED ISSUE #30356: Add to Cart button within "Click for price" popup not working.
### Preconditions (*)

1. Magento 2.4-develop
2. Magento_Msrp module is enabled.

### Steps to reproduce (*)

1. *Stores => Configurations => Sales => Minimum Advertised Price*  settings *Enable MAP: Yes*and *Display Actual Price : On Gesture*
2. For any product *Minimum Advertised Price* is set higher price then *Price*.

### Expected result (*)

1. Add to cart within popup on product listing should add that product to cart.

### Actual result (*)

1. Add to cart within popup on product listing is actually doing nothing and reloading the page.
Peek 2020-10-15 15-28

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by sanganinamrata**
### Description (*)
 Fixed Add to cart functionality within *Click for price* popup on any product listings.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30356

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento run Static Tests

**Review by rogyar — COMMENTED** [review]
Hi @sanganinamrata. Thank you for your contribution. Could I ask you to cover your changes with an MFTF test, please? 
The test will go through the "Steps to reproduce" described in the original issue and assert that we meet the expected behavior. 

Thank you!

**Comment by sanganinamrata** [comment]
@rogyar Sorry for the late reply, Actually I haven't written the MFTF test till now. But I've identified this issue on Magento 2.3 and 2.4 both and tested it with the above solution.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @sanganinamrata, thanks for your contribution.

I'm moving this PR to change requested column since it requires test coverage.

@engcom-Foxtrot @engcom-Hotel @engcom-Charlie can you help with test coverage on this?

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by gabrieldagama — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8366](https://jira.corp.magento.com/browse/ENGCOM-8366) has been created to process this Pull Request

**Comment by sanganinamrata** [comment]
@rogyar Will you please add `hacktoberfest-accepted` label to this PR? This event is about to finish. Without this label to my PR, I'll be eliminated from that challenge. :)

**Comment by engcom-Alfa** [comment]
@magento give me test instance

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @sanganinamrata 
During testing, we faced some issues.

_**Problem:**_ Add to cart within popup from the _Wishlist_ and _Compare Products_ pages are actually doing nothing.

**Manual testing scenario:**

1. Go to Admin -> Stores -> Configuration -> Sales -> Sales -> Minimum Advertised Price and set:

- **Enable MAP** to **Yes**
- **Display Actual Price** to **On Gesture**

2. For any product _Minimum Advertised Price_ is set higher price than _Price_.
3. Log in as customer on Storefront;
4. Add product to Wishlist;
5. From the wishlist page click on the **Add to cart** within popup

**Actual Result:** :heavy_multiplication_x: Add to cart within popup on the wishlist page is actually doing nothing

Peek 2020-10-23 10-06

The same problem and with Compare Products

**Actual Result :** :heavy_multiplication_x: Add to cart within popup on the compare products page is actually doing nothing

Peek 2020-10-23 10-07

@sanganinamrata Could you take a look?
Thanks!

**Comment by sanganinamrata** [comment]
@engcom-Alfa Hi,

Thanks for pointing it out to me. I checked on fresh `Magento 2.3 & 2.4`. `Click for Price` is not working for `wishlist and compare products` already. I'll fix it by tomorrow.

**Comment by sanganinamrata** [comment]
@engcom-Alfa Hi,

As you mentioned above, I've fixed this issues to all areas as listed below:
> Category page, 
> Search result page, 
> My Wish-list page, 
> Compare products page, 
> My Wish-list section on 2 column pages sidebar.

Let me know if any more updates you want from me.

Thank you.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@sanganinamrata Could you please fix failed `Static Tests`?
Thanks!

**Comment by engcom-Charlie** [comment]
@sanganinamrata I'll fix failed tests.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by rogyar — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
@magento give me test instance

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @sanganinamrata . 

Unfortunately, adding product to cart within the "**Click for price**" popup is not working for **_Compare Products_**

**Manual testing scenario:**

1. Go to Admin -> Stores -> Configuration -> Sales -> Sales -> Minimum Advertised Price and set:

- **Enable MAP** to Y**es**
- **Display Actual Price** to **On Gesture**

2. For any product Minimum Advertised Price is set higher price than Price.
3. Go to Storefront;
4. Add product to compare
5. From the compare products page click on the **Add to cart** within popup;

**Actual Result:** :heavy_multiplication_x: Add to cart within popup on the compare products page is actually doing nothing

Peek 2020-11-02 11-12

@sanganinamrata Could you take a look?
Thanks!

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8366](https://jira.corp.magento.com/browse/ENGCOM-8366) has been created to process this Pull Request

**Comment by engcom-Charlie** [comment]
Hi, @sanganinamrata I will fix adding from the Compare Products list.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by koushikch7 — APPROVED** [review]

**Comment by engcom-Delta** [comment]
@sanganinamrata Please resolve with the conflicts to move ahead with this PR

**Review by engcom-Delta — CHANGES_REQUESTED** [review]
Please resolve the conflicts on the PR

**Pull request closed without merging**
