### PR TITLE
magento/magento2#37107 Replace Deprecated Output Escaping

### LINKED ISSUE #37107: [Issue] Chore: Catalog Widget - Replace Block Escaping with Escaper
This issue is automatically created based on existing pull request: magento/magento2#37082: Chore: Catalog Widget - Replace Block Escaping with Escaper

---------
### Description (*)
Refactors the `Magento_CatalogWidget` module to replace `$block` escaping functions with `$escaper` escaping functions.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by BeggiNN**
### Description (*)

Refactors the Magento_CatalogWidget module to replace $block escaping functions with $escaper escaping functions.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#37107

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by BeggiNN** [comment]
@magento run Functional Tests CE

**Comment by BeggiNN** [comment]
@magento run Functional Tests CE, Integration Tests

**Comment by BeggiNN** [comment]
@magento run Functional Tests CE, Integration Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Integration Tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @BeggiNN,

Thanks for the contribution!

Please fix the integration test failures, it seems due to these PR changes.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run Integration Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE, Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Comment by engcom-Hotel** [comment]
The integration test has been clear now. And the `Functional Tests EE` failure seems flaky to me. Hence moving this PR further.

Thanks

**Comment by engcom-Delta** [comment]
@magento run Functional Tests EE

**Comment by engcom-Delta** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

1. Verify the deprecated functions in lib/internal/Magento/Framework/View/Element/AbstractBlock.php class 
2. Verify the function defined in lib/internal/Magento/Framework/Escaper.php class

**After:** :heavy_check_mark:  

In the codebase of the 2.4-develop branch some of the functions are marked as deprecated from the lib/internal/Magento/Framework/View/Element/AbstractBlock.php class and the function defined in class lib/internal/Magento/Framework/Escaper.php with the same name will be used from now

Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
The Functional EE test failures are different in recent 2  successive builds. They neither part of PR nor failing because of the PR changes, hence moving it to Merge in Progress.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37982/06121562520563a27c14a61c90d9f20c/Functional/allure-report-ee/index.html#categories

image

**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37982/66116c6156dcd72c71a66d0c24065894/Functional/allure-report-ee/index.html#categories/6ca9d315ebd9ab54dbe1fb9148ebdc1f/17a9cfbd1ca31362/

image

**Pull request merged**
