### PR TITLE
ProductRepository GetById use correct cache key

### LINKED ISSUE #38384: ProductRepository function GetById does not create the correct cache key
### Preconditions and environment

- 2.4.6-p3

The ProductRepository's function `getById` does not create the correct cache key based on $editMode and $storeId.
The $storeId can be passed as string and int. But before the cache key is created, the $storeId is not parsed to an integer.

See difference with the `get` function.

`get`
```
$cacheKey = $this->getCacheKey([$editMode, $storeId === null ? $storeId : (int) $storeId]);
```

`getById`
```
$cacheKey = $this->getCacheKey([$editMode, $storeId]);
```

### Steps to reproduce

Use the product repository in a class

Retrieve the product by using the repositories method 'getById' with same parameters except the $storeId should be once string and the other time it should be and integer

```
$product = $this->productRepository->getById(1, false, '1');
$product = $this->productRepository->getById(1, false, 1);
```

Product is retrieved twice from database

### Expected result

When using the `getById` method with same store value (string or int). The second time the product should be retrieved from memory.

### Actual result

Product is retrieved twice

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by MaximGns**
### Description (*)
The ProductRepository's function getById does not create the correct cache key based on $editMode and $storeId.
The $storeId can be passed as string and int. But before the cache key is created, the $storeId is not parsed to an integer.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38384

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by MaximGns** [comment]
@magento run all tests

**Comment by MaximGns** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Echo** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** 

**Manual testing scenario:**

Follow steps from [comment](https://github.com/magento/magento2/issues/38384#issue-2101791870)

**Before:** :heavy_multiplication_x: 
Screenshot 2024-04-19 at 4 03 18 PM

**After:** :heavy_check_mark:  
Screenshot 2024-04-19 at 4 09 55 PM


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B,Functional Tests CE ,WebAPI Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by onlinebizsoft** [comment]
@engcom-Hotel which version should this update be included ?

**Comment by engcom-Hotel** [comment]
Hello @onlinebizsoft,

As per the JIRA [AC-10947](https://jira.corp.adobe.com/browse/AC-10947), the fix is released in 2.4.8-beta1.

Thanks

**Pull request merged**
