### PR TITLE
[Backport] Changes-Schedule-Update-Form-filed-misalign-2.2

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Description (*)

Original Issue: #20402
### Fixed Issues (if relevant)

1. magento/magento2#20403: Schedule update from filed misalignment in 768 x 1147 resolution
2. Magento 2.2.x

### Manual testing scenarios (*)

1. Login to Admin panel => Catalog => Categories => Navigate any category => Schedule Design Update section
2. Schedule update from field misalignment in 768 x 1147 resolution

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [new Magento instance](https://pr-20404.instances.magento-community.engineering).
Admin access: [https://pr-20404.instances.magento-community.engineering/admin](https://pr-20404.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sivaschenko** [comment]
Hi @amol2jcommerce thanks for the contribution, can you please port this PR to 2.3-develop branch as we'd like to merge it to 2.3 first to keep branches in sync.

**Comment by amol2jcommerce** [comment]
Hi @sivaschenko , 
Our pull request for 2.2-develop branch same changes are present in the 2.3-develop & pull request is #20403

**Comment by amol2jcommerce** [comment]
Hi @sivaschenko @magento-engcom-team please review.

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-4245](https://jira.corp.magento.com/browse/ENGCOM-4245) has been created to process this Pull Request

**Pull request merged**
