### PR TITLE
Update InstallSchema.php

### PR DESCRIPTION
**Pull request by markoweb**
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=9134) <br/>All committers have signed the CLA.

**Comment by adragus-inviqa** [comment]
Yep, keep using those arrays for important stuff, people. You just love typing, don't you?! 👍 

_(You're not the target here, @markoweb.)_

**Comment by orlangur** [comment]
@adragus-inviqa, +1, some
```
$table->addColumn('first_name', 'string')
            ->setLength('255')
            ->setNotnull(true);
```
would be way better here ;)

Is there some community module integrating Doctrine into Magento 2 maybe?

**Comment by adragus-inviqa** [comment]
Yeah, well, remember [this](https://github.com/magento/magento2/pull/4279)? That didn't go too well, did it?

**Comment by okorshenko** [comment]
@markoweb thank you for your contribution. Unfortunately, we can not accept this PR because we are not allowing changes in existing setup/upgrade scripts.
If you would like to fix this issue, please, bump module setup version and create upgrade script for it. In this case, everyone will be updated. But if we will update existing script, only new installations will get this update.

Please, submit new pull request once ready.

Thank you.

**Comment by orlangur** [comment]
> because we are not allowing changes in existing setup/upgrade scripts

Are you sure about that? Because I saw some changes by core team members where both setup and upgrade scripts were changed.

I do agree that changing only setup is not acceptable, but want to understand whether in this PR just upgrade part was missing or also change to setup was incorrect.

**Pull request closed without merging**
