### PR TITLE
Fix empty cart validation

### PR DESCRIPTION
**Pull request by wojtekn**
### Description

This PR prevents from running UpdateItemQty validation before Clear Shopping Cart action is triggered. In the other case validation breaks for use case in which product existing in cart went out of stock in the meantime.

### Fixed Issues

1. magento/magento2#21294

### Manual testing scenarios

1. Add simple product in backend, set positive quantity and Stock Status = In Stock
2. Open another browser tab and access product in frontend
3. Add product to cart
4. Navigate to cart
5. Enable "Clear Shopping Cart" button by running this code in console:
  `jQuery('.action.clear').show()`
  It's hidden in CSS for some reason.
6. Back to product form in the backend
7. Set Stock Status for product to Out of Stock, save
8. Click "Clear Shopping Cart" button in the cart in frontend

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21295) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @wojtekn. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by wojtekn** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @wojtekn. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @wojtekn, here is your [new Magento instance](https://pr-21295.instances.magento-community.engineering).
Admin access: [https://pr-21295.instances.magento-community.engineering/admin](https://pr-21295.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by wojtekn** [comment]
Issue doesn't reproduce on test instance based on PR changes.

**Comment by swnsma** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swnsma. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swnsma, here is your [Magento instance](https://i-21295-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21295-2-3-develop.instances.magento-community.engineering/admin](https://i-21295-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by swnsma — CHANGES_REQUESTED** [review]
Hi @wojtekn,

Thank you for you contribution!
1. Please check failed JS static tests.
2. Could you remove hard-coded jQuery selected from the component and pass it like variable:
https://github.com/magento/magento2/blob/94383aa66cf8a5499399f6e21300bbf73b3384f2/app/code/Magento/Checkout/view/frontend/templates/cart/form.phtml#L28

**Comment by swnsma** [comment]
@wojtekn, thanks!

I will check after Travis report will be ready.

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-4362](https://jira.corp.magento.com/browse/ENGCOM-4362) has been created to process this Pull Request

**Pull request merged**
