### PR TITLE
fixed typo

### LINKED ISSUE #6994: Typo in message when removing coupon from cart
There is a typo in the message being displayed to a user when removing a coupon code. One 'l' when it should be two in 'cancelled'.

`\vendor\magento\module-checkout\Controller\Cart\CouponPost.php` line 137 is currently:

`$this->messageManager->addSuccess(__('You canceled the coupon code.'));`

And should be:
`$this->messageManager->addSuccess(__('You cancelled the coupon code.'));`

### PR DESCRIPTION
**Pull request by jermenkoo**
Fixed #6994

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=6998) <br/>All committers have signed the CLA.

**Comment by shanevbg** [comment]
#6994 was not a real typo, both spellings are correct!
http://grammarist.com/spelling/cancel/
In American English, the verb cancel is usually inflected canceled and canceling—with one l. This is not a rule, however, and exceptions are easily found. In varieties of English from outside the U.S., including Canadian, British, and Australian English, cancelled and cancelling are the preferred spellings.

**Comment by jermenkoo** [comment]
I would claim that we should try to be consistent as well. (even though is a minor, negligible issue).

**Comment by shanevbg** [comment]
Just pointing out that Americans will complain that it's a typo after you fix it for other countries.  Much like colour and color.  If the goal is to use British spellings everywhere then you should be consistent.
http://grammarist.com/spelling/color-colour/
Color and colour are different spellings of the same word. Color is the preferred spelling in American English, and colour is preferred in all other main varieties of English.

**Review by shanevbg — COMMENTED** [review]
I think "fixing" this will cause confusion.  It would be better to create a language pack for GB_eng

**Comment by almarchenko** [comment]
@jermenkoo  Thanks for your input! We will discuss the best solution and let you know!

**Comment by okorshenko** [comment]
@jermenkoo Thank you for your contribution. 
After several internal discussions, we agreed to keep Americal English variant of this word. Closing this PR

**Pull request closed without merging**
