### PR TITLE
MAGETWO-59282: Corrected previous fix to this ticket.

### PR DESCRIPTION
**Pull request by wardcapp**
Do not set store id on the response when it was not set in the first place.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=6990) <br/>All committers have signed the CLA.

**Comment by okorshenko** [comment]
Hi @wardcapp 
Could you please fix broken unit tests so that we can proceed with PR acceptance? Thank you

**Comment by wardcapp** [comment]
Hello @okorshenko, I was able to address some of the broken unit tests, but for some or other reason the login unit test appears to be broken (which does not seem to relate to the changes made within the PR):



`There was 1 failure:`
`1) Magento\User\Model\UserTest::testLoginsAreLogged`
`Failed asserting that false is true.`
`/home/travis/build/magento/magento2/dev/tests/integration/testsuite/Magento/User/Model/UserTest.php:286`
                                                                         
`FAILURES!  `                                                              
`Tests: 5189, Assertions: 12884, Failures: 1, Incomplete: 73, Skipped: 75.`

Locally (PHP 7.0.21, Ubuntu 16.04.1) these unit tests are succeeding:

`# ../../../vendor/bin/phpunit` `../../../dev/tests/integration/testsuite/Magento/User/Model/UserTest.php
PHPUnit 4.1.0 by Sebastian Bergmann.`

`Configuration read from /var/www/website/dev/tests/integration/phpunit.xml.dist`

`.................................`

`Time: 55.99 seconds, Memory: 70.00MB`

`OK (33 tests, 68 assertions)`

Might have been reported before (are others experiencing the same issue?) and will try look into it, but it is currently unclear why this specific test is failing on the CI server.

**Comment by Ctucker9233** [comment]
@magento-team This doesn't appear to be merged into 2.2.7. Is there a reason?

**Pull request merged**
