### PR TITLE
Replace intval() function by using direct type casting to (int)

### PR DESCRIPTION
**Pull request by mage2pratik**
### Description (*)

Changed intval($val) to (int)$val, since it is faster.

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4552](https://jira.corp.magento.com/browse/ENGCOM-4552) has been created to process this Pull Request

**Review by orlangur — CHANGES_REQUESTED** [review]
@mage2pratik we don't need such kind of change performed manually. Is was already done all over the code but without a proper test it will appear back again and again.

Feel free to prepare a PR containing `php-cs-fixer` used the same way we already use `phpcs`: https://github.com/magento/magento2/blob/2.3-develop/dev/tests/static/testsuite/Magento/Test/Php/LiveCodeTest.php#L269

**Comment by mage2pratik** [comment]
Hi @orlangur I've checked whole 2.3-develop repository and found optimization require in single lib file.
And JFI, I found this issue using php-cs-fixer "modernize_types_casting".
Kindly review this PR and proceed, if solution is correct. Thanks :)

**Comment by orlangur** [comment]
@mage2pratik again, without a proper static test such contribution does not make sense. It was introduced recently in https://github.com/magento/magento2/commit/7c55811a43ae0a9d80cc3c6544c42088bfe0d790#diff-c050202c296c21a2ac7332d04709c599 and such situation will repeat until we prevent it.

**Pull request closed without merging**
