### PR TITLE
Fixed #24386: shipping address lost on admin create new order page.

### LINKED ISSUE #24386: shipping address lost so can not change shipping address
shipping address lost so can not change the shipping address

### Preconditions (*)
- Magento 2.3.2
- create the customer from admin
- add 3-4 additional addresses for that customer

### Steps to reproduce (*)
1. Login to Admin -> Sales -> Orders -> Create New Order  -> Select Customer -> Go to Address Information 
2. Select different Address For billing Address
3. Uncheck the "Same As Billing Address" for shipping address
4. Change the billing address again 
5. Check the "Same As Billing Address" for shipping address
6. See the shipping address section lost at one point

### Expected result (*)
The shipping address section should not be lost.
If admin wants to update shipping again then how can they do it as the shipping section is lost.

### Actual result (*)
Peek 2020-08-05 16-00

### PR DESCRIPTION
**Pull request by mahesh-rajawat**
Fixed shipping address lost on Admin create new order page. 

### Fixed Issues (if relevant)

1. #24386

### Manual testing scenarios (*)

1. Followed all steps mentioned in #24386 .
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @maheshWebkul721,
Could you review and fix functional test failures?

**Comment by mahesh-rajawat** [comment]
@ihor-sviziev , fixed functional test related to this PR, current functional test failure is not related to this PR. Please check it.

**Comment by ihor-sviziev** [comment]
@magento Functional Tests build

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests build

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @maheshWebkul721,
Looks like success message isn't appear after applying coupon code after your changes, you can see all steps here:
https://testing-service.magento-community.engineering/reports/magento/magento2/pull/24398/bf84bdbdd9a5b5af672fb80f88bbecd2/Functional/allure-report-ce/index.html#categories/24cbb1c3f04ea9a25d082b783dbb59c7/f67c67d03bb91494/

Could you adjust your code to fix this issue?

**Comment by ihor-sviziev** [comment]
@maheshWebkul721 I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
