### PR TITLE
setAttributeSetFilter accepts both integer and integer-array

### PR DESCRIPTION
**Pull request by NiklasBr**
### Description (*)
Short Doc block fix to keep param info up to date with its method

### Fixed Issues (if relevant)
n/a

### Manual testing scenarios (*)
You can try it in an editor with codesense and suplly an array to the method and watch it complain that the method only accepts an integer

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22133) <br/>All committers have signed the CLA.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4658](https://jira.corp.magento.com/browse/ENGCOM-4658) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@NiklasBr thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
