### PR TITLE
[MFTF] Refactoring AdminMassOrdersHoldOnPendingAndProcessingTest

### LINKED ISSUE #31516: [Issue] [MFTF] Refactoring AdminMassOrdersHoldOnPendingAndProcessingTest
This issue is automatically created based on existing pull request: magento/magento2#31508: [MFTF] Refactoring AdminMassOrdersHoldOnPendingAndProcessingTest

---------
### Description (*)
A new test has been created to improve execution time.
The old "AdminMassOrdersHoldOnPendingAndProcessingTest" has been deprecated.

### Manual testing scenarios (*)

1. Create two orders
2. Invoice the second order
3. Go to the Orders Grid
4. Hold both orders via mass update
5. Verify the result

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
A new test has been created to improve execution time.
The old "AdminMassOrdersHoldOnPendingAndProcessingTest" has been deprecated.

### Manual testing scenarios (*)

1. Create two orders
2. Invoice the second order
3. Go to the Orders Grid
4. Hold both orders via mass update
5. Verify the result

### Resolved issues:
1. [x] resolves magento/magento2#31516: [MFTF] Refactoring AdminMassOrdersHoldOnPendingAndProcessingTest

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Review by rogyar — APPROVED** [review]
Good job!

The failing tests are not related to the current changeset.

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8669](https://jira.corp.magento.com/browse/ENGCOM-8669) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
Manual QA is not applicable for MFTF Refactoring PR-s. Moving it to _Extended Testing_ column

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
