### PR TITLE
Implement ActionInterface for /swatches/ajax/media

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
This is a part of the process of introducing implementations of `ActionInterface`.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run  Functional Tests B2B, Functional Tests EE

**Review by ihor-sviziev — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7171](https://jira.corp.magento.com/browse/ENGCOM-7171) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Kilo** [comment]
Failed functional test not related to the changes in this PR

**Comment by ihor-sviziev** [comment]
@engcom-Kilo could you explain why this PR was moved to "to approve" column?

**Comment by engcom-Kilo** [comment]
> @engcom-Kilo could you explain why this PR was moved to "to approve" column?

Seems can be problem with Backward compatible
[https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/)

**Comment by lbajsarowicz** [comment]
@engcom-Kilo But we're moving from 2.3 to 2.4
There's no better time for such change.

**Comment by engcom-Kilo** [comment]
> @engcom-Kilo But we're moving from 2.3 to 2.4
> There's no better time for such change.

yes,
moved to Marge in Progress

**Review by ihor-sviziev — DISMISSED** [review]

**Review by slavvka — CHANGES_REQUESTED** [review]
@lbajsarowicz please resolve the conflicts and re-run tests after upgrade to PHP 7.4

**Review by ihor-sviziev — DISMISSED** [review]

**Comment by ihor-sviziev** [comment]
Moved to on hold, the same reason as other PRs

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7171](https://jira.corp.magento.com/browse/ENGCOM-7171) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
FYI this PR was moved to "oh hold" due to internal discussions, reason the same as there https://github.com/magento/magento2/pull/27538#issuecomment-624891873

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @lbajsarowicz ,
We finally have final decision, it clearly described here https://github.com/magento/magento2/pull/27296#pullrequestreview-418541438.

Could you update to bring back the extending of abstract action?

**Comment by lbajsarowicz** [comment]
If anyone else wants to pick this, feel free to take my code and continue.
I won't be available to handle that in next 2 - 3 weeks.

**Pull request closed without merging**
