### PR TITLE
Allow overriding block templates through block arguments

### PR DESCRIPTION
**Pull request by LordZardeck**
### Description (*)

Without checking if the template is set already, this causes the template attribute to always override any arguments set, preventing you from changing the template without using the deprecated action node. This PR makes the simple change of checking if the template is already set before attempting to overwrite it with the attribute template.

### Fixed Issues (if relevant)

1. magento/magento2#3356: XML syntax to change block's template

### Manual testing scenarios (*)

1. Use a reference block node for a block that defines a template as an attribute (such as checkout.customer.sku in Magento_AdvancedCheckout) and define the template as an argument:
```xml
<referenceBlock name="checkout.customer.sku">
    <arguments>
        <argument name="template" xsi:type="string">MyCompany_MyModule::widget/sku.phtml</argument>
    </arguments>
</referenceBlock>
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @LordZardeck. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3654](https://jira.corp.magento.com/browse/ENGCOM-3654) has been created to process this Pull Request

**Comment by sdzhepa** [comment]
Hello @LordZardeck 

During testing for this PR our QA engineer found an issue related to it
Could you please have a look and provide required fixes?

Please see QA comment after testing:

PR doesn't fix issue #3356

**Manual testing scenario:**
1. Create custom module
2. Add layout file:
```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="copyright">
            <action method="setTemplate">
                <argument name="template" xsi:type="string">Foo_Bar::copyright.phtml</argument>
            </action >
       </referenceBlock>
    </body>
</page>

```
3. Check home page
**Actual Result:** OK, Copyright in footer is changed


4. Change layout file:
```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="copyright">
            <arguments>
                <argument name="template" xsi:type="string">Foo_Bar::copyright.phtml</argument>
            </arguments>
       </referenceBlock>
    </body>
</page>

```
5. Check home page
**Actual Result:** NOT OK, Copyright in footer is missed.

**Comment by sidolov** [comment]
Hi @LordZardeck , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
