### PR TITLE
Fixed date validation issue in DateRange filter component

### PR DESCRIPTION
**Pull request by konarshankar07**
### Description (*)

This PR will fix the date validation issue for dateRange component.

### Fixed Issues (if relevant)

1. https://github.com/magento/adobe-stock-integration/issues/881: 500 (Internal server error) appears in Developer Console if try to apply not valid data in date field (Media Gallery, Uploaded Date or Modification Date filters)

### Manual testing scenarios (*)

Steps for reproducing this issue is in https://github.com/magento/adobe-stock-integration/issues/881 ticket

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
Ignore failing **Functional Tests** and **Integration Tests** as it's caused by date used in the tests.

Focus on fixing **Static Tests**

**Comment by rogyar** [comment]
Hi @konarshankar07. 

Could I also ask you to cover your change by a small unit test, please? 

Thank you!

**Comment by rogyar** [comment]
Hi @konarshankar07. Please, take a look at the failing static tests.

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-6545](https://jira.corp.magento.com/browse/ENGCOM-6545) has been created to process this Pull Request

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
The 500 Internal server error doesn't appear in Developer Console 
But: 
1. The filter doesn't seem to be working. I have one image in the Media Gallery that was added today
And when I select the _Uploaded Date - To_ a day in the past, the image that had been added today is found
date_filter

2. When _"1234"_ is typed into _From_ or _To_ field and applied, it applies "**Invalid date**"  
So, you can apply date range _From_ **Invalid date** _To_ **Invalid date**
Nevertheless, the today's date applied it _From_ and _To_ fields
invalid_date

**Comment by konarshankar07** [comment]
Thanks @engcom-Bravo  for the feedback. I will fix this issue ASAP

**Comment by konarshankar07** [comment]
This PR is no longer required

**Pull request closed without merging**
