### PR TITLE
Missing Font CSP Paylater Popup

### LINKED ISSUE #38624: [Issue] Missing Font CSP Paylater Popup
This issue is automatically created based on existing pull request: magento/magento2#37401: Missing Font CSP Paylater Popup

---------
Paylater Popup: 
Refused to load the font 'https://www.paypalobjects.com/webstatic/mktg/2014design/font/PP-Sans/PayPalSansBig-Medium.woff' because it violates the following Content Security Policy directive

Update:
Refused to frame 'https://www.paypalobjects.com/' because it violates the following Content Security Policy directive:

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by in-session**
Paylater Popup: 
Refused to load the font 'https://www.paypalobjects.com/webstatic/mktg/2014design/font/PP-Sans/PayPalSansBig-Medium.woff' because it violates the following Content Security Policy directive

Update:
Refused to frame 'https://www.paypalobjects.com/' because it violates the following Content Security Policy directive:

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38624: Missing Font CSP Paylater Popup

### CODE REVIEW

**Comment by mrtuvn** [comment]
Here is one example for speed-up improve merge process. When risk low and changes small i think we can have option merge  for some maintainer can ability to merge immediately(Require at least two reviewer accept)

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento create issue

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Charlie** [comment]
Hi @in-session,

Thank you for your contribution!

In order to proceed further on this PR, I have followed the below steps on 2.4-develop
	1. Setup Paypal Express checkout in admin
	2. Set Enable In-Context Checkout Experience to "Yes"
	3. In Advertise PayPal Pay Later section select "Yes" for "Enable PayPal Pay Later". Enabled it on Home page, Catalog Product Page 
	4. Visit storefront
	5. On home page we can see PayPal pay later button. Clicked on it.

### :heavy_check_mark: QA Passed

**Before:** :heavy_multiplication_x: 
Got errors in console about woff font because of violating CSP
image


**After:** :heavy_check_mark:  
Not getting error about WOFF
image

Since the build is failing, currently moving it further in Extended Testing.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run WebAPI Tests

**Comment by engcom-Charlie** [comment]
The functional B2B and EE failures are different in recent 2 runs they seems to be flaky. Few failures are repetitive but they are known issues.

Repetitive failures in B2B with open issue is: 
1. [ACQE-6438](https://jira.corp.adobe.com/browse/ACQE-6438) - StorefrontPropertiesOfAProductAttributeTest

**Functional B2B:  Run1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37401/685d3ca21e4d3e195b993c9a4244c759/Functional/allure-report-b2b/index.html#categories
image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37401/f48291e355660b57a40b38dac9743e6c/Functional/allure-report-b2b/index.html#categories

image


**Functional EE:  Run1:**  
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37401/dadd50cbf4d537b95cf5624d8ecd2c78/Functional/allure-report-ee/index.html#categories
image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37401/d488c56ff5b0e537b36fbb2be10fb1de/Functional/allure-report-ee/index.html#categories
image

Repetitive failures in EE with open issues are:
1. [ACQE-6438](https://jira.corp.adobe.com/browse/ACQE-6438) - StorefrontPropertiesOfAProductAttributeTest
2. [ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331) - StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest

**Comment by engcom-Charlie** [comment]
The WebAPI failure in recent 2 build is a known issue.  It is not related to this PR. Hence moving the PR to Merge in Progress now.
[AC-11750 ](https://jira.corp.adobe.com/browse/AC-11750)- testGetCustomerDescendingSortedOrders

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37401/fc7629b184bedd5d43176b82573b838b/WebApi/console-error-logs.html
image

image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37401/00a2ee523d034ce33c850d2a9736b9b6/WebApi/console-error-logs.html
image

**Pull request merged**
