### PR TITLE
[32031][To 2.4-develop] Marked Framework Model, Module, Mview and ObjectManager interfaces as API

### LINKED ISSUE #32031: Mark Framework Model, Module, Mview and ObjectManager interfaces as API
The following interfaces should be marked as API in 2.4-develop branch

1. lib/internal/Magento/Framework/Model/Entity/ScopeInterface.php
1. lib/internal/Magento/Framework/Model/Entity/ScopeProviderInterface.php
1. lib/internal/Magento/Framework/Model/EntitySnapshot/AttributeProviderInterface.php
1. lib/internal/Magento/Framework/Model/ResourceModel/Db/VersionControl/RelationInterface.php
1. lib/internal/Magento/Framework/Model/ResourceModel/Type/Db/ConnectionFactoryInterface.php
1. lib/internal/Magento/Framework/Module/ModuleListInterface.php
1. lib/internal/Magento/Framework/Mview/ConfigInterface.php
1. lib/internal/Magento/Framework/Mview/ProcessorInterface.php
1. lib/internal/Magento/Framework/Mview/View/ChangelogInterface.php
1. lib/internal/Magento/Framework/Mview/View/CollectionInterface.php
1. lib/internal/Magento/Framework/Mview/View/State/CollectionInterface.php
1. lib/internal/Magento/Framework/Mview/View/StateInterface.php
1. lib/internal/Magento/Framework/Mview/View/SubscriptionInterface.php
1. lib/internal/Magento/Framework/Mview/ViewInterface.php
1. lib/internal/Magento/Framework/ObjectManager/ConfigCacheInterface.php
1. lib/internal/Magento/Framework/ObjectManager/ConfigInterface.php
1. lib/internal/Magento/Framework/ObjectManager/ConfigLoaderInterface.php
1. lib/internal/Magento/Framework/ObjectManager/DefinitionInterface.php
1. lib/internal/Magento/Framework/ObjectManager/DynamicConfigInterface.php
1. lib/internal/Magento/Framework/ObjectManager/FactoryInterface.php
1. lib/internal/Magento/Framework/ObjectManager/NoninterceptableInterface.php
1. lib/internal/Magento/Framework/ObjectManager/RelationsInterface.php

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixes #32031
### Fixed Issues (if relevant)

1. Fixes magento/magento2#32031>

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by danielrussob** [comment]
@magento run Functional Tests B2B, Integration Tests

**Comment by danielrussob** [comment]
I confirm that this PR is just a code cleanup / marked as API some class. We are waiting for tests.

**Comment by danielrussob** [comment]
I confirm that all files mentioned in issue (https://github.com/magento/magento2/issues/32031) are covered

**Comment by Usik2203** [comment]
@magento run Functional Tests B2B, Integration Tests

**Review by aleron75 — APPROVED** [review]
For QA: the failing functional test seems flaky

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Review by danielrussob — APPROVED** [review]

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@Usik2203 could you please re-create branch (from actual 2.4-dev) and PR? For some reason, I cannot update this PR.

**Review by engcom-Foxtrot — CHANGES_REQUESTED** [review]
@Usik2203 could you please re-create branch (from actual 2.4-dev) and PR? For some reason, I cannot update this PR.

**Comment by Usik2203** [comment]
Hi @engcom-Foxtrot 
PR was recreated from actual 2.4-develop branch 
New PR https://github.com/magento/magento2/pull/32804

I am closing this one favour of   https://github.com/magento/magento2/pull/32804
Thanks!

**Pull request closed without merging**
