### PR TITLE
Replace repetitive actions with Action Groups in AdminUpdateFlatCategoryNameAndDescriptionTest

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Fixed Issues (if relevant)
Test is refactored according to the best practices followed by MFTF.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by Den4ik** [comment]
@magento run Functional Tests EE

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-9324](https://jira.corp.magento.com/browse/ENGCOM-9324) has been created to process this Pull Request

**Review by Den4ik — APPROVED** [review]

**Pull request merged**
