### PR TITLE
Fix docBlock for hasInvoices(), hasShipments(), hasCreditmemos()

### PR DESCRIPTION
**Pull request by nuzil**
### Description
Small improvements of docBlock for app/code/Magento/Sales/Model/Order.php docBlock description.
hasInvoices(), hasShipments(), hasCreditmemos() returns **int** and not **bool**

### Manual testing scenarios
No testing scenarios, just docBlock changed

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @nuzil. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
They should be boolean even though they actually returning count. It's better to change implementation.

**Comment by nuzil** [comment]
@orlangur 
Agree, though so also, but then I though about IF there are a case when developers used this method in wrong way and used them for receive count() of invoices. That will crash their implementation. 
Not sure should we think about that cases or if code logic is correct we have to do it?

**Comment by VladimirZaets** [comment]
Hi @nuzil. 
Yes, we understand it. We consider and make a decision for each case separately.
We had the discussion about this case and we think that the correct way to fix this problem it is changing implementation.

**Comment by nuzil** [comment]
@VladimirZaets deal 👍

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-2194](https://jira.corp.magento.com/browse/ENGCOM-2194) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @nuzil. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.6. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Comment by ihor-sviziev** [comment]
Hi @nuzil @VladimirZaets @orlangur,
It's better to use `(bool)$variable` than `boolval($variable)` because it's construction of language and no overhead on function execution.

**Comment by sreichel** [comment]
@orlangur this should be moved to "Port to 2.3 Merged" on board.

**Pull request merged**
