### PR TITLE
Ensure that url suffix resolvers return strings to match function declaration

### LINKED ISSUE #30909: ProductUrlSuffix and CategoryUrlSuffix GraphQL resolvers fail with null values
### Preconditions (*)

1. Magento version 2.4.x
2. Magento 2.4-develop

### Steps to reproduce (*)

1. Go to Admin -> Stores -> Configuration -> Catalog -> Catalog -> Search Engine Optimization
2. Clear product and category url suffix values in admin and save

Screenshot from 2020-11-20 15-24-20

Run GraphQL query that requests product and/or category url suffix value

```graphql
{
  categoryList {
    url_suffix
  }
}
```

**Expected result:**  Empty string (`''`) is returned for `url_suffix` value

Screenshot from 2020-11-20 15-40-01

**Actual Result:** :heavy_multiplication_x: Query fails

Screenshot from 2020-11-20 15-29-15

:heavy_multiplication_x:  with the following error in `exception.log`:

`
2020-11-20 13:29:04] main.ERROR: Return value of Magento\CatalogUrlRewriteGraphQl\Model\Resolver\CategoryUrlSuffix::getCategoryUrlSuffix() must be of the type string, null returned {"exception":"[object] (GraphQL\\Error\\Error(code: 0): Return value of Magento\\CatalogUrlRewriteGraphQl\\Model\\Resolver\\CategoryUrlSuffix::getCategoryUrlSuffix() must be of the type string, null returned at /var/www/html/magento24/vendor/webonyx/graphql-php/src/Error/Error.php:174, TypeError(code: 0): Return value of Magento\\CatalogUrlRewriteGraphQl\\Model\\Resolver\\CategoryUrlSuffix::getCategoryUrlSuffix() must be of the type string, null returned at /var/www/html/magento24/app/code/Magento/CatalogUrlRewriteGraphQl/Model/Resolver/CategoryUrlSuffix.php:80)"} []
`

### Additional Information
The problem is that the private functions `getProductUrlSuffix` and `getCategoryUrlSuffix` are declared with `string` as the return type, but when values are cleared in admin config, `null` gets stored in the `core_config_data` table. The value being returned by `ScopeConfigInterface->getValue` should be checked for null and changed to empty string instead.
I will create PR to fix this.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by aligent-lturner**
### Description (*)
This pull request is to fix #30909 - where a null value for the product and/or category url suffix results in a type error being thrown during GraphQL queries

### Fixed Issues (if relevant)
1. Fixes magento/magento2#30909

### Manual testing scenarios (*)
1. Clear product and category url suffix values in admin and save
2. Run GraphQL query that requests product and/or category url suffix value

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — APPROVED** [review]

**Comment by aligent-lturner** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Go to Admin -> Stores -> Configuration -> Catalog -> Catalog -> Search Engine Optimization
2. Clear product and category url suffix values in admin and save

Screenshot from 2020-11-20 15-24-20

Run GraphQL query that requests product and/or category url suffix value

```graphql
{
  categoryList {
    url_suffix
  }
}
```

**Before:** :heavy_multiplication_x: Query fails

Screenshot from 2020-11-20 15-29-15

with the following error in `exception.log`:

`
2020-11-20 13:29:04] main.ERROR: Return value of Magento\CatalogUrlRewriteGraphQl\Model\Resolver\CategoryUrlSuffix::getCategoryUrlSuffix() must be of the type string, null returned {"exception":"[object] (GraphQL\\Error\\Error(code: 0): Return value of Magento\\CatalogUrlRewriteGraphQl\\Model\\Resolver\\CategoryUrlSuffix::getCategoryUrlSuffix() must be of the type string, null returned at /var/www/html/magento24/vendor/webonyx/graphql-php/src/Error/Error.php:174, TypeError(code: 0): Return value of Magento\\CatalogUrlRewriteGraphQl\\Model\\Resolver\\CategoryUrlSuffix::getCategoryUrlSuffix() must be of the type string, null returned at /var/www/html/magento24/app/code/Magento/CatalogUrlRewriteGraphQl/Model/Resolver/CategoryUrlSuffix.php:80)"} []
`

**After:** :heavy_check_mark: Empty string` (' ') `is returned for `url_suffix` value

Screenshot from 2020-11-20 15-40-01

It was also checked when the product and category url suffix values were filled

Screenshot from 2020-11-20 15-46-24


**Actual Result:** :heavy_check_mark: The correct value is returned for `url_suffix`

Screenshot from 2020-11-20 15-47-51

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Integration Tests, Functional Tests B2B

**Comment by aligent-lturner** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Pull request merged**
