### PR TITLE
Fixed issue #23575

### PR DESCRIPTION
**Pull request by syed92hasan**
### Description (*)

Created date mismatch with a calendar icon
### Fixed Issues (if relevant)

1. #23575: Created date mismatch with a calendar icon

### Manual testing scenarios (*)

 1. Admin -> Marketing -> User Contents -> Reviews
 2. Select created date

   Before Update Result

before-update

  After Update Result
    
after-update

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by kalpmehta — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, thank you for the review.
[ENGCOM-5459](https://jira.corp.magento.com/browse/ENGCOM-5459) has been created to process this Pull Request
:eight_spoked_asterisk: @kalpmehta, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@syed92hasan thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by syed92hasan** [comment]
> @syed92hasan thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

Hi @magento-engcom-team ,

Done

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

**Before:**

before

**After:**

after

**Comment by sivaschenko** [comment]
Static test fail is not valid. See the sniff fix here: https://github.com/magento/magento2/pull/23790

**Pull request merged**
