### PR TITLE
Fixes problem with wrong image URL in sitemap

### PR DESCRIPTION
**Pull request by krisdante**
### Description (*)
Problem was caused by the wrong context of generation. It was adminhtml
and for this area URL for selected image sizes are not defined (as
those sizes are not defined).
Fixed by using Emulation and stwiched to Frontend area for Sitemap generation.

### Fixed Issues (if relevant)

1. magento/magento2#24484: sitemap image URLs has wrong cache path
2.(indirectly) magento/magento2#5321: Images added to sitemap are "404 Not Found" on Nginx [Magento 2.1.0]
3.(indirectly) magento/magento2#4511: XML Sitemap refers to non-watermarked images

### Manual testing scenarios (*)

1. Create 2 stores
2. Add at least one product to each of those store
3. Add at least one image to each of the products
4. Create Sitemap for one of the stores.
5. Generate sitemap (form admin)
6. Open sitemap and check the URL of the image in the feed.
It needs to be valid (not 404) and egual to url of large image from the storefront.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by krisdante** [comment]
FIxes #5321

**Comment by krisdante** [comment]
Fixes #4511

**Review by kalpmehta — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, thank you for the review.
[ENGCOM-5844](https://jira.corp.magento.com/browse/ENGCOM-5844) has been created to process this Pull Request
:eight_spoked_asterisk: @kalpmehta, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by kalpmehta** [comment]
@krisdante Can you add automated tests please?

**Comment by manishmaharjan** [comment]
@krisdante , It seems like it works when sitemap is manually generated, but when sitemap is generated by a scheduler it seems to still take placeholder image. Has this issue also been addressed? Thanks

**Comment by krisdante** [comment]
@manishmaharjan This is different piece of code. Please add a new issue. You can mention me there and I will fix it.

**Comment by edijsvanags** [comment]
> Does not `$this->appEmulation->stopEnvironmentEmulation();` should also be triggered in catches if an exception is thrown ?

It should, however, you can use the _finally_ method, which will be executed each time. 

`try {
                $this->emulation->startEnvironmentEmulation(
                    $sitemap->getStoreId(),
                    \Magento\Framework\App\Area::AREA_FRONTEND,
                    true
                );
                $sitemap->generateXml();
                ......
            } catch (\Exception $e) {
                ......
            } finally {
                $this->emulation->stopEnvironmentEmulation();
            }
`

**Pull request merged**
