### PR TITLE
[Backport] issue fixed #20259 Store switcher not sliding up and down, only dropd…

### LINKED ISSUE #20259: Store switcher not sliding up and down, only dropdown arrow working
Store switcher not sliding up and down, only dropdown arrow working 

### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.2

### Steps to reproduce (*)

Step 1: Go to frontend in mobile device
Step 2: click on toggle in left top corner
Step 3: Go to setting tab and see store switcher and click on label (Ref screenshot)
   
### Expected result (*)

Dropdown should open and close as arrow working

### Actual result (*)

mobile

### PR DESCRIPTION
**Pull request by irajneeshgupta**
### Original Pull Request 
 https://github.com/magento/magento2/pull/20260

issue fixed #20259 Store switcher not sliding up and down, only dropdown arrow working

### Description (*)
Store switcher not sliding up and down, only dropdown arrow working 

Step 1: Go to frontend in mobile device
Step 2: click on toggle in left top corner
Step 3: Go to setting tab and see store switcher and clcik on label (Ref screenshot)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by mageprince** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @mageprince. Thank you for your request. I'm working on Magento instance for you

**Review by mageprince — APPROVED** [review]

**Comment by mageprince** [comment]
@magento-engcom-team Not need instance now. This PR is checked with the 2.2-develop local setup

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-4012](https://jira.corp.magento.com/browse/ENGCOM-4012) has been created to process this Pull Request

**Pull request merged**
