### PR TITLE
Fixed collation of translation table

### LINKED ISSUE #30085: [Translations] Translations Table has the wrong collation
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Add a translation to the translations table with the string 'Cancel Coupon'.
2. Add a translation to the translations table with the string 'Cancel coupon'.

### Expected result (*)

1. It should be possible to add multiple capitalised versions of a string.

### Actual result (*)

1. It'll give a 'Unique constraint violation found', because the collation of the string field is case insensitive. While translations are case sensitive. There are multiple examples in the Magento codebase where multiple versions of the same string exist. For example: 'Cancel coupon' and 'Cancel Coupon'.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by BrentRobert**
### Description (*)

It should be possible to add multiple capitalised versions of a string. This is not the case as the table uses a case insensitive collation. Therefore 'cancel coupon' and 'Cancel coupon' can not be added to the table, making one of the two untranslatable as there is a unique index.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30085

### Manual testing scenarios (*)

1. Add rows manually to the table using multiple capitalisation versions of a string, for example: 'cancel coupon' and 'Cancel coupon'
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by BrentRobert** [comment]
@magento run all tests

**Review by Stepa4man — CHANGES_REQUESTED** [review]
Hi @BrentRobert 
Thanks for your contribution.

Could you please check Magento\GraphQl\GiftCardAccount\ApplyGiftCardToCartOnMutlipleWebsitesTest::testApplyFirstGiftCardToCartOnSecondWebsite locally? It looks like it is failed.

@sidolov @slavvka could you please guys approve changes to DB (and failed DB compare test)?

**Comment by BrentRobert** [comment]
@Stepa4man I'll check it out!

**Comment by BrentRobert** [comment]
@magento run all tests

**Comment by BrentRobert** [comment]
@Stepa4man Where do you see this test failing? It was not in the build report?

**Comment by Stepa4man** [comment]
> @Stepa4man Where do you see this test failing? It was not in the build report?

Seems like it's gone.

**Review by Stepa4man — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, thank you for the review.
[ENGCOM-8725](https://jira.corp.magento.com/browse/ENGCOM-8725) has been created to process this Pull Request
:eight_spoked_asterisk: @Stepa4man, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by Stepa4man** [comment]
@BrentRobert, can you write a setup-integration test for this PR?

**Comment by Stepa4man** [comment]
@gabrieldagama can we approve DB compare test failure?

**Comment by Stepa4man** [comment]
@magento2 run all tests

**Comment by gabrieldagama** [comment]
Hi @Stepa4man, yes in this case we would need to approve it. Since this is a PR issue we will process the high priority PRs first and then come back to lower priority later.

**Comment by engcom-Lima** [comment]
@magento run all tests

**Review by engcom-Lima — CHANGES_REQUESTED** [review]
Hi @BrentRobert ,

Thanks for the collaboration & contribution!

### :x: QA not Passed

As information provided in the description, we can add multiple capitalized versions of a string but after taking PR changes still not able to do so.


**Manual Scenario Steps**
- Add a translation to the translations table with the string 'Cancel Coupon'.
- Add a translation to the translations table with the string 'Cancel coupon'.

**:heavy_check_mark: Expected result After Fix** It should allow adding multiple capitalized versions of a string.


**:x: Actual result After Fix**  Not able to add multiple capitalized versions of a string.
Screenshot 2023-08-17 at 12 48 28 PM

Also please check the failed builds.

**Comment by engcom-Lima** [comment]
Hi @BrentRobert ,

Please review above [comment](https://github.com/magento/magento2/pull/31597#pullrequestreview-1582295417).

Thanks

**Comment by engcom-Lima** [comment]
Hi @BrentRobert ,

Thanks for your contribution and collaboration.

We are closing this PR as there is no latest update. Please feel free to reopen it.

Thanks

**Pull request closed without merging**
