### PR TITLE
Fixed: Wrong price calculation for bundle products 

### LINKED ISSUE #35665: Wrong price calculation for bundle products
### Preconditions and environment

- 2.4.1

### Steps to reproduce

Create a simple product with price 6.75

Create a bundle product which is consisted of 18 pieces of the simple product and add a price of 95% to the bundle product. 

The final price that magento calculates is 115.38 which is wrong

### Expected result

The price rounded is 115.43 (115.425)

### Actual result

The price is 115.38

### Additional information

The bug is coming due to order of calculation. 

Magento is doing it like this 

`round((price * bundle price %)) * pieces `

The correct calculation would be 

`round(price* pieces * bundle price %)`

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by aasim110**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#35665

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by aasim110** [comment]
@magento run all tests

**Comment by aasim110** [comment]
@magento run all tests

**Comment by aasim110** [comment]
@magento run all tests

**Comment by aasim110** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
Hi @aasim110, As per the results of the automated tests, you may need to update test methods.

**Comment by aasim110** [comment]
@magento run Integration Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @aasim110,

Thanks for the contribution!

As part of the [Definition of done](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1), please provide some automated tests for this fix.

Thanks

**Pull request closed without merging**
