### PR TITLE
Allow to generate big number of customer on galera cluster

### LINKED ISSUE #31038: [Issue] Allow to generate big number of customer on galera cluster
This issue is automatically created based on existing pull request: magento/magento2#30990: Allow to generate big number of customer on galera cluster

---------

### Manual testing scenarios (*)

1. Install magento on Galera cluster ( Magento  Cloud Pro for example )
2. create profile that have 10M customer
3. run `bin/magento s:p:g path/to_custom_profile`

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kandy**
### Manual testing scenarios (*)

1. Install magento on Galera cluster ( Magento  Cloud Pro for example )
2. create profile that have 10M customer
3. run `bin/magento s:p:g path/to_custom_profile`

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31038: Allow to generate big number of customer on galera cluster

### CODE REVIEW

**Comment by kandy** [comment]
@magento run all tests

**Comment by kandy** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Integration Tests, Unit Tests

**Comment by ihor-sviziev** [comment]
Seems like test failures not related.

@magento run Functional Tests B2B, Integration Tests, Unit Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8508](https://jira.corp.magento.com/browse/ENGCOM-8508) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked that existing profiles `small.xml`and `medium.xml` generate data without errrors

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Pull request merged**
