### PR TITLE
[Backport] Resolved undefined index issue for import adapter

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Original Pull Request 
 https://github.com/magento/magento2/pull/19765

### Description (*)

Added a condition to check if 'sku' column exists in CSV file before setting its value.
### Fixed Issues (if relevant)

1. magento/magento2#19761: Custom import adapter data validation issue

### Manual testing scenarios (*)

1. Create a custom import adapter extending `Magento\ImportExport\Model\Import\Entity\AbstractEntity`
2. Add valid columns in `getValidColumnNames()` function.
    e.g. ['column1', 'column2', 'column3']
3. Create CSV file with columns stated above and add data.
4. Go to System > Import
5. Select your adapter from "Entity Type" dropdown
6. Select your CSV file in "Select File to Import" field.
7. Click on "Check Data" button
8. CSV file should get validated if column and data are available

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-5030](https://jira.corp.magento.com/browse/ENGCOM-5030) has been created to process this Pull Request

**Comment by Nazar65** [comment]
HI @amol2jcommerce based on this comment https://github.com/magento/magento2/issues/19761#issuecomment-451092004 fix for forward port must be reverted and refactored.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5030](https://jira.corp.magento.com/browse/ENGCOM-5030) has been created to process this Pull Request

**Comment by Nazar65** [comment]
QA Passed :heavy_check_mark:

**Pull request merged**
