### PR TITLE
Changed constructor to use an interface

### PR DESCRIPTION
**Pull request by dverkade**
The front controller only accepts an HTTP response object. The front controller now has a direct dependency on the Response\Http class, which is not correct. The front controller should not care which response object will be injected only that it will adhire the ResponseInterface. So changed this constructor to accept a ResponseInterface which in di.xml is being replaced by the Response\Http class.

### CODE REVIEW

**Comment by vrann** [comment]
@dverkade can you please synchronize your branch with the latest develop?

**Comment by vrann** [comment]
@dverkade actually, did it with the GitHub UI

**Comment by vrann** [comment]
@dverkade this pull request duplicates #6772. Closing.

**Comment by magento-team** [comment]
@dverkade thank you for your contribution. Your Pull Request has been successfully merged

**Pull request merged**
