### PR TITLE
When creating a customer, prevent selection of store not relevant to chosen website

### PR DESCRIPTION
**Pull request by joshdavenport**
When creating a customer, and with customers scope not set to Global, it is possible to select a store (in the "Send welcome email from" dropdown) that is not relevant to the website.

### Description (*)
While an improvement has been made to this process by the resolving of this issue - https://github.com/magento/magento2/issues/10411 . There is still a flaw in this process where it is possible to select a store that is not relevant to the selected website (the value in "Associate to Website"). The fix introduced in https://github.com/magento/magento2/issues/10411
 prevents an invalid store by providing an error, but the user should never be able to select an invalid store in the first place. This PR adds filtering to the select, only showing relevant stores to the selected website when customers can be scoped to websites (i.e. not global).

### Fixed Issues (if relevant)
None, but further enhances fix from https://github.com/magento/magento2/issues/10411

### Manual testing scenarios (*)
1. Magento 2.3 with fix from https://github.com/magento/magento2/issues/10411
2. Customer Configuration > Scope set to Website
3. Create a new customer, and change "Associate to Website"

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19782) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @joshdavenport. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by joshdavenport** [comment]
I'm not sure where I should be adding/changing tests to cover this if applicable. If somebody could point me in the right direction there I can make necessary changes.

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-3712](https://jira.corp.magento.com/browse/ENGCOM-3712) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @joshdavenport thanks for your contirbution! Looks like `app/code/Magento/Store/Model/System/Store.php` update and $options['value'] format change, breaks `app/code/Magento/UrlRewrite/Block/Edit/Form::_getStoresListRestrictedByEntityStores()` functionality. Can you please check.

**Comment by sidolov** [comment]
Hi @joshdavenport , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
