### PR TITLE
Updated tedivm/jshrink dependency to PHP 8 compatible version

### PR DESCRIPTION
**Pull request by vlmed**
### Description (*)
Update `tedivm/jshrink` dependency version from "~1.3.0" to "~1.4.0"

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/457

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/31778

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by vlmed** [comment]
@magento run all tests

**Comment by vlmed** [comment]
@magento run all tests

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @vlmed thanks for the pull request! Can you please also update [EE composer.json](https://github.com/magento/partners-magento2ee/blob/php8-develop/composer.json) and lock files and link the EE pull request using the [related PR section](https://devdocs.magento.com/contributor-guide/pull-request-tests.html#related-pull-requests). That should fix static tests

**Comment by vlmed** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@vlmed I have updated ce and ee branches and linked EE pull request in the description of this PR

@magento run all tests

**Review by coderimus — CHANGES_REQUESTED** [review]
Hello @vlmed 
Please, fix conflicts for the composer.lock and one of the lib modules composer.json. Looks like this is a result of the latest PHP8 dev branch merge.

**Comment by vlmed** [comment]
Hello @coderimus, @sivaschenko. Thanks for review. Conflicts have already been resolved.

**Comment by vlmed** [comment]
@magento run all tests

**Review by coderimus — APPROVED** [review]

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run WebAPI Tests,Functional Tests CE

**Review by sivaschenko — APPROVED** [review]

**Pull request merged**
