### PR TITLE
#25907: Fix CatalogSpecialPriceStorage API delete does not delete by …

### PR DESCRIPTION
**Pull request by sanjay-wagento**
Fix CatalogSpecialPriceStorage API delete does not delete by store id

### Description (*)

Fix CatalogSpecialPriceStorage API delete does not delete by store id

### Fixed Issues (if relevant)

magento/magento2#25907

### Manual testing scenarios (*)

1. Create multiple websites
2. Set Catalog Price Scope to Website
3. Create special price for a product on one of the websites (or both)
4. Call V1/products/special-price-delete API specifying one of the store_id's

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sdzhepa** [comment]
@magento run Functional Tests CE

**Review by sdzhepa — CHANGES_REQUESTED** [review]
Hello @sanjay-wagento 

Could you please cover these changes with API-function autotests.
It is required according to the [Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests)

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
@engcom-Echo can you please check integration tests?

**Comment by engcom-Echo** [comment]
@magento run Integration Tests

**Comment by engcom-Echo** [comment]
Hi @VladimirZaets could you please approve it?

**Review by VladimirZaets — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7794](https://jira.corp.magento.com/browse/ENGCOM-7794) has been created to process this Pull Request

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @sanjay-wagento .

During testing, we faced the issue.

**_Problem:_** Not able to delete special price for a product via API

**Preconditions:**

Have 2 simple products (for example) :

- **Simple 1** , Special price = **80$**,
- **Simple 2** , Special price = **80$**,

Have at least 2 Websites, Stores, Store views
In my case:
Screenshot from 2020-07-10 16-44-43
Main store : `store_id = 1`
Second store : `store_id = 2`

**Manual testing scenario:**

1. Set Catalog Price Scope to Website ( Go to **Admin -> Stores -> Configuration -> Catalog -> Catalog -> Price** and set **Catalog Price Scope** to **Website**);
2. Call **POST**  `V1/products/special-price-delete `API specifying one of the store_id's -> Execute

Screenshot from 2020-07-10 16-50-08
Screenshot from 2020-07-10 16-59-25

In my case, it must remove the special price for both products in the Second Store (**store_id = 2**)
3. Run in console: `php bin/magento indexer:reindex`
4. Go to Storefront -> Catalog with products

**Actual Result:** :heavy_multiplication_x:  The special price has not been deleted for both products in the Second Store



@sanjay-wagento Could you take a look?

Thanks!

**Comment by engcom-Echo** [comment]
Hi @sanjay-wagento , I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
