### PR TITLE
dev:di:info error

### LINKED ISSUE #38740: dev:di:info error in magento 2.4.7
### Preconditions and environment

- Magento version : 2.4.7
- When executing bin/magento dev:di:info "Class\Path\Name" I get the error:

Constructor Parameters:
+------+----------------+------------------+
| Name | Requested Type | Configured Value |
+------+----------------+------------------+

There is an error in /var/www/html/vendor/symfony/console/Output/Output.php at line: 109
Symfony\Component\Console\Output\Output::writeln(): Argument #1 ($messages) must be of type Traversable|array|string, null given, called in /var/www/html/vendor/magento/module-developer/Console/Command/DiInfoCommand.php on line 97#0 /var/www/html/vendor/magento/module-developer/Console/Command/DiInfoCommand.php(97): Symfony\Component\Console\Output\Output->writeln(NULL)
#1 /var/www/html/vendor/magento/module-developer/Console/Command/DiInfoCommand.php(166): Magento\Developer\Console\Command\DiInfoCommand->printConstructorArguments('Magento\\Custome...', Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/vendor/symfony/console/Command/Command.php(326): Magento\Developer\Console\Command\DiInfoCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Developer\Console\Command\DiInfoCommand\Interceptor->___callParent('run', Array)
#5 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Developer\Console\Command\DiInfoCommand\Interceptor->Magento\Framework\Interception\{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/generated/code/Magento/Developer/Console/Command/DiInfoCommand/Interceptor.php(77): Magento\Developer\Console\Command\DiInfoCommand\Interceptor->___callPlugins('run', Array, Array)
#7 /var/www/html/vendor/symfony/console/Application.php(1078): Magento\Developer\Console\Command\DiInfoCommand\Interceptor->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Developer\Console\Command\DiInfoCommand\Interceptor), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/vendor/magento/framework/Console/Cli.php(118): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/vendor/symfony/console/Application.php(175): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
#12 {main}

### Steps to reproduce

1. Open terminal
2. Run command `bin/magento dev:di:info "Magento\Customer\Model\Registration"`

### Expected result

- show constructor parameter

### Actual result

<pre>Constructor Parameters:
+------+----------------+------------------+
|<font color="#26A269"> Name </font>|<font color="#26A269"> Requested Type </font>|<font color="#26A269"> Configured Value </font>|
+------+----------------+------------------+

There is an error in /var/www/html/vendor/symfony/console/Output/Output.php at line: 109
Symfony\Component\Console\Output\Output::writeln(): Argument #1 ($messages) must be of type Traversable|array|string, null given, called in /var/www/html/vendor/magento/module-developer/Console/Command/DiInfoCommand.php on line 97#0 /var/www/html/vendor/magento/module-developer/Console/Command/DiInfoCommand.php(97): Symfony\Component\Console\Output\Output-&gt;writeln(NULL)
#1 /var/www/html/vendor/magento/module-developer/Console/Command/DiInfoCommand.php(166): Magento\Developer\Console\Command\DiInfoCommand-&gt;printConstructorArguments(&apos;Magento\\Custome...&apos;, Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/vendor/symfony/console/Command/Command.php(326): Magento\Developer\Console\Command\DiInfoCommand-&gt;execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\Command-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Developer\Console\Command\DiInfoCommand\Interceptor-&gt;___callParent(&apos;run&apos;, Array)
#5 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Developer\Console\Command\DiInfoCommand\Interceptor-&gt;Magento\Framework\Interception\{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/generated/code/Magento/Developer/Console/Command/DiInfoCommand/Interceptor.php(77): Magento\Developer\Console\Command\DiInfoCommand\Interceptor-&gt;___callPlugins(&apos;run&apos;, Array, Array)
#7 /var/www/html/vendor/symfony/console/Application.php(1078): Magento\Developer\Console\Command\DiInfoCommand\Interceptor-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application-&gt;doRunCommand(Object(Magento\Developer\Console\Command\DiInfoCommand\Interceptor), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/vendor/magento/framework/Console/Cli.php(118): Symfony\Component\Console\Application-&gt;doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/vendor/symfony/console/Application.php(175): Magento\Framework\Console\Cli-&gt;doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/bin/magento(23): Symfony\Component\Console\Application-&gt;run()
</pre>

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rogerdz**
### Description (*)

$paramsTable->render() not return anything (https://github.com/symfony/console/blob/v6.4.2/Helper/Table.php#L318).
It call $this->output->writeln for display table => not need $output->writeln in magento 

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38740

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run WebAPI Tests, Functional Tests EE, Functional Tests B2B

**Comment by engcom-Bravo** [comment]
Hello,

Internal team has started to work on it

Thanks.

**Comment by hostep** [comment]
For some reason, this PR wasn't marked as merged, even though the code was merged (cherry-picked?) recently here: https://github.com/magento/magento2/commit/c6d91bdf2468a104ffef556cb51031959bf245ff

**Comment by engcom-Bravo** [comment]
@hostep  Thanks for your contribution!!.

Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-11999 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-11999&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta1.

Thanks

**Pull request closed without merging**
