### PR TITLE
25162 Fixed link in error message on frontend 

### LINKED ISSUE #25162: Message at Frontend has No HTML format
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Store-> configuration-> Customer -> Newsletter
3. 
image
"Allow Guest Subscription" is "No"
4. Go to frontend
5. Enter the email "test@localhost.com" , press "Subscribe" at the bottom.
6. Look the message:
image

### Expected result (*)

image

### Actual result (*)

image

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixed #25162 issue
ezgif com-video-to-gif

### Fixed Issues (if relevant)

1. magento/magento2#25162: Message at Frontend has No HTML format

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Usik2203. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Usik2203, here is your [new Magento instance](https://pr-26328.instances.magento-community.engineering).
Admin access: [https://pr-26328.instances.magento-community.engineering/admin](https://pr-26328.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rogyar** [comment]
Hi, @Usik2203. Thank you for your contribution. I would kindly ask you to cover your change with an automated test, please. It's necessary for further PR processing. In this particular case, I would recommend a simple MFTF test.

Also, do not forget to sign [Adobe CLA](https://github.com/magento/magento2/pull/26328/checks?check_run_id=381246555).

Thank you!

**Comment by Usik2203** [comment]
Hi, @rogyar. Thank you for your advice. I started working on creating MFTF test for this PR. 
Thanks.

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @Usik2203. It looks like something went wrong with the current PR. Please, make sure it includes only the necessary commits.

Thank you.

**Pull request closed without merging**
