### PR TITLE
#27370 Internet explorer issue:Default billing/shipping address not showing

### PR DESCRIPTION
**Pull request by vasilii-b**
### Description (*)
This PR applies fixes to show the customer addresses under Addresses tab on a Customer Edit page in the admin area

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
1. magento/magento2#27370: Internet explorer issue:Default billing/shipping address not showing

### Manual testing scenarios (*)
Please see the original issue.

The result should look like in other browsers.

IE 11 result
Result - IE11

Google Chrome result
Result - Chrome

### Questions or comments
Should I provide an MFTF test for this case?

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by edenduong — APPROVED** [review]
Hi @vasilii-b: Thank you for your contribution. I believe this PR is covered by the MFTF test in `AdminAssertCustomerDefaultBillingAddress` Action Group. But because the environment of MFTF now is not in IE so it can not find the problem.

**Comment by magento-engcom-team** [comment]
Hi @edenduong, thank you for the review.
[ENGCOM-7175](https://jira.corp.magento.com/browse/ENGCOM-7175) has been created to process this Pull Request
:eight_spoked_asterisk: @edenduong, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by vasilii-b** [comment]
Hi @edenduong,
Could you please manage the labels for this PR? It seems the label `Progress: pending review` is not necessary anymore since you reviewed the changes. Should not it be `Progress: ready for testing`?

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [Magento instance](https://i-27383-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27383-2-4-develop.instances.magento-community.engineering/admin_2537](https://i-27383-2-4-develop.instances.magento-community.engineering/admin_2537)
Login: `485538bc` Password: `13e4fb9c0e6c`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [new Magento instance](https://pr-27383.instances.magento-community.engineering).
Admin access: [https://pr-27383.instances.magento-community.engineering/admin_43cf](https://pr-27383.instances.magento-community.engineering/admin_43cf)
Login: `9357706a` Password: `2d1f3748b23e`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:**
screen1

**After:**
screen2

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Pull request merged**
