### PR TITLE
Fix Varnish VCL Template to use path without /pub to health_check.php

### LINKED ISSUE #36903: [Issue] Fix Varnish VCL Template to use path without /pub to health_check.php
This issue is automatically created based on existing pull request: magento/magento2#34323: Fix Varnish VCL Template to use path without /pub to health_check.php

---------

### Description (*)
As per Magento 2.4.2 the /pub directory is now the recommended document root, the default varnish vcl should be changed to reflect that too.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by marvinhinz**
### Description (*)
As per Magento 2.4.2 the /pub directory is now the recommended document root, the default varnish vcl should be changed to reflect that too.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36903: Fix Varnish VCL Template to use path without /pub to health_check.php

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@marvinhinz please revert latest commit with changes in auto loader

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests look not related to changes from this PR.

**Comment by engcom-Alfa** [comment]
Hi @marvinhinz and @ihor-sviziev 
Thanks for your contribution and collaboration!
I understand that the default varnish vcl is going to be changed to reflect /pub directory too. But here the question is, how would we validate that changes are enough/accurate.
As part of QA validation, could you please help me with steps to reproduce the existing case and to validate the changes?
Thanks in advance

**Comment by ihor-sviziev** [comment]
@engcom-Alfa,
You can apply changes to your varnish.vcl file, restart varnish and check nginx logs to see the requests to health check file

**Comment by engcom-Alfa** [comment]
Hi @marvinhinz and @ihor-sviziev
I have re-tested it with the combination of nginx and varnish configurations.

1. Make sure that the varnish is working with Magento successfully in ngnix server
2. Changed the varnish.vcl file's health check file php file path from /pub/health_check.php to /health_check.php.
3. Observed no logs in the nginx_access.log file
4. Applied the PR changes into the varnish4.vcl, varnish5.vcl and varnish6.vcl files as per the updates.
5. Observed no logs in the nginx_access.log file

Just a front end home refreshed once and one log relevant to that been logged into the file as shown in the below screenshot.
Highlighted the Before PR changes log and after PR changes log.
Screenshot 2021-12-16 at 11 10 57 PM


No additional changes in the logs have been noticed. Basically no logs were logged into that before PR changes and after PR changes as well.

If PR changes going to help in resolving any issue, kindly elaborate and let me know what and how the issue can be identified please!

**Review by torhoehn — CHANGES_REQUESTED** [review]
@ihor-sviziev What about the other matches of `pub` int the vcl files? Shouldn't they also be removed?

**Comment by ishakhsuvarov** [comment]
Closing this for now due to inactivity for a long time.

Please feel free to reopen.

**Comment by ihor-sviziev** [comment]
@ishakhsuvarov I think QA didn't know how to test it right, changes still looks pretty good

**Comment by ishakhsuvarov** [comment]
@ihor-sviziev In this case I'll put it in for additional round of testing

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by torhoehn** [comment]
> @ihor-sviziev What about the other matches of `pub` int the vcl files? Shouldn't they also be removed?

I think this is still valid.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
It seems that bot has moved this PR from Ready for Testing to Changes Requested, hence moving it back.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @marvinhinz , @ihor-sviziev , @torhoehn,

Thank you for your contribution!

:heavy_check_mark: QA Passed
Varnish .vcl is using path without /pub to health_check.php

**Preconditions:**
1. Configure varnish and confirmed that varnish is working successfully.


**Steps to reproduce:**
1. Checked that magento instance’s doc root is /pub
2. Configure magento instance's .host and .port in varnish's vcl file
3. Applied the PR changes into the varnish4.vcl, varnish5.vcl and varnish6.vcl files as per the updates.

**Before:**
In apache logs, found that health_check.php call is going with /pub and its showing 404 status
image


**After:**
We are getting, health_check.php call is going without /pub and its showing 200 status
image

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run Integration Tests

**Comment by engcom-Charlie** [comment]
@magento run Integration Tests

**Comment by engcom-Charlie** [comment]
The failing tests are not related to the PR changes or not failing because of PR. Hence moving it to Merge In Progress.

Thank you!

**Comment by engcom-Lima** [comment]
@magento create issue

**Pull request merged**
