### PR TITLE
Removed usage of CliIndexerReindexActionGroup action group

### LINKED ISSUE #31130: [Issue] Removed usage of CliIndexerReindexActionGroup action group
This issue is automatically created based on existing pull request: magento/magento2#31128: Removed usage of CliIndexerReindexActionGroup action group

---------
### Description
Remove usage or changed value of CliIndexerReindexActionGroup action group from tests to improve execution time for the following modules:
- Bundle 
- BundleImportExport 
- CatalogUrlRewrite 
- ConfigurableProduct

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Remove usage or changed value of CliIndexerReindexActionGroup action group from tests to improve execution time for the following modules:
- Bundle 
- BundleImportExport 
- CatalogUrlRewrite 
- ConfigurableProduct

### Resolved issues:
1. [x] resolves magento/magento2#31130: Removed usage of CliIndexerReindexActionGroup action group

### CODE REVIEW

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Comment by sergiy-v** [comment]
Going to check failed tests for Bundle module.

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE

**Comment by rogyar** [comment]
Yeah, looks like the failing tests for bundling products are related.

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
Hello @rogyar,
Just FYI, I done with the changes. Looks like the failed test for B2B is not related to the changes (I see timeout issue there).
Would you check it please?

Thank you.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8525](https://jira.corp.magento.com/browse/ENGCOM-8525) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Pull request merged**
