### PR TITLE
#27656 Remove invoice email sending when order email is sending

### LINKED ISSUE #13466: Invoice Sales Email not send
### Preconditions

1. Magento 2.2.2
2. OS: Ubuntu 16.04
3. Mysql version 5.7.21
4. PHP version 7.0.22

### Steps to reproduce

1. Set up "Stores -> Settings -> Configuration -> Sales -> Sales Emails -> Invoice -> Enabled -> Yes"
2. Configure PayPal "Stores -> Settings -> Configuration -> Sales -> Payment Methods -> PayPal -> Payment Action -> Sale"
3. Make order and pay with PayPal.

### Expected result

1. Order Created
2. Email with order information send.
3. Invoice Created
4. Email with invoice information send

### Actual result

1. Order Created <- ok
2. Email with order information send. <- ok
3. Invoice Created <- ok
4. Email with invoice information is not send <- wrong

Overview docs http://docs.magento.com/m2/ce/user_guide/configuration/sales/sales-emails.html
Since sales emails for invoice is enabled Magento should sends a transactional email for each invoice generated.

### LINKED ISSUE #27656: 2.3.4 Invoice always sent (if exist) when order placed.
### Preconditions (*)
related to attempt to fix 
https://github.com/magento/magento2/issues/13466

commit 
https://github.com/magento/magento2/commit/5ccd367ebc628b588a77cb2032faeabd6005b039
1. # h3. Steps to reproduce (*)
1. Place order with a payment method that instantly generates an invoice
1. The module/code that generated an invoice now is responsible for checking it's state and send to customer
1. but here https://github.com/magento/magento2/commit/896ae3bce3615ba59ba0e43757d6712de023dc20#diff-5e96777dde905631ad1729751f5cc83fR72 magento checks if invoice exist and send it to customer
1. If so, pleas give the possibility to disable this in `sales*model_service_quote_submit*success` without code modifying or changing `\Magento\Quote\Observer\SubmitObserver::execute` or its dependencies

### Expected result (*)
1. Invoice Sending is managed by modules that created this invoice and should be configurable
1. Invoice is not sent the same time the order placed
1. or this feature is disabled and can be configured

### Actual result (*)
1. Invoice is always sent if exists https://github.com/magento/magento2/commit/896ae3bce3615ba59ba0e43757d6712de023dc20#diff-5e96777dde905631ad1729751f5cc83fR7
1. The original intention to fix https://github.com/magento/magento2/issues/13466 if so **the PayPal module is responsible for sending its invoice NOT MAGENTO QUOTE MODULE**

### PR DESCRIPTION
**Pull request by ilnytskyi**
### Description (*)

The fix for https://github.com/magento/magento2/issues/13466 does not seem to be placed in the same observer where order email is sent especially without the possibility to disable it;

Original fix also violates SRP and there is no way to disable that feature from admin
Additionally discovering an invoice this way can be wrong if two invoices were generated and both should be sent.
```
$invoice = current($order->getInvoiceCollection()->getItems());
```

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/13466

### Manual testing scenarios (*)

1. Place order with any payment method that can generate an invoice the same time or later
2. Only order email sent. Invoice email should be handled by creator module.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by lenaorobei — CHANGES_REQUESTED** [review]
It looks to me that with removing invoice sending we will end up with the same issue like https://github.com/magento/magento2/issues/13466.

If that is PayPal issue let's create and link them. At least we will understand the root cause.

**Comment by ilnytskyi** [comment]
@lenaorobei

No need to create anything.
https://github.com/magento/magento2/issues/13466
it is a PayPal issue than was not fixed right way

**Comment by lenaorobei** [comment]
I got this, but what I'm saying is that we should point to the proper fix prior to merging this PR.
By just accepting this change we can easily reopen https://github.com/magento/magento2/issues/13466

What I'd expect - is not just revert wrong change, but identify and fix the real problem.

**Comment by lenaorobei** [comment]
@ilnytskyi are you still up for resolving the root cause issue?

**Comment by ilnytskyi** [comment]
No, I will not fix the PayPal module issue.
I think the code should be reverted as in my PR and the 
#13466 should be reopened and fixed in the PayPal module.

**Comment by lenaorobei** [comment]
Thanks for your reply. I reopened the issue.
Putting this PR `On Hold` until issue with PayPal is resolved.

**Comment by engcom-Charlie** [comment]
Hello @ilnytskyi now we have possibility to disable invoice email sending.
### Case 1 :heavy_check_mark:
have sales emails invoce disabled
image
place order via PayPal we will get one order email as expected.
image
### Case 2 :heavy_check_mark:
have sales emails invoce enabled
image
place order via PayPal we will get two emails as expected.
image

What do you think?
Thank you.

**Comment by engcom-Charlie** [comment]
Hello, @ilnytskyi seems the issue mentioned above has already been fixed on the latest 2.4-develop please see https://github.com/magento/magento2/pull/27739#issuecomment-750865450.
So I close this PR.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
