### PR TITLE
Fixes for request shipping rates populates

### PR DESCRIPTION
**Pull request by sheetal2jcommerce**
### Description (*)
Fixes applied when creating a new order in the admin panel, clicking "Get shipping methods and rates" shipping methods returned for the chosen store.If the instance configured for multipile websites,all attributes which require website specific data like currency, this fixes will work.

### Fixed Issues (if relevant)

1. magento/magento2#15497: requestShippingRates populates wrong store and website IDs when retrieving shipping rates and methods in admin panel

### Manual testing scenarios (*)

1. Create two or more websites within the Magento install, and create each with their own store and store views.
2. Turn on some shipping methods for one store, and other shipping methods for the other store.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @sheetal2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by VladimirZaets** [comment]
Hi @sheetal2jcommerce, thanks for collaboration. Please fix failed tests.

**Comment by sivaschenko** [comment]
Original pull request https://github.com/magento/magento2/pull/18560

**Comment by sivaschenko** [comment]
Hi @sheetal2jcommerce , would you like to continue work on this PR?

**Comment by sivaschenko** [comment]
@sheetal2jcommerce closing due to inactivity. Feel free to contact me if you'd like to continue work on this contribution.

**Comment by sheetal2jcommerce** [comment]
Hi @sivaschenko , Yes I want to continue work on this ticket. After removing unneccessory comments I found conflict in file which I resolved. Please explain me further to do.
Thanks
Sheetal

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3628](https://jira.corp.magento.com/browse/ENGCOM-3628) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@sheetal2jcommerce thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by sivaschenko** [comment]
Hi @sheetal2jcommerce we cannot reproduce the issue on 2.3-develop:

Manual testing scenario:

1. Create 2 websites, 2 store and 2 stores view. 1 store and 1 store view per website;
2. Set enable to "Flat Rate" shipping method for first store (ID 1), and to "Free Shipping" method for second store (ID 2);
3. Create custom product for second store (ID 2);
4. Go to Sales->Order;
5. Click "Create New Order";
6. Click "Create New Customer";
7. Select Storeview for second website (ID 2);
8. Click "Add Products" and add, created before, product to Order;
9. Fill all required fields in "Address Information";
10.Click "Get shipping methods and rates";

Actual result: Shipping method "Free Shipping" returned for the chosen store (ID 2);

Is there anything we've missed?

**Comment by sheetal2jcommerce** [comment]
Hi @sivaschenko 
Please configure such a shipping method for which you can set a rates website wise.
So when you select last website, it will show the rates assign for website -1. 
This is happening because application picking admin store  website to fetch data and not quote store website.
Hoping this will help you to generate issue.

Thanks
Sheetal

**Comment by sivaschenko** [comment]
Hi @sheetal2jcommerce looks like the issue was already fixed. Please check commit from 1st October: https://github.com/magento/magento2/commit/cc00197d13d6244e32201e4c6bf00287e54747c5

I am closing this pull request as not actual, feel free to reach out to me for any questions/comments

**Comment by sheetal2jcommerce** [comment]
Hi @sivaschenko ,

I have fix the issue for ticket  "#15497" which is still open.
So its not clear  how the issue is closed and ticket also not declare that this issue is fixed.
Can you describe this please.

Thanks

**Comment by sivaschenko** [comment]
Hi @sheetal2jcommerce , sorry for that situation, the issue was fixed as part of an internal task that wasn't linked to the issue. Thanks for pointing that out, the issue will be verified and closed if confirmed

**Pull request closed without merging**
