### PR TITLE
Replace repetitive actions with Action Groups in AdminCreateProductDuplicateUrlkeyTest

### LINKED ISSUE #32379: [Issue] Replace repetitive actions with Action Groups in AdminCreateProductDuplicateUrlkeyTest
This issue is automatically created based on existing pull request: magento/magento2#32288: Replace repetitive actions with Action Groups in AdminCreateProductDuplicateUrlkeyTest

---------

### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run the test in the local environment and verified that it run successfully

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run the test in the local environment and verified that it run successfully

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32379: Replace repetitive actions with Action Groups in AdminCreateProductDuplicateUrlkeyTest

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Static Tests

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-8923](https://jira.corp.magento.com/browse/ENGCOM-8923) has been created to process this Pull Request

**Pull request merged**
