### PR TITLE
Bug Fix: Add missing return statement to admin usage enable controller

### LINKED ISSUE #31374: [Issue] Bug Fix: Add missing return statement to admin usage enable controller
This issue is automatically created based on existing pull request: magento/magento2#31356: Bug Fix: Add missing return statement to admin usage enable controller

---------
### Description (*)
Although there is a response-type Docblock declaration, there is no `return` statement.
This results in invalid handling of the Controller in FrontendController class.

### Fixed Issues (if relevant)
1. [X] Invalid controller handling.

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Although there is a response-type Docblock declaration, there is no `return` statement.
This results in invalid handling of the Controller in FrontendController class.

### Fixed Issues (if relevant)
1. [X] Invalid controller handling.

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31374: Bug Fix: Add missing return statement to admin usage enable controller

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Could you cover your change with some kind of automated test?

**Comment by ihor-sviziev** [comment]
@magento create issue

@magento run Functional Tests B2B

**Comment by lbajsarowicz** [comment]
@magento run all tests

@ihor-sviziev Added Unit Tests. Also marked one of these as `Skipped` due to lack of Exception handling there.

**Comment by ihor-sviziev** [comment]
@lbajsarowicz could you explain this:
> Also marked one of these as Skipped due to lack of Exception handling there.

If it's not handled - can we just expect that method execute just throws the same exception?

**Comment by lbajsarowicz** [comment]
@magento run all tests

@ihor-sviziev Referenced https://github.com/magento/magento2/issues/31393 in the Skip message.

**Comment by ihor-sviziev** [comment]
@magento run 
Static Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8572](https://jira.corp.magento.com/browse/ENGCOM-8572) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**


**Manual testing scenario:**

1. Go to app/code/Magento/AdminAnalytics/Controller/Adminhtml/Config/EnableAdminUsage.php
2. Verify missing return statement to admin usage enable controller
3. Go to app/code/Magento/AdminAnalytics/Test/Unit/Controller/Adminhtml/Config/EnableAdminUsageTest.php
4. Verify missing return statement to admin usage enable controller

**Before:** :heavy_multiplication_x: 

Screenshot 2024-01-18 at 7 21 26 PM

Screenshot 2024-01-18 at 7 23 55 PM


**After:** :heavy_check_mark:  


Screenshot 2024-01-18 at 7 31 21 PM

Screenshot 2024-01-18 at 7 33 26 PM

Screenshot 2024-01-18 at 7 33 49 PM


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
Functional Tests CE and Functional Tests B2B failure are different on last two run on same commit.

Functional Tests B2B
Run1 
Screenshot 2024-01-25 at 6 02 08 PM

Run2
Screenshot 2024-01-25 at 6 02 12 PM

Functional Tests CE
Run1
Screenshot 2024-01-25 at 6 02 29 PM

Run2
Screenshot 2024-01-25 at 6 02 34 PM

Hence moving it to `Merge In Progress`

**Pull request merged**
