### PR TITLE
MC-38226: Unexpected behavior on the PayPal express review page during loading

### LINKED ISSUE #32006: Unexpected behavior on the PayPal express review page during loading
Precondition:

1. [Configure PayPal Express Checkout](https://jira.corp.magento.com/browse/MAGETWO-76147)
2. Create simple product (price = 10)
3. Create customer with address: 
(on) use incorrect address
* First Name: Account
* Last Name: Account
* Email Address: Account@gmail.com
* Company: Company
* Address: Street Address
* City: City
* State/Province: California (CA)
* Zip/Postal Code: 90230
* Country: United States
* Telephone: 12122
* Password: 123123qQ
* Confirm Password: 123123qQ

Steps:
1. Go to frontend
2. Open simple product
3. Click "Add to Cart" button 
4. Click "Pay pal" button 
5. login sandbox account
6. Click "Continue" button
 
(/) Expected result
Paypal express review page is loading correctly
  
(x) Actual result
Paypal express review page is loading incorrectly
Update Shipping Method button appears

### PR DESCRIPTION
**Pull request by viktorpetryk**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#32006

### Manual testing scenarios (*)
see magento/magento2#32006

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by victorpetryk** [comment]
@magento run all tests

**Comment by victorpetryk** [comment]
@magento run all tests

**Comment by victorpetryk** [comment]
@magento run all tests

**Comment by victorpetryk** [comment]
@magento run Functional Tests B2B

**Review by zakdma — APPROVED** [review]

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-32008`.

**Comment by engcom-Oscar** [comment]
:heavy_check_mark: QA passed

Precondition:
1. [Configure PayPal Express Checkout](https://jira.corp.magento.com/browse/MAGETWO-76147)
2. Create simple product (price = 10)
3. Create customer with address: 
(on) use incorrect address
* First Name: Account
* Last Name: Account
* Email Address: Account@gmail.com
* Company: Company
* Address: Street Address
* City: City
* State/Province: California (CA)
* Zip/Postal Code: 90230
* Country: United States
* Telephone: 12122
* Password: 123123qQ
* Confirm Password: 123123qQ

Steps:
1. Go to frontend
2. Open simple product
3. Click "Add to Cart" button 
4. Click "Pay pal" button 
5. login sandbox account
6. Click "Continue" button
:x: **Before:**
Paypal express review page is loading incorrectly
Update Shipping Method button appears

:heavy_check_mark: **After:**
Paypal express review page is loading correctly. 
'Update Shipping Method' button doesn't appear

**Pull request merged**
