### PR TITLE
Fix for the issue #25675

### PR DESCRIPTION
**Pull request by sichensol**
### Description (*)
This pull request should fix issue #25675

### Fixed Issues (if relevant)
1. magento/magento2#25675: Unable add product to cart in Magento 2.3.3 backend when stock quantity is 1 - "The requested qty is not available"

### Manual testing scenarios (*)
Described here https://github.com/magento/magento2/issues/25675

### CODE REVIEW

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hi @molneek, thank you for your contribution!
Could you please drop a few words about the root reason of the issue and how the applied solution solves it? Unfortunately, it's not clear without performing an additional investigation.

Please, also note, due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) the changes should be covered by tests. Could you please cover your fix by an automated test?

Thank you!

**Comment by sichensol** [comment]
Hi @dmytro-ch, thank you for review. The root reason for the issue is that during checking a product inventory this method calls several times before item is saved to a DB and after. But the method uses item id to collect inventory information. And when an item is not saved to a DB but checked inventory for the product, we collect incorrect data, that in next checking will be added to current qty and corrupt the result. 
E.g we have 1 qty of a product. We add to the cart this item. Magento checks inventory and stores that for itemId = null qty is 1, then during nex checking when the item is saved to DB Magento checks in the method if there is not a qty info for itemId (e.g 5) add this qty to currently used qty. But as qty stored for itemId = null this will always true and Magento adds unappropriate qty and corrupts data.
After that in the following checks, qty can't be matched with actual qty and Magento displays the error message "The requested qty is not available".

Also, this fix does not require additional automated tests, as all Magento current tests are good with this solution. And this solution fixes the process of corrupting data and does not change the method signature

**Comment by dmytro-ch** [comment]
@molneek thank you for the details!

**Comment by dmytro-ch** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-25711.instances.magento-community.engineering).
Admin access: [https://pr-25711.instances.magento-community.engineering/admin](https://pr-25711.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
@molneek, unfortunately, there is no test that covers the aforementioned case.
Please create at least a simple unit test (e.g. `\Magento\CatalogInventory\Test\Unit\Model\Quote\Item\QuantityValidator\QuoteItemQtyListTest`) which will make sure the quantity calculation logic is performed correctly, according to the scenario you've just described above.
It can be easily accomplished by calling the `\Magento\CatalogInventory\Model\Quote\Item\QuantityValidator\QuoteItemQtyList::getQty` method with different sets of parameters and asserting the result.

Thank you!

**Comment by dmytro-ch** [comment]
Hello @molneek, I'm closing this PR now due to inactivity.
Feel free to reopen and update if you wish to continue.
Thank you!

**Comment by sichensol** [comment]
Hello @dmytro-ch, I've added a unit test as you asked, please verify this merge request one more time

**Comment by molneek** [comment]
@dmytro-ch I close this PR due to open the new one for the 2.4 version https://github.com/magento/magento2/pull/26650

**Pull request closed without merging**
