### PR TITLE
PHP unit fqcn annotation

### PR DESCRIPTION
**Pull request by MathiasReker**
PHPUnit annotations should be a FQCNs including a root namespace.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @MathiasReker. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
@MathiasReker what is the source of such recommendation? Should be combined with exception annotations removal to avoid conflict.

**Comment by MathiasReker** [comment]
Don't worry for conflicts, I made a script for each PR to solve any conflicts. It is a better practice. I don't have specific link to doc: https://phpunit.readthedocs.io/en/7.4/

**Comment by orlangur** [comment]
@MathiasReker ok. Exact link is needed though. Let's start from another PR where I mentioned the test based on `php-cs-fixer` is needed and then continue with all other your PRs.

Such scripts you write may be later used to implement corresponding `phpcs` or `php-cs-fixer` rules.

**Comment by MathiasReker** [comment]
This could be done with PHP CS fixer: `php ../php-cs-fixer.phar fix ./ --using-cache="no" --rules="php_unit_fqcn_annotation"`

**Pull request closed without merging**
