### PR TITLE
[Backport] fixed Product Advanced Pricing design issue #18775

### PR DESCRIPTION
**Pull request by gelanivishal**
### Original PR 
https://github.com/magento/magento2/pull/18790

### Description (*)
There was a small design issue die to app/code/Magento/Ui/view/base/web/templates/form/field.html file visible="$data.labelVisible" was on child element of the label, because of that parent was still visible even if the label visibility was false.

### Fixed Issues (if relevant)

1. magento/magento2#18775: Product Advanced Pricing design issue

### Manual testing scenarios (*)

1. login magento admin
2. goto catalog products
3: click on Add Product button
4: fill details then click on Advanced Pricing
5: in customer group price click Add

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3310](https://jira.corp.magento.com/browse/ENGCOM-3310) has been created to process this Pull Request

**Comment by sidolov** [comment]
Hi @gelanivishal , we can't reproduce the issue described in the PR. Please, provide additional steps for the issue. 
Thank you!

**Comment by sivaschenko** [comment]
Hi @gelanivishal , would you like to continue the progress on this PR?

**Comment by gelanivishal** [comment]
Hello @sivaschenko 

I can't find error in **Codacy/PR Quality Review**. If you find it then please guide me.

Thank you.

**Comment by sivaschenko** [comment]
Hi @gelanivishal , I believe that there is no need to fix static tests. However, as it was mentioned in https://github.com/magento/magento2/pull/18881#issuecomment-434343368 we cannot reproduce the issue described in your PR.

Could you confirm that the issue is still actual and provide more details for us to be able to reproduce the actual issue and verify the fix. Does it appear only in specific browsers? Could you attach a screenshot?

**Comment by VladimirZaets** [comment]
@gelanivishal, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Pull request closed without merging**
