### PR TITLE
Fix SKU limit in import new products

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

Fix SKU limit in import new product
### Fixed Issues (if relevant)

1. magento/magento2#17865: import new products via csv: products are created with empty value when strings are too long

### Manual testing scenarios (*)

1. prepare a correct csv to create new products via backend. Use short values (less then 71 characters) for name/sku for a few records, then use a longer strings ((more then 71 characters) for name/sku for other records.

2. go to system > import:
-- entity type = products
-- import behaviour = add/update, skip error entries
-- allow errors count = I tried with several numbers from 10 (default) to 500 but issue persists
-- field separator = ; (semicolon)
-- multiple value separator = , (comma, default)
-- field enclosure = unchecked (default)

3. Select the csv to import and run check data

4. when strings are too long, I expect to see an error after I run check data. I also expect that import get blocked until all error are fixed so no products gets created until the check data allows you to proceed with the import.
### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by slavvka — APPROVED** [review]
Thank you for the contribution!

**Comment by magento-engcom-team** [comment]
Hi @slavvka, thank you for the review.
[ENGCOM-3203](https://jira.corp.magento.com/browse/ENGCOM-3203) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@ravi-chandra3197 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by slavvka** [comment]
hey @ravi-chandra3197 During testing the fix we encountered with the problem:

Manual testing scenario:
1. Create simple product with SKU that contains 64 characters.
1. Click Save.
1. :white_check_mark: Product is successfully saved.
1. Prepare a correct csv to create new product with SKU that contains 64 characters.
1. Go to system > import:
  – entity type = products
  – import behaviour = add/update, skip error entries
  – allow errors count = I tried with several numbers from 10 (default) to 500 but issue persists
  – field separator = ; (semicolon)
  – multiple value separator = , (comma, default)
  – field enclosure = unchecked (default)
1. Select the csv to import and run check data
1. :x: Validation error "Attribute sku exceeded max length in row(s): 1".

:information_source: Problem is connected with strict comparison in line https://github.com/magento/magento2/pull/18639/files#diff-def2be563c3045d145e78b66496cbc02R74

**Comment by ravi-chandra3197** [comment]
@slavvka can you review it 
I have changed as per your suggestions now it allows the product with SKU that contains 64 characters.
and i have also update change on [Backport] Fix SKU limit in import new products #18591

**Review by slavvka — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @slavvka, thank you for the review.
[ENGCOM-3203](https://jira.corp.magento.com/browse/ENGCOM-3203) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
