### PR TITLE
Added a validation for the dimension and enable KGS to be a possible …

### LINKED ISSUE #38618: UPS REST "A shipment cannot have a KGS/IN or LBS/CM or OZS/CM as its unit of measurements"
### Preconditions and environment

Magento version 2.4.7

### Steps to reproduce

Set European Union as Origin of the Shipment in Sales->Delivery Methods->UPS

### Expected result

UPS rates is visible in checkout and cart.

### Actual result

No UPS rates is visible in checkout and cart.

### Additional information

Seems like UnitOfMeasurement is hardcoded to "IN".
If you have European Union (other origins may experience the same problem) as Origin of the Shipment this will cause an error in the UPS REST request:
"A shipment cannot have a KGS/IN or LBS/CM or OZS/CM as its unit of measurements"

1147         foreach ($rowRequest->getPackages() as $package) {
1148             $rateParams['RateRequest']['Shipment']['Package'][] = [
1149                 "PackagingType" => [
1150                     "Code" => "{$params['48_container']}",
1151                     "Description" => "Packaging"
1152                 ],
1153                 "Dimensions" => [
1154                     "UnitOfMeasurement" => [
1155                         "Code" => "IN",
1156                         "Description" => "Inches"
1157                     ],
1158                     "Length" => "5",
1159                     "Width" => "5",
1160                     "Height" => "5"
1161                 ],
1162                 "PackageWeight" => [
1163                     "UnitOfMeasurement" => [
1164                         "Code" => "{$rowRequest->getUnitMeasure()}"
1165                     ],
1166                     "Weight" => "{$this->_getCorrectWeight($package['weight'])}"
1167                 ]
1168             ];
1169         }

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by digitalrisedorset**
The UPS integration currently only works for the unit of measurement `Inches`. European shops who want to use UPS are not able to setup their Magento integration with Kgs. 

### Description (*)
The change enables the UPS module to work interchangeably with Inch or with Cm. The change is made when the UPS mode works with API integration. 

### Fixed Issues (if relevant)
1. Fixes magento/magento2#38618

### Manual testing scenarios (*)
The scope of the PR changes one mode of the UPS integration and that is the Rest mode with the UPS integration:
Enable the UPS shipping method
Setup the type with the Rest mode
The shipment origin setting requires a Postcode

**Use case 1:** this currently does not return rates and that is what the fix changes
Set the Shipping origin to be European 
Set the weight unit in Kgs
Ensure the currency for the country of origin is allowed in the system
validate UPS returns some shipping methods 

**Use case 2:**: backward compliance test
Set the Shipping origin to be United States 
Set the weight unit in Lbs
Ensure the currency for the country of origin is allowed in the system
validate UPS returns some shipping methods 

**Use case 3:**: backward compliance test / the unit Kg is not authorised for US origin
Set the Shipping origin to be United States 
Set the weight unit in Kgs
Ensure the currency for the country of origin is allowed in the system
validate UPS does not return any shipping methods 

### Questions or comments
I have attempted to add integration tests. There are many in place and I was hopeful to get at least one added for the use case of unit measure 'Kg' and origin 'EU' but I found that the blocker is that these tests mocks when the API call is triggered and that means we can't add tests for this issue as far as I see it

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by digitalrisedorset** [comment]
@magento run all tests

**Comment by sanmic** [comment]
@digitalrisedorset What's the current status of this ticket?

**Comment by digitalrisedorset** [comment]
@sanmic This PR is awaiting review and its change resolves the issue for the API mode of the shipment module

**Comment by engcom-Charlie** [comment]
The required changes of this issue has been published in https://github.com/magento/magento2/commit/493e01f54c8922c620fe9c9f2bfdd1aa536b9bb6 . Hence closing this PR now.

**Pull request closed without merging**
