### PR TITLE
Bundles and tier price give unexpected results

### PR DESCRIPTION
**Pull request by irajneeshgupta**
### Description (*)

qty 1 was hardcoded passed in `getSelectionFinalTotalPrice()` , changed it to selected qty to correct calculate the tier pricing.

### Fixed Issues (if relevant)

1. magento/magento2#22807: Bundles and tier price give unexpected results
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5164](https://jira.corp.magento.com/browse/ENGCOM-5164) has been created to process this Pull Request

**Comment by soleksii** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @stoleksiy. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @stoleksiy, here is your [new Magento instance](https://pr-22843.instances.magento-community.engineering).
Admin access: [https://pr-22843.instances.magento-community.engineering/admin](https://pr-22843.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by soleksii** [comment]
Hi @irajneeshgupta !

I've checked PR changes and looks like they do not fix the issue #22807 

**Preconditions:**

1 .Create a simple product with price $10.00 and tier price of $9.00 for 2 or more quantities;
2. Create a bundle product, with only one option, and add the simple product as the only selection, use _Quantity = 2_ and _User defined = unchecked_;

**Steps to reproduce:**

1. Go to the bundle product page on the frontend;
2. Select qty = 1 and click add to cart. Minicart shows correct prices (unit $18, total $18);
3. Without leaving the page, select qty = 2 and click add to cart. Minicart shows wrong prices (unit $36, total $108, should be $18/$54);

**Actual Result:**

after1

Could you take a look, please?!

**Comment by sidolov** [comment]
@irajneeshgupta , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
