### PR TITLE
Improve setup:di:compile performance by using gc_disable

### LINKED ISSUE #38035: [Issue] Improve setup:di:compile performance by using gc_disable
This issue is automatically created based on existing pull request: magento/magento2#38032: Improve setup:di:compile performance by using gc_disable

---------

### Description (*)

By disabling garbage collector the code generation finishes a bit faster:
1. Result for this `contribution repo`
Selection_755

With larger apps the difference is not that significant but noticeable
2.  
- 2 minutes without changes
Selection_758

- under 2 minutes with changes
Selection_757

I also checked calling `gc_collect_cycles` after each operation to save some memory, but the difference is not that significant and visible on the second screenshot.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Run setup:di:compile on different CPUs with and without changes
2. Compare execution time

### Questions or comments

1. More tests needed on different CPUs.
2. The actual result may vary per project, depending from number of plugins/factories/proxies needed to detect and generate.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ilnytskyi**
### Description (*)

By disabling garbage collector the code generation finishes a bit faster:
1. Result for this `contribution repo`
Selection_755

With larger apps the difference is not that significant but noticeable
2.  
- 2 minutes without changes
Selection_758

- under 2 minutes with changes
Selection_757

I also checked calling `gc_collect_cycles` after each operation to save some memory, but the difference is not that significant and visible on the second screenshot.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Run setup:di:compile on different CPUs with and without changes
2. Compare execution time

### Questions or comments

1. More tests needed on different CPUs.
2. The actual result may vary per project, depending from number of plugins/factories/proxies needed to detect and generate.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38035: Improve setup:di:compile performance by using gc_disable

### CODE REVIEW

**Comment by ilnytskyi** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Is that inspired by https://github.com/composer/composer/commit/ac676f4 https://blog.blackfire.io/performance-impact-of-the-php-garbage-collector.html ?

**Comment by engcom-Hotel** [comment]
@magento create issue

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ilnytskyi** [comment]
> Is that inspired by [composer/composer@ac676f4](https://github.com/composer/composer/commit/ac676f4) https://blog.blackfire.io/performance-impact-of-the-php-garbage-collector.html ?

@ihor-sviziev partially yes. There are other cases where this approach is used like PHPstan https://phpstan.org/blog/phpstan-1-6-0-with-conditional-return-types

**Comment by ihor-sviziev** [comment]
@engcom-Delta, any updates on testing these changes?

**Comment by hostep** [comment]
@ihor-sviziev: I believe testing results are availalbe on the associated issue: https://github.com/magento/magento2/issues/38035

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
:x: QA not Passed

We have tested the functionality of the below command with and without PR changes (on the vanilla instance), but the outcome is almost the same:

`time bin/magento setup:di:compile`

Please find below the screenshots of the outcome for reference:

_**Without PR Changes**_
image

_**With PR Changes**_
image

We are using the Mac environment to test this PR. Please review the PR changes and let us know if we missed anything.

Thanks

**Comment by engcom-Hotel** [comment]
Hi @ilnytskyi,

I trust you've reviewed this [comment](https://github.com/magento/magento2/pull/38032#issuecomment-1991245865). We haven't noticed significant differences with or without the PR changes. Kindly reconsider this and inform us if anything has been overlooked.

Thank you.

**Comment by engcom-Hotel** [comment]
Hello @ilnytskyi,

Thank you for your contribution!

As we have been unable to get any reply from your side for a long time, we are closing this PR for now. 

Whenever you are ready to take this up please free to reopen it or ask us to reopen the same. We will be happy to do that.

Thanks again!

**Pull request closed without merging**
