### PR TITLE
[2.4] [ISSUE-29299] Fix Build-in README installation command.

### LINKED ISSUE #29299: PHP build-in webserver readme cmd line installation command is outdated
### Preconditions (*)

Since ElasticSearch is required from 2.4 version we need to update README for a build-in webserver. 

There are missing ElasticSearch params that are required by default. Also, I'm also confused because copy-paste of installation command is not working, new line glue character should be added.

### Examples (*)
1. Missing ES params result:
https://prnt.sc/tpj4op

2. No glue character result:
https://prnt.sc/tpj62o

**Steps to reproduce:**
Open phpserver/README.MD
copy How to install Magento command and paste into the terminal

**Actual Result:**

**Expected Result:**
The installation must be successful

### Proposed solution
https://github.com/magento/magento2/pull/29300

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by progreg**
### Description (*)

Fix Build-in README installation command. 

- Add required ElasticSearch params since 2.4. 
- Add new line concatenation character

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29299

### Manual testing scenarios (*)

1. Open phpserver/README.MD
2. copy `How to install Magento` command and paste into the terminal

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-7910](https://jira.corp.magento.com/browse/ENGCOM-7910) has been created to process this Pull Request
:eight_spoked_asterisk: @swnsma, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Actual Result:** :heavy_check_mark: Magento was successfully installed.

Screenshot from 2020-07-29 11-05-39

Screenshot from 2020-07-29 11-06-33

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Pull request merged**
