### PR TITLE
Added a check quote is_active or not, because it removed quotes

### LINKED ISSUE #36898: [Issue] Added a check quote is_active or not, because it removed quotes
This issue is automatically created based on existing pull request: magento/magento2#36862: Added a check quote is_active or not, because it removed quotes

---------

### Description (*)

Somising went wrong while saving the customer.

- Magento version 2.4.3
- Anything else that would help a developer reproduce the bug:
  1. You need to have an order that was completed more than the number of days specified in the admin panel in the field Quote Lifetime (days).
  2. This order must also not be edited for the same number of days.
  3. You must have cron job enabled.

1. Go to the user who placed an order more than 30 days ago.
2. Try changing any of the fields.

The new data is not saved and I get the following error:
CleanShot 2022-11-18 at 09 40 20

After starting to look for the cause of this problem, I went to look in the var/log/system.log file where I found it:
Снимок экрана от 2023-02-14 19-43-00
Next I went to the database to find quote with entity_id = 173008 in quote table but it was not there.
Then I started looking for the reason why this record disappeared. 
I found the problem in vendor/magento/module-sales/Model/ResourceModel/Collection/ExpiredQuotesCollection.php
Function of this class getExpiredQuotes receives the collection of quotes and checks whether the quota is older than the number of days specified in one of the fields in the quote lifetime field but dont have check for quote is_active:
Снимок экрана от 2023-02-14 20-12-47
It turns out that the function returns all quotas that are older than n-number of days and then deletes them in the class -vendor/magento/module-sales/Cron/CleanExpiredQuotes.php

It turns out that without a check for quote is_active 1, Magenta uses cron to delete all fields of the quote table that are older than n-number of days, so when user data is changed, Magenta cannot find the quota associated with it and issues an error.
The solution to this problem is to add a check to see if the quota is active:
Снимок экрана от 2023-02-14 20-26-08

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

To test these changes you need:
1. Go to database - quote table
2. Update the `created_at` and `update_at` field values ​​a couple of days ago from today's date
3. Go to admin panel Stores->Configuration->Sales->Checkout->Shopping Cart->Quote LoifeTime(days) field and set 1 day
4. Start the cron job and you will see that records that have become orders will not be deleted, which will solve the problem. Only those that have not become orders are deleted

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by invade-agency**
### Description (*)

Somising went wrong while saving the customer.

- Magento version 2.4.3
- Anything else that would help a developer reproduce the bug:
  1. You need to have an order that was completed more than the number of days specified in the admin panel in the field Quote Lifetime (days).
  2. This order must also not be edited for the same number of days.
  3. You must have cron job enabled.

1. Go to the user who placed an order more than 30 days ago.
2. Try changing any of the fields.

The new data is not saved and I get the following error:
CleanShot 2022-11-18 at 09 40 20

After starting to look for the cause of this problem, I went to look in the var/log/system.log file where I found it:
Снимок экрана от 2023-02-14 19-43-00
Next I went to the database to find quote with entity_id = 173008 in quote table but it was not there.
Then I started looking for the reason why this record disappeared. 
I found the problem in vendor/magento/module-sales/Model/ResourceModel/Collection/ExpiredQuotesCollection.php
Function of this class getExpiredQuotes receives the collection of quotes and checks whether the quota is older than the number of days specified in one of the fields in the quote lifetime field but dont have check for quote is_active:
Снимок экрана от 2023-02-14 20-12-47
It turns out that the function returns all quotas that are older than n-number of days and then deletes them in the class -vendor/magento/module-sales/Cron/CleanExpiredQuotes.php

It turns out that without a check for quote is_active 1, Magenta uses cron to delete all fields of the quote table that are older than n-number of days, so when user data is changed, Magenta cannot find the quota associated with it and issues an error.
The solution to this problem is to add a check to see if the quota is active:
Снимок экрана от 2023-02-14 20-26-08

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

To test these changes you need:
1. Go to database - quote table
2. Update the `created_at` and `update_at` field values ​​a couple of days ago from today's date
3. Go to admin panel Stores->Configuration->Sales->Checkout->Shopping Cart->Quote LoifeTime(days) field and set 1 day
4. Start the cron job and you will see that records that have become orders will not be deleted, which will solve the problem. Only those that have not become orders are deleted

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36898: Added a check quote is_active or not, because it removed quotes

### CODE REVIEW

**Comment by invade-agency** [comment]
@magento run all tests

**Comment by invade-agency** [comment]
@magento run Static Tests, Functional Tests EE

**Comment by invade-agency** [comment]
https://github.com/magento run all tests

**Comment by invade-agency** [comment]
@magento run all tests

**Comment by invade-agency** [comment]
@magento run all tests

**Comment by invade-agency** [comment]
@magento run Integration Tests, Functional Tests EE, Functional Tests B2B

**Comment by invade-agency** [comment]
@magento run all tests

**Comment by invade-agency** [comment]
@magento run Functional Tests EE

**Comment by invade-agency** [comment]
@magento run Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento create issue

**Comment by invade-agency** [comment]
@magento run all tests

**Comment by invade-agency** [comment]
@magento run Functional Tests B2B

**Comment by invade-agency** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
Hi @invade-agency,
Since we can't reproduce the issue https://github.com/magento/magento2/issues/36898#issuecomment-1439446597, and we didn't get any updates from you, I'm closing this Pull request.

**Pull request closed without merging**
