### PR TITLE
Use registry to prevent potential event dispatch loop

### PR DESCRIPTION
**Pull request by graemelambert**
Something I've come across during Magento 1 development recently is the potential to get into an event dispatch loop.

Example: order is saved, sales_order_save_after event is dispatched, an observer does something off the back of the event and changes a field on the order, triggering the process again.

### CODE REVIEW

**Comment by fooman** [comment]
Wouldn't it be better to throw an exception in this case so that the developer can fix the infinite loop rather than allowing for it?

**Comment by jameshalsall** [comment]
-1 for this.

This is not something that should be fixed in Magento, rather something that should be fixed in your logic.

**Comment by dsikkema-magento** [comment]
Hi @graemelambert, thank you for your contribution. Due to the concerns pointed out above, I don't think we can accept this implementation, but we would welcome a way to improve how infinite event loops are handled.

What behavior do you see in M2 when you get that loop? I think we should throw an error that makes it clear what the source of the problem is, and break the infinite loop -- if that is not the current behavior, would you consider updating your pull request to throw such an exception when it detects an event cycle?

**Comment by dsikkema-magento** [comment]
Internal ticket created: MAGETWO-49731

**Comment by dsikkema** [comment]
Internal ticket created: MAGETWO-49731

**Comment by dsikkema-magento** [comment]
@graemelambert, Thanks for your contribution, but we're going to go ahead and close this for now due to concerns listed above.

**Pull request closed without merging**
