### PR TITLE
MFTF: Refactoring AdminUrlRewritesForProductInAnchorCategoriesTestWithConfi…

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
AdminUrlRewritesForProductInAnchorCategoriesTestWithConfigurationTurnedOffTest is refactored according to the best practices followed by MFTF.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
Run AdminUrlRewritesForProductInAnchorCategoriesTestWithConfigurationTurnedOffTest in the local environment and verified the test runs successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by dmytro-ch** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by dmytro-ch** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-28418.instances.magento-community.engineering).
Admin access: [https://pr-28418.instances.magento-community.engineering/admin_3627](https://pr-28418.instances.magento-community.engineering/admin_3627)
Login: `ba610d38` Password: `5edf017523b7`
Instance will be terminated in up to 3 hours.

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello @kate-kyzyma.
Looks like there is an issue with one of the ancestor test.
Could you please evaluate and apply the appropriate changes if necessary?

Thank you!

**Comment by kate-kyzyma** [comment]
Hello @dmytro-ch 
I have updated the child test. Please, check.

Thanks.

**Comment by dmytro-ch** [comment]
@magento run all tests

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7607](https://jira.corp.magento.com/browse/ENGCOM-7607) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
