### PR TITLE
Replace repetitive actions with Action Groups in AdminUpdateTopCategoryUrlWithNoRedirectTest and AdminUpdateTopCategoryUrlWithRedirectTest

### LINKED ISSUE #33774: [Issue] Replace repetitive actions with Action Groups in AdminUpdateTopCategoryUrlWithNoRedirectTest and AdminUpdateTopCategoryUrlWithRedirectTest
This issue is automatically created based on existing pull request: magento/magento2#30562: Replace repetitive actions with Action Groups in AdminUpdateTopCategoryUrlWithNoRedirectTest and AdminUpdateTopCategoryUrlWithRedirectTest

---------

### Description (*)
The tests are refactored according to the best practices followed by MFTF.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)
Run tests in the local environment and verified that it run successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
The tests are refactored according to the best practices followed by MFTF.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)
Run tests in the local environment and verified that it run successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#33774: Replace repetitive actions with Action Groups in AdminUpdateTopCategoryUrlWithNoRedirectTest and AdminUpdateTopCategoryUrlWithRedirectTest

### CODE REVIEW

**Review by dmytro-ch — APPROVED** [review]

**Comment by dmytro-ch** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-8434](https://jira.corp.magento.com/browse/ENGCOM-8434) has been created to process this Pull Request

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello @kate-kyzyma, could you please check the failed tests?

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Semantic Version Checker

**Comment by dmytro-ch** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by dmytro-ch** [comment]
@magento run Functional Tests CE

**Comment by kate-kyzyma** [comment]
@magento run Semantic Version Checker

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by kate-kyzyma** [comment]
Hi @dmytro-ch!
I have fixed Semantic issues. As for B2B and CE failed tests, it not related to my changes.

Please, check current changes.
Thanks.

**Comment by dmytro-ch** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-8434](https://jira.corp.magento.com/browse/ENGCOM-8434) has been created to process this Pull Request

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run Functional Tests CE, Integration Tests, Unit Tests

**Comment by dmytro-ch** [comment]
@magento run Functional Tests CE

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-8434](https://jira.corp.magento.com/browse/ENGCOM-8434) has been created to process this Pull Request

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8434](https://jira.corp.magento.com/browse/ENGCOM-8434) has been created to process this Pull Request

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Pull request merged**
