### PR TITLE
URL Key already exist error coming if we give same name for two produ…

### PR DESCRIPTION
**Pull request by yurii-v-git**
…cts. #21860

### Description (*)
Creating unique URL key for the new product.  
When a new product is creating and the admin has not filled the URL key field in the product edit form the unique URL key will be created.

### Fixed Issues (if relevant)

1.#21860: URL Key already exists error coming if we give the same name for two products. 

### Manual testing scenarios (*)

1.  Create a Product from Magento Admin and set visibility to catalog & search or catalog or search.
2.  Create another product with the same name. And select visibility catalog & search or catalog or search.
3. The second product has a unique URL key(it's modified like SKU)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22066) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=22066) before we can accept your contribution.<br/><hr/>**Yuriy** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by rogyar** [comment]
Hi @yvechirko. Please, sign CLA. It's required operation for processing a PR. Thank you

**Comment by hostep** [comment]
@yvechirko: just a question/remark, a url key can be non-unique as long as it isn't defined in the same store view. Does your code keep that in mind? At first sight of your code, it looks at uniqueness over all store views, but that's not correct.

So to clarify: if you have 2 store views: en_us & en_gb for example, then it is allowed to have 2 url key's which are 100% the same, one defined in the en_us store view, and the other in the en_gb store view.

**Comment by orlangur** [comment]
Closing as bug report is invalid.

**Pull request closed without merging**
