### PR TITLE
issue fixed #22388

### LINKED ISSUE #22388: Admin panel Product Stock status is not automatically getting updated from out of stock to in-stock
### Preconditions (*)

1. Magento 2.3.0
2. Magento Admin panel 

### Steps to reproduce (*)

1. Login to the Admin panel
2. Navigate to catalog -> product
3. Select preferred product OR Click on Add new product  button
4. On product page change quantitiy to 0  and save then system automatically changing the stock status to "Out-of-stock".
5. Now again change the quantity to more than 0 and save, observe in this case system is not automatically changing stock status to "Instock"

### Expected result (*)
1. When qty is updated more than 0 then system should automaticaaly change the stock status to "Instock"

### Actual result (*)

1. After updating the qty to more than 0, stock status is not updating to "Instock" automatically. 

Please refer to the attached screen shot. 
https://drive.google.com/file/d/1pZsHG3uL3afPGim8-h30nsT7ejSmMK9u/view

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)
Admin panel Product Stock status is not automatically getting updated from out of stock to in-stock when product quantity is changed from 0 to a positive number

### Fixed Issues (if relevant)

1. #22388 Admin panel Product Stock status is not automatically getting updated from out of stock to in-stock

### Manual testing scenarios (*)

1. Login to admin panel
2. Go to Catalog->Products
3. Edit any product that is out of stock with 0 quantity
4. Enter quantity 1 or any positive number
5. Save the product to see 'Stock Status' change to 'In Stock'

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22688) <br/>All committers have signed the CLA.

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@magento run Database Compare build

**Comment by slavvka** [comment]
Hey @webkul-paul Since we are not sure it is a bug (https://github.com/magento/magento2/issues/22388#issuecomment-519226325) this PR gets on hold until the solution

**Comment by slavvka** [comment]
@webkul-paul thank you for your efforts but according to our PO this ii not a bug:

> this is definitely not a bug, product stock status should not be updated automatically to “In stock” when quantity is updated, this should be done manually.

**Comment by ghost** [comment]
@slavvka 
But in Magento 2.2.9, changing quantity to 1 or higher changes stock status to 'In Stock' from 'Out of Stock'. Then why not in 2.3.x ?

**Comment by slavvka** [comment]
@webkul-paul that fix was approved mistakenly. To be good it should be reverted

**Pull request closed without merging**
