### PR TITLE
AC-2039 AC-1667 upgrade TinyMCE references

### LINKED ISSUE #38533: [Issue] AC-2039 AC-1667 upgrade TinyMCE references
This issue is automatically created based on existing pull request: magento/magento2#36543: AC-2039 AC-1667 upgrade TinyMCE references

---------

### Description (*)

[AC-2039](https://jira.corp.adobe.com/browse/AC-2039) and  https://github.com/magento/magento2/commit/32b3a36af7588f4fad3ef5803e41fc65757a7fbb already upgraded TinyMCE to >= 5.10, and only the reference in magento/magento2-base is wrong.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by AntonEvers**
### Description (*)

[AC-2039](https://jira.corp.adobe.com/browse/AC-2039) and  https://github.com/magento/magento2/commit/32b3a36af7588f4fad3ef5803e41fc65757a7fbb already upgraded TinyMCE to >= 5.10, and only the reference in magento/magento2-base is wrong.

### Manual testing scenarios (*)

    1. Hit composer install
    2. Verify the TinyMCE version from 3.4.7 to 5.10.2 
### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38533: AC-2039 AC-1667 upgrade TinyMCE references

### CODE REVIEW

**Comment by AntonEvers** [comment]
@magento run all tests

**Comment by AntonEvers** [comment]
Looks like this Functional Tests EE failure is a false positive. Not related to the change I made.

**Review by fredden — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run all tests

**Review by engcom-Lima — DISMISSED** [review]
Hi @AntonEvers ,

Thanks for the collaboration & contribution!

### :x: QA not Passed

After taking PR changes issue was not resolved. Getting error in the console:
```
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/product-community-edition is locked to version 2.4.3-p1 and an update of this package was not requested.
    - roave/security-advisories dev-latest conflicts with tinymce/tinymce <5.10 (magento/magento2-base 2.4.3-p1 replaces tinymce/tinymce 3.4.7).
    - magento/product-community-edition 2.4.3-p1 requires magento/magento2-base 2.4.3-p1 -> satisfiable by magento/magento2-base[2.4.3-p1].
    - Root composer.json requires roave/security-advisories dev-latest -> satisfiable by roave/security-advisories[dev-latest].


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Manual Scenario Steps**
- Run `composer require --dev roave/security-advisories:dev-latest`

**:heavy_check_mark: Expected result After Fix**  Command should run successfully.



**:x: Actual result After Fix** Getting error after running the command
```
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/product-community-edition is locked to version 2.4.3-p1 and an update of this package was not requested.
    - roave/security-advisories dev-latest conflicts with tinymce/tinymce <5.10 (magento/magento2-base 2.4.3-p1 replaces tinymce/tinymce 3.4.7).
    - magento/product-community-edition 2.4.3-p1 requires magento/magento2-base 2.4.3-p1 -> satisfiable by magento/magento2-base[2.4.3-p1].
    - Root composer.json requires roave/security-advisories dev-latest -> satisfiable by roave/security-advisories[dev-latest].


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```
image

Kindly recheck the PR.

**Comment by fredden** [comment]
@engcom-Lima the error message you've shared suggests that you're using an (old) released version of Magento (2.4.3-p1), not the version in this pull request. Please can you try again.

Also, the changes here are not dependent on `roave/security-advisories`, but are instead fixing an internal inconsistency within Magento where it supplies version 5.x of a certain library, but incorrectly advertises the same as version 3.x. The fact that this fixes the problem described in https://github.com/magento/magento2/issues/34562 is a side-effect.

**Comment by fredden** [comment]
@engcom-Lima @engcom-Hotel please can you provide an update on this pull request?

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
Hi @fredden, Thank you for your contribution. We have tested this PR again today and here are the actual results.

Steps to reproduce:
1.Run composer require --dev roave/security-advisories:dev-latest or composer update --dry-run roave/security-advisories (if package already installed)

We are getting the below error in the PR branch 

Actual result:


Screenshot 2024-03-18 at 5 59 11 PM


Expected result: Command should run successfully.

Please let us know if we are missing something.

**Comment by engcom-Delta** [comment]
> @engcom-Lima the error message you've shared suggests that you're using an (old) released version of Magento (2.4.3-p1), not the version in this pull request. Please can you try again.
> 
> Also, the changes here are not dependent on `roave/security-advisories`, but are instead fixing an internal inconsistency within Magento where it supplies version 5.x of a certain library, but incorrectly advertises the same as version 3.x. The fact that this fixes the problem described in #34562 is a side-effect.

Hi @fredden , Thank you for your reply. Could you please elaborate this statement for better understanding ?

**Comment by fredden** [comment]
@engcom-Delta this pull request is nothing to do with the `roave/security-advisories` package. Testing of this pull request should not involve that package.

In order to verify the changes being proposed here, please compare the version strings listed in the TinyMCE files with what is being claimed in `composer.json`. These version numbers should match.

**Before** these changes (ie, current HEAD = b2286ecfb014dbe05a45004526541aa8250259c2):

https://github.com/magento/magento2/blob/b2286ecfb014dbe05a45004526541aa8250259c2/composer.json#L346
https://github.com/magento/magento2/blob/b2286ecfb014dbe05a45004526541aa8250259c2/lib/web/tiny_mce_5/tinymce.min.js#L7
https://github.com/magento/magento2/blob/b2286ecfb014dbe05a45004526541aa8250259c2/lib/web/tiny_mce_5/plugins/help/plugin.min.js#L7
etc

**After** these changes (ie, this branch = b22afb235f433b4eda2d42aa5ae28bca25260097):

https://github.com/magento/magento2/blob/b22afb235f433b4eda2d42aa5ae28bca25260097/composer.json#L346
https://github.com/magento/magento2/blob/b22afb235f433b4eda2d42aa5ae28bca25260097/lib/web/tiny_mce_5/tinymce.min.js#L7
https://github.com/magento/magento2/blob/b22afb235f433b4eda2d42aa5ae28bca25260097/lib/web/tiny_mce_5/plugins/help/plugin.min.js#L7
etc


I recommend that this pull request is accepted as-is, and a separate pull request should be opened to update the TinyMCE libraries to a version which is compatible with the `roave/security-advisories` package.

**Comment by hostep** [comment]
@fredden: do we know why these lines are part of the `composer.json` files? It's in the `replace` section, but there is nothing installing this package, so in my opinion these lines can just be removed entirely, no?

The same can be said about:
```
- trentrichardson/jquery-timepicker-addon
- components/jquery
- components/jqueryui
- twbs/bootstrap
```

**Comment by fredden** [comment]
@hostep no, I don't know for sure. I /think/ it's so that we don't get duplicate copies of the library if another Composer package were to list it as a requirement of their package. Magento includes TinyMCE (and jQuery etc) by default, so these lines ensure that another copy isn't pulled in via Composer "unnecessarily". It would also protect against another package pulling in `^5.0 || ^6.0` and then getting v6.x.x which may or may not be compatible with Magento itself, leading to hard-to-diagnose bugs.

**Comment by hostep** [comment]
Pffff, I vote we get rid of these lines, nothing of this makes sense to me.

A Magento intallation won't automatically pickup tinymce libraries installed via `tinymce/tinymce`, they are manually maintained in `lib/web`.

If somebody would install TinyMCE via composer (no idea why, because it's a javascript library, you have npm/yarn/... for that ecosystem), they will still have to do manual work to get those files included in the Magento frontend. So in my opinion there isn't much risk with allowing people to install `tinymce/tinymce` via composer ...

**Comment by fredden** [comment]
@hostep yes, this sounds sensible to me.

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

1.Run composer install
2.Verify the version of TinyMCE on composer.json
3.Verify the version of TinyMCE on magento2/lib/web/tiny_mce_5/tinymce.min.js
4.Verify the version of TinyMCE on magento2/lib/web/tiny_mce_5/plugins/help/plugin.min.js
5.Verify version is upgraded to TinyMCE from 3.4.7 to 5.10.2


**Before:** :heavy_multiplication_x: 

Screenshot 2024-03-20 at 5 57 06 PM

Screenshot 2024-03-20 at 6 15 56 PM

Screenshot 2024-03-20 at 6 16 35 PM


**After:** :heavy_check_mark:  

Screenshot 2024-03-20 at 6 20 14 PM

Screenshot 2024-03-20 at 6 24 54 PM

Screenshot 2024-03-20 at 6 25 26 PM

Screenshot 2024-03-20 at 6 25 50 PM


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Delta** [comment]
@magento create issue

**Comment by engcom-Delta** [comment]
As per the below comment on this PR, we are taking care of upgrade TinyMCE references and not the roave/security-advisories package. So adding additional description on this PR.

https://github.com/magento/magento2/pull/36543#issuecomment-2003839424

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by hostep** [comment]
TinyMCE was further upgraded from v5 to v7.3.0 in https://github.com/magento/magento2/commit/dce0ae5cccc04c38bfaa3aed39d23d4a7d0b1331, so I think this PR should be updated to reflect that, no?

**Comment by engcom-Charlie** [comment]
The functional EE failure is same in both the recent build run but the fialure is a known issue. It is not failing because of the PR changes. 

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36543/52f00c488ad36ebacb9d258bc015348d/Functional/allure-report-ee/index.html#categories

image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36543/ea5211bae0f372403129e4e98962dbde/Functional/allure-report-ee/index.html

image

**Known issues :**
StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest: [#ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331)


The functional B2B failures are not similar in recent 2 runs, seems to be flaky.
**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36543/0bad9e04b57a05afad30620876f6ac00/Functional/allure-report-b2b/index.html

image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36543/bfcfda4d8008fab8f3cbec9a348b6246/Functional/allure-report-b2b/index.html#categories

image

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-11681 by the internal team
Related commits: https://github.com/magento/magento2/commit/b34c0a75a79d5f60246273397d4e7d10ab89e994

Based on the Jira ticket, the target version is 2.4.8-beta1.

Thanks

**Comment by hostep** [comment]
Thanks! A cleaner commit to reference is this one: https://github.com/magento/magento2/commit/ea4e2175becd6c8bececab4ed86b8ab167f66a0d

**Pull request merged**
