### PR TITLE
magento/magento2#32990: Date and Time Format for Custom Option Not Working

### LINKED ISSUE #32990: Date and Time Format for Custom Option Not Working
### Preconditions (*)

1. Magento ver. 2.4.2
2. Nginx 1.18.0 (Ubuntu)
3. Maria DB 10.3.25

### Steps to reproduce (*)

1. [Follow these Steps](https://docs.magento.com/user-guide/stores/attribute-date-time-options.html) to Configure Date format
2. Check Date of Product with Custom Options of type Date

### Expected result (*)

1. Date Format Should Change on Front-end

### Actual result (*)

1. See result Below

https://user-images.githubusercontent.com/51072292/117776610-353bae00-b255-11eb-90f2-37dab6fe7f0c.mp4

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ *] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by NitrogenUA**
### Description (*)

Fixed Catalog Date & Time Custom Options not honoring Date Fields Order when JS calendar is used.

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/32990

### Manual testing scenarios (*)

1. In admin panel under Stores -> Configuration -> Catalog -> Date & Time Custom Options configure Date Fields Order.
2. Modify any product by adding a Customizable Option of Date type.
3. On frontend verify that observed custom option date of that product matches configuration from step 1.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by NitrogenUA** [comment]
@magento run all tests

**Comment by NitrogenUA** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @NitrogenUA,

Thanks for your contribution!

The changes look good to me. However, please cover the changes with some automated tests in accordance with the [Definition of Done (DOD)](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1).

Thanks

**Comment by engcom-November** [comment]
I have added MFTF test coverage.

**Comment by engcom-November** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @engcom-November,

Please made the changes as per our discussion.

Thanks

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi @NitrogenUA,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- In admin panel under Stores -> Configuration -> Catalog -> Date & Time Custom Options configure Date Fields Order.
- Modify any product by adding a Customizable Option of Date type.
- On frontend verify that observed custom option date of that product matches configuration from step 1.


**Before:** :heavy_multiplication_x: 

Screenshot 2024-08-14 at 11 54 53


Screenshot 2024-08-14 at 11 55 05


**After:** :heavy_check_mark: 


Screenshot 2024-08-14 at 12 03 15






Screenshot 2024-08-14 at 12 03 08





Screenshot 2024-08-14 at 12 01 15



Verified all the Different Combinations.Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

**Comment by engcom-November** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-November** [comment]
The repeating failure in Functional Tests B2B and Functional Tests EE are falky and known issues.

**Functional Tests B2B**
**Run 1:**
image

**Run 2:**
image

**Known issues:**
[ACQE-6801](https://jira.corp.adobe.com/browse/ACQE-6801) - StorefrontCheckoutProcessForQuoteWithoutNegotiatedPricesTest

**Functional Tests EE**
**Run 1:**
image

**Run 2:**
image

**Known issues:**
[ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331) - StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest

Hence moving this to **Merge in prrogress**.

**Pull request merged**
