### PR TITLE
Remove Extra White Spaces within HTML

### PR DESCRIPTION
**Pull request by nikoelgatito**
### Description (*)

While the template itself might look better when superposed, the resulting HTML is a link with additional spaces on each sides which doesn't look good on hover when underlined.

### Questions or comments

Note: As all top links should use the same pattern, wrapping the label within a span tag wasn't an option.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [X] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by Stepa4man — CHANGES_REQUESTED** [review]
Hi @nikoelgatito 
Thanks for your contribution

Please check failed tests.
(**updates** you don't need to add strict types declaration)

**Comment by hostep** [comment]
Hi @Stepa4man!
I'm pretty sure `declare(strict_types=1);` should only be added to **php** files, not to **phtml** files. If I search the current codebase of Magento 2, there are **0 phtml files** with `declare(strict_types=1);` and **3637 php files** which do have it.
So I don't think that requirement is valid in scope of this fix?

**Comment by Stepa4man** [comment]
> Hi @Stepa4man!
> I'm pretty sure `declare(strict_types=1);` should only be added to **php** files, not to **phtml** files. If I search the current codebase of Magento 2, there are **0 phtml files** with `declare(strict_types=1);` and **3637 php files** which do have it.
> So I don't think that requirement is valid in scope of this fix?

That's true, you are right.

**Comment by engcom-Echo** [comment]
Hi @nikoelgatito. Please sign CLA.

**Comment by mrtuvn** [comment]
@nikoelgatito my PR in https://github.com/magento/magento2/pull/27340 already do such thing

**Comment by Stepa4man** [comment]
I'm closing this PR due to inactivity. If you are planning to continue work, please open it again. Thanks.

**Pull request closed without merging**
