### PR TITLE
[MFTF] use ActionGroup go to AdminTaxRuleGridPage

### PR DESCRIPTION
**Pull request by Usik2203**
This PR creates and uses `AdminTaxRuleGridOpenPageActionGroup` to go to `AdminTaxRuleGridPage`

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by rogyar** [comment]
@magento run Functional Tests EE

**Review by rogyar — APPROVED** [review]
The failing tests are not related to the current changeset

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7806](https://jira.corp.magento.com/browse/ENGCOM-7806) has been created to process this Pull Request

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA not applicable

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Pull request merged**
