### PR TITLE
Zero payment Order processing status fix

### LINKED ISSUE #29907: [Issue] Zero payment Order processing status fix
This issue is automatically created based on existing pull request: magento/magento2#28513: Zero payment Order processing status fix

---------
### Description (*)
Current PR extends Free payment method class to set correct order status if status selected as processing and "auto create invoices" set to NO

### Manual testing scenarios (*)
  1. Update Zero Subtotal Checkout Method configuration in admin to use status Processing and 
automatically invoice items to NO
 2. Finish order with no payment required, easiest way is create coupon with 100% discount and use free shipping
3. Check newly create order status is processing, actual result pending

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by alekszakatov**
### Description (*)
Current PR extends Free payment method class to set correct order status if status selected as processing and "auto create invoices" set to NO

### Manual testing scenarios (*)
  1. Update Zero Subtotal Checkout Method configuration in admin to use status Processing and 
automatically invoice items to NO
 2. Finish order with no payment required, easiest way is create coupon with 100% discount and use free shipping
3. Check newly create order status is processing, actual result pending

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29907: Zero payment Order processing status fix

### CODE REVIEW

**Comment by alekszakatov** [comment]
@magento run all tests

**Comment by alekszakatov** [comment]
@magento run all tests

**Comment by kodubovik** [comment]
@magento run all tests

**Comment by alekszakatov** [comment]
@magento run all tests

**Comment by alekszakatov** [comment]
@magento run all tests

**Comment by alekszakatov** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
@magento create issue

**Comment by lenaorobei** [comment]
Hi @alekszakatov. Could you please provide more details about the issue you are experiencing? I see manual test steps, but could you please add expected and actual results and say more abut use case when it appears.

Would really appreciate it.

**Comment by lenaorobei** [comment]
Closing this PR due to inactivity. Please feel free to reopen if you are going to continue working on it.
Thank you.

**Pull request closed without merging**
