### PR TITLE
Changed class description in auto generated patch

### PR DESCRIPTION
**Pull request by SilinMykola**
I changed description in Magento\MediaGalleryUi\Setup\Patch\Data\AddMediaGalleryPermissions class.
Also I changed aliases order.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by SilinMykola** [comment]
@magento run all tests

**Review by andrewbess — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, thank you for the review.
[ENGCOM-9113](https://jira.corp.magento.com/browse/ENGCOM-9113) has been created to process this Pull Request
:eight_spoked_asterisk: @andrewbess, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9113](https://jira.corp.magento.com/browse/ENGCOM-9113) has been created to process this Pull Request

**Comment by Den4ik** [comment]
@magento run WebAPI Tests, Unit Tests, Functional Tests EE, Functional Tests B2B

**Comment by SilinMykola** [comment]
@magento run Functional Tests EE

**Review by ledian-hymetllari — APPROVED** [review]

**Comment by Den4ik** [comment]
@magento run Functional Tests EE

**Review by andrewbess — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, thank you for the review.
[ENGCOM-9113](https://jira.corp.magento.com/browse/ENGCOM-9113) has been created to process this Pull Request

**Comment by andrewbess** [comment]
This PR has already been merged

**Pull request merged**
