### PR TITLE
["Save in New Attribute Set"] : Form should be validated before prompt the popup

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

- In backend
- Go to create New Product form
- Add Attribute
- Create New Attribute
- "Save in New Attribute Set" without fill " Attribute Label"

We should validate the form when the user click "Save in New Attribute Set". Currently, the popup "Enter Name for New Attribute Set" is shown, and after the user fill the name and click ok, it validates => waste time for the user. We can save it by validate before the popup is shown.

### Manual testing scenarios (*)

- In backend
- Go to create New Product form
- Add Attribute
- Create New Attribute
- "Save in New Attribute Set" without fill " Attribute Label"
=> The form is validated 
If the user fill  "Attribute Label", it will show the popup

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by dmytro-ch** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [Magento instance](https://i-25132-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25132-2-3-develop.instances.magento-community.engineering/admin](https://i-25132-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dmytro-ch** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-25132.instances.magento-community.engineering).
Admin access: [https://pr-25132.instances.magento-community.engineering/admin](https://pr-25132.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6131](https://jira.corp.magento.com/browse/ENGCOM-6131) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
