### PR TITLE
Fix: addFilterToMap function is not working for certain columns #3619

### LINKED ISSUE #36719: addFilterToMap function is not working for certain columns
### Preconditions and environment

Magento 2.4.5-p1

There an issue related with addFilterToMap function on custom grid collection used in custom admin grid. If you map column with name `created_at` it will conflicts with same column in joined table in `where` condition.  It seems that new plugin `Magento\Sales\Plugin\Model\ResourceModel\Order\OrderGridCollectionFilter` in `aroundAddFieldToFilter` function ignores AbstractDb's mapper   `_getMappedField` that called inside `_translateCondition`. In this case you get error "SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous".

### Steps to reproduce

1. Create custom grid in admin based on table that has  `created_at` column
2. Rewrite `_initSelect` to add join with another table that also has `created_at` column and after that apply filter map `$this->addFilterToMap('created_at', 'main_table.created_at'); `
3. Apply filter on the grid by 'created_at'  field or you can just apply `addFieldToFilter` by `created_at` column programmatically on you collection

### Expected result

filtering of a collection by mapped  column `created_at` works without errors and uses applied filter mapping

### Actual result

applied filter mapping for `created_at` column not working. Getting error`SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous`.

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by ananth-iyer**
### Description (*)

1. Fix: addFilterToMap function is not working for certain columns #36719

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36719

### Manual testing scenarios (*)

1. Create custom grid in admin based on table that has created_at column
2. Rewrite _initSelect to add join with another table that also has created_at column and after that apply filter map $this->addFilterToMap('created_at', 'main_table.created_at'); 
3. Apply filter on the grid by 'created_at' field or you can just apply addFieldToFilter by 4. created_at column programmatically on you collection

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ananth-iyer** [comment]
@magento run all tests

**Comment by ananth-iyer** [comment]
@magento run Unit Tests

**Comment by ananth-iyer** [comment]
@magento give me test instance with edition b2b

**Comment by ananth-iyer** [comment]
https://github.com/magento run all tests

**Comment by ananth-iyer** [comment]
@magento run all tests

**Comment by ananth-iyer** [comment]
@magento run all tests

**Comment by ananth-iyer** [comment]
@magento run Integration Tests

**Comment by ananth-iyer** [comment]
@magento run Functional Tests EE

**Comment by ananth-iyer** [comment]
@magento run all tests

**Comment by ananth-iyer** [comment]
@magento run Functional Tests B2B

**Comment by ananth-iyer** [comment]
@magento run Functional Tests B2B

**Comment by ananth-iyer** [comment]
@magento run Functional Tests B2B

**Comment by ananth-iyer** [comment]
@magento run all tests

**Comment by ananth-iyer** [comment]
@magento run Integration Tests

**Comment by ananth-iyer** [comment]
@magento run Functional Tests CE

**Comment by ananth-iyer** [comment]
@magento run Functional Tests B2B

**Comment by ananth-iyer** [comment]
@magento run Functional Tests B2B

**Comment by ananth-iyer** [comment]
@magento run Functional Tests B2B

**Comment by ananth-iyer** [comment]
@magento run Functional Tests B2B

**Comment by ananth-iyer** [comment]
@magento run all tests

**Comment by ananth-iyer** [comment]
@magento run Functional Tests EE

**Comment by ananth-iyer** [comment]
@magento run all tests

**Comment by ananth-iyer** [comment]
@magento run all tests

**Comment by ananth-iyer** [comment]
@magento run Functional Tests EE

**Comment by ananth-iyer** [comment]
@magento run all tests

**Comment by ananth-iyer** [comment]
@magento run Functional Tests CE

**Comment by ananth-iyer** [comment]
@magento run Functional Tests CE

**Comment by ananth-iyer** [comment]
@magento run all tests

**Comment by ananth-iyer** [comment]
@magento run Functional Tests CE

**Comment by ananth-iyer** [comment]
@magento run WebAPI Tests

**Comment by ananth-iyer** [comment]
@magento run Functional Tests EE

**Comment by ananth-iyer** [comment]
@magento run Functional Tests CE

**Comment by ananth-iyer** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ananth-iyer** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by glanujnehra** [comment]
This PR is in development by an internal team, it will be completed and delivered to the mainline according to our standards and processes. All the original community commits will be preserved.

**Pull request merged**
