### PR TITLE
Fix non-working regenerate flag

### LINKED ISSUE #39152: [Issue] Fix non-working regenerate flag
This issue is automatically created based on existing pull request: magento/magento2#39140: Fix non-working regenerate flag

---------
### Description (*)

The functionality around the regenerate flag (file `var/.regenerate`) seems broken for some time already. The flag is meant to wipe out generated code (from the `generated/` folder). However, this does not much.

### Manual testing scenarios (*)

To test for this:
```bash
touch var/.regenerate
mkdir -p generated/code/
touch generated/code/test
```

Expected behaviour: A lock file `var/.regenerate.lock` is generated, the generated code (and specifically, the dummy file `generated/code/test`) is removed and the lock is removed as well, simply by reloading the Magento application (a refresh on the frontend, a call upon `bin/magento`, or something similar) while in the Developer Mode.

Actual behaviour: The `var/.regenerate` just sits there, doing nothing. Likewise, the dummy file `generated/code/test` is still there.

The reason for this is quite simple: Within the main class `\Magento\Framework\Code\GeneratedFiles`, the flag is defined via a constant https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Code/GeneratedFiles.php#L24 with a value `/var/.regenerate` (an absolute path) and not `var/.regenerate` (a relative path). Because of this, the write call `isExists()` fails validation https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Code/GeneratedFiles.php#L123 and therefore the flag is never picked up upon.

Changing the constant value to `var/.regenerate` makes sure (on my side) that the generated files are cleaned up properly.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by jissereitsma**
### Description (*)

The functionality around the regenerate flag (file `var/.regenerate`) seems broken for some time already. The flag is meant to wipe out generated code (from the `generated/` folder). However, this does not much.

### Manual testing scenarios (*)

To test for this:
```bash
touch var/.regenerate
mkdir -p generated/code/
touch generated/code/test
```

Expected behaviour: A lock file `var/.regenerate.lock` is generated, the generated code (and specifically, the dummy file `generated/code/test`) is removed and the lock is removed as well, simply by reloading the Magento application (a refresh on the frontend, a call upon `bin/magento`, or something similar) while in the Developer Mode.

Actual behaviour: The `var/.regenerate` just sits there, doing nothing. Likewise, the dummy file `generated/code/test` is still there.

The reason for this is quite simple: Within the main class `\Magento\Framework\Code\GeneratedFiles`, the flag is defined via a constant https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Code/GeneratedFiles.php#L24 with a value `/var/.regenerate` (an absolute path) and not `var/.regenerate` (a relative path). Because of this, the write call `isExists()` fails validation https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Code/GeneratedFiles.php#L123 and therefore the flag is never picked up upon.

Changing the constant value to `var/.regenerate` makes sure (on my side) that the generated files are cleaned up properly.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#39152: Fix non-working regenerate flag

### CODE REVIEW

**Comment by engcom-Hotel** [comment]
@magento create issue

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @jissereitsma,

Thanks for the report and collaboration!

The changes seems good to me, but there are some static tests failures. Please fix them.

Thanks

**Comment by engcom-Charlie** [comment]
It seems that the review changes mentioned in [comment](https://github.com/magento/magento2/pull/39140#pullrequestreview-2302780539),  has been taken care hence moving it back to review.

**Comment by engcom-Dash** [comment]
Hello @jissereitsma ,

Thanks for your contribution!

As per this [comment](https://github.com/magento/magento2/issues/39152#issuecomment-2342912832), the issue is not reproducible. I also tried but was unable to reproduce it.

Could you please recheck or provide more details?

Thanks again.

**Comment by engcom-Dash** [comment]
As per this https://github.com/magento/magento2/pull/39140#issuecomment-2354756798 closing this PR. Feel free to reopen it if needed. Thanks!

**Pull request closed without merging**
