### PR TITLE
Correct path to 'enable_charts' default

### LINKED ISSUE #37668: [Issue] Correct path to 'enable_charts' default
This issue is automatically created based on existing pull request: magento/magento2#35260: Correct path to 'enable_charts' default

---------
### Description
The configuration option to show charts is `admin/dashboard/enable_charts`, however the default is set in `system/dashboard/enable_charts`. This pull request corrects the path for the default value.

### Related Pull Requests

*None*

### Fixed Issues
*None*

### Manual testing scenarios
1. Navigate to the admin and notice the presence/absence of charts on the dashboard page.

### Questions or comments
*None*

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fredden**
### Description
The configuration option to show charts is `admin/dashboard/enable_charts`, however the default is set in `system/dashboard/enable_charts`. This pull request corrects the path for the default value.

### Related Pull Requests

*None*

### Fixed Issues
*None*

### Manual testing scenarios
1. Navigate to the admin and notice the presence/absence of charts on the dashboard page.

### Questions or comments
*None*

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37668: Correct path to 'enable_charts' default

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento give me test instance

**Comment by ihor-sviziev** [comment]
Just checked - now the charts are enabled by default after your change ✅.

image

**Review by ihor-sviziev — APPROVED** [review]

**Comment by peterjaap** [comment]
@ihor-sviziev so why is this still not merged?

**Comment by ihor-sviziev** [comment]
@peterjaap, I think because of P3 priority, which is "low"

**Comment by peterjaap** [comment]
So this will never be merged?

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run Static Tests

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

- Navigate to the admin and notice the presence/absence of charts on the dashboard page.

**Before:** :heavy_multiplication_x: 
Screenshot 2023-07-27 at 3 17 30 PM


**After:** :heavy_check_mark:  
Screenshot 2023-07-27 at 3 29 36 PM
Screenshot 2023-07-27 at 3 29 05 PM
Screenshot 2023-07-27 at 3 28 56 PM

Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Unit Tests,WebAPI Tests

**Comment by engcom-Echo** [comment]
@magento run Unit Tests,WebAPI Tests,Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests

**Comment by engcom-Echo** [comment]
Failing Test are not related to the PR changes.
Hence Moving to `Merge In Progress`

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Integration Tests,Unit Tests,Functional Tests EE

**Comment by engcom-Echo** [comment]
Functional Tests EE failures are different on last two run on same commit. Other build failures are not related to PR.
Functional Tests EE
Run1
35260-ee

Run2
Screenshot 2023-08-18 at 12 28 51 PM

**Comment by engcom-Lima** [comment]
Moving to **On Hold**  as we are waiting for PO confirmation.

**Comment by fredden** [comment]
@engcom-Lima I don't understand why you need a "purchase order confirmation" for this pull request. Please can you explain what this purchase order is for? I don't see what is being purchased here.

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
> @engcom-Lima I don't understand why you need a "purchase order confirmation" for this pull request. Please can you explain what this purchase order is for? I don't see what is being purchased here.

Hii Fredden, We require Product owner confirmation before merging to mainline. PO here means product owner.

**Comment by fredden** [comment]
@engcom-Lima thanks for explaining the acronym. What needs to be confirmed, please?

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@engcom-Delta @engcom-Charlie, any updates on this?

**Comment by engcom-Charlie** [comment]
Thank you @fredden and @ihor-sviziev for your contribution!

As a result of  the confirmation, we get conveyed by Product SME, that we are not going ahead with this PR/feature. 

It has been experienced in the past that there were some issues occurred by enabling this chart on Dashboard.
Hence regretting not to merge this PR into current mainline and closing it for the same.

Thank you!

**Comment by fredden** [comment]
@engcom-Charlie please can you re-open this pull request.

What issues have been encountered? Let's get those problems fixed (in a different pull request than this).

**Comment by fredden** [comment]
@engcom-Charlie please can you re-open this pull request.

**Comment by chernenm** [comment]
Hello @fredden, @ihor-sviziev,

Let me provide additional insights on the issues we are currently having with the Admin Dashboard functionality.
Basically the main issue we are currently facing is that when customers have millions of records in the **sales_order** and **search_query** tables, the Admin panel home page can be loading more than 10 seconds, which is affecting admin user login experience and performance. Please note that whole Admin panel is blocked while the dashboard is loading.

Here is the exact SQL query for **sales_order** which is causing this performance degradation:

`SELECT SUM((IFNULL(main_table.base_total_invoiced, 0) - IFNULL(main_table.base_tax_invoiced, 0) - IFNULL(main_table.base_shipping_invoiced, 0) - (IFNULL(main_table.base_total_refunded, 0) - IFNULL(main_table.base_tax_refunded, 0) - IFNULL(main_table.base_shipping_refunded, 0)) + (IF(main_table.bs_customer_bal_total_refunded IS NULL, 0, main_table.bs_customer_bal_total_refunded - IFNULL(main_table.base_tax_refunded, 0) - IFNULL(main_table.base_shipping_refunded, 0))) - (IF(main_table.base_gift_cards_refunded IS NULL, 0, main_table.base_gift_cards_refunded - IFNULL(main_table.base_tax_refunded, 0) - IFNULL(main_table.base_shipping_refunded, 0)))) * main_table.base_to_global_rate) AS `lifetime`, AVG((IFNULL(main_table.base_total_invoiced, 0) - IFNULL(main_table.base_tax_invoiced, 0) - IFNULL(main_table.base_shipping_invoiced, 0) - (IFNULL(main_table.base_total_refunded, 0) - IFNULL(main_table.base_tax_refunded, 0) - IFNULL(main_table.base_shipping_refunded, 0)) + (IF(main_table.bs_customer_bal_total_refunded IS NULL, 0, main_table.bs_customer_bal_total_refunded - IFNULL(main_table.base_tax_refunded, 0) - IFNULL(main_table.base_shipping_refunded, 0))) - (IF(main_table.base_gift_cards_refunded IS NULL, 0, main_table.base_gift_cards_refunded - IFNULL(main_table.base_tax_refunded, 0) - IFNULL(main_table.base_shipping_refunded, 0)))) * main_table.base_to_global_rate) AS `average` FROM `sales_order` AS `main_table` WHERE (main_table.status NOT IN('Canceled', 'Payment Failure', 'Rejected')) AND (main_table.state NOT IN('new', 'pending_payment'));`

Adobe Commerce team was not able to come up with a quick solution to improve performance of the query and it was suggested to redesign the dashboard, so it can be initialized asynchronously instead, which requires bigger effort and introduces backward incompatible changes.

And the issue with the **search_query** SQL was previously reported here https://github.com/magento/magento2/issues/27559

I hope these additional insights could help to clarify what exact issues the dashboard is causing and why it makes sense to keep this particural PR on hold till the above performance concerns addressed first.

**Comment by hostep** [comment]
Can't we then just not fix the incorrect config path, but set the default value to disabled instead of enabled?
And later on figure out how to fix performance issue and enable it again?

**Comment by engcom-Charlie** [comment]
Hi @fredden,

Thank you for your contribution!

As discussed with @chernenm, Adobe Commerce team is ready to go ahead with this PR but with the default value set to Disabled only.

Can you please do the the needful so that we can go ahead with this PR further.

Thank you!

**Comment by engcom-Charlie** [comment]
Hi @fredden,

Did you get a chance to look into above [comment](https://github.com/magento/magento2/pull/35260#issuecomment-1835532873).

Thank you!

**Comment by fredden** [comment]
@engcom-Charlie I saw the comment while I was away travelling. I'm back now. I disagree, but will comply.

**Comment by fredden** [comment]
I have opened https://github.com/magento/magento2/pull/38272 to change the default value for this configuration setting.

**Comment by ihor-sviziev** [comment]
@fredden, I guess the idea was to correct the path and change the default value to 0 (that's a default value now because of the wrong path) so that this change is backward compatible and won't cause any performance issues during Magento updates.

**Comment by fredden** [comment]
My goal with this pull request was to implement the intent of the original author: to have the charts enabled by default.

**Comment by fredden** [comment]
> Can you please do this in the same PR instead of creating a new PR.

The two pull requests have distinct and separate scopes. I see this pull request as a bug-fix, whereas #38272 is a policy change. Let's not confuse the two.

**Comment by ihor-sviziev** [comment]
Hi @fredden,
I guess you didn't get the answer in https://github.com/magento/magento2/pull/35260#issuecomment-1835532873.

Before the changes in this Pull Request - the default value was 0 (turned off) just due to the fact of the wrong path.
If we fix just the path - it will automatically change the default value to 1, and this might cause issues during the Magento upgrade. Since the Adobe team is trying to keep the backward compatibility - they can't accept this pull request as is.

As they suggested, in order to accept this Pull Request - we need to change the path  AND default value from 1 to 0 to maintain backward compatibility.

As to me, it absolutely makes sense. Don't you think so?

**Comment by fredden** [comment]
@ihor-sviziev I have seen and understood the comments here.

**Comment by ihor-sviziev** [comment]
@fredden, sorry, I don't understand how we can merge this Pull Request now.
Maybe we can merge the branch from https://github.com/magento/magento2/pull/38272 to this pull request (with conflict resolution) so that this PR will contain both changes and not cause any performance degradation.

**Comment by fredden** [comment]
@ihor-sviziev thanks for following up on this. Let's get #38272 merged in and then come back to this pull request. This pull request is fixing a bug, whereas that pull request is implementing a policy change (which I disagree with).

**Comment by engcom-Charlie** [comment]
Hi @fredden,

As mentioned in [this](https://github.com/magento/magento2/pull/35260#issuecomment-1852083572) comment, Product Owner wants to go ahead with [this](https://github.com/magento/magento2/pull/35260#issuecomment-1835532873) PR, only when it will be having the correct path change along with value being as 0 by default. Can you please make the changes accordingly so that we will move this PR further.

Thank you!

**Comment by fredden** [comment]
@engcom-Charlie please see previous comments. You have already asked for this and I have already responded.

**Comment by engcom-Charlie** [comment]
As we are not going ahead with this changes for now, moving this PR on Hold.

**Comment by engcom-Charlie** [comment]
Moving it to Merge in Progress now

**Pull request merged**
