### PR TITLE
Remove unneccessary spacing below minicart action

### LINKED ISSUE #27987: Mini cart  'View and Edit Cart" link not in alignment issue
### Preconditions (*)

1. Magento version 2.3.4 
2.

### Steps to reproduce (*)

1.Add product into cart 
2.click on mini cart button 

### Expected result (*)

1. "View and Edit Cart" link should be vertically aligned.  

2.
 minicart-fix

### Actual result (*)

1. 
minicart-issue

2.

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Before this PR we have spacing below minicart action "View and Edit Cart"
Here is compare 

Before
before-cart-link

After
after-cart

More info:
Selector `minicart-widgets` render nothing children but it's still add extra fixed 15px inside by css, that make minicart link become misalignment. Not impact to functional only problem with eye visual
In my opinion use margin for parent wrapper (minicart-widgets) may be not good practices little bit tricky. In this case we have empty content div with margin. Instead we should add for children wrapper if content available

### Fixed Issues (if relevant)

1. Fixes magento/magento2#27987

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE

**Comment by ihor-sviziev** [comment]
I think this change might cause regression for modules that rendering here their buttons like Apple pay, google pay, PayPal express, etc. 
Have you checked that?

**Comment by mrtuvn** [comment]
Can we have any docs describe this ? I don't find doc related with promotions setup or visually on minicart from frontend

**Comment by ihor-sviziev** [comment]
@mrtuvn ah. sorry, it looks like this, so your solution will not affect it.
image

**Review by ihor-sviziev — APPROVED** [review]

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8723](https://jira.corp.magento.com/browse/ENGCOM-8723) has been created to process this Pull Request

**Review by ptylek — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-8723](https://jira.corp.magento.com/browse/ENGCOM-8723) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
Hi @mrtuvn,

We are closing this PR.The PR is in Draft since longtime.

Once you are ready Please feel free to reopen it to process the PR further.

Thanks

**Pull request closed without merging**
