### PR TITLE
Issue[34981] Reset customer account Lock Expires date after password reset

### LINKED ISSUE #34981: Customer who exceeded max login failures not able to login even after reset password
### Preconditions (*)

1. Magento 2.4.0 CE

### Steps to reproduce (*)

1. Lock yourself out of a customer account
2. Reset the password
3. Lock is still active

### Expected result (*)

1. Lock yourself out of a customer account
2. Reset the password
3. Lock is removed

### Actual result (*)

1. Lock yourself out of a customer account
2. Reset the password
3. Lock is still active
4. The User account will active after sometime

This was fixed before in #15255. However, this commit removed this one-line fix again: https://github.com/magento/magento2/commit/cdc0fd39bac4218fe16eecb34ee7ffa407ac94ca#diff-b8e39c5ed5e0b80ed62825ba186962adf41803236c50285ab7466ec65f632967L627

What is the reason for removing this fix?

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR set `lock_expires` field to **NULL** and `failures_num` to **0** 
Mentioned changes allow customers login to customer account immediately after password was changed.

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/34981

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento give me 2.4-develop instance

**Comment by Usik2203** [comment]
@magento give me test instance

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Pull request closed without merging**
