### PR TITLE
Magento2 resizes and recompresses original image during upload #17910

### PR DESCRIPTION
**Pull request by mahsn**
**Preconditions**
2.2.5 and below versions are affected
**Steps to reproduce**
Create jpg file larger than 1900x1200 pixels

1. Login to admin
2. Create or update existing product image by uploading new file you created
3. Observe that after upload image is resized to not exceed 1900x1200
4. File is also processed by php using compression quality setting
5. Expected result
6. File is uploaded as it is - it is not modified by Magento 2

**Actual result**
File is resized
File is recompressed
This issue dublicate  with #13747 , there is some features that already added in magento 2.2. I created 3 input in Configuration > Advanced > Developer under the Image Processing Settings to put max values of images.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mahsn. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by mahsn** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @mahsn. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @mahsn, here is your [new Magento instance](https://pr-18199.engcom.dev.magento.com).
Admin access: [https://pr-18199.engcom.dev.magento.com/admin](https://pr-18199.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`

**Comment by slavvka** [comment]
Hey @mahsn could please clarify the reason of creating this PR that just move configurations (which is backward incompatible btw)? The original issue to 2.2 were fixed and ported to 2.3 already.

**Comment by mahsn** [comment]
> Hey @mahsn could please clarify the reason of creating this PR that just move configurations (which is backward incompatible btw)? The original issue to 2.2 were fixed and ported to 2.3 already.

@slavvka actually i knew that this issue already fixed , but when i taked this issue , i read the comments, @php4umagento proposed to create  a config in admin under Advanced > Developer > Image processing - max width, max height, That' s why created these fields.

**Comment by slavvka** [comment]
@mahsn I see. Do you personally see any important reason of doing it? As I said this is BIC and therefore should made only if really needed. Do you feel that? If not, I think I may close this PR

@php4umagento Do you have any concerns?

**Comment by mahsn** [comment]
> @mahsn I see. Do you personally see any important reason of doing it? As I said this is BIC and therefore should made only if really needed. Do you feel that? If not, I think I may close this PR
> 
> @php4umagento Do you have any concerns?

hi @slavvka  Actually it is going to be better create this fields in admin under Advanced > Developer > Image processing , Besides that I don't have a concern

**Comment by slavvka** [comment]
hey @mahsn. I got it. Thank you for the efforts but I am gonna close this PR.

**Pull request closed without merging**
