### PR TITLE
Fixed missing condition values in widget popup form

### PR DESCRIPTION
**Pull request by vovayatsyuk**
This patch fixes missing condition values, when edit previously
inserted widget in cms page or cms block content. See #2360.

### CODE REVIEW

**Comment by Vinai** [comment]
Thank you for the PR! We are currently waiting for the travis builds to work again, which should happen in a few days. Once that is running and the tests are green we can continue to process your contribution.

**Comment by mazhalai** [comment]
@vovayatsyuk Please merge latest from develop and rerun builds.

**Comment by vovayatsyuk** [comment]
@mazhalai done.

**Comment by vovayatsyuk** [comment]
I believe this issue was fixed recently in https://github.com/magento/magento2/commit/3ff19bf82a2ff2e4b7c3e9223cb53083fb60c72d#diff-ac1afb59aadaafca2da2336fb75e9114

**Comment by vrann** [comment]
@vovayatsyuk can you please close the issue if it's not reproduced on the latest develop?

**Pull request closed without merging**
