### PR TITLE
Fixed issue: Magento backend catalog "MSRP" without currency symbol

### PR DESCRIPTION
**Pull request by 00F100**
In this PR fix values of special_price and msrp into products list admin

### Description (*)

The values of special_price and msrp into admin products list

### Fixed Issues (if relevant)

1. magento/magento2#21910: Magento backend catalog "MSRP" without currency symbol

### Manual testing scenarios (*)

1. Admin Menu > Stores > Configuration > Sales > Sales > Minimum Advertised Price = Yes
2. Navigate to admin catalog product grid
3. Using "Columns" selection, add 'Manufacturer's Suggested Retail Price'(MSRP) column in the grid

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24379) <br/>All committers have signed the CLA.

**Comment by 00F100** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @00F100. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @00F100, here is your [new Magento instance](https://pr-24379.instances.magento-community.engineering).
Admin access: [https://pr-24379.instances.magento-community.engineering/admin](https://pr-24379.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by orlangur** [comment]
@00F100 is it still an issue considering https://github.com/magento/magento2/issues/20906#issuecomment-510258609?

**Comment by 00F100** [comment]
in this pr fix 3 columns: cost, special_price and msrp, not only cost.

**Comment by 00F100** [comment]
if cost has been fixed, i remove from this PR

**Comment by orlangur** [comment]
@00F100 did you find commits where `Cost` was fixed? Would be nice to make fix consistent with core one.

**Comment by 00F100** [comment]
yes, equals except here extends Price, not send all to Price class.

**Comment by rodrigowebjump** [comment]
@00F100 Please try to follow the fix approach used in https://github.com/magento/magento2/pull/20907/files

Const NAME is the component name, not the column name that can be defined by xml file.

**Comment by 00F100** [comment]
@rodrigowebjump now it's good?

**Comment by 00F100** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @00F100. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @00F100, here is your [new Magento instance](https://pr-24379.instances.magento-community.engineering).
Admin access: [https://pr-24379.instances.magento-community.engineering/admin](https://pr-24379.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by 00F100** [comment]
CLA is empty :(

Captura de tela de 2019-09-16 10-42-55

**Comment by 00F100** [comment]
CLA not working

Captura de tela de 2019-09-16 14-02-24

Captura de tela de 2019-09-16 14-02-17

**Review by orlangur — CHANGES_REQUESTED** [review]
This fix is incorrect and similar to https://github.com/magento/magento2/pull/20907/files.

In a proper fix, like it was made for `Cost`, new columns will not be added to grid by default.

Please specify commits where it was fixed for `Cost` and do a similar fix for `Special Price` and `MSRP`.

**Comment by rodrigowebjump** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [new Magento instance](https://pr-24379.instances.magento-community.engineering).
Admin access: [https://pr-24379.instances.magento-community.engineering/admin](https://pr-24379.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rodrigowebjump** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [Magento instance](https://i-24379-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24379-2-3-develop.instances.magento-community.engineering/admin](https://i-24379-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by 00F100** [comment]
@orlangur please, help me. In version 2.3-develop Cost not formated and i not find commit to change Cost how do you say.

**Comment by 00F100** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @00F100. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @00F100, here is your [new Magento instance](https://pr-24379.instances.magento-community.engineering).
Admin access: [https://pr-24379.instances.magento-community.engineering/admin](https://pr-24379.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by 00F100** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @00F100. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @00F100, here is your [new Magento instance](https://pr-24379.instances.magento-community.engineering).
Admin access: [https://pr-24379.instances.magento-community.engineering/admin](https://pr-24379.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by orlangur** [comment]
@00F100, sorry, I don't have time to do it instead of you. Try searching using info from https://github.com/magento/magento2/issues/20906#issuecomment-510258609, probably something was mentioned in git log.

**Comment by 00F100** [comment]
You are not able to come up with a suitable solution, only able to say what you do not like.

easy to solve: one less contributor.

Rename Magento to Veselov.

**Comment by orlangur** [comment]
Sorry @00F100, I would like to find an accordance here with you.

> magento 2.3.3 is not on github

I wasn't aware, sorry, just saw the https://github.com/magento/magento2/issues/20906#issuecomment-510258609 which is from July.

I don't know what was the way to fix it in `2.3.3`, this issue may be even irreproducible then. What I know for sure is that adding columns to grid (even invisible ones) is not a proper solution.

To find a proper solution let's wait for a release publishing, I'll ask EngCom guys in Slack if there is any ETA.

**Pull request closed without merging**
