### PR TITLE
Fixed: #21278, Add sort order on downloadable links

### PR DESCRIPTION
**Pull request by mahesh-rajawat**
Fixed: Sort order missing on Downloadable Product Links and Sample Columns.

### Description (*)

In this PR, sortOrder issue fixed for Downloadable Product Links and Sample Columns
### Fixed Issues (if relevant)

1. #21278 
2. ...

### Manual testing scenarios (*)

1. Followed all steps as mentioned in #21278 issue.
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @maheshWebkul721 thanks for the pull request!

Adding parameters to protected methods is not backward compatible approach.

Considering the general approach to data in this file and taking into account that this PR is hardcoding sort orders in the file anyway, I think it's alright to stick to existing approach forr setting sort order: https://github.com/magento/magento2/blob/9cdc1b70c9a40c63fbb58ffd5a8e5385255ef319/app/code/Magento/Downloadable/Ui/DataProvider/Product/Form/Modifier/Links.php#L116 - specifying exact sort order directly in the array.

**Comment by mahesh-rajawat** [comment]
@sivaschenko , i have fixed it.

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-4345](https://jira.corp.magento.com/browse/ENGCOM-4345) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
✔️ QA passed

**Pull request merged**
