### PR TITLE
Disable charts on dashboard by default

### LINKED ISSUE #38430: [Issue] Disable charts on dashboard by default
This issue is automatically created based on existing pull request: magento/magento2#38272: Disable charts on dashboard by default

---------
### Description

This is a follow-up to https://github.com/magento/magento2/pull/35260 where Adobe have specifically required that charts be disabled by default on the dashboard due to performance concerns.

Note that this will actually have zero impact as the path to this setting is incorrect, which is what is being fixed in https://github.com/magento/magento2/pull/35260

### Related Pull Requests
This is related to https://github.com/magento/magento2/pull/35260

### Manual testing scenarios
There are no effective changes being made here. No specific testing is required.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fredden**
### Description

This is a follow-up to https://github.com/magento/magento2/pull/35260 where Adobe have specifically required that charts be disabled by default on the dashboard due to performance concerns.

Note that this will actually have zero impact as the path to this setting is incorrect, which is what is being fixed in https://github.com/magento/magento2/pull/35260

### Related Pull Requests
This is related to https://github.com/magento/magento2/pull/35260

### Manual testing scenarios
There are no effective changes being made here. No specific testing is required.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38430: Disable charts on dashboard by default

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Review by Den4ik — APPROVED** [review]

**Comment by engcom-Charlie** [comment]
No specific testing is required as the path to 'enable_charts' setting is incorrect. In this PR only the config value as been set to 0 by default as conveyed by the Product owner [here](https://github.com/magento/magento2/pull/35260#issuecomment-1852083572).

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by engcom-Charlie** [comment]
The functional B2b, EE and WebAPI failures are differnt in recent 2 builds, seems to be flakey. Hence moving it to Merge in Progress..

**Functional B2B:**
Run 1:
image

Run 2:
image


**Functional EE:**
Run 1:
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38272/bf3d85ec3d4ffc95593150b3ed2693b5/Functional/allure-report-ee/index.html >> No error

Run 2:
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38272/2326b8eaec0f5f964219db97f4fe5657/Functional/allure-report-ee/index.html >> No error

**WebAPI** 
Run 1: 
image

Run 2:
image

image

**Comment by engcom-Charlie** [comment]
@magento create issue

**Pull request merged**
