### PR TITLE
Fix translation issue

### PR DESCRIPTION
**Pull request by jignesh-baldha**
### Description
This PR will fix issue in translate file.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @jignesh-baldha. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by osrecio** [comment]
Hi @jignesh-baldha , Can you give me some steps to reproduce the error ? Or we can see this translation?

**Comment by jignesh-baldha** [comment]
Hello @osrecio please check attached screenshot. Translation for the highlighted area in the screenshot is not working due to spacing in CSV file.


configuration settings stores magento admin

**Review by osrecio — APPROVED** [review]
Thanks for your contribution @jignesh-baldha

**Comment by magento-engcom-team** [comment]
Hi @osrecio, thank you for the review.
[ENGCOM-2863](https://jira.corp.magento.com/browse/ENGCOM-2863) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @jignesh-baldha. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
