### PR TITLE
[Correct code formatting]

### PR DESCRIPTION
**Pull request by hitesh-wagento**
### This PR is a:

- [ ] Bug fix or improvement

### Summary
Correct Code formatting.

### Additional information
NA

### CODE REVIEW

**Comment by orlangur** [comment]
Hi @hitesh-wagento, please combine all PRs with fixing indentation in LESS files into a single PR.

Also, please check why it is not enforced by `phpcs` currently.

**Comment by hitesh-wagento** [comment]
@orlangur , Yes now I am create only one PR for all coding related changes in Blank theme. Previously I think no more changes occurred so I have created multiple PRs.

**Comment by orlangur** [comment]
@hitesh-wagento please add all changes related to indentation changes in Luma, Blank or wherever else here.

Please check why `phpcs` didn't catch this violation also, it would be nice so that such kind of mistake nevermore occurs.

**Comment by hitesh-wagento** [comment]
ok, Let me create one new PR with luma and blank both changes.

**Comment by orlangur** [comment]
@hitesh-wagento just force push into this branch 😉

**Comment by hitesh-wagento** [comment]
@orlangur  I have pushed my changes in **multishipping-module-less-patch** branch. Do we need to create Forwardport and Backport PR again ?

**Comment by hitesh-wagento** [comment]
Hello @orlangur

Any update in this PR ?

Thanks

**Comment by orlangur** [comment]
H @hitesh-wagento, please do the same with https://github.com/magento/magento2/pull/15813 - force push into it - after this PR is merged. No need to create a PR for 2.1.

**Comment by hitesh-wagento** [comment]
Hi @orlangur 

I have pushed my changes in #15813

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-1959](https://jira.corp.magento.com/browse/ENGCOM-1959) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @hitesh-wagento. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.6 release.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
