### PR TITLE
Add Note to Explain Search Weight Values

### LINKED ISSUE #36646: [Issue] Add Note to Explain Search Weight Values
This issue is automatically created based on existing pull request: magento/magento2#35738: Add Note to Explain Search Weight Values

---------
### Description (*)
Adds a note beneath the `Search Weight` attribute's `Storefront Properties` input to explain what the values mean.
+ See: https://docs.magento.com/user-guide/catalog/search-weighted.html#set-the-search-weight-properties-of-an-attribute

### Manual testing scenarios (*)
1. Log into the admin
2. Navigate to `Stores -> Attributes -> Product`
3. Select any attribute from the grid
4. Open the `Storefront Properties` options on the left hand side
5. Ensure `Use in Search` is enabled
6. Observe the note is present beneath the `Search Weight` option
7. The note should read: `10 is the highest priority/heaviest weighting.`

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by pykettk**
### Description (*)
Adds a note beneath the `Search Weight` attribute's `Storefront Properties` input to explain what the values mean.
+ See: https://docs.magento.com/user-guide/catalog/search-weighted.html#set-the-search-weight-properties-of-an-attribute

### Manual testing scenarios (*)
1. Log into the admin
2. Navigate to `Stores -> Attributes -> Product`
3. Select any attribute from the grid
4. Open the `Storefront Properties` options on the left hand side
5. Ensure `Use in Search` is enabled
6. Observe the note is present beneath the `Search Weight` option
7. The note should read: `10 is the highest priority/heaviest weighting.`

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36646: Add Note to Explain Search Weight Values

### CODE REVIEW

**Comment by pykettk** [comment]
@magento run all tests

**Comment by pykettk** [comment]
@magento give me 2.4-develop instance

**Comment by pykettk** [comment]
# Manual Testing
### Test Instance
image

### 2.4 Develop Instance
image

**Comment by pykettk** [comment]
Failing functional tests are non-related.

**Comment by pykettk** [comment]
@magento run all tests

**Comment by pykettk** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento create issue

**Pull request merged**
