### PR TITLE
fixed Translation issue send-friend in send.phtml #18779

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)
I think there is no need to use escapeJs method as we are already using escapeHtml method.
Due to this string getting converted in hexadecimal.

### Fixed Issues (if relevant)

1. magento/magento2#18779: Translation issue send-friend in sendphtml

### Manual testing scenarios (*)

Add translation in module-send-friend module. put Name -> Na-me:. string will become Na\u002Dme\u003A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by ghost** [comment]
@orlangur  - code pushed with latest changes

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3284](https://jira.corp.magento.com/browse/ENGCOM-3284) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@rahulwebkul thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18822) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18822) before we can accept your contribution.<br/>**4** out of **14** committers have signed the CLA.<br/><br/>:white_check_mark: sreichel<br/>:white_check_mark: magento-engcom-team<br/>:white_check_mark: sidolov<br/>:white_check_mark: gelanivishal<br/>:x: joanhe<br/>:x: paliarush<br/>:x: fascinosum<br/>:x: krissyhiserote<br/>:x: nathanjosiah<br/>:x: undefined<br/>:x: dthampy<br/>:x: slopukhov<br/>:x: aakimov<br/>:x: olysenko<hr/>**** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Pull request closed without merging**
