### PR TITLE
Move menu entry log from level INFO to DEBUG

### LINKED ISSUE #38095: [Issue] Move menu entry log from level INFO to DEBUG
This issue is automatically created based on existing pull request: magento/magento2#33987: Move menu entry log from level INFO to DEBUG

---------
### Description (*)
The `var/log/system.log` file gets flooded with messages like the following.
```
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Theme::design_config was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Theme::system_design_theme was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Config::system_config was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::system_design_schedule was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::system_store was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::dashboard was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::system was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::system_tools was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::system_design was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::system_convert was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::system_cache was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::marketing was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::marketing_communications was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::marketing_seo was processed [] []
```

While these messages may be interesting to see in the `var/log/debug.log` file, it makes no sense for them to appear in `var/log/system.log`.

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
None that I know of.

### Manual testing scenarios (*)
1. Flush cache.
2. Log in to backend.
3. See `var/log/debug.log`. The "Add of item ..."  messages should be seen here.
4. See `var/log/system.log`. The messages should not be seen here.

### Questions or comments
None.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by tdgroot**
### Description (*)
The `var/log/system.log` file gets flooded with messages like the following.
```
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Theme::design_config was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Theme::system_design_theme was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Config::system_config was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::system_design_schedule was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::system_store was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::dashboard was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::system was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::system_tools was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::system_design was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::system_convert was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::system_cache was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::marketing was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::marketing_communications was processed [] []
[2021-09-03 11:44:16] main.INFO: Add of item with id Magento_Backend::marketing_seo was processed [] []
```

While these messages may be interesting to see in the `var/log/debug.log` file, it makes no sense for them to appear in `var/log/system.log`.

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
None that I know of.

### Manual testing scenarios (*)
1. Flush cache.
2. Log in to backend.
3. See `var/log/debug.log`. The "Add of item ..."  messages should be seen here.
4. See `var/log/system.log`. The messages should not be seen here.

### Questions or comments
None.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38095: Move menu entry log from level INFO to DEBUG

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9210](https://jira.corp.magento.com/browse/ENGCOM-9210) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9210](https://jira.corp.magento.com/browse/ENGCOM-9210) has been created to process this Pull Request

**Comment by Quazz** [comment]
@tdgroot Should the same be done here: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Backend/Model/Menu/Director/Director.php ?

Generates messages such as: "main.INFO: Item Magento_Backend::system_currency was removed [] []"

**Comment by tdgroot** [comment]
> @tdgroot Should the same be done here: https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Backend/Model/Menu/Director/Director.php ?
> 
> Generates messages such as: "main.INFO: Item Magento_Backend::system_currency was removed [] []"

yes, good suggestion :). I applied the change for that file too!

**Comment by tdgroot** [comment]
@magento run all tests

**Comment by tdgroot** [comment]
@magento run all tests

**Comment by tdgroot** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Functional Tests B2B

**Comment by tdgroot** [comment]
What can be done to get this merged?

**Comment by ihor-sviziev** [comment]
@tdgroot, unfortunately this PR got low priority, so we don't plan to merge it in nearest future, as currently focusing only on p0, p1, p2 issues

**Comment by maaarghk** [comment]
@ihor-sviziev focus by who? The tests all pass, hitting merge would take you 0~1 seconds more or less. Isn't the whole point in allowing community contributions that you can focus on p0 to p2 internally and let the other stuff get prioritised by "whoever shows up and does it"?

**Comment by ihor-sviziev** [comment]
@shikhamis11 how come this PR has 17 upvotes and not accepted as a part of community voting?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by shikhamis11** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento create issue

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**
1. Flush cache.
2. Log in to backend.
3. See var/log/system.log

**Before:** :heavy_multiplication_x: 

Screenshot 2023-10-17 at 8 50 52 PM

Screenshot 2023-10-17 at 8 50 52 PM

**After:** :heavy_check_mark:  

Screenshot 2023-10-20 at 7 03 17 PM


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by maaarghk** [comment]
are you like truly not allowed to look at the failed tests and point out they're unrelated? : (

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
The Functional CE test results are different in recent 2 builds. They seems to be not related to PR or failing because of PR changes. Hence moving it to Merge In Progress.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/33987/7ac5177de1ce1e427b542775a70c666c/Functional/allure-report-ce/index.html#categories

image



**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/33987/bc7675820129bed7d45decbc533e0848/Functional/allure-report-ce/index.html#categories

image

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Pull request merged**
