### PR TITLE
Date creation not consistent with Magento/DateTime with french format

### PR DESCRIPTION
**Pull request by khodu**
### Description (*)

Resolved Date creation not consistent with Magento/DateTime with french format issue.
### Fixed Issues (if relevant)

1. magento/magento2#6187: Date creation not consistent with Magento/DateTime with french format

### Manual testing scenarios (*)

1.Try to format a date using \Magento\Framework\Stdlib\DateTime\DateTime->date("d/m/y", "15/08/2016")
2. Now Return correct value.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @khodu. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3432](https://jira.corp.magento.com/browse/ENGCOM-3432) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@khodu thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by orlangur** [comment]
@khodu please check comment in https://github.com/magento/magento2/pull/19057. Closing as duplicate.

@VladimirZaets you can share your insight in older PR as well.

**Comment by VladimirZaets** [comment]
@orlangur Yes, I already seen that is duplicate and also wanted to close it, thanks

**Pull request closed without merging**
