### PR TITLE
Remove unused namespace from Ui Export model

### PR DESCRIPTION
**Pull request by williankeller**
### Description
The Export model have some unused namespaces: `Magento\Framework\Filesystem\Directory\WriteInterface`.
Just removing it and update description

### Manual testing scenarios
1. For example, go to orders list;
2. Export list of order by XML or CSV;
3. All should export as expected.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14834) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
@williankeller thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by larsroettig** [comment]
Hi @williankeller, we can not accept this because you remove an interface for 2.2. 
If you change the target branch to 2.3 we accept this.

http://devdocs.magento.com/guides/v2.0/contributor-guide/backward-compatible-development/#introduction-of-a-method-to-a-class-or-interface

http://devdocs.magento.com/guides/v2.2/extension-dev-guide/versioning/codebase-changes.html

best regards, 

Lars

**Comment by williankeller** [comment]
@larsroettig, Makes sense to me. Done! :smiley:

**Comment by magento-engcom-team** [comment]
Hi @williankeller. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.3.0 release.

**Pull request merged**
