### PR TITLE
Fix typo in breadcrumbs component on product page

### PR DESCRIPTION
**Pull request by ilnytskyi**
### Description (*)

Breadcrumbs on product page do not build well since parametr given into uiComponent has typo

### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/21011 Not all Breadcrumbs are present on the product page if URL includes categories

### Manual testing scenarios (*)

1. Open product page using direct link including category path
2. See category tree in breadcrumbs

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ilnytskyi. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by swnsma** [comment]
Hi @ilnytskyi,
Thank you for your contribution!

Could you please check unit-test for this functionality?
`\Magento\Catalog\Test\Unit\ViewModel\Product\BreadcrumbsTest::productJsonEncodeDataProvider`

**Review by swnsma — CHANGES_REQUESTED** [review]
Hi @ilnytskyi,
Thank you for your contribution!

Could you please check failed unit-tests:
`\Magento\Catalog\Test\Unit\ViewModel\Product\BreadcrumbsTest::productJsonEncodeDataProvider`

**Comment by swnsma** [comment]
Hi @ilnytskyi,
I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by swnsma** [comment]
#19781

**Pull request closed without merging**
