### PR TITLE
Fix Useless use of Cat

### PR DESCRIPTION
**Pull request by gy741**
### Description (*)

Hello.

I modified the UUOC(useless use of cat).

what do you think?

Ref: https://en.wikipedia.org/wiki/Cat_(Unix)#Useless_use_of_cat

Thanks.

### Fixed Issues (if relevant)

Not relevant

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18725) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @gy741. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by DanielRuf — APPROVED** [review]

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-3235](https://jira.corp.magento.com/browse/ENGCOM-3235) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@gy741 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by gy741** [comment]
thank you for the invitation....
I accepted the team invitation.

**Comment by magento-engcom-team** [comment]
Hi @gy741. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
