### PR TITLE
fix issue with logging each cookie as separate context

### PR DESCRIPTION
**Pull request by aleksinoleg**
### Description (*)
When the number of cookies becomes more than 50 the warning log is written: "Unable to send the cookie. Maximum number of cookies would be exceeded." And each cookie is converting to a separate log context. And in the case of using the Graylog app, it is converting to a separate field.
By this pull request, the $_COOKIE array is converting to a string and writing as 'cookie' context while writing the log

### Manual testing scenarios (*)

1. Exceed the number of cookies > 50
2. Watch the log

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@aleksinoleg Finally, someone will fix that! 👍

We also were having this issue - we're sending logs to some Elasticsearch based tool, and it was hunting because of too many fields (each key is sent as a separate key). Also, it doesn't have any value for sending all cookies as separate values, so PR, in general, looks good to me.

Let's wait for the test results.
@magento run all tests

**Comment by aleksinoleg** [comment]
@ihor-sviziev, I have no time to fix all stacked tests. It would be great if someone will fix it. Thanks

**Comment by ihor-sviziev** [comment]
@sidolov  @gabrieldagama could you provide info on why some tests are failing with no build results?

**Comment by ihor-sviziev** [comment]
Hi @aleksinoleg,
Could you re-target your Pull Request to the 2.4-develop branch as the 2.3 release line is already closed for contributions?

**Comment by sidolov** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Closing this PR as a duplicate of https://github.com/magento/magento2/pull/31334

**Pull request closed without merging**
