### PR TITLE
Fix the newsletter confirmation email From

### LINKED ISSUE #34963: [Issue] Fix the newsletter confirmation email From
This issue is automatically created based on existing pull request: magento/magento2#34635: Fix the newsletter confirmation email From

---------
Fix the newsletter confirmation email From on multi-store env

### Description (*)

Bug: the newsletter subscription confirmation email has the wrong email in From field
if the customer is assigned to a non-default store and subscribed/unsubscribed via admin panel

### Fixed Issues (if relevant)

I didn't find the existing issue

### Manual testing scenarios (*)

1. In admin panel of multi-store Magento, open some customer that assigned to non-default store
2. Go to "Newsletter" tab
3. Select (or unelect if it's selected already) the "Subscribed to Newsletter" checkbox and save the customer

Expected:
The customer receives an email with a store-specific email in From header

Actual:
The customer receives an email with default email in From header

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by sevka**
Fix the newsletter confirmation email From on multi-store env

### Description (*)

Bug: the newsletter subscription confirmation email has the wrong email in From field
if the customer is assigned to a non-default store and subscribed/unsubscribed via admin panel

### Fixed Issues (if relevant)

I didn't find the existing issue

### Manual testing scenarios (*)

1. In admin panel of multi-store Magento, open some customer that assigned to non-default store
2. Go to "Newsletter" tab
3. Select (or unelect if it's selected already) the "Subscribed to Newsletter" checkbox and save the customer

Expected:
The customer receives an email with a store-specific email in From header

Actual:
The customer receives an email with default email in From header

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#34963: Fix the newsletter confirmation email From

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @sevka,
Thank you for your contribution! 
Could you sign the Adobe CLA and cover your changes with some automated tests?

**Review by andrewbess — CHANGES_REQUESTED** [review]
Hello @sevka 
Thank you for your contribution.
Could you please fix static and unit tests
Thank you in advance.

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@sevka Please sign CLA. We could not merge PR without that.

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @sevka,

Thank you for your contribution!

We are not able to proceed further on this PR as you have not  sign the Adobe CLA yet. Hence closing this PR.

Please reopen and update if you wish to continue.

Thank you for your contribution!

**Comment by Den4ik** [comment]
@magento create issue

**Pull request closed without merging**
