### PR TITLE
#18012: added i18n wrapper to be used in underscore templates for translation

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Introduced `i18n` method for underscore to provide an ability use translation in underscore templates.
`<%= _.i18n('Hello') %>`

### Fixed Issues
1. #18012

### Manual testing scenarios
See #18012 for the example.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
@sergiy-v well done, thank you!
We just need to make sure the translation phrase is properly parsed and included in `js-translation.json` dictionary file. Could you please check it?

References:
- [app/code/Magento/Translation/Model/Js/Config.php](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Translation/Model/Js/Config.php)
- [app/code/Magento/Translation/etc/di.xml](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Translation/etc/di.xml#L64)

**Comment by sergiy-v** [comment]
> @sergiy-v well done, thank you!
> We just need to make sure the translation phrase is properly parsed and included in `js-translation.json` dictionary file. Could you please check it?
> 
> References:
> 
> * [app/code/Magento/Translation/Model/Js/Config.php](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Translation/Model/Js/Config.php)
> * [app/code/Magento/Translation/etc/di.xml](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Translation/etc/di.xml#L64)


@dmytro-ch I'll check and add needed changes, thank you.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6708](https://jira.corp.magento.com/browse/ENGCOM-6708) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
