### PR TITLE
Chore: Downloadable - Replace Block Escaping with Escaper

### LINKED ISSUE #37170: [Issue] Chore: Downloadable - Replace Block Escaping with Escaper
This issue is automatically created based on existing pull request: magento/magento2#37159: Chore: Downloadable - Replace Block Escaping with Escaper

---------
### Description (*)
Refactors the `Magento_Downloadable` module to replace `$block` escaping functions with `$escaper` escaping functions.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37095: Chore: Admin Analytics - Replace Block Escaping with Escaper

### PR DESCRIPTION
**Pull request by pykettk**
### Description (*)
Refactors the `Magento_Downloadable` module to replace `$block` escaping functions with `$escaper` escaping functions.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37095: Chore: Admin Analytics - Replace Block Escaping with Escaper

### Resolved issues:
1. [x] resolves magento/magento2#37170: Chore: Downloadable - Replace Block Escaping with Escaper

### CODE REVIEW

**Comment by pykettk** [comment]
@magento create issue

**Review by leonhelmus — APPROVED** [review]
Looks good @pykettk

**Comment by engcom-November** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
:heavy_check_mark: QA Passed 

**Preconditions:** - 
Install fresh Magento **2.4-develop** and **PHP 8.1** 

**Manual testing scenario:** 
Verify in the Magento_Downloadable module to replaces $block escaping functions with $escaper escaping functions after applying the PR changes.
**Before:** :heavy_multiplication_x:  
image

**After:** :heavy_check_mark: 
image
**Additionally tested:**
Verified the Downloadable product functionality in the frontend.

No additional manual test case is required in regression cycle as this PR is related to the refactoring of the codes.

**Pull request closed without merging**
