### PR TITLE
 issue with the price display in the Recently Viewed widget

### LINKED ISSUE #38167: [Issue]  issue with the price display in the Recently Viewed widget
This issue is automatically created based on existing pull request: magento/magento2#38159:  issue with the price display in the Recently Viewed widget

---------
### Title
Out-of-stock simple product prices are not shown in the “Recently Viewed Product” widget

### Description (*)
When we visit the out-of-stock simple product in the frontend that product price is not shown in the “Recently viewed Product” widget however we can see the same out-of-stock product price in the “Related Product” Widget And “Product list page” so as per Magento behavior the price of the out of stock simple product should be shown in “Recently viewed Product” Widget also.in screenshot1 you can see that we can not see the price in the ‘recently viewed product’ widget but  we can see the same ‘out-of-stock’ product price in the ‘related product’ widget 
Screenshot 1:
image

### Manual testing scenarios (*)
1: Access the Magento admin panel and navigate to 'content' -> 'Widget' and   add a widget
2: in “Storefront Properties” and “Layout Updates” select  the option as shown in screenshot2
Screenshot 2:
image

3:in the widget options setting select the option as shown in below screenshot and save the widget
Screenshot 3:
image

4: create some simple product and set them as ‘Out of stock’ or change the status of existing products to ‘Out of stock’

5: After navigate to 'stores' -> 'configuration'->catalog->inventory in stock option tab set the ‘display out of stock product’ to yes as you can see in screenshot 4
image

6:now you visit these ‘out-of-stock’ simple product and  see the recently viewed product widget you can see that the price of out of stock simple product is not shown in the “Recently Viewed Product”
Screenshot 5:
image

### Expected result 
The price of out-of-stock simple product should be shown in the Recently Viewed Product Widget 

###  Actual result 
we can not see the price of the out-of-stock simple products in the Recently Viewed Product Widget

### Additional Information 

Recently viewed product widget load Price from these two HTML files: ‘regular_price.html’ and ‘special_price.html’, located in the following path:
1:magento/module-catalog/view/base/web/template/product/price/regular_price.html
2:magento/module-catalog/view/base/web/template/product/price/special_price.html

both files contain a condition on line 7: <if args="isSalable($row())"> this condition determines whether the product is salable(in-stock). If the product is not salable(out-of-stock), the price of that product will not be displayed in the “Recently Viewed Product” Widget. These templates only load prices for the “Recently Viewed Product” widget; therefore, you can view the price of the out-of-stock simple products in the ‘Related Product’ and “Product List” pages

I have included a screenshot(screenshot 6) of the regular_price.html file so you can see the condition in line 7 of that file 
Screenshot 6:
image

### Solution 

So to see the out-of-stock simple product price in the recently viewed product widget we have to modify the regular_price.html file and  special_price.html and remove the <if  "isSalable($row())"> condition so after applying this we can see the price of the out-of-stock simple product price in “Recently Viewed Product” widget. i have added the screenshot(screenshot 7) of the regular_price.html file for your reference so you can see the file after the changes

Screenshot 7:
image

### PR DESCRIPTION
**Pull request by DhruvBasan**
### Title
Out-of-stock simple product prices are not shown in the “Recently Viewed Product” widget

### Description (*)
When we visit the out-of-stock simple product in the frontend that product price is not shown in the “Recently viewed Product” widget however we can see the same out-of-stock product price in the “Related Product” Widget And “Product list page” so as per Magento behavior the price of the out of stock simple product should be shown in “Recently viewed Product” Widget also.in screenshot1 you can see that we can not see the price in the ‘recently viewed product’ widget but  we can see the same ‘out-of-stock’ product price in the ‘related product’ widget 
Screenshot 1:
image

### Manual testing scenarios (*)
1: Access the Magento admin panel and navigate to 'content' -> 'Widget' and   add a widget
2: in “Storefront Properties” and “Layout Updates” select  the option as shown in screenshot2
Screenshot 2:
image

3:in the widget options setting select the option as shown in below screenshot and save the widget
Screenshot 3:
image

4: create some simple product and set them as ‘Out of stock’ or change the status of existing products to ‘Out of stock’

5: After navigate to 'stores' -> 'configuration'->catalog->inventory in stock option tab set the ‘display out of stock product’ to yes as you can see in screenshot 4
image

6:now you visit these ‘out-of-stock’ simple product and  see the recently viewed product widget you can see that the price of out of stock simple product is not shown in the “Recently Viewed Product”
Screenshot 5:
image

### Expected result 
The price of out-of-stock simple product should be shown in the Recently Viewed Product Widget 

###  Actual result 
we can not see the price of the out-of-stock simple products in the Recently Viewed Product Widget

### Additional Information 

Recently viewed product widget load Price from these two HTML files: ‘regular_price.html’ and ‘special_price.html’, located in the following path:
1:magento/module-catalog/view/base/web/template/product/price/regular_price.html
2:magento/module-catalog/view/base/web/template/product/price/special_price.html

both files contain a condition on line 7: <if args="isSalable($row())"> this condition determines whether the product is salable(in-stock). If the product is not salable(out-of-stock), the price of that product will not be displayed in the “Recently Viewed Product” Widget. These templates only load prices for the “Recently Viewed Product” widget; therefore, you can view the price of the out-of-stock simple products in the ‘Related Product’ and “Product List” pages

I have included a screenshot(screenshot 6) of the regular_price.html file so you can see the condition in line 7 of that file 
Screenshot 6:
image

### Solution 

So to see the out-of-stock simple product price in the recently viewed product widget we have to modify the regular_price.html file and  special_price.html and remove the <if  "isSalable($row())"> condition so after applying this we can see the price of the out-of-stock simple product price in “Recently Viewed Product” widget. i have added the screenshot(screenshot 7) of the regular_price.html file for your reference so you can see the file after the changes

Screenshot 7:
image

### Resolved issues:
1. [x] resolves magento/magento2#38167:  issue with the price display in the Recently Viewed widget

### Related Pull Requests
https://github.com/magento-gl/magento2-page-builder/pull/75

### CODE REVIEW

**Comment by DhruvBasan** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
@magento create issue

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE, Integration Tests, WebAPI Tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @DhruvBasan,

Thank you for your collaboration!

As per the [Definition of Done (DOD)](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1), could you please ensure that the changes are covered with some automated tests?

Thank you.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B,Functional Tests EE ,WebAPI Tests

**Comment by engcom-Echo** [comment]
Build failure are not related to PR changes.
Moving it to` pending review`.

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Review by engcom-Hotel — APPROVED** [review]
The failed test seems flaky to me. Hence approving the PR.

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
@magento give me test instance

**Comment by engcom-Bravo** [comment]
Hi @DhruvBasan,

Thanks for the collaboration & contribution!

:heavy_check_mark: QA Passed

**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Access the Magento admin panel and navigate to 'content' -> 'Widget' and add a widget
- in “Storefront Properties” and “Layout Updates” select the option as shown in screenshot2
- in the widget options setting select the option as shown in below screenshot and save the widget
- create some simple product and set them as ‘Out of stock’ or change the status of existing products to ‘Out of stock’
- After navigate to 'stores' -> 'configuration'->catalog->inventory in stock option tab set the ‘display out of stock product’ to yes
- now you visit these ‘out-of-stock’ simple product and see the recently viewed product widget you can see that the price of out of stock simple product is not shown in the “Recently Viewed Product”


**Before:** :heavy_multiplication_x: 

Screenshot 2024-05-07 at 11 58 46







**After:** :heavy_check_mark:  

Screenshot 2024-05-07 at 12 08 01



Builds are failed. Hence, moving this PR to **Extended Testing.**


Thanks.

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Integration Tests,Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Functional Tests B2B,Functional Tests EE,Functional Tests CE failure are different on last two run on same commit.
And Also contains known failure.
`Functional Tests B2B`
Run1
38159-B2b

Run2
Screenshot 2024-05-09 at 2 40 40 PM

`Functional Tests EE`
Run1
38159-ee
Run2
Screenshot 2024-05-09 at 2 44 15 PM


`Functional Tests CE`
Run1
38159-ce

Run2
Screenshot 2024-05-09 at 2 40 52 PM

WebAPI Tests failures are also known failures.

Screenshot 2024-05-09 at 2 48 00 PM

Hence moving it to `merge in progress.`

**Pull request merged**
