### PR TITLE
Improve: [UrlRewrite] Move grid implementation to ui components

### PR DESCRIPTION
**Pull request by Den4ik**
### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/126

### Description (*)

1. Moved url grid implementation to ui components
2. Added mass delete action
3. Added inline edit
4. Added unit tests for new actions

### Fixed Issues (if relevant)

No issue

### Manual testing scenarios (*)

1. Go to Marketing->UrlRewrites
2. Try to filter items
3. Try inline edit
4. Try mass delete

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Den4ik** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [new Magento instance](https://pr-23570.instances.magento-community.engineering).
Admin access: [https://pr-23570.instances.magento-community.engineering/admin](https://pr-23570.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rogyar** [comment]
Hi @Den4ik. Please note that you need to adjust the existing functional tests since they rely on the old selectors.

**Comment by Den4ik** [comment]
Hi @rogyar Yep, I'm on it

**Comment by Den4ik** [comment]
@rogyar mftf tests fixed. But I'm not sure that we should support old functional tests that broken for now. What do you think?

**Comment by rogyar** [comment]
Hi @Den4ik. The problem is not all legacy functional tests are migrated to the MFTF approach (a lot of work needs to be done :D https://github.com/magento/magento-functional-tests-migration/issues). So the old functional tests are still being used for checking the changes including the internal process of merging PRs. So I believe we still need to support them. But the best option here is to migrate the old tests to MFTF. We could raise this question in maintainers channel to discuss in details.

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [Magento instance](https://i-23570-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23570-2-3-develop.instances.magento-community.engineering/admin](https://i-23570-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Den4ik** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [Magento instance](https://i-23570-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23570-2-3-develop.instances.magento-community.engineering/admin](https://i-23570-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Den4ik** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [Magento instance](https://i-23570-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23570-2-3-develop.instances.magento-community.engineering/admin](https://i-23570-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Den4ik** [comment]
@rogyar All tests fixed, migrated all related mtf tests. Please review

**Comment by rogyar** [comment]
I would say it's PR of the year. Amazing, thank you! 
The only thing that I would recommend is creating MFTF tests based on the action groups only. You have almost all tests done in that way except this one
app/code/Magento/Catalog/Test/Mftf/Test/AdminCreateCategoryWithNoAnchorFieldTest.xml
However, it's rather a recommendation for the future than a request for changes. 
Great job! 
I believe other maintainers should check the code for possible backward compatibility issues (@sidolov, @sivaschenko).

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-5509](https://jira.corp.magento.com/browse/ENGCOM-5509) has been created to process this Pull Request

**Comment by Den4ik** [comment]
@rogyar Thanks for recommendation

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Review by engcom-Foxtrot — APPROVED** [review]

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento-engcom-team what's progress on this PR?

**Comment by Den4ik** [comment]
@engcom-Golf @engcom-Foxtrot  any updates?

**Comment by Den4ik** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [Magento instance](https://i-23570-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23570-2-3-develop.instances.magento-community.engineering/admin](https://i-23570-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by lontrau** [comment]
Tốt

**Comment by slavvka** [comment]
Hey @Den4ik Could you please resolve the conflicts?

**Review by slavvka — APPROVED** [review]

**Comment by Den4ik** [comment]
@slavvka Can you describe what's problem with semantic version checker? PR don't contain php version changes.
Also is it problem with CI for functional tests?

**Comment by slavvka** [comment]
Hey @Den4ik I saw the SVC issue yesterday, trying to figure it out.

**Comment by slavvka** [comment]
@Den4ik As for Functional tests there is an issue in MFTF:
`Could not resolve entity reference "{{AdminUrlRewriteIndexSection.requestPathFilter}}" in Action with stepKey "inputProductName".`
`Exception occurred parsing action at StepKey "inputProductName" in Test "AdminUrlRewritesForProductAfterImportTest"`
`app/code/Magento/UrlRewrite/Test/Mftf/Test/AdminUrlRewritesForProductAfterImportTest.xml `

**Comment by Den4ik** [comment]
> @Den4ik As for Functional tests there is an issue in MFTF:
> `Could not resolve entity reference "{{AdminUrlRewriteIndexSection.requestPathFilter}}" in Action with stepKey "inputProductName".`
> `Exception occurred parsing action at StepKey "inputProductName" in Test "AdminUrlRewritesForProductAfterImportTest"`
> `app/code/Magento/UrlRewrite/Test/Mftf/Test/AdminUrlRewritesForProductAfterImportTest.xml `

Thanks. I'm on it

**Comment by Den4ik** [comment]
@slavvka I fixed related with this task Functional tests. But looks like some not related tests broken

**Comment by slavvka** [comment]
@Den4ik Cool. Looks like it is random failure. Fixes for SVC are on their way and soon we will see the consistent results. But I may say that they are removal of blocks that are MAJOR change so it also should pass the architectural review.

**Comment by Den4ik** [comment]
@slavvka Please ping me if I can help. Thanks

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
Hey @Den4ik please resolve conflicts

**Comment by slavvka** [comment]
The PR is under architectural review

**Comment by Den4ik** [comment]
@slavvka conflict resolved

**Comment by slavvka** [comment]
@Den4ik Cool, and functional tests passed. So the only question now is to get architectural approval. I'll keep you updated.

**Comment by slavvka** [comment]
@Den4ik The architectural approval is granted. Could you please resolve the conflicts so we can proceed with delivery?

**Comment by Den4ik** [comment]
@slavvka Thanks, I'm on it

**Comment by Den4ik** [comment]
@slavvka I resolved conflicts. Could you please help with EE and B2B tests, because they don't have any info

**Comment by slavvka** [comment]
Hey @Den4ik Functional EE and B2B tests are failing to the issue with tests generation:
```05:18:21 [Build Functional EE] In TestGenerator.php line 247:
05:18:21 [Build Functional EE]                                                                                
05:18:21 [Build Functional EE]   Could not resolve entity reference "{{AdminUrlRewriteIndexSection.requestPa  
05:18:21 [Build Functional EE]   thFilter}}" in Action with stepKey "inputProductName".                       
05:18:21 [Build Functional EE]   Exception occurred parsing action at StepKey "inputProductName" in Element   
05:18:21 [Build Functional EE]   "before"                                                                     
05:18:21 [Build Functional EE]   /var/www/html/app/code/Magento/CatalogStaging/Test/Mftf/Test/AdminDeletePro  
05:18:21 [Build Functional EE]   ductStagingUpdateWhenTheProductIsUsedTest.xml 
```

@engcom-Foxtrot could you please help @Den4ik with that?

**Comment by Den4ik** [comment]
@slavvka thanks. @engcom-Foxtrot please ping me if you need any help from me. Unfortunately I don't have access to EE and B2B now

**Comment by engcom-Foxtrot** [comment]
@slavvka @Den4ik I'll take care of that.

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@Den4ik, unfortunately, I have no rights to push into https://github.com/magenius-team/magento2.git repository.

**Comment by Den4ik** [comment]
> have no rights to push

@engcom-Foxtrot Very strange. Previously Magento team members pushed to forked repository
Seem like github changes. I don't see checkbox "Allow edits from maintainers"

**Comment by Den4ik** [comment]
@engcom-Foxtrot How I can help with delivering this PR?

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [Magento instance](https://i-23570-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-23570-2-4-develop.instances.magento-community.engineering/admin_fd36](https://i-23570-2-4-develop.instances.magento-community.engineering/admin_fd36)
Login: `a54bf69e` Password: `9f2faf19ccaf`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
@engcom-Kilo please address failed tests.

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [Magento instance](https://i-23570-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-23570-2-4-develop.instances.magento-community.engineering/admin_dccd](https://i-23570-2-4-develop.instances.magento-community.engineering/admin_dccd)
Login: `8eb396b4` Password: `f6b81bde00ca`
Instance will be terminated in up to 3 hours.

**Comment by slavvka** [comment]
@magento run all tests

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by engcom-Golf** [comment]
I'm Moving this to merge, as SVC failure is approved ->https://github.com/magento/magento2/pull/23570#issuecomment-572640894

**Review by slavvka — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @slavvka, thank you for the review.
[ENGCOM-5509](https://jira.corp.magento.com/browse/ENGCOM-5509) has been created to process this Pull Request

**Comment by engcom-Golf** [comment]
I'm Will fix another one flaky test on EE

**Comment by engcom-Golf** [comment]
Finally all test passed

**Pull request merged**
