### PR TITLE
Fix issue with di.xml config merging for classes array argument in case of different sources and the class name difference in leading slash.

### PR DESCRIPTION
**Pull request by swnsma**
### Description
PR to fix the reasons of #20410 (issue #20409).
During research I have discovered bug in config merging from di.xml.
Merging of nested arguments (array) in case of difference in class name (leading slash) in different files can leads to config lost.

### Fixed Issues (if relevant)
1. magento/magento2#20409
2. https://github.com/magento/magento2/issues/21193

#### Pre-Conditions
1. Change constructor of \Magento\Cms\Controller\Index\Index and add new argument 'data' (simple way to visualize it):
```
public function __construct(`
`        Context $context,`
        ForwardFactory $resultForwardFactory,
        ScopeConfigInterface $scopeConfig = null,
        Page $page = null,
        array $data = []
    ) {
        var_dump($data);
        die;
    }
```
#### Steps to reproduce
1. Create module A and B with simple config set (registration.php and module.xml).
2. Execute in terminal `php bin/magento setup:upgrade`.
3. Create etc/di.xml for module A:
```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Cms\Controller\Index\Index">
        <arguments>
            <argument name="data" xsi:type="array">
                <item name="p1" xsi:type="string">Hello Phrase1</item>
            </argument>
        </arguments>
    </type>
</config>
```
4. Create etc/di.xml for module B:
```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="\Magento\Cms\Controller\Index\Index">
        <arguments>
            <argument name="data" xsi:type="array">
                <item name="p2" xsi:type="string">Hello Phrase2</item>
            </argument>
        </arguments>
    </type>
</config>
```
5. Execute in terminal `php bin/magento cache:flush`
6. Open home page.
#### Expected results
image
#### Actual results
image

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @swnsma. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by dominicfernando** [comment]
@swnsma  I think "\" making the problem

<type name="\Magento\Cms\Controller\Index\Index">
        <arguments>
            <argument name="data" xsi:type="array">
                <item name="p2" xsi:type="string">Hello Phrase2</item>
            </argument>
        </arguments>
    </type>

**Comment by dominicfernando** [comment]
@swnsma 

I think "\" making the problem.

<type name="\Magento\Cms\Controller\Index\Index">
        <arguments>
            <argument name="data" xsi:type="array">
                <item name="p2" xsi:type="string">Hello Phrase2</item>
            </argument>
        </arguments>
    </type>

**Comment by dominicfernando** [comment]
@swnsma 

 `\` making the problem.  But I think you try to solve `\` problem.

`
<type name="\Magento\Cms\Controller\Index\Index">
        <arguments>
            <argument name="data" xsi:type="array">
                <item name="p2" xsi:type="string">Hello Phrase2</item>
            </argument>
        </arguments>
    </type>
`

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-4094](https://jira.corp.magento.com/browse/ENGCOM-4094) has been created to process this Pull Request

**Comment by swnsma** [comment]
@dominicfernando
Yes.
There only difference for now is during array arguments merge :)

**Comment by Nazar65** [comment]
HI @swnsma your PR also fixes this issue -> https://github.com/magento/magento2/issues/21193 your changes solves this

**Comment by swnsma** [comment]
Hi @Nazar65,
Thanks!

**Comment by swnsma** [comment]
PR break Backward Compatibility due to merging of configs between general and concrete application level (e.g. adminhtml/frontend) leads to merging of configs (after changes in this PR) but not replacing of configs (before changes in this PR).

**Pull request closed without merging**
