### PR TITLE
FIX Medium date time (international month name) in newsletter queue

### PR DESCRIPTION
**Pull request by TechOS-PL**
### Fixed Issues (if relevant)
1. magento/magento2#4642: Newsletter date translation

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=10736) <br/>All committers have signed the CLA.

**Comment by miguelbalparda** [comment]
Can you please edit this PR and use the correct template? Thanks!

**Review by vkublytskyi — CHANGES_REQUESTED** [review]
The fix cannot be considered as correct because it changes UI presentation of dates. However, this solution may be applied as a patch for particular Magento instance if needed.

In fact, the issue is deeper and requires precise changes. 

**Issue 1** Magento Calendar widget sends on server dates in locale format. Widget should provide a possibility to define two separate formats: date-time presentation format (how date is displayed for user at UI) and date-time data format (how it is transferred between server and browser)

**Issue 2.** `Magento\Framework\Stdlib\DateTime\Timezone::date` assume that `\IntlDateFormatter::SHORT` is always used for date and time. But Magento UI uses different formats and has no `@api` interface to parse such strings or normalize it to unified format.

@TechOS-PL you will make a significant contribution if  resolve one of these issues in scope of this PR.

**Comment by sidolov** [comment]
@TechOS-PL , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration!

**Pull request closed without merging**
