### PR TITLE
Fixed #17311 Region is always required when creating a new order in the Admin area

### LINKED ISSUE #17311: Region is always required when creating a new order in the Admin area
### Preconditions

1.  Magento 2.2.5
2.  PHP 7.0.31
3.  MariaDB 10.1.29
4.  Apache 2.4.29
5.  Ubuntu 18.04

### Steps to reproduce

1. Have a clean Magento 2.2.5 install (composer create-project)
2. In the Admin area go to Sales -> Orders
3. Click "Create New Order"
4. Click "Create New Customer"
5. State/Province is mandatory as the selected country is United States
6. Change country to "The Netherlands" (Where state/province isn't mandatory)
7. State/Provice is still required

### Expected result

1. Region should only be required for countries that are selected in the "State is Required for" configuration option under Stories -> Configuration -> General -> General -> State Options.

### Actual result

1. Region is always mandatory when creating a new address from the "Create New Order" form.
2. This functionality works properly when creating a new address under Customers, adding a new Customer. ect.

The problem is most likely in this class:
https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Customer/Block/Adminhtml/Edit/Renderer/Region.php#L51

* Line 51: always a required and _required CSS class
* Line 53: always a setRequired(true)
* Line 63: always a required-entry CSS class

If the above is true then this bug applies to all versions from 2.0 to 2.3

### PR DESCRIPTION
**Pull request by verma-ankur**
Fixed #17311 Region is always required when creating a new order in the Admin area

### Preconditions

1.  Magento 2.2.5
2.  PHP 7.0.31
3.  MariaDB 10.1.29
4.  Apache 2.4.29
5.  Ubuntu 18.04

### Steps to reproduce

1. Have a clean Magento 2.2.5 install (composer create-project)
2. In the Admin area go to Sales -> Orders
3. Click "Create New Order"
4. Click "Create New Customer"
5. State/Province is mandatory as the selected country is United States
6. Change country to "The Netherlands" (Where state/province isn't mandatory)
7. State/Provice is still required

### Expected result

1. Region should only be required for countries that are selected in the "State is Required for" configuration option under Stories -> Configuration -> General -> General -> State Options.

### Actual result

1. Region is always mandatory when creating a new address from the "Create New Order" form.
2. This functionality works properly when creating a new address under Customers, adding a new Customer. ect.

The problem is most likely in this class:
https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Customer/Block/Adminhtml/Edit/Renderer/Region.php#L51

* Line 51: always a required and _required CSS class
* Line 53: always a setRequired(true)
* Line 63: always a required-entry CSS class

If the above is true then this bug applies to all versions from 2.0 to 2.3

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ankur-cedcoss. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by aleron75 — APPROVED** [review]
works for me too

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-4102](https://jira.corp.magento.com/browse/ENGCOM-4102) has been created to process this Pull Request

**Comment by aleron75** [comment]
Hello @ankur-cedcoss, thanks for your contribution.

Once merged, don't forget you can easily port this PR (if needed, as it appears to be) to other branches with the Porting Tool, [read more here](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#porting-tool).

**Comment by sdzhepa** [comment]
Hello @verma-ankur 

Thank you for contribution and collaboration!

During testing, we faced an issue
Could you please have a look and fix it?

Please see the quote of QA comment after testing on branch with the PR:
- **Problem:** _"State/Province" field is still required in "Shipping Address" column_

**Manual testing scenario:**

1. Login to Admin;
2. Go to Sales -> Orders;
3. Click on "Create New Order" button;
4. Click on "Create New Customer" button;
5. "State/Province" field is mandatory as the selected country is United States;
6. Change country to the "Netherlands" (Where state/province isn't mandatory);

**Actual Result:** Not OK,  In the "Shipping Address" column "State/Province" field is still required

problem

**Comment by sidolov** [comment]
@verma-ankur , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
