### PR TITLE
Multiselect attribute options wrong translation on add product page 19388

### PR DESCRIPTION
**Pull request by novikor**
### Description (*)

- Set correct store for adminhtml area by default. The problem was that store with id=1 was used previously in admin panel which is wrong.
### Fixed Issues (if relevant)

1. magento/magento2#19388: Multiselect attribute options wrong translation on Add Product page

### Manual testing scenarios (*)

1. See #19388 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @novikor. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3555](https://jira.corp.magento.com/browse/ENGCOM-3555) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @novikor , considering that this is a major change I would ask you to run all the integration tests on locally and to identify additional adjustments needed for Magento modules and/or tests (Only limited number of tests is running on travis for each pull request to minimize time and resource consumption)

Also, please check the failed functional tests:


    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 27:217:8 / Magento\Sitemap\Test\TestCase\GenerateSitemapEntityTest.testGenerateSitemap with data set "GenerateSitemapEntityTestVariation2_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 34:268:3 / Magento\Wishlist\Test\TestCase\ViewProductInCustomerWishlistOnBackendTest.test with data set "ViewProductInCustomerWishlistOnBackendTestVariation2_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 34:268:3 / Magento\Wishlist\Test\TestCase\ViewProductInCustomerWishlistOnBackendTest.test with data set "ViewProductInCustomerWishlistOnBackendTestVariation3_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 34:268:3 / Magento\Wishlist\Test\TestCase\ViewProductInCustomerWishlistOnBackendTest.test with data set "ViewProductInCustomerWishlistOnBackendTestVariation4_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 34:268:3 / Magento\Wishlist\Test\TestCase\ViewProductInCustomerWishlistOnBackendTest.test with data set "ViewProductInCustomerWishlistOnBackendTestVariation5_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / isolate:16:168:Magento_Sales_Test_TestCase_CreateOrderBackendTest / Magento\Sales\Test\TestCase\CreateOrderBackendTest.test with data set "CreateOrderBackendTestVariation18_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / isolate:16:168:Magento_Sales_Test_TestCase_CreateOrderBackendTest / Magento\Sales\Test\TestCase\CreateOrderBackendTest.test with data set "CreateOrderBackendTestVariation19_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 32:257:8 / Magento\Vault\Test\TestCase\ReorderUsingVaultTest.test with data set "ReorderUsingVaultBraintreeTestVariation1_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 7:61:8 / Magento\CatalogRule\Test\TestCase\CreateCatalogPriceRuleEntityTest.test with data set "CatalogRule_Create_ForGuestUsers_ByProductAttribute_AdjustPriceToValue_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 22:177:8 / Magento\Sales\Test\TestCase\MoveRecentlyComparedProductsOnOrderPageTest.test with data set "MoveRecentlyComparedProductsOnOrderPageTestVariationWithConfigurableProduct1_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 22:177:8 / Magento_Sales_Test_TestCase_PrintOrderFrontendGuestTest_phpunit.xml.[empty]
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 22:177:8 / Magento\Sales\Test\TestCase\ReorderOrderEntityTest.test with data set "ReorderOrderEntityTestVariation1_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / isolate:15:167:Magento_Sales_Test_TestCase_CreateOrderBackendPartOneTest / Magento\Sales\Test\TestCase\CreateOrderBackendPartOneTest.test with data set "CreateOrderBackendTestVariation2_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / isolate:15:167:Magento_Sales_Test_TestCase_CreateOrderBackendPartOneTest / Magento\Sales\Test\TestCase\CreateOrderBackendPartOneTest.test with data set "CreateOrderBackendTestVariation3_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / isolate:15:167:Magento_Sales_Test_TestCase_CreateOrderBackendPartOneTest / Magento\Sales\Test\TestCase\CreateOrderBackendPartOneTest.test with data set "CreateOrderBackendTestVariation5_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / isolate:15:167:Magento_Sales_Test_TestCase_CreateOrderBackendPartOneTest / Magento\Sales\Test\TestCase\CreateOrderBackendPartOneTest.test with data set "CreateOrderBackendTestVariation6_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / isolate:15:167:Magento_Sales_Test_TestCase_CreateOrderBackendPartOneTest / Magento\Sales\Test\TestCase\CreateOrderBackendPartOneTest.test with data set "CreateOrderBackendTestVariation7_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 23:185:8 / Magento\SalesRule\Test\TestCase\CreateSalesRuleEntityPartTwoTest.testCreateSalesRule with data set "CreateSalesRuleEntityTestVariation14_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 20:164:8 / Magento\Review\Test\TestCase\CreateProductReviewFrontendEntityTest.test with data set "CreateProductReviewFrontendEntityTestVariation2_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 20:164:8 / Magento\Review\Test\TestCase\MassActionsProductReviewEntityTest.test with data set "MassActionsProductReviewEntityTestVariation1_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 20:164:8 / Magento\Review\Test\TestCase\MassActionsProductReviewEntityTest.test with data set "MassActionsProductReviewEntityTestVariation2_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 20:164:8 / Magento\Review\Test\TestCase\MassActionsProductReviewEntityTest.test with data set "MassActionsProductReviewEntityTestVariation3_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 20:164:8 / Magento\Review\Test\TestCase\MassActionsProductReviewEntityTest.test with data set "MassActionsProductReviewEntityTestVariation4_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 20:164:8 / Magento\Review\Test\TestCase\ModerateProductReviewEntityTest.test with data set "ModerateProductReviewEntityTestVariation1_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 33:265:8 / Magento\Wishlist\Test\TestCase\AddProductToWishlistEntityTest.test with data set "AddProductToWishlistEntityTestVariation2_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 33:265:8 / Magento\Wishlist\Test\TestCase\AddProductToWishlistEntityTest.test with data set "AddProductToWishlistEntityTestVariation3_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 33:265:8 / Magento\Wishlist\Test\TestCase\AddProductToWishlistEntityTest.test with data set "AddProductToWishlistEntityTestVariation4_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 33:265:8 / Magento\Wishlist\Test\TestCase\AddProductToWishlistEntityTest.test with data set "AddProductToWishlistEntityTestVariation5_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 33:265:8 / Magento\Wishlist\Test\TestCase\AddProductToWishlistEntityTest.test with data set "AddProductToWishlistEntityTestVariation9_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 33:265:8 / Magento\Wishlist\Test\TestCase\AddProductToWishlistEntityTest.test with data set "AddProductToWishlistEntityTestVariation10_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 33:265:8 / Magento\Wishlist\Test\TestCase\AddProductToWishlistEntityTest.test with data set "AddProductToWishlistEntityTestVariation11_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 33:265:8 / Magento\Wishlist\Test\TestCase\AddProductToWishlistEntityTest.test with data set "AddProductToWishlistEntityTestVariation12_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 33:265:8 / Magento\Wishlist\Test\TestCase\AddProductToWishlistEntityTest.test with data set "AddProductToWishlistEntityTestVariation13_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 33:265:8 / Magento\Wishlist\Test\TestCase\AddProductToWishlistEntityTest.test with data set "AddProductToWishlistEntityTestVariation14_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 33:265:8 / Magento\Wishlist\Test\TestCase\ConfigureProductInCustomerWishlistOnBackendTest.test with data set "ConfigureProductInCustomerWishlistOnBackendTestVariation2_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 33:265:8 / Magento\Wishlist\Test\TestCase\ConfigureProductInCustomerWishlistOnBackendTest.test with data set "ConfigureProductInCustomerWishlistOnBackendTestVariation3_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 33:265:8 / Magento\Wishlist\Test\TestCase\ConfigureProductInCustomerWishlistOnBackendTest.test with data set "ConfigureProductInCustomerWishlistOnBackendTestVariation4_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 33:265:8 / Magento\Wishlist\Test\TestCase\ConfigureProductInCustomerWishlistOnBackendTest.test with data set "ConfigureProductInCustomerWishlistOnBackendTestVariation5_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 33:265:8 / Magento\Wishlist\Test\TestCase\DeleteProductFromCustomerWishlistOnBackendTest.test with data set "DeleteProductFromCustomerWishlistOnBackendTestVariation1_0"
    MTF / Functional-Tests-CE / Functional Tests CE - MTF / 33:265:8 / Magento\Wishlist\Test\TestCase\DeleteProductFromCustomerWishlistOnBackendTest.test with data set "DeleteProductFromCustomerWishlistOnBackendTestVariation2_0"

**Comment by VladimirZaets** [comment]
@novikor, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Pull request closed without merging**
