### PR TITLE
Small cleanup refactoring

### PR DESCRIPTION
**Pull request by Vinai**
This PR against the develop branch replaces #750.

It contains the following refactorings:

* Fix typo in method name
* Change interpret  method return value to conform with Layout\ReaderInterface

### CODE REVIEW

**Comment by Vinai** [comment]
The integration test failure is because of #913, not because of this PR.

**Comment by vpelipenko** [comment]
@Vinai, #913 is merged, please, update this pull request for green tests.

**Comment by vpelipenko** [comment]
@Vinai, could you remove the last empty commit from this pull request? To re-run tests you just need to click "Restart Job" button on job page (look at https://travis-ci.org/magento/magento2/jobs/45948063 for example). We would like to prevent empty commits in our development history.

**Comment by Vinai** [comment]
Sure, I updated the PR with a squashed commit.

**Comment by vpelipenko** [comment]
CR: passed
Builds: green
Resolution: OK to merge

**Pull request merged**
