### PR TITLE
[CurrencySymbol] Fixing the disabled currency inputs

### PR DESCRIPTION
**Pull request by eduard13**
### Description (*)
This PR fixes the disabled state of currency symbols.

### Fixed Issues (if relevant)
1. Navigate to `Stores / Currency Symbols`
2. Even if the **EUR** and **USD** have disabled state, you still are able to change values and save them.

### Manual testing scenarios (*)
1. Navigate to `Stores / Currency Symbols`
2. The Default Currency Symbols have disabled state, and you aren't able to change their value, until you uncheck the `Use Standard`

### Questions or comments
Not sure how to properly test this fix by MFTF, if anyone have some idea, just let me know.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @eduard13. Thank you for your contribution. Could you cover this case with MFTF test, please?

**Comment by eduard13** [comment]
Hi @rogyar, could you please review the MFTF coverage?
Thank you.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-6728](https://jira.corp.magento.com/browse/ENGCOM-6728) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:x: QA Failed

After unchecking the __Use Standard__ checkbox, the field becomes editable but remains grey. 
It should become white, highlighted. 
gray field

**Comment by eduard13** [comment]
Hi @engcom-Bravo, could you please check it now? Now it should be fine. The not needed `disabled` class has been removed.
Thanks.

**Comment by engcom-Bravo** [comment]
@rogyar Could you please review the latest commit?

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-6728](https://jira.corp.magento.com/browse/ENGCOM-6728) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

Fixed the highlighting 
currency_symbols

**Pull request merged**
