### PR TITLE
[Backport] bundle-product-radio-button-misalign

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Original Pull Request 
 https://github.com/magento/magento2/pull/20519

### Fixed Issues (if relevant)

1. magento/magento2#20518: Bundle product radio button misalign
2. ...

### Manual testing scenarios (*)

1. Any Bundle product
2. Click customize and Add to cart button
3. Radio button misalign

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4041](https://jira.corp.magento.com/browse/ENGCOM-4041) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @amol2jcommerce , thanks for the backport. Looks like the checkbox button is not aligned properly:
image
Can you please check if the fix should be adjusted for 2.2 version.

**Comment by amol2jcommerce** [comment]
* @magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce, here is your [new Magento instance](https://pr-20743.instances.magento-community.engineering).
Admin access: [https://pr-20743.instances.magento-community.engineering/admin](https://pr-20743.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by amol2jcommerce** [comment]
Hi @sivaschenko branch updated. please review.

**Comment by sivaschenko** [comment]
Hi @amol2jcommerce , thanks, we'll retest

**Pull request merged**
