### PR TITLE
MFTF: Refactoring admin check url rewrites multiple storeviews product import test

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
AdminCheckUrlRewritesMultipleStoreviewsProductImportTest is refactored according to the best practices followed by MFTF.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
Run AdminCheckUrlRewritesMultipleStoreviewsProductImportTest in the local environment and verified the test runs successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento run all tests

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @kate-kyzyma. It does look like that for some reason the system cannot generate MFTF tests for the Commerce Edition. Could I ask you to test your changes with the Commerce Edition as well? 

Thank you.

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B

**Comment by dmytro-ch** [comment]
Hello @rogyar, I also faced the same issue for other PRs, it seems to be an infrastructure issue.  The checks successfully passed after restarting the tests.

**Comment by rogyar** [comment]
Hi @dmytro-ch. Thank you for the clarification!

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7623](https://jira.corp.magento.com/browse/ENGCOM-7623) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
