### PR TITLE
#20376 Fix issue with file uploading if an upload field is disabled

### PR DESCRIPTION
**Pull request by serhiyzhovnir**
### Fixed Issues

1. https://github.com/magento/magento2/issues/20376: Image gets uploaded if field is disable in Category 

### Manual testing scenarios

1 Login to admin panel
2 Goto Catalog present on left
3 Then goto Categories
4 Select Dafault category
5 Change Store View to Default Store view
6 Now click to content tab
7 then click Browse to find or drag image here, it will not work untill we don't remove the tick from the Use Default Value
8 But when we simply drags a image on it, then image gets added successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @serhiyzhovnir. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20461) <br/>All committers have signed the CLA.

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-20461.instances.magento-community.engineering).
Admin access: [https://pr-20461.instances.magento-community.engineering/admin](https://pr-20461.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-3937](https://jira.corp.magento.com/browse/ENGCOM-3937) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@serhiyzhovnir thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request merged**
