### PR TITLE
allow the CookieManager class to write the session cookie instead of PHP

### LINKED ISSUE #27531: CookieManager is not used the first time the session cookie PHPSESSID is set
### Preconditions (*)

1. Seen in Magento 2.3.1, 2.3.4 and 2.4-develop
2. We are using a custom CookieManager to work around issue #26377 - https://github.com/Veriteworks/CookieFix
3. We discovered that the Magento session manager does not use CookieManager to set the PHPSESSID cookie, if it was not there before
4. This prevents Magento from setting custom options on the session cookie, if the user did not already have a session cookie
5. If the page makes any AJAX requests, the session cookie is set for those, so the CookieManager is then used and your session cookie will be updated with your custom options.

### Steps to reproduce (*)

1. Take a 2.4-develop instance
2. Create a custom cookie manager (eg. install veriteworks/CookieFix)
3. Visit the store front, then clear your cookies
4. Visit the store home page, and view the requests in the developer window
5. Observe that your custom option is not set in the response headers on the first request, but is set on requests after that

### Expected result (*)

1. The session cookie will always be written by the CookieManager class

### Actual result (*)

When you visit the front end without a session cookie:
1. `\Magento\Framework\Session\SessionManager->start()` is called
2. `\Magento\Framework\Session\SessionManager->start()` calls $this->initIniOptions to run ini_set for every session.xxxx setting
3. `\Magento\Framework\Session\SessionManager->start()` runs `session_start()` - at this point, PHP creates a session ID internally
4. `\Magento\Framework\Session\SessionManager->start()` runs `$this->renewCookie(...)`, but passes a blank session ID
5. `\Magento\Framework\Session\SessionManager->renewCookie(...)` does nothing because the session ID is blank
6. before it exists, PHP notices that the session cookie does not exist, and writes it out using only the options defined by ini_set() earlier.  The Magento CookieManager is not used.

### Possible fixes:
* in SessionManager::renewCookie, allow it to default to `session_id()`
* in SessionManager::start(), add `$sid = session_id();` after `session_start()` to ensure `renewCookie` works

### PR DESCRIPTION
**Pull request by johnorourke**
### Description (*)
* We are using di.xml to provide a custom CookieManager to work around issue #26377 - https://github.com/Veriteworks/CookieFix
* We discovered that the Magento session manager does not use CookieManager to set the PHPSESSID cookie, if it was not there before
* This prevents Magento from setting custom options on the session cookie, if the user did not already have a session cookie
* If the page makes any AJAX requests, the session cookie is set for those, so the CookieManager is then used and your session cookie will be updated with your custom options.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#27531: CookieManager is not used the first time the session cookie PHPSESSID is set

### Manual testing scenarios (*)
1. Create a module which overrides \Magento\Framework\Stdlib\CookieManagerInterface
2. Observe that if you do not have a PHPSESSID cookie, your custom module will not be used - PHP will set its own options

### Questions or comments
In investigating this, I can see potential for simplifying the session manager code.  It uses the ini_set functions to copy Magento config options into PHP ini option, purely for the case where session_start() is run when you have no session cookie.  It would be better to skip this, and ensure the CookieManager class is used every time, so that PHP never needs to write the session cookie itself. Then all the ini_set commands could be removed.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by johnorourke** [comment]
Note - this fix results in the Set-Cookie header being sent twice for PHPSESSID, first one from PHP and the second from your CookieManager

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @johnorourke,
Your changes looks good to me. Could you sign Adobe CLA and cover your changes with any type of automated tests in order to prevent appearing this issue again in future?

**Comment by ihor-sviziev** [comment]
Hi @johnorourke,
Will you be able to sign Adobe CLA and cover your changes with some type of automated tests?

**Comment by ihor-sviziev** [comment]
@johnorourke I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
