### PR TITLE
Minimize complexity for customer address import model

### PR DESCRIPTION
**Pull request by sankalpshekhar**
### Description (*)

This PR simplifies IfElse branching in \Magento\CustomerImportExport\Model\Import\Address
### Fixed Issues (if relevant)

None

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by orlangur — CHANGES_REQUESTED** [review]
@sankalpshekhar please enforce code is simplified by removing corresponding

```
@SuppressWarnings(PHPMD.CyclomaticComplexity)
@SuppressWarnings(PHPMD.NPathComplexity)
```

annotations.

**Comment by sankalpshekhar** [comment]
@orlangur The changes made doesn't eliminates the high Cyclomatic or NPath complexity, but it reduces them. for e.g. prior to change _prepareDataForUpdate() had a Cyclomatic and NPath complexity of 19 & 1080 respectively. With the amends it has been reduced to 17 & 864 respectively, which is still larger than the threshold of 10 & 200.

Other changes address the _cleancode_ recommendation from _PHPMD_ to remove ELSE statements, as it is never necessary.

**Comment by orlangur** [comment]
> recommendation from PHPMD to remove ELSE statements

This is useless actually.

> prior to change _prepareDataForUpdate() had a Cyclomatic and NPath complexity of 19 & 1080 respectively. With the amends it has been reduced to 17 & 864 respectively, which is still larger than the threshold of 10 & 200.

It shouldn't be too hard to refactor into few methods to meet threshold, isn't it?

**Comment by sankalpshekhar** [comment]
@orlangur Reduced the Cyclomatic & NPath complexity to 14 & 540 respectively. Additionally removed unused fields referenced in the constructor

**Review by orlangur — CHANGES_REQUESTED** [review]
Such change is not allowed, see https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/

Please remove PHPMD suppression annotations not relevant after refactoring.

**Comment by sankalpshekhar** [comment]
> Such change is not allowed, see https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/

Such changes are forbidden for classes with @api annotation, however the class in commit here isn't an API.

> Please remove PHPMD suppression annotations not relevant after refactoring.

The refactoring has reduced the complexity, but it hasn't brought it below the threshold

**Comment by orlangur** [comment]
@sankalpshekhar for any class we cannot remove properties. Additional refactoring needs to be applied so that result is measurable and enforced by phpmd.

**Comment by sankalpshekhar** [comment]
Unused fields have been marked as @deprecated, instead of being removed.

Removed nPath complexity for _validateRowForUpdate()

**Comment by sankalpshekhar** [comment]
@orlangur Please let know your review report, and how we can get closure on this?

**Review by orlangur — CHANGES_REQUESTED** [review]
LGTM!

After all builds are green, please squash commits into a single one so that we have perfectly clean history 😉

**Comment by sankalpshekhar** [comment]
@orlangur Multiple commits have been squashed into a single one.

All static tests passed, except for one called out as "Static method cannot be intercepted and its use is discouraged", which I believe if fixed would make the module not backward compatible.

**Comment by sankalpshekhar** [comment]
@orlangur Is there anything else i can help with to get closure on this PR?

**Comment by sivaschenko** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-5575](https://jira.corp.magento.com/browse/ENGCOM-5575) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by engcom-Foxtrot** [comment]
Static test failures fixed in Engcom repo.

**Pull request merged**
