### PR TITLE
Fix typehint

### PR DESCRIPTION
**Pull request by shochdoerfer**
Corrected Quote item type hint.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @shochdoerfer. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3983](https://jira.corp.magento.com/browse/ENGCOM-3983) has been created to process this Pull Request

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-3983](https://jira.corp.magento.com/browse/ENGCOM-3983) has been created to process this Pull Request

**Comment by orlangur** [comment]
> rogyar assigned rogyar and unassigned orlangur 15 minutes ago

@rogyar what?)

**Comment by rogyar** [comment]
@orlangur I had this PR opened in a tab during some time, then assigned to myself (was unassigned). Looks like my request emptied the assignees. It wasn't for a purpose :)

**Comment by orlangur** [comment]
@rogyar yep, sometimes I have the same double approval. Thanks for clarification.

By the way, the bot assigns automatically after approval, no need for this manual action ;)

**Pull request merged**
