### PR TITLE
33540: Removed paragonie/sodium_compat and declared ext-sodium composer dependency

### PR DESCRIPTION
**Pull request by srsathish92**
### Description (*)
I have removed the paragonie/sodium_compat dependency and declared the ext-sodium dependency for both framework and root composer.

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/562

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33540

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@srsathish92 thanks for the pull request! Can you please create a related pull request to https://github.com/magento/partners-magento2ee/ with the corresponding composer.json and lock files updates

**Comment by srsathish92** [comment]
@sivaschenko Sure, I have created the related PR in https://github.com/magento/partners-magento2ee/.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@sivaschenko, looks like the PRs aren't linked. Could you check and fix that?

**Comment by andrewbess** [comment]
@magento run Static Tests

**Review by andrewbess — CHANGES_REQUESTED** [review]
Hello @srsathish92 
Thank you for your contribution.
Could you please resolve merge-conflict.
Thank you in advance

**Comment by srsathish92** [comment]
> Hello @srsathish92
> Thank you for your contribution.
> Could you please resolve merge-conflict.
> Thank you in advance

Fixed the conflicts, Can you please check now. Thanks

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Review by Den4ik — APPROVED** [review]
✅ Looks good for me

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by sivaschenko** [comment]
@magento run Functional Tests B2B

**Review by andrewbess — APPROVED** [review]
Hello @srsathish92 
Thank you for your contribution.
Great job.

**Pull request merged**
