### PR TITLE
fix #13530

### LINKED ISSUE #13530: "Template file 'header.html' is not found" error while trying to save Design Configuration.
### Preconditions
1. Magento `2.2-develop` branch, current commit: f18377b9e59
2. PHP 7.0.27

### Steps to reproduce
1. Setup a clean Magento from the `2.2-develop` using commit f18377b9e59
2. Go into the backend to Content => Design => Configuration
3. Open either the Global or Website scoped configuration
4. Click 'Save and Continue'

### Expected result
1. Configuration should be saved without errors

### Actual result
1. We are getting the error: `Something went wrong while saving this configuration: Template file 'header.html' is not found.`

### Discussion
Curiously enough, this only happens on the Global and Website scope, when trying the same on the Storeview scope, it works and we don't see this error.

### PR DESCRIPTION
**Pull request by AngelBS**
### Fixed Issues (if relevant)

1. magento/magento2#13530: "Template file 'header.html' is not found" error while trying to save Design Configuration. 

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=13931) <br/>All committers have signed the CLA.

**Comment by rogyar** [comment]
Hello, @AngelBS. Thank you for the contribution. 
Your solution fixes the behaviour. However, it does not fix the issue. 
The `design_email_header_template` and `design_email_footer_template` are declared in the `frontend` area but on the attempt to save the design configuration the system tries to find the mentioned templates in the `adminhtml` area. That's the main reason for the issue. 
So, the templates area upon the request should be fixed first of all (from adminhtml to frontend). After that, we will not have the necessity to duplicate the existing templates in frontend and adminhtml (it does not make sense). 
Thanks.

**Comment by rogyar** [comment]
@AngelBS are you going to proceed with this PR?

**Comment by rogyar** [comment]
Closing this request because of no activity

**Pull request closed without merging**
