### PR TITLE
ISSUE-27590 - Improve downloadable link status checks on order placement

### LINKED ISSUE #25177: about Downloadable Product Zero Subtotal Checkout Issue...
### Preconditions (*)

1. Magento 2.3.3 & 2.3-develop
2. PHP 7.3.10

### Steps to reproduce (*)

1. Create a Zero Downloadable Product, set it can be download “INVOICED”
2. set Zero Subtotal Checkout Order status Processing and Auto INVOICE

### Expected result (*)

1. User Order status should be "Complete"
2. User Downloadable should be "Aviable"

### Actual result (*)

1. User Order status is "Closed"
2. User Downloadable is "Pending"

### LINKED ISSUE #27590: Downloadable Product links not available for mixed orders (downloads & shipping products) after payment
### Preconditions (*)

1. Magento CE 2.3.4 on Ubuntu 18.04 LAMP stack migrated from Magento 1.9.4.1

### Steps to reproduce (*)

1. Place an order with downloadable products **and** shipping products
2. Choose any online direct payment method such as credit card or paypal
3. Customer gets the email with download links
2. Go to customer account and try to download the products

### Expected result (*)

1. Download links should be available for download right after payment.

### Actual result (*)

1. Cannot download products, "Link not available".
The order is on status processing, invoice created with status "paid" which is the precondition to make downloads available.

### Additional details
confirmation in multiple scenarios: https://github.com/magento/magento2/issues/27590#issuecomment-609464544 

### Further observations

If I click on "ship order" and the order changes the status to status "complete" links are activated! Its a bad workaround as customers expect their downloads to be available right after payment.

If I purchase digital products only, the order status is directly on "complete" and links are available.

I guess it must be a bug in the order status scheme in relation to download products availability, my expected behavior is the exact way it works in Magento 1 and also what I read from the devdocs for Magento 2. 

Please note there is another bug with downloadable products and order status in case of zero subtotal orders which end on status closed: https://github.com/magento/magento2/issues/25177
So it looks to me like the whole magento_downloadable module is still buggy, maybe this ticket is related in some way?

### PR DESCRIPTION
**Pull request by zaximus84**
### Description (*)

When an order containing downloadable products is placed, observers are executed to create downloadable link records (downloadable_link_purchased_item). Various criteria are checked to determine what the link statuses should be. The user will be unable to access the links until they are marked as available.

Downloadable products can be configured to become available only after the items are invoiced. However, under certain circumstances, the links are still unavailable even after being invoiced. This is because some of the checks are based on order status instead of item status. As an example, an order containing downloadable products and physical items won't reach Complete status until all items are shipped. This means the download links remain unavailable until all items are shipped.

This PR changes the initial check during download link creation to evaluate individual item status instead of order status. If the order item is invoiced, it's marked as available. This resolves issue with both mixed orders (containing downloadable and physical) and zero dollar orders (where the order status skips straight to closed instead of reaching complete).

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/27590
2. Fixes https://github.com/magento/magento2/issues/25177

### Manual testing scenarios (*)
Scenario 1:
1. In store configuration > Catalog / Catalog > Downloadable Product Options, set Order Item Status to Enable Downloads = Invoiced.
1. Configure a payment method that will invoice on order placement, such as Braintree configured with Auth & Capture payment action.
1. Create a downloadable product with downloadable links.
1. Log in to the store front.
1. Add the downloadable product to the cart as well as at least one physical item.
1. Check out, pay with the payment method mentioned above, and place the order.
1. Go to /downloadable/customer/products/ and confirm the appropriate download links are available.

Scenario 2:
1. In store configuration > Sales / Payment Methods > Zero Subtotal Checkout, set New Order Status = Processing and Automatically Invoice All Items = Yes.
1. Perform steps 1 - 4 from scenario 1, but price the downloadable product as $0.
1. On the store front, add the downloadable product to the cart (with no other items), check out, and place the order.
1. Go to /downloadable/customer/products/ and confirm the appropriate download links are available.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by zaximus84** [comment]
@magento run all tests

**Comment by zaximus84** [comment]
@magento run all tests

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Thanks for taking over this!

Could you please address static build failures and consider covering expected behavior with integration test?

**Comment by gabrieldagama** [comment]
The risk was set to`low` due to: the suggested changes shouldn't affect other areas.

**Comment by engcom-Golf** [comment]
Hi @zaximus84 
Could you please update your branch and resolve conflicts? Also please address static build failures and cover expected behavior with auto tests.

**Comment by sidolov** [comment]
@zaximus84  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
