### PR TITLE
Make page title for forgot password page translatable

### PR DESCRIPTION
**Pull request by arnoudhgz**
Original PR: #18598 --> had to be on 2.3 develop branch

### Description (*)
The page title always showed English, because the wrong method was being used to make it translatable.

### Manual testing scenarios (*)
1. Use another language than English (with translation)
2. See that the page title is actually translated

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @arnoudhgz. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by arnoudhgz** [comment]
@larsroettig this is the new PR based on the 2.2-develop PR: https://github.com/magento/magento2/pull/18598

**Comment by larsroettig** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @larsroettig. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @larsroettig, here is your [new Magento instance](https://pr-20940.instances.magento-community.engineering).
Admin access: [https://pr-20940.instances.magento-community.engineering/admin](https://pr-20940.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by larsroettig** [comment]
✅ Review
✅Testing and QA

**Review by larsroettig — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @larsroettig, thank you for the review.
[ENGCOM-4099](https://jira.corp.magento.com/browse/ENGCOM-4099) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @arnoudhgz we cannot reproduce the described issue on 2.3-develop.

Here is the test scenario that we used:
1. Install language pack, for example: Dutch
2. Add string "Forgot Your Password","Forgot Your PasswordEdit",module,Magento_Customer to nl_NL.csv(for example, app/i18n/lang_pack/nl_NL/nl_NL.csv)
3. Set Stores->Configuration->General->Locale Options=Dutch (Netherlands)
4. Flush cache
5. Go to forgot password page (/customer/account/forgotpassword/)

Actual Result:
Page title is translated

image

Can you please help us to reproduce the issue?

**Comment by arnoudhgz** [comment]
@sivaschenko thank you for your feedback and good to see that is already solved. I tried it too... When I first created the PR it was broken on Magento 2.2. I'll close this PR.

**Pull request closed without merging**
