### PR TITLE
Issue #5627: main.CRITICAL: Broken reference (Magento CE v2.1)

### PR DESCRIPTION
**Pull request by malachy-mcconnell**
- Changed log level from critical to info

### Fixed Issues (if relevant)

1. magento/magento2#5627: main.CRITICAL: Broken reference (Magento CE v2.1)

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=9092) <br/>All committers have signed the CLA.

**Comment by Ctucker9233** [comment]
@malachy-mcconnnell In my opinion, all this does is downgrade the issue instead of fixing the issue. Right now, if there is a real broken link, it is lost in a sea of other reported broken links and the developer has no clue which one is the real Critical Error. Is it possible to expand the scope of this PR to fix the reason why these "broken links" are being reported in the first place?

**Comment by magento-team** [comment]
@malachy-mcconnnell thank you for your contribution to Magento 2 project

**Comment by scottsb** [comment]
@okorshenko I think @Ctucker9233 is correct that this doesn't fully resolve #5627. I think downgrading this situation from CRITICAL is legitimate (though I would have picked WARNING as the best level per PSR-3/RFC 5424), but the problem in #5627 is that core Magento with no changes is logging spurious messages. The fact that they were improperly CRITICAL made it worse, but the fundamental issue was that they were getting logged in the first place. This doesn't fix that.

**Comment by orlangur** [comment]
Is it going to be fixed the way I explained https://github.com/magento/magento2/issues/5627#issuecomment-279440749 ? So that all existing issues, including ones downgraded to INFO in this PR, are fixed and this perfect state is enforced by CI?

**Pull request merged**
