### PR TITLE
#28422 :- Newsletter subscription confirmation email never sent again

### LINKED ISSUE #28422: Newsletter subscription confirmation email never sent again
### Preconditions (*)
1. Magento 2.4-develop
### Steps to reproduce (*)
1. Enable newsletter subscription confirmation ("Need to Confirm" option)
2. Log in with an account which is not subscribed to the newsletter
3. Subscribe to the newsletter from My account > Newsletter Subscription
4. An email asking for subscription confirmation is received.
5. Imagine the user does not confirm, deletes the email, forgets it or anything else, but he does not confirm his newsletter subscription
6. He comes back some time later and wants to subscribe to the newsletter, so he does the process again
7. Subscribe to the newsletter from My account > Newsletter Subscription

### Expected result (*)
1. The confirmation email is sent again

### Actual result (*)

1. The confirmation email is never sent again.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by konarshankar07**
### Description (*)

This PR will fix the issue with resending newsletter email if user didn't confirmed to the newsletter subscription
### Fixed Issues (if relevant)

1. Fixes magento/magento2#28422

### Manual testing scenarios (*)

1. Enable newsletter subscription confirmation ("Need to Confirm" option)
2. Log in with an account which is not subscribed to the newsletter
3. Subscribe to the newsletter from My account > Newsletter Subscription
4. An email asking for subscription confirmation is received.
5. Imagine the user does not confirm, deletes the email, forgets it or anything else, but he does not confirm his newsletter subscription
6. He comes back some time later and wants to subscribe to the newsletter, so he does the process again
7. Subscribe to the newsletter from My account > Newsletter Subscription

### Expected Result
Newsletter subscription email will be received
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by konarshankar07** [comment]
@magento run all tests

**Comment by rogyar** [comment]
Hi @konarshankar07. Thanks a lot for your fix. 
We need to adjust the unit tests correspondingly to cover the change. The cyclomatic complexity of the exiting method (failing static test) has nothing to do with your changes but you may resolve it as well if you wish. Just keep backward compatibility in mind. 

Thank you!

**Comment by konarshankar07** [comment]
@magento run all tests

**Comment by konarshankar07** [comment]
Hello @rogyar ...
For fixing cyclomatic complexity can I create a private function? I read the https://devdocs.magento.com/contributor-guide/backward-compatible-development/ doc but it didn't mentioned that we can create any new private function

**Comment by rogyar** [comment]
Hi @konarshankar07 you may create new private functions. This change does not violate backward compatible development principles. 

Thank you!

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @konarshankar07. Thanks for collaboration. Do you have any updates?

**Comment by konarshankar07** [comment]
@magento run Static Tests

**Comment by engcom-Charlie** [comment]
Hi @konarshankar07, can you please add a short description to the new method to fix the static test?
Thanks for your collaboration.

**Comment by konarshankar07** [comment]
Hello @engcom-Charlie ...
Method name is already self explanatory so I don't think we need to add the short description. Let me know your thought
Thanks

**Comment by engcom-Charlie** [comment]
@konarshankar07 agree with you but it needs to add to fix static test.

**Comment by konarshankar07** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8034](https://jira.corp.magento.com/browse/ENGCOM-8034) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Enable newsletter subscription confirmation (Go to Admin -> Stores -> Configuration -> Customers -> Newsletter and set "**Need to Confirm**" option to "**Yes**")
2. Log in with an account which is not subscribed to the newsletter;
3. Subscribe to the newsletter from My account > Newsletter Subscription;
4. An email asking for subscription confirmation is received;
5. Imagine the user does not confirm, deletes the email, forgets it or anything else, but he does not confirm his newsletter subscription;
6. He comes back sometime later and wants to subscribe to the newsletter, so he does the process again;
7. Subscribe to the newsletter from My account > Newsletter Subscription;

**Before:** :heavy_multiplication_x: The confirmation email is never sent again.

**After:** :heavy_check_mark: The confirmation email is sent again and we can confirm the newsletter subscription

**Review by rogyar — APPROVED** [review]

**Pull request merged**
