### PR TITLE
#24452 Category Admin UI does not save tree changes unless OK button is clicked 

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)
The code was not working on enter press because there was no event handler added for enter press in the modal component, I have added it and called the button 2 click 

### Fixed Issues (if relevant)
1. magento/magento2#24452 : Category Admin UI does not save tree changes unless OK button is clicked 

### Manual testing scenarios (*)

1. Login admin 
2. goto categories 
3. Now drag any category to your desired position
4. popup will appear to confirm
5: press enter and the popup will be closed but the category position will not be saved

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-24498.instances.magento-community.engineering).
Admin access: [https://pr-24498.instances.magento-community.engineering/admin](https://pr-24498.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-5803](https://jira.corp.magento.com/browse/ENGCOM-5803) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @ashutoshwebkul.

During testing we faced with the issue.

_**Problem:**_ When you press the "Enter" button, js error message appears

**Manual testing scenario:**

1. Login to Admin;
2. Go to Catalog->Categories;
3. Create several categories;
4. Now drag any category to your desired position;
5. Popup will appear to confirm;
6. Press "Enter" button

**Actual Result:**  js error message appears
after

@ashutoshwebkul Could you take a look, please?

Thanks!

**Comment by sidolov** [comment]
@ashutoshwebkul  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
