### PR TITLE
Correct swagger definition for is_default

### PR DESCRIPTION
**Pull request by pmclain**
### Description (*)
Attribute options `is_default` does not return a bool, but rather an array of
strings containing the store ids the option value is default for. Correcting
the phpdocs fixes the incorrect return type being reported in the generated
swagger docs.

### Fixed Issues (if relevant)
1. magento/magento2#16657 REST API: catalogProductAttributeManagementV1 Get returns Array insted of Boolean for is_default

### Manual testing scenarios (*)
1. Create admin oauth token
2. Use token to request attributes for default product attribute set via the rest api
```
curl -X GET \
  https://{{store_url}}/rest/V1/products/attribute-sets/4/attributes \
  -H 'Authorization: Bearer {{valid token}}
```
3. The default option value for the `country_of_manufacture` is returned as an array (current behaviour)
```
...
    {
        "label": "United States",
        "value": "US",
        "is_default": [
            "1"
        ]
    },
...
```
4. View the swagger UI, https://{{store_url}}/swagger the definition for `is_default` in `GET /V1/products/attribute-sets/{attributeSetId}/attributes` matches the current behaviour.
```
"options": [
      {
        "label": "string",
        "value": "string",
        "sort_order": 0,
        "is_default": [
          "string"
        ],
        "store_labels": [
          {
            "store_id": 0,
            "label": "string"
          }
        ]
      }
    ],
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @pmclain. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3248](https://jira.corp.magento.com/browse/ENGCOM-3248) has been created to process this Pull Request

**Comment by sidolov** [comment]
Hi @pmclain unfortunately, we cannot deliver such changed to the patch releases according to our Backward Compatibility policy, docblock of API classes is a part of API too and cannot be changed (affected interface also used for webapi service calls and we may break a lot of 3d party services that expects bool instead of array). I'll move your PR to on hold and we will deliver changes to the next minor release. 
Thank you!

**Comment by ihor-sviziev** [comment]
@sidolov 2.4-develop branch was already created. Is there any updates on this PR?

**Comment by sidolov** [comment]
@slavvka could you please share updates on this? Thanks!

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-3248](https://jira.corp.magento.com/browse/ENGCOM-3248) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @pmclain 
Unfortunately, We are not able to reproduce this problem on 2.4-develop instance.

**Actual Result:**
The default option value for the country_of_manufacture is returned as a bool
screen1

View the swagger UI
screen2

@pmclain Could you take a look?

Thanks!

**Comment by ihor-sviziev** [comment]
Hi @pmclain,
Will you be able to review following testing report https://github.com/magento/magento2/pull/18709#issuecomment-581847344 and give your feedback?

**Comment by ihor-sviziev** [comment]
@pmclain  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
