### PR TITLE
Update Row.php

### PR DESCRIPTION
**Pull request by Maddesto**
current solution doesnt work with staging, if row_id != entity_id, status will be not correct, select from catalog_product_entity to apply staging

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19368) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=19368) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
Hi @Maddesto. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by nuzil** [comment]
Hello @Maddesto, thanks a lot for your contribution. May I ask you to add some testing scenario with what is your fix exactly fixing and how it can be reproduced. 
Thanks a lot

**Comment by nuzil** [comment]
Also can you please check Codacy tests and sync your branch with mainline

**Comment by nuzil** [comment]
Closed due to inactivity. Feel free to reopen if you want to finish this PR

**Pull request closed without merging**
