### PR TITLE
[TEST] DO NOT PROCESS

### PR DESCRIPTION
**Pull request by super-user-test-tool**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — DISMISSED** [review]

**Comment by m2-github-services** [comment]
@sidolov thank you for the review! We have changed pull request base branch in order to provide ability to merge current pull request and schedule MQP patch delivery job.

**Review by sidolov — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Review by sidolov — DISMISSED** [review]

**Comment by sidolov** [comment]
@sidolov thank you for the review! We have changed pull request base branch in order to provide ability to merge current pull request and schedule MQP patch delivery job.

**Comment by m2-github-services** [comment]
@sidolov thank you for the review! We have changed pull request base branch in order to provide ability to merge current pull request and schedule MQP patch delivery job.

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Review by sidolov — DISMISSED** [review]

**Comment by m2-github-services** [comment]
@sidolov thank you for the review! We have changed pull request base branch in order to provide ability to merge current pull request and schedule quality patch delivery job.

**Pull request closed without merging**
