### PR TITLE
Clean backslash in global di xml

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Clean up unnecessary backslash define in `argument`. Class does not need leading backslash
Example
Should use
`<argument name="logger" xsi:type="object">Psr\Log\LoggerInterface\Proxy</argument>`
instead<br/>
`<argument name="logger" xsi:type="object">\Psr\Log\LoggerInterface\Proxy</argument>`

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

Smoke test

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Seems like it’s doing the same as https://github.com/magento/magento2/pull/26948

**Comment by mrtuvn** [comment]
Ok i will close this one

**Pull request closed without merging**
