### PR TITLE
#31764: Improve check on field prefix

### LINKED ISSUE #31764: main_table prefix on exception company_name
<!---
Please review our guidelines before adding a new issue: https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Fields marked with (*) are required. Please don't remove the template.
--]

### Preconditions (*)
[!---
Provide the exact Magento version (example: 2.4.0) and any important information on the environment where bug is reproducible.
--]
1. Magento 2.3.6 B2B
1. Magento 2.4 B2B

### Steps to reproduce (*)
[!---
Important: Provide a set of clear steps to reproduce this bug. We can not provide support without clear instructions on how to reproduce.
--]
1. Login to admin panel
1. Customer > All Customers
1. Show company name column 
1. Filter by company name

After further investigation and collaboration i have found the cause for the issue, to replicate this issue. 

A new collection is needed with an add a join from a field from the custom table to the customer grid collection, and try to filter the collection with that field.

### Expected result (*)
[!--- Tell us what do you expect to happen. --]
1. In 2.4-develop without B2B features enabled - Company filter is working fine with Billing/shipping address company name.

### Actual result (*)

After installing B2B, Company name is removed for all existing normal customers from Customers page.
For Company Account customers - Company name is displayed in the Company column but filtering with the same company name is not working. Filtering with billing / shipping Address - Company name works.

```
[2021-01-19 16:25:17] report.CRITICAL: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'main*table.company_name' in 'where clause', query was: SELECT COUNT(*) FROM `customer_grid_flat` AS `main*table`
 LEFT JOIN `directory*country_region` AS `rct` ON rct.region_id=`main_table`.`billing_region*id`
 LEFT JOIN `directory*country_region_name` AS `rnt` ON rnt.region_id=`main_table`.`billing_region_id` AND rnt.locale='en*GB'
 LEFT JOIN `company*advanced_customer_entity` AS `company_customer` ON company_customer.customer_id = main_table.entity*id
 LEFT JOIN `company` ON company.entity*id = company_customer.company_id WHERE (`main_table`.`company_name` LIKE '%naveo%') {"exception":"[object] (Zend_Db_Statement_Exception(code: 42): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'main_table.company_name' in 'where clause', query was: SELECT COUNT(*) FROM `customer_grid_flat` AS `main*table`
 LEFT JOIN `directory*country_region` AS `rct` ON rct.region_id=`main_table`.`billing_region*id`
 LEFT JOIN `directory*country_region_name` AS `rnt` ON rnt.region_id=`main_table`.`billing_region_id` AND rnt.locale='en*GB'
 LEFT JOIN `company*advanced_customer_entity` AS `company_customer` ON company_customer.customer_id = main_table.entity*id
 LEFT JOIN `company` ON company.entity*id = company_customer.company_id WHERE (`main_table`.`company_name{{ LIKE '%naveo%') at /Users/Dava/Sites/espo/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:110, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'main_table.company*name' in 'where clause' at /Users/Dava/Sites/espo/vendor/magento/framework/DB/Statement/Pdo/Mysql.php:91)"} [>
}}``


## 
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- < ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- [x] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- [ > Severity: **S4** *- Affects aesthetics, professional look and feel, "quality" or "usability".*

### PR DESCRIPTION
**Pull request by DavaGordon**
### Description (*)

This change prevents magento throwing exception when filtering customer admin grids due to a column not having a the prefix of main_table.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31764

### Manual testing scenarios (*)

1. Login to admin panel
2. Customer > All Customers
3. Show company name column
4. Filter by company name

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by DavaGordon** [comment]
@magento run all tests

**Comment by DavaGordon** [comment]
@magento run all tests

**Comment by danielrussob** [comment]
@magento give me test instance

**Comment by danielrussob** [comment]
@magento give me 2.4-develop instance

**Comment by danielrussob** [comment]
As linked from @gabrieldagama 

List of tests failing:
AdminAddRemoveDefaultVideoGiftCardProductTest
AdminAddRemoveDefaultVideoVirtualProductTest
AdminAddRemoveDefaultVideoBundleProductTest
StorefrontGalleryConfigurableProductWithVisualSwatchAttributePrependMediaTest
StorefrontGalleryConfigurableProductWithSeveralAttributesPrependMediaTest

We are working on fixing those, once that is done we can rerun the tasks and make sure they are green, will keep you posted! Thanks!

**Comment by danielrussob** [comment]
@magento give me new instance with edition b2b

**Comment by danielrussob** [comment]
@magento give me test instance with edition b2b

**Comment by danielrussob** [comment]
Hello @DavaGordon DavaGordon, Thank you for your contribution
on the instance of b2b based on your PR, there is no problem but
on the instance of Community Edition based on your PR (give me test instance) there's a problem on Customer CRUD grid

the edit button under "Action" column (in the grid) is missing

and accessing directly to INSTANCEURL/customer/index/edit/id/1/

just tab Customer View is present and other tabs are missing

this instance go to 503 rhythmically, I don't know if it was a problem with Magento Cloud (error on s:d:c or similar) or with your PR

I will test it again later

**Comment by danielrussob** [comment]
@magento give me test instance

**Comment by DavaGordon** [comment]
> Hello @DavaGordon DavaGordon, Thank you for your contribution
> on the instance of b2b based on your PR, there is no problem but
> on the instance of Community Edition based on your PR (give me test instance) there's a problem on Customer CRUD grid
> 
> the edit button under "Action" column (in the grid) is missing
> 
> and accessing directly to INSTANCEURL/customer/index/edit/id/1/
> 
> just tab Customer View is present and other tabs are missing
> 
> this instance go to 503 rhythmically, I don't know if it was a problem with Magento Cloud (error on s:d:c or similar) or with your PR
> 
> I will test it again later

@danielrussob the issues you raised i have tested locally and was unable to replicate on a magento-cloud docker instance.
As part of my testing I set this up on a community based version and ee edition and can confirm that this fix raises no issues as the fix specifically relates to the customer grid functionality all other pages extend from the base method.

If you have any questions please feel free to drop me a message.

**Comment by danielrussob** [comment]
@magento give me test instance

**Comment by danielrussob** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by danielrussob** [comment]
We (@DavaGordon and Me) have tested the issue on Magento 2.4-develop vanilla with b2b and we are not able to reproduce the issue

@sdzhepa We are chatting about the option to replace in any case app/code/Magento/Customer/Model/ResourceModel/Grid/Collection.php:84 , beacuse this new change could be a better solution in long term, can we discuss about quality?

**Comment by DavaGordon** [comment]
As per our conversation in regards to the code quality at this moment in time to code has no checks in place to see if the field exists within the main_table (customer_grid_flat).

My recommendation is to check the index to see if the column exists if it does prepend main_table. on the front of it as the records exists. 

`$this->getFulltextIndexColumns()`

**Result** 
```
Array
(
    [0] => name
    [1] => email
    [2] => created_in
    [3] => taxvat
    [4] => shipping_full
    [5] => billing_full
    [6] => billing_firstname
    [7] => billing_lastname
    [8] => billing_telephone
    [9] => billing_postcode
    [10] => billing_region
    [11] => billing_city
    [12] => billing_fax
    [13] => billing_company
)
```
Prior to this fix we were getting the following error 

`Unknown column 'main_table.company_name' `

After implementation it was able to check that the column was not present in customer_grid_flat and was able to get the data date from the correct source in this case the company table previously left joined 

**Tested**
Magneto EE/CE 
Version: 2.3.6 / 2.4.0

**Comment by gabrieldagama** [comment]
@magento give me 2.4-develop instance with edition b2b

**Comment by DavaGordon** [comment]
After further investigation and collaboration with @gabrieldagama we  found the cause for the issue could possibly be when a new collection with an add a join from a field from the custom table to the customer grid collection, and try to filter the collection with that field.

**Comment by aleron75** [comment]
@magento run Functional Tests CE

**Comment by danielrussob** [comment]
@magento run Functional Tests B2B

**Comment by danielrussob** [comment]
@magento run Functional Tests CE

**Comment by ishakhsuvarov** [comment]
Closing this for now as tests had been red for a long time with no updates.

Please feel free to reopen if you still want to continue working on this.

**Pull request closed without merging**
