### PR TITLE
Fixed Adding out of stock items to wishlist shows success message but fails

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

Fixed Adding out of stock items to wishlist shows success message but fails
### Fixed Issues (if relevant)

1. magento/magento2#21519: Adding out of stock items to wishlist shows success message but fails

### Manual testing scenarios (*)

1. Navigate to an out of stock product page
2. Add product to wishlist

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by krishprakash** [comment]
@magento-engcom-team give me 2.3-test instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-test instance for you

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5158](https://jira.corp.magento.com/browse/ENGCOM-5158) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
Hi @ravi-chandra3197 I cannot reproduce issue [#21519](https://github.com/magento/magento2/issues/21519) on 2.3-develop. Please, take a look for [comment](https://github.com/magento/magento2/issues/21518#issuecomment-487753589)

**Comment by sidolov** [comment]
@ravi-chandra3197 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
