### PR TITLE
Fixed fatal error if upgrading from Magento v2.0.0 to v2.3 and non system attributes missing

### PR DESCRIPTION
**Pull request by suneet64**
Fixed fatal error if upgrading from Magento v2.0.0 to v2.3 and non system attributes missing.

### Description (*)

A fatal error while setup:upgrade if you are upgrading from Magento v2.0.0 to Magento v2.3 and non system attributes not exist in the existing database.

### Manual testing scenarios (*)

1. Have a Magento v2.0.0 clean installation.
2. Remove manufacturer and color attributes from **Stores > Attributes > Product** as these are not system attributes.
3. Upgrade the Magento to v2.3 using command line
4. Enable the display_errors from app/bootstrap.php file.
5. **Before:** Execute setup:upgrade and while upgrading data you will notice a fatal error because of missing manufacturer and color attributes.
**After:** The fatal error disappear in this fix.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @suneet64. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — APPROVED** [review]
Thanks @suneet64!

Very similar to https://github.com/magento/magento2/pull/19514/files.

Wondering if we have any other updates.

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3609](https://jira.corp.magento.com/browse/ENGCOM-3609) has been created to process this Pull Request

**Comment by suneet64** [comment]
Hi @orlangur ,

I didn't find any other update for this.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3609](https://jira.corp.magento.com/browse/ENGCOM-3609) has been created to process this Pull Request

**Comment by sdzhepa** [comment]
✔️ QA passed

**Pull request merged**
