### PR TITLE
Cleanup ObjectManager usage - Magento_Config

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This PR cleanups ObjectManager usage in Magento_Config, adds additional dependencies with backward compatibility to api classes, and removes object manager instantiation from non-api classes.

### Fixed Issues (if relevant)

N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@slavvka @lenaorobei could you give us info why we have "No build reports available" on this PR?

**Comment by slavvka** [comment]
@Bartlomiejsz @ihor-sviziev Tests are failing due to:
```
02:22:54 [Build Functional EE] [2020-04-15 07:22:54] report.ERROR: There are no commands defined in the "deploy:mode" namespace.
02:22:54 [Build Functional EE] #0 /var/www/html/vendor/symfony/console/Application.php(650): Symfony\Component\Console\Application->findNamespace('deploy:mode')
02:22:54 [Build Functional EE] #1 /var/www/html/vendor/symfony/console/Application.php(235): Symfony\Component\Console\Application->find('deploy:mode:set')
02:22:54 [Build Functional EE] #2 /var/www/html/lib/internal/Magento/Framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
02:22:54 [Build Functional EE] #3 /var/www/html/vendor/symfony/console/Application.php(147): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
02:22:54 [Build Functional EE] #4 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
02:22:54 [Build Functional EE] #5 {main} [] []
```

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @Bartlomiejsz,
Could you fix the issue listed above?

**Comment by ihor-sviziev** [comment]
Hi @Bartlomiejsz,
Tests still failing, please check it

**Comment by Bartlomiejsz** [comment]
Hi @slavvka, got a question, was anything changed in how instances for testing are built? I believe issue you mentioned could be caused by not executed setup:di:compile after modification of existing constructor dependencies, and I'm not able to reproduce such issue on my local branch once di is complied

**Comment by ihor-sviziev** [comment]
@Bartlomiejsz 
All tests still failing. Looks like the issue happens during `bin/magento deploy:mode:set production`. Please try it locally.

**Comment by Bartlomiejsz** [comment]
@ihor-sviziev that's really weird, I was able to set Magento into production mode without any issues:
```
Enabling maintenance mode
Starting compilation
Compilation was started.
%message% 0/8 [>---------------------------]   0% < 1 sec 76.5 MiBProxies code generation... 0/8 [>---------------------------]   0% < 1 sec 76.5 MiB
Proxies code generation... 1/8 [===>------------------------]  12% 1 sec 80.5 MiB
Repositories code generation... 1/8 [===>------------------------]  12% 1 sec 80.5 MiB
Repositories code generation... 2/8 [=======>--------------------]  25% 25 secs 203.0 MiB
Service data attributes generation... 2/8 [=======>--------------------]  25% 25 secs 203.0 MiB
Service data attributes generation... 3/8 [==========>-----------------]  37% 25 secs 203.0 MiB
Application code generator... 3/8 [==========>-----------------]  37% 25 secs 203.0 MiB
Application code generator... 4/8 [==============>-------------]  50% 44 secs 229.0 MiB
Interceptors generation... 4/8 [==============>-------------]  50% 44 secs 229.0 MiB
Interceptors generation... 5/8 [=================>----------]  62% 1 min 261.0 MiB
Area configuration aggregation... 5/8 [=================>----------]  62% 1 min 261.0 MiB
Area configuration aggregation... 6/8 [=====================>------]  75% 1 min 339.0 MiB
Interception cache generation... 6/8 [=====================>------]  75% 1 min 339.0 MiB
Interception cache generation... 7/8 [========================>---]  87% 1 min 337.0 MiB
App action list generation... 7/8 [========================>---]  87% 1 min 337.0 MiB
App action list generation... 8/8 [============================] 100% 1 min 337.0 MiB
Generated code and dependency injection configuration successfully.
Compilation complete
Starting deployment of static content

Deploy using quick strategy
frontend/Magento/blank/en_US            2252/2252           ============================ 100%   40 secs
adminhtml/Magento/backend/en_US         2258/2258           ============================ 100%   45 secs
frontend/Magento/luma/en_US             2269/2269           ============================ 100%   45 secs

Execution time: 142.07347202301
Deployment of static content complete
Disabling maintenance mode
Enabled production mode.

```
I will try to dig into possible reasons, but for now I'm not sure what can be cause of that.

**Comment by ihor-sviziev** [comment]
@slavvka, could you add detailed steps to reproduce of this issue? We can't reproduce this issue locally

**Comment by slavvka** [comment]
@Bartlomiejsz @ihor-sviziev I found another error during the installation:
```
01:11:01 [Build Functional CE] Installing user configuration...
01:11:01 [Build Functional CE] PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\Config\Model\Config\Structure\ElementVisibilityInterface in /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:50
01:11:01 [Build Functional CE] Stack trace:
01:11:01 [Build Functional CE] #0 /var/www/html/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Config\\...')
01:11:01 [Build Functional CE] #1 /var/www/html/app/code/Magento/Config/Model/Config/Structure/AbstractElement.php(62): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Config\\...')
01:11:01 [Build Functional CE] #2 /var/www/html/app/code/Magento/Config/Model/Config/Structure/Element/Field.php(75): Magento\Config\Model\Config\Structure\AbstractElement->__construct(Object(Magento\Store\Model\StoreManager), Object(Magento\Framework\Module\Manager))
01:11:01 [Build Functional CE] #3 /var/www/html/generated/code/Magento/Config/Model/Config/Structure/Element/Field/Interceptor.php(14): Magento\Config\Model\Config\Structure\Element\Field->__construct(Object(Magento\Store\Model\StoreManager), Object(Magento\Fr in /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php on line 50
01:11:09 [Build Functional CE] {"messages":{"error":[{"code":500,"message":"Server internal error. See details in report api\/627486201398"}]}
```

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @Bartlomiejsz,
Seems like the issue in DI, you need to pass [proxy](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/proxies.html) object via di.xml in constructor for case that causes test failure.

Could you update your PR?

**Comment by slavvka** [comment]
@Bartlomiejsz are you going to continue working on it? Also please resolve the conflicts

**Comment by Bartlomiejsz** [comment]
Hi @slavvka, I can work on that, however I have two doubts:
- `AbstractElement` class is inherited by few children, so it would require to set up proxy for each of them - if in some project code someone inherits this class (which is strongly possible), such change might be breaking
- 2.4.0 branch is no longer open for features - will such change be approved if I'll finish it at this point?

**Comment by slavvka** [comment]
@Bartlomiejsz yes, you right. 2.4.0 is in regression phase. But we are going to work out a delivery strategy to 2.5 where we can deliver this PR. So I am closing it for now and please feel free to recreate it once we are ready to accept PRs to 2.5

**Pull request closed without merging**
