### PR TITLE
Error on design configuration save with imageUploader form element po…

### PR DESCRIPTION
**Pull request by yurii-v-git**
…pulated from gallery #21032

### Description (*)

This change fixes all file uploads on the theme config edit form page when is used "Select from Gallery" chooser of images.

### Fixed Issues (if relevant)

1. magento/magento2#21032: Error on design configuration save with imageUploader form element populated from gallery

### Manual testing scenarios (*)

1. Log in to Admin panel
2. Go to Content -> Design -> Configuration
3. Click "Edit" link in a grid
4. Expand "Header" fieldset
5. Click "Select from Gallery" button for " Logo Image" field
6. Select any image and click on "Add Selected" button
7. Click the "Save Configuration" button
8. The success message is shown (the image was stored without any errors)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22132) <br/>All committers have signed the CLA.

**Review by orlangur — APPROVED** [review]

**Comment by sidolov** [comment]
Hi @yvechirko , looks like you made some commits with email different than in your GitHub profile, please, add email from commits to your profile!
Thank you!

**Comment by jurpro** [comment]
Hello. Is there any fix error of this? I have the same error. Thank you.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-4800](https://jira.corp.magento.com/browse/ENGCOM-4800) has been created to process this Pull Request

**Comment by soleksii** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @stoleksiy. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @stoleksiy, here is your [Magento instance](https://i-22132-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22132-2-3-develop.instances.magento-community.engineering/admin](https://i-22132-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by soleksii** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @stoleksiy. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @stoleksiy, here is your [new Magento instance](https://pr-22132.instances.magento-community.engineering).
Admin access: [https://pr-22132.instances.magento-community.engineering/admin](https://pr-22132.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed 

**Precondition:**

Set pub folder as DocumentRoot in Apache2 configuration
set1

**Steps to reproduce issue:**
1. Log in to Admin panel;
2. Go to Content -> Design -> Configuration;
3. Click "Edit" link in a grid;
4. Expand "Header" field set;
5. Click "Select from Gallery" button for " Logo Image" field;
6. Select any image and click on "Add Selected" button;
7. Click the "Save Configuration" button;

**Before:**
before

**After:**
after

**Note:** 

If **DocumentRoot** is set to default, the issue #21032 is not reproducible

**Pull request merged**
