### PR TITLE
Use Variable for border-radius

### LINKED ISSUE #28674: [Issue] Use Variable for border-radius
**Preconditions:**
This issue is automatically created based on existing pull request: magento/magento2#28548: Use Variable for border-radius

The border-radius was hardcoded, so i changed it to: @button__border-radius

**Steps to reproduce:**

Variable **@button__border-radius** is defined in `lib/web/css/source/lib/variables/_buttons.less` library and has default value for border-radius = 3px
screenshot_51

**Actual Result**

**Expected Result**

We don't need to hardcoded value if we use the default value for the border-radius

### PR DESCRIPTION
**Pull request by Scarbous**
The border-radius was hard coded, so i changed it to: @button__border-radius

### Resolved issues:
1. [x] resolves magento/magento2#28674: Use Variable for border-radius

### CODE REVIEW

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7630](https://jira.corp.magento.com/browse/ENGCOM-7630) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

The size of the border-radius is still the same as before (expected)

For example:

screenshot_49

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Pull request merged**
