### PR TITLE
Adding sql conditions constants in AdapterInterface

### PR DESCRIPTION
**Pull request by alessandrozucca**
I'm adding some sql constant for 'like', 'nlike' which currently are hardcoded all over
the codebase. Having constants makes it easier to find what are all the available options

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=5778) <br/>All committers have signed the CLA.

**Comment by ghost** [comment]
Internal Ticket created: MAGETWO-56738

**Comment by vkublytskyi** [comment]
@alessandrozucca, thank you for contribution.

As string literals with condition codes is used not only in DB adapter (e.g. `Magento\Framework\Data\Collection\Filesystem`) it's make sense to move constants outside from `Magento\Framework\DB\Adapter\AdapterInterface`.

@alessandrozucca would you improve your PR and move introduced constants to `Magento\Framework\Data\ConditionInterface` (without  `SQL_CONDITION_`  prefix)?

**Comment by alessandrozucca** [comment]
Hi @vkublytskyi, yep makes sense.
I will submit an update

**Comment by alessandrozucca** [comment]
@vkublytskyi changes added :)

**Comment by vkublytskyi** [comment]
@alessandrozucca, thank you for quick update

**Comment by okorshenko** [comment]
Closing this pull request. Sorce branch was removed

**Pull request closed without merging**
