### PR TITLE
Add missing entity type constraint to catalog URL rewrite check

### LINKED ISSUE #31225: [Issue] Add missing entity type constraint to catalog URL rewrite check
This issue is automatically created based on existing pull request: magento/magento2#31218: Add missing entity type constraint to catalog URL rewrite check

---------

### Description (*)

This fixes the error
```
main.CRITICAL: Notice: Trying to access array offset on value of type bool in vendor/magento/module-catalog-url-rewrite/Model/Storage/DynamicStorage.php on line 182 
```

Which happens if one tries to access a URL which ends with a category URL rewrite. It happens because `findProductRewriteByRequestPath` in that class doesn't constrain the `$productFromDb` select with the `product` entity type (or `$categoryFromDb` with the `category` entity type for that matter, but it doesn't directly contribute to this bug), and falsely returns the category URL rewrite for `$productFromDb`. This causes the method to continue even though it should return null at this point, leading to it trying to access the `redirect_type` property of the falsy `$categoryFromDb` on line 182, which generates the notice and causes the error report to show.

### Manual testing scenarios (*)

1. Create a category with the name "Test Category" and set the URL path as "test-category". Doesn't matter at which level the category is.
2. Access "<base_url>/asdf/test-category". The "asdf" here is just any fake path in the store, meaning that normally a 404 page should show.

Due to this bug a notice will be shown if you're in developer mode, a Magento error report otherwise.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x]  All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### LINKED ISSUE #31235: [Issue] Add missing entity type constraint to catalog URL rewrite check
This issue is automatically created based on existing pull request: magento/magento2#31218: Add missing entity type constraint to catalog URL rewrite check

---------

### Description (*)

This fixes the error
```
main.CRITICAL: Notice: Trying to access array offset on value of type bool in vendor/magento/module-catalog-url-rewrite/Model/Storage/DynamicStorage.php on line 182 
```

Which happens if one tries to access a URL which ends with a category URL rewrite. It happens because `findProductRewriteByRequestPath` in that class doesn't constrain the `$productFromDb` select with the `product` entity type (or `$categoryFromDb` with the `category` entity type for that matter, but it doesn't directly contribute to this bug), and falsely returns the category URL rewrite for `$productFromDb`. This causes the method to continue even though it should return null at this point, leading to it trying to access the `redirect_type` property of the falsy `$categoryFromDb` on line 182, which generates the notice and causes the error report to show.

### Manual testing scenarios (*)

1. Create a category with the name "Test Category" and set the URL path as "test-category". Doesn't matter at which level the category is.
2. Access "<base_url>/asdf/test-category". The "asdf" here is just any fake path in the store, meaning that normally a 404 page should show.

Due to this bug a notice will be shown if you're in developer mode, a Magento error report otherwise.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x]  All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31225: Add missing entity type constraint to catalog URL rewrite check

### PR DESCRIPTION
**Pull request by aapokiiso**
### Description (*)

This fixes the error
```
main.CRITICAL: Notice: Trying to access array offset on value of type bool in vendor/magento/module-catalog-url-rewrite/Model/Storage/DynamicStorage.php on line 182 
```

Which happens if one tries to access a URL which ends with a category URL rewrite. It happens because `findProductRewriteByRequestPath` in that class doesn't constrain the `$productFromDb` select with the `product` entity type (or `$categoryFromDb` with the `category` entity type for that matter, but it doesn't directly contribute to this bug), and falsely returns the category URL rewrite for `$productFromDb`. This causes the method to continue even though it should return null at this point, leading to it trying to access the `redirect_type` property of the falsy `$categoryFromDb` on line 182, which generates the notice and causes the error report to show.

### Manual testing scenarios (*)

1. Create a category with the name "Test Category" and set the URL path as "test-category". Doesn't matter at which level the category is.
2. Access "<base_url>/asdf/test-category". The "asdf" here is just any fake path in the store, meaning that normally a 404 page should show.

Due to this bug a notice will be shown if you're in developer mode, a Magento error report otherwise.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x]  All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31225: Add missing entity type constraint to catalog URL rewrite check

### Resolved issues:
1. [ ] resolves magento/magento2#31235: Add missing entity type constraint to catalog URL rewrite check

### CODE REVIEW

**Comment by aapokiiso** [comment]
@magento run all tests

**Comment by aapokiiso** [comment]
The failing functional tests don't seem to be related to this change.

**Comment by rogyar** [comment]
@magento create issue

**Review by rogyar — CHANGES_REQUESTED** [review]
@aapokiiso good catch! According to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered by auto-tests. 

Could I kindly ask you to cover your fix with an MFTF test that will create a category and assert that there's no notice in developer mode on visiting URL that ends on the category-rewrite basis. 

Thank you!

**Comment by sidolov** [comment]
@magento create issue

**Comment by engcom-Hotel** [comment]
Hello @aapokiiso .
I will help with tests.

**Comment by engcom-Hotel** [comment]
@aapokiiso not able to reproduce the issue, could you please check my comment in https://github.com/magento/magento2/issues/31225 ?

**Comment by aapokiiso** [comment]
@engcom-Hotel Hi, thanks for your testing. I'll see what is causing this in our Magento instance. The fix itself is quite straight-forward (imo), but I'll check why the issue doesn't happen with a clean Magento instance.

**Comment by engcom-Hotel** [comment]
Hello @aapokiiso,
Closing the PR due to inactivity.
Feel free to reopen it if you have additional information for reproducing the issue.
Thank you.

**Comment by JelleGe** [comment]
> @engcom-Hotel Hi, thanks for your testing. I'll see what is causing this in our Magento instance. The fix itself is quite straight-forward (imo), but I'll check why the issue doesn't happen with a clean Magento instance.

How did you fix this issue? We face the same problem at the moment with Magento 2.4.1 and php7.4

**Comment by JelleGe** [comment]
Sadly we still face the issue on php7.4, when the product is removed. Even with the following fix:
https://github.com/aapokiiso/magento2/tree/catalogurlrewrite-dynamic-storage-entity-type-constraint

**Pull request closed without merging**
