### PR TITLE
Free Shipping Patch fixes 

### PR DESCRIPTION
**Pull request by markalston**
Cart price rules for free shipping are broken on all shipping methods including Free Shipping.  Currently cart rules do not work at all properly on UPS, FedEx or USPS.  On the Free Shipping Method either the entire shipment is free or none of it.  You cannot allow only free shipping on selected items (contrary to what is shown as possible in the cart rules generation page).

### Description
This patch takes the pull request #11502 of @JosephMaxwell and fixes it such that free shipping works on select items only.  It also changes the PR to properly charge for non-free items and not change the rate charges as free items are added and removed from the order.

### Fixed Issues (if relevant)

1. magento/magento2#12573 Free Shipping Shopping Cart Rule doesn't work with UPS
2. magento/magento2#14206 Free Shipping For Matching Items Only
3. magento/magento2#10704 Free shipping code is not working for UPS for magento 2
### Manual testing scenarios
1. Generate a Cart price rule for free shipping on selected items (or subtotal of selected items).
2. Add free shipping and non free shipping items to cart.
3. Go to checkout and see proper shipping charges (or free charges) depending on items added to cart.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14277) <br/>All committers have signed the CLA.

**Comment by Edelman06** [comment]
The courier delivery companies are increasing day by day. The most important thing to consider is the reliability when hiring a company. If you want to pick right service then just get the feedbacks from their existing customers or can get the recommendations from others. We have also found the best [Courier services Ft Worth](https://deliveryservicedallas.com/) and are satisfied with their work.

**Comment by Sil-B** [comment]
Great fix. Thanks!

**Comment by orlangur** [comment]
@markalston,

> All commits are accompanied by meaningful commit messages

Could you please squash your changes and make commit messages actually meaningful?

**Comment by markalston** [comment]
@orlangur Sorry about the individual commits. Seems like no way to avoid that when editing directly on Github. 

For my help, which commit messages are not meaningful?

**Comment by orlangur** [comment]
@markalston all of them. Commit message must reflect what was fixed and not which files were updated.

> Seems like no way to avoid that when editing directly on Github.

You can edit message prior to committing but AFAIR only one file may be edited at once. After changes are finalized, please squash them into a single commit using Git locally and force push into the same branch.

**Comment by sidolov** [comment]
Hi @markalston , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by vasilii-b** [comment]
In case anyone comes here in 2022 looking for the fix (patch) - seems it's over [here](https://support.magento.com/hc/en-us/articles/360060101131-MDVA-36138-free-shipping-rule-not-applied-cart-multiple-items) from the Quality Patches tool under the code MDVA-36138.

Hope I saved you some time 🤞🏻

**Pull request closed without merging**
