### PR TITLE
Fix Magento2#36230: Stale links to topics migrated to Adobe domains

### LINKED ISSUE #36230: Stale links to topics migrated to Adobe domains
### Summary (*)
Adobe migrated Magento documentation to Adobe domains.
https://devdocs.magento.com/migrated.html

### Examples (*)
The pull request description template itself is a clear example:

```
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.
```

The link points to https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog, which was moved to https://developer.adobe.com/commerce/contributor/guides/code-contributions/#community-backlog-priority.

### Proposed solution
The solution is simple enough: update the links :-)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Tomasito665**
### Description (*)

Many Magento documentation articles migrated from https://devdocs.magento.com/ to Adobe domains. See the following article for an exhaustive list: https://devdocs.magento.com/migrated.html. When using the old links, some articles appear greyed out with a link to the new location, like this one:

image

And some others redirect automatically from https://devdocs.magento.com/ to their new location under  *.adobe.com/ like, for example, https://docs.magento.com/user-guide/catalog/catalog-urls.html, which redirects to https://experienceleague.adobe.com/docs/commerce-admin/catalog/catalog/catalog-urls.html. This pull request updates all devdocs.magento.com links to their new locations.

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
1. Fixes magento/magento2#36230

### Manual testing scenarios (*)
1. Go to the "Contribute" section of the main README, click on "Report an issue", and assert that it redirects to a working page that does not redirect to somewhere else.

### Questions or comments
Not all links were updated because not all documentation is migrated; consider this a first pass to update links of documentation that was already migrated. We will need to file another pull request in the future when all documentation is migrated to Adobe domains.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [X] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
Hi @Tomasito665 

Thank you for your contribution. Unfortunately introducing so many changes also raises a requirement to fix a lot outdated coding style issues that got detected by static tests.

If possible, please take a look at failed static tests and address problems accordingly.

Thanks

**Comment by glo05363** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
Hello @Tomasito665,

Please resolve the conflicts, so that we can move further with this PR for review.

Thanks

**Comment by engcom-Dash** [comment]
Closing this PR due to no response to the last https://github.com/magento/magento2/pull/36238#issuecomment-2352803963 Feel free to reopen it.

**Pull request closed without merging**
