### PR TITLE
Fixed Click for price in home page not work #15922

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

Fixed Click for price in home page not work #15922
### Fixed Issues (if relevant)

1. magento/magento2#15922:Click for price in home page can`t work 

### Manual testing scenarios (*)

N/A
### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-19663.instances.magento-community.engineering).
Admin access: [https://pr-19663.instances.magento-community.engineering/admin](https://pr-19663.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by DanielRuf — COMMENTED** [review]
Why were the IDs removed?

**Comment by rogyar** [comment]
@DanielRuf please, check the previous attempt for details https://github.com/magento/magento2/pull/17376

**Comment by DanielRuf** [comment]
So these are definitely not used by other scripts and styles?

**Comment by rogyar** [comment]
In this particular case, they are not

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
