### PR TITLE
#13157 - Last Ordered Items block - bad js code

### PR DESCRIPTION
**Pull request by omiroshnichenko**
### Description
Fix logic in last-order-items.js and Recently Ordered block.

### Fixed Issues
magento/magento2#13157: Last Ordered Items block - bad js code

### Manual testing scenarios
1. Create order for registered customer
2. Verify that Add to Cart button in Recently Ordered block reflects is_salable property of recently ordered product

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @omiroshnichenko. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by ishakhsuvarov** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov, here is your [new Magento instance](http://34.228.235.121/pr-19039/).
Admin access: [http://34.228.235.121/pr-19039//admin](http://34.228.235.121/pr-19039//admin)
Login: `admin` Password: `123123q`

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3378](https://jira.corp.magento.com/browse/ENGCOM-3378) has been created to process this Pull Request

**Comment by sidolov** [comment]
Hi @omiroshnichenko , we found several issues with provided fix: 

**case 1:** Add to Cart button disappear after product was added to cart from 'Recently Ordered' section
1. Open admin panel
2. Create simple product Simple1 
3. Login to Storefront as Customer
4. Click Add to Cart 
5. Submit Order
6. Proceed to My Account page
7. Enable checkbox Simple1 in 'Recently Ordered' section
8. Click Add to Cart button in 'Recently Ordered' section 
9. Check button Add to Cart in 'Recently Ordered' section 
**10.  Button is not visible**
11. Refresh My Account page (F5)
12.  Add to Cart is visible in 'Recently Ordered' section

case 2: Add to Cart button is not visible after product change Status Stock from "Out of Stock" to "In Stock"

1. Open Backend
2. Create simple product Simple1 with qty=1
3. Login to Storefront as Customer
4. Click Add Product to cart (qty=1)
5. Submit Order
6. Go to My Account page
7. Check 'Recently Ordered' section. 
8.  Button Add to Cart is not visible
9. Open Backend 
10. Go to Catalog - Products
11. Click Edit simple1
12. Input Quantity=1, Status Stock= In Stock
12. Save product
13. Open My Account page on Storefront
14. Check 'Recently Ordered' section

 **Expected:**
Add to Cart is visible in 'Recently Ordered' section

 **Actual:** 
Add to Cart isn't visible in 'Recently Ordered' section

**Comment by omiroshnichenko** [comment]
Hi @sidolov, first case was fixed. Second case is not related to this issue. Problem is with customer data invalidation. Currently, Magento invalidates customer data on any POST request that goes from storefront. So, I think separate issue should be created for second case.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3378](https://jira.corp.magento.com/browse/ENGCOM-3378) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @omiroshnichenko. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
