### PR TITLE
Updated the error reporting for the Config Element Iterator.

### PR DESCRIPTION
**Pull request by PivitParkour94**
### Description

Attempt to make the debugging a little easier when the system configuration is incorrect.
Needed to add the App state class and the Logger to determine how much logging is used and how to get the error to the end developer or user.
Updated the PHPUnit test to have logger and state mocks. Included a Unit test for confirming the exception message in developer mode.

### Fixed Issues (if relevant)

1. N/A

### Manual testing scenarios

0. Enable developer mode
1.  Pull in module with invalid system config
2. Try navigating to the Stores -> Configuration
3. Ensure there is a clear exception being thrown explaining which element key is breaking

### Contribution checklist
 - [ x ] Pull request has a meaningful description of its purpose
 - [ x ] All commits are accompanied by meaningful commit messages
 - [ x ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ? ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @PivitParkour94. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by ihor-sviziev** [comment]
Hi @PivitParkour94,
Could you describe some use-case when such changes might be useful? How we actually need to test your change?
PS: also check failed tests, we can't accept PR when tests are failing

**Comment by PivitParkour94** [comment]
@ihor-sviziev Yeah no worries,

I was working on an installation which had some third-party code that had invalidated `adminhtml/system.xml` files. I was given a vague issue and it took some excessive debugging to find it, in my opinion debugging should be caught by the code, and as a community we can make little tweaks to make the job easier for every other developer, why wouldn't we share that via a PR.

So there's not really a use case, it's more just a general improvement to hopefully cut out a few extra hours of debugging.

**Comment by ihor-sviziev** [comment]
@PivitParkour94,
In order to accept/reject any solution - we have to understand what the issue did you tried to fix. Could you prepare any code example, steps to reproduce, or something else, then we'll be able to understand your issue and will decide is it fixed correctly or we should adjust something?

**Comment by PivitParkour94** [comment]
Don't worry about it, I just wanted to solve it globally instead of having a tacky local solution. That's fine, I'll just close this off.

Cheers

**Pull request closed without merging**
