### PR TITLE
enable merge js in default mode

### PR DESCRIPTION
**Pull request by alekszakatov**
### Description (*)
Enable js bundle for default build mode

### Manual testing scenarios (*)
  1. Switch to default mode
 2. Enable js bundle in admin
3. Check bundle js filies on front

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by alekszakatov** [comment]
@magento run all tests

**Comment by alekszakatov** [comment]
@magento run all tests

**Comment by alekszakatov** [comment]
@magento run all tests

**Comment by alekszakatov** [comment]
@magento run all tests

**Comment by alekszakatov** [comment]
@magento run all tests

**Comment by alekszakatov** [comment]
@magento run all tests

**Comment by alekszakatov** [comment]
@magento run all tests

**Comment by alekszakatov** [comment]
@magento run all tests

**Comment by alekszakatov** [comment]
@magento run all tests

**Comment by alekszakatov** [comment]
@magento run all tests

**Comment by alekszakatov** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
Hi @alekszakatov . Thanks for collaboration. As we discussed on Contribution Triage Meeting, your changes will change the community and extension developer's experience, but the benefit of it is not really hight. Due to it, I close this PR.

The discussion with PO you can see by the [link](https://www.youtube.com/watch?v=gsefmmeDMWM&list=PLDvMskiz68Q2BLkj0-xzjuFl7ZVti9Quj&index=2&t=639s)  

If you have some concerns about it or want to provide additional information, feel free to contact me here or join our Contribution Triage session.
The schedule you can find on Magento Community Calendar [page](https://opensource.magento.com/community-calendar)

**Pull request closed without merging**
