### PR TITLE
magento/magento2#16968 Adding force reload product

### PR DESCRIPTION
**Pull request by otsmyh**
Adding force reload product

### Description (*)

We need to reload product in this place, because products
with the same id may have different sets of order attributes.
Has been implemented suggested solution.

### Manual testing scenarios (*)
Please see issue description.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19394) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=19394) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
Hi @otsmyh. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
@otsmyh please provide detailed steps to reproduce.

**Comment by otsmyh** [comment]
Issue: https://github.com/magento/magento2/issues/16968


Preconditions
Tested on Magento 2.1.11, but by checking the code, this will still fail on Magento 2.2

Steps to reproduce
Hang on, this is complicated ;)

I am adding configurable products to the cart, programmatically. Some of these products have low stock, let's say: one item in stock each. The problem occurs when I add multiple variants of the same configurable in the same request.

/** @var \Magento\Checkout\Model\Cart $cart */

$params = [
    'qty' => 1,
    'super_attribute' => [
        $product1['super_attribute_id'] => $product1['option_id']
    ]
];

$this->cart->addProduct($configurableId, $params);

$params = [
    'qty' => 1,
    'super_attribute' => [
        $product2['super_attribute_id'] => $product2['option_id']
    ]
];

$this->cart->addProduct($configurableId, $params);
When I run this code, which adds two variants of the same configurable, I get this error:

"We don't have as many "" as you requested."

So while each variant has stock of 1, when I add 1 of each to the cart, I still get an out-of-stock error.

I traced the cause of this error to this line:

$product = $this->productRepository->getById($productInfo, false, $storeId);
(in vendor/magento/module-checkout/Model/Cart.php : 304)

It loads the configurable that is used as a "candidate" for the cart. When the configurable is needed twice in the request, it is loaded from the product repository cache, and not created anew. The problem with this is that this product model is later modified with some "custom options" (especially "attributes"), that should make the first configurable different from the second configurable. They are used to compare present cart products to check if they are in the cart already (\Magento\Quote\Model\Quote\Item::compareOptions()).

Since the same configurable is used twice (while it shouldn't) it is added a qty of 1, which gives it a quantity of 2, and this exceeds the stock of the variants, and this gives the named error.

Expected result
I should be able to add multiple variants of a configurable (with low stock).

Actual result
"We don't have as many "" as you requested."

**Comment by sivaschenko** [comment]
Hi @otsmyh thanks for the contribution. The problem is valid, it cannot be reproduced from UI as `\Magento\Checkout\Model\Cart::addOrderItem` method is used, that force reloads a product before calling the `addProduct`.

However, considering that `\Magento\Checkout\Model\Cart` is deprecated I don't think it should be used for adding products to the cart programmatically. Can you please check if `\Magento\Quote\Model\Quote::addProduct` will work for you as expected.

Actually, I think it's even better and more safe to use the interface methods like `\Magento\Quote\Api\Data\CartInterface::setItems` via `\Magento\Quote\Api\CartItemRepositoryInterface::save`. See example here: https://github.com/magento/magento2/blob/8c2e1789281c8ed95bfb60e74b071ff9f59ad2e9/dev/tests/integration/testsuite/Magento/CheckoutAgreements/Model/Checkout/Plugin/GuestValidationTest.php#L228

**Comment by sidolov** [comment]
Hi @otsmyh , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
