### PR TITLE
Issue in adding the wishlist of "zero price" product

### PR DESCRIPTION
**Pull request by gelanivishal**
### Description
Fixed add to wishtlist item which price is zero. 

### Fixed Issues (if relevant)

1. magento/magento2#16479:Issue in adding the wishlist of "zero price" product

### Manual testing scenarios

1. Login as a customer in front end of the website.
2. Open product with zero price
3. Click on the wishlist button in the product.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by sidolov** [comment]
Hi @gelanivishal , we can't reproduce this issue on the vanilla 2.2-develop branch, please, check once again. 

**Our steps for reproducing:** 
1. Create simple product with Price=0.
2. Login as a customer.
3. Go to product detail page.
4. Click ADD TO WISH LIST

**Actual result:**
Product is added to wishlist without error
16494main

**Comment by gelanivishal** [comment]
@sidolov You can reproduce in v2.2.4 instance, For more information please check https://github.com/magento/magento2/issues/16479 

Thank you.

**Comment by orlangur** [comment]
@gelanivishal the fix is against `2.2-develop`, so, you need to test on `2.2-develop` as well, not on other `2.2.x` release.

**Comment by gelanivishal** [comment]
@orlangur I have found an issue on v2.2.4 version so Do I push changes on 2.3-develop branch?

Thank you.

**Comment by orlangur** [comment]
@gelanivishal no, you should reproduce an issue on `2.2-develop` or `2.3-develop` and only after this create a PR.

**Comment by gelanivishal** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal, here is your [Magento instance](https://i-16494-2-2-develop.engcom.dev.magento.com).
Admin access: [https://i-16494-2-2-develop.engcom.dev.magento.com/admin](https://i-16494-2-2-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by gelanivishal** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal, here is your [Magento instance](https://i-16494-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-16494-2-3-develop.engcom.dev.magento.com/admin](https://i-16494-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by gelanivishal** [comment]
@sidolov @orlangur I can reproduce error on 2.3-develop, Please check attached screenshot of above instance 


So, I'll create a new PR for 2.3-develop

Thank you.

**Comment by gelanivishal** [comment]
@sidolov @orlangur I have created a new https://github.com/magento/magento2/pull/16537 PR for 2.3-develop branch

Thank you.

**Comment by sidolov** [comment]
@gelanivishal , in this case, I'm closing this PR as not relevant, thank you for the contribution!

**Pull request closed without merging**
