### PR TITLE
Fixxes #15565

### PR DESCRIPTION
**Pull request by EliasKotlyar**
Fix for #15565 

### Description
Simple Fix

### Fixed Issues (if relevant)
Fix for #15565 

### Manual testing scenarios
See Ticket

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@EliasKotlyar thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VladimirZaets** [comment]
Hi @vgelani, please, sign CLA, otherwise, we can't process pull request

**Comment by gelanivishal** [comment]
@VladimirZaets Already signed.

**Comment by magento-engcom-team** [comment]
Hi @EliasKotlyar. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.6 release.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
