### PR TITLE
Some strings not translatable in M2.4.1

### LINKED ISSUE #31849: Some strings not translatable in M2.4.1
### Preconditions (*)
1. Clean Magento 2.4.1 installation
1. 2.4-develop

### Steps to reproduce (*)
1. Add a product to cart
1. Navigate to cart page
1. Open admin interface, find the product, save it as "Out of Stock"
1. Refresh cart page, see error message: **There are no source items with the in stock status**
1. Find the translation for the message in <magento install dir>vendor/magento/module-catalog-inventory/i18n/en_US.csv
1. Change the result string to be something else
1. Clean "translate" cache
1. Refresh the cart page and witness the previously mentioned string being not translated to value we changed it at point 6

### Expected result (*)
1. Error messages are translated

### Actual result (*)
1. Error messages are not translated - can be verified even with default en_US language - change the translation for the error message

### NOTES
The **steps to reproduce** part only highlights one specific string, however this seems to be a more general problem:

Due to update of design (and translations) loading in https://github.com/magento/magento2/commit/b2a035d93c98487b69bbcd6b719e79ddf8e39574
(loading design and translations was moved from beforeDispatch to beforeExecute)

However there are several plugins in M2 ecosystem, which come before actual execute call, \Magento\InventorySales\Model\IsProductSalableForRequestedQtyCondition\IsProductSalableForRequestedQtyConditionChain is one of the many examples (on quote loading, validation is triggered).

Verified this in clean Magento 2.4.1 - the error phrase is never translated, as renderers for Phrase is set only in \Magento\Theme\Plugin\LoadDesignPlugin::beforeExecute

This happens due to renderer not being set to \Magento\Framework\Phrase, and if it is used earlier than the renderers are set - the original string gets returned, as it uses the RendererPlaceholder class to render them.

With current state, a lot of strings cannot be translated, the only imaginable workaround is to move design and translations loading back to beforeDispatch method. (Moving just the translation loading to beforeDispatch won't help, if the translations are in theme.)

## 
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- < ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- [x] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- [ > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

### PR DESCRIPTION
**Pull request by engcom-Kilo**
### Description (*)

Translation load happens to late, skipping all observers subscribed on controller action predispatch

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/31849

### Manual testing scenarios (*)

1. https://github.com/magento/magento2/issues/31849

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by mrtuvn** [comment]
@engcom-Kilo Can you check with coverage if we remove unneccessary part load translate in here ? Maybe we call load for translate part twice

trace paths
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Theme/Plugin/LoadDesignPlugin.php <= this call to desginLoader for load translate

https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/View/DesignLoader.php#L55 <= area load translate part

**Comment by ihor-sviziev** [comment]
@engcom-Kilo feels like your test coverage isn’t covering the case with translation. Can we write some integration test for that?

**Comment by engcom-Kilo** [comment]
> @engcom-Kilo Can you check with coverage if we remove unneccessary part load translate in here ? Maybe we call load for translate part twice
> 
> trace paths
> https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Theme/Plugin/LoadDesignPlugin.php <= this call to desginLoader for load translate
> 
> https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/View/DesignLoader.php#L55 <= area load translate part
> Actually this call load for design first -> then load to translate -> then check design change
> 
> `LoadDesignPlugin` is already known caused high load make write a lot cache to redis localstorage on server. We should addressing this

Hello @mrtuvn 
Thanks for your notice. I've seen this plugin, there will be no additional loading because of local cache
https://github.com/magento/magento2/blob/dfd17e9da1c9e92098b82d10406ddc1f7b7cf82e/lib/internal/Magento/Framework/App/AreaList.php#L128
https://github.com/magento/magento2/blob/dfd17e9da1c9e92098b82d10406ddc1f7b7cf82e/lib/internal/Magento/Framework/App/Area.php#L204

**Comment by engcom-Kilo** [comment]
> @engcom-Kilo feels like your test coverage isn’t covering the case with translation. Can we write some integration test for that?

Hello @ihor-sviziev 
Unfortunately I haven't found possibility to verify this changes with integration test as 
https://github.com/magento/magento2/blob/f258736279c358b38c082b4d8e1d55100945d2d0/dev/tests/integration/framework/Magento/TestFramework/Annotation/AppArea.php#L83 called on test start, which invokes
https://github.com/magento/magento2/blob/f258736279c358b38c082b4d8e1d55100945d2d0/lib/internal/Magento/Framework/App/Area.php#L245
before front controller, and translations are working anyway, with changes or without.

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Database Compare, Functional Tests B2B, WebAPI Tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8881](https://jira.corp.magento.com/browse/ENGCOM-8881) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Review by zakdma — APPROVED** [review]

**Comment by dmitriyprime** [comment]
:heavy_check_mark: QA passed

**Before:**
before

**After:**
after

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-32326`.

**Pull request merged**
