### PR TITLE
Mark classes and interfaces as API part 4

### LINKED ISSUE #32672: Mark classes and interfaces as API part 4
Mark the following classes and interfaces as APIs

1. Magento\Framework\Data\Form\Element\Factory
1. Magento\Customer\Controller\Adminhtml\Index
1. Magento\Sales\Model\Order\Email\Sender\OrderSender
1. Magento\Sales\Model\Order\Email\Sender\InvoiceSender
1. Magento\Customer\Model\Url
1. Magento\Framework\UrlFactory
1. Magento\Cms\Model\Template\FilterProvider
1. Magento\Sales\Model\Service\InvoiceService
1. Magento\Framework\HTTP\Adapter\Curl
1. Magento\Framework\Convert\DataObject

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Marked the following classes and interfaces as APIs

Magento\Framework\Data\Form\Element\Factory
Magento\Customer\Controller\Adminhtml\Index
Magento\Sales\Model\Order\Email\Sender\OrderSender
Magento\Sales\Model\Order\Email\Sender\InvoiceSender
Magento\Customer\Model\Url
Magento\Framework\UrlFactory
Magento\Cms\Model\Template\FilterProvider
Magento\Sales\Model\Service\InvoiceService
Magento\Framework\HTTP\Adapter\Curl
Magento\Framework\Convert\DataObject

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32672
2. 
### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Closed and re-opened PR in order to trigger adobe CLA check again
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8990](https://jira.corp.magento.com/browse/ENGCOM-8990) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run WebAPI Tests

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama the branch with code successfully imported into`magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-32682`.

**Pull request merged**
