### PR TITLE
Make Framework coding standard compliant

### PR DESCRIPTION
**Pull request by dverkade**
Started work on the Magento Framework to become coding standard compliant.
- Removed all instances of ignoring the coding standards in the docblock
- Ran PHPCBF over it in order to fix issues
- Manually fixed issues.

### CODE REVIEW

**Comment by dverkade** [comment]
This is still a work in progress and I will fix all outstanding issues file by file.

**Comment by jameshalsall** [comment]
Please don't merge PRs like this, they make diffs very difficult to read and offer very little value.

If there are coding standards issues then they should be addressed as and when code changes naturally occur on those lines.

**Comment by dverkade** [comment]
Hi @jameshalsall 

I do not agree with this. The core of Magento has neglected to adhire their own coding standard and has put the @codingStandardsIgnoreFile entry on top of every file which throws errors. This is not correct and should be fixed.

It's weird and just plain stupid that you want to enforce and test for coding violations and then ignore the files which throw errors. Why check for them in the first place? If someone requests a PR or a core developer makes a change in those files it will not check for coding standard either. In order to get better code and a better platform all files and classes should respect the coding standard. 

It's up to Magento to determine if they want to merge this PR when it's finished.

**Comment by akira28** [comment]
I really like what you are doing here!
To make this happen I think you should also fix those tests that are failing.

**Comment by ihor-sviziev** [comment]
@dverkade would be great to do not create pull request until you're finish working on it & all tests will be passed. Anyway, it's really good progress!

**Comment by orlangur** [comment]
This PR is already nearly impossible to process and it's just Framework part. Automated changes must not be mixed with some manual work.

I described viable strategy and why it won't work this way [here](https://github.com/magento/magento2/pull/6913#issuecomment-252564568).

**Comment by dverkade** [comment]
Hi @orlangur what do you mean by "Automated changes must not be mixed with some manual work."

**Comment by orlangur** [comment]
Hi @dverkade,

To minimize code review efforts changes like https://github.com/magento/magento2/pull/7166/commits/24e674364ea19b12c2fea40666c5713fc3827978 and https://github.com/magento/magento2/pull/7166/commits/7d7c32772ab93f96869cf2f138a583c3d1658f9d must be done automatically and in separate commits mentioning exact command performed. So that reviewer can just execute the same command and assure that output is exactly the same.

**Comment by okorshenko** [comment]
@dverkade are you still working on this or we can close this PR?

**Comment by dverkade** [comment]
Hi @okorshenko 

Is see that many of these issues have been fixed by merging this pull request: 8685
I think it is better to close this one, since it's open to long and has to many conflicts. I will run the tests again on the develop branch and will submit a PR for every file that's need to change, so that the PR's are smaller and easier to accept. 

Is that a solution that works best for you guys?

**Comment by orlangur** [comment]
@dverkade seeing update in this PR I wanted to suggest you joining my efforts on making codebase standards compliant :)

Here is the detailed plan: https://github.com/magento/magento2/pull/8823#issuecomment-285180479

Let's do the 1. similar to approach I used in 8685:
- create temporary branch
- remove `@codingStandardsIgnoreFile` from `*.php` files with some automated tool (NOT touching `*.phtml` until we upgrade `phpcs`) 
- apply automatic fixes by `phpcbf`, `php-cs-fixer`
- apply manual fixes all over the codebase until we have zero violations (arbitrary amount of commits here - just like you did in this PR)
- after we have all builds green with temporary branch synced with mainline, we start to create clean branch for PR
- first we do squashed manual commits, grouped as it seems logical to us (for example, I did https://github.com/magento/magento2/pull/8685/commits/c3e7df5f892b5d54de115033d28f9908bc4ebb95 as separate commit to isolate such changes from other violations fixes)
- then we add three automatic commits - annotation removal and fixes by two tools
- and then we will probably need one more small manual commit to fix some new violations coming from `develop`
- wait for PR to be processed and reapply automatic fixes as needed

**Pull request closed without merging**
