### PR TITLE
[Backport 2.3 -> 2.2] Fix meta title property & Updated unit test

### PR DESCRIPTION
**Pull request by gelanivishal**
### Original Pull Request
#11368

### Description
If, inside a controller you try to set metadata title with:

    $resultPage->getConfig()->setMetadata('title', 'some meta title');

you will get an error on frontend:

Recoverable Error: Object of class Magento\Framework\View\Page\Title could not be converted to string...

becouse `processMetadataContent` will return an istance of `Magento\Framework\View\Page\Title` instead of a string.

### Fixed Issues (if relevant)

1. magento/magento2#2956: Unable to render page when 'meta title' page config param is set

#### Scenario 1

1. Create a controller
2. Inside the `execute` function add: 
```
$resultPage = $this->resultPageFactory->create();
$resultPage->getConfig()->getTitle->set('my title');
$resultPage->getConfig()->setMetadata('title', 'metatitle');
return $resultPage;
```
3. As result you will have in your page:

```
<title>my title</title>
<meta name="title" content="metatitle"/>
```

#### Scenario 2

1. Create a controller
2. Inside the `execute` function add: 
```
$resultPage = $this->resultPageFactory->create();
$resultPage->getConfig()->getTitle->set('my title');
return $resultPage;
```
3. As result you will have in your page:

```
<title>my title</title>
<meta name="title" content="my title"/>
```

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @vgelani. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
@vgelani please do not rewrite authors of original commits during porting. Feel free to do just a one commit with `git commit -c 32e2e4de5921ecb7b13722955298e886ec2b2d59`, just that @slackerzz should be properly credited as author and you as author of port will be mentioned as committer.

**Comment by gelanivishal** [comment]
@orlangur Yeah, I got it. I'll take care in next PR.

**Comment by orlangur** [comment]
@vgelani, thanks for your endeavors, @slackerzz will take care of this PR porting. He noticed some changes were missed which resulted in failing unit test.

**Pull request closed without merging**
