### PR TITLE
Text overlap on the close icon.

### PR DESCRIPTION
**Pull request by suryakant-krish**
### Description (*)

1. This is direct PR because it is small change.

### Fixed Issues (if relevant)

1. This is direct PR because it is a small change.

### Manual testing scenarios (*)

1. Login into admin panel > Go to store configuration > Select any store when modal box open add some extra text through inspect element. Text overlap on close icon.
2. Actual Result.
actual-result
3. Expected Result. 
expected-result

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by Karlasa** [comment]
Hi @suryakant-krish 

I would say it's more about issue of not having title element in this confirm popup.
Adding padding like that would look odd on confirms where title exists. 

Cheers,

**Comment by suryakant-krish** [comment]
@Karlasa, @sidolov

Go to admin panel > Catalog > Category > Change store view.
Please find attached screesnshot.
Reproduce on 2.3

actual-result

**Comment by miguelbalparda** [comment]
I'm with @Karlasa on this one, will close. Feel free to reopen if anything changes. Thanks!

**Pull request closed without merging**
