### PR TITLE
[Forwardport] [Correct code formatting]

### PR DESCRIPTION
**Pull request by hitesh-wagento**
### Original Pull Request 
 https://github.com/magento/magento2/pull/15811
### This PR is a:

- [ ] Bug fix or improvement

### Summary
Correct Code formatting.

### Additional information
NA

### CODE REVIEW

**Comment by hitesh-wagento** [comment]
@orlangur Could you please check what cause failed travis?

Thanks,

**Comment by hitesh-wagento** [comment]
Hello @orlangur

Any update in this PR ?

Thanks

**Comment by orlangur** [comment]
@hitesh-wagento same PR targeting `2.2-develop` should be processed first.

**Comment by orlangur** [comment]
@hitesh-wagento please force push into this branch once PR targeting `2.2-develop` is merged, currently there are unintended changes in `Customer` `di.xml` here.

**Comment by hitesh-wagento** [comment]
@orlangur Could you please check what cause failed travis?

Thanks,

**Comment by orlangur** [comment]
@hitesh-wagento no, you are supposed to do it.

Closing as this PR contains changes not related to original PR. Please use a tool to create a port.

**Pull request closed without merging**
