### PR TITLE
Update CategorySetup.php

### LINKED ISSUE #33142: [Issue] Update CategorySetup.php
This issue is automatically created based on existing pull request: magento/magento2#33126: Update CategorySetup.php

---------
landing_page attribute is used under Admin Panel: Catalog->Categories->Content section with a purpose to add cms block in Categories. So here I am changing Attribute Group to Content from Display Settings.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by manavluhar**
We are having One Dropdown Field at `Admin-Panel=>Catalaog=>Categories=>Category Form Page=>Content Section` Location To **add CMS Block**. 
Category_Form

The Name of  attribute which is connected with this field is **landing_page**.  As this Attribute is used to add **Content**(_CMS Block_), It should be considered inside **content** group and Its group name should **Content** Instead of **Display Settings** .

Landing_Page_Attribute

As **landing_page** attribute should be considered under  **content** group, I am creating a new group, Assigning **content** as a group ID, updating **landing_page** attribute's group, and Giving correct short-order by changing values of `sort` for needed attributes.

Data_Patch_Installation

After changes, it will be easy to identify the **group** and **Content Section**(_where it will be shown at Admin-Panel_) by just checking the code related to **landing_page** While working on it or on Its related development.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#33142: Update CategorySetup.php

### CODE REVIEW

**Comment by manavluhar** [comment]
Signed Adobe CLA

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento give me test instance

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by manavluhar** [comment]
I updated the comment @gabrieldagama

**Comment by Den4ik** [comment]
Changes from PR affect new M2 installation. What about exists stores?
In my opinion changes should be made as new patches.

@ihor-sviziev @gabrieldagama What do you think?

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run all tests

**Pull request closed without merging**
