### PR TITLE
[Backport] Add missing short description on MoveToWishlist

### PR DESCRIPTION
**Pull request by mage2pratik**
### Original Pull Request 
 https://github.com/magento/magento2/pull/21249
### Description (*)
Add missing short description on class MoveToWishlist to match PSR standards

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by swnsma** [comment]
Hi @mage2pratik,
Thank you for your contribution!
Unfortunately, I can not accept this pull request because we no longer support pull requests with cleanup into 2.2-develop branch.
You can find more info by visiting this [link.](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules)

**Comment by mage2pratik** [comment]
Hi @swnsma,
I didn't see any cleanup tag in "Original Pull Request" #21249.

**Comment by swnsma** [comment]
Hi @mage2pratik,
The PR #21249 has been marked as 'Merged' because all commits from this PR were merged inside other PR #21260.
As result, PR #21249 was never being processed and "merged" automatically.

**Pull request closed without merging**
