### PR TITLE
Code reduced in functions.php

### PR DESCRIPTION
**Pull request by joelbladt**
### Description (*)
The if construct is unnecessary. You can solve it with a short-if construct.

### Contribution checklist (*)
 - [ x ] Pull request has a meaningful description of its purpose
 - [ x ] All commits are accompanied by meaningful commit messages
 - [ x ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ x ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by joelbladt** [comment]
@magento give me test instance

**Comment by joelbladt** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @joelbladt. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @joelbladt. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @joelbladt, here is your [new Magento instance](https://pr-25397.instances.magento-community.engineering).
Admin access: [https://pr-25397.instances.magento-community.engineering/admin](https://pr-25397.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rodrigowebjump** [comment]
Hi @joelbladt 
Thanks for your submission.
Unfortunately, we could not accept this change because in this case, it reduces code readability.

Thanks

**Pull request closed without merging**
