### PR TITLE
Resolve API create /V1/products/attribute-sets/groups ("sort_order" and "attribute_group_code") not changing.

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

magento/magento2#23634: Resolve API create /V1/products/attribute-sets/groups two fields (sort_order and "attribute_group_code" field) not changing in the DataBase. **Remember check in the Database, because the API always return the "sort_order" and "attribute_group_code" which is sent in the body parameter of request.**

Solution: The reason is in the save() function, it doesn't get the value in the extension_attributes. To fix it, in the save() function of repository, we need to get the value in the extension_attributes and add them to the model.

### Fixed Issues (if relevant)

1. magento/magento2#23634: Eav Group Repository Order not changing.

### Manual testing scenarios (*)

Call the API:
Method: POST
http://[magento2 domain]/rest/default/V1/integration/admin/token
`{"username":"admin","password":"123123q"}`

The result is the [TOKEN]

Method: POST
http://[magento 2 domain]/rest/default/V1/products/attribute-sets/groups
Authorization: Bearer [TOKEN]
```
{
  "group": {
    "attribute_group_name": "Product Details",
    "attribute_set_id": "3",
    "extension_attributes": {
      "attribute_group_code": "details-test",
      "sort_order": "50"
    }
  }
}
```

Check in the Database, the last record in the table "eav_attribute_group". The attribute_group_code : "details-test" and "sort_order": "50" are saved correctly.

 **Remember check in the Database, because the API always return the "sort_order" and "attribute_group_code" which is sent in the body parameter of request.**

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-23690.instances.magento-community.engineering).
Admin access: [https://pr-23690.instances.magento-community.engineering/admin](https://pr-23690.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by edenduong** [comment]
Hi @orlangur : Could you please review my pull request?

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-5618](https://jira.corp.magento.com/browse/ENGCOM-5618) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

screen

**Before:**
before

**After:**
after

**Pull request merged**
