### PR TITLE
Fix for making subcategories appear in breadcrumbs

### PR DESCRIPTION
**Pull request by Yamaha32088**
### Description (*)
The typo will break sub categories from appearing in the breadcrumbs

### Fixed Issues (if relevant)

1. magento/magento2#7967: Problems with breadcrumbs

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Yamaha32088. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
Hi @Yamaha32088 , thanks for the contribution! Can you please update the https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Catalog/Test/Unit/ViewModel/Product/BreadcrumbsTest.php

**Comment by Yamaha32088** [comment]
@sivaschenko done. Thanks for catching that

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3698](https://jira.corp.magento.com/browse/ENGCOM-3698) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @Yamaha32088 we cannot reproduce the issue on 2.3-develop. We used the following manual testing scenario:

- Create nesting category: Default Category->A1->A2->A3->A4->A5
- Create product and assign to category A5.
- Go to product detail page

Actual Result: Breadcrumbs contain categories

Are there any details that we missed while verification of the issue?

**Comment by Yamaha32088** [comment]
Hello @sivaschenko that appears to be the correct steps. Did you make sure that it wasn't using the fallback option of the "HTTP Referrer"? I found the bug on a site that was migrated from Magento 1.x to 2.x, although I don't suspect that would cause any differences on how products are linked to categories. I just know that it is definitely a typo and there were no sub-categories appearing for me until I fixed it.

**Comment by magento-engcom-team** [comment]
Hi @Yamaha32088. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
