### PR TITLE
Fetch first available store if default is not

### LINKED ISSUE #36434: Admin user can't login as customer if a GWS scope not including the default store is set on their role
### Preconditions and environment

- Adobe Commerce : 2.4.4
- Commerce only, is this the right place to report commerce bugs?
- Working on 2.4.3

### Steps to reproduce

1. Have a magento commerce 2.4.4 setup with the module admin-gws enabled
2. Create a secondary website, store and store view (all linked to each other)
3. Create a user role with only the second website scope, not the default one
4. Create an admin user and assign them this role
5. Log in to this admin user account
6. Find some frontend customer belonging to any scope (even the admin user one) and add them to the login_as_customer_assistance_allowed table
7. Try to login as this customer with the admin user 

### Expected result

Admin user can log in as customers belonging to their scope

### Actual result

Error pops up "an has occured during application run"

image

### Additional information

Tested on a 2.4.3, works as expected.
While debugging, I found that the error occurs when trying to get the default store view in the LAC feature, 
vendor/magento/module-login-as-customer-admin-ui/Controller/Adminhtml/Login/Login.php->getLoginProceedRedirectUrl().
The admin-gws module adds a plugin on the store collection (vendor/magento/module-admin-gws/Plugin/CollectionFilter.php) that adds a filter to the stores collection, that prevents returning stores that do not belong in the current admin user scope. Which means that sometimes, storeManager->getDefaultStoreView() can return NULL, a behavior thats is not taken into account by the LAC module. 

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by thomas-kl1**
### Description (*)

With GWS module, defaultStoreView might return null. So we need to fetch an other store if null.

### Fixed Issues (if relevant)

1. Fixes [magento/magento2#36434](https://github.com/magento/magento2/issues/36434)

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by thomas-kl1** [comment]
@magento run all tests

**Comment by thomas-kl1** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
We are closing this PR as per this https://github.com/magento/magento2/issues/36434#issuecomment-1330665912

**Comment by thomas-kl1** [comment]
@engcom-November please?

**Comment by thomas-kl1** [comment]
Also the changes here are aligned with other Magento 2 core modules. So it make sens to apply sames changes here, please reopen.

**Comment by engcom-November** [comment]
Hi @thomas-kl1 ,
I re-verified the issue again on latest Magento 2.4-develop instance with enterprise edition but the issue is still not reproducible with below steps performed:
**Steps performed:**

 1.    Enabled Login as customer from admin - Stores - Configuration - Customers - Login as Customer
  2.  Created 2nd website, store and store view as per Magento [devdocs](https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/multi-sites/ms-admin.html?lang=en)
  3.  Created Customers from front end both the websites (Main website and 2nd website)
  4. Created Admin user role - assigned to only 2nd store scope
   5. Created new Admin user with only new user role assigned to this admin user
   6. Login to admin using new admin user
   7. Customers - All Customers - Only customers created on 2nd store are displayed to the user
   8. Open/edit the customer for which login as customer is enabled already - Click on Login as Customer
    No issue: User is logged as customer
  9.  Open other customer for which login as customer is not enabled. - Enable login as customer from account information page and save
  10.  Click on Login as Customer - No issue. User is logged as customer
image
image
image

**Pull request closed without merging**
