### PR TITLE
Issue 35981: Cart Rule with product qty requirement does work

### LINKED ISSUE #35981: Cart Rule with product qty requirement does work on Magento 2.4.3 + Graphql
### Preconditions and environment

- Magento version 2.4.3
- GraphQl Usage

### Steps to reproduce

1. Add Cart Rule:
Zrzut ekranu z 2022-08-19 13-32-53
2. Add Qty 2 or more of product to cart.
3. Check cart prices.

### Expected result

Rule where product qty should be equals 1 , should not be applied for higher product qty.

### Actual result

Discount will be applied.

### Additional information

Magento will create 2 entities on add to cart, simple and configurable in quote_item table.

magento/module-sales-rule/Model/Rule/Condition/Product/Combine.php 
function retrieveValidateEntities, has such code:
`else {
    $validateEntities = $entity->getChildren() ?: [];
    $validateEntities[] = $entity;
}`

It causes to create $validateEntities, which where node [0] has simple with qty 1, and use for validation instead of using $entity qty which should be 2 or higher. 

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rogerdz**
### Description (*)

Change attribute_scope for quote_item_qty condition to parent

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35981

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Review by edenduong — CHANGES_REQUESTED** [review]
Thank you for your contribution
Could you please cover your change by automation test ? I think it can covered by Unit Test.

**Comment by rogerdz** [comment]
@edenduong Thank you for your review, I added unit test to new commit.

**Comment by rogerdz** [comment]
@magento run all tests

**Review by edenduong — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento give me test instance

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B F

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B

**Pull request merged**
