### PR TITLE
Add tip for upper limit of the Email Text Length Limit field range

### PR DESCRIPTION
**Pull request by TomashKhamlai**
### Description (*)

Tiny improvement.
image

### Fixed Issues (if relevant)

1. None.

### Manual testing scenarios (*)

1. Review tests. Manual checking is not required

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by TomashKhamlai** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by TomashKhamlai** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai, here is your [Magento instance](https://i-24253-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24253-2-3-develop.instances.magento-community.engineering/admin](https://i-24253-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai, here is your [new Magento instance](https://pr-24253.instances.magento-community.engineering).
Admin access: [https://pr-24253.instances.magento-community.engineering/admin](https://pr-24253.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5687](https://jira.corp.magento.com/browse/ENGCOM-5687) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
