### PR TITLE
2.3.7 release - https://github.com/magento/magento2/pull/34514

### PR DESCRIPTION
**Pull request by kanhaiya5590**
https://github.com/magento/magento2/pull/34514

### Fixed Issues (if relevant)

1. Fixes magento/magento2 https://github.com/magento/magento2/issues/34415
2. Issue existing in Magento 2.3.7-p2

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by kanhaiya5590** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run all tests

**Comment by kanhaiya5590** [comment]
@magento run Static Tests

**Comment by kanhaiya5590** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by sidolov** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by sidolov** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by kanhaiya5590** [comment]
Hi Team,

Can any one please help to fix **Functional Tests EE**

**Comment by ishakhsuvarov** [comment]
Hi @kanhaiya5590 

Unfortunately we are unable to accept Pull requests to any branches or releases other than current `2.4-develop` therefore I have to close this PR now.

Please feel free to reopen same PR into current branch if you think that issue persists.

Thanks.

**Pull request closed without merging**
