### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by wa-daniel-fahl**
Fix typo in checkRequiredFields method

### Description (*)
Fixed a typo in the private method "checkRequiredFields"

### Contribution checklist (*)
 - [ x ] Pull request has a meaningful description of its purpose
 - [ x ] All commits are accompanied by meaningful commit messages
 - [  ] All new or changed code is covered with unit/integration tests (if applicable)
 - [  ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24709) <br/>All committers have signed the CLA.

**Review by VladimirZaets — APPROVED** [review]

**Review by slavvka — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
@wa-daniel-fahl thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@engcom-Foxtrot please take a look at Functional Ce and EE tests

**Comment by VladimirZaets** [comment]
Hi @wa-daniel-fahl. Thanks for collaboration. It is already fixed in 5aa774b18c82fc7af5610bb1fd470cb6ac064766

**Pull request closed without merging**
