### PR TITLE
Updated colinmollenhour/php-redis-session-abstract to PHP 8 Compatible version

### LINKED ISSUE #32709: Update colinmollenhour/php-redis-session-abstract to PHP 8 Compatible version
Update colinmollenhour/php-redis-session-abstract to PHP 8 Compatible version (1.4.4)

### PR DESCRIPTION
**Pull request by sivaschenko**
### Description (*)
Updated colinmollenhour/php-redis-session-abstract to PHP 8 Compatible version (1.4.4)

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/533

### Fixed Issues (if relevant)
Fixes https://github.com/magento/magento2/issues/32709

### Manual testing scenarios (*)
No manual testing required

### CODE REVIEW

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento import pr to magento-commerce/magento-engcom

**Comment by magento-engcom-team** [comment]
@sivaschenko, an error occurred during the Pull Request import.

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes from this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8997](https://jira.corp.magento.com/browse/ENGCOM-8997) has been created to process this Pull Request

**Pull request merged**
