### PR TITLE
Fix for Issue #4468 "Unable to insert multiple catalog product list widgets (with pager) in CMS page"

### PR DESCRIPTION
**Pull request by vasilii-b**
### Description (*)
This PR aims to solve issue reported in #4468.

### Fixed Issues (if relevant)
1. magento/magento2#4468: Unable to insert multiple catalog product list widgets in CMS page

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by vasilii-b** [comment]
Hi @rogyar,
I have had a look on the failed unit test and gave it a try on the local as well. The results differ for some reason.

<details>
<summary>Test results</summary>

**Travis**

image

**Local**

image
</details>
<br/>
Can you please advice ?
Thank you!

**Comment by rogyar** [comment]
Hi @vasilii-b. That might be a case when a timestamp is used during the tests and the issue is just a matter of milliseconds/seconds. I will run the tests once again

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18714-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18714-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18714-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-18714/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-18714//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-18714//admin)
Login: `admin` Password: `123123q`

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
