### PR TITLE
[Catalog|Sales] Fix wrong behavior of grid row click event

### PR DESCRIPTION
**Pull request by Den4ik**
### Description (*)

Fixed issue related with grid row click event when impossible to select input field value and checkbox in grid row

### Fixed Issues (if relevant)

1. magento/magento2#22988: Wrong behavior of grid row and checkbox click

### Manual testing scenarios (*)

1. Go to Catalog->Categories page
2. Open Products in Category fieldset
3. Try to select value in position field with mousup not above input field
Same steps for admin order create page with Assign products

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Den4ik** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [Magento instance](https://i-22990-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22990-2-3-develop.instances.magento-community.engineering/admin](https://i-22990-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Den4ik** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Den4ik. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, here is your [new Magento instance](https://pr-22990.instances.magento-community.engineering).
Admin access: [https://pr-22990.instances.magento-community.engineering/admin](https://pr-22990.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by Den4ik** [comment]
@VladimirZaets Any updates with PR?

**Comment by Den4ik** [comment]
@VladimirZaets Any progress?

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-6007](https://jira.corp.magento.com/browse/ENGCOM-6007) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by sidolov** [comment]
@magento run Static Tests build

**Comment by engcom-Foxtrot** [comment]
@Den4ik can you please fix static test failures?

**Comment by VladimirZaets** [comment]
@magento run Static Tests build

**Comment by Den4ik** [comment]
@magento run Adobe CLA Signed?

**Comment by Den4ik** [comment]
> @Den4ik can you please fix static test failures?

@engcom-Foxtrot  Working on it

**Comment by VladimirZaets** [comment]
Hi @Den4ik. Please merge latest mainline to your branch

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6007](https://jira.corp.magento.com/browse/ENGCOM-6007) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Review by krzksz — APPROVED** [review]

**Comment by slavvka** [comment]
Guys, thank you for patience. This PR is delivery queue

**Comment by slavvka** [comment]
@magento run all tests

**Pull request merged**
