### PR TITLE
MC-40850: Not able to save downloadable product with sample link after creating a future staging update with end date from the Downloadable Product page

### PR DESCRIPTION
**Pull request by SmVladyslav**
### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/489

### Fixed Issues (if relevant)

1. Fixes magento/partners-magento2ee#488

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by SmVladyslav** [comment]
@magento run all tests

**Comment by SmVladyslav** [comment]
@magento run Functional Tests EE

**Comment by SmVladyslav** [comment]
@magento run Functional Tests EE

**Review by zakdma — APPROVED** [review]

**Comment by SmVladyslav** [comment]
@magento run all tests

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-32136`.

**Comment by engcom-Oscar** [comment]
:heavy_check_mark: QA passed

Was checked case from Manual testing scenarios 

:x: **Before:**

Unable to save the product, and see the message, 'The downloadable sample isn't related to the product. Verify the link and try again.'

:heavy_check_mark: **After:**

Able to save the product, and see the message 'You saved the product.'

Screenshot from 2021-02-17 14-41-33

**Pull request merged**
