### PR TITLE
UPS Shipment Tracking: Show "Delivered On" only when package has actually been delivered

### LINKED ISSUE #29659: [Issue] UPS Shipment Tracking: Show "Delivered On" only when package has actually been delivered
This issue is automatically created based on existing pull request: magento/magento2#29080: UPS Shipment Tracking: Show "Delivered On" only when package has actually been delivered

---------

### Summary (*)

Magento 2.4-develop
The UPS Tracking API returns the activity status code "D" for delivered packages. The delivery properties of the tracking object should only be set if we see this status code. Otherwise packages that are still in transit show as delivered, incorrectly.

Consider the following extract of a UPS tracking API response:

```xml
...
    <Package>
      <TrackingNumber>*REMOVED*</TrackingNumber>
      <DeliveryIndicator>N</DeliveryIndicator>
      <Activity>
        <ActivityLocation>
          <Address>
            <City>Secaucus</City>
            <StateProvinceCode>NJ</StateProvinceCode>
            <CountryCode>US</CountryCode>
          </Address>
        </ActivityLocation>
        <Status>
          <StatusType>
            <Code>I</Code>
            <Description>Departed from Facility</Description>
          </StatusType>
          <StatusCode>
            <Code>DP</Code>
          </StatusCode>
        </Status>
        <Date>20200711</Date>
        <Time>034100</Time>
        <GMTDate>2020-07-11</GMTDate>
        <GMTTime>07:41:00</GMTTime>
        <GMTOffset>-04:00</GMTOffset>
        <NextScheduleActivity>
          <Date>2020-07-15</Date>
          <Time>235900</Time>
        </NextScheduleActivity>
      </Activity>
      <Activity>
        <ActivityLocation>
          <Address>
            <City>New York</City>
            <StateProvinceCode>NY</StateProvinceCode>
            <CountryCode>US</CountryCode>
          </Address>
        </ActivityLocation>
        <Status>
          <StatusType>
            <Code>I</Code>
            <Description>Origin Scan</Description>
          </StatusType>
          <StatusCode>
            <Code>OR</Code>
          </StatusCode>
        </Status>
        <Date>20200710</Date>
        <Time>202339</Time>
        <GMTDate>2020-07-11</GMTDate>
        <GMTTime>00:23:39</GMTTime>
        <GMTOffset>-04:00</GMTOffset>
      </Activity>
...
```

In this case, the package is still in transit. However, because the check for the `DeliveryStatus` is missing, the package would incorrectly show as delivered in Magento, and display the date/time of the first activity as _Delivered On_.

### Examples (*)

You will need a valid UPS tracking number and UPS API keys to test this.

### PR DESCRIPTION
**Pull request by danbtl**
### Description (*)

The UPS Tracking API returns the activity status code "D" for delivered packages. The delivery properties of the tracking object should only be set if we see this status code. Otherwise packages that are still in transit show as delivered, incorrectly.

Consider the following extract of a UPS tracking API response:

```xml
...
    <Package>
      <TrackingNumber>*REMOVED*</TrackingNumber>
      <DeliveryIndicator>N</DeliveryIndicator>
      <Activity>
        <ActivityLocation>
          <Address>
            <City>Secaucus</City>
            <StateProvinceCode>NJ</StateProvinceCode>
            <CountryCode>US</CountryCode>
          </Address>
        </ActivityLocation>
        <Status>
          <StatusType>
            <Code>I</Code>
            <Description>Departed from Facility</Description>
          </StatusType>
          <StatusCode>
            <Code>DP</Code>
          </StatusCode>
        </Status>
        <Date>20200711</Date>
        <Time>034100</Time>
        <GMTDate>2020-07-11</GMTDate>
        <GMTTime>07:41:00</GMTTime>
        <GMTOffset>-04:00</GMTOffset>
        <NextScheduleActivity>
          <Date>2020-07-15</Date>
          <Time>235900</Time>
        </NextScheduleActivity>
      </Activity>
      <Activity>
        <ActivityLocation>
          <Address>
            <City>New York</City>
            <StateProvinceCode>NY</StateProvinceCode>
            <CountryCode>US</CountryCode>
          </Address>
        </ActivityLocation>
        <Status>
          <StatusType>
            <Code>I</Code>
            <Description>Origin Scan</Description>
          </StatusType>
          <StatusCode>
            <Code>OR</Code>
          </StatusCode>
        </Status>
        <Date>20200710</Date>
        <Time>202339</Time>
        <GMTDate>2020-07-11</GMTDate>
        <GMTTime>00:23:39</GMTTime>
        <GMTOffset>-04:00</GMTOffset>
      </Activity>
...
```

In this case, the package is still in transit. However, because the check for the `DeliveryStatus` is missing, the package would incorrectly show as delivered in Magento, and display the date/time of the first activity as _Delivered On_.

### Related Pull Requests

None

### Fixed Issues (if relevant)

Couldn't find any open issues related to this.

### Manual testing scenarios (*)

You will need a valid UPS tracking number and UPS API keys to test this.

### Questions or comments

Let me know if you need samples of the UPS tracking API response.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [X] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29659: UPS Shipment Tracking: Show "Delivered On" only when package has actually been delivered

### CODE REVIEW

**Comment by danbtl** [comment]
@magento run all tests

**Comment by danbtl** [comment]
@magento run all tests

**Comment by danbtl** [comment]
@joni-jones Could you please have a look at this PR? Let me know if you need additional information.

**Comment by joni-jones** [comment]
Hi @danbtl, thanks for pointing your attention to this issue. I'm not sure how familiar you are with tracking functionality, so let me provide some context. The idea, that a customer or merchant can see all package transition history for a specific shipment, basically the same what almost all carriers provide - when a package left a shipping facility, current transit destination, delivery status, etc. So not only when a package was delivered.

The current logic is the following, the latest (XML nodes follow from latest to earlier update order) tracking information will be represented as shipment status and previous - as shipment activities. For instance, if a package in transit then the status will be `In Transit`, and activities like `Label Created`, `Shipped`, `Out for Delivery`, etc - will be represented as activities.

The proposed changes will break this logic because if the latest status is not `Delivered` then we will just lose the information about the current status.

> However, because the check for the DeliveryStatus is missing, the package would incorrectly show as delivered in Magento, and display the date/time of the first activity as Delivered On.

I think the problem, not in the logic for UPS carrier itself but in the label for status https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Shipping/Block/DataProviders/Tracking/DeliveryDateTitle.php#L25. The label says `Delivered On` but it should be something like `Current Status` or `Status Updated`.

**Comment by danbtl** [comment]
Hi @joni-jones, thank you for reviewing this issue. I spent some time to look into this a bit further.

You're right, my proposed patch will hide the "Delivered on" row for packages that are still in transit. Like you mentioned, the real problem is that the label "Delivered On" is incorrect, and it should really say "Status on" or something similar (at least while the package is still in transit).

The FedEx provider contains a plugin that changes this label: https://github.com/magento/magento2/blob/b4770e47dcaa0ba7aa3c802eceda0317cfe401dc/app/code/Magento/Fedex/Plugin/Block/DataProviders/Tracking/ChangeTitle.php#L27-L33

I could add a similar plugin to the UPS module that simply changes the label using the same `afterGetTitle` mechanism. What do you think?

**Comment by sidolov** [comment]
@magento create issue

**Comment by danbtl** [comment]
@joni-jones I updated the PR. I added a plugin to change the _Delivered On_ title to _Status Updated On_ for the UPS carrier. This is using the same plugin mechanism that is used by the FedEx module.
Let me know your thoughts.

**Review by VladimirZaets — APPROVED** [review]

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-8045](https://jira.corp.magento.com/browse/ENGCOM-8045) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@danbtl thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by danbtl** [comment]
@VladimirZaets Thank you for reviewing this. This is my first Magento PR. Is there anything else I should do to get this merged?

**Comment by cherryz23** [comment]
Could you give me a call?

Sent from my Apple Watch

**Comment by engcom-Delta** [comment]
@magento give me test instance

**Comment by engcom-Delta** [comment]
@magento give me test instance

**Comment by engcom-Delta** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Result:**
:x: **Before:**
#29080Main

:heavy_check_mark: **After:**
ShippingTrack

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Pull request merged**
