### PR TITLE
Issue #36582 - Unable to create new customer address on specific website

### LINKED ISSUE #36582: Unable to Create New Address: The website with id 3 that was requested wasn't found. Verify the website and try again.
### Preconditions and environment

- PHP 8.1
- MySQL V8
- Magento 2.4.4-2.4.5

### Steps to reproduce

1. Create new Store View
    - Store: Main Website Store
    - Name: ….. (Anything)
    - Code: ….. (Anything)
    - Status: Enabled
    - Sort Order: ….. (Any Number)
2. Create New Website
3. Create New Store, Assign this new store to previous created website.
4. Create New Store View, Assign this new store view to previous created store.
5. Under Stores > Settings > Configuration > Customer > Customer Configuration > Account Sharing Options > Share Customer Accounts, set this to Global.
6. Save configuration.
7. Add new customer, and assign the customer to New Website and select other Store View which is not related to current website.
Screenshot 2022-12-08 at 4 46 09 PM

8. Edit that created customer.
9. Go to Addresses (left sidebar).
10. Click Add New Address.

### Expected result

- Showing add new Address form

### Actual result

- Showing pop-up message `Something went wrong.`

Screenshot 2022-12-08 at 13 00 27

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by fiko**
### Description (*)

Fixing reported issue of unable to create new customer address from admin panel when that customer is created for another website which the store id is not match with the website id.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36582

### Manual testing scenarios (*)

1. Create new Store View
    - Store: Main Website Store
    - Name: ….. (Anything)
    - Code: ….. (Anything)
    - Status: Enabled
    - Sort Order: ….. (Any Number)
2. Create New Website
3. Create New Store, Assign this new store to previous created website.
4. Create New Store View, Assign this new store view to previous created store.
5. Under Stores > Settings > Configuration > Customer > Customer Configuration > Account Sharing Options > Share Customer Accounts, set this to Global.
6. Save configuration.
7. Add new customer, and assign the customer to New Website.
8. Edit that created customer.
9. Go to Addresses (left sidebar).
10. Click Add New Address.

image

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by fiko** [comment]
@magento run all tests

**Comment by fiko** [comment]
@magento run Integration Tests

**Comment by fiko** [comment]
https://github.com/magento run Integration Tests

**Comment by fiko** [comment]
@magento run Unit Tests, Functional Tests B2B, Functional Tests EE, Functional Tests CE, Database Compare

**Comment by fiko** [comment]
@magento run Magento Health Index, Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE, Semantic Version Checker, Static Tests, WebAPI Tests

**Comment by fiko** [comment]
@magento run WebAPI Tests

**Comment by fiko** [comment]
@magento run Functional Tests CE

**Comment by fiko** [comment]
@magento run Functional Tests B2B

**Comment by swnsma** [comment]
@magneto run all tests

**Comment by swnsma** [comment]
@magneto run all tests

**Comment by swnsma** [comment]
@magento run all tests

**Comment by swnsma** [comment]
@magento run all tests

**Review by swnsma — APPROVED** [review]

**Comment by swnsma** [comment]
@magento run tests Functional Tests B2B

**Comment by fiko** [comment]
@magento run Functional Tests B2B

**Comment by hostep** [comment]
Looks like there is a [competing PR over here](https://github.com/magento/magento2/pull/36583), only one of both should be handled. I don't really care which one, because they are 100% the same.

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

1. Login as admin.
2. Create new Store View
3. Create New Website
4. Create New Store, Assign this new store to previous created website.
5. Create New Store View, Assign this new store view to previous created store.
6. Under Stores > Settings > Configuration > Customer > Customer Configuration > Account Sharing Options > Share Customer Accounts, set this to Global.
7. Save configuration.
8. Add new customer, and assign the customer to New Website and select other Store View which is not related to current website.
9. Edit that created customer. 
10. Go to Addresses (left sidebar). 
11. Click Add New Address.

**Before:** :heavy_multiplication_x: Getting error while clicking on "Add New Address"
Screenshot 2023-02-16 at 1 32 12 PM


**After:** :heavy_check_mark:  Now able to add address.
Screenshot 2023-02-16 at 1 42 14 PM

**Additionally tested:**

1. Login to FE.
2. Added product to cart.
3. Placed an order

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by engcom-Delta** [comment]
Functional Tests B2B failure is not happening due to PR Changes hence move it to Merge in Progres.

Thanks.

**Comment by simonmaass** [comment]
this is still happening in 2.4.6-p1.... when will this be fixed?

**Comment by ageffray** [comment]
Up ! When does this HUGE bug will be fixed ??? I can't understand how it's possible to let this kind of bug... Especially when issue is created since almost a year...

**Comment by hostep** [comment]
The PR is included in Magento 2.4.7 which will be released soon ([9 April](https://experienceleague.adobe.com/en/docs/commerce-operations/release/planning/schedule)), Magento only puts out one release per year, so it takes some time for fixes to become released unfortunately.
If you want a quicker fix, look into a way to patch the changes from this PR into your installation.

**Pull request merged**
