### PR TITLE
New file AddDataForCostaRica.php

### LINKED ISSUE #37382: [Issue] New file AddDataForCostaRica.php
This issue is automatically created based on existing pull request: magento/magento2#33189: New file AddDataForCostaRica.php

---------
Add Costa Rica states data.
@magento run all tests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37375: New file AddDataForCostaRica.php

### PR DESCRIPTION
**Pull request by p3ll3**
Add Costa Rica states data.
@magento run all tests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37382: New file AddDataForCostaRica.php

### CODE REVIEW

**Review by danielrussob — CHANGES_REQUESTED** [review]
Hello @p3ll3 ,
thank you for your contribution, could you add

implements \Magento\Framework\Setup\Patch\PatchVersionInterface

and relative getVersion() ?

**Comment by danielrussob** [comment]
@magento run all tests

**Comment by p3ll3** [comment]
Hi @danielrussob, I just added the updates you were asking for, let me know if you need anything else.

**Comment by engcom-Charlie** [comment]
Hi @p3ll3,

Thanks for your contribution!

It seems that as per your [comment](https://github.com/magento/magento2/pull/33189#issuecomment-903931845), you have implemented the review changes so moving it for review.

Thank You!

**Review by fredden — APPROVED** [review]

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

1. Verify CostRica states are displayed in the store front >> Multi-shipping,via normal order, customer address creation(Address Book).
2. Verify in admin panel -> Customer creation page, creating order from admin panel by creating new customer

**Before:** :heavy_multiplication_x: States were not displaying of CostRica.
**Admin Panel:**
Screenshot 2023-04-17 at 11 59 09 AM

**Store front:**
Screenshot 2023-04-17 at 11 58 14 AM




**After:** :heavy_check_mark:  Now it is displaying.
Screenshot 2023-04-17 at 12 00 04 PM

Screenshot 2023-04-17 at 12 29 26 PM

Screenshot 2023-04-17 at 12 19 24 PM


Builds are failed. Hence, moving this to Extended Testing.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Integration Tests,Database Compare

**Pull request merged**
