### PR TITLE
ASI: Fix observers

### PR DESCRIPTION
**Pull request by VladimirZaets**
### Description (*)
Parsing all store views for used images while saving a product/categroy

### Related Pull Requests
https://github.com/magento/adobe-stock-integration/pull/1251
https://github.com/magento/partners-magento2ee/pull/236
https://github.com/magento/partners-magento2-infrastructure/pull/1

### Fixed Issues (if relevant)
1. https://github.com/magento/adobe-stock-integration/issues/1278: Saving the product or category in a specific store view overwrites used in info for other scopes

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by VladimirZaets** [comment]
Regarding dependencies on the EAV module. We use methods of abstract class from the EAV module, according to it dependencies on the EAV module is required.

**Comment by naydav** [comment]
> Regarding dependencies on the EAV module. We use methods of abstract class from the EAV module, according to it dependencies on the EAV module is required.

In this case, we have no choice (only global refactoring). The interfaces from `Catalog` don't provide the needed level of abstraction.  

We have the same situation with `CatalogSearch` module.
https://github.com/magento/magento2/blob/392b34fc8ef5379772ffd3c4fedd25b81fa3cb17/app/code/Magento/CatalogSearch/composer.json#L16

**Comment by lenaorobei** [comment]
PAT: https://bamboo.corp.magento.com/browse/MCCE24-MCCE24446/latest

**Comment by sivaschenko** [comment]
https://m2build-comm-2.devops.magento.com/job/MTS-API-Tests/9947/

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-7492](https://jira.corp.magento.com/browse/ENGCOM-7492) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
https://m2build.devops.magento.com/job/Existing-PR-Tests/26372/

**Review by sivaschenko — APPROVED** [review]

**Review by Nazar65 — CHANGES_REQUESTED** [review]
:x:  QA failed for Scheduled Changes 
Scenario 
1. Create Two store views
2. Create product with default images on all store views for example for default store view image1.jpg
3. Set different image for second store view by click on New Scheduled Update
4. Select second store view, select different image like image2.jpg
5. Click save.

**Expected result:**

image1.jpg is Used In 1 Product
image2.jpg is Used in 1 Product

**Actual Result:**
Default store-view image is duplicated on save schedule Update action

image1.jpg is Used in 2 Product
image2.jpg is Used In 1 Product

**Comment by VladimirZaets** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-7492](https://jira.corp.magento.com/browse/ENGCOM-7492) has been created to process this Pull Request

**Comment by Nazar65** [comment]
:heavy_check_mark: QA Passed

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
@magento run all tests

**Pull request merged**
