### PR TITLE
Configurable Product Links Validation Bug when int value is 0

### LINKED ISSUE #13210: Configurable Product Links Validation Bug when int value is 0
### Preconditions
1. Magento 2.4-develop
2. Attribute with Source Model having 0 as one value
3. Create a simple Product with attribute value 0 selected

### Steps to reproduce

1. Create configurable containing the simple product via REST Api

### Expected result

1. Configurable Product is created with the linked simple product

### Actual result

1. Exception thrown: Product with id \"%1\" does not contain required attribute \"%2\"."

The validation of the product links attributes from the configurable-product module is not type-safe which leads to a validation error when the value is (int)0
See: https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php#L103

### PR DESCRIPTION
**Pull request by engcom-Charlie**
### Description (*)

Fixed and covered by test

### Fixed Issues (if relevant)

1. Fixes magento/magento2#13210

### Manual testing scenarios (*)

See #13210

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @engcom-Charlie, could you please review the failing WebAPI Test?
Thank you for your contribution.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by eduard13 — APPROVED** [review]
Good job 👍 
Looks like the failing test isn't related with the current changes.

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-7787](https://jira.corp.magento.com/browse/ENGCOM-7787) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

Tested according to the steps, described in [comment ](https://github.com/magento/magento2/issues/13210#issuecomment-359773155)

**Manual testing scenario:**

1. Created a simple Product with Value Zero for "New Attribute";

Screenshot from 2020-07-08 17-27-38

2. Try to create a new configurable product for the simple via Rest API:
**POST** `/V1/products`

Screenshot from 2020-07-08 16-22-41

**Before:** :heavy_multiplication_x: Exception thrown: Product with id "%1" does not contain required attribute "%2"."

Screenshot from 2020-07-08 16-22-49

**After:** :heavy_check_mark: Configurable Product was created with the linked simple product

Screenshot from 2020-07-08 18-13-42
Screenshot from 2020-07-08 18-14-39

**Pull request merged**
