### PR TITLE
Resolve "Layered Navigation Price Step" in Category Form display wrong currency issue25970

### LINKED ISSUE #25970: "Layered Navigation Price Step" in Category Form display wrong currency
### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Go to backend
2. Set default currency to Euro

image

3. Go to Catalog->Categories
4. Edit one category, scroll to Display Settings 
5. See:

image

### Expected result (*)

1. It must display as Euro

### Actual result (*)

1. Dollar because it is hard-code :

image

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#25970 #21684: "Layered Navigation Price Step" in Category Form display wrong currency

### Fixed Issues (if relevant)

1. magento/magento2#25970: "Layered Navigation Price Step" in Category Form display wrong currency
2. magento/magento2#21684: Currency sign for "Layered Navigation Price Step" is not according to default settings

### Manual testing scenarios (*)

1. Go to backend
2. Set default currency to Euro

image

3. Go to Catalog->Categories
4. Edit one category, scroll to Display Settings 
5. See:

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by dmytro-ch** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-25971.instances.magento-community.engineering).
Admin access: [https://pr-25971.instances.magento-community.engineering/admin](https://pr-25971.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6451](https://jira.corp.magento.com/browse/ENGCOM-6451) has been created to process this Pull Request

**Comment by dmytro-ch** [comment]
@edenduong, thank you for the MFTF test. Well done!

**Comment by engcom-Alfa** [comment]
Hi @edenduong 
This issues ([#25970 ](https://github.com/magento/magento2/issues/25970), [#21684](https://github.com/magento/magento2/issues/21684)) were already fixed by PR #24815.

**Actual Result:**
before

 So, we have to close it.
@edenduong Thank you for your contribution!

**Pull request closed without merging**
