### PR TITLE
[MQP] Implement Tax Rate Mass Delete feature

### PR DESCRIPTION
**Pull request by Den4ik**
MQP port for #33484 to 2.4.3

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33399

### Manual testing scenarios (*)

See #33484

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Static Tests

**Comment by sidolov** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
magento run all tests

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
Hi @Den4ik 

Unfortunately we are unable to accept Pull requests to any branches or releases other than current `2.4-develop` therefore I have to close this PR now.

Please feel free to reopen same PR into current branch if you think that issue persists.

Thanks.

**Comment by Den4ik** [comment]
@ishakhsuvarov does your comment mean that mqp is die and no official quality patches could be created for previous Magento versions?
CC @sidolov

**Pull request closed without merging**
