### PR TITLE
Remove forbidden `@author` tag

### LINKED ISSUE #37253: [Issue] Remove forbidden `@author` tag
This issue is automatically created based on existing pull request: magento/magento2#37003: Remove forbidden `@author` tag

---------
### Description
According to https://devdocs.magento.com/guides/v2.4/coding-standards/docblock-standard-general.html#documentation-space, the `@author` tag is not permitted in Magento. This pull request removes this tag from some modules. Given there are so many instances of this tag, I've opened a small pull request to get the process started. I expect that the linter will force me to fix several other coding standards violations on the way, so having a smaller pull request means that task is easier to manage. I plan to open more pull requests to tackle the other instances of this tag.

See also https://github.com/magento/magento-coding-standard/pull/382 and https://github.com/magento/magento-coding-standard/issues/167

### Manual testing scenarios
There are not code changes in this pull request. This pull request only removes forbidden comments.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fredden**
### Description
According to https://devdocs.magento.com/guides/v2.4/coding-standards/docblock-standard-general.html#documentation-space, the `@author` tag is not permitted in Magento. This pull request removes this tag from some modules. Given there are so many instances of this tag, I've opened a small pull request to get the process started. I expect that the linter will force me to fix several other coding standards violations on the way, so having a smaller pull request means that task is easier to manage. I plan to open more pull requests to tackle the other instances of this tag.

See also https://github.com/magento/magento-coding-standard/pull/382 and https://github.com/magento/magento-coding-standard/issues/167

### Manual testing scenarios
There are not code changes in this pull request. This pull request only removes forbidden comments.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37253: Remove forbidden `@author` tag

### CODE REVIEW

**Comment by fredden** [comment]
@magento run Static Tests

**Review by leonhelmus — APPROVED** [review]
Looks good to me

**Comment by leonhelmus** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
Adding the same priority as https://github.com/magento/magento2/pull/36976#event-8742638190

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B, Functional Tests EE , Static Tests

**Comment by engcom-Lima** [comment]
@magento run Static Tests ,Functional Tests EE

**Comment by engcom-Lima** [comment]
@magento run Static Tests , Functional Tests EE

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

- Verified @author tag got removed from `email-fedex-groupedproduct-integration` module.

**After:** :heavy_check_mark:  
Screenshot 2023-04-19 at 12 28 26 PM




No addiitional manual test cases is required for the regression as this PR related to the removal of the @author tag from the `email-fedex-groupedproduct-integration` module.

Multiple builds are failing hence, moving this PR to Extended Testing

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Static Tests,  WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Unit Tests

**Comment by engcom-Charlie** [comment]
The Functional CE failures are not related to the PR changes as failing tests are known issues, below is list of open JIRAs for the same.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37003/cd8400f547e9addde26a27128dc19059/Functional/allure-report-ce/index.html#categories
image

**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37003/21db55cf401ab445382013250ae54d6f/Functional/allure-report-ce/index.html#categories
image

**Known issues:**
[ACQE-6695](https://jira.corp.adobe.com/browse/ACQE-6695) - TierPricingWhenPriceScopeIsWebsiteWorkingProperlyWithMultipleCurrenciesConfiguredTest
[ACQE-6774](https://jira.corp.adobe.com/browse/ACQE-6695) - StorefrontCashOnDeliveryPaymentForSpecificCountryTest

**Comment by engcom-Charlie** [comment]
The Functional EE failures are not related to the PR changes as failing tests are known issues, below is list of open JIRAs for the same.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37003/87daad5f1fdcf3f35cfe6162892917f4/Functional/allure-report-ee/index.html#categories
image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37003/6aaafc25d2cac9bffc92644cb0ac9efe/Functional/allure-report-ee/index.html#categories/f9b62a55a184699bcb07a760e8ac3662/d3c2e79e520d5d9b/
image


**Known issues:**
[ACQE-6695](https://jira.corp.adobe.com/browse/ACQE-6695) - TierPricingWhenPriceScopeIsWebsiteWorkingProperlyWithMultipleCurrenciesConfiguredTest
[ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331) - StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest
[ACQE-6774](https://jira.corp.adobe.com/browse/ACQE-6774) - StorefrontCashOnDeliveryPaymentForSpecificCountryTest

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
The Functional B2B failures are not related to the PR changes as failing tests are known issues, below is list of open JIRAs for the same. Hence moving this PR to Merge in Progress

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37003/2d7be885d14a6a14fbb68ff82e714c33/Functional/allure-report-b2b/index.html#categories
image


**Run 2**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37003/fd7c9b90fdea5625d91c8d08b749a84e/Functional/allure-report-b2b/index.html#categories/8f0831c1d06562890f5ec21062dae309/da277d4c25e77809/
image

**Known issues:**
[ACQE-6695](https://jira.corp.adobe.com/browse/ACQE-6695) - TierPricingWhenPriceScopeIsWebsiteWorkingProperlyWithMultipleCurrenciesConfiguredTest
[ACQE-6774](https://jira.corp.adobe.com/browse/ACQE-6774) - StorefrontCashOnDeliveryPaymentForSpecificCountryTest

**Pull request merged**
