### PR TITLE
[MFTF] Refactoring AdminPanelIsFrozenIfStorefrontIsOpenedViaCustomerViewTest

### LINKED ISSUE #31519: [Issue] [MFTF] Refactoring AdminPanelIsFrozenIfStorefrontIsOpenedViaCustomerViewTest
This issue is automatically created based on existing pull request: magento/magento2#31502: [MFTF] Refactoring AdminPanelIsFrozenIfStorefrontIsOpenedViaCustomerViewTest

---------
### Description
The test is refactored to improve execution time

### Manual testing scenarios
1. Place an order
2. Create an invoice, a shipment, a credit memo for the order
3. Login to Storefront
4. Go to My Account->My Orders
5. Open the order
6. Print the order
7. Assert customer data

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description
The test is refactored to improve execution time

### Manual testing scenarios
1. Place an order
2. Create an invoice, a shipment, a credit memo for the order
3. Login to Storefront
4. Go to My Account->My Orders
5. Open the order
6. Print the order
7. Assert customer data

### Resolved issues:
1. [x] resolves magento/magento2#31519: [MFTF] Refactoring AdminPanelIsFrozenIfStorefrontIsOpenedViaCustomerViewTest

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8601](https://jira.corp.magento.com/browse/ENGCOM-8601) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** Functional Tests B2B, EE, CE are failed

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run Functional Tests B2B

**Comment by gabrieldagama** [comment]
@magento run Functional Tests B2B

**Pull request merged**
