### PR TITLE
MFTF: Set of fixes for failing Functional Tests

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
**Functional Tests** are running simultaneously and as a result - sometimes the Magento instances created for Testing are just overloaded. As mentioned in https://github.com/magento/magento2/issues/26396 - that's because we get False Negatives.

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/26396 DeleteProduct and DeleteCustomer Action Groups failure

### Manual testing scenarios (*)
1. Add `.` to README in random place
2. Create Pull Request

### Questions or comments
:man_facepalming: 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by okorshenko** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento instance for you

**Comment by okorshenko** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [new Magento instance](https://pr-26407.instances.magento-community.engineering).
Admin access: [https://pr-26407.instances.magento-community.engineering/admin](https://pr-26407.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
Here is some issue with unit tests, but I't definitely not related to this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6621](https://jira.corp.magento.com/browse/ENGCOM-6621) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
**Notice:** QA not applicable

**Comment by engcom-Golf** [comment]
@magento run FunctionalTestsB2B  tests

**Comment by engcom-Golf** [comment]
@magento run Functional tests

**Comment by engcom-Golf** [comment]
@magento run functional tests

**Pull request merged**
