### PR TITLE
Implement ActionInterface for `cms/page/view`

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
This PR is example for **How to replace Abstract Action class with ActionInterface**

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]
Functional tests failure isn’t related to changes from this PR

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7133](https://jira.corp.magento.com/browse/ENGCOM-7133) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests B2B

I miss green :heavy_check_mark:

**Pull request merged**
