### PR TITLE
#33935 fixed issue with Call to undefined method getLinkField

### PR DESCRIPTION
**Pull request by paveldedovetsewave**
### Description (*)
This PR fixes error reported in the #33935

### Fixed Issues (if relevant)
Fix for https://github.com/magento/magento2/issues/33935

### Manual testing scenarios (*)
1. Admin - Stores - Configuration - Catalog - Catalog - Set "Use Flat Catalog Product" to Yes and Save
2. Reindex and Clear cache
3. Front-end - Open any Bundle Product - No errors on UI

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by paveldedovetsewave** [comment]
@magento give me test instance

**Comment by paveldedovetsewave** [comment]
@magento run all tests

**Comment by paveldedovetsewave** [comment]
@magento run all tests

**Comment by BarnyShergold** [comment]
@magento run Functional Tests B2B, Static Tests

**Comment by BarnyShergold** [comment]
@paveldedovetsewave  - You need to sign the Adobe CLA as well

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
How does this solve the issue? The issue implies some code calls the method getLinkField, but there is no mention of this in the code changes.

**Comment by DedovetsPavel** [comment]
@BarnyShergold the previous solultion with $selectionsCollection->exportToArray() was incorrect and caused call method getLinkField from the collection which doesn't have such method. I've changed original method with using another purpose for getting data ($selection->getData('is_default') instead of $selection['is_default'])

**Comment by DedovetsPavel** [comment]
@magento run all tests

**Comment by DedovetsPavel** [comment]
@magento run Functional Tests B2B

**Comment by BarnyShergold** [comment]
@DedovetsPavel - The UnitTests are now failing as the method you changed has 7 levels of nesting!
Perhaps refactor first section to be -

```
        $typeInstance = $product->getTypeInstance();
        $typeInstance->setStoreFilter($product->getStoreId(), $product);

        if ($product->getTypeId() === BundleType::TYPE_BUNDLE && 
            $typeInstance->hasRequiredOptions($product)) {

```

Or perhaps extract lines 43 - 52 and make a private method? getIsNoCustomizations ?

**Comment by DedovetsPavel** [comment]
@magento run all tests

**Comment by DedovetsPavel** [comment]
@magento run all tests

**Comment by BarnyShergold** [comment]
@magento run Static Tests,Integration Tests,Functional Tests CE,Functional Tests B2B

**Comment by BarnyShergold** [comment]
@magento run Static Tests,Functional Tests B2B

**Review by BarnyShergold — APPROVED** [review]
All tests now pass!

**Comment by magento-engcom-team** [comment]
Hi @BarnyShergold, thank you for the review.
[ENGCOM-9241](https://jira.corp.magento.com/browse/ENGCOM-9241) has been created to process this Pull Request
:eight_spoked_asterisk: @BarnyShergold, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** 

**Manual testing scenario:**

Admin - Stores - Configuration - Catalog - Catalog - Set "Use Flat Catalog Product" to Yes and Save
Reindex and Clear cache
Front-end - Open any Bundle Product - No errors on UI
**Before:** :heavy_multiplication_x: 



**After:** :heavy_check_mark:  


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Review by engcom-Delta — CHANGES_REQUESTED** [review]
User is still getting error on UI when we Set "Use Flat Catalog Product" to Yes

**Comment by imran9935** [comment]
Hello @paveldedovetsewave ,
As I have checked, this issue is happening because there is one more file (Magento\Bundle\Plugin\Catalog\ViewModel\Product\AddBundleOptionsData) in which $selectionsCollection->exportToArray() **Screenshot-1** is used, which is causing the issue. So I have changed the code and now it is working as intented, please check below **Screenshot-2**.

Screenshot-1
image

Screenshot-2
image

**Comment by engcom-Dash** [comment]
Hello @paveldedovetsewave 

It looks like this branch is out of date with the base branch. Could you please update it so we can proceed with this PR?

Thank you!

**Comment by engcom-Dash** [comment]
Closing this PR since it has not been updated in a while. Please feel free to reopen if needed.

**Pull request closed without merging**
