### PR TITLE
#19062 Remove unused PHPMD ruleset

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)

Each contribution to Magento is tested against the Code Style rules provided in Magento repository:

https://github.com/magento/magento2/blob/a119df4e9ab5ffe3f3097255cc6a02cfe2e23376/dev/tests/static/phpunit.xml.dist#L21-L23

The class contains ruleset hardcoded:

https://github.com/magento/magento2/blob/9db2bd05dbf0a1a7a5b4986bdb9091f4f2d2c1f8/dev/tests/static/testsuite/Magento/Test/Php/LiveCodeTest.php#L285

However in the repository, there is also other ruleset available:

https://github.com/magento/magento2/blob/42ad5383200fb60cc4fa543094d805c9dc94b546/dev/tests/static/framework/Magento/ruleset.xml

Which is not being used across the project.

### Fixed Issues (if relevant)

1. magento/magento2#19062

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by orlangur** [comment]
This is a PHPCS ruleset used [here](https://github.com/magento/magento2/blob/9db2bd05dbf0a1a7a5b4986bdb9091f4f2d2c1f8/dev/tests/static/testsuite/Magento/Test/Php/LiveCodeTest.php#L269).

**Comment by lbajsarowicz** [comment]
@orlangur I feel like this ruleset (https://github.com/magento/magento2/blob/42ad5383200fb60cc4fa543094d805c9dc94b546/dev/tests/static/framework/Magento/ruleset.xml) is inconsistent with the other one https://github.com/magento/magento2/blob/42ad5383200fb60cc4fa543094d805c9dc94b546/dev/tests/static/testsuite/Magento/Test/Php/_files/phpmd/ruleset.xml

For example:
`<rule ref="Squiz.Commenting.DocCommentAlignment"/>`

I just wonder about getting some consistency, that's why I wanted to get rid of the one.

**Comment by orlangur** [comment]
One is for PHPCS, another is for PHPMD. They must differ.

**Pull request closed without merging**
