### PR TITLE
Fix for category tree structure being deformed in GraphGl responses

### PR DESCRIPTION
**Pull request by raivisdejus**
### Description (*)
Currently running the following Graph Ql query

```
{
    category(id: 2) {
        children {
            name
            children {
                name
                children {
                    name
                    children {
                        name
                    }
                }
            }
        }
    }
}
```

Will give categories that are sorted according to their levels where last items in a level get all the children.
```
Cat 1
Cat 2
- Cat 1 subcategory
- Cat 2 subcategory 
```

### Fixed Issues (if relevant)
1. magento/magento2#18735: Graph Ql category tree structure is lost (children all grouped with last item)

### Manual testing scenarios (*)
Run the following query with the fixed code
```
{
    category(id: 2) {
        children {
            name
            children {
                name
                children {
                    name
                    children {
                        name
                    }
                }
            }
        }
    }
}
```
Category tree structure is now preserved
```
Cat 1
- Cat 2 subcategory
Cat 2
- Cat 1 subcategory 
```

### Contribution checklist (*)
 - [+] Pull request has a meaningful description of its purpose
 - [+] All commits are accompanied by meaningful commit messages
 - [-] All new or changed code is covered with unit/integration tests (if applicable)
 - [+] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @raivisdejus. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by raivisdejus** [comment]
@orlangur Please note this pull request as proper fix for the previous one  (18975) you assigned to yourself

**Comment by orlangur** [comment]
@raivisdejus please cover implementation with tests - especially cover cases which you found not working for previous implementation.

**Comment by orlangur** [comment]
Hi @raivisdejus, please create this PR in GraphQL dedicated fork: https://github.com/magento/graphql-ce

**Pull request closed without merging**
