### PR TITLE
Only Update Indexer Mode When Required

### LINKED ISSUE #36823: [Issue] Only Update Indexer Mode When Required
This issue is automatically created based on existing pull request: magento/magento2#36422: Only Update Indexer Mode When Required

---------
### Description (*)
Updates the indexer mode change mass actions to only change modes when required i.e. when the current index mode is different to the one being applied. This prevents unnecessary trips to the database.

Also updates the messaging displayed to the admin to inform them how many indexers were updated and how many were skipped thanks to this change.

Finally, replaces the deprecated `addSuccess()` function with the non-deprecated `addSuccessMessage()` function for the message manager class when displaying the changed messages to the admin.

### Manual testing scenarios (*)
1. Log into the admin
2. Set any number of indexers to be `Update on Schedule`
3. Observe the success message to confirm the correct number of indexers were updated versus skipped, based on their original mode

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by pykettk**
### Description (*)
Updates the indexer mode change mass actions to only change modes when required i.e. when the current index mode is different to the one being applied. This prevents unnecessary trips to the database.

Also updates the messaging displayed to the admin to inform them how many indexers were updated and how many were skipped thanks to this change.

Finally, replaces the deprecated `addSuccess()` function with the non-deprecated `addSuccessMessage()` function for the message manager class when displaying the changed messages to the admin.

### Manual testing scenarios (*)
1. Log into the admin
2. Set any number of indexers to be `Update on Schedule`
3. Observe the success message to confirm the correct number of indexers were updated versus skipped, based on their original mode

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36823: Only Update Indexer Mode When Required

### CODE REVIEW

**Comment by pykettk** [comment]
@magento run all tests

**Comment by pykettk** [comment]
@magento give me 2.4-develop instance

**Comment by pykettk** [comment]
@magento give me test instance

**Comment by pykettk** [comment]
@magento give me 2.4-develop instance

**Comment by pykettk** [comment]
@magento give me test instance

**Comment by pykettk** [comment]
# Manual Testing Results
## Before
https://user-images.githubusercontent.com/40261741/200118504-43a7ab37-e9e5-406a-a04c-8042f05a2367.mov

## After
https://user-images.githubusercontent.com/40261741/200118499-d3e9406e-33d4-4808-9375-2d6a60cd9404.mov

**Comment by pykettk** [comment]
@magento run Unit Tests

**Comment by pykettk** [comment]
@magento run all tests

**Comment by pykettk** [comment]
@magento give me test instance

**Comment by pykettk** [comment]
@magento run all tests

**Review by fredden — APPROVED** [review]

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by shraddhajain123** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
As this PR's [branch](https://github.com/pykettk/magento2/tree/indexer-mode-change) is deleted and hence not accessible, created new PR. 

https://github.com/magento/magento2/pull/36864 is the new PR which is the replacement of current one. 

Closing this PR now, Rest whole activity will be take care in  https://github.com/magento/magento2/pull/36864

Thank you!

**Pull request closed without merging**
