### PR TITLE
Order information in print order, invoice, credit memo and shipment is not proper aligned

### LINKED ISSUE #24393: Order information in print order, invoice, credit memo and shipment is not proper aligned
### Preconditions (*)

1. Magento 2.3.2 ... 2.4-develop
1. PHP 7.2.19

### Steps to reproduce (*)

1. Place an order
1. Go to customer account section and open that order
1. Click on print order link

### Expected result (*)

1. Order information should be
order-info

### Actual result (*)

order-info-issue

### PR DESCRIPTION
**Pull request by engcom-Echo**
### Description (*)

Order information must be displayed in a line.
64064204-082f9f00-cc1c-11e9-8823-2797fc233e11

### Fixed Issues (if relevant)

1. Fixes magento/magento2#24393

### Manual testing scenarios (*)

See magento/magento2#24393

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by eduard13** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @eduard13, here is your [new Magento instance](https://pr-28948.instances.magento-community.engineering).
Admin access: [https://pr-28948.instances.magento-community.engineering/admin_0dd0](https://pr-28948.instances.magento-community.engineering/admin_0dd0)
Login: `032f375e` Password: `4628324d068e`
Instance will be terminated in up to 3 hours.

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @engcom-Echo, it works great 👍, thank you for the fix. 

However, probably it makes sense to cover the customer frontend part by a simple MFTF test, that will check for the `table` tag on `Order Information` section. 
Additionally, most likely there will be some failing static tests as well (related to the template files).
Thank you.

**Comment by engcom-Echo** [comment]
Hi, @eduard13.

The first task I want to see which tests will fail and correct them accordingly.
Then I will cover the changes. Thank you for your cooperation.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run all tests

**Review by eduard13 — APPROVED** [review]
Approving 👍

**Comment by eduard13** [comment]
The failing tests don't seem to be related with this PR.

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-7828](https://jira.corp.magento.com/browse/ENGCOM-7828) has been created to process this Pull Request

**Comment by eduard13** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-7828](https://jira.corp.magento.com/browse/ENGCOM-7828) has been created to process this Pull Request

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @engcom-Echo, could you please fix the merging conflicts here?
Thank you.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @engcom-Echo,
Could you resolve conflicts?

**Comment by eduard13** [comment]
Hi @engcom-Echo, please feel free to reopen it in case you want to continue the progress on it. Also it seems that the related issue has been closed as well.
Thank you.

**Pull request closed without merging**
