### PR TITLE
Date column ui component locale date format

### PR DESCRIPTION
**Pull request by Karlasa**
### Description (*)
added option to fallback to locale date format configuration. 
So in case lets say in ui component xml you pass empty value you can automatically fallback to locale date format. 

### Fixed Issues (if relevant)

Fixes issue where ui component have hardcoded date format and when having multi site with different date formats it adds option to fallback to locale settings. 
example: Have this issue with requisition lists grid in B2B in storefront.

### Manual testing scenarios (*)

By default it doesn't change anything but if you change passed settings in component level and send empty value you can use locale specific settings. 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @Karlasa. Thank you for your contribution. Would you provide a little bit more information about the use case:

> Fixes issue where ui component have hardcoded date format and when having multi site with different date formats it adds option to fallback to locale settings.

So, if an UI component has a hardcoded date format, the following check https://github.com/magento/magento2/pull/22213/files#diff-8c266c07ae31f60348f20567f5fa5d92R29
does not override the hardcoded value. So a value from locale won't count. 

Thank you.

**Comment by Karlasa** [comment]
@rogyar 
I will use it with patch where I remove UI component setting value (as it's not possible to remove under theme) 
example like this: 

Screen Shot 2019-04-09 at 14 44 42

Just figured that it would be good to have this option if anyone will be going to create something new with those components :)

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5323](https://jira.corp.magento.com/browse/ENGCOM-5323) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
