### PR TITLE
[Backport 2.1-develop] #11347 Fix payment failed email not being sent

### PR DESCRIPTION
**Pull request by adrian-martinez-interactiv4**
According to documentation, an email should be sent "if the payment method that is chosen during checkout fails to complete the transaction."

### Description
Payment failed email is not being sent.

### Fixed Issues (if relevant)

1. magento/magento2#11347: Payment Failed Email not working as intended

### Manual testing scenarios
As described in  magento/magento2#11347

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by dmanners** [comment]
I will put this on hold until the 2.2-develop pr has been processed.

**Comment by dmanners** [comment]
As with https://github.com/magento/magento2/pull/11603 I will close this PR because.

1. Not all payment providers use the code in this manor and as such this will only fix some cases.
2. The exception is not payment specific and as such we could be sending payment failure emails that are unrelated to payment failure.

Feel free to reach out if you have any questions about this.

**Comment by ebaschiera** [comment]
Hi @dmanners ,
I see no reason to reject this PR based on your reason 2.
In Magento 1 the failed transaction email worked exactly like that. Emails were sent not only due to payment troubles, but for any exception thrown during checkout. I.E.: db table lock timeouts, errors in modules observing sales_order_place_before and sales_order_payment_* events, and so on. We run several web shops and we managed to see a lot of different cases.
In my opinion there is no need to remove that feature.

Thanks!

**Comment by dmanners** [comment]
@ebaschiera thanks for the feedback. I have raised you points with the payment integration team. They have this change on their radar.

**Pull request closed without merging**
