### PR TITLE
SubTotal Rounding Issue For Decimal Quantity Enabled Product

### LINKED ISSUE #37817: SubTotal Rounding Issue For Decimal Quantity Enabled Product
### Preconditions and environment

::: Magento version : 2.4.6 :::

::: Test Product Specification :::
-- Type : Simple
-- Price 20.67
-- Quantity : 1.5 (Enabled Decimal Quantity For Product)

::: Fixed Shipping Price :::
-- Price : 7.50 $

### Steps to reproduce

Add a product, with above defined specifications, to cart. (Now look at checkout/cart page)

After that flat rate shipping price is set to 7.50 $, place order. And check customer account => Order History (You'll find incorrect order total, it was supposed to be 38.51 but showing 30.50) => View Order (Order Item Subtotal, Sub Total & Grand Total is wrong with value of 38.50, which is supposed to be 38.51).

### Expected result

Expected result should be like 

Before Place Order
Screenshot

After Place Order
Screenshot (2)
Screenshot (4)
Order View Page Admin Side
Screenshot (6)
Invoice View Page Admin Side
Screenshot (9)

### Actual result

Actual result is like below.
Before Place Order
Screenshot (1)

After Placing Order
Screenshot (3)
Screenshot (5)
Order View Page Admin Side
Screenshot (7)
Invoice View Page Admin Side
Screenshot (10)

### Additional information

This isssue is also occuring in the emails being sent after order confirmation, invoice pdf etc.. where ever the row total, subtotal and grant total is concerned. Also grantotal of the order is wrong in the history grids. This could also be an issue in api responses.

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Kannakiraj123**
### Description (*)
SubTotal Rounding Issue For Decimal Quantity Enabled Product

### Related Pull Requests
Insert Below Code

vendor/magento/module-directory/Model/Currency.php : Line No. 429

```
$this->numberFormatter->setAttribute(
            \NumberFormatter::ROUNDING_MODE,
            \NumberFormatter::ROUND_HALFUP
        );
```
### Fixed Issues (if relevant)
1. Fixes #37817 

### Manual testing scenarios (*)

::: Test Product Specification :::
-- Type : Simple
-- Price 20.67
-- Quantity : 1.5 (Enabled Decimal Quantity For Product)

::: Fixed Shipping Price :::
-- Price : 7.50 $

Steps to reproduce
Add a product, with above defined specifications, to cart. (Now look at checkout/cart page)

After that flat rate shipping price is set to 7.50 $, place order. And check customer account => Order History (You'll find incorrect order total, it was supposed to be 38.51 but showing 30.50) => View Order (Order Item Subtotal, Sub Total & Grand Total is wrong with value of 38.50, which is supposed to be 38.51).

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Kannakiraj123** [comment]
@magento run all tests

**Comment by Kannakiraj123** [comment]
@magento run Unit Tests

**Comment by Kannakiraj123** [comment]
@magento run Unit Tests

**Comment by Kannakiraj123** [comment]
@magento run Unit Tests

**Comment by Kannakiraj123** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hello,

Thanks for your Contribution and collaboration.

internal team is started working on this issue and the steps to reproduce are as below

- Log in to Magento admin panel.
- Set one product for decimal qty allow.
- Set price 20.67
- Open the same product in frontend
- Add 1.5 qty in cart


Thanks.

**Comment by engcom-Bravo** [comment]
Hi @Kannakiraj123,

Thanks for your Contribution.

Internal team is working on this issue as mentioned in https://github.com/magento/magento2/issues/37817#issuecomment-1785004635.

Thanks.

**Comment by swnsma** [comment]
@magento run all tests

**Comment by swnsma** [comment]
Hello @Kannakiraj123,
According to DoD, changes, changes should be covered with automated tests.
May I ask you to add an integration test that would check test case described in https://github.com/magento/magento2/issues/37817 ?

**Review by swnsma — CHANGES_REQUESTED** [review]
Please add an integration test that would check test case described in https://github.com/magento/magento2/issues/37817

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-9221 by the internal team
Related commits: https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-9221&type=commits

Based on the Jira ticket, the target version is 2.4.7-beta3.

Thanks

**Pull request closed without merging**
