### PR TITLE
fixed confusing grammar in the backend formatDate() function

### PR DESCRIPTION
**Pull request by princefishthrower**
### Description (*)
Just wanted to fix some confusing grammar I found in the standard code while working on our Magento project - there was just some poorly worded descriptions on the formatDate() function

### Manual testing scenarios (*)
No code changed, only comments.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [X] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @princefishthrower, thank you for your contribution, could you please also fix the static tests?
Thank you.

**Comment by engcom-Golf** [comment]
Hi @eduard13 done :heavy_check_mark:

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-6963](https://jira.corp.magento.com/browse/ENGCOM-6963) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Pull request merged**
