### PR TITLE
Implement ActionInterface for /checkout/sidebar/updateItemQty

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This is a part of the process of introducing implementations of `ActionInterface`.

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7246](https://jira.corp.magento.com/browse/ENGCOM-7246) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by VladimirZaets** [comment]
Hi @Bartlomiejsz .  We still decide approach with controllers (extending or interface implementation) due to backward compatibility policy, so currently, I put on hold label. As we take some decision I will provide updates. Thanks

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @Bartlomiejsz,
We finally have final decision, it clearly described here https://github.com/magento/magento2/pull/27296#pullrequestreview-418541438.

Could you bring back extending from abstract action and resolve conflicts?

**Comment by Bartlomiejsz** [comment]
Hi @ihor-sviziev, the only reason of this PR was to remove extending of Abstract action to improve performsnce. If this for some reason is not allowed for 2.4.0 it makes no sense to work on this PR

**Pull request closed without merging**
