### PR TITLE
[MFTF] Refactoring of CaptchaWithDisabledGuestCheckoutTest

### LINKED ISSUE #30828: [Issue] WIP: [MFTF] Refactoring of CaptchaWithDisabledGuestCheckoutTest
This issue is automatically created based on existing pull request: magento/magento2#30803: WIP: [MFTF] Refactoring of CaptchaWithDisabledGuestCheckoutTest

---------

### Description (*)
The test is refactored according to the best practices followed by MFTF.

#### Preconditions: 
Guest checkout is disabled, 1 failed login attempt is allowed

1. Add a product to the Cart
2. Go to the MiniCart -> click the "Checkout" button
3. Provide incorrect credentials on the Sign In popup
4. Check if Captcha is displayed
5. Reload page
6. Go to the MiniCart -> click the "Checkout" button
7. Check if Captcha is displayed

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
The test is refactored according to the best practices followed by MFTF.

#### Preconditions: 
Guest checkout is disabled, 1 failed login attempt is allowed

1. Add a product to the Cart
2. Go to the MiniCart -> click the "Checkout" button
3. Provide incorrect credentials on the Sign In popup
4. Check if Captcha is displayed
5. Reload page
6. Go to the MiniCart -> click the "Checkout" button
7. Check if Captcha is displayed

### Resolved issues:
1. [x] resolves magento/magento2#30828: WIP: [MFTF] Refactoring of CaptchaWithDisabledGuestCheckoutTest

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8543](https://jira.corp.magento.com/browse/ENGCOM-8543) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** Some tests are waiting for status

**Comment by AnnaAPak** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
✔️ QA Passed

The provided MFTF test case is working fine. Please find the Allure report for the same.

image

image

**Comment by sidolov** [comment]
@magento run Functional Tests B2B

**Pull request merged**
