### PR TITLE
Added function to check against running/pending/successful cron tasks

### PR DESCRIPTION
**Pull request by chickenland**
This PR adds function to filter all correctly run, running or pending cron tasks.

### Description (*)
If a cron has just been run, cache is cleared and the cron processed again, then scheduled tasks reschedule for the same time.

### Fixed Issues (if relevant)
1. magento/magento2#21380: Cron schedule is being duplicated

### Manual testing scenarios (*)
When not updated, running `bin/magento cron:run && bin/magento cache:flush` repeatedly will cause tasks that have completed to be rescheduled - leading to many tasks repeating.  This should no longer happen.

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @chickenland,
Thank you for contribution! Your changes looks good to me.

Unfortunately there is failing static tests. Could you fix code to make tests pass, squash all changes into single commit and force push?

Also looks like method `getPendingSchedules` not used anymore and should be safely removed

Thank you in advance

**Comment by chickenland** [comment]
Pushed up changes that should fix the tests.

I believe that getPendingSchedules is still used within processPendingJobs and shouldn't be removed at this time.

**Comment by chickenland** [comment]
Pushed another series - I might need a pointer on what is failing as I can't figure it out from the message that's returned.

**Comment by chickenland** [comment]
@ihor-sviziev Could you give me a steer on what needs fixing here? I can't seem to figure it out from the static test results in https://testing-service.magento-community.engineering/reports/magento/magento2/pull/23312/8d0f1771-5e56-49e4-a733-183a3aa289be/10219/Statics/allure-report-ce/index.html#suites/51d3ab4d5d77a0bc6a7ea344e9e7e6be/9d0419465c8ec328/

**Comment by engcom-Foxtrot** [comment]
@ihor-sviziev @chickenland static tests fixed.

**Comment by chickenland** [comment]
Thanks @engcom-Foxtrot !  Was it just a case of addressing the ones that couldn't be auto fixed?  From the looks of it, this was around things I don't think I'd changed :/

**Comment by sivaschenko** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5335](https://jira.corp.magento.com/browse/ENGCOM-5335) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

**Before:**

before

**After:**

after

**Comment by anuprasadkummali** [comment]
i am getting this swarm of cron in scheduler suspect this to be the reason behind high cpu usage. Magento CE 2.3.4 

 3696244 | yotpo_yotpo_orders_sync                       | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:06:00 | NULL        | NULL        |
|     3696245 | yotpo_yotpo_orders_sync                       | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:07:00 | NULL        | NULL        |
|     3696246 | yotpo_yotpo_orders_sync                       | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:08:00 | NULL        | NULL        |
|     3696247 | yotpo_yotpo_orders_sync                       | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:09:00 | NULL        | NULL        |
|     3696248 | yotpo_yotpo_orders_sync                       | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:10:00 | NULL        | NULL        |
|     3696249 | yotpo_yotpo_orders_sync                       | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:11:00 | NULL        | NULL        |
|     3696250 | yotpo_yotpo_orders_sync                       | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:12:00 | NULL        | NULL        |
|     3696251 | yotpo_yotpo_orders_sync                       | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:13:00 | NULL        | NULL        |
|     3696252 | yotpo_yotpo_orders_sync                       | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:14:00 | NULL        | NULL        |
|     3696253 | yotpo_yotpo_orders_sync                       | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:15:00 | NULL        | NULL        |
|     3696254 | yotpo_yotpo_orders_sync                       | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:16:00 | NULL        | NULL        |
|     3696255 | ddg_automation_customer_subscriber_guest_sync | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:15:00 | NULL        | NULL        |
|     3696257 | ddg_automation_importer                       | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:10:00 | NULL        | NULL        |
|     3696258 | ddg_automation_importer                       | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:15:00 | NULL        | NULL        |
|     3696259 | ddg_automation_status                         | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:15:00 | NULL        | NULL        |
|     3696261 | ddg_automation_abandonedcarts                 | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:10:00 | NULL        | NULL        |
|     3696262 | ddg_automation_abandonedcarts                 | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:15:00 | NULL        | NULL        |
|     3696263 | ddg_automation_reviews_and_wishlist           | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:15:00 | NULL        | NULL        |
|     3696265 | ddg_automation_campaign                       | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:10:00 | NULL        | NULL        |
|     3696266 | ddg_automation_campaign                       | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:15:00 | NULL        | NULL        |
|     3696267 | ddg_automation_order_sync                     | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:15:00 | NULL        | NULL        |
|     3696268 | ddg_automation_catalog_sync                   | pending | NULL     | 2020-08-29 16:57:07 | 2020-08-29 17:15:00 | NULL        | NULL        |
|     3696274 | indexer_reindex_all_invalid                   | pending | NULL     | 2020-08-29 17:00:07 | 2020-08-29 17:06:00 | NULL        | NULL        |
|     3696275 | indexer_reindex_all_invalid                   | pending | NULL     | 2020-08-29 17:00:07 | 2020-08-29 17:07:00 | NULL        | NULL        |
|     3696276 | indexer_reindex_all_invalid                   | pending | NULL     | 2020-08-29 17:00:07 | 2020-08-29 17:08:00 | NULL        | NULL        |
|     3696277 | indexer_reindex_all_invalid                   | pending | NULL     | 2020-08-29 17:00:07 | 2020-08-29 17:09:00 | NULL        | NULL        |
|     3696278 | indexer_reindex_all_invalid                   | pending | NULL     | 2020-08-29 17:00:07 | 2020-08-29 17:10:00 | NULL        | NULL        |
|     3696279 | indexer_reindex_all_invalid                   | pending | NULL     | 2020-08-29 17:00:07 | 2020-08-29 17:11:00 | NULL        | NULL        |
|     3696280 | indexer_reindex_all_invalid                   | pending | NULL     | 2020-08-29 17:00:07 | 2020-08-29 17:12:00 | NULL        | NULL        |
|     3696281 | indexer_reindex_all_invalid                   | pending | NULL     | 2020-08-29 17:00:07 | 2020-08-29 17:13:00 | NULL        | NULL        |
|     3696282 | indexer_reindex_all_invalid                   | pending | NULL     | 2020-08-29 17:00:07 | 2020-08-29 17:14:00 | NULL        | NULL        |
|     3696283 | indexer_reindex_all_invalid                   | pending | NULL     | 2020-08-29 17:00:07 | 2020-08-29 17:15:00 | NULL        | NULL        |
|     3696289 | indexer_update_all_views                      | pending | NULL     | 2020-08-29 17:00:07 | 2020-08-29 17:06:00 | NULL        | NULL        |
|     3696290 | indexer_update_all_views                      | pending | NULL     | 2020-08-29 17:00:07 | 2020-08-29 17:07:00 | NULL        | NULL        |
|     3696291 | indexer_update_all_views                      | pending | NULL     | 2020-08-29 17:00:07 | 2020-08-29 17:08:00 | NULL        | NULL        |
|     3696292 | indexer_update_all_views                      | pending | NULL     | 2020-08-29 17:00:07 | 2020-08-29 17:09:00 | NULL        | NULL        |
|     3696293 | indexer_update_all_views                      | pending | NULL     | 2020-08-29 17:00:07 | 2020-08-29 17:10:00 | NULL        | NULL        |
|     3696294 | indexer_update_all_views                      | pending | NULL     | 2020-08-29 17:00:07 | 2020-08-29 17:11:00 | NULL        | NULL        |
|     3696295 | indexer_update_all_views                      | pending | NULL     | 2020-08-29 17:00:07 | 2020-08-29 17:12:00 | NULL        | NULL        |
|     3696296 | indexer_update_all_views                      | pending | NULL     | 2020-08-29 17:00:07 | 2020-08-29 17:13:00 | NULL        | NULL        |
|     3696297 | indexer_update_all_views                      | pending | NULL     | 2020-08-29 17:00:07 | 2020-08-29 17:14:00 | NULL        | NULL        |
|     3696298 | indexer_update_all_views                      | pending | NULL     | 2020-08-29 17:00:07 | 2020-08-29 17:15:00 | NULL        | NULL

**Comment by ihor-sviziev** [comment]
@anuprasadkummali 
Could you report separate issue with more info about steps to reproduce?

**Pull request merged**
