### PR TITLE
security-package/issues/115: Fix AdminSessionsManagerTest and AuthSessionTest. 

### PR DESCRIPTION
**Pull request by p-bystritsky**
### Description (*)

Fix required for  magento/security-package builds stabilization.

### Fixed Issues (if relevant)

1. https://github.com/magento/security-package/issues/115

### Manual testing scenarios (*)

1. None

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run Unit Tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7031](https://jira.corp.magento.com/browse/ENGCOM-7031) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by naydav** [comment]
Fixed in scope of https://github.com/magento/security-package/pull/124

**Pull request closed without merging**
