### PR TITLE
add check for attribute option values

### PR DESCRIPTION
**Pull request by torhoehn**
### Fixed Issues (if relevant)

1. magento/magento2#21504: Attribute text field takes blank values

### Manual testing scenarios (*)

1. While configurable product creation now you can't create an attribute option value which only contains a space.
2. While attribute creation now you can't save any attribute if the option value only contains a space.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hi @torhoehn, could you please check the automated tests failures?

**Comment by torhoehn** [comment]
@dmytro-ch Thanks for your review! All tests have passed now.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6236](https://jira.corp.magento.com/browse/ENGCOM-6236) has been created to process this Pull Request
:eight_spoked_asterisk: @dmytro-ch, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello @torhoehn, thank you for the updates.
Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) the changes should be covered by tests. Could you please cover your fix by automated tests?

**Comment by VladimirZaets** [comment]
@torhoehn , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6349](https://jira.corp.magento.com/browse/ENGCOM-6349) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
