### PR TITLE
Remove space between textarea field in contact form

### LINKED ISSUE #29779: [Issue] Remove space between textarea field in contact form
This issue is automatically created based on existing pull request: magento/magento2#29771: Remove space between textarea field in contact form

### Preconditions (*)
1. Magento 2.4

### Steps to reproduce (*)
Just clean code template. Remove space between textarea in contact form

### Expected result (*)
Just clean code template. Remove space between textarea in contact form

### Actual result (*)
space between textarea in contact form

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Just clean code template. Remove space between textarea in contact form

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29779: Remove space between textarea field in contact form

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8101](https://jira.corp.magento.com/browse/ENGCOM-8101) has been created to process this Pull Request
:eight_spoked_asterisk: @rogyar, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
**Notice:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** Tests were not run

**Comment by mrtuvn** [comment]
@magento run all tests

**Pull request merged**
