### PR TITLE
Fixed: Method chaining broken Module_Catalog Product Collection

### PR DESCRIPTION
**Pull request by mahesh-rajawat**
Fixed Issue: #24964 

### Description (*)

Fixed issue in this PR: Method chaining broken by refactor in Module_Catalog Product Collection
### Fixed Issues (if relevant)

1. magento/magento2#24964

### Manual testing scenarios (*)

1. Create an instance of \Magento\Catalog\Model\ResourceModel\Product\Collection
2. Call the method addAttributeToFilter with attribute is_saleable
3. Chain the method addAttributeToFilter with any other attribute to chain the function.
4. Chaining is working properly.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by omegades — COMMENTED** [review]
hi maheshWebkul721,

Thank you for the fix, however this does not fix my issues with Porto on 2.3.3 :)

2019/10/11 11:15:47 [error] 1567#1567: *240 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Catalog\Model\ResourceModel\Product\Collection::addIsSaleableAttributeToFilter() must b$
Stack trace:
#0 /var/www/domain.com/vendor/magento/module-catalog/Model/ResourceModel/Product/Collection.php(1582): Magento\Catalog\Model\ResourceModel\Product\Collection->addIsSaleableAttributeToFilter(1)
#1 /var/www/domain.com/app/code/Smartwave/Filterproducts/Block/Home/LatestList.php(56): Magento\Catalog\Model\ResourceModel\Product\Collection->addAttributeToFilter('is_saleable', 1, 'left')
#2 /var/www/domain.com/app/code/Smartwave/Filterproducts/Block/Home/LatestList.php(33): Smartwave\Filterproducts\Block\Home\LatestLis" while reading response header from upstream, client: 0.0.0.0, server: m3.$

**Comment by mahesh-rajawat** [comment]
@omegades , That's your third party module issue. you need to call `addIsSaleableAttributeToFilter` with the correct parameter type.

**Comment by omegades** [comment]
@maheshWebkul721 Thank you for the feedback :)

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6065](https://jira.corp.magento.com/browse/ENGCOM-6065) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by VladimirZaets** [comment]
Covered in the scope of https://github.com/magento/magento2/pull/25915

**Pull request merged**
