### PR TITLE
ISSUE-30880 - Add CSP entry to allow google analytics ajax

### LINKED ISSUE #30880: Google Analytics CSP Violation
### Preconditions (*)

1. Magento 2.4.0
2. Magento_Csp installed / enabled
3. Magento_GoogleAnalytics installed / enabled

### Steps to reproduce (*)

1. In admin store configuration, go to Sales / Google API > Google Analytics. Set Enabled = Yes and enter an Account Number.
2. Flush all caches and load a page on the store front (such as the home page).

### Expected result (*)

1. There are no console errors / failed assets or requests due to CSP violations.

### Actual result (*)

1. There is a console error regarding a CSP violation for an XHR request to https://www.google-analytics.com/j/collect. If CSP is in report-only mode, it's just a console error. If CSP is actually enforced, the XHR request is not executed.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by zaximus84**
### Description (*)
Google analytics scripts make ajax calls (to GA). With the existing CSP whitelist in the analytics module, these requests are blocked. This PR adds a CSP entry for connect-src to allow ajax requests to www.google-analytics.com

### Fixed Issues (if relevant)
1. Fixes magento/magento2#30880

### Manual testing scenarios (*)
1. Ensure that Magento_CSP is enabled and functional (content security policy headers appear in store front page responses). 
2. In store configuration, enable Google Analytics and set an account number.
3. Flush caches and visit the store front.
4. In the developer console, confirm that there is no error pertaining to an ajax call to https://www.google-analytics.com/j/collect.
5. In the network tab, confirm that there was a successful ajax call to https://www.google-analytics.com/j/collect.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8450](https://jira.corp.magento.com/browse/ENGCOM-8450) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @sidolov .
Could you put an appropriate label for test coverage?
Thanks!

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. In admin store configuration, go to Sales / Google API > Google Analytics. Set Enabled = Yes and enter an Account Number.
2. Flush all caches and load a page on the store front (such as the home page)ж
3. Open developer console:

**Before:** :heavy_multiplication_x:  Error:  Refused to connect to...



**After:** :heavy_check_mark: no error pertaining to an ajax call to https://www.google-analytics.com/j/collect.

Screenshot from 2020-11-12 13-27-14
Screenshot from 2020-11-12 10-52-00

**Comment by engcom-Alfa** [comment]
Hi @sidolov .
Could you put an appropriate label for test coverage?
Thanks!

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
