### PR TITLE
15863: [Forwardport] Refactored javascript code of admin notification modal popup

### PR DESCRIPTION
**Pull request by IvanPletnyov**
### Description 
Refactored code in [popup.phtml](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/AdminNotification/view/adminhtml/templates/system/messages/popup.phtml) and [popup.js](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/AdminNotification/view/adminhtml/web/js/system/messages/popup.js)

### Original pull request

[15341](https://github.com/magento/magento2/pull/15341) [Backport] Refactored javascript code of admin notification modal popup

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16216) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @IvanPletnyov. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on Pull Request changes
- `@magento-engcom-team give me new test instance` - deploy **NEW** test instance based on Pull Request changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy Vanilla Magento instance for Issue or Pull Request

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by VladimirZaets** [comment]
Hi @IvanPletnyov  , please, sign CLA, otherwise, we can't process your pull request

**Comment by VladimirZaets** [comment]
@magento-engcom-team give me {2.3-develop} instance

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-2039](https://jira.corp.magento.com/browse/ENGCOM-2039) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@IvanPletnyov thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @IvanPletnyov. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.6 release.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
