### PR TITLE
#19016 - Double extension point of product conversion service.

### PR DESCRIPTION
**Pull request by chrom**
Fix double extension point of product conversion service when generating simple products through the wizard in product page.
https://github.com/magento/magento2/issues/19016

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19028) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @chrom. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by chrom** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @chrom. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @chrom, here is your [new Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-19028/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-19028//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-19028//admin)
Login: `admin` Password: `123123q`

**Review by orlangur — CHANGES_REQUESTED** [review]
Hi @chrom, please apply requested changes from https://github.com/magento/magento2/pull/19042. Somehow I overlooked the 2.3 PR.

**Comment by orlangur** [comment]
Closing as this PR does not seem to achieve goal described in issue: having a single product type conversion extension point.

Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened. Thanks for collaboration!

**Pull request closed without merging**
