### PR TITLE
To make it possible to change the existing customer group

### PR DESCRIPTION
**Pull request by WaPoNe**
### Description (*)
 This commit is necessary to make it possible to change the existing customer group.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @WaPoNe. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](https://i-22014-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22014-2-3-develop.instances.magento-community.engineering/admin](https://i-22014-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rogyar** [comment]
Hi @WaPoNe. Thank you for your collaboration. I've just tried to reproduce the mentioned issue on the current 2.3-develop branch.

**Steps to reproduce**
- Create a new customer
- Export customer data to a CSV file
- Changed customer group field value in CSV file
- Import customer data from CSV file using update strategy

**Expected result**
Customer group is changed 

**Actual result**
Customer group is changed 

So, I found no issues with changing customer group using import. 
Probably, the steps to reproduce require addiitonal preconditions. If you still think that the issue exists, please, create an issue in the current repository with all details described and mention this issue in the description of current PR. 

Thank you.

**Comment by sidolov** [comment]
@WaPoNe , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
