### PR TITLE
[Forwardport] Category\Collection::joinUrlRewrite should use the store set on the collection

### PR DESCRIPTION
**Pull request by rostyslav-hymon**
### Original Pull Request 
 https://github.com/magento/magento2/pull/13716 + https://github.com/magento/magento2/pull/14385
The problem is that Magento\Catalog\Model\ResourceModel\Category\Collection::joinUrlRewrite always use the store id from the store manager. I think that it should instead use the storeId set on the actual collection.

### Description

Now joinUrlRewrite uses directly the storeManager, but if a store is set directly on the collection, it should use the store set, and not the default passed by the store manager.
The method getStoreId(), if not set, already goes on fallback to the store manager and get the default, so it should be safe to directly use getStoreId().

### Fixed Issues (if relevant)

1. magento/magento2#13704: Category\Collection::joinUrlRewrite should use the store set on the collection

### Manual testing scenarios

I already provided an automated unit test. There is an code example in the related issue magento/magento2#13704.
It's my first automated test here, so I hope it's ok :)

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Hi @rostyslav-hymon, could you add also changes from https://github.com/magento/magento2/pull/14385?

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
Hi @rostyslav-hymon, I added commit from https://github.com/magento/magento2/pull/14385 myself and approved your PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-1103](https://jira.corp.magento.com/browse/ENGCOM-1103) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @rostyslav-hymon. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.3.0 release.

**Pull request merged**
