### PR TITLE
Resolve "Number of results" and "Number of Uses" in edit "Search Term" missing validate number (issue 24100)

### LINKED ISSUE #24100: "Number of results" and "Number of Uses" in edit "Search Term" missing validate number
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to frontend
2. At the right top, in "Search Entire Store Here", enter "gggg", and search
3. Go to Backend
4. Marketing->Search Terms
5. Choose record "gggg"
6. In "Number of results" and "Number of Uses", fill "one"
7. Click "Save Search"

image

### Expected result (*)

1. Don't allow to save
### Actual result (*)

1. Can save normally

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#24100: "Number of results" and "Number of Uses" in edit "Search Term" missing validate number 

Solution: Add class "required-entry validate-digits validate-zero-or-greater" in `app/code/Magento/Search/Block/Adminhtml/Term/Edit/Form.php`

### Fixed Issues (if relevant)

1. magento/magento2#24100: "Number of results" and "Number of Uses" in edit "Search Term" missing validate number 

### Manual testing scenarios (*)

1. Go to frontend
2. At the right top, in "Search Entire Store Here", enter "gggg", and search
3. Go to Backend
4. Marketing->Search Terms
5. Choose record "gggg"
6. In "Number of results" and "Number of Uses", fill "one"
7. Click "Save Search"

image

#### Expected result 
1. Don't allow to save

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-24101.instances.magento-community.engineering).
Admin access: [https://pr-24101.instances.magento-community.engineering/admin](https://pr-24101.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-5587](https://jira.corp.magento.com/browse/ENGCOM-5587) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
