### PR TITLE
Update page-cache.js

### PR DESCRIPTION
**Pull request by devdesco-ceo**
Fix Bug: page-cache.js:40 «Uncaught TypeError: element.prop is not a function»
Reference: https://mage2.pro/t/topic/999

### CODE REVIEW

**Comment by daim2k5** [comment]
@devdesco-ceo Thank you for your contribution. Please accept the contributors license agreement so this PR can be further processed. This can be done by clicking the "Details" link next to the "license/cla" check below.

**Comment by mazhalai** [comment]
@devdesco-ceo can you please resync with develop and restart builds?

**Comment by devdesco-ceo** [comment]
Can't figue out how to resync with base

**Comment by piotrekkaminski** [comment]
@devdesco-ceo https://help.github.com/articles/syncing-a-fork/ ?

**Comment by irenelagno** [comment]
hi! @devdesco-ceo,
thank you for contribution. Please fix [failing builds](https://travis-ci.org/magento/magento2/builds/123626782).
Internal ticket MAGETWO-56693 was created to process your PR.

**Comment by aakimov** [comment]
Hi @devdesco-ceo, 

This pull request will be closed as duplicate of https://github.com/magento/magento2/pull/4022.

Thank you for your understanding and interest in Magento.

**Comment by Apurva025** [comment]
@devdesco-ceo,  @daim2k5 ,
Hello All,

After applying fix as     .prop('href', element.src)

**New JS  error is appearing:**
Error: Permission denied to access property "document"
elem.contentDocument || elem.contentWindow.document :     jquery.js (line 2998, col 1)

image

**Comment by adragus-inviqa** [comment]
@Apurva025 - https://github.com/magento/magento2/pull/4496#issuecomment-244497968

**Comment by Apurva025** [comment]
@adragus-inviqa,

This isn't working.
(function lookup(element) {
 if ($.nodeName(element, "iframe") && $(element).prop('src').indexOf(window.location.hostname) != -1) { return; } 
Its giving same error:
Error: Permission denied to access property "document"
elem.contentDocument || elem.contentWindow.document : jquery.js (line 2998, col 1)


Now if I change above code as:
 if ($.nodeName(element, "iframe") ) { return; } 

that is removing  **&& $(element).prop('src').indexOf(window.location.hostname) != -1**
This is working for me.

Can, I remove this condition  "&& $(element).prop('src').indexOf(window.location.hostname) != -1" ?
Is there any other way of checking above condition
 "&& $(element).attr('src').indexOf(window.location.hostname) != -1" is also giving error.

**Comment by Apurva025** [comment]
@adragus-inviqa,

These both are working 

1.     **($.nodeName(element, "iframe") ) { return; }**
Or 
2.     **if ($.nodeName(element, "iframe")  && $('iframe').prop('src').indexOf(window.location.hostname) != -1) { return; }**

**Pull request closed without merging**
