### PR TITLE
Multiple Inventory Architectural Proposal

### PR DESCRIPTION
**Pull request by IvanChepurnyi**
As a result of long discussions in original ticket Multinode Inventory #473 and my proposed [description](https://gist.github.com/IvanChepurnyi/70fcea1793db4b22c7fe) of implementation, I've prepared the following architecture proposal. 
## Main Idea

Separate Inventory from G/W/S direct relation in Magento and provide a possibility for a merchant to manage multiple warehouses/supplier in a simple and transparent way.
## Entities

At the following chart, a general relation between them is described
Relation of Entities
- **Inventory**, **Inventory Record** are immutable analogs of **Warehouse** and **Warehouse Record** accordingly.
- **Inventory Configuration** uses **Scope Configuration** as a dependency. **Inventory Record Configuration** uses **Inventory Configuration** as a dependency. So fallback of configuration values is done from top to bottom, and each entity should use own configuration instance if there is a record in the database for it. 
  For example:
  There are 2 Inventory Records, one of them has associated database record. In this case entity repository should create Inventory Record Configuration instance for the first item and use Inventory Configuration for the second. Also, Inventory Record Configuration must be instantiated with Inventory Configuration supplied as a dependency.
- **Inventory Reservation** entity created to realize atomic stock operations, as current implementation in Magento makes the deduction of it as a matter of chance to get below minimum reservation quantity.
- **Inventory Index Record** entity contains almost the same properties as **Inventory Record**, but it can include aggregated information from multiple records, so it is not One to One relation, and it shouldn't contain record identifier.
## Matching Inventory for Current Scope

As new implementation does not have a direct connection to a store or a website in Magento, the process of locating available Inventory for all products in specified scope (Store, Website, etc.) is done in _InventoryManagementInterface_. 
### Product Collection

Product Collection Flow
### Product View

Product View Flow

One product view it is already an overhead to find initial inventory and then inventory record, so registry should return inventory record for all specified product identifiers. The system should provide only product identifiers for wich inventory records are required. For composite products (grouped, configurable), it should supply currently enabled and visible child product identifiers.
### Shopping Cart

Shopping Cart Flow

As seen from the above chart, the system should retrieve InventoryRecords separately for each deliverable item within the shopping cart. A deliverable item is a combination of quote item and shipping address. Based on this deliverable item a new instance of **InventoryRecordCriteriaInterface** should be created to decouple inventory from quote module. 

Based on criteria object an **InventoryRecordCollectionInterface** with one Inventory Record or more is returned per each product in the request. Depending on **isMultipleInventory()** of criteria there can be retrieved multiple or single inventory records for the same product, but multiple records only should be returned if a single Inventory can not fulfil delivery. 

Every combination of composite product should be requested as a separate **InventoryRecordCriteriaInterface** with **isMultipleInventory()** flag set to false. For instance if we have quantity 2 for a bundle product in the cart, then the system should create two separate request objects. 

**InventoryValidatorInterface** is used to validate response from **InventoryManagementInterface** and its **suggestRequest()** method should be used to propose a correct quantity for a specific Inventory Record. This logic at the moment is duplicated in various locations, so by introducing criteria/collection pair for inventory validation it will make it more transparent and managed in a single place.
### Inventory Reservation

This new entity is introduced to make stock changes atomic and without deadlocks. It also gives great possibility to track inventory changes in the system without complex database operation with order items.

Each Inventory Reservation should have a status. There are six different statuses of reservation in proposed interface:
- `STATUS_NEW` -  it is created to have a state in between order creation and inventory deduction. At the following status, nothing is deducted from Inventory Record
- `STATUS_CONFIRMED` - it is created to deduct actual quantity from inventory record and change its status if needed. The operation of deduction should be a single database query for all order reservation. In case if resulting quantity of an item is lower than allowed, `STATUS_ERROR` should be set on the reservation. If confirmed reservation did not complete after some period, it should be canceled.
- `STATUS_COMPLETE` - it is created to tell the system that it is not possible to cancel it anymore. It is set when customer completes payment.
- `STATUS_RETURNED` - it is created to process credit memos, returns, void (cc auth). When reservation reaches this state quantity is returned into Inventory Record.

Inventory Reservation instance is immutable, so every response from **InventoryReservationManagementInterface** returns a new object instance with same id, but changed status. So do not forget to update object references within appropriate objects.

Process of placing the order in relation to inventory reservation:
Order Creation Flow

_Side note
It is possible to update inventory record and inventory reservation within the same `UPDATE` query in MySQL, so operation will be atomic and will increase the number of orders/second in Magento._

Process of Void/Refund/Return:
Return Flow

All the flow charts in this pull request description you can find at the following URL:
https://www.lucidchart.com/documents/view/f0242fbd-55bb-4339-acfe-9b7295aa84b2

### CODE REVIEW

**Comment by naspar** [comment]
You are a star!
Thanks for sharing such useful and detailed explanation.

**Comment by seansan** [comment]
Impressive!

**Comment by webkul** [comment]
Brilliant Thanks for sharing .

**Comment by magento-cicd** [comment]
We have automated a Magento Contributor License Agreement verifier for contributions sent to our GitHub projects.
Please see the CLA agreement in the Pull Request comments below.

**Comment by IvanChepurnyi** [comment]
CLA signed!

**Comment by centerax** [comment]
Is this going to be merged ?

**Comment by mbrinton01** [comment]
A version of Multi-Node inventory based on this feedback is being developed.  There are some differences in the approach but this feedback was included in the design.

**Comment by vrann** [comment]
@IvanChepurnyi this research was taken as a basis for multi-node inventory management in Magento and had the key impact on the architectural design. While I'm closing this PR, the work on the multiple inventory is still in progress.

**Comment by scottsb** [comment]
@vrann Will the new functionality be available in Community Edition?

**Comment by seansan** [comment]
Naturally ;) much of the input was provided by the community ...

**Comment by mbrinton01** [comment]
@scottsb @seansan I don't have the answer at this point in development, we will announce more when it's closer to being in a release state

**Comment by maghamed** [comment]
Hey @scottsb @seansan now Multi Source Inventory (MSI) is a community project being developed by community engineers which development is orchestrated by Magento Community Engineering team.
You can track the project status on the GitHub - https://github.com/magento-engcom/magento2/wiki

For now, it's decided that MSI going to be a new evolutionary way of development Catalog Inventory we have in Magento 2. And all the multi sourcing support would be available in Community Edition

**Pull request closed without merging**
