### PR TITLE
Update Template.php

### PR DESCRIPTION
**Pull request by liam-wiltshire**
Updating the comment to reflect that in .phtml files $block is used rather than $this

### CODE REVIEW

**Comment by liam-wiltshire** [comment]
Reported in Issue #2785

**Comment by davidalger** [comment]
Thank you for the PR! We are currently waiting for the travis builds to work again, which should happen in a few days. Once that is running and the tests are green we can continue to process your contribution. In the mean time, can you please sign the contributor license agreement? You can do this by following the "Details" link next to the "license/cla" check below. Thanks!

**Comment by liam-wiltshire** [comment]
Thanks @davidalger, cla signed!

**Comment by mazhalai** [comment]
@liam-wiltshire Please merge latest from develop and rerun builds.

**Comment by vkorotun** [comment]
Internal ticket: MAGETWO-56557

**Pull request merged**
