### PR TITLE
Magento backend catalog MSRP without currency symbol

### PR DESCRIPTION
**Pull request by mage2pratik**
### Description (*)

Fixed Magento backend catalog "MSRP" without currency symbol.

### Fixed Issues (if relevant)

1. magento/magento2#21910: Magento backend catalog "MSRP" without currency symbol

### Manual testing scenarios (*)

1. Admin Menu > Stores > Settings > Configuration > Sales > Minimum Advertised Price = Yes
2. Navigate to admin catalog product grid
3. Using "Columns" selection, add 'Manufacturer's Suggested Retail Price'(MSRP) column in the grid

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hi @mage2pratik!
I guess this column is not expected to be shown by default on Products listing.

**Comment by orlangur** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @orlangur. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @orlangur, here is your [new Magento instance](https://pr-21911.instances.magento-community.engineering).
Admin access: [https://pr-21911.instances.magento-community.engineering/admin](https://pr-21911.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by orlangur** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @orlangur. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @orlangur, here is your [Magento instance](https://i-21911-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21911-2-3-develop.instances.magento-community.engineering/admin](https://i-21911-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by orlangur — CHANGES_REQUESTED** [review]
Hi @mage2pratik!

Dmytro is right, also, please note that if such change would be valid, it should be placed in `Msrp` module.

Please fix the special price case in the same PR.

**Comment by orlangur** [comment]
@mage2pratik I believe you missed the `if such change would be valid` part. Current fix is not correct, no new column should be added to grid by default.

**Comment by sidolov** [comment]
Hi @mage2pratik , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
