### PR TITLE
Add missing order_data array to EmailSender classes

### LINKED ISSUE #29604: [Issue] Add missing order_data array to EmailSender classes
This issue is automatically created based on existing pull request: magento/magento2#27454: Add missing order_data array to EmailSender classes

---------
### Summary (*)
Magento 2.4-develop
Magento 2.3.4 now recommends using scalar variables instead of objects within the email templates. Unfortunately, not all classes were migrated. For example, [\Magento\Sales\Model\order\Email\Sender\ShipmentSender](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/Order/Email/Sender/ShipmentSender.php) was given the new array, despite now it being deprecated, but its replacement, [\Magento\Sales\Model\Order\Shipment\Sender\EmailSender](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/Order/Shipment/Sender/EmailSender.php) did not.

This change was introduced in commits like https://github.com/magento/magento2/commit/fd721b157fc7034ff4d209c2bafd70d151d88f47#diff-7b993c70d2652919564eeaf30afe7326. Several more do change the email templates to use `order_data` instead.

### Examples (*)

1. Create a shipment email template using `{{order_data.is_not_virtual}}` (as opposed to `{{order.is_not_virtual}}`);
2. Send it programatically using `\Magento\Sales\Model\Order\Shipment\Sender\EmailSender`;

### Proposed solution

### PR DESCRIPTION
**Pull request by kassner**
### Description

Magento 2.3.4 now recommends using scalar variables instead of objects within the email templates. Unfortunately, not all classes were migrated. For example, [\Magento\Sales\Model\order\Email\Sender\ShipmentSender](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/Order/Email/Sender/ShipmentSender.php) was given the new array, despite now it being deprecated, but its replacement, [\Magento\Sales\Model\Order\Shipment\Sender\EmailSender](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Model/Order/Shipment/Sender/EmailSender.php) did not.

This change was introduced in commits like https://github.com/magento/magento2/commit/fd721b157fc7034ff4d209c2bafd70d151d88f47#diff-7b993c70d2652919564eeaf30afe7326. Several more do change the email templates to use `order_data` instead.

### Manual testing scenarios

1. Create a shipment email template using `{{order_data.is_not_virtual}}` (as opposed to `{{order.is_not_virtual}}`);
2. Send it programatically using `\Magento\Sales\Model\Order\Shipment\Sender\EmailSender`;

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29604: Add missing order_data array to EmailSender classes

### CODE REVIEW

**Review by edenduong — CHANGES_REQUESTED** [review]
Hi @kassner: Could you please sign Adobe CLA? And arcording to Magento DOD, please cover your changes by Unit Test. Thank you very much!

**Comment by sidolov** [comment]
@magento create issue

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8087](https://jira.corp.magento.com/browse/ENGCOM-8087) has been created to process this Pull Request

**Review by edenduong — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @edenduong, thank you for the review.
[ENGCOM-8087](https://jira.corp.magento.com/browse/ENGCOM-8087) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Manual testing scenario:**

- Create email template for invoice with additional rows in template
 image
- Set template for Invoice Email Template and Invoice Email Template for Guest
- Order simple product as guest
- Create invoice for order
- Send invoice email programatically using `Magento\Sales\Model\Order\Invoice\Sender\EmailSender`

**Result:**
:x: **Before:**
No customer name(depends on `order_data.customer_name`) and shipping address(depends on `order_data.is_not_virtual`) in email for simple product
image


:heavy_check_mark: **After:**
Customer name, custom node and shipping information is displayed in invoice email for simple product
image

**Comment by engcom-Delta** [comment]
**Note:** Functional Tests B2B and Functional Tests EE are failed

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Pull request merged**
