### PR TITLE
Special Price shown without currency symbol in magento backoffice

### PR DESCRIPTION
**Pull request by XxXgeoXxX**
Base issue: https://github.com/magento/magento2/issues/20472

### Description (*)
Magento 2.3.X
Magento 2.2.X

#### Steps to reproduce (*)
Navigate to admin catalog product grid
Using "Columns" selection add 'Special Price' column in the grid
#### Expected result (*)
Special Price will be shown with currency code

#### Actual result (*)
Special Price showed without currency code. 

### Manual testing scenarios (*)
Navigate to admin catalog product grid
Using "Columns" selection add 'Special Price' column in the grid

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3928](https://jira.corp.magento.com/browse/ENGCOM-3928) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [new Magento instance](https://pr-20474.instances.magento-community.engineering).
Admin access: [https://pr-20474.instances.magento-community.engineering/admin](https://pr-20474.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sivaschenko** [comment]
Hi @XxXgeoXxX , thanks for the pull request, can you please check the test instance: Special Price column is empty.

**Comment by XxXgeoXxX** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX, here is your [new Magento instance](https://pr-20474.instances.magento-community.engineering).
Admin access: [https://pr-20474.instances.magento-community.engineering/admin](https://pr-20474.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by XxXgeoXxX** [comment]
Hi @sivaschenko 
updated PR. Looks like magento skips values for some column when you enable it this column in BO->Products->Columns but it xml use <addField>false</addField> and show them only after some event(click/sort per this column)

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3928](https://jira.corp.magento.com/browse/ENGCOM-3928) has been created to process this Pull Request

**Comment by sidolov** [comment]
@XxXgeoXxX , please, resolve merge conflicts

**Comment by XxXgeoXxX** [comment]
HI @sidolov
merge conflict was resolved

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3928](https://jira.corp.magento.com/browse/ENGCOM-3928) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminUserSetStatusForEachSourceItemTest functional test is failing on this pull request

**Comment by nmalevanec** [comment]
> Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminUserSetStatusForEachSourceItemTest functional test is failing on this pull request

@sivaschenko I've created PR to MSI repository, to fix mentioned above test https://github.com/magento-engcom/msi/pull/2068

**Comment by ishakhsuvarov** [comment]
@sivaschenko @nmalevanec https://github.com/magento-engcom/msi/pull/2068 is now merged.

**Comment by sivaschenko** [comment]
`Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.AdminUserSetStatusForEachSourceItemTest` is failing on this pull request

    Failed asserting that any element by '//tr[1]//td[count(//div[@data-role='grid- 
    wrapper']//tr//th[normalize-space(.)='Quantity']/preceding-sibling::th) +1 ]' on page 
    /admin/catalog/product/index/store/0/
    Elements: 
    + <td> 
    contains text '100'

image

**Review by orlangur — CHANGES_REQUESTED** [review]
@XxXgeoXxX please elaborate a proper fix, see https://github.com/magento/magento2/issues/20906#issuecomment-479692859.

**Comment by sidolov** [comment]
@XxXgeoXxX , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
