### PR TITLE
#33220 memorize toolbar parameters for catalogsearch

### LINKED ISSUE #33220: search result sorting broken when "Remember Category Pagination" is enabled
### Preconditions (*)

1. Magento 2.4.2-p1 with sample data

### Steps to reproduce (*)

1. Go to Stores > Configuration > Catalog > Catalog > Storefront
2. Enable "Remember Category Pagination"
3. Go to frontend and search for something (e.g. "bag")
4. Sort defaults to "Relevance". Change to "Price".
5. Clicik the arrow to sort by price desc/asc.

### Expected result (*)

1. Search result should still be sorted by price. 

### Actual result (*)

1. The sort defaults back to Relevance. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by vovsky**
### Description (*)
This PR fixes toolbar sorting issues on Search pages if Remember Category Pagination is enabled.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#33220

### CODE REVIEW

**Comment by vovsky** [comment]
@magento run all tests

**Comment by bgorski** [comment]
It looks like you are improving Catalog Search here. Why have you placed your code in Catalog instead?

**Comment by bgorski** [comment]
@magento run Functional Tests B2B

**Review by bgorski — CHANGES_REQUESTED** [review]
@vovsky thank you for your contribution!
It looks like you are improving Catalog Search here. Why have you placed your code in Catalog instead?
Also, can you cover your fix with an integration test?

**Comment by mrtuvn** [comment]
@bgorski @vovsky 
I think that maybe difference case since in module catalog we have plugin for that too
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Plugin/Framework/App/Action/ContextPlugin.php#L58
Anyone know this ? Seem in catalog we already add some code related with memorize toolbar

**Comment by Den4ik** [comment]
@bgorski You opinion make sense and I also preferrer move changes into `CatalogSearch` module due to depends of this module from `Catalog` module.
@mrtuvn Plugin moving data from catalog session to http context and execute after predispatch observers and in this case all looks good for me.
@vovsky Please also add some tests for you changes.

**Comment by engcom-Bravo** [comment]
@vovsky @Den4ik @bgorski and @mrtuvn  Thanks for your contribution!
@vovsky  I am working on the requested changes.

**Comment by engcom-Bravo** [comment]
Since this changes default search behaviour and from functionality perspective this is a breaking change for merchants, and it might break some extensions and customizations. So, moving this pull request on hold until we get confirmation.

**Comment by sdzhepa** [comment]
@engcom-Bravo  

Do you have any updates on this PR? was it approved or not?

**Comment by engcom-Charlie** [comment]
On [this](https://github.com/magento/magento2/pull/33421#issuecomment-919740670) we are still waiting for the updates so moving this PR to on hold status.

Thank you!

**Comment by engcom-Hotel** [comment]
Hello,

We are still under discussion on this PR. Will keep you posted accordingly.

Thanks

**Review by bgorski — APPROVED** [review]

**Comment by bgorski** [comment]
@engcom-Hotel this is not a breaking change. If by breaking you meant that search functionality will start reacting to how regular categories are sorted, then this is already happening without this PR. The only thing that's added here is a fix for search results to also be able to affect the sorting param memorization instead of always defaulting to what was selected on categories. Of course that also means that categories will also retain the param set on search results, but I would say that's an improvement in UX. If as a customer you want to go for the cheapest product for example, then you want both categories and search to show you this kind of sorting without having to set it twice.

Apart from that, I moved the PR functionality to the CatalogSearch module myself, and then approved.

**Comment by bgorski** [comment]
@magento run all tests

**Review by Den4ik — APPROVED** [review]
Checked locally and don't see any issues

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

- Go to `Stores > Configuration > Catalog > Catalog > Storefront`
- Enable "Remember Category Pagination"
- Go to frontend and search for something (e.g. "bag")
- Sort defaults to "Relevance". Change to "Price".
- Clicik the arrow to sort by price `desc/asc`.

**Before:** :heavy_multiplication_x: The sort defaults back to Relevance
Before_PR


**After:** :heavy_check_mark:  Search result should still be sorted by price.
After_PR

Builds are failing.Hence, moving this PR to **Extended Testing**

**Comment by glo71317** [comment]
Working on delivery internally along with these changes

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-7698 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-8904&type=commits

Based on the Jira ticket, the target version is 2.4.7-beta2.

Thanks

**Pull request merged**
