### PR TITLE
MC-35717: Admin can not add a Product with a Customizable Option (File) to Order by SKU

### LINKED ISSUE #30285: Admin can not add a Product with a Customizable Option (File) to Order by SKU
**Preconditions:**
* Magento EE 2.3.5-p1, EE 2.4.0-beta1 
* A Simple Product with a Customizable Option File is created (for example, Customizable Options -> Option Title = "TEST OPTION 1", Option Type = File, Compatible File Extensions = jpg, Maximum Image Size = 1000 x 1000 px)

**Steps to Reproduce:**
* Go to the Magento Admin Panel > Sales > Orders
* Click the “Create New Order” button
* Click the “Create New Customer” button
* Click the “Add Products By SKU” button
* Enter SKU of the created Product into the “SKU number” input field
* Enter some valid quantity into the “Qty” input field
* Click the “Add to Order” button
* Click the “Configure” button under the name and the SKU of the created Products
* Click the “Choose File” button on the appeared “Configure Product” page
* Select a valid file
* Click the “OK” button
* Click the “Add Products to Order”

**(/) Expected results:**

The Product should appear in the “Items Ordered” grid

**(x) Actual results:**
* There are no products in the “Items Ordered”
* “1 product(s) require attention.” warning message appears in the grid
 “You need to choose options for your item.”appears under the Product name and SKU
* “Remove” button does not work

### PR DESCRIPTION
**Pull request by SmVladyslav**
### Related Pull Requests

magento/partners-magento2ee/pull/427

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30285 (MC-35717)

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by SmVladyslav** [comment]
@magento run all tests

**Comment by SmVladyslav** [comment]
@magento run Database Compare, Functional Tests B2B, Functional Tests CE, WebAPI Tests

**Comment by rogyar** [comment]
@magento run  Functional Tests B2B, Functional Tests CE

**Comment by SmVladyslav** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by SmVladyslav** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by SmVladyslav** [comment]
@magento run all tests

**Comment by SmVladyslav** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by SmVladyslav** [comment]
@magento run all tests

**Comment by SmVladyslav** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Unit Tests

**Comment by SmVladyslav** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by SmVladyslav** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by SmVladyslav** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by SmVladyslav** [comment]
@magento run Functional Tests B2B

**Comment by SmVladyslav** [comment]
@magento run Functional Tests B2B

**Review by zakdma — APPROVED** [review]

**Comment by SmVladyslav** [comment]
@magento run all tests

**Comment by engcom-Oscar** [comment]
:heavy_check_mark: QA passed

Tested by next scenario:

* A Simple Product with a Customizable Option File is created (for example, Customizable Options -> Option Title = "TEST OPTION 1", Option Type = File, Compatible File Extensions = jpg, Maximum Image Size = 1000 x 1000 px)
* Go to the Magento Admin Panel > Sales > Orders
* Click the “Create New Order” button
* Click the “Create New Customer” button
* Click the “Add Products By SKU” button
* Enter SKU of the created Product into the “SKU number” input field
* Enter some valid quantity into the “Qty” input field
* Click the “Add to Order” button
* Click the “Configure” button under the name and the SKU of the created Products
* Click the “Choose File” button on the appeared “Configure Product” page
* Select a valid file
* Click the “OK” button
* Click the “Add Products to Order”

:x: **Before:**
* There are no products in the “Items Ordered”
* “1 product(s) require attention.” warning message appears in the grid
 “You need to choose options for your item.”appears under the Product name and SKU
* “Remove” button does not work

:heavy_check_mark: ** After applying PR:**

**Comment by SmVladyslav** [comment]
@magento run Functional Tests B2B

**Comment by SmVladyslav** [comment]
@magento run Functional Tests B2B

**Comment by SmVladyslav** [comment]
@magento run Functional Tests B2B

**Review by zakdma — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Comment by SmVladyslav** [comment]
@magento run all tests

**Comment by SmVladyslav** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

**Review by zakdma — APPROVED** [review]

**Comment by SmVladyslav** [comment]
@magento run Functional Tests CE

**Comment by SmVladyslav** [comment]
@magento run Functional Tests CE

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31055`.

**Pull request merged**
