### PR TITLE
Update di.xml to support MariaDB 10.5.x

### LINKED ISSUE #31109: MariaDB 10.5 support
### Preconditions (*)
1. Magento 2.4.1
2. Debian Server upgraded to bullseye with MariaDB 10.5.8

### Steps to reproduce (*)
1. bin/magento setup:upgrade

### Expected result (*)
1. setup:upgrade should not abort

### Actual result (*)
1. Error: Current version of RDBMS is not supported. Used Version: 10.5.8-MariaDB-3. Supported versions: MySQL-8, MySQL-5.7, MariaDB-(10.2-10.4)

It is possible to circumvent the version check with an override in module di.xml:

```
    <type name="Magento\Framework\DB\Adapter\SqlVersionProvider">
        <arguments>
            <argument name="supportedVersionPatterns" xsi:type="array">
                <item name="MariaDB-(10.2-10.5)" xsi:type="string">^10\.[2-5]\.</item>
            </argument>
        </arguments>
    </type>
```
So far, no errors seem to occur with this hack. But i guess there will be some compatibility issues.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by tdgroot**
Update di.xml to support MariaDB 10.5.x

### Description (*)

Magento seems to already support MariaDB 10.5, but not explicitly yet.

### Related Pull Requests

* Follow up of #31499 (no CLA was signed for that PR)

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31109

### Manual testing scenarios (*)

Not sure what testing procedures Magento follows when a new db version is added.

1. Setup Magento on MariaDB 10.5
2. Run the application
3. Profit? 😄 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
Just curiously how changes with new mariadb affect to code

**Review by Den4ik — APPROVED** [review]
✅ Approved

I'm working on 10.5 and don't have issues. I hope core team can configure 10.5 for run tests before merge

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9109](https://jira.corp.magento.com/browse/ENGCOM-9109) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by gabrieldagama** [comment]
Hi @tdgroot, thanks for contributing! We acknowledge that Magento may be compatible with MariaDB 10.5, but it is not official and in order to accept such change we need to adjust our infrastructure and run the tests on the 10.5 version, that will be done eventually, but we cannot accept such contribution right now.

Follow here the docs with supported versions: https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

Thanks!

**Pull request closed without merging**
