### PR TITLE
MSI-430: Added additional container to shipment form for display extra shipment information (ex. Inventory data)

### PR DESCRIPTION
**Pull request by seruymt**
### Description
Added additional container to shipment form for display extra shipment information (ex. Inventory data)

### Fixed Issues (if relevant)

1. none

### Manual testing scenarios

1. none

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14731) <br/>All committers have signed the CLA.

**Comment by sidolov** [comment]
Hi @seruymt , looks like your commit email is different than in GitHub account, please, create a new commit with GitHub email and force push branch or add email from commit to your account.
Also, please, sign CLA, otherwise we can't process your pull request.

**Comment by seruymt** [comment]
Hi @sidolov, thanks for explanation, I've signed CLA

**Comment by magento-engcom-team** [comment]
@seruymt thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @seruymt. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.3.0 release.

**Pull request merged**
