### PR TITLE
#35275: Minicart thumbnail image showing wrong size in frontend which…

### LINKED ISSUE #35275: Minicart thumbnail image showing wrong size in frontend which is half of image size in XML file
After upgrading Magento version from 2.3.5-p1 to 2.4.3-p1, I am facing the problem of minicart thumbnail size. I found that in the view.xml file, the width and height of half the size set for the minicart thumbnail shows in the frontend minicart. 

**Note:** It works fine in my old Magento version that the size which is in view.xml file shows the width and height of the size in the frontend.

### Preconditions (*)
1. Magento version 2.4.3-p1

### Steps to reproduce (*)

**Important:** By the way, this is the default issue in both Blank and Luma themes.

1. Create any one product and upload the thumbnail image of the product in it.
1. Go to Front End and add product to cart.
1. You will see thumbnail images of the product in the minicart.
1. If you inspect it, the image loads the same size as it would in **view.xml* but in the upper HTML tag *<span class="product-image-container">** takes half width and height attribute and due to that minicart design is breaking and showing small thumbnail image.
1. For example, if you enter the 150x150 width and height in the **view.xml** file, then it will show 75x75 px inline width and height attributes in the upper <span> HTML tag.
`<image id="mini*cart_product*thumbnail" type="thumbnail">
                <width>75</width>
                <height>75</height>
            </image>`

### Expected result (*)

1. Prodcut item width and height of the <span> tag should be 150px shown which is given in the **view.xml** file

### Actual result (*)

1. It is showing 75x75 px width & height in <span> tag. **See above screenshots**

## 
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- < > Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- < > Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- < > Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- < > Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- < > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

### PR DESCRIPTION
**Pull request by olegpola**
… is half of image size in XML

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35275

### Manual testing scenarios (*)

1. ...
3. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by olegpola** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@olegpola Can you please sign CLA?

**Comment by hostep** [comment]
This will fix https://github.com/magento/magento2/issues/35275 BTW, but I'm not convinced that this issue is actually valid. Maybe @engcom-Delta: can we try to get a product owner involved here in order to make sure this isn't accidentally merged in case the issue is found to not be valid...

**Comment by Viper9x** [comment]
Hi @olegpola this pull request is invalid and will be caused a new issue: the thumbnail image will have a double size.

In the changes in PR [24743](https://github.com/magento/magento2/pull/24743/) @dmdanilchenko changed the `width` (and `height`) in both HTML and XML files:
app/code/Magento/Catalog/view/frontend/web/template/product/image_with_borders.html
app/design/frontend/Magento/blank/etc/view.xml
app/design/frontend/Magento/luma/etc/view.xml
You can take a look at PR's changed files here: https://github.com/magento/magento2/pull/24743/files

You guys had this issue because you declared width and height for`<image id="mini_cart_product_thumbnail" type="thumbnail">` in your custom theme. But with the new change in PR [24743](https://github.com/magento/magento2/pull/24743/), the width and height size should be double. So issue #35275 is invalid.

Conclusion: The correct solution is double the size of height and width for `<image id="mini_cart_product_thumbnail" type="thumbnail">` in <your theme dir>/etc/view.xml, not changing any from app/code/Magento/Catalog/view/frontend/web/template/product/image_with_borders.html.

**Comment by ihor-sviziev** [comment]
Hi @olegpola,
I do agree with @Viper9x, the image should be 2x sized, so the real size on the website should be 2x smaller.
I'm closing this PR as not valid.

**Pull request closed without merging**
