### PR TITLE
a miss spelling bug in Magento\Payment\Model\Method\Adapter

### PR DESCRIPTION
**Pull request by zzyycoder**
### Description (*)

fetchTransactionInfo method should use 'fetch_transaction_info' command code, not 'fetch_transaction_information'

### Fixed Issues (if relevant)

https://github.com/magento/magento2/issues/20139

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hostep** [comment]
@zzyycoder, maybe you can provide a bit more info, like what it fixes exactly, maybe exact steps to reproduce?
Also, is this related to https://github.com/magento/magento2/issues/20139?

**Comment by zzyycoder** [comment]
> @zzyycoder, maybe you can provide a bit more info, like what it fixes exactly, maybe exact steps to reproduce? Also, is this related to #20139?

yes it is related to #20139 
in order to allow my payment gateway to fetch transaction information, have to configure:
<can_fetch_transaction_information>1</can_fetch_transaction_information>
<can_fetch_transaction_info>1</can_fetch_transaction_info>

This must be a mistake~

**Comment by zzyycoder** [comment]
@magento run all tests

**Comment by 93kamikaze** [comment]
@magento run all tests

**Pull request closed without merging**
