### PR TITLE
Fix cannot change product type from downloadable to virtual by unchecking "Is this downloadable Product?

### LINKED ISSUE #24122: Cannot change product type from downloadable to virtual by unchecking "Is this downloadable Product?"
### Preconditions (*)

1. Downloadable Product 1
qty: 100500
status: enabled, IN_STOCK
weight: This item has no weight
links: no links, just samples
samples: 1 sample file

### Steps to reproduce (*)

1. Log in as Admin
2. Open Downloadable Product 1
3. Uncheck "Is this downloadable Product?"
4. Save the product

### Expected result (*)

1. Save is effective. 
2. I can buy a virtual product with that SKU
3. References to samples are kept in the database but the type_id and/or switcher prevents using this information almost like the weight is kept in the Virtual type of product. this gives an ability to switch back from virtual to downloadable smoothly without losing data
4. Alternative: if the first 2 options cannot be implemented, then Merchant receives alert or validation with instruction to remove links and samples first and only then Magento application allows to uncheck "Is this downloadable Product?"
Example:
image

### Actual result (*)

1. Save is not effective.
2. When I try to add product through API the product ~is out of stock~ behaves like a product that is out of stock (missing links) so it is still downloadable.
3. No alert. No validation. The checkbox "Is this downloadable Product?" is checked again, however, it was unchecked before save.
Peek 2020-08-10 19-16

### PR DESCRIPTION
**Pull request by deepaktiwariwebkul**
### Description (*)

Cannot change product type from downloadable to virtual by unchecking "Is this downloadable Product?"

### Fixed Issues (if relevant)

1. Fixes magento/magento2#24122 : Cannot change product type from downloadable to virtual by unchecking "Is this downloadable Product?

### Manual testing scenarios (*)

1. Open Downloadable Product
2. Uncheck the Is Downloadable Product Option.
3. Save the product.
4. Now the product becomes a Virtual product.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by krzksz** [comment]
Hey @deepaktiwariwebkul, can you take a look at failing tests?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @deepaktiwariwebkul,
Could you review failing tests and adjust tests / your code changes?
Thank you!

**Comment by gabrieldagama** [comment]
Risk is set to low since the changes may not affect other areas.

**Comment by engcom-Charlie** [comment]
@deepaktiwariwebkul could you please look through failed tests?
Thank you.

**Comment by engcom-Charlie** [comment]
@deepaktiwariwebkul could you please look through failed Integration tests? Looks like it caused by changes in your PR.
Thank you.

**Comment by engcom-Charlie** [comment]
Hi @deepaktiwariwebkul, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
