### PR TITLE
Added attribute crossorigin to head.xsd for linkTypes

### LINKED ISSUE #32509: Integrity and crossorigin with external stylesheets not working
### Preconditions (*)
1. Magento 2.3.0
2. PHP 7.1

### Steps to reproduce (*)
1. Edit `app/design/frontend/<Vendor>/<theme>/Magento_Theme/layout/default_head_blocks.xml`
2. Try to include a CDN CSS or JS like Bootstrap for example: `<link rel="stylesheet" src_type="url" src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"/>`
3. Error: attribute integrity and crossorigin not supported

### Expected result (*)
Ability to import external CSS and JS using modern methods and requirements

### Actual result (*)

Errors saying attributes integrity and crossorigin is not supported.

### PR DESCRIPTION
**Pull request by erfanimani**
### Description (*)

Allows the crossorigin attribute to be added to `link` types, for HEAD elements, in as per https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin

### Related Pull Requests

N/A

### Fixed Issues (if relevant)

These issues/features are related:

1. https://github.com/magento/magento2/issues/32509
2. https://github.com/magento/magento2/issues/21427
3. https://github.com/magento/magento2/issues/29513

### Manual testing scenarios (*)

1. Add `<css src="https://my.cdn.com/style.min.css" media="screen" src_type="url" crossorigin="anonymous"/>` to default_head_blocks.xml
2. Ensure crossorigin attribute is added correctly and doesn't break the site with an XSD error

### Questions or comments

There's probably already some work in the pipeline regarding this work, but I thought I would create a PR anyway as I need the diff for a patch.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @erfanimani,
Could you cover your changes with some kind of test?

**Comment by erfanimani** [comment]
Hi @ihor-sviziev, thanks for the feedback. I don't think a unit test or functional test is fitting for a pure XSD change. Do you have any suggestions?

**Comment by ihor-sviziev** [comment]
Yeah, it seems like we don't have any test coverage for XSD schemas. Let's not cover it.

@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved

Failing WebAPI tests looks not related to changes from this PR. The SVC failure probably should be approved additionally.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8929](https://jira.corp.magento.com/browse/ENGCOM-8929) has been created to process this Pull Request

**Comment by erfanimani** [comment]
Thanks all. I've also added the attribute integrity, as the referenced issue: https://github.com/magento/magento2/issues/32509

(https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Oscar** [comment]
@engcom-Foxtrot can you please check this PR.

**Comment by engcom-Foxtrot** [comment]
QA passed.

**Comment by engcom-Foxtrot** [comment]
Semantic Version Checker should be approved.

**Comment by engcom-Charlie** [comment]
Raised new internal approval request JIRA [ticket](https://jira.corp.adobe.com/browse/AC-6881) on adobe portal for MVC test failure. Waiting for the approvals.

Thank you!

**Comment by abhattGlo** [comment]
@magento run Semantic Version Checker

**Comment by engcom-Charlie** [comment]
@magento run Semantic Version Checker

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
As we got the [SVC](https://jira.corp.adobe.com/browse/AC-6881) approval mentioned in [here](https://github.com/magento/magento2/pull/32455#issuecomment-1286888081) and the build is green now moving this PR to Merge in Progress.

**Comment by erfanimani** [comment]
It took some time, but is finally happening :)

**Pull request merged**
