### PR TITLE
compliance to StorefrontMinicartSection

### LINKED ISSUE #27897: MFTF: Inconsistent case in Section name
`StorefrontMinicartSection` and `StorefrontMiniCartSection` are defined.
There should be consistency.

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

### PR DESCRIPTION
**Pull request by engcom-Echo**
### Description (*)
The tests are consistent with StorefrontMinicartSection. StorefrontMiniCartSection removed.

### Fixed Issues (if relevant)

1. magento/magento2#27897 : MFTF: Inconsistent case in Section name #27897

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by rogyar** [comment]
The failing test is not related to the current change

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7485](https://jira.corp.magento.com/browse/ENGCOM-7485) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Pull request merged**
