### PR TITLE
[forwardport] PR#12712 : Found 2 elements with non-unique id #email

### PR DESCRIPTION
**Pull request by julienanquetil**
### Description

Forwardport PR #12712
### Fixed Issues (if relevant)

1. magento/magento2#14850: Found 2 elements with non-unique id #email: magento 2 contact

### Manual testing scenarios

1. No duplicate alert in console : [DOM] Found 2 elements with non-unique id #email

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by okorshenko** [comment]
@magento-engcom-team give me new test instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento instance for you
 - [x] Sample Data
 - [x] Luma Theme

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [new Magento instance](https://pr-14867.engcom.dev.magento.com).
Admin access: [https://pr-14867.engcom.dev.magento.com/admin](https://pr-14867.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Please make sure you are PR **author** or **assignee** to access the instance.

**Comment by magento-engcom-team** [comment]
Hi @julienanquetil. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.3.0 release.

**Pull request merged**
