### PR TITLE
fix Same store name overriding in the store view grid filter

### LINKED ISSUE #29267: Same store name overriding in the store view grid filter
### Preconditions (*)

1. install the magento 2.3.5-p1, 2.4-develop

### Steps to reproduce (*)

1. create the new store view with same name "Default Store View"
issue1
2. now go to sales -> order grid or catalog -> product grid and open the filter and check the listed store view, It display only one store, which is not correct.

here is the screenshot

### Expected result (*)

1. It should display all the stores which is created, but currently it display only last store which is created. Its override the option with last option.
2. I have checked the code and its using the store name as the array key which should not be correct.

### Actual result (*)

1. It is displayed only last store which is created. Its override the option with last option. 
issue2

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

1. https://prnt.sc/to0p41
2. https://prnt.sc/to0p7z

### PR DESCRIPTION
**Pull request by engcom-Charlie**
### Description (*)

Fixed and covered by test

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29267

### Manual testing scenarios (*)

1. please see #29267

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7997](https://jira.corp.magento.com/browse/ENGCOM-7997) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Create the new store view with same name "Default Store View"

issue1
2. Go to Admin -> Sales -> order grid or catalog -> product grid;
3. Open the filter and check the listed store view

**Before:** :heavy_multiplication_x: It displays only one store, which is not correct.

Peek 2020-08-12 12-14

**After:** :heavy_check_mark: It displays all the stores which are created

Peek 2020-08-12 12-42

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@VladimirZaets 
Please approve changes in this Pull Request.
Thanks

**Comment by engcom-Kilo** [comment]
@sidolov 
Please review test coverage.
Thanks

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7997](https://jira.corp.magento.com/browse/ENGCOM-7997) has been created to process this Pull Request

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-7997](https://jira.corp.magento.com/browse/ENGCOM-7997) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA Passed

**Pull request merged**
