### PR TITLE
#33204 - Fixed: Reset button not working in user/customer form at adminpanel

### LINKED ISSUE #33204: Reset button in User form doesn't work when 2FA enabled
This issue is related to "Reset" button functionality of user form at admin panel. By default, this "Reset" button reloads page and navigate to "User Info" tab, but it stops working when two-factor authentication module(Magento_TwoFactorAuth) is enabled.

### Preconditions (*)
1. Installed magento 2.4, 2.4-develop
2. Two-Factor Authentication (2FA) must be enabled.

### Steps to reproduce (*)
1. Go to Admin.
2. Navigate to Systems > Permissions > All Users.
3. Select any user and open user edit page.
4. Click on "Reset" button.

### Expected result (*)
1. Page should reload.
2. If other tab is selected then it should reload page and returns to main "User Info" tab.

### Actual result (*)
Nothing happens on click of "Reset" button.
reset_button

### PR DESCRIPTION
**Pull request by AartiJogiya**
### Description (*)
This pull request contains the solution of the issue: #33204  -  "Reset" button in user form is not working. I have seen the same issue in customer edit form (Customers > All Customers > Edit customer page) as well. The solution applied in this pull request resolves both the issue as it is regarding reset button "id" which conflicts when there are two different forms (UI-component form and form created using block method) are used in the same page.

**Below is the explanation of the issue and applied solution:**
In Magento admin-forms, "Reset" button can be from either UI-components or using the block method. Both has difference in functionality however button "id" is same. Below are the two different "reset" button functions:

1. The reset button of UI-component form reloads page and sets intial values to form fields.
    - Associated file path: 
        - Magento/Ui/view/base/web/js/form/element/abstract.js (function name: reset)
        - Magento/Ui/view/base/web/js/form/adapter/buttons.js
          
2. The reset button of form which is created using the block method reloads and navigates to the main page.
    - Associated file path:
        - Magento/Backend/Block/Widget/Form/Container.php (line no: 105)

When any admin page contains both the forms (UI-component and block method), the "Reset" button doesn't work as its "id" is the same. I have changed the "id" of reset button in UI-component form to "reset_ui_form" which solves this issue.

### Fixed Issues (if relevant)
 1. Fixes magento/magento2#33204 - Reset button in User form doesn't work when 2FA enabled
 2. Fixes Reset button not working in customer edit page in admin panel.

### Manual testing scenarios (*)
 1. Enable two factor authentication module (Magento_TwoFactorAuth) and setup authentication. Login to admin panel and Navigate to Systems > Permissions > All Users. Select any user and open user edit form. Click on the Reset button and it will reload page.
 2. Navigate to Customers > All Customers > Edit customer page and click on reset button. It will reload page after applying this solution.
 3. In Customer/User edit form, Open other tabs in left section and click on reset button, It will reload page and navigate to first tab menu.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by srsathish92** [comment]
Hi @AartiJogiya, thank you for your contribution. Please make sure you covered your PR by some automated tests. In this case a MFTF test would a perfect match. Thank you.

**Comment by AartiJogiya** [comment]
@magento run all tests

**Review by Den4ik — CHANGES_REQUESTED** [review]
@AartiJogiya Thanks for work.
I'm agree with @srsathish92. Could you please cover changes by tests

**Comment by AartiJogiya** [comment]
@magento run all tests

**Comment by AartiJogiya** [comment]
@magento  run all tests

**Pull request closed without merging**
