### PR TITLE
Replace repetitive actions with Action Groups in AdminEditRelatedBundleProductTest, EnableDisableBundleProductStatusTest, AdminMassDeleteBundleProductsTest

### LINKED ISSUE #34313: [Issue] Replace repetitive actions with Action Groups in AdminEditRelatedBundleProductTest, EnableDisableBundleProductStatusTest, AdminMassDeleteBundleProductsTest
This issue is automatically created based on existing pull request: magento/magento2#34099: Replace repetitive actions with Action Groups in AdminEditRelatedBundleProductTest, EnableDisableBundleProductStatusTest, AdminMassDeleteBundleProductsTest

---------

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)
Tests are refactored according to the best practices followed by MFTF.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)
Tests are refactored according to the best practices followed by MFTF.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#34313: Replace repetitive actions with Action Groups in AdminEditRelatedBundleProductTest, EnableDisableBundleProductStatusTest, AdminMassDeleteBundleProductsTest

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento create issue
@magento run all tests

**Review by eduard13 — APPROVED** [review]

**Pull request merged**
