### PR TITLE
Fs/error on dob

### PR DESCRIPTION
**Pull request by sertlab**
This PR fixes this issue
https://github.com/magento/magento2/issues/26700

**How to test**
- Set DOB as a required during customer registration and try to register

**Actual Result**
Registration fails with message (under the calendar) "Please select a valid date"

**Expected Result**
Registration should be complete

**What changed**
preg_replace() modified in order moment js to accept the date format value
as it seems moment(date,'M/d/Y').isValid() returns false
but now moment(date,'M/dd/Y').isValid() returns true

### CODE REVIEW

**Comment by mrtuvn** [comment]
Can you cover your change with unit test ?

**Comment by sertlab** [comment]
> @sertlab Can you cover your change with unit test ?
> The last change of file Timezone in this PR
> #26701

some unit test coverage added to this .

**Comment by mrtuvn** [comment]
@sertlab Can you run test case for class
lib/internal/Magento/Framework/Stdlib/DateTime/Timezone.php
Add some case to scopeDateDataProvider in this class
https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Stdlib/Test/Unit/DateTime/TimezoneTest.php#L311

**Comment by bubasuma** [comment]
Hi @sertlab 
Although replacing `M/d/Y` by `M/dd/Y` works for `moment().isValid()`.  This is not really the moment JS equivalent of `M/d/Y`. See https://momentjs.com/docs/#/displaying/
I did some basic test with momentJS date formatting. See screenshot below
Screen Shot 2020-03-12 at 9 14 18 AM

I believe the momentJS equivalent of  `M/d/Y` should be `M/D/Y`. See screenshot below
Screen Shot 2020-03-12 at 9 25 07 AM

**Comment by bubasuma** [comment]
Hi @sertlab
Thank you for your contribution and collaboration!
Internal Magento team is working on this issue right now.

**Comment by bubasuma** [comment]
Hi @sertlab
Thank you for your contribution and collaboration!
The issue was fixed by Magento team.
The fix will be available with the upcoming 2.4.0 release.

**Pull request closed without merging**
