### PR TITLE
Update validation.js to properly indicate required fields for accessibility

### LINKED ISSUE #36617: [Issue] Update validation.js to properly indicate required fields for accessibility
This issue is automatically created based on existing pull request: magento/magento2#36257: Update validation.js to properly indicate required fields for accessibility

---------
**Steps to reproduce issue:**
1. Navigate to an address form on the site (e.g. _Account > My Account > Address Book > Add New Address_)
2. Inspect the street line 2 address form field

**Expected result:**
* The field will _not_ include the `aria-required="true"` property since it is not a required field

**Actual result:** 
* The field _does_ include the `aria-required="true"` property even though it is not a required field

**Technical details:**
* The issue appears to be in the selection of form fields to which the `aria-required="true"` attribute should be applied; it is filtering only by field type and not by required class as it should be.

**Contribution checklist (*)**
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by rsisco**
**Steps to reproduce issue:**
1. Navigate to an address form on the site (e.g. _Account > My Account > Address Book > Add New Address_)
2. Inspect the street line 2 address form field

**Expected result:**
* The field will _not_ include the `aria-required="true"` property since it is not a required field

**Actual result:** 
* The field _does_ include the `aria-required="true"` property even though it is not a required field

**Technical details:**
* The issue appears to be in the selection of form fields to which the `aria-required="true"` attribute should be applied; it is filtering only by field type and not by required class as it should be.

**Contribution checklist (*)**
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36617: Update validation.js to properly indicate required fields for accessibility

### CODE REVIEW

**Comment by rsisco** [comment]
@magento give me 2.4-develop instance
@magento give me test instance

**Comment by rsisco** [comment]
@magento give me 2.4-develop instance

**Comment by rsisco** [comment]
@magento run all tests

**Comment by rsisco** [comment]
It looks like the functional tests are failing for most (all?) pull requests right now, so I am marking the task as completed because there is no reason to believe that the failures are related to the work in this PR.

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B , Functional Tests CE ,Functional Tests EE

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B , Functional Tests CE ,Functional Tests EE

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B , Functional Tests CE ,Functional Tests EE

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento `2.4-develop`

**Manual testing scenario:**

1. Navigate to an address form on the site (e.g. Account > My Account > Address Book > Add New Address)
2. Inspect the street line 2 address form field

**Before:** :heavy_multiplication_x: 
The field will not include the aria-required="true" property since it is not a required field.
Screenshot 2022-10-19 at 2 41 45 PM

**After:** :heavy_check_mark:  
The field does include the aria-required="true" property even though it is not a required field.
Screenshot 2022-10-19 at 2 37 10 PM



Builds are failed after so many try. Hence, moving it to Extended testing.

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
It seems that bot have moved the PR from Extended testing to Ready for Testing hence moving it back.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE, Integration Tests

**Comment by engcom-Delta** [comment]
@magento run Integration Tests

**Comment by engcom-Delta** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE, Integration Tests

**Comment by engcom-Delta** [comment]
@magento run Functional Tests CE

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by faizan-shk** [comment]
@rsisco @engcom-Lima the automation tests are failing continuously and seems to be related to the changes of this PR.
I am working on the fix

Thanks You!

**Comment by faizan-shk** [comment]
@magento run all tests

**Comment by faizan-shk** [comment]
@magento run WebAPI Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Pull request merged**
