### PR TITLE
Add possibility generate varnish 4 config file, issue #864

### PR DESCRIPTION
**Pull request by hummer2k**
- Added varnish 4 compatible vcl
- Added possibility to extend config node system/full_page_cache/varnish/path to add new varnish versions.

Issue: #864

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Looks like we have some issues with test Magento\Framework\Data\Form\Element\DateTest::testGetValue (or maybe implementation) when we have 1st month of year.

**Comment by otoolec** [comment]
Thanks for submitting this PR.  I've linked it to the internal ticket MAGETWO-32339 for issue #864

**Comment by vpelipenko** [comment]
@hummer2k, unfortunately we can't except this PR, due to duplication of our work. Last few weeks we also worked on Varnish 4 compatibility for page cache. This work was announced in https://github.com/magento/magento2/issues/864 issue. Our improvement is already finished by development team and will be available on public after next update at the end of this week. Please, stay tuned.

**Comment by hummer2k** [comment]
No big deal!

**Pull request closed without merging**
