### PR TITLE
Fixing typo in validation.js advice container

### PR DESCRIPTION
**Pull request by steverobbins**

### CODE REVIEW

**Comment by antonkril** [comment]
Introduces breaking changes. Please make old variable also available.

**Comment by steverobbins** [comment]
@antonkril Old variable has been made available.

**Comment by piotrekkaminski** [comment]
internal ticket MAGETWO-54585

**Comment by hshar7** [comment]
Hi @steverobbins I see that this PR has some merge conflict with minified JS files. Could you, please, resolve those and merge latest mainline.

**Comment by steverobbins** [comment]
@hshar7 Conflict resolved and rebased on `develop`.

**Comment by hshar7** [comment]
Sorry to say this @steverobbins but we cannot process this after careful review. It modifies a third party library, which we are not to modify.

**Comment by hshar7** [comment]
@steverobbins closed this, you may reopen it if updated but I think it would be best to just make a new one with the latest changes from that validation library, If you are still interested!

**Pull request closed without merging**
