### PR TITLE
[MFTF] Check Magento Marketplace content rendering 

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This MFTF test add check displaying of Magento Marketplace page

1. login to admin 
2. Go to Magento Marketplace page
3. Assert content rendering

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE

**Comment by dmytro-ch** [comment]
@magento run Functional Tests CE

**Comment by gabrieldagama** [comment]
Hi @Usik2203 thanks for contributing, we have discussed this PR at the Community Triage meeting. Our team believes that there is not much benefit to asserting that the marketplace page is rendered.

When we consider adding a new test it is ideal that the new test case worth the execution time, in this case, we don't see much value.

But thanks again.

**Pull request closed without merging**
