### PR TITLE
Fix Typo in Data\Form\Element\Factory.php

### PR DESCRIPTION
**Pull request by zack6849**
Sorry for the small PR!

Fixes typo in \Magento\Framework\Data\Form\Element\Factory.php

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18476) <br/>All committers have signed the CLA.

**Comment by VladimirZaets** [comment]
Hi @zack6849 , please, sign CLA, otherwise, we can't process your pull request

**Comment by magento-engcom-team** [comment]
@zack6849 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @zack6849. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
