### PR TITLE
magento/magento2#34707: New Relic module does not complies with CSP

### LINKED ISSUE #34707: New Relic module does not complies with CSP
### Preconditions (*)
1. Magneto Commerce v2.4.2
2. New Relic Reporting module v100.4.1

### Steps to reproduce (*)
1. Enable the extension to strart tracking website data.
2. Enter to the homepage

### Expected result (*)
1. Domains for the new relic domains for browser reporting should be included into the CSP headers

### Actual result (*)
1. The following errors appears on the browser console (chrome): 
```
[Report Only] Refused to load the script 'https://js-agent.newrelic.com/nr-spa-1212.min.js' because it violates the following Content Security Policy directive: "script-src [.....] 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
[Report Only] Refused to load the script 'https://bam.nr-data.net/1/[..]etToken' because it violates the following Content Security Policy directive: "script-src [..]'unsafe-inline' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

Current workarround:
1. Add a new module and set this values explicitly. Requires developer knowhow.

---
- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Kiraberos**
- fixed issue with compliance new relic module with CSP

### Description (*)

According to #34707 create csp_whitelist.xml and added domains for the new relic domains in the module NewRelicReporting.

### Related Pull Requests

No

### Fixed Issues (if relevant)

1. Fixes magento/magento2#34707

### Manual testing scenarios (*)

1. Configure new relic locally in Magento 2 
2. Go to the main page, and opened the browser console (chrome).

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Kiraberos** [comment]
@magento run all tests

**Comment by Kiraberos** [comment]
@magento run all tests

**Comment by Kiraberos** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by Kiraberos** [comment]
@magento run all tests

**Review by ishakhsuvarov — APPROVED** [review]

**Pull request merged**
