### PR TITLE
Add improvements for varnish vcl files

### PR DESCRIPTION
**Pull request by nagno**
Hi,

I have created this PR to improve the varnish configuration a little bit and fix some issues.
I don't have varnish 3 at the moment, so I did not add the same configuration to the Varnish 3
files, because I can't test it.

This PR is for https://github.com/magento/magento2/issues/1575

### CODE REVIEW

**Comment by daim2k5** [comment]
Hi @nagno you need also to accept the CLA otherwise we can't use your PR.

**Comment by nagno** [comment]
Hi @daim2k5,

I tried to sign it at least 4 times since I submitted the PR, but it is still not displays as signed.
It always displays a successful message, but it is still not appears as signed. This is my last attempt from 2 minutes ago: https://nimbus.everhelper.me/client/notes/share/323299/6aDViGBJltvnWuxVA5irNxLyVdEv8SMe/

I'm happy to sign it, but it not works for some reason :(

**Comment by daim2k5** [comment]
Hi @nagno thanks for the information i try to forward to a person that can maybe help with that ;-)

**Comment by nagno** [comment]
@daim2k5: Perfect, thanks! :)

**Comment by daim2k5** [comment]
@nagno  please one more time because CLA service crashed ;-)

**Comment by nagno** [comment]
@daim2k5: unfortunately it still not works :(
I got the same "thank you" page, but on github it is still reported as not signed.

**Comment by benmarks** [comment]
Sorry @nagno, we're working on it. Thanks for helping us.

**Comment by benmarks** [comment]
Update: we've resolved the issue of the crashed CLA monitor, but the PRs submitted while it was down are stuck. We're working to unstick them (Ref *CICD-1981*). Sorry for the friction, and thanks for understanding as we get this new process sorted out.

**Comment by nagno** [comment]
Hi @benmarks,
Thanks for the update! I can re-submit the PR if that helps.

**Comment by benmarks** [comment]
Looks like we're resolved, thanks to internal team effort. @daim2k5, do your thing!

**Comment by dsikkema-magento** [comment]
Internal ticket: MAGETWO-49876

**Comment by okorshenko** [comment]
@nagno Your Pull Request merged to develop branch. Thank you for contribution!

**Pull request merged**
