### PR TITLE
Fix the issue with missing asterisk for admin required fields

### PR DESCRIPTION
**Pull request by dmytro-ch**
### Preconditions
There is a missing asterisk for admin required fields.

### Description (*)
Looks like the issue was accidentally caused by the following commit: https://github.com/magento/magento2/commit/7d4721dd38d832b072c2f77d74da3a23a53fa675

1. The same fix should be applied as for the Magento 2.3 in order to fix the issue: https://github.com/magento/magento2/commit/eb173dd1b90cf3c729ec10dd115652b56586108a
2. Also, the following temporary fix for admin login form should be reverted: https://github.com/magento/magento2/commit/af700494b83600a29d03badbef20374a81960b4a

### Fixed Issues
1. magento/magento2#18904: Missing asterisk for admin required fields

### Manual testing scenarios (*)
1. Check the admin form with required fields. (E.g. Admin login page, admin order create page etc.)

### Expected result
1. The asterisk is shown for the required foelds.
screen shot 2018-10-28 at 12 26 13 pm
screen shot 2018-10-28 at 12 33 27 pm

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18905-2-2-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18905-2-2-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-18905-2-2-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-18905/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-18905//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-18905//admin)
Login: `admin` Password: `123123q`

**Comment by sidolov** [comment]
Hi @dmytro-ch , we found few test failures with current solution: 

`MTF / Functional-Tests-CE / Functional Tests CE - MTF / isolate:3:39:Magento_Catalog_Test_TestCase_Product_CreateSimpleProductEntityPartTwoTest / Magento\Catalog\Test\TestCase\Product\CreateSimpleProductEntityPartTwoTest.testCreate with data set "CreateSimpleProductEntityTestVariation23_0"`

`MTF / Functional-Tests-CE / Functional Tests CE - MTF / 6:55:4 / Magento\Catalog\Test\TestCase\ProductAttribute\CreateAttributeSetEntityTest.testCreateAttributeSet with data set "CreateAttributeSetEntityTestVariation1_0"`

`MTF / Functional-Tests-CE / Functional Tests CE - MTF / 6:55:4 / Magento\Catalog\Test\TestCase\ProductAttribute\CreateProductAttributeEntityFromProductPageTest.test with data set "CreateProductAttributeEntityFromProductPageTestVariation1_Searchable_Global_Visible_Comparable_HtmlAllowed_UsedForSorting_0"`

`MTF / Functional-Tests-CE / Functional Tests CE - MTF / 6:55:4 / Magento\Catalog\Test\TestCase\ProductAttribute\CreateProductAttributeEntityTest.testCreateProductAttribute with data set "CreateProductAttributeEntityTestVariation2_0"`

`MTF / Functional-Tests-CE / Functional Tests CE - MTF / 6:55:4 / Magento\Catalog\Test\TestCase\ProductAttribute\CreateProductAttributeEntityTest.testCreateProductAttribute with data set "CreateProductAttributeEntityTestVariation6_0"`

`MTF / Functional-Tests-CE / Functional Tests CE - MTF / 6:55:4 / Magento\Catalog\Test\TestCase\ProductAttribute\CreateProductAttributeEntityTest.testCreateProductAttribute with data set "CreateProductAttributeEntityTestVariation7_0"`

Please, take a look

**Comment by dmytro-ch** [comment]
For now, I've resolved the mentioned failures, except the "CreateProductAttributeEntityTest" test.
Will continue investigating the issue.

**Comment by sidolov** [comment]
Hi @dmytro-ch , will you continue work on this? 
Thank you!

**Comment by dmytro-ch** [comment]
Hello @sidolov.
Unfortunately, I could not resolve the issue with failing functional tests yet.

The problem should be related to my local environment setup, considering the same tests permanently fail in _2.2-develop_ branch.

```
Magento\Catalog\Test\TestCase\ProductAttribute\CreateProductAttributeEntityTest::testCreateProductAttribute with data set "CreateProductAttributeEntityTestVariation3_0" (CreateProductAttributeEntityTestVariation3_0)
Exception: Container is not found "conditions""
```

```
Magento\Catalog\Test\TestCase\ProductAttribute\CreateProductAttributeEntityTest::testCreateProductAttribute with data set "CreateProductAttributeEntityTestVariation6_0" (CreateProductAttributeEntityTestVariation6_0)
Products attribute options are absent on product form: blue
Failed asserting that false is true.
```

```
Magento\Catalog\Test\TestCase\ProductAttribute\CreateProductAttributeEntityTest::testCreateProductAttribute with data set "CreateProductAttributeEntityTestVariation8_0" (CreateProductAttributeEntityTestVariation8_0)
Product Attribute is absent on Product form.
Failed asserting that false is true.
```

I'm using:
- ChromeDriver: 2.43.600233
- Chrome headless: 70.0.3538.102 
- Selenium: 3.4.0

I was also trying to use PhantomJS and Firefox instead of Chrome, but encountered another issue.

I'm not sure I can finish this PR soon. So the issue can be passed to another developer, in order to finish it ASAP.

Thank you!

**Comment by sidolov** [comment]
Hi @dmytro-ch , try to use older version of selenium, for example, 2.53.1 and corresponded driver for it.

**Comment by dmytro-ch** [comment]
@sidolov, thank you for the recomendations.

I've downgraded following dependencies:

- ChromeDriver: 2.21.371461
- Chrome headless: 50.0.2661.75
- Selenium: 2.53.1

But exactly the same issues still arise as previously.

I'm running the test separately on clean database.

```
vendor/bin/phpunit --filter CreateCategoryEntityTest
```

All the required system configs are also set (https://devdocs.magento.com/guides/v2.2/mtf/mtf_quickstart/mtf_quickstart_magento.html).
All the dependencies are up to date.

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.

**Pull request merged**
