### PR TITLE
Issue resolved #19607. Page Not Found when deleting Attribute Set #19614

### LINKED ISSUE #19607: Magento 2.3. Page Not Found when deleting Attribute Set
### Preconditions (*)

1. Magento 2.3
2.

### Steps to reproduce (*)

1. Create New Attribute Set then try to delete it
2.

### Expected result (*)

1. I expect it to delete the attribute but it results in a page not found
2.

### Actual result (*)

1. Page not found
screen shot 2018-12-06 at 4 18 42 pm

2.

### PR DESCRIPTION
**Pull request by ghost**
Description (*)
Page Not Found when deleting Attribute Set

Fixed Issues (if relevant)
1. magento/magento2 #19607: Page Not Found when deleting Attribute Set

Manual testing scenarios (*)
1.Delete a product attribute set.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @cedcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by ghost — COMMENTED** [review]
Issue resolved #19607. Page Not Found when deleting Attribute Set #19614

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [new Magento instance](https://pr-19633.instances.magento-community.engineering).
Admin access: [https://pr-19633.instances.magento-community.engineering/admin](https://pr-19633.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3641](https://jira.corp.magento.com/browse/ENGCOM-3641) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@cedcommerce thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @cedcommerce. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
