### PR TITLE
Fixed typo "attibute" -> "attribute" in Catalog Module

### PR DESCRIPTION
**Pull request by joshtmprod**
Fixed a typo of the word attribute in the Catalog module. File: /view/frontend/templates/product/compare/list.phtml, line 104.

### CODE REVIEW

**Comment by MomotenkoNatalia** [comment]
Hi @joshtmprod !
Thanks for contributing! I created internal ticket MAGETWO-49782 to process your PR.

Please sign Contributor License Agreement displayed below.

**Comment by joshtmprod** [comment]
All set!

**Comment by vkorotun** [comment]
Check also app/design/frontend/Magento/blank/Magento_Catalog/web/css/source/_module.less:698.
Typos are such things that easily getting copy&pasted by developers :)
Probably other places exist...

**Comment by MomotenkoNatalia** [comment]
@vkorotun  We have already fixed other places. Internal ticket MAGETWO-49782 is in testing now.

**Pull request merged**
