### PR TITLE
Non existing file, when adding image to gallery with move option. Fix for #21978

### PR DESCRIPTION
**Pull request by dudzio12**
### Description (*)
1. Fix for throwing error "File not exist" when adding image to product via `addImageToMediaGallery` method with `$move`.

### Fixed Issues (if relevant)
1. magento/magento2#21978: Adding product image: File doesn't exist #21978

### Manual testing scenarios (*)
1. Add image via above method programatically.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22020) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @dudzio12. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-4838](https://jira.corp.magento.com/browse/ENGCOM-4838) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@dudzio12 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
