### PR TITLE
Fixed 19658 Magento modal popup box align vertically middle

### PR DESCRIPTION
**Pull request by abrarpathan19**
### Description (*)

Magento modal popup box align vertically middle

### Fixed Issues (if relevant)

1. magento/magento2#19658: Magento modal popup box align vertically middle

### Manual testing scenarios (*)

1. Magento modal popup box set veticle align middle.
2. Admin -> Content -> click and try to delete page attention message please review below link 
http://prntscr.com/lsbus1

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @abrarpathan19. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-19660.instances.magento-community.engineering).
Admin access: [https://pr-19660.instances.magento-community.engineering/admin](https://pr-19660.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by TomashKhamlai** [comment]
The proper placement is documented so just warn that this change requires changes to the documentation too.
https://devdocs.magento.com/guides/v2.3/pattern-library/containers/slideouts-modals-overlays/img/modal5.png
For this reason the related issue was closed.

Also in most cases it is possible to override styling in child theme.
Modals in Magento UI accepts options object. It is better to give an advantage of customizing modal placement via JS library by adding more properties like `"placement":"top|middle|"x":"int","y":"int","geometry": "center|corner"` rather then force these changes for everyone via CSS. I mean we never know how people would react to this change.

**Review by DanielRuf — CHANGES_REQUESTED** [review]
This will produce issues with very long content. Also the 55px "fix" is not good.

**Comment by DanielRuf** [comment]
Also we could do this with flexbox. The proposed solution would create new problems and change existing UIs.

**Comment by miguelbalparda** [comment]
Closing for now because of the stated reasons, feel free to reopen if anything changes.

**Pull request closed without merging**
