### PR TITLE
Missing section when custom role is selected

### LINKED ISSUE #35506: [Issue] Missing section when custom role is selected
This issue is automatically created based on existing pull request: magento/magento2#35439: Missing section when custom role is selected

---------

### Description (*)

When we select custom "Roles Resources" then we don't see "Magento Web API" under "Store>Configuration>Services"

### Manual testing scenarios (*)

1. Login to Magento Admin as Administrator
2. Navigate to "Store>Configuration>Services"
3. You should be able to see "Magento Web API"
4. Now set a custom permission by navigating to "System>User Roles"
5. Select Administrators
6. Go to Role Resources Tab
7. Under "Resource Access" select Custom
8. Now select every checkbox and save the role
9. Navigate to "Store>Configuration>Services"
10. You will see "Magento Web API" section is missing
11. After applying this fix it will remain

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by arifadobe**
### Description (*)

When we select custom "Roles Resources" then we don't see "Magento Web API" under "Store>Configuration>Services"

### Manual testing scenarios (*)

1. Login to Magento Admin as Administrator
2. Navigate to "Store>Configuration>Services"
3. You should be able to see "Magento Web API"
4. Now set a custom permission by navigating to "System>User Roles"
5. Select Administrators
6. Go to Role Resources Tab
7. Under "Resource Access" select Custom
8. Now select every checkbox and save the role
9. Navigate to "Store>Configuration>Services"
10. You will see "Magento Web API" section is missing
11. After applying this fix it will remain

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#35506: Missing section when custom role is selected

### CODE REVIEW

**Comment by arifadobe** [comment]
@magento give me test instance

**Comment by arifadobe** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by arifadobe** [comment]
@magento run Functional Tests EE

**Comment by arifadobe** [comment]
@magento create issue

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests EE

**Pull request merged**
