### PR TITLE
Update Runtime.php

### PR DESCRIPTION
**Pull request by dverkade**
Constructor shoud use an interface, so that any class implementing the interface can be passed into this class.

### CODE REVIEW

**Comment by davidalger** [comment]
Thank you for the PR! We are currently waiting for the travis builds to work again, which should happen in a few days. Once that is running and the tests are green we can continue to process your contribution. In the mean time, can you please sign the contributor license agreement?

**Comment by dverkade** [comment]
Hi David,

Thank you for your e-mail. Could you please send me a copy of the 
agreement?

**Comment by davidalger** [comment]
@dverkade At the bottom of GitHub pull request pages you'll see status checks for Travis, and also one for the "license/cla" and that's the one you need to act on to change green. You do that by clicking "Details" or following this URL (what it points to): https://cla.dev.magento.com/magento/magento2?pullRequest=2769

Thanks!

**Comment by mazhalai** [comment]
@dverkade Please merge latest from develop and rerun builds.

**Comment by dsikkema-magento** [comment]
Internal ticket: MAGETWO-49871

@dverkade could you please take a look at the failing travis builds?

**Comment by dverkade** [comment]
Hi,

Please see Pull Request #2990 which is the same. I have changed another 
file and created a complete new Pull Request.

Danny Verkade

**Comment by okorshenko** [comment]
@dverkade Thank you for contribution. We will try re-run tests for your PR using our internal infrastructure.

**Pull request merged**
