### PR TITLE
fix : Admin grid actions dropdown cut off in versions after 2.4.3 #36710

### LINKED ISSUE #36710: Admin grid actions dropdown cut off in versions after 2.4.3
### Preconditions and environment

Magento version: 2.4.5-p1

### Steps to reproduce

1. Log into admin
2. Go to **Content > Pages**
3. Click the "Select" in the Action column for the last row in the grid

### Expected result

I expect to see the whole dropdown without causing an inner scroll to reach the content.  This was last seen working correctly on version 2.4.3-p2.

Screenshot 2023-01-06 at 8 36 42 AM

### Actual result

The dropdown that appears is cut off and only accessible if you scroll within the table's wrapping `div`.  Occurs in versions 2.4.4 and 2.4.5.

Screenshot 2023-01-06 at 8 37 13 AM

### Additional information

This appears caused due to the `.data-grid-actions-cell` `position: relative;` that was added to the admin theme file...
vendor/magento/theme-adminhtml-backend/Magento_Ui/web/css/source/module/_data-grid.less.  Removing this appears to correct the issue.

<pre><code>.data-grid-actions-cell {
    padding-left: @data-grid-cell__padding-horizontal * 2;
    padding-right: @data-grid-cell__padding-horizontal * 2;
    <strong>position: relative;</strong>
    text-align: center;
    width: 1%;
}</code></pre>

Screenshot below shows code diff between version 2.4.5-p1 (left) and 2.4.3 (right) where the `position: relative` line was shown as not existing in 2.4.3.
Screenshot 2023-01-06 at 11 56 34 AM

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by dekiakbar**
### Description (*)
Fix: Admin grid actions dropdown cut off in versions after 2.4.3 #36710 

### Fixed Issues (if relevant)
1. Fixes magento/magento2#36710

### Manual testing scenarios (*)
1. Log into admin
2. Go to Content > Pages
3. Click the "Select" in the Action column for the last row in the grid

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by dekiakbar** [comment]
@magento give me test instance

**Comment by dekiakbar** [comment]
@magento run all tests

**Comment by dekiakbar** [comment]
@magento runFunctional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by dekiakbar** [comment]
@magento give me test instance

**Comment by dekiakbar** [comment]
https://github.com/magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by dekiakbar** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by dekiakbar** [comment]
@magento give me test instance

**Comment by dekiakbar** [comment]
@magento run WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Lima** [comment]
Hi @dekiakbar ,

Thanks for your contribution and collaboration.

The issue is not reproducible in the latest `2.4-develop`. 

Below is the screenshot for your reference:
- Verified admin grid in Pages.
Screenshot 2023-08-21 at 6 53 38 PM
- Verified admin grid in Blocks
Screenshot 2023-08-21 at 6 45 56 PM

Kindly retest it in the latest `2.4-develop` and let us know if you are facing any issues.
This issue is taken care of by the internal team. Hence, closing this PR.

Thanks

**Pull request closed without merging**
