### PR TITLE
issue/20975: Query slow when using quotes for integers in WHERE state…

### PR DESCRIPTION
**Pull request by PascalBrouwers**
…ments

### Fixed Issues (if relevant)

1. magento/magento2#20975: Query slow when using quotes for integers in WHERE statements

### Manual testing scenarios (*)

1. Load a product in the backend and check the query log.
2. See that for example `SELECT `eav_attribute`.* FROM `eav_attribute` WHERE (`eav_attribute`.`attribute_id`='74')` is now `SELECT `eav_attribute`.* FROM `eav_attribute` WHERE (`eav_attribute`.`attribute_id`=74)`

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20976) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=20976) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
Hi @PascalBrouwers. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sidolov** [comment]
Hi @PascalBrouwers  , please, sign CLA, otherwise, we can't process your pull request

**Comment by sidolov** [comment]
@PascalBrouwers , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by PascalBrouwers** [comment]
@magento run all tests

**Comment by PascalBrouwers** [comment]
@sidolov how do I reopen this issue?

**Comment by sidolov** [comment]
@PascalBrouwers in this case you need to re-create the PR since the 2.3-develop branch was removed

**Pull request closed without merging**
