### PR TITLE
Add delete action for default addresses

### PR DESCRIPTION
**Pull request by thomas-kl1**
Add delete button to the default  address on customer book page.

### Description
Delete a default address is possible in Magento, controller action allows it and the system can handle it.
However the customer can't delete a default address as there's no action button.  
The only way for a customer to delete his default address is to create a new, set it as default, then he can delete the first one.

### Manual testing scenarios

1. Go to the addresses section in customer account page
2. Click "Delete address" on a default address

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @thomas-blackbird. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by thomas-kl1** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @thomas-blackbird. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @thomas-blackbird, here is your [new Magento instance](https://pr-16688.engcom.dev.magento.com).
Admin access: [https://pr-16688.engcom.dev.magento.com/admin](https://pr-16688.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Please make sure you are PR **author** or **assignee** to access the instance.

**Comment by VladimirZaets** [comment]
Hi @thomas-blackbird. Thanks for collaboration.
Currently, Magento has business criteria that customer should have at least one address. So we can't support functionality to delete default address.

**Comment by thomas-kl1** [comment]
Ok nevermind, is there any chance that this case can be configurable in the settings? Where it could be "Allow delete default address" with "no" by default?  
Anyway, can you tell me more about this business criteria? :smiley:

**Comment by orlangur** [comment]
@thomas-blackbird you can do it for your custom Magento instance, there is no need to bloat core with such setting.

I don't like this requirement is not enforced on server side though.

**Pull request closed without merging**
