### PR TITLE
magento/magento2#: Replace deprecated methods in back-end controllers of Magento/Customer

### PR DESCRIPTION
**Pull request by atwixfirster**
### Description (*)

Pull request replaces deprecated `addError`, `addSuccess`, `addException` methods

```
addError -> addErrorMessage
addSuccess -> addSuccessMessage
addException -> addExceptionMessage
```

 in the next controllers:

- app/code/Magento/Customer/Controller/Adminhtml/Index/MassAssignGroup.php
- app/code/Magento/Customer/Controller/Adminhtml/Index/MassDelete.php
- app/code/Magento/Customer/Controller/Adminhtml/Index/MassSubscribe.php
- app/code/Magento/Customer/Controller/Adminhtml/Index/ResetPassword.php
- app/code/Magento/Customer/Controller/Adminhtml/Index/Save.php
- app/code/Magento/Customer/Controller/Adminhtml/Index.php
- app/code/Magento/Customer/Controller/Adminhtml/Locks/Unlock.php

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

Thank you!

### CODE REVIEW

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
@atwixfirster could yo please check the failing unit tests?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @atwixfirster,
Could you review and fix integration tests?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by atwixfirster** [comment]
>  Could you review and fix integration tests?

@dmytro-ch @ihor-sviziev,  

**done**

Thanks, guys!

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5723](https://jira.corp.magento.com/browse/ENGCOM-5723) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @atwixfirster 

During testing we faced the issue

**Problem:** "404 Error" message occurs when trying to "Subscribe to Newsletter" via mass action

**Manual testing scenario:** 

1. Login to Admin;
2. Create 2 customers for example;
3. Select them from the grid;
4. Select "Subscribe to Newsletter" from drop down menu;

**Actual Result:**

error

@atwixfirster Could you take a look, please?

Thanks!

**Comment by atwixfirster** [comment]
Thank you, @engcom-Alfa !

I will check

**Comment by edenduong** [comment]
@dmytro-ch : Should they combine to one??

https://github.com/magento/magento2/pull/24284
https://github.com/magento/magento2/pull/24197
https://github.com/magento/magento2/pull/24340

**Comment by dmytro-ch** [comment]
@edenduong, these PRs will be combined after approval.
Thank you!

**Comment by ihor-sviziev** [comment]
> @dmytro-ch : Should they combine to one??
> 
> #24284
> #24197
> #24340

It's really easier to test each PR separately

**Comment by dmytro-ch** [comment]
> It's really easier to test each PR separately

I agree, it depends on PRs.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5723](https://jira.corp.magento.com/browse/ENGCOM-5723) has been created to process this Pull Request

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5723](https://jira.corp.magento.com/browse/ENGCOM-5723) has been created to process this Pull Request

**Review by sidolov — CHANGES_REQUESTED** [review]
@atwixfirster please, take a look at the issue reported by @engcom-Alfa

**Comment by atwixfirster** [comment]
> @atwixfirster please, take a look at the issue reported by @engcom-Alfa

@sidolov, of course . I will check that issue in 3-4 hours.

Thanks

**Comment by atwixfirster** [comment]
> @atwixfirster please, take a look at the issue reported by @engcom-Alfa

**fixed**

Thank you, @engcom-Alfa 👍

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @atwixfirster,
Unfortunately integration tests started failing after your latest change.
Please review & fix them.
Thank you!

**Comment by atwixfirster** [comment]
> Hi @atwixfirster,
> Unfortunately integration tests started failing after your latest change.
> Please review & fix them.
> Thank you!

Good morning, @ihor-sviziev!

**fixed**

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5723](https://jira.corp.magento.com/browse/ENGCOM-5723) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
