### PR TITLE
Fix simple products unlink from original bundle product

### PR DESCRIPTION
**Pull request by MaxSouza**
### Description (*)

If bundle product was duplicated - simple products unlink from original bundle product.

### Fixed Issues (if relevant)

1. #24757: Duplicating product functionality doesn't support bundle products

### Manual testing scenarios (*)

1. Go to edit bundle product at the admin
2. Hit save and duplicate btn
3. After save, check if the old bundle still has items

### Questions or comments

The product that it will be duplicate

image

image

The product that it has been duplicate

image

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by aleron75** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @aleron75. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @aleron75, here is your [new Magento instance](https://pr-25017.instances.magento-community.engineering).
Admin access: [https://pr-25017.instances.magento-community.engineering/admin](https://pr-25017.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by aleron75** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @aleron75. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @aleron75, here is your [Magento instance](https://i-25017-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25017-2-3-develop.instances.magento-community.engineering/admin](https://i-25017-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by aleron75** [comment]
Sorry @MaxSouza but I didn't manage to reproduce the issue.

I created 4 simple products, made the first bundle, associated two simple products to option 1, associated the other two products to option 2, enabled bundle, hit save+duplicate, enabled new bundle, hit save.

Both bundle products have identical options and associated products both in vanilla M2.3 and in M2.3 + your code.

What am I missing?

**Comment by MaxSouza** [comment]
Hi @aleron75 , 

It's correct, without my code both bundle products does not identical. Could you test without my changes?

**Comment by hostep** [comment]
Hi @MaxSouza: I think I might have already fixed this a few weeks ago in: https://github.com/magento/magento2/pull/24703

Can you confirm?

**Comment by MaxSouza** [comment]
Hi @hostep,

I confirmed, it's fixed.

**Pull request closed without merging**
