### PR TITLE
Upgrade PHPStan to version 1.5

### LINKED ISSUE #35315: [Issue] Upgrade PHPStan to version 1.5
This issue is automatically created based on existing pull request: magento/magento2#35234: Upgrade PHPStan to version 1.5

---------

### Description (*)
[PHPStan 1.5](https://github.com/phpstan/phpstan/releases/tag/1.5.0) was released yesterday. This PR upgrades PHPStand 1.4.9 to 1.5.0.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by shochdoerfer**
### Description (*)
[PHPStan 1.5](https://github.com/phpstan/phpstan/releases/tag/1.5.0) was released yesterday. This PR upgrades PHPStand 1.4.9 to 1.5.0.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#35315: Upgrade PHPStan to version 1.5

### CODE REVIEW

**Comment by nuzil** [comment]
@magento run all tests

**Review by andrewbess — CHANGES_REQUESTED** [review]
Hello @shochdoerfer 
Thank you for your contribution here
Could you please resolve merge conflicts
Thank you in advance.

**Comment by sdzhepa** [comment]
@magento create issue

**Comment by shochdoerfer** [comment]
@andrewbess should we also upgrade to the latest PHPStand version (1.5.6)?

**Comment by andrewbess** [comment]
Hello @shochdoerfer 
Please update your branch from the mainline (`2.4-develop`) and just upgrade `phpstan/phpstan` composer dependency to the 1.5.6.
I will import your PR into `magento-commerce` and merge it ASAP.
Thank you in advance.

**Comment by shochdoerfer** [comment]
@andrewbess done!

**Review by andrewbess — APPROVED** [review]
Hello @shochdoerfer 
Thank you for your contribution
This PR imported into `magento-commerce` repo
Please don't change it.

**Pull request merged**
