### PR TITLE
reference directive restored for _extends.less. extends replaced to mixins in _extend.less

### LINKED ISSUE #36914: [Issue] reference directive restored for _extends.less. extends replaced to mixins in _extend.less
This issue is automatically created based on existing pull request: magento/magento2#35101: reference directive restored for _extends.less. extends replaced to mixins in _extend.less

---------
### Description (*)

When I installed a clear M2, I saw that the `reference` directive removed for the import of **_extends.less** file. I've found [this PR](https://github.com/magento/magento2/pull/31793) and I explained why removing `reference` is a bad idea:
https://github.com/magento/magento2/pull/31793#issuecomment-1038102831

I've investigated later how to restore `reference` but repair the issue of Grunt in [the PR](https://github.com/magento/magento2/pull/31793). 

And I've found a solution described here:
https://github.com/magento/magento2/pull/31793#issuecomment-1038905078

@ihor-sviziev asked me to create a PR with the fix, so I made it.

### Related Pull Requests
https://github.com/magento/magento2/pull/31793

### Manual testing scenarios (*)

1. Create a new theme which extends Magento Blank theme.
2. Compile styles via default deploying (setup:static-content:deploy) and via Grunt.
3. Look at block titles of My Account (they should look the same after all build processes).
4. Find matches of `abs` selectors in `styles-m.css` and `styles-l.css` files. Quantity of them and the size of `styles-m.css` should be less in comparison with the main branch (2.4-develop).

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by serhii-chernenko**
### Description (*)

When I installed a clear M2, I saw that the `reference` directive removed for the import of **_extends.less** file. I've found [this PR](https://github.com/magento/magento2/pull/31793) and I explained why removing `reference` is a bad idea:
https://github.com/magento/magento2/pull/31793#issuecomment-1038102831

I've investigated later how to restore `reference` but repair the issue of Grunt in [the PR](https://github.com/magento/magento2/pull/31793). 

And I've found a solution described here:
https://github.com/magento/magento2/pull/31793#issuecomment-1038905078

@ihor-sviziev asked me to create a PR with the fix, so I made it.

### Related Pull Requests
https://github.com/magento/magento2/pull/31793

### Manual testing scenarios (*)

1. Create a new theme which extends Magento Blank theme.
2. Compile styles via default deploying (setup:static-content:deploy) and via Grunt.
3. Look at block titles of My Account (they should look the same after all build processes).
4. Find matches of `abs` selectors in `styles-m.css` and `styles-l.css` files. Quantity of them and the size of `styles-m.css` should be less in comparison with the main branch (2.4-develop).

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36914: reference directive restored for _extends.less. extends replaced to mixins in _extend.less

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@mrtuvn, could you please review?

**Comment by mrtuvn** [comment]
Looking goods at my pov
Sorry current i totally lost of track with magento codebase. Since a while i don't work with magento anymore. But i will support you as much as possible 
Class mixins, or abstract in reference import should not show at output files final css. I think current extend way seem outdated and not working properly if we use grunt compile. This task may take efforts to recheck with extend implements in codebase. If we want styles consistency same (php compile and lessjs compile/grunt)
From my opinion i think we need to check compare results file extends with both theme luma/blank too

**Comment by mrtuvn** [comment]
Can you check static fails at reports ?

**Comment by mrtuvn** [comment]
@magento run Static Tests

**Comment by mrtuvn** [comment]
@magento run Static Tests

**Comment by mrtuvn** [comment]
Seem false positive results from Less sniffer checks. From my view is magento use php to check less/css code ?
cc: @ihor-sviziev @sidolov

**Comment by mrtuvn** [comment]
@magento run Static Tests

**Comment by mrtuvn** [comment]
@magento run Static Tests

**Comment by mrtuvn** [comment]
https://github.com/magento/magento-coding-standard/issues/395
Found this one report may clear for reason fail static tests. I think we should take a look at current implement in static check sniffer
CC: @ihor-sviziev @sdzhepa @sivaschenko

**Review by mrtuvn — APPROVED** [review]
looks good

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
Hi @sdzhepa,
I think we should increase priority to p2 as currently it causes bad developer experience (more info with explanation and screenshots in see in the thread to related PR). Can we increase it?

**Comment by mrtuvn** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Comment by mrtuvn** [comment]
composer.lock at root still use v23 of @magento/magento-coding-standard

**Comment by engcom-Alfa** [comment]
@magento run all Tests

**Comment by mrtuvn** [comment]
@engcom-Alfa  you have to wait test results after pump up version magento-coding-standard in composer.lock for re-test (Static Tests)

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by mrtuvn** [comment]
Visual should not change or make any regression

But if you want to compare difference of changes you should take a look at blank theme at pub folder
before 
search/find available ".abs-"
styles-l.css 45
styles-m.css 321

after
search/find available ".abs-"
styles-l.css 36
styles-m.css 188 //<=size smaller

@engcom-Alfa

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run Static Tests

**Comment by mrtuvn** [comment]
cc @andrewbess @sidolov any way to version bump @magento-code-standard latest version at composer.lock ?

**Comment by mrtuvn** [comment]
@magento run Static Tests

**Comment by mrtuvn** [comment]
re-run test static
@magento run Static Tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Static Tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Integration Tests,Functional Tests EE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@Inevix @mrtuvn @ihor-sviziev  
Thanks for the collaboration & contribution!


:heavy_check_mark: QA Passed
reference directive restored for _extends.less. extends replaced to mixins in _extend.less

**Manual Scenario Steps**
For manual steps we have followed [comment](https://github.com/magento/magento2/pull/35101#issuecomment-1176113022)

For actual result we have followed [comment](https://github.com/magento/magento2/pull/35101#issuecomment-1176335882)


**Before:** :heavy_multiplication_x: 

Theme luma (search/find available ".abs-")
styles-l.css 77
image

styles-m.css 419
image


**After:** :heavy_check_mark: 
Theme luma (search/find available ".abs-")
styles-l.css 68
image

styles-m.css 254
image

As there are test failure so moving to `Extended Testing`

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B ,Functional Tests EE

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B ,Functional Tests EE

**Comment by engcom-Echo** [comment]
Functional Tests EE and Functional Tests B2B failures are different on last two run.
Functional Tests EE 
Run1
image

Run2
image

Functional Tests B2B
Run1
image

Run2
image

Hence moving to `Merge In Progress`

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by serhii-chernenko** [comment]
@EmilConsor the imported file with `reference`, is a special optimization in LESS to get only that styles to the result bundle that really used. Others have to be cleaned up.
So, if you didn't use selectors from there, they will disappear.

Regarding the mentioned [file](
https://github.com/magento/magento2/blob/2.4-develop/app/design/frontend/Magento/blank/web/css/source/_forms.less#L30) it has to be investigated separately. 

But removing the reference is not a correct fix. Please don't hesitate to create a new issue with your finding to raise it again and discuss.

**Pull request merged**
