### PR TITLE
CE-33568: Update `phpmd/phpmd` to the latest version (2.10.2)

### PR DESCRIPTION
**Pull request by andrewbess**
### Description (*)

This pull request (PR) provides updating of the `phpmd/phpmd` composer dependency to the latest version 2.10.2.
Also, the update of the `pdepend/pdepend` composer dependency to version 2.10.0 is had in this PR.

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/566

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33568

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by andrewbess** [comment]
@magento run Functional Tests B2B

**Comment by andrewbess** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]

**Review by eduard13 — APPROVED** [review]

**Pull request merged**
