### PR TITLE
Simplify some conditional checks

### PR DESCRIPTION
**Pull request by DanielRuf**
### Description (*)

This PR simplifies some conditional checks and removes duplicate code.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by swnsma — CHANGES_REQUESTED** [review]
Hi @DanielRuf,

Thank you for your contribution!
Unfortunately, according to Magento Refactoring Policy, all files which have changes in PR need to be refactored.

Could you please check and fix failed tests?

**Comment by DanielRuf** [comment]
The failing test does not seem to be related. See https://testing-service.magento-community.engineering/reports/magento/magento2/pull/24849/3bd3fe35482a2077b74ff3249ae7231d/Statics/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

Not sure what you mean with refactoring in this case.

**Comment by swnsma** [comment]
Hi @DanielRuf,
Thank you for your reply.

If you do changes in some files, Magento Static Test will check the whole file.
In other words, if you change the file, you are responsible to make it green.

Unfortunately, even if test fail is really do not related to your changes, we can not continue with Pull Request without green tests.

Could you please make changes according to the failed static test checks?

**Comment by DanielRuf** [comment]
I'll try to resolve them.

**Comment by DanielRuf** [comment]
Hm, can someone check this? Currently a few tests fail now. Not yet sure why.
This enforcement makes it harder for contributors to contribute anything if they have to fix the code of others and do not know how it should actually work.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6125](https://jira.corp.magento.com/browse/ENGCOM-6125) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-6125](https://jira.corp.magento.com/browse/ENGCOM-6125) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @DanielRuf 

During testing, we faced the issue.

**_Problem:_** Fatal error when creating products using bulk APIs

**Manual testing scenario:**

1. Install Magento with **amqp**;
2. In console run command: `bin/magento queue:consumers:start async.operations.all`
3. Try to create products using bulk APIs
`POST <host>/rest/default/async/bulk/V1/products`

**Actual Result:** When we send the request from API client, we receive a fatal error message
after

and possibly because of that the WebAPI tests fall

@DanielRuf Could you take a look?

Thanks!

**Comment by DanielRuf** [comment]
Splat operator does not work with associative arrays. So I have to revert the one change. But then your CI still says that we have to refactor that part. Can we ignore this then and which comment should I use to correctly ignor eit?

https://stackoverflow.com/a/40663869/753676
https://bugs.php.net/bug.php?id=76613

**Comment by DanielRuf** [comment]
Splat operator does not work with associative arrays. So I have to revert the one change. But then your CI still says that we have to refactor that part. Can we ignore this then and which comment should I use to correctly ignore it?

https://stackoverflow.com/a/40663869/753676
https://bugs.php.net/bug.php?id=76613

**Comment by DanielRuf** [comment]
I have reverted the change regarding the splat operator.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6125](https://jira.corp.magento.com/browse/ENGCOM-6125) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @DanielRuf.

Could you remove unused `Magento\Framework\Exception\TemporaryStateExceptionInterface;` from `OperationProcessor` class?
screen
 Thanks!

**Comment by DanielRuf** [comment]
> Could you remove unused `Magento\Framework\Exception\TemporaryStateExceptionInterface;` from `OperationProcessor` class?

Done.

**Review by VladimirZaets — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
