### PR TITLE
[Backport] Corrected the translation for comment tag

### PR DESCRIPTION
**Pull request by yogeshsuhagiya**
### Original Pull Request 
https://github.com/magento/magento2/pull/21023

### Description (*)
Corrected the translation for `<comment>` tag and added translation key
Goto: STORES > Configuration > Payment Methods > RECOMMENDED SOLUTIONS: > OTHER PAYPAL PAYMENT SOLUTIONS: > Payflow Pro > Required PayPal Settings > Payflow Pro and Express Checkout. > Enable PayPal Credit

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios
N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by orlangur — CHANGES_REQUESTED** [review]
@yogeshsuhagiya please adopt corresponding tests to your changes.

**Comment by yogeshsuhagiya** [comment]
Hi @orlangur, I'm not getting your point, can you please let me know which tests I've to adopt?

**Comment by orlangur** [comment]
@yogeshsuhagiya check Travis CI builds which are currently failing.

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Comment by Nazar65** [comment]
ping @orlangur to approve.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-5014](https://jira.corp.magento.com/browse/ENGCOM-5014) has been created to process this Pull Request

**Pull request merged**
