### PR TITLE
magento/magento2#24043: Better exception handling during cli commands.

### PR DESCRIPTION
**Pull request by p-bystritsky**
### Description (*)

This PR is updating https://github.com/magento/magento2ce/commit/9ffe7eb2d3e6fcbf18eb39b6b847e99b0550a028

### Fixed Issues (if relevant)

1. magento/magento2#24043: Better exception handling during cli commands.
2. magento/magento2#24678: Static Content Deploy in developer mode without force flag is broken in 2.3-develop

### Manual testing scenarios (*)

1. Try to execute any incorrect console command through bin/magento
2. Correct exception message displayed in console.
3. Exception trace is logged in corresponding files.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5955](https://jira.corp.magento.com/browse/ENGCOM-5955) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by hostep** [comment]
@p-bystritsky : out of curiosity, will this also fix https://github.com/magento/magento2/issues/24678 ?

**Comment by hostep** [comment]
I can confirm that applying this PR fixes #24678, nice!

@p-bystritsky: can you edit your post and add #24678 to the fixed issues list so it will get automatically marked as fixed when this PR gets merged? Thanks!

**Comment by hostep** [comment]
I do have one remark about only logging the trace to the `system.log` file: wouldn't it make sense to also log the exception message? Only logging the trace is a bit strange and provides little context about this entry in the log file and might leave people confused reviewing the log files as what that stacktrace is doing in there without an exception message itself, no?

**Comment by sidolov** [comment]
@hostep agree with you, @p-bystritsky could you take a look on it?

**Comment by engcom-Foxtrot** [comment]
@hostep @sidolov updated

**Comment by p-bystritsky** [comment]
@hostep @sidolov updated

**Comment by hostep** [comment]
LGTM! Thanks!

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5955](https://jira.corp.magento.com/browse/ENGCOM-5955) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
