### PR TITLE
Fixed Massaction design with submenu on grid pages

### PR DESCRIPTION
**Pull request by ananth-iyer**
### Fixed Issues (if relevant)

1. magento/magento2#20928: [Backend] Admin product grid Massaction design issue with sub menu
2. ...

### Manual testing scenarios (*)

1. Goto Catalog > Product grid page
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ananth-iyer. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20938) <br/>All committers have signed the CLA.

**Comment by sdzhepa** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-20938-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20938-2-3-develop.instances.magento-community.engineering/admin](https://i-20938-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [new Magento instance](https://pr-20938.instances.magento-community.engineering).
Admin access: [https://pr-20938.instances.magento-community.engineering/admin](https://pr-20938.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sdzhepa** [comment]
Hello @ananth-iyer 
Thank you for contribution and collaboration!

We found this PR does not fix mentioned issue but brings a new one.
Could you please have a look and fix it?

Please, see attached GIF for more details
bcbf30cb-1cae-47f5-8d54-9a3dfe8e0a05

**Comment by ananth-iyer** [comment]
@sdzhepa Oh! I will create a new PR for the fixes. Can you check in 2.3 without my PR? if you see the scroll bar in Change Status submenu

**Comment by ananth-iyer** [comment]
@sdzhepa I have checked in Magento 2.2.x is showing correct design. I think need to check design for 2.3 only.

**Comment by ananth-iyer** [comment]
@sdzhepa Because of this PR changes my design changes are affected, let me know my next step: https://github.com/magento/magento2/pull/10651

**Comment by ananth-iyer** [comment]
@sdzhepa I have fixed the issue you mentioned in below:

> Hello @ananth-iyer
> Thank you for contribution and collaboration!
> 
> We found this PR does not fix mentioned issue but brings a new one.
> Could you please have a look and fix it?
> 
> Please, see attached GIF for more details
> bcbf30cb-1cae-47f5-8d54-9a3dfe8e0a05

New design for submenu in Massaction:
ezgif-3-ab436f3fc11c

**Comment by sdzhepa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [new Magento instance](https://pr-20938.instances.magento-community.engineering).
Admin access: [https://pr-20938.instances.magento-community.engineering/admin](https://pr-20938.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by Ctucker9233** [comment]
@magento-engcom-team is a 2.2 backport planned?

**Pull request merged**
