### PR TITLE
Fix #26504 - Broken reference errors pilling up logs

### LINKED ISSUE #26504: Broken reference errors piling up logs
Logs becoming bloated and Sentry going crazy with broken reference errors.

```
$ cat var/log/system.log | grep "Broken reference"
[2020-01-23 03:32:33] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:32:39] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:33:44] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:33:45] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:35:56] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:37:41] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:38:48] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:41:30] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:41:32] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:42:48] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:42:50] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:42:51] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:42:52] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:43:05] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:43:07] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:43:15] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:43:17] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:43:29] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:43:45] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:44:26] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:44:28] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:44:46] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:45:01] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:45:03] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:46:15] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:46:25] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:47:41] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:47:56] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:49:35] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []
[2020-01-23 03:49:37] .WARNING: Broken reference: The element with the "category.view.container" ID wasn't found. Verify the ID and try again. [] []

```

The only occurance of changing "category.view.container." is in our theme:

```
app/design/frontend/Theme/theme/Magento_Theme/layout/default.xml:
<move element="content.top" destination="category.view.container" />
```

### Preconditions (*)

1. Magento 2.3.3 & 2.4-develop
2. Custom theme extended from Luma

### Steps to reproduce (*)

1. Extend luma theme
2. Move the container:

```
app/design/frontend/Theme/theme/Magento_Theme/layout/default.xml:
<move element="content.top" destination="category.view.container" />
```
3. Browse website etc. and check logs after a while

### Expected result (*)

Stop bloating the logs.

### Actual result (*)

Bloating of logs with useless errors.

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

All of other **Broken reference** logs across Magento are only logged in developer mode. This PR fixes the only place from which it was logged also in production mode, possibly causing pilling up of logs

### Fixed Issues (if relevant)

1. Fixes magento/magento2#26504

### Manual testing scenarios (*)

Please check fixed issue for steps to reproduce

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Bartlomiejsz** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @Bartlomiejsz,
Could you cover your changes with some type of test?

**Comment by Bartlomiejsz** [comment]
Hi @ihor-sviziev, to be honest I'm not sure here. Whole GeneratorPool class is pretty complex, and currently have no unit tests (MFTF are not applicable I believe).
So to cover this one minor change (which is already part of few other classes in core) I would have to write test for `process` method which, as mentioned is very complex at this point and this has nothing to do with my change.

**Comment by ihor-sviziev** [comment]
@Bartlomiejsz yeah, make sense. So I changed label to "not required".
Thank you!

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing functional tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7692](https://jira.corp.magento.com/browse/ENGCOM-7692) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
1. Custom theme extended from Luma;
2. Enabled Production mode;

**Manual testing scenario:**

1. Extend luma theme;
2. Move the container: 
`app/design/frontend/Theme/theme/Magento_Theme/layout/default.xml`:
```
<move element="content.top" destination="category.view.container" />
```
3. Go to Storefront and browse different pages;
4. Check **system.log** file

**Before:** :heavy_multiplication_x: Logs are full of Broken reference errors

Screenshot from 2020-06-17 11-50-21

After: :heavy_check_mark: Broken reference errors are only logged in developer mode

**Pull request merged**
