### PR TITLE
[Backport] Replacing deprecated methods for tests.

### PR DESCRIPTION
**Pull request by tiagosampaio**
### Original Pull Request 
 https://github.com/magento/magento2/pull/17645
Replacing deprecated methods for tests.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @tiagosampaio. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by okorshenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, thank you for the review.
[ENGCOM-2900](https://jira.corp.magento.com/browse/ENGCOM-2900) has been created to process this Pull Request

**Comment by osrecio** [comment]
@okorshenko @miguelbalparda Maybe is a good idea combine PR: https://github.com/magento/magento2/pull/17871 in this PR. 

What do you think?

**Comment by okorshenko** [comment]
@magento-engcom-team combine 17871

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
@tiagosampaio all pull requests have been successfully combined together: 
 - merged https://github.com/magento/magento2/pull/17871: [Backport] Replacing deprecated methods for Magento_Security module.

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-2900](https://jira.corp.magento.com/browse/ENGCOM-2900) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @tiagosampaio. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
