### PR TITLE
#23990: Reset not working properly in Add review from admin

### PR DESCRIPTION
**Pull request by konarshankar07**
### Description (*)

This PR is regarding the improper behaviour of the reset button in review form in admin
### Fixed Issues (if relevant)

1. magento/magento2#23990: Reset not working properly in Add review from admin

### Manual testing scenarios (*)

1. Go to Admin
2. Marketing -> All Reviews -> New Review
3. Click any product
4. Fill all data
5. Click on Reset
6. The form is reset to blank values

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-5737](https://jira.corp.magento.com/browse/ENGCOM-5737) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @konarshankar07 

During testing we faced an issue.

_**Problem:**_  "Product Rating" block is not cleared after pressing the "Reset" button

**Actual Result:**
screen

@konarshankar07  Could you take a look, please?

Thanks!

**Comment by konarshankar07** [comment]
Hello @engcom-Alfa ,
Can you please add the steps to reproduce the above issue? Cause I'm not getting the review star
Thanks

**Comment by engcom-Alfa** [comment]
Hi @konarshankar07 

**Steps to reproduce:**
1. Login to Admin;
2. Create simple product;
3. Go to Stores->Attributes->Ratings;
4. Click on "Price" from the grid;
5. In "Rating Visibility" tab select "Default Store View";
6. Click on "Save Rating" button;
7. Repeat 4-6 steps for "Quality" and "Value" ratings;
8. Go to Marketing->All Reviews->New Review;
9. Select created before product;
10. Click on "Default Store View" in "Visability" block ;
11. Fill all required fields;
12. Click on "Reset" button;

**Actual Result:**
screen

@konarshankar07 Could you take a look?

Thanks!

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-5737](https://jira.corp.magento.com/browse/ENGCOM-5737) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by aleron75** [comment]
The PHPMD test fails because a method is 101 lines long instead of 100.

Given that the best practice would suggest refactoring the method since it's just one too many you can suppress that warning adding the following at the end of the docblock:

`@SuppressWarnings(PHPMD.ExcessiveMethodLength)`

**Pull request merged**
