### PR TITLE
MFTF: Admin Login As Customer - Change Account Information Test

### PR DESCRIPTION
**Pull request by DmitryTsymbal**
This PR contains a test for changing customer Information using Login As Customer functionality

**Steps to reproduce:**

1 - Create a customer

2 - Login to customer's account using Login As Customer functionality

3 - Update Customer's information

4 - Perform assertions

### CODE REVIEW

**Comment by DmitryTsymbal** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run all tests

**Comment by DmitryTsymbal** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by dmytro-ch** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B

**Comment by dmytro-ch** [comment]
@magento run Functional Tests EE

**Comment by dmytro-ch** [comment]
@magento run Functional Tests EE

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-9033](https://jira.corp.magento.com/browse/ENGCOM-9033) has been created to process this Pull Request

**Comment by eduard13** [comment]
@magento create issue

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-9033](https://jira.corp.magento.com/browse/ENGCOM-9033) has been created to process this Pull Request

**Comment by eduard13** [comment]
@magento create issue

**Comment by engcom-Charlie** [comment]
Hi @DmitryTsymbal 

Thanks for the contribution!

While setting up your branch on local for testing, we are getting below errors:

image

We have followed below steps:
	1.	Git clone via git clone https://github.com/DmitryTsymbal/magento2.git command.
	2.	Git checkout in-branch via git checkout AdminLoginAsCustomerChangeAccountInformation command.
	3.	Running composer install. And then we are getting above error.

Can you please help us on this.

Thank you in advance!

**Comment by DmitryTsymbal** [comment]
Hello @engcom-Charlie 
Thank you for the update. I have been merged 2.4-develop into working branch and was able run "composer install" command successfully without any issues.
Please check.
Thanks!

**Comment by DmitryTsymbal** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @DmitryTsymbal,

The setup is working fine now. I am able to do composer install in PR branch. Moving the issue to Ready for Testing.

**Pull request merged**
