### PR TITLE
Bugfix/13266 Update the processing of items for the top menu

### PR DESCRIPTION
**Pull request by arnoudhgz**
Original PR: https://github.com/magento/magento2/pull/13323 (was closed, but recreated on request by @orlangur )

### Description
The counter in the foreach loop was not being calculated correctly. This resolved in the 'last' css class not being set on the output when one or more parent items are not active.

With this PR the items will be filtered first before they are being processed for the html output.

### Fixed Issues (if relevant)
1. magento/magento2#13266: Topmenu 'last' class not being set if the a parent is inactive

### Manual testing scenarios
1. Do a clean install of Magento 2.2 with sample data
2. Set a level 1 category (e.g. Gear or Gift Cards) inactive
3. Refresh the appropriate cache
4. Inspect the menu and see there is a class last on the **last** active top menu item

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @arnoudhgz. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by arnoudhgz** [comment]
@orlangur It was quite difficult to reduce the complexity of the _getHtml method. When creating more private methods the complexity for the class became bigger. 

But it seemed solved now.

**Comment by arnoudhgz** [comment]
@orlangur I closed the previous PR, you requested me to add it again... could you please review it (I know you have a lot on your plate :) )

**Comment by arnoudhgz** [comment]
@orlangur @sidolov how do I get this PR reviewed? I don't get what I need to do....

**Comment by orlangur** [comment]
@arnoudhgz sorry, looks like I didn't post review yet http://prntscr.com/l17jbw. Will review shortly.

**Pull request closed without merging**
