### PR TITLE
MAGESHIP-21 Add Shipping Tracking URL to DB, API and email template

### PR DESCRIPTION
**Pull request by RhodriOwainDavies**
**Please beware this is critical for Magento Shipping (to be released in v2.2.2 - discuss with @joni-jones @orlangur & Nadia Kalinovich**

### Description
Add a new field sales_shipment_track.track_url.
Expose this field via API.
Including this URL as a hyperlink in the Shipment Sent Email template.

### Feature
To support impending Magento Shipping feature request of inserting Carrier Specific URL in email template to Customer

### Manual testing scenarios
1. API Test
POST /V1/order/{orderId}/ship
Pass in tracking_url as an extension attribute (in same manner as tracking_number)
2. UI Test
In the admin section, view a Shipment which already has a trackinging URL set (via API in Test #1).  Click Send Tracking Email.  Check email, Tracking Number should be a hyperlink to tracking_url

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [  ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by ishakhsuvarov** [comment]
Hi @RhodriOwainDavies
`2.2.1-preview` branch is not intended to be used as Pull Request target. Please use `2.2-develop` to deliver code for upcoming `2.2.x` releases.
Thank you

**Comment by orlangur** [comment]
@RhodriOwainDavies could you please just reopen https://github.com/magento/magento2/pull/10799 and continue work there? As it was already reviewed and in such a way it would be easier to track changes.

**Comment by RhodriOwainDavies** [comment]
Unfortunately, I don't have the permissions to re-open [#10799|https://github.com/magento/magento2/pull/10799] - if you can re-open that one, I'll update the code on there.

**Comment by orlangur** [comment]
Here you go! Please change target to `develop` branch also and (ideally) squash the changes into single commit (or we can do it after all CR notes are fulfilled and the build is green).

**Pull request closed without merging**
