### PR TITLE
Include custom source model options in attribute index

### PR DESCRIPTION
**Pull request by rain2o**
### Description
When a multiselect Product Attribute uses a custom source model those values are not included when indexing the attribute values for filters on the product grid. The result is those attributes cannot be used as a filter in the product grid. 

This was originally opened as [issue #417](https://github.com/magento/magento2/issues/417) but was closed as it was considered a feature request and moved to the forums [here](https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/Attribute-Indexing-ignores-custom-source-model-options/idi-p/46851). The solution is based on @maderlock's comment [here](https://github.com/magento/magento2/issues/417#issuecomment-265146285) but replaced the use of `ObjectManager` with dependency injection of `AttributeRepositoryInterface`.

### Fixed Issues (if relevant)
1. magento/magento2#417 : Attribute Indexing ignores custom source model options

### Manual testing scenarios
1. Create a multiselect attribute with a custom source model. 
2. Within the attribute set Use in Layered Navigation to "Filterable (with results)"
3. Select one or more values for the given attribute on two or more products in the same category.
4. View the category page. The new attribute should now be an available filter.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16727) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=16727) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: rain2o<br/>:x: Rain2o<hr/>**Rain2o** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by magento-engcom-team** [comment]
Hi @rain2o. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
Nowadays all changes must be applied to `2.3-develop` first (see https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules). Please prepare a new pull request, this one should be `on hold` until the latter is merged.

**Comment by rain2o** [comment]
Thanks for the update @orlangur . I don't think that was the case when I originally submitted. New PR has been requested for 2.3 at #19176. Just waiting for everything to process.

**Comment by orlangur** [comment]
@rain2o,

> I don't think that was the case when I originally submitted

Sure thing, default branch was changed in September.

**Pull request closed without merging**
