### PR TITLE
magento#38805: Issue at product import when provided with custom options-type: file

### LINKED ISSUE #38805: Issue at product import when provided with custom options-type: file (Created Product does not contain price for custom-option and show only the first file type extension provided)
### Preconditions and environment

- Magento version: 2.4.7
- PHP-8.3

Attached the CSV used during the testing.
[export_catalog_product_20240606_161012.csv](https://github.com/user-attachments/files/15613984/export_catalog_product_20240606_161012.csv)

### Steps to reproduce

1. Create a CSV file for product import.
2. Add the necessary data for the product along with custom_options.
3. Add the type: file and other data for the custom_options column. Make sure to add more than one file_extension attribute.
4. Navigate to System>Import.
5. Choose Entity type: Products and Import behaviors: Add/Update. Leave the remaining settings as default. (separators: ",")
6. Validate and Import the Product.
7. Check the created product customization options section on the edit product page. The price is missing and file extension show only the first extension provided in the CSV.

### Expected result

Screenshot from 2024-06-06 16-01-46

### Actual result

Screenshot from 2024-06-06 16-33-41

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by yaroslav-kozar**
Ensure the import with custom options works properly for the 'file' type.

### Description (*)
- Fixed the issue with parsing 'file_extension' data.
- Resolved the issue where the price was not set for the custom-options file type.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38805

### Manual testing scenarios (*)

1. Create a CSV file for product import.
2. Add the necessary data for the product along with custom options.
3. Add the type file and other data for the custom options column. Ensure you include more than one file_extension attribute.
4. Navigate to System > Import.
5. Choose Entity type: Products and Import behavior: Add/Update. Leave the remaining settings as default (separators: ",").
6. Validate and import the product.
7. Check the created product customization options section on the edit product page. Ensure the price is set and file extensions are displayed properly.

**Attached the CSV used during the testing.**
[catalog_product.csv](https://github.com/user-attachments/files/16192938/catalog_product.csv)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Yaroslav1301** [comment]
@magento run all tests

**Comment by Yaroslav1301** [comment]
@magento run all tests

**Comment by Yaroslav1301** [comment]
@magento run Functional Tests CE

**Comment by Yaroslav1301** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by Yaroslav1301** [comment]
@magento run Functional Tests EE, Functional Tests B2, Functional Tests CE

**Comment by Yaroslav1301** [comment]
Functional Tests CE failures are different on last two run on same commit:
Run 1
image

Run 2 
image

Functional Tests B2B - not related to my PR.
image

Functional Tests EE - not related to my PR.
image

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
Hi @Yaroslav1301,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Create a CSV file for product import.
- Add the necessary data for the product along with custom options.
- Add the type file and other data for the custom options column. Ensure you include more than one file_extension attribute.
- Navigate to System > Import.
- Choose Entity type: Products and Import behavior: Add/Update. Leave the remaining settings as default (separators: ",").
- Validate and import the product.
- Check the created product customization options section on the edit product page. Ensure the price is set and file extensions are displayed properly.


**Before:** :heavy_multiplication_x: 

Screenshot 2024-07-23 at 14 16 10




**After:** :heavy_check_mark: 



Screenshot 2024-07-23 at 14 35 53



Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Unit Tests

**Comment by engcom-Charlie** [comment]
Few test failures in recent 2 builds for functional B2B are not consistent and remaining are known issues.

**Functional B2B: Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38926/160c52709da3872f5873915709e1150a/Functional/allure-report-b2b/index.html#categories
image

**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38926/c99967efa9bb347827a643d0abb829f1/Functional/allure-report-b2b/index.html#categories/a644910ae0cb11e839a98baa21929b76/1c476d5ca9970f9c/

image

**Known issues in B2B:**
1. StorefrontAddBundleDynamicProductToShoppingCartWithDisableMiniCartSidebarTest: [#ACQE-6786](https://jira.corp.adobe.com/browse/ACQE-6786)
2. StorefrontLoginFormCheckDuplicateValidateMessageTest: [#ACQE-6799](https://jira.corp.adobe.com/browse/ACQE-6799)
3. TierPricingWhenPriceScopeIsWebsiteWorkingProperlyWithMultipleCurrenciesConfiguredTest: [#ACQE-6695](https://jira.corp.adobe.com/browse/ACQE-6695)
4. StorefrontCashOnDeliveryPaymentForSpecificCountryTest: [#ACQE-6774](https://jira.corp.adobe.com/browse/ACQE-6774)

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
Few test failures in recent 2 builds for functional EE are not consistent and remaining are known issues. Hence moving this to Merge in Progress

**Functional B2B: Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38926/2275c173863de41716cbc9f636ca56d3/Functional/allure-report-ee/index.html#categories/a62c3d6db6631ba28c4130df03eca285/40aabd6b5fd9b4b/

image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38926/c1659c8a572ba859325dd65148e32337/Functional/allure-report-ee/index.html#categories/8f0831c1d06562890f5ec21062dae309/2f40d06202ced82e/

image

**Known issues in EE:**
1. StorefrontAddBundleDynamicProductToShoppingCartWithDisableMiniCartSidebarTest: [#ACQE-6786](https://jira.corp.adobe.com/browse/ACQE-6786)
2. StorefrontCashOnDeliveryPaymentForSpecificCountryTest: [#ACQE-6774](https://jira.corp.adobe.com/browse/ACQE-6774)
3. StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest: [#ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331)
4. StorefrontLoginFormCheckDuplicateValidateMessageTest: [#ACQE-6799](https://jira.corp.adobe.com/browse/ACQE-6799)
5. TierPricingWhenPriceScopeIsWebsiteWorkingProperlyWithMultipleCurrenciesConfiguredTest: [#ACQE-6695](https://jira.corp.adobe.com/browse/ACQE-6695)
6. BannerValidateVideoBackgroundVideoURLs: [#ACQE-6828](https://jira.corp.adobe.com/browse/ACQE-6828)

**Pull request merged**
