### PR TITLE
Upgrade jquery to 3.6.0

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

This pull efforts to upgrade jquery to version 3.6.0
added resolve passive event listeners problem on mobile (touchstart) when call preventDefault

https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.js
minify version
https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js

jquery-migrate 3.3.2
https://code.jquery.com/jquery-migrate-3.3.2.js

Guide
https://jquery.com/upgrade-guide/3.0/

Remain works
-remove old patches (jQuery UI - v1.12.1)
https://github.com/magento/magento2/tree/2.4-develop/lib/web/jquery/patches
seperate each components to individual package

-check compatible with remain widgets
https://github.com/magento/magento2/tree/2.4-develop/lib/web/jquery (Main here)
Other places in external modules, EE, v.v

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

Should we minimal jquery widget ?

'jquery-ui-modules/core',
'jquery-ui-modules/accordion',
'jquery-ui-modules/button',
'jquery-ui-modules/datepicker',
'jquery-ui-modules/dialog',
'jquery-ui-modules/draggable',
'jquery-ui-modules/effect',
'jquery-ui-modules/menu',
'jquery-ui-modules/mouse',
'jquery-ui-modules/position',
'jquery-ui-modules/progressbar',
'jquery-ui-modules/resizable',
'jquery-ui-modules/selectable',
'jquery-ui-modules/slider',
'jquery-ui-modules/sortable',
'jquery-ui-modules/tabs',
'jquery-ui-modules/timepicker',
'jquery-ui-modules/tooltip',
'jquery-ui-modules/widget'

Instead load all above. We only use on demands files

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by tuna2smc** [comment]
remain task upgrade jquery ui following magento seperate to modules

**Comment by mrtuvn** [comment]
remain task upgrade jquery ui (current latest 1.12.1) following magento seperate to modules

**Comment by xmav** [comment]
Hi @mrtuvn !
Thank you for this contribution! Cannot wait to see build results )

**Comment by xmav** [comment]
@mrtuvn Let me share some info: We(magento team) are working on jquery-ui upgrade. Please contact me if you plan to work on jquery-ui upgrade so we can sync and avoid duplication in efforts

**Comment by mrtuvn** [comment]
Hi @xmav you can work directly on this branch

**Comment by fascinosum** [comment]
@magento run all tests

**Comment by tuna2smc** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@xmav Can you deliver this error note to team
mage-backend-tabs
I also got this issue before

**Comment by xmav** [comment]
Hi @mrtuvn 
Could you provide steps to reproduce issue above ?

**Comment by mrtuvn** [comment]
Upgrade to jquery 3.6.0 + jquery ui to latest -> Go to admin

**Comment by mrtuvn** [comment]
@magento run Unit Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by mrtuvn** [comment]
rebase + run check again
@magento run all tests

**Comment by krissyhiserote** [comment]
@mrtuvn  We recently merged our code for the jquery ui upgrade to 1.12.1.  Could you please make sure you have the latest code in your branch and run builds again?

**Comment by mrtuvn** [comment]
Yes i have rebase new code to branch

**Comment by krissyhiserote** [comment]
@mrtuvn so it looks like there are still some test failures.  Would you like to split up this work to get these failures fixed?  My team would be willing to look at some or all these test failures.

**Comment by mrtuvn** [comment]
@magento run Unit Tests, Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run Unit Tests, Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by krissyhiserote** [comment]
@mrtuvn We will take the functional test failures and start fixing those unless you tell me otherwise.  We will fix these in our own branch, but I will make sure your branch is synced with ours.

**Comment by mrtuvn** [comment]
@krissyhiserote i will let this PR like this. Other fix can do by another seperate PR.

**Comment by bondmedia007** [comment]
Afternoon all, Our Penetration testers have found that the current jQuery version used in Magento 2.4.3 is vulnerable in some means to hackers does this thread relate to the issue found?

**Comment by mrtuvn** [comment]
2.4.3 still use old version jquery. This pr will update to higher version

**Comment by bondmedia007** [comment]
@mrtuvn thanks for letting me know, when you say internal team do you mean the guys working at Magento?

**Comment by in-session** [comment]
I would like to add some comments on the subject: https://github.com/magento/magento2/pull/34559#issuecomment-964832285

**Comment by mrtuvn** [comment]
Yes @xmav may know more details

**Comment by Rrego6** [comment]
Hi there, @mrtuvn . If you get a chance, could you help me understand the reason for changes to `lib/web/jquery/patches/jquery.js`? To me, it makes more sense to remove this file entirely.

**Comment by mrtuvn** [comment]
That file apply fixes for lighthouse warn "Does not use passive listeners to improve scrolling performance"

**Comment by mrtuvn** [comment]
Pull latest code to branch
@magento run all tests

**Comment by Rrego6** [comment]
@mrtuvn I don't think that lighthouse warnings are necessary to fix for this upgrade. The upgrade does not cause these issues correct?

This change to patches breaks our unit tests since the function signature for the callback in the patch is not valid.  (ns is null)

**Comment by mrtuvn** [comment]
I can remove that file in this scope of ticket. And tracking warning lighthouse in seperate PR/ticket

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, Unit Tests

**Comment by mrtuvn** [comment]
Deleted file patches jquery
@magento run Unit Tests

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
Closed this because internal team already updated jquery

**Comment by mrtuvn** [comment]
I'm not sure maybe @xmav @sidolov may know this

**Comment by bondmedia007** [comment]
Thank you @mrtuvn look forward to hearing from @xmav and @sidolov have a great day.

**Comment by xmav** [comment]
I am not aware of plans to backport this to 2.4.3

**Comment by kirmorozov** [comment]
Good Luck :) I tried it years ago.
https://github.com/magento/magento2/issues/13685

**Pull request closed without merging**
