### PR TITLE
Add store id to retrieve localized content from category repository

### PR DESCRIPTION
**Pull request by mirkocesaro**
### Description
This commit solves an issue with the anchor category url generation.
To generate the anchor category url, data is retrieved by category repository without specifying  proper store id. Doing so, the generated url does not use the localized category name into request path.

### Manual testing scenarios
1. We assume we are working with Magento with one website and (at least) two storeviews:
  - store ID: 1 (default)
  - store ID: 2
2. Create an **anchor** category "test" (let say it has id 456) under Default Category with different url key for the storeviews:
  - url_key for store 1 : test-foo
  - url_key for store 2 : test-bar
3. Create a child category of "test" named "test child" and assign one product whose url_key is for exaple: "my-product" (let say id 123)

Expected result:
In the url_rewrite table we exepct to find the following rows:

```
entity_type|entity_id|target_path                             |request_path            |store_id|
-----------|---------|----------------------------------------|------------------------|--------|
product    |123      |catalog/product/view/id/123/category/456|test-foo/my-product.html|1       |
product    |123      |catalog/product/view/id/123/category/456|test-bar/my-product.html|2       |
```

Actual result:

```
entity_type|entity_id|target_path                             |request_path            |store_id|
-----------|---------|----------------------------------------|------------------------|--------|
product    |123      |catalog/product/view/id/123/category/456|test-foo/my-product.html|1       |
product    |123      |catalog/product/view/id/123/category/456|test-foo/my-product.html|2       |

```
as we can see the request_path value for the second row (store_id 2) is not as expected 

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22212) <br/>All committers have signed the CLA.

**Review by phoenix128 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @phoenix128, thank you for the review.
[ENGCOM-4701](https://jira.corp.magento.com/browse/ENGCOM-4701) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@mirkocesaro thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by hostep** [comment]
Thanks for the PR @mirkocesaro 

But we already have two competing PR's with the exact same changes:
- 2.3: https://github.com/magento/magento2/pull/20826
- 2.2: https://github.com/magento/magento2/pull/14344

@phoenix128, we should probably close this PR as a duplicate, right?

**Comment by sivaschenko** [comment]
Hi @mirkocesaro , thanks for the pull request! However, I have to close it as it's a duplicate to https://github.com/magento/magento2/pull/20826

**Pull request closed without merging**
