### PR TITLE
magento/magento2#36928: 504 gateway timeout when creating configurabl…

### LINKED ISSUE #36928: 504 gateway timeout when creating configurable product on dev instance
### Preconditions and environment

- 2.4.x develop

### Steps to reproduce

Clone a configurable product. 
Try to create variations for 5 colors and 5 sizes. 
Add 3 images to the products. 
Click on save

### Expected result

Product is saved relatively fast 5-15 seconds

### Actual result

504 gateway timeout

### Additional information

As you can see in the following video there are multiple issues in usability. 

First of all after cloning the product there is noeasy way to disassociate the previous ones. 

Secondly while adding the new variations, with default settings there's a timeout. 

If saving a product takes so long, it's detrimental to the shop owner as he's paying his employees to just wait for Magento to save. 

Compared to other platforms Woocommerce / CsCart, Prestashop, the saving process is extremely slower. 

https://user-images.githubusercontent.com/20220341/221552550-e0a6f23d-f7e9-4ed5-ad99-30da8bad227d.mp4

The video was taken using the magento instance that the bot created but it's similar in production systems

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Alexander-Khohklov**
- fixed 504 gateway timeout when creating configurable product
 
### Description (*)
Was finded commits that are able to fix similar bug, 
MC-42892: [Performance] Product image resize function onsave taking long time when saving product images in admin panel.
But there is absent argument in Admin area.
Absent argument was added and fixed in this PR.

### Fixed Issues
1. Fixes magento/magento2#36928

### Manual testing scenarios (*)
1.Install Magento instance
2.Create one configurable product and clone the product
3.Create configurations with 5 variations colour and size
4.Add three images for the products
5.save the product

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Alexander-Khohklov** [comment]
@magento run Functional Tests B2B

**Comment by Alexander-Khohklov** [comment]
@magento run Unit Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by Alexander-Khohklov** [comment]
@magento run Unit Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by Alexander-Khohklov** [comment]
@magento  run Unit Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by Alexander-Khohklov** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by Alexander-Khohklov** [comment]
@magento run Unit Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by Alexander-Khohklov** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Comment by Alexander-Khohklov** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]
Failed test seems flaky to me

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Lima** [comment]
@magento give me test instance

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**
1.Install Magento instance
2.Create one configurable product and clone the product
3.Create configurations with 5 variations colour and size
4.Add three images for the products
5.save the product.

**Before:** :heavy_multiplication_x: Getting 504 error.

Screenshot 2023-04-06 at 1 31 07 PM

**After:** :heavy_check_mark:  Now working fine.
Screenshot 2023-04-06 at 1 44 44 PM

**Pull request merged**
