### PR TITLE
Removed unused class imports 

### LINKED ISSUE #29012: [Issue] Removed unused class imports
This issue is automatically created based on existing pull request: magento/magento2#28696: Removed unused class imports 

---------

### Summary (*)

Magento 2.4-develop
This PR removes redundand class imports for some classes

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR removes redundand class imports for some classes

### Resolved issues:
1. [x] resolves magento/magento2#29012: Removed unused class imports

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Review by aleron75 — APPROVED** [review]

**Comment by aleron75** [comment]
There are some failing tests related to B2B but I don't see any relation with this PR so I approved it.

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-7673](https://jira.corp.magento.com/browse/ENGCOM-7673) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked cases create customer on frontend and in admin panel, refactored patches are applied without errors during magento install and `setup:upgrade`
#28696PR

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@magento create issue

**Pull request merged**
