### PR TITLE
updating lib LESS docs

### PR DESCRIPTION
**Pull request by Karlasa**
Seems like LESS docs are bit outdated. planning on going through all the files. Here is the first part :) 

### Description
Keeping LESS lib docs up to date as in PR #11371 .lib-url-check is removed 

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Karlasa. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by Karlasa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Karlasa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Karlasa, here is your [new Magento instance](https://pr-17479.engcom.dev.magento.com).
Admin access: [https://pr-17479.engcom.dev.magento.com/admin](https://pr-17479.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`

**Comment by Karlasa** [comment]
docs are cleaned up :)

**Comment by VladimirZaets** [comment]
Hi @Karlasa. Thanks for collaboration. I think this fixes better to delivery to Magento 2.3 version. This fixes looks like cleanup. But according to [Magento Code Contributions Guide](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#rules) we don't delivering code cleanup to Magento 2.2 version

**Comment by Karlasa** [comment]
@VladimirZaets #17097 is backport to 2.2 and was merged so i see no issue about that. And as it's actually just doc about code not code itself. Could as easly called it a bug, because code examples do not work as expected in LESS docs

**Comment by VladimirZaets** [comment]
@Karlasa [The Magento Code Contributions Guide](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#rules) was updated after that PR was merged. But you make sense, this issue we can consider as a bug.

**Comment by magento-engcom-team** [comment]
Hi @Karlasa. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
