### PR TITLE
magento/magento2#23138: Magento_Theme. Incorrect configuration file location 

### PR DESCRIPTION
**Pull request by atwixfirster**
### Description (*)

Pull request provides fix for #23138 ticket.
### Fixed Issues (if relevant)

1. magento/magento2#23138: Magento_Theme. Incorrect configuration file location 

### Manual testing scenarios (*)

1. Go to `STORES` > `Configuration` > `ADVANCED` > `Developer` > `JavaScript Settings`

**Expected result:** `Move JS code to the bottom of the page` option should be available for administrator:

23140-01-min

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

Thank you!

### CODE REVIEW

**Review by orlangur — CHANGES_REQUESTED** [review]
@atwixfirster please provide actionable steps to reproduce in issue (for instance, functionality which didn't work due to wrong configuration file location).

**Comment by hostep** [comment]
@atwixfirster: good find! I noticed the same problem a couple of weeks ago and then completely forgot about reporting it here.

Can you test if removing the file entirely keeps the configuration field working? Because the same configuration field also exists in the file [`app/code/Magento/Backend/etc/adminhtml/system.xml`](https://github.com/magento/magento2/blob/1c2bcb117b1a8d8f2cb1badb95fd286cbee31677/app/code/Magento/Backend/etc/adminhtml/system.xml#L185-L188)

I'm suspecting the file `app/code/Magento/Theme/etc/system.xml` was added by accident in https://github.com/magento/magento2/commit/91bdb745e71

The correct fix here would probably be to remove the file `app/code/Magento/Theme/etc/system.xml`.

(also: please don't edit posts of other members here, that's not the correct way of replying to a question 😉)

**Comment by atwixfirster** [comment]
Hi, @orlangur !

> @atwixfirster please provide actionable steps to reproduce in issue (for instance, functionality which didn't work due to wrong configuration file location).

I've updated PR description. Regarding [documentation](https://devdocs.magento.com/guides/v2.3/config-guide/config/config-files.html) `system.xml` should locate in the `etc/adminhtml` folder.

So, my PR moves `app/code/Magento/Theme/etc/system.xml` to `app/code/Magento/Theme/etc/adminhtml/system.xml`.

Please approve :)

Thank you!

**Comment by atwixfirster** [comment]
Hi, @hostep!

Thank you for your notices!


> Can you test if removing the file entirely keeps the configuration field working? Because the same configuration field also exists in the file [`app/code/Magento/Backend/etc/adminhtml/system.xml`](https://github.com/magento/magento2/blob/1c2bcb117b1a8d8f2cb1badb95fd286cbee31677/app/code/Magento/Backend/etc/adminhtml/system.xml#L185-L188)
> I'm suspecting the file `app/code/Magento/Theme/etc/system.xml` was added by accident in [91bdb74](https://github.com/magento/magento2/commit/91bdb745e71)
> 
> The correct fix here would probably be to remove the file `app/code/Magento/Theme/etc/system.xml`.
> 
File  `app/code/Magento/Theme/etc/system.xml` has been **removed** in favor of `app/code/Magento/Backend/etc/adminhtml/system.xml` configuration .

> (also: please don't edit posts of other members here, that's not the correct way of replying to a question 😉)

It was an accident. I've reverted my changes in Vlad's comment

😊 

Thank you again!

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5241](https://jira.corp.magento.com/browse/ENGCOM-5241) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
