### PR TITLE
Allow underscore and slash in URL rewrite

### PR DESCRIPTION
**Pull request by maximecarey**
### Description
Add forward slash (/) and underscore (_) in the permitted characters of the TranslitUrl filter, allowing to create URLs rewrite with these in it. I was trying to create URLs with the /{SKU}/name format. Thought that this should be built-in.

### Fixed Issues (if relevant)

1. magento/magento2#7040: Trailing Slash in Product URLs No longer working

### Manual testing scenarios

1. Create a product
2. Change it's URL so it contains a slash and underscore

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=17478) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @werfu. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-2733](https://jira.corp.magento.com/browse/ENGCOM-2733) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@werfu thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by orlangur** [comment]
@VladimirZaets allowing slashes in URL rewrites will lead to problems in routing, isn't it?

**Comment by maximecarey** [comment]
@orlangur have a look at Magento\UrlRewrite\Controller\Router class. You'll see in the Match function that it try to match the request url with a stored rewrite. If found it rewrite it. Otherwise it return null and normal routing starts. Sure one could create a rewrite that hide a controller action, but you can't prevent a user being dumb.

**Comment by VladimirZaets** [comment]
Hi @werfu. We found a few cases where we have the problem with routing. Could you please check?
**Cases:**
**Case 1:**
Set Stores-Configuration-Catalog-Catalog-Search Engine Optimization-Product URL Suffix=/
Create 3 simple product:
Name and SKU=simple1, URL Key=simple1 ;
Name and SKU=simple2, URL Key=simple1/ ;
Name and SKU=simple3, URL Key=simple1/description ;
Go to simple2 product detail page
**Action result:** simple1 product detail page is opened
**Case 2:**
Set Stores-Configuration-Catalog-Catalog-Search Engine Optimization-Product URL Suffix=/
Create simple product with URL Key=checkout/cart
Add another product to cart.
Click View and Edit Cart.
**Action result:** Simple product detail page is opened instead of cart page.

**Comment by maximecarey** [comment]
@VladimirZaets for case 1 a simple validation to ensure that an URL key doesn't finish with a slash should do the trick. However, for the case 2, I would need a way to enumerate routes exposed by controllers, which I don't know how (still learning M2, moved from M1.9).

**Comment by maximecarey** [comment]
@VladimirZaets pushed the trim to remove trailing slash. Is case 2 a stopper? If a user decides to be dump do we really need to prevent it?

**Comment by VladimirZaets** [comment]
Hi @werfu. Thanks for collaboration. We discussed this case with the team and took the decision that we can't approve your fix because it can broking routing.

**Pull request closed without merging**
