### PR TITLE
ISSUE-14747 Newsletter subscription confirmation message does not dis…

### PR DESCRIPTION
**Pull request by KaushikChavda**
### Fixed Issues (if relevant)

1. magento/magento2#14747: Newsletter subscription confirmation message does not display after clicking link in email

### Manual testing scenarios
1. I've stested with my local enviorment and its working fine.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15242) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=15242) before we can accept your contribution.<br/><hr/>**Kaushik Chavda** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by VladimirZaets** [comment]
Hi @kaushik-chavda, please, sign CLA, otherwise, we can't process your pull request.

**Comment by KaushikChavda** [comment]
Hi @VladimirZaets, I've already signed previously and also tyring to sign again and its showing thank you message for signing the CLA for pull request #15242 
Please help me out, see the attached screenshot.
image

**Comment by VladimirZaets** [comment]
@kaushik-chavda looks like your email in Git account is different with email on Github. 
You need to add email from git `git config --global user.email` to Github and after that try again to sign CLA.

**Pull request closed without merging**
