### PR TITLE
[Forwardport] [Resolved : Changing @tab-content__border variable has no effect in B…

### LINKED ISSUE #14999: Changing @tab-content__border variable has no effect in Blank theme
### Preconditions
Any Magento 2
FE theme inherited from Magento/Blank

### Steps to reproduce
In `Custom/theme/web/css/source/_theme.less` set less variables to:
@tab-content__border-top-status: false;
@tab-content__border: 1px solid #000;

### Expected result
Tabs content has border

### Actual result
Tabs content has no border

### What causes the issue
[web/css/source/_sections.less](https://github.com/magento/magento2/blob/2.2-develop/app/design/frontend/Magento/blank/web/css/source/_sections.less#L24) calls `.lib-data-tabs()` mixin with `@_tab-content-border-top-status: true` argument, so `@tab-content__border-top-status` variable isn't used in  `.lib-data-tabs()`

### Solution
1. Remove `@_tab-content-border-top-status: true` argument in [web/css/source/_sections.less](https://github.com/magento/magento2/blob/2.2-develop/app/design/frontend/Magento/blank/web/css/source/_sections.less#L24) (as it's done in [Magento/Luma](https://github.com/magento/magento2/blob/2.2-develop/app/design/frontend/Magento/luma/web/css/source/_sections.less#L66));
2. Add `@tab-content__border-top-status: true` in [web/css/source/_variables.less](https://github.com/magento/magento2/blob/2.2-develop/app/design/frontend/Magento/blank/web/css/source/_variables.less)

### Workaround
[Create](https://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-guide/css_quick_guide_approach.html#structured_changes) `Custom/theme/web/css/source/_sections_extend.less` with:

```
.media-width(@extremum, @break) when (@extremum = 'min') and (@break = @screen__m) {
    .product.data.items {
        > .item.content {
            ._lib-tab-content-border(
                @_tab-content-border-top-status: @tab-content__border-top-status
            );
        }
    }
}
```

### PR DESCRIPTION
**Pull request by hitesh-wagento**
### Original Pull Request 
 https://github.com/magento/magento2/pull/15914
…heme, fixes #14999

### Fixed Issue

magento/magento2 #14999: Changing @tab-content__border variable has no effect in Blank theme

### CODE REVIEW

**Comment by VladimirZaets** [comment]
Hi, @hiren-wagento, I took your PR into processing, thank you for collaboration.

**Comment by hitesh-wagento** [comment]
@VladimirZaets Could you please check what cause failed travis?

Thanks,

**Comment by hitesh-wagento** [comment]
@VladimirZaets 

Any update in this PR ?

Thanks

**Comment by magento-engcom-team** [comment]
Hi @hitesh-wagento. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.3.0 release.

**Pull request merged**
