### PR TITLE
Reduce unused class in markup

### LINKED ISSUE #32572: Possible nonstandard HTML class in Checkout Authentication template
### Summary (*)
The class `action action-remind` only exist in checkout authentication template for **Forgot Password Link**. In all other pages is used: class="action remind" instead
I didn't find any style or selector using the tag `action-remind`

### Examples (*)
All the following templates use `action remind` instead `action-remind`:
vendor/magento/module-checkout/view/frontend/web/template/form/element/email.html
vendor/magento/module-customer/view/frontend/templates/form/login.phtml

Class ‘action action-remind’ is there in authentication template  Path: app/code/Magento/Checkout/view/frontend/web/template/authentication.html
Other all related files have class ‘action remind’ instead.
Issue: Inaccurate class name added in authentication template

### Proposed solution
Change the class from **action-remind** to **remind** in other words:
Before:
`class="action action-remind"`
After:
`class="action remind"`

or the changes could be done in reverse too.

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Just clean up html markup and reduce unused html class. use `remind` instead old class `action-remind` for anchor links
Note: action-remind class not defined in any less/css files
### Fixed Issues (if relevant)

1. Fixes magento/magento2#32572

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-8972](https://jira.corp.magento.com/browse/ENGCOM-8972) has been created to process this Pull Request

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@nagento run Unit Tests

**Comment by mrtuvn** [comment]
@magento run Unit Tests, Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE

**Comment by engcom-Bravo** [comment]
Hi @mrtuvn,

We are closing this PR.The PR is in Draft since longtime.

Once you are ready Please feel free to reopen it to process the PR further.

Thanks

**Pull request closed without merging**
