### PR TITLE
feat: Add support for middle name in Cart addresses

### LINKED ISSUE #39088: [Issue] feat: Add support for middle name in Cart addresses
This issue is automatically created based on existing pull request: magento/magento2#37464: feat: Add support for middle name in Cart addresses

---------
Add support for middle name in Cart Address (billing, shipping)

### Description (*)
It seems the middle name is currently unsupported for the GraphQL implementation of the Cart addresses. The reason is unclear to me.

### Manual testing scenarios (*)
1. Create a Cart and populate the Billing and / or Shipping Address using a GraphQL mutation including a middle name
2. Check if the middle name is stored in the database
3. Check if the middle name is returned when getting the Cart through a GraphQL query.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [X] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by pmzandbergen**
Add support for middle name in Cart Address (billing, shipping)

### Description (*)
It seems the middle name is currently unsupported for the GraphQL implementation of the Cart addresses. The reason is unclear to me.

### Manual testing scenarios (*)
1. Create a Cart and populate the Billing and / or Shipping Address using a GraphQL mutation including a middle name
2. Check if the middle name is stored in the database
3. Check if the middle name is returned when getting the Cart through a GraphQL query.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [X] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#39088: feat: Add support for middle name in Cart addresses

### CODE REVIEW

**Comment by pmzandbergen** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @pmzandbergen,

Thanks for the contribution!

Just one thing, please cover the changes with some automated tests to verify if the middle name is saving or not.

Thanks

**Comment by engcom-November** [comment]
@magento create issue

**Comment by pmzandbergen** [comment]
I’ll add tests tomorrow.

**Pull request closed without merging**
