### PR TITLE
Remove unnecessary translation of HTML tags

### PR DESCRIPTION
**Pull request by yogeshsuhagiya**
### Description
There is no need to translate string with HTML tags like `<label>` and `<span>`, instead translate only string value.

### Fixed Issues (if relevant)

1. N/A

### Manual testing scenarios
1. N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Yogeshks. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by orlangur** [comment]
We have discussion in mainteiners group now regarding HTML in translated messages, putting on hold until it is finished.

**Comment by yogeshsuhagiya** [comment]
@magento-engcom-team @orlangur Hello team, any updates?

**Review by orlangur — APPROVED** [review]
This was the only occurrence of `<label>` in translation messages.

There are 14 occurrences of `<span>` prior to this change, would be nice if you eliminate all of them 👍

**Comment by yogeshsuhagiya** [comment]
Hello @orlangur , okay I'll try to update all other occurrence of span tag

**Comment by magento-engcom-team** [comment]
Hi @Yogeshks. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
