### PR TITLE
[Backport] fixes-customer-information-wishlist-configurable-product-alignment-2.2

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Description (*)

Original PR: #20558: fixes-customer-information-wishlist-configurable-product-alignment
### Fixed Issues (if relevant)

1. #20760: admin customer information wishlist configurable product alignment issue while editing
Magento 2.2.x

### Manual testing scenarios (*)

1.  Go to admin
2.  In Customers >>All customers>> edit customer>>click on wishlist
3.  Action Configure

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by dmytro-ch** [comment]
Hi @amol2jcommerce,
please consider to port the fixes for functional test and make sure it works.
Thank you!

**Comment by amol2jcommerce** [comment]
* @magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce, here is your [new Magento instance](https://pr-21173.instances.magento-community.engineering).
Admin access: [https://pr-21173.instances.magento-community.engineering/admin](https://pr-21173.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by amol2jcommerce** [comment]
Hi @dmytro-ch I checked & it's work.

**Comment by dmytro-ch** [comment]
I mean the MFTF: https://devdocs.magento.com/mftf/2.2/introduction.html
Thank you!

**Comment by amol2jcommerce** [comment]
Hi @dmytro-ch branch updated. please review.

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-21173.instances.magento-community.engineering).
Admin access: [https://pr-21173.instances.magento-community.engineering/admin](https://pr-21173.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4308](https://jira.corp.magento.com/browse/ENGCOM-4308) has been created to process this Pull Request

**Comment by amol2jcommerce** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  amol@twojay.in
    Domain 2jcommerce.in has exceeded the max emails per hour (268/250 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:28373)
	by mail.2jcommerce.co.uk with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-d057-amol=2jcommerce.in@sgmail.github.com>)
	id 1gw9C8-000Qnr-SP
	for amol@2jcommerce.in; Tue, 19 Feb 2019 17:28:37 +0000
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=aJDT63vorzVOEJF4gagY2V0qxXw=; b=oWo53F7dExlYAPsa
	EbYDxaIPIKt5mc1UGOoPEW15vlphZfGF1ie3K2RktkrvbuxuYUzK5mIoI0mLwSph
	Ly51FRfBzLhIn6jgj8HeUflyCRyfA1VQfBEpgjOUspqaTU0O72lKaJXG1jH9bh/S
	YcOCyehRBfkkQwy8aXo7CDxpA1g=
Received: by filter0327p1iad2.sendgrid.net with SMTP id filter0327p1iad2-15627-5C6C3C9A-50
        2019-02-19 17:27:54.498720379 +0000 UTC m=+79706.652522955
Received: from github-lowworker-e51511d.cp1-iad.github.net (unknown [192.30.252.34])
	by ismtpd0003p1iad2.sendgrid.net (SG) with ESMTP id KImEZRFAT9-A4sf9zezPLw
	for <amol@2jcommerce.in>; Tue, 19 Feb 2019 17:27:54.594 +0000 (UTC)
Received: from github.com (localhost [127.0.0.1])
	by github-lowworker-e51511d.cp1-iad.github.net (Postfix) with ESMTP id 8A7B280C22
	for <amol@2jcommerce.in>; Tue, 19 Feb 2019 09:27:54 -0800 (PST)
Date: Tue, 19 Feb 2019 17:27:54 +0000 (UTC)

**Pull request merged**
