### PR TITLE
added fix to ticket 25455

### PR DESCRIPTION
**Pull request by Ashna-Jahan**
### Fixed Issues (if relevant)

1. magento/magento2#<25455>: Inconsistency with full stops in admin configurations

### Manual testing scenarios (*)

1. Go to Admin > Stores > Configuration > Catalog > Catalog > Store Front.
2. You can now see that the comments under the configurations are consistent with full stops after the sentence after this fix is added.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by nuzil** [comment]
Can you please sign CLA?

**Review by kanthy-i95dev — APPROVED** [review]

**Review by nuzil — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-6231](https://jira.corp.magento.com/browse/ENGCOM-6231) has been created to process this Pull Request
:eight_spoked_asterisk: @nuzil, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@Ashna-Jahan thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Bravo** [comment]
Hello @nuzil. Could You please put an appropriate [label](https://github.com/magento/magento2/pull/25456#issuecomment-549276562) in order for us to be able to further process current PR. Thank You.

**Comment by Ashna-Jahan** [comment]
@nuzil I have signed the CLA.

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
