### PR TITLE
Fix #24713 - Symbol of the Belarusian currency BYR is outdated

### LINKED ISSUE #24713: Symbol of the Belarusian currency BYR is outdated
### Preconditions (*)
**Magento 2.3.x**
Symbol of the Belarusian currency BYR is outdated.
Since 2016, the symbol of the Belarusian currency BYR has become obsolete and is no longer used. 
image
image

Resources:
https://www.xe.com/currency/byr-belarusian-ruble
https://www.xe.com/currencyconverter/convert/?Amount=1&From=BYN&To=USD

### Steps to reproduce (*)
1. Login to admin
2. Go to the Stores --> Configuration--> Currency Setup
3. In Currency Options add "Belarusian Ruble(2000-2016)" to the Allowed Currencies list
4. Go to the Stores--> Currency Rates
5. Check Belarusian Ruble's currency symbol

### Expected result (*)
image

### Actual result (*)
image

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This is fix for #24713. As difference between steps described in issue, `Belarusian Ruble (2000-2016)` should not be the selected currency (this is outdated one), but `Belarusian Ruble` instead. In this PR I replaced all usages of old currency, so valid one would be used as default.

### Fixed Issues (if relevant)

1. magento/magento2#24713: Symbol of the Belarusian currency BYR is outdated

### Manual testing scenarios (*)

1. Login to admin
2. Go to the Stores --> Configuration--> Currency Setup
3. In Currency Options add "Belarusian Ruble" to the Allowed Currencies list
4. Go to the Stores--> Currency Rates
5. Check Belarusian Ruble's currency symbol - it should be equal to `BYN`

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lbajsarowicz — APPROVED** [review]
Verified ( https://en.wikipedia.org/wiki/Belarusian_ruble ), approve.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-6324](https://jira.corp.magento.com/browse/ENGCOM-6324) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Bravo** [comment]
Hello @lbajsarowicz. Would You please mark this PR with an appropriate [label](https://github.com/magento/magento2/pull/25723#issuecomment-557932877). Thank You.

**Review by VladimirZaets — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
