### PR TITLE
MC-23904: Can't Refund Invoice Without 0 Quantities Through REST API

### LINKED ISSUE #23069: Can't Refund Invoice Without 0 Quantities Through REST API
1. The API responds with error "You can't create a creditmemo without products." from the QuantityValidator.

### PR DESCRIPTION
**Pull request by engcom-Echo**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#23069

### Manual testing scenarios (*)

1.  See: magento/magento2#23069

Additional Information:
[Endpoint](https://devdocs.magento.com/guides/v2.4/rest/modules/sales/refunds.html): POST V1/invoice/:invoiceId/refund
_If you try to apply the service to an invoice created using an offline payment method, the system will return a validation error._

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
I believe right now you even can't to refund in the admin, not only through the web api

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Hi @engcom-Echo ,
Could you explain use case when such request could be valid? I believe creating an order and doing credit memo from the admin with screenshots will be good enough

**Comment by engcom-Echo** [comment]
@ihor-sviziev. Thank you for your question. It is important.
Peek 2020-11-04 10-18
---------------------
image

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8421](https://jira.corp.magento.com/browse/ENGCOM-8421) has been created to process this Pull Request

**Review by engcom-Kilo — APPROVED** [review]

**Review by zakdma — APPROVED** [review]

**Comment by engcom-Oscar** [comment]
:heavy_check_mark: QA Passed

### Manual testing scenario
1.Create an order with online payment method, like PayPal Express Checkout and with $0 shipping cost, ex. free shipping.
2.Invoice the order in admin
3.Try to refund the invoice using the 'POST' restAPI call "invoice/{invoiceId}/refund" -  items at quantity 0 and a positive adjustment. For example:
{"items": [{"qty": 0, "orderItemId": 6, "extensionAttributes": {}}], "appendComment": false, "notify": true, "isOnline": true, "arguments": {"adjustment_negative": 0.0, "adjustment_positive": 0.99, "shipping_amount": 0}}

**Before** applying changes provided in the PR, the API responds with error "You can't create a creditmemo without products." from the QuantityValidator.

**Afters** switching to the PR, refund work properly
Screenshot from 2020-11-09 13-03-28

**Comment by zakdma** [comment]
@magento import pull request to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the pull request successfully imported.

**Pull request merged**
