### PR TITLE
MSI-478: Unskip StockStatusFilterTest

### PR DESCRIPTION
**Pull request by kisroman**
### Description
Created new tests for Catalog Search as old wasn't good as an integration test.

### Fixed Issues (if relevant)
1. https://github.com/magento-engcom/msi/issues/478

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15690) <br/>All committers have signed the CLA.

**Comment by orlangur** [comment]
Please make builds green and amend changes with force push.

**Comment by kisroman** [comment]
@orlangur, done. Pls continue review.

**Comment by magento-engcom-team** [comment]
Hi @kisroman. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Pull request merged**
