### PR TITLE
Fixed Issue #20121 Cancel order increases stock although "Set Items' Status to be In Stock When Order is Cancelled" is set to No

### PR DESCRIPTION
**Pull request by shikhamis11**
Fixed Issue #20121 Cancel order increases stock although "Set Items' Status to be In Stock When Order is Cancelled" is set to No

### Preconditions

1. Magento 2.2.6 Community
2. Reproduced on PHP 7.1.18 and 7.1.25
3. MariaDB 10.1.26 and 10.3.11
4. Go to Stores -> Configuration -> Catalog -> Inventory and make sure the following options are set as per below:
 * **Decrease Stock When Order is Placed** to **Yes**
 * **Set Items' Status to be In Stock When Order is Cancelled** to **No**
 * **Manage Stock** to **Yes**
 * **Automatically Return Credit Memo Item to Stock** to **No**
(see screenshot below)
image

### Steps to reproduce

1. Place an order with 1 item of product (i.e. qty = 1)
2. Cancel order

### Expected result

1. Product quantity in product catalog is decreased by 1 after order is created
2. Product quantity remains the same (i.e. does not increase) after order is canceled

### Actual result

1. Product quantity in product catalog is decreased by 1 after order is created
2. Product quantity is increased by 1 immediately after order is canceled

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by aleron75 — APPROVED** [review]

**Comment by aleron75** [comment]
Hello @shikhamis11 thanks for your contribution!

Once merged, don't forget you can easily port this PR to other branches with the Porting Tool, [read more here](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#porting-tool).

**Comment by shikhamis11** [comment]
@aleron75 sure . Thanks :)

**Comment by shikhamis11** [comment]
@magento-engcom-team @aleron75 this Pull request is approved but not assigned in community Pull request why?

**Pull request closed without merging**
