### PR TITLE
[fix] salesrule data corrupted after migration

### PR DESCRIPTION
**Pull request by AurelienLavorel**
### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @AurelienLavorel. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
@AurelienLavorel please provide clear steps to reproduce. Bugs in migration tool should be fixed in migration tool, not in core.

**Comment by AurelienLavorel** [comment]
If you forgot the PR title, don't you think that it's a good idea to check if data exist before inserting it?

**Comment by orlangur** [comment]
@AurelienLavorel no, as emptiness of `$data` may indicate a severe error. https://en.wikipedia.org/wiki/Fail-fast is much better than hide errors.

**Comment by AurelienLavorel** [comment]
I hope that Adobe acquisition will change that mindset, my customers don't want to see errors.

**Comment by orlangur** [comment]
Thanks @AurelienLavorel, it's not about customers seeing errors, it is that we should not hide the root cause.

So, if migration tool produces invalid sales rule data, it should be fixed. Here is the corresponding repo: https://github.com/magento/data-migration-tool

**Comment by AurelienLavorel** [comment]
Fixing data migration tool "only" help new migrations, it's not fixing already live store. We have to override a lot of code for this kind of bug and the correction will never been in main repo. It's time consuming and end user doesn't understand why we have the same bug on multiple projects.

**Pull request closed without merging**
