### PR TITLE
ISSUE-26481 - Allow 'Is Default' radio to be cleared when editing swatch and dropdown attributes

### LINKED ISSUE #26481: Unable to remove default text swatch value and value automatically assigning
When creating a new text swatch, if you click "Is default" you can not undo it and having a blank value is no longer possible. That causes a problem for products where the swatch is optional.

That value will then automatically assign itself to any old products if they are saved, even if you did not select any text swatch value.

### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Add new text swatch attribute with 3 options
2. Values Required = No
3. Do NOT click any "Is Default"
4. Save attribute
5. Assign attribute to attribute set Default
6. Create new product. You can see that the swatch selection is BLANK = CORRECT
7. Edit the attribute again and select "Is Default" on any selection
8. Save attribute
9. Try to edit attribute again, now it is impossible to remove the default option
10. Create a new product again, the default selection is prefilled and you have to manually select "blank" even if the value is supposed to be OPTIONAL with "Values Required"

This also causes a VERY annoying side-bug:

1. Create ANOTHER text swatch attribute
2. Values Required = No
3. Add 3 options and click "Is Default" on any
4. Save attribute and add to attribute set
5. Clear Cache etc.
6. Go into an old product added in previous steps and look at the new swatch value, it should still be blank = correct
7. Save product without doing any changes.
8. Look at the new swatch value. Suddenly it has a value assigned! BY ITSELF!

This causes MAJOR problems.

If you edit an attribute set with a new text swatch. The "default value" will be assigned on ALL products automatically when that product is edited without the intent of the catalog manager.

In fact ANY edit to the product will make it change to the default text swatch value even if you want it to be blank.

### Expected result (*)

A text swatch value should not assign its default value by itself without the catalog managers input.

### Actual result (*)

Text swatch value is assigned by itself, even if left blank upon product save when new attributes are added to the attribute group.

issue_26481_1

### PR DESCRIPTION
**Pull request by zaximus84**
### Description (*)
Partially fixes problems outlined in issue [26481](https://github.com/magento/magento2/issues/26481). Currently, there is no way to deselect an Is Default selection when editing swatch and dropdown attributes in admin.

Screen Shot 2020-04-07 at 9 35 24 AM

This PR makes it possible to click the selected radio again to deselect it, effectively removing the default value in the eav_attribute table on save. As outlined in issue [26481](https://github.com/magento/magento2/issues/26481), there are a number of reasons that an admin user may wish to undo the default on an attribute.

Note that this PR only adds the ability to remove the default selection on the attribute itself. Existing product data for the attribute is unaffected. Other challenges mentioned in [26481](https://github.com/magento/magento2/issues/26481) (such as default values being applied to products at unintended times) are not addressed by this PR as the exact expectation for the behavior of a default value is debatable.

### Fixed Issues (if relevant)
1. Fixes #26481: Unable to remove default text swatch value and value automatically assigning

### Manual testing scenarios (*)
1. In admin, go to Stores > Attributes / Product.
2. Click Add New Attribute.
3. Set "Catalog Input Type for Store Owner" to Dropdown.
4. Under Manage Options, click Add Option to add multiple options.
5. Click the "Is Default" radio on one of the options, complete any other required fields, and click Save and Continue Edit.
6. On page reload, click the currently selected "Is Default" radio. It should become unchecked.
7. Save the attribute again. On page reload, all "Is Default" radios should still be unchecked.
8. Repeat the steps above using Visual Swatch or Text Swatch as the "Catalog Input Type for Store Owner".

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @zaximus84,
Your changes looks good. Could you review & fix failing tests and cover your test with some kind of automated test, for instance MFTF?

**Comment by engcom-Hotel** [comment]
Hi @zaximus84, will help with tests.

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
Hi @zaximus84, 
Not sure that the solution works, could you please have a look.
26481_NA2R
Thank you.

**Comment by sidolov** [comment]
@zaximus84  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
