### PR TITLE
SymLinks cross compatibility between Apache versions

### PR DESCRIPTION
**Pull request by angelo983**
This file change to solve error 500 with Apache 2.4

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23545) <br/>All committers have signed the CLA.

**Review by orlangur — CHANGES_REQUESTED** [review]
After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by angelo983** [comment]
Functional Tests build and Sample Data Tests build failed due to timeout.
I think that would be better rerun all tests.

**Comment by angelo983** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @angelo983,
1. In general your changes looks good, but it's not clear how to test it? I was using Apache 2.4 for a long time and I hadn't any 500 error. Could you add steps to reproduce?
2. Also as @orlangur  requested - could you squash your changes into single commit?
3. Issue with functional tests & sample data tests looks not related to your changes, so no need to fix anything

Thank you!

**Comment by angelo983** [comment]
Ok, I will squash the changes into single commit

**Pull request closed without merging**
