### PR TITLE
#32332 : Fixed Replace usages of ReflectionParameter deprecated methods

### PR DESCRIPTION
**Pull request by konarshankar07**
### Description (*)

Replaced isArray and isCallable deprecated method of ReflectionParameter
### Fixed Issues (if relevant)

1. Fixes magento/magento2#32332

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by konarshankar07** [comment]
@magento run all tests

**Comment by konarshankar07** [comment]
@magento run Functional Tests CE Functional Tests B2B Functional Tests EE

**Comment by konarshankar07** [comment]
@magento run Functional Tests CE

**Comment by sivaschenko** [comment]
Functional tests failure does not look to be related to the changes in the pull request

**Review by sivaschenko — APPROVED** [review]

**Comment by sivaschenko** [comment]
Thanks for the important contribution toward PHP 8 compatibility @konarshankar07 !

**Pull request merged**
