### PR TITLE
fix  Fatal Error when save configurable product in Magento 2.2.5 #18082

### PR DESCRIPTION
**Pull request by thiagolima-bm**
fix  Fatal Error when save configurable product in Magento 2.2.5 #18082

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18461) <br/>All committers have signed the CLA.

**Review by sidolov — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3135](https://jira.corp.magento.com/browse/ENGCOM-3135) has been created to process this Pull Request

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3135](https://jira.corp.magento.com/browse/ENGCOM-3135) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @thiagolima-bm. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.

**Pull request merged**
