### PR TITLE
Fixed Issue #25173:Issue with Guest Checkout when disabled guest checkout from admin

### LINKED ISSUE #25173: Issue with Guest Checkout when disabled guest checkout from admin
There is no proper check for guest checkout at the time of order placement.

### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Add product in cart from frontend as a guest.
2. Go to checkout page
3. Now login into Admin.
4. Disable Guest Checkout from admin. Navigate to **Store > Configuration** then **Sales > Checkout** now find Allow Guest Checkout in **Checkout Options** section and disable it.
5. Now go to opened guest checkout page and try to place order

### Expected result (*)

1. Order should not be placed and there should be an error like "Guest checkout is disabled."

### Actual result (*)

1. Guest is able to place the order.

### PR DESCRIPTION
**Pull request by ghost**
### Fixed Issues (if relevant)

1. fixes magento/magento2#25173:Issue with Guest Checkout when disabled guest checkout from admin

### Manual testing scenarios (*)
1. Add product in cart from frontend as a guest.
2. Go to checkout page
3. Now login into Admin.
4. Disable Guest Checkout from admin. Navigate to **Store > Configuration** then **Sales > Checkout** now find Allow Guest Checkout in **Checkout Options** section and disable it.
5. Now go to opened guest checkout page and try to place order
6. Now guest will not be able to place order if guest checkout is disabled from admin.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ghost** [comment]
@rodrigowebjump - Please review the PR. I have done the suggested changes. due to some issues i had to recreate this PR.
this PR is duplicate PR - https://github.com/magento/magento2/pull/25174
I have done all the changes mentioned in https://github.com/magento/magento2/pull/25174

**Comment by rodrigowebjump** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [new Magento instance](https://pr-25326.instances.magento-community.engineering).
Admin access: [https://pr-25326.instances.magento-community.engineering/admin](https://pr-25326.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rodrigowebjump** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [Magento instance](https://i-25326-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25326-2-3-develop.instances.magento-community.engineering/admin](https://i-25326-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@paliarush @rodrigowebjump - Any update on it. I didn't get any update over it from 17 days. Please check this PR.

**Comment by sdzhepa** [comment]
Closed after reviewing on internal Triage meeting
See more details https://github.com/magento/magento2/issues/25173#issuecomment-635560044

**Pull request closed without merging**
