### PR TITLE
Fixing #26356: Problem with Swagger UI in creating token for customers

### PR DESCRIPTION
**Pull request by marcoaacoliveira**
### Description (*)
I had to change a bit the process of retrieve a customer by email, now if websiteId is 0, it will try through all websites to find the customer.

### Fixed Issues (if relevant)
1. magento/magento2#26356: Create customer's token in swagger UI not working properly

### Manual testing scenarios (*)
1. Create a user in site by registration form; 
2. Try to login through Swagger UI with that user;

### Questions or comments
I'm not sure if in this case we gonna need new (or even if would be possible) tests. I would mostly appreciate some help from reviewer in that.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by marcoaacoliveira** [comment]
@pmclain thanks a lot for reviewing it. There are some tests skipped, I've never seen it before... Do you have any idea what the problem is?

**Review by pmclain — CHANGES_REQUESTED** [review]
@marcoaacoliveira Could you think about exploring how the swagger experience could be modified? Is it possible to add a store code input? This would allow the requests to succeed, since the request is failing because the store code in the request is incorrect.

`https://{{domain}}/rest/{{store_code}}/V1/integration/customer/token` would be needed.

**Comment by pmclain** [comment]
@marcoaacoliveira What I mention above is currently supported. Add the desired store code as a query parameter.

`https://{domain}/swagger?store={store_code}`

**Comment by pmclain** [comment]
Closing the PR as the request works when the store code is passed to swagger, no application changes are required. https://devdocs.magento.com/guides/v2.3/rest/generate-local.html#generate-a-full-rest-reference-locally

**Comment by marcoaacoliveira** [comment]
> @marcoaacoliveira What I mention above is currently supported. Add the desired store code as a query parameter.
> 
> `https://{domain}/swagger?store={store_code}`

Indeed, I was wrong, I didn't know we could do something like that. It isn't a bug at all, is it?

**Pull request closed without merging**
