### PR TITLE
Fixed Sales order Address Information edit form layout design improvement

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

Fixed Sales order Address Information edit form layout design
### Fixed Issues (if relevant)

1. magento/magento2#19805:Sales order Address Information edit form layout design improvement

### Manual testing scenarios (*)

1. N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](https://i-22058-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22058-2-3-develop.instances.magento-community.engineering/admin](https://i-22058-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-22058.instances.magento-community.engineering).
Admin access: [https://pr-22058.instances.magento-community.engineering/admin](https://pr-22058.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rogyar** [comment]
Hi @ravi-chandra3197. Thank you for your collaboration. Could you doublecheck your solution, please? The form looks not quite right after the fix.

image

Please, take a look at the "Expected Result" section in the original issue and compare with the current result. Thank you

**Comment by sidolov** [comment]
@ravi-chandra3197 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
