### PR TITLE
Move JS module initialization to separate tasks

### PR DESCRIPTION
**Pull request by krzksz**
### Description (*)
I'm currently during a process of profilling and trying to improve Magento frontend performance as much as possible. This is one of the improvements that I found.

#### The Issue
As you can see on the below screenshot `First CPU idle` and `Max Potential First Input Delay` times are not great and it would be nice to improve them.
mage-lighthouse
And so I run a quick performance profile, with 4x CPU slowdown for easier spotting and here's what I found:
mage-timeline
Those two big long-running tasks are coming from Magento initializing all `data-mage-init` modules. The first one is responsible for collecting all the data needed for initialization which happens in the same task as initializing custom Knockout bindings, hence change in `lib/web/mage/bootstrap.js`. The second one is initialization of each of the modules themselves which can also be done in separate tasks like you see in changed `lib/web/mage/apply/main.js`.
#### The Fix
Here's the result after applying both changes:
main improved lighthouse
main improved timeline
As you can see both metrics improved dramatically. Next step would be to reduce this huge `TTI` but until it happens it would be great to make sure we are not blocking the main thread for too long preventing it from handling user interactions. 

### Manual testing scenarios (*)
This is not a functional change, everything should we working as before.

### Questions or comments
Since this is not a functional change, as long as all tests are still passing I would consider this change covered with tests.
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by krzksz** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @krzksz. Thank you for your request. I'm working on Magento instance for you

**Comment by ihor-sviziev** [comment]
@krzksz good catch!
Let's wait for test results

**Review by lbajsarowicz — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7146](https://jira.corp.magento.com/browse/ENGCOM-7146) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by ptylek — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-7146](https://jira.corp.magento.com/browse/ENGCOM-7146) has been created to process this Pull Request
:eight_spoked_asterisk: @ptylek, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @krzksz ,
Amazing improvement!
Could you fix failing static tests?

**Comment by ihor-sviziev** [comment]
@krzksz do you think it’s possible to cover your changes with some tests?

**Comment by ihor-sviziev** [comment]
Just reviewed test failures - looks like they’re not related to changes from this PR, some failures on MSI. To make sure I just restarted this functional test

**Comment by krzksz** [comment]
@ihor-sviziev I think I fixed failing static test (there was line break missing) but I don't think this change should be covered by any additional tests.

My point is that as long as existing functional tests are passing, it means that all frontend modules are still initialized properly. Otherwise I would have to add tests that are heavily coupled to the implementation which would do more harm then good.

**Comment by krzksz** [comment]
Test failing with `copyPaste` error which is a false-positive.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7146](https://jira.corp.magento.com/browse/ENGCOM-7146) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@krzksz approved!
I also think that it’s impossible to cover this change with meaningful tests, so let’s not cover it.
Thank you so much for such improvement!

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Comment by ilnytskyi** [comment]
@krzksz 
Would the same changes be applicable for backend js?

file:
lib/web/mage/backend/bootstrap.js

this file is seem to be used by backend 
lib/web/mage/apply/main.js

**Comment by krzksz** [comment]
In theory yes, it's that storefront was my priority because it affects much more people, their experience and actual buying process.

**Pull request merged**
