### PR TITLE
Fixed required class is missing in load template

### PR DESCRIPTION
**Pull request by gaurav-473**
### Description (*)
Required class is missing in load template

### Manual testing scenarios (*)

1. Marketing -> Email Template -> Load Template 
2. Template is required field but required class is missing.

Screenshot_2019-10-11_15-20-31

### CODE REVIEW

**Comment by gaurav-473** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @gauravagarwal1001. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @gauravagarwal1001, here is your [new Magento instance](https://pr-24981.instances.magento-community.engineering).
Admin access: [https://pr-24981.instances.magento-community.engineering/admin](https://pr-24981.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by gaurav-473** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @gauravagarwal1001. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @gauravagarwal1001, here is your [Magento instance](https://i-24981-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24981-2-3-develop.instances.magento-community.engineering/admin](https://i-24981-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dmytro-ch** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-24981.instances.magento-community.engineering).
Admin access: [https://pr-24981.instances.magento-community.engineering/admin](https://pr-24981.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6068](https://jira.corp.magento.com/browse/ENGCOM-6068) has been created to process this Pull Request

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6103](https://jira.corp.magento.com/browse/ENGCOM-6103) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:**
before

**After:**
after

**Comment by engcom-Foxtrot** [comment]
Covering

**Pull request merged**
