### PR TITLE
[Backport] Sample Link Issue in Downloadable product in magento-2.2.6  #19344

### PR DESCRIPTION
**Pull request by ansari-ziyaurrahman**
Sample Link Issue in Downloadable product. #19344

### Description (*)
Fixed issue of Sample Link Issue in Downloadable product.

### Fixed Issues (if relevant)
1. magento/magento2#19344: Sample Link Issue in Downloadable product

### Manual testing scenarios (*)

1. Create New product with sample Links.
2. Add and edit links eith multiple products.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19431) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
Fix for 2.3 https://github.com/magento/magento2/commit/440e9eb40884e12236f820f9ba1e52cb704e702f

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3584](https://jira.corp.magento.com/browse/ENGCOM-3584) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@ansari-krish thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by orlangur — CHANGES_REQUESTED** [review]
@ansari-krish please cherry-pick https://github.com/magento/magento2/commit/440e9eb40884e12236f820f9ba1e52cb704e702f properly so that original commit author is preserved.

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.

**Comment by orlangur** [comment]
@sidolov @sivaschenko any idea why this improper PR was merged?

**Comment by sivaschenko** [comment]
@orlangur why do you consider this PR improper?

**Comment by orlangur** [comment]
@sivaschenko because it didn't pass code review, here is a request change: https://github.com/magento/magento2/pull/19431#pullrequestreview-179422685

**Comment by sivaschenko** [comment]
@orlangur as I can see, the requested commit was added to the pull request after the code review, so the code review was considered outdated.

**Comment by orlangur** [comment]
@sivaschenko nope, it obviously wasn't: https://github.com/magento/magento2/pull/19431/commits/3b6307bb8b162455e5150189234ca57ac21734a6

I'll share a suggestion regarding automated safeguard in Slack.

**Pull request merged**
