### PR TITLE
WIP[issue 31935] Remove related url_key attribute from parent product

### LINKED ISSUE #31935: [Atwix] Products query filtering with url-key has issues with Grouped Product
Issue with the `products` query when filtering strictly on `url*key`. The query below returns not only the SimpleProduct with the specified `url_key` but also the GroupedProduct (with different `url*key`) containing it.
{
  products(filter:\{url_key:{eq:"augusta-earrings"}})
  \{items{*_typename,sku,url*key,name}}
}
response:
{
  "data": {
    "products": {
      "items": <
        {
          "__typename": "GroupedProduct",
          "sku": "VA23",
          "url_key": "augusta-trio",
          "name": "Augusta Trio"
        },
        {
          "__typename": "SimpleProduct",
          "sku": "VA12-SI-NA",
          "url_key": "augusta-earrings",
          "name": "Augusta Earrings"
        }
      >
    }
  }
}
**Expected Behavior:**

Filtering with url-key of the simple product should return just the simple product

 

**Actual Behaviour:**

Filtering with url-key of the simple product return the simple product and also the grouped product under which the simple product is linked.

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

BEFORE
Screenshot 2021-02-11 at 18 55 03
AFTER
<pre>
"_source": {
          "store_id": "1",
          "sku": "grouped",
          "status": 1,
          "status_value": "Enabled",
          "visibility": 4,
          "name": "grouped orange banana",
          "url_key": "grouped",
          "tax_class_id": 0,
          "tax_class_id_value": "None",
          "category_ids": [
            2,
            3,
            4
          ],
          "position_category_2": "10000",
          "name_category_2": "Default Category",
          "position_category_3": "0",
          "name_category_3": "one",
          "position_category_4": "0",
          "name_category_4": "two",
          "price_0_1": "10.000000",
          "price_1_1": "10.000000",
          "price_2_1": "10.000000",
          "price_3_1": "10.000000"
        }
</pre>
Screenshot 2021-02-11 at 19 06 23

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/31935

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by eduard13** [comment]
Putting it `on hold` for now, for additional clarification.

**Comment by eduard13** [comment]
Unfortunately, looks like it was decided to leave it as currently is.
Thank you for your involvement.

**Pull request closed without merging**
