### PR TITLE
Order mail sender empty 16865

### PR DESCRIPTION
**Pull request by nadeefit6**
### Description (*)
Magento/Sales/Model/Order/Email/SenderBuilder.php
79+ $transport->setIdentityContainerStore($this->identityContainer->getStore());

### Fixed Issues (if relevant)

1. Transaction emails sender email is incorrect

### Manual testing scenarios (*)

1. Place and order and get order confirmation email
2. Check the sender email in order confirmation email

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @nadeefit6. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by dmytro-ch** [comment]
Hi @nadeefit6,
your working branch contains the commits from another branch (PR #21938).
The new branches for 2.3 release line must be based on the `2.3-develop` branch only.

I would also recommend combining all these changes in a single PR if you wish to deliver them togather.

Thank you!

**Comment by cram412** [comment]
Hi @nadeefit6 @dmytro-ch 

Sorry, but seems this fix is wrong

I've also investigated this issue, it happens because Magento introduced separate file `Magento\Framework\Mail\Template\TransportBuilderByStore` and used it to add mail sender. But in the `Magento\Framework\Mail\Template\TransportBuilder` constructor creates two instances of the Message object what is wrong

Check this screenshot https://pasteboard.co/I7GfCCu.png

Another bug is that Magento ignores sender name
Everywhere in code i found this usage 
```
$this->message->setFrom($result['email'], $result['name']);
```
Actually `Magento\Framework\Mail\MessageInterface::setFrom()` appies only one parameter.  See method declaration
```
namespace Magento\Framework\Mail;

/**
 * Mail Message interface
 *
 * @api
 */
interface MessageInterface
{

    ...

    /**
     * Set from address
     *
     * @param string|array $fromAddress
     * @return $this
     */
    public function setFrom($fromAddress);
}
```

This can be fixed with passing this params as array `->setFrom([$result['email'] => $result['name']])`

Kinda regards,
Oleg Kraminsky
Magento developer

**Comment by dmytro-ch** [comment]
@cram412, thank you for the update!
It makes sense. Please feel free to prepare a new PR with an actual fix.

@nadeefit6, I'm closing this PR for now.
Please make sure you create a working branch based on the `2.3-develop` branch only.

Thank you!

**Pull request closed without merging**
