### PR TITLE
Rename LESS var names to 'darker' vs 'darkie'

### PR DESCRIPTION
**Pull request by philwinkle**
### Description (*)

The LESS variable `color-brown-darkie` has a negative connotation in some languages. Darkie itself doesn't mean much in English. I've renamed this to `color-brown-darker` and unified other uses of "darkie" to also use the phrase "darker".

See existing usage here: https://github.com/magento/magento2/blob/2.3-develop/app/design/adminhtml/Magento/backend/web/css/source/variables/_colors.less#L11

### Manual testing scenarios (*)

1. Search the code base for "color-brown-darkie"

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @philwinkle. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21030) <br/>All committers have signed the CLA.

**Comment by sivaschenko** [comment]
Hi @philwinkle thank you for the pull request! Unfortunately, we cannot accept this contribution as changing the less variable name is a backward incompatible change.

See more information about backward compatible development here: https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/#cssless

**Comment by DrewML** [comment]
Speaking with other members of the arch team now, but we _need_ to land this, and quickly. There is an exception to every rule, and in this case the harm from this language being present in our code significantly outweighs the impact of a style-related bug.

**Comment by magento-engcom-team** [comment]
@philwinkle thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by ericerway** [comment]
Happy to weigh in from a product standpoint. @DrewML let me know how I can help.

**Comment by DrewML** [comment]
Following up on this with engcom in the morning. For now, backports have been done internally to address this in 2.2.x and 2.1.x

**Review by DrewML — APPROVED** [review]

**Comment by DrewML** [comment]
Forgot to hit "Approve". Let's get this merged up. We'll be addressing the small back-compat issue in the release notes when these changes go out.

**Comment by ericerway** [comment]
Nice work everyone! Looks like we're merged across the board. 🎉

**Comment by ilnytskyi** [comment]
We used 3rd-party paid extension which used this variable, after upgrade to newer version of M2, all admin css files were not compiled because of the old name (@color-brown-darkie) in the module :D
lol

**Pull request merged**
