### PR TITLE
Fixed Issue: Special price of 0.0000 is not shown on frontend, but is calculated in cart

### PR DESCRIPTION
**Pull request by mahesh-rajawat**
Fixed issue of product with a special price of 0.00, this is not shown on the frontend. Not in the product listings and also not on the product detail page.

### Description (*)
Product Special Price is set to 0 then its not visible on product listing and Product View page, but when
we add product in cart, its price added to 0 in cart. In this pull request i have fixed this issue, now
Special price is displaying 0 as well. 

### Fixed Issues (if relevant)

1. magento/magento2#18268: Special price of 0.0000 is not shown on frontend, but is calculated in car

### Manual testing scenarios (*)

1. Created new product and set the special price 0 and saved it.
2. Open product in category page special price is displaying 0 as normal.
3. Open product in product view page special price is displaying 0.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18604) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rodrigowebjump** [comment]
Hi @maheshWebkul721 

We are trying to have everything merged on 2.3 before merging it to 2.2 and others.
Thus, I would kindly ask you to change the branch to 2.3.
It's up to you to decide whether to create a new PR or edit this one.

I already reviewed your code and it is ok.

Also, do not forget to check the license/CLA.

**Comment by mahesh-rajawat** [comment]
Ok @rodrigowebjump , I am going to create new pull request for 2.3-develop

**Comment by testmagento2** [comment]
Hi
I found a temporary solution by create catalog price rule and it changed the price to 0

**Review by rodrigowebjump — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-3195](https://jira.corp.magento.com/browse/ENGCOM-3195) has been created to process this Pull Request

**Comment by mahesh-rajawat** [comment]
#SQUASHTOBERFEST

**Comment by sidolov** [comment]
Hi @maheshWebkul721 , looks like commits in current PR were made with the different email than in your GitHub profile, please, add email from commits to your profile and sign the CLA.
Thank you!

**Comment by mahesh-rajawat** [comment]
@sidolov , email added and signed CLA

**Comment by sidolov** [comment]
Hi @maheshWebkul721 , few commits with different email still present in the PR, please, take a look
Thank you!

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
