### PR TITLE
[Improvement] Implement customer group grid on ui component

### PR DESCRIPTION
**Pull request by simpleadm**
### Description
Several versions ago backend grid widgets (`\Magento\Backend\Block\Widget\Grid`) were marked as 
deprecated in favour of UI component implementation. This PR refactors customer group grid to use UI components. 
At least it will save time of third party developers who needs to extend customer groups grid :)

### Manual testing scenarios
Before changes:
image

After changes:
image
Filers:
image

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=13501) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=13501) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: simpleadm<br/>:x: VladimirZaets

**Comment by VladimirZaets** [comment]
Hi @simpleadm , please fix failed Travis tests. 
Also, please try to run next functional tests, because they fail with your changes:
`Magento\Customer\Test\TestCase\DeleteSystemCustomerGroupTest.test with data set "DeleteSystemCustomerGroup1_0"`
`Magento\Customer\Test\TestCase\DeleteSystemCustomerGroupTest.test with data set "DeleteSystemCustomerGroup2_0"`
`Magento\Customer\Test\TestCase\LoginOnFrontendFailTest.test with data set "LoginOnFrontendFailTestVariation1_0"`
`Magento\Customer\Test\TestCase\MassAssignCustomerGroupTest.test with data set "MassAssignCustomerGroupTestVariation1_0"`
`Magento\Customer\Test\TestCase\VerifyDisabledCustomerGroupFieldTest.test with data set "VerifyDisabledCustomerGroupField1_0"`

If you need some help or guide how to running functional tests locally, please let us know.

**Comment by VladimirZaets** [comment]
Hi @simpleadm. Can you please resolve conflicts with 2.3-develop branch. Thanks

**Comment by simpleadm** [comment]
Hi @VladimirZaets ,
Conflicts were resolved and functional tests passed.

**Comment by magento-engcom-team** [comment]
Hi @simpleadm. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Pull request merged**
