### PR TITLE
Fixed issue Billing & Shipping address the same checkbox is empty

### LINKED ISSUE #33725: 'Billing & Shipping address the same' checkbox is empty
### Preconditions (*)

1. Clean installation of "magento/product-community-edition": "2.4.2"

### Steps to reproduce (*)

1. Add some product to cart
2. Go to checkout
3. Fill shipping address by Chrome autocomplete
4. Click 'Next' to go to next step **BEFORE** shipping methods block is reloaded (recalculated)

See reproducing here https://youtu.be/-lW947TCD7k

### Expected result (*)

1. 'My billing and shipping address are the same' checkbox is checked by default

### Actual result (*)

1. 'My billing and shipping address are the same' checkbox is not checked by default

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rostilos**
### Related Pull Requests
https://github.com/magento/inventory/pull/3383

### Fixed Issues (if relevant)

1. Fixes #33725

### Manual testing scenarios (*)
1. Add some product to cart
2. Go to checkout
3. Fill shipping address by Chrome autocomplete
4. Click 'Next' to go to next step BEFORE shipping methods block is reloaded (recalculated)
5. 'My billing and shipping address are the same' checkbox is checked by default

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rostilos** [comment]
@magento run all tests

**Comment by rostilos** [comment]
@magento run Static Tests

**Comment by rostilos** [comment]
https://github.com/magento run all tests

**Comment by rostilos** [comment]
@magento run all tests

**Comment by rostilos** [comment]
@magento run all tests

**Comment by rostilos** [comment]
@magento run Functional Tests CE

**Comment by rostilos** [comment]
https://github.com/magento run Functional Tests CE

**Comment by rostilos** [comment]
@magento run Functional Tests CE

**Comment by rostilos** [comment]
@magento run all tests

**Comment by rostilos** [comment]
@magento run Functional Tests B2B Integration Tests

**Comment by rostilos** [comment]
@magento run Functional Tests B2B

**Comment by rostilos** [comment]
@magento run Integration Tests

**Comment by rostilos** [comment]
@magento run Integration Tests

**Comment by rostilos** [comment]
@magento run all tests

**Comment by rostilos** [comment]
@magento run Functional Tests CE

**Comment by rostilos** [comment]
@magento run Functional Tests CE

**Comment by rostilos** [comment]
@magento run all tests

**Comment by rostilos** [comment]
@magento run all tests

**Comment by rostilos** [comment]
@magento run Functional Tests EE

**Comment by rostilos** [comment]
@magento run all tests

**Comment by rostilos** [comment]
@magento run Integration Tests

**Comment by rostilos** [comment]
https://github.com/magento run all tests

**Comment by rostilos** [comment]
@magento run all tests

**Comment by rostilos** [comment]
@magento run Functional Tests EE

**Comment by rostilos** [comment]
@magento run Functional Tests EE

**Comment by rostilos** [comment]
@magento run Functional Tests CE

**Comment by rostilos** [comment]
@magento run Functional Tests CE

**Comment by rostilos** [comment]
@magento run Functional Tests CE

**Comment by rostilos** [comment]
@magento run Functional Tests CE

**Comment by rostilos** [comment]
@magento run Functional Tests CE

**Comment by rostilos** [comment]
@magento run Functional Tests B2B

**Comment by rostilos** [comment]
@magento run Functional Tests CE

**Comment by rostilos** [comment]
https://github.com/magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by rostilos** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
@magento give me test instance

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Changes look good to me but can we add some automated tests to verify this?

**Comment by rostilos** [comment]
Sure, I'll make tests for that

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by rostilos** [comment]
One of the tests crashes with an error. 

Most likely it's because now after filling the address, there will be a loader on the component with shippings methods until they are updated (after changing address details).

**Comment by engcom-Charlie** [comment]
Hi @rostilos,

Thank you for your contribution!

@engcom-Hotel I have added the automation test coverage for this PR.

@rostilos, in order to move this PR further, the build should be green. Currently are you looking into the failed tests. 

Thank you!

**Comment by rostilos** [comment]
I would like to clarify if I edit this test (mentioned above), because otherwise the functional tests will always crash with an error?
Is it correct ?

**Comment by engcom-Echo** [comment]
> I would like to clarify if I need to edit this test (mentioned above), because otherwise the functional tests will always crash with an error? Is this correct? 

Yes you need to modify the test mentioned in [comment](https://github.com/magento/magento2/pull/36463#issuecomment-1521419695)

**Comment by rostilos** [comment]
@magento run Functional Tests EE

**Comment by rostilos** [comment]
@magento run all tests

**Comment by rostilos** [comment]
I'm not sure if the tests that went wrong at the moment refer to edits from the PR. But I could be wrong.

**Comment by engcom-Charlie** [comment]
> I'm not sure if the tests that went wrong at the moment refer to edits from the PR. But I could be wrong. 

Okay, let we have a look on this failed test.

Meanwhile, can you please also look into the other 9 broken tests listing [here](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36463/8d2522a39ae84bf7b5dc1865edcebd3b/Functional/allure-report-ce/index.html#categories/99f6d466ee04e9f5f8ae548d04ff0523/987a3c2f9a2c87ac/) confirming whether those are related to PR changes.

image


Thank you!

**Comment by rostilos** [comment]
Yes, I apologize. Some of the tests below also need to be refined to wait for the end of the loader before performing some actions

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by rostilos** [comment]
@magento run Functional Tests CE

**Comment by rostilos** [comment]
@magento run all tests

**Comment by rostilos** [comment]
@magento run Unit Tests

**Comment by rostilos** [comment]
@magento run Functional Tests EE

**Comment by rostilos** [comment]
The bug itself made me think that at this point, the user has the ability to move to the next checkout step before the available shipping methods are updated after the address change.
The idea of "fixing" this bug is to prevent the user from moving to the next checkout step before the section with the shipping methods is updated after changing the shipping address (by setting a loader).
Some mftf tests have been rewritten in relation to this change and some conditions have been added to make it possible to wait for finished loading of shiping methods. There is some problem with some of the tests as I don't have an understanding of how to extend their functionality at the moment. I'm referring to this test from the screenshot ( https://app.hiptest.com/projects/69435/test-plan/folders/457014/scenarios/1840408 ) as it is not in the files defined in this repository. I would like to ask you to help me with this

**Comment by rostilos** [comment]
https://github.com/magento/inventory/pull/3383
Here is the PR to the magento/inventory repository with edits to some mftf tests

**Comment by rostilos** [comment]
@magento run Unit Tests

**Comment by engcom-Echo** [comment]
> [magento/inventory#3383](https://github.com/magento/inventory/pull/3383) Here is the PR to the magento/inventory repository with edits to some mftf tests related to this PR

Can you please update description of https://github.com/magento/inventory/pull/3383 mentioning this [PR](https://github.com/magento/magento2/pull/36463) in `### Related Pull Requests` section similar to what we have updated in the description [here](https://github.com/magento/magento2/pull/36463#issue-1445527762)

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by rostilos** [comment]
@magento run Functional Tests CE

**Comment by rostilos** [comment]
@magento run Functional Tests EE

**Comment by engcom-Echo** [comment]
@rostilos Functional Tests EE does not seems related to your PR changes.
But Unit Test failure is their can you please confirm if that is related to your changes?
image

**Comment by rostilos** [comment]
@magento run all tests

**Comment by rostilos** [comment]
It seems to me that the failed tests are not related to edits from the PR, please check this

**Comment by engcom-Echo** [comment]
> It seems to me that the failed tests are not related to edits from the PR, please check this

@rostilos Thanks for your contribution. Build failures are not related to PR so we can move this PR ahead.

**Review by engcom-Hotel — APPROVED** [review]
Build failures seems falky to me. Hence approving the PR.

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

- Add some product to cart
- Go to checkout (Guest)
- Fill shipping address by Chrome autocomplete
- Click 'Next' to go to next step BEFORE shipping methods block is reloaded (recalculated)
- 'My billing and shipping address are the same' checkbox is checked by default

**Before:** :heavy_multiplication_x: Checkbox was not checked
Screenshot 2023-05-08 at 12 45 16 PM


**After:** :heavy_check_mark:  Now working fine
Screenshot 2023-05-08 at 3 53 01 PM

Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, WebAPI Tests

**Comment by engcom-Charlie** [comment]
As all the test have passed, moving this PR to Merge in Progress.

Thank you!

**Comment by engcom-Echo** [comment]
@magneto run all tests

**Comment by rostilos** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
The Functional B2B and EE test is failing because of this PR hence moving back to Changes Requested.

image

Thank you!

**Comment by engcom-Charlie** [comment]
Hi @rostilos,

Thank you for your contribution!

I will look into this failure.

Thank you!

**Comment by engcom-Charlie** [comment]
Removed the unwanted file change from the PR to fix the AdminCreateCustomerSegmentConditionCombinationTest .xml Functional B2B failure.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
AdminCreateCustomerSegmentConditionCombinationTest .xml failure is fix now.

Rerunning the rest of the build.

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, WebAPI Tests

**Comment by rostilos** [comment]
@engcom-Charlie It seems to me that the errors in the tests are not related to the edits in the PR, could you confirm this?

**Comment by engcom-Charlie** [comment]
> @engcom-Charlie It seems to me that the errors in the tests are not related to the edits in the PR ( Almost all errors are related to the functionality in the admin panel or related to the problem that some products in the build out of the stock, and are not related to edits from the PR, as the edits implied only visual storefront functionality on checkout/cart pages). Could you confirm this?

Hi @rostilos,

In AdminCreateCustomerSegmentConditionCombinationTest.xml test, when control goes to checkout/cart page, because of below changes, made in f182aa15a4d81416d1befe72445330761173ee66 commit the test is failing as Unable to locate element: {"method":"css selector","selector":"#checkout-shipping-method-load}

app/code/Magento/Checkout/Test/Mftf/ActionGroup/CheckoutSelectFlatRateShippingMethodActionGroup.xml
<waitForElementClickable selector="{{CheckoutShippingMethodsSection.shippingMethodFlatRate}}" stepKey="waitForFlatRateShippingMethod"/>

image


Thank you!

**Review by Den4ik — APPROVED** [review]
I can confirm that failed tests looks not related to the changes

**Comment by Den4ik** [comment]
> AdminCreateCustomerSegmentConditionCombinationTest
@engcom-Charlie Where do you see failed AdminCreateCustomerSegmentConditionCombinationTest?
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36463/4cd43f05ba355cac001dc35f6eed4dc9/Functional/allure-report-ce/index.html#suites
I don't see this test fail there

**Comment by engcom-Charlie** [comment]
> > AdminCreateCustomerSegmentConditionCombinationTest
> > @engcom-Charlie Where do you see failed AdminCreateCustomerSegmentConditionCombinationTest?
> > https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36463/4cd43f05ba355cac001dc35f6eed4dc9/Functional/allure-report-ce/index.html#suites
> > I don't see this test fail there

I was explaining is about [this](https://github.com/magento/magento2/pull/36463#issuecomment-1637524268) comment for 30707766350246b2d039050c39f2bd557a42d39c commit @Den4ik. 

Remaining failures of Functional CE, B2B and EE are not part of this PR and not failing because of this PR changes. In recent 2 builds the failures are different.

Hence moving it to Merge in Progress now.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B,Functional Tests CE, Functional Tests EE

**Comment by rostilos** [comment]
It seems to me that the failed B2B tests are not related to PR, can any of the reviewers confirm this?

**Comment by rostilos** [comment]
@magento run Functional Tests B2B

**Pull request merged**
