### PR TITLE
[RSS] Covering the RSS module by integration tests

### PR DESCRIPTION
**Pull request by eduard13**
### Description (*)
This PR covers the RSS module by integration tests. The following use cases are covered:
- The RSS is disabled: the RSS page link isn't present in footer links and the page isn't accessible
- The RSS is enabled: the RSS page is available and the link is added in footer links 
- The RSS is enabled: the Catalog New Products RSS link is present
- The RSS is enabled: the Categories RSS link is present

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
@eduard13 what's the purpose of such test? Was this functionality ever broken?

We do not write tests to ensure configuration is working, we may just assume it works when configuration mechanisms have been tested by themselves separately.

**Comment by rogyar** [comment]
I believe it was done for improving integration tests coverage. I find it very useful for regression testing.  So, once there's a change somewhere in the system - better tests coverage increases chances to spot the existing issues significantly.

There are two downsides in better tests coverage:
- Time necessary for tests execution
- Tests need to be maintained 

But especially in case of such a big amount of contributions from the community, I believe these two downsides don't overweight an improved possibility to spot an issue on the automated testing stage.

**Comment by orlangur** [comment]
@rogyar the problem is such tests do not look any useful (was this functionality ever broken?) and quite expensive at the same time. Also, they look more like UI tests which are usually written with Selenium but very minimalistic (in Russian "функциональные тесты на минималках" :)).

We already assure this functionality is not broken with tests for templating system and for configuration. There is absolutely no need to write such tests for each controller action in each particular module and just assert that configuration is respected and template is renderer.

**Review by orlangur — CHANGES_REQUESTED** [review]
@eduard13 please leave integration tests only covering some useful scenarios (none of these 4 satisfy such condition), to enforce logic of controllers or any other you concern of feel free to write additional unit tests.

**Comment by orlangur** [comment]
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

**Pull request closed without merging**
