### PR TITLE
Fix dom observer not calling all listeners (regression)

### LINKED ISSUE #38622: Category description WYSIWYG is empty on non default storeview
### Preconditions and environment

- Magento version: 2.4.7
- Pagebuilder modules disabled

### Steps to reproduce

1. Edit category in the backend on storeview level
2. Untick the box 'Use default value' next to the category description field WYSWYG editor
3. Enter a description in the WYSIWYG editor
4. Save

### Expected result

Description is saved and shown in the edit form

### Actual result

WYSIWYG editor is empty after load

### Additional information

This is due to a change in `dom-observer.js` in https://github.com/magento/magento2/commit/5b931fec7dedb343a303bef40ec47c4b5f58859f 

The `return` here now exits the loop early, which wasn't the case before, since it was inside a `_` function before: https://github.com/magento/magento2/commit/5b931fec7dedb343a303bef40ec47c4b5f58859f#diff-844cfb7b272693bacaa64be3a0fd96a543cc145b478330777c39682cc15b5961R152

Patch that fixes the issue:

```
Index: src/vendor/magento/module-ui/view/base/web/js/lib/view/utils/dom-observer.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/view/base/web/js/lib/view/utils/dom-observer.js b/view/base/web/js/lib/view/utils/dom-observer.js
--- a/view/base/web/js/lib/view/utils/dom-observer.js	
+++ b/view/base/web/js/lib/view/utils/dom-observer.js	(date 1713248057631)
@@ -149,7 +149,7 @@
         _.each(watchers.selectors, function (listeners, selector) {
             for (let data of listeners) {
                 if (!data.ctx.contains(node) || !$(node, data.ctx).is(selector)) {
-                    break;
+                    continue;
                 }
 
                 if (data.type === 'add') {

```

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by thlassche**
### Description (*)
A change in `dom-observer.js` in https://github.com/magento/magento2/commit/5b931fec7dedb343a303bef40ec47c4b5f58859f changed the logic, making it only call the first listener instead of all listeners. This leads to unexpected behaviour

The `return` here now exits the loop early, which wasn't the case before, since it was inside a `_` function before: https://github.com/magento/magento2/commit/5b931fec7dedb343a303bef40ec47c4b5f58859f#diff-844cfb7b272693bacaa64be3a0fd96a543cc145b478330777c39682cc15b5961R152

### Fixed Issues (if relevant)
1. Fixes magento/magento2#38622

### Related Pull Requests
https://github.com/magento-gl/magento2-page-builder/pull/77

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@thlassche wasn't it fixed in https://github.com/magento/magento2/pull/38276 ?

**Comment by ihor-sviziev** [comment]
@magenro run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
@magento give me test instance

**Comment by engcom-Bravo** [comment]
Hi @thlassche,

Thanks for the collaboration & contribution!

:heavy_check_mark: QA Passed

**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Edit category in the backend on storeview level
- Untick the box 'Use default value' next to the category description field WYSWYG editor
- Enter a description in the WYSIWYG editor
- Save


**Before:** :heavy_multiplication_x: 

Screenshot 2024-04-17 at 09 56 03


**After:** :heavy_check_mark:  


Screenshot 2024-04-17 at 11 53 42


Screenshot 2024-04-17 at 11 54 20




Builds are failed. Hence, moving this PR to **Extended Testing.**


Thanks.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B,WebAPI Tests,Integration Tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B,Integration Tests,WebAPI Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Functional Test B2B, Functional Test CE, Functional Test EE contain  known failures.
Below is the list of known failure along with the Internal JIRA.
[ACQE-6487](https://jira.corp.adobe.com/browse/ACQE-6487) - StorefrontSelectedByQueryParamsConfigurableOptionsThumbImagesTest
[ACQE-6590](https://jira.corp.adobe.com/browse/ACQE-6590) - AdminCheckConfigurationForPayPalExpressCheckoutInUnitesStatesTest
[ACQE-6523](https://jira.corp.adobe.com/browse/ACQE-6523) - AdminReorderWithCatalogPriceRuleDiscountTest
[ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331) - StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest
[ACQE-6423](https://jira.corp.adobe.com/browse/ACQE-6423) - ApplyTaxesAndFptForSimpleProductWithCanadianPstOriginTest
[ACQE-5677](https://jira.corp.adobe.com/browse/ACQE-5677) - StorefrontQuoteCanBeRenamedUntilLockedTest

Hence Moving it to merge in Progress

**Comment by maluda259** [comment]
This critical bug is still present in Magento 2.4.7-p4
It's been almost a year and this serious issue has not been merged to latest version yet.

**Comment by ihor-sviziev** [comment]
@maluda259, it was added to 2.4.8-beta1 and 2.4.8-beta2.
I'm not sure if it will be ported to 2.4.7 since it should receive the only security updates

**Comment by DomPixie** [comment]
No one has appeared to mention, Fixed via QPT

ACSD-64467

https://github.com/magento/quality-patches/blob/master/patches/os/ACSD-64467_2.4.7-p3.patch

**Pull request merged**
