### PR TITLE
Refactor datetime class

### PR DESCRIPTION
**Pull request by Tjitse-E**
### Description (*)
When creating a console command that uses `\Magento\Framework\Stdlib\DateTime\DateTime`, the integration test suite will fail. This is because the constructor of this class does a call to the DB via the `getConfigTimezone()` method:
```
   public function __construct(TimezoneInterface $localeDate)
    {
        $this->_localeDate = $localeDate;
        $this->_offset = $this->calculateOffset($this->_localeDate->getConfigTimezone());
    }

```
 I propose that we refactor this class, so this call is done in the `getGmtOffset()` method. I don't see any downsides to this, but let me know if I've missed any.

### Fixed Issues (if relevant)
Related issue: https://github.com/baldwin-agency/magento2-module-url-data-integrity-checker/issues/2

### Manual testing scenarios (*)
1. Create a new module with a console command.
2. Inject an instance of `\Magento\Framework\Stdlib\DateTime\DateTime` in the console command class via DI.
3. Run the integration testing suite. Normally this will fail. If you apply the commits from this PR it will pass.

### Questions or comments
I thought about leaving ` private $_offset` intact. But it isn't used anywhere else than in `getGmtOffset()`, so i've removed this.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Tjitse-E** [comment]
@joni-jones the code styling issues are resolved.

**Review by aleron75 — APPROVED** [review]
> the constructor of this class does a call to the DB via the getConfigTimezone() method

doing this calculation in constructor also violates the best practice of using constructors only for assignments so for me, this contribution is very appreciated

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-7155](https://jira.corp.magento.com/browse/ENGCOM-7155) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
