### PR TITLE
Fixed: Wrong price calculation for bundle products

### LINKED ISSUE #35665: Wrong price calculation for bundle products
### Preconditions and environment

- 2.4.1

### Steps to reproduce

Create a simple product with price 6.75

Create a bundle product which is consisted of 18 pieces of the simple product and add a price of 95% to the bundle product. 

The final price that magento calculates is 115.38 which is wrong

### Expected result

The price rounded is 115.43 (115.425)

### Actual result

The price is 115.38

### Additional information

The bug is coming due to order of calculation. 

Magento is doing it like this 

`round((price * bundle price %)) * pieces `

The correct calculation would be 

`round(price* pieces * bundle price %)`

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by aasim110**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#35665

### Manual testing scenarios (*)

1. Create a simple product with a price 6.75
2. Create a bundle product which is consisted of 18 pieces of the simple product and adds a price of 95% to the bundle product.
3. The final price that Magento calculates is 115.38 which is wrong

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by aasim110** [comment]
@magento run all tests

**Comment by aasim110** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @aasim110,

It seems the build failures are due to code changes, request you to please fix those.

Thanks

**Comment by aasim110** [comment]
@magento run all tests

**Comment by aasim110** [comment]
@magento run all test

**Comment by aasim110** [comment]
@magento run all commands

**Comment by aasim110** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by aasim110** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
The Web API tests has been fixed. Working on the static test failures now.

**Comment by aasim110** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @aasim110,

There were no unit test failures present here prior to your commit a69b9a4b5e41390f8c98328b32ec6cef394cc057 

Now as you can see there are multiple unit test failures are occurring.

Can you please have a look at them as the rest of failures already been taken care from my side.

Thank you!

**Comment by aasim110** [comment]
@magento run Unit Tests

**Comment by aasim110** [comment]
@engcom-Charlie The Unit test is fine now

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
Implemented fixes for all the test failures. Requesting for review.

**Review by engcom-Hotel — APPROVED** [review]
:white_check_mark: Approving this PR for further processing

**Comment by engcom-Delta** [comment]
Hi @aasim110 ,

Thank you for your contribution. We have tested this after taking PR changes , some scenarios are working fine but some are not.

1. Created a bundle product with 19 pieces of the simple product and added a price of 94% to the bundle product - 120.555 and final price that magento calculates is 120.56 which is correct

Screenshot 2023-11-04 at 1 54 48 AM


2. Created a bundle product with 22 pieces of the simple product and added a price of 95% to the bundle product - 141.075 and final price that magento calculates is 141.08 which is correct

Screenshot 2023-11-04 at 1 55 02 AM


3. Created a bundle product with 18 pieces of the simple product and added a price of 95% to the bundle product - 115.425 and final price that magento calculates is **115.42 which is incorrect**

Screenshot 2023-11-04 at 1 54 31 AM


We have verified this various combinations but for this particular scenario the price is not rounding up.

Let us know if we are missing something here.

Thanks,

**Comment by aasim110** [comment]
Hi @engcom-Delta,

In Magento, a price difference of just 0.01 may often be considered negligible due to rounding. we can’t do anything on this

**Comment by engcom-Delta** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**

- Install fresh Magento **`2.4-develop`** 

**Manual testing scenario:**

1. Create a simple product with price 6.75

2. Create a bundle product which is consisted of 18 pieces of the simple product and add a price of 95% to the bundle product.

3. Verify the final price that magento calculates.


**Before:** :heavy_multiplication_x: 

Screenshot 2023-11-03 at 12 08 32 PM


**After:** :heavy_check_mark:  

1. Created a bundle product with 19 pieces of the simple product and added a price of 94% to the bundle product - 120.555 and final price that magento calculates is 120.56 .

Screenshot 2023-11-04 at 1 54 48 AM


2. Created a bundle product with 22 pieces of the simple product and added a price of 95% to the bundle product - 141.075 and final price that magento calculates is 141.08 .

Screenshot 2023-11-04 at 1 55 02 AM


3. Created a bundle product with 18 pieces of the simple product and added a price of 95% to the bundle product - 115.425 and final price that magento calculates is **115.42 .

Screenshot 2023-11-04 at 1 54 31 AM


Builds are Passed. Hence, moving this PR to **Merge in Progress**

**Pull request merged**
