### PR TITLE
[MFTF] Repetitive elements replaced by AdminAssertCurrencyInOrderActionGroup

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR replaces repetitive elements to `AdminAssertCurrencyInOrderActionGroup`

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento give me test instance

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests EE, Functional Tests B2B, WebAPI Tests

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests EE

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests EE

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests EE

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Pull request merged**
