### PR TITLE
Adding back the functionality to use the PHP cookie for GraphQL user

### LINKED ISSUE #28040: GraphQl. Retrieve customer's shopping cart without an authorization token
### Preconditions (*)

1. Sample data
2. Login as `Veronica Costello`
3. Add any product(s) into a shopping cart

### Steps to reproduce (*)

1. Copy `PHPSESSID` value from a browser window

2. Set `PHPSESSID` in a header 

3. Run the next GraphQL query to retrieve a customer's cart
```
{
  cart(cart_id: "kSjlU0dTeaH9CUuaRGFSUTOejwTN9ZLn") {
    id
    items {
      id
      quantity
      product {
        sku
      }
    }
  }
}
```

### Expected result (*)

1. GraphQl should use an Authorization token (`Bearer`) ONLY to retrieve a customer's cart.

### Actual result (*)

1. Guest sees products which customer has been added into shopping cart.

### PR DESCRIPTION
**Pull request by jesse-deboer**
Fixes #28040

### Preconditions (*)

- Sample data
- Login as Veronica Costello
- Add any product(s) into a shopping cart

### Steps to reproduce (*)
- Copy PHPSESSID value from a browser window
- Set PHPSESSID in a header

- Run the next GraphQL query to retrieve a customer's cart
```
 {
  cart(cart_id: "kSjlU0dTeaH9CUuaRGFSUTOejwTN9ZLn") {
    id
    items {
      id
      quantity
      product {
        sku
      }
    }
  }
}
```

### Expected result (*)
GraphQl should be authorized by the cookie set in PHP

### Actual result (*)
GraphQL call needs a bearer token and won't work

### CODE REVIEW

**Comment by manavluhar** [comment]
@jesse-deboer Please Sign CLA

**Review by engcom-Charlie — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run Unit Tests

**Comment by engcom-Lima** [comment]
Hi @jesse-deboer ,

Thanks for your contribution and collaboration.
I have tried to reproduce the issue in latest `2.4-develop` but issue is not reproducible to me. I have followed below steps :

**Preconditions:**

- Sample data
- Login as Veronica Costello
- Add any product(s) into a shopping cart

**Manual testing scenario:**

1. Copy PHPSESSID value from a browser window
2. Set PHPSESSID in a header
3. Run the next GraphQL query to retrieve a customer's cart.

```
 {
  cart(cart_id: "kSjlU0dTeaH9CUuaRGFSUTOejwTN9ZLn") {
    id
    items {
      id
      quantity
      product {
        sku
      }
    }
  }
}
```
I am able to run above query successfully , I am not getting any error or need of bearer token.
Below is the screenshot for your reference:
image

Kindly provide me more information in order to reproduce the issue.Also,please try in latest `2.4-develop` if you are facing any issue let us know.

Thanks

**Comment by engcom-Lima** [comment]
Hi @jesse-deboer ,

Thanks for your contribution and collaboration.

Kindly provide more information as mentioned in the [comment](https://github.com/magento/magento2/pull/35004#issuecomment-1247910659).

Thanks

**Comment by engcom-Lima** [comment]
Hi @jesse-deboer ,

Thanks for contribution and collaboration.

Closing this PR as there is no update on this from last 14 days. Please feel to reopen it.

Thanks

**Pull request closed without merging**
