### PR TITLE
[MFTF] Create new ActionGroup for saving product 

### LINKED ISSUE #29292: [Issue] [MFTF] Create new ActionGroup for saving product
This issue is automatically created based on existing pull request: magento/magento2#29142: [MFTF] Create new ActionGroup for saving product 

---------
This PR creates new `AdminProductFormSaveActionGroup` for saving product form

### PR DESCRIPTION
**Pull request by Usik2203**
This PR creates new `AdminProductFormSaveActionGroup` for saving product form 

### Resolved issues:
1. [x] resolves magento/magento2#29292: [MFTF] Create new ActionGroup for saving product

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Review by eduard13 — DISMISSED** [review]
Thank you for your contribution 👍

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-7857](https://jira.corp.magento.com/browse/ENGCOM-7857) has been created to process this Pull Request
:eight_spoked_asterisk: @eduard13, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by eduard13** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Alfa** [comment]
@magento create issue

**Review by slavvka — CHANGES_REQUESTED** [review]
@Usik2203 @engcom-Alfa @engcom-Echo After 2.4.0 release this PR got conflicts. Please resolve them

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run Functional Tests CE ,  Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run WebAPI Tests , Static Tests , Integration Tests , Functional Tests B2B

**Comment by engcom-Echo** [comment]
Failed functional and Integration tests not related to the changes in this PR

**Review by eduard13 — APPROVED** [review]
Indeed, the failed ones aren't related with this PR

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-7857](https://jira.corp.magento.com/browse/ENGCOM-7857) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Pull request merged**
