### PR TITLE
Feature/9201 cli command info system

### PR DESCRIPTION
**Pull request by dreamworkers**
This PR introduces a basic CLI command for getting Magento installation and setup data. Currently, it displays the following:

screenshot 2017-05-29 17 07 22

### Description
- Has a command called 'info:system'.
- The command resides at Magento_Developer module.

### Fixed Issues (if relevant)
1. magento/magento2#9201: Create New CLI command: Collect Magento Information

### Manual testing scenarios
1. Switch to dreamworkers:feature/9201-cli-command-info-system 
2. php bin/magento setup:upgrade
3. php bin/magento info:system

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by okorshenko** [comment]
@dreamworkers thank you for your contribution. Unfortunately lots of the test are broken. Could you please fix broken tests so that we can proceed this acceptance of this PR.

**Comment by dreamworkers** [comment]
@okorshenko Thanks, I'll look into the remaining issues and update the PR soon.

**Comment by okorshenko** [comment]
Hi @dreamworkers could you pleas let me know what is progress on this PR. Can we close it and you will create new one once ready?

**Comment by okorshenko** [comment]
Closing this PR for now. Please, create new PR once ready or re-open this one

**Comment by dreamworkers** [comment]
@okorshenko Sure, I'll create a new PR soon, by fixing the stuffs this one had. Sorry for the delay.

**Pull request closed without merging**
