### PR TITLE
26870: Fixes For Attribute sets not preserving attribute values when …

### LINKED ISSUE #26870: Attribute sets not preserving attribute values when set is changed and attribute is placed in a diffrent group.
### Preconditions (*)
1. Magento ver. 2.3.3
2. PHP 7.1.33

### Steps to reproduce (*)
1. In the admin navigate to Stores -> Attribute Sets
2. Click on any attribute set (i'll use the default DBs "Gear" attribute set)
3.Move a attribute out of a group (ie. Search engine optimization -> url_key gets moved into Product Details -> url_key)
4. Edit a product (Catalog ->product -> Any product)
5. Take note that Search engine optimization -> url_key has a value set
6.Change the attribute set to our modified one ie. Gear
7. url_key is now blank

### Expected result (*)
1. url_key (or any shared attribute) preserves its value. (as it used to in older versions of magento 2)

### Actual result (*)
1. The attribute's input is now empty.

### PR DESCRIPTION
**Pull request by SarojRam**
…set is changed and attribute is placed in a diffrent group.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#26870

### Manual testing scenarios (*)

1. In the admin navigate to Stores -> Attribute Sets
2. Click on any attribute set (I have use the default DBs "Gear" attribute set)
3. Move a attribute out of a group (ie. Search engine optimization -> url_key gets moved into Product Details -> url_key)
4. Edit a product (Catalog ->product -> Any product)
5. Take note that Search engine optimization -> url_key has a value set
6. Change the attribute set to our modified one ie. Gear + Click on 'Save' to product.
7. url_key is with value its not empty.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by SarojRam** [comment]
@magento run all tests

**Comment by SarojRam** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @SarojRam. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @SarojRam, here is your [new Magento instance](https://pr-28711.instances.magento-community.engineering).
Admin access: [https://pr-28711.instances.magento-community.engineering/admin_e89e](https://pr-28711.instances.magento-community.engineering/admin_e89e)
Login: `8bab22ce` Password: `8619ef811bcf`
Instance will be terminated in up to 3 hours.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi, @SarojRam thanks for the pull request! Could you provide more details on the solution proposed? 

I believe the issue is related to some fields being empty after changing the attribute set, but by removing the reloadItem that will remove the event that reloads the fields after changing the attribute set, the expected result is that the fields don't get empty, but the form still gets reloaded.

**Comment by sidolov** [comment]
@SarojRam  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
