### PR TITLE
Fix issue 19328 - Success Message Icon vertically misaligned in admin panel

### PR DESCRIPTION
**Pull request by SyntaxKay**
### Description (*)

Success Message icon misaligned.
### Fixed Issues (if relevant)

1. magento/magento2#19328 : Success Message Icon vertically misaligned in admin panel

### Manual testing scenarios (*)

1.Login to admin panel > System > Import.
2.Select necessary Option > Upload CSV.
3.Click on Check Data Button > Check success Message Icon

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by SyntaxKay** [comment]
@sivaschenko i have done changes in this pull request as well from this PR https://github.com/magento/magento2/pull/19334

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-4068](https://jira.corp.magento.com/browse/ENGCOM-4068) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @speedy008 there is an issue with this PR that was introduced to 2.3 by forward-port as well. Please see the screen shot:
image

**Comment by SyntaxKay** [comment]
@sivaschenko I have updated solution regarding error icon.

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [new Magento instance](https://pr-19333.instances.magento-community.engineering).
Admin access: [https://pr-19333.instances.magento-community.engineering/admin](https://pr-19333.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by VasylShvorak** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @VasylShvorak. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @VasylShvorak, here is your [new Magento instance](https://pr-19333.instances.magento-community.engineering).
Admin access: [https://pr-19333.instances.magento-community.engineering/admin](https://pr-19333.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Pull request merged**
