### PR TITLE
Failed tests fixes on PHP 8.1 (Static Tests, Unit Tests)

### PR DESCRIPTION
**Pull request by andrewbess**
### Related Issues (*)

1. Partially fixes magento/magento2#34441
1. Partially fixes magento/magento2#34653

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by andrewbess** [comment]
@magento run Static Tests, Unit Tests

**Comment by andrewbess** [comment]
@magento run Static Tests, Unit Tests with env PHP 8.1

**Comment by andrewbess** [comment]
@magento run Static Tests, Unit Tests with env PHP 8.1

**Comment by andrewbess** [comment]
@magento run Static Tests, Unit Tests

**Comment by andrewbess** [comment]
@magento run Static Tests, Unit Tests with env PHP 8.1

**Comment by andrewbess** [comment]
@magento run Static Tests, Unit Tests

**Comment by andrewbess** [comment]
@magento run Static Tests, Unit Tests with env PHP 8.1

**Comment by andrewbess** [comment]
@magento run Static Tests, Unit Tests

**Comment by andrewbess** [comment]
@magento run Static Tests, Unit Tests with env PHP 8.1

**Comment by andrewbess** [comment]
@magento run Static Tests, Unit Tests with env PHP 8.1

**Comment by andrewbess** [comment]
@magento run Static Tests, Unit Tests with env PHP 8.1

**Comment by andrewbess** [comment]
@magento run Static Tests, Unit Tests

**Comment by andrewbess** [comment]
@magento run Static Tests, Unit Tests with env PHP 8.1

**Comment by andrewbess** [comment]
@magento run Static Tests, Unit Tests

**Comment by andrewbess** [comment]
@magento run Static Tests, Unit Tests with env PHP 8.1

**Comment by andrewbess** [comment]
@magento run Static Tests, Unit Tests

**Comment by andrewbess** [comment]
@magento run Static Tests, Unit Tests

**Comment by xmav** [comment]
@magento run Static Tests, Unit Tests

**Comment by xmav** [comment]
@magento run Unit Tests with env PHP 8.1

**Comment by xmav** [comment]
pending delivery https://github.com/magento-commerce/magento2ce/pull/7322

**Pull request merged**
