### PR TITLE
Use product type id instead of product id

### LINKED ISSUE #35458: [Issue] Use product type id instead of product id
This issue is automatically created based on existing pull request: magento/magento2#35299: Use product type id instead of product id

---------

### Description (*)
The condition supposed to match `$product->getTypeId()` against `['grouped', 'configurable', 'bundle']` - not the product id.

### Related Pull Requests
-

### Fixed Issues (if relevant)
-

### Manual testing scenarios (*)
No testing required.

### Questions or comments
-

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by tobias-forkel**
### Description (*)
The condition supposed to match `$product->getTypeId()` against `['grouped', 'configurable', 'bundle']` - not the product id.

### Related Pull Requests
-

### Fixed Issues (if relevant)
-

### Manual testing scenarios (*)
No testing required.

### Questions or comments
-

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#35458: Use product type id instead of product id

### CODE REVIEW

**Review by manavluhar — CHANGES_REQUESTED** [review]
```
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

namespace Magento\Catalog\Model\Product\Option;

use Magento\Catalog\Api\Data\ProductCustomOptionInterface;
use Magento\Catalog\Api\Data\ProductInterface;
use Magento\Catalog\Api\ProductCustomOptionRepositoryInterface as OptionRepository;
use Magento\Catalog\Model\Product\Option;
use Magento\Catalog\Model\ResourceModel\Product\Relation;
use Magento\Framework\App\ObjectManager;
use Magento\Framework\EntityManager\Operation\ExtensionInterface;
use Magento\Framework\Exception\CouldNotSaveException;

/**
 * SaveHandler for product option
 *
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 */
class SaveHandler implements ExtensionInterface
{
    /**
     * @var string[]
     */
    private array $compositeProductTypes = ['grouped', 'configurable', 'bundle'];

    /**
     * @var OptionRepository
     */
    protected OptionRepository $optionRepository;

    /**
     * @var Relation
     */
    private $relation;

    /**
     * @param OptionRepository $optionRepository
     * @param Relation|null $relation
     */
    public function __construct(
        OptionRepository $optionRepository,
        ?Relation        $relation = null
    ) {
        $this->optionRepository = $optionRepository;
        $this->relation = $relation ?: ObjectManager::getInstance()->get(Relation::class);
    }

    /**
     * Perform action on relation/extension attribute
     *
     * @param object $entity
     * @param array $arguments
     * @return ProductInterface|object
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     * @throws CouldNotSaveException
     */
    public function execute($entity, $arguments = [])
    {
        if ($entity->getOptionsSaved()) {
            return $entity;
        }

        $options = $entity->getOptions();
        $optionIds = [];

        if ($options) {
            $optionIds = array_map(function (Option $option) {
                return $option->getOptionId();
            }, $options);
        }

        /** @var ProductInterface $entity */
        foreach ($this->optionRepository->getProductOptions($entity) as $option) {
            if (!in_array($option->getOptionId(), $optionIds)) {
                $this->optionRepository->delete($option);
            }
        }
        if ($options) {
            $this->processOptionsSaving($options, (bool)$entity->dataHasChangedFor('sku'), $entity);
        }

        return $entity;
    }

    /**
     * Save custom options
     * 
     * @param array $options
     * @param bool $hasChangedSku
     * @param ProductInterface $product
     * @return void
     * @throws CouldNotSaveException
     */
    private function processOptionsSaving(array $options, bool $hasChangedSku, ProductInterface $product): void
    {
        $isProductHasRelations = $this->isProductHasRelations($product);
        /** @var ProductCustomOptionInterface $option */
        foreach ($options as $option) {
            if (!$isProductHasRelations && $option->getIsRequire()) {
                $message = 'Required custom options can not be added to a simple product'
                    . ' that is a part of a composite product.';
                throw new CouldNotSaveException(__($message));
            }

            if ($hasChangedSku && $option->hasData('product_sku')) {
                $option->setProductSku($product->getSku());
            }
            $this->optionRepository->save($option);
        }
    }

    /**
     * Check if product doesn't belong to composite product
     *
     * @param ProductInterface $product
     * @return bool
     */
    private function isProductHasRelations(ProductInterface $product): bool
    {
        $result = true;
        if (!in_array($product->getTypeId(), $this->compositeProductTypes)
            && $this->relation->getRelationsByChildren([$product->getId()])
        ) {
            $result = false;
        }
        return $result;
    }
}
```

Can you please Update your PR according to the suggested changes? @tobias-forkel

**Comment by tobias-forkel** [comment]
@manavluhar [manavluhar](https://github.com/manavluhar)

Thanks for your suggestion! I want to keep my first PR as simple as possible without adding further changes, especially wording. Create your own PR and explain why you want to change the spelling. `Cannot` and `can not` are both acceptable spellings in my opinion.

**Comment by manavluhar** [comment]
Hi @tobias-forkel , Except for this change(cannot to can not), I have suggested changes according to Coding Standards. If you review it once.

**Review by manavluhar — APPROVED** [review]

**Comment by manavluhar** [comment]
@tobias-forkel Can you please Sign the CLA so this PR can proceed further?

**Comment by sdzhepa** [comment]
@magento run all tests

**Comment by tobias-forkel** [comment]
Thanks @manavluhar 

I just signed the CLA and committed your suggestions.

**Comment by manavluhar** [comment]
@magento run all tests

**Review by Den4ik — CHANGES_REQUESTED** [review]
Hi @tobias-forkel 
Please check failed static tests

**Comment by tobias-forkel** [comment]
@magento run all tests

**Comment by tobias-forkel** [comment]
@Den4ik Done + Static Tests passed

**Comment by tobias-forkel** [comment]
@manavluhar 

Anything else needed to push this forward?

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Integration Tests

**Comment by engcom-Charlie** [comment]
Hi @tobias-forkel,

Thank you for your contribution!

Since the review changes have been taken care and the build is green now, so moving this PR in Ready for Testing.

Thank you!

**Comment by engcom-Alfa** [comment]
Hi @tobias-forkel ,
I tried to reach you thru Slack channel, but could not find you there!
You are invited to join the [Magento Community Slack Channel](https://developer.adobe.com/open/magento/slack), please feel free to join the workspace.

**Comment by hostep** [comment]
@engcom-Alfa, the mistake can be seen here, where `getTypeId` was mistakenly changed to `getId` by accident: https://github.com/magento/magento2/commit/1b7697f8304d4326182b021d724c781c41b06807#diff-161b798378bbafeaa469c15a23f666c268a5bc6eb6be4df1584beb0d25223c20R124 (which is part of https://github.com/magento/magento2/pull/31645)

What I think is the purpose of this `in_array` check, is to avoid having to call `getRelationsByChildren` and thus avoid executing unnecessary SQL queries when the product you are trying to create or update is of type `grouped` or `configurable` or `bundle`. Because those can have required custom options and can't belong to another composite product type.
In contrast, a `simple` or `virtual` product can belong to one of those 3 composite product types and if that is the case, it can't have a required custom option.
This is what the check is supposed to do I believe.

So steps to reproduce in the backoffice of Magento:
- Create a configurable product and create some children and give it a required custom option
- Create a simple product and give it a required custom option
- Change the code `Magento\Catalog\Model\ResourceModel\Product\Relation::getRelationsByChildren` and add this line:
```
\Magento\Framework\App\ObjectManager::getInstance()->get(\Psr\Log\LoggerInterface::class)->critical('getRelationsByChildren called!');
```
- Now edit the configurable product and save it, expected is that there is **no** output `getRelationsByChildren called` in the `system.log` file
- Now edit the simple product and save it, expected is that there **is** output `getRelationsByChildren called` in the `system.log` file
- Open one of the simple/virtual products that belongs to the configurable product, try to give it a required custom option and save it, expected is that there **is** output `getRelationsByChildren called` and there is an error when trying to save the product saying: `Required custom options cannot be added to a simple product that is a part of a composite product.`

@tobias-forkel: correct me if I'm wrong 🙂

**Comment by engcom-Alfa** [comment]
Hi @hostep Thank you so much for the detailed above explanation!

I have followed to identify the issue as mentioned below that just follows as you explained above

1. Created a configurable product and with the custom options as shown in the screenshot:
image

2. Created a simple product with custom options too as shown in the below screenshot:
image

3. Updated one line of code in the file & function: `Magento\Catalog\Model\ResourceModel\Product\Relation::getRelationsByChildren` ; The added line as first line of code inside the function is `\Magento\Framework\App\ObjectManager::getInstance()->get(\Psr\Log\LoggerInterface::class)->critical('getRelationsByChildren called!');`. The updated line is shown in the below screenshot.
image

4. Edited the configurable product & saved. Checked the `system.log` file latest logs, and found the log text `getRelationsByChildren called! [] []`

5. Edited the simple product also, and found the similar log updated in the file mentioned in step4.
6. Opened the configurable product's compounded simple product with the colour option to edit it, and added the new custom option to it. Saved the product.
      - Checked the `system.log` file latest logs, and found the log text `getRelationsByChildren called! [] []`
      - Also got the error `Required custom options cannot be added to a simple product that is a part of a composite product.` in the UI.
      - The same exception message was available in the system.log file also.

**Query:** **_I took the file changes into the local and repeated the above step6. Didn't notice any change in the feature after pulling PR code changes. So, can you please help me to understand in which scenario the file changes are going to be utilised and what fix does it do?_**
@tobias-forkel 

@hostep Thanks for this additional info about this PR [#31645](https://github.com/magento/magento2/pull/31645) too!

**Comment by hostep** [comment]
@engcom-Alfa, you should repeat from step 4 with the code changes from this PR, in step 4 you should no longer see `getRelationsByChildren called!` in the `system.log` file. All the rest should act the same as before.

To repeat myself, the point of this change, is that a certain SQL statement is no longer executed when saving configurable, bundled and grouped products when they have a required custom option. Which is a micro optimisation. But it's a good one because the code as it is currently makes no sense (even though it doesn't really cause issues).

**Comment by engcom-Alfa** [comment]
> @engcom-Alfa, you should repeat from step 4 with the code changes from this PR, in step 4 you should no longer see `getRelationsByChildren called!` in the `system.log` file. All the rest should act the same as before.
> 
> To repeat myself, the point of this change, is that a certain [SQL statement](https://github.com/magento/magento2/blob/2.4.4/app/code/Magento/Catalog/Model/ResourceModel/Product/Relation.php#L146-L158) is no longer executed when saving configurable, bundled and grouped products when they have a required custom option. Which is a micro optimisation. But it's a good one because the code as it is currently makes no sense (even though it doesn't really cause issues).

Thank you for the reply!
I can proceed ahead.
Thanks much :)

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by tobias-forkel** [comment]
Well explained @hostep! Thank you!

Yes, depending on how product options are setup, the backend will falsely return `Required custom options cannot be added to a simple product that is a part of a composite product.` while saving the product - because of `if (!in_array($product->getId(), $this->compositeProductTypes)`.

In this particular case I was able to fix it by manually changing the condition in `vendor/magento/module-catalog/Model/Product/Option/SaveHandler.php` and save the configurable product again. I did not investigate further - but I noticed the mistake in the condition ( `$product->getId()` instead of `$product->getTypeId()` ) and decided to open a PR.

**Pull request merged**
