### PR TITLE
magento/magento2#38540: When customer is set for quote order is still a guest order

### LINKED ISSUE #38540: When customer is set for quote order is still a guest order
https://github.com/magento/magento2/blob/a98a64a73a72b7bb7bf297d3aba5f9920c8a2b70/app/code/Magento/Quote/Model/Quote.php#L859-L861

if ($this->_customer) {
            $this->setCustomerId($this->_customer->getId());
        }

You need to change it to 

if ($this->_customer) {
            $this->setCustomerId($this->_customer->getId());
            $this->setCustomerIsGuest(0);
        }

or incapsulate this logic into setCustomerId() method 

Additional Information:
This issue is caused when checking out from a guest cart programmatically, when you assign a customer to the cart before submitting it to place the order, the quote remains as guest even though a customer has been assigned.

### PR DESCRIPTION
**Pull request by shmVan**
- fix Module Magento\Quote: added $this->setCustomerIsGuest(false) if isset customer Quote for function beforeSave().

### Description (*)

This issue is caused when checking out from a guest cart programmatically, when you assign a customer to the cart before submitting it to place the order, the quote remains as guest even though a customer has been assigned.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38540

### Manual testing scenarios (*)

1. Install custom module [I38540V](https://github.com/magento/magento2/files/14743254/I38540V.zip) 
2. Run command bin/magento order:place
3. After saving the quote, the customer_is_guest value must be false

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by shmVan** [comment]
@magento run all tests

**Comment by shmVan** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @shmVan,

Thanks for the contribution!

However, it seems the build is failing due to the code changes. We request you to fix these issues. Especially WebAPI and Integration tests.

Thanks

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Few test failures in recent 2 builds for functional B2B are not consistent and remaining are known issues. 

**Functional B2B: Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38921/fb1e4c7bc98dc909a242c3192d78b057/Functional/allure-report-b2b/index.html#categories
image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38921/6469461a75a4a2a7ecfe118efe8aebdb/Functional/allure-report-b2b/index.html#categories/4a30a3b2be47054fe298171c561ed23f/ee137de87df69628/
image

**Known issues in CE, EE, B2B:**
1. StorefrontCashOnDeliveryPaymentForSpecificCountryTest: [#ACQE-6774](https://jira.corp.adobe.com/browse/ACQE-6774)
2. StorefrontLoginFormCheckDuplicateValidateMessageTest: [#ACQE-6799](https://jira.corp.adobe.com/browse/ACQE-6799)
3. TierPricingWhenPriceScopeIsWebsiteWorkingProperlyWithMultipleCurrenciesConfiguredTest: [#ACQE-6695](https://jira.corp.adobe.com/browse/ACQE-6695)

**Comment by engcom-Charlie** [comment]
Few test failures in recent 2 builds for functional B2B, CE are not consistent and remaining are known issues.

**Functional EE: Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38921/cfe56b715d92813d1a00555c710e5815/Functional/allure-report-ee/index.html
image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38921/29c10522e518fbabcc070d94cbada4d9/Functional/allure-report-ee/index.html
image

**Known issues in EE:** 

1. StorefrontCashOnDeliveryPaymentForSpecificCountryTest: [#ACQE-6774](https://jira.corp.adobe.com/browse/ACQE-6774)
2. StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest: [#ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331)
3. TierPricingWhenPriceScopeIsWebsiteWorkingProperlyWithMultipleCurrenciesConfiguredTest: [#ACQE-6695](https://jira.corp.adobe.com/browse/ACQE-6695)
4. StorefrontAddBundleDynamicProductToShoppingCartWithDisableMiniCartSidebarTest: [#ACQE-6786](https://jira.corp.adobe.com/browse/ACQE-6786)

**Comment by engcom-Charlie** [comment]
Hi @shmVan,

Thank you for your contribution!

In order to proceed further on this PR, the build needs to be green. For functional failures we have already our analysis in above [comment1](https://github.com/magento/magento2/pull/38921#issuecomment-2255870155), [comment2](https://github.com/magento/magento2/pull/38921#issuecomment-2258606480). These are the known failures so we can exclude them.

Can you please look into [Integration](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38921/db76366d82093da8b184d7965c35ec4b/Integration/console-error-logs.html) and [Web](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38921/1548ddd4d297fc10d3bed2dd324d1dc7/WebApi/console-error-logs.html) API failures related to CE.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run WebAPI Tests, Unit Tests, Integration Tests

**Comment by engcom-Charlie** [comment]
@magento run WebAPI Tests, Unit Tests, Integration Tests

**Comment by engcom-Charlie** [comment]
Hi @shmVan,

Too many [Integration](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38921/0a4f3a13cac0bfbe73f99e74f515bc46/Integration/console-error-logs.html) and [WebAPI](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38921/90638c11af5b2ce392334965f5a46d58/WebApi/console-error-logs.html) test failures are there because of the PR changes.

As mentioned [above](https://github.com/magento/magento2/pull/38921#issuecomment-2262144072), in order to proceed further we need a green build. Kindly have a look into these failures.

**Comment by engcom-Charlie** [comment]
Hi @shmVan,

As mentioned [here](https://github.com/magento/magento2/pull/38921#issuecomment-2285990537), please have a look at failed test cases. Till then closing this PR. 

Once you are done with changes, feel free to reopen the PR after pushing the changes.

Thank you!

**Pull request closed without merging**
