### PR TITLE
Issue resolved #19607. Page Not Found when deleting Attribute Set

### LINKED ISSUE #19607: Magento 2.3. Page Not Found when deleting Attribute Set
### Preconditions (*)

1. Magento 2.3
2.

### Steps to reproduce (*)

1. Create New Attribute Set then try to delete it
2.

### Expected result (*)

1. I expect it to delete the attribute but it results in a page not found
2.

### Actual result (*)

1. Page not found
screen shot 2018-12-06 at 4 18 42 pm

2.

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)

Page Not Found when deleting Attribute Set

### Fixed Issues (if relevant)

1. magento/magento2 #19607: Page Not Found when deleting Attribute Set

### Manual testing scenarios (*)

1. Delete a product attribute set.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19614) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @cedcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
Hi @cedcommerce , thanks for the contribution. Delete operation should be performed using post request. So I think it is the actual request that is incorrect, not the controller marker.

Could you please take a look if it's possible to update the delete button here:
https://github.com/magento/magento2/blob/8c2e1789281c8ed95bfb60e74b071ff9f59ad2e9/app/code/Magento/Catalog/Block/Adminhtml/Product/Attribute/Set/Main.php#L130-L146

It might requeire some update to javascript here:
https://github.com/magento/magento2/blob/8c2e1789281c8ed95bfb60e74b071ff9f59ad2e9/app/code/Magento/Catalog/view/adminhtml/templates/catalog/product/attribute/set/main.phtml#L209

**Comment by cedcommerce** [comment]
ok @sivaschenko , i am checking the same. as it was a get request that's why i made changes on controller.I will update soon.

**Pull request closed without merging**
