### PR TITLE
MFTF: Admin Marketing Email Template Update Test

### PR DESCRIPTION
**Pull request by DmitryTsymbal**
This PR contains a test for updating created Email Templates.

**Steps to reproduce:**

1 - Create Email Template

2 - Find Created Email Template in grid

3 - Update Created Email Template

4 - Perform assertions

### CODE REVIEW

**Comment by dmytro-ch** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
Hello @DmitryTsymbal, thank you for your contribution!
It looks like there is a compatibility issue with B2B and Commerce tests, taking into account the builds fails during the tests generation phase. Could you please have a look?

Feel free to contact me if you need some help.

Thank you!

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello @DmitryTsymbal, thank you for your contribution!
It looks like there is a compatibility issue with B2B and Commerce tests, taking into account the builds fails during the tests generation phase. Could you please have a look?

Feel free to contact me if you need some help.

Thank you!

**Comment by engcom-Charlie** [comment]
Hi @DmitryTsymbal, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Comment by DmitryTsymbal** [comment]
@magento run all tests

**Comment by DmitryTsymbal** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run all tests

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello @DmitryTsymbal, could you please update your working branch with the latest changes from mainline and resolve merge conflicts?
There is also an issue reported by Semantic Version Checker. Could you please check and fix it as well?

**Comment by DmitryTsymbal** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
Hi

I am closing this PR for now as it seems like it has become stale and still needs work.

Please feel free to reopen if you wish to continue.

Thanks!

**Pull request closed without merging**
