### PR TITLE
fixed Translation issue send-friend in send.phtml #18779

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)
I think there is  no need to use escapeJs method as we are already using escapeHtml method.
Due to this string getting converted in hexadecimal. 

### Fixed Issues (if relevant)
1. magento/magento2#18779: Translation issue send-friend in sendphtml 

### Manual testing scenarios (*)
1. Add translation in module-send-friend module. put Name -> Na-me:. string will become Na\u002Dme\u003A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18821) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18821) before we can accept your contribution.<br/>**1** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: rahulwebkul<br/>:x: mastiuhin-olexandr<br/>:x: rostyslav-hymon<br/>:x: serhii-balko<br/>:x: magento-cicd2<br/>:x: viktym

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
Please do the same for ```$block->escapeHtml(__('Remove'))``` also.

**Comment by ghost** [comment]
@orlangur - code pushed with latest changes

**Review by orlangur — APPROVED** [review]
@rahulwebkul excellent 👍

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3285](https://jira.corp.magento.com/browse/ENGCOM-3285) has been created to process this Pull Request

**Comment by orlangur** [comment]
@rahulwebkul please get rid of changes not related to your fix with force push.

**Comment by ghost** [comment]
@orlangur - i am having some issues in my branch. I am pushing code again in some time.

**Pull request closed without merging**
