### PR TITLE
Prune triggers after setting database up properly

### LINKED ISSUE #2130: Error during installation on Magento >=2.4.1
### Preconditions
I develop in a Docker environment including Elasticsearch 7.7.1, Redis 6, PHP 7.4 and MariaDB 10.4

Magento Version : 2.4.2 EE (tested in 2.4.0 EE, 2.4.1 CE and 2.4.1 EE, too)
ElasticSuite Version : 2.10.3
Environment : Developer

Third party modules :
- "cweagans/composer-patches": "^1.7"
- "magento/magento-coding-standard": "^6.0"
-  "phpunit/phpunit": "~9.2.0"

### Steps to reproduce
1. `composer require smile/elasticsuite`
2. `bin/magento module:enable Smile_ElasticsuiteCore Smile_ElasticsuiteCatalog Smile_ElasticsuiteSwatches Smile_ElasticsuiteCatalogRule Smile_ElasticsuiteVirtualCategory Smile_ElasticsuiteThesaurus Smile_ElasticsuiteCatalogOptimizer Smile_ElasticsuiteTracker Smile_ElasticsuiteAnalytics Smile_ElasticsuiteAdminNotification`
3. `bin/magento setup:config:set --es-hosts elasticsearch:9200`
4. `bin/magento setup:config:set --es-enable-ssl 0`
5. `bin/magento setup:upgrade`

### Expected result
1. No errors and a clean execution of the command `setup:upgrade`.

### Actual result
1. `Cache types config flushed successfully
Cache cleared successfully
File system cleanup:
/var/www/default/generated/code/Composer
/var/www/default/generated/code/Fastly
/var/www/default/generated/code/Magento
/var/www/default/generated/code/PayPal
/var/www/default/generated/code/Psr
/var/www/default/generated/code/Smile
/var/www/default/generated/code/Symfony
The directory '/var/www/default/generated/metadata/' doesn't exist - skipping cleanup
Updating modules:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.smile_virtualcategory_catalog_category_product_position' doesn't exist, query was: CREATE TRIGGER trg_smile_virtualctgr_cat_ctgr_prd_position_after_insert AFTER INSERT ON smile_virtualcategory_catalog_category_product_position FOR EACH ROW
BEGIN
INSERT IGNORE INTO ``catalogsearch_fulltext_cl`` (``entity_id``) VALUES (NEW.``product_id``);
END`
2. If you run `setup: upgrade` again after this error, it will go through without errors. However, the trigger is then not created in the table.

### LINKED ISSUE #37304: [Issue] Prune triggers after setting database up properly
This issue is automatically created based on existing pull request: magento/magento2#33092: Prune triggers after setting database up properly

---------
### Description
When installing a new module which both installs tables and associated mview indexers, Magento fails to run `setup:upgrade` successfully.

This is because there is a step within `setup:upgrade` that's designed to prune old triggers from the database that happens before the new database state is established. The implementation detail of this prune is: remove all the known-good triggers, remove all other triggers, reinstate known-good triggers. It's the last step here that's causing issue. When this step tries to reinstate the "known-good" triggers, it's using the new code and therefore needs the new tables that haven't yet been created.

This pull request is a work-around for the problem described here. A proper fix would be to avoid unsubscribe/resubscribe of triggers within this prune step entirely.

### Related Pull Requests

*none*

### Fixed Issues
- Fixes https://github.com/Smile-SA/elasticsuite/issues/2130

### Manual testing scenarios

1. Install Magento
2. Set indexers to "Update by Schedule": php bin/magento indexer:set-mode schedule
3. Add [bug33092.tar.gz](https://github.com/magento/magento2/files/11083065/bug33092.tar.gz) with tar xzf bug33092.tar.gz
4. Enable the module with php bin/magento module:enable Magento_Bug33092
5. Run php bin/magento setup:upgrade
6. Witness error message / lack of error

### Questions or comments
*None*

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fredden**
### Description
When installing a new module which both installs tables and associated mview indexers, Magento fails to run `setup:upgrade` successfully.

This is because there is a step within `setup:upgrade` that's designed to prune old triggers from the database that happens before the new database state is established. The implementation detail of this prune is: remove all the known-good triggers, remove all other triggers, reinstate known-good triggers. It's the last step here that's causing issue. When this step tries to reinstate the "known-good" triggers, it's using the new code and therefore needs the new tables that haven't yet been created.

This pull request is a work-around for the problem described here. A proper fix would be to avoid unsubscribe/resubscribe of triggers within this prune step entirely.

### Related Pull Requests

*none*

### Fixed Issues
- Fixes https://github.com/Smile-SA/elasticsuite/issues/2130

### Manual testing scenarios
1. Install Magento
1. Set indexers to "Update by Schedule": `php bin/magento indexer:set-mode schedule`
1. Add `smile/elasticsuite` or similar
1. Enable the modules provided by the aforementioned composer package with `bin/magento module:enable`
1. Run `php bin/magento setup:upgrade`
1. Witness error message / lack of error

### Questions or comments
*None*

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37304: Prune triggers after setting database up properly

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
Hi @fredden 

Unfortunately, can't reproduce the issue.

I followed the below steps to reproduce the issue.

Test case 1:
        Step 1 : Installed magento 2.4.2
        Step 2: Created custom module and **created DB table using db_schema.xml**
        Step 3: Created the indexer in indexer.xml under custom module
        Step 4: Created the indexer view id in mview.xml
        Step 5: Ran the command "indexer: reindex"
        Step 6: Ran the command "setup:upgrade"
       **Output** -  No error, find the screenshots for the same
Screenshot 2021-06-01 at 7 00 28 PM
Screenshot 2021-06-01 at 7 06 18 PM

Test case 2:
        Step 1 : Installed magento 2.4.2
        Step 2: Created custom module and **created DB table using setup script**
        Step 3: Created the indexer in indexer.xml under custom module
        Step 4: Created the indexer view id in mview.xml
        Step 5: Ran the command "indexer: reindex"
        Step 6: Ran the command "setup:upgrade"
       **Output** -  No error, find the screenshots for the same
Screenshot 2021-06-01 at 5 21 38 PM
Screenshot 2021-06-01 at 5 31 53 PM
Screenshot 2021-06-01 at 6 01 06 PM
Screenshot 2021-06-01 at 6 00 23 PM

Test case 3:
        Step 1 : Installed magento 2.4.2
        Step 2: **Added smile/elasticsuite** 
        Step 3: Ran the command "setup:upgrade"
        Step 4: **Output** -  No error, find the screenshots for the same
Screenshot 2021-06-01 at 7 13 45 PM
Screenshot 2021-06-01 at 7 13 20 PM
Screenshot 2021-06-01 at 7 14 12 PM

Kindly requesting to you please verify the steps and let me know the more details for reproduce the issue.

**Comment by fredden** [comment]
Thanks for looking into this @engcom-Lima. I think the reason that you were unable to reproduce is that your indexers were in `realtime` mode (Update on Save), not `schedule` (Update by Schedule). I'll revise the steps to reproduce to include more details. I'll update here when that's done.

**Comment by engcom-Lima** [comment]
Hi @fredden

Sorry to say, We did not get any update from you more than 14 days. Hence, closing this ticket.

Please feel free to raise the new ticket or reopen the ticket if you have any issue with reproducible steps and screenshots.

**Comment by fredden** [comment]
I'm having trouble reproducing this reliably. I can reproduce, but I'm working on narrowing down the steps to a reliable set of instructions. I'll reopen this soon.

**Comment by fredden** [comment]
The following script reliably reproduces the problem:

```sh
#!/bin/sh
set -ex
git clone --depth=1 https://github.com/magento/magento2.git
cd magento2/var
git clone --depth=1 https://github.com/magento/inventory.git
cd ../app/code/Magento
for f in ../../../var/inventory/Inventory*/; do ln -s "$f" .; done
cd ../../..

composer install
php bin/magento setup:install --backend-frontname admin --db-host db --db-name magento2 --db-user magento2 --db-password magento2 --base-url http://localhost/ --use-rewrites 1 --search-engine elasticsearch7 --elasticsearch-host elasticsearch --document-root-is-pub 0
php bin/magento deploy:mode:set developer
php bin/magento setup:upgrade
php bin/magento indexer:set-mode schedule
# php bin/magento indexer:reindex

jq < composer.json '.replace["magento/module-inventory-sales-api"]="*"|.replace["magento/module-inventory-sales"]="*"|.replace["magento/module-inventory-indexer"]="*"' > composer.temp
mv composer.temp composer.json
composer require smile/elasticsuite

php bin/magento module:enable Smile_ElasticsuiteAdminNotification Smile_ElasticsuiteCore Smile_ElasticsuiteCatalog Smile_ElasticsuiteCatalogGraphQl Smile_ElasticsuiteCatalogRule Smile_ElasticsuiteCatalogOptimizer Smile_ElasticsuiteTracker Smile_ElasticsuiteThesaurus Smile_ElasticsuiteSwatches Smile_ElasticsuiteIndices Smile_ElasticsuiteAnalytics Smile_ElasticsuiteVirtualCategory

php bin/magento setup:upgrade
```

Screenshot_2021-06-25_00-48-19

**Comment by fredden** [comment]
@engcom-Lima please can you reopen this. I don't seem to have a button to do so myself.

**Comment by fredden** [comment]
@engcom-Lima please can you reopen this.

**Comment by sdzhepa** [comment]
@engcom-Lima 

Could you please take a look at this PR one more time according to the new comments?

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
Hi @krissyhiserote 
Thanks for your collaboration and contribution!
Could you please update about your review status
Thanks in advance

**Comment by hostep** [comment]
Hi @sdzhepa, @engcom-Lima, @engcom-Alfa, can we try to move this forwards again?
It looks like @krissyhiserote is not responding, so maybe this should be assigned to somebody else?

I can confirm that this PR fixes issue https://github.com/Smile-SA/elasticsuite/issues/2130 when using Magento 2.4.3-p2

**Comment by sdzhepa** [comment]
@engcom-Alfa, @engcom-Hotel 

Looks like [krissyhiserote](https://github.com/krissyhiserote) was suggested by GitHub automatization as a person for Code Review. It is just a suggestion and it does not mean she will(or has to) work on it.

So, feel free to take this PR in progress, do CR and all other required activities

**Review by swnsma — APPROVED** [review]
Hi @fredden,
Thank you for your contribution!

Overall, it seems that issue in system design itself (weird that \Magento\Framework\Mview\TriggerCleaner::removeTriggers is also responsible for re-instantiation of triggers).
In long run, it would be nice to have re-instantiation of triggers in separated method and call `removeUnusedTriggers` before `installSchema` and `installTriggers` after.
However, I can not think about scenario to force it now (even if referenced table is being dropped during `installSchema` setup it does not harm `removeUnusedTriggersStep`).

@engcom-Alfa, @sdzhepa, I guess we could proceed with this PR.

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
Hi @fredden,

Thanks for your contribution and collaboration.

I have tried to reproduce the issue in **2.4.6 composer installation** and the issue was reproducible here. I also observed that after the installation of the `smile/elasticsuite` module(version ^2.11), my setup is not working because of elasticsearch failure. Below is the screenshot for your reference:
image
**Frontend:**
image

I have checked the document from here -> [elasticsuite](https://github.com/Smile-SA/elasticsuite) , It is mentioned that they cannot ensure compatibility between **ElasticSuite <2.11** and **Magento >=2.4.6** versions.

Can you suggest us any other module/extension for testing this PR?

Thanks

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
Hi @engcom-Lima. I've run the reproduction script from https://github.com/magento/magento2/pull/33092#issuecomment-868061123, and can confirm that the bug exists on the current `2.4-develop` (currently a047c7639c63bf2b858e0bbd9689eb993a48a5a2). When the changes from this pull request are applied, the bug no longer shows up. It sounds like you've successfully verified the same.

From what I can tell, you're now having trouble with some specific functionality of a third-party module. Do you require me to create a new module which demonstrates this bug? This should be achievable with an indexer and a new database table.

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B,Functional Tests EE,Functional Tests CE,Unit Tests

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Lima** [comment]
Hi @fredden ,

Thanks for your contribution and collaboration.

> @engcom-Lima the failing 'Unit Test' is fixed in #37287 and is unrelated to the changes in this pull request. If the test failure is blocking you here, I recommend that you make #37287 more important / get it merged in.

Priority has been increased and internal team is working on it. 


:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

- Followed the steps given in  [comment](https://github.com/magento/magento2/pull/33092#issuecomment-1485873448) 

**Before:** :heavy_multiplication_x: Upgrade command was failing by giving SQLSTATE error.
Screenshot 2023-03-28 at 1 00 53 PM


**After:** :heavy_check_mark:  Upgrade command successfully executed.
Screenshot 2023-03-28 at 1 03 41 PM
Screenshot 2023-03-28 at 1 03 50 PM

Moving this PR to **Extended Testing** as multiple builds are failing.

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Delta** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Delta** [comment]
All the builds are green , Hence moving this PR to Merge in progress

Thanks

**Pull request merged**
