### PR TITLE
Fixed type issue. Create unit test for customer data model

### PR DESCRIPTION
**Pull request by AndreyChorniy**
### Description (*)

This PR fixed type issue in phpdocs. Create unit test for customer data model

### Manual testing scenarios (*)

We have not easy steps to manual test these changes.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by aleron75** [comment]
Hello @AndreyChorniy, first of all, thank you for your contribution!

I'm not a big fan of testing getters and setters, especially in this case where they just proxy calls to `\Magento\Framework\Api\AbstractSimpleObject`.

Nevertheless, why did you choose to test only `getGroupId()` and `getCreatedIn()`?
Let me know what you think, thanks!

**Comment by AndreyChorniy** [comment]
Hello @aleron75,

I agree with you that this is not a complex test and this is primitive test coverage for getter.
But I know that changes to the core will not be merged without test coverage, I have created this. 

This class was not covered by tests before, so I decided to start this from coverage for these two methods. But in my todo list to cover all methods from this class in the future.

**Comment by aleron75** [comment]
Thanks for clarifying @AndreyChorniy; I 've consulted with other maintainers and we decided to approve this PR. If you plan to cover other methods it will be very appreciated.

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-6751](https://jira.corp.magento.com/browse/ENGCOM-6751) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark:  QA Passed

- The typos are fixed
- The test is created and passes

**Pull request merged**
