### PR TITLE
Autoload for vendor root folders

### PR DESCRIPTION
**Pull request by Rus0**
### Description (*)

Added a validation for existing autoload file.

### Fixed Issues (if relevant)

1. magento/magento2#17753: Magento cannot run with custom Composer vendor directories

### Manual testing scenarios (*)

1. Create a temporary directory for vendor data: mkdir /tmp/composer-vendor-dir
2. Create a project directory: mkdir ~/magento-project
3. Set the Composer vendor directory: export COMPOSER_VENDOR_DIR="/tmp/composer-vendor-dir"
4. Create a Magento project: composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition ~/magento-project
5. Observe successful Composer installation
6. Attempt to access Magento CLI: php bin/magento

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Rus0. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-engcom-team** [comment]
@Rus0 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @Rus0. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Comment by hostep** [comment]
@magento-engcom-team or @sidolov : the changes in this PR use tabs for indentation instead of spaces, I'm wondering why the static tests didn't catch this?

**Comment by sidolov** [comment]
@hostep looks like this test disabled for the Travis, I'll check, thank you for the input!

**Pull request merged**
