### PR TITLE
#27500 Prepare Downloadable module Tests for PHPUnit 8

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Preparing PHPUnit Tests to run with PHPUnit 8.
PRs for each module is separated to make tests easier to merge.

### Fixed Issues (if relevant)
1. magento/magento2#27500

### Manual testing scenarios (*)
N/A

### Questions or comments
PR #27701 needs to be merged first (otherwise PHPUnit tests fail)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — COMMENTED** [review]
Hello @lbajsarowicz. Thank you for your contribution, you did a great job!

Unfortunately, the updated tests still result with numerous warnings while running with PHPUnit 8:
```
1) Magento\Downloadable\Test\Unit\Block\Adminhtml\Catalog\Product\Edit\Tab\Downloadable\LinksTest::testGetConfig
createPartialMock called with method(s) __wakeup that do not exist in Magento\Downloadable\Model\Product\Type. This will not be allowed in future versions of PHPUnit.
createPartialMock called with method(s) getStoreTitle that do not exist in Magento\Downloadable\Model\Link. This will not be allowed in future versions of PHPUnit.
createPartialMock called with method(s) __wakeup that do not exist in Magento\Framework\Registry. This will not be allowed in future versions of PHPUnit.

...

62) Magento\Downloadable\Test\Unit\Pricing\Price\LinkPriceTest::testGetLinkAmount
createPartialMock called with method(s) getProduct that do not exist in Magento\Downloadable\Model\Link. This will not be allowed in future versions of PHPUnit.

WARNINGS!
Tests: 192, Assertions: 694, Warnings: 62.
```

The PHPUnit 8 strongly encourages to avoid creating test doubles with non-existing methods.
Even though it does not lead to failures, shouldn't we fix these warnings as well?

Thank you!

**Comment by lbajsarowicz** [comment]
We need to fix these between 8 and 9. (I have bot for that already)

**Comment by dmytro-ch** [comment]
To be honest, I'm not sure if PO (or someone else responsible for this) will approve upgrade to the aforementioned PHPUnit version in case the 30% of tests end up with warnings.

**Comment by lbajsarowicz** [comment]
This is because of improper use of PHPUnit methods, not because migration.
Migration just revealed incompetence of people who wrote these tests. But sure. I can fix them too, but for now Community Engineering is currently thinking mostly on how to take down my PRs so I'm not going to fix them unless I have written confirmation that the would not throw our work away, because something I've done during one weekend, has been the subject of work for whole team of engineers for last weeks.

**Review by dmytro-ch — APPROVED** [review]
I partially agree. And I'll approve this PR and other ones having the same issue, just not to complicate the current situation more.
I was asking just because it would be great to make everything possible to avoid a second round of refactoring with tons of PRs while migrating from 8 to 9 versions.

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7412](https://jira.corp.magento.com/browse/ENGCOM-7412) has been created to process this Pull Request

**Comment by lbajsarowicz** [comment]
8 to 9 migration will be done in 1 PR 😅

**Pull request merged**
