### PR TITLE
Add missing semicolons for 'const' and 'let'

### LINKED ISSUE #35325: Magento 2.4.4 admin panel - Uncaught SyntaxError: Unexpected token 'const'
### Summary (*)
Magento 2.4.4 running on PHP 8.1 in Production mode

If you enable the js bundling and minify the scripts. 
`php bin/magento config:set  dev/js/minify_files 1`
`php bin/magento config:set  dev/js/enable_js_bundling 1`

After running the deployment and logging into the admin panel. We can't click on any menue option. There is an error in the browser console: *Uncaught SyntaxError: Unexpected token 'const'*

### Preconditions (*)
1. PHP 8.1
2. Magento 2.4.4, 2.4-develop
3. Magento instace should be in production mode

### Steps to reproduce (*)
1. Enable JS bundling.
2. Minify the JS files
3. Run deployment
4. Login to the admin panel.

### Expected result (*)
We should be able to access admin panel without any error.

### Actual result (*)
We are getting the following error and not able to click on any menu option:

Admin Error

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### LINKED ISSUE #35711: [Issue] Add missing semicolons for 'const' and 'let'
This issue is automatically created based on existing pull request: magento/magento2#35540: Add missing semicolons for 'const' and 'let'

---------
### Description
Semicolons are required according to the Magento coding standard:
https://github.com/magento/magento-coding-standard/blob/50e7c2ad3d7110b06527d75a1aa954b7c20f6ea1/eslint/.eslintrc-magento#L89

While there are many missing semicolons in these files, I have only fixed the `const` and `let` statements as these are causing problems for users in the admin - see https://github.com/magento/magento2/issues/35325

Ideally these files would conform to the Magento coding standard. Applying the auto-fix feature of `eslint` produced a much larger set of changes.

### Fixed Issues
1. Fixes https://github.com/magento/magento2/issues/35325

### Manual testing scenarios
See https://github.com/magento/magento2/issues/35325

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fredden**
### Description
Semicolons are required according to the Magento coding standard:
https://github.com/magento/magento-coding-standard/blob/50e7c2ad3d7110b06527d75a1aa954b7c20f6ea1/eslint/.eslintrc-magento#L89

While there are many missing semicolons in these files, I have only fixed the `const` and `let` statements as these are causing problems for users in the admin - see https://github.com/magento/magento2/issues/35325

Ideally these files would conform to the Magento coding standard. Applying the auto-fix feature of `eslint` produced a much larger set of changes.

### Fixed Issues
1. Fixes https://github.com/magento/magento2/issues/35325

### Manual testing scenarios
See https://github.com/magento/magento2/issues/35325

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#35711: Add missing semicolons for 'const' and 'let'

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
I guess it was partly fixed in https://github.com/magento/magento2/commit/faa7e0ee7f402ab518ad38f004467a26491d9ab4

**Comment by fredden** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests look not related to changes from this PR.

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B, Functional Tests CE , Functional Tests EE

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
1. make sure Magento instance running with PHP 8.1 version.
2. Magento instance should be in default/ production mode

**Manual testing scenario:**
1. Enable JS bundling using command: `php bin/magento config:set dev/js/enable_js_bundling 1`
3. Minify the JS files using command: `php bin/magento config:set dev/js/minify_files 1`
4. Run deployment command
5. Login to the admin panel and check JS errors in developer tool's console output.

**Before:** :heavy_multiplication_x: We were getting the error as shown in the below screenshot.
    image

**After:** :heavy_check_mark: We are not getting any errors and application is running smooth.
   image

Since it is an error in the console output based on specific pre-conditions, there is no additional regression test case is required.

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by fredden** [comment]
Adobe staff do not follow the same workflow that is enforced for community contributions.

**Pull request merged**
