### PR TITLE
[MFTF] Refactoring StorefrontOrderPagerDisplayedTest

### PR DESCRIPTION
**Pull request by AnnaAPak**
The test is refactored to improve execution time

### Related Pull Requests
https://github.com/magento/magento2/pull/33557

Please, note: the test is dependent on https://github.com/magento/magento2/pull/33557

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Semantic Version Checker

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, Semantic Version Checker

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
@AnnaAPak thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by Den4ik — APPROVED** [review]

**Comment by Den4ik** [comment]
> @AnnaAPak thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

@AnnaAPak Could you pay attention to this message

**Pull request merged**
