### PR TITLE
fixes-for-product-page-product-in-website-multi-store-view-not-display-proper

### PR DESCRIPTION
**Pull request by priti2jcommerce**
### Description (*)

2.3.0
On product page product in website for multi store view not display proper

### Manual testing scenarios (*)

1. create another store 
2. select that store for product 
3. display not proper 

### Expected result (*)
2019-02-22_14-06_chaz kangeroo hoodie

### Actual result (*)
2019-02-22_14-05_chaz kangeroo hoodie

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by priti2jcommerce** [comment]
* @magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce, here is your [Magento instance](https://i-21404-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21404-2-3-develop.instances.magento-community.engineering/admin](https://i-21404-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rogyar** [comment]
Hi @priti2jcommerce. Are you sure that setup.css modified within a scope of the current PR is related to the described issue?

**Comment by priti2jcommerce** [comment]
HI @rogyar 
Thanks for the update, creating new PR for this, Please check #21426

**Comment by rogyar** [comment]
Hi @priti2jcommerce. Thank you, I'm closing this one

**Pull request closed without merging**
