### PR TITLE
Fix integration test Magento\Elasticsearch6\Controller\QuickSearchTest

### PR DESCRIPTION
**Pull request by skovalenk**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/catalog-storefront/issues/102

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by skovalenk** [comment]
Issue: https://github.com/magento/catalog-storefront/issues/102

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7719](https://jira.corp.magento.com/browse/ENGCOM-7719) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@skovalenk thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request merged**
