### PR TITLE
CMS Page Store switcher fix

### PR DESCRIPTION
**Pull request by vpashovski**
Search by Request path instead of Target path

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24289) <br/>All committers have signed the CLA.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5698](https://jira.corp.magento.com/browse/ENGCOM-5698) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@vpashovski thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VladimirZaets** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, here is your [Magento instance](https://i-24289-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24289-2-3-develop.instances.magento-community.engineering/admin](https://i-24289-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Delta** [comment]
Hi @vpashovski Could you provide more information about how to reproduce issue with `if(!$currentRewrite)` statement?

**Comment by vpashovski** [comment]
Hi @engcom-Delta 
1. Create two store views.
2. Create CMS Page with same URL key for each store view.
3. Go to this page on frontend and try to switch the store.

Result without the fix is: Switching the store and redirect to home page
Expected result: Switch the store and stay on same page.

**Comment by sdzhepa** [comment]
Hello @vpashovski 

During PR processing we found that Magento team has already delivered the same fix by internal Pull Request.
Commit details:   https://github.com/magento/magento2/commit/0788dd4a7404db879f97c4a643e58fb4c178d055

Unfortunately, I have to close this PR

**Pull request closed without merging**
