### PR TITLE
Fix invalid @method phpdoc to prevent prophecy mocking error

### PR DESCRIPTION
**Pull request by tkotosz**
## Issue - Invalid docblock prevent using Prophecy

I am trying to use [Magento\Catalog\Model\Product](https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Model/Product.php) with Prophecy (using phpspec) and I get the following error :

```
could not double `Magento\Catalog\Model\Product` and implement interfaces: [Prophecy\Prophecy\ProphecySubjectInterface, Prophecy\Doubler\Generator\ReflectionInterface].
```
## Fix

After I found [this](https://github.com/phpspec/prophecy/issues/185) it turned out the Product class has invalid `@method` phpdoc [here](https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Model/Product.php#L26). So in order to fix this issue only this phpdoc need to be fixed.

### CODE REVIEW

**Comment by okorshenko** [comment]
@tkotosz, thank you for contribution!

CR: passed
Builds: red (known issue)
Resolution: OK to merge
Ticket: MAGETWO-42614

**Comment by tkotosz** [comment]
@okorshenko I have updated the PR since this issue appeared in other classes as well.

**Comment by magento-cicd** [comment]
We have automated a Magento Contributor License Agreement verifier for contributions sent to our GitHub projects.
Please see the CLA agreement in the Pull Request comments below.

**Comment by okorshenko** [comment]
@tkotosz , could you please merge latest changes from develop branch? Thank you

**Comment by tkotosz** [comment]
@okorshenko Done

**Pull request merged**
