### PR TITLE
magento/magento2#37028: [Sales] Missing relation data when reorder

### LINKED ISSUE #37028: [Sales] Missing relation data when reorder
### Preconditions and environment

- Magento version 2.4.5-p1
- PHP 8.1

### Steps to reproduce

1. Place an order
2. Reorder that order

### Expected result

- `relation_child_id` and `relation_child_real_id` are set in parent order row. A link is diplayed on parent order view to new order.
Capture d’écran 2023-03-08 à 10 07 31
- `relation_parent_id` and `relation_parent_real_id` are set in child order row. A link is diplayed on child order view to parent order.

Capture d’écran 2023-03-08 à 10 06 53

### Actual result

- `relation_child_id` and `relation_child_real_id` are not set in parent order row. No link is diplayed on parent order view to new order.
- `relation_parent_id` and `relation_parent_real_id` are not set in child order row. No link is diplayed on child order view to parent order.

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by KrasnoshchokBohdan**
- fix createOrder method to understand that order is reordered.

### Description (*)

Change \Magento\Sales\Model\AdminOrder\Create::createOrder to understand that order is reordered, before changes part of this method didn't work because it tries to get order from session, now it looks to 'reordered' parameter that added in \Magento\Sales\Model\AdminOrder\Create::initFromOrder 

### Related Pull Requests

--

### Fixed Issues (if relevant)

1. Fixes magento/magento2#37028

### Manual testing scenarios (*)

1. Place an order
2. Reorder that order from backend
3. Check on backend order page view

Before fix:
relation_child_id and relation_child_real_id are not set in parent order row. No link is diplayed on parent order view to new order.
relation_parent_id and relation_parent_real_id are not set in child order row. No link is diplayed on child order view to parent order.

After fix:
relation_child_id and relation_child_real_id are set in parent order row. A link is diplayed on parent order view to new order.
relation_parent_id and relation_parent_real_id are set in child order row. A link is diplayed on child order view to parent order.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run Functional Tests EE

**Comment by KrasnoshchokBohdan** [comment]
@magento run Functional Tests CE

**Comment by KrasnoshchokBohdan** [comment]
@magento run Unit Tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run Unit Tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run Functional Tests CE

**Comment by DanK894** [comment]
@magento run Functional Tests CE

**Comment by KrasnoshchokBohdan** [comment]
Failed tests seems flaky to me

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]
Hello @KrasnoshchokBohdan,

Thanks for the contribution!

Changes look good to me and the failed tests don't seems to be relevant to the changes. Hence approving the PR.

Thanks

**Comment by engcom-Lima** [comment]
Hi @KrasnoshchokBohdan ,

Thanks for your contribution and collaboration.

I have a query on below scenario -
After taking PR changes I have observed that parent order is getting cancelled when parent order is in pending state after reordering.Below is the screenshot for your reference:
Screenshot 2023-05-04 at 7 00 48 PM

Is this a expected behaviour? Question arised because before taking PR changes when order is in pending state and reordered then, parent order was not cancelled. 
So, Kindly provide us information about the query and inform us whether it will impact others functionality as well.

Thanks

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B , Functional Tests EE, Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

1. Place an order
2. Reorder that order from backend
3. Check on backend order page view

**Before:** :heavy_multiplication_x: 

Screenshot 2023-05-04 at 6 59 31 PM
Screenshot 2023-05-04 at 7 00 02 PM
Screenshot 2023-05-04 at 7 02 36 PM

**After:** :heavy_check_mark:  

Screenshot 2023-05-04 at 7 03 27 PM
Screenshot 2023-05-04 at 7 00 26 PM
Screenshot 2023-05-04 at 7 00 48 PM

Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run WebAPI Tests

**Comment by engcom-Charlie** [comment]
Hi @KrasnoshchokBohdan,

Thank you for your contribution!

While going through the PR, I have found that some regression issue is getting created by this PR changes.

In order to reproduce the issue, I have followed below steps.
1. Created new order
2. From admin side, created a reorder of the order created in step 1

**Issue**:
After creating reorder from parent order, I have found that, the parent order is getting in **Canceled** status and the newly created reorder is been in **Pending** status. On the other hand when I tested the same on current 2.4-develop, both the parent as well as the newly created reorder are showing in **Pending** status only. Hence it means that, in PR branch the status of the parent order is getting changed and its falling in wrong status.

**Adding some more information on it**:
In PR branch, I have also tested the reorder functionality at storefront. On store front the reorder functionality works just like current 2.4 develop branch means parent order and reordered order both are staying in **Pending** status only.

Clearly it seems that while achieving the purpose of this PR, new issue is getting created. Also if we are providing some feature on admin side, we should also implement the same at store front too.

@KrasnoshchokBohdan, can you please have a look at all above mentioned points. In order to proceed the PR further, we need fully implemented solution till that time we are moving it to On Hold status. Let us know when you are ready to work on it again, and we will be happy to move it back further. Thank you for your contribution

**Current  2.4-develop branch:**
After reorder
image

OnStorefront
image

**On PR branch:**
image

After reoder:
image

On Storefront:
image

After reordering from storefront:
image


Thank you!

**Comment by KrasnoshchokBohdan** [comment]
@engcom-Charlie I work on it again

**Comment by engcom-Charlie** [comment]
> @engcom-Charlie I work on it again

Thank you @KrasnoshchokBohdan!

**Comment by engcom-Charlie** [comment]
Hi @KrasnoshchokBohdan,

As per this [comment](https://github.com/magento/magento2/pull/37298#issuecomment-1552831717), this PR needs implemeentation changes hence making it as draft.  If you are going to create new PR for this issue, then we can close this PR and you can proceed. Or else you can continue on the same. Kindly let us know.

Thank you!

**Comment by KrasnoshchokBohdan** [comment]
@engcom-Charlie I will continue on the same PR

**Comment by KrasnoshchokBohdan** [comment]
@engcom-Charlie 
Hi, yes, I continue working on this.
Thank you!

**Comment by KrasnoshchokBohdan** [comment]
@engcom-Charlie
Hi!
I deleted the part with cancelling parent order, ran test that is related to this code, and tested it locally, now the new order and the parent order are in "pending" status!
image

**Comment by KrasnoshchokBohdan** [comment]
@magento run Functional Tests B2B

**Comment by KrasnoshchokBohdan** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
Hi @KrasnoshchokBohdan,

Thank you for the updates!

@engcom-Hotel can you please do the code review.

Thank you!

**Comment by engcom-Lima** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B, Integration Tests, Integration Tests

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**
1. Place an order
2. Reorder that order from the backend
3. Check on the backend order page view

**Before:** :heavy_multiplication_x: Child order id was not created while reordering.
Screenshot 2023-06-22 at 12 15 51 PM

Screenshot 2023-06-22 at 12 15 43 PM


**After:** :heavy_check_mark:  
Screenshot 2023-06-22 at 12 16 05 PM
Screenshot 2023-06-22 at 12 16 14 PM
**Link to previous order:**
image


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, Integration Tests, WebAPI Tests

**Comment by engcom-Charlie** [comment]
Hi @KrasnoshchokBohdan 

Thank you for modifying the PR for the regression points mentioned [here](https://github.com/magento/magento2/pull/37298#issuecomment-1552831717).

While checking the latest PR changes and current functional test failures, I have found that, the latest changes creating one new regression issue.

EditOrderFromAdminWithSavedWithinPayPalPayflowProCreditCardForRegisteredCustomerTest the functional test is getting failed because of the below mentioned regression scenario:-

From Admin section when we do "Edit Order" of an order which was placed with Credit Card PayPal pay flow Pro, the older order is not getting canceled. As per the current behaviour on magento 2.4-develop, the older order in this scenario should get canceled. Because of the new PR changes, both the orders( newly created from Edit order and original order) are being in Processing status which ultimately causing the test failure.

The PR needs the modification in order to take care of mentioned issue hence moving it to Changes Request. @KrasnoshchokBohdan can you please go have a look into it. 

Thank you!

**Comment by KrasnoshchokBohdan** [comment]
@engcom-Charlie I work on it

**Comment by engcom-Charlie** [comment]
Hi @KrasnoshchokBohdan,

Did you get a chance to look into the [mentioned](https://github.com/magento/magento2/pull/37298#issuecomment-1604243992) issue. 

Moving this in On Hold. Let us know once you are done with the new implementation.

Thank you!

**Comment by KrasnoshchokBohdan** [comment]
@engcom-Charlie Thank you!
I work on it!

**Comment by KrasnoshchokBohdan** [comment]
@magento run Functional Tests CE Functional Tests B2B Functional Tests EE WebAPI Tests Static Tests

**Comment by engcom-Charlie** [comment]
Thank you for the updates @KrasnoshchokBohdan!

Moving it for Testing.

**Comment by KrasnoshchokBohdan** [comment]
Failed tests seems flaky to me

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Review by engcom-Hotel — APPROVED** [review]
Failed tests seems flaky to me, hence approving this PR

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**
1. Place an order
2. Reorder that order from the backend
3. Check on the backend order page view

**Before:** :heavy_multiplication_x: Child order id was not created while reordering.
image


**After:** :heavy_check_mark:  
Screenshot 2023-07-26 at 3 27 50 PM
Screenshot 2023-07-26 at 5 20 45 PM
image
image


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**
1. Place an order
2. Reorder that order from the backend
3. Check on the backend order page view

**Before:** :heavy_multiplication_x: Child order id was not created while reordering.
image


**After:** :heavy_check_mark:  
Screenshot 2023-07-26 at 3 27 50 PM
Screenshot 2023-07-26 at 5 20 45 PM
image
image


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, WebAPI Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Unit Tests,Integration Tests,Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Unit Tests,Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
Failed test does not seems to related to PR.
Hence moving in `merge in progress`

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run Integration Tests, Unit Tests, WebAPI Tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run Integration Tests, Unit Tests, WebAPI Tests

**Comment by atIOCrON** [comment]
We updated to v2.4.7-p1 where this fix was pushed and it has caused problems because the "Reorder" button should not cause the new order to link to the previous one as suggested here.

We've been using Magento since 2009 and this was never the behaviour of the reorder button.

The link on the admin order page to a new order is only when you "Edit" an order. In that case, there should be a link because the orders are the same, you are editing one which cancels the first and makes the second, however, the reorder button is just a shortcut to place a brand new order for a client, it has nothing to do with the previous order.

This "fix" should be removed, it makes no sense at all.

**Comment by rhengeveldbordex** [comment]
We are encountering the same issue! All reorders are now being incorrectly linked to the original orders. I completely agree that this "fix" should be reverted. It’s frustrating and disrupts the intended functionality of the reorder button, which should create a brand new order without any ties to the previous one.

**Pull request merged**
