### PR TITLE
26214: Bundle Product / Create / Price validation for dynamic price

### LINKED ISSUE #26214: Bundle Product / Create / Price validation for dynamic price
### Preconditions (*)
1. Magento 2.4

### Steps to reproduce (*)
1. Enter "New Product / Bundle" form
2. Turn off "Dynamic price"
3. Enter the price and remove it. You'll see a validation error.

### Expected result (*)
1. Turning dynamic price back on should turn off validation on price field

### Actual result (*)
1. ezgif-7-7a7ea0e29f9d

### PR DESCRIPTION
**Pull request by phuocnh**
### Description (*)
- Fixed Bundle Product / Create / Price validation for dynamic price

### Fixed Issues (if relevant)

1. magento/magento2#26214: Bundle Product / Create / Price validation for dynamic price

### Manual testing scenarios (*)
1. Enter "New Product / Bundle" form
2. Turn off "Dynamic price"
3. Enter the price and remove it. You'll see a validation error.
4. Turn on "Dynamic price". You'll see remove a validation error.

video fixed https://youtu.be/zyPJw6udqO0

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by iibrah** [comment]
okfnfi

**Comment by iibrah** [comment]
Screenshot_٢٠١٩١٢٢٢-٠١٢٣١٢

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @phuocnh, thank you for your contribution. [Due to Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) the changes should be covered by tests. Could you please cover your fix by a MFTF test and also fix the static tests?
Thank you.

**Comment by phuocnh** [comment]
@eduard13 please check again
thanks

**Comment by eduard13** [comment]
Hi @phuocnh, as I mentioned previously, your changes have to be covered by an automated test. I'd suggest covering by a simple [MFTF](https://devdocs.magento.com/mftf/docs/getting-started.html) test.

**Comment by eduard13** [comment]
Hi @phuocnh, are you willing to continue the progress on this one? There is no much left till the end, as you should only cover your fix by a test.
Please let me know if you need any assistance.
Thank you.

**Comment by phuocnh** [comment]
Hi @eduard13

now all checks have passed, please check it
thanks

**Comment by eduard13** [comment]
Closing this one, as it looks like the repo doesn't exist anymore.

**Pull request closed without merging**
