### PR TITLE
Custom category layout update not affecting products.

### LINKED ISSUE #27285: Custom category layout update not affecting products
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Create a custom layout update

I created a file `catalog_category_view_selectable_276_noindexnofollow.xml` in `app/design/frontend/<VENDOR>/<THEME>/Magento_Catalog/layout`. That file should set noindex, nofollow for a certain category.

```xml
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <head>
        <meta name="robots" content="NOINDEX,NOFOLLOW"/>
    </head>
</page>
```
So we imagine we have a category with ID `276`, named _Shirts_.

2. In Admin got to the category with ID `276` and select this update via the **Custom Layout update** dropdown. Please see that I also set **Apply Design to Products**.

layout_update

3. Go to a sub category of this former category and enable **Use parent category settings**. Additionally I enabled **Apply Design to Products** for this category as well.

This is a subcategory of _Shirts_, named _Soccer Shirts_.

layout_update_sub

4. In the frontend check  the `head` section of this three pages:

* Category page _Shirts_
* Category page _Soccer shirts_
* Product page of category _Soccer shirts_

### Expected result (*)

1. :heavy_check_mark: The category page _Shirts_ should have `<meta name="robots" content="NOINDEX,NOFOLLOW">`: 
2. :heavy_check_mark:  The category page _Soccer shirts_ should have `<meta name="robots" content="NOINDEX,NOFOLLOW">`
3. :heavy_check_mark:  The product page of a product of _Soccer shirts_ should have `<meta name="robots" content="NOINDEX,NOFOLLOW">`:

### Actual result (*)

1. :heavy_check_mark:  The two category pages do have the entry  `<meta name="robots" content="NOINDEX,NOFOLLOW">`
2. :x: The product page of the sub category _Soccer shirts_ does not have this entry

### PR DESCRIPTION
**Pull request by engcom-Kilo**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/27285

### Manual testing scenarios (*)

1. see https://github.com/magento/magento2/issues/27285

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Review by Stepa4man — APPROVED** [review]
Hi @engcom-Kilo 
Thanks for your contribution

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, thank you for the review.
[ENGCOM-8789](https://jira.corp.magento.com/browse/ENGCOM-8789) has been created to process this Pull Request
:eight_spoked_asterisk: @Stepa4man, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by zakdma — APPROVED** [review]

**Comment by engcom-Oscar** [comment]
:heavy_check_mark: QA passed
Was checked case from Manual testing scenarios 
:x: **Before:**
The two category pages do have the entry <meta name="robots" content="NOINDEX,NOFOLLOW">
x The product page of the sub category does not have this entry
Screenshot from 2021-02-22 08-47-44

:heavy_check_mark: **After:**

Screenshot from 2021-02-22 10-02-43
Screenshot from 2021-02-22 10-02-57
Screenshot from 2021-02-22 10-03-08

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-32217`.

**Pull request merged**
