### PR TITLE
Fix HTML syntax in report.phtml error template

### PR DESCRIPTION
**Pull request by abcpremium**
Added missing quotes to the div tags with class `control`.

### Description
Added **missing quotes** to the class attribute of div tags in the default reporting template file in **pub/errors/default/report.phtml**

### Manual testing scenarios

1. Open in any editor with syntax highlighting, it shouldn't show any more syntax warnings.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15454) <br/>All committers have signed the CLA.

**Comment by avoelkl** [comment]
Hi @abcpremium! Thanks for the PR! I can see the quotes are missing in the 2.3-develop branch as well. Once this PR is done it would be great to apply the same in the 2.3 branch (if you like).

**Review by avoelkl — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @avoelkl, thank you for the review.
[ENGCOM-1654](https://jira.corp.magento.com/browse/ENGCOM-1654) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@abcpremium thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by abcpremium** [comment]
Hey @avoelkl, thanks for accepting the PR. However, this is my first PR ever, so when you say I should do this for 2.3-develop also, do you mean the exact same procedure as this one? Or can I "modify" this PR to include both 2.2-develop and 2.3-develop? Sorry for this stupid question *shame on me*

**Comment by avoelkl** [comment]
Hi @abcpremium,
No shame, there's a first time for everything!
Actually you would need to apply the same changes on the 2.3 branch and create a new pull request. Please do not modify this pull request. I hope this helps :)

**Comment by avoelkl** [comment]
Actually there is a tool for porting changes here: [https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically). I haven't tried it myself but if you want to give it a try I am sure we can find someone to help with this.

**Comment by magento-engcom-team** [comment]
Hi @abcpremium. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

Please, consider porting this solution across release lines.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Comment by abcpremium** [comment]
@avoelkl Alright I used the tool to port my changes to 2.3-develop. Really easy to use it, nice!

**Pull request merged**
