### PR TITLE
Remove unused integration test

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Clean unused integration test file seem this file not call or depends in codebase

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @mrtuvn,
It feels like this test covers the following class, which exists in the codebase:
https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/View/Model/Layout/Merge.php

Isn't it?
If so - it seems like the integration test is located in the wrong directory/namespace. I think it's good to move it

**Comment by ihor-sviziev** [comment]
@mrtuvn feels like following test covers much less use cases:
https://github.com/magento/magento2/blob/2.4-develop/dev/tests/integration/testsuite/Magento/Framework/View/Model/Layout/MergeTest.php

Can we combine them into a single class?

**Comment by mrtuvn** [comment]
I'm not sure maybe you are right. 2 files mentioned is 2 difference cases cover for origin class Magento/Framework/View/Model/Layout/Merge.php

**Pull request closed without merging**
