### PR TITLE
Improve Bundle Option & Selection Data Extensibility

### LINKED ISSUE #34805: [Issue] Improve Bundle Option & Selection Data Extensibility
This issue is automatically created based on existing pull request: magento/magento2#34803: Improve Bundle Option & Selection Data Extensibility

---------

### Description (*)
Updated the visibility from `private` to `public` for the following functions in `Magento\Bundle\Block\Catalog\Product\View\Type\Bundle` for improved extensibiility:
- `getOptionItemData()`
- `getSelectionItemData()`

### Manual testing scenarios (*)
1. Create a new local module
2. Create a before/after/around plugin for each of the aforementioned functions
3. Configure the plugin in `etc/di.xml`
4. Enable the module
5. Enable and configure Xdebug and add breakpoints in your plugin(s)
6. Load a bundle product page on the frontend
7. Ensure the plugin(s) breakpoint(s) are hit

### Questions or comments
I don't know why these were originally declared `private` functions so if there's a reason this change cannot be made, please let me know.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by pykettk**
### Description (*)
Updated the visibility from `private` to `public` for the following functions in `Magento\Bundle\Block\Catalog\Product\View\Type\Bundle` for improved extensibiility:
- `getOptionItemData()`
- `getSelectionItemData()`

### Manual testing scenarios (*)
1. Create a new local module
2. Create a before/after/around plugin for each of the aforementioned functions
3. Configure the plugin in `etc/di.xml`
4. Enable the module
5. Enable and configure Xdebug and add breakpoints in your plugin(s)
6. Load a bundle product page on the frontend
7. Ensure the plugin(s) breakpoint(s) are hit

### Questions or comments
I don't know why these were originally declared `private` functions so if there's a reason this change cannot be made, please let me know.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#34805: Improve Bundle Option & Selection Data Extensibility

### CODE REVIEW

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by fredden** [comment]
@magento run all tests

**Comment by pykettk** [comment]
@magento run all tests

**Comment by pykettk** [comment]
@magento run all tests

**Comment by pykettk** [comment]
@magento run Semantic Version Checker Static Tests

**Comment by pykettk** [comment]
@magento run all tests

**Comment by pykettk** [comment]
@magento run Database Compare

**Comment by pykettk** [comment]
@magento run Static Tests

**Comment by pykettk** [comment]
@magento run Semantic Version Checker

**Comment by pykettk** [comment]
@magento run all tests

**Comment by torhoehn** [comment]
@magento run all tests

**Comment by pykettk** [comment]
@magento run all tests

**Comment by pykettk** [comment]
@magento run all tests

**Comment by pykettk** [comment]
@magento run all tests

**Comment by pykettk** [comment]
@magento run all tests

**Review by fredden — APPROVED** [review]

**Review by leonhelmus — APPROVED** [review]

**Comment by engcom-Dash** [comment]
Hello @pykettk,

Thanks for the collaboration & contribution!

✔️ QA Passed
Preconditions:
Install fresh Magento 2.4-develop

Steps to reproduce

- Create [a plugin](https://developer.adobe.com/commerce/php/development/components/plugins/) for the Magento\Bundle\Block\Catalog\Product\View\Type\Bundle::getOptionItemData() and Magento\Bundle\Block\Catalog\Product\View\Type\Bundle function::getSelectionItemData functions
- Observe that the plugin code executes as expected

Before: ✖️
Since we can't create a plugin for a private method, it will not be triggered anyway.

After: ✔️
Plugin is triggered.
image


Builds are failed. Hence, moving this PR to Extended Testing.

Thanks

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
Hello @pykettk, It seems your branch is disabled (I’m unable to click on it), so I can’t run the build on your PR. Could you please check it and take the necessary action?

**Comment by pykettk** [comment]
@engcom-Dash I will have to open a new PR for this - the original branch was deleted when I was doing some cleanup given that it is almost 3 years old 😂

**Comment by pykettk** [comment]
Closing in favour of #39271

**Pull request closed without merging**
