### PR TITLE
Filter out Dynamic SKU fragments for multi-select Options

### LINKED ISSUE #26297: Inconsistent Dynamic SKU behavior with multi-select Customizable options
Magento's SKU builder for Customizable Options behaves inconsistently. It ignores empty values for single selections, but then concatenates multiple empty values when evaluated from an Option array, such as a Checkbox or Multi-select Option.

This behavior is defined in
[`Magento\Catalog\Model\Product\Option\Type\Select::getOptionSku`](https://github.com/magento/magento2/blob/2.2/app/code/Magento/Catalog/Model/Product/Option/Type/Select.php#L279-L292)

### Preconditions (*)
1. Magento 2.2.10
2. PHP 7.2

### Steps to reproduce (*)
1. Create any simple product
2. Add a Checkbox or Multi-Select Customizable Option
3. Configure at least two options (of any Title and Price), leaving the SKU fragments empty.
4. On the frontend, add this product to your cart, selecting both custom options.
5. In the `quote_item` table (or within the order after checkout), observe the SKU.

### Expected result (*)
1. Because we have not configured any SKU fragments, the SKU should not be altered - a base product SKU of "TEST_SKU" should remain so.

### Actual result (*)
1. Quote/Order Item has a SKU of "TEST_SKU--", a result of concatenating the SKU with the array of concatenated Options containing (empty) SKU fragments.

### PR DESCRIPTION
**Pull request by Morgon**
### Description (*)
When using Product Options, Magento builds a Dynamic SKU based on the options selected. When you omit the SKU fragment for single-value types, Magento does not append a value to the Dynamic SKU. However, multi-select values are built in an array, which is then imploded. 

Magento does not currently evaluate whether any of those values are empty, which can result in extraneous delimiters appearing at the end of the SKU. By using `array_filter` to toss out any blank SKU fragments, we can enact consistent behavior through all types.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#26297 Inconsistent Dynamic SKU behavior with multi-select Customizable options

### Manual testing scenarios (*)

1. Create any simple product
2. Add a Checkbox or Multi-Select Customizable Option
3. Configure at least two options (of any Title and Price), leaving the SKU fragments empty.
4. On the frontend, add this product to your cart, selecting both custom options.
5. In the quote_item table (or within the order after checkout), observe the SKU.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — CHANGES_REQUESTED** [review]
@Morgon please, cover changes with automated test

**Comment by engcom-Charlie** [comment]
Hi @Morgon please, cover changes with automated tests. Otherwise, we can't proceed with your PR.
Thank you.

**Comment by engcom-Charlie** [comment]
@Morgon I'll take care of test coverage.

**Comment by engcom-Charlie** [comment]
@Morgon Unfortunately I don't have access to push test coverage to your PR.

**Comment by engcom-Charlie** [comment]
Hi @Morgon, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
