### PR TITLE
Fix grammar in demo store notice

### PR DESCRIPTION
**Pull request by erikhansen**
Fix grammar in demo store notice. The current notice says:

> This is demo store. No orders will be fulfilled.

It should say:
> This is a demo store. No orders will be fulfilled.

### CODE REVIEW

**Review by okorshenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, thank you for the review.
[ENGCOM-621](https://jira.corp.magento.com/browse/ENGCOM-621) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@erikhansen thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
@erikhansen thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by sidolov** [comment]
Fixed translation file according to changes

**Comment by magento-engcom-team** [comment]
@erikhansen thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by erikhansen** [comment]
@magento-engcom-team I've accepted that agreement.

@sidolov Thanks for catching that.

**Pull request merged**
