### PR TITLE
34084: Replaced tag 'br' to a valid version

### LINKED ISSUE #34084: Replace `</br>` with a valid version of `<br />`
### Preconditions (*)

1. 2.3.7

### Steps to reproduce (*)

1. Search the codebase for `</br>`

### Expected result (*)

1. No results, as `</br>` isn't a valid HTML tag. Its deprecated XHTML and basically a stray closing tag.

### Actual result (*)

1. Quite some references to `</br>` in various (magento) modules. 

I'd opt for using `<br />` over `<br>` as it follows the guidelines for self-closing HTML elements.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ X ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ X ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by AZiniukhin**
### Description (*)

Deprecated "\<br\>" and "\</br\>" tags were changed to their valid version "\<br /\>"

### Fixed Issues (if relevant)

1. Fixes magento/magento2#34084

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by BarnyShergold** [comment]
@magento run all tests

**Comment by xmav** [comment]
Hi @ihor-sviziev 
yes, jQuery require tags to be properly closed. It is important to have "correct" tags in html that will be manipulated by jquery. From that point it is not needed to update tags in translations like `Warning!<br />This action will remove this user from already assigned role.<br />Are you sure?` as this should not affect jquery but will be backward [incompatible](https://devdocs.magento.com/contributor-guide/backward-compatible-development/#translatable-phrases)

**Comment by BarnyShergold** [comment]
@magento run all tests

**Comment by xmav** [comment]
@BarnyShergold I believe this should be addressed by @AZiniukhin

**Comment by hostep** [comment]
Maybe take [the following comment](https://github.com/magento/magento2/issues/34084#issuecomment-921682043) into account as well? Or are there valid cases for keeping a space in the tag in the year 2021?

**Review by orlangur — CHANGES_REQUESTED** [review]
Please use a shorter tag version as suggested in https://github.com/magento/magento2/pull/34136#issuecomment-924264885

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

**Comment by DanielRuf** [comment]
Magento 2 uses html5 as doctype so this makes no real difference afaik.

Where is documented, that `<br>` does not work for jQuery? Because this is the valid version for empty elements in html5, `<br/>` would be xhtml.

**Comment by DanielRuf** [comment]
I did not find any depreciation comment at https://www.w3.org/TR/2011/WD-html5-author-20110809/the-br-element.html

**Comment by BarnyShergold** [comment]
> @BarnyShergold I believe this should be addressed by @AZiniukhin

Yes - sorry, wrong tag entered!

**Comment by orlangur** [comment]
@DanielRuf ok :) We have too many `<br />` with or without space currently in code but without enforcing only one variant let's not touch them.

**Review by orlangur — CHANGES_REQUESTED** [review]
@AZiniukhin as pointed out in discussion `<br>` is perfectly valid so don't touch them.

Just change all `</br>` to `<br>`.

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by BarnyShergold** [comment]
@magento run functional tests CE,Integration Tests,Static Tests,Unit Tests

**Comment by orlangur** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
Simply <br> is sufficient and consistency

**Comment by engcom-Dash** [comment]
Hello @AZiniukhin ,

Thank you for your contributions!

Please resolve the conflict so we can proceed with this PR?

Thanks again!

**Comment by engcom-Dash** [comment]
Closing this PR since it has not been updated in a while. Please feel free to reopen if needed.

**Pull request closed without merging**
