### PR TITLE
[PERF Improvements]Load polyfills for browsers that don't support certain features

### LINKED ISSUE #28382: [Issue] [PERF Improvements]Load polyfills for browsers that don't support certain features
Here I'm using RequireJS configuration and the whole deps mechanism to conditionally load browser features polyfils only when needed. Changes in this PR include:

### Preconditions (*)

1. Magento version 2.3.5 

### Expected result (*)

UI components, e.g. in checkout or admin are still functional.
Polyfills for Map, WeakMap, FormData and MutationObserver are loaded only for old browsers that do not support them.

### Actual result (*)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by krzksz**
### Description (*)
This PR is a part of my effort to improve Magento 2 frontend performance.

Here I'm using RequireJS configuration and the whole `deps` mechanism to conditionally load browser features polyfils only when needed. Changes in this PR include:

### Manual testing scenarios (*)

1. UI components, e.g. in checkout or admin are still functional.
2. Polyfills for Map, WeakMap, FormData and MutationObserver are loaded only for old browsers that do not support them.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28382: [PERF Improvements]Load polyfills for browsers that don't support certain features

### CODE REVIEW

**Comment by okorshenko** [comment]
memo: We do have a recording of this demo.

**Comment by ihor-sviziev** [comment]
@krzksz looks like it will be not easy to cover these changes with automatic tests. Do you think it's possible to cover your changes with some tests?

**Comment by ihor-sviziev** [comment]
As we discussed in Slack - it's too hard to cover these changes with automated tests, so I put label "not required"

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @krzksz,
Your changes looks good to me.
Could you fix static tests?

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7285](https://jira.corp.magento.com/browse/ENGCOM-7285) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [new Magento instance](https://pr-27618.instances.magento-community.engineering).
Admin access: [https://pr-27618.instances.magento-community.engineering/admin_8eb0](https://pr-27618.instances.magento-community.engineering/admin_8eb0)
Login: `e84ff395` Password: `12428af099a7`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

UI components are still functional and polyfills for Map, WeakMap, FormData, and MutationObserver aren't loaded for new browsers.

**Comment by VladimirZaets** [comment]
@magento create issue

**Comment by VladimirZaets** [comment]
@magento run all tests

**Pull request merged**
