### PR TITLE
Percent of product price discount not working with exclude sku condition #36528

### LINKED ISSUE #36528: Percent of product price discount not working with exclude sku condition
### Preconditions and environment

- Magento 2.4.5

### Steps to reproduce

1. Set SKU attribute 'use for promo rule conditions' true.
2. Add coupon code test with exclude product by SKU
3. Add few product in cart and apploy coupon code

### Expected result

Discount should apply for all product except exclude product using sku condition.

### Actual result

Discount apply in all product without excluding product mention rule

### Additional information

Here is ref. snapshot for the same.
test10-Promotions-Marketing-Magento-Admin
Joust-Duffle-Bag
Shopping-Cart

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Kannakiraj123**
### Description (*)
   Percent of product price discount not working with exclude sku condition

### Related Pull Requests
        1.I checked particular item matched to cart rule condition using "$rule->getConditions()->validate($item)". 

### Fixed Issues (if relevant)

1. Fixes  #36528

### Manual testing scenarios (*)
  1.Set SKU attribute 'use for promo rule conditions' true.
  2.Add coupon code test with exclude product by SKU
 3.Add few product in cart and apploy coupon code
  4.Discount should apply for all product except exclude product using sku condition.

### CODE REVIEW

**Comment by Kannakiraj123** [comment]
@magento run all tests

**Comment by Kannakiraj123** [comment]
@magento run all tests

**Comment by Kannakiraj123** [comment]
@magento run all tests

**Comment by Kannakiraj123** [comment]
@magento run Static Tests

**Comment by Kannakiraj123** [comment]
@magento run unit tests

**Comment by Kannakiraj123** [comment]
@magento run unit tests

**Comment by Kannakiraj123** [comment]
@magento run all tests

**Comment by Kannakiraj123** [comment]
@magento run all tests

**Comment by Kannakiraj123** [comment]
@magento  run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @Kannakiraj123,

Please take care of the failed tests.

Thanks

**Comment by engcom-Charlie** [comment]
Hi @Kannakiraj123,

Thank you for your contribution!

@engcom-Hotel, as per this [comment](https://github.com/magento/magento2/issues/36528#issuecomment-1513084965), this is not the issue which is getting address here.

Kindly refer this document https://experienceleague.adobe.com/docs/commerce-admin/marketing/promotions/cart-rules/price-rules-cart-create.html?lang=en#step-2%3A-describe-the-conditions.

```
Conditions section serves to specify conditions that will be applied to whole cart.
Add conditions in the Actions tab to limit the number of products affected by the cart price rule.
```

As per this closing this PR. Please feel free to reopen it for any updates.

Thank you!

**Pull request closed without merging**
