### PR TITLE
[Catalog|MediaStorage] Use theme for image frame param calculation

### LINKED ISSUE #19710: Magento 2.3 images cache generation generates wrong hash for some images with a custom theme that has the keep_frame var set to 0
### Summary (*)
I just upgrade my Magento 2 project from 2.2.6 to 2.3. After the upgrade, some images in the catalog are showing placeholders instead of the images. I have regenerated the images cache with the catalog:images:resize but some images are still missing (swatch images in category pages and image thumbnail in category pages).

After some investigation, it seems that is it a problem with the hash used for the image cache directory. When generating the images cache in the CLI, all images have in their misc params used to build the hash a value of "keep_frame" => 1, although in the view.xml file of my custom theme, the param "product_image_white_borders" is set to 0. When generating the image path for the catalog pages, the keep frame param is 0. 

My investigation led me to the ParamsBuilder class (module-catalog/Model/Product/Image/ParamsBuilder) that uses its viewConfig property to get the value of the var "product_image_white_borders" in the "hasDefaultFrame" function. Seemingly, when running the CLI command, the view config that is injected in the ParamsBuilder is not the same that is used by the ImageResize command, and it has a wrong "product_image_white_borders" value of 1. It seems that it does not use the theme that the ImageResize command is currently processing, and its scope is global. 

### Environment
Magento 2.3 Open Source with custom frontend theme

### Examples (*)
Assign images to products in the catalog.
Set the value of the variable "product_image_white_borders" to 0 in your custom theme view.xml file.
Regenerate product images cache with the CLI command catalog:images:resize.

### Proposed solution
The product thumbnail in category pages should appear but instead the placeholder image is shown.

### PR DESCRIPTION
**Pull request by Den4ik**
### Description (*)

This PR replace for https://github.com/magento/magento2/pull/33413 with fixed unit tets
Full description available in issue magento/magento2#19710

### Fixed Issues (if relevant)

1. Fixes magento/magento2#19710

### Manual testing scenarios (*)

1. Assign images to products in the catalog.
2. Set the value of the variable "product_image_white_borders" to 0 in your custom theme view.xml file.
3. Regenerate product images cache with the CLI command catalog:images:resize.
4. The product thumbnail in category pages should appear

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Unit Tests

**Comment by ihor-sviziev** [comment]
@Den4ik I think this PR continues https://github.com/magento/magento2/pull/33413 ?

**Comment by Den4ik** [comment]
@ihor-sviziev if https://github.com/magento/magento2/pull/33413 will not be updated soon this PR replace original

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Unit Tests

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Unit Tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9147](https://jira.corp.magento.com/browse/ENGCOM-9147) has been created to process this Pull Request

**Comment by engcom-Charlie** [comment]
Hi @Den4ik and @ihor-sviziev,
Thanks for your contribution!!

As its mentioned in one of the [comment](https://github.com/magento/magento2/issues/19710#issuecomment-873100828) , I have first tried to reproduce this issue on 2.4 develop branch.  I am following below steps:

1. Setup magento 2.4 develop 
2. Enable the developer mode
3. Created custom theme and applied to the store
4. Added few products with images
5. As a result, On store front, I can see new theme with added products along with images
6. Set the value of the variable "product_image_white_borders" to 0 in custom theme view.xml file.
7.  Run bin/magento catalog:images:resize command
8. After all above steps, I can still able to see the catalog product images on store front.

Can you please mention if I am missing any step to reproduce the issue since currently its not reproducible with above steps. 

Although I will try to reproduce the issue by upgrading magento framework from mentioned version in issue but it will be helpful if you provide some details on it.

Thank you in advance!

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
I'm close this PR due to `themeModel` precalculated at https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/View/Asset/Repository.php#L156-L168 and no need pass to param builder

**Pull request closed without merging**
