### PR TITLE
Minor refactoring to AccessChangeQuoteControl and it's Unit Tests

### LINKED ISSUE #29672: [Issue] Minor refactoring to AccessChangeQuoteControl and it's Unit Tests
This issue is automatically created based on existing pull request: magento/magento2#29670: Minor refactoring to AccessChangeQuoteControl and it's Unit Tests

---------
### Description (*)
Improve the Unit Tests, adjust the plugin.
Introduced `: void` to return type of plugin, that does not require from us to make extra assertions in Unit Tests to the return type.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)
N/A

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Improve the Unit Tests, adjust the plugin.
Introduced `: void` to return type of plugin, that does not require from us to make extra assertions in Unit Tests to the return type.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)
N/A

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29672: Minor refactoring to AccessChangeQuoteControl and it's Unit Tests

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8027](https://jira.corp.magento.com/browse/ENGCOM-8027) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Actual Result:** :heavy_check_mark: We've got a StateException "Invalid state change requested"

**Pull request merged**
