### PR TITLE
Fix BadMethodCallException when some modules are disabled

### LINKED ISSUE #29642: [Issue] Fix BadMethodCallException when some modules are disabled
This issue is automatically created based on existing pull request: magento/magento2#25508: Fix BadMethodCallException when some modules are disabled

---------
When the "magento/module-amqp" and "magento/module-bundle-graph-ql" modules are disabled a request to /rest/default/V1/guest-carts/XXXXXXXXX/estimate-shipping-methods fails with the following error.
`Exception #0 (BadMethodCallException): Missing required argument $resolvers of Magento\Framework\MessageQueue\ConnectionTypeResolver.`

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by nocturnalfrog**
When the "magento/module-amqp" and "magento/module-bundle-graph-ql" modules are disabled a request to /rest/default/V1/guest-carts/XXXXXXXXX/estimate-shipping-methods fails with the following error.
`Exception #0 (BadMethodCallException): Missing required argument $resolvers of Magento\Framework\MessageQueue\ConnectionTypeResolver.`

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29642: Fix BadMethodCallException when some modules are disabled

### CODE REVIEW

**Review by orlangur — CHANGES_REQUESTED** [review]
Shouldn't this be added to global `di.xml` instead? Please check failed tests also

**Comment by nocturnalfrog** [comment]
Hi @orlangur,

Correct me if I'm wrong, but I haven't been able to find a framework component with a di.xml file?
Also, I think the default value in the signature is a lot more transparant, wouldn't you agree?

**Comment by nocturnalfrog** [comment]
Hi @orlangur,

Please review this PR again.
Thanks!

**Comment by VladimirZaets** [comment]
Hi @nocturnalfrog, the `di` path for framework level is `app/etc/di.xml`

**Comment by nocturnalfrog** [comment]
@VladimirZaets,
I don't see a single precedent in `app/etc/di.xml` for creating an empty `xsi:type="array"` argument. 
I do count over 200 cases in the `vendor/magento` where a  `__construct` method has an argument that has an empty array as a default value. 

Can you clarify why you think my code changes are not the correct way of fixing this particular bug?

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6338](https://jira.corp.magento.com/browse/ENGCOM-6338) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@nocturnalfrog thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @nocturnalfrog. Can you please cover your solution by automated tests?
Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

**Comment by nocturnalfrog** [comment]
@VladimirZaets,
I thing the label `Auto-Tests: Not Required` applies in this case, wouldn't you agree?

**Comment by VladimirZaets** [comment]
@nocturnalfrog I think this case can be covered by integration tests, so if we can cover it, why we shouldn't?

**Comment by nocturnalfrog** [comment]
Hi @VladimirZaets,
Can you refer me to an example / an existing integration test that covers a similar situation?

**Comment by nocturnalfrog** [comment]
Hi @VladimirZaets,
Can you refer me to an example / an existing integration test that covers a similar situation?

**Comment by orlangur** [comment]
@nocturnalfrog I'll try to find something similar, basically the idea is to have some dummy modules with similar situation in integration test.

**Comment by engcom-Golf** [comment]
I'll take care of test coverage

**Comment by sidolov** [comment]
@magento create issue

**Review by lenaorobei — DISMISSED** [review]

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @nocturnalfrog .

Unfortunately, we are not able to reproduce this problem on a fresh 2.4-develop instance.

**Manual testing scenario:**

1. Disable Amqp and BundleGraphQL modules 
(Run in console: `php bin/magento module:disable Magento_Amqp Magento_BundleGraphQl`);
2. Go to swagger -> quoteGuestShipmentEstimationV1

3. Click on **Execute** button;

**Actual Result:** :heavy_check_mark: Response 200 OK 



@nocturnalfrog Maybe we missed something?
Could you take a look?

Thanks!

**Comment by gabrieldagama** [comment]
Closing this PR since the issue was not reproducible on 2.4. Please feel free to reopen it anytime.

**Pull request closed without merging**
