### PR TITLE
Update menu.xml

### LINKED ISSUE #30435: [Issue] Update menu.xml
This issue is automatically created based on existing pull request: magento/magento2#30428: Update menu.xml

---------
Preconditions (*)
Magento 2.4-develop
Login as Customer is enabled
Steps to reproduce (*)
Go to backend
Expected result (*)
https://xd.adobe.com/view/b9d43ac6-ee9f-4e94-516a-70dd15b45232-cfe5/screen/87f8df4a-baae-4830-8080-04b7bda23670/Log-admin-3
image
Actual result (*)
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by gulshanchitransh**
Preconditions (*)
Magento 2.4-develop
Login as Customer is enabled
Steps to reproduce (*)
Go to backend
Expected result (*)
https://xd.adobe.com/view/b9d43ac6-ee9f-4e94-516a-70dd15b45232-cfe5/screen/87f8df4a-baae-4830-8080-04b7bda23670/Log-admin-3
image
Actual result (*)
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30435: Update menu.xml

### CODE REVIEW

**Comment by sivaschenko** [comment]
#dmcdindia2020

**Comment by sivaschenko** [comment]
@magento create issue

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @gulshanchitransh. Thank you for your collaboration. Could I ask you to cover this change by an MFTF or integration test, please? The test will check that the "Login as Customer" item belongs to the correct parent item

**Comment by sidolov** [comment]
@gulshanchitransh  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
