### PR TITLE
Fix Ui-Select (Multiselect) close button issues

### LINKED ISSUE #27240: Magento 2.3.4 .action-close broken when Multiselect is used in a modal
### Preconditions (*)

1. Magento 2.3.4 and the default Magento Backend theme

### Steps to reproduce (*)

1. Create a modal form in the admin section with insertForm and add a multiselect uiComponent in the form
2. When the modal opens, add an element to the multiselect.

### Expected result (*)

1. The close button has to be next to the item name and included in the item element.

Capture d’écran 2020-03-11 à 12 18 48

### Actual result (*)

1. The action-close button is broken because it inherits the CSS of the .action-close button of the modal

Capture d’écran 2020-03-11 à 12 08 55

I will open a PR with the fix for this issue shortly

### PR DESCRIPTION
**Pull request by LyraGhost**
### Description (*)

1. Fix positioning of remove/close button for ui-select in single-select mode (in form and in modal)
Before:
image
After:
image

2. Fix positioning of remove/close button in multiple-select mode when used in a modal (see linked issue)
image

### Fixed Issues (if relevant)

1. Also Fixes magento/magento2#27240
(PR was never opened for issue and was similar to fix I was applying for single-select mode, so I included it)

### Manual testing scenarios (*)

For fix 1. above:
1. Create form ui component with ui-select field.
2. Set the following config for the field:
    - multiple: false
    - chipsEnabled: false
    - isRemoveSelectedIcon: true

For fix 2. above:
1. Create form ui component with modal.
2. Add ui-select field in modal.

### Questions or comments

I'm not really sure if tests are applicable to this, but if so I'll need help writing them as I don't know how to go about doing so.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Den4ik** [comment]
@magento run all tests

**Review by Den4ik — APPROVED** [review]
✅ Approved

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9104](https://jira.corp.magento.com/browse/ENGCOM-9104) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@LyraGhost thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run WebAPI Tests

**Comment by engcom-Charlie** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**
 1. Created Ui Form and added Ui-Select component in it with following configuration

- multiple: false
- chipsEnabled: false
- isRemoveSelectedIcon: true

**Actual Result:** :heavy_check_mark:
 1. Verified that Close button position is correct and properly inline. 

**After:** :heavy_check_mark:  

image

**Before:** :heavy_multiplication_x: 
 
image


2. Created Ui Form and added Ui-multiselct component in it with below configuration
- multiple: true
- chipsEnabled: false
- isRemoveSelectedIcon: true

**Actual Result:** :heavy_check_mark:
1. Verified that Close button position is correct and properly inline. 

**After:** :heavy_check_mark:  

 image

**Before:** :heavy_multiplication_x: 
image

**Tested all the manual scenarios, no impact on regression testing.**

**Pull request merged**
