### PR TITLE
#23766 - fix pattern validation on form submit

### PR DESCRIPTION
**Pull request by vahir2016**
On checkout cart validation submit with Jquery, fix pattern validation bug

### Description (*)

Force param to be interpreted as regex.

### Fixed Issues (if relevant)

1. magento/magento2#<23766>: On checkout cart submit, pattern regex validation fails

### Manual testing scenarios (*)

1. On checkout cart page, use input type text for quantity and use pattern like "[0-9]"
2. Bind jquery submit to submit form on input change
3. The form should submit with no error in broswer console

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23767) <br/>All committers have signed the CLA.

**Comment by vahir2016** [comment]
Hello, 

Done.

**Comment by vahir2016** [comment]
Hello, 

This is my first PR for Magento, should I do something more ?

Ty

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5557](https://jira.corp.magento.com/browse/ENGCOM-5557) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@vahir2016 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by vahir2016** [comment]
Hello,

Done.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
