### PR TITLE
bugfix: fix cartFix rules incorrect discount ammount

### LINKED ISSUE #38694: [Issue] Sales rule CartFixed calculation : incorrect discount amount
### Preconditions and environment

- Magento version 2.4.7

### Steps to reproduce

1. Create a sales rule "test1", without coupon, cart fixed amount = 5€ (Discard subsequent rules = no)
2. Create a sales rule "test2", without coupon, cart fixed amount = 10€ (Discard subsequent rules = no)
3. Create a sales rule "test3", with coupon 'test3', cart fixed amount = 1€ (Discard subsequent rules = no)
4. Create a frontend cart, with total amount > 20€
5. Add coupon test3

### Expected result

Discount of 16€

### Actual result

Discount different of 16€, amount change when cart items changes.

### Additional information

The difference between amount applied and correct amount can be very big  - it depends on rules amounts, and items in cart. In one of our cases, we saw a 90€ discount applied, instead of 40€...

I'm still on debug. The issue is probably somewhere between  `src/vendor/magento/module-sales-rule/Model/Rule/Action/Discount/CartFixed.php::calculate` and `src/vendor/magento/module-sales-rule/Helper/CartFixedDiscount.php::getDiscountedAmountProportionally`. I will update the issue if I get more informations.

Update : I really don't understand what's the goal of `getDiscountedAmountProportionally` method. It can sometimes - and sometimes it does - produce a ratio bigger than 1, hence appliying a bigger discount than expected. Even when the ratio is under 1, I don't really get why we lower the discount. I guess such "proportionality" could be usefull for % discounts, to avoid that two -10% sum up at -20% instead of -19% (-10% on a -10% discount). But for fixed cart price, I don't understand..

So a quickfix is to simply remove it, by replacing `if ($isAppliedToShipping) {` with `if (true || $isAppliedToShipping) {` in CartFixed class. This is of course a temporary ugly fix, that you can apply at your own risk, but in our case it fixed the error and we stopped losing money (or making our customers angry) because of it. Now, let's wait for an answer from a Magento architect.

Update 2 : Same issue with rules that only applies on shipping amounts. (apply on shipping amount = Yes + Apply on product where name = 'some inexistant name').
Seems because of another ratio in `src/vendor/magento/module-sales-rule/Helper/CartFixedDiscount.php::getShippingDiscountAmount`.  But https://github.com/magento/magento2/issues/38671 needs to be fixed to be tested.

Quick fix for that (at your own risks) : 
```
--- a/Model/Validator.php	2024-05-03 08:38:15
+++ b/Model/Validator.php	2024-05-03 08:38:05
@@ -486,6 +486,14 @@
                                     $quoteBaseSubtotal,
                                     $shippingQuoteAmount
                                 );
+
+                            $quoteBaseSubtotal = (float) $address->getBaseShippingAmount();
+                            foreach ($quote->getAllItems() as $item) {
+                                if ($rule->getActions()->validate($item)) {
+                                    $quoteBaseSubtotal += (float) $item->getBaseRowTotal();
+                                }
+                            }
+
                             $discountAmount = $this->cartFixedDiscountHelper->
                             getShippingDiscountAmount(
                                 $rule,

```

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by joacols**
- Add init totals into foreach rules loop to allow for total calculation after each rules apply on Discount.php

- remove logic for adding item discount to address base discount on Discount.php

- on CartFixed.php now use validator to calculate current valid items total discount for rule on proporcional discount calculation.

refs: #38694

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38694

### Manual testing scenarios (*)
1.     create multiple cartFix rules and apply them. 

3.     also, see the case reported in the issue to be sure. 

### Questions or comments
 i tested this on my project with my own integration tests. is there a simple way of seting up this github environment?
a one liner setup would be excelent if there is none but i dont have the time to set it up right now. 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by joacols** [comment]
@magento run all tests

**Comment by joacols** [comment]
failed tests have nothing to do with my code

**Comment by engcom-Bravo** [comment]
Hi @joacols,

Thank you for your contribution!

The Magento core engineering team is working on the issue which you have addressed in this PR. Team will cherry pick the commits from your PR and may do further implementation to cover few more scenarios as needed. We will reach out to you if we need more information. For now, you can pause work on this PR.

Thank you once again!

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket ACP2E-3349 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-3349&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta2.

Thanks

**Comment by joacols** [comment]
> Hello,
> 
> As I can see this issue got fixed in the scope of the internal Jira ticket ACP2E-3349 by the internal team Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-3349&type=commits
> 
> Based on the Jira ticket, the target version is 2.4.8-beta2.
> 
> Thanks

Hi, 
Even though the problem has been solved, the way of solving it still breaks the validator class.

**Pull request closed without merging**
