### PR TITLE
Use U.S. English spelling for 'optimization'.

### PR DESCRIPTION
**Pull request by davidangel**
### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by orlangur — CHANGES_REQUESTED** [review]
1. We must not change code of third-party libraries (like KnockoutJS)
2. Changing fieldset name is backward-incompatible as to me: http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/index.html#magento-apis

**Comment by orlangur** [comment]
@davidangel, thanks for your contribution, it looks like all places which could be changed are already fixed in https://github.com/magento/magento2/pull/11345.

**Comment by davidangel** [comment]
1. Reverted. Is there a reason knockout.js isn't included via npm?
2. I was not able to find any other instances of `search_engine_optimisation` in the codebase. I was able to find 7 other results for `search_engine_optimization`. Are we sure this change is not desired?

**Comment by orlangur** [comment]
>  Is there a reason knockout.js isn't included via npm?

Yes. We don't want NodeJS on prod. It could be included via some Composer plugins but for now it works like that.

> Are we sure this change is not desired?

Yeah, third-party customizations are relying on names. Keeping them unbroken is lesser evil than a typo in caption not shown to end user.

**Pull request closed without merging**
