### PR TITLE
[fix] typo in method name _exportAddress[s]es

### PR DESCRIPTION
**Pull request by mhauri**
### Description
Method name `\Magento\Paypal\Model\Api\Nvp::_exportAddressses` contained typo
Renamed it to `_exportAddresses`.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-1581](https://jira.corp.magento.com/browse/ENGCOM-1581) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@mhauri thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by miguelbalparda — CHANGES_REQUESTED** [review]
Protected methods cannot be removed, please check https://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/index.html

**Comment by DanielRuf** [comment]
> Protected methods cannot be removed, please check devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/index.html

What exactly do you mean?

**Review by DanielRuf — APPROVED** [review]

**Comment by mhauri** [comment]
@miguelbalparda I've added the deprecated notice in commit: https://github.com/magento/magento2/pull/15275/commits/1a0c8e50a0698ac4c9dbe55aae32c9d1bd650109

**Review by DanielRuf — APPROVED** [review]

**Comment by miguelbalparda** [comment]
Hi @DanielRuf, I saw you approved quite  a few PRs. We try to reserve this for maintainers, in the future feel free to add +1 or emoji answers instead of that. Thanks!

**Comment by DanielRuf** [comment]
> in the future feel free to add +1 or emoji answers instead of that. Thanks!

Ok, understood. Did not know this. Sorry.

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-1581](https://jira.corp.magento.com/browse/ENGCOM-1581) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @mhauri. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

Please, consider porting this solution across release lines.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
