### PR TITLE
[Backport] 2.2 .gitignore to 2.1

### PR DESCRIPTION
**Pull request by aschrammel**
### Description
This PR includes the additional folders and files added in 2.2-develop `.gitignore` in 2.1-develop

### Fixed Issues (if relevant)
-

### Manual testing scenarios
1. Checkout and pull 2.1-develop branch from upstream
2. In my case the `generated` folder was marked as untracked
3. Apply PR
4. `generated` folder is not longer marked as untracked

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by orlangur — CHANGES_REQUESTED** [review]
For each added row please make sure that it is really needed in `2.1-develop` and update PR accordingly.

**Comment by orlangur** [comment]
@aschrammel manual testing scenario is incorrect also: `generated` folder has nothing to do with `2.1.x` branch line, looks like you switched from `2.2.x` at some point. Simply remove the untracked `generated` folder if you stay on `2.1.x`.

**Comment by VladimirZaets** [comment]
The files `grunt-config.json`, `/dev/tools/grunt/configs/local-themes.js` are also absent in 2.1.x branches

**Comment by VladimirZaets** [comment]
Hi @aschrammel , I am closing PR because these changes are not necessary for 2.1-branch.
If you have any objections or you want to discuss please reopen this PR.
Thank you for collaboration

**Pull request closed without merging**
