### PR TITLE
magento/magento2#28564: Handle empty masked quote id return case

### LINKED ISSUE #28564: Handle empty masked quote id return case
**Issue found:**

When we try to create a masked quote id in a scenario, "When a new customer is created on storefront and on using mutations to create customer token for same customer and a cart using CustomerCart on CustomerCart resolver in Magento/QuoteGraphQl/Model/Resolver/CustomerCart.php.

We figured out that masked quote id is empty (" ")is given from Magento/Quote/Model/QuoteIdToMaskedQuoteId.php and quote*id*mask table, even when quote->getId() is created in Quote table,

We fixed it on resolver level, but it needs a core code fix. An additional logic need to be added in **Magento/Quote/Model/QuoteIdToMaskedQuoteId.php** that checks for such cases where a quote id is present and create a non empty masked id on a requested quote.

After fixing this, revert the changes accordingly in **Magento/QuoteGraphQl/Model/Resolver/CustomerCart.php* and make sure that the *testGetLoggedInCustomerCartWithoutMaskedQuoteId* still passes in *dev/tests/api/functional/testsuite/Magento/GraphQl/Quote/Customer/GetCustomerCartTest.php* *without any changes**.

### PR DESCRIPTION
**Pull request by pmarjan**
Update resolver: delegate resolving to Quote CustomerCartResolver

### CODE REVIEW

**Comment by pmarjan** [comment]
@magento run all tests

**Review by rogyar — APPROVED** [review]
Good job!

**Comment by rogyar** [comment]
Additional autotests are not required here since the changed logic is already covered by API-functional tests. It's just a refactoring of the existing resolver.

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7681](https://jira.corp.magento.com/browse/ENGCOM-7681) has been created to process this Pull Request

**Review by danielrenaud — APPROVED** [review]

**Pull request merged**
