### PR TITLE
JSON Controlller implements HttpPostActionInterface

### PR DESCRIPTION
**Pull request by jignesh26**
### Description (*)

When the admin trying to add the new reviews, its calling the post request to JsonProductInfo, and this class implemented HttpGetActionInterface hence it throws 404. I checked changed the implemented HttpGetActionInterface to HttpPostActionInterface

### Manual testing scenarios (*)

1. Admin Menu -> Marketing -> Review -> Add New Review -> Select Product it will redirect to review page form with product detail.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19680) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @jignesh26. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
Hi @jignesh26 , thanks for your contribution! As I can see the updated controller is not updating the application state and is used to retrieve the data. So I believe it should be called using `GET` method.

Considering the above, it's the client code that should be updated to call the controller using the `GET` method instead.

**Comment by jignesh26** [comment]
Hi @sivaschenko,

Thank you for reviewing my comment, but as its using in the admin and using the below code, 

$this->setRowClickCallback('review.gridRowClick');
$this->setUseAjax(true);
This only use the post request, and i think for the admin all ajax call is done via post actions.

It would be great if we use the post action interface or both in case i have seen many other controllers are using the both actions. 

Let me know sivaschenko, in which flow i need to go.

**Comment by sivaschenko** [comment]
Hi @jignesh26 I think that request is initiated here: https://github.com/magento/magento2/blob/f77f96b0df866862b822beeb74766353dd41f01a/app/code/Magento/Review/Block/Adminhtml/Add.php#L59

BTW, That's a very interesting file as you can see, that requires refactoring in general. In case you have some time and you'd like not just to fix the issue but also extract the JS from the php file - it will be very much appreciated :)

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [new Magento instance](https://pr-19680.instances.magento-community.engineering).
Admin access: [https://pr-19680.instances.magento-community.engineering/admin](https://pr-19680.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-4091](https://jira.corp.magento.com/browse/ENGCOM-4091) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@jignesh26 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by jignesh26** [comment]
@sivaschenko Thanks for reviewing the request.

**Comment by sdzhepa** [comment]
Hello @jignesh26 

Thank you for contribution and collaboration!

We found these changes were already made and delivered into current `2.3-develop` branch:  https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Review/Block/Adminhtml/Add.php#L59

Commit details: https://github.com/magento/magento2/commit/eed3bc376b8afa124effb1870fd2ab20ac433b14
PR details: https://github.com/magento/magento2/pull/20146

This PR can be closed

**Pull request closed without merging**
