### PR TITLE
Fix HttpMethodValidator produces 404 instead of 405 response

### LINKED ISSUE #24018: HttpMethodValidator produces 404 instead of 405 response
### Summary

The validation based on the new (2.3.0+) HTTP method marker interfaces (HttpGetActionInterface, HttpPostActionInterface, ...) throw an exception that is turned into a 404 response by the front controller:

```
        throw new InvalidRequestException(
            new NotFoundException(new Phrase('Page not found.'))
        );
```

A proper response status code would be `405 Method Not Allowed`.

### Steps to reproduce

1. Make a GET request to an action with `HttpPostActionInterface`
2. Watch the status code received.

### Expected Result
1. 404 Not Found.

### Actual Result
1. 405 Method Not Allowed.

### Proposed solution

1. Use a different "replace result" than `NotFoundException` that at least returns an error page with the correct status code. **Minimum solution: send correct status code**
2. Do not mis-use exceptions as results at all **Architectural improvement: do not mix unrelated types**
3. Add more marker interfaces to determine the type of result, i.e. `JsonActionInterface`, `HtmlActionInterface`, ... and return a different body depending on those **Ideal solution: enable handling of 405 errors in different context**

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)

HttpMethodValidator produces 404 instead of 405 response
### Fixed Issues (if relevant)

1. Fixes magento/magento2#24018 : HttpMethodValidator produces 404 instead of 405 response

### Manual testing scenarios (*)

1. Make a GET request to an action with HttpPostActionInterface
2. Watch the status code received.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by buskamuza** [comment]
Please see https://github.com/magento/architecture/pull/10#discussion_r205481001

**Comment by buskamuza** [comment]
Also, I think this can be considered a breaking change, as HTTP response codes should be considered public API. Though I don't thinks our docs cover it now. But it can potentially break someone.

**Comment by AlexMaxHorkun** [comment]
https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html
`An origin server SHOULD return the status code 405 (Method Not Allowed) if the method is known by the origin server but not allowed for the requested resource, and 501 (Not Implemented) if the method is unrecognized or not implemented by the origin server. The methods GET and HEAD MUST be supported by all general-purpose servers`

**Comment by AlexMaxHorkun** [comment]
I think we initially wanted to return 405 but stumbled upon this specification. Also if I'm remembering correctly Varnish would not take 405 response to GET and HEAD requests well so it basically broke page-cache

**Comment by AlexMaxHorkun** [comment]
I don't think functional tests that are being run during community PR employ varnish and it would be dangerous to merge this. Page-cache bugs are hard to fix and detect

**Comment by AlexMaxHorkun** [comment]
Also I don't see `Allow` header being generated when the exception is thrown, am I missing something?

**Comment by buskamuza** [comment]
IMO, 405 code makes sense. But according to specs (https://tools.ietf.org/html/rfc7231#section-6.5.5) `The origin server MUST generate an
   Allow header field in a 405 response containing a list of the target
   resource's currently supported methods.`. So if we move in this direction, could you please take a look at implementing the `Allow` header as well, and also please check items mentioned by @AlexMaxHorkun . And ... as usual, consider backward compatibility impact.
Could you please create a small document to https://github.com/magento/architecture repo with description of design changes? Thanks.

**Pull request closed without merging**
