### PR TITLE
improve Magento\Catalog\Model\ImageUploader error handler

### PR DESCRIPTION
**Pull request by fsw**
### Description (*)
Magento\Catalog\Model\ImageUploader is catching detailed exceptions and turning it into generic "Something went wrong while saving the file(s)." Data on what actually went wrong is gone.
This fix logs exception and passes previous exception to constructor not to loose this info.

Also I would like to discuss if there are some guidelines on handling such cases in Magento 2.
In my humble opinion in development mode we show detailed info and in production mode we show "something went wrong" and log exception so catching exception just to show "Something went wrong while saving the file" in both modes and loose debug info does not make much sense and I would remove both this try/catches at all.

### Manual testing scenarios (*)

1) change media dir permissions to not writable
2) upload a file in admin panel
3) see info on what folder lacks permissions in error log.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lenaorobei — CHANGES_REQUESTED** [review]
I agree with adding logging, but for security reasons we dont want to expose additional info.

**Comment by fsw** [comment]
> I agree with adding logging, but for security reasons we dont want to expose additional info.

Yes but additional info is hidden anyway in production mode (witch is indeed great for security). I think showing stack in developer mode and logging it in production and showing generic message is a good logic and can't see why we should treat some cases differently.

**Comment by lenaorobei** [comment]
`LocalizedException` is designed to be shown to the end user and it is not recommended to add any additional info other then allowed to be displayed. Logging should be good enough in this case.

**Comment by fsw** [comment]
@lenaorobei , way of handling exceptions is of course disputable hence I was wondering is there any official Magento guidance for it.
Just to be clear, I was not opting to add any additional info to `LocalizedException` but to simply remove try/catches like this.

Because without this specific try/catch:
* in development mode we show full details
* in production we show "something went wrong" witch is also translatable

And without it:
* in development we show "something went wrong saving the file" witch is not very helpful
* in production we change "something went wrong" to "something went wrong saving the file" witch is also not very helpful
* we have 5 LOC more increasing complexity without any profit.

hence I think second option is better.

**Comment by lenaorobei** [comment]
QA notes: please make sure that extended message is shown in development mode only.

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-7067](https://jira.corp.magento.com/browse/ENGCOM-7067) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@fsw thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Golf** [comment]
Failed functional tests not related to the changes in this PR

**Pull request merged**
