### PR TITLE
Create empty modelData array to avoid undefined var error

### PR DESCRIPTION
**Pull request by peterjaap**
### Description

Create empty modelData array to avoid undefined var error further in the function if the change type is not one of the listed cases

### Fixed Issues (if relevant)

None

### Manual testing scenarios

-

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by sidolov** [comment]
@magento-engcom-team combine 18530

**Comment by magento-engcom-team** [comment]
Hi @sidolov. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
@peterjaap all pull requests have been successfully combined together: 
 - merged https://github.com/magento/magento2/pull/18530: Change expected Exception namespace to fix docblock

**Comment by sidolov** [comment]
@magento-engcom-team combine 18531

**Comment by magento-engcom-team** [comment]
Hi @sidolov. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
@peterjaap all pull requests have been successfully combined together: 
 - merged https://github.com/magento/magento2/pull/18531: Removed unused class import for Magento\Framework\App\State

**Comment by magento-engcom-team** [comment]
Hi @peterjaap. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
