### PR TITLE
Removed CliCacheFlushActionGroup usage for ConfigurableProduct module

### LINKED ISSUE #31954: [Issue] Removed CliCacheFlushActionGroup usage for ConfigurableProduct module
This issue is automatically created based on existing pull request: magento/magento2#31953: Removed CliCacheFlushActionGroup usage for ConfigurableProduct module

---------
### Description
Removed CliCacheFlushActionGroup usage for ConfigurableProduct, CatalogUrlRewrite, Config, Contact and Cookie modules.

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Removed CliCacheFlushActionGroup usage for ConfigurableProduct, CatalogUrlRewrite, Config, Contact and Cookie modules.

### Resolved issues:
1. [x] resolves magento/magento2#31954: Removed CliCacheFlushActionGroup usage for ConfigurableProduct module

### CODE REVIEW

**Comment by sergiy-v** [comment]
@magento create issue

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B,Semantic Version Checker

**Comment by sergiy-v** [comment]
Few things should be fixed, working on it.

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Semantic Version Checker

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run WebAPI Tests, Unit Tests, Static Tests, Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B, Magento Health Index, Integration Tests, Database Compare

**Comment by sergiy-v** [comment]
All tests are green, @eduard13 please proceed with review. 
Thanks.

**Review by eduard13 — APPROVED** [review]
Good job 👍

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8731](https://jira.corp.magento.com/browse/ENGCOM-8731) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
Manual QA is not applicable. Moving this PR to _Extended Testing_ column

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run Functional Tests EE

**Comment by gabrieldagama** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
Hello @gabrieldagama, just FYI, all tests are green.
Thank you!

**Pull request merged**
