### PR TITLE
Remove wishlist sidebar for wishlist index page

### LINKED ISSUE #29674: [Issue] Remove wishlist sidebar for wishlist index page
This issue is automatically created based on existing pull request: magento/magento2#28441: Remove wishlist sidebar for wishlist index page

---------

### Description (*)

Remove wishlist sidebar for wishlist index page
### Fixed Issues (if relevant)

1. Fixes magento/magento2#N/A

### Manual testing scenarios (*)

1. Add product into a wishlist for registered customer
2. visit My wishlist page

### Expected result
After-My_Wish_List

### Actual result
before-My_Wish_List

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

Remove wishlist sidebar for wishlist index page
### Fixed Issues (if relevant)

1. Fixes magento/magento2#N/A

### Manual testing scenarios (*)

1. Add product into a wishlist for registered customer
2. visit My wishlist page

### Expected result
After-My_Wish_List

### Actual result
before-My_Wish_List

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29674: Remove wishlist sidebar for wishlist index page

### CODE REVIEW

**Comment by ravi-chandra3197** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
@magento create issue

**Comment by sdzhepa** [comment]
It looks like Duplicate of
https://github.com/magento/magento2/pull/25345
https://github.com/magento/magento2/issues/25344

**Comment by sidolov** [comment]
@ravi-chandra3197 I'm closing the PR as duplicate of https://github.com/magento/magento2/pull/25345

**Pull request closed without merging**
