### PR TITLE
Fixed Orders and Returns page layout design improvement #21132

### PR DESCRIPTION
**Pull request by abrarpathan19**
### Description (*)

1. Go to Luma theme footer links click on **"Orders and Returns"** page
2. Check the consistance layout as per the luma theme contact page create account page etc

### Fixed Issues (if relevant)

1. magento/magento2#21132:Magento luma theme Orders and Returns page layout design improvement

### Manual testing scenarios (*)

1. Go to Luma theme footer links click on **"Orders and Returns"** page

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @abrarpathan19. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by amol2jcommerce** [comment]
Duplicate #20817

**Comment by abrarpathan19** [comment]
@amol2jcommerce 
Why you have closed my issue? Let review to Magento  Reviewer/Maintainers, which solution is the better, let decided to the reviewer.

**Comment by Karlasa** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Karlasa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Karlasa, here is your [Magento instance](https://i-21133-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21133-2-3-develop.instances.magento-community.engineering/admin](https://i-21133-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by Karlasa — COMMENTED** [review]
@abrarpathan19 
I will close this PR as fix for issue what was described in description is already been merged and this code is not currently needed. Feel free to create code refactoring PR if you feel that merged PR can be done better.

Cheers,
Karla

**Pull request closed without merging**
