### PR TITLE
Removed CliIndexerReindexActionGroup action group usage for Sales module

### LINKED ISSUE #31801: [Issue] Removed CliIndexerReindexActionGroup action group usage for Sales module
This issue is automatically created based on existing pull request: magento/magento2#31788: Removed CliIndexerReindexActionGroup action group usage for Sales module

---------
### Description
Remove CliIndexerReindexActionGroup action group usage from tests to improve execution time for Sales, SalesRule, Search, Store and Swatches modules.

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Remove CliIndexerReindexActionGroup action group usage from tests to improve execution time for Sales, SalesRule, Search, Store and Swatches modules.

### Resolved issues:
1. [x] resolves magento/magento2#31801: Removed CliIndexerReindexActionGroup action group usage for Sales module

### CODE REVIEW

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B,Semantic Version Checker

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests B2B

**Comment by rogyar** [comment]
@magento create issue

**Review by rogyar — APPROVED** [review]
Great job!

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8681](https://jira.corp.magento.com/browse/ENGCOM-8681) has been created to process this Pull Request

**Comment by sergiy-v** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Pull request merged**
