### PR TITLE
Improvement/CE-33708: Update PHPUnit to 9.4.4

### LINKED ISSUE #33708: Update `phpunit/phpunit` composer dependency to version ~9.4.0 (STAGE 2)
This issue is a STAGE 2 of the magento/magento2#33596.
We need to upgrade `phpunit/phpunit` to the version ~9.4.0 (that equals to the version 9.4.4) with fixes of the codebase of the Magento tests.

### Related issue (*)
1. magento/magento2#33596 - parent issue
2. magento/magento2#33707 - STAGE 1
3. magento/magento2#33709 - STAGE 3

### PR DESCRIPTION
**Pull request by bohdan-harniuk**
### Description (*)
This PR contains updating to the PHPUnit v. 9.4.4 and fixes for 9 warnings in unit tests. Those warnings are not an issue of upgrade to PHPUnit 9.4.4, but actual for the current platform health or 2.4-develop branches with the PHPUnit 9.2.6.
Some of the similar warnings were fixed in the first stage of the upgrade: https://github.com/magento/magento2/issues/33707

Fixed warnings:
```
There were 9 warnings:

1) Magento\Customer\Test\Unit\Model\Plugin\SaveCustomerGroupExcludedWebsiteTest::testAfterSaveWithExcludedWebsitesChanged with data set #0 (array('2'), array(1, 2), 2)
Method save may not return value of type Mock_GroupExcludedWebsite_e685e2ac, its return declaration is "Magento\Customer\Api\Data\GroupExcludedWebsiteInterface"

2) Magento\Customer\Test\Unit\Model\Plugin\SaveCustomerGroupExcludedWebsiteTest::testAfterSaveWithExcludedWebsitesChanged with data set #1 (array(), array(1, 2), 2)
Method save may not return value of type Mock_GroupExcludedWebsite_e685e2ac, its return declaration is "Magento\Customer\Api\Data\GroupExcludedWebsiteInterface"

3) Magento\Customer\Test\Unit\Model\Plugin\SaveCustomerGroupExcludedWebsiteTest::testAfterSaveWithExcludedWebsitesChanged with data set #2 (array(2), array(1, 2), 2)
Method save may not return value of type Mock_GroupExcludedWebsite_e685e2ac, its return declaration is "Magento\Customer\Api\Data\GroupExcludedWebsiteInterface"

4) Magento\Customer\Test\Unit\Model\Plugin\SaveCustomerGroupExcludedWebsiteTest::testAfterSaveWithExcludedWebsitesChanged with data set #3 (array(1, 2), array(), 0)
Method save may not return value of type Mock_GroupExcludedWebsite_e685e2ac, its return declaration is "Magento\Customer\Api\Data\GroupExcludedWebsiteInterface"

5) Magento\Customer\Test\Unit\Model\Plugin\SaveCustomerGroupExcludedWebsiteTest::testAfterSaveWithExcludedWebsitesChanged with data set #4 (array(1, 2), array('1'), 1)
Method save may not return value of type Mock_GroupExcludedWebsite_e685e2ac, its return declaration is "Magento\Customer\Api\Data\GroupExcludedWebsiteInterface"

6) Magento\Customer\Test\Unit\Model\Plugin\SaveCustomerGroupExcludedWebsiteTest::testAfterSaveWithExcludedWebsitesChanged with data set #5 (array('1', 2, 3), array('2', 1), 2)
Method save may not return value of type Mock_GroupExcludedWebsite_e685e2ac, its return declaration is "Magento\Customer\Api\Data\GroupExcludedWebsiteInterface"

7) Magento\WeeeGraphQl\Test\Unit\Model\Resolver\FixedProductTaxResolverTest::testShouldReturnEmptyResult
Trying to configure method "getStore" which cannot be configured because it does not exist, has not been specified, is final, or is static

8) Magento\WeeeGraphQl\Test\Unit\Model\Resolver\FixedProductTaxResolverTest::testShouldReturnResult with data set #0 (1, array(array('FPT 2', array(0.5, 'USD')), array('FPT 1', array(1, 'USD')), array('FPT 2', array(1.5, 'USD'))))
Trying to configure method "getStore" which cannot be configured because it does not exist, has not been specified, is final, or is static

9) Magento\WeeeGraphQl\Test\Unit\Model\Resolver\FixedProductTaxResolverTest::testShouldReturnResult with data set #1 (2, array(array('FPT 2', array(0.55, 'USD')), array('FPT 1', array(1.1, 'USD')), array('FPT 2', array(1.65, 'USD'))))
Trying to configure method "getStore" which cannot be configured because it does not exist, has not been specified, is final, or is static
```

### Fixed Issues (if relevant)
1. Fixes magento/magento2#33708

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by bohdan-harniuk** [comment]
@magento run all tests

**Comment by bohdan-harniuk** [comment]
@magento run Functional EE Tests

**Comment by bohdan-harniuk** [comment]
@magento run Functional Tests EE

**Comment by bohdan-harniuk** [comment]
@magento run Functional Tests B2B

**Comment by Den4ik** [comment]
@bohdan-harniuk Could you please merge main line into PR

**Pull request merged**
