### PR TITLE
Added .DS_Store to .gitignore for Mac users

### PR DESCRIPTION
**Pull request by woutersamaey**
### Description
Added .DS_Store to .gitignore for Mac users

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by hostep** [comment]
Why not add it to your global git config instead of specifying this per project?
See: https://github.com/magento/magento2/issues/7608#issuecomment-263958286

**Comment by ishakhsuvarov** [comment]
@hostep I assume this may still be a nice addition for people who did not configure it globally and would not hurt anyone.

**Comment by hostep** [comment]
Ok, no problem, it can join all the phpstorm, netbeans, ... ignores.

(In my opinion, a .gitignore file should only ignore specific files to the project, if you want to ignore something based on your environment, like based on your OS, or which IDE you are using, you should put it in your global gitignore file).

But indeed, it won't hurt anyone, go ahead :)

**Comment by orlangur** [comment]
@hostep except it will hurt https://insight.sensiolabs.com/what-we-analyse check if we ever use one :)

**Pull request merged**
