### PR TITLE
Fix regression - Add previous exception with more details

### LINKED ISSUE #34166: [Issue] Fix regression - Add previous exception with more details
This issue is automatically created based on existing pull request: magento/magento2#33419: Fix regression - Add previous exception with more details

---------

### Description (*)

As part of https://github.com/magento/magento2/pull/32730, we got a regression - the 2nd parameter for the previous exception was lost. It was reported in https://github.com/magento/magento2/pull/32730#discussion_r618140599. 

This PR brings back this 2nd parameter, it will be really useful for a clear understanding of what's happened and why, when we catch an exception during email sending.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)

As part of https://github.com/magento/magento2/pull/32730, we got a regression - the 2nd parameter for the previous exception was lost. It was reported in https://github.com/magento/magento2/pull/32730#discussion_r618140599. 

This PR brings back this 2nd parameter, it will be really useful for a clear understanding of what's happened and why, when we catch an exception during email sending.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#34166: Fix regression - Add previous exception with more details

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Unit Tests

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9149](https://jira.corp.magento.com/browse/ENGCOM-9149) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-9149](https://jira.corp.magento.com/browse/ENGCOM-9149) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @ihor-sviziev , @Den4ik and @eduard13 
Thanks for the collaboration & contribution!

:x: QA not Passed

Required logs in case of Mailing exception

**Manual Scenario Steps**

1. Using a fresh Magento 2.4-develop sent a mail from the front end > Contact us; Noted the System.log, Exception.log and Debug.log from the var/log
2. Updated the line of code to throw the exception as defined in the [Description](https://github.com/magento/magento2/issues/23645#issue-466124266), and tried sending mail from the same _Contact us_ form.
3. Noted all the logs as like Step 1, and there was no additional logs. It is valid because - the PR fix not yet included.
4. Compiled the PR fix changes and upgraded.
5. Confirmed the updated line of code to throw the exception as defined in the [Description](https://github.com/magento/magento2/issues/23645#issue-466124266), and tried sending mail again from the same _Contact us_ form.
6. Tried to find the logs in all the log files relevant to it, and no additional logs found in the files at all.

**:heavy_check_mark: Expected result After Fix** 
- Expected additional logs relevant to the mailing exception


**:x: Actual result After Fix** 
- Found the error message as like shown in the below screenshot, but there is no logs relevant to it at all in any of the log files!
  image

**Comment by ihor-sviziev** [comment]
@engcom-Alfa,
Please add the following line `throw new \Magento\Framework\Exception\LocalizedException(__('test localized exception'));` before the
https://github.com/magento/magento2/blob/5d43aac4b0431250bc629e6a11f4d0671f8bd135/app/code/Magento/Email/Model/Transport.php#L102

**Comment by engcom-Alfa** [comment]
HI @ihor-sviziev 
1. Used a fresh Magento instance with smtp installed setup. Updated the code that you have mentioned in the [above-comment](https://github.com/magento/magento2/pull/33419#issuecomment-899433964).
2. Opened the Front end - Contact us form. Submitted the form but no exception received. Successfully sent the mail as shown in below screenshot.
image

This above case I tested before applying PR fix code! since I have to test that the fails before the fix to see exception logs and then the updated exception logs after the fix!

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Since this PR auto moved to Ready For Testing, pushing it back to Changes Requested!

**Comment by engcom-Charlie** [comment]
Hi @ihor-sviziev,

Thank you for your contribution!

I will have a look on the comments received in changes requested.

Thank you!

**Comment by engcom-Charlie** [comment]
Hi @ihor-sviziev, and @engcom-Alfa 

I have gone through this issue and [#32730](https://github.com/magento/magento2/pull/32730) issues and below are the findings.

@engcom-Alfa , I have tried to reproduce the issue on 2.4-develop branch having smtp installed and its reproducible.

To reproduce it, I have the added code base mentioned in [comment](https://github.com/magento/magento2/pull/33419#issuecomment-899433964). As a result, we can see error on store front, and  you will not see any exception entry in exception log.

image

In this issue implementation, we have taken care of passing the original exception as a second parameter along with an exception log entry. So as a part of testing of this issue, we should be getting the exception entry in exception log.

Thank you!

**Comment by engcom-Alfa** [comment]
> Hi @ihor-sviziev, and @engcom-Alfa
> 
> I have gone through this issue and [#32730](https://github.com/magento/magento2/pull/32730) issues and below are the findings.
> 
> @engcom-Alfa , I have tried to reproduce the issue on 2.4-develop branch having smtp installed and its reproducible.
> 
> To reproduce it, I have the added code base mentioned in [comment](https://github.com/magento/magento2/pull/33419#issuecomment-899433964). As a result, we can see error on store front, and you will not see any exception entry in exception log.
> 
> image
> 
> In this issue implementation, we have taken care of passing the original exception as a second parameter along with an exception log entry. So as a part of testing of this issue, we should be getting the exception entry in exception log.
> 
> Thank you!

After your updates, I gave a fresh try
Installed a new Magento instance without sample data, update the same line of code, tried to get the error by submitting the Contact-us form. But, successfully accepted the from! Strange!

**Comment by engcom-Alfa** [comment]
@magento create issue

**Pull request merged**
