### PR TITLE
MAGENTO NEED MORE COOKIE!!

### PR DESCRIPTION
**Pull request by kschroeder**
MAGENTO SWEET!!  LIKE COOKIE!!

```
                .---. .---. 
               :     : o   :    
           _..-:   o :     :-.._    
       .-''  '  `---' `---' "   ``-.    
     .'   "   '  "  .    "  . '  "  `.  
    :   '.---.,,.,...,.,.,.,..---.  ' ;
    `. " `.                     .' " .'
     `.  '`.                   .' ' .'
      `.    `-._           _.-' "  .'  .----.
        `. "    '"--...--"'  . ' .'  .'  o   `.a
        .'`-._'    " .     " _.-'`. :       o  :
  jgs .'      ```--.....--'''    ' `:_ o       :
    .'    "     '         "     "   ; `.;";";";'
   ;         '       "       '     . ; .' ; ; ;
  ;     '         '       '   "    .'      .-'
  '  "     "   '      "           "    _.-'
```
MAGENTO HAVE COOKIE!!  LIKE COOKIE MONSTER!!
```
               _  _
             _/0\/ \_
    .-.   .-` \_/\0/ '-.
   /:::\ / ,_________,  \
  /\:::/ \  '. (:::/  `'-;
  \ `-'`\ '._ `"'"'\__    \
   `'-.  \   `)-=-=(  `,   |
jgs    \  `-"`      `"-`   /
```
MAGENTO NEED COOKIE MONSTER!!

ME SUBSTITUTE PhpCookieManager WITH PhpCookieMonster BECAUSE MAGENTO NEED MORE COOKIE!!

April Fools y'all. :-)

### CODE REVIEW

**Comment by adragus-inviqa** [comment]
Can you please add some tests? Otherwise, LGTM.

**Comment by kschroeder** [comment]
@adragus-inviqa Cookie Monster never tested cookie before.  Cookie Monster only eat cookie.  Will try testing cookies but making no promises.

**Comment by Koc** [comment]
Om nom nom!
https://www.youtube.com/watch?v=_OKGUAbpj5k

**Comment by PieterCappelle** [comment]
😂

**Comment by okorshenko** [comment]
@kschroeder thank you for your contribution. We will consider renaming of this class in a future Magento releases ;)

**Comment by kschroeder** [comment]
This pull request closed?  Like oven door on cookie?

**Pull request closed without merging**
