### PR TITLE
#26989 MFTF: Use <magentoCron> for reindex

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Optimize Functional Tests performance by using `<magentoCron groups="index">` where applicable.
Replace `cache:flush` with `cache:flush config` where applicable.,

### Related Pull Requests
* https://github.com/magento/partners-magento2b2b/pull/53

### Fixed Issues (if relevant)
1. magento/magento2#26989

### Manual testing scenarios (*)
1. CI Functional Tests should pass in < 70 minutes

### Questions or comments
**Work In Progress** as I need to stabilise the CI.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

Failure not related to the scope of change, rather it's caused by other test running on the same instance:
image

**Comment by lbajsarowicz** [comment]
@magento run all tests

Rollback the huge changes and starting with little steps.

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests EE

image

Error not related to the change introduced.

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests EE, Integration Tests

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-7026](https://jira.corp.magento.com/browse/ENGCOM-7026) has been created to process this Pull Request

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-7026](https://jira.corp.magento.com/browse/ENGCOM-7026) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by sidolov** [comment]
@magento run all tests

**Pull request merged**
