### PR TITLE
Fixed issue #14550

### PR DESCRIPTION
**Pull request by geet07**
### Description (*)

Price Filter Issue in Search criteria not returning correct product #14550
### Fixed Issues (if relevant)

1. Fixes magento/magento2 #14550

### Manual testing scenarios (*)

Hit the products REST api using any client with searchCriteria Category id as 23 and price filter as price between $40 and $50 or between $70 and $80. Here is the URL that i built
rest/V1/products?searchCriteria[filter_groups][1][filters][0][field]=category_id&searchCriteria[filter_groups][1][filters][0][value]=23&searchCriteria[filter_groups][1][filters][0][condition_type]=eq&searchCriteria[filter_groups][2][filters][0][field]=price&searchCriteria[filter_groups][2][filters][0][value]=40&searchCriteria[filter_groups][2][filters][0][condition_type]=from&searchCriteria[filter_groups][3][filters][0][field]=price&searchCriteria[filter_groups][3][filters][0][value]=50&searchCriteria[filter_groups][3][filters][0][condition_type]=to&searchCriteria[filter_groups][2][filters][1][field]=price&searchCriteria[filter_groups][2][filters][1][value]=70&searchCriteria[filter_groups][2][filters][1][condition_type]=from&searchCriteria[filter_groups][3][filters][1][field]=price&searchCriteria[filter_groups][3][filters][1][value]=80&searchCriteria[filter_groups][3][filters][1][condition_type]=to

Check the response of the Call

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by geet07** [comment]
#dmcdindia2020

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the pull request @geet07 ! Can you please cover the fix by either integration or MFTF test

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Will help with the test.

**Comment by engcom-Hotel** [comment]
Hello @geet07.
Changes cause several fails at tests. Could you please check reports and update the solution.
Thank you.

**Comment by engcom-Hotel** [comment]
Hello @geet07.
The provided solution doesn't work (response still contains products with other prices).
Could you please let me know if you are going to continue working on this PR?
Thank you.

**Comment by engcom-Hotel** [comment]
Hello @geet07.
The created request gives the next search criteria:
```
"search_criteria": {
 "filter_groups": [
   {
     "filters": [
       {
         "field": "category_id",
         "value": "23",
         "condition_type": "eq"
       }
     ]
   },
   {
     "filters": [
       {
         "field": "price",
         "value": "40",
         "condition_type": "from"
       },
       {
         "field": "price",
         "value": "70",
         "condition_type": "from"
       }
     ]
   },
   {
     "filters": [
       {
         "field": "price",
         "value": "80",
         "condition_type": "to"
       },
       {
         "field": "price",
         "value": "50",
         "condition_type": "to"
       }
     ]
   }
 ]
}
```
Based on https://devdocs.magento.com/guides/v2.4/rest/performing-searches.html
_When constructing a search, keep the following in mind:
To perform a logical OR, specify multiple filters within a filter_groups.
To perform a logical AND, specify multiple filter_groups._
So, we are looking for products with prices bigger than 40 OR 70 AND less than 50 OR 80 (basically it means from 40 to 80).
The product with the price 69 is fine with such select and the functionality works as expected.
Selection of the two subfilters requires additional functionality which you can ask via feature request.
Thank you.

**Comment by gabrieldagama** [comment]
Closing this PR due to inactivity. This issue is a feature request and it would need to be discussed further in its implementation.

**Pull request closed without merging**
