### PR TITLE
Refactor / Cleanup: `use` section does not need leading backslash

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
`use` section does not actually need `\` at the beginning of the classpath (leading backslash)

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6504](https://jira.corp.magento.com/browse/ENGCOM-6504) has been created to process this Pull Request
:eight_spoked_asterisk: @dmytro-ch, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Charlie** [comment]
:heavy_check_mark: QA Passed

**Comment by ihor-sviziev** [comment]
Wasn't it enforced by static tests? If no - It's good idea to add it 
/CC @lenaorobei

**Comment by ihor-sviziev** [comment]
I just reported issue for coding standard https://github.com/magento/magento-coding-standard/issues/165

**Comment by orlangur** [comment]
@ihor-sviziev @lenaorobei such test should have been elaborated in the first place and only then changes merged. There is existing fix for `php-cs-fixer` doing this, I suppose it was used by PR author.

**Comment by lbajsarowicz** [comment]
Actually, I haven't used `php-cs-fixer` but I already spoke to @lenaorobei that I'm going to send her form time to time tool + config to get rid of the most common issues of code style that do not affect how code works. 

By this I mean - removing leading backslashes, incorrect annotations etc.

**Comment by orlangur** [comment]
@lbajsarowicz send where? Changes just applied and merged from time to time?

**Comment by lbajsarowicz** [comment]
@orlangur I want - from time to time - review what changes can be applied (the ones that we have already covered with automated static checks), and fix them automatically for whole Magento, not as a contribution.

**Comment by orlangur** [comment]
I see, then it sounds good as may be applied to ce/ee/b2b codebase all at once.

The right thing is actually forbid any coding standard violations and apply necessary changes together with any rule addition. I promoted such approach from the very beginning but wasn't heard and as a result poor processes were established and this is still not fixed.

**Comment by lbajsarowicz** [comment]
@orlangur So, let's do that together :  ) I believe that now, before 2.4 that would be a little bit easier

**Comment by orlangur** [comment]
Okiz. Let me aggregate my thoughts and older notes during this longer weekend and then I'll reach you out. @coderimus is in too.

**Pull request merged**
