### PR TITLE
Mark Various Modules interfaces as API

### LINKED ISSUE #32022: Mark Search, Security, Shipping, Store, Tax, Theme and Ui interfaces as API
The following interfaces should be marked as API in 2.4-develop branch

1. app/code/Magento/Search/Model/SearchEngine/ValidatorInterface.php
1. app/code/Magento/Search/Setup/InstallConfigInterface.php
1. app/code/Magento/Security/Api/Data/UserExpirationInterface.php
1. app/code/Magento/Shipping/Model/Carrier/Source/GenericInterface.php
1. app/code/Magento/Store/Model/Config/Importer/Processor/ProcessorInterface.php
1. app/code/Magento/Store/Model/StoreResolver/ReaderInterface.php
1. app/code/Magento/Store/Model/StoreSwitcher/ContextInterface.php
1. app/code/Magento/Store/Model/StoreSwitcher/RedirectDataInterface.php
1. app/code/Magento/Store/Model/StoreSwitcher/RedirectDataPostprocessorInterface.php
1. app/code/Magento/Store/Model/StoreSwitcher/RedirectDataPreprocessorInterface.php
1. app/code/Magento/Store/Model/StoreSwitcher/RedirectDataSerializerInterface.php
1. app/code/Magento/Store/Model/StoreSwitcherInterface.php
1. app/code/Magento/Tax/Api/TaxAddressManagerInterface.php
1. app/code/Magento/Tax/Model/System/Message/NotificationInterface.php
1. app/code/Magento/Tax/Model/TaxClass/Type/TypeInterface.php
1. app/code/Magento/Theme/Model/Design/Config/MetadataProviderInterface.php
1. app/code/Magento/Theme/Model/Theme/StoreThemesResolverInterface.php
1. app/code/Magento/Ui/Component/Form/Element/DataType/DataTypeInterface.php
1. app/code/Magento/Ui/Component/Layout/Tabs/TabInterface.php
1. app/code/Magento/Ui/Component/Wysiwyg/ConfigInterface.php
1. app/code/Magento/Ui/Config/Argument/ParserInterface.php
1. app/code/Magento/Ui/Config/ConverterInterface.php
1. app/code/Magento/Ui/Controller/UiActionInterface.php
1. app/code/Magento/Ui/DataProvider/AddFieldToCollectionInterface.php
1. app/code/Magento/Ui/DataProvider/AddFilterToCollectionInterface.php
1. app/code/Magento/Ui/DataProvider/Mapper/MapperInterface.php
1. app/code/Magento/Ui/DataProvider/Modifier/PoolInterface.php
1. app/code/Magento/Ui/Model/ColorPicker/ModeInterface.php
1. app/code/Magento/Ui/Model/UrlInput/ConfigInterface.php

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

The following interfaces marked as API

app/code/Magento/Search/Model/SearchEngine/ValidatorInterface.php
app/code/Magento/Search/Setup/InstallConfigInterface.php
app/code/Magento/Security/Api/Data/UserExpirationInterface.php
app/code/Magento/Shipping/Model/Carrier/Source/GenericInterface.php
app/code/Magento/Store/Model/Config/Importer/Processor/ProcessorInterface.php
app/code/Magento/Store/Model/StoreResolver/ReaderInterface.php
app/code/Magento/Store/Model/StoreSwitcher/ContextInterface.php
app/code/Magento/Store/Model/StoreSwitcher/RedirectDataInterface.php
app/code/Magento/Store/Model/StoreSwitcher/RedirectDataPostprocessorInterface.php
app/code/Magento/Store/Model/StoreSwitcher/RedirectDataPreprocessorInterface.php
app/code/Magento/Store/Model/StoreSwitcher/RedirectDataSerializerInterface.php
app/code/Magento/Store/Model/StoreSwitcherInterface.php
app/code/Magento/Tax/Api/TaxAddressManagerInterface.php
app/code/Magento/Tax/Model/System/Message/NotificationInterface.php
app/code/Magento/Tax/Model/TaxClass/Type/TypeInterface.php
app/code/Magento/Theme/Model/Design/Config/MetadataProviderInterface.php
app/code/Magento/Theme/Model/Theme/StoreThemesResolverInterface.php
app/code/Magento/Ui/Component/Form/Element/DataType/DataTypeInterface.php
app/code/Magento/Ui/Component/Layout/Tabs/TabInterface.php
app/code/Magento/Ui/Component/Wysiwyg/ConfigInterface.php
app/code/Magento/Ui/Config/Argument/ParserInterface.php
app/code/Magento/Ui/Config/ConverterInterface.php
app/code/Magento/Ui/Controller/UiActionInterface.php
app/code/Magento/Ui/DataProvider/AddFieldToCollectionInterface.php
app/code/Magento/Ui/DataProvider/AddFilterToCollectionInterface.php
app/code/Magento/Ui/DataProvider/Mapper/MapperInterface.php
app/code/Magento/Ui/DataProvider/Modifier/PoolInterface.php
app/code/Magento/Ui/Model/ColorPicker/ModeInterface.php
app/code/Magento/Ui/Model/UrlInput/ConfigInterface.php

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32022

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
rebased 2.5-develop branch

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B

**Comment by mrtuvn** [comment]
Should add strict_types

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8820](https://jira.corp.magento.com/browse/ENGCOM-8820) has been created to process this Pull Request

**Comment by mrtuvn** [comment]
Re-targeted PR branch to 2.4-develop as internal discussed with @gabrieldagama

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE, Integration Tests

**Comment by mrtuvn** [comment]
@magento run Integration Tests

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama the branch with code successfully imported into`magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-32152`.

**Pull request merged**
