### PR TITLE
Fix image order when 10+ images on dropdown configurable products

### LINKED ISSUE #37285: [Issue] Fix image order when 10+ images on dropdown configurable products
This issue is automatically created based on existing pull request: magento/magento2#37282: Fix image order when 10+ images on dropdown configurable products

---------

### Description (*)

This PR fixes an images order, which was described mostly in this issue https://github.com/magento/magento2/issues/22249 and fixed in this commit https://github.com/magento/magento2/commit/700a1535cb6f58224e8e302ad1b4556d8a118e01

The same issue appears for products using the Dropdown attribute types (not swatches)

### Related Pull Requests

- https://github.com/magento/magento2/pull/22287

### Manual testing scenarios (*)

1. Install Magento with sample data
2. Update 2 attributes color and size to use Dropdown as "Catalog Input Type for Store Owner"
3. Upload more than 10 images to `WJ12-XS-Blue` product
4. On configurable product page that images should have correct order

### Questions or comments

Does it need new issue?

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [X] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by lumnn**
### Description (*)

This PR fixes an images order, which was described mostly in this issue https://github.com/magento/magento2/issues/22249 and fixed in this commit https://github.com/magento/magento2/commit/700a1535cb6f58224e8e302ad1b4556d8a118e01

The same issue appears for products using the Dropdown attribute types (not swatches)

### Related Pull Requests

- https://github.com/magento/magento2/pull/22287

### Manual testing scenarios (*)

1. Install Magento with sample data
2. Update 2 attributes color and size to use Dropdown as "Catalog Input Type for Store Owner"
3. Upload more than 10 images to `WJ12-XS-Blue` product
4. On configurable product page that images should have correct order

### Questions or comments

Does it need new issue?

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [X] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37285: Fix image order when 10+ images on dropdown configurable products

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Review by Den4ik — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B ,Functional Tests CE,Functional Tests EE ,Unit Tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

- Install Magento with sample data
- Update 2 attributes color and size to use Dropdown as "Catalog Input Type for Store Owner"
- Upload more than 10 images to WJ12-XS-Blue product
- On configurable product page that images should have correct order

**Before:** :heavy_multiplication_x: Images were not in correct order.
Screenshot 2023-03-24 at 12 47 47 PM

**Frontend:**
Screenshot 2023-03-24 at 12 49 38 PM


**After:** :heavy_check_mark:  Now, it is correct.

Screenshot 2023-03-24 at 1 03 50 PM

Screenshot 2023-03-24 at 1 12 12 PM


Builds are failing. Hence. moving this PR to **Extended Testing**

**Comment by engcom-Charlie** [comment]
It seems that bot moved it to Ready for Testing hence pulling it back to Extended testing.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
As all tests are passed, moving it to Merge in Progress now.

Thank you!

**Pull request merged**
