### PR TITLE
#26206 Add information about currently reindexed index.

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Answers the need for more information about failed reindex.

ezgif-7-84cd063d47d7

Change additionally improves performance by replacing `foreach() { array_merge() }` with `array_merge(...$args)`. Additionally with `-v` debug information included about exception trace.

### Fixed Issues (if relevant)
1. magento/magento2#26206 Missing information about the currently reindexed index on failure

### Manual testing scenarios (*)

1. Run desired reindex. Expect the reindex name to be immediately visible

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
Clean `2.4-develop` also fails the same test for me. Rolling back my changes to see if it's issue related with `2.4-develop` itself, or can I fix that.

The integration test is - in general - useless, written wrong way, so I'm not sure about it's corectness.

**Comment by lbajsarowicz** [comment]
https://github.com/magento/magento2/pull/26225 Has to be merged first (!).
↑ is already merged to this feature branch, to pass the Integration and Functional Tests.

**Review by pmclain — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @pmclain, thank you for the review.
[ENGCOM-6533](https://jira.corp.magento.com/browse/ENGCOM-6533) has been created to process this Pull Request
:eight_spoked_asterisk: @pmclain, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
