### PR TITLE
13254 configurable products are not saving with multiple associate products

### PR DESCRIPTION
**Pull request by AlexandrKozyr**
### Description

A pull request changes a way array of configurable_attributes_data for configurable product saving action is sent to the server. After changes, this array is json_encoded in order not to create redundant params for the request. The unit test also is fixed to match new format.

### Fixed Issues (if relevant)

1. magento/magento2#13254: Configurable products are not saving with multiple associate products 

### Manual testing scenarios

1. Saving a configurable product with 1000 simple product variations with 7 attributes

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=17992) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @AlexandrKozyr. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by aleron75 — CHANGES_REQUESTED** [review]
I see that this class uses native PHP JSON functions.

I would suggest taking the chance to inject and use ~~`\Magento\Framework\Json\EncoderInterface` and `\Magento\Framework\Json\DecoderInterface` wrappers~~ `\Magento\Framework\Serialize\Serializer\Json` instead of native `json_encode` and `json_decode`. Thanks!

**Comment by aleron75** [comment]
Hi @AlexandrKozyr, just a ping to consider applying the changes I suggested.
Thanks

**Review by dmanners — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmanners, thank you for the review.
[ENGCOM-3255](https://jira.corp.magento.com/browse/ENGCOM-3255) has been created to process this Pull Request

**Comment by sidolov** [comment]
Hi @AlexandrKozyr , we found the issue with the proposed solution: 

**Manual testing scenario:**

1. Create 7 drop-down attributes with 15 values each. The scope of the attributes set to Global.
2. Add those attributes to the Default attribute set.
3. Create 16 simple products in the way that each of them has the following characteristics:
4.  Set some value for each of those 7 attributes (there is no attribute with an empty value).
5. There is no such other product that at least one of its attributes has the same value as the corresponding attribute of the current product.
6. Start to create a configurable product.
7. When creating the configuration select those 7 attributes for it and check only one value per each attribute when selecting values.
8. Generate the configuration. There should be generated one variation.
9. Now when `Add Products Manually` option is available - remove newly created variation and add manually 16 earlier created products.
10. Click save.

**Actual result:**
Fatal error is shown. Looks like a lot of memory tried to allocate with current changes.

**Comment by sidolov** [comment]
Hi @AlexandrKozyr , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
