### PR TITLE
Removed $this->setShowGlobalIcon();

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

Is there any usage of `$this->setShowGlobalIcon()`?

I could not find any place where the vaule is used. In M1 there are some more files with this code, but it also seems unused.

### Fixed Issues (if relevant)

1. n/a

### Manual testing scenarios (*)

1. n/a

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @sreichel. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3512](https://jira.corp.magento.com/browse/ENGCOM-3512) has been created to process this Pull Request

**Comment by orlangur** [comment]
@sreichel please consider removal of logic related to `columnCountLayoutDepend` also. Was never used in M2 but never removed as well.

**Comment by sreichel** [comment]
@orlangur yes, i can remove it. I'll update PR later.

**Comment by sivaschenko** [comment]
@sreichel can you please remove the new commit and add it to a separate pull request as the first one is already in delivery stage

**Comment by sivaschenko** [comment]
I don't think the pull request will be marked as merged if it will have extra commits, I think it's better to revert the branch to after the first commit and force push

**Comment by sreichel** [comment]
@sivaschenko I tried to help but its starting to waste time. There are a lot of PRs with multiple commits -  e.g. all with failed tests. And `push force` just to make it look clean?

**Comment by sidolov** [comment]
Hi @sreichel , recently we delivered commit ba006c02d3bc7dc0dc71553c991f66b6364f138d to the 2.3-develop branch, other two commits were skipped because you pushed them right before the merge. Looks like this commits are not related to current PR and should be removed. After the force push your PR will be merged and closed

**Comment by sreichel** [comment]
@sidolov

> Looks like this commits are not related to current PR and should be removed.

Not related to the initial commit, but to orlangurs request .... thought i should add it here ...

**Pull request closed without merging**
