### PR TITLE
12183 Fixed Configurable Product's normal price is not visible on Product Catalog

### PR DESCRIPTION
**Pull request by krnshah**
### Description (*)

Fixed Configurable Product's normal price is not visible on Product Catalog
### Fixed Issues (if relevant)

1. magento/magento2#12183: Fixed Configurable Product's normal price is not visible on Product Catalog

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18883) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @krnshah. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3309](https://jira.corp.magento.com/browse/ENGCOM-3309) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@krnshah thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VladimirZaets** [comment]
Hi @krnshah, thanks for collaboration. We tried to apply your fix, but regular price for products still not showing.

**Comment by VladimirZaets** [comment]
Hi @krnshah , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Comment by krnshah** [comment]
Hi @VladimirZaets 

Step to reproduce the bug : 

-- Create configurable product and assign 2 or 3 simple products. 
-- Set special price to the simple product. that lowest special price from configurable product should be shown in product listing page as **As low as** price and there should be shown **regular price** of that same product as well (you can see the simple product).

-- Expected result : 


-- Actual result : 
screenshot-10 16 16 93-2018 11 24-11-12-51

**Comment by krnshah** [comment]
As per the PR i have changed in app/code/Magento/ConfigurableProduct/view/base/templates/product/price/final_price.phtml this file.
-- There is one condition to check **isProductList** from product data. and it will set false statically so i have remove that condition (we dont need to check that condition for configurable product).
-- And set the value of **is_product_list** in an array so this will achieve our expected result.

**Comment by sidolov** [comment]
Hi @krnshah , changeset for current PR does not contain any changes.
I'm closing this PR right now. Please, update the branch and reopen it if you wish to continue. 
Thank you!

**Comment by ghost** [comment]
Hi @krnshah, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+magento2+18883), it will take less than a minute. </br>Your feedback will help us to improve contribution process.

**Pull request closed without merging**
