### PR TITLE
ISSUE#21446: Removed unnecessary files to move them to Magento Commerce

### LINKED ISSUE #21446: Community themes contain resources for Commerce edition modules
### Summary (*)

The three standard themes have several folders which reference modules that do not exist in Community edition.  They mostly contain `_module.less` files and this leads to unused style rules in the deployed CSS.  Also it's a little bit annoying.

### Examples (*)

The following folders are superfluous:

    adminhtml/Magento/backend/Magento_AdvancedCheckout
    adminhtml/Magento/backend/Magento_Banner
    adminhtml/Magento/backend/Magento_CatalogPermissions
    adminhtml/Magento/backend/Magento_CustomerBalance
    adminhtml/Magento/backend/Magento_GiftCard
    adminhtml/Magento/backend/Magento_GiftRegistry
    adminhtml/Magento/backend/Magento_GiftWrapping
    adminhtml/Magento/backend/Magento_Reward
    adminhtml/Magento/backend/Magento_Rma
    adminhtml/Magento/backend/Magento_VersionsCms
    adminhtml/Magento/backend/Magento_VisualMerchandiser
    frontend/Magento/black/Magento_AdvancedCheckout
    frontend/Magento/black/Magento_Banner
    frontend/Magento/black/Magento_CatalogEvent
    frontend/Magento/black/Magento_GiftCard
    frontend/Magento/black/Magento_GiftCardAccount
    frontend/Magento/black/Magento_GiftRegistry
    frontend/Magento/black/Magento_GiftWrapping
    frontend/Magento/black/Magento_Invitation
    frontend/Magento/black/Magento_MultipleWishlist
    frontend/Magento/black/Magento_Rma
    frontend/Magento/black/Magento_VersionsCms
    frontend/Magento/luma/Magento_AdvancedCheckout
    frontend/Magento/luma/Magento_CustomerBalance
    frontend/Magento/luma/Magento_GiftCard
    frontend/Magento/luma/Magento_GiftCardAccount
    frontend/Magento/luma/Magento_GiftWrapping
    frontend/Magento/luma/Magento_Invitation
    frontend/Magento/luma/Magento_MultipleWishlist
    frontend/Magento/luma/Magento_Reward
    frontend/Magento/luma/Magento_Rma

### Proposed solution

Move the mentioned resources to the appropriate theme or the modules' own `view` folders.

### PR DESCRIPTION
**Pull request by andrewbess**
### Description (*)

This PR partially fixes the issue#21446. It removes the `less` files of the `adminhtml` area and some `less` files from `frontend` area (that haven't been separated for different frontend themes) to move them to Magento Commerce

### Related Pull Requests

https://github.com/magento/partners-magento2ee/pull/173

### Fixed Issues (if relevant)

1. Fixes magento/magento2#21446: Community themes contain resources for Commerce edition modules

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
Hi @slavvka @lenaorobei ,
Could you help to understand why static test fails?

**Comment by slavvka** [comment]
@ihor-sviziev 
```
01:43:04 1) Magento\Test\Less\LiveCodeTest::testCodeStyle
01:43:04 Magento\Framework\Exception\LocalizedException: The following patterns didn't return any result:
01:43:04 app/design/adminhtml/Magento/backend/Magento_GiftRegistry/web/css/source/_module-old.less
01:43:04 
01:43:04 /var/www/html/lib/internal/Magento/Framework/App/Utility/Files.php:1617
01:43:04 /var/www/html/dev/tests/static/testsuite/Magento/Test/Less/LiveCodeTest.php:76
01:43:04 /var/www/html/dev/tests/static/testsuite/Magento/Test/Less/LiveCodeTest.php:57
```

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @andrewbess,
Could you investigate why static test fails and adjust your PR or test itself? As for me message isn't clear at all, but definitely there should be some meaning behind that failure.

Thank you!

**Comment by ihor-sviziev** [comment]
Hi @andrewbess,
Will you be able to update your PR?

**Comment by ihor-sviziev** [comment]
@andrewbess  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @andrewbess,
Unfortunately static tests still fails, please review and fix them

**Comment by ihor-sviziev** [comment]
I think this change could break some functionality related to ee / b2b, so added milestone 2.5.

**Comment by ihor-sviziev** [comment]
@andrewbess will you be able to update your PR?

**Comment by ihor-sviziev** [comment]
@andrewbess I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by friendscottn** [comment]
This issue probably shouldn't be closed, but if you arrived here like me because you working on performance and removing unused css, take a look at this related issue #24666. If the issue has not be resolved in your version of Magento there's a [patch](https://github.com/vasilii-b/magento2-frontend-improvements) to fix the issue.

**Pull request closed without merging**
