### PR TITLE
Fixed issue 17403 Shipping information API validation.

### PR DESCRIPTION
**Pull request by vaibhavahalpara**
### Description

Shipping information API validation: Validate Shipping city, shipping firstname, shipping lastname, billing country, billing city, billing firstname, billing lastname

### Fixed Issues (if relevant)

1. magento/magento2#17403: shipping information API validation

### Manual testing scenarios

1. Generate cart using POST rest/V1/guest-carts
2. Add product to cart POST rest/V1/guest-carts/[cart-id]/items
    **REQUEST**
{ "cartItem": { "sku": "[sku]", "qty": 1, "quote_id": "[cart-id]" } }
3. Make a request to endpoint POST rest/V1/guest-carts/[:cart-id]/shipping-information
    **REQUEST**
`
{
  "addressInformation":{
     "shippingAddress":{
        "country_id":"IN",
        "region":"XYZ",
        "region_id":0,
          "street":["test"],
        "telephone":"99040503256",
          "postcode":"1234",
        "city":"",
        "firstname":"vaibhav",
        "lastname":"ahalpara",
        "middlename":""
     },
     "billingAddress":{
        "country_id":"IN",
        "region":"XYZ",
        "region_id":0,
          "street":["test"],
        "telephone":"99040503256",
          "postcode":"1234",
        "city":"",
        "firstname":"vaibhav",
        "lastname":"ahalpara",
        "middlename":""
     },
    "shipping_method_code":"flatrate",
    "shipping_carrier_code":"flatrate"
  }
}
`
4. Change values to validate Country, City, Firstname, Lastname .
5. Code will change all required values.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=17534) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @vaibhavahalpara. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by vaibhavahalpara — COMMENTED** [review]
add street,postcode and telephone validation and add test script

**Review by vaibhavahalpara — COMMENTED** [review]
Fixed PSR-2 standard issues

**Review by vaibhavahalpara — COMMENTED** [review]
Define methods in shippingAddressMock

**Comment by magento-engcom-team** [comment]
@vaibhavahalpara thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by orlangur — CHANGES_REQUESTED** [review]
Nowadays all changes must be applied to `2.3-develop` first (see https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules). Please prepare a new pull request, this one should be `on hold` until the latter is merged.

**Comment by orlangur** [comment]
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

**Pull request closed without merging**
