### PR TITLE
Fixed  back redirect for view order from edit customer

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

fixed  back redirect for view order from edit customer
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: N/A

### Manual testing scenarios (*)

1. create new customer
2. place test order with test product
3. Admin -> Customers -> All Customers -> edit customer -> view  -> Orders
click on order to view it
now from view order click back

Expected result (*)
back redirect edit customer 

Actual result (*)
back redirect sales/order/index/

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ravi-chandra3197** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197, here is your [new Magento instance](https://pr-23882.instances.magento-community.engineering).
Admin access: [https://pr-23882.instances.magento-community.engineering/admin](https://pr-23882.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-5526](https://jira.corp.magento.com/browse/ENGCOM-5526) has been created to process this Pull Request
:eight_spoked_asterisk: @miguelbalparda, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
