### PR TITLE
#865: add getParams/setParam to RequestInterface

### PR DESCRIPTION
**Pull request by ashsmith**
As per issue #865, the getParams and setParams method is missing from the RequestInterface. Which are methods relied upon heavily in app/code/Magento/*.

### CODE REVIEW

**Comment by otoolec** [comment]
@ashsmith Thanks for providing this pull request.  In order for us to accept the PR we would need the Travis CI tests to pass though.  

* Can you fix the broken unit tests?  I've provided a fix for one of them as a PR to your branch.  Please identify other failing tests and provide similar fixes. 

* Can you modify all implementations of the RequestInterface to conform to the changes you've made?  For example the [Magento\Framework\App\Console\Request](https://github.com/magento/magento2/blob/8352a97e5bcb8610f18579c0b4528cdaeb95d188/lib/internal/Magento/Framework/App/Console/Request.php#L10) class needs to have the new methods added.

After making these changes, please make sure that there aren't any other issues identified by TravisCI.

**Comment by ashsmith** [comment]
Working on fixing the failing tests. Didn't realise quite how many would be affected by this change.

**Comment by ashsmith** [comment]
Okay, I've updated the tests. I'm getting one failure locally that I can debug where `Zend_Controller_Response_Http::__toString()` is throwing an exception when it isn't expected to, but not providing anything useful to help debug. Hoping it's just an env issue.

**Comment by otoolec** [comment]
@ashsmith I've resolved the merge conflicts that exist and am submitting an internal PR for your code.  This should allow us to accept your PR next week!

I didn't see any errors related to `Zend_Controller_Response_Http::__toString()` yet.  Can you describe the scenario where you saw them?  Was it from running unit tests locally?

**Comment by ashsmith** [comment]
@otoolec It was when running locally. I have a feeling it's to do with my local dev. I'll rebuild my vm tonight and run it again to be sure.

**Pull request merged**
