### PR TITLE
Fixed-20249: Added new pull request.Global select box arrow issue. wh…

### PR DESCRIPTION
**Pull request by suryakant-krish**
### Description (*)

Backend: Global select box arrow issue. when user select any option wrong arrow icon displayed.
### Fixed Issues (if relevant)

1. magento/magento2 #20249>: Backend: Global select box arrow issue. when user select any option wrong arrow icon displayed.

### Manual testing scenarios (*)

1. Login into admin panel > Content > Configuration > Select any theme > Click on applied theme > choose any other theme. Arrow direction is wrong.

Note: This change for global select box.

2. Actual Result.
actual

3. Expected Result.
expected

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20423) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=20423) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: suryakant-krish<br/>:x: smakawana

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-20423.instances.magento-community.engineering).
Admin access: [https://pr-20423.instances.magento-community.engineering/admin](https://pr-20423.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rogyar** [comment]
Hi @suryakant-krish. Thank you for your collaboration. Please note, after your change the entire dropbox (including the arrow direction) changes its state on hover. It's not correct behavior, the hover effect should stay the same.

**Comment by sidolov** [comment]
Hi @suryakant-krish , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
