### PR TITLE
Fixed issue of Google reCAPTCHA on contact form

### PR DESCRIPTION
**Pull request by hiren0241**
Fixed issue of Google reCAPTCHA : Sometimes reCAPTCHA doesn't display.

### Description (*)
This pull request resolved issue of Google reCaptcha doesn't display on contact form of magento2.
### Fixed Issues (if relevant)

1. magento/magento2#19618: Google reCAPTCHA : Sometimes reCAPTCHA doesn't display - hidden dependance

### Manual testing scenarios (*)
1. Disable Magento Captcha Module.
2. Captcha is display on contact form
3. Able to send contact form
4. Enable Magento Captcha Module
5. Captcha is display on contact form
6. Able to send contact form

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @hiren0241. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by hiren0241** [comment]
I am unable to reopen this PR. Can anybody help?

**Comment by hiren0241** [comment]
Hi @sidolov ,

I am unable to reopen this PR. Are you able to reopen it? Or cab you help me how can I do it?

**Comment by orlangur** [comment]
@hiren0241 it is not possible to reopen PR after branch is removed.

**Pull request closed without merging**
