### PR TITLE
[Forwardport] Responsive Design Footers bottom of screen on mobile devices #15118

### PR DESCRIPTION
**Pull request by vijay-wagento**
### Original Pull Request 
 https://github.com/magento/magento2/pull/15353
Solved footer issue for mobile view

### Description
Solved footer issue for mobile view

### Fixed Issues (if relevant)

1. magento/magento2#15118: Responsive Design, Footers do not snap to bottom of screen on mobile devices
2. ...

### Manual testing scenarios

1. Check footer in mobile

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15729) <br/>All committers have signed the CLA.

**Comment by VladimirZaets** [comment]
Hi @vijay-wagento. This fix has some problems. First of all, if page content will be less than 100% of page size that footer will not be on the bottom of the page.
Also if the page will contain some content in the bottom the content will be overlapped by footer and will never be visible.
The right way to fix it presented in [this](https://github.com/magento/magento2/pull/15471) PR

**Comment by vijay-wagento** [comment]
@VladimirZaets I created PR from the reference PR you have given using Porting tool.

**Comment by VladimirZaets** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, here is your [Magento instance](https://pr-15729.engcom.dev.magento.com).
Admin access: [https://pr-15729.engcom.dev.magento.com/admin](https://pr-15729.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Please make sure you are PR **author** or **assignee** to access the instance.

**Comment by VladimirZaets** [comment]
screen shot 2018-06-04 at 12 20 13

Our automation tool gived you reference to porting tool. In the Magento 2.3  version this fix provide new bug. I attached the screenshot.

**Comment by vijay-wagento** [comment]
Hello @VladimirZaets, Thanks we are looking into it.

**Comment by VladimirZaets** [comment]
@vijay-wagento, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Pull request closed without merging**
