### PR TITLE
#14971 Improper Handling of Pagination SEO

### PR DESCRIPTION
**Pull request by chickenland**
This PR removes the p= query string parameter when navigating to the first page - to avoid duplicate content SEO issues.

### Description (*)
First page pagination link include the pagination query string (for example p=1)  when on a later page - which causes a duplicate content SEO issue.

### Fixed Issues (if relevant) (*)
#14971: Improper Handling of Pagination SEO

### Manual testing scenarios (*)
* Visit a category with more than 1 page
* Use pagination to go to page 2
* Return to page 1 via pagination and verify that the pagination query string parameter is not present in the URL

### Manual testing scenarios (*)
* Visit a category with more than 1 page
* Use pagination to go to page 2
* Add a filter
* Return to page 1 via pagination and verify that the pagination query string parameter is not present in the URL, but the filter is

### CODE REVIEW

**Comment by slavvka** [comment]
@magento run all tests

**Comment by chickenland** [comment]
Looks like the code test is failing on the file I've altered, but not in a function I've changed code.

Shall I fix as part of this?

**Comment by krzksz** [comment]
Hey @chickenland, yes please fix the issues if possible.

**Review by krzksz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-6455](https://jira.corp.magento.com/browse/ENGCOM-6455) has been created to process this Pull Request
:eight_spoked_asterisk: @krzksz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @chickenland .
     Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by auto test.
Thanks!

**Comment by engcom-Golf** [comment]
I will take care of test coverage

**Comment by engcom-Golf** [comment]
Hi @krzksz all changes covered by unit test could you please review ?

**Review by krzksz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-6455](https://jira.corp.magento.com/browse/ENGCOM-6455) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
