### PR TITLE
Fix bug missed products with reindex catalog_category_product

### PR DESCRIPTION
**Pull request by raumatbel**
### Description

Products are missed in the table **catalog_category_product_index** when you run reindex **catalog_category_product**

### Fixed Issues (if relevant)

1. magento/magento2#8018: Running indexer:reindex catalog_category_product fails due to limit 500

### Manual testing scenarios

1. Create multiple child categories with each other
2. Assign about 500 or 600 products to the smallest child category
3. Run **bin/magento indexer:reindex catalog_category_product**
4. In the table **catalog_category_product_index** a lot of products are been missed and in the frontend these are not visible.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=10974) <br/>All committers have signed the CLA.

**Comment by orlangur** [comment]
This is obviously not a proper fix.

Are you able to reproduce mentioned issue on `develop`? Looks like it was fixed in https://github.com/magento/magento2/search?q=MAGETWO-62616&type=Commits&utf8=✓ and/or https://github.com/magento/magento2/search?q=MAGETWO-63601&type=Commits&utf8=✓

**Comment by orlangur** [comment]
@raumatbel are you going to proceed with checking issue on `develop` and then, maybe, backporting of a proper fix?

**Comment by raumatbel** [comment]
@orlangur I'm going to check this ticket in this branch with multiple categories and products. When I have feedback I will notify you

**Comment by raumatbel** [comment]
@orlangur I am going to close this PR because I have done commits of the other issues in this PR. I will create one new. Thanks

**Pull request closed without merging**
