### PR TITLE
Fix widget recent view product not fit in mobile view

### LINKED ISSUE #27058: Recently viewed products in Luma theme does not fit on screen
Using the "recently viewed products" widget on mobile will break the viewport and forcing sidescrolling.

The problem is even worse when using translated "add to cart" that make the button longer.

### Preconditions (*)

1. Magento 2.3.3
2. Luma theme
3. Mobile view

### Steps to reproduce (*)

1. Add a new widget for "Recently viewed products"
2 .Select Layout update "All pages" and container "Sidebar Main"
3. Visit some products in mobile view until the widget appears in mobile view

### Expected result (*)

Each product should wrap on a new line to fit the add to cart button, not be on a 2x grid.

### Actual result (*)

The add to cart goes outside the viewport, and the images overlap the previous product.

image

If you have a language with longer text than "add to cart" the effect will be worse:

image

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Fix for widget recent view product fit again in mobile view

### Fixed Issues (if relevant)

1. Fixes magento/magento2#27058: Recently viewed products in Luma theme does not fit on screen

### Manual testing scenarios (*)

1. Magento 2.3.4+ with sampledata 
2. Theme blank or luma
3. Add a new widget for "Recently viewed products"
4. Select Layout update "All pages" and container "Sidebar Main"
5. View some product in frontend
6. Visit some products in mobile view until the widget appears in mobile view

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by edenduong — CHANGES_REQUESTED** [review]
Hi @mrtuvn, thank you for your contribution.
Could you please check the fail static test?

image

**Comment by mrtuvn** [comment]
Fixed code styles follow less magento standards

**Review by edenduong — APPROVED** [review]
Thank you !

**Comment by magento-engcom-team** [comment]
Hi @edenduong, thank you for the review.
[ENGCOM-7264](https://jira.corp.magento.com/browse/ENGCOM-7264) has been created to process this Pull Request

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @edenduong 
Could you review the latest changes?
Thanks!

**Review by edenduong — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @edenduong, thank you for the review.
[ENGCOM-7264](https://jira.corp.magento.com/browse/ENGCOM-7264) has been created to process this Pull Request

**Review by ptylek — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-7264](https://jira.corp.magento.com/browse/ENGCOM-7264) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:**
_luma_
widget4

_blank_
widget3

**After:**
_luma_
widget1

_blank_
widget2

**Pull request merged**
