### PR TITLE
Refactor of 'Around' plugins 

### LINKED ISSUE #31443: [Issue] Refactor of 'Around' plugins
This issue is automatically created based on existing pull request: magento/magento2#31360: Refactor of 'Around' plugins 

---------

### Description (*)
Several minor updates to `around` plugins in Magento, introduced during the review of the existing plugins (looking for invalid uses for around plugins)

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Several minor updates to `around` plugins in Magento, introduced during the review of the existing plugins (looking for invalid uses for around plugins)

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31443: Refactor of 'Around' plugins

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Review by orlangur — APPROVED** [review]
Nice @lbajsarowicz !

Broken functional tests do not seem to be related to changes introduced in PR.

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-8555](https://jira.corp.magento.com/browse/ENGCOM-8555) has been created to process this Pull Request
:eight_spoked_asterisk: @orlangur, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by sidolov** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@lbajsarowicz @orlangur 
Thanks for the collaboration & contribution!


:heavy_check_mark: QA Passed
Refactor of 'Around' plugins

**Manual Scenario Steps**
1. Verified all minor changes and also tested using create configurable product from admin .


**After:** :heavy_check_mark: 
Configurable product created from backend.
image


There are some build failures hence moving to `Extended Testing`

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Failing Functional Tests B2B are different on same commit. On last two run different test are failing.

Run1
image

Run2
image


Hence Moving to `Merge In Progress`

**Pull request merged**
