### PR TITLE
[32058][To 2.4-develop] Marked classes and interfaces as API part 3

### LINKED ISSUE #32058: Mark classes and interfaces as API part 3
The following classes and interfaces should be marked as API in 2.4-develop branch

1. Magento\Framework\Data\Form\Element\Image	
1. Magento\Sales\Model\Order\Pdf\Total\DefaultTotal	
1. Magento\Catalog\Block\Adminhtml\Product\Edit\Button\Generic	
1. Magento\Sales\Controller\Adminhtml\Order	
1. Magento\Customer\Setup\CustomerSetup	
1. Magento\Checkout\Controller\Cart
1. Magento\Quote\Model\Quote\Item\CartItemOptionsProcessor

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixes #32058

### Related Pull Requests

https://github.com/magento/magento2/pull/32185
### Fixed Issues (if relevant)

1. Fixes magento/magento2#32058>

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by danielrussob** [comment]
@magento run Functional Tests EE

**Comment by danielrussob** [comment]
@magento run Unit Tests

**Comment by danielrussob** [comment]
I confirm that this PR is just a code cleanup / marked as API some class. We are waiting for tests.

**Comment by danielrussob** [comment]
I confirm that all files mentioned in issue (https://github.com/magento/magento2/issues/32058) are covered

**Comment by Usik2203** [comment]
Hi @aleron75  @danielrussob 
Thank you for review . 
I have only one doubts about label `Cleanup` 
I am not sure that PRs which related with `API Changes` project should have `Cleanup` label. 
I do this conclusion due to 
1. API Changes issues have **P1** priority 
2. We already have examples where such type PRs were merged and were not considered as `Cleanup` .

@sivaschenko @gabrieldagama Could i kindly ask you to clarify should such type of PRs have `Cleanup` label or should be understood as an improvement ? 

Thanks !

**Comment by aleron75** [comment]
Good point @Usik2203, let's see what others say. Thank you

**Comment by sivaschenko** [comment]
I would agree with @Usik2203 .

Cleanup PRs are usually PRs that have little to no impact on functionality and developer experience. API Changes PRs do introduce a big change of developer experience, so I wouldn't mark them as a cleanup.

**Comment by danielrussob** [comment]
Unit tests are fake positive @sivaschenko can you confirm, please?

**Comment by danielrussob** [comment]
This failing test is fake positive

**Review by danielrussob — APPROVED** [review]

**Comment by gabrieldagama** [comment]
@magento run Unit Tests

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama the branch with code successfully imported into`magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-32735`.

**Pull request merged**
