### PR TITLE
Migrate ZF2 components to Laminas components

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
This PR do following:
- replaces all \Zend\\* dependencies to \Laminas\\* (executed following instruction https://docs.laminas.dev/migration/)
- Adds laminas/laminas-zendframework-bridge in order to have backward compatibility, so Magento will still be able to load \Zend\\ classes

### Fixed Issues (if relevant)

1. https://github.com/magento/community-features/issues/229
2. https://github.com/magento/magento2/issues/26335

### Manual testing scenarios (*)
1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, here is your [new Magento instance](https://pr-26436.instances.magento-community.engineering).
Admin access: [https://pr-26436.instances.magento-community.engineering/admin_70c4](https://pr-26436.instances.magento-community.engineering/admin_70c4)
Login: `110b697e` Password: `f88aec94b9f0`
Instance will be terminated in up to 3 hours.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@ihor-sviziev, Most of failures are because of "absence" of `\Laminas\Stdlib\Glob` class. Please try to resolve the issue and rerun the tests.

**Comment by ihor-sviziev** [comment]
Current status is following:
All tests for magento Open source were passing (until there merge conflict appeared).
@lenaorobei contacted me in Slack and said that @fascinosum from internal team is working on the same thing and currently there is two options that under discussion:
1. Replace all zend namespaces with Laminas and add laminas to zend framework bridge (that what I did and this is the most backward compatible change should be)
2. Just replace namespaces without adding bridge

From my perspective it’s better to do 1st option as it should not break custom extensions, hovered it should break even b2b and EE versions, but it is due to test failures

**Comment by lenaorobei** [comment]
Hi @ihor-sviziev,
Internal team finished upgrade in `2.3-develop` branch and `2.4-develop` in on the way. As we discussed previously @fascinosum will contact you if any change is required. Thank you.

**Comment by ihor-sviziev** [comment]
@lenaorobei thx for update!

**Comment by diazwatson** [comment]
Guys what is the status of this?

**Comment by ihor-sviziev** [comment]
@diazwatson 
@lenaorobei said me some time ago that my changes were merged to internal branch and will be merged soon. But looks like it still didn’t happen

**Comment by diazwatson** [comment]
I was about to open an issue to look at this today and then I realised you were already working on this.
Lets see what the guys say 🤞

**Comment by fascinosum** [comment]
hello @ihor-sviziev, @diazwatson 
this community contribution is part of the implementation of migration ZF2 components to Laminas. 
Internal ticket is in progress (MC-13825).
Thank you for contribution and your participation

**Comment by eduard13** [comment]
Just leaving it here for the history.
While trying to install the latest dependencies, was getting the following issue:
> Installing laminas/laminas-dependency-plugin (1.0.3): Loading from cache
PHP Fatal error:  Uncaught Error: Undefined class constant ‘PRE_COMMAND_RUN’ in /home/dev/sites/mage23/vendor/laminas/laminas-dependency-plugin/src/DependencyRewriterPlugin.php:63

So, if you also face this one, try to upgrade the composer version using `composer self-update`, it should help.
Thanks.

**Comment by diazwatson** [comment]
Thanks for sharing it @eduard13

**Pull request merged**
