### PR TITLE
Updated system.xml

### PR DESCRIPTION
**Pull request by sanganinamrata**
### Description (*)

Updated system.xml regarding translation.

### Fixed Issues (if relevant)

N/A

### CODE REVIEW

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-6806](https://jira.corp.magento.com/browse/ENGCOM-6806) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @sanganinamrata. Thank you for your contribution.

Could you add label and comment values into the translation file?

Thanks!

**Comment by lenaorobei** [comment]
@sanganinamrata could you please address comment from @engcom-Alfa?

**Comment by lenaorobei** [comment]
Closing this PR due to inactivity. Please feel free to reopen if you are going to continue working on it.
Thank you.

**Pull request closed without merging**
