### PR TITLE
Pass custom attributes to current link via XML

### LINKED ISSUE #38500: [Issue] Pass custom attributes to current link via XML
This issue is automatically created based on existing pull request: magento/magento2#30070: Pass custom attributes to current link via XML

---------
### Description (*)

Actualy we are able to add custom attributes for links in customer account navigation via XML for example:
```
    <referenceBlock name="customer-account-navigation-account-link">
        <arguments>
            <argument name="attributes" xsi:type="array">
                <item name="class" xsi:type="string">account-custom-class</item>
            </argument>
        </arguments>
    </referenceBlock>

```
But when `customer-account-navigation-account-link` is as current page in this case it is `https://sample.com/customer/account/` our custom attribute dosn't show because method `getAttributesHtml()` [isn't used for current link](https://github.com/magento/magento2/pull/30070/commits/526b9d7e3a070870047acb37aaaf7ccff93540d1).

For non-current link method `getAttributesHtml()` [is used](https://github.com/magento/magento2/blob/f476d89951f8abebede69fa84db77a49690ded3e/lib/internal/Magento/Framework/View/Element/Html/Link/Current.php#L151).

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by mattkrupnik**
### Description (*)

Actualy we are able to add custom attributes for links in customer account navigation via XML for example:
```
    <referenceBlock name="customer-account-navigation-account-link">
        <arguments>
            <argument name="attributes" xsi:type="array">
                <item name="class" xsi:type="string">account-custom-class</item>
            </argument>
        </arguments>
    </referenceBlock>

```
But when `customer-account-navigation-account-link` is as current page in this case it is `https://sample.com/customer/account/` our custom attribute dosn't show because method `getAttributesHtml()` [isn't used for current link](https://github.com/magento/magento2/pull/30070/commits/526b9d7e3a070870047acb37aaaf7ccff93540d1).

For non-current link method `getAttributesHtml()` [is used](https://github.com/magento/magento2/blob/f476d89951f8abebede69fa84db77a49690ded3e/lib/internal/Magento/Framework/View/Element/Html/Link/Current.php#L151).

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38500: Pass custom attributes to current link via XML

### CODE REVIEW

**Comment by mattkrupnik** [comment]
@magento run all tests

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @mattkrupnik. Thank you for your contribution. Could I ask you to extend the description slightly by adding information about what problem we are trying to solve, please? Also, you may add a note that the introduced approach [exists](https://github.com/magento/magento2/blob/f476d89951f8abebede69fa84db77a49690ded3e/lib/internal/Magento/Framework/View/Element/Html/Link/Current.php#L151) for a non-current link.

Also, please, take a look at the failing B2B Unit tests. It looks like there's an assertion that needs to be adjusted. 

Thank you!

**Review by sidolov — CHANGES_REQUESTED** [review]
@mattkrupnik please, sign Adobe CLA

**Comment by mattkrupnik** [comment]
@magento run Unit Tests

**Comment by rogyar** [comment]
@magento run Unit Tests

**Comment by rogyar** [comment]
@magento run all tests

**Comment by mattkrupnik** [comment]
> @mattkrupnik please, sign Adobe CLA

Can you approve? Your change request were realised.

**Comment by dudzio12** [comment]
@magento run all tests

**Comment by dudzio12** [comment]
@rogyar @sidolov Could you finish your review please?

**Review by dudzio12 — APPROVED** [review]
I think there is no logical point in skipping that for current link only

**Comment by mattkrupnik** [comment]
@magento run all tests

**Comment by mattkrupnik** [comment]
@rogyar @sidolov Could you finish your review please?

**Comment by mattkrupnik** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento create issue

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
Hi @mattkrupnik ,

Thanks for the collaboration & contribution!

✔️ QA Passed
Preconditions:

Install fresh Magento 2.4-develop
Steps to reproduce
As per the Description.
Before: ✖️ 
Screenshot 2024-09-13 at 6 45 19 PM

After: ✔️
Screenshot 2024-09-13 at 6 41 56 PM

Builds are failed. Hence, moving this PR to Extended Testing.

Thanks

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
Failing tests seem flaky and Jira tickets have been created for these flaky tests.

See Jira:
[Jira 1](https://jira.corp.adobe.com/browse/ACQE-6487)
[Jira 2](https://jira.corp.adobe.com/browse/ACQE-6492)

So moving it to a further status.

**Comment by engcom-Dash** [comment]
@magento run Functional Tests CE, Functional Tests CE

**Pull request merged**
