### PR TITLE
[32059] [To 2.4-develop] Update classes and interfaces and mark them as API part 3 

### LINKED ISSUE #32059: Update classes and interfaces part 3
Update the following classes and interfaces in 2.5-develop branch:

1. Magento\Checkout\Model\Type\Onepage	Create a new interface and move constants there. Current class must implement the new interface to maintain backward compatibility
1. Magento\Framework\Image\AdapterFactory	Change visibility of protected properties to private
1. Magento\Catalog\Model\Config	Change visibility of protected properties/methods to private
1. Magento\Customer\Model\CustomerRegistry	Change visibility of protected properties/methods to private 
1. Magento\Quote\Setup\QuoteSetup	Change visibility of protected properties/methods to private 
1. Magento\Ui\Component\Control\Container	Change visibility of createButton() method to private 
1. Magento\Catalog\Model\Layer\Filter\Item	Change visibility of protected properties/methods to private

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixes #32059
### Fixed Issues (if relevant)

1. Fixes magento/magento2#32059

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by danielrussob** [comment]
Hello @Usik2203 ,
files are different from https://github.com/magento/magento2/issues/32059 can you have a double check please?

**Comment by Usik2203** [comment]
> Hello @Usik2203 ,
> files are different from #32059 can you have a double check please?

Hi @danielrussob 
I  double checked .  Everything is ok for me 
Thanks

**Review by aleron75 — APPROVED** [review]
For QA: the semantic version checker correctly fails because there are intentional changes in the visibility of some methods and properties. 

Regarding the Functional tests:
- EE ones don't seem to have real failures
- B2B seems a flaky test

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-9022](https://jira.corp.magento.com/browse/ENGCOM-9022) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Foxtrot** [comment]
SVC failures should be approved.

**Comment by danielrussob** [comment]
Hello @Usik2203 ,
thank you for your contribution but according to guidelines you cannot change protected member to private in the same lane 2.4.x cause it's a breaking change

**Comment by Usik2203** [comment]
> Hello @Usik2203 ,
> thank you for your contribution but according to guidelines you cannot change protected member to private in the same lane 2.4.x cause it's a breaking change

Hi @danielrussob 
Thank you for review , 
These changes `(changing protected member to private)`  were requested in this issue https://github.com/magento/magento2/issues/32059

Also this PR should be target to 2.4-develop based on massages in Slack channel ` #api-changes-project `
<pre>
We have had some discussions internally and have made a decision, we will be splitting this project in 2 phases (or milestone if you prefer), these phases will be:
Mark all required classes/interfaces with @api tag
Perform the refactors that will actually impact code

Also, the first phase of this project will be delivered to 2.4-develop, not 2.5 anymore, the second phase is under discussion still

I will be reviewing all the issues and make sure we split these 2 types of work

After that, I would need your help to recreate these PRs to 2.4-develop, we likely will need to create a new branch from 2.4-develop, cherry pick your commits and create a new PR
</pre>

Based on this information I think that changes are corect 

cc @gabrieldagama

**Comment by danielrussob** [comment]
> > Hello @Usik2203 ,
> > thank you for your contribution but according to guidelines you cannot change protected member to private in the same lane 2.4.x cause it's a breaking change
> 
> Hi @danielrussob
> Thank you for review ,
> These changes `(changing protected member to private)` were requested in this issue #32059
> 
> Also this PR should be target to 2.4-develop based on massages in Slack channel `#api-changes-project`
> 
> We have had some discussions internally and have made a decision, we will be splitting this project in 2 phases (or milestone if you prefer), these phases will be:
> Mark all required classes/interfaces with @api tag
> Perform the refactors that will actually impact code
> 
> Also, the first phase of this project will be delivered to 2.4-develop, not 2.5 anymore, the second phase is under discussion still
> 
> I will be reviewing all the issues and make sure we split these 2 types of work
> 
> After that, I would need your help to recreate these PRs to 2.4-develop, we likely will need to create a new branch from 2.4-develop, cherry pick your commits and create a new PR
> Based on this information I think that changes are corect
> 
> cc @gabrieldagama

OK, waiting @gabrieldagama !

**Comment by gabrieldagama** [comment]
Hi @Usik2203 @danielrussob we already marked these classes as API on `api-changes-develop` branch, the changes to it's properties must be done on 2.5 release line.

**Pull request closed without merging**
