### PR TITLE
Prevent cross origin iframe content reading

### LINKED ISSUE #32264: [Issue] Prevent cross origin iframe content reading
This issue is automatically created based on existing pull request: magento/magento2#32244: Prevent cross origin iframe content reading

---------

### Description (*)

Issue described in https://github.com/magento/magento2/pull/8005, https://github.com/magento/magento2/pull/7914 will message like this reproducing randomly (shown as console error):
image
image

Seems like it's happening because domain checking only on the exact element, not on all listed

The message looks like this:
```
[2021-02-22 04:30:25] [ERROR] SecurityError: Blocked a frame with origin "https://example.com" from accessing a cross-origin frame.
ConsoleOutputHandler.show @ console-output-handler.min.js:2
(anonymous) @ logger.min.js:6
Logger.processOutput_ @ logger.min.js:6
Logger.log_ @ logger.min.js:3
Logger.error @ logger.min.js:3
(anonymous) @ page-cache.min.js:4
map @ jquery.min.js:35
contents @ page-cache.min.js:4
lookup @ page-cache.min.js:4
(anonymous) @ page-cache.min.js:4
each @ jquery.min.js:28
lookup @ page-cache.min.js:4
(anonymous) @ page-cache.min.js:4
each @ jquery.min.js:28
lookup @ page-cache.min.js:4
$.fn.comments @ page-cache.min.js:4
_create @ page-cache.min.js:6
(anonymous) @ widget.min.js:15
_createWidget @ widget.min.js:21
$.<computed>.<computed> @ widget.min.js:14
$.<computed>.<computed> @ widget.min.js:13
(anonymous) @ main.min.js:2
execCb @ require.min.js:112
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
defContext.require @ mixins.min.js:11
requirejs @ require.min.js:117
init @ main.min.js:1
(anonymous) @ main.min.js:6
_.each._.forEach @ underscore.min.js:7
(anonymous) @ main.min.js:5
apply @ main.min.js:5
fire @ jquery.min.js:212
add @ jquery.min.js:215
jQuery.fn.ready @ jquery.min.js:223
jQuery.fn.init @ jquery.min.js:200
jQuery.fn.init @ jquery-migrate.min.js:27
jQuery @ jquery.min.js:16
(anonymous) @ bootstrap.min.js:1
execCb @ require.min.js:112
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
(anonymous) @ require.min.js:66
(anonymous) @ require.min.js:11
(anonymous) @ mixins.min.js:8
execCb @ require.min.js:112
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
(anonymous) @ require.min.js:66
(anonymous) @ require.min.js:11
(anonymous) @ mixins.min.js:8
execCb @ require.min.js:112
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
(anonymous) @ require.min.js:66
(anonymous) @ require.min.js:11
(anonymous) @ mixins.min.js:8
execCb @ require.min.js:112
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:104
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
(anonymous) @ require.min.js:55
(anonymous) @ require.min.js:11
execCb @ require.min.js:112
check @ require.min.js:56
enable @ require.min.js:73
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
load @ mixins.min.js:8
(anonymous) @ require.min.js:71
(anonymous) @ require.min.js:11
on @ require.min.js:40
callPlugin @ require.min.js:61
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
load @ mixins.min.js:8
(anonymous) @ require.min.js:71
(anonymous) @ require.min.js:11
on @ require.min.js:40
callPlugin @ require.min.js:61
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
load @ mixins.min.js:8
(anonymous) @ require.min.js:71
(anonymous) @ require.min.js:11
on @ require.min.js:40
callPlugin @ require.min.js:61
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
configure @ require.min.js:86
requirejs @ require.min.js:116
req.config @ require.min.js:117
(anonymous) @ requirejs-config.min.js:1
(anonymous) @ requirejs-config.min.js:1
(anonymous) @ requirejs-config.min.js:2
Show 103 more frames

```

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Magento 2.3.6-p2
2. Add some iframe, browse website, you'll **randomly** see this error in the browser console

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)

Issue described in https://github.com/magento/magento2/pull/8005, https://github.com/magento/magento2/pull/7914 will message like this reproducing randomly (shown as console error):
image
image

Seems like it's happening because domain checking only on the exact element, not on all listed

The message looks like this:
```
[2021-02-22 04:30:25] [ERROR] SecurityError: Blocked a frame with origin "https://example.com" from accessing a cross-origin frame.
ConsoleOutputHandler.show @ console-output-handler.min.js:2
(anonymous) @ logger.min.js:6
Logger.processOutput_ @ logger.min.js:6
Logger.log_ @ logger.min.js:3
Logger.error @ logger.min.js:3
(anonymous) @ page-cache.min.js:4
map @ jquery.min.js:35
contents @ page-cache.min.js:4
lookup @ page-cache.min.js:4
(anonymous) @ page-cache.min.js:4
each @ jquery.min.js:28
lookup @ page-cache.min.js:4
(anonymous) @ page-cache.min.js:4
each @ jquery.min.js:28
lookup @ page-cache.min.js:4
$.fn.comments @ page-cache.min.js:4
_create @ page-cache.min.js:6
(anonymous) @ widget.min.js:15
_createWidget @ widget.min.js:21
$.<computed>.<computed> @ widget.min.js:14
$.<computed>.<computed> @ widget.min.js:13
(anonymous) @ main.min.js:2
execCb @ require.min.js:112
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
defContext.require @ mixins.min.js:11
requirejs @ require.min.js:117
init @ main.min.js:1
(anonymous) @ main.min.js:6
_.each._.forEach @ underscore.min.js:7
(anonymous) @ main.min.js:5
apply @ main.min.js:5
fire @ jquery.min.js:212
add @ jquery.min.js:215
jQuery.fn.ready @ jquery.min.js:223
jQuery.fn.init @ jquery.min.js:200
jQuery.fn.init @ jquery-migrate.min.js:27
jQuery @ jquery.min.js:16
(anonymous) @ bootstrap.min.js:1
execCb @ require.min.js:112
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
(anonymous) @ require.min.js:66
(anonymous) @ require.min.js:11
(anonymous) @ mixins.min.js:8
execCb @ require.min.js:112
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
(anonymous) @ require.min.js:66
(anonymous) @ require.min.js:11
(anonymous) @ mixins.min.js:8
execCb @ require.min.js:112
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
(anonymous) @ require.min.js:66
(anonymous) @ require.min.js:11
(anonymous) @ mixins.min.js:8
execCb @ require.min.js:112
check @ require.min.js:56
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
(anonymous) @ require.min.js:72
(anonymous) @ require.min.js:11
(anonymous) @ require.min.js:74
each @ require.min.js:3
emit @ require.min.js:74
check @ require.min.js:61
enable @ require.min.js:73
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:104
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
(anonymous) @ require.min.js:55
(anonymous) @ require.min.js:11
execCb @ require.min.js:112
check @ require.min.js:56
enable @ require.min.js:73
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
load @ mixins.min.js:8
(anonymous) @ require.min.js:71
(anonymous) @ require.min.js:11
on @ require.min.js:40
callPlugin @ require.min.js:61
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
load @ mixins.min.js:8
(anonymous) @ require.min.js:71
(anonymous) @ require.min.js:11
on @ require.min.js:40
callPlugin @ require.min.js:61
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
load @ mixins.min.js:8
(anonymous) @ require.min.js:71
(anonymous) @ require.min.js:11
on @ require.min.js:40
callPlugin @ require.min.js:61
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
callGetModule @ require.min.js:74
completeLoad @ require.min.js:103
onScriptLoad @ require.min.js:112
load (async)
req.load @ require.min.js:119
load @ require.min.js:112
load @ require.min.js:55
fetch @ require.min.js:55
check @ require.min.js:56
enable @ require.min.js:73
enable @ require.min.js:101
(anonymous) @ require.min.js:73
(anonymous) @ require.min.js:11
each @ require.min.js:3
enable @ require.min.js:71
init @ require.min.js:54
(anonymous) @ require.min.js:97
setTimeout (async)
req.nextTick @ require.min.js:117
localRequire @ require.min.js:97
configure @ require.min.js:86
requirejs @ require.min.js:116
req.config @ require.min.js:117
(anonymous) @ requirejs-config.min.js:1
(anonymous) @ requirejs-config.min.js:1
(anonymous) @ requirejs-config.min.js:2
Show 103 more frames

```

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Magento 2.3.6-p2
2. Add some iframe, browse website, you'll **randomly** see this error in the browser console

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32264: Prevent cross origin iframe content reading

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Static Tests, WebAPI Tests

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Static Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Static Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Static Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Unit Tests, Functional Tests B2B

**Review by Den4ik — APPROVED** [review]
✅ Approve

Researched and discussed with @ihor-sviziev 

Changes make since if `$(element)` will be array of 2+ elements. I did't found steps for reproducing issue.
But I admit that `element` could be selector string by some external libraries like FB pixel, twitter etc. Moving code block prevent issue.

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9101](https://jira.corp.magento.com/browse/ENGCOM-9101) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by sfritzsche** [comment]
Hi @ihor-sviziev,
Hi @Den4ik,

we also encountered this problem today. 
We want to add some missing things to your code changes:

1. if you look at the implementation of Magento's "$.nodeName" you will see that there is already a "lowerCase" comparison. So `if ($.nodeName(element, "iframe")) {` should be sufficient.
2. you don't check if the src attribute is empty.
3. the technique of dynamically creating a `<a>` tag, setting the href property (iframe SRC) and then reading the hostname did not work in our tests.A query via the js native `new URL() `seems to be more stable here.

From these points we have the following code:

```
(function lookup(element) {
var iframeDomain;

// prevent cross origin iframe content reading
if ($.nodeName(element, "iframe")) {
    if($(element).prop('src').length) {
        var iframeDomain = (new URL($(element).prop('src')));
        if (window.location.hostname !== iframeDomain.hostname) {
            return []; // src not base-url/origin
        }
    } else {
        return []; // empty src
    }
}

/** ... **/
contents = function (elem) { ...
```
Could you check this once ?

**Comment by engcom-Bravo** [comment]
Hi @ihor-sviziev,

As per this https://github.com/magento/magento2/issues/32264#issuecomment-2036569519 We are closing this PR.

Please feel free to reopen the PR.

Thanks.

**Pull request closed without merging**
