### PR TITLE
[Forwardport] Do not overwrite URL Key with blank value

### PR DESCRIPTION
**Pull request by mage2pratik**
### Original Pull Request 
 https://github.com/magento/magento2/pull/17882

### Description
- do not update existing products with a blank URL Key if no `url_key` value is provided in the import data
- do not update existing products with a new URL Key if a `name` but no `url_key` value is provided in the import data

### Fixed Issues
- magento/magento2#17023: CSV Import of `sku,attribute` empties `url_key` value

### Manual testing scenarios
See issue for details. Essentially if importing a CSV with `sku,name` or `sku,description` only, the result is the unexpected update or removal of the URL Key of the product.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3262](https://jira.corp.magento.com/browse/ENGCOM-3262) has been created to process this Pull Request

**Comment by sidolov** [comment]
Hi @mage2pratik , please, resolve merge conflicts

**Comment by magento-engcom-team** [comment]
@mage2pratik thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request closed without merging**
