### PR TITLE
Fixed address book display horizontal scroll in responsive view

### PR DESCRIPTION
**Pull request by mage2pratik**
### Description (*)

Fixed address book display horizontal scroll in responsive view (iPad).

### Fixed Issues (if relevant)

1. magento/magento2#21271: Address book display horizontal scroll in responsive view

### Manual testing scenarios (*)

1. Go to My Account
2. Add Additional addresses in my account -> Address book
3. See the added addresses in responsive views iPad(768x1024).
4. Displaying the horizontal scroll

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-21272.instances.magento-community.engineering).
Admin access: [https://pr-21272.instances.magento-community.engineering/admin](https://pr-21272.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4309](https://jira.corp.magento.com/browse/ENGCOM-4309) has been created to process this Pull Request

**Pull request merged**
