### PR TITLE
Prevent "Overwrite the existing configuration for ...?" question

### LINKED ISSUE #29612: [Issue] Prevent "Overwrite the existing configuration for db-ssl-verify?" question
This issue is automatically created based on existing pull request: magento/magento2#26818: Prevent "Overwrite the existing configuration for db-ssl-verify?" question

---------
### Summary (*)
Magento 2.4-develop
This question is occurred [every time](https://github.com/magento/magento2/issues/26762#issuecomment-584698357) I run:
```
$ ./bin/magento setup:config:set
```

after upgrade to 2.3.4

Also see #26762 

We should ask this question only if new value of configuration option is not equal to the old value,.

### PR DESCRIPTION
**Pull request by flancer64**
Duplication for PR https://github.com/magento/magento2/pull/26818

This question is occurred [every time](https://github.com/magento/magento2/issues/26762#issuecomment-584698357) I run:
```
$ ./bin/magento setup:config:set
```

after upgrade to 2.3.4

We should ask this question only if new value of configuration option is not equal to the old value,. 

### Resolved issues:
1. [x] resolves magento/magento2#29612: Prevent "Overwrite the existing configuration for db-ssl-verify?" question

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @flancer64,
Could you fix failing static tests? Functional tests failures looks not related.
It's really strange that we hadn't this failure in prev. PR.

**Comment by flancer64** [comment]
@ihor-sviziev , something is done. I hope it will help with static tests.

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Review by flancer64 — COMMENTED** [review]
Great solution! I didn't see this way (y) ;)

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8230](https://jira.corp.magento.com/browse/ENGCOM-8230) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Result:**
**Before:**
:x: `Overwrite the existing configuration for db-ssl-verify?` is shown, when `'driver_options'` has no changes in `env.php`
image


**After:**
:heavy_check_mark: `Overwrite the existing configuration for db-ssl-verify?` message is not shown, when `'driver_options'` has no changes in `env.php`
image

:heavy_check_mark: `Overwrite the existing configuration for db-ssl-verify?` message is shown, when `'driver_options'` has new value in `env.php`
image

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Pull request merged**
