### PR TITLE
Introducing method reflection storage to increase performance

### LINKED ISSUE #36276: Long time request execution
### Preconditions and environment

- 2.4.5
- Make a request to bulk API with a lot of products in request. For instance 5k. <website_url>rest/async/bulk/V1/products.

### Steps to reproduce

- open client to work with Magento API
- fetch the token
- fill request body with huge amount of product. For instance > 5k
- create API request to the <website_url>rest/async/bulk/V1/products
- wait until request finishes

### Expected result

Have a quick response

### Actual result

Request duration is too long

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by wassuupp**
### Description (*)
Proposed solution allows to reduce request execution time for the big amount of entities. Solution is based on xdebug profiling results. It uses a variable inside the class, which stores reflected methods data. This approach reduces the numbers of operations for the reflection methods execution for the entities which are repeated in request.
The results of the performance measurements tests are in the following table: 
[Measurements of bulk API.pdf](https://github.com/magento/magento2/files/9763267/Measurements.of.bulk.API.pdf)

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36276

### Manual testing scenarios (*)
1. open client to work with Magento API
2. fetch the token
3. fill request body with huge amount of product. For instance > 5k
4. create API request to the <website_url>rest/async/bulk/V1/products
5. wait until request finishes

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by wassuupp** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by peterjaap** [comment]
@wassuupp could you give this PR a name? Like "Introducing method reflection storage to increase performance" ?

**Comment by peterjaap** [comment]
@wassuupp could you give this PR a name? Like "Introducing method reflection storage to increase performance" ?

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Moving this PR to "Merge in progress" due to there being no files to test.

**Comment by hostep** [comment]
@engcom-Hotel: it looks like the changes from this PR were already included in Magento 2.4.6 by https://github.com/magento/magento2/commit/9c42b97a9c307bf32fd46e3b72d5856ce8ee4429 (you can see the [history over here](https://github.com/magento/magento2/commits/2.4.6/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php))

No idea why this PR is still open or why you think it still needs to be merged?

**Comment by ihor-sviziev** [comment]
Hi @wassuupp,
As @hostep said, this change was already delivered to the 2.4-develop branch as cherry-picked commits in https://github.com/magento/magento2/commit/c46527302b30795fe6d882a8fbbcab3524da581b https://github.com/magento/magento2/commit/ecb341c18187adeb26941531dcc14fff5e7d76d6 https://github.com/magento/magento2/commit/3d9a140bfe8dc303474b693b44a05aeaf36d7a52.
Thank you so much for your contribution!
Since changes were already delivered, I'm closing this pull request.

**Pull request closed without merging**
