### PR TITLE
fix: Prevent loops in resolving final URL Rewrite

### LINKED ISSUE #38692: Adding URL rewrites with an accent causes infinite loading
### Preconditions and environment

- Tested on 2.4.5-p7 and 2.4.6-p4
- Vanilla Magento with sample data

### Steps to reproduce

Add a new URL Rewrite with an accent and redirect type not set to None

Example:
Screenshot 2024-05-02 at 12 18 23

### Expected result

URL Rewrite is successfully created and functioning

### Actual result

The saving will last forever 

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by pmzandbergen**
### Description (*)
URL rewrites with the same request and target path will create a loop in the GraphQL resolver.

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
1. Fixes magento/magento2#38692

### Manual testing scenarios (*)
1. Create a URL rewrite with the same request and target path
2. Resolve the URL rewrite using GraphQL
3. Test with and without this PR

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by pmzandbergen** [comment]
Note: Created a more robust fix

**Comment by engcom-Bravo** [comment]
Hello,

Internal team has started to work on it

Thanks.

**Comment by pmzandbergen** [comment]
@magento review

**Comment by pmzandbergen** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-11907 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-11907&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta1.

Thanks

**Pull request closed without merging**
