### PR TITLE
Added getter and setter on store model and interface

### PR DESCRIPTION
**Pull request by hervebackstage**
Added getter and setter on store model and interface

### Description

this change gives the node is_active available to the API call rest/default/V1/store/storeViews

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=11077) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=11077) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: hervebackstage<br/>:x: paliarush<br/>:x: viktym

**Comment by orlangur** [comment]
Please sign CLA and check review notes in https://github.com/magento/magento2/pull/10923.

**Comment by osrecio** [comment]
Same PR: #10923

**Comment by orlangur** [comment]
Closing in favor of earlier PR with the same approach which was decided to be merged as is.

@hervebackstage thanks for collaboration!

**Pull request closed without merging**
