### PR TITLE
Expiration time cannot be float

### PR DESCRIPTION
**Pull request by nextend**
Expire time of PHP setcookie cannot be bigger than INT as FLOAT is not accepted and throws error.

### CODE REVIEW

**Comment by nextend** [comment]
This error happens if you set big session timeout on the admin interface.

**Comment by daim2k5** [comment]
@nextend Thank you for your contribution. Please accept the contributors license agreement so this PR can be further processed. This can be done by clicking the "Details" link next to the "license/cla" check below.

**Comment by nextend** [comment]
@daim2k5 done

**Comment by mazhalai** [comment]
@nextend can you please resync with develop and restart builds?

**Comment by nextend** [comment]
@mazhalai Could you tell me how to do that?

**Comment by mazhalai** [comment]
To resync:
- git fetch --all
- git checkout <your branch>
- git merge magento(or whatever is your name for magento remote)/develop
- push to your remote branch.
- click on "details" next to "continuous-integration/travis-ci/pr " below, and it should automatically re-run the tests.

**Comment by daim2k5** [comment]
@nextend did it work?

**Comment by nextend** [comment]
Is it good now?

**Comment by ilol** [comment]
Internal ticket: MAGETWO-56382

**Comment by vrann** [comment]
@nextend unfortunately, we don't process PRs to 2.0 branch at the moment. Please re-create it against the develop branch.

**Pull request closed without merging**
