### PR TITLE
Fix coupon marked as usage#32384

### LINKED ISSUE #32384: Unused coupon marked as used
### Preconditions (*)

1. Magento 2.3.6 (I've checked code version for Magento 2.4 and it's the same) and minimum order amount limit set
2. Registered user
3. Coupon code with 1 use for customer and fixed discount amount

### Steps to reproduce (*)

1. Fill the cart up to the minimum order amount
2. Put the coupon to the cart just before the last checkout step, so the new total order amount is below minimum amount
3. Submit the order in the fastest way (i.e. I used payment-information API)

### Expected result (*)
1. The order is not placed, an error about minimum amount is shown
2. The coupon is still usable

### Actual result (*)
1. The order is not placed and an error about minimum amount is shown
2. The coupon is marked as used for the customer (in `salesrule_customer` ) and cannot be used again

Hint maybe:
The coupon is marked as used by `CouponUsagesIncrement`, a plugin to `beforeSubmit` of `QuoteManagement`. The quote validation is in `submitQuote`, nested to `submit`, so it is run after, and throws uncatched exceptions up to the frontend, so the database keeps the coupon as used. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by gixid192**
### Description (*)
The flow is exactly described in the issue #32384
Magento has the function to handle it already, it's just that it only check when order place, not quote submit.

What I do in this PR is extend the block code up further in the quote submit function, so when there's an error happen, it will be handled correctly.

### Fixed Issues (if relevant)
Fixes magento/magento2#32384

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by gixid192** [comment]
@magento run all tests

**Comment by gixid192** [comment]
@magento run Functional Tests B2B, Unit Tests

**Review by hws47a — CHANGES_REQUESTED** [review]
Hi @gixid192, thank you for your contribution. 
The change looks good to me, however, as per [contribution guidelines](https://devdocs.magento.com/contributor-guide/contributing.html), all changes must be covered with tests.
You may adjust one of the tests or introduce a new one here: `app/code/Magento/Quote/Test/Unit/Model/QuoteManagementTest.php`
Let me know if you need any help.

**Comment by gixid192** [comment]
Thank @hws47a, I'm new to testing in general, I will cover the test as soon as possible.

**Comment by engcom-Foxtrot** [comment]
Hello, @gixid192. Unfortunately, I'm closing and re-creating this PR, as I was not able to push any changes to this PR branch. Please feel free to push any updates to #33015.

**Pull request closed without merging**
