### PR TITLE
magento/magento2#: Test Coverage. API functional tests. removeItemFromCart

### PR DESCRIPTION
**Pull request by atwixfirster**
### Description (*)

PR adds a test coverage for the next exceptions of `removeItemFromCart` mutation:
-  [Required parameter "cart_id" is missing.](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/QuoteGraphQl/Model/Resolver/RemoveItemFromCart.php#L53)
-  [Required parameter "cart_item_id" is missing.](https://github.com/magento/magento2/blob/2.3.3/app/code/Magento/QuoteGraphQl/Model/Resolver/RemoveItemFromCart.php#L58)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

Thank you!

### CODE REVIEW

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7020](https://jira.corp.magento.com/browse/ENGCOM-7020) has been created to process this Pull Request
:eight_spoked_asterisk: @dmytro-ch, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello @atwixfirster, could you please update your working branch with the latest changes from `2.4-develop` and fix static test?

**Comment by atwixfirster** [comment]
> Hello @atwixfirster, could you please update your working branch with the latest changes from `2.4-develop` and fix static test?

**done**

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-7020](https://jira.corp.magento.com/browse/ENGCOM-7020) has been created to process this Pull Request

**Pull request merged**
