### PR TITLE
PHP Brecate Start Issues.

### PR DESCRIPTION
**Pull request by mayankzalavadia**
### Description
PHP Brecate starting issues. Some server not supported that types of syntax.

### Fixed Issues (if relevant)

1. PHP Brecate starting issues onmagento/module-layered-navigation/view/frontend/templates/layer/filter.phtml

### Manual testing scenarios

1. Go to product listing and check left side filter.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=10986) <br/>All committers have signed the CLA.

**Comment by Jeroenll** [comment]
You forgot to add `echo`.

Also, according to the [documentation](http://php.net/manual/en/language.basic-syntax.phptags.php) the tag `<?=` is always available regardless of the `short_open_tag` ini setting since PHP5.4.

**Comment by mayankzalavadia** [comment]
Now the code is updated with echo.

**Comment by orlangur** [comment]
Echoes were replaced with `<?=` in all templates and it is enforced with a sniff.

Please provide details according to https://github.com/magento/magento2/blob/develop/.github/ISSUE_TEMPLATE.md so that anyone can reproduce this problem. Agree with @JeroenVanLeusden, more details [here](https://stackoverflow.com/a/1386627).

**Comment by orlangur** [comment]
Hi @mayankzalavadia, are you going to proceed?

**Pull request closed without merging**
