### PR TITLE
Replace repetitive actions with Action groups in StorefrontInactiveCatalogRuleTest

### LINKED ISSUE #33556: [Issue] Replace repetitive actions with Action groups in StorefrontInactiveCatalogRuleTest
This issue is automatically created based on existing pull request: magento/magento2#33218: Replace repetitive actions with Action groups in StorefrontInactiveCatalogRuleTest

---------

### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run the test in the local environment and verified that it runs successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run the test in the local environment and verified that it runs successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#33556: Replace repetitive actions with Action groups in StorefrontInactiveCatalogRuleTest

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run WebAPI Tests, Functional Tests CE, Functional Tests B2B

**Comment by eduard13** [comment]
@magento run Functional Tests CE

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-9154](https://jira.corp.magento.com/browse/ENGCOM-9154) has been created to process this Pull Request

**Comment by engcom-Charlie** [comment]
@magento create issue

**Comment by engcom-Charlie** [comment]
Hi @eduard13 and @kate-kyzyma 

I have done the required setup to test this PR. 

When I am running vendor/bin/mftf run:test StorefrontInactiveCatalogRuleTest --remove test case getting below error.

image

image


Can you please mention, is this the expected behaviour, as the test case is showing 0 assertions and 1 failure.

Thanks in advance!

**Comment by eduard13** [comment]
Hi @engcom-Charlie, thank you for testing this one, really strange that all the checks are green 😕.
@kate-kyzyma, could you please check the reported above issue?

**Comment by engcom-Charlie** [comment]
@eduard13 Thanks for confirming.

:x: QA not Passed 

I have done the required setup to test this PR.

When I am running vendor/bin/mftf run:test StorefrontInactiveCatalogRuleTest --remove test case getting below error.

image

image

image

**Comment by engcom-Charlie** [comment]
Hi @eduard13 and @kate-kyzyma

I have retested this issue and found that its working fine. I was missing out few steps of MFTF related setup which was causing [some issue](https://github.com/magento/magento2/pull/33218#issuecomment-885440239) when I was testing.

Sorry for the inconvenience.

The MFTF test case vendor/bin/mftf run:test StorefrontInactiveCatalogRuleTest --remove is working as expected.

:heavy_check_mark: QA Passed

image

**Pull request merged**
