### PR TITLE
WIP: Cleanup ObjectManager usage - Magento_Widget

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This PR cleanups ObjectManager usage in Magento_Widget, adds additional dependencies with backward compatibility to api classes, and removes object manager instantiation from non-api classes.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @Bartlomiejsz. Please, check my comments from your [recent PR](https://github.com/magento/magento2/pull/26684). The same idea is applicable here. We need to preserve backward compatibility upon making such changes. 
Keep in mind that `LoadOptions` may be already inherited by a child class that invokes `parent::construct` method. In that case, you will have fatal error since `$conditionHelper` and `$json` arguments will equal NULL.

**Comment by rogyar** [comment]
Hi @Bartlomiejsz. My previous comment does not apply to the current case since we are modifying a non-API class. Could you check the failing tests, please? 

Thank you

**Comment by rodrigowebjump** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [Magento instance](https://i-26685-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26685-2-4-develop.instances.magento-community.engineering/admin_560b](https://i-26685-2-4-develop.instances.magento-community.engineering/admin_560b)
Login: `fe485edc` Password: `b862132e8725`
Instance will be terminated in up to 3 hours.

**Comment by Bartlomiejsz** [comment]
Closing for same reason as https://github.com/magento/magento2/pull/27855 - will be recreated for 2.5.0

**Pull request closed without merging**
