### PR TITLE
New products widget swatches

### PR DESCRIPTION
**Pull request by ashokramji**
### Fixed Issues (if relevant)

1. magento/magento2#14134: Swatches not showing on homepage New products widget

### Manual testing scenarios

1. Create a widget and call New products on home page
2. Add to New product list any configurable products

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15524) <br/>All committers have signed the CLA.

**Comment by ashokramji** [comment]
Anyone fix the issue...???

**Comment by sidolov** [comment]
Hi @ashokramji  , please, sign CLA, otherwise, we can't process your pull request

**Comment by sidolov** [comment]
Hi @ashokramji , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by sidolov** [comment]
Hi @ashokramji , will you continue progress with PR? 
Thank you!

**Comment by ashokramji** [comment]
Hi @sidolov ,I will continue the progress with PR

Thank You!

**Review by orlangur — CHANGES_REQUESTED** [review]
Nowadays all changes must be applied to `2.3-develop` first (see https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules). Please prepare a new pull request, this one should be `on hold` until the latter is merged.

**Comment by orlangur** [comment]
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

**Pull request closed without merging**
