### PR TITLE
Update checkout_index_index.xml

### PR DESCRIPTION
**Pull request by kevinjruffe**
Without this you'll get an undefined index error in Magento\CustomerCustomAttributes\Block\Checkout\LayoutProcessor

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23449) <br/>All committers have signed the CLA.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5368](https://jira.corp.magento.com/browse/ENGCOM-5368) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@kevinjruffe thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
Hi, @kevinjruffe . I have no idea how to reproduce it. Can you give me some steps for testing scenario?

**Comment by sidolov** [comment]
@kevinjruffe , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
