### PR TITLE
magento/magento2#15255 unlock customer after password reset

### PR DESCRIPTION
**Pull request by gelanivishal**
### Original Pull Request
#15534 

Unlock customer after password reset

### Fixed Issues (if relevant)

1. magento/magento2#15255: unlock customer after password reset

### Manual testing scenarios

1. After x customer failed login, customer get locked
2. From backend, it's sent a reset password main
3. User changes his password
4. User is still locked

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @vgelani. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on Pull Request changes
- `@magento-engcom-team give me new test instance` - deploy **NEW** test instance based on Pull Request changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy Vanilla Magento instance for Issue or Pull Request

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by phoenix128** [comment]
Closing as duplicate of https://github.com/magento/magento2/pull/16255 .

**Review by phoenix128 — APPROVED** [review]
Hello @vgelani , thank you for your contribution.

**Comment by magento-engcom-team** [comment]
Hi @phoenix128, thank you for the review.
[ENGCOM-2060](https://jira.corp.magento.com/browse/ENGCOM-2060) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @vgelani. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.3.0 release.

**Pull request merged**
