### PR TITLE
Issue 36052: Can't Create shipment for ordered qty less than 1

### LINKED ISSUE #36052: Can't Create shipment for ordered qty less than 1
### Preconditions and environment

- Magento version: Magento Open Source Ver. 2.4.4-p1, Magento Open Source Ver. 2.4.5
- Create an Order with Qty less than 1. Then create the invoice and then create the shipment. The items will not be displayed in the "Items to Ship"  section.

image

I have fixed this by changing the below code in the file **Magento\Sales\Model\Order\ShipmentFactory.php**

```
 private function validateItem(\Magento\Sales\Model\Order\Item $orderItem, array $items)
    {
        if (!$this->canShipItem($orderItem, $items)) {
            return false;
        }

        // Remove from shipment items without qty or with qty=0
        if (!$orderItem->isDummy(true)
            && (!isset($items[$orderItem->getId()]) || (int) $items[$orderItem->getId()] <= 0)
        ) {
            return false;
        }
        return true;
    }
```

Changed the **(int) $items[$orderItem->getId()]** to  **$items[$orderItem->getId()]**

### Steps to reproduce

Step 1: Create an order with an item with decimal qty and the qty must be less than 1. (Eg:0.5)
Step 2: Create invoice
Step 3: Create Shipment 

### Expected result

The items are to be displayed in the "Items to Ship" section.

### Actual result

The items are not displayed in the "Items to Ship" section.

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rogerdz**
### Description (*)
Can't Create shipment for ordered qty less than 1

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36052

### Manual testing scenarios (*)

1. Create an order with an item with decimal qty and the qty must be less than 1. (Eg:0.5)
2. Create invoice
3. Create shipment

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Review by edenduong — APPROVED** [review]
Thank you for your contribution!

**Comment by edenduong** [comment]
P/S : Added Autotest is not required because it only change int type to float type.

**Comment by engcom-Lima** [comment]
Hi @rogerdz ,

This PR is duplicate of this PR : https://github.com/magento/magento2/pull/35972
Hence, closing this PR.

Thanks

**Pull request closed without merging**
