### PR TITLE
get.php - check existence of required config array items

### LINKED ISSUE #36640: [Issue] get.php - check existence of required config array items
This issue is automatically created based on existing pull request: magento/magento2#36379: get.php - check existence of required config array items

---------
### Description (*)

`pub/get.php` throw warning `Trying to access array offset on value of type null` in some weird cases of corrupted `resource_config.json`

### Manual testing scenarios (*)

1. Delete content of `var/resource_config.json`
2. Request /get.php?something

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by freezy-sk**
### Description (*)

`pub/get.php` throw warning `Trying to access array offset on value of type null` in some weird cases of corrupted `resource_config.json`

### Manual testing scenarios (*)

1. Delete content of `var/resource_config.json`
2. Request /get.php?something

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36640: get.php - check existence of required config array items

### CODE REVIEW

**Comment by Den4ik** [comment]
@freezy-sk Please sign CLA

**Comment by freezy-sk** [comment]
@Den4ik signed ;)

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Integration Tests

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by Den4ik** [comment]
@magento run Functional Tests B2B

**Review by Den4ik — APPROVED** [review]
✅ Approved

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento `2.4-develop`

**Manual testing scenario:**
1. Remove the content of var/resource_config.json
2. Request the get.php 

**Before:** : Without PR changes:
Request the /instance url/get.php
Screenshot 2022-11-10 at 8 09 38 PM

**After:** :With PR changes:  
Request the /instance url/get.php
Screenshot 2022-11-10 at 8 15 32 PM
Thanks.

**Comment by engcom-Delta** [comment]
@magento create issue

**Pull request merged**
