### PR TITLE
Added getStatusBySku method + product_status + docs

### PR DESCRIPTION
**Pull request by sedonik**
### Description (*)
This PR provides solution for soling issue https://github.com/magento/magento2/issues/26111
Added product_status option to the values option list.

### Fixed Issues (if relevant)

1. magento/magento2#26111: configurable_options uses disabled products to populate the options #26111

### Preconditions (*)

1. magento/module-configurable-product-graph-ql: 100.3.1

### Steps to reproduce (*)

1. Create Configurable product which contains two Color configurations, for example, "Color1" and "Color2". 
2. Disable the "Color2" configuration.
3. Perform query:
``` graphql
{
  products(
    filter: {
      sku: {
        eq: "Configurable"
      }
    }
  ) {
    items {
      id
      attribute_set_id
      name
      sku
      type_id
      categories {
        id
      }
      ... on ConfigurableProduct {
        configurable_options {
          id
          attribute_id
          label
          position
          use_default
          attribute_code
          values {
            value_index
            label
          }
          product_id
        }
        variants {
          product {
            id
            name
            sku
            attribute_set_id
          }
        }
      }
    }
  }
}
```
### Expected result (*)
Disabled option should not be returned.
``` graphql
{
  "data": {
    "products": {
      "items": [
        {
          "id": 4,
          "attribute_set_id": 4,
          "name": "Configurable",
          "sku": "Configurable",
          "type_id": "configurable",
          "categories": [
            {
              "id": 3
            }
          ],
          "configurable_options": [
            {
              "id": 1,
              "attribute_id": "93",
              "label": "Color",
              "position": 0,
              "use_default": false,
              "attribute_code": "color",
              "values": [
                {
                  "value_index": 4,
                  "label": "Color1"
                  "product_status": "Enabled"
                },
                {
                  "value_index": 5,
                  "label": "Color2"
                  "product_status": "Disabled"
                }
              ],
              "product_id": 4
            }
          ],
          "variants": [
            {
              "product": {
                "id": 5,
                "name": "Configurable-Color1",
                "sku": "Configurable-Color1",
                "attribute_set_id": 4
              }
            }
          ]
        }
      ]
    }
  }
}
```

### Actual result (*)
Disabled "Color2" option is returned in the `configurable_options` section.
``` graphql
{
  "data": {
    "products": {
      "items": [
        {
          "id": 4,
          "attribute_set_id": 4,
          "name": "Configurable",
          "sku": "Configurable",
          "type_id": "configurable",
          "categories": [
            {
              "id": 3
            }
          ],
          "configurable_options": [
            {
              "id": 1,
              "attribute_id": "93",
              "label": "Color",
              "position": 0,
              "use_default": false,
              "attribute_code": "color",
              "values": [
                {
                  "value_index": 4,
                  "label": "Color1"
                },
                {
                  "value_index": 5,
                  "label": "Color2"
                }
              ],
              "product_id": 4
            }
          ],
          "variants": [
            {
              "product": {
                "id": 5,
                "name": "Configurable-Color1",
                "sku": "Configurable-Color1",
                "attribute_set_id": 4
              }
            }
          ]
        }
      ]
    }
  }
}
```

### CODE REVIEW

**Review by swnsma — CHANGES_REQUESTED** [review]
Hi @sedonik!
Thank you for your contribution!

Could you help me to find business example where **disabled/enabled** flag will be useful on frontend?

**Comment by sedonik** [comment]
Hi @swnsma ,

I think it can be useful in any place where is used "values".

For example, when "Color2" option is disabled customer can ask the shop owner to order and enable this option.

Or maybe Shop owner could provide this option as an advertisement and when there are some customers want to order this product.

**Comment by swnsma** [comment]
Hi @sedonik,
I think in such case it may be used as 'out-of-stock' product.
Also I think in case if product is 'disabled' - we should know nothing about it on frontend (e.g. visible but disabled product will not be shown on storefront even by direct link).
What to you think about this alternative ?

**Comment by sedonik** [comment]
Hi @swnsma
After some thinking, I've added a plugin that detects if an option is disabled, unset this variable from return array.
[New PR](https://github.com/magento/magento2/pull/26690)

**Comment by swnsma** [comment]
@sedonik please check my comment in your New PR :)
So, can I close this Pull Request?

**Review by swnsma — CHANGES_REQUESTED** [review]
@sedonik please check my comment in your New PR :)
So, can I close this Pull Request?

**Comment by sedonik** [comment]
@swnsma Yes, Thank you.

**Comment by swnsma** [comment]
Closed by request.
New PR: https://github.com/magento/magento2/pull/26690

**Pull request closed without merging**
