### PR TITLE
Added stacktrace to report error output when enabled

### PR DESCRIPTION
**Pull request by wsakaren**
Currently just gives a description of error, no stack trace, which slows down debugging as you have to open in var/report. If reporting is set to trace mode IMO then it should also display the stack trace in browser.

### CODE REVIEW

**Comment by dkvashninbay** [comment]
Hi @wsakaren, thanks for contribution!
There are several comments according 7b4b054 , please verify them and we'll be able to merge this pull request.
Best regards

**Comment by magento-cicd** [comment]
We have automated a Magento Contributor License Agreement verifier for contributions sent to our GitHub projects.
Please see the CLA agreement in the Pull Request comments.

**Comment by Vinai** [comment]
@wsakaren Can you please rebase onto the current develop? It would also be nice if you would respond to the comments of @dkvashninbay . Also, the automated license agreement needs to be signed in order to process this PR further. Thanks!

**Comment by wsakaren** [comment]
I don't have bandwidth at present to progress I'm afraid. Suggest close.

**Pull request closed without merging**
