### PR TITLE
[Shipping] Adding the tracking number client validation

### PR DESCRIPTION
**Pull request by eduard13**
### Description (*)
This PR provides a client validation for tracking number.

### Fixed Issues (if relevant)
1. magento/magento2#24745: Magento pop up not display on tracking info message

### Manual testing scenarios (*)
1. Create a new order
2. Create a shipment for that order
3. Navigate to the shipment
4. Add a new tracking carrier
5. The Tracking Number should be validated before sending the request
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by VladimirZaets** [comment]
Hi @eduard13. Thanks for collaboration. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @eduard13. Thanks for collaboration. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

**Comment by eduard13** [comment]
Hi @VladimirZaets, I've added a functional testing coverage for this fix. Please review it again.
Thank you.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6060](https://jira.corp.magento.com/browse/ENGCOM-6060) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
