### PR TITLE
Replace repetitive actions with Action Groups in StorefrontConfigurableProductCanAddToCartTest

### LINKED ISSUE #33784: [Issue] Replace repetitive actions with Action Groups in StorefrontConfigurableProductCanAddToCartTest
This issue is automatically created based on existing pull request: magento/magento2#32117: Replace repetitive actions with Action Groups in StorefrontConfigurableProductCanAddToCartTest

---------

### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)

Run the test in the local environment and verified that it run successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)

Run the test in the local environment and verified that it run successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#33784: Replace repetitive actions with Action Groups in StorefrontConfigurableProductCanAddToCartTest

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B Functional Tests EE

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello @kate-kyzyma, could you please check and fix the issue reported by Semantic Version Checker?

**Comment by kate-kyzyma** [comment]
@magento run Semantic Version Checker

**Comment by dmytro-ch** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run Functional Tests EE, Functional Tests B2B, Static Tests

**Comment by dmytro-ch** [comment]
@magento run Static Tests

**Comment by dmytro-ch** [comment]
@magento run Functional Tests EE

**Comment by dmytro-ch** [comment]
@magento run Static Tests

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run Integration Tests, Functional Tests B2B, WebAPI Tests

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-8922](https://jira.corp.magento.com/browse/ENGCOM-8922) has been created to process this Pull Request

**Comment by eduard13** [comment]
@magento create issue

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8922](https://jira.corp.magento.com/browse/ENGCOM-8922) has been created to process this Pull Request

**Comment by engcom-Charlie** [comment]
✔️ QA Passed

The provided MFTF test case is working fine and green in build. Please find the Allure report for the same.

image

image

**Pull request merged**
