### PR TITLE
24259-fixed url-rewrites generation

### PR DESCRIPTION
**Pull request by oscarsanch**
### Description (*)

If Single-store Mode is enabled then url-rewrites do not generate for product 

### Fixed Issues (if relevant)

1. magento/magento2#<24259>: URL key/SEO friendly URL not used for products when in single-store mode
2. url rewrite generator skips generation for products if application has single store mode

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24747) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=24747) before we can accept your contribution.<br/>

**Comment by josefbehr** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @josefbehr. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @josefbehr, here is your [new Magento instance](https://pr-24747.instances.magento-community.engineering).
Admin access: [https://pr-24747.instances.magento-community.engineering/admin](https://pr-24747.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by josefbehr — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
Hello @oscarsanch. Thank You for Your contribution. In order to further process Your PR, please cover it with the appropriate auto-tests.

**Comment by VladimirZaets** [comment]
@oskarolaussen, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Comment by josefbehr** [comment]
@VladimirZaets is it really more important to have tests than to have this bug fixed?

**Pull request closed without merging**
