### PR TITLE
Remove 'pub/' directory from paths in css source maps when compiling using grunt

### LINKED ISSUE #38837: Grunt Less uses pub/ prefix for sourcemaps
### Summary

When using grunt to generate css, the associated sourcemaps use the prefix pub/ on all urls it generates. This forces the webserver config to employ a workaround to allow pub/ urls to continue to work, just for the sourcemaps. Sourcemaps should not use the pub/ prefix.

### Examples

Deploy Vanilla 2.4.7-p1
> cp Gruntfile.js.sample Gruntfile.js
> php bin/magento deploy:mode:set development
> grunt clean
> grunt exec
> grunt less
> less pub/static/frontend/Magento/luma/en_US/css/styles-l.css.map

Observe the paths include pub/static

Browse to the frontend and inspect an element in the dev console.
Check the location of the less file obtained via the sourcemap

vDLOkBHE70

Although this will still work if your nginx config includes the following snippet

https://github.com/magento/magento2/blob/91cb4d46834b88bb8dc9f5b06279a63d9ad0963c/nginx.conf.sample#L98C1-L104C2

But isn't the use of /pub/ urls now unsupported?

### Proposed solution

_No response_

### Release note

less/css sourcemaps generated by grunt no longer use the /pub prefix for paths.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by hostep**
### Description (*)
When compiling css using grunt, and generating sourcemaps, the url's in the sourcemap point to .less files inside the `pub/` directory, which is not correct, as Magento's document root is set to `pub/` in the webserver config, so `pub/` should not be in the url of the sourcemaps.

Fixed with the help from reading the [documentation from less](https://lesscss.org/usage/#less-options-source-map-basepath):
> #### Source Map Basepath
>
> `lessc --source-map-basepath=less-files/`	`{ sourceMap: { sourceMapBasepath: 'less-files/' } }`
>
> This is the opposite of the rootpath option, it specifies a path which should be removed from the output paths. For instance if you are compiling a file in the less-files directory but the source files will be available on your web server in the root or current directory, you can specify this to remove the additional `less-files` part of the path.
> 
> It defaults to the path to the input less file.

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/38837

### Manual testing scenarios (*)
1. Setup clean Magento
2. Run:
```
$ cp package.json.sample package.json
$ cp Gruntfile.js.sample Gruntfile.js
$ npm install
$ grunt clean:luma && grunt exec:luma && grunt less:luma
```
3. Open the frontend in your browser and open the inspector
4. Expectation is not to see a `pub/` directory in the path when hovering over a less filename in the inspector:
Screenshot 2024-06-18 at 20 37 48

### Questions or comments
No automated test were added, I don't think we have tests for grunt workflows, or do we?

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hostep** [comment]
There's no good reason for this (I think), but let's run the automated test suite once...

@magento run all tests

**Comment by hostep** [comment]
@magento run Static Tests

**Comment by hostep** [comment]
There is still one static test failure:

```
Use the function form of 'use strict'.
line 17, col 32, Error - Use the function form of &apos;use strict&apos;. (strict)
```

If somebody could give me a hint of how to fix this, that would be appreciated, I'm not a node.js developer, so it would take me too long to research a good solution.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by Eddcapone** [comment]
For me the source maps are not getting generated at all when compiling by using grunt.

**Comment by hostep** [comment]
@Eddcapone,  it sounds like you aren't using Magento 2.4.7 but probably a lower version? In that case you'll also need this fix: https://github.com/magento/magento2/pull/28415, which got included in Magento 2.4.7

**Comment by Eddcapone** [comment]
> @Eddcapone, it sounds like you aren't using Magento 2.4.7 but probably a lower version? In that case you'll also need this fix: #28415, which got included in Magento 2.4.7

Thank you so much, I try to figure this out for a long time...
Adding[ these lines](https://github.com/magento/magento2/pull/28415/files) solved it!

**Comment by hostep** [comment]
And that last one can be fixed by the first commit in this pull request: https://github.com/magento/magento2/pull/38840/commits/8f0387c34e7aee076a5d07a69e589df198fffb59

**Comment by Eddcapone** [comment]
> And that last one can be fixed by the first commit in this pull request: [8f0387c](https://github.com/magento/magento2/commit/8f0387c34e7aee076a5d07a69e589df198fffb59)

Confimred. I applied your fix and now it works as it is supposed to.

**Review by Eddcapone — APPROVED** [review]

**Comment by engcom-November** [comment]
Hello @hostep,

Thank you for collaboration and contribution!

### ✔️ QA Passed

**Preconditions:**
- Install fresh Magento 2.4-develop

**Steps to reproduce:**
- Run:
```
$ cp package.json.sample package.json
$ cp Gruntfile.js.sample Gruntfile.js
$ npm install
$ grunt clean:luma && grunt exec:luma && grunt less:luma
```
- Open the frontend in your browser and open the inspector
- Expectation is not to see a pub/ directory in the path when hovering over a less filename in the inspector.

**Before: ✖️** 
pub/ directory can be seen in path of less file.
image

**After: ✔️**
pub/ directory cannot be seen in path of less file.
image

Thank you.

**Comment by engcom-November** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
Since builds are failed, moving it to Extended Testing.

**Comment by engcom-November** [comment]
@magento run Static Tests

**Comment by engcom-November** [comment]
@magento run Static Tests

**Comment by engcom-November** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Unit Tests

**Comment by engcom-November** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Review by Eddcapone — APPROVED** [review]

**Comment by engcom-November** [comment]
The repeating Functional Tests B2B, Functional Tests EE and Functional Tests CE failures are flaky and know issues.

**Functional Tests B2B:**
**Run 1:**
image

**Run 2:**
image

**Known issues:**
[ACQE-6695](https://jira.corp.adobe.com/browse/ACQE-6695) - TierPricingWhenPriceScopeIsWebsiteWorkingProperlyWithMultipleCurrenciesConfiguredTest
[AC-12714](https://jira.corp.adobe.com/browse/AC-12714) - StorefrontLoginFormCheckDuplicateValidateMessageTest
[ACQE-6886](https://jira.corp.adobe.com/browse/ACQE-6886) - StorefrontVerifyMultipleProductRatingsOnCategoryPageTest
[ACQE-6350](https://jira.corp.adobe.com/browse/ACQE-6350) - AdminCreateDraftQuoteFromQuoteGridPageWithMultipleStoresTest

**Functional Tests EE:**
**Run 1:**
image

**Run 2:**
image

Known issues:
[ACQE-6695](https://jira.corp.adobe.com/browse/ACQE-6695) - TierPricingWhenPriceScopeIsWebsiteWorkingProperlyWithMultipleCurrenciesConfiguredTest
[AC-12714](https://jira.corp.adobe.com/browse/AC-12714) - StorefrontLoginFormCheckDuplicateValidateMessageTest
[ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331) - StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest

**Functional Tests CE:**
**Run 1:**
image

**Run 2:**
image

**Known issues:**
[ACQE-6695](https://jira.corp.adobe.com/browse/ACQE-6695) - TierPricingWhenPriceScopeIsWebsiteWorkingProperlyWithMultipleCurrenciesConfiguredTest
[ACQE-6774](https://jira.corp.adobe.com/browse/ACQE-6774) - StorefrontCashOnDeliveryPaymentForSpecificCountryTest

Hence moving this to **Merge in Progress**.

**Pull request merged**
