### PR TITLE
Update UrlRewriteCollection.php

### LINKED ISSUE #31853: UrlRewriteCollection store_id filter may be ambiguous
### Summary (*)

The collection `app/code/Magento/UrlRewrite/Model/ResourceModel/UrlRewriteCollection.php` has a function `addStoreFilter`, the problem here is that the filter is being added without table reference on `store_id`.

That may be a problem on extensibility whenever a join is added to the collection on a table that also has a `store_id` column.

### Examples (*)
Add a plugin that adds a join to this collection from a table that has `store_id` column.

### Proposed solution
Add main_table reference to the `store_id` on `addStoreFilter` function.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by ghost**
Fix:

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/31853

### Manual testing scenarios (*)

1. Save product in catalog without error
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by achatpc** [comment]
I don't know if this helps, but not being the only one having this problem, I think it's useful to share how it was fixed on my end.

**Comment by achatpc** [comment]
@magento run all tests

**Review by Stepa4man — CHANGES_REQUESTED** [review]
Hi @achatpc 
Thanks for your contribution.

Could you please also fix Unit test here?
`Magento\UrlRewrite\Test\Unit\Model\ResourceModel\UrlRewriteCollectionTest`

Thanks in advance.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run WebAPI Tests

**Review by ghost — COMMENTED** [review]
work for me

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Review by Stepa4man — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passsed
Was tested functionality related to URL Rewrites and everything works as expected.

**Pull request merged**
