### PR TITLE
\Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend must not filter non numeric values

### LINKED ISSUE #37675: EAV attribute backend model 'ArrayBackend' filters non numeric values
### Preconditions and environment

- Magento ^2.4.6

### Steps to reproduce

1. Create a new product attribute eg 'foobar' with
 - a `\Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend` backend model
 - a custom source model which has non numeric option values
2. Save the product with changed attribute 'foobar' values (eg through a REST API call)

### Expected result

Changed/new attribute values are saved to the product.

### Actual result

Attribute values are not saved

### Additional information

The non numeric values are filtered here and won't be saved:
https://github.com/magento/magento2/blob/2.4.6/app/code/Magento/Eav/Model/Entity/Attribute/Backend/ArrayBackend.php#L67

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by DiskoPete**
### Description (*)
This pull request fixes an issue where the `\Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend` eav attribute backend model filters non numeric values.

### Fixed Issues
1. Fixes magento/magento2#37675

### Manual testing scenarios (*)
1. Create a new product attribute eg 'foobar' with
  - \Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend backend model
 - custom source model which has non numeric option values
2. Save the product with changed attribute 'foobar' values (eg through a REST API call)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by DiskoPete** [comment]
@magento run all tests

**Review by abukatar — CHANGES_REQUESTED** [review]
Please rerun the tests and fix issues caused by your changes.

**Comment by abukatar** [comment]
Hello @DiskoPete 

Thank you for your contribution and collaboration!

An internal Magento team is working on this issue right now.
Please re-run the automatic tests and resolve issues related to your fix

**Comment by hostep** [comment]
It seems like this made it into the core by https://github.com/magento/magento2/commit/2d5c94623a986f3b31c4f94a85e577e1052eba7a

The author of this PR was indeed kept in git history as we can see here: https://github.com/magento/magento2/commits/bbd5612/app/code/Magento/Eav/Model/Entity/Attribute/Backend/ArrayBackend.php

So, I think this PR can be closed now?

**Comment by engcom-Dash** [comment]
Hello @DiskoPete ,

Thanks for the contributions!

Please resolve the conflict so we can proceed with this PR.

Thanks.

**Comment by DiskoPete** [comment]
Hello @engcom-Dash 

The conflict is solved

**Comment by engcom-Dash** [comment]
Hello @DiskoPete,

Thanks for your contributions!

It appears that the changes were already added in commit 2d5c946. Therefore, I’ll be closing this PR for now.

For more details, please refer to https://github.com/magento/magento2/pull/37677#issuecomment-1919945115.

Thanks again!

**Pull request closed without merging**
