### PR TITLE
[Fixed] - SalesRule module collection missing event prefix

### LINKED ISSUE #30588: SalesRule module collection missing event prefix
### Preconditions

1. Magento 2.3.0 CE

### Steps to reproduce

1. Try to observe events: salesrule_rule_collection_load_before, salesrule_rule_collection_load_after

### Expected result

1. Event is dispatched and listeners execute

### Actual result

1. Listeners aren't executed because the collection is missing the event prefix

Code lines to reproduce:
```
/* @var \Magento\SalesRule\Model\ResourceModel\Rule\Collection $collection */
$collection = $this->_objectManager
    ->create(\Magento\SalesRule\Model\ResourceModel\Rule\Collection::class);
$collection->load();
```
Proposed fix by adding following lines to  \Magento\SalesRule\Model\ResourceModel\Rule\Collection:
```
    /**
     * Event prefix
     *
     * @var string
     */
    protected $_eventPrefix = 'salesrule_rule_collection';
    /**
     * Event object
     *
     * @var string
     */
    protected $_eventObject = 'rule_collection';
```

### PR DESCRIPTION
**Pull request by niravkrish**
### Description (*)

Added missing event prefix in the sales_rule collection class.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30588

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8365](https://jira.corp.magento.com/browse/ENGCOM-8365) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi, @niravkrish thanks for your contribution. Can you please have a look at the static test failures?

Thanks

**Comment by gabrieldagama** [comment]
@magento run Functional Tests CE,Functional Tests EE,Integration Tests

**Comment by engcom-Charlie** [comment]
Hi, @niravkrish please fix static test failures. Otherwise, we can't proceed with your PR.
Thank you.

**Comment by engcom-Charlie** [comment]
Hi, @niravkrish could you please fix `Static Tests` failures?
Thank you.

**Comment by engcom-Charlie** [comment]
@niravkrish I'll fix test failures.

**Comment by engcom-Charlie** [comment]
@magento run Static Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by niravkrish** [comment]
Hi @gabrieldagama,

How can I solve the Semantic Version Checker Error?
Currently, the setup_version is deprecated and not available for this module.

Thanks & Regards,
Nirav Patel

**Review by gabrieldagama — APPROVED** [review]
Hi @niravkrish, thanks for updating the PR!

The SVC tests don't need to be fixed, just approved. We will handle that during the delivery process.

Thanks for contributing!

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8365](https://jira.corp.magento.com/browse/ENGCOM-8365) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
QA not applicable

**Comment by engcom-Charlie** [comment]
:heavy_check_mark: QA Passed
**Before**: 
here is no dispatch specially event for loading `\Magento\SalesRule\Model\ResourceModel\Rule\Collection`.
Only general `core_collection_abstract_load_before` was dispatched.

**After**
here are dispatch general `core_collection_abstract_load_before` and `salesrule_rule_collection` event for load before(+ `_load_before`) and after (+ `_load_after`) for `\Magento\SalesRule\Model\ResourceModel\Rule\Collection`.

**Comment by engcom-Charlie** [comment]
Need to approve because two protected properties were added in `\Magento\SalesRule\Model\ResourceModel\Rule\Collection`.

**Comment by gabrieldagama** [comment]
Approval ticket created: https://jira.corp.magento.com/browse/MC-39099

**Comment by engcom-Alfa** [comment]
Hi @niravkrish Thanks for your contribution and collaboration
Apologies for picking this ticket back very late.
Since it is an old ticket and required to validate its QA analysis. Kindly help us with the exact steps to reproduce the issue, that has been fixed here.
Kindly mention if there is any pre-conditions are applied. Also help me with what is the expected and what is the actual result currently.
Thanks in advance!

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @niravkrish Thanks for your contribution and collaboration
Apologies for picking this ticket back very late.
Since it is an old ticket and required to validate its QA analysis. Kindly help us with the exact steps to reproduce the issue, that has been fixed here.
Kindly mention if there is any pre-conditions are applied. Also help me with what is the expected and what is the actual result currently.
Thanks in advance!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE, WebAPI Tests

**Comment by engcom-Charlie** [comment]
Merged latest Magento develop in this PR branch and tried to reproduce the issue and tested the provided solution.

**Preconditions**
In order to reproduce this issue added below code in custom controller.

```
$collection = $this->_objectManager
    ->create(\Magento\SalesRule\Model\ResourceModel\Rule\Collection::class);
$collection->load();
```

**Actual Result:**
Listeners aren't executed because the collection is missing the event prefix.  salesrule_rule_collection_load_before, salesrule_rule_collection_load_after was not getting executed.

**Expected Result:** 
Listeners are executed because the collection’s event prefix “salesrule_rule_collection” have been added.
image

The PR fix is working fine. 
 
Build were failing previously, implemented the fix for static test failures.

As the build is successful now moving it further.

Thank you!

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

This PR is relevant to the dev triaged. As per the above-comment we have done with our testing and PR changes worked well.
Hence moving this ticket to _Merge In Progress_.

**Pull request merged**
