### PR TITLE
Add back extension point for adding some html to the category page

### LINKED ISSUE #29286: Add back extension point for adding some html to the category page
### Summary (*)
In PR https://github.com/magento/magento2/pull/24728 there was done one change that caused method `getProductDetailsHtml ` and all their methods stopped to be executed at all that prevents adding customizations here.

During investigation why it was done - it was done due to issue in Swatches module, but fix was done actually in catalog.

I described it in https://github.com/magento/magento2/pull/24728#issuecomment-664219144

### Examples (*)
We need to add some HTML to the product listing page (category page), for instance some product label.

### Proposed solution
Move additional check from catalog module to the Swatches module.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by iGerchak**
### Description (*)
Moved check from the catalog to the swatches module in order to add back the extension point.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#29286

### Manual testing scenarios (*)

1. See https://github.com/magento/magento2/pull/24728 and magento/magento2#29286

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by iGerchak** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Oh, thx for fixing it so quickly

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@iGerchak please fix static tests

**Comment by iGerchak** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run static test

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7911](https://jira.corp.magento.com/browse/ENGCOM-7911) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Set configurable product out of stock, make sure the child is in stock;
2. Display Out of Stock Products set to Yes;
3. select color witch available in the configurable product;

**Actual Result:**

:heavy_check_mark:  listing page not showing swatch for out of stock product same as on product detail page



and everything related to the swatch functionality was also checked

**Pull request merged**
