### PR TITLE
Set fallback values for email and _website columns to avoid 'undefined index' error in CustomerComposite.php

### PR DESCRIPTION
**Pull request by TomashKhamlai**
### Description (*)
There are proper validation messages for `ERROR_CODE_COLUMN_NOT_FOUND` and `ERROR_CODE_COLUMN_NAME_INVALID` but this code is not reachable.

### Fixed Issues (if relevant)
1. None, please, look into manual testing scenarios

### Manual testing scenarios (*)
1. Create a Customer
2. Navigate to **Customers -> All Customers** and export them all
3. Navigate to **System -> Import** and use the CSV of all your customers. Use Add/Update behavior and "Customers and Addresses (single file)" as an entity type.

**Expected result:**
At least one of the two validation messages:

`We can't find required columns: email", "_website.`

`Column names: "ID", "Name", "Email", "Group", "Phone", "ZIP", "Country", "State/Province", "Customer Since", "Web Site", "Confirmed email", "Account Created in", "Billing Address", "Shipping Address", "Date of Birth", "Tax VAT Number", "Gender", "Street Address", "City", "Fax", "VAT Number", "Company", "Billing Firstname", "Billing Lastname", "Account Lock" are invalid`

**Actual result:**
`Notice: Undefined index: email in /var/www/html/pr/app/code/Magento/CustomerImportExport/Model/Import/CustomerComposite.php on line 302`

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18679) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by TomashKhamlai** [comment]
Hello, @rogyar. Few days ago I reinstalled the system om my workstation and git was not properly configured. Git used my unix-system username tkhamlai@dagento.dagento.tsg as email to sign my commit message, as a result I am not able to sign the CLA.. Is it a good idea to reset to unchanged state, then merge upstream, then apply changes as a patch and force push into my fork branch?

**Comment by ihor-sviziev** [comment]
@TomashKhamlai sure! Please do that!

**Comment by TomashKhamlai** [comment]
@ihor-sviziev done.

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
