### PR TITLE
Fixed Issue #35900: Allow "Show all products" in category page

### LINKED ISSUE #35900: Catalog Page Empty if "Allow All Products Per Page" is set to "Yes"
### Preconditions and environment

- Magento 2.4.5

### Steps to reproduce

Deploy 2.4.5 vanilla
Create Test Category
Create Test Product in test category
Browse to test category page on frontend and ensure product is visible.
Set Allow All Products Per Page setting (Config -> Catalog -> Catalog) to Yes
image

Clear Cache
Browse to test category page on frontend and ensure product is visible.

### Expected result

Product is visisble
image

### Actual result

Product is not visible
image

### Additional information

_No response_

### Release note

The Category Page is no longer empty when "Allow All Products Per Page" is set to "Yes".

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Bashev**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#35900

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Bashev** [comment]
@magento give me test instance

**Comment by Bashev** [comment]
@magento run all tests

**Comment by Bashev** [comment]
@magento run Functional Tests B2B

**Comment by Bashev** [comment]
@magento run Functional Tests B2B

**Comment by Bashev** [comment]
@magento run Functional Tests B2B

**Comment by Bashev** [comment]
@magento run Functional Tests B2B

**Comment by Bashev** [comment]
Resolved internally.

**Comment by JoergLindner** [comment]
Sorry, this is not a complete fix, as it shows now all products even if they are marked as 'search', which suppose to be shown only while searching it, not by just looking into a category. Here it should only shown products with 'catalog,search' or 'catalog' setting!

**Pull request closed without merging**
