### PR TITLE
Fixed: Placing order in Admin for more stock than is available is allowed and does not show error.

### PR DESCRIPTION
**Pull request by mahesh-rajawat**
…owed and does not show error

Fixed issue: Placing order in Admin for more stock than is available is allowed and does not show error

### Description (*)

Fixed Admin Created order more than available quantity. 
### Fixed Issues (if relevant)

1. #24365 

### Manual testing scenarios (*)

**Issue 1**
1. Create Test Product, in stock, Qty 10
2. Create Test Customer
3. Create Test Order in Adminhtml. Assign Test Customer.
4. Add a product with more than half quantity 6 and total available 10.
5. Now no warning message appearing.

**Issue 2**
1. Create Test Product, in stock, Qty 10
2. Create Test Customer
3. Create Test Order in Adminhtml. Assign Test Customer.
4. Add a product with more than the available 12.
5. Now error message appearing and admin can not submit the order.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mahesh-rajawat** [comment]
@magento-engcom-team, i am getting the functional test failed due to this issue #10702, In this Functional test bundle product is creating with scope 1, and this line `https://github.com/magento/magento2/blob/2f60bd15d65ff8fe961b9b6d844adcef2e2f00f2/app/code/Magento/CatalogInventory/Model/Quote/Item/QuantityValidator.php#L136` its fetching the stock status with website id 1. Let me know if i need to proceed further?

**Comment by mahesh-rajawat** [comment]
@magento-engcom-team , you need to look in to this.

**Comment by mahesh-rajawat** [comment]
@sidolov could you please look into it?

**Comment by mahesh-rajawat** [comment]
@magento-engcom-team could you please suggest me reagarding functional test faluire?

**Comment by mahesh-rajawat** [comment]
@magento-engcom-team any update on it?

**Comment by sidolov** [comment]
@maheshWebkul721 looks like the issue was fixed in scope of commit 52604a6bc6cf79facaf1873ec6f45249ee3a0704. 
I'm closing the PR as not relevant, please, feel free to reopen it if you find one more case. Thank you for the collaboration!

**Pull request closed without merging**
