### PR TITLE
404 not found form validation url when updating quantity in cart page

### PR DESCRIPTION
**Pull request by gulshanchitransh**
404 not found form validation url when updating item quantity in cart page

### Description (*)
404 not found form validation url when updating item quantity in cart page

### Manual testing scenarios (*)
1. Add product to cart
2. Go to cart page
3. Edit any item quantity and click update shopping cart button.
4. Cart form validation request goes to 404 url

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22657) <br/>All committers have signed the CLA.

**Comment by rogyar** [comment]
Hi @gulshanchitransh. Thank you for your collaboration. I cannot reproduce this issue somehow. Maybe it appears under some particular circumstances. However, the provided way of getting URL of validation endpoint is much better than the existing hardcoded value.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-5069](https://jira.corp.magento.com/browse/ENGCOM-5069) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
