### PR TITLE
 PaymentTokenRepositoryInterface: missing setTotalCount in getList() method

### PR DESCRIPTION
**Pull request by textarea**
Missing setTotalCount method on \Magento\Vault\Model\PaymentTokenRepository->getList method

### Description (*)
added setTotalCount($collection->getSize() on $searchResults return object

### Fixed Issues (if relevant)

1. magento/magento2#19706: PaymentTokenRepositoryInterface: missing setTotalCount in getList() method

### Manual testing scenarios (*)

/** @var \Magento\Vault\Api\PaymentTokenRepositoryInterface */
echo $this->paymentTokenRepository->getList(
$this->searchCriteriaBuilder->create()
)->getTotalCount();

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19707) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @textarea. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by okorshenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [new Magento instance](https://pr-19707.instances.magento-community.engineering).
Admin access: [https://pr-19707.instances.magento-community.engineering/admin](https://pr-19707.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by okorshenko** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [Magento instance](https://i-19707-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19707-2-3-develop.instances.magento-community.engineering/admin](https://i-19707-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3675](https://jira.corp.magento.com/browse/ENGCOM-3675) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@textarea thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @textarea. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
