### PR TITLE
Fixing bug with non-existent customer group breaking quote

### LINKED ISSUE #29327: [Issue] Fixing bug with non-existent customer group breaking quote
This issue is automatically created based on existing pull request: magento/magento2#28902: Fixing bug with non-existent customer group breaking quote

---------
### Preconditions (*)

There's a bug when a customer group deleted, it's still referenced in active quotes which causes an error on the checkout page.
Such a quote becomes broken and the customer is not able to place an order. This pull request adds functionality for getting customer group from the current customer in case customer group saved to the quote does not exist.

### Steps to reproduce (*)

1. Create a new customer group.
2. Create a new customer. Link that customer to the customer group created on the previous step.
3. Log in to the Magento storefront and add some products to the shopping cart.
4. Go to the admin and delete the customer group created on step 1.
5. Return to the storefront and proceed to checkout.

 **Actual result:** :heavy_multiplication_x:  an error "No such entity id = ... " displayed. Shipping methods are not rendered.
missin_customer_group

 **Expected result:** :heavy_check_mark: a customer should be able to complete an order without any issue.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kodubovik**
### Description (*)

There's a bug when a customer group deleted, it's still referenced in active quotes which causes an error on the checkout page.
Such a quote becomes broken and the customer is not able to place an order. This pull request adds functionality for getting customer group from the current customer in case customer group saved to the quote does not exist.

### Manual testing scenarios (*)

1. Create a new customer group.
2. Create a new customer. Link that customer to the customer group created on the previous step.
3. Log in to the Magento storefront and add some products to the shopping cart.
4. Go to the admin and delete the customer group created on step 1.
5. Return to the storefront and proceed to checkout.
* Expected result: a customer should be able to complete an order without any issue.
* Actual result: an error "No such entity id = ... " displayed. Shipping methods are not rendered.
missin_customer_group

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29327: Fixing bug with non-existent customer group breaking quote

### CODE REVIEW

**Comment by kodubovik** [comment]
@magento run all tests

**Comment by swnsma** [comment]
@magento run all tests

**Comment by kodubovik** [comment]
@magento run all tests

**Comment by swnsma** [comment]
@magento run all tests

**Review by swnsma — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-7793](https://jira.corp.magento.com/browse/ENGCOM-7793) has been created to process this Pull Request
:eight_spoked_asterisk: @swnsma, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @kodubovik 

Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) all changes should be covered by automated tests. 
Could you please cover your fix by a [MFTF](https://devdocs.magento.com/mftf/docs/getting-started.html) test?
Thank you.

**Comment by kodubovik** [comment]
@magento run all tests

**Comment by kodubovik** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Comment by kodubovik** [comment]
@magento run Functional Tests B2B

**Comment by kodubovik** [comment]
@magento run Functional Tests B2B

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-7793](https://jira.corp.magento.com/browse/ENGCOM-7793) has been created to process this Pull Request

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Create a new customer group;
2. Create a new customer. Link that customer to the customer group created on the previous step.
3. Log in to the Magento storefront and add some products to the shopping cart.
4. Go to the admin and delete the customer group created on step 1.
5. Return to the storefront and proceed to checkout.

**Before:** :heavy_multiplication_x: an error "No such entity id = ... " displayed. Shipping methods are not rendered.

Screenshot from 2020-07-28 10-49-13

**After:** :heavy_check_mark: Shipping methods are rendered and the order was successfully created with the default customer group

Screenshot from 2020-07-28 11-18-33

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by swnsma** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Pull request merged**
