### PR TITLE
Fix Ui-Select (Multiselect) close button issues (cont.)

### LINKED ISSUE #34338: [Issue] Fix Ui-Select (Multiselect) close button issues (cont.)
This issue is automatically created based on existing pull request: magento/magento2#33948: Fix Ui-Select (Multiselect) close button issues (cont.)

---------

### Description (*)

Fix active state of multiselect close button, missed in scope of previous PR 

### Related Pull Requests

magento/magento2#33098

### Manual testing scenarios (*)

1. Create form ui component with modal.
2. Add ui-select field with default settings in modal.
3. Check that active (click) state behaviour is consistent.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by LyraGhost**
### Description (*)

Fix active state of multiselect close button, missed in scope of previous PR 

### Manual testing scenarios (*)

1. Create form ui component with modal.
2. Add ui-select field with default settings in modal.
3. Check that active (click) state behaviour is consistent.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#34338: Fix Ui-Select (Multiselect) close button issues (cont.)

### CODE REVIEW

**Comment by LyraGhost** [comment]
@magento run all tests

**Comment by BarnyShergold** [comment]
@magento run Database Compare

**Review by BarnyShergold — APPROVED** [review]
This looks fine but some of the tests are failing for no apparent reason. Will try running a few and keep an eye on.

**Comment by magento-engcom-team** [comment]
Hi @BarnyShergold, thank you for the review.
[ENGCOM-9206](https://jira.corp.magento.com/browse/ENGCOM-9206) has been created to process this Pull Request
:eight_spoked_asterisk: @BarnyShergold, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by BarnyShergold** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B,Integration Tests

**Comment by BarnyShergold** [comment]
@magento run Functional Tests B2B

**Comment by LyraGhost** [comment]
@magento run Functional Tests B2B

**Comment by BarnyShergold** [comment]
@magento run Functional Tests B2B

**Comment by BarnyShergold** [comment]
@LyraGhost - yay all tests passed :)

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
> 3. Check that active (click) state behaviour is consistent.

Hello @LyraGhost,

Thanks for the contribution!

Please let us know which kind of inconsistency you are mentioning here. Also, It will helpful for us to test this PR if you provide us the actual and expected results (with screenshots if possible).

Thanks

**Comment by LyraGhost** [comment]
before (clicking, active state):
image

after (clicking, active state):
image

active state was inconsistent with default behavior
see related PR for more testing scenarios

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by BarnyShergold** [comment]
@magento run Functional Tests B2B,Functional Tests EE

**Comment by BarnyShergold** [comment]
@magento run Functional Tests B2B,Functional Tests EE

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests EE

**Comment by engcom-Alfa** [comment]
Hi @LyraGhost and @BarnyShergold 
Thanks for your contribution and collaboration!

Executing failed job "Functional Tests EE", Let me give a few tries. All jobs should pass before moving this PR forward!

Thanks for your patience!

**Pull request merged**
