### PR TITLE
checkout_index_index.xml file code improvement.

### LINKED ISSUE #30550: [Issue] checkout_index_index.xml file code improvement.
This issue is automatically created based on existing pull request: magento/magento2#30538: checkout_index_index.xml file code improvement.

---------

### Description (*)

Removed **sortOrder** from **messages, authentication, progressBar, estimation, and sidebar checkout components** as they are already been rendered without those sortOrders and individual getRegions at `app/code/Magento/Checkout/view/frontend/web/template/onepage.html`

### Fixed Issues (if relevant)

1. This is code improvement.

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by sanganinamrata**
### Description (*)

Removed **sortOrder** from **messages, authentication, progressBar, estimation, and sidebar checkout components** as they are already been rendered without those sortOrders and individual getRegions at `app/code/Magento/Checkout/view/frontend/web/template/onepage.html`

### Fixed Issues (if relevant)

1. This is code improvement.

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30550: checkout_index_index.xml file code improvement.

### CODE REVIEW

**Comment by rogyar** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
@magento give me test instance

**Comment by sidolov** [comment]
@magento create issue

**Comment by rogyar** [comment]
@magento run Integration Tests

**Review by ptylek — APPROVED** [review]
Currently it gives wrong impression that changing sortOrder could have any impact for changing those checkout components order. Adding Auto-Tests: Not Required label as removing these sortOrders doesn't change anything - components are displayed with getRegion().

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-8370](https://jira.corp.magento.com/browse/ENGCOM-8370) has been created to process this Pull Request
:eight_spoked_asterisk: @ptylek, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by sanganinamrata** [comment]
@ptylek, Will you please add `hacktoberfest-accepted` label to this PR? This event is about to finish. Without this label to my PR, I'll be eliminated from that challenge. :)

**Comment by ptylek** [comment]
@sanganinamrata all approved/merged PRs should be counted for the hacktoberfest, afaik label is only added if they can't be approved/merged before the end of October

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

This is code improvement. The order of sorting components has not been changed. 
Everything work as previously (expected).

**Pull request merged**
