### PR TITLE
issue fixed #20163 On iPhone5 device newsletter subscription input bo…

### LINKED ISSUE #20163: On iPhone5 device newsletter subscription input box not contain complete text (placeholder)
On iPhone device newsletter subscription input box not contain complete text (placeholder) 

### Preconditions (*)

1.Issue is arises is 2.5 version 2.3 version of magneto on iPhone device

### Steps to reproduce (*)

1.Go to iphone5 device and check newsletter subscription block above footer 

### Expected result (*)

2019-01-10_16-11_create new customer account

### Actual result (*)

2019-01-10_16-19_about us

### PR DESCRIPTION
**Pull request by cedarvinda**
…x not contain complete text (placeholder)

issue fixed #20163 On iPhone5 device newsletter subscription input box not contain complete text (placeholder)

### Description (*)

On iPhone device newsletter subscription input box not contain complete text (placeholder)

### Manual testing scenarios (*)

1.Go to iphone5 device and check newsletter subscription block above footer

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
Hi @cedarvinda , thanks for your contribution! The PR specifies the custom `font-size` for mobile, can you please ensure the default font size is still used on desktop.

**Comment by cedarvinda** [comment]
@sivaschenko Thankyou for review... I will update the font-size in media query.

**Comment by cedarvinda** [comment]
@sivaschenko Now updated _module.less using media query.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3992](https://jira.corp.magento.com/browse/ENGCOM-3992) has been created to process this Pull Request

**Pull request merged**
