### PR TITLE
reward-points-notifications-not-proper

### PR DESCRIPTION
**Pull request by priti2jcommerce**
### Description (*)
2.3.0 (enterprise)

### Fixed Issues (if relevant)

1. magento/magento2#20444 : Issue title
2. ...

### Manual testing scenarios (*)

1. Go to admin >> Customer >>All customer
2. Edit 
3. click on Reward Points

### Expected result (*)

1. 
image

2.

### Actual result (*)

1. image

2.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by priti2jcommerce** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce, here is your [Magento instance](https://i-20446-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20446-2-3-develop.instances.magento-community.engineering/admin](https://i-20446-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sivaschenko** [comment]
Hi @priti2jcommerce thanks for the pull request! However, the styles for reward point should be added to Magento_Reward scope of design and the pull request should be opened towards Magento Commerce repository.

Feel free to contact me if you need any help with that.

**Comment by sivaschenko** [comment]
@priti2jcommerce Looks like the issue is already fixed: see https://github.com/magento/magento2/issues/20444#issuecomment-476376830

**Pull request closed without merging**
