### PR TITLE
fix wrong resource model used for category when using flat tables

### PR DESCRIPTION
**Pull request by OZZlE**
This Observer calls saveAttribute on a resource model that does not have that function.

Changed so it uses the correct resource model.

### Description
fix for:
`[Thu May 18 16:27:38.170239 2017] [:error] [pid 9931] [client 46.21.96.82:40436] FastCGI: server "/usr/sbin/php-fpm7.0" stderr: PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Magento\\Catalog\\Model\\ResourceModel\\Category\\Flat::saveAttribute() in ../htdocs/vendor/magento/module-catalog-url-rewrite/Observer/CategoryUrlPathAutogeneratorObserver.php:54, referer: https://.../custom-fit-guide/richtige-golfgriffe-fur-sie?edit=1&store_id=9

[Thu May 18 16:27:38.170283 2017] [:error] [pid 9931] [client 46.21.96.82:40436] FastCGI: server "/usr/sbin/php-fpm7.0" stderr: Stack trace:, referer: .../custom-fit-guide/richtige-golfgriffe-fur-sie?edit=1&store_id=9
[Thu May 18 16:27:38.170288 2017] [:error] [pid 9931] [client 46.21.96.82:40436] FastCGI: server "/usr/sbin/php-fpm7.0" stderr: #0 .../2017-04-18_10-30-55/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): Magento\\CatalogUrlRewrite\\Observer\\CategoryUrlPathAutogeneratorObserver->execute(Object(Magento\\Framework\\Event\\Observer)), referer: .../custom-fit-guide/richtige-golfgriffe-fur-sie?edit=1&store_id=9

[Thu May 18 16:27:38.170293 2017] [:error] [pid 9931] [client 46.21.96.82:40436] FastCGI: server "/usr/sbin/php-fpm7.0" stderr: #1 .../2017-04-18_10-30-55/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod(Object(Magento\\CatalogUrlRewrite\\Observer\\CategoryUrlPathAutogeneratorObserver), Object(Magento\\Framework\\Event\\Observer)), referer: .../custom-fit-guide/richtige-golfgriffe-fur-sie?edit=1&store_id=9

[Thu May 18 16:27:38.170298 2017] [:error] [pid 9931] [client 46.21.96.82:40436] FastCGI: server "/usr/sbin/php-fpm7.0" stderr: #2 .../2017-04-18_10-30-55/htdocs/vendor/magento/framework/Event/Manager.php(66): Magento\\Framework\\Event\\Invoker\\InvokerDefault->dispatch(Array, Objec..., referer: .../custom-fit-guide/richtige-golfgriffe-fur-sie?edit=1&store_id=9`

### CODE REVIEW

**Comment by OZZlE** [comment]
test case in travis is not valid as it "verifies" a broken implementation..

**Comment by OZZlE** [comment]
@kassner I fixed the test cases so it passes now but wasn't able to extend the test case, so if you want you can do it

**Comment by maghamed** [comment]
It's very similar issue as we have in the scope of PR 
https://github.com/magento/magento2/pull/8256
when we are trying to write data into the Flat table.

Writing into the Flat table violates the CQRS approach, and should be forbidden.
At this stage we need to have dedicated Exception which will show the error at earliest possible stage

**Comment by okorshenko** [comment]
Hi @OZZlE thank you for your Pull Request. 
Closing this PR.
Please consider comment from @maghamed

**Comment by OZZlE** [comment]
@maghamed not sure I am getting this.. the current M2 implementation is using a function that does not exist (saveAttribute) in that Class throwing a fatal error. I have only changed so it uses \Magento\Catalog\Model\ResourceModel\Category class to save the attribute instead.

Why would that it will save it directly to flat tables? Doesn't make sense.. Anyhow not my problem here :D if that indeed really happens.. which I have a hard time understanding..

**Comment by OZZlE** [comment]
@okorshenko I don't believe this is correct.. current implementation uses a function that does not exist when you have flat tables enabled and throws a fatal error. Only reason that this class passes it's test cases is because it doesn't cover this scenario at all.. 

I don't get why changing to the correct SourceModel should violate the CQRS approach..

**Pull request closed without merging**
