### PR TITLE
Fix issue with saving filters from url-applier to default view of bookmark

### LINKED ISSUE #1789: Bookmark saves filter from url-applier component to default view in some cases
### Preconditions (*)
Have an image that used in categories

### Steps to reproduce (*)
1. Open media gallery
2. Open view details from image
3. Click on Used in Categories link
4. Category grid rendered with url-filter applier, and asset filter applied

### Expected result (*)
1. Default view of bookmark saved without filter

### Actual result (*)
1. Default view sometime contains filter that were applied from url-filter applier

**Its depends on js initialization, the url filter applier must apply filters after the bookmark saves default view on grid initalization in case if  grid contains bookmark component.**

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1789

### Manual testing scenarios (*)
1. Open media gallery
2. Open view details from image
3. Click on Used in Categories link
4. Category grid rendered with url-filter applier, and asset filter applied

1. Default view of bookmark saved without filter

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by rogyar** [comment]
Hi @sivaschenko. Just want to double-check that we are on the same page. 
You've added the "Auto-Tests: Covered" label with no actual coverage introduced in this PR. Does it mean that the change in this PR is supposed to fix the existing failing test? 

Thank you.

**Comment by Nazar65** [comment]
@rogyar failing test is not related to the changes in this pr, also this behaviour already covered by mftf test.

**Comment by rogyar** [comment]
Hi @Nazar65. Thank you for the clarification. 
I mean, if we provide a fix and it's already covered by MFTF tests, usually it means that without the provided fix the tests are supposed to be failing. So the fix eventually fixes the previously failing tests. 

If this assumption is correct for the current PR, that's great.

Thanks

**Comment by sidolov** [comment]
@sivaschenko , @Nazar65  could you please clarify the automation status? I agree with @rogyar , if we are going to fix something- it should be covered with a test. If test is already created then why it's green since we have a bug in functionality?

**Comment by Nazar65** [comment]
@sidolov this fixes bug with js initialization, so covering such functionality with tests is no giid idea, because we will introduce one more fkajy test, and in this case thr ui_bookmark tabke also needs tobbe empty.

**Comment by sivaschenko** [comment]
@sidolov @rogyar the PR contains an improvement to stability of the functionality that is covered by MFTF tests.

In case there is a PR that contains refactoring or implementation change to existing functionality that is covered by MFTF tests, such PR is covered with tests even if does not change the test results.

**Comment by sivaschenko** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-8147](https://jira.corp.magento.com/browse/ENGCOM-8147) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

The Default view doesn't contain any bookmarks, it is empty as expected

Manual testing scenario - https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/5115557

**Comment by sivaschenko** [comment]
Already merged to 2.4.1-develop.

**Pull request merged**
