### PR TITLE
MC-37941: There is no space between rating stars and a review text in the case of long rating name

### LINKED ISSUE #31890: There is no space between rating stars and a review text in the case of  long rating name
**Preconditions:**
* Magento EE 2.4.0, EE 2.4.1 is installed
* A Simple Product is created
* Go to Magento Admin > Stores > Attributes > Ratings
* Open “Price” rating
* Default Value = Default Store View Price
* Default Store View = Default Store View Price
* Select “Default Store View” in the “Rating Visibility“ section
* Click “Save Rating” button
* Repeat above-mentioned steps for all available ratings

**Steps to Reproduce:**
* Go to the Storefront as a guest
* Go to the created Product page
* Click the “Be the first to review this product” link
* Select 5 stars for an each rating
* Fill all required fields with a valid data
* Click  the “Submit Review” button
* Go to the Magento Admin panel > MARKETING > User Content > Pending Reviews
* Check the submitted review check-box
* Select the “Update Status” option in the “Action” drop-down
* Select the “Approved” option in the appeared “Status” drop-down
* Click the “Submit” button
* Go to the Storefront as a guest again
* Go to the created Product page
* Scroll down the page to the "Customer Reviews" section

**(/) Expected results:**

There should be a space between rating stars and a review text

*(see the attached EE 2.4.1. REWIEW SPACE RATING EXPECTED.png)*

**(x) Actual results:**

There is no space between rating stars and a review text

*(see the attached EE 2.4.1. REWIEW SPACE RATING ACTUAL.png)*

### PR DESCRIPTION
**Pull request by viktorpetryk**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#31890

### Manual testing scenarios (*)

see magento/magento2#31890

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by victorpetryk** [comment]
@magento run all tests

**Comment by victorpetryk** [comment]
@magento run Functional Tests B2B

**Comment by victorpetryk** [comment]
@magento run all tests

**Comment by victorpetryk** [comment]
@magento run Functional Tests B2B

**Comment by victorpetryk** [comment]
@magento run Functional Tests CE

**Comment by victorpetryk** [comment]
@magento run Functional Tests CE

**Comment by victorpetryk** [comment]
@magento run Functional Tests B2B

**Comment by victorpetryk** [comment]
@magento run all tests

**Review by engcom-Kilo — APPROVED** [review]

**Comment by engcom-Oscar** [comment]
:heavy_check_mark: QA passed
Was checked case from Manual testing scenario 
:x: **Before:**
Screenshot from 2021-02-02 11-38-40

:heavy_check_mark: **After:**
Screenshot from 2021-02-02 11-39-39

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31892`.

**Pull request merged**
