### PR TITLE
Add checkout_cart_product_add_before event #17830

### PR DESCRIPTION
**Pull request by leandro-rosa**
Add checkout_cart_product_add_before event [#17830](https://github.com/magento/magento2/issues/17830)

### Description
Add dispatch event checkout_cart_product_add_before

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18080) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @leandro-rosa. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-engcom-team** [comment]
@leandro-rosa thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by okorshenko** [comment]
Hi @leandro-rosa 
Could you please fix broken tests so that we can proceed with PR acceptance. We agreed to accept new event

Thank you

**Comment by sidolov** [comment]
Hi @leandro-rosa , will you continue work with PR? 
Thank you!

**Comment by magento-engcom-team** [comment]
Hi @leandro-rosa. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
