### PR TITLE
Generated code is not consistent with Magento requirements and Coding Standard

### LINKED ISSUE #28376: [Issue] Generated code is not consistent with Magento requirements and Coding Standard
This issue is automatically created based on existing pull request: magento/magento2#28351: Generated code is not consistent with Magento requirements and Coding Standard

---------
### Preconditions:
If you generate Patch using Magento CLI tool and then check it against Coding Standard, several issues are going to be reported. 

### Fixed Issues (if relevant)
N/A

### Steps to reproduce (*)
1. **Run in the console:** `php bin/magento setup:db-declaration:generate-patch Magento_Catalog test` for example;
2. Open generated file;

**Actual Result:**

screenshot_22

**Expected Result:**

screenshot_23
### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
If you generate Patch using Magento CLI tool and then check it against Coding Standard, several issues are going to be reported. 

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28376: Generated code is not consistent with Magento requirements and Coding Standard

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

Running them all to make sure that there are no side effects.

**Review by aleron75 — APPROVED** [review]
I took a look at failing tests and they don't seem related to this PR, so I would approve it.

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-7588](https://jira.corp.magento.com/browse/ENGCOM-7588) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

1. **Run in the console:** `php bin/magento setup:db-declaration:generate-patch Magento_Catalog test` for example;
2. Open generated file;

**Before:**
screenshot_22

**After:**
screenshot_23

**Comment by engcom-Charlie** [comment]
Failed tests not related to changes from this PR.

**Comment by slavvka** [comment]
@magento create issue

**Comment by lbajsarowicz** [comment]
@magento run all tests

I'd like to verify if there are no issues with current mainline.

**Pull request merged**
