### PR TITLE
remove unnecessary spaces around inline-link widget

### LINKED ISSUE #32712: unnecessary spaces around inline-link widget
### Preconditions (*)
Magento 2.4.2

### Steps to reproduce (*)
1. Place an inline-link (widget) into a site or cms-block inside of a text. 
`This is a ,{{widget type="Magento\Catalog\Block\Category\Widget\Link" anchor_text="link" title="link" template="category/widget/link/link_inline.phtml" id_path="category/4"}}, to show the behaviour of inline-links.`

### Expected result (*)
The link should not have any spaces around it:
grafik

### Actual result (*)
The link gets inserted with additional whitespaces around it:
grafik

---

- [ x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Small change to remove whitespace around link inline 

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32712

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Unit Tests, WebAPI Tests

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-9025](https://jira.corp.magento.com/browse/ENGCOM-9025) has been created to process this Pull Request
:eight_spoked_asterisk: @swnsma, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by mrtuvn** [comment]
I think this specific case don't need some cover by tests. This changes not impact too much business and no side-effect @swnsma what do you think

**Pull request closed without merging**
