### PR TITLE
Fixed #22506: Search suggestion panel overlapping on advance reporting button 

### LINKED ISSUE #22506: Search suggestion panel overlapping on advance reporting button
### Preconditions (*)
1. Admin panel magento 2.3

### Steps to reproduce (*)
1. Log into the admin panel 
2. Click on search icon form the dashboard
3. Enter any Search keyword (Email Id)  
4. Search result pop-up overlapping on advanced reporting button 

### Expected result (*)
1. After entering sample data in the search box then the system should not be overlapped pop-up on advanced reporting button.

### Actual result (*)
1. Search result pop-up should not be overlapped on advanced reporting.

search

### PR DESCRIPTION
**Pull request by dev-ajaysaini**
Search suggestion panel overlapping on advance reporting button Fixed.

### Description (*)

In this PR is have fixed Search suggestion panel overlapping on advance reporting button.
### Fixed Issues (if relevant)

1. #22506 
2. ...

### Manual testing scenarios (*)

1. Log into the admin panel
2. Click on search icon form the dashboard
3. Enter any Search keyword (Email Id) or Long text.
4. Search result pop-up is now not overlapping on advanced reporting button.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22520) <br/>All committers have signed the CLA.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4833](https://jira.corp.magento.com/browse/ENGCOM-4833) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@webkul-ajaysaini thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VasylShvorak** [comment]
Hi @webkul-ajaysaini during testing I found that issue is still reproduced on Firefox.
#22520Firefox
Could you take a look?

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-4833](https://jira.corp.magento.com/browse/ENGCOM-4833) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
