### PR TITLE
FIX: The front-end date-picker is not localized.

### PR DESCRIPTION
**Pull request by baranada**
### Description (*)
the datepicker jquery ui has missing language code files. so I included it.

### Fixed Issues (if relevant)
1. magento/magento2#26565: The front-end date-picker is not localized.

### Manual testing scenarios (*)
Same as original contents
https://github.com/magento/magento2/issues/26565

### Questions or comments
Todo : if translations are put in the magento js translation way, harder to update translations, but more efficient in transportations.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
Hi @baranada . Thanks for collaboration. This PR needs to be approved internally cause new JS library was introduced. I will take care of it.

**Comment by sivaschenko** [comment]
@magento run all tests

**Review by sivaschenko — CHANGES_REQUESTED** [review]
@baranada thanks for the pull request!

Can you please check the failed test builds?

There is plenty of failed functional test.

Unit tests are failing with error:
`TypeError: undefined is not an object (evaluating '$('link[href*=\'calendar.css\']')`

Not sure what is the reason for Static tests failure though, will restart the build

**Comment by sivaschenko** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
The changes are currently under discussion and pending approval. Moved the pull request to the `To Approve` column

**Comment by engcom-Alfa** [comment]
Hi @baranada & @sivaschenko ,
Thanks for your contribution and collaboration!

Since this ticket was under approval process and took time to proceed ahead, re-looked if the issue is reproducible.
As I tried to reproduce in the Magento latest code version `2.4-develop', the issue is not reproducible.

If I configure from admin login: Stores > Settings > Configuration > General > General > Locale drop down- German (Switzerland), the front end _Created A new customer_ page has the DOB in the below screenshot format.
image

If I configure from admin login: Stores > Settings > Configuration > General > General > Locale drop down- English (United States), the front end _Created A new customer_ page has the DOB in the below screenshot format.
image

Hope this is what tried to PR in this PR. May be since it has turned little older ticket, possible that some other fix might have covered this issue. Kindly confirm me if the issue is fixed from your end as well so that we can close this PR ticket along with associated issue.
If you are still facing the same issue, kindly provide me the complete step by step procedure to reproduce the issue.
Thanks

**Comment by engcom-Alfa** [comment]
> Hi @baranada & @sivaschenko , Thanks for your contribution and collaboration!
> 
> Since this ticket was under approval process and took time to proceed ahead, re-looked if the issue is reproducible. As I tried to reproduce in the Magento latest code version `2.4-develop', the issue is not reproducible.
> 
> If I configure from admin login: Stores > Settings > Configuration > General > General > Locale drop down- German (Switzerland), the front end _Created A new customer_ page has the DOB in the below screenshot format. image
> 
> If I configure from admin login: Stores > Settings > Configuration > General > General > Locale drop down- English (United States), the front end _Created A new customer_ page has the DOB in the below screenshot format. image
> 
> Hope this is what tried to PR in this PR. May be since it has turned little older ticket, possible that some other fix might have covered this issue. Kindly confirm me if the issue is fixed from your end as well so that we can close this PR ticket along with associated issue. If you are still facing the same issue, kindly provide me the complete step by step procedure to reproduce the issue. Thanks

Based on this comment, closing this PR as off now
In case of any further findings, please feel free to re-open the ticket with all the necessary information.
Thanks!

**Pull request closed without merging**
