### PR TITLE
Fix button color on hover in email template

### PR DESCRIPTION
**Pull request by Karlasa**
On hover button should use @button-primary__hover__color not @button-primary__color
### Fixed Issues (if relevant)

Corrected button hover text color.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by nahuelsanchez** [comment]
@magento-engcom-team give me 2.2 instance.

**Comment by nahuelsanchez** [comment]
@magento-engcom-team give me 2.2.0 instance

**Comment by magento-engcom-team** [comment]
Hi @nahuelsanchez. Thank you for your request. I'm working on Magento 2.2.0 instance for you

**Comment by magento-engcom-team** [comment]
Hi @nahuelsanchez, here is your [Magento instance](https://i-14455-2-2-0.instances.magento-community.engineering).
Admin access: [https://i-14455-2-2-0.instances.magento-community.engineering/admin](https://i-14455-2-2-0.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Pull request merged**
