### PR TITLE
Minor cleanup: fixed wrong usage of sprintf, it only takes 2 placeholders here and w…

### LINKED ISSUE #39062: [Issue] Minor cleanup: fixed wrong usage of sprintf, it only takes 2 placeholders here and w…
This issue is automatically created based on existing pull request: magento/magento2#38628: Minor cleanup: fixed wrong usage of sprintf, it only takes 2 placeholders here and w…

---------
…e gave it 3 arguments.

### Description (*)
Found with running phpstan on level 0:
```
 ------ ------------------------------------------------------------------------
  Line   framework-message-queue/Consumer/Config/Validator/ConsumerInstance.php
 ------ ------------------------------------------------------------------------
  42     Call to sprintf contains 2 placeholders, 3 values given.
 ------ ------------------------------------------------------------------------
```

This PR fixes this, it doesn't fix anything major, as the code runs fine as-is and doesn't crash. So this is only a minor cleanup.

I've left the trailing comma, since that's accepted by PHP > 8.0 and it results in cleaner git diffs.

### Manual testing scenarios (*)
Nothing to test, the code wasn't behaving wrong before, this is just a minor cleanup.
The [unit test for this class already tests for the correct exception message](https://github.com/magento/magento2/blob/725b6483932b4bbbbd9f463de80c82914346643d/lib/internal/Magento/Framework/MessageQueue/Test/Unit/Consumer/Config/Validator/ConsumerInstanceTest.php#L121-L122), so if unit tests are green, this can be considered good enough.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by hostep**
…e gave it 3 arguments.

### Description (*)
Found with running phpstan on level 0:
```
 ------ ------------------------------------------------------------------------
  Line   framework-message-queue/Consumer/Config/Validator/ConsumerInstance.php
 ------ ------------------------------------------------------------------------
  42     Call to sprintf contains 2 placeholders, 3 values given.
 ------ ------------------------------------------------------------------------
```

This PR fixes this, it doesn't fix anything major, as the code runs fine as-is and doesn't crash. So this is only a minor cleanup.

I've left the trailing comma, since that's accepted by PHP > 8.0 and it results in cleaner git diffs.

### Manual testing scenarios (*)
Nothing to test, the code wasn't behaving wrong before, this is just a minor cleanup.
The [unit test for this class already tests for the correct exception message](https://github.com/magento/magento2/blob/725b6483932b4bbbbd9f463de80c82914346643d/lib/internal/Magento/Framework/MessageQueue/Test/Unit/Consumer/Config/Validator/ConsumerInstanceTest.php#L121-L122), so if unit tests are green, this can be considered good enough.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#39062: Minor cleanup: fixed wrong usage of sprintf, it only takes 2 placeholders here and w…

### CODE REVIEW

**Comment by hostep** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento create issue

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
The **Functional CE** failures are different in recent 2 runs, seems to be flaky.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38628/cc677f6ece906fd770625c41527e58dd/Functional/allure-report-ce/index.html#categories
image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38628/d092cabf3f7138b5f7b7566a15c6f1e9/Functional/allure-report-ce/index.html#categories
image

**Comment by engcom-Charlie** [comment]
Some functional EE test fialures are differnt in recent 2 builds, one is constant in both the build. This test fialure is a known failure and exits open JIRA for the same.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38628/fd5b91e27a556b9c00652f529519ac60/Functional/allure-report-ee/index.html#categories

image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38628/e92fa8c4d126ac46f97ae914ad9c0f6b/Functional/allure-report-ee/index.html#categories/7ab86c37ada5ce9839cb60a85ecf9b8f/fac5d2e9fe8720ca/
image

**Known issues :**
StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest: [#ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331)

**Comment by engcom-Charlie** [comment]
In the recent 2 builds the Functional B2B failures are not consistent in recent 2 builds, seems to be flaky. Hence moving this PR to Merge in Progress.

**Run 1:**
No B2B failure

**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38628/ce60b81a6d8495aa1a22322a9cdc21c0/Functional/allure-report-b2b/index.html#categories
image

**Pull request merged**
