### PR TITLE
Load storage polyfill conditionally

### LINKED ISSUE #28381: [Issue] Load storage polyfill conditionally
This one follows the approach from #27618 which let's us remove loading of storage polyfill so it is only applied for those rare cases when it is not supported. I also reformatted requirejs-config.js keys a bit so it is aligned with other configurations you can find in Magento codebase.

### Preconditions (*)

1. Magento version 2.3.5 

### Steps to reproduce (*)

1. Storage polyfill is only loaded and applied when either `localStorage` or `sessionStorage` are not available.

### Actual result (*)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by krzksz**
### Description (*)
This PR is a part of my effort to improve Magento 2 frontend performance.

This one follows the approach from https://github.com/magento/magento2/pull/27618 which let's us remove loading of storage polyfill so it is only applied for those rare cases when it is not supported. I also reformatted `requirejs-config.js` keys a bit so it is aligned with other configurations you can find in Magento codebase.

### Manual testing scenarios (*)

1. Storage polyfill is only loaded and applied when either `localStorage` or `sessionStorage` are not available.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28381: Load storage polyfill conditionally

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@krzksz looks like it will be not easy to cover these changes with automatic tests. Do you think it's possible to cover your changes with some tests?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @krzksz,
Your changes looks good to me.
Could you fix the static tests?

**Comment by ihor-sviziev** [comment]
As we discussed in Slack - it's too hard to cover these changes with automated tests, so I put label "not required"

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7299](https://jira.corp.magento.com/browse/ENGCOM-7299) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Before:**

- polyfill.js is always loaded

#27619Main

**After:**

- polyfill.js is not loaded when `localStorage` or `sessionStorage` are available.

#27619PR

- polyfill.js is loaded when cookies are blocked

#27619PRBlocked

**Comment by VladimirZaets** [comment]
@magento create issue

**Comment by slavvka** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@omiroshnichenko done in https://github.com/magento/magento2/pull/28749

**Pull request merged**
