### PR TITLE
Fixed issue #20187 Downloadble Price duplicate issue

### PR DESCRIPTION
**Pull request by GovindaSharma**
Fixed issue #20187 Downloadble Price duplicate issue

### Description (*)
Fixed issue #20187 Downloadble Price duplicate issue

### Fixed Issues (if relevant)

1. magento/magento2#20187: Issue title

### Manual testing scenarios (*)

1.Install one downloadable product and one simple product
2.in frontend open both products in different browser tabs to compare the layout
3.Price is getting duplicated

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by GovindaSharma** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-4399](https://jira.corp.magento.com/browse/ENGCOM-4399) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
✔️ QA passed

**Pull request merged**
