### PR TITLE
Fix invalid method access to array in admin full tax summary

### LINKED ISSUE #32374: [Issue] Fix invalid method access to array in admin full tax summary
This issue is automatically created based on existing pull request: magento/magento2#32346: Fix invalid method access to array in admin full tax summary

---------

### Description (*)

This seems to be a regression introduced here:
https://github.com/magento/magento2/commit/70ede03e5c2dc9e2c3bb23d0fc5c29cb03cbe7dd#diff-1f0e062a61e6915bf3f30e7ee293d2bb626f48a67aa14e79bb6f11635e053c6bR59

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Make an order with products from multiple tax classes (to get a full tax summary). 
2. View the order in admin.
3. Invoice the order fully.
4. Make a full credit memo for the invoice.
5. View the credit memo. The page should break due to `Call to a member function getId() on array in vendor/magento/module-sales/view/adminhtml/templates/order/totals/tax.phtml:62`

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by aapokiiso**
### Description (*)

This seems to be a regression introduced here:
https://github.com/magento/magento2/commit/70ede03e5c2dc9e2c3bb23d0fc5c29cb03cbe7dd#diff-1f0e062a61e6915bf3f30e7ee293d2bb626f48a67aa14e79bb6f11635e053c6bR59

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Make an order with products from multiple tax classes (to get a full tax summary). 
2. View the order in admin.
3. Invoice the order fully.
4. Make a full credit memo for the invoice.
5. View the credit memo. The page should break due to `Call to a member function getId() on array in vendor/magento/module-sales/view/adminhtml/templates/order/totals/tax.phtml:62`

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32374: Fix invalid method access to array in admin full tax summary

### CODE REVIEW

**Comment by aapokiiso** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by bgorski** [comment]
@magento run Database Compare, Functional Tests B2B, Functional Tests EE

**Review by bgorski — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @bgorski, thank you for the review.
[ENGCOM-8903](https://jira.corp.magento.com/browse/ENGCOM-8903) has been created to process this Pull Request
:eight_spoked_asterisk: @bgorski, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Oscar** [comment]
Hi @aapokiiso !
I was not able to reproduce described issue following next steps:
Manual testing scenarios (*)
Make an order with products from multiple tax classes (to get a full tax summary).
View the order in admin.
Invoice the order fully.
Make a full credit memo for the invoice.
View the credit memo. The page should break due to Call to a member function getId() on array in vendor/magento/module-sales/view/adminhtml/templates/order/totals/tax.phtml:62

Can you please clarify *Actual result and *Expected result for this case?

**Comment by engcom-Foxtrot** [comment]
@aapokiiso @engcom-Oscar I've checked the code and found no suitable way to reproduce the issue on the default Magento 2 CE installation. Seems like 'rates' array element can be set only in
https://github.com/magento/magento2/blob/cdd4d4b5f11deb8cf88bfd72da8718819839ab28/app/code/Magento/Sales/Block/Adminhtml/Order/Totals/Tax.php#L96-L100, but I don't see the way for $taxClassAmount to be not set. Please correct me if I'm wrong.

**Comment by aapokiiso** [comment]
@engcom-Foxtrot Hey, I'm not sure if I'm understanding correctly, but the original issue is that `$rate` is treated as an object in the template when calling `$rate->getId()`, when in fact it is an array (see the other usages of `$rate` in the template).

Let me know if I can clarify the issue more.

**Comment by engcom-Foxtrot** [comment]
@aapokiiso yes, you're right. But I did not find any scenario to force this line to execute, as $_fullInfo always comes without 'rates' element set.

**Comment by ihor-sviziev** [comment]
Hi @bgorski,
Unfortunately, using the `rate-ratecode` as ID isn't a good option. There is quite a high probability of having ID duplication on the page. As a result, it will cause not expected behavior or broken functionality. Instead, it's better to generate some random string and use it there. 
This approach is used in https://github.com/magento/magento2/pull/30516, so it's better to accept it instead.

Having that in mind, I'm closing this PR. Thank you so much for your contribution!

**Pull request closed without merging**
