### PR TITLE
[WIP] Faster is table exists nocache 

### PR DESCRIPTION
**Pull request by jonashrem**
### Description (*)
Variant of #28516 without the caching to check out, if this resolves the failing test.

### Related Pull Requests
#28516 

### Questions or comments
Please ignore this PR. We only test here.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by jonashrem** [comment]
@magento run Integration Tests

**Comment by jonashrem** [comment]
@magento run Integration Tests

**Comment by jonashrem** [comment]
@magento run Integration Tests

**Comment by ihor-sviziev** [comment]
Hi @jonashrem,
I believe we can close this PR in favor of #28516?

**Comment by jonashrem** [comment]
yes, of course.

**Pull request closed without merging**
