### PR TITLE
Filter only visible and enabled products

### LINKED ISSUE #33934: [Issue] Filter only visible and enabled products
This issue is automatically created based on existing pull request: magento/magento2#32939: Filter only visible and enabled products

---------

### Description (*)
In the VisibilityStatusProcessor there was a filter for status and visibility using `joinAttribute` this resulted in getting all products where `status` was greater than 0 and `visibility` was greater than 0. However, the "disabled" status in Magento is `2` and the "not visibile" visibility in Magento is `1`, resulting in all products, including the non-visibile and disabled products, where returned in the GraphQL results.

### Manual testing scenarios (*)

1. With GraphQL filter products (i.e. related products with an SKU) where there are disabled and enabled products
2. Make sure you return the `status` and `visibility` of the product in the results
3. Check the list of products for disabled or hidden products
4. After this change there should not be any disabled or hidden products, while they were returned before

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ArjenMiedema**
### Description (*)
In the VisibilityStatusProcessor there was a filter for status and visibility using `joinAttribute` this resulted in getting all products where `status` was greater than 0 and `visibility` was greater than 0. However, the "disabled" status in Magento is `2` and the "not visibile" visibility in Magento is `1`, resulting in all products, including the non-visibile and disabled products, where returned in the GraphQL results.

### Manual testing scenarios (*)

1. With GraphQL filter products (i.e. related products with an SKU) where there are disabled and enabled products
2. Make sure you return the `status` and `visibility` of the product in the results
3. Check the list of products for disabled or hidden products
4. After this change there should not be any disabled or hidden products, while they were returned before

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#33934: Filter only visible and enabled products

### CODE REVIEW

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run WebAPI Tests

**Comment by gabrieldagama** [comment]
Hi, @ArjenMiedema thanks for contributing. It seems that VisibilityStatusProcessor aims to add the attribute to the collection, not really filter it. Since this is used in the scope of GraphQL I believe the filter should be up to the user to decide, not forced by the processor.

So, if the user wants to fetch disabled and not visible products, they should be able to. What do you think? Thanks

**Comment by ArjenMiedema** [comment]
@gabrieldagama I can agree with you on this, but that means that it should be possible to filter on these attributes in the GraphQL call. But these attributes can not be selected as filterable attributes, so that results in having disabled or non-visible products in your webshop if you fetch them (i.e. related products) using GraphQL.

Not sure if anyone already looked into that, but that felt kinda impossible for me, which resulted in this "solution".

**Comment by Den4ik** [comment]
@magento run WebAPI Tests

**Comment by Den4ik** [comment]
@magento run WebAPI Tests

**Review by sidolov — CHANGES_REQUESTED** [review]
@ArjenMiedema please, check failed webapi tests, looks like they are related to the changes

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by engcom-Charlie** [comment]
Hi [ArjenMiedema](https://github.com/ArjenMiedema),

Thank you for your contribution!

I am looking into this issue and build failure.

Thank you!

**Comment by engcom-Charlie** [comment]
In order to work on build failure of this PR, first I was trying to reproduce the scenario/issue on magento 2.4 develop.

It seems that the issue is not reproducible on magento 2.4 develop. I have followed the below steps on magento 2.4 develop as well as on PR environment for the same.

1. Created three different products 1. sku:Router 2. sku:RouterNotVisible(product with Enable Product as No) 3. sku:RouterDisabled(Product with Visibility as Not Visible Individually ) as per issue’s requirement 

2. Tried below GraphQL query
{
  products(filter: { sku: { in: [ "Router", "RouterNotVisible", "RouterDisabled" ] } }) {
    total_count
    items {
      name
      sku
      stock_status
      price_range {
        minimum_price {
          regular_price {
            value	
            currency
          }
        }
      }
    }
    page_info {
      page_size
      current_page
    }
  }
}
 
3. The above query is giving same result on both the environment. Like below: 
On PR branch: 
image

On magento 2.4-develop:
image

The issue is not reproducible on magento 2.4 develop as the query giving the same result what is expected in this PR.

In discussion with PO for confirmation hence moving this PR in On-Hold status.

**Comment by engcom-Charlie** [comment]
As per above [comment](https://github.com/magento/magento2/pull/32939#issuecomment-1067633532) and confirmation from @cpartica, closing this PR.

Please reopen and update if you wish to continue.

Thank you for your contribution!

**Pull request closed without merging**
