### PR TITLE
[Catalog][Webapi] REST API Category translation

### PR DESCRIPTION
**Pull request by vasilii-b**
### Description (*)
This PR solve issue when other category attributes than specified in REST API request are changed.

### Fixed Issues (if relevant)
1. magento/magento2#17186

### Manual testing scenarios (*)
1. Create 2 storeviews.
2. Create a category
3. Make a `PUT` request to `magento-url/rest/{store-code}/V1/categories/{category-id}` with settings like:
```json
{
    "saveOptions": true,
    "category": {
        "id": 4,
        "name": "Category storeview specific name"
    }
}
```
4. Got to that category in admin area and see that only category name and url was changed, no other settings was modified (like include in menu, is active, etc) - they still have checked "Use Default Value".

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
Hi @vasilii-b , thank you for the pull request! Please take a look at the failed integration and unit tests on Travis.

**Comment by sidolov** [comment]
Hi @vasilii-b , will you continue progress on the PR?

**Review by sidolov — CHANGES_REQUESTED** [review]
Please, take a look at failed tests

**Comment by sidolov** [comment]
@vasilii-b , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
