### PR TITLE
disable add to cart until page load

### PR DESCRIPTION
**Pull request by sunilit42**
### Description (*)
Open a configurable product having DropDown options
When the page is being loaded, you will notice that the dropdowns has no values
Click Add To Cart button during this time. The page will be reloaded and a notice message "Open a configurable product having DropDown options" will be shown

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21007) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @sunilit42. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by VladimirZaets** [comment]
Hi @sunilit42 , please, sign CLA, otherwise, we can't process your pull request

**Comment by VladimirZaets** [comment]
Hi @sunilit42 , please, sign CLA, otherwise, we can't process your pull request

**Comment by sunilit42** [comment]
@VladimirZaets i did it

**Comment by sunilit42** [comment]
> Hi @sunilit42 , please, sign CLA, otherwise, we can't process your pull request

i did it, let me know any thing missing

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4178](https://jira.corp.magento.com/browse/ENGCOM-4178) has been created to process this Pull Request

**Comment by cscd98** [comment]
Just what I wanted, thanks :+1:

**Comment by craigcarnell** [comment]
@VladimirZaets @sidolov 

if $block->isRedirectToCartEnabled() then he button is never re-enabled. validate-product.js changed only has affect when isRedirectToCartEnabled is false.

**Pull request merged**
