### PR TITLE
21610-No loading mask on sitemap, when click on Save

### PR DESCRIPTION
**Pull request by solwininfotech**
### Fixed Issues (if relevant)

1. magento/magento2#21610: No loading mask on sitemap, when click on Save

### Manual testing scenarios (*)

  1. Go to Marketing option.
  2. Click on site map
  3. Then click on add site map.
  4. Fill the require fields.
  5. Click on save button multiple time.

New Sitemap Creation
new_sitemap_creation

New Sitemap Creation Process
new_sitemap_creation_process

New Sitemap Created Successfully
new_sitemap_created_successfully

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by solwininfotech** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @solwininfotech. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @solwininfotech, here is your [new Magento instance](https://pr-22660.instances.magento-community.engineering).
Admin access: [https://pr-22660.instances.magento-community.engineering/admin](https://pr-22660.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by orlangur — CHANGES_REQUESTED** [review]
JS code must not be placed in PHP code, selectors must rely on data attributes and not HTML ID or CSS classes.

**Comment by sidolov** [comment]
@solwininfotech , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
