### PR TITLE
Changed element to name for move action

### PR DESCRIPTION
**Pull request by lazyguru**
Changed <move> layout command to use name instead of element for referencing
which block to move.  This is for consistency with other layout commands (and to make @annarudko happy).  I did update the unit tests and they ran successfully on my local machine.

### CODE REVIEW

**Comment by Vinai** [comment]
Don't you think that "move element" reads nicer then "move name"? The former is closer to English. But that's just my .02€ - don't worry if you think it really is better.

**Comment by lazyguru** [comment]
@Vinai  I have no issue with move element.  But for consistency, other actions should be updated as well then (eg remove element instead of remove name, etc...).

**Comment by Vinai** [comment]
I agree, consistency would be nice.

**Comment by vrann** [comment]
@lazyguru Thanks for contribution! I would agree with Vinai that it will make more sense to have it as "move element" and rename all other attributes in the blocks such as "remove" for consistency. What do you think about that?

**Comment by lazyguru** [comment]
I have no issue either way.  My only contention is with consistency.  

A downside to renaming all of the other actions is a greater affect on the platform and a definite break in BC.  It will mean additional work in updating layout files, etc.. (again, I don't care either way.  Just mentioning a concern).  As M2 is entering the merchant beta phase and we are wanting extension providers to start updating their extensions, I think that kind of change would almost require waiting until 2.1 (only my 2 cents though).  However, the change I have proposed here affects a new action only and might have a lesser impact.

**Comment by lazyguru** [comment]
I take that back on waiting for 2.1.  Because it is a BC break, it would mean either it happens now or waits until 3.0 to stay true to semver

**Comment by vrann** [comment]
I'm glad you mentioned that! I was hesitant answering that we cannot take the change due to merchant beta API freeze, because it should be a way to accept such changes and stage them for later releases. We will think on the possible strategy for that. In the mean time I put this change on hold.

**Comment by lazyguru** [comment]
I'm curious on which change causes this to be on hold?  If we are near a code freeze point then I would think the obvious choice is to go with "move name" and plan for the change to use element for version 3.0

**Comment by vrann** [comment]
The public api freeze happened during merchant beta. After that backward incompatible changes to public APIs are not welcome until next major release. I assume that this change changed the structure of the xml file, so that any extension which used "element" before may be broken. Is that right?

**Comment by lazyguru** [comment]
> I assume that this change changed the structure of the xml file, so that any extension which used "element" before may be broken. Is that right?

In that sense, yes this change would be a BC break.  I was thinking in terms of M1 -> M2.  Would it be better if I found a way to allow either syntax?

**Comment by vrann** [comment]
I think either syntax might cause even more inconsistency than just different attribute names across elements: you'll get different attribute names for the same element!

Why don't we close current pull request due to api freeze, and in the new release you'll be able to submit either this change or rename everything to the "element". We will work on the strategy on how to submit PRs for the future releases earlier, not to wait for that too long.

**Comment by lazyguru** [comment]
While I don't like the end result (stuck with inconsistency), I agree that there really isn't anything that can be done due to the API freeze.  I'm guessing we will have to wait for 3.0 to fix things

**Comment by alankent** [comment]
It is not definite, and subject to internal discussion, but I am in the camp of minimizing backwards incompatibility but not saying zero changes until 3.0. Otherwise it becomes another major set of changes. I prefer the Jim Collins rule of 20% change per year, to keep the product ticking along without too much incompatibility but not stagnating at the same time.

The plan to achieve this was to move towards independent version series per module. Module version numbers are not product version numbers. The idea was we could introduce a major version number change for a module if we change its API, but the product version (e.g. CE 2.1) could still be a minor number change. Product version numbers are driven by marketing decisions; module version numbers are driven by semantic versioning.

This will not be in place for GA 2.0 (most likely). Probably not even CE 2.1. The short term plan is to keep the module version numbers more in sync to simplify testing etc. But the long term thinking is to allow modules to have independent version numbers to give the platform more flexibility. But we are no rushing into this change as it is not clear if the benefits will be worth the additional complexity. At worst we can increment the major version number of all modules during a minor product number change. (I personally like the idea of starting module version numbers at 10.0.0 at GA to clarify the difference between module version numbers and product version numbers, but this also has not been agreed to internally yet.)

**Comment by lazyguru** [comment]
I'm referencing the inclusion of PHP7 support along with other recent decisions to break the code freeze for underlying architectural changes (http://alankent.me/2015/10/07/xml-schema-resolution-in-php-storm-with-urns-quick-note/) as a reason to reopen this PR.  It's clear the freeze is not a hard-freeze and I feel this PR addresses a consistency issue that should be dealt with.

**Pull request closed without merging**
