### PR TITLE
Resolve "Action" column is not the last column in "Design Configuration" (issue 24139)

### LINKED ISSUE #24139: "Action" column is not the last column in "Design Configuration"
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Content->Configuration
3. Check the grid

### Expected result (*)

image

### Actual result (*)

image

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#24139:"Action" column is not the last column in "Design Configuration"

Solution: Add sortOrder = 50 in action column (it has no-value before)

### Fixed Issues (if relevant)

1. magento/magento2#24139:"Action" column is not the last column in "Design Configuration"

### Manual testing scenarios (*)

1. Go to backend
2. Content->Configuration
3. Check the grid

#### Expected result

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-24140.instances.magento-community.engineering).
Admin access: [https://pr-24140.instances.magento-community.engineering/admin](https://pr-24140.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-5627](https://jira.corp.magento.com/browse/ENGCOM-5627) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

**Before:**
before

**After:**
after

**Pull request merged**
