### PR TITLE
Make totals compare subtotals with taxes before reloading customer data

### LINKED ISSUE #26294: Customer data AJAX request is executed on every cart page reload when subtotal is set to be displayed including tax.
### Preconditions (*)
1. Magento 2.3.3
2. Product that can be added to cart

### Steps to reproduce (*)
1. Create tax zone and rule so products in shop are taxed
2. Set Stores -> Configuration -> Sales -> Tax -> Shopping Cart Display Settings -> Display subtotal to "Including Tax"
3. Refresh caches
4. Go to storefront
4. Add product to cart
5. Visit cart page
6. Open browser Network tab to see requests done by browser

### Expected result (*)

1. customer data cart section AJAX request is executed only once when entering cart page for the first time, after refreshing page data is not reloaded

### Actual result (*)
1. customer data cart section AJAX request is executed on every cart page refresh

When setting tax configuration to display prices including tax (common scenario for European shops) code from vendor/magento/module-checkout/view/frontend/web/js/model/totals.js file:
```javascript
    var quoteItems = ko.observable(quote.totals().items),
        cartData = customerData.get('cart'),
        // quoteSubtotal = parseFloat(quote.totals().total_segments.find(total => total.code === 'subtotal').value),
        quoteSubtotal = parseFloat(quote.totals().subtotal),
        subtotalAmount = parseFloat(cartData().subtotalAmount);

    quote.totals.subscribe(function (newValue) {
        quoteItems(newValue.items);
    });

    if (quoteSubtotal !== subtotalAmount) {
        customerData.reload(['cart'], false);
    }
```

is constantly invalidating cart customerData section. 

The reason is that `subtotalAmount` variable always contains subtotal without tax.
 `quoteSubtotal` contains value that depends on Magento tax configuration (including or excluding tax depending on setting mentioned in Steps to reproduce).

### PR DESCRIPTION
**Pull request by krzksz**
### Description (*)
Because of the fact that customer data cart's `subtotalAmount` contains a value that always includes a tax we need to use `subtotal_incl_tax` instead of `subtotal`, which contains the tax only if the setting to include them is enabled in admin panel.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#26294: Customer data AJAX request is executed on every cart page reload when subtotal is set to be displayed including tax.

### Manual testing scenarios (*)

1. Create tax zone and rule so products in shop are taxed
2. Set Stores -> Configuration -> Sales -> Tax -> Shopping Cart Display Settings -> Display subtotal to "Including Tax"
3. Refresh caches
4. Go to storefront
5. Add product to cart
6. Visit cart page
7.  Validate in devtools network tab that request for reloading customer data is not done on every refresh.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by krzksz** [comment]
I'll try to fix tests today.

**Review by sidolov — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8205](https://jira.corp.magento.com/browse/ENGCOM-8205) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @krzksz. Could you fix the failing tests?
Thanks!

**Comment by krzksz** [comment]
@magento run Static Tests,Unit Tests

**Comment by engcom-Charlie** [comment]
Hi @krzksz could you please fix the unit tests?
Thank you.

**Comment by krzksz** [comment]
I'm having trouble with them as they are passing on my local environment but I'll try to come up with some different approach there.

**Comment by sidolov** [comment]
@krzksz do you had a chance to take a look at failed tests?

**Comment by sidolov** [comment]
@krzksz I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
