### PR TITLE
#14918 improve Indexer Batch Provider

### PR DESCRIPTION
**Pull request by thiagolima-bm**
FIX: Ineficient Indexer Batch Provider #14918 

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@thiagolima-bm thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by thiagolima-bm** [comment]
Somehow travis is failing..

**Review by larsroettig — COMMENTED** [review]
Hi @thiagolima-bm, I restart the build it was javascript test problem on Travis. The code looks for me good. I have not timed for manually testing. 

Best regards, 

Lars

**Comment by thiagolima-bm** [comment]
Thanks @larsroettig ;)

**Comment by sivaschenko** [comment]
Hi @thiagolima-bm , those changes are not backward compatible. Is there a way to introduce these as a separate interface/implementation (dropping the $linkField parameter and changing keys of generator).

**Comment by sidolov** [comment]
Hi @thiagolima-bm , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
