### PR TITLE
Fixed issue #20802 Dashboard Refresh Statistics action redirects to 404

### PR DESCRIPTION
**Pull request by GovindaSharma**
Fixed issue #20802 Dashboard Refresh Statistics action redirects to 404

### Description (*)
Fixed issue #20802 Dashboard Refresh Statistics action redirects to 404

### Fixed Issues (if relevant)

1. magento/magento2 #20802 Dashboard Refresh Statistics action redirects to 404

### Manual testing scenarios (*)

    1.Open the backend (on Dashboard)
    2.Click on the Reload Data button

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by GovindaSharma** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma, here is your [new Magento instance](https://pr-20804.instances.magento-community.engineering).
Admin access: [https://pr-20804.instances.magento-community.engineering/admin](https://pr-20804.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by GovindaSharma** [comment]
looks like PR is alreday created.so i am closing it.

**Pull request closed without merging**
