### PR TITLE
#26473: Improved logic for product image updating for configurable products

### LINKED ISSUE #26473: BUG: Wrong selected product image when query url param configurable product
###  Summary of the issue (*)
In my webshop I have games and this games have different editions and a used and a new state.
Now I have one configurable product for example: "007 From Russia With Love" with a couple of simple products under it:

*(Attribute) System*
1. PlayStation 2
2. GameCube

*(Attribute) State*
1. New
2. Used

In my product listings I only show the configurable products but the product URL is changed to the specific system attribute in my condition it is: http://local.magento/007-from-russia-with-love.html#142=345 so it links to the specific simple product with that system already selected. 

The price and the selected system attribute is correct on the productpage only the product image is not selected for this simple product. It takes the default image of the configurable product.

### Preconditions (*)

1. Magento 2.3.3
2. MySQL 5.6.23
3. Ubuntu 16.04.5 LTS (Docker container: https://hub.docker.com/r/alexcheng/magento2/)
4. PHP 7.2.12

### Steps to reproduce (*)

1. Make a configurable product with a random image.
2. Make 2 simple products under it with 2 attributes System,State(See summary) and the simple products need different images.
3. Link to the productpage of the configurable product with # query like http://local.magento/007-from-russia-with-love.html#142=345 so that a system is already selected. Ofcourse change the '142' to your attribute super id and the '345' with a option of the attribute.
4. Check if it shows image of Configurable product or from simple product.

### Expected result (*)

1.  alt text

### Actual result (*)

1.  alt text

### LINKED ISSUE #26856: Wrong gallery main image and active preview after updating for configurable products.
Wrong gallery main image and active preview after gallery data updating for configurable products.

### Preconditions
1. Magento 2.4

### Steps to reproduce
1. Create a configurable product (the `color` attribute uses for example) with associated products:
- product with 'Black' color
- product with 'White' color 

2. Add image and video for each products like on the screenshot below.
Screen Shot 2020-02-13 at 11 36 56 AM

### Expected result
1. Expected result for case when the `color` attribute has 'Dropdown' type.
Screen Shot 2020-02-13 at 11 49 44 AM

2. Expected result for case when the `color` attribute has 'Visual Swatch' type.
Screen Shot 2020-02-13 at 12 05 47 PM

### Actual result
1. Actual result for case when the `color` attribute has 'Dropdown' type. Wrong main image and active preview for 'Black' option.
Screen Shot 2020-02-13 at 11 45 04 AM

2. Actual result for case when the `color` attribute has 'Visual Swatch' type. Wrong main image and active preview for 'White' option. Swatch logic always use first image after gallery updating.
Screen Shot 2020-02-13 at 11 55 47 AM

### LINKED ISSUE #26858: Wrong gallery behavior when query url param configurable product
Wrong gallery behavior for preselected option by query url param for configurable product.

### Preconditions
1. Magento 2.4

### Steps to reproduce
1. Create a configurable product (the `color` attribute uses for example) with associated products:
- product with 'Black' color
- product with 'White' color 

2. Add image and video for each products like on the screenshot below.
Screen Shot 2020-02-13 at 11 36 56 AM

3. Add needed params to product URL to preselected option.
For example 
- `http://store.com/configurable-b.html#93=4` where 93 - is `color` attribute id and 4 - 'white' option id
- `http://store.com/configurable-b.html#93=5` where 93 - is `color` attribute id and 5 - 'black' option id 

### Expected result
1. For URL with query to preselect 'white' option.
Screen Shot 2020-02-13 at 2 03 43 PM

2. For URL with query to preselect 'black' option.
Screen Shot 2020-02-13 at 2 01 08 PM

### Actual result
1. For URL with query to preselect 'white' option.
Screen Shot 2020-02-13 at 1 55 56 PM

2. For URL with query to preselect 'black' option.
Screen Shot 2020-02-13 at 1 53 42 PM

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Improved logic for product image updating (gallery data updating) for configurable products.

### Fixed Issues
1. #26473 
1. #26856
1. #26858

### Manual testing scenarios
See issue description from #26473 and [this comment](https://github.com/magento/magento2/issues/26473#issuecomment-577589896).
See issue description from #26856.
See issue description from #26858.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sergiy-v** [comment]
Working on fixes for tests.

**Comment by dmytro-ch** [comment]
@sergiy-v, great job! Thank you for the fixes.
Would you mind to cover the aforementioned cases by autotests?

**Comment by sergiy-v** [comment]
> @sergiy-v, great job! Thank you for the fixes.
> Would you mind to cover the aforementioned cases by autotests?

@dmytro-ch thanks for review, working on tests.

**Comment by sergiy-v** [comment]
The tests has been added.
#26856: StorefrontConfigurableOptionsThumbImagesTest, StorefrontConfigurableSwatchOptionsThumbImagesTest.
#26473: StorefrontSelectedByQueryParamsConfigurableOptionsThumbImagesTest.
#26858: StorefrontSelectedByQueryParamsConfigurableSwatchOptionsThumbImagesTest.

@dmytro-ch please check it once you will have a chance.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6992](https://jira.corp.magento.com/browse/ENGCOM-6992) has been created to process this Pull Request

**Comment by dmytro-ch** [comment]
@sergiy-v, thank you for the updates!
Could you please squash all commits into a single one in order to clean up history?

**Comment by sergiy-v** [comment]
> @sergiy-v, thank you for the updates!
> Could you please squash all commits into a single one in order to clean up history?

@dmytro-ch I have cleaned up the commit story. Thanks.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6992](https://jira.corp.magento.com/browse/ENGCOM-6992) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by slavvka** [comment]
@magento run Functional Tests EE

**Pull request merged**
