### PR TITLE
Run WebAPI tests from module directory

### PR DESCRIPTION
**Pull request by mslabko**
### Description (*)
Run tests with changed infrastructure branch

### Related Pull Requests
https://github.com/magento/partners-magento2-infrastructure/pull/39

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mslabko** [comment]
@magento run WebAPI Tests

**Comment by mslabko** [comment]
@magento run WebAPI Tests without extension magento/inventory

**Comment by mslabko** [comment]
@magento run WebAPI Tests

**Comment by ihor-sviziev** [comment]
Hi @mslabko,
Seems like this is test PR.
There are no activity for a month. Can we close it?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @mslabko @sidolov @gabrieldagama ,
Seems like this is test PR.
There are no activity for a month. Can we close it?

**Pull request closed without merging**
