### PR TITLE
[Forwardport-2.3] Resolve typo despatch event #18372

### PR DESCRIPTION
**Pull request by neeta-wagento**
### Fixed Issues (if relevant)

1. magento/magento2#18355: Typo in dispatched event name

### Manual testing scenarios

1.  method Magento\CatalogSearch\Model\Indexer\Fulltext\Action\DataProvider::getSearchableAttributes dispatches event with typo in its name
2. catelogsearch_searchable_attributes_load_after
instead of
catalogsearch_searchable_attributes_load_after

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @neeta-wagento. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by orlangur** [comment]
Hi @neeta-wagento, such changes are already present in `2.3-develop`: https://github.com/magento/magento2/pull/13097

Thanks for collaboration!

**Comment by rogyar** [comment]
@orlangur I believe this change is rather about the description in the PHP comment than renaming the event. The event is already renamed in 2.3-develop but the corresponding comment is missing (compare with 2.2-develop)

**Comment by orlangur** [comment]
@rogyar current comment in `2.3-develop` is quite sufficient.

**Comment by rogyar** [comment]
@orlangur I mean, there's no comment in 2.3-develop, only the deprecation annotation with no "@see" or explanation. We have that explanation in 2.2-develop.

**Comment by orlangur** [comment]
@rogyar yes, I've got your point, those contributions were made in very different time. As there are two consecutive calls of `dispatch` it's pretty clear what is deprecated and which event should be used instead (otherwise @sidolov would request a change in original PR).

**Pull request closed without merging**
