### PR TITLE
fixed issue #23024 : Grid Action Column Design Issues

### PR DESCRIPTION
**Pull request by Shubham0492**
### Description (*)

If grid action column position change then multi action box not align with action.

### Fixed Issues (if relevant)

1. #23024 : Grid Action Column Design Issues

### Manual testing scenarios (*)

1 . Open any Grid that action column has more than one action like CMS Block grid.
2. Programmatically change the position of an action column.
3. Comment updated_time column flush cache and reload grid.
4. Now remove comment and flush cache and reload the grid. now action column will at second last position. https://prnt.sc/ntyan7
5. Now select action, you will see the column popup always at last position. But after updating it will display with action column.

https://prnt.sc/ntybge

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mahesh-rajawat** [comment]
@dmytro-ch , any update on it?

**Comment by dmytro-ch** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-23236.instances.magento-community.engineering).
Admin access: [https://pr-23236.instances.magento-community.engineering/admin](https://pr-23236.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5620](https://jira.corp.magento.com/browse/ENGCOM-5620) has been created to process this Pull Request
:eight_spoked_asterisk: @dmytro-ch, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @Shubham-Webkul !

During testing we faced the issue

**_Problem:_** Column popup goes beyond the grid

**Steps to reproduce:**

1. Login to Admin;
2. Go to Content->Elements->Pages;
3. You should have about 15 pages in the grid;
4. In Action column click on "select" dropdown menu;
5. Scroll down the page

**Actual Result:**
error

@Shubham-Webkul Could you take a look, please?

Thanks!

**Comment by sidolov** [comment]
@Shubham-Webkul , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
