### PR TITLE
Fixed issue 25910 choose drop down not close when open another

### LINKED ISSUE #25910: Choose drop down not close when open another for upload file for swatch
Choose drop down not close when open another for upload file for swatch

### Preconditions (*)
Magento : 2.3.3

### Steps to reproduce (*)
1. Admin - Stores
2. Attributes - Product
3. Add New Attribute 
4. Properties - Select Visual swatch from Catalog Input Type for Store Owner drop down
5. Click on Add Swatch - Upload image/color
6. Add Swatch again - Click on choose file 
7. without close this click on 1st swatch choose drop down

### Expected result (*)
Other choose file drop down should close once open another

### Actual result (*)
image

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR  fixed #25910: issue 

### Fixed Issues (if relevant)

1. magento/magento2 #25910: Choose drop down not close when open another for upload file for swatch 

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @Usik2203. Thank you for the fix. According to the last updates to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered by automated tests. Could I kindly ask you to cover your changes by MFTF test? 

Thank you.

**Comment by Usik2203** [comment]
Hi, @rogyar 
I covered my fix by MFTF test. 
Thanks for Your advice.

**Comment by Usik2203** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Usik2203. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Usik2203, here is your [new Magento instance](https://pr-26090.instances.magento-community.engineering).
Admin access: [https://pr-26090.instances.magento-community.engineering/admin_b532](https://pr-26090.instances.magento-community.engineering/admin_b532)
Login: `f29f43f8` Password: `0cda837296e1`
Instance will be terminated in up to 3 hours.

**Review by rogyar — DISMISSED** [review]
Hi @Usik2203. Thank you for providing the test. The current version of the test emulates swatch clicking behavior. However, It does not perform any checks (assertions).
Your test should assert that after clicking on a new swatch the previous dropdown is not visible.

**Comment by Usik2203** [comment]
Hi @rogyar 
I have added some assertions for this test 
Thank you for Your advice.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-6966](https://jira.corp.magento.com/browse/ENGCOM-6966) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
