### PR TITLE
Input type datetime is used in lib styles

### LINKED ISSUE #30064: Input type datetime is used in lib styles
The `input[type=datetime]` has been depricated for some time -> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime
But is still used in the `lib/web/css/source/lib/_forms.less`

### Preconditions (*)

1. This issue is found in all magento 2 versions

### Steps to reproduce (*)
None, this styling issue, that has no major impact.

### Expected result (*)
The styling is applied for any input type date.
And not only for the datetime.

### Actual result (*)
Only the `input[type=datetime]` styled.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by GrimLink**
### Description (*)
By replacing the attribute selector `input[type=datetime]` for a less specific input type selector.
It will it not force us to override the lib styles for using a deprecated html input type.

This change will keep the old situation intact.
And adds support `input[type=date]` and `input[type=datetime-local]`, for the form styling.

### Fixed Issues (if relevant)

1. Fixes #30064 

### Manual testing scenarios (*)
None.
Magento 2 does not use this input type on the front-end.
The only place this attribute is found in, is in the `lib/web/css/docs`.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by GrimLink** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8216](https://jira.corp.magento.com/browse/ENGCOM-8216) has been created to process this Pull Request

**Review by ptylek — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-8216](https://jira.corp.magento.com/browse/ENGCOM-8216) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Dev experience is required for testing of this PR. Please note that Manual testing has not been performed.

**Comment by engcom-Foxtrot** [comment]
Manual testing not required.

**Pull request merged**
