### PR TITLE
related-upsell-crosssell-products-alignment-in-admin: alignment not p…

### PR DESCRIPTION
**Pull request by ranee2jcommerce**
### Description (*)

1. Magento 2.3.x
2. Related, Upsell-crosssell-products-alignment-in-admin: alignment not proper

### Fixed Issues (if relevant)

1. magento/magento2#20588: In admin, Related, Up-sell, Cross-sell products alignment not proper

### Manual testing scenarios (*)

1. Go to admin
2. Catalog -> Products -> Edit Product
3. Go to "Related Products, Up-Sells, and Cross-Sells" section
4. Add Related Products, Up-Sells, and Cross-Sells products

### Expected Result (*)
2019-01-24_18-54_beginner s yoga - products

### Actual Result (*)
2019-01-24_18-50_beginner s yoga - products

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ranee2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sdzhepa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [new Magento instance](https://pr-20584.instances.magento-community.engineering).
Admin access: [https://pr-20584.instances.magento-community.engineering/admin](https://pr-20584.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sdzhepa** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-20584-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20584-2-3-develop.instances.magento-community.engineering/admin](https://i-20584-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
hello @ranee2jcommerce 


We cannot reproduce issue described by PR on vanila 2.3-develop.
Could you please confirm or provide additional details?


**Manual testing scenario.**
1. Request vanila instance `give me 2.3-develop instance`
2. Create several products (simple, configurable)
3. Open any simple product edit page
4. Go to "Related Products, Up-Sells, and Cross-Sells" section
5. Add all test products to each section

**Actual Result:**  There is no issue descibed in this PR and initial Issue. Please see results per each section

pr_20584_1




Thank you for contribution and collaboration!

**Comment by ranee2jcommerce** [comment]
Hello @sdzhepa 

I have checked this on previous instance, it was generating the issue. But now I can see there is no issue on 2.3-develop branch.

Thank you for info.

**Pull request closed without merging**
