### PR TITLE
[MFTF] Check GoogleAnalytics rendering on the page.

### LINKED ISSUE #32764: [Issue] [MFTF] Check GoogleAnalytics rendering on the page.
This issue is automatically created based on existing pull request: magento/magento2#32762: [MFTF] Check GoogleAnalytics rendering on the page.

---------

### Description (*)

This test check if GoogleAnalytics was rendered on the pages

1. Enable GoogleAnalytics
2. Go to home page 
3. Assert is GoogleAnalytics script present in code source.

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This test check if GoogleAnalytics was rendered on the pages

1. Enable GoogleAnalytics
2. Go to home page 
3. Assert is GoogleAnalytics script present in code source.

### Resolved issues:
1. [x] resolves magento/magento2#32764: [MFTF] Check GoogleAnalytics rendering on the page.

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE

**Comment by dmytro-ch** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
Hi @Usik2203 thanks for contributing, we have discussed this PR at the Community Triage meeting. Our team believe that there is not much benefit to asserting that the GA component is rendered since this doesn't guarantee that the feature works.

When we consider adding a new test it is ideal that the new test case worth the execution time, in this case we don't see much value.

But thanks again.

**Pull request closed without merging**
