### PR TITLE
Fixed - Fatal Error when save configurable product in Magento 2.2.5 #18082

### PR DESCRIPTION
**Pull request by Shubham0492**
**Description**
I have checked that if there is any validation error exist then after click save button configurable-matrix data remove.You can check the file app/code/Magento/ConfigurableProduct/view/adminhtml/web/js/variations/variations.js in function serializeData due to fatal error comes.Now I have added condition that if there is any validation error exist then configurable-matrix data will not remove and after submit form all value will exist and product will successfully save.

**Fixed Issues (if relevant)**
1 - #18082: Fatal Error when save configurable product in Magento 2.2.5

**Manual testing scenarios**
Add new configurable product with name and sku of 63 characters length For Example: "Amzer 203877 Kristal FULL HD Tempered Glass for OnePlus 6 Clear".
Now click on "Create Configuration" button.
Now, When you try to save it's configuration, It shows client side validation error for child products SKUs. Decrease length of child product's SKUs and then save the product. It generates a error report as attached.But after apply changes product successfully saved.

**Contribution checklist**
  Pull request has a meaningful description of its purpose
  All commits are accompanied by meaningful commit messages

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18753) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @Shubham-Webkul. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sidolov** [comment]
Hi @Shubham-Webkul , looks like you made some commits with email different than in your GitHub profile, please, add email from commits to your profile!
Thank you!

**Comment by Shubham0492** [comment]
@sidolov  as i have checked that i done all commits using Shubham.Sharma967@webkul.com email.Please let me know clearly what mistake i am doing.So that i can fix it.
Thank You!

**Comment by Shubham0492** [comment]
@sidolov  I have added all emails which used to make commit.
Thank You!

**Comment by Shubham0492** [comment]
#SQUASHTOBERFEST

**Comment by orlangur** [comment]
https://github.com/magento/magento2/pull/18461 seems to be an exact backport of `2.3.x` fix.

@Shubham-Webkul thanks for your endeavours!

**Pull request closed without merging**
