### PR TITLE
Custom attributes were only saved if the value was equal to the existing value

### PR DESCRIPTION
**Pull request by CyberSecutor**
Custom attributes were only saved if the value was equal to the existing value

### Description (*)
When adding a special_price to a product for a specific store using the rest API, the special_price was not added due to the check that was changed in this PR.

The request below would only add a special_price to product 172270 if a special_price has already been set.
If the special_price is set to use the "Default value" for a specific store, the value will not get changed/set.

```json
https://somestore.com/rest/dutch_store/V1/products/
Post body:

{
    "product": {
        "sku": "172270",
        "custom_attributes": [
            {
                "attribute_code": "special_price",
                "value": 148.99
            }
        ]
    }
}
```

### Fixed Issues (if relevant)
The bug got introduced with merging this quality patch into the 2.4.3 branch.
https://support.magento.com/hc/en-us/articles/360059375492-MDVA-33168-API-async-endpoint-unsets-special-price

### Manual testing scenarios (*)
1. Setup up a Magento webshop with multiple stores
2. Set a value for special_price at global level for a specific product.
3. Try to set a special price at store level using the API request example listed above.

### CODE REVIEW

**Comment by CyberSecutor** [comment]
@magento run all tests

**Comment by igorwulff** [comment]
Can someone please check this PR?

**Comment by CyberSecutor** [comment]
@andrewbess 

After reviewing with another colleague (Boris Perevyazko) we came to the conclusion the patch can be a lot more specific.

We removed the check for the scopeOverriddenValue  because it makes no sense.

The `$this->scopeOverriddenValue->containsValue` is always checking against old pre-initialized product data.
Therefore when adding a new value for a certain scope, it is always false.
This causes any attributes or custom_attributes that are not set at scope level to not be saved.

**Comment by CyberSecutor** [comment]
@magento run all tests

**Comment by rutgerrademaker** [comment]
@CyberSecutor 
We found an issue with your patch / PR
The second commit will cause data-loss in case you do not send all the attributes, e.g:
If you send a REST request to a 'store scope' with only 1 value (e.g special_price) all the other attributes that were set on 'store scope' will be deleted (!)

We're currently testing another approach to fix the same problem:

```
--- a/Model/ProductRepository.php
+++ b/Model/ProductRepository.php
@@ -272,7 +272,7 @@
         $this->linkManagement = $linkManagement ?: \Magento\Framework\App\ObjectManager::getInstance()
             ->get(CategoryLinkManagementInterface::class);
         $this->scopeOverriddenValue = $scopeOverriddenValue ?: \Magento\Framework\App\ObjectManager::getInstance()
-            ->get(ScopeOverriddenValue::class);
+            ->create(ScopeOverriddenValue::class);
     }
```

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @CyberSecutor,

I agree with the @rutgerrademaker on this https://github.com/magento/magento2/pull/34665#issuecomment-1024245621. 

I think due to these changes some tests are failing. Please take care of them and also please cover the changes with some automated tests.

Thanks

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
Hello @CyberSecutor,

Thank you for your contributions!

I have tried to replicate the issue with a few of the custom attributes, except for special_price, and it was working as expected.

However, when I tested with special_price, I found that updating it using the API at `https://somestore.com/rest/dutch_store/V1/products/` updates the special_price for all stores.

To update the special_price, we have a separate API that can be used for this purpose. Please see the cURL command below or [dev doc](https://developer.adobe.com/commerce/webapi/rest/modules/catalog/catalog-pricing/):

```
curl --location 'https://app.magento.test/rest/V1/products/special-price' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJraWQiOiIxIiwiYWxnIjoiSFMyNTYifQ.eyJ1aWQiOjEsInV0eXBpZCI6MiwiaWF0IjoxNzMwMjc1NjMyLCJleHAiOjE3MzAyNzkyMzJ9.mtlxD3nJ_B3xwT0X__Z521S_QtEj-0eAA6MD2FSTJEY' \
--header 'Cookie: PHPSESSID=ed797261dddc80a773b250ddd4e28123; XDEBUG_SESSION=PHPSTORM; private_content_version=662f7996615d4b046adc38f9767578f9' \
--data '{
  "prices": [
    {
      "price": 19,
      "store_id": 2,
      "sku": "Test Product 2"
    }
  ]
}'
```
Thanks.

CC: @rutgerrademaker

**Comment by engcom-Dash** [comment]
Closing this PR since it has not been updated in a while. Please feel free to reopen it if needed.

**Pull request closed without merging**
