### PR TITLE
magento/magetno2#8676: I can not translate title attribute in xml fil…

### PR DESCRIPTION
**Pull request by DanijelPotocki**
…es translation not working

- add translation of resource title

### Description
magento/magetno2#8676: Added translation to customer resource title

### Fixed Issues (if relevant)
1. magento/magetno2#<issue_number>: Fixed issue where resource title was not being translated

### Manual testing scenarios
1. In customer resource check if title is being translated
2. Checked if it's working with and without new code

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=8915) <br/>All committers have signed the CLA.

**Comment by avoelkl** [comment]
Solves #8676

**Comment by avoelkl** [comment]
Thanks for the PR @DanijelPotocki, this will be merged soon!

**Comment by vrann** [comment]
@DanijelPotocki Thank you for the contribution.

**Pull request merged**
