### PR TITLE
Reorder adding of page layout handles

### PR DESCRIPTION
**Pull request by aschrammel**
Add type-dependent layout handles before more specific ID/SKU layout
handles.

When updating a product page layout for a specific ID with `catalog_product_view_id_<product_ID>.xml` some changes may be overwritten by a less specific `catalog_product_view_type_<product_type>.xml`.

### Description
Change the order of loading the layout handles in `\Magento\Catalog\Helper\Product\View` and `\Magento\Review\Controller\Product\ListAction` to add the type specific layout handles BEFORE more specific ID/SKU specific layout handles.

In `\Magento\Catalog\Controller\Category\View` the updates are already loaded in the above suggested order.
### Fixed Issues (if relevant)
--

### Manual testing scenarios

1. Create a configurable product
2. Create a layout override for this product on by ID base (`catalog_product_view_id_<product_ID>.xml`)
3. In this layout update try to overwrite the `product.info.options.configurable` block with a custom template in referenced block `product.info.options.wrapper`
4. Before applying the PR the custom template is not taken into account, afterwards it is taken into account

### Example override
```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="product.info.options.wrapper">
            <block class="Vendor\Module\Block\Product\View\Type\Configurable"
                name="product.info.options.configurable" as="options_configurable" before="-"
                template="Vendor_Module::product/view/type/options/configurable.phtml"/>
        </referenceBlock>
    </body>
</page>
```
### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by mzeis** [comment]
Hi @aschrammel, thank you very much for your contribution!

I will process your PR. I hope to able to do this before the holidays. If not please be a little bit patient with me. :-)

**Comment by aschrammel** [comment]
Hi @mzeis, thank you for your reply.

Of course - enjoy your holidays. 😃

**Comment by mzeis** [comment]
@aschrammel I will discuss your PR with the core team. The change makes sense in my opinion but we have to consider that 3rd party integrators might rely on the current behaviour and it might not be good to change this in a patch release.

**Comment by aschrammel** [comment]
@mzeis Thanks for the feedback. Of course there may be issues with 3rd party integrations and it's clear that a merge in a patch release may not be the best.
Nevertheless I think that this obviously undesired behaviour wasn't recognized since now because it's a rare edge case to update a layout via XML for only one product (ID or SKU).

**Comment by mzeis** [comment]
@aschrammel I think so too and am awaiting for approval from the core team. Thanks for your patience!

**Review by okorshenko — APPROVED** [review]

**Comment by mzeis** [comment]
Hi @aschrammel, thank you again for your contribution! It has been merged into `2.2-develop`.

**Comment by aschrammel** [comment]
Hi @mzeis, was me a pleasure ;)
Thanks for processing it.

**Pull request merged**
