### PR TITLE
Clarify XSD for formElements allowed settings

### LINKED ISSUE #14140: UI component definition.map.xml overlooks XSD-valid nodes
### Preconditions

The issue was discovered in Magento 2.2.2 EE, but looks like it still exists in the 2.2-develop branch of this repository. 

### Steps to reproduce

1. Create and configure a new UI form component with the following XML definition:

```
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
  <!-- Include standard <argument>, <settings>, <dataSource> to create minimal form. -->
  <fieldset name="billing">
    <field name="shippingMethod" formElement="select">
      <formElements>
        <select>
          <settings>
            <options class="Magento\Shipping\Model\Config\Source\Allmethods" />
            <label>Shipping Method</label>
          </settings>
        </select>
      </formElements>
    </field>
  </fieldset>
</form>
```

### Expected result

1. The XML should validate with the provided XSD files. (It does.)
2. When viewing the form in the browser, a dropdown select box with the label "Shipping Method" should be shown and populated with the values defined in the `Allmethods` class.

**OR**

1. The XML should not validate with the provided XSD files, because the parser will not read the configuration correctly.

### Actual result

1. The XML validates.
2. The dropdown select box is populated correctly, but the label is not shown.

However, the following code does display the label in the generated markup:

```
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
  <!-- Include standard <argument>, <settings>, <dataSource> to create minimal form. -->
  <fieldset name="billing">
    <field name="shippingMethod" formElement="select">
      <settings>
        <label>Shipping Method</label>
      </settings>
      <formElements>
        <select>
          <settings>
            <options class="Magento\Shipping\Model\Config\Source\Allmethods" />
          </settings>
        </select>
      </formElements>
    </field>
  </fieldset>
</form>
```

The issue seems to be how `definition.map.xml` is written, specifically around [line 285](https://github.com/magento/magento2/blob/cb0954add41284de1b003fa378551b3e973b306c/app/code/Magento/Ui/view/base/ui_component/etc/definition.map.xml#L285) and [787](https://github.com/magento/magento2/blob/cb0954add41284de1b003fa378551b3e973b306c/app/code/Magento/Ui/view/base/ui_component/etc/definition.map.xml#L787). Settings such as `<label>`, which are common to many UI components, are read only from a top-level `<settings>` node, while component-specific settings such as `<options>` are read from the appropriate `<settings>` descendent of `<formElements>`. 

This constraint/decision is perfectly understandable, _but_ it is not represented in the corresponding XSD (see [line 271](https://github.com/magento/magento2/blob/cb0954add41284de1b003fa378551b3e973b306c/app/code/Magento/Ui/etc/ui_configuration.xsd#L271) of ui_configuration.xsd, and the corresponding `formElements` group). Any child from the `abstractSettings` group (found [here](https://github.com/magento/magento2/blob/cb0954add41284de1b003fa378551b3e973b306c/app/code/Magento/Ui/view/base/ui_component/etc/definition/ui_settings.xsd#L866)) is allowed (valid) within the `<settings>` nodes that are descendents of `<formElements>`, but none of them are read by the configuration reader because they aren't specified in definition.map.xml.

### Potential Solutions

Depending on the architectural desires of the Magento team, this miscommunication could be fixed in a few ways:

1. Adding the appropriate xpath mappings for `abstractSettings` within every component-specific settings mapping.
2. Clarifying/constraining the XSD files to ensure that `abstractSettings` are only placed in top-level `<settings>` nodes, and component-specific settings remain isolated.

In short, the new UI component semantics function properly, but permit certain undefined behaviors that should be clarified in both the code itself and in documentation.

### PR DESCRIPTION
**Pull request by neillrobson**
### Description

In an attempt to resolve #14140, new complex types have been defined for every UI component specified in [`ui_settings.xsd` line 49](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Ui/view/base/ui_component/etc/definition/ui_settings.xsd#L49) (valid attribute codes for "formElement"). These complex types only include the `<settings>` child node, along with any grandchildren that pertain specifically to that form element (no `abstractSettings`). Finally, `ui_configuration.xsd` has been updated with a new group holding these complex types, and the corresponding validation for the `<formElements>` tag references this new group rather than the existing, more general group.

### Fixed Issues (if relevant)

1. magento/magento2#14140: UI component definition.map.xml overlooks XSD-valid nodes

### Manual testing scenarios

**I have not tested these changes due to lack of time,** nor am I sure that I have applied the appropriate fix to the task at hand. Please review both the functionality of the changes and the issue that they are intended to fix before merging, and feel free to make changes/a new PR if necessary.

### CODE REVIEW

**Review by VladimirZaets — APPROVED** [review]

**Review by VladimirZaets — DISMISSED** [review]
@RNanoware Please look at builds result on the travis-ci. You have set "formElementPrice" type to "price" element (formElementsConfig), but this type isn't declared.

**Comment by neillrobson** [comment]
@VladimirZaets I completely missed that--thank you! I couldn't figure out why the price component never had any valid `<settings>` configuration specified, but I made the assumption that adding empty groups/types with the proper labels would be the best course of action. The behavior of the validation itself remains unchanged, but the skeleton exists now for future developers to add configuration as needed.

**Comment by neillrobson** [comment]
Is there any way to run the Travis CI tests locally, or is pushing up code to my Github branch the only way to check for errors? Alas, the CI build takes a few hours, and I often don't have time during the week to come back and check on my mistakes.

**Comment by VladimirZaets** [comment]
Hi @RNanoware , we had the discussion your PR, because it has backward incompatible changes. 
Unfortunately, we can't merge it to Magento 2.2, but we are ok to merge it to Magento 2.3. 
Can you please move your commits to the branch that will be based on 2.3-develop and change target pull request branch to 2.3-develop.

**Comment by neillrobson** [comment]
I just made a new PR (which can be found [here](https://github.com/magento/magento2/pull/15161)). I don't trust myself trying to manually edit an existing pull request to target a different branch without breaking something. Hope this helps; let me know if there is anything else I can do!

**Comment by VladimirZaets** [comment]
@RNanoware thanks. I close this PR and will start work with PR to the 2.3 branch.

**Pull request closed without merging**
