### PR TITLE
Fix file upload styles duplication in luma theme

### LINKED ISSUE #32373: [Issue] Fix file upload styles duplication in luma theme
This issue is automatically created based on existing pull request: magento/magento2#32354: Fix file upload styles duplication in luma theme

---------

### Description (*)
I noticed that styles for file uploader located both in `styles-m` and `styles-l` css files that loaded on the page that is not really needed.
In order to fix that - I wrapped all styles to the following section:
```less
& when (@media-common = true) {
   //...original styles here
}
```

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
I noticed that styles for file uploader located both in `styles-m` and `styles-l` css files that loaded on the page that is not really needed.
In order to fix that - I wrapped all styles to the following section:
```less
& when (@media-common = true) {
   //...original styles here
}
```

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32373: Fix file upload styles duplication in luma theme

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
Yes without wrap styles will show in both files
https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/responsive-web-design/rwd_css.html

**Comment by ihor-sviziev** [comment]
@magento run Database Compare, Functional Tests B2B, Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento run Database Compare, Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by gabrieldagama** [comment]
@magento create issue

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8909](https://jira.corp.magento.com/browse/ENGCOM-8909) has been created to process this Pull Request

**Comment by slavvka** [comment]
@magento give me test instance

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
:heavy_check_mark: QA Passed

In this PR, there is nothing to test, the PR is related to the optimization of the CSS definition which is repeating in `styles-m` and `styles-l` files by moving the CSS definition to the following section:

```
& when (@media-common = true) {
   //...original styles here
}
```

Referred to the below doc for reference:

https://developer.adobe.com/commerce/frontend-core/guide/responsive-design/css/#media-queries

Moving forward with this PR, moving it to `Extended testing` as the tests are still failing.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Static Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Unit Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
The failed B2b test seems flaky, it failed on different functional tests 2 times. Please refer to the below screenshot for reference:

Build 1:

image

Build 2:

image

Hence moving this PR to `Merge in progress`.

Thanks

**Pull request merged**
