### PR TITLE
Fix for issue 25147 - Totals information management module - only set carrier/method code if set in address

### LINKED ISSUE #25147: Totals Information Management - setting quote shipping method when address method is null
### Preconditions (*)

1. 2.3.2(2.3-develop) Magento Commerce or Open Source 
2. Amasty Conditions module installed (cannot reproduce with vanilla m2 because this)
3. PHP 7.2.21

### Steps to reproduce (*)

1. On the checkout, the component `Amasty_Conditions/js/action/recollect-totals` makes a call to `/V1/guest-carts/:cartId/totals-information` which passes through Magento\Checkout\Model\TotalsInformationManagement
2. In this model the following:
```
$quote->getShippingAddress()->setCollectShippingRates(true)->setShippingMethod(
     $addressInformation->getShippingCarrierCode() . '_' . $addressInformation->getShippingMethodCode()
);
``` 
is set, but when a shipping method has not been selected, it will return the quote shipping method with a total of 0 and a name of `_`, because `$addressInformation->getShippingCarrierCode()` and method code are null - so `setShippingMethod('_')` happens in effect.
3. This then means that validation for the shipping method is bypassed.
4. An order can then be placed without shipping information/carrier

### Expected result (*)

1. If the address info has the shipping carrier and/or method code set to null, the `setShippingMethod` should not be called and the quote total is returned without setting a shipping code pair

### Actual result (*)

1. When a address info instance is submitted with shipping codes set to null, a method is set with label `_` and zero value, meaning an order can be placed without a valid shipping method.

### PR DESCRIPTION
**Pull request by joe-vortex**
- Totals Information Management - setting quote shipping method when address method is not null

### Description (*)

Fix for setting shipping carrier and method codes only when address contains it.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#25147: Totals Information Management - setting quote shipping method when address method is null - https://github.com/magento/magento2/issues/25147

### Manual testing scenarios (*)

1. Install Amasty Conditions module and go to checkout
2. Without amasty module - create api call to `/V1/guest-carts/:cartId/totals-information` then refresh page. Shipping will show as null in console and 0.00 in sumary

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by joe-vortex** [comment]
@paliarush I've rerun the static tests several times and they keep failing, any ideas?

**Comment by joe-vortex** [comment]
@sidolov  any action required from me?

**Review by sidolov — CHANGES_REQUESTED** [review]
@joe-vortex could you please cover changes with automated test?

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8154](https://jira.corp.magento.com/browse/ENGCOM-8154) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
Manual testing is omitted  https://github.com/magento/magento2/issues/25147#issuecomment-545994359

**Pull request merged**
