### PR TITLE
Remove 'version' manipulation from sampledata:deploy, improve success messaging

### LINKED ISSUE #36554: [Issue] Remove 'version' manipulation from sampledata:deploy, improve success messaging
This issue is automatically created based on existing pull request: magento/magento2#36187: Remove 'version' manipulation from sampledata:deploy, improve success messaging

---------
### Description
When running `bin/magento sampledata:deploy`, an error message is shown regarding a missing `version` key in `composer.json`. The linked page provided in the error message says that `version` should not be present in `composer.json`. The `sampledata:deploy` command then tries to add a 'version' key to `composer.json` with varying degrees of success. When this is coupled with the lack of success message, developers are left wondering if the command was successful or not. The 'version' string within `composer.json` is not required nor used by anything in this module, and should not be present.

This pull request adds a success message and instructions on what to do next for developers to follow when the command is successful, and removes any manipulation of 'version' within `composer.json`.

#### No success message
1. Run `bin/magento sampledata:deploy`
1. Witness (lack of) success messaging when the command completes successfully

#### 'version' requirement in `composer.json`
1. Ensure that `composer.json` has no `version` key (according to Composer best practices)
1. Run `bin/magento sampledata:deploy`
1. Witness (lack of) error messaging and (lack of) changes in `composer.json`

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fredden**
### Description
When running `bin/magento sampledata:deploy`, an error message is shown regarding a missing `version` key in `composer.json`. The linked page provided in the error message says that `version` should not be present in `composer.json`. The `sampledata:deploy` command then tries to add a 'version' key to `composer.json` with varying degrees of success. When this is coupled with the lack of success message, developers are left wondering if the command was successful or not. The 'version' string within `composer.json` is not required nor used by anything in this module, and should not be present.

This pull request adds a success message and instructions on what to do next for developers to follow when the command is successful, and removes any manipulation of 'version' within `composer.json`.

#### No success message
1. Run `bin/magento sampledata:deploy`
1. Witness (lack of) success messaging when the command completes successfully

#### 'version' requirement in `composer.json`
1. Ensure that `composer.json` has no `version` key (according to Composer best practices)
1. Run `bin/magento sampledata:deploy`
1. Witness (lack of) error messaging and (lack of) changes in `composer.json`

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36554: Remove 'version' manipulation from sampledata:deploy, improve success messaging

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by engcom-Delta** [comment]
Hi @fredden,

This issue has been checked with the following

1.  Magento 2.4-develop
2. PHP 8.1

**Manual testing scenario:**
1. checked composer.json has no version key
2. Run bin/magento sampledata:deploy

Before PR changes we are getting as below

Screenshot 2022-11-19 at 10 12 51 AM

After PR changes we are getting as below

Screenshot 2022-11-19 at 11 25 00 AM

Could you please check that the PR changes are as expected and please let us know if we are missed any steps.

Thanks.

**Comment by fredden** [comment]
@engcom-Delta thanks for testing this. It looks like you have successfully tested the part of this change which stops this command manipulating the `composer.json` file.
I suspect that the reason you're not being offered any packages to install is because you have not installed Magento via composer. Please can you install Magento via composer and try again?

**Comment by engcom-Lima** [comment]
@magento create issue

**Pull request merged**
