### PR TITLE
MC-37692: [Issue] Check if single store mode is enabled

### LINKED ISSUE #29445: [Issue] Check if single store mode is enabled
This issue is automatically created based on existing pull request: magento/magento2#29391: Check if single store mode is enabled

---------
### Description (*)
Check if single store mode is enabled, not just if there is a single store. Allowing you to select the store you wish to place the order under.

### Preconditions (*)
Magento 2.4 installed

### Steps to reproduce (*)
1. Set up Magento with single store (store code `default`, website code `default`)
2. Configure web server so that when in the admin the `MAGE_RUN_CODE` is `admin`
3. Disable single store mode in the admin.
4. Configure a payment method to be enabled at admin level, for 'Default config', but disabled in scope for the `Main website'
5. In the Magento admin, begin creating an order.
  - new customer
  - add product (if possible see below)

### Expected result (*)
Payment methods should contain the one that is enabled at admin level.

### Actual result (*)
Payment methods available only those which are enabled for Main website.

### Questions or comments
This issue is hard to completely show/explain, as it heavily dependant on store setup. For example:
- if not products are enabled for the admin, (only at website level) you will be unable to select products to add the order.
- Even though single store mode is disabled, you aren't presented with the option to select the store you wish to place the order for.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by engcom-Echo**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#29445

### Manual testing scenarios (*)

1. See magento/magento2#29445

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @engcom-Echo,
Could you cover your changes with some automated test?

**Comment by engcom-Echo** [comment]
Hi @ihor-sviziev. So it will be done. Let's see how the changes will affect the existing tests, I think there will be many falls.
Thank you for joining

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@sivaschenko @sidolov could you check why the tests are not starting?

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@ihor-sviziev launched, please let me know if you still cannot trigger the tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Please review and fix test failures

**Pull request closed without merging**
