### PR TITLE
#33586: fix php warning message at search advansed result and index pages

### LINKED ISSUE #33586: Warning: trim() expects parameter 1 to be string, array given | magento/module-catalog-search
### Preconditions (*)

- Magento 2.4.2
- PHP 7.4

### Steps to reproduce (*)

Pass an array to any advanced search string input
For example: `/catalogsearch/advanced/result/?name[]=error`

### Expected result (*)

It should not throw an unhandled error.

### Actual result (*)

```
Warning: trim() expects parameter 1 to be string, array given in vendor/magento/module-catalog-search/Model/Advanced.php on line 201

Trace:
#1 trim() called at [vendor/magento/module-catalog-search/Model/Advanced.php:201]
#2 Magento\CatalogSearch\Model\Advanced->addFilters() called at [vendor/magento/module-catalog-search/Controller/Advanced/Result.php:62]
#3 Magento\CatalogSearch\Controller\Advanced\Result->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#4 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#5 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php:51]
#6 Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#7 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#8 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callPlugins() called at [generated/code/Magento/CatalogSearch/Controller/Advanced/Result/Interceptor.php:23]
#9 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#10 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#11 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#12 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#13 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callPlugins() called at [generated/code/Magento/CatalogSearch/Controller/Advanced/Result/Interceptor.php:32]
#14 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:186]
#15 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:118]
#16 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#17 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#18 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#19 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#20 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:75]
#21 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#22 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#23 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#24 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#25 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#26 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by korovitskyi**
…ages

### Description (*)
Fixed PHP errors at the  `catalogsearch/advanced/result` and `catalogsearch/advanced/index` pages.

### Fixed Issues

1. Fixes magento/magento2#33586

### Manual testing scenarios (*)

1.  Open page with URL and parametrs: `/catalogsearch/advanced/result/?name[]=somename`;
2.  Open page with URL and parametrs: `/catalogsearch/advanced/index/?name[]=somename`;

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by korovitskyi** [comment]
@magento run all tests

**Comment by korovitskyi** [comment]
@magento run all tests

**Comment by korovitskyi** [comment]
@magento run all tests

**Comment by korovitskyi** [comment]
Hi, @ihor-sviziev .
It was prepared solution to fix pages with path: `/catalogsearch/advanced/index` and `/catalogsearch/advanced/reult`, where params have an array value.
Can you check if it's ok to check params as an array and skip it?
Thank you.

**Review by nuzil — APPROVED** [review]
Hi @korovitskyi 
Thanks for your effort, looks good for me. Also test fail is not related to your PR

**Comment by engcom-Delta** [comment]
@magento run Functional Tests CE

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1.We should have fresh installation of Magento 2.4 Develop. 



**Manual testing scenario:**

1. Go to Frontend 
2. Click on 'Advanced Search ' link
3. Enter the product Name and click on 'Search' button
4. Replace the extended URL path with catalogsearch/advanced/result/?name[]=error 
5. Remove rest of text from URL and Press Enter
5. Validate the search results


**Before:** :heavy_multiplication_x: We had been getting exception 

Screenshot 2022-01-31 at 5 06 39 PM


**After:** :heavy_check_mark:  We are getting valid search results

Screenshot 2022-01-31 at 6 58 35 PM

Since it is URL tampered test case there is no additional regression required

**Pull request merged**
