### PR TITLE
breeze theme

### PR DESCRIPTION
**Pull request by Raza-Webiators**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Raza-Webiators** [comment]
merge this

**Comment by maaarghk** [comment]
lmao

**Comment by engcom-Charlie** [comment]
Hi @Raza-Webiators,

Thank you for your contribution!

In order to proceed further on this PR, can you please update the PR description. Kindly add Manual testing scenario, what is the expected and actual behaviour along with the screen shots or any other information which helps us to proceed further.

Thank you!

**Comment by mrtuvn** [comment]
if you need to use theme you should install it via composer instead. But in my opinion should not add custom theme in core it's may not fit with most of other demands

**Comment by hostep** [comment]
@vovayatsyuk, tagging you here, since this might be violating your copyright...

**Comment by vovayatsyuk** [comment]
I think someone is making its first steps with git/magento and mixed up their repo with magento))

**Pull request closed without merging**
