### PR TITLE
Issue #19417 Fixed

### PR DESCRIPTION
**Pull request by mahesh-rajawat**
Products added to a category are not shown at the frontend

### Description (*)

Assign a product to category, and schedule cron jobs, Product was not listing in category after running indexer via cron. Fixed now in this PR.
### Fixed Issues (if relevant)

1. #19417 
2. ...

### Manual testing scenarios (*)

1. Run magento indexer:reindex to make all indexes up to date.
2. Switch all indexes to the "Update Scheduled" mode.
3. Set up Cron.
4. Create a simple product (visible at the frontend, qty > 0)
5. Create a category.
6. Go to the frontend and make sure that the category is empty.
7. Open the created category (step 4) and assign the created product to it.
8. Save category changes.

Wait until Cron reindexes category changes or run magento indexer:reindex catalog_category_product.
Open the category at the frontend. Now products are listing.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by torhoehn — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @torhoehn, thank you for the review.
[ENGCOM-3682](https://jira.corp.magento.com/browse/ENGCOM-3682) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @maheshWebkul721 we found an issue while testing this PR - Products added to a category are not shown on frontend, can you please check it:

Manual testing scenario:

Run in console: 'php bin/magento indexer:reindex' to make all indexes up to date.
Go to Admin->System->Index Management
Switch all indexes to the "Update by Schedule" mode.
Create a simple product (visible at the frontend, qty > 0)
Create a category.
Go to the frontend and make sure that the category is empty.
Open the created category and assign the created before product to it.
Save category changes.
Run in console: 'php bin/magento indexer:reindex catalog_category_product'
Open the category at the frontend.

Actual Result: The category is still empty

**Comment by mahesh-rajawat** [comment]
@sivaschenko , i am working on it.

**Comment by sidolov** [comment]
Hi @maheshWebkul721 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
