### PR TITLE
Resolve Hidden custom Shipping Policy in Admin Store View scope 

### LINKED ISSUE #36425: Hidden custom Shipping Policy in Admin Store View scope
### Preconditions and environment

- Magento version 2.4-develop
- PHP 8.1
- Apply Shipping Policy.

### Steps to reproduce

1. Go to Stores => Settings => Configuration => Sales => Shipping Settings => Shipping Policy Parameters
2. Set 'Apply custom Shipping Policy' to Yes
3. Fill Shipping Policy field with text
4. Switch in Store View scope in admin.

### Expected result

Shipping Policy field visible in Store View scope

### Actual result

Shipping Policy field is not visible in Store View scope

### Additional information

1.Set 'Apply custom Shipping Policy' to No
2. Switch in Store View scope in admin.

Shipping Policy field visible in Store View scope

Screenshot 2022-11-10 at 4 57 02 PM

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

Resolve hidden custom Shipping Policy in Admin Store View scope #36425

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36425

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by angelo983** [comment]
@magento give me 2.4-develop instance

**Comment by angelo983** [comment]
@magento give me 2.4-develop instance

**Comment by angelo983** [comment]
@magento give me 2.4-develop instance

**Comment by angelo983** [comment]
@magento give me 2.4-develop instance

**Comment by angelo983** [comment]
@magento run all tests

**Comment by nishant04412** [comment]
Hi @ravi-chandra3197 and @angelo983,

This issue has been taken care in internal JIRA ticket. Once Internal PR will get merged, we will notify it here.

JIRA Ref: https://jira.corp.adobe.com/browse/AC-7003

Thank you!

**Comment by engcom-Hotel** [comment]
Hello @ravi-chandra3197,

Thank you for your contribution!

We discovered that the fix for this issue has been delivered internally. We apologize for missing that there is a public contribution available. We are taking measures to avoid situations like these in the future.

Thanks again!

**Pull request closed without merging**
