### PR TITLE
[Forwardport] Removed double occurrences from files.

### PR DESCRIPTION
**Pull request by mageprince**
### Original Pull Request 
 https://github.com/magento/magento2/pull/16581

### Description

Removed double occurrences from **jQuery, angular JS files** and **Magento Setup** module's scan function's comment.

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios

N/A

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mageprince. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-2222](https://jira.corp.magento.com/browse/ENGCOM-2222) has been created to process this Pull Request

**Comment by sanganinamrata** [comment]
@mageprince Hello,

I'll take care of my PR porting by myself.

Thanks :)

**Comment by mageprince** [comment]
Hi @sanganinamrata,

I think anyone can do PR porting on Magento 2 GitHub repository. Anyway thanks for your feedback. I will not do porting your PR.

Thanks :)

**Pull request closed without merging**
