### PR TITLE
Command to rebuild MySQL Triggers

### PR DESCRIPTION
**Pull request by josephmcdermott**
### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/6478

### Manual testing scenarios
1. Start with a 2.0.x instance with Indexers set to By Schedule.
2. Upgrade to 2.1.8 or 2.1.9.
3. In the DB, attempt to delete a row from catalog_product_entity_varchar.
4. Observe error: `ERROR 1054: 1054: Unknown column 'entity_id' in 'NEW'`.
5. Run CLI command `./bin/magento indexer:rebuild-triggers`.
6. Retry step 3 with success this time.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [-] All new or changed code is covered with unit/integration tests (if applicable)
 - [-] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by vrann** [comment]
@josephmcdermott is there any reason why this can't be a part of the UpgradeSchem.php script? I'm a bit hesitant introducing CLI command which will be used just once in a very specific use case (most SI or developers most likely will not use it ever) but it will be supported from version to version of Magento.

**Comment by josephmcdermott** [comment]
No not really, it could be a setup script. I use this kind of approach in local dev from time to time though (manually turning off and on via admin panel index management), as I often find on client DB's that the triggers are missing or are owned by another user, etc. so this can be quite useful.

**Comment by vrann** [comment]
@josephmcdermott would you be willing to convert it to setup script?

**Comment by josephmcdermott** [comment]
Went to have a look, and looks like you guys already have this in hand with the same approach:
https://github.com/magento/magento2/commit/78b796f1cf5df53e2883650cbbec7f36a53d1e8f

The install() method does the 'turn off and turn on' I was proposing, during every install/upgrade in the RecurringData class.

**Pull request closed without merging**
