### PR TITLE
DOM loads incorrect XML file: Better error message with more detail when...

### PR DESCRIPTION
**Pull request by SchumacherFM**
... a XML file is malformed.

When your fingers accidentially create an invalid XML file ;-) and you reload front end or backend then the current default error messages are like:

```
Catchable fatal error: Argument 1 passed to Magento\Framework\Config\Dom::_mergeNode() must be an instance of DOMElement, null given, called in /Users/OSXuser/Sites/magento2/site/lib/internal/Magento/Framework/Config/Dom.php on line 103 and defined in /Users/OSXuser/Sites/magento2/site/lib/internal/Magento/Framework/Config/Dom.php on line 118
```

```
Warning: DOMDocument::loadXML(): Start tag expected, '&lt;' not found in Entity, line: 14 in /Users/OSXuser/Sites/magento2/site/lib/internal/Magento/Framework/Config/Dom.php on line 321
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'DOMDocument::lo...', '/Users/OSXuser/Sit...', 321, Array)
#1 /Users/OSXuser/Sites/magento2/site/lib/internal/Magento/Framework/Config/Dom.php(321): DOMDocument->loadXML('<?xml version="...')
#2 /Users/OSXuser/Sites/magento2/site/lib/internal/Magento/Framework/Config/Dom.php(102): Magento\Framework\Config\Dom->_initDom('<?xml version="...')
```

```
Warning: DOMDocument::loadXML(): Start tag expected, '<' not found in Entity, line: 74 in /Users/OSXuser/Sites/magento2/site/lib/internal/Magento/Framework/Config/Dom.php on line 320

Catchable fatal error: Argument 1 passed to Magento\Framework\Config\Dom::_mergeNode() must be an instance of DOMElement, null given, called in /Users/OSXuser/Sites/magento2/site/lib/internal/Magento/Framework/Config/Dom.php on line 102 and defined in /Users/OSXuser/Sites/magento2/site/lib/internal/Magento/Framework/Config/Dom.php on line 117
```

It is pretty hard to figure out what is wrong. You can even get messages like that one:

screen shot 2015-01-10 at 5 48 52 pm

This implementation catches the error when `DOMDocument::loadXML()` fails to load the XML file.

The new error output is something like:

```
Invalid XML in file Magento/Integration/etc/frontend/routes.xml:
XML file content:
&lt;?xml version=&quot;1.0&quot;?&gt;
&lt;!--
/**
 * @copyright Copyright (c) 2014 X.commerce, Inc. (http://www.magentocommerce.com)
 */
--&gt;
&lt;config xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:noNamespaceSchemaLocation=&quot;../../../../../../lib/internal/Magento/Framework/App/etc/routes.xsd&quot;&gt;
    &lt;router id=&quot;standard&quot;&gt;
        &lt;route id=&quot;oauth&quot; frontName=&quot;oauth&quot;&gt;
            &lt;module name=&quot;Magento_Integration&quot; /&gt;
        &lt;/route&gt;
    &lt;/router&gt;
&lt;/xconfig&gt;

Stack trace ...
```

A small discussion could be needed regarding `htmlspecialchars()` because I think most output of these error messages will be in the browser....

Unit tests for this new feature are passing but one test is failing on my machine:

```
Magento\Tools\Di\Code\Scanner\XmlScannerTest::testCollectEntities
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 'Magento\Framework\App\Request...\Proxy'
 )
```

no idea :-(

### CODE REVIEW

**Comment by alankent** [comment]
Regarding htmlspecialchsrs(), should not be called too early. Eg error might go into json response. Html encoding should be done by presentation code (eg in phtml file) typically.
Another problem I hit a few times with xml errors was it did not always say the file name the error was in.

**Comment by SchumacherFM** [comment]
Thanks @kandy for pointing me to the right direction. I have a major rewrite of `Magento\Framework\Config\Dom` done and moved most of the stuff into `Magento/Framework/Xml/Parser`.

Also replaced a lot of calls `DOMDocument()` with the `Xml\Parser`.

Took me a couple of hours until everything worked so far. 

Error messages are now very descriptive and also @alankent the `htmlspecialchars` function is gone.

Some review in class `Magento\Framework\Config\Theme` is needed because layout update XML will not get validated which was before a @ todo annotation.

I hope this gets merged ...

```
Moved all DOMDocument() calls into Magento/Framework/Xml/Parser.
Refactored Magento\Framework\Config\Dom
Adjusted every single call to DOMDocument to call instead Xml\Parser.
Removed @todo for validation in Magento\Framework\Config\Theme because XML will be now validated.
Unit tests updated and added.
```

**Comment by SchumacherFM** [comment]
The failed test `Magento\Test\Php\LiveCodeTest::testCodeStylePsr2` is for coding style in `dev/tests/api-functional` which I haven't touched.

**Comment by amacgregor** [comment]
@SchumacherFM Having the same issue with Magento\Test\Php\LiveCodeTest::testCodeStylePsr2 on my pull request, the same test passes locally.

**Comment by mzeis** [comment]
@SchumacherFM The test `Magento\Tools\Di\Code\Scanner\XmlScannerTest::testCollectEntities` fails on my local machine too. 0.42.0-beta4, no files modified.

    php -v
    PHP 5.5.20-1~dotdeb.1 (cli) (built: Dec 19 2014 21:28:35)
    
    phpunit --version
    PHPUnit 4.4.1 by Sebastian Bergmann.`

**Comment by SchumacherFM** [comment]
@mzeis The test will fail on every machine where the var/generated folder exists. In this generated folder is the Proxy class.

A protected method here https://github.com/magento/magento2/blob/develop/dev%2Ftools%2FMagento%2FTools%2FDi%2FCode%2FScanner%2FXmlScanner.php#L63 check if the Proxy class NOT exists. If so the test passes. But if the proxy class exists (because of the var/generated/ folder) the test will fail.

Clear cache before running tests ;-)

**Comment by Vinai** [comment]
That should be done in the setup, no?

**Comment by vpelipenko** [comment]
@SchumacherFM, Travis build is still not green due to failed tests. Are you going to continue to work on fixing them?

**Comment by SchumacherFM** [comment]
Working on it!

**Comment by SchumacherFM** [comment]
Im stuck here and cannot / will not proceed:

```
cys at cys in ~/Sites/magento2/dev/tests/unit on develop
$ ../../../vendor/bin/phpunit -vvv
PHP Fatal error:  Class 'Magento\Setup\Model\UserConfigurationDataMapper' not found in /Users/cys/Sites/magento2/dev/tests/unit/testsuite/Magento/Setup/Controller/ConsoleControllerTest.php on line 287
PHP Stack trace:
PHP   1. {main}() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/phpunit:55
PHP   3. PHPUnit_TextUI_Command->run() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/TextUI/Command.php:132
PHP   4. PHPUnit_TextUI_Command->handleArguments() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/TextUI/Command.php:141
PHP   5. PHPUnit_Util_Configuration->getTestSuiteConfiguration() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/TextUI/Command.php:681
PHP   6. PHPUnit_Util_Configuration->getTestSuite() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/Util/Configuration.php:825
PHP   7. PHPUnit_Framework_TestSuite->addTestFiles() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/Util/Configuration.php:911
PHP   8. PHPUnit_Framework_TestSuite->addTestFile() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/Framework/TestSuite.php:411
PHP   9. PHPUnit_Framework_TestSuite->addTestSuite() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/Framework/TestSuite.php:386
PHP  10. PHPUnit_Framework_TestSuite->__construct() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/Framework/TestSuite.php:320
PHP  11. PHPUnit_Framework_TestSuite->addTestMethod() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/Framework/TestSuite.php:219
PHP  12. PHPUnit_Framework_TestSuite::createTest() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/Framework/TestSuite.php:800
PHP  13. PHPUnit_Util_Test::getProvidedData() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/Framework/TestSuite.php:472
PHP  14. ReflectionMethod->invoke() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/Util/Test.php:377
PHP  15. Magento\Setup\Controller\ConsoleControllerTest->helpActionForLanguageCurrencyTimezoneDataProvider() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/Util/Test.php:377
```

Any ideas?

**Comment by anupdugar** [comment]
Thanks @SchumacherFM. We will look into the test failure and let you know if we have any recommendations.

**Comment by anupdugar** [comment]
@SchumacherFM Can you try merging with the latest code and run the Unit tests again? I was able to successfully run them on my local and continuous integration environment.

**Comment by SchumacherFM** [comment]
Thanks for looking into it!

The tests are running and one test is failing. Gonna fix it.

But I'm getting this error:

```
........................................................... 11741 / 12174 ( 96%)
.......................................................PHP Warning:  call_user_func_array() expects parameter 2 to be array, null given in /Users/cys/Sites/magento2/app/code/Magento/Webapi/Controller/Rest.php on line 180
PHP Stack trace:
PHP   1. {main}() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/phpunit:55
PHP   3. PHPUnit_TextUI_Command->run() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/TextUI/Command.php:132
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/TextUI/Command.php:179
PHP   5. PHPUnit_Framework_TestSuite->run() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:426
PHP   6. PHPUnit_Framework_TestSuite->run() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/Framework/TestSuite.php:675
PHP   7. PHPUnit_Framework_TestSuite->run() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/Framework/TestSuite.php:675
PHP   8. PHPUnit_Framework_TestCase->run() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/Framework/TestSuite.php:675
PHP   9. PHPUnit_Framework_TestResult->run() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/Framework/TestCase.php:753
PHP  10. PHPUnit_Framework_TestCase->runBare() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/Framework/TestResult.php:686
PHP  11. PHPUnit_Framework_TestCase->runTest() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/Framework/TestCase.php:817
PHP  12. ReflectionMethod->invokeArgs() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/Framework/TestCase.php:951
PHP  13. Magento\Webapi\Controller\RestTest->testOverrideParams() /Users/cys/Sites/magento2/vendor/phpunit/phpunit/src/Framework/TestCase.php:951
PHP  14. Magento\Webapi\Controller\Rest->dispatch() /Users/cys/Sites/magento2/dev/tests/unit/testsuite/Magento/Webapi/Controller/RestTest.php:262
PHP  15. call_user_func_array:{/Users/cys/Sites/magento2/app/code/Magento/Webapi/Controller/Rest.php:180}() /Users/cys/Sites/magento2/app/code/Magento/Webapi/Controller/Rest.php:180
.
```

**Comment by SchumacherFM** [comment]
Fixing the integration errors ...

**Comment by anupdugar** [comment]
@SchumacherFM We have a bug internally to fix the warning : MAGETWO-34563. Thanks for pointing that out.

**Comment by anupdugar** [comment]
@SchumacherFM Any update on this?

**Comment by SchumacherFM** [comment]
Not yet

**Comment by SchumacherFM** [comment]
I will resend this PR. Something is weird.

**Comment by anupdugar** [comment]
Not a problem @SchumacherFM. Feel free to open another one, once you have issues resolved on your end. Thanks again!

**Pull request closed without merging**
