### PR TITLE
Magento_Sales integration tests: fix invoice_list fixture var tags

### PR DESCRIPTION
**Pull request by evktalo**
### Description

In the invoice_list fixture for Magento/Sales integration tests, the var tags changed in this pull request refer to non-existing variables and the other has a wrong type.

### Fixed Issues (if relevant)

None.

### Manual testing scenarios

1. Open the fixture file in PHPStorm
2. Check if usage of the variables in the var tags can be found
3. Check if the type of the variable is shown correctly

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @evktalo. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-2115](https://jira.corp.magento.com/browse/ENGCOM-2115) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@evktalo thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by orlangur** [comment]
Hi @evktalo! Any contributions should be applied to `2.2-develop` first, please create corresponding 2.2 PRs for both of your PRs.

**Comment by magento-engcom-team** [comment]
Hi @evktalo. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.3.0 release.

**Pull request merged**
