### PR TITLE
Fix external links to the Magento technical documentation

### PR DESCRIPTION
**Pull request by dshevtsov**
### Description (*)

Fix broken links and update obsolete links to devdocs.magento.com and docs.magento.com domains.

### Manual testing scenarios (*)

1. Click a link to devdocs.magento.com or docs.magento.com domains
2. The requested HTML page is successfully rendered with no errors
3. The page is of latest version of the topic (2.3)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24036) <br/>All committers have signed the CLA.

**Comment by hostep** [comment]
@dshevtsov: wouldn't it make more sense to have some sort of `latest` part in the url on devdocs instead of a fixed version number which will change every year or so?
I already suggested something like that a while ago: https://github.com/magento/devdocs/issues/924#issuecomment-266825555

**Comment by dshevtsov** [comment]
@hostep yes, it would, for sure. This is in the DevDocs team roadmap and we've been discussing different ways of how to get closer to this.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-5553](https://jira.corp.magento.com/browse/ENGCOM-5553) has been created to process this Pull Request
:eight_spoked_asterisk: @rogyar, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
