### PR TITLE
Clearer PHPDocs comment for AbstractBlock and Escaper

### PR DESCRIPTION
**Pull request by edward-simpson**
### Description (*)
Improvement/clarification of PHPDocs comment for escapeJsQuote as I felt the use of the word "quote" when referring to what is actually an 'apostrophe' was a bit misleading

`Magento\Framework\View\Element\AbstractBlock::escapeJsQuote`
`Magento\Framework\Escaper::escapeJsQuote`

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-6235](https://jira.corp.magento.com/browse/ENGCOM-6235) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@edward-simpson thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by rogyar** [comment]
Hi @edward-simpson. Please, take a look at the failing static tests. The short description for functions/methods should be in single-line format.

**Comment by engcom-Alfa** [comment]
QA not applicable

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-6235](https://jira.corp.magento.com/browse/ENGCOM-6235) has been created to process this Pull Request

**Comment by okorshenko** [comment]
@magento run Semantic Version Checker build

**Comment by okorshenko** [comment]
@magento run Semantic Version Checker

**Comment by slavvka** [comment]
The PR is being imported now

**Comment by slavvka** [comment]
@magento run Semantic Version Checker

**Pull request merged**
