### PR TITLE
Fix accessibility errors on cart and checkout pages

### LINKED ISSUE #34483: [Issue] Fix accessibility errors on cart and checkout pages
This issue is automatically created based on existing pull request: magento/magento2#33851: Fix accessibility errors on cart and checkout pages

---------
### Description (*)
This PR fixes Accessibility errors reported by Lighthouse module (Available in Chrome dev tools) on the shopping cart and checkout pages.

### Manual testing scenarios (*)
1. Open _Stores > Configuration > Sales > Sales > Gift Options_ and enable gift messages for both orders and per item levels.
2. Add product to the cart.
3. Navigate to the shopping cart page and run the Lighthouse accessibility test. There is an "ARIA IDs are not unique" error.
4. Navigate to the checkout page and run the Lighthouse accessibility test. There are navigation and ARIA errors.
5. Apply the patch and check the pages again.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by vovayatsyuk**
### Description (*)
This PR fixes Accessibility errors reported by Lighthouse module (Available in Chrome dev tools) on the shopping cart and checkout pages.

### Manual testing scenarios (*)
1. Open _Stores > Configuration > Sales > Sales > Gift Options_ and enable gift messages for both orders and per item levels.
2. Add product to the cart.
3. Navigate to the shopping cart page and run the Lighthouse accessibility test. There is an "ARIA IDs are not unique" error.
4. Navigate to the checkout page and run the Lighthouse accessibility test. There are navigation and ARIA errors.
5. Apply the patch and check the pages again.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#34483: Fix accessibility errors on cart and checkout pages

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Unit Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by vovayatsyuk** [comment]
@magento run Functional Tests CE

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9188](https://jira.corp.magento.com/browse/ENGCOM-9188) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9188](https://jira.corp.magento.com/browse/ENGCOM-9188) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Have a Magento installed with Sample data


**Manual testing scenario:**

1. Open Stores > Configuration > Sales > Sales > Gift Options and enable gift messages for both orders and per item levels.

2. Front end: Add product to the cart.
 
3. Navigate to the shopping cart page and run the Lighthouse accessibility test; Validate the result.

4. Navigate to the checkout page and run the Lighthouse accessibility test; Validate the result.


**Before:** :heavy_multiplication_x: Shopping cart checkout pages were giving an "ARIA IDs are not unique" error with ~90% accessibility result and Checkout payment page were with navigation and ARIA errors.

image


**After:** :heavy_check_mark: Shopping cart checkout pages are with 100% accessibility result without errors and Checkout payment page also with 98% without navigation and ARIA errors.

image

Since this fix relevant to accessibility result fix and has no impact on functional regression, there is no additional testing is required on this!

**Pull request merged**
