### PR TITLE
Use a temp table for category/product indexing

### PR DESCRIPTION
**Pull request by toddbc**
This avoids an expensive LIKE operation on each row, and front-loads the work beforehand.

For a full category/product reindex, this typically reduces the time taken by more than 90% (99% in my examples with largish product catalogs.)  It helps less for incremental reindexes.

### CODE REVIEW

**Comment by mazhalai** [comment]
@toddbc can you please sync with develop branch?

**Comment by toddbc** [comment]
Rebased.

**Comment by toddbc** [comment]
Hmm, looks like there's a regression - we haven't used this much on Magento 2, so maybe I made a mistake when applying.  Will investigate, but won't be right away - sorry.

**Comment by toddbc** [comment]
Fixed.  Had lost the query() around insertFromSelect().

Also corrected a compatibility issue with MySQL 5.7.

**Comment by adragus-inviqa** [comment]
What happens with the temp table on an exception? Also, would it better to have just a slight touch of randomness in the temp table's name (some substring of md5, sha1 etc.)?

**Comment by toddbc** [comment]
Temp tables are by nature per-connection.  This means:
1. If two clients connect to MySQL, they cannot see each other's temp tables.  They can both create a temp table named "temp" and they won't conflict or overlap.
2. Once the connection is closed, the temp table will automatically be destroyed by MySQL.
3. If a connection is not closed and reused (i.e. because persistent db connections are enabled), the temp table MAY still exist.  This is why we attempt to drop it before creating it.

One thing to note: `CREATE TEMPORARY TABLE` does not issue an implicit `COMMIT` like `CREATE TABLE` does, BUT it also does not rollback (the temp table will still exist.)  So even if the transaction is rolled back by an exception, a reused connection may STILL have the table.  That's again why it's necessary to `DROP TEMPORARY TABLE IF EXISTS` first.

The indexer code already uses temp tables for other things, so this isn't really introducing any new risk.  I don't believe it uses hashes for the names, and it doesn't really need to.

**Comment by rganin** [comment]
@toddbc , thanks for your contribution.
Internal ticket created: MAGETWO-52316.

**Comment by vzabaznov** [comment]
Hi @toddbc PR was merged and will be delivered in next release, thank you for contributing

**Pull request closed without merging**
