### PR TITLE
#24581 Added unique key on eav_attribute_label table

### LINKED ISSUE #24581: MIssing unique key on eav_attribute_label table
### Summary (*)

Magento 2.4-develop

The table `eav_attribute_label` should contain a unique key constraint on the (`store_id`, `attribute_id`) pair.  
Version: 
 - Identified on 2.3.2 Magento Open Source 
 - Checked table structure for version 2.2.6, key is still missing. 
 - Didn't check versions prior to 2.2.6, but most probably it has been there since the beginning of time.

_Also layered navigation disappears on frontend._

**Relates issues:**
https://github.com/magento/magento2/issues/24581 
https://github.com/magento/magento2/issues/24718

**Steps to reproduce:**

1. Create a product with any attribute;
2. Open `eav_attribute_label` and add a new row with the same `attribute_id` and `store_id` values

Screenshot from 2020-11-24 14-30-57

3. Go to Storefront -> Product page

**Actual Result:** :heavy_multiplication_x: Item with the same id already exists.

Screenshot from 2020-11-24 13-11-13

**Expected Result:** :heavy_check_mark: should be notified that duplicate values cannot be created for these fields

Screenshot from 2020-11-24 13-22-27

### Examples (*)
One (faulty?) 3rd party extension inserted something in the `eav_attribute_label` using `insertOnDuplicate`, but since there is no unique key on the table I ended up with duplicate pairs (store_id, attribute_id).
This resulted in "item with id X already exists" error when loading attribute labels

### Proposed solution
Add a unique key  constraint on the (`store_id`, `attribute_id`) pair.  

```
        <constraint xsi:type="unique" referenceId="EAV_ATTRIBUTE_LABEL_ATTRIBUTE_ID_STORE_ID_UNIQUE">
            <column name="store_id"/>
            <column name="attribute_id"/>
        </constraint>
``` 

as a bonus, since this is becoming a unique index, the existing index on the store_id, attribute_id pair can be dropped

```
        <index referenceId="EAV_ATTRIBUTE_LABEL_ATTRIBUTE_ID_STORE_ID" indexType="btree">
            <column name="attribute_id"/>
            <column name="store_id"/>
        </index>
```

### PR DESCRIPTION
**Pull request by KaushikChavda**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#24581: Missing unique key on eav_attribute_label table

### Manual testing scenarios (*)

1. Installed fresh magento2.3-develop and the unique key was missing
2. After added the unique key to table reinstall Magento and its fixed.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24682) <br/>All committers have signed the CLA.

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @KaushikChavda, please, sign CLA, otherwise, we can't process your pull request

**Comment by KaushikChavda** [comment]
> Hi @KaushikChavda, please, sign CLA, otherwise, we can't process your pull request

I've signed already.

**Comment by KaushikChavda** [comment]
> Hi @KaushikChavda, please, sign CLA, otherwise, we can't process your pull request

Hello @VladimirZaets could you please review now, I've sign the CLA.

**Comment by KaushikChavda** [comment]
@VladimirZaets VladimirZaets & @akaplya 

Please let me know what things are pending as all checks are Success.

Thanks

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5977](https://jira.corp.magento.com/browse/ENGCOM-5977) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by ihor-sviziev** [comment]
FYI changes from this PR were reverted in f3d3bce01229df6c47949036bf04921b52ecd6ba

**Pull request merged**
