### PR TITLE
Asynchronous operation validate

### PR DESCRIPTION
**Pull request by sedonik**
### Description

Added Magento\AsynchronousOperations\Model\OperationStatusPool and Magento\AsynchronousOperations\Model\OperationStatusValidator classes. 
Added list of statuses to Magento\AsynchronousOperations\Model\OperationStatusPool with di.xml file.
Added validation to Magento\AsynchronousOperations\Model\Operation::setStatus method. 

### Fixed Issues

1. magento/async-import#100: Add Operation Status validator

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sedonik** [comment]
Hi @nuzil ,

I've created new PR similar to https://github.com/magento/async-import/pull/110.
Could you check, please?

Thanks.

**Comment by nuzil** [comment]
Let’s wait for tests to finish. But I am for it

**Review by nuzil — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-6439](https://jira.corp.magento.com/browse/ENGCOM-6439) has been created to process this Pull Request
:eight_spoked_asterisk: @nuzil, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
