### PR TITLE
improve test AccountTest

### LINKED ISSUE #29700: [Issue] improve test AccountTest
This issue is automatically created based on existing pull request: magento/magento2#29693: improve test AccountTest

---------

### Description (*)

Improve test `dev/tests/integration/testsuite/Magento/Customer/Controller/AccountTest`
Now assert is based on _XPath_ selector instead of _assertStringContainsString_

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by engcom-Charlie**
### Description (*)

Improve test `dev/tests/integration/testsuite/Magento/Customer/Controller/AccountTest`
Now assert is based on _XPath_ selector instead of _assertStringContainsString_

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29700: improve test AccountTest

### CODE REVIEW

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8041](https://jira.corp.magento.com/browse/ENGCOM-8041) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Kilo** [comment]
@magento create issue

**Pull request merged**
