### PR TITLE
Replace repetitive actions with Action Groups in AdminCreateInactiveFlatCategoryTest and AdminUpdateFlatCategoryAndAddProductsTest

### LINKED ISSUE #34490: [Issue] Replace repetitive actions with Action Groups in AdminCreateInactiveFlatCategoryTest and AdminUpdateFlatCategoryAndAddProductsTest
This issue is automatically created based on existing pull request: magento/magento2#34470: Replace repetitive actions with Action Groups in AdminCreateInactiveFlatCategoryTest and AdminUpdateFlatCategoryAndAddProductsTest

---------

### Fixed Issues (if relevant)

Tests are refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run test locally

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Fixed Issues (if relevant)

Tests are refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run test locally

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#34490: Replace repetitive actions with Action Groups in AdminCreateInactiveFlatCategoryTest and AdminUpdateFlatCategoryAndAddProductsTest

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by shikhamis11** [comment]
@kate-kyzyma can you merge this and #34487 into this one and close another one?

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@shikhamis11
Done. https://github.com/magento/magento2/pull/34487 was merged into this one and closed.

**Comment by shikhamis11** [comment]
@magento create issue

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Semantic Version Checker

**Comment by shikhamis11** [comment]
@kate-kyzyma please check the `Semantic Version Checker` test details 
It seems you missed some keys while refactoring.

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@shikhamis11 
Done. The issue is fixed.

**Comment by shikhamis11** [comment]
@magento run Functional Tests B2B

**Pull request merged**
