### PR TITLE
Re-apply fix for JS error in the customer data

### LINKED ISSUE #31920: JS error in the customer data
Originally this issue was reported in https://github.com/magento/magento2/commit/5983e1733d56b1b2f15fb4f0e64094a3a4f3145d#commitcomment-44080850 by @HenKun.

The following commit https://github.com/magento/magento2/commit/5983e1733d56b1b2f15fb4f0e64094a3a4f3145d leads to similar issues described in https://github.com/magento/magento2/pull/24847.

### Preconditions (*)

1. Magento 2.4.1, or 2.4-develop

### Steps to reproduce (*)

1. Add the following code to the page on frontend:
```html
<script>
    require(['Magento_Customer/js/customer-data'], function (customerData) {
        console.log(customerData.getExpiredSectionNames());
    });
</script>
```
2. Go to the frontend, see the console

### Expected result (*)

1. In the console you should see an empty array, like this: 
image

### Actual result (*)

1. in the console we see the following error:
image

### Additional info from Engcom
Add the script to, for example, /app/code/Magento/Customer/view/frontend/templates/form/edit.phtml
script

1. In the Storefront, Sign In as a Customer
2. Go to _My Account_
3. Click **Edit** under _Contact Information_
4. Observe the dev console

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by TuVanDev**
### Description (*)
The fixes for issue #31920 in PR [31940](https://github.com/magento/magento2/pull/31940) were removed [accidentally](https://github.com/magento/magento2/commit/405ee6ebdfb9a3df7455153eb11af2f91fdba562). This PR revert code changes in PR [31940](https://github.com/magento/magento2/pull/31940) for fixing errors in customer data when component is not initialized.

### Related Pull Requests
- [31940](https://github.com/magento/magento2/pull/31940)

### Related Commits
- https://github.com/magento/magento2/pull/31940/commits/240253770cf2c41430d494c17730fe6484cbc18f
- https://github.com/magento/magento2/commit/405ee6ebdfb9a3df7455153eb11af2f91fdba562

### Fixed Issues (if relevant)
1. Fixes magento/magento2#31920

### Manual testing scenarios (*)
1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Viper9x** [comment]
@magento run all tests

**Comment by Viper9x** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE,Unit Tests

**Comment by Viper9x** [comment]
@magento run Functional Tests B2B,Unit Tests

**Comment by Viper9x** [comment]
@magento run Functional Tests B2B,Unit Tests

**Comment by Viper9x** [comment]
@magento run Unit Tests

**Comment by Viper9x** [comment]
@magento run Unit Tests

**Comment by Viper9x** [comment]
@magento run Unit Tests

**Comment by Viper9x** [comment]
@magento run Unit Tests

**Comment by Viper9x** [comment]
@magento run Unit Tests

**Comment by Viper9x** [comment]
@magento run all tests

**Comment by Viper9x** [comment]
@magento run Functional Tests B2B,Functional Tests EE,Integration Tests, Unit Tests

**Comment by Viper9x** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
https://github.com/magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@sidolov @sivaschenko, what's wrong with unit and integration tests? We don't see any results

**Comment by sidolov** [comment]
@ihor-sviziev we are looking into the issue, thanks for the input!

**Comment by engcom-Lima** [comment]
@magento run Unit Tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento `2.4-develop`

**Manual testing scenario:**
1. Add the script to, for example, `/app/code/Magento/Customer/view/frontend/templates/form/edit.phtml`
```
<script>
    require(['Magento_Customer/js/customer-data'], function (customerData) {
        console.log(customerData.getExpiredSectionNames());
    });
</script>

```
2. In the Storefront, Sign In as a Customer
3. Go to My Account
4. Click Edit under Contact Information
5. Observe the dev console

**Before:** :heavy_multiplication_x:  Getting error in console.
Screenshot 2022-10-25 at 6 22 22 PM

**After:** :heavy_check_mark:  Getting array as expected.
Screenshot 2022-10-25 at 6 39 51 PM

Unit test is failed. Hence, moving it to extended testing.

**Comment by engcom-Echo** [comment]
@magento run Unit Tests

**Comment by engcom-Echo** [comment]
@ihor-sviziev @Viper9x,

PR(https://github.com/magento/magento2/pull/31940) were reverted (https://github.com/magento/magento2/commit/405ee6ebdfb9a3df7455153eb11af2f91fdba562) by internal team due to it caused regression issue.

**Issue:** "mage-cache-storage" cookie expiration date is not updated after "Cookie Lifetime" is changed.

Below are the details of issue.
**Steps To Reproduce:**

        1. Login as registered customer
        2. Make sure that following cookies expiration date is 1 day by default:
                  mage-cache-sessid
                  mage-cache-storage
                  section_data_ids
        3. Login as Admin
        4. Go to Stores>Configuration>General>Web>Default Cookie Settings
        5. Set Cookie Lifetime=1209600 (2 weeks)
        6. Click Save Config button
        7. Clear cache and make re-index
        8. Open new incognito window and login by the same customer again

**Actual Result:**
      mage-cache-sessid and section_data_ids cookies expiration date is changed to 2 weeks successfully.
      But mage-cache-storage expiration date is left as 1 day.

**Expected Result:**
      mage-cache-storage cookie expiration date is 2 weeks, the same as for mage-cache-sessid
      and section_data_ids cookies.

**Comment by ihor-sviziev** [comment]
Hi @Viper9x,
Could you please try to fix the issue listed above?

**Comment by Viper9x** [comment]
Hi @ihor-sviziev I'll take a look.

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by AshishKumarPundeer** [comment]
@Viper9x  @ihor-sviziev 
Thanks for the collaboration & contribution!

:heavy_multiplication_x: QA Failed

Re-apply fix for JS error in the customer data

**Manual Scenario Steps**

1. After taking the PR changes we have checked the [issue](https://github.com/magento/magento2/issues/31920 ) is got fixed. But for the [scenario](https://github.com/magento/magento2/pull/36177#issuecomment-1311305360)  we are still able to reproduce the same. Please find the attached screenshot for you references. 

Before taking the PR changes 
Screenshot 2023-02-15 at 7 54 04 PM

After taking the PR changes 
Screenshot 2023-02-15 at 8 08 54 PM

**Comment by engcom-Charlie** [comment]
As per this [comment](https://github.com/magento/magento2/pull/36177#issuecomment-1431511480), moving it to Changes Requested.

Thank you!

**Comment by ihor-sviziev** [comment]
So looks like if we can't accept these changes, we should always wrap our code in
```

**Comment by AshishKumarPundeer** [comment]
@ihor-sviziev and @Viper9x we are working on [mentioned](https://github.com/magento/magento2/pull/36177#issuecomment-1431511480) failure.

Thank you

**Comment by engcom-Charlie** [comment]
Pushed the code fix for [mentioned](https://github.com/magento/magento2/pull/36177#issuecomment-1434685460) issue on behalf of @AshishKumarPundeer 

Thank you!

**Comment by AshishKumarPundeer** [comment]
@magento run all tests

**Comment by AshishKumarPundeer** [comment]
@magento run Functional Tests EE

**Comment by AshishKumarPundeer** [comment]
@magento run Functional Tests EE

**Review by ihor-sviziev — APPROVED** [review]

**Comment by AshishKumarPundeer** [comment]
Functional Tests EE failures are different on last two run
Run1
Screenshot 2023-02-23 at 12 29 01 PM

Run2
Screenshot 2023-02-23 at 12 29 06 PM

Hence moving to further process

**Comment by engcom-Charlie** [comment]
Hi @Viper9x and @ihor-sviziev,

Thank you for the contribution!

I have tested the [issue](https://github.com/magento/magento2/issues/31920) with the PR changes and it’s working fine . Also the above [mentioned](https://github.com/magento/magento2/pull/36177#issuecomment-1431511480) regression is not occurring now. 

:heavy_check_mark:  QA Passed

**Steps to reproduce** 

1. Add the following code to the page on frontend:
```
<script>
    require(['Magento_Customer/js/customer-data'], function (customerData) {
        console.log(customerData.getExpiredSectionNames());
    });
</script>
```
2. Visit the storefront, check the console

**Before:** :heavy_multiplication_x: 
image

**After:** :heavy_check_mark: 
image


3. "mage-cache-storage" cookie expiration date is now getting updated after "Cookie Lifetime" is changed.
image

As the PR is now working as expected, moving it to Merge in Progress.

Thank you!

**Pull request merged**
