### PR TITLE
Fixes #23824: User data serialised multiple times on save when loaded…

### LINKED ISSUE #23824: User data serialised multiple times on save when loaded via loadByUsername
### Preconditions (*)

1. Magento 2.2.* or 2.3.*

### Steps to reproduce (*)

1. Load a user using the `loadByUsername` method of the model.
2. Set some data on the model.
3. Save the model.

### Expected result (*)

1. The model is saved with the `extra` field data properly serialised.

### Actual result (*)

1. The model is saved with the `extra` field data serialised twice, corrupting the data and preventing it from being properly unserialised. This can prevent login.

### PR DESCRIPTION
**Pull request by mustdobetter**
… via loadByUsername.

Unserialises the extra data when loading a user using the loadByUsername method of the User model.

### Description (*)

The User model provides a method to allow the loading of a user by its username. This however does not unserialise the `extra` field data. If the model is then saved, the already serialised data is serialised again in the `beforeSave` method, leading to data corruption. This fix unserialises the data in the `loadByUsername` method to ensure that the data is loaded as expected into the model and avoids the duplicate serialisation issue when loading a user by its username.

### Fixed Issues (if relevant)

1. magento/magento2#23824: User data serialised multiple times on save when loaded by loadByUsername

### Manual testing scenarios (*)

1. Load a user with some serialised data set in the `extra` field using using the `loadByUsername` method of the `Magento\User\Model\User` model class.
2. Make some modifications to the data.
3. Save the model using the `save` method of the model.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23827) <br/>All committers have signed the CLA.

**Review by Den4ik — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5640](https://jira.corp.magento.com/browse/ENGCOM-5640) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@mustdobetter thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
