### PR TITLE
Remove overwritten longhand CSS properties

### PR DESCRIPTION
**Pull request by DanielRuf**
### Description (*)

This PR removes and resolves overwritten longhand CSS properties.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento combine 24884

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on combining the pull requests for you

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-6026](https://jira.corp.magento.com/browse/ENGCOM-6026) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @DanielRuf. Could you resolve merge conflicts?

**Comment by DanielRuf** [comment]
Will do so later do.

**Comment by krzksz** [comment]
Hey @DanielRuf, are you still going to continue working on this issue?

**Comment by DanielRuf** [comment]
Will do so when I find some time this week.

**Comment by DanielRuf** [comment]
I will check today if there is still something that I have to do. Had not much time so far.

**Comment by engcom-Charlie** [comment]
Hello @DanielRuf, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Comment by DanielRuf** [comment]
> Please reopen and update if you wish to continue.

Hi, I can not reopen, the members of the group that I am in have not the rights to reopen PRs.
Please reopen for me.

**Comment by DanielRuf** [comment]
@magento run Integration Tests

**Comment by DanielRuf** [comment]
I can not really see what exactly fails in the integration tests because the CI is not that helpful at all.

So far I am done with my CSS changes here.

**Comment by DanielRuf** [comment]
It looks like the minifier tests are the problem: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/24889/3d6378a6040d975ef97587c85eaf1f41/Integration/allure-report-ee/index.html

> Minified CSS differs from initial minified CSS snapshot. Ensure that new CSS is fully valid for all supported browsers and replace old minified snapshot with new one.

How can we update the snapshot? Is this explained somewhere and can someone do this for this PR?

**Comment by rogyar** [comment]
Hi @DanielRuf. I believe we need to change the following fixture for comparison

https://github.com/magento/magento2/blob/4e6375b3aab5f9821bbc5ecf6df0c2f10c3d2017/dev/tests/integration/testsuite/Magento/Framework/View/_files/static/theme/web/css/styles.css

correspondingly to the changes introduced in this PR. So we have the integration tests green

**Comment by DanielRuf** [comment]
> How can we update the snapshot? Is this explained somewhere and can someone do this for this PR?

I still do not what and how I have to change there ;-) Help is very appreciated.

**Comment by rogyar** [comment]
Hi @DanielRuf. Fair enough. 

From my understanding, you need to minify the new version (introduced with your PR) of the following file `testsuite/Magento/Framework/View/_files/static/theme/web/css/styles.css` manually and replace the `testsuite/Magento/Framework/View/_files/static/expected/styles.magento.min.css` using the minified result.

**Comment by DanielRuf** [comment]
> From my understanding, you need to minify the new version (introduced with your PR) of the following file `testsuite/Magento/Framework/View/_files/static/theme/web/css/styles.css` manually

With which tool? Is there no script which does this?

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by DanielRuf** [comment]
> @magento run all tests

As there were no further changes regarding the minified files this does not change anything regarding the failing tests ;-)

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @DanielRuf. Can you please regenerate min CSS file and replace an existing one that placed in dev/tests/integration/testsuite/Magento/Framework/View/_files/static/expected/styles.magento.min.css. This file uses in integration test (dev/tests/integration/testsuite/Magento/Framework/View/Asset/MinifierTest.php). Please notify me if you will need any help

**Comment by DanielRuf** [comment]
> Hi @DanielRuf. Can you please regenerate min CSS file and replace an existing one that placed in dev/tests/integration/testsuite/Magento/Framework/View/_files/static/expected/styles.magento.min.css. This file uses in integration test (dev/tests/integration/testsuite/Magento/Framework/View/Asset/MinifierTest.php). Please notify me if you will need any help

Please see my previous comments. Which command can I use to generate / update these files locally?

**Comment by mrtuvn** [comment]
@DanielRuf in case you need integration test you can try setup warden for local testing
https://docs.warden.dev/configuration/magento2-testing.html#running-integration-tests

**Comment by DanielRuf** [comment]
Does this recreate the minifued files? Because I don't think so.

Still, we just need a new minified testbundle, nothing more. If you can do this then you are very welcome to provide / push it to my branch.

So far it seems there is no helpful answer or direct help with creating the new minified file and no one knows the right command for this.

I think it's best we close this PR here since I do not have a working Magento setup right now and there is no progress regarding the tests.

**Comment by gabrieldagama** [comment]
The risk was set to`low` due to: the suggested changes shouldn't impact other areas.

**Comment by engcom-Golf** [comment]
Hi @DanielRuf. Could you resolve merge conflicts?

**Comment by DanielRuf** [comment]
@engcom-Golf please read my last comments.

Short answer: no.

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by DanielRuf** [comment]
@engcom-Golf can you share the exact steps / commands that you used to generate the minified css file? That would be really helpful. Because so far no one provided this piece of information.

**Comment by engcom-Golf** [comment]
@DanielRuf minified file content is result of \Magento\Framework\Code\Minifier\Adapter\Css\CSSmin::minify(). It is invoked in dev/tests/integration/testsuite/Magento/Framework/View/Asset/MinifierTest.php
The actual result of the test execution on your PR branch equals to expected result as the logic of minification was not modified, just only input data was changed.

**Comment by DanielRuf** [comment]
> @DanielRuf minified file content is result of \Magento\Framework\Code\Minifier\Adapter\Css\CSSmin::minify(). It is invoked in dev/tests/integration/testsuite/Magento/Framework/View/Asset/MinifierTest.php

And how do I run these locally? This is what I still miss as information.

**Comment by engcom-Golf** [comment]
> And how do I run these locally? This is what I still miss as information.

You can run integration tests on the local environment using the following instructions:
https://devdocs.magento.com/guides/v2.4/test/integration/integration_test_execution.html

**Comment by DanielRuf** [comment]
> You can run integration tests on the local environment using the following instructions:
> [devdocs.magento.com/guides/v2.4/test/integration/integration_test_execution.html](https://devdocs.magento.com/guides/v2.4/test/integration/integration_test_execution.html)

Thank you very much.

**Comment by engcom-Golf** [comment]
Hi @DanielRuf. I can't properly modify the file through the online editor. Could I ask you to allow changes to a pull request branch using the following steps:
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Thank you!

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Hello @DanielRuf 
Please provide access to your branch according to https://github.com/magento/magento2/pull/24889#issuecomment-695994605
Otherwise, your PR should be closed due to no activity.

**Comment by DanielRuf** [comment]
> Otherwise, your PR should be closed due to no activity.

Closing as I see no option for this, probably because I moved the forked repo.

**Pull request closed without merging**
