### PR TITLE
Change commit to rollBack on fail

### PR DESCRIPTION
**Pull request by flancer64**
I suppose we should rollback transaction before exception. We are in the loop and we should not commit partial result on error or we should not use transaction at all.

### CODE REVIEW

**Comment by flancer64** [comment]
There is an error "The class StockManagement has a coupling between objects value of 13." related to the changes:

```
$ phpunit $TEST_FILTER
PHPUnit 4.1.0 by Sebastian Bergmann.
Configuration read from /home/travis/build/magento/magento2/dev/tests/static/phpunit.xml.dist
...FS
Time: 36.34 seconds, Memory: 327.75MB
There was 1 failure:
1) Magento\Test\Php\LiveCodeTest::testCodeMess
PHP Code Mess has found error(s):
/home/travis/build/magento/magento2/app/code/Magento/CatalogInventory/Model/StockManagement.php:19  The class StockManagement has a coupling between objects value of 13. Consider to reduce the number of dependencies under 13.
Failed asserting that 2 matches expected 0.
/home/travis/build/magento/magento2/dev/tests/static/testsuite/Magento/Test/Php/LiveCodeTest.php:233

FAILURES!                                        
Tests: 5, Assertions: 4, Failures: 1, Skipped: 1.
```

**Comment by okorshenko** [comment]
@flancer64 thank you for the fix. Don't worry about the static test. We can process this PR without green static test because the failure was not caused by your fix.

**Comment by magento-team** [comment]
@flancer64 thank you for your contribution

**Comment by Ctucker9233** [comment]
@magento-team This isn't included in 2.2.7. Why Not?

**Pull request merged**
