### PR TITLE
magento/magento2#32456: Admin Grid date range filter not working as expected.

### LINKED ISSUE #32456: Admin Grid date range filter not working as expected
### Preconditions (*)

1. Magento 2.4.1

### Steps to reproduce (*)

1. In Backend select "Sales/Orders".
2. Click on "Filters" and add a date range filter for "purchase date" and apply this filter. The filtered grid will appear as expected.
3. Click on "Clear all" to remove this filter
filter2

### Expected result (*)

After removing the filter the date range should be cleared when you click next time on "Filters". 

### Actual result (*)

The date range is still filled out. Even worse, if you click next time on "Apply filters" (without modifying the date range), this date range is not applied.

filter

- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by engcom-Foxtrot**
### Description (*)

Re-creation of https://github.com/magento/magento2/pull/32485.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32456.

### Manual testing scenarios (*)

1. See magento/magento2#32456.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Functional Tests EE

**Review by Den4ik — CHANGES_REQUESTED** [review]
@engcom-Foxtrot Thanks for tests.
Could you try move `value: shiftedValue` from `attr: {}` section to main `data-bind`

```
<input class="admin__control-text" type="text" data-bind="
    hasFocus: focused,
    datepicker: { storage: shiftedValue, options: options },
    valueUpdate: valueUpdate,
    value: shiftedValue,
    attr: {
        name: inputName,
        placeholder: placeholder,
        'aria-describedby': noticeId,
        disabled: disabled
    }" />
``` 

In my opinion it looks better instead of searching html element and clear it. Also this solution don't require changes in js file.

**Comment by engcom-Foxtrot** [comment]
> @engcom-Foxtrot Thanks for tests.
> Could you try move `value: shiftedValue` from `attr: {}` section to main `data-bind`
> 
> ```
> <input class="admin__control-text" type="text" data-bind="
>     hasFocus: focused,
>     datepicker: { storage: shiftedValue, options: options },
>     valueUpdate: valueUpdate,
>     value: shiftedValue,
>     attr: {
>         name: inputName,
>         placeholder: placeholder,
>         'aria-describedby': noticeId,
>         disabled: disabled
>     }" />
> ```
> 
> In my opinion it looks better instead of searching html element and clear it. Also this solution don't require changes in js file.

It's not, it requires some more changes to work.

**Comment by Den4ik** [comment]
> > @engcom-Foxtrot Thanks for tests.
> > Could you try move `value: shiftedValue` from `attr: {}` section to main `data-bind`
> > ```
> > <input class="admin__control-text" type="text" data-bind="
> >     hasFocus: focused,
> >     datepicker: { storage: shiftedValue, options: options },
> >     valueUpdate: valueUpdate,
> >     value: shiftedValue,
> >     attr: {
> >         name: inputName,
> >         placeholder: placeholder,
> >         'aria-describedby': noticeId,
> >         disabled: disabled
> >     }" />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In my opinion it looks better instead of searching html element and clear it. Also this solution don't require changes in js file.
> 
> It's not, it requires some more changes to work.

Are you sure? Just checked and all work perfect.


https://user-images.githubusercontent.com/1129623/119327343-8acb7e00-bc8b-11eb-80e2-0100084cd002.mp4

**Comment by Den4ik** [comment]
From Slack discussion:
Moving `value: shiftedValue` to main `data-bind` section leads to lose first `0`.
This is problem of initialisation date format that is `M/d/y`.

In my opinion problem require more research and fix for main issue that hides deeper

**Comment by Den4ik** [comment]
**From Slack:**
This PR fixed issue described at https://github.com/magento/magento2/issues/32456 but in my opinion we should update PR by some reasons.
As I described in comment https://github.com/magento/magento2/pull/33027#pullrequestreview-663167090 `value` should be moved from `attr` section to main `data-bind`. It should be done because In this case we have different ways for input element update. Binding to value in `attr` section will not update input field because it’s bug or feature of [HTMLInputElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement) implementation. Visible value linked to HTMLInputElement `value` property.
`attr` section use `setAttribute` method of [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element) api implementation and this is don’t effect to value  property.
You may try experiment on this page, for example: https://developer.mozilla.org/en-US/docs/Web/API/Element
```
document.querySelectorAll("[id='main-q']")[0].value
""
document.querySelectorAll("[id='main-q']")[0].getAttribute('value')
null
document.querySelectorAll("[id='main-q']")[0].setAttribute('value', 1)
undefined
document.querySelectorAll("[id='main-q']")[0].value=2
2
document.querySelectorAll("[id='main-q']")[0].getAttribute('value')
"1"
document.querySelectorAll("[id='main-q']")[0].value
"2"
```
Moving `value: shiftedValue` to main `data-bind` section leads to lose first 0.
It’s happened  because currently we have incorrect initial dateFormat
So, my recommendation is fix main problem instead of making temporary fix and reporting another issue for future fix.

**Comment by Den4ik** [comment]
@engcom-Foxtrot I'm close this PR prior to https://github.com/magento/magento2/pull/33591

**Pull request closed without merging**
