### PR TITLE
Comma too much in calender

### LINKED ISSUE #37725: [Issue] Comma too much in calender
This issue is automatically created based on existing pull request: magento/magento2#34608: Comma too much in calender

---------

### Description (*)
This is simply an error in the spelling. The code snippet, contains a syntax error. The comma after the module name 'jquery' should be removed as it results in a redundant element.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by in-session**
### Description (*)
This is simply an error in the spelling. The code snippet, contains a syntax error. The comma after the module name 'jquery' should be removed as it results in a redundant element.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37725: Comma too much in calender

### CODE REVIEW

**Comment by in-session** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
Can you share screenshot before/after of this updates

**Comment by in-session** [comment]
@mrtuvn 
It's just a little bug within the phtml, you can see it in the changed files. In the last amendment of the file, the comma was forgotten to be removed.

**Comment by mrtuvn** [comment]
Seem this is new recent changes related condition load datepicker.

**Review by Den4ik — APPROVED** [review]

**Comment by Den4ik** [comment]
Failed tests is not related to changes but finally

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9344](https://jira.corp.magento.com/browse/ENGCOM-9344) has been created to process this Pull Request

**Comment by Den4ik** [comment]
@magento run Functional Tests B2B, Integration Tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Lima** [comment]
Hi @in-session ,

Thanks for your contribution and collaboration.

Please provide us steps to reproduce the issue as I have tried to reproduce the issue but issue is not reproducible to me. Below are the steps which I have followed:
1. Verified the console for any of the js error in the frontend by creating a product having custom options using date.
2. Verified js error by adding product into cart, mini cart and orders page of frontend.
3. Created a block having calendar and added to frotend and verified for any js error in the console.

Please refer this [document](https://developer.adobe.com/commerce/frontend-core/javascript/jquery-widgets/calendar/#code-sample) here sample code. Please provide us steps to reproduce the issue.

Thanks

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B ,Functional Tests EE, Functional Tests CE, WebAPI Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B ,Functional Tests EE, Functional Tests CE

**Comment by in-session** [comment]
> @in-session, it's not a big deal for most browsers to have redundant commas at the end. That's why this issue doesn't have such a high priority. It might be the issue only for bundling tools I guess.

@ihor-sviziev Yes, that's true, but it's still frustrating that a small change is lying around for 2 years and we have the same problem over and over again. And in that case you're right about that: _It might be the issue only for bundling tools I guess._ That the reason why we did this

**Comment by Den4ik** [comment]
@engcom-Lima @engcom-Charlie @sidolov I believe that we can just move this PR to Merge In Progress without any worries.

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

Functional Tests EE seems to be flaky. Hence, moving this PR to Merge in Progress.

**Test run 1:**
image

**Test run 2:**
image

**Pull request merged**
