### PR TITLE
[BUGFIX] Also set the Quantity for the product for correct tier pricing

### LINKED ISSUE #29655: [Issue] [BUGFIX] Also set the Quantity for the product for correct tier pricing
This issue is automatically created based on existing pull request: magento/magento2#28893: [BUGFIX] Also set the Quantity for the product for correct tier pricing

---------

### Description (*)

When you retrieve a cart through GraphQl after a quantity update for a product with tier pricing the single unit price is returned.

### Manual testing scenarios (*)

1. Add a product with a tier price to the cart
2. Change the Quantity
3. Generate customer token through graphql
4. Retrieve the cart through the cart call
_query {
  cart(cart_id: "SJRzyxm0GV04kZO53OtHD7KwgYhzpVWB"){
    items {
      uid
      quantity
      product{
        name
        sku
        price_tiers {
          quantity
          final_price {
            value
          }
          discount {
            amount_off
            percent_off
          }
        }
      }
      prices{
        price{
          value
        }
      }
    }
    prices {
      discounts {
        label
        amount {
          value
        }
      }
      subtotal_excluding_tax {
        value
      }
      applied_taxes {
        label
        amount {
          value
        }
      }
    }
  }
}_

**Expected result:** 
correct tier price has been applied
**Actual result:** 
price for quantity one is returned.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by lewisvoncken**
### Description (*)

When you retrieve a cart through GraphQl after a quantity update for a product with tier pricing the single unit price is returned.

### Manual testing scenarios (*)

1. Add a product with a tier price to the cart through GraphQl
2. Change the Quantity
3. Retrieve the cart through the cart call
4. expected result: correct tier price has been applied
5. actual result: price for quantity one is returned.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29655: [BUGFIX] Also set the Quantity for the product for correct tier pricing

### CODE REVIEW

**Review by davidverholen — APPROVED** [review]

**Comment by davidverholen** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @davidverholen, thank you for the review.
[ENGCOM-7754](https://jira.corp.magento.com/browse/ENGCOM-7754) has been created to process this Pull Request
:eight_spoked_asterisk: @davidverholen, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by davidverholen** [comment]
@lewisvoncken for some reason, only the B2B static test is failing because of the [missing class description](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/28893/18f2d70c5ac4c74a0567df2623e252ee/Statics/allure-report-b2b/index.html#suites/51d3ab4d5d77a0bc6a7ea344e9e7e6be)

can you add a valid description for the class then all should be green

**Comment by sidolov** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
@magento run Static Tests

**Comment by engcom-Alfa** [comment]
@magento run Static Tests

**Comment by engcom-Alfa** [comment]
Hi @lewisvoncken , @davidverholen 
Thanks for the collaboration & contribution!

:x: QA not Passed

Price of am cart item is not as per total quantity of the product, and the response item price is with one quantity only.

**Manual Scenario Steps**

1. Created a guest cart using GraphQL mutation
2. Added the product to cart as guest customer using a mutation mentioned below: 
`mutation {
  addSimpleProductsToCart(
    input: {
      cart_id: "a50lAXBWSqhPREDj6cGuTvpd5IBJCs7b"
      cart_items: [
        {
          data: {
            quantity: 1
            sku: "24-MB01"
          }
        }
      ]
    }
  ) {
    cart {
      items {
        id
        product {
          sku
          stock_status
        }
        quantity
        prices {
        total_item_discount {
          value
        }
        price {
          value
        }
        discounts {
          label
          amount {
            value
          }
        }
      }
      }
    }
  }
}`
3. Validated the response cart item  price


**:heavy_check_mark: Expected result After Fix** 
- Cart item price should return according to the total quantity added to the cart.
- If the product value is 34 and by adding 2 quantity, the price should be responded with the price 68


**:x: Actual result After Fix** 
- Cart item price is getting returned for one quantity of the product.
- If the product value is 34 and by adding 3 quantity to the cart, the price is responded with the 34 only
   afterfix


Additionally, a couple of below points also required to cover.
1. All the failure Auto-Test jobs should be passed in this PR
2. There is no auto-test has been covered relate to this PR, and it is required

Kindly cover above points also!

Thanks

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Requesting Changes as per above comment

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run Unit Tests

**Comment by engcom-Lima** [comment]
@magento run Unit Tests

**Comment by engcom-Lima** [comment]
Hi @lewisvoncken,
Thanks for the contribution
I tried to reproduce the issue on 2.4-develop, however the issue is not reproducible.

Steps followed to reproduce the issue:-

1. Install fresh Magento 2.4-develop instance
2. Create a simple product with tier price
Screenshot 2022-03-14 at 3 11 28 PM

3. Add that product to cart through GraphQl
**Request:**
```
mutation addProductsToCart {
  addProductsToCart(
    cartId: "wYysBYwuJj8THwQtzXEoO4oSgHYpdqJy"
    cartItems: [{ quantity: 1, sku: "24-MB01" }]
  ) {
    cart {
      items {
        product {
          name
          sku
        }
        quantity
      }
    }
  }
}
```

4. Update the quantity
**Request:**
```
mutation {
  updateCartItems(
    input: {
      cart_id: "wYysBYwuJj8THwQtzXEoO4oSgHYpdqJy",
      cart_items: [
        {
          cart_item_uid: "MTI="
          quantity: 20
        }
      ]
    }
  ){
    cart {
      items {
        uid
        product {
          name
        }
        quantity
      }
      prices {
        grand_total{
          value
          currency
        }
      }
    }
  }
}
```
5. Retrieve the cart through cart call
**Request:**
```
query {
  cart(cart_id: "wYysBYwuJj8THwQtzXEoO4oSgHYpdqJy"){
    items {
      uid
      quantity
      product{
        name
        sku
        price_tiers {
          quantity
          final_price {
            value
          }
          discount {
            amount_off
            percent_off
          }
        }
      }
      prices{
        price{
          value
        }
      }
    }
    prices {
      discounts {
        label
        amount {
          value
        }
      }
      subtotal_excluding_tax {
        value
      }
      applied_taxes {
        label
        amount {
          value
        }
      }
    }
  }
}
```
**Response:**
```
{
  "data": {
    "cart": {
      "items": [
        {
          "uid": "MTI=",
          "quantity": 20,
          "product": {
            "name": "Joust Duffle Bag",
            "sku": "24-MB01",
            "price_tiers": [
              {
                "quantity": 10,
                "final_price": {
                  "value": 9
                },
                "discount": {
                  "amount_off": 1,
                  "percent_off": 10
                }
              },
              {
                "quantity": 20,
                "final_price": {
                  "value": 8
                },
                "discount": {
                  "amount_off": 2,
                  "percent_off": 20
                }
              }
            ]
          },
          "prices": {
            "price": {
              "value": 8
            }
          }
        }
      ],
      "prices": {
        "discounts": null,
        "subtotal_excluding_tax": {
          "value": 160
        },
        "applied_taxes": []
      }
    }
  }
}
```

**Result:**
As we can see correct tier price is applied to the product and **160 USD** is appropriately returned for updated quantity **20**

**Comment by engcom-Lima** [comment]
In discussion with PO for confirmation hence moving this PR in On-Hold status.

**Comment by engcom-Alfa** [comment]
I tried to reproduce from my end also in Magento 2`.4-develop` version and below is the procedure I followed:

1. Created a new simple product with admin login UI and set the special pricing and tier prices as well as shown in the below screenshot.
image

2. Using GraphQL requests, retrieved a customer login token and followed by added the same product into the cart using a GraphQL query as below:
Request: `mutation {
  addSimpleProductsToCart(
    input: {
      cart_id: "{{CustomerCart}}"
      cart_items: [
        {
          data: {
            quantity: 5
            sku: "SimpleProd01"
          }
        }
      ]
    }
  ) {
    cart {
      items {
        id
        product {
          sku
          stock_status
        }
        quantity
      }
    }
  }
}`
Response is: `{
    "data": {
        "addSimpleProductsToCart": {
            "cart": {
                "items": [
                    {
                        "id": "21",
                        "product": {
                            "sku": "SimpleProd01",
                            "stock_status": "IN_STOCK"
                        },
                        "quantity": 5
                    }
                ]
            }
        }
    }
}`

3. Cross checked with the cart item details using a query as below-
Request: `query {
  cart(cart_id: "{{CustomerCart}}"){
    items {
      id
      uid
      quantity
      product{
        name
        sku
        price_tiers {
          quantity
          final_price {
            value
          }
          discount {
            amount_off
            percent_off
          }
        }
      }
      prices{
        price{
          value
        }
      }
    }
    prices {
      discounts {
        label
        amount {
          value
        }
      }
      subtotal_excluding_tax {
        value
      }
      applied_taxes {
        label
        amount {
          value
        }
      }
    }
  }
}`
Response `{
    "data": {
        "cart": {
            "items": [
                {
                    "id": "21",
                    "uid": "MjE=",
                    "quantity": 5,
                    "product": {
                        "name": "SimpleProd01",
                        "sku": "SimpleProd01",
                        "price_tiers": [
                            {
                                "quantity": 5,
                                "final_price": {
                                    "value": 8
                                },
                                "discount": {
                                    "amount_off": 2,
                                    "percent_off": 20
                                }
                            },
                            {
                                "quantity": 10,
                                "final_price": {
                                    "value": 7
                                },
                                "discount": {
                                    "amount_off": 3,
                                    "percent_off": 30
                                }
                            },
                            {
                                "quantity": 20,
                                "final_price": {
                                    "value": 6
                                },
                                "discount": {
                                    "amount_off": 4,
                                    "percent_off": 40
                                }
                            }
                        ]
                    },
                    "prices": {
                        "price": {
                            "value": 8
                        }
                    }
                }
            ],
            "prices": {
                "discounts": null,
                "subtotal_excluding_tax": {
                    "value": 40
                },
                "applied_taxes": []
            }
        }
    }
}`
**Here, the data response is as per the more discounted price of tier price setup.**

4. Again, updated the cart quantity of a product to 1 using a QraphQL query:
Request: `mutation {
	updateCartItems(
		input: {
			cart_id: "{{CustomerCart}}",
			cart_items: [
                {
					cart_item_id: 21 quantity: 1
				}
			]
		}) {
		cart {
			items {
				id product {
					name
				}
				quantity
			}
			prices {
				grand_total {
					value currency
				}
			}
		}
	}
}`
Response: `{
    "data": {
        "updateCartItems": {
            "cart": {
                "items": [
                    {
                        "id": "21",
                        "product": {
                            "name": "SimpleProd01"
                        },
                        "quantity": 1
                    }
                ],
                "prices": {
                    "grand_total": {
                        "value": 9,
                        "currency": "USD"
                    }
                }
            }
        }
    }
}`
5. Again cross checked with the cart item details using a query as same as step 3's request and we got the response as:
`{
    "data": {
        "cart": {
            "items": [
                {
                    "id": "21",
                    "uid": "MjE=",
                    "quantity": 1,
                    "product": {
                        "name": "SimpleProd01",
                        "sku": "SimpleProd01",
                        "price_tiers": [
                            {
                                "quantity": 5,
                                "final_price": {
                                    "value": 8
                                },
                                "discount": {
                                    "amount_off": 2,
                                    "percent_off": 20
                                }
                            },
                            {
                                "quantity": 10,
                                "final_price": {
                                    "value": 7
                                },
                                "discount": {
                                    "amount_off": 3,
                                    "percent_off": 30
                                }
                            },
                            {
                                "quantity": 20,
                                "final_price": {
                                    "value": 6
                                },
                                "discount": {
                                    "amount_off": 4,
                                    "percent_off": 40
                                }
                            }
                        ]
                    },
                    "prices": {
                        "price": {
                            "value": 9
                        }
                    }
                }
            ],
            "prices": {
                "discounts": null,
                "subtotal_excluding_tax": {
                    "value": 9
                },
                "applied_taxes": []
            }
        }
    }
}`
**Here, this time, it considered the special price rather than tier pricing because quantity is set to 1.**

Based on the above observation, we can consider that, the issue is not reproducible.
Anyhow, we will discuss internally and come to the conclusion before closing the ticket.

In case of any additional info to reproduce it, kindly help us with more detailed information like missing steps to reproduce, and if any configurations/settings required to be followed as a pre condition as such @lewisvoncken @davidverholen

**Comment by engcom-Lima** [comment]
As per [last comment ](https://github.com/magento/magento2/pull/28893#issuecomment-1227422759) issue is not reproducible and there is no update from long time. Hence, closing this PR. Please feel free to reopen this PR by commenting in same PR.

**Pull request closed without merging**
