### PR TITLE
Fixed 'magento' adding in the URL when Use Web Server Rewrites set to NO using Console Command #25976

### LINKED ISSUE #25976: 'magento' adding in the URL when Use Web Server Rewrites set to NO using Console Command
### Summary (*)

This is a Developer experience issue. I have created one simple console file that will generate product name, URL etc.

1. Magento 2.3.x with sample data
2. Use Web Server Rewrites field set to No
3. Clear cache if prompted

### Examples (*)

1. app/code/Custom/Pro/etc/di.xml

```
<?xml version="1.0"?> 
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Framework\Console\CommandListInterface">
        <arguments>
            <argument name="commands" xsi:type="array">
                <item name="checkProductURL" xsi:type="object">Custom\Pro\Console\Command\ProductURLFetch</item>
            </argument>
        </arguments>
    </type>
</config>
```

2. app/code/Custom/Pro/Console/Command/ProductURLFetch.php

```
<?php
 
namespace Custom\Pro\Console\Command;

use Magento\Catalog\Api\ProductRepositoryInterfaceFactory;
use Magento\Catalog\Model\ResourceModel\Product\CollectionFactory;
use Magento\Framework\App\ObjectManagerFactory;
use Magento\Framework\App\State;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;


class ProductURLFetch extends \Symfony\Component\Console\Command\Command
{
    /**
     * @var \Magento\Catalog\Api\ProductAttributeRepositoryInterface
     */
    protected $productAttributeRepository;

    /**
     * @var \Magento\Framework\Api\SearchCriteriaBuilder
     */
    protected $searchCriteriaBuilder;

    /**
     * @var \Magento\Catalog\Model\ResourceModel\Attribute
     */
    protected $attributeResource;

    /**
     * @var State
     */
    protected $appState;

    protected $_productRepositoryFactory;

    /**
     * @var \Magento\Framework\EntityManager\EntityMetadata
     */
    protected $metadata;

    /**
     * Object manager factory
     *
     * @var ObjectManagerFactory
     */
    private $objectManagerFactory;
    /**
     * @var CollectionFactory
     */
    private $collectionFactory;

    /**
     * @param ObjectManagerFactory $objectManagerFactory
     * @param CollectionFactory $collectionFactory
     * @param State $appState
     * @param ProductRepositoryInterfaceFactory $productRepositoryFactory
     */
    public function __construct(
        ObjectManagerFactory $objectManagerFactory,
        CollectionFactory $collectionFactory,
        State $appState,
        ProductRepositoryInterfaceFactory $productRepositoryFactory
    ) {
        $this->objectManagerFactory = $objectManagerFactory;
        $this->appState = $appState;
        $this->collectionFactory = $collectionFactory;
        $this->_productRepositoryFactory = $productRepositoryFactory;
        parent::__construct();
    }

    /**
     * {@inheritdoc}
     */
    protected function configure()
    {
        $this->setName('catalog:product:showurl');
        $this->setDescription('It will just show Product URLs.');
    }

    /**
     * {@inheritdoc}
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->appState->setAreaCode(\Magento\Framework\App\Area::AREA_FRONTEND);
        
        $productCollection = $this->collectionFactory->create();
        $output->setDecorated(true);
        $productCollection->addAttributeToSelect('name','sku','url');        
        try {
            foreach ($productCollection as $product){
                $output->writeln( $product->getProductURL()  );
            }

            $output->writeln("<info>Product URLs has been generated..</info>");

            return \Magento\Framework\Console\Cli::RETURN_SUCCESS;
        } catch (\Exception $exception) {

            $output->writeln("");
            $output->writeln("<error>{$exception->getMessage()}</error>");
            // we must have an exit code higher than zero to indicate something was wrong
            return \Magento\Framework\Console\Cli::RETURN_FAILURE;
        }
    }

}
```

Execute below console.
`php bin/magento catalog:product:showurl`

**Output**
URL in the output will be as follows:
http://www.example.com/magento/kir-1100.html

It should not contain '**magento**' as in the URL.
http://www.example.com/kir-1100.html

### Proposed solution

Looking into the file <magento-root>/vendor/magento/module-store/Model/Store.php
and function named `_updatePathUseRewrites` returns base URL with 'magento'.

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

Fixed 'magento' adding in the URL when Use Web Server Rewrites set to NO using Console Command #25976
### Fixed Issues (if relevant)

1. Fixes magento/magento2#25976

### Manual testing scenarios (*)

1. follow the same steps mentioned issue #25976
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by VladimirZaets** [comment]
@magento I am working on it

**Comment by VladimirZaets** [comment]
@magento I am working on it

**Comment by BarnyShergold** [comment]
@magento run all tests

**Review by sidolov — CHANGES_REQUESTED** [review]
@ravi-chandra3197  could you please cover changes with automated test?

**Comment by gabrieldagama** [comment]
Risk set to medium since Store is a critical module/feature on the platform and the changes may affect other areas.

**Comment by engcom-Echo** [comment]
Hi, @ravi-chandra3197 are you going to continue progress on that? 
Could you please check failed tests? Otherwise, we can't proceed with your PR.
Thank you.

**Comment by sidolov** [comment]
@ravi-chandra3197  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
