### PR TITLE
[Fixed Jump Datepicker issue in Catalog Price Rule]

### PR DESCRIPTION
**Pull request by hitesh-wagento**
### Description (*)
Fixed Jump Datepicker issue in Catalog Price Rule

### Fixed Issues (if relevant)

1. magento/magento2#26289: Jump Datepicker in Catalog Price Rule

### Manual testing scenarios (*)

1. Login to Backend
2. Go to Marketing => Promotions => Catalog Price Rule
3. Click on Datepicker

### Expected result

1. Datepicker does not jump in Catalog Price Rule
expected

### Actual result

1. Jump Datepicker in Catalog Price Rule
actual

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by ptylek** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @ptylek. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @ptylek, here is your [new Magento instance](https://pr-26290.instances.magento-community.engineering).
Admin access: [https://pr-26290.instances.magento-community.engineering/admin](https://pr-26290.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by ptylek — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-6550](https://jira.corp.magento.com/browse/ENGCOM-6550) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
