### PR TITLE
#7413 fix, downloadable in group not working

### PR DESCRIPTION
**Pull request by alekszakatov**
### Description (*)
Fix for https://github.com/magento/magento2/issues/7413
not sure why it was closed issue still reproducible in 2.4-develop

### Fixed Issues (if relevant)
    1. #7413
### Manual testing scenarios (*)
1. create 1-3 downloadable products with real files for download
2. create group product and assign previously create product to current group product
3. (optional) set in configuration Catalog->Downloadable product options - Order Item Status to Enable Downloads - PENDING and allow Disable Guest Checkout if Cart Contains Downloadable Items - NO
4. complete checkout with group product, links should be available in email and in admin, if it will be registered customer link should be available in download section 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by alekszakatov** [comment]
@magento run all tests

**Comment by alekszakatov** [comment]
@magento run all tests

**Comment by alekszakatov** [comment]
@magento run all tests

**Comment by alekszakatov** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
Hi @alekszakatov. Thanks for collaboration. This PR was reviewed on Community Contribution Triage meeting. The recording of the meeting you can look by the [link](https://www.youtube.com/watch?v=gsefmmeDMWM&list=PLDvMskiz68Q2BLkj0-xzjuFl7ZVti9Quj&index=2&t=639s)

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi, @alekszakatov thanks for the pull request, it looks good! All our changes now must be covered with tests, are you able to cover this one?

Please let me know if you are available for it. Thanks.

**Comment by gabrieldagama** [comment]
The risk was set to`low` due to: the suggested changes shouldn't affect other areas.

**Comment by gabrieldagama** [comment]
Hi @alekszakatov, looking at the `SaveDownloadableOrderItemObserver`, it seems we already have a solution for this issue:

```
$productType = $orderItem->getRealProductType() ?: $orderItem->getProductType();
```

I will close this PR for now, please feel free to reopen it if you think it's still necessary.
Thanks.

**Pull request closed without merging**
