### PR TITLE
[MFTF] Add new AdminOrderClickSubmitOrderActionGroup

### LINKED ISSUE #29649: [Issue] [MFTF] Add new AdminOrderClickSubmitOrderActionGroup
This issue is automatically created based on existing pull request: magento/magento2#29630: [MFTF] Add new AdminOrderClickSubmitOrderActionGroup

---------
This PR adds new  `AdminOrderClickSubmitOrderActionGroup`

### PR DESCRIPTION
**Pull request by Usik2203**
This PR adds new  `AdminOrderClickSubmitOrderActionGroup` 

### Resolved issues:
1. [x] resolves magento/magento2#29649: [MFTF] Add new AdminOrderClickSubmitOrderActionGroup

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Review by lbajsarowicz — APPROVED** [review]
✔️  Thanks for this improvement.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-8023](https://jira.corp.magento.com/browse/ENGCOM-8023) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by sidolov** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Pull request merged**
