### PR TITLE
Issue #24842: Unable to delete custom option file in admin order create

### PR DESCRIPTION
**Pull request by adrian-martinez-interactiv4**
Fix inputBox selector to match html structure.

### Fixed Issues (if relevant)

1. magento/magento2#24842: Unable to delete custom option file in admin order create

### Manual testing scenarios (*)

1. Follow magento/magento2#24842 steps to reproduce, and for actual and expected results.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — CHANGES_REQUESTED** [review]
@adrian-martinez-interactiv4 nice catch! Please, cover changes with the functional test to avoid such issues in the future. Thank you!

**Comment by adrian-martinez-interactiv4** [comment]
I've been looking at mftf files and examples, and sincerely, I don't know how to replicate use case of upload a file (or having a file uploaded), to check then that file box name gets striked-through and file gets erased...

**Review by lenaorobei — APPROVED** [review]

**Comment by lenaorobei** [comment]
@engcom-Echo please help with MFTF tests here.

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-6818](https://jira.corp.magento.com/browse/ENGCOM-6818) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

No JS error appears in the console. The order item is updated and the order proceeds
delete_file

**Comment by engcom-Echo** [comment]
I will take care of test coverage.

**Pull request merged**
