### PR TITLE
Notification counter design issue #23473

### PR DESCRIPTION
**Pull request by thurow**
### Description (*)
Fixing admin notification counter with more than 1 digit.

### Fixed Issues (if relevant)

1. magento/magento2#23473: Notification counter design issue

### Manual testing scenarios (*)

1. Log in into magento admin panel
2. See if the notification counter can afford more than 1 digit without breaking the circle
3. Manual update the number of notification if necessary to reproduce (put like 20, or 99+)

### Questions or comments

Captura de Tela 2019-09-14 às 11 33 31
Captura de Tela 2019-09-14 às 11 33 39
Captura de Tela 2019-09-14 às 11 36 29

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by thurow** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @thurow. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @thurow, here is your [Magento instance](https://i-24589-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24589-2-3-develop.instances.magento-community.engineering/admin](https://i-24589-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by kalpmehta — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, thank you for the review.
[ENGCOM-5840](https://jira.corp.magento.com/browse/ENGCOM-5840) has been created to process this Pull Request
:eight_spoked_asterisk: @kalpmehta, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
