### PR TITLE
Fixed apply discount coupons for bundle product

### PR DESCRIPTION
**Pull request by NikolasSumrak**
Fixed apply discount coupons for bundle product with both virtual and simple product and "Ship Bundle Items" = "Separately"

### Description (*)

Fix issue: Coupon doesn't work for bundle product
Preconditions:
1. Magento 2.2.8 Enterprise Edition
2. Have Bundle item with children:
- Simple product, default QTY = 1
- Virtual Product, default QTY = 1
3. Have Cart Price rule with coupon, some discount (e.g. 10%), with conditions:
If ANY  of these conditions are TRUE :
If an item is FOUND  in the cart with ANY  of these conditions true: 
SKU  is  SKU_OF_BUNDLE_PRODUCT

Steps to reproduce:
1. Add to cart this Bundle Item
2. Go to cart page
3. Apply coupon

Expected Result:
Coupon has been applied

Actual result:
Coupon has not been applied. 
Message "Invalid coupon code" shown.

### Manual testing scenarios (*)

See Description

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22987) <br/>All committers have signed the CLA.

**Review by orlangur — CHANGES_REQUESTED** [review]
Hi @NikolasSumrak,

I'm not sure such logic wasn't intentional, please write an integration test covering described case.

**Comment by engcom-Golf** [comment]
@orlangur hello, test added. Please review.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5360](https://jira.corp.magento.com/browse/ENGCOM-5360) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@NikolasSumrak thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by magento-engcom-team** [comment]
@NikolasSumrak thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request merged**
