### PR TITLE
[MFTF] Using action group to go to admin category page

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR using `AdminOpenCategoryPageActionGroup` to go to admin category page.
And changes this part of code 
`<amOnPage url="{{AdminCategoryPage.url}}" stepKey="goToCategoryPage"/>`
`<waitForPageLoad stepKey="waitForCategoryPageLoad"/>`

### CODE REVIEW

**Review by rogyar — CHANGES_REQUESTED** [review]
According to the failing tests most likely there's an issue on the test generation step. Usually, it happens when there's some error like missing action group or so. 

Could you, please, run the functional tests locally and make sure that you have no errors? 

Thank you!

**Comment by Usik2203** [comment]
Hi @rogyar .
I have fixed failed checks related with my changes. 
Errors in Functional Tests CE not related with my changes.

Thanks you!

**Review by lbajsarowicz — APPROVED** [review]
:+1: That is really nice of you that you decided to replace these Actions into ActionGroups. Thank you!

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7303](https://jira.corp.magento.com/browse/ENGCOM-7303) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

**Pull request merged**
