### PR TITLE
Bugfix #26479 Exception when Autoloader was not registered properly

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Issue for problem occured randomly with Integration Tests.

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/26479

### Manual testing scenarios (*)
1. Running Integration Tests, you should not get an error `Error: Call to a member function findFile() on array`

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @lbajsarowicz,
Could you fix failing static tests?

**Comment by lbajsarowicz** [comment]
@ihor-sviziev Changed the Exception type that was not expected to be generic Exception.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
I think cover this case with some tests will be hard, so putting “not required” label

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6674](https://jira.corp.magento.com/browse/ENGCOM-6674) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
