### PR TITLE
Resolve Missing "expand/collapse" icon in paypal setting (issue 24118)

### LINKED ISSUE #24118: Missing "expand/collapse" icon in paypal setting
### Preconditions (*)

1. 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Stores->Configuration
3. Sales->Payment Methods
4. Check the screen. No "expand/collapse" icon

image

### Expected result (*)

Have the icon:

image

### Actual result (*)

No icon:

image

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#24118: Missing "expand/collapse" icon in paypal setting

Solution: fix in style.css of Paypal module

### Fixed Issues (if relevant)

1. magento/magento2#24118: Missing "expand/collapse" icon in paypal setting

### Manual testing scenarios (*)

1. Go to backend
2. Stores->Configuration
3. Sales->Payment Methods
4. Check the screen. No "expand/collapse" icon

image

#### Expected result

Have the icon:

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-24119.instances.magento-community.engineering).
Admin access: [https://pr-24119.instances.magento-community.engineering/admin](https://pr-24119.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by josefbehr — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @josefbehr, thank you for the review.
[ENGCOM-5609](https://jira.corp.magento.com/browse/ENGCOM-5609) has been created to process this Pull Request
:eight_spoked_asterisk: @josefbehr, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:**
before

**After:**
after

**Pull request merged**
