### PR TITLE
[Backport] Fixed issue  Unable to open URL for downloadable product

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Original Pull Request 
 https://github.com/magento/magento2/pull/19996
Fixed issue Unable to open URL for downloadable product #18944
Preconditions (*)

1.  Magento V2.2.6 Clean Install.
2.  PHP 7.0.28
3.  No special caching is present.

Steps to reproduce (*)

1.   Create downloadable product.
2.    Add a link to this product, for example https://google.com
3.    Save product.
4.    Order product in front-end.
5.    After order status complete navigate to your downloadable products in front-end.
6.   Click the button to open the URL set in step 2 to download your product.

**Expected result (*)**

    A new page of https://google.com is opened and shown in browser.

 **Actual result (*)**

    Page is not opened correctly and error by Magento is thrown:
    Something went wrong while getting the requested content.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4297](https://jira.corp.magento.com/browse/ENGCOM-4297) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [new Magento instance](https://pr-21262.instances.magento-community.engineering).
Admin access: [https://pr-21262.instances.magento-community.engineering/admin](https://pr-21262.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Pull request merged**
