### PR TITLE
9830 - Null order in Magento\Sales\Block\Order\PrintShipment.php

### PR DESCRIPTION
**Pull request by MateuszChrapek**
**DESCRIPTION**
When trying to print the order information from customer's account view the following error is placed in httpd logs:
`Fatal error: Call to a member function getRealOrderId() on null in /vendor/magento/module-sales/Block/Order/PrintShipment.php`
The cause of this was additional AJAX request taking place after closing the print prompt as discussed by @ihor-sviziev in #9830, trying to render print information one additional time, however without registry properly initialized, it results in the error. I've changed the block that was causing this issue to be uncachable, which seems to be fixing the problem. I've also added changes that were added to 2.1 from #10530 that were not present in 2.2.

**FIXED ISSUES**

 - https://github.com/magento/magento2/issues/9830 Null order in Magento\Sales\Block\Order\PrintShipment.php
- https://github.com/magento/magento2/issues/10530 Print order error on magento 2.1.8

**MANUAL TESTING SCENARIOS**

- create a new order as logged customer
- go to your account page
- go to order view
- click 'Print order' button
- check httpd logs whether or not the error described in the #9830 is visible

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=17998) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @MateuszChrapek. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-2940](https://jira.corp.magento.com/browse/ENGCOM-2940) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @MateuszChrapek. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
