### PR TITLE
magento/magento2#: GraphQl. setPaymentMethodAndPlaceOrder. Remove redundant logic.

### PR DESCRIPTION
**Pull request by atwixfirster**
### Description (*)

PR removes a redundant logic in the `setPaymentMethodAndPlaceOrder` mutation validation conditions:

```
...

if (!isset($args['input']['cart_id']) || empty($args['input']['cart_id'])) {
            throw new GraphQlInputException(__('Required parameter "cart_id" is missing'));
}

...

if (!isset($args['input']['payment_method']['code']) || empty($args['input']['payment_method']['code'])) {
            throw new GraphQlInputException(__('Required parameter "code" for "payment_method" is missing.'));
}
```

because `Webonyx` covers `isset($args['input']['cart_id'])`, `isset($args['input']['payment_method']['code']` cases.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

Thank you!

### CODE REVIEW

**Comment by atwixfirster** [comment]
@magento run all tests

**Comment by rogyar** [comment]
Hi @atwixfirster. Could you cover this case with a test, please?

**Comment by atwixfirster** [comment]
@magento run all tests

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7664](https://jira.corp.magento.com/browse/ENGCOM-7664) has been created to process this Pull Request

**Review by prabhuram93 — APPROVED** [review]

**Comment by prabhuram93** [comment]
@dthampy Its Ready for Testing. Has coverage.

**Comment by dthampy** [comment]
@magento run all tests

**Review by dthampy — APPROVED** [review]

**Pull request merged**
