### PR TITLE
Remove forbidden `@author` tag from `Magento_Wishlist`

### LINKED ISSUE #37243: [Issue] Remove forbidden `@author` tag from `Magento_Wishlist`
This issue is automatically created based on existing pull request: magento/magento2#36978: Remove forbidden `@author` tag from `Magento_Wishlist`

---------
### Description
According to https://devdocs.magento.com/guides/v2.4/coding-standards/docblock-standard-general.html#documentation-space, the `@author` tag is not permitted in Magento. This pull request removes this tag from the `Magento_Wishlist` module. Given there are so many instances of this tag, I've opened a small pull request to get the process started. I expect that the linter will force me to fix several other coding standards violations on the way, so having a smaller pull request means that task is easier to manage. I plan to open more pull requests to tackle the other instances of this tag.

See also https://github.com/magento/magento-coding-standard/pull/382 and https://github.com/magento/magento-coding-standard/issues/167

See also https://github.com/magento/magento2/pull/36304, https://github.com/magento/magento2/pull/36976, https://github.com/magento/magento2/pull/36977

### Manual testing scenarios
There are not code changes in this pull request. This pull request only removes forbidden comments.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fredden**
### Description
According to https://devdocs.magento.com/guides/v2.4/coding-standards/docblock-standard-general.html#documentation-space, the `@author` tag is not permitted in Magento. This pull request removes this tag from the `Magento_Wishlist` module. Given there are so many instances of this tag, I've opened a small pull request to get the process started. I expect that the linter will force me to fix several other coding standards violations on the way, so having a smaller pull request means that task is easier to manage. I plan to open more pull requests to tackle the other instances of this tag.

See also https://github.com/magento/magento-coding-standard/pull/382 and https://github.com/magento/magento-coding-standard/issues/167

See also https://github.com/magento/magento2/pull/36304, https://github.com/magento/magento2/pull/36976, https://github.com/magento/magento2/pull/36977

### Manual testing scenarios
There are not code changes in this pull request. This pull request only removes forbidden comments.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37243: Remove forbidden `@author` tag from `Magento_Wishlist`

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run Static Tests

**Review by leonhelmus — APPROVED** [review]

**Comment by leonhelmus** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
Adding the same priority as https://github.com/magento/magento2/pull/36976#event-8742638190

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE

**Pull request merged**
