### PR TITLE
honor queue_consumer.xml maxMessages

### LINKED ISSUE #29522: [Issue] honor queue_consumer.xml maxMessages
This issue is automatically created based on existing pull request: magento/magento2#28995: honor queue_consumer.xml maxMessages

---------

### Summary (*)

Magento 2.4-develop
The maxMessages="100" attribute in `app/code/Magento/MediaStorage/etc/queue_consumer.xml` for instance is not being used. Instead only deployment configuration is used.

### Examples (*)

1. install vanilla Magento and run `pgrep -fl queue:consumers:start`
2. see that all consumers have `--max-messages=10000`
3. apply the PR
4. run `pkill -f queue:consumers:start`
5. wait for cron to restart the consumers
6. see that the values from queue_consumer.xml are used with a fallback and max of the deployment config or 10000 if that is not set.

### Proposed solution

### PR DESCRIPTION
**Pull request by AntonEvers**
### Description (*)

The maxMessages="100" attribute in `app/code/Magento/MediaStorage/etc/queue_consumer.xml` for instance is not being used. Instead only deployment configuration is used.

### Manual testing scenarios (*)

1. install vanilla Magento and run `pgrep -fl queue:consumers:start`
2. see that all consumers have `--max-messages=10000`
3. apply the PR
4. run `pkill -f queue:consumers:start`
5. wait for cron to restart the consumers
6. see that the values from queue_consumer.xml are used with a fallback and max of the deployment config or 10000 if that is not set.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29522: honor queue_consumer.xml maxMessages

### CODE REVIEW

**Comment by AntonEvers** [comment]
@magento run all tests

**Comment by AntonEvers** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento create issue

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Great catch!
Could you please cover this behaviour with integration test?

**Comment by gabrieldagama** [comment]
The risk was set to`low` due to: the suggested changes shouldn't affect other areas.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-8163](https://jira.corp.magento.com/browse/ENGCOM-8163) has been created to process this Pull Request

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Result:**
**Before:**
#28995Main

**After:**
#28995PR

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Pull request merged**
