### PR TITLE
magento2-925 Failed Test due to Class not following the naming conventions

### PR DESCRIPTION
**Pull request by amacgregor**
magento2-925 Failed Test due to Class not following the naming conventions

- Update The Test Mocks
- Fix the Failing test due incorrect class name
- Refactor class filenames and names to follow StudlyCase
- Fix Directory Structure
- Update comments

### CODE REVIEW

**Comment by amacgregor** [comment]
This is weird, the same failing test from the static suit is passing locally.

**Comment by amacgregor** [comment]
@antonmakarenko @alankent Any advice on what to do in this case, I have no idea of way the static_phpcs suite fails on TravisCI

**Comment by vpelipenko** [comment]
Static tests are fixed now.

**Comment by maksek** [comment]
MAGETWO-32697

**Comment by maksek** [comment]
CR: passed
Builds: green
Resolution: OK to merge
Ticket: MAGETWO-32697

**Pull request merged**
