### PR TITLE
#32760 fix order items missing in invoice email when invoice created …

### LINKED ISSUE #32760: Invoice Created Via /V1/order/:orderId/invoice Missing Items in Invoice Email
### Preconditions (*)

1. 2.4.2

### Steps to reproduce (*)

1. Go to Marketing > _Communications_ > Email Templates.
2. Press Add New Template.
3. Load New Invoice template.
4. Add any Template Name.
5. Press Save Template.
6. Set the template you just created under Stores > Configuration > Invoice > Invoice Email Template.
7. Place order online.
8. Create invoice for the order via /V1/order/:orderId/invoice.

### Expected result (*)

1. The invoice has the items listed.

### Actual result (*)

1. The invoice does not have items listed.

The issue seems to be in vendor/magento/module-sales/Model/Order/Invoice/Sender/EmailSender.php lines 105 - 120.
The $transport is missing order_id and invoice_id.

Alternatively, the Magento/Sales/view/frontend/email/invoice_new.html (and invoice_new_guest.html) should replace:
{{layout area="frontend" handle="sales_email_order_invoice_items" invoice_id=$invoice_id order_id=$order_id}}

with

{{layout area="frontend" handle="sales_email_order_invoice_items" invoice=$invoice order=$order}}

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ x ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by vovsky**
### Description (*)
PR fixes missing order items in invoice email when invoice is created via API

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32760

### Manual testing scenarios (*)
1. Place order
2. Create invoice via Rest API
3. Email is missing order items

### CODE REVIEW

**Comment by vovsky** [comment]
@magento run all test

**Comment by vovsky** [comment]
@magento run all test

**Comment by eduard13** [comment]
@magento run all test

**Comment by eduard13** [comment]
@magento run all tests

**Comment by vovsky** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Functional Tests EE

**Review by Den4ik — APPROVED** [review]
@vovsky Thanks for your contribution

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9061](https://jira.corp.magento.com/browse/ENGCOM-9061) has been created to process this Pull Request

**Comment by engcom-Oscar** [comment]
:heavy_check_mark: QA passed

Was checked case from Manual testing scenarios 

:x: **Before:**
Screenshot from 2021-05-17 15-47-28

:heavy_check_mark: **After:**
Screenshot from 2021-05-17 15-47-18

**Pull request merged**
