### PR TITLE
[Backport] 20434 consider url rewrite when change product visibility attribute

### PR DESCRIPTION
**Pull request by VitaliyBoyko**
Original PR: #20774 

### Description (*)
Has been implemented observing the saving attribute via mass action, creating/deleting URL rewrites appropriately on the product visibility attribute change. 
For more details see the issue (magento/magento2#20434).

### Fixed Issues (if relevant)
1. magento/magento2#20434: Product URL duplicate M2.2.6

### Manual testing scenarios (*)
CASE 1:

Step 1. Create a product with the following URL (or any of your choice): « mon-produit-de-test » - Visible product (catalog, search)
Step 2. Create a second one with the same values but invisible individually then URL « mon-produit-de-test »
Step 3. Change visibility of the second product to visible via mass action.

The Url Key exist exception should be thrown.

CASE 2:
Step 1. Create a product with the following URL (or any of your choice): « mon-produit-de-test » - Visible product (catalog, search)
Step 2. Set visibility attribute to invisible via product grid mass action

Product URL rewrite should be removed.

CASE 3:
Step 1. Create a product with the following URL (or any of your choice): « mon-produit-de-test » - Not visible
Step 2. Set visibility attribute to visible via product grid mass action

Product URL rewrite should be created.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @VitaliyBoyko. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4659](https://jira.corp.magento.com/browse/ENGCOM-4659) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Comment by sivaschenko** [comment]
The pull request is causing performance degradation on 2.2-develop branch

    Save Attributes (Product Grid Mass Actions): 8.6% (mainline = 35 | team = 38) -> DEGRADATION
    Save Attributes (Product Grid Mass Actions): 12.2% (mainline = 49 | team = 55) -> DEGRADATION
    Save Attributes (Product Grid Mass Actions): 27.3% (mainline = 198 | team = 252) -> DEGRADATION

The degradation is caused by an additional observer to `catalog_product_attribute_update_before` event. @kandy can you please advise how this PAT failure can be handled

**Comment by sidolov** [comment]
Hi @VitaliyBoyko , do you have any progress on this?

**Comment by VitaliyBoyko** [comment]
Hi @sidolov 
I believe the performance degradation is quite expected here.
Saving URL rewrites requires additional operations performed on DB that obviously increases the load. Thanks!

**Comment by sivaschenko** [comment]
@kandy can you please take a look if the PAT failure can be approved for this PR?

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by orlangur** [comment]
Closing as corresponding 2.3 PR needs to be reverted: it introduced incorrect URL Rewrites behavior.

Correct behavior taking into consideration Piotr Kaminsky comment is being implemented in https://github.com/magento/magento2/pull/23275.

**Pull request closed without merging**
