### PR TITLE
issue:#33989 Fixed failed importing product with SKU that has Unicode character

### LINKED ISSUE #33989: Importing product with SKU that has Unicode character fails
1. Magento 2.x

1. Import product that has sku `30612190-5233-8  16Â½`

### Expected result (*)
1. Product is imported without errors

### Actual result (*)
1. Error
Note: There is no issue when product is created from Admin UI - Catalog - Products page with sku 30612190-5233-8  16Â½. Product created successfully.
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by PascalBrouwers**
### Description (*)
See: https://github.com/magento/magento2/issues/33989

### Fixed Issues (if relevant)
1. Fixes magento/magento2#33989

### Manual testing scenarios (*)
1. See: https://github.com/magento/magento2/issues/33989

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by PascalBrouwers** [comment]
Fix is this line: https://github.com/magento/magento2/pull/33990/files#diff-266a910d8532a5e3514012fc32975a38b9200289a197ee9a7c6598bd440e4759L117
But I fixed the other incorrect `strtolower` as well.

**Comment by shikhamis11** [comment]
@magento run all tests

**Comment by PascalBrouwers** [comment]
had to apply the fixes to app/code/Magento/CatalogImportExport/Model/Import/Product.php as well

@magento run all tests

**Comment by PascalBrouwers** [comment]
had to apply the fixes to function saveData as well
verified that import now successfully runs
@magento run all tests

**Review by Den4ik — CHANGES_REQUESTED** [review]
@PascalBrouwers Thanks for PR.
Could you please fix failed Static tests and create new one for the changes

**Comment by BarnyShergold** [comment]
@PascalBrouwers - Any update on fixing the Unit Tests?

**Comment by engcom-Charlie** [comment]
Hi @PascalBrouwers,

Thank you for your contribution!

I am planning to work on the failing static tests, but before proceeding,  I have tried to reproduce this issue on 2.4-develop branch and its not reproducible.

To reproduce it, I am doing below steps.
1. Magento 2.4 develop instance
2. Create new product with SKU="30612190-5233-8 16Â½" 
3. Go to Admin > System> Export
4. Download the .csv file for Entity types: Product, You will get the entry with  SKU="30612190-5233-8 16Â½"  this product
5. Updating the above SKU's entry in .csv file and also adding a new product entry with SKU="abcÂ½" in .csv file
6. Going to Admin > System> Import
7. With the Entity Types: Product and Import behavior: Add/Update I am uploading the above updated file.
8. The check data passes everything and Import is working successfully.
9. As a result, I can see the new Product with SKU=abcÂ½ and updated  SKU=30612190-5233-8 16Â½ properly on store front as well as in admin.

Can you please provide the detail steps to reproduce this issue if I am missing anything. In order to proceed further to fix the failed tests it will will be really helpful.

Thank you in advance!

**Comment by engcom-Charlie** [comment]
Hi @PascalBrouwers,

Can you please provide information on this [comment](https://github.com/magento/magento2/pull/33990#issuecomment-925638326) so that I can able to work on this issue if its exist.

Thank you!

**Comment by engcom-Charlie** [comment]
Hi @PascalBrouwers,

As I have mentioned in my [comment](https://github.com/magento/magento2/pull/33990#issuecomment-925638326), the given issue is not reproducible on 2.4 develop and waited for the confirmation.

Due to inactivity, I’m closing this PR now.

Please reopen and update if you wish to continue.

Thank you for your contribution!

**Pull request closed without merging**
