### PR TITLE
[Forwardport] Updated SynonymGroup.xml

### PR DESCRIPTION
**Pull request by sanganinamrata**
### Original Pull Requests 
 https://github.com/magento/magento2/pull/16557
https://github.com/magento/magento2/pull/16636
https://github.com/magento/magento2/pull/16637

### Fixed Issues (if relevant)

Updated SynonymGroup.xml by removing extra space from the value of **is_required** XML node. 
Corrected function comment for **Magento Setup** module **includeClasses** function.
Removed double occurrences from jQuery, angular JS files and Magento Setup module's scan function's comment.

### Manual testing scenarios

N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @sanganinamrata. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by sidolov** [comment]
`/combine 16636 16637`

**Comment by sidolov** [comment]
@magento-engcom-team combine 16636 16637

**Comment by magento-engcom-team** [comment]
Hi @sidolov. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
@sanganinamrata all pull requests have been successfully combined together: 
 - merged https://github.com/magento/magento2/pull/16636: [Forwardport] Corrected function comment
 - merged https://github.com/magento/magento2/pull/16637: [Forward Port] Removed double occurrences from files.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-2223](https://jira.corp.magento.com/browse/ENGCOM-2223) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @sanganinamrata. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Pull request merged**
