### PR TITLE
missing use statement in layout generator

### PR DESCRIPTION
**Pull request by adeptofvoltron**
### Description (*)
 
Simple change. LocalizedException was used in class \Magento\Framework\View\Layout\Generator\Block, but it were missing in use section. It were not causing any fatal errors because of the way how it was used in method \Magento\Framework\View\Layout\Generator\Block::handleRenderException:
```
 $message = ($cause instanceof LocalizedException) ? $cause->getLogMessage() : $cause->getMessage();
```

### Manual testing scenarios (*)

1.force any block to throw LocalizedException during generation, and check error message in logs. It ought to be message from the \Magento\Framework\Exception\LocalizedException::getLogMessage method

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19009) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @adeptofvoltron. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3374](https://jira.corp.magento.com/browse/ENGCOM-3374) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@adeptofvoltron thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by adeptofvoltron** [comment]
@sidolov thank you for your review. I would only like to make a notice that another Pull Request is throwing LocalizedException in exacly same class:
https://github.com/magento/magento2/pull/19008

**Comment by magento-engcom-team** [comment]
Hi @adeptofvoltron. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
