### PR TITLE
Remove unused variables in unit test

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Vinai** [comment]
It seems the broken integration test has nothing to do with the changes in the PR.

**Comment by fooman** [comment]
Thanks @Vinai - the memory test has been fluctuating for me locally on other occasions as well (and it seems for Magento as well https://github.com/magento/magento2/blob/6fb4e9d9c7b5eedf9cbc037b5349e3fc69536155/dev/tests/integration/testsuite/Magento/MemoryUsageTest.php#L69). And yes I fail to see how deleting a variable in a test (which wouldn't be initialised as part of the memory test I think) could make it worse.

**Comment by vancoz** [comment]
Internal ticket MAGETWO-52389

**Comment by okorshenko** [comment]
@fooman thank you for your contribution

**Pull request merged**
