### PR TITLE
Removed unused plugin on protected method

### LINKED ISSUE #37927: [Issue] Removed unused plugin on protected method
This issue is automatically created based on existing pull request: magento/magento2#32158: Removed unused plugin on protected method

---------

### Description (*)

Removed an unused plugin. The plugin seems to be legacy code, and wouldn't have worked anyway do to it being targeted for a protected method.

The plugin even had unit tests.

Actually, the original methods don't seem to be used anywhere either. I'm not sure why they're not removed. They're marked as protected, so it shouldn't cause any backwards compatibility issues.

* `isCityActive`
* `isStateActive`

See this commit for some background:
https://github.com/magento/magento2/commit/e7f80002654281ddce53dfe630a43d186dbf668c

The previous class with different name was renamed and refactored. The methods used to be public. If this hasn't caused any regression (I don't thinks so), then the original methods should be removed too.

### Questions or comments

Should the original methods be removed?

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by erfanimani**
### Description (*)

Removed an unused plugin. The plugin seems to be legacy code, and wouldn't have worked anyway do to it being targeted for a protected method.

The plugin even had unit tests.

Actually, the original methods don't seem to be used anywhere either. I'm not sure why they're not removed. They're marked as protected, so it shouldn't cause any backwards compatibility issues.

* `isCityActive`
* `isStateActive`

See this commit for some background:
https://github.com/magento/magento2/commit/e7f80002654281ddce53dfe630a43d186dbf668c

The previous class with different name was renamed and refactored. The methods used to be public. If this hasn't caused any regression (I don't thinks so), then the original methods should be removed too.

### Questions or comments

Should the original methods be removed?

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37927: Removed unused plugin on protected method

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]

**Comment by BarnyShergold** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @BarnyShergold, thank you for the review.
[ENGCOM-8761](https://jira.corp.magento.com/browse/ENGCOM-8761) has been created to process this Pull Request
:eight_spoked_asterisk: @BarnyShergold, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by BarnyShergold** [comment]
@magento run Functional Tests B2B

**Comment by BarnyShergold** [comment]
@magento run Functional Tests B2B

**Comment by BarnyShergold** [comment]
@magento run Functional Tests B2B

**Comment by BarnyShergold** [comment]
@erfanimani The Functional Tests b2B keep failing but I can't see why what you've added would cause these issues - this maybe a false positive. Can you check?

**Comment by erfanimani** [comment]
Thanks for the heads up @BarnyShergold.

I had a look at the Allure output of the functional tests, and the errors definitely seem unrelated. It looks like these might be changes introduced in 2.4-develop from other PRs?

**Comment by BarnyShergold** [comment]
@engcom-Hotel Can you advise?

**Comment by BarnyShergold** [comment]
@magento run Functional Tests B2B

**Comment by BarnyShergold** [comment]
@magento run Functional Tests B2B

**Comment by BarnyShergold** [comment]
@magento run Functional Tests B2B

**Comment by erfanimani** [comment]
Thanks @BarnyShergold . The failing test looks unrelated?

    MC-31666: Validate Banner with Collage Center Appearance with No Fallback Image, Disabled Infinite Loop, Disabled Play Only When Visible, and Disabled Lazy Load

**Comment by BarnyShergold** [comment]
@magento run Functional Tests B2B

**Comment by BarnyShergold** [comment]
Now we are getting  MC-3979: Collage Right - Can Inline Edit Slide Content When In 25 Percent Width Column

Trying again!

**Comment by BarnyShergold** [comment]
@magento run Functional Tests B2B

**Comment by BarnyShergold** [comment]
@erfanimani - FINALLY!

**Comment by peterjaap** [comment]
@BarnyShergold so why is this still not merged?

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento create issue

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Integration Tests,Functional Tests EE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Integration Tests

**Comment by engcom-Echo** [comment]
Thanks for the contribution!

✔️ QA Passed

As in this PR, the changes are related to removed unused plugin on protected method

There is nothing to reproduce in this issue but it is a good to have. 

Build are failing hence moving it to `Extended Testing`

**Comment by engcom-Echo** [comment]
Functional Tests B2B failure are different on last two run on same commit.
Run1
Screenshot 2023-08-29 at 1 54 01 PM

Run2
Screenshot 2023-08-29 at 1 54 06 PM

Hence moving it to `Merge In Progress`

**Pull request merged**
