### PR TITLE
Update MockObject class in Widget module

### PR DESCRIPTION
**Pull request by hws47a**
### Description (*)
Replace outdated PSR-0 `\PHPUnit_Framework_MockObject_MockObject` with current PSR-2 class name `\PHPUnit\Framework\MockObject\MockObject`

### Related Pull Requests
#26775 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @hws47a,
Your changes looks good
Could you fix failing static tests?

**Review by lbajsarowicz — APPROVED** [review]
For future reference: you can just remove whole doc block, as it's about either adding description or removing block

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-6907](https://jira.corp.magento.com/browse/ENGCOM-6907) has been created to process this Pull Request

**Review by ihor-sviziev — APPROVED** [review]
Functional test failure isn’t related to this PR

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6907](https://jira.corp.magento.com/browse/ENGCOM-6907) has been created to process this Pull Request

**Comment by engcom-Golf** [comment]
@magento run all tests

**Pull request merged**
