### PR TITLE
[32027][To 2.4-develop] Marked Framework interfaces as API part 4

### LINKED ISSUE #32027: Mark Framework interfaces as API part 4
The following interfaces should be marked as API in 2.4-develop branch

1. lib/internal/Magento/Framework/Encryption/Adapter/EncryptionAdapterInterface.php
1. lib/internal/Magento/Framework/Event/ConfigInterface.php
1. lib/internal/Magento/Framework/Event/InvokerInterface.php
1. lib/internal/Magento/Framework/Event/ManagerInterface.php
1. lib/internal/Magento/Framework/Exception/TemporaryStateExceptionInterface.php
1. lib/internal/Magento/Framework/Filesystem/Directory/PathValidatorInterface.php
1. lib/internal/Magento/Framework/Filesystem/DriverPoolInterface.php
1. lib/internal/Magento/Framework/Filesystem/File/ReadInterface.php
1. lib/internal/Magento/Framework/Filter/DirectiveProcessor/FilterInterface.php
1. lib/internal/Magento/Framework/Filter/DirectiveProcessorInterface.php
1. lib/internal/Magento/Framework/Filter/FactoryInterface.php
1. lib/internal/Magento/Framework/Filter/FilterManager/ConfigInterface.php
1. lib/internal/Magento/Framework/Filter/SimpleDirective/ProcessorInterface.php
1. lib/internal/Magento/Framework/Filter/VariableResolverInterface.php

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixes #32027

### Related Pull Requests

https://github.com/magento/magento2/pull/32170
### Fixed Issues (if relevant)

1. Fixes magento/magento2#32027>

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by danielrussob** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by aleron75** [comment]
I confirm the PR covers all the changes requested in the related Issue. Waiting for tests to finish in order to approve.

**Comment by Usik2203** [comment]
@magento run  Functional Tests EE, WebAPI Tests

**Comment by Usik2203** [comment]
Hi @aleron75 
Thank you for review 
Could i kindly ask you to remove `Cleanup` label based on this comment
https://github.com/magento/magento2/pull/32735#issuecomment-819324804
Thanks!

**Comment by danielrussob** [comment]
As mentioned with Sergii Ivashchenko static tests are ok

**Review by danielrussob — APPROVED** [review]

**Review by aleron75 — APPROVED** [review]

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama the branch with code successfully imported into`magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-32728`.

**Pull request merged**
