### PR TITLE
Feature/9798 updating configurable product options based on produc id and sku

### PR DESCRIPTION
**Pull request by lpouwelse**
### Description (*)

The mysql table 'product_attribute_super_attribute' contains an unique constraint on (product_id, attribute_id). When option_id is not supplied while updating this will result in an unique failure. So when OptionId is not provided, based on the unique key constraint OptionId will be set if available.

### Fixed Issues (if relevant)

1. magento/magento2#9798: Problem adding attribute options to configurable product via REST Api

### Manual testing scenarios (*)

1. First create a configurable product linked to some single products by following the tutorial (https://devdocs.magento.com/guides/v2.3/rest/tutorials/bulk-configurable-product/plan-product.html)
2. Create another simple product (https://devdocs.magento.com/guides/v2.3/rest/tutorials/bulk-configurable-product/create-configurable-simple-products.html)
3. (Re)-define configurable product options (https://devdocs.magento.com/guides/v2.3/rest/tutorials/bulk-configurable-product/define-config-product-options.html)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-5385](https://jira.corp.magento.com/browse/ENGCOM-5385) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@lpouwelse thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
Hi @lpouwelse,@sivaschenko . 
During testing on the 2.3-develop, we get this result when we re-send the request with the addition of the option : "{"message": "An error occurred while saving the option. Please try to save again."}".
In your case, the option is overwritten under the same id in the 'product_attribute_super_attribute' table.

I think that we should get an error with this repeated request for adding an option.
What do you think about this and how to use your fix if we merge it?
Thanks!

**Comment by sivaschenko** [comment]
@engcom-Alfa I think the fix provided in this pull request is simplifying the usage of configurable product options API. Also, it enables the client to manage options (i.e. option position) without the option id. Also, I don't see another way to update the option position.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by lpouwelse** [comment]
@sivaschenko thanks for your reply.

**Pull request merged**
