### PR TITLE
32061 remove deprecated interfaces part 1

### PR DESCRIPTION
**Pull request by adamphh**
Remove deprecated interfaces part 1

1. app/code/Magento/CatalogSearch/Model/ResourceModel/Fulltext/Collection/DefaultFilterStrategyApplyCheckerInterface.php: Deprecated since May 2019
2. app/code/Magento/MediaGalleryApi/Model/Asset/Command/DeleteByDirectoryPathInterface.php: Can be removed, has been deprecated since April 2020
3. app/code/Magento/MediaGalleryApi/Model/Asset/Command/DeleteByPathInterface.php: Can be removed, has been deprecated since April 2020
4. app/code/Magento/MediaGalleryApi/Model/Asset/Command/GetByIdInterface.php: Can be removed, has been deprecated since April 2020
5. app/code/Magento/MediaGalleryApi/Model/Asset/Command/GetByPathInterface.php: Can be removed, has been deprecated since April 2020
6. app/code/Magento/MediaGalleryApi/Model/Asset/Command/SaveInterface.php: Can be removed, has been deprecated since April 2020
7. app/code/Magento/MediaGalleryApi/Model/Keyword/Command/GetAssetKeywordsInterface.php: Can be removed, has been deprecated since April 2020
8. app/code/Magento/MediaGalleryApi/Model/Keyword/Command/SaveAssetKeywordsInterface.php: Can be removed, has been deprecated since April 2020
9. app/code/Magento/Payment/Model/Method/ConfigInterface.php: Deprecated since 2018
10. app/code/Magento/Search/Model/QueryFactoryInterface.php: Deprecated since 2017
11. app/code/Magento/Store/Api/StoreResolverInterface.php: Deprecated since June 2018, has replacement

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32061

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by adamphh** [comment]
Re-open pull request to run the check again (Sign the Adobe CLA!)

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by adamphh** [comment]
@magento run WebAPI Tests

**Comment by adamphh** [comment]
@magento run WebAPI Tests

**Comment by adamphh** [comment]
@magento run all tests

**Comment by adamphh** [comment]
@magento run Unit Tests

**Comment by adamphh** [comment]
@magento run Unit Tests

**Pull request closed without merging**
