### PR TITLE
Set of fixes introduced during #CoreReview 31.01.2020

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
This PR fixes introduced backward incompatible changes in following commit (`CategoryRepositoryInterface` dependency was added in the middle of constructor arguments):
https://github.com/magento/magento2/commit/5e12e57e99a8adf2c042d5cc81e85dca3a29757a#diff-28c7c49b28292e55b8349293d02f8499R145

Changes covered and explained during #CoreReview 
https://youtu.be/076Y_EAVD8c

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests
Maybe today :pray:

**Review by ihor-sviziev — APPROVED** [review]
Failing functional & unit tests are not related to changes from this PR, so I'm approving this PR

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6808](https://jira.corp.magento.com/browse/ENGCOM-6808) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
