### PR TITLE
Backend: Global select box arrow issue. when user select any option wrong arrow icon displayed.

### PR DESCRIPTION
**Pull request by suryakant-krish**
### Description (*)

Backend: Global select box arrow issue. when user select any option wrong arrow icon displayed.
### Fixed Issues (if relevant)

1. This is direct pr as per suggest magento reviewer.
2. Backend: Global select box arrow issue. when user select any option wrong arrow icon displayed.

### Manual testing scenarios (*)

1. Login into admin panel > Content > Configuration > Select any theme > Click on applied theme > choose any other theme. Arrow direction is wrong.

    Note: This change for global select box.
2. Actual Result.
actual-result-1

3. Expected Result.
expected-result

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by suryakant-krish** [comment]
Please consider only this commit id "e829652"

**Comment by sidolov** [comment]
Hi @suryakant-krish , unfortunately, we can't process only a few commits from the pull request. Please, put only mentioned commit to the branch and force push the current branch. 
Thank you!

**Comment by suryakant-krish** [comment]
Hello sidolov,

I Have pushed branch please review it,

**Comment by sivaschenko** [comment]
Hi @suryakant-krish I still see a number of commits fixing different issues, can you please add the description for all issues fixed to the pull request.

**Comment by suryakant-krish** [comment]
Hello sivaschenko,
Created new pull request due to other commits.
here is the reference for the new pull request.
https://github.com/magento/magento2/pull/20423

**Pull request closed without merging**
