### PR TITLE
[MFTF] Check if Shipping Address added on Checkout is saved after Order is placed

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
This test checks if Shipping Address added on Checkout is saved after Order is placed

### Manual testing scenarios (*)
1. Add any Product to the Cart
2. Proceed to the Checkout
3. Click "+ New Address" button
4. Provide address details
5. Click the "Ship here" button
6. Go to My Account->Address book
7. Assert that the added address isn't saved to Address Book yet
8. Go back to Checkout and place the Order
9. Go to My Account->Address book
10.  Assert that the added address is saved to Address Book

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run Functional Tests EE,Functional Tests B2B,Functional Tests CE

**Review by sidolov — APPROVED** [review]

**Review by Den4ik — APPROVED** [review]

**Pull request merged**
