### PR TITLE
Resolve Bad style on Validate VAT number messages issue23738

### LINKED ISSUE #23738: Bad style on Validate VAT number messages
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Stores->Configuration->General
2. Scroll to Store Information
3. Click "Validate VAT number" with empty information. 
- Fill the correct VAT number with the country. Click "Validate VAT number"

### Expected result (*)

1. The error message should be red.
2. The success message should be green.

### Actual result (*)

Both messages are same color.
1. 
image

2. 
image

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

Resolve magento/magento2#23738: Bad style on Validate VAT number messages

Reason: No style for error and success class in CSS.

Solution: Use other class and add the color to the message

### Fixed Issues (if relevant)

1. magento/magento2#23738: Bad style on Validate VAT number messages

### Manual testing scenarios (*)

1. Go to Stores->Configuration->General
2. Scroll to Store Information
3. Click "Validate VAT number" with empty information. 
- Fill the correct VAT number with the country. Click "Validate VAT number"

Results
1. The error message should be red.
2. The success message should be green.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-23739.instances.magento-community.engineering).
Admin access: [https://pr-23739.instances.magento-community.engineering/admin](https://pr-23739.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5558](https://jira.corp.magento.com/browse/ENGCOM-5558) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @edenduong !

During testing we faced an issue.

**Problem:** The error and success messages should be above "Validate VAT Number" button

**Actual Result:**

after2

after1

Could you take a look?

Thanks!

**Comment by edenduong** [comment]
@engcom-Alfa: Thank you for your feedback.

I have changed the source code. Please check it again.

@sidolov: Please review my new changes.

Thanks!

**Comment by edenduong** [comment]
@sidolov: Could you please review my new changes?

Thank you and have a nice day.

**Review by Stepa4man — APPROVED** [review]
Hi @edenduong
Thanks for your contribution

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, thank you for the review.
[ENGCOM-5558](https://jira.corp.magento.com/browse/ENGCOM-5558) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
