### PR TITLE
[MFTF] Use action group for adding to cart

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR uses` StorefrontClickAddToCartOnProductPageActionGroup` instead 

 `<click selector="{{StorefrontProductActionSection.addToCart}}" stepKey="addToCart"/>`
        `<waitForPageLoad stepKey="waitForAddToCart"/>`
        `<waitForElementVisible selector="{{StorefrontMessagesSection.success}}" stepKey="waitForSuccessMessage"/>`

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run Functional Tests EE , Functional Tests B2B

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7736](https://jira.corp.magento.com/browse/ENGCOM-7736) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
**Notice:** QA not applicable

**Pull request merged**
