### PR TITLE
Fixes #25120 stores the attribute url_path for non-default Stores

### LINKED ISSUE #25120: Magento2 incorrectly stores the attribute url_path for non-default stores
### Preconditions (*)

1. Magento 2.3-develop
2. env: dev

### Steps to reproduce (*)

1. Create second store view. my config:

2. Go to categories and switch to a second store view
3. Change the name of a child category (Root -> 1st Parent -> 1st Child -> 1st Grandchild) for that store view only (url_key still same as others). For example, change the name for category "1st Child" to "1st Child second store view".
4. Check attribute url_path in table ''catalog_category_entity_varchar'.
b4d416e5e7

We use attribute 'url_path' in our module elasticsuite https://github.com/Smile-SA/elasticsuite for feature Autocomplete. Related issue https://github.com/Smile-SA/elasticsuite/issues/1560

### Expected result (*)

1. url_path is stored correctly
### Actual result (*)

1. For the category "1st Grandchild" url_path is incorrectly stored.

### PR DESCRIPTION
**Pull request by androshchuk**
### Description (*)

Fix for issue 25120
### Fixed Issues (if relevant)

1. magento/magento2#25120: Magento2 incorrectly stores the attribute url_path for non-default Stores

### Manual testing scenarios (*)

1. Create second store view.
2. Go to categories and switch to a second store view.
3. Change the name of a child category (Root -> 1st Parent -> 1st Child -> 1st Grandchild) for that store view only (url_key still same as others). For example, change the name for category "1st Child" to "1st Child second store view".
4. Check attribute url_path in table ''catalog_category_entity_varchar'.
5. Attribute url_path should now be stored correctly.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6124](https://jira.corp.magento.com/browse/ENGCOM-6124) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@androshchuk thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
Hi @androshchuk. Could you sign the Adobe CLA? Thanks!

**Comment by sdzhepa** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [new Magento instance](https://pr-25143.instances.magento-community.engineering).
Admin access: [https://pr-25143.instances.magento-community.engineering/admin](https://pr-25143.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
