### PR TITLE
added GNU Free Font to be used by sales PDFs

### PR DESCRIPTION
**Pull request by rossmc**
**Please Note:** A similar PR(#13016) I submitted for the same issue to the 2.2-develop branch has been merged already.
### Description

The sales PDFs use the Libertine font which is not a unicode font and therefore it does not have full support of characters. It does not support Arabic, Russian, Greek, Indian or Thai alphabets and many more. For example it does not support the Indian rupee currency symbol ( ₹ ) and displays _tofu_ boxes instead, which makes the PDF invoice totals illegible.

It's better if we use a [unicode font](https://en.wikipedia.org/wiki/Unicode_font) to support more writing systems and characters.  So I've added the open source  [GNU Free Font](https://www.gnu.org/software/freefont/) which supports much more writing systems.

### Fixed Issues (if relevant)

1. magento/magento2#9666: Magento 2.1.6 - Invoice PDF doesn't support Thai
2. magento/magento2#12323: Magento 2.1.3 - Invoice and shipment PDF doesn't support Arabic

### Manual testing scenarios

1. Set the [store currency](http://docs.magento.com/m2/ce/user_guide/stores/currency-symbols.html) to use the ruppe currency symbol ( ₹ ) .
2. [Print an invoice](http://docs.magento.com/m2/ce/user_guide/sales/invoice-print-multiple.html).

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by savadk00hi** [comment]
@rossmc 

Hello
I use Farsi language in magento 2.3 but in sales pdf the characters are not displayed correctly

screen shot 2018-04-15 at 10 13 25 pm

**Comment by rossmc** [comment]
Hi @savadk00hi,

I'm not sure if the [GNU Free Font](https://www.gnu.org/software/freefont/) I added in this PR supports Farsi, but it does support much more writing systems than the current Libertine font that is being used.  From what I could find it supports more writing systems than any other open source font available.

The issue is that there is no one single font that supports all writing systems and characters in existence.  [It's not possible with the OpenType font spec](https://stackoverflow.com/a/34734338/1814446).

Anyway, If the GNU Free Font added in this PR does not support Farsi, you could try forking [this module of mine](https://github.com/rossmc/SalesPdfFonts) and change it use a font which supports Farsi, one of Google's Noto fonts probably support Farsi.
https://www.google.com/get/noto/

**Comment by magento-engcom-team** [comment]
Hi @rossmc. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.3.0 release.

**Comment by msliman** [comment]
Any solution for Arabic Language, the characters are separated and reversed  ?

**Comment by afnanm** [comment]
also me, arabic letters are not connected. how to fix it? is there a solution? also currency symbol in arabic is  shown as character @rossmc @magento-engcom-team

**Comment by Sumayah90** [comment]
Hi @rossmc,
Is this issue solved? 
I can see 3 out of 4 is done 

Kindly inform us

Thanks

**Comment by pieal86** [comment]
any solution for this: "characters are separated and reversed"?
More than a year..

**Comment by rossmc** [comment]
See response with suggested solution from more than a year ago...
https://github.com/magento/magento2/pull/14710#issuecomment-381435041

**Pull request merged**
