### PR TITLE
Add validation greater than zero for Maximum Qty Allowed in Shopping Cart for fixed #23319

### LINKED ISSUE #23319: Unable to save edited product when max_sale_qty is Magento's default
### Preconditions (*)

1. Install Magento Open Source 2.3.1 

### Steps to reproduce (*)

1. Go to admin area
2. Go to Stores->Configuration->Catalog->Inventory->Product Stock Options
3. Edit the global default to be 0 
4. Save the config
5. Open create a simple product form and fill in minimum required data
6. Open the advanced inventory popup
7. Uncheck the checkbox "use_config_max_sale_qty"
8. Observe the default value of 0 in max_sale_qty field
9. Do not edit the default provided
10. Click Save

### Expected result (*)

1. Product is successfully saved

### Actual result (*)

1. Save is not happening, validation is failed due to validate-grater-then-0 on max_sale_qty field.

This value however comes from the cataloginventory's db_schema (module-catalog-inventory/etc/db_schema.xml):
```
<table name="cataloginventory_stock_item" resource="default" engine="innodb" comment="Cataloginventory Stock Item">
...
<column xsi:type="decimal" name="max_sale_qty" scale="4" precision="12" unsigned="false" **nullable="false"
                default="0"** comment="Max Sale Qty"/>
...
</table>
```

While in the same module, in magento/module-catalog-inventory/view/adminhtml/ui_component/product_form.xml:
```
<field name="max_sale_qty" formElement="input">
    <argument name="data" xsi:type="array">
        <item name="config" xsi:type="array">
            <item name="value" xsi:type="object">Magento\CatalogInventory\Model\Source\StockConfiguration</item>
        </item>
    </argument>
    <settings>
        <scopeLabel>[GLOBAL]</scopeLabel>
        <validation>
            <rule name="**validate-greater-than-zero**" xsi:type="boolean">true</rule>
        </validation>
        <label translate="true">Maximum Qty Allowed in Shopping Cart</label>
        <dataScope>max_sale_qty</dataScope>
    </settings>
</field>
```

And in the same module, inmodule-catalog-inventory/etc/adminhtml/system.xml:
```
<section id="cataloginventory" translate="label" type="text" sortOrder="50" showInDefault="1" showInWebsite="1" showInStore="1">
...
<group id="item_options" translate="label comment" type="text" sortOrder="10" showInDefault="1" showInWebsite="1" showInStore="1">
...
<field id="max_sale_qty" translate="label" type="text" sortOrder="4" showInDefault="1" showInWebsite="0" showInStore="0" canRestore="1">
                    <label>Maximum Qty Allowed in Shopping Cart</label>
                    <validate>**validate-number**</validate>
                </field>


So, there is inconsistency - if 0 is allowed as value for max_sale_qty. If 0 is set from the start as default, there shouldn't be validation that would forbid it on the frontend.

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

Add validation greater than zero for Maximum Qty Allowed in Shopping Cart for fixed #23319

### Fixed Issues (if relevant)

1. magento/magento2#23319: Unable to save edited product when max_sale_qty is Magento's default

### Manual testing scenarios (*)

1. Go to admin area
2. Go to Stores->Configuration->Catalog->Inventory->Product Stock Options
3. Edit the global default Maximum Qty Allowed in Shopping Cart to be 0 
4. Save the config
### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @ravi-chandra3197 I've just checked the original issue and the following mention in particular:
> Save is not happening, validation is failed due to validate-grater-then-0 on max_sale_qty field.

So, the problem is the system allows to set 0 as the global default value but does not allow saving product with 0 because of additional validation.
In your PR you introduce another validation that validates values greater than 0. Would you provide more information on how the additional "greater than 0" validation solves the existing "greater than 0" validation? 
Thank you.

**Comment by ravi-chandra3197** [comment]
> Hi @ravi-chandra3197 I've just checked the original issue and the following mention in particular:
> 
> > Save is not happening, validation is failed due to validate-grater-then-0 on max_sale_qty field.
> 
> So, the problem is the system allows to set 0 as the global default value but does not allow saving product with 0 because of additional validation.
> In your PR you introduce another validation that validates values greater than 0. Would you provide more information on how the additional "greater than 0" validation solves the existing "greater than 0" validation?
> Thank you.

Hello @rogyar 
I have debugged and found that currently, Magento allows saving Maximum Qty Allowed in Shopping Cart to 0 because only validate-number is used.
I have added for  validate-greater-than-zero because when we edit product and use the default config value so it creates an issue because for edit product have validation with PR #https://github.com/magento/magento2/pull/18481
The problem seems to be introduced with this fix: #18477

**Comment by rogyar** [comment]
Hi @ravi-chandra3197. Thank you for the explanation. My point is, you are still not able to save the product. The original issue says "**Unable to save edited product** when max_sale_qty is Magento's default". Please, use the steps from the original issue: 

Go to admin area
Go to Stores->Configuration->Catalog->Inventory->Product Stock Options
Edit the global default to be 0
Save the config
Open create a simple product form and fill in minimum required data
Open the advanced inventory popup
Uncheck the checkbox "use_config_max_sale_qty"
Observe the default value of 0 in max_sale_qty field
Do not edit the default provided
Click Save

Then check if your fix provides the expected result:
> **Expected result**
Product is successfully saved

Thank you

**Comment by ravi-chandra3197** [comment]
> Hi @ravi-chandra3197. Thank you for the explanation. My point is, you are still not able to save the product. The original issue says "**Unable to save edited product** when max_sale_qty is Magento's default". Please, use the steps from the original issue:
> 
> Go to admin area
> Go to Stores->Configuration->Catalog->Inventory->Product Stock Options
> Edit the global default to be 0
> Save the config
> Open create a simple product form and fill in minimum required data
> Open the advanced inventory popup
> Uncheck the checkbox "use_config_max_sale_qty"
> Observe the default value of 0 in max_sale_qty field
> Do not edit the default provided
> Click Save
> 
> Then check if your fix provides the expected result:
> 
> > **Expected result**
> > Product is successfully saved
> 
> Thank you

Hello @rogyar 
so your point of view we should allow saving Maximum Qty Allowed in Shopping Cart with 0 value?

I think we have validated global default value and restrict save with 0, because whenever we use 
the default value in the product where we have restricted to save Maximum Qty Allowed in Shopping Cart with 0 value so we have to validate default value before save.

**Comment by rogyar** [comment]
Hi @ravi-chandra3197. That's correct, to solve this issue we should either allow or disallow 0 value everywhere to avoid confusions. I believe adding a validation "greater than zero" everywhere is the best option.

**Comment by rogyar** [comment]
Just want to double-check we are on the same page. To proceed with the current solution we need to add additional validation for the global default (Stores -> Configuration -> Catalog -> Inventory)

**Comment by sidolov** [comment]
@ravi-chandra3197 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
