### PR TITLE
fix issue #24366 - Updating cart quantity 

### PR DESCRIPTION
**Pull request by GDauer**
### Description (*)

This **Pull Request** fix Updating cart quantity, causes wrong error message to be displayed when backorders is involved. Internal ticket **MC-19752**

### Fixed Issues (if relevant)

1. magento/magento2#24366: Updating cart with quantity that results in error, causes wrong error message to be displayed when backorders involved.

### Manual testing scenarios (*)

1. Deploy **2.3-develop**
2. Create a test **Category**
3. Create test **product** in test **category.**
4. Set the stock **product** to Qty = 10
5. **Allows Backorders** with _Notify_ to the product
6. Set **Max in cart** = 30 in test product.
7. Go to frontend and add 10 items to cart
8. **Verify** no warning messages
9. Change quantity to 25 and Update cart
10. Verify backorder warning of 15 items backordered
11. Change quantity to 35 and Update cart

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by GDauer** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @GDauer. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @GDauer, here is your [new Magento instance](https://pr-24380.instances.magento-community.engineering).
Admin access: [https://pr-24380.instances.magento-community.engineering/admin](https://pr-24380.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by gwharton** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @gwharton, here is your [new Magento instance](https://pr-24380.instances.magento-community.engineering).
Admin access: [https://pr-24380.instances.magento-community.engineering/admin](https://pr-24380.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by gwharton** [comment]
@GDauer Solution Looks good. Test failures need resolving though.

**Review by rodrigowebjump — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-5790](https://jira.corp.magento.com/browse/ENGCOM-5790) has been created to process this Pull Request
:eight_spoked_asterisk: @rodrigowebjump, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@GDauer thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
