### PR TITLE
Don't assume a frontend cache section exists in the env.php file.

### LINKED ISSUE #35812: [2.4.4] Missing Frontend CacheInfo breaks bin/magento
### Preconditions and environment

- Magento 2.4.4
- Upgrade from 2.3.2
- Website is a PWA so doesn't use regular frontend.

### Steps to reproduce

composer update --no-dev
Run bin/magento.

### Expected result

See a list of commands.

### Actual result

```Warning: Undefined array key "frontend" in ../vendor/magento/framework/App/Cache/Frontend/Pool.php on line 90```

### Additional information

I have no clue what causes the exact scenario to start happening. But it appears that it's a minor programming oversight. Where someone assumed that if cacheInfo exists, the frontend cacheInfo also exists which apparently isn't true.

Fix is changing line 89 from
`if (null !== $cacheInfo) {`
to
`if (null !== $cacheInfo && isset($cacheInfo[FrontendPool::KEY_FRONTEND_CACHE]) {`

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### LINKED ISSUE #35861: graphql id_salt causing 500 server errors
### Preconditions and environment

- Magento version: 2.4.4
- Anything else that would help a developer reproduce the bug:  Issue started after upgrade to 2.4.4 from 2.3.x. We've had this on multiple unconnected websites running 2.4.4.

### Steps to reproduce

The issue occurs *seemingly* at random. We've identified however that sending any request to the graphql endpoint e.g. https://<yoursite>/graphql on our sites trigger a 500 server error across all cms, category, product, cart pages.

### Expected result

Expected Result: Graphql works as expected, web pages don't produce 500 errors.

### Actual result

The following various errors are triggered on loading any web pages:

Notice: Undefined index: frontend in /public_html/vendor/magento/
framework/App/Cache/Frontend/Pool.php on line 90

[2022-07-22T08:24:29.404089+00:00] main.ERROR: SQLSTATE[70100]: <<Unknown error>>: 1927 Connection was killed, query was: SELECT `queue_message`.`topic_name`, `queue_message`.`body`, `queue_message_status`.`id` AS `relation_id`, `queue_message_status`.`queue_id`, `queue_message_status`.`message_id`, `queue_message_status`.`status`, `queue_message_status`.`updated_at`, `queue_message_status`.`number_of_trials` AS `retries`, `queue`.`name` AS `queue_name` FROM `queue_message`
 INNER JOIN `queue_message_status` ON queue_message.id = queue_message_status.message_id
 INNER JOIN `queue` ON queue.id = queue_message_status.queue_id WHERE (queue_message_status.status IN (2, 5)) AND (queue.name = ‘export’) ORDER BY `queue_message_status`.`updated_at` ASC, `queue_message_status`.`id` ASC
 LIMIT 1

GraphQL (2:3)
1: mutation {
2:   createCustomer(
     ^
3:     input: {

### Additional information

We identified that our env.php file had been modified, and the following had been added:
,
    ‘cache’ => [
        ‘graphql’ => [
            ‘id_salt’ => ‘SALTHERE’
        ]
    ]

Removing the section instantly brought the website back online. Visiting the graphql endpoint again reproduced the issue.

There appear to be multiple recent posts on a stackexchange with the same issue: https://magento.stackexchange.com/questions/357938/magento-2-4-4-suddenly-adds-cache-tag-to-env-php/358492#358492

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### LINKED ISSUE #38363: [Issue] Don't assume a frontend cache section exists in the env.php file.
This issue is automatically created based on existing pull request: magento/magento2#38119: Don't assume a frontend cache section exists in the env.php file.

---------
### Description (*)
Code exists in Magento that assumes your `app/etc/env.php` will always contain a `frontend` section if there is a `cache` section. Like this:
```php
    'cache' => [
        'frontend' => [
            ...
        ]
     ]
```

But that's not always the case. All shops that were setup before Magento 2.3.1 didn't have a `cache` section in their `env.php` file in a default installation (if they didn't use Redis as caching).
If they now upgrade to Magento 2.4.4 or higher and use a graphql endpoint, Magento [automatically writes](https://github.com/magento/magento2/blob/2.4.6-p3/app/code/Magento/GraphQlCache/Model/CacheId/CacheIdCalculator.php#L124-L128) `cache > graphql > id_salt` to the `env.php` file and so introduces a `cache` section without a `frontend` section.

This then leads to this crash on every execution within Magento (frontend, backoffice, `bin/magento`, ...):
```
Warning: Undefined array key "frontend" in lib/internal/Magento/Framework/App/Cache/Frontend/Pool.php on line 90
```

This PR fixes this.

### Fixed Issues (if relevant)
1. Fixes #35812
2. Fixes #35861

### Manual testing scenarios (*)
1. Fully setup a working Magento
2. Edit the `app/etc/env.php` file and remove the entire `frontend` section in the `cache` section
3. Run `bin/magento` or visit the frontend
4. Expected is to not see an error/crash
5. Run added unit test with and without fix. Without the fix, the test will fail (`vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist lib/internal/Magento/Framework/App/Test/Unit/Cache/Frontend/PoolTest.php`)

More elaborate testing scenario that can cause this situation:
1. Using PHP 7.2 and composer v1, setup Magento 2.3.0 and install it fully (don't configure it with Redis caching)
2. Double check that the `app/etc/env.php` file contains no `cache` section
3. Using PHP 8.2 and composer v2, upgrade this installation to Magento 2.4.6-p3 (or 2.4-develop)
4. Run `bin/magento setup:upgrade`
6. Your `app/etc/env.php` file will be updated to a new format, but will still not contain a `cache` section.
7. Confirm that Magento works correctly
8. On the frontend visit the `/graphql` url
9. Check your `app/etc/env.php` file and see that a `cache` section has appeared with a `graphql` section but no `frontend` section
10. Visit the homepage or run `bin/magento`
11. See errors/crashes

### Questions or comments
Should we expect that when we run `bin/magento setup:upgrade` it will update your `app/etc/env.php` file with all missing sections? Would people expect this? Or will this cause issues in some scenario's? Running `bin:magento setup:config:set` without extra flags does exactly that. That seems to be some kind of hidden feature ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by hostep**
### Description (*)
Code exists in Magento that assumes your `app/etc/env.php` will always contain a `frontend` section if there is a `cache` section. Like this:
```php
    'cache' => [
        'frontend' => [
            ...
        ]
     ]
```

But that's not always the case. All shops that were setup before Magento 2.3.1 didn't have a `cache` section in their `env.php` file in a default installation (if they didn't use Redis as caching).
If they now upgrade to Magento 2.4.4 or higher and use a graphql endpoint, Magento [automatically writes](https://github.com/magento/magento2/blob/2.4.6-p3/app/code/Magento/GraphQlCache/Model/CacheId/CacheIdCalculator.php#L124-L128) `cache > graphql > id_salt` to the `env.php` file and so introduces a `cache` section without a `frontend` section.

This then leads to this crash on every execution within Magento (frontend, backoffice, `bin/magento`, ...):
```
Warning: Undefined array key "frontend" in lib/internal/Magento/Framework/App/Cache/Frontend/Pool.php on line 90
```

This PR fixes this.

### Fixed Issues (if relevant)
1. Fixes #35812
2. Fixes #35861

### Manual testing scenarios (*)
1. Fully setup a working Magento
2. Edit the `app/etc/env.php` file and remove the entire `frontend` section in the `cache` section
3. Run `bin/magento` or visit the frontend
4. Expected is to not see an error/crash
5. Run added unit test with and without fix. Without the fix, the test will fail (`vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist lib/internal/Magento/Framework/App/Test/Unit/Cache/Frontend/PoolTest.php`)

More elaborate testing scenario that can cause this situation:
1. Using PHP 7.2 and composer v1, setup Magento 2.3.0 and install it fully (don't configure it with Redis caching)
2. Double check that the `app/etc/env.php` file contains no `cache` section
3. Using PHP 8.2 and composer v2, upgrade this installation to Magento 2.4.6-p3 (or 2.4-develop)
4. Run `bin/magento setup:upgrade`
6. Your `app/etc/env.php` file will be updated to a new format, but will still not contain a `cache` section.
7. Confirm that Magento works correctly
8. On the frontend visit the `/graphql` url
9. Check your `app/etc/env.php` file and see that a `cache` section has appeared with a `graphql` section but no `frontend` section
10. Visit the homepage or run `bin/magento`
11. See errors/crashes

### Questions or comments
Should we expect that when we run `bin/magento setup:upgrade` it will update your `app/etc/env.php` file with all missing sections? Would people expect this? Or will this cause issues in some scenario's? Running `bin:magento setup:config:set` without extra flags does exactly that. That seems to be some kind of hidden feature ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38363: Don't assume a frontend cache section exists in the env.php file.

### CODE REVIEW

**Comment by hostep** [comment]
@magento run all tests

**Comment by hostep** [comment]
@magento run all tests

**Comment by swnsma** [comment]
@magento run all tests

**Comment by swnsma** [comment]
@magento run Functional Tests B2B,Functional Tests CE

**Comment by swnsma** [comment]
https://github.com/magento run Functional Tests B2B, Functional Tests CE

**Comment by swnsma** [comment]
@magento run Functional Tests B2B,Functional Tests CE

**Comment by swnsma** [comment]
@magento run Functional Tests CE

**Review by swnsma — APPROVED** [review]

**Review by Den4ik — APPROVED** [review]

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
Fully set-up a working Magento

**Manual testing scenario:**

1. Edit the app/etc/env.php file and remove the entire frontend section in the cache section
2. Run bin/magento or visit the frontend
3. . Expected is to not see an error/crash
4. Run added unit test with and without fix. Without the fix, the test will fail 
(`vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist lib/internal/Magento/Framework/App/Test/Unit/Cache/Frontend/PoolTest.php`)

**Actual Result:** :heavy_check_mark:
The valid home page should be visible in the browser.

**After:** :heavy_check_mark:  
The valid home page should be visible in the browser.
image

**Before:** :heavy_multiplication_x:
image

image

**Tested all the manual scenarios, no impact on regression testing.**

**Comment by engcom-Hotel** [comment]
@magento create issue

**Comment by hostep** [comment]
@engcom-Hotel: you realize that this was already approved and merged? :p

**Pull request merged**
