### PR TITLE
Replace repetitive actions with Action Groups in AdminSimpleProductTypeSwitchingToConfigurableProductTest and AdminConfigurableProductTypeSwitchingToVirtualProductTest

### LINKED ISSUE #33788: [Issue] Replace repetitive actions with Action Groups in AdminSimpleProductTypeSwitchingToConfigurableProductTest and AdminConfigurableProductTypeSwitchingToVirtualProductTest
This issue is automatically created based on existing pull request: magento/magento2#32282: Replace repetitive actions with Action Groups in AdminSimpleProductTypeSwitchingToConfigurableProductTest and AdminConfigurableProductTypeSwitchingToVirtualProductTest

---------

### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run the test in the local environment and verified that it run successfully

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run the test in the local environment and verified that it run successfully

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#33788: Replace repetitive actions with Action Groups in AdminSimpleProductTypeSwitchingToConfigurableProductTest and AdminConfigurableProductTypeSwitchingToVirtualProductTest

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-8918](https://jira.corp.magento.com/browse/ENGCOM-8918) has been created to process this Pull Request

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests EE

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-8918](https://jira.corp.magento.com/browse/ENGCOM-8918) has been created to process this Pull Request

**Comment by eduard13** [comment]
@magento create issue

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8918](https://jira.corp.magento.com/browse/ENGCOM-8918) has been created to process this Pull Request

**Comment by engcom-Charlie** [comment]
✔️ QA Passed

The provided updated MFTF test cases are working fine and green in build. Please find the Allure report for the same.

1. vendor/bin/mftf run:test AdminSimpleProductTypeSwitchingToConfigurableProductTest --remove

image

image


2. vendor/bin/mftf run:test AdminConfigurableProductTypeSwitchingToVirtualProductTest --remove

image

image

**Comment by eduard13** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Pull request merged**
