### PR TITLE
[MFTF] Updating with AdminOpenCMSPagesGridActionGroup

### LINKED ISSUE #31573: [Issue] [MFTF] Updating with AdminOpenCMSPagesGridActionGroup
This issue is automatically created based on existing pull request: magento/magento2#31569: [MFTF] Updating with AdminOpenCMSPagesGridActionGroup

---------
### Description (*)
Test have been updated with AdminOpenCMSPagesGridActionGroup

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
Test have been updated with AdminOpenCMSPagesGridActionGroup

### Resolved issues:
1. [x] resolves magento/magento2#31573: [MFTF] Updating with AdminOpenCMSPagesGridActionGroup

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Comment by sidolov** [comment]
@magento create issue

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Comment by eduard13** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Review by eduard13 — APPROVED** [review]
The failing tests aren't related with these changes.

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8682](https://jira.corp.magento.com/browse/ENGCOM-8682) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Pull request merged**
