### PR TITLE
magento/magento2#37864: Removed unused class from ProductRepository

### LINKED ISSUE #37864: ProductRepository is loading initializationHelper which is an Adminhtml controller
### Summary

The `Magento\Catalog\Model\ProductRepository` is loading the `Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper` in its constructor, but then continues to not use it.

This, on a first look, doesn't seem to cause any issues. However when using some third party modules which extend the `PathInfoProcessor` and that uses the productRepository this is causing some issues with loading in di.xml configurations.

When trying to use the rest-api with an oauth authorization, the `Magento\Framework\App\Http` class is triggered, which first tries to get the area code of the current url. But then the custom logic by the third party is triggered, finally loading in the productRepository. The productRepository then tries to load the above mentioned adminhtml controller, which tries to access the roleLocatorInterface, which is now not based on the webapi_rest/di.xml, but on the default app/etc/di.xml. Causing the `Magento\Framework\Authorization\RoleLocator\DefaultRoleLocator` to be loaded instead of the `Magento\Framework\Authorization\RoleLocatorInterface\WebapiRoleLocator`. This last thing causes the authorization to fail, as the `DefaultRoleLocator` returns `''` instead of executing logic like the `WebapiRoleLocator`.

There is currently no workaround for this.

### Examples

The only thing that is required to be changed for this to work is to remove the `\Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper $initializationHelper,` in `Magento\Catalog\Model\ProductRepository` on line 225.

Which is causing this issue, and isn't being used in the file at all.

### Proposed solution

Remove the loading of `\Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper $initializationHelper,` inside the `Magento\Catalog\Model\ProductRepository`.

### Release note

Removing unused `Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper` from `Magento\Catalog\Model\ProductRepository`

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by BeggiNN**
- Removed unused class \Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper from \Magento\Catalog\Model\ProductRepository

### Description (*)
Removed unused class \Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper which is an Adminhtml controller from \Magento\Catalog\Model\ProductRepository.

When trying to use the rest-api with an oauth authorization, the Magento\Framework\App\Http class is triggered, which first tries to get the area code of the current url. But then the custom logic by the third party is triggered, finally loading in the productRepository. The productRepository then tries to load the above mentioned adminhtml controller, which tries to access the roleLocatorInterface, which is now not based on the webapi_rest/di.xml, but on the default app/etc/di.xml. Causing the Magento\Framework\Authorization\RoleLocator\DefaultRoleLocator to be loaded instead of the Magento\Framework\Authorization\RoleLocatorInterface\WebapiRoleLocator. This last thing causes the authorization to fail, as the DefaultRoleLocator returns '' instead of executing logic like the WebapiRoleLocator.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#37864

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by BeggiNN** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@BeggiNN looks like you described a 2nd issue that this PR fixes.
Could you please report a separate issue for tracking the fix? I think it will require additional test coverage

**Comment by BeggiNN** [comment]
@magento run all tests

**Comment by BeggiNN** [comment]
@magento run Unit Tests, WebAPI Tests

**Comment by BeggiNN** [comment]
@magento run all tests

**Comment by BeggiNN** [comment]
@magento run all tests

**Comment by BeggiNN** [comment]
@magento run Functional Tests EE Functional Tests CE Functional Tests B2B

**Comment by BeggiNN** [comment]
@magento run Semantic Version Checker, Integration Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by BeggiNN** [comment]
@magento run Functional Tests CE

**Comment by BeggiNN** [comment]
@magento run Integration Tests

**Comment by BeggiNN** [comment]
@magento run Integration Tests

**Comment by BeggiNN** [comment]
@magento run Integration Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

**Comment by engcom-Echo** [comment]
### :heavy_check_mark: QA Passed

QA not required.

**Pull request merged**
