### PR TITLE
chore: checkout last 5 commits

### PR DESCRIPTION
**Pull request by DanielRuf**
### Description

By default Travis checks out the last 50 commits. This PR is meant to see the performance gain by checking out the last 5 commits.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by DanielRuf** [comment]
Some test timeout: https://travis-ci.org/magento/magento2/jobs/375364647

Should I push a new empty commit to trigger a new build or can someone retry the failing build?

We also need more and faster builds.

**Comment by VladimirZaets** [comment]
Hi @DanielRuf , I restarted the build.

**Comment by DanielRuf** [comment]
> Hi @DanielRuf , I restarted the build.

Thanks.

**Comment by VladimirZaets** [comment]
@DanielRuf but I have one question, why 5? rather than 1 as an example?

**Comment by DanielRuf** [comment]
> @DanielRuf but I have one question, why 5? rather than 1 as an example?

https://docs.travis-ci.com/user/customizing-the-build#Git-Clone-Depth

> Please note that if you use a depth of 1 and have a queue of jobs, Travis CI won’t build commits that are in the queue when you push a new commit.

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

**Pull request merged**
