### PR TITLE
Add variable font size for input display on iOS

### LINKED ISSUE #32261: [Issue] Add variable font size for input display on iOS
This issue is automatically created based on existing pull request: magento/magento2#32253: Add variable font size for input display on iOS

---------

### Description (*)

This PR  just improvement add variable default for input allow reuse in frontend
Before if we set font size below 16px when focus input display on iOS devices will zoom screen
With this variable FE devs can reuse or re-define they own value

https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone
https://www.warrenchandler.com/2019/04/02/stop-iphones-from-zooming-in-on-form-fields/

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Go to real mobile device
2. Navigate to search input
3. Focus to input by search something

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

This PR  just improvement add variable default for input allow reuse in frontend
Before if we set font size below 16px when focus input display on iOS devices will zoom screen
With this variable FE devs can reuse or re-define they own value

https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone
https://www.warrenchandler.com/2019/04/02/stop-iphones-from-zooming-in-on-form-fields/

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Go to real mobile device
2. Navigate to search input
3. Focus to input by search something

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32261: Add variable font size for input display on iOS

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Static Tests, Integration Tests, Functional Tests EE

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by mrtuvn** [comment]
@magento run Static Tests, Functional Tests EE

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8810](https://jira.corp.magento.com/browse/ENGCOM-8810) has been created to process this Pull Request

**Comment by mrtuvn** [comment]
@magento run Static Tests, Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento run Static Tests, Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE

**Comment by engcom-Bravo** [comment]
Hi @mrtuvn,

We are closing this PR.The PR is in Draft since longtime.

Once you are ready Please feel free to reopen it to process the PR further.

Thanks

**Pull request closed without merging**
