### PR TITLE
Changed element to name for move action

### PR DESCRIPTION
**Pull request by lazyguru**
See #1376 for reference.  GitHub doesn't allow reopening a PR when a force push is done (had to be done after rebasing develop to my branch) so I'm opening a new PR for review.

### CODE REVIEW

**Comment by Vinai** [comment]
You really want to stick to the use of `name` instead of `element` after all, even though the latter reads much nicer?

**Comment by lazyguru** [comment]
As I said in the original, I don't care which we use.  However, it should be consistent.  "name" is used by all of the other commands so that is why I created this PR to change element to move.  We could certainly change all of the other ones to "element" instead of "name"

**Comment by Stuperfied** [comment]
Unless your planning on defining a new international standard it doesn't matter from a programming point of view as long as your consistent and the label somewhat describes what it is identifying. Kind of like KB, MB, GB, (now KiB etc... because of a minor few idealists), the name was inaccurate but everyone understood.

**Comment by KrystynaKabannyk** [comment]
Hello @lazyguru, can you please update the code and cover it by Travis tests?

**Comment by lazyguru** [comment]
Rebased branch against develop and update commit for files that have changed (some new files using <move element= and some files that have been removed since my original commit).  I see Travis build is green now

**Comment by daim2k5** [comment]
Thank you for your contribution. Please accept the contributors license agreement so this PR can be further processed. This can be done by clicking the "Details" link next to the "license/cla" check below.

**Comment by lazyguru** [comment]
Done (I had done it previously but I did it again just now.  However, it looks like it is not updating?)

**Comment by lazyguru** [comment]
I have tried repeatedly to re-sign the CLA (as I said before, I signed it a long time ago already).  I think there is something wrong with your CLA assistant.  See screenshot here showing that I have signed it:

screen shot 2016-03-31 at 2 52 40 pm

**Comment by daim2k5** [comment]
@lazyguru working now :-)

**Comment by vrann** [comment]
@lazyguru on the latest develop branch the only supported attribute for the move element is ``element``: https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/View/Layout/etc/elements.xsd#L300

I searched through the code and found just one instance of the ``<move name="..">`` while there are 73 instances of the ``<move element="..">``

Sorry for such a delay on this PR but it seems like consistency issue was fixed meanwhile.

**Comment by lazyguru** [comment]
@vrann the consistency issue is between the syntax of <move element vs <rename name or <add name, etc...  if you found instances of <move name, those would be bugs (introduced AFTER I created this PR) and would actually be reasons to support accepting this PR as clearly even core devs get confused about the inconsistency between move/rename/add commands using different identifiers.

**Comment by vrann** [comment]
@lazyguru I see what you mean. That one instance was in tests, so not a bug. Regarding consistency with the ``rename name`` - this will be backward incompatible change, which will break any third-party extension which is using the move node. I would not advocate for such change because the compatibility is more important here.

**Comment by lazyguru** [comment]
I understand. It's a shame the original PR wasn't accepted 2 years ago when I submitted it. Perhaps a future change could support both name and element and then deprecate element?

**Comment by vrann** [comment]
@lazyguru that's a possibility let me sync up with the architect in this area.

**Pull request closed without merging**
