### PR TITLE
[Cms] Added a getByIdentifier() method to the block reposistory

### PR DESCRIPTION
**Pull request by enrico69**
### Description
Added a _getByIdentifier()_ method to the cms block repository. This method is usefull when you wan to edit block in _UpgradeData_ scripts. 

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=8858) <br/>All committers have signed the CLA.

**Comment by orlangur** [comment]
"All new or changed code is covered with unit/integration tests" is checked for no reason currently ;)

**Comment by convenient** [comment]
Might be useful to be aware of https://github.com/magento/magento2/issues/6570 and https://github.com/magento/magento2/pull/7417 in which identifier is not enough to update cms blocks by identifier when that identifier is shared across multiple stores.

**Comment by enrico69** [comment]
Will take in to account all the comments in the request.

**Pull request closed without merging**
