### PR TITLE
Fix for issue #3019 (blank password/obscure field)

### PR DESCRIPTION
**Pull request by srenon**
Bug - Blank value for field type password/obscure when switch store view in store config

### CODE REVIEW

**Comment by srenon** [comment]
The testing script will need to be updated since is expecting hasBackendModel() to be called 1 time.

1) Magento\Config\Test\Unit\Block\System\Config\FormTest::testInitFields with data set #1 (array(), 'Config Value', 'some/config/path', true, 'Config Value')
Expectation failed for method name is equal to string:hasBackendModel when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.

**Comment by mazhalai** [comment]
Related internal ticket MAGETWO-48100

**Comment by mazhalai** [comment]
@srenon Please fix uint tests and sync with latest develop

**Comment by mazhalai** [comment]
MAGETWO-48100

**Comment by mazhalai** [comment]
@srenon thank you for your contribution, your PR has been merged.

**Comment by mimarcel** [comment]
Hello @srenon ,

Please note that PR https://github.com/magento/magento2/pull/6231 was created to revert current PR due to another issue. Since screenshot in issue https://github.com/magento/magento2/issues/3019 shows a problem with a field in Gmail/Google Apps SMPT Pro, I assume this is a 3rd party extension which should fix their backend model to correctly handle the values.

**Comment by srenon** [comment]
@mimarcel .... Yes the screen shot was from a third party extension but this also affect core module that uses "password/obscure". This should be a cause by the the same issue https://github.com/magento/magento2/issues/2984

To replicate this issue all you need to do is to create a system.xml with

```
<field id="production_secret" translate="label" type="obscure" >
           <label>Production Secret</label>
           <backend_model>Magento\Config\Model\Config\Backend\Encrypted</backend_model>
</field>
```

Then echo the value with `echo $this->getConfigData('production_secret');`

**Comment by mimarcel** [comment]
@srenon I can not replicate the issue.

### Preconditions:
1. have latest M2.1 installed
2. apply fix from https://github.com/magento/magento2/pull/6231

### Steps
- Add system config field

``` xml
                <field id="production_secret" translate="label" type="obscure" sortOrder="1" showInDefault="1" showInWebsite="1" showInStore="1" >
                    <label>Production Secret</label>
                    <backend_model>Magento\Config\Model\Config\Backend\Encrypted</backend_model>
                </field>
```
- Set a value on admin store.
- Switch to another store.

### Result:
- the password is still there, it is not blank.

**Pull request merged**
