### PR TITLE
Enable using URI segments that do not belong to a key-value pair.

### PR DESCRIPTION
**Pull request by berkanduzgun**
### Description
You can find description here => https://github.com/magento/magento2/issues/12242

### Fixed Issues (if relevant)
1. magento/magento2#12242: Fourth URI segment is lost during redirection

### Manual testing scenarios
1. Make a request to http://example.com/test-1/test-2/test-3/test-4.html
2. Magento redirects to https://example.com/test-1/test-2/test-3/test-4.html as expected.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=12243) <br/>All committers have signed the CLA.

**Comment by miguelbalparda** [comment]
This is breaking some tests, can you check them?

**Comment by berkanduzgun** [comment]
I will check them @miguelbalparda

**Comment by sidolov** [comment]
Hi @berkanduzgun, with provided fix several integration tests became failed. 
Something went wrong with new implementation, url building is not correct for some cases:

```
Magento\Catalog\Model\CategoryTest::testGetCategoryIdUrl
Failed asserting that 'http://localhost/index.php/catalog/category/view/s/id/' ends with "catalog/category/view/".

Magento\Catalog\Model\CategoryTest::testGetUrl
Failed asserting that 'http://localhost/index.php/catalog/category/view/s/id/' ends with "catalog/category/view/".

Magento\Catalog\Model\ProductExternalTest::testGetProductUrl
Failed asserting that 'http://localhost/index.php/catalog/product/view/id/s/' ends with "catalog/product/view/".
```

**Comment by sidolov** [comment]
Hi @berkanduzgun , will you continue work with PR?

**Comment by berkanduzgun** [comment]
@sidolov I would like to continue. I see that you have a deadline set for December. I cannot promise a solution in that time frame but can try my best.

**Comment by sidolov** [comment]
@berkanduzgun , as an option, we can close this PR now and you will reopen it if you wish to continue

**Comment by berkanduzgun** [comment]
@sidolov , I have found a different solution and now CI fails because of a simple phpcs problem. I will fix it today.

**Comment by berkanduzgun** [comment]
@sidolov Currently this one passes the checks. You may review the solution when you are ready.

**Comment by sidolov** [comment]
Hi @berkanduzgun, I investigated this issue deeply. 

Provided solution looks like workaround, but the main problem is not fixed. I think we need fix  method **\Magento\Store\App\FrontController\Plugin\RequestPreprocessor::aroundDispatch**:
1. move check **$this->isHttpsRedirect($request)** to the method beginning and send redirect if the request is not secure. 
2. use **\Magento\Framework\App\Router\PathConfigInterface::getCurrentSecureUrl** method for build new secure url based on the current 
3. Fix **\Magento\Store\App\FrontController\Plugin\RequestPreprocessor::isHttpsRedirect** method (remove check for POST type, this fix will allow check all request types)

As result might be something like this: 

```
if ($this->isHttpsRedirect($request)) {
     /** @var \Magento\Framework\App\Router\PathConfigInterface $pathConfig */
     $redirectUrl = $pathConfig->getCurrentSecureUrl($request);
     ....
     return $redirect;
}
```

**Comment by berkanduzgun** [comment]
@sidolov thanks for your review and suggestion. Honestly I am not convinced. Because the solution you propose does not solve the problem when another type of base URL redirection is performed. For example:

Base URL : https://www.example.com/
Requested URL : https://example.com/1/2/3/4/5

I am open for further suggestions to improve the solution of course.

**Comment by sidolov** [comment]
Hi @berkanduzgun , i can't propose any good solution for the issue right now. I propose close PR and reopen it when you wish to continue.

**Comment by berkanduzgun** [comment]
Hi @sidolov, why do you think current changes are workaround?

You may close the PR but the problem will continue to exist.

**Comment by sidolov** [comment]
Hi @berkanduzgun , i think the current solution is workaround because getUrl must return valid redirect URL without any magic parameters (like '_base_url_redirection'). So, we need more generic fix for all cases (including all client code with usages in 3d party extensions)

**Comment by sidolov** [comment]
Hi @berkanduzgun , I'm closing this PR for now, reopen it if you have the different solution. Thank you for collaboration!

**Pull request closed without merging**
