### PR TITLE
Fix address custom attributes to be object instead of an array

### PR DESCRIPTION
**Pull request by BrentRobert**
### Description (*)

When logged in with a saved address, custom_attributes in the billing-address and shipping-address will be an object as following:
```
customAttributes = {
  number: {
    attribute_code: 'number',
    value: '33'
  },
  box_number: {
    attribute_code: 'box_number',
    value: 'bus 4'
  }
}
```
When NOT logged in, custom_attributes in the billing-address and shipping-address are converted to an array as following:
```
customAttributes = [
  {
    attribute_code: 'number',
    value: '33'
  },
  {
    attribute_code: 'box_number',
    value: 'bus 4'
  }
]
```

This pull request makes sure both cases are objects.

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by BrentRobert** [comment]
Any help on how to fix these tests? They seem to be EE.

**Comment by BrentRobert** [comment]
@viktym is this something you might be able to look into?

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Hi @BrentRobert. Could you please elaborate what is the business case or bug you are trying to solve with this PR?

**Comment by lenaorobei** [comment]
Closing this PR due to inactivity. Please feel free to reopen if you are going to continue working on it.
Thank you.

**Pull request closed without merging**
