### PR TITLE
#11627 Fix query filter configurable products

### PR DESCRIPTION
**Pull request by jmorenoons**
Poblem when filter a product list whith configurable product attribute and simple product attribute.

### Description
Change the query that do a join when apply filters in catalog product list. Now the query validate that the attribute exist for configurable product or for simple product assigned to configurable.

### Fixed Issues (if relevant)
1. magento/magento2#11627: Problem with the attribute color

### Manual testing scenarios
1. Click Men - Bottoms - Pants -> 12 items
2. Click Style - Leggings -> 4 items, 2 in green
3. Click Color - Green

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=12123) <br/>All committers have signed the CLA.

**Comment by dmanners** [comment]
@jmorenoons could you have a look at the integration test failures? If you need help with running these tests the dev docs have a good page on the matter http://devdocs.magento.com/guides/v2.2/test/integration/integration_test_execution.html

```
There were 2 failures:
1) Magento\CatalogSearch\Model\Search\FilterMapper\CustomAttributeFilterTest::testApplyByOneFilter
Select queries must be the same in case when we have one filter to apply.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 'SELECT `some_index`.`entity_id` FROM `some_table` AS `some_index`\n
- INNER JOIN `trv_catalog_product_index_eav` AS `field1_filter` ON `some_index`.`entity_id` = `field1_filter`.`entity_id` AND `some_index`.`source_id` = `field1_filter`.`source_id` AND `field1_filter`.`attribute_id` = 42 AND `field1_filter`.`store_id` = 1 WHERE (`some_index`.`attribute_id` = 42) AND (`some_index`.`value` = 'value2')'
+ INNER JOIN `trv_catalog_product_index_eav` AS `field1_filter` ON (`some_index`.`entity_id` = `field1_filter`.`entity_id` OR `some_index`.`source_id` = `field1_filter`.`source_id`) AND `field1_filter`.`attribute_id` = 42 AND `field1_filter`.`store_id` = 1 WHERE (`some_index`.`attribute_id` = 42) AND (`some_index`.`value` = 'value2')'
/home/travis/build/magento/magento2/dev/tests/integration/testsuite/Magento/CatalogSearch/Model/Search/FilterMapper/CustomAttributeFilterTest.php:114
2) Magento\CatalogSearch\Model\Search\FilterMapper\CustomAttributeFilterTest::testApplyByTwoFilters
Select queries must be the same in case when we have two filters to apply.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 'SELECT `some_index`.`entity_id` FROM `some_table` AS `some_index`\n
- INNER JOIN `trv_catalog_product_index_eav` AS `field1_filter` ON `some_index`.`entity_id` = `field1_filter`.`entity_id` AND `some_index`.`source_id` = `field1_filter`.`source_id` AND `field1_filter`.`attribute_id` = 42 AND `field1_filter`.`store_id` = 1\n
- INNER JOIN `trv_catalog_product_index_eav` AS `field2_filter` ON `some_index`.`entity_id` = `field2_filter`.`entity_id` AND `some_index`.`source_id` = `field2_filter`.`source_id` AND `field2_filter`.`attribute_id` = 450 AND `field2_filter`.`store_id` = 1'
+ INNER JOIN `trv_catalog_product_index_eav` AS `field1_filter` ON (`some_index`.`entity_id` = `field1_filter`.`entity_id` OR `some_index`.`source_id` = `field1_filter`.`source_id`) AND `field1_filter`.`attribute_id` = 42 AND `field1_filter`.`store_id` = 1\n
+ INNER JOIN `trv_catalog_product_index_eav` AS `field2_filter` ON (`some_index`.`entity_id` = `field2_filter`.`entity_id` OR `some_index`.`source_id` = `field2_filter`.`source_id`) AND `field2_filter`.`attribute_id` = 450 AND `field2_filter`.`store_id` = 1'
/home/travis/build/magento/magento2/dev/tests/integration/testsuite/Magento/CatalogSearch/Model/Search/FilterMapper/CustomAttributeFilterTest.php:145
FAILURES!
Tests: 2124, Assertions: 9539, Failures: 2, Skipped: 77, Incomplete: 49.
```

**Comment by AVoskoboinikov** [comment]
Hi @jmorenoons 
Thanks for contribution, this is something we definitely should fix. But I believe we need to look for more performance-safe solution than just replacing AND with OR. I've made a benchmark for two queries 
[with_and.sql.txt](https://github.com/magento/magento2/files/1502087/with_and.sql.txt) and [with_or.sql.txt](https://github.com/magento/magento2/files/1502088/with_or.sql.txt). The result is that query with "AND" takes less than 1 second. Query with "OR" takes about 50 seconds. We need to find more appropriate solution for this. 
You can make the same benchmark as I did with our performance-toolkit with ee medium profile and mysqlslap. If you have any suggestions feel free to reach us.

**Comment by AVoskoboinikov** [comment]
@jmorenoons, @ishakhsuvarov 
Check this patch file [search_attr.txt](https://github.com/magento/magento2/files/1505462/search_attr.txt) - this should be more performance-safe fix. 

But please, make benchmarks before merging. Our internal Performance build will not cover this fix, so it is better to use mysqlslap to test it. Thanks.

**Comment by ishakhsuvarov** [comment]
Hi @jmorenoons 
Would you like to proceed with this PR? Could you please look at proposal by @AzVo.
Thanks

**Comment by ishakhsuvarov** [comment]
@jmorenoons We are closing this PR for now due to inactivity. 
Please reopen and check suggestion by @AzVo if you wish to proceed.

Thank you for collaboration.

**Pull request closed without merging**
