### PR TITLE
Trying to get data from non existent products

### PR DESCRIPTION
**Pull request by angelo983**
When calling Products in Cart report, it called data of deleted products resulting in exception trying to access $productData[$item->getProductId()]

### Preconditions

1. Magento 2.1.10

### Steps to reproduce

1. Delete a product recently sold
1. Open Reports > Marketing > Products in Cart

### Expected result

1. List of products

### Actual result

1. Blank list

### CODE REVIEW

**Comment by dmanners** [comment]
Thank you @angelo983 for your PR. Could you please add some manual test cases and mention any related issue. See our guidelines for more information https://github.com/magento/magento2/blob/2.2-develop/PULL_REQUEST_TEMPLATE.md

**Comment by ishakhsuvarov** [comment]
Hi @angelo983 
Would be really nice if you could provide a similar fix for `2.2-develop` and possibly `2.3-develop` as well.
Thanks

**Comment by angelo983** [comment]
@ishakhsuvarov have I to open new pull requests to provide a similar fix for 2.2-develop and possibly 2.3-develop?

**Comment by ishakhsuvarov** [comment]
@angelo983 That would be really helpful

**Comment by angelo983** [comment]
Now I have applied the same fix for 2.2-develop and 2.3-develop but I had to open other two pull requests.

**Comment by ishakhsuvarov** [comment]
@angelo983 Thank you

**Pull request merged**
