### PR TITLE
#27500 Prepare Tax module Tests for PHPUnit 8

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Preparing PHPUnit Tests to run with PHPUnit 8.
PRs for each module is separated to make tests easier to merge.

### Fixed Issues (if relevant)
1. magento/magento2#27500

### Manual testing scenarios (*)
N/A

### Questions or comments
PR #27701 needs to be merged first (otherwise PHPUnit tests fail)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — CHANGES_REQUESTED** [review]
There's one "gremlin" still hiding from us 

https://github.com/magento/magento2/blob/5796c66706dedbc11a918e39fc585e415eb99b6f/app/code/Magento/Tax/Test/Unit/Controller/Adminhtml/Rate/AjaxLoadTest.php#L31

**Comment by lbajsarowicz** [comment]
Looks like for that file one of the tools was not run.
Thank you @rogyar for being aware :-)

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7424](https://jira.corp.magento.com/browse/ENGCOM-7424) has been created to process this Pull Request

**Comment by slavvka** [comment]
@magento run Database Compare

**Pull request merged**
