### PR TITLE
[Catalog] Fixing the position of the sidebar removing icon on product listing page

### PR DESCRIPTION
**Pull request by eduard13**
### Description (*)
This PR fixes the X positioning for sidebar wishlist items on category pages.

### Fixed Issues (if relevant)

1. magento/magento2#21190: The Wishlist removing icon isn't correctly positioned on category pages
2. ...

### Manual testing scenarios (*)
Check the task's steps

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-21191.instances.magento-community.engineering).
Admin access: [https://pr-21191.instances.magento-community.engineering/admin](https://pr-21191.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4244](https://jira.corp.magento.com/browse/ENGCOM-4244) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @eduard13 the remove icon position is still slightly shifted to the bottom. Can you please take a look:
image

**Comment by eduard13** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @eduard13, here is your [new Magento instance](https://pr-21191.instances.magento-community.engineering).
Admin access: [https://pr-21191.instances.magento-community.engineering/admin](https://pr-21191.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sidolov** [comment]
@eduard13 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
