### PR TITLE
magento/magento2#: Add additional test coverage to “updateCustomer” mutation

### LINKED ISSUE #28394: [Issue] magento/magento2#: Add additional test coverage to “updateCustomer” mutation
This issue is automatically created based on existing pull request: magento/magento2#28304: magento/magento2#: Add additional test coverage to “updateCustomer” mutation

---------

### Description (*)

PR adds a test coverage for the next cases of `updateCustomer` mutation:
- Invalid date of birth
- Invalid email address
- Empty customer last name

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by atwixfirster**
### Description (*)

PR adds a test coverage for the next cases of `updateCustomer` mutation:
- Invalid date of birth
- Invalid email address
- Empty customer last name

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28394: magento/magento2#: Add additional test coverage to “updateCustomer” mutation

### CODE REVIEW

**Comment by atwixfirster** [comment]
@magento run all tests

**Comment by atwixfirster** [comment]
@magento run all tests

**Comment by atwixfirster** [comment]
@rogyar , could you please review this one? Failed static tests are not tie to a proposed changes.

Thank you!

**Comment by rogyar** [comment]
@magento run all tests

**Review by rogyar — APPROVED** [review]
The failing tests are not related to the current changes

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7593](https://jira.corp.magento.com/browse/ENGCOM-7593) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Charlie** [comment]
Failed tests not related to changes from this PR.

**Comment by slavvka** [comment]
@magento create issue

**Comment by engcom-Charlie** [comment]
Failed tests not related to changes from this PR.

**Pull request merged**
