### PR TITLE
[Forwardport] CSS load order incorrect using default_head_blocks.xml #1821

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Original Pull Request 
 https://github.com/magento/magento2/pull/14290
Added new attribute 'order' for set loading order .
Those attribute resolve issue about render files for some order.

### Fixed Issues (if relevant)
1. magento/magento2#1821: CSS load order incorrect using default_head_blocks.xml #1821

### CODE REVIEW

**Comment by VladimirZaets** [comment]
Hi, @ihor-sviziev , thank you for collaboration. But, unfortunately, this isn't the full fix. Please look at commits `21cb3af6210c248097e9d6b27a473a1456973b16` , `51c78b9414a3e23bc8d31cd571b98b95d0c949b9`  and `ad82a7aadafcc67e451a090afed6d5258512101d` in current 2.2-develop branch.

**Review by VladimirZaets — APPROVED** [review]

**Comment by ishakhsuvarov** [comment]
@magento-engcom-team give me new test instance

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov, here is your [new Magento instance](https://pr-14815.engcom.dev.magento.com).
Admin access: [https://pr-14815.engcom.dev.magento.com/admin](https://pr-14815.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Please make sure you are PR **author** or **assignee** to access the instance.

**Comment by ishakhsuvarov** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov, here is your [Magento instance](https://i-14815-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-14815-2-3-develop.engcom.dev.magento.com/admin](https://i-14815-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by VladimirZaets** [comment]
Hi @ihor-sviziev , currently this fix breaks down the `swagger` functionality. The problem is in `swagger` implementation. Swagger does not have dependencies. Because your fix changes the loading order, the Swagger is loading before than libraries that he uses.
The Swagger was fixed and updated in Magento 2.2 version, so will be great if you make forward port to Magento 2.3

**Comment by ihor-sviziev** [comment]
Hi @VladimirZaets,
I don't have free time to fix these issues. I'm closing my PR.
Feel free to create new forwardport PR if you have time for that.

**Pull request closed without merging**
