### PR TITLE
Fixed #20038 loading icon disappearing before background process completes for Braintree payment in Admin

### LINKED ISSUE #20038: loading icon disappearing before background process completes for braintree payment (Admin order)
### Preconditions (*)

1. Magento 2.1.15
2.

### Steps to reproduce (*)

1. Enable Braintree payment method 
2. Navigate to create order page in admin
3. Add items, Enter address, Select shipping method
4. Select braintree credit card/braintree saved card as payment method
5. Click on submit button(at the bottom of the page)

### Expected result (*)

1. Loading icon must be displayed untill the page is redirected to new order view page.

### Actual result (*)

1. Loading icon is disappearing before background process completes (https://www.screencast.com/t/AqqwzC0B ). 
2. Since loading icon is disappeared, admin can click on another submit button(at the top). If so, multiple orders are creating.

### PR DESCRIPTION
**Pull request by ghost**
### Fixed Issues (if relevant)

1. magento/magento2#20038: loading icon disappearing before background process completes for braintree payment (Admin order)

### Manual testing scenarios (*)

1. Login to the Admin
2. Create a order for a customer
3. Use Credit Card(BrainTree) payment method
4. Click 'Submit Order' button
5. Full page loader should be visible until user is redirected to succes page or error occurs.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22675) <br/>All committers have signed the CLA.

**Comment by ronak2ram** [comment]
Hi @kunal-rtpl, please, sign CLA, otherwise, we can't process your pull request.

**Comment by ghost** [comment]
> Hi @kunal-rtpl, please, sign CLA, otherwise, we can't process your pull request.

Hi ronak2ram, signed

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5324](https://jira.corp.magento.com/browse/ENGCOM-5324) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
