### PR TITLE
[Forwardport] fixed - Default values are not rendering on Wishlist product edit page

### PR DESCRIPTION
**Pull request by edenduong**
### Original Pull Request 
 https://github.com/magento/magento2/pull/18967

### Description (*)
While editing wishlist item that has configuration, it will not visible selected on configuration page. But after applying this fix it will work.

### Fixed Issues (if relevant)

1. magento/magento2#18555: Magento 2.2.6 Default values are not rendering on Wishlist product edit page

### Manual testing scenarios (*)

1. Add any configurable product with configured attributes to wishlist
2. Now edit the item from wishlist to change the configuration.
3. On Item configuration page the previously opted option will get selected automatically.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by rodrigowebjump** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [new Magento instance](https://pr-23838.instances.magento-community.engineering).
Admin access: [https://pr-23838.instances.magento-community.engineering/admin](https://pr-23838.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rodrigowebjump** [comment]
Hi @edenduong Thanks for your contribution.

The issue still happening for visual or text swatch.
Please, could you test it again?

**Review by sidolov — APPROVED** [review]

**Review by sidolov — CHANGES_REQUESTED** [review]
Please, verify issue once again. See @rodrigowebjump comment

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5556](https://jira.corp.magento.com/browse/ENGCOM-5556) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by edenduong** [comment]
I close this Pull Request because seems the origin solution has problem. So this Port Pull Request has the same.

**Pull request closed without merging**
