### PR TITLE
[MFTF] Refactoring of AdminUpdateSimpleProduct...Tests (asserting product details on Storefront)

### LINKED ISSUE #31248: [Issue] [MFTF] Refactoring of AdminUpdateSimpleProduct...Tests (asserting product details on Storefront)
This issue is automatically created based on existing pull request: magento/magento2#31247: [MFTF] Refactoring of AdminUpdateSimpleProduct...Tests (asserting product details on Storefront)

---------
### Description (*)
Asserting product details on Storefront has been refactored in **_AdminUpdateSimpleProduct...Tests_** 
(according to the best practices)

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
Asserting product details on Storefront has been refactored in **_AdminUpdateSimpleProduct...Tests_** 
(according to the best practices)

### Resolved issues:
1. [x] resolves magento/magento2#31248: [MFTF] Refactoring of AdminUpdateSimpleProduct...Tests (asserting product details on Storefront)

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Review by rogyar — APPROVED** [review]
Great job!

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8536](https://jira.corp.magento.com/browse/ENGCOM-8536) has been created to process this Pull Request
:eight_spoked_asterisk: @rogyar, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** Some tests are in waiting status

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @AnnaAPak, thanks for contributing! Can you resolve the conflicts on this PR?

Thanks!

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Pull request merged**
