### PR TITLE
Remove redundant model load

### PR DESCRIPTION
**Pull request by benyatesvortex**
Removes unnecessary mode load which has a negative impact on performance

### Description (*)
The model load that has been removed is now redundant due to the `afterGetProductAttributes()` method in `sales-rule/Model/Plugin/QuoteConfigProductAttributes.php`. 

### Manual testing scenarios (*)

1. ... Add a quote item associated with a sales rule to the cart
2. ...Ensure quote item is added with applicable rules applied

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by benyatesvortex** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @benyatesvortex. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @benyatesvortex, here is your [new Magento instance](https://pr-25681.instances.magento-community.engineering).
Admin access: [https://pr-25681.instances.magento-community.engineering/admin](https://pr-25681.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by lenaorobei** [comment]
Please address unit test failures https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/25681/47f97ae34b7a052f2d69806dfe935722/Unit/allure-report-ce/index.html#suites/b20d0e4f61ee2e8ee71033ab62db4e78

**Comment by lenaorobei** [comment]
Closing this PR due to inactivity. Please feel free to reopen if you are still up to finishing it.

**Pull request closed without merging**
