### PR TITLE
Revert "Removing the MatchMedia"

### PR DESCRIPTION
**Pull request by andrewbess**
### Description (*)

This pull request (PR) reverts commit 34dcfd434c389455c60cae59d799e59c8e92b78a by the license reasons.
The issue magento/magento2#33865 has been reopened.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@andrewbess, could you provide some more details on this?

**Review by eduard13 — APPROVED** [review]

**Comment by andrewbess** [comment]
> @andrewbess, could you provide some more details on this?

Hello @ihor-sviziev 
Thank you for your question

Please read license https://creativecommons.org/licenses/by-sa/3.0/

> ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

**Comment by andrewbess** [comment]
The currency converter API is down again
currency-converter-api-is-down

**Pull request merged**
