### PR TITLE
Resolved Typo

### PR DESCRIPTION
**Pull request by UdgamN**
### Description (*)
Fixed Typo issue

### Fixed Issues (if relevant)

Expected Result : 
The following markup corresponds to the accessibility demands on line number 11.

Actual Result : 
The following markup corresponds to the accesibility demands

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22621) <br/>All committers have signed the CLA.

**Review by orlangur — APPROVED** [review]
Same as https://github.com/magento/magento2/pull/22569/files but in another file.

During delivery please check no more occurrences of `accesibility` in code.

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-5033](https://jira.corp.magento.com/browse/ENGCOM-5033) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@UdgamN thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by UdgamN** [comment]
> Same as https://github.com/magento/magento2/pull/22569/files but in another file.
> 
> During delivery please check no more occurrences of `accesibility` in code.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-5035](https://jira.corp.magento.com/browse/ENGCOM-5035) has been created to process this Pull Request

**Pull request merged**
