### PR TITLE
add permission check for "reload data" data button

### LINKED ISSUE #38283: [Issue] add permission check for "reload data" data button
This issue is automatically created based on existing pull request: magento/magento2#38279: add permission check for "reload data" data button

---------
despite that the user does not have permission for refreshing the statistics button, it is shown and when pressed a "not permitted" page is shown.

therefore add the check that is used with that controller action.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. create a new user role, without the permission Magento_Reports::statistics
2. create a new user with that role

Expected:
3. no "Reload Data" button is shown, as there is no permission for that 

Actual:
3. the "Reload Data" button is shown and clickable
4. on click of the "Reload Data" button a "not permitted"-page is shown to the user

### Questions or comments
Additional to that missing permission check, this function (including the controller \Magento\Backend\Controller\Adminhtml\Dashboard\RefreshStatistics) should be migrated to the reporting module for dependencies sakes and the refreshstatistics.phtml be renamed to dashboard_actions.phtml or so as it already shows all childhtml elements (so anyone could contribute new actions) - the reload-feature should not be any different

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by brosenberger**
despite that the user does not have permission for refreshing the statistics button, it is shown and when pressed a "not permitted" page is shown.

therefore add the check that is used with that controller action.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. create a new user role, without the permission Magento_Reports::statistics
2. create a new user with that role

Expected:
3. no "Reload Data" button is shown, as there is no permission for that 

Actual:
3. the "Reload Data" button is shown and clickable
4. on click of the "Reload Data" button a "not permitted"-page is shown to the user

### Questions or comments
Additional to that missing permission check, this function (including the controller \Magento\Backend\Controller\Adminhtml\Dashboard\RefreshStatistics) should be migrated to the reporting module for dependencies sakes and the refreshstatistics.phtml be renamed to dashboard_actions.phtml or so as it already shows all childhtml elements (so anyone could contribute new actions) - the reload-feature should not be any different

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38283: add permission check for "reload data" data button

### CODE REVIEW

**Comment by brosenberger** [comment]
@magento run all tests

**Comment by brosenberger** [comment]
https://github.com/magento run all tests

**Comment by engcom-Bravo** [comment]
@magento create issue

**Comment by brosenberger** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
Hi @brosenberger,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- create a new user role, without the permission Magento_Reports::statistics
- create a new user with that role


**Before:** :heavy_multiplication_x: 

Screenshot 2024-09-18 at 11 46 01



**After:** :heavy_check_mark: 

There will be no `RELOAD DATA` Button.

Screenshot 2024-09-18 at 11 50 31



Screenshot 2024-09-18 at 11 50 03



Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Static test failures have been fixed.

The functional B2B failures are not consistent in recent 2 builds, seems to be flaky. They are not part of PR or failing because of PR changes.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38279/5eccafdfe6071bb45fa45da5ef18096b/Functional/allure-report-b2b/index.html#categories

image

**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38279/530f183c5e93a232a5101c6fdc499fc2/Functional/allure-report-b2b/index.html#categories

image

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Pull request merged**
