### PR TITLE
Re-throw catched exceptions thrown inside code generation autoloader

### LINKED ISSUE #34028: Missing classes required by DI in commands are not reported & logs are misleading
### Summary (*)
When a class requested in the constructor of a Command does not exist, a misleading error is shown instead of the actual source of the problem. When running bin/magento the output is just "Class Vendor\SomeModule\Console\Command\SomeCommand\Interceptor does not exist". 
To fix the problem the developer is forced to open the logfiles.

### Examples (*)
Create a new module with a command that injects a class that cannot be autoloaded (Class XYZ). Try to run the command or just bin/magento. Instead of printing "Class XYZ does not exist" it prints "The Interceptor does not exist. "

### Proposed solution
It seems to be enough to add a "throw $exception;" after [line 55 in framework/Code/Generator/Autoloader.php](https://github.com/magento/magento2/blob/f0f779a07596da9be8845050815f83dd907f3844/lib/internal/Magento/Framework/Code/Generator/Autoloader.php#L55)
The message should be changed, too as the possible reason is described as a permission issue only.
But i dont about other possible consequences/side effects of this change.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by marvinhinz**
Re-throw catched exceptions thrown inside code generation autoloader. This goes against psr-4, but it makes sense in this case. 

### Description (*)
Please see issue #34028 

### Fixed Issues (if relevant)
1. Fixes magento/magento2#34028

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
It looks like your change causing webapi test failures. Could you check it?

**Comment by marvinhinz** [comment]
@magento run all tests

**Comment by marvinhinz** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Hi @marvinhinz,
Will you be able to update your PR?

**Comment by engcom-Lima** [comment]
Hi @ihor-sviziev, the failures are there as the autoloader is throwing exceptions, however as per [PSR-4 2.4](https://www.php-fig.org/psr/psr-4/) standard ```Autoloader implementations MUST NOT throw exceptions, MUST NOT raise errors of any level, and SHOULD NOT return a value.```

And as the autoloader is throwing exceptions response code **500** is returned and the API's are expecting response code **400**

**Comment by marvinhinz** [comment]
Is there a way to take a look inside the log files of the test suites?

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests, WebAPI Tests,Static Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @marvinhinz,

Thank you for your contribution!

The solution given is against the PSR-4 standard as we are returning the value in autoloader. Also because of the given solution many Functional, Integration, WebAPI tests are either failed or broken.

image

image

Do you want to propose any other solution for this issue. 

Thank you!

**Comment by engcom-Charlie** [comment]
On the basis of [above](https://github.com/magento/magento2/pull/34326#issuecomment-1076004841) findings and since we didn't got any reply on above [comment](https://github.com/magento/magento2/pull/34326#issuecomment-1076004841), closing this PR.

Please reopen and update if you wish to continue.

Thank you for your contribution!

**Comment by marvinhinz** [comment]
@engcom-Charlie breaking so many tests is indeed a problem, but the current state is also problematic. 
I just ran into this issue again in development, and its really bugging me :D 

In production env this is not even an issue, as these problems will be visible when running setup:di:compile. 
Only in development mode, the classes are lazily generated and thus we cannot detect the issue before the class is autoloaded. 

I understand that the proposed solution violates PSR-4. The only reason behind forbidding throwing exceptions is not to prevent other autoloaders that may exist. But when the Code Generator is responsible to load the requested class, which other autoloader will be able to succeed after the Code Generator failed? So i think in this case one should make an exception. 

Regarding the failing tests:  instead of throwing an exception, i will try to solve this by storing last generator exceptions somewhere so that they can be read in the App/ExceptionHandler::buildContentFromException() and add them as related exceptions.

**Pull request closed without merging**
