### PR TITLE
Updated wish list GraphQl read me file

### PR DESCRIPTION
**Pull request by chiranjeevi-cj**
### Description (*)

Update README.md file:

- wishlist graphql
- wishlist analytics
- wishlist
- widget
- weee graphql
- weee
- webapi security
- webapi async

### Fixed Issues (if relevant)

1. magento/devdocs magento/devdocs#4451: README content for modules - work in M2 Code

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by chiranjeevi-cj** [comment]
@magento run all tests

**Review by Stepa4man — APPROVED** [review]
Hi @chiranjeevi-cj 
Thanks for your contribution

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, thank you for the review.
[ENGCOM-8569](https://jira.corp.magento.com/browse/ENGCOM-8569) has been created to process this Pull Request
:eight_spoked_asterisk: @Stepa4man, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by chiranjeevi-cj** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento combine 31378 31384 31387 31388 31415 31417 31419

**Comment by magento-engcom-team** [comment]
Hi @sidolov. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
@chiranjeevi-cj all pull requests have been successfully combined together: 
 - merged https://github.com/magento/magento2/pull/31378: Updated wishlist analytics readme file
 - merged https://github.com/magento/magento2/pull/31384: Updated wishlist readme file
 - merged https://github.com/magento/magento2/pull/31387: Updated widget readme file
 - merged https://github.com/magento/magento2/pull/31388: Updated weee graphql module readme file
 - merged https://github.com/magento/magento2/pull/31415: Updated weee module readme file
 - merged https://github.com/magento/magento2/pull/31417: Updated webapi security module readme file
 - merged https://github.com/magento/magento2/pull/31419: Updated webapi async module readme file

**Review by engcom-Delta — CHANGES_REQUESTED** [review]
@chiranjeevi-cj please replace `http` to `https` in links

**Comment by chiranjeevi-cj** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Unit Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Unit Tests

**Comment by engcom-Hotel** [comment]
@magento run Unit Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Pull request merged**
