### PR TITLE
Update price index if product is added to website

### LINKED ISSUE #31069: [Issue] Update price index if product is added to website
This issue is automatically created based on existing pull request: magento/magento2#31067: Update price index if product is added to website

---------

### Description (*)
In the scenario of multiple websites, if a product is created and added to one website. It works properly, shows on frontend etc. In case the same product is added to another website via an API call, then the product won't be visible due to missing price index. It will either require to do full price index + cache clean to make the product visible or some additional change e.g. price, in order to be processed by price indexer. This PR adds an mview subscription to catalog_product_website table to inject the product id to catalog_product_price_cl and enable it to be processed by incremental indexer.

From admin interface adding product to another website works, as there is a choice of from which website to copy the data from (or use default values), but in case of API call, the product <> website relation is just inserted (it does actually update fulltext and catalog_category at the moment).

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)
1. Set indexers in scheduled mode
2. Create at least 2 websites with store views
3. Create a product in one of the websites, with sufficient data that it will be shown on frontend.
4. Fire an API call to **rest/V1/products/{sku}/websites**, adding the product created in step 1 to another website
5. Wait for next incremental indexer to process changes
6. Check that the product is not visible in the website it was assigned to, due to missing price in catalog_product_index_price for the corresponding website

### Contribution checklist (*)
 - [x ] Pull request has a meaningful description of its purpose
 - [x ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by siimm**
### Description (*)
In the scenario of multiple websites, if a product is created and added to one website. It works properly, shows on frontend etc. In case the same product is added to another website via an API call, then the product won't be visible due to missing price index. It will either require to do full price index + cache clean to make the product visible or some additional change e.g. price, in order to be processed by price indexer. This PR adds an mview subscription to catalog_product_website table to inject the product id to catalog_product_price_cl and enable it to be processed by incremental indexer.

From admin interface adding product to another website works, as there is a choice of from which website to copy the data from (or use default values), but in case of API call, the product <> website relation is just inserted (it does actually update fulltext and catalog_category at the moment).

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31069

### Manual testing scenarios (*)
1. Set indexers in scheduled mode
2. Create at least 2 websites with store views
3. Create a product in one of the websites, with sufficient data that it will be shown on frontend.
4. Fire an API call to **rest/V1/products/{sku}/websites**, adding the product created in step 1 to another website
5. Wait for next incremental indexer to process changes
6. Check that the product is not visible in the website it was assigned to, due to missing price in catalog_product_index_price for the corresponding website

### Contribution checklist (*)
 - [x ] Pull request has a meaningful description of its purpose
 - [x ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31069: Update price index if product is added to website

### CODE REVIEW

**Comment by siimm** [comment]
@magento create issue

**Comment by danielrussob** [comment]
@magento run all tests

**Comment by danielrussob** [comment]
@magento give me test instance

**Comment by danielrussob** [comment]
@magento give me 2.4-develop instance

**Comment by danielrussob** [comment]
We (cc: @aleron75) confirm that the issue is reproduced on vanilla Magento and is bug fixed by this patch

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @siimm, thanks for your contribution! Are you able to cover this scenario with automated tests? Maybe Integration tests will be suitable in this case, we can replace the API call with a direct call to the `ProductWebsiteLinkRepositoryInterface`. What do you think?

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by siimm** [comment]
@gabrieldagama I will try to come up with integration test for this

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE, Static Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
Hi @siimm I'll take care of test coverage.

**Review by danielrussob — CHANGES_REQUESTED** [review]
Hello @engcom-Charlie,
we are waiting for your test coverage, can you confirm?

**Comment by engcom-Charlie** [comment]
Hello @danielrussob, please take a look https://github.com/magento/magento2/issues/31069.
Thank you.

**Comment by engcom-Charlie** [comment]
Hi @siimm, I'm closing this PR since the issue mentioned here was closed.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
