### PR TITLE
comments & validation added in cookie configuration

### PR DESCRIPTION
**Pull request by ajithkumar-maragathavel**
### Description (*)

Go to Stores -> Settings -> Configuration -> General -> Web and expand Default Cookie Settings section.
1. Added comments to each field for a better understanding of the admin user.
2. Added number validation for cookie lifetime field to make sure it only accepts numbers.

### Manual testing scenarios (*)

1. Given string characters in the cookie lifetime field and verify number validation is working
2. Verify the comments are displayed under each field of the section.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @ajithkumar-maragathavel. Thank you for providing this change. I would kindly ask you to cover the validation process using an MFTF test. 

Please, follow the best practices for functional tests described [here](https://github.com/magento/magento-functional-tests-migration/wiki/Best-practices)

**Comment by ajithkumar-maragathavel** [comment]
@rogyar I will cover the changes with the MFTF test and will commit the changes and let you know.
Thanks for the review.

**Comment by ajithkumar-maragathavel** [comment]
@rogyar I have covered the validation using the MFTF test. Please review it and share your suggestions.

**Comment by rogyar** [comment]
Hi @ajithkumar-maragathavel. Thank you for covering the solution with MFTF test, great job! 

There's one more improvement that we can bring here. In the test, you've covered only the negative scenario (putting invalid value to the field). We may also introduce a positive scenario. So the steps will be the following:

- Go to settings, fill the field with an incorrect value
- Assert that the validation error is present
- Fill the field with the correct value
- Assert that there's no validation error.


Thank you!

**Comment by ajithkumar-maragathavel** [comment]
> Hi @ajithkumar-maragathavel. Thank you for covering the solution with MFTF test, great job!
> 
> There's one more improvement that we can bring here. In the test, you've covered only the negative scenario (putting invalid value to the field). We may also introduce a positive scenario. So the steps will be the following:
> 
>     * Go to settings, fill the field with an incorrect value
> 
>     * Assert that the validation error is present
> 
>     * Fill the field with the correct value
> 
>     * Assert that there's no validation error.
> 
> 
> Thank you!

@rogyar  Thanks for the review. I will also cover the positive scenario.
Just have one doubt. Please clarify me.

The assertion should be written as a separate action group. Right?

**Comment by ajithkumar-maragathavel** [comment]
@rogyar I have also covered the positive case scenario for the cookie lifetime save operation in Magento admin. Please review it.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7488](https://jira.corp.magento.com/browse/ENGCOM-7488) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:**
Screenshot from 2020-04-27 09-15-01

**After:**
Screenshot from 2020-04-27 09-21-03

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Pull request merged**
