### PR TITLE
Fix: Datepicker problem when using non en-US locale.

### PR DESCRIPTION
**Pull request by tao-s**
Current code convert date format "yyyy/MM/dd" to "YYYYYYYY/MM/DD".

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14627) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
@tao-s thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VladimirZaets** [comment]
Hi @tao-s  , please, sign CLA, otherwise, we can't process your pull request.

**Comment by tao-s** [comment]
Sorry, @VladimirZaets. I was late.
I signed to CLA. Please marge this PR.

**Comment by magento-engcom-team** [comment]
Hi @tao-s. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

**Pull request merged**
