### PR TITLE
MFTF: Enabling Email To Friend Functionality. Assert Options

### LINKED ISSUE #29145: [Issue] MFTF: Enabling Email To Friend Functionality. Assert Options
This issue is automatically created based on existing pull request: magento/magento2#29042: MFTF: Enabling Email To Friend Functionality. Assert Options

---------
**Preconditions:**
This PR with a test that Enables Email To A Friend Functionality in Admin Panel

**Steps to reproduce:**

1 - Login to admin
2 - Enable Email To A Friend Functionality
3 - Navigate to Stores->Configuration->Catalog->Email To A Friend
4 - Assert additional options

**Actual Result:**

**Expected Result:**

### PR DESCRIPTION
**Pull request by DmitryTsymbal**
**Description**
This PR with a test that Enables Email To A Friend Functionality in Admin Panel

**Steps To reproduce:**

1 - Login to admin
2 - Enable Email To A Friend Functionality
3 - Navigate to Stores->Configuration->Catalog->Email To A Friend
4 - Assert additional options

### Resolved issues:
1. [x] resolves magento/magento2#29145: MFTF: Enabling Email To Friend Functionality. Assert Options

### CODE REVIEW

**Comment by dmytro-ch** [comment]
@magento run all tests

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7804](https://jira.corp.magento.com/browse/ENGCOM-7804) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@magento run Functional Tests CE

**Review by slavvka — CHANGES_REQUESTED** [review]
@DmitryTsymbal Please fix the MFTF tests. They are failing since a couple of days ago there were introduced static checks for MFTF tests: 
```
Test AdminCatalogEmailToFriendSettingsTest is missing the required annotations: severity
Test AdminCreateCreditMemoWithZeroPriceCheckOrderStatusTest is missing the required annotations: stories, severity
```

**Comment by DmitryTsymbal** [comment]
Hello @slavvka , I have added missed severity annotation into _AdminCatalogEmailToFriendSettingsTest_ test.
Unfortunately I have not permissions to add the same into _AdminCreateCreditMemoWithZeroPriceCheckOrderStatusTest_
Thanks!

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Pull request merged**
