### PR TITLE
Prevent removal existing images while importing products by API

### PR DESCRIPTION
**Pull request by lpouwelse**
### Description (*)
Prevent removal existing images while importing products by API

### Fixed Issues (if relevant)
1. magento/magento2#10461: Updating a product through the API removes its images

### Manual testing scenarios (*)

1. Create a new product by the API
2. Link some images in the magento interface
3. Update product by rest API
4. Validate product images still exists

### Questions or comments
not applicable

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable) _not applicable_
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5759](https://jira.corp.magento.com/browse/ENGCOM-5759) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @lpouwelse 
Unfortunately, we are not able to reproduce the issue on fresh 2.3-develop instance providing by steps from PR. Maybe we missed something?

@lpouwelse Could you take a look, please?

Thanks!

**Comment by lpouwelse** [comment]
@magento-engcom-team upcoming two weeks i'm not able to take a look. Maybe the original author of the issue.

**Comment by sidolov** [comment]
@lpouwelse since we cannot reproduce the issue I'm closing the current pull request. 
If you find additional steps to reproduce the issue, please, feel free to re-open it and continue work. 
Thank you for the collaboration!

**Pull request closed without merging**
