### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by didactic-umbrella**
### Description

Reword readme

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios

N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16055) <br/>All committers have signed the CLA.

**Comment by didactic-umbrella** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella, here is your [Magento instance](https://pr-16055.engcom.dev.magento.com).
Admin access: [https://pr-16055.engcom.dev.magento.com/admin](https://pr-16055.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Please make sure you are PR **author** or **assignee** to access the instance.

**Pull request closed without merging**
