### PR TITLE
[MFTF] Refactoring AdminMassOrdersCancelProcessingAndClosedTest

### LINKED ISSUE #31517: [Issue] [MFTF] Refactoring AdminMassOrdersCancelProcessingAndClosedTest
This issue is automatically created based on existing pull request: magento/magento2#31507: [MFTF] Refactoring AdminMassOrdersCancelProcessingAndClosedTest

---------
### Description (*)
A new test has been created to improve execution time.
The old "AdminMassOrdersCancelProcessingAndClosedTest" has been deprecated.

### Manual testing scenarios (*)
1. Create two orders
2. Invoice the first order
3. Invoice and refund the second order
4. Go to the Orders Grid
5. Try to cancel both orders via mass update
6. Verify the result

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
A new test has been created to improve execution time.
The old "AdminMassOrdersCancelProcessingAndClosedTest" has been deprecated.

### Manual testing scenarios (*)
1. Create two orders
2. Invoice the first order
3. Invoice and refund the second order
4. Go to the Orders Grid
5. Try to cancel both orders via mass update
6. Verify the result

### Resolved issues:
1. [x] resolves magento/magento2#31517: [MFTF] Refactoring AdminMassOrdersCancelProcessingAndClosedTest

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Review by rogyar — APPROVED** [review]
The failing tests are not related to the current changeset.

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8670](https://jira.corp.magento.com/browse/ENGCOM-8670) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
