### PR TITLE
Fix overlap customer address edit text

### LINKED ISSUE #33357: Backend > Customers > Cannot edit an address when French language is selected
Magento ver. 2.4.1-p1
Commerce Cloud

### Steps to reproduce (*)

This bug occurs if French language is selected for the backend.

Backend > Customers > Select a customer > Addresses

Next to the Default billing address and Default Shipping address blocks, the "Edit" links cannot be selected because they overlap with the French translations of "Default billing addres" and "Default Shipping address" titles. Please see screen shot.

magento_BO

### Expected result (*)

Move "Edit" links so that they can be selected when French language is activated.

- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Fix overlap text when left title become long text!
Before (failed at long text)
long-text

After
after

after2

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33357

### Manual testing scenarios (*)

1. Go login to backend
2. Switch to locale with long expected text (ex: france) OR change translate english text length (Default billing address)
3. Go to customer
4. Edit addresses
5. See text visual Default shipping and Default billing address

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by Den4ik — APPROVED** [review]
✅ Approved
Looks good for me.
@mrtuvn Thanks for contribution

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run all tests

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9135](https://jira.corp.magento.com/browse/ENGCOM-9135) has been created to process this Pull Request

**Comment by eduard13** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Review by eduard13 — APPROVED** [review]

**Comment by engcom-Charlie** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Set admin Language to French from Admin Settings >> Interface Locale 


**Manual testing scenario:**

1.	Go to admin  Customers >> All customers >> Select customer(Edit)  >> Addresses
2.	Verify the default shipping address & Billing address, observed the Edit link should not overlapped

**Actual Result:** :heavy_check_mark:
 
1. Verified that Edit links are not overlapped with Default shipping address & Default Billing address text in French language and even if the text is longer.

**After:** :heavy_check_mark:  

image

image

**Before:** :heavy_multiplication_x: 

image

Admin Language setting:

image


**Tested all the manual scenarios, no impact on regression testing.**

**Pull request merged**
