### PR TITLE
#1829: Duplicated items in Asset filter on Entities grids

### LINKED ISSUE #1829: Duplicated items in Asset filter on Entities grids
### Description
Previously, there was an issue with Used In entities filter https://github.com/magento/adobe-stock-integration/issues/1618, now the same issue with the Asset filter on Entities grid

I have been using the _Magento 2.4.1-beta1_ instance

### Precondition (*)
1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. An image added to the content of Block or Product or Page.

### Steps to reproduce (*)
1. Go to **Content - Blocks**
2. Click **Filters**
3. Click on **Asset** filter
4. Place the cursor on the _Asset title_ field
5. Start typing the image title, previously added to Content 

### Actual result (*)
The found entities are duplicated
duplicated
duplicated1

### PR DESCRIPTION
**Pull request by joweecaquicla**
### Description (*)

This PR will introduce the fix to duplicated items in Asset filter on entities grids.

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/adobe-stock-integration/issues/1829

### Manual testing scenarios (*)

**Precondition:**

1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. An image added to the content of Block or Product or Page.

**Test steps:**

1. Go to Content - Blocks
2. Click Filters
3. Click on Asset filter
4. Place the cursor on the Asset title field
5. Start typing the image title, previously added to Content
6. Found entities/results must not be duplicated.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by joweecaquicla** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
The changed functionality is covered by functional tests. The change reduces the rate of requests for options ensuring the functionality works as expected for slower systems. I don't think any additional test coverage is needed

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-8188](https://jira.corp.magento.com/browse/ENGCOM-8188) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

Could not reproduce the _Duplicated items_ in Asset filter

Added a step in already existing scenario - https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/4951024

**Pull request merged**
