### PR TITLE
#38682 - Fix DeployPackage type error

### LINKED ISSUE #38682: [Issue] Static content deploy - Type error
### Preconditions and environment

- Magento version 2.4.7

### Steps to reproduce

1. Create an empty less file in your theme
2. Launch `setup:static-content:deploy --force`

### Expected result

The error "LESS file is empty" is displayed correctly

### Actual result

```
 Magento\Framework\Exception\LocalizedException::__construct(): Argument #1 ($phrase) must be of type Magento\Framework\Phrase, string given, called in /var/www/html/vendor/magento/module-deploy/Service/DeployPackage.php on line 142
```

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Nuranto**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#38682

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Nuranto** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
Hi @Nuranto,

Thanks for the collaboration & contribution!

:heavy_check_mark: QA Passed

**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Create an empty less file in your theme
- Launch setup:static-content:deploy --force

**Before:** :heavy_multiplication_x: 

Screenshot 2024-05-10 at 12 06 34



**After:** :heavy_check_mark:  

Screenshot 2024-05-10 at 12 14 47




Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
The functional EE failures in recent 2 builds are having 2 known issues and 1 inconsistent failure, considering it as flaky. Hence moving this PR to Merge in Progress

Known Failures having open JIRA:
1. StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest: [#6331](https://jira.corp.adobe.com/browse/ACQE-6331)
2. AdminReorderWithCatalogPriceRuleDiscountTest: [#6523](https://jira.corp.adobe.com/browse/ACQE-6523)

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38683/dc5808a2836126d886e7655b264676a1/Functional/allure-report-ee/index.html
image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38683/d699eb65cb68cff095dbf63af3fee8c7/Functional/allure-report-ee/index.html#categories
image

**Pull request merged**
