### PR TITLE
No short echo tag

### PR DESCRIPTION
**Pull request by MathiasReker**
Replace short-echo <?= with long format <?php echo syntax.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @MathiasReker. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
Hi @MathiasReker. Thank you for your collaboration. Could you provide more details for this change, please? The main question is what is wrong with short echo tags and why they should be replaced by the full echo tags? Also, the description is required part of every PR. Even a short explanation for a PR is very useful in most cases. 
Thanks.

**Comment by MathiasReker** [comment]
bad practice IMO. Have a look at this post: https://softwareengineering.stackexchange.com/questions/151661/is-it-bad-practice-to-use-tag-in-php

**Comment by MathiasReker** [comment]
Rebased.

**Comment by MathiasReker** [comment]
Rebased.

**Comment by orlangur** [comment]
@MathiasReker such change is incorrect, there is even a separate code sniff to enforce short tag used.

Even in the link from 2012 you mentioned I obtain "go ahead and use it" according to block scheme.

**Comment by ghost** [comment]
Hi @MathiasReker, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+magento2+20660), it will take less than a minute. </br>Your feedback will help us to improve contribution process.

**Pull request closed without merging**
