### PR TITLE
[MFTF] CreateOrderFromEditCustomerPageTest refactoring

### PR DESCRIPTION
**Pull request by AnnaAPak**
This PR is to refactor CreateOrderFromEditCustomerPageTest according to the best practices

Please, note: the test is dependent on https://github.com/magento/magento2/pull/34261

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Semantic Version Checker

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento Static Tests, Integration Tests, Unit Tests, WebAPI Tests

**Review by Den4ik — APPROVED** [review]
✅ Looks ok. Approve due to passed mftf tests.

Let's wait rerun of failed tests before move to "Merge In Progress"

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9339](https://jira.corp.magento.com/browse/ENGCOM-9339) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by Den4ik** [comment]
@magento run Static Tests, Integration Tests, Unit Tests, WebAPI Tests

**Comment by AnnaAPak** [comment]
@magento run all tests

**Comment by AnnaAPak** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE

**Comment by Den4ik** [comment]
@AnnaAPak Could you explain why did you update orderInGrid element selection? As I see it works ok with old element

**Comment by sidolov** [comment]
@AnnaAPak please, resolve merge conflicts

**Comment by engcom-Charlie** [comment]
Hi @AnnaAPak,

Thank you for your contribution!

I am looking into the merge conflicts.

Thank you.

**Comment by engcom-Charlie** [comment]
https://github.com/magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
I have merged 2.4-develop into this branch and resolved all the conflicts.

Below failed/broken test cases in the build failures are not part of PR changes or not failing because of any change made in PR. Hence moving this to Merge in Progress.

Failed test cases are: 
Functional CE: 
1. AdminLoginAsCustomerLoggingFilterTest.xml
2. AdminInvoiceCreatedForWholeOrderWithConfigurableProductTest.xml

Functional b2b:
1. StorefrontGuestBillingAddressPreselectedTest.xml ==> broken 



Thank you!

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests EE

**Pull request merged**
