### PR TITLE
[MFTF] Use ActionGroup for checking category save success message.

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

Add `AssertAdminCategorySaveSuccessMessageActionGroup` for checking success message after category was saved

### CODE REVIEW

**Review by lbajsarowicz — APPROVED** [review]
:heavy_check_mark: Nice catch. Thank you for your contribution.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7407](https://jira.corp.magento.com/browse/ENGCOM-7407) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by slavvka** [comment]
@magento run Functional Tests CE

**Pull request merged**
