### PR TITLE
#27500 Prepare ImportExport module Tests for PHPUnit 8

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Preparing PHPUnit Tests to run with PHPUnit 8.
PRs for each module is separated to make tests easier to merge.

### Fixed Issues (if relevant)
1. magento/magento2#27500

### Manual testing scenarios (*)
N/A

### Questions or comments
PR #27701 needs to be merged first (otherwise PHPUnit tests fail)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7403](https://jira.corp.magento.com/browse/ENGCOM-7403) has been created to process this Pull Request

**Comment by slavvka** [comment]
@magento run Unit Tests build

**Comment by slavvka** [comment]
@magento run Unit Tests

**Comment by slavvka** [comment]
```
21:17:12 PHP Fatal error:  Declaration of Magento\CatalogImportExport\Test\Unit\Model\Import\Product\Type\OptionTest::setUp() must be compatible with Magento\ImportExport\Test\Unit\Model\Import\AbstractImportTestCase::setUp(): void in /var/www/html/app/code/Magento/CatalogImportExport/Test/Unit/Model/Import/Product/Type/OptionTest.php on line 1073
```

**Review by slavvka — CHANGES_REQUESTED** [review]
```
06:32:09 PHP Fatal error:  Declaration of Magento\CatalogImportExport\Test\Unit\Model\Import\Product\Type\OptionTest::setUp() must be compatible with Magento\ImportExport\Test\Unit\Model\Import\AbstractImportTestCase::setUp(): void in /var/www/html/app/code/Magento/CatalogImportExport/Test/Unit/Model/Import/Product/Type/OptionTest.php on line 1073
```

**Comment by lbajsarowicz** [comment]
@magento run all tests

Actually we should have only 2 tests there
- Unit
- Static

But... somehow the rest also displays. So let's re-run them

**Comment by slavvka** [comment]
Stll
```
14:54:34 PHP Fatal error:  Declaration of Magento\CatalogImportExport\Test\Unit\Model\Import\ProductTest::setUp() must be compatible with Magento\ImportExport\Test\Unit\Model\Import\AbstractImportTestCase::setUp(): void in /var/www/html/app/code/Magento/CatalogImportExport/Test/Unit/Model/Import/ProductTest.php on line 1832
```

**Comment by slavvka** [comment]
```
15:39:06 PHP Fatal error:  Declaration of Magento\Banner\Test\Unit\Block\Adminhtml\Widget\Instance\Edit\Chooser\ContainerTest::setUp() must be compatible with Magento\Widget\Test\Unit\Block\Adminhtml\Widget\Instance\Edit\Chooser\AbstractContainerTest::setUp(): void in /var/www/html/app/code/Magento/Banner/Test/Unit/Block/Adminhtml/Widget/Instance/Edit/Chooser/ContainerTest.php on line 15
```

**Review by dmytro-ch — COMMENTED** [review]
I guess the latest error is not relevant to the current PR. I'll double-check it.

**Comment by slavvka** [comment]
> I guess the latest error is not relevant to the current PR. I'll double-check it.

@dmytro-ch Probably you are right. So we need to wait for Widget/Banners to be merged to make sure

**Comment by dmytro-ch** [comment]
However, there is another issue reproducible for me while testing with PHPUnit 8
```
1) Magento\ImportExport\Test\Unit\Helper\ReportTest::testGetExecutionTime
TypeError: DateTime::diff() expects parameter 2 to be boolean, null given

app/code/Magento/ImportExport/Helper/Report.php:56
app/code/Magento/ImportExport/Test/Unit/Helper/ReportTest.php:123
```

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
Stll issue with
```
14:54:34 PHP Fatal error:  Declaration of Magento\CatalogImportExport\Test\Unit\Model\Import\ProductTest::setUp() must be compatible with Magento\ImportExport\Test\Unit\Model\Import\AbstractImportTestCase::setUp(): void in /var/www/html/app/code/Magento/CatalogImportExport/Test/Unit/Model/Import/ProductTest.php on line 1832
```

Looks like `CatalogImportExport` module was never processed

**Comment by slavvka** [comment]
@magento run all tests

**Review by slavvka — APPROVED** [review]

**Pull request merged**
