### PR TITLE
issue/25771 : Fix wysiwyg image browser always calling php instead of…

### PR DESCRIPTION
**Pull request by PascalBrouwers**
… directy linking to thumbnail image file

### Description (*)

See: https://github.com/magento/magento2/issues/25771

### Fixed Issues (if relevant)

1. magento/magento2#25771: Backend wysiwyg image browser always calls php instead of loading directly the image file

### Manual testing scenarios (*)

1. Create a symlink to pub/media: `mkdir symlink && mv pub/media symlink && cd pub && ln -s ../symlink/media media`
2. Go to backend and open up a wysiwyg image browser and have a few images in there.
3. Note that all src to the image are in the format of admin/cms/wysiwyg_images/thumbnail/file/
4. Reload the image browser. By now all the images should have gotten a thumbnail.
5. Verify that src goes to the image directly instead of going to the php admin/cms/wysiwyg_images/thumbnail/file/ again.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by PascalBrouwers** [comment]
@melnikovi 1 line fix, should be easy to review ;)
The unpatched version of the code would result in `.thumbsyourimagename.jpg` which of course never exists.

**Review by ihor-sviziev — APPROVED** [review]
Hi @PascalBrouwers,
Could you resolve merge conflict?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @PascalBrouwers,
Could you resolve merge conflict?

**Comment by ihor-sviziev** [comment]
Hi @PascalBrouwers,
Original issue was already fixed in `2.4-develop` branch in  https://github.com/magento/magento2/commit/9a31aa2a0f5f238e1df601274d307308ac767659.

I'm closing this PR. Thank you for contribution!

**Pull request closed without merging**
