### PR TITLE
Remove Magento_ReleaseNotification module and cleanup all traces of it

### LINKED ISSUE #29363: Magento 2.4.0 release notification not showing up in backend
### Preconditions (*)
1. Magento 2.4.0 or 2.4.1 or 2.4.2 or 2.4.3 or 2.4.4 or 2.4.5 or 2.4.6 or 2.4.7 or ...

### Steps to reproduce (*)
1. Setup clean 2.4.0 or 2.4.1 or 2.4.2, ... installation, not a `2.4-develop` instance! (see reasoning below)
2. Login to backend (struggle your way through the whole 2FA process rigmarole)
3. Once finally logged in, seeing a notification at the bottom of the page:
```
We’ll try to show it again the next time you sign in to Magento Admin.
To learn more about new features, see our latest Release Notes in DevDocs' Release Information
```
4. Also notice the strange 'Next >' link in the footer
5. Logout in backend
6. Login to backend
7. Not seeing any release notifications popup

### Expected result (*)
1. Not being confused: if there are release notes for 2.4.0, show them, if there aren't, don't show that `We’ll try to show it again ...` message

### Actual result (*)
1. Being confused: is there a release notes popup for Magento 2.4.0? If yes, why isn't it showing up? If no, why is that message `We’ll try to show it again ...` showing up ...

### Additional information
https://github.com/magento/magento2/issues/29363#issuecomment-754913283

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by hostep**
### Description (*)
The release notification module has been broken since Magento 2.4.0 as explained over here: https://github.com/magento/magento2/issues/29363

Also after some more investigation, it still tries to fetch content from a remote endpoint on the magento.com domain that no longer seems to exist at the time of writing, for example: https://magento.com/release_notifications/2.2.4/community/en_us.json (I picked 2.2.4 because I know for sure that that release contained a release notification popup, as demonstrated in the second screenshot in https://github.com/magento/magento2/issues/29363#issuecomment-754913283)

So to me it sounds like this module won't be used anymore now and in the future.

Since this module was referenced in the `Magento_AdminAnalytics` module, I also removed all traces over there and had to rework a little bit of the css there to make the line height in the popup match with how it was before (since it referenced some css from the release notification module).

### Related Pull Requests

https://github.com/magento-gl/magento2-infrastructure/pull/16

### Fixed Issues (if relevant)
1. Fixes magento/magento2#29363

### Manual testing scenarios (*)
1. Since the removed module got referenced in the `Magento_AdminAnalytics` module, make sure that module still works properly
2. Easiest way to test is to temporarily modify the method `Magento\AdminAnalytics\Model\Condition\CanViewNotification::isVisible` and hardcode a `return true;` in its first line
3. After doing so, visit the dashboard in the backoffice and you should see a popup showing up, verify that it looks exactly like it looked before the removal of the ReleaseNotification module

### Questions or comments
Is this PR considered backwards compatible?
Or should we instead of completely removing the module, just hardcode it to never show up again in the backoffice, so we don't get that weird half-rendered popup anymore you see when visiting the backoffice for the first time on every single new release of Magento like shown in the first screenshot of https://github.com/magento/magento2/issues/29363#issuecomment-754913283 ?

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hostep** [comment]
@magento run all tests

**Comment by hostep** [comment]
The following static test failure will be resolved once https://github.com/magento/magento-coding-standard/pull/432 is finally approved and released:

```
FILE: /var/www/html/app/design/adminhtml/Magento/backend/Magento_AdminAnalytics/web/css/source/_module.less
-----------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------------------
 46 | WARNING | CSS class names should be separated with "-" (dash) instead of "_" (underscore)
-----------------------------------------------------------------------------------------------------------
```

I'm currently not going to try to fix other test failures, until it's clear if this PR will be approved as is, or if it needs to be reworked completely.

**Review by Den4ik — COMMENTED** [review]
@hostep I'm totally agree with you and also suggest to remove this module 👍 
PR looks good for me, but let's try to check it more detailed

**Review by fredden — APPROVED** [review]

**Review by fredden — APPROVED** [review]
The changes here look good to me. The automation is saying that there are problems preventing this from being merged / tested.

**Comment by hostep** [comment]
Rebased changes on latest 2.4-develop branch to solve the merge conflict with the composer.lock file (which will probably happen again in the future)

Got an agreement from the PO through @sidolov on Slack that the PR can be processed as-is and the entire module can be removed.
Internal devs will pick up the failing tests.

@magento run all tests

**Review by Den4ik — APPROVED** [review]

**Comment by sidolov** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
:heavy_check_mark: QA Passed 
**Preconditions:** - Latest Magento **2.4-develop** and **PHP 8.1** 
**Manual testing scenario:** 
1. Modified the method Magento\AdminAnalytics\Model\Condition\CanViewNotification::isVisible and hardcode a return true; in its first line
2. Visit Admin Dashboard and verify below text showing up for the 1st time login
**Before:** :heavy_multiplication_x:  
Below text is displayed in the footer section of Dashboard page with invalid non clickable "Next" link before applying PR changes.
image
image

**After:** :heavy_check_mark: 
No weird text / popup showing on the Dashboard page and footer section of Dashboard page with PR changes.
image
image
Builds are failed hence, moving this to extended testing.

**Comment by hostep** [comment]
@engcom-Charlie: just FYI, the failing static test about the underscore will be fixed once coding-standard version 32 is being released as it will contain [a fix](https://github.com/magento/magento-coding-standard/pull/432) for this false positive, so there is no need to put time into fixing that one.

**Comment by engcom-Charlie** [comment]
Hi @hostep,

Thank you for your contribution!

Thank you for the [information](https://github.com/magento/magento2/pull/36849#issuecomment-1463890561) about static test failure. 

I will have a look on the rest of the test failures and raise approval JIRA tickets for some of tests failures if needed proceed as per the process.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
@magento run Static Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by hostep** [comment]
@engcom-Charlie: can you please revert https://github.com/magento/magento2/pull/36849/commits/e6da6eded197e940375ac98718c8155468219827 again, I already explained twice now that we don't need it. It makes the code harder to read and it's a false positive in the static tests that will be fixed by an upcoming new version of the coding-standard library ...

Thanks for understanding!

/cc @sidolov

**Comment by engcom-Charlie** [comment]
Hi @hostep,

I have reverted the code base of e6da6ed revision.

As I have mentioned you, as a part of process we need successful builds in order to proceed a PR towards merge. Hence, I have created approval [JIRA](https://jira.corp.adobe.com/browse/AC-8306) for this false positive static test failure.

Thank you!

**Comment by fredden** [comment]
@magento run all tests

**Comment by hostep** [comment]
Rebased on latest `2.4-develop` branch, to make this PR clean again, without unnecessary commits.

Tests will still fail, and that's expected.

@magento run all tests

**Comment by hostep** [comment]
@magento run all tests

**Comment by hostep** [comment]
Rebased on latest 2.4-develop branch to fix merge conflicts caused by https://github.com/magento/magento2/commit/f87634afb1decf7558687da5760a0c6090db59fa#diff-671e339cfcad7f363cb9b85f3a31ad8d749246162f93a2ade2b746dc1f4b72e7

@magento run all tests

**Review by Den4ik — CHANGES_REQUESTED** [review]
@hostep Could you please verify static tests. They are related to changes

**Comment by fredden** [comment]
@Den4ik there are two errors that I can see in the Static Tests.

One is because Adobe Commerce ('B2B' & 'EE') still lists this module in its `composer.json` file. This is not something that we are able to fix and will need to be done by someone on Adobe staff (with access to the relevant repositories).

The other error is fixed by https://github.com/magento/magento-coding-standard/pull/432 which has been merged in, but no release has yet been created containing this fix.

**Comment by hostep** [comment]
@Den4ik: indeed, like Dan says, the test failures are expected. Please read through all comments if you want to know the whole story.
Could you please remove the "needs update" label again if possible? Thanks!

**Review by Den4ik — APPROVED** [review]

**Comment by engcom-Charlie** [comment]
It seems that bot have moved this PR to Ready for testing from Pending Approval hence moving it back.

Thank you!

**Comment by hostep** [comment]
Rebased on latest `2.4-develop` and fixed conflict in `composer.lock` file (which will most likely return if this PR stays open for another few months).

Coding standards 32 got released some weeks ago, which should already fix one failure in the static tests that no longer will trigger now. The others are still pending approval, maybe within 2 years we might be able to proceed here? Who knows ...

@magento run all tests

**Comment by hostep** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@engcom-Charlie, if I got right, we got the approval from PO, so we should change the status of this PR.
What is the status of all the linked internal issues/pull requests?

**Comment by engcom-Charlie** [comment]
Hi @ihor-sviziev,

As I have mentioned [above](https://github.com/magento/magento2/pull/36849#issuecomment-1708430251), we have got the approval on internal JIRA of "Static test failure".

On the rest 2 apporval JIRA's which are mentioned [here](https://github.com/magento/magento2/pull/36849#issuecomment-1471959713) we are still waiting for all the required approvals there. Hence We will be keeping this PR in the same status for now.

Thank you!

**Comment by ihor-sviziev** [comment]
@hostep it feels like in Magento the module was not removed, but instead - marked as deprecated
https://github.com/magento/magento2/commit/3ee3962f86f422cd45657a27823a360163afcb36

**Comment by engcom-Charlie** [comment]
As informed by Product Owner, Adobe Magento internal team will be taking care of this feature in future releases.

Magento will be first deprecating the modules and then will be removing it. Hence closing the PR now.

Thank you!

**Comment by hostep** [comment]
Thanks for the info @engcom-Charlie !

Can you make sure internal team is aware about dependenncy of the AdminAnalytics module on the ReleaseNotification module, so if they remove this module, they will need to fix AdminAnalytics module. Like I proposed in this PR.

**Pull request closed without merging**
