### PR TITLE
Fix eav form foreach error #21134

### PR DESCRIPTION
**Pull request by wojtekn**
### Description

PR adds missing initialization for two class variables which can be returned by class methods as parameters of type array. Without this initialization they are return as null what can result in throwing "Invalid argument supplied for foreach()" warning.

### Fixed Issues

1. magento/magento2#21134

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @wojtekn. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21135) <br/>All committers have signed the CLA.

**Comment by orlangur** [comment]
Ping @osrecio :)

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4583](https://jira.corp.magento.com/browse/ENGCOM-4583) has been created to process this Pull Request

**Comment by osrecio** [comment]
Sorry @orlangur I was very busy last week. Thanks for your support!

And of course thanks @wojtekn for your efforts and your patient. Very appreciate it.

**Comment by orlangur** [comment]
@osrecio no problem, this seemed abandoned to me since February. Please review PR as you originally picked it up :)

**Review by osrecio — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @osrecio, thank you for the review.
[ENGCOM-4583](https://jira.corp.magento.com/browse/ENGCOM-4583) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
