### PR TITLE
Fixing a test for Magento Newsletter.

### PR DESCRIPTION
**Pull request by tiagosampaio**
Fixing a test for Magento Newsletter.

### Description

The problem occurred because the constructor is being considered. By running the phpunit directly you can check this error out.

```
> php ./vendor/bin/phpunit -c ./dev/tests/unit/phpunit.xml.dist ./app/code/Magento/Newsletter
```

The tests will break.

```
1) Magento\Newsletter\Test\Unit\Model\ProblemTest::testAddSubscriberData
ArgumentCountError: Too few arguments to function Magento\Newsletter\Model\SubscriberFactory::__construct(), 0 passed in /Users/tiagosampaio/Sites/OpenSource/Magento2/vendor/phpunit/phpunit-mock-objects/src/Generator.php on line 216 and at least 1 expected

/Users/tiagosampaio/Sites/OpenSource/Magento2/generated/code/Magento/Newsletter/Model/SubscriberFactory.php:29
/Users/tiagosampaio/Sites/OpenSource/Magento2/app/code/Magento/Newsletter/Test/Unit/Model/ProblemTest.php:71

2) Magento\Newsletter\Test\Unit\Model\ProblemTest::testAddQueueData
ArgumentCountError: Too few arguments to function Magento\Newsletter\Model\SubscriberFactory::__construct(), 0 passed in /Users/tiagosampaio/Sites/OpenSource/Magento2/vendor/phpunit/phpunit-mock-objects/src/Generator.php on line 216 and at least 1 expected

/Users/tiagosampaio/Sites/OpenSource/Magento2/generated/code/Magento/Newsletter/Model/SubscriberFactory.php:29
/Users/tiagosampaio/Sites/OpenSource/Magento2/app/code/Magento/Newsletter/Test/Unit/Model/ProblemTest.php:71

3) Magento\Newsletter\Test\Unit\Model\ProblemTest::testAddErrorData
ArgumentCountError: Too few arguments to function Magento\Newsletter\Model\SubscriberFactory::__construct(), 0 passed in /Users/tiagosampaio/Sites/OpenSource/Magento2/vendor/phpunit/phpunit-mock-objects/src/Generator.php on line 216 and at least 1 expected

/Users/tiagosampaio/Sites/OpenSource/Magento2/generated/code/Magento/Newsletter/Model/SubscriberFactory.php:29
/Users/tiagosampaio/Sites/OpenSource/Magento2/app/code/Magento/Newsletter/Test/Unit/Model/ProblemTest.php:71

4) Magento\Newsletter\Test\Unit\Model\ProblemTest::testGetSubscriberWithNoSubscriberId
ArgumentCountError: Too few arguments to function Magento\Newsletter\Model\SubscriberFactory::__construct(), 0 passed in /Users/tiagosampaio/Sites/OpenSource/Magento2/vendor/phpunit/phpunit-mock-objects/src/Generator.php on line 216 and at least 1 expected

/Users/tiagosampaio/Sites/OpenSource/Magento2/generated/code/Magento/Newsletter/Model/SubscriberFactory.php:29
/Users/tiagosampaio/Sites/OpenSource/Magento2/app/code/Magento/Newsletter/Test/Unit/Model/ProblemTest.php:71

5) Magento\Newsletter\Test\Unit\Model\ProblemTest::testGetSubscriber
ArgumentCountError: Too few arguments to function Magento\Newsletter\Model\SubscriberFactory::__construct(), 0 passed in /Users/tiagosampaio/Sites/OpenSource/Magento2/vendor/phpunit/phpunit-mock-objects/src/Generator.php on line 216 and at least 1 expected

/Users/tiagosampaio/Sites/OpenSource/Magento2/generated/code/Magento/Newsletter/Model/SubscriberFactory.php:29
/Users/tiagosampaio/Sites/OpenSource/Magento2/app/code/Magento/Newsletter/Test/Unit/Model/ProblemTest.php:71

6) Magento\Newsletter\Test\Unit\Model\ProblemTest::testUnsubscribeWithNoSubscriber
ArgumentCountError: Too few arguments to function Magento\Newsletter\Model\SubscriberFactory::__construct(), 0 passed in /Users/tiagosampaio/Sites/OpenSource/Magento2/vendor/phpunit/phpunit-mock-objects/src/Generator.php on line 216 and at least 1 expected

/Users/tiagosampaio/Sites/OpenSource/Magento2/generated/code/Magento/Newsletter/Model/SubscriberFactory.php:29
/Users/tiagosampaio/Sites/OpenSource/Magento2/app/code/Magento/Newsletter/Test/Unit/Model/ProblemTest.php:71

7) Magento\Newsletter\Test\Unit\Model\ProblemTest::testUnsubscribe
ArgumentCountError: Too few arguments to function Magento\Newsletter\Model\SubscriberFactory::__construct(), 0 passed in /Users/tiagosampaio/Sites/OpenSource/Magento2/vendor/phpunit/phpunit-mock-objects/src/Generator.php on line 216 and at least 1 expected

/Users/tiagosampaio/Sites/OpenSource/Magento2/generated/code/Magento/Newsletter/Model/SubscriberFactory.php:29
/Users/tiagosampaio/Sites/OpenSource/Magento2/app/code/Magento/Newsletter/Test/Unit/Model/ProblemTest.php:71
```

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @tiagosampaio. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by rodrigowebjump — APPROVED** [review]
Hi @tiagosampaio Thanks for your contribution

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-3550](https://jira.corp.magento.com/browse/ENGCOM-3550) has been created to process this Pull Request

**Comment by tiagosampaio** [comment]
Hi @rodrigowebjump. Thank you for your review.

**Review by nuzil — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-3550](https://jira.corp.magento.com/browse/ENGCOM-3550) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @tiagosampaio. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.

**Comment by diazwatson** [comment]
Hey guys, how can I move this to Port to 2.3 Created column?

**Comment by sidolov** [comment]
Hi @diazwatson , please, create PR from your fork to the Magento repository and this port will move on the board automatically.

**Comment by diazwatson** [comment]
Hi @sidolov , I did it last 27 Nov, here is the link
https://github.com/diazwatson/magento2/pull/1

**Pull request merged**
