### PR TITLE
issue/24043: add better exception handling for cli commands

### PR DESCRIPTION
**Pull request by PascalBrouwers**
### Fixed Issues (if relevant)

1. magento/magento2#24043: Better exception handling during cli commands

### Manual testing scenarios (*)

1. Have a module with a wrong path in registration.php. For example set the path in vendor/magento/module-catalog/registration.php to __DIR__ . '/wrong_folder'
2. Run bin/magento setup:upgrade
3. See that it shows the actual exception (error with module registration)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @PascalBrouwers. Thank you for your contribution. Please, check the failing integration tests

**Comment by PascalBrouwers** [comment]
All failures in the tests have nothing to do with the changes in this PR.

**Comment by PascalBrouwers** [comment]
@rogyar All failures in the tests have nothing to do with the changes in this PR. So either fix the tests or ignore the messages.

**Comment by rogyar** [comment]
Hi @PascalBrouwers. Please, take a look at the following test https://testing-service.magento-community.engineering/reports/magento/magento2/pull/24044/411a2007-03b1-44f0-857d-48083f80b119/26357/Integration/allure-report-ce/index.html#suites/69ab40e7d96841d93275d46d2aeb2a4f/921cbff04d53dd04/
which have an assertion for the CLI output. Since we have expanded the information that is being shown once an error appeared, the assertion fails. 

Also, please note that in case if we have an exception upon invoking `parent::doRun`(https://github.com/magento/magento2/pull/24044/files#diff-4eb287b4e24c054a400e5f7b40dab0cbR105-R107), eventually the `$exitCode` will be undefined. However, we need a value since we use it for `return`.

**Comment by PascalBrouwers** [comment]
Ok, i'll make sure the variable exitCode is defined.

**Comment by PascalBrouwers** [comment]
Hmm, the static test is mentioning:
`array_merge(...) is used in a loop and is a | | resources greedy construction`
But I'm not using array_merge.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5621](https://jira.corp.magento.com/browse/ENGCOM-5621) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

**Before:**
after

**After:**

**Comment by PascalBrouwers** [comment]
Thank you! Filled in the survey. Took a few tries to be able to login though.

**Pull request merged**
