### PR TITLE
fix for the issue #26135

### LINKED ISSUE #26135: Sticky header for navigation in mobile, desktop
### Description (*)

Sticky header for mobile, desktop versions

### Expected behavior (*)

It will be easier for user to navigate the categories (using sticky menu) at any position in the page.

### Benefits

It is a smart navigation that fixes the menu to the top of screen as the user scrolls down a page.

### Additional information

It improves user experience

### PR DESCRIPTION
**Pull request by divyajyothi5321**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#26135 : Sticky header for navigation in mobile, desktop 

### Manual testing scenarios (*)

1. Go to any page in magento instance
2. Scroll the page to the footer
3. you can observe that the header is not sticky for both mobile and desktop.
4. With this fix the user is abled to access the header links directly from the footer section.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
Seem your PR already duplicated with PR https://github.com/magento/magento2/pull/26447

**Comment by mrtuvn** [comment]
@divyajyothi5321 Can you update file by move .lib-sticky-nav() to top right before background-color ?

**Comment by mrtuvn** [comment]
@magento run all tests

**Review by bgorski — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @bgorski, thank you for the review.
[ENGCOM-9078](https://jira.corp.magento.com/browse/ENGCOM-9078) has been created to process this Pull Request
:eight_spoked_asterisk: @bgorski, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by bgorski** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
i have also created PR for this but consideration duplication with this one (since owner inactive after 1 year)
See this https://github.com/magento/magento2/pull/28840

**Comment by bgorski** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by bgorski** [comment]
@divyajyothi5321 thank you for the contribution! The fix is extended in #28840 so I'm putting this one on hold since it's the extension that will get merged but it's great that you got the ball rolling with your great contribution, much appreciated!

**Comment by bgorski** [comment]
For the reason described above and because #28840 got accepted, this PR can now be closed.

**Pull request closed without merging**
