### PR TITLE
Solution for User role issue with customer group

### PR DESCRIPTION
**Pull request by ghost**
Solution for User role issue with customer group #16499
### Description

Now the “customer group” menu is displayed under "customers" menu on the admin side and store menu is invisible for new user. issue was is ACL file. 
In ACL file  'Customer group should be in 'Magento_Customer::customer' instead of 'Magento_Backend::stores_other_settings'.
### Fixed Issues (if relevant)

1. magento/magento2#16499:User role issue with customer group #16499

### Manual testing scenarios

1.System > Permission > User Roles.
2.Create a user role with 'customer group' permission which is specified in issue steps.
3. Login with new user credential. now only customer menu is enabled and store menu is not visible for new user.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16527) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=16527) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: emiprotech<br/>:x: Tejas<hr/>**Tejas** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by magento-engcom-team** [comment]
Hi @emiprotech. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by VladimirZaets** [comment]
Hi @Teja , please, sign CLA, otherwise, we can't process your pull request

**Comment by emiprotech** [comment]
@VladimirZaets , I have submitted from  'emipro' not from Tejas

**Comment by sidolov** [comment]
@emiprotech , @teja , I am closing this PR due to missing signed CLA.
Please reopen and update pull request if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
