### PR TITLE
fix: customer account create page does not work

### LINKED ISSUE #35490: [Issue] fix: customer account create page does not work
This issue is automatically created based on existing pull request: magento/magento2#35442: fix: customer account create page does not work

---------

### Description (*)

Fixes this exception which made the create account page unusable:

```
Exception: Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vendor/magento/module-customer/Block/Widget/Name.php on line 110 in /var/www/vendor/magento/framework/App/ErrorHandler.php:61
```

### Reproduction Steps
This is very easily reproducible by:

- Setting up a clean Magento 2.4.4
- In the backoffice, going to Stores > Configuration > Customers > Customer Configuration > Name and Address Options
- Configuring the following 2 fields:
- Show Prefix: Optional
- Prefix Dropdown Options: Mr;Mrs
- In frontend, going to the create account page
- You immediately get the error as mentioned in the opening post.

### Fixed Issues (if relevant)

none.

### Manual testing scenarios (*)

1. Open the create account page
2. It should work properly

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kolaente**
### Description (*)

Fixes this exception which made the create account page unusable:

```
Exception: Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vendor/magento/module-customer/Block/Widget/Name.php on line 110 in /var/www/vendor/magento/framework/App/ErrorHandler.php:61
```

### Fixed Issues (if relevant)

none.

### Manual testing scenarios (*)

1. Open the create account page
2. It should work properly

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#35490: fix: customer account create page does not work

### CODE REVIEW

**Comment by kolaente** [comment]
@magento run all tests

**Comment by kolaente** [comment]
@magento run Functional Tests CE Functional Tests B2B

**Comment by kolaente** [comment]
@magento run Functional Tests CE

**Comment by kolaente** [comment]
@magento run Functional Tests B2B

**Comment by sdzhepa** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
@magento create issue

**Comment by hostep** [comment]
Steps to reproduce has been added over here: https://github.com/magento/magento2/issues/35490#issuecomment-1133668222 (it would be appreciated if Adobe staff puts a little bit more effort in trying to understand what the proposed code change does so there is fewer time wasted with going back and forth over here on github)

**Comment by KrusLeung** [comment]
### Same question #35985 looking for solution 

**Preconditions and environment**
Magento 2.4.4 Open Source
PHP 8.1.9
Composer 2.1.0
-------
**Steps to reproduce**

1. Upgraded PHP version 7.4.3 to 8.1.9
2. Enabled PHP 8.1.9
3. Disabled PHP 7.4.3
4. Enter to [https:///www.worldtreemall.com](https://github.com/magento/magento2/issues/url)
5. Enter to Create an account
6. [https://www.worldtreemall.com/customer/account/create/](https://github.com/magento/magento2/issues/url) shows the Error.

-----
**Actual result**
```
1 exception(s):
Exception #0 (Exception): Deprecated Functionality: trim(): Passing null to parameter https://github.com/magento/magento2/issues/1 ($string) of type string is deprecated in /var/www/html/vendor/magento/module-customer/Block/Widget/Name.php on line 110

Exception #0 (Exception): Deprecated Functionality: trim(): Passing null to parameter https://github.com/magento/magento2/issues/1 ($string) of type string is deprecated in /var/www/html/vendor/magento/module-customer/Block/Widget/Name.php on line 110

#1 trim() called at [vendor/magento/module-customer/Block/Widget/Name.php:110]
#2 Magento\Customer\Block\Widget\Name->getPrefixOptions() called at [vendor/magento/module-customer/view/frontend/templates/widget/name.phtml:39]
#3 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:71]
#4 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/View/Element/Template.php:263]
#5 Magento\Framework\View\Element\Template->fetchView() called at [vendor/magento/framework/View/Element/Template.php:293]
#6 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1095]
#7 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1099]
#8 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:660]
#9 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/module-customer/view/frontend/templates/form/register.phtml:40]
#10 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:71]
#11 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/View/Element/Template.php:263]
#12 Magento\Framework\View\Element\Template->fetchView() called at [vendor/magento/framework/View/Element/Template.php:293]
#13 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1095]
#14 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1099]
#15 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:660]
#16 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:578]
#17 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:555]
#18 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#19 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#20 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#21 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#22 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#23 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#24 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#25 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#26 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#27 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#28 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#29 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#30 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#31 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#32 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#33 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#34 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#35 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#36 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#37 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:975]
#38 Magento\Framework\View\Layout->getOutput() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#39 Magento\Framework\View\Layout\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#40 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#41 Magento\Framework\View\Layout\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:41]
#42 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:260]
#43 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171]
#44 Magento\Framework\View\Result\Layout->renderResult() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#45 Magento\Framework\View\Result\Page\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#46 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#47 Magento\Framework\View\Result\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:23]
#48 Magento\Framework\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:120]
#49 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#50 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
```

**Comment by KrusLeung** [comment]
It didn't solve yet. Please help support team @magento-admin

**Comment by KrusLeung** [comment]
[#35542](https://github.com/magento/magento2/pull/35442) #35490 #35985 

Edited `app/code/Magento/Customer/Block/Widget/Name.php` as below:

From `$prefixOption = $this->getObject()->getPrefix();` to `$prefixOption = $this->getObject()->getPrefix() ?? '';`

-----
**After submited account creation**
Got this on https://www.example.com/customer/account/createpost/
```
ValueError: bcsub(): Argument #1 ($num1) is not well-formed in /var/www/html/vendor/magento/zendframework1/library/Zend/Locale/Math.php:259
Stack trace:
#0 /var/www/html/vendor/magento/zendframework1/library/Zend/Locale/Math.php(259): bcsub()
#1 /var/www/html/vendor/magento/zendframework1/library/Zend/Locale/Format.php(385): Zend_Locale_Math::Sub()
#2 /var/www/html/vendor/magento/zendframework1/library/Zend/Locale/Format.php(662): Zend_Locale_Format::toNumber()
#3 /var/www/html/vendor/magento/zendframework1/library/Zend/Filter/NormalizedToLocalized.php(106): Zend_Locale_Format::toFloat()
#4 /var/www/html/vendor/magento/framework/Data/Form/Filter/Date.php(69): Zend_Filter_NormalizedToLocalized->filter()
#5 /var/www/html/vendor/magento/module-customer/Model/Metadata/Form/AbstractData.php(197): Magento\Framework\Data\Form\Filter\Date->inputFilter()
#6 /var/www/html/vendor/magento/module-customer/Model/Metadata/Form/Date.php(20): Magento\Customer\Model\Metadata\Form\AbstractData->_applyInputFilter()
#7 /var/www/html/vendor/magento/module-customer/Model/Metadata/Form.php(244): Magento\Customer\Model\Metadata\Form\Date->extractValue()
#8 /var/www/html/generated/code/Magento/Customer/Model/Metadata/Form/Interceptor.php(23): Magento\Customer\Model\Metadata\Form->extractData()
#9 /var/www/html/vendor/magento/module-customer/Model/CustomerExtractor.php(84): Magento\Customer\Model\Metadata\Form\Interceptor->extractData()
#10 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Customer\Model\CustomerExtractor->extract()
#11 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Model\CustomerExtractor\Interceptor->___callParent()
#12 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Model\CustomerExtractor\Interceptor->Magento\Framework\Interception\{closure}()
#13 /var/www/html/generated/code/Magento/Customer/Model/CustomerExtractor/Interceptor.php(23): Magento\Customer\Model\CustomerExtractor\Interceptor->___callPlugins()
#14 /var/www/html/vendor/magento/module-customer/Controller/Account/CreatePost.php(368): Magento\Customer\Model\CustomerExtractor\Interceptor->extract()
#15 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Customer\Controller\Account\CreatePost->execute()
#16 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callParent()
#17 /var/www/html/vendor/magento/module-customer/Controller/Plugin/Account.php(64): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}()
#18 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Customer\Controller\Plugin\Account->aroundExecute()
#19 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}()
#20 /var/www/html/generated/code/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(23): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callPlugins()
#21 /var/www/html/vendor/magento/framework/App/Action/Action.php(111): Magento\Customer\Controller\Account\CreatePost\Interceptor->execute()
#22 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch()
#23 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callParent()
#24 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}()
#25 /var/www/html/generated/code/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(32): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callPlugins()
#26 /var/www/html/vendor/magento/framework/App/FrontController.php(245): Magento\Customer\Controller\Account\CreatePost\Interceptor->dispatch()
#27 /var/www/html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#28 /var/www/html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#29 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#30 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#31 /var/www/html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#32 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#33 /var/www/html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(75): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#34 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
#35 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#36 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#37 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#38 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#39 /var/www/html/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#40 {main}
```

**Comment by KrusLeung** [comment]
It didn't solve yet. Support team please help! Thank you @magento-admin

**Comment by KrusLeung** [comment]
> [#35542](https://github.com/magento/magento2/pull/35442) #35490 #35985
> 
> Edited `app/code/Magento/Customer/Block/Widget/Name.php` as below:
> 
> From `$prefixOption = $this->getObject()->getPrefix();` to `$prefixOption = $this->getObject()->getPrefix() ?? '';`
> 
> **After submited account creation** Got this on https://www.example.com/customer/account/createpost/
> 
> ```
> ValueError: bcsub(): Argument #1 ($num1) is not well-formed in /var/www/html/vendor/magento/zendframework1/library/Zend/Locale/Math.php:259
> Stack trace:
> #0 /var/www/html/vendor/magento/zendframework1/library/Zend/Locale/Math.php(259): bcsub()
> #1 /var/www/html/vendor/magento/zendframework1/library/Zend/Locale/Format.php(385): Zend_Locale_Math::Sub()
> #2 /var/www/html/vendor/magento/zendframework1/library/Zend/Locale/Format.php(662): Zend_Locale_Format::toNumber()
> #3 /var/www/html/vendor/magento/zendframework1/library/Zend/Filter/NormalizedToLocalized.php(106): Zend_Locale_Format::toFloat()
> #4 /var/www/html/vendor/magento/framework/Data/Form/Filter/Date.php(69): Zend_Filter_NormalizedToLocalized->filter()
> #5 /var/www/html/vendor/magento/module-customer/Model/Metadata/Form/AbstractData.php(197): Magento\Framework\Data\Form\Filter\Date->inputFilter()
> #6 /var/www/html/vendor/magento/module-customer/Model/Metadata/Form/Date.php(20): Magento\Customer\Model\Metadata\Form\AbstractData->_applyInputFilter()
> #7 /var/www/html/vendor/magento/module-customer/Model/Metadata/Form.php(244): Magento\Customer\Model\Metadata\Form\Date->extractValue()
> #8 /var/www/html/generated/code/Magento/Customer/Model/Metadata/Form/Interceptor.php(23): Magento\Customer\Model\Metadata\Form->extractData()
> #9 /var/www/html/vendor/magento/module-customer/Model/CustomerExtractor.php(84): Magento\Customer\Model\Metadata\Form\Interceptor->extractData()
> #10 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Customer\Model\CustomerExtractor->extract()
> #11 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Model\CustomerExtractor\Interceptor->___callParent()
> #12 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Model\CustomerExtractor\Interceptor->Magento\Framework\Interception\{closure}()
> #13 /var/www/html/generated/code/Magento/Customer/Model/CustomerExtractor/Interceptor.php(23): Magento\Customer\Model\CustomerExtractor\Interceptor->___callPlugins()
> #14 /var/www/html/vendor/magento/module-customer/Controller/Account/CreatePost.php(368): Magento\Customer\Model\CustomerExtractor\Interceptor->extract()
> #15 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Customer\Controller\Account\CreatePost->execute()
> #16 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callParent()
> #17 /var/www/html/vendor/magento/module-customer/Controller/Plugin/Account.php(64): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}()
> #18 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Customer\Controller\Plugin\Account->aroundExecute()
> #19 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}()
> #20 /var/www/html/generated/code/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(23): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callPlugins()
> #21 /var/www/html/vendor/magento/framework/App/Action/Action.php(111): Magento\Customer\Controller\Account\CreatePost\Interceptor->execute()
> #22 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch()
> #23 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callParent()
> #24 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}()
> #25 /var/www/html/generated/code/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(32): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callPlugins()
> #26 /var/www/html/vendor/magento/framework/App/FrontController.php(245): Magento\Customer\Controller\Account\CreatePost\Interceptor->dispatch()
> #27 /var/www/html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
> #28 /var/www/html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
> #29 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
> #30 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
> #31 /var/www/html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
> #32 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
> #33 /var/www/html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(75): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
> #34 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
> #35 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
> #36 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
> #37 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
> #38 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
> #39 /var/www/html/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
> #40 {main}
> ```

This seems to be an issue with me not running bin/magento set:upgrade or bin/magento setup:static-content:deploy -f or bin/magento s:d:c only

**Comment by KrusLeung** [comment]
> [#35542](https://github.com/magento/magento2/pull/35442) #35490 #35985
> 
> Edited `app/code/Magento/Customer/Block/Widget/Name.php` as below:
> 
> From `$prefixOption = $this->getObject()->getPrefix();` to `$prefixOption = $this->getObject()->getPrefix() ?? '';`
> 
> **After submited account creation** Got this on https://www.example.com/customer/account/createpost/
> 
> ```
> ValueError: bcsub(): Argument #1 ($num1) is not well-formed in /var/www/html/vendor/magento/zendframework1/library/Zend/Locale/Math.php:259
> Stack trace:
> #0 /var/www/html/vendor/magento/zendframework1/library/Zend/Locale/Math.php(259): bcsub()
> #1 /var/www/html/vendor/magento/zendframework1/library/Zend/Locale/Format.php(385): Zend_Locale_Math::Sub()
> #2 /var/www/html/vendor/magento/zendframework1/library/Zend/Locale/Format.php(662): Zend_Locale_Format::toNumber()
> #3 /var/www/html/vendor/magento/zendframework1/library/Zend/Filter/NormalizedToLocalized.php(106): Zend_Locale_Format::toFloat()
> #4 /var/www/html/vendor/magento/framework/Data/Form/Filter/Date.php(69): Zend_Filter_NormalizedToLocalized->filter()
> #5 /var/www/html/vendor/magento/module-customer/Model/Metadata/Form/AbstractData.php(197): Magento\Framework\Data\Form\Filter\Date->inputFilter()
> #6 /var/www/html/vendor/magento/module-customer/Model/Metadata/Form/Date.php(20): Magento\Customer\Model\Metadata\Form\AbstractData->_applyInputFilter()
> #7 /var/www/html/vendor/magento/module-customer/Model/Metadata/Form.php(244): Magento\Customer\Model\Metadata\Form\Date->extractValue()
> #8 /var/www/html/generated/code/Magento/Customer/Model/Metadata/Form/Interceptor.php(23): Magento\Customer\Model\Metadata\Form->extractData()
> #9 /var/www/html/vendor/magento/module-customer/Model/CustomerExtractor.php(84): Magento\Customer\Model\Metadata\Form\Interceptor->extractData()
> #10 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Customer\Model\CustomerExtractor->extract()
> #11 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Model\CustomerExtractor\Interceptor->___callParent()
> #12 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Model\CustomerExtractor\Interceptor->Magento\Framework\Interception\{closure}()
> #13 /var/www/html/generated/code/Magento/Customer/Model/CustomerExtractor/Interceptor.php(23): Magento\Customer\Model\CustomerExtractor\Interceptor->___callPlugins()
> #14 /var/www/html/vendor/magento/module-customer/Controller/Account/CreatePost.php(368): Magento\Customer\Model\CustomerExtractor\Interceptor->extract()
> #15 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Customer\Controller\Account\CreatePost->execute()
> #16 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callParent()
> #17 /var/www/html/vendor/magento/module-customer/Controller/Plugin/Account.php(64): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}()
> #18 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Customer\Controller\Plugin\Account->aroundExecute()
> #19 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}()
> #20 /var/www/html/generated/code/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(23): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callPlugins()
> #21 /var/www/html/vendor/magento/framework/App/Action/Action.php(111): Magento\Customer\Controller\Account\CreatePost\Interceptor->execute()
> #22 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch()
> #23 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callParent()
> #24 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Account\CreatePost\Interceptor->Magento\Framework\Interception\{closure}()
> #25 /var/www/html/generated/code/Magento/Customer/Controller/Account/CreatePost/Interceptor.php(32): Magento\Customer\Controller\Account\CreatePost\Interceptor->___callPlugins()
> #26 /var/www/html/vendor/magento/framework/App/FrontController.php(245): Magento\Customer\Controller\Account\CreatePost\Interceptor->dispatch()
> #27 /var/www/html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
> #28 /var/www/html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
> #29 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
> #30 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
> #31 /var/www/html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
> #32 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
> #33 /var/www/html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(75): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
> #34 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
> #35 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
> #36 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
> #37 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
> #38 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
> #39 /var/www/html/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
> #40 {main}
> ```

This seems to be an issue with me not running bin/magento set:upgrade or bin/magento setup:static-content:deploy -f or bin/magento s:d:c only

**Pull request closed without merging**
