### PR TITLE
Swagger get store information gives error #13143

### PR DESCRIPTION
**Pull request by XxXgeoXxX**
### Description (*)
Base issue https://github.com/magento/magento2/issues/13143

Steps to reproduce
Go to Swagger
open storeStoreConfigManagerV1
Method GET /V1/store/storeConfigs
Add Items: `default` and `test`

Or
http://yourdomain.com/rest/V1/store/storeConfigs?storeCodes[]=default&storeCodes[]=test

### Comments
This fix looks like and quick and resolved only this one request. I have checked other web-api calls and they use another structure(for example `searchCriteria` or used only simple types). 
I propose to create a ticket and get approval in architecture Magento git repository for totally rebuild `storeConfigs` query.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by nuzil** [comment]
I guess we have to change Servic contracts for store configs. Lets me deep dive here and maybe we can find a good way

**Comment by nuzil** [comment]
Btw looks like similar, I will review
https://github.com/magento/magento2/pull/27529

**Comment by XxXgeoXxX** [comment]
Hi
@nuzil 
I have checked related PR, but for me(branch 2.4-develop), it doesn't resolve the problem
I analyzed deeper and find that you need to enter access token to call storeConfigs method. That means the provided link couldn't be shared without access(private data). That's why I based my solution on titier-prices-information query. I reverted my previous changes and change GET method to POST. After that swagger correctly handles that.

**Comment by nuzil** [comment]
Hi @XxXgeoXxX 
Unfortunatelly change GET to POST is not a solution for us.
POST methods have to be used for posting data, in our cause it will lead to misusage of POST method. GET data have to stay GET method.

Solution provided in another PR works for me also (I technically first fix it myself and them compared solutions). 
I asked also guy to apply tests for we could correctly test such cases.

If there are still some issues you have, please share them, we will try to find a solution.

I'm closing it for now. Thanks a lot for your time!!

**Pull request closed without merging**
