### PR TITLE
Fix for PHP_CodeSniffer error after app:config:dump

### PR DESCRIPTION
**Pull request by dng-dev**
### Description (*)
After app:config:dump in our CI environment phpcs complains about uppercase constant for "null"
(Generic.PHP.LowerCaseConstant.Found) TRUE, FALSE and NULL must be lowercase; expected "null" but  found "NULL" (Generic.PHP.LowerCaseConstant.Found)

The source of this uppercase constant can be found in the [php source].(https://github.com/php/php-src/blob/master/ext/standard/var.c#L486)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. install magento2
2. excute app:config:dump

### Contribution checklist (*)
 - [x ] Pull request has a meaningful description of its purpose
 - [x ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23787) <br/>All committers have signed the CLA.

**Comment by rogyar** [comment]
Ideally, you should exclude the config file from static code analysis. But in case if your infrastructure strictly requires checking all incoming PHP files it might be a good catch.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-5474](https://jira.corp.magento.com/browse/ENGCOM-5474) has been created to process this Pull Request
:eight_spoked_asterisk: @rogyar, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@dng-dev thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by dng-dev** [comment]
@rogyar are the checks hanging?

**Comment by rogyar** [comment]
Hi @dng-dev. The tests will be executed internally once again, so no worries.

**Pull request merged**
