### PR TITLE
[MFTF] Updating with OpenEditProductOnBackendActionGroup

### LINKED ISSUE #31249: [Issue] [MFTF] Updating with OpenEditProductOnBackendActionGroup
This issue is automatically created based on existing pull request: magento/magento2#31243: [MFTF] Updating with OpenEditProductOnBackendActionGroup

---------
### Description (*)
Utilizing AssertAdminProductIsAssignedToCategoryActionGroup instead of filtering Products Grid by SKU and clicking the first row (in order to decrease test execution time)

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
Utilizing AssertAdminProductIsAssignedToCategoryActionGroup instead of filtering Products Grid by SKU and clicking the first row (in order to decrease test execution time)

### Resolved issues:
1. [x] resolves magento/magento2#31249: [MFTF] Updating with OpenEditProductOnBackendActionGroup

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8535](https://jira.corp.magento.com/browse/ENGCOM-8535) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** Functional Tests CE  and Functional Tests EE are failed

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Pull request merged**
