### PR TITLE
Fix wording of downloadable Products

### PR DESCRIPTION
**Pull request by bh-ref**

### CODE REVIEW

**Comment by bh-ref** [comment]
see also https://github.com/magento/magento2/pull/2775

**Comment by KrystynaKabannyk** [comment]
hello @bh-ref , can you please update code and cover it by Travis tests?

**Comment by bh-ref** [comment]
@KrystynaKabannyk  unfortunately, I do not know how to write the needed Travis tests or even where to put them. But feel free to reject this pull request and maybe solve it another way.

**Comment by KrystynaKabannyk** [comment]
@bh-ref, sorry for the confusion, I meant that you should cover the code by automated tests and have a green run on Travis.

**Comment by vkublytskyi** [comment]
@bh-ref, as provided fix couldn't be a reason of errors appeared in Travis log please try to just rerun tests.

**Comment by bh-ref** [comment]
created #4149 to combine/update #2776 #2775

**Pull request closed without merging**
