### PR TITLE
Fixed typo in unit test introduced by accident in e0c61dee13afcd10c03…

### LINKED ISSUE #37792: [Issue] Fixed typo in unit test introduced by accident in e0c61dee13afcd10c03…
This issue is automatically created based on existing pull request: magento/magento2#37785: Fixed typo in unit test introduced by accident in e0c61dee13afcd10c03…

---------
…3803e344a22df10631eeb

### Description (*)
Accidentally found by running phpstan on level 0 on the entire codebase. `$this->attribute§('getIsUnique')` is not really proper code.

It looks like this mistake was accidentally introduced in https://github.com/magento/magento2/commit/e0c61dee13afcd10c033803e344a22df10631eeb#diff-220a7a1cb2d4bae1236aeeb318f8ae5368fb92017598c1db77fba6754d2cf9fa

I've also marked the test to no longer being skipped, it seems to run without any issues after this fix. I have no idea what is being mentioned in MAGETWO-48956?

### Manual testing scenarios (*)
1. Run `vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist app/code/Magento/Catalog/Test/Unit/Model/Category/Attribute/Backend/SortbyTest.php` and make sure it doesn't output errors

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by hostep**
…3803e344a22df10631eeb

### Description (*)
Accidentally found by running phpstan on level 0 on the entire codebase. `$this->attribute§('getIsUnique')` is not really proper code.

It looks like this mistake was accidentally introduced in https://github.com/magento/magento2/commit/e0c61dee13afcd10c033803e344a22df10631eeb#diff-220a7a1cb2d4bae1236aeeb318f8ae5368fb92017598c1db77fba6754d2cf9fa

I've also marked the test to no longer being skipped, it seems to run without any issues after this fix. I have no idea what is being mentioned in MAGETWO-48956?

### Manual testing scenarios (*)
1. Run `vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist app/code/Magento/Catalog/Test/Unit/Model/Category/Attribute/Backend/SortbyTest.php` and make sure it doesn't output errors

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37792: Fixed typo in unit test introduced by accident in e0c61dee13afcd10c03…

### CODE REVIEW

**Comment by hostep** [comment]
@magento run all tests

**Comment by hostep** [comment]
@magento run all tests

**Comment by hostep** [comment]
Failed tests look not related to changes here.

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests look not related to changes from this PR.

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**
- Run `vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist app/code/Magento/Catalog/Test/Unit/Model/Category/Attribute/Backend/SortbyTest.php and make sure it doesn't output errors`

**Before:** :heavy_multiplication_x: Unit test cases getting skipped.
Screenshot 2023-07-24 at 7 27 42 PM



**After:** :heavy_check_mark:  Now working fine.
Screenshot 2023-07-24 at 7 27 50 PM


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by hostep** [comment]
Thanks @engcom-Lima!

Can you take a look at jira ticket MAGETWO-48956, to see what it mentions and why this test was skipped because of it?
We can't see inside your jira system, so I have no idea what it is about.

Thanks!

**Comment by engcom-Lima** [comment]
Hi @hostep ,

Thanks for your contribution and collaboration.

I have checked the **MAGETWO-48956** Jira ticket, for some reason, the team had skipped the unit test but forget to unskip it later.

Thanks

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by hostep** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Unit Tests,Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Unit Tests,Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Unit Tests,Functional Tests B2B

**Comment by engcom-Echo** [comment]
Functional Tests B2B failures are different on last two run on same commit.
Run1
Screenshot 2023-09-06 at 2 50 10 PM

Run2
Screenshot 2023-09-06 at 2 50 14 PM

Hence moving to `merge in progress`.

**Pull request merged**
