### PR TITLE
Fixed Issue #25254:Validation issue for configuable product in cart

### LINKED ISSUE #25254: Validation issue for configuable product  in cart
There is no proper validation for configurable product in cart. If we add configurable product in cart and then remove associated product from configurable product in admin then there is no error on cart page and guest/customer is able to place order.

### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Create a configurable product. Here i am creating configurable product using color attribute with Maroon, Black and Green variation.
2. Add configurable product in cart with variation color Maroon.
3. Go to admin and remove Maroon color variation from configurable product.
4. Now go to cart page

### Expected result (*)

1. There should be error on cart page like variation does not exist

### Actual result (*)

1. There is no error on cart page and customer/guest is able to place order with added variation. But that variation does not exist.

### PR DESCRIPTION
**Pull request by ghost**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#25254:Validation issue for configuable product in cart

### Manual testing scenarios (*)

1. Create a configurable product. Here i am creating configurable product using color attribute with Maroon, Black and Green variation.
2. Add configurable product in cart with variation color Maroon.
3. Go to admin and remove Maroon color variation from configurable product.
4. Now go to cart page

Now there will be error on cart page and checkout page.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by aleron75** [comment]
Hello @rahulwebkul, thank you for your contribution!

Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. 

For this specific case, you should cover your fix by automated tests with the scenario which leads to an issue: tests should fail on the mainline and pass with your fix.

Thanks again!

**Comment by ghost** [comment]
@aleron75 - Thanks for you feedback. I need to write UNIT Test right? Or do i need to write any other test case?
Let me know your comments on it.

**Comment by ghost** [comment]
> @aleron75 - Thanks for you feedback. I need to write UNIT Test right? Or do i need to write any other test case?
> Let me know your comments on it.

@aleron75 - Any update over it?

**Comment by aleron75** [comment]
>I need to write UNIT Test right?

yes, as the guidelines says, _"pick the most lightweight (execution time wise) test type that will provide sufficient coverage"_

if you think a unit test can provide sufficient coverage for your case, go with it

**Comment by aleron75** [comment]
Hello @rahulwebkul, will you be able to proceed with the PR, providing tests?
Let me know,
thanks!

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @rahulwebkul. Thanks for collaboration. Due to Magento DOD, all PRs should be covered by automated tests. Please cover your changes by automated tests

**Comment by VladimirZaets** [comment]
@rahulwebkul , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Pull request closed without merging**
