### PR TITLE
phpDocumentor Return tag must be an int

### PR DESCRIPTION
**Pull request by reindert-vetter**
Because count() gives an int, hasShipment returns an int. Now i can't do this:
```if ($view->getOrder()->hasShipments() === true) {```

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=10760) <br/>All committers have signed the CLA.

**Comment by orlangur** [comment]
@reindert-vetter code like 
`if ($view->getOrder()->hasShipments() === true) {`
should be always written as
`if ($view->getOrder()->hasShipments()) {`
actually.

I do agree that current implementation of the method could be a bit confusing but I believe we should not change contract here but just change implementation.

Please change all `has*` methods in this class so that they always return boolean value if you wish:
```
public function hasShipments()
    {
        return (bool)$this->getShipmentsCollection()->count();
    }
```
To match implementation with PHPDoc correctly.

**Comment by reindert-vetter** [comment]
Done

**Comment by orlangur** [comment]
Great, thanks for the quick change!

**Review by orlangur — APPROVED** [review]

**Pull request merged**
