### PR TITLE
Spelling Mistake in Setup > Patch

### PR DESCRIPTION
**Pull request by sudhanshu-bajaj**
### Description (*)

Spelling mistake in Patch 
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4758](https://jira.corp.magento.com/browse/ENGCOM-4758) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@sudhanshu-bajaj thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by sudhanshu-bajaj** [comment]
@orlangur Any idea why this failed "The Travis CI build failed" ?

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-4765](https://jira.corp.magento.com/browse/ENGCOM-4765) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
**Notice:** QA not applicable

**Pull request merged**
