### PR TITLE
[MFTF] Add StorefrontCheckoutClickSaveAddressButtonActionGroup

### LINKED ISSUE #30916: [Issue] [MFTF] Add StorefrontCheckoutClickSaveAddressButtonActionGroup
This issue is automatically created based on existing pull request: magento/magento2#30528: [MFTF] Add StorefrontCheckoutClickSaveAddressButtonActionGroup

---------
This PR add `StorefrontCheckoutClickSaveAddressButtonActionGroup`

### PR DESCRIPTION
**Pull request by Usik2203**
This PR add `StorefrontCheckoutClickSaveAddressButtonActionGroup`

### Resolved issues:
1. [x] resolves magento/magento2#30916: [MFTF] Add StorefrontCheckoutClickSaveAddressButtonActionGroup

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by rogyar** [comment]
Hi @Usik2203. Thanks for the refactoring. Good job! Since your edits contain backward-incompatible changes, the best way is to wait for 2.5-develop branch. I'm putting this on hold for now.

Thanks.

**Comment by rogyar** [comment]
Hi @Usik2203. Please, refer to my comment that explains a workaround for removing old steps and preserving BC

https://github.com/magento/magento2/pull/30223#discussion_r508492932

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
Hi @rogyar
I have applied your recommendations
Seems failed test are not related with my changes.
Thanks

**Comment by rogyar** [comment]
Hi @Usik2203. Please, make sure you've adjusted this PR according to the following comment 

https://github.com/magento/magento2/pull/30525#discussion_r515237925

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
Hi @rogyar
I have applied your recommendations
Thanks :)

**Comment by rogyar** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by rogyar** [comment]
@magento run Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Review by rogyar — APPROVED** [review]
The failing tests do not seem to be related to the current PR

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8454](https://jira.corp.magento.com/browse/ENGCOM-8454) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento create issue

**Pull request merged**
