### PR TITLE
Issue #10207. Avoiding duplicates in validator's messages

### PR DESCRIPTION
**Pull request by akolpakovgor**
### Description

The current message merging process with built-in function _array_merge_recursive_ does not handle duplicates, that produces issues described in the original issue. Proposed fix ignores duplicate messages, but provides compatible with _array_merge_recursive_ result.

### Fixed Issues (if relevant)

1. magento/magento2#10207: Magento\Framework\Model\AbstractModel::validateBeforeSave error notice (Array to string conversion)

### Manual testing scenarios (*)

1. Programmatically save a quote with an invalid email address.
2. Catch the error, try another save of the quote with an still invalid email address.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22316) <br/>All committers have signed the CLA.

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-4748](https://jira.corp.magento.com/browse/ENGCOM-4748) has been created to process this Pull Request

**Comment by akolpakovgor** [comment]
work in progress

**Review by sivaschenko — CHANGES_REQUESTED** [review]
@akolpakovgor thanks for the pull request! Can you please fix the failed unit tests - see the Travis tests result

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @akolpakovgor thanks for the updates and test coverage!

As I can see the messages array is still multidimentional after the change, so the issue that this PR is intended to fix appears to be still actual with the current change.

Can you please provide more information on why have you decided to change the approach and do not use the `array_merge` as in the initial commit?

**Comment by akolpakovgor** [comment]
Hi @sivaschenko,
the blocker of adding `array_merge` is test lib/internal/Magento/Framework/Validator/Test/Unit/ConfigTest.php, that explicitly expects multidimensional array:
https://github.com/magento/magento2/blob/45a636521193c97a203fa8213d5503e5879015dc/lib/internal/Magento/Framework/Validator/Test/Unit/ConfigTest.php#L196-L201
Changing this test could break backward compatibility, so I've decided to filter duplicates, but keep the current array structure.
Talking about issue itself, I think, that filtering duplicates should resolve described case, as `$_messages` array will be one-dimensional. Processing and displaying multidimensional validation result sounds like a separate scope.
Let me know, what do you think.

**Comment by sivaschenko** [comment]
@akolpakovgor in case you'd like to keep multidimentional array of errors - the client code has to be adjusted to handle that array correctly

**Comment by sivaschenko** [comment]
@akolpakovgor are you still working on this PR? The code changes do not seem correct at the moment

**Comment by sivaschenko** [comment]
Closing due to inactivity. Feel free to reopen if you'd like to continue progress on this pull request

**Pull request closed without merging**
