### PR TITLE
Use correct ScopeId in StockRegistry

### PR DESCRIPTION
**Pull request by marcusirgens**
### Description (*)
For some reason, scopeId is overwritten in `Magento\CatalogInventory\Model\StockRegistry`. This allows passing custom values.

### Fixed Issues (if relevant)

1. magento/magento2#22872: \Magento\CatalogInventory\Model\StockRegistry $scopeId parameter value immediately overwritten

### Manual testing scenarios (*)
Not necessary, covered by unit tests

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23231) <br/>All committers have signed the CLA.

**Comment by orlangur** [comment]
@marcusirgens,

> Manual testing scenarios (*)
> Not necessary, covered by unit tests

This is never true when we talk about customer-facing scenarios.

**Review by orlangur — CHANGES_REQUESTED** [review]
@marcusirgens looks like we need to get default value in some cases: https://github.com/magento/magento2/commit/68ce404b7a5dcb781232e8e40a8efebd01503e35#diff-9d0a7a3e82a3b046e54a204adc7474ab

@naydav @AVoskoboinikov can you provide some insight on this change?

**Comment by marcusirgens** [comment]
With the provided method signature in the interface, it feels like the methods should either accept a scopeId or use the default, so discarding the value is definitely wrong.

**Comment by orlangur** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@marcusirgens a lot of tests are failed with provided changes, could you please take a look?

**Comment by lenaorobei** [comment]
@marcusirgens are you still up to working on this PR?
I merged latest `2.4-develop` to your branch.

**Comment by marcusirgens** [comment]
I'll take a look at it this weekend @lenaorobei

**Comment by lenaorobei** [comment]
Closing this PR due to inactivity. Please feel free to reopen if you are going to continue working on it.
Thank you.

**Pull request closed without merging**
