### PR TITLE
Selecting Existing Address in Admin Order

### LINKED ISSUE #32906: [Issue] Selecting Existing Address in Admin Order
This issue is automatically created based on existing pull request: magento/magento2#32783: Selecting Existing Address in Admin Order

---------
### Description
Selecting an existing address while creating an order does not have the customer_address_id field set correctly so this data is not passed to backend and saved. On page refresh 'Add New' is still selected. 

The existing code tries to set this value but does so incorrectly so it is not saved.

### Manual testing scenarios
1. Create a new order for an existing customer that has at least one billing address saved
2. Select 'Add New' from the billing address dropdown and refresh the page (Add New should be selected)
3. Select an existing address from the billing address dropdown and refresh the page. Add New is still selected with corret billing address in indivual inputs.

### Questions or comments
There may be a better way to resolve this issue, but this is what I did in my project (although I extended the method and added the change there).

### PR DESCRIPTION
**Pull request by bentideswell**
### Description
Selecting an existing address while creating an order does not have the customer_address_id field set correctly so this data is not passed to backend and saved. On page refresh 'Add New' is still selected. 

The existing code tries to set this value but does so incorrectly so it is not saved.

### Manual testing scenarios
1. Create a new order for an existing customer that has at least one billing address saved
2. Select 'Add New' from the billing address dropdown and refresh the page (Add New should be selected)
3. Select an existing address from the billing address dropdown and refresh the page. Add New is still selected with corret billing address in indivual inputs.

### Questions or comments
There may be a better way to resolve this issue, but this is what I did in my project (although I extended the method and added the change there).

### Resolved issues:
1. [x] resolves magento/magento2#32906: Selecting Existing Address in Admin Order

### CODE REVIEW

**Comment by bentideswell** [comment]
@magento run all tests

**Comment by bentideswell** [comment]
@magento run all tests

**Comment by bentideswell** [comment]
@magento run all tests

**Comment by bentideswell** [comment]
@magento run Functional Tests B2B, WebAPI Tests

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by bentideswell** [comment]
Any idea why those 2 test are failing? Looking into the details, I can’t see any specific test that has failed.

**Comment by Den4ik** [comment]
@magento run Integration Tests, Functional Tests EE

**Review by Den4ik — CHANGES_REQUESTED** [review]
Hi @bentideswell
Thanks for your contribution. Your implementation correct with Prototype usage.
Could you also look and fix next affected lines:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/view/adminhtml/web/order/create/scripts.js#L1122
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/view/adminhtml/web/order/create/scripts.js#L1110

**Comment by bentideswell** [comment]
Sure thing. I've just modified the commit and this now includes the extra 2 instances of the issue in the same file. Thanks!

**Comment by engcom-Dash** [comment]
Hello @bentideswell,

Thank you for your contributions!

Please resolve the conflict so we can proceed with this PR.

Thanks again!

**Comment by engcom-Dash** [comment]
Closing this PR since it has not been updated in a while. Please feel free to reopen if needed.

**Pull request closed without merging**
