### PR TITLE
Update system.xml

### PR DESCRIPTION
**Pull request by Nagamaiah007**
### Fixed Issues (if relevant)

1. magento/magento2 #25757: Link (terms and conditions) is not opening new tab. Missing target="_blank" for anchor tag.

### Manual testing scenarios (*)

1. Go to Admin Page -> Menu
2. Stores -> Settings -> Configuration -> General -> Advanced Reporting Page
3. Link (terms and conditions) is opening in new tab with this fix

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by kalpmehta — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, thank you for the review.
[ENGCOM-6339](https://jira.corp.magento.com/browse/ENGCOM-6339) has been created to process this Pull Request
:eight_spoked_asterisk: @kalpmehta, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by kanthy-i95dev — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
Hello @Nagamaiah007. Thank You for Your contribution. In order for us to be able to further process Your PR please cover it with an appropriate Auto-Test. Thank You.

**Review by sidolov — APPROVED** [review]

**Comment by VladimirZaets** [comment]
@engcom-Bravo Hi, I think this PR  not required to be covered by autotests

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-6339](https://jira.corp.magento.com/browse/ENGCOM-6339) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
