### PR TITLE
Fix overlap display issue in cms page privacy theme luma

### LINKED ISSUE #32926: CMS menu issue - Luma Theme
Luma Theme needs a check for different sizes of the screen.  In order to reproduce this issue click in the footer the linked named **Privacy and Cookie Policy** then resize the browser window. Bellow you may find how is looking the CMS menu when the size of the screen is a small one.

Screenshot 2021-05-02 152055

This is happening when the menu is visible.

Screenshot 2021-05-02 152034

A change in the padding value at the bottom will fix this.

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Small change in less styles to avoid overlap visual in cms page privacy-policy theme luma
from mobile screen resolution (<768px)

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32926

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE

**Review by Den4ik — APPROVED** [review]
✅ Looks as useful solution

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9090](https://jira.corp.magento.com/browse/ENGCOM-9090) has been created to process this Pull Request

**Comment by dmitriyprime** [comment]
:heavy_check_mark: QA passed

**Comment by engcom-Alfa** [comment]
Hello @mrtuvn, @ptylek and @Den4ik
Thank you for your contribution and collaboration!

I am a new QA engineer and would like to test this Pull Request to unblock and speed up the delivery. 
Unfortunately, with the current description, I do not see how it can be tested.
Could you please provide more details on how it can be tested?
For example
- Steps to reproduce and actual/expected result. That I can use to check previous and current behavior to confirm it is fixed.
- Any functional user flows that can be affected by such changes
- Any other advice/ recommendations that will allow us to test it

**Before PR fix** in Chrome, Firefox, Microsoft Edge and Opera browsers (screenshots are below).
image

**Comment by Den4ik** [comment]
@engcom-Alfa You may reproduce and test it with installed sample data from https://github.com/magento/magento2-sample-data

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Have a theme luma setup
2. Sample data should be upgraded


**Manual testing scenario:**

1. Home page, click on "Privacy and Cookie Policy" from footer. Validate by resizing the browser to mobile/ tab sizes.

2. Category page, click on "Privacy and Cookie Policy" from footer. Validate by resizing the browser to mobile/ tab sizes.
 
3. Product details page, click on "Privacy and Cookie Policy" from footer. Validate by resizing the browser to mobile/ tab sizes.


**Before:** :heavy_multiplication_x: Privacy Policy page header overlapping to Privacy Menu

image

**After:** :heavy_check_mark:  Privacy Menu and page header are aligned properly

image


Tested the same UI alignment navigating from different UI pages like; Home page, product page, category page, cart page etc!
Tested using different browsers like Chrome, Firefox, Microsoft edge

**Pull request merged**
