### PR TITLE
[MFTF] Use AdminExpandCategoryTreeActionGroup for ExpandTree click

### LINKED ISSUE #29289: [Issue] [MFTF] Use AdminExpandCategoryTreeActionGroup for ExpandTree click
This issue is automatically created based on existing pull request: magento/magento2#29133: [MFTF] Use AdminExpandCategoryTreeActionGroup for ExpandTree click

---------
This PR use `AdminExpandCategoryTreeActionGroup` for clicking on ExpandTree
instead 
`<click selector="{{AdminCategorySidebarTreeSection.expandAll}}" stepKey="clickOnExpandTree"/>`
       ` <waitForPageLoad stepKey="waitForCategoryToLoad"/>`

### PR DESCRIPTION
**Pull request by Usik2203**
This PR use `AdminExpandCategoryTreeActionGroup` for clicking on ExpandTree
instead 
`<click selector="{{AdminCategorySidebarTreeSection.expandAll}}" stepKey="clickOnExpandTree"/>`
       ` <waitForPageLoad stepKey="waitForCategoryToLoad"/>`

### Resolved issues:
1. [x] resolves magento/magento2#29289: [MFTF] Use AdminExpandCategoryTreeActionGroup for ExpandTree click

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by eduard13** [comment]
@magento run all tests

**Review by eduard13 — DISMISSED** [review]
Thank you for your contribution 👍

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-7867](https://jira.corp.magento.com/browse/ENGCOM-7867) has been created to process this Pull Request

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-7867](https://jira.corp.magento.com/browse/ENGCOM-7867) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
@magento create issue

**Pull request merged**
