### PR TITLE
fix issue 24735

### PR DESCRIPTION
**Pull request by dmdanilchenko**
### Fixed Issues (if relevant)

1. magento/magento2#24735: Image in minicart is blurred on iPhone

### Manual testing scenarios (*)

1. Add product to cart
2. Open minicart on iPhone device

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24743) <br/>All committers have signed the CLA.

**Comment by VladimirZaets** [comment]
Hi @dmdanilchenko , please, sign CLA, otherwise, we can't process your pull request.

**Comment by nuzil** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @nuzil. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @nuzil, here is your [new Magento instance](https://pr-24743.instances.magento-community.engineering).
Admin access: [https://pr-24743.instances.magento-community.engineering/admin](https://pr-24743.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @dmdanilchenko,
Could you sign CLA and add your committer email to GitHub account?

**Comment by dmdanilchenko** [comment]
Hi @ihor-sviziev it is done. 
@nuzil , thanks for support!

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5980](https://jira.corp.magento.com/browse/ENGCOM-5980) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@dmdanilchenko thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [Magento instance](https://i-24743-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24743-2-3-develop.instances.magento-community.engineering/admin](https://i-24743-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [new Magento instance](https://pr-24743.instances.magento-community.engineering).
Admin access: [https://pr-24743.instances.magento-community.engineering/admin](https://pr-24743.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by engcom-Alfa** [comment]
Hi @dmdanilchenko 

During testing we faced with the issue

**_Problem:_** The image in the mini cart has become very small (**39x39 px**) on Blank theme 

**Steps to reproduce:**
1. Create product with image;
2. In admin change theme to Blank;
3. Go to Storefront;
4. Add product to cart;
5. Click on mini cart;

**Actual Result:**
after2

**_Note:_**  On Luma theme image size in mini cart is (**75x75 px**) :heavy_check_mark: 
after3

@dmdanilchenko Could you take a look, please?

Thanks!

**Review by ihor-sviziev — APPROVED** [review]

**Comment by dmdanilchenko** [comment]
@engcom-Alfa thanks for your note, i updated the PR (made the same fix for Blank theme)

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @dmdanilchenko,
Could you also sign Adobe CLA?

**Comment by dmdanilchenko** [comment]
@ihor-sviziev Adobe CLA is done

**Comment by ihor-sviziev** [comment]
> @ihor-sviziev Adobe CLA is done

Still showing that it's not signed, please double check it
image

**Comment by dmdanilchenko** [comment]
@ihor-sviziev , signed again with alternative email. Looks like it is fine now

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [new Magento instance](https://pr-24743.instances.magento-community.engineering).
Admin access: [https://pr-24743.instances.magento-community.engineering/admin](https://pr-24743.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by ihor-sviziev** [comment]
@sidolov @VladimirZaets,
Is there any issues with this PR? It passed QA 22 days ago and no updates since yet

**Comment by nuzil** [comment]
Agree, we are waiting for it for Async import project :-)

**Comment by Karlasa** [comment]
@dmdanilchenko  @ihor-sviziev 
Are you sure that only minicart component is using this template and this change will not affect some other images in storefront?

**Comment by ihor-sviziev** [comment]
> @dmdanilchenko @ihor-sviziev
> Are you sure that only minicart component is using this template and this change will not affect some other images in storefront?

It doesn't really matter as image will be anyway 2x.

**Comment by Karlasa** [comment]
> > @dmdanilchenko @ihor-sviziev
> > Are you sure that only minicart component is using this template and this change will not affect some other images in storefront?
> 
> It doesn't really matter as image will be anyway 2x.

Actually it does, if you have some other img using it and haven't changed size 2x in view.xml it will now render  2x smaller as before because css width/2. But double checked and seems like should not be in use in anywhere else so good to go :)

**Comment by slavvka** [comment]
@ihor-sviziev Do you agree?

**Comment by slavvka** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
> > > @dmdanilchenko @ihor-sviziev
> > > Are you sure that only minicart component is using this template and this change will not affect some other images in storefront?
> > 
> > 
> > It doesn't really matter as image will be anyway 2x.
> 
> Actually it does, if you have some other img using it and haven't changed size 2x in view.xml it will now render 2x smaller as before because css width/2. But double checked and seems like should not be in use in anywhere else so good to go :)

It’s not used anywhere else, so it’s fine to merge it

**Review by slavvka — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @slavvka, thank you for the review.
[ENGCOM-5980](https://jira.corp.magento.com/browse/ENGCOM-5980) has been created to process this Pull Request

**Comment by slavvka** [comment]
Internal ticket for performance degradation review https://jira.corp.magento.com/browse/MC-30242

**Comment by slavvka** [comment]
@dmdanilchenko Could you please resolve the conflict?

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@slavvka fixed merge conflict myself

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5980](https://jira.corp.magento.com/browse/ENGCOM-5980) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [Magento instance](https://i-24743-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-24743-2-4-develop.instances.magento-community.engineering/admin_67a1](https://i-24743-2-4-develop.instances.magento-community.engineering/admin_67a1)
Login: `aaf8882c` Password: `37dfc328bb27`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [new Magento instance](https://pr-24743.instances.magento-community.engineering).
Admin access: [https://pr-24743.instances.magento-community.engineering/admin_1923](https://pr-24743.instances.magento-community.engineering/admin_1923)
Login: `f841962b` Password: `9d5174fdc343`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:**
before

**After:**
after

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR.

**Comment by slavvka** [comment]
Performance degradation approval is in progress (https://jira.corp.magento.com/browse/MC-30242)

**Comment by slavvka** [comment]
```
CompareReports\SiteSpeedCompareReports::testWebPageTestRequestsCount with data set "Customer cart" ('Customer cart', array(array(77, 74, 82, 98), array(29, 10, 4, 3, 5), array(2983946, 414712, 29559, 74204), array(5904)), array(array(77, 74, 82, 98), array(29, 10, 4, 3, 5), array(2984128, 414712, 34951, 74204), array(5862)))
Image Size in the `Customer cart` scenario is greater than on mainline. Team-fork has 18.2% degradation. 
```
```
CompareReports\SiteSpeedCompareReports::testWebPageTestRequestsCount with data set "Customer checkout" ('Customer checkout', array(array(78, 76, 83, 97), array(27, 10, 4, 2, 5), array(2983946, 414712, 20473, 74204), array(5728)), array(array(78, 76, 83, 97), array(27, 10, 4, 2, 5), array(2984128, 414712, 25865, 74204), array(5731)))
Image Size in the `Customer checkout` scenario is greater than on mainline. Team-fork has 26.3% degradation. 
```
```
CompareReports\SiteSpeedCompareReports::testWebPageTestRequestsCount with data set "Guest cart" ('Guest cart', array(array(77, 74, 82, 98), array(29, 10, 4, 3, 5), array(2983946, 414712, 29559, 74204), array(5942)), array(array(77, 74, 82, 98), array(29, 10, 4, 3, 5), array(2984128, 414712, 34951, 74204), array(5958)))
Image Size in the `Guest cart` scenario is greater than on mainline. Team-fork has 18.2% degradation.
```
``` 
CompareReports\SiteSpeedCompareReports::testWebPageTestRequestsCount with data set "Guest checkout" ('Guest checkout', array(array(78, 76, 83, 97), array(27, 10, 4, 2, 5), array(2983946, 414712, 20473, 74204), array(1928)), array(array(78, 76, 83, 97), array(27, 10, 4, 2, 5), array(2984128, 414712, 25865, 74204), array(1931)))
Image Size in the `Guest checkout` scenario is greater than on mainline. Team-fork has 26.3% degradation. 
```

**Comment by slavvka** [comment]
PAT degradation is approved

**Review by slavvka — APPROVED** [review]
PAT degradation is approved

**Comment by magento-engcom-team** [comment]
Hi @slavvka, thank you for the review.
[ENGCOM-5980](https://jira.corp.magento.com/browse/ENGCOM-5980) has been created to process this Pull Request

**Pull request merged**
