### PR TITLE
patch-19386 : Fixed Links once created not deleted from The Links Sec…

### PR DESCRIPTION
**Pull request by ansari-ziyaurrahman**
Links once created not deleted from The Links Section in Downloadable products 

### Description (*)
Fixed Links once created not deleted from The Links Section in Downloadable products.

### Fixed Issues (if relevant)
1. magento/magento2#19386: Links once created not deleted from The Links Section in Downloadable products 

### Manual testing scenarios (*)
1. Check with new and existing product.
2. Add new product and edit also it.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19389) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @ansari-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by orlangur** [comment]
Please never apply similar changes in different pull requests. This would lead to conflict once first one is merged.

**Comment by ansari-ziyaurrahman** [comment]
Hi @orlangur 
Thanks for review this issue.
I have to say that #19150 and #19389 both have different issues. Look at once it show similar but they have different files. Sure patch are same in both issues but they are in different files. First issue in sample links section (#19150 ) and this issue in Links section issue. Please let me know if you have any confusion.
Thanks.

**Comment by ansari-ziyaurrahman** [comment]
HI @orlangur,
I am Reopen this issue due to this is not a duplicate issue.
Let me know your thoughts, Please.

**Comment by orlangur** [comment]
@ansari-krish nope, this is already covered by https://github.com/magento/magento2/pull/19150#issuecomment-441403251

**Pull request closed without merging**
