### PR TITLE
#25832 Allow to set negative number for attribute position

### PR DESCRIPTION
**Pull request by Tomasz-Silpion**
### Description (*)

Change attribute position field validation from validate-digits ("Please enter a valid number in this field") to integer ("A positive or negative non-decimal number please")

### Fixed Issues (if relevant)

1. magento/magento2#25832: Allow to set negative number for attribute position in layered navigation

### Manual testing scenarios (*)

1. Go to admin -> stores -> attributes -> product
2. Try to enter negative number for position in storefront properties
3. Clear cache and check if attribute has higher priority than attributes with position 0

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [X] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by krzksz — CHANGES_REQUESTED** [review]
Hello @Tomasz-Silpion, please sign the CLA otherwise we are not able to process your PR.

**Comment by dmytro-ch** [comment]
Hi @Tomasz-Silpion, thank you for your contribution!
Please sign CLA, otherwise, we won't be able to process your pull request.

Also, due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) the changes should be covered by tests. Could you please cover your fix by automated tests?

Thank you!

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hi, @Tomasz-Silpion, thank you for your contribution.
I briefly checked your solution and I guess it has the right to life.

Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) the changes should be covered by tests. Could you please cover your fix by automated tests?

Thank you!

**Review by krzksz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-6369](https://jira.corp.magento.com/browse/ENGCOM-6369) has been created to process this Pull Request

**Comment by krzksz** [comment]
Dear @Tomasz-Silpion, due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your changes by automated tests.

**Comment by engcom-Bravo** [comment]
Hello @Tomasz-Silpion. Thanks for contribution. Please cover Your PR with the appropriate auto-tests so that we may process it further. Thank You.

**Comment by VladimirZaets** [comment]
@Tomasz-Silpion, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Comment by Tomasz-Silpion** [comment]
@magento give me 2.4-develop instance

**Pull request closed without merging**
