### PR TITLE
[Forwardport] [Backport] fixed store wise product filter issue

### PR DESCRIPTION
**Pull request by shikhamis11**
### Original Pull Request 
 https://github.com/magento/magento2/pull/19911
### Original Pull Request 
 https://github.com/magento/magento2/pull/18994
Fixed issue - #18374
Unable to get product attribute value for store-view scope type in product collection loaded for a specific store.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sidolov** [comment]
Hi @shikhamis11 , provided changes already merged in scope of https://github.com/magento/magento2/pull/18994
I'm closing this PR as not relevant. 
Thank you for the contribution!

**Comment by shikhamis11** [comment]
@sidolov yes This is already merged but the changes are not reflecting on 2.3-develop branch.

**Comment by davidverholen** [comment]
there was another commit that has been merged reverting the change. For some reason it's not shown in the pr or in the github file history (it shows for example in phpstorm git file history)
https://github.com/magento/magento2/commit/a4b989bc916d769f92b3ec88303d1f5dd76ef3a7

However since the change has already been approved in https://github.com/magento/magento2/pull/18994 I guess this could be merged

**Review by davidverholen — APPROVED** [review]

**Pull request merged**
