### PR TITLE
Fixed issue #23575

### PR DESCRIPTION
**Pull request by syed92hasan**
### Description (*)

Created date mismatch with a calendar icon
### Fixed Issues (if relevant)

1. magento/magento2#23575: Created date mismatch with a calendar icon

### Manual testing scenarios (*)

 1.   Admin -> Marketing -> User Contents -> Reviews
 2.   Select created date
   
Before Update Result
   
     
before-update

After Update Result 

after-update

    

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23633) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23633) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Stepa4man<br/>:x: sayed<hr/>**sayed** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Review by Stepa4man — CHANGES_REQUESTED** [review]
Hi @syed92hasan, thanks for your contribution!
Please sign CLA.

**Comment by syed92hasan** [comment]
> Hi @syed92hasan, thanks for your contribution!
> Please sign CLA.

Hi @Stepa4man,
 > CLA sign in done, please check.

**Comment by Stepa4man** [comment]
> > Hi @syed92hasan, thanks for your contribution!
> > Please sign CLA.
> 
> Hi @Stepa4man,
> 
> > CLA sign in done, please check.

@syed92hasan, I don't think so.
Looks like you had committed to the repo with the different user. Please make sure that your git user email matches with github account email.

**Pull request closed without merging**
