### PR TITLE
Improve mediaGallery reload action, to prevents js error

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. https://github.com/magento/adobe-stock-integration/issues/1272 

### Manual testing scenarios (*)
Verify that Media Gallery opened correct in all cases and there is no js errors on console

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @Nazar65. Thank you for your collaboration. Could I ask you to cover this change using a Jasmine or MFTF? 

Thank you.

**Comment by orlangur** [comment]
@Nazar65 could you provide testing scenario revealing the bug?

**Comment by Nazar65** [comment]
> @Nazar65 could you provide testing scenario revealing the bug?

nope, i can cover it only with unit tests, it is specific case for third party extensions

**Review by sivaschenko — CHANGES_REQUESTED** [review]
I think this issue should be fixed on New Media Gallery side (adobe-stock-integration repo). The mediabrowser widget should not be instantiated with the new media gallery.

**Comment by Nazar65** [comment]
Closing as this fix migrated to the adobe-stock-integration repo

**Pull request closed without merging**
