### PR TITLE
Correctly escape custom product image attributes

### PR DESCRIPTION
**Pull request by alexander-aleman**
### Description (*)

This change tries to solve https://github.com/magento/magento2/issues/25219 by no longer escaping strings of the form `attribute-name="attribute value"` but direclty rendering and escaping them in the view.

### Fixed Issues (if relevant)

1. magento/magento2#25219: Custom attributes of images generated by Block\Product\ImageFactory don't render correctly

### Manual testing scenarios (*)

1. See https://github.com/magento/magento2/issues/25219

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by aleron75 — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-6962](https://jira.corp.magento.com/browse/ENGCOM-6962) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Review by engcom-Delta — DISMISSED** [review]
Hi @alexander-aleman could you resolve merge conflicts?

**Comment by alexander-aleman** [comment]
@engcom-Delta it seems some tests are stuck on in progress, could you maybe restart them?

**Comment by engcom-Delta** [comment]
@magento run all tests

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-6962](https://jira.corp.magento.com/browse/ENGCOM-6962) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
