### PR TITLE
Fix PHPDocs for \Magento\Framework\Data\Collection::getItemById

### LINKED ISSUE #38485: [Issue] Fix PHPDocs for \Magento\Framework\Data\Collection::getItemById
This issue is automatically created based on existing pull request: magento/magento2#38439: Fix PHPDocs for \Magento\Framework\Data\Collection::getItemById

---------

Add null as possible type returned by `getItemById` method.
Method returns null when item is not found.

PHPStan complains in the code using that method:
Sample usage:
```php
$product = $productCollection->getItemById(42);
if ($product) { # phpstan: If condition is always true.
    // some logic
}
```

Result in PHPStorm:
image

### Description (*)

Adds `null` type to PHPDocs of `\Magento\Framework\Data\Collection::getItemById`.
Fixes minor grammar issues in PHPDocs of that class.
### Manual testing scenarios (*)

1. Create a module that uses any Collection and add code which reflects `if` condition specified in the PR summary
2. Configure PHPStan with enabled `Treat PHPDoc types as certain` (usually it is enabled by default)
3. Run static analysis (or open file in IDE with static analysis capabilities such as PHPStorm)
4. There should be no warning/error `if condition is always true`

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by MTheProgrammer**
Add null as possible type returned by `getItemById` method.
Method returns null when item is not found.

PHPStan complains in the code using that method:
Sample usage:
```php
$product = $productCollection->getItemById(42);
if ($product) { # phpstan: If condition is always true.
    // some logic
}
```

Result in PHPStorm:
image

### Description (*)

Adds `null` type to PHPDocs of `\Magento\Framework\Data\Collection::getItemById`.
Fixes minor grammar issues in PHPDocs of that class.
### Manual testing scenarios (*)

1. Create a module that uses any Collection and add code which reflects `if` condition specified in the PR summary
2. Configure PHPStan with enabled `Treat PHPDoc types as certain` (usually it is enabled by default)
3. Run static analysis (or open file in IDE with static analysis capabilities such as PHPStorm)
4. There should be no warning/error `if condition is always true`

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38485: Fix PHPDocs for \Magento\Framework\Data\Collection::getItemById

### CODE REVIEW

**Comment by MTheProgrammer** [comment]
@magento give me test instance

**Review by edenduong — APPROVED** [review]
Thank you for your contribution!

**Comment by engcom-Delta** [comment]
@magento create issue

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by MTheProgrammer** [comment]
It fails Semantic Version Checker test because of the fix in PHPDocs, but no API is changed in reality. Code is the same. How to deal with this?
```
Suggested version increase (based on PHP code analysis and files changed) MAJOR
```

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**
1. Create a module that uses any Collection and add code which reflects if condition specified in the PR summary
2. Configure PHPStan with enabled Treat PHPDoc types as certain (usually it is enabled by default)
3. Run static analysis (or open file in IDE with static analysis capabilities such as PHPStorm)
4. There should be no warning/error if condition is always true

**Before: ❌**
image
Warning stating that if condition is always true.

**After: :heavy_check_mark:** 
Screenshot 2024-03-07 at 1 42 54 PM
There is no warning/error that if condition is always true.

**Comment by engcom-November** [comment]
@magento Functional Tests B2B, Functional Tests EE, Semantic Version Checker

**Comment by engcom-November** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Semantic Version Checker

**Comment by engcom-November** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
As SVC tests are failing we have raised a internal approval jira, hence moving this to Pending Approval.

**Comment by engcom-November** [comment]
Since we got the approval for SVC failure [AC-11580](https://jira.corp.adobe.com/browse/AC-11580), moving this to extended testing because of failed builds.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, Integration Tests, WebAPI Tests

**Comment by engcom-November** [comment]
@magento run Functional Tests EE

**Comment by engcom-November** [comment]
Functional Tests CE, Functional Tests EE and Functional Tests B2B are different on last two runs on same commit.

Functional Tests CE :
Contains know failures:
[ACQE-6102](https://jira.corp.adobe.com/browse/ACQE-6102)
Run 1 :
image

Run 2 : 
image

Functional Tests EE :
Contains know failures:
[ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331)
Run 1 : 
image

Run 2 : 
image

Functional Tests B2B :
Contains know failures:
[ACQE-6363](https://jira.corp.adobe.com/browse/ACQE-6363)
Run 1 : 
image

Run 2 : 
image

**Comment by engcom-November** [comment]
WebAPI Tests :
GRAPHQL WebAPI tests for CE : 
Run 1 : 
image

Run 2 : 
image

Executed the same test locally but the error was not reproducible.
So this seems to be flaky.

Hence moving this to `Merge in Progress`.

**Pull request merged**
