### PR TITLE
Remove forbidden `@author` tag

### LINKED ISSUE #37263: [Issue] Remove forbidden `@author` tag
This issue is automatically created based on existing pull request: magento/magento2#37013: Remove forbidden `@author` tag

---------
### Description
According to https://devdocs.magento.com/guides/v2.4/coding-standards/docblock-standard-general.html#documentation-space, the `@author` tag is not permitted in Magento. This pull request removes this tag from some modules. Given there are so many instances of this tag, I've opened a small pull request to get the process started. I expect that the linter will force me to fix several other coding standards violations on the way, so having a smaller pull request means that task is easier to manage. I plan to open more pull requests to tackle the other instances of this tag.

See also https://github.com/magento/magento-coding-standard/pull/382 and https://github.com/magento/magento-coding-standard/issues/167

### Manual testing scenarios
There are not code changes in this pull request. This pull request only removes forbidden comments.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fredden**
### Description
According to https://devdocs.magento.com/guides/v2.4/coding-standards/docblock-standard-general.html#documentation-space, the `@author` tag is not permitted in Magento. This pull request removes this tag from some modules. Given there are so many instances of this tag, I've opened a small pull request to get the process started. I expect that the linter will force me to fix several other coding standards violations on the way, so having a smaller pull request means that task is easier to manage. I plan to open more pull requests to tackle the other instances of this tag.

See also https://github.com/magento/magento-coding-standard/pull/382 and https://github.com/magento/magento-coding-standard/issues/167

### Manual testing scenarios
There are not code changes in this pull request. This pull request only removes forbidden comments.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37263: Remove forbidden `@author` tag

### CODE REVIEW

**Comment by fredden** [comment]
@magento run Static Tests

**Review by leonhelmus — APPROVED** [review]
Looks good to me!

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento run Functional Tests B2B, Functional Tests CE,

**Comment by engcom-Delta** [comment]
Functional Tests B2B and CE failiures are different on last two run 
B2B:run 1
Screenshot 2023-03-21 at 8 51 32 PM
run 2
Screenshot 2023-03-21 at 8 49 16 PM
CE: run 1
Screenshot 2023-03-21 at 8 50 41 PM
run2
Screenshot 2023-03-21 at 8 49 51 PM

Hence functional test case failures are flaky

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
As mentioned above [comment](https://github.com/magento/magento2/pull/37013#issuecomment-1478059806) the functional tests are flaky and unit tests are not failing due to PR changes. Hence Moving this PR to merge in Progress.

Thanks.

**Pull request merged**
