### PR TITLE
Feature/32442 delete laminas form from composer

### PR DESCRIPTION
**Pull request by AndreyChorniy**
### Description (*)
This PR created for delete package laminas/laminas-form

### Fixed Issues (if relevant)
Resolves https://github.com/magento/magento2/issues/32442

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by AndreyChorniy** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
It seems like your changes broke some functionality. Please review and fix test failures.

**Comment by AndreyChorniy** [comment]
@magento run all tests

**Comment by AndreyChorniy** [comment]
Hello @ihor-sviziev,
It seems that a couple of extensions which were as a dependency for laminas/laminas-form, used in tests and this is broke them after deleting.
So as the solution I decided to install two packages, and for now, we can see that tests passed.
But I have a question here. 
Is this is a good solution to install these packages separately? Or do we need to fix issues using some other classes?

**Comment by ihor-sviziev** [comment]
@AndreyChorniy, from my perspective, it seems like we should check if it is used only in the tests - better to fix tests with alternatives or add these dependencies to the require-dev section instead. What do you think about it?

**Comment by ihor-sviziev** [comment]
@AndreyChorniy I just checked - looks like they're used not in tests, so it's better to declare them as you did.
https://github.com/magento/magento2/search?q=Laminas%5CFilter%5C
https://github.com/magento/magento2/search?q=Laminas%5CHydrator

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@AndreyChorniy could you add to the description the following line?
Fixes #32442

**Comment by AndreyChorniy** [comment]
Hello @ihor-sviziev,
I have adjusted the description for this PR.

**Comment by ihor-sviziev** [comment]
@sivaschenko, for some reason, it didn't link the issue to PR. Could you link it properly?

**Comment by sivaschenko** [comment]
Hi @ihor-sviziev @AndreyChorniy

The issue is referenced correctly, not sure why github doesn't link it.

@AndreyChorniy have you tried to remove the references for the `filter` and `hydrator` dependencies instead of adding them to composer.json?

**Comment by ihor-sviziev** [comment]
Hi @AndreyChorniy,
Thank you for your contribution!
I'm closing this PR as we have a better solution in https://github.com/magento/magento2/pull/32513. It completely removes parts that we did not need, and they used those laminas components. I think it's better to accept it instead.

**Pull request closed without merging**
