### PR TITLE
MC-38993: Magento\Authorization\Model\ResourceModel\Rules missing update method

### LINKED ISSUE #29128: Magento\Authorization\Model\ResourceModel\Rules missing update method
Basically in [Rules Model](https://github.com/magento/magento2/blob/fa6d291646b1ca0ebc0ebd3798ec8aaae634d486/app/code/Magento/Authorization/Model/Rules.php#L61) is used "update" method from the resouceModel. However it was never declared in [Rules Resource Model](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Authorization/Model/ResourceModel/Rules.php)

### Preconditions (*)

I discovered in on magento 2.3. But is still appear in Magento 2.4
Magento 2.4-develop

### Steps to reproduce (*)

just use anywhere "update" method from Rules Model

### Expected result (*)

Not having a fatal error would be nice

### Actual result (*)

PHP Fatal error:  Uncaught Error: Call to undefined method Magento\Authorization\Model\ResourceModel\Rules::update() in /var/www/magento/vendor/magento/module-authorization/Model/Rules.php:61

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by engcom-Golf**
Added deprecated tag to the method. Will be deleted in next major release

### Description (*)

Method was never implemented and used. Migrated from Magento 1

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29128

### Manual testing scenarios (*)

1. Create a module that will use method \Magento\Authorization\Model\Rules::update
2. Run the code
Expected result: 
An exception that the method is obsolete but not a fatal error
3. Run Static Tests
Expected result: 
An exception that method can not be used as it is deprecated 
 
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@engcom-Golf can it be covered with automated test?

**Comment by engcom-Golf** [comment]
@ihor-sviziev these changes don't add any functionality that can be broken and nothing to cover with tests. If you use the deprecated method in code somewhere Static Tests will fail.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8473](https://jira.corp.magento.com/browse/ENGCOM-8473) has been created to process this Pull Request

**Comment by engcom-Golf** [comment]
@magento run Functional Tests B2B, Integration Tests

**Comment by engcom-Golf** [comment]
@magento run all tests

**Review by zakdma — APPROVED** [review]

**Comment by zakdma** [comment]
@magento copy pr to https://github.com/magento-tsg/magento2ce

**Comment by zakdma** [comment]
@magento import pull request to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the pull request successfully imported.

**Comment by engcom-Bravo** [comment]
QA not applicable, dev experience is required to test the PR. Moved to _Extended Testing_ column

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
