### PR TITLE
Fix php error in profiler when using PHP 8.1

### LINKED ISSUE #35307: [Magento 2.4.4] Class Magento\Framework\Profiler\Driver\Standard\Stat not compatible with PHP 8.1
### Preconditions (*)

1. Magento 2.4.4

### Steps to reproduce (*)

1. In a custom module (in our case, a debug toolbar), call the method `getFilteredTimerIds` of the class Magento\Framework\Profiler\Driver\Standard\Stat.

### Expected result (*)

1. The function returns an array of ordered timer ids

### Actual result (*)

1. PHP crashes with the following error :

```
1 exception(s):
Exception #0 (Exception): Deprecated Functionality: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/vendor/magento/framework/Profiler/Driver/Standard/Stat.php on line 213

Exception #0 (Exception): Deprecated Functionality: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/vendor/magento/framework/Profiler/Driver/Standard/Stat.php on line 213
<pre>#1 strpos() called at [vendor/magento/framework/Profiler/Driver/Standard/Stat.php:213]
#2 Magento\Framework\Profiler\Driver\Standard\Stat->_getOrderedTimerIds() called at [vendor/magento/framework/Profiler/Driver/Standard/Stat.php:158]
#3 Magento\Framework\Profiler\Driver\Standard\Stat->getFilteredTimerIds() called at [app/code/Smile/DebugToolbar/Helper/Profiler.php:96]
#4 Smile\DebugToolbar\Helper\Profiler->prepareTimers() called at [app/code/Smile/DebugToolbar/Helper/Profiler.php:68]
#5 Smile\DebugToolbar\Helper\Profiler->computeStats() called at [app/code/Smile/DebugToolbar/Observer/AddToolbar.php:105]
#6 Smile\DebugToolbar\Observer\AddToolbar->execute() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:88]
#7 Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:74]
#8 Magento\Framework\Event\Invoker\InvokerDefault->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#9 Magento\Framework\Event\Invoker\InvokerDefault\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#10 Magento\Framework\Event\Invoker\InvokerDefault\Interceptor->Magento\Framework\Interception\{closure}() called at [app/code/Smile/DebugToolbar/Plugin/Event/Invoker.php:64]
#11 Smile\DebugToolbar\Plugin\Event\Invoker->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#12 Magento\Framework\Event\Invoker\InvokerDefault\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#13 Magento\Framework\Event\Invoker\InvokerDefault\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/Event/Invoker/InvokerDefault/Interceptor.php:23]
#14 Magento\Framework\Event\Invoker\InvokerDefault\Interceptor->dispatch() called at [vendor/magento/framework/Event/Manager.php:66]
#15 Magento\Framework\Event\Manager->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#16 Magento\Framework\Event\Manager\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#17 Magento\Framework\Event\Manager\Interceptor->Magento\Framework\Interception\{closure}() called at [app/code/Smile/DebugToolbar/Plugin/Event/Manager.php:52]
#18 Smile\DebugToolbar\Plugin\Event\Manager->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#19 Magento\Framework\Event\Manager\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#20 Magento\Framework\Event\Manager\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/Event/Manager/Interceptor.php:23]
#21 Magento\Framework\Event\Manager\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:131]
#22 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#23 Magento\Framework\App\Http\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#24 Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#25 Magento\Framework\App\Http\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#26 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#27 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>
```

The error happens in the protected method `_getOrderedTimerIds`:

```
for ($j = $i + 1; $j < count($timerIds); $j++) {
    if (strpos($timerIds[$j], $prevTimerId . Profiler::NESTING_SEPARATOR) === 0) {
        $result[] = $timerIds[$j];
        /* Mark timer as already added */
        $timerIds[$j] = null;
    }
}
```

$timerIds[$j] is set to null at line 216, so the call to strpos at line 210 fails (strpos only accepts string values in PHP 8.1).

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by vovayatsyuk**
### Description (*)
This PR fixes possible deprecation error:

```
Deprecated: strpos(): Passing null to parameter 1 ($haystack) of type string is deprecated 
in Magento/Framework/Profiler/Driver/Standard/Stat.php:213
```

### Fixed Issues
1. Fixes magento/magento2#35307

### Manual testing scenarios (*)
1. Appy the [first commit from this PR](https://github.com/magento/magento2/pull/35321/commits/42d88187c54c4ae80468c34f1319de075a48ec75) and run unit test: `./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist lib/internal/Magento/Framework/Profiler/Test/Unit/Driver/Standard/StatTest.php`
2. You'll see an error during the test
3. Apply all other commits, and run the test again.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Install the Magento latest 2.4-develop version code.
2. Make sure Magento instance running with PHP 8.1 version
3. Execute the command: `./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist lib/internal/Magento/Framework/Profiler/Test/Unit/Driver/Standard/StatTest.php` and check it is successfully getting executed from the Magento root folder as shown in below screenshot
image

**Manual testing scenario:**

1. Open the file `lib/internal/Magento/Framework/Profiler/Test/Unit/Driver/Standard/StatTest.php` and update four line of lines of code as shown in the commit changes [HERE](https://github.com/magento/magento2/pull/35321/commits/42d88187c54c4ae80468c34f1319de075a48ec75).

2. Flush through CLI command once.
 
3. Run the unit test command again: `./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist lib/internal/Magento/Framework/Profiler/Test/Unit/Driver/Standard/StatTest.php`

4. Validate that, it is getting executed as trialled in pre conditions.


**Before:** :heavy_multiplication_x: Throwing deprecated exception error as shown in below screenshot.
image

**After:** :heavy_check_mark: Executed successfully and resulted as like in above mentioned pre-condition step
image

There is no additional regression is required as part of testing, since it is a fix relevant to unit test case specifically with php 8.1.

**Comment by engcom-Alfa** [comment]
Since there is a Static Tests job is getting failed, moving it to _Extended Testing_ column for further investigations.
Thanks

**Comment by vovayatsyuk** [comment]
There are some weird warnings in B2B testing: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/35321/14e025c0c42599e9966ca9044c7ad667/Statics/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

**Comment by engcom-Charlie** [comment]
Hi @vovayatsyuk,

Thank you for your contribution!

I will look into the build failures.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
The static test case failures are not part of this PR changes, hence moving this PR to Merge in Progress.

Thank you!

**Pull request merged**
