### PR TITLE
Fix issue 19286 - Wrong pager style

### PR DESCRIPTION
**Pull request by SyntaxKay**
### Description (*)

1. Magento 2.2-Develop
### Fixed Issues (if relevant)

1. magento/magento2#19286: Wrong pager style

### Manual testing scenarios (*)

1. Add more than 10 order from one account.
2. Go to -> Myaccount -> My orders 
3. Pagination design of orders tables.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3507](https://jira.corp.magento.com/browse/ENGCOM-3507) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@speedy008 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by rodrigowebjump — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-3507](https://jira.corp.magento.com/browse/ENGCOM-3507) has been created to process this Pull Request

**Comment by rodrigowebjump** [comment]
Hi, @speedy008 Thanks for your contribution. 
Please, could you also open a PR for 2.3-develop branch and refer this PR?

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.

**Comment by SyntaxKay** [comment]
@magento-engcom-team 
I have already port  into magento-2.3-develop.

**Pull request merged**
