### PR TITLE
24978 fixed popup design in new email template adminhtml

### PR DESCRIPTION
**Pull request by RonakParmar**
### Description (*)
The js confirmation popup design is not proper in Add/Edit Email template at adminhtml. Please follow below steps to reproduce the issue.

### Fixed Issues (if relevant)

1. magento/magento2#24978: New Email Template JS Confirm Message Popup Design is not Proper

### Manual testing scenarios (*)

1.Login Admin -> Marketing
2. Under Communication Section -> Open Email Templates and Newsletter Templates both in different browser tab.
3. Click on Add New Template button on both the views.
4. Click on Convert to Plain Text button.
5. Observe the js Confirmation Popup of both the views is different.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by dmytro-ch** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-25035.instances.magento-community.engineering).
Admin access: [https://pr-25035.instances.magento-community.engineering/admin](https://pr-25035.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6073](https://jira.corp.magento.com/browse/ENGCOM-6073) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
Issue is not reproducible on 2.3-develop, but is reproducible on 2.3.3
**On Hold** while 2.3.3 would be merged to 2.3-develop
cc @sdzhepa

**Comment by RonakParmar** [comment]
@engcom-Delta As the 2.3.3 now merged, Is anyone review this PR?  Right now it is on hold.
Let me know if I have to do anything regarding this PR.

Thank you.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6073](https://jira.corp.magento.com/browse/ENGCOM-6073) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @RonakParmar. Unfortunately, we are not able to reproduce this [issue](https://github.com/magento/magento2/issues/24978) on fresh 2.4-develop

**Actual Result:**
before

**Comment by dmytro-ch** [comment]
Hello @RonakParmar, I'm closing this PR now due to inactivity.
Feel free to reopen and update if you wish to continue.
Thank you!

**Pull request closed without merging**
