### PR TITLE
Do not close not reviewed issues

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)

Unfortunately, we still have a lot of not-reviewed issues. The bot shouldn't close the issues that weren't triaged as they still might be critical.

/CC @sivaschenko @sidolov @gabrieldagama 

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by Den4ik — APPROVED** [review]
✅ 

I'm agree with it

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9099](https://jira.corp.magento.com/browse/ENGCOM-9099) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by hostep** [comment]
Should we also exclude issue with labels that start with `Reproduced on `?
Based on: https://github.com/magento/magento2/issues/27039#issuecomment-852941333

**Comment by ihor-sviziev** [comment]
@hostep I will discuss it with other maintainers

**Comment by hostep** [comment]
And another example of an issue that just got closed by the stalebot, even though it was already confirmed: https://github.com/magento/magento2/issues/24736

**Comment by ihor-sviziev** [comment]
As we discussed on the Maintainers call - if contributors still think it's an important issue that still should be solved - he (or she) should review it with a maintainer and later on discussed it during the Public Triage meeting.

If you feel that some issue still should be fixed, please reach maintainers and discuss it.

I'm closing my PR.

**Pull request closed without merging**
