### PR TITLE
[Backport] Resolved upgrade issue if manufacturer attribute missing [Magento 2.2]

### PR DESCRIPTION
**Pull request by suneet64**
[Backport] Original pull request https://github.com/magento/magento2/pull/19514

Resolved upgrade issue if manufacturer attribute missing [Magento 2.2]

### Description (*)

A fatal error while setup:upgrade if you are upgrading to Magento v2.2.7 from an earlier version and manufacturer attribute not exist in the existing database.

### Fixed Issues (if relevant)

1. magento/magento2#18134: Manufacturer error when upgrading to 2.2.6

### Manual testing scenarios (*)

1. Have a Magento v2.2.5 clean installation.
2. Remove manufacturer attribute from Stores > Attributes > Product as it is not a system attribute.
3. Upgrade the Magento to v2.2.7 using command line
4. Enable the display_errors from app/bootstrap.php file.
5. **Before:** Execute setup:upgrade and while upgrading data you will notice a fatal error because of missing manufacturer attribute.
**After:** The fatal error disappear in this fix.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @suneet64. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
@suneet64 thanks for your contribution, we'll process this pull request once https://github.com/magento/magento2/pull/19514 will be merged

**Review by orlangur — CHANGES_REQUESTED** [review]
@suneet64 cherry-picks of existing commits must be applied instead of redoing changes.

**Comment by suneet64** [comment]
@orlangur In this commit, I have applied the fix for Magento v2.2 and in https://github.com/magento/magento2/pull/19514, for v2.3. The files which I modified for v2.2 do not exist in v2.3. Please let me know the next steps for this.

**Comment by orlangur** [comment]
@suneet64 the best way is to cherry-pick 2.3 commits unchanged and then apply necessary refactoring.

**Comment by suneet64** [comment]
@orlangur the changes done for 2.3 are already merged and the branch has been deleted. Please suggest the next steps. Thanks!

**Comment by sivaschenko** [comment]
Hi @suneet64 can you please cherry-pick both @orlangur and @sidolov commits from the original PR

**Comment by suneet64** [comment]
Hi @sivaschenko, I just cherry picked the commits from the original PR. Please review.

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-4092](https://jira.corp.magento.com/browse/ENGCOM-4092) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
✔️ QA passed

**Pull request merged**
