### PR TITLE
Empty system message

### PR DESCRIPTION
**Pull request by snky1987**
Fixed issue with empty system message popup when issue has been fixed in the other window and current window wasn't refreshed.

Default message to display hard coded in controller.

Created separate pull request as from now on every single fix will be pushed to separate branches (as it should be) also fixed Coding standards issues.

If any Travis CI issues will appear due to coding standards it will be about differences between Windows and Unix environment (line endings).

### CODE REVIEW

**Comment by otoolec** [comment]
I've updated internal ticket MAGETWO-32969 from issue #919 to point to this pull request for processing.

**Comment by anupdugar** [comment]
@snky1987 Any updates based on suggestions provided in #919 ?

**Comment by snky1987** [comment]
Hi @anupdugar I know i promissed to do it last week. I have really busy time. Tried to take a look on it today but my ebay project is too expensive to do side tasks. I will come back to it asap (probably this week). I promise :) Cheers.

**Comment by anupdugar** [comment]
@snky1987 Did you get a chance to work on this? If not, maybe we can close this for now and you can create another when the fixes are ready.

**Comment by anupdugar** [comment]
@snky1987 Closing this for now since we haven't heard back in a while.
Feel free to create a PR if you have the suggested improvements ready or any further questions. Thanks again for reporting this!

**Pull request closed without merging**
