### PR TITLE
[32031]Marked Framework Model, Module, Mview and ObjectManager interfaces as API

### LINKED ISSUE #32031: Mark Framework Model, Module, Mview and ObjectManager interfaces as API
The following interfaces should be marked as API in 2.4-develop branch

1. lib/internal/Magento/Framework/Model/Entity/ScopeInterface.php
1. lib/internal/Magento/Framework/Model/Entity/ScopeProviderInterface.php
1. lib/internal/Magento/Framework/Model/EntitySnapshot/AttributeProviderInterface.php
1. lib/internal/Magento/Framework/Model/ResourceModel/Db/VersionControl/RelationInterface.php
1. lib/internal/Magento/Framework/Model/ResourceModel/Type/Db/ConnectionFactoryInterface.php
1. lib/internal/Magento/Framework/Module/ModuleListInterface.php
1. lib/internal/Magento/Framework/Mview/ConfigInterface.php
1. lib/internal/Magento/Framework/Mview/ProcessorInterface.php
1. lib/internal/Magento/Framework/Mview/View/ChangelogInterface.php
1. lib/internal/Magento/Framework/Mview/View/CollectionInterface.php
1. lib/internal/Magento/Framework/Mview/View/State/CollectionInterface.php
1. lib/internal/Magento/Framework/Mview/View/StateInterface.php
1. lib/internal/Magento/Framework/Mview/View/SubscriptionInterface.php
1. lib/internal/Magento/Framework/Mview/ViewInterface.php
1. lib/internal/Magento/Framework/ObjectManager/ConfigCacheInterface.php
1. lib/internal/Magento/Framework/ObjectManager/ConfigInterface.php
1. lib/internal/Magento/Framework/ObjectManager/ConfigLoaderInterface.php
1. lib/internal/Magento/Framework/ObjectManager/DefinitionInterface.php
1. lib/internal/Magento/Framework/ObjectManager/DynamicConfigInterface.php
1. lib/internal/Magento/Framework/ObjectManager/FactoryInterface.php
1. lib/internal/Magento/Framework/ObjectManager/NoninterceptableInterface.php
1. lib/internal/Magento/Framework/ObjectManager/RelationsInterface.php

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixes #32031
### Fixed Issues (if relevant)

1. Fixes magento/magento2#32031>

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE, Integration Tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9030](https://jira.corp.magento.com/browse/ENGCOM-9030) has been created to process this Pull Request

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama the branch with code successfully imported into`magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-32804`.

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama the branch with code successfully imported into`magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-32804`.

**Comment by gabrieldagama** [comment]
This PR has been merged to `api-changes-develop`.

**Pull request closed without merging**
