### PR TITLE
Removed duplicated action group - AdminOpenCMSBlocksGridActionGroup

### LINKED ISSUE #30896: [Issue] Removed duplicated action group - AdminOpenCMSBlocksGridActionGroup
This issue is automatically created based on existing pull request: magento/magento2#30895: Removed duplicated action group - AdminOpenCMSBlocksGridActionGroup

---------
### Description (*)

Removed duplicated action group AdminOpenCMSBlocksGridActionGroup.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by gabrieldagama**
### Description (*)

Removed duplicated action group AdminOpenCMSBlocksGridActionGroup.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30896: Removed duplicated action group - AdminOpenCMSBlocksGridActionGroup

### CODE REVIEW

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento create issue
@magento create issue

**Comment by gabrieldagama** [comment]
@magento run Functional Tests B2B

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8458](https://jira.corp.magento.com/browse/ENGCOM-8458) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
QA not applicable

**Pull request merged**
