### PR TITLE
Fix a misspelled parameter name in TaxTest

### PR DESCRIPTION
**Pull request by akiojalehto**
### Description
Found a misspelled parameter name in \Magento\Weee\Test\Unit\Model\TaxTest::testGetWeeeAmountExclTax

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@akiojalehto could you prepare 1 pull request instead of 16 with all your changes? It will decrease overhead for processing each separate PR by magento team.

**Comment by akiojalehto** [comment]
Sorry I didn't mean to commit so much, but kept finding more of these.. And then I thought that these are in separated contexts that it might make sense to keep these separated.

Don't have anymore for now, if you can process these it might be easier. I will collect these kind of commits in the future for a single PR if I find more.

**Comment by ihor-sviziev** [comment]
@akiojalehto your pull requests actually have 1 context: fixing misspellings in the core. Currently is will not be easy to process 16 PRs, please merge all your changes into 1 PR and it will be processed.

Thank you! 

PS: Here is example of PR that had big list of changes that was successfully processed without any issues: https://github.com/magento/magento2/pull/11235

**Comment by okorshenko** [comment]
Hi @akiojalehto 
Please let us know if you can merge all misspellings Prs into one

**Comment by akiojalehto** [comment]
Sure, I'll try to get it done today

**Comment by okorshenko** [comment]
I'm working on this right now

**Comment by okorshenko** [comment]
All done. Working on PR review and testing

**Review by okorshenko — APPROVED** [review]

**Comment by akiojalehto** [comment]
Nice job, thanks! Sorry for the trouble.

**Comment by okorshenko** [comment]
No problem. Thank you for code cleanup!

**Pull request merged**
