### PR TITLE
Removed Grunt Config Files From gitignore

### PR DESCRIPTION
**Pull request by sprankhub**
### Description (*)
The following two DevDocs posts nicely show how to use Grunt in order to generate the CSS etc.:

* [Using Grunt for Magento tasks](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/tools/using_grunt.html)
* [Compile LESS using Grunt](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/css-topics/css_debug.html)

When working on a Magento 2 project, it makes sense that anyone working on the project uses the same Grunt configuration, so that the CSS is generated in the exact same way. Hence, it makes sense to include Grunt configuration files into git. The file `/dev/tools/grunt/configs/local-themes.js` has already been removed from `.gitignore` in other pull requests (#18960 / #19350). This pull requests removes the remaining Grunt configuration files from the default `.gitignore`.

### Manual testing scenarios (*)
1. Create Magento 2 project.
2. Install and configure Grunt as described in the [DevDocs](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/tools/using_grunt.html#grunt_config).
3. Expected behaviour: Grunt configuration files will be added to git.
4. Actual behaviour: Grunt configuration files are not added to git, because they are included in the default `.gitignore`.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by torhoehn — DISMISSED** [review]
Thanks for your contribution!

**Comment by magento-engcom-team** [comment]
Hi @torhoehn, thank you for the review.
[ENGCOM-5740](https://jira.corp.magento.com/browse/ENGCOM-5740) has been created to process this Pull Request
:eight_spoked_asterisk: @torhoehn, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @sprankhub. Thanks for collaboration. 
This fix is not fully valid. We provide the sample of Gruntfile.js file and package.json, but we don't want to commit it because of users can have their own customization. If you want to add some customization to all members of your team you can just update sample file that will be successfully committed and all team members will have ability yo use it

**Comment by torhoehn** [comment]
@VladimirZaets I think @sprankhub uses the correct way to share the config files. If they follow your suggestion their changes could be gone with the next update of Magento. So his approach will exactly allow to have own customization and even to share it.

**Comment by hostep** [comment]
@VladimirZaets: I agree and this problem could be solved if those lines get removed from the `.gitignore` file which is put in place when running `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition`

That file seems to be slightly different then the one in this repo since it is lacking the line `app/etc/config.php` (based on a vanilla 2.3.2 install vs https://github.com/magento/magento2/blob/2.3.2/.gitignore)

So how is that `.gitignore` file changed? Does that file exists in this repo? Or is it somewhere in some non-public repo? Any chance that repo can get opened so people can also contribute to it?

Thanks!

@torhoehn: I think @VladimirZaets means that Magento devs cloning this repo are also using their own version of those files and they don't want to accidentally commit those files, hence why they are ignored.

**Comment by sprankhub** [comment]
I do not really have anything to add besides the points mentioned by @torhoehn and @hostep. I really think this is the right way. If you are working on a client project, it is vital that any dev can checkout the project and directly work on it without having to copy numerous config files from one place to another.

**Comment by sprankhub** [comment]
@VladimirZaets could you have a look at this pull request again given the feedback from @torhoehn, @hostep and me? Thanks!

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Hi @lenaorobei,
Seems like we need to deliver this fix to composer only installations and keep it as is for GIT repo, but not sure how to do that. Seems like some internal tool should be adjusted instead.

Could you help me with processing this PR?

**Comment by ihor-sviziev** [comment]
@sidolov  any thoughts?

**Comment by sprankhub** [comment]
I see "progress needs update". Anything from my side that can be done to push this forward?

**Comment by ihor-sviziev** [comment]
Maybe @gabrieldagama @sivaschenko ?

**Comment by ihor-sviziev** [comment]
maybe @okorshenko ?

**Comment by sivaschenko** [comment]
@ihor-sviziev @sprankhub this pull request requires technical discussion and approval from our side as there are different points of view regarding the .gitignore content that should be considered.

Since the priority on this pull request was set to P4, I don't think we'll be able to be addressed soon.

Is there any workaround that can solve this issue for developers that require that without the change for everyone? (I.e. using composer post install script)

Do you think the priority should be increased?

**Comment by ihor-sviziev** [comment]
Seems like it’s available only for partners

**Comment by sprankhub** [comment]
I still think this change makes sense - especially for client projects. If you would not like to have it in the general repository, it would indeed make sense to implement it somehow in the repository, which creates the meta packages as suggested by @hostep. However, I do not have access to it.

Since adding the respective lines to the `.gitignore` is kind of obvious and straightforward, I do not think that this needs to be added to the docs. As a reference, this is what we usually append to the default `.gitignore` from Magento:

    !/Gruntfile.js
    !/package.json
    !/grunt-config.json

Feel free to close this PR if you do not want to / "cannot" merge.

**Comment by sivaschenko** [comment]
Hi @sprankhub thank you for the pull request! However, considering there are different opinions about the desired content of gitignore file and estimated low priority/severity of this change I have to close this PR.

**Pull request closed without merging**
