### PR TITLE
magento/magento2#37902: It's time to change the password in the admin…

### LINKED ISSUE #37902: It's time to change your password link not working.
### Preconditions and environment

- Magento 2.4.6

### Steps to reproduce

1. Login to admin panel
2. If your password expired and **Password Change** setting set to **Recommended** you will a message "It's time to change your password." with link.
3. When you click on this link then simply same page will be refreshed.
4. No way to reset password.

### Expected result

It should redirect to reset/change admin password page.

### Actual result

It is not redirecting to reset/change admin password page.Simply refresh admin dashboard page.

### Additional information

In same admin dashboard page if click on user icon then on Account Setting, it directs to reset/change admin password page.
I think issue is in key that is added to link url.

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by BeggiNN**
It's time to change the password in the admin panel. Problem with the link

- Fix 'It's time to change your password' link in admin panel

### Description (*)

When the “Change Password” option is “Recommended” and "Password Lifetime (days)" has expired.
image
The link will not work:
image

### Fixed Issues (if relevant)

1. Fixes magento/magento2#37902

### Manual testing scenarios (*)

1. Login to admin panel
2. If your password expired and Password Change setting set to Recommended you will a message "It's time to change your password." with link.
3. When you click on this link then simply same page will be refreshed.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by BeggiNN** [comment]
@magento run all tests

**Comment by BeggiNN** [comment]
@magento run Unit Tests, Semantic Version Checker, Integration Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by BeggiNN** [comment]
@magento run Functional Tests CE

**Comment by BeggiNN** [comment]
@magento run Functional Tests CE

**Comment by BeggiNN** [comment]
@magento run Integration Tests

**Comment by BeggiNN** [comment]
@magento run Integration Tests

**Comment by BeggiNN** [comment]
@magento run Integration Tests

**Comment by BeggiNN** [comment]
@magento run Integration Tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @BeggiNN,

Thanks for the contribution!

In accordance with [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1), please cover the changes with some automated tests.

Thanks

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Integration Tests,Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Review by engcom-Hotel — APPROVED** [review]
Failed B2b test seems flaky to me. The failures are different in 2 consecutive build runs. Please have a look into the below screenshots:

**Build Run 1**

image

**Build Run 2**
image

Hence approving the PR to process further.

Thanks

**Comment by engcom-Delta** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

1. Login to admin panel
2. Go to Stores-> Configuration -> Advanced-> Admin->Security
3. Make “Change Password” option is “Recommended” and "Password Lifetime (days)" has expired.
4. If your password expired and Password Change setting set to Recommended you will a message "It's time to change your password." with link.
5. Click on the link

**Before:** :heavy_multiplication_x: 

“Change Password” option is “Recommended” and "Password Lifetime (days)" is set to 1

Screenshot 2023-11-21 at 2 20 40 PM

Got link on dashboard. It's time to change your password

Screenshot 2023-11-21 at 2 23 12 PM

No way to proceed

Screenshot 2023-11-21 at 2 23 27 PM


**After:** :heavy_check_mark:  


Screenshot 2023-11-21 at 3 01 51 PM

Account screen appears

Screenshot 2023-11-21 at 3 02 11 PM

Screenshot 2023-11-21 at 3 02 30 PM

Password chosen 

Screenshot 2023-11-21 at 3 08 11 PM

Old password not working

Screenshot 2023-11-21 at 3 08 54 PM

New password worked

Screenshot 2023-11-21 at 3 09 11 PM

Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Comment by cristhianlizcanov** [comment]
Hello, thank you very much I was able to solve it in the administrator part but how to change the password when I log in with a role other than the administrator, when I click on its time change password it redirects me to a page not found and not to the Account Settings of the role

**Pull request merged**
