### PR TITLE
Replace repetitive actions with Action Groups in AdminCreateStoreViewTest

### LINKED ISSUE #34631: [Issue] Replace repetitive actions with Action Groups in AdminCreateStoreViewTest
This issue is automatically created based on existing pull request: magento/magento2#34552: Replace repetitive actions with Action Groups in AdminCreateStoreViewTest

---------

### Fixed Issues (if relevant)
Test is refactored according to the best practices followed by MFTF.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Fixed Issues (if relevant)
Test is refactored according to the best practices followed by MFTF.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#34631: Replace repetitive actions with Action Groups in AdminCreateStoreViewTest

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by shikhamis11** [comment]
@magento create issue

**Comment by shikhamis11** [comment]
@magento run all tests

**Comment by shikhamis11** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Review by shikhamis11 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, thank you for the review.
[ENGCOM-9358](https://jira.corp.magento.com/browse/ENGCOM-9358) has been created to process this Pull Request
:eight_spoked_asterisk: @shikhamis11, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

The PR has updates related to the cod-refactoring in the _app/code/Magento/Store/Test/Mftf/Test/AdminCreateStoreViewTest.xml_ test file. As per the auto-test results, the code changes executed successfully passed.

Since it is an existing test and just has been refactored, no test case creation is required as part of regression testing as well.
Hence approving the changes!
Thanks

**Pull request merged**
