### PR TITLE
Add to Compare link not showing in mobile view under 640px

### PR DESCRIPTION
**Pull request by tejash-wagento**
### Description (*)

On Product detail page Add to Compare link is not showing in mobile view under 640px(@screen__s) resolution

### Fixed Issues (if relevant)

1. magento/magento2#26364: Add to Compare link not showing in mobile view under 640px

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-26365.instances.magento-community.engineering).
Admin access: [https://pr-26365.instances.magento-community.engineering/admin](https://pr-26365.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-6593](https://jira.corp.magento.com/browse/ENGCOM-6593) has been created to process this Pull Request

**Review by ptylek — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-6593](https://jira.corp.magento.com/browse/ENGCOM-6593) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [new Magento instance](https://pr-26365.instances.magento-community.engineering).
Admin access: [https://pr-26365.instances.magento-community.engineering/admin](https://pr-26365.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by engcom-Alfa** [comment]
Hi @tejash-wagento.
Could you fix this issue and for the blank theme?

**Actual Result:**
after

Thanks!

**Comment by ptylek** [comment]
@engcom-Alfa I added fix for blank theme [#26424 ](https://github.com/magento/magento2/pull/26424)

**Review by krzksz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-6593](https://jira.corp.magento.com/browse/ENGCOM-6593) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [new Magento instance](https://pr-26365.instances.magento-community.engineering).
Admin access: [https://pr-26365.instances.magento-community.engineering/admin_f33d](https://pr-26365.instances.magento-community.engineering/admin_f33d)
Login: `81e95436` Password: `4314f8588c1e`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
