### PR TITLE
Fixed issue #27099 - Newsletter Input width issue

### LINKED ISSUE #27099: Newsletter Input width issue.
Newsletter Input width issue.

### Preconditions (*)

Magento 2.3.4

1. When enter wrong email input width increased.

### Steps to reproduce (*)

1. Enter invalid email address in footer newletter.

### Expected result (*)

 image

### Actual result (*)

 image

issues_27099

### PR DESCRIPTION
**Pull request by dipeshrangani**
Newsletter Input width issue.

### Preconditions (*)

Magento 2.3.4

1. When enter wrong email input width increased.

### Reference issue (*)
Fixed #27099 

### Steps to reproduce (*)

1. Enter invalid email address in footer newletter.

### Expected result (*)

 image

### Actual result (*)

 image

### CODE REVIEW

**Comment by rogyar** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-27106.instances.magento-community.engineering).
Admin access: [https://pr-27106.instances.magento-community.engineering/admin_c560](https://pr-27106.instances.magento-community.engineering/admin_c560)
Login: `c088de8d` Password: `8e8b50a57e59`
Instance will be terminated in up to 3 hours.

**Review by rogyar — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7010](https://jira.corp.magento.com/browse/ENGCOM-7010) has been created to process this Pull Request

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @dipeshrangani.
Could you fix it and for the Blank theme in the scope of this PR?
Thanks!

**Comment by dipeshrangani** [comment]
Hi @engcom-Alfa, I have fixed this issue in blank theme as well.
Please review.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7010](https://jira.corp.magento.com/browse/ENGCOM-7010) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:**
_Luma theme_
Peek 2020-05-12 10-30

_Blank theme_
Peek 2020-05-12 10-33

**After:**
_Luma theme_
Peek 2020-05-12 10-47

_Blank theme_
Peek 2020-05-12 10-43

Tested on desktop, mobile, and tablets.

**Pull request merged**
