### PR TITLE
[MFTF] use actionGroup go to new product attribute page

### PR DESCRIPTION
**Pull request by Usik2203**
This PR use `AdminNavigateToNewProductAttributePageActionGroup` to go to NewProductAttributePage instead 
 `<amOnPage url="{{ProductAttributePage.url}}" stepKey="navigateToNewProductAttributePage"/>`
        `<waitForPageLoad stepKey="waitForPageLoad"/>`

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7782](https://jira.corp.magento.com/browse/ENGCOM-7782) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Pull request merged**
