### PR TITLE
Hotfix/27051

### PR DESCRIPTION
**Pull request by RonakParmar**
### Description (*)

Magento Open Source 2.3.3

### Fixed Issues (if relevant)

1. magento/magento2#27051: Saving an attribute with backend_type 'static' will remove the content of the 'frontend_class' field.

### Manual testing scenarios (*)

1)    Navigate to Stores > Attributes > Product
2)   Click an attribute with backend_type = static. Example: sku or category_ids
3)   On the attribute edit page, you can either modify some fields or not modify any field at all.
4)   Click "Save and continue edit".

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @RonakParmar. Thank you for your collaboration. I'm putting it on hold at the moment. Need to discuss the best approach in this case internally.

**Comment by RonakParmar** [comment]
Is anybody guide me to fix the Database Compare and Static Tests ?

Thank you.

**Comment by RonakParmar** [comment]
@rogyar  Is there any update in this PR?

**Comment by rogyar** [comment]
Hi @RonakParmar. We have discussed this change internally. The way of fixing this issue provided in the current PR cannot be accepted as it is. The main problem is, we might not need all possible validation combinations in the dropdown. Moreover, this approach might bring more complexity from the maintenance perspective. Imagine that in the future there will be tens of different length validations. 

The best way here is to consider preserving the frontend class value in the database upon the attribute edit process if there's no such frontend class in the dropdown instead of setting it to NULL.

**Comment by VladimirZaets** [comment]
@RonakParmar , I am closing this PR now due to inactivity.
Please reopen if you wish to continue and refactor it according to changes that are requested by @rogyar . If you need some help or clarification feel free to ping me or @rogyar. 
Thank you for collaboration

**Pull request closed without merging**
