### PR TITLE
CMS page URL rewrite deletion in setup area

### PR DESCRIPTION
**Pull request by CNanninga**
Added CMS page URL rewrite plugin to setup area as well, so that deletion of URL rewrites will occur there

### CODE REVIEW

**Comment by Vinai** [comment]
Thank you for the PR! We are currently waiting for the travis builds to work again, which should happen in a few days. Once that is running and the tests are green we can continue to process your contribution.
In the mean time, can you please sign the contributor license agreement?

**Comment by CNanninga** [comment]
Done!

**Comment by CNanninga** [comment]
Just discovered that, while this fix is definitely needed, it still does not result in the deletes being run properly, because a "setup" area is never defined to load XML files from.  See issue #2725.

**Comment by KrystynaKabannyk** [comment]
Hello @CNanninga, can you please update the code and cover it by Travis tests?

**Comment by vkublytskyi** [comment]
Closed as issue #2725 already fixed

**Pull request closed without merging**
