### PR TITLE
Better error message on failed customer login

### PR DESCRIPTION
**Pull request by kolaente**
### Description (*)

Previously,  the user would just see the message "The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later." which is irritating for the user. We had customers complain about this when their account was unlocked, but they entered a bad password.
This PR changes this, so the user sees a more clear message "Invalid login or password.".

### Manual testing scenarios (*)

1. Enter incorrect customer login information, from a customer who is unlocked
2. See "Incorrect login or password." message

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by kolaente** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @kolaente. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @kolaente, here is your [new Magento instance](https://pr-25342.instances.magento-community.engineering).
Admin access: [https://pr-25342.instances.magento-community.engineering/admin](https://pr-25342.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by VladimirZaets** [comment]
Hi @kolaente, thanks for the collaboration. We don't need to have this message, we have 2 reasons for this:
1) Your message provides information is account exists
2) Our PO decided to use the general message for all cases related to the wrong authorization.

According to it, I close this PR

**Comment by kolaente** [comment]
Hi @VladimirZaets,
since the registration form tells me if an account exists, that is not something I would hide from the sign in form: 
grafik

The error message is only misleading for end users. It does not provide useful information when an account is not locked, but the user only entered the wrong email or password. This happened to us, we had customers of the shop call and complain multiple times their account was locked when they only entered the wrong password.

**Comment by amenk** [comment]
please reopen  @VladimirZaets

The security argument is invalid..there is even an easy to use guest API endpoint for those who want to harvest existing customer email addresses.

https://devdocs.magento.com/redoc/2.3/async-guest-rest-api.html#tag/customersisEmailAvailable

**Pull request closed without merging**
