### PR TITLE
fixes-customer-information-wishlist-configurable-product-alignment

### PR DESCRIPTION
**Pull request by priti2jcommerce**
### Description (*)
admin customer information wishlist configurable product alignment issue while editing
Magento 2.3.0

### Fixed Issues (if relevant)

1. magento/magento2#20760
2. ...
### Manual testing scenarios (*)

1. Go to admin
2. In Customers >>All customers>> edit customer>>click on wishlist
3. Action Configure

### Expected result (*)
2019-01-24_11-44_p d - customers - customers

### Actual result (*)
2019-01-24_11-42_p d - customers - customers

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by priti2jcommerce** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by federivo** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @federivo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @federivo, here is your [Magento instance](https://i-20558-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20558-2-3-develop.instances.magento-community.engineering/admin](https://i-20558-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by federivo — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @federivo, thank you for the review.
[ENGCOM-4053](https://jira.corp.magento.com/browse/ENGCOM-4053) has been created to process this Pull Request

**Comment by federivo** [comment]
@priti2jcommerce thank you for your contribution. 
When merged, consider back-porting this to 2.2. You can easily achieve it using the Porting Tool, [check here](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#porting-tool).

**Comment by priti2jcommerce** [comment]
Hi @federivo ,

Thanks for update

**Pull request merged**
