### PR TITLE
Region field required validation based on country: For admin order create area

### PR DESCRIPTION
**Pull request by viral-wagento**
### Description

When we create an order from Admin, check into 'Address Information' - Billing/Shipping Address Section, Region field is displayed as Required Field for all countries. It should be required for only those countries- which are set under - Stories -> Configuration -> General -> General -> State Options.

### Fixed Issues (if relevant)

1. magento/magento2#17311: Region is always required when creating a new order in the Admin area

### Manual testing scenarios

1. Have a clean Magento 2.2.5 install (composer create-project)
2. In the Admin area go to Sales -> Orders
3. Click "Create New Order"
4. Click "Create New Customer"
5. State/Province is mandatory as the selected country is United States
6. Change country to "The Netherlands" (Where state/province isn't mandatory)
7. State/Province is still required

### Actual Result
Region field displayed as required for all countries.

### Expected Result
Region field should only be required for countries selected under Stories -> Configuration -> General -> General -> State Options.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @viral-wagento. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by viral-wagento** [comment]
@magento-engcom-team give me test instance for this PR

**Comment by magento-engcom-team** [comment]
Hi @viral-wagento. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @viral-wagento, here is your [new Magento instance](https://pr-17404.engcom.dev.magento.com).
Admin access: [https://pr-17404.engcom.dev.magento.com/admin](https://pr-17404.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`

**Comment by VladimirZaets** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, here is your [Magento instance](https://i-17404-2-2-develop.engcom.dev.magento.com).
Admin access: [https://i-17404-2-2-develop.engcom.dev.magento.com/admin](https://i-17404-2-2-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by VladimirZaets** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, here is your [Magento instance](https://i-17404-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17404-2-2-5.engcom.dev.magento.com/admin](https://i-17404-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by VladimirZaets** [comment]
Hi @viral-wagento. Thanks for the collaboration. 
The issue magento/magento2#17311 was already fixed by the internal team and currently don't reproduces in the current 2.2-develop (2.2.6) branch.

**Pull request closed without merging**
