### PR TITLE
Add missing annotations to MFTF tests

### PR DESCRIPTION
**Pull request by sta1r**
### Description (*)

This PR addresses a number of `DEPRECATION:` notices raised when running MFTF tests. 

The notices related to missing `stories` and `severity` annotations. I've tried wherever possible to follow the lead of sibling tests e.g. if a test has no `severity` annotation and all the other tests in its folder say `<severity>CRITICAL</critical>`, also mark as critical. 

### Questions or comments

It's worth noting that the devdocs:
- don't advise on differences in [severity](https://devdocs.magento.com/mftf/docs/test/annotations.html#severity) grade 
- don't really clarify the distinction between (or hierarchy of) [stories](https://devdocs.magento.com/mftf/docs/test/annotations.html#severity) and [features](https://devdocs.magento.com/mftf/docs/test/annotations.html#features)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
Covered already in https://github.com/magento/magento2/pull/26391/files - I'd like to keep your PR to cover elements that are not covered by above mentioned PR.

**Review by lbajsarowicz — CHANGES_REQUESTED** [review]
Waiting for https://github.com/magento/magento2/pull/26391/files to be merged, then resolve conficts.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @sta1r,
Could you please resolve conflicts?

**Comment by sta1r** [comment]
@ihor-sviziev conflicts resolved!

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6975](https://jira.corp.magento.com/browse/ENGCOM-6975) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Pull request merged**
