### PR TITLE
Issue #20631 Fixed.

### PR DESCRIPTION
**Pull request by mahesh-rajawat**
Fixed checkout shipping page issue #20631 

### Description (*)

Console error on checkout after changing the allowed countries from admin.
### Fixed Issues (if relevant)

1. #20631 
2. ...

### Manual testing scenarios (*)

1. Add a product to cart as guest.
2. Fill the shipping address and reload the page now shipping address must be filled already.
3. Go to Admin->Stores->configuration->General, Change allowed countries single one that is not filled on checkout. like i have filled United State at checkout and change allowed countries to Libya.
4. Now reload the checkout shipping page again.

Now there is no console error.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by novikor** [comment]
@maheshWebkul721 , please squash your commits (merge with 2.3 and fix inself) into one.
Also please create a port of this Pull Request for 2.2-develop.

Thank you.

**Review by novikor — CHANGES_REQUESTED** [review]
@maheshWebkul721 , please squash your commits (merge with 2.3 and fix inself) into one.
Also please create a port of this Pull Request for 2.2-develop.

Thank you.

**Comment by ghost** [comment]
Hi @maheshWebkul721, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+magento2+20632), it will take less than a minute. </br>Your feedback will help us to improve contribution process.

**Comment by mahesh-rajawat** [comment]
@novikor, i tried to sqash all commits but not able to do it, could you please suggest me some commands, so i can create a new PR. i think i made some mistake with this PR

**Pull request closed without merging**
