### PR TITLE
Fixing getUrl() function

### LINKED ISSUE #30567: Get Product Url function is returning a url with 301 redirect type instead of url with redirect type of 0
### Preconditions (*)

1. Magento 2.3.6
2. PHP 7.3
3. Mysql 5.7.31

### Steps to reproduce (*)

1. Create a product
2. Modify product Url with auto create 301 url redirects let's say the old url is "my-new-product" the new one is "my-new-product-2"
3. Now try to get that product with collection and call getProductUrl() function

### Expected result (*)

1. Product url  = my-new-product-2

### Actual result (*)

1. Product url  = my-new-product

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by amine-y**
### Description (*)

This PR will fixe a problem releated to getProductUrl() function to get the url without a 301 redirect but the url with redirect type of 0 
### Fixed Issues (if relevant)

1. Fixes magento/magento2#30567

### Manual testing scenarios (*)

1. Change product url from admin with generate 301 on and try to get with getProductUrl()
2. The new Url is returned

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by amine-y** [comment]
@magento give me test instance

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @amine-y,
Good catch! Could you cover your changes with integration test?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by amine-y** [comment]
@ihor-sviziev 
> Hi @amine-y,
> Good catch! Could you cover your changes with integration test?

ok I will create tests for it

**Comment by ihor-sviziev** [comment]
@amine-y,
Will you be able to update your PR with suggested changes? Maybe you have some questions or need some help?

**Comment by amine-y** [comment]
@ihor-sviziev Sorry for the late response, for the unit tests I can't create them

**Comment by ihor-sviziev** [comment]
Hi @engcom-Charlie @engcom-Delta @engcom-Hotel could you help with covering test with automated tests?

**Comment by engcom-Hotel** [comment]
I will help.

**Comment by amine-y** [comment]
@engcom-Hotel You need to have many 301 redirects for the product then try to use the getUrl function and it will give you the URL with 301 not a direct URL to the product

**Comment by engcom-Hotel** [comment]
@amine-y are you able to reproduce it on 2.4-develop version?

**Comment by amine-y** [comment]
@engcom-Hotel I only test it on Magento 2.3.6 currently I didn't test it on 2.4-develop version

**Comment by engcom-Hotel** [comment]
@amine-y Could you please check it on 2.4-develop and let me know if you can reproduce the issue.

**Comment by engcom-Hotel** [comment]
I have tested the issue via integrational test for your PR.
How to setup and run it you can find here:
https://devdocs.magento.com/guides/v2.4/test/integration/integration_test_execution.html#configure-the-framework-for-test-environment

[30580_test.zip](https://github.com/magento/magento2/files/5623818/30580_test.zip)

**Comment by engcom-Hotel** [comment]
Hello @amine-y .
Closing due to inactivity.
Please feel free to reopen it and provide steps to reproduce.
Thank you.

**Comment by amenk** [comment]
It is still an issue in latest develop

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/ResourceModel/Product/Collection.php#L1483

Depending on the order of the url_rewrites when there are multiple entries with the same product ID, it might return a redirected URL. In most cases such a redirected URL is not a problem, but it is very inefficient to not return the final URL but a URL which itself is redirected.

Please reopen.

**Comment by ihor-sviziev** [comment]
@amenk do you have some specific steps to reproduce on clean mangento installation? If so - please provide them

**Comment by amenk** [comment]
@ihor-sviziev Thanks for your response.

No, I did not reproduce this on a clean installation

I do understand that each issue has to be reproduced before a pull request can be approved, but I suggest to also just look at the code here: It is pretty clear to see, that also 301 redirects might and up in the product URL results and we have to ask ourselves if this makes sense.

Most of the time there will not be a visible problem, because the URLs are forwarded automatically. So is it intended the getProductUrl() returns not the direct URL or is this a glitch?

What do you think?

**Comment by ihor-sviziev** [comment]
@amenk, unfortunately, w/o steps to reproduce, it's hard to identify if the fix is correct. There is a chance that we already fixed the issue, so we may fix the data in the DB using the migration script. Does it make sense? 

Thank you!

**Comment by amenk** [comment]
@magento give me test instance

**Comment by amenk** [comment]
@ihor-sviziev The funny part is there were already tests created in https://github.com/magento/magento2/pull/30580#issuecomment-736649030

I am wondering if those failed without the patch or they didn't

**Comment by amenk** [comment]
@magento give me 2.4-develop instance

**Comment by ihor-sviziev** [comment]
@amenk if I got correctly, the issue was NOT reproducible in 2.4-develop branch using these tests.

**Comment by amenk** [comment]
@ihor-sviziev 
Yes you are right.
It's not simply reproducible by

1. Change URL of duffle-bag with redirect checkbox on to new-url
2. View bags category
3. Now the URL is "new-url" as expected

Things become interesting when we delete the rewrite entry for "new-url.html"

Now duffle bag indeed links to the 301 URL which try to redirect to new-url.html

https://9c574843abd546ed09a6214852e015e2-2-4-develop.instances.magento-community.engineering/gear/bags.html?p=2

And we have a 404 even

On the instance of this PR we at least have the non-SEO-URL and the page can be opened

https://9c574843abd546ed09a6214852e015e2.instances.magento-community.engineering/

I believe this problem does not appear ofen, because in standard cases Magento writes first the new URL and then the redirects. But if there are changes on the redirect table (let it be through imports or more complex scenarios) problems can appear.

The fix is easy though and should be merged.

**Comment by amenk** [comment]
Instance of this PR:

ksnip_tmp_aYMLPC

2.4-develop:

ksnip_tmp_ALgFsp
ksnip_tmp_PLSBTz

**Comment by ihor-sviziev** [comment]
@amenk, so if I got it correctly - the steps to reproduce should be following:
1. Install Magento with sample data
2. Go and change the URL key for `24-MB01` to `new-url` in the admin
3. Go and delete URL rewrite with request path = `/new-url.html` (failure emulation during URL rewrite regeneration)
4. Go to frontend -> /gear/bags.html?p=2
5. Click "Joust Duffle Bag"

**Expected result**
✔ You should see the product page
✔ On the category page, the product URL should be like `catalog/product/view/id/1/s/new-url/category/4/` because we removed URL rewrite in step 3.

**Actual result**
❌ You see the 404 page
❌ On the category page, the product URL is an old URL path (which then has 301 redirects to the new URL)

Potentially this issue might happen if some failure, such as server restart during URL generation or some 3rt party integration issue.

**Comment by amenk** [comment]
@ihor-sviziev Yes, thanks.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9097](https://jira.corp.magento.com/browse/ENGCOM-9097) has been created to process this Pull Request

**Comment by amenk** [comment]
The fix is not working in some cases (when working with collections).

The filter redirect_type=0 has to be added here as well

https://github.com/magento/magento2/blob/aff512bfaaa28db2000c1ebcb29b9d2e0a23cc48/app/code/Magento/Catalog/Model/ResourceModel/Product/Collection.php#L1487

**Comment by Den4ik** [comment]
What about MFTF test for this fix?

**Comment by engcom-Hotel** [comment]
:x: QA not Passed

Hello @amine-y,

Thank you for the contribution!

I am able to reproduce the issue in Magento 2.4-develop branch using steps mentioned in [Comment](https://github.com/magento/magento2/pull/30580#issuecomment-842315832). Please refer below screenshot for reference:

Screenshot 2021-08-18 at 9 41 36 PM

404 Page:

image


But when I tried to deploy this build on my local machine, I am getting the below error when trying to run `composer install` command. Please find below the screenshot for reference:

Screenshot 2021-08-18 at 9 46 37 PM

Please fix this issue so that we can continue with the testing.

Thanks

**Comment by ihor-sviziev** [comment]
Hi @engcom-Hotel, could you try again after merging the recent changes?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Hello @ihor-sviziev,

Thanks for your reply!

I will try again after merging.

Thanks

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9097](https://jira.corp.magento.com/browse/ENGCOM-9097) has been created to process this Pull Request

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9097](https://jira.corp.magento.com/browse/ENGCOM-9097) has been created to process this Pull Request

**Comment by engcom-Hotel** [comment]
✔️ QA Passed

Hello @amine-y,

I have tested all the possible scenarios manually related to PR. 

**Preconditions **
- Magento 2.4-develop
- PHP 7.4
- Mysql 5.7.31

**Manual Testing Scenarios **

- Change the URL Key for a product from the admin panel for e.g. new-url 
- Delete the value from database table url_rewrite with request path = /new-url.html
- Clear the cache using the `bin/magento c:f` command
- Check the product listing page from the front-end
- Click on the product for which URL key has been updated from the admin panel.
- Verify if there is no 404 page and a proper product detail page should render.

**Note**
The product URL remains the same for e.g. `http://local.magento30580.com/new-url.html`

**Actual Result ✔️ **
Verified that the 404 page should not render and a proper product detail should render.

**After ✔️ **
Screenshot 2021-08-24 at 9 40 49 PM

**Before ✖️ **
Screenshot 2021-08-24 at 9 42 17 PM


**Tested all the manual scenarios, no impact on regression testing.**

**Pull request closed without merging**
