### PR TITLE
Remove deprecated methods

### PR DESCRIPTION
**Pull request by AnshuMishra17**
### Description (*)
Replaced deprecated methods addError and addSuccess with addErrorMessage and addSuccessMessage respectively.

### Manual testing scenarios (*)
1. Submit email to friend form from frontend.
2. Ran PHPUnit tests for SendFriend module.

### CODE REVIEW

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5200](https://jira.corp.magento.com/browse/ENGCOM-5200) has been created to process this Pull Request

**Comment by orlangur** [comment]
@AnshuMishra17 are these the only occurrences left? Do we have a test enforcing no old methods are used?

**Comment by AnshuMishra17** [comment]
@orlangur I have checked and there are more occurrences of methods addError and addSuccess.
I am not sure regarding testing no old methods are used.

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Review by orlangur — CHANGES_REQUESTED** [review]
@AnshuMishra17 we don't need changes in one file only, please prepare a full changeset similar to https://github.com/magento/magento2/pull/22703

**Comment by AnshuMishra17** [comment]
@orlangur Sure, I will make the changes and update the PR.

**Comment by sidolov** [comment]
@AnshuMishra17 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
