### PR TITLE
Allow more htmlClasses

### LINKED ISSUE #36891: [Issue] Allow more htmlClasses
This issue is automatically created based on existing pull request: magento/magento2#36452: Allow more htmlClasses

---------
Follow-up on #34559
Supports classes like `w-screen left-1/2 right-1/2 mx-[-50vw] relative` as used in Tailwind 3
See https://regexr.com/72318 vs https://regexr.com/72315

### PR DESCRIPTION
**Pull request by barryvdh**
Follow-up on #34559
Supports classes like `w-screen left-1/2 right-1/2 mx-[-50vw] relative` as used in Tailwind 3
See https://regexr.com/72318 vs https://regexr.com/72315

### Resolved issues:
1. [x] resolves magento/magento2#36891: Allow more htmlClasses

### CODE REVIEW

**Comment by Vinai** [comment]
Note: `-screen left-1/2 right-1/2 mx-[-50vw] relative` are all usable in tailwind v2, too (`mx-[-50vw]` only with the JIT)

**Comment by mrtuvn** [comment]
nice to see some class tailwind arbitrary values variants

**Comment by in-session** [comment]
@berryvdh can you make also a new pull for https://github.com/magento/magento2-page-builder/pull/791

**Comment by barryvdh** [comment]
@in-session can you update your PR as it's not merged yet?

**Comment by mattgrul** [comment]
@barryvdh The follwoing arbitrary values fail with this updated version - `grid-rows-[auto 1fr]`

Using only one value with no space within the square brackets seems to work however - `grid-rows-[auto]`

**Comment by barryvdh** [comment]
@mattgrul I'm not sure if that class is valid, but maybe we don't need such strict validation and just allow classes with `([a-zA-Z\d\-_/:.\[\]] *)*` ?

https://regexr.com/737mk

**Comment by barryvdh** [comment]
Do we even need validation at that point 😓 
https://regexr.com/73fp6 with `[a-zA-Z\d\-_/:.\[\]\&() ]*` ?

**Comment by jissereitsma** [comment]
@barryvdh In some CSS frameworks, the `@` character is also used for CSS classes. Would it be an idea to include that character as well in your PR?

**Comment by barryvdh** [comment]
Sure thing

**Comment by Tjitse-E** [comment]
@barryvdh  the commit that adds the at (@) sign seems breaks XML parsing:
```
Element '{http://www.w3.org/2001/XMLSchema}redefine': Failed to parse the XML resource 'urn:magento:framework:View/Layout/etc/elements.xsd'.
Line: 10
```

Error: Unescaped & or non terminated character/entity reference. 

This seems to be the correct way of escaping the at sign: `[a-zA-Z\d\-_/:.\[\]&amp;@() ]*`. Could you verify that?

**Comment by barryvdh** [comment]
Ugh, I think `[a-zA-Z\d\-_/:.\[\]\\&amp;@() ]*` ?

**Review by Tjitse-E — APPROVED** [review]

**Comment by eduard13** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Lima** [comment]
Hi @barryvdh ,

Thanks for your contribution and collaboration.

I have tried to reproduce the issue in latest **`2.4-develop`** but issue is not reproducible to me.
I have tried to revert back the changes given in the [PR](https://github.com/magento/magento2/pull/34559) and followed [steps to reproduce](https://github.com/magento/magento2/pull/34559#issuecomment-1001438406) the issue but issue is not reproducible to me.
Kindly provide me information whether I am missing any thing. Also, please provide us information in order to reproduce the issue.

Thanks

**Comment by engcom-Charlie** [comment]
Hi @barryvdh,

Thank you for your contribution!

I have tried to reproduce this issue in latest magento 2.4-develop, followed below steps, but the issue is not reproducible for us.

1. Adding htmlClass="product-info-main w-screen left-1/2 right-1/2 mx-[-50vw] relative md:max-w-2xl" in app/code/Magento/Catalog/view/frontend/layout/catalog_product_view.xml file 
2. Deploy static content and flush cache
We are not getting any error on content deploy as well as on Product page.

Can you please let us know if we are missing anything in order to reproduce. We are waiting for your feedback on above [comment](https://github.com/magento/magento2/pull/36452#issuecomment-1422331036) too, till then moving it to On hold.

Thank you!

**Comment by hostep** [comment]
@engcom-Charlie: make sure you are running in `developer` mode, if you are running in `production` mode the error doesn't show up. Also make sure your caches are flushed just before visiting the product page.

I just tested it on a clean Magento from 2.4-develop, steps to reproduce:
- setup clean magento
- run `bin/magento deploy:mode:set developer`
- setup a category and product in the backoffice so you have something to go to on the frontend
- make a change like this:
```diff
diff --git a/app/code/Magento/Catalog/view/frontend/layout/catalog_product_view.xml b/app/code/Magento/Catalog/view/frontend/layout/catalog_product_view.xml
index 6e24f84f004..136bc5081f7 100644
--- a/app/code/Magento/Catalog/view/frontend/layout/catalog_product_view.xml
+++ b/app/code/Magento/Catalog/view/frontend/layout/catalog_product_view.xml
@@ -36,7 +36,7 @@
         </referenceBlock>

         <referenceContainer name="content">
-            <container name="product.info.main" htmlTag="div" htmlClass="product-info-main" before="-">
+            <container name="product.info.main" htmlTag="div" htmlClass="product-info-main w-screen left-1/2 right-1/2 mx-[-50vw] relative md:max-w-2xl" before="-">
                 <container name="product.info.price" label="Product info auxiliary container" htmlTag="div" htmlClass="product-info-price">
                     <container name="product.info.stock.sku" label="Product auxiliary info" htmlTag="div" htmlClass="product-info-stock-sku">
                         <container name="product.info.type" before="-"/>
```
- reindex + flush caches
- visit the product on the frontend
- you'll get an error like this:
```
1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'container', attribute 'htmlClass': [facet 'pattern'] The value 'product-info-main w-screen left-1/2 right-1/2 mx-[-50vw] relative md:max-w-2xl' is not accepted by the pattern '[a-zA-Z][a-zA-Z\d\-_:]*(\s[a-zA-Z][a-zA-Z\d\-_:]*)*'.
Line: 800
```

With the changes proposed here in this PR and another cache flush, the error no longer happens.

**Comment by engcom-Charlie** [comment]
Hi @hostep,

Thank you for your guidance and contribution!

I have tested this PR as mentioned in above comment, the issue is reproducible and the solution given in this PR is working fine. Followed below steps.

:heavy_check_mark: QA Passed

**Manual Scenario Steps**
- setup magento
- run bin/magento deploy:mode:set developer
- created product in admin
- make a below changes:
Adding htmlClass="product-info-main w-screen left-1/2 right-1/2 mx-[-50vw] relative md:max-w-2xl" in app/code/Magento/Catalog/view/frontend/layout/catalog_product_view.xml file

- Reindex and flush cache
- Visit the created product on storefront

**Before:** :heavy_multiplication_x: 
image


**After:** :heavy_check_mark: 
image

Thank you!

**Comment by engcom-Charlie** [comment]
The functional test failure is not related to PR or not failing because of PR changes hence moving this to Merge in Progress.

**Functional test B2B**
image

**Comment by engcom-Lima** [comment]
@magento create issue

**Pull request merged**
