### PR TITLE
Add additional check if password hash is empty in auth process

### PR DESCRIPTION
**Pull request by progreg**
### Description

Added additional check for password hash if the customer was created without a password from admin area.

### Fixed Issues

1. magento/magento2#19060: User created by admin cannot login

### Manual testing scenarios

1. Create customer at admin area (without password)
2. Try to login at frontend as a customer

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @progreg. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3390](https://jira.corp.magento.com/browse/ENGCOM-3390) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @progreg. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Review by salehawal — COMMENTED** [review]
i also found a isue in this methud, after changing the return value format it did work fine

    public function isValidHash($password, $hash)
    {
        $this->explodePasswordHash($hash);

        foreach ($this->getPasswordVersion() as $hashVersion) {
            $password = $this->hash($this->getPasswordSalt() . $password, $hashVersion);
        }

        $hash = $this->getPasswordHash();
        return Security::compareStrings(
            $password,
            $hash
        );
    }

**Pull request merged**
