### PR TITLE
Fixed incorrect price of customizable options shown below "Customer Activities" #26101

### LINKED ISSUE #26101: Customizable Options Price
There is an issue when creating a backend order, with a product that has Customizable Options. Moving the product to the Wishlist or Cart does not keep the price of the selected options. Although the correct price is shown for the customer in the Frontend, the sidebar shows the incorrect price.

### Preconditions (*)
1. Magento 2.3
2. Product with 1 or more Customizable Options with a fixed or percentage price

### Steps to reproduce (*)
1. Log in to the backend
2. Sales > Orders > Create New Order
3. Select Customer
4. Click Add Products
5. Find product with Customizable Options
6. Click Configure
7. Select Option that will increase price
8. Click OK
9. Click Add Selected Product(s) to Order
10. The price shown should include the Option price
11. Select Move to Wishlist form the Action drop-down
12. Click Update Item and Quantities

### Expected result (*)
The price shown in the left sidebar, should be that of the selected option

### Actual result (*)
The price shown is the base price of the product and does not include the selection price

### Additional Information
https://github.com/magento/magento2/issues/26101#issuecomment-570705209
https://github.com/magento/magento2/issues/26101#issuecomment-631541616
Update:
On Storefront in customers shopping cart price showing correctly (PRD+opt) https://github.com/magento/magento2/issues/26101#issuecomment-632332366

### PR DESCRIPTION
**Pull request by Serializator**
### Description (*)
Use the `getFinalPrice()` on the product model instead of using the price info model to get the final price, it didn't seem the include the price of each customized option in the final price.

Refactor the implementation of the block for the "Shopping Cart" list below "Customer Activities" so that it uses the parents implementation if no custom price is found, this way I didn't have to duplicate the changes from the parent block.

### Fixed Issues (if relevant)
1. fixes magento/magento2#26101: Customizable Options Price

### Manual testing scenarios (*)
1. Create a product with at least one customizable option
2. Create a customer
3. Sales > Orders > Create New Order
4. Choose your customer
6. Add your product with at least one customizable option
7. "Items Ordered > Action > Move to Wishlist > Update Items and Quantities"
8. "Price" in the left sidebar underneath "Wish List" should include the price of the customizable option

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Serializator** [comment]
Hi @joni-jones,

I've signed the Adobe CLA and resolved the conflict.

Kind regards,
Julian

**Comment by Serializator** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
@magento run all tests

**Review by sidolov — CHANGES_REQUESTED** [review]
@Serializator could you please take a look at failed tests?

**Comment by gabrieldagama** [comment]
Risk is set to low since the changes may not affect other areas.

**Comment by engcom-Charlie** [comment]
@Serializator could you please fix static tests?
Thank you.

**Comment by engcom-Charlie** [comment]
@Serializator I'll fix static tests.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by Serializator** [comment]
Thank you @engcom-Charlie, I totally  forgot about this PR. What is the status of the review?

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
Hello @Serializator,

Please resolve the conflicts, so that we can move further with this PR for review.
image


Thanks

**Comment by engcom-Dash** [comment]
@Serializator - Closing this PR due to no response to the last https://github.com/magento/magento2/pull/26257#issuecomment-2352765871. Feel free to reopen it.

**Pull request closed without merging**
