### PR TITLE
Fix incorrect logo on order print page

### LINKED ISSUE #34942: The default luma logo is shown on frontend order print page
During migration from Magento 2.3.x to 2.4.3-p1 we noticed an issue - the print order/invoice/credit memo pages (on frontend) started showing a default luma logo instead of the logo that is shown on the entire website.

### Preconditions (*)

1. Magento 2.4.3
2. Luma theme
3. Set custom logo in the header on the frontend

### Steps to reproduce (*)
1. Go to the frontend
2. Place some order
3. On the frontend go to My Account > My Orders > View Order > Print Order

### Expected result (*)
1. If you explicitly defined a custom logo for emails - that logo should be shown (the highest priority) - Config path `sales/identity/logo_html`
2. If you specified a custom frontend logo - that logo should be shown (medium priority) - Config path `design/header/logo_src`
2. If you didn't specify both custom logo for emails and frontend logo - the default luma should be shown (the lowest priority)
**The same flow should be for invoices and credit memos.**

### Actual result (*)
1. If you explicitly defined a custom logo for emails - that logo should be shown (the highest priority) - ✔ works fine
2. If you specified a custom frontend logo  - that logo should be shown (medium priority) - ❌ doesn't work, but worked on Magento 2.3.7-p2.
3. If you explicitly defined a custom logo for emails - that logo should be shown (✔ works fine)

### Additional info
The issue appeared after the following commit: https://github.com/magento/magento2/commit/4531c763b5afad4af054bf5dce14669dce0c49ee
It had to fix the case when the first option didn't work fine.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)

This PR adds a fallback to a header logo in case if the sales HTML logo() isn't declared.
Originally the issue was introduced in https://github.com/magento/magento2/commit/4531c763b5afad4af054bf5dce14669dce0c49ee

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/34942

### Manual testing scenarios (*)

1. See linked issue description

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by Den4ik — CHANGES_REQUESTED** [review]
Hi @ihor-sviziev.
Thanks for the good fix.

I believe that we could inject theme `LogoPathResolver` as fallback class and call `getPath` instead of duplicate part of code.
What do you think?

**Comment by ihor-sviziev** [comment]
@Den4ik I thought about it as well, but it doesn't get store id from the current order, but from the store manager (there might be some edge cases when you're in admin, for instance), so I decided to do it like that.

**Comment by Den4ik** [comment]
@ihor-sviziev Wrote direct message in slack

**Comment by ihor-sviziev** [comment]
As we discussed in Slack - it might be improved to reduce the code duplication, but I don't have enough time for that now.

**Comment by engcom-Lima** [comment]
Since all the builds are passed moving it to Pending Review column.

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9400](https://jira.corp.magento.com/browse/ENGCOM-9400) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Pull request merged**
