### PR TITLE
MFTF: Extract Action Groups to separate files - magento/module-customer

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Extract each Action Group to separate file, to follow MFTF Best Practices.

### Related Pull Requests
https://github.com/magento/partners-magento2b2b/pull/51

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/26331

### Questions or comments
Had to extract the changes per-module. The previous try failed, because of conflicts.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
Dear Maintainers, due to your concerns about **backward compatibility**, I provided the `_Deprecated_ActionGroup.xml` that provides the deprecated ActionGroups that will be loaded like before, but extra **comment** was added to notify about **depreciation**.

Hope that will let you merge that sooner than with `2.4`

**Comment by torhoehn** [comment]
@lbajsarowicz Could you please check why the tests are failing in this PR?

**Comment by lbajsarowicz** [comment]
@torhoehn Fixed. When moving Action Groups from multiple files into single file, the duplicated ones were revealed.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6426](https://jira.corp.magento.com/browse/ENGCOM-6426) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by VladimirZaets** [comment]
Hi @lbajsarowicz. Please fix action group usage in EE/B2B versions and MSI/Page-builder extensions.

**Comment by lbajsarowicz** [comment]
@VladimirZaets Merged latest `2.4-develop` that fixed the issues.

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests B2B

**Comment by lbajsarowicz** [comment]
Merged latest `2.4-develop`, fixed conflicts.
I hope that after 4 months it will be merged.

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests B2B

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests B2B

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests B2B

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests B2B

This is ridiculous. December, January, February...

**Comment by lbajsarowicz** [comment]
@magento run all tets

Maybe today?

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests B2B
:pray: :pray: :pray:

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests B2B

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests B2B

image

**Comment by lbajsarowicz** [comment]
@magento run all tests

The issue was related to missing change for B2B module

**Comment by lbajsarowicz** [comment]
@magento run all tests

Added missing Copyright to B2B file.

**Comment by lenaorobei** [comment]
⚠️ Delivery notes: run with `pb` and `pb-ee`.

**Review by lenaorobei — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-6426](https://jira.corp.magento.com/browse/ENGCOM-6426) has been created to process this Pull Request

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-6426](https://jira.corp.magento.com/browse/ENGCOM-6426) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Pull request merged**
