### PR TITLE
Updated pdepend/pdepend package to 2.9.1

### PR DESCRIPTION
**Pull request by konarshankar07**
### Description (*)

Updated pdepend/pdepend package to 2.9.1

### Fixed Issues (if relevant)

Fixes magento/magento2#32867

### Related Pull Requests
https://github.com/magento/magento2/pull/33225

### CODE REVIEW

**Comment by konarshankar07** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
Are there any partner contributors voluteers to collaborate on this PR and create corresponding EE PR to fix static tests?

Added "help wanted" label for this purpose

**Comment by sivaschenko** [comment]
Removed "help wanted" label, as @drpayyne has joined to help on commerce repo side and created a needed EE PR

**Comment by rogyar** [comment]
@magento run Functional Tests CE Functional Tests EE Functional Tests B2B

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @konarshankar07. May I ask you to resolve the conflicts, please? Thank you.

**Comment by andrewbess** [comment]
Closing this pull request in favour of PR containing update to the newer dependency version: https://github.com/magento/magento2/pull/33569

**Pull request closed without merging**
