### PR TITLE
Fix: #20379 Calendar icon not aligned inside the textbox in Add Design Change page

### PR DESCRIPTION
**Pull request by irajneeshgupta**
### Description (*)

Changed class `admin__scope-old` to `form-inline`.

### Fixed Issues (if relevant)

1. magento/magento2#20379: Issue title:calendar icon not aligned inside the textbox in Add Design Change page

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @irajneeshgupta. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @irajneeshgupta thanks for the pull request! According to the description the PR is targeted to fix a single calendar icon. I think that the fix should be much more specific to that icon.

Additionally, I don't understand what is the issue, the calendar icon looks completely fine in my opinion.

**Comment by hostep** [comment]
@sivaschenko: I believe this already got fixed in: https://github.com/magento/magento2/pull/18593, we have this one as a patch on our shops and it fixes a bunch of incorrectly aligned calendar icons if I remember correctly.

**Comment by sivaschenko** [comment]
@hostep thanks for the tip, however, I believe that was a different issue. This PR is changing old calendar icon style (outside the input box) to new (inside the input box)

**Comment by hostep** [comment]
@sivaschenko: ah yes, you are correct, sorry, my bad!

**Comment by irajneeshgupta** [comment]
@sivaschenko 
any updates on this PR.

**Comment by sivaschenko** [comment]
@irajneeshgupta please see the code review comments https://github.com/magento/magento2/pull/20389#pullrequestreview-218847970

**Comment by sidolov** [comment]
@irajneeshgupta , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
