### PR TITLE
Check if copy method is copy before sending comment email

### LINKED ISSUE #29915: [Issue] Check if copy method is copy before sending comment email
This issue is automatically created based on existing pull request: magento/magento2#29911: Check if copy method is copy before sending comment email

---------
### Preconditions (*)

Magento 2.4-develop

As seen in the comments email copies should only be sent as separated emails if their copy method is copy.

Screenshot from 2020-10-19 10-28-34

### Steps to reproduce: (*)

1. Go to Admin -> Stores -> Configuration -> Sales -> Sales Email -> Order Comments and set **Enabled** to **Yes**
2. Add email address to **Send Order Comment Email Copy To**
3. Set **Send Order Comments Email Copy Method** to **Bcc**
4. Place order.
5. Add order comment in order overview (adminhtml area) and **uncheck** notify customer.

**Actual Result:** :heavy_multiplication_x: a copy of the email was sent 

Screenshot from 2020-10-16 15-07-38

**Expected Result:** :heavy_check_mark:   Email copy should not be send because notify customer is disabled and copy set to bcc.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by Jeroenll**
### Description (*)
As seen in the comments email copies should only be sent as separated emails if their copy method is copy.

### Related Pull Requests
None I could find.

### Fixed Issues (if relevant)
None I could find.

### Manual testing scenarios (*)
1. Enable `sales_email/order_comment/enabled`
2. Add email address to `sales_email/order_comment/copy_to`
3. Set `sales_email/order_comment/copy_method` to bcc (default value).
4. Place order.
5. Add order comment in order overview (adminhtml area) and uncheck notify customer.

6. Email copy should not be send because notify customer is disabled and copy set to bcc.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29915: Check if copy method is copy before sending comment email

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Review by sidolov — CHANGES_REQUESTED** [review]
@JeroenVanLeusden could you please cover changes with automated test?

**Comment by engcom-Charlie** [comment]
Hi @JeroenVanLeusden, please cover your changes by automated test. Otherwise, we can't proceed with your PR.
Thank you.

**Comment by JeroenVanLeusden** [comment]
@sidolov Will do. However shouldn't we remove the entire ifelse statement and only send a copy/bcc if the customer itself actually receives an email?

**Comment by sidolov** [comment]
@JeroenVanLeusden do you mean to send an email when `$notify === true` only?

**Comment by JeroenVanLeusden** [comment]
@sidolov Correct

**Comment by sidolov** [comment]
If we are going to be consistent with the comment
```
// Email copies are sent as separated emails if their copy method is 'copy' or a customer should not be notified
```
and I believe it's a right way to preserve backward compatible behavior, we should remove the `esle` statement and just add one more `if` expression like:
```
if (!$notify || $this->identityContainer->getCopyMethod() === 'copy') {
    $sender->sendCopyTo();
}
```

**Comment by JeroenVanLeusden** [comment]
Fine by me. Will update this when i find some spare time.

**Comment by engcom-Charlie** [comment]
Hi @JeroenVanLeusden, will you continue with this PR?
Thank you.

**Comment by JeroenVanLeusden** [comment]
It's still on my todo list, hopefully will have some time end of this week.

**Comment by JeroenVanLeusden** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8348](https://jira.corp.magento.com/browse/ENGCOM-8348) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

### Case 1 

**Manual testing scenario:**

1. Go to Admin -> Stores -> Configuration -> Sales -> Sales Email -> Order Comments and set **Enabled** to **Yes**
2. Add email address to **Send Order Comment Email Copy To**
3. Set **Send Order Comments Email Copy Method** to **Bcc**
4. Place order.
5. Add order comment in order overview (adminhtml area) and **uncheck** notify customer.

**Before:** :heavy_multiplication_x: a copy of the email was sent (but shouldn't have been sent because the customer notification was turned off and the copy was set to a hidden copy.)

Screenshot from 2020-10-16 15-07-38

**After:** :heavy_check_mark:  email copy wasn't sent

### Case 2

**Manual testing scenario:**

1. Go to Admin -> Stores -> Configuration -> Sales -> Sales Email -> Order Comments and set **Enabled** to **Yes**
2. Add email address to **Send Order Comment Email Copy To**
3. Set **Send Order Comments Email Copy Method** to **Bcc**
4. Place order.
5. Add order comment in order overview (adminhtml area) and **check** notify customer.

**After:** :heavy_check_mark:  email copy was sent

**Pull request merged**
