### PR TITLE
30692 issue resolved - Selecting a payment method results in a 400 error

### LINKED ISSUE #30692: Selecting a payment method results in a 400 error
### Preconditions (*)

1. Magento 2.4-develop
2. Checkout terms and agreements enabled in _Stores->Configuration->(Sales)Checkout->Enable Terms and Conditions_
3. At least one manually selected terms and conditions

### Steps to reproduce (*)

1. Logged in user
2. Go to last step of checkout
3. Select any payment method

### Expected result (*)

1. REST call set-payment-information completes successfully

### Actual result (*)

1. REST call set-payment-information results in a 400 error 
image

The error message reads "The order wasn't placed. First, agree to the terms and conditions, then try placing your order again." and comes from [here](https://github.com/magento/magento2/blob/2.4.1/app/code/Magento/CheckoutAgreements/Model/Checkout/Plugin/Validation.php#L101)

**Note:** Order successfully could be placed 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by yogeshkarodiya**
Selecting a payment method results in a 400 error

### Description (*)
CheckoutAgreements/Model/Checkout/Plugin/Validation.php plugin validating term and condition when payment information is saving but as per current flow payment information is saving at the time of checkout page loading. So we have to remove this validation at the time of save payment information. Term and condition validation already exist at the time of order place for method SavePaymentInformationAndPlaceOrder.

### Fixed Issues (if relevant)
#30692 Selecting a payment method results in a 400 error

1. Fixes magento/magento2#30692

### Manual testing scenarios (*)
This is not coming for guest customer because beforeSavePaymentInformation not available for guest customer.
Logged In customer Testing flow
1> Logged in user
2> Go to last step of checkout
3> Select any payment method
4> REST call set-payment-information completes successfully

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Hi @yogeshkarodiya,
It seems like you just reverting changes from MC-30258 https://github.com/magento/magento2/search?q=MC-30258&type=commits
@sidolov @gabrieldagama @sivaschenko, could you provide more details about MC-30258 - what was the purpose of adding these changes?

**Comment by ihor-sviziev** [comment]
@yogeshkarodiya, could you resolve the conflict?

**Comment by sivaschenko** [comment]
@ihor-sviziev here is a description of MC-30258

** STEPS TO REPLICATE:**
- Within your admin panel enable Terms and conditions with settings of "Applied Manually".
Stores > Settings > Terms and Conditions > Add New Condition (please see screenshot attached)
Stores > Settings > Configuration > Sales > Checkout > Checkout Options > Enable Terms and Conditions: YES
- Within your admin panel enable any Credit Card method. (reproduced with cybersource and braintree)
- On the store front cart multiple items then proceed to checkout with multiple addresses.
- After Entering payment information and clicking "Go to Review Your Order" you should get a http 400 bad request. This error occurred because in this file "vendor/magento/module-checkout-agreements/Model/Checkout/Plugin/Validation.php", the  beforeSavePaymentInformation() method called validateAgreements() which throw an exception error "Please agree to all the terms and conditions before placing the order."

This validation should not be happening at this step due to the Terms and Conditions not existing until the Review step in multishipping checkout.

**EXPECTED RESULTS:**
Review page should load successfully

 **ACTUAL RESULTS:**
Review page leads to 400 in console

**Comment by ihor-sviziev** [comment]
@yogeshkarodiya, could you make sure that the following steps still work fine after your changes?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@yogeshkarodiya, 
Could you resolve conflicts and make sure that the following steps still work fine after your changes?
https://github.com/magento/magento2/pull/30735#issuecomment-767553552

**Comment by ishakhsuvarov** [comment]
Hi

I am closing this PR for now as it seems like it has become stale and still needs work.

Please feel free to reopen if you wish to continue.

Thanks!

**Pull request closed without merging**
