### PR TITLE
Problem on mobile when catalog gallery allowfullscreen is false #5808

### PR DESCRIPTION
**Pull request by Crossmotion**
https://github.com/magento/magento2/issues/5808

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=8434) <br/>All committers have signed the CLA.

**Comment by vrann** [comment]
@Crossmotion thank you for the contribution. I will let you know on any additional questions after verification.

**Comment by zetlen** [comment]
LGTM :+1:

**Comment by vrann** [comment]
@zetlen we've been trying to reproduce the issue and it is not reproducible on 2.1.3 or 2.1-dev. Android emulated device was used to test it. Can you provide more details on environment when the bug is reproduced? I.e. device, browser, etc.

**Comment by vrann** [comment]
@Crossmotion sorry, wrong name reference in comment earlier :) please take a look.

**Comment by vrann** [comment]
@Crossmotion please share any information available so that issue can be reproduced.

**Comment by Crossmotion** [comment]
@vrann sorry for the delay, I will reply in detail  tomorrow, but please also check https://github.com/magento/magento2/issues/5808 for info to reproduce.

**Comment by vrann** [comment]
@Crossmotion reproduced the issue on iPhone. Testing fix.

**Pull request merged**
