### PR TITLE
Improvement: Added additional marketing tags to be excluded in Varnish configuration

### LINKED ISSUE #38298: Varnish configuration does not exclude all marketing parameters
### Preconditions and environment

- Magento version: 2.4.6-p3

### Steps to reproduce

Export the varnish configuration in the Magento admin and search for the part in the generated VCL file to determine that not all marketing parameters are excluded. 

### Expected result

All marketing parameters are excluded

### Actual result

Common marketing parameters are not excluded for instance: 

- gad_source (https://support.google.com/google-ads/answer/13327296?hl=en ) 
- srsltid (https://support.google.com/analytics/answer/11479699?hl=en ) 
- msclkid (https://help.ads.microsoft.com/apex/index/3/en/60000 )

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by CreamDevelopment**
### Description
Improvement: Added additional marketing tags to be excluded in Varnish configuration

### Fixed Issues (if relevant)
1. Fixes magento/magento2#38298

### Manual testing scenarios
1. Go into the admin and export the varnish configuration to show the extra marketing tags to be excluded. 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@CreamDevelopment, please sign CLA

**Comment by CreamDevelopment** [comment]
@ihor-sviziev It has bene signed.

**Comment by hostep** [comment]
Maybe `_kx` can be added as well? It was proposed in https://github.com/magento/magento2/pull/36796/files#r1095535697, but that PR got closed unfortunately.
`_kx` seems to be related with Klaviyo: https://help.klaviyo.com/hc/en-us/articles/115005076767

**Comment by ihor-sviziev** [comment]
@hostep I do agree, but we also have a separate fixes for that in https://github.com/magento/magento2/pull/35228 and https://github.com/magento/magento2/pull/38221

**Comment by peterjaap** [comment]
@hostep @CreamDevelopment @ihor-sviziev maybe we can add a configuration field for this?

**Comment by ihor-sviziev** [comment]
@peterjaap, I think it would be too complicated. I think having it like that should be enough

**Comment by engcom-Charlie** [comment]
Hi @CreamDevelopment,

Thank you for your contribution!

We are not able to update your PR branch now as the fork is not updated. Can you please update your branch so that we can proceed further on this PR. 

Thank you!

**Comment by engcom-Charlie** [comment]
As we are unable to update the branch in order to proceed ahead as mentioned in [here](https://github.com/magento/magento2/pull/38302#issuecomment-2295559653), closing this PR now. Please feel free to reopen once you are done with the needed.

**Pull request closed without merging**
