### PR TITLE
MFTF: Allow shipment update emails to be disabled 

### LINKED ISSUE #33165: Cannot disable shipment update emails
### Preconditions

1. Magento 2.4.2;

### Steps to reproduce

1. In the admin panel, go to Stores > Configuration > Sales > Sales Emails and disable the Shipment comments;
2. Open a shipment view in the admin panel;

### Expected result

1. No `Notify Customer by Email` checkbox;

### Actual result (*)

1. Checkbox is still there:

Screenshot from 2021-06-07 15-36-36

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
I have covered the fix https://github.com/magento/magento2/pull/33166 for https://github.com/magento/magento2/issues/33165 issue by MFTF tests

### Related Pull Requests
https://github.com/magento/magento2/pull/33166

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/33165

### Manual testing scenarios (*)
See https://github.com/magento/magento2/issues/33165

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@eduard13 please, review my PR.

Thanks.

**Comment by eduard13** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Integration Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by eduard13** [comment]
@magento run Integration Functional Tests CE, Functional Tests B2B

**Review by eduard13 — APPROVED** [review]
Thank you @kate-kyzyma for the test coverage.
The failed tests are related to the related PR.

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-9124](https://jira.corp.magento.com/browse/ENGCOM-9124) has been created to process this Pull Request

**Comment by engcom-Charlie** [comment]
:x: QA not Passed

I have created a clone of https://github.com/kate-kyzyma/magento2.git and did checkout allow-shipment-update-emails-to-be-disabled branch.

Done the Setup MFTF and run the test case as vendor/bin/mftf run:test AdminDisableShipmentCommentsTest --remove 

The MFTF test case is failing. You can find the respective allure report below.

image

image


Note: Since https://github.com/magento/magento2/pull/33166 PR changes are not in above given branch the manual testing will not give the correct result still mentioning the steps to reproduce.

**Pre Conditions**

1. There should be order created it should be shipped followed by invoice. At least one order should be existing in the Admin panel Sales > Shipments grid


**Manual testing scenario:**

1. In the admin panel, go to Stores > Configuration > Sales > Sales Emails > Shipment comments - disable it

2. Open a shipment view (Sales > Shipments > view any shipment from grid) in the admin panel;

**Comment by eduard13** [comment]
@magento run all tests

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-9124](https://jira.corp.magento.com/browse/ENGCOM-9124) has been created to process this Pull Request

**Comment by eduard13** [comment]
Hi @engcom-Charlie, basically the reported by you errors were actually the expected ones. However, I've also added the fix in this PR, so we'll have the green tests.

Could you please double check this one?

Thank you.

**Comment by engcom-Charlie** [comment]
Moving this in Ready for testing as https://github.com/magento/magento2/pull/33166 is still in testing in progress.

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
:heavy_check_mark: QA Passed

The newly created auto tests are valid. 

The test case is working fine and green in build. Please find the Allure report for the same.

@kate-kyzyma and @eduard13 as https://github.com/magento/magento2/pull/33166 is already in Merge in Progress so please [remove the issue fix](https://github.com/magento/magento2/pull/33232#issuecomment-882441243) which is added by you  and **only keep MFTF test case fix in this ticket**

image

image

**Comment by eduard13** [comment]
Hi @engcom-Charlie, thank you for checking it, however the fix won't cause any conflicts with the related PR, so there is no reason to remove it.

What do you think?

Thanks.

**Comment by engcom-Charlie** [comment]
Hi @eduard13,

Thanks for replying.

https://github.com/magento/magento2/pull/33166 ticket is having the issue fix which is in Merge in progress.

This ticket https://github.com/magento/magento2/pull/33232  is specifically for MFTF test coverage which is working fine. I think when it will get merge, since it also having the above fix in it it will cause unnecessary conflicts at the time of merging. So I have requested that you can remove the fix made in  33166 and only go with the MFTF test case related PR change in this ticket.

Thank you!

**Comment by eduard13** [comment]
Hi @engcom-Charlie, since this PR contains exactly the same changes (there is no difference), then normally there should be no conflicts with these 2 PRs.

**Comment by engcom-Charlie** [comment]
Hi @eduard13, as you confirmed in https://github.com/magento/magento2/pull/33232#issuecomment-896776807 moving this ticket to Merge in Progress.

Thank you!

**Comment by slavvka** [comment]
@magento give me test instance

**Pull request merged**
