### PR TITLE
Show error message when customer click on Add to cart button without selecting atleast one product from recently orderred list

### PR DESCRIPTION
**Pull request by mageprince**
### Description (*)

It should display a proper error message when customer click on Add to cart button without selecting at least one product from the recently ordered list

### Fixed Issues (if relevant)

https://github.com/magento/magento2/issues/21398

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mageprince. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by mageprince** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @mageprince. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @mageprince, here is your [new Magento instance](https://pr-21401.instances.magento-community.engineering).
Admin access: [https://pr-21401.instances.magento-community.engineering/admin](https://pr-21401.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by mageprince** [comment]
@magento-engcom-team tested in Magento test instance.

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-21401.instances.magento-community.engineering).
Admin access: [https://pr-21401.instances.magento-community.engineering/admin](https://pr-21401.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4355](https://jira.corp.magento.com/browse/ENGCOM-4355) has been created to process this Pull Request

**Pull request merged**
