### PR TITLE
Do not load backend block context on frontend

### LINKED ISSUE #37617: [Issue] Do not load backend block context on frontend
This issue is automatically created based on existing pull request: magento/magento2#36368: Do not load backend block context on frontend

---------

### Description (*)

The class is used on frontend, but loads the backend context. So with all dependencies, it's also creating backend session that additionally causes session locks.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Set a breakpoint in the constructor of `Magento\Backend\Block\Template\Context` (because it uses backend session `\Magento\Backend\Model\Session` and other heavy objects)
2. Try placing an order on the frontend.

**Expected result:** 
✅ the class from the "backend" module shoudln't be loaded on frontend
**Actual result:**
❌ the class is getting loaded on frontend.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)

The class is used on frontend, but loads the backend context. So with all dependencies, it's also creating backend session that additionally causes session locks.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Set a breakpoint in the constructor of `Magento\Backend\Block\Template\Context` (because it uses backend session `\Magento\Backend\Model\Session` and other heavy objects)
2. Try placing an order on the frontend.

**Expected result:** 
✅ the class from the "backend" module shoudln't be loaded on frontend
**Actual result:**
❌ the class is getting loaded on frontend.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37617: Do not load backend block context on frontend

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@sidolov @sivaschenko @ishakhsuvarov do you feel we have a chance to get approval for SVC failure?

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
Hi @ihor-sviziev ,

Thanks for your contribution and collaboration.

Please provide steps to reproduce the issue.

Thanks

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@engcom-Lima, 
you can set a breakpoint in the constructor of `Magento\Backend\Block\Template\Context` (because it uses backend session  `\Magento\Backend\Model\Session`) and then try placing an order on frontend.
Expected result: the class from the "backend" module shoudln't be loaded on frontend
Actual result: the class is getting loaded on frontend.

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
Hi @ihor-sviziev ,

Thanks for your contribution and collaboration.

I have verified the PR and it is working fine for checkout process but when we are doing reordering the product from the frontend backend class again it is calling. [Video](https://shared-assets.adobe.com/link/7abb08f9-8058-41be-490c-688a51c608b8) is for your reference.

Kindly provide us fix for the above scenario.

Thanks

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@engcom-Lima @engcom-Hotel I fixed the listed above issue

**Review by engcom-Hotel — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**
- Set a breakpoint in the constructor of `Magento\Backend\Block\Template\Context` (because it uses backend session `\Magento\Backend\Model\Session` and other heavy objects)
- Try placing an order on the frontend.
- Reorder from the frontend.

**Before:** :heavy_multiplication_x: _Backend class was loaded ._
Screenshot 2023-06-14 at 3 06 12 PM


**After:** :heavy_check_mark:  _Now able to place an order_
image

Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
Hi @ihor-sviziev,

Thank you for your contribution!

Raised internal approval JIRA ticket for the SVC failure. Once we get all the required approvals, will proceed further on this PR. Till then moving it to Pending Approval.

Thank you!

**Comment by sidolov** [comment]
@magento run Semantic Version Checker

**Comment by ihor-sviziev** [comment]
@engcom-Charlie any updates on approval process?

**Comment by engcom-Charlie** [comment]
> @engcom-Charlie any updates on approval process?

Hi @ihor-sviziev,

We haven't got all the required approvals yet. As soon as we will get the approvals will proceed on it further.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run Semantic Version Checker

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by engcom-Charlie** [comment]
The web API test failures seems to be flaky, not related to this PR.

Run 1:
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36368/b173e719540743dc56d019faf42b3405/WebApi/console-error-logs.html

Run 2:
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36368/93939e369a5cf0ff0fb33c1aa329c9ad/WebApi/console-error-logs.html

**Comment by engcom-Charlie** [comment]
Functional B2B failures are different in recent 2 builds.

Run 1: 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36368/e06015e06297976f6872ee20be99c960/Functional/allure-report-b2b/index.html#categories

image


Run 2: 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36368/bfdc5c52f0214d41192d0e162a8b51ed/Functional/allure-report-b2b/index.html#categories

image


From these 2, CustomerOrderCancellationFromOrderHistoryTest test is a known error all test failures are different.

**Comment by engcom-Charlie** [comment]
The functional EE test failures are different in recent 2 builds, seems to be flaky and not part of this PR.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36368/f286aaf6769abbdf8feb22a56aacbc99/Functional/allure-report-ee/index.html#categories
image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36368/38c7d60804707fe939b6b8b70676d93f/Functional/allure-report-ee/index.html#categories

image

**Comment by engcom-Charlie** [comment]
We have got required approvals on approval [JIRA](https://jira.corp.adobe.com/browse/AC-9034).

**Comment by engcom-Charlie** [comment]
As we got all required approvals now, moving this to Merge in Progress.

**Pull request merged**
