### PR TITLE
Unable to add configurable product to cart on any non-default store view

### LINKED ISSUE #31660: Unable to add configurable product to cart on any non-default store view (French store).
**Note: Simple Products work across website/store code, this bug is specific to configurable products**

**PWA Repro:**

URL - <https://integration-5ojmyuq-jnz3dtiuj77ca.us-4.magentosite.cloud/montana-wind-jacket.html]

Steps - 
 1. Go to above URL.

2. Switch to French Store and try adding configurable to to cart.

 

Expected - Product should get added.

Actual - User gets error "Could not add item to cart. Please check required options and try again."

**GQL Repro:**
1. Using a backend on 2.4.2-beta3, create a cart
1. Attempt to add a configurable item to the "french" store:
```java
// Query
mutation addConfigurableProductToCart(
  $cartId: String!
  $quantity: Float!
  $sku: String!
  $parentSku: String!
) {
  addConfigurableProductsToCart(
    input: {
      cart_id: $cartId
      cart_items: [
        { data: { quantity: $quantity, sku: $sku }, parent_sku: $parentSku }
      ]
    }
  ) {
    cart {
      id
      total_quantity
    }
  }
}
{code}

{code:java}
// Query Variables
{
  "cartId":"9cfw1jBRxnyyic8jVoBLXELkDOZtobJ4",
  "quantity": 1,
  "sku": "WT09-XL-Yellow",
  "parentSku": "WT09"
} {code}
{code:java}
// Header
{ 
  "store": "fr" 
}{code}
 

Expected:
{code:java}
 {
  "data": {
    "addConfigurableProductsToCart": {
      "cart": {
        "id": "9cfw1jBRxnyyic8jVoBLXELkDOZtobJ4",
        "total_quantity": 4
      }
    }
  }
}{code}
 

Actual:
{code:java}
{
  "errors": [
    {
      "message": "Could not add the product with SKU WT09 to the shopping cart: The website with id 2 that was requested wasn't found. Verify the website and try again.",
      "extensions": {
        "category": "graphql-input"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addConfigurableProductsToCart"
      ]
    }
  >,
  "data": {
    "addConfigurableProductsToCart": null
  }
} ```

### PR DESCRIPTION
**Pull request by shikhamis11**
### Description (*)
**Note: Simple Products work across website/store code, this bug is specific to configurable products**

PWA Repro:

URL - <https://integration-5ojmyuq-jnz3dtiuj77ca.us-4.magentosite.cloud/montana-wind-jacket.html>

**Steps -** 

    Go to above URL.

    Switch to French Store and try adding configurable to to cart.

 

**Expected -** Product should get added.

Actual - User gets error "Could not add item to cart. Please check required options and try again."

**GQL Repro:**

    Using a backend on 2.4.2-beta3, create a cart
    Attempt to add a configurable item to the "french" store:

// Query
```
mutation addConfigurableProductToCart(
  $cartId: String!
  $quantity: Float!
  $sku: String!
  $parentSku: String!
) {
  addConfigurableProductsToCart(
    input: {
      cart_id: $cartId
      cart_items: [
        { data: { quantity: $quantity, sku: $sku }, parent_sku: $parentSku }
      ]
    }
  ) {
    cart {
      id
      total_quantity
    }
  }
}
{code}

{code:java}
// Query Variables
{
  "cartId":"9cfw1jBRxnyyic8jVoBLXELkDOZtobJ4",
  "quantity": 1,
  "sku": "WT09-XL-Yellow",
  "parentSku": "WT09"
} {code}
{code:java}
// Header
{ 
  "store": "fr" 
}{code}
 

Expected:
{code:java}
 {
  "data": {
    "addConfigurableProductsToCart": {
      "cart": {
        "id": "9cfw1jBRxnyyic8jVoBLXELkDOZtobJ4",
        "total_quantity": 4
      }
    }
  }
}{code}
 

Actual:
{code:java}
{
  "errors": [
    {
      "message": "Could not add the product with SKU WT09 to the shopping cart: The website with id 2 that was requested wasn't found. Verify the website and try again.",
      "extensions": {
        "category": "graphql-input"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addConfigurableProductsToCart"
      ]
    }
  >,
  "data": {
    "addConfigurableProductsToCart": null
  }
} 
```

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/31660

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by shikhamis11** [comment]
@magento give me test instance

**Comment by shikhamis11** [comment]
@magento run Static Tests

**Comment by shikhamis11** [comment]
@magento run Static Tests

**Comment by shikhamis11** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8673](https://jira.corp.magento.com/browse/ENGCOM-8673) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by prabhuram93 — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Pull request merged**
