### PR TITLE
Fix for #11796 Magento2.2.0 home page product grid issues

### PR DESCRIPTION
**Pull request by punitv**
### Description

Fixed homepage product grid issues. 
- Display 5 products in a row and with no margin addition for the first product on next row (Desktop view).
- Display 2 products in a row (Mobile portrait mode).
- Display 3 products in a row (Mobile landscape mode).

### Fixed Issues (if relevant)

1. magento/magento2#11796: Magento2.2.0 home page product grid issues

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=13081) <br/>All committers have signed the CLA.

**Comment by punitv** [comment]
I tried many times signing  Contributor License Agreement but still shows not signed yet.

**Comment by dmanners** [comment]
@punitv I think your user that committed is different from the user that you are signed into github with. Please either update the committed user or change the github user.

**Comment by punitv** [comment]
@dmanners Yes, I fork repository with one user-email and committed code using different user-email. Will [this](https://help.github.com/articles/changing-author-info/) be the way to update the committed user.

**Comment by dmanners** [comment]
@punitv you will need to change all your commits. I think https://stackoverflow.com/a/3042512 should cover your needs here.

**Pull request merged**
