### PR TITLE
FIX for issue https://github.com/magento-engcom/php-7.2-support/issue…

### PR DESCRIPTION
**Pull request by phoenix128**
FIX for https://github.com/magento-engcom/php-7.2-support/issues/33

### Description
Void methods were breaking Interceptor classes due to a return statement.
PHP7.2 forbids the presence of a return statement with parameters in void methods, even if returning null.

### Fixed Issues (if relevant)
1. https://github.com/magento-engcom/php-7.2-support/issues/33

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@phoenix128 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @phoenix128. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.3.0 release.

**Comment by WesleyVestjens** [comment]
Are there any plans for merging this into the 2.2-develop branch as well? Magento 2.2.x and PHP 7.1.x are also affected by this bug.

**Comment by joshuaadickerson** [comment]
Can this be backported to 2.2?

**Pull request merged**
