### PR TITLE
issue fixed #20176 Confirmation pop-up at mobile view not prope

### LINKED ISSUE #20176: Confirmation pop-up at mobile view not proper
### Preconditions (*)

1. 2.3.0
2.

### Steps to reproduce (*)

1. Add product into cart 
2. remove product from minicart
3. pop-up not showing proper at mobile view

### Expected result (*)

1. 
2019-01-10_19-41_breathe-easy tank 2

2.

### Actual result (*)

1. 
2019-01-10_19-41_breathe-easy tank

2.

### PR DESCRIPTION
**Pull request by cedarvinda**
issue fixed #20176 Confirmation pop-up at mobile view not prope

### Manual testing scenarios (*)

1. Add product into cart
2. remove product from minicart
3. pop-up not showing proper at mobile view

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by DanielRuf** [comment]
Isn't this fixed by properly using `box-sizing: border-box`?

**Comment by cedarvinda** [comment]
@DanielRuf No, It will not fix from this rule.

l82w62k

**Comment by DanielRuf** [comment]
See the width of `50rem`. It should be `max-width`.

**Comment by cedarvinda** [comment]
Yes ... great !! This can be done using max-width ... but what I have done using media query its not proper ?

**Comment by DanielRuf** [comment]
It may work but not on all viewports, especially if the breakpoint is changed in the theme less settings.

**Comment by cedarvinda** [comment]
Its working fine in all Viewport (checked) .. I have compiled first in my Local system and test then created PR. But still testing in my local using max-width.

**Comment by DanielRuf** [comment]
> if the breakpoint is changed in the theme less settings

If we lower the width of it in the less variable it will produce issues ;-)

**Comment by cedarvinda** [comment]
@DanielRuf 320px is min to reduce with of device, but in magento already using 75% width in same element for small devices, I can also use 75% for that particular resolution.

**Comment by DanielRuf** [comment]
`width: 75%` + `max-width: 50rem` might be probably a good combination. Not sure but the percentage based and max-width solutions are much better than the calc with the fixed `30px` value.

**Comment by cedarvinda** [comment]
@DanielRuf Thanks for suggestion... I will go with you (y)

**Comment by priti2jcommerce** [comment]
Hi @DanielRuf and @cedarvinda ,

PR #20196 already merged for 2.3.0

**Pull request closed without merging**
