### PR TITLE
fixed issue 25433

### PR DESCRIPTION
**Pull request by Ashna-Jahan**
### Description (*)

<strong>I think this is not an issue since there is a trash icon at the end of the line item so, user can click on it to get rid of the validation, 
In this fix we have Increased the width of the div so that the trash icon will be visible to user in first glance.</strong>
 
### Fixed Issues (if relevant)

1. magento/magento2#25433: Close (X) not working when error come for qty

### Manual testing scenarios (*)

1. Go to advanced pricing area and click on 'Add'. 
2. After this fix the trash Icon will be displayed in first glance so that the user can click on it for getting rid of the validation.
3. Please look into the screenshot below.
4. 
trashicon

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by kalpmehta** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, here is your [Magento instance](https://i-25759-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25759-2-3-develop.instances.magento-community.engineering/admin](https://i-25759-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kalpmehta** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, here is your [new Magento instance](https://pr-25759.instances.magento-community.engineering).
Admin access: [https://pr-25759.instances.magento-community.engineering/admin](https://pr-25759.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by kalpmehta** [comment]
Hi @Ashna-Jahan, thanks for your contribution. I still see this issue occurring when the screen width is less than 768 px. This looks like a half fix. Do you have any idea on how to resolve this for lesser than 768 px devices too?

**Review by kanthy-i95dev — APPROVED** [review]

**Review by kanthy-i95dev — CHANGES_REQUESTED** [review]
@Ashna-Jahan please check @kalpmehta comments

**Comment by Ashna-Jahan** [comment]
Hi @kalpmehta, this is working fine in my devices (android and iPhone)  with this fix. Please find the below screenshots. For your reference
iphone
android <strong>Please provide screenshots is you still able to reproduce.</strong>

**Comment by kalpmehta** [comment]
Thank you @Ashna-Jahan for additional information. I agree it's working on desktop and mobile, but if you could resize your browser to mock lesser than 768 px you will notice the original issue. 

Attaching the screenshot:
image

I think I'm good with the half fix for now, however, if you can please remove "!important" from the CSS additions that would be great. Generally it's not a good idea to use !important. Let me know if you need any help!

**Review by kanthy-i95dev — APPROVED** [review]

**Comment by kalpmehta** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, here is your [new Magento instance](https://pr-25759.instances.magento-community.engineering).
Admin access: [https://pr-25759.instances.magento-community.engineering/admin](https://pr-25759.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by kalpmehta** [comment]
@Ashna-Jahan `min-width: 682px` is creating below issue:
image

Please remove that rule and make sure nothing else gets adversely impacted by your changes.

**Comment by Ashna-Jahan** [comment]
Hi @kalpmehta, 
I have fixed the issue and committed the code. Please review and let me know If you have any query on this.

**Comment by kalpmehta** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, here is your [new Magento instance](https://pr-25759.instances.magento-community.engineering).
Admin access: [https://pr-25759.instances.magento-community.engineering/admin](https://pr-25759.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by Ashna-Jahan** [comment]
Hi @kalpmehta,
If design disturbs when we resize a browser, can we consider it as a bug. please let me know.

**Comment by kalpmehta** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, here is your [Magento instance](https://i-25759-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25759-2-3-develop.instances.magento-community.engineering/admin](https://i-25759-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by kalpmehta — APPROVED** [review]

**Comment by kalpmehta** [comment]
Thank you @Ashna-Jahan for your continuous efforts to fix this issue!

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, thank you for the review.
[ENGCOM-6375](https://jira.corp.magento.com/browse/ENGCOM-6375) has been created to process this Pull Request
:eight_spoked_asterisk: @kalpmehta, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @Ashna-Jahan. 
The issue [#25433](https://github.com/magento/magento2/issues/25433), mentioned by you in the description, was not solved in the scope of this PR. This is another problem.

@Ashna-Jahan Could you take a look?
Thanks!

**Comment by Ashna-Jahan** [comment]
Hi @engcom-Alfa,
#25433 is not actually an issue since we have trash icon at the end of the. User can click on this for removal of validation.   
This will be issue only when the user has no choice other than reloading page to remove the validation.

**Comment by engcom-Alfa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [Magento instance](https://i-25759-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25759-2-3-develop.instances.magento-community.engineering/admin](https://i-25759-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [new Magento instance](https://pr-25759.instances.magento-community.engineering).
Admin access: [https://pr-25759.instances.magento-community.engineering/admin](https://pr-25759.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by engcom-Alfa** [comment]
Hi @Ashna-Jahan 

During testing, I faced the issue.

**Problem:** "Icon" button isn't visible without scrolling on mobile

**Manual testing scenario:**

1. Log in to Admin;
2. Go to Catalog->Products->Add Product;
3. Open developer tools in the browser and enable Device mode ( IPad for ex.);
4. Click on "Advanced Pricing" link;
5. Click on "Add" button;

**Actual Result:**
Without scrolling, we do not see a trash icon
Peek

@Ashna-Jahan Could you take a look?

Thanks!

**Comment by Ashna-Jahan** [comment]
Hi @engcom-Alfa,

I have fixed the issue. Please review and let me know If you have any concern.

**Comment by kalpmehta** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, here is your [new Magento instance](https://pr-25759.instances.magento-community.engineering).
Admin access: [https://pr-25759.instances.magento-community.engineering/admin](https://pr-25759.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by kalpmehta — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, thank you for the review.
[ENGCOM-6375](https://jira.corp.magento.com/browse/ENGCOM-6375) has been created to process this Pull Request

**Review by kanthy-i95dev — APPROVED** [review]

**Review by kalpmehta — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, thank you for the review.
[ENGCOM-6375](https://jira.corp.magento.com/browse/ENGCOM-6375) has been created to process this Pull Request

**Review by kanthy-i95dev — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

**Actual Result:**
after3

**Pull request merged**
