### PR TITLE
Upgrade the -dev versions of dependencies for Magento

### LINKED ISSUE #24635: Use of undefined constant GLOB_BRACE in dependency "allure-framework/allure-phpunit"
### Preconditions (*)
Magento Version: 2.3.2

### Steps to reproduce (*)

`./bin/magento dev:test:run unit`

### Expected result (*)
No PHP Warnings

### Actual result (*)

several:
```
Warning: Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' (this will throw an Error in a future version of PHP) in /var/www/html/src/vendor/allure-framework/allure-phpunit/src/Yandex/Allure/Adapter/AllureAdapter.php:74.
```

### Related Informations

Problem is, GLOB_BRACE is not available in alle Unix Systems.
For example the often in Docker context used "Alpine" 
https://github.com/docker-library/php/issues/719

There is an (not merged) upstream PullRequest available in https://github.com/allure-framework/allure-phpunit/pull/44
But I did not check yet, if this is the proper solution.

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Along with PHPUnit upgrade, all other `-dev` dependencies should be upgraded.
Doing that now, in scope of this PR.

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
Fixes https://github.com/magento/magento2/issues/24635

### Manual testing scenarios (*)
Execute all tests, expecting the Allure outcome to be correctly reported.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests
Submitted the updated `composer.lock` after locking dependencies back, the way these were done previously.

**Comment by hostep** [comment]
@lbajsarowicz: it might be better if you update your composer version to at least 1.10.0 and re-generate the `composer.lock` file after you did that. Then the removal of those `funding` sections will not happen and the `composer.lock` file will have fewer changes and will be easier to review.

**Comment by lbajsarowicz** [comment]
That update should've been performed with PHPUnit upgrade.
This PR is going to be taken down either way, because it's too late to introduce it to 2.4.0, but it's backwards compatible so it cannot be introduced to 2.4.1

But that is a kind of manifest, that something went wrong with preparing 2.4.0

**Review by orlangur — CHANGES_REQUESTED** [review]
For now I see only Allure upgraded, is it WiP?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@orlangur yep, only allure were updated as phpunit was already 9.1, and actually no one tested all these tests on phpunit 9.0, so basically it should be more correct to put 9.1 there. 
But in case if someone tested it on 9.0 - i'm also ok to keep it as is

**Comment by orlangur** [comment]
@ihor-sviziev @lbajsarowicz then I would make description more specific

> Along with PHPUnit upgrade, **all other** -dev dependencies should be upgraded.
> Doing that now, in scope of this PR.

**Comment by orlangur** [comment]
@hostep @lbajsarowicz composer dependency needs to be changed to 1.10+ then.

@lbajsarowicz again, are you going to upgrade all other dev dependencies in scope of this PR?

**Comment by lbajsarowicz** [comment]
I've updated all the dependencies that were available with stable release

**Comment by orlangur** [comment]
> I switched all the dependencies to @stable, ran composer update on them --with-dependencies , then locked them in composer.json
So all available -dev were updated with it's dependencies

Thanks, now it's clear to me :)

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-7597](https://jira.corp.magento.com/browse/ENGCOM-7597) has been created to process this Pull Request
:eight_spoked_asterisk: @orlangur, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by orlangur — CHANGES_REQUESTED** [review]
Ah, @lbajsarowicz, this cannot be resolved in Web UI :(

image

**Comment by lbajsarowicz** [comment]
@magento run all tests

Another `composer.lock` update. There is also `PHPUnit 9.2` coming in other PR and Core Team is going to release another upgrade of RC for MFTF, so I believe that another few `composer.lock` updates are coming.

**Pull request closed without merging**
