### PR TITLE
Do not send an ajax request if there no affected sections

### LINKED ISSUE #31948: [Issue] Do not send an ajax request if there no affected sections
This issue is automatically created based on existing pull request: magento/magento2#31933: Do not send an ajax request if there no affected sections

---------
### Description (*)
In the customer data, we have a handler for all ajax requests. If we have some custom JS that sends POST, PUT or DELETE request, it tries to send a request to the backend to reload affected sections. As we had such a request by some tracking - these requests caused an additional request to the backend on all the pages that caused a significant load to the servers.

In case if there are no affected sections, it is still sending requests to the backend.

We got this issue when we created a mixin to the `getAffectedSections` for `Magento_Customer/js/section-config` and returning an empty array for our custom URL (request is sent not to Magento, so it can't affect any Magento sections).

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)
1. Open app/code/Magento/Customer/view/frontend/web/js/section-config.js
2. at the beginning of the `getAffectedSections` method add following code in console:
```php
            if (typeof url === 'string' && url.indexOf('my-url-not-affecting-sections') !== -1) {
                return [];
            }
```
image
3. Open frontend
4. open developer tools, execute following JS:
```javascript
jQuery.post('/my-url-not-affecting-sections');
```
5. Go to the "network" tab in the developer tools, review the list of requests

**Actual result:**
image
 ❌ request for reloading customer sections was sent to the backend

**Expected result**
image
✔ request for reloading customer sections shouldn't be sent to the backend

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
In the customer data, we have a handler for all ajax requests. If we have some custom JS that sends POST, PUT or DELETE request, it tries to send a request to the backend to reload affected sections. As we had such a request by some tracking - these requests caused an additional request to the backend on all the pages that caused a significant load to the servers.

In case if there are no affected sections, it is still sending requests to the backend.

We got this issue when we created a mixin to the `getAffectedSections` for `Magento_Customer/js/section-config` and returning an empty array for our custom URL (request is sent not to Magento, so it can't affect any Magento sections).

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)
1. Open app/code/Magento/Customer/view/frontend/web/js/section-config.js
2. at the beginning of the `getAffectedSections` method add following code in console:
```php
            if (typeof url === 'string' && url.indexOf('my-url-not-affecting-sections') !== -1) {
                return [];
            }
```
image
3. Open frontend
4. open developer tools, execute following JS:
```javascript
jQuery.post('/my-url-not-affecting-sections');
```
5. Go to the "network" tab in the developer tools, review the list of requests

**Actual result:**
image
 ❌ request for reloading customer sections was sent to the backend

**Expected result**
image
✔ request for reloading customer sections shouldn't be sent to the backend

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31948: Do not send an ajax request if there no affected sections

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Note: I don't have enough experience with writing JS unit tests, so would be good if someone could help with it

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Sample Data Tests EE, Static Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @engcom-Charlie, can you try to add test coverage on this one? I guess jasmine unit test could be an option, can you give it a try? Thanks!

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by gabrieldagama** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8779](https://jira.corp.magento.com/browse/ENGCOM-8779) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Open app/code/Magento/Customer/view/frontend/web/js/section-config.js
2. at the beginning of the `getAffectedSections` method add following code in console:
```php
            if (typeof url === 'string' && url.indexOf('my-url-not-affecting-sections') !== -1) {
                return [];
            }
```
image
3. Open frontend
4. open developer tools, execute following JS:
```javascript
jQuery.post('/my-url-not-affecting-sections');
```
5. Go to the "network" tab in the developer tools, review the list of requests

**Before:** :heavy_multiplication_x: request for reloading customer sections was sent to the backend



**After:** :heavy_check_mark: request for reloading customer sections wasn't sent to the backend



Was checked general customer functionality, and everything works as expected.
Screenshot from 2021-02-18 10-20-35

**Comment by ihor-sviziev** [comment]
Hi @gabrieldagama,
Could you check one more PR in similar area? https://github.com/magento/magento2/pull/31940

**Pull request merged**
