### PR TITLE
38662 - Graphql type error fix

### LINKED ISSUE #38662: [Graphql] Type issue in 2.4.7
### Preconditions and environment

- Magento version 2.4.7

### Steps to reproduce

1. Launch a graphql query that will use GetCustomSelectedOptionAttributes

### Expected result

No error

### Actual result

```
main.ERROR: Magento\Framework\GraphQl\Query\Uid::encode(): Argument #1 ($id) must be of type string, int given, called in /var/www/html/vendor/magento/module-customer-graph-ql/Model/Customer/GetCustomSelectedOptionAttributes.php on line 58
```

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Nuranto**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#38662

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Nuranto** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run WebAPI Tests, Static Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @Nuranto,

Thank you for your contribution!

### :heavy_check_mark: QA Passed

**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**
1. Created customer custom attribute with type as int
```
'custom',
            [
                'label' => 'custom',
                'input'      => 'select',
                'type' => 'int',
                'source'     => 'Magento\Eav\Model\Entity\Attribute\Source\Boolean',
                'required' => true,
                'default'    => '1',
                'position' => 333,
                'visible' => true,
                'system' => false,
                'is_used_in_grid' => true,
                'is_visible_in_grid' => true,
                'is_filterable_in_grid' => true,
                'is_searchable_in_grid' => false,
                'backend' => ''
            ]
```
2. Set developer mode in the magento instance
3. Create one customer and logged in with that user in storefront
4. Execute below GraphQl query 
```
query AccountDashboard {
  __typename
  customer {
    email
    __typename
  }
}
```

**Before:** :heavy_multiplication_x: 
image


**After:** :heavy_check_mark:  on PR branch
image


Build is failing hence moving this PR to **Extended Testing**.

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by engcom-Charlie** [comment]
The Functional B2B test failures are different in recent 2 builds hence seems to be flaky and not related to PR.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38663/ef6aa3f8d6ef4999b8fa98a5358ca53a/Functional/allure-report-b2b/index.html#categories
image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38663/93200a807671c97c1bae511bc29e0325/Functional/allure-report-b2b/index.html#categories
image

**Comment by engcom-Charlie** [comment]
Some of the Functional EE failures are not consistent in recent 2 builds, seems to be flaky and not related to PR. One test failure is consistent and its a known failure and have open issue for the same. Hence moving this PR to Merge in Progress.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38663/a22056aa7891bc00858d300a3a618145/Functional/allure-report-ee/index.html#categories/f5a70ec99dae2c5e7b2f1aa499dc4363/5a67b3984193b59f/

image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38663/df567d24129aa262ab672da5a413161b/Functional/allure-report-ee/index.html#categories

image


**Known issue :**
- StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest: [#ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331)

**Pull request merged**
