### PR TITLE
Date creation not consistent with Magento/DateTime with french format

### PR DESCRIPTION
**Pull request by khodu**
### Description (*)

Resolved Date creation not consistent with Magento/DateTime with french format issue.
### Fixed Issues (if relevant)

1. magento/magento2#6187: Date creation not consistent with Magento/DateTime with french format

### Manual testing scenarios (*)

1. Try to format a date using \Magento\Framework\Stdlib\DateTime\DateTime->date("d/m/y", "15/08/2016")
2. Now Return correct value.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @khodu. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — DISMISSED** [review]
Hi @khodu,

Nothing has changed since https://github.com/magento/magento2/pull/19057/files#r230777493.

Digit separator is still replaced with new code which is not correct. Please pay more attention to https://stackoverflow.com/a/2891949 I referred.

**Comment by khodu** [comment]
Hi @orlangur 

Have you ever test my changes??
please first test my changes and then give me review.
i have also checked this link. https://stackoverflow.com/a/2891949

**Comment by orlangur** [comment]
@khodu there is nothing to test yet. From the code it is obviously that after such replacement day will be mixed with month. Please elaborate a fix which works in all cases.

**Comment by khodu** [comment]
@orlangur 

That's the problem man.
first you test it with 1000 scenario and then give it back. 
I have tested in all the scenarios and there is no mixing in day and month.

**Comment by orlangur** [comment]
@khodu ok, will try it in action and then get back to you. Thanks man)

**Comment by khodu** [comment]
@orlangur

It is already 23days passed. I think you have already test it. Please give your suggestion if you find any error or approve my change request.

Thanks.

**Comment by orlangur** [comment]
@khodu please never change assignee without agreement.

**Review by orlangur — CHANGES_REQUESTED** [review]
@khodu please add automated test cases demonstrating  that logic works as expected in cases I mentioned.

**Comment by sidolov** [comment]
@khodu , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
