### PR TITLE
[Fixed Radio alignment issue #20025]

### PR DESCRIPTION
**Pull request by hitesh-wagento**
### Description (*)
Fixed Radio alignment issue

### Fixed Issues (if relevant)

1. magento/magento2#20025: Radio alignment issue

### Manual testing scenarios (*)

1. Add any product in Cart.
2. Go to Checkout Page.

### Expected result

1. Radio should be aligned.
expected

### Actual result

1. Radio little bit up.
actual

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @hitesh-wagento. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3770](https://jira.corp.magento.com/browse/ENGCOM-3770) has been created to process this Pull Request

**Comment by hitesh-wagento** [comment]
Hi @VladimirZaets 

Any Update on this PR ?

Thanks

**Comment by sdzhepa** [comment]
Hello @hitesh-wagento 

During testing our QA engineer faced an issue.
Could you please have a look and fix it?

Please see the quote of QA comment after testing on branch with the PR:
- **Problem:** _Radio Buttons customizable optionы are incorrectly aligned on product details page._

**Manual testing scenario:**
1. Create simple product with custom option Option Type=Radio Buttons
2. Go to product details page

**Actual Result:** Not OK,  Radio buttons have incorrect vertical alignment


**Expected Result:** On 2.3-develop(without this fix) radio buttons have correct alignment.
20026_main


Thank you for contribution and collaboration!

**Comment by hitesh-wagento** [comment]
Hi @sdzhepa 

I have fixed radio issue please review once 

fixed


Thanks

**Comment by hitesh-wagento** [comment]
Hi @VladimirZaets 

Any Update on this PR ?

Thanks

**Comment by VladimirZaets** [comment]
Changing in general styles (that applied for all forms) can provide additional UI problem. I think you should fix each specific case separately.

**Comment by sidolov** [comment]
@hitesh-wagento , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
