### PR TITLE
[Backport] MAGETWO-91411: Delete action in grid could be sent multiple times

### PR DESCRIPTION
**Pull request by novikor**
### Fixed Issues (if relevant)
Mass delete deletes all products #15935

### Manual testing scenarios
See #15935 for instructions

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by iivashchenko — APPROVED** [review]
Approved

**Comment by novikor** [comment]
I will cope with failed tests.

**Comment by novikor** [comment]
Please merge the PR

**Comment by VladimirZaets** [comment]
Hi @novikor. Currently your PR in QA status. After PR was verified the PR will be merged. Thanks

**Comment by magento-engcom-team** [comment]
Hi @novikor. Thank you for your contribution. 
We will aim to release these changes as part of 2.1.15. 
Please check the release notes for final confirmation.

**Comment by greenwichecomm** [comment]
I have Magento 2.2.4 and we had the mass delete happen last night, 12,000 products were deleted until we had 0 left.   Please elaborate on the fix

**Comment by iivashchenko** [comment]
@greenwichecomm as I see [Magento 2.2.4](https://github.com/magento/magento2/blob/2.2.4/app/code/Magento/Ui/Component/MassAction/Filter.php) doesn't have changes, provided under that ticket. You can update your instance or apply the corresponding patch.

**Pull request merged**
