### PR TITLE
#23208: fixed bug with loading section data after each request

### PR DESCRIPTION
**Pull request by vicobohdan**
### Description (*)

changed variable name to correct one

### Fixed Issues (if relevant)

1. magento/magento2#23208: bad code refactoring causes loading section data after each request

### Manual testing scenarios (*)

1. refresh page more times - section data (with same type) must load only once not after each request.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23282) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23282) before we can accept your contribution.<br/><hr/>**bvico** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by vicobohdan** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @vicobohdan. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @vicobohdan, here is your [new Magento instance](https://pr-23282.instances.magento-community.engineering).
Admin access: [https://pr-23282.instances.magento-community.engineering/admin](https://pr-23282.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by vicobohdan** [comment]
I'm not be able to duplicate bug from automated Functional tests 

> MAGETWO-99025: Estimate Shipping and Tax block sections on shipping cart saving correctly for Guest.

on test instance. After logout my cart is empty....

**Comment by sidolov** [comment]
Hi @vicobohdan  , please, sign CLA, otherwise, we can't process your pull request

**Comment by vicobohdan** [comment]
I signed CLA.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5353](https://jira.corp.magento.com/browse/ENGCOM-5353) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@vicobohdan thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by engcom-Foxtrot** [comment]
@magento-admin run functional tests build

**Comment by engcom-Foxtrot** [comment]
@vicobohdan thank you for contribution.
Unfortunately, your PR brokes persistent shopping cart functionality, that is indicated by functional test failure. Please fix it.
Steps to reproduce:
1. Enable Persistent Shopping Cart (go to Stores > Settings > Configuration > Customers > Persistent Shopping Cart and set Enable Persistence = Yes, Clear Persistence on Sign Out = No).
2. Create a Product.
3. Create and log in as Customer.
4. Add the Product to cart.
5. Log out (Product still present in a Shopping Cart).
6. Delete persistent_shopping_cart cookie.
7. Reload the page (Shopping Cart should become empty).

**Comment by vicobohdan** [comment]
Do you kidding me? :D Does not work even in magento "vanilla" 2.3.1... It's not my bug, however I don't understand for what is 'Persist Shopping Cart' option in configuration, persist cart works only if 'Clear Persistence on Sign Out' option is set to No! 
I checked code in observer module-persistent/Observer/SynchronizePersistentOnLogoutObserver.php
there is condition only for persistent/options/enable and  persistent/options/logout_clear from config

Screenshot from 2019-06-26 13-54-16

So I guess this bug haven't any relation to this issue. I don't know for what there is 'Persist Shopping Cart' option. If you think there are something wrong with persist cart / config options or whatever pls open new issue/or if working correct with 'Clear Persistence on Sign Out' set to No, test must be fixed.

**Comment by hostep** [comment]
@vicobohdan, it looks like Magento devs just pushed some commits on the `2.3-develop` branch which manipulates the same code you were changing: https://github.com/magento/magento2/commit/a9ceb1acdce1b2026f8b5658cb0f9fa092506aba#diff-57700c9d2035d3ee7dfcc487f3732902

Can you check if the issue you were encountering is now fixed on the `2.3-develop` branch by this commit and maybe then this PR is no longer necessary? (since the code you were trying to change is now removed)

Thanks!

**Comment by erfanimani** [comment]
Hmm, the store ID check has been removed completely — I guess that would fix it.

I'm just wondering, is there any way we can see the contents of `magento-performance/MC-18191`?

**Comment by sidolov** [comment]
Hi @erfanimani check for the storeId has been removed, because we should clear customer data when the user changes the website instead of the store. I'm closing this PR as not relevant. 
Thank you for your contribution!

**Pull request closed without merging**
