### PR TITLE
Textarea patch 1

### PR DESCRIPTION
**Pull request by textarea**
### Description (*)
On modal setTitle() call, subTitle tag get erased and not appended any more, caused by:
modalSubTitle: '[data-role="sub**T**itle"]'

### Fixed Issues (if relevant)
1. magento/magento2#26141: Modal Popup and Custom subTitle erased

### Manual testing scenarios (*)
1. Create a popup or custom modal with a title and subtitle.
2. Change title with setTitle() method

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by krzksz — CHANGES_REQUESTED** [review]
I think we should rather change the selector in JavaScript file to `[data-role="subtitle"]` as I wasn't able to find camel case `data-role` attribute value anywhere else in Magento.

**Comment by textarea** [comment]
Hi @krzksz, as you prefer, but there are different camel case data-role attributes, for example:
modalCloseBtn: '[data-role="closeBtn"]' in the same modal.js file.

**Review by krzksz — APPROVED** [review]
That's true I don't know why I didn't find it when searching through the files.

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-6517](https://jira.corp.magento.com/browse/ENGCOM-6517) has been created to process this Pull Request
:eight_spoked_asterisk: @krzksz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by krzksz** [comment]
Hi @textarea, great contribution!
Due to Magento Definition of Done all code must be covered by tests. Please cover your fix by auto test.

**Comment by engcom-Golf** [comment]
I will take care of test coverage

**Comment by textarea** [comment]
Thanks @Nazar65 !

**Review by krzksz — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Golf** [comment]
failed Functional Tests B2B Not related to the changes in this PR

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-6517](https://jira.corp.magento.com/browse/ENGCOM-6517) has been created to process this Pull Request

**Comment by slavvka** [comment]
@textarea Please fix failing Unit test

**Comment by Nazar65** [comment]
I will fix them

**Comment by Nazar65** [comment]
@slavvka done :heavy_check_mark:

**Pull request merged**
