### PR TITLE
Fix missing escape Url method

### LINKED ISSUE #30036: [Issue] Fix missing escape Url method
This issue is automatically created based on existing pull request: magento/magento2#30008: Fix missing escape Url method

### Description (*)

Correct missing escape url in layout template module widget

### Preconditions
1. Magento 2.4-develop

### Steps to reproduce (*)

1. Go to Admin 
1. Go Content > Elements > Widgets
1. Edit one exists widget

### Expected result (*)
1. Page should load without break
1. Add layout update should work

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Correct missing escape url in layout template module widget

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Go to Admin 
2. Go Content > Elements > Widgets
3. Edit one exists widget
4. Page should load without break
5. Add layout update should work

For test edit widget add/delete "Layout Updates" we need merge the PR https://github.com/magento/magento2/pull/29991 first 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30036: Fix missing escape Url method

### CODE REVIEW

**Comment by rogyar** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento create issue

**Review by sidolov — CHANGES_REQUESTED** [review]
@mrtuvn could you please cover changes with automated test?

**Comment by mrtuvn** [comment]
@sidolov i'm not sure how to start a test with such case
@engcom-Alfa @engcom-Charlie can you give any suggest on test cover?

**Comment by mrtuvn** [comment]
In my opinion this case we don't have to cover with automated tests

**Comment by mrtuvn** [comment]
@magento give me test instance

**Comment by engcom-Charlie** [comment]
@mrtuvn you can write an integration test on the block which uses a template changed by this PR and checks if the additional code is present.
Thank you.

**Comment by mrtuvn** [comment]
@engcom-Charlie Can you help with cover by mftf ? I'm not familiar with mftf test

**Comment by engcom-Charlie** [comment]
@mrtuvn Here is all information https://devdocs.magento.com/mftf/docs/introduction.html. If you will have any questions, let me know.
Thank you.

**Comment by mrtuvn** [comment]
@magento run all tests
I think no need cover this PR with automated tests. Instead we can manually test. This file used in admin area so it's will not affected or impact to another area

**Comment by engcom-Charlie** [comment]
@mrtuvn can you please add additional info on how to reproduce the issue manually?
Thank you.

**Comment by mrtuvn** [comment]
rebase mainline code base + add fix static tests

**Comment by engcom-Charlie** [comment]
@magento run Static Tests

**Comment by engcom-Charlie** [comment]
@mrtuvn I'll take care of test coverage.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-8312](https://jira.corp.magento.com/browse/ENGCOM-8312) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by sivaschenko** [comment]
QA: Please consider including https://github.com/magento/magento2/pull/29991 during testing if needed to unblock required scenarios

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Layout Update** can be added successfully and displayed correctly 
### Manual testing scenario
1. Go to **Content - Widgets**. Click **Add Widget** 
2. Select for example 
_Type_ - _CMS Page Link_
_Design Theme_ - _Magento Blank_
click **Continue**
3. Add several **Layout Updates**
4. Specify different _Diaplay on_, _Products_, _Container_, _Template_ for each added **Layout Update**
5. Assert that all the **Layout Updates** are displayed correctly 

### Actual result
add_layout


**NOTE that the bug with Deleting is not fixed in this PR**
widget_before

**Comment by engcom-Bravo** [comment]
Further investigation discovered that if there are a lot of _Layout Updates_ added, and after the web page is refreshed, it's taking some time for the options to load
widge_load

@sivaschenko @sidolov Please see if this is acceptable

**Pull request merged**
