### PR TITLE
Skip ProcessManagerTest w/o pcntl extension

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
Unit tests are failing with no errors when this extension is missing

```bash
./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist
```
image

That was caused by `app/code/Magento/Indexer/Test/Unit/Model/ProcessManagerTest.php` test. It was running `exit(1)` in the test when pcntl extension wasn't available.

I added "skip" for this test in case if the `pcntl` extension isn't available.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by xmav** [comment]
Hi @ihor-sviziev
Do you have list of failed tests ?

**Comment by ihor-sviziev** [comment]
@xmav,
I provided the screenshot, there no failed tests, the PHPUnit command just failing w/o any errors.

**Comment by ihor-sviziev** [comment]
Static test failure looks not related to changes from this PR.

**Comment by xmav** [comment]
You may try to change log config to show test names instead of dots. So we will know last test before phpunit termination

**Comment by ihor-sviziev** [comment]
@xmav, could you provide example of how can we show the tests?

**Comment by ihor-sviziev** [comment]
@xmav If fails on the following output:
image

The command I executed is following:
```
./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist --testdox
```

**Comment by ihor-sviziev** [comment]
Hi @xmav,
That was `app/code/Magento/Indexer/Test/Unit/Model/ProcessManagerTest.php` test. It was running `exit(0)` in the test when pcntl extension wasn't available. I force-pushed my changes

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Looks like failing tests are not related to changes from this PR.

**Comment by ihor-sviziev** [comment]
@xmav, I just updated the PR, also double-checked - it still works fine w/o the pcntl extension

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by andrewbess — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, thank you for the review.
[ENGCOM-9237](https://jira.corp.magento.com/browse/ENGCOM-9237) has been created to process this Pull Request
:eight_spoked_asterisk: @andrewbess, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9237](https://jira.corp.magento.com/browse/ENGCOM-9237) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Dash** [comment]
@ihor-sviziev, @Den4ik and @andrewbess  Thanks for your contribution and collaboration. 
I have followed below steps to reproduce the issue and not able to reproduce it on 2.4-develop
1. I have removed pcntl extention (disabled it from php.ini file)
2. executed the unit test ./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist --testdox and observers testcases successfully passed as shown in the below screenshot
Screenshot 2022-01-06 at 3 10 28 PM

**Comment by engcom-Alfa** [comment]
Hi @ihor-sviziev and @Den4ik 
According to the [above-comment](https://github.com/magento/magento2/pull/34116#issuecomment-1006417365), issue is not actually reproducible! Please let us know the exact procedure to reproduce the test failure.
Thanks in advance

**Comment by ihor-sviziev** [comment]
@engcom-Alfa @engcom-Dash,
It looks like you didn't disable that PHP extension. Could you show your output of `php -m | grep pcntl`?

**Comment by engcom-Dash** [comment]
@ihor-sviziev  
We have removed the extension pcntl and then executed the unit test ./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist --testdox and observers testcases successfully passed. 
Below is the screenshot of succesfully executed test case and result of php -m | grep pcntl

Screenshot 2022-01-08 at 12 51 32 AM

**Comment by ihor-sviziev** [comment]
@engcom-Dash will check it later, thx

**Comment by ihor-sviziev** [comment]
@engcom-Dash,
The screenshot you provided actaully shows the issue.

Example:
```bash
./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist --testdox app/code/Magento/Indexer/Test/Unit/Console/Command/
```
shows the success message, timings, and returns 0 return code (success):
image

But 
```bash
./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist --testdox app/code/Magento/Indexer/Test/Unit/Model/
```
doesn't show the success message, timings, and returns 1 return code (failure)
image

**Comment by engcom-Dash** [comment]
@ihor-sviziev 
I have rerun the test case and below is the updated screenshot which is showing

✅ shows the success message
✅ shows timings
✅ returns 0 return code (success):

Screenshot 2022-01-10 at 6 37 46 PM

**Comment by ihor-sviziev** [comment]
@engcom-Dash please contact me in the engcom slack for better understanding

**Comment by engcom-Dash** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Removed the pcntl extension and result of php -m | grep pcntl is blank (below is the screenshot for same)
2. Executed the test case ‘./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist --testdox app/code/Magento/Indexer/Test/Unit/Model/’
3. Test case has been executed successfully 
	✅ shows the success message
	✅ shows timings
	✅ returns 0 return code (success)
 

**Before:** :heavy_multiplication_x:  We are not getting the successful testcase message 

Screenshot 2022-01-11 at 1 45 37 PM


**After:** :heavy_check_mark: Test case has been executed successfully with successful testcase message.

Screenshot 2022-01-11 at 12 43 51 PM

Since this PR is related to unit testing and all automated testcase are passing hence there is no additional testing required as part of regression.

**Pull request merged**
