### PR TITLE
#23354 : Data saving problem error showing when leave blank qty and update it

### PR DESCRIPTION
**Pull request by konarshankar07**
### Description (*)

Error message added if qty field left empty when qty is updated in multishipping.
### Fixed Issues (if relevant)

1. magento/magento2#23354 : Data saving problem error showing when leave blank qty and update it

### Manual testing scenarios (*)

1. Front end -> Login into account
2. Add more than 2 products to the cart
3. From cart go to checkout with multiple addresses
4. Qty leave blank and click on Update Qty & Addresses
5. Error message "Qty field cannot be empty"

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by orlangur — CHANGES_REQUESTED** [review]
Please add client side validation instead and remove this one.

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

**Review by orlangur — CHANGES_REQUESTED** [review]
Hi @konarshankar07, I meant a validation on JavaScript side - `required-entry` rule or something.

**Comment by konarshankar07** [comment]
Hello @orlangur 
Sorry, my bad. I'll update the code.
Thanks

**Review by orlangur — CHANGES_REQUESTED** [review]
@konarshankar07 great, looks perfect now!

Please squash changes into a single commit so that we have perfectly clean history 😉

**Comment by konarshankar07** [comment]
Hello @orlangur 

As per your request, I squashed all my commit and now getting an error in automated testing. Can you please help me out to fix this?

Thanks

**Comment by konarshankar07** [comment]
Hello @orlangur ,

Do you still have any queries with this pull request?

Thanks

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-5398](https://jira.corp.magento.com/browse/ENGCOM-5398) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
