### PR TITLE
Wishlist-icon-not-align-on-mobile-view ::Wishlist icon not align on m…

### PR DESCRIPTION
**Pull request by ajay2jcommerce**
…obile view

### Fixed Issues (if relevant)

1. magento/magento2 #20502: Wishlist icon not align on mobile view

### Manual testing scenarios (*)

1. login the customer.
2. Add the Simple product and Downloadable product.
3. Go to Shopping cart.
4. Switch mobile view.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ajay2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by mage2pratik** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik, here is your [new Magento instance](https://pr-20506.instances.magento-community.engineering).
Admin access: [https://pr-20506.instances.magento-community.engineering/admin](https://pr-20506.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by mage2pratik** [comment]
@ajay2jcommerce : Wishlist icon overlapped when "Gift Options" is enabled for simple product.
Please go through the HTML structure and check is there any element persist or not. I've attached image regarding the issue:

screenshot-20506-1

**Review by mage2pratik — CHANGES_REQUESTED** [review]
Wishlist icon overlapped when "Gift Options" is enabled for simple product. Please go through the HTML structure and check is there any element persist or not.

**Comment by ajay2jcommerce** [comment]
Hi @mage2pratik, 
I have made changes regarding overlapped when "Gift Options"  is enabled for simple product.

**Comment by mage2pratik** [comment]
Hi @ajay2jcommerce : Design glitch after click on Gift icon.

**Expected/Default result (*):**
screenshot-20506-2

**Actual result (*)**
screenshot-20506-3

**Comment by ajay2jcommerce** [comment]
Hi @mage2pratik I have made changes regarding Design glitch after click on Gift icon. 
Please review.

Thanks
Ajay

**Comment by ajay2jcommerce** [comment]
Hi @magento-engcom-team please review.

**Comment by torhoehn** [comment]
@ajay2jcommerce Please don't change any assignments we made before. I think @mage2pratik will progress here.

**Comment by ajay2jcommerce** [comment]
Hi 
@magento-engcom-team please review.

**Review by mage2pratik — APPROVED** [review]

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-20506.instances.magento-community.engineering).
Admin access: [https://pr-20506.instances.magento-community.engineering/admin](https://pr-20506.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @ajay2jcommerce. Thanks for collaboration.
Class "no-display" should hide the element, what the reason to move in to left 0?

**Comment by VladimirZaets** [comment]
Hi, @ajay2jcommerce , I took your PR into processing, thank you for collaboration.

**Pull request closed without merging**
