### PR TITLE
Fix type error in ConfigureFedexDefaults.php (PHP 7.1 Compatibility)

### PR DESCRIPTION
**Pull request by marvinhinz**
### Description (*)
This error happens to me on setup:install / setup:upgrade:
`PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /srv/htdocs/foobar/htdocs/prod/releases/179/magento/vendor/magento/module-fedex/Setup/Patch/Data/ConfigureFedexDefaults.php:104`

This code path is not always executed because it depends on config values, so i guess thats why its not fixed/reported yet. 
On php7.1 the following change was introduced: "The empty index operator is not supported for strings anymore"

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable) 
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by marvinhinz** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Hi @marvinhinz,
Could you provide some steps to reproduce this issue? What PHP version are you using?

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Integration Tests, WebAPI Tests

**Comment by marvinhinz** [comment]
> Hi @marvinhinz,
> Your changes look good, but not clear what the issue it's causing.
> Could you provide what are the steps to reproduce, the actual and expected results? What PHP version are you using?

Hello @ihor-sviziev, i think it happens because of migrated config values from M1 to M2. In an empty/clean magento2 installation the condition in line 99 will not be triggered i guess.

**Review by Den4ik — APPROVED** [review]
✅ Changes looks good with correct logic
@marvinhinz I'm approve this changes.

Failed functional test is not related to the changes

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9165](https://jira.corp.magento.com/browse/ENGCOM-9165) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by Den4ik** [comment]
Code logic looks correct, but in this case I think it's not so easy test it manually.

**Comment by ihor-sviziev** [comment]
As discussed with @Den4ik in Slack - covering this case with unit tests will take way more time than fixing this issue.

**Comment by ihor-sviziev** [comment]
Hi @marvinhinz,
Could you provide what result are you getting before applying the changes? 
```sql
SELECT *
FROM core_config_data
WHERE path = 'carriers/fedex/allowed_methods';
```

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by marvinhinz** [comment]
> Hi @marvinhinz,
> Could you provide what result are you getting before applying the changes?
> 
> ```sql
> SELECT *
> FROM core_config_data
> WHERE path = 'carriers/fedex/allowed_methods';
> ```

One row with following data:

`EUROPE_FIRST_INTERNATIONAL_PRIORITY,FEDEX_1_DAY_FREIGHT,FEDEX_2_DAY_FREIGHT,FEDEX_2_DAY,FEDEX_2_DAY_AM,FEDEX_3_DAY_FREIGHT,FEDEX_EXPRESS_SAVER,FEDEX_GROUND,FIRST_OVERNIGHT,GROUND_HOME_DELIVERY,INTERNATIONAL_ECONOMY,INTERNATIONAL_ECONOMY_FREIGHT,INTERNATIONAL_FIRST,INTERNATIONAL_GROUND,INTERNATIONAL_PRIORITY,INTERNATIONAL_PRIORITY_FREIGHT,PRIORITY_OVERNIGHT,SMART_POST,STANDARD_OVERNIGHT,FEDEX_FREIGHT,FEDEX_NATIONAL_FREIGHT`

**Comment by marvinhinz** [comment]
@Den4ik can this be merged or is there anything left i can do?

**Comment by Den4ik** [comment]
> @Den4ik can this be merged or is there anything left i can do?

@marvinhinz This PR will be merged by position in PRs list

**Pull request merged**
