### PR TITLE
Unset rather than set null that delete the value

### LINKED ISSUE #9186: REST API catalogProductRepositoryV1 overwriting default values
# Preconditions

1. Magento 2
### Steps to reproduce

This demonstration is only with a single storeview, but can be reproduced with multiple storeviews or multiple websites like already mentioned by a bunch of other reporters above

1. Setup a clean Magento installation using the 2.2-develop branch (I used commit eb84c5393da)
2. Go into the backend
3. Make a note of the default storeview code, it's `default` (we'll need this later when we create an API request)
4. Create a new product:
    - name: "Base"
    - SKU: "base"
    - price: 100
    - description: "Base"
    - short description: "Base"

5. Look at the various `catalog_product_entity_int`, `catalog_product_entity_text`, `catalog_product_entity_varchar` tables in the database, they contain only values for store_id = 0, this is **good so far**!
6. Still in the backend, go to System > Integrations and add a new integration with full access
7. Activate the new integration and take a note of the 'access token' (example: `abc`)
8. Execute the following curl command, which only updates the "name" attribute, using the storeview code from 3, and the access token from 7:
```
curl -k -X PUT -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer abc" -d "{ \"product\": { \"name\": \"New name on storeview level\" }}" https://domain/rest/default/V1/products/base
```

9. Go back in the backend and take a look at the product, but switch to the 'Default Store View' scope.
10. It is expected that the 

11. Also take a look at the database again, to the `catalog_product_entity_int`, `catalog_product_entity_text`, `catalog_product_entity_varchar` tables, it is expected you'll only see one entry for store_id = 1, but there are like 10 entries, **not good**!

# Expected result

Only attribute where the checkmark "Use Default Value" is unchecked is for the attribute "name"

# Actual result

All the following attributes now also have a value on storeview level, which is not what is expected:
    - status
    - tax class
    - visibility
    - description
    - short description
    - url key
    - meta title
    - meta keywords
    - meta description
    - display product options in

### LINKED ISSUE #26484: Updating a product through the API unchecks "Use Default Value" on a bunch of attributes
When you update a product. For example adding an image using the API. Which is totally unrelated to anything else, such as editing price.

The checkbox "Use Default Value" becomes unchecked on a bunch of attributes, such as price.

This turns into a problem when you want to edit the product later, update the price, or the description etc. and nothing happens. So you have to change store view scope to that particular store, check the box "Use Default Value" and save to be able to change the price.

This should not happen in the first place.

### Preconditions (*)

1. Magento 2.3.3
2. 2 store views

### Steps to reproduce (*)

1. Create 2 store views
2. Add a new product with a price
3. Change store view on the product. You can see "Use Default Value" for price is checked.
4. Update the product using the API, for example uploading an image
5. View the product again and change store scope
6. Notice the "Use Default Value" on price is now unchecked (amongst other attributes)

### Expected result (*)

Checkbox "Use Default Value" should remain checked until a user actually unchecks it.

### Actual result (*)

Checkbox "Use Default Value" unchecks itself when you update the product using the API for all store views.

### Additional info 
I just re-produced it on 2.4-dev.

Seems to be a problem with scopes.

In addition to the steps above, do the following:

1. Stores > All Stores. Click "Main Website Store" and change "Default Store View" to the second store view

image

2. Open "Default Store View" and change to status to disabled
3. Go into product, select scope "Default store view" (first store) Click "Use Default Value" on everything. Save.
4. Change store scope to second store view. Click "Use Default Value" on everything. Save.
5. Change scope to second store view again. A bunch of "Use Default Value" are unchecked.

image

### LINKED ISSUE #31083: MAGENTO 2.3.5 /V1/products overwrite default values on multi-store site even when only one field is sent to update
### Preconditions (*)

1. V:2.3.5, 2.4-develop
2. Product API (catalogProductRepositoryV1)

### Steps to reproduce (*)

1. Configure all store view to run under one domain E.G: dev.test. 
2. Set one more Environment apart from default website/store/store view.
3. E.G: IE
Screen Shot 2020-11-27 at 19 26 08
4. Create product on all store view using postman or any other tool:
**URL:** `rest/all/V1/products`
**BODY**
```
{
  "product": {
    "sku": "test-1",
    "name": "Test 1",
    "attribute_set_id": 4,
    "price": 10,
    "status": 1,
    "visibility": 4,
    "type_id": "simple",
    "weight": 100
  },
  "saveOptions": true
}
```
5. Update product name for IE store view:
**URL:** `rest/en-ie/V1/products`
**BODY:**
```
{
  "product": {
    "sku": "test-1",
    "name": "Test 1 changed",
  },
  "saveOptions": true
}
```

### Expected result (*)

1. When API for en-ie is sent I expect only product name changed/updated for that store view

### Actual result (*)

1. Instead all values previously sent for all store view have the checkbox unchecked and populated with the all store view data therefore this values cannot be updated using the all store views again 
2.
Screen Shot 2020-11-27 at 19 49 03

Thanks

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### LINKED ISSUE #32544: Magento 2.3: "Use Default Value" gets unchecked for Multiple Attributes when updating with an API
### Preconditions (*)

1. Magento 2.3
2. Multiple Store Views.

### Steps to reproduce (*)

1. Bulk Insert new products on Magento 2 backend and all affected product attributes are checked by default
2. To connect the Sales to our Warehouse Management System, we need to create the same items to Dearsystems and BULK List the items to create a connection. But, we are using Magento 2 as master source of products. Dearsys only receives data from M2.
3. After Bulk Listing, go to Magento 2 Default Store View. You'll notice attributes are not checked anymore. Which causes a lot of issues to update all manually.

### Expected result (*)

1. All attributes should remain checked and should FOLLOW the Default value which is checked.

### Actual result (*)

1. Attributes are no longer checked under Default Store View.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### LINKED ISSUE #33052: [API] Product Repository Problem in upcoming 2.4.3 release -> MC-39481
### Description

Original issue -> https://github.com/magento/magento2/issues/31083 (MAGENTO 2.3.5 /V1/products overwrite default values on multi-store site even when only one field is sent to update)

Related commit that will be released in 2.4.3 -> https://github.com/magento/magento2/commit/6a27b0ce155a418e05bf6a7753af5a947af5668e

Original problem is fixed but another one was created. Now the opposite thing is happening

I'm pasting my comment from the original issue here for context.

> @hostep After trying the patch (https://github.com/magento/magento2/search?q=MC-39481&type=commits) to 2 magento instances. One 2.4.2 and one 2.3.5-p2 it creates a different problem.
> 
> The problem that @lano-vargas said was fixed but a new issue arised.
> 
> Let's say you have 1 website and 2 store views again.
> 
> You create a product via API and then you try to update the product via API -> PUT @ domain/rest/{{store_code}}/V1/products/{{sku}} and change your locale values like the name. It works great so far.
> 
> but then if you try to make another call to the same store view but change only ONE custom attribute, it then ticks off the use default again for all the attributes that were unchecked by the explicit api call that came before this one.
> 
> So if you changed the name to be specific to the locale, it gets lost and uses the default value once again.
> 
> ex.
> 
> { "product": { "custom_attributes": [ { "attribute_code": "my_attribute", "value": "test_value" } ] } }
> 

Proposed solution is:

If I explicitly changed something, for example the name of the product @domain/rest/{{store_code}}/V1/products/{{sku}} and then I make another call, but only for one attribute, for example the price, do not check "use default value" for the website and store view attributes. 

This is a major issue because data will be lost with the above example.

### Preconditions (*)
Tried in both Magento 2.3.5-p2 & Magento 2.4.2 

M 2.3.5-p2 with php73
M 2.4.2 with php74

Have some attributes in website or store view scope

### Steps to reproduce (*)
Create a product via API

Update the product with it's locale data @domain/rest/{{store_code}}/V1/products/{{sku}
Make another call changing only 1 attribute, for example the price @domain/rest/{{store_code}}/V1/products/{{sku}

### Expected result (*)
All the attributes should stay as is on the store view and only the attribute in the request should change.

### Actual result (*)
The changed attributes from the first PUT request get their checkbox "use default value" checked resulting in locale data loss.

### PR DESCRIPTION
**Pull request by thomas-kl1**
### Description (*)

The idea of 6a27b0ce155a418e05bf6a7753af5a947af5668e was to prevent inherited values to be saved on current scope when "use default/website" is checked. Sadly the implementation has some false positive case that lead to delete the values that were originally saved on current scope.
The goal was actually to ignore those cases, so we shouldn't use the setData($attributeCode) which set to null, but unsetData($attributeCode) which remove the reference of the attribute instead of setting null.

### Related Commits

- https://github.com/magento/magento2/commit/6a27b0ce155a418e05bf6a7753af5a947af5668e

### Fixed Issues (if relevant)

1. Fixes [magento/magento2#31083](https://github.com/magento/magento2/issues/31083)
2. Fixes [magento/magento2#26484](https://github.com/magento/magento2/issues/26484)
3. Fixes [magento/magento2#33052](https://github.com/magento/magento2/issues/33052)
4. Fixes [magento/magento2#32544](https://github.com/magento/magento2/issues/32544)
4. Fixes [magento/magento2#9186](https://github.com/magento/magento2/issues/9186)

### Manual testing scenarios (*)

1. Run bulk async products api with partial updates
2. There is no data loss

### Questions or comments

This is critical, please process it asap as it may cause data loss on products on many websites.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by thomas-kl1** [comment]
@magento run all tests

**Comment by thomas-kl1** [comment]
Not sure about the failures, not everything seems to be related, any thoughts?

**Comment by thomas-kl1** [comment]
@magento run all tests

**Comment by thomas-kl1** [comment]
@magento run all tests

**Comment by blacktek** [comment]
@thomas-kl1 do you have plans to fix the failed tests? this is a very severe issue that is blocking us to go live with the new M2.4.5

Thank you for your help, much appreciated!

**Comment by thomas-kl1** [comment]
Hello @blacktek you can add a thumb up to the PR so it's prioritized and Adobe would take a look on this issue

**Comment by blacktek** [comment]
> PR



> Hello @blacktek you can add a thumb up to the PR so it's prioritized and Adobe would take a look on this issue

Hello thomas, done! but it seems that checks failed and you need extra work to make them passing, right? it's a very severe issue

**Comment by thomas-kl1** [comment]
@magento run all tests

**Comment by thomas-kl1** [comment]
https://github.com/magento run all tests

**Comment by thomas-kl1** [comment]
Hello @Den4ik 

Could you take a look there? I know that many UT needs to be refactored/fixed, but this is a critical issue we do face with our customers.

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @thomas-kl1,

Need to take care of all the failed tests like WebAPI, Integration tests etc.

Thanks

**Comment by blacktek** [comment]
Hello,
  I'll be out of office until the 11st of April.

I'll reply on my return.

Kind Regards,
TT

**Comment by engcom-Echo** [comment]
@magento run all test

**Comment by blacktek** [comment]
Hello,
  I'll be out of office until the 25th of April.

I'll reply on my return.

Kind Regards,
TT

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by thomas-kl1** [comment]
@engcom-Echo I didn't had time to work on it since, I need some time

**Comment by engcom-Echo** [comment]
@thomas-kl1 are you going to take care of the build fixes or should we proceed now?

**Comment by thomas-kl1** [comment]
Hello @engcom-Echo 

Thank you, if you are ready to work on these, please proceed, really appreciated 😄

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all test

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Hi @thomas-kl1 

Thank you for your contribution!
While going through the PR, I have found that some regression issue is getting created by this PR changes.
In order to reproduce the issue, I have followed below steps.
1. Create two new product **product 1(Bag)** and **product2(Jacket)**
2. Now through `rest/default/V1/products` Api we have tried to update _product2_ name with _product1_. We are getting error
```
       {
    		"message": "URL key for specified store already exists."
	}
```
3. Product2 name is changed to anything else it changes correctly and after that if we try to change product 2 name to product1 it works fine. For reference I have attached a video.

https://github.com/magento/magento2/assets/51681435/9c1d0147-ff18-41b9-99eb-d3e4992d60ca


@thomas-kl1 can you please have a look at above issue?

**Comment by thomas-kl1** [comment]
@engcom-Echo I did a rollback of the urlKey case: https://github.com/thomas-kl1/magento2/commit/98fff3bd438063922e8c7d47fc10f4a26d3e2a27 

Does it fix the behavior?

**Comment by engcom-Echo** [comment]
> Does it fix the behavior?

@thomas-kl1 let me reverify the issue and come back.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
> 

@thomas-kl1 it fixes the issue. Thanks

**Comment by engcom-Echo** [comment]
> @engcom-Echo I did a rollback of the urlKey case: [thomas-kl1@98fff3b](https://github.com/thomas-kl1/magento2/commit/98fff3bd438063922e8c7d47fc10f4a26d3e2a27)
> 
> Does it fix the behavior?

@thomas-kl1 Thanks for the quick response! Yes it does fixes the [mentioned](https://github.com/magento/magento2/pull/36493#issuecomment-1556723137) issue.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Unit Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Lima** [comment]
Hi @thomas-kl1 ,

Thanks for your contribution and collaboration.

Please provide us information that this PR fixes below issues mentioned in the above [comment] or not (https://github.com/magento/magento2/pull/36493#issue-1455777709):

1. Fixes https://github.com/magento/magento2/issues/31083
2. Fixes https://github.com/magento/magento2/issues/26484
3. Fixes https://github.com/magento/magento2/issues/33052
4. Fixes https://github.com/magento/magento2/issues/32544
5. Fixes https://github.com/magento/magento2/issues/9186

As we have observed that issues still reproducible after taking PR changes.

Thanks

**Comment by thomas-kl1** [comment]
@engcom-Lima actually it won't fix them, it fixes a bug introduced by the changes of their fixes.
When setData($attributeCode) was used, it results with unwanted data-loss.

**Comment by engcom-Lima** [comment]
@thomas-kl1  Please provide us in detailed steps to reproduce the issue.

Thanks 🙂

**Comment by thomas-kl1** [comment]
@engcom-Hotel you should use the webapi async endpoints in order to reproduce the issue. Calls must be done for all, then scoped by store.

**Comment by engcom-Lima** [comment]
Hi @thomas-kl1 ,

Thanks for your contribution and collaboration.

Kindly provide us update on above [comment](https://github.com/magento/magento2/pull/36493#issuecomment-1570179199) as soon as possible.

Thanks

**Comment by engcom-Lima** [comment]
Hi @thomas-kl1 ,

Thanks for your conttribution and collaboration.

This PR is not updated from long time. We assume the issue had been resolved. Hence, closing this PR. Please feel free to reopen this incase if you still facing any issue.

Thanks

**Comment by engcom-Lima** [comment]
@thomas-kl1 Please have a look on this [comment](https://github.com/magento/magento2/pull/36493#issuecomment-1570179199). If we are missing anything please inform to us.

**Pull request closed without merging**
