### PR TITLE
Issue-4053. Cannot create full datetime product attribute

### PR DESCRIPTION
**Pull request by maciejtrybula**
### Fixed Issues (if relevant)

1. magento/magento2#4053: Cannot create full datetime product attribute

### Manual testing scenarios

1. Go to Admin Panel -> Catalog -> Products
2. Edit any product from list
3. Click on the attribute "Set product as New To" calendar
4. Time pick should be visible, choose any time and save the product
5. After save time should be set on this attribute (optionally you can check this in `catalog_product_entity_datetime` table)

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15315) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=15315) before we can accept your contribution.<br/>

**Comment by sidolov** [comment]
Hi @Szpadyzor , changing the default value for datepicker may affect all existing usages in client code and break functionality in 3d party extensions. You can override default value by [widget configuration during initialization](https://github.com/magento/magento2/pull/15315/files#diff-0db7607bf6150e0c896ddb1526e18866R40)

**Comment by maciejtrybula** [comment]
@sidolov 
Right, i didn't saw that.
So what do You think, it is better to leave it like it is, or give user ability to save this value with or without time?

**Comment by orlangur** [comment]
@Szpadyzor try to achieve what is described in issue without touching default value.

**Comment by sidolov** [comment]
Hi @Szpadyzor , looks like the issue caused by misconfiguration, can I close this PR as not relevant?

**Comment by orlangur** [comment]
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.

**Pull request closed without merging**
