### PR TITLE
Removing unused .htaccess.sample

### PR DESCRIPTION
**Pull request by steverobbins**
The existence of `.htaccess.sample` is legacy code included from Magento 1.  It's only purpose was for the `Enterprise_Staging` module when creating a new stage/site.

e.g.

```
$sample = file_get_contents(BP . DS . '.htaccess.sample');
// ...
$outputFile = $this->getBaseFolder() . DS . $this->_website->getCode() . DS . '.htaccess';
file_put_contents($outputFile, $sample);
```

Since this repository only hosts the Community Edition and there are zero references to this file in the code base, this file is obsolete and should be removed.

### CODE REVIEW

**Comment by Vinai** [comment]
Thank you for the PR! We are currently waiting for the travis builds to work again, which should happen in a few days. Once that is running and the tests are green we can continue to process your contribution.
Even though your patch doesn't really affect any functionality covered by tests, having the tests pass is a required step of the process of accepting PRs. Thank you for understanding.

**Comment by mazhalai** [comment]
@steverobbins Please merge latest from develop and rerun builds.

**Comment by steverobbins** [comment]
Rebased on develop.

**Comment by steverobbins** [comment]
Rebased on `develop`.

**Comment by arkadiych** [comment]
@steverobbins, thank you for your contribution! 
We won’t remove .htaccess.sample. We have similar sample files for php.ini and nginx.conf. This .htaccess.sample file will allow you rollback your changes in origin .htaccess file in case of modifications.

**Comment by steverobbins** [comment]
Well, the `php.ini` and `nginx.conf` are necessary since they need to be configured higher up than the Magento application.  This `.htaccess` is the only one that has an original and copy.

You shouldn't use a `.sample` (`.bak`, etc) for rollbacks.  That's what version control is for.  If they don't use version control they can always come here for reference.

Again, it's not a file for reference, it's a file from a previous EE 1.x feature.

**Comment by okorshenko** [comment]
@steverobbins , as we already informed you, our architects decided keep this file in code base for merchants convenience. We distribute Magento code via composer, git and archive files (which are out of version control system).
Thank you for your patience and contribution to Magento!

**Pull request closed without merging**
