### PR TITLE
Fix handling of mixins for modules with no dependencies defined

### LINKED ISSUE #28340: [Issue] Fix handling of mixins for modules with no dependencies defined
This issue is automatically created based on existing pull request: magento/magento2#27690: Fix handling of mixins for modules with no dependencies defined

---------

### Description (*)
This PR addresses an issue that was outlined in https://github.com/magento/magento2/pull/25587#issuecomment-611074021 and investigated by me afterwards.

This is a regression I have introduced when refactoring mixins module, but it applies only in two cases which are not present in the Magento itself:
```javascript
// Module defined as anything else then a function with dependencies skipped.
define('my-module', {
  foo: 'bar'
});
// Module defined with dependencies passed as "null".
define('my-module', null, {
  foo: 'bar'
});
```
which both results in special case where second element of RequireJS's `defQueue` is `null` and made the script throw an error when somebody required such module.

### Manual testing scenarios (*)
1. Open the store.
2. Open browser console.
3. Paste and execute the following code:
```javascript
define('my-module', {
  foo: 'bar'
});
require(['my-module', function(){});
```
4. Verify that no error similar to `TypeError: Cannot read property 'map' of null` is thrown.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by krzksz**
### Description (*)
This PR addresses an issue that was outlined in https://github.com/magento/magento2/pull/25587#issuecomment-611074021 and investigated by me afterwards.

This is a regression I have introduced when refactoring mixins module, but it applies only in two cases which are not present in the Magento itself:
```javascript
// Module defined as anything else then a function with dependencies skipped.
define('my-module', {
  foo: 'bar'
});
// Module defined with dependencies passed as "null".
define('my-module', null, {
  foo: 'bar'
});
```
which both results in special case where second element of RequireJS's `defQueue` is `null` and made the script throw an error when somebody required such module.

### Manual testing scenarios (*)
1. Open the store.
2. Open browser console.
3. Paste and execute the following code:
```javascript
define('my-module', {
  foo: 'bar'
});
require(['my-module', function(){});
```
4. Verify that no error similar to `TypeError: Cannot read property 'map' of null` is thrown.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28340: Fix handling of mixins for modules with no dependencies defined

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]
Failing functional test not related to changes from this PR>

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7447](https://jira.corp.magento.com/browse/ENGCOM-7447) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**
1. Go to Storefront;
2. Open browser console;
3. Paste and execute the following code:
```javascript
define('my-module', {
  foo: 'bar'
});
require(['my-module'], function(){});
```
**Before:** :heavy_check_mark: 
Screenshot from 2020-04-17 10-49-52

**After:** :heavy_multiplication_x: 
Screenshot from 2020-04-17 10-54-11

**Comment by sdzhepa** [comment]
@magento run Functional Tests B2B,Functional Tests CE

**Comment by sdzhepa** [comment]
@magento create issue

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B,Functional Tests CE

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Pull request merged**
