### PR TITLE
[MFTF] Add new ActionGroup

### LINKED ISSUE #29539: [Issue] [MFTF] Add new ActionGroup
This issue is automatically created based on existing pull request: magento/magento2#29472: [MFTF] Add new ActionGroup

---------
This PR add new `StorefrontCheckoutClickNextButtonActionGroup` for clicking next button on checkout page

### PR DESCRIPTION
**Pull request by Usik2203**
This PR add new `StorefrontCheckoutClickNextButtonActionGroup` for clicking next button on checkout page

### Resolved issues:
1. [x] resolves magento/magento2#29539: [MFTF] Add new ActionGroup

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by VladimirZaets** [comment]
@magento run all tests

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7991](https://jira.corp.magento.com/browse/ENGCOM-7991) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento create issue

**Pull request merged**
