### PR TITLE
[Lib] Fix previous attempts to correct wrong behaviour of collapsible library

### PR DESCRIPTION
**Pull request by Den4ik**
### Description (*)

This PR provide complete fix for wrong behaviour of collapsible library on product page and category page.
Previous fix was broke category page filter behaviour

### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/pull/23390

### Manual testing scenarios (*)

1. Go to category page
2. Try to click onto filter headers
3. Expected that the page will not make strange jumps

### Expected result
r06vh_2019-07-24_16-27-23
pp81n_2019-07-24_16-24-59

### Actual result
9o16q_2019-07-24_16-32-42

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Den4ik** [comment]
@sidolov could you check this PR. Previous fix was broke catalog filters collapse

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5600](https://jira.corp.magento.com/browse/ENGCOM-5600) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

**Before:**
before

**After:**
after

**Comment by Karlasa** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Karlasa. Thank you for your request. I'm working on Magento instance for you

**Comment by Karlasa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Karlasa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Karlasa, here is your [Magento instance](https://i-23862-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23862-2-3-develop.instances.magento-community.engineering/admin](https://i-23862-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Pull request merged**
