### PR TITLE
33206: Removed lib/web/es6-collections.js  and replaced usages with native JS

### LINKED ISSUE #33206: Eliminate es6-collections.js
**Depends on MutationObserver.js elimination**: https://github.com/magento/magento2/issues/33207

Remove `lib/web/es6-collections.js` and replace usages with native JS.

The es6-collections are providing the following polyfills:
- **WeakMap** - ✔ supported https://caniuse.com/mdn-javascript_builtins_weakmap
https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/lib/web/es6-collections.js#L8-L22
- **Map** - ✔ supported https://caniuse.com/mdn-javascript_builtins_map
https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/lib/web/es6-collections.js#L24-L46
- **Set** - ✔ supported https://caniuse.com/mdn-javascript_builtins_set
https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/lib/web/es6-collections.js#L48-L67
- **WeakSet** - ✔ supported https://caniuse.com/mdn-javascript_builtins_weakset
https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/lib/web/es6-collections.js#L69-L80

Following the investigation in: https://github.com/magento/magento2/issues/32851

### PR DESCRIPTION
**Pull request by anzin**
### Description (*)

I've removed lib/web/es6-collections.js and replaced usages with native JS

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33206

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Unit Tests, WebAPI Tests

**Comment by ihor-sviziev** [comment]
@magento run Unit Tests

**Review by Den4ik — APPROVED** [review]
✅ Looks ok for me

Failed tests is not related to changes

**Comment by ihor-sviziev** [comment]
@sivaschenko @sidolov, could you provide some info on why the unit tests are failing w/o any errors in the results?

**Comment by andrewbess** [comment]
@magento run Functional Tests B2B

**Comment by andrewbess** [comment]
@magento run Unit Tests

**Review by andrewbess — APPROVED** [review]

**Comment by andrewbess** [comment]
@magento run Unit Tests

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, thank you for the review.
[ENGCOM-9136](https://jira.corp.magento.com/browse/ENGCOM-9136) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
@anzin @andrewbess Jascript Unit test `grunt spec` are failing with the following error:

ReferenceError: Can't find variable: WeakMap at
http:/localhost:8000/pub/static/frontend/Magento/blank/en_US/Magento_Ui/js/lib/registry/registry.js:16
http:/localhost:8000/pub/static/frontend/Magento/blank/en_US/requirejs/require.js:1650 execCb
http:/localhost:8000/pub/static/frontend/Magento/blank/en_US/mage/requirejs/resolver.js:156 execCb
http:/localhost:8000/pub/static/frontend/Magento/blank/en_US/requirejs/require.js:866 check
http:/localhost:8000/pub/static/frontend/Magento/blank/en_US/requirejs/require.js:1143 enable
http:/localhost:8000/pub/static/frontend/Magento/blank/en_US/requirejs/require.js:774 init
 http:/localhost:8000/pub/static/frontend/Magento/blank/en_US/requirejs/require.js:1170 callGetModule
http:/localhost:8000/pub/static/frontend/Magento/blank/en_US/requirejs/require.js:1544 completeLoad
http:/localhost:8000/pub/static/frontend/Magento/blank/en_US/requirejs/require.js:1671 onScriptLoad

**Review by sivaschenko — CHANGES_REQUESTED** [review]
@anzin @andrewbess Jascript Unit test grunt spec are failing with the following error:

ReferenceError: Can't find variable: WeakMap at
http:/localhost:8000/pub/static/frontend/Magento/blank/en_US/Magento_Ui/js/lib/registry/registry.js:16
http:/localhost:8000/pub/static/frontend/Magento/blank/en_US/requirejs/require.js:1650 execCb
http:/localhost:8000/pub/static/frontend/Magento/blank/en_US/mage/requirejs/resolver.js:156 execCb
http:/localhost:8000/pub/static/frontend/Magento/blank/en_US/requirejs/require.js:866 check
http:/localhost:8000/pub/static/frontend/Magento/blank/en_US/requirejs/require.js:1143 enable
http:/localhost:8000/pub/static/frontend/Magento/blank/en_US/requirejs/require.js:774 init
http:/localhost:8000/pub/static/frontend/Magento/blank/en_US/requirejs/require.js:1170 callGetModule
http:/localhost:8000/pub/static/frontend/Magento/blank/en_US/requirejs/require.js:1544 completeLoad
http:/localhost:8000/pub/static/frontend/Magento/blank/en_US/requirejs/require.js:1671 onScriptLoad

**Comment by ihor-sviziev** [comment]
Looks like WeekMap isn't supported by library for js unit tests. Can we add it only for tests?

**Comment by sivaschenko** [comment]
@anzin @andrewbess if the WeakMap isn't supported by the library for js unit tests can you please take a look if this issue can be resolved by updating npm packages or (less preferable) adding an additional dependency to package.json

**Comment by ihor-sviziev** [comment]
FYI here is a WIP PR for updating the js unit test library https://github.com/magento/magento2/pull/33429.

**Comment by ihor-sviziev** [comment]
I just ran the tests on the local machine - we have more than 100 failing tests with a new version. It's definitely not easy to fix them altogether.
I think it's better to keep the old version for now.

**Comment by andrewbess** [comment]
@mageno run Unit Tests

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
> @anzin @andrewbess if the WeakMap isn't supported by the library for js unit tests can you please take a look if this issue can be resolved by updating npm packages or (less preferable) adding an additional dependency to package.json

I believe that we can use es6-collections polyfilll at js tests due to unsupport es6 by phantomjs.
Something like attached patch file
[es6-collections-in-js-tests.tar.gz](https://github.com/magento/magento2/files/6780057/es6-collections-in-js-tests.tar.gz)

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2b, WebAPI Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Review by andrewbess — APPROVED** [review]

**Review by ihor-sviziev — APPROVED** [review]

**Comment by andrewbess** [comment]
Hello @Den4ik @sivaschenko 
All tests have been run successfully.
The ignoring of the eslint and jscs were added because the file added to tests is original es6-collections.js from the `lib/web/` directory.
Please approve this changes.
Thank you in advance.

**Pull request merged**
