### PR TITLE
Removed inline JavaScript from template

### PR DESCRIPTION
**Pull request by pivulic**
## Problem

Difficult to extend the **catalogAddToCart** widget due to Inline JavaScript, something you strongly are against to according to: http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/javascript/js_init.html

### CODE REVIEW

**Comment by orlangur** [comment]
I didn't try to understand this logic deeply but it looks like your changes changed the semantics.

Before that only for 

```
<?php if ($block->isRedirectToCartEnabled()) : ?>
```

false condition this initialization occured.

Also, product/view/form template received knowledge about addToCart which is not correct. Should be done within initial template similar to positive branch of {{if}}:

```
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
```

**Comment by daim2k5** [comment]
@pivulic Thank you for your contribution. Please accept the contributors license agreement so this PR can be further processed. This can be done by clicking the "Details" link next to the "license/cla" check below.

**Comment by pivulic** [comment]
I have now clicked the **Details** link and accepted the license. But here it says I still haven't, maybe a temporary glitch?

Not sure what you meant @orlangur, could you maybe commit your changes the way you think it should be? The idea is basically to remove the Inline JavaScript from addtocart.phtml

**Comment by daim2k5** [comment]
@pivulic maybe because your githib email adress is not public? Maybe you can check...

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-53439

**Comment by orlangur** [comment]
@pivulic, I'm not going to rework this code, just tried to describe why current changes seem doubtful to me.

So here is an example of correct inline JavaScript elimination in this file: https://github.com/magento/magento2/commit/f1917377578523634c687218ce635f48d2e404a5#diff-bcc11b36af8eaf52078666d9755945beL46 (note that there is still `<script>` tag but the code became declarative)

Here is where `if` condition was introduced: https://github.com/magento/magento2/commit/7c1abf6dc7bf014df739e804df856d006e050e2d#diff-bcc11b36af8eaf52078666d9755945beL48

Correct implementation should result in two declarative `<script>` blocks in both branches of `if` statement within `app/code/Magento/Catalog/view/frontend/templates/product/view/addtocart.phtml` file, without hardcoding of addtocart into `app/code/Magento/Catalog/view/frontend/templates/product/view/form.phtml` file and without `<?php if ($block->isRedirectToCartEnabled()) : ?>` logic breakage.

/cc @guz-anton

**Comment by anton-huz** [comment]
HI @pivulic ,
As you can find we abandon your fix but issue got an attention.

First of all we made usage `catalogAddToCart` alias, second fix was proper _declarative initialization_.

Please review if suitable for you. Current PR I close. Fill free to comment if any notice you have.

**Comment by pivulic** [comment]
Nice!

**Pull request closed without merging**
