### PR TITLE
Remove unused comments from _initDiscount() function

### PR DESCRIPTION
**Pull request by mageprince**
### Description

Remove unused comments from _initDiscount() function of Tax.php
### Fixed Issues (if relevant)

N/A
### Manual testing scenarios

N/A
### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mageprince. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by VladimirZaets** [comment]
Hi @mageprince. Thanks for the collaboration. Remove commented code is ok, but 
 due to [Magento backward-compatible guide](http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/) we can't change method signature. The method should, as previously returns `void`.

**Comment by mageprince** [comment]
@VladimirZaets Thanks for the review. I have updated method signature.

**Comment by magento-engcom-team** [comment]
Hi @mageprince. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Pull request merged**
