### PR TITLE
Fix #22747 - JavaScript modules contain unnecessary define checks

### LINKED ISSUE #22747: JavaScript modules contain unnecessary define checks
Many Magento 2 RequireJS modules start with a check for the presence of RequireJS' "define" function. I wonder if this check is (still) necessary, or that it may be removed.

As far as I can tell "require.js" is the first JavaScript file that is loaded on every Magento 2 page, both frontend and backend. It is loaded synchronously, so all other JavaScript must be executed after this file has completed its execution. It is this file that ensures that the "define" function exists, and that it contains the 'amd' attribute.

Is the above code a remnant of the past in which the presence of RequireJS was uncertain, or is there still an important use case that is underdocumented?

### Preconditions (*)

1. This issue occurs in all Magento 2 versions to date.

### Steps to reproduce (*)

1. Visit translate.js or any other JavaScript file in Magento that contains the following code

```
if (typeof define === 'function' && define.amd) {
```

https://github.com/magento/magento2/blob/2.3-develop/lib/web/mage/translate.js

### Expected result (*)

1. If the check serves no function, I suggest it be removed from over 100 files in Magento 2 code. It takes up space, time, and makes these files harder to understand for a student of Magento.

```
define([
    'jquery',
    'mage/mage'
], function($){
    // module body
});
```

### Actual result (*)

1. The code now looks like this:

```
(function (factory) {
    if (typeof define === 'function' && define.amd) {
        define([
            'jquery',
            'mage/mage'
        ], factory);
    } else {
        factory(jQuery);
    }
}(function ($) {
    // module body
})

```

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This is cleanup for #22747

### Fixed Issues (if relevant)

1. magento/magento2#22747: JavaScript modules contain unnecessary define checks

### Manual testing scenarios (*)

1. Check files in codebase - Magento JS files used by requireJS shouldn't contain define checks

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5994](https://jira.corp.magento.com/browse/ENGCOM-5994) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @Bartlomiejsz. Could you resolve merge conflicts?

**Comment by Bartlomiejsz** [comment]
Hi @engcom-Alfa, done

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5994](https://jira.corp.magento.com/browse/ENGCOM-5994) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
