### PR TITLE
Create Security.md file to show on GitHub Security/Policy page

### PR DESCRIPTION
**Pull request by piotrekkaminski**
### Description (*)
Create Security.md file to show on GitHub Security/Policy page as default policy

### Manual testing scenarios (*)
Check GitHub Security tab

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23067) <br/>All committers have signed the CLA.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5189](https://jira.corp.magento.com/browse/ENGCOM-5189) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@piotrekkaminski thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by soleksii** [comment]
QA not applicable

**Comment by kalpmehta** [comment]
@piotrekkaminski Very good idea. Thanks for creating the Github Security tab.

**Pull request merged**
