### PR TITLE
Mark interfaces as api url rewrite graphql wishlist 2.4

### LINKED ISSUE #32023: Mark UrlRewriteGraphQl, User, Vault, Webapi, Widget and Wishlist interfaces as API
The following interfaces should be marked as API in 2.4-develop branch

1. app/code/Magento/UrlRewriteGraphQl/Model/Resolver/UrlRewrite/CustomUrlLocatorInterface.php
1. app/code/Magento/User/Model/Spi/NotificationExceptionInterface.php
1. app/code/Magento/User/Model/Spi/NotificatorInterface.php
1. app/code/Magento/Vault/Block/Customer/IconInterface.php
1. app/code/Magento/Webapi/Controller/Rest/RequestProcessorInterface.php
1. app/code/Magento/Widget/Block/BlockInterface.php
1. app/code/Magento/Wishlist/Controller/IndexInterface.php
1. app/code/Magento/Wishlist/Controller/WishlistProviderInterface.php
1. app/code/Magento/Wishlist/Model/AuthenticationStateInterface.php
1. app/code/Magento/Wishlist/Model/ResourceModel/Item/Product/CollectionBuilderInterface.php
1. app/code/Magento/Wishlist/Model/Wishlist/BuyRequest/BuyRequestDataProviderInterface.php

### PR DESCRIPTION
**Pull request by vlmed**
### Description (*)
Recreated PR  from https://github.com/magento/magento2/pull/32076

The following interfaces marked as API:

1. app/code/Magento/UrlRewriteGraphQl/Model/Resolver/UrlRewrite/CustomUrlLocatorInterface.php
2. app/code/Magento/User/Model/Spi/NotificationExceptionInterface.php
3. app/code/Magento/User/Model/Spi/NotificatorInterface.php
4. app/code/Magento/Vault/Block/Customer/IconInterface.php
5. app/code/Magento/Webapi/Controller/Rest/RequestProcessorInterface.php
6. app/code/Magento/Widget/Block/BlockInterface.php
7. app/code/Magento/Wishlist/Controller/IndexInterface.php
8. app/code/Magento/Wishlist/Controller/WishlistProviderInterface.php
9. app/code/Magento/Wishlist/Model/AuthenticationStateInterface.php
10. app/code/Magento/Wishlist/Model/ResourceModel/Item/Product/CollectionBuilderInterface.php
11. app/code/Magento/Wishlist/Model/Wishlist/BuyRequest/BuyRequestDataProviderInterface.php

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32023

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by vlmed** [comment]
@gabrieldagama  I recreated https://github.com/magento/magento2/pull/32076 PR to 2.4-develop

**Comment by eduard13** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8987](https://jira.corp.magento.com/browse/ENGCOM-8987) has been created to process this Pull Request

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama the branch with code successfully imported into`magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-32660`.

**Pull request merged**
