### PR TITLE
Remove extra semicolon

### PR DESCRIPTION
**Pull request by rspl1006**
Remove extra semicolon

### CODE REVIEW

**Comment by mazhalai** [comment]
@rspl1006 please sign the CLA, and sync with latest develop.
Internal ticket MAGETWO-50222

**Comment by mazhalai** [comment]
@rspl1006 We cannot accept this PR without the CLA.

**Comment by rspl1006** [comment]
I have signed CLA, please let me know if anything else required.

**Comment by ishakhsuvarov** [comment]
Hi @rspl1006 

Unfortunately CLA was not signed correctly. Most likely it happened because the email you have used for the commit is not included into github profile. 

Could you please update information and try signing again? You may use this [CLA Assistant link](https://cla.dev.magento.com/magento/magento2?pullRequest=3647) for this.

Thank you for collaboration!

**Pull request merged**
