### PR TITLE
[MFTF] use action group to go to customer account

### LINKED ISSUE #29842: [Issue] [MFTF] use action group to go to customer account
This issue is automatically created based on existing pull request: magento/magento2#29835: [MFTF] use action group to go to customer account

---------
This PR uses `StorefrontOpenMyAccountPageActionGroup` for navigation to customer account

### PR DESCRIPTION
**Pull request by Usik2203**
This PR uses `StorefrontOpenMyAccountPageActionGroup` for navigation to customer account

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/316

### Resolved issues:
1. [x] resolves magento/magento2#29842: [MFTF] use action group to go to customer account

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@Usik2203 Are you able to verify Magento B2B and Magento EE errors in MFTF compilation?

**Comment by sidolov** [comment]
@magento create issue

**Comment by lbajsarowicz** [comment]
The issue is caused by reference in Magento EE:
```
 ! [NOTE] Merge Error - Step could not be found in either TestXML or DeltaXML.                                          
 !                      Test: 'OnePageCheckoutWithAllProductTypesAndGiftCardProductTest'        TestStep:                           
 !        'checkOrderInStorefront'      LinkedStep: 'waitForCustomerDashboardPageLoad' in Test                               
 !        "OnePageCheckoutWithAllProductTypesAndGiftCardProductTest"                                                    
 !        /var/www/html/.ee/app/code/Magento/GiftCard/Test/Mftf/Test/OnePageCheckoutWithAllProductTypesAndGiftCardProduc
 !        tTest.xml                                                                                                     
 !                                                         
```

**Review by lbajsarowicz — CHANGES_REQUESTED** [review]
Please review the issues in Magento 2 EE / B2B.
We need to replace the references there.

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE ,

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
> Please review the issues in Magento 2 EE / B2B.
> We need to replace the references there.

Hi @lbajsarowicz 
Done

**Review by lbajsarowicz — APPROVED** [review]
✔️  Perfect, thank you!

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-8143](https://jira.corp.magento.com/browse/ENGCOM-8143) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8143](https://jira.corp.magento.com/browse/ENGCOM-8143) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by gabrieldagama** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by gabrieldagama** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by gabrieldagama** [comment]
@magento run all tests

**Pull request merged**
