### PR TITLE
Update date component template

### PR DESCRIPTION
**Pull request by lucscu**
### Description
Added readonly attribute to fix mobile possibility to insert custom text with opened keyword.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14875) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
@LucScu thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VladimirZaets** [comment]
Hi @LucScu , please, sign CLA, otherwise, we can't process your pull request

**Comment by VladimirZaets** [comment]
Hi @LucScu , thank you for collaboration. Currently, we want to have the ability to change a date uses `datepicker` or input field for that. 
Also, we can't merge this PR because your fix is backward incompatible.
[Read more about backward compatibility in Magento](http://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/index.html)

As a workaround you can add the `readonly` setting for `date` component, that should be disabled as default, but we will have the ability to change it by passing the value to the configuration.

**Pull request closed without merging**
