### PR TITLE
Fix Image cache clean comment

### PR DESCRIPTION
**Pull request by jonasGossiaux**
### Description (*)
The old comment was a copy/paste from the clean media function which cleans js and css, but this function cleans the images.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by jonasGossiaux** [comment]
@magento run all tests

**Comment by jonasGossiaux** [comment]
@magento run all tests

**Comment by jonasGossiaux** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
This PR already merged and shouldn't have pending review status

**Pull request merged**
