### PR TITLE
Remove white space from admin Customer edit address

### PR DESCRIPTION
**Pull request by Dharmeshvaja91**
### Description (*)

 Admin  customer edit address tab there is unnecessary label element available.
### Manual testing scenarios (*)

1. Admin >> Customers >> Edit Customer 
2. Go to Addresses 

### Actual Result (*)
actual-result

### Expected Result (*)
expected-result

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Dharmeshvaja91. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4293](https://jira.corp.magento.com/browse/ENGCOM-4293) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @Dharmeshvaja91 , thanks for the pull request. I think the issue is not actual anymore as the design of customer addresses page has been changed.
image
Can you please check on the latest 2.3-develop code base.

**Comment by Dharmeshvaja91** [comment]
> Hi @Dharmeshvaja91 , thanks for the pull request. I think the issue is not actual anymore as the design of customer addresses page has been changed.
> image
> Can you please check on the latest 2.3-develop code base.

okk @sivaschenko i will check this on vanilla instance.

**Comment by Dharmeshvaja91** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Dharmeshvaja91. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Dharmeshvaja91, here is your [Magento instance](https://i-21256-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21256-2-3-develop.instances.magento-community.engineering/admin](https://i-21256-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sidolov** [comment]
@Dharmeshvaja91 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
