### PR TITLE
increase length of sales_order_payment:last_trans_id from 32 to 100

### PR DESCRIPTION
**Pull request by ghost**
txn_id field in sales_payment_transaction table is length 100, since last_trans_id in the sales_order_payment table links directly to that field both should be of the same type and length. Personally I found out as the transaction IDs of the payment gateway I'm trying to integrate is more than 32 characters long.

I'm not sure if this needs to be added on an db update script at this point.

### CODE REVIEW

**Comment by daim2k5** [comment]
Hi @martinebiz could you please accept the CLA?

**Comment by martinebiz** [comment]
done @daim2k5

**Comment by daim2k5** [comment]
@martinebiz please one more time because CLA service crashed ;-)

**Comment by martinebiz** [comment]
done @daim2k5 ;)

**Comment by NadiyaS** [comment]
Hi @martinebiz ,
thank you for contribution and we are sorry for delay.
Internal ticket number is MAGETWO-46672.

**Comment by ao** [comment]
Could somebody please merge this?

**Comment by dcapilla** [comment]
Sorry I don't have permissions.

**Comment by aakimov** [comment]
Hello @martinebiz,

Unfortunately we cannot accept your pull request as is.
Magento 2 has been already released, so all related DB changes must be added to DB update script.

Moreover your fix will be accepted **only** if Magento installs without failures on MySQL Cluster.
As you probably know, MySQL Cluster NDB 7.0 and later support a maximum row length of 14 KB (not including BLOB values) i.e. increasing column length can theoretically violate this restriction.

Thank you for understanding and sorry for the response delay.

**Comment by SerhiyShkolyarenko** [comment]
Closing PR as not updated more than 14 days.

**Pull request closed without merging**
