### PR TITLE
When customer re-order an order created from another storeview, Graph…

### LINKED ISSUE #29974: [GraphQl bug] Couldn't re-order in in different store
### Preconditions (*)

**1. Create order by graphql (pwa-studio)
2. Magento 2.4.0**

### Steps to reproduce (*)

I have 2 store (English, Arabic).
1. Login as customer account
2. Create an order at English storeview
3. After order complete, switch to Arabic storeview then navigate to: Customer account -> order history
4. Try to re-order item.
5. I received the message: **_Order number "%1" doesn't belong to the current customer_**

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by codynguyen1**
### Description (*)
When customer re-order an order created from another storeview, GraphQl returned error:
"Order number "%1" doesn\'t belong to the current customer"
Actually it's because the order getting function is using curren store from context to get the order model. According to the original source of magento, the current store id checking is not neccessary:
vendor/magento/module-sales/Controller/AbstractController/Reorder.php (at line 87)

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29974

### Manual testing scenarios (*)

I have 2 store (English, Arabic).

1. Login as customer account
2. Create an order at English storeview
3. After order complete, switch to Arabic storeview then navigate to: Customer account -> order history
4. Try to re-order item.
5. I received the message: Order number "%1" doesn't belong to the current customer

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by edenduong — CHANGES_REQUESTED** [review]
Hi @codynguyen1,

Thank you for your contribution. As Magento Definition of Done, could you please cover your changes by Automation Test?

**Comment by edenduong** [comment]
@magento run all tests

**Comment by codynguyen1** [comment]
@magento run all tests

**Comment by codynguyen1** [comment]
@magento run all tests

**Review by edenduong — APPROVED** [review]
Thank you !

**Comment by magento-engcom-team** [comment]
Hi @edenduong, thank you for the review.
[ENGCOM-8305](https://jira.corp.magento.com/browse/ENGCOM-8305) has been created to process this Pull Request

**Review by edenduong — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @edenduong, thank you for the review.
[ENGCOM-8305](https://jira.corp.magento.com/browse/ENGCOM-8305) has been created to process this Pull Request

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8305](https://jira.corp.magento.com/browse/ENGCOM-8305) has been created to process this Pull Request

**Review by edenduong — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @edenduong, thank you for the review.
[ENGCOM-8305](https://jira.corp.magento.com/browse/ENGCOM-8305) has been created to process this Pull Request

**Comment by engcom-Lima** [comment]
Hi @codynguyen1,

Thanks for your contribution and collaboration.

We have tried to reproduce the issue but the issue is not reproducible to me in the latest `2.4-develop`. Kindly recheck it in the latest `2.4-develop` if you are facing any issues please inform us.

Screenshot 2023-08-22 at 3 01 53 PM
Screenshot 2023-08-22 at 3 01 59 PM
Screenshot 2023-08-22 at 3 01 37 PM


Thanks

**Comment by engcom-Lima** [comment]
Hi @codynguyen1 ,


Please do the needful.

**Comment by engcom-Lima** [comment]
Hi @codynguyen1 ,

We are closing this PR as there is no latest update on it. Please feel free to reopen it in case you are facing any issues.

**Pull request closed without merging**
