### PR TITLE
32853: Upgraded legacy-build.min.js to the latest version

### PR DESCRIPTION
**Pull request by anzin**
### Description (*)

I've upgraded legacy-build.min.js to the latest version

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32853

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by anzin** [comment]
@magento run all tests

**Comment by anzin** [comment]
@magento run all Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by Den4ik — APPROVED** [review]
✅ Changes looks ok for me.
As mentioned @andrewbess failed Functional Tests related to unavailable currency convert API service

**Comment by anzin** [comment]
@magento run all Functional Tests CE

**Comment by anzin** [comment]
@magento run all Functional Tests CE

**Comment by anzin** [comment]
@magento run Functional Tests CE

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@anzin Could you check EE compilation locally?

**Pull request merged**
