### PR TITLE
Uncommented mod_expires and mod_deflate from .htaccess

### PR DESCRIPTION
**Pull request by miguelbalparda**
#4390 & #1615

### CODE REVIEW

**Comment by zekefarwell** [comment]
+1.  Looks like a no brainer to me.

**Comment by choukalos** [comment]
+1; Thanks @miguelbalparda - I pinged internally to raise priority of accepting this PR.

**Comment by choukalos** [comment]
Hey @miguelbalparda - I chatted with the front-end team about this PR; we can't accept this PR.  Sounds like most of this PR will already be covered by planned work for all upcoming releases (aka 2.2, 2.1.3, 2.0.11).  
- Pub/Static & Pub/Media have .htaccess settings already for mod_expires and mod_headers
- mod_deflate is a gap; but it's been added to the ticket; as always for it to work merchant needs to have appropriate mod installed & configured on their server.
- Also you didn't make the changes to the htaccess.sample file

So per discussion with the team closing this PR; you should see the equivalent changes in our upcoming patch releases.

**Comment by miguelbalparda** [comment]
Got it, thanks for the quick reply and tell the team(s) they are doing an amazing work!

**Comment by miguelbalparda** [comment]
@choukalos can we revisit this one?

**Pull request closed without merging**
