### PR TITLE
Remove "Administrators" name from the query to fetch an administrators role

### LINKED ISSUE #36998: [Issue] Remove "Administrators" name from the query to fetch an administrators role
This issue is automatically created based on existing pull request: magento/magento2#36971: Remove "Administrators" name from the query to fetch an administrators role

---------

### Description (*)
When we set up a review environment with the production database and we try to create an admin account, we get the "No Administrators role was found, data fixture needs to be run" error.

This is because the query searches for a role actually named "Administrators", but our client renamed the "Administrators" role to "All rights". Looking for a role with exactly that name isn't needed since it'll just use the first one it finds with the correct rights. This change makes sure it'll just use the first matching role it finds, regardless of name.

```
mysql> select * from authorization_role WHERE parent_id = 0 AND tree_level = 1 AND role_type = 'G' AND user_id = 0 AND user_type = 2 ORDER BY sort_order DESC LIMIT 1;
+---------+-----------+------------+------------+-----------+---------+-----------+--------------+
| role_id | parent_id | tree_level | sort_order | role_type | user_id | user_type | role_name    |
+---------+-----------+------------+------------+-----------+---------+-----------+--------------+
|       1 |         0 |          1 |          1 | G         |       0 | 2         | All rights   |
+---------+-----------+------------+------------+-----------+---------+-----------+--------------+
```

### Fixed Issues (if relevant)

No issue created.

### Manual testing scenarios (*)

1. Rename the "Adminstrators" role to something else
2. Run `bin/magento admin:user:create --admin-user=johndoe --admin-firstname=John --admin-lastname=Doe --admin-password=JohnDoe123 --admin-email="johndoe@example.com"`

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36997: Remove "Administrators" name from the query to fetch an administrators role

### PR DESCRIPTION
**Pull request by peterjaap**
### Description (*)
When we set up a review environment with the production database and we try to create an admin account, we get the "No Administrators role was found, data fixture needs to be run" error.

This is because the query searches for a role actually named "Administrators", but our client renamed the "Administrators" role to "All rights". Looking for a role with exactly that name isn't needed since it'll just use the first one it finds with the correct rights. This change makes sure it'll just use the first matching role it finds, regardless of name.

```
mysql> select * from authorization_role WHERE parent_id = 0 AND tree_level = 1 AND role_type = 'G' AND user_id = 0 AND user_type = 2 ORDER BY sort_order DESC LIMIT 1;
+---------+-----------+------------+------------+-----------+---------+-----------+--------------+
| role_id | parent_id | tree_level | sort_order | role_type | user_id | user_type | role_name    |
+---------+-----------+------------+------------+-----------+---------+-----------+--------------+
|       1 |         0 |          1 |          1 | G         |       0 | 2         | All rights   |
+---------+-----------+------------+------------+-----------+---------+-----------+--------------+
```

### Fixed Issues (if relevant)

1. [x] resolves magento/magento2#36998: Remove "Administrators" name from the query to fetch an administrators role

### Manual testing scenarios (*)

1. Rename the "Adminstrators" role to something else
2. Run `bin/magento admin:user:create --admin-user=johndoe --admin-firstname=John --admin-lastname=Doe --admin-password=JohnDoe123 --admin-email="johndoe@example.com"`

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36998: Remove "Administrators" name from the query to fetch an administrators role

### CODE REVIEW

**Review by fredden — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento give me test instance

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

1. Rename the "**Adminstrators**" role to something else
2. Run **`bin/magento admin:user:create --admin-user=johndoe --admin-firstname=John --admin-lastname=Doe --admin-password=JohnDoe123 --admin-email="johndoe@example.com"`**

**Before:** :heavy_multiplication_x: Admin is not getting created from the terminal when Administrator name is changed.

Screenshot 2023-03-07 at 6 33 08 PM


**After:** :heavy_check_mark:  Now able to create.

Screenshot 2023-03-08 at 1 34 30 PM
Screenshot 2023-03-08 at 1 34 56 PM
Screenshot 2023-03-08 at 1 37 16 PM
Screenshot 2023-03-08 at 1 42 51 PM

**Additionally tested:**

- Created multiple administrator.
- Logged in with created admin in step1.
- Done the invoice,creditmemo and shipment from all the admin created.
- Created multiple role by giving priviledges

Builds are failed , hence, moving this PR to **Extended Testing**.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by fredden** [comment]
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
Functional Tests EE, Functional Tests CE,Functional Tests B2B failure are different on last two run on same commit.
Functional Tests EE
Run1
EE-36971

Run2
EE2-36971


Functional Tests CE
Run1
CE-36971

Run2
CE2-36971

Functional Tests B2B
Run1
B2b-36971

Run2
B2b2-36971

Hence moving to `Merge In Progress`

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by hostep** [comment]
It looks like this PR got merged in 2.4-develop recently via: https://github.com/magento/magento2/commit/d4a9791d0f589ee1006beba25c240a39a59d50e9

But this PR is not marked as merged, which is quite strange? I've found at least 3 other PR's where the same thing happened, any idea what's going on here? A bug in github? A mistake made by Adobe? Something else? ...

**Comment by engcom-Charlie** [comment]
> It looks like this PR got merged in 2.4-develop recently via: [d4a9791](https://github.com/magento/magento2/commit/d4a9791d0f589ee1006beba25c240a39a59d50e9)
> 
> But this PR is not marked as merged, which is quite strange? I've found at least 3 other PR's where the same thing happened, any idea what's going on here? A bug in github? A mistake made by Adobe? Something else? ...

Hi @hostep,

It is not a bug, after adding this this PR into mainline PR, we have added one commit of merging 2.4-dev into this, that is the reason it is still showing as in Open status

Thank you!

**Comment by ihor-sviziev** [comment]
@engcom-Charlie, since both commit was from you (https://github.com/magento/magento2/commit/5344e89f48ede3eaff34fcd17d52801685dd59c3 merged changes to the internal branch and https://github.com/magento/magento2/pull/36971/commits/5eb89b5f466d83f67b1011a1d75683faf46180b1 merged 2.4-develop branch to the PR branch), could you please next time make sure all commits from PR will be included to the internal branch for merging to prevent not marking PR as merged in the future?
Thank you in advance!

**Comment by ihor-sviziev** [comment]
Changes from this PR was merged in https://github.com/magento/magento2/commit/5344e89f48ede3eaff34fcd17d52801685dd59c3

**Pull request closed without merging**
