### PR TITLE
Minicart-search-logo-not-vertically-aligned

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Fixed Issues (if relevant)

1. magento/magento2#20905: Minicart, search & logo not vertically aligned between 640 to767 device pixel.

### Manual testing scenarios (*)

1..Go to frontend -> resize screen (min width 640 and max width 767)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by cedarvinda** [comment]
@magento-engcom-team give me test instance.

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda, here is your [new Magento instance](https://pr-20955.instances.magento-community.engineering).
Admin access: [https://pr-20955.instances.magento-community.engineering/admin](https://pr-20955.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by torhoehn — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @torhoehn, thank you for the review.
[ENGCOM-4118](https://jira.corp.magento.com/browse/ENGCOM-4118) has been created to process this Pull Request

**Comment by Karlasa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Karlasa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Karlasa, here is your [new Magento instance](https://pr-20955.instances.magento-community.engineering).
Admin access: [https://pr-20955.instances.magento-community.engineering/admin](https://pr-20955.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by Karlasa — CHANGES_REQUESTED** [review]
@amol2jcommerce  @torhoehn 
I don't agree with these changes. 
Code should follow coding standards and each component change should be placed into correct module design file. 
For correct fix there are really no need for extra lines of code, just breakpoint for design should be changed from @screen__s to @screen__m 
example in: https://github.com/magento/magento2/blob/ba66e00c4869c8ec8930888b126bb1ad5ed8a633/app/design/frontend/Magento/luma/Magento_Theme/web/css/source/_module.less#L425

https://github.com/magento/magento2/blob/ba66e00c4869c8ec8930888b126bb1ad5ed8a633/app/design/frontend/Magento/luma/Magento_CatalogSearch/web/css/source/_module.less#L202
and
https://github.com/magento/magento2/blob/ba66e00c4869c8ec8930888b126bb1ad5ed8a633/app/design/frontend/Magento/luma/Magento_Checkout/web/css/source/module/_minicart.less#L414

**Review by torhoehn — CHANGES_REQUESTED** [review]
@Karlasa Ah, you're right.

**Comment by amol2jcommerce** [comment]
Hi @Karlasa @torhoehn changes updated as per requested.

**Review by Karlasa — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Karlasa, thank you for the review.
[ENGCOM-4118](https://jira.corp.magento.com/browse/ENGCOM-4118) has been created to process this Pull Request

**Review by torhoehn — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @torhoehn, thank you for the review.
[ENGCOM-4118](https://jira.corp.magento.com/browse/ENGCOM-4118) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
✔️ QA passed

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @amol2jcommerce the commits in this pull request are not linked to your github account. Can you please check the email configured for github and push the changes as a single commit correctly linked to the author.

**Comment by amol2jcommerce** [comment]
Hi @sivaschenko, I closed this PR due to committed from different account and that account didn't sign CLA. We generate New PR #21638 for this & sign CLA account.

**Pull request closed without merging**
