### PR TITLE
Add @api annotation to the ScopeConfig WriterInterface

### PR DESCRIPTION
**Pull request by navarr**
### Description

I would like a more official way of writing config that's part of the API.

Currently, You should use `Magento\Config\Model\ResourceModel\Config::saveConfig` - which is @api annotated.

That class implements `Magento\Framework\App\Config\ConfigResource\ConfigInterface` (which is not annotated) - and that class is used by `Magento\Framework\App\Config\Storage\WriterInterface` (which is not annotated - but I propose to do so here)

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by larsroettig — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @larsroettig, thank you for the review.
[ENGCOM-1097](https://jira.corp.magento.com/browse/ENGCOM-1097) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@navarr thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by navarr** [comment]
@magento-engcom-team That link just takes me to the magento user page on github.

**Comment by larsroettig** [comment]
@navarr Because you are already in Magento org :-) maybe we should fix this in automation 🔍

**Comment by sidolov** [comment]
Hi @navarr , I see that in namespace `\Magento\Framework\App\Config` we have several interfaces without @api annotation, so, can you describe the scenario when you need write to storage with usage `\Magento\Framework\App\Config\Storage\WriterInterface`?

**Comment by navarr** [comment]
@sidolov Yes.  Our team was writing a log rotator (for the database), where older logs are deleted.

To accomplish this, we had two config fields: a start time, and a frequency.  These are then compiled into a configuration setting that contains the actual cron format.

We needed a method to write to the config during this compilation step.  The developer's first go was to use the config Value model and save it - but that's not the Magento way, so we went down the rabbit hole of trying to figure out how we're _supposed_ to save config.

The internet likes WriterInterface - but it's not annotated, so I went down the chain of things it does to find something annotated.

Unfortunately what we found was `Magento\Config\Model\ResourceModel\Config`.  While we can use that (since it's annotated) - using another module's resourcemodel seems very wrong.

The ideal situation is that there is an api annotated interface for setting config.  WriterInterface seems like the best choice.

**Comment by sidolov** [comment]
@navarr I see that it useful for you, thank you for fast response!

**Pull request merged**
