### PR TITLE
Issue 35964: Bundle options decimal qty is rendered as an integer par…

### LINKED ISSUE #35964: Bundle options decimal qty is rendered as an integer part only
### Preconditions and environment

- Magento version: CE 2.4.4

### Steps to reproduce

1. Create a bundle product
2. Allow "Qty Uses Decimals" in Advanced Inventory **for bundle options**
3. Buy this bundle product with decimal options Qty like 1.5
4. Check option Qty in the email / customer account / admin panel order details / invoice details / shipment details

### Expected result

Bundle options Qty must be rendered everywhere according to amount you bought, in our case **qty = 1.5**

### Actual result

Bundle options Qty is rendered only **as an integer part, qty = 1**

### Additional information

This happens due to using `sprintf('%d', $attributes['qty'])`, this `'%d'` makes it using only integer part.

Needs to be fixed at least in `\Magento\Bundle\Block\Adminhtml\Sales\Order\Items\Renderer`, `\Magento\Bundle\Block\Adminhtml\Sales\Order\View\Items\Renderer` and `\Magento\Bundle\Block\Sales\Order\Items\Renderer`

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rogerdz**
…t only

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35964

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Review by edenduong — CHANGES_REQUESTED** [review]
Thank you for your contribution. Could you please cover your change by automation test? I think it can be covered by Unit test by mockup getSelectionAttributes to make (attributes['qty'] = float number).

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
Hi @edenduong, thank you for your review. I added Unit test.

**Review by edenduong — APPROVED** [review]
Thank you for your contribution!

**Comment by engcom-Lima** [comment]
@magento give me test instance

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

**Review by engcom-Lima — CHANGES_REQUESTED** [review]
Hi @rogerdz ,

Thanks for your contribution and collaboration.
I have tried to reproduce the issue and the issue is reproducible to me but after applying the PR changes the issue is still reproducible to me .Below is the screenshot for your reference:
image
image

image

Kindly recheck it .

Thanks

**Comment by rogerdz** [comment]
Hi @engcom-Lima, I think issue reported is adding bundle option with qty 1.5, not adding qty 1.5 for bundle product.

**Comment by ishakhsuvarov** [comment]
@engcom-Lima please take a look at it again with regards to the last comment.

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
@magento give me test instance

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento `2.4-develop`

**Manual testing scenario:**
Create a bundle product and with min two options of simple product (set yet for Qty uses decimal in Advanced inventory) save it and in options give 1.5 as default qty .
Add to cart without specifying qty and place an order.
Check orders page in frontend and admin page/invoices/shipment/credit memo product redered as 1.5
**Before:** :heavy_multiplication_x: 
**Mail:**
Screenshot 2022-10-25 at 2 52 57 PM

**Customer Order page:**
image

**Admin orders page:**
Screenshot 2022-10-25 at 3 52 56 PM

**After:** :heavy_check_mark:  
**Mail:**
Screenshot 2022-10-25 at 3 14 15 PM

**Customer Order page:**
Screenshot 2022-10-25 at 2 48 15 PM

**Admin orders page:**
Screenshot 2022-10-25 at 2 48 05 PM

No additional manual test case is required as part of regression.

**Pull request merged**
