### PR TITLE
Correctly revert default mode after mass image deletion

### LINKED ISSUE #1769: Add selected button still active after image deletion
### Preconditions (*)

1. Install Magento 2.4-develop with Adobe Stock Integration and IMS
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Enhanced Media Gallery Enabled
4. Image is in the Media Gallery
### Steps to reproduce (*)

1. Go to Content -> Pages
2. Add New Page
3. Enter "Page Title"
4. Expand "Content" section
5. Click on the "Show / Hide Editor" -> "Insert Image..."
6. Click on the "Delete Images..." button
7. Select any image by clicking on it
8. Click on the "Delete Selected" button
9. Confirm Deleting
10. Pay attention - no image is selected 
11. Click on the "Add Selected"

### Expected result (*)

There is no "Add Selected" button because no image is selected. 
Impossible to add an image to page
### Actual result (*)

Empty image url added to page
Peek 2020-08-19 14-27

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1769: Add selected button still active after image deletion

### Manual testing scenarios (*)

```
    Go to Content -> Pages
    Add New Page
    Enter "Page Title"
    Expand "Content" section
    Click on the "Show / Hide Editor" -> "Insert Image..."
    Click on the "Delete Images..." button
    Select any image by clicking on it
    Click on the "Delete Selected" button
    Confirm Deleting
    Pay attention - no image is selected
    Click on the "Add Selected"
```

There is no "Add Selected" button because no image is selected.
Impossible to add an image to page
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@Nazar65 please add the check for the button to MFTF test

**Comment by Nazar65** [comment]
@magento run all tests

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8042](https://jira.corp.magento.com/browse/ENGCOM-8042) has been created to process this Pull Request

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed 
There is no "Add Selected" button because no image is selected.
Peek 2020-08-20 151

**Pull request merged**
