### PR TITLE
rewrite fix while product website update using mass action

### PR DESCRIPTION
**Pull request by AnshuMishra17**
### Description (*)
URL rewrite fix while product website update using mass action

### Fixed Issues (if relevant)
1. magento/magento2#21329: URL Rewrites are overwritten

### Manual testing scenarios (*)
1. Added multiple websites.
2. Set URL key value at store level for any product.
3. Added the product in a new website using website update via mass action.
4. Removed product from a website using website update via mass action.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @AnshuMishra17. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by miguelbalparda** [comment]
Hi @AnshuMishra17, any chance you can port this to 2.3 before we merge this to 2.2? Thanks!

**Comment by AnshuMishra17** [comment]
@miguelbalparda Magento Port Tool (https://porting.engcom.dev.magento.com) is saying that I can't port unmerged PR.
Do I need to create a separate PR, then?

**Comment by miguelbalparda** [comment]
Yes, since the change is pretty small in LOC you should be able to create a new PR pointing to the correct branch without much hassle. No need to close this one. Thanks!

**Comment by AnshuMishra17** [comment]
@miguelbalparda Can I edit the PR and change the base?

**Comment by AnshuMishra17** [comment]
@miguelbalparda I have created a new PR https://github.com/magento/magento2/pull/21462

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5193](https://jira.corp.magento.com/browse/ENGCOM-5193) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
Hi @AnshuMishra17  I am not able to reproduce issue [#21329](https://github.com/magento/magento2/issues/21329) on 2.2-develop. 
#21358CantReproduce
Could you take a look?

**Comment by sidolov** [comment]
@AnshuMishra17 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
