### PR TITLE
Resolve No validate "Sort Order" in Widget Form (issue 24154)

### LINKED ISSUE #24154: No validate "Sort Order" in Widget Form
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Content->Widget
3. Add Widget
4. Choose Type: CMS Static Block
5. Choose Theme: Magento Luma
6. Continue
7. Fill all required field: Widget Title, Assign to Store Views, Select Block
8. "Sort order" fill string "one"

### Expected result (*)

1. Can not save because it is not a number
### Actual result (*)

1. Save normally

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#24154: No validate "Sort Order" in Widget Form

Solution: add class '**validate-number**' for the field Sort Order instead of empty value

### Fixed Issues (if relevant)

1. magento/magento2#24154: No validate "Sort Order" in Widget Form

### Manual testing scenarios (*)

1. Go to backend
2. Content->Widget
3. Add Widget
4. Choose Type: CMS Static Block
5. Choose Theme: Magento Luma
6. Continue
7. Fill all required field: Widget Title, Assign to Store Views, Select Block
8. "Sort order" fill string "one"

#### Expected result 

1. Can not save because it is not a number

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5647](https://jira.corp.magento.com/browse/ENGCOM-5647) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5647](https://jira.corp.magento.com/browse/ENGCOM-5647) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
