### PR TITLE
MFTF: Invalid Admin Login/Logout Action Groups

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
I hope that no more left in Magento codebase.
Last round of replacements for Admin Login / Logout.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello, @lbajsarowicz, thank you for your contribution. That's impressive, you did a great job!
Could you please check the failed tests? I guess most of the failures related to the mismatching password for the username "admin2" after refactoring.

Thank you!

**Comment by lbajsarowicz** [comment]
Thanks @dmytro-ch - I'm going to fix it by the end of the week.
I'm pretty sure that won't be merged for long, so... we have some time :-)

**Comment by lbajsarowicz** [comment]
@magento run all tests
I have no idea why I need to force it manually :face_with_head_bandage:

**Comment by lbajsarowicz** [comment]
Yay, conflicts to solve! :cactus:

**Comment by lbajsarowicz** [comment]
Additionally changed stepKey to be `camelCase` instead of `PascalCase`

**Comment by lbajsarowicz** [comment]
Changes performed directly to the core by @okolesnyk

**Pull request closed without merging**
