### PR TITLE
Prevent "Overwrite the existing configuration for db-ssl-verify?" question

### LINKED ISSUE #29612: [Issue] Prevent "Overwrite the existing configuration for db-ssl-verify?" question
This issue is automatically created based on existing pull request: magento/magento2#26818: Prevent "Overwrite the existing configuration for db-ssl-verify?" question

---------
### Summary (*)
Magento 2.4-develop
This question is occurred [every time](https://github.com/magento/magento2/issues/26762#issuecomment-584698357) I run:
```
$ ./bin/magento setup:config:set
```

after upgrade to 2.3.4

Also see #26762 

We should ask this question only if new value of configuration option is not equal to the old value,.

### PR DESCRIPTION
**Pull request by flancer64**
This question is occurred [every time](https://github.com/magento/magento2/issues/26762#issuecomment-584698357) I run:
```
$ ./bin/magento setup:config:set
```

after upgrade to 2.3.4

Also see #26762 

We should ask this question only if new value of configuration option is not equal to the old value,. 

### Resolved issues:
1. [x] resolves magento/magento2#29612: Prevent "Overwrite the existing configuration for db-ssl-verify?" question

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @flancer64,

Thank you for your contribution!
Seems like the listed above issue was already fixed in https://github.com/magento/magento2/pull/26763.
Could you confirm that?

**Comment by flancer64** [comment]
@ihor-sviziev  , I can confirm that the issue is not fixed in #26763.

I've reverted my patch in my local project (based on Magento 2.4.0) and I have the same warning:
```
$ ./work/bin/magento setup:config:set
Overwrite the existing configuration for db-ssl-verify?[Y/n]
```

I see code from #26763 in 
* ./vendor/magento/magento2-base/setup/src/Magento/Setup/Model/ConfigOptionsList/DriverOptions.php
* ./setup/src/Magento/Setup/Model/ConfigOptionsList/DriverOptions.php

It looks like:
```
    private function optionExists($options, $driverOptionKey): bool
    {
        return isset($options[$driverOptionKey])
            && ($options[$driverOptionKey] === false || !empty($options[$driverOptionKey]));
    }
```

I've re-apply my patch and the warning is disappeared.

So, I can confirm that #26763 was not fix the issue listed above.

**Comment by ihor-sviziev** [comment]
@flancer64 do you think it's possible to cover your change with any type of automated test?

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8168](https://jira.corp.magento.com/browse/ENGCOM-8168) has been created to process this Pull Request

**Comment by flancer64** [comment]
> do you think it's possible to cover your change with any type of automated test?

Yes, I think it is possible but I cannot do it. I know nothing about Magento Testing Framework. Sorry.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Result:**
**Before:**
:x: `Overwrite the existing configuration for db-ssl-verify?` is shown, when `'driver_options'` has no changes in `env.php`
image


**After:**
:heavy_check_mark: `Overwrite the existing configuration for db-ssl-verify?` message is not shown, when `'driver_options'` has no changes in `env.php`
image
:heavy_check_mark: `Overwrite the existing configuration for db-ssl-verify?` message is shown, when `'driver_options'` has new value in `env.php`
image

**Comment by sidolov** [comment]
@flancer64 looks like something went wrong with the source branch, it's removed now. I'm closing the PR since we cannot proceed without the source code. Feel free to reopen it in case you want to continue. Thank you for your contribution!

**Comment by ihor-sviziev** [comment]
@flancer64 could you create new PR with the same changes?

**Comment by flancer64** [comment]
I found I can use a branch in my fork.

**Comment by flancer64** [comment]
@sidolov , done.

**Pull request closed without merging**
