### PR TITLE
Removed Unnecessary slash in namespace in di.xml

### PR DESCRIPTION
**Pull request by milindsingh**
### Description (*)

Removed unnecessary root slash `\` in namespace in di.xml causing failure in overwriting with same namespace without root slash. Hence, removed all root slashes from `di.xml` where present.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-3923](https://jira.corp.magento.com/browse/ENGCOM-3923) has been created to process this Pull Request

**Comment by aleron75** [comment]
Hello @milind

**Comment by aleron75** [comment]
Hello @milindsingh thanks for your contribution.

Once merged, don't forget you can easily port this PR (if needed) to other branches with the Porting Tool, [read more here](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#porting-tool).

**Comment by milindsingh** [comment]
@aleron75 Sure! Thanks!
(Also, SSL for Magento Porting Tool has expired, making it unavailable for web (chrome & firefox)) 
https://porting.engcom.dev.magento.com/login
https porting engcom dev magento com login

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
