### PR TITLE
magento/magento2#21001 - fix unit tests, by passing currency to numbe…

### PR DESCRIPTION
**Pull request by kdegorski**
…r formatter, then it behaves as was expected in test.

### Description (*)
The changes are only in unit tests which were'nt testing what they supposed to. Added neccessary parameters to achieve that goal

### Fixed Issues (if relevant)
1. magento/magento2#21001 - Unit Tests failed

### Manual testing scenarios (*)
1. Run the unit tests `2.3.0/vendor/magento/framework/Locale/Test/Unit/FormatTest.php`

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21880) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @kdegorski. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — APPROVED** [review]
Nice catch @kdegorski!

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4554](https://jira.corp.magento.com/browse/ENGCOM-4554) has been created to process this Pull Request

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4554](https://jira.corp.magento.com/browse/ENGCOM-4554) has been created to process this Pull Request

**Comment by soleksii** [comment]
Hi @kdegorski ! I've checked PR and looks like that these changes doesn't solve the problem completely.

**Actual result:**
screen

ICU version => 63.1

Thanks!

**Comment by kdegorski** [comment]
According to thread https://bugs.openjdk.java.net/browse/JDK-8211262 there was a change of  de_CH grouping character - so there's not option to make those tests apply to different versions of ICU. (since CLDR v33)
@stoleksiy Should I remove this test case?

**Comment by soleksii** [comment]
@kdegorski You do not need to remove test case. We will approve these changes as they are. Thanks!

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Comment by orlangur** [comment]
@kdegorski @stoleksiy why not make `decimalSymbol` ICU-version-dependent?

**Review by orlangur — APPROVED** [review]
Thanks @kdegorski, looks much more robust now 👍

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4554](https://jira.corp.magento.com/browse/ENGCOM-4554) has been created to process this Pull Request

**Pull request merged**
