### PR TITLE
[#18269] If import product has missing categories, make a lookup for existing categories to keep the correct url rewrites

### PR DESCRIPTION
**Pull request by ulftietze**
…existing categories to keep the correct url rewrites

### Fixed Issues (if relevant)

1. magento/magento2#18269: Product Import -> Missing categories entry in importfile removes url rewrites

### Manual testing scenarios

1. Updated Unit Test

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ulftietze. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-3367](https://jira.corp.magento.com/browse/ENGCOM-3367) has been created to process this Pull Request

**Comment by aleron75** [comment]
Hello @ulftietze thank you for your contribution.

Once merged, don't forget you can easily port this PR to other branches with the Porting Tool, [read more here](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool). 

If you already did it and I missed it, please ignore my message.

Cheers

**Comment by sidolov** [comment]
Hi @ulftietze , we cannot reproduce described issue:

**Manual testing scenario:**
1. Two websites are created: base and second
2. Simple product is created on both websites: base and second.
3. Simple product is assigned to categories: Default Category/cat1,Default Category/cat2.
4. URL Rewrite contains following informations:
18942beforeimport

Import csv with following information:
``
 sku,url_key,product_websites
 simple1,custom-url-key-for-product-123456789,"base,second"
``

Url rewrites for categories are present in url_rewrite table.
18942afterimport

**Comment by sivaschenko** [comment]
@ulftietze closing the pull request due to inactivity. Feel free to reopen is you will have any additional details for us to reproduce the issue

**Pull request closed without merging**
