### PR TITLE
[Forwardport] Responsive Design Footers bottom of screen on mobile devices #15118

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Original Pull Request 
 https://github.com/magento/magento2/pull/15353
Solved footer issue for mobile view

### Description
Solved footer issue for mobile view

### Fixed Issues (if relevant)

1. magento/magento2#15118: Responsive Design, Footers do not snap to bottom of screen on mobile devices
2. ...

### Manual testing scenarios

1. Check footer in mobile

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by gwharton** [comment]
Arghhh, this resolution is not right. Please look at the original issue #15118. The PR that was originally created, that this is a forward port of, is a poor fix for this issue. It means that the footer is ALWAYS at the bottom of the screen, and the main page content scrolls behind it. 

The resolution to this issue should in my opinion make the footers replicate the same behaviour as the desktop. See the remainder of the comments in #15118 and the second attempt at a PR which has not yet been accepted.

**Comment by ihor-sviziev** [comment]
Hi @gwharton,
I created forwardport to 2.3-develop branch in order to have similar changes and same bugs in 2.2.x and 2.3.x and easier backport/forwardport fixes for them. 
Here is two potential PR that fixes this issue: https://github.com/magento/magento2/pull/16981 and https://github.com/magento/magento2/pull/17006

**Comment by gwharton** [comment]
Thanks @ihor-sviziev I see the need to keep the branches consistent. 

It just feels a bit messy at the moment as there are several PR's that all seem to be conflicting with one another, and all in the "accept" state, and all proposing to make changes to 2.2-develop that will ultimately conflict with the changes being proposed to 2.3-develop here. 

Aslong as someone somewhere has a good handle on all this, then I'm sure it will all workout in the end.!!! :)

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Pull request merged**
