### PR TITLE
Optimize QuoteIdToMaskedQuoteId model and fix infinite loop

### PR DESCRIPTION
**Pull request by ihor-sviziev**
Port https://github.com/magento/magento2/pull/33324 to 2.4.3

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>
2. 

### Release Notes

Improve performance by using direct SQL queries

### Categories

Performance, Shopping Cart

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by andrewbess — APPROVED** [review]

**Comment by m2-github-services** [comment]
@andrewbess thank you for the review! We have changed pull request base branch in order to provide ability to merge current pull request and schedule quality patch delivery job.

**Review by Den4ik — APPROVED** [review]

**Comment by m2-github-services** [comment]
@Den4ik thank you for the review! We have changed pull request base branch in order to provide ability to merge current pull request and schedule quality patch delivery job.

**Comment by Den4ik** [comment]
@sidolov @sivaschenko @gabrieldagama 
I'm looking ComposerTest file and don't agree with logic of php version check.

```
$this->assertEmpty(
    array_diff($rootPhpVersions, $modulePhpVersions),
    "PHP version {$phpVersion} in component {$name} is inconsistent with version "
    . self::$rootJson['require']['php'] . ' in root composer.json'
);
```

Why php version is inconsistent if we have same version `~7.4.0` for both projects?
I believe that we should check that diff count should be smaller than count of `$rootPhpVersions`

```
$this->assertTrue(
    count(array_diff($rootPhpVersions, $modulePhpVersions)) < count ($rootPhpVersions),
    "PHP version {$phpVersion} in component {$name} is inconsistent with version "
    . self::$rootJson['require']['php'] . ' in root composer.json'
);
```

**Comment by Den4ik** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by sidolov** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@sidolov, could you check why functional and unit tests are failing? These failures are not related to changes from this PR.

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE, Unit Tests

**Comment by sidolov** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by sidolov** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by sidolov** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by sidolov** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by sidolov** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by sidolov** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by sidolov** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by ihor-sviziev** [comment]
On finally, the only one test is failing.

@magento run Functional Tests CE

**Comment by Den4ik** [comment]
@magento run Functional Tests CE

**Comment by m2-github-services** [comment]
@sidolov quality patch delivery job is successfully scheduled! Link to the quality patch tool pull request will be provided as soon as it's created

**Comment by m2-github-services** [comment]
Pull request with quality patch was successfully created, available by the link: magento/quality-patches#65

**Comment by engcom-Lima** [comment]
Since this PR is already merged. Hence, moving this PR to recently merged.

**Pull request merged**
