### PR TITLE
Encrypt Email SMTP Password Field

### LINKED ISSUE #36705: [Issue] Encrypt Email SMTP Password Field
This issue is automatically created based on existing pull request: magento/magento2#36683: Encrypt Email SMTP Password Field

---------

Amends the PR from @barryvdh & Stores SMTP passwords as an obscured & encrypted field in the backend

### Description (*)

1. amends app/code/Backend/etc/adminhtml/system.xml file to make SMTP password field an obscured & encrypted field
2. amends app/code/Email/etc/config.xml to ensure ScopeConfigInterface retrieval of the password field will unencrypt the password value

### Related Pull Requests

Amends PR https://github.com/magento/magento2/pull/32241

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Save a password in the SMTP transport settings
2. Observe that the field is obscured on entry
3. Observe that the password field is an encrypted value in the core_config_data table
4. Observe that emails are successfully sent by the transport (i.e. password reset, upon new customer creation, etc)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by gusdemayo**
Amends the PR from @barryvdh & Stores SMTP passwords as an obscured & encrypted field in the backend

### Description (*)

1. amends app/code/Backend/etc/adminhtml/system.xml file to make SMTP password field an obscured & encrypted field
2. amends app/code/Email/etc/config.xml to ensure ScopeConfigInterface retrieval of the password field will unencrypt the password value

### Related Pull Requests

Amends PR https://github.com/magento/magento2/pull/32241

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Save a password in the SMTP transport settings
2. Observe that the field is obscured on entry
3. Observe that the password field is an encrypted value in the core_config_data table
4. Observe that emails are successfully sent by the transport (i.e. password reset, upon new customer creation, etc)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36705: Encrypt Email SMTP Password Field

### CODE REVIEW

**Comment by barryvdh** [comment]
Thanks, good idea!

**Comment by ihor-sviziev** [comment]
Hi @gusdemayo,
I think we should also add the data migration path to encrypt the old value

**Comment by barryvdh** [comment]
@ihor-sviziev but this isn't released yet right? The SMTP password is not in 2.4.2-p2 of 2.4.5-p1, it will be available in 2.4.6 only.

**Comment by ihor-sviziev** [comment]
@barryvdh ah, you’re right!

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Hi @ishakhsuvarov,
Do you believe it's still possible to add this change as a hotfix to 2.4.6?
I see according to release schedule, beta should be available pretty soon https://experienceleague.adobe.com/docs/commerce-operations/release/planning/schedule.html

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ishakhsuvarov** [comment]
@ihor-sviziev It's unlikely but I'll see what I can do

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by ishakhsuvarov** [comment]
> @ishakhsuvarov, thx for the update. If it won't be included - we should add migration that will encrypt the credentials

Yes, I think this is a very valid concern, thus I am actively working on adding it to 2.4.6 :) I'll post an update here once I know for sure if it is a success or not

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento `2.4-develop`

**Manual testing scenario:**

1. Save a password in the SMTP transport settings
2. Observe that the field is obscured on entry
3. Observe that the password field is an encrypted value in the core_config_data table
4. Observe that emails are successfully sent by the transport (i.e. password reset, upon new customer creation, etc)

**Before:** :heavy_multiplication_x: 
**Password was visible in console:**
Screenshot 2023-01-05 at 6 27 44 PM

**In db password was not encrypted:**
Screenshot 2023-01-05 at 5 47 51 PM


**After:** :heavy_check_mark:  
**Password is not visible now:**
Screenshot 2023-01-05 at 7 23 31 PM

**In db password is encrypted:**
Screenshot 2023-01-05 at 7 31 53 PM

**Additionally tested:**

  1. Checked mail functionality by creating account.
  2. Reset customer password.

Since builds are failed hence, moving this PR to extended testing.

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Comment by barryvdh** [comment]
If this doesn't get in 2.4.6 an upgrade path might need to be provided?

**Comment by nathanjosiah** [comment]
@magento export issue to Jira project AC as Bug

**Comment by nathanjosiah** [comment]
This was already addressed in private security branches

**Comment by hostep** [comment]
I can confirm this change is included in Magento 2.4.6-beta8

**Pull request closed without merging**
