### PR TITLE
Be able to add error before going to checkout

### PR DESCRIPTION
**Pull request by maximehuran**
### Description

This event allow us to make custom check before going to checkout, and add some error messages : 

```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
    <event name="validate_quote">
        <observer name="namespace_module_check_quote" instance="Namespace\Module\Observer\CheckQuote"/>
    </event>
</config>

```

```php
<?php

namespace Namespace\Module\Observer;

use Magento\Framework\Event\Observer;
use Magento\Framework\Event\ObserverInterface;
use Magento\Framework\Message\ManagerInterface;

class CheckQuote implements ObserverInterface
{
    /**
     * @var MessageManager
     */
    protected $messageManager;

    /**
     * @param ManagerInterface $messageManager
     */
    public function __construct(ManagerInterface $messageManager)
    {
        $this->messageManager = $messageManager;
    }

    /**
     *
     * @param Observer $observer
     * @see validate_quote
     */
    public function execute(Observer $observer)
    {
        /** @var \Magento\Quote\Model\Quote $quote */
        $quote = $observer->getEvent()->getQuote();
        $quoteHasError = true; // Create the rule you want
        // Add message if quote has error (The user is not able to go to checkout)
        if ($quoteHasError) {
            $this->messageManager->addErrorMessage(
                __('Your custom error message.')
            );
            $quote->setHasError(true);
        }
    }
}
```

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16648) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=16648) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
Hi @maximehuran. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by orlangur** [comment]
Adding new events is discouraged. The same behavior could be easily achieved with `afterExecute` plugin.

**Comment by maximehuran** [comment]
I am not really fond of the `afterExecute` plugin because this code will be executed before : 
```
$this->_customerSession->regenerateId();
        $this->_objectManager->get('Magento\Checkout\Model\Session')->setCartWasUpdated(false);
        $this->getOnepage()->initCheckout();
        $resultPage = $this->resultPageFactory->create();
        $resultPage->getConfig()->getTitle()->set(__('Checkout'));
```

I think I'll use the `beforeExecute`.

But I think there is a bigger problem without an event like that.
First, I used the event `sales_quote_collect_totals_after` to do what I want.
But this event is called in the cart, but not when you click on the button `Go to checkout` in minicart.
So it means you can add error to quote with `sales_quote_collect_totals_after`, but you can proceed to checkout when your quote has error. There is a non sense for me in the logic. 

This is why I decided to add this event, which allow us to manage error before going to quote.

Another solution is to process the `$quote->collectTotals()` before the condition `if (!$quote->hasItems() || $quote->getHasError() || !$quote->validateMinimumAmount())`

This will fire the event `sales_quote_collect_totals_after` which allow us to have the same event for cart verification, and before checkout verification.

**Comment by orlangur** [comment]
Forget about events, really :)

Again, adding new events is not a right way to go.

If you believe current code does not allow proper customization, refactor it not breaking BC so that pluginization is possible.

**Comment by orlangur** [comment]
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.

**Pull request closed without merging**
