### PR TITLE
[Backport] 'wishlist-page-edit-remove-item-misalign-2-2' :: On wish list page ed…

### PR DESCRIPTION
**Pull request by nainesh2jcommerce**
…it, remove item misalign in 640 X 767 resolution

### Description (*)

Original PR: https://github.com/magento/magento2/pull/20400

### Fixed Issues (if relevant)

1. magento/magento2#20399: : On wish list page edit, remove item misalign in 640 X 767 resolution
2. 

### Manual testing scenarios (*)

1. add product to wish list
2. check edit remove item button on 640 X 767 resolution

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by nainesh2jcommerce** [comment]
Hi @rogyar,
Any news on this PR? Thanks!

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-3911](https://jira.corp.magento.com/browse/ENGCOM-3911) has been created to process this Pull Request

**Comment by sdzhepa** [comment]
Hello @nainesh2jcommerce 

We found that issue was already fixed and delivered in the scope of #20544

This PR can be closed.

Thank you for contribution and collaboration!

**Pull request closed without merging**
