### PR TITLE
MFTF: use LogoutActionGroup instead of `amOnPage` /auth/logout

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
I was using custom admin path, so I saw 404 in most of the tests when looking at them during run. Realized that 404 is caused by invalid Admin Logout URL. After investigation, I've noticed that most of the tests use hardcoded logout URL instead of LogoutActionGroup, so that I replaced all occurencies of this hardcoded logout into Action group.

### Fixed Issues (if relevant)
Irrelevant.

### Manual testing scenarios (*)
1. Run MFTF

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — APPROVED** [review]
Nice catch!

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5269](https://jira.corp.magento.com/browse/ENGCOM-5269) has been created to process this Pull Request

**Comment by soleksii** [comment]
QA not applicable

**Comment by dmytro-ch** [comment]
Hi @lbajsarowicz,
could you please resolve merge conflicts?

Thank you!

**Comment by lbajsarowicz** [comment]
Sure, I'll do it today evening

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5269](https://jira.corp.magento.com/browse/ENGCOM-5269) has been created to process this Pull Request
:eight_spoked_asterisk: @dmytro-ch, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Pull request merged**
