### PR TITLE
Remove redundant fieldset in sale rule form

### LINKED ISSUE #29599: [Issue] Remove redundant fieldset in sale rule form
This issue is automatically created based on existing pull request: magento/magento2#27585: Remove redundant fieldset in sale rule form
---------
remove redundant fieldset in sale rule form. "Currently Active". This field is used in Magento Commerce, not in open source.

### Preconditions (*)
1. Magento 2.4 CE

### Steps to reproduce (*)
1. Go to backend.
2. Create New Cart Price Rule.

Check:

image

### Expected result (*)

image

Should be:

image

### Actual result (*)

image

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

This PR remove redundant fieldset in sale rule form. "Currently Active". This field is used in Magento Commerce, not in open source.

image

Should be:

image

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/170

### Manual testing scenarios (*)

1. Go to backend.
2. Create New Cart Price Rule.

Check:

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29599: Remove redundant fieldset in sale rule form

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8090](https://jira.corp.magento.com/browse/ENGCOM-8090) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Result:**
:x: Before:
image

:heavy_check_mark: After:
image

**Comment by engcom-Delta** [comment]
**Note:** Functional Tests B2B are failed

**Pull request merged**
