### PR TITLE
Fix #28947 - Proper reset action for select component

### LINKED ISSUE #28947: Scope not reset on New Synonym Group form
Scope not reset on New Synonym Group form

### Preconditions (*)
Magento 2.3.4

### Steps to reproduce (*)

1. Admin - Marketing - SEO & Search 
2. Click on New Synonym Group
3. Select scope different then default 
4. Enter other details 
5. Click on Reset 

### Expected result (*)
All values should be reset 

### Actual result (*)
image

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This PR adds `reset` method to the select component, which was previously inherited from `abstract` parent component, and was not working correctly, since it was created there for text field.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#28947

### Manual testing scenarios (*)

Please check fixed issue for steps to test

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Bartlomiejsz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

Failed tests are not related to the changes.

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by Bartlomiejsz** [comment]
Closing as related issue was already fixed in other PR

**Pull request closed without merging**
