### PR TITLE
Fixed typo in deploy module README.md

### PR DESCRIPTION
**Pull request by arnolds**
### Description (*)

Fixed typo in deploy module README.md from `bin/magento setup:mode:set` to `bin/magento deploy:mode:set`.

It needed changing, because the command `bin/magento setup:mode:set` does not exist.

Screenshot 2019-07-16 at 21 24 18

The correct command is `bin/magento deploy:mode:set`.

### Manual testing scenarios (*)

1. Go to `magento2/app/code/Magento/Deploy/README.md` file.
2. Scroll down, or search for `bin/magento setup:mode:set`.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23735) <br/>All committers have signed the CLA.

**Review by kalpmehta — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, thank you for the review.
[ENGCOM-5458](https://jira.corp.magento.com/browse/ENGCOM-5458) has been created to process this Pull Request
:eight_spoked_asterisk: @kalpmehta, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@arnolds thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Delta** [comment]
**Notice:** QA not applicable

**Pull request merged**
