### PR TITLE
[Forwardport] fix: prevent inline-block issue in name form due to space and font-size

### PR DESCRIPTION
**Pull request by DanielRuf**
### Original Pull Request 
 https://github.com/magento/magento2/pull/16048

### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/16047

### Manual testing scenarios

1. open a page where the name form is eg /customer/account/edit/
2. compare the space between asterisk / required field indicator to other fields with the required field indicator

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on Pull Request changes
- `@magento-engcom-team give me new test instance` - deploy **NEW** test instance based on Pull Request changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy Vanilla Magento instance for Issue or Pull Request

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by DanielRuf** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf, here is your [Magento instance](https://pr-16097.engcom.dev.magento.com).
Admin access: [https://pr-16097.engcom.dev.magento.com/admin](https://pr-16097.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Please make sure you are PR **author** or **assignee** to access the instance.

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.3.0 release.

**Pull request merged**
