### PR TITLE
Resolve Missing Validation at some Payment Method Settings issue 23916

### LINKED ISSUE #23916: Missing Validation at some Payment Method Settings
### Preconditions (*)

1. Magento 2.3 develop

### Steps to reproduce (*)

1. Go to Store->Configurations->Sales->Payment Method
2. Find these fields:
- Check/Money Order
  * Minimum Order Total
  * Maximum Order Total
- Bank Transfer Payment
  * Minimum Order Total
  * Maximum Order Total
  * Sort Order
- Cash On Delivery Payment
  * Minimum Order Total
  * Maximum Order Total
  * Sort Order
- Purchased Order
  * Minimum Order Total
  * Maximum Order Total
- Authorize.Net Direct Post (Deprecated)
  * Minimum Order Total
  * Maximum Order Total
- Authorize.Net
  * Minimum Order Total
  * Maximum Order Total

3. Fill string "one" to the fields
4. Save
### Expected result (*)

1. Can not save because it is not number

### Actual result (*)

1. Save normally with the wrong data type

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#23916: Missing Validation at some Payment Method Settings

Solution: Add the **validate** tag into the system.xml file

### Fixed Issues (if relevant)

1. magento/magento2#23916: Missing Validation at some Payment Method Settings

### Manual testing scenarios (*)

1. Go to Store->Configurations->Sales->Payment Method
2. Find these fields:
- Check/Money Order
  * Minimum Order Total
  * Maximum Order Total
- Bank Transfer Payment
  * Minimum Order Total
  * Maximum Order Total
  * Sort Order
- Cash On Delivery Payment
  * Minimum Order Total
  * Maximum Order Total
  * Sort Order
- Purchased Order
  * Minimum Order Total
  * Maximum Order Total
- Authorize.Net Direct Post (Deprecated)
  * Minimum Order Total
  * Maximum Order Total
- Authorize.Net
  * Minimum Order Total
  * Maximum Order Total

3. Fill string "one" to the fields
4. Save

**Expected result: Can not save because it is not number**

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-23917.instances.magento-community.engineering).
Admin access: [https://pr-23917.instances.magento-community.engineering/admin](https://pr-23917.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-5504](https://jira.corp.magento.com/browse/ENGCOM-5504) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by fooman** [comment]
Does `validate-number validate-zero-or-greater` allow an empty field? Reason I am asking is that otherwise any change to any payment method could now require someone to manually input all those zeroes (even on inactive payment methods) before being able to save the page.

**Comment by edenduong** [comment]
> Does `validate-number validate-zero-or-greater` allow an empty field? Reason I am asking is that otherwise any change to any payment method could now require someone to manually input all those zeroes (even on inactive payment methods) before being able to save the page.

@fooman Yes. You can leave them empty and save. No problem. It only validates when the user enter the data but it is not a number.

**Comment by edenduong** [comment]
@sivaschenko : Could I receive Bug fixed reward? Thank you :)

**Pull request merged**
