### PR TITLE
[Backport 2.2] issue #18931 fixed.

### PR DESCRIPTION
**Pull request by Jeroenll**
### Description (*)
Add missing translations, backport of https://github.com/magento/magento2/pull/18938

### Fixed Issues (if relevant)
1. magento/magento2#18931: Product added to shopping cart / comparison list message not translated by default

### Manual testing scenarios (*)
1. Change language to non english.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @JeroenVanLeusden. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3593](https://jira.corp.magento.com/browse/ENGCOM-3593) has been created to process this Pull Request

**Comment by Jeroenll** [comment]
@magento-engcom-team Accidentally deleted branch, did I mess up some automation tools now?

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-4003](https://jira.corp.magento.com/browse/ENGCOM-4003) has been created to process this Pull Request

**Pull request merged**
