### PR TITLE
Fix export module select option error when open export page in backend

### PR DESCRIPTION
**Pull request by GraysonChiang**
### Description (*)
Something when wrong if doesn't install any import/export module when open the export page in backend.

### Fixed Issues (if relevant)
Add 'if' condition

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18859) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18859) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
Hi @GraysonChiang. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Please update the styles to match the Magento 2 code standards, and particularly PSR1: https://www.php-fig.org/psr/psr-1/

**Comment by sivaschenko** [comment]
Hi @GraysonChiang , thank you for your contribution, please update the code style to match PSR-1 and sign the [Contributor License Aggreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18859) so that we can process the pull request further

**Comment by sidolov** [comment]
Hi @GraysonChiang , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
