### PR TITLE
magento/magento2#23054

### LINKED ISSUE #23054: Cron job not running after crashed once
### Preconditions (*)
Magento EE 2.2.8
Crontab configured as per the documentation

### Steps to reproduce (*)
- An error makes the cron job indexer_update_all_views fail once (in my case, database unavailable)

### Expected result (*)
- Current run should be marked as failed in the table cron_schedule
- Next run should run correctly and status be updated at the end in cron_schedule

### Actual result (*)
Table cron_schedule is filled with pending jobs, no job for indexer_update_all_views is run (no output in var/log/cron.log, no status update in cron_schedule table.

Logs :
var/log/cron.log (last success + the error message)
```
[2019-05-29 11:25:10] report.INFO: Cron Job indexer_update_all_views is run [] []
[2019-05-29 11:28:03] report.ERROR: Cron Job indexer_update_all_views has an error: SQLSTATE[08S01]: Communication link failure: 1047 WSREP has not yet prepared node for application use, query was: SELECT `mview_state`.* FROM `mview_state` WHERE (`mview_state`.`view_id`='catalog_product_flat'). Statistics: {"sum":0,"count":1,"realmem":0,"emalloc":0,"realmem_start":182714368,"emalloc_start":180313880} [] []
```
=> And then no more logs about indexer_update_all_views, even if other jobs from the index group run correctly and output success in var/log/cron.log
Database recovered a minute after and query was OK

### PR DESCRIPTION
**Pull request by mamsincl**
### Description (*)

Extending Magento/Cron module with functionality of being able to close the orphan/stale running cron tasks (schedules) which been started before, but somehow stopped running

### Fixed Issues (if relevant)

1. Fixes #23054 : Cron job not running after crashed once

### Manual testing scenarios (*)

preconditions:
1. _ps_ command availability on server
2. _php bin/magento setup:upgrade_ to apply modifications in database
3. run _php bin/magento cron:run_ multiple time (or be sure that crontab does the same) to get the necessary data for process schedules

(scenario a)
1. change "success" to "running" on couple of job on _cron_schedule_ table
2. run _php bin/magento cron:run_ 
3. check the modified rows

(scenario b)
1. run _php bin/magento cron:run_ on CLI
2. shut down/restart the server from a different console before getting back the prompt
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-hostname.html
### Questions or comments

If you using multiple instances or in cloud environment, be sure that you have set up the hostname(s) of your instance(s) (eg. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-hostname.html) in prior to avoid false negative match if you checking the hostnames as well

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24789) <br/>All committers have signed the CLA.

**Comment by mamsincl** [comment]
Hello @magento-engcom-team, @buskamuza and @tariqjawed83 ,

I do not know If you ever checking tests results if any is failing, but - since I not even touch it - **Unit Tests build**  errors came from original branch.
 Also unable to do anything with the suggested version increase in **Semantic Version Checker build**, since I had to implement those modifications into (even new) files to cover everything (setting with default value, language file, etc)

The failing of **Static Tests build** is coming from my additions, the reasons are:
- _Magento\Test\Integrity\ObserverImplementationTest_ is failing since my main function - which is responsible for clearing the database - is ***public*** to give the chance to the integrators to implement their own solution (there are multiple workarounds already available to solve the issue)
- _Magento\Test\Php\LiveCodeTest_ is failing mainly of using ***shell_exec*** command: the reason of using it, since Magento Shell class implements ***exec*** php command to execute console command - but often happening that the output (of ***exec***) just coming back truncated which happened during development process ..... that is the reason of using forbidden and discouraged php functions 
I am not too keen, but can re-implement *Magento\Framework\Shell* if necessary even with possible issue of the command output - or even extending *Shell* class with a new public function to implement ***shell_exec*** function (but this also will failing static test with the same issue)

**Comment by mamsincl** [comment]
Hi @magento-engcom-team @magento-cicd2,

Can you review my comments and react as well, please.

Thanks,
Robert

**Comment by brucemead** [comment]
Any update on this one please?

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @mamsincl, thanks for your contribution and sorry for the delay in processing it.

I'm not sure if cleaning of orphan/stale jobs from the cronjob schedule table is a good idea, we are basically masking the problem, and by removing that probably the developer won't even be aware that there could be a problem. Usually, this kind of issue happens when something needs to be fixed, so I guess it would be better something that improves developer visibility on such problems.

I'm not sure if you have seen this but we have this proposal https://github.com/magento/architecture/pull/171/files, which has really nice ideas on how to make cronjob more reliable, if you are interested in this we could start some discussion on how to start such implementation.

Please let me know your thoughts.

Thanks.

**Comment by gabrieldagama** [comment]
Closing this PR due to contributor inactivity, if you still want to work on this please feel free to reopen it. Thank you!

**Pull request closed without merging**
