### PR TITLE
fix for ambigous column user_id in where clause

### LINKED ISSUE #31216: [Issue] fix for ambigous column user_id in where clause
This issue is automatically created based on existing pull request: magento/magento2#31205: fix for ambigous column user_id in where clause

---------
Magento\Users\Model\ResourceModel\User\Collection addFilterToMap for user_id 

### Description (*)
When filtering Magento\Users\Model\ResourceModel\Users\Collection by user_id , it throws an SQL exception ( ambigous user_id in where condition )

**Preconditions:**

Magento version: 2.4-develop
PHP version: 7.4
ElasticSearch version: 7
MySQL version: 8.0

**Manual testing scenario:**

1. Add the code from the attached file 
[Code_to_reproduce_31205.zip](https://github.com/magento/magento2/files/5730136/Code_to_reproduce_31205.zip)
2. Run in console: `php bin/magento setup:upgrade`;
3. Log in to the admin panel;
4. open URL <domain>/admin/column;

**Actual Result:** :heavy_multiplication_x:  2 exceptions occur

Screenshot from 2021-02-02 15-26-29

**Expected Result:** :heavy_check_mark: No exceptions

### PR DESCRIPTION
**Pull request by dorupetruc**
Magento\Users\Model\ResourceModel\User\Collection addFilterToMap for user_id 

### Description (*)
When filtering Magento\Users\Model\ResourceModel\Users\Collection by user_id , it throws an SQL exception ( ambigous user_id in where condition )

### Manual testing scenarios (*)

1. go to Backend > System > Permissions > All users grid
2. filter the grid by ID
3. expected result : grid filtered by ID
actual result: first time it redirects to dashboard & subsequent access of All Users grid throws the aabove exception.

### Resolved issues:
1. [x] resolves magento/magento2#31216: fix for ambigous column user_id in where clause

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Comment by danielrussob** [comment]
@magento give me 2.4-develop instance

**Comment by danielrussob** [comment]
@magento give me test instance

**Comment by danielrussob** [comment]
@magento run all tests

**Comment by danielrussob** [comment]
Hello, @dorupetruc 
thanks for your contribution! 💯 


As: https://github.com/magento/magento2/pull/31205/checks?check_run_id=1517247098 
Please sign "Adobe CLA Signed" 


Tell me if you have some problems 👍

**Comment by danielrussob** [comment]
@magento give me 2.4-develop instance

**Comment by danielrussob** [comment]
Hello @dorupetruc,
we (CC: @aleron75) are not able to reproduce the issue on vanilla Magento 2.4 Instance

Can you confirm that the **only steps** to reproduce the issue are the following:

go to Backend > System > Permissions > All users grid
filter the grid by ID
expected result: grid filtered by ID
actual result: the first time it redirects to dashboard & subsequent access of All Users grid throws the above exception.


Can you try with:

@magento give me 2.4-develop instance

**Comment by aleron75** [comment]
Thanks @dorupetruc for your contribution.

I managed to get the exception by running the following script in a Magento root directory and I confirm that the error is fixed with the changes provided by this PR:
```php
<?php
// set error verbosity
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

// require boostrap file
try {
    require __DIR__ . '/app/bootstrap.php';
} catch (\Exception $e) {
    echo $e->getMessage() . PHP_EOL;
    exit(1);
}

// bootstrap framework
$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $_SERVER);
/** @var \Magento\Framework\App\Http $app */

// get the Object Manager
$objectManager = $bootstrap->getObjectManager();

// set application area
$state = $objectManager->get('Magento\Framework\App\State');
$state->setAreaCode(\Magento\Framework\App\Area::AREA_ADMINHTML);

// TEST CODE 
/** @var \Magento\User\Model\ResourceModel\User\Collection::class $collection */
$collection = $objectManager->get(\Magento\User\Model\ResourceModel\User\Collection::class);
$collection->addFieldToFilter('user_id', 1);
$collection->count();
```
Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing_dod.html), all code must be covered by tests.

For this specific case, this fix should be covered by automated tests with the scenario which leads to an issue: tests should fail on the mainline and pass with this fix.

I suggest adding a `\Magento\User\Test\Unit\Model\ResourceModel\User\CollectionTest.php` unit test to prove that this PR fixes the issue.

**Review by aleron75 — CHANGES_REQUESTED** [review]
Hello @dorupetruc, do you think it's feasible to cover this PR by automated tests?

**Comment by engcom-Hotel** [comment]
Hello @dorupetruc 
Can't reproduce the issue. Could you please check https://github.com/magento/magento2/issues/31216#issuecomment-747463125
Thank you.

**Comment by dorupetruc** [comment]
Try to filter by user_id

**Comment by engcom-Hotel** [comment]
31205_not_able_to_rep2
Also works, are you able to reproduce it on 2.4?

**Comment by engcom-Hotel** [comment]
Hello @dorupetruc,
I have checked steps to reproduce from @aleron75 https://github.com/magento/magento2/pull/31205#issuecomment-742344627 and was able to reproduce the issue.
Steps:
Magento version: 2.4-develop
PHP version: 7.4
ElasticSearch version: 7
MySQL version: 8.0
1. Add the code from the attached file 
[Code_to_reproduce_31205.zip](https://github.com/magento/magento2/files/5730136/Code_to_reproduce_31205.zip)
2. bin/magento se:up
3. log in to admin panel
4. open URL <domain>/admin/column
Exspected: 1
Actual: 2 exception(s)...

Could you please update the description with proper steps to reproduce the issue?
Thank you.

**Comment by engcom-Hotel** [comment]
I will help with the test coverage.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Integration Tests, Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Review by aleron75 — APPROVED** [review]

**Review by danielrussob — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

### Case 1.

**Manual testing scenario:**

1. Add the code from the attached file 
[Code_to_reproduce_31205.zip](https://github.com/magento/magento2/files/5730136/Code_to_reproduce_31205.zip)
2. Run in console: `php bin/magento setup:upgrade`;
3. Log in to the admin panel;
4. open URL <domain>/admin/column;

**Before:** :heavy_multiplication_x:  2 exceptions occur

Screenshot from 2021-02-02 15-26-29

**After:** :heavy_check_mark: No exceptions

Screenshot from 2021-02-02 16-08-03

### Case 2.

**Manual testing scenario:**

1. Go to Admin -> System -> Permissions -> All users grid;
2. Filter the grid by ID;

**After:** :heavy_check_mark:  The grid filtered by ID correctly 
Peek 2021-02-03 09-24

**Comment by magento-engcom-team** [comment]
@dorupetruc thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request merged**
