### PR TITLE
Make align edit and remove icon in the minicart.

### PR DESCRIPTION
**Pull request by chirag-wagento**
### Description (*)

In the minicart edit and remove icon is not aligned.

### Fixed Issues (if relevant)

1. magento/magento2#26652: In the minicart edit and remove icon is not aligned.

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lenaorobei — DISMISSED** [review]
Failures are not related to the changes in this PR.

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-7070](https://jira.corp.magento.com/browse/ENGCOM-7070) has been created to process this Pull Request

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @chirag-wagento.

Looks like edit and remove icons still don't seem to be aligned properly (on luma and blank themes)

**Actual Result:**
after

@chirag-wagento Could you take a look?

Thanks!

**Comment by lenaorobei** [comment]
Closing this PR due to inactivity. Please feel free to reopen if you are going to continue working on it.
Thank you.

**Pull request closed without merging**
