### PR TITLE
Changed "active" to "enabled" in bin/magento maintenance:status command

### LINKED ISSUE #38486: [Issue] Changed "active" to "enabled" in bin/magento maintenance:status command
This issue is automatically created based on existing pull request: magento/magento2#38410: Changed "active" to "enabled" in bin/magento maintenance:status command

---------
### Description (*)

I noticed that for changing maintenance mode using the commands `bin/magento maintenance:enable` and `bin/magento maintenance:disable`. But when executing the command `bin/magento maintenance:status`,  I got `Status: maintenance mode is active`.

### Changes Made
This Pull Request updates the output message of the `bin/magento maintenance:status` command. The status message has been modified for better clarity, changing from `active` to `enabled` and from `not active` to `disabled` for a more accurate representation of the maintenance mode status.

**Before :**

Screenshot from 2024-02-01 20-46-19

**After :**

Screenshot from 2024-02-02 17-56-30

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by YevhenZvieriev**
### Description (*)

I noticed that for changing maintenance mode using the commands `bin/magento maintenance:enable` and `bin/magento maintenance:disable`. But when executing the command `bin/magento maintenance:status`,  I got `Status: maintenance mode is active`.

### Changes Made
This Pull Request updates the output message of the `bin/magento maintenance:status` command. The status message has been modified for better clarity, changing from `active` to `enabled` and from `not active` to `disabled` for a more accurate representation of the maintenance mode status.

**Before :**

Screenshot from 2024-02-01 20-46-19

**After :**

Screenshot from 2024-02-02 17-56-30

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38486: Changed "active" to "enabled" in bin/magento maintenance:status command

### CODE REVIEW

**Comment by YevhenZvieriev** [comment]
@magento run all tests

**Comment by hostep** [comment]
I'm not a fan of this, there is nothing wrong with 'active' or 'not active' in my opinion. But that's just my opinion.

Also, if we do go ahead with this, then change it in correct English and call it 'enabled' and 'not enabled' please.

**Comment by YevhenZvieriev** [comment]
Hi, @hostep!

Thank you for your feedback. I value your viewpoint and will take into account your recommendation about using 'enabled' and 'disabled' instead.

I'll update the pull request after making the required changes.

**Comment by YevhenZvieriev** [comment]
@magento run all tests

**Review by berliozd — APPROVED** [review]

**Review by andrewbess — CHANGES_REQUESTED** [review]
Hello @YevhenZvieriev 
Thank you for your contribution
Could you please fixe unit tests too
Thank you in advance.

**Comment by YevhenZvieriev** [comment]
@magento run all tests

**Comment by YevhenZvieriev** [comment]
@magento run all tests

**Comment by YevhenZvieriev** [comment]
Hello @andrewbess 

I fixed Unit Tests

**Comment by YevhenZvieriev** [comment]
@magento run all tests

**Comment by YevhenZvieriev** [comment]
Hello @andrewbess 

I've addressed the unit test failures, and the code now passes all unit tests successfully. Please review the updated version of the PR at your earliest convenience.

**Comment by andrewbess** [comment]
@magento run WebAPI Tests, Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by andrewbess** [comment]
@magento run WebAPI Tests, Functional Tests EE, Functional Tests B2B

**Comment by andrewbess** [comment]
@magento run WebAPI Tests, Functional Tests B2B

**Comment by andrewbess** [comment]
The WebAPI test failures look like flaky
- https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38410/ec6b8ab8d72d852d3d3be902b88971dd/WebApi/console-error-logs.html
- https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38410/d475a22075197f938e835653443d7032/WebApi/console-error-logs.html
- https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38410/794855ce474c81e2b7ec9d9e53491731/WebApi/console-error-logs.html

**Review by andrewbess — APPROVED** [review]
Fixes look good for me
Approved
Thank you @YevhenZvieriev for your work here

**Comment by engcom-Delta** [comment]
@magento create issue

**Comment by engcom-Delta** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** 

**Manual testing scenario:**

1. bin/magento maintenance:enable
2. bin/magento maintenance:status
3. bin/magento maintenance:disable
4. bin/magento maintenance:status

**Before:** :heavy_multiplication_x: 


Screenshot 2024-03-04 at 7 38 26 PM


**After:** :heavy_check_mark:  

Screenshot 2024-03-04 at 7 50 02 PM


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@maegnto run Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
Functional Tests B2B failure are different on last two run on same commit.
Run1
Screenshot 2024-03-05 at 4 22 25 PM

Run2
Screenshot 2024-03-05 at 4 22 29 PM


Hence moving it to `merge in progress.`

**Comment by engcom-Charlie** [comment]
It seems that bot moved this PR to testing hence moving back to Merge in Progress.

**Pull request merged**
