### PR TITLE
Import - Allowed Error Count Fix For Zero Or Greater #36252

### LINKED ISSUE #36252: Custom Import - Not allowed to set "allowed error count" to 0
### Preconditions and environment

- Magento 2.4.2-p2
- PHP7.4

### Steps to reproduce

1. Navigate to admin
2. system -> import
3. pick any from dropdown
4. try to set allowed error count to 0
5. validation says you need to enter a number greater than 0
Screenshot 2022-10-06 at 16 00 04

### Expected result

0 is an accepted value for allowed error count.
Within the code base:

vendor/magento/module-import-export/Model/Import/ErrorProcessing/ProcessingErrorAggregator.php
`public function initValidationStrategy($validationStrategy, $allowedErrorCount = 0)
    {`

The default value for allowed error count is 0, but it is being forced higher due to admin frontend validation

### Actual result

Have to enter a value greater than 0. To work around this issue, entering 0.0001 works, as it is technically greater than 0, and the code type casts it to int, where it is rounded to 0.

### Additional information

I have submitted a PR to fix this https://github.com/magento/magento2/pull/36253

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by asim-blueprintprep**
### Description (*)
This PR sets Allowed Error Count in the Import/Export module to accept 0 or greater value to match the backend code where the default value is 0.
vendor/magento/module-import-export/Model/Import/ErrorProcessing/ProcessingErrorAggregator.php
`public function initValidationStrategy($validationStrategy, $allowedErrorCount = 0) {`

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36252

### Manual testing scenarios (*)
1. Log in to admin
2. System -> Import
3. Pick any from drop down
4. Change allowed error count to 0 and click check data
5. Before PR change, it will throw a validation rule it must be greater than 0
6. After PR change, it will accept 0 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by asim-blueprintprep** [comment]
@magento give me 2.4-develop instance

**Comment by asim-blueprintprep** [comment]
I can confirm the bug exists on 2.4-develop

**Comment by asim-blueprintprep** [comment]
@magento give me test instance

**Comment by asim-blueprintprep** [comment]
I can confirm the bug is resolved after this PR has gone through

**Comment by asim-blueprintprep** [comment]
@magento run all tests

**Comment by asim-blueprintprep** [comment]
@magento run Functional Tests B2B

**Comment by asim-blueprintprep** [comment]
Does anyone know why the functional tests fail? All I see is a 404 - I will mark task as complete for now due to error running test.

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B , Functional Tests CE ,Functional Tests EE

**Comment by engcom-Lima** [comment]
@magento run Functional Tests CE ,Functional Tests EE

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento `2.4-develop`

**Manual testing scenario:**

1. Log in to admin
2. System -> Import
3. Pick any from drop down
4. Change allowed error count to 0 and click check data
5. Before PR change, it will throw a validation rule it must be greater than 0
6. After PR change, it will accept 0

**Before:** :heavy_multiplication_x: 
image


**After:** :heavy_check_mark:  
image

**Additionally tested:**
Imported different kinds of options available successfully.

Since minor code changes hence,no additional manual test case is required .

**Comment by hostep** [comment]
Halelujah, this silly bug was been driving me crazy last week. Thanks for the fix @asim-blueprintprep!

**Pull request merged**
