### PR TITLE
Added Fix for 25936

### PR DESCRIPTION
**Pull request by divyajyothi5321**
### Fixed Issues (if relevant)

1. magento/magento2#25936: Regular Price Label Alignment Issues in Frontend

### Manual testing scenarios (*)

1. Admin->Catalog->Products->Add Product
2. Add Price ex:$20
3. Click on Advanced Pricing and add regular price ex:$10
4. Save the product
5. Open product in frontend
6. With this fix advanced pricing aligned in single line

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by aleron75** [comment]
@magento give me test instance

**Comment by aleron75** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @aleron75. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @aleron75. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @aleron75, here is your [Magento instance](https://i-26237-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26237-2-4-develop.instances.magento-community.engineering/admin](https://i-26237-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by aleron75** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @aleron75. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @aleron75, here is your [new Magento instance](https://pr-26237.instances.magento-community.engineering).
Admin access: [https://pr-26237.instances.magento-community.engineering/admin](https://pr-26237.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by aleron75 — APPROVED** [review]
I verified the fix on Chrome 79.0.3945.88 (Linux), see screenshot below:

Workspace 1_010

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-6534](https://jira.corp.magento.com/browse/ENGCOM-6534) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Review by ptylek — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-6534](https://jira.corp.magento.com/browse/ENGCOM-6534) has been created to process this Pull Request

**Pull request merged**
