### PR TITLE
Allow items to be shipped with a qty > 0 and < 1 #35972

### LINKED ISSUE #35971: Unable to ship items with a qty > 0 and < 1
### Preconditions and environment

- 2.4.5 (and prior)
- Product must have qty uses decimals enabled and a minimum qty in cart below zero (i.e. 0.2)

### Steps to reproduce

1. Create simple product in admin
2. Enable qty uses decimals for the product
3. Set minimum qty in cart equal to 0.2
4. Create an order - adding a qty of 0.5 for the test product
5. Order / Invoice create correctly
6. Ship the order

### Expected result

Shipment is created with a qty of 0.5

### Actual result

Shipment "items" are blank and therefore, you cannot create shipment

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by engcom-Delta**
### Description (*)
Cast the qty to a float, rather than an int. The casted value is checked for <= 0, so anything > 0 and < 1 would be (incorrectly) cast to a 0. If this check fails, the item is not added to the shipment. By casting to a float, the validation is passed correctly and you can now ship items with a qty between 0 and 1.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35971

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
same https://github.com/magento/magento2/pull/35972

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento run Functional Tests, Integration Tests

**Comment by engcom-Delta** [comment]
@magento run  Functional Tests B2B

**Comment by engcom-Delta** [comment]
@magento run Integration Test

**Comment by engcom-Delta** [comment]
@magento run Functional Tests

**Comment by engcom-Delta** [comment]
@magento run Functional Tests CE

**Comment by engcom-Delta** [comment]
@magento run Integration Tests

**Comment by engcom-Delta** [comment]
Since this is a new PR  for [PR](https://github.com/magento/magento2/pull/35972), In this PR static test failure was fixed and all the checks are passed. Hence moving this PR to Merge in Progress.

Thanks.

**Comment by ihor-sviziev** [comment]
@engcom-Delta don't you think it should be covered with some automated test?

**Comment by engcom-Delta** [comment]
Hi @ihor-sviziev @ishakhsuvarov

we have covered and updated the unit testcase in this PR as per the reviewed changes in [PR](https://github.com/magento/magento2/pull/36373).

Thanks

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@engcom-Delta That's great that you are added unit tests. But I have a question. ObjectManager is deprecated to use in unit tests and in fact new unit test still use this functional. I see that it's easy to use deprecated functional in same way of other tests, but in fact it's increase  amount of legacy code.
Do you think that make sense to replace ObjectManager usage with `new` command?

**Comment by engcom-Delta** [comment]
@Den4ik
Thank you for reviewing. Since this PR is merged, Hence we will update the unittest case as per the comment in new PR.
Thanks.

**Comment by engcom-Delta** [comment]
@Den4ik 
Thank you for reviewing. Since this PR was merged, Hence we will update the new PR according to the [comment](https://github.com/magento/magento2/pull/36232#issuecomment-1294099901).
Thanks

**Pull request merged**
