### PR TITLE
:speech_balloon: fix typo in php doc

### LINKED ISSUE #29470: [Issue] :speech_balloon: fix typo in php doc
This issue is automatically created based on existing pull request: magento/magento2#29451: :speech_balloon: fix typo in php doc

---------

### Description (*)
fix a typo in downloadable in the class description of \Magento\Downloadable\Block\Sales\Order\Email\Items\Downloadable

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by brosenberger**
### Description (*)
fix a typo in downloadable in the class description of \Magento\Downloadable\Block\Sales\Order\Email\Items\Downloadable

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29470: :speech_balloon: fix typo in php doc

### CODE REVIEW

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-7983](https://jira.corp.magento.com/browse/ENGCOM-7983) has been created to process this Pull Request
:eight_spoked_asterisk: @swnsma, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
@magento create issue

**Pull request merged**
