### PR TITLE
This will shorten the list of allowed currencies

### PR DESCRIPTION
**Pull request by melaxon**
### Description (*)

I was not sure where to find Magento/Framework on github and created this file.

The change will check currency list in Store->Configuration->General->Currency setup against selected currencies in "Installed" list (Configuration->Advanced->System)
Only selected currencies will be listed to shorten the list and simplify the settings

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @melaxon. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19829) <br/>All committers have signed the CLA.

**Review by orlangur — CHANGES_REQUESTED** [review]
Hi @melaxon, I don't see this file used anywhere in your PR.

**Comment by melaxon** [comment]
Please discard this PR

**Pull request closed without merging**
