### PR TITLE
issue fixed #19866 Configurable product grid legend label overlapping

### PR DESCRIPTION
**Pull request by cedarvinda**
issue fixed #19866 Configurable product grid legend label overlapping

### Description (*)

issue fixed #19866 Configurable product grid legend label overlapping

### Manual testing scenarios (*)

Step 1: Go to admin url
Step 2: login to admin panel
Step 3: click on Catalog link from left side then click on product link in sub menu
Step 4: Click on add product button dropdown and select simple product
Step 5: Fill simple product form and click create configuration button existing under Configurations tab.
Step 6: Complete steps to create configuration (Popup will open)
Step 6.1: Select Attributes then click next button
Step 6.2: Select Attribute Values then click in next button
Step 6.3: Bulk Images, Price and Quantity then click next button
Step 6.4: Summary screen will show and click on generate product button
Now you will see issue (ref actual result screenshot image)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by cedarvinda** [comment]
@VladimirZaets please review this PR.

**Comment by cedarvinda** [comment]
@nuzil can you please review this ?

**Comment by nuzil** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @nuzil. Thank you for your request. I'm working on Magento instance for you

**Comment by cedarvinda** [comment]
@magento-engcom-team give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by cedarvinda** [comment]
@magento-engcom-team give me 2.3-develop instance.

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda, here is your [Magento instance](https://i-19951-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19951-2-3-develop.instances.magento-community.engineering/admin](https://i-19951-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by cedarvinda** [comment]
@nuzil please review now.

**Comment by nuzil** [comment]
Pls have a look at test result. Looks like issue is still there
screen shot 2019-01-10 at 10 11 16

**Review by nuzil — CHANGES_REQUESTED** [review]
Please see test results

**Comment by cedarvinda** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @cedarvinda, here is your [new Magento instance](https://pr-19951.instances.magento-community.engineering).
Admin access: [https://pr-19951.instances.magento-community.engineering/admin](https://pr-19951.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by cedarvinda** [comment]
@nuzil  above instance was develop instance not test instance.

**Comment by cedarvinda** [comment]
I checked in my test instance its fine (pref screenshot and test instance)
eeeeee

**Review by nuzil — APPROVED** [review]
Yes, correct. its fine

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-3830](https://jira.corp.magento.com/browse/ENGCOM-3830) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @cedarvinda thanks for the contribution. I think this issues should be fixed by removing the unneeded label rather than making it transparent. Would you be able to correct the fix?

**Comment by sivaschenko** [comment]
@cedarvinda I am closing this pull request due to inactivity. Feel free to reach me if you'd like to continue work on this contribution.

**Comment by cedarvinda** [comment]
@sivaschenko still any issue in this PR ?

**Comment by sivaschenko** [comment]
@cedarvinda yes, please see comment https://github.com/magento/magento2/pull/19951#issuecomment-454000015
I don't think hiding an element is the correct solution in this case.

**Comment by sivaschenko** [comment]
Closing this pull request due to inactivity, feel free to reopen if you'd like to continue progress

**Pull request closed without merging**
