### PR TITLE
Resolve wrong Cursor icon when hover in "Images And Videos" small, thumbnail ... options

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

Resolve wrong Cursor icon when hover in "Images And Videos" small, thumbnail, ...,
In 2.3-develop:

image

It must be:

image

### Manual testing scenarios (*)

1. Go to backend
2. Edit one product
3. Go to "Images And Videos"
4. Upload Images
5. Hover "small" or "thumbnail"
See hand icon:

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rodrigowebjump** [comment]
@magento give me 2.3-develop instance\

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [Magento instance](https://i-25749-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25749-2-3-develop.instances.magento-community.engineering/admin](https://i-25749-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rodrigowebjump** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [new Magento instance](https://pr-25749.instances.magento-community.engineering).
Admin access: [https://pr-25749.instances.magento-community.engineering/admin](https://pr-25749.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rodrigowebjump — APPROVED** [review]
Hi @edenduong 

Thanks for your contribution

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-6346](https://jira.corp.magento.com/browse/ENGCOM-6346) has been created to process this Pull Request
:eight_spoked_asterisk: @rodrigowebjump, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
