### PR TITLE
Fixed issue : Trim whitespace on SKU when saving product #16572

### PR DESCRIPTION
**Pull request by AnshuMishra17**
### Description
Strip whitespace from the beginning and end of SKU while saving product in admin.

### Fixed Issues
1. magento/magento2#16572: Trim whitespace on SKU when saving product

### Manual testing scenarios
1. Added new product with sku having whitespaces in beginning, at the end and at both the beginning and the end.
2. Updated product with sku having whitespaces in beginning, at the end and at both the beginning and the end.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @AnshuMishra17. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by VladimirZaets** [comment]
Hi @AnshuMishra17, thank you for collaboration.
We tested your PR and we found the case where SKU isn't trimmed.

**Problem**: SKU isn't trimmed for configurable product options.
**Manual testing scenario**:

1. Create configurable product that has SKU with whitespaces.
2. Before save this product create configurations.
3. Save Configurable product.


**Expected result**: Configurable product SKU is trimmed.
**Actual result**: Configurable options are saved with whitespaces.

**Comment by VladimirZaets** [comment]
Hi @AnshuMishra17. Thanks for fixes

**Comment by VladimirZaets** [comment]
Hi @AnshuMishra17. 
We tested your PR and we found the next problem:

**Problems:** SKU of configurable product isn't trimmed before Configurations are generated. It caused whitespaces in SKU of generated simple products.

**Manual testing scenario:**
Create configurable product that has SKU with whitespaces(in the beginning and at the end).
Before save this product create configurations.
Save Configurable product.
 **Whitespaces are inside SKU of configurations.**

**Comment by AnshuMishra17** [comment]
@VladimirZaets I have added the the code to trim while simple products are generated. Where exactly these should be trimmed, means at which step child product SKU needs t o be trimmed?

**Comment by VladimirZaets** [comment]
Hi @AnshuMishra17, with the child products all are ok, but the SKU of the configurable product itself isn't trimmed.

**Comment by AnshuMishra17** [comment]
@VladimirZaets I have fixed the above mentioned issue.

**Comment by VladimirZaets** [comment]
@AnshuMishra17 thanks

**Comment by VladimirZaets** [comment]
Hi @AnshuMishra17.  I am closing this PR because the PR [#18019](https://github.com/magento/magento2/pull/18019) provided a more complex solution for this issue, namely:

1) Provided and used new rules for frontend validation.
2) Worked with API calls

Thank you for collaboration.

**Pull request closed without merging**
