### PR TITLE
[vcl] don't explicitly hash the host header

### LINKED ISSUE #29988: [Issue] [vcl] don't explicitly hash the host header
This issue is automatically created based on existing pull request: magento/magento2#28928: [vcl] don't explicitly hash the host header

---------
Hashing `req.http.host`/`client.ip` is already handled by the [built-in
vcl](https://github.com/varnishcache/varnish-cache/blob/6.0/bin/varnishd/builtin.vcl#L86)
so there's no need to repeat it explicitly.

It's also a bit confusing as `req.url` is not explicitly handled, even
though it's a more important hash input than the host.

note: all versions have been changed for the sake of consistency
but both the 4.x and 5.x series have been EOL'd a (long) while ago and users
should be encouraged to upgraded as soon as possible.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by gquintard**
Hashing `req.http.host`/`client.ip` is already handled by the [built-in
vcl](https://github.com/varnishcache/varnish-cache/blob/6.0/bin/varnishd/builtin.vcl#L86)
so there's no need to repeat it explicitly.

It's also a bit confusing as `req.url` is not explicitly handled, even
though it's a more important hash input than the host.

note: all versions have been changed for the sake of consistency
but both the 4.x and 5.x series have been EOL'd a (long) while ago and users
should be encouraged to upgraded as soon as possible.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29988: [vcl] don't explicitly hash the host header

### CODE REVIEW

**Comment by gquintard** [comment]
@magento run all tests

**Review by lbajsarowicz — APPROVED** [review]
Nice catch!

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7759](https://jira.corp.magento.com/browse/ENGCOM-7759) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@gquintard thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by gquintard** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
**Automated Tests** are not applicable, as the change is related to infrastructure configuration.

**Comment by sidolov** [comment]
@magento create issue

**Comment by engcom-Bravo** [comment]
Dev experience is required for testing of this PR. Please note that Manual testing has not been performed.

**Comment by engcom-Charlie** [comment]
:heavy_check_mark: QA Passed

Hashing is already handled by the built-in vcl starting from varnish 4.0.
Magento-supported varnish versions are 4.x, 5.2 or 6.x (see https://devdocs.magento.com/guides/v2.4/config-guide/varnish/config-varnish-install.html).

**Pull request merged**
