### PR TITLE
Update Ga.php to fix no revenue data in GA4

### LINKED ISSUE #37605: No revenue data in GA4 when using Magento_GoogleGtag extension
### Preconditions and environment

Magento 2.4.5-p1
Google Analytics 4

### Steps to reproduce

Switch on Google Analytics 4 part of the Magento Google Gtag extension
Place an order
Wait for data to appear in Google Analytics 4
On GA4, goto Reports->Monetization-> E-commerce purchases

### Expected result

Correct revenue data is reported

### Actual result

Items purchased (quantities) are reported correctly but revenue is reported as zero.

### Additional information

If you Google the issue of revenue not showing on GA4, a common problem is that the currency is not being passed in the purchase event.

According to the Google developer documentation there ought to be (an ISO 3) currency field set in the purchase event data: see https://developers.google.com/analytics/devguides/collection/ga4/ecommerce?sjid=1876830166853332977-EU&client_type=gtag

When I added console.log statements to vendor/magento/module-google-gtag/view/frontend/web/js/google-gtag.js, I can see that the purchaseObject data sent with the purchase event does not contain a currency field.

Probably needs an urgent fix given that the deadline for GA4 adoption is 1st July 2023

Regards

Mark

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by DomPixie**
### Description (*)

Fix for No revenue data in GA4

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/37605

### Manual testing scenarios (*)

1. Switch on Google Analytics 4 part of the Magento Google Gtag extension
2. Place an order
3. Wait for data to appear in Google Analytics 4
4. On GA4, goto Reports->Monetization-> Verify the Revenue in the Monetization overview.

Correct revenue data is reported

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by DomPixie** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Please fix failing unit tests

**Comment by DomPixie** [comment]
@magento run Unit Tests

**Comment by DomPixie** [comment]
@ihor-sviziev I believe this has been done - thanks

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Unit Tests, Integration Tests, WebAPI Tests, Functional Tests CE, Functional Tests B2B, Functional Tests EE

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Unit Tests

**Comment by engcom-Echo** [comment]
@magento run Unit Tests

**Comment by engcom-Echo** [comment]
@magento run Unit Tests

**Comment by engcom-Echo** [comment]
Test failure are not related to PR changes.
Hence moving to `Pending Review`

**Review by engcom-Hotel — APPROVED** [review]
Failed test seems flaky to me, hence approving the PR.

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by engcom-Lima** [comment]
@magento give me test instance

**Comment by engcom-Lima** [comment]
@magento give me test instance with ee edition

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**
- Account should be created on the Google of GA4.

**Manual testing scenario:**

1. Switch on Google Analytics 4 part of the Magento Google Gtag extension
2. Place an order
3. Wait for data to appear in Google Analytics 4
4. On GA4, go to Reports->Monetization and verify the Correct revenue data is reported

**Before:** :heavy_multiplication_x: 

Screenshot 2023-08-07 at 12 54 35 PM

**After:** :heavy_check_mark:  
Screenshot 2023-08-07 at 12 45 25 PM
Screenshot 2023-08-07 at 12 45 30 PM


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
Failing test are not related to PR changes.
Hence moving it to `Merge in progress`

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Unit Tests,Integration Tests,Functional Tests EE,Functional Tests CE

**Comment by engcom-Echo** [comment]
Functional Tests EE and Functional Tests CE failure are different on last two run.
Functional Tests CE
Run1
37668-ce

Run2
37668-ce2


Functional Tests EE
Run1
37668-ee

Run2
37668-ee2

Other Failures are not related to PR

**Pull request merged**
