### PR TITLE
Make sure Yes/No attribute Layered Navigation filter uses index

### PR DESCRIPTION
**Pull request by stkec**
Fixes performance degradation when using Yes/No attributes in Layered navigation [#21771](Related Issue: https://github.com/magento/magento2/issues/21771)

### Description (*)
After [#3283](https://github.com/magento/magento2/issues/3283) merged it is possible to use Yes/No attributes in Layered Navigation. But when MySql engine assembles the SQL query there are 2 more places where FrontendInput of the Layered Navigation Attribute is hardcoded as ['select', 'multiselect']. As a result, Yes/No attribute processed not as a 'Term' condition as it suppose to be for Layered Attribute but as a default unknown condition

### Fixed Issues (if relevant)
1. magento/magento2#21771: Performance degradation in Layered navigation using Yes/No attribute

### Manual testing scenarios (*)
1. Set Yes/No Product attribute 'Filterable'
2. Go to Anchor Category Page on frontend
3. Try to apply filter by Yes/No attribute

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21772) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @stkec. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4504](https://jira.corp.magento.com/browse/ENGCOM-4504) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@stkec thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by p-bystritsky** [comment]
QA passed.

**Pull request merged**
