### PR TITLE
Fix #3637 Add missing catalogsearch layout for swatches.

### LINKED ISSUE #3637: Swatches does not work properly into Catalogsearch
Steps to reproduce : 
- Pick an attribute based on swatches (ie. "color" on Magento with sample datas).
- Set "Use in Search Results Layered Navigation" to "Yes".
- Go to catalogsearch result page.

=> The swatches are appearing on the DOM, but, they are not displayed properly.

This may be due to the fact that there is no layout for catalogsearch_result_index in the swatches module.

### PR DESCRIPTION
**Pull request by romainruaud**

### CODE REVIEW

**Comment by davidalger** [comment]
@romainruaud Please sync with latest develop. The failing PHP 5.5 tests have been fixed.

**Comment by romainruaud** [comment]
@davidalger I have done this, but the Travis server seems to have rebooted during tests ... (The system is going down for power off now).

What should I do ?

**Comment by davidalger** [comment]
I rebooted that test and they are all green now. Thanks for the contribution! This is now up to the core team to review and process.

**Comment by piotrekkaminski** [comment]
internal issue MAGETWO-54586

**Pull request merged**
