### PR TITLE
Properly hyphenate "third-party"

### PR DESCRIPTION
**Pull request by erikhansen**
To review the text edited by this PR, go to "CONTENT > Design > Configuration" and click on any row in the table.

42175027-c77a2efc-7de9-11e8-955d-be97810cb03b

Sources:
* https://www.merriam-webster.com/dictionary/third-party
* https://en.wiktionary.org/wiki/third-party#English

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16489) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @erikhansen. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by erikhansen** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @erikhansen. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @erikhansen, here is your [new Magento instance](https://pr-16489.engcom.dev.magento.com).
Admin access: [https://pr-16489.engcom.dev.magento.com/admin](https://pr-16489.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Please make sure you are PR **author** or **assignee** to access the instance.

**Comment by erikhansen** [comment]
I verified that this PR changes the text in "CONTENT > Design > Configuration":

magento admin-uaiok

**Review by avoelkl — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @avoelkl, thank you for the review.
[ENGCOM-2165](https://jira.corp.magento.com/browse/ENGCOM-2165) has been created to process this Pull Request

**Comment by avoelkl** [comment]
Hi @erikhansen, thanks for your PR and fixing this.

**Comment by magento-engcom-team** [comment]
Hi @erikhansen. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.6. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
