### PR TITLE
Fix #30724 - Customer Account Edit controller action enforces Page Title to "Account Information"

### LINKED ISSUE #30724: Customer Account Edit controller action enforces Page Title to "Account Information"
### Preconditions (*)

Magento 2.3.5

### Steps to reproduce (*)

Change the page title in `view/frontend/layout/customer_account_edit.xml` file of a module.

### Expected result (*)

The page title set in the layout file is used as the browser page title.

### Actual result (*)

It is not. "Account Information" is always used as page title, whatever the setting of the layout.

This is coming from the `Magento\Customer\Controller\Account\Edit` controller action that enforces this value. There seems to be no workaround here. Except rewriting the whole action in a custom implementation.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#30724

### Manual testing scenarios (*)

Please check fixed issue for testing scenario

### Questions or comments

I don't think any tests would be applicable here

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Bartlomiejsz** [comment]
@magento run all tests

**Comment by Bartlomiejsz** [comment]
@magento Functional Tests B2B, Functional Tests CE, Integration Tests

**Comment by Bartlomiejsz** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Integration Tests

**Comment by rogyar** [comment]
@magento give me test instance

**Comment by rogyar** [comment]
For QA. I believe we don't need to cover this change with another heavy auto-test just for checking the page title. 
Thanks.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8524](https://jira.corp.magento.com/browse/ENGCOM-8524) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Change the page title in `view/frontend/layout/customer_account_edit.xml` file of a module

```xml

    <head>
        <title>Custom Account Information</title>
    </head>

```
2. Go to Storefront -> My Account -> Account Information

**Before:** :heavy_multiplication_x: The title wasn't changed



**After:** :heavy_check_mark: The title was changed

Screenshot from 2020-12-07 10-38-01

:heavy_check_mark:  The translation of the title was also checked and everything works as expected.

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Integration Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Pull request merged**
