### PR TITLE
add key for returned array for first level in rest api

### LINKED ISSUE #30676: [Issue] add key for returned array for first level in rest api
This issue is automatically created based on existing pull request: magento/magento2#30606: add key for returned array for first level in rest api

---------

### Description (*)
add key for returned array for first level in api
when you return array in rest api for example
```
/**
 * GET mobile apps link
 * @return array
 */
public function getMobileAppsLink(){
    $data['android']="value";
    $data['ios']="value2";
    return $data;
}
```
expectation : 
```
{
    "android": "value",
    "ios": "value2"
}
```
current result:
```
[
    "value",
    "value2"
]
```

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by taoufiqaitali**
### Description (*)
add key for returned array for first level in api
when you return array in rest api for example
```
/**
 * GET mobile apps link
 * @return array
 */
public function getMobileAppsLink(){
    $data['android']="value";
    $data['ios']="value2";
    return $data;
}
```
expectation : 
```
{
    "android": "value",
    "ios": "value2"
}
```
current result:
```
[
    "value",
    "value2"
]
```

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30676: add key for returned array for first level in rest api

### CODE REVIEW

**Review by swnsma — CHANGES_REQUESTED** [review]
Hi @taoufiqaitali!
Thank you for your contribution!
May I ask you to explain (better with examples) which problem your changes are solving and how they can be useful?

**Comment by taoufiqaitali** [comment]
> Hi @taoufiqaitali!
> Thank you for your contribution!
> May I ask you to explain (better with examples) which problem your changes are solving and how they can be useful?

when you return array in rest api for example
```
/**
 * GET mobile apps link
 * @return array
 */
public function getMobileAppsLink(){
    $data['android']="value";
    $data['ios']="value2";
    return $data;
}
```
expectation : 
```
{
    "android": "value",
    "ios": "value2"
}
```
current result:
```
[
    "value",
    "value2"
]
```

**Comment by swnsma** [comment]
Hi @taoufiqaitali!
Thank you for update.

I may be wrong, but as far as I understand, "array" should be used to represent a list of items.
In case if you need to have associated structure, you should create you own DTO (Data) interface and impementation.
Let's ask other oppinions.

@rogyar @sidolov @sivaschenko @VitaliyBoyko

**Comment by sidolov** [comment]
@swnsma totally agree with you, response with pre-defined structure should have interface and DTO.

**Comment by taoufiqaitali** [comment]
@swnsma @sidolov code here is not to change the structure of DTO,
magento stripe keys even if they defined in array, for first level arrays
keys should not be striped

**Comment by taoufiqaitali** [comment]
image
" If your method is returning an associative array, the keys surely have meaning. I do not understand why Magento chose to handle arrays this way. "

**Comment by sidolov** [comment]
@magento create issue

**Comment by swnsma** [comment]
Hi @taoufiqaitali,

The idea that PHP has it's own meaning for the 'array'.
You could find the definition of 'array' [here](https://en.wikipedia.org/wiki/Data_structure#Examples).

**Comment by swnsma** [comment]
Hi @taoufiqaitali,

The idea that PHP has it's own meaning for the 'array'.
You could find the definition of 'array' [here](https://en.wikipedia.org/wiki/Data_structure#Examples).

**Comment by swnsma** [comment]
Hi @taoufiqaitali,

The idea that PHP has its meaning for the 'array'.
You could find the definition of 'array' [here](https://en.wikipedia.org/wiki/Data_structure#Examples).
In PHP 'array' is something that includes both: array features and [map](https://www.mathworks.com/help/matlab/matlab_prog/overview-of-the-map-data-structure.html) features.

Your concern is mostly related to that you are looking for 'map' behavior for 'array' structure.

**Comment by swnsma** [comment]
Hi @taoufiqaitali,

The idea that PHP has its meaning for the 'array'.
You could find the definition of 'array' here.
In PHP 'array' is something that includes both: array features and map features.

Your concern is mostly related to that you are looking for 'map' behavior for 'array' structure.

If we could into your example:
```
/**
 * GET mobile apps link
 * @return array
 */
public function getMobileAppsLink(){
    $data['android']="value";
    $data['ios']="value2";
    return $data;
}
```

The correct way will be:

```
interface MobileLinkInterface
{
    public function getAndroid(): string;
    public function getIos(): string;
}

class MobileLink implements MobileLinkInterface
{
    private $androidLink;
    private $iosLink;

    public function __construct(string $androidLink, $iosLink)
    {
        $this->androidLink = $androidLink;
        $this->iosLink = $iosLink;
    }

    public function getAndroid(): string
    {
        return $this->androidLink;
    }

    public function getIos(): string
    {
        return $this->iosLink;
    }
}

*****************************

/**
 * GET mobile apps link
 * @return MobileLinkInterface
 */
public function getMobileAppsLink(){
    return $this->linkFactory->create(['androidLink' => 'value', 'iosLink' => 'value2']);
}
```

Idea of not allowing to use of 'map' in API is to separate data structure declaration and data itself.
In that case, data is declared via interfaces (via Service Contracts) and the format is static (until you have not to change the interface).
In the case of using 'map', we can not provide a service contract for the data declaration, because data structure will depend on the data itself, new keys in the map will be reflected as new fields in the structure of API response. The approach will make APIs 'dynamic' and this approach does not fit to the 'Service Contract' approach.
Again, @sidolov could correct me if I am wrong.

**Comment by sidolov** [comment]
@swnsma you are 100% right. In case of dynamic data structure, every client of the API will have to check if some particular key and data exist in the response instead of just using it because it's declared in the contract and MUST be present in response unconditionally.

**Comment by swnsma** [comment]
Hello!
I am closing the PR as there are no activity for a couple of month.
Please feel free to re-open it or continue discussion here.

**Pull request closed without merging**
