### PR TITLE
1716: Use Magento naming approach for FolderTree class

### LINKED ISSUE #1716: Use Magento naming approach for FolderTree class
`\Magento\MediaGalleryUi\Model\Directories\FolderTree::buildTree` to `\Magento\MediaGalleryUi\Model\Directories\GetFolderTree::execute`

### PR DESCRIPTION
**Pull request by joweecaquicla**
### Description (*)

This PR will implement the use of Magento naming approach for FolderTree class.
### Related Pull Requests

N/A
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/adobe-stock-integration/issues/1716

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by joweecaquicla** [comment]
@magento run all tests

**Review by sivaschenko — CHANGES_REQUESTED** [review]
@joweecaquicla can you please rename the class as well

**Comment by joweecaquicla** [comment]
@magento run all tests

**Comment by joweecaquicla** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by sivaschenko** [comment]
Changes covered by MFTF tests

**Pull request merged**
