### PR TITLE
Resolved issue if checkbox custom option is optional

### PR DESCRIPTION
**Pull request by suneet64**
Resolved issue if checkbox custom option is optional

### Description (*)

On frontend, unable to add to cart if product's custom option is checkbox and optional.

### Manual testing scenarios (*)

1. Have a Magento v2.3 clean installation.
2. Create a product with the checkbox custom option and keep that option as optional.
3. **Before:** Add to cart without selecting any option and you will get `The product's required option(s) weren't entered. Make sure the options are entered and try again.` error.
**After:** This error disappears in this fix.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @suneet64. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](https://i-19532-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19532-2-3-develop.instances.magento-community.engineering/admin](https://i-19532-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-19532.instances.magento-community.engineering).
Admin access: [https://pr-19532.instances.magento-community.engineering/admin](https://pr-19532.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by magento-engcom-team** [comment]
Hi @suneet64. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
