### PR TITLE
CE-33707: Update PHPUnit to v9.3.0

### LINKED ISSUE #33707: Update `phpunit/phpunit` composer dependency to version ^9.3 (STAGE 1)
This issue is a STAGE 1 of the magento/magento2#33596.
We need to upgrade `phpunit/phpunit` to the version ^9.3 with fixes of the codebase of the Magento tests.

### Related issue (*)
1. magento/magento2#33596 - parent issue
2. magento/magento2#33708 - STAGE 2
3. magento/magento2#33709 - STAGE 3

### PR DESCRIPTION
**Pull request by bohdan-harniuk**
### Description (*)
This PR contains merged branches with the updated PHPUnit to version 9.3.0 and updated codebase to be compatible with it for the Magento 2 CE repository.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#33707

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by bohdan-harniuk** [comment]
@magento run all tests

**Comment by fooman** [comment]
@bohdan-harniuk any chance you can amend the phpunit constraint to be `^9.3 <9.5`? see https://github.com/magento/magento2/issues/33761 for the 9.5 removal of a method affecting Magento tests.

**Comment by bohdan-harniuk** [comment]
> @bohdan-harniuk any chance you can amend the phpunit constraint to be `^9.3 <9.5`? see #33761 for the 9.5 removal of a method affecting Magento tests.

Hello, @fooman 

No, we have few tasks for updating PHPUnit to the latest version step by step. https://github.com/magento/magento2/issues/33596

Thanks, Bohdan

**Comment by andrewbess** [comment]
Hello @fooman.
Thank you for your question.
Now, we are working on fully update of the unit tests Magento according to requirements the latest version `phpunit/phpunit` (9.5).
The main task of the our working - magento/magento2#33596
The issue magento/magento2#33761 I am going to close as duplicate.
Thank you again.

**Comment by bohdan-harniuk** [comment]
@magento run Functional Tests EE

**Comment by Den4ik** [comment]
@bohdan-harniuk Could you please merge main line into PR and resolve conflict

**Pull request merged**
