### PR TITLE
Solution for Admin user is not able to login with customer group user role.

### PR DESCRIPTION
**Pull request by ghost**
### Description

Solution for Magento 2.2.5 : Admin user is not able to login with customer group user role #16501.

It's because of ACL issue. 'Customer group should be in 'Magento_Customer::customer' instead of 'Magento_Backend::stores_other_settings'.

### Fixed Issues (if relevant)

1. magento/magento2#16501: Magento 2.2.5 : Admin user is not able to login with customer group user role.

### Manual testing scenarios

1. System > Permission > User Roles.
2. Create a user role with 'customer group' permission.
3. Login with new user credential.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16503) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=16503) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: emiprotech<br/>:x: Tejas<hr/>**Tejas** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by magento-engcom-team** [comment]
Hi @emiprotech. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by dmanners** [comment]
Hi @emiprotech there are two committers to this PR could you please make sure that both have signed the CLA or make both commits come from the same github user. Once that is done I would be happy to progress this PR.

Thanks

**Comment by ghost** [comment]
Hello @dmanners ,
Thank you for information , let me close it and create again pull request.

**Comment by ghost** [comment]
Hi @dmanners ,
Actually  after update repository , files changes are applied in repository.
changes are merged by this pull request .https://github.com/magento/magento2/pull/17515

**Comment by dmanners** [comment]
Oh nice, thanks for the update @emiprotech and your time spent on this issue.

**Pull request closed without merging**
