### PR TITLE
Allow forwarding to noroute admin route

### LINKED ISSUE #35682: Better error message if admin route doesn't exist
### Preconditions and environment

Magento version: 2.4.3-p2

### Steps to reproduce

1. Go to the admin panel
2. Go to any URL that doesn't exist: `localhost:8080/admin/idontexist`
3. Error message is: `Invalid security or form key. Please refresh the page.`

### Expected result

Error message should be: `Route with ID 'idontexist' doesn't exist` or `Route with ID 'idontexist' does not have a subroute 'index/index'`

### Actual result

`Invalid security or form key. Please refresh the page.`

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by fredden**
### Description
In the adminhtml area, when a suitable route does not exist, the request is forwarded to the `noroute` action/route to show a "404 Error Page not found" message/page. However, because the action did not implement `\Magento\Framework\App\CsrfAwareActionInterface`, it failed the CSRF validation and instead the user was redirected to the dashboard with an error message saying "Invalid security or form key. Please refresh the page." This error message does not describe the problem.

This pull request allows the Forward action to pass the CSRF validation step, and show the intended page to the end user.

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/35682

### Manual testing scenarios
1. Browse to the admin and log in
1. Change the URL to an invalid path (eg, `/admin-front-name-here/example-invalid-route`)

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@sidolov, I believe we should set the p2 priority because now the forwarding in the admin looks broken.

**Comment by ihor-sviziev** [comment]
@fredden, can we cover this case with integration or functional test?

**Comment by engcom-Charlie** [comment]
Hi @fredden and @ihor-sviziev,

Thank you for your contribution!

I will work on covering automation tests for this fix.

Thank you!

**Comment by engcom-Charlie** [comment]
Currently working on some high priority task, will resume once that is done.

Thank you!

**Comment by ishakhsuvarov** [comment]
Closing this for now due to a long inactivity.

Please feel free to reopen.

**Comment by fredden** [comment]
@ishakhsuvarov please can you re-open this pull request. I don't see why this was closed. The last update posted was from @engcom-Charlie saying that they will add test coverage for this change. Do you (@ishakhsuvarov) have any information you can share to justify closing this without warning? The change is valid and has been accepted as such. The only step remaining as far as I can tell, is for Adobe to add test coverage, which @engcom-Charlie has promised to do.

**Comment by ihor-sviziev** [comment]
I just reviewed the changes, not sure if we really need to cover them somehow.
Will merge 2.4-develop branch and check if tests are passing

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Semantic Version Checker

**Review by ihor-sviziev — APPROVED** [review]

**Pull request merged**
