### PR TITLE
fix: change "My Dashboard" to "My Account", fixes #16007

### LINKED ISSUE #16007: My Dashboard used instead of My Account
### Preconditions

1. Magento 2.2.4

### Steps to reproduce

1. Go to /customer/account/
2. Check title on the right and compare it with the link text on the left

### Expected result

1. It should read "My Account"

### Actual result

1. It reads "My Dashboard"

### PR DESCRIPTION
**Pull request by DanielRuf**
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by misha-kotov** [comment]
Hi @DanielRuf, do your changes affect both of these labels? Anywhere else? 
image

**Comment by DanielRuf** [comment]
So far these should at least affect the makred ones + title.

**Comment by DanielRuf** [comment]
Should we also change "Account Dashboard" to "My Account"?

**Comment by VladimirZaets** [comment]
@DanielRuf I think, yes
@misha-kotov can you please clarify all places where we should replace?
Thanks

**Comment by misha-kotov** [comment]
@DanielRuf the marked labels above + title sounds right to me. Are you saying there another "account dashboard" somewhere?

**Comment by DanielRuf** [comment]
> @DanielRuf the marked labels above + title sounds right to me. Are you saying there another "account dashboard" somewhere?

I did not change the "Account Dashboard" on the left but should also change this.

**Comment by VladimirZaets** [comment]
Hi @DanielRuf, can you please also change "Account Dashboard" label. Thanks

**Comment by VladimirZaets** [comment]
Hi @DanielRuf, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Comment by DanielRuf** [comment]
> Please reopen and update if you wish to continue.

Done.

**Comment by VladimirZaets** [comment]
Hi @DanielRuf , thanks for the update.

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.6. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Comment by DanielRuf** [comment]
Backport failed on 2.1. Do we still need it for 2.1?

**Pull request merged**
