### PR TITLE
keeps on product in customer or visitor compare list if stock status is changing to out_of_stock (related to issues 24620 and 24617 + fix to 24582)

### PR DESCRIPTION
**Pull request by kkorushkin**
### Description
Related to issues #24620 and #24617
This fix provide changing logic of Product Compare functionality. It's alows to keeps on  product visibility that already in Compare List when it Stock Status changing to OUT_OF_STOCK
**upd:** Added fix related to issue magento/magento2#24582   
**upd:** Added filter to exclude disabled items from collection

### Manual testing scenarios (*)
1. Find the product **Chaz Kangeroo Hoodie** (SKU: MH01) from the Storefront and add to compare
2. Login to Admin
3. Find the product in the admin panel by SKU: MH01 and open it
4. Expand Configurations tab
5. Click **Edit Configurations** > **Next** > **Next**
6. Under **Quantity** enable **Apply single quantity to each SKUs** and set it to 0
7. Click **Next** > **Generate Products**
8. Save the product.
9. Copy the URL key of the product and construct the products URL:
{{base_url}} + / + {{URL_key}} + {{product_URL_suffix}}, for example http://graphql-ce.loc/chaz-kangeroo-hoodie.html
Verify that it has OUT_OF_STOCK status.
10. Navigate to {{base_url}}/catalog/product_compare/

### Actual result (*)

1.  We see in the top right that there is one item in the comparison list  
Screenshot_20190916_140835

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by josefbehr — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @josefbehr, thank you for the review.
[ENGCOM-6139](https://jira.corp.magento.com/browse/ENGCOM-6139) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
Hello @kkorushkin. Thank You for Your contribution. I'd have several questions if You don't mind. 
 First: You've written "Related to issues #24620 and #24617". Yes the PR is related to both of these issues but it fixes the first one and does not fix the second one, leaving it unchanged. Did You mean not to touch the second issue with Your PR indeed?

**Comment by kkorushkin** [comment]
> Hello @kkorushkin. Thank You for Your contribution. I'd have several questions if You don't mind.
> First: You've written "Related to issues #24620 and #24617". Yes the PR is related to both of these issues but it fixes the first one and does not fix the second one, leaving it unchanged. Did You mean not to touch the second issue with Your PR indeed?

Hi @engcom-Bravo. Thx for your attention on my PR, I DO appreciate that! I've missed last commit related to #24617 but don't missed to mention it, my bad :) Now it's there.
So at the moment my PR covers three  issues #24620, #24617 and #24582
Hope I'm not miss some :)

**Comment by engcom-Bravo** [comment]
@kkorushkin, unfortunately it seems a new problem has appeared - please take a look at this at the ticket's bottom:
resolve
So we need to resolve it before we can move further. Thank You.

**Review by josefbehr — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @josefbehr, thank you for the review.
[ENGCOM-6139](https://jira.corp.magento.com/browse/ENGCOM-6139) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
@kkorushkin, Thank You for the work done. At first I was ready to gladly state, that PR worked perfectly. And in fact it is doing very well now fixing all of those three issues. But I'm sad to say that it caused a new issue. In fact i'm not 100% sure the issue is caused by precisely Your PR, but most likely it is exactly so as I was not able to reproduce it on the develop version (that doesn't contain Your PR). So consider the following scenario.
1. Display Out of Stock Products is set to Yes.
2. Simple Product created with status In Stock.
3. On the Frontend add the product to Compare list and navigate to comparison list page.
4. In the Backend make the Product Out of Stock.
5. Return to Frontend and reload the page.

**Expected Result**
In stead of Add to Cart button there's a non-clickable Out of Stock phrase on the product block.

**Actual Result**
There's a usual clickable Add to Cart button remaining on the product block.

Would You please fix it too. Thank You.

**Review by josefbehr — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @josefbehr, thank you for the review.
[ENGCOM-6139](https://jira.corp.magento.com/browse/ENGCOM-6139) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
@kkorushkin, there has been no change in the behavior I described in my last comment. Please watch the gif below:
outofstock
Would You please take care of it.

**Comment by kkorushkin** [comment]
@engcom-Bravo Maybe i was miss something while pushing? But i've chacked all files in branch and there's all the same as on my local instance.  I'll keep on searching issue from my side.
Peek_2019-10-29 21-18

**Comment by engcom-Bravo** [comment]
Hi, @kkorushkin, sorry for delay. I pulled a code from Your [branch](https://github.com/kkorushkin/magento2/tree/24620-buggy_on_product_compare_functionality_while_product_configuration_changes), i.e.,  24620-buggy_on_product_compare_functionality_while_product_configuration_changes. Unfortunately, I have successfully reproduced the last discussed bug You were not able to reproduce. It is probably that Your not being able to reproduce it while I'm still able to do that is caused by different order of the steps we take. Consider please the following ones (preserve the order):
1. Vanilla installation.
2. A simple product created (In Stock).
3. The product added to Compare on the Frontend.
4. Comparison list page is entered (http://{store_base_url}catalog/product_compare/index/)
5. Display Out of Stock Products is set to Yes. Configuration Saved. Reindex, Cacheflush.
6. Back to the storefront. Reload Comparison list page.

**Expected Result**
In stead of Add to Cart button there's a non-clickable Out of Stock phrase on the product block.

**Actual Result**
There's a usual clickable Add to Cart button remaining on the product block.

Could You recheck it please. Thank You.

**Comment by kkorushkin** [comment]
@engcom-Bravo   I'm sorry for delay i was busy at work. I see that 24620 was close. Is that mean that current pr don't need any more?

**Comment by engcom-Bravo** [comment]
@kkorushkin, currently I don't know why that branch was closed, but no, not in the least. I mean, Your PR is quite important. I'll try to find out what happened with the branch.

**Comment by engcom-Bravo** [comment]
Would You @kkorushkin please explain what exactly You mean  under 'was close' - at least the link does seem to be valid, doesn't it?

**Comment by kkorushkin** [comment]
@engcom-Bravo well, i've seen this comment  https://github.com/magento/magento2/issues/24620#issuecomment-538473883 so i thought we've done with it.

**Comment by engcom-Lima** [comment]
Based on the [comment](https://github.com/magento/magento2/issues/24620#issuecomment-538473883) and this [comment](https://github.com/magento/magento2/issues/24582#issuecomment-581781446), we are closing this PR as this is not reproducible and expected behaviour.

**Pull request closed without merging**
