### PR TITLE
[MFTF] Sorting in media gallery

### LINKED ISSUE #1776: [MFTF] Sorting in media gallery
Test case link: https://studio.cucumber.io/projects/131313/test-plan/folders/1337102/scenarios/4699447

### Preconditions (*)
1. Admin user is logged in

### Steps
1. Open standalone Media Gallery
2. Create folder "a" in the root directory
3. Upload two different images to folder "a"
4. Create folder "b" in the root directory
5. Upload an image to folder "b"
6. Apply "Newest First" sorting
7. Verify the positions of 3 images in the grid (images should be displayed in the upload order)
8. Apply "Oldest First" sorting
9. Verify the positions of 3 images in the grid (images should be displayed in the reverse to upload order)
10. Apply "Directory: Ascending" sorting
11. Verify the positions of 3 images in the grid (images from directory "a" should be listed first)
12. Apply "Directory: Descending" sorting
13. Verify the positions of 3 images in the grid (images from directory "b" should be listed first)
14. Apply "Name: A to Z" sorting
15. Verify the positions of 3 images in the grid
16. Apply "Name: Z to A" sorting
17. Verify the positions of 3 images in the grid

### PR DESCRIPTION
**Pull request by joweecaquicla**
### Description (*)

This PR will introduce MFTF for sorting in media gallery.
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/adobe-stock-integration/issues/1776

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sivaschenko** [comment]
@joweecaquicla general approach looks good 👍

**Comment by rogyar** [comment]
Hi @joweecaquicla. Thank you for respecting the best practices upon MFTF tests development 👍

**Comment by joweecaquicla** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8402](https://jira.corp.magento.com/browse/ENGCOM-8402) has been created to process this Pull Request

**Pull request merged**
