### PR TITLE
[Backport] MAGETWO-61422 Respect Category Top Navigation Max Depth setting

### PR DESCRIPTION
**Pull request by torhoehn**
### Original Pull Request 
 https://github.com/magento/magento2/pull/12640
### Description
The setting `Stores > Configuration > Catalog > Catalog > Category Top Navigation > Maximal Depth` was actually never being used to limit the top menu maximum depth.

Now the setting will be used as a condition for the category collection when it is fetched.

### Fixed Issues
1. magento/magento2#7543: Category Top Navigation / Maximal Depth configuration not working

### Manual testing scenarios
1. Change the setting in the backend
2. Refresh the invalidated cache
3. See that the setting actually is being used

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-2454](https://jira.corp.magento.com/browse/ENGCOM-2454) has been created to process this Pull Request

**Comment by sidolov** [comment]
Hi @torhoehn , we found that changes provided by this PR broke several functional tests: 

`Magento\Catalog\Test\TestCase\Category\UpdateCategoryEntityFlatDataTest`
`Magento\Catalog\Test\TestCase\Category\UpdateInactiveCategoryEntityFlatDataTest`

Can you take a look at this tests? Looks like we need the different solution for this release line.

**Comment by torhoehn** [comment]
@sidolov I can't see any failed failed test. Can you provide some more information about what you mean?

**Comment by sidolov** [comment]
Hi @torhoehn , the functional test suite that usually ran at Travis contains few major functional tests. We run the full suite on each PR on our internal infrastructure and found test failures with the provided solution listed above. You probably can reproduce these test failures on your local environment.

**Comment by sidolov** [comment]
Hi @torhoehn , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
