### PR TITLE
Fixed #6955 Admin: While product which has images deleted. It's not deleting from Folder

### LINKED ISSUE #6955: Admin: While product which has images deleted. It's not deleting from Folder.
### Preconditions

1. I'm using Magento 2 CE Version 2.1.1
### Steps to reproduce

1.  Go to Admin -> Products -> Catalog
2.  When Product has image & if you delete from listing.
3.  It will not delete product images from Folder.
### Expected result

1.  When product is deleted, It should delete all product images from Folder as well.
### Actual result

1. Currently it's not deleting product Images.
2. Due to Image Not Deleted, there will be lots of space on server will be used.
3. This is the only case for Products, May be we have same issue of other Admin module as well where image is uploaded.
4. Need to check whole Admin where image is related while Delete.

### PR DESCRIPTION
**Pull request by amitvishvakarma**
Fixed #6955 Admin: While product which has images deleted. It's not deleting from Folder
### Preconditions

1. I'm using Magento 2 CE Version 2.1.1
### Steps to reproduce

1.  Go to Admin -> Products -> Catalog
2.  When Product has image & if you delete from listing.
3.  It will not delete product images from Folder.
### Expected result

1.  When product is deleted, It should delete all product images from Folder as well.
### Actual result

1. Currently it's not deleting product Images.
2. Due to Image Not Deleted, there will be lots of space on server will be used.
3. This is the only case for Products, May be we have same issue of other Admin module as well where image is uploaded.
4. Need to check whole Admin where image is related while Delete.

### CODE REVIEW

**Review by orlangur — CHANGES_REQUESTED** [review]
Please implement logic as a plugin for `$this->productRepository->delete($product);` instead.

Is there a smarter way to remove images maybe?

**Comment by amitvishvakarma** [comment]
> Please implement logic as a plugin for `$this->productRepository->delete($product);` instead.
> 
> Is there a smarter way to remove images maybe?

I had reverted previous changes and used event "catalog_product_delete_after_done" now so media images will be deleted once product is deleted.

**Comment by sidolov** [comment]
Hi @amitvishvakarma , please, implement logic in the plugin for productRepository as @orlangur mentioned and revert productRepository usage instead of model.

**Comment by sidolov** [comment]
@amitvishvakarma , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
