### PR TITLE
Added custom_options file upload directory to .gitignore.

### PR DESCRIPTION
**Pull request by erfanimani**
Solves accidentally committing an uploaded file by a developer!

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19871) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @erfanimani. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by VladimirZaets** [comment]
Hi @erfanimani, please, sign CLA, otherwise, we can't process your pull request

**Comment by erfanimani** [comment]
Thanks, done.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4558](https://jira.corp.magento.com/browse/ENGCOM-4558) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@erfanimani thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VasylShvorak** [comment]
**Notice:** QA not applicable

**Comment by orlangur** [comment]
@VasylShvorak, well, it is applicable in fact.

1. Create custom option with some media
0. Assure working directory is still clean from Git perspective

**Pull request merged**
