### PR TITLE
Authentication popup should be removed from Checkout page.

### LINKED ISSUE #29208: [Issue] Authentication popup should be removed from Checkout page.
This issue is automatically created based on existing pull request: magento/magento2#29183: Authentication popup should be removed from Checkout page.

---------

### Preconditions (*)

Magento is rendering \Magento\Customer\Block\Account\AuthenticationPopup block on every frontend page, while this block is used only for authorizing guest users before accessing Checkout. So it's totally useless on the Checkout page and may cause some problems for developers.

### Related Pull Requests

None

### Fixed Issues (if relevant)

1. None

### Steps to reproduce (*)

1. Disable Guest Checkout ( Go to **Admin -> Stores -> Configuration -> Sales -> Checkout** and set **Allow Guest Checkout** to **No**);
2. Go to Storefront;
3. Make sure code `<div id="authenticationPopup"...` is present in any storefront page source code;

**Actual Result:** :heavy_check_mark: `authenticationPopup` is present in any storefront page

4. Login As Customer, proceed to Checkout;
5. Make sure code `<div id="authenticationPopup"...` is absent in Checkout page source code.

**Actual Result:** :heavy_multiplication_x: Code `<div id="authenticationPopup"...`block  is present in Checkout page source code.

**Expected Result:** :heavy_check_mark: Code `<div id="authenticationPopup"...` should be absent in Checkout page source code.

Screenshot from 2020-07-20 12-06-42

Checkout functionality still works as previously (expected).

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by p-bystritsky**
### Description (*)

Magento is rendering \Magento\Customer\Block\Account\AuthenticationPopup block on every frontend page, while this block is used only for authorizing guest users before accessing Checkout. So it's totally useless on the Checkout page and may cause some problems for developers.

### Related Pull Requests

None

### Fixed Issues (if relevant)

1. None

### Manual testing scenarios (*)

1. Disable Guest Checkout.
2. Make sure code `<div id="authenticationPopup"...  ` is present in any storefront page source code.
2. As Customer, proceed to Checkout.
3. Make sure code `<div id="authenticationPopup"...  ` is absent in Checkout page source code.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29208: Authentication popup should be removed from Checkout page.

### CODE REVIEW

**Review by rogyar — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7855](https://jira.corp.magento.com/browse/ENGCOM-7855) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Disable Guest Checkout ( Go to **Admin -> Stores -> Configuration -> Sales -> Checkout** and set **Allow Guest Checkout** to **No**);
2. Go to Storefront;
3. Make sure code `<div id="authenticationPopup"...` is present in any storefront page source code;

**Actual Result:** :heavy_check_mark: `authenticationPopup` is present in any storefront page



4. Login As Customer, proceed to Checkout;
5. Make sure code `<div id="authenticationPopup"...` is absent in Checkout page source code.

**Before:** :heavy_multiplication_x: Code `<div id="authenticationPopup"...`block  is present in Checkout page source code.



**After:** :heavy_check_mark: Code <div id="authenticationPopup"... is absent in Checkout page source code.

Screenshot from 2020-07-20 12-06-42

Checkout functionality still works as previously (expected).

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
Hi @p-bystritsky. Removing block is  backward-incompatible change, we cant delivery it to 2.4, due to it I set onhold label to this PR

**Comment by ihor-sviziev** [comment]
I have one more thing - some extensions for customizing checkout use this feature for loggin in customers and refreshing the page just after. I believe we shouldn't remove this block without having any issues with that.

Instead I would prefer accepting solution something like this: https://github.com/magento/magento2/pull/27686, that will improve frontend performance.

**Comment by sidolov** [comment]
@p-bystritsky since the popup can be useful for 3d party developers and removing it is a backward-incompatible change I'm closing the PR as not relevant. Thank you for your contribution!

**Pull request closed without merging**
