### PR TITLE
magento/magento2#37895: Wishlist creating issue

### LINKED ISSUE #37895: Wishlist creating issue
### Preconditions and environment

- Magento version: 2.4.6

### Steps to reproduce

1. Login as a customer
2. Add two products to wishlist
3. Edit any one product - This will land you to PDP page.
4. Add the product to the cart. 
5. It will redirect on the wishlist page with a success and error message.

https://github.com/magento/magento2/assets/130979143/abf22add-3568-44ef-8575-dbd64ed383a3

### Expected result

Wishlist product added to cart with a success message.

### Actual result

Wishlist product added to cart but gives an error message also "The Wish List item can't load at this time. Please try again later."

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Alexander-Khohklov**
-fixed issue Wishlist product added to cart without an error message also "The Wish List item can't load at this time. Please try again later."

### Description (*)
redirect on the wishlist page with a success  affter editted product added to cart from wishlist page.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#37895

### Manual testing scenarios (*)

1. Login as a customer
2. Add two products to wishlist
3. Edit any one product - This will land you to PDP page.
4. Add the product to the cart.
5. It will redirect on the wishlist page with a success message, 
    without "The Wish List item can't load at this time. Please try again later." error message.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Alexander-Khohklov** [comment]
@magento run all tests

**Comment by shikhamis11** [comment]
@magento run all tests

**Comment by shikhamis11** [comment]
@Alexander-Khohklov Thank you for your Pull Request. Can you also cover the changes with MFTF tests?

**Comment by Alexander-Khohklov** [comment]
@magento run Integration Tests, Functional Tests EE, Functional Tests CE, Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @Alexander-Khohklov,

Thanks for the contribution!

In accordance with [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1), please cover the changes with some automated tests.

Thanks

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento give me test instance

**Comment by engcom-Charlie** [comment]
Hi @Alexander-Khohklov,

Thank you for your contribution!

In order to work on the test coverage, I I tried to reproduce this issue on magento 2.4 develop. It seems that the issue is not reproducible now.

Steps followed to reproduce the issue:
1. Login as a customer
2. Add two products to wishlist
3. Edit any one product - This will land you to PDP page.
4. Add the product to the cart.
5. Here, It is keeping the user on PDP page only with a success message and not redirecting it to wishlist page back hence ultimately we cant see any error message as mentioned in linked issue.

Can you please re-check the issue if its still reproducible or please let us know if I am missing anything here.

Thank you!

**Comment by engcom-Charlie** [comment]
Hi @Alexander-Khohklov,

Thank you for your contribution!

As per [this](https://github.com/magento/magento2/pull/38075#issuecomment-1794496384) comment, the issue is not reproducible. Please check once and confirm till then moving this PR in On Hold.

Thank you!

**Comment by engcom-Charlie** [comment]
As per [this](https://github.com/magento/magento2/pull/38075#issuecomment-1803131087) comment, the issue is not reproducible hence closing this PR now.

Please feel free to reopen in case of any updates.

**Comment by Alexander-Khohklov** [comment]
@magento magento give me test instance

**Comment by Alexander-Khohklov** [comment]
@magento give me 2.4.6-p3 test instance

**Pull request closed without merging**
