### PR TITLE
[Unit] Fix broken unit tests

### PR DESCRIPTION
**Pull request by Den4ik**
### Description (*)

This PR fixing broken unit tests:
1. `PHP Fatal error:  Class Mock_OrderPaymentExtensionInterface_175badce contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Magento\Sales\Api\Data\OrderPaymentExtensionInterface::getVaultPaymentToken) in 23dev/vendor/phpunit/phpunit-mock-objects/src/Generator.php(264) : eval()'d code on line 1`
2. `Magento\TestFramework\Dependency\PhpRuleTest::testGetDependencyInfoCaseGetUrl with data set "getUrl from same module" ('Magento\Cms\SomeClass', '$this->getUrl("cms/index/index")', array())
Magento\Framework\Exception\LocalizedException: Invalid URL path: cms/index/index`
3. `Magento\TestFramework\Dependency\PhpRuleTest::testGetDependencyInfoCaseGetUrl with data set "getUrl from another module" ('Magento\SomeModule\SomeClass', '$this->getUrl("cms/index/index")', array(array('Magento\Cms', 'hard', 'getUrl("cms/index/index"')))
Magento\Framework\Exception\LocalizedException: Invalid URL path: cms/index/index`
4. `Magento\Reports\Test\Unit\Model\ResourceModel\Product\CollectionTest::testAddViewsCount
Error: Call to a member function getDefaultAttributeSetId() on null`

### Fixed Issues (if relevant)

No issue

### Manual testing scenarios (*)

1. run `php bin/magento dev:tests:run unit`

### Questions or comments

Another one failed test:
`Magento\Framework\App\Test\Unit\ObjectManagerFactoryTest::testCreateObjectManagerFactoryCouldBeOverridden
Failed asserting that exception of type "\BadMethodCallException" is thrown.`

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by orlangur** [comment]
Hi @Den4ik, another failed test was already reported in https://github.com/magento/magento2/issues/11268

**Comment by Den4ik** [comment]
Hi @orlangur 
Thanks for the reference

**Comment by Den4ik** [comment]
@magento run all tests

**Review by orlangur — APPROVED** [review]
Thanks @Den4ik! Didn't check locally but from 9 checks this seems to be ready.

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-5438](https://jira.corp.magento.com/browse/ENGCOM-5438) has been created to process this Pull Request
:eight_spoked_asterisk: @orlangur, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
