### PR TITLE
ISSUE-5021 fixed guest checkout with custom shipping carrier with unde…

### PR DESCRIPTION
**Pull request by vovsky**
…rscores

### Description (*)
It's not possible to complete guest checkout if custom shipping carrier with underscores in carrier code is used. PR that fixes this issue for logged in users is already merged. This PR fixes the same problem for guest checkout.

### Fixed Issues (if relevant)

1. magento/magento2#5021: "Please specify a shipping method" Exception

### Manual testing scenarios (*)

1. Create custom shipping method module with underscore '_' in carrier code eg. "custom_shipping"
2. Enable custom shipping method
3. Add product to cart as a Guest
4. Go to checkout and select custom shipping method
5. Place order

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19505) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @vovsky. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — APPROVED** [review]
Mentioned PR is https://github.com/magento/magento2/pull/18689/files

**Comment by hostep** [comment]
Can somebody confirm if this will also fix https://github.com/magento/magento2/issues/13902? If yes, can somebody add this issue to the list of fixed issues? Thanks!

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-4237](https://jira.corp.magento.com/browse/ENGCOM-4237) has been created to process this Pull Request

**Pull request merged**
