### PR TITLE
[MFTF] deprecated GoToAttributeGridPageActionGroup

### LINKED ISSUE #30103: [Issue] [MFTF] deprecated GoToAttributeGridPageActionGroup
This issue is automatically created based on existing pull request: magento/magento2#30081: [MFTF] deprecated GoToAttributeGridPageActionGroup

---------
This PR deprecated `GoToAttributeGridPageActionGroup`

### PR DESCRIPTION
**Pull request by Usik2203**
This PR deprecated `GoToAttributeGridPageActionGroup`

### Resolved issues:
1. [x] resolves magento/magento2#30103: [MFTF] deprecated GoToAttributeGridPageActionGroup

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by rogyar — APPROVED** [review]

**Comment by rogyar** [comment]
The failing tests are not related to the current change

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8226](https://jira.corp.magento.com/browse/ENGCOM-8226) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento create issue

**Pull request merged**
