### PR TITLE
Fix wrong type of argument appendSummaryFieldsToCollection

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixed issue with wrong type of argument for appendSummaryFieldsToCollection
It will fix issue in `app/code/Magento/Review/Observer/CatalogProductListCollectionAppendSummaryFieldsObserver:execute()` where appendSummaryFieldsToCollection get `int`as `storeId`

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magetno run all tests

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @Usik2203. Could you take a look at the failing tests, please? 

Thank you!

**Comment by Usik2203** [comment]
Hi @rogyar .
All tests are successfully now.
Thank You  for Your recommendation.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-6964](https://jira.corp.magento.com/browse/ENGCOM-6964) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
