### PR TITLE
M2C-2205 Move LESS styling files

### PR DESCRIPTION
**Pull request by ptylek**
### Description (*)

LESS styling for Magento_Contact and Magento_Cms was moved to correct _design_ directory.

### Fixed Issues (if relevant)

1. magento/magento2#25276: Magento_Contact module MUST NOT include any design-level LESS styling

### Manual testing scenarios (*)

1. Result of `find . -type f -name "_module.less"`
```
./design/frontend/Magento/luma/Magento_CustomerBalance/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_AdvancedCheckout/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_LayeredNavigation/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Theme/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Reward/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Review/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Vault/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Wishlist/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Invitation/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Customer/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_CatalogSearch/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_GiftCard/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_GiftCardAccount/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Newsletter/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Rma/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Sales/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_GiftMessage/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_MultipleWishlist/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Downloadable/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_GiftWrapping/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_AdvancedSearch/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Msrp/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Multishipping/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_GroupedProduct/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_InstantPurchase/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Checkout/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Catalog/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_GiftRegistry/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_Bundle/web/css/source/_module.less
./design/frontend/Magento/luma/Magento_SendFriend/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Swatches/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_AdvancedCheckout/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_LayeredNavigation/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Theme/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Reward/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Braintree/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Paypal/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Review/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_CatalogEvent/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Vault/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Wishlist/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Invitation/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Customer/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_CatalogSearch/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_GiftCard/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_GiftCardAccount/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Newsletter/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Rma/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Sales/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_GiftMessage/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_MultipleWishlist/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Contact/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Downloadable/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_GiftWrapping/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Msrp/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Multishipping/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_GroupedProduct/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_SalesRule/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_ProductVideo/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Checkout/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Catalog/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_GiftRegistry/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Weee/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_Bundle/web/css/source/_module.less
./design/frontend/Magento/blank/Magento_SendFriend/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Translation/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_VersionsCms/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_ConfigurableProduct/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_CustomerBalance/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_AdvancedCheckout/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Reward/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Braintree/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Ui/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Paypal/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Review/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Signifyd/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_CatalogPermissions/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Vault/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Customer/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Marketplace/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_GiftCard/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Banner/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Integration/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Rma/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_CurrencySymbol/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_AdminNotification/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Sales/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Contact/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Downloadable/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_VisualMerchandiser/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_GiftWrapping/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Config/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Staging/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Analytics/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_ProductVideo/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Catalog/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Shipping/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_AdminAnalytics/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_GiftRegistry/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Tax/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_ReleaseNotification/web/css/source/_module.less
./design/adminhtml/Magento/backend/Magento_Backend/web/css/source/_module.less
```

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6203](https://jira.corp.magento.com/browse/ENGCOM-6203) has been created to process this Pull Request

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @ptylek , please, sign CLA, otherwise, we can't process your pull request

**Comment by ptylek** [comment]
@VladimirZaets I signed CLA

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6203](https://jira.corp.magento.com/browse/ENGCOM-6203) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @ptylek, Is this the right behavior for moving a file from the **Magento_Cms** module to the **Magento_Contact**?
screen

@ptylek Could you take a look?

Thanks!

**Comment by ptylek** [comment]
@engcom-Alfa Good catch, thanks and sorry for inconvenience. I pushed a fix.

**Comment by ptylek** [comment]
@engcom-Alfa What other updates can be done on this PR in order to move it to Review stage? Thanks in advance.

**Comment by engcom-Alfa** [comment]
@ptylek Sorry, but we need to get approval from the reviewer.

**Comment by engcom-Alfa** [comment]
@VladimirZaets Could you review the latest commit?

**Review by krzksz — APPROVED** [review]

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6203](https://jira.corp.magento.com/browse/ENGCOM-6203) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
