### PR TITLE
Change product_price_value in cart data section based on tax settings

### PR DESCRIPTION
**Pull request by NickdeK**
### Description (*)

Change the `product_price_value` data based on the tax setting. Uses the same functions as used in the template for the `product_price` data so it should always match the data shown in the minicart. The exception is when both prices should be shown (inclusive and exclusive tax), in this case a object is returned with both prices in it. `product_price_value` is not used anywhere in Magento so this shouldn't be a problem.

### Fixed Issues (if relevant)

1. magento/magento2#20310: Cart section data has wrong product_price_value

### Manual testing scenarios (*)

1. Set Magento configuration Stores > Configuration > Sales > Tax > Shopping Cart Display Settings > Display Prices to Including Tax/Excluding Tax/Both
2. Add a item to your cart
3. Check the cart data section in dev tools to see if the correct price is shown.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20316) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @NickdeK. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by josefbehr — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @josefbehr, thank you for the review.
[ENGCOM-4359](https://jira.corp.magento.com/browse/ENGCOM-4359) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@NickdeK thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request merged**
