### PR TITLE
Query params being added twice on url generation for Store::getCurrentUrl(..)

### PR DESCRIPTION
**Pull request by popoviciandrei**
### Description

This PR fixes the bug that adds the the query params twice when generating the current url for another $store instance.
The query params are being passed via $storeParsedQuery on line 1177, so calling for $this->_request->getRequestString() on line 1136 causes this qparam duplication issue.

### Manual testing scenarios
We need a mage store with 2 store views

1. Disable include store_id in the url in the admin
2. In the frontend navigate to a page like <mage_url_for_store_view_1>/somepage?qparam=qvalue
3. Switch store view from the store switcher area. 
4. The new url will be somthing like <mage_url_for_store_view_2>/somepage?qparam=value?___store=<store_view_2_id>&amp;qparam=qvalue.
After the current PR fix is applied when switching sites we don't have the previous qparams twice.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by miguelbalparda** [comment]
I restarted the failing tests just in case, but it seems the unit testings were failing.

**Comment by miguelbalparda** [comment]
No luck this time, would you mind checking the tests @popoviciandrei?

**Comment by popoviciandrei** [comment]
hi @miguelbalparda I'll have a look at the tests maybe they need to be updated too..

**Comment by miguelbalparda** [comment]
@okorshenko can you chime in here?

**Comment by ishakhsuvarov** [comment]
@popoviciandrei @miguelbalparda I've fixed unit tests. Proceeding with the testing and merge now.

**Comment by popoviciandrei** [comment]
Thank you @ishakhsuvarov for doing this.

**Comment by vherasymenko** [comment]
@popoviciandrei  Hi. I Tried reproduce your issue and it was without success.

Steps which were executed:

- Magento url for default storeview (`http://magentossl.vg`)
- Magento url for second storeview (`http://magentossl2.vg`)

1. Install clean Magento from develop `branch`
2. Create second storeview
3. Configure second store view on other domain
4. `Stores > Configuration > General > Web > Url Options > Add Store Code to Urls set to "No"`
5. Go to frontend side to address `http://magentossl.vg?qparam=qvalue`
6.Change store view using store switcher
 
**Actual Result:** Current url (`http://magentossl2.vg/?___store=store2&qparam=qvalue`) without some duplicated values ( It`s correct behavior )

Maybe I forgot some steps for correct reproducing this issue. Could you try reproduce it on clean Magento installation from develop branch, or add more steps if some were missed.

**Comment by popoviciandrei** [comment]
hi @K7Triton thank you for this.
 Our test environment has the following setup inside magento-vars.php that is set as "auto_prepend_file" by Magento Cloud.
// Start of the magento-vars.php
$pathInfo = explode('/', ltrim($_SERVER['REQUEST_URI'], '/'), 2);
if (in_array($pathInfo[0], ['fr', 'en'])) {
    $_SERVER['REQUEST_URI'] = '/' . (array_key_exists(1,$pathInfo) ? $pathInfo[1] : '');
}
if (isHttpHost("b2b.com")) {
    switch ($pathInfo[0]) {
        case "en":
            $_SERVER["MAGE_RUN_CODE"] = "enb2b";
            $_SERVER["MAGE_RUN_TYPE"] = "store";
            break;
        case "fr":
            $_SERVER["MAGE_RUN_CODE"] = "frb2b";
            $_SERVER["MAGE_RUN_TYPE"] = "store";
            break;
        default:
            $_SERVER["MAGE_RUN_CODE"] = "b2b";
            $_SERVER["MAGE_RUN_TYPE"] = "website"; 
     }
}
if (isHttpHost("b2c.com")) {
    switch ($pathInfo[0]) {
        case "en":
            $_SERVER["MAGE_RUN_CODE"] = "en";
            $_SERVER["MAGE_RUN_TYPE"] = "store";
            break;
        case "fr":
            $_SERVER["MAGE_RUN_CODE"] = "fr";
            $_SERVER["MAGE_RUN_TYPE"] = "store";
            break;
        default:
            $_SERVER["MAGE_RUN_CODE"] = "base";
            $_SERVER["MAGE_RUN_TYPE"] = "website";
    }
}
// End of the file magento-vars.php

I am pretty sure this setup can be done from an Nginx Level, but this is the hint we got from the MCloud support team. So we came with this solution to set the store code from the magento-vars.php file.

We have a 2 websites: 
- b2c with store views: fr, en
- b2b with store view: frb2b, enb2b

But because in magento the store view ids has to be the unique and the client want the nice urls ( b2b.com/fr, b2b.com/en, b2c.com/fr, b2c.com/en ) we can't use the "use store_view in the url" magento setting.



Then in the admin we set the base_urls & base_link_urls like:
- For store_view "fr" : b2c.com/fr/
- For store_view "en": b2c.com/en/
- For store_view "frb2b": b2b.com/fr/
- For store_view "enb2b": b2b.com/en/
- Plus also the setting: "Auto-redirect to Base-Url" was set to "No".

Please confirm if you can set it up like this.

**Comment by vherasymenko** [comment]
@popoviciandrei Hi. I have few question for you:
- Which version of magento you use on MagentoCloud ??
- Could you reproduce your issue on clean Magento (develop or 2.1) branches using Nginx or Appache configuration ?

**Comment by popoviciandrei** [comment]
@K7Triton I tested on a 2.1.7 EE.

I couldn't set it up via nginx as I couldn't find the right syntax to implement the scenario that i was able to do in magento-vars.php file.

**Comment by ishakhsuvarov** [comment]
@popoviciandrei Unfortunately we still can not reproduce the initial case you described. Please provide more information.
Is only cloud version affected? We tried to reproduce it with clean git installations in local environment. If this issue related only to Cloud maybe support may be helpful on this subject?

**Comment by popoviciandrei** [comment]
hi @ishakhsuvarov I think I need to retest this on a CE only rather than Cloud.

You can decline or put this PR on hold, until I can retest this again. But also quite busy so hard to resume this at the moment.

**Comment by ishakhsuvarov** [comment]
@popoviciandrei Then I am going to close it for now. Please reopen or leave a comment if you get any additional information regarding steps to reproduce and we will continue work on it.
Thank you for collaboration.

**Pull request closed without merging**
