### PR TITLE
Fix broken commit in #15040 that accidentally reverted previous changes.

### PR DESCRIPTION
**Pull request by gwharton**
### Description
Issue #15009/PR #15020 fixed issues with the gallery template.
PR#15040 accidentally reverted the fixes.
This PR reapplies them

### Fixed Issues (if relevant)
1. magento/magento2#16580: Product gallery caption issue

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by gwharton** [comment]
I have checked and this was only broken in 2.2-develop. The original fix that was reverted is still applied to 2.1-develop and 2.3-develop correctly so no backporting/forwardporting is required.

**Comment by gwharton** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @gwharton, here is your [new Magento instance](https://pr-16594.engcom.dev.magento.com).
Admin access: [https://pr-16594.engcom.dev.magento.com/admin](https://pr-16594.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Please make sure you are PR **author** or **assignee** to access the instance.

**Comment by gwharton** [comment]
I can confirm that I have checked the fix in the test instance. The image captions are not displayed under the image by default.

**Review by Karlasa — APPROVED** [review]
It was wrong before because not defining options != false because fotorama fallback settings are not all "false" by default. Works well now, nice job!

**Comment by miguelbalparda** [comment]
Right now we have 3 different solutions for this issue #16594 #15546 #16941. It seems we will be moving forward with #16594 but we'd like to have some more input if possible.

**Comment by Karlasa** [comment]
@miguelbalparda I think this PR can be merged to fix the main issue and after that move forward with other improvements if needed

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-2555](https://jira.corp.magento.com/browse/ENGCOM-2555) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @gwharton. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Comment by gwharton** [comment]
Porting to 2.1 and 2.3 is not required. The fix has already been applied to both branches.

**Comment by hostep** [comment]
@magento-engcom-team : you say this PR will be part of Magento 2.2.7, but the PR is listed in the Magento 2.2.6 milestone: https://github.com/magento/magento2/milestone/20, so which one is the correct one?
Please try to stay consistent so people know what they can expect :)

Thanks!

**Comment by tmotyl** [comment]
For some reason this commit is not visible in the file in the 2.2-develop branch.
https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Catalog/view/frontend/templates/product/view/gallery.phtml

**Comment by gwharton** [comment]
Well, i have no idea why the changes have gone! I will create another pull request to fix this again.

**Comment by tmotyl** [comment]
thanks

**Pull request merged**
