### PR TITLE
Cleaned up duplicate variable assignments in the same line

### PR DESCRIPTION
**Pull request by bgorski**
### Description (*)
This is a simple cleanup of two assignments to the same variable occurring in the same line.
Created by using the following regex:
 (\$.*) \= \1 = (with space before to exclude things like self::$loader = $loader = new \Composer\Autoload\ClassLoader(); and with space after to make sure it's an assignment and not anything else like ===)
And replacing with:
 $1 = (also with space before and after to keep the formatting right)

### Related Pull Requests
-

### Fixed Issues (if relevant)
-

### Manual testing scenarios (*)
none required

### Questions or comments
-

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by aleron75** [comment]
Hello @bgorski thank you for your contribution!

Can you please take a look at the [failed static test report](https://github.com/magento/magento2/pull/28085/checks?check_run_id=640597583) to check what's wrong with it?  

I'm pretty sure the test doesn't fail because of your changes but because of legacy code. If you can apply suggested cleanup it would be very useful.

Thank you!
Alessandro

**Comment by bgorski** [comment]
@aleron75 thank you for assigning yourself to this PR. All those issues were indeed legacy code that just happened to be in the same files I edited. 
I fixed most of them, but decided to leave three of them intact:
- two instances of "Avoid function calls in a FOR loop test part" warnings
- one instance of "The use of function md5() is forbidden" error
Those would require some refactoring that I haven't exactly had in mind when creating this simple contribution - and as you suspected they're not new things generated by code changes from this PR. Do you think leaving them would be an issue?

**Comment by aleron75** [comment]
> Do you think leaving them would be an issue?

it is indeed because if tests don't pass the PR can't be merged.

Do you think you can fix those failing tests?

Best.
Alessandro

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @bgorski. Thanks for collaboration. Can you please fix failed tests?

**Comment by engcom-Charlie** [comment]
Hi @bgorski, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Comment by bgorski** [comment]
I'm not sure how to reopen this. I'll create a new PR.

**Pull request closed without merging**
