### PR TITLE
Fix for url_rewrite on page delete via api

### PR DESCRIPTION
**Pull request by avdb**
Problem: when deleting a cms page via api the url_rewrites aren't deleted

Steps to reproduce:
- add cms page via api
- delete cms page via api
- add new cms page with same identifier via api
- ERROR: Could not save the page, URL key already exists

Solution: moved di.xml from etc/adminhtml to etc/ folder in CmsUrlRewrite module
Event trigger to delete url rewrites is located in di.xml

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=10568) <br/>All committers have signed the CLA.

**Comment by ishakhsuvarov** [comment]
@avdb Would be really nice to cover this change with an api-functional test. Do you need any help with that?

**Comment by ishakhsuvarov** [comment]
@avdb Added test on our side.

**Comment by Ctucker9233** [comment]
@magento-team Will this be backported to 2.2?

**Pull request merged**
