### PR TITLE
Replaced deprecated method addError with addErrorMessage

### PR DESCRIPTION
**Pull request by VinothKumar361**
### Description (*)

This Pull request replaces the deprecated  addError method with addErrorMessage method
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by VinothKumar361** [comment]
@magento run all tests

**Comment by edenduong** [comment]
@magento run all tests

**Comment by edenduong** [comment]
Hi @VinothKumar361 : Could you please check the static tests? Thank you !

**Review by edenduong — CHANGES_REQUESTED** [review]
Thank you for your contribution. Please fix the static test.

**Comment by VinothKumar361** [comment]
> Thank you for your contribution. Please fix the static test.

**Comment by VinothKumar361** [comment]
@magento run all tests

**Review by edenduong — CHANGES_REQUESTED** [review]
Hi @VinothKumar361 : Please resolve the conflict code and also the static test. Thanks!

**Comment by engcom-Echo** [comment]
@magento run Static Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by edenduong — DISMISSED** [review]
Thank you !

**Comment by magento-engcom-team** [comment]
Hi @edenduong, thank you for the review.
[ENGCOM-7951](https://jira.corp.magento.com/browse/ENGCOM-7951) has been created to process this Pull Request
:eight_spoked_asterisk: @edenduong, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @VinothKumar361 . During testing, we faced the issue.

**Manual testing scenario:**

1. Create customer and subscribe to newsletters;
2. Go to Admin -> Marketing -> Newsletter Subscribers;
3. Select the subscriber's checkbox;
4. Select **Unsubscribe** from the dropdown mass action menu;
5. Click on **Submit** button;

**Actual Result:** :heavy_multiplication_x: 404 error message received

Peek 2020-08-11 11-24

@VinothKumar361 Could you take a look?

Thanks!

**Comment by engcom-Echo** [comment]
Hi @engcom-Alfa, the bug fixed. Thank you.

**Comment by engcom-Echo** [comment]
Hi @edenduong. Please approve again to deliver the PR for testing. Thanks.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-7951](https://jira.corp.magento.com/browse/ENGCOM-7951) has been created to process this Pull Request

**Pull request merged**
