### PR TITLE
Allowed php 8 compatible phpstan version

### LINKED ISSUE #31176: Update phpstan/phpstan dependency to PHP 8 compatible version
### Description (*)
Update phpstan/phpstan dependency version from ">=0.12.3 <=0.12.23" to ">=0.12.3 <=0.12.54"
Ensure composer install runs on PHP 7.4 and 8.0

### PR DESCRIPTION
**Pull request by sivaschenko**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/31176

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run Sample Data Tests CE,Sample Data Tests EE,Sample Data Tests B2B

**Comment by sivaschenko** [comment]
@magento run Database Compare,Static Tests

**Comment by hostep** [comment]
This conflicts with: https://github.com/magento/magento2/pull/30581

@sivaschenko: why the upper bound? Please allow all 0.12.* versions?

**Comment by ihor-sviziev** [comment]
Hi @sivaschenko,
This is duplicate of #30581
That was approved in October, but still didn’t get any attention. Can we close this one and move forward original one?
Also not clear why can't we use ^0.12.3 as suggested in original PR?

**Comment by sivaschenko** [comment]
@hostep @ihor-sviziev thanks for the link to the duplicate PR.

I've basically used this PR to test the PHP 8 project boards and builds on php8-develop branch that I have been preparing.

Closing it now.

We are going to provide more information on PHP 8 compatibility for Magento soon. Meanwhile can you please mark the PRs/issues related to PHP 8 with "Project: PHP8" label, also all related PRs should be targeting php8-develop branch (it's based on 2.4-develop).

The boards for PHP 8 Compatibility project:
Backlog: https://github.com/magento/magento2/projects/31
PRs: https://github.com/magento/magento2/projects/32

**Pull request closed without merging**
