### PR TITLE
[MFTF] use action group to save categories

### LINKED ISSUE #29388: [Issue] [MFTF] use action group to save categories
This issue is automatically created based on existing pull request: magento/magento2#28993: [MFTF] use action group to save categories

---------
This PR use `AdminSaveCategoryActionGroup` to save category instead
`<click selector="{{AdminCategoryMainActionsSection.SaveButton}}" stepKey="saveSubCategory"/>`
`<waitForPageLoad stepKey="waitForSecondCategoryToSave"/>`

### PR DESCRIPTION
**Pull request by Usik2203**
This PR use `AdminSaveCategoryActionGroup` to save category instead
`<click selector="{{AdminCategoryMainActionsSection.SaveButton}}" stepKey="saveSubCategory"/>`
`<waitForPageLoad stepKey="waitForSecondCategoryToSave"/>`

### Resolved issues:
1. [x] resolves magento/magento2#29388: [MFTF] use action group to save categories

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by rogyar** [comment]
@magento run Functional Tests B2B

**Review by rogyar — CHANGES_REQUESTED** [review]
@Usik2203 please, take a look at the failing functional tests

**Comment by Usik2203** [comment]
@magento run Functional Tests B2B

**Comment by Usik2203** [comment]
Hi @rogyar 
I see that failed test is not related with my changes 
Thanks!

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by rogyar** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Integration Tests

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7928](https://jira.corp.magento.com/browse/ENGCOM-7928) has been created to process this Pull Request
:eight_spoked_asterisk: @rogyar, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Charlie** [comment]
@magento create issue

**Pull request merged**
