### PR TITLE
Resolve error when call getRssUrl() method

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

Let check: `public function getRssUrl($wishlistId = null)`

image

When the customer is not login, call getRssUrl() will return the error:

image

Solution: Declare `$params = [];`

### Manual testing scenarios (*)

1. Create Controller
2.

```
        $url = $this->_objectManager->create('Magento\Wishlist\Helper\Data')->getRssUrl();
        var_dump($url);
        die;
```

Expected Result: No error, print the Url

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by kalpmehta — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, thank you for the review.
[ENGCOM-5694](https://jira.corp.magento.com/browse/ENGCOM-5694) has been created to process this Pull Request
:eight_spoked_asterisk: @kalpmehta, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Nice catch, @edenduong !
Could you please cover the corresponding case with a unit test in `\Magento\Wishlist\Test\Unit\Helper\DataTest`?
I would recommend delivering other fixes similar to the current one along with automated tests, in order to proof the issue and make sure it's properly fixed.
In this case, no need to provide a long PR description with detailed steps to reproduce etc. Also, such quality PR will be rather considered as "Improvement" than just "clean up".

Thank you!

**Comment by dmytro-ch** [comment]
@edenduong could you please review the unit and static tests failures?

**Comment by edenduong** [comment]
> @edenduong could you please review the unit and static tests failures?

Hi @dmytro-ch : I just changed the source to cover Unit Test and also fix the static test. Please check it again.

Thanks.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5694](https://jira.corp.magento.com/browse/ENGCOM-5694) has been created to process this Pull Request

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5694](https://jira.corp.magento.com/browse/ENGCOM-5694) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

**Before:**
before

**After:**
after

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
