### PR TITLE
Improve array semicolon and misspelled

### PR DESCRIPTION
**Pull request by williankeller**
### Description
Just improving code, removing semicolon from array brackets and fix small misspelled.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=17820) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @williankeller. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by osrecio — APPROVED** [review]
Thanks for your contribution @williankeller . We will process your PR ASAP

**Comment by magento-engcom-team** [comment]
Hi @osrecio, thank you for the review.
[ENGCOM-2890](https://jira.corp.magento.com/browse/ENGCOM-2890) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @williankeller. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Pull request merged**
