### PR TITLE
Fix wrong typo function name

### LINKED ISSUE #29987: [Issue] Fix wrong typo function name
This issue is automatically created based on existing pull request: magento/magento2#29986: Fix wrong typo function name

Correct function name caused by typo

### Preconditions (*)
1. Magento 2.4

### Steps to reproduce (*)
Correct function name caused by typo

### Expected result (*)
Correct function name 

### Actual result (*)
Fix wrong typo function name

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Correct function name caused by typo

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. From admin dashboard
2. Go to catalog > Category
3. Go to workarounds new category field
4. All function should work without break

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29987: Fix wrong typo function name

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by parkerthegeniuschild — APPROVED** [review]

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8181](https://jira.corp.magento.com/browse/ENGCOM-8181) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked create and save new category, edit existing category. All values from category form are saved, no errors occur

**Comment by ihor-sviziev** [comment]
@engcom-Delta seems like you missed to move this PR further in QA process?

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Comment by gabrieldagama** [comment]
@magento run all tests

**Pull request merged**
