### PR TITLE
#32910 fix rewriting category product URL for the one store group

### LINKED ISSUE #32910: Adding category to product in store view scope does not generate all url rewrites
### Preconditions (*)

1. Reproduced at least on Magento 2.3.1, 2.3.6-p1, 2.4.2

### Steps to reproduce (*)

1. Create 2 store views
2. Create category with anchor enabled (and in 2.4.2 make sure category/product url generation is enabled)
3. Add new product without category
4. Open product edit in storeview scope
5. Add product to category and save

### Expected result (*)

1. Category product urlrewrites are generated to both storeviews
image

### Actual result (*)

1. Urlrewrites are generated only to the storeview where changes where made
image

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by korovitskyi**
### Description (*)

Fixed adding category to product in store view scope to generate all url rewrites

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32910

### Manual testing scenarios (*)

1. Create 2 store views
2. Create category with anchor enabled (and in 2.4.2 make sure category/product url generation is enabled)
3. Add new product without category
4. Open product edit in storeview scope
5. Add product to category and save

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by korovitskyi** [comment]
@magento run all tests

**Review by andrewbess — CHANGES_REQUESTED** [review]
Hello @korovitskyi 
Thank you for your contribution.
Could you please fix failed tests (you can ask me about it)?
Thank you in advance.

**Comment by korovitskyi** [comment]
@magento run all tests

**Comment by korovitskyi** [comment]
@magento run all tests

**Comment by korovitskyi** [comment]
@magento run all tests

**Comment by korovitskyi** [comment]
@magento run all tests

**Comment by korovitskyi** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE,WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by engcom-Charlie** [comment]
Hi @korovitskyi,

Thank you for your contribution!

By looking at your steps, it seems that when assigning a category to product from edit, you have selected the category from other category which is not the Root Category for that store. Can you please confirm on this.

The category product url will gets generated for the selected scope against the category, if, that category is or falls under the category which we select as a Root category in store/scope.  So wanted to confirm that, are you selecting the category which does not belongs to the scope. It might be the reason you are not getting the second entry.

I have tried to reproduce this issue on my local by following below steps

1. Created New website(germany), new store, and new store view. While creating new Store, I have selected Default Category as my Root category.

image


3. I have created a new category(Germany). 

4. Created new product(test product) Note: Currently I have  selected “Main website and Germany” under “Products in Websites” section.  and saved it. As we have assigned 2 websites to this product, Here we got 2 entries for each store id
image

5. Open the product in Edit mode, changed the scope to new scope i.e. Germany store view and selected one category from Default Category(gear). By doing this, the category url entry gets created for the scope for which its gets selected. So here we can see 2 entries for new store id-8, and 1 for default store-1
image

So as per the above steps the issue is not reproducible for me.

As I have mentioned above, can you please check and reconfirm once on your steps.

Thank you!

**Comment by engcom-Charlie** [comment]
As mentioned in above [comment](https://github.com/magento/magento2/pull/35053#issuecomment-1077707645) the issue is not reproducible for me. 

Since the issue is not reproducible and didn't got any reply on other steps to reproduce if any, closing this PR now.

Please reopen and update if you wish to continue.

Thank you for your contribution!

**Comment by hostep** [comment]
@engcom-Charlie: please try again but use 2 storeviews only and not 2 websites + 2 stores + 2 storeviews.

The expectation is that there will be 2 url rewrites generated because the category is scoped on "global" level, so when you save a category on a production it should assign the product to the category on global level (meaning in this specific case the 2 storeviews) and it's expected that all storeviews get an url rewrite generated.

----

But you test case is a good one to test as well after applying the changes from this PR, to make sure if you work with two different websites and root categories that only the necessary url rewrites get generated, so test your scenario with this PR applied and see if only the expected url rewrites get generated and not too many of them.

Thanks!

**Comment by engcom-Charlie** [comment]
@hostep Thank you for your reply!

I will check the issue as per the above mentioned points.

**Comment by engcom-Charlie** [comment]
Hi @hostep,

As per your recent comment, I have tried to reproduce the issue as below.

1. Created only new store view (storeview2) on 2.4 develop, so ultimately we have
i.  Main Website, Main Website Store, Default Store View
ii.  Main Website, Main Website Store, storeview2
image

2. Created new category “test” under Default Category of Magento 
image

3. Created new product "testnew". Here 2 urls got created, 1 for store_id 1 and for store_id 2
5. Edited the product, changed the scope to “[storeview2] and assigned newly created category “test”.  By doing this, we can see 2 entries for new store id-2, and 1 for default store-1 
6.  I have also assigned the other existing category "Gear" to this newly created product. Here also we can see new 2 entries for new store id-2, and 1 for default store-1 
image

So as per the above steps the issue is still not reproducible for me.

Can you please let me know if I am missing anything in order to reproduce this issue.

Thank you in advance!

**Comment by hostep** [comment]
@engcom-Charlie: thanks for re-testing.

And actually you succeeded in reproducing the bug. You are missing the following 2 records in your `url_rewrite` table:
- `gear/testnew.html` for store_id 1
- `test/testnew.html` for store_id 1

They only got generated for store_id 2, but are missing for store_id 1, that's what the bug report in #32910 is about 🙂

**Comment by engcom-Charlie** [comment]
Hi @hostep,

Thank you for this clarity.

Will check the PR changes accordingly now and look into the test failures.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @hostep,

As per your recent [comment](https://github.com/magento/magento2/pull/35053#issuecomment-1108685058), I have tried the scenario on PR branch.

1. Created only new store view (storeview2), so ultimately we have
i.  Main Website, Main Website Store, Default Store View
ii.  Main Website, Main Website Store, storeview2
2. Created new category “test” under Default Category of Magento 
3. Created new product testnew. Here 2 urls got created, 1 for store_id 1 and for store_id 2
image
- testnew.html for store_id 2
- testnew.html for store_id 1

4. Edited the product, changed the scope to “storeview2” and assigned newly created category “test”.  By doing this, we can see 2 entries for new store id-2, and 1 for default store-1 as below.
image

- test/testnew.html for store_id 1
- test/testnew.html for store_id 2
- testnew.html for store_id 2

Also checking other scenarios.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Looking into some high priority task. Will resume work on this PR once finished with it.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE, Integration Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by engcom-Charlie** [comment]
Hi @korovitskyi & @andrewbess,

Thank you for your contribution!

The build is failing for few of below functional test cases.

1. StoreFrontRecentlyViewedAtStoreViewLevelTest.xml
2. StoreFrontRecentlyViewedAtStoreLevelTest.xml
3. StorefrontPurchaseProductCustomOptionsDifferentStoreViewsTest.xml

It seems that "aside.confirm .modal-footer button.action-accept" selector is not working, showing timeout errorand hence the click event in confirmation model is not getting completed. 

I have gone through above test cases, and tried to execute the same functional flow manually. Its working fine. The confirmation modal is absolutely clickable in the functional flow.

Looking into other failures now.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by engcom-Charlie** [comment]
Gone through all remaining failed test cases, errors which are getting displayed in allure report, till that point the functional flow is working fine when we test it manually.

It seems that those are not failing because of this PR changes. Hence moving it further.

Thank you!

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Lima** [comment]
@magento run Adobe CLA Signed?

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
1. Install the fresh Magento 2.4-develop instance with sample data.
2. Product should be created.

**Manual testing scenario:**
1. Create 2 store views.
2. Create category with anchor enabled.
3. Add new product without category.
4. Open product edit in store views scope
5. Add product to category and save it.
6. Check in database other store id is getting displayed.

**Before:** :heavy_multiplication_x: Url rewrites are generated only to the store-view where changes where made
Screenshot from 2022-06-20 19-13-49


**After:** :heavy_check_mark: Category product url rewrites are generated to both store-views
after_pr_changes_32910


Created 3 store views and add product in the scope and validated url write is correctly added up in all the store views.

**Comment by hostep** [comment]
Thanks @engcom-Lima!

I think we might also need to test a scenario with 2 different root categories, that are assigned to 2 different stores that have more than 1 storeview each.

And see if the results of that test make sense.

Idea for this was sparked by [this](https://github.com/magento/magento2/pull/35053#issuecomment-1077707645) and [this other](https://github.com/magento/magento2/pull/35053#issuecomment-1103905337) comment

**Comment by engcom-Lima** [comment]
Hi @hostep 

I have tested this [scenario](https://github.com/magento/magento2/pull/35053#issuecomment-1077707645) where I have created two websites,two stores,two store views.
Result found is url rewrite happened only to the product associated website and store.
Below is the screenshot for your reference:
Screenshot from 2022-06-22 16-01-49

According to your [comment](https://github.com/magento/magento2/pull/35053#issuecomment-1103905337) that's what you have expected.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
It seems that the functional build failures are not related to this PR changes. Added observation [here](https://github.com/magento/magento2/pull/35053#issuecomment-1157657311).

As mentioned [here](https://github.com/magento/magento2/pull/35053#issuecomment-1158788246), moving this PR for Merge.

Thank you!

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by hostep** [comment]
@engcom-Alfa, @engcom-Charlie, @engcom-Lima, @ishakhsuvarov: I'm not exactly sure why the label `Issue: needs update` is still attached to this PR, as far as I know, this was tested, accepted and can be moved forwards?

**Comment by engcom-Charlie** [comment]
Hi @hostep,

I have added comment in [issue](https://github.com/magento/magento2/issues/32910#issuecomment-1253240278), and removed the needs update label got added there. 

As per the process this PR will move further.

Thank you!

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Review by ishakhsuvarov — APPROVED** [review]
Approving per comments above.

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
Looking like bot had moved from Merge in progress to Ready for testing column. As per above comments moving this PR again to Merge in progress.

**Comment by ishakhsuvarov** [comment]
Moving to "extended testing" to resolve conflicts and make sure tests are passing.

**Comment by hostep** [comment]
@engcom-Echo, @ishakhsuvarov: this was incorrectly closed. The issue does exist, I just tested it *again* (for the so many'th time) using commit 3e5be99a940 and it still reproduces, once again:

1. Setup clean Magento
2. Setup 2 storeviews (only 1 website, only 1 store)
3. Enable Catalog > Catalog > Search Engine Optimization > Generate "category/product" URL Rewrites
4. Create a category without any products
5. Create a product and do **not** assign it to a category
6. Open the previously created product in the backoffice and switch to one of the two storeviews
7. Now assign a category and save the product
8. Investigate the `url_rewrite` database table and notice that only one url rewrite got generated, it should have generated two of the
Screenshot 2023-01-02 at 14 56 46
m

Please re-open, test again, with and without the changes of this PR and report back if the PR fixes this problem or not...

**Comment by engcom-Echo** [comment]
@hostep Thank you for the details steps.
Issue is reproducible with steps mention in [comment](https://github.com/magento/magento2/pull/35053#issuecomment-1368968870). Hence reopening the PR.

@hostep @korovitskyi @andrewbess Thanks for the collaboration & contribution!

:heavy_check_mark: QA Passed
Fixed adding category to product in store view scope to generate all url rewrites

**Manual Scenario Steps**

1.  Setup clean Magento
2. Setup 2 storeviews (only 1 website, only 1 store)
3. Enable Catalog > Catalog > Search Engine Optimization > Generate "category/product" URL Rewrites
4. Create a category without any products
5. Create a product and do not assign it to a category
6. Open the previously created product in the backoffice and switch to one of the two storeviews
7. Now assign a category and save the product
8. Investigate the url_rewrite database table and notice that only one url rewrite got generated, it should have generated two of them

Before PR
image

After PR
 url rewrite are generated for both store
image

Hence Moving it to `merge in progress`.

**Comment by engcom-Echo** [comment]
Moving it to Extended Testing for build failure analysis.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Unit Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by hostep** [comment]
@engcom-Echo: the changes you did to `dev/tests/integration/testsuite/Magento/Quote/Model/ShippingMethodManagementTest.php` don't seem to have anything to do with generating url rewrites. Why did you change that file in scope of this PR? Shouldn't it go into it's own PR?

**Comment by engcom-Echo** [comment]
> 

@hostep there is test failure i have only rearrange the test so that previous test do not cause any failure in next test.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by hostep** [comment]
> there is test failure although it is not related to PR but to process PR we need to fix such failures.In this case we have only rearrange the test so that previous test do not cause any failure in next test.

So this will need to be fixed in every single new PR here on github?? Because this PR here will probably take a few days until merged?

**Comment by engcom-Echo** [comment]
> > there is test failure although it is not related to PR but to process PR we need to fix such failures.In this case we have only rearrange the test so that previous test do not cause any failure in next test.
> 
> So this will need to be fixed in every single new PR here on github?? Because this PR here will probably take a few days until merged?

Yes this is the process. If there are any test failure on PR we need to fix those failure before merging. Or get an approval for tests failures if required to merge such PR.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Functional Tests CE Failures are different on last two run and an issue with the currency converter server outage.
Run1 
image

Run2
image

Also Functional Test B2B and EE are related to issue with the currency converter server outage.

Hence Moving to `Merge In Progress`

**Pull request merged**
