### PR TITLE
[Backport] Minimum Qty Allowed in Shopping Cart not working on related product

### PR DESCRIPTION
**Pull request by mageprince**
### Original Pull Request 
 https://github.com/magento/magento2/pull/19566

### Description (*)

Solve **Minimum Qty Allowed in Shopping Cart** not working on related products

### Manual testing scenarios (*)

1. Let's take two simple products **Product A** and **Product B**
2. Set Minimum Qty Allowed in Shopping Cart = 10 in **Product A** from
Advanced Inventor->Minimum Qty Allowed in Shopping Cart
3. Assign **Product A** as a related product in **Product B**
3. Open PDP page of **Product B**
4. Check Product A checkbox from Related Products block on PDP
5. Add to cart **Product B** 

### Expected result (*)

Add to cart **Product A** with Qty = 10

### Actual result (*)

1. Add only 1 qty of Product A to the cart
2. Showing error "We don't have as many of some products as you want."

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mageprince. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-21317.instances.magento-community.engineering).
Admin access: [https://pr-21317.instances.magento-community.engineering/admin](https://pr-21317.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4323](https://jira.corp.magento.com/browse/ENGCOM-4323) has been created to process this Pull Request

**Pull request merged**
