### PR TITLE
32848: Upgraded script.aculo.us to the latest version 1.9.0

### PR DESCRIPTION
**Pull request by anzin**
### Description (*)

I've upgraded version script.aculo.us from 1.8.2 to 1.9.0.

Deleting a library is not possible due to its use in the following libraries:

1. lib / web / prototype / prototype.js
2. lib / web / prototype / validation.js
3. lib / web / prototype / window.js
4. lib / web / extjs / ext-tree.js

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32848

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by anzin** [comment]
@magento run all tests

**Comment by anzin** [comment]
@magento run Functional Tests B2B

**Comment by andrewbess** [comment]
@magento run Functional Tests B2B

**Comment by anzin** [comment]
@magento run Functional Tests B2B

**Review by eduard13 — APPROVED** [review]

**Review by Den4ik — APPROVED** [review]

**Review by andrewbess — APPROVED** [review]
Hello @anzin 
Thank you for your contribution.
The changes are approved.

**Pull request merged**
