### PR TITLE
Update AbstractCarrierInterface::collectRates return signature

### LINKED ISSUE #28514: AbstractCarrierInterface::collectRates() has incorrect return signature
### Summary

[\Magento\Shipping\Model\Carrier\AbstractCarrierInterface::collectRates](https://github.com/magento/magento2/blob/dc6d0b01fff3988f706f718e16d877bb4b1dea91/app/code/Magento/Shipping/Model/Carrier/AbstractCarrierInterface.php#L24-L31) currently has in its signature that it will return `\Magento\Framework\DataObject`, but technically `\Magento\Shipping\Model\Rate\Result` is used everywhere, and it does not inherit the DataObject, so the signature is, de facto, incorrect.

### Examples

[\Magento\Shipping\Model\Shipping](https://github.com/magento/magento2/blob/dc6d0b01fff3988f706f718e16d877bb4b1dea91/app/code/Magento/Shipping/Model/Shipping.php#L197-L264):

```
        if (!$result) {
            //One shipment for all items.
            $result = $carrier->collectRates($request);
        }

        if (!$result) {
            return $this;
        } elseif ($result instanceof Result) { // use Magento\Shipping\Model\Rate\Result;
            $this->getResult()->appendResult($result, $carrier->getConfigData('showmethod') != 0);
        } else {
            $this->getResult()->append($result);
        }
```

Both append methods expect the result class:

```
    /**
     * Append result received from a carrier.
     *
     * @param Result $result
     * @param bool $appendFailed Append result's errors as well.
     * @return void
     */
    public function appendResult(Result $result, bool $appendFailed): void
    {
        $this->results[] = ['result' => $result, 'appendFailed' => $appendFailed];
    }
```

```
    /**
     * Add a rate to the result
     *
     * @param \Magento\Quote\Model\Quote\Address\RateResult\AbstractResult|\Magento\Shipping\Model\Rate\Result $result
     * @return $this
     */
    public function append($result)
    {
        if ($result instanceof \Magento\Quote\Model\Quote\Address\RateResult\Error) {
            $this->setError(true);
        }
        if ($result instanceof \Magento\Quote\Model\Quote\Address\RateResult\AbstractResult) {
            $this->_rates[] = $result;
        } elseif ($result instanceof \Magento\Shipping\Model\Rate\Result) {
            $rates = $result->getAllRates();
            foreach ($rates as $rate) {
                $this->append($rate);
            }
        }
        return $this;
    }
```

Some Magento shipping modules also don't expect the DataObject to be used:

[Flatrate](https://github.com/magento/magento2/blob/dc6d0b01fff3988f706f718e16d877bb4b1dea91/app/code/Magento/OfflineShipping/Model/Carrier/Flatrate.php#L71-L99):

```
    /**
     * Collect and get rates
     *
     * @param RateRequest $request
     * @return Result|bool
     * @SuppressWarnings(PHPMD.CyclomaticComplexity)
     * @SuppressWarnings(PHPMD.NPathComplexity)
     */
    public function collectRates(RateRequest $request)
    {
        /** @var Result $result */
        $result = $this->_rateResultFactory->create();
...
        return $result;
    }
```

[Freeshipping](https://github.com/magento/magento2/blob/dc6d0b01fff3988f706f718e16d877bb4b1dea91/app/code/Magento/OfflineShipping/Model/Carrier/Freeshipping.php#L84-L128):

```
    /**
     * FreeShipping Rates Collector
     *
     * @param RateRequest $request
     * @return \Magento\Shipping\Model\Rate\Result|bool
     */
    public function collectRates(RateRequest $request)
    {
...
        /** @var \Magento\Shipping\Model\Rate\Result $result */
        $result = $this->_rateResultFactory->create();
...
        return $result;
    }
```

[UPS](https://github.com/magento/magento2/blob/dc6d0b01fff3988f706f718e16d877bb4b1dea91/app/code/Magento/Ups/Model/Carrier.php#L248-L276):

```
    /**
     * Collect and get rates/errors
     *
     * @param RateRequest $request
     * @return Result|Error|bool
     */
    public function collectRates(RateRequest $request)
    {
...
    }
```

[Fedex](https://github.com/magento/magento2/blob/dc6d0b01fff3988f706f718e16d877bb4b1dea91/app/code/Magento/Fedex/Model/Carrier.php#L288-L305):

```
    /**
     * Collect and get rates
     *
     * @param RateRequest $request
     * @return Result|bool|null
     */
    public function collectRates(RateRequest $request)
    {
        if (!$this->canCollectRates()) {
            return $this->getErrorMessage();
        }

        $this->setRequest($request);
        $this->_getQuotes();
        $this->_updateFreeMethodQuote($request);

        return $this->getResult();
    }
```

Basically no class expects `\Magento\Framework\DataObject`, as the AbstractCarrierInterface::collectRates() suggests.

### Proposed solution

Change the method's signature to reflect the real world, but the method is marked with `@api`, so I don't know how to proceed.

### PR DESCRIPTION
**Pull request by kassner**
### Description

See #28514

### Fixed Issues (if relevant)

1. Fixes #28514

### Manual testing scenarios

1. Run phpstan/psalm against a custom shipping method class.
2.
```
 ------ --------------------------------------------------------------------------------- 
  Line   app/code/Vendor/Module/Model/Carrier/MyCarrier.php  
 ------ --------------------------------------------------------------------------------- 
  108    Method                                                                           
         Vendor\Module\Model\Carrier\MyCarrier::collectRates() should
         return bool|Magento\Framework\DataObject|null but returns            
         Magento\Shipping\Model\Rate\Result.                                              
 ------ --------------------------------------------------------------------------------- 
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@gabrieldagama, I believe we can accept this PR even to 2.4-develop, as it's just fixing incorrect return type in the phpdoc block and won't hurt anyone during an upgrade, right?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by Den4ik — CHANGES_REQUESTED** [review]
HI @kassner!
Thanks for your work.

Some of classes that implements `AbstractCarrierInterface` also may return `Magento\Quote\Model\Quote\Address\RateResult\Error` that extends `DataObject` class.
In my opinion we have 2 ways in this case:
1. Add `Result` additionally to interface definition
2. `Result` should extending some `AbstractResult` that extending `DataObject`

**Comment by kassner** [comment]
True. The result of `collectTotals` in the core is used in two places:

1st:

https://github.com/magento/magento2/blob/4b439a632dd86033ed6afc07695f05f522b6d3c4/app/code/Magento/Shipping/Model/Shipping.php#L326-L331

Where `appendPackageResult` expects `\Magento\Shipping\Model\Rate\Result`:

https://github.com/magento/magento2/blob/4b439a632dd86033ed6afc07695f05f522b6d3c4/app/code/Magento/Shipping/Model/Rate/PackageResult.php#L48-L51

2nd:

https://github.com/magento/magento2/blob/4b439a632dd86033ed6afc07695f05f522b6d3c4/app/code/Magento/Shipping/Model/Shipping.php#L335-L346

Which handles both `null|false`, `\Magento\Shipping\Model\Rate\Result` and `mixed`, as the `append` method will just silently ignore a non-parseable value:

https://github.com/magento/magento2/blob/4b439a632dd86033ed6afc07695f05f522b6d3c4/app/code/Magento/Shipping/Model/Rate/Result.php#L77-L97

Your 2nd suggestion shouldn't be the case, as AbstractResult is defined in Magento\Quote, but the Result is in Magento\Shipping. IMHO Magento\Shipping should define a ResultInterface for that and then change Magento\Quote classes to implement it, but that's not for me to decide.

**Comment by Den4ik** [comment]
I think 1st is preferrer

**Comment by ishakhsuvarov** [comment]
Hi @kassner 

I am closing this PR for now as it seems like it has become stale and still needs work.

Please feel free to reopen if you wish to continue.

Thanks!

**Pull request closed without merging**
