### PR TITLE
Optimize loading of media gallery when editing a product

### LINKED ISSUE #33434: [Issue] Optimize loading of media gallery when editing a product
This issue is automatically created based on existing pull request: magento/magento2#32818: Optimize loading of media gallery when editing a product

---------

### Description (*)

This PR aims to optimize the loading of the gallery tab when editing a product with many images, by avoiding redundant operations.

In a real-world example with a product with nearly 300 images, loading the gallery was more than 10 times faster after applying the changes.

### Manual testing scenarios (*)

1. Create a product.
2. Add or import a hundred images.
3. Edit the product again, opening the gallery tab is (very) slow.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by blmage**
### Description (*)

This PR aims to optimize the loading of the gallery tab when editing a product with many images, by avoiding redundant operations.

In a real-world example with a product with nearly 300 images, loading the gallery was more than 10 times faster after applying the changes.

### Manual testing scenarios (*)

1. Create a product.
2. Add or import a hundred images.
3. Edit the product again, opening the gallery tab is (very) slow.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#33434: Optimize loading of media gallery when editing a product

### CODE REVIEW

**Comment by blmage** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Static Tests, Integration Tests, Functional Tests EE, Functional Tests B2B

**Comment by mrtuvn** [comment]
@magento run Static Tests, Functional Tests B2B

**Comment by mrtuvn** [comment]
Can you cover your change with some js tests in jasmine
dev/tests/js/jasmine/tests/app/code/Magento/Catalog/adminhtml/js/product-gallery.test.js

**Comment by mrtuvn** [comment]
@magento run Unit Tests, Static Tests, Integration Tests, Functional Tests CE, Functional Tests EE

**Comment by blmage** [comment]
@mrtuvn Could you point me to what you think should be covered that is not already by the current tests?

**Comment by blmage** [comment]
@magento run Static Tests

**Comment by blmage** [comment]
Not sure what keyword the bot did not like here, especially since I did not mention it..  closing this in the hope that it will fix the problem.

**Comment by mrtuvn** [comment]
@blmage do you close this or it's auto closed

**Comment by blmage** [comment]
@mrtuvn I closed it myself because the bot started to act weirdly (without even being mentioned), and I was hoping that might stop it from adding more and more comments.

Do you know what happened, and/or how this can be avoided?

Also, should I reopen this PR, or open another one?

Thanks!

**Comment by mrtuvn** [comment]
Feel free to reopen if you want. I don't know what happens internal. Maybe some broken ci deploy

**Comment by blmage** [comment]
@mrtuvn I've checked `dev/tests/js/jasmine/tests/app/code/Magento/Catalog/adminhtml/js/product-gallery.test.js`, and everything seems to be covered already. What other case would you like to see handled?

**Comment by mrtuvn** [comment]
Basically this is js test from core số you are free to add any new test case with your change in this file

**Comment by blmage** [comment]
The PR only adds internal changes to `_create` and `_addItem`, which are [already covered](https://github.com/magento/magento2/blob/ad08ccfda9b2125a6568da414565305d27f9ac7a/dev/tests/js/jasmine/tests/app/code/Magento/Catalog/adminhtml/js/product-gallery.test.js#L93-L130), so I'm not sure what cases could be added?

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@blmage Could you please check static and functional tests. Looks like failed tests related to the changes

**Comment by blmage** [comment]
@Den4ik Static tests should be fixed now.

I don't think the failed functional tests are related to this PR though, given that they also seem to fail for other PRs.

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run WebAPI Tests, Functional Tests B2B

**Comment by Den4ik** [comment]
@magento run WebAPI Tests

**Review by Den4ik — APPROVED** [review]
Hi @blmage!
Thats awesome. Gallery load time for 300 images reduced from 25sec to 1sec.
Thanks for you work.

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9068](https://jira.corp.magento.com/browse/ENGCOM-9068) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@blmage thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

> 1. Create a simple product; uploading ~100s of images while creating.


**Manual testing scenario:**
> 
> 1. Navigate to the Admin side product page.
> 
> 2. Search the product that is having ~100s of images. Click on Edit products.
>  
> 3. Click on `Images and Videos` tab section of the product edit page, and validate its response time.
> 

**Before:** :heavy_multiplication_x: Response time was around 2000ms for around 70 uploaded images

> image


**After:** :heavy_check_mark:  Response time is around 650ms for around 70 uploaded images

> image

**Pull request merged**
