### PR TITLE
[Forwardport] #7903 correct the position of the datepicker when you scroll

### PR DESCRIPTION
**Pull request by hitesh-wagento**
### Original Pull Request 
 https://github.com/magento/magento2/pull/12045

### Description

Change less styles for field-control so datepicker fields do not appear out of place

### Fixed Issues (if relevant)

1. magento/magento2#7903: Datepicker does not scroll

### Manual testing scenarios

As described in the issue

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @hitesh-wagento. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by hitesh-wagento** [comment]
Hi @sidolov 

Any Update in this PR ?

Thanks

**Comment by sidolov** [comment]
@hitesh-wagento , PR currently in `Delivery in progress status`. You can track your PR status on the [board](https://github.com/magento/magento2/projects/3).
Also, you can see the status in the PRs right column:
54c26a3292

**Comment by hitesh-wagento** [comment]
@sidolov

Any update in this PR ?

Thanks

**Comment by magento-engcom-team** [comment]
Hi @hitesh-wagento. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Pull request merged**
