### PR TITLE
Fixed 19793: Area Frontend Reload Captcha button misaligned.

### PR DESCRIPTION
**Pull request by suryakant-krish**
Area Frontend Reload Captcha button misaligned.
### Fixed Issues (if relevant)

1. magento/magento2#19793: Area Frontend: Reload Captcha button misaligned.

### Manual testing scenarios (*)

1. Go to frontend > Click on sign in link top right corner > Click on forgot password link.
Reload Captcha button vertical misaligned.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by aleron75 — APPROVED** [review]

**Comment by aleron75** [comment]
Hello @suryakant-krish thanks for your contribution.

Once merged, provided the same issue applies also on other versions, you can easily port this PR to other branches with the Porting Tool, [read more here](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#porting-tool).

**Comment by sivaschenko** [comment]
Hi @suryakant-krish reload captcha button is positioned incorrectly after entering incorrect password 3 times when trying to login to customer account. Please take a look:
image

**Comment by sidolov** [comment]
@suryakant-krish , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
