### PR TITLE
fixed Quote Item Prices are NULL in cart related events. #18685

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)
before these two observers checkout_cart_product_add_after, checkout_cart_product_update_after cart item is not saved into the database the object is only created and in the object price was not set but custom price was set so there was no issue of custom price, we could have added the price in the item from two files:
app/code/Magento/Quote/Model/Quote/Item/Processor.php and
app/code/Magento/Quote/Model/Quote.php
I have added the price in this file app/code/Magento/Quote/Model/Quote/Item/Processor.php

### Fixed Issues (if relevant)

1. magento/magento2#18685: Quote Item Prices are NULL in cart related events

### Manual testing scenarios (*)

1. create a module which has observers for these two events checkout_cart_product_add_after, checkout_cart_product_update_after cart
2. now in the observer try to get the added item price by calling $observer->getEvent()->getQuoteItem()->getPrice()

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ashutoshwebkul. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by ghost** [comment]
#squashtoberfest

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3271](https://jira.corp.magento.com/browse/ENGCOM-3271) has been created to process this Pull Request

**Comment by ghost** [comment]
@magento-engcom-team, why there is no reward update on the pull request, is there anything else need to be done, I am new to contribution so please guide me and is this pull request eligible for #squashtoberfest event

**Comment by ghost** [comment]
@magento-engcom-team can I know the reason why review failed, I went through the details at codacy but there is no proper description, please explain so i can fix this

**Comment by magento-engcom-team** [comment]
Hi @ashutoshwebkul. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.

**Pull request merged**
