### PR TITLE
Issues #22338 - Override price-box.js using mix-in Firefox

### PR DESCRIPTION
**Pull request by srenon**
### Description (*)

Mix-in does not work in Firefox, Safari and other non-chrome browsers.

### Fixed Issues (if relevant)

1. magento/magento2#22338: Magento 2.3 - Issue to override price-box.js using mixin(In Firefox 66.0.2 version)

### Manual testing scenarios (*)

1. Create a mix-in for price-box.js

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24054) <br/>All committers have signed the CLA.

**Review by VladimirZaets — APPROVED** [review]

**Comment by engcom-Foxtrot** [comment]
@srenon please, sign CLI and resolve the merge conflict.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5559](https://jira.corp.magento.com/browse/ENGCOM-5559) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

**Before:**
before

**After:**
after

Checked on Firefox v.68.0.2

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
