### PR TITLE
Resolve Sales Rule extensibility problem for actions issue 18359

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

Solution:
$formName should be `$formName = $this->getRequest()->getParam('form_namespace');`  (Get correct params which is sent, 'form_namespace' not 'form')

Should add: `$model->setFormName($formName);` to code.

`\Magento\SalesRule\Controller\Adminhtml\Promo\Quote\NewActionHtml, Magento\CatalogRule\Controller\Adminhtml\Promo\Catalog\NewActionHtml`

 **like in**
```
 \Magento\SalesRule\Controller\Adminhtml\Promo\Quote\NewConditionHtml ,
Magento\CatalogRule\Controller\Adminhtml\Promo\Catalog\NewConditionHtml
```

### Fixed Issues (if relevant)

1. magento/magento2#18359: Sales Rule extensibility problem for actions

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by swnsma** [comment]
Hi @edenduong,
Could you provide steps to reproduce and (or) prepared code for this issue?

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5781](https://jira.corp.magento.com/browse/ENGCOM-5781) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
Hi @edenduong after fix we cannot apply condition for Category in Actions tab for Cart Price Rule
**Manual testing scenario:**

- Go to Marketing->Cart Price Rules and click Add New Rule
- Navigate to Actions tab
- Select Category in the `If ALL  of these conditions are TRUE :` section 
- Choose specific category and click Apply icon

:heavy_check_mark: **Expected result:**
Category id is applied
#23763Main

:x: **Actual result:**
Category id is not applied after it was chosen
#23763PR

Could you take a look?

**Comment by sidolov** [comment]
@edenduong  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by edenduong** [comment]
I will continue solving this issue so I reopened this PR.

**Comment by edenduong** [comment]
Seems someone fixed it and it was merged to develop, so I will close this PR.

Thanks!

**Pull request closed without merging**
