### PR TITLE
Fix failure for missing product on Storefront

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Standard issue related with Indexers set to reindex on schedule.

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
image

### Manual testing scenarios (*)
N/A

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
image
image

**Comment by lbajsarowicz** [comment]
To solve Second Issue with EE - I merged #26776 to have latest feature of MFTF (`<mageCron`) available.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-6837](https://jira.corp.magento.com/browse/ENGCOM-6837) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by lbajsarowicz** [comment]
D'oh. I've broken whole Magento :rofl:

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi, @lbajsarowicz please check failed functional test.

**Comment by lbajsarowicz** [comment]
@engcom-Charlie not related to the changes

**Comment by engcom-Charlie** [comment]
@lbajsarowicz tests don't fail on the mainline.

**Comment by lbajsarowicz** [comment]
You have to be kidding 🤦‍♂️
Tests are failing for month or so, call @okolesnyk, he will explain you how test estimation affects the overlapping tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @rogyar could You please review PR again?

**Review by rogyar — APPROVED** [review]
@lbajsarowicz good job!

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-6837](https://jira.corp.magento.com/browse/ENGCOM-6837) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Pull request merged**
