### PR TITLE
LoginToStorefrontActionGroup action group is utilize in existing MFTF

### LINKED ISSUE #28165: [Issue] LoginToStorefrontActionGroup action group is utilize in existing MFTF
This issue is automatically created based on existing pull request: magento/magento2#28113: LoginToStorefrontActionGroup action group is utilize in existing MFTF

---------
### Description (*)
**LoginToStorefrontActionGroup** is utilized to replace sequence of actions which has used for store front customer login.

### Manual testing scenarios (*)
1. Run the **StorefrontPurchaseProductWithCustomOptionsWithLongValuesTitleTest, StorefrontDeleteCustomerAddressTest, StorefrontPersistedCustomerLoginTest, ConfigurableProductChildImageShouldBeShownOnWishListTest, StorefrontDeletePersistedWishlistTest** and verified the test runs successfully.

### Questions or comments
If any please let me know your feedback's.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by srsathish92**
### Description (*)
**LoginToStorefrontActionGroup** is utilized to replace sequence of actions which has used for store front customer login.

### Manual testing scenarios (*)
1. Run the **StorefrontPurchaseProductWithCustomOptionsWithLongValuesTitleTest, StorefrontDeleteCustomerAddressTest, StorefrontPersistedCustomerLoginTest, ConfigurableProductChildImageShouldBeShownOnWishListTest, StorefrontDeletePersistedWishlistTest** and verified the test runs successfully.

### Questions or comments
If any please let me know your feedback's.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28165: LoginToStorefrontActionGroup action group is utilize in existing MFTF

### CODE REVIEW

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @srsathish92. Thank you for your collaboration. 

`LoginToStorefrontActionGroup` is a legacy action group. Also, it has a name that does not meet the naming convention. 

Please, use the following action groups `StorefrontFillCustomerLoginFormActionGroup` + `StorefrontClickSignOnCustomerLoginFormActionGroup` instead of `LoginToStorefrontActionGroup`

Thank you!

**Comment by srsathish92** [comment]
@rogyar Thanks for your feedback. As per your suggestions, I have updated action groups. can you please review now?

**Review by rogyar — APPROVED** [review]
The failing tests are not related to the current change

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7529](https://jira.corp.magento.com/browse/ENGCOM-7529) has been created to process this Pull Request

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Comment by slavvka** [comment]
@magento create issue

**Pull request merged**
