### PR TITLE
[Backport] Alignment Issue While Editing Order Data containing Downlodable Products with "Links can be purchased separately" enabled in Admin Section

### PR DESCRIPTION
**Pull request by deepakk-webkul**
### Original Pull Request 
 https://github.com/magento/magento2/pull/22298
Alignment Issue While Editing Order Data containing Downlodable Products with "Links can be purchased separately" enabled in Admin Section

### Description (*)
Magento 2.3.x
Magento 2.2.x

### Fixed Issues (if relevant)

1. magento/magento2#20917: Alignment Issue While Editing Order Data containing Downlodable Products in Admin Section

### Manual testing scenarios (*)

1. Login into admin panel
2. go to Order grid section from Sales > Orders
3. Reorder any order containing downladable product with "Links can be purchased separately" enabled.
4. now click on configure button : https://prnt.sc/navb8m
5. A modal will display an alignment issue : https://prnt.sc/navble

### Actual result (*)
https://prnt.sc/navble

### Expected result (*)
https://prnt.sc/navc9o

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22582) <br/>All committers have signed the CLA.

**Review by ronak2ram — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ronak2ram, thank you for the review.
[ENGCOM-5017](https://jira.corp.magento.com/browse/ENGCOM-5017) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@webkul-deepakkumar thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by orlangur** [comment]
@dmytro-ch @sivaschenko do we allow such kind of cleanup to be backported?

**Comment by dmytro-ch** [comment]
As a matter of fact, the backport should be rejected if the original pull request is marked as a cleanup.
We've got many similar PRs for 2.2 release line previously. Those PRs have been also closed despite the necessity of the provided fixes.

**Comment by orlangur** [comment]
@dmytro-ch I personally would allow to backport anything which produces visually recognizable result as otherwise it is hard to determine what is an "important fix". But we should be consistent on this and have clear rules for any situation.

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed 

**Before:**

before

**After:**

after

**Pull request merged**
