### PR TITLE
Fixed ability to save configuration in field without label

### PR DESCRIPTION
**Pull request by AndreyChorniy**
### Description (*)
This PR add the ability to save the configuration in the field without a label. 

### Fixed Issues (if relevant)
1. magento/magento2#23899: system.xml file validation issue

### Manual testing scenarios (*)

1. In system.xml create field without a label:
```
`<group id="test_group" translate="label" type="text" sortOrder="90" showInDefault="1" showInWebsite="1" showInStore="1">
                <field id="test_field" translate="label comment" type="text" sortOrder="10" showInDefault="1" showInWebsite="0" showInStore="0" canRestore="1">
                    <comment>Use {{name}} as Product Name placeholder</comment>
                </field>
</group>`
```
2. Go to admin panel `System -> Configuration -> {path_to_your_new_field}`
3. Fill this field
4. Save configuration

### Questions or comments
This fix deletes part of `if` expression. In my opinion, we don't need to disallow save fields without labels.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-6460](https://jira.corp.magento.com/browse/ENGCOM-6460) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Charlie** [comment]
Hello @AndreyChorniy 
Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.
Thanks!

**Comment by engcom-Golf** [comment]
I will take care of test coverage

**Comment by engcom-Golf** [comment]
Hi @aleron75 all changes covered by unit test could you please review ?

**Comment by aleron75** [comment]
Hello @AndreyChorniy, can you please check the failing unit test?
Thanks

**Comment by engcom-Golf** [comment]
@aleron75 test failed because i changed mock file, will fix them tomorrow's, and static test.

**Comment by engcom-Golf** [comment]
@aleron75 all done :heavy_check_mark:

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-6460](https://jira.corp.magento.com/browse/ENGCOM-6460) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
