### PR TITLE
Add event listeners passive for fotorama lib improves lighthouse metrics

### LINKED ISSUE #31140: [Issue] Add event listeners passive for fotorama lib improves lighthouse metrics
This issue is automatically created based on existing pull request: magento/magento2#31080: Add event listeners passive for fotorama lib improves lighthouse metrics

---------

### Description (*)

Improve lighthouse metrics score for fotorama js lib

Screenshot from 2020-11-27 22-30-28

### Preconditions
2.4-develop

### Steps to reproduce
1. From Admin Panel, create a product
2. From Storefront, open the previously created products page
3. Right-click on the web page and select **Inspect** to open browsers dev console
4. Switch to the _Lighthouse_ tab
5. Click **Generate report**
gen_rep
6. Observe the red scores under _Diagnostics_

### Actual Result
The score for `fotorama js lib` was red
before2

### Expected result
after
### Manual testing scenario
1. From Admin Panel, create a product
2. From Storefront, open the previously created products page
3. Right-click on the web page and select **Inspect** to open browsers dev console
4. Switch to the _Lighthouse_ tab
5. Click **Generate report**
gen_rep
6. Observe the red scores under _Diagnostics_

**BEFORE** applying changes provided in the PR, the score for `fotorama js lib` was red
before2

**AFTER** switching to the PR
after

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Improve lighthouse metrics score for fotorama js lib

Screenshot from 2020-11-27 22-30-28

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31140: Add event listeners passive for fotorama lib improves lighthouse metrics

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8494](https://jira.corp.magento.com/browse/ENGCOM-8494) has been created to process this Pull Request

**Comment by sidolov** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

### Manual testing scenario
1. From Admin Panel, create a product
2. From Storefront, open the previously created products page
3. Right-click on the web page and select **Inspect** to open browsers dev console
4. Switch to the _Lighthouse_ tab
5. Click **Generate report**
gen_rep
6. Observe the red scores under _Diagnostics_

**BEFORE** applying changes provided in the PR, the score for `fotorama js lib` was red
before2

**AFTER** switching to the PR
after

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B

**Comment by glevhen** [comment]
this PR cause js errors on the product page when swipe fotorama product images (touch events)
image
`fotorama.js:1222 Unable to preventDefault inside passive event listener invocation.`

**Comment by mrtuvn** [comment]
https://github.com/magento/magento2/pull/34162/files#diff-ce58a428085808b85d9b7ef9d673d944a80f1d841a2e8320d691314597d624f5
Already did that here

**Pull request merged**
