### PR TITLE
Fixed issue #21450

### PR DESCRIPTION
**Pull request by geet07**
### Description (*)
Url should be generated without #size=169&color=56 parameters.

### Fixed Issues (if relevant)

1. magento/magento2#[21450](https://github.com/magento/magento2/issues/21450): Magento 2.3 -21450: solve issue adding attributes value in URL param

### Manual testing scenarios (*)

1. Enable After Adding a Product Redirect to Shopping Cart setting from store >> configuration >> sales >> checkout >> Shoping Cart >> After Adding a Product Redirect to Shopping Cart .

2. Add any configurable product from the product detail page.

3. After adding a product it will redirect to checkout/cart page and URL which will not include any parameters.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sidolov** [comment]
Hi @geet07 , the file you removed in this PR was added to resolve the following issue: 

## STEPS TO REPRODUCE

1. Go to Products > Catalog > Add Product
2. Enter the following information

Product Name: testupload
Sku: testupload
Price: 100
Quantity: 10
Stock Status: In Stock

**Configurations Tab**
Click on Create Configurations button
Select color attribute and click Next
Select Two Color attributes from the list and click Next
In the Price section select "Apply single price to all Skus" and set Price = 100
In the Quantity section select "Apply single quantity to each SKUs" and set the qty = 10 and click next to finish with the process

**Customizable Options**
Click on the "Add Option" button and enter the below details:
Option title: Add Logo
Option Type: File
Uncheck the Required checkbox
SKU: FILE
Compatible extensions: jpg, gif, jpeg, eps
Maximum Image Size: 0px
Save the item

3. Go to the frontend and load testupload product
4. Select one of the color options
5. Click on the Choose File button and try to upload a .txt file
6. Click Add to cart
 The selected color is not longer selected and the error "You need to choose options for your item." is displayed

## EXPECTED RESULTS
 If the user attempts to upload a file with unsupported file format, a descriptive error associated to invalid file format should be displayed - "File '<file name uploaded by user>' for '<option name>' has an invalid extension." and the selected configurable options should remain selected.

## ACTUAL RESULTS
 If the user attempts to upload a file with unsupported file format, the error "You need to choose options for your item." appears (error not associated to the actual problem) and the options selected by the user are lost, forcing the user to re-select the options.


Please, take to account that mentioned scenario should work properly after your fix.

**Comment by geet07** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @geet07. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @geet07, here is your [new Magento instance](https://pr-24254.instances.magento-community.engineering).
Admin access: [https://pr-24254.instances.magento-community.engineering/admin](https://pr-24254.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by geet07** [comment]
> Hi @geet07 , the file you removed in this PR was added to resolve the following issue:
> 
> ## STEPS TO REPRODUCE
> 1. Go to Products > Catalog > Add Product
> 2. Enter the following information
> 
> Product Name: testupload
> Sku: testupload
> Price: 100
> Quantity: 10
> Stock Status: In Stock
> 
> **Configurations Tab**
> Click on Create Configurations button
> Select color attribute and click Next
> Select Two Color attributes from the list and click Next
> In the Price section select "Apply single price to all Skus" and set Price = 100
> In the Quantity section select "Apply single quantity to each SKUs" and set the qty = 10 and click next to finish with the process
> 
> **Customizable Options**
> Click on the "Add Option" button and enter the below details:
> Option title: Add Logo
> Option Type: File
> Uncheck the Required checkbox
> SKU: FILE
> Compatible extensions: jpg, gif, jpeg, eps
> Maximum Image Size: 0px
> Save the item
> 
> 1. Go to the frontend and load testupload product
> 2. Select one of the color options
> 3. Click on the Choose File button and try to upload a .txt file
> 4. Click Add to cart
>    The selected color is not longer selected and the error "You need to choose options for your item." is displayed
> 
> ## EXPECTED RESULTS
> If the user attempts to upload a file with unsupported file format, a descriptive error associated to invalid file format should be displayed - "File '' for '' has an invalid extension." and the selected configurable options should remain selected.
> 
> ## ACTUAL RESULTS
> If the user attempts to upload a file with unsupported file format, the error "You need to choose options for your item." appears (error not associated to the actual problem) and the options selected by the user are lost, forcing the user to re-select the options.
> 
> Please, take to account that mentioned scenario should work properly after your fix.

Hi @sidolov, I have reverted my previous commit and resolved the issue.  I have also checked these scenarios, which you mentioned above. Please check and let me know if there is another change required.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5732](https://jira.corp.magento.com/browse/ENGCOM-5732) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by engcom-Foxtrot** [comment]
Failed tests fixed in internal repo.

**Comment by engcom-Foxtrot** [comment]
@geet07, could you please remove restrictions from your https://github.com/geeta07/magento2 repository? It would greatly improve our workflow with your pull requests.

**Comment by geet07** [comment]
> @geet07, could you please remove restrictions from your https://github.com/geeta07/magento2 repository? It would greatly improve our workflow with your pull requests.

Hi @engcom-Foxtrot ,
Options
I have checked, there is no restrictions. Can you please share details which type of restrictions I can remove.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
