### PR TITLE
Order Invoice create page doesn't show order items properly for bundle product Fixed Issue #27350

### PR DESCRIPTION
**Pull request by gaurav-473**
Fixed Issue #27350

### Fixed Issues (if relevant)
1. magento/magento2#27350

While crating invoice for bundle product doesn't show its child items.
### Preconditions (*)

1. Magento version 2.3.4 CE

### Steps to reproduce (*)

1. Create Bundle Product and add 2 items https://prnt.sc/ritlae
2. Place order for Bundle product with both the items https://prnt.sc/ritmme
3. Go to create invoice page for the same order https://prnt.sc/ritn0p

### Expected result (*)

1. Order Items should be displayed properly as in screenshot https://prnt.sc/rito2g

### Actual result (*)

1. Items are missing https://prnt.sc/ritn0p

### CODE REVIEW

**Comment by gauravagarwal1001** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @gauravagarwal1001. Thank you for your request. I'm working on Magento instance for you

**Comment by gauravagarwal1001** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @gauravagarwal1001. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @gauravagarwal1001, here is your [new Magento instance](https://pr-27602.instances.magento-community.engineering).
Admin access: [https://pr-27602.instances.magento-community.engineering/admin_2c29](https://pr-27602.instances.magento-community.engineering/admin_2c29)
Login: `6654fd22` Password: `0c2d4c52eae6`
Instance will be terminated in up to 3 hours.

**Comment by gauravagarwal1001** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @gauravagarwal1001. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @gauravagarwal1001, here is your [Magento instance](https://i-27602-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27602-2-4-develop.instances.magento-community.engineering/admin_5322](https://i-27602-2-4-develop.instances.magento-community.engineering/admin_5322)
Login: `959ee0f5` Password: `014f9b1b067b`
Instance will be terminated in up to 3 hours.

**Review by gabrieldagama — COMMENTED** [review]
Hi @gauravagarwal1001, thanks for the pull request! Could you update this PR with the mainline? Also, all the PRs now must have test coverage, it would be nice to add an MFTF to check if the items are displayed.

Let me know if you need any help with this.

Thanks.

**Review by sidolov — CHANGES_REQUESTED** [review]
Waiting for contributor's response

**Comment by engcom-Charlie** [comment]
Hi gauravagarwal1001, can you please merge the conflict and cover your changes by autotest? Otherwise, we can't proceed with your PR.
Thank you.

**Comment by engcom-Charlie** [comment]
Hi @gauravagarwal1001, I'll try to continue with your pr.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by saphaljha** [comment]
@magento run Functional Tests B2B

**Review by gabrieldagama — APPROVED** [review]

**Comment by gabrieldagama** [comment]
@magento run Functional Tests B2B

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8159](https://jira.corp.magento.com/browse/ENGCOM-8159) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Create Bundle Product with different option types (dropdown, radio button, checkbox, multi-select);



2. Create an Order with pre-selected options;
3. Go to create invoice page for the same order;

**Before:** :heavy_multiplication_x: Items are missing




**After:** :heavy_check_mark: The bundle product is displayed with a list of options



Also, was tested with a few bundle products with different types of options in order, and everything works as expected.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Pull request merged**
