### PR TITLE
Marked classes and interfaces as API part 2

### LINKED ISSUE #32056: Mark classes and interfaces as API part 2
The following classes and interfaces should be marked as API in 2.4-develop branch

1. Magento\Ui\DataProvider\Modifier\PoolInterface	
1. Magento\Framework\App\RouterInterface	
1. Magento\Framework\Setup\Patch\DataPatchInterface
1. Magento\Framework\Console\Cli
1. Magento\Catalog\Controller\Adminhtml\Product	
1. Magento\Framework\App\Config\ValueFactory	
1. Magento\Framework\Module\ModuleListInterface
1. Magento\Catalog\Pricing\Price\FinalPrice
1. Magento\Framework\App\Config\ConfigResource\ConfigInterface	
1. Magento\Framework\Module\Dir	
1. Magento\Framework\App\Cache\Type\Config	
1. Magento\Store\Ui\Component\Listing\Column\Store\Options
1. Magento\Framework\Mview\ActionInterface
1. Magento\Ui\DataProvider\AddFieldToCollectionInterface	
1. Magento\Framework\Filesystem\Directory\ReadFactory
1. Magento\Framework\GraphQl\Query\ResolverInterface	
1. Magento\Payment\Gateway\Config\Config	
1. Magento\Ui\DataProvider\AddFilterToCollectionInterface	
1. Magento\Customer\Block\Adminhtml\Edit\GenericButton

### PR DESCRIPTION
**Pull request by ProkopovVitaliy**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#32056

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ProkopovVitaliy** [comment]
@magento run all tests

**Comment by ProkopovVitaliy** [comment]
@magento run all tests

**Review by eduard13 — CHANGES_REQUESTED** [review]
@ProkopovVitaliy please change the base mainline, it should point 2.5-develop.

**Comment by ProkopovVitaliy** [comment]
> @ProkopovVitaliy please change the base mainline, it should point 2.5-develop.

i recreated PR here https://github.com/magento/magento2/pull/32132

**Pull request closed without merging**
