### PR TITLE
Grid filtration doesn't work for mysql special characters

### PR DESCRIPTION
**Pull request by laconica-sergey**
### Manual testing scenarios

1. Create several products
2. Open product grid
3. Open filters block
4. Enter % or _ to name field
5. Do filter

###Expected result

Grid shows only products with the symbol

###Actual result

Grid shows all products
 
### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=12749) <br/>All committers have signed the CLA.

**Comment by avoelkl** [comment]
Hi @laconica-sergey,
Thanks for the PR!
I just tried to test and reproduce any, anyway it seems this is already working on the latest 2.2-develop branch.

See my screenshots below. Can you please give me some more information where/how this is not working? Thanks!

In this case I added two products:
Samsung Galaxy S8 G950F and
Samsung Galaxy% S8+ G955F

Samung%
bildschirmfoto 2018-01-03 um 20 54 48

Samsung_
bildschirmfoto 2018-01-03 um 20 54 30

**Comment by avoelkl** [comment]
Any update on my previous question @laconica-sergey?

**Comment by igrybkov** [comment]
Hi @avoelkl,

You actually reproduced the issue: the filter doesn't apply, and your search disrespects special character in the search phrase. Search for the term 'Samsung%' should show nothing in your case and search by the phrase 'Galaxy%' should show only one product with the exact match.

To make it clear, try to search by the '%' sign — you will see both products, but the only one actually should match this search.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[MAGETWO-85827](https://jira.corp.magento.com/browse/MAGETWO-85827) has been created to process this Pull Request

**Pull request merged**
