### PR TITLE
integrate phing, phpunit

### PR DESCRIPTION
**Pull request by BlackIkeEagle**
First big task is running phpunit.

additionally there are 2 dev tasks added
- composer (install php dependencies)
- local-install-grunt (install npm packages for frontend development)

Signed-off-by: BlackEagle ike.devolder@gmail.com

### CODE REVIEW

**Comment by stevenvdp** [comment]
+1

**Comment by choukalos** [comment]
Hi @BlackIkeEagle We're currently investigating Phing.  Can you provide some insights on the value that  Phing would bring to Magento?  How do you see Phing and our CLI tool being utilized?  

Thanks!

**Comment by BlackIkeEagle** [comment]
@choukalos phing would give a lot of integrators and website builders a nice quick start to get their webistes automatically tested. Since both Jenkins and bamboo for instance work easily with this type of 'build' descriptions.

Phing also gives us a way to uniformly describe how to test/build/package/deploy a magento2 project.
What I've currently done is a cleanup of how the tests are run via travis but this could go as far as test -> build -> deploy.

Phing should not be integrated with the magento cli tool, phing could use the magento cli tool to run commands defined there.

From my point of view the biggest value would be the ease of reuse for companies using magento to build shops.

**Comment by Zatara7** [comment]
Hi @BlackIkeEagle after much discussion with Magento architects, we decided to not implement this functionality into Magento. Reason being that we already support a build system. It would be nice to also have this but it would mean having to support another dependency. The architects recommended creating a separate fork that contains this if you would like to implement that. Then of course if that fork has a high popularity we will accept it to the core. Thank you for your contribution.

**Pull request closed without merging**
