### PR TITLE
Replace deprecated message manager methods usage

### PR DESCRIPTION
**Pull request by samgranger**
### Description
This pull request replaces the majority of deprecated usage of addSuccess, addNotice, addWarning & addError methods with the addSuccessMessage, addNoticeMessage, addWarningMessage & addErrorMessage methods.

### Fixed Issues (if relevant)
n/a

### Manual testing scenarios
1. Test one of each message type

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by dmanners** [comment]
@samgranger thanks for this, seems there are a lot of test failures. Are you able to have a look into these for us?

**Comment by samgranger** [comment]
Hi David,

I will fix the issues and update this pull request later this week, hoping to find some time tomorrow.

**Comment by adrian-martinez-interactiv4** [comment]
Hi @samgranger , this PR seems to be a duplicated of PR https://github.com/magento/magento2/pull/12008 , are you interested in helping to complete that PR if needed? Thank you !

**Comment by dmanners** [comment]
HI @samgranger I will close this just now but feel free to jump on and help with the older PR that was to replace these deprecated calls also.

**Pull request closed without merging**
