### PR TITLE
Fixed #23897 Sales Configuration in the Minimum Amount field have not proper validation

### LINKED ISSUE #23897: Sales Configuration in the Minimum Amount field have not proper validation
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

`Sales` configuration in the `Sales` have `Minimum Order Amount` have a field `Minimum Amount` that field have used Minimum Order Amount. But issue is that field taking any of the value. There should be take proper validation.

1. Login to the Magento 2 admin.
2. Go to the STORES >> Settings >> Configuration >> Sales >> Sales >> Minimum Order Amount: 
3. Minimum Amount: add any text value
4. Save Config

### Expected result (*)

1. There should be allow only digit.
2. Expected-Result-Sales-MinimumAmount png

### Actual result (*)

1. There is a taking all the value like text and string as well.  Validation is missing
2. Actual-Result-Sales-MinimumAmount png

### PR DESCRIPTION
**Pull request by kirtinariya1**
### Description (*)

Magento 2.3 Sales configuration in the `Sales` have `Minimum Order Amount` have a field `Minimum Amount` resolved proper validation.

### Fixed Issues (if relevant)

1. #23897 : Sales Configuration in the Minimum Amount field have not proper validation

### Manual testing scenarios (*)

1. Login to the Magento 2 admin.
2. Go to the STORES >> Settings >> Configuration >> Sales >> Sales >> Minimum Order Amount:
3. Minimum Amount: add any text value
4. Save Config
5. There should be allow only digits

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-5516](https://jira.corp.magento.com/browse/ENGCOM-5516) has been created to process this Pull Request
:eight_spoked_asterisk: @swnsma, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by sdzhepa** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [new Magento instance](https://pr-23898.instances.magento-community.engineering).
Admin access: [https://pr-23898.instances.magento-community.engineering/admin](https://pr-23898.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
