### PR TITLE
Fixed invalid method call

### LINKED ISSUE #33839: Fixed invalid method call
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1. https://github.com/magento/magento2/pull/33658#issue-701397597
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

Issue spotted while trying to request invoice item details for order with discount, but without discount description. In that case Internal server error occurs

### Manual testing scenarios (*)

No steps required I believe, just make sure that existing method is being called :)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Bartlomiejsz** [comment]
@magento run all tests

**Comment by bgorski** [comment]
This fixed obvious 3 incorrect calls. Marking as accepted.

**Review by bgorski — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@magento run Database Compare, Functional Tests CE, Integration Tests, Static Tests, Unit Tests, WebAPI Tests

**Comment by mrtuvn** [comment]
This changes would consider at first queue deploy. Changes risk low

**Comment by engcom-Alfa** [comment]
Thanks for the contribution and collaboration @Bartlomiejsz and @bgorski !

Tried reproducing the issue in `2.4-develop` version before testing the given PR fix code referring PR description/ comments.
Issue is not reproducible and below is the information on this:


**Pre Conditions**

1. Installed a fresh 2.4-develop version


**Reproducible steps**

1. Created the cart rule from front end having the coupon code

2. Created a new order using front end login applying the above created coupon code.

3. Admin side: Sales > Order : Submitted the shipment and followed by Invoice

4. Viewed Invoices grid, and then clicked on the generated invoice "view"


**Expected Issue as per PR description/ comments:** 
> Internal Server Error


**Actual Result**
> Getting a proper Invoice viewed page with all the invoice information
> Below is the actual screenshot
> image



**Since there is no manual scenario to execute, based on the given one description I have tried to reproduce as mentioned above. In order to proceed forward from QA stage, require a proper steps to reproduce the issue before fix. Kindly provide me detailed steps to reproduce please!**

**Comment by Bartlomiejsz** [comment]
Hi @engcom-Alfa, as the code changes graphql modules, you got to request those invoices with the items using graphql. Also, please make sure that the order has no value in `discount_description` field in db.

Another way to check those changes is to simply add `_('Test translation');` anywhere in the code, in any controller, model etc. Using this class later will result in exception, and fixing method call by changing to `__('Test translation');` will again make it work

**Comment by engcom-Alfa** [comment]
Hi @Bartlomiejsz
Thanks for the above information. Well, tried to query the graphql request as like shown in below screenshot.

image

Invoices with/without _discount_description_ in the tables _sales_order_ & _sales_invoice_, responding with internal server error. Responding the same before fix case, and after PR fix case as well.
**Kindly help me replying with the exact query you are using to reproduce the issue in _2.4-develop_ version.**
Thanks in advance!

**Comment by bgorski** [comment]
@engcom-Alfa You are using a deprecated query. Which indeed doesn't work - thanks for letting me know, I'll create a separate PR for that. 
As for the issue reported here, please use the following steps:
0. As a precondition - use a Magento store in a language other than English and with a valid translation file translating the "Discount" phrase (having problems with that? See the bottom of this comment)
1. Create a cart price rule applying to all store views and all groups and with no coupon code (that's important!), no conditions and actions like 20 discount amount (effectively applying 20% off to all products in cart for everyone)
2. Register a customer and place an order in the admin panel for that customer 
3. Generate an invoice for that order
4. Use the following GraphQL mutation to generate the customer token:
```
mutation {
  generateCustomerToken(
    email: "your.customer@email.here"
    password: "your-password"
  ) {
    token
  }
}
```
5. Use the token from from the previous mutation to authorize the following query:
```
query {
    customer {
        orders {
            items {
                order_number
                grand_total
                status
                invoices {
                    id
                      items {
                          id
                          discounts {
                              amount {
                                value
                              }
                              label
                          }
                      }
                }
            }            
        }
    }
}
```
This will trigger the faulty behavior. 

What's important about this is that your Magento instance will probably have the `_('text here)` function defined. So on an English store you may not see any error, but the phrase inside won't be translated (in this context, the  `_('Discount')` call in `Magento\SalesGraphQl\Model\Resolver\Invoice\InvoiceItems` is a faulty attempt to translate the "Discount" word to the store language). If you want to be double sure about the faulty behavior, you need to edit the code of `Magento\SalesGraphQl\Model\Resolver\Invoice\InvoiceItems` and replace `_('Discount')` with `_('Discount')->render()`. Which will work for the indended `__('Discount')` function (the actual translation), but will throw an error for `_('Discount')`.

**Comment by engcom-Alfa** [comment]
Thank you so much for the detailed reproducible steps @bgorski !

:heavy_check_mark: QA Passed


**Manual testing scenario:**

1. Executed all the given steps as per the [above comment](https://github.com/magento/magento2/pull/33658#issuecomment-899136380). (Note- Even after non-rendered translated "Discount" phrase, I could able to reproduce using Arabic SA language)


**Before:** :heavy_multiplication_x: Getting an error for the GraphQL invoice details request.

image


**After:** :heavy_check_mark:  GraphQL invoice details request works as well as expected.

image

There is no other additional regression testing is required since it is a particular graphql request related issue.

**Comment by Bartlomiejsz** [comment]
@engcom-Alfa thank you for testing the PR
Regarding info about automated tests - I believe the PR was marked as `Auto-Tests: Not Required` for two reasons:
- my changes fixes really obvious mistakes done by initial code authors, so to test only my changes I would have to write something like `if (function_exists('__')) {...}` which makes no sense
- if on the other hand I would have to write test for whole functionality, that would mean that, to process the PR, I would have to create test for code that someone else created (with mistakes) and which was created without the tests, that as you're saying, are required

I won't be able to write test in any of those options, so if you will still believe that this is required, unfortunately this will have to be picked up by someone else...

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by bgorski** [comment]
@engcom-Alfa as for tests, what we're dealing with here is a function-level fix - a replacement of a faulty function with a correct one. This has no chance of regressing and also affects no other parts of the code because it doesn't change any data, only outputs a text. If we were to create a test for it, what we would really test is a basic core logic (if the correct `__('text here')` function works as it should), not anything really related to the logic of this graphql call - and we would need a rather complex test for it. Which means that we would increase the complexity of the testsuite, and that's also something we have to maintain (in this case we'd have a test that can regress that tests a functionality that can't).
This is why I marked this as something that doesn't require automated tests - I believe a manual one is enough here.

**Comment by engcom-Alfa** [comment]
Thanks you for the detailed information @Bartlomiejsz and @bgorski , I will process it for merging!

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Executed all the given steps as per the [above comment](https://github.com/magento/magento2/pull/33658#issuecomment-899136380). (Note- Even after non-rendered translated "Discount" phrase, I could able to reproduce using Arabic SA language)


**Before:** :heavy_multiplication_x: Getting an error for the GraphQL invoice details request.

image


**After:** :heavy_check_mark:  GraphQL invoice details request works as well as expected.

image

The actual response received is displayed below
`{
  "data": {
    "customer": {
      "orders": {
        "items": [
          {
            "order_number": "000000001",
            "grand_total": 69,
            "status": "Complete",
            "invoices": [
              {
                "id": "MQ==",
                "items": [
                  {
                    "id": "MQ==",
                    "discounts": []
                  }
                ]
              }
            ]
          },
          {
            "order_number": "000000002",
            "grand_total": 34,
            "status": "Processing",
            "invoices": []
          },
          {
            "order_number": "000000003",
            "grand_total": 1472.6,
            "status": "Complete",
            "invoices": [
              {
                "id": "Mg==",
                "items": [
                  {
                    "id": "Mg==",
                    "discounts": [
                      {
                        "amount": {
                          "value": 10
                        },
                        "label": "qqqq"
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "order_number": "000000004",
            "grand_total": 42.44,
            "status": "Pending",
            "invoices": []
          },
          {
            "order_number": "000000005",
            "grand_total": 66.44,
            "status": "Pending",
            "invoices": []
          },
          {
            "order_number": "000000006",
            "grand_total": 42.44,
            "status": "Processing",
            "invoices": [
              {
                "id": "Mw==",
                "items": [
                  {
                    "id": "Mw==",
                    "discounts": [
                      {
                        "amount": {
                          "value": 7.8
                        },
                        "label": "Discount"
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  }
}`

There is no other additional regression testing is required since it is a particular Graphql request related issue (Above [comment1](https://github.com/magento/magento2/pull/33658#issuecomment-899762760) and [comment2](https://github.com/magento/magento2/pull/33658#issuecomment-900671766) has more info on this)

**Comment by engcom-Alfa** [comment]
@magento create issue

**Pull request merged**
