### PR TITLE
magento/magento2#22568: Add an extension point to RateRequest in Magento\Quote\Model\Quote\Address::requestShippingRates

### PR DESCRIPTION
**Pull request by atwixfirster**
### Description (*)

PR fixes a problem described in issue https://github.com/magento/magento2/issues/22568.

### Fixed Issues (if relevant)

1. magento/magento2#22568: Add an extension point to RateRequest in requestShippingRates

Thank you!

### CODE REVIEW

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5003](https://jira.corp.magento.com/browse/ENGCOM-5003) has been created to process this Pull Request

**Review by orlangur — CHANGES_REQUESTED** [review]
@atwixfirster new events should not be added. Instead of this existing code should be refactored if it is not pluginizable.

**Comment by atwixfirster** [comment]
> @atwixfirster new events should not be added. Instead of this existing code should be refactored if it is not pluginizable.

Now, if I want to set a custom option to `$request` object I have to override a whole `Magento\Quote\Model\Quote\Address` class!!!

For example, my `etc/di.xml`:
```
<?xml version="1.0"?>
<config>
    <preference for="Magento\Quote\Model\Quote\Address" type="Vendor\Module\Model\Quote\Address" />
</config>
```

@orlangur , could you please clarify or provide the best solution for this problem?

Thank you in advance!

**Comment by dmytro-ch** [comment]
> @atwixfirster new events should not be added. Instead of this existing code should be refactored if it is not pluginizable.

Thank you @orlangur! This is a really good point, especially considering the principles that are also mentioned in [Magento 2 Technical Guidelines](https://devdocs.magento.com/guides/v2.2/coding-standards/technical-guidelines.html#14-events).

> 14.1. All values (including objects) passed to an event MUST NOT be modified in the event observer. Instead, plugins SHOULD BE used for modifying the input or output of a function.

**Comment by orlangur** [comment]
Existing extension points are good enough already, see issue comments for more details.

**Pull request closed without merging**
