### PR TITLE
Add Header (h1 - h6) tags to layout xml htmlTags Allowed types

### PR DESCRIPTION
**Pull request by furan917**
### Description (*)
The point of this PR is simply to allow H1 to H6 tags to be used in the layout XML as htmlTags so that users and theme creators can set titles with proper header tags using the XML. As an example a creator create a H2 container with a `Magento\Framework\View\Element\Text` block inside it to easily create titles where they need. 

### Manual testing scenarios (*)

1.add this block inside any referenceContainer you want

            <container name="some-title" htmlTag="h5" htmlClass="title">
                <block class="Magento\Framework\View\Element\Text" name="some.section.title">
                    <arguments>
                        <argument name="text" xsi:type="string">Your title here</argument>
                    </arguments>
                </block>
            </container>

2. Clear Cache and Reload page and see that the Header tag is now working and does not throw a container type not allowed error

### Questions or comments
I am not sure if there was a reason these weren't included so there may be something I am not thinking about but it seemed like it could be a helpful addition to devs and creators. 
This is my first time contributing to M2 so please let me know if something can be done better or if I have missed anything.

There is a failure in the code sniffer for the Container.php I have changed but these failures, I think, are not introduced by me?

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by furan917** [comment]
Static test build fails because the file does not match the set code standards before my editing it. 
Good news as they are all fixable by automation. Or simple Doc updates so wont be a blocker.

**Comment by furan917** [comment]
Hey @orlangur just looking to check if this is in review/needs further steps/further discussion or anything in case I can help with anything!

**Comment by orlangur** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@orlangur could you explain why this PR was moved to On hold and what is the current status?

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7038](https://jira.corp.magento.com/browse/ENGCOM-7038) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@furan917 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

**Before:**
before

**After:**
after

**Pull request merged**
