### PR TITLE
Prevent SOAP fault from using non built-in entities

### LINKED ISSUE #38189: SOAP API returns invalid XML when SOAP fault reason contains diacritics
### Preconditions and environment

Magento version 2.4.6-p3

### Steps to reproduce

1. Create a store and set locale to de_DE
2. Add some products
3. Use the SOAP API to add another product to the DE store using a url_key that already exists

### Expected result

The SOAP client reports the error message: **URL-Key für den ausgewählten Store existiert bereits.**

### Actual result

The SOAP client fails with the message **looks like we got no XML document**

### Additional information

The problem lies in the way the SOAP fault is created by Magento. In [Magento\Webapi\Model\Soap\Fault.php](https://github.com/magento/magento2/blob/f6d4542518bf01f7d3ceca330d7290de62afcb4e/app/code/Magento/Webapi/Model/Soap/Fault.php#L252) the XML that is sent back by the SOAP server is not created by using DOMDocument but by string manipulation.
The problematic code is:
`$reason = htmlentities($reason);`
Using htmlentities here will encode all entities and not just the XML built-in entities. The resulting XML cannot be parsed because it contains unknown entities. 
Instead we should use htmlspecialchars:
`$reason = htmlspecialchars($reason, ENT_XML1);` 

I will try to create a PR to change this in the code base.Until then using a patch will create a workaround

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by ainigma32**
### Description (*)

Instead of using `htmlentities()` to escape text used in an XML document we should use `htmlspecialchars()`
This will ensure that fault reasons containing diacritics will not result in invalid XML.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38189

### Manual testing scenarios (*)

1. Create a store and set the locale to de_DE
2. Create some products in that store
3. Use a SOAP client to add another product to the DE store using a url_key that already exists
4. The SOAP client should now return a valid SOAP fault with the correct error message: URL-Key für den ausgewählten Store existiert bereits.

### Questions or comments

I have added a new function to [the existing unit test](https://github.com/magento/magento2/blob/f6d4542518bf01f7d3ceca330d7290de62afcb4e/app/code/Magento/Webapi/Test/Unit/Model/Soap/FaultTest.php) but I am not sure if that is sufficient. Any feedback will be welcome.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ainigma32** [comment]
@magento run Unit Tests

**Comment by ainigma32** [comment]
@magento run all tests

**Comment by ainigma32** [comment]
@magento run all tests

**Comment by ainigma32** [comment]
@magento run Sample Data Tests CE,Sample Data Tests EE,Sample Data Tests B2B

**Comment by ainigma32** [comment]
Seems like the only tests that are failing have nothing to do with the changes in this PR

**Comment by ainigma32** [comment]
@magento run all tests

**Comment by ainigma32** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi @ainigma32,

As per this comment https://github.com/magento/magento2/issues/38189#issuecomment-1960805845 We are closing this PR.

Please feel free to reopen the PR.

Thanks.

**Pull request closed without merging**
