### PR TITLE
Removed CliCacheFlushActionGroup usage for CatalogSearch and other modules

### LINKED ISSUE #33531: [Issue] Removed CliCacheFlushActionGroup usage for CatalogSearch and other modules
This issue is automatically created based on existing pull request: magento/magento2#33530: Removed CliCacheFlushActionGroup usage for CatalogSearch and other modules

---------
### Description
Removed CliCacheFlushActionGroup usage for CatalogSearch, GroupedProduct, Newsletter, Paypal, Quote and Review modules.

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Removed CliCacheFlushActionGroup usage for CatalogSearch, GroupedProduct, Newsletter, Paypal, Quote and Review modules.

### Resolved issues:
1. [x] resolves magento/magento2#33531: Removed CliCacheFlushActionGroup usage for CatalogSearch and other modules

### CODE REVIEW

**Comment by sergiy-v** [comment]
@magento create issue

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Semantic Version Checker

**Review by andrewbess — APPROVED** [review]
Hello @sergiy-v 
Thank you for your contribution.
Changes are approved.
Waiting for finishing tests

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, thank you for the review.
[ENGCOM-9156](https://jira.corp.magento.com/browse/ENGCOM-9156) has been created to process this Pull Request
:eight_spoked_asterisk: @andrewbess, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE

**Comment by sergiy-v** [comment]
@magento run WebAPI Tests, Unit Tests, Static Tests, Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B, Magento Health Index, Integration Tests, Database Compare

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-9156](https://jira.corp.magento.com/browse/ENGCOM-9156) has been created to process this Pull Request

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @sergiy-v,

Thanks for your contribution.

I have run all of the MFTF test cases from this PR on my local environment and found that 15 Broken(warning), 5 Failed, 7 Successful. 

Can you please have a look on below warnings and errors.

Here is the Allure report for the same.
image

image

image

Also below are some of the common errors/warning I am getting.

image

image

image

image

image

Thank you in advance!

**Comment by eduard13** [comment]
Hi @engcom-Charlie, it looks more like a env setup issue. Could you please double check it?
Thank you.

**Comment by sergiy-v** [comment]
@magento run Integration Tests, Functional Tests CE

**Comment by sergiy-v** [comment]
Hello @engcom-Charlie,
Unfortunately I could not reproduce the errors you shared.
Please try one more time and in case of error provide a command how you are running MFTF tests.
Thank you!

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-9156](https://jira.corp.magento.com/browse/ENGCOM-9156) has been created to process this Pull Request

**Pull request merged**
