### PR TITLE
AppState emulateAreaCode was not respected by file collector

### LINKED ISSUE #29656: [Issue] AppState emulateAreaCode was not respected by file collector
This issue is automatically created based on existing pull request: magento/magento2#28917: AppState emulateAreaCode was not respected by file collector

---------
### Preconditions (*)

Magento 2.4-develop

The "hack" to emulate an area code via AppState->emulateAreaCode() is not respected by the base file collector. The consequence is that *.xml file in the emulated area is not found by the file collector.  

### Steps to reproduce (*)
The problem occurs in an extension I have built that require to access the adminhtml area from the graphql area. There are likely other modules in the Magento 2 that suffers from the same problem. However I can not point one such module without spending a considerable amount of time searching for it.  

The following snippet suffer from this bug,  
```
$data = $this->app_state->emulateAreaCode(   
  \Magento\Framework\App\Area::AREA_ADMINHTML,   
  [$this, "getDataSourceData"],  
  [$field, $args]
);  
```

1. Create simple CLI command.
2. Create `\Magento\Framework\View\File\Collector\Base` with param `['subDir' => 'ui_component']`.

> $baseFileCollector = $objectManager->create(Base::class, ['subDir' => 'ui_component']);

3. Emulates callback inside `adminhtml` area.
> $adminAreaEmulate = $objectManager->create(EmulatedAdminhtmlAreaProcessor::class);
> $adminAreaEmulate->process([$baseFileCollector, 'getFiles'], [$theme, '*']); 

**Actual Result**: 
As result, we have files only from `base` area.
`view/base/ui_component/*`

**Expected Result:**
As result, we have files from `base` and `adminhtml` areas.
`view/base/ui_component/*`
`view/adminhtml/ui_component/*`
### Questions or comments
I thinks someone more knowledgable should look into this issue. I have troubleshooted and my conclusions are as follows.  
  
The base file collector is accessing the area code of the Theme with a call to getData('area').  
The Theme has an override called getArea(), this method is never called by the base file collector.
This causes problems for modules that use "emulated area codes" via the   
\Magento\Framework\App\State->emulateAreaCode() method.
The emulated area code is then not respected by the file collector since it access the data directly and not via the intended getArea() method in the Theme.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by johan-lindahl**
### Description (*)
The "hack" to emulate an area code via AppState->emulateAreaCode() is not respected by the base file collector. The consequence is that *.xml file in the emulated area is not found by the file collector.  

### Manual testing scenarios (*)
The problem occurs in an extension I have built that require to access the adminhtml area from the graphql area. There are likely other modules in the Magento 2 that suffers from the same problem. However I can not point one such module without spending a considerable amount of time searching for it.  

The following snippet suffer from this bug,  
```
$data = $this->app_state->emulateAreaCode(   
  \Magento\Framework\App\Area::AREA_ADMINHTML,   
  [$this, "getDataSourceData"],  
  [$field, $args]
);  
```
### Questions or comments
I thinks someone more knowledgable should look into this issue. I have troubleshooted and my conclusions are as follows.  
  
The base file collector is accessing the area code of the Theme with a call to getData('area').  
The Theme has an override called getArea(), this method is never called by the base file collector.
This causes problems for modules that use "emulated area codes" via the   
\Magento\Framework\App\State->emulateAreaCode() method.
The emulated area code is then not respected by the file collector since it access the data directly and not via the intended getArea() method in the Theme.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29656: AppState emulateAreaCode was not respected by file collector

### CODE REVIEW

**Comment by johan-lindahl** [comment]
@magento run all tests

**Comment by johan-lindahl** [comment]
@magento run all tests

**Comment by gwharton** [comment]
I dont know if it is related, but I when running bin/magento console apps that emulate AREA_FRONTEND, the /etc/view.xml file is not read from your theme when you attempt to do anything theme related, e.g simply getting the viewConfig item results in a merged object of all enabled modules etc/view.xml but the content from the themes view.xml is missing.

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-8130](https://jira.corp.magento.com/browse/ENGCOM-8130) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Bravo** [comment]
Dev experience is required for testing of this PR. Please note that Manual testing has not been performed.

**Comment by engcom-Charlie** [comment]
:heavy_check_mark: **QA Passed**
Checked by the following steps:

1. Create simple CLI command.
2. Create `\Magento\Framework\View\File\Collector\Base` with param `['subDir' => 'ui_component']`.

> $baseFileCollector = $objectManager->create(Base::class, ['subDir' => 'ui_component']);

3. Emulates callback inside `adminhtml` area.
> $adminAreaEmulate = $objectManager->create(EmulatedAdminhtmlAreaProcessor::class);
> $adminAreaEmulate->process([$baseFileCollector, 'getFiles'], [$theme, '*']); 


**Before**: 
As result, we have files only from `base` area.

**After**
As result, we have files from `base` and `adminhtml` areas.

**Comment by richjoregonstate** [comment]
@johan-lindahl @lenaorobei 

It looks like this fix has a few more consequences then intended. My team just finished an upgrade from 2.3 -> 2.4.3 (enterprise) and we now get an "Area code not set" any time we run a cli command. Upon investigation we found that the change from `$area = $theme->getData('area');` to `$area = $theme->getArea();` was the root of the issue.

The large difference between the two is that `$theme->getData('area');` can return `null` while `$theme->getArea();` can't. Instead  it throws "Area code not set". When `$theme->getData('area');` returns `null`, in 2.4.2 and later, nothing happens as the file path it looks at doesn't exist* and the `$result` is unaffected. However in 2.4.3 this behavior is no longer preserved. 

I do believe that the switch to `$theme->getArea();` is the right move, however in order to preserve the original behavior of the function the second `collectFilesWithContext` block should be wrapped in a try-catch block, that throws a warning instead of erroring out completely. A-la:
```php
try {
    $area = $theme->getArea();
    $themeFiles = $this->componentDirSearch->collectFilesWithContext(
        ComponentRegistrar::MODULE,
        "view/{$area}/{$this->subDir}{$filePath}"
    );
    foreach ($themeFiles as $file) {
        $result[] = $this->fileFactory->create($file->getFullPath(), $file->getComponentName());
    }
}
catch (\Magento\Framework\Exception\LocalizedException $e ) {
   ...  // Warning area code not set
} // Otherwise fail normally 

```

*The file path looks like "view//{$this->subDir}{$filePath}" which is invalid due to "//".

**Comment by devetus** [comment]
We are experiencing the same issue "Area code is not set" while updating modules during the upgrade from 2.3.6->2.4.3-p1

**Comment by hostep** [comment]
@devetus: I'm going to guess that your problem might get fixed by: https://github.com/magento/magento2/pull/33726

**Comment by devetus** [comment]
@hostep thanks, that worked like a charm in my case, without extra try-catch block.

**Pull request merged**
