### PR TITLE
Resolve "New Accounts Report" should disable the sort ability of "New Account" columns (because it can not run) #25033

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#25033: "New Accounts Report" should disable the sort ability of "New Account" columns (because it can not run) 

### Fixed Issues (if relevant)

1. magento/magento2#25033: "New Accounts Report" should disable the sort ability of "New Account" columns (because it can not run) 

### Manual testing scenarios (*)

1. Go to backend
2. Reports-> Customers-> New
3. Show report
4. Click "New Account" column
=> Disable sort, no reload page

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello @edenduong,
did you investigate the reason why the sorting does not work for customer report grids?
It might be possible to fix the not working sort order for customer reports collections.

Thank you!

**Comment by edenduong** [comment]
Hi @dmytro-ch : the main reason is all the report in the magento backend can not be sort too.
The second reason is Some record are string like “No record found ...”, some record are the number (1,2,3...) so I think it is not the same data type and can not be sortable.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6104](https://jira.corp.magento.com/browse/ENGCOM-6104) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Foxtrot** [comment]
Covering

**Pull request merged**
