### PR TITLE
Product Media Gallery GQL response is sorted by image position

### LINKED ISSUE #37671: Product Media Gallery GQL response is not sorted by image position
### Preconditions and environment

- Magento version: 2.4-develop

### Steps to reproduce

1. Edit the prdouct
2. Add images
3. Save it
4. edit the same product and this time drag the last image to the very first
5. save the productproduct

### Expected result

GraphQl response should return the gallery sorted by their position.

### Actual result

Gallery images are sorted by their IDs.

### Additional information

Use this Query:

````
{
  products(filter: { sku: { eq: "24-MB01" } }) {
    items {
      name
      sku
      url_key
      stock_status
      media_gallery {
              __typename
              ... on ProductVideo {
                video_content {
                  video_url
                  video_title
                  __typename
                }
                __typename
              }
              ... on ProductImage {
                url
                __typename
              }
            }
    }
    total_count
    page_info {
      page_size
    }
  }
}

````

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Kannakiraj123**
### Description (*)
Product Media Gallery GQL response is sorted by image position

### Related Pull Requests
I added usort function to gallery array in resolver function

### Fixed Issues (if relevant)

1. Fixes #37671 

### Manual testing scenarios (*)
1.Edit the prdouct
2.Add images
3.Save it
4.edit the same product and this time drag the last image to the very first
5.save the product

**Use this Query for check media gallery:**

```
{
  products(filter: { sku: { eq: "24-MB01" } }) {
    items {
      name
      sku
      url_key
      stock_status
      media_gallery {
              __typename
              ... on ProductVideo {
                video_content {
                  video_url
                  video_title
                  __typename
                }
                __typename
              }
              ... on ProductImage {
                url
                __typename
              }
            }
    }
    total_count
    page_info {
      page_size
    }
  }
}
```

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Kannakiraj123** [comment]
@magento run all tests

**Comment by Kannakiraj123** [comment]
@magento run all tests

**Comment by Kannakiraj123** [comment]
@magento run all tests

**Comment by Kannakiraj123** [comment]
@magento run all tests

**Comment by thiaramus** [comment]
This issue is under development by an internal team. The fix will be delivered to the mainline according to our processes once done, and the status of this issue will be updated. If there are any incomplete Pull Requests to this issue and the community code will be re-used, all original commits will be preserved.

**Pull request merged**
