### PR TITLE
Update AddDataForPoland.php in module-directory

### LINKED ISSUE #30933: [Issue] Update AddDataForPoland.php in module-directory
This issue is automatically created based on existing pull request: magento/magento2#30930: Update AddDataForPoland.php in module-directory

---------
Update typo on a comment at the top of the file. From "PLYING.txt" to "COPYING.txt"

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by samuel27m**
Update typo on a comment at the top of the file. From "PLYING.txt" to "COPYING.txt"

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30933: Update AddDataForPoland.php in module-directory

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8471](https://jira.corp.magento.com/browse/ENGCOM-8471) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE, Functional Tests EE, WebAPI Tests

**Pull request closed without merging**
