### PR TITLE
[32027] Marked Framework interfaces as API part 4

### LINKED ISSUE #32027: Mark Framework interfaces as API part 4
The following interfaces should be marked as API in 2.4-develop branch

1. lib/internal/Magento/Framework/Encryption/Adapter/EncryptionAdapterInterface.php
1. lib/internal/Magento/Framework/Event/ConfigInterface.php
1. lib/internal/Magento/Framework/Event/InvokerInterface.php
1. lib/internal/Magento/Framework/Event/ManagerInterface.php
1. lib/internal/Magento/Framework/Exception/TemporaryStateExceptionInterface.php
1. lib/internal/Magento/Framework/Filesystem/Directory/PathValidatorInterface.php
1. lib/internal/Magento/Framework/Filesystem/DriverPoolInterface.php
1. lib/internal/Magento/Framework/Filesystem/File/ReadInterface.php
1. lib/internal/Magento/Framework/Filter/DirectiveProcessor/FilterInterface.php
1. lib/internal/Magento/Framework/Filter/DirectiveProcessorInterface.php
1. lib/internal/Magento/Framework/Filter/FactoryInterface.php
1. lib/internal/Magento/Framework/Filter/FilterManager/ConfigInterface.php
1. lib/internal/Magento/Framework/Filter/SimpleDirective/ProcessorInterface.php
1. lib/internal/Magento/Framework/Filter/VariableResolverInterface.php

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixes https://github.com/magento/magento2/issues/32027

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/32027

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Review by coderimus — APPROVED** [review]
Hello @Usik2203 
Thank you for the adjustments. 👍

**Comment by magento-engcom-team** [comment]
Hi @coderimus, thank you for the review.
[ENGCOM-8765](https://jira.corp.magento.com/browse/ENGCOM-8765) has been created to process this Pull Request

**Comment by Usik2203** [comment]
@magento run Database Compare

**Comment by gabrieldagama** [comment]
Closed in favour of https://github.com/magento/magento2/pull/32728

**Pull request closed without merging**
