### PR TITLE
#28270 Showed tier price for pre selected swatch via cart edit

### LINKED ISSUE #28270: Configurable product with swatches, doesn't show tier pricing when clicking edit in cart OR when active swatch set with url hash
### Preconditions (*)

1. Magento 2.3.5

### Steps to reproduce (*)

1. Create a configurable product with swatch options
2. Add tier prices to one of the options
3. Go to configurable product PDP 
4. Select the tier price product
5. Add the product to cart
6. Click on edit button from mini cart/ cart page
7. Check the tier price is not shown on edit product page
8. Load the page with #attribute_id=value_id to preset the swatch value

### Expected result (*)

1. Tier price block should show

### Actual result (*)

1. Tier price does not show

### Solution (*)

The issue lies in file;
`/vendor/magento/module-swatches/view/base/web/js/swatch-renderer.js`

The function _UpdatePrice: function () { has a dependency on if this.options.tierPriceTemplate being defined on hashed options being set on load, which it isnt.

Here's the change to ensure it gets defined;

Before:

```
_UpdatePrice: function () {
        var $widget = this,
            $product = $widget.element.parents($widget.options.selectorProduct),
            $productPrice = $product.find(this.options.selectorProductPrice),
            result = $widget._getNewPrices(),
            tierPriceHtml,
            isShow;

        $productPrice.trigger(
            'updatePrice',
            {
                'prices': $widget._getPrices(result, $productPrice.priceBox('option').prices)
            }
        );

        isShow = typeof result != 'undefined' && result.oldPrice.amount !== result.finalPrice.amount;

        $product.find(this.options.slyOldPriceSelector)[isShow ? 'show' : 'hide']();

        if (typeof result != 'undefined' && result.tierPrices && result.tierPrices.length) {
            if (this.options.tierPriceTemplate) {
                tierPriceHtml = mageTemplate(
                    this.options.tierPriceTemplate,
                    {
                        'tierPrices': result.tierPrices,
                        '$t': $t,
                        'currencyFormat': this.options.jsonConfig.currencyFormat,
                        'priceUtils': priceUtils
                    }
                );
                $(this.options.tierPriceBlockSelector).html(tierPriceHtml).show();
            } 

```
After;

```
_UpdatePrice: function () {
        var $widget = this,
            $product = $widget.element.parents($widget.options.selectorProduct),
            $productPrice = $product.find(this.options.selectorProductPrice),
            result = $widget._getNewPrices(),
            tierPriceHtml,
            isShow;

        $productPrice.trigger(
            'updatePrice',
            {
                'prices': $widget._getPrices(result, $productPrice.priceBox('option').prices)
            }
        );

        isShow = typeof result != 'undefined' && result.oldPrice.amount !== result.finalPrice.amount;

        $product.find(this.options.slyOldPriceSelector)[isShow ? 'show' : 'hide']();

        if (typeof result != 'undefined' && result.tierPrices && result.tierPrices.length) {
            // ADDED HERE
            if (this.options.tierPriceTemplate = $(this.options.tierPriceTemplateSelector).html()) {
                tierPriceHtml = mageTemplate(
                    this.options.tierPriceTemplate,
                    {
                        'tierPrices': result.tierPrices,
                        '$t': $t,
                        'currencyFormat': this.options.jsonConfig.currencyFormat,
                        'priceUtils': priceUtils
                    }
                );
                $(this.options.tierPriceBlockSelector).html(tierPriceHtml).show();
            }
```

Additional information
more detailed steps and screens #28270 ([Comment](https://github.com/magento/magento2/issues/28270#issuecomment-648931001))

### PR DESCRIPTION
**Pull request by srsathish92**
### Description (*)
This PR helps to assign `tierPriceTemplate` value before `swatch.initialized` trigger.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#28270

### Manual testing scenarios (*)
please check #28270

### Related Pull Requests
MFTF changes for B2B version:
- https://github.com/magento/partners-magento2b2b/pull/193

### Questions or comments
N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by srsathish92** [comment]
@magento run all tests

**Review by krzksz — CHANGES_REQUESTED** [review]
Hey! Thanks for your contribution! Please fix the static tests, they seem to be not related to your changes but since you are touching the file, you have to fix it.

**Comment by srsathish92** [comment]
@krzksz I have fixed static test, can please review now?

**Review by krzksz — APPROVED** [review]
Great work, thanks! Since this doesn't change any existing logic and all functional tests are passing then I would say we don't require any additional tests.

**Comment by krzksz** [comment]
On the other hand, @srsathish92 do you think you would be able to write an E2E test that goes through reproduction steps outlined in https://github.com/magento/magento2/issues/28270?

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-7845](https://jira.corp.magento.com/browse/ENGCOM-7845) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1.Create a configurable product with swatch options;
2. Add tier prices to one of the options;

Screenshot from 2020-07-16 13-41-19

3. Go to configurable product PDP;
4. Select the tier price product;

**Actual Result:** :heavy_check_mark: Tier price is shown for selected swatches 



5. Add the product to cart;
6. Click on edit button from mini cart/ cart page;
7. Check that the tier prices are shown on edit product page;

**Before:** :heavy_multiplication_x: Tier prices do not show



**After:** :heavy_check_mark: Tier price block is shown

**Comment by engcom-Kilo** [comment]
Working with MFTF test.

**Comment by engcom-Kilo** [comment]
@magento run Functional Tests B2B, @magento run Functional Tests EE, @magento run Functional Tests CE

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Pull request merged**
