### PR TITLE
Update README.md

### LINKED ISSUE #33247: [Issue] Update README.md
This issue is automatically created based on existing pull request: magento/magento2#33169: Update README.md

---------
- Added **" • "** before **Magento System Requirements** Link to give generalize look to : `Magento System Requirements`, `Install Magento`, `Learn About GraphQL in Magento 2` these all **3** sections.

- Removed **full stops**(.) from **Magento System Requirements** and **Install Magento** Links.

- Replaced `Learn More About GraphQL in Magento 2` with `Learn About GraphQL in Magento 2` as this section is providing a link for **GraphQL Developer Guide**.

- As **Contribution Guide** is common for all versions at **DevDocs**, changed the link for the same from [https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html) to [https://devdocs.magento.com/contributor-guide/contributing.html](https://devdocs.magento.com/contributor-guide/contributing.html)

- Changed [https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#report](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#report) this link with [https://devdocs.magento.com/contributor-guide/contributing.html#report](https://devdocs.magento.com/contributor-guide/contributing.html#report) as before one was not redirecting to **Report an issue** section in **DevDocs**

- Added this line : **To open an issue, click here**, in New line.

- Changed [https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#labels](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#labels) this link with [https://devdocs.magento.com/contributor-guide/contributing.html#labels](https://devdocs.magento.com/contributor-guide/contributing.html#labels) as before one was not redirecting to **Labels applied by the Community Engineering team** section in **DevDocs**

- Added updated link for **Slack channels**, Which will redirect the user to the **Slack Application** instead of opening the Slack channel in the browser. If the user is not having a Slack Application, then the **Slack channel** will open in the browser. The purpose is to gain more traffic on the Slack Channel.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by manavluhar**
- Added **" • "** before **Magento System Requirements** Link to give generalize look to : `Magento System Requirements`, `Install Magento`, `Learn About GraphQL in Magento 2` these all **3** sections.

- Removed **full stops**(.) from **Magento System Requirements** and **Install Magento** Links.

- Replaced `Learn More About GraphQL in Magento 2` with `Learn About GraphQL in Magento 2` as this section is providing a link for **GraphQL Developer Guide**.

- As **Contribution Guide** is common for all versions at **DevDocs**, changed the link for the same from [https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html) to [https://devdocs.magento.com/contributor-guide/contributing.html](https://devdocs.magento.com/contributor-guide/contributing.html)

- Changed [https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#report](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#report) this link with [https://devdocs.magento.com/contributor-guide/contributing.html#report](https://devdocs.magento.com/contributor-guide/contributing.html#report) as before one was not redirecting to **Report an issue** section in **DevDocs**

- Added this line : **To open an issue, click here**, in New line.

- Changed [https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#labels](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#labels) this link with [https://devdocs.magento.com/contributor-guide/contributing.html#labels](https://devdocs.magento.com/contributor-guide/contributing.html#labels) as before one was not redirecting to **Labels applied by the Community Engineering team** section in **DevDocs**

- Added updated link for **Slack channels**, Which will redirect the user to the **Slack Application** instead of opening the Slack channel in the browser. If the user is not having a Slack Application, then the **Slack channel** will open in the browser. The purpose is to gain more traffic on the Slack Channel.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#33247: Update README.md

### CODE REVIEW

**Comment by manavluhar** [comment]
@magento run all tests

**Review by bgorski — APPROVED** [review]

**Comment by bgorski** [comment]
This PR modifies only the README.md file, therefore failed checks for Database Compare and Functional Tests EE are not relevant.

**Comment by magento-engcom-team** [comment]
Hi @bgorski, thank you for the review.
[ENGCOM-9120](https://jira.corp.magento.com/browse/ENGCOM-9120) has been created to process this Pull Request
:eight_spoked_asterisk: @bgorski, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by sdzhepa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
Hi All,

The PR request has a update related to the README.md file content updates (majorly related to styling correction).

Tried to access all the replaced links, noticed accurate links have been updated; There is no broken links.

There is **no other manual testing is required** in this case, and there is no impact of any other features.
Hence marking it with _Merge In Progress_.

Thanks for the contribution!

**Pull request merged**
