### PR TITLE
Making backend load general locale by default.

### PR DESCRIPTION
**Pull request by ghost**
Fixes issue [#2465](https://github.com/magento/magento2/issues/2465)

Backend was not loading "General Locale" and with it the login page not translate.

Thanks

### CODE REVIEW

**Comment by Vinai** [comment]
Thanks for the contribution! We will need to wait for the travis build authentication to be in place for the tests to pass, then we can continue processing your PR.

**Comment by vancoz** [comment]
Hello @labofidea, please merge latest from develop and rerun builds.

**Comment by ghost** [comment]
@vancoz,  merge done.

**Comment by vancoz** [comment]
@labofidea, thank you, can you also fix indentation in your changes?

**Comment by ghost** [comment]
@vancoz, indentation fixed.

**Comment by vancoz** [comment]
@labofidea thank you, internal ticket - MAGETWO-47940

**Comment by vancoz** [comment]
@labofidea thank you, internal ticket - MAGETWO-47940

**Pull request merged**
