### PR TITLE
15963 fix issue imported configurable

### PR DESCRIPTION
**Pull request by krnshah**
### Description (*)

Imported Configurable Products Don't Retain Type Without Children/Configurations.

### Fixed Issues (if relevant)

1. magento/magento2 #15963: Imported Configurable Products Don't Retain Type Without Children/Configurations

### Manual testing scenarios (*)

1. Backend -> Catalog->Product->Add product as configurable product and don't assign configurable product.(It should save as configurable product instead of simple product)
2. Backend -> Store->Import->Set entity type to Product. add csv file with product type configurable product, don't add configurable attribute.(It should save as configurable product instead of simple product)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @krnshah. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
Hi @krnshah. You have already created PR with the fix (https://github.com/magento/magento2/pull/19801). Could you provide more information about purpose of this PR?

**Comment by krnshah** [comment]
Hi @rogyar , By mistake i have add other commit in this branch that is why i have created new branch and another pull request. So no purpose of this PR ( #19801 ) and closed it already.

**Review by orlangur — CHANGES_REQUESTED** [review]
This is obviously not a "fix" but removal of existing functionality. Checking if reported issue is valid at all.

**Comment by krnshah** [comment]
Hi @orlangur 

Any update on this?

**Comment by sivaschenko** [comment]
Hi @krnshah thanks for the pull request. I don't think eliminating the type transition processing is a proper way to fix it.

I think removing the `configurable` `compatibleTypes`  argument from `Magento\Catalog\Model\Product\TypeTransitionManager` in `/Users/sivashch/Projects/m2ce/app/code/Magento/ConfigurableProduct/etc/di.xml` is more proper fix for the issue.

However, as @orlangur mentioned, the actual behavior looks to me more like a feature that was intentionally designed and implemented then an issue.

**Comment by sivaschenko** [comment]
The issue https://github.com/magento/magento2/issues/15963 need to be confirmed before processing this PR

**Comment by sivaschenko** [comment]
Hi @krnshah according to PO comment in the issue https://github.com/magento/magento2/issues/15963#issuecomment-455622746 it is a designed system behaviour. So I am closing this pull request. Feel free to reach me if you have any questions or comments.

**Pull request closed without merging**
