### PR TITLE
added Customer Firstname and LastName for newsLetter subscription

### PR DESCRIPTION
**Pull request by mohith-ecommerce**
### Description (*)

"Customer First Name" and "Customer Last Name" should display empty instead of "----" in Newsletter Subscribers for logged in users
### Fixed Issues (if relevant)

1. magento/magento2#25057:"Customer First Name" and "Customer Last Name" should display empty instead of "----" in Newsletter Subscribers

### Manual testing scenarios (*)

1.subscribed for news letter subscription as logged in user as well as guest
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rodrigowebjump** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [new Magento instance](https://pr-25117.instances.magento-community.engineering).
Admin access: [https://pr-25117.instances.magento-community.engineering/admin](https://pr-25117.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by ihor-sviziev** [comment]
Hi @mohith227,
Actually data will not be saved anywhere as there is no fields in DB:
https://github.com/magento/magento2/blob/71b0142a12e33b1d08a9de977dfd36e1e16cd79c/app/code/Magento/Newsletter/etc/db_schema.xml#L10-L39

**Comment by mohith-ecommerce** [comment]
@ihor-sviziev ya I agree that but we need to show the customer first name and last name in the grid so I am making use of the customer id that is saved in the DB and displaying their first and last name

**Comment by ihor-sviziev** [comment]
> @ihor-sviziev ya I agree that but we need to show the customer first name and last name in the grid so I am making use of the customer id that is saved in the DB and displaying their first and last name

Ok, but how method `subscribe` relates to subscribers grid if value isn't stored in DB?

**Comment by mohith-ecommerce** [comment]
@ihor-sviziev in method subscribe we getting customer object based on the id so I am making use of that to get customer first and last name

**Comment by rodrigowebjump** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [new Magento instance](https://pr-25117.instances.magento-community.engineering).
Admin access: [https://pr-25117.instances.magento-community.engineering/admin](https://pr-25117.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rodrigowebjump** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [Magento instance](https://i-25117-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25117-2-3-develop.instances.magento-community.engineering/admin](https://i-25117-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rodrigowebjump** [comment]
Hi @mohith227 Thanks for your pull request.

I am closing the PR since it not address the issue properly.
Please review the issue details. Try to check the file /view/adminhtml/layout/newsletter_subscriber_block.xml inside Newsletter module.

Regards

**Pull request closed without merging**
