### PR TITLE
Implemented skipping price indexation process on `catalogrule_product` indexer, when there is no active catalog rule

### LINKED ISSUE #34784: Very slow `catalogrule_product` index even when no catalog rule exists
On a Magento 2.4.3 instance:
- I don't have any catalog rule
- I have ~100k products, mostly configurable
- I have 4 websites
- Have almost all my indexes setup on scheduled mode

### Steps to reproduce (*)

1. Add some ids (or update some product attributes) into `catalogrule_product_cl` table.
2. Run `indexer_update_all_views` CRON job.

### Expected result (*)

1. Product ids quantity should not have that big impact in index processing time.
2. The index process should end in a reasonable time.

### Actual result (*)

1. Product ids quantity is brutally impacting execution time.
2. Index process should end in a moment, when no catalog rule is set.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by dudzio12**
Implemented skipping price indexation process on `catalogrule_product` indexer, when there is no active catalog rule

### Description (*)

This is a fast fix for specific situation, when `catalogrule_product` index is on schedule mode and there is no active catalog rule to index. That problems enlarges on M2 instanced with large amount of products and dynamic data.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#34784

### Manual testing scenarios (*)

1. Add some ids (or update some product attributes) into catalogrule_product_cl table.
2. Run indexer_update_all_views CRON job.
3. Catalog rule index data should be valid.

Retry steps with active catalogrule and when catalog rule is marked from active to inactive and vice versa. 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by dudzio12** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@dudzio12 what will happen in case we had active rules and the index was built according to them, then all rules became inactive? According to the changes, there is no reindex operation will be performed and data in the index will be incorrect. Am I missing something?

**Comment by dudzio12** [comment]
> @dudzio12 what will happen in case we had active rules and the index was built according to them, then all rules became inactive? According to the changes, there is no reindex operation will be performed and data in the index will be incorrect. Am I missing something?

It will be cleared when clean action is executed just above if statement I've added ;)

**Comment by dudzio12** [comment]
@magento run all tests

**Comment by dudzio12** [comment]
Failed test is not related to this PR

**Pull request closed without merging**
