### PR TITLE
#29089 : GraphQL: category & categoryList query return wrong image url

### LINKED ISSUE #29089: GraphQL: category & categoryList query return wrong image url
The `category` & `categoryList` query return wrong image URL on an upgraded instance (from 2.3.4 to 2.3.5).

For example - GraphQl result:

```
{
  "id": 34,
  "url_path": "venia-dresses",
  "image": "https://cif-enablement-s4n4tla-o24f6fbtz7p34.demo.magentosite.cloud/index.php/media/catalog/category/timeless.jpg"
}
```
URL is wrong and resolves into 404. Correct URL should be without `/index.php` like `https://cif-enablement-s4n4tla-o24f6fbtz7p34.demo.magentosite.cloud/media/catalog/category/timeless.jpg`

### Preconditions (*)

1. Magento 2.3.5, upgraded from 2.3.4
2.

### Steps to reproduce (*)

1. Setup Magento 2.3.4
2. Install Venia sample data like described on the docs
3. Upgrade to Magento 2.3.5
4. Query for categories which have an image, both `category` & `categoryList` returns wrong image URL

### Expected result (*)

1. Correct Image URL
2.

### Actual result (*)

1. Wrong image URL, see above
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by konarshankar07**
### Description (*)

This PR will fix the issue with the category image URL if the url rewrite is disabled in magento
### Fixed Issues (if relevant)

Fixes https://github.com/magento/magento2/issues/29089

### Manual testing scenarios (*)

Make sure the url rewrite is disabled in Magento 

Run following query
```
 {
  category(id: 24) {
    image
  }
}
```
### Expected Result
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by konarshankar07** [comment]
@magento run all tests

**Comment by rogyar** [comment]
Hi @konarshankar07. Looks good to me. Could you cover your fix with an API-functional test, please? 

Thanks

**Comment by rogyar** [comment]
Related issue: https://github.com/magento/magento2/issues/29089

**Comment by konarshankar07** [comment]
Hello @rogyar ..
Someone else has already fixed this issue in https://github.com/magento/magento2/pull/30689 PR but didn't cover the changes with the tests. Should we close this PR or Do I need to write the test for this fix?
Thanks

**Comment by rogyar** [comment]
Hi @konarshankar07. You may write the coverage within the scope of the current PR. Thank you!

**Comment by rogyar** [comment]
I mean, It's not necessary to close this one and open a new one. You can change the title and description of this PR and provide the test

**Pull request closed without merging**
