### PR TITLE
UPS Option to include TAX in rate

### PR DESCRIPTION
**Pull request by gwharton**
The current UPS Module uses the UPS Rate excluding TAX to use as the rate charged to the customer during checkout.

This modification adds an additional config option so you can choose whether to request and include TAX information from UPS in the rate or not.

This modification is especially useful for businesses who are not TAX registered and cannot claim back the TAX charged by UPS. This allows them to pass on the TAX costs to the customer as part of the overall shipping rate.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=11707) <br/>All committers have signed the CLA.

**Comment by gwharton** [comment]
I branched 2.2-develop for this fix, but if approved can it be merged into 2.3-develop aswell so future releases get the changes.

**Comment by misha-kotov** [comment]
Hi @gwharton , thanks for your contribution. A couple things: 
- `Include TAX in Rate` should be changed to `Include Tax in Rate` in the admin panel configuraitons
- Can you clarify where in the admin panel config this new setting would appear? 
- What's name of the new response field that will be returned in addition to the existing `GrandTotal` ?

**Comment by gwharton** [comment]
The admin panel setting appears below the "Enable Negotiated Rates" setting, but only when UPS Type is set to "United Parcel Service XML". Getting TAX information (and negotiated rates) are not supported in the non XML service type. 

screenshot 16

**Comment by gwharton** [comment]
Here are the responses received for the following combinations with negotiated rates set

For a UK-UK shipment (taxes applicable)

Include Tax in rate = NO

```
    <NegotiatedRates>
      <NetSummaryCharges>
        <GrandTotal>
          <CurrencyCode>GBP</CurrencyCode>
          <MonetaryValue>9.35</MonetaryValue>
        </GrandTotal>
      </NetSummaryCharges>
    </NegotiatedRates>
```

Include Tax in rate = YES

```
    <NegotiatedRates>
      <TaxCharges>
        <Type>VAT</Type>
        <MonetaryValue>1.87</MonetaryValue>
      </TaxCharges>
      <NetSummaryCharges>
        <GrandTotal>
          <CurrencyCode>GBP</CurrencyCode>
          <MonetaryValue>9.35</MonetaryValue>
        </GrandTotal>
        <TotalChargesWithTaxes>
          <CurrencyCode>GBP</CurrencyCode>
          <MonetaryValue>11.22</MonetaryValue>
        </TotalChargesWithTaxes>
      </NetSummaryCharges>
    </NegotiatedRates>
```

For a UK-USA shipment (taxes NOT applicable)

Include Tax in rate = NO

```
    <NegotiatedRates>
      <NetSummaryCharges>
        <GrandTotal>
          <CurrencyCode>GBP</CurrencyCode>
          <MonetaryValue>44.37</MonetaryValue>
        </GrandTotal>
      </NetSummaryCharges>
    </NegotiatedRates>
```

Include Tax in rate = YES

```
    <NegotiatedRates>
      <NetSummaryCharges>
        <GrandTotal>
          <CurrencyCode>GBP</CurrencyCode>
          <MonetaryValue>44.37</MonetaryValue>
        </GrandTotal>
      </NetSummaryCharges>
    </NegotiatedRates>
```

**Comment by gwharton** [comment]
And the same responses received without negotiated rates set

For a UK-UK shipment (taxes applicable)

Include Tax in rate = NO

```
    <TransportationCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>6.45</MonetaryValue>
    </TransportationCharges>
    <ServiceOptionsCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>0.00</MonetaryValue>
    </ServiceOptionsCharges>
    <TotalCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>6.45</MonetaryValue>
    </TotalCharges>
```

Include Tax in rate = YES

```
    <TransportationCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>6.45</MonetaryValue>
    </TransportationCharges>
    <ServiceOptionsCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>0.00</MonetaryValue>
    </ServiceOptionsCharges>
    <TaxCharges>
      <Type>VAT</Type>
      <MonetaryValue>1.29</MonetaryValue>
    </TaxCharges>
    <TotalCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>6.45</MonetaryValue>
    </TotalCharges>
    <TotalChargesWithTaxes>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>7.74</MonetaryValue>
    </TotalChargesWithTaxes>
```

For a UK-USA shipment (taxes NOT applicable)

Include Tax in rate = NO

```
    <TransportationCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>35.16</MonetaryValue>
    </TransportationCharges>
    <ServiceOptionsCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>0.00</MonetaryValue>
    </ServiceOptionsCharges>
    <TotalCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>35.16</MonetaryValue>
    </TotalCharges>
```

Include Tax in rate = YES

```
    <TransportationCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>35.16</MonetaryValue>
    </TransportationCharges>
    <ServiceOptionsCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>0.00</MonetaryValue>
    </ServiceOptionsCharges>
    <TotalCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>35.16</MonetaryValue>
    </TotalCharges>
```

**Comment by gwharton** [comment]
The code change checks for the presence of the TaxCharges field. If the field is present and the option to include tax in rate is set to Yes, then the MonetaryValue of the TaxCharges field is added to the rate.

There is an alternative method to get the total including tax as if tax is applicable to the rate then the additional field "TotalChargesWithTaxes" could be used instead of summing the two fields to obtain the total including tax, but I chose not to use this option to minimise the amount of code changes. Let me know if this method is preferred and I will update.

**Comment by misha-kotov** [comment]
@gwharton sorry for the delay. I think this will all work, but I'm wondering if it's better for naming consistency to name "total" and "total with taxes" fields like this: 

Negotiated rates = ON, Include Tax in Rate = ON
`GrandTotal`
`GrantTotalWithTaxes` -> update this name

Negotiated rates = OFF, , Include Tax in Rate = ON
`TotalCharges`
`TotalChargesWithTaxes`

One last thing: I'd prefer to change the admin panel setting name slightly. Currently the name `Include Tax in Total` is confusing bc it can be interpreted as "the tax value will be included in the exiting 'total' field". 
I propose to call it something like `Request Tax-Inclusive Rate` with hint text of "When available, this value is returned in addition to totals without tax".

**Comment by gwharton** [comment]
@misha-kotov I have updated the labelling on the admin panel to be inline with your comments, although I have proposed a slightly different comment to the suggested one.

I have also changed the logic to get rid of the maths. There is no point in obtaining the base charge, then the taxes and adding the two together, when the total including tax is also returned from UPS and can be used directly.

I have also fixed a problem with the setting of the responseCurrencyCode which was not working correctly when negotiated rates were used, and was made worse by my original commit.

With regard to the naming of the fields in the response, these are the field names that are returned by UPS in their API and are beyond our control I am afraid. They're not consistent, but we are stuck with them.

**Comment by okorshenko** [comment]
Hi @gwharton thank you for update. Could you please cover your improvement with integration tests so that we can proceed with PR acceptance
Thank you

**Comment by misha-kotov** [comment]
@gwharton thanks for your edits. Now that you changed the math calculations, can you provide examples of how it looks now? The 4 combinations/examples you gave above were very useful.

**Comment by gwharton** [comment]
@misha-kotov There are 8 possible routes through the code. I will summarise all 8 here.

<b>Option 1</b>

Negotiated Rates Option set to "NO"
Request Tax Inclusive Rate Option set to "NO"
Shipping source and destination means tax is applicable to shipment (ex UK -> UK)

XML Snippet received back from UPS Servers

```
    <TransportationCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>6.45</MonetaryValue>
    </TransportationCharges>
    <ServiceOptionsCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>0.00</MonetaryValue>
    </ServiceOptionsCharges>
    <TotalCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>6.45</MonetaryValue>
    </TotalCharges>
```

In this combination

```
$cost is set from TotalCharges->MonetaryValue
$responseCurrencyCode is set from TotalCharges->CurrencyCode
```

<b>Option 2</b>

Negotiated Rates Option set to "NO"
Request Tax Inclusive Rate Option set to "NO"
Shipping source and destination means NO tax is applicable to shipment (ex UK -> USA)

XML Snippet received back from UPS Servers

```
    <TransportationCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>35.16</MonetaryValue>
    </TransportationCharges>
    <ServiceOptionsCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>0.00</MonetaryValue>
    </ServiceOptionsCharges>
    <TotalCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>35.16</MonetaryValue>
    </TotalCharges>
```

In this combination

```
$cost is set from TotalCharges->MonetaryValue
$responseCurrencyCode is set from TotalCharges->CurrencyCode
```

<b>Option 3</b>

Negotiated Rates Option set to "NO"
Request Tax Inclusive Rate Option set to "YES"
Shipping source and destination means tax is applicable to shipment (ex UK -> UK)

XML Snippet received back from UPS Servers

```
    <TransportationCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>6.45</MonetaryValue>
    </TransportationCharges>
    <ServiceOptionsCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>0.00</MonetaryValue>
    </ServiceOptionsCharges>
    <TaxCharges>
      <Type>VAT</Type>
      <MonetaryValue>1.29</MonetaryValue>
    </TaxCharges>
    <TotalCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>6.45</MonetaryValue>
    </TotalCharges>
    <TotalChargesWithTaxes>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>7.74</MonetaryValue>
    </TotalChargesWithTaxes>
```

In this combination

```
$cost is set from TotalChargesWithTaxes->MonetaryValue
$responseCurrencyCode is set from TotalChargesWithTaxes->CurrencyCode
```

<b>Option 4</b>

Negotiated Rates Option set to "NO"
Request Tax Inclusive Rate Option set to "YES"
Shipping source and destination means NO tax is applicable to shipment (ex UK -> USA)

XML Snippet received back from UPS Servers

```
    <TransportationCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>35.16</MonetaryValue>
    </TransportationCharges>
    <ServiceOptionsCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>0.00</MonetaryValue>
    </ServiceOptionsCharges>
    <TotalCharges>
      <CurrencyCode>GBP</CurrencyCode>
      <MonetaryValue>35.16</MonetaryValue>
    </TotalCharges>
```

In this combination

```
$cost is set from TotalCharges->MonetaryValue
$responseCurrencyCode is set from TotalCharges->CurrencyCode
```

<b>Option 5</b>

Negotiated Rates Option set to "YES"
Request Tax Inclusive Rate Option set to "NO"
Shipping source and destination means tax is applicable to shipment (ex UK -> UK)

XML Snippet received back from UPS Servers

```
    <NegotiatedRates>
      <NetSummaryCharges>
        <GrandTotal>
          <CurrencyCode>GBP</CurrencyCode>
          <MonetaryValue>9.35</MonetaryValue>
        </GrandTotal>
      </NetSummaryCharges>
    </NegotiatedRates>
```

In this combination

```
$cost is set from NegotiatedRates->NetSummaryCharges->GrandTotal->MonetaryValue
$responseCurrencyCode is set from NegotiatedRates->NetSummaryCharges->GrandTotal->CurrencyCode
```

<b>Option 6</b>

Negotiated Rates Option set to "YES"
Request Tax Inclusive Rate Option set to "NO"
Shipping source and destination means NO tax is applicable to shipment (ex UK -> USA)

XML Snippet received back from UPS Servers

```
    <NegotiatedRates>
      <NetSummaryCharges>
        <GrandTotal>
          <CurrencyCode>GBP</CurrencyCode>
          <MonetaryValue>44.37</MonetaryValue>
        </GrandTotal>
      </NetSummaryCharges>
    </NegotiatedRates>
```

In this combination

```
$cost is set from NegotiatedRates->NetSummaryCharges->GrandTotal->MonetaryValue
$responseCurrencyCode is set from NegotiatedRates->NetSummaryCharges->GrandTotal->CurrencyCode
```

<b>Option 7</b>

Negotiated Rates Option set to "YES"
Request Tax Inclusive Rate Option set to "YES"
Shipping source and destination means tax is applicable to shipment (ex UK -> UK)

XML Snippet received back from UPS Servers

```
    <NegotiatedRates>
      <TaxCharges>
        <Type>VAT</Type>
        <MonetaryValue>1.87</MonetaryValue>
      </TaxCharges>
      <NetSummaryCharges>
        <GrandTotal>
          <CurrencyCode>GBP</CurrencyCode>
          <MonetaryValue>9.35</MonetaryValue>
        </GrandTotal>
        <TotalChargesWithTaxes>
          <CurrencyCode>GBP</CurrencyCode>
          <MonetaryValue>11.22</MonetaryValue>
        </TotalChargesWithTaxes>
      </NetSummaryCharges>
    </NegotiatedRates>
```

In this combination

```
$cost is set from NegotiatedRates->NetSummaryCharges->TotalChargesWithTaxes->MonetaryValue
$responseCurrencyCode is set from NegotiatedRates->NetSummaryCharges->TotalChargesWithTaxes->CurrencyCode
```

<b>Option 8</b>

Negotiated Rates Option set to "YES"
Request Tax Inclusive Rate Option set to "YES"
Shipping source and destination means NO tax is applicable to shipment (ex UK -> USA)

XML Snippet received back from UPS Servers

```
    <NegotiatedRates>
      <NetSummaryCharges>
        <GrandTotal>
          <CurrencyCode>GBP</CurrencyCode>
          <MonetaryValue>44.37</MonetaryValue>
        </GrandTotal>
      </NetSummaryCharges>
    </NegotiatedRates>
```

In this combination

```
$cost is set from NegotiatedRates->NetSummaryCharges->GrandTotal->MonetaryValue
$responseCurrencyCode is set from NegotiatedRates->NetSummaryCharges->GrandTotal->CurrencyCode
```

I'll take a look at the integration tests now, and make sure all 8 routes are covered by a test.

**Comment by magento-engcom-team** [comment]
@gwharton thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by gwharton** [comment]
@okorshenko I have added unit tests to cover the code changes. The unit tests use actual live XML response files obtained from the UPS servers, and are injected/fed through the xml parsing routines via the normal collectRates method with the various options set to cover all of the above 8 scenareos.

**Review by okorshenko — APPROVED** [review]

**Pull request merged**
