### PR TITLE
Sitemap Generation - Product URL check null fix

### PR DESCRIPTION
**Pull request by asim-vax**
### Description (*)
Using category URL in products for sitemap - checks if metadata is null or not, when data is either blank/empty or has contents. The null check never passes.

This fix sets empty field to null, so IS NULL check passes.

### Manual testing scenarios (*)

1. log into admin 
2. stores -> config -> catalog -> catalog -> Search Engine Optimisation -> Use category URL in product -> No
3. Generate sitemap
4. view sitemap -> it uses catalog/product/view/id/2149 type URL
5. Apply fix in pull request
6. Regenerate sitemap
7. sitemap now uses request path (i.e product-name) rather than category/product-name

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @asim-vax. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21749) <br/>All committers have signed the CLA.

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-4519](https://jira.corp.magento.com/browse/ENGCOM-4519) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@asim-vax thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by aleron75** [comment]
Hello @asim-vax,
once merged, don't forget you can easily port this PR (if needed) to other branches with the Porting Tool, [read more here](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#porting-tool).

**Comment by VasylShvorak** [comment]
Hi @asim-vax I cannot reproduce issue on 2.3-develop branch.
**Manual testing scenario:**
- Set Stores -> Configuraation -> Catalog -> Catalog -> Search Engine Optimization
#21749Conf
 - Go to Marketing ->Site Map
 - Click Add Sitemap
- Set Filename and Path
- Click Save & Generate
- View sitemap
- ✔️ Url's for category and product are correct
#21749Sitemap

**Comment by asim-vax** [comment]
@VasylShvorak having looked at a blank 2.3 installation the metadata for a product is indeed null, however - we came from an m1 installation, converted to m2
Screenshot from 2019-03-22 14-36-52
As you can see, the metadata field is not null,but an empty string - and our entire sitemap became BASE_URL/catalog/product/view/id/868

**Comment by VasylShvorak** [comment]
✔️ QA passed

**Pull request merged**
