### PR TITLE
Fix issue with loading mask on Admin Checkout

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
After address change / enter, page reload does not take place, so we should not wait for page load (which is loaded), but we should wait for loading mask disappear.

The ActionGroup itself made my own tests flaky.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Looks good, but let’s wait for test results

**Review by ihor-sviziev — APPROVED** [review]
Failing functional tests not related to changes from this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7275](https://jira.corp.magento.com/browse/ENGCOM-7275) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Pull request merged**
