### PR TITLE
Fixed Cache Management mass-action checkbox alignment

### PR DESCRIPTION
**Pull request by mage2pratik**
### Description (*)

Fixed Cache Management mass-action checkbox alignment
### Fixed Issues (if relevant)

1. magento/magento2#21255: Magento backend Cache Management mass action checkbox alignment is not proper.

### Manual testing scenarios (*)

1. Login to admin panel
2. Navigate on System -> Tools (Cache Management)
3. Observe the mass action check-box

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4288](https://jira.corp.magento.com/browse/ENGCOM-4288) has been created to process this Pull Request

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hi @mage2pratik, 
thank you for your contribution!
Could you please also revert the changes made for functional test `app/code/Magento/Sales/Test/Mftf/Section/OrdersGridSection.xml` in #21022.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4288](https://jira.corp.magento.com/browse/ENGCOM-4288) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @mage2pratik , thank you for the pull request! This PR is basically a revert of the fix for https://github.com/magento/magento2/issues/21021 . Will you be able to provide a correct fix for that issue in this PR as well?

**Comment by dmytro-ch** [comment]
Hi @sivaschenko,
thank you for the update!
I had a concern regarding the "bug" fixed in #21022.
So, if this solution breaks something, I would rather revert these changes than apply new fixes.
Looking forward to your answer. :)

Thank you!

**Comment by sivaschenko** [comment]
Hi @dmytro-ch I completely agree with your concern, I simply was wondering if we could not just revert the fix, but correct it.

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [Magento instance](https://i-21257-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21257-2-3-develop.instances.magento-community.engineering/admin](https://i-21257-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dmytro-ch** [comment]
@sivaschenko, please note, the alignment issue has already been fixed in #20237.
I briefly checked the solution on `2.3-develop` and did not notice additional issues.

Thank you!

**Comment by sivaschenko** [comment]
@mage2pratik @dmytro-ch looks like both https://github.com/magento/magento2/issues/21255 and https://github.com/magento/magento2/issues/21021 are fixed on latest 2.3-develop, can you please confirm that and close this PR if necessary

**Comment by dmytro-ch** [comment]
Yes, the bug with backend Cache Management mass action checkbox alignment has been has been also fixed in #20237.
Thank you!

**Pull request closed without merging**
