### PR TITLE
Fixed #22859 Ui component form DataProvider

### LINKED ISSUE #22859: Ui component form DataProvider
So... This will be a long thread... I have some backend forms with Ui components.
The inputs of the form are not filled when editing an existent entity.
I am using Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider default class as dataprovider, everything works perfect but the fields are not prefilled.
That's because the dataprovider's returned data does not match the form's ui component data parsing.

I don't know how to make this more... understandable... but I'll try to explain.

My ui component uses Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider as its Data Provider.

DataProviderUiForm

When the form components (Ui\Component\Form.php) try to get the data from the data provider it goes through getDataSourceData()

formcomponent

The code:

>     $data = $this->getContext()->getDataProvider()->getData();

The data is returned from the DataProvider's Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider::getData()

>     public function getData()
>     {
>         return $this->searchResultToOutput($this->getSearchResult());
>     }

---->

>     protected function searchResultToOutput(SearchResultInterface $searchResult)
>     {
>         $arrItems = [];
> 
>         $arrItems['items'] = [];
>         foreach ($searchResult->getItems() as $item) {
>             $itemData = [];
>             foreach ($item->getCustomAttributes() as $attribute) {
>                 $itemData[$attribute->getAttributeCode()] = $attribute->getValue();
>             }
>             $arrItems['items'][] = $itemData;
>         }
> 
>         $arrItems['totalRecords'] = $searchResult->getTotalCount();
> 
>         return $arrItems;
>     }

Here we see that the collection is parsed and the instanced of objects are added to 
$arrItems['items'], which are not added with the object's id as their keys(!!Remember this!!)
And this screws everything up...

But let's say that everything is good, the data is perfect. It is how the core team wanted.

Now, the problem is:

>         if (isset($data[$id])) {
>             $dataSource = [
>                 'data' => $data[$id]
>             ];
>         } elseif (isset($data['items'])) {
>             foreach ($data['items'] as $item) {
>                 if ($item[$item['id_field_name']] == $id) {
>                     $dataSource = ['data' => ['general' => $item]];
>                 }
>             }
>         }

Basically here, the code checks if in the returned collection (SearchResult), there is an instance of my object that has its index $id (its id) (As said earlier, key, which was not set as expected result), but anyway that is wrong because the dataprovider's data is in the ['items'], if not, we check in the collection for the id, and set that instance as a Default (??) (I really don't understand why this happens and it is not going as in the first branch of the if)

Well, when doing this, the data is incorrect (well it is correct, but the js does not know what to do with it)

Incorrect:

incorrectFData

So, a small change in the code, works as expected:

>         if (isset($data[$id])) {
>             $dataSource = [
>                 'data' => $data[$id]
>             ];
>         } elseif (isset($data['items'])) {
>             foreach ($data['items'] as $item) {
>                 if ($item[$item['id_field_name']] == $id) {
>                     $dataSource = [
>                         'data' => $item
>                     ];
>                     //$dataSource = ['data' => ['general' => $item]];
>                 }
>             }
>         }

Correct:

correctFData

And the form fields are correctly filled.

**This "bug" is ONLY on collapsable form** 

Or I thought so. I found this when I tried to change the form layout from 2-column with left tabs to 1-column layout because tabs when there is only a single fieldset its kinda pointless.
The code was identical, but it worked before.
I suspect everything worked because my fieldset name is "general", as in how data is returned in the form component (data[ ... , 'general' => [CORRECT DATA], ...]
And the js when parsed the json data, has gone to data.<fieldset_name>, in this case, it has gone to data.general, which had the correct data.

Well, I tested this too:
I went to another form and changed the fieldset's name from "general" to something else.
And the form did not have its fields populated anymore, because there was no data in fieldset's name (data.<fieldset_name)

fieldsetnamechange

Everything could be solved if I changed the data provider class.
I'd extend the default data provider, and change the getData() as I want to.
But, I don't want to do that. The class already exists, it does everything I want to, and its a default used by the core team, why should I change that when it does its job.

So... After the whole ... discussion, the fix is really simple and solves everything.

In `vendor/magento/module-ui/Component/Form.php::getDataSourceData()`

We change

>         if (isset($data[$id])) {
>             $dataSource = [
>                 'data' => $data[$id]
>             ];
>         } elseif (isset($data['items'])) {
>             foreach ($data['items'] as $item) {
>                 if ($item[$item['id_field_name']] == $id) {
>                     $dataSource = ['data' => ['general' => $item]];
>                 }
>             }
>         }

Into this:

>         if (isset($data[$id])) {
>             $dataSource = [
>                 'data' => $data[$id]
>             ];
>         } elseif (isset($data['items'])) {
>             foreach ($data['items'] as $item) {
>                 if ($item[$item['id_field_name']] == $id) {
>                     $dataSource = [
>                         'data' => $item
>                     ];
>                 }
>             }
>         }

### Preconditions (*)

1. Magento version 2.3.x
2. Create a custom ui form using the data provider from the Magento Framework module (Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider)

### Steps to reproduce (*)

1. Module creation with a simple ui form.
app/code/Nextus/WalletCampaign/composer.json with default module data
app/code/Nextus/WalletCampaign/registration.php with default module data
app/code/Nextus/WalletCampaign/etc/module.xml with default module data
app/code/Nextus/WalletCampaign/etc/acl.xml where I create the ACL for the module
app/code/Nextus/WalletCampaign/etc/adminhtml/routes.xml with the module route.

app/code/Nextus/WalletCampaign/etc/di.xml
```
......
     <type name="Magento\Framework\View\Element\UiComponent\DataProvider\CollectionFactory">
        <arguments>
            <argument name="collections" xsi:type="array">
                <item name="wallet_campaign_data_source" xsi:type="string">Nextus\WalletCampaign\Model\ResourceModel\WalletCampaign\DataProvider\Collection</item>
            </argument>
        </arguments>
    </type>
......
```

The setup files with module database schema 
A simple model triad
app/code/Nextus/WalletCampaign/Model/WalletCampaign.php
app/code/Nextus/WalletCampaign/Model/ResourceModel/WalletCampaign.php
app/code/Nextus/WalletCampaign/Model/ResourceModel/WalletCampaign/Collection.php

DataProvider's collection:
app/code/Nextus/WalletCampaign/Model/ResourceModel/WalletCampaign/DataProvider/Collection.php

>     public function __construct(
>         EntityFactory $entityFactory,
>         Logger $logger,
>         FetchStrategy $fetchStrategy,
>         EventManager $eventManager,
>         string $mainTable = 'nextus_wallet_campaign',
>         ?string $resourceModel = 'Nextus\WalletCampaign\Model\ResourceModel\WalletCampaign',
>         ?string $identifierName = 'entity_id',
>         ?string $connectionName = null
>     ) {
>         parent::__construct($entityFactory, $logger, $fetchStrategy, $eventManager, $mainTable, $resourceModel, $identifierName, $connectionName);
>     }

The backend controller to render the form:
app/code/Nextus/WalletCampaign/Controller/Adminhtml/Campaign/Edit.php

>     public function execute()
>     {
>         $resultPage = $this->resultPageFactory->create();
>         return $resultPage;
>     }

The xml layout file for the controller:
app/code/Nextus/WalletCampaign/view/adminhtml/layout/wallet_campaign_edit.xml

> <?xml version="1.0"?>
> <page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
>     <body>
>         <referenceBlock name="content">
>             <uiComponent name="wallet_campaign_form"/>
>         </referenceBlock>
>     </body>
> </page>

The save controller which has the save logic.
app/code/Nextus/WalletCampaign/Controller/Adminhtml/Campaign/Save.php

Save button block:
app/code/Nextus/WalletCampaign/Block/Adminhtml/Campaign/Edit/SaveButton.php
(sample/default save button php)

The ui component:

app/code/Nextus/WalletCampaign/view/adminhtml/ui_component/wallet_campaign_form.xml
Well... here I want to be succinct because there is a lot of code.

```
 <?xml version="1.0" encoding="UTF-8"?>
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    <argument name="data" xsi:type="array">
        <item name="js_config" xsi:type="array">
            <item name="provider" xsi:type="string">wallet_campaign_form.wallet_campaign_data_source</item>
        </item>
        <item name="label" xsi:type="string" translate="true">Wallet Campaign</item>
        <item name="template" xsi:type="string">templates/form/collapsible</item>
    </argument>
    <settings>
        <buttons>
            <button name="save" class="Nextus\WalletCampaign\Block\Adminhtml\Campaign\Edit\SaveButton"/>
        </buttons>
        <namespace>wallet_campaign_form</namespace>
        <dataScope>data</dataScope>
        <deps>
            <dep>wallet_campaign_form.wallet_campaign_data_source</dep>
        </deps>
    </settings>
    <dataSource name="wallet_campaign_data_source">
        <argument name="data" xsi:type="array">
            <item name="js_config" xsi:type="array">
                <item name="component" xsi:type="string">Magento_Ui/js/form/provider</item>
            </item>
        </argument>
        <settings>
            <submitUrl path="wallet/campaign/save"/>
        </settings>
        <dataProvider class="Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider" name="wallet_campaign_data_source">
            <settings>
                <requestFieldName>entity_id</requestFieldName>
                <primaryFieldName>entity_id</primaryFieldName>
            </settings>
        </dataProvider>
    </dataSource>
    <fieldset name="general">
        ---FIELDS---
    </fieldset>
</form>
```

### Expected result (*)

1. After you save some data into the database, and you'd go to edit that data, the form should be filled with your data.

### Actual result (*)

1. The form fields are not filled with your data.

There is no question or anything else, I just thought I should let you know about this, and it should be solved. Or maybe I am wrong and my implementation of ui form is wrong and maybe someone would have the time to correct me.

*Maybe someone would ask me why I used that dataprovider and not the one from ui components (vendor/magento/module-ui/DataProvider/AbstractDataProvider.php), the answer is simple. As I see in that data provider, the code is not fully completed, and it still uses the "old model triad" features (collection -> addFieldTo*, and you have to create the dataprovider to give it a class), instead of the service contracts, and in the code, there is "//TODO: Technical dept, should be implemented as part of SearchAPI support for Catalog Grids".
That means on the future, there will be an implementation of service contracts there
The dataprovider from the magento framework module, has everything working with the service contracts, well... almost... it still relies on the model triad to get its data, but at least the data provider logic is "new(?)"
So I had to choose which one should I use for my work, and I thought that I should use the latest things that are now, it was more of a gamble.*

### PR DESCRIPTION
**Pull request by kirtinariya1**
Custom module ui_component resolved the form fields are not filled with data. when used <fieldset name="general"> in custom module.

### Description (*)

Ui component form DataProvider

### Fixed Issues (if relevant)

1. #22859 : Custom module ui_component resolved the form fields are not filled with data.

### Manual testing scenarios (*)

1)Create custom module with a simple ui form.

2)Create app/code/Nextus/WalletCampaign/view/adminhtml/ui_component/wallet_campaign_form.xml
 
```
<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    <argument name="data" xsi:type="array">
        <item name="js_config" xsi:type="array">
            <item name="provider" xsi:type="string">wallet_campaign_form.wallet_campaign_data_source</item>
        </item>
        <item name="label" xsi:type="string" translate="true">Wallet Campaign</item>
        <item name="template" xsi:type="string">templates/form/collapsible</item>
    </argument>
    <settings>
        <buttons>
            <button name="save" class="Nextus\WalletCampaign\Block\Adminhtml\Campaign\Edit\SaveButton"/>
        </buttons>
        <namespace>wallet_campaign_form</namespace>
        <dataScope>data</dataScope>
        <deps>
            <dep>wallet_campaign_form.wallet_campaign_data_source</dep>
        </deps>
    </settings>
    <dataSource name="wallet_campaign_data_source">
        <argument name="data" xsi:type="array">
            <item name="js_config" xsi:type="array">
                <item name="component" xsi:type="string">Magento_Ui/js/form/provider</item>
            </item>
        </argument>
        <settings>
            <submitUrl path="wallet/campaign/save"/>
        </settings>
        <dataProvider class="Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider" name="wallet_campaign_data_source">
            <settings>
                <requestFieldName>entity_id</requestFieldName>
                <primaryFieldName>entity_id</primaryFieldName>
            </settings>
        </dataProvider>
    </dataSource>
    <fieldset name="general">
        ---FIELDS---
    </fieldset>
</form>
```

3)The form fields are not filled with your data.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23768) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23768) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: kirtinariya1<br/>:x: Kirti Nariya<hr/>**Kirti Nariya** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by sprankhub** [comment]
I think this would be a pretty massive change. Every uiComponent, which uses the standard implementation would then break. I currently do not have the time to dig deeper into it, but can't you define `general` as the `dataScope`, which then leads to the usage of the right data?

**Comment by kirtinariya1** [comment]
@sprankhub Thanks for your review i appreciate your kind of information. But i have tested with `general`  and after removed `general` core magento Ui component form working fine. It's just problem when used `general` in custom module.

**Comment by slavvka** [comment]
@magento run all tests

**Comment by LucianMihalache** [comment]
Hi guys.
Thank you for working on this.
There is no problem in removing the general. In fact, the general over there was messing everything else up. I am running the fix for 2 months on 10 instances with no problem, with 20-30 custom modules.

**Comment by sidolov** [comment]
@kirtinariya1 I'm closing this PR because it contains only new line added

**Pull request closed without merging**
