### PR TITLE
Catalog Rule: Update Return Type for getWebsiteIds()

### PR DESCRIPTION
**Pull request by pykettk**
### Description (*)
Updates the `getWebsiteIds()` function's return type. This function is inherited from [`Magento\Rule\Model\AbstractModel`](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Rule/Model/AbstractModel.php#L472-L484) - which defines the return type as an array, not a string.

### Manual testing scenarios (*)
1. Call the `Magento\CatalogRule\Model\Rule::getWebsiteIds()` function as part of a `foreach` loop
2. Observe the intellisense complain about an incorrect data type

### Notes
Failing tests are unrelated.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by pykettk** [comment]
@magento run all tests

**Comment by pykettk** [comment]
@magento run Functional Tests EE, Integration Tests, Static Tests

**Review by fredden — APPROVED** [review]

**Comment by pykettk** [comment]
@magento run Integration Tests

**Comment by fredden** [comment]
@magento run all tests

**Pull request closed without merging**
