### PR TITLE
[Backport] magento/magento2#12396: Total Amount cart rule without tax

### PR DESCRIPTION
**Pull request by eduard13**
### Original Pull Request 
 https://github.com/magento/magento2/pull/21288
Added new condition type to give user opportunity to choose the configuration.

### Description (*)
I thought about the fix of what should be fixed in here. But I guess it's up to the user what to choose and what conditions to have to apply the rule. 
I decided to add new Cart Attribute to **Subtotal (Excl. Tax)** which is basically one of the totals _base_subtotal_with_discount_ 

### Fixed Issues (if relevant)

1. magento/magento2#<[12396](https://github.com/magento/magento2/issues/12396)>: "Total Amount" cart rule without tax

### Manual testing scenarios (*)

1. Go to the Admin Panel. Open Marketing->Cart Price Rules
2. Add new rule or edit existing one
3. Under the Condition tab you will be able to see new Configuration Subtotal (Excl. Tax).

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-21845.instances.magento-community.engineering).
Admin access: [https://pr-21845.instances.magento-community.engineering/admin](https://pr-21845.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4540](https://jira.corp.magento.com/browse/ENGCOM-4540) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
