### PR TITLE
Fixed typo in method name

### PR DESCRIPTION
**Pull request by olmer**
Method name \Magento\Framework\App\Request\Http::removeRepitedSlashes contained typo

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15256) <br/>All committers have signed the CLA.

**Review by orlangur — APPROVED** [review]

**Comment by orlangur** [comment]
Good job @olmer, congrats with your first contribution!

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-1575](https://jira.corp.magento.com/browse/ENGCOM-1575) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@olmer thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @olmer. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

**Pull request merged**
