### PR TITLE
Tailwindui css layout support - colon is not accepted by the pattern

### LINKED ISSUE #34430: tailwindui css layout support - colon is not accepted by the pattern
I would like to use tailwindui for a project, but unfortunately it is currently not possible because no colon is allowed within the htmlClass. 

```
<!-- Width of 16 by default, 32 on medium screens, and 48 on large screens -->
<div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl"></div>
```

`
<referenceContainer name="header-wrapper" htmlClass="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl" htmlId="header" />
`

`Element 'referenceContainer', attribute 'htmlClass': [facet 'pattern'] The value 'page-wrapper flex relative md:p-0' is not accepted by the pattern '[a-zA-Z][a-zA-Z\d\-_]*(\s[a-zA-Z][a-zA-Z\d\-_]*)*'.
Line: 1306`

Is there a way to make this compatible?

### PR DESCRIPTION
**Pull request by in-session**
https://tailwindcss.com/docs/responsive-design#overview

Fixes https://github.com/magento/magento2/issues/34430

### CODE REVIEW

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento run Functional Tests EE, Functional Tests CE, Unit Tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
Failing tests are not related to changes from this PR

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9332](https://jira.corp.magento.com/browse/ENGCOM-9332) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@in-session thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by ihor-sviziev** [comment]
@sidolov, I think the priority for this PR should be set to P2 as it prevents using Tailwind CSS with Magento

**Comment by Den4ik** [comment]
@ihor-sviziev I'm agree with changes, but validation is not blocking to use this classes in layout. You just will see warning in IDE

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9332](https://jira.corp.magento.com/browse/ENGCOM-9332) has been created to process this Pull Request

**Comment by Den4ik** [comment]
@in-session Could you explain what is blocking to use classes with `:` except IDE notification?

**Comment by in-session** [comment]
@Den4ik 
Is that what you mean?

```
1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceContainer', attribute 'htmlClass': [facet 'pattern'] The value 'header content header-top mt-0 border-0 flex items-end mb-0 md:mb-3 md:mt-6 relative md:pb-10 md:pt-0 px-0 grid-flow-row auto-rows-max' is not accepted by the pattern '[a-zA-Z][a-zA-Z\d\-_]*(\s[a-zA-Z][a-zA-Z\d\-_]*)*'.
Line: 1280

<pre>#1 Magento\Framework\Config\Dom->__construct() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]
#2 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:66]
#3 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#4 Magento\Framework\ObjectManager\ObjectManager->create() called at [vendor/magento/framework/Config/DomFactory.php:43]
#5 Magento\Framework\Config\DomFactory->createDom() called at [vendor/magento/framework/View/Model/Layout/Update/Validator.php:141]
#6 Magento\Framework\View\Model\Layout\Update\Validator->isValid() called at [vendor/magento/framework/View/Model/Layout/Merge.php:524]
#7 Magento\Framework\View\Model\Layout\Merge->_validateMergedLayout() called at [vendor/magento/framework/View/Model/Layout/Merge.php:500]
#8 Magento\Framework\View\Model\Layout\Merge->load() called at [generated/code/Magento/Framework/View/Model/Layout/Merge/Interceptor.php:149]
#9 Magento\Framework\View\Model\Layout\Merge\Interceptor->load() called at [vendor/magento/framework/View/Layout/Builder.php:86]
#10 Magento\Framework\View\Layout\Builder->loadLayoutUpdates() called at [vendor/magento/framework/View/Layout/Builder.php:63]
#11 Magento\Framework\View\Layout\Builder->build() called at [vendor/magento/framework/View/Layout.php:271]
#12 Magento\Framework\View\Layout->build() called at [vendor/magento/framework/View/Layout.php:896]
#13 Magento\Framework\View\Layout->getBlock() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:293]
#14 Magento\Framework\View\Layout\Interceptor->getBlock() called at [vendor/magento/module-cms/Helper/Page.php:218]
#15 Magento\Cms\Helper\Page->prepareResultPage() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#16 Magento\Cms\Helper\Page\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#19 Magento\Cms\Helper\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#20 Magento\Cms\Helper\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Cms/Helper/Page/Interceptor.php:23]
#21 Magento\Cms\Helper\Page\Interceptor->prepareResultPage() called at [vendor/magento/module-cms/Controller/Noroute/Index.php:47]
#22 Magento\Cms\Controller\Noroute\Index->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#23 Magento\Cms\Controller\Noroute\Index\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#24 Magento\Cms\Controller\Noroute\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#25 Magento\Cms\Controller\Noroute\Index\Interceptor->___callPlugins() called at [generated/code/Magento/Cms/Controller/Noroute/Index/Interceptor.php:23]
#26 Magento\Cms\Controller\Noroute\Index\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#27 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#28 Magento\Cms\Controller\Noroute\Index\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#29 Magento\Cms\Controller\Noroute\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#30 Magento\Cms\Controller\Noroute\Index\Interceptor->___callPlugins() called at [generated/code/Magento/Cms/Controller/Noroute/Index/Interceptor.php:32]
#31 Magento\Cms\Controller\Noroute\Index\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:245]
#32 Magento\Framework\App\FrontController->getActionResponse() called at [vendor/magento/framework/App/FrontController.php:212]
#33 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:147]
#34 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#35 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#36 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#37 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#40 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:75]
#41 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#42 Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#43 Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#44 Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->___callPlugins() called at [generated/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin/Interceptor.php:23]
#45 Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#46 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#47 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#48 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#49 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#50 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
</pre>
```

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE, Functional Tests CE, Unit Tests

**Comment by hostep** [comment]
@Den4ik:
> but validation is not blocking to use this classes in layout. You just will see warning in IDE

I've seen more and more problems popping up in the latest few Magento versions that get affected at runtime by invalid (according to the schema) xml files. Not sure if it only happens in development or also in production mode and not sure in which Magento version it changed. But it's definitely not only the IDE that throws warnings.

**Comment by in-session** [comment]
I would now like to raise a fundamental question: Would it not make sense to better standardise the modules in the future? 
Perhaps the community could also be involved a little more in the development or survey.  

As a small example for the slides:
Pagebuilder uses slick slider, 50% per module developer use owl or swiper.

I therefore ask myself why, in this case, one doesn't decide in favour of the Swiper, for example.
I, for example, also build everything using swiper, as it has the best functions, requirements and adaptability for me. To be honest, this is always the problem that everything has to be rewritten and that simply costs a lot of time. And even if you are more involved with Magento, it would be very good to have a script template catalogue here. Then the module builders would also stick more to the internal things and build on them. Of course, Magento Luma is supposed to be a lightweight template, but in my opinion it doesn't make sense to use a library that no one will need afterwards. 

Lazyload: https://github.com/magento/magento2/pull/34558#issuecomment-964820453

References: https://npmcharts.com/compare/slick,swiper,owl.carousel?interval=30
https://github.com/kenwheeler/slick 
https://github.com/OwlCarousel2/OwlCarousel2
https://github.com/nolimits4web/swiper

**Comment by ihor-sviziev** [comment]
@in-session could you create a separate issue for that discussion? I'll try to bring the needed people to discussiuon.
Thank you!

**Comment by Den4ik** [comment]
@in-session @hostep You where right. I forgot to check mode on project where I tested it (PS. it was default mode). Validation worked only on developer mode

**Review by torhoehn — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @torhoehn, thank you for the review.
[ENGCOM-9332](https://jira.corp.magento.com/browse/ENGCOM-9332) has been created to process this Pull Request

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9332](https://jira.corp.magento.com/browse/ENGCOM-9332) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Magento should be installed and working well.


**Manual testing scenario:**

1. Open any front end file, for example considered /app/code/Magento/catalog/view/frontend/layout/catalog_product_view.xml

2. Change the htmcl class name to htmlClass="product-info-main md:max-w-2xl""
 
3. Deploy static content and flush cache

4. Front end - Open the Product details page from any catagory.


**Before:** :heavy_multiplication_x: Were getting an error page

Attach screenshot

**After:** :heavy_check_mark: Getting an proper product details page

Attach screenshot

**Comment by in-session** [comment]
@magento give me test instance

**Comment by BernardRobbins-BMediaLLC** [comment]
I created a module that should fix this in the meantime: https://github.com/BernardRobbins/TailWindUiM2Fix

**Comment by barryvdh** [comment]
Doesn't this miss some cases? https://docs.hyva.io/hyva-themes/building-your-theme/styling-layout-containers.html
For example `w-screen left-1/2 right-1/2 mx-[-50vw] relative`
The patch there from @ArjenMiedema  does solve it:

```
@package magento/framework

diff --git View/Layout/etc/elements.xsd View/Layout/etc/elements.xsd
index 51f1931..14baa00 100644
--- View/Layout/etc/elements.xsd
+++ View/Layout/etc/elements.xsd
@@ -119,7 +119,7 @@

     <xs:simpleType name="htmlClassType">
         <xs:restriction base="xs:string">
-            <xs:pattern value="[a-zA-Z][a-zA-Z\d\-_]*(\s[a-zA-Z][a-zA-Z\d\-_]*)*"/>
+            <xs:pattern value="[a-zA-Z\-][a-zA-Z\d\-_/:.\[\]]*(\s[a-zA-Z][a-zA-Z\d\-_/:.\[\]]*)*"/>
         </xs:restriction>
     </xs:simpleType>
```

**Comment by in-session** [comment]
> Doesn't this miss some cases? https://docs.hyva.io/hyva-themes/building-your-theme/styling-layout-containers.html For example `w-screen left-1/2 right-1/2 mx-[-50vw] relative` The patch there from @ArjenMiedema does solve it:
> 
> ```
> @package magento/framework
> 
> diff --git View/Layout/etc/elements.xsd View/Layout/etc/elements.xsd
> index 51f1931..14baa00 100644
> --- View/Layout/etc/elements.xsd
> +++ View/Layout/etc/elements.xsd
> @@ -119,7 +119,7 @@
> 
>      <xs:simpleType name="htmlClassType">
>          <xs:restriction base="xs:string">
> -            <xs:pattern value="[a-zA-Z][a-zA-Z\d\-_]*(\s[a-zA-Z][a-zA-Z\d\-_]*)*"/>
> +            <xs:pattern value="[a-zA-Z\-][a-zA-Z\d\-_/:.\[\]]*(\s[a-zA-Z][a-zA-Z\d\-_/:.\[\]]*)*"/>
>          </xs:restriction>
>      </xs:simpleType>
> ```

Yes because of change from Version 2 to 3 also for page builder. We need to open a new merge for it.

**Comment by in-session** [comment]
> 

mx-[-50vw] = -mx-[50vw]?

**Comment by barryvdh** [comment]
Not sure, that's the example from https://docs.hyva.io/hyva-themes/faqs/full-bleed-cms-content.html

**Comment by barryvdh** [comment]
Update PR in https://github.com/magento/magento2/pull/36452

**Pull request merged**
