### PR TITLE
Correct variable name

### LINKED ISSUE #38093: [Issue] Correct variable name
This issue is automatically created based on existing pull request: magento/magento2#38083: Correct variable name

---------

### Description (*)

This pull request corrects variable name in the `app/code/Magento/CatalogRule/Controller/Adminhtml/Promo/Catalog/NewConditionHtml.php`

### Related Pull Requests

This pull request corrects only variable name and does not alter Magento behaviour.

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

N/A

### Questions or comments

N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by mage2pratik**
### Description (*)

This pull request corrects variable name in the `app/code/Magento/CatalogRule/Controller/Adminhtml/Promo/Catalog/NewConditionHtml.php`

### Related Pull Requests

This pull request corrects only variable name and does not alter Magento behaviour.

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

N/A

### Questions or comments

N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38093: Correct variable name

### CODE REVIEW

**Comment by engcom-Hotel** [comment]
@magento create issue

**Review by fredden — APPROVED** [review]

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

1. Go to app/code/Magento/CatalogRule/Controller/Adminhtml/Promo/Catalog/NewConditionHtml.php
2. Verify the variable responseBody 

**Before:** :heavy_multiplication_x: 

Screenshot 2023-11-22 at 2 04 35 PM


**After:** :heavy_check_mark:  

Screenshot 2023-11-22 at 3 09 25 PM


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Functional Tests EE,Integration Tests ,Functional Tests CE ,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Functional Tests EE,Integration Tests ,Functional Tests CE ,Functional Tests B2B

**Comment by engcom-Echo** [comment]
Functional Tests EE builds are green. 
Functional Tests CE build failure are different on last two run on same commit.
Run1
Screenshot 2023-11-23 at 3 54 48 PM

Run2
Screenshot 2023-11-23 at 3 55 33 PM

Hence moving it to `merge in progress`

**Pull request merged**
