### PR TITLE
Fopen flags

### PR DESCRIPTION
**Pull request by MathiasReker**
The flags in fopen calls must omit t, and b must be omitted or included consistently.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @MathiasReker. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
@MathiasReker what is the basis for such recommendation?

**Comment by MathiasReker** [comment]
better practice. binary modes is recommended everywhere.

**Comment by ghost** [comment]
Hi @MathiasReker, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+magento2+20693), it will take less than a minute. </br>Your feedback will help us to improve contribution process.

**Pull request closed without merging**
