### PR TITLE
Fixed custom option dropdown option missaligned

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)

Catalog Product - Customizable Options > drop-down option type aligned issue fixed.
### Fixed Issues (if relevant)

1. magento/magento2#19558:custom option dropdown option missaligned
2. ...

### Manual testing scenarios (*)

1. Not Required for designing alignment issue

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @emiprotech. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](https://i-19567-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19567-2-3-develop.instances.magento-community.engineering/admin](https://i-19567-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rogyar** [comment]
Hi @emiprotech. Thank you for your contribution. As it's mentioned in the original issue, the bug has been already fixed in the 2.3-develop branch. I've just double checked this matter.
Feel free to reopen this PR if some related issues are still present.

**Pull request closed without merging**
