### PR TITLE
Fix type definition mapper typo

### LINKED ISSUE #35108: Incorrect 'longblog' database definition, should be 'longblob'
### Steps to reproduce (*)
1. Look at this line: https://github.com/magento/magento2/blob/2d446475953e907c9844d493857d172bc9956bd8/app/etc/di.xml#L1615

### Expected result (*)
1. seeing `longblob`

### Actual result (*)
1. seeing `longblog`

### Discussion
Accidentally noticed this, no idea if this can cause problems in any way in Magento, but it looks a bit sloppy 🙂 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### LINKED ISSUE #35128: [Issue] Fix type definition mapper typo
This issue is automatically created based on existing pull request: magento/magento2#35109: Fix type definition mapper typo

---------
### Description (*)
Fixed typo in di.xml

### Fixed Issues (if relevant)
1. Fixes magento/magento2#35108

### Manual testing scenarios (*)
No need to test

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by dudzio12**
### Description (*)
Fixed typo in di.xml

### Fixed Issues (if relevant)
1. Fixes magento/magento2#35108

### Manual testing scenarios (*)
No need to test

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#35128: Fix type definition mapper typo

### CODE REVIEW

**Comment by dudzio12** [comment]
Run all tests

**Comment by bgorski** [comment]
@dudzio12 thank you for the contribution! Can you provide steps for testing this? This is an obvious typo and the PR will get accepted, but when it does, the next step is manual testing. Adobe QA engineers will have to know how to trigger the piece of code that you fixed.

**Review by bgorski — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests EE, Functional Tests CE

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

This PR is relevant to the the correct of text in the di.xml and has no functional impact and hence no testing required.
Since the auto-test jobs are successfully running with this PR, moving to _Merge In Progress_.
Thanks for the contribution and collaboration @dudzio12 and @bgorski .

**Pull request merged**
