### PR TITLE
Fixed Issue Configurable product not showing price

### PR DESCRIPTION
**Pull request by sureshp1000**
Fixed Issue: Configurable product not showing price on category and product page #28068: it was not showing price when all simple products are out of stock.

### Description (*)
Configurable products not showing price on category and product page when all the associated simple products are out of stock.

### Fixed Issues (if relevant)

1. Fixes magento/magento2# https://github.com/magento/magento2/issues/28068

### Manual testing scenarios (*)

    1. Create a configurable product with all its associated simple products as out of stock
    2. On front-end go to product page of that configurable product
    3. The product price should be shown at product page

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sureshp1000** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sureshp1000. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sureshp1000, here is your [new Magento instance](https://pr-28445.instances.magento-community.engineering).
Admin access: [https://pr-28445.instances.magento-community.engineering/admin_24f4](https://pr-28445.instances.magento-community.engineering/admin_24f4)
Login: `50f6427e` Password: `e0eb3ce28070`
Instance will be terminated in up to 3 hours.

**Comment by rogyar** [comment]
@magento run all tests

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @sureshp1000. 

Thank you for your collaboration. Please take a look at the failing functional tests. It looks like that the provided change breaks the normal price rendering flow for many cases.

**Comment by engcom-Kilo** [comment]
Working with MFTF test.

**Comment by engcom-Kilo** [comment]
Added MFTF test.

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@sureshp1000 
Please check failed Tests. 
Thanks

**Comment by engcom-Kilo** [comment]
Hi @sureshp1000, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
