### PR TITLE
Uppercase event names do not make sense anymore

### PR DESCRIPTION
**Pull request by ghost**
With this change https://github.com/magento/magento2/commit/b5ff83f572b20ec23a91fd2f17665e744f8f7a7c#diff-9e2d40c58c6176522795f8b5ec4d6392R41 all event names get lower cased so we might as well enforce this in the xsd (and possibly remove the lower casing in the config reader)

### CODE REVIEW

**Comment by fooman** [comment]
Looks like Magento still has some uppercased event names. Will update the PR to include changing them as well.

**Comment by ktomk** [comment]
@fooman: Good catch and great to see the XSD reflect this. I don't know what the common ground is, but I see that other libraries are changing the `mb_internal_encoding()` their own, and because of that I would suggest to explicitly pass the `"UTF-8"` encoding as second parameter with `mb_strtolower()` in [line 49](https://github.com/magento/magento2/blob/b5ff83f572b20ec23a91fd2f17665e744f8f7a7c/lib/internal/Magento/Framework/Event/Manager.php#L49) and in the other file in [line 41](https://github.com/magento/magento2/blob/b5ff83f572b20ec23a91fd2f17665e744f8f7a7c/lib/internal/Magento/Framework/Event/Config/Converter.php#L41).

Technically if the XSD is introduced, the transposition to lowercase should not be necessary any longer.

References:
- https://www.w3.org/TR/xmlschema-2/#nt-charRange

**Comment by fooman** [comment]
This change would also need to bump magento/framework's major version number as it's a breaking change. Please advise if you want me to include that in this PR as well.

**Comment by dsikkema-magento** [comment]
@fooman, thank you for your contribution. This change does make sense from one perspective, since like you said, uppercase names don't make sense. On the other hand, it doesn't hurt if they are uppercase, and it's probably best to never introduce this breaking change, so I don't think we will accept this pull request.

**Comment by ktomk** [comment]
@dsikkema: So do you revert the original, backward compatibility breaking change then, too? Or is it that you just say so here but do so otherwise?

**Comment by fooman** [comment]
@ktomk the original change is not breaking due to also lower casing upon reading from the config here https://github.com/magento/magento2/commit/b5ff83f572b20ec23a91fd2f17665e744f8f7a7c#diff-9e2d40c58c6176522795f8b5ec4d6392L41

**Comment by ktomk** [comment]
@fooman: It is breaking because it triggers more events than it did earlier.

**Pull request closed without merging**
