### PR TITLE
Allow backend login without redirect

### LINKED ISSUE #31042: [Issue] Allow backend login without redirect
This issue is automatically created based on existing pull request: magento/magento2#30950: Allow backend login without redirect

---------

### Description (*)
Magento 2.4-develop
Currently, when accessing a backend page via a direct URL as a logged out admin, the admin is redirected to `<backend-url>/admin` to log in. After logging in, they are redirected to the admin dashboard (or whatever page is selected as the startup page in system configuration).

This can be frustrating, since the admin now has to manually navigate to the requested page. This also potentially prevents some scripted tasks.

This PR proposes to remove the redirect to `<backend-url>/admin`, in which case the log in happens on the same page as the requested page (same as M1). The user is directly redirected to the requested page after login.

### Related Pull Requests

- [MAGETWO-45465](https://github.com/magento/magento2/commit/2bf7c958f68137ee187f8798c73aed15846a1a33) The proposed code to be removed was added in this commit.

### Manual testing scenarios (*)

1. Add an admin user with a role that allows them to view products (`Magento_Catalog::products` ACL resource).
2. Make sure you're logged out from the backend.
3. Attempt to access `<backend-url>/catalog/product/`
4. The login form should be presented to you. Check the URL - you should still be on `<backend-url>/catalog/product/` with this PR.
5. Log in.
6. You should see the product listing directly (and not be redirected to the startup page).

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by aapokiiso**
### Description (*)

Currently, when accessing a backend page via a direct URL as a logged out admin, the admin is redirected to `<backend-url>/admin` to log in. After logging in, they are redirected to the admin dashboard (or whatever page is selected as the startup page in system configuration).

This can be frustrating, since the admin now has to manually navigate to the requested page. This also potentially prevents some scripted tasks.

This PR proposes to remove the redirect to `<backend-url>/admin`, in which case the log in happens on the same page as the requested page (same as M1). The user is directly redirected to the requested page after login.

### Related Pull Requests

- [MAGETWO-45465](https://github.com/magento/magento2/commit/2bf7c958f68137ee187f8798c73aed15846a1a33) The proposed code to be removed was added in this commit.

### Manual testing scenarios (*)

1. Add an admin user with a role that allows them to view products (`Magento_Catalog::products` ACL resource).
2. Make sure you're logged out from the backend.
3. Attempt to access `<backend-url>/catalog/product/`
4. The login form should be presented to you. Check the URL - you should still be on `<backend-url>/catalog/product/` with this PR.
5. Log in.
6. You should see the product listing directly (and not be redirected to the startup page).

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31042: Allow backend login without redirect

### CODE REVIEW

**Comment by aapokiiso** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by aleron75** [comment]
Hello @aapokiiso, thanks for your contribution.

I was looking at the failing tests and I think the only two that fails related to this PR are the following functional tests :
- https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/30950/20327aedcf685b756e688a5ef42261e4/Functional/allure-report-ce/index.html#suites/8187718e2fd144987673ef34ee62b41b/ad84e8298e4832aa/
- https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/30950/4c398eb8fb9542bb7ea45094ef2fd5dd/Functional/allure-report-ee/index.html#suites/8187718e2fd144987673ef34ee62b41b/8039051fa01d9711/

Would you mind updating the above functional test (it's the same kind of test failing on both CE and EE)?

The other failing tests seem flaky and not directly related to this PR, let the QA team verify that.

Thank you again.

**Comment by aapokiiso** [comment]
@magento run Functional Tests CE Functional Tests EE Functional Tests B2B

**Comment by aapokiiso** [comment]
@magento run all tests

**Comment by aapokiiso** [comment]
@aleron75 The related functional test has now been fixed

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-8539](https://jira.corp.magento.com/browse/ENGCOM-8539) has been created to process this Pull Request

**Review by engcom-Delta — CHANGES_REQUESTED** [review]
Hi @aapokiiso . I checked PR changes  and found issue: admin is redirected to `noroute/index/` page when Add Secret Key to URLs=Yes
**Manual testing scenario:**

- Set Stores->Configuration->Advanced->Admin->Security->Add Secret Key to URLs=Yes
image
- Add an admin user with a role that allows them to view products (Magento_Catalog::products ACL resource).
 image
- Make sure you're logged out from the backend.
- Go to <backend-url>/catalog/product/
- Log in.

**Result:**
:x: Admin see the `404 Not Found` page
Peek 2020-12-15 10-21

**Note:** Behavior when Add Secret Key to URLs=No:
:heavy_check_mark: Admin see the product listing directly
Peek 2020-12-15 10-19


Could you take a look?

**Comment by engcom-Charlie** [comment]
@aapokiiso I'll continue with your PR.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-8539](https://jira.corp.magento.com/browse/ENGCOM-8539) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Result:**
**Before:**
:x: The admin is redirected to <backend-url>/admin
Peek 2020-12-28 09-22


**After:**
:heavy_check_mark: Admin see the product listing directly
Peek 2020-12-28 08-50

**Comment by engcom-Delta** [comment]
@magento create issue

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Comment by ihor-sviziev** [comment]
@aapokiiso @aleron75 I feel that test coverage is still missing here, while you just fixed failing MFTF tests.

**Pull request merged**
