### PR TITLE
Fix call_user_func_array in Magento Framework

### LINKED ISSUE #34301: Fix `call_user_func_array` in the codebase with test coverage
### Description (*)
The call of the function `call_user_func_array` with associative array as params if param names for callback function are different with keys in provided associative array provokes the fatal error in PHP >= 8.0.
As part of this task, we need to use array_values($params) to make the behaviour the same with PHP < 8.0.
Also, we need coverage of the changed functionality with unit or integration tests.

### PR DESCRIPTION
**Pull request by SilinMykola**
### Description (*)
Change calls call_user_func_array() in Magento lib.

### Related Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/34301

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run Static Tests with env PHP 8.0

**Review by andrewbess — APPROVED** [review]

**Comment by xmav** [comment]
@magento run Unit Tests, Integration Tests, Functional Tests B2B with env PHP 8.0

**Comment by xmav** [comment]
@magento run Semantic Version Checker

**Pull request merged**
