### PR TITLE
Fix HTML syntax error in visual.phtml

### LINKED ISSUE #38247: [Issue] Fix HTML syntax error in visual.phtml
This issue is automatically created based on existing pull request: magento/magento2#37457: Fix HTML syntax error in visual.phtml

---------
Start tag (th) not closed properly, expected  '>'.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by AntonKryvoruchko**
Start tag (th) not closed properly, expected  '>'.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38247: Fix HTML syntax error in visual.phtml

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @AntonKryvoruchko, 
Could you please fix the static test failures (might be not directly related to changes, but we need to make our changed files to pass the static tests)?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests look not related to changes from this PR.

**Comment by engcom-Delta** [comment]
@magento create issue

**Comment by engcom-Delta** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

1. Go to app/code/Magento/Swatches/view/adminhtml/templates/catalog/product/attribute/visual.phtml
2. Verify 8, 24, 25, 43, 59, 90 and 100 line 
3. The changes should be saved


**Before:** :heavy_multiplication_x: 


Screenshot 2023-12-07 at 2 20 24 PM

Screenshot 2023-12-07 at 2 21 47 PM

Screenshot 2023-12-07 at 2 22 24 PM

Screenshot 2023-12-07 at 2 23 17 PM


**After:** :heavy_check_mark:  


Screenshot 2023-12-07 at 3 24 45 PM

Screenshot 2023-12-07 at 3 25 44 PM

Screenshot 2023-12-07 at 3 26 34 PM

Screenshot 2023-12-07 at 3 27 12 PM


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Static Tests,Integration Tests,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests

**Comment by engcom-Echo** [comment]
WebAPI Tests failure does not seems to be related to PR.

Hence moving it to `merge in progress`

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by hostep** [comment]
Let is be noted that there is a competing PR with the same changes over here: https://github.com/magento/magento2/pull/38261

Both got approved, so we should halt one of them and only proceed with one and not with both.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @AntonKryvoruchko,

Can you please have a look into Static test [failures](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37457/0f0d6f8ef038857b451105454ee11437/Statics/console-error-logs.html). Till then moving it to Changes Requested.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Static Tests,WebAPI Tests,Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
Build failure are not related to PR.
Hence moving it to Ready for Testing.

**Comment by engcom-Delta** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

Go to app/code/Magento/Swatches/view/adminhtml/templates/catalog/product/attribute/visual.phtml
Verify 8, 24, 25, 43, 59, 90 and 100th line
The changes should be saved

**Before:** :heavy_multiplication_x: 



**After:** :heavy_check_mark:  


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, WebAPI Tests

**Comment by engcom-Charlie** [comment]
The functional B2b, CE are having some common failures in recent 2 builds the rest failures in these seems to be flaky. After analysis, found that all consistent failures not failing because of this PR changes. They are known issues and having JIRA for them.

**Functional B2B: Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37457/6683d484b162dc555275951ce799f4ce/Functional/allure-report-b2b/index.html

**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37457/35a7f4740eb2098a34a7169e7802e2c7/Functional/allure-report-b2b/index.html

Known issue:
1. AdminReorderWithCatalogPriceRuleDiscountTest :  https://jira.corp.adobe.com/browse/ACQE-6523

**Functional CE: Run 1:**
 https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37457/848a02f03e5f31a2b6523879e7114b35/Functional/allure-report-ce/index.html

Run 2: 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37457/b50b8ffb35af038c2ecfc1ff60baaabb/Functional/allure-report-ce/index.html

Known issue:
1. AdminCheckConfigurationForPayPalExpressCheckoutInUnitesStatesTest: https://jira.corp.adobe.com/browse/ACQE-6590

**Comment by engcom-Charlie** [comment]
The functional EE and WebAPI tests are having some common failures in recent 2 builds the rest failures in these seems to be flaky. After analysis, found that all consistent failures not failing because of this PR changes. They are known issues and having JIRA for them.

**Functional EE: Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37457/314e44f190a04d29ef0b7611748c306d/Functional/allure-report-ee/index.html

image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37457/f65a434cced43990c9fcfac745d49537/Functional/allure-report-ee/index.html

image


**WebAPI Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37457/31214569cac8b7bbf0a0b254b0615eae/WebApi/console-error-logs.html
image

image

**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37457/8a242f961c9ae6720fa50b21f26a5fce/WebApi/console-error-logs.html
image

image

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
We have faced some PAT and static test failures because of this PR while merging hence moving it back to Extended Testing.

**Pull request merged**
