### PR TITLE
fixed word typo

### PR DESCRIPTION
**Pull request by ledian-hymetllari**
### Fixed Issues (if relevant)

1. Fixed word typo

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15907) <br/>All committers have signed the CLA.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-1925](https://jira.corp.magento.com/browse/ENGCOM-1925) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@ledian-hymetllari thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by ledian-hymetllari** [comment]
@orlangur can you help me how to fix this travis continous integration error please ? Thank you.

**Comment by orlangur** [comment]
@ledian-hymetllari I don't see any failures at the moment.

**Comment by magento-engcom-team** [comment]
Hi @ledian-hymetllari. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.6 release.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Comment by ledian-hymetllari** [comment]
@orlangur i see , it looks good now. It is ready for merge.

**Pull request merged**
