### PR TITLE
#1291 - moved dependencies in correct module

### PR DESCRIPTION
**Pull request by tzyganu**
Issue #1291 was marked as closed but not all the problems reported there were fixed.  
I moved some dependencies in the correct module.  
One side effect of this is that I eliminated one dependency from the EAV module to the Catalog module.  
There are others, but I'm working on them :smile: 

Summary:
- moved preference for `Magento\Authorization\Model\UserContextInterface` in the Authorization module
- moved catalog references from EAV module to catalog module

### CODE REVIEW

**Comment by tzyganu** [comment]
some tests are failing,  because of [this line](https://github.com/magento/magento2/blob/develop/app/code/Magento/Directory/Model/Currency/Import/Webservicex.php#L17). You cannot have concatenation in a constant. But that's not my fault.

**Comment by mazhalai** [comment]
@tzyganu Please sync with develop. Builds errors have been fixed.

**Comment by strajeru** [comment]
@mazhalai Done, but something else fails `The command "sudo apt-get update -qq" failed and exited with 100 during .`. Can you restart this?

**Comment by mazhalai** [comment]
@strajeru possibly a travis issue. Restarted build.

**Comment by okorshenko** [comment]
Internal ticket: MAGETWO-52471

**Comment by okorshenko** [comment]
@tzyganu your pull request merged to develop branch. Thank you for your contribution.

**Pull request merged**
