### PR TITLE
fix strpos args order

### PR DESCRIPTION
**Pull request by quasilyte**

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22054) <br/>All committers have signed the CLA.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4618](https://jira.corp.magento.com/browse/ENGCOM-4618) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@quasilyte thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by orlangur** [comment]
@quasilyte please sign CLA though.

Can this automated check be integrated easily?

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
