### PR TITLE
Update laminas feed to be PHP8 compatible

### PR DESCRIPTION
**Pull request by hws47a**
### Description (*)

Set laminas feed version as ^2.13.0 to be PHP8 compatible

It turned out that it's already updated in composer.lock to 2.13.1 as it was allowed by `^2.9.0`. 
So no packages are actually updated. Probably no testing needed.

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/527

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31340

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hws47a** [comment]
@magento run all tests

**Comment by hws47a** [comment]
@magento run Unit Tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes from this PR.

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Unit Tests

**Pull request merged**
