### PR TITLE
[MFTF] Adding AdminGoToOrderStatusPageActionGroup

### LINKED ISSUE #31624: [Issue] [MFTF] Adding AdminGoToOrderStatusPageActionGroup
This issue is automatically created based on existing pull request: magento/magento2#31603: [MFTF] Adding AdminGoToOrderStatusPageActionGroup

---------
### Description (*)
AdminGoToOrderStatusPageActionGroup has been added
Tests have been updated with AdminGoToOrderStatusPageActionGroup

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
AdminGoToOrderStatusPageActionGroup has been added
Tests have been updated with AdminGoToOrderStatusPageActionGroup

### Resolved issues:
1. [x] resolves magento/magento2#31624: [MFTF] Adding AdminGoToOrderStatusPageActionGroup

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8615](https://jira.corp.magento.com/browse/ENGCOM-8615) has been created to process this Pull Request

**Comment by sidolov** [comment]
@magento create issue

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** Functional Tests EE are failed

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
