### PR TITLE
[MFTF] Final set of changes to improve the MFTF tests

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
This PR contains all other changes I introduced to MFTF and some more:
- Unified `stepKey` to be `camelCase` (lower first)
- Added `ActionGroup` suffix to all Action Groups
- Updated documentation to follow best practices

### Fixed Issues (if relevant)
1. magento/magento2#26331

### Manual testing scenarios (*)
Run MFTF tests for:
- https://github.com/magento/magento2
- https://github.com/magento/partners-magento2b2b
- https://github.com/magento/partners-magento2ee
- https://github.com/magento/magento2-page-builder
- https://github.com/magento/magento2-page-builder-ee

### Related Pull Requests
- https://github.com/magento/magento2/pull/26570
- https://github.com/magento/partners-magento2b2b/pull/44
- https://github.com/magento/partners-magento2ee/pull/133
- https://github.com/magento/magento2-page-builder/pull/369
- https://github.com/magento/magento2-page-builder-ee/pull/104
- https://github.com/magento/magento2-functional-testing-framework/pull/563

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

I've merged `2.4-develop` that introduced some new issues in the meantime :man_facepalming:

**Comment by fooman** [comment]
Appreciate the effort you are putting into this but do want to highlight that renaming existing actionGroups will be hard on early adopters using MFTF to test extensions across multiple Magento versions.

For example we would have in our test
```
        <before>
            <actionGroup ref="logout" stepKey="logout"/>
            <actionGroup ref="LoginAsAdmin" stepKey="loginAsAdmin"/>
        </before>
```

After this PR gets merged we will need to change the above depending if we want to test against 2.3 or 2.4. Are there any strategies that would avoid us having to maintain separate branches (I am still hopeful that we don't need separate branches for the code itself).

**Comment by lbajsarowicz** [comment]
This will be covered for 2.3.* with `Deprecated` syntax from MFTF 2.6.0.
I mean - you'll be noticed that with Magento 2.4 the Action Group will be unavailable.

**Comment by fooman** [comment]
So you are essentially confirming that there is no way to have the same test run on 2.3 and 2.4 that references the existing ActionGroups?

The rename change itself is doable however just maintaining different branches (just for the tests) is something I would want to avoid (and probably Marketplace too if they ever are going to support MFTF on submitted extensions).

**Comment by lbajsarowicz** [comment]
That's actually something that bothers me too.
Until 2.4 is released, we have huge field to address the issue.

Let me talk with @okolesnyk to find the best solution for such case.

For me it's super-important to finally have consistent and clean naming pattern, that will be forced with XSD at some point of time.

**Comment by fooman** [comment]
okay great - will follow what you can think of.

What might be workable from my point of view would be a more generous deprecation period:

Keep the old actionGroup names available so something like logout extends adminLogoutAction Group or whatever the exact name is. Please note that this would only work if it was possible to extend an already extended actionGroup which is currently not supported. These intermediate group names would then be removed with Magento 2.5. That would allow someone to use the improved names for any new work. And the old ones can slowly be phased out as support for Magento 2.3 gets dropped over time.

**Comment by lenaorobei** [comment]
@lbajsarowicz is this PR still actual? Or we will go module by module?

**Comment by lbajsarowicz** [comment]
We won't be able to do it in one PR.
Before things get merged, we have hundreds of conflicts :(

**Pull request closed without merging**
