### PR TITLE
Fix price discrepancies with some tax configurations

### LINKED ISSUE #28334: Price filter ignores inclusion of tax
### Preconditions
1.I have set Backend Catalog Price as a Excluding Tax And Front side Display Product Price in Catalog set as Including Tax.
2. Magento 2.3.3p2
3. Magento 2.4-develop

### Steps to reproduce
Magento 2.3.3p2
Go to Backend and set this Tax Calculation configuration
Stores -> Configuration -> Sales -> Tax
46853224-19609900-ce1b-11e8-9d9a-c7043df60132

Stores -> Taxes -> Tax Zones and Rates
46853275-3b5a1b80-ce1b-11e8-8b46-79b159ef5de4

Stores -> Taxes -> Tax Rules
46853330-562c9000-ce1b-11e8-8add-1537e0066fdd

Go to Front end listing page and filter it by Price Range 40 to 50
### Expected result
In listing Page After Price filter Display result between 40 to 50
## Actual result
In listing Page After Price filter Display result in some products are displayed greater than 50. Please check below screen shot .
46853576-2e89f780-ce1c-11e8-89ca-d7265d07baf3

### PR DESCRIPTION
**Pull request by blmage**
### Description (*)

This PR introduces several reusable concepts:

- declarative, language-agnostic modifiers for price expressions (using language-specific builders),
- resolvers for [Elasticsearch scripts](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/modules-scripting.html) (allowing to adapt the aggregation / filter / sort behaviors of one or more fields),
- AST for [Lucene expressions](https://www.elastic.co/guide/en/elasticsearch/reference/7.13/modules-scripting-expression.html) (allowing to write performant ES scripts, at the expense of having to work on numbers only), 

and uses them to fix the discrepancies that arise when indexed prices need to be converted due to the tax configuration.

This concerns at least:

- price filter in the layered navigation,
- price filter in the advanced search.  
- sorting on prices in any product list.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#28334

### Manual testing scenarios (*)

1. See magento/magento2#28334

### Questions or comments

- The PR also fixes the layered navigation when search modules are disabled.
- The scripting feature is available on all Elasticsearch versions since at least **5.0.0**.
- I've not added any test yet, given how involved this PR is, but this is planned (hopefully with some help!) if it goes any further.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by blmage** [comment]
@magento run all tests

**Comment by blmage** [comment]
@magento run all tests

**Comment by blmage** [comment]
@magento run all tests

**Comment by blmage** [comment]
@magento run all tests

**Comment by blmage** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests, WebAPI Tests

**Comment by blmage** [comment]
@magento run all tests

**Comment by blmage** [comment]
@magento run all tests

**Comment by blmage** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, WebAPI Tests

**Comment by blmage** [comment]
@magento run Integration Tests

**Comment by engcom-Hotel** [comment]
Hello @blmage,

Thanks for your contribution!

We request you to please resolve the conflicts so that we can move further with this PR.

Thanks

**Pull request closed without merging**
