### PR TITLE
Redirecting users to sales order history page

### PR DESCRIPTION
**Pull request by ajithkumar-maragathavel**
### Description (*)

If the guest user visits _http://local.magento.com/sales/guest/form/_ in Magento, then It will display a page with the Orders and Returns form. 

But when the logged-in users visit  _http://local.magento.com/sales/guest/form/_ in Magento, then It will redirect to the customer dashboard page.

If we redirect the user to the sales order history page instead of customer dashboard page. It would provide more user experience.
Therefore, I changed the redirection URL to the sales order history page.

### Manual testing scenarios (*)

1. Access the URL as the guest user, It redirects to the order and returns form.
2. Access the URL as the logged-in user, It redirects to the sales order history page.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @ajithkumar-maragathavel,
Your change looks good to me. 
Could you review failing tests and update your changes/tests itself accordingly?

**Comment by ajithkumar-maragathavel** [comment]
@ihor-sviziev Thanks for the review. I have fixed the integration test failure and static test warning. Please review it.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7463](https://jira.corp.magento.com/browse/ENGCOM-7463) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

1. Access the URL as the logged-in user 
(_http://local.magento.com/sales/guest/form/_ in my case)

**Before:** :heavy_multiplication_x: redirected to **My Account** page;
Peek 2020-04-22 13-30

**After:** :heavy_check_mark: redirected to the **sales order history** page.
Peek 2020-04-22 14-14

2. Access the URL as the **guest** user

**Actual Result:**
:heavy_check_mark: redirected to **Orders and Returns** page;
Peek 2020-04-22 14-27

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

**Pull request merged**
