### PR TITLE
Improve swatch table overflow handling

### PR DESCRIPTION
**Pull request by Cyanoxide**
### Description (*)
Updates swatches.css to add overflow:auto to the three swatch tables (text, dropdown & visual) to allow for scrolling if the amount of inputs exceeds the available space and increase the min width of inputs (150px) within the table for better usability. 

Intentionally left original input width (50px) as a fallback.

### Fixed Issues (if relevant)

1. magento/magento2#19932: Fix Swatch Overflow issue
2. magento/magento2#19933: [backport] Fix Swatch Overflow issue

### Manual testing scenarios (*)

1. Add multiple store view and languages to your store (Our store has 19 but you should be able to reach replicate the issue with less)
2. Open an attribute page within the Admin area to configure (Stores > Product > Any attribute).
3. Table inputs at the bottom for languages should be too small to to use effectively
4. If 3. isn't true add more store views, the more that are added the smaller the input fields get.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21421) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @Cyanoxide. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by Cyanoxide** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Cyanoxide. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Cyanoxide, here is your [new Magento instance](https://pr-21421.instances.magento-community.engineering).
Admin access: [https://pr-21421.instances.magento-community.engineering/admin](https://pr-21421.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-21421.instances.magento-community.engineering).
Admin access: [https://pr-21421.instances.magento-community.engineering/admin](https://pr-21421.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4372](https://jira.corp.magento.com/browse/ENGCOM-4372) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@Cyanoxide thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request merged**
