### PR TITLE
fix for tier price 0 when saving product second time

### PR DESCRIPTION
**Pull request by keyurshah070**
### Fixed Issues (if relevant)

1. magento/magento2#25195: Issue with tier price 0 when saving product second-time

### Manual testing scenarios (*)

1. Set the tier price 0 as discussed steps in ticket
2. Now I can save the tier price 0 for the second time

Screenshot 2019-10-21 at 15 41 44

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello @keyurshah070, thank you for your contribution. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) all changes should be covered by tests. Could you please cover your fix by automated tests?
Thank you!

**Comment by keyurshah070** [comment]
Yes, sure I will check this @dmytro-ch

**Comment by keyurshah070** [comment]
What kind of automated test you want? and how can I create this? @dmytro-ch

**Comment by dmytro-ch** [comment]
Hi @akamuraasai, this case should be covered at least by unit test `\Magento\Catalog\Test\Unit\Model\Attribute\Backend\TierPrice\UpdateHandlerTest`.

**Comment by dmytro-ch** [comment]
Hi @keyurshah070, this case should be covered at least by unit test in `\Magento\Catalog\Test\Unit\Model\Attribute\Backend\TierPrice\UpdateHandlerTest`.

**Comment by VladimirZaets** [comment]
@keyurshah070, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Pull request closed without merging**
