### PR TITLE
[Forwardport] Add integration tests for product urls rewrite generation

### PR DESCRIPTION
**Pull request by rostyslav-hymon**
### Original Pull Request 
 https://github.com/magento/magento2/pull/13567
### Description
This pull request contains integration tests for the product url rewrite generation. We were trying to fix the permanent redirection issue when updating an url_key at store level (see the related issues below).

The issue was caused by `$this->urlPersist->deleteByData` being executed before the replace process.
We discovered that, in the 2.2-dev branch, the issue was fixed by side effect in this commit: a0d3a637a.  This PR just provide the tests we were using when fixing the issue but the fix itself is already merged (see: https://github.com/magento/magento2/commit/a0d3a637a08c2efa444a4fa259ac9d0d8100a113#diff-4e1fd4e484fc5142fc23f8ef0cde6718L53).

#### Related to 
 * https://github.com/magento/magento2/issues/13240#issuecomment-359865615
 * https://github.com/magento/magento2/issues/10073

#### Maybe related to
 * https://github.com/magento/magento2/issues/8227
 * https://github.com/magento/magento2/issues/5863
 * https://github.com/magento/magento2/issues/8957

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by sunilk4y** [comment]
Is there any patch available to fix this issue, or we have to keep waiting for 2.3.0 (
 any tentative date for 2.3.0 release?
 We have more than 1,000 products with urls like this https://www.makevana.com.au/catalog/product/view/id/4827/s/gold-plated-sterling-silver-clover-leaf-earrings/category/226/ and its very annoying and hurting indexing.

**Comment by PiroozMB** [comment]
@sunilk4y they don't just care about you and me. They're making fun of us and making money for themselves. You can never find a correct way of fixing their bugs in old versions and they leave people with no answer. very selfish.  
@rostyslav-hymon

**Comment by miguelbalparda** [comment]
@piroozmb you are acting like a customer and you are not entitled to that in an OSS. Somebody put their effort to fix this in their own free time and you are complaining because you just feel like it. If you need a patch before it’s officialy released you can get the diff and apply it manually via CLI. Just add .diff to any pull request URL and you’ll get the raw diff.

**Comment by PiroozMB** [comment]
@miguelbalparda which .diff are you talking about. you see on git thousands threads about this issue and each of them has its own diff. by the way if you are not official magento evelopers and you put this as a solution here on git and you haven't tested it not knowing that it's not working!

**Comment by wasim-bajwa-rltsquare** [comment]
Facing the same issue in magento 2.2.5 version. Also checked the later versions 2.2.7 and 2.3 as well, the issue is still there.

**Comment by cygnet-jmcharadva** [comment]
Facing the same issue with magento 2.3.1 version. Is there any solution?

**Pull request merged**
