### PR TITLE
#10824 add name for order items grid default renderer block

### PR DESCRIPTION
**Pull request by Zefiryn**
Add name for default renderer block of order items to allow other modules reference it.

### Fixed Issues (if relevant)

1. magento/magento2#10824: Cannot add new columns to item grid in admin sales_order_view layout

### Manual testing scenarios
1. In custom module create file `view/adminhtml/layout/sales_order_view.xml` with the following content
```
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="order_items">
            <arguments>
                <argument name="columns" xsi:type="array">
                    <item name="test_column" xsi:type="string" translate="true">Test Header</item>
                </argument>
            </arguments>
            <referenceBlock name="default_order_items_renderer">
                <arguments>
                    <argument name="columns" xsi:type="array">
                        <item name="test_column" xsi:type="string" translate="true">col-test</item>
                    </argument>
                </arguments>
            </referenceBlock>

            <block class="Magento\Sales\Block\Adminhtml\Items\Column\DefaultColumn"
                   name="column_test_column"
                   template="Vendor_Module::test.phtml" group="column" />
        </referenceBlock>
    </body>
</page>
```
2. create file view/adminhtml/templates/test.phtml file with content
```
Test column
```
3. Go to the order view page.
4. Column with header "Test Header" is shown with content "Test column"

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by ishakhsuvarov** [comment]
@Zefiryn Thanks for the PR. I think this process may be automated and all blocks which lack name may be updated. Are you interested in that kind of automation?

**Comment by Zefiryn** [comment]
@ishakhsuvarov sure, are you thinking about bin/magento command?

**Comment by ishakhsuvarov** [comment]
@Zefiryn more like one-time fix which updates all the blocks without names. That can be backed up  by static test which would not allow to create new blocks without names.

**Comment by Zefiryn** [comment]
@ishakhsuvarov ok, I will try to work on it in the next 2 weeks and I will push it to this PR.

**Comment by ihor-sviziev** [comment]
@Zefiryn I also prepared similar pull request but for other blocks and got good feedback how it could be fixed in better way. Just take a look at the following comment: https://github.com/magento/magento2/pull/10354#issuecomment-318606882

**Pull request merged**
