### PR TITLE
Upgraded phpstan dependency to 1.1

### PR DESCRIPTION
**Pull request by hostep**
### Description (*)
PHPstan version 1.0 got released earlier this week: https://phpstan.org/blog/phpstan-1-0-released
This PR changes the dependency constraints for phpstan.
This also changes the deprecated `excludes_analyse` config to `excludePaths`.

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/650

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/34604

### Manual testing scenarios (*)
1. Run phpstan on various php files to see if it still works without issues, for example:
```
./vendor/bin/phpstan analyse --level 1 --no-progress --memory-limit=4G --configuration ./dev/tests/static/testsuite/Magento/Test/Php/_files/phpstan/phpstan.neon setup/src/Magento/Setup/Test/Unit/Console/Style/MagentoStyleTest.php
```
(this command comes from https://github.com/magento/magento2/pull/30581#issuecomment-780108973, and also see: https://github.com/magento/magento2/blob/2.4-develop/dev/tests/static/framework/Magento/TestFramework/CodingStandard/Tool/PhpStan.php#L81-L92)

### Questions or comments
Should we still allow version 0.12.x of phpstan to get installed as well, or is that not necessary?

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hostep** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@xmav can we add it to the platform health?

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9331](https://jira.corp.magento.com/browse/ENGCOM-9331) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by xmav** [comment]
Hi @ihor-sviziev 
Yes this could be part of Platform Health. I saw version 1.1.1 - https://github.com/phpstan/phpstan/releases
Could we try it ?

**Comment by xmav** [comment]
(please keep target branch to 2.4-develop)

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @hostep,
Could you update phpstan to latest available version (1.1.1 now)?

**Comment by hostep** [comment]
Done!

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests look not related to changes from this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9331](https://jira.corp.magento.com/browse/ENGCOM-9331) has been created to process this Pull Request

**Review by andrewbess — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, thank you for the review.
[ENGCOM-9331](https://jira.corp.magento.com/browse/ENGCOM-9331) has been created to process this Pull Request

**Comment by xmav** [comment]
@magento import code to Magento-trigger/magento2ce

**Comment by m2-github-services** [comment]
@xmav the branch with the code is successfully imported into the `Magento-trigger/magento2ce` repository. Branch name: `imported-hostep-magento2-34555`.

**Comment by andrewbess** [comment]
I have fixed the merge-conflicts here

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run Unit Tests with env PHP 8.1 with edition CE without extensions magento-commerce/inventory, magento-commerce/adobe-stock-integration, magento-commerce/security-package, magento-commerce/magento2-page-builder, magento-commerce/adobe-ims

**Comment by xmav** [comment]
works fine with a big change set. Tested on 2.4(2.4.3)<=>2.4-develop (https://github.com/magento/magento2/compare/2.4...2.4-develop)

**Comment by xmav** [comment]
@magento import code to Magento-trigger/magento2ce

**Comment by m2-github-services** [comment]
@xmav an error occurred during the Pull Request import.

**Comment by xmav** [comment]
@magento import code to Magento-trigger/magento2ce

**Comment by m2-github-services** [comment]
@xmav the branch with the code is successfully imported into the `Magento-trigger/magento2ce` repository. Branch name: `imported-hostep-magento2-34555`.

**Comment by xmav** [comment]
Hi @hostep @andrewbess 
I would ask for one more change: change version constrain to `~1.1.0`.
Other than that it looks good

Thanks!

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by xmav** [comment]
Functional Tests issue unrelated to changes in this PR.

**Comment by xmav** [comment]
@magento import code to Magento-trigger/magento2ce

**Comment by m2-github-services** [comment]
@xmav the branch with the code is successfully imported into the `Magento-trigger/magento2ce` repository. Branch name: `imported-hostep-magento2-34555`.

**Comment by hostep** [comment]
@xmav:

> I would ask for one more change: change version constrain to ~1.1.0.

Why? Have you read the [backwards compatibility promise for developers](https://phpstan.org/developing-extensions/backward-compatibility-promise)?

> This article talks about classes, interfaces, and methods that can be safely used by extension developers without the risk of breaking in minor versions.

**Comment by xmav** [comment]
Hi @hostep 
Thank you for pointing to that article. Main background under that is to have builds stable. We may change constraints to be more loose over time.

**Comment by hostep** [comment]
Ok thanks, but the problem is that I'll have to send in yet another PR within a week or 2 when version 1.2.0 gets released, so this will be a maintenance nightmare if we want to stay close to the latest version of phpstan I'm afraid.
I can see why you want those constraints set like this for packages where it's not clear how they deal with semantic versioning or backwards compatibilities, but in this case it's pretty clear.

**Comment by xmav** [comment]
even if we will use loose constrain someone should do composer update and push updated composer.lock file to use new version.

**Comment by hostep** [comment]
@xmav: Exactly, and that's a good thing!

So this would allow core Magento to only update phpstan when you want to, but will allow the users of the Magento software to still update phpstan to newer versions, because the users might want to stay closer to the latest version to benefit from new features and bugfixes.

**Comment by hostep** [comment]
@xmav, As predicted, phpstan 1.2.0 was released today: https://github.com/phpstan/phpstan/releases/tag/1.2.0

Since it contains support for new PHP 8.1 features, I believe we should probably upgrade it again over here ... (and maybe this time use `^` instead of `~` notation in the constraints ... 😉 )
If somebody is willing to do so, please do, I'm leaving in holiday for the next 3 weeks, so I won't have time to look into this myself.

Thanks!

**Pull request merged**
