### PR TITLE
Remove backup menu if the backup feature is disabled

### LINKED ISSUE #29280: [Issue] Remove backup menu if the backup feature is disabled
This issue is automatically created based on existing pull request: magento/magento2#29222: Remove backup menu if the backup feature is disabled

---------

### Preconditions: (*)

This PR will remove the backup menu in backend if the backup feature is disabled in Configuration

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Steps to reproduce (*)

1. Go to stores -> configurations, Advanced, system. DIsable backup 

image

2. Clear cache
3. Check the backup menu:

**Actual Result:** :heavy_multiplication_x: The backup is still located in the menu

Screenshot from 2020-07-27 09-13-19

**Expected Result:** Backup should be excluded from the menu
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

This PR will remove the backup menu in backend if the backup feature is disabled in Configuration

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Go to stores -> configurations, Advanced, system. DIsable backup 

image

2. Clear cache
3. Check the backup menu:

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29280: Remove backup menu if the backup feature is disabled

### CODE REVIEW

**Comment by edenduong** [comment]
@magento run all tests

**Review by lbajsarowicz — CHANGES_REQUESTED** [review]
Why won't just use `dependsOnConfig` on `<add` instruction in `magento/module-backup/etc/adminhtml/menu.xml:10` ?

```xml
<add id="Magento_Backup::system_tools_backup" title="Backups" translate="title" module="Magento_Backup" sortOrder="30" parent="Magento_Backend::system_tools" action="backup/index" resource="Magento_Backup::backup" dependsOnConfig="system/backup/functionality_enabled"/>

```

**Comment by edenduong** [comment]
@lbajsarowicz : Thank you very much ! I forgot that attribute :)

**Review by lbajsarowicz — APPROVED** [review]
Perfect!

**Comment by lbajsarowicz** [comment]
@edenduong That is why we have our community :clap:

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7883](https://jira.corp.magento.com/browse/ENGCOM-7883) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by edenduong** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Go to stores -> configurations, Advanced, system. DIsable backup 

image

2. Clear cache
3. Check the backup menu:

**Before:** :heavy_multiplication_x: The backup is still located in the menu


**After:** :heavy_check_mark: Backup excluded from the menu
image

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @lbajsarowicz, please review test coverage.

**Review by lbajsarowicz — APPROVED** [review]
:heavy_check_mark: Perfect! Thank you.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7883](https://jira.corp.magento.com/browse/ENGCOM-7883) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Charlie** [comment]
@magento run Semantic Version Checker, Integration Tests, Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Pull request merged**
