### PR TITLE
#8193 - fixes negative positive when using numeric value

### PR DESCRIPTION
**Pull request by kanduvisla**
This fixes the issue described in https://github.com/magento/magento2/issues/8193 where getting an option ID for a numeric value could resolve in a negative positive.

### CODE REVIEW

**Comment by kanduvisla** [comment]
The check says ma pull request quality could be better, because I have 1 newline on line 206. Do I need to create a new pull request for this?

**Comment by fooman** [comment]
@kanduvisla you can update your pull request by pushing new commits to the branch on your fork - see http://stackoverflow.com/questions/9790448/how-to-update-a-pull-request

**Comment by vrann** [comment]
@kanduvisla Thanks for the contribution! There are a couple of comments for this PR:
1. please provide steps to reproduce, so that this issue can be verified through the UI. What problems is it causing? Tried to create a new attribute with the dropdown input. Here is the select box which I've got on the Product Edit page. Ids are correct:
screen shot 2017-03-03 at 5 15 27 pm
2. Please write unit or integration tests which will expose the issue by calling the ``$attributeSource->getOptionId("56");``

**Comment by vrann** [comment]
@kanduvisla are you working on this PR? will you be able to provide more details, please?

**Comment by kanduvisla** [comment]
I'm sorry, very busy and everything. I haven't had the time to look into it yet

**Comment by vrann** [comment]
@kanduvisla closing, as far as I was not able to reproduce it based on the give information. Feel free to re-create.

**Pull request closed without merging**
