### PR TITLE
feature/25312 Add Colombian regions

### PR DESCRIPTION
**Pull request by magudelo62**
### Description (*)
Add Colombian Regions

### Fixed Issues (if relevant)

1. magento/magento2#25312: Add Colombian regions

### Manual testing scenarios (*)
Add product to cart
Go to checkout
Select Colombia as shipping / billing country

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by osrecio** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @osrecio. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @osrecio, here is your [new Magento instance](https://pr-25313.instances.magento-community.engineering).
Admin access: [https://pr-25313.instances.magento-community.engineering/admin](https://pr-25313.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by osrecio — APPROVED** [review]
I tested in my local environment and new region are usable.

**Comment by magento-engcom-team** [comment]
Hi @osrecio, thank you for the review.
[ENGCOM-6183](https://jira.corp.magento.com/browse/ENGCOM-6183) has been created to process this Pull Request
:eight_spoked_asterisk: @osrecio, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Bravo** [comment]
Hello @osrecio. Would You please mark this issue with an appropriate [label](https://github.com/magento/magento2/pull/25313#issuecomment-546708724) on Auto-Tests. Thank You.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6183](https://jira.corp.magento.com/browse/ENGCOM-6183) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
