### PR TITLE
Orders-and-Returns-layout-not-proper

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Fixed Issues (if relevant)

1. magento/magento2#20816: Orders and Returns layout not proper
2. Magento 2.3

### Manual testing scenarios (*)

1. Click Orders and Returns link in footer

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-4056](https://jira.corp.magento.com/browse/ENGCOM-4056) has been created to process this Pull Request

**Comment by cedarvinda** [comment]
@amol2jcommerce You did same changes in #20810 PR Thankyou.

**Comment by amol2jcommerce** [comment]
@cedarvinda why you close PR ?
Are you sure both PR changes are same? No different?
@engcom-backlog-nazar please check

**Comment by amol2jcommerce** [comment]
Hi @magento-engcom-team @sidolov please review.

**Comment by amol2jcommerce** [comment]
@magento-engcom-team please review.

**Comment by amol2jcommerce** [comment]
Hi @sidolov @magento-engcom-team please review

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-4134](https://jira.corp.magento.com/browse/ENGCOM-4134) has been created to process this Pull Request

**Pull request merged**
