### PR TITLE
32852: Removed lib/web/FormData.js

### PR DESCRIPTION
**Pull request by anzin**
### Description (*)

I've removed lib/web/FormData.js

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32852: Investigate upgrade to the latest FormData.js

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by anzin** [comment]
@magento run all tests

**Comment by anzin** [comment]
@magento run Unit Tests

**Comment by anzin** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
Note: all modern browsers supports FormData API: https://caniuse.com/mdn-api_formdata

**Review by andrewbess — APPROVED** [review]
Hello @anzin 
Thank you for your contribution.
Your changes are approved.
All tests passed successfully.

**Review by ihor-sviziev — APPROVED** [review]

**Review by Den4ik — APPROVED** [review]

**Comment by anzin** [comment]
@magento run all tests

**Comment by anzin** [comment]
@magento run Sample Data Tests EE, Sample Data Tests B2B

**Comment by anzin** [comment]
@magento run Sample Data Tests EE

**Comment by andrewbess** [comment]
@magento run Functional Tests CE

**Review by andrewbess — APPROVED** [review]

**Comment by anzin** [comment]
@magento run Functional Tests EE

**Comment by andrewbess** [comment]
@magento run Functional Tests B2B

**Comment by sivaschenko** [comment]
@magento run Sample Data Tests EE, Sample Data Tests B2B

**Comment by Den4ik** [comment]
@magento run Functional Tests B2B

**Pull request merged**
