### PR TITLE
[Backport] Empty block rendering in My Account page sidebar fixed using designing changes.

### PR DESCRIPTION
**Pull request by mage2pratik**
### Original Pull Request 
 https://github.com/magento/magento2/pull/20630

### Description (*)

Empty block rendering in My Account page sidebar fixed using designing changes.
### Fixed Issues (if relevant)

1. magento/magento2#19139: Empty block rendering in My Account page sidebar

### Manual testing scenarios (*)

1. Create an Account or Sign In
2. Review left sidebar in My Account section

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by amol2jcommerce** [comment]
PR already created #20835

**Comment by slavvka** [comment]
Closed as duplicate

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-4187](https://jira.corp.magento.com/browse/ENGCOM-4187) has been created to process this Pull Request

**Pull request merged**
