### PR TITLE
Multi Language frontend bug fix

### PR DESCRIPTION
**Pull request by DavidBelicza**
Magento 2 does not translate frontend error messages. These changes fix this bug.

### CODE REVIEW

**Comment by lucscu** [comment]
@antboiko @piotrekkaminski 
What does it means "The Travis CI build failed" ?

**Comment by DavidBelicza** [comment]
@LucScu It means the Magento develop branch does not pass the CI tests: https://travis-ci.org/magento/magento2

**Comment by lucscu** [comment]
@DoveID Why it fails if the pull request is only string modifications?

**Comment by DavidBelicza** [comment]
@LucScu I recommend you to read about git branching how works the basics of git.

**Comment by lucscu** [comment]
@DoveID I know how git works, i don't understand why string modifications do fail the CI? Or the fail is caused by other thing?

**Comment by lucscu** [comment]
@DoveID Why CI check is now passed with same changes?

**Comment by antboiko** [comment]
@DoveID thank you for your contribution, we have ticket MAGETWO-55058 to process this PR.

Best,
Anton.

**Comment by adragus-inviqa** [comment]
/cc https://github.com/magento/magento2/pull/4038

Lots of duplicates here.

**Comment by vkorotun** [comment]
Internal ticket: MAGETWO-56553

**Comment by vkorotun** [comment]
Hey @DoveID can you check with the latest mainline if these phrases aren't being fixed/translated already, since we've merge another similar PR and made some fixes internally. 
Thx.

**Pull request closed without merging**
