### PR TITLE
Removes some code for PHP versions we no longer support.

### LINKED ISSUE #39361: [Issue] Removes some code for PHP versions we no longer support.
This issue is automatically created based on existing pull request: magento/magento2#39202: Removes some code for PHP versions we no longer support.

---------
### Description (*)
Found some code in the codebase that no longer makes sense if we only support PHP 8.2 (soon 8.3?) and higher:
- `libxml_disable_entity_loader ` was deprecated in PHP 8.0: https://php.watch/versions/8.0/libxml_disable_entity_loader-deprecation
- `always_populate_raw_post_data ` was removed in PHP 7.0: https://www.php.net/manual/en/migration70.incompatible.php#migration70.incompatible.removed-ini-directives.features

### Fixed Issues (if relevant)
None

### Manual testing scenarios (*)
1. Check that the changed classes still function like they should function

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### LINKED ISSUE #39368: [Issue] Removes some code for PHP versions we no longer support.
This issue is automatically created based on existing pull request: magento/magento2#39202: Removes some code for PHP versions we no longer support.

---------
### Description (*)
Found some code in the codebase that no longer makes sense if we only support PHP 8.2 (soon 8.3?) and higher:
- `libxml_disable_entity_loader ` was deprecated in PHP 8.0: https://php.watch/versions/8.0/libxml_disable_entity_loader-deprecation
- `always_populate_raw_post_data ` was removed in PHP 7.0: https://www.php.net/manual/en/migration70.incompatible.php#migration70.incompatible.removed-ini-directives.features

### Fixed Issues (if relevant)
None

### Manual testing scenarios (*)
1. Check that the changed classes still function like they should function

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#39361: Removes some code for PHP versions we no longer support.

### PR DESCRIPTION
**Pull request by hostep**
### Description (*)
Found some code in the codebase that no longer makes sense if we only support PHP 8.2 (soon 8.3?) and higher:
- `libxml_disable_entity_loader ` was deprecated in PHP 8.0: https://php.watch/versions/8.0/libxml_disable_entity_loader-deprecation
- `always_populate_raw_post_data ` was removed in PHP 7.0: https://www.php.net/manual/en/migration70.incompatible.php#migration70.incompatible.removed-ini-directives.features

### Fixed Issues (if relevant)
None

### Manual testing scenarios (*)
1. Check that the changed classes still function like they should function

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#39361: Removes some code for PHP versions we no longer support.

### Resolved issues:
1. [x] resolves magento/magento2#39368: Removes some code for PHP versions we no longer support.

### CODE REVIEW

**Comment by hostep** [comment]
@magento run all tests

**Review by Den4ik — APPROVED** [review]
Hey @hostep 
Thanks for the PR, it's great update.
✅ All looks ok for me.

**Comment by Den4ik** [comment]
@magento run Integration Tests

**Comment by engcom-Charlie** [comment]
Hi @hostep,

Thank you for the contribution!

By looking at the code, the changes looks good to me. No manual testing is required for now. We will check the build results further.

If you know any concrete manual step to reproduce, can you please mention the same. 

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Charlie** [comment]
As  per [this](https://github.com/magento/magento2/pull/39202#issuecomment-2437844363), moving this PR to Extended Testing as the build is failing.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by hostep** [comment]
> If you know any concrete manual step to reproduce, can you please mention the same.

I'm not sure what you mean with this question? Could you elaborate a bit?

**Comment by engcom-Charlie** [comment]
Moving this PR to Merge in Progress as build is green

> > If you know any concrete manual step to reproduce, can you please mention the same.
> 
> I'm not sure what you mean with this question? Could you elaborate a bit?

If in case, you might know the exact area/feature where this modified/deleted code was getting used, we can check those features manually.

But for now, as I have mentioned; code looks good to me, hence moving this PR to Merge in Progress as build is green.

**Comment by hostep** [comment]
Makes sense indeed @ihor-sviziev.
I currently lack the time to deal with those, but will try to keep it in the back of my mind unless someone else picks it up.

**Comment by engcom-Charlie** [comment]
@magento create issue

**Comment by hostep** [comment]
@engcom-Charlie: this is very confusing, we should create a **new** issue with a good description based on Ihor's comments

**Comment by ihor-sviziev** [comment]
@hostep I just created task for that https://github.com/magento/magento2/issues/39362

**Pull request merged**
