### PR TITLE
fixed issue "Forgot password form should not available while customer is logged in." #18901

### PR DESCRIPTION
**Pull request by webkul-ratnesh**
### Description (*)

By applying this fix magento is unable to open forgot password page after customer login

### Fixed Issues (if relevant)

1. magento/magento2#18901: Forgot password form should not available while customer is logged in.

### Manual testing scenarios (*)

1. Goto forgot password link
2. Then goto customer login page and do successful login.
3. It should not redirect customer to forgot password page.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @webkul-ratnesh. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by webkul-ratnesh** [comment]
#SQUASHTOBERFEST

**Comment by swnsma** [comment]
Hi @webkul-ratnesh,

Look like issue already has been fixed in 2.2-develop with #19089.
I will close this PR.
Thank you for your time.

**Comment by webkul-ratnesh** [comment]
@swnsma I did not understand what just happen, I requested PR 29 days ago, but other PR accepted with same fix that requested 20 days ago.
Any ways thanks for the information, might be i am missing something.

**Comment by swnsma** [comment]
@webkul-ratnesh,

Looks like there is something wrong with this pull request. Please check [changes](https://github.com/magento/magento2/pull/18903/files). 

I think it has lead to confusion and, as result, that your pull request has stuck. 

I apologize that this has happened with you.
I can advice to check changes in pull request, to be sure that true changes are available for review.

**Pull request closed without merging**
