### PR TITLE
Added a default sort to the categories to sort by position. Fixes magento/catalog-storefront/104

### PR DESCRIPTION
**Pull request by Dnyomo**
### Description (*)

This fixed a bug where the default GraphQL Category method does not sort by category position. By adding this filter results are returned in the correct order.

### Related Pull Requests

https://github.com/magento/catalog-storefront/pull/173

### Fixed Issues (if relevant)

1. Fixes magento/catalog-storefront#104

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lbajsarowicz — CHANGES_REQUESTED** [review]
@Dnyomo The code is fine, however (!) could you provide the use-case (what is the purpose / what area your PR affects)? Thank you for your input!

**Comment by mslabko** [comment]
@magento run Web-API Tests, Integration Tests

**Comment by mslabko** [comment]
@magento run WebAPI Tests

**Comment by Dnyomo** [comment]
I am going to open a new PR to 2.4-develop

**Pull request closed without merging**
