### PR TITLE
[Backport] Fixed add to wishlist issue on product price 0

### PR DESCRIPTION
**Pull request by sreichel**
### Description

Backport magento/magento2#16537

### Fixed Issues (if relevant)

1. magento/magento2#16479:Issue in adding the wishlist of "zero price" product

### Manual testing scenarios

1. Login as a customer in front end of the website.
2, Open product with zero price
2, Click on the wishlist button in the product

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by sidolov** [comment]
Hi @sreichel , please, ensure that the issue https://github.com/magento/magento2/issues/16479 reproduced on 2.1 release line, I see only two labels `Reproduced` applied.

**Comment by sreichel** [comment]
@magento-engcom-team give me 2.1.15 instance

**Comment by magento-engcom-team** [comment]
Hi @sreichel. Thank you for your request.
Unfortunately, I can only deploy instances for `2.2` and `2.3` release lines

**Comment by sreichel** [comment]
@sidolov I havent tested this with 2.1 (running PHP7.1), just checked the code for where `getValue()` is compared to `===false` and found nothing.

How about change related unit tests to "zero price"?

Btw ... MAGETWO-73277 added same code to `app/code/Magento/GroupedProduct/Pricing/Price/ConfiguredRegularPrice.php`. Should this be fixed too?

**Comment by sidolov** [comment]
@sreichel , fix unit test according to changes is a good idea

**Comment by sidolov** [comment]
Hi @sreichel , we can't reproduce this issue on the latest 2.1-develop

**Steps to reproduce:**
1. Log in as a customer in frontend of the website.
2. Click on the wishlist button in the product.

**Actual result:** 
The product is added to the wishlist.

**Comment by sreichel** [comment]
Closed due to lack of time.

**Pull request closed without merging**
