### PR TITLE
#1797: The vertical image is not centered in Category image preview

### LINKED ISSUE #1797: The vertical image is not centered in Category image preview
### Preconditions

1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. A vertical image saved to Media gallery
To save a vertical image to Media Gallery, perform the following steps:
- Open **Search Adobe Stock**
- Click **Filters** 
- Select **Orientation** - **Vertical**
- **Apply Filters** 
- **Save Preview** of one the found Vertical images

### Steps to reproduce (*)
1. Go to **Catalog** - **Categories**
2. Expand **Content** and click **Select from Gallery**
3. Select the previously saved Vertical image and click **Add Selected**
4. Observe the preview image 

### Expected result (*)
The preview image is centered

### Actual result (*)
The preview image is shifted to the left side, empty white space appears on the right side
Selection_076

### PR DESCRIPTION
**Pull request by joweecaquicla**
### Description (*)

This PR will introduce the fix to align the position of vertical images to centre in category image preview.
### Related Pull Requests

N/A
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/adobe-stock-integration/issues/1797

### Manual testing scenarios (*)

1. A vertical image saved to Media gallery
_To save a vertical image to Media Gallery, perform the following steps:_
- Open Search Adobe Stock
- Click Filters
- Select Orientation - Vertical
- Apply Filters
- Save Preview of one the found Vertical images
2. Go to Catalog - Categories
3. Expand Content and click Select from Gallery
4. Select the previously saved Vertical image and click Add Selected
5. The preview image should be centered.
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by joweecaquicla** [comment]
@magento run all tests

**Comment by rogyar** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-29869.instances.magento-community.engineering).
Admin access: [https://pr-29869.instances.magento-community.engineering/admin_fac6](https://pr-29869.instances.magento-community.engineering/admin_fac6)
Login: `09c98926` Password: `36801d24ba35`
Instance will be terminated in up to 3 hours.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8119](https://jira.corp.magento.com/browse/ENGCOM-8119) has been created to process this Pull Request

**Comment by joweecaquicla** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Before** switching to PR
Selection_076
**After**
Selection_080

Added test steps to already existing scenario - https://studio.cucumber.io/projects/131313/test-plan/folders/1054245/scenarios/4484351

**Pull request merged**
