### PR TITLE
Issue/26843: Fix es_US Spanish (United States ) Locale is not support…

### LINKED ISSUE #26843: es_US Spanish (United States ) Locale is not supported in Magento 2.3.4
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1.Create a language pack for the spanish united states with locale as es_US
2. Now run Static-content deploy for the es_US localization with
 php bin/magento setup:static-content:deploy -f --theme="Magento/blank" es_US
3. We are getting an error 
es_US argument has invalid value, please run info:language:list for list of available locales

### Expected result (*)

1. Theme should be deployed for the es_US localization.

### Actual result (*)

1. es_US argument has invalid value, please run info:language:list for list of available locales

### PR DESCRIPTION
**Pull request by vincentle89**
…ed in Magento 2.3.4 #26843

Fix missing code es_US in the list of  available locales

### Description (*)
Fix missing code in the list of  available locales

### Fixed Issues (if relevant)

1. magento/magento2#26843: es_US Spanish (United States ) Locale is not supported in Magento 2.3.4

### Manual testing scenarios (*)
1. Create a store view and set locale as "es_US"
2. Run command: php bin/magento setup:static-content:deploy -f --theme="Magento/blank" es_US

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by vincent-le89** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @vincent-le89. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @vincent-le89, here is your [new Magento instance](https://pr-26857.instances.magento-community.engineering).
Admin access: [https://pr-26857.instances.magento-community.engineering/admin_826a](https://pr-26857.instances.magento-community.engineering/admin_826a)
Login: `88fbb848` Password: `edcc7125083d`
Instance will be terminated in up to 3 hours.

**Review by ihor-sviziev — APPROVED** [review]
Failing functional tests are not related to changes from this PR

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6899](https://jira.corp.magento.com/browse/ENGCOM-6899) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@vincent-le89 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

**Before:**
before

**After:**
after

**Pull request merged**
