### PR TITLE
Remove duplicated var customer.name from email template

### LINKED ISSUE #29087: [Issue] Remove duplicated var customer.name from email template
This issue is automatically created based on existing pull request: magento/magento2#29054: Remove duplicated var customer.name from email template

---------

### Preconditions(*)

There are two customer.name variables (second is in line 13). One can be removed. I removed the first one as the same pattern appears in other email templates.
`/var/www/html/magento24/app/code/Magento/Customer/view/frontend/email/password_reset.html`

### Steps to reproduce(*)
Cleanup, nothing will change.

to check if a variable is available :
1. Go to Admin-> Marketing -> Email Templates -> Add New Template;
2. Load **Reset Password** template;
3. Click on **Insert Variable...** button;

### Expected Result:* 

**Customer Name** template variable is present in list

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ptylek**
### Description (*)

There are two customer.name variables (second is in line 13). One can be removed. I removed the first one as the same pattern appears in other email templates.

### Manual testing scenarios (*)

Cleanup, nothing will change.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29087: Remove duplicated var customer.name from email template

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@magento run all tests
But these changes should not cause any test failure

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7815](https://jira.corp.magento.com/browse/ENGCOM-7815) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Go to Admin-> Marketing -> Email Templates -> Add New Template;
2. Load **Reset Password** template;
3. Click on **Insert Variable...** button;

**After:**

**Customer Name** template variable is present in list

**Pull request merged**
