### PR TITLE
[Catalog] Fixing the Products grid with default values on multi stores

### PR DESCRIPTION
**Pull request by eduard13**
### Description (*)
This PR fixes the products grid to use the default values on multi storing website.

### Fixed Issues (if relevant)

1. magento/magento2#13338: Products grid in admin does not display default values?
2. ...

### Manual testing scenarios (*)
1. Make sure you have a product
2. Make sure you have several store views
3. Set a different value for Product Name for each store view

For more details, check task's steps.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4342](https://jira.corp.magento.com/browse/ENGCOM-4342) has been created to process this Pull Request

**Comment by rogyar** [comment]
**For QA**
This change might affect different product data providers such as CrossSell, UpSell, Grouped Products, Custom Options etc. This change should not bring unexpected behavior since if the data provider is store-related, the corresponding store view is set within a scope of `getData` method. However, all cases need to be tested.

**Comment by sivaschenko** [comment]
Hi @eduard13 we are not able to reproduce the issue on vanilla 2.3-develop. Are you able to reproduce it on the latest codebase and are there any specific steps that should be made?

**Comment by eduard13** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @eduard13, here is your [Magento instance](https://i-21363-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21363-2-3-develop.instances.magento-community.engineering/admin](https://i-21363-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by eduard13** [comment]
@sivaschenko yes, I was able to reproduce it on vanilla. Please make sure you use a different store view for your store, as example:
Having 2 store views for the same store:
- Default
- French

The French is set as default (most probably this is the missed part):
xnip2019-02-25_16-44-55

Then just set the product name for French store view, and check the products grid.
Let me know if any additional info is required.
PS: You still can check the current instance.
Thanks.

**Pull request merged**
