### PR TITLE
#30218 GraphQL returns null address if optional telephone is set as e…

### LINKED ISSUE #30218: GraphQL returns null address if optional telephone is set as empty string
### Preconditions (*)

1. Version 2.4.0 and 2.4-develop
2.

### Steps to reproduce (*)

1.Configure Magento address settings to have telephone number as optional.
2. Using GraphQL add a billing address to a quote using an empty string as the telephone value
3. Execute cart query via GraphQL.  Billing address will return as 'null'

### Expected result (*)

1. Billing address expected to return in GraphQL response with full address details shown
2.

### Actual result (*)

1. billing address returns as null.
2. This is caused because the telephone field in the CartAddressInput in the GraphQL schema is marked as non-nullable. Magento saved the telephone value as null in the quote address when it is passed an empty string.  The address is then validated against the schema when the response is being prepared and fails the schema validation.

### Additional info from Engcom
**Steps to reproduce**
1. From Admin, go to _Stores - Configuration - Customer - Customer Configuration - Name and Address Options_. Set **Show Telephone** to **Optional**
show_telephone
2. Using GraphQL mutation, add a product to Cart
3. Set Billing Address on cart using the following Mutation 
```graphql
mutation {
  setBillingAddressOnCart(
    input: {
      cart_id: "YOrpn8PaE1sNO88W4KTqGlMu1UB6Rpoh"
      billing_address: {
        address: {
          firstname: "Bob"
          lastname: "Roll"
          company: "Magento"
          street: [
            "Magento Pkwy"
            "Main Street"
          ]
          city: "Austin"
          region: "TX"
          postcode: "78758"
          telephone: ""        #<---- note that the telephone is an empty string. 
          country_code: "US"
          save_in_address_book: true
        }
        same_as_shipping: false
      }
    }
  ) {
    cart {
      billing_address {
        firstname
        lastname
        company
        street
        city
        region {
          code
          label
        }
        postcode
        telephone
        country {
          code
          label
        }
      }
    }
  }
}
```
4. Query Cart 
```graphql
query{
  cart(cart_id: "YOrpn8PaE1sNO88W4KTqGlMu1UB6Rpoh"){
    billing_address{
      city
      firstname
      lastname
      telephone
      region{
        code
      }
      street
    }
    items{
      id
      quantity
      product{
        name
      }
    }
  }
}
```
**Actual Result**
Cart query displayed Billing Adress as _null_
```graphql
{
  "data": {
    "cart": {
      "billing_address": null,
      "items": [
        {
          "id": "1",
          "quantity": 3,
          "product": {
            "name": "Sproduct"
          }
        }
      ]
    }
  }
}
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by SaftaArtem**
### Description (*)
I change input and output type for telephone field. From String! to String, because telephone field has 3 states(no, required, optional)

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30218

### Manual testing scenarios (*)
Stores - Configuration - Customer - Customer Configuration - Name and Address Options
Set Show Telephone to
1. No
2. Optional
3. Required

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @SaftaArtem. Good job, thank you for your collaboration. According to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all the changes should be covered by auto-tests. I would ask you to cover this case with an API-funcitonal test. The test will create cart address with no telephone provided and assert that there's no error in return.

Thank you

**Comment by SaftaArtem** [comment]
Hi, *@rogyar, i wrote tests for creating and getting new address without
telephone field*

чт, 19 нояб. 2020 г. в 17:29, Yaroslav Rogoza <notifications@github.com>:

**Comment by rogyar** [comment]
@magento run WebAPI Tests

**Comment by rogyar** [comment]
Hi @SaftaArtem. Good job. In the meantime, could I ask you to sign [Adobe CLA](http://opensource.adobe.com/cla.html). Without your sign, we cannot proceed with processing the PR. 

Thank you.

**Comment by SaftaArtem** [comment]
Done.

пн, 23 нояб. 2020 г. в 14:19, Yaroslav Rogoza <notifications@github.com>:

**Comment by rogyar** [comment]
Hi @SaftaArtem. Please, take a look at the failing test. 

Thank you.

**Pull request merged**
