### PR TITLE
MFTF: Remove risky test that does not have implementation

### LINKED ISSUE #28850: [Issue] MFTF: Remove risky test that does not have implementation
This issue is automatically created based on existing pull request: magento/magento2#28605: MFTF: Remove risky test that does not have implementation

---------
### Description (*)
I am removing test that does not have implementation.
That kind of tests are considered Risky as these does not test anything, but give false assumption that feature is covered with tests.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
I am removing test that does not have implementation.
That kind of tests are considered Risky as these does not test anything, but give false assumption that feature is covered with tests.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28850: MFTF: Remove risky test that does not have implementation

### CODE REVIEW

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7635](https://jira.corp.magento.com/browse/ENGCOM-7635) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento create issue

**Pull request merged**
