### PR TITLE
Wishlist icon not align on mobile view - Fixed - #20502

### PR DESCRIPTION
**Pull request by rschulerdh**
### Description (*)

1. magento/magento2#20502: Wishlist icon not align on mobile view

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by kalpmehta — APPROVED** [review]

**Comment by kalpmehta** [comment]
@rschulerdh Thanks for your contribution. Please sign the CLA otherwise we cannot accept your PR.

**Review by sudheers-kensium — APPROVED** [review]

**Comment by sidolov** [comment]
@rschulerdh please, sign CLA, otherwise, we cannot proceed with your PR

**Comment by rschulerdh** [comment]
@magento  Unfortunately, I can't move on with the procedure. I've signed the CLA several times, but the task is not complete. The page reloads and always the "sign CLA" step is open. How can I proceed in this case?

**Comment by rschulerdh** [comment]
> CLA
Unfortunately, I can't move on with the procedure. I've signed the CLA several times, but the task is not complete. The page reloads and always the "sign CLA" step is open. How can I proceed in this case.

**Comment by sidolov** [comment]
@rschulerdh issue with CLA caused by fact that commit in PR was made by another user - richardschuler. We have few options how to resolve it: make a new commit with correct account and force push the branch or ask richardschuler sign CLA too.

**Comment by kalpmehta** [comment]
Closing this since CLA is not signed.

**Pull request closed without merging**
