### PR TITLE
[Customer] Provides a Patch for Backend Model of Adminhtml

### PR DESCRIPTION
**Pull request by EliasKotlyar**
Provides a Bugfix for loading the backend-model of the customers in the adminhtml.

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
It doesn't looks like good solution

**Comment by EliasKotlyar** [comment]
Hello ihor-sviziev,

Could you please explain why you think that its a bad solution? I couldnt find another solution for loading the Backend-Model of the Customer Attribute in the DataProvider.

Greetings
Elias

**Comment by ihor-sviziev** [comment]
@EliasKotlyar I think collection should execute this method if it's needed.

**Comment by antonkril** [comment]
Agree with @ihor-sviziev. It is not a responsibility of the data provider

**Review by antonkril — CHANGES_REQUESTED** [review]
Consider fixing on collection level, or using different collection here.

**Comment by vrann** [comment]
@EliasKotlyar hi, verifying this pull request and it seems there outstanding items from the previous reviewers. Are you currently working on updating the code?

**Comment by okorshenko** [comment]
@EliasKotlyar thank you for your contribution. Unfortunately we can not accept this PR in current state. 

Thank you

**Pull request closed without merging**
