### PR TITLE
[32029][To 2.4-develop] Mark Framework interfaces as API part 5

### LINKED ISSUE #32029: Mark Framework interfaces as API part 5
The following interfaces should be marked as API in 2.4-develop branch:

1. lib/internal/Magento/Framework/HTTP/AsyncClient/HttpResponseDeferredInterface.php
1. lib/internal/Magento/Framework/HTTP/AsyncClientInterface.php
1. lib/internal/Magento/Framework/Image/Adapter/AdapterInterface.php
1. lib/internal/Magento/Framework/Image/Adapter/ConfigInterface.php
1. lib/internal/Magento/Framework/Indexer/Config/DependencyInfoProviderInterface.php
1. lib/internal/Magento/Framework/Indexer/Table/StrategyInterface.php
1. lib/internal/Magento/Framework/Interception/ConfigInterface.php
1. lib/internal/Magento/Framework/Interception/ConfigLoaderInterface.php
1. lib/internal/Magento/Framework/Interception/ConfigWriterInterface.php
1. lib/internal/Magento/Framework/Interception/DefinitionInterface.php
1. lib/internal/Magento/Framework/Interception/InterceptorInterface.php
1. lib/internal/Magento/Framework/Interception/ObjectManager/ConfigInterface.php
1. lib/internal/Magento/Framework/Interception/PluginListInterface.php
1. lib/internal/Magento/Framework/Locale/AvailableLocalesInterface.php
1. lib/internal/Magento/Framework/Locale/OptionInterface.php
1. lib/internal/Magento/Framework/Mail/EmailMessageInterface.php
1. lib/internal/Magento/Framework/Mail/MimeInterface.php
1. lib/internal/Magento/Framework/Mail/MimeMessageInterface.php
1. lib/internal/Magento/Framework/Mail/MimePartInterface.php
1. lib/internal/Magento/Framework/Message/ExceptionMessageFactoryInterface.php

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixes #32029
### Related Pull Requests

https://github.com/magento/magento2/pull/32168
### Fixed Issues (if relevant)

1. Fixes magento/magento2 #32029>

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by danielrussob** [comment]
@magento run Functional Tests B2B

**Comment by danielrussob** [comment]
I confirm that this PR is just a code cleanup / marked as API some class. We are waiting for tests.

**Comment by danielrussob** [comment]
I confirm that all files mentioned in issue (https://github.com/magento/magento2/issues/32029) are covered

**Comment by danielrussob** [comment]
Hi @Usik2203 , thank you for your contribution

Can you tell me why you have marked:

lib/internal/Magento/Framework/HTTP/AsyncClient/Request.php
lib/internal/Magento/Framework/HTTP/AsyncClient/Response.php
lib/internal/Magento/Framework/Image/Adapter/AbstractAdapter.php
lib/internal/Magento/Framework/Mail/Address.php
lib/internal/Magento/Framework/ObjectManager/ConfigCacheInterface.php
lib/internal/Magento/Framework/ObjectManager/RelationsInterface.php as API?

It's not linked in: https://github.com/magento/magento2/issues/32029

**Comment by Usik2203** [comment]
> Hi @Usik2203 , thank you for your contribution
> 
> Can you tell me why you have marked:
> 
> lib/internal/Magento/Framework/HTTP/AsyncClient/Request.php
> lib/internal/Magento/Framework/HTTP/AsyncClient/Response.php
> lib/internal/Magento/Framework/Image/Adapter/AbstractAdapter.php
> lib/internal/Magento/Framework/Mail/Address.php
> lib/internal/Magento/Framework/ObjectManager/ConfigCacheInterface.php
> lib/internal/Magento/Framework/ObjectManager/RelationsInterface.php as API?
> 
> It's not linked in: #32029

Hi @danielrussob  @aleron75
These classes were marked  for preventing such type of failed static tests
https://github.com/magento/magento2/pull/32175#issuecomment-785755363

Also could i kindly ask you to remove Cleanup label based on this comment
#32735 (comment)

Thanks!

**Review by danielrussob — APPROVED** [review]

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama the branch with code successfully imported into`magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-32729`.

**Pull request merged**
