### PR TITLE
[Backport] Fixed Custom option price calculation is wrong with multi currency when option price type is percentage

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Original Pull Request 
 https://github.com/magento/magento2/pull/19608

### Description (*)

 We have set multi currency custom option with percentage price type now it is working with multi currency switcher.
### Fixed Issues (if relevant)

1. magento/magento2#19561:Custom option price calculation is wrong with multi currency when option price type is percentage

### Manual testing scenarios (*)

1. Set Currency Rates in Magento from Stores > Currency Rates ( Ist -> 70.09, Usd -> 1)
2. Goto Catalog > Product and edit any Simple product.
3. Set custom option typed ‘dropdown’ and add options with Price type ‘percentage’.
4. Go to Front end product details page in which you have created custom options.
5. Change currency from Currency drop down. and now you will get correct price of the custom option.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by miguelbalparda** [comment]
I keep seeing you doing backports for other people's PRs, have you talked with them about that @amol2jcommerce?

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4292](https://jira.corp.magento.com/browse/ENGCOM-4292) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [new Magento instance](https://pr-21263.instances.magento-community.engineering).
Admin access: [https://pr-21263.instances.magento-community.engineering/admin](https://pr-21263.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Pull request merged**
