### PR TITLE
#25211 Fix first load of RSS New Products, Special Products and Discounts

### PR DESCRIPTION
**Pull request by osrecio**
Fix first load of RSS New Products, Special Products and Discounts

### Description (*)

The first time that try to load rss page, get `\Magento\Framework\Phrase` in `Zend\Feed\Writer\AbstractFeed->setTitle` and is not prepared for recieve `\Phrase`

### Fixed Issues (if relevant)

1. magento/magento2#25211: RSS Feed - first load not working

### Manual testing scenarios (*)

1. Enable standard RSS Feed module.
2. Enable RSS Feed for New Products and Special Products.
3. Proceed to domain.tld/rss
4. Loads correctly

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [] All new or changed code is covered with unit/integration tests (if applicable)
 - [] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by osrecio** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @osrecio. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @osrecio, here is your [new Magento instance](https://pr-25320.instances.magento-community.engineering).
Admin access: [https://pr-25320.instances.magento-community.engineering/admin](https://pr-25320.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @osrecio. Thanks for collaboration.
I investigated this PR, I think the better way to fix it is refactor this method (
https://github.com/magento/magento2/blob/6f1c7e37c316e39ada4c033e937ece141bcee4c5/app/code/Magento/Rss/Model/Rss.php#L82 ). We serialize data to save it in the cache. And at the same time we can unserialize and return this data. It looks like a hack but it will be just one place and we will guarantee that all Phrase objects converted to string

**Comment by VladimirZaets** [comment]
@osrecio, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Pull request closed without merging**
