### PR TITLE
Extend locales validation - include (3 chars) language codes as valid.

### LINKED ISSUE #33996: Filipino (philippines) language translation not working!
### Preconditions (*)

1. Magento 2.3, 2.4, 2.4-develop
2. Multi Store

### Steps to reproduce (*)

- Create a new store view for philippines i.e. philippines

- Go to system -> configuration -> change scope from Default to philippines store view

- Change locale to Filipino (Philippines)

- Install language pack for Filipino i.e. composer require mageplaza/magento-2-filipino-language-pack:dev-master Or can create a custom language pack

- Go to front-end and change Store view form Default to Philippines

### Expected result (*)

1. translation should work on frontend!

### Actual result (*)

exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/vendor/mageplaza/magento-2-filipino-language-pack/language.xml" is invalid:
Element 'code': [facet 'pattern'] The value 'fil_PH' is not accepted by the pattern '[a-z]{2}_([a-zA-Z]{4}_)?[A-Z]{2}'.
Line: 3

Verify the XML and try again.
Exception #1 (Magento\Framework\Config\Dom\ValidationException): Element 'code': [facet 'pattern'] The value 'fil_PH' is not accepted by the pattern '[a-z]{2}_([a-zA-Z]{4}_)?[A-Z]{2}'.
Line: 3

Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/var/www/html/m2-git/vendor/mageplaza/magento-2-filipino-language-pack/language.xml" is invalid:
Element 'code': [facet 'pattern'] The value 'fil_PH' is not accepted by the pattern '[a-z]{2}_([a-zA-Z]{4}_)?[A-Z]{2}'.
Line: 3

### Additional Information (*)

All other locale have code either az_AZ or  az_aAzZ_ZZ, only Filipino language have code `fil_PH` which is different form all other codes.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Bashev**
### Description (*)
#33996 

### Fixed Issues (if relevant)

1. Fixes #33996 

### Manual testing scenarios (*)

1. See details in the issue #33996 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Bashev** [comment]
@magento give me test instance

**Comment by Bashev** [comment]
@magento give me test instance

**Comment by Bashev** [comment]
@magento run all tests

**Review by BarnyShergold — APPROVED** [review]
NIce fix!
Just need to wait for those pesky tests to run.

**Comment by magento-engcom-team** [comment]
Hi @BarnyShergold, thank you for the review.
[ENGCOM-9213](https://jira.corp.magento.com/browse/ENGCOM-9213) has been created to process this Pull Request
:eight_spoked_asterisk: @BarnyShergold, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by Bashev** [comment]
@magento run Functional Tests B2B

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9213](https://jira.corp.magento.com/browse/ENGCOM-9213) has been created to process this Pull Request

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
✔️ QA Passed

Hello @Bashev,

Thanks for the contribution!

I have tested all the scenarios manually in this PR. 

**Preconditions**
Magento 2.4-develop

**Steps to reproduce**
1. Create a new store view named philippines. 
2. Select scope as philippines store view.
3. Select locale Filipino (Philippines).

**Actual Result:** :heavy_check_mark:
Verified that no fatal error should come.

**After** ✔️ 

image

**Before** ✖️ 

image

**Tested all the manual scenarios, no impact on regression testing.**

**Comment by Bashev** [comment]
@magento run all tests

**Comment by Bashev** [comment]
@magento run Functional Tests CE

**Pull request merged**
