### PR TITLE
Replace repetitive actions with Action Groups in AdminUpdateSimpleProductWithRegularPriceOutOfStockTest

### LINKED ISSUE #32584: [Issue] Replace repetitive actions with Action Groups in AdminUpdateSimpleProductWithRegularPriceOutOfStockTest
This issue is automatically created based on existing pull request: magento/magento2#32529: Replace repetitive actions with Action Groups in AdminUpdateSimpleProductWithRegularPriceOutOfStockTest

---------

### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)

Run the test in the local environment and verified that it run successfully

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)

Run the test in the local environment and verified that it run successfully

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32584: Replace repetitive actions with Action Groups in AdminUpdateSimpleProductWithRegularPriceOutOfStockTest

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Integration Tests

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8966](https://jira.corp.magento.com/browse/ENGCOM-8966) has been created to process this Pull Request

**Comment by engcom-Oscar** [comment]
@magento create issue

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @kate-kyzyma, can you resolve conflicts? Thanks!

**Comment by kate-kyzyma** [comment]
Hi, @gabrieldagama 

The merge conflict is resolved.

Thanks.

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests CE

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by eduard13** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Pull request merged**
