### PR TITLE
Added DHL Setting to allow user to choose whether DHL quotes include any TAX or not.

### LINKED ISSUE #30035: [Issue] Added DHL Setting to allow user to choose whether DHL quotes include any TAX or not.
This issue is automatically created based on existing pull request: magento/magento2#30020: Added DHL Setting to allow user to choose whether DHL quotes include any TAX or not.

---------

### Description (*)
The DHL Shipping module included in Magento receives shipping quotes direct from DHL's API servers. If the shipment is going between two countries where TAX would be charged to the shippers account on the transaction by DHL, then this TAX is included in the totals received back from the DHL servers and is included in the price that is used by Magento to display to the user.

Currently, whether TAX is included in the quote is not configurable.

This PR provides an option that allows the seller to choose whether the price that is passed on to Magento from DHL includes any TAX that DHL charges.

This provides the ability to pass shipping prices onto Magento excluding TAX, and then have the regular Magento tax rules determine whether any TAX should be added on to the shipping, in accordance with the TAX rules. 

Without this setting it would be extremely easy to misconfigure your store and double account for tax on certain purchases.

The default option for the setting, is on, which is the current position in 2.4-develop, so there should be no impact on existing users. The setting can be enabled if required.

Included in this PR is a minor fix at the beginning of the CollectRates function, which clears any existing rates from previous calls to CollectRates. This is not a problem with running under Magento as this never happens, but it now does within integration tests, which call CollectRates multiple times on the same object (it does now additional tests have been added). Without the fix, each time CollectRates is called, it was adding the collected rates ontop of existing rates from previous calls. This change ensures that the module always starts with no rates when CollectRates is called. If you would like this split out and its own issue creating, then let me know.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Integration tests included

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by gwharton**
### Description (*)
The DHL Shipping module included in Magento receives shipping quotes direct from DHL's API servers. If the shipment is going between two countries where TAX would be charged to the shippers account on the transaction by DHL, then this TAX is included in the totals received back from the DHL servers and is included in the price that is used by Magento to display to the user.

Currently, whether TAX is included in the quote is not configurable.

This PR provides an option that allows the seller to choose whether the price that is passed on to Magento from DHL includes any TAX that DHL charges.

This provides the ability to pass shipping prices onto Magento excluding TAX, and then have the regular Magento tax rules determine whether any TAX should be added on to the shipping, in accordance with the TAX rules. 

Without this setting it would be extremely easy to misconfigure your store and double account for tax on certain purchases.

The default option for the setting, is on, which is the current position in 2.4-develop, so there should be no impact on existing users. The setting can be enabled if required.

Included in this PR is a minor fix at the beginning of the CollectRates function, which clears any existing rates from previous calls to CollectRates. This is not a problem with running under Magento as this never happens, but it now does within integration tests, which call CollectRates multiple times on the same object (it does now additional tests have been added). Without the fix, each time CollectRates is called, it was adding the collected rates ontop of existing rates from previous calls. This change ensures that the module always starts with no rates when CollectRates is called. If you would like this split out and its own issue creating, then let me know.

### Approval Request

https://jira.corp.magento.com/browse/MC-38176

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/30035

### Manual testing scenarios (*)

1. Integration tests included

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30035: Added DHL Setting to allow user to choose whether DHL quotes include any TAX or not.

### CODE REVIEW

**Comment by gwharton** [comment]
@magento run all tests

**Comment by gwharton** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento create issue

**Review by aleron75 — COMMENTED** [review]
Hello @gwharton thanks for your contribution.

The failing test is due to the fact that this PR introduces new functionality (a config fieldset) that would lead to a MINOR version increase. 

Let me discuss this internally, we'll come back to this PR asap.

**Review by aleron75 — DISMISSED** [review]
The failing test shouldn't cause any issue, thus I approve.

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-8299](https://jira.corp.magento.com/browse/ENGCOM-8299) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Approval request: https://jira.corp.magento.com/browse/MC-38176

**Review by aleron75 — APPROVED** [review]

**Comment by engcom-Delta** [comment]
@gwharton, thanks for your contribution.Please resolve the conflicts to move on this PR

**Pull request closed without merging**
