### PR TITLE
Resolve Missing "Customer Group Price" label when adding new customer group price rule issue24640

### LINKED ISSUE #24640: Missing "Customer Group Price" label when adding new customer group price rule
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Create New Product form
3. Click "Advanced Pricing"
4. In "Customer Group Price", click "Add"
=> label "Customer Group Price" suddenly disappear.

### Expected result (*)

image

### Actual result (*)

image

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#24640: Missing "Customer Group Price" label when adding new customer group price rule

### Fixed Issues (if relevant)

1. magento/magento2#24640: Missing "Customer Group Price" label when adding new customer group price rule

### Manual testing scenarios (*)

1. Go to backend
2. Create New Product form
3. Click "Advanced Pricing"
4. In "Customer Group Price", click "Add"
=> label "Customer Group Price" suddenly disappear.

#### Expected result

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-6009](https://jira.corp.magento.com/browse/ENGCOM-6009) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @edenduong 

During testing, we faced the issue

**_Problem:_** After clicking the "Add" button, the "Advanced Pricing" title truncated

**Actual Result:**
problem

@edenduong Could you take a look, please?

Thanks!

**Comment by edenduong** [comment]
I will continue to fixing it.

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-24641.instances.magento-community.engineering).
Admin access: [https://pr-24641.instances.magento-community.engineering/admin](https://pr-24641.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Pull request closed without merging**
