### PR TITLE
Fixed No result searches for queries with non alphanumeric characters like "1:20"

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
Fixed No result searches for queries with non alphanumeric characters like "1:20"
### Description (*)

Fixed No result searches for queries with non alphanumeric characters like "1:20"
### Fixed Issues (if relevant)

1. magento/magento2#20878: No result searches for queries with non alphanumeric characters like "1:20"

### Manual testing scenarios (*)

1. N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by ghost** [comment]
@ravi-chandra3197 This not fix the problem

**Comment by ravi-chandra3197** [comment]
@engcom-backlog-nazar
I have got the following result after this patch

search results for test 1 20

**Comment by ghost** [comment]
@ravi-chandra3197 try  sku like 42:20 ?

**Comment by rogyar** [comment]
Hi @ravi-chandra3197. Thank you for your collaboration. I'm closing this PR because of inactivity. Also, please note that the related issue is closed.

**Pull request closed without merging**
