### PR TITLE
#22018 Add a form option to agreement functionality

### PR DESCRIPTION
**Pull request by kisroman**
### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/22018

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by madonzy** [comment]
@kisroman can you please fix pipe issues so merge could proceed?

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by josefbehr** [comment]
@madonzy I restarted all tests except codacy, there I cannot restart the process. @magento-engcom-team can you do this or give me the permission to do it?

**Review by josefbehr — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @josefbehr, thank you for the review.
[ENGCOM-5928](https://jira.corp.magento.com/browse/ENGCOM-5928) has been created to process this Pull Request
:eight_spoked_asterisk: @josefbehr, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @kisroman 
During testing we faced with the issue

_**Problem:**_ There are no terms and conditions on the consumer creation page

**Manual testing scenario:**
1. Go to Stores->Configuration->Sales->Checkout->Checkout Options;
2. Set **Enable Terms and Conditions** to **Yes**;
3. Go to Stores->Terms and Conditions-> Add New Condition;
4. Fill all required fields and Select **Customer Registration** from **Forms to Use In** menu;
5. Save Condition;
6. Go to Storefront->Create an Account;

**Actual Result:** 
"Terms and Conditions" block is missing
after

@kisroman Could you take a look, please?

Thanks!

**Comment by kisroman** [comment]
@engcom-Alfa, you were right. Last refactoring cleaned needed line. Update the branch and try again.

**Comment by josefbehr** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @josefbehr. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @josefbehr, here is your [new Magento instance](https://pr-22185.instances.magento-community.engineering).
Admin access: [https://pr-22185.instances.magento-community.engineering/admin](https://pr-22185.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by josefbehr — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @josefbehr, thank you for the review.
[ENGCOM-5928](https://jira.corp.magento.com/browse/ENGCOM-5928) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
Hey @kisroman  Could you please fix the static tests

**Comment by slavvka** [comment]
@engcom-Foxtrot could you please take a look at static tests?

**Comment by slavvka** [comment]
This PR is waiting for Architectural review

**Comment by slavvka** [comment]
The MINOR changes don't require approval so proceed with the fixing and delivery

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Please stabilize tests

**Comment by engcom-Charlie** [comment]
Hi @kisroman, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
