### PR TITLE
Fixed 'Undefined class constant' error when interceptor is generated.

### LINKED ISSUE #28981: [Issue] Fixed 'Undefined class constant' error when interceptor is generated.
This issue is automatically created based on existing pull request: magento/magento2#28797: Fixed 'Undefined class constant' error when interceptor is generated.

---------
### Summary (*)
1. Magento 2.4-develop
2. Since constant is [declared as private](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Theme/Block/Html/Title.php#L27) it's not accessible from parent classes.
3. Since it used [with `static` keyword](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Theme/Block/Html/Title.php#L104), PHP will search it within class instance.
4. Class instance will be an instance of generated `Interceptor` without access to private variables of child classes.
5. This will lead to an 'Undefined class constant' error.

### Examples (*)
1. Create a plugin for `Magento\Theme\Block\Html\Title` class:

    ```xml
    <type name="Magento\Theme\Block\Html\Title">
        <plugin name="titlePlugin" type="Magento\Theme\Plugin\TitlePlugin" />
    </type>
    ```

    ```php
    <?php

    namespace Magento\Theme\Plugin;

    class TitlePlugin
    {
        /**
         * @param mixed $subject
         * @param mixed $result
         * @return mixed
         */
        public function afterGetPageHeading(
            $subject,
            $result
        ) {
            return $result;
        }
    }
    ```

2. Open frontend.
3. You'll see an error:

    ```
    Error: Undefined class constant 'XML_PATH_HEADER_TRANSLATE_TITLE' in app/code/Magento/Theme/Block/Html/Title.php:104 
    Stack trace: 
    #0 app/code/Magento/Theme/Block/Html/Title.php(82): Magento\Theme\Block\Html\Title->shouldTranslateTitle() 
    #1 generated/code/Magento/Theme/Block/Html/Title/Interceptor.php(32): Magento\Theme\Block\Html\Title->getPageHeading() 
    #2 app/code/Magento/Theme/view/frontend/templates/html/title.phtml(12): Magento\Theme\Block\Html\Title\Interceptor->getPageHeading()
    ...
    ```

### Proposed solution
Another way to solve this bug - is to declare constant as public instead of private.
If you think it should be public - I'll update PR.

### PR DESCRIPTION
**Pull request by vovayatsyuk**
### Description (*)
1. Since constant is [declared as private](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Theme/Block/Html/Title.php#L27) it's not accessible from parent classes.
2. Since it used [with `static` keyword](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Theme/Block/Html/Title.php#L104), PHP will search it within class instance.
3. Class instance will be an instance of generated `Interceptor` without access to private variables of child classes.
4. This will lead to an 'Undefined class constant' error.

### Manual testing scenarios (*)
1. Create a plugin for `Magento\Theme\Block\Html\Title` class:

    ```xml
    <type name="Magento\Theme\Block\Html\Title">
        <plugin name="titlePlugin" type="Magento\Theme\Plugin\TitlePlugin" />
    </type>
    ```

    ```php
    <?php

    namespace Magento\Theme\Plugin;

    class TitlePlugin
    {
        /**
         * @param mixed $subject
         * @param mixed $result
         * @return mixed
         */
        public function afterGetPageHeading(
            $subject,
            $result
        ) {
            return $result;
        }
    }
    ```

2. Open frontend.
3. You'll see an error:

    ```
    Error: Undefined class constant 'XML_PATH_HEADER_TRANSLATE_TITLE' in app/code/Magento/Theme/Block/Html/Title.php:104 
    Stack trace: 
    #0 app/code/Magento/Theme/Block/Html/Title.php(82): Magento\Theme\Block\Html\Title->shouldTranslateTitle() 
    #1 generated/code/Magento/Theme/Block/Html/Title/Interceptor.php(32): Magento\Theme\Block\Html\Title->getPageHeading() 
    #2 app/code/Magento/Theme/view/frontend/templates/html/title.phtml(12): Magento\Theme\Block\Html\Title\Interceptor->getPageHeading()
    ...
    ```

### Questions or comments
Another way to solve this bug - is to declare constant as public instead of private.
If you think it should be public - I'll update PR.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28981: Fixed 'Undefined class constant' error when interceptor is generated.

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7713](https://jira.corp.magento.com/browse/ENGCOM-7713) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked case from **[Manual testing scenario](https://github.com/magento/magento2/pull/28797#issue-436391008)**
**Before:**
:x: Error "Undefined class constant 'XML_PATH_HEADER_TRANSLATE_TITLE' " is shown
#28797Main


**After:**
:heavy_check_mark: No errors when plugin is loaded
#28797PR

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento create issue

**Comment by slavvka** [comment]
@magento run WebAPI tests

**Comment by slavvka** [comment]
@magento run WebAPI Tests

**Comment by slavvka** [comment]
@magento run Integration Tests

**Pull request merged**
