### PR TITLE
Issues 31197 - Loading wrong order tax info

### LINKED ISSUE #31197: Magento loading the wrong Tax info on admin Invoice and Creditmemo page
After upgrading from Magento 2.3.3 to 2.4.1, we are having random broken invoice pages. After further debugging, this seems to be core issue.

### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Install clear Magento!
2. Set-up tax rule for `CA` region.
3. Go to `Store`->`Configuration`->`Sales`->`Tax`->`Orders, Invoices, Credit Memos Display Settings` and set
     `Include Tax In Order Total` -> `Yes`;
     `Display Full Tax Summary` -> `Yes`;
4. Create a simple product.
5. Place order with this product chose `State/Province` -> `California`.
6. Place one more order and choose any `State/Province` except for `California` (to avoid taxes).
7. Open the second order on the admin panel and create an invoice for it.
8. Open the second order again, go to the `Invoices` tab, and open the invoice.

### Expected result (*)

1. Invoice page loaded successfully

### Actual result (*)

1. Invoice page broken
image

### Additional information

file

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/Block/Adminhtml/Order/Totals/Tax.php#L98

[app/code/Magento/Tax/Model/ResourceModel/Sales/Order/Tax/Collection.php](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Tax/Model/ResourceModel/Sales/Order/Tax/Collection.php#L36)

image

In the image above ``order->getId()`` is actually an instance of Magento\Sales\Model\Order\Creditmemo or Magento\Sales\Model\Order\Invoice therefore ``getId()`` will return the invoice or credit memo id instead of the order id which will send the wrong information to the SQL below.

```
SELECT 
  `main_table`.* 
FROM 
  `sales_order_tax` AS `main_table` 
WHERE 
  (main_table.order_id = 1) 
ORDER BY 
  `process` ASC
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by srenon**
### Description (*)
Magento references the wrong class object when loading tax info for the admin credit memo and invoice page.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31197

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by danielrussob** [comment]
@magento give me test instance

**Comment by danielrussob** [comment]
@magento give me 2.4-develop instance

**Comment by danielrussob** [comment]
@magento run all tests

**Review by sidolov — CHANGES_REQUESTED** [review]
@srenon could you please cover changes with some kind of automated tests? Thanks!

**Comment by engcom-Charlie** [comment]
@srenon I'll take care of test coverage.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8579](https://jira.corp.magento.com/browse/ENGCOM-8579) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Set-up tax rule for `CA` region.
2. Go to `Store`->`Configuration`->`Sales`->`Tax`->`Orders, Invoices, Credit Memos Display Settings` and set
     `Include Tax In Order Total` -> `Yes`;
     `Display Full Tax Summary` -> `Yes`;
3. Create a simple product.
4. Place order with this product chose `State/Province` -> `California`.
6. Place one more order and choose any `State/Province` except for `California` (to avoid taxes).
7. Open the second order on the admin panel and create an invoice for it.
8. Open the second order again, go to the `Invoices` tab, and open the invoice.

**Before:** :heavy_multiplication_x: Invoice page broken

Screenshot from 2020-12-24 11-30-52

**After:** :heavy_check_mark: Invoice page loaded successfully

Screenshot from 2020-12-24 11-54-55
Screenshot from 2020-12-24 11-55-07

**Pull request merged**
