### PR TITLE
Improvement PageLayout Config Builder. Added save in cache config files.

### LINKED ISSUE #29546: [Issue] Improvement PageLayout Config Builder. Added save in cache config files.
This issue is automatically created based on existing pull request: magento/magento2#28818: Improvement PageLayout Config Builder. Added save in cache config files.

---------

### Preconditions (*)

Magento 2.4-develop

Magento often runs `getPageLayoutsConfig`. I added to save in cache config files. This optimization will be reduced load time.
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Steps to reproduce (*)

1. Go to Admin->Content->Pages;
2. Test load time protected function getConfigFiles().

**Expected Result:**

Load time should be faster 

**Actual Result:**

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by Knase**
### Description (*)

Magento often runs `getPageLayoutsConfig`. I added to save in cache config files. This optimization will be reduced load time.
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29546: Improvement PageLayout Config Builder. Added save in cache config files.

### CODE REVIEW

**Comment by Knase** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Knase. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Knase, here is your [Magento instance](https://i-28818-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28818-2-4-develop.instances.magento-community.engineering/admin_f300](https://i-28818-2-4-develop.instances.magento-community.engineering/admin_f300)
Login: `b7bd962e` Password: `8912a59ae74b`
Instance will be terminated in up to 3 hours.

**Comment by Knase** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento create issue

**Review by sidolov — CHANGES_REQUESTED** [review]
Hi @Knase! Nice finding, usually caching the repeatable operations can significantly improve performance but sometimes it looks almost the same time as without cache. Do you have any performance measurements for both cases: with and without the cache? Thank you!

**Comment by sidolov** [comment]
@Knase do you have any updates on the PR? Thanks!

**Comment by engcom-Echo** [comment]
Hi, @Knase. Please can you fix fail tests?

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8195](https://jira.corp.magento.com/browse/ENGCOM-8195) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Echo** [comment]
:heavy_check_mark: QA passed
**Result:**

:x: **Before:**
image

:heavy_check_mark: **After:**
image

Tested protected function getConfigFiles().
On test used delay  "usleep(100);", otherwise, the values time ​​is very meager.

**Pull request merged**
