### PR TITLE
Removed 'indexer:reindex', 'cache:flush' and AdminReindexAndFlushCache

### LINKED ISSUE #31031: [Issue] [WIP] Removed 'indexer:reindex', 'cache:flush' and AdminReindexAndFlushCache
This issue is automatically created based on existing pull request: magento/magento2#31025: [WIP] Removed 'indexer:reindex', 'cache:flush' and AdminReindexAndFlushCache

---------
### Description
Remove 'indexer:reindex', 'cache:flush' commands and usage of AdminReindexAndFlushCache action group from tests to improve execution for the following modules:
- Bundle
- Catalog
- CatalogRule
- CatalogRuleConfigurable
- CatalogUrlRewrite
- Downloadable
- Indexer
- Paypal
- Sales

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Remove 'indexer:reindex', 'cache:flush' commands and usage of AdminReindexAndFlushCache action group from tests to improve execution for the following modules:
- Bundle
- Catalog
- CatalogRule
- CatalogRuleConfigurable
- CatalogUrlRewrite
- Downloadable
- Indexer
- Paypal
- Sales

### Resolved issues:
1. [x] resolves magento/magento2#31031: [WIP] Removed 'indexer:reindex', 'cache:flush' and AdminReindexAndFlushCache

### CODE REVIEW

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by rogyar** [comment]
Hi @sergiy-v, great job. Looks good to me. As for the failing tests, we have the same set of failing tests for almost every PR until they are stabilized. So they are not related to your changes.

**Comment by rogyar** [comment]
This one is marked as WIP. Are you going to add/change something or just wanted to check the tests?

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by sergiy-v** [comment]
> Hi @sergiy-v, great job. Looks good to me. As for the failing tests, we have the same set of failing tests for almost every PR until they are stabilized. So they are not related to your changes.

Hello @rogyar, thank you for clarification.

> This one is marked as WIP. Are you going to add/change something or just wanted to check the tests?

I removed [WIP], just waiting for green tests.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8496](https://jira.corp.magento.com/browse/ENGCOM-8496) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** Functional Tests B2B  and Functional Tests EE are failed, some tests are waiting for status

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by sergiy-v** [comment]
@magento run Unit Tests,Functional Tests B2B

**Pull request merged**
