### PR TITLE
Prevent adding form keys to forms with external action URLs

### PR DESCRIPTION
**Pull request by krzksz**
### Description (*)

This issue fixes the case where `form_key` field was being added to POST forms that had external (not belonging to shop's base URL) action URL.

### Fixed Issues (if relevant)

1. magento/magento2#23382: form_key parameter gets added to all forms

### Manual testing scenarios (*)

1. Prepare a static block with following text content (with editor disabled):
```html
<form action="https://google.com" method="POST"><input type="submit" value="Submit test form"></form>
```
2. Add above static block to any CMS page.
3. Go to the CMS page, open developer tools under `Network` tab with `Preserve log` checkbox checked.
4. Click `Submit test form` button and verify that no `form_key` field was added to request parameters.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by krzksz** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @krzksz. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @krzksz, here is your [new Magento instance](https://pr-25336.instances.magento-community.engineering).
Admin access: [https://pr-25336.instances.magento-community.engineering/admin](https://pr-25336.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6199](https://jira.corp.magento.com/browse/ENGCOM-6199) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Golf** [comment]
@magento run all tests

**Pull request merged**
