### PR TITLE
[32013][PR to 2.4-develop] Marked AdvancedSearch, Analytics, Backend, Bundle, CardinalCommerce as API 

### LINKED ISSUE #32013: Mark AdvancedSearch, Analytics, Backend, Bundle, CardinalCommerce as API
The following interfaces should be marked as API in 2.4-develop branch
1. app/code/Magento/AdvancedSearch/Block/SearchDataInterface.php
1. app/code/Magento/Analytics/Api/Data/LinkInterface.php
1. app/code/Magento/Analytics/Api/LinkProviderInterface.php
1. app/code/Magento/Analytics/Model/Connector/CommandInterface.php
1. app/code/Magento/Analytics/Model/ExportDataHandlerInterface.php
1. app/code/Magento/Analytics/Model/ReportWriterInterface.php
1. app/code/Magento/Analytics/ReportXml/DB/Assembler/AssemblerInterface.php
1. app/code/Magento/Backend/Model/Image/UploadResizeConfigInterface.php
1. app/code/Magento/Backend/Model/Search/Config/Structure/ElementBuilderInterface.php
1. app/code/Magento/Bundle/Pricing/Adjustment/BundleCalculatorInterface.php
1. app/code/Magento/CardinalCommerce/Model/Response/JwtParserInterface.php
1. app/code/Magento/CardinalCommerce/Model/Response/JwtPayloadValidatorInterface.php

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixes https://github.com/magento/magento2/issues/32013

### Related Pull Requests

https://github.com/magento/magento2/pull/32167

### Fixed Issues (if relevant)

1. Fixes magento/magento2 #32013>

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by danielrussob** [comment]
@magento run Integration Tests

**Comment by danielrussob** [comment]
I confirm that this PR is just a code cleanup / marked as API some class. We are waiting for tests.

**Comment by danielrussob** [comment]
I confirm that all files mentioned in issue (https://github.com/magento/magento2/issues/32013) are covered

**Comment by danielrussob** [comment]
Hi @Usik2203 , thank you for your contribution

Can you tell me why you have marked: app/code/Magento/Analytics/ReportXml/DB/SelectBuilder.php as API?

It's not linked in: https://github.com/magento/magento2/issues/32013

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
> Hi @Usik2203 , thank you for your contribution
> 
> Can you tell me why you have marked: app/code/Magento/Analytics/ReportXml/DB/SelectBuilder.php as API?
> 
> It's not linked in: #32013

This file was marked as API for fixing static issue when PR was target to 2.5-develop branch . Removed this file from this PR now.

**Comment by Usik2203** [comment]
@magento run Functional Tests EE , WebAPI Tests

**Comment by danielrussob** [comment]
@magento run Static Tests

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run  WebAPI Tests , Unit Tests , Static Tests , Sample Data Tests EE , Sample Data Tests B2B ,  Functional Tests EE , Functional Tests B2B

**Comment by danielrussob** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by danielrussob** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-9069](https://jira.corp.magento.com/browse/ENGCOM-9069) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama the branch with code successfully imported into`magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-32723`.

**Comment by gabrieldagama** [comment]
This PR has been merged to `api-changes-develop`.

**Pull request closed without merging**
