### PR TITLE
Upgrade to Promise-based requirejs

### PR DESCRIPTION
**Pull request by kirmorozov**
### Description (*)
Changes introduce major performance upgrade for Front-end, removes extra computation and timeouts overhead.
These changes are upgrading requirejs internals with requirejs/alameda - Promise-based implementation.
*mostly compatible with original RequireJS.
In this PR incompatible changes are resolved.

### Fixed Issues (if relevant)

1. magento/magento2#19470: Debugging of JS issues is painful, upgrade to Promise-based requirejs
2. ...

### Manual testing scenarios (*)
Changes must be at low level and compatible with most modules.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @kirmorozov. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
Hi @kirmorozov , thanks for your contribution! For such fundamental changes an architectural approval is required. Can please create a pull request to https://github.com/magento/architecture describing your proposition.

**Comment by kirmorozov** [comment]
Hi, fellow, 
Nothing major. 
This is simple replacement, same require(), define() API and polyfill for Promise.
Browser support stays the same, for most APIs.
Plus it is easier to expose dependency tree between modules.

It does not change architecture outside requirejs, and requirejs-related internals. 
only 's' property require is going away, 
and adding special exposure of queue so mixin.js can mess with it.
Change is so deep, very few engineers will ever get there.

I'll handle issues with tests as soon as reproduce them locally.

**Comment by sivaschenko** [comment]
Hi @kirmorozov , I mean you are actually updating the library we are relying on `lib/web/requirejs/require.js`. Such changes should get common attention and approval. That's why I had to ask you to communicate that to https://github.com/magento/architecture

**Comment by kirmorozov** [comment]
jsbuild is doomed.
Please lets move on with removal of jsbuild-based magento bundles as they are inefficient.
Gulp or Grunt bundling provide uglyfied bundles along with source maps.

**Comment by DrewML** [comment]
We'll discuss more in the meeting (https://github.com/magento/architecture/issues/47), but regarding the perf comment:

> Changes introduce major performance upgrade for Front-end, removes extra computation and timeouts overhead.

Do you have before/after traces you can share? Would be nice to see where the time was being spent.

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [new Magento instance](https://pr-19517.instances.magento-community.engineering).
Admin access: [https://pr-19517.instances.magento-community.engineering/admin](https://pr-19517.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by kirmorozov** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @kirmorozov. Thank you for your request. I'm working on Magento instance for you

**Comment by sivaschenko** [comment]
Hi @kirmorozov can you please provide benchmark for this pull request as was requested on the architecture discussion meeting

**Comment by sidolov** [comment]
Hi @kirmorozov , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
