### PR TITLE
Add Event Prefix And Object To The Catalog Product Option Value Collection

### LINKED ISSUE #29621: [Issue] Add Event Prefix And Object To The Catalog Product Option Value Collection
This issue is automatically created based on existing pull request: magento/magento2#26401: Add Event Prefix And Object To The Catalog Product Option Value Collection

---------
### Preconditions (*)

Magento 2.4-develop

### Fixed Issues (if relevant)
n/a

### Steps to reproduce: (*)
1. Try to customize the collection loading of \Magento\Catalog\Model\ResourceModel\Product\Option\Value\Collection.
2. Currently, one can only use the generic events like `core_collection_abstract_load_before`.
3. With this pull request, one can also use specific events like `catalog_product_option_value_collection_load_before`.

**Actual Result:** 
:heavy_multiplication_x: here is no dispatch specially event for loading Magento\Catalog\Model\ResourceModel\Product\Option\Value\Collection.
Only general `core_collection_abstract_load_before` was dispatched.

**Expected Result:** 
:heavy_check_mark: here is dispatch general `core_collection_abstract_load_before` and `catalog_product_option_value_collection` event for load before(+ `_load_before`) and after (+ `_load_after`) for Magento\Catalog\Model\ResourceModel\Product\Option\Value\Collection.

### Questions or comments
Would it make sense to check more relevant Magento core models / collections and add event prefixes / objects there as well?

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by sprankhub**
### Description (*)
This pull request adds an event prefix and event object to the catalog product option value collection, so that it can be customized in a better way.

### Fixed Issues (if relevant)
n/a

### Manual testing scenarios (*)
1. Try to customize the collection loading of \Magento\Catalog\Model\ResourceModel\Product\Option\Value\Collection.
2. Currently, one can only use the generic events like `core_collection_abstract_load_before`.
3. With this pull request, one can also use specific events like `catalog_product_option_value_collection_load_before`.

### Questions or comments
Would it make sense to check more relevant Magento core models / collections and add event prefixes / objects there as well?

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29621: Add Event Prefix And Object To The Catalog Product Option Value Collection

### CODE REVIEW

**Comment by sprankhub** [comment]
@akaplya could you have a look here? Thanks :-)

**Comment by sidolov** [comment]
@magento create issue

**Comment by sidolov** [comment]
`Risk: high` since someone can observe `core_collection_abstract_load_before ` event and expect `app/code/Magento/Catalog/Model/ResourceModel/Product/Option/Value/Collection` but after the fix the event mmname will be changed.

**Comment by sprankhub** [comment]
I do not see high risk here, @sidolov. After the change, **two** events will be dispatched: `core_collection_abstract_load_before` (same as currently!) plus the new `catalog_product_option_value_collection_load_before`. So we solely add a new event here.

**Comment by sidolov** [comment]
@sprankhub thank you for the clarification! I have changed the risk label!

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8295](https://jira.corp.magento.com/browse/ENGCOM-8295) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Bravo** [comment]
Dev experience is required for testing this PR. Please note that Manual testing has not been performed.

**Comment by engcom-Charlie** [comment]
:heavy_check_mark: QA Passed
**Before**: 
here is no dispatch specially event for loading Magento\Catalog\Model\ResourceModel\Product\Option\Value\Collection.
Only general `core_collection_abstract_load_before` was dispatched.

**After**
here is dispatch general `core_collection_abstract_load_before` and `catalog_product_option_value_collection` event for load before(+ `_load_before`) and after (+ `_load_after`) for Magento\Catalog\Model\ResourceModel\Product\Option\Value\Collection.

**Comment by engcom-Alfa** [comment]
Hi @sidolov .

Could you put an appropriate label for test coverage?
Thanks!

**Comment by gabrieldagama** [comment]
@magento run Semantic Version Checker

**Comment by gabrieldagama** [comment]
Approval internal ticket: https://jira.corp.magento.com/browse/MC-38732

**Pull request merged**
