### PR TITLE
Fix issue where <depends> node does not work for "label" fields in system.xml

### PR DESCRIPTION
**Pull request by erikhansen**
This pull request fixes Github issue #2340 

The code is using Prototype, which required adding all of the `if` conditionals around any usage of the `target` variable, as Prototype returns "null" if an element isn't found. I would recommend all of this code being refactored to jQuery in the future, as it will simplify things.

### CODE REVIEW

**Comment by Vinai** [comment]
Thank you for your contribution!  
All tests pass, license agreement is signed, code looks okay. Ready for review by core team.

**Comment by erikhansen** [comment]
@Vinai Thanks! Any idea when this might get merged? I'm working on an extension and it would be great if this PR could get merged within the next week or two.

**Comment by Vinai** [comment]
No, sorry - I can't say, don't know.

**Comment by alankent** [comment]
Hi @erikhansen, its probably obvious but we have not done many releases with M2 yet (!). Did you need/want this in a patch, or is the next release okay? We are planning on roughly quarterly releases.

Currently we are not planning frequent patches in the short term, but there has been some interesting internal discussions about the pros and cons of different approaches. However, it is very unlikely in the next two weeks to be released if that helps with your planning.

Feel free to share an opinion with justification of how to release and when. Until we get more practiced, frequent releases are unlikely. But understanding the benefits (and negatives) from the external perspective would be interesting.

**Comment by erikhansen** [comment]
@alankent Thanks for weighing in on this. With an application as massive as Magento, I think a quarterly release cycle makes sense. Even though efforts have been made to have code coverage with automated tests, I expect that you're still doing significant manual functional review before each release, making it a big effort to push out a new release.

That being said, based on the past 7 years of working with Magento, one of the most frustrating things was spending time patching core issues, only to find that Magento knew about the issue and had an internal patch for it, but didn't properly publicize that information. Emailing Enterprise support was often the only way to know whether a patch existed.

It would be great if a mechanism could be implemented to allow developers and merchants visibility into issues that have been logged and/or fixed, in between releases. I'm actively developing on M2 and one of the first things I do when it seems that I've encountered a core bug is to search the issues on this repo to see if anyone else has encountered the issue. However I expect that Magento's internal Jira ticketing system has significantly more information about known issues. Whether that system is opened to the public or whether a Magento employee manually curates a list of internally known issues, I'd love to have more visibility into known issues (and associated commits/patches).

**Comment by alankent** [comment]
Hi @erikhansen, with M2 the patching process is changing. We are moving to making _all_ patches available via Composer (no more hot fixes). So there won't be any patches available to some and not all in the future. But we are definitely interested to get feedback on the approach to make sure we have not missed something.

Also, all patches will be cumulative, to avoid the merge conflict problem of different overlapping patches. (That was another problem with multiple independent patches floating around.)

Being open, we are going to have to build up those new muscle skills and processes. We have the internal "head knowledge", but have not released an official M2 patch yet. E.g. There are "maintenance patches" (cumulative bits that are not urgent, but we think are worth patching), urgent customer fixes covered by Support (what hot fixes used to be for), and security fixes. They have different release timing needs. But for all three we plan to do via Composer available to everyone at the same time.

Regarding internal versus external tracking systems, we talk about this every so often. Frankly right now we are undergoing a lot still as part of the ongoing spin-out from the parent company (we are a separate company, with support from eBay still). Such process changes are probably going to have to wait until those activities are out of the way. We are trying hard to keep the development team as isolated from those activities as possible, so major process changes are less likely for a little while. Feel free to remind us in a few months time! ;-)

**Comment by erikhansen** [comment]
@alankent Cumulative patches distributed via Composer makes sense. Hopefully those patches will include detailed change logs covering exactly what is covered in that patch.

I'll touch base in a few months to see how the process of opening up the internal issues log is going.

**Comment by dsikkema-magento** [comment]
Internal ticket: MAGETWO-49874

**Pull request merged**
