### PR TITLE
Allow for EAV varchar attributes to have leading zeros added/removed

### PR DESCRIPTION
**Pull request by JeremyPlease**
### Description (*)

The previous Magento behavior was to not update EAV attributes that were numeric strings with leading zeros added or removed (ie. changing from `09` to `9`). This PR fixes this behaviour by removing the `is_numeric` check and only using strict comparison (`!==`) to determine if a value has changed.

### Fixed Issues (if relevant)

1. magento/magento2#7170: "Numeric-ish values not properly evaluated on varchar attributes"

### Manual testing scenarios (*)

1. Add a custom attribute named "num_string" with type of `varchar` to customers
2. Create a new customer and set "num_string" to "09"
3. Edit the newly created custer and set "num_string" to "9" and save

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

-----

Thanks to @serhiirepin for pointing out the solution in https://github.com/magento/magento2/issues/7170#issuecomment-404169043.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @JeremyPlease. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
You don't need to test an abstract class in integration test.

Just save some EAV attribute, for instance, product one with values as described in issue (I would recommend both `09` -> `9` and `9` -> `09` cases).

**Comment by orlangur** [comment]
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

**Comment by JeremyPlease** [comment]
No problem. When I have time to add the appropriate tests I'll reach out to reopen this.

**Pull request closed without merging**
