### PR TITLE
[2.3] Add support for validation message callback

### PR DESCRIPTION
**Pull request by floorz**
### Description (*)

- Adds a type check for message just before attempting to process validation params on it
- Resolves the callback if it was one using the validation rule for the 'this' context

### Fixed Issues (if relevant)

1. magento/magento2#20078: Magento Ui form validator message callback not supported

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20079) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @floorz. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3803](https://jira.corp.magento.com/browse/ENGCOM-3803) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@floorz thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by floorz** [comment]
@VladimirZaets should I make a branch and pull request similar to this but for the 2.2-develop branch?

**Comment by VladimirZaets** [comment]
Hi @floorz, thank for collaboration. Yes, you are right, but PR to 2.2 branch will be processed after PR for 2.3 will be merged.

**Pull request merged**
