### PR TITLE
Add preload support for images/fetch via XML/Priority Hints Support

### LINKED ISSUE #34564: [Issue] Add preload support for images/fetch via XML/Priority Hints Support
This issue is automatically created based on existing pull request: magento/magento2#34560: Add preload support for images/fetch via XML/Priority Hints Support

---------
fetch: Resource to be accessed by a fetch or XHR request, such as an ArrayBuffer or JSON file. If a critical area is made via Ajax call, it can also be triggered earlier via perload. This can affect different pages, so this should be controllable via XMl.

Referencing:
https://web.dev/preload-responsive-images/#preload-overview
https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload#including_media

### PR DESCRIPTION
**Pull request by in-session**
fetch: Resource to be accessed by a fetch or XHR request, such as an ArrayBuffer or JSON file. If a critical area is made via Ajax call, it can also be triggered earlier via perload. This can affect different pages, so this should be controllable via XMl.

Referencing:
https://web.dev/preload-responsive-images/#preload-overview
https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload#including_media

### Resolved issues:
1. [x] resolves magento/magento2#34564: Add preload support for images/fetch via XML/Priority Hints Support

### CODE REVIEW

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento run Semantic Version Checker, Functional Tests EE, Functional Tests CE, Unit Tests

**Comment by ihor-sviziev** [comment]
@sidolov, I set priority to P2 as this allows to use preload for more assets and define the priority of loading scripts and images that should be used for improving frontend performance.

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests look not related to changes from this PR.

PS: I don't think that in such case SVC should fail

**Comment by ihor-sviziev** [comment]
@magento create issue

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9334](https://jira.corp.magento.com/browse/ENGCOM-9334) has been created to process this Pull Request

**Comment by Den4ik** [comment]
How changes will affect to styles/scripts merging?

**Comment by ihor-sviziev** [comment]
@Den4ik, it won't affect the styles/script merging

**Comment by in-session** [comment]
With the relavance, you can only control how the browser should classify manually inserted scripts. As a rule, these are scripts that are loaded outside the requirejs. preload for images are critical images such as the Luma logo that are needed in a timely manner.

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE, Functional Tests CE, Unit Tests

**Comment by Den4ik** [comment]
@kandy Could we merge this PR into 2.4 release line with changes in xsd?

**Comment by in-session** [comment]
@magento run Functional Tests EE, Functional Tests CE, Unit Tests

**Comment by kandy** [comment]
@Den4ik if it back

> @kandy Could we merge this PR into 2.4 release line with changes in xsd?

Unless it is backward-incompatible, there should not be any problem to merge

**Comment by ihor-sviziev** [comment]
@kandy, it looks like a false positive on SVC build that should be approved. Unfortunately, such approvals take from months to... Ages:(

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9334](https://jira.corp.magento.com/browse/ENGCOM-9334) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests CE, Functional Tests EE, Semantic Version Checker

**Comment by engcom-Alfa** [comment]
Hi @in-session , @ihor-sviziev , @Den4ik 
Thanks for your contribution and collaboration!

By looking into the code changes, we understood that, the fix helps to load the images the are required to be loaded first in the UI page.
Can you please let us know in which UI page, we can expect this improvement after PR changes? Please mention a few pages that are going to preload the images after these changes
If our understanding is wrong, kindly guide us to reproduce the issue step by step.
Thanks in advance!

**Comment by in-session** [comment]
@engcom-Alfa 
The changes within the PR are not only for images, this gives the possibility to give the images or other resources a higher priority via XML preload. The PR is for frontend optimisation for all stores. 

Referencing Preload Image:
https://web.dev/preload-responsive-images/#preload-overview
https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload#including_media

Referencing Preload Fetch:
_fetch: Resource to be accessed by a fetch or XHR request, such as an ArrayBuffer or JSON file._
https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload#what_types_of_content_can_be_preloaded

And Add also Priority Hints:
Priority Hints can be set for resources in HTML by specifying an importance attribute on a <script>, , or <link> element (though other elements such as <iframe> may see support later). An example can be something like this:
https://developers.google.com/web/updates/2019/02/priority-hints#using_priority_hints

**Comment by in-session** [comment]
But i found out an other core problem, so we need to fix this also:
Ashampoo_Snap_Dienstag, 28  Dezember 2021_12h10m26s_003_

If a preload for a script is inserted, it is converted to a script.:
Ashampoo_Snap_Dienstag, 28  Dezember 2021_12h11m34s_004_

**Comment by in-session** [comment]
@magento give me test instance

**Comment by in-session** [comment]
When the following point is active you can preload script now: Move JS code to the bottom of the page
Ashampoo_Snap_Dienstag, 28  Dezember 2021_13h45m12s_007_
Ashampoo_Snap_Dienstag, 28  Dezember 2021_13h43m54s_006_

**Comment by in-session** [comment]
@magento give me test instance

**Comment by in-session** [comment]
@magento give me test instance

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
It seems that the head data should be completely revised, controlling the order only by asset type will cause problems.

1.

> `<link rel="preload"`
>  - CSS
>  - FONT
>  - IMG
>  - JS
>  - FETCH

2.

> `<link rel="stylesheet"`
> `<script`

 
3.

> `<link rel="icon"`
> `<link rel="shortcut icon"`
> `<link rel="apple-touch-icon"`
> `<link rel="mask-icon"`

**Review by Den4ik — APPROVED** [review]

**Comment by Den4ik** [comment]
Why it was marked as `[TEST]` at title?

**Comment by Den4ik** [comment]
@in-session could you explain please?

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9334](https://jira.corp.magento.com/browse/ENGCOM-9334) has been created to process this Pull Request

**Comment by in-session** [comment]
@Den4ik 
After a few more tests, some areas were reprogrammed. There was still the problem that scripts were not displayed correctly via preload, which has been fixed:
Ashampoo_Snap_Dienstag, 28  Dezember 2021_12h11m34s_004_

Furthermore, preload as image was output as font if it was an svg image, this is also fixed.

There is only one area missing now, the sorting of the output:
Ashampoo_Snap_Dienstag, 28  Dezember 2021_13h30m18s_005_

**Comment by in-session** [comment]
@magento give me test instance

**Comment by in-session** [comment]
@magento give me test instance

**Comment by in-session** [comment]
@magento give me test instance

**Comment by engcom-Alfa** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento give me test instance

**Comment by in-session** [comment]
@magento give me test instance

**Comment by in-session** [comment]
@engcom-Alfa 
I still have to remove the unnecessary files

There is only one area missing now, the sorting of the output:

Ashampoo_Snap_Mittwoch, 5  Januar 2022_13h46m23s_028_

> 
> First
> 
> > `<meta`
> 
> 1
> 
> > `<link rel="preconnect"`
> > `<link rel="dns-prefetch"`
> 
> 2
> 
> > `<link rel="preload"`
> > 
> > * CSS
> > * FONT
> > * IMG
> > * JS
> > * FETCH
> 
> 3
> 
> > `<link rel="stylesheet"`
> > `<script`
> 
> 4 all other link with rel
> 
> > `<link rel="icon"`
> > `<link rel="shortcut icon"`
> > `<link rel="apple-touch-icon"`
> > `<link rel="mask-icon"`
> > `<link rel="manifest"`

**Comment by in-session** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
❌ QA not Passed

**Manual Scenario Steps**

1. Merge the branch with magento 2.4-develop
2. Run the code on the magento server 
 
**:heavy_check_mark: Expected result After Fix** 
-  Stylesheet and logo.svg will upload with preload xml with priorities

**:x: Actual result After Fix** 
-  Css is breaking after using preload with style sheet
- 
Screenshot 2022-01-13 at 4 33 43 PM

**Comment by in-session** [comment]
@magento give me test instance

**Comment by in-session** [comment]
@magento give me test instance

**Comment by in-session** [comment]
@magento give me test instance

**Comment by in-session** [comment]
@magento give me test instance

**Comment by engcom-Alfa** [comment]
@magento run all test

**Comment by engcom-Alfa** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
@magento Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE, Semantic Version Checker, Unit Tests

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE, Semantic Version Checker, Unit Tests

**Comment by engcom-Delta** [comment]
@magento run Functional Tests CE

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. We should have fresh installation of Magento 2.4 Develop. 

**Manual testing scenario:**

1. Open the frontend
2. Inspect Luma Logo
3. Search the with xpath //link[@rel='preload']
4. Validate the results whether you find a element with log.svg

**Before:** :heavy_multiplication_x: We can not find out link tag with logo.svg 
Screenshot 2022-02-02 at 5 00 19 PM

**After:** :heavy_check_mark:  We can find out link tag  with logo.svg

Screenshot 2022-02-02 at 4 48 08 PM


We do not need regression test scenarios for this case since code impact is not there.

**Comment by engcom-Delta** [comment]
@magento run Functional Tests CE

**Comment by engcom-Delta** [comment]
@magento run Functional Tests B2B, Functional, Functional Tests EE, Integration Tests, Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE, Semantic Version Checker, Unit Tests

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE, Semantic Version Checker, Unit Tests

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE, Semantic Version Checker, Unit Tests

**Review by engcom-Delta — CHANGES_REQUESTED** [review]
Auto test cases are failing inspite of running several times. Hence moving the ticket to 'Request Changes' state

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE, Unit Tests, Semantic Version Checker , Sample Data Tests EE, Sample Data Tests CE, Integration Tests

**Comment by engcom-Charlie** [comment]
https://github.com/magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Charlie** [comment]
@magento give me test instance

**Comment by engcom-Charlie** [comment]
@magento give me test instance

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run 
Functional Tests B2B, Functional Tests CE, Functional Tests EE,  Integration Tests, Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE, Semantic Version Checker, Unit Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run
Functional Tests B2B, Functional Tests CE, Functional Tests EE, Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE, Semantic Version Checker, Unit Tests, Static Tests

**Comment by in-session** [comment]
@engcom-Charlie 
Thanks for the edit on the pull, could you maybe look at pull #35580 in the context, it is in relation to this one.

**Comment by engcom-Charlie** [comment]
Hi @in-session,

In order to move this PR further, we need successful build.  I have fixed few unit as well as integration tests. 

Can you please have a look into the remaining failed tests. There are more than 500 functional tests are failing along with the others. It seems that PR is creating this failures.

Can you please check them so that we can move further. Also please add all the required changes in single PR so that we can run the build against all the changes together, get less failures and all the changes will go further together.

Thank you in advance!

**Comment by engcom-Charlie** [comment]
On the basis of above comment and since we didn't got any reply on above [comment](https://github.com/magento/magento2/pull/34560#issuecomment-1203751450) closing this PR.

Please reopen and update if you wish to continue.

Thank you for your contribution!

**Comment by Den4ik** [comment]
I believe that core team could help with tests fixes instead of closing improvement PRs

**Pull request closed without merging**
