### PR TITLE
Fix potentially corrupt merged CSS files.

### LINKED ISSUE #29172: Corrupt Merged CSS Files
Note that due to the nature of this issue, there's little chance that this can be replicated by somebody attempting to triage this ticket, I'm raising purely so I have something to reference with a pull request, so an engineer can review. 

### Preconditions (*)

1. CSS Merging Enabled (Store > Configuration > Advanced > Developer > CSS Settings > Merge CSS Files).
2. `var/tmp` and `pub/static` being on different filesystems

### Steps to reproduce (*)

1. Delete the merged files from `pub/static/_cache/merged/`.
2. Hammer the website with concurrent traffic.

### Expected result (*)

1. Website loads, looking as it should.

### Actual result (*)

1. It's possible that the merged file is incomplete, entirely breaking the design of the site until such time as the merged file is removed or a change results in a different filename. The effected pages are at best, very ugly and at worse, entirely non-usable, as elements you need to interact with may overlap, etc.

Work was previously done to improve this issue in commit 1b46c966d416ec27ca0891be654b69d7345da2d6, there is however an edge case. The previous commit generates randomly named files, so that two concurrent generation requests don't start writing to the same file, causing one request to copy the partly generated file from the other request. This is a good idea, as each concurrent generation of the file creates its own file. Once generated, the file is moved from the temporary location to the target location using a rename command. 

The rename command is *normally* atomic, meaning the target file is never a partially complete file. The edge case is that if the temp directory and the static directory are not on the same filesystem, the rename command is no longer atomic. This means that during the rename from the temporary path to the static directory, the file can be served partially complete and cached in the CDN / browser cache.

The only solution I'm aware of is to have the temporary file created in the same directory as the target path. Pull request to follow.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by pocallaghan**
### Description (*)
Create temporary files in the same static directory as the target file
to ensure that both files are on the same filesystem and thus the call
to rename will be atomic.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29172

### Manual testing scenarios (*)

1. Delete the merged files from pub/static/_cache/merged/
2. Hammer the website with concurrent traffic.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@pocallaghan 
Your solution looks good to me.
Now unit tests are failing. Could you fix them? I believe just fixing them will add test coverage to this change

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7970](https://jira.corp.magento.com/browse/ENGCOM-7970) has been created to process this Pull Request

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by onlinebizsoft** [comment]
Any news?

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by sidolov — CHANGES_REQUESTED** [review]
@pocallaghan please, take a look at failed static tests, there are a couple of items that should be addressed. Thanks!

**Comment by engcom-Hotel** [comment]
Hello,

As discussed internally, reproduction of this issue is not possible locally, as we need multiple resources/systems and create heavy traffic on the instance.

The code changes look good, hence after working on the build failures, we will move this PR to merge in progress.

Thanks

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Unit Tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by engcom-Charlie** [comment]
It seems that bot moved this PR from Merge in Progress to Changes Requested on assignment, hence moving it back.

Thank you!

**Pull request merged**
