### PR TITLE
Update README.md of Google_Analytics module

### LINKED ISSUE #32616: [Issue] Update README.md of Google_Analytics module
This issue is automatically created based on existing pull request: magento/magento2#32448: Update README.md of Google_Analytics module

---------
### Description (*)
Update Readme content for Google Analytics module, Google Analytics settings is not under General tab, it is located under Sales tab.

### Fixed Issues (if relevant)
1. magento/devdocs magento/devdocs#4451: README content for modules - work in M2 Code

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by charles-tychons**
### Description (*)
Update Readme content for Google Analytics module, Google Analytics settings is not under General tab, it is located under Sales tab.

### Fixed Issues (if relevant)
1. magento/devdocs magento/devdocs 4451: README content for modules - work in M2 Code

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32616: Update README.md of Google_Analytics module

### CODE REVIEW

**Comment by bgorski** [comment]
@magento run all tests

**Review by bgorski — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @bgorski, thank you for the review.
[ENGCOM-8973](https://jira.corp.magento.com/browse/ENGCOM-8973) has been created to process this Pull Request
:eight_spoked_asterisk: @bgorski, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Oscar** [comment]
@magento create issue

**Comment by charles-tychons** [comment]
@magento-engcom-team This PR was merged several years ago, Just noticed this is still showing the incorrect store configuration path in the documentation. https://developer.adobe.com/commerce/php/module-reference/module-google-optimizer

**Pull request merged**
