### PR TITLE
WYSIWYG Image-Popup is not working correctly with multipleEditors

### PR DESCRIPTION
**Pull request by Nazar65**
### Description (*)
Two or more wysiwyg-editors on the catalog product edit page, only the first one is in wysiwyg-mode - at least the last editor in the same "block" (eg. content) is hidden/in plain text-area-mode.

### Fixed Issues (if relevant)
1. magento/magento2#18548: Issue title

### Manual testing scenarios (*)

1. Open the catalog product edit page
2. Open the "content" area"
3. Enable the WYSIWYG-Mode for the Description
4. Hide the last editor in the same area (eg. Short Description or ItemDescV)
5. Click on Insert Image in the Description Editor
6. Click on the browse-icon for the Image URL
7. Select a image from the media browser
8. Click on insert file

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-22174.instances.magento-community.engineering).
Admin access: [https://pr-22174.instances.magento-community.engineering/admin](https://pr-22174.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4682](https://jira.corp.magento.com/browse/ENGCOM-4682) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Comment by sidolov** [comment]
Hi @Nazar65 , in order to keep consistency between release lines we should deliver fixes to 2.3-develop first. Does this described issue reproduce on the 2.3-develop?

**Comment by Nazar65** [comment]
Hi @sidolov no, in 2.3-dev we have new WYSIWYG editor, and this issue occurs only on 2.2-dev branch with older version of WYSIWYG editor,.

**Comment by sidolov** [comment]
@Nazar65 thank you for the clarification!

**Pull request merged**
