### PR TITLE
[module-security] Remove duplicate DI arguments

### PR DESCRIPTION
**Pull request by nickolasburr**
### Description (*)

Regarding `module-security`:

Duplicate DI arguments for `Magento\Security\Model\SecurityManager` are set via `etc/di.xml` and `etc/adminhtml/di.xml`. Since the arguments are already set globally and not modified or needed in an adminhtml-specific manner, this change removes the duplication from `etc/adminhtml/di.xml`.

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @nickolasburr. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sidolov** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sidolov. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sidolov, here is your [new Magento instance](https://pr-21341.instances.magento-community.engineering).
Admin access: [https://pr-21341.instances.magento-community.engineering/admin](https://pr-21341.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Pull request closed without merging**
