### PR TITLE
fix: simplify literal boolean checks

### PR DESCRIPTION
**Pull request by DanielRuf**
### Description (*)

We can typecast to boolean and check the result directly.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
Incorrect replacement, see https://github.com/magento/magento2/pull/19674/files#r240019815

Please combine with that PR.

**Comment by DanielRuf** [comment]
Afaik there is a combine command for PRs, right?

**Comment by orlangur** [comment]
@DanielRuf yep, just that it will produce two commits :)

@magento-engcom-team combine 19674

**Comment by magento-engcom-team** [comment]
Hi @orlangur. Thank you for your request. I'm working on combining the pull requests for you

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
@DanielRuf all pull requests have been successfully combined together: 
 - merged https://github.com/magento/magento2/pull/19674: fix: simplify literal boolean checks

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3658](https://jira.corp.magento.com/browse/ENGCOM-3658) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
