### PR TITLE
Update Readme file for magento2 repository

### PR DESCRIPTION
**Pull request by sidolov**
### Description
Updated readme.md
- Added Maintainers section 
- Added Contributors section 
- Changed links to documentation

### Fixed Issues (if relevant)
none

### Manual testing scenarios
none

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by okorshenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, thank you for the review.
[ENGCOM-1353](https://jira.corp.magento.com/browse/ENGCOM-1353) has been created to process this Pull Request

**Comment by okorshenko** [comment]
@magento-engcom-team give me 2.2.3 verification instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [Magento instance](http://i-14791.engcom.dev.magento.com).
Admin access: [http://i-14791.engcom.dev.magento.com/admin](http://i-14791.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @sidolov. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.1.15 release.

**Pull request merged**
