### PR TITLE
Solve fatal error on credit memo mail

### PR DESCRIPTION
**Pull request by arnoudhgz**
Also insert the correct item for invoice mail, to calculate the appropriate subtotal on row item.

This is an addition of PR https://github.com/magento/magento2/pull/22265 where the subtotal for creditmemo should be fixed. Now this same strategy is chosen for the invoice mail and the fatal error caused by this previous PR is solved.

By checking the type instance of `$item` I tried to keep it as strict as possible while keeping code the change as simple as possible.

### Fixed Issues (if relevant)
1. magento/magento2#25617: Fatal error on creditmemo mail grouped product

### Manual testing scenarios (*)
1. Add grouped product to cart, make sure to have for one item 3 products.
2. Place order. 
3. In the backend create invoice for this order, **nb** make sure to invoice only 2 of the 3 products (update qty)
4. Send invoice mail, see that the subtotal is correct
5. In the backend create credit memo for this same order, **nb** make sure to only credit 1 product (update qty)
6. Send credit memo mail, see that the subtotal is correct.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by arnoudhgz** [comment]
@joni-jones the CLA is in progress by someone from my company. Can you advice me on the `Semantic Version Checker` failure?

**Comment by arnoudhgz** [comment]
@sidolov / @joni-jones  can you advice me on the Semantic Version checker? All other checks are passed.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @arnoudhgz,
I just looked on your fix - for sure it should work, however it looks like  class `app/code/Magento/Sales/Block/Order/Email/Items/Order/DefaultOrder.php` is designed for rendering order items, so this issue is wider - looks like incorrect block is used for rendering invoice and credit memo items.

Could you investigate why it tries to use this block for rendering credit memo and invoice items and adjust your solution?

**Comment by ihor-sviziev** [comment]
Hi @arnoudhgz,
Will you be able to update your PR?

**Comment by arnoudhgz** [comment]
@ihor-sviziev at the moment I do not have the time to investigate the wider issue about the wrong class usage. I don't know if it is actually wrong since the items are rendered from the related order...

**Comment by ihor-sviziev** [comment]
Hi @arnoudhgz,
Yeah, I see that related issue was already closed.
So I'm closing this PR as issue isn't reproducing anymore.

Thank you for your contribution!

**Pull request closed without merging**
