### PR TITLE
Added Fix for - 26181

### PR DESCRIPTION
**Pull request by divyajyothi5321**
### Fixed Issues (if relevant)

1. magento/magento2#26181: Out of stock text is not aligned properly with add to cart button at list page in responsive

### Manual testing scenarios (*)

1. Go to Frond end and product listing page
2. With this fix in mobile view the out of stock text and add links are aligned compared with add to cart button as shown below

outofstok-expected

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-26183.instances.magento-community.engineering).
Admin access: [https://pr-26183.instances.magento-community.engineering/admin](https://pr-26183.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi, @divyajyothi5321. Thank you for your collaboration. 

At some resolutions, they are still not aligned (check the wishlist and compare icons). 
image

Also, I'm not sure that an additional color (orange) should be used in this particular case. The alignment fix is required, no doubts here. But bringing additional colors to the theme might be a topic for additional debates.

**Comment by divyajyothi5321** [comment]
@rogyar Can we add custom breakpoints in theme

**Comment by divyajyothi5321** [comment]
For integration test I'm getting "testTableSelection with data set #1" from the source "Magento\Reports\Model\ResourceModel\Report\Product\Viewed\CollectionTest.testTableSelection with data set #16", which is not related to any CSS changes made by me.

**Comment by rogyar** [comment]
Hi @divyajyothi5321. The tests are slightly broken. We are waiting for PR with the fixes for tests to be merged soon. 
As for the custom media queries, it depends. But I would say that we may not introduce custom media queries in most cases since such change might be considered as backward incompatible.

**Comment by divyajyothi5321** [comment]
@rogyar thank you for your suggestion, I didn't add any custom media queries adjusted with existing media queries  and now all checks are passed please review my latest changes and let me know for any modifications.

**Comment by rogyar** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-26183.instances.magento-community.engineering).
Admin access: [https://pr-26183.instances.magento-community.engineering/admin](https://pr-26183.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rogyar** [comment]
Hi @divyajyothi5321. Now it's much better. Thank you

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-6536](https://jira.corp.magento.com/browse/ENGCOM-6536) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
