### PR TITLE
magento/magento2#22814: Product stock alert - unsubscribe not working

### PR DESCRIPTION
**Pull request by yuriichayka**
Setting StoreId for Unsubscribe controller

### Description (*)

storeId wasn't set while loading the model hence failed to execute delete product alerts previously

### Fixed Issues (if relevant)

1. magento/magento2#22814: Product stock alert - unsubscribe not working

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by novikor — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @novikor, thank you for the review.
[ENGCOM-5371](https://jira.corp.magento.com/browse/ENGCOM-5371) has been created to process this Pull Request
:eight_spoked_asterisk: @novikor, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@yuriichayka thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Delta** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Delta. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Delta, here is your [new Magento instance](https://pr-23459.instances.magento-community.engineering).
Admin access: [https://pr-23459.instances.magento-community.engineering/admin](https://pr-23459.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by engcom-Delta** [comment]
Hi @yuriichayka I have tested PR changes and I got page with 404 status code when I used controller endpoint /productalert/unsubscribe/stock/product/1 .

**Manual testing scenario:**

- Create simple product (ID=1)
- Set Stores->Configuration->Catalog->Catalog->Product Alerts->Allow Alert When Product Comes Back in Stock=Yes
- Set t Stores->Configuration->Catalog->Catalog->Inventory->Display Out of Stock Products=Yes
- Create customer and log in
- Go to product page and click Notify me when this product is in stock
- Try unsubscribe using /productalert/unsubscribe/stock/product/1.

**Result:**
Page 404 Not Found is shown
image

**Comment by yuriichayka** [comment]
> Hi @yuriichayka I have tested PR changes and I got page with 404 status code when I used controller endpoint /productalert/unsubscribe/stock/product/1 .
> 
> **Manual testing scenario:**
> 
> * Create simple product (ID=1)
> * Set Stores->Configuration->Catalog->Catalog->Product Alerts->Allow Alert When Product Comes Back in Stock=Yes
> * Set t Stores->Configuration->Catalog->Catalog->Inventory->Display Out of Stock Products=Yes
> * Create customer and log in
> * Go to product page and click Notify me when this product is in stock
> * Try unsubscribe using /productalert/unsubscribe/stock/product/1.
> 
> **Result:**
> Page 404 Not Found is shown
> image

Hello @engcom-Delta . The reason is that the Stock class implements HttpPostActionInterface now, so it works only via POST methods.
 404 occurs because you are trying to access such endpoint via GET from browser. 
 Please test it via POST with appropriate authentication token in header. (Postman, for example)
I should have mentioned it in the description, sorry.

**Comment by engcom-Foxtrot** [comment]
QA passed.

**Pull request merged**
