### PR TITLE
fixed Product Advanced Pricing design issue #18775

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)
There was a small design issue die to app/code/Magento/Ui/view/base/web/templates/form/field.html file visible="$data.labelVisible" was on child element of the label, because of that parent was still visible even if the label visibility was false.

### Fixed Issues (if relevant)

1. magento/magento2#18775: Product Advanced Pricing design issue

### Manual testing scenarios (*)

1. login magento admin
2. goto catalog products
3: click on Add Product button
4: fill details then click on Advanced Pricing
5: in customer group price click Add

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18790) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @ashutoshwebkul. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3267](https://jira.corp.magento.com/browse/ENGCOM-3267) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@ashutoshwebkul thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by ghost** [comment]
#squashtoberfest

**Comment by magento-engcom-team** [comment]
Hi @ashutoshwebkul. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
