### PR TITLE
Convert long form tags with echo to use short-echo tags

### PR DESCRIPTION
**Pull request by davidalger**
There has long been a community request (see #107) to see Magento use short-echo tags across the board. Many prominent members of the community are in support of this change, particularly since system requirements were updated to demand PHP 5.4 or newer. Do note that this is **not** to be confused with short tags in general, and nobody is suggesting Magento use short tags, only short-echo tags. So the only thing being done here is replacing instances of `<?php echo $foo ?>` with the shorter `<?= $foo ?>` form which as of PHP 5.4 is fully supported.

The largest benefit of this is code readability. There is also a benefit of reduced line lengths. Templates are notorious for cumbersome line-lengths and this will help alleviate that to a degree.

The conversion seen here was done using the script found in this gist: [convert-tags.sh](https://gist.github.com/davidalger/fc88849cb1451589856a). Very simple to do actually.

Two things to note about this PR since it has a pretty wide scope:

a. Somebody would need to run the script agains the enterprise code to effect the change there as well.

b. Since it affects all templates, I am aware there is a risk of conflicts between this and other active branches internally. If conflicts arise, they are easily resolved (the history on the branch of this PR will show this as having been done once):

```
git checkout feature/short-echo-tags
git fetch --all
git merge upstream/develop -X theirs
bash -c "$(curl -sSf https://gist.githubusercontent.com/davidalger/fc88849cb1451589856a/raw/c848ee5922736c0f7dc4e930be4053572c913721/convert-tags.sh)"
git push
```

One question which I think this begs is this: Should I write a static test to enforce the use of short-echo tags in the core. Yes, PSR-1 allows them both. But it would be great to see Magento not only using them, but have something in place to enforce _consistent_ use of them throughout the core and across the board. If 3rd parties don't want to use them, fine…their choice…but at least core has one unified format. I'd be willing to add a static tests for this if desired.

Please consider accepting these changes. The community will thank you for it! ;)

### CODE REVIEW

**Comment by steverobbins** [comment]
Can we write a code sniff for this?  There is [already one](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Generic/Sniffs/PHP/DisallowShortOpenTagSniff.php#L72-L81) to disallow `<?=` but not enforce it.

**Comment by vancoz** [comment]
Hello @davidalger, according to latest @maksek response here #107 we are going to keep full tag as main one.

**Comment by Vinai** [comment]
:(

**Comment by erikhansen** [comment]
@maksek @vancoz If you look at the [PSR-1 section regarding tags](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md#21-php-tags), you will see that it says:

> PHP code MUST use the long `<?php ?>` tags or the short-echo `<?= ?>` tags; it MUST NOT use the other tag variations.

Since short echo tags are very clearly acceptable as a part of PSR-1, I would ask you to reconsider your stance on this PR, as I think the community (and programmer's fingers across the world) would thank you for it.

**Comment by vancoz** [comment]
@erikhansen, davidalger we are really appreciate contribution from our community so let us discuss this question again.

Regards

**Comment by orlangur** [comment]
@davidalger are you going to enforce it with sniff within this PR?

**Comment by davidalger** [comment]
@orlangur I've made one pass at adding a static test. I'm waiting on builds to complete, then going to push some code which should intentionally break the test to verify it fails a changed file. Once I do that, I plan on reverting the failed change and then hope to see this accepted!

**Comment by davidalger** [comment]
@vrann @okorshenko @orlangur 

I've completely rebuilt this branch from scratch based on latest develop using the process / script outlined in the task description. Also a handful of manual edits in a separate commit that were found in the sniff mentioned below. They are in a separate commit.

There has been a Sniff added to enforce the use of short-echo tags as well as a unit test for that Sniff in the static testing frameworks unit test suite. If the decision is made to not enforce this via a sniff, I can remove it, but the sniff was definitely helpful in finding the edge cases which I manually updated. Personally I think it makes sense to enforce it via a Sniff, even if it's considered a departure from strict PSR-1 standards (I would argue it's not, merely an additional coding guideline refusing the use of `<?php` tag in combination with `echo`).

In order to have the static tests report properly on Travis, I rebased on top of the branch for #9872 (resolves incorrect static test reporting on Travis). That branch is now underway being processed and will hopefully be merged soon.

Magento 2 has long dropped support for PHP versions where short-echo tags are not always available. They are _always_ available for use in any version of PHP newer than PHP 5.4 regardless of any ini settings.

There is a huge amount of community support shifting everything to use the short-echo tags as is partly demonstrated by #107 and this PR. The last word from @maksek was that we would "see how it evolves" — given the continued evolution of the Magento platform and the community engineering team, I would like this to be re-considered. Magento is already using short-echo tags in various places, and they make the code clearer and easier to read.

Ideally I would like to see this included in the M2.2 release, and will personally make the effort to apply the changes to the EE and B2B engcom repositories if that is what will make this happen. Open to feedback. Thanks for considering!

**Comment by davidalger** [comment]
Looks like #9872 just got merged into the mainline, so I just rebased on develop and pushed. Let's see if my tests still pass! :)

**Review by orlangur — APPROVED** [review]
Changes seem fine to me but why need them in scope of this PR?

**Comment by davidalger** [comment]
@orlangur When you ask "why need them in scope of this PR" — what changes are you referring to?

**Comment by orlangur** [comment]
@davidalger it was https://github.com/magento/magento2/pull/1563/commits/a626c364186c3a6f23ccd07c8277401839e44044, I expected to have this comment attached to particular changes..

**Comment by davidalger** [comment]
@orlangur Ah, ok. I think I understand now :) The changes to develop caused conflicts in a few files, resulting in GitHub showing the branch as not-mergeable. So I merged upstream/develop using `-X theirs` and ran the script from the original task description to update those templates which, as a result of the merge from develop, now had usages of `<?php echo` on the lines changed. These lines would have failed the static tests after I merged if I didn't update them. Does that make sense? Basically, I was updating the branch so it would be mergeable. Maybe there is a better way to handle that?

**Comment by orlangur** [comment]
@davidalger thanks, got it, so, basically those semantical changes came from mainline, not from your PR.

Sorry for confusion, I saw https://github.com/magento/magento2/pull/1563/commits/a3ee58a51f0836a96ec31aa905c3f940afd26765 + https://github.com/magento/magento2/pull/1563/commits/a626c364186c3a6f23ccd07c8277401839e44044 in one screen just because so GitHub notifications work. This mistake should not occur again)

**Comment by davidalger** [comment]
@orlangur No problem. Thanks for taking this!

**Comment by okorshenko** [comment]
Hi @davidalger we are working on stabilization of this PR.

**Pull request merged**
