### PR TITLE
#19921 : ACL incorrect for Advance in system configuration

### PR DESCRIPTION
**Pull request by konarshankar07**
### Fixed Issues (if relevant)

1. magento/magento2#19921: ACL incorrect for Advance in system configuration

### Manual testing scenarios (*)

1. Login into backend 
2. Go To System -> Permissions -> User Roles
3. 'Advanced Section' role has been disabled
4. ''Advanced Section'' has been deprecated

### Questions or comments

I think the best is to remove the code from the system.xml and acl.xml so we don't get ran into this issue again. Let me know your thoughts.
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the pull request @konarshankar07 , can you please correct the resource in https://github.com/magento/magento2/blob/2.3-develop/setup/src/Magento/Setup/Test/Unit/Module/Di/_files/app/code/Magento/SomeModule/etc/adminhtml/system.xml

**Comment by konarshankar07** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @konarshankar07. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @konarshankar07, here is your [Magento instance](https://i-23600-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23600-2-3-develop.instances.magento-community.engineering/admin](https://i-23600-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by sivaschenko — APPROVED** [review]

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-5750](https://jira.corp.magento.com/browse/ENGCOM-5750) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-5750](https://jira.corp.magento.com/browse/ENGCOM-5750) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
