### PR TITLE
Fixed store view label alignment issue over cart price rule page into admin

### PR DESCRIPTION
**Pull request by ktpl-prakash**
### Description (*)
Magento 2.3-Develop
Store View label alignment issue over cart price rules page into admin.

###  Preconditions (*)
1.Magento 2.3-Develop

### Fixed Issues (if relevant)

1. Store View label aligment issue over Cart Price Rule page

### Manual testing scenarios (*)

1. Login to Backend 
2. Create New or Edit Cart Price Rule 

### Expected result (*)

1 https://prnt.sc/m66l23

###  Actual result (*)

1 https://prnt.sc/m66khg

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @prakashpatel07. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [new Magento instance](https://pr-20244.instances.magento-community.engineering).
Admin access: [https://pr-20244.instances.magento-community.engineering/admin](https://pr-20244.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sivaschenko** [comment]
Hi @prakashpatel07 thanks for the pull request, however labels are still miss-aligned:

image

Also, can you please squash commits into a single one to remove unnecessary merge commits that are included in the pull request.

**Comment by rogyar** [comment]
@sivaschenko it's not about the input part but the left part that says "Main Website".
Take a look at the screenshot https://prnt.sc/m66khg On your screenshot it's fixed ;)

**Comment by sivaschenko** [comment]
@prakashpatel07 @rogyar Website/Store part is still detached from the field and far to the left.

I suggest fixing that by removing the `text-align: left` from `.tree-store-scope [class*='field-w'] .admin__field-label, .tree-store-scope [class*='field-sg'] .admin__field-label` rather than adding padding to a label.

Here is the result:
image

**Comment by sidolov** [comment]
Hi @prakashpatel07 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by ghost** [comment]
Hi @prakashpatel07, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+magento2+20244), it will take less than a minute. </br>Your feedback will help us to improve contribution process.

**Pull request closed without merging**
