### PR TITLE
Allow specify font type when declare custom font

### LINKED ISSUE #29719: Font format incorrect import in theme
### Preconditions:

Magento 2.4-develop

Default magento font import lib-font-face use type woff or woff2. In real case when user use another font type such as true type. Font import will work incorrect if add format truetype

Example in less define custom font

`.lib-font-face(
    @family-name: 'Inter-Light',
    @font-path: '@{baseDir}fonts/Inter-Light',
    @font-format: 'ttf',
    @font-weight: normal,
    @font-style: normal,
    @font-display: auto
);
`

will generate css font-face

`
@font-face {
    font-family: 'Inter-Light';
    src: url('../fonts/Inter-Light.ttf') format('ttf');
    font-weight: normal;
    font-style: normal;
    font-display: auto;
}
`
format font src seem incorrect in the case truetype. Reference in this doc

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face

src: url('../fonts/Inter-Light.ttf') format('ttf') should be 

src: url('../fonts/Inter-Light.ttf') format('truetype');

### Steps to Reproduce:

1. Tested with font added with /web/css/source/_typography.less inside luma/blank theme or custom theme
2. Use custom font non-default from magento (ttf, eot)
3. use format specific while import font
4. Also use type font specific too
5. Make sure output css render and page load without problem. Font render correctly

**Actual Result:** :heavy_multiplication_x: 

Font not render properly
font_before_change

styles-m.css render with font 
Screenshot from 2020-10-05 21-26-58

**Expected Result:** :heavy_check_mark: 

import
font_after_import
render styles-m.css
font_render_after
web font request
font_after_change
### Proposed solution

--- Update mixin font with new type font argument in order import correct type
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Previously custom font can added via theme by less file but some case font use other type (ttf,otf...) magento will not include correctly font. Font will not render properly. This patch allow frontend developers can specific font type when include font in theme.

Use case 1: no define font type -> use default font like before magento will gen font use woff/woff2
Use case 2: use font format -> Developers will need define both format and type for render font

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29719

### Manual testing scenarios (*)

1. Tested with font added with /web/css/source/_typography.less inside luma/blank theme or custom theme
2. Use custom font non-default from magento (ttf, eot)
3. use format specific while import font
4. Also use type font specific too
5. Make sure output css render and page load without problem. Font render correctly

### Questions or comments

Tested with import Roboto font used ttf format
Screenshot from 2020-10-05 21-33-35

**Before Result:** :heavy_multiplication_x: 

Font not found in network chrome devtools
font_before_change

styles-m.css render with font 
Screenshot from 2020-10-05 21-26-58

**After Result:** :heavy_check_mark: 

import
font_after_import
render styles-m.css
font_render_after
web font request
font_after_change

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
@magento run all tests

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-8068](https://jira.corp.magento.com/browse/ENGCOM-8068) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by mrtuvn** [comment]
@engcom-Alfa @engcom-Kilo can you check this

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE

**Comment by engcom-Alfa** [comment]
Dev experience is required for testing this PR. Please note that Manual testing has not been performed.

**Comment by mrtuvn** [comment]
@engcom-Alfa i have updated info manual tests ! Anything missing info here

**Comment by engcom-Foxtrot** [comment]
QA passed.

**Pull request merged**
