### PR TITLE
Convert ShareWishlistEntityTest to MFTF

### PR DESCRIPTION
**Pull request by MilaLesechko**
### Description (*)
This is convertation ShareWishlistEntityTest from MTF to MFTF 
testCaseId = MAGETWO-23394

TestCase
[Magento/Wishlist/Test/TestCase/ShareWishlistEntityTest.php](https://github.com/magento/magento2/blob/2.3-develop/dev/tests/functional/tests/app/Magento/Wishlist/Test/TestCase/ShareWishlistEntityTest.php)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20486) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @MilaLesechko. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by MilaLesechko** [comment]
Ok, pull request on https://github.com/magento/magento-functional-tests-migration/pull/671

**Comment by sidolov** [comment]
Closed due to move to the MFTF migration repo: https://github.com/magento/magento-functional-tests-migration/pull/671

**Pull request closed without merging**
