### PR TITLE
fix additional product options tooltip visibility

### PR DESCRIPTION
**Pull request by torhoehn**
### Fixed Issues (if relevant)

1. magento/magento2#25392: Product Additional Options Tooltip not fully visible

### Manual testing scenarios (*)

1. Create a product that includes an additionalOption value that is over 55 characters
2. Place order for product
3. View invoice for order in customer dashboard

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6216](https://jira.corp.magento.com/browse/ENGCOM-6216) has been created to process this Pull Request
:eight_spoked_asterisk: @dmytro-ch, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Bravo** [comment]
Hello @torhoehn. Thank You for Your contribution. The PR really fixes issue #25392 as it is supposed to. But there is one more issue remaining in this case. As You may see it from the image from the **Expected Result**  of #25392
Screenshot 2019-10-31 at 08 39 21
there is a whole html tag of `<a href="#" class="dots tooltip toggle" onclick="return false">...</a>` passed as a part of the customizable option text instead of supposedly only `...` that when clicked on had to fully reveal the text and hide the tooltip (or do something similar).
Though probably this related issue deserves a separate PR I'll still try to ask You could You please fix it too. Thank You.

**Comment by torhoehn** [comment]
@engcom-Bravo 
Thanks for approving this PR. Thanks for the mention of the html tag, it's already mentioned in #25050. I'll try to fix this.

**Comment by engcom-Bravo** [comment]
Thank You @torhoehn. And how would You prefer - to fix it in the current PR or in the new one?

**Comment by torhoehn** [comment]
@engcom-Bravo I think it's more clear to fix it in a separate PR.

**Comment by engcom-Bravo** [comment]
Ok, @torhoehn, then we process this one further. Thank You for the work done.

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed.

**Pull request merged**
