### PR TITLE
magento/magento2#: GraphQL. Mutation: sendEmailToFriend. Test coverage for “Please provide Email of sender.”

### LINKED ISSUE #28138: [Issue] magento/magento2#: GraphQL. Mutation: sendEmailToFriend. Test coverage for “Please provide Email of sender.”
This issue is automatically created based on existing pull request: magento/magento2#28034: magento/magento2#: GraphQL. Mutation: sendEmailToFriend. Test coverage for “Please provide Email of sender.”

---------

### Description (*)

PR provides a test coverage for `Please provide Email of sender.` error of `sendEmailToFriend` miutation.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. GraphQl query
```
mutation {
    sendEmailToFriend(
        input: {
                product_id: 1
                sender: {
                    name: "Name"
                    email: ""
                    message: "Lorem Ipsum"
                }
                recipients: [
                    {
                        name: "Recipient Name 1"
                        email:"recipient1@mail.com"
                    },
                    {
                        name: "Recipient Name 2"
                        email:"recipient2@mail.com"
                    }
                ]
        }
    ) {
        sender {
            name
            email
            message
        }
        recipients {
            name
            email
        }
    }
}
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by atwixfirster**
### Description (*)

PR provides a test coverage for `Please provide Email of sender.` error of `sendEmailToFriend` miutation.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. GraphQl query
```
mutation {
    sendEmailToFriend(
        input: {
                product_id: 1
                sender: {
                    name: "Name"
                    email: ""
                    message: "Lorem Ipsum"
                }
                recipients: [
                    {
                        name: "Recipient Name 1"
                        email:"recipient1@mail.com"
                    },
                    {
                        name: "Recipient Name 2"
                        email:"recipient2@mail.com"
                    }
                ]
        }
    ) {
        sender {
            name
            email
            message
        }
        recipients {
            name
            email
        }
    }
}
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28138: magento/magento2#: GraphQL. Mutation: sendEmailToFriend. Test coverage for “Please provide Email of sender.”

### CODE REVIEW

**Review by rogyar — APPROVED** [review]

**Comment by rogyar** [comment]
The failing tests are not related to the current change

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7494](https://jira.corp.magento.com/browse/ENGCOM-7494) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Charlie** [comment]
The failing functional tests are not related to the change in this pr.

**Comment by slavvka** [comment]
@magento create issue

**Review by slavvka — CHANGES_REQUESTED** [review]
Please fix the failing tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by slavvka — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @slavvka, thank you for the review.
[ENGCOM-7494](https://jira.corp.magento.com/browse/ENGCOM-7494) has been created to process this Pull Request

**Pull request merged**
