### PR TITLE
Disable max session size in admin - Unable to login to admin anymore …

### LINKED ISSUE #35312: Disable max session size in admin - Unable to login to admin anymore
### Preconditions (*)

1.
2. Magento 2.4-develop, 2,4,4

### Steps to reproduce (*)

1. Store > Settings > Configuration. - Advanced and choose System - Security - set Max Session Size in Admin to 0 and save
2. Login to admin

### Expected result (*)

1. [Screenshots, logs or description]
2. Login works

### Actual result (*)

1. [Screenshots, logs or description]
2. Unable to login

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by nisha-vaghela**
…#35312

### Fixed Issues (if relevant)

1. Fixes #35312

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by nisha-vaghela** [comment]
@magento give me test instance

**Comment by nisha-vaghela** [comment]
@magento give me 2.4-develop instance

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @nisha-vaghela,
Your changes look good.
Could you please cover your changes with some automated test?
Thank you!

**Comment by glo71317** [comment]
Based on the priority we are working on the automation test and will deliver soon for 2.4.5 release

**Comment by engcom-Alfa** [comment]
We raised internal PR-https://github.com/magento-gl/magento2ce/pull/288 along with this PR commits, and covering the automation tests and resolved PR comments.
Once Internal PR will get merged, will notify here

**Comment by ihor-sviziev** [comment]
@engcom-Alfa, Is there any reason you can't add commits to this PR and then merge it?

**Comment by glo71317** [comment]
> @engcom-Alfa, Is there any reason you can't add commits to this PR and then merge it?

We have added your commits in our PR, So no worries :)

**Pull request merged**
