### PR TITLE
Issue 36702: fix unit test

### LINKED ISSUE #36702: Can't run unit test
### Preconditions and environment

- Magento version 2.4-develop

### Steps to reproduce

run command: 
./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist

(doc: https://developer.adobe.com/commerce/testing/guide/unit/command-line/)

### Expected result

no error

### Actual result

Error: Config file allure/allure.config.php doesn't exist

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rogerdz**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#36702

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by hostep** [comment]
Can confirm that this change fixes running unit tests again on my local machine. Thanks @rogerdz!

**Review by fredden — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
Hi @rogerdz ,

Thank you for your contribution and collaboration.

We have tried to implement the fix provided by you and it is working fine. Running command `./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist` in the terminal is working fine  . Below is the screenshot for your reference:
Screenshot 2023-04-10 at 2 50 10 PM
Screenshot 2023-04-10 at 2 50 18 PM

But as per this [comment](https://github.com/magento/magento2/issues/36702#issuecomment-1498540704) we have checked in the PHP Storm command is failing to run in the php storm.Below is the screenshot for your reference:
Screenshot 2023-04-10 at 3 14 24 PM

Please provide us complete solution that works in PHP storm as well.

Thanks

**Comment by nishant04412** [comment]
Hi @rogerdz and @hostep,

This issue has been taken care in internal JIRA ticket. Once Internal PR will get merged, we will notify it here.

JIRA Ref: https://jira.corp.adobe.com/browse/AC-7698

Thank you!

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-7698 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-7698&type=commits

Based on the Jira ticket, the target version is 2.4.7-beta1.

Hence we are closing this PR.

Thanks

**Pull request closed without merging**
