### PR TITLE
Fixed Wrong label for button Login in checkout page #19275

### PR DESCRIPTION
**Pull request by hitesh-wagento**
### Fixed Issues (if relevant)

1. magento/magento2#19275: Wrong label for button Login in checkout page
### Steps to reproduce (*)

1. Add any product to Cart.
2. Go to checkout page
3. You can see Login text top right side.

### Expected result (*)
Buttons with correct label "Login"
login-text

### Actual result (*)
Buttons with wrong label "Sign in"

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @hitesh-wagento. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
Hi @hitesh-wagento , I believe the "Sign In" label is used for multiple templates in checkout and customer functionality, also is covered by translation https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Checkout/i18n/en_US.csv#L109. Why do you think the "Login" is the correct label?

**Comment by hitesh-wagento** [comment]
HI @sivaschenko,

You can see on checkout page left side Login button after adding Email address in input. So I am thinking we should same button lable on one page. If you need I can add "Login" translation in CSV file.

index


Thanks

**Comment by sivaschenko** [comment]
@hiren-wagento thanks for the clarification. I could find only one place in Magento where "Login" is used: the button on the checkout form. "Sing In" is the term used in all other places. Considering that even the comment above that button says "Sign In", I think that's "Login" that should be changed to "Sign In".

**Comment by sidolov** [comment]
Hi @hitesh-wagento , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
