### PR TITLE
Fix issue 20234 : Review text Should be capitalized 

### PR DESCRIPTION
**Pull request by SyntaxKay**
### Description (*)

Review text Should be capitalized

### Fixed Issues (if relevant)

1. magento/magento2#20234:  Review text Should be capitalized

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by orlangur** [comment]
Hi @speedy008, please do not add reviewers or assignees without prior agreement ;)

**Comment by rogyar** [comment]
Hi @speedy008. Thank you for your contribution. We cannot consider the existing style as an issue. Please, check the original issue for the explanation. Thank you.

**Review by orlangur — CHANGES_REQUESTED** [review]
Please update captions following https://devdocs.magento.com/guides/v2.3/design-styleguide/capitalization/capitalization.html.

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

**Comment by sidolov** [comment]
@speedy008 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
