### PR TITLE
Fixed customer_is_guest issue 24736

### PR DESCRIPTION
**Pull request by mahesh-rajawat**
Fixed issue Quote `customer_is_guest` set to 0 for guest.

### Description (*)

In this PR customer_is_guest set to 0 in quote table fixed.
### Fixed Issues (if relevant)

1. #24736 

### Manual testing scenarios (*)

1. Add a product as a guest `customer_is_guest =1` now. 
2. Now login in customer then `customer_is_guest=0` now.
3. Clear everything, add a product for logged in customer, `customer_is_guest=0`.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by Stepa4man — CHANGES_REQUESTED** [review]
Hi @maheshWebkul721
Thanks for your contribution. 
Please check red tests.

**Comment by mahesh-rajawat** [comment]
@Stepa4man @magento could you please check the failed tests in details? they are not related to this fix.

**Comment by hostep** [comment]
This might also fix https://github.com/magento/magento2/issues/23908, but somebody would need to test this very carefully as it seems to be quite complex.

**Comment by hostep** [comment]
Can we maybe also add a database migration script which executes something like:

```sql
UPDATE quote SET customer_is_guest = 0 WHERE customer_id IS NOT NULL AND customer_is_guest = 1;
UPDATE quote SET customer_is_guest = 1 WHERE customer_id IS NULL AND customer_is_guest = 0;
```

So all incorrect `customer_is_guest` flags on the quotes in the database are getting fixed.

**Comment by mahesh-rajawat** [comment]
@Stepa4man any news on it?

**Comment by engcom-Foxtrot** [comment]
@maheshWebkul721 thanks for your contribution.
Unfortunately, we cannot accept PR with failed test builds. Please, fix them. We are totally sure failures are caused by this PR.

**Comment by mahesh-rajawat** [comment]
Closing this PR, i have create new one #25010

**Pull request closed without merging**
