### PR TITLE
clean up unnecessary variable

### LINKED ISSUE #33077: [Issue] clean up unnecessary variable
This issue is automatically created based on existing pull request: magento/magento2#31790: clean up unnecessary variable

---------

### Description (*)
clean up unnecessary variable 'tmp'

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by omaxmo**
### Description (*)
clean up unnecessary variable 'tmp'

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#33077: clean up unnecessary variable

### CODE REVIEW

**Comment by omaxmo** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests, Static Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests, Static Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8709](https://jira.corp.magento.com/browse/ENGCOM-8709) has been created to process this Pull Request

**Review by ptylek — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-8709](https://jira.corp.magento.com/browse/ENGCOM-8709) has been created to process this Pull Request

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by peterjaap** [comment]
@ihor-sviziev @pytek so why is this still not merged?

**Comment by engcom-Delta** [comment]
Hi @omaxmo , Please clear the conflicts to move further in this PR

**Review by engcom-Delta — CHANGES_REQUESTED** [review]
Please clear the conflicts on the PR to test further

**Comment by engcom-Dash** [comment]
Closing this PR since it has not been updated in a while. Please feel free to reopen if needed.

**Pull request closed without merging**
