### PR TITLE
Add "Last Updated At" Column to Admin Product Grid

### LINKED ISSUE #35488: [Issue] Add "Last Updated At" Column to Admin Product Grid
This issue is automatically created based on existing pull request: magento/magento2#35436: Add "Last Updated At" Column to Admin Product Grid

---------
# Description
When managing products in the Adobe Commerce admin, it would be useful to see when they were last updated. This pull request adds that information to the grid. The information already exists in the database.

# Manual testing scenarios
1. Log into the admin
2. Navigate to `Catalog -> Products`
3. Notice the list of products lacks information about the last time it was updated
4. Apply the changes in this pull request
5. Notice the list of products now shows the date/time it was last updated

# Contribution checklist
- [x] Pull request has a meaningful description of its purpose
- [x] All commits are accompanied by meaningful commit messages
- [x] All new or changed code is covered with unit/integration tests (if applicable)
- [x] `README.md` files for modified modules are updated and included in the pull request if any [`README.md` predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
- [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by pykettk**
# Description
When managing products in the Adobe Commerce admin, it would be useful to see when they were last updated. This pull request adds that information to the grid. The information already exists in the database.

# Manual testing scenarios
1. Log into the admin
2. Navigate to `Catalog -> Products`
3. Notice the list of products lacks information about the last time it was updated
4. Apply the changes in this pull request
5. Notice the list of products now shows the date/time it was last updated

# Contribution checklist
- [x] Pull request has a meaningful description of its purpose
- [x] All commits are accompanied by meaningful commit messages
- [x] All new or changed code is covered with unit/integration tests (if applicable)
- [x] `README.md` files for modified modules are updated and included in the pull request if any [`README.md` predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
- [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#35488: Add "Last Updated At" Column to Admin Product Grid

### CODE REVIEW

**Comment by pykettk** [comment]
@magento run Functional Tests B2B

**Comment by pykettk** [comment]
@magento run Integration Tests

**Comment by torhoehn** [comment]
@magento run all tests

**Review by torhoehn — APPROVED** [review]
LGTM!

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

- Install the fresh Magento 2.4-develop instance with sample data.

**Manual testing scenario:**
1. Go to Magento admin.
2. Click on Catalog >> Product
3. Check whether admin is able to see when product is updated last time.

**Before:** :heavy_multiplication_x: There was no information about when product is updated last time.
Screenshot from 2022-05-17 15-08-30


**After:** :heavy_check_mark:  Admin is able to see the information about when product got updated.
Screenshot from 2022-05-17 15-20-56

Edited the product and validated for current date is displaying in the `Last Updated At` column.
Since its a small UI change hence,there is no need for additional manual/automated case for regression.

**Comment by engcom-Alfa** [comment]
Since it has a _feature request_ updates, we have to update the Magento document as well.
Here is the current document link - https://docs.magento.com/user-guide/catalog/products.html on this.
Should be noted for documentation purpose.
Thanks

**Comment by pykettk** [comment]
@engcom-Alfa I'll make the necessary changes to the linked documentation later today - thanks for the link, it's very convenient.

As for creating test cases, would you be able to assist with pointing me in the right direction here please? I'm not too familiar with the MFTF or how UI Component tests are conducted so highlighting an example would be perfect. Failing that I'll spend some time digging around, though this might take a little longer while I figure it out.

**Comment by engcom-Alfa** [comment]
> @engcom-Alfa I'll make the necessary changes to the linked documentation later today - thanks for the link, it's very convenient.
> 
> As for creating test cases, would you be able to assist with pointing me in the right direction here please? I'm not too familiar with the MFTF or how UI Component tests are conducted so highlighting an example would be perfect. Failing that I'll spend some time digging around, though this might take a little longer while I figure it out.

Thanks for your response @pykettk. Internal team will do these necessary activities on this. Nothing to do from your end now.
Thanks much for your contribution

**Pull request merged**
