### PR TITLE
magento/magento2#8596: Varnish/ESI breaks on product pages when skus …

### PR DESCRIPTION
**Pull request by mcspronko**
…have slashes

 - added base64_encode function for handles to support /

### CODE REVIEW

**Comment by okorshenko** [comment]
Hi @mcspronko 
Could you please resolve the code conflict so that we can process this RP?

**Comment by mcspronko** [comment]
Hi @okorshenko 

Yes, no problem.

**Comment by mcspronko** [comment]
@okorshenko please check now.

**Comment by okorshenko** [comment]
Will be delivered in scope of https://github.com/magento/magento2/pull/8769

**Pull request closed without merging**
