### PR TITLE
Adjust critical CSS extraction and placement

### LINKED ISSUE #26498: CSS shows up twice when Critical CSS Enabled
### Preconditions (*)

1. 2.3.4
2.

### Steps to reproduce (*)

1. Enable `use_css_critical_path`

### Expected result (*)

1. The stylesheets are only loaded once

### Actual result (*)

1. `styles-m.css`, `styles-l.css` and `print.css` styles show up multiple times in developer tools.

I have traced the problem to the following method:
`beforeSendResponse` in `module-theme/Controller/Result/AsyncCssPlugin.php`

This line appears to be re-inserting the original style tags:

```
$content = str_replace('</body', implode("\n", $cssMatches) . "\n</body", $content);
```

If you comment out this line, the HTML is as expected, with each style element existing only once and preventing double download of stylesheets.

I think there's some confusion over the implementation of the following technique:

```
<link rel="preload" as="style" media="all" onload="this.onload=null;this.rel='stylesheet'"href="...en_US/css/styles-m.css">
```

I would expect that the purpose of the onload method is that rather than needing one `<link>` to preload and a separate `<link>` at the bottom of the HTML to then achieve the affect of asynchronously loading the CSS, this behaviour can be achieved with just one `<link>` element. After `onload` event has fired, the `rel` attribute swaps and applies the CSS.

### PR DESCRIPTION
**Pull request by krzksz**
### Description (*)
This pull requests introduces following changes:

- Async CSS loading pattern is updated according to the [newest best practice](https://timkadlec.com/remembers/2020-02-13-when-css-blocks/), allowing us to completely remove `rel="preload"` polyfill.
- Moving existing stylesheets around no longer uses regular expressions which should reduce memory consumption and prevent backtrace limit errors for large pages.
- Styles are now added once, before `</head>` tag, after critical CSS. 

### Fixed Issues (if relevant)

1. magento/magento2#26498: CSS shows up twice when Critical CSS Enabled

### Manual testing scenarios (*)

1. Enable critical CSS in Magento's admin panel and flush the case.
2. Verify that all external stylesheets are loaded asynchronously without blocking first contentful and meaningful paint.
3. Verify that all external stylesheets are located in the same order at the end of  `<head>`, after inline cricitcal CSS.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
In general looks good to me. Let’s wait for test results

**Review by ihor-sviziev — DISMISSED** [review]
Functional test failures not related to changes from this PR.
SVC failure should be approved, but I think in this case it’s not a big deal
Approved!

@krzksz thank you for amazing job!

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7086](https://jira.corp.magento.com/browse/ENGCOM-7086) has been created to process this Pull Request

**Review by engcom-Delta — CHANGES_REQUESTED** [review]
Hi @krzksz described scenario from [issue](https://github.com/magento/magento2/issues/26498#issuecomment-577236042) is still reproducible: `styles-m.css`, `styles-l.css` are loaded twice
image

Could you take a look?

**Comment by krzksz** [comment]
On it.

**Comment by krzksz** [comment]
Fixed, check for `</head` was also catching on `</header>` tag :D

**Comment by ihor-sviziev** [comment]
@krzksz will you be able to cover this new issue with test?

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7086](https://jira.corp.magento.com/browse/ENGCOM-7086) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Comment by engcom-Echo** [comment]
Backward incompatible changes (deleted block)- need approve

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @krzksz,
Now we have array to string conversion after your latest change.
Please fix it

**Comment by VladimirZaets** [comment]
Hi @krzksz, do you have any updates?

**Comment by krzksz** [comment]
@VladimirZaets Hey, I'm waiting for the conclusion in https://github.com/magento/magento2/pull/27270, then we can apply the final approach here.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @krzksz,
https://github.com/magento/magento2/pull/27270 was already merged. Please update your PR.

**Comment by ihor-sviziev** [comment]
@krzksz ,
will you be able to update your PR?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Hi @krzksz,
I'm closing this PR due to inactivity and as we already have better PR https://github.com/magento/magento2/pull/28480

**Pull request closed without merging**
