### PR TITLE
Added unique key on eav_attribute_label table

### PR DESCRIPTION
**Pull request by alex311982**
**Description (*)**
The table eav_attribute_label should contain a unique key constraint on the (store_id, attribute_id) pair.
This PR add it.

**Contribution checklist (*)**
 Pull request has a meaningful description of its purpose
 All commits are accompanied by meaningful commit messages
 All new or changed code is covered with unit/integration tests (if applicable)
 All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@alex311982 Please sign Adobe CLA.

**Comment by alex311982** [comment]
@magento give me test instance

**Comment by alex311982** [comment]
@magento give me test instance

**Comment by alex311982** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests, Semantic Version Checker, Unit Tests

**Pull request closed without merging**
