### PR TITLE
requirejs-config.js files only generated for default locale

### PR DESCRIPTION
**Pull request by BlackIkeEagle**
When we deploy the static files, the requirejs-config.js files are only
generated for the default locale, no matter what locales are required in
the deployment.

For example, we have a Belgian shop with 4 locales nl_NL, fr_FR, de_DE
and en_US. Where we have nl_NL set as default locale for the shop.

we run:
$ bin/magento setup:static-content:deploy en_US nl_NL fr_FR de_DE

we only get the following requirejs-config files:

./pub/static/_requirejs/
./pub/static/_requirejs/adminhtml/
./pub/static/_requirejs/adminhtml/Magento/
./pub/static/_requirejs/adminhtml/Magento/backend/
./pub/static/_requirejs/adminhtml/Magento/backend/nl_NL/
./pub/static/_requirejs/adminhtml/Magento/backend/nl_NL/requirejs-config.js
./pub/static/_requirejs/frontend/
./pub/static/_requirejs/frontend/Magento/
./pub/static/_requirejs/frontend/Magento/blank/
./pub/static/_requirejs/frontend/Magento/blank/nl_NL/
./pub/static/_requirejs/frontend/Magento/blank/nl_NL/requirejs-config.js

This fix makes sure the localeresolver is set to the desired locale for
deploying resulting in:

./pub/static/_requirejs/
./pub/static/_requirejs/adminhtml/
./pub/static/_requirejs/adminhtml/Magento/
./pub/static/_requirejs/adminhtml/Magento/backend/
./pub/static/_requirejs/adminhtml/Magento/backend/nl_NL/
./pub/static/_requirejs/adminhtml/Magento/backend/nl_NL/requirejs-config.js
./pub/static/_requirejs/adminhtml/Magento/backend/en_US/
./pub/static/_requirejs/adminhtml/Magento/backend/en_US/requirejs-config.js
./pub/static/_requirejs/adminhtml/Magento/backend/fr_FR/
./pub/static/_requirejs/adminhtml/Magento/backend/fr_FR/requirejs-config.js
./pub/static/_requirejs/adminhtml/Magento/backend/de_DE/
./pub/static/_requirejs/adminhtml/Magento/backend/de_DE/requirejs-config.js
./pub/static/_requirejs/frontend/
./pub/static/_requirejs/frontend/Magento/
./pub/static/_requirejs/frontend/Magento/blank/
./pub/static/_requirejs/frontend/Magento/blank/nl_NL/
./pub/static/_requirejs/frontend/Magento/blank/nl_NL/requirejs-config.js
./pub/static/_requirejs/frontend/Magento/blank/en_US/
./pub/static/_requirejs/frontend/Magento/blank/en_US/requirejs-config.js
./pub/static/_requirejs/frontend/Magento/blank/fr_FR/
./pub/static/_requirejs/frontend/Magento/blank/fr_FR/requirejs-config.js
./pub/static/_requirejs/frontend/Magento/blank/de_DE/
./pub/static/_requirejs/frontend/Magento/blank/de_DE/requirejs-config.js

fixes MAG2DBCEN-21

Signed-off-by: Ike Devolder ike.devolder@studioemma.eu

### CODE REVIEW

**Comment by dsikkema-magento** [comment]
Internal ticket created: MAGETWO-49717

**Comment by rossluk** [comment]
I think resolver part should be in emulateApplicationLocale method, because Resolver used in Translator too.

**Comment by okorshenko** [comment]
@BlackIkeEagle Your Pull Request merged to develop branch. Thank you for contribution!

**Comment by BlackIkeEagle** [comment]
@okorshenko Do you have a resource where we can see when certain fixes would land in 2.0 ? Thanks.

**Comment by okorshenko** [comment]
@BlackIkeEagle this fix was merged to `develop` branch and will be available in the next minor release. We will take into account your request to include this fix to next patch release. Thank you.

**Pull request merged**
