### PR TITLE
Extract images from content only when new media gallery enabled

### LINKED ISSUE #1750: The content modules does not aware of Media Gallery status
### Preconditions (*)
1. Magento 2.4-dvelop installed
2. New media Gallery Disabled by default.

### Steps to reproduce (*)

1. Navigate to Cms grid or Product Grid
2. Create new (product or page or block)
3. Attach image to the descriptions field of entity
4. Save entity (note that new media gallery disabled)

### Expected result (*)
Exception.log file is empty there is no any exception

### Actual result (*)
```
[2020-08-12 10:30:12] main.CRITICAL: There is no such media asset with path "wysiwyg/womens/womens-t-shirts.png" {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): There is no such media asset with path \"wysiwyg/womens/womens-t-shirts.png\" at /var/www/html/magento24/app/code/Magento/MediaGallery/Model/Asset/Command/GetByPath.php:81)"} []
[2020-08-12 10:30:12] main.CRITICAL: An error occurred during get media asset list: There is no such media asset with path "wysiwyg/womens/womens-t-shirts.png" {"exception":"[object] (Magento\\Framework\\Exception\\IntegrationException(code: 0): An error occurred during get media asset list: There is no such media asset with path \"wysiwyg/womens/womens-t-shirts.png\" at /var/www/html/magento24/app/code/Magento/MediaGallery/Model/Asset/Command/GetByPath.php:103, Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): There is no such media asset with path \"wysiwyg/womens/womens-t-shirts.png\" at /var/www/html/magento24/app/code/Magento/MediaGallery/Model/Asset/Command/GetByPath.php:81)"} []

```

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1750: The content modules does not aware of Media Gallery status

### Manual testing scenarios (*)
1. Magento 2.4-dvelop installed
2. New media Gallery Disabled by default.
3. Navigate to Cms grid or Product Grid
4. Create new (product or page or block)
5. Attach image to the descriptions field of entity
6. Save entity (note that new media gallery disabled)

### Expected result (*)
Exception.log file is empty there is no any exception

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed 
Exception.log file is empty there is no any exception
Manual testing [scenario](https://studio.cucumber.io/projects/131313/test-plan/folders/1054245/scenarios/5088660)

**Pull request merged**
