### PR TITLE
503 error on store front catalog pages

### LINKED ISSUE #29660: [Issue] 503 error on store front catalog pages
This issue is automatically created based on existing pull request: magento/magento2#29146: 503 error on store front catalog pages

---------

### Description (*)

https://support.magento.com/hc/en-us/articles/360025762211-503-error-on-store-front-catalog-pages-with-Integrity-constraint-violation-in-logs
The described error even occurs in Magento 2.3.3 Open Source, so the changes of the patch should be in the core files.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by torhoehn**
### Description (*)

https://support.magento.com/hc/en-us/articles/360025762211-503-error-on-store-front-catalog-pages-with-Integrity-constraint-violation-in-logs
The described error even occurs in Magento 2.3.3 Open Source, so the changes of the patch should be in the core files.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29660: 503 error on store front catalog pages

### CODE REVIEW

**Comment by torhoehn** [comment]
@magento run all tests

**Comment by torhoehn** [comment]
Static Tests doesn't fail because of this PR.

**Comment by rogyar** [comment]
Hi @torhoehn. Thank you for your collaboration. 
I'm not sure this patch should be a part of the core. Let me explain my point. 
The problem of duplicated entries in `search_tmp_` tables has been fixed, so the mentioned entries don't appear anymore. 
They may appear in case if you are upgrading Magento from 2.2.x (where this issue was present) to 2.3.x. 
The mentioned patch introduces a "brute-force" like workaround for overriding the existing records. 
With the current system default behavior, there's no need to override the records. But if there are still duplicated records in this table, the cause of that might be different and by providing this workaround we will "hide" the issue. So we never know the original cause of it. 
I believe that's the main idea why the "workaround" is not included into the core.

**Comment by torhoehn** [comment]
@rogyar Thanks for your explanation. Indeed we had this in a system that was upgraded from 2.2.x to 2.3.x. But even after a complete reset of all indices, we got this exception again. Do you know another way to prevent this issue or to find out what causes this?

**Comment by rogyar** [comment]
Hi @torhoehn. I wish I could help you with the solution. Usually, we apply this patch on such projects. But this issue never appears on the "clean" 2.3 projects.

**Comment by torhoehn** [comment]
Thanks for your answer! :)

**Comment by sidolov** [comment]
@magento create issue

**Comment by sidolov** [comment]
Hi @rogyar according to your conversation I can assume that current solution will fix the symptom, not the cause. @torhoehn are you going to investigate the root cause of the problem or we can close the PR? 
Thank you guys for your feedback!

**Review by sidolov — CHANGES_REQUESTED** [review]
Looks like fix is not reliable

**Comment by torhoehn** [comment]
@sidolov For us the fix is working fine and has solved this kind of exceptions and empty catalog category views. I don't know why the community should find out the cause of the problem if Magento already provided a patch for this problem.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Hi @torhoehn,
Could you describe steps to reproduce of the issue on latest magento version?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @torhoehn,
Linked article says that issue was fixed in 2.3.3 and clearly describes that this is workaround. Could you describe steps to reproduce of the issue on latest magento version? 
Maybe instead of implementing workaround we could write some patch that will execute automatically during upgrade and will fix the root of the issue?

**Comment by ihor-sviziev** [comment]
@torhoehn could you answer to https://github.com/magento/magento2/pull/29146#pullrequestreview-491230538 ?

**Comment by engcom-Charlie** [comment]
@torhoehn please look at https://github.com/magento/magento2/pull/29146#pullrequestreview-491230538. Otherwise, we can't proceed with your PR.
Thank you.

**Comment by engcom-Charlie** [comment]
Hi @torhoehn, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
