### PR TITLE
UPS negotiated rate error blocks checkout

### PR DESCRIPTION
**Pull request by nfourteen**
### Description
Magento v2.2.2

This PR fixes an error when the UPS API returns a `//RatingServiceSelectionResponse/RatedShipment/NegotiatedRates` value for some, but not all configured service **Allowed Methods** and completely blocks checkout as the customer can't select any shipping options.

**Screenshot from checkout/cart URL**
screen shot 2018-03-22 at 9 32 50 pm

Based upon what the UPS API returns, this may or may not be reproducible. I'll include the XML for the 3 configured services I was receiving from UPS at the bottom. 

I believe it's safer to check whether the `NegotiatedRates` node exists for the current service `$code` in the `$allowedMethods` array. Currently the code assumes that if:
```
$negotiatedArr = $xml->getXpath("//RatingServiceSelectionResponse/RatedShipment/NegotiatedRates");
```
isn't `empty` then the `NegotiatedRates` node exists for all services. But if a `NegotiatedRates` node exists for service code **01 - UPS Next Day Air**, but not for service code **03 - UPS Ground**, then the `$negotiatedActive` check will be `true` while processing service code **03**. But when: 
```
$cost = $shipElement->NegotiatedRates->NetSummaryCharges->GrandTotal->MonetaryValue;
```
is executed a **Trying to get property of non-object** error will occur causing a 500 (Internal Service Error) response.

screen shot 2018-03-22 at 10 36 47 pm

### Fixed Issues (if relevant)
n/a

### Manual testing scenarios
1. Enable **Flat Rate** (default is enabled) and **UPS** options in `Stores > Configuration > Sales > Shipping Methods`
2. Set up UPS configuration (see screenshot below)
    * The **Ship to Specific Countries** option was set to only _United States_
3. Add some products to the cart
    * Go to the mini cart and select **View and Edit Cart**
    * Select the **Estimate Shipping and Tax** dropdown
    * Enter a valid state and zip combination
or
    * Go to the mini cart and select **Proceed to Checkout**
    * Enter a valid address

oee test_admin_admin_system_config_edit_section_carriers

```xml
<!-- UPS Next Day Air -->
<RatedShipment>
	<Service>
		<Code>01</Code>
	</Service>
	<RatedShipmentWarning>Your invoice may vary from the displayed reference rates</RatedShipmentWarning>
	<BillingWeight>
		<UnitOfMeasurement>
			<Code>LBS</Code>
		</UnitOfMeasurement>
		<Weight>1.0</Weight>
	</BillingWeight>
	<TransportationCharges>
		<CurrencyCode>USD</CurrencyCode>
		<MonetaryValue>35.70</MonetaryValue>
	</TransportationCharges>
	<ServiceOptionsCharges>
		<CurrencyCode>USD</CurrencyCode>
		<MonetaryValue>0.00</MonetaryValue>
	</ServiceOptionsCharges>
	<TotalCharges>
		<CurrencyCode>USD</CurrencyCode>
		<MonetaryValue>35.70</MonetaryValue>
	</TotalCharges>
	<GuaranteedDaysToDelivery>1</GuaranteedDaysToDelivery>
	<ScheduledDeliveryTime>10:30 A.M.</ScheduledDeliveryTime>
	<RatedPackage>
		<TransportationCharges>
			<CurrencyCode>USD</CurrencyCode>
			<MonetaryValue>35.70</MonetaryValue>
		</TransportationCharges>
		<ServiceOptionsCharges>
			<CurrencyCode>USD</CurrencyCode>
			<MonetaryValue>0.00</MonetaryValue>
		</ServiceOptionsCharges>
		<TotalCharges>
			<CurrencyCode>USD</CurrencyCode>
			<MonetaryValue>35.70</MonetaryValue>
		</TotalCharges>
		<Weight>0.6</Weight>
		<BillingWeight>
			<UnitOfMeasurement>
				<Code>LBS</Code>
			</UnitOfMeasurement>
			<Weight>1.0</Weight>
		</BillingWeight>
	</RatedPackage>
	<NegotiatedRates>
		<NetSummaryCharges>
			<GrandTotal>
				<CurrencyCode>USD</CurrencyCode>
				<MonetaryValue>28.26</MonetaryValue>
			</GrandTotal>
		</NetSummaryCharges>
	</NegotiatedRates>
</RatedShipment>
```
```xml
<!-- UPS Second Day Air -->
<RatedShipment>
	<Service>
		<Code>02</Code>
	</Service>
	<RatedShipmentWarning>Your invoice may vary from the displayed reference rates</RatedShipmentWarning>
	<BillingWeight>
		<UnitOfMeasurement>
			<Code>LBS</Code>
		</UnitOfMeasurement>
		<Weight>1.0</Weight>
	</BillingWeight>
	<TransportationCharges>
		<CurrencyCode>USD</CurrencyCode>
		<MonetaryValue>24.20</MonetaryValue>
	</TransportationCharges>
	<ServiceOptionsCharges>
		<CurrencyCode>USD</CurrencyCode>
		<MonetaryValue>0.00</MonetaryValue>
	</ServiceOptionsCharges>
	<TotalCharges>
		<CurrencyCode>USD</CurrencyCode>
		<MonetaryValue>24.20</MonetaryValue>
	</TotalCharges>
	<GuaranteedDaysToDelivery>2</GuaranteedDaysToDelivery>
	<ScheduledDeliveryTime/>
	<RatedPackage>
		<TransportationCharges>
			<CurrencyCode>USD</CurrencyCode>
			<MonetaryValue>24.20</MonetaryValue>
		</TransportationCharges>
		<ServiceOptionsCharges>
			<CurrencyCode>USD</CurrencyCode>
			<MonetaryValue>0.00</MonetaryValue>
		</ServiceOptionsCharges>
		<TotalCharges>
			<CurrencyCode>USD</CurrencyCode>
			<MonetaryValue>24.20</MonetaryValue>
		</TotalCharges>
		<Weight>0.6</Weight>
		<BillingWeight>
			<UnitOfMeasurement>
				<Code>LBS</Code>
			</UnitOfMeasurement>
			<Weight>1.0</Weight>
		</BillingWeight>
	</RatedPackage>
	<NegotiatedRates>
		<NetSummaryCharges>
			<GrandTotal>
				<CurrencyCode>USD</CurrencyCode>
				<MonetaryValue>19.49</MonetaryValue>
			</GrandTotal>
		</NetSummaryCharges>
	</NegotiatedRates>
</RatedShipment>
```
```xml
<!-- UPS Ground -->
<RatedShipment>
	<Service>
		<Code>03</Code>
	</Service>
	<RatedShipmentWarning>Your invoice may vary from the displayed reference rates</RatedShipmentWarning>
	<BillingWeight>
		<UnitOfMeasurement>
			<Code>LBS</Code>
		</UnitOfMeasurement>
		<Weight>1.0</Weight>
	</BillingWeight>
	<TransportationCharges>
		<CurrencyCode>USD</CurrencyCode>
		<MonetaryValue>9.43</MonetaryValue>
	</TransportationCharges>
	<ServiceOptionsCharges>
		<CurrencyCode>USD</CurrencyCode>
		<MonetaryValue>0.00</MonetaryValue>
	</ServiceOptionsCharges>
	<TotalCharges>
		<CurrencyCode>USD</CurrencyCode>
		<MonetaryValue>9.43</MonetaryValue>
	</TotalCharges>
	<GuaranteedDaysToDelivery/>
	<ScheduledDeliveryTime/>
	<RatedPackage>
		<TransportationCharges>
			<CurrencyCode>USD</CurrencyCode>
			<MonetaryValue>9.43</MonetaryValue>
		</TransportationCharges>
		<ServiceOptionsCharges>
			<CurrencyCode>USD</CurrencyCode>
			<MonetaryValue>0.00</MonetaryValue>
		</ServiceOptionsCharges>
		<TotalCharges>
			<CurrencyCode>USD</CurrencyCode>
			<MonetaryValue>9.43</MonetaryValue>
		</TotalCharges>
		<Weight>0.6</Weight>
		<BillingWeight>
			<UnitOfMeasurement>
				<Code>LBS</Code>
			</UnitOfMeasurement>
			<Weight>1.0</Weight>
		</BillingWeight>
	</RatedPackage>
</RatedShipment>
```

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by larsroettig — CHANGES_REQUESTED** [review]
Hi @nfourteen,
currently you have a conflict in **app/code/Magento/Ups/Model/Carrier.php**

Can you check this, please also I recommend adding the use cases to \Magento\Dhl\Test\Unit\Model\CarrierTest for a better quality.

best regards,

Lars

**Comment by nfourteen** [comment]
@larsroettig I will submit a test shortly.

**Comment by nfourteen** [comment]
@larsroettig I've finished submitting the requested changes. Thanks!

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14276) <br/>All committers have signed the CLA.

**Comment by sidolov** [comment]
Hi @nfourteen , please, sign CLA, otherwise, we can't process your pull request

**Review by larsroettig — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-2722](https://jira.corp.magento.com/browse/ENGCOM-2722) has been created to process this Pull Request

**Comment by sidolov** [comment]
Hi @nfourteen , we can't reproduce this issue on the latest 2.2-develop branch. 

**Manual testing scenario:**

1. Set Shipping origin US.
2. Configure UPS.
3. Change appropriate UPS settings as described in PR.
4. Add simple product to cart
5. Go to the mini cart and select View and Edit Cart
6. Select the Estimate Shipping and Tax dropdown
7. Enter a valid state and zip combination:

- Country=United
- States
- State/Province=Maryland
- Zip/Postal Code=21703

**Actual Result:**
UPS shipping methods are displayed

Please, verify this issue on the latest 2.2-develop and provide additional steps if issue still reproducing. 
Thank you!

**Comment by nfourteen** [comment]
Hello @sidolov, I will definitely look into whether this is still reproducible on the current 2.2-develop branch. However, I won't be able to look into it until Dec as I'm currently traveling and don't have my development machine. Is it possible to leave this issue open until then?

**Comment by sidolov** [comment]
Hi @nfourteen , I think we can close PR now and reopen it when you decide to continue progress. What do you think?

**Comment by nfourteen** [comment]
@sidolov I think that would be fine. However, as far as I can see, every other xpath node is checked in some way to ensure it's not null—except the negotiated rates node. That's all this PR does and whether the issue still exists or not, I believe it would be good to check for null values—especially considering UPS could change their response at any time. But feel free to close it and I'll reopen it if I can reproduce the error when I return home.

**Comment by sidolov** [comment]
@nfourteen thank you for the fast response! Hope you will have time to finish your pull request! 
Thank you!

**Comment by nfourteen** [comment]
@sidolov I can confirm this issue is still reproducible in `magento:2.2-develop` and `magento:2.3-develop`. The basic issue that remains is that the current logic assumes all `RatedShipment` nodes will contain a `NegotiatedRates` node. This, however, is not the case and although it may be difficult to reproduce I would like to ask that the Magento Core team review this issue throughly rather than closing it because it can't be reproduced.

The problem is that the `$negotiatedArr` contains `NegotiatedRates` nodes from the entire response for all `RatedShipment` nodes, but each individual `RatedShipment` is never checked if it has a `NegotiatedRates` node. The `$negotiatedArr` variable is used to check if negotiated rates are active (along with two other user defined config variables), which currently the conditional test `!empty($negotiatedArr)` will always be true so long as one `RatedShipment` node contains a `NegotiatedRates` node.

In the UPS API documentation, per page 72 of **Rating Package XML Developer Guide.pdf**, it states that "...if a particular shipment based on zone, origin, destination or even shipment size doesn't qualify for the existing discount then no negotiated rates container will be returned." To me that clearly states that sometimes not all `RatedShipment` nodes will contain a `NegotiatedRates` node, which I hope will further convey the possibility that it may be a difficult issue to reproduce.

I realize this got pretty wordy and it's probably pretty difficult to follow without code. I would be happy to create a Github repo containing what I have and some code mock ups to explain the issue in a more concise manner. Please let me know at your convenience if there's any questions or if I can clarify anything. 

Thank you!

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-4500](https://jira.corp.magento.com/browse/ENGCOM-4500) has been created to process this Pull Request

**Review by orlangur — CHANGES_REQUESTED** [review]
@nfourteen,

> I can confirm this issue is still reproducible in magento:2.2-develop and magento:2.3-develop

Then it needs to be fixed in `2.3-develop` first. Please prepare another pull request.

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

**Comment by sidolov** [comment]
Hi @nfourteen , will you continue progress on this? We just need the same changes for 2.3-develop first. Thank you!

**Comment by nfourteen** [comment]
Hello @sidolov, Sorry...I just returned from a 1.5 month trip with very limited internet access. Yes, I will try and get the done this weekend. Thanks!

**Comment by nfourteen** [comment]
Hello @sidolov, I looked into this and it seems it was fixed in a commit made on Apr 30, 2019 by @zakdma. See [commit here](https://github.com/magento/magento2/commit/74e912abd53d70b130b437c4f197e09d3bdf0684#diff-448789bcf544b1a120dd8d12bb25db70).

The `NegotiatedRates` array is correctly being checked to make sure the node exists in both 2.3 and 2.2. I think we can close this PR at this time.

**Pull request closed without merging**
