### PR TITLE
Product not exist fix when attempt to get an image

### LINKED ISSUE #26876: Error when sending sales mails in async mode if product was removed
### Preconditions (*)

1. magento 2.3.1+
2. 

### Steps to reproduce (*)

1. Set up async mails sending 
2. Buy a product, create order, invoice or shipment
3. Send sales mails
4. Remove product (along with configurable(parent) product)
5. Try to resend sales email (e.g. set column `email_sent` to Null in relative tables)
6. or try to send invoice/shipment again 
Selection_375

### Expected result (*)

1. Emails are send
2. If there are newer sales items planned to send (email_sent is null) emails will be sent
3. Job code shows warning or problem item is ignored but newer items are sent

### Actual result (*)

1. Emails are not sent
2. If there are newer sales items planned to send (email_sent is null) emails will not be sent; It leads that sales async mailing stop working
Selection_374
3. in `var/log/cron.log` this log appears 
```
[2020-02-14 12:41:09] main.ERROR: Cron Job sales_send_order_invoice_emails has an error: Call to a member function getData() on null. Statistics: {"sum":0,"count":1,"realmem":0,"emalloc":0,"realmem_start":73400320,"emalloc_start":36940360} [] []
[2020-02-14 12:41:09] main.CRITICAL: Error when running a cron job {"exception":"[object] (RuntimeException(code: 0): Error when running a cron job at /var/www/html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:327, Error(code: 0): Call to a member function getData() on null at /var/www/html/vendor/magento/module-catalog/Helper/Image.php:502)"} []

```
4. Newer items are blocked to send

### PR DESCRIPTION
**Pull request by ilnytskyi**
### Description (*)

This PR fixes an issue when async email sending is blocked because the removed product
And this error is shown 
```
main.ERROR: Cron Job sales_send_order_invoice_emails has an error: Call to a member function getData() on null. Statistics: {"sum":0,"count":1,"realmem":0,"emalloc":0,"realmem_start":73400320,"emalloc_start":37177640} [] []
main.CRITICAL: Error when running a cron job {"exception":"[object] (RuntimeException(code: 0): Error when running a cron job at /var/www/html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:327, Error(code: 0): Call to a member function getData() on null at /var/www/html/vendor/magento/module-catalog/Helper/Image.php:502)"} []
```
### Fixed Issues (if relevant)

1. Fixes magento/magento2#26876

### Manual testing scenarios (*)

1. See steps form the issue https://github.com/magento/magento2/issues/26876
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7517](https://jira.corp.magento.com/browse/ENGCOM-7517) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @ilnytskyi. Thanks for collaboration. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests or update the existing ones.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by lenaorobei — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-7517](https://jira.corp.magento.com/browse/ENGCOM-7517) has been created to process this Pull Request

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @ilnytskyi . 
Unfortunately, we are not able to reproduce this problem following by steps from the [issue](https://github.com/magento/magento2/issues/26876#issue-565310749) .

**Precondition:**
Have Configurable product with images;

**Manual testing scenario:**

1. Set up async mails sending ( Go to Admin -> Stores -> Configuration -> Sales -> Sales Emails -> General Settings and set **Asynchronous sending** to "Enable");
2. Create Order -> Invoice -> Shipment;
3. Send sales mails

Actual Result: :heavy_check_mark: All 3 messages were received

Screenshot from 2020-08-21 14-20-54

4. Remove product (along with configurable(parent) product);
5. try to send the invoice again


**Actual Result:** :heavy_check_mark: the message was successfully received



@ilnytskyi Could you take a look? Maybe we missed something..

Thanks!

**Comment by ilnytskyi** [comment]
@engcom-Alfa 
It was actual for 2.3.1 so maybe now somethings is different.
Please confirm that you use cron to sent an email, and the image is used in the email template.

**Comment by lenaorobei** [comment]
@engcom-Alfa could you please confirm https://github.com/magento/magento2/pull/26877#issuecomment-681694449

**Comment by engcom-Alfa** [comment]
Hi @ilnytskyi @lenaorobei .

We checked this PR in more detail again and we were able to reproduce this problem in the following steps:

**Precondition:**

Since there is no product image in the email templates, we have added this programmatically.

**Manual testing scenario:**

1. Set up async mails sending ( Go to Admin -> Stores -> Configuration -> Sales -> Sales Emails -> General Settings and set **Asynchronous sending** to **Enable**);
2. Create a product with an image;
3. Go to Storefront;
4. Add product to Cart and create order;
5. Send sales emails;
6. Run **cron**;

**Actual Result:** :heavy_check_mark: The order confirmation email was received

Screenshot from 2020-09-07 16-21-59


7. Remove product ;
8. Try to resend sales email (e.g. set column email_sent to Null in relative tables);
9. Run **cron**;

**Actual Result:** :heavy_multiplication_x: If there are newer sales items planned to send (email_sent is null) emails will not be sent; It leads that sales async mailing stop working



in `var/log/cron.log` this log appears

Screenshot from 2020-09-07 16-26-14

@lenaorobei Could you approve it again?

Thanks!

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-7517](https://jira.corp.magento.com/browse/ENGCOM-7517) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Precondition:**

Since there is no product image variable in the email templates, we have added this programmatically.

**Manual testing scenario:**

1. Set up async mails sending ( Go to Admin -> Stores -> Configuration -> Sales -> Sales Emails -> General Settings and set **Asynchronous sending** to **Enable**);
2. Create a product with an image;
3. Go to Storefront;
4. Add product to Cart and create order;
5. Send sales emails;
6. Run **cron**;

**Actual Result:** :heavy_check_mark: The order confirmation email was received

Screenshot from 2020-09-07 16-21-59


7. Remove product ;
8. Try to resend sales email (e.g. set column email_sent to Null in relative tables);
9. Run **cron**;

**Before** :heavy_multiplication_x: Emails are not sent
:heavy_multiplication_x: If there are newer sales items planned to send (email_sent is null) emails will not be sent; It leads that sales async mailing stop working



in `var/log/cron.log` this log appears

Screenshot from 2020-09-07 16-26-14

**After:** :heavy_check_mark: Emails are send

Screenshot from 2020-09-09 11-32-05

:heavy_check_mark: If there are newer sales items planned to send (email_sent is null) emails will be sent

**Pull request merged**
