### PR TITLE
Changes on Region/State

### LINKED ISSUE #33180: [Issue] Changes on Region/State
This issue is automatically created based on existing pull request: magento/magento2#33175: Changes on Region/State

---------

### Description (*)
Changed **Region/State** to **Region/State/Province** As User is able to select **Province** Along with **State** and **Region**.
At Admin-panel : `General->General->Store Information` and `Sales->Shipping Settings->Origin`  **Region/State** Field is there.

image

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by manavluhar**
### Description (*)
Changed **Region/State** to **Region/State/Province** As User is able to select **Province** Along with **State** and **Region**.
At Admin-panel : `General->General->Store Information` and `Sales->Shipping Settings->Origin`  **Region/State** Field is there.

image

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#33180: Changes on Region/State

### CODE REVIEW

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Unit Tests

**Comment by Den4ik** [comment]
@magento create issue

**Comment by Den4ik** [comment]
@magento run Integration Tests

**Pull request closed without merging**
