### PR TITLE
Resolve "Merge On Conflict" missing the Label in "New Synonym Group" form issue23953

### LINKED ISSUE #23953: "Merge On Conflict" missing the Label in "New Synonym Group" form
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go Marketing -> Search Synonyms -> New Synonym Group
2. Check the form

image

### Expected result (*)

1. Has the label

### Actual result (*)

1. No Label (User can not understand, must hover on ? to read) => BAD UX

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#23953: "Merge On Conflict" missing the Label in "New Synonym Group" form

Solution: Just add:

` <description translate="true">Merge existing synonyms</description>`

### Fixed Issues (if relevant)

1. magento/magento2#23953: "Merge On Conflict" missing the Label in "New Synonym Group" form

### Manual testing scenarios (*)

1. Go Marketing -> Search Synonyms -> New Synonym Group
2. Check the form
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5531](https://jira.corp.magento.com/browse/ENGCOM-5531) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @edenduong , @VladimirZaets !

I'm not sure this is the right solution.

According to Magento documentation [(Search Synonyms)](https://docs.magento.com/m2/ce/user_guide/marketing/search-synonyms.html) this checkbox label has a different name then in this PR and the label are located on the right side of the checkbox.

@VladimirZaets Could you take a look?

Thanks!

**Comment by edenduong** [comment]
@engcom-Alfa : Thank you for your reply. I will recheck it.

**Comment by edenduong** [comment]
@engcom-Alfa: I have changed the source code. You can check it again.
@VladimirZaets: Please review my new changes.

Thanks.

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-23954.instances.magento-community.engineering).
Admin access: [https://pr-23954.instances.magento-community.engineering/admin](https://pr-23954.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by edenduong** [comment]
@VladimirZaets: Could you please take a look again? Thanks

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5531](https://jira.corp.magento.com/browse/ENGCOM-5531) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by edenduong** [comment]
Could I receive “bug fixed award” :) It has description in the document but it losses so It is really a bug.

**Comment by edenduong** [comment]
@sidolov : Could I receive the "Bugfix award" for this PR? Thank you :)

**Pull request merged**
