### PR TITLE
[MFTF] Remove redundant Index and Flush Cache action group

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR removes reduntand ActionGroup `app/code/Magento/Indexer/Test/Mftf/ActionGroup/IndexerActionGroup/AdminReindexAndFlushCacheActionGroup.xml`
because we already have similar 
`app/code/Magento/Indexer/Test/Mftf/ActionGroup/AdminReindexAndFlushCacheActionGroup.xml`

### CODE REVIEW

**Review by lbajsarowicz — APPROVED** [review]
Thank you for removal of that.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7405](https://jira.corp.magento.com/browse/ENGCOM-7405) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Pull request merged**
