### PR TITLE
Fix wrong format error DHL shipping label

### LINKED ISSUE #31032: [Issue] Fix wrong format error DHL shipping label
This issue is automatically created based on existing pull request: magento/magento2#31021: Fix wrong format error DHL shipping label

---------
Fix "The response is in wrong format." error while generating dhl shipping label. When product name has unicode characters substr() is sending � in <PieceContents> causing erros dhl syntax errors.

### Description (*)
DHL shipping.log produces error "Error in parsing request XML:The element type "PieceContents" must be terminated by the matching end-tag "&lt;/PieceContents&gt;"."

This is caused in our use case by substr() not supporting multibyte characters in product name.

### Preconditions
1. Magento 2.4-develop
2. Magento DHL settings and Store Settings set for USA address
3. A Customer with a valid United Kingdom address 

### Steps to reproduce (*)

1. create a product with product name "Φυστίκι Ψημένο με Αλάτι Συσκευασία"
2. place an order with dhl shipping method (having debug mode will help trace dhl error response)
3. try to ship order with "create shipping label" checkbox checked
4. while requesting label creation you get "The response is in wrong format."

### Expected result
Shipping Label should be created

### Actual Result
"The response format is wrong" error message appears
wrong_format

### Note from Engcom :exclamation: 
We are able to get the error message with a product named _Product_

### PR DESCRIPTION
**Pull request by vpsnak**
Fix "The response is in wrong format." error while generating dhl shipping label. When product name has unicode characters substr() is sending � in <PieceContents> causing erros dhl syntax errors.

### Description (*)

DHL shipping.log produces error "Error in parsing request XML:The element type "PieceContents" must be terminated by the matching end-tag "&lt;/PieceContents&gt;"."

This is caused in our use case by substr() not supporting multibyte characters in product name.

### Manual testing scenarios (*)

1. create a product with product name "Φυστίκι Ψημένο με Αλάτι Συσκευασία"
2. place an order with dhl shipping method (having debug mode will help trace dhl error response)
3. try to ship order with "create shipping label" checkbox checked
4. while requesting label creation you get "The response is in wrong format."

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31032: Fix wrong format error DHL shipping label

### CODE REVIEW

**Comment by vpsnak** [comment]
@magento run all tests

**Comment by vpsnak** [comment]
@magento Static Tests,Functional Tests B2B,Functional Tests EE,Integration Tests

**Comment by vpsnak** [comment]
@magento run Static Tests,Functional Tests B2B,Functional Tests EE,Integration Tests

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @vpsnak. Thank you for your collaboration. According to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered by auto-tests. Could I ask you to cover this case with an integration test, please? Feel free to extend the [existing test](https://github.com/magento/magento2/blob/60d26960f8c8c968a253b65e7ad8b4224d9536cf/dev/tests/integration/testsuite/Magento/Dhl/Model/CarrierTest.php#L28) for that. 

Thank you!

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by engcom-Hotel** [comment]
Hello @vpsnak.
I will check failing tests, could you please cover your changes according to recommendations from
https://github.com/magento/magento2/pull/31021#pullrequestreview-537533449

**Comment by vpsnak** [comment]
@engcom-Hotel @rogyar i have never made an Automated test, i am searching on how to cover this issue with a test case because its a tricky situation. I have to test _shipmentDetails in order to test the difference between substr(implode(',', $content), 0, 34) and  $this->string->substr(implode(',', $content), 0, 34) on line 1751? Or can i make a test just passing the same string to both and test the result?

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE, Integration Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE, Integration Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
> @engcom-Hotel @rogyar i have never made an Automated test, i am searching on how to cover this issue with a test case because its a tricky situation. I have to test _shipmentDetails in order to test the difference between substr(implode(',', $content), 0, 34) and $this->string->substr(implode(',', $content), 0, 34) on line 1751? Or can i make a test just passing the same string to both and test the result?

Let me help you with the test of the changes.

**Comment by engcom-Charlie** [comment]
@vpsnak I will continue with your PR.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8537](https://jira.corp.magento.com/browse/ENGCOM-8537) has been created to process this Pull Request
:eight_spoked_asterisk: @rogyar, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@vpsnak thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

### Case 1.  
**_With product name "Φυστίκι Ψημένο με Αλάτι Συσκευασία"_**

1. Create a product with product name "Φυστίκι Ψημένο με Αλάτι Συσκευασία";
2. Place an order with dhl shipping method;
3. Try to ship order with "create shipping label" checkbox checked
    

**Before:** :x: while requesting label creation we get "The response is in wrong format."

:heavy_multiplication_x:  With _**Documents**_ type
Screenshot from 2020-12-14 16-03-20

:heavy_multiplication_x: With _**Non Documents**_ type
Screenshot from 2020-12-15 15-33-46

**After:** :heavy_check_mark:  The shipment has been created

:heavy_check_mark: With _**Documents**_ and _**Non Documents**_ types

Screenshot from 2020-12-15 15-26-12

### Case 2.  
**_With  product name "Simple 1"_**

1. Create a product with product name "Simple 1";
2. Place an order with dhl shipping method;
3. Try to ship order with "create shipping label" checkbox checked
    

**Before:** :x: while requesting label creation we get "The response is in wrong format."

:heavy_multiplication_x:  With _**Documents**_ type
Screenshot from 2020-12-15 15-38-02


:heavy_check_mark: With _**Non Documents**_ type
Screenshot from 2020-12-15 15-38-20


**After:** :heavy_check_mark:  The shipment has been created

:heavy_check_mark: With _**Documents**_ and _**Non Documents**_ types

Screenshot from 2020-12-15 15-44-36

**Pull request merged**
