### PR TITLE
Update insert.js

### LINKED ISSUE #30361: An empty window opens after the second click of the "Add Attribute" button
### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Go to Catalog -> Products -> Add New Product
2. Click on the "Add Attribute" button (Upper right corner)
3. Click on the "Create New Attribute" button
4. Close the opened window
5. Click on the "Create New Attribute" button again

### Expected result (*)

The "New Attribute" window opened (as on the 4 step)

### Actual result (*)

Empty window opened with title. Error in console:

Peek 2020-10-07 14-49

```
Uncaught TypeError: value.split is not a function
    at insert.js:204
    at Function._.each._.forEach (underscore.js:150)
    at UiClass.filterExternalLinks (insert.js:203)
    at UiClass.initExternalLinks (insert.js:178)
    at UiClass.destroyInserted (insert.js:166)
    at UiClass._super (wrapper.js:106)
    at UiClass.destroyInserted (insert-form.js:106)
    at UiClass.destroyInserted (wrapper.js:109)
    at registry.js:58
    at Registry._resolveRequest (registry.js:417)
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by ashvin0009**
#30361 :  Fixed an empty window opens after the second click of the "Add Attribute" button

### Description
Fixes #30361 - an empty window opens after the second click of the "Add Attribute" button

### Fixed Issues

1. Fixes magento/magento2#<30361>

### Manual testing scenarios

1. Go to Catalog -> Products -> Add New Product
2. Click on the "Add Attribute" button (Upper right corner)
3. Click on the "Create New Attribute" button
4. Close the opened window
5. Click on the "Create New Attribute" button again
6. The blank window doesn't show up and there is no error in dev console. Add attribute feature is also working fine.

### Contribution checklist (*)
 - [Y] Pull request has a meaningful description of its purpose
 - [Y] All commits are accompanied by meaningful commit messages
 - [Y] All new or changed code is covered with unit/integration tests (if applicable)
 - [Y] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ashvin0009** [comment]
@magento run all tests.

**Comment by ashvin0009** [comment]
@magento run all tests

**Comment by rodrigowebjump** [comment]
@magento give me test instance

**Comment by sivaschenko** [comment]
#dmcdindia2020

**Comment by rogyar** [comment]
Hi @ashvin0009. Thank you for your contribution. The following case seems to be already covered by the following PR 

https://github.com/magento/magento2/pull/30400

Since the mentioned PR has been created earlier, I have to mark this one as a duplicate. In case if author of the mentioned PR will not proceed working on the PR, you may continue with your PR. 

Thank you.

**Comment by ihor-sviziev** [comment]
Hi @ashvin0009,
Thank you so much for your contribution!
Unfortunately, I see that we already have merged PR that fixes the same issue https://github.com/magento/magento2/pull/30400.
I'm closing this PR as not relevant anymore.

**Pull request closed without merging**
