### PR TITLE
#22047: Magento CRON Job Names are missing in NewRelic: Transactions FIX

### PR DESCRIPTION
**Pull request by PiotrSiejczuk**
### Description (*)

Magento CRON Job Names are missing in NewRelic: Transactions Names - This Pull Request Fixes it as per Detailed Description below

### Fixed Issues (if relevant)

1. magento/magento2#22047: Magento CRON Job Names are missing in NewRelic: "Transaction Names"

### Manual testing scenarios (*)

1. Running Magento 2.3.x
2. Correctly Configured CRON Jobs
3. Schedule Cron Job Execution
4. Wait for any Cron Job Execution
5. See Cron Jobs Executed with proper Transaction Names in NewRelic Transaction traces:

NewRelic-UnknownTraces-ExpectedResult

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22061) <br/>All committers have signed the CLA.

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @PiotrSiejczuk , thanks for the pull request!

`Magento_Cron` module should not be aware of New Relic, can you please move the implementation to `Magento_NewRelicReporting` module.

Also, please avoid adding static functions and ensure method/constant/properties visibility is set to `private` where possible

**Comment by PiotrSiejczuk** [comment]
@sivaschenko thank you for your feedback. I have discussed this topic together with @lbajsarowicz. The idea is that he is going to extend his changes within: PR: https://github.com/magento/magento2/pull/22059 to incorporate mine by doing that within NewRelic_Reporting Module

If for some reason that is not going to happen I will refactor my PR to improve logic and quality of the proposed changes

**Comment by sidolov** [comment]
Hi @PiotrSiejczuk , I'm closing this PR since https://github.com/magento/magento2/pull/22059 was merged recently. 
Thank you for your contribution!

**Comment by PiotrSiejczuk** [comment]
Hi @sidolov, thank you for your information. Although commits from @lbajsarowicz are not addressing the whole scope of the reported issue. It is perfect that CLI CRON commands are being correctly Tracked @ NewRelic now. Although it is not tracking correctly ATOMIC Transactions executed within standard CRON execution. That being said: this ticket should not be CLOSED as the FIX is not addressing the whole scope of the ISSUE described initially

**Pull request closed without merging**
