### PR TITLE
MC-37385: Unexpected unchecking of "Append Comments" check-box

### LINKED ISSUE #30256: Unexpected unchecking of "Append Comments" check-box
Preconditions
1. Create simple product  

1. Create Customer with address
* First Name: John
* Last Name: Doe
* Email Address: john.doe@example.com(use real mail)
* Company: Magento
* Address: 6161 West Centinela Avenue
* City: Culver City
* State/Province: California (CA)
* Zip/Postal Code: 90230
* Country: United States
* Telephone: 555-55-555-55
 

Steps:
1. Go to admin -> sales -order -> create new order -> select customer
* Add Products => simple product
* add comments in Order Comments textarea
* Append Comments => yes
* Email Order Confirmation => yes
* click Get shipping methods and rates -> select shipping method 

(/) Expected result
"Append Comments" check-box should be checked

(x) Actual result
"Append Comments" check-box is unchecked

### PR DESCRIPTION
**Pull request by SmVladyslav**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#30256 (MC-37385)

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by SmVladyslav** [comment]
@magento run all tests

**Comment by SmVladyslav** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Integration Tests, Static Tests, WebAPI Tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8578](https://jira.corp.magento.com/browse/ENGCOM-8578) has been created to process this Pull Request

**Comment by SmVladyslav** [comment]
@magento run Functional Tests B2B

**Comment by SmVladyslav** [comment]
@magento run Static Tests

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Before:**
:x: "Append Comments" check-box is not checked when shipping method is selected
Peek 2020-12-24 11-31


**After:**
:heavy_check_mark: "Append Comments" check-box is checked when shipping method is selected
Peek 2020-12-24 14-40

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Review by engcom-Kilo — APPROVED** [review]

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Result in [comment](https://github.com/magento/magento2/pull/31422#issuecomment-750872603)

Automation tests are passed

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31422`.

**Pull request merged**
