### PR TITLE
Fix incorrect row totals in invoice email

### LINKED ISSUE #32307: Invoice confirmation email showing incorrect row totals when partially cancelled
Invoice confirmation email showing incorrect row totals when partially cancelled as it displays amounts from order item, not from invoice item.

### Preconditions (*)

1. Magento Commerce 2.4.1
2. PHP 7.4.15

### Steps to reproduce (*)

1. Add few products to the cart with multiple qty
2. Proceed to checkout and complete the order
3. Invoice the order for partial qty in backend
4. Ship the same qtys as per invoice
5. Cancel the rest of order
6. (optional) Go to invoice view in the backend and click "Send Email" if automatic emails are disabled

### Expected result (*)

1. Invoice email received displays correct invoiced row totals for invoiced qty (e.g. as in Magento backend)

### Actual result (*)

1. Invoice email displays incorrect invoiced row totals

### PR DESCRIPTION
**Pull request by denis-zyk**
### Description (*)

Invoice confirmation email showing incorrect row totals when partially cancelled as it displays amounts from order item, not from invoice item.

### Fixed Issues

1. Fixes magento/magento2#32307

### Manual testing scenarios (*)

1. Add few products to the cart with multiple qty
2. Proceed to checkout and complete the order
3. Invoice the order for partial qty in backend
4. Ship the same qtys as per invoice
5. Cancel the rest of order
6. (optional) Go to invoice view in the backend and click "Send Email" if automatic emails are disabled
7. Check whether invoice email received contains correct row totals

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by denis-zyk** [comment]
@magento run all tests

**Comment by Stepa4man** [comment]
@magento run all tests

**Comment by chrom** [comment]
@magento give me 2.4-develop instance

**Comment by Stepa4man** [comment]
@engcom-Alfa 
@engcom-Bravo 
@engcom-Charlie 
@engcom-Dash 
@engcom-Delta 
@sivaschenko
@gabrieldagama 
Please, take into account, this is not the first PR with failed static tests (end many others) where tests failed or checked files that weren't even changed.

Can somebody update me if we have any problems with tests now? 
Thanks.

**Comment by chrom** [comment]
@magento give me 2.4-develop instance

**Comment by gabrieldagama** [comment]
Hi @Stepa4man, yes these failures are happening on mainline as well, it shouldn't be related to this PR, please proceed as usual. An internal team is working on solving this problem.

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
As per this comment https://github.com/magento/magento2/issues/32307#issuecomment-797408348 this issue is likely fixed on 2.4.2, closing this PR for now. If this still relevant, please feel free to reopen it!

**Pull request closed without merging**
