### PR TITLE
Apply coupoun and scroll top to check. applied successfully or not

### PR DESCRIPTION
**Pull request by krnshah**
### Description (*)

If we are applying the coupon code from the admin while create order and click on "Apply coupon code" it not showing error/success msg, we have to scroll up to check the msg.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: N/A

### Manual testing scenarios (*)

1. Admin >> Sales >> Orders
2. Create a New Order
3. Add Products
4. Coupon code >> Enter invalid coupon
5. Click on Apply button

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by orlangur** [comment]
@krnshah first of all, please do not ping reviewers without prior agreement. Secondly, please report an issue so that it can be verified and then add a link to description.

**Review by sidolov — CHANGES_REQUESTED** [review]
Please, create the issue for current pull request or extend description with detailed steps to reproduce, actual and expected result. These steps can help us better understand provided fix. 
Thank you!

**Comment by sidolov** [comment]
@krnshah , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by krnshah** [comment]
I have added the description. please let me know if any information needed.

**Comment by davidverholen** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @davidverholen. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @davidverholen, here is your [new Magento instance](https://pr-22341.instances.magento-community.engineering).
Admin access: [https://pr-22341.instances.magento-community.engineering/admin](https://pr-22341.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by davidverholen** [comment]
@sidolov the change is basically working, so I'd approve it.
There might be better solutions from an ux perspective I guess, but this should probably be solved globally and not be discussed here

**Review by davidverholen — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @davidverholen, thank you for the review.
[ENGCOM-5212](https://jira.corp.magento.com/browse/ENGCOM-5212) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed 

**Before:**

before

**After:**

after

**Pull request merged**
