### PR TITLE
Bugfix for regions with single quote in name

### PR DESCRIPTION
**Pull request by ddonnini**
Before this bugfix, changing the country of a customer address
use to generate a jQuery exception that breaks the options
population if a region of that country has a name containg
one of the css meta-characters.
For example, selecting France the option Côtes-d'Armor breaks
jQuery.

### CODE REVIEW

**Comment by lanken** [comment]
It's bad practice to change default flow of existing tests. Additionally in current case you overwrite France address at once without saving it.

The best way is to test customer with specific address separately.
The only changes you need to perform for this is to add one more variation to UpdateCustomerFrontendEntity test in https://github.com/magento/magento2/blob/develop/dev/tests/functional/tests/app/Magento/Customer/Test/TestCase/UpdateCustomerFrontendEntity/test.csv
```
"description";"customer/data/firstname";"customer/data/lastname";"customer/data/email";"address/data/firstname";"address/data/lastname";"address/data/company";"address/data/street";"address/data/city";"address/data/country_id";"address/data/region_id";"address/data/region";"address/data/telephone";"address/data/fax";"address/data/postcode";"constraint"
"Update customer information and add US address";"Jany %isolation%";"Doe %isolation%";"janydoe%isolation%@example.com";"Jany %isolation%";"Doe %isolation%";"Company %isolation%";"Some street %isolation%";"City %isolation%";"United States";"Colorado";"-";"555-888-111-999";"161-999-8888";"12345";"assertCustomerAddressSuccessSaveMessage, assertCustomerDefaultAddresses"
"Update customer information and add UK address";"Jonny %isolation%";"Doe %isolation%";"jonny%isolation%@example.com";"John %isolation%";"Doe %isolation%";"Company %isolation%";"Some street %isolation%";"City %isolation%";"United Kingdom";"-";"Region %isolation%";"0123456789-02134567";"5555-874-99634";"12345";"assertCustomerAddressSuccessSaveMessage, assertCustomerDefaultAddresses"
"Update customer information and add France address";"-";"-";"-";"Jean";"Reno";"Magento %isolation%";"18-20 Rue Maréchal Leclerc";"Quintin";"France";"Côtes-d'Armor";"-";"333-33-333-33";"-";"22800";"assertCustomerAddressSuccessSaveMessage, assertCustomerDefaultAddresses"
```

You should also slightly change \Magento\Customer\Test\Block\Form\CustomerForm::fill() (this changes hasn't been delivered to mainline yet)
```
    public function fill(FixtureInterface $customer, Element $element = null)
    {
        /** @var CustomerInjectable $customer */
        if ($customer->hasData()) {
            return parent::fill($customer, $element);
        }
    }
```

**Comment by ddonnini** [comment]
Cool, thanks, I'll change it as soon as possible

**Comment by ddonnini** [comment]
@lanken is it better now?
Thanks again.

**Comment by lanken** [comment]
Yes, it's much better. The main idea is right, but could you, please, revert changes in
- application.yml.dist
- install_data.yml.dist
- phpunit.xml.dist
It's better to use not dist files, in such way you wouldn't commit them by mistake.

Also, revert changes in dev/tests/functional/tests/app/Magento/Customer/Test/Repository/Address.php as you deleted getAddressFR() method.

In file dev/tests/functional/tests/app/Magento/Customer/Test/TestCase/UpdateCustomerFrontendEntity/test.csv you should only add additional line, but don't delete existing ones.

**Comment by ddonnini** [comment]
Maybe it's quite necessary a new pull request when everything is ok, without all my mistakes, what do you think?

**Comment by vpelipenko** [comment]
Probably you can force push the source branch and leave there only one commit with correct fixes, it is not necessary to create new pull request.

**Comment by Vinai** [comment]
You might find this useful regardign squashing commits: http://stackoverflow.com/a/5201642/485589

**Comment by ddonnini** [comment]
Voillà, thanks to all!

**Comment by vpelipenko** [comment]
CR: passed
Builds: green
Resolution: OK to merge
Ticket: MAGETWO-32688

**Pull request merged**
