### PR TITLE
Fix URL path of Sourcemap(.map) files

### LINKED ISSUE #37290: [Issue] Fix URL path of Sourcemap(.map) files
This issue is automatically created based on existing pull request: magento/magento2#28415: Fix URL path of Sourcemap(.map) files

---------

### Description (*)

Verified the problem and fix on Magento 2.4.5-p1 and 2.4-develop. The problem doesn't exist on Magento 2.3.7-p4 so probably one of the recent changes in 2.4.x to the grunt code or one of the updated npm packages causes the problem.

Steps to reproduce:
1. Setup clean Magento
2. Copy `package.json.sample` to `package.json`
3. Run `npm install`
4. Run `cp Gruntfile.js.sample Gruntfile.js`
5. Run `grunt exec:luma`
6. Run `grunt less:luma`
7. Run: `grep -r 'sourceMappingURL' pub/static` and notice this output:
```
$ grep -r 'sourceMappingURL' pub/static
pub/static/frontend/Magento/luma/en_US/css/styles-l.css:/*# sourceMappingURL=pub/static/frontend/Magento/luma/en_US/css/styles-l.css.map */
pub/static/frontend/Magento/luma/en_US/css/styles-m.css:/*# sourceMappingURL=pub/static/frontend/Magento/luma/en_US/css/styles-m.css.map */
```
Which are incorrect paths to the sourcemap files, the browser tries to load these incorrectly resulting in 404 errors and doesn't find the original less files in the inspector:
Screenshot 2023-01-05 at 13 45 50
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by tshabatyn**
### Fixed Issues (if relevant)

1. [x] resolves magento/magento2#37290: Fix URL path of Sourcemap(.map) files

### Manual testing scenarios (*)

Verified the problem and fix on Magento 2.4.5-p1 and 2.4-develop. The problem doesn't exist on Magento 2.3.7-p4 so probably one of the recent changes in 2.4.x to the grunt code or one of the updated npm packages causes the problem.

Steps to reproduce:
1. Setup clean Magento
2. Copy `package.json.sample` to `package.json`
3. Run `npm install`
4. Run `cp Gruntfile.js.sample Gruntfile.js`
5. Run `grunt exec:luma`
6. Run `grunt less:luma`
7. Run: `grep -r 'sourceMappingURL' pub/static` and notice this output:
```
$ grep -r 'sourceMappingURL' pub/static
pub/static/frontend/Magento/luma/en_US/css/styles-l.css:/*# sourceMappingURL=pub/static/frontend/Magento/luma/en_US/css/styles-l.css.map */
pub/static/frontend/Magento/luma/en_US/css/styles-m.css:/*# sourceMappingURL=pub/static/frontend/Magento/luma/en_US/css/styles-m.css.map */
```
Which are incorrect paths to the sourcemap files, the browser tries to load these incorrectly resulting in 404 errors and doesn't find the original less files in the inspector:
Screenshot 2023-01-05 at 13 45 50

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37290: Fix URL path of Sourcemap(.map) files

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@tshabatyn could you add some issue description and how you're going to fix it?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@tshabatyn  unfortunately it's really hard to understand what the issue you have, how to test it and not clear if your fix is correct.
Could you add some issue description and how you're going to fix it?

**Comment by ihor-sviziev** [comment]
@tshabatyn  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by hostep** [comment]
Hey @ihor-sviziev!
Can we have this PR re-opened? It's a really good one and actually fixes the path to the sourcemaps generated by the less compiler.

Steps to reproduce:
1. Setup clean Magento
2. Copy `package.json.sample` to `package.json`
3. Run `npm install`
4. Run `grunt exec:luma`
5. Run `grunt less:luma`
6. Run: `grep -r 'sourceMappingURL' pub/static` and notice this output:
```
$ grep -r 'sourceMappingURL' pub/static
pub/static/frontend/Magento/luma/en_US/css/styles-l.css:/*# sourceMappingURL=pub/static/frontend/Magento/luma/en_US/css/styles-l.css.map */
pub/static/frontend/Magento/luma/en_US/css/styles-m.css:/*# sourceMappingURL=pub/static/frontend/Magento/luma/en_US/css/styles-m.css.map */
```
Which are incorrect paths to the sourcemap files, the browser tries to load these incorrectly resulting in 404 errors and doesn't find the original less files in the inspector:
Screenshot 2023-01-05 at 13 45 50


7. Apply the fix from this PR
8. Run `grunt less:luma` again
9. Run `grep -r 'sourceMappingURL' pub/static` again and notice correct relative paths are generated:
```
$ grep -r 'sourceMappingURL' pub/static
pub/static/frontend/Magento/luma/en_US/css/styles-l.css:/*# sourceMappingURL=styles-l.css.map */
pub/static/frontend/Magento/luma/en_US/css/styles-m.css:/*# sourceMappingURL=styles-m.css.map */
```
Also, the sourcemap files are now loaded in the browser and the inspector finds the less files where the code originally came from:
Screenshot 2023-01-05 at 13 47 16


Thanks for this fix @tshabatyn!

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by joshuaswarren** [comment]
Hello, @ihor-sviziev - I'm going through some of the oldest open pull requests on the Magento 2 repository to better understand why they are still open, if they ought to be closed, etc. 

On this one, I noticed that it's marked as changes requested and links back to a comment you made in 2020 - https://github.com/magento/magento2/pull/28415#pullrequestreview-420885739

At least to my admittedly untrained eye, @hostep's comment in https://github.com/magento/magento2/pull/28415#issuecomment-1372180105 seems like it clarifies what @tshabatyn was solving in this pull request. Is there additional info still needed, and if so, what might it be? 

Thanks for helping me understand this! Through my position at the Magento Association, I'm on a crusade to get more community innovations merged smoothly into the Magento codebase and understanding these oldest pull requests can really help me determine the best way to apply our efforts.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

1. Followed steps given in the [comment](https://github.com/magento/magento2/pull/28415#issuecomment-1372180105) and [document](https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/css-topics/css_debug.html).

**Before:** :heavy_multiplication_x: Path was wrong.
Screenshot 2023-04-13 at 3 48 09 PM
Screenshot 2023-04-13 at 3 49 36 PM


**After:** :heavy_check_mark:  Now correct
Screenshot 2023-04-13 at 3 52 44 PM
Screenshot 2023-04-13 at 3 50 53 PM

**Pull request merged**
