### PR TITLE
Fix setting addresstype in case it is not set yet

### PR DESCRIPTION
**Pull request by c-walter**
### Description (*)

With Magento 2.3.3 the mail-sending was changed, with that change you are not able to add recipients in an array to the transport-builder.
When adding recipients as array the "to" part in messageData is not set. You have to add the reciepents in a loop or, add one recipient so that `if (isset($this->messageData[$addressType]))` returns true in order to add the rest as array.

### Manual testing scenarios (*)

1. create an instance of \Magento\Framework\Mail\Template\TransportBuilder
2. set template, template options, template vars, add recipients as array using "addTo"
3. try to send message
4. result: an error occurs because "to" is not set

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by VladimirZaets** [comment]
Hi @c-walter  , please, sign CLA, otherwise, we can't process your pull request

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @c-walter , please, sign CLA, otherwise, we can't process your pull request

**Comment by c-walter** [comment]
@VladimirZaets thanks for the information. CLA is signed now

**Comment by VladimirZaets** [comment]
Hi @c-walter. Thanks for collaboration. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

**Comment by engcom-Golf** [comment]
I will take care f test coverage

**Comment by engcom-Golf** [comment]
Hi @c-walter thank you for you contribution, fix already in 2.4-develop
DeepinScreenshot_select-area_20200204160706

**Pull request closed without merging**
