### PR TITLE
Removed CliCacheFlushActionGroup usage for Catalog module

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Removed CliCacheFlushActionGroup usage for Catalog module

### Fixed Issues
#31902

### CODE REVIEW

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B,Semantic Version Checker

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run WebAPI Tests, Unit Tests, Static Tests, Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B, Magento Health Index, Integration Tests, Database Compare

**Comment by sergiy-v** [comment]
Hello @eduard13, all tests are green, please proceed with review.

**Review by eduard13 — APPROVED** [review]
Good job 👍

**Comment by engcom-Bravo** [comment]
Manual QA not applicable. Moving this PR to _Extended Testing_ column

**Pull request merged**
