### PR TITLE
Change GA4 purchase event data values to numbers

### PR DESCRIPTION
**Pull request by lumnn**
### Description (*)

GA4 purchase event requires certain values (order total, tax, delivery cost, product prices) to be numbers. Existing implementation uses `number_format` function that in some locales adds commas to numbers (1000 -> "1,000"), which makes it an incorrect for GA4.

### Fixed Issues (if relevant)

1. Fixes magento/magento2##37708

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by DannyDaemonic** [comment]
Seems to work and the logic is sound. Currently using this in production.

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @lumnn,

Thanks for the contribution!

There seem some conflicts in the PR, please resolve them. It might be possible the related issue has already been fixed and merged with the 2.4-develop branch.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @lumnn,

Meanwhile, we are moving this issue `On Hold`.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @lumnn,

We had a discussion internally on this PR and as the actual issue is already been addressed and fixed in 2.4-develop branch. We can close this PR.

But thanks for the contribution.

**Pull request closed without merging**
