### PR TITLE
Fix extra white space at mobile modal view

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Rework at modal component. Add some code update for modal at mobile view

Before fix 
evidence-before-fix
After fix
evidence-after-fix

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@mrtuvn is something there you wanted to improve?

**Comment by mrtuvn** [comment]
reduce extra spacing purposes only instead increase height overall of modal

**Comment by mrtuvn** [comment]
default modal styles will have fullsize in mobile
https://i.imgur.com/vYYrkld.png (modal size fullsize screen + content small)
but in my opinion it's should show correct size content it's should show based on content. Specially when you have small/little content
https://i.imgur.com/ftD0fM0.png (modal size show with correct content)

**Comment by mrtuvn** [comment]
closed it's in my opinion it's not looks like a issue

**Pull request closed without merging**
