### PR TITLE
Store view specific label text field not clear when click on reset issue 23991

### LINKED ISSUE #23991: Store view specific label text field not clear when click on reset
### Preconditions (*)

1. Magento 2.3
2.

### Steps to reproduce (*)

1. Go to Admin
2. Marketing -> Cart Price Rule
3. Fill all the fields
4. Click on Reset
5. Review the Store View Specific Labels -> Default Store View field

### Expected result (*)

1. All the fields should clear when click on Reset.

### Actual result (*)

1. "Store View Specific Labels" still has value
2. https://www.screencast.com/t/bznJ2QGK
Peek 2020-08-05 16-30

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#23991: Store view specific label text field not clear when click on reset

Problem: Reset button has the onclick = location.reload(). But it can not run. Because of form.js also observer the click of reset button to reset, but it only reset the field which rendered by UI Component. Some fields of Cart Price Rule form are not the UI Components => can not reset

Solution: just change the id for reset button to "reset_button" id => the  onclick = location.reload() can run.

### Fixed Issues (if relevant)

1. magento/magento2#23991: Store view specific label text field not clear when click on reset

### Manual testing scenarios (*)

1. Go to Admin
2. Marketing -> Cart Price Rule
3. Fill all the fields
4. Click on Reset
5. Review the Store View Specific Labels -> Default Store View field
=> All the fields should clear when click on Reset.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by kalpmehta** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, here is your [Magento instance](https://i-23994-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23994-2-3-develop.instances.magento-community.engineering/admin](https://i-23994-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by kalpmehta — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, thank you for the review.
[ENGCOM-5542](https://jira.corp.magento.com/browse/ENGCOM-5542) has been created to process this Pull Request
:eight_spoked_asterisk: @kalpmehta, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @edenduong !

I'm not sure about the correct behavior with PR changes. 
The page should not be overloaded when the "Reset" button is pressed.

**Actual Result:**
after

@kalpmehta, @edenduong  Could you take a look, please?

Thanks!

**Comment by edenduong** [comment]
@engcom-Alfa: Thank you for your feedback. I see it and I write it in the description of this PR.  Because when it doesn't reload,  it can not clear some field on the page. ( some fields of the form is not the UI- Component, it uses the old "Block" form. The current code only reset the UI-component) 

Now, it has two place (two code block) to reset:
- 1: Reload the page (now it is inactive - because it is overrided by code 2)
- 2: No reload, but reset only the UI Component. it is now active. Some fields aren't UI-component so it can not run correctly.

So I think we shoud reload page. Some page of Magento also do that. Please see :
-New Tax Rate
-New Tax Rule
...
and other page use the old "Block" form.

**Comment by engcom-Alfa** [comment]
@VladimirZaets Is this the right behavior?
Could you take a look, please?

**Review by sidolov — CHANGES_REQUESTED** [review]
@edenduong I believe it's the same issue as in https://github.com/magento/magento2/pull/23997#pullrequestreview-275025745

**Comment by edenduong** [comment]
> @edenduong I believe it's the same issue as in [#23997 (review)](https://github.com/magento/magento2/pull/23997#pullrequestreview-275025745)

@sidolov : Yes. It is the same issue but it is for Cart Price Rule. It need to fix similar Catalog Rule.
As I answer in this PR:
https://github.com/magento/magento2/pull/23997
We don't know the structure of HTML code like that:

image

So it is impossible to reset the HTML tag if we don't know the HTML structure. Reload Page is the simple and better solution.

**Comment by sidolov** [comment]
@edenduong it's weird to duplicate browser refresh button for the form reset purpose, everyone can reload the page. If we can't properly reset the form, maybe it would be better to eliminate the reset button at all? @piotrekkaminski what do you think?

**Pull request closed without merging**
