### PR TITLE
refs #2412 fixed permissions.

### PR DESCRIPTION
**Pull request by clwells**
Per the discussion on #2412 here is our proposed solution.

### CODE REVIEW

**Comment by astorm** [comment]
Are there setup instructions anywhere for running systems using Apache `mod_php`, or a statement that `mod_php` systems aren't supported?  Without those it's impossible to comment on this solution.

**Comment by clwells** [comment]
mod_php can supported (although I don't recommend it).  I'll get some instructions attached here to clarify.

Chris

**Comment by astorm** [comment]
@clwells appreciated, as that's how many many many folks are running Magento 1 right now, but I'm more looking for an official position from Magento Inc. on this one.  They control the platform architecture, they should be able to lay out how this is supposed to work.   If we're out here coming up with workarounds for mod_php that the Magento engineering team isn't officially supporting that's a recipe for breaking things in the future.   I don't think it's too much to ask for an official position from the platform owners on this.

**Comment by clwells** [comment]
@astorm - 100% agreed.

**Comment by Andres-Botero** [comment]
Thanks @clwells

**Comment by dsikkema-magento** [comment]
@clwells one possible concern could be, if only owner has write access, all the time, then php-user should always be the owner, and therefore php-user could always have write access and that could be undesirable for security. What do you think?

**Comment by clwells** [comment]
@dsikkema - This is desirable actually.  You own the file, PHP runs as you, you can read/write the file.  This doesn't work in mod_php land but in spots where FPM is set up to run as you it's desirable.

**Comment by ghost** [comment]
Opened internal task item MAGETWO-56715

**Comment by vkublytskyi** [comment]
Close this PR as since 2.0.6 Magento does not set file permissions directly. For more details, see Magento file system ownership and permissions:
- http://devdocs.magento.com/guides/v2.1/install-gde/prereq/file-sys-perms-over.html
- http://devdocs.magento.com/guides/v2.1/install-gde/install/post-install-umask.html

**Pull request closed without merging**
