### PR TITLE
Frontend customer account order list

### LINKED ISSUE #28488: [Issue] Frontend customer account order list
This issue is automatically created based on existing pull request: magento/magento2#28417: Frontend customer account order list

---------

### Description (*)

Fixed frontend customer account list issue, covered by test

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Preconditions:
magento 2.4-develop

### Steps to reproduce

1) Create 1 category and 1 simple product;
2) Create a customer on Frontend and login him to Frontend;
3) Create the same 11 orders with 1 simple product from step 2;
4) Go to “My Account”->"My Orders";
6) Click page 2 to display the 11th order on the orders grid;
7) Select `Show=20` per page from the drop-down menu.

### Actual Result:
“You have placed no orders” message is displayed

Peek 2020-06-03 12-42

### Expected Result:
All 11 orders are displayed on 1 page.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by engcom-Charlie**
### Description (*)

Fixed frontend customer account list issue, covered by test

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1) Install Magento 2.4-develop CE+EE branch.
2) Create 1 category and 1 simple product.
3) Create customer on Frontend and log in him to Frontend.
4) Create the same 11 orders with 1 simple product from step 2.
5) Go to “My Account”.
6) Go to “My Orders”.
7) Click page 2 to display 11th order on orders grid.
8) Select Show=20 per page drop-down.

### Actual Result:
“You have placed no orders” message is displayed:
### Expected Result:
All 11 orders are displayed on 1 page.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28488: Frontend customer account order list

### CODE REVIEW

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7610](https://jira.corp.magento.com/browse/ENGCOM-7610) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1) Create 1 category and 1 simple product;
2) Create a customer on Frontend and login him to Frontend;
3) Create the same 11 orders with 1 simple product from step 2;
4) Go to “My Account”->"My Orders";
6) Click page 2 to display the 11th order on the orders grid;
7) Select `Show=20` per page from the drop-down menu.

**Before:** :heavy_multiplication_x: “You have placed no orders” message is displayed

Peek 2020-06-03 12-42

**After:** :heavy_check_mark: All 11 orders are displayed on 1 page.

Peek 2020-06-03 13-13

**Comment by engcom-Kilo** [comment]
Added MFTF test

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Failing functional tests looks not related to changes from this Pr, but to be sure I just restarted them

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7610](https://jira.corp.magento.com/browse/ENGCOM-7610) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
