### PR TITLE
Remove strlen($baseUrl) from substr

### PR DESCRIPTION
**Pull request by codynguyen1**
Just need to cut off the media path, so the 3rd parameter is not neccessary.
3rd param cause missing some characters as well. (when the file name is longer than base url)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

On some cases, when the image file name is longer than base url, the url lost some characters causing the error:
Result: https://prnt.sc/r7qeuz
Actual url: https://prnt.sc/r7qezz
So I removed the 3rd param to avoid it.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

@magento give me test instance 
@magento give me 2.4-develop instance

### CODE REVIEW

**Review by swnsma — CHANGES_REQUESTED** [review]
Hi @codynguyen1,

Thank you for your contribution!
Could you cover your changes with Unit Tests?

**Comment by codynguyen1** [comment]
@swnsma I just ran the unit test for "vendor/magento/module-catalog-graph-ql/Test/Unit" on my local environment, do I need to do any thing else?
And how do I update the " All new or changed code is covered with unit/integration tests (if applicable)" item?
By the way, is submitting changes request to graphQL to this repo is right? cause I also see a graphql-ce repo but cannot create PR there.
Thank you!

**Comment by swnsma** [comment]
Hi @codynguyen1,

The class which you have changed does not cover with Unit Tests.
It will be great if you could cover this class with Unit Tests or, at least, cover the scenario which you have fixed in your PR (when image name is longer than a base path - it should not be cut).

To be honest, if you how no experience in writing unit tests, it may be difficult in the beginning but it fast to learn and Magento has a lot of examples of it :)
Otherwise, the PR will be put on hold until someone else introduces tests for your PR. This is a new contribution policy and we must follow them.

You free to make PR's related to GraphQL in the current repository.

**Comment by codynguyen1** [comment]
@swnsma  I updated the Unit test, please review it.
Thank you!

**Comment by swnsma** [comment]
Hi @codynguyen1!
Thank you for your update!
Could you please check failed tests?

**Comment by codynguyen1** [comment]
@swnsma Hi, the testing is giving me problem from another source, how can I get through this?
Thanks!
Screenshot at Mar 05 10-46-15

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-7048](https://jira.corp.magento.com/browse/ENGCOM-7048) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@codynguyen1 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed
### Manual Testing scenario
1. Created a subcategory and added an image named _Sample-png-image-500kb.png_
2. Performed a GraphQL query
```graphql
query category($id: Int!){
  category(id: $id) {
    product_count
    description
    url_key
    name
    id
    image
    breadcrumbs {
      category_name
      category_url_key
      __typename
    }
    meta_title
    meta_description
    meta_keywords
    __typename
  }
}
QUERY VARIABLES
{"id": 3}
```
The response body **BEFORE** switching to PR
7048_before

The response body **AFTER** switching to PR
7048_after

The link is valid and leads to the Category image

**Comment by engcom-Echo** [comment]
It seems that this problem is already fixed on [fix](https://github.com/magento/magento2/commit/3b4703b8c8ab31b8b50e88a8283cbf446d387bcc) and merged yesterday.

**Pull request closed without merging**
