### PR TITLE
fixing time format on admin sales order grid

### PR DESCRIPTION
**Pull request by krejcif**

### CODE REVIEW

**Comment by vrann** [comment]
@magexo can you please provide the description of your fix, i.e. expected result vs actual result.

**Comment by vrann** [comment]
@magexo verified the fix, here arebug description.
- create customer, create product, create order
- in admin backend navigate to Sales->Orders grid
- see the date, i.e. "Jan 30, 2017, 16:01:00 PM"
- open the order and check the date under "Order Date"

Expected result:
- date is the same as on the grid

Actual result
- date is different. I.e.: "Jan 30, 2017, 4:47:45 PM"

Note: date on the grid is wrong

Please correct me if it's not accurate

**Comment by krejcif** [comment]
yes, that's it...

**Comment by mikeymike** [comment]
Just came across this by chance but if you merge this you're going to want to close this 4 month old PR doing the same thing 

https://github.com/magento/magento2/pull/6785

**Comment by vrann** [comment]
@magexo Thank you for the contribution!

**Comment by vrann** [comment]
@mikekeilty Thanks for contribution, accepted it here.

**Comment by heldchen** [comment]
thanks @vrann!

**Comment by danielerovatti** [comment]
@vrann bug is still present in v.2.1.5 in vendor/magento/module-sales/view/adminhtml/ui_component/sales_order_grid.xml

**Comment by vrann** [comment]
@danielerovatti that is expectable: this PR was accepted to the develop branch which will be the part of the 2.2 release. There is a separate process of the backporting to the 2.1 branch.

**Comment by fxdegroot** [comment]
It should actually be **h:mm:ss A** instead of **H:mm:ss A**

**Comment by OZZlE** [comment]
@vrann when will you backport this to 2.1? It's still present in 2.1.7 .... Since 2.2 is still in RC you should really be backporting bugs like these, especially when they are simple to fix..

**Comment by OZZlE** [comment]
A == AM/PM
Capital H == 24 hour formatted hour (which is not used with AM/PM)

so either the A should be removed or it should be lowercase h

**Pull request merged**
