### PR TITLE
[Backport] Fix of saving "clone_field" fields

### PR DESCRIPTION
**Pull request by gelanivishal**
### Original Pull Request
#18160 

### Description
After the Config model's refactoring, which came with released version 2.2.6, there was an error in storing the fileds which were created using "clone_field" feature. When the values were stored, the path was wrong and the values were stored under the wrong key.

E.g. when saving Product Image Placeholders.
Instead of expected values `catalog/placeholder/image_placeholder`, `catalog/placeholder/ small_image_placeholder`, `catalog/placeholder/swatch_image_placeholder` and `catalog/placeholder/thumbnail_placeholder`, all fields were saved to the `catalog/placeholder/ placeholder`.
### Manual testing scenarios
1. Configuration -> Catalog -> Catalog
2. Open Product Image Placeholders tab
3. Upload an image
4. Save
5. "Saved" image is missing after page load.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by rodrigowebjump — APPROVED** [review]
Hi @gelanivishal 
Thanks for your contribution

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-3205](https://jira.corp.magento.com/browse/ENGCOM-3205) has been created to process this Pull Request

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18660) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Comment by maartenwolfsen** [comment]
I created a patch for this: https://gist.githubusercontent.com/maartenatmarissen/ecba171479af7f360942f64cf11355b2/raw/52f0255a1c1e6635765612ca6984d01eee9cf2ac/Config.php.patch.

Which can be applied using, for example: cweagans/composer-patches

**Pull request merged**
