### PR TITLE
[Backport] Fixes reverted for remove space when only one country in drop-down on both cart …

### PR DESCRIPTION
**Pull request by nilesh2jcommerce**
### Description

In Magento 2.1.X version having issue of extra space on both cart and checkout page for country dropdown. Even only one country is selected from admin.
I have applied fixes in core to remove this space issue from all version of 2.1.X

### Fixed Issues (if relevant)

1. #2146: Countries drop-down is empty

### Manual testing scenarios

1. Go in admin >> store >> configuration >> general under country options select one country in "Allow country" multi select drop-down and save it and then add product and move on both cart and checkout page there you will see country drop-down which contain no blank field or extra space before country which is select-able from admin.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=17194) <br/>All committers have signed the CLA.

**Comment by ihor-sviziev** [comment]
Hi @nilesh2jcommerce,
I don't see these changes not in 2.2-develop not in 2.3-develop. Looks like this issue was fixed in different way. It's better to have the same fix across the all 2.x release lines. Could you find how exactly it was fixed and create backport for it?

**Comment by nilesh2jcommerce** [comment]
Hi @ihor-sviziev

Yes exactly those fixes not applied on 2.2-develop not in 2.3-develop. But I have crosschecked on Latest Magento 2.2.X version after selecting single country from admin.Still showing extra **one space** on  checkout page for country drop-down. Can you please check and let me know according I will take step on this.

**Comment by ihor-sviziev** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, here is your [Magento instance](https://i-17194-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17194-2-2-5.engcom.dev.magento.com/admin](https://i-17194-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ihor-sviziev** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request.
Unfortunately, I can only deploy instances for `2.2-develop` and `2.3-develop` base branches

**Comment by ihor-sviziev** [comment]
Hi @nilesh2jcommerce,
What "space" are you talking about?
The empty one in "country" selector (above "United States")?
image


If no - please add correct steps to reproduce and maybe some screenshots to be sure we're on the same page

**Comment by nilesh2jcommerce** [comment]
Hi @ihor-sviziev,

Yes speaking about that extra space above United state. But sounds logically need that one space there.

I will figure out how it fixed in both 2.2-develop & 2.3-develop and let you know.

**Comment by nilesh2jcommerce** [comment]
Hi @ihor-sviziev,

I have found how this gone fixed and managed in both 2.2-develop & 2.3-develop. Same way I have fixed in 2.1-develop please check

**Comment by ihor-sviziev** [comment]
Hi @nilesh2jcommerce,
1. I see that your changes were just back-porting following changes: https://github.com/magento/magento2/commit/40ed7645b99ac68638c9910987b6da5b3601e61c
However there is related changes in https://github.com/magento/magento2/commit/e98deb723bc6b47e11ae5521e4c7496e55d790f2. Could you just cherry-pich these two commits?

2. You did also changes in Layout processor, that as I understood - not required anymore. Could you add only needed commits and force push your branch OR just create new PR with only required changes?

**Comment by nilesh2jcommerce** [comment]
Hi @ihor-sviziev,

Changes which I have made in Layout processor that was done from different branch and pushed which is not required.
**New fixes which I have applied that is managed different from individual branch and merged.**

Do you want me to remove my old fix which applied in Layout processor file?

**Comment by ihor-sviziev** [comment]
@nilesh2jcommerce,
As I understood you found how it was fixed in 2.2.x, and it was done in different way. We would like to keep fixes between the release lines as same as possible, so we would like to revert changes that you did originally (in layout processor) and add the same changes as we had in 2.2.x release line (in previous comment I added links to needed commits). Also we would like too keep original author name in a commit, so it would be better to do cherry pick of those commits

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-2975](https://jira.corp.magento.com/browse/ENGCOM-2975) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@nilesh2jcommerce thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @nilesh2jcommerce. Thank you for your contribution. 
We will aim to release these changes as part of 2.1.16. 
Please check the release notes for final confirmation.

**Pull request merged**
