### PR TITLE
MFTF: Replace repetitive actions with Action Groups in AdminUpdateCategoryAndMakeInactiveTest and VerifyChildCategoriesShouldNotIncludeInMenuTest

### LINKED ISSUE #30058: [Issue] MFTF: Replace repetitive actions with Action Groups in AdminUpdateCategoryAndMakeInactiveTest and VerifyChildCategoriesShouldNotIncludeInMenuTest
This issue is automatically created based on existing pull request: magento/magento2#30049: MFTF: Replace repetitive actions with Action Groups in AdminUpdateCategoryAndMakeInactiveTest and VerifyChildCategoriesShouldNotIncludeInMenuTest

---------

### Description (*)
AdminUpdateCategoryAndMakeInactiveTest and VerifyChildCategoriesShouldNotIncludeInMenuTest are refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
AdminUpdateCategoryAndMakeInactiveTest and VerifyChildCategoriesShouldNotIncludeInMenuTest in the local environment and verified the tests run successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
AdminUpdateCategoryAndMakeInactiveTest and VerifyChildCategoriesShouldNotIncludeInMenuTest are refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
AdminUpdateCategoryAndMakeInactiveTest and VerifyChildCategoriesShouldNotIncludeInMenuTest in the local environment and verified the tests run successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30058: MFTF: Replace repetitive actions with Action Groups in AdminUpdateCategoryAndMakeInactiveTest and VerifyChildCategoriesShouldNotIncludeInMenuTest

### CODE REVIEW

**Comment by sidolov** [comment]
@magento import to magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
Pull request successfully imported into `magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-30049`.

**Comment by magento-engcom-team** [comment]
Pull request successfully imported into `magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-30049`.

**Comment by sidolov** [comment]
@magento create issue

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-8267](https://jira.corp.magento.com/browse/ENGCOM-8267) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Pull request merged**
