### PR TITLE
Static lambda

### PR DESCRIPTION
**Pull request by MathiasReker**
This PR is risky. I made it from a theoretic point of view, but it need to be tested well, and the PR is big - so I guess it should just be closed again.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @MathiasReker. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
@MathiasReker what are the benefits of static lambda?

**Comment by MathiasReker** [comment]
http://php.net/manual/en/functions.anonymous.php

**Comment by orlangur** [comment]
@MathiasReker static lambda definition does not answer my question.

> As of PHP 5.4, anonymous functions may be declared statically. This prevents them from having the current class automatically bound to them. Objects may also not be bound to them at runtime.

What is the real benefit?

**Comment by MathiasReker** [comment]
speed

**Comment by orlangur** [comment]
@MathiasReker please provide some benchmarks then.

**Comment by MathiasReker** [comment]
screenshot

I just closed all my PR's. I am sorry, I do not have time to document everything. I just did my PR's to be a nice guy since it did not cost me anything else than power. I can't work free at the moment, because I have customers waiting for me. I hope you understand :-)

**Comment by orlangur** [comment]
@MathiasReker no problem, hope some day you may have some spare time to finish contributions so that they meet our standards https://github.com/magento/magento2/blob/2.3-develop/.github/CONTRIBUTING.md and can be actually processed.

Good luck with making your customers happy!

**Pull request closed without merging**
