### PR TITLE
Resolve Rule coupon code generate form validation issue23778

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. magento/magento2#23778: Resolve Rule coupon code generate form validation

Reason: **validateElement** function of jquery validation doesn't show the message.
Should use **validateSingleElement**

### Fixed Issues (if relevant)

1. magento/magento2#23778: Rule coupon code generate form validation

### Manual testing scenarios (*)

Case 1: 
1. Login to Admin
2. Create new sales rule with 'Use Auto Generation' enabled 
3. save rule
4. Open 'Manage Coupon Codes' section
5. Click 'Generate' button without filling required values

Expected result:
1. Validation error messages should be displayed 

Case 2: 
1. Login to Admin
2. Create new sales rule with 'Use Auto Generation' enabled 
3. save rule
4. Open 'Manage Coupon Codes' section
5. Add non integer value to 'Dash Every X Characters' box
5. Click 'Generate' button 

Expected result:
1. Proper  Validation error messages should be displayed so customer can input integer value there

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by Stepa4man — APPROVED** [review]
Hi @edenduong. Thanks for your contribution

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, thank you for the review.
[ENGCOM-5468](https://jira.corp.magento.com/browse/ENGCOM-5468) has been created to process this Pull Request
:eight_spoked_asterisk: @Stepa4man, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @edenduong !

During testing we faced an issue!

**Problem:** A verification error message is displayed but not focused on it

**Actual Result:**

after


**Note:** 

For example:

Go to Admin->Content->Widget->Add Widget;

after2

Focused on the field with validation error message


Could you please fix it in scope of this PR?

Thanks!

**Comment by edenduong** [comment]
Hi @engcom-Alfa,

I have just changed the code. You can test it again. Now it will focus to the first invalid element.

**Comment by engcom-Alfa** [comment]
@Stepa4man Could you review new changes? Thanks!

**Review by Stepa4man — APPROVED** [review]
I'm ok with these changes. Thanks, @edenduong!

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, thank you for the review.
[ENGCOM-5468](https://jira.corp.magento.com/browse/ENGCOM-5468) has been created to process this Pull Request
:eight_spoked_asterisk: @Stepa4man, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @edenduong !

Unfortunately, we faced an another issue.

**Problem:** JS error after pressing the button "Generate"

**Manual testing scenario:**

1. Login to Admin;
2. Go to Marketing->Cart Price Rules->Add New Rule;
3. Fill all required fields and enable  'Use Auto Generation';
4. Open 'Manage Coupon Codes' section;
5. Leave "Coupon Qty" empty and click on "Generate" button;
6. Open browser console;

**Actual Result:** JS error has occurred

after4

@edenduong Could you take a look, please?

Thanks!

**Comment by edenduong** [comment]
Hello @engcom-Alfa, @Stepa4man : I have changed the source code. Just remove the redundant code :) You can check it again.
Have a nice day :)

**Comment by edenduong** [comment]
@magento run all tests

**Comment by edenduong** [comment]
@magento run all tests

**Comment by edenduong** [comment]
All checks have passed

**Comment by engcom-Alfa** [comment]
@Stepa4man Could you review again, please?

**Comment by edenduong** [comment]
@Stepa4man : Thank you for continuing review my pull request. Could you please take a look this pull request again? :)

**Review by Stepa4man — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, thank you for the review.
[ENGCOM-5468](https://jira.corp.magento.com/browse/ENGCOM-5468) has been created to process this Pull Request
:eight_spoked_asterisk: @Stepa4man, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @edenduong ! 

During testing we faced an issue again.

**Problem:** JS error message does not disappear after entering valid data

**Actual Result:**

after5

**Expected Result:**

after6

@edenduong Could you take a look?

Thanks!

**Comment by edenduong** [comment]
Hello @engcom-Alfa ,I see some fields in Magento 2 is the same. So I think it is normal.
However, now, I resolve the problem. You can check it again.

@Stepa4man : Please check the new source code change for me :)

Have a good day.

**Comment by edenduong** [comment]
All checks of automation test have passed.

**Comment by edenduong** [comment]
@Stepa4man,  @engcom-Alfa : Please take a look at this PR :) Have a nice day !

**Review by Stepa4man — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, thank you for the review.
[ENGCOM-5468](https://jira.corp.magento.com/browse/ENGCOM-5468) has been created to process this Pull Request
:eight_spoked_asterisk: @Stepa4man, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
