### PR TITLE
Additional info not shown at customer/account/edit

### PR DESCRIPTION
**Pull request by jaykobi**
Block's call to form.additional.info is hidden within collapsed password fieldset.

### CODE REVIEW

**Comment by sshrewz** [comment]
Internal ticket - MAGETWO-56792

**Comment by snohe** [comment]
Internal ticket - MAGETWO-56792

**Comment by sevos1984** [comment]
@skymeissner Why form.additional.info shouldn't be hidden? According to code this is used for captcha and remember me, these are fields for password and should be hidden if password is hidden.

**Comment by slavvka** [comment]
Closing since there's no response from the author and it is not a bug.

**Pull request closed without merging**
