### PR TITLE
Fixed typo issue and added missing header in customer sales order grid

### PR DESCRIPTION
**Pull request by vishal-7037**
### Description (*)

Fixed Typo issue as well as added header title for Last Action Column
### Fixed Issues (if relevant)

1. magento/magento2#22641: Typo Issue and Missing header title at Customer Sales order grid

### Manual testing scenarios (*)

1. Login to Magento admin
2. Open Customer > All Customers > Edit any customer
3. Check header title of Order column and header title of last column.

Before Fixed: 
magento_customer_order_grid

After Fixed: 
magento_customer_order_grid_fixed

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by vishal-7037** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @vishal-7037. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @vishal-7037, here is your [new Magento instance](https://pr-22643.instances.magento-community.engineering).
Admin access: [https://pr-22643.instances.magento-community.engineering/admin](https://pr-22643.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by vishal-7037** [comment]
I've tested at Vanilla Magento 2.3 Instance and working fine. 

vanila_customer_sales_grid

Thanks.

**Comment by rogyar** [comment]
@magento-engcom-team give me test instanc

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-22643.instances.magento-community.engineering).
Admin access: [https://pr-22643.instances.magento-community.engineering/admin](https://pr-22643.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-5059](https://jira.corp.magento.com/browse/ENGCOM-5059) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Before:**

before

**After:**

after

**Pull request merged**
