### PR TITLE
[Todo] Fixed CSS issue from 

### PR DESCRIPTION
**Pull request by gelanivishal**
### Description
_ToDo UI: Temporary. Should be changed_
- I have removed temporary files.

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios

N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by VladimirZaets** [comment]
Hi, @gelanivishal, thank for collaboration. Due to [Magento backward-compatible guide](http://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/) we can't rename or move files. Someone can use this files in their implementations. With yours changes their implementation will be broken.

**Comment by VladimirZaets** [comment]
Hi @gelanivishal. What is the reason to reopen this PR?

**Comment by gelanivishal** [comment]
@VladimirZaets So when will you fix this type of Todo task?

**Pull request closed without merging**
