### PR TITLE
Fix infinite loop when disabled product and coupon code used in cart

### PR DESCRIPTION
**Pull request by robertsplorins**
### Description (*)
If the cart has disabled product in it, then total recalculation will be triggered in here
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Quote/Model/ResourceModel/Quote/Item/Collection.php#L289

If cart has a coupon code applied, then observer app/code/Magento/SalesRule/Observer/CouponCodeValidation.php 
will load the quote through the quote repository getList. This will reinstantiate the quote, during which total collection will get triggered again because of the disabled product, which will then go again into the observer, and so on, creating an infinite loop.

The fix changes the observer to fetch the old coupon code by DB query, instead of reinstantiating the quote through quote repository's getList. 

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. Add 2 different products to cart
2. Add coupon code
3. Disable one of the products
4. Trigger total recollection (refresh page/go to cart and edit qty)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by robertsplorins** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @robertsplorins. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @robertsplorins, here is your [Magento instance](https://i-26545-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26545-2-4-develop.instances.magento-community.engineering/admin_207b](https://i-26545-2-4-develop.instances.magento-community.engineering/admin_207b)
Login: `bd242ee4` Password: `b2aae915fcb3`
Instance will be terminated in up to 3 hours.

**Comment by robertsplorins** [comment]
could not reproduce on 2.4-develop

**Comment by robertsplorins** [comment]
Was already fixed by this https://github.com/magento/magento2/commit/32e778123803022f168dd35f96af58b27e180ef3

**Pull request closed without merging**
