### PR TITLE
#33506: updated elasticsearch/elasticsearch composer dependency

### PR DESCRIPTION
**Pull request by korovitskyi**
### Description (*)
Updated `elasticsearch/elasticsearch` composer dependency to version 7.13.1

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33506

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by korovitskyi** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Unit Tests

**Comment by eduard13** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Unit Tests

**Comment by eduard13** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Unit Tests

**Comment by eduard13** [comment]
Hi @korovitskyi, looks like something went wrong with your forked repo that says it was removed. Could you please double check that?

Thank you.

**Pull request closed without merging**
