### PR TITLE
27027 added date format adjustment for 'validate-dob' rule

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Added date format adjustment for 'validate-dob' rule

### Fixed Issues
#27027

### Manual testing scenarios
See issue description from #27027.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7036](https://jira.corp.magento.com/browse/ENGCOM-7036) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

No error appears after switching to the PR
customer_dofb

**Comment by nelero** [comment]
Thanks
how to use it with cweagans/composer-patches ? like in this message https://github.com/magento/magento2/issues/26675#issuecomment-582392597
is there anything to remove in paths of diff file ?

Thanks

**Comment by sergiy-v** [comment]
> Thanks
> how to use it with cweagans/composer-patches ? like in this message [#26675 (comment)](https://github.com/magento/magento2/issues/26675#issuecomment-582392597)
> is there anything to remove in paths of diff file ?
> 
> Thanks

Hello @nelero,
Not sure I 100% understand what are you looking for.
According to instruction for patch applying from your comment you are looking for PR diff, you can get by the following link.
https://github.com/magento/magento2/pull/27149.diff

Thank you.

**Comment by nelero** [comment]
hi @sergiy-v ,
thanks for the link. My question was if there was anything to remove in the paths of the content of the diff file. If you have a look at the https://github.com/magento/magento2/issues/26675#issuecomment-582392597 (the comment pointed), you'll see that we have to remove some parts of the paths written in the diff file in order to apply it correctly.
So i was wondering if we had to do the same with this diff file.
Thanks

**Comment by nelero** [comment]
hi @sergiy-v , i found my way to apply this patch with [cweagans/composer-patches](https://github.com/cweagans/composer-patches)

1. Create the patches/composer folder at the magento root directory
2. copy first part of diff file, related to magento/module-customer in a file in this folder, i.e. 27149-customer.diff
3. Copy the last part of diff file, related to magento/module-ui in another file 27149-ui.diff
4. In those 2 files, remove app/code/Magento/Customer/ and app/code/Magento/Ui/ wherever it appears
5. Add these lines in the composer.json file :
```
"extra": {
         "magento-force": "override",
         "composer-exit-on-patch-failure": true,
         "patches": {
             "magento/module-customer":{
                 "1.0": "patches/composer/27149-customer.diff"
             },
             "magento/module-ui":{
                 "1.0": "patches/composer/27149-ui.diff"
             }
 
         }
     } 
 ```
6. Run composer -v install
7. Run composer update --lock

**Comment by sergiy-v** [comment]
> hi @sergiy-v , i found my way to apply this patch with [cweagans/composer-patches](https://github.com/cweagans/composer-patches)

Hello @nelero, nice to hear that, thank you for your update!

**Comment by matthewhaworth** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @matthewhaworth. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @matthewhaworth, here is your [Magento instance](https://i-27149-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27149-2-4-develop.instances.magento-community.engineering/admin_4b80](https://i-27149-2-4-develop.instances.magento-community.engineering/admin_4b80)
Login: `f55d572f` Password: `65e79e93e371`
Instance will be terminated in up to 3 hours.

**Pull request merged**
