### PR TITLE
Convert MSRP currency of configurable product options

### LINKED ISSUE #29603: [Issue] Convert MSRP currency of configurable product options
This issue is automatically created based on existing pull request: magento/magento2#27446: Convert MSRP currency of configurable product options

---------
### Preconditions:

Magento 2.4-develop

The MSRP of configurable products is updated in Javascript when an option is chosen. Javascript uses an object with prices of the options. The prices in this object are converted to the chosen currency. MSRP prices however were not converted, leading to the price being displayed in a wrong currency.

### Steps to reproduce:

1. Enable MAP (Configuration > Sales > Sales > Minimum Advertised Price > Enable MAP).
2. Enable multiple currencies (Configuration > General > Currency Setup > Allowed Currencies)
3. Create a configurable product with options that have an MSRP
4. Go to the frontend and choose a currency that is not the base currency
5. View the product on the frontend a choose an option.

**Expected result:** :heavy_check_mark:  The MSRP is converted to the chosen currency

**Actual result:** :heavy_multiplication_x: The MSRP is not converted but it is labeled as the chosen currency

### PR DESCRIPTION
**Pull request by ashokadewit**
### Description

The MSRP of configurable products is updated in Javascript when an option is chosen. Javascript uses an object with prices of the options. The prices in this object are converted to the chosen currency. MSRP prices however were not converted, leading to the price being displayed in a wrong currency.

### Manual testing scenarios

1. Enable MAP (Configuration > Sales > Sales > Minimum Advertised Price > Enable MAP).
2. Enable multiple currencies (Configuration > General > Currency Setup > Allowed Currencies)
3. Create a configurable product with options that have an MSRP
4. Go to the frontend and choose a currency that is not the base currency
5. View the product on the frontend a choose an option.

Expected result: The MSRP is converted to the chosen currency
Actual result: The MSRP is not converted but it is labeled as the chosen currency

Screenshot from 2020-03-26 11-13-38

Note that the MSRP is configured in euro but displayed in dollars with the euro amount.

After applying the change the MSRP is converted:

Screenshot from 2020-03-26 12-52-14

Rates in table directory_currency_rate:

Screenshot from 2020-03-26 12-57-40

### Resolved issues:
1. [x] resolves magento/magento2#29603: Convert MSRP currency of configurable product options

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Review by sidolov — CHANGES_REQUESTED** [review]
@ashokadewit could you please cover changes with the automated tests?

**Comment by engcom-Echo** [comment]
I will take care of test coverage.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8174](https://jira.corp.magento.com/browse/ENGCOM-8174) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@ashokadewit thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Enable MAP (Configuration > Sales > Sales > Minimum Advertised Price > Enable MAP).
2. Enable multiple currencies (Configuration > General > Currency Setup > Allowed Currencies)
3. Create a configurable product with options that have an MSRP
4. Go to the frontend and choose a currency that is not the base currency
5. View the product on the frontend a choose an option.

**Before:** :heavy_multiplication_x:  The MSRP is not converted but it is labeled as the chosen currency



**After:** :heavy_check_mark: The MSRP is converted to the chosen currency

**Comment by engcom-Echo** [comment]
@magento run all tests

**Pull request merged**
