### PR TITLE
MFTF: Newsletter Subscription With Enabled Need To Confirm Config

### LINKED ISSUE #33344: [Issue] MFTF: Newsletter Subscription With Enabled Need To Confirm Config
This issue is automatically created based on existing pull request: magento/magento2#33342: MFTF: Newsletter Subscription With Enabled Need To Confirm Config

---------
This PR contains a MFTF test for checking newsletter subscription process with enabled  "Need To Confirm" config.
Guests and customers should receive correct notifications.

**Steps to reproduce**
1 - Enable "Need To Confirm" config.
2 - Subscribe to newsletter as guest on storefront
3 - Login as customer
4 - Subscribe to newsletter as customer on storefront
5 - Perform assertions

### PR DESCRIPTION
**Pull request by DmitryTsymbal**
This PR contains a MFTF test for checking newsletter subscription process with enabled  "Need To Confirm" config.
Guests and customers should receive correct notifications.

**Steps to reproduce**
1 - Enable "Need To Confirm" config.
2 - Subscribe to newsletter as guest on storefront
3 - Login as customer
4 - Subscribe to newsletter as customer on storefront
5 - Perform assertions

### Resolved issues:
1. [x] resolves magento/magento2#33344: MFTF: Newsletter Subscription With Enabled Need To Confirm Config

### CODE REVIEW

**Comment by DmitryTsymbal** [comment]
@magento run all tests

**Comment by shikhamis11** [comment]
@magento create issue

**Comment by shikhamis11** [comment]
@magento run all tests

**Comment by shikhamis11** [comment]
@magento run Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by shikhamis11** [comment]
@magento run all tests

**Review by sidolov — CHANGES_REQUESTED** [review]
@DmitryTsymbal please, check failed tests

**Comment by DmitryTsymbal** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
I have checked that the PR changes have 2 new files, and the build failure is not because of the PR changes. So moving this to Merge in Progress.

Thank You!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
Hi @sidolov,

I have merged 2.4 develop into this branch and also fixed the issue of failed **StorefrontNewsletterSubscriptionWithEnabledNeedToConfirmConfigTest** functional test case.

As the PR is covering the MFTF test case and now the build is green so moving it forward to Merge in Progress.

Thank you!

**Comment by engcom-Charlie** [comment]
It seems that bot moved this PR in Changes Requested, so moving it back to Merge in Progress.

Thank you!

**Pull request merged**
