### PR TITLE
fix full name not displayed in top nav header when varnish and nginx used

### PR DESCRIPTION
**Pull request by taoufiqaitali**
### Description (*)
when varnish and nginx is used, full name is not displayed when you logout and login again.

### Manual testing scenarios (*)

1. install magento 2.3.3
2. use Varnish and nginx
3. login ->Logout -> login again

current result 
image
after change
image

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @taoufiqaitali,
Could you add steps to reproduce? I can't reproduce this issue on clear magento installation.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by taoufiqaitali** [comment]
> Hi @taoufiqaitali,
> Could you add steps to reproduce? I can't reproduce this issue on clear magento installation.

Hi @ihor-sviziev 
just install nginx and varnish and then logout and login

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @taoufiqaitali,
I wasn't able to reproduce this issue.

I created environment with nginx & varnish using https://warden.dev/ docker installation, internally it uses Varnish + nginx + php-fpm.

I tried multiple times to logout and login - all the time I'm getting correct behavior:
image
image



Please try to reproduce on clean magento installation, and provide us steps to reproduce.

**Comment by ihor-sviziev** [comment]
@taoufiqaitali  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
