### PR TITLE
"Create Permanent Redirect for URLs if URL Key Changed" for categories

### LINKED ISSUE #24922: "Create Permanent Redirect for URLs if URL Key Changed" for categories
When setting the config option `Stores > Configuration > Catalog > Catalog > SEO > Create Permanent Redirect for URLs if URL Key Changed` to "No". The "Create Permanent Redirect for old URL" is unchecked by default for products but is still checked by default when you change the URL key on a category.

### Preconditions (*)

1. Magento 2.3.2  and `2.4-develop`

### Steps to reproduce (*)
1. Go to `Stores > Configuration > Catalog > Catalog > Search Engine Optimisation` and set `Create Permanent Redirect for URLs if URL Key Changed` to "No".
2. Go to any category and edit the URL key.

### Expected result (*)

1. "Create Permanent Redirect for old URL" is **unchecked** by default (like products)

### Actual result (*)

1. "Create Permanent Redirect for old URL" is **checked ** by default

screenshot-magento staging edge-servers com-2019 10 08-12_41_44

screenshot-magento staging edge-servers com-2019 10 08-12_42_37

### PR DESCRIPTION
**Pull request by engcom-Charlie**
### Description (*)

Fixed and covered by the test.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#24922

### Manual testing scenarios (*)

see #24922

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by swnsma — CHANGES_REQUESTED** [review]
Hi @engcom-Charlie,

Could you please check next case:

1. When `Go to Stores > Configuration > Catalog > Catalog > Search Engine Optimisation and set Create Permanent Redirect for URLs if URL Key Changed` is set to "YES" (by default), checkbox is disabled until you start to edit url-key (which is fine).
Screen Shot 2020-06-21 at 1 26 08 PM

2.  When `Go to Stores > Configuration > Catalog > Catalog > Search Engine Optimisation and set Create Permanent Redirect for URLs if URL Key Changed` is set to "NO", checkbox is not disabled even if you have not changed anything.
Screen Shot 2020-06-21 at 1 25 17 PM

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-7724](https://jira.corp.magento.com/browse/ENGCOM-7724) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked scenario from #24922

:x: **Before:**
#28752Main

:heavy_check_mark: **After:**
#28752PR

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-7724](https://jira.corp.magento.com/browse/ENGCOM-7724) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
**Notice:** QA not applicable. 
Only MFTF was added in last [commit](https://github.com/magento/magento2/pull/28752/commits/0c9623a74a65fae3a2ce10abb4fecfd4b5ef144f)

**Comment by engcom-Echo** [comment]
@magento run all tests

**Pull request merged**
