### PR TITLE
Less file image mixin usage added.

### LINKED ISSUE #30732: [Issue] Less file image mixin usage added.
This issue is automatically created based on existing pull request: magento/magento2#30730: Less file image mixin usage added.

---------

### Description (*)

Less file image mixin usage added as its less mixin is defined here: `<root>/lib/web/css/source/lib/_utilities.less:303`
The `.lib-url()` mixin wraps passed value with 'url( ... )' and returns `@lib-url-check-output` variable. Can be used with `.lib-css()` mixin.
If the variable is set to false, the `.lib-url()` will return false. (Reference: https://magento-devdocs.github.io/magento2-ui-library/utilities.html#liburlcheck - Here please consider `.lib-url-check()` as `.lib-url()` only as its been updated in latest magento versions.)

### Related Pull Requests

N/A

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by pratiksangani**
### Description (*)

Less file image mixin usage added as its less mixin is defined here: `<root>/lib/web/css/source/lib/_utilities.less:303`
The `.lib-url()` mixin wraps passed value with 'url( ... )' and returns `@lib-url-check-output` variable. Can be used with `.lib-css()` mixin.
If the variable is set to false, the `.lib-url()` will return false. (Reference: https://magento-devdocs.github.io/magento2-ui-library/utilities.html#liburlcheck - Here please consider `.lib-url-check()` as `.lib-url()` only as its been updated in latest magento versions.)

### Related Pull Requests

N/A

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30732: Less file image mixin usage added.

### CODE REVIEW

**Comment by pratiksangani** [comment]
@magento create issue

**Comment by pratiksangani** [comment]
@magento run all tests

**Comment by pratiksangani** [comment]
@ihor-sviziev Will you please proceed this PR?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @pratiksangani,
Could you fix failing static tests?

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

**Comment by sidolov** [comment]
@pratiksangani I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
