### PR TITLE
[TASK] Updated the implements for the Magento_Cms Adminhtml Controllers

### PR DESCRIPTION
**Pull request by lewisvoncken**
### Description (*)

code clean up by adding correct implements for Cms Adminhtml Controllers.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @lewisvoncken. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [new Magento instance](https://pr-19715.instances.magento-community.engineering).
Admin access: [https://pr-19715.instances.magento-community.engineering/admin](https://pr-19715.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3676](https://jira.corp.magento.com/browse/ENGCOM-3676) has been created to process this Pull Request

**Review by rodrigowebjump — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-3676](https://jira.corp.magento.com/browse/ENGCOM-3676) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @lewisvoncken. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
