### PR TITLE
PhpDoc @param $quote can accept null

### PR DESCRIPTION
**Pull request by idsergiu**
### Description (*)
PhpDoc @param $quote can accept null

### Manual testing scenarios (*)
1. Send a null quote in the available payment methods

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run all tests

**Review by Den4ik — APPROVED** [review]
✔️ Approve

@idsergiu Thanks for your work

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9079](https://jira.corp.magento.com/browse/ENGCOM-9079) has been created to process this Pull Request

**Comment by andrewbess** [comment]
This PR has already been merged

**Pull request merged**
