### PR TITLE
MFTF: Admin Delete Newsletter Subscriber

### LINKED ISSUE #29032: [Issue] MFTF: Admin Delete Newsletter Subscriber
This issue is automatically created based on existing pull request: magento/magento2#28972: MFTF: Admin Delete Newsletter Subscriber

---------
**Preconditions:**

This PR contains a test for deleting newsletter subscriber as Admin User

**Steps to reproduce:**

1 - Subscribe a customer for newsletter

2 - Navigate as Admin User to Admin>Marketing>Newsletter Subscribers

3 - Find subscriber on grid

4 - Delete Subscriber

5 - Perform Assertions

**Actual Result:**

**Expected Result:** The subscriber was successfully deleted

### PR DESCRIPTION
**Pull request by DmitryTsymbal**
This PR contains a test for deleting newsletter subscriber as Admin User

**Steps to reproduce:**

1 - Subscribe a customer for newsletter

2 - Navigate as Admin User to Admin>Marketing>Newsletter Subscribers

3 - Find subscriber on grid

4 - Delete Subscriber

5 - Perform Assertions

### Resolved issues:
1. [x] resolves magento/magento2#29032: MFTF: Admin Delete Newsletter Subscriber

### CODE REVIEW

**Comment by dmytro-ch** [comment]
@magento run all tests

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7788](https://jira.corp.magento.com/browse/ENGCOM-7788) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
