### PR TITLE
MFTF: Unlock Admin User Entity Test

### LINKED ISSUE #34836: [Issue] MFTF: Unlock Admin User Entity Test
This issue is automatically created based on existing pull request: magento/magento2#32758: MFTF: Unlock Admin User Entity Test

---------
This PR contains a test for unlocking admin user on "Locked Users" grid

**Steps to reproduce:**

1 - Create Admin user

2 - Lock Admin User

3 - Find locked Admin User on "Locked Users" grid

4 - Unlock Admin User

5 - Perform Assertions

### PR DESCRIPTION
**Pull request by DmitryTsymbal**
This PR contains a test for unlocking admin user on "Locked Users" grid

**Steps to reproduce:**

1 - Create Admin user

2 - Lock Admin User

3 - Find locked Admin User on "Locked Users" grid

4 - Unlock Admin User

5 - Perform Assertions

### Resolved issues:
1. [x] resolves magento/magento2#34836: MFTF: Unlock Admin User Entity Test

### CODE REVIEW

**Comment by DmitryTsymbal** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run Functional Tests CE , Functional Tests B2B , WebAPI Tests

**Comment by dmytro-ch** [comment]
@magento run Functional Tests CE , Functional Tests B2B

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B

**Comment by dmytro-ch** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run all tests

**Review by Den4ik — CHANGES_REQUESTED** [review]
Hi @DmitryTsymbal 
Please update mftf test based on console log from failed tests

**Comment by Den4ik** [comment]
> Please update mftf test based on console log from failed tests

@DmitryTsymbal sorry, looks like reported problems is not related to changes from this PR

**Comment by Den4ik** [comment]
Failed test related to two-factor-auth module that don't described in "Build configuration".
Waiting for response from Core team

**Comment by Den4ik** [comment]
@magento run Functional Tests EE, Functional Tests B2B, Functional Test CE, Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE

**Review by sidolov — CHANGES_REQUESTED** [review]
@DmitryTsymbal please, check tests failures

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @DmitryTsymbal,

Thank you for your contribution!

I am looking into the failed tests from the build.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Sample Data Tests CE, Sample Data Tests EE, Sample Data Tests B2B, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Currently not looking into this PR as I am in between some other priority tasks. Will resume work on this once done with current work.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento create issue

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
Hi @sidolov, 

I have merged latest 2.4-develop branch into this PR branch and resolved all conflicts. 

Previously The build phase was not successful  because of issue in AdminUnlockAdminUserEntityTest.xml test case. I have fixed the issue by modifying the test title and added testCaseId in AdminUnlockAdminUserEntityTest.xml test’s  annotation.

Now the build phase is successful but below tests are failing.

- app/code/Magento/CatalogSearch/Test/Mftf/Test/SearchEntityResultsTest/QuickSearchWithTwoCharsEmptyResultsTest.xml
-  app/code/Magento/LoginAsCustomer/Test/Mftf/Test/AdminLoginAsCustomerLoggingFilterTest.xml

Note: The failing test cases are working fine on my local setup.

image


In this PR, since complete new test case has been added and the test cases which are failing now are not part of this PR changes or not failing because of any change made in this PR moving this PR further.

Requesting @Den4ik to review the changes again hence moving it to Pending Review.

Thank You!

**Comment by Den4ik** [comment]
@magento run Functional Tests CE

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9377](https://jira.corp.magento.com/browse/ENGCOM-9377) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Pull request merged**
