### PR TITLE
Revert "Add validation phone field on checkout page"

### PR DESCRIPTION
**Pull request by engcom-Charlie**
Reverts magento/magento2#27537

This PR has been reverted due to a regression bug for 2.4.1 `MC-36812`. These changes was Rejected by Product Manager

Explanation:

> The input validation on the customer and customer address attributes should be configured in Admin in attribute settings. There is currently possible to configure only numbers and - symbol input validation and all the validations are extensible so if merchants want to add any other validation rules which are not available out of the box they can customize them by themselves.  

This functionality is already available in Admin Panel(UI) for Commerce edition(EE). It has section "Customer Address Attributes"

> In Open Sorce(CE) edition, there is no UI in Admin Panel for this but it can be easily done with minimal dev assistance.

### CODE REVIEW

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@sidolov Please review this PR.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8032](https://jira.corp.magento.com/browse/ENGCOM-8032) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Precondition:**
Magento 2.4-develop (**EE**)
Create a category;
Create Product and assign to category;

**Manual testing scenario:**
1. Go to Admin -> Stores -> Attributes -> Customer Address and select **telephone** attribute for edit;
2. Make sure that **Input Validation** is set to **None**


3. Go to Storefront;
4. Add product to cart;
5. Click on **Proceed to Checkout** button;
6. Fill all required fields;

**Before:** :heavy_multiplication_x: Please enter a valid phone number. For example (123) 456-7890 or 123-456-7890.



**After:** :heavy_check_mark: No validation for **Phone Number** field




Also was checked on the **CE** and **B2B** versions of Magento, and everything works as previous (expected).

**Comment by ihor-sviziev** [comment]
@engcom-Charlie @sidolov thank you for making revert publicly with sharing reason why it was reverted!

**Pull request merged**
