### PR TITLE
Remove Wishlist AddToCart Observer on `checkout_cart_add_product_complete` event

### PR DESCRIPTION
**Pull request by vasilii-b**
### Description
Cleanup the core as for TODO from `Magento/Checkout/Controller/Cart/Add.php:115`.
Was removed `AddToCart` observer on event `checkout_cart_add_product_complete`.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios
N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by VladimirZaets** [comment]
Hi, @vasilii-b, due to [Magento backward-compatible guide](http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/) we can't remove existing classes.

**Comment by vasilii-b** [comment]
@VladimirZaets I see. Then what's the way to go here ? Should I only remove the ToDo and mark those classes ad deprecated ?
With removed lines from `events.xml`, deleted files won't be called anymore, anytime. They'll be present there only physically without doing any job.
Would like to know your thoughts on this. 
Thank you!

**Comment by VladimirZaets** [comment]
@vasilii-b In this cases we should only mark classes as deprecated. In Magento this classes   won't be called anymore but someone can use or extend this classes in their implementation.

What the reason to delete this files? Are you sure that this observer is redundant and unnecessary and that removing this classes will not broke functionality?

**Comment by orlangur** [comment]
@VladimirZaets looks like you missed the
> Backward Сompatibility Policy is not applied to Plugins, Observers and Setup Scripts.

part.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-2767](https://jira.corp.magento.com/browse/ENGCOM-2767) has been created to process this Pull Request

**Comment by VladimirZaets** [comment]
@orlangur Ok, I agree, but I not sure that deleting this observer will not break functionality.

**Comment by sidolov** [comment]
Hi @vasilii-b , @orlangur , I don't think that we should remove the part of the functionality because of comment. Looks like the author meant that this logic should be refactored and moved from observer to plugin or something else.

**Comment by vasilii-b** [comment]
So, what's the way to go here, @sidolov @orlangur ? 🤔 Remove that observer or create a plugin for it ?
Thank you!

**Comment by orlangur** [comment]
@vasilii-b you need to find out functionality implemented by this observer and refactor it as a plugin if you want to remove observer.

**Review by orlangur — CHANGES_REQUESTED** [review]
@vasilii-b you need to find out functionality implemented by this observer and refactor it as a plugin if you want to remove observer.

**Comment by sidolov** [comment]
Hi @vasilii-b , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
