### PR TITLE
Fixed typo in tracking.phtml - renamed JS-functions "currier" to "carrier"

### LINKED ISSUE #34523: [Issue] Fixed typo in tracking.phtml - renamed JS-functions "currier" to "carrier"
This issue is automatically created based on existing pull request: magento/magento2#33414: Fixed typo in tracking.phtml - renamed JS-functions "currier" to "carrier"

---------
### Description (*)

While implementing a custom shipping carrier I mentioned some typos in the JS-handler-functions used in the Magento_Shipping/view/adminhtml/templates/order/tracking.phtml:

- bindCurrierOnchange
- currierOnchange

I renamed them to 

- bindCarrierOnchange
- carrierOnchange

### PR DESCRIPTION
**Pull request by 4ctobias**
### Description (*)

While implementing a custom shipping carrier I mentioned some typos in the JS-handler-functions used in the Magento_Shipping/view/adminhtml/templates/order/tracking.phtml:

- bindCurrierOnchange
- currierOnchange

I renamed them to 

- bindCarrierOnchange
- carrierOnchange

### Resolved issues:
1. [x] resolves magento/magento2#34523: Fixed typo in tracking.phtml - renamed JS-functions "currier" to "carrier"

### CODE REVIEW

**Comment by 4ctobias** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Review by Den4ik — APPROVED** [review]

**Review by n-ramdi — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run all tests

**Review by ArthurHW — APPROVED** [review]

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

1. Go to app/code/Magento/Shipping/view/adminhtml/templates/order/tracking.phtml
2. Verify the values in the phtml file.

**Before:** :heavy_multiplication_x: 

Screenshot 2023-12-31 at 7 42 52 PM


**After:** :heavy_check_mark:  

Screenshot 2024-01-02 at 11 27 07 AM

Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Pull request merged**
