### PR TITLE
My-Accounttele-phone-field-require-no-validation-appear

### PR DESCRIPTION
**Pull request by dipti2jcommerce**
In My Account dashboard page when we create new address from address book telephone field is require,but no validation appear while submission 

### Description (*)
In My Account dashboard page when we create new address from address book telephone field is require,but no validation appear while submission 

### Fixed Issues (if relevant)

In My Account dashboard page when we create new address from address book telephone field is require,but no validation appear while submission #20261

### Manual testing scenarios (*)
2019-01-14_12-52_add new address

### Contribution checklist (*)

In My Account dashboard page when we create new address from address book telephone field is require,but no validation appear while submission

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20262) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @dipti2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by tuyennn** [comment]
The problem came form the unknown 
**->getAttributeValidationClass('fax')** which defined in telephone templates phtml, definitely this should be
 **->getAttributeValidationClass('telephone')**

https://github.com/magento/magento2/blob/80d87ec4ec795d03fea7ec96fd851666a5226069/app/code/Magento/Customer/view/frontend/templates/widget/telephone.phtml#L22

This happened only on branch 2.3

Please remove the lines, if this PR would be accepted
https://github.com/magento/magento2/blob/80d87ec4ec795d03fea7ec96fd851666a5226069/app/code/Magento/Customer/view/frontend/templates/widget/telephone.phtml#L19-L24

**Comment by dipti2jcommerce** [comment]
Hi @tuyennn ,
I have change value from fax to telephone ->getAttributeValidationClass('fax') which defined in telephone templates phtml, to
->getAttributeValidationClass('telephone').
And its working fine,please check.
Thanks,
Dipti

**Review by VladimirZaets — APPROVED** [review]

**Comment by tuyennn** [comment]
@dipti2jcommerce As I saw you made change to
````
class="input-text <?= $block->escapeHtmlAttr($block->getAttributeValidationClass('telephone')) ?>"
````

So why should we keep these lines? - You could remove those
https://github.com/magento/magento2/blob/80d87ec4ec795d03fea7ec96fd851666a5226069/app/code/Magento/Customer/view/frontend/templates/widget/telephone.phtml#L19-L24

**Comment by dipti2jcommerce** [comment]
Hi @tuyennn ,
I have removed my changes made previously and add changes as per requirement,please check .
Thanks,
Dipti

**Comment by magento-engcom-team** [comment]
@dipti2jcommerce thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @dipti2jcommerce. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
