### PR TITLE
Fix - Next Page button triggered when filtering Customer grid

### PR DESCRIPTION
**Pull request by ronak2ram**
### Description
I do change in grid.phtml. There is a missing button type. If we did not put button type then button work as a submit button.

### Fixed Issues (if relevant)
1. magento/magento2#17789: Next Page button triggered when filtering Customer grid

### Manual testing scenarios
1. Go to "Sales -> Orders"
2. "Create new order"
3. Customer grid is displayed
4. Focus on any column filter (i.e. text box in email column)
5. Press ENTER to trigger the filter

### Expected result

1. Filter's AJAX call is triggered
2. Results don't change because the filter input was empty
3. Grid is still showing the same page.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ronak2ram. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by miguelbalparda** [comment]
Hi @ronak2ram! Thanks for your contribution. Can you please create a port to 2.3? We are trying to have everything merged in 2.3 before proceeding with other branches. Thanks!!

**Comment by ronak2ram** [comment]
Hello @miguelbalparda 
I created port for 2.3. Please check pull #17874

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-2920](https://jira.corp.magento.com/browse/ENGCOM-2920) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @ronak2ram. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Comment by ronak2ram** [comment]
Hello @magento-engcom-team 
I read this(https://github.com/magento/magento2/wiki/Contribution-Rewards) document.
As per this document I think Bug fix achievement missing for this pull.

**Pull request merged**
