### PR TITLE
Fixes for the issues found by Unit Tests for PHP 8.1 compatibility

### PR DESCRIPTION
**Pull request by karyna-t**
### Description (*)
This PR is fixing existing Unit Tests (and related files from Magento Core) to be compatible with PHP 8.1.

### Related Issues
1. magento/magento2#34441

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by karyna-tsymbal-atwix** [comment]
@magento run all tests

**Comment by karyna-tsymbal-atwix** [comment]
test Magento\Wishlist\Test\Unit\Model\WishlistTest is fixed in https://github.com/magento/magento2/pull/34453

static test `Magento\Test\Php\LiveCodeTest::testCodeStyle` fails because of the problem in magento-coding-standards.
There is a PR that should fix the issue:
https://github.com/magento/magento-coding-standard/pull/319

**Comment by karyna-tsymbal-atwix** [comment]
@magento run all tests

**Comment by karyna-tsymbal-atwix** [comment]
@magento run all tests

**Comment by karyna-tsymbal-atwix** [comment]
@magento run all tests

**Comment by karyna-tsymbal-atwix** [comment]
@magento run all tests

**Review by andrewbess — APPROVED** [review]

**Review by xmav — APPROVED** [review]

**Comment by xmav** [comment]
Functional tests failures not related to changes in this PR.

**Pull request merged**
