### PR TITLE
Change Admin layout label

### PR DESCRIPTION
**Pull request by AnshuMishra17**
### Description (*)
Changed the 2 column layout label for admin theme.

### CODE REVIEW

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5584](https://jira.corp.magento.com/browse/ENGCOM-5584) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @AnshuMishra17 !

Could you please add this phrase `Admin 2 columns with left bar` into translate file?

Thanks!

**Comment by AnshuMishra17** [comment]
@engcom-Alfa Done, I have added the phrase in translate file.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
