### PR TITLE
Add wordwrap to Mail Message body.

### PR DESCRIPTION
**Pull request by delgor**
### Description (*)
Add a word wrap to the Mail::Message::setBody() function to ensure the maximum line length of an e-mail as specified in http://www.rfc-editor.org/rfc/rfc5322.txt Section 2.1.1

### Fixed Issues (if relevant)

1. magento/magento2#24528: Mail line length too long, breaks DKIM signature

### Manual testing scenarios (*)

1. Let Magento send any e-mail (Newsletter subscription, Customer registration, password recovery).

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @delgor , please, sign CLA, otherwise, we can't process your pull request

**Comment by delgor** [comment]
I signed the CLA.

I see that the Database Compare build is failing - considering that my change is nowhere near the database, could this be an error in the check? What needs to be done here?

**Comment by gwharton** [comment]
Already fixed in 2.3-develop by changing encoding type to QUOTED PRINTABLE.

**Comment by gwharton** [comment]
Closing this PR as no longer required. Please reopen and comment if the solution already merged in 2.3-develop does not resolve your issue. #23649

**Pull request closed without merging**
