### PR TITLE
Sitemap Observer Unit Test improvement: Expect email notification to send, and simplify setup a bit.

### PR DESCRIPTION
**Pull request by evktalo**
### Description (*)

Add an expect for the emailNotification's sendErrors method. This makes the test match its title (testScheduledGenerateSitemapsSendsExceptionEmail) better.

Also try to be more consistent when calling PHPUnit's TestCase's mock creation functions in setUp; favour createMock.

### Manual testing scenarios (*)

1. install magento
2. in root, call vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist app/code/Magento/Sitemap/Test/Unit/Model/ObserverTest.php

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [-] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by edenduong — APPROVED** [review]
Thank you for your contribution!

**Comment by magento-engcom-team** [comment]
Hi @edenduong, thank you for the review.
[ENGCOM-7209](https://jira.corp.magento.com/browse/ENGCOM-7209) has been created to process this Pull Request
:eight_spoked_asterisk: @edenduong, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Pull request merged**
