### PR TITLE
.lib-popup-button-close-icon() misses a leading underscore

### PR DESCRIPTION
**Pull request by redelschaap**
Added underscore to `.lib-popup-button-close-icon()`

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=5957) <br/>All committers have signed the CLA.

**Comment by vkorotun** [comment]
Internal ticket: MAGETWO-56543

**Comment by undefined-olha** [comment]
Hello, @redelschaap!
We appreciate your efforts, but in this case we shoudl leave mixin as is. 
Underscore before mixins in the UI libarary is used to define "privat" mixin, which shoudl not be used separately from parent mixin.

Example of "public" (independent) mixin:

``` less
//  Rating-vote mixin
.lib-rating-vote(
    @_icon-count: @rating-icon__count, // accepts global variables
    @_icon-content: @rating-icon__content,
    @_icon-font: @rating-icon__font,
    @_icon-font-size: @rating-icon__font-size,
    @_icon-letter-spacing: @rating-icon__letter-spacing,
    @_icon-color: @rating-icon__color,
    @_icon-color-active: @rating-icon__active__color
) {
    // rating styles go here
}
```

Example of "privat" mixin:

``` less
//  Popup Headings
._lib-popup-headings(
    @_popup-title-headings, // accepts parent variables
    @_popup-title-headings-level
) when (@_popup-title-headings = true) and (@_popup-title-headings-level = h1) {
    .lib-heading(h1);
}
```

Also this changes can affect existing stores.
Please do not hesitate to ask any questions.
Thank you.

**Comment by redelschaap** [comment]
Please help me then understand why `.lib-popup-button-close-icon()` should be public and have no leading underscore, while `._lib-popup-button-close-reset()` should be private and have a leading underscore?

They're both used in other functions and have the same declaration structure:

``` less
//  Popup close button use icon
.lib-popup-button-close-icon(
    @_popup-button-close-icon,
    @_popup-icon-font-content,
    @_popup-icon-font,
    @_popup-icon-font-size,
    @_popup-icon-font-line-height,
    @_popup-icon-font-color,
    @_popup-icon-font-color-hover,
    @_popup-icon-font-color-active,
    @_popup-icon-font-margin,
    @_popup-icon-font-vertical-align,
    @_popup-icon-font-position,
    @_popup-icon-font-text-hide
) when (@_popup-button-close-icon = true) {
    .lib-button-icon(
        @_icon-font-content: @_popup-icon-font-content,
        @_icon-font: @_popup-icon-font,
        @_icon-font-size: @_popup-icon-font-size,
        @_icon-font-line-height: @_popup-icon-font-line-height,
        @_icon-font-color: @_popup-icon-font-color,
        @_icon-font-color-hover: @_popup-icon-font-color-hover,
        @_icon-font-color-active: @_popup-icon-font-color-active,
        @_icon-font-margin: @_popup-icon-font-margin,
        @_icon-font-vertical-align: @_popup-icon-font-vertical-align,
        @_icon-font-position: @_popup-icon-font-position,
        @_icon-font-text-hide: @_popup-icon-font-text-hide
    );
}

//  Popup close button reset
._lib-popup-button-close-reset (
    @_popup-button-close-reset
) when (@_popup-button-close-reset = true) {
    .lib-button-reset();
}
```

**Pull request closed without merging**
