### PR TITLE
magento/magento2#35906 GraphQL Routes query with fragments has issue in the category page #35906

### LINKED ISSUE #35906: GraphQL Routes query with fragments has issue in the category page
### Preconditions and environment

Environment: Magento Open Source 2.4.5

Preconditions: Use the category page URL in the param. Also, use fragments in the query

### Steps to reproduce

1. Create a sub category under default category and run the graphQL query with category url in the query. Please run it in the tool
````
query Route($url: String!) {
    route(url: $url) {
      redirect_code
      relative_url
      type
   
      ... on CategoryTree {
        name
        id
        url_path
        url_suffix
        breadcrumbs {
          category_name
          category_url_path
          category_uid
        }
      }
       ...on SimpleProduct{
        ...ProductFragment
        }
    }
  }
fragment ProductFragment on SimpleProduct {
    name
    price_range {
      minimum_price {
        regular_price {
          value
        }
        final_price {
          value
        }
      }
    }
    description {
      html
    }
    image {
      url
    }
    media_gallery {
      url
    }
  }
````

2. Variable used:
 `{
  "url": "men.html"
}`

### Expected result

Returns category information.

`{
  "data": {
    "route": {
      "redirect_code": 0,
      "relative_url": "men.html",
      "type": "CATEGORY",
      "name": "Men",
      "id": 11,
      "url_path": "men",
      "url_suffix": ".html",
      "breadcrumbs": null
    }
  }
}`

### Actual result

500 Internal server error is returned

`{
  "errors": [
    {
      "debugMessage": "Notice: Undefined property: GraphQL\\Language\\AST\\FragmentSpreadNode::$selectionSet in /var/www/html/mage245/vendor/magento/module-catalog-graph-ql/Model/Category/DepthCalculator.php on line 83",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 2,
          "column": 5
        }
      ],
      "path": [
        "route"
      ]
    }
  ],
  "data": {
    "route": null
  }
}`

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by monteshot**
### Description (*)

- Changed from non-safe if statement to safe "empty if ()" statement

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35906

### Manual testing scenarios (*)

1. Steps the same as described in comment https://github.com/magento/magento2/issues/35906#issuecomment-1225229286

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by monteshot** [comment]
@magento run all tests

**Comment by monteshot** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by monteshot** [comment]
@magento run Functional Tests B2B

**Comment by monteshot** [comment]
Hi @alena-marchenko , @chernenm. Thank you for joining the review. Is everything okay with the PR?

**Comment by engcom-November** [comment]
Hi @monteshot 
Development team is currently working on this issue.
Thank you.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Unit Tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @monteshot,

It seems that the build failures are due to code changes. Please resolve them.

Thanks

**Comment by monteshot** [comment]
@magento run all tests

**Comment by monteshot** [comment]
@engcom-Hotel I have updated the code of test to newest version. Please review th PR again

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B,Functional Tests EE

**Comment by monteshot** [comment]
Following errors not suitable to this PR(bugfix for GraphQL)
image
image

**Comment by monteshot** [comment]
@magento run Functional Tests B2B Functional Tests EE

**Comment by monteshot** [comment]
@magento run Functional Tests EE

**Comment by monteshot** [comment]
@magento run Functional Tests B2B

**Comment by monteshot** [comment]
@magento run Functional Tests EE

**Comment by monteshot** [comment]
@magento run Functional Tests EE

**Comment by monteshot** [comment]
@magento run Functional Tests EE

**Comment by engcom-Lima** [comment]
Builds are green. Hence,moving this PR to **Merge in Progress.**

**Pull request merged**
