### PR TITLE
Context "isCustomer" should return false for Admin and Integration tokens

### LINKED ISSUE #29893: GraphQl context, extension attribute isCustomer returns true for Admin and Integration tokens
### Preconditions (*)

1. Have a token generated for admin user
2. Have a token generated for integration

### Steps to reproduce (*)

1. get the `$context` object that is passed into any GraphQl resolver
2. execute `$context->getExtensionAttributes()->getIsCustomer()` when the request uses the admin token, or the integration token

### Expected result (*)

1. `$context->getExtensionAttributes()->getIsCustomer()` will return `true`
2.

### Actual result (*)

1. `$context->getExtensionAttributes()->getIsCustomer()` should return `false`
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by pmarjan**
### Fixed Issues (if relevant)

1. [GraphQl context, extension attribute isCustomer returns true for Admin and Integration tokens](https://github.com/magento/magento2/issues/29893)

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
Code is fine in itself but is causing one functional test to fail.

**Comment by pmarjan** [comment]
> Code is fine in itself but is causing one functional test to fail.

@BarnyShergold all checks are fine now. (Functional tests can be flaky: meaning some of them the may pass or may not pass under the exact same circumstances)

**Review by BarnyShergold — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @BarnyShergold, thank you for the review.
[ENGCOM-8265](https://jira.corp.magento.com/browse/ENGCOM-8265) has been created to process this Pull Request
:eight_spoked_asterisk: @BarnyShergold, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by BarnyShergold** [comment]
Auto-Tests: Not Required

**Comment by gabrieldagama** [comment]
Hi @pmarjan, can you provide what is the use case for this issue/PR?

Tokens created in Magento aren't related to the customer, so the request is not related to any specific customer, I believe that is why it does return false.

Thankls.

**Comment by BarnyShergold** [comment]
@magento run Database Compare

**Comment by eduard13** [comment]
Looks like the issue has been already fixed in the following commit 336078e3b6b7cb6bc12b323505cce4176705417c.

Closing as not being actual anymore.

**Pull request closed without merging**
