### PR TITLE
#38659 - Fix order status update

### LINKED ISSUE #38659: [Issue] Cannot update Order status in 2.4.7
### Preconditions and environment

- Magento version 2.4.7

### Steps to reproduce

1. Try to update status from admin order page view

### Expected result

Status updated

### Actual result

Status not updated

### Additional information

I don't understand this change introduced in 2.4.7 : 
https://github.com/magento/magento2/issues/36562

```
private function getOrderStatus(string $orderStatus, string $historyStatus): string
    {
        return ($orderStatus === Order::STATE_PROCESSING || $orderStatus === Order::STATUS_FRAUD) ? $historyStatus
            : $orderStatus;
    }
```

Why would we be able to change status only if current status is processing or fraud ? (Also, `Order::STATE_PROCESSING` instead of `Order::STATUS_PROCESSING` )

If I understand correctly the issue #36562, the fix should be something like this instead : 
```
private function getOrderStatus(OrderInterface $order, string $historyStatus): string
    {
        $statuses = $this->orderConfig->getStateStatuses($order->getState());
        
        if (!in_array($status, array_keys($statuses))) {
            return $order->getStatus();
        }
        return $historyStatus;
    }
```

Or am I missing something ?

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Nuranto**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#38659

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Nuranto** [comment]
@magento run all tests

**Comment by pbrouwers** [comment]
@Nuranto can you include a revert of the broken code here? https://github.com/magento/magento2/commit/632f253106e0a2d68cbf0b5a58b12eeeb0a014bf

**Comment by Nuranto** [comment]
Actually, looking at this code, I wonder if we shouldn't take the opportunity to do a more thorough refactoring. This PR is a conveninent quick fix for the issue, but there's more to do :

The AddComment controller should use the OrderService::addComment service, and the state/status check that I added here should be done in the Order::addStatusHistory class. We will then need to revise the tests accordingly.... 

It's a too big task for me, especially without being sure that the PR will be approved, I think it would be worth asking for the opinion of the Magento architects.

What do you think ?

**Comment by YiffyToys** [comment]
So the static test is basically complaining about the @param in the method comment.
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38661/a1e071315a06ec25f7ffe9f8af1a0e82/Statics/console-error-logs.html


One of the unit tests looks interesting.
"Call to a member function getStateStatuses() on null"
That means "$order->getConfig()" was null.
I'm not sure that can happen outside a unit test. 
(The test may have failed to set up the order config.)
But it's easy to handle by just skipping the check to make the code bullet proof.
 ```
 $config =$order->getConfig()
 if (is_null($config)) {
    // TODO: log about order config being null and include order-id in the log message
     return $historyStatus;
 }
 $statuses =config->getStateStatuses($order->getState());
```
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38661/2eb55eff5d856c66daecb1d8c35717c3/Unit/allure-report-b2b/index.html#categories/79ed4d6211c69c293e7e7274e32246b1/15a9a1dca4ce89f4/

the B2B functional test looks like it was broken by something completely different and unrelated.
"CSS or XPath element with //section[@id='order-items']/div/div/button/span[text() = 'Add Products'] was not found."

same for the EE functional test
"There was '#super-product-table .product-item-name' element on page /api-grouped-product662a71e6e0ec82.html
+ <strong> Api Simple Product662a71e757c5d2
containing 'Api Simple Product662a71e757c5d2'"


The Web-API test could be unrelated. Maybe even the test itself is outdated.
"1) Magento\GraphQl\NegotiableQuote\SendNegotiableQuoteForReviewTest::testSendNegotiableQuoteCannotResend
Failed asserting that exception of type "Exception" is thrown."
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38661/120e2a1451cdcf961a7d5080c3da67a0/WebApi/console-error-logs.html

**Comment by YiffyToys** [comment]
So what developer is going to pick this up, make the 2 trivial changes and run the tests again?
As merchants we are a user and have enough work of our own.
(And no time to work our way through a complex Adobe license agreement to be allowed to clone the repository.)

**Comment by engcom-Hotel** [comment]
Hello @Nuranto,

As you said here https://github.com/magento/magento2/pull/38661#issuecomment-2079114792, more refactoring is required on this PR for now. Hence we are closing this PR. Please let us know whenever you are ready with this, we will reopen it.

Thanks

**Pull request closed without merging**
