### PR TITLE
fixed My account Address Book Additional Address Entries table issue #27335

### PR DESCRIPTION
**Pull request by abrarpathan19**
### Fixed Issues (if relevant)

1. magento/magento2#27335 My account Address Book Additional Address Entries table issue

### Manual testing scenarios (*)

1. Login to Luma theme front end -> My account -> Address Book -> Address Entries table
2. See the table head aliment issue in (Tablet, Desktop)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Review by edenduong — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @edenduong, thank you for the review.
[ENGCOM-7153](https://jira.corp.magento.com/browse/ENGCOM-7153) has been created to process this Pull Request

**Comment by abrarpathan19** [comment]
@edenduong Thanks for approving PR

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

See the screenshot made **BEFORE** switching to PR

pr 27336_before

and **AFTER** switching to the PR

pr 27336_after

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Pull request merged**
