### PR TITLE
Add PsrLogMessageProcessor to the default log handlers

### LINKED ISSUE #29943: [Issue] Add PsrLogMessageProcessor to the default log handlers
This issue is automatically created based on existing pull request: magento/magento2#29796: Add PsrLogMessageProcessor to the default log handlers

---------
### Description (*)
This pull request adds support for using [PSR-3 placeholders](https://www.php-fig.org/psr/psr-3/#12-message) (such as {variable_name}) in the default Magento 2 logs.

### Manual testing scenarios (*)
Add a named placeholder to a log message and the corresponding key to a context array.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by marcusirgens**
### Description (*)
This pull request adds support for using [PSR-3 placeholders](https://www.php-fig.org/psr/psr-3/#12-message) (such as {variable_name}) in the default Magento 2 logs.

### Manual testing scenarios (*)
Add a named placeholder to a log message and the corresponding key to a context array.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29943: Add PsrLogMessageProcessor to the default log handlers

### CODE REVIEW

**Comment by VladimirZaets** [comment]
@magento I am working on it

**Comment by marcusirgens** [comment]
An argument can be made against creating the processor in the constructor. We could modify these handlers to be created using DI instead of that's of interest.

**Comment by sidolov** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @marcusirgens,
Your changes looks good. Could you cover them with some kind of integration test?

**Comment by ihor-sviziev** [comment]
Hi @marcusirgens,
Will you be able to update your PR?

**Comment by engcom-Hotel** [comment]
Let me help with the test.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8332](https://jira.corp.magento.com/browse/ENGCOM-8332) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@sidolov test coverage still missing, so why you approved this pr?

**Comment by sidolov** [comment]
Hi @ihor-sviziev , it's a nice feature and we want to proceed with it, coverage will be added on the Extended Testing stage.

**Comment by ihor-sviziev** [comment]
@engcom-Bravo any updates on testing this PR? Is everything ok with it?

**Comment by ihor-sviziev** [comment]
@engcom-Bravo @sidolov, any updates?

**Comment by sidolov** [comment]
Hi @ihor-sviziev , this PR has P3 priority and it's currently postponed while we have PRs with higher priority in our backlog.

**Pull request closed without merging**
