### PR TITLE
MFTF: Add missing tests annotations

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Test Generation triggers tons of `DEPRECATION` notices
image

### Fixed Issues (if relevant)
N/A

### Related Pull Requests
https://github.com/magento/magento2/pull/26391
https://github.com/magento/partners-magento2b2b/pull/40
https://github.com/magento/partners-magento2ee/pull/124

### Manual testing scenarios (*)
1. `vendor/bin/mftf generate:tests`
2. You should see no notices.

### Questions or comments
Same commit for EE and B2B submitted.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
Severities received from @okolesnyk 
Related PRs
- https://github.com/magento/magento2/pull/26391
- https://github.com/magento/partners-magento2b2b/pull/40
- https://github.com/magento/partners-magento2ee/pull/124

**Comment by lbajsarowicz** [comment]
Important: Do not merge before https://github.com/magento/magento2/pull/26395 that is already merged to this branch.

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6620](https://jira.corp.magento.com/browse/ENGCOM-6620) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
