### PR TITLE
Fix broken link in README.md

### PR DESCRIPTION
**Pull request by samuel27m**
### Description (*)

Fixed broken link in README.md

### Manual testing scenarios (*)

1. Click the link "Magento System Requirements" link in README.md
2. It works

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-4661](https://jira.corp.magento.com/browse/ENGCOM-4661) has been created to process this Pull Request

**Review by mikeshatch — APPROVED** [review]
Good eye, samuel. There's also another broken link where it says "Bugcrowd researcher crowd." I tried to fix it myself, but it wouldn't allow me to.

**Comment by samuel27m** [comment]
@mikeshatch Do you know the specific URL? Maybe you could create a PR yourself to fix that one. There's also another one https://magento.com/security/reporting-magento-security-issue that just redirects to the same broken link you mentioned

**Comment by mikeshatch** [comment]
@samuel27m I haven't been able to do a Pull Request since Magento invited me to be a part of their organization. I haven't been able to figure it out yet. That's why I suggested it to you in case you were interested.

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Comment by mautz-et-tong** [comment]
@mikeshatch: The Bugcrowd link is already fixed here: https://github.com/magento/magento2/pull/22195

**Comment by mikeshatch** [comment]
> @mikeshatch: The Bugcrowd link is already fixed here: #22195

It was fixed before I noticed it, you mean? I still see this link as broken: https://bugcrowd.com/magento

**Comment by mautz-et-tong** [comment]
Bugcrowd was replaced with hackerone. That is why there is this PR: https://github.com/magento/magento2/pull/22195/files. So there is no need to take care on the broken link as it will be replaced.

**Comment by mikeshatch** [comment]
> Bugcrowd was replaced with hackerone. That is why there is this PR: 

I see. Thank you!

**Pull request merged**
