### PR TITLE
Resolved Can not save "CMS Block" with empty content issue 23800

### LINKED ISSUE #23800: Can not save "CMS Block" with empty content
**Fill All Required Field but can not save CMS Block.**

We can save the CMS Page with the empty content but we can not save 'CMS Block' with empty content. We should remove the validate in CMS Block form (**like the CMS Page**) (**And as  it displays - with no required symbol**).

### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Backend.
2. Select Content->Blocks->Add New Block
3. Fill all **required field** with '*'
4. Click Save

test

### Expected result (*)

1. Save successfully with the empty content
### Actual result (*)

1. No thing happened. No notification.

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#23800: Can not save "CMS Block" with empty content

**Fill all required field but Can not save CMS Block**

We can save the CMS Page with the empty content but we can not save 'CMS Block' with empty content. We should remove the validate in CMS Block form (**like the CMS Page**) (**And as  it displays - with no required symbol**).

Just removed the code in app/code/Magento/Cms/view/adminhtml/ui_component/cms_block_form.xml

### Fixed Issues (if relevant)

1. magento/magento2#23800: Can not save "CMS Block" with empty content

### Manual testing scenarios (*)

1. Go to Backend.
2. Select Content->Blocks->Add New Block
3. Fill all **required field** with '*'
4. Click Save

=> Save successfully

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @edenduong. Thank you for your contribution. Please, check my comments in the original issue. Thank you.

**Comment by edenduong** [comment]
Hello @rogyar,
Thank you for your feedback.
I think we can use the empty CMS block. Because the admin or developer can create the page with the empty block for the layout (the content staff can modify it later.). The layout with some empty block content which the staff can add it depends on their requirements. It may be useful for preparing the website page.
I see in the DB, that field also "Can be null":

image

As the CMS Page, I think we also can leave them empty .

**Comment by rogyar** [comment]
Hi @edenduong. That makes sense. Another use case that comes in mind is for some languages the store owner might want to have the content empty. Thank you for providing the additional info.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-5487](https://jira.corp.magento.com/browse/ENGCOM-5487) has been created to process this Pull Request
:eight_spoked_asterisk: @rogyar, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
