### PR TITLE
Fixed order information in print order, invoice, credit memo and shipment is not proper aligned #24393

### PR DESCRIPTION
**Pull request by rani-priya**
Fixed order information in print order, invoice, credit memo and shipment is not proper aligned #24393

### Fixed Issues (if relevant)

1. magento/magento2#24393: order information in print order, invoice, credit memo and shipment is not proper aligned

### Manual testing scenarios (*)

1. Place an order
2. Navigate to customer account section and open that order
3. Click on print order link
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @rani-webkul, please, sign CLA, otherwise, we can't process your pull request

**Comment by rani-priya** [comment]
Hi @VladimirZaets , I have signed CLA 3 times but here it's not showing. Could you please help?

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6049](https://jira.corp.magento.com/browse/ENGCOM-6049) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by sdzhepa** [comment]
@magento run all tests

**Review by krzksz — CHANGES_REQUESTED** [review]
Hey @rani-webkul, please check the failing tests.

**Comment by engcom-Charlie** [comment]
Hi @rani-webkul, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
