### PR TITLE
System configuration Validation for Customer/Admin Token life time

### LINKED ISSUE #29487: Customer Token Life in system config
This field should be save empty, but incorrect validation was applied. Because of that, admin user couldn't save the empty value.

### Preconditions (*)

1. Magento 2.4 CE

### Steps to reproduce (*)

1. Go to Stores > Settings > Configuration > Services > OAuth
2. Save Customer Token Lifetime (hours) without any value, Should be empty as mentioned in comment note

### Expected result (*)

1. configuration should save with empty value.

### Actual result (*)

1. [Screenshots, logs or description]
image

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by ejaz-alam**
### Description (*)
This field should be save empty, but incorrect validation was applied. Because of that, admin user couldn't save the empty value.

### Manual testing scenarios (*)

Without the fix
    Log in in the admin area
    Go to Stores -> Configurations -> Services -> OAuth.
    Save Customer Token Lifetime (hours) field without the value/empty.
    Save Admin Token Lifetime (hours) field without the value/empty.
    Did not saved the configuration without the integer value. 

With the fix
    Log in in the admin area
    Go to Stores -> Configurations -> Services -> OAuth.
    Save Customer Token Lifetime (hours) field without the value/empty.
    Save Admin Token Lifetime (hours) field without the value/empty.
    Configuration saved as mentioned in note comment.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)

### Resolved issues:
1. [x] resolves magento/magento2#29487: Customer Token Life in system config

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @aliejaz55. Could you check the same issue for the admin token lifetime, please? 

Also, according to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html), all changes should be covered by autotests. Could I ask you to create a simple MFTF test for this case. The idea of this test is to go to the corresponding settings tab in the admin panel, leave the token lifetime value empty, save the settings and make sure that no error appears. 

There's a [documentation](https://devdocs.magento.com/mftf/docs/introduction.html) of the MFTF framework itself. 

You can also check some examples from the recently merged PRs:

https://github.com/magento/magento2/pull/27371/files
https://github.com/magento/magento2/pull/27343/files
https://github.com/magento/magento2/pull/27029/files


And one more link for the best practices https://github.com/magento/magento-functional-tests-migration/wiki/Best-practices

Thank you!

**Comment by sidolov** [comment]
@magento create issue

**Comment by aliejaz55** [comment]
@rogyar for admin token, it has the same issue. I am working on it. Will be resolved soon.

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @aliejaz55. Thank you for collaboration. Do you have some updates regarding test coverage? If you need some help on it, please tell us

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by aliejaz55** [comment]
Yes @VladimirZaets please guide me on this. I have searched about MFTF, but it looks tbat I have to setup all my system for this. Please tell any middle way, that I can use now and in future pull requests.

**Review by ejaz-alam — COMMENTED** [review]
@rogyar please check this, removed required validation for admin token. Looking for some help in MFTF. That can also help me for future contribution.

**Comment by VladimirZaets** [comment]
@aliejaz55 [here](https://devdocs.magento.com/mftf/docs/introduction.html) is you can find the documentation, how to setup mftf framework locally and how to run tests. If you will have more specific questions, feel free to ask

**Comment by engcom-Kilo** [comment]
@aliejaz55 
Working with MFTF test

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8078](https://jira.corp.magento.com/browse/ENGCOM-8078) has been created to process this Pull Request

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8078](https://jira.corp.magento.com/browse/ENGCOM-8078) has been created to process this Pull Request

**Comment by engcom-Oscar** [comment]
:heavy_check_mark: QA Passed

### Preconditions:
1.Base Magento 2.4-develop installed.

### Steps to reproduce :
1. Log in in the admin area.
2. Go to Stores -> Configurations -> Services -> OAuth -> Access Token Expiration.
3. Empty 'Customer Token Lifetime (hours)' field and save config.
4. Empty 'Admin Token Lifetime (hours)' field and save config.

### Before :heavy_multiplication_x: 
Config is not saved. Incorrect validation applied. 

image


### After :heavy_check_mark:
Config saved successfully.

image

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8135](https://jira.corp.magento.com/browse/ENGCOM-8135) has been created to process this Pull Request

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by ejaz-alam** [comment]
@magento run all tests

**Comment by ejaz-alam** [comment]
@magento-engcom-team why the bug fix award removed?

**Pull request merged**
