### PR TITLE
[Backport]Fix-issue-19399-Add product customization option collapsible design issue

### PR DESCRIPTION
**Pull request by SyntaxKay**
### Original Pull Request
magento/magento2#19405

### Description (*)

Add product customization option collapsible design issue
### Fixed Issues (if relevant)

1.magento/magento2#19399 : Add product customization option collapsible design issu

### Manual testing scenarios (*)

1.Go to -> Catalog Product -> add product from backend
2.Go to -> customization option.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
Hi @speedy008. Thank you for the fix. We can accept changes to `2.2-develop` branch only if the changes are present in `2.3-develop` branch. Since the issue is reproducible on `2.3-develop` branch, please, consider creating the same PR to the `2.3-develop` branch and mark the current PR as backport (change the title). Thank you

**Comment by SyntaxKay** [comment]
Hi @rogyar 
I have updated this PR as Backport In 2.2-develop branch.
and created Origin PR in 2.3-develop branch.

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

**Pull request merged**
