### PR TITLE
Remove @SuppressWarnings and optimize imports on Category View

### PR DESCRIPTION
**Pull request by arnoudhgz**
### Description
Two @SuppressWarnings could be removed by splitting up the execute
method by moving logic to separate private methods.

Also the imports of this file are improved.

### Manual testing scenarios
1. Visit any category page, output should not be changed compared to before this change

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @arnoudhgz. Thank you for the refactoring. Please note that the unit tests should be adjusted correspondingly

**Comment by arnoudhgz** [comment]
@rogyar thank you for your feedback, I have overlooked this.. Will look into it asap

**Comment by arnoudhgz** [comment]
@rogyar should I also look into the Codacy thing? It is actually not a new issue.

**Review by orlangur — APPROVED** [review]
@arnoudhgz Codacy can be safely ignored in general (and I don't see what could be a better name here particularly).

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4818](https://jira.corp.magento.com/browse/ENGCOM-4818) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
