### PR TITLE
magento/adobe-stock-integration#1746: Corrected placeholders

### LINKED ISSUE #1746: Placeholders correction
- ui-select empty options placeholder should be corrected
 - keyword field placeholder should be corrected

### Steps to Reproduce 1
1. Open Media Gallery
2. Expand filter section
3. Open any ui-select filter

### Expected Result 1
Correct placeholder text is displayed when no options are loaded

### Steps to Reproduce 2
1. Open Media Gallery
2. Edit details for any image
3. See placeholder on the field preceding "Add New Tag" button

### Expected Result 2
The placeholder should be "New Tag" (instead of "New Keyword")

### PR DESCRIPTION
**Pull request by sivaschenko**
### Description (*)
 - corrected ui-select empty options placeholder
 - corrected keyword field placeholder

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/adobe-stock-integration/issues/1746

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sivaschenko** [comment]
The affected functionality is covered by MFTF tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-7998](https://jira.corp.magento.com/browse/ENGCOM-7998) has been created to process this Pull Request

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed 
Сorrected ui-select empty options placeholder
Peek 2020-08-12 11-54

Сorrected keyword field placeholder
Screenshot_79

**Pull request merged**
