### PR TITLE
Fix sales_email_order_items rendering

### PR DESCRIPTION
**Pull request by BrentRobert**
### Description (*)

This pull request fixes the rendering of the sales order items in emails. Due to strict mode the order variable gets stripped and is not available anymore.

### Fixed Issues (if relevant)

1. magento/magento2#26882: 2.3.4 Email Template New Pickup Order or add New Template order items are missing in Mail

### Manual testing scenarios (*)

1. Test with the default new order email.
2. Test with a new default template created in the backend.
3. Both scenario's should now render the order items.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by gwharton** [comment]
Feels very much like this fix is being applied at the wrong level. There is something more fundamental wrong here as the same problem is affecting shipment, invoice and credit memo emails too.

Look at the difference between legacy mode and normal mode for template processing. legacy mode works, normal mode doesn't.

**Comment by BrentRobert** [comment]
@gwharton this PR is supposed to fix the 'normal' mode for order items. Passing objects is just not allowed any more in normal mode as all passed variables need to be scalar for security reasons. Therefore I pass the ID of the order and retrieve the order.

This PR however does only fix the order items, not those of invoices etc..

**Comment by gwharton** [comment]
Hi Brent, oh yes. I see that now. My apologies. I've taken a look through the commits made back in Sept/Oct where the scalar variables only mode was introduced, quite extensive changes i see.

**Comment by gwharton** [comment]
Is the intention to extend this to include the others? or do we need another bug raising?

**Comment by gwharton** [comment]
Seems in the OrderSender.php we are still setting various objects in the transportobject which will no longer be accepted, e.g $store, $billing (is that object or array), $order. Shouldnt these be removed if they are no longer accepted by the template processor?

The variables section at the top of the email templates also needs work.

Are these entries still valid????




Seems like a perfect opportunity to make the data in the OrderSender match the variables available in the template.

**Comment by gwharton** [comment]
Note, the following files need looking at too

vendor/magento/module-sales/Model/Order/Email/Sender/CreditmemoCommentSender.php
vendor/magento/module-sales/Model/Order/Email/Sender/CreditmemoSender.php
vendor/magento/module-sales/Model/Order/Email/Sender/InvoiceCommentSender.php
vendor/magento/module-sales/Model/Order/Email/Sender/InvoiceSender.php
vendor/magento/module-sales/Model/Order/Email/Sender/OrderCommentSender.php
vendor/magento/module-sales/Model/Order/Email/Sender/OrderSender.php
vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentCommentSender.php
vendor/magento/module-sales/Model/Order/Email/Sender/ShipmentSender.php
vendor/magento/module-sales/Model/Order/Creditmemo/Sender/EmailSender.php
vendor/magento/module-sales/Model/Order/Invoice/Sender/EmailSender.php
vendor/magento/module-sales/Model/Order/Shipment/Sender/EmailSender.php

**Pull request closed without merging**
