### PR TITLE
[MFTF] Refactoring AdminMassOrdersHoldOnCompleteTest

### LINKED ISSUE #31515: [Issue] [MFTF] Refactoring AdminMassOrdersHoldOnCompleteTest
This issue is automatically created based on existing pull request: magento/magento2#31510: [MFTF] Refactoring AdminMassOrdersHoldOnCompleteTest

---------
### Description (*)
The test is refactored to improve execution time

### Manual testing scenarios (*)
1. Create an order
2. Invoice and ship the order
3. Go to the Orders Grid
5. Try to hold the order via mass update
6. Verify the result

### Related Pull Requests
https://github.com/magento/magento2/pull/31509

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
The test is refactored to improve execution time

### Manual testing scenarios (*)
1. Create an order
2. Invoice and ship the order
3. Go to the Orders Grid
5. Try to hold the order via mass update
6. Verify the result

### Related Pull Requests
https://github.com/magento/magento2/pull/31509

### Resolved issues:
1. [x] resolves magento/magento2#31515: [MFTF] Refactoring AdminMassOrdersHoldOnCompleteTest

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Comment by eduard13** [comment]
@magento run all tests

**Review by eduard13 — APPROVED** [review]
The failed tests do not seem to be related with these changes.

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8597](https://jira.corp.magento.com/browse/ENGCOM-8597) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
Manual QA not applicable for MFTF Refactoring PR. Moving it to _Extended testing_ column

**Comment by eduard13** [comment]
@magento run Integration Tests

**Comment by eduard13** [comment]
@magento run Functional Tests CE

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run Functional Tests B2B

**Comment by gabrieldagama** [comment]
@magento run Functional Tests B2B, Integration Tests

**Pull request merged**
