### PR TITLE
Solve couponcode error message break issue

### PR DESCRIPTION
**Pull request by mageprince**
### Description (*)

On checkout page coupon code validation message break when enter coupon like "test/"
### Fixed Issues (if relevant)

https://github.com/magento/magento2/issues/21353

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mageprince. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by miguelbalparda** [comment]
Does this happen with any other special char?

**Comment by mageprince** [comment]
@miguelbalparda No, this issue not raised with other special characters. This will happened only with "/" because API `/V1/guest-carts/:cartId/coupons/:couponCode` consider as new URL.

**Comment by ishakhsuvarov** [comment]
@mageprince Wouldn't it be better to encode this slash in some way instead of removing it completely?

**Comment by mageprince** [comment]
> @mageprince Wouldn't it be better to encode this slash in some way instead of removing it completely?

If we encode slash here then we also need to decode slash in `\Magento\Quote\Model\CouponManagement::set` which is not best way. becuase this function also used in other place like cart page which uses controller to pass the coupon code instead of API.

The main issue here is only with "/" if we enter coupon like "test/" then it will contain url like `http://www.example.com/rest/default/V1/carts/mine/coupons/test%2F` and which going to 404 not found.

**Comment by mageprince** [comment]
@miguelbalparda Any update on this PR ?

**Comment by josefbehr** [comment]
@mageprince if we can create such coupon codes (containing or ending in "/"), this issue is not solved by the PR. I'm trying to get clarification on this, until then I'll put this PR on hold.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @mageprince,
Looks like this PR got stuck. I'm trying to push it forward.

We have update in the issue description, so expected result was changed. More details https://github.com/magento/magento2/issues/21353#issuecomment-522711267

Could you update your PR according to new requirements?

**Comment by engcom-Golf** [comment]
Hi @mageprince could you please sign CLA ?, as we cannot proceed until you not signed.

**Comment by ihor-sviziev** [comment]
@mageprince  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
