### PR TITLE
15319 :  misleading data-container in product list

### PR DESCRIPTION
**Pull request by sunilit42**
Issue :- https://github.com/magento/magento2/issues/15319

Description 
 - change data-container class name based on view mode

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15350) <br/>All committers have signed the CLA.

**Comment by SubrataBauri** [comment]
@sunilit42 you have to sign the License CLA

**Comment by sunilit42** [comment]
@sidolov 

I did, please check it.

**Comment by sidolov** [comment]
Hi @sunilit42 , looks like changes to `Magento/Analytics/etc/adminhtml/system.xml` was added by mistake, please, revert this file.

**Comment by sunilit42** [comment]
@sidolov 
sorry for that.

i did revert back. please check it.

**Comment by magento-engcom-team** [comment]
Hi @sunilit42. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

Please, consider porting this solution across release lines.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
