### PR TITLE
[Backport] Fixed-Widget-left-navigation-block-2.2

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Description (*)

Original Issue: #20492
### Fixed Issues (if relevant)

1. magento/magento2#20493: In Admin configuration Widget left navigation block not proper in tablet landscape view
2. Magento 2.2

### Manual testing scenarios (*)

1. Admin configuration CONTENT->Widget->Add new widget
2. While filling form ,left navigation block have design issue in tablet view

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by VladimirZaets** [comment]
Hi @amol2jcommerce. Please note that changes to 2.2-develop branch can be accepted only if these changes are present in the 2.3-develop branch (https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html). Please, create a pull request to the 2.3-develop branch and rename this one as backport.

**Comment by amol2jcommerce** [comment]
Hi @VladimirZaets ,
Our pull request for 2.2-develop branch and 2.3-develop pull request is #20493

**Comment by amol2jcommerce** [comment]
Hi @VladimirZaets @magento-engcom-team please review.

**Comment by VladimirZaets** [comment]
Hi @amol2jcommerce. Why code in this PR is different from the original PR?

**Comment by amol2jcommerce** [comment]
Hi @VladimirZaets branch updated. please review.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4247](https://jira.corp.magento.com/browse/ENGCOM-4247) has been created to process this Pull Request

**Pull request merged**
