### PR TITLE
Added support for process fork to mview indexation

### PR DESCRIPTION
**Pull request by MateuszMesek**
### Description (*)

Added support for process fork to MView indexation

### Related Pull Requests

https://github.com/magento/magento2/pull/36155

### Fixed Issues (if relevant)

1. magento/magento2#38246

### Manual testing scenarios (*)

1. Prepare MView action and use `Magento\Indexer\Model\ProcessManager` inside
2. Set environment variable `MAGE_INDEXER_THREADS_COUNT=2`
3. Run `indexer_update_all_views` cron job

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by MateuszMesek** [comment]
@magento run all tests

**Comment by MateuszMesek** [comment]
@magento run all tests

**Review by andrewbess — APPROVED** [review]
Hello @MateuszMesek 
Thank you for your contribution
Fixes look nice for me
Approved

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Hello @MateuszMesek,

Thanks for the collaboration!

:x: QA not Passed

We are unable to reproduce the issue in the latest development branch 2.4-develop. Please refer to the below steps we have followed to reproduce the original issue:
1. Set up a vanilla instance with the latest development branch i.e. 2.4-develop.
2. Added `MAGE_INDEXER_THREADS_COUNT` and set its value as `4`
image

3. Run `bin/magento setup:upgrade`
4. Add products in the instance:
image

5. Start MySQL `show full processlist` with the interval of every 1 second with the command below to monitor the queries:
`mysqladmin --verbose -u root -p -i 1 processlist`

6. Run cron via the below command:
`bin/magento cron:run --group=index`

But the process went well and we do not see any `Delete` query in the process list.

Please let us know if we missed anything to reproduce the issue.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @MateuszMesek,

Have you had a chance to check this comment, https://github.com/magento/magento2/pull/38248#issuecomment-1935720379?

Thanks

**Comment by MateuszMesek** [comment]
Hello @engcom-Hotel 

This issue occurs only when Mview action use `Magento\Indexer\Model\ProcessManager`. 
Please check `Manual testing scenarios` in my first comment, https://github.com/magento/magento2/pull/38248#issue-2028972194

This issue can be reproduce only by prepare custom code, you can't reproduce in vanilla instance.

**Comment by MateuszMesek** [comment]
Hello @engcom-Hotel 

I updated code of your module to allow test our issue.

[Magz.zip](https://github.com/magento/magento2/files/14498141/Magz.zip)

My steps to replicate issue are:
- Install module
- Enable module
`./bin/magento mod:ena Magz_Merchandizing`
- Enable schedule mode of new indexer
`./bin/magento indexer:set-mode schedule merchandizing_popular`
- Add changes to changelog table
`INSERT INTO merchandizing_popular_order_cl (entity_id)
VALUES (1), (2), (3), (4), (5), (6), (7), (8);`
- Run indexer in multi threads mode
`MAGE_INDEXER_THREADS_COUNT=4 ./bin/magento cron:run --group=index --bootstrap=standaloneProcessStarted=1`

**Comment by engcom-Hotel** [comment]
Hello @MateuszMesek,

Thanks for the updated code, but the issue is still not reproducible for us with the latest development branch i.e. 2.4-develop. I request you to please try to reproduce the issue in the [latest development branch](https://github.com/magento/magento2) and let us know if this is still reproducible for you.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @MateuszMesek,

I trust you've reviewed this [comment](https://github.com/magento/magento2/pull/38248#issuecomment-1987966472). We are still unable to reproduce the issue with the latest development branch i.e. 2.4-develop. Kindly reconsider this and inform us if anything has been overlooked.

Thanks

**Comment by MateuszMesek** [comment]
Hello @engcom-Hotel 

Yes, I can still reproduce this issue on latest commit (c971859e7f82412dbc505086bc79469efa0908c2) in development branch 2.4-develop.

We have modified code of Magz_Merchandizing module to display processed ids in output in case when we call cron job.

On my local environment in case when I add list of ids to changelog table (`INSERT INTO merchandizing_popular_order_cl (entity_id) VALUES (1), (2), (3), (4), (5), (6), (7), (8);`)
And next when I call cron job then on output I see:
```
MAGE_INDEXER_THREADS_COUNT=4 ./bin/magento cron:run --group=index --bootstrap=standaloneProcessStarted=1

1
Ran jobs by schedule.
```
And inside var/log/cron.log file:
```
[2024-03-19T08:05:01.374918+00:00] main.CRITICAL: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.merchandizing_popular_order_cl__tmp65f9472d57b710_49733668' doesn't exist in /var/www/html/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php:90
```

Please remember about have installed pcntl module in PHP.
You can check if correct method was used by `Magento\Indexer\Model\ProcessManager` by add `var_dump(__METHOD__)` inside `simpleThreadExecute` and `multiThreadsExecute` methods of this class.
Output example in my local environment with this var_dump is:
```
MAGE_INDEXER_THREADS_COUNT=4 ./bin/magento cron:run --group=index --bootstrap=standaloneProcessStarted=1
string(57) "Magento\Indexer\Model\ProcessManager::multiThreadsExecute"

1
Ran jobs by schedule.
```

**Comment by engcom-Hotel** [comment]
Hello @MateuszMesek,

Appreciate your response!

Before I proceed, could you please resolve the conflicts? Once that's done, we can move forward with the next steps.

Thanks

**Comment by MateuszMesek** [comment]
@magento run all tests

**Comment by MateuszMesek** [comment]
@engcom-Hotel done

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Comment by engcom-Hotel** [comment]
Failed tests seem flaky to me. Please refer to the below screenshots for reference:

**_WebAPI Tests_**
<details>
_Test Run 1_

image

_Test Run 2_
image

</details>

_**Functional Tests B2B**_

<details>
_Test Run 1_

image

_Test Run 2_
image

</details>

Hence moving the PR into merge in progress.

**Pull request merged**
