### PR TITLE
Media gallery loaded twice

### PR DESCRIPTION
**Pull request by sidolov**
### Description (*)

1. Media gallery browser will send 2 requests for content after button click. 
2. Browser loading content every time when you open the tab.

### Fixed Issues (if relevant)

https://github.com/magento/adobe-stock-integration/issues/84

### Manual testing scenarios (*)

1. Log in to the admin panel
2. Navigate to Content -> Pages
3. Push `New page` button
4. Expand content tab
5. Push `Insert\Edit image` button, located on the editor
6. Push `Browse` button

**Expected result:** 
Content loaded. (in the browser dev tools we can see **one** request)

**Actual result:**
Content loaded. (in the browser dev tools we can see **two** requests)

7. Close the tab.
8. Push `Browse` button one more time

**Expected result:** 
Content loaded without any request because it was loaded before.

**Actual result:**
Content loaded. (in the browser dev tools we can see **two** requests)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-5418](https://jira.corp.magento.com/browse/ENGCOM-5418) has been created to process this Pull Request
:eight_spoked_asterisk: @orlangur, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @sidolov !

During testing, i faced an issue.

**Problem:** after re-opening "Insert/Edit image" tab the page darkens and is blocked(GIF attached).

**Manual testing scenario:**

1. Log in to the admin panel
2. Navigate to Content -> Pages
3. Push "New page" button
4. Expand content tab
5. Push "Insert\Edit image" button, located on the editor
6. Push "Browse" button
7. Close the tab.
8. Push Browse button one more time
9. Close the tab.
10. Close "Insert/Edit image" tab 
11. Push "Insert\Edit image" button again
12. Push "Browse" button
13. Close the tab.

**Actual Result:**
"Insert/Edit image" tab hidden.
The page darkens and is blocked.

GIF:


Could you take a look?

**Comment by sidolov** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sidolov. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sidolov, here is your [Magento instance](https://i-23621-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23621-2-3-develop.instances.magento-community.engineering/admin](https://i-23621-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sidolov** [comment]
@engcom-Alfa , I found the cause of the issue, it should be fixed now

**Review by orlangur — CHANGES_REQUESTED** [review]
LGTM but please squash changes

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-5418](https://jira.corp.magento.com/browse/ENGCOM-5418) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Review by orlangur — CHANGES_REQUESTED** [review]
@sivaschenko @sidolov can we get this squashed without retesting please?

**Review by sivaschenko — CHANGES_REQUESTED** [review]
`Magento\FunctionalTestingFramework.functional\PageBuilderWithWYSIWYG.SlideItemDeleteImage` is failing on this PR

**Comment by sivaschenko** [comment]
@magento run all tests

**Pull request merged**
