### PR TITLE
[backport 2.1] Category\Collection::joinUrlRewrite should use the store set on the collection

### PR DESCRIPTION
**Pull request by alepane21**
The problem is that Magento\Catalog\Model\ResourceModel\Category\Collection::joinUrlRewrite always use the store id from the store manager. I think that it should instead use the storeId set on the actual collection.

### Description
Now joinUrlRewrite uses directly the storeManager, but if a store is set directly on the collection, it should use the store set, and not the default passed by the store manager.
The method getStoreId(), if not set, already goes on fallback to the store manager and get the default, so it should be safe to directly use getStoreId().

### Fixed Issues (if relevant)

1. magento/magento2#13704: Category\Collection::joinUrlRewrite should use the store set on the collection

### Manual testing scenarios
I already provided an automated unit test. There is an code example in the related issue magento/magento2#13704.
It's my first automated test here, so I hope it's ok :)

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by alepane21** [comment]
@orlangur Now that I've fixed the tests, should also remove the on hold label?

Thanks!

**Comment by orlangur** [comment]
Hi @alepane21, it's `on hold` because PR to `2.2-develop` needs to be processed first. If there was a need to adjust tests, the label would be `needs update` :)

**Comment by alepane21** [comment]
Hi, could this be merged in the march milestone?

Thanks!

**Comment by dmanners** [comment]
Hi @alepane21 now that the original PR has been merged in. Would you be so kind as to update this PR with those changes and we can sort this out as well.

Thank you.

**Comment by magento-engcom-team** [comment]
Hi @alepane21. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.1.15 release.

**Pull request merged**
