### PR TITLE
Allow filter directive processors to be used with the Widget template filter

### LINKED ISSUE #29764: [Issue] Allow filter directive processors to be used with the Widget template filter
This issue is automatically created based on existing pull request: magento/magento2#28723: Allow filter directive processors to be used with the Widget template filter

---------
### Description (*)
This allows the use of filter directives with the `Magento\Widget\Model\Template\Filter` filter (which is used by CMS content). This makes extending the filter directives actually useful.

By applying the changes in this Pull Request, the following DI configuration also applies to this filter as well:
```xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Framework\Filter\Template">
        <arguments>
            <argument name="directiveProcessors" xsi:type="array">
                <item name="my-custom-directive" sortOrder="1000" xsi:type="object"><!--...--></item>
            </argument>
        </arguments>
    </type>
</config>
```

### Manual testing scenarios (*)
1. Create a custom filter directive via DI
2. See this filter directive now being applied for CMS pages and CMS blocks

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by theCapypara**
### Description (*)
This allows the use of filter directives with the `Magento\Widget\Model\Template\Filter` filter (which is used by CMS content). This makes extending the filter directives actually useful.

By applying the changes in this Pull Request, the following DI configuration also applies to this filter as well:
```xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Framework\Filter\Template">
        <arguments>
            <argument name="directiveProcessors" xsi:type="array">
                <item name="my-custom-directive" sortOrder="1000" xsi:type="object"><!--...--></item>
            </argument>
        </arguments>
    </type>
</config>
```

### Manual testing scenarios (*)
1. Create a custom filter directive via DI
2. See this filter directive now being applied for CMS pages and CMS blocks

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29764: Allow filter directive processors to be used with the Widget template filter

### CODE REVIEW

**Comment by Parakoopa** [comment]
It seems contributors can't add labels anymore. This is a partner contribution for "Tudock GmbH", could someone add the labels for that?

**Comment by Parakoopa** [comment]
@magento run all tests

**Comment by Parakoopa** [comment]
@magento-engcom-team The failing builds are not because of changes I made, it's just something old in the same file, what can I do about this?

**Comment by lenaorobei** [comment]
@magento create issue

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Hi @Parakoopa. Thanks for this improvement. 

Static builds work in a way that the whole content of changed file is being checked.

For this specific failure `The use of function html_entity_decode() is discouraged`: I believe it makes sense to add `// phpcs:ignore Magento2.Functions.DiscouragedFunction` annotation, since it is not related to your change.

Please consider also adding integration test to cover this behaviour.

**Comment by engcom-Charlie** [comment]
Hi @Parakoopa could you please take a look at https://github.com/magento/magento2/pull/28723#pullrequestreview-475815179?
Otherwise, we can't proceed with your PR.
Thank you.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by Parakoopa** [comment]
@engcom-Charlie I don't really understand why that test is failing now.

**Comment by lenaorobei** [comment]
Static tests pass now, but this change still requires additional test coverage. I believe, integration test would suit best.

**Comment by engcom-Charlie** [comment]
Hi @Parakoopa, can you please cover your changes by integration test?
Thank you.

**Comment by gabrieldagama** [comment]
The risk was set to`low` due to: the suggested changes shouldn't impact other areas.

**Comment by Parakoopa** [comment]
I will implement the integration tests as soon as I find the time for it.

**Comment by engcom-Charlie** [comment]
Hi @Parakoopa, do you have any updates about test coverage?
Thank you.

**Comment by Parakoopa** [comment]
I still have this on my TODO list.

**Comment by Parakoopa** [comment]
@magento run all tests

**Comment by Parakoopa** [comment]
@engcom-Charlie
Is there any update on this? I did the requested changes.

**Comment by theCapypara** [comment]
@magento-engcom-team Any updates?

**Comment by engcom-Charlie** [comment]
Hi @theCapypara,

Thank you for your contribution!

Once the PR will get reviewed from community members, it will move further.

Thank you!

**Comment by hostep** [comment]
I have the impression that this change is no longer needed since Magento 2.4.3 as a similar change was introduced in scope of https://github.com/magento/magento2/pull/31772 apparently.

So this PR can probably be closed if somebody could confirm this? Thanks! 🙂

**Comment by theCapypara** [comment]
To be honest it is a bit frustrating to contribute to Magento / Adobe Commerce if after 2 years this is the answer and there is still no word from the maintainers. I get that this is just a simple fix and I'm happy to see it fixed somewhere else, but it's still pretty discouraging that this keeps happening. I would love to some communication and quicker processing of Pull Requests in the future or I'll just re-consider whether or not it's worth to even contribute in the first place.

**Pull request closed without merging**
