### PR TITLE
Fixed - Need margin bottom to new Widget in Checkout/Cart Summary box

### PR DESCRIPTION
**Pull request by niravkrish**
### Description (*)

Added margin-bottom for static cms block widget after cart totals in luma and blank theme.

### Fixed Issues (if relevant)

1. magento/magento2#25703: Need margin bottom to new Widget in Checkout/Cart Summary box

### Manual testing scenarios (*)

1. Manual Testing

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by fabriciosobral** [comment]
Duplicated by [https://github.com/magento/magento2/pull/25729](url)

**Comment by niravkrish** [comment]
Hi, @fabriciosobral,

> Duplicated by [https://github.com/magento/magento2/pull/25729](url)

Please check your code first and then add this type of statement.
my code is completely different than your pull request.

Thank You,
Nirav Patel

**Comment by fabriciosobral** [comment]
I did, tks!

**Comment by krzksz** [comment]
Hey @niravkrish, thank you for your contribution both within this and https://github.com/magento/magento2/pull/25729. I'm going to close your PR this time and I asked Fabricio to follow the whole issue lifetime process to avoid such situations in the future.

**Pull request closed without merging**
