### PR TITLE
Remove php.ini sample

### PR DESCRIPTION
**Pull request by wiardvanrij**
### Description (*)

The current php.ini.sample is really outdated and is not really "mature".  It is simple to provide users with the basics, which is only things about memory_limit at the moment.  For the rest users should refer to the Magento2 version requirements.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18850) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @wiardvanrij. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by orlangur** [comment]
@wiardvanrij memory limit is already covered in Magento dev docs as well, why do we need this file at all then?

**Comment by wiardvanrij** [comment]
@orlangur Oh I agree, it would be better to remove it :) - updated

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3303](https://jira.corp.magento.com/browse/ENGCOM-3303) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @wiardvanrij. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Comment by ncioj10** [comment]
I think it is not very good to entirely remove this file. Is it possible to provide a updated version, as there are only bits of information flying around about this topic?

**Comment by orlangur** [comment]
@ncioj10 https://devdocs.magento.com/guides/v2.3/install-gde/prereq/php-settings.html should contain all the needed settings. If it's not true, it should be fixed instead of adding some file here.

**Pull request merged**
