### PR TITLE
[Backport] chore: remove old CSS fixes for IE

### PR DESCRIPTION
**Pull request by DanielRuf**
### Original Pull Request 
 https://github.com/magento/magento2/pull/19329

### Description (*)

This PR removes old CSS workarounds / fixes for IE.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
Hi @DanielRuf. Thank you for your collaboration. The code cleanup can be performed only for 2.3-develop branch for now. 2.2-develop is closed for cleanups (https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#rules)

**Comment by DanielRuf** [comment]
Okay, thanks for the information.

**Comment by Ctucker9233** [comment]
@rogyar I just looked at the contributor guide and it doesn't say 2.2 is closed to cleanups. It just says do everything in 2.3 first and then it can be backported.

**Comment by hostep** [comment]
@Ctucker9233:

Screenshot 2019-04-07 at 09 56 41

**Pull request closed without merging**
