### PR TITLE
fix Elastic Search interferes with the default sort order of products (changing newest first to oldest first)

### LINKED ISSUE #31043: Elastic Search interferes with the default sort order of products (changing newest first to oldest first)
### Preconditions (*)
1. Magento 2.4-develop
2. 2.3.5-p1 is all I have tested this in so far.

### Steps to reproduce (*)
- Create a category in Magento with several products in it, all have the position in the category set to the value 1
image

- Go to category page

### Expected result (*)
1. The newest products in the database (the one with the highest entity_id) are shown first
image
2. The Order by for the SQL query for retrieving the products
```
 SELECT `e`.*, `cat_index`.`position` AS `cat_index_position`, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`, `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_category_product_index_store1` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=1 AND cat_index.visibility IN(2, 4) AND cat_index.category_id=33
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.customer_group_id = 0 AND price_index.website_id = '1' ORDER BY `cat_index`.`position` asc, `e`.`entity_id` DESC
```

### Actual result (*)
1. The oldest products(with the lower entity_id) are shown first
image
2. The Order by for the SQL query for retrieving the products
```
SELECT `e`.*, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`, `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price`, IFNULL(review_summary.reviews_count, 0) AS `reviews_count`, IFNULL(review_summary.rating_summary, 0) AS `rating_summary`, `stock_status_index`.`stock_status` AS `is_salable` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.customer_group_id = 0 AND price_index.website_id = '1'
 LEFT JOIN `review_entity_summary` AS `review_summary` ON e.entity_id = review_summary.entity_pk_value AND review_summary.store_id = 1 AND review_summary.entity_type = (SELECT `review_entity`.`entity_id` FROM `review_entity` WHERE (entity_code = 'product'))
 INNER JOIN `cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id AND stock_status_index.website_id = 0 AND stock_status_index.stock_id = 1 WHERE (stock_status_index.stock_status = 1) AND (e.entity_id IN (1201, 1202, 1203)) ORDER BY FIELD(e.entity_id,1201,1202,1203)
```

:warning: **Note**: In Magento 2.3.6 with `Search Engine=MySQL` the newest product in the database (the one with the highest entity_id) was shown first. With Magento 2.4-develop with `Search Engine= Elasticsearch 7` this behaviour changed. The oldest product is shown first, the newest last.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

The severity of this issue will differ between niches but for some businesses, this is quite critical. Like designer or boutique fashion retailers where the target audience frequent the website to view the latest items to hit the fashion lines etc.

---

I can't believe there are not more reports of this... I did [ask the question](https://magento.stackexchange.com/questions/326729/elastic-search-v7-changing-magento-default-product-sort-position-in-categories) on Magento Stack Exchange and it is passed by will hardly any views and zero interaction.

I'm obviously assuming this is a bug and not meant to happen.

### PR DESCRIPTION
**Pull request by engcom-Charlie**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#31043

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by edenduong — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @edenduong, thank you for the review.
[ENGCOM-8834](https://jira.corp.magento.com/browse/ENGCOM-8834) has been created to process this Pull Request

**Comment by edenduong** [comment]
@magento run all tests

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
I believe such changes are causing a side effect and we need to review it, @engcom-Foxtrot, can you have a look at it? Thanks.

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by juhanihaapala** [comment]
This fix doesn't seem to work because the _id field is string thus it's not sorted as number. So the _id value should be changed to integer in elasticsearch to make this work. Or if I understood correctly it needs to be indexed as integer.

My test case I simplified the elastic search query:
```
{
  "stored_fields": [
    "_id",
    "_score"
  ],
  "sort": [
    {
      "_id": {
        "order": "desc"
      }
    }
  ],
  "query": {
    "bool": {
      "must": [
        {
          "terms": {
            "_id": [12899, 9738]
          }
        }
      ]
    }
  }
}
```


Which results:
```
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 2,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [
      {
        "_index" : "vaunuaitta_product_1_v2",
        "_type" : "document",
        "_id" : "9738",
        "_score" : null,
        "sort" : [
          "9738"
        ]
      },
      {
        "_index" : "vaunuaitta_product_1_v2",
        "_type" : "document",
        "_id" : "12899",
        "_score" : null,
        "sort" : [
          "12899"
        ]
      }
    ]
  }
}
```
When the expected would be hits be otherway.

**Comment by engcom-Alfa** [comment]
@magento give me 2.2.3 instance

**Comment by ishakhsuvarov** [comment]
Closing this PR for now as I can see multiple comments mentioning it violates coding standards and does not completely work as descibed.

Please feel free to reopen to continue working on it

**Pull request closed without merging**
