### PR TITLE
Fixed Backend Catalog Bundled products do not load when using Dutch language

### PR DESCRIPTION
**Pull request by mikeKots**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mikeKots** [comment]
@magento run all tests

**Comment by mikeKots** [comment]
@magento run all tests

**Comment by mikeKots** [comment]
@magento run Functional Tests CE

**Comment by manavluhar** [comment]
Hi @mikeKots, kindly update the description of this PR and mention the related issue if there is any relevant issue there.

**Comment by sdzhepa** [comment]
Hello @mikeKots 

Could you please provide more details in the description? like preconditions, steps to reproduce, actual/expected results any other additional information

It will help us to verify and process this issue/pr much more faster

Thank you in advance!

**Comment by sdzhepa** [comment]
Closed due to no response.

It is not clear the problem/bug that this PR should resove

**Pull request closed without merging**
