### PR TITLE
magento/magento2#12549: Payment method option is not showing under shopping cart rules condition tab.

### PR DESCRIPTION
**Pull request by p-bystritsky**
### Fixed Issues (if relevant)

1. magento/magento2#12549

### Manual testing scenarios (*)

1. Go to Marketing > Promotions > Cart Price Rules
2. Add New Rule
3. Open Conditions tab.
4. Payment Method option should be available as well as the Shipping Method etc.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @p-bystritsky. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by nuzil** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @nuzil. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @nuzil, here is your [new Magento instance](https://pr-20042.instances.magento-community.engineering).
Admin access: [https://pr-20042.instances.magento-community.engineering/admin](https://pr-20042.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3773](https://jira.corp.magento.com/browse/ENGCOM-3773) has been created to process this Pull Request

**Review by nuzil — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-3773](https://jira.corp.magento.com/browse/ENGCOM-3773) has been created to process this Pull Request

**Comment by thiagosantos** [comment]
Does the fix was sent to the 2.2-develop branch?
At the Magento 2.2.7, this options still not available.

**Comment by sivaschenko** [comment]
@thiagosantos after this pull request will be merged to 2.3, it can be ported to 2.2

**Comment by magento-engcom-team** [comment]
Hi @p-bystritsky. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Comment by thiagosantos** [comment]
> @thiagosantos after this pull request will be merged to 2.3, it can be ported to 2.2

@sivaschenko 
It was merged, will now be ported?

Best,

**Pull request merged**
