### PR TITLE
magento/magento2#3795: Validation messages missing from datepicker fo…

### PR DESCRIPTION
**Pull request by thanura-bi**
…rm elements

- New validation rule implemented to validate date range and added in to the cms page add/edit from

### Fixed Issues (if relevant)

1. magento/magento2#3795: Validation messages missing from datepicker form elements

### Manual testing scenarios

1. Edit a CMS Page 
2. Under custom design template section, select "To date" as an earlier date than "From date"
3. Then try to Save

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=17520) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @thanura-bi. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by dmanners** [comment]
Hi @VladimirZaets would you be able to help @thanura-bi figuring out what the best practice for this change would be?

**Comment by sidolov** [comment]
Hi @thanura-bi , please, sign CLA, otherwise, we can't process your pull request

**Comment by thanura-bi** [comment]
@VladimirZaets Any update on this pull request?

**Comment by thanura-bi** [comment]
@dmanners Do you know if there's anyone else to review this pull request?

**Comment by dmanners** [comment]
Hi @thanura-bi let me see.

**Comment by thanura-bi** [comment]
> Hi @thanura-bi let me see.

Thanks David!

**Review by orlangur — CHANGES_REQUESTED** [review]
Nowadays all changes must be applied to `2.3-develop` first (see https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules). Please prepare a new pull request, this one should be `on hold` until the latter is merged.

**Comment by orlangur** [comment]
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

**Pull request closed without merging**
