### PR TITLE
Declare module namespace before template path name

### PR DESCRIPTION
**Pull request by mage2pratik**
### Description
When we override block history(Magento\Sales\Block\Order\History) to my custom module.
It throws an error and finding order/history.phtml in my custom module.
I tried to extend Block Magento\Sales\Block\Order\History from my custom module.

```
1 exception(s):
Exception #0 (Magento\Framework\Exception\ValidatorException): Invalid template file: 'order/history.phtml' in module: 'Vendor_Module' block's name: 'sales.order.history'
```

### Fixed Issues (if relevant)

1. magento/magento2#16484: Declare module namespace before template path name(Magento_Sales::order/history.phtml).

### Manual testing scenarios
1. I override history block
`<preference for="Magento\Sales\Block\Order\History" type="Vendor\Module\Block\Order\History" />`

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by sidolov** [comment]
@magento-engcom-team combine 17176 17177 17178

**Comment by magento-engcom-team** [comment]
Hi @sidolov. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
@mage2pratik all pull requests have been successfully combined together: 
 - merged https://github.com/magento/magento2/pull/17176: [Backport] Updated Magento_Newsletter's block file.
 - merged https://github.com/magento/magento2/pull/17177: [Backport] Corrected Magento_Framework's test xml file.
 - merged https://github.com/magento/magento2/pull/17178: [Backport] hide cookie notice instead of reloading site

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your contribution. 
We will aim to release these changes as part of 2.1.15. 
Please check the release notes for final confirmation.

**Pull request merged**
