### PR TITLE
Fixed PHP 8.2 deprecation warnings: 'creation of dynamic property'.

### PR DESCRIPTION
**Pull request by hostep**
### Description (*)
This fixes PHP 8.2 deprecated usage of 'creation of dynamic property': https://www.php.net/manual/en/migration82.deprecated.php#migration82.deprecated.core.dynamic-properties

The phpstan tool is able to find these problems, here's a copy paste from https://github.com/magento/adobe-commerce-beta/issues/61 where I've reported this a few months ago during the Magento 2.4.6 beta period:

```
  172    Access to an undefined property Magento\Framework\Error\Processor::$_errorDir.
  173    Access to an undefined property Magento\Framework\Error\Processor::$_reportDir.
  186    Access to an undefined property Magento\Framework\Error\Processor::$_indexDir.
  268    Access to an undefined property Magento\Framework\Error\Processor::$_indexDir.
  269    Access to an undefined property Magento\Framework\Error\Processor::$_errorDir.
  454    Access to an undefined property Magento\Framework\Error\Processor::$_errorDir.
  472    Access to an undefined property Magento\Framework\Error\Processor::$_errorDir.
  475    Access to an undefined property Magento\Framework\Error\Processor::$_errorDir.
  611    Access to an undefined property Magento\Framework\Error\Processor::$_reportDir.
  732    Access to an undefined property Magento\Framework\Error\Processor::$_errorDir.
  176    Access to an undefined property Magento\ImportExport\Model\Export\Entity\AbstractEntity::$_storeIdToCode.
  179    Access to an undefined property Magento\ImportExport\Model\Export\Entity\AbstractEntity::$_storeIdToCode.
  354    Access to an undefined property Magento\ImportExport\Model\Export\Entity\AbstractEntity::$_invalidRows.
  512    Access to an undefined property Magento\ImportExport\Model\Export\Entity\AbstractEntity::$_invalidRows.
  430    Access to an undefined property Magento\Shipping\Model\Carrier\AbstractCarrier::$_result.
  40     Access to an undefined property Magento\Setup\Fixtures\FixturesAsserts\SimpleProductsAssert::$optionRepository.
```

### Related Pull Requests
- https://github.com/magento/magento-zend-loader/pull/1
- https://github.com/magento/magento-zend-db/pull/1
- https://github.com/magento/magento-zend-pdf/pull/1
- https://github.com/magento/magento2-functional-testing-framework/pull/905

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/adobe-commerce-beta/issues/61

In the wild, we've only ran into problems with deprecations in the `magento/magento-zend-pdf` library so far, none of the others we've triggered yet, but that doesn't mean you can't trigger them.

### Manual testing scenarios (*)
- Run `vendor/bin/phpstan analyse --level=0 {some-path}  | grep 'Access to an undefined property'` on all Magento code, it should not output anything (don't run this on the root the M2 codebase, otherwise it will take hours and might crash your computer if you don't have at least 32 GB of memory)
- Test all affected code and make sure that everything keeps working as expected (I'm assuming the automated tests will take care of this)

### Questions or comments
<del>I've used `protected` scoped members here and there, because I wanted to stay consistent with the existing members in the classes, but not sure if that's recommended and I should maybe change them to `private`?</del>
<del>_Update_: changed them to `private` because the semantic version check failed otherwise.</del>
_Update 2_: integration tests fail when `_storeIdToCode` is a `private` member in `AbstractEntity.php`, so changed it back to `protected` which solved the integration tests, however now the Semantic Version check fails again, but in my opinion, this one should be allowed...
_Update 3_: Same thing for the `$_result` in `AbstractCarrier`, had to change it back to `protected` to solve more integration tests.

The `public` scopes in `pub/errors/processor.php` are needed for the integration tests, they directly call those, so we can't make them `private`.

I won't write new automated tests, because I think that's not relevant in scope of this PR.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hostep** [comment]
@magento run all tests

**Comment by hostep** [comment]
@magento run all tests

**Comment by hostep** [comment]
Failing unit & functional tests seems to be not related to this PR.
Failing integration tests, I'm not sure, they look suspicious, but I can't seem to figure out how this PR broke them, so let's try them again...

@magento run Integration Tests

**Comment by hostep** [comment]
@magento run all tests

**Comment by hostep** [comment]
@magento run all tests

**Comment by hostep** [comment]
All integration tests should be good now (except for some flaky ones)

@magento run all tests

**Comment by hostep** [comment]
Rest of failing integration test + unit tests are due to some issue in the Usps module, nothing related to this PR.
Failures in functional tests don't look related at first sight (flaky tests probably)

Only the failure in the semantic version checker is related to this PR, that one will need approval I guess?

**Review by ihor-sviziev — APPROVED** [review]

**Comment by hostep** [comment]
Looked a bit more into the failing integration tests with the Usps module, and it might have been caused by changes in this PR. So added some more fixes, by changing accessibility of `$_result` in the `AbstractCarrier` from `private` to `protected` and removing it from all shipping models, since it's now inherited.

@magento run all tests

**Comment by hostep** [comment]
@magento run all tests

**Comment by hostep** [comment]
Alrighty, so that indeed fixed the integration tests, good 🥳 

Failures in functional tests don't look related at first sight (flaky tests probably)

Only the failures in the semantic version checker are related to this PR, those will need approval I guess..

**Review by ihor-sviziev — APPROVED** [review]

**Review by fredden — APPROVED** [review]

**Comment by glo71317** [comment]
Guys, I am processing this pull request internally! Thanks for the contribution!

**Pull request merged**
