### PR TITLE
[Typo] Update README.md

### PR DESCRIPTION
**Pull request by 4quaternion**
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15856) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=15856) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: 4quaternion<br/>:x: magento-engcom-team

**Comment by okorshenko** [comment]
`/combine 15857 15858 15859`

**Comment by okorshenko** [comment]
`/combine 15857 15858 15859`

**Comment by magento-engcom-team** [comment]
We got some errors while combining pull requests:
 - https://github.com/magento/magento2/pull/15859 : Base branch must be the same for target and source pull request
 - https://github.com/magento/magento2/pull/15857 : Can't merge https://github.com/magento/magento2/pull/15857 to https://github.com/magento/magento2/pull/15856
 - https://github.com/magento/magento2/pull/15858 : Can't merge https://github.com/magento/magento2/pull/15858 to https://github.com/magento/magento2/pull/15856

**Comment by okorshenko** [comment]
`/combine 15857 15858 15859`

**Comment by DanielRuf** [comment]
Please keep these PRs closed, they fix nothing.

**Comment by okorshenko** [comment]
Hi @DanielRuf please don't close this one. I'm working on it. Testing new feature for contributor assistance

**Comment by okorshenko** [comment]
`/combine 15857 15858 15859`

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on combining the pull requests for you

**Comment by DanielRuf** [comment]
Isn't it more consistent to have a command like the new testinstance command where we explicitely mention magento-engcom-team?

Makes more sense to me. Then we can also use

@magento-engcom-team help

like you would expect from a normal cli.

**Comment by magento-engcom-team** [comment]
We got some errors while combining pull requests:
 - https://github.com/magento/magento2/pull/15859 : Base branch must be the same for target and source pull request

**Comment by magento-engcom-team** [comment]
We got some errors while combining pull requests:
 - https://github.com/magento/magento2/pull/15857 : Can't merge https://github.com/magento/magento2/pull/15857 to https://github.com/magento/magento2/pull/15856
 - https://github.com/magento/magento2/pull/15858 : Can't merge https://github.com/magento/magento2/pull/15858 to https://github.com/magento/magento2/pull/15856

**Comment by magento-engcom-team** [comment]
We got some errors while combining pull requests:
 - https://github.com/magento/magento2/pull/15857 : Can't merge https://github.com/magento/magento2/pull/15857 to https://github.com/magento/magento2/pull/15856
 - https://github.com/magento/magento2/pull/15858 : Can't merge https://github.com/magento/magento2/pull/15858 to https://github.com/magento/magento2/pull/15856

**Comment by magento-engcom-team** [comment]
We got some errors while combining pull requests:
 - https://github.com/magento/magento2/pull/15859 : Base branch must be the same for target and source pull request

**Pull request closed without merging**
