### PR TITLE
[Backport] 2.2 develop pr port 19136

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Fixed Issues (if relevant)

1. #19136 
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by milindsingh** [comment]
Duplicate https://github.com/magento/magento2/pull/18524

**Comment by amol2jcommerce** [comment]
@milindsingh 
since backport PR is not using original commit , do not close my backport.

**Comment by DanielRuf** [comment]
The other is from the original commit author.

**Pull request closed without merging**
