### PR TITLE
Fixed issue: The header checkbox is selected on all remaining pages

### LINKED ISSUE #29996: The header checkbox is selected on all remaining pages
### Preconditions (*)

1. Magento 2.4-develop
2. Php v.7.3

### Steps to reproduce (*)

- Have at least 2 pages with customers in the grid

1. Go to Admin->Customers->All Customers;
2. Select all records on the current page by clicking the header checkbox;
3. Go to the second page;

### Expected result (*)

:heavy_check_mark: On the next page, the title checkbox should be empty 

### Actual result (*)

:heavy_multiplication_x: You will see that the header checkbox is selected on all remaining pages

after2

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by sarfarazbheda**
### Preconditions (*)
- Magento 2.4-develop
- Php v.7.3

### Description (*)

Fixed the issue related to the Admin grid for the Mass Selection, Filter, Search, and Pagination.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29996

### Manual testing scenarios (*)

Have at least 2 pages with customers in the grid
1. Go to Admin->Customers->All Customers;
2. Select all records on the current page by clicking the header checkbox;
3. Go to the second page;

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sarfarazbheda** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@magento run all tests

**Pull request closed without merging**
