### PR TITLE
[Backport]fixes-for-#20237-2-2

### PR DESCRIPTION
**Pull request by nainesh2jcommerce**
### Original Pull Request 
https://github.com/magento/magento2/pull/20237

### Description (*)

Backend: User Role Checkbox alignement.
### Fixed Issues (if relevant)

This is direct pull request as per Magento reviewer suggested,

### Manual testing scenarios (*)

1. Login into admin panel > System > User Roles > Click on Adminstrator User > Role User > Look checkbox alignment.
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-21319.instances.magento-community.engineering).
Admin access: [https://pr-21319.instances.magento-community.engineering/admin](https://pr-21319.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [Magento instance](https://i-21319-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21319-2-2-develop.instances.magento-community.engineering/admin](https://i-21319-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4319](https://jira.corp.magento.com/browse/ENGCOM-4319) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @nainesh2jcommerce , thanks for the backport! 

However, the original pull request is marked as a cleanup. We cannot accept cleanup pull requests to 2.2-develop. 

See [Contribution Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for details.

**Pull request closed without merging**
