### PR TITLE
Remove unnecessary spaces for code improvement

### PR DESCRIPTION
**Pull request by mage2pratik**
### Description

Remove unnecessary spaces for code improvement and to reduce file size.
### Fixed Issues (if relevant)

N/A

### Manual testing scenarios

N/A

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by nuzil** [comment]
@mage2pratik can you please provide source of this code standard? Cause current PHP documentation + PHP CS fixer are using space in this case.

**Comment by mage2pratik** [comment]
@nuzil I've updated current PR's title and description. In this PR, I've removed unnecessary spaces in couple of files to reduce file size.

**Comment by sidolov** [comment]
Hi @mage2pratik , unfortunately, we can't accept this pull request because there is no rule that not allows spaces in cases with typecasting. Benefit from reducing files size is insignificant compared with Magento distrib size and PR processing overhead. 
Thank you for your contribution!

**Pull request closed without merging**
