### PR TITLE
[Backport] Minor Typo fix in AbstractFilter.php

### PR DESCRIPTION
**Pull request by milindsingh**
### Original Pull Request 
 https://github.com/magento/magento2/pull/20005

### Description (*)

Minor  Typo in comment

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-3829](https://jira.corp.magento.com/browse/ENGCOM-3829) has been created to process this Pull Request

**Comment by orlangur** [comment]
Unfortunately, we can't accept such Pull Requests to 2.2 release line, all code cleanup like typos, spelling mistakes, etc should be delivered to 2.3 release line. For more information, please, refer to [Magento Code Contributions Guide](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#rules).

**Comment by ghost** [comment]
Hi @milindsingh, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+magento2+20200), it will take less than a minute. </br>Your feedback will help us to improve contribution process.

**Pull request closed without merging**
