### PR TITLE
fixed design issue on sales order view page frontend #24395

### PR DESCRIPTION
**Pull request by rani-priya**
### Fixed Issues (if relevant)

1. magento/magento2#24395: fixed design issue on sales order view page frontend

### Manual testing scenarios (*)

1. Place an order with even number of items
2. Go to customer account section and view the order

order-list-issue

### CODE REVIEW

**Comment by Stepa4man** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, here is your [new Magento instance](https://pr-24396.instances.magento-community.engineering).
Admin access: [https://pr-24396.instances.magento-community.engineering/admin](https://pr-24396.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by Stepa4man — APPROVED** [review]
@rani-webkul, thanks for your contribution.

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, thank you for the review.
[ENGCOM-5747](https://jira.corp.magento.com/browse/ENGCOM-5747) has been created to process this Pull Request
:eight_spoked_asterisk: @Stepa4man, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
