### PR TITLE
Resolve "Delete Template" and "Convert to Plain Text" confirm message (at Edit email template) should have the Magento Backend Design (issue 24082)

### LINKED ISSUE #24082: "Delete Template" and "Convert to Plain Text" confirm message (at Edit email template) should have the Magento Backend Design
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Backend
2. Marketing -> Email Templates
3. Create 1 email template
4. Edit the email template which is created
5. Click "Delete Template"
6. Click "Convert to Plain Text"

### Expected result (*)

1. 
image

2.
image

### Actual result (*)

1. 
image

2.
image

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#24082: "Delete Template" and "Convert to Plain Text" (at Edit email template) should have the Magento Backend Design

Solution: Use "Magento_Ui/js/modal/confirm" instead of use window.confirm

### Fixed Issues (if relevant)

1. magento/magento2#24082: "Delete Template" and "Convert to Plain Text" (at Edit email template) should have the Magento Backend Design

### Manual testing scenarios (*)

1. Go to Backend
2. Marketing -> Email Templates
3. Create 1 email template
4. Edit the email template which is created
5. Click "Delete Template"
6. Click "Convert to Plain Text"

#### Expected result

1. 
image

2.
image
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-24083.instances.magento-community.engineering).
Admin access: [https://pr-24083.instances.magento-community.engineering/admin](https://pr-24083.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @edenduong. Thanks for collaboration.
Will be great if you move all JS from `.phtml` template to `.js` file and use `x-magento-init` approach to inject JS into phtml.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5638](https://jira.corp.magento.com/browse/ENGCOM-5638) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-24083.instances.magento-community.engineering).
Admin access: [https://pr-24083.instances.magento-community.engineering/admin](https://pr-24083.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by edenduong** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
