### PR TITLE
magento/magento2#9685: Just display "saveable" Attributes in Customer…

### PR DESCRIPTION
**Pull request by avelikdusgg**
Admin Form

Render on customer form only saveable attributes.

### Description
Customer attribute will be rendered on  customer edit form in Admin panel,
if attribute is visible and assigned to adminhtml_customer from

### Fixed Issues (if relevant)
1. magento/magento2#9685: Just display "saveable" Attributes in Customer Admin Form

### Manual testing scenarios

1. See issue #9685 

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by dmanners** [comment]
Thank you @avelikdusgg for this PR. There are some failures on travis. Could you please look into these problems for us?

First Static test failures.

```
1) Magento\Test\Php\LiveCodeTest::testCodeStyle

PHP Code Sniffer detected 1 violation(s): 


FILE: ...magento/magento2/app/code/Magento/Customer/Model/Customer/DataProvider.php

--------------------------------------------------------------------------------

FOUND 1 ERROR AFFECTING 1 LINE

--------------------------------------------------------------------------------

 433 | ERROR | Line exceeds maximum limit of 120 characters; contains 124

     |       | characters

--------------------------------------------------------------------------------

2) Magento\Test\Php\LiveCodeTest::testCodeMess

PHP Code Mess has found error(s):

/home/travis/build/magento/magento2/app/code/Magento/Customer/Model/Customer/DataProvider.php:38	The class DataProvider has 18 fields. Consider redesigning DataProvider to keep the number of fields under 15.

/home/travis/build/magento/magento2/app/code/Magento/Customer/Model/Customer/DataProvider.php:356	The method getAttributesMeta() has a Cyclomatic Complexity of 10. The configured cyclomatic complexity threshold is 10.
```

Secondly there are 2 unit test failures that I think are down to not mocking the required methods.

```
There were 2 errors:


1) Magento\Customer\Test\Unit\Model\Customer\DataProviderTest::testGetDataWithVisibleAttributes

Error: Call to a member function getAttributes() on null


/home/travis/build/magento/magento2/app/code/Magento/Customer/Model/Customer/DataProvider.php:433

/home/travis/build/magento/magento2/app/code/Magento/Customer/Model/Customer/DataProvider.php:414

/home/travis/build/magento/magento2/app/code/Magento/Customer/Model/Customer/DataProvider.php:362

/home/travis/build/magento/magento2/app/code/Magento/Customer/Model/Customer/DataProvider.php:211

/home/travis/build/magento/magento2/lib/internal/Magento/Framework/TestFramework/Unit/Helper/ObjectManager.php:162

/home/travis/build/magento/magento2/app/code/Magento/Customer/Test/Unit/Model/Customer/DataProviderTest.php:1211


2) Magento\Customer\Test\Unit\Model\Customer\DataProviderTest::testGetDataWithVisibleAttributesWithAccountEdit

Error: Call to a member function getAttributes() on null


/home/travis/build/magento/magento2/app/code/Magento/Customer/Model/Customer/DataProvider.php:433

/home/travis/build/magento/magento2/app/code/Magento/Customer/Model/Customer/DataProvider.php:414

/home/travis/build/magento/magento2/app/code/Magento/Customer/Model/Customer/DataProvider.php:362

/home/travis/build/magento/magento2/app/code/Magento/Customer/Model/Customer/DataProvider.php:211

/home/travis/build/magento/magento2/lib/internal/Magento/Framework/TestFramework/Unit/Helper/ObjectManager.php:162

/home/travis/build/magento/magento2/app/code/Magento/Customer/Test/Unit/Model/Customer/DataProviderTest.php:1284
```

**Comment by avelikdusgg** [comment]
@dmanners 
Thank you. I will check errors.

**Comment by okorshenko** [comment]
Hi @avelikdusgg could please let us know if you would like to proceed with this PR?

**Comment by magento-engcom-team** [comment]
@avelikdusgg we are closing this Pull Request now due to inactivity. If you'd like to update it, please reopen.
Additionally, issue #9685 seems to be resolved now.

**Comment by magento-engcom-team** [comment]
Hi @avelikdusgg. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

**Pull request closed without merging**
