### PR TITLE
Fix: cms breadcrumbs localization

### PR DESCRIPTION
**Pull request by coresh**
### E.g: for ```ru_RU``` locale (Not localized):

```Главная >  About Us```
### Screenshot -> not localized breadcrumbs:
Screenshot-20190714120436-305x68

### But expected (Localized):

```Главная >  О нас```
### Screenshot -> localized breadcrumbs:
Screenshot-20190714130345-351x74

### Magento Community edition (Fixed):
```vendor/magento/module-cms/Block/Page.php:159```
### Magento Commerce edition (Should be fixed:)
```vendor/magento/module-versions-cms/Block/Cms/Page.php:113```
### before fix:
```            $breadcrumbsBlock->addCrumb('cms_page', ['label' => $page->getTitle(), 'title' => $page->getTitle())];```
### after fix:
```            $breadcrumbsBlock->addCrumb('cms_page', ['label' => __($page->getTitle()), 'title' => __($page->getTitle())]);```

### Manual testing scenarios

1. Opening any custom created CMS page
2. Checking breadcrumbs

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23695) <br/>All committers have signed the CLA.

**Comment by coresh** [comment]
### All checks have passed:
Please merge the pull request.

Thank you

**Comment by hostep** [comment]
Hmm, I think this is not correct.
The idea is that you translate cms content by creating multiple pages in different languages in the backend.
So in this case, you could simply change the title of the cms page from 'About Us' to 'О нас' in the backend of Magento, right?

**Comment by coresh** [comment]
> Hmm, I think this is not correct.
> The idea is that you translate cms content by creating multiple pages in different languages in the backend.
> So in this case, you could simply change the title of the cms page from 'About Us' to 'О нас' in the backend of Magento, right?

Exactly.

The current Magento 2 statement:
For each locale should be created a separated page for the specified locale including
breadcrumbs (Page Title).

Auto localizations of cms breadcrumbs would be comfortable, but,
IMO: to following the current Magento 2 CMS pages localization behavior the current pull request should be closed without merging.

Thank you

**Pull request closed without merging**
