### PR TITLE
[#2291]:+ fixed inconsistent plugin placement

### PR DESCRIPTION
**Pull request by StevenGuapaBV**
Fixed folder structure for plugins to be placed in a root Plugin folder. Also removed duplicate plugins in adminhtml di which were already present in etc/di

### Description
To be consistent in the location where plugins are kept I updated the module CatalogUrlRewrite where a some model plugins where not in the Plugins root folder. 

### Fixed Issues (if relevant)
1. magento/magento2#2291: Inconsistent location for plugins

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @StevenGuapaBV. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by orlangur** [comment]
@StevenGuapaBV would be really nice to enforce plugin placement with a static test.

**Comment by StevenGuapaBV** [comment]
@orlangur I will try to make time for that soon. Don't think this pull request is the best place to add that static test, but I can make a new one for that.

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-2483](https://jira.corp.magento.com/browse/ENGCOM-2483) has been created to process this Pull Request

**Review by miguelbalparda — CHANGES_REQUESTED** [review]
The tests seems to be failing because of your changes, can you check that please?

**Comment by sidolov** [comment]
Hi @StevenGuapaBV , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
