### PR TITLE
Added unique key on eav_attribute_option_value table

### LINKED ISSUE #24718: Missing unique key on eav_attribute_option_value table
This is similar to #24581 but for the table `eav_attribute_option_value`
### Summary (*)
The table `eav_attribute_option_value` does not have a unique index on the column pair (`option_id`, `store_id`).  
There is no reason for an option to have 2 values for the same store so this should be restricted.  

_Also layered navigation disappears on frontend._

**Relates issues:**
https://github.com/magento/magento2/issues/24581 
https://github.com/magento/magento2/issues/24718

### Examples (*)
Same as #24581, if by any faulty code an option gets 2 values for the same store view this causes a lot of issues when editing product / attributes / maybe others.
### Proposed solution
add a unique key on the column pair (`option_id`, `store_id`) on the table `eav_attribute_option_value`

```
    <table name="eav_attribute_option_value">
       ......
        <constraint xsi:type="unique" referenceId="EAV_ATTRIBUTE_OPTION_VALUE_OPTION_ID_STORE_ID_UNIQUE">
            <column name="store_id"/>
            <column name="option_id"/>
        </constraint>
    </table>
```

### PR DESCRIPTION
**Pull request by UncleTioma**
### Description (*)

Added unique key on `eav_attribute_option_value` table
### Fixed Issues (if relevant)

1. magento/magento2#24718: MIssing unique key on eav_attribute_option_value table

### Manual testing scenarios (*)

1. Installed fresh magento2.3-develop and the unique key was missing
2. After added the unique key to table reinstall Magento and its fixed.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by orlangur — APPROVED** [review]

**Review by orlangur — CHANGES_REQUESTED** [review]
Please squash changes into a single commit so that we have perfectly clean history 😉

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-5956](https://jira.corp.magento.com/browse/ENGCOM-5956) has been created to process this Pull Request
:eight_spoked_asterisk: @orlangur, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5956](https://jira.corp.magento.com/browse/ENGCOM-5956) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
