### PR TITLE
Ensure Quote::collectTotals() correctly handles recursion

### LINKED ISSUE #37856: [Issue] Ensure Quote::collectTotals() correctly handles recursion
This issue is automatically created based on existing pull request: magento/magento2#36475: Ensure Quote::collectTotals() correctly handles recursion

---------
### Description
We have written a plug-in for a shipping method. Our plugin requires access the quote object to perform its business logic. We get a reference to the current quote object by calling `Magento\Checkout\Model\Session::getQuote()`. This works correctly and we get a reference to the quote object and can perform the required actions.

Within `Magento\Checkout\Model\Session::getQuote()`, there is a call to `$quote->collectTotals()`. When this runs via our plug-in, Magento ends up calling `$quote->collectTotals()` within an existing call to `$quote->collectTotals()` (recursion). This becomes a problem when we introduce gift cards, which is a feature of Adobe Commerce. Because we are applying the gift cards each time `$quote->collectTotals()` is called, but the second time around the gift cards are already 'used', so they do not get applied to the `$quote`, and therefore disappear from the checkout.

### Manual testing scenarios
Preconditions:
- Adobe Commerce with Gift Card Accounts feature
- Gift card with an available balance less than the total of the cart
- A plug-in within the shipping method totals collection which calls `Magento\Checkout\Model\Session::getQuote()`

Steps to reproduce:
1. Add items to cart to ensure cart total is more than available balance on gift card
1. Apply gift card at cart
1. Proceed to payment step in checkout
1. Notice gift card is applied correctly
1. Select payment method multiple times
1. Notice gift card is (not) applied correctly

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fredden**
### Description
We have written a plug-in for a shipping method. Our plugin requires access the quote object to perform its business logic. We get a reference to the current quote object by calling `Magento\Checkout\Model\Session::getQuote()`. This works correctly and we get a reference to the quote object and can perform the required actions.

Within `Magento\Checkout\Model\Session::getQuote()`, there is a call to `$quote->collectTotals()`. When this runs via our plug-in, Magento ends up calling `$quote->collectTotals()` within an existing call to `$quote->collectTotals()` (recursion). This becomes a problem when we introduce gift cards, which is a feature of Adobe Commerce. Because we are applying the gift cards each time `$quote->collectTotals()` is called, but the second time around the gift cards are already 'used', so they do not get applied to the `$quote`, and therefore disappear from the checkout.

### Manual testing scenarios
Preconditions:
- Adobe Commerce with Gift Card Accounts feature
- Gift card with an available balance less than the total of the cart
- A plug-in within the shipping method totals collection which calls `Magento\Checkout\Model\Session::getQuote()`

Steps to reproduce:
1. Add items to cart to ensure cart total is more than available balance on gift card
1. Apply gift card at cart
1. Proceed to payment step in checkout
1. Notice gift card is applied correctly
1. Select payment method multiple times
1. Notice gift card is (not) applied correctly

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37856: Ensure Quote::collectTotals() correctly handles recursion

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

**Comment by convenient** [comment]
Not a Magento maintainer, but spotted this and I have worked on something similar before.

https://github.com/magento/magento2/pull/18678

What is the first thing to initiate collectTotals when you grab it from the session? Is it when it detects a currency code change?

**Comment by fredden** [comment]
The stack trace / code paths that I'm looking at in this particular case are as follows. (I've taken all the interceptors out and removed lots of around\* plug-ins which didn't seem relevant.)

- HTTP POST to REST API
- `Magento\Checkout\Model\PaymentInformationManagement->savePaymentInformation()`
- `Magento\Quote\Model\PaymentMethodManagement->set()`
- `Magento\Quote\Model\Quote\Payment->importData()`
- `Magento\Quote\Model\Quote->collectTotals()`
- `Magento\Quote\Model\Quote\TotalsCollector->collect()`
- `Magento\Quote\Model\Quote\TotalsCollector->collectAddressTotals()`
- `Magento\Quote\Model\Quote\Address\Total\Shipping->collect()`
- `Magento\Quote\Model\Quote\Address->collectShippingRates()`
- `Magento\Quote\Model\Quote\Address->requestShippingRates()`
- `Magento\Shipping\Model\Shipping->collectRates()`
- `Magento\Shipping\Model\Shipping->collectCarrierRates()`
- `ShipperHQ\Shipper\Model\Carrier\Shipper->collectRates()`
- `ShipperHQ\Shipper\Model\Carrier\Shipper->setRequest()`
- `ShipperHQ\Shipper\Model\Carrier\Processor\ShipperMapper->getShipperTranslation()`
- `Merchant\Module\Plugin\NotRelevantClassName->afterGetCartDetails()`
- `Magento\Checkout\Model\Session->getQuote()`
- `Magento\Quote\Model\Quote->collectTotals()`

The problem we were investigating is to do with gift cards being assigned to the quote on the first run (which is the inner call) and then being 'used up' by the time the totals are collected for that particular collector the second run (in the outer call). When there's only one call to `Magento\Quote\Model\Quote\TotalsCollector->collect()` (which is in `...\Quote->collectTotals()`, after the flag check), the gift card gets applied correctly.

I'm not aware of any currency code changes in this stack / process.

**Comment by convenient** [comment]
Ahhh interesting @fredden 

So this does not actually cause an infinite loo?  just an additional call to `collectTotals`? 🤔 I think my original case may not have caught this due to how the rest api instantiates the quote separately from the checkout session singleton.

Historically I have worked around this kind of thing by getting the quote from the plugin/event object rather than trying to grab it from the session, and it seems others have [posted similar on stack exchange](https://magento.stackexchange.com/a/340050/17176). Just in case you wanted to review alternate considerations

**Comment by ilnytskyi** [comment]
In my opinion the quote model works ok. 
```
Magento\Quote\Model\Quote->collectTotals()
```
If you need to recollect totals you can reset that via flag.
Instead of using method that triggers additional checks
```
Magento\Checkout\Model\Session::getQuote()
```
You can just extract quote id from 
```
Magento\Checkout\Model\Session::getQuoteId()
```
or other objects that available inside your plugin
```
Merchant\Module\Plugin\NotRelevantClassName->afterGetCartDetails()
```
and load from chace in `QuoteRepository`. Then you have same object intact.

Additionally `Magento\Checkout\Model\Session` caches quote in its own property so there is a risk that if some code performs saves or does not handle clearing of `Magento\Checkout\Model\Session` state you might end up with unexpected behaviour like this.

**Comment by fredden** [comment]
@ilnytskyi & @convenient, would you suggest changing this to `throw` an error instead of mask the duplicate call? If so, I'll investigate this, and also look to change how the session gets the quote object, to avoid this scenario going forward.

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, Unit Tests, WebAPI Tests

**Review by engcom-Hotel — APPROVED** [review]
Hello @fredden,

Failed tests seem flaky to me, and changes seem fine. Hence approving the PR.

Thanks

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests B2B,Functional Tests CE,Unit Tests,WebAPI Tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests B2B,Functional Tests CE

**Comment by engcom-Hotel** [comment]
Hello @fredden,

We are unable to reproduce the issue mentioned here. Please go through this comment https://github.com/magento/magento2/issues/37856#issuecomment-1677233938 and let us know in case we have missed anything.

Meanwhile, we are putting this issue `On Hold`.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @fredden,

We are closing this PR for now as the original issue is not reproducible for us. Please go through with the comment here https://github.com/magento/magento2/issues/37856#issuecomment-1677233938.

Feel free to reopen it and let us know if we have missed anything in order to reproduce the issue.

Thanks

**Pull request closed without merging**
