### PR TITLE
Fixed condition for products list widget

### PR DESCRIPTION
**Pull request by hryvinskyi**
Steps to Reproduce
- Create new Magento instance with sample data
- Edit cms block Home Page
- Edit widget product list (Hot Sellers) and add a condition product attribute "Description" contains "The"

Expected result: products are displayed for which description contains "The"
Actual result: products no displayed

### CODE REVIEW

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @hryvinskyi. Thank you for your collaboration. Could you, please, extend the description by providing information about the issue you are trying to solve with your change? I assume the bug is with the widget rule when you try to create a condition on an attribute type text but it would be very helpful if you could provide steps to reproduce in the description as well. 

Thank you!

**Comment by hryvinskyi** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @hryvinskyi. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @hryvinskyi, here is your [new Magento instance](https://pr-29061.instances.magento-community.engineering).
Admin access: [https://pr-29061.instances.magento-community.engineering/admin_9347](https://pr-29061.instances.magento-community.engineering/admin_9347)
Login: `d27ca57f` Password: `7f2c9e2bd75c`
Instance will be terminated in up to 3 hours.

**Comment by hryvinskyi** [comment]
Hi @rogyar. 

> I assume the bug is with the widget rule when you try to create a condition on an attribute type text

Yes exactly.

#### Reproduce

1. Create new magento instance with sample data
2. Edit cms block Home Page
3. Edit widget product list (Hot Sellers) and add a condition product attribute "Description" contains "The"

Expected result: products are displayed for which description contains "The"
Actual result: products no displayed

**Comment by rogyar** [comment]
Hi @hryvinskyi. Got it, thank you for the explanation. I've updated the PR description correspondingly. 
According to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all new changes should be covered by autotests. Could I kindly ask you to cover your modification to the system behavior by an integration or MFTF test, please? 

Thank you.

**Comment by hryvinskyi** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Echo. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Echo, here is your [new Magento instance](https://pr-29061.instances.magento-community.engineering).
Admin access: [https://pr-29061.instances.magento-community.engineering/admin_366f](https://pr-29061.instances.magento-community.engineering/admin_366f)
Login: `36e6a6bb` Password: `9dea34177733`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Echo** [comment]
Hi @hryvinskyi. Thank you for your report.
Unfortunately, I can't reproduce this issue.

Step to reproduce:
Content->Elements->Pages
Edit "Home page"
Add widget to content
On "Insert Widget" page:
Widget Type selected "Catalog Products List"
Create Conditions - "Description  contains  army"
Click "Insert Widget" and Save "Home Page"
Go to Storefront
Products whose description contains the text "army" are displayed

image
image
image

Please update your description or provide more details for this issue.

**Comment by hryvinskyi** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @hryvinskyi. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @hryvinskyi, here is your [new Magento instance](https://pr-29061.instances.magento-community.engineering).
Admin access: [https://pr-29061.instances.magento-community.engineering/admin_898e](https://pr-29061.instances.magento-community.engineering/admin_898e)
Login: `798035b2` Password: `eefbcb46ea8b`
Instance will be terminated in up to 3 hours.

**Comment by VladimirZaets** [comment]
@hryvinskyi hi, do you have any update on it?

**Comment by engcom-Echo** [comment]
Hi @hryvinskyi , I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
