### PR TITLE
magento/magento2#14623: Join extension attributes are not added to Or…

### LINKED ISSUE #14623: Join extension attributes are not added to Order and Order Items
### Preconditions

1. Magento 2.1.3
2. 7.0.25-0ubuntu0.16.04.1

### Steps to reproduce

1. Define a Extension attribute for the relevant interfaces with a join table:
```xml
    <extension_attributes for="Magento\Sales\Api\Data\OrderItemInterface">
        <attribute code="some_id" type="string">
            <join reference_table="SOMETABLE" join_on_field="item_id" reference_field="item_id">
                <field>some_id</field>
            </join>
        </attribute>
    </extension_attributes>
    <extension_attributes for="Magento\Sales\Api\Data\OrderInterface">
        <attribute code="some_id" type="string">
            <join reference_table="SOMETABLE" join_on_field="quote_id" reference_field="quote_id">
                <field>some_id</field>
            </join>
        </attribute>
    </extension_attributes>
```
2. Make sure there's matching data in the SOMETABLE table and the sales_order_item table
3. Request order(s) or order items via REST

### Expected result

1. The "some_id" attribute should be included in the response for orders and order items

### Actual result

1. The extension attribute is not included in any of the two responses

This was partially fixed in #8035, but only for order search results

### PR DESCRIPTION
**Pull request by Kiraberos**
- fixed issue associated with joining extension attributes for Order and Order items

### Description (*)

According to #14623 and added processing of extension attributes when joining to Order and Orders items.

### Related Pull Requests
No

### Fixed Issues (if relevant)

1. Fixes magento/magento2#14623

### Manual testing scenarios (*)

1. Defined an Extension attribute for the relevant interfaces with a join table in the custom module
2. I made sure that the SOMETABLE table and the sales_order_item table have matching data:
- Orders
image
- Order items
image
3. Requested order(s) or order items via REST (used swagger)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Kiraberos** [comment]
@magento run all tests

**Comment by Kiraberos** [comment]
@magento run Unit Tests

**Comment by Kiraberos** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by Kiraberos** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Comment by Kiraberos** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Comment by Kiraberos** [comment]
@magento run all tests

**Comment by Kiraberos** [comment]
@magento run all tests

**Comment by Kiraberos** [comment]
@magento run Functional Tests EE, Integration Tests

**Comment by Kiraberos** [comment]
@magento run Integration Tests

**Comment by Kiraberos** [comment]
@magento run Integration Tests

**Comment by Kiraberos** [comment]
@magento run Integration Tests

**Comment by Kiraberos** [comment]
@magento run Integration Tests

**Comment by Kiraberos** [comment]
@magento run Integration Tests

**Comment by Kiraberos** [comment]
@magento run Integration Tests

**Comment by Kiraberos** [comment]
@magento run Integration Tests

**Comment by Kiraberos** [comment]
@magento run Integration Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by Kiraberos** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
Hello @Kiraberos,

Thanks for the contribution!

As part of the review process, we have tried to reproduce the actual issue in the 2.4-develop branch but the issue is not reproducible for us. 

We have created a custom attribute with the name `customer_dob` and we are able to get the same this attribute with `V1/orders/{ID}` API:

image

Please also find the module for reference:
[Magz.zip](https://github.com/magento/magento2/files/11396505/Magz.zip)

Let me know if we have missed anything.

Thanks

**Comment by Kiraberos** [comment]
@engcom-Hotel 
Thanks for the information) But in the task, it is indicated that the task is not only for orders but also for order items
And it is also indicated that this was corrected in a separate pr for orders
image

For order items similar behavior?
I also used /V1/orders/items/ for check

Thank you in advance)

**Comment by engcom-Hotel** [comment]
Hello @Kiraberos,

thanks for the reply!

We have tried with the same module and this PR changes, but we are still unable to get the extension attribute with the `V1/orders/items/{id}` API.

Please let us know if we missed anything.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @Kiraberos,

We are still waiting for your reply. Please refer to this https://github.com/magento/magento2/pull/37307#issuecomment-1538118209 and let us know if we missed anything.

Thanks

**Comment by Kiraberos** [comment]
Hello @engcom-Hotel 
I was able to reproduce the problem using V1/orders/items/{id} and it needs improvement.

I'll take care of it when I get the chance.

Thanks)

**Comment by engcom-Hotel** [comment]
Hello @Kiraberos,

Thanks for the reply!

By looking into your reply here https://github.com/magento/magento2/pull/37307#issuecomment-1562934566, it seems that the PR is still in the implementation phase. 

Hence marking this PR as a draft. You can reopen it or you can ask us to reopen whenever you are ready with the PR.

Thanks

**Pull request closed without merging**
