### PR TITLE
reconditioning product count & Id filtering method

### PR DESCRIPTION
**Pull request by manavluhar**
### Description (*)
Updating Load product count for specified items as :
-> while filtering Variable $ids in empty() always exists and is not falsy
-> Variable $categoriesProductsCount in isset() is never defined

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run Integration Tests, Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by manavluhar** [comment]
Hi @hostep, Thank you for letting me know. Why other PRs are yet not merged or accepted? any specific reason?

**Comment by engcom-Hotel** [comment]
Hello @manavluhar,

This PR https://github.com/magento/magento2/pull/35216 is already in the "Merge in progress" bucket. So we are making this PR on hold and waiting for that PR to merge. Once the PR will be merged we can reopen this PR for the remaining open issue.

Thanks

**Comment by manavluhar** [comment]
@engcom-Hotel closing this PR as issue is resolved by #35216 this PR.

**Pull request closed without merging**
