### PR TITLE
Backport of #5807: Fix minicart not cleared after order completion

### LINKED ISSUE #1461: Cart Items are not deleted after success checkout
Is this new feature or is a bug?
screen shot 2015-07-09 at 09 56 14

### LINKED ISSUE #4416: Mini cart shows old values when customer session is over
## Steps to reproduce
1. Magento 2.0.2, all cache types are disabled
2. go to frontend, do not log in
3. add few products to shopping cart
4. wait until session is over (1 hour by default)
5. go to shopping cart page
## Expected result
1. shopping cart and mini shopping cart should show the same values - zero in our case
## Actual result
1. shopping cart is empty, but mini shopping cart has added products https://drive.google.com/file/d/0B6jlEIvY3J2OM0dpaEx5azM5RkU/view

### LINKED ISSUE #4460: shipping cart is empty than also minicart display item [ Magento 2.0.0 ]
i have install magento 2.0.0 on live server

when i have remove items from shipping cart, minicart not updated.

now i refresh page few times, than also minicart display item.

### LINKED ISSUE #4969: minicart not cleared after order completion
I'm facing the issue of minicart not cleared after order completion using our custom payment method.

This is the same issue as:
[Cart Items are not deleted after success checkout #1461](https://github.com/magento/magento2/issues/1461)

As we're creating extension for payment method, we've limitation to not to override, modify or inject our content to any view or layout (like onepage/success) after order completion.
i.e; all the process is working on server end in our action controller.

### PR DESCRIPTION
**Pull request by AntonEvers**
Fixes #4460 Fixes #4416 Fixes #1461 Fixes #4969 Fixes MAGETWO-52593

(cherry picked from commit 9093ce9c2f5a4ba8c60ef0dd0769e620b4ce6f18)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Original #5807 PR wasn't merged, fix was implemented in different way, so it should be done in the same way.
Also looks like it was already fixed in 2.1-develop by #10050

**Comment by reijervano** [comment]
Guys,

this pull request does not fix the problem!

**Comment by CNanninga** [comment]
In my experience, this issue does still exist in 2.1.9.  #10050 doesn't fix the specific issue wherein the mini-cart still shows its old contents after completing an order.

Whether the appropriate implementation or not, this PR does fix it.  (Though you must implement the same template change in additional templates if your theme or a custom extension is overriding the order success page.)

**Comment by AntonEvers** [comment]
I fully agree that this PR is not the proper solution. But as a hotfix it's ok. I'd rather see that not only POST and AJAX calls can invalidate the cart cache but also regular page requests. Let's work on a proper solution from here. I was asked to backport this by the Magento developers.

**Comment by vkublytskyi** [comment]
@ajpevers as original PR #5807 was closed and not merged into `develop` branch and I was not able to reproduce linked issues on  `2.1-develop` branch I close this PR. If the issue is still valid, please provide steps to reproduce for actual `2.1` version to reopen this PR.

**Comment by AntonEvers** [comment]
Hi @vkublytskyi,

Can you please contact @vrann on this issue? He asked me on 1 september: [8:54 PM] 
@anton.evers Hi! would you be interested to make a backport this issue to 2.1? https://github.com/magento/magento2/pull/5807

Thanks,

Anton

**Pull request closed without merging**
