### PR TITLE
Backport apply coupoun and scroll top to check. applied successfully or not

### PR DESCRIPTION
**Pull request by krnshah**
### Description (*)

If we are applying the coupon code from the admin while create order and click on "Apply coupon code" it not showing error/success msg, we have to scroll up to check the msg.
#22341 
### Fixed Issues (if relevant)

1. magento/magento2#22341: Apply coupoun and scroll top to check. applied successfully or not

### Manual testing scenarios (*)

1. Admin >> Sales >> Orders
2. Create a New Order
3. Add Products
4. Coupon code >> Enter invalid coupon
5. Click on Apply button

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by dmytro-ch** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-23195.instances.magento-community.engineering).
Admin access: [https://pr-23195.instances.magento-community.engineering/admin](https://pr-23195.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5266](https://jira.corp.magento.com/browse/ENGCOM-5266) has been created to process this Pull Request

**Comment by makkoff** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
