### PR TITLE
Fix wrong path slider jquery widget

### LINKED ISSUE #35327: jQuery UI Slider and SelectMenu Mapping is not correct in requirejs-config.js
### Preconditions (*)

On Magento 2.4.4 release, jQuery UI Slider and SelectMenu Mapping is not correct in vendor/magento/module-theme/view/base/requirejs-config.js. This causes an error on frontend as jQuery slider and selectmenu modules do not get loaded and we see an error saying "$j(..).slider is not a function".

### Steps to reproduce (*)

Open vendor/magento/module-theme/view/base/requirejs-config.js

On line 42 you will notice the incorrect mapping -

'jquery-ui-modules/slider': 'jquery/ui-modules/widgets/selectmenu',

### Expected result (*)

The correct mapping should be -

'jquery-ui-modules/selectmenu': 'jquery/ui-modules/widgets/selectmenu',
'jquery-ui-modules/slider': 'jquery/ui-modules/widgets/slider',

### Actual result (*)

This causes an error on frontend where jQuery slider is used and shows an error saying "$j(..).slider is not a function".

Screenshot 2022-04-19 at 4 38 23 PM

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Correct wrong widget name path requirejs theme

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35327

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hostep** [comment]
This relates to this issue: https://github.com/magento/magento2/issues/35327 I guess?

**Comment by mrtuvn** [comment]
Thanks for the note. I have updated PR description

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
Fix look correct for me. Let's wait tests results

**Comment by Den4ik** [comment]
@magento give me test instance

**Comment by Den4ik** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by Den4ik** [comment]
https://github.com/magento run Functional Tests EE

**Comment by hostep** [comment]
@mrtuvn: there is a claim in https://github.com/magento/magento2/issues/35327 that the following line should get added as well, could you verify this and add it if you agree?

```
'jquery-ui-modules/selectmenu': 'jquery/ui-modules/widgets/selectmenu',
```

Thanks! 🙂

**Comment by mrtuvn** [comment]
Done! 
Thanks for your feedbacks

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE

**Comment by mrtuvn** [comment]
@magento run all tests

**Review by krissyhiserote — APPROVED** [review]
@mrtuvn I don't see any issues with these changes as long as all the tests are passing.

**Comment by Den4ik** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE

**Comment by engcom-Lima** [comment]
Hi @mrtuvn , @krissyhiserote , @Den4ik Thanks for contribution and collaboration .
By looking at the issue description ,I can see there is an Jquery mapping mismatch in the codes. But can you please let us know that ,how we can reproduce this issue in the front end .

Thanks

**Comment by mrtuvn** [comment]
i think we can reproduce issue by call to "jquery-ui-modules/slider" in any frontend template custom (phtml) inline script for example

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

- Install the fresh Magento 2.4-develop instance with Sample data.


**Manual testing scenario:**

1. Login to front-end as customer.
2. Open console and check if any js error displayed in it

**Before:** :heavy_multiplication_x: Getting JS error in the frontend console.
Screenshot from 2022-05-17 17-37-41



**After:** :heavy_check_mark:  There was no js error found in the console after PR changes.
Screenshot from 2022-05-17 21-50-24

Navigated to other pages and validated whether any js error is there or not. Since this issue having minor changes which is not affecting any functionality hence,no additional manual/automated case required for regression cycle.

**Comment by knowgod** [comment]
I have just realized that I faced the same issue. Looking forward to this fix merged.

**Comment by ishakhsuvarov** [comment]
@knowgod Should be delivered shortly

**Pull request merged**
