### PR TITLE
apache2 default config file update

### PR DESCRIPTION
**Pull request by jakwinkler**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by qsolutions-pl** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@qsolutions-pl it seems like you have an issue with not auto-generated product images. If so - please double-check if you have a correct file in the media directory https://github.com/magento/magento2/blob/6ed69330190ed034d337e20e696ac8f184da7096/pub/media/.htaccess

**Comment by qsolutions-pl** [comment]
@ihor-sviziev I do use composer installation so all files like `.htaccess` are default
I use this `apache2` config, to match `nginx`
```
VirtualDocumentRoot "/home/jakub/MagentoProjects/%1/pub/"
```
or for production (if runs apache2)
```
DocumentRoot "/home/projectname/public_html/pub/"
```
In such setup, image generation on request does not work.
If you take a look at `nginx` config: 

```
location /media/ {
    try_files $uri $uri/ /get.php$is_args$args;
```
you will see that all requests to `media/*` are passed to `get.php` script

That part of the config is missing in `pub/.htaccess` file and that is why image generation on request does not work.

**Comment by qsolutions-pl** [comment]
@ihor-sviziev I'll check later why `pub/media/.htaccess` is ignored / skipped, file is there.

**Comment by ihor-sviziev** [comment]
@qsolutions-pl, please check the `AllowOverride` directive. I believe it's set incorrectly. More details here: 
http://httpd.apache.org/docs/2.4/mod/core.html#allowoverride

**Comment by qsolutions-pl** [comment]
`allowoverride` is enabled, still checking...

**Comment by gabrieldagama** [comment]
Hi @qsolutions-pl, thanks for contributing! Can you provide what problem we are solving here and the steps to reproduce it?

Thanks!

**Comment by ihor-sviziev** [comment]
As we discussed in Slack with @qsolutions-pl - the issue was related to incorrect environment configuration.
I'm closing this PR as not relevant anymore.

**Pull request closed without merging**
