### PR TITLE
[Backport] Email to a Friend form not full responsive and remove link not positi…

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Original Pull Request 
 https://github.com/magento/magento2/pull/20874
Email to a Friend form not full responsive and remove link not position on correct place

### Description (*)
Email to a Friend form not full responsive and remove link not position on correct place

### Manual testing scenarios (*)

1. Open frontend 
2. Login as customer or create account 
3. Open any product page and click email link 
4. Email to a Friend this page will open and go in mobile size (Ref screenshot) 

### Actual result (*)
qnhpgda png png image 309 x 716 pixels scaled 84

### Expected result (*)
jswotsw png png image 308 x 545 pixels

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by Karlasa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Karlasa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Karlasa, here is your [new Magento instance](https://pr-21166.instances.magento-community.engineering).
Admin access: [https://pr-21166.instances.magento-community.engineering/admin](https://pr-21166.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by Karlasa — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Karlasa, thank you for the review.
[ENGCOM-4231](https://jira.corp.magento.com/browse/ENGCOM-4231) has been created to process this Pull Request

**Pull request merged**
