### PR TITLE
Updated return type in SaleRule Module #13278

### PR DESCRIPTION
**Pull request by amittiwari024**
### Description

- Updated return type hint of setIsActive() of Magento\SalesRule\Api\Data\RuleInterface is RuleInterface type ($this).
- Updated return type hint of setIsActive() of Magento\SalesRule\Model\Data\Rule is Rule type ($this).

### Fixed Issues (if relevant)

1. magento/magento2#13278: Wrong return type in Salesrule Module RuleInterface.php

### Manual testing scenarios

1. N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15337) <br/>All committers have signed the CLA.

**Comment by amittiwari024** [comment]
Hello @mzeis ,
May I know the updates regarding this pull request ? is it approved or not.
Thank You !!!

**Comment by mzeis** [comment]
Hi @amittiwari024, thank you for your PR! I think it shouldn't be a problem to get this into `2.2-develop`, I'm just double-checking with the core team that it's no problem to fix this for an `@api` annotated interface / class in a patch release.

**Comment by amittiwari024** [comment]
Hi @mzeis ,
Thanks for the quick reply!!

**Comment by amittiwari024** [comment]
@mzeis , Hi may I know any update on this?

**Comment by mzeis** [comment]
Hi @amittiwari024, sorry for letting you wait! I followed up and hopefully I can update you soon.

**Comment by mzeis** [comment]
Hi @amittiwari024, the core team asks you to please create a new PR with the same changes against `2.3-develop` instead of `2.2-develop`.

The reason why we cannot add it in 2.2.x: this change would lead to changes in the WSDL file that is generated automatically. This may affect integrations written in other languages. To maintain backward compatibility in 2.2.x, we have to move this to 2.3.

Thanks for your understanding. If you create the new PR, I'm happy to process it for you!

**Comment by amittiwari024** [comment]
Hi @mzeis, so I need to create the same pull request for 2.3 version?

**Comment by mzeis** [comment]
Hi @amittiwari024, let's try instead if the Magento tools handle it correctly when I change the PR base for this PR. I will let you know if I need you do to anything. Thanks!

**Comment by mzeis** [comment]
@amittiwari024 Do you see the merge conflicts ("This branch has conflicts that must be resolved")? If you update the patch branch in your fork to be based on `2.3-develop` and do a force push to your branch to update it, the conflicts should be gone.

Please tell me if you want me to look into it instead.

Thanks!

**Comment by amittiwari024** [comment]
@mzeis  Thanks

**Comment by amittiwari024** [comment]
@mzeis okay i will do this

**Comment by amittiwari024** [comment]
@mzeis please check now and do the needful I am not sure I have updated the version 2.3 of PR.
Thank you.

**Comment by mzeis** [comment]
Hi @amittiwari024,

I think your PR branch is not up-to-date because it says this on https://github.com/amittiwari024/magento2/tree/amittiwari024-patch-1: "This branch is 1 commit ahead, 413 commits behind magento:2.2-develop."

What I would do:

* Create a local clone of your repository
* Make sure that the `2.3-develop` branch of your clone is up-to-date (have a look at this [video](https://www.youtube.com/watch?v=mJDCL0uzIpY))
* Delete the branch `amittiwari024-patch-1` locally
* Re-create the branch, this time based on `2.3-develop`
* Apply the change from 5c91f4b139003d6571f6fc2d4fd688213e0422f0
* Commit the change
* Force push it onto your fork

Please let me know if I can help with this.

**Comment by mzeis** [comment]
@amittiwari024 I close the issue due to inactivity. Please follow my suggestions in https://github.com/magento/magento2/pull/15337#issuecomment-394604296 to fix the conflict and I'll be happy to continue proccesing this PR. Thank you!

**Pull request closed without merging**
