### PR TITLE
Aria-atomic="true" missing on error container

### LINKED ISSUE #29560: [Issue] Aria-atomic="true" missing on error container
This issue is automatically created based on existing pull request: magento/magento2#27386: Aria-atomic="true" missing on error container

---------

### Description (*)
Issue : Aria-atomic="true" is missing on error container

Summary: The page contains an error container made with the WAI-ARIA `role="alert"` attribute, but it does not contain a WAI-ARIA attribute that will make sure all assistive technology can read the error message after more than one invalid submission.

Fix: To make sure that all assistive technologies will read the error message after more than one invalid submission, added the WAI-ARIA attribute `aria-atomic="true"` to the error container tag.

### Related Pull Requests
N/A
### Fixed Issues (if relevant)
N/A

**Preconditions:**

have Cart price rule with discount code;

**Steps to reproduce:**
1. Go to Storefront;
2. Add product to cart;
3. Go to Shopping Cart;
4. Expand **Apply Discount Code** tab and fill correct code

**Expected Result:** :heavy_check_mark:  The success message is shown on the page

Screenshot from 2020-09-03 11-19-16

5. Try to fill with incorrect code

**Expected Result:** :heavy_check_mark:  The error message is shown on the page

Screenshot from 2020-09-03 11-19-06

6. Proceed to Checkout;
7. Fill all required fields and go to  Review & Payments step;
8. Expand the **Apply Discount Code** tab and fill correct code

**Expected Result:** :heavy_check_mark:  The success message is shown on the page

Screenshot from 2020-09-03 11-13-30

9. Try to fill with incorrect code

**Expected Result:** :heavy_check_mark:  The error message is shown on the page

Screenshot from 2020-09-03 11-13-19
Actual Result:
### Questions or comments
N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by bradleybrecher**
### Description (*)
Issue : Aria-atomic="true" is missing on error container

Summary: The page contains an error container made with the WAI-ARIA `role="alert"` attribute, but it does not contain a WAI-ARIA attribute that will make sure all assistive technology can read the error message after more than one invalid submission.

Fix: To make sure that all assistive technologies will read the error message after more than one invalid submission, added the WAI-ARIA attribute `aria-atomic="true"` to the error container tag.

### Related Pull Requests
N/A
### Fixed Issues (if relevant)
N/A

**Precondition:**

have Cart price rule with discount code;

**Manual testing scenario:**

1. Go to Storefront;
2. Add product to cart;
3. Go to Shopping Cart;
4. Expand **Apply Discount Code** tab and fill correct code

**Expected Result:** :heavy_check_mark:  The success message is shown on the page

Screenshot from 2020-09-03 11-19-16

5. Try to fill with incorrect code

**Expected Result:** :heavy_check_mark:  The error message is shown on the page

Screenshot from 2020-09-03 11-19-06

6. Proceed to Checkout;
7. Fill all required fields and go to  Review & Payments step;
8. Expand the **Apply Discount Code** tab and fill correct code

**Expected Result:** :heavy_check_mark:  The success message is shown on the page

Screenshot from 2020-09-03 11-13-30

9. Try to fill with incorrect code

**Expected Result:** :heavy_check_mark:  The error message is shown on the page

Screenshot from 2020-09-03 11-13-19
### Questions or comments
N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29560: Aria-atomic="true" missing on error container

### CODE REVIEW

**Comment by rogyar** [comment]
I can confirm that it's a good idea to wrap all messages into the `area-atomic` DOM element since we stack messages in this DOM element in case of more than one message.

**Review by rogyar — CHANGES_REQUESTED** [review]
@bradleybrecher. Thank you for your contribution. According to the new [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered by automated tests. I would recommend covering this change by MFTF test that will check that `aria-atomic` tag is present in case of error/success message on the page. You can use the following example of the selector that shows how to create a proper selector and assert it using `seeElement` command. 

https://github.com/magento/magento2/blob/37731349799b541f05e6799bb8f66da23de0d2f7/app/code/Magento/Indexer/Test/Mftf/Section/AdminIndexManagementSection.xml#L18

Thank you.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by rogyar** [comment]
Hi @engcom-Charlie. I would still recommend using a separate test case instead of modifying test selectors. My concern is if `[aria-atomic=true]` will be removed or modified for the DOM elements for some reason, we will have many failing tests instead of one. If we don't change selectors but introduce a new test that ensures that the corresponding selectors have `[aria-atomic=true]`, we will potentially have only one test failing in case of changing the corresponding DOM element.

I hope, I described both cases clear :)

**Comment by engcom-Charlie** [comment]
Hi @rogyar, do you mean it should be a new mftf test or add a selector check to some already written test?
Thank you.

**Comment by rogyar** [comment]
Hi @engcom-Charlie. My recommendation was to introduce a new MFTF test that will go to the corresponding page and check that `.message-success[aria-atomic=true]` selector exists and visible. Without modifying the existing MFTF elements. In that way, we will preserve backward compatibility and reduce the chance of a couple of failing tests as the result of the DOM elements refactoring in the future. 

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento create issue

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi, @sidolov can you please review this PR?
Thank you.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8120](https://jira.corp.magento.com/browse/ENGCOM-8120) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@bradleybrecher thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

Precondition:

have Cart price rule with discount code;

**Manual testing scenario:**

1. Go to Storefront;
2. Add product to cart;
3. Proceed to Checkout;
4. Fill all required fields and go to  Review & Payments step;
5. Expand the **Apply Discount Code** tab and fill incorrect code

Actual Result: :heavy_multiplication_x: The error message is shown on the page

Screenshot from 2020-09-03 11-13-19

6. Try to fill with correct code

Actual Result: :heavy_multiplication_x: The success message is shown on the page

Screenshot from 2020-09-03 11-13-30

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8120](https://jira.corp.magento.com/browse/ENGCOM-8120) has been created to process this Pull Request

**Comment by rogyar** [comment]
Hi @engcom-Charlie. Cold you move this PR to the correct status, please? pull-request-dashboard-manager don't trust me in my decisions :) 

Thank you

**Pull request merged**
