### PR TITLE
Custom attribute value in Customer Address and Quote Address is array

### PR DESCRIPTION
**Pull request by NikolasSumrak**
### Description (*)
**REOPENED PR from** https://github.com/magento/magento2/pull/29307
After setting customer attributes, in value of each customer attribute we have array[attribute_code=>code, value=>value] instead of value. Just run new unit test on code without fix in app/code/Magento/Customer/Model/Address/AbstractAddress.php.

For understanding issue follow the code lines below:
1. app/code/Magento/Customer/Model/Address/AbstractAddress.php:285 and below
passing by reference in foreach (line 285: foreach ($value as &$attribute) )
here all custom attributes convert to array from object (line 286)
After that we have array with custom attributes like as:
```
    $customAttributes = [
            'test_attribute' => [
                'attribute_code' => 'test_attribute',
                'value' => 'test'
            ]
        ];
```
2. lib/internal/Magento/Framework/Model/AbstractExtensibleModel.php:221
3. lib/internal/Magento/Framework/Model/AbstractExtensibleModel.php:121
here we see forearch($data[self::CUSTOM_ATTRIBUTES] as $code => $value)
and ->setValue($value); where value is array!
```
[
    'attribute_code' => 'test_attribute',
    'value' => 'test'
]
```

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento run all tests

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @NikolasSumrak. Thank you for bringing this fix back. 
Could you check the failing tests, please?

**Comment by engcom-Echo** [comment]
Hi @NikolasSumrak, I don't think it will happen.
image

**Comment by engcom-Charlie** [comment]
Hi @NikolasSumrak could you please provide exact steps to reproduce the issue and fix failed tests?
Thank you.

**Comment by haunguyen1989** [comment]
Customer address attribute store value in table magento_customercustomattributes_sales_flat_quote_address wrong with 
`attribute code + "/n" + value`. Ex: test_attribute\ntest

**Comment by sidolov** [comment]
@NikolasSumrak , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
