### PR TITLE
Adding required custom options to simple product removes it from parent composite products without warning

### LINKED ISSUE #30492: Adding required custom options to simple product removes it from parent composite products without warning
### Steps to reproduce
1. Login to the Magento Admin panel
2. Create a configurable or group product
3. Create a simple product and add it to configurable or group product
4. Edit simple product and add a required custom option
5. Save

### Expected result
A simple product should not be saved. A warning should be displayed to the admin user: "Required custom options cannot be added to a simple product that is a part of a composite product"

### Actual result
A simple product is saved. It is unassigned from parent composite products. No warning is displayed to the admin user.

### Additional Info

Moreover there is problem with those simple product custom options. When simple product has custom option and You are in configurable product page and You choose simple product ( configurable attribute ) there should also be possibility to choose product simple custom option.

### PR DESCRIPTION
**Pull request by engcom-Charlie**
### Description (*)

Please see https://github.com/magento/magento2/issues/30492

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30492

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by shikhamis11 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, thank you for the review.
[ENGCOM-8838](https://jira.corp.magento.com/browse/ENGCOM-8838) has been created to process this Pull Request
:eight_spoked_asterisk: @shikhamis11, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

### Manual testing scenario
1. Login to the Magento Admin panel
2. Create a configurable or group product
3. Create a simple product and add it to configurable or group product
4. Edit simple product and add a required custom option
5. Save

**BEFORE** applying changes provided in the PR, a _You saved the product_ success message appeared
before_Screenshot from 2021-03-02 12-49-44

**AFTER**switching to the PR, A warning _Required custom options cannot be added to a simple product that is a part of a composite product_ appears
after_Screenshot from 2021-03-02 12-49-44

**Pull request merged**
