### PR TITLE
Fix for issue 27474

### LINKED ISSUE #27474: In the invoice it is not shown, if the invoice email has been sent or not
### Preconditions (*)

Magento 2.3.4

### Steps to reproduce (*)

1. Create an order
2. Create the corresponding invoice in the backend
3. Open the invoice in the backend and take a look at the header

### Expected result (*)

I would assume to see an information in the header section of the invoice, which informs me if the invoice email has been sent or not. It was this way in Magento 1, it is available for the order, but not for the invoice. So you only see, if the order confirmation mail has been sent out, but not if the invoice is actually sent or not.

### Actual result (*)

No email hint is shown.
Screenshot from 2021-05-05 10-50-54

I debugged this issue a bit. The email hint would normally be processed by `\Magento\Sales\Block\Adminhtml\Order\Invoice\View::getHeaderText`. But this function is never called as far as I can see. The corresponding block is defined in `vendor/magento/module-sales/view/adminhtml/layout/sales*order_invoice*view.xml:14`, but has no template defined. In the end this block is initialized in `\Magento\Sales\Controller\Adminhtml\Order\Invoice\View::execute` where the title is set. But there only the invoice increment id is shown, no status hint.

### PR DESCRIPTION
**Pull request by topanok**
### Description (*)
Since this behavior occurs both on the invoice page and on the shipment and credit memo pages, it was decided to add an info block to these pages. The page headers were also changed to bring them to the appropriate view, because only the number was displayed on the invoice and shipment page, and View Memo on the credit memo page.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#27474

### Manual testing scenarios (*)
1. Create an order
2. Create the corresponding invoice in the backend
3. Create the corresponding shipment in the backend
4. Create the corresponding crdit memo in the backend
5. Open the invoice or shipment or credit memo in the backend and take a look at the new Info block with rwith the relevant information about the email and so on

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by topanok** [comment]
@magento run all tests

**Comment by topanok** [comment]
@magento run all tests

**Comment by topanok** [comment]
@magento run all tests

**Comment by topanok** [comment]
@magento run all tests

**Comment by topanok** [comment]
@magento run all tests

**Comment by topanok** [comment]
@magento run all tests

**Comment by topanok** [comment]
@magento run all tests

**Comment by topanok** [comment]
@magento run Functional Tests B2B,  Integration Tests

**Comment by topanok** [comment]
Clarifications are needed from the reviewer on the Semantic Version Checker test

**Comment by topanok** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B, Integration Tests, Semantic Version Checker

**Comment by topanok** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B, Integration Tests

**Comment by topanok** [comment]
@magento run all tests

**Comment by topanok** [comment]
@magento run all tests

**Comment by topanok** [comment]
@magento run all tests

**Comment by topanok** [comment]
@magento run all tests

**Comment by topanok** [comment]
@magento run all tests

**Comment by topanok** [comment]
@magento run Functional Tests EE, Functional Tests CE, Semantic Version Checker , WebAPI Tests

**Comment by topanok** [comment]
@magento run all tests

**Comment by topanok** [comment]
@magento run all tests

**Comment by topanok** [comment]
@magento run all tests

**Comment by topanok** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by topanok** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @topanok,

Thanks for the contribution!

Can we cover the changes related to the credit memo and invoice page with some automated tests?

Also please take care of the failed tests.

Thanks

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by topanok** [comment]
@engcom-Hotel Hello! Yes, I'm working on tests.

**Comment by engcom-Echo** [comment]
Hi @topanok,

Did you get chance to look on above [comment](https://github.com/magento/magento2/pull/36030#pullrequestreview-1449572035)?

**Comment by topanok** [comment]
Hi @engcom-Hotel. A bit busy right now, but I'm working on tests as well

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@engcom-Hotel automated test coverage has been added.

**Comment by engcom-Hotel** [comment]
@magento run WebAPI Tests, Functional Tests EE, Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run WebAPI Tests

**Review by engcom-Hotel — APPROVED** [review]
Hello @topanok,

Thanks for the contribution and collaboration!

The failed functional test seems flaky to me and for semantic version failure, we need to raise an approval ticket internally. 

Hence approving the PR.

Thanks

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by topanok** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE, Semantic Version Checker

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**
1. Create an order
2. Create the corresponding invoice in the backend
3. Open the invoice in the backend and take a look at the header

**Before:** :heavy_multiplication_x: No information of the invoice email was shown in the header.
Screenshot 2023-07-10 at 11 45 20 AM


**After:** :heavy_check_mark:  Mail sent information was now getting displayed.
**Invoice:**
Screenshot 2023-07-10 at 11 55 45 AM
**Shipment:**
Screenshot 2023-07-10 at 11 53 25 AM

**Credit Memo:**
Screenshot 2023-07-10 at 11 54 20 AM


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

**Comment by topanok** [comment]
@magento run Unit Tests

**Comment by topanok** [comment]
@engcom-Lima Hello! As you can see, only Semantic Version remains, with which I cannot do anything.

**Comment by engcom-Echo** [comment]
> 

We will create internal ticket for approval and move it ahead once it gets approved.

**Comment by engcom-Echo** [comment]
We have raised internal approval request [JIRA](https://jira.corp.adobe.com/browse/AC-9140) for Semantic version failure. Waiting for approvals. 
Hence moving this to `Pending Approval`

Thank you!

**Comment by engcom-Echo** [comment]
We have got comment from internal team for approval ticket.
@topanok Can you please have a look at below comment and make changes?

```
Backward incompatible changes can be avoided, can't find any valid rationale behind the creation of new empty blocks, as templates can be redefined without the need for generating additional blocks.
The same for the new method in the abstract block.
```

hence moving it to changes requested.

**Comment by topanok** [comment]
@engcom-Echo I answer.... Each of the 3 added block templates calls the getCreatedAtAdminDate method that was added. Blank blocks have also been added for flexibility in adding and modifying data. I think this is Magento Best Practices. Again, calling the getOrderAdminDate method for, say, shipment is somehow incorrect, that is why the getCreatedAtAdminDate method was added, which is used in 4 blocks that are inherited from the AbstractOrder class, including the Order\View\Info block in the getOrderAdminDate method.

**Comment by engcom-Charlie** [comment]
Moving it to Pending Review as per information provided in [comment](https://github.com/magento/magento2/pull/36030#issuecomment-1637732061).

Thank you!

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @topanok,

I agree with the internal team's comment here: https://github.com/magento/magento2/pull/36030#issuecomment-1637732061

I think we can remove the empty blocks because that is required in order to redefine templates. 

We request you to please do the needful.

Thanks

**Comment by engcom-Hotel** [comment]
Thanks @topanok,

Let me move it to "Pending Review" bucket for review

**Comment by engcom-Hotel** [comment]
@magento run WebAPI Tests, Unit Tests, Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE, Unit Tests, WebAPI Tests

**Review by engcom-Hotel — APPROVED** [review]
Hello @topanok,

Thanks for the contribution!

Build fails seems flaky to me, hence approving the PR.

Thanks

**Comment by engcom-Lima** [comment]
@magento run Semantic Version Checker

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

1. Create an order
2. Create the corresponding invoice in the backend


3. Open the invoice in the backend and take a look at the header

**Before:** :heavy_multiplication_x: 
Screenshot 2023-08-09 at 12 51 49 PM
Screenshot 2023-08-09 at 12 51 36 PM



**After:** :heavy_check_mark:  
Screenshot 2023-08-09 at 1 07 57 PM
Screenshot 2023-08-09 at 1 07 40 PM
Screenshot 2023-08-09 at 1 08 43 PM

Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B,WebAPI Tests,Unit Tests

**Comment by topanok** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B,WebAPI Tests,Unit Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Moving this PR to the "Pending Review" bucket due to the latest changes.

**Comment by topanok** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B,WebAPI Tests,Unit Tests

**Comment by topanok** [comment]
@magento run WebAPI Tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**
1. Create an order
2. Create the corresponding invoice in the backend
3. Open the invoice in the backend and take a look at the header

**Before:** :heavy_multiplication_x: 
Screenshot 2023-08-16 at 3 01 02 PM



**After:** :heavy_check_mark:  
Screenshot 2023-08-16 at 3 09 57 PM
Screenshot 2023-08-16 at 3 10 47 PM
Screenshot 2023-08-16 at 3 11 43 PM
Screenshot 2023-08-16 at 3 11 55 PM

Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE, Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Integration Tests,Database Compare

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Database Compare

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Database Compare

**Comment by topanok** [comment]
It will take forever .... :-(

**Comment by topanok** [comment]
@magento run Unit Tests,Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by topanok** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Hello @topanok,

It seems you are working on this PR. Can you please confirm if you are working on fixing its build failures?

Thanks

**Comment by engcom-Hotel** [comment]
@magento run Database Compare, Unit Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Comment by engcom-Hotel** [comment]
Moving this PR for testing after fixing the Functional tests failures.

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

Moving PR to **Merge in progress**

**Pull request merged**
