### PR TITLE
Fix for empty category field values in REST calls

### PR DESCRIPTION
**Pull request by igorwulff**
### Description
When using either rest/all/V1/categories or rest/all/V1/categories?rootCategoryId=2 the name and product_count fields are empty for all categories in the tree. This does not happen when using a store code like default without a rootCategoryId as GET param, like this: rest/default/V1/categories

### Manual testing scenarios (*)
Use Magento installatie with a category tree and place a REST API call to 'rest/all/V1/categories'.

This will result in empty field values for name and product_count.

When using a storecode like default instead of all in the endpoint call, the fields will be filled in the data that we get back from the API endpoint.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by igorwulff** [comment]
The original PR was closed and not re-opened even though it was ready to be merged. I didn't get a reply for my last query, so I've created a new PR. Here is the old one (https://github.com/magento/magento2/pull/23587)

**Comment by igorwulff** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @igorwulff. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @igorwulff, here is your [Magento instance](https://i-24042-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24042-2-3-develop.instances.magento-community.engineering/admin](https://i-24042-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by igorwulff** [comment]
Can this PR please be checked?

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @igorwulff. Thanks for collaboration. 
Our unit tests are failed. Can you please check that case and fix if it needed?

**Comment by igorwulff** [comment]
Hi @VladimirZaets I've checked the issue and think the getNode method should be removed from the codebase and the unittest, but would like advice from Magento regarding this and on how to proceed. The getNode method is after my change and as far as I know nowhere used and no longer required.

**Comment by VladimirZaets** [comment]
Hi, @igorwulff, due to [Magento backward-compatible guide](http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/) we can't delete protected method. Please mark it as deprecated

**Comment by igorwulff** [comment]
> Hi, @igorwulff, due to [Magento backward-compatible guide](http://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/) we can't delete protected method. Please mark it as deprecated

Thanks! I will perform the changes most likely today.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24042) <br/>All committers have signed the CLA.

**Comment by igorwulff** [comment]
> [CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24042) 
> Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=24042) before we can accept your contribution.
> **1** out of **2** committers have signed the CLA.
> 
>  igorwulff
>  Igor Wulff
> 
> **Igor Wulff** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

I'm unsure what this means? I did sign it,

**Comment by igorwulff** [comment]
> Hi @igorwulff. Thanks for collaboration.
> Our unit tests are failed. Can you please check that case and fix if it needed?
Hi @VladimirZaets, I've done the requested changes. Can you check them again? I'm also unsure about the comment regarding the CLA, since I did sign it, but it is still nagging about something.

**Comment by sidolov** [comment]
Hi @igorwulff  , looks like you made commit 4b06769939d1eef89727d889e53ac4104c4ceb59 with email different than in your GitHub profile, please, add email from commits to your profile!
Thank you!

**Comment by igorwulff** [comment]
> Hi @igorwulff , looks like you made commit [4b06769](https://github.com/magento/magento2/commit/4b06769939d1eef89727d889e53ac4104c4ceb59) with email different than in your GitHub profile, please, add email from commits to your profile!
> Thank you!

This should be fixed now. Can you verify?

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5714](https://jira.corp.magento.com/browse/ENGCOM-5714) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@igorwulff thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Delta** [comment]
Hi @igorwulff Unfortunatelly, I cannot reproduce issue on 2.3-develop.
Here is my result with one root category:
#24042MainSwagger

#24042MainRest

Result with second root category:
#24042MainSecondRootSwagger


#24042MainSecondRoot

Category tree in admin:
#24042MainCatagory

Could you take a look?

**Comment by igorwulff** [comment]
> Hi @igorwulff Unfortunatelly, I cannot reproduce issue on 2.3-develop.
> Here is my result with one root category:
> #24042MainSwagger
> 
> #24042MainRest
> 
> Result with second root category:
> #24042MainSecondRootSwagger
> 
> #24042MainSecondRoot
> 
> Category tree in admin:
> #24042MainCatagory
> 
> Could you take a look?

Yes I will check it this week and give this PR an update.

**Comment by igorwulff** [comment]
> Hi @igorwulff Unfortunatelly, I cannot reproduce issue on 2.3-develop.
> Here is my result with one root category:
> #24042MainSwagger
> 
> #24042MainRest
> 
> Result with second root category:
> #24042MainSecondRootSwagger
> 
> #24042MainSecondRoot
> 
> Category tree in admin:
> #24042MainCatagory
> 
> Could you take a look?

I'm unsure how to proceed. I tested multiple shops from us from version 2.3.2 and always get the same result without my patch:

Invalid result (missing names, is_active data) when calling /index.php/rest/all/V1/categories
image-invalid-rest-call

Call with only /index.php/rest/default/V1/categories only works correctly:
image-working-rest-call

This patch is not only fixing the issue I'm having, but also improves the code quality at that location. Either way I think it is preferable to merge these changes. But I'm curious why you can't reproduce the issue I'm having.

What steps should I take to replicate the same situation?

**Comment by ihor-sviziev** [comment]
Hi @engcom-Delta,
Could you review following comment https://github.com/magento/magento2/pull/24042#issuecomment-529488542?
Is it helped to reproduce this issue?

**Comment by engcom-Delta** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Delta. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Delta, here is your [Magento instance](https://i-24042-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24042-2-3-develop.instances.magento-community.engineering/admin](https://i-24042-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Delta** [comment]
@igorwulff I try to reproduce your category tree with which issue was caused, but I am not able to reproduce it 2.3-develop [instance](https://i-24042-2-3-develop.instances.magento-community.engineering/admin).
Could you check [instance](https://i-24042-2-3-develop.instances.magento-community.engineering/admin) configuration and tell if something is wrong configured?

**Comment by sidolov** [comment]
@igorwulff , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
