### PR TITLE
[Backport] Fixed a couple of spelling mistakes

### PR DESCRIPTION
**Pull request by mage2pratik**
### Original Pull Request 
 https://github.com/magento/magento2/pull/16980
 https://github.com/magento/magento2/pull/16928
https://github.com/magento/magento2/pull/16889
 https://github.com/magento/magento2/pull/16880

### Description

Fixed a couple of spelling mistakes.
### Fixed Issues (if relevant)

N/A

### Manual testing scenarios

N/A
### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by sidolov** [comment]
@magento-engcom-team combine 17150 17148 17146

**Comment by magento-engcom-team** [comment]
Hi @sidolov. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
@mage2pratik all pull requests have been successfully combined together: 
 - merged https://github.com/magento/magento2/pull/17150: [Backport] Reduce lengthy code of LoginPost
 - merged https://github.com/magento/magento2/pull/17148: [Backport] Microrefactoring in product gallery block helper
 - merged https://github.com/magento/magento2/pull/17146: [Backport] Array short syntax

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your contribution. 
We will aim to release these changes as part of 2.1.15. 
Please check the release notes for final confirmation.

**Pull request merged**
