### PR TITLE
issues-25010: fix CustomerIsGuest for quotes

### LINKED ISSUE #23908: The shipping information was unable to be saved. verify the input data and try again.
### Additional Details
Detailed explanation and result of the investigation  https://github.com/magento/magento2/issues/23908#issuecomment-538087658

### Preconditions (*)

1. Magento 2.3.2, 2.3-develop

### Steps to reproduce (*)

1. Create a customer account
2. Go to my account, and add a shipping address
2.5. Enable Persistent Shopping Cart **(updated Oct 10.2019)**
3. Add any product and ~go to the checkout~ **_!Impotent:_** wait until the customer session expires (one hour by default) but no longer than Persistence Lifetime is set to **(updated Oct 10.2019)**
3.5 Reload the page so that somewhere in the upper-right corner You get "Not You?" link next to the welcome message  **(updated Oct 10.2019)**
3.6 Clik on "Not You?" enter the credentials of the customer and log in **(updated Oct 10.2019)**
3.6 Go to Mini Cart end press Precede to Checkout **(updated Oct 10.2019)**
4. Select the address you have just added
5. Select a shipping method and click next button

### Expected result (*)

1. Payment page should show up

### Actual result (*)

1.  
Screenshot_2

### LINKED ISSUE #24736: Quote `customer_is_guest` set to 0 for guests
### Preconditions
1. Magento 2.3.1

### Steps to reproduce (*)

1. Be guest
2. Put item in cart
3. Go to checkout
4. Fill in shipping information
5. Select shipping method
6. Proceed to payment screen

### Expected result (*)

1. In database, `quote.customer_is_guest` === 1

### Actual result (*)

1. `quote.customer_is_guest` === 0

:exclamation: **Take a note of the following:**
```
<column xsi:type="smallint" name="customer_is_guest" padding="5" unsigned="true" nullable="true"
                identity="false" default="0" comment="Customer Is Guest"/>
```
 in /app/code/Magento/Quote/etc/db_schema.xml. Though there probably everything works fine with quote.customer_is_guest in Core code it is still a bug of the code design. Once the field is 'nullable="true"' it would better remain null until it is set explicitly than be zero from the very beginning (default="0"). Or if for some reason it needs to be zero until being assigned a concrete value the comment="Customer Is Guest" is obviously not a sufficient one here. It's not right for the real guest customer to have its customer_is_guest being equal zero on any quote stage, at least unless there is something explanatory said on it. The side, i.e.  non-core developers (though probably some of the last ones too) may write wrong code being mislead by such a situation.

### PR DESCRIPTION
**Pull request by ffalkone**
### Description (*)
Fixed issue Quote `customer_is_guest` set to 0 for guest.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#24736 : Quote `customer_is_guest` set to 0 for guests
1. Fixes magento/magento2#23908 : The shipping information was unable to be saved. verify the input data and try again

### Manual testing scenarios (*)
1. Test: Customer Frontend
  - Enable Persistent Shopping Cart
  - Create a customer account
  - Go to my account, and add a shipping address
  - Add any product 
  - **_!Impotent:_** wait until the customer session expires (one hour by default) but no longer than Persistence Lifetime is set to 
  - Reload the page so that somewhere in the upper-right corner You get "Not You?" link next to the welcome message
  - Click on "Not You?" enter the credentials of the customer and log in
  - Go to Mini Cart end press Precede to Checkout
  - Select the address you have just added
  - Select a shipping method and click next button
  - you get no error message and can continue 
2. Test: Admin interface (ensure that is working as before after patch)
  - register customer in frontend 
  - add shipping and billig address
  - login in Backend
  - create order for customer (select customer and store)
  - you get no error message and can continue 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sdzhepa** [comment]
Hello @falkone


As I already mentioned here https://github.com/magento/magento2/issues/23908#issuecomment-545986488 internal team has already fixed the #23908 in the scope of `MC-21568` and it should be delivered soon.

Unfortunately, I have to put `on Hold` label here till `MC-21568` will be delivered to `2.3-develop`. Only after that, we can figure out does this PR need additional work/update or not

**Comment by sdzhepa** [comment]
Hello @ffalkone 

The internal team has delivered fix for https://github.com/magento/magento2/issues/23908 in the scope of [`MC-21568`](https://github.com/magento/magento2/search?q=MC-21568&type=Commits).

Label `Progress: on hold` removed from this PR

**Comment by hostep** [comment]
What would be the status of this PR? It looks like [MC-21568](https://github.com/magento/magento2/commit/6f0623f3f0f95ecdb960f5de89371fb8c8d51abc) will be delivered in Magento 2.3.4

Are there still additional fixes needed to solve [the](https://github.com/magento/magento2/issues/24736) [issues](https://github.com/magento/magento2/issues/23908)?

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@ffalkone I'm closing the PR since the issue was fixed in scope of `MC-21568`

**Pull request closed without merging**
