### PR TITLE
Fix static test failures for class annotaions

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
I found that we have false positive static tests, example: 
https://github.com/magento/magento2/commit/8ea9b0e5ed8f2ecdb490a16dcac9033ce9cdac1a
image
```
PHP Code Sniffer detected 2 violation(s): 
FILE: /var/www/html/app/code/Magento/Sales/Cron/CleanExpiredQuotes.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 12 | ERROR | [x] Class is missing annotation block
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
Failed asserting that 2 matches expected 0.
```

These checks were moved to Magento Coding Standards, so we don't need to have them. 
In addition to that - removed class annotation is ok - https://github.com/magento/magento-coding-standard/pull/171

CC @lenaorobei 

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-7097](https://jira.corp.magento.com/browse/ENGCOM-7097) has been created to process this Pull Request

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7097](https://jira.corp.magento.com/browse/ENGCOM-7097) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
**Notice:** QA not applicable

**Comment by engcom-Charlie** [comment]
Failed functional tests not related to the changes in this PR

**Pull request merged**
