### PR TITLE
Update MockObject class in Wishlist module

### PR DESCRIPTION
**Pull request by hws47a**
### Description (*)
Replace outdated PSR-0 `\PHPUnit_Framework_MockObject_MockObject` with current PSR-2 class name `\PHPUnit\Framework\MockObject\MockObject`

### Related Pull Requests
#26775 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]
Failing functional and integration tests are not related to this PR

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6895](https://jira.corp.magento.com/browse/ENGCOM-6895) has been created to process this Pull Request

**Review by Nazar65 — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by slavvka** [comment]
@hws47a Please fix the failing tests

**Review by lbajsarowicz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-6895](https://jira.corp.magento.com/browse/ENGCOM-6895) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Pull request merged**
