### PR TITLE
#36142 FIX Caching route query for products and cms pages

### LINKED ISSUE #36142: [GraphQL] Result for route query for products and cms pages is never cached
### Preconditions and environment

- Magento version: 2.4.5
- Cache must be enabled (for easy testing use default file cache)
- A product with the url key "test"
- A cms page with the url "test-cms"

### Steps to reproduce

Execute the following query as GET request:
```GRAPHQL
query route {
    route(url: "test") {
        type
    }
}
```

```GRAPHQL
query route {
    route(url: "test-cms") {
        type
    }
}
```

### Expected result

I expect the query result to be cached with the following cache identity tag: 
For products: mage---_XXX_\_CAT_P\__PRODUCTID_
For cms pages: mage---_XXX_\_CMS_P\__CMSID_

(Italic written XXX, PRODUCTID, CMSID are variables)

### Actual result

No cache is written for the result.
This leads to the problem that the route query is slow for products and cms pages as it's never cached.

### Products
The problem arises because of the following code:
https://github.com/magento/magento2/blob/91549b925da128ba79807400f551f2b2d0cfeed9/app/code/Magento/CatalogUrlRewriteGraphQl/Model/Resolver/UrlRewrite/CatalogUrlResolverIdentity.php#L29-L39

In line 32 the isset checks for the occurence of `id`. This works only for categories as the id for products is stored in the array with the key `entity_id` instead of `id`. So no cache tag is returned from the function which leads to no cache gets written.

image

### Cms pages
The problem arises because of the following code:
https://github.com/magento/magento2/blob/91549b925da128ba79807400f551f2b2d0cfeed9/app/code/Magento/CmsUrlRewriteGraphQl/Model/Resolver/UrlRewrite/CmsUrlResolverIdentity.php#L26-L33

In line 29 the isset checks for the occurence of `id`. This doesn't work as the id for cms pagesis stored in the array with the key `page_id` instead of `id`. So no cache tag is returned from the function which leads to no cache gets written.

image

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by larsroettig**
### Description (*)

Fixes caching for route query for products and cms route query. The caching was basses on a deprecated `id` I changed 
to `entity_id` to make sure that cache get flush out when the product change. 

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36142

### Manual testing scenarios (*)

1.  Create Test Product with the URL `test.html`
2.  Execute  Executing is 300 - 600 ms 

```
query route {
    route(url: "test.html") {
        type
    }
}
```

4.  Execute  Executing is 150 - 300 ms reduced execution up to 50%   

```
query route {
    route(url: "test.html") {
        type
    }
}
```

5.  Change the URL  via `Search Engine Optimisation ` to `new_test` without url `Create Permanent Redirect for old URL`
3.  Execute  will answer with no match 
```
query route {
    route(url: "test.html") {
        type
    }
}
```

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by larsroettig** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Review by t-heuser — CHANGES_REQUESTED** [review]
You need to watch for `id` (categories) and `entity_id` (products) in the CatalogUrlResolverIdentity class on line 32.
For categories no `entity_id` is given.
My proposal is the following:
```PHP
        $id = $resolvedData['id'] ?? $resolvedData['entity_id'] ?? null;
        if ($id) {
```

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento run Functional Tests B2B, Functional Tests CE,Functional Tests EE,Integration Tests, WebAPI Tests

**Comment by JacobBrownAustin** [comment]
Thank you.  It appears that this issue was fixed in a similar commit from last month (December 7th),  https://github.com/magento/magento2/commit/967439abee8e9e2e934aaa983748357dd8816b7d .
The changes in that commit are slightly different,  but from my quick testing,  it does work to solve the same issue as this pull request.

**Pull request closed without merging**
