### PR TITLE
Fix copy-paste static test failure on mainline.

### PR DESCRIPTION
**Pull request by nmalevanec**
### Description (*)
Fix copy-paste static test failure, which fails because of identical methods in 
/Magento/Customer/Model/Customer/DataProvider.php and /Magento/Customer/Model/FileUploaderDataResolver.php

### Fixed Issues (if relevant)
1. none.

### Manual testing scenarios (*)
1. Run php LiveCodeTest
2. Check, no failures occurred.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @nmalevanec. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — APPROVED** [review]
Thanks @nmalevanec! Nice that you refactored before methods became different :-)

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3707](https://jira.corp.magento.com/browse/ENGCOM-3707) has been created to process this Pull Request

**Review by orlangur — CHANGES_REQUESTED** [review]
@nmalevanec please resolve conflicts and check if changes by @e0n4eg are sufficient.

**Comment by nmalevanec** [comment]
Already has been fixed.

**Pull request closed without merging**
