### PR TITLE
Issue 36073: Coupon codes export to Excel XML not working as expected

### LINKED ISSUE #36073: Coupon codes export to Excel XML not working as expected
### Preconditions (*)
1. Magento 2.4.5

### Steps to reproduce (*)
1. Create a salesrule of type "Specific Coupon" and check "Use auto generation":
Bildschirmfoto 2022-09-02 um 10 25 52

2. Hit "Save and Continue Edit"
3. Head to "Manage Coupon Codes" Tab and generate e.g. 500 Coupons: 
Bildschirmfoto 2022-09-02 um 10 26 15

4. Hit generate and wait for completion
5. Go to generated coupon code list and hit "Mass actions" -> "Select all"
Bildschirmfoto 2022-09-02 um 10 30 28

6. All coupons (500) should now be shown as selected.
7. Choose "Export to CSV" and hit the "Export" button.
Bildschirmfoto 2022-09-02 um 10 31 46

8. The generated and downloaded file contains all 500 coupons.
9. Choose "Export to Excel XML" and hit the "Export" button.
Bildschirmfoto 2022-09-02 um 10 33 52

10. The generated and downloaded file only contains as much items, as choosen in the items per page selector. In the above mentioned example that would be 20.

### Expected result (*)
1. The export of Excel XML should contain all selected coupons. In the above mentioned example 500.

### Actual result (*)
1. The generated and downloaded file only contains as much items as selected in the items per page selector instead of the selected items itself.

### PR DESCRIPTION
**Pull request by rogerdz**
### Description (*)
Coupon codes export to Excel XML not working as expected

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36073

### Manual testing scenarios (*)

1. Create a salesrule of type "Specific Coupon" and check "Use auto generation"
2. Hit "Save and Continue Edit"
3. Head to "Manage Coupon Codes" Tab and generate e.g. 500 Coupons
4. Hit generate and wait for completion
5. Go to generated coupon code list and hit "Mass actions" -> "Select all"
6. All coupons (500) should now be shown as selected.
7. Choose "Export to CSV" and hit the "Export" button.
8. The generated and downloaded file contains all 500 coupons.
9. Choose "Export to Excel XML" and hit the "Export" button.
10. The generated and downloaded file only contains as much items, as choosen in the items per page selector. In the above mentioned example that would be 20.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Review by edenduong — APPROVED** [review]
Thank you for your contribution !
PS: Added  "auto-tests: not required" because it has the same code like that in getCsv and getXml. And this changed takes many times to write automation test.

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
Install fresh Magento `2.4-develop`

**Manual testing scenario:**

1. Create a salesrule of type "Specific Coupon" and check "Use auto generation"
2. Hit "Save and Continue Edit"
3. Head to "Manage Coupon Codes" Tab and generate e.g. 500 Coupons
4. Hit generate and wait for completion
5. Go to generated coupon code list and hit "Mass actions" -> "Select all"
6. All coupons (500) should now be shown as selected.
7. Choose "Export to CSV" and hit the "Export" button.
8. The generated and downloaded file contains all 500 coupons.
9. Choose "Export to Excel XML" and hit the "Export" button.
10. The generated and downloaded file only contains as much items, as choosen in the items per page selector. In the above mentioned example that would be 20.

**Before:** :heavy_multiplication_x: All coupons were not getting inserted in the XML file
Screenshot 2022-09-16 at 5 56 47 PM

**After:** :heavy_check_mark:  Now working fine.
Screenshot 2022-09-16 at 6 15 26 PM

**Additionally tested:**
Tested for more number of coupon codes for XML as well as for CSV file.

PR is working fine,hence , moving to merge in progress.

Thanks

**Comment by engcom-Lima** [comment]
Looking like bot has moved this ticket accidently from Merge In progress to Ready for testing. Hence, moving back to merge in progress.

**Pull request merged**
