### PR TITLE
[Framework] Fixing the caches that don't have no instance configured

### PR DESCRIPTION
**Pull request by eduard13**
### Description (*)
This PR fixes the caches that don't no instance configured, as it's an optional argument.

### Fixed Issues (if relevant)
1. magento/magento2#26224: Cache type without "instance" causes exception

### Manual testing scenarios (*)

1. Create a cache type using "cache.xml" without the "instance" argument
```xml
<config .../>
    <type name="exceptional_cache_type">
        <label>Exceptional Cache Type</label>
        <description>An exceptional cache type using a quantum computer</description>
    </type>
</config>
```
2. Go to "System > Cache Management" in the backend
3. Check the checkbox of the cache type "Exceptional Cache Type"
4. Select "Disable" and click "Submit"

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @eduard13. Thank you for your collaboration. Please, join the discussion in the original issue. We have one more option here: throw an exception with the particular message instead of accepting a cache type with no implementation. But this point needs to be discussed additionally. I haven't found a use case for a cache type with no implementation

**Comment by rogyar** [comment]
Hey @eduard13. I'm putting this PR on hold for now. We are going to discuss this topic internally. If you refer to the original issue, this case is not as straight forward as it seems to be. 

Thank you.

**Comment by eduard13** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @eduard13, here is your [Magento instance](https://i-26236-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26236-2-4-develop.instances.magento-community.engineering/admin_c85e](https://i-26236-2-4-develop.instances.magento-community.engineering/admin_c85e)
Login: `2d51cad3` Password: `cf495e4770f9`
Instance will be terminated in up to 3 hours.

**Comment by eduard13** [comment]
Closing in favor of #26933.

**Pull request closed without merging**
