### PR TITLE
Fixes wepApi functional tests php8 compatibility

### PR DESCRIPTION
**Pull request by SilinMykola**
### Description (*)
Fixes for api functional tests.

### Related Issues
1. magento/magento2#34196
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by SilinMykola** [comment]
@magento run WebAPI Tests with env PHP 8.0

**Comment by andrewbess** [comment]
@magento run all tests with env PHP 8.0

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by SilinMykola** [comment]
@magento run all tests

**Comment by SilinMykola** [comment]
@magento run WebAPI Tests with env PHP 8.0

**Comment by xmav** [comment]
@SilinMykola @andrewbess Could you please confirm that similar cases across codebase (including extensions) were checked ? I mean use of `abs` and `round` with possible non-valid input parameter type. Not all code is covered by tests so would be great to be sure that we fixed all places

**Comment by xmav** [comment]
Please check static tests failures

**Comment by SilinMykola** [comment]
@magento run WebAPI Tests with env PHP 8.0

**Comment by SilinMykola** [comment]
@magento run all tests

**Comment by SilinMykola** [comment]
@magento run WebAPI Tests with env PHP 8.0

**Comment by andrewbess** [comment]
@magento run all tests with env PHP 8.0

**Comment by xmav** [comment]
Changes in this PR covered by WebAPI tests. No extra coverage required

**Pull request merged**
