### PR TITLE
Improve address save flow to allow to use custom validators

### PR DESCRIPTION
**Pull request by vovayatsyuk**
> This is a copy of my previous PR: #7552. I've made some very bad things there, and I had to restart PR  :disappointed:

I'm facing an issue, that I cannot make some fields optional because of hardcoded
validation of address fields. Moreover, validation is made in private method, so I can't use plugin for it.

Hopefully, there is a [public validation method analogue](https://github.com/magento/magento2/blob/develop/app/code/Magento/Customer/Model/Address/AbstractAddress.php#L561), available in address class, that can be extended with plugins.

### CODE REVIEW

**Comment by vrann** [comment]
@vovayatsyuk Please check this PR https://github.com/magento/magento2/pull/8519: it fixes the similar issue of certain attributes being required. If it solves the same issue of some fields being required.

Also, can you provide more details on how do you make those fields optional?

**Comment by vrann** [comment]
@vovayatsyuk please merge the PR with the latest develop branch

**Comment by vovayatsyuk** [comment]
1. Merged. While merging, I've noticed that mine PR is already merged. I think that the #7552 was merged before.
2. I've made optional fields with [address-field-manager](http://docs.swissuplabs.com/m2/extensions/address-field-manager/). (It uses the same approach as Magento use for customer prefix, suffix, and other configurable address attributes)

**Comment by vrann** [comment]
@vovayatsyuk Hi, Pull Request now has 0 Files changed after your last commit. Can you please check what happened? You might overwritten your changes by the mainline.

**Comment by vovayatsyuk** [comment]
It is because my changes where already merged by magento team:

801c121f0fb27fa09ad860d72c9c1ae0f180ec85
bd7eecf1cb65be6ce21c630e641942f613b40265

I think there is no point to keep this ticket active. Should I close it?

**Comment by vrann** [comment]
@vovayatsyuk yes, please

**Comment by orlangur** [comment]
@vrann I've noticed in a couple of processed pull requests already that some guys are not using Git properly.

Here you can see that https://github.com/magento/magento2/pull/7882/commits/cde83ef20c2b5a645e05450dfe93ca78a203f2fb commit is present in mainline as https://github.com/magento/magento2/commit/801c121. So, somebody did inappropriate rebase which changed the hash of initial commit. With proper Git usage this PR would be marked as Merged without any additional actions.

Cc: @okorshenko, @maghamed, @ishakhsuvarov

**Comment by vovayatsyuk** [comment]
@orlangur it was me :(

In my previous PR I've made a mistake and decided to create another one. But someone from magento team already applied my changes from the first PR internally. So this PR become empty as soon as my original commit from the first PR was pushed to dev branch and I merged it in here.

p.s. I'll be careful next time..

**Comment by orlangur** [comment]
Oh :) That's totally unexpected. Sorry guys for disturbing you, I overlooked the probability of force push by PR author.

**Pull request closed without merging**
