### PR TITLE
issue #18931 fixed.

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)

Translation string was missing as the success message is updated in PR https://github.com/magento/magento2/pull/13862

### Fixed Issues (if relevant)

1. magento/magento2#18931: Product added to shopping cart / comparison list message not translated by default

### Manual testing scenarios (*)

1. Change your Locale something other than en_US. 
2. Add product to cart or Add product to Compare.
3. The success Message will not be translated.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by ghost** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul, here is your [new Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-18938/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-18938//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/pr-18938//admin)
Login: `admin` Password: `123123q`

**Comment by VladimirZaets** [comment]
Hi @ayazwebkul. Thanks for collaboration. But, I think that add HTML tag (<a href in the current case) is bad way, we don't do it. First of all because HTML template can changing any time and translation shouldn't be dependet to the view (html template). We should add to translation only plain text.

**Comment by arnoudhgz** [comment]
@VladimirZaets when I search in the translations there are quite some translations with html tags. If this indeed should be changed according to your review than also the .phtml templates must be changed:

- https://github.com/magento/magento2/commit/323246531601f3537b4316eb815e47aeb4cbbe03
- https://github.com/magento/magento2/commit/edd6062d2f40056d0a0a376fd62bbe8b67a06437

@ayazwebkul The old translation should be removed, when the strings will not be splitted.

**Comment by ghost** [comment]
@VladimirZaets as per the template, I need to put the same string in the translation file, either the template file is updated so that it doesn't contain the html tags. As I can check the wishlist module, downloadable module too contains such string. If you know the other way round for this, plz provide reference.

**Comment by ghost** [comment]
@arnoudhgz the previous string is still being used in Addgroup.php file so is not removed from translation file.
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Checkout/Controller/Cart/Addgroup.php#L100

I have removed the old string from catalog page.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3345](https://jira.corp.magento.com/browse/ENGCOM-3345) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @ayazwebkul. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
