### PR TITLE
Resolve Report->Product->Downloads has wrong ACL issue 23900

### LINKED ISSUE #23900: Report->Product->Downloads has wrong ACL
As my inspection, I see controller app/code/Magento/Reports/Controller/Adminhtml/Report/Product/Downloads.php has wrong acl in ADMIN_RESOURCE
=> admin with no permission "Report/Downloads" still access the Downloads Report.

### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Go to Store->Configuration, Advanced->Admin, Set **"Add Secret Key to URLs" : "No"**

image

2. Create New Role with followings Permission:
image
Check label "Products" but uncheck "Downloads"
3. Create New Admin User and Assign to this role.
4. Logout current admin user and login to New admin user.
5. Go to this url : http://[Magento 2 domain]/admin/reports/report_product/downloads

### Expected result (*)

1. Can not access because don't have permission
### Actual result (*)

1. Still access normally

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#23900: Report->Product->Downloads has wrong ACL

Solution: Change to correct ACL:

   ` const ADMIN_RESOURCE = 'Magento_Reports::downloads';`

in `app/code/Magento/Reports/Controller/Adminhtml/Report/Product/Downloads.php`

### Fixed Issues (if relevant)

1. magento/magento2#23900: Report->Product->Downloads has wrong ACL

### Manual testing scenarios (*)

1. Go to Store->Configuration, Advanced->Admin, Set **"Add Secret Key to URLs" : "No"**

image

2. Create New Role with followings Permission:
image
Check label "Products" but uncheck "Downloads"
3. Create New Admin User and Assign to this role.
4. Logout current admin user and login to New admin user.
5. Go to this url : http://[Magento 2 domain]/admin/reports/report_product/downloads
Expected Result: Can not access

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-5505](https://jira.corp.magento.com/browse/ENGCOM-5505) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by Stepa4man — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, thank you for the review.
[ENGCOM-5505](https://jira.corp.magento.com/browse/ENGCOM-5505) has been created to process this Pull Request
:eight_spoked_asterisk: @Stepa4man, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by edenduong** [comment]
@sivaschenko : Could I receive Bug fixed reward? Thank you :)

**Pull request merged**
