### PR TITLE
[Backport] Fixed issue #22767: Not clear logic for loading CMS Pages with setStoreId function

### LINKED ISSUE #22767: Not clear logic for loading CMS Pages with setStoreId function
### Preconditions (*)

1. 2.1.x
2. 2.2.x
3. 2.3.x

### Steps to reproduce (*)

1. Create some class that will load CMS Page:
```
 /**
     * Constructor.
     */
    public function __construct(
        \Magento\Cms\Model\PageFactory $pageFactory
    ) {
        $this->pageFactory = $pageFactory;
    }

/** @var \Magento\Cms\Model\Page $page */
$page = $this->pageFactory->create();
$page->setStoreId([2]);
$page->load($identifier, Page::IDENTIFIER);
```
2. According to description for magic function **setStoreId** must be array in Magento\Cms\Model\Page:
` * @method Page setStoreId(array $storeId)`

[Link](https://github.com/magento/magento2/blob/bd82ed4ecd5c7d66c819711a2a4425d46c232583/app/code/Magento/Cms/Model/Page.php#L19)

3. But in Magento\Cms\Model\ResourceModel\Page in method **_getLoadSelect** you have this part of code:
```
 if ($object->getStoreId()) {
            $storeIds = [
                Store::DEFAULT_STORE_ID,
                (int)$object->getStoreId(),
            ];
......
}
```
[Link](https://github.com/magento/magento2/blob/bd82ed4ecd5c7d66c819711a2a4425d46c232583/app/code/Magento/Cms/Model/ResourceModel/Page.php#L200)

4. If you will provide array it will be just 1 and not merged with provided array. 

### Expected result (*)

1. If description correct and **store_id** must be array, then in Resource Model must be changed logic for merging array
2. If it must be just **int**, then it must be changed description for magic function in Magento\Cms\Model\Page

### Actual result (*)

1. See steps

### PR DESCRIPTION
**Pull request by krishprakash**
### Original Pull Request 
 https://github.com/magento/magento2/pull/22772

Fixed: Not clear logic for loading CMS Pages with setStoreId function.
### Description (*)

In this PR, i have fixed #22767 issue.
### Fixed Issues (if relevant)

1. magento/magento2#22767
2. ...

### Manual testing scenarios (*)

1. Tested it by programmatically. 
2. 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by ronak2ram — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ronak2ram, thank you for the review.
[ENGCOM-5217](https://jira.corp.magento.com/browse/ENGCOM-5217) has been created to process this Pull Request

**Review by orlangur — CHANGES_REQUESTED** [review]
@krishprakash original commit author must be preserved

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23149) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23149) before we can accept your contribution.<br/><hr/>**Prakash Prajapati** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by krishprakash** [comment]
@orlangur I have updated the PR as suggested by you.
Please have a look and update the PR.
Thank you.

**Comment by krishprakash** [comment]
@orlangur
Is there anything remaining from my end ?
If any please let me know.
Otherwise please update the status of PR.
Thanks.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-5217](https://jira.corp.magento.com/browse/ENGCOM-5217) has been created to process this Pull Request
:eight_spoked_asterisk: @orlangur, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
