### PR TITLE
#33506: updated elasticsearch/elasticsearch composer dependency

### PR DESCRIPTION
**Pull request by korovitskyi**
### Description (*)
Updated `elasticsearch/elasticsearch` composer dependency to version 7.13.1
Reopen by https://github.com/magento/magento2/pull/33522.

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/568

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33506

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by korovitskyi** [comment]
@magento run all tests

**Comment by korovitskyi** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Unit Tests

**Comment by eduard13** [comment]
@magento run Functional Tests B2B, WebAPI Tests

**Comment by sivaschenko** [comment]
@korovitskyi thank you for your PR, can you please create related EE PR with composer.json/lock update

**Comment by Den4ik** [comment]
@korovitskyi Could you please resolve merge conflict

**Comment by korovitskyi** [comment]
Hi, @Den4ik .
Conflicts were resolved.
Thank you.

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run Functional Tests B2B

**Review by eduard13 — APPROVED** [review]

**Review by andrewbess — APPROVED** [review]
Hello @korovitskyi 
Thank you for your contribution
Great job.

**Pull request merged**
