### PR TITLE
Mitigate performance issue in #36667 during price indexing

### LINKED ISSUE #36667: Randomly getting flooded with queries from related / upsell / crosssell blocks and price indexing
### Preconditions and environment

- Magento 2.4.1
- Multiple websites at least 5 
- At least 50 price rules
- 150k products
- 800+ categories
- At least 15 customer groups

### Steps to reproduce

I don't have the exact steps, other than the fact that reindexing the price rules takes too long. However in my case I see hundreds of queries like this 

image

Which take too long to finish and drop our website

### Expected result

The site is still working and queries are much faster and won't bring the site down. 

### Actual result

The website is down with a lot of queries in queue. Over 2k siilar to this 

```
SELECT `e`.*, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`, `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price`, `cat_index`.`position` AS `cat_index_position`, `stock_status_index`.`is_salable`, `links`.`link_id`, `links`.`product_id` AS `_linked_to_product_id`, `link_attribute_position_int`.`value` AS `position` FROM `catalog_product_entity` AS `e` INNER JOIN `inventory_stock_5` AS `inventory_in_stock` ON e.sku = inventory_in_stock.sku INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.customer_group_id = 0 AND price_index.website_id = '2' INNER JOIN `catalog_category_product_index_store5` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=5 AND cat_index.visibility IN(2, 4) AND cat_index.category_id=2 INNER JOIN `catalog_product_entity` AS `product` ON product.entity_id = e.entity_id INNER JOIN `inventory_stock_5` AS `stock_status_index` ON product.sku = stock_status_index.sku INNER JOIN `catalog_product_link` AS `links` ON links.linked_product_id = e.entity_id AND links.link_type_id = 4 LEFT JOIN `catalog_product_link_attribute_int` AS `link_attribute_position_int` ON link_attribute_position_int.link_id = links.link_id AND link_attribute_position_int.product_link_attribute_id = '3' INNER JOIN `catalog_product_entity` AS `product_entity_table` ON links.product_id = product_entity_table.entity_id WHERE (inventory_in_stock.is_salable = 1) AND (stock_status_index.is_salable = 1) AND (links.product_id in ('80468')) AND (`e`.`entity_id` != '80468') ORDER BY `position` ASC
```

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by ioweb-gr**
### Description (*)

This is the first part of solving partially the issue #36667 tackling the performance issue of the queries coming from related / upsell and cross-sell blocks.

As described in #36667 the related / upsell and cross-sell blocks run a non optimized query breaking magento in MariaDB versions 10.4-10.6 because these long running queries prevent the indexer from renaming the tables creating a long running exclusive lock on the tables instead. 

https://github.com/magento/magento2/issues/36667#issuecomment-1725549906

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36667

### Manual testing scenarios (*)

1. It's not so simple to test this, you need to actually replicate the situation but you can visually check that it has an effect on the queries coming from the blocks because intially they cause a double join. With this PR the double join is removed essentially mitigating the issue. 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ioweb-gr** [comment]
@magento run all tests

**Comment by Adel-Magebinary** [comment]
Thank you for the work @ioweb-gr !  One line of code means a whole world of change for merchants using Magento 2!  I took @ioweb-gr and other guys weeks of weeks to troubleshoot this issue.

**Comment by ioweb-gr** [comment]
Thanks for the kind words. I had been struggling for months with this and you were one of the few people who tried to help. 
I just hope this will get merged to save a lot of headaches and the magento team will realistically think about revamping the indexers. Indexing has and will always be a pain for all shop owners with a lot of bugs, but dropping the whole website down just because a long select is running on the tables is something I would have never imagined. It's unrealistic to think that there are never going to be long running queries.

**Comment by hostep** [comment]
@magento run all tests

**Comment by Adel-Magebinary** [comment]
@ioweb-gr 

To save your time on the test result

```
There was 1 failure:

1) Magento\CatalogInventory\Test\Unit\Model\Plugin\ProductLinksTest::testAfterGetProductCollectionShow with data set #0 (0, 1)
Expectation failed for method name is "addInStockFilterToCollection" when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.

FAILURES!
Tests: 23311, Assertions: 72504, Failures: 1, Warnings: 12, Skipped: 115.
```

**Comment by ioweb-gr** [comment]
Ah cool it just needs to be asserted that the correct method is called not the one I removed

**Comment by hostep** [comment]
@ioweb-gr: would you like to fix the failing unit test? I think you'll need to change [this line](https://github.com/magento/magento2/blob/97e33f527a71cd8bb2c3f9ae79545fb11e5eb5b0/app/code/Magento/CatalogInventory/Test/Unit/Model/Plugin/ProductLinksTest.php#L55).
PR's can't be merged with failing tests (except for flaky tests - if any)
Also the static tests fail with:
```
FILE: /var/www/html/app/code/Magento/CatalogInventory/Model/Plugin/ProductLinks.php
-----------------------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
-----------------------------------------------------------------------------------
 38 | WARNING | Missing short description
 39 | WARNING | There must be exactly one blank line before tags
-----------------------------------------------------------------------------------
```

I know this isn't due to your change, but because this class hasn't been touched in 6 years and Magento coding standards did change over the years. They now require a short description in the phpdocs section to explain what this `afterGetProductCollection` method is good for. If you don't know a good explanation, then we'll  have to ask somebody from the internal Adobe team to try to figure this out.

It would also be appreciated if somebody from the internal team with a lot of experience in this area could review this change and confirm this is a good fix and won't cause regressions, @kandy maybe?

**Comment by ioweb-gr** [comment]
Yeah I'll submit a change for the failing test as soon as possible. Unfortunately I don't know as much about the code usage to describe it. Circumstances brought me to it unfortunately. 

As for the change itself, I still don't understand why we need two functions which do the exact same thing regarding filtering salable products based on the configuration.

I think if someone from the internal team can review it, one of the functions, the least significant one should be refactored out of the system entirely to avoid confusion on which to use or mark the one that's worse as deprecated

**Comment by ioweb-gr** [comment]
@hostep I'm not sure I understand this test warning 

`There must be exactly one blank line before tags`

Any ideas?

**Comment by hostep** [comment]
Sure, so to fix the static tests, the docblock should look a bit like so:

```
    /**
     * short description goes here  <==== adjust this
     *                              <==== here's that empty line it wants
     * @param Link $subject
     * @param Collection $collection
     * @return Collection
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
```

**Comment by ioweb-gr** [comment]
OK great, so only the description needed if someone knows exactly why this was added :)

**Comment by Nuranto** [comment]
@magento run all tests

**Comment by Nuranto** [comment]
@ioweb-gr there's still : 

```
FILE: /var/www/html/app/code/Magento/CatalogInventory/Model/Plugin/ProductLinks.php
-----------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
-----------------------------------------------------------------------------------
 38 | WARNING | Missing short description
-----------------------------------------------------------------------------------
```

**Comment by Nuranto** [comment]
Hi !

I see, the initial commit : https://github.com/magento/magento2/commit/1eaca435cff48d20e75a29f6383e90c85ce4c003

So I guess you can report the commit message as method description : `Simple product don't shown as associated in grouped when set out of stock`, or if I understand correctly, something like this `Filter on stock status based on configuration `

**Comment by ioweb-gr** [comment]
OK @Nuranto I've added the original commit message as description. Hopefully it will work out like this

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@ioweb-gr, great job!
Maybe we can make the old method as deprecated with explanation that it might lead to performance issues?
If so - I would recommend to create a separate pull request for this change, just to not block this one.

**Comment by ihor-sviziev** [comment]
@ioweb-gr i think it won't have a chance to be merged separately due to a very low priority and not clear improvement.
Maybe keep 2 separate commits, one for the fix itself and 2nd one for improving the code? So that people could apply a specific commit?

**Comment by Adel-Magebinary** [comment]
@ihor-sviziev we applied this fix on a couple of large installations. It worked perfectly and most of our db lock/index issues were fixed.  The site performance increased significantly. I don't understand why this is low priority ...

Maybe most people just didn't bother to report this issue.

**Comment by ihor-sviziev** [comment]
@Adel-Magebinary I meant that improving code style separately would be a low priority, but the fix itself is very important

**Comment by ioweb-gr** [comment]
@ihor-sviziev ok done. I used shorthand syntax which makes things 8.1+ compatible

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
As further changes have happened in this PR after approval, moving this PR back to pending review.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Static Tests, WebAPI Tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @ioweb-gr,

Thanks for the contribution!

Please resolve the static test failure.

**Comment by ioweb-gr** [comment]
Correct me if I'm wrong as I can see there is only one warning 

image

I'm assuming it's targetting this 

```
    /**
     * ProductLinks constructor.
     *
     * @param Configuration $configuration
     * @param Stock $stockHelper
     */
    public function __construct(
        private readonly Configuration $configuration,
        private readonly Stock $stockHelper
    ) {}
```

And wants it like this? 

```
    /**
     * ProductLinks constructor.
     *
     * @param Configuration $configuration
     * @param Stock $stockHelper
     */
    public function __construct(
        private readonly Configuration $configuration,
        private readonly Stock $stockHelper
    ) {
    }
```

However this syntax for the constructor in php 8.2 looks very weird. Normally constructors with no body would have the curly braces in one line after the closing parenthesis. 

Is it really OK to modify like this? @engcom-Hotel

**Comment by hostep** [comment]
@ioweb-gr: If Magento's coding standard would follow the latest [PER-CS 2.0 coding style](https://www.php-fig.org/per/coding-style/#4-classes-properties-and-methods#44-methods-and-functions) then you would be correct, as it says:
> If a function or method contains no statements or comments (such as an empty no-op implementation or when using constructor property promotion), then the body SHOULD be abbreviated as {} and placed on the same line as the previous symbol, separated by a space. For example:
> ```php
> class Point
> {
>    public function __construct(
>      public readonly int $x,
>      public readonly int $y,
>    ) {}
> }
> ```

But at the moment Magento's coding standard is a bit outdated and still follows [PSR-2](https://www.php-fig.org/psr/psr-2/) or [PSR-12](https://www.php-fig.org/psr/psr-12/) (not sure which one), which both were created before PHP 8 existed and property promotion was a feature.

So for now, unfortunately yes, please change it to put the brace on the next line. One day (hopefully) the Magento Coding standard will switch to PER-CS 2 (or newer) 🤞

**Comment by ioweb-gr** [comment]
OK done

**Comment by hostep** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

**Review by engcom-Hotel — APPROVED** [review]
Failed tests seem flaky to me, hence approving the PR.

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Hotel** [comment]
:heavy_check_mark: QA Passed

** Manual testing scenarios (*) **
It's not so simple to generate the scenario and test this PR, but as per internal discussion, we can visually check that it affects the queries coming from the blocks because initially, they cause a double join. 

With this PR the double join is removed essentially mitigating the issue. Moving this PR further by looking into code changes and comparing both the methods (Previous and Current).

**Actual Result:** :heavy_check_mark:
Mitigate performance issue in #36667 during price indexing due to double join in the query.

*Tested all the manual scenarios, no impact on regression testing.** 

Failed tests seem flaky to me, they are different in 2 consecutive runs. Please refer to the below screenshot:

**_Function Test EE:_**

[Run 1](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38050/342051c58634b9c1423af7097a0d149a/Functional/allure-report-ee/index.html#categories)

image

[Run 2](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38050/8525a29bc580dfda2f2ebcb750e8a8b5/Functional/allure-report-ee/index.html#categories)
image

**_Function Test B2B:_**

[Run 1](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38050/2d252378cf19f85e620ecef34cf84ef4/Functional/allure-report-b2b/index.html#categories)

image

[Run 2](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38050/65a0d723f502b5bb9bd421ab0efdd5d0/Functional/allure-report-b2b/index.html#categories)
image

Hence moving the PR in `Merge in progress`

Thanks

**Pull request merged**
