### PR TITLE
Added the possibility of using the Contact module's functionality in headless applications

### PR DESCRIPTION
**Pull request by bgorski**
### Description (*)
As a developer working on backends meant to be used in headless apps like PWA storefronts I would like to be able to utilize the Magento_Contact (the contact form) functionality using GraphQL. 
Currently it's not possible because there's no Magento_ContactGraphQl module that would allow that.

### Manual testing scenarios (*)
0. As a precondition, configure the Contact feature, go to `/contact/index/` on the regular magento storefront and send the form - you should receive an email. This is not part of this PR, but we'll be doing the same thing via a GraphQL mutation
1. Run the following mutation:
```
mutation {
    submitContactForm(
        input: {
            name: "John Doe",
            email: "johndoe@example.com",
            telephone: "123123123",
            comment: "I like donuts."
        }
    ) {
        success
    }
}
```
2. Test if you received an email and that the response returns `true` for the `success`.

### Questions or comments
As side effects of adding this GraphQL functionality, I did the following things:
1. Improved the re-usability of the email sending feature by moving the validation from the action class to a separate class and the quality of the Post action mostly by adding some return hints and removing the check if it's a POST request, which is obsolete now that the class implements the HttpPostActionInterface
2. The `dev/tests/integration/testsuite/Magento/Contact/Controller/IndexTest.php` test covers all my refactoring in the Magento_Contact module, so I believe that no additional Integration tests are necessary. So I added only API Functional tests to cover the GraphQL part.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36830: Added the possibility of using the Contact module's functionality in headless applications

### CODE REVIEW

**Comment by bgorski** [comment]
@magento run all tests

**Comment by bgorski** [comment]
@magento run all tests

**Comment by bgorski** [comment]
@magento run all tests

**Comment by bgorski** [comment]
@magento run all tests

**Comment by fooman** [comment]
There also seems to be a similar implementation for PWA Studio here
https://github.com/magento/magento2-pwa/tree/main/ContactGraphQlPwa

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by paales** [comment]
This is already covered by https://developer.adobe.com/commerce/webapi/graphql/schema/store/mutations/contact-us/?

**Comment by bgorski** [comment]
@paales back when I created the PR over three years ago it wasn't there, but you're correct - now it is. Closing the PR.

**Pull request closed without merging**
