### PR TITLE
Removed CliCacheFlushActionGroup usage for Downloadable and other modules

### LINKED ISSUE #32518: [Issue] Removed CliCacheFlushActionGroup usage for Downloadable and other modules
This issue is automatically created based on existing pull request: magento/magento2#32517: Removed CliCacheFlushActionGroup usage for Downloadable and other modules

---------
### Description (*)
Removed CliCacheFlushActionGroup usage for Downloadable, Elasticsearch, Elasticsearch6, Fedex, Indexer, LayeredNavigation, LoginAsCustomer, Msrp, Multishipping modules.

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Removed CliCacheFlushActionGroup usage for Downloadable, Elasticsearch, Elasticsearch6, Fedex, Indexer, LayeredNavigation, LoginAsCustomer, Msrp, Multishipping modules.

### Resolved issues:
1. [x] resolves magento/magento2#32518: Removed CliCacheFlushActionGroup usage for Downloadable and other modules

### CODE REVIEW

**Comment by sergiy-v** [comment]
@magento create issue

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Semantic Version Checker

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE

**Comment by sergiy-v** [comment]
@magento run WebAPI Tests, Unit Tests, Static Tests, Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B, Magento Health Index, Integration Tests, Database Compare

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8964](https://jira.corp.magento.com/browse/ENGCOM-8964) has been created to process this Pull Request

**Pull request merged**
