### PR TITLE
Fixed validation strategy label in import form

### PR DESCRIPTION
**Pull request by elevinskii**
### Manual testing scenarios

1. Go to Admin -> System -> Import
2. Choose any **Entity Type**
3. The label for select after **Import Behavior** field was broken

e1f119211a

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @elevinskii. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by federivo** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @federivo. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @federivo, here is your [new Magento instance](https://pr-20847.instances.magento-community.engineering).
Admin access: [https://pr-20847.instances.magento-community.engineering/admin](https://pr-20847.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by federivo — APPROVED** [review]

**Comment by federivo** [comment]
@elevinskii thanks for your contribution!

**Comment by magento-engcom-team** [comment]
Hi @federivo, thank you for the review.
[ENGCOM-4083](https://jira.corp.magento.com/browse/ENGCOM-4083) has been created to process this Pull Request

**Comment by elevinskii** [comment]
@federivo you are welcome!

**Pull request merged**
