### PR TITLE
[32032] Marked framework interfaces as API part 6

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixes https://github.com/magento/magento2/issues/32032

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/32032

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Review by coderimus — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @coderimus, thank you for the review.
[ENGCOM-8767](https://jira.corp.magento.com/browse/ENGCOM-8767) has been created to process this Pull Request

**Review by coderimus — CHANGES_REQUESTED** [review]
@Usik2203 after the investigation and communication with the community engineers we have to mark this class `Magento\Framework\Profiler\Driver\Standard\Stat` from the static test failure report as an @api. Please, mark it with the @api notation in the scope of this PR :)

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
> @Usik2203 after the investigation and communication with the community engineers we have to mark this class `Magento\Framework\Profiler\Driver\Standard\Stat` from the static test failure report as an @api. Please, mark it with the @api notation in the scope of this PR :)

Hi @coderimus 
**Done**

**Comment by eduard13** [comment]
@magento run Functional Tests B2B

**Comment by gabrieldagama** [comment]
Closed in favour of https://github.com/magento/magento2/pull/32732

**Pull request closed without merging**
