### PR TITLE
[Backport] Fix typo in SQL join when joining custom option prices for price indexer [2.2]

### PR DESCRIPTION
**Pull request by udovicic**
### Description (*)
In case where product has price variation for custom option per website, only default value (store_id = 0) is taken into an account due to typo in SQL statement.

**NOTE**: This is a copy of #19546, but for a _2.2-develop_.

### Fixed Issues (if relevant)

1. N/A

### Manual testing scenarios (*)

This one is pretty obvious from diff, but...

1. Create scenario where simple product price is regulated per website and have at least two websites
2. Set default price to amount X
3. Set price of custom option (on default view) to amount to Y
4. Switch scope to another website and set price of custom option to be 0
5. Execute price indexer
6. Difference between min and max price should be visible only on one website, however all websites will have this difference

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @udovicic. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
@udovicic thanks for your contribution, this pull request will be processed after https://github.com/magento/magento2/pull/19546 is merged

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3622](https://jira.corp.magento.com/browse/ENGCOM-3622) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @udovicic can you please include static tests fix commit https://github.com/magento/magento2/pull/19546/commits/c1be7d84b74d11455409c3ecfb12cb2bb27e3516 from the 2.3 PR in this backport

**Comment by udovicic** [comment]
@sivaschenko Changes have been pushed

**Comment by sivaschenko** [comment]
@udovicic thank you

**Comment by VasylShvorak** [comment]
✔️ QA passed

**Pull request merged**
