### PR TITLE
Issue#20277 fixed for 2.3.x

### PR DESCRIPTION
**Pull request by mahesh-rajawat**
Fixed: Downloading a file from an order where the file type custom option is no longer present results in a 404.
### Fixed Issues (if relevant)

1. #20277 
2. ...

### Manual testing scenarios (*)

1. Create a product with a custom option of the type "File"
2. Create a new order and upload a file for the product as a custom option
3. Check the order and download the file, this is working.
4. Update the product and delete the custom option from the product.
5. Go back to the order and try to download the file again. No longer 404.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3887](https://jira.corp.magento.com/browse/ENGCOM-3887) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
