### PR TITLE
Fixes to launch Magento with PHP 8.1 - part 3

### PR DESCRIPTION
**Pull request by karyna-t**
### Description (*)
Fixes for compatibility with PHP 8.1 (to be able to launch Magento)
Part 3

### Related Issues
1. magento/magento2#34505

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by xmav** [comment]
@mageto run Static Tests, Semantic Version Checker

**Comment by karyna-tsymbal-atwix** [comment]
@mageto run Static Tests, Semantic Version Checker

**Comment by andrewbess** [comment]
@mageto run Static Tests, Semantic Version Checker

**Review by ihor-sviziev — APPROVED** [review]

**Comment by xmav** [comment]
@magento run all tests with env PHP 8.1

**Comment by xmav** [comment]
@magento run Static Tests

**Comment by xmav** [comment]
@magento run Semantic Version Checker

**Review by andrewbess — APPROVED** [review]
Hello @karyna-tsymbal-atwix 
Thank you for contribution
Great work ✔️

**Comment by andrewbess** [comment]
@magento run Static Tests with env PHP 8.1

**Comment by karyna-tsymbal-atwix** [comment]
@magento run Static Tests

**Comment by andrewbess** [comment]
@magento run Static Tests

**Comment by andrewbess** [comment]
@magento run Static Tests, Semantic Version Checker

**Comment by xmav** [comment]
@magento run Static Tests, Semantic Version Checker

**Comment by xmav** [comment]
@magento import code to magento-trigger/magento2ce

**Comment by m2-github-services** [comment]
@xmav the branch with the code is successfully imported into the `magento-trigger/magento2ce` repository. Branch name: `imported-karyna-tsymbal-atwix-magento2-34640`.

**Comment by xmav** [comment]
@magento run Static Tests

**Comment by xmav** [comment]
All tests will be re-checked during delivery to 2.4-develop

**Pull request merged**
