### PR TITLE
Removed redundant header issue in grid cells while adding grouped product items after changing attribute set

### LINKED ISSUE #30911: Redundant header generated while add a product to grouped product
### Preconditions (*)
1. M2.3.x
2. M2.4.0

### Steps to reproduce (*)
1. Go Admin > Catalog > Products
2. Select Grouped Product from drop down of Add Product button
3. In new product page, at Attribute Set select, choose Top
4. Scroll down to tab Grouped Products and try add new product.
5. Got an issue [https://imgur.com/porq478](https://imgur.com/porq478)
6. Loom: https://www.loom.com/share/b28e534af9254eec99bf5fc4e77a0376

### Expected result (*)
1. [https://imgur.com/iIjvWuq](https://imgur.com/iIjvWuq)

### Actual result (*)
1. [https://imgur.com/porq478](https://imgur.com/porq478)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”.

### PR DESCRIPTION
**Pull request by saphaljha**
### Description (*)

Removed redundant header issue in grid cells while adding grouped product items after changing attribute set

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30911

### Manual testing scenarios (*)

1. Manually tested

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by saphaljha** [comment]
@magento run all tests

**Comment by saphaljha** [comment]
@magento run Functional Tests CE, Integration Tests, Functional Tests B2B

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @saphaljha, thanks for your contribution! 

Can you cover the changes with automated tests? I would recommend updating the `app/code/Magento/GroupedProduct/Test/Unit/Ui/DataProvider/Product/Form/Modifier/GroupedTest.php` test to validate/cover your changes.

Thanks.

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE, Functional Tests EE, Integration Tests, Unit Tests

**Comment by saphaljha** [comment]
> Hi @saphaljha, thanks for your contribution!
> 
> Can you cover the changes with automated tests? I would recommend updating the `app/code/Magento/GroupedProduct/Test/Unit/Ui/DataProvider/Product/Form/Modifier/GroupedTest.php` test to validate/cover your changes.
> 
> Thanks.

Hello @gabrieldagama , 

Ok sure, I'll try to cover it with MFTF, also I'll work necessary update in unit test.

Thank you

**Comment by engcom-Hotel** [comment]
@magento run Integration Tests

**Comment by engcom-Charlie** [comment]
@saphaljha I'll take care of test coverage.

**Comment by saphaljha** [comment]
Hello @engcom-Charlie, ok thank you

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8545](https://jira.corp.magento.com/browse/ENGCOM-8545) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Precondition:**

Sample Data

**Manual testing scenario:**

1. Go Admin > Catalog > Products;
2. Select Grouped Product from drop-down of **Add Product** button;
3. In the new product page, at _Attribute Set_ select, choose **Top**;
4. Scroll down to the tab **Grouped Products** and try to add a new product;

**Before:** :heavy_multiplication_x: Redundant headers generated



**After:** :heavy_check_mark: Redundant headers were not generated

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Pull request merged**
