### PR TITLE
Changes for add to cart button text translate with custom theme

### PR DESCRIPTION
**Pull request by priti2jcommerce**
Description

    The "Add to Cart" Button text is not translating correctly for custom theme after the product added to the cart.When product page load, the translation for the "Add to Cart" is working as expected and button not getting translated into "Add to Basket".

Fixed Issues (if relevant)

    #3423

Manual testing scenarios
    1.Go to app\design\frontend\package\vendor\i18n\en_US.csv
    2.changes the text
    "Add to Cart","Add to Basket"
    "Adding...","Adding Basket"
    "Added","Added Basket"
    3.And run the following commands:
    php bin/magento setup:upgrade
    php bin/magento setup:static-content:deploy
    4.On Product page goes through the process of being added to the cart as expected, when add to cart process is completed the "Add to Cart" button shows Add To Basket from the translation and this work.

Contribution checklist

    Pull request has a meaningful description of its purpose
    All commits are accompanied by meaningful commit messages
    All new or changed code is covered with unit/integration tests (if applicable)
    All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18213) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18213) before we can accept your contribution.<br/>**10** out of **11** committers have signed the CLA.<br/><br/>:white_check_mark: Drischie<br/>:white_check_mark: magento-engcom-team<br/>:white_check_mark: sidolov<br/>:white_check_mark: ronak2ram<br/>:white_check_mark: emiprotech<br/>:white_check_mark: Yogeshks<br/>:white_check_mark: gelanivishal<br/>:white_check_mark: vasilii-b<br/>:white_check_mark: arnoudhgz<br/>:white_check_mark: eduard13<br/>:x: RuslanKostiv1

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
Hi @priti2jcommerce. Looks like something went wrong upon the PR creation. As you can see, there are much more files changed than expected. Please, make sure that you have `2.3-develop` branch up to date in your forked repository, create a new branch from `2.3-develop`, make the necessary changes in the new branch, commit/push the changes into your repository and create the PR once again. I'm closing this PR and waiting for a new one.

**Comment by priti2jcommerce** [comment]
Hi @rogyar ,
Thanks for update, I will create a new pull request from 2.3-develop branch .

**Pull request closed without merging**
