### PR TITLE
[MFTF] Add StorefrontClickProceedToCheckoutActionGroup

### LINKED ISSUE #30926: [Issue] [MFTF] Add StorefrontClickProceedToCheckoutActionGroup
This issue is automatically created based on existing pull request: magento/magento2#30529: [MFTF] Add StorefrontClickProceedToCheckoutActionGroup

---------
This PR add new `StorefrontClickProceedToCheckoutActionGroup`

### PR DESCRIPTION
**Pull request by Usik2203**
This PR add new `StorefrontClickProceedToCheckoutActionGroup`
### Resolved issues:
1. [x] resolves magento/magento2#30926: [MFTF] Add StorefrontClickProceedToCheckoutActionGroup

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests EE , Functional Tests B2B

**Comment by rogyar** [comment]
Hi @Usik2203. Thanks for the refactoring. Good job! Since your edits contain backward-incompatible changes, the best way is to wait for 2.5-develop branch. I'm putting this on hold for now.

Thanks.

**Comment by rogyar** [comment]
Hi @Usik2203. Please, refer to my comment that explains a workaround for removing old steps and preserving BC

https://github.com/magento/magento2/pull/30223#discussion_r508492932

**Comment by Usik2203** [comment]
@magento run Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests B2B

**Comment by Usik2203** [comment]
Hi @rogyar
I have applied your recommendations
Seems failed test are not related with my changes.
Thanks

**Comment by rogyar** [comment]
Hi @Usik2203. Please, make sure you've adjusted this PR according to the following comment 

https://github.com/magento/magento2/pull/30525#discussion_r515237925

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
Hi @rogyar
I have applied your recommendations
Thanks :)

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8438](https://jira.corp.magento.com/browse/ENGCOM-8438) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
QA not applicable

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento create issue

**Pull request merged**
