### PR TITLE
MC-36818: Related Products, added as Scheduled Changes, remain on the Product Page on the Storefront after the End Date of the update.

### PR DESCRIPTION
**Pull request by SmVladyslav**
### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/470

### Fixed Issues (if relevant)

1. Fixes partners-magento2ee#469

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by SmVladyslav** [comment]
@magento run all tests

**Comment by SmVladyslav** [comment]
@magento run Functional Tests B2B, WebAPI Tests

**Comment by SmVladyslav** [comment]
@magento run all tests

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31951`.

**Pull request merged**
