### PR TITLE
Graphql events.xml is added for quote submit succes to trigger sales …

### PR DESCRIPTION
**Pull request by cyildirim**
…email

### Description (*)
Sales email is not sent after order placement through graphql requests. The fix includes event that triggers sales emails after order placement.

### Fixed Issues (if relevant)
#28124  is fixed with this PR.

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. set `sales_email/order/enabled` to yes
1. Follow [official graphql order placement document](https://devdocs.magento.com/guides/v2.3/graphql/tutorials/checkout/checkout-customer.html )to place order
2. Observe order confirmation email is received

### Questions or comments
I haven't seen any test related to this feature as it's used with soap and rest events.xml. I am happy to add related test if required.

### Contribution checklist (*)

 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by cyildirim** [comment]
@magento run all tests

**Comment by cyildirim** [comment]
@magento run Functional Tests B2B

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @cyildirim. Thank you for your collaboration. 

Please note, we already have the same observer registered (for the same event) in the `Quote` module.

https://github.com/magento/magento2/blob/2.3/app/code/Magento/Quote/etc/frontend/events.xml

As there result, the observer with the module that is being loaded later in the modules loading sequence will override the previous declaration. The existing issue will not be fixed in that way

**Comment by rogyar** [comment]
My fault. I've just noticed that the previous observer is registered for all areas except the GraphQl. 
Could I ask you to cover this case with integration or API-functional test, please? 

I see the integration tests as the following, you are emulating the GraphQl area and triggering the `sales_model_service_quote_submit_success` event. Then you assert that the corresponding observer is being invoked. 

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @rogyar, please review the test coverage.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7683](https://jira.corp.magento.com/browse/ENGCOM-7683) has been created to process this Pull Request

**Pull request merged**
