### PR TITLE
Update minimum required php version in bootstrap.php

### LINKED ISSUE #30004: [Issue] Update minimum required php version in bootstrap.php
This issue is automatically created based on existing pull request: magento/magento2#29993: Update minimum required php version in bootstrap.php

---------

**Preconditions:**

Magento 2.4-develop
Php v.7.2

According to the [Magento system requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements-tech.html#php), the minimum required version of php is 7.3

**Steps to reproduce:**

1. Install Magento by using a console

**Actual Result:** :heavy_multiplication_x: we are able to install Magento with PHP v 7.2

**Expected Result:** :heavy_check_mark: We should receive the message in console: 

`Magento supports PHP 7.3.0 or later. Please read https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements-tech.html`

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30004: Update minimum required php version in bootstrap.php

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by rogyar** [comment]
Nice catch! 😀

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@magento create issue

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8184](https://jira.corp.magento.com/browse/ENGCOM-8184) has been created to process this Pull Request

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8184](https://jira.corp.magento.com/browse/ENGCOM-8184) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

Magento 2.4-develop
Php v.7.2

**Manual testing scenario:**

1. Install Magento by using a console

**Before:** :heavy_multiplication_x: we are able to install Magento with PHP v 7.2

**After:** :heavy_check_mark: We receive the message in console: 

`Magento supports PHP 7.3.0 or later. Please read https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements-tech.html`

**Comment by ihor-sviziev** [comment]
Wow. Quite big list of issues caused by incorrect minimum php version check...

**Pull request merged**
