### PR TITLE
#23400: Label for custom attributes on checkout - fixed

### PR DESCRIPTION
**Pull request by sudheers-kensium**
### Description (*)

#23400: Label for custom attributes on checkout - fixed

### Fixed Issues (if relevant)

1. magento/magento2#23400: Label for custom attributes on checkout

### Manual testing scenarios (*)

1. Create custom customer address attribute
2. Set label
3. Go to checkout
4. Fill attribute
5. Go to payment
6. Attribute value will display

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @sudheers-kensium. Thanks for collaboration. Can you please explain how removing code that is responsible for manage attributes fix this issue?

**Comment by sudheers-kensium** [comment]
> Hi @sudheers-kensium. Thanks for collaboration. Can you please explain how removing code that is responsible for manage attributes fix this issue?

Hi @VladimirZaets. Due to this code customer attribute_code is displaying, so I removed the code and verified then it is working without any issue and I observed that code is not present in older versions.

**Review by VladimirZaets — APPROVED** [review]

**Comment by VladimirZaets** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, here is your [Magento instance](https://i-24056-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24056-2-3-develop.instances.magento-community.engineering/admin](https://i-24056-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5605](https://jira.corp.magento.com/browse/ENGCOM-5605) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @sudheers-kensium ! 

I'm not able to reproduce this [#23400](https://github.com/magento/magento2/issues/23400) issue providing by your steps on fresh 2.3-develop instance. 

**Manual testing scenario:**
1. Create custom customer address attribute;
2. Add product to Cart;
3. Go to checkout;
4. Fill attribute values (including custom attribute);
5. Go to payment;

**Actual Result:**

:heavy_check_mark:  Attribute value displayed
before

With your PR changes, attribute value stopped appearing.

**Actual Result:**
:heavy_multiplication_x: Attribute value not displayed

after

@sudheers-kensium Could you take a look, please?

Thanks!

**Comment by sudheers-kensium** [comment]
Hi @engcom-Alfa , Verified and reproduced the issue on Magento 2.3.1 and 2.3.2 both CE and EE.

**Comment by engcom-Alfa** [comment]
Hi @sudheers-kensium could you please provide more details how to reproduce this [issue](https://github.com/magento/magento2/issues/23400)?
Thanks!

**Comment by sudheers-kensium** [comment]
Hi @engcom-Alfa Please check below link. I have created customer address attribute with code **customcode** , label **CUSTOM VALUE!!!**  and value **Testing**
https://drive.google.com/file/d/1MmQFKsWED_jZigPQflJESvHNjk20TlTN/view

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5605](https://jira.corp.magento.com/browse/ENGCOM-5605) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by sdzhepa** [comment]
Hello @sudheers-kensium 

FYI: @VladimirZaets , @sidolov , @engcom-Alfa 

Unfortunately, we cannot accept this PR and need to find another solution to fix this issue because removing part of the code could fix this issue only partially but create new bugs for other customers/users 

After several rounds of discussion and additional testing our QAs found that such solution brings new bug for Magento Commerce Edition(EE) that was previously fixed by Magento Core team in the scop of internal jira ticket `MAGETWO-95436`



QA report quote:

> **Precondition:**
> Magento 2 EE
> Simple product is created
>
> **Steps to reproduce:**
> 1. Login to Admin;
> 2. Go to Stores→Attributes→ Customer Address→ Add New Attribute;
>     **_Dataset 1:_**
> Default Label: Test dropdown;
> Attribute Code: test_dropdown;
> Input Type: Dropdown;
> Values Required: No;
> Show on Storefront: Yes;
> Forms to Use In: (select both);
> Select the Sort Order: 10
> Options:
> -- dropdown_option_1;
> -- dropdown_option_2;
> Save attribute;
> **_Dataset 2:_**
> Default Label: Test Multiple Select;
> Attribute Code: test_multiple_selectn;
> Input Type: Multiple Select;
> Values Required: No;
> Show on Storefront: Yes;
> Forms to Use In: (select both);
> Select the Sort Order: 20
> Options:
> -- multiple_option_1;
> -- multiple_option_2;
> Save attribute;
> 3. Go to Storefront;
> 4. Add created simple product to the cart;
> 5. Click on “Proceed to Checkout” button on mini-cart;
> 6. Fill all required fields and Click on “Next” button
> 
> Actual Result: https://www.screencast.com/t/YrawPp6w

**Comment by nntoan** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @nntoan. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @nntoan, here is your [Magento instance](https://i-24056-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-24056-2-4-develop.instances.magento-community.engineering/admin_73d8](https://i-24056-2-4-develop.instances.magento-community.engineering/admin_73d8)
Login: `23bdf3dd` Password: `2687f0e14b37`
Instance will be terminated in up to 3 hours.

**Pull request closed without merging**
