### PR TITLE
Use session proxy for generic session and checkout SuccessValidator 

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
In the session constructor, we have session_start, so in order to speed up the object creation and not causing exceptions when they're not expected (during object creation), we should use Proxy for all sessions as a workaround.
More info about this issue https://github.com/magento/magento2/issues/17310#issuecomment-742422361

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by swnsma** [comment]
Wow! Brilliant idea.
Let's wait tests result :)

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE, WebAPI Tests
@swnsma pls check also https://github.com/magento/magento2/pull/31257

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, WebApi Tests

**Comment by swnsma** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, WebApi Tests

**Comment by ihor-sviziev** [comment]
Seems like we have some issue with GraphQL tests. I'll try to check them a bit later.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
In the GraphQL area, I see some test failures due to using session proxy, so here I specially defined to use NOT a proxy.

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by gabrieldagama** [comment]
Hi @engcom-Charlie, can you investigate the cause of the problem mentioned here https://github.com/magento/magento2/pull/31263#issuecomment-745411535

Thanks!

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by swnsma** [comment]
Hi @gabrieldagama, @ihor-sviziev,
What do you think, probably we should put issue with GraphQl in separated ticket?

**Comment by ihor-sviziev** [comment]
@magento combine #31257

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
@ihor-sviziev all pull requests have been successfully combined together:

**Comment by ihor-sviziev** [comment]
> While working on the fix - I found another issue in the GraphQL area - so far "not existing store" web API test cases are failing with 503 error (report page) if we're using a proxy, which is absolutely not obvious and not clear why it happening.
> 
> So far I don't have enough experience with GraphQL to fix that, so I just added to GraphQL area using not a proxy as a workaround for now.

Ok... After a long debug session and discussions with @engcom-Charlie, I found the reason why it wasn't failing before my changes and started failing:
<details>
  <summary>Before my changes</summary>


  1. creates Magento\GraphQl\Controller\GraphQl
  2. it depends on Magento\GraphQl\Controller\HttpRequestProcessor
  3. it depends on graphQlHeaders --> Magento\DirectoryGraphQl\Controller\HttpHeaderProcessor\CurrencyProcessor
  4. it depends on Magento\Framework\Session\SessionManagerInterface --> Magento\Framework\Session\Generic
  5. it depends on Magento\Framework\Session\Config\ConfigInterface --> Magento\Framework\Session\Config
  6. inside constructor it calls `$this->_scopeConfig->getValue()`, that calls `$this->scopeCodeResolver->resolve($scope, $scopeCode)`, that calls `\Magento\Store\Model\Resolver\Store::getScope(NULL)`.
  This method returns current (or default store) and nothing is failing! ✔
  
  
</details>

<details>
  <summary>After my changes (w/o changes in graphql module)</summary>

  1. creates Magento\GraphQl\Controller\GraphQl
  2. it depends on Magento\GraphQl\Controller\HttpRequestProcessor
  3. it depends on graphQlHeaders --> Magento\DirectoryGraphQl\Controller\HttpHeaderProcessor\CurrencyProcessor
  4. it depends on Magento\Framework\Session\SessionManagerInterface --> Magento\Framework\Session\Generic\Proxy
  <-- It doesn't failing because it's just a proxy that isn't calling constructor yet!
  5. executes `\Magento\StoreGraphQl\Controller\HttpHeaderProcessor\StoreProcessor::processHeaderValue` that setting current store to `non_existing_store`
 <-- here it's not failing because it's not trying to retrieve current store
  6. executes `\Magento\DirectoryGraphQl\Controller\HttpHeaderProcessor\CurrencyProcessor::processHeaderValue`
  7. that calls `$this->session->getCurrencyCode()` (Magento\Framework\Session\Generic really creates here, earlier it was just a proxy)
  8. it depends on Magento\Framework\Session\Config\ConfigInterface --> Magento\Framework\Session\Config
  6. inside constructor it calls `$this->_scopeConfig->getValue()`, that calls `$this->scopeCodeResolver->resolve($scope, $scopeCode)`, that calls `\Magento\Store\Model\Resolver\Store::getScope(NULL)`.
  <-- Here it fails because current store is set to "non_existing_store" and such store can't be found. ❌
</details>

**Comment by ihor-sviziev** [comment]
@sidolov @gabrieldagama seems like combining PRs feature stopped to work

**Comment by sidolov** [comment]
@magento combine 31257

**Comment by magento-engcom-team** [comment]
Hi @sidolov. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
@ihor-sviziev all pull requests have been successfully combined together: 
 - merged https://github.com/magento/magento2/pull/31257: Use session proxy for checkout SuccessValidator

**Comment by sidolov** [comment]
@ihor-sviziev you used an incorrect message pattern, PRs successfully combined.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

I just reported a GraphQL area related issue, it should be fixed separetely. https://github.com/magento/magento2/issues/31336.
I believe we can test it

**Comment by ihor-sviziev** [comment]
I found that `Magento\Framework\Session\Config` has quite a heavy constructor that tries to get value from config, that later on tries to detect current store. Seems like this also works as a workaround for graphql test failures.
@magento run all tests.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
As an alternative solution, I created https://github.com/magento/magento2/pull/31350 that should probably fix this issue in all the places altogether, if it will work.

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@magento run WebAPI Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@swnsma i believe you could review this PR

**Comment by swnsma** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@swnsma all tests are passed ✅

**Review by swnsma — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@swnsma I believe automated tests are not suitable here, right? Can we add label that auto tests not required?

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @ihor-sviziev .

It seems that the problem is not completely solved for checkout.

**Manual testing scenario:**

1. Go to Storefront;
2. Add product to Cart;
3. Proceed to Checkout;
4. Reload the page several times (10 for ex)

**Actual Result:** :heavy_multiplication_x: session_start(): Failed to read session data...

Screenshot from 2020-12-21 15-46-56


This error occurs at all stages of order creation and on the view pages.
@ihor-sviziev Could you take a look?
Thanks!

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-8565](https://jira.corp.magento.com/browse/ENGCOM-8565) has been created to process this Pull Request

**Comment by engcom-Charlie** [comment]
Hello @ihor-sviziev could you please look at https://github.com/magento/magento2/pull/31263#pullrequestreview-556389304?
Thank you.

**Comment by ihor-sviziev** [comment]
Now on vacation, will back in 1 week

**Comment by engcom-Charlie** [comment]
Hello, @ihor-sviziev do you have any updates?

**Comment by ihor-sviziev** [comment]
For now, I'm closing this PR. I will update and re-open it when will have some free time for that

**Pull request closed without merging**
