### PR TITLE
Import error message does not insert variable

### PR DESCRIPTION
**Pull request by ghost**
Hi,

this is a PR for _Import error message does not insert variable #2844_.
Just stored the row in which the error happens to improve error out.

Please let me know if this is fine.

Best

### CODE REVIEW

**Comment by daim2k5** [comment]
Thank you for the PR! We are currently waiting for the travis builds to work again, which should happen in a few days. Once that is running and the tests are green we can continue to process your contribution.

**Comment by ghost** [comment]
thanks for the reply. I already wondered if I did something wrong because of the failing build.
so lets wait for this to work

best

**Comment by vkholoshenko** [comment]
@xhallix, team is processing your pull-request right now (internal reference: MAGETWO-47555). Is there any reason to close the ticket?

**Comment by ghost** [comment]
Hi,

yes, I just made this from the development Branch of my fork and wanted to work on this branch for other prs.
therefore I opened a new pr from a dedicated branch
 Import message missing variable #3035

Please use this PR #3035 since the develop does not include the fix.
sorry for confusion.

**Comment by xhallix** [comment]
in addition to the comment above:

I made this PR Import message missing variable #3035

**Comment by xhallix** [comment]
please use this PR above for Integration

**Comment by vkholoshenko** [comment]
@xhallix, thanks.

**Pull request closed without merging**
