### PR TITLE
Email sending events

### PR DESCRIPTION
**Pull request by ghost**
Part of the same project as Pull Requests #1199 and #1201 - refer there for background information.

This pull requests adds events during the email sending process of transactional sales emails. The events allows any extension to add arbitrary objects to be used in the email templates.

### CODE REVIEW

**Comment by kandy** [comment]
@fooman, Do not you think that is strange to copy the same code in different places? I believe that same can be implemented using Interceptors

**Comment by fooman** [comment]
@kandy strange? possibly. I have only started working with Magento2 and it seems to require a lot more explicit code mentions to get things done (most of the code is really getting the event manager into the functions). How the code is currently structured I don't think the interceptor approach will work as well. However feel free to create a different pull request for Magento to consider.

**Comment by fooman** [comment]
Looks like the latest version created a merge conflict. Will take a look into this after Imagine.

**Comment by vpelipenko** [comment]
@fooman, did you have a time to look at conflict?

**Comment by fooman** [comment]
Just catching up - have taken care of the merge conflicts.

**Comment by vpelipenko** [comment]
CR: passed
Builds: green
Resolution: OK to merge
Internal ticket: MAGETWO-36735

**Pull request merged**
