### PR TITLE
Removed CliCacheFlushActionGroup usage for Sales module

### LINKED ISSUE #31937: [Issue] Removed CliCacheFlushActionGroup usage for Sales module
This issue is automatically created based on existing pull request: magento/magento2#31936: Removed CliCacheFlushActionGroup usage for Sales module

---------
### Description
Removed CliCacheFlushActionGroup usage for Sales, SalesRule, Search, Shipping and Store modules.

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Removed CliCacheFlushActionGroup usage for Sales, SalesRule, Search, Shipping and Store modules.

### Resolved issues:
1. [x] resolves magento/magento2#31937: Removed CliCacheFlushActionGroup usage for Sales module

### CODE REVIEW

**Comment by sergiy-v** [comment]
@magento create issue

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B,Semantic Version Checker

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Magento Health Index, Semantic Version Checker, Static Tests

**Comment by ihor-sviziev** [comment]
@sivaschenko magento don't want to run tests. could you check that?

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE, Functional Tests CE

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Hotel** [comment]
Hello @sergiy-v,
Could you please resolve conflicts?

**Comment by sergiy-v** [comment]
@magento run all tests

**Comment by sergiy-v** [comment]
> Hello @sergiy-v,
> Could you please resolve conflicts?

Hello @engcom-Hotel.
The conflicts has been resolved. Will check tests result later today.
Thank you.

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8721](https://jira.corp.magento.com/browse/ENGCOM-8721) has been created to process this Pull Request

**Comment by sergiy-v** [comment]
@engcom-Hotel all tests are green, please proceed.
Thank you.

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Pull request merged**
