### PR TITLE
Fixed issue of drop-down arrow direction in cart price rule

### PR DESCRIPTION
**Pull request by hiren0241**
### Description (*)

Fixed issue of drop-down arrow direction in cart price rule. 

### Fixed Issues (if relevant)

1. magento/magento2#22434: While add cart price rule from admin click on Condition drop-down arrow direction not change.

### Manual testing scenarios (*)

1. Go to Admin
2. Marketing > Cart Price rule
3. Conditions > Click on +
4. Open/close and review the Drop-down arrow direction
5. Drop down arrow should be changes as per other drop-downs

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by hiren0241** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @hiren0241. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @hiren0241, here is your [new Magento instance](https://pr-22456.instances.magento-community.engineering).
Admin access: [https://pr-22456.instances.magento-community.engineering/admin](https://pr-22456.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by ronak2ram — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ronak2ram, thank you for the review.
[ENGCOM-4797](https://jira.corp.magento.com/browse/ENGCOM-4797) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Comment by meker12** [comment]
Release note: 

**UI**
In the _Conditions_ section of the _New Cart Price Rule_ page in the Magento Admin, the dropdown arrow in the _If ALL  of these conditions are TRUE _ field now points in the correct direction.

**Pull request merged**
