### PR TITLE
Fixed issue #21650

### PR DESCRIPTION
**Pull request by geet07**
### Description (*)
Saving product with options with thousands separator in price fails.

### Fixed Issues (if relevant)

1. magento/magento2#<21650>: Saving product with options with thousands separator in price fails

### Manual testing scenarios (*)

1. Add Product with custom options (Price: 1000).
2.  Once Product saved, Again edit the same product with custom options now you can save all values sucessfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22699) <br/>All committers have signed the CLA.

**Review by orlangur — CHANGES_REQUESTED** [review]
@geet07 we cannot simply remove validation. Corrected validator must be used instead.

**Comment by geet07** [comment]
> @geet07 we cannot simply remove validation. Corrected validator must be used instead.

Hi @orlangur,

Thank you for message.

As per your comment I have added validation same a catalog main price. So now you can check this and  let me know if there is another changes reqiured.

**Comment by orlangur** [comment]
Thanks @geet07! Did you check implementation why `validate-number` is not working?

**Comment by geet07** [comment]
> Thanks @geet07! Did you check implementation why `validate-number` is not working ?

Yes I have checked, When we change the locale for admin user then there will be change in price format, So due to this "thousands separator" position also change & that 'validation-number' validation doesn't work too. I have also checked with other price field that 'validation-number' validation not use in the current system.

**Comment by geet07** [comment]
Hi @orlangur, 

Is there any another changes required?

**Comment by geet07** [comment]
Hi @orlangur,

Can You please help me to close this issue.

**Pull request closed without merging**
