### PR TITLE
Adding Italian language package

### PR DESCRIPTION
**Pull request by WaPoNe**
### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21013) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @WaPoNe. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by WaPoNe** [comment]
Adding Italian language package

**Review by aleron75 — COMMENTED** [review]
Hello @WaPoNe thanks for your contribution.

In order to make static test go green, in language pack's `composer.json` please remove version and set dependency from `magento/framework` to `*`.

Finally, add `"magento/language-it_it": "*"` in the `replace` node of root `composer.json`

**Comment by hostep** [comment]
@WaPoNe: out of curiosity, what does this PR actually achieve? I don't see any translations in your PR?

Maybe I'm missing something obvious here, but I never quite understood what those [built-in language packs](https://github.com/magento/magento2/tree/ca42e4205c96f6a16ec45a82176c38702d9e725d/app/i18n/Magento) do in Magento, there's just nothing in there?

**Comment by WaPoNe** [comment]
@aleron75 : Done!

**Comment by WaPoNe** [comment]
Conflicts resolved

**Comment by WaPoNe** [comment]
@hostep : you're right. My PR does not achieve anything special; it just adds Italian language to built-in language packs ;-)

**Comment by hostep** [comment]
@WaPoNe: ok, and can you explain what this means exactly? Does it help in some way, or how can we see the improvement which is being done by this PR?

**Comment by aleron75** [comment]
> Does it help in some way, or how can we see the improvement which is being done by this PR?

Hello @hostep I see the point of your question but I also think that if other language packs are there in the same format we should wonder what is the value of all of them, not only of this one.

In other words, should we accept this or remove the others?

**Comment by hostep** [comment]
I agree, never quite understood what those other empty language packs do in core Magento.
If there is no purpose for them, they should probably be removed indeed.

**Comment by WaPoNe** [comment]
My idea reflects the @aleron75 one: you should decide to accept this language pack or to remove the others?
@hostep what is the final decision?

**Comment by hostep** [comment]
@WaPoNe: well I can't really give a hard decision here, since I'm only a community contributor, not a member of the core Magento team :)

I'm currently trying to understand why these are here in the first place, to understand the history and trying to figure out if they still have a purpose.

So, they got introduced in https://github.com/magento/magento2/commit/974d259df65aef731626aa41228e76c3763235b3
The most relevant part of the commit message seems to be:
```
* Framework improvements:
  * Introduced language packages with ability to inherit dictionaries
```
In that commit, I can see some csv files in various modules which still got translated texts, for example, in the csv file for French in the Catalog module: `app/code/Magento/Catalog/i18n/fr_FR.csv`, there are still translated phrases in there:
`"Error during retrieval of option value: %s","Erreur lors de la récupération de la valeur de l'option:% s"`

So at that point, these (empty) translations packs probably made the non-English translations from the various `.csv` files work if I have to guess, since there needs to be some sort of entry point for a translation pack to register itself to Magento.

Then fast forward 17 months, and I find a new commit, where most of these non-English `.csv` files got removed: https://github.com/magento/magento2/commit/9736c70b800
If I have to guess again: Magento probably didn't want to ship with partially translated phrases and didn't want to maintain these themselves.
Two months before the removal of these `.csv` files, Ben announced that they were going to work with crowdin for the translations: https://community.magento.com/t5/News-Announcements/Translating-Magento/td-p/16945

Strangely enough the current codebase still contains some of these non-English `.csv` files, for example:
```bash
$ find . -type f -iname 'fr_FR.csv'
./app/code/Magento/Ui/i18n/fr_FR.csv
./app/code/Magento/ProductVideo/i18n/fr_FR.csv
./app/code/Magento/Search/i18n/fr_FR.csv
./app/code/Magento/Msrp/i18n/fr_FR.csv
./app/code/Magento/Swatches/i18n/fr_FR.csv
./app/code/Magento/Developer/i18n/fr_FR.csv
```
None of these seem to contain translations in French at first sight, just English.
It looks like those got introduced by https://github.com/magento/magento2/commit/b9ecb3bc97b, which was merged a day after all the others got removed. I'm guessing there were some merge conflicts here and some new files which were introduced on this branch probably didn't conflict and got introduced without anyone noticing.

---

Anyways, so far for looking back in the history.

My conclusion is: these empty language packs are probably a left-over from the days where Magento was still maintaining translations themselves. This later got outsourced to the community using crowdin. The idea might have been to regularly pull in translations from crowdin in the Magento core, but until this day, this doesn't seem to have happened and might not happen at all in the future, I have no idea if there are still plans in that direction? (@buskamuza ?)

If there are no further plans from Magento to take care of non-English translations, it would make sense to remove the current language modules from the core, except for the English one, so these directories can probably be removed:
- app/i18n/Magento/de_DE
- app/i18n/Magento/es_ES
- app/i18n/Magento/fr_FR
- app/i18n/Magento/nl_NL
- app/i18n/Magento/pt_BR
- app/i18n/Magento/zh_Hans_CN

Next to those directories, the following files should probably be removed as well:
- app/code/Magento/Developer/i18n/de_DE.csv
- app/code/Magento/Developer/i18n/es_ES.csv
- app/code/Magento/Developer/i18n/fr_FR.csv
- app/code/Magento/Developer/i18n/nl_NL.csv
- app/code/Magento/Developer/i18n/pt_BR.csv
- app/code/Magento/Developer/i18n/zh_Hans_CN.csv
- app/code/Magento/Msrp/i18n/de_DE.csv
- app/code/Magento/Msrp/i18n/es_ES.csv
- app/code/Magento/Msrp/i18n/fr_FR.csv
- app/code/Magento/Msrp/i18n/nl_NL.csv
- app/code/Magento/Msrp/i18n/pt_BR.csv
- app/code/Magento/Msrp/i18n/zh_Hans_CN.csv
- app/code/Magento/ProductVideo/i18n/de_DE.csv
- app/code/Magento/ProductVideo/i18n/es_ES.csv
- app/code/Magento/ProductVideo/i18n/fr_FR.csv
- app/code/Magento/ProductVideo/i18n/nl_NL.csv
- app/code/Magento/ProductVideo/i18n/pt_BR.csv
- app/code/Magento/ProductVideo/i18n/zh_Hans_CN.csv
- app/code/Magento/Search/i18n/de_DE.csv
- app/code/Magento/Search/i18n/es_ES.csv
- app/code/Magento/Search/i18n/fr_FR.csv
- app/code/Magento/Search/i18n/nl_NL.csv
- app/code/Magento/Search/i18n/pt_BR.csv
- app/code/Magento/Search/i18n/zh_Hans_CN.csv
- app/code/Magento/Swatches/i18n/de_DE.csv
- app/code/Magento/Swatches/i18n/es_ES.csv
- app/code/Magento/Swatches/i18n/fr_FR.csv
- app/code/Magento/Swatches/i18n/nl_NL.csv
- app/code/Magento/Swatches/i18n/pt_BR.csv
- app/code/Magento/Swatches/i18n/zh_Hans_CN.csv
- app/code/Magento/Ui/i18n/de_DE.csv
- app/code/Magento/Ui/i18n/es_ES.csv
- app/code/Magento/Ui/i18n/fr_FR.csv
- app/code/Magento/Ui/i18n/nl_NL.csv
- app/code/Magento/Ui/i18n/pt_BR.csv
- app/code/Magento/Ui/i18n/zh_Hans_CN.csv

Next to those, there are some German translation files being used in the integration tests, but I don't think those can be removed:
- dev/tests/integration/testsuite/Magento/Setup/Module/I18n/Pack/_files/expected/app/design/adminhtml/default/i18n/de_DE.csv
- dev/tests/integration/testsuite/Magento/Setup/Module/I18n/Pack/_files/expected/app/code/Magento/FirstModule/i18n/de_DE.csv
- dev/tests/integration/testsuite/Magento/Setup/Module/I18n/Pack/_files/expected/app/code/Magento/SecondModule/i18n/de_DE.csv
- dev/tests/integration/testsuite/Magento/Setup/Module/I18n/Pack/_files/expected/lib/web/i18n/de_DE.csv

@WaPoNe: maybe hold of a few days until somebody from core Magento can give some feedback here, that might be safest?

**Comment by WaPoNe** [comment]
@hostep : ok.. we'll wait for the safest decision by the Magento core members.

**Comment by hostep** [comment]
@WaPoNe: after talking a little bit with @vkublytskyi on [Slack](https://magentocommeng.slack.com/archives/CD97DKBHS/p1553525571012600) in the `#translations` channel, it looks like this PR is not going to get accepted:
> I don’t see any real benefits from adding Italian or any other language pack to the core because of one simple reason. None of them except en_US  does not contain even a single phrase. And this is actually one of reason why we start [the new project](https://twitter.com/hashtag/MagentoTranslation) with Community as the main goals, for now, are simplify the process of translation and have automated builds and releasing of language packages.

But we also can't remove the current existing language packs:
> Removing of them would be backward incompatible change as if some 3rd party module contains translations for language declared in core language package they will be broken. When we will have packages build from Crowdin translations I think we will be able to mark language packages in core as “abandoned” (in composer.json) with reference to new packages

What we can do however is removing that list of non-English csv files inside the various Magento modules. I've just created a PR for this over here: https://github.com/magento/magento2/pull/21927

I hope you don't mind me closing this PR?
Thanks for the effort though! :)

**Pull request closed without merging**
