### PR TITLE
Add get filter method

### PR DESCRIPTION
**Pull request by embed0**
### Description
In case you would like to add count of products for swatches, the count number of products for swatch is stored in this field which is protected and other methods like getOptionViewData(FilterItem $filterItem, Option $swatchOption) are also protected.

### Fixed Issues
 - Provide method to get filter data without the need to extend the block and use of preference

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14581) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=14581) before we can accept your contribution.<br/>

**Comment by larsroettig** [comment]
Hi @embed0,
 thank you for your first contribution pls sign our Contributor License Agreement
https://cla.dev.magento.com/magento/magento2?pullRequest=14581

best regards,

Lars

**Review by orlangur — COMMENTED** [review]
> In case you would like to add count of products for swatches, the count number of products for swatch is stored in this field which is protected and other methods like getOptionViewData(FilterItem $filterItem, Option $swatchOption) are also protected

They are protected intentionally. Such proposed getter would break class encapsulation. Instead of increasing amount of public class methods `getSwatchData` should be expanded in described scenario.

**Comment by orlangur** [comment]
Hi @embed0, thanks for your endeavors, please try to implement needed customization the way I referred to. If you believe Magento lacks some extension points, let's try to figure out where they needs to be added, just that we shouldn't add random getters here and there just to access the class internals (example of such collaboration: https://github.com/magento/magento2/pull/13414).

**Pull request closed without merging**
