### PR TITLE
Fix order spam when search engine is down

### LINKED ISSUE #36119: Magento 2.4.x When Elasticsearch doesn't work, orderings will be unlimitedly spammed.
### Preconditions and environment

- Magento 2.4.x
- Catalog Search Engine was set Elasticsearch7

### Steps to reproduce

- Add to cart
- Go checkout page
- Disable Elasticsearch service (Elasticsearch suddenly stop working)
- Click Place Order button
- An error message was shown but order was still placed.
- You can spam "Click Place Order" more one times without limit action and the orders would be placed without any mechanism which prevents Place Order action.
- If your store have Credit or Reward Points features(can be checked in EE ). In this case, customer can apply credit points to get $0 order without being subtracted any credit points.

### Expected result

- Order is not placed successfully
- Order should not spammed.
- Admin should not be able to do invoice,shipping etc.

### Actual result

- Order is placed successfully
- Can spam Place Order to make many orders at the same time.
- https://www.loom.com/share/00369a0f855a4e50be2e5594bc92ddb7
- Admin is be able to do invoice,shipping etc.

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### LINKED ISSUE #36349: [Issue] Fix order spam when search engine is down
This issue is automatically created based on existing pull request: magento/magento2#36241: Fix order spam when search engine is down

---------

### Description (*)

**Orders can be spammed if the search engine service is down and the Catalog Search index mode is set to Update on Save.**
This is caused by an unhandled exception on the "Magento\CatalogInventory\Observer\ReindexQuoteInventoryObserver" observer for the "sales_model_service_quote_submit_success"event. The exception is caused because both price and stock catalog re-indexation trigger a fulltext re-index. The solution I found was to handle the exception during the observer execution and invalidate the offending indexes for later re-indexation.
### Fixed Issues (if relevant)

1. Fixes magento/magento2#36119

### Manual testing scenarios (*)

1. Add to cart
2. Go checkout page
3. Disable Elasticsearch service (Elasticsearch suddenly stop working)
4. Click Place Order button

**Expected result**
The order is placed without any issues and both Produce Price and Stock Indexes should be invalidated (reindex required in the admin dashboard).
image
image

### Questions or comments

One of the items listed in the expected scenario proposed in the issue ("Admin should not be able to do invoice,shipping etc.") should not be considered since the order can be placed correctly when the search engine is not working and the issue with the order spamming can be resolved by correctly handling the exception thrown after the order is already placed.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by texboy**
### Description (*)

**Orders can be spammed if the search engine service is down and the Catalog Search index mode is set to Update on Save.**
This is caused by an unhandled exception on the "Magento\CatalogInventory\Observer\ReindexQuoteInventoryObserver" observer for the "sales_model_service_quote_submit_success"event. The exception is caused because both price and stock catalog re-indexation trigger a fulltext re-index. The solution I found was to handle the exception during the observer execution and invalidate the offending indexes for later re-indexation.
### Fixed Issues (if relevant)

1. Fixes magento/magento2#36119

### Manual testing scenarios (*)

1. Add to cart
2. Go checkout page
3. Disable Elasticsearch service (Elasticsearch suddenly stop working)
4. Go to index management and select all and change the indexes to update on save.
5. Click Place Order button

**Expected result**
The order is placed without any issues and both Produce Price and Stock Indexes should be invalidated (reindex required in the admin dashboard).
image
image

### Questions or comments

One of the items listed in the expected scenario proposed in the issue ("Admin should not be able to do invoice,shipping etc.") should not be considered since the order can be placed correctly when the search engine is not working and the issue with the order spamming can be resolved by correctly handling the exception thrown after the order is already placed.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36349: Fix order spam when search engine is down

### CODE REVIEW

**Comment by texboy** [comment]
@magento run all tests

**Comment by texboy** [comment]
@magento run WebAPI Tests

**Comment by texboy** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by texboy** [comment]
https://github.com/magento run Functional Tests B2B , Functional Tests CE , Functional Tests EE

**Comment by texboy** [comment]
@magento run Functional Tests B2B , Functional Tests CE , Functional Tests EE

**Comment by texboy** [comment]
@magento run Functional Tests B2B , Functional Tests CE , Functional Tests EE

**Comment by texboy** [comment]
@magento run all tests

**Comment by texboy** [comment]
https://github.com/magento run all tests

**Comment by texboy** [comment]
@magento run all tests

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE

**Comment by engcom-Lima** [comment]
Hi @texboy ,

Thanks for your contribution and collaboration.

I have tested this PR , I am able to place an order successfully without spamming but as given in your expected result "both Produce Price and Stock Indexes should be invalidated (reindex required in the admin dashboard)."  this is not happening in my case. Kindly provide more information how to get this.

Thanks

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE

**Comment by texboy** [comment]
Hi @engcom-Lima! Thanks for running the tests! Please make sure that the indexes are set to "Update on save" on your test environment:

- Go to Systems -> Index Management
  - image
- Select all indexes and change the indexes to update on save:
  - image

- Kill the elasticsearch service by identifying the service PID and killing it with the following commands:
`ps -ef | grep elas`
`sudo kill <PID-NUMBER>`
  - image

- Place the order:
  - image

- Check indexes on admin:
  - image

**Comment by texboy** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
Install fresh Magento `2.4-develop`

**Manual testing scenario:**
1. Add to cart
2. Go checkout page
3. Disable Elasticsearch service (Elasticsearch suddenly stop working)
4. Go to index management and select all and change the indexes to update on save.
5. Click Place Order button

**Before:** :heavy_multiplication_x: 
**Getting error but Order was placed:**
image

**Order is spammed:**
Screenshot 2022-10-21 at 5 12 44 PM


**After:** :heavy_check_mark:  
**Order is placed without spamming:**
image

**INDEXERS:**
Screenshot 2022-10-21 at 5 38 32 PM

Builds are failed, hence moving this PR to extended testing.

**Comment by engcom-Echo** [comment]
@magento run Integration Tests, Functional Tests EE

**Pull request merged**
