### PR TITLE
Fix cache update on switch to virtual cart

### LINKED ISSUE #37204: [Issue] Fix cache update on switch to virtual cart
This issue is automatically created based on existing pull request: magento/magento2#36838: Fix cache update on switch to virtual cart

---------

### Description (*)

On GraphQL context, we found a problem of updating the cache related to the **getAllItems** function in **app/code/Magento/Quote/Model/Quote/Address.php**. When we do the following steps : 

- Create a promo code to auto add a free product related to a physical product 
- Login to an account.
- Add a virtual product
- Add a physical product (related to a promo code you have created)
- Apply a coupon code to have an auto add promo product
- Remove the physical, so the auto added product will be removed and have only the virtual product on cart

The cart will be **free** even if we have a product on cart ! 

The problem is the items cache in Address model is empty due to the following code : 
`
  $canAddItems = $this->getQuote()->isVirtual()
                    ? $addressType == self::TYPE_BILLING
                    : $addressType == self::TYPE_SHIPPING;
`

The quote type is switched before the cache reset !

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by aelmizeb**
### Description (*)

On GraphQL context, we found a problem of updating the cache related to the **getAllItems** function in **app/code/Magento/Quote/Model/Quote/Address.php**. When we do the following steps : 

- Create a promo code to auto add a free product related to a physical product 
- Login to an account.
- Add a virtual product
- Add a physical product (related to a promo code you have created)
- Apply a coupon code to have an auto add promo product
- Remove the physical, so the auto added product will be removed and have only the virtual product on cart

The cart will be **free** even if we have a product on cart ! 

The problem is the items cache in Address model is empty due to the following code : 
`
  $canAddItems = $this->getQuote()->isVirtual()
                    ? $addressType == self::TYPE_BILLING
                    : $addressType == self::TYPE_SHIPPING;
`

The quote type is switched before the cache reset !

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37204: Fix cache update on switch to virtual cart

### CODE REVIEW

**Comment by aelmizeb** [comment]
https://github.com/magento  run all tests

**Comment by aelmizeb** [comment]
@magento run all tests

**Comment by chernenm** [comment]
@magento create issue

**Comment by chernenm** [comment]
The original issue is not reproducible anymore.

**Comment by ThomasHWeb** [comment]
@chernenm I had the same issue. Thanks to the changes from @aelmizeb, it fixed it.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
Hello @aelmizeb,

Thanks for the contribution!

We have tried to reproduce the issue in the 2.4-develop branch but the actual doesn't seem to be reproducible for us. The scenario mentioned in the main description is not able to reproducible. 

Please refer to the below screenshot of our cart price rule and let us know if we have missed anything:

image

Till the time we are moving this PR `On Hold`.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @aelmizeb,

As per this comment https://github.com/magento/magento2/pull/36838#issuecomment-1661969613, we are unable to reproduce the issue. 

We request you to please go through with the comment and let us know if we have missed anything. 

We are closing this PR for now.

Let us know when you are ready to work on it again, and we will be happy to re-open it. Thank you for your contribution!

Thanks

**Pull request closed without merging**
