### PR TITLE
[Backport] Adjusted documentation for ReadInterface to reflect Exception

### PR DESCRIPTION
**Pull request by mageprince**
### Original Pull Request 
 https://github.com/magento/magento2/pull/20283

### Description (*)

`openFile` ends up calling `magento/framework/Filesystem/DriverInterface.php` -> `fileOpen` which can throw a `Magento\Framework\Exception\FileSystemException`. My proposed change adds the exception to the documentation for the method.

### Fixed Issues (if relevant)

Not relevant.

### Manual testing scenarios (*)

Not relevant for this code change, as it involves only documentation.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mageprince. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
Hi @mageprince. Thank you for your collaboration. This change is considered as code cleanup. According to the contribution guide (https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#rules) a code cleanup cannot be accepted to 2.2-develop branch.

**Comment by rogyar** [comment]
Hi @mageprince. Thank you for collaboration. According to the contributors guide https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#rules the code cleanup cannot be accepted to 2.2-develop branch (including backports)

**Comment by mageprince** [comment]
@rogyar Thanks for your review. I didn't know about these updates. I will take care of it next time :)

**Pull request closed without merging**
