### PR TITLE
Fixed double URL Rewrite when category have 301 redirect

### LINKED ISSUE #35758: [Issue] Fixed double URL Rewrite when category have 301 redirect
This issue is automatically created based on existing pull request: magento/magento2#35736: Fixed double URL Rewrite when category have 301 redirect

---------
### Description (*)
Fixed  issue "Item (Magento\Catalog\Model\Category\Interceptor) with the same ID "n" already exists."
if category have 301 Redirect

this issue happend if generate url using Magento\CatalogUrlRewrite\Model\CategoryUrlRewriteGenerator->generate
this methot alvays add is_autogenerated = 1

### PR DESCRIPTION
**Pull request by hryvinskyi**
### Description (*)
Fixed  issue "Item (Magento\Catalog\Model\Category\Interceptor) with the same ID "n" already exists."
if category have 301 Redirect

this issue happend if generate url using Magento\CatalogUrlRewrite\Model\CategoryUrlRewriteGenerator->generate
this methot alvays add is_autogenerated = 1

### Resolved issues:
1. [x] resolves magento/magento2#35758: Fixed double URL Rewrite when category have 301 redirect

### CODE REVIEW

**Comment by hryvinskyi** [comment]
https://github.com/magento run all tests

**Comment by hryvinskyi** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
create new issue

**Comment by engcom-Charlie** [comment]
@magento create issue

**Comment by engcom-Dash** [comment]
Hi @hryvinskyi ,

Kindly Add the Preconditions,environment,Steps to reproduce and Actual as well as Expected result.

Thanks!!!

**Comment by engcom-Delta** [comment]
Hi @hryvinskyi ,
Its related issue # https://github.com/magento/magento2/issues/35758 has been closed due to no response from reporter for more than 14 days. Hence closed.

**Comment by engcom-Delta** [comment]
Hi @hryvinskyi ,
We are closing the PR since its issue already closed, Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Pull request closed without merging**
