### PR TITLE
resolve notification shows that there is not enough quantity for that item

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

magento/magento2#21564: Resolve notification shows that there is not enough quantity for that item

Reason: the logic 

 ` public function validate(Observer $observer)`

in Magento\CatalogInventory\Model\Quote\Item\QuantityValidator should be validated when the quoteItemId is not "Null"

Solution: Don't run the logic if the quoteItemId = null. It should be the Int. Check "If"

### Fixed Issues (if relevant)

1. magento/magento2#21564: notification shows that there is not enough quantity for that item
### Manual testing scenarios (*)

In Catalog-->Inventory Settings, Set item threshold to "0", and notify when item reaches to "0" (So that it does not notify if quantity is 1)

1. Login To magento backend
2. Go to Sales
3. Create new order
4. Select any customer.
5. select a product which have only one item remaining in stock (ex T-shirt)
6. The product is added successfully without the error notification

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-23686.instances.magento-community.engineering).
Admin access: [https://pr-23686.instances.magento-community.engineering/admin](https://pr-23686.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5449](https://jira.corp.magento.com/browse/ENGCOM-5449) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@edenduong thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
Hi @edenduong !

During testing we faced an issue. 

**Problem:**  The product is added without the error notification when product quantity is more then "Out-of-Stock Threshold"

**Steps to reproduce:**

1. Go to Admin->Stores->Configuration->Catalog->Inventory;
2. In "Product Stock Options" tab set "Out-of-Stock Threshold" to "3" for example;
3. Create simple product with quantity "4" for example;
4. Go to Sales->Orders->Create New Order;
5. Select any customer;
6. Add created before product to quote with quantity "2";

**Expected Result:**

We should get the error message "The requested qty is not available"

**Actual result:**

The product is added without the error notification
after

@edenduong  Could you take a look?

Thanks!

**Comment by edenduong** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [Magento instance](https://i-23686-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23686-2-3-develop.instances.magento-community.engineering/admin](https://i-23686-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by edenduong** [comment]
@engcom-Alfa: It also happens on 2.3-develop. I think it may be another issue. I will check it again.

**Comment by edenduong** [comment]
@engcom-Alfa : I think it is another issue.

image

Now it will check only for the Threshold 0. 
The problem happens on the 2.3-develop

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @edenduong thanks for the pull request! What is the case when `$quoteItemId` is `null`? I think it's better to address the root cause and ensure the `getQty` method is called only when `$quoteItemId` is defined

**Comment by edenduong** [comment]
Hi @sivaschenko, Thank you for your feedback. I have just updated the source code. Should check the quoteItem->getId() in Magento\CatalogInventory\Model\Quote\Item\QuantityValidator

**Comment by edenduong** [comment]
Hi @sivaschenko, thank you for your feedback. I will try to debug it again.

**Comment by sivaschenko** [comment]
Looks like this is a duplicate to https://github.com/magento/magento2/pull/22849 fixing https://github.com/magento/magento2/issues/18812

@edenduong and @shikhamis11 can you please collaborate on a single solution to deliver a single pull request and close another.

**Comment by edenduong** [comment]
Hello @shikhamis11,
I will close this pull request. You can continue to work. 
Thanks.

**Comment by edenduong** [comment]
I will try to inspect it again so I will reopen.

**Comment by edenduong** [comment]
I will close this Pull request because seems someone has the solution to fix it. Thanks!

**Comment by prog7707** [comment]
where is the solution for this issue

**Comment by prog7707** [comment]
> 
> 
> I will close this Pull request because seems someone has the solution to fix it. Thanks!

Where is the solution for this issue

**Pull request closed without merging**
