### PR TITLE
fixed js translation

### PR DESCRIPTION
**Pull request by torhoehn**
"Not yet calculated" for the tax in the summary section in the checkout was not being translated.

### Description (*)

Now the correct function call for js translations is made.

### Fixed Issues (if relevant)

1. magento/magento2#18939: "Not yet calculated" for the tax in the summary section in the checkout is not translatable

### Manual testing scenarios (*)

1. Setup a two-store site where the default store uses "en_Us" as the language and the second store uses "es_ES" (Spanish ).
2. Add Spanish translation for the text: "Not yet calculated" through the design section. i.e, in the file: `app/design/frontend/<Package>/<theme>/i18n/es_ES.csv`.
   
        "Not yet calculated","Aún no calculado"
2. Now on the frontend, switch to Spanish store. Then add a product to the cart and go for checkout.
3. In the payment step, under the summary section, you will see "Not yet calculated" is not translated for the **Tax** eventhough the same text corresponding to **Shipping** is translated.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rajeev-k-tomy** [comment]
@torhoehn This pull request does not seem good. There are mainly two points I need to emphasize here.

1. You added an unwanted `jquery` dependency on the component.
2. The dependency `mage/translate` should come just after the `ko` dependency, which is what the practice we can see in other checkout core UiComponents.

It would be great if you correct it and then do a pull request.

**Comment by torhoehn** [comment]
@progammer-rkt  Thanks for your feedback, but:
1. I did not add jquery
2. I think there is no guideline for sort order of parameters

So for now I'll just wait until a maintainer reviews this PR.

**Review by Karlasa — APPROVED** [review]

**Comment by rajeev-k-tomy** [comment]
@Karlasa What about the unnecessary `jquery` dependency present. I think we should remove it.

@torhoehn You are right that there is no guideline for this. But sometimes (most of the time) we should refer the practices ("non-writtern practices") that the core code follows. It is just a suggestion from my side.

Whilst as I mentioned. jQuery dependency has to be removed as it is not required in this component.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3340](https://jira.corp.magento.com/browse/ENGCOM-3340) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.

**Pull request merged**
