### PR TITLE
Convert MageBraintree to use the serializer rather than Zend_Json

### PR DESCRIPTION
**Pull request by dmanners**
As Zend1 is end of life usage of Zend_Json should be converted to the internal serializer in Magento2

### CODE REVIEW

**Review by ishakhsuvarov — CHANGES_REQUESTED** [review]
Currently we can not accept majority of the changes which modify the constructor signature.
This requirement is introduced to maintain maximum compatibility with already existing extensions and customizations, potentially relying on the class via extending.

**Comment by ishakhsuvarov** [comment]
@dmanners Currently we can not accept majority of the changes which modify the constructor signature.
This requirement is introduced to maintain maximum compatibility with already existing extensions and customizations, potentially relying on the class via extending.

To add a new parameter to the constructor you may introduce it as optional, for example:
```php
public function __construct(
    \Magento\Framework\Serialize\SerializerInterface $serializer = null
) {
    $this->serializer = $serialize ?: \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\Serialize\SerializerInterface::class);
}
```

**Comment by dmanners** [comment]
Thanks for the feedback @ishakhsuvarov I guess that covers all the other zend_json PRs I have put in over the last few days.

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by ishakhsuvarov** [comment]
@dmanners Thank you for the update. We are going to proceed with processing now.

**Comment by okorshenko** [comment]
@dmanners Thank you for your contribution to Magento 2 project! Your pull request has been successfully merged! For some reason, we have different your commit hashes that's why this PR is not closed. But your changes already on develop branch. Thank you

**Comment by dmanners** [comment]
@okorshenko thanks. It is probably cause I like to keep my branches up to date and regularly rebase them. You may have merged an older version or something. No issue there as there where no new commits added after the rebase.

**Pull request closed without merging**
