### PR TITLE
Sorting galery media by position

### LINKED ISSUE #26709: Product video doesn't play when it is not placed first in the sort order.
### Preconditions (*)

- Magento Version : [2.2.9](https://github.com/magento/magento2/releases/tag/2.2.9)

 - PHP 7.1.32 
 - MySQL  Ver 14.14 Distrib 5.7.28, for Linux (x86_64) using  EditLine wrapper

- Sample data is used.
 

### Steps to reproduce 

1. Edit the simple product of a configurable product and add a product video. ( In our case, we have used Chaz Kangeroo Hoodie as Configurable Product and Chaz Kangeroo Hoodie-XS-Black as its simple product )
2. The video used is [https://www.youtube.com/watch?v=L4XjEuCPOJY](https://www.youtube.com/watch?v=L4XjEuCPOJY).
3. Now, sort the video in media gallery to make it seen anywhere but not the first position.
4. Save the product.
5. View the configurable product in storefront product details page.
6. Click on the color swatch to view the simple product media gallery.
7. Click the video thumbnail and play the video.

Imgur
Imgur

### Expected result 

1. The video should play when clicked on the thumbnail.

### Actual result

1.  Only the thumbnail image of the youtube video is visible.
2. The video is not played if the video is not in the first position according to the sort order in admin panel.
Imgur

Imgur

Imgur

Imgur

### Addition Information 
https://github.com/magento/magento2/issues/26709#issuecomment-602561906

I could easily reproduce the issue on the latest 2.4-develop
youtube_video_26709

### PR DESCRIPTION
**Pull request by LucasCalazans**
### Description
The gallery of configurable products is not showing the video correctly when the video position in the admin is changed.

### Fixed Issues
1. Fixes magento/magento2#26709: Product video doesn't play when it is not placed first in the sort order.

### Manual testing scenarios
1. Create a configurable product with images in the parent product
2. Add images and a video in the gallery of a child product
3. Go to storefront, select the options of the child that has a video
4. Click on the thumb of the video
5. The video should appear in the gallery with a play button

https://www.loom.com/share/29ef24c26ea04a3d8cd2e03465f071e2

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by LucasCalazans** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @LucasCalazans. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @LucasCalazans, here is your [new Magento instance](https://pr-27593.instances.magento-community.engineering).
Admin access: [https://pr-27593.instances.magento-community.engineering/admin_9f69](https://pr-27593.instances.magento-community.engineering/admin_9f69)
Login: `e7bd5e44` Password: `65d2e183d06a`
Instance will be terminated in up to 3 hours.

**Comment by LucasCalazans** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @LucasCalazans. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @LucasCalazans, here is your [Magento instance](https://i-27593-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27593-2-4-develop.instances.magento-community.engineering/admin_4a29](https://i-27593-2-4-develop.instances.magento-community.engineering/admin_4a29)
Login: `4660f735` Password: `de1157b0f96f`
Instance will be terminated in up to 3 hours.

**Review by sidolov — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Edit the simple product of a configurable product and add a product video;
2. Save product;
3. Now, sort the video in the media gallery to make it seen anywhere but not the first position;
4. Save the product again;
5. View the configurable product in the storefront product details page.
6. Click on the color swatch to view the simple product media gallery.
7. Click the video thumbnail and play the video.

**Before:**
:heavy_multiplication_x: Only the thumbnail image of the youtube video is visible.
:heavy_multiplication_x: The video is not played if the video is not in the first position according to the sort order in admin panel.



**After:**
:heavy_check_mark: The video plays when you click on the thumbnail.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Need approval. Fixed type matching.

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @LucasCalazans .

Could you resolve merge conflicts?
Thanks!

**Comment by ishakhsuvarov** [comment]
Hi @LucasCalazans 

I am closing this PR for now as it seems like it has become stale and still needs work.

Please feel free to reopen if you wish to continue.

Thanks!

**Pull request closed without merging**
