### PR TITLE
Add a ModuleManagerInterface for determining if a module is enabled

### PR DESCRIPTION
**Pull request by navarr**
This is a useful addition for feature detection and enablement for third party modules (such as "activate this functionality if such and such GiftCard extension exists"

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by orlangur** [comment]
```
public function isEnabled($moduleName)
    {
        return $this->moduleList->has($moduleName);
    }
```

This is the only method of mentioned class. What is the purpose of proposed interface?

**Comment by navarr** [comment]
Purpose is to add an easy ability to determine if a module is enabled to the API.  Currently neither the ModuleManager nor the ModuleListInterface are @api annotated

@orlangur

**Comment by orlangur** [comment]
Interface is only useful when implementation may be potentially switched. Why not mark class method with `@api` instead?

**Comment by navarr** [comment]
I can do that.  I defaulted to an interface b/c I figured it'd be what'd be desired - after all, just b/c I can't think of an alternative implementation doesn't mean one can't exist!

Should I PR the addition on the model itself?  Doing so would add a couple non-api deprecated methods to the API though

**Comment by orlangur** [comment]
I was thinking about marking only one method as `@api`.

Let me check in Slack whether there was some reasoning behind not marking this class as `@api` and whether we should mark class or method.

**Comment by orlangur** [comment]
Raised a question in Slack

> Is there any reason of not marking https://github.com/magento/magento2/blob/2.2-develop/lib/internal/Magento/Framework/Module/Manager.php as `@api`?

**Comment by navarr** [comment]
@orlangur I'm guessing you never got any feedback in Slack?

**Comment by orlangur** [comment]
@navarr yeah, but now we have a better process.

**Comment by orlangur** [comment]
@antonkril @buskamuza please take a look on this interface suggestion. Of course it should be done against `2.3-develop` but first it would be nice to understand whether such feature detection is an acceptable approach.

**Comment by antonkril** [comment]
Explicit `isModuleEnabled` checks are usually a sign of bad modularity.

But yes, such interface with @api annotation makes sense.

**Review by antonkril — APPROVED** [review]
Makes sense

**Comment by navarr** [comment]
I'm closing this PR to make a new one against 2.3

**Pull request closed without merging**
