### PR TITLE
[Port PR #12807 2.2 => 2.3] Reorder adding of page layout handles

### PR DESCRIPTION
**Pull request by aschrammel**
Add type-dependent layout handles before more specific ID/SKU layout
handles.

When updating a product page layout for a specific ID with `catalog_product_view_id_<product_ID>.xml` some changes may be overwritten by a less specific `catalog_product_view_type_<product_type>.xml`.

### Description
Change the order of loading the layout handles in `\Magento\Catalog\Helper\Product\View` and `\Magento\Review\Controller\Product\ListAction` to add the type specific layout handles BEFORE more specific ID/SKU specific layout handles.

In `\Magento\Catalog\Controller\Category\View` the updates are already loaded in the above suggested order.
### Fixed Issues (if relevant)
--

### Manual testing scenarios

1. Create a configurable product
2. Create a layout override for this product on by ID base (`catalog_product_view_id_<product_ID>.xml`)
3. In this layout update try to overwrite the `product.info.options.configurable` block with a custom template in referenced block `product.info.options.wrapper`
4. Before applying the PR the custom template is not taken into account, afterwards it is taken into account

### Example override
```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="product.info.options.wrapper">
            <block class="Vendor\Module\Block\Product\View\Type\Configurable"
                name="product.info.options.configurable" as="options_configurable" before="-"
                template="Vendor_Module::product/view/type/options/configurable.phtml"/>
        </referenceBlock>
    </body>
</page>
```
### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=13064) <br/>All committers have signed the CLA.

**Comment by aschrammel** [comment]
@mzeis I don't know how relevant this repo is, but the patch is already applied here https://github.com/Coderimus/magento2/commit/3d78a8f407d692cad2ecbf170d8618cb82d574c4 for 2.3-develop

**Comment by magento-engcom-team** [comment]
@aschrammel thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by mzeis** [comment]
@aschrammel Your PR already has been forward-ported to 2.3 by the core team, so we don't need to merge this PR anymore: https://github.com/magento/magento2/commit/6e6c7d2987182cb48042db28f72a8c08de615d8d

Thanks again for your contribution!

**Pull request closed without merging**
