### PR TITLE
Corrects coding standard

### PR DESCRIPTION
**Pull request by brenofabio**
### Description (*)

Split database option array into multiple lines.

### Related Pull Requests

N/A

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable) N/A
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by brenofabio** [comment]
@magento run all tests

**Comment by brenofabio** [comment]
@magento run Functional Tests CE

**Review by ihor-sviziev — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8270](https://jira.corp.magento.com/browse/ENGCOM-8270) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@brenofabio thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by orlangur — CHANGES_REQUESTED** [review]
Hi @brenofabio! Where did you observe coding standard failure for this line?

**Comment by brenofabio** [comment]
> Hi @brenofabio! Where did you observe coding standard failure for this line?

Hi @orlangur!

PSR-2/PSR-12 (2.3 Lines)

"Lines SHOULD NOT be longer than 80 characters; lines longer than that SHOULD be split into multiple subsequent lines of no more than 80 characters each."

It's not a hard limit, just a recommendation to enhance the readability of the code.

**Comment by sidolov** [comment]
Hi @brenofabio , according to the coding standards used by the Magento team the line must be no longer than 120 characters, so, the current file does not violate them. I'm closing the PR since it's not relevant. Thank you for your contribution!

**Pull request closed without merging**
