### PR TITLE
Changes-Hamburger-Icon-was-available-on-a-page

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Pull request to 2.2-develop
https://github.com/magento/magento2/pull/20214

### Fixed Issues (if relevant)

1. magento/magento2#20210: Hamburger Icon was available on a page where menu was not present. Issue in responsive view
2. Magento version 2.2

### Manual testing scenarios (*)

1) Login to Customer Panel
2) Place Order for any product
3) Create invoice and shipment for this order from the backend
4) Repeat step 1
5) Open the browser in mobile responsive
6) Go to my account->my order->view the same order or any other order with the status "complete"
7) Click on Order Shipment subtab
8) Click on Print All Shipments
9) Cancel the option to print the Shipment form
10) Check the page

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-3853](https://jira.corp.magento.com/browse/ENGCOM-3853) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.

**Comment by amol2jcommerce** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by amol2jcommerce** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Pull request merged**
