### PR TITLE
Fixed error while adding new review from admin panel

### PR DESCRIPTION
**Pull request by suneet64**
Fixed error while adding new review from admin panel

### Description (*)

An error after selecting the product while adding review from Magento admin. 

### Fixed Issues (if relevant)

1. magento/magento2#20122: Getting error on adding new review from admin panel

### Manual testing scenarios (*)

1. Have a Magento v2.3 clean installation.
2. Login to admin panel and navigate to Marketing > User Content > Reviews.
3. Click on New Review button and select any product for adding review.
4. **Before:** An error being displayed which states that `A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.`
**After:** The error disappear in this fix.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @suneet64. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by milindsingh** [comment]
@suneet64 why did you removed the interface?
I think the issue is the interface type

**Comment by suneet64** [comment]
@milindsingh yes, you are right! There should be HttpPostActionInterface and I have added that.

**Comment by sivaschenko** [comment]
Hi @suneet64 , thanks for the contribution! Considering that controller does not change the application state and is used simply to retrieve data - the `HttpGetActionInterface` is correct. That's the client code that should be fixed to retrieve data using `GET` method instead of `POST`.

**Comment by suneet64** [comment]
Hi @sivaschenko , thanks for the review! I just changed the interface to `HttpGetActionInterface` and fixed the client code from `POST` to `GET`.

**Comment by suneet64** [comment]
Hi @sivaschenko , after changing the client code from `POST` to `GET`, the Travis CI build failed. Can you please suggest why it failed? Thanks!

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @suneet64. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
