### PR TITLE
Deprecated redundant class

### PR DESCRIPTION
**Pull request by drpayyne**
### Description

Deprecated redundant `\Magento\Sales\Model\Order\Email\Sender\ShipmentSender` with preference for `\Magento\Sales\Model\Order\Shipment\Sender\EmailSender` since it implements a data interface. Please refer https://github.com/magento/magento2/issues/14885#issuecomment-484214353

### Fixed Issues
1. magento/magento2#14885: Refactoring: Code duplication EmailSender / ShipmentSender and so on

### Manual testing scenarios
1. No testing as this PR only deprecates a class

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by swnsma** [comment]
Hi @drpayyne,
Thank you for your contribution!
Could you please check failed static test?

**Comment by drpayyne** [comment]
Hey @swnsma, thanks for reviewing. I've fixed the static test failures. Thanks!

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-6807](https://jira.corp.magento.com/browse/ENGCOM-6807) has been created to process this Pull Request
:eight_spoked_asterisk: @swnsma, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by swnsma** [comment]
Hi! Thank you, @drpayyne 
May I ask you also ask you to mark as 'deprecated' all tests which is related to this class?

**Comment by drpayyne** [comment]
Hi @swnsma, fixed that too. Thanks!

**Comment by engcom-Alfa** [comment]
@swnsma  Could you review the latest changes?
Thanks!

**Comment by swnsma** [comment]
Hi @drpayyne!
Thank you!
How about 
> \Magento\Sales\Model\Order\Email\Sender\ShipmentSenderTest
?

**Comment by drpayyne** [comment]
Hi @swnsma, sorry I don't understand your comment. I've deprecated the test class you've mentioned too. :thinking:

**Comment by swnsma** [comment]
Hi @drpayyne!

You have deprecated class:
> app/code/Magento/Sales/Test/Unit/Model/Order/Email/Sender/ShipmentSenderTest.php 

But you did not deprecate integration tests class:
>dev/tests/integration/testsuite/Magento/Sales/Model/Order/Email/Sender/ShipmentSenderTest.php

Or I miss something?

**Comment by drpayyne** [comment]
Hi @swnsma, I've deprecated that too now. Thank you.

**Comment by swnsma** [comment]
@drpayyne Thank you!

**Review by swnsma — APPROVED** [review]
@QA please make sure that tests works correctly with removed in this PR classes.

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-6807](https://jira.corp.magento.com/browse/ENGCOM-6807) has been created to process this Pull Request
:eight_spoked_asterisk: @swnsma, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Charlie** [comment]
Failed functional test not related to the changes in this PR test fails in 2.4-develop with MSI modules.
image

**Pull request merged**
