### PR TITLE
Fixed "additional_images" column validation

### PR DESCRIPTION
**Pull request by Yonn-Trimoreau**
When importing (for real), the character used to explode "additional_images" column is not the same as when validating.
Instead, the multiple value separator is used. So here is the fix for validator.

Here you can find the corresponding line for real import, where you can understand the paradox :
https://github.com/pepe1518/magento2/blob/2ee22c350530e97caf33a079bcad86cfe8b7da40/vendor/magento/module-catalog-import-export/Model/Import/Product.php#L1330

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=6774) <br/>All committers have signed the CLA.

**Comment by PieterCappelle** [comment]
+1 for this. @okorshenko could you please review this one and merge. More than 10 issues are reported for this one. Thanks in advance.

**Comment by vrann** [comment]
@PieterCappelle working on accepting this.
@Yonn-Trimoreau thank you for creating the PR.

**Comment by vrann** [comment]
@Yonn-Trimoreau trying to understand, how does removing of unused constant helps with the issue. If you can help with that will be great.

**Comment by Yonn-Trimoreau** [comment]
You're looking at the wrong commit, there are 2, the first which fixes the issue, and the second which is only a conflict resolution (don't know why I had to make it but GitHub asked..), here is the first commit : https://github.com/magento/magento2/pull/6774/commits/71ccc5632dc19f670bff8598f564eb650d553d8a

**Comment by Yonn-Trimoreau** [comment]
And removing the unused constant is just for clean code

**Comment by vrann** [comment]
I'm looking into "Files Changed (1)" section of the PR
screen shot 2017-03-21 at 9 25 48 am

Please make sure all the changes are reflected there. You can squash all your changes in one commit and force push the branch.

**Comment by vrann** [comment]
@Yonn-Trimoreau also, please do not remove the constant :) It is backward incompatible change.

**Comment by Yonn-Trimoreau** [comment]
I don't know how to do that. +, it seems already fixed on develop branch : https://github.com/magento/magento2/edit/develop/app/code/Magento/CatalogImportExport/Model/Import/Product/Validator/Media.php

**Comment by vrann** [comment]
@Yonn-Trimoreau you are right, it is fixed. Closing this PR, but thank you for participation regardless.

**Pull request closed without merging**
