### PR TITLE
Improve price index consistency and run time

### LINKED ISSUE #35719: [Issue] Improve price index consistency and run time
This issue is automatically created based on existing pull request: magento/magento2#35524: Improve price index consistency and run time

---------

### Description (*)
With a very large product set (~213k) on 1 of our sites, the price index (and through the use of MSI, the inventory index) takes a very long time to complete, with multiple hours spent executing deleteIndexData. It seems the primary cause of this slowdown is string to int conversions or vice versa in MySQL, and ensuring that all IDs are integers beforehand yields much more consistent and reasonable performance on these larger sets

### Manual testing scenarios (*)
1. Get a bunch of products
2. Use MSI
3. Have multiple stock sources (with a non default providing most of the stock)
4. Run an inventory index (the issue is most noticeable here due to InventoryCatalog's plugin "PriceIndexUpdatePlugin", and its call to reindexList with a very large number of IDs)

### Contribution checklist (*)
 - [✓] Pull request has a meaningful description of its purpose
 - [✓] All commits are accompanied by meaningful commit messages
 - [✓] All new or changed code is covered with unit/integration tests (if applicable)
 - [✓] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [✓] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by nicka101**
### Description (*)
With a very large product set (~213k) on 1 of our sites, the price index (and through the use of MSI, the inventory index) takes a very long time to complete, with multiple hours spent executing deleteIndexData. It seems the primary cause of this slowdown is string to int conversions or vice versa in MySQL, and ensuring that all IDs are integers beforehand yields much more consistent and reasonable performance on these larger sets

### Manual testing scenarios (*)
1. Get a bunch of products
2. Use MSI
3. Have multiple stock sources (with a non default providing most of the stock)
4. Run an inventory index (the issue is most noticeable here due to InventoryCatalog's plugin "PriceIndexUpdatePlugin", and its call to reindexList with a very large number of IDs)

### Contribution checklist (*)
 - [✓] Pull request has a meaningful description of its purpose
 - [✓] All commits are accompanied by meaningful commit messages
 - [✓] All new or changed code is covered with unit/integration tests (if applicable)
 - [✓] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [✓] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#35719: Improve price index consistency and run time

### CODE REVIEW

**Comment by nicka101** [comment]
@magento run all tests

**Comment by nicka101** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Comment by nicka101** [comment]
@magento run Functional Tests B2B

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run Static Tests

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
@magento run Static Tests

**Comment by engcom-Alfa** [comment]
@magento run Static Tests

**Comment by engcom-Alfa** [comment]
@magento run Static Tests

**Comment by engcom-Alfa** [comment]
@magento run Static Tests

**Comment by engcom-Alfa** [comment]
@magento run Static Tests

**Comment by nicka101** [comment]
The instance where I observed the speedup has 213,816 products, of which all of them are provided by a non-default stock, each in one or more of many stock sources (all attached to the non-default stock) based on the providing distributor.

It may also be relevant that the site has bundled products, as the MSI modules (specifically InventoryCatalog) contain a [plugin](https://github.com/magento/inventory/blob/develop/InventoryCatalog/Plugin/InventoryIndexer/Indexer/Stock/Strategy/Sync/PriceIndexUpdatePlugin.php) that triggers a partial price index after a non-default stock reindex (one that was specifically added to address an issue with bundle products and their pricing).

On the dataset in question, the list of IDs passed to the partial reindex consist of every single product in the store (213,816), however, 213,800 of the IDs are enclosed in quotes as strings, and only the last 16 are given as integers. This seems to confuse MySQL, which would then subsequently spent HOURS executing just the delete in deleteIndexData. My testing showed that simply ensuring that the IDs are all integers reduced the execution time from multiple hours to less than 10 minutes, while adding no/negligible cost to sites where the price indexer is working as expected

**Comment by nicka101** [comment]
The instance where I observed the speedup has 213,816 products, of which all of them are provided by a non-default stock, each in one or more of many stock sources (all attached to the non-default stock) based on the providing distributor.

It may also be relevant that the site has bundled products, as the MSI modules (specifically InventoryCatalog) contain a [plugin](https://github.com/magento/inventory/blob/develop/InventoryCatalog/Plugin/InventoryIndexer/Indexer/Stock/Strategy/Sync/PriceIndexUpdatePlugin.php) that triggers a partial price index after a non-default stock reindex (one that was specifically added to address an issue with bundle products and their pricing).

On the dataset in question, the list of IDs passed to the partial reindex consist of every single product in the store (213,816), however, 213,800 of the IDs are enclosed in quotes as strings, and only the last 16 are given as integers. This seems to confuse MySQL, which would then subsequently spent HOURS executing just the delete in deleteIndexData. My testing showed that simply ensuring that the IDs are all integers reduced the execution time from multiple hours to less than 10 minutes, while adding no/negligible cost to sites where the price indexer is working as expected

**Comment by engcom-Alfa** [comment]
@magento run Static Tests

**Comment by engcom-Alfa** [comment]
@magento run Static Tests

**Comment by engcom-Alfa** [comment]
@magento run Static Tests

**Comment by engcom-Alfa** [comment]
@magento run Static Tests

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

There are steps give in [above-comment](https://github.com/magento/magento2/pull/35524#issuecomment-1164609593) to cross check the performance improvements.
But, we also have to have most of the bundle products set to non-default sources to identify the performance improvements and it is challenging to replicate in local Magento instances.
Hence regressed with the functional scenarios mentioned below before moving ahead.

1. Created bundle products with non-default sources/stocks. Places an order and shipped.
2. Created simple/config products with non-default sources/stocks. Places an order and shipped.
3. Validated if source2 products are invisible in source1's website as such
4. Cross checked with out of stock products of non-default sources are not available in the frontend to place an order.

There is no additional regression test cases required as part of regression testing since it is a performance improvement.

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Charlie** [comment]
Hi @nicka101,

Thank you for your contribution!

I have fixed static test failures. 

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Gone through the build failure. There are some Functional CE, EE, B2B test failures. Below are few test failures. 

- AdminCheckingDateAfterChangeFrenchCanadaInterfaceLocaleTest.xml
- AdminSavesTheImagePreviewWithNewNameTest.xml 
- AdminAdobeStockStandaloneMediaGallerySavePreviewTest.xml 
- AdminStandaloneMediaGallerySearchByKeywordTest.xml

After analysis found that the tests which are failing now are not part of this PR changes or not failing because of any PR change. There are some flecky tests too. 

Hence moving the PR for Merging.

Thank you!

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Pull request merged**
