### PR TITLE
[MFTF] ZeroSubtotalOrdersWithProcessingStatusTest refactoring

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
The test is refactored according to the best practices

### Related Pull Requests
https://github.com/magento/magento2/pull/33727

Please, note: the test is dependent on #33727

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run all tests

**Comment by AnnaAPak** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Semantic Version Checker

**Review by sidolov — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests CE

**Comment by engcom-Alfa** [comment]
@magento run WebAPI Tests, Unit Tests, Static Tests, Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B, Magento Health Index, Integration Tests, Database Compare, Functional Tests CE

**Comment by engcom-Alfa** [comment]
The PR auto-tests are continuously failing in as per my prior executions.
Hence moving the ticket to _Extended Testing_.

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
Hi @AnnaAPak,

Thank you for your contribution!

The build is green now and the test cases from the PR are working fine on local environment too. Hence moving this PR to Merge in Progress.

Thank you.

**Pull request merged**
