### PR TITLE
Resolved undefined index issue for import adapter

### PR DESCRIPTION
**Pull request by jaimin-ktpl**
### Description (*)

Added a condition to check if 'sku' column exists in CSV file before setting its value.
### Fixed Issues (if relevant)

1. magento/magento2#19761: Custom import adapter data validation issue

### Manual testing scenarios (*)

1. Create a custom import adapter extending `Magento\ImportExport\Model\Import\Entity\AbstractEntity`
2. Add valid columns in `getValidColumnNames()` function.
    e.g. ['column1', 'column2', 'column3']
3. Create CSV file with columns stated above and add data.
4. Go to System > Import
5. Select your adapter from "Entity Type" dropdown
6. Select your CSV file in "Select File to Import" field.
7. Click on "Check Data" button
8. CSV file should get validated if column and data are available

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @jaimin-ktpl. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
Hi @jaimin-ktpl thanks for your contribution! As I can see the `$skuSet` variable is used to count number of processed entities. So in case, when there is no `sku`, this calculation will not work. Is there a way to replace the hardcoded `sku` field to a dynamic record identifier?

**Comment by jaimin-ktpl** [comment]
Hello @sivaschenko , Thank you for your inputs on it. Can we set an incremental variable for each valid row? Something like, `$entitySet` instead of `$skuSet`.
Or we can directly increase value of `$_processedEntitiesCount` for each valid rows?

**Comment by sivaschenko** [comment]
Hi @jaimin-ktpl , I think there may be no need for a variable and we may directly increment the `$_processedEntitiesCount` for each valid row.

I.e. that's exactly how `_processedEntitiesCount` handled in https://github.com/magento/magento2/blob/ddebed6b9abac9f3659fec4cc5c4c2c04dd86c05/app/code/Magento/CatalogImportExport/Model/Import/Product.php#L2483 and https://github.com/magento/magento2/blob/ddebed6b9abac9f3659fec4cc5c4c2c04dd86c05/app/code/Magento/CustomerImportExport/Model/Import/AbstractCustomer.php#L193

However, there is a concern about the reason the code was using the `sku` key at the first place. I think that's used to handle a case when import contains multiple rows for a single enitity. To count entities instead of just rows.

**Comment by jaimin-ktpl** [comment]
Hello @sivaschenko , I have updated the code to check for entity count.

**Review by sivaschenko — APPROVED** [review]

**Comment by jaimin-ktpl** [comment]
@VladimirZaets , waiting for your review on this PR. Please review it when you have time.. Thanks.

**Comment by VladimirZaets** [comment]
Hi, @jaimin-ktpl. The ticked already reviewed and currently in processing status. Thanks

**Comment by p-bystritsky** [comment]
QA passed.

**Pull request merged**
