### PR TITLE
#13904 [Back port for 2.1] Add To Cart success message link

### PR DESCRIPTION
**Pull request by mrkhoa99**
Original PR:
https://github.com/magento/magento2/commit/073de209076d60ef12482551479b5f1f770f00d5

### Description

If I add a product to the shopping cart, I want to go to the cart directly after that in many cases without having to search for a link.

### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/pull/13904

### Manual testing scenarios

1. Go to a product view page
2. Click "Add to Cart"
3. Check if the success message contains the checkout cart link.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@mrkhoa99 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by mrkhoa99** [comment]
@VladimirZaets Do you have any idea about the Travis build failed? 
https://travis-ci.org/magento/magento2/jobs/378345711
Seems that do we need to change the URL with slash?

**Comment by VladimirZaets** [comment]
Hi @mrkhoa99, I will look tests, currently, I see that getCartUrl() method returns the string with transformed special symbols, like `<` as the example. I will investigate is it ok or not and will provide more information.

**Comment by VladimirZaets** [comment]
Hi @mrkhoa99, do you try to investigate the integration tests failing?

**Comment by VladimirZaets** [comment]
@mrkhoa99, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration.

**Pull request closed without merging**
