### PR TITLE
Fixed coding standard violations in the Framework\Validator namespace

### PR DESCRIPTION
**Pull request by dverkade**
Fixed coding standard violations in the Framework\Validator namespace, so that it will be checked bij PHP CS and no longer be ignored while doing CI checks. Made the following changes:
- Removed @codingStandardsIgnoreFile
- Fixed indentation
- Fixed number of chars per line
- Accidentally removed new lines from the end of the file in first commit. Fixed this in the second commit.

### CODE REVIEW

**Comment by dverkade** [comment]
I will look into this why the test fails, fix it and make a commit again.

**Comment by orlangur** [comment]
Such kind of manual changes is a waste of time for both developer and PR reviewers. With ~700 files with violations and 2-4 files fixed per PR you'll need few hundreds of PRs created.

Please get familiar with approach I described in https://github.com/magento/magento2/pull/7166#issuecomment-287712529 and already successfully used and fix coding standard violations in similar manner.

**Comment by vrann** [comment]
@orlangur I don't think that everything should be fixed in one pull request, more granular fixes will allow delivering changes often. However, if you'd like to work on the automated tool, please feel free to do so.

@dverkade can you please fix the issue with the static test:
```
FILE: ...1694-SLE1/magento2/lib/internal/Magento/Framework/Validator/Factory.php
--------------------------------------------------------------------------------
FOUND 2 ERROR(S) AFFECTING 2 LINE(S)
--------------------------------------------------------------------------------
 81 | ERROR | Opening parenthesis of a multi-line function call must be the
    |       | last content on the line
 82 | ERROR | Closing parenthesis of a multi-line function call must be on a
    |       | line by itself
--------------------------------------------------------------------------------
```

**Comment by vrann** [comment]
@dverkade can you please fix unit tests":

```
	Failed	Magento\Framework\Validator\Test\Unit\BuilderTest::testCreateValidator testCreateValidator with data set #0 History
< 1 sec
Magento\Framework\Validator\Test\Unit\BuilderTest::testCreateValidator with data set #0 (array(array('name_alias', 'Magento\\Framework\\Validator\\Test\\Unit\\Test\\StringLength', array(array(array(1, Magento\Framework\Validator\Constraint\Option))), 'name', 'property')), Magento\Framework\Validator)
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
                 '_wrappedValidator' => Magento\Framework\Validator\Test\Unit\Test\StringLength Object (...)
-                '_alias' => 'name_alias'
+                '_alias' => Array (...)
(11 more lines...)
Failed	Magento\Framework\Validator\Test\Unit\BuilderTest::testCreateValidator testCreateValidator with data set #1 History
< 1 sec
Magento\Framework\Validator\Test\Unit\BuilderTest::testCreateValidator with data set #1 (array(array('description_alias', 'Magento\\Framework\\Validator\\Test\\Unit\\Test\\StringLength', array(array(array('setMin', array(10)), array('setMax', array(1000)))), 'description', 'property')), Magento\Framework\Validator)
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
                 '_wrappedValidator' => Magento\Framework\Validator\Test\Unit\Test\StringLength Object (...)
-                '_alias' => 'description_alias'
+                '_alias' => Array (...)
(11 more lines...)
Failed	Magento\Framework\Validator\Test\Unit\BuilderTest::testCreateValidator testCreateValidator with data set #2 History
< 1 sec
Magento\Framework\Validator\Test\Unit\BuilderTest::testCreateValidator with data set #2 (array(array('sku_alias', 'Magento\\Framework\\Validator\\Test\\Unit\\Test\\StringLength', array(array(Magento\Framework\Validator\Constraint\Option\Callback)), 'sku', 'property')), Magento\Framework\Validator)
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ @@
                 '_wrappedValidator' => Magento\Framework\Validator\Test\Unit\Test\StringLength Object (...)
-                '_alias' => 'sku_alias'
+                '_alias' => Array (...)
(11 more lines...)
```

**Comment by dverkade** [comment]
@orlangur Thank you for your suggestion. Since you have a clear idea on how to fix this you can do it on all the modules in the /app/code folder. I'm focusing on the Framework. The first time it was all in one PR which became impossible to proces, so I opted for this approach where I'll fix a couple of files and do a PR per namespace. This way the PR's can be processed faster and developers can benefit from these changes immedialely while not every file is yet coding standard compliant. 

@vrann I fixed the coding violations which where still in there and I fixed the failing unit tests. So this PR is now complete from my side.

**Comment by orlangur** [comment]
@vrann @dverkade the problem is not with granularity, changes can be partial with automated approach as well, the problem is with time spent on manual changes and then rigorous review of such changes.

Ok, I'll do my best to show my approach in action asap, fixing all the codebase (modules, framework, whatever else...).

**Pull request merged**
