### PR TITLE
magento/magento2#15775: Incorrect return type getList() in CustomerRepository 

### PR DESCRIPTION
**Pull request by p-bystritsky**
### Fixed Issues (if relevant)

1. magento/magento2#15775: Incorrect return type getList() in CustomerRepository

### Manual testing scenarios

1. Install attached module.
[test-module.zip](https://github.com/magento/magento2/files/2745871/test-module.zip)
2. Execute command `bin/magento foo:bar:test`
3. Command output should be `Passed`

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @p-bystritsky. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by orlangur** [comment]
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

**Comment by davidverholen** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
@p-bystritsky please fix all failed tests

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Please fix all failed tests

**Comment by orlangur** [comment]
Closing as 2.3 PR is still not merged.

**Pull request closed without merging**
