### PR TITLE
Language cleanup on mass actions from the Customers grid

### PR DESCRIPTION
**Pull request by p-maguire**
### Description (*)
This pull request corrects a few grammar issues on the "Delete" and "Customer Unsubscribe from Newsletter" mass actions on the Customers grid.

### Fixed Issues (if relevant)

1. None

### Manual testing scenarios (*)

1. Login to admin and go to Customers-->All Customers
2. Select one or more customers
3. Select the "Delete" or "Unsubscribe from Newsletter" options.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18751) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @p-maguire. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3249](https://jira.corp.magento.com/browse/ENGCOM-3249) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@p-maguire thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @p-maguire. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
