### PR TITLE
Implemented Option Type validation in validationItemTypes

### LINKED ISSUE #26110: Bundle product with option type radio and dropdown can be added to the cart with multiple choices
### Preconditions (*)

1. Sample Data

### Steps to reproduce (*)

1. Add product to the cart
```graphql
mutation addBundle(
  $cart_id: String!
) {
  addBundleProductsToCart(
    input: {
      cart_id: $cart_id
      cart_items: {
        data: {
          quantity: 1
          sku: "24-WG080"
        }
        bundle_options: [
          {
            id: 1
            quantity: 1
            value: [
              "1"
              "2"
              "3"
            ]
          }
          {
            id: 2
            quantity: 1
            value: [
              "4"
            ]
          }
                    {
            id: 3
            quantity: 1
            value: [
              "5"
            ]
          }
                    {
            id: 4
            quantity: 1
            value: [
              "8"
            ]
          }
        ]
      }
    }
  ) {
    cart {
      items {
        id
        quantity
        product {
          sku
        }
        ... on BundleCartItem {
          bundle_options {
            id
            label
            type
            values {
              id
              label
              quantity
              __typename
            }
          }
        }
      }
    }
  }
}
```

### Expected result (*)

1. Some message that complains about invalid input for BundleItem.type: radio/dropdown

### Actual result (*)

1. Successfully added to cart

### Additional information 
The issue was confirmed again on the lates `2.4-develop` code. May 28, 2020
In general it is possible to add to Shopping Cart and place order with option type radio and dropdown with multiple choices. This flow is not possible using UI on Storefront.
More details: https://github.com/magento/magento2/issues/26110#issuecomment-635308289

### PR DESCRIPTION
**Pull request by sedonik**
### Description 

This PR is adding the ability to validate Bundle product with option type radio and dropdown can be added to the cart with multiple choices 

### Fixed Issues

1. Fixes magento/magento2#26110: Bundle product with option type radio and dropdown can be added to the cart with multiple choices

### Steps to reproduce

1. Add product to the cart
```graphql
mutation addBundle(
  $cart_id: String!
) {
  addBundleProductsToCart(
    input: {
      cart_id: $cart_id
      cart_items: {
        data: {
          quantity: 1
          sku: "24-WG080"
        }
        bundle_options: [
          {
            id: 1
            quantity: 1
            value: [
              "1"
              "2"
              "3"
            ]
          }
          {
            id: 2
            quantity: 1
            value: [
              "4"
            ]
          }
                    {
            id: 3
            quantity: 1
            value: [
              "5"
            ]
          }
                    {
            id: 4
            quantity: 1
            value: [
              "8"
            ]
          }
        ]
      }
    }
  ) {
    cart {
      items {
        id
        quantity
        product {
          sku
        }
        ... on BundleCartItem {
          bundle_options {
            id
            label
            type
            values {
              id
              label
              quantity
              __typename
            }
          }
        }
      }
    }
  }
}
```

### Expected result

1. Some message that complains about invalid input for BundleItem.type: radio/dropdown

### Actual result

1. Successfully added to cart

### CODE REVIEW

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Hi @sedonik I've checked the default Luma theme and I was able to reproduce the same bug:

- I've created bundle product with radiobutton options.
- Changed product HTML template using inspector to checkboxes and selected all of them.
- Product was added to cart with multiple options.

i.e. this bug should not be fixed in GraphQL layer, but in lower layer, where buy request is prepared for bundle product before adding to cart.

**Comment by sedonik** [comment]
Thank you @lenaorobei I've reproduced with default Luma theme. 
I agree that such a case could be validated as well.
I will think where better to move validation.

**Comment by sedonik** [comment]
Hi @lenaorobei,

I've moved validation to the \Magento\Bundle\Model\Product\Type class.
It should be Error when adding a bundled product with changed radio to checkboxes and selected more than one option.
Could you check this solution?

Thanks.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @sedonik,
I see that issue https://github.com/magento/magento2/issues/26110 was already fixed in https://github.com/magento/magento2/pull/29256.
Could you confirm that?

**Comment by ihor-sviziev** [comment]
Hi @sedonik,
I'm closing this PR as issue was already fixed in https://github.com/magento/magento2/pull/29256.
Feel free to put your comments here if it's still there.

**Pull request closed without merging**
