### PR TITLE
magento/magento2#37953: Attribute getStoreLabel wrong behavior

### LINKED ISSUE #37953: Attribute getStoreLabel wrong behavior
### Preconditions and environment

- Magento version 2.4.6-p2

### Steps to reproduce

1. Create any attribute, with a default label
2. Set a different label for store id = X
3. load attribute on admin area, and dump `$attribute->getStoreLabel(X)`

### Expected result

Store label is dumped

### Actual result

Default label is dumped

### Additional information

The problem is quite obvious when watching the first method lines : 

https://github.com/magento/magento2/blob/3cc15fbed80c1f75c77c7cfeeaaba3ca25fe81b8/app/code/Magento/Eav/Model/Entity/Attribute.php#L490-L495

A fix could be : 

`if (null === $storeId && $this->hasData('store_label')) {` instead of `if ($this->hasData('store_label')) {`

But it's probably a bit more complicated than that, we probably want to use default value if store label is empty or not set

Workaround : `$attribute->unsetData('store_label')->getStoreLabel($storeId);`

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Kiraberos**
- fixed issue with wrong behavior of the store labels

### Description (*)
In accordance with #37953, an additional check for a null store ID has been added

### Related Pull Requests
No

### Fixed Issues (if relevant)

1. Fixes magento/magento2#37953

### Manual testing scenarios (*)
1. Reproduced the problem
image
2. Debugged the method \Magento\Eav\Model\Entity\Attribute::getStoreLabel
3. Made sure that the fix worked
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Kiraberos** [comment]
@magento run all tests

**Comment by Kiraberos** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by Kiraberos** [comment]
@magento run Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @Kiraberos,

Thanks for the contribution!

PR changes seem good to us, but please cover the changes with some automated tests in accordance with the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1).

Thanks

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Echo** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

1. We have follow steps from [comment](https://github.com/magento/magento2/issues/37953#issuecomment-1740501139)
Screenshot 2023-11-08 at 2 12 41 PM


**Before:** :heavy_multiplication_x: 
beforePR


**After:** :heavy_check_mark:  
AfterPR


Hence moving it to `Merge In Progress`

**Comment by engcom-Charlie** [comment]
This PR yet not merged in magento 2.4 develop yet because of the PAT failure hence moving it back to Extended Testing.

**Comment by engcom-Charlie** [comment]
Hi @Kiraberos,

This PR is causing PAT(Performance Acceptance failure)  as below.

It looks like there have a degradation in PR related to increased cache load and memory peak usage.  Can you please rework on this PR in order to get it further, till then we are moving this PR to On Hold. 

image


image

**Comment by engcom-Charlie** [comment]
As we are getting Performance Acceptance failure(PAT) as mentioned [here](https://github.com/magento/magento2/pull/38073#issuecomment-1869299673), closing this PR now.

@Kiraberos, feel free to reopen once you updated it to fix the PAT failure.

Thank you!

**Pull request merged**
