### PR TITLE
Currency not convert in new product widget without cache clean

### LINKED ISSUE #38321: Currency not convert in new product widget without cache clean
### Preconditions and environment

- Magento version: 2.4.6-p3

### Steps to reproduce

1) Allow All Currencies from **Stores > Configuration > GENERAL > Currency Setup > Currency Options > Allowed Currencies**
2) Add Catalog New Products List widget in home-page-block cms block
3) Go to frontend and switch currency

### Expected result

image
Currency should be converted to switched currency

### Actual result

image
Price currency displays the previous currency. Working fine after cache clean.

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rutvik-monpara**
### Description (*)
- Added currency code to CacheKeyInfo

### Fixed Issues (if relevant)
1. Fixes magento/magento2#38321

### Manual testing scenarios (*)
1. Allow All Currencies from Stores > Configuration > GENERAL > Currency Setup > Currency Options > Allowed Currencies
2. Add Catalog New Products List widget in home-page-block cms block
3. Go to frontend and switch currency no need to cache clean after switch currency

### CODE REVIEW

**Comment by rutvik-monpara** [comment]
@magento run all tests

**Comment by rutvik-monpara** [comment]
@magento run all tests

**Comment by rutvik-monpara** [comment]
@magento give me test instance

**Comment by rutvik-monpara** [comment]
@magento run Functional Tests B2B

**Comment by rutvik-monpara** [comment]
@magento run Functional Tests CE, Static Tests

**Comment by rutvik-monpara** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
Hello @rutvik-monpara
Thank you for your collaboration
Sorry, but this PR is duplicated with https://github.com/magento/magento2/pull/37899.
I think we need to close this PR to avoid confusion.

Also, this PR is not backward compatible and has not test coverage
I'll close this PR.

**Pull request closed without merging**
