### PR TITLE
Chore: Bundle - Replace Block Escaping with Escaper

### LINKED ISSUE #37101: [Issue] Chore: Bundle - Replace Block Escaping with Escaper
This issue is automatically created based on existing pull request: magento/magento2#37088: Chore: Bundle - Replace Block Escaping with Escaper

---------
### Description (*)
Refactors the `Magento_Bundle` module to replace `$block` escaping functions with `$escaper` escaping functions.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by pykettk**
### Description (*)
Refactors the `Magento_Bundle` module to replace `$block` escaping functions with `$escaper` escaping functions.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37101: Chore: Bundle - Replace Block Escaping with Escaper

### CODE REVIEW

**Comment by pykettk** [comment]
@magento create issue

**Review by leonhelmus — APPROVED** [review]
Looks good! Thanks for the PR!

**Comment by engcom-November** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
:heavy_check_mark: QA Passed 

**Preconditions:** - 
Install fresh Magento **2.4-develop** and **PHP 8.1** 
**Manual testing scenario:** 

**Before:** :heavy_multiplication_x:  
image

**After:** :heavy_check_mark: 
image

Additionally tested:
Verified Magento Bundle product functionality in the frontend.

No additional manual test case is required in regression cycle as this PR is related to the refactoring of the codes.
As builds are failed hence, moving this PR to Extended Testing

**Comment by pykettk** [comment]
Replaced by #37420

**Pull request closed without merging**
