### PR TITLE
Fix layout xml and page layout caching issue on redis cluster under high load

### PR DESCRIPTION
**Pull request by andrey-legayev**
### Description (*)
Bugs which were fixed:
 - $this->pageLayout was not checked after reading from cache, but was used as is
 - two cache items were used in once place instead of one (performance impact)

Changes:
 - replace 2 cache items by 1 - it should improve performance
 - add "_MERGED" to cache key suffix to have compatibility with old cache keys during deployment of new version

### Fixed Issues (if relevant)
1. #6942 Layout corruption (Title is wrong, but issue is real)

### Manual testing scenarios (*)
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22765) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=22765) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: andrey-legayev<br/>:x: magento-team<br/>:x: pdohogne-magento

**Comment by andrey-legayev** [comment]
I've created a branch from tag 2.3.1 (which is branch "2.2") and pointed pull request to 2.3-develop
I'm not sure why I see not only my commits... can anyone explain it?
Is it a regular practice to create branch from 2.3-develop?

**Comment by curto83** [comment]
I'm not sure how this works I need help

**Comment by andrey-legayev** [comment]
I've cherry-picked all my commits to be on top of 2.3-develop and created #22766

**Pull request closed without merging**
