### PR TITLE
graphQl-200: Product Compare

### LINKED ISSUE #28522: Catalog/Customer :: Product Compare List
As a Magento End Customer,
I want to add one or more products to my compare list
So that 
I can compare different attributes of the products to make an informed purchase decision. 

  

**Acceptance Criteria**

- Only logged in customers can add products to compare lists.
- A customer can only create one compare list. 
- The compare list must have all product attributes configured as comparable in Magento backend. 
- Customers can add/remove products to/from the compare list. 
- Customers can clear the compare list with a single action.

**Approved Schema**

- https://github.com/magento/architecture/blob/master/design-documents/graph-ql/coverage/catalog/compare-list.graphqls

### PR DESCRIPTION
**Pull request by kisroman**
https://github.com/magento/graphql-ce/pull/338

### CODE REVIEW

**Comment by josefbehr** [comment]
@magento run all tests

**Review by josefbehr — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @josefbehr, thank you for the review.
[ENGCOM-5820](https://jira.corp.magento.com/browse/ENGCOM-5820) has been created to process this Pull Request
:eight_spoked_asterisk: @josefbehr, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by ghost** [comment]
@TomashKhamlai unfortunately, only members of the maintainers team are allowed to assign developers to the pull request

**Comment by lenaorobei** [comment]
@kisroman thank you for all the efforts you put into these 2 PRs.

Please understand that introducing new interfaces and schema changes require transparent approval flow by architecture team and must be publicly highlighted.

Next steps that we are going to perform in order to process your PRs:
- prepare use cases for product compare functionality (in progress)
- prepare architecture schema proposal https://github.com/magento/architecture

Once proposed schema will cover all use cases, we will be able to move forward.
I will keep you updated about this.

Sorry for such delay and hope for your understanding.

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @kisroman , can you please add the description of changes introduced in the pull request and testing instructions. If approved it will also require the test coverage

**Comment by gabrieldagama** [comment]
Hi @kisroman, thanks for contributing. 
This feature has been introduced in 2.4-develop already. Here is the PR https://github.com/magento/magento2/pull/29047

Closing this one as the feature is already implemented.

Thanks for contributing!

**Pull request closed without merging**
