### PR TITLE
Fixed issue Magento Community Edition: Version 2.4.5 - Date Picker design getting disturb

### LINKED ISSUE #36499: Magento Community Edition: Version 2.4.5 - Date Picker design getting disturb
### Preconditions and environment

1. Magento Community Edition 2.4.5 without sample data is installed.
2. Login into admin > Marketing > Cart Price Rules
3. Click on date picker of start column in grid, Select the date from date picker, After selecting the date "Date selector" text visible instead of calendar icon.

### Steps to reproduce

1. Login into admin > Marketing > Cart Price Rules
2. Click on date picker of start column in grid, Select the date from date picker, After selecting the date "Date selector" text visible instead of calendar icon.

Before

After

### Expected result

After selecting date from the date picker, calendar icon should be visible over there.

### Actual result

After selecting date from the date picker, "Date selector" text visible instead of calendar icon.

### Additional information

After
Before

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rostilos**
### Fixed Issues (if relevant)

1. Fixes #36499

### Manual testing scenarios (*)
1. Magento Community Edition 2.4.5 without sample data is installed.
2. Login into admin > Marketing > Cart Price Rules
3. Click on date picker of start column in grid, Select the date from date picker
4. After selecting date from the date picker, calendar icon should be visible over there.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rostilos** [comment]
@magento run all tests

**Comment by rostilos** [comment]
@magento run Unit Tests Static Tests

**Comment by rostilos** [comment]
@magento run Unit Tests

**Comment by rostilos** [comment]
@magento run Static Tests

**Comment by rostilos** [comment]
@magento run WebAPI Tests

**Comment by rostilos** [comment]
@magento run Integration Tests

**Comment by rostilos** [comment]
https://github.com/magento run Integration Tests, Functional Tests B2B, Functional Tests EE, Static Tests

**Comment by rostilos** [comment]
@magento run Integration Tests, Functional Tests B2B, Functional Tests EE, Static Tests

**Comment by rostilos** [comment]
https://github.com/magento run Static Tests

**Comment by rostilos** [comment]
@magento run Static Tests

**Comment by rostilos** [comment]
@magento run all tests

**Comment by rostilos** [comment]
@magento run Unit Tests , WebAPI Tests

**Comment by rostilos** [comment]
@magento run Static Tests

**Comment by hostep** [comment]
According to a recent comment in https://github.com/magento/magento2/issues/36499#issuecomment-1505563669, the issue got fixed internally by Adobe, which would mean that this PR is no longer necessary. @rostilos: maybe you can confirm this is fixed now on the `2.4-develop` branch?

**Comment by engcom-Hotel** [comment]
Hello @rostilos,

Thank you for the contribution!

We discovered that the fix for this issue has been delivered internally. We apologize for missing that there is a public contribution available. We are taking measures to avoid situations like these in the future.

Thanks again!

**Pull request closed without merging**
