### PR TITLE
2.1

### PR DESCRIPTION
**Pull request by manikbhardwaj**

### CODE REVIEW

**Comment by orlangur** [comment]
@manik348, what did you try to accomplish?

**Comment by manikbhardwaj** [comment]
I want to merge 2.1 into 2.0.

**Comment by orlangur** [comment]
It is not possible as it would ruin versioning policy. All necessary branches - 2.0, 2.1, develop (aka 2.2.0-dev) - are already created.

**Comment by manikbhardwaj** [comment]
Actually i fork magento 2 in my github but it does not show me 2.1. it is only showing develop and 2.0.
I want to add 2.1 also on list.

**Comment by orlangur** [comment]
I see... http://stackoverflow.com/questions/4410091/github-import-upstream-branch-into-fork can be helpful on this.
Basically, you need to checkout 2.1 branch from mainline repository and push it to your fork.

**Pull request closed without merging**
