### PR TITLE
Resolve No validate "Proxy Port" in Paypal Module (Paypal Express, Paypal Payflow -Link, Pro, Advanced) issue24304

### LINKED ISSUE #24304: No validate "Proxy Port" in Paypal Module (Paypal Express, Paypal Payflow -Link, Pro, Advanced)
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Store->Configurations
3. Sales-> Payment Methods
4. "API Uses Proxy" in Paypal Express, Paypal Payflow, Paypal Pro is "Yes"
5. "Proxy Port" fill "one"
6. Save

### Expected result (*)

1. Can not save because it is not number

### Actual result (*)

1. Save normally

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#24304: No validate "Proxy Port" in Paypal Module (Paypal Express, Paypal Payflow -Link, Pro, Advanced)

Solution: Add "validate-digits validate-zero-or-greater" in .xml file

### Fixed Issues (if relevant)

1. magento/magento2#24304: No validate "Proxy Port" in Paypal Module (Paypal Express, Paypal Payflow -Link, Pro, Advanced)

### Manual testing scenarios (*)

1. Go to backend
2. Store->Configurations
3. Sales-> Payment Methods
4. "API Uses Proxy" in Paypal Express, Paypal Payflow, Paypal Pro is "Yes"
5. "Proxy Port" fill "one"
6. Save

#### Expected result 

1. Can not save because it is not number

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by swnsma — CHANGES_REQUESTED** [review]
Hi @edenduong,

Thank you for your contribution!
Can we use range for validation of port value ([tap](https://en.wikipedia.org/wiki/Port_(computer_networking))) instead of **validate-zero-or-greater** ?

**Comment by edenduong** [comment]
> Hi @edenduong,
> 
> Thank you for your contribution!
> Can we use range for validation of port value ([tap](https://en.wikipedia.org/wiki/Port_(computer_networking))) instead of **validate-zero-or-greater** ?

Thank you for your reviewing. I have change the source code to validate the range 0-65535

Thank you.

**Comment by swnsma** [comment]
> > Hi @edenduong,
> > Thank you for your contribution!
> > Can we use range for validation of port value ([tap](https://en.wikipedia.org/wiki/Port_(computer_networking))) instead of **validate-zero-or-greater** ?
> 
> Thank you for your reviewing. I have change the source code to validate the range 0-65535
> 
> Thank you.

Great!
Thank you!

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-5719](https://jira.corp.magento.com/browse/ENGCOM-5719) has been created to process this Pull Request

**Comment by dmytro-ch** [comment]
Hi @edenduong,
please, combine the pull requests with such improvements in one single pull request on order make it easier to process these PRs by Community Engineering Team.
#24313
#24309
#24303 
#24305
Also, feel free to create pull requests for minor fixes and obvious improvements without opening the issues.

Thank you!

**Comment by magento-engcom-team** [comment]
Hi @edenduong
Thank you for your contribution. This pull request has been combined (merged) with https://github.com/magento/magento2/pull/24313 to optimize pull requests queue on magento/magento2 repository
Closing this pull request.

**Pull request closed without merging**
