### PR TITLE
Remove laminas/laminas-dependency-plugin dependency

### LINKED ISSUE #36515: [Issue] Remove laminas/laminas-dependency-plugin dependency
This issue is automatically created based on existing pull request: magento/magento2#36495: Remove laminas/laminas-dependency-plugin dependency

---------
### Description (*)
This PR removes the `laminas/laminas-dependency-plugin` composer plugin.
The plugin was introduced in https://github.com/magento/magento2/pull/26436 and its purpose is described as follows on [their homepage](https://github.com/laminas/laminas-dependency-plugin):
> This Composer plugin, when enabled in a project, intercepts requests to install packages from the zendframework and zfcampus vendors, and will replace them with the equivalents from the Laminas Project.

Reason why I think we should get rid of this, is that I'm currently unable to use a modern version of composer to install dependencies on the `2.4-develop` branch:
```
$ composer --version
Composer version 2.4.4 2022-10-27 14:39:29

$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - laminas/laminas-dependency-plugin is locked to version 2.5.0 and an update of this package was not requested.
    - laminas/laminas-dependency-plugin 2.5.0 requires composer-plugin-api >=1.1.0 <2.3.0 -> found composer-plugin-api[2.3.0] but it does not match the constraint.
```

Which was a restriction added to that plugin in https://github.com/laminas/laminas-dependency-plugin/commit/54d508ab145072c4c7e7ec07cdad1e10196ad373

I believe that after 2 years since Magento switched from Zend to Laminas, that this plugin is not really necessary anymore, most people will have gotten used to the Laminas components by now and should install those instead of the old Zend ones.

// cc @ihor-sviziev 

### Fixed Issues (if relevant)
None that I know of

### Manual testing scenarios (*)
1. Use composer 2.3.x or 2.4.x
2. Try to run `composer install` without getting errors

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### LINKED ISSUE #36516: Unable to install Magento with Composer version 2.4.4
### Preconditions and environment

- Magento `2.4-develop` branch, after https://github.com/magento/magento2/commit/4b43b2b29e9dc42501875b6356978868a1b1268e
- Composer version 2.3.0 or better

### Steps to reproduce

1. Clone repository
1. Run `composer install`

### Expected result

Required packages are installed.

### Actual result

An error is shown.

Screenshot_2022-11-23_11-51-13

### Additional information

The `laminas/laminas-dependency-plugin` package does not support recent / current versions of Composer. See https://github.com/laminas/laminas-dependency-plugin/pull/41/commits/54d508ab145072c4c7e7ec07cdad1e10196ad373 for some details about this. It's likely that this plug-in can be safely removed from this project.

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by hostep**
### Description (*)
This PR removes the `laminas/laminas-dependency-plugin` composer plugin.
The plugin was introduced in https://github.com/magento/magento2/pull/26436 and its purpose is described as follows on [their homepage](https://github.com/laminas/laminas-dependency-plugin):
> This Composer plugin, when enabled in a project, intercepts requests to install packages from the zendframework and zfcampus vendors, and will replace them with the equivalents from the Laminas Project.

Reason why I think we should get rid of this, is that I'm currently unable to use a modern version of composer to install dependencies on the `2.4-develop` branch:
```
$ composer --version
Composer version 2.4.4 2022-10-27 14:39:29

$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - laminas/laminas-dependency-plugin is locked to version 2.5.0 and an update of this package was not requested.
    - laminas/laminas-dependency-plugin 2.5.0 requires composer-plugin-api >=1.1.0 <2.3.0 -> found composer-plugin-api[2.3.0] but it does not match the constraint.
```

Which was a restriction added to that plugin in https://github.com/laminas/laminas-dependency-plugin/commit/54d508ab145072c4c7e7ec07cdad1e10196ad373

I believe that after 2 years since Magento switched from Zend to Laminas, that this plugin is not really necessary anymore, most people will have gotten used to the Laminas components by now and should install those instead of the old Zend ones.

// cc @ihor-sviziev 

### Fixed Issues (if relevant)
None that I know of

### Manual testing scenarios (*)
1. Use composer 2.3.x or 2.4.x
2. Try to run `composer install` without getting errors

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36515: Remove laminas/laminas-dependency-plugin dependency
2. [x] resolves magento/magento2#36516: Unable to install Magento with Composer version 2.4.4

### CODE REVIEW

**Comment by hostep** [comment]
@magento run all tests

**Comment by hostep** [comment]
Failing tests don't seem to have anything to do with the changes in this PR.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
As to me it fully make sense to remove this plugin as part of platform health project.
/CC @sidolov @andrewbess

**Comment by hostep** [comment]
Rebased on latest 2.4-develop, because conflicts were introduced recently by https://github.com/magento/magento2/commit/142b483206acc24a5289f126c677066c7d964338

I'm afraid this will keep happening if the composer files are being updated all the time. The maintainers here have my permission to fix conflicts themselves in this PR during my holiday period (end November till end December).

@magento run all tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento `2.4-develop`

**Manual testing scenario:**
1.  Use composer 2.4.x.
2. Run composer install without getting errors.

**Before:** :heavy_multiplication_x: 
Screenshot 2022-11-23 at 4 16 35 PM

**After:** :heavy_check_mark:  
Screenshot 2022-11-23 at 4 53 38 PM

No additional manual test case is required as part of regression.

Builds are failed , hence, moving it to extended testing.

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Echo** [comment]
@magento run Adobe CLA Signed?

**Comment by engcom-Echo** [comment]
@magento run Adobe CLA Signed?

**Pull request merged**
