### PR TITLE
2.3 develop Fix Translate into Indonesian language

### PR DESCRIPTION
**Pull request by Fzyn56**
### Description

helping magento with translation problem into indonesia language

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: en_US.csv

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=13568) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=13568) before we can accept your contribution.<br/>**4** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: okorshenko<br/>:white_check_mark: ishakhsuvarov<br/>:white_check_mark: okolesnyk<br/>:white_check_mark: joni-jones<br/>:x: danielrenaud<br/>:x: eric-bohanon<br/>:x: dthampy<br/>:x: magento-engcom-team<br/>:x: sereban<br/>:x: rganin

**Comment by Fzyn56** [comment]
I want to contribute in this project, I want Translate into Indonesia language.

**Comment by orlangur** [comment]
Hi @hansconan,

> wants to merge 4,144 commits into `2.2-develop` from `2.3-develop`

Please create PR based on a proper branch from your fork.

**Comment by orlangur** [comment]
> I want to contribute in this project, I want Translate into Indonesia language.

Please check https://crowdin.com/project/magento-2 on translating Magento to different languages (you can find this link under right badge on https://github.com/magento/magento2/blob/2.2-develop/README.md).

**Pull request closed without merging**
