### PR TITLE
FIX #14080 Added improvements to Category repository (save method)

### LINKED ISSUE #14080: Category path is the same as key producing duplicate URL issue
### Preconditions
Magento 2.4
Ubuntu 18.04

### Steps to Reproduce

1. Create any category on second level (with parent_id =2).
Name: Test category 1, Url key: test-category-1.
2. Create sub category in "Test category 2" with `level = 2` by res api:
`/V1/categories`
```json
{
	"category": {
		"name": "Test category 2",
		"parent_id":"3",  /* Test category 1 */
		"is_active":"true",
		"include_in_menu": true,
		"level":"2",
		"custom_attributes": [{ "attribute_code": "url_key", "value": "test-category-2" }]
	}
}
```
At now we have the url_key: "test-category-1" and path: "/test-category-1/test-category-2".

3. Change the url key of the Test category 2 either in the backend or via the api to something like "test-category-2-changed"

### Expected result:
Category "Test category 2" has attribute values:
url_key: "test-category-2-changed"
url_path: "/test-category-1/test-category-2-changed"

### Actual result:
Category "Test category 2" has attribute values:
url_key: "test-category-2-changed"
url_path: "test-category-2-changed"

**Note**
When I try to change a category url key, it changes the path to be identical which results in an error being raised and short category urls which don't include its parent, it has now affected categories that I haven't explicitly changed/saved.
(table `catalog_category_entity_varchar`)

screen shot 2018-03-13 at 12 35 48

As you can see from the screen shot (with url_key, attribute_id 117 and url_path, attribute_id 118) the mens-footwear category has been affected but not the womens-footwear category.

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Added improvements to category repository (save method) to fix level issue.

### Fixed Issues (if relevant)
#14080

### Manual testing scenarios
See #14080 issue description for details.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
Related PR #27291

**Comment by sergiy-v** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run all tests

**Comment by sergiy-v** [comment]
@eduard13 PR is ready to review, the functional tests errors are not related to the changes.
Thank you.

**Review by lbajsarowicz — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7112](https://jira.corp.magento.com/browse/ENGCOM-7112) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by lbajsarowicz** [comment]
@sergiy-v I really like the fact that you covered that change with MFTF tests. However (!) I'm not sure if it's the best approach to cover that kind of change. What I mean is that in this specific case Integration Tests would give cleaner overview what is happening under the hood. 

Thanks once again for well-done Functional Test.

**Comment by sergiy-v** [comment]
> @sergiy-v I really like the fact that you covered that change with MFTF tests. However (!) I'm not sure if it's the best approach to cover that kind of change. What I mean is that in this specific case Integration Tests would give cleaner overview what is happening under the hood.
> 
> Thanks once again for well-done Functional Test.

@lbajsarowicz Thanks for your thoughts, will keep it in mind next time)

**Review by eduard13 — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-7112](https://jira.corp.magento.com/browse/ENGCOM-7112) has been created to process this Pull Request
:eight_spoked_asterisk: @eduard13, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi, @sergiy-v 

During testing, we faced the issue.

**_Problem:_** The category is saved with the wrong **url_path**

**Manual testing scenario:**
**1.** Create any category on the second level (with parent_id =2).
Name: Test category 1, Url key: test-category-1.
**2.** Create subcategory in "Test category 2" with level = 2 by rest api:
/V1/categories
```json
{
	"category": {
		"name": "Test category 2",
		"parent_id":"3",  /* Test category 1 */
		"is_active":"true",
		"include_in_menu": true,
		"level":"2",
		"custom_attributes": [{ "attribute_code": "url_key", "value": "test-category-2" }]
	}
}
```
**Actual Result:**
:heavy_multiplication_x:  Now we have the url_key: "test-category-2" and path: "test-category-2"
Screenshot from 2020-03-17 15-45-36

**Expected Result:**
:heavy_check_mark:  The url_path should be "/test-category-1/test-category-2"

**3.** Change the URL key of the Test category 2 either in the backend or via the api to something like "test-category-2-changed"

**Actual Result:**

:heavy_multiplication_x: Category "Test category 2" has attribute values:
url_key: "test-category-2-changed"
url_path: "test-category-2-changed"
Screenshot from 2020-03-17 16-10-58
Or Am I wrong?

@sergiy-v Could you take a look?

Thanks!

**Comment by sergiy-v** [comment]
Hi, @engcom-Alfa.
Unfortunately I can not reproduce it.
Please check testing scenario steps, maybe I missed something.

**Manual testing scenario:**
1. Created category on the second level (with parent_id =2).
**Name**: Test category 1,
**Url key**: test-category-1.
Screen Shot 2020-03-17 at 4 57 13 PM

2. Created subcategory in "Test category 2" with level = 2 by rest api:
/V1/categories
Screen Shot 2020-03-17 at 4 59 44 PM

**Result:**
Screen Shot 2020-03-17 at 5 01 09 PM

3. Changed the URL key of the "Test category 2" via Admin Panel to "test-category-2-changed"
Screen Shot 2020-03-17 at 5 03 54 PM
**Result:**
Screen Shot 2020-03-17 at 5 04 57 PM

@engcom-Alfa if we would not find the reason of the bug - I will update the test with all described steps.

Thank you.

**Comment by engcom-Alfa** [comment]
@sergiy-v Thank you for the clarification!
I checked again and everything works correctly. 
Thanks!

**Comment by engcom-Alfa** [comment]
@lbajsarowicz @eduard13 Could you approve again?
Thank you!

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-7112](https://jira.corp.magento.com/browse/ENGCOM-7112) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:**
before

**After:**
after

**Review by lbajsarowicz — APPROVED** [review]
:heavy_check_mark: Thank you for your contribution.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7112](https://jira.corp.magento.com/browse/ENGCOM-7112) has been created to process this Pull Request

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Pull request merged**
