### PR TITLE
Bundle-Product-add-to-cart-button-misaligned-on-tab-portrait ::Bundle…

### PR DESCRIPTION
**Pull request by ajay2jcommerce**
… Product add to cart button misaligned on tab portrait view.

### Fixed Issues (if relevant)

1. magento/magento2#20193: Bundle Product add to cart button misaligned on tab portrait view
2. ...

### Manual testing scenarios (*)

1.In product detail page on "Bundle Product" click "Customize and Add to Cart" show bundle option check "add to cart" button.
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ajay2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3871](https://jira.corp.magento.com/browse/ENGCOM-3871) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@ajay2jcommerce thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @ajay2jcommerce. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
