### PR TITLE
[TEST, DO NOT TOUCH] checking fixes (updated 2021-10-13)

### PR DESCRIPTION
**Pull request by karyna-t**
### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/625

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests with env PHP 8.0

**Comment by andrewbess** [comment]
@magento run all tests with env PHP 8.0

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests with env PHP 8.0

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests with env PHP 8.0

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by anzin** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by anzin** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE with env PHP 8.0

**Pull request closed without merging**
