### PR TITLE
Fixed issue for save int & small-int default value.

### PR DESCRIPTION
**Pull request by nishantjariwala**
### Description (*)
Hi,
Here I've found an issue while saving blank field of database type int & small-int. It should be blank if I leave it blank but rather then it set that field value to 0.

### Fixed Issues (if relevant)

1. magento/magento2#23268: Issue with value set to 0 for int & smallint type fields.

### Manual testing scenarios (*)

1. Create field with int/smallint & set it's default value to NULL in database.
2. Add above field in any form.
3. Now, Leave it blank and save the form.
4. Here, It should be NULL but rather than it's storing as 0.
5. https://prnt.sc/o1ug19

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23269) <br/>All committers have signed the CLA.

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
Hi @nishantjariwala , looks like provided changes broke a lot of Magento scenario, a lot of tests are failing. Could you take a look?

**Comment by sidolov** [comment]
@nishantjariwala  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by sidolov** [comment]
@nishantjariwala , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
