### PR TITLE
Test coverage for PR #27357 (E-mail templates)

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Additional Integration Tests coverage for PR provided by @ptylek 

### Fixed Issues (if relevant)
1. magento/magento2#27357

### Manual testing scenarios (*)

1. ...
2. ...

### Support
Solving this issue is supported by [Mediotype](mediotype.com)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7461](https://jira.corp.magento.com/browse/ENGCOM-7461) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Review by slavvka — CHANGES_REQUESTED** [review]
@lbajsarowicz please resolve the conflicts and re-run tests after upgrade to PHP 7.4

**Review by slavvka — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @slavvka, thank you for the review.
[ENGCOM-7461](https://jira.corp.magento.com/browse/ENGCOM-7461) has been created to process this Pull Request

**Comment by lbajsarowicz** [comment]
@magento run all tests

I'd like to verify if there are no issues with current mainline.

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

Just to make sure that nothing was broken in the meantime.

**Comment by ihor-sviziev** [comment]
@slavvka @VladimirZaets is there any reasons why this PR isn't getting merged?

**Comment by ihor-sviziev** [comment]
Progress:accept label just disappeared. I just fixed it

**Pull request merged**
