### PR TITLE
Fix loading of calendar script

### LINKED ISSUE #32260: [Issue] Fix loading of calendar script
This issue is automatically created based on existing pull request: magento/magento2#32255: Fix loading of calendar script

---------
Fix calendar mixins loading in Safari and Firefox.

### Description (*)
There is a bug with the loading of mixins in Safari and Firefox. 

When you call the widget using the imperative notation: `.calendar({`, the mixin for this module is not loading in Safari and Firefox. 

We change the calendar widget to be initialized in declarative notation to avoid this problem: `<script type="text/x-magento-init">`

### Manual testing scenarios (*)

1. Create a mixin for `mage/calendar`

app/code/Vendor/Module/view/frontend/requirejs-config.js:
```
var config = {
    config: {
        mixins: {
            'mage/calendar': {
                'Vendor_Module/js/lib/mage/calendar-mixin': true
            }
        }
    }
};
```
app/code/Vendor/Module/view/frontend/web/js/lib/mage/calendar-mixin.js:
```
define([
    'jquery'
], function ($) {
    'use strict';

    return function (widget) {
        $.widget('mage.calendar', widget.calendar, {
            _initPicker: function (element) {
               console.log('calendar mixin initialized');
           }
        });

        return $.mage.calendar;
    };
});
```

2. Open the page on the frontend with a date picker input (e.g. date of birth in customer account).

-- __Before Fix:__ --

**Expected result:** calendar-mixin.js is loading in Safari and Firefox (Dev Tools -> Network), `calendar mixin initialized` is in the console output.
**Actual result:** calendar-mixin.js is not loading in Safari and Firefox, no message in the console.

-- __After Fix:__ --

**Expected result:** calendar-mixin.js is loading in Safari and Firefox (Dev Tools -> Network), `calendar mixin initialized` is in the console output.
**Actual result:** calendar-mixin.js is loading in Safari and Firefox, `calendar mixin initialized` message written in the console.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by artttj**
Fix calendar mixins loading in Safari and Firefox.

### Description (*)
There is a bug with the loading of mixins in Safari and Firefox. 

When you call the widget using the imperative notation: `.calendar({`, the mixin for this module is not loading in Safari and Firefox. 

We change the calendar widget to be initialized in declarative notation to avoid this problem: `<script type="text/x-magento-init">`

### Manual testing scenarios (*)

1. Create a mixin for `mage/calendar`

app/code/Vendor/Module/view/frontend/requirejs-config.js:
```
var config = {
    config: {
        mixins: {
            'mage/calendar': {
                'Vendor_Module/js/lib/mage/calendar-mixin': true
            }
        }
    }
};
```
app/code/Vendor/Module/view/frontend/web/js/lib/mage/calendar-mixin.js:
```
define([
    'jquery'
], function ($) {
    'use strict';

    return function (widget) {
        $.widget('mage.calendar', widget.calendar, {
            _initPicker: function (element) {
               console.log('calendar mixin initialized');
           }
        });

        return $.mage.calendar;
    };
});
```

2. Open the page on the frontend with a date picker input (e.g. date of birth in customer account).

-- __Before Fix:__ --

**Expected result:** calendar-mixin.js is loading in Safari and Firefox (Dev Tools -> Network), `calendar mixin initialized` is in the console output.
**Actual result:** calendar-mixin.js is not loading in Safari and Firefox, no message in the console.

-- __After Fix:__ --

**Expected result:** calendar-mixin.js is loading in Safari and Firefox (Dev Tools -> Network), `calendar mixin initialized` is in the console output.
**Actual result:** calendar-mixin.js is loading in Safari and Firefox, `calendar mixin initialized` message written in the console.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32260: Fix loading of calendar script

### CODE REVIEW

**Comment by artttj** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by artttj** [comment]
Some checkings failed, it's turned out this affects calendars in products export in the admin. A possible solution is to check for area code. Please feel free to advise though.

**Comment by artttj** [comment]
@magento I am working on this

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@artttj 
> Some checkings failed, it's turned out this affects calendars in products export in the admin. A possible solution is to check for area code. Please feel free to advise though.

Could you explain what the issue you see, so I may help you

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @artttj & @ihor-sviziev 

Thank you for your contribution!

I am going through this issue and will update it with the findings.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi  @artttj & @ihor-sviziev,

Here are the findings-

From functional test EE and Functional test B2B below 2 test cases are failing.

1. app/code/Magento/CustomAttributeManagement/Test/Mftf/Test/StorefrontAssertCalendarButtonNearDateFieldCustomerAttributeTest.xml
In this test, the datepicker element i.e ui-datepicker-trigger v-middle is itself is not getting loaded which is causing the failure.

2. app/code/Magento/ScheduledImportExport/Test/Mftf/Test/AdminScheduledExportGridFilteringTest.xml
For this one, If we go to admin/scheduled_operation/new/type/export/ page, select Product as a Entity Type, putting Attribute Code in search criteria then search functionality is not working.

Both of the test case are failing because of the PR changes. Need to have a look on Integration tests yet.

Thank you!

**Comment by engcom-Charlie** [comment]
It seems that bot moved this issue from Changes Requested to Review in Progress so pulling it back to Changes Requested.

Thank you!

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @artttj,
This change causes a regression issue on the Magento EE (exact steps to reproduce you can see in failed Functional Test results).
I was able to reproduce it on the test instance.
https://4e7b8d4587c9b0642caab7edd5f57247.instances.magento-community.engineering/customer/account/create/
image
image
As you can see -we're getting object to the "bind" function
I think it should be reproducible on the Magento OS as well.

Could you re-check the issue and update your PR accordingly?

**Pull request closed without merging**
