### PR TITLE
Fixed issue #23135: Insert Variable popup missing template variables for new templates

### PR DESCRIPTION
**Pull request by mahesh-rajawat**
Fixed Issue: Insert Variable popup missing template variables for new Email Templates

### Description (*)

I have fixed issue #23135 in this PR. 
### Fixed Issues (if relevant)

1. #23135: Insert Variable popup missing template variables for new templates

### Manual testing scenarios (*)

1. Go to Marketing > Email Templates and press Add New Template button.
2. Select some template (e.g. Contact Form) and press Load Template button.
3. Press Insert Variable button.
4. Template Variables also there in insert variable popup.
https://prnt.sc/nyx7fo

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by orlangur — CHANGES_REQUESTED** [review]
@maheshWebkul721 please add more details to commit message.

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

**Comment by mahesh-rajawat** [comment]
@orlangur In static test, it says there are multiple blank line on line no. 60.
Could you please let me know where are multiple line here: 
`https://github.com/magento/magento2/blob/8a47b415e184692661ea4cba230d02a44f367f31/app/code/Magento/Email/Block/Adminhtml/Template/Edit/Form.php#L60 ` :wink:

**Review by sidolov — APPROVED** [review]
@engcom-Foxtrot , please, take care of failed tests after QA activities

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5440](https://jira.corp.magento.com/browse/ENGCOM-5440) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
