### PR TITLE
Fixed issue #16425

### PR DESCRIPTION
**Pull request by geet07**
### Description (*)

OR Condition in searchCriteria (REST API) dosn't work

### Fixed Issues (if relevant)

1. magento/magento2#16425: OR Condition in searchCriteria (REST API) dosn't work

### Manual testing scenarios (*)

Create some categories (two or three)
Create come products foreach category
Enable a REST API token
Make a call to resource "/V1/products" with a search parameter like this:
```
["searchCriteria"]=>
  array(1) {
    ["filterGroups"]=>
    array(1) {
      [1]=>
      array(1) {
        ["filters"]=>
        array(2) {
          [0]=>
          array(3) {
            ["field"]=>
            string(11) "category_id"
            ["value"]=>
            string(3) "{id category 1}"
          }
          [1]=>
          array(3) {
            ["field"]=>
            string(11) "category_id"
            ["value"]=>
            string(3) "{id category 2}"
          }
        }
      }
    }
  }
```
This condition will return all products in category {id category 1} OR {id category 2}
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by geet07** [comment]
Hi @orlangur 

Is there any other change required?

**Comment by orlangur** [comment]
@magento run all tests

**Review by sidolov — CHANGES_REQUESTED** [review]
@geet07 please, take a look at failed tests

**Comment by VladimirZaets** [comment]
@geet07, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Pull request closed without merging**
