### PR TITLE
[Forwardport] Clean code

### PR DESCRIPTION
**Pull request by torhoehn**
### Original Pull Request 
 https://github.com/magento/magento2/pull/16841

### Description

Just modify some code, and make it Cleaner more...

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by sidolov** [comment]
@torhoehn , please, take a look at failed tests

**Comment by sidolov** [comment]
Hi @torhoehn , tests still failing, will continue progress with this PR?

**Comment by sidolov** [comment]
Hi @torhoehn , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
