### PR TITLE
addProductsToCart mutation reports proper errors in user_errors request in GraphQL

### LINKED ISSUE #37908: GraphQL addProductsToCart mutation reports unrelated errors in user_errors
### Preconditions and environment

- 2.4.6-p2
- Demo products available
- MSI configured (although not known if it is a specific MSI issue)

### Steps to reproduce

1. Create a product "PRODUCT-1" with inventory of 100
2. Create a product "PRODUCT-2" with inventory of 100 (make sure indexers etc. have ran)

3. Create an empty cart:

```graphql
mutation {
  createEmptyCart(input: {cart_id: "CART_ID_CART_ID_CART_ID_CART_ID_"})
}
```

4. Add a product with for quantity of 100 to the cart.

```graphql
mutation AddProductOne {
  addProductsToCart(cartId: "CART_ID_CART_ID_CART_ID_CART_ID_", cartItems: [{
    sku: "PRODUCT-1",
    quantity: 100
  }]) {
    cart {
      items {
        ... on SimpleCartItem {
          quantity
        }
        errors {
          code
          message
        }
      }
    }
    user_errors {
      code
      message
    }
  }
}
```

5. Run this mutation again, you will see an error on `user_errors`, this is correct.
6. Change the quantity of PRODUCT-1 to 50 in the backend
7. Validate that the items[0].errors has entries:

```graphql
query GetCart {
  cart(cart_id: "CART_ID_CART_ID_CART_ID_CART_ID_") {
    items {
      ... on SimpleCartItem {
        quantity
      }
      product {
        sku
      }
      errors {
        code
        message
      }
    }
  }
}
```
8. Add the second product to the cart with quantity of 1

```graphql
mutation {
  addProductsToCart(cartId: "CART_ID_CART_ID_CART_ID_CART_ID_", cartItems: [{
    sku: "PRODUCT-2",
    quantity: 1
  }]) {
    cart {
      items {
        ... on SimpleCartItem {
          quantity
        }
        product {
          sku
        }
        errors {
          code
          message
        }
      }
    }
    user_errors {
      code
      message
    }
  }
}
```

### Expected result

I would expect the user_errors to be empty because there was no error with the operation, only an error with the cart it's self.

### Actual result

user_errors contains the error of the other item..

### Additional information

We currently have to do some very dirty checking to see on which item this error occurs and do a string match on the message to filter any cart item errors. This is not foolproof and is slow when there are many items in the cart. This issue arises because add to cart actions become very slow when there are many items in the cart because we fetch those items on each action.

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Vasudev-22**
### Description (*)

As per this issue, the condition for failed sku, we need to show the error in user_errors field, but in the code, it was pushed the cart error along with the failed user input, so the correct sku also got an error.

### Related Pull Requests
1. Fixes for #37908

### Fixed Issues (if relevant)

1. Fixes magento/magento2#37908

### Manual testing scenarios (*)

1. Create a product "PRODUCT-1" with inventory of 190
2. Create a product "PRODUCT-2" with inventory of 123 (make sure indexers etc. have ran)
3. Create an empty cart:
4. Add a product with for quantity of 123 to the cart.
5. Run this mutation again, you will see an error on user_errors, this is correct.
6. Change the quantity of PRODUCT-2 to 50 in the backend
7. Add the first product to the cart with quantity of 1

We have added a PRODUCT-2 with more than qty 123.
Here We are getting errors it is expected.
user error will come only when the user is trying to add insufficient qty product.

Screenshot 2023-09-27 at 4 32 10 PM
Screenshot 2023-09-27 at 4 31 55 PM

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Vasudev-22** [comment]
@magento run all test

**Comment by Vasudev-22** [comment]
@magento run all test

**Comment by Vasudev-22** [comment]
@/magento run all test

**Comment by Vasudev-22** [comment]
@magento run all test

**Comment by Vasudev-22** [comment]
@magento run all tests

**Comment by Vasudev-22** [comment]
@magento run all tests

**Comment by Vasudev-22** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Hello @Den4ik,

As I can see you have picked this PR for review, are you still on it?

**Comment by Den4ik** [comment]
Hi @engcom-Hotel 
Yep, I'll provide review update today

**Comment by Den4ik** [comment]
@magento run Integration Tests

**Comment by Den4ik** [comment]
@magento run Functional Tests CE

**Review by Den4ik — APPROVED** [review]
@Vasudev-22 Thanks for contribution.
Changes looks ok. Tested locally, and all looks correct

**Comment by Den4ik** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by Den4ik** [comment]
@magento run Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Comment by engcom-Delta** [comment]
@magento run Functional Tests CE

**Comment by Den4ik** [comment]
@magento run Functional Tests CE

**Comment by engcom-Delta** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

1. Create a product "PRODUCT-1" with inventory of 190
2. Create a product "PRODUCT-2" with inventory of 123 (make sure indexers etc. have ran)
3. Create an empty cart
4. Add PRODUCT-2 with for quantity of 123 to the cart
5. Run this mutation again, you will see an error on user_errors, this is correct
6. Change the quantity of PRODUCT-2 to 50 in the backend
7. Add the PRODUCT-1 to the cart with quantity of 1
8. Add the PRODUCT-2 to the cart with quantity of 1

**Before:** :heavy_multiplication_x: 

Screenshot 2023-11-09 at 2 45 14 AM

Screenshot 2023-11-09 at 2 47 55 AM

Screenshot 2023-11-09 at 2 49 06 AM

Screenshot 2023-11-09 at 2 49 20 AM

Screenshot 2023-11-09 at 2 51 12 AM

Screenshot 2023-11-09 at 2 52 59 AM

Screenshot 2023-11-09 at 2 54 46 AM


**After:** :heavy_check_mark:  

Screenshot 2023-11-09 at 2 14 35 AM

Screenshot 2023-11-09 at 2 21 26 AM

Screenshot 2023-11-09 at 2 23 05 AM

Screenshot 2023-11-09 at 2 23 16 AM

Screenshot 2023-11-09 at 2 31 44 AM

Screenshot 2023-11-09 at 2 34 03 AM

Screenshot 2023-11-09 at 2 34 20 AM


Build is failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B,  Functional Tests CE, Functional Tests EE, Integration Tests, Unit Tests

**Comment by engcom-Charlie** [comment]
As the build is green now, moving this PR to Merge in Progress.

**Pull request merged**
