### PR TITLE
Checkout module: Removing deprecated Message Manager method calls

### PR DESCRIPTION
**Pull request by Loxzibit**
### Description
Removing usage of deprecated Message Manager method calls on the Checkout module

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14343) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
@Loxzibit thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by sidolov** [comment]
Hi @Loxzibit , please, take a look at the failed unit and static tests!

**Comment by Loxzibit** [comment]
Hi @sidolov I've addressed the failing tests.

**Comment by sidolov** [comment]
@Loxzibit looks good!
 Thank you for your contribution!

**Pull request merged**
