### PR TITLE
CatalogImportExport validation

### PR DESCRIPTION
**Pull request by bartdelvauxx**

### CODE REVIEW

**Comment by bartdelvauxx** [comment]
This pull request solves 2 issues when doing a catalog product import. 

The first issue appears when you have a required attribute in your configuration and you import new products. With this fix, you solves an error of using an undefined class constant. 

The second issue appears with the validation of the file. A message was returned that a file was empty (even there is data in). This issue was solved by updating the processed rows count.

**Comment by vpelipenko** [comment]
Integration tests were failed. I've just restarted this job.

**Comment by kokoc** [comment]
@bartdelvauxx Thank you for the contribution!

CR: passed
Resolution: ready to merge
Internal reference: MAGETWO-37499
Builds: Green

**Comment by kokoc** [comment]
@bartdelvauxx your pull request is merged in 0.74.0-beta10. Thank you very much for your contribution and continued support to Magento 2!

**Comment by kokoc** [comment]
@bartdelvauxx your pull request is merged in 0.74.0-beta10. Thank you very much for your contribution and continued support to Magento 2!

**Pull request merged**
