### PR TITLE
[Wishlist] Giving the possibility to set/update item description on item update

### LINKED ISSUE #28261: [Issue] [Wishlist] Giving the possibility to set/update item description on item update
This issue is automatically created based on existing pull request: magento/magento2#28222: [Wishlist] Giving the possibility to set/update item description on item update

---------

### Preconditions (*)
This PR improves the wishlist item update, by allowing to update the description while updating the wishlist item.

The problem occurs, when we want to set/update the item description in the same time when we update item's quantity, which doesn't seem to be supported for now.

### Fixed Issues (if relevant)
N/A
### Steps to reproduce:

1. Create a simple product;
2. Log in on the storefront
3. Add the simple product to wishlist
4. Now, programmatically, try to update the quantity and the description for this item.

```
$wishlistId = 1;
$wishlistItemId = 1;

/** @var \Magento\Wishlist\Model\Wishlist $wishlist */
$wishlist = $objectManager->create(\Magento\Wishlist\Model\Wishlist::class);
$wishlistItemFactory = $objectManager->create(\Magento\Wishlist\Model\ItemFactory::class);
$wishlistItemResource = $objectManager->create(\Magento\Wishlist\Model\ResourceModel\Item::class);
$wishlist->load($wishlistId);

/** @var WishlistItem $wishlistItem */
$wishlistItem = $wishlistItemFactory->create();
$wishlistItemResource->load($wishlistItem, $wishlistItemId);
$wishlistItem->setDescription('My new description');
$wishlist->updateItem($wishlistItem, new \Magento\Framework\DataObject(['qty' => 777]));
```

**Actual Result:**     :heavy_multiplication_x: Quantity updated, but no description

screenshot_12

**Expected Result:**  :heavy_check_mark:  Quantity and description updated

screenshot_13

### Questions or comments
Looks like the description, is only used in case there is a new wishlist item created, which only happens if we're trying to update the item with some different options(custom options/super_attribute, etc) that are already added to wishlist.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by eduard13**
### Description (*)
This PR improves the wishlist item update, by allowing to update the description while updating the wishlist item.

The problem occurs, when we want to set/update the item description in the same time when we update item's quantity, which doesn't seem to be supported for now.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)

1. Create a simple product
2. Log in on the storefront
3. Add the simple product to wishlist
4. Now, programmatically, try to update the quantity and the description for this item.
```php
$wishlistId = 1;
$wishlistItemId = 1;

/** @var \Magento\Wishlist\Model\Wishlist $wishlist */
$wishlist = $objectManager->create(\Magento\Wishlist\Model\Wishlist::class);
$wishlistItemFactory = $objectManager->create(\Magento\Wishlist\Model\ItemFactory::class);
$wishlistItemResource = $objectManager->create(\Magento\Wishlist\Model\ResourceModel\Item::class);
$wishlist->load($wishlistId);

/** @var WishlistItem $wishlistItem */
$wishlistItem = $wishlistItemFactory->create();
$wishlistItemResource->load($wishlistItem, $wishlistItemId);
$wishlistItem->setDescription('My new description');
$wishlist->updateItem($wishlistItem, new \Magento\Framework\DataObject(['qty' => 22]));
```

After running this test code, we'll be able to see that we've updated only the qty, and not the description.
### Questions or comments
Looks like the description, is only used in case there is a new wishlist item created, which only happens if we're trying to update the item with some different options(custom options/super_attribute, etc) that are already added to wishlist.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28261: [Wishlist] Giving the possibility to set/update item description on item update

### CODE REVIEW

**Comment by eduard13** [comment]
@magento run all tests

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7561](https://jira.corp.magento.com/browse/ENGCOM-7561) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Create a simple product;
2. Log in on the storefront
3. Add the simple product to wishlist
4. Now, programmatically, try to update the quantity and the description for this item.

```
$wishlistId = 1;
$wishlistItemId = 1;

/** @var \Magento\Wishlist\Model\Wishlist $wishlist */
$wishlist = $objectManager->create(\Magento\Wishlist\Model\Wishlist::class);
$wishlistItemFactory = $objectManager->create(\Magento\Wishlist\Model\ItemFactory::class);
$wishlistItemResource = $objectManager->create(\Magento\Wishlist\Model\ResourceModel\Item::class);
$wishlist->load($wishlistId);

/** @var WishlistItem $wishlistItem */
$wishlistItem = $wishlistItemFactory->create();
$wishlistItemResource->load($wishlistItem, $wishlistItemId);
$wishlistItem->setDescription('My new description');
$wishlist->updateItem($wishlistItem, new \Magento\Framework\DataObject(['qty' => 777]));
```

**Before:**     :heavy_multiplication_x: Quantity updated, but no description

screenshot_12

**After:**  :heavy_check_mark:  Quantity and description updated

screenshot_13

**Comment by slavvka** [comment]
@magento create issue

**Pull request merged**
