### PR TITLE
Replaced ArrayInterface with OptionSourceInterface

### PR DESCRIPTION
**Pull request by sreichel**
### Description (*)

> lib\internal\Magento\Framework\Option\ArrayInterface.php

```
/**
 * @todo Remove in favor of the ancestor interface
 */
interface ArrayInterface extends \Magento\Framework\Data\OptionSourceInterface
```

Replaced all occurrences and marked ArrayInterface as deprecated.

### Fixed Issues (if relevant)

1. n/a

### Manual testing scenarios (*)

1. n/a

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @sreichel. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
Considering that theoretically, this is backward incompatible change, probably it would be better to mark the interface as deprecated first. However, I think it is very unlikely that ArrayInterface is used as a parameter type anywhere. Added this pull request to discuss at a group code review.

**Comment by sreichel** [comment]
@sivaschenko Thanks for reply, I've not removed the interface. It marked as deprecated and not used in core. Should not break anything. (?)

**Comment by sivaschenko** [comment]
@sreichel I.e. it will break code where:
- there is a method that accepts a parameter of type ArrayInterface, 
- and this method is called passing an instance of a class that was implementing ArrayInterface before this pull request (but does not implement anymore).

**Comment by sivaschenko** [comment]
Hi @sreichel we had a group code review session today discussing this pull request, we decided that is will be unsafe to replace the interface on this stage. It's ok to mark the interface as deprecated for now. Then after a couple of releases with it being deprecated, it will be ok to replace it.

**Comment by sreichel** [comment]
@sivaschenko is it OK to set `@decreacted` via internal ticket?

**Comment by sivaschenko** [comment]
@sreichel I am not sure about internal tickets, you can do it in this pull request as I think anyway this pull request will have to be recreated by the time it will be OK to deliver it.

**Comment by sivaschenko** [comment]
@sreichel the pull request is put on hold. Please open another pull request with a link to this one where  an interface is marked as deprecated

**Comment by sivaschenko** [comment]
It is necessary to deprecate the interface before removing it from inheritance hierarchy. This pull request will be processed a couple of releases after https://github.com/magento/magento2/pull/19601 is merged

**Comment by orlangur** [comment]
@sivaschenko are you sure it can be processed earlier than `2.4-develop`?

**Comment by sivaschenko** [comment]
@orlangur In my opinion it can be processed earlier, however, no, I am not sure.

**Comment by orlangur** [comment]
@sivaschenko keeping open pull request is not a proper way to track necessary changes. Please report internal ticket targeting `2.4-develop` describing necessary changes instead.

**Comment by orlangur** [comment]
Changed my mind.

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @sreichel , we are going to resume processing of this pull request.

Can you please update your branch, resolve conflicts and ensure all tests are passing

**Comment by sivaschenko** [comment]
The pull request is approved to be merged to 2.4 at https://github.com/magento/architecture/issues/174 including the removal of ArrayInterface

**Comment by sreichel** [comment]
I'll update for 2.4.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @sreichel,
Branch `2.4-develop` was already created and this PR was re-targeted into it. Could you update your PR and resolve merge conflicts?

**Comment by ihor-sviziev** [comment]
Hi @sreichel,
Will you be able to finalize your PR, or we can close it?

**Comment by ihor-sviziev** [comment]
@sreichel  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
