### PR TITLE
[Forwardport] Remove extra spaces from Magento/Ui

### PR DESCRIPTION
**Pull request by ronak2ram**
### Original Pull Request 
 https://github.com/magento/magento2/pull/16872
### Description
Remove extra spaces from Magento/Ui
### Fixed Issues
N/A
### Manual testing scenarios
N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ronak2ram. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by VladimirZaets** [comment]
Hi @ronak2ram , unfortunately, we can't accept this pull request because there is no rule that not allows empty lines or space symbols. 
If you want to add this rule you can discuss it with us in the Slack channel and we will take the decision about it.
Thank you for your contribution!

**Comment by ronak2ram** [comment]
@VladimirZaets 
I find the duplicate port(#17054) of this port. And it's merged.
I am surprised after seeing this.

**Comment by ronak2ram** [comment]
@VladimirZaets @magento-engcom-team 
I find the duplicate port(#17054) of this port. And it's merged.
I am surprised after seeing this.

**Pull request closed without merging**
