### PR TITLE
[WIP] Issue 33955 min qty allowed

### LINKED ISSUE #33955: "Minimum Qty Allowed in Shopping Cart" for simple product bug when adding product more than once
### Preconditions (*)

1. Magento CE 2.4.2-p2

### Steps to reproduce (*)

1. Set simple product to have a "Minimum Qty Allowed in Shopping Cart" >1 for example 5 
grafik
2. Go to frontend to this product and add 5 pcs of this item to the cart 
grafik
3. Stay on product page and add 1 more pc to the cart 
grafik

### Expected result (*)

1. Because the minimum qty of the item is already in the cart I expect any other qty (in this example additional 1) to be addable to the cart

### Actual result (*)

1. It is not possible to add any qty < than the minimum cart qty to the cart.
2. The error message is "The fewest you may purchase is 5."
3. When you go to cart and change the number of the qty to 6 for example it works as expected
grafik

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Bashev**
### Description (*)

Add validation based on quantity in cart. 
See issue #33955 

### Fixed Issues (if relevant)

1. Fixes #33955 

### Manual testing scenarios (*)

1. See #33955 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Bashev** [comment]
@magento give me test instance

**Comment by Bashev** [comment]
@magento give me test instance

**Comment by Bashev** [comment]
@magento give me test instance

**Comment by Bashev** [comment]
@magento give me test instance

**Comment by Bashev** [comment]
@magento give me test instance

**Comment by Bashev** [comment]
@magento give me test instance

**Comment by Bashev** [comment]
@magento give me test instance

**Comment by Bashev** [comment]
@magento give me test instance

**Comment by Bashev** [comment]
@magento give me test instance

**Comment by Bashev** [comment]
@magento give me test instance

**Comment by Bashev** [comment]
@magento give me test instance

**Comment by Bashev** [comment]
@magento give me test instance

**Comment by glo05363** [comment]
@Bashev Thanks for working on the same, This issue has been taken care by internal team in [JIRA](https://jira.corp.adobe.com/browse/AC-1116) . The issue is no more reproducible hence we are closing the same.

**Comment by engcom-Charlie** [comment]
Hi @Bashev,

Thank you for your contribution!

As per [this](https://github.com/magento/magento2/issues/33955#issuecomment-1477352198) comment, closing this PR for now.

Please reopen for any new updates.

Thank you!

**Pull request closed without merging**
