### PR TITLE
Fixed a couple of typos

### PR DESCRIPTION
**Pull request by dverkade**
### Description
- Changed typo "whith" to "with"
- Fixed typo and missing word in test name

### Fixed Issues
None

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @dverkade. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by okorshenko** [comment]
@magento-engcom-team give me 2.2.4 verification instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.2.4 verification instance for you

**Comment by okorshenko** [comment]
@magento-engcom-team give me new test instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [new Magento instance](https://pr-17293.engcom.dev.magento.com).
Admin access: [https://pr-17293.engcom.dev.magento.com/admin](https://pr-17293.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`

**Comment by dverkade** [comment]
@okorshenko please note that this PR is on the **2.3-develop** branch and not on the 2.2-develop branch. So this should be tested with 2.3

**Comment by okorshenko** [comment]
@magento-engcom-team give me 2.2.4 instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.2.4 instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [Magento instance](https://i-17293-2-2-4.engcom.dev.magento.com).
Admin access: [https://i-17293-2-2-4.engcom.dev.magento.com/admin](https://i-17293-2-2-4.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @dverkade. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Pull request merged**
