### PR TITLE
Add action items for stale bot comment

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
cc @sivaschenko

**Comment by sivaschenko** [comment]
Thanks for the PR @ihor-sviziev . The message suggesting to return the attention to the stale issue might help to prevent closing of overlooked important issues.

@sdzhepa what do you think about the comment change?

**Review by sivaschenko — APPROVED** [review]

**Review by sdzhepa — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@sivaschenko exactly! 
Right now message says that we'll just close it and not provides any reasons behind it.

The idea behind closing stale issues - is not just closing them without any reason, but closing **not important ones**. It means if someone could make some progress and fix the issue - why not? If no one

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, thank you for the review.
[ENGCOM-8598](https://jira.corp.magento.com/browse/ENGCOM-8598) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@sivaschenko maybe we should somehow stress that we would like to focus on the most important issues and not spend time on not important ones?

**Comment by sivaschenko** [comment]
@ihor-sviziev I believe we had a lot of communication about the priorities introduction last year.

How do you think we can stress it?

**Comment by ihor-sviziev** [comment]
@sivaschenko not all the contributors are reading all Magento articles. For people that don’t really know the idea behind it might be not clear why would you close the issue. Maybe adding some links to the articles would be good.
Or do you feel it’s clear enough now?

**Comment by sivaschenko** [comment]
@ihor-sviziev I wouldn't include the link to a post in the comment. I think the current content is enough, a simple response in comment will reset the stale counter and the issue will not be closed.

**Comment by ihor-sviziev** [comment]
@sivaschenko ok, so are you going to merge this PR?

**Comment by sivaschenko** [comment]
@ihor-sviziev it's in the queue to mainline now

**Pull request merged**
