### PR TITLE
Fixes-for-account-my-recent-reviews-alignment

### PR DESCRIPTION
**Pull request by priti2jcommerce**
### Description (*)

for account my recent reviews alignment 

### Fixed Issues (if relevant)

1. magento/magento2#20800
2. ...

### Manual testing scenarios (*)

1. add reviews with logged in customer 
2. on my account dashboard 
3. reviews alignment not proper 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-20801.instances.magento-community.engineering).
Admin access: [https://pr-20801.instances.magento-community.engineering/admin](https://pr-20801.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rogyar** [comment]
I've left a comment in the original issue. @priti2jcommerce could you check it, please. The issue description is not clear enough.

**Comment by priti2jcommerce** [comment]
Hi @rogyar 

there is vertical alignment issue
image

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4130](https://jira.corp.magento.com/browse/ENGCOM-4130) has been created to process this Pull Request

**Pull request merged**
