### PR TITLE
"Conditions" field of Catalog Price Rule no reset after clicking reset button issue 23996

### LINKED ISSUE #23996: "Conditions" field of Catalog Price Rule no reset after clicking reset button
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Admin
2. Marketing -> Catalog Price Rule
3. Fill "Condition" Field
4. Click on Reset

### Expected result (*)

1.  should clear when click on Reset.

### Actual result (*)

1. "Condition" still has value

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#23996: "Conditions" field of Catalog Price Rule no reset after clicking reset button

Problem: Reset button has the onclick = location.reload(). But it can not run. Because of form.js also observer the click of reset button to reset, but it only reset the field which rendered by UI Component. 

=> "Condition field form"  can not reset

Solution: just change the id for reset button to "reset_button" id => the  onclick = location.reload() can run.

### Fixed Issues (if relevant)

1. magento/magento2#23996: "Conditions" field of Catalog Price Rule no reset after clicking reset button

### Manual testing scenarios (*)

1. Go to Admin
2. Marketing -> Catalog Price Rule
3. Fill "Condition" Field
4. Click on Reset
=> should clear when click on Reset.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by kalpmehta** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, here is your [Magento instance](https://i-23997-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23997-2-3-develop.instances.magento-community.engineering/admin](https://i-23997-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by kalpmehta — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, thank you for the review.
[ENGCOM-5541](https://jira.corp.magento.com/browse/ENGCOM-5541) has been created to process this Pull Request
:eight_spoked_asterisk: @kalpmehta, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by sidolov — CHANGES_REQUESTED** [review]
Hi @edenduong , I'm not sure that it's correct behavior to reload the whole page just for form reset. 
I have investigated the issue, looks like the that some fields in the form are not UI components, just plain HTML. We have several ways how to fix them: more complex solution - make them as UI components and the second one - adjust reset mechanism to handle fields that are not UI components.

**Comment by edenduong** [comment]
> Hi @edenduong , I'm not sure that it's correct behavior to reload the whole page just for form reset.
> I have investigated the issue, looks like the that some fields in the form are not UI components, just plain HTML. We have several ways how to fix them: more complex solution - make them as UI components and the second one - adjust reset mechanism to handle fields that are not UI components.

@sidolov :

image

The condition field is not a normal input. It is the "HTML" code:

image

So I think we can not know how to "reset" the "HTML element" in this case **"Generally".** If I know the html structure, I can reset it. **But we can not make it generally and make sure other changes like that in the future can be reseted too.** So I think it is better and simple solution it we reloaded the page.

**Pull request closed without merging**
