### PR TITLE
Resolve "Enable Single-Store Mode" is "Yes" but the create New Rating has store view title issue25060

### LINKED ISSUE #25060: "Enable Single-Store Mode" is "Yes" but the create New Rating has store view title
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Settings -> Configuration-> General, "Enable Single-Store Mode" is "Yes"
2. Store-> Ratings -> Add New Rating
3. View the form

image

### Expected result (*)

That field should hidden, because it is in single-store mode

### Actual result (*)

image

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#25060: "Enable Single-Store Mode" is "Yes" but the create New Rating has store view title

### Fixed Issues (if relevant)

1. magento/magento2#25060: "Enable Single-Store Mode" is "Yes" but the create New Rating has store view title

### Manual testing scenarios (*)

1. Go to Settings -> Configuration-> General, "Enable Single-Store Mode" is "Yes"
2. Store-> Ratings -> Add New Rating
3. View the form
=> No show the field store-view scope title 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello @edenduong, thank you for your contribution. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) the changes should be covered by tests. Could you please cover your fix by automated tests?
Thank you!

**Comment by edenduong** [comment]
@dmytro-ch: I have covered this PR by MFTF test. Please check it. Thanks!

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6190](https://jira.corp.magento.com/browse/ENGCOM-6190) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
