### PR TITLE
[MFTF] add AssertStorefrontCustomerLogoutSuccessPageActionGroup

### LINKED ISSUE #29841: [Issue] [MFTF] add AssertStorefrontCustomerLogoutSuccessPageActionGroup
This issue is automatically created based on existing pull request: magento/magento2#29836: [MFTF] add AssertStorefrontCustomerLogoutSuccessPageActionGroup

---------
This PR add new Assert ActionGroup for asserting `CustomerLogoutSuccessPage`

### PR DESCRIPTION
**Pull request by Usik2203**
This PR add new Assert ActionGroup for asserting `CustomerLogoutSuccessPage`

### Resolved issues:
1. [x] resolves magento/magento2#29841: [MFTF] add AssertStorefrontCustomerLogoutSuccessPageActionGroup

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

Looks like we have flaky tests there, again:
image

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run  Functional Tests EE, Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8121](https://jira.corp.magento.com/browse/ENGCOM-8121) has been created to process this Pull Request

**Review by lbajsarowicz — APPROVED** [review]
✔️  Also 100% green from my side.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-8121](https://jira.corp.magento.com/browse/ENGCOM-8121) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Pull request merged**
