### PR TITLE
[FEATURE] [issue-3283] Added Filter Support for Yes/No (boolean) attr…

### PR DESCRIPTION
**Pull request by lewisvoncken**
…ibutes

### Description

Currently it is only possible to set an attribute to is_filterable to attributes with catalog input type Dropdown, Multiple Select and Price. But in some cases you want a Yes/No (boolean) attribute to be filterable.

### Fixed Issues (if relevant)

1. magento/magento2#3283: «Yes/No» attributes should be allowed in the Layered Navigation

### Manual testing scenarios

Before:
1. 
image

2. 
image

After:
1.
image
2.
image
3. After a reindex the attribute will be displayed as a filter!

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @lewisvoncken. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by lewisvoncken** [comment]
@magento-engcom-team 

the PR Quality Review has not been analysed

**Comment by lewisvoncken** [comment]
@magento-engcom-team 
Codacy coudn't run the analyses, let me know if this PR needs an update.

**Review by slavvka — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @slavvka, thank you for the review.
[ENGCOM-3097](https://jira.corp.magento.com/browse/ENGCOM-3097) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @lewisvoncken. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
