### PR TITLE
Fix the compatibility issue introduced by the change of catalog product view layout.

### PR DESCRIPTION
**Pull request by Hailong**
### Description (*)

Layout change of the Magento_Catalog::catalog_product_view.xml breaks legacy templates in which uses the $block->getProduct() function calls. Problem is the new introduced block class doesn't support this.

To avoid incompatibility problem. it's better to have the new class extends from the legacy class.

### Fixed Issues (if relevant)

1. magento/magento2#22036: $block->getProduct() in catalog product view template failed after upgrading from 2.3.0 to 2.3.1
### Manual testing scenarios (*)

1. Install Magento 2.3.0.
2. Install [Porto Theme](https://www.portotheme.com)
3. Product page is broken.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by rogyar** [comment]
Agree. The existing templates that invoke `getProduct()` of the block might be broken. 
Thank you!

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4605](https://jira.corp.magento.com/browse/ENGCOM-4605) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@Hailong thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @Hailong @rogyar I have a concern about the backward incompatibility of this backward compatibility fix. 

The backward incompatible difference between 2.3.1 and 2.3.2 version of the class is going to be 1 introduced a public method and more importantly 2 required constructor parameters.

**Comment by rogyar** [comment]
@sivaschenko. Agree. We need to choose between two evils here:
- Fix backward incompatible changes introduced in 2.3.1 (fix is fair in case of 2.3.0->2.3.1 upgrade)
- Leave backward incompatible changes introduced in 2.3.1 and don't introduce new potentially backward incompatible changes in 2.3.2.

After some consideration, I prefer the second option.

**Comment by sivaschenko** [comment]
Closing the pull request considering the discussion above. Feel free to contact me in case of any questions or comments

**Comment by Hailong** [comment]
Agree! Just for information of any others who are using Porto theme with Magento 2.3.1, Porto theme has published a newer version which has a fix for this problem.

**Comment by Seb33300** [comment]
@Hailong Where did you find the fixed version of Porto? I am encountering the same issue with the latest version 3.1.8 downloaded on themeforest

**Comment by Hailong** [comment]
@Seb33300 My theme was also 3.1.8 downloaded from ThemeForest. I just downloaded it again and checked it for you. The fixed file is in zip named `Patch for Magento 2.3.1 And Above.zip`, and its name is `details.phtml`

**Comment by Hailong** [comment]
@Seb33300 BTW, don't forget to unzip all the 'Patch...' zip files, and merge them into the theme. I don't like this either, but this is how Porto releases their new versions.

**Pull request closed without merging**
