### PR TITLE
Fix Enable Flat For API modes

### PR DESCRIPTION
**Pull request by dvynograd**
By default Flat tables is disabled for using in API (SOAP, REST) areas.
Which affects performance.
It happened because isAvailable set to false by default and enabled in frontend/di.xml

In that PR i decided to do opposite disable it for backend and enable by default for all others areas.

### CODE REVIEW

**Comment by dvynograd** [comment]
@maghamed your CR comments has been implemented.

**Comment by maghamed** [comment]
If you @dvynograd  would like to achieve this behavior:
>In that PR i decided to do opposite disable it for backend and enable by default for all others areas.

It's better to add your changes (enable  by default for all areas) to ./Catalog/etc/di.xml (general Di.xml file)
and overwrite (make disable) for adminhtml area only in Catalog/etc/adminhtml/di.xml

Because potentially some more areas could appear in future. And having this fix, behaviour would be preserved. Also you no need copy-paste

**Comment by dvynograd** [comment]
@maghamed ok, thanks, thats almost what i did in the previous commits, will rollback it back.

**Comment by dvynograd** [comment]
@maghamed your CR comments have been implemented

**Review by maghamed — COMMENTED** [review]
Please pay attention on broken Travis builds
https://travis-ci.org/magento/magento2/jobs/199954592

**Comment by dvynograd** [comment]
@maghamed 
This fix pointed to a new issue.

If you will take a look into failed integrations tests, you will find that it has relation to saving a category in a flat mode.

Magento\Catalog\Model\Indexer\FlatTest::testCreateCategory

This happens when phpunit tries to execute this line:

`$category->getResource()->save($categoryOne);`

Previously, before fix in this PR, setting catalog/frontend/flat_catalog_category into true wasn't enough for activating flat mode, since it worked only in front-end mode.

But after fix it finally stated testing what it suppose to do.

Why it isn't working:

Because resource model ( \Magento\Catalog\Model\ResourceModel\Category\Flat )  tries to save data directly in to flat table, since there no additional logic such as in \Magento\Catalog\Model\ResourceModel\Category::save.

I've also tried to use category repository to save 

`
$repository = self::$objectManager->get(\Magento\Catalog\Api\CategoryRepositoryInterface::class);
        $repository->save($categoryOne);
`

But also failed due to \Magento\Catalog\Model\ResourceModel\Category\Flat doesn't have validate method. which \Magento\Catalog\Model\ResourceModel\Category -> \Magento\Catalog\Model\ResourceModel\AbstractResource -> \Magento\Eav\Model\Entity\AbstractEntity::validate has 

I think we can't merge at least fix for categories, because api has method for saving categories.

catalogCategoryRepositoryV1 POST /V1/categories
"Magento\Catalog\Model\CategoryRepository::save

`$this->categoryResource->save($category);`

I think i have a lack of knowledge here, i don't know what suppose to do it with this issue, @maghamed could you contact me and explain it

**Comment by ishakhsuvarov** [comment]
Hi @dvynograd 
Unfortunately we can not accept this Pull Request at the moment. 
Currently all of the Magento Service Contracts are Command API (in [CQRS](https://martinfowler.com/bliki/CQRS.html) terms) thus it must work with raw data (EAV tables, etc.) instead of indexed (a.k.a. flat).

**Pull request closed without merging**
