### PR TITLE
ICO file not supported in media file uploader fixed, issue #23881

### PR DESCRIPTION
**Pull request by rajeshwebkul**
### Description (*)

When uploading ico file from media file uploader the error is received of "We don't recognize or support this file extension type"

### Fixed Issues (if relevant)

1. magento/magento2#23881: "Select from Gallery" option on media file uploader does not use correct allowable file types

### Manual testing scenarios (*)

Content -> Configuration
    Global -> Edit
        HTML Head -> Favicon icon
            Select from Gallery
            Choose Files
            Select "<anyfile>.ico" from local filesystem

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5816](https://jira.corp.magento.com/browse/ENGCOM-5816) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
Hi @sagarwebkul Warning message "Unsupported image format" is displayed when ico image is uploaded.
#24500PRWarning

**Manual testing scenario:**

- Go to Content -> Configuration
- Click Global -> Edit
- Choose HTML Head -> Favicon icon
- Click Select from Gallery -> Choose Files
- Select "<anyfile>.ico" from local filesystem

**Result:**
:x:  Warning message "Unsupported image format" is displayed

**Notice:** Ico image is succesfully uploaded and could be applied as Favicon Icon

Could you take a look?

**Comment by rajeshwebkul** [comment]
@engcom-Delta let me check this once again will update the PR.

**Comment by VladimirZaets** [comment]
@sagarwebkul what progress with it?

**Comment by sidolov** [comment]
@sagarwebkul  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
