### PR TITLE
Added "Add / update" comment. Update was missing.

### PR DESCRIPTION
**Pull request by gastondisacco**
Should have the same description as in CartItemRepositoryInterface.php.
Currently only says add, but the API works for add and update too.

### CODE REVIEW

**Comment by gastondisacco** [comment]
"Added "Add / update" comment. Update was missing." was the original title of the post, changed it to notice travis error.

**Comment by dverkade** [comment]
Hi,

I have head the same problem. The build is failling on calling a URL for fetching the exchange rates. I have rebased my commit a couple of times and finally it passed. You might want to try this as well.

**Comment by gastondisacco** [comment]
Hi @dverkade, thanks for your comment! Will try again so.

**Review by davidalger — APPROVED** [review]

**Comment by okorshenko** [comment]
@gastondisacco thank you for your contribution!
@davidalger thank you for processing this PR

**Pull request merged**
