### PR TITLE
fix qty calculation for the sold product reports

### PR DESCRIPTION
**Pull request by polkan-msk**
### Description (*)
without the "group by" I'm adding in this commit, report has the same
products several times. So to get proper total qty one need to manually
sum all the qtys for the product.

### Manual testing scenarios (*)

1. go to Reports > Products > Ordered
2. select dateFrom = 01/01/2018 and dateTo = 05/05/2019
3. select Show By = Year and Submit
4. make sure there are no duplicates in the table (each product exists in a single example and its qty summed)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22871) <br/>All committers have signed the CLA.

**Comment by swnsma** [comment]
HI @polkan-msk,
Thank you for your contribution.
As you PR provide functional changes, I need to clarify this question with Product Owner of Magento Reports. It could take some time.

**Comment by polkan-msk** [comment]
hi @swnsma 
yes, sure, but I believe it is a bug, though.
please see the screenshots:
before the fix: https://drive.google.com/open?id=1-ptjvG-2T8i8MXmvohVxNR6X9bPp-mhr
after the fix: https://drive.google.com/open?id=1w9GNxkvo-SWhOmNPiaPbnWONWoz-UVKq

**Comment by misha-kotov** [comment]
Hi @polkan-msk, does the problem happen with a specific product type only (simple, configurable, etc)?

**Comment by polkan-msk** [comment]
hi @misha-kotov. no, it happens for all types. the sql just does not have a 'group by' clause.

**Comment by misha-kotov** [comment]
@polkan-msk thanks for confirming. So in your example, how are the quantities 13, 12, 11, 6, and 3 grouped? Are those product quantities in individual orders?

**Comment by swnsma** [comment]
Hi @misha-kotov,
I have checked this case and can say that those items are grouped by individual orders.

**Comment by misha-kotov** [comment]
OK in that case I agree with the proposed fix.

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-5133](https://jira.corp.magento.com/browse/ENGCOM-5133) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @polkan-msk  , thanks for the pull request! However, this issue was fixed earlier in https://github.com/magento/magento2/pull/22646

I have to close this pull request as duplicate, but let's collaborate on delivering the earlier pull request with the best quality.

**Pull request closed without merging**
