### PR TITLE
Elasticsearch price fieldname is incorrect during indexing when storeId and websiteId do not match

### PR DESCRIPTION
**Pull request by alexander-aleman**
### Description (*)

The method getProductPriceData expects $websiteId as a parameter, but $storeId was given. It should be $websiteId since prices are website specific. Also see \Magento\Elasticsearch\Elasticsearch5\Model\Adapter\DataMapper\ProductDataMapper where a similar method exists and $websiteId is used. In cases where $websiteId and $storeId are different this causes the price filter to not work because ElasticSearch contains a field $fieldName = 'price_' . $customerGroupId . '_' . $storeId, but during filtering $fieldName = 'price_' . $customerGroupId . '_' . $websiteId is requested.

### Manual testing scenarios (*)

1. Create a website with 2 stores (i.e. there is a store with storeId which differs from websiteId)
2. Enable elasticsearch as search backend
3. Enable index on schedule
4. run bin/magento indexer:reindex
5. Make sure the price attribute is enabled as a filter
6. The price filter should now work for both stores after this change

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @alexander-aleman. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21216) <br/>All committers have signed the CLA.

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-4268](https://jira.corp.magento.com/browse/ENGCOM-4268) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@alexander-aleman thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request merged**
