### PR TITLE
fix paypal payflow mobile iframe redirection for new browsers

### LINKED ISSUE #29469: [Issue] fix paypal payflow mobile iframe redirection for new browsers
This issue is automatically created based on existing pull request: magento/magento2#24865: fix paypal payflow mobile iframe redirection for new browsers

---------

### Description (*)

One of our clients were having issue for paypal payflow payments on mobile being marked as cancelled lead to loss on sales, we found that browser prevents redirection for payflow from iframe on new safari browser due to sandbox attribute.
https://developer.apple.com/documentation/safari_release_notes/safari_13_release_notes
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#Attributes

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. Setup paypal payflow on magento
2. try checkout on Iphone 11 using payflow
3. after place order iframe will show blank, because payflow is trying redirect to using top.location

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by BestResponseMedia**
### Description (*)

One of our clients were having issue for paypal payflow payments on mobile being marked as cancelled lead to loss on sales, we found that browser prevents redirection for payflow from iframe on new safari browser due to sandbox attribute.
https://developer.apple.com/documentation/safari_release_notes/safari_13_release_notes
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#Attributes

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. Setup paypal payflow on magento
2. try checkout on Iphone 11 using payflow
3. after place order iframe will show blank, because payflow is trying redirect to using top.location

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29469: fix paypal payflow mobile iframe redirection for new browsers

### CODE REVIEW

**Review by sidolov — CHANGES_REQUESTED** [review]
Hi @BestResponseMedia  please, sign CLA, otherwise, we can't process your pull request

**Comment by BestResponseMedia** [comment]
I have signed CLA, but not appearing to pass @sidolov

**Comment by ihor-sviziev** [comment]
@magento create issue

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @BestResponseMedia,
Thank you so much for your contribution! Unfortunately it took so much time to get respond to you, we're really sorry for that. This issue looks to me really critical and we definitely need to fix it in case if it wasn't resolved yet.

Unfortunately in order to accept your contribution we need to have signed Adobe CLA. I see you above wrote that you already signed, but status still not signed. Could you go to the following link and follow instructions? https://github.com/magento/magento2/pull/24865/checks?check_run_id=970490369

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @BestResponseMedia please, sign CLA, otherwise, we can't process your pull request.

**Comment by VladimirZaets** [comment]
@BestResponseMedia , I am closing this PR now due to inactivity. Unforchantly, we can't merge this PR without signed CLA. 
Please reopen and update if you wish to continue.
Thank you for collaboration

**Review by mikew-westlund — COMMENTED** [review]
below is from the PayPal integration guide:

[https://developer.paypal.com/docs/payflow/integration-guide/configure-hosted-checkout/#mobile-optimized-checkout-pages](https://developer.paypal.com/docs/payflow/integration-guide/configure-hosted-checkout/#mobile-optimized-checkout-pages)

To support the mobile page in the latest browsers, you’ll need to add sandbox section to the iframe tag; as shown in the example below:

`<iframe id="payflow-link-iframe" sandbox="allow-top-navigation allow-scripts allow-same-origin allow-forms allow-modals" src="https://pilot-payflowlink.paypal.com/?SECURETOKEN=XXXXX&SECURETOKENID=XXXX"></iframe>`

**Comment by ihor-sviziev** [comment]
@mikew-westlund still this issue not fixed?

**Pull request closed without merging**
