### PR TITLE
#23297 : Deleting disabled category forces category flat and catalog search re-indexed fully

### PR DESCRIPTION
**Pull request by konarshankar07**
### Fixed Issues (if relevant)

1. magento/magento2#23297: Deleting disabled category forces category flat and catalog search re-indexed fully

### Manual testing scenarios (*)

1. Login in the Magento backend
2. Go to Catalog -> Category
3. Create New category
4. Select  Enable Category to NO
5. Save
6. Result : No indexer are invalids
7. Delete the Category
8. Result : No indexer are invalids

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @konarshankar07 thanks for the pull request! 

I have a question:
If the index does not need to be updated when the category save as not active, and it does not need to be updated when inactive category is deleted: why should it require reindex when an active category is deleted?

**Comment by konarshankar07** [comment]
Hello @sivaschenko 

We need to reindex the category when an active category is deleted because the flat table needs to update so the user will not able to see the category in the frontend

**Comment by sivaschenko** [comment]
@konarshankar07 I don't see the difference between those two scenarios:
1. Deleted active category.
2. Save active category as not active. Delete not active category.

I'd expect the equal reindexing behaviour in both such cases

**Comment by konarshankar07** [comment]
@sivaschenko 
So you are saying that if active category is deleted then we also don't need to reindex?

**Comment by sivaschenko** [comment]
@konarshankar07 I think that reindex should be triggered when changing the category to not active

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@konarshankar07 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by gulshankumar** [comment]
@sivaschenko I was facing a reindex required when deleting already inactive category. Why Magento requires to reindex in this case?

**Comment by sivaschenko** [comment]
@gulshankumar this is a known issue that this PR was targeting: https://github.com/magento/magento2/issues/23297 . As the pull request was closed, the issue is still actual

**Comment by konarshankar07** [comment]
Hello @sivaschenko and @gulshankumar 
Should I reopen this PR?

**Comment by sivaschenko** [comment]
Hi @konarshankar07 yes, you can reopen the PR, however, please pay attention to the comment https://github.com/magento/magento2/pull/23599#issuecomment-515746578

**Comment by sivaschenko** [comment]
@konarshankar07 would you like to continue progress on this pull request?

**Comment by konarshankar07** [comment]
Hello @sivaschenko,
Honestly, I'm still confused with when we need to reindex or not. Please check the following scenario.
1) If inactive category is saved then reindex should be triggered or not 
2)If inactive category is deleted then reindex should be triggered or not

As per my opinion, Reindex will not triggered in both the cases. Correct me if I'm wrong
Thanks

**Comment by sivaschenko** [comment]
@konarshankar07 considering the previous conversation in this PR, I think that:
 - If category is switched from active to inactive - reindex should be triggered
 - If inactive category is deleted - reindex should not be triggered

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,
I have already fixed the issue for reindexing deleted inactive category in the following commit
https://github.com/magento/magento2/pull/23599/commits/3d52a3b40a9e95c7e8b39b76373df8a39d0d3805. Can you please check and let me know if you are happy with it?
Thanks

**Comment by sivaschenko** [comment]
Hey @konarshankar07 thanks for the response. Is reindex currently triggered when a category is switched from active to inactive?

**Comment by konarshankar07** [comment]
Yes @sivaschenko. Updates are in https://github.com/magento/magento2/pull/23599/commits/0d4d04bf64379c24fbe6d1d533a0d0853cff25fe commit

**Comment by sivaschenko** [comment]
@konarshankar07 it appears that reindex is triggered every time the category is saved (even if it hasn't became inactive) based on the mentioned commit

**Comment by konarshankar07** [comment]
Yes @sivaschenko correct. I have added the changes in https://github.com/magento/magento2/pull/23599/commits/3d52a3b40a9e95c7e8b39b76373df8a39d0d3805 and after you mentioned that we need to focus on original issue i.e reindexing deleted inactive category so that's why I have removed those changes in https://github.com/magento/magento2/commit/0d4d04bf64379c24fbe6d1d533a0d0853cff25fe.

**Comment by sivaschenko** [comment]
@konarshankar07 sorry for confusion, please trigger reindex when a category is switched from active to inactive (recently active category is saved as inactive).

**Pull request closed without merging**
