### PR TITLE
Remove recursion in location of static files.

### LINKED ISSUE #31530: [Issue] Remove recursion in location of static files.
This issue is automatically created based on existing pull request: magento/magento2#30883: Remove recursion in location of static files.

---------
### Description (*)
Magento 2.4-develop
The default NGINX config contains a possible bug in location `static`, that leads to infinite recursion.
This PR remove it.

### Manual testing scenarios (*)
1. Enable [Static content signing](https://devdocs.magento.com/guides/v2.4/config-guide/cache/static-content-signing.html#static-content-signing).
2. Try to open URL like [MAGE_URL]/static/version-example

**Expected**: 404 page
**Actual**: 500 error

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by edspc**
### Description (*)
The default NGINX config contains a possible bug in location `static`, that leads to infinite recursion.
This PR remove it.

### Manual testing scenarios (*)
1. Enable [Static content signing](https://devdocs.magento.com/guides/v2.4/config-guide/cache/static-content-signing.html#static-content-signing).
2. Try to open URL like [MAGE_URL]/static/version-example

**Expected**: 404 page
**Actual**: 500 error

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31530: Remove recursion in location of static files.

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Comment by gabrieldagama** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8632](https://jira.corp.magento.com/browse/ENGCOM-8632) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by engcom-Delta — CHANGES_REQUESTED** [review]
Hi @edspc  I am not able to reproduce issue described by PR on 2.4-develop
**Manual testing scenario:**

- Install nginx
image

- Install magento
- Try to open URL like [MAGE_URL]/static/version-example/, in my case - `http://magento2dev.loc/static/version1611070641/`

**Result:**
:heavy_check_mark: Page `404 error: Page not found.` is shown
image

**Note:** If try to open URL like `[MAGE_URL]/static/version-example` without ending slash,  500 error is shown
image

Same behavior is with PR changes

Could take a look and correct me if I am wrong?

**Comment by edspc** [comment]
Hi @engcom-Delta.

The context of the original location block is designed for URL starts with `/static/version` then **digits** with ending slash.  It's like your's 1st try. By the way declaration of this block allows nginx to process URL that starts with `/static/version` and **no matter** what is going after (example `/static/version`, `/static/version-123/`, etc). But there is logic only for numeric version inside that block, so in another case – 500.

So the second try is proper for testing this case.

> Same behavior is with PR changes

Let me clarify, did you restart nginx after updating the file?

No changes:
no changes

With changes from PR:
with changes from pr

**Comment by ihor-sviziev** [comment]
@magento give me 2.4-develop instance

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests, Static Tests

**Comment by engcom-Delta** [comment]
@edspc thanks for clarification. Restart nginx after updating the file was required.
@ihor-sviziev Could you approve PR to move it into Ready for Testing column?

**Comment by ihor-sviziev** [comment]
Moved.

Note: on apache env. this issue not reproducing (on test instanced apache is used)

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Result:**
**Before:**
:x: Page `500 Internal Server Error` is shown when url `[MAGE_URL]/static/version-example` is opened
image


**After:**
Page `404 error: Page not found.` is shown when url `[MAGE_URL]/static/version-example` is opened
image
image

**Comment by engcom-Delta** [comment]
**Note:** Functional Tests CE and Functional Tests EE are failed

**Comment by ihor-sviziev** [comment]
@engcom-Delta, now tests are passing. Can we move it to the "accept" column?

**Comment by engcom-Delta** [comment]
**Note:** No needs any update: PR was added to regression scope

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Pull request merged**
