### PR TITLE
Solve #21504:Attribute text field takes blank values

### PR DESCRIPTION
**Pull request by mageprince**
### Description (*)

Attribute text field takes the blank value on `create new value` in `Create Product Configurations` popup
### Fixed Issues (if relevant)

https://github.com/magento/magento2/issues/21504

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mageprince. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4401](https://jira.corp.magento.com/browse/ENGCOM-4401) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
Hi @mageprince . Those PR changes fix issue only for default attribute "color". But we still have such kind of issue with Dropdown, Text Swatch and Visual Swatch

**Comment by mageprince** [comment]
@VasylShvorak This issue and solution created only for creating blank attribute from **Admin->Configurable Product -> Create Configurations ->Create new Value**

We will create new issue(For make clear description of this issue and PR) for the creating blank attribute from Admin->Stores->Attributes->Product->Add new attribute->Manage Options (Values of Your Attribute)

**Comment by mageprince** [comment]
@VasylShvorak @sidolov any update on this PR ?

**Comment by VladimirZaets** [comment]
Hi @mageprince. I think the fix will be the same and we should fix that case in the scope of this PR.

**Comment by VladimirZaets** [comment]
@mageprince, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Pull request closed without merging**
