### PR TITLE
Magento Connect no longer exist

### PR DESCRIPTION
**Pull request by miguelbalparda**
### Fixed Issues (if relevant)

1. magento/magento2#12632

### Manual testing scenarios

1. Login to the admin
2. Go to Find partners & extensions
3. Link and image points to Magento Connect

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by osrecio** [comment]
Thanks @miguelbalparda for your contribution, I'll process this right away!

**Comment by miguelbalparda** [comment]
Just changed CSS class name too.

**Comment by osrecio** [comment]
Thanks @miguelbalparda ! Merging in progress

**Comment by osrecio** [comment]
@miguelbalparda Can you add Backport for 2.3 branch ? Thanks!

**Comment by miguelbalparda** [comment]
Will do!

**Pull request merged**
