### PR TITLE
MAGETWO-96618: JS files relocation BC in 2.3 too

### PR DESCRIPTION
**Pull request by rbayet**
### Description (*)

Introduce the 'old_path: new_path' path mappings for JS files relocated in the context of #16302.
Those BC mappings are present in the 2.2.x line but were not added for the 2.3.x line which would impact any third party module/extension/theme relying on the old paths.

### Fixed Issues (if relevant)

1. magento/magento2#19291: JS files relocation inside the web/js directory not BC in 2.3.x

### Manual testing scenarios (*)

1. Create new Product in Backend with gift message ~/ gift wrapping~ and returns (EE only) allowed
2. (optional) Activate Authorizenet and Paypal payment methods
2. Checkout Product in Frontend
3. Register Account, test Captcha is working
4. Log out, go to Forgot Password, test Captcha is working
5. ~Log in, test Captcha is working~
6. (optional) Checkout and place order with gift message, w/ Authorizenet  payment method
7. (optional) Checkout and place order with gift message, w/ Paypal payment method
8. Checkout and place order with gift message, w/ Checkmo payment method
9. Go to customer account, test Change Email
10. In customer account, test Change Password
11. In customer account, test adding and deleting addresses
12. In customer account, check previous order(s) gift message  
13. (EE only) In backend, process order(s) to be able to return it/them
14. (EE only) In customer account, create a return for an order, check the "return" tab is visible on the order view
15. Create new Downloadable product in Backend with several priced links
16. Test downloadable product PDP in Frontend : selecting/deselecting links must change price
17. Test Send-a-friend in Frontend
18. Test autocomplete search box
19. Enable and configure Wee/FPT in backend, add it to a product and test it in frontend

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19583) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @rbayet. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rbayet** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rbayet. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rbayet, here is your [new Magento instance](https://pr-19583.instances.magento-community.engineering).
Admin access: [https://pr-19583.instances.magento-community.engineering/admin](https://pr-19583.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3624](https://jira.corp.magento.com/browse/ENGCOM-3624) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@rbayet thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by rbayet** [comment]
Manual testing scenarios OK for me except 

- test 7 : Placing order w/ Authorizenet (not possible on the test instance)
- test 8 : Placing order w/ Paypal (not possible on the test instance)
- tests 14 and 15 : not possible to tests returns on the CE / Open source rest instance

**Comment by rbayet** [comment]
Hi @orlangur,

Is force pushing ok to fix some of the travis errors reported ?

Regards

**Comment by rbayet** [comment]
I don't know what to make of the Travis CI failure.

It seems to be related to a lot of `Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL. (1)` errors, even for files not even remotely affected by the PR (Magento\Ui for instance)...

Initial Travis CI failure was clear cut: just a missing new line at the end of a new file.

**Edit :** re-launched the build, it passed.

**Comment by magento-engcom-team** [comment]
Hi @rbayet. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
