### PR TITLE
34866: Save address data from shopping cart page

### LINKED ISSUE #34866: Cart Price Rule with shipping method set as condition is not working Magento 2.4.1
### Preconditions (*)

1. Magento 2.4.1
2. just plain , default magento setup

### Steps to reproduce (*)

1. Create a cart price rule (as mentioned in video/ below setp)
Admin - Marketing - Cart Price Rules - Add new Rule
- Set coupon basic information and select Specific Coupon, Enter Coupon code
- Go to condition and set : If ALL  of these conditions are TRUE : Shipping Method  is  [flatrate] Fixed
- In action set apply as Percent of product price discount
- Apply to shipping amount as yes
- In "Apply the rule only to cart items matching the following conditions (leave blank for all items)" section,  set "Free Shipping" drop down as For shipment with matching items
- Front end Login using customer. 
Note: Default shipping method should be Flat rate - Fixed.
Add a product to cart and apply coupon in Shopping Cart page - Issue. "Coupon is Not valid" error message is displayed
Apply discount in checkout page - No issue. Coupon applied
https://user-images.githubusercontent.com/85919383/147129168-31e44dee-46eb-40b1-aec9-23288584734e.mp4

2.

### Expected result (*)

1. When we apply created coupon after selecting Flat Rate as shipping method, the coupon should applied successfully 
2.

### Actual result (*)

1. Even after selecting the flat rate as shipping method when we try to apply that coupon its giving invalid coupon error.
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.
[[S1]]()
- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ S1] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._
screenshot-127 0 0 1-2021 12 22-22_37_57
screenshot-127 0 0 1-2021 12 22-22_37_20

### PR DESCRIPTION
**Pull request by mmezhensky**
### Description (*)
This PR fixed issue with Cart Price Rule and shipping method set as condition.
This problem is caused by the fact that the shipping address does not contain information about the shipping method when validating the coupon code. This is because Magento does not save this on the shopping cart page.
I added saving shipping information for this. 

### Fixed Issues (if relevant)

1. Fixes magento/magento2#34866

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mmezhensky** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by mahesh-singh-rajawat** [comment]
@mmezhensky Thank you fixing this issue.

It will be taken care into one of the Internal [JIRA ticket](https://jira.corp.adobe.com/browse/AC-2044). Once Internal PR will get merged, we will notify.

Thank you!

**Comment by rimple-saini** [comment]
@mmezhensky As I can see this issue got fixed in the scope of the internal Jira ticket [JIRA ticket - AC-2044](https://jira.corp.adobe.com/browse/AC-2044). by the internal team
Related commits: https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-2044&type=commits

Based on the Jira ticket, the target version is 2.4.7-beta2.

Thanks

**Comment by engcom-Charlie** [comment]
As per [above](https://github.com/magento/magento2/pull/35032#issuecomment-1704869031) comment, closing this PR now.

Thank you!

**Pull request closed without merging**
