### PR TITLE
Fix #20111 - display variables in popup while editing existing email template

### LINKED ISSUE #20111: Email Template Information Insert Variable popup blank
### Preconditions (*)

1. 2.3.0
2.

### Steps to reproduce (*)

1. Go to admin>>MARKETING>>Email Templates>> edit the template
2.

### Expected result (*)

1. 
image

2.

### Actual result (*)

1. 
image

2.

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

In this PR I tried to fix #20111 after it was probably abandoned.

### Fixed Issues (if relevant)

1. magento/magento2#20111: Email Template Information Insert Variable popup blank

### Manual testing scenarios (*)

1. Go to admin >> MARKETING >> Email Templates
2. Edit existing template
3. Check **Insert variable** popup if it contains variables

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4812](https://jira.corp.magento.com/browse/ENGCOM-4812) has been created to process this Pull Request

**Comment by soleksii** [comment]
Hi @Bartlomiejsz ! 

**Your fix provides next problem:** Fatal Error message after insert variable to template

**Steps to reproduce:**

1. Login to Admin;
2. Go to Marketing->Communications->Email Templates;
3. Click on "Add New Template" button;
4. Select "New Account" template from the list for example;
5. Click on "Load Template" button;
6. Fill all required fields;
7. Click on "Save Template" button;
8. Click on created before template for edit;
9. Click on "Insert Variable..." button;
10. Select any link from the list for example;
11. Click on "Save Template" button;
12. Click on "Preview" link in the template grid

**Actual result:** We've got fatal error message

after

**Comment by Bartlomiejsz** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Bartlomiejsz. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Bartlomiejsz, here is your [Magento instance](https://i-22469-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22469-2-3-develop.instances.magento-community.engineering/admin](https://i-22469-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Bartlomiejsz** [comment]
@magento-engcom-team give me test instanc

**Comment by Bartlomiejsz** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Bartlomiejsz. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Bartlomiejsz, here is your [new Magento instance](https://pr-22469.instances.magento-community.engineering).
Admin access: [https://pr-22469.instances.magento-community.engineering/admin](https://pr-22469.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by Bartlomiejsz** [comment]
@stoleksiy this error is not caused by those changes. You can see exactly same error when you follow those steps on 2.3-develop instance:
1. Login to Admin;
2. Go to Marketing->Communications->Email Templates;
3. Click on "Add New Template" button;
4. Select "New Account" template from the list for example;
5. Click on "Load Template" button;
6. Fill all required fields;
6. Move cursor to the beginning of template (before header path being loaded)
7. Click on "Insert Variable..." button;
8. Select any link from the list for example;
9. Click on "Save Template" button;
10. Click on "Preview" link in the template grid

This is because as result you have incorrect html being saved (variable is injected before **<!DOCTYPE** and this have nothing to do with changes from PR. This even have nothing to do with injecting variables because customer can write any dummy text before header in template and result will be the same I believe.

**Comment by soleksii** [comment]
@Bartlomiejsz Thanks for the clarification!

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed 

**Before:**

before

**After:**

after

**Comment by roma84** [comment]
After this fix, template variables are missing when creating a new template: https://prnt.sc/nxj254
So, this fix reverts the issue.

**Pull request merged**
