### PR TITLE
Replace repetitive actions with Action Groups in StorefrontProductNameWithHTMLEntitiesTest

### LINKED ISSUE #33806: [Issue] Replace repetitive actions with Action Groups in StorefrontProductNameWithHTMLEntitiesTest
This issue is automatically created based on existing pull request: magento/magento2#33214: Replace repetitive actions with Action Groups in StorefrontProductNameWithHTMLEntitiesTest

---------

### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run the test in the local environment and verified that it run successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run the test in the local environment and verified that it run successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#33806: Replace repetitive actions with Action Groups in StorefrontProductNameWithHTMLEntitiesTest

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by shikhamis11** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento create issue

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-9183](https://jira.corp.magento.com/browse/ENGCOM-9183) has been created to process this Pull Request
:eight_spoked_asterisk: @eduard13, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by shikhamis11 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11, thank you for the review.
[ENGCOM-9183](https://jira.corp.magento.com/browse/ENGCOM-9183) has been created to process this Pull Request

**Comment by engcom-Charlie** [comment]
✔️ QA Passed

The provided MFTF test case is working fine and green in build. Please find the Allure report for the same.

image

image

**Pull request merged**
