### PR TITLE
Fix unit tests - Revert "AC-8030::Sync 2.4.6-develop with 2.4-develop"

### LINKED ISSUE #37289: [Issue] Fix unit tests - Revert "AC-8030::Sync 2.4.6-develop with 2.4-develop"
This issue is automatically created based on existing pull request: magento/magento2#37287: Fix unit tests - Revert "AC-8030::Sync 2.4.6-develop with 2.4-develop"

---------
### Description
Following the introduction of bfef50e4deeafe3847c07fb7ac5141c02aad50a0 (which does not seem to be associated with any pull request), unit tests have been consistently failing. This pull request reverts the faulty commit.

The commit message suggests that this is a back-port from `2.4.6`, however that version does not suffer from this bug / include that change: https://github.com/magento/magento2/blame/2.4.6/app/code/Magento/Reports/Test/Unit/Model/ResourceModel/Order/CollectionTest.php#L465

### Manual testing scenarios
1. Automated unit tests should pass.

### Questions or comments
I do not understand why this commit was added to the repository. Perhaps @glo71317 can provide some context / explanation.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fredden**
### Description
Following the introduction of bfef50e4deeafe3847c07fb7ac5141c02aad50a0 (which does not seem to be associated with any pull request), unit tests have been consistently failing. This pull request reverts the faulty commit.

The commit message suggests that this is a back-port from `2.4.6`, however that version does not suffer from this bug / include that change: https://github.com/magento/magento2/blame/2.4.6/app/code/Magento/Reports/Test/Unit/Model/ResourceModel/Order/CollectionTest.php#L465

### Manual testing scenarios
1. Automated unit tests should pass.

### Questions or comments
I do not understand why this commit was added to the repository. Perhaps @glo71317 can provide some context / explanation.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37289: Fix unit tests - Revert "AC-8030::Sync 2.4.6-develop with 2.4-develop"

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by fredden** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by fredden** [comment]
@sidolov please can you mark this as slightly more important? This test failure is causing the Adobe engineering team to do a lot more work than otherwise would be required. It's also costing Adobe more machine power to keep running the unit tests on unrelated pull requests which are failing due to this bug introduced by @glo71317 without explanation.

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B , Functional Tests CE, Functional Tests EE

**Comment by glo71317** [comment]
> @sidolov please can you mark this as slightly more important? This test failure is causing the Adobe engineering team to do a lot more work than otherwise would be required. It's also costing Adobe more machine power to keep running the unit tests on unrelated pull requests which are failing due to this bug introduced by @glo71317 without explanation.

@fredden Sorry for inconvenience!!! Yes i agreed this issue is introduced with my changes. 
**Just for Info:** This test was continuously failing in my Sync PR, So, I adjusted the test and it got passed. later i analysed and found it should not required that was failing due to time zone. I have already raised one PR which is #queue 5, So, waiting for queue to merge.
Today i will check with team to get merge on priority.

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE

**Comment by engcom-Lima** [comment]
@magento run Functional Tests CE

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
it seem like the issue got fixed in https://github.com/magento/magento2/commit/1ca2d9da13f5f7a1e15cf1e6ffc208a6c0920678. I think we should close this Pull Reqeuest

**Comment by engcom-Lima** [comment]
As issue has been fixed in the [commit](https://github.com/magento/magento2/commit/1ca2d9da13f5f7a1e15cf1e6ffc208a6c0920678) .Hence, closing this PR.

**Comment by ihor-sviziev** [comment]
@fredden, I think we can ping @glo71317 for further discussions of the fix that was implemented

**Pull request closed without merging**
