### PR TITLE
Issue 35667: Admin reset password link broken

### LINKED ISSUE #35667: Admin reset password link broken
### Preconditions and environment

- Magento 2.4.4
- Multiple websites and stores

### Steps to reproduce

1. Enable settings Add Store Code to Urls
2. Create 2 new website with each 1 store view
3. Create new admin user
5. Click `Forgot your password?` link in the admin login page;
6. Input your e-mail and submit;
7. Click the link in the email.

### Expected result

Form to reset the password

### Actual result

404 not found

### Additional information

Link is generated as `http://magento.local/admin/admin_123456/admin/auth/resetpassword/key/xxxxxxxxxx/?id=1&token=yyyyyyyy`, but it should be `http://magento.local/admin_123456/admin/auth/resetpassword/key/xxxxxxxxxx/?id=1&token=yyyyyyyy` (notice the extra `admin/` right after the domain name).

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rogerdz**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#35667

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by bgorski** [comment]
@magento run Functional Tests B2B

**Comment by bgorski** [comment]
@magento run Functional Tests B2B

**Comment by bgorski** [comment]
@magento run Functional Tests B2B

**Comment by bgorski** [comment]
After some in-depth code analysis I decided to close this PR. Changes here are too broad (a modification of \Magento\Backend\Model\Url class marked with `@api`) for the scope of the issue. The class is used in too many places in the code and modification like that can have unforeseen consequences. 
But still, thank you for your contribution! It's still greatly appreciated even if not everything gets merged.

**Pull request closed without merging**
