### PR TITLE
[Eav Performance] #164 - Use eav cache for the method getAttribute

### PR DESCRIPTION
**Pull request by PierreLeMaguer**
### Fixed Issues (if relevant)

[magento/community-features#183: Improve the performance of the method app/code/Magento/Eav/Model/Config.php::getAttribute](https://github.com/magento/community-features/issues/183)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23906) <br/>All committers have signed the CLA.

**Comment by sidolov** [comment]
Hi @PierreLeMaguer looks like you made some commits with an email different than in your GitHub profile, please, add email from commits to your profile!
Thank you!

**Comment by sidolov** [comment]
@PierreLeMaguer , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by romainruaud** [comment]
I'm reopening this PR (sorry if I'm exceeding my rights on this repository).

@sidolov @kandy can you give us clear directives about what needs to be changed / remain to be done ?

regards

**Review by sidolov — CHANGES_REQUESTED** [review]
@romainruaud , you made a commit with an email that is not connected to your GitHub account. To resolve this issue just add email from the commit to your GitHub account.

**Comment by romainruaud** [comment]
@sidolov I'm not the commiter, it's my colleague :)

But everything should be ok regarding his email now (he registered his both email into his Github account).

Can you give us the next steps ?

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5829](https://jira.corp.magento.com/browse/ENGCOM-5829) has been created to process this Pull Request

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
Hello, @PierreLeMaguer. Unfortunately, your PR causes a massive number of test failures. Please rework your solution.

**Comment by sidolov** [comment]
@PierreLeMaguer  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
