### PR TITLE
PUT, DELETE methods support added.

### PR DESCRIPTION
**Pull request by milindsingh**
### Description (*)

PUT, DELETE methods support added in ` \Magento\Framework\HTTP\Client\Curl` class.
Same as the feature-request https://github.com/magento/community-features/issues/101

### Fixed Issues (if relevant)

As by the coding standards it is preferred to use the `Curl` class instead of php curl lib directly, 
but the lib `Curl` class does not supports `PUT, DELETE` methods.
`phpcs: MEQP1.Security.DiscouragedFunction.Found: The use of function curl_init() is discouraged`

### Manual testing scenarios (*)

1. Use curl via Client Curl class

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @milindsingh. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
Hi @milindsingh , thanks for your contribution. Can you please cover the new added functionality with tests.

**Comment by milindsingh** [comment]
@sivaschenko Yes, sure

**Comment by milindsingh** [comment]
@sivaschenko Can you guide me where I can add the tests?

**Comment by sivaschenko** [comment]
Unit tests can be created in `/Users/sivashch/Projects/magento2/lib/internal/Magento/Framework/HTTP/Test/Unit`, the test class should correspond to changed class: `Magento\Framework\HTTP\Test\Unit\Client\CurlTest`.

Integration tests can be added under`dev/tests/integration/testsuite/Magento/Framework/HTTP`, recommended classname `Magento\Framework\HTTP\Client\CurlTest`

**Comment by milindsingh** [comment]
I am working on Unit Tests for now.

**Comment by sidolov** [comment]
Hi @milindsingh , are you still working on this PR?

**Comment by milindsingh** [comment]
@sidolov yes.
You can close the PR if needed, I'll reopen once I finish

**Comment by sidolov** [comment]
Hi @milindsingh , thank you for the fast response! 
Feel free to reopen pull request when you finish!

**Comment by milindsingh** [comment]
@sivaschenko I have added the unit test cases. I didn't find integration tests for curl anywhere in Magento, hence skipped.

**Comment by sivaschenko** [comment]
Hi @milindsingh , thank you for the tests! 

It would be good if you add a bit more assertions to the unit test as currently it does not seem to test the differences between call. I'd suggest to update the mock callback to pass the request-specific options to the response, so that they can be verified.

**Comment by milindsingh** [comment]
Hi @ssivaschenko, Thanks for the review.
Can you please guide me with creating unit tests?

The following line in [Curl.php](https://github.com/magento/magento2/blob/6daf159812f7cb89c8b11186f124b7f901d0a868/lib/internal/Magento/Framework/HTTP/Client/Curl.php) create a `callback` inside the `curl resource` which doesn't trigger while unit testing, testing the the function `parseHeaders` seems very difficult.
```
$this->curlOption(CURLOPT_HEADERFUNCTION, [$this, 'parseHeaders']);
```
What is best way to unit test `curl` clients (as we cannot call the actual callback set in curl resource)?

**Comment by sivaschenko** [comment]
Hi @milindsingh ,

I see two possible approaches:

The first approach the best from my point of view, however, it requires a bit more time. It considers refactoring of `\Magento\Framework\HTTP\Client\Curl` and moving direct interaction with curl native functions to a separate class. This approach also described here: https://stackoverflow.com/questions/7911535/how-to-unit-test-curl-call-in-php

The second approach considers fewer changes,however, it allows to test only the fact that URL was set to curl resource correctly. Here I propose to change the `curl_exec` mock to return `curl_getinfo($resource)` so that the url can be verified in the test after the call by `$this->assertArraySubset(['url' => $url], $this->model->getBody());`.

Both approaches include getting rid of unnecessary from my point of view `\Magento\Framework\HTTP\Test\Unit\Client\CurlTest::$curlExectClosure` and both `txt` files.

Let me know what you think.

**Comment by sivaschenko** [comment]
Closing this pull request due to inactivity, feel free to reopen if you'd like to continue progress

**Pull request closed without merging**
