### PR TITLE
[MFTF] Added new actionGroup to click on first row on order grid

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)
Added `AdminClickFirstRowOrderGridActionGroup`  for clicking on first row on order grid

### CODE REVIEW

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7293](https://jira.corp.magento.com/browse/ENGCOM-7293) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by elevinskii** [comment]
That's good changes are giving us opportunity to write only 1 line of XML code instead 2 ones, making our code more understandable and readable - it's out of doubts.

But I'd suggest to go a bit more further - as our admin grids are very similar (more or less), we could put new action group inside `Ui` module and use it without any relation to particular page (but then `AdminOrdersGridSection.firstRow` should be replaced by `AdminDataGridTableSection.firstRow`, probably).

@Usik2203 
Let me know, if you need more details. Thanks!

**Comment by lbajsarowicz** [comment]
I know that's minor issue, but would you be able to change it to `AdminOrderGridClickFirstRowActionGroup`? I find it easier to find the Action Groups related to some area entering in PHPStorm `Admin` + area + do something and not always it's showing the right entries : ) 

Imagine that when you enter `AdminOrderGrid` you have all actions related one by another.

**Review by lbajsarowicz — APPROVED** [review]
:heavy_check_mark:  Awesome, thank you

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7293](https://jira.corp.magento.com/browse/ENGCOM-7293) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Pull request merged**
