### PR TITLE
Cart Rule discount for Subtotal

### LINKED ISSUE #36760: "Subtotal (Excl. Tax)" condition for Cart rule is not working for FREE Shipping
### Preconditions and environment
 - Magento version `2.4.3-p2`
 - Enable Tablerate shipping

### Steps to reproduce

**Backend**
1. Create a cart rule with following

 - {{{}Conditions{}}}: `Subtotal (Excl. Tax)` is equals or greater than `100`
 - {{{}Actions{}}}: `Free Shipping` = `For matching items only`

1. Create another cart rule with coupon `XYZ` to give a `Fixed amount discount for whole cart` of `10`

**Storefront**
1. Add items to the cart to make a subtotal of 105
1. Apply the coupon `XYZ` to get 10$ OFF

### Expected result

The shipping fee should not be 0 (i.e. FREE shipping cart rule should not be applied)
### Actual result

The shipping fee is showing 0 (i.e. FREE shipping cart rule is applied)
### Additional information

!https://user-images.githubusercontent.com/1205071/213676297-f3145d58-e179-47fb-aebc-19d5edb4e47a.png|width=593,height=348!

**Quick n Dirty Solution**

Step debugging showed that the value provided by the `$address->getData('base*subtotal_with*discount')` is not correct:
!https://user-images.githubusercontent.com/1205071/213677260-afb0ac81-6fd1-450a-a945-3212f479f63c.png|width=509,height=152!

So ended up tweaking as below:

`\Magento\OfflineShipping\Model\SalesRule\Calculator::processFreeShipping()`
``{{
public function processFreeShipping(\Magento\Quote\Model\Quote\Item\AbstractItem $item)
{
$address = $item->getAddress();

$item->setFreeShipping(false);

foreach ($this->_getRules($address) as $rule) {

/* Quick Fix - Start */
$address->setBaseSubtotalWithDiscount($address->getBaseSubtotal() + $address->getBaseDiscountAmount());
/* Quick Fix - End */

/* @var $rule \Magento\SalesRule\Model\Rule */
if (!$this->validatorUtility->canProcessRule($rule, $address))

{ continue; }

}}``
### Release note

*No response*
### Triage and priority
 - < ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
 - [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
 - [ ] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
 - [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
 - [ > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

### PR DESCRIPTION
**Pull request by Vasudev-22**
### Description (*)

1. Discount amount for subtotal is added successfully in quote and quote address table
2. Has an issue in reset function for shipping discount and discount applies ,
3. Modified in reset function 
 ```
$address->setBaseSubtotalWithDiscount($address->getBaseSubtotalWithDiscount());
$address->setSubtotalWithDiscount($address->getSubtotalWithDiscount());
```

### Related Pull Requests

https://github.com/magento/magento2/issues/36760
### Fixed Issues (if relevant)

1. Fixes magento/magento2#36760

### Manual testing scenarios (*)

1. **Backend**
      Create a cart rule with following
     _Conditions_: Subtotal (Excl. Tax) is equals or greater than 100
     _Actions_: Free Shipping = For matching items only
      Create another cart rule with coupon XYZ to give a Fixed amount discount for whole cart of 10
  **Storefront**
      Add items to the cart to make a subtotal of 105
     Apply the coupon XYZ to get 10$ OFF
 **Expected result**
     The shipping fee should not be 0 (i.e. FREE shipping cart rule should not be applied)

image

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Vasudev-22** [comment]
@magento run all tests

**Comment by Vasudev-22** [comment]
@magento run unit tests

**Comment by Vasudev-22** [comment]
@magento run Integration Tests

**Comment by Vasudev-22** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by Vasudev-22** [comment]
@magento run Functional Tests EE, Integration Tests

**Comment by mahesh-singh-rajawat** [comment]
@Vasudev-22 Thank you for working on this.
It will be taken care into one of the internal [JIRA Ticket](https://jira.corp.adobe.com/browse/AC-7886). Once internal PR get merged, we will notify.

Thank you!

**Comment by engcom-Hotel** [comment]
Hello @Vasudev-22,

Thanks for the contribution!

As the issue is fixed internally, we are closing this PR. Please refer to the below link for related commits:

https://github.com/magento/magento2/issues/36760#issuecomment-1513254893

Thanks

**Pull request closed without merging**
