### PR TITLE
Updated subscriber spelling

### LINKED ISSUE #36163: typo error on a js file.
### Summary (*)

On Magento 2.3.5 there is a typo error right here:
vendor/magento/module-catalog/view/frontend/web/js/product/storage/storage-service.js
line 120:
 /**
             * Subscribers list
             */
            subsctibers = {};
this object  subsctibers = {}; is used in further parts of this js with that same name, which is a typo.

### Examples (*)

line 191
processSubscribers: function (initialized, config) {
                if (subsctibers[config.namespace]) {
                    _.each(subsctibers[config.namespace], function (callback) {
                        callback(initialized);
                    });

                    delete subsctibers[config.namespace];
                }
            },

### Proposed solution

It should be replaced by subscribers
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by sandy6666**
Updated Subscriber spelling

### Fixed Issues (if relevant)
1. Fixes magento/magento2#36163

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sandy6666** [comment]
@magento run all tests

**Comment by sandy6666** [comment]
@magento run Functional Tests CE

**Comment by sandy6666** [comment]
@magento run all tests

**Review by edenduong — APPROVED** [review]
Thank you for your contribution !

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by engcom-Charlie** [comment]
The Functional B2B failures are seems to be flaky and not part of this PR. All are known failures.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36171/2cdb999054ae67a09e46bbd02fc44c7a/Functional/allure-report-b2b/index.html
image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36171/2abb1103b7db303ac1092d763aedce61/Functional/allure-report-b2b/index.html#categories
image

Known issue:
1. [ACQE-6350](https://jira.corp.adobe.com/browse/ACQE-6350)- AdminCreateDraftQuoteFromQuoteGridPageWithMultipleStoresTest
2. [ACQE-6523](https://jira.corp.adobe.com/browse/ACQE-6523)- AdminReorderWithCatalogPriceRuleDiscountTest
3. [ACQE-6648](https://jira.corp.adobe.com/browse/ACQE-6648)- StorefrontUpdateCustomerAddressBelgiumTestCest

**Comment by engcom-Charlie** [comment]
The Functional EE failures seems to be flaky and having known issues.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36171/7c46c470c41b57fa4fa4433dd8925042/Functional/allure-report-ee/index.html#categories/2afd3b34d66263d23832312f8fed37f1/fa65c3178c3dd199/
image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36171/d017d08824933752be29edb9ba03b5c9/Functional/allure-report-ee/index.html#categories
image



1. [ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331)- StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTestCest
2. [ACQE-6523](https://jira.corp.adobe.com/browse/ACQE-6523)- AdminReorderWithCatalogPriceRuleDiscountTest

**Comment by engcom-Charlie** [comment]
The WebAPI test failures seems to be flaky and having known issues. Hence moving the PR to Merge in Progress.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36171/fa7a68e0bceb06d13aaf72db0ea705a4/WebApi/console-error-logs.html
image

image

image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36171/bc6cbb144010137fffb548450cc15b2b/WebApi/console-error-logs.html
image

Known issue:
1. [ACP2E-3085](https://jira.corp.adobe.com/browse/ACP2E-3085)- testSetBillingAddressIfCustomerIsNotOwnerOfAddress

**Pull request merged**
