### PR TITLE
Track details save while creating shipment via api

### PR DESCRIPTION
**Pull request by arijit-de93**
### Description

Code has been changed for the getTracksCollection() where it will check if the TRACKS data are already present,  pull from there else create a collection and take it from there.

### Fixed Issues (if relevant)

1. magento/magento2#13954: Track details save while creating shipment via api
2. ...

### Manual testing scenarios

1. Create Shipment through API by providing the track details.
2. Once created, check the track information in the admin site.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by dmanners** [comment]
Hi @arijit-de thank you for this Pull Request.

I do not think this is the right fix in this situation. From what I can see now after your change the `getTracksCollection` returns `\Magento\Sales\Api\Data\ShipmentTrackInterface` and not the expected `\Magento\Sales\Model\ResourceModel\Order\Shipment\Track\Collection`.

My suggestion here would be to look into the places calling `getTracksCollection` and see if they should be calling that method or indeed another method like `getTracks`.

**Comment by arijit-de93** [comment]
@dmanners , I will check this out.

**Comment by dmanners** [comment]
Hi @arijit-de Did you get any update on my feedback here?

**Comment by sidolov** [comment]
@arijit-de , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
