### PR TITLE
Fixed Force to show billing address form

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

Fixed Force to show billing address form
### Fixed Issues (if relevant)

1. magento/magento2#16380: Force to show billing address form

### Manual testing scenarios (*)

1. N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ravi-chandra3197. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by ravi-chandra3197** [comment]
Hello @orlangur
I have updated my code can review it.

**Comment by orlangur** [comment]
Hi @ravi-chandra3197, please do not assign reviewers without prior agreement.

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-3713](https://jira.corp.magento.com/browse/ENGCOM-3713) has been created to process this Pull Request

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3713](https://jira.corp.magento.com/browse/ENGCOM-3713) has been created to process this Pull Request

**Comment by p-bystritsky** [comment]
@ravi-chandra3197 PR should be reworked, as currently billing address in some cases is uneditable.
1. Create a Virtual Product.
2. Create a User with some default billing address.
3. As User, add a Virtual Product to cart and go to Checkout.
4. Try to edit the billing address.
default

**Comment by sidolov** [comment]
@ravi-chandra3197 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by driskell** [comment]
@p-bystritsky What were your steps to reproduce this from the start? I don't get the same issue as you. How did you mark the shipping address as not usable for shipping?

**Comment by driskell** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @driskell. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @driskell, here is your [Magento instance](https://i-19813-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19813-2-3-develop.instances.magento-community.engineering/admin](https://i-19813-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by driskell** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @driskell. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @driskell, here is your [new Magento instance](https://pr-19813.instances.magento-community.engineering).
Admin access: [https://pr-19813.instances.magento-community.engineering/admin](https://pr-19813.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by driskell** [comment]
Testing without a canUseForBilling() patch and only comparing behaviour between vanilla 2.3-develop and this PR - I see no visible or functional change. The billing address is not editable in either so looks to be a false positive. To edit the billing address you need to select "New address" in the drop down and type in a new address, then click Update.

When testing using our instance of 2.3 locally with our module that populates a shipping address where canUseForBilling returns false, this PR fixes the issue that we were experiencing, as reported in #16380 

Can this be merged? Many thanks.

**Review by driskell — APPROVED** [review]

**Comment by driskell** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @driskell. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @driskell, here is your [Magento instance](https://i-19813-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19813-2-3-develop.instances.magento-community.engineering/admin](https://i-19813-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krzksz** [comment]
Hey @ravi-chandra3197 and @driskell, can you please take a look at failing functional tests for virtual product? I'm don't think this is a coincidence.

**Comment by slavvka** [comment]
@ravi-chandra3197 Could you please take a look at the failing tests?

**Review by slavvka — CHANGES_REQUESTED** [review]
Please fix the failing tests

**Comment by ravi-chandra3197** [comment]
Hello @slavvka 
I have checked  failing tests, but it's not related to my PR changes, it's showing like e.g " CSS or XPath element with '.action-edit-address' was not found,
"
can you help me to fix failing tests?

Thank you.

**Comment by driskell** [comment]
@ravi-chandra3197 I was thinking about the test and wondering if it was actually impacted here, because virtual products don't show a shipping address. So previously it's possible there was some strange UI behaviour when checking out on those.

@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @driskell. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by slavvka** [comment]
@ravi-chandra3197  After several build reruns the failure persist. So I think there's an issue with tests because of your changes. Could you please run them locally to check?

**Comment by engcom-Charlie** [comment]
Hi @ravi-chandra3197, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
