### PR TITLE
Can't update totals for credit note

### PR DESCRIPTION
**Pull request by Valant13**
### Description (*)
Implement changes from commit 451f7b9

### Fixed Issues (if relevant)

1. magento/magento2#22774: Can't update totals for credit note

### Manual testing scenarios (*)

1. Select an invoice
2. Click "Credit Memo"
3. Add value to Refund Shipping , Adjustment Refund or Adjustment Fee field

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by torhoehn** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @torhoehn, here is your [new Magento instance](https://pr-23343.instances.magento-community.engineering).
Admin access: [https://pr-23343.instances.magento-community.engineering/admin](https://pr-23343.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by gwharton** [comment]
These changes have already been merged into 2.3-develop. Closing no longer required.

**Pull request closed without merging**
