### PR TITLE
Fixed MFTF tests naming convention

### LINKED ISSUE #29650: [Issue] Fixed MFTF tests naming convention
This issue is automatically created based on existing pull request: magento/magento2#29578: Fixed MFTF tests naming convention

---------

### Description (*)

This PR will fix the MFTF naming convention for login as customer functionality
### Related Pull Requests

https://github.com/magento/magento2/pull/29415

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by konarshankar07**
### Description (*)

This PR will fix the MFTF naming convention for login as customer functionality
### Related Pull Requests

https://github.com/magento/magento2/pull/29415

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29650: Fixed MFTF tests naming convention

### CODE REVIEW

**Comment by konarshankar07** [comment]
@magento run all tests

**Comment by rogyar** [comment]
For QA: Please note that this PR contains some backward-incompatible changes.

**Review by rogyar — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8021](https://jira.corp.magento.com/browse/ENGCOM-8021) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Charlie** [comment]
@okolesnyk Can you please review this PR?

**Comment by sidolov** [comment]
@magento create issue

**Comment by konarshankar07** [comment]
Hello @sidolov 
As https://github.com/magento/magento2/pull/29415 PR has been merged. Can we please also merge this PR?
Thanks

**Comment by sidolov** [comment]
@konarshankar07 unfortunately, we cannot merge such changes in the scope of patch release since they are backward incompatible. I believe we will have the ability to process it once the branch 2.5-develop will be opened.

**Pull request closed without merging**
