### PR TITLE
MFTF: Shipping To Multiple Addresses If Maximum QTY Limit Was Reached

### PR DESCRIPTION
**Pull request by DmitryTsymbal**
This PR contains MFTF test for verifying if Shipping To Multiple Addresses option is available before reaching maximum qty limit and after.

**Steps to reproduce**
1 - Configure Maximum QTY limit
2 - Add product into shopping cart (allowed qty limit)
3 - Update Product's qty (reached limit)
4 - Perform Assertions

### CODE REVIEW

**Comment by DmitryTsymbal** [comment]
@magento run all tests

**Review by sidolov — CHANGES_REQUESTED** [review]
@DmitryTsymbal  please, resolve merge conflicts

**Comment by engcom-Charlie** [comment]
Hi @DmitryTsymbal,

Thank you for your contribution!

I will look into the build conflicts.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Integration Tests, Functional Tests B2B

**Comment by engcom-Charlie** [comment]
Hi @sidolov,

I have merged latest 2.4-develop changes into this PR branch and resolved all conflicts.

The integration test which is failing in build is not part of this PR and not failing because of any of the changes made in this PR so moving this PR to Merge in Progress.

image


Thank you!

**Pull request merged**
