### PR TITLE
Make possible to upload SVG logo by admin

### PR DESCRIPTION
**Pull request by cbmd**
Nowadays it is pretty useful to have an option to upload SVG logo, since this will reduce assets that needs for all different devices to be rendered perfectly.

### CODE REVIEW

**Comment by vrann** [comment]
Hi, @cbmd,
thanks for contribution!
You allow to upload SVG just for Logo. Should this option be available for any Image, so that allowed extensions in the Magento\Backend\Model\Config\Backend\Image is extended on svg as well?

**Comment by cbmd** [comment]
@vrann I do think that it can be done in more general class, but in case "just for logo" we avoid situations where it can be uploaded for example for products (which is useless usage of image type, as i think). But we could discuss this one with community :)

**Comment by cbmd** [comment]
So i meant that this type of images should be used carefully, since in some cases it will dramatically increase image size instead of making it better in performance and usability wise...

**Comment by vrann** [comment]
@cbmd thanks, I see your reasons.

Can you please cover the contribution with tests? It is something we ask contributors to do as a part of https://github.com/magento/magento2/wiki/Contribution-Guide

**Comment by anupdugar** [comment]
@cbmd Any updates on this?

**Comment by cbmd** [comment]
@anupdugar @vrann Sorry about delay, i will provide them ASAP for sure, busy weeks...

**Comment by vpelipenko** [comment]
@cbmd, do you have any news for us?

**Comment by vrann** [comment]
@cbmd this change is covered with the test in internal codebase. We will merge this PR soon. Thanks!

**Comment by vrann** [comment]
@cbmd can you please make sure that there is no conflicts in the files you contributed with the latest from the mainline. Backend models were moved to the Config module.

**Comment by vrann** [comment]
@cbmd I've resolved conflict internally. No other changes is need. Please don't do any other change.
This pull request will be merged soon. Thanks!

**Comment by snohe** [comment]
@cbmd, this is now included in 0.74.0-beta1.  Thank you again for your contribution and continued support in Magento!

**Pull request merged**
