### PR TITLE
Fixing issue #8196

### PR DESCRIPTION
**Pull request by basselalaraaj**
Fixing issue #8196

### CODE REVIEW

**Comment by avoelkl** [comment]
Hi @basselalaraaj,
Mind to update your PR as there is one conflicting file:
app/code/Magento/ConfigurableProduct/Model/ResourceModel/Product/Type/Configurable.php

Thanks!

**Comment by vrann** [comment]
@basselalaraaj please merge the code with the latest from the develop branch. Currently it is not mergeable

**Comment by basselalaraaj** [comment]
@vrann @avoelkl created new pull request
https://github.com/magento/magento2/pull/8751

**Comment by orlangur** [comment]
@basselalaraaj, for the future - you can simply force push into the same branch you created PR from ;)

**Pull request closed without merging**
