### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by piotrekkaminski**
Add translation badge from Crowdin

### CODE REVIEW

**Comment by vpelipenko** [comment]
@piotrekkaminski, we have internal task tracking system, please, use it. What is Crowdin? Do we really need this link there?

**Comment by daim2k5** [comment]
I think we need this, is only one link but the information is very important.

**Comment by piotrekkaminski** [comment]
@vpelipenko can this be merged now? we have the external system and we need to encourage people to contribute translations. As this is something specific to Github, i don't see a place for it in the Jira.

**Comment by magento-cicd** [comment]
We have automated a Magento Contributor License Agreement verifier for contributions sent to our GitHub projects.
Please see the CLA agreement in the Pull Request comments.

**Comment by davidalger** [comment]
@vpelipenko Would you mind sharing an update on whether or not we can expect this to be merged or if it should be closed? In my opinion it would be valuable to include the link, so I'd like to see it merged, but it would be great to know whether or not that is expected to happen.

**Comment by buskamuza** [comment]
@piotrekkaminski , could you, please, sign CLA and update the branch to make the checklist green?

**Comment by piotrekkaminski** [comment]
@buskamuza i tried signing several times and it still says it is not signed. Travis fails due to mysql gone away and other problem, not related to text file change.

**Comment by eddielau** [comment]
@mmansoorebay will be able to help with CLA issue.

**Comment by KrystynaKabannyk** [comment]
The internal ticket is created MAGETWO-50796.

**Pull request closed without merging**
