### PR TITLE
Correcting position of Product name in Thumbnail popup

### LINKED ISSUE #34155: [Issue] Correcting position of Product name in Thumbnail popup
This issue is automatically created based on existing pull request: magento/magento2#33888: Correcting position of Product name in Thumbnail popup

---------

### Description (*)
When admin user click on Product Thumbnail one popup is showing and there product title is not in the center.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. login to admin panel -> Catalog -> Products
2. Click on the Thumbnail of any product and check the position of Product's Name

Actual Result (*)
image

Expactced Result (*)
image

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by manavluhar**
### Description (*)
When admin user click on Product Thumbnail one popup is showing and there product title is not in the center.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. login to admin panel -> Catalog -> Products
2. Click on the Thumbnail of any product and check the position of Product's Name

Actual Result (*)
image

Expactced Result (*)
image

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#34155: Correcting position of Product name in Thumbnail popup

### CODE REVIEW

**Comment by manavluhar** [comment]
@magento give me test instance

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by BarnyShergold** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Review by BarnyShergold — APPROVED** [review]
Hard to spot the change on the single line file!

**Comment by magento-engcom-team** [comment]
Hi @BarnyShergold, thank you for the review.
[ENGCOM-9195](https://jira.corp.magento.com/browse/ENGCOM-9195) has been created to process this Pull Request
:eight_spoked_asterisk: @BarnyShergold, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by manavluhar** [comment]
> Hard to spot the change on the single line file!

**replaced**
`.modal-popup .modal-title{font-size:2.4rem;margin-right:6.4rem}`
**with**
`.modal-popup .modal-title{font-size:2.4rem}`

**replaced** 
`.modal-title{font-weight:400;margin-bottom:0;min-height:1em}`
**with**
`.modal-title{text-align:center;font-weight:400;margin-bottom:0;min-height:1em}`

@BarnyShergold 🙌

**Comment by bgorski** [comment]
@manavluhar I beautified the file and from what I see this is going to affect all modals on pages where that css is loaded - is that the intended behavior here?
CC @BarnyShergold

**Comment by BarnyShergold** [comment]
@magento run Functional Tests CE

**Comment by BarnyShergold** [comment]
@manavluhar can you please check the comment made by @bgorski and confirm?

**Comment by manavluhar** [comment]
Thank you for following up @BarnyShergold 🙌
Yes, This is the intended behavior here @bgorski 😊

**Comment by Den4ik** [comment]
@magento create issue

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by manavluhar** [comment]
@magento run Functional Tests CE

**Comment by manavluhar** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by manavluhar** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run Magento Health Index, Functional Tests CE

**Comment by manavluhar** [comment]
@magento run Functional Tests CE

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run all tests

**Comment by manavluhar** [comment]
@magento run Unit Tests, Functional Tests EE, Functional Tests B2B

**Comment by manavluhar** [comment]
@magento run all tests

**Review by engcom-Delta — CHANGES_REQUESTED** [review]
It is not resolved

**Comment by engcom-Delta** [comment]
Hi @manavluhar , 

Thanks for the collaboration & contribution!

### :x: QA not Passed

Correcting position of Product name in Thumbnail popup

**Manual Scenario Steps**

1. login to admin panel -> Catalog -> Products
2. Click on the Thumbnail of any product and check the position of Product's Name

**:heavy_check_mark: Expected result After Fix** 

new


**:x: Actual result After Fix** 

Screenshot 2023-12-13 at 8 32 15 PM

**Comment by manavluhar** [comment]
@magento run all tests

**Pull request closed without merging**
