### PR TITLE
magento/magento2#25866: Fixed negative number for out of stock threshold

### PR DESCRIPTION
**Pull request by staniag**
### Description (*)
Improved the validation for minQty. It was using the old value if provided quantity threshold was negative.

### Fixed Issues (if relevant)

1. magento/magento2#25158: Can't set products' Out of Stock Threshold to a negative value
2. magento/magento2#25866: Can not set Negative number for Out of stock threshold

### Manual testing scenarios (*)

1. Setted threshold to -10
2. Setted threshold to 50
3. Left threshold empty

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - ~[ ] All new or changed code is covered with unit/integration tests (if applicable)~
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @alex-kolesnyk. Thank you for your request.
Unfortunately, I can only deploy instances for `2.2-develop` and `2.3-develop` base branches

**Comment by magento-engcom-team** [comment]
Hi @alex-kolesnyk. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @alex-kolesnyk. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @alex-kolesnyk. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @alex-kolesnyk, here is your [Magento instance](https://i-25868-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25868-2-4-develop.instances.magento-community.engineering/admin](https://i-25868-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ishakhsuvarov** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @ishakhsuvarov, here is your [new Magento instance](https://pr-25868.instances.magento-community.engineering).
Admin access: [https://pr-25868.instances.magento-community.engineering/admin](https://pr-25868.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by dmytro-ch** [comment]
Hi @sagaltsev, thank you for your contribution!

I have doubts about the current fix, considering a similar solution https://github.com/magento/magento2/commit/6f4df9be6a8f2a43b08b3831821d01fe6f1e4c2f#diff-1555bd96a37cc3d7a70869442e07a012 applied in scope of the internal ticket `MC-19872`, has been reverted https://github.com/magento/magento2/commit/b21394fa5d4a860476c32b1d678eb577b8ac3c83#diff-1555bd96a37cc3d7a70869442e07a012 by `MC-20504`.

Unfortunately, I could not find any additional information on why the fix was reverted.
@sidolov, @ishakhsuvarov could you please check for some details in the tickets mentioned above?

Thank you!

**Comment by dmytro-ch** [comment]
Hello @sagaltsev, I'm closing this PR now due to inactivity.
Feel free to reopen and update if you wish to continue.
Thank you!

**Pull request closed without merging**
