### PR TITLE
Replace repetitive actions with Action Groups in AdminConfigurableProductCreateTest

### LINKED ISSUE #32507: [Issue] Replace repetitive actions with Action Groups in AdminConfigurableProductCreateTest
This issue is automatically created based on existing pull request: magento/magento2#32463: Replace repetitive actions with Action Groups in AdminConfigurableProductCreateTest

---------

### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run the test in the local environment and verified that it run successfully

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### LINKED ISSUE #32569: [Issue] Replace repetitive actions with Action Groups in AdminConfigurableProductCreateTest
This issue is automatically created based on existing pull request: magento/magento2#32463: Replace repetitive actions with Action Groups in AdminConfigurableProductCreateTest

---------

### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run the test in the local environment and verified that it run successfully

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32507: Replace repetitive actions with Action Groups in AdminConfigurableProductCreateTest

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run the test in the local environment and verified that it run successfully

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32507: Replace repetitive actions with Action Groups in AdminConfigurableProductCreateTest

### Resolved issues:
1. [x] resolves magento/magento2#32569: Replace repetitive actions with Action Groups in AdminConfigurableProductCreateTest

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests EE

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B

**Review by edenduong — APPROVED** [review]
Thank you for your contribution !

**Comment by edenduong** [comment]
@magento create issue

**Comment by magento-engcom-team** [comment]
Hi @edenduong, thank you for the review.
[ENGCOM-8962](https://jira.corp.magento.com/browse/ENGCOM-8962) has been created to process this Pull Request

**Pull request merged**
