### PR TITLE
Replace repetitive actions with Action Groups in AdminConfigurableProductOutOfStockAndDeleteCombinationTest and AdminConfigurableProductOutOfStockTestDeleteChildrenTest

### LINKED ISSUE #34316: [Issue] Replace repetitive actions with Action Groups in AdminConfigurableProductOutOfStockAndDeleteCombinationTest and AdminConfigurableProductOutOfStockTestDeleteChildrenTest
This issue is automatically created based on existing pull request: magento/magento2#34113: Replace repetitive actions with Action Groups in AdminConfigurableProductOutOfStockAndDeleteCombinationTest and AdminConfigurableProductOutOfStockTestDeleteChildrenTest

---------

### Fixed Issues (if relevant)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Fixed Issues (if relevant)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#34316: Replace repetitive actions with Action Groups in AdminConfigurableProductOutOfStockAndDeleteCombinationTest and AdminConfigurableProductOutOfStockTestDeleteChildrenTest

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Semantic Version Checker

**Comment by eduard13** [comment]
@magento create issue
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Pull request merged**
