### PR TITLE
Use backend model also for default config values

### PR DESCRIPTION
**Pull request by kweij**
This causes the ```afterLoad()``` method to be invoked, also for default configuration values from ```config.xml```

Fixes issue #7741

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=7742) <br/>All committers have signed the CLA.

**Comment by antonkril** [comment]
@kweij please fix failing tests.

**Comment by ishakhsuvarov** [comment]
Hi @kweij 
I'm closing this PR for now due to inactivity. Please reopen if you would like to continue work on it.
Thank you.

**Comment by kweij** [comment]
~Where can I find the failed test results? I'd like to continue work on this.~

Found it!

**Comment by ishakhsuvarov** [comment]
@kweij I've reopened the PR. Plese sync your branch with the latest `develop` and resolve conflicts. You will see test results by following Travis CI details link.

**Comment by kweij** [comment]
@antonkril I can't get the tests to run without failure. I had to change the unit test to change the expected result (this sounds horrible, but it just wasn't correct) - but now the integration test fails and my understanding of these tests is insufficient to deal with this issue. Any help would be appreciated.

**Comment by ishakhsuvarov** [comment]
Hi @kweij 
I will look into the test failures and let you know if I find anything useful.

**Pull request merged**
