### PR TITLE
Update system.xml

### PR DESCRIPTION
**Pull request by hackrat**
Fixed ACL Incorrect for Advanced section in backend configurations

### Description (*)
ACL resource assigned was wrong.
### Fixed Issues (if relevant)

1. magento/magento2#19921: ACL incorrect for Advance in system configuration

### Manual testing scenarios (*)

1. Create a new role in the backend
2. Give the role access to the resource 'Advanced Section'
3. Create a new account
4. Give the account the new role
5. Login with the new account and go to Stores -> Configuration -> Advanced -> Advanced

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @hackrat. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19924) <br/>All committers have signed the CLA.

**Review by VladimirZaets — APPROVED** [review]

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3760](https://jira.corp.magento.com/browse/ENGCOM-3760) has been created to process this Pull Request

**Comment by sdzhepa** [comment]
Hello @hackrat 

During testing our QA engineer faced an issue.
Could you please have a look and fix it?

Please see the quote after testing on branch with the PR:

PR doesn't fix issue #19921 

Manual testing scenario:
1. Create a new role in the backend with next Role Resources:
- Resource Access=Custom
- Resources=Advanced Section
2. Create a new admin user and assign test role
3. Login with the new Admin user based on test role

**Actual Result:** Not OK,  'Advanced Section' is not shown


Thank you for contribution and collaboration

**Comment by sidolov** [comment]
Hi @hackrat , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by ghost** [comment]
Hi @hackrat, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+magento2+19924), it will take less than a minute. </br>Your feedback will help us to improve contribution process.

**Comment by sidolov** [comment]
@hackrat , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
