### PR TITLE
Make product SKU not null

### LINKED ISSUE #27411: Table structure issue catalog_product_entity (sku field is allowed nulls)
### Preconditions (*)
1. Any Magento version (tested on all significant releases, 2.1, 2.2, 2.3)
2. Reproduced on 2.4-develop

### Steps to reproduce (*)
1. Add a product either through migration, a custom importer or directly in the database.
2. Leave out the field SKU (in other words, leave it NULL).
3. Go to the product edit page in the backoffice.

### Expected result (*)
1. Should not be possible to add the product OR should not throw an error in the backoffice.

### Actual result (*)
1. Product is added without issues.
2. When attempting to edit the product in the backoffice the following error is thrown:
`Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Catalog\Model\ProductRepository::prepareSku() must be of the type string, null given, called in /vendor/magento/module-catalog/Model/ProductRepository.php on line 790 and defined in /vendor/magento/module-catalog/Model/ProductRepository.php:800 Stack trace: 
#0  /vendor/magento/module-catalog/Model/ProductRepository.php(790): Magento\Catalog\Model\ProductRepository->prepareSku(NULL) 
#1 /vendor/magento/module-catalog/Model/ProductRepository.php(349): Magento\Catalog\Model\ProductRepository->saveProductInLocalCache(Object(Magento\Catalog\Model\Product\Interceptor), '3e07f167255019f...') 
#2 /vendor/magento/module-catalog/Model/ProductRepository.php(314): Magento\Catalog\Model\ProductRepository->cacheProduct('3e07f167255019f...', Object(Magento\Catalog\Model\Product in /vendor/magento/module-catalog/Model/ProductRepository.php on line 800`

### LINKED ISSUE #32525: Table structure issue catalog_product_entity (sku field is allowed nulls)
# Preconditions

1. Any Magento version (tested on all significant releases, 2.1, 2.2, 2.3)
2. Reproduced on 2.4-develop
3. #magento2/27411 was closed while it's a verified and open bug. You can't do that. Opening this as a new issue. 

# Steps to reproduce

1. Add a product either through migration, a custom importer or directly in the database.
2. Leave out the field SKU (in other words, leave it NULL).
3. Go to the product edit page in the backoffice.

# Expected result

1. Should not be possible to add the product OR should not throw an error in the backoffice.

# Actual result

1. Product is added without issues.
2. When attempting to edit the product in the backoffice the following error is thrown:
`Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Catalog\Model\ProductRepository::prepareSku() must be of the type string, null given, called in /vendor/magento/module-catalog/Model/ProductRepository.php on line 790 and defined in /vendor/magento/module-catalog/Model/ProductRepository.php:800 Stack trace: #0 /vendor/magento/module-catalog/Model/ProductRepository.php(790): Magento\Catalog\Model\ProductRepository->prepareSku(NULL) #1 /vendor/magento/module-catalog/Model/ProductRepository.php(349): Magento\Catalog\Model\ProductRepository->saveProductInLocalCache(Object(Magento\Catalog\Model\Product\Interceptor), '3e07f167255019f...') #2 /vendor/magento/module-catalog/Model/ProductRepository.php(314): Magento\Catalog\Model\ProductRepository->cacheProduct('3e07f167255019f...', Object(Magento\Catalog\Model\Product in /vendor/magento/module-catalog/Model/ProductRepository.php on line 800`

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
Fixes issue when we weren't able to create product with null SKU through magento, but still could make it in DB. That's a mistake for sure that we should fix.

I think test coverage isn't needed for this case, as Magento itself worked fine and you weren't able to create such a product from it.

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/27411
2. Fixes https://github.com/magento/magento2/issues/32525

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by hws47a — COMMENTED** [review]
Hi @ihor-sviziev, the change make total sense for me, however, it could be not backward compatible as

> The following is a list of prohibited DB Schema changes:
> 
> Modifying field type, default value, or property

As we are changing the type from basically `?string` to `string`

Do you know somebody who we can ask for guidance?
Alternatively, we may target it to the `2.5-develop` branch.

**Comment by ihor-sviziev** [comment]
@sidolov @sivaschenko what do you think about this PR? Can we accept it?

**Comment by hws47a** [comment]
I agree that there is no need for tests as product SKU piece should be covered many-many times and it doesn't make sense to inject the wrong value into DB to trigger the error

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8947](https://jira.corp.magento.com/browse/ENGCOM-8947) has been created to process this Pull Request

**Review by hws47a — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @hws47a, thank you for the review.
[ENGCOM-8947](https://jira.corp.magento.com/browse/ENGCOM-8947) has been created to process this Pull Request

**Comment by engcom-Oscar** [comment]
:heavy_check_mark: QA passed

Was checked case from Manual testing scenarios 
1. Add a new 
2. product directly in the database.
2. Leave out NULL for the field SKU.
3. Go to the product edit page in the backoffice.

:x: **Before:**
Screenshot from 2021-03-22 16-16-46

:heavy_check_mark: **After:**
Screenshot from 2021-03-22 15-41-34

**Pull request merged**
