### PR TITLE
Integration Tests: `setup:install` command hangs when question provided

### LINKED ISSUE #36539: [Issue] Integration Tests: `setup:install` command hangs when question provided
This issue is automatically created based on existing pull request: magento/magento2#35948: Integration Tests: `setup:install` command hangs when question provided

---------

### Description (*)
This Pull Request adds `--no-interaction` flag in order to avoid the situation when `setup:install` (or any other command) gets stuck due to the question asked in a non-interactive environment.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
1. Add class that asks question after Magento installation (e.g. about Config import)
2. Execute Magento Integration Tests

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
This Pull Request adds `--no-interaction` flag in order to avoid the situation when `setup:install` (or any other command) gets stuck due to the question asked in a non-interactive environment.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
1. Add class that asks question after Magento installation (e.g. about Config import)
2. Execute Magento Integration Tests

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36539: Integration Tests: `setup:install` command hangs when question provided

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@lbajsarowicz, shouldn't we add similar for setup:install?

**Comment by lbajsarowicz** [comment]
@ihor-sviziev I added it here:
https://github.com/magento/magento2/pull/35948/files#diff-f52136b2dfa5c36438fc1969770d5a968b040984ee336dc9362854e53193b071R552

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Please fix unit tests failure

**Comment by ihor-sviziev** [comment]
I also had similar issue on GitHub Actions, it was just now showing any result for a long time and then was just cancelled by me. It was really hard to debug such case doe to missing any output and logs

**Comment by ihor-sviziev** [comment]
@lbajsarowicz any updates?

**Comment by lbajsarowicz** [comment]
@magento run Unit Tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@ihor-sviziev I updated Unit Tests.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@lbajsarowicz still failing :(

**Comment by ishakhsuvarov** [comment]
Moving to `extended testing` in hopes that someone would be able to stabilize the tests and get ti delivered.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Integration Tests, Functional Tests CE, Functional Tests B2B, Functional Tests EE

**Comment by engcom-Echo** [comment]
@ihor-sviziev Can you please review the PR i have fixed the unit tests which were failing.

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Integration Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Echo** [comment]
@magento Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by engcom-Delta** [comment]
@magento create issue

**Comment by engcom-Delta** [comment]
Hi @lbajsarowicz,
We have tried to reproduce the issue in magento 2.4-develop and following steps are followed to reproduce.
1. Add class that asks question after Magento installation 
a. Enabled magento production mode.
b. Created website, store, and storeview from backend
c. Magento setup:upgrade && di:compile
d. bin/magento app:config:dump
e. change the store name.
f.  bin/magento app:config:import

Screenshot 2022-11-28 at 4 43 03 PM
2. Run Magento Integration Tests
we are getting as below 
Screenshot 2022-11-28 at 4 50 36 PM
please let us know if we are missing any steps or we are following different steps.

**Comment by engcom-Delta** [comment]
Hi @lbajsarowicz,
Thanks for the collaboration & contribution!
We have tried to reproduce the issue in magento 2.4-develop it is not reproducible and following steps are followed to reproduce.

1. Add class that asks question after Magento installation
a. Enabled magento production mode.
b. Created website, store, and storeview from backend
c. Magento setup:upgrade && di:compile
d. bin/magento app:config:dump
e. change the store name.
f. bin/magento app:config:import (command line)after these steps we are getting as below
Screenshot 2022-11-28 at 4 43 03 PM


2. Run Magento Integration Tests we are getting as below
Screenshot 2022-11-28 at 4 50 36 PM

If there are any steps missing or we are following a different approach, please let us know.

Thanks.

**Comment by lbajsarowicz** [comment]
@engcom-Delta Even if **you** cannot reproduce the issue, the headless processes should be run in `--non-interactive` mode, because you can not interact with the CLI during Integration Tests execution. Saying that, please proceed with processing this Pull Request.

**Comment by engcom-Echo** [comment]
@lbajsarowicz 
Thanks for the collaboration & contribution!


:heavy_check_mark: QA Passed
Integration Tests: setup:install command hangs when question provided

**Manual Scenario Steps**
1. Add class that asks question after Magento installation 
2. Execute Magento Integration Tests

**Before:** :heavy_multiplication_x: 
installation is not successful.
before


**After:** :heavy_check_mark: 
Test gets executed after successful installation.
after

**Comment by engcom-Charlie** [comment]
It seems bot moved this PR from Merge in Progress to Ready for Testing hence moving it back.

**Pull request merged**
