### PR TITLE
Remove unnecessary cache manipulation during setup

### LINKED ISSUE #38124: [Issue] Remove unnecessary cache manipulation during setup
This issue is automatically created based on existing pull request: magento/magento2#38123: Remove unnecessary cache manipulation during setup

---------
### Description

When running `bin/magento setup:db-data:upgrade` (or `bin/magento setup:upgrade`), Magento turns off some caches, then re-enables the same. This causes Magento to write out its configuration to disk, but this step seems unnecessary and is causing some issues with downstream modules which observe this event (write deployment configuration to disk) because it is not necessary at this step. Relevant caches are already cleared later on in the process, so turning them off and then back on again seems redundant.

I can't work out why this was added. The best I can find is the initial commit (https://github.com/magento/magento2/commit/96a2e17754c78e3939fcbe14f7729d7ded52e544), which says "MC-30236: Upgrade from 2.3.x CE with SD to 2.3.x EE AreaCode Exception". `MC-30263` seems like a reference to a ticket, but I don't have any visibility on this. I don't see any tests associated with this commit to demonstrate the bug it claims to resolve. The description of the supposed bug ("AreaCode Exception") suggests that this action (disable/enable caches) is not the correct resolution anyway. This pull request effectively removes all changes related to that ticket from this repository.

For my reference later, the specific case which we were investigating (which lead me back to this) was https://gitlab.hyva.io/hyva-themes/magento2-theme-module/-/blob/main/src/Plugin/HyvaModulesConfig/UpdateOnModuleStatusChange.php?ref_type=heads#L40 being called during during deployment, which over-wrote the file we stored in version control.

### Manual testing scenarios
1. Environment file gets regenerated as expected.
   1. Add a code comment to `app/etc/env.php`
   1. Run `bin/magento cache:disable layout && bin/magento cache:enable`
   1. Review the content of `app/etc/env.php` to see that the file has been regenerated.
1. Environment file does *not* get regenerated during `setup` commands
   1. Add a code comment to `app/etc/env.php`
   1. Run `bin/magento setup:db-data:upgrade`
   1. Review the content of `app/etc/env.php` to see that the file has *not* been modified.
   1. Run `bin/magento setup:upgrade`
   1. Review the content of `app/etc/env.php` to see that the file has *not* been modified.

### Questions or comments
I am happy to learn more about _why_ this code was initially added. It may be that the bug this was intended to fix no longer exists, or that there is a better way to fix that bug if it still remains.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fredden**
### Description

When running `bin/magento setup:db-data:upgrade` (or `bin/magento setup:upgrade`), Magento turns off some caches, then re-enables the same. This causes Magento to write out its configuration to disk, but this step seems unnecessary and is causing some issues with downstream modules which observe this event (write deployment configuration to disk) because it is not necessary at this step. Relevant caches are already cleared later on in the process, so turning them off and then back on again seems redundant.

I can't work out why this was added. The best I can find is the initial commit (https://github.com/magento/magento2/commit/96a2e17754c78e3939fcbe14f7729d7ded52e544), which says "MC-30236: Upgrade from 2.3.x CE with SD to 2.3.x EE AreaCode Exception". `MC-30263` seems like a reference to a ticket, but I don't have any visibility on this. I don't see any tests associated with this commit to demonstrate the bug it claims to resolve. The description of the supposed bug ("AreaCode Exception") suggests that this action (disable/enable caches) is not the correct resolution anyway. This pull request effectively removes all changes related to that ticket from this repository.

For my reference later, the specific case which we were investigating (which lead me back to this) was https://gitlab.hyva.io/hyva-themes/magento2-theme-module/-/blob/main/src/Plugin/HyvaModulesConfig/UpdateOnModuleStatusChange.php?ref_type=heads#L40 being called during during deployment, which over-wrote the file we stored in version control.

### Manual testing scenarios
1. Environment file gets regenerated as expected.
   1. Add a code comment to `app/etc/env.php`
   1. Run `bin/magento cache:disable layout && bin/magento cache:enable`
   1. Review the content of `app/etc/env.php` to see that the file has been regenerated.
1. Environment file does *not* get regenerated during `setup` commands
   1. Add a code comment to `app/etc/env.php`
   1. Run `bin/magento setup:db-data:upgrade`
   1. Review the content of `app/etc/env.php` to see that the file has *not* been modified.
   1. Run `bin/magento setup:upgrade`
   1. Review the content of `app/etc/env.php` to see that the file has *not* been modified.

### Questions or comments
I am happy to learn more about _why_ this code was initially added. It may be that the bug this was intended to fix no longer exists, or that there is a better way to fix that bug if it still remains.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38124: Remove unnecessary cache manipulation during setup

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento create issue

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run Functional Tests CE

**Comment by fredden** [comment]
@magento run Functional Tests CE

**Comment by fredden** [comment]
All tests are passing, which suggests that the problem which caused these changes to be introduced has likely been solved. This confirms that this work-around is no longer necessary.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Charlie** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
Magento with latest installation

**Manual testing scenario:**

1. Added a code comment to app/etc/env.php
2. Ran bin/magento setup:db-data:upgrade
3. Reviewed the content of app/etc/env.php

**Before:** :heavy_multiplication_x:
The app/etc/env.php was getting modified after setup:db-data:upgrade

**After:** :heavy_check_mark:  
The app/etc/env.php is not getting modified after setup:db-data:upgrade

5. Ran bin/magento setup:upgrade
6. Reviewed the content of app/etc/env.php


**Before:** :heavy_multiplication_x:
The app/etc/env.php was getting modified after bin/magento setup:upgrade

**After:** :heavy_check_mark:  
The app/etc/env.php is not getting modified after bin/magento setup:upgrade

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by engcom-Charlie** [comment]
The functional B2B failures are differnt in recent 2 runs. They are not related to PR and not failing because of PR changes.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38123/a978b14101e572c5f85942b532ce355c/Functional/allure-report-b2b/index.html

image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38123/2a509d655c82bd8e330f3a5d1cfaa9d5/Functional/allure-report-b2b/index.html#categories
image

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
As mentioned [above](https://github.com/magento/magento2/pull/38123#issuecomment-1831692925) Functional B2B failures are not related to this PR and the rest build is green hence moving this PR to Merge in Progress.

**Pull request merged**
