### PR TITLE
Fix currency validator on BE. Throw error when value is empty.

### PR DESCRIPTION
**Pull request by bmxmale**
### Description
currency-validator

Add statement to ignore validation when value is empty.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16222) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @bmxmale. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on Pull Request changes
- `@magento-engcom-team give me new test instance` - deploy **NEW** test instance based on Pull Request changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy Vanilla Magento instance for Issue or Pull Request

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by phoenix128** [comment]
Hello @bmxmale ,
thank you for your contribution.

Would you please provide a scenario to reproduce this issue?
Thanks.

**Comment by bmxmale** [comment]
Hi @phoenix128,
sorry for delay in response.

On `Stores -> Configuration -> General -> Currency Setup`
Setup `Base Currency`, `Default Display Currency`, `Allowed Currencies` to eg `Danish Krone`

Next prepare `bin/magento app:config:dump`

When magento read data from `config.php` file some backend validations like this from PR get empty values so throwing errors.

I also update to latest 2.2-develop version. Problem still persist.

**Comment by phoenix128** [comment]
Hello @bmxmale ,
thank you for your additional information.

**Comment by phoenix128** [comment]
I confirm this issue, but I am not sure this is the way to fix it.
I think we should skip the wole validation procedure for such fields coming from `config.php`.
I will start an internal discussion about that. Meanwhile I am putting this `on hold`.

**Comment by bmxmale** [comment]
@phoenix128 I agree to resolve problem on top level but fix for that could take some time. My fix don't mess much, but provide possibility to save config on this case.

When you finish internal discussion I could help with fixing config from file case.

**Comment by phoenix128** [comment]
I understand @bmxmale ,
we will handle this as soon as possible. I'll do my best to not delay it.

**Comment by phoenix128** [comment]
Hello @bmxmale ,
we have been talking about this and we agree that this PR is just trying to cover the issue and it may also have some unexpected behaviour.

The main problem seems to be in `\Magento\Config\Model\Config::_processGroup` and seems to be system wide. Not only currency related.

We are working to find a more complete solution unless you want to try to provide it.

**Comment by phoenix128** [comment]
Hello @bmxmale ,
I opened another PR with a more complete solution here: https://github.com/magento/magento2/pull/16393 .

You found a very important issue, thank you very much for your time and for your work.

**Pull request closed without merging**
