### PR TITLE
tear price change with tier price

### PR DESCRIPTION
**Pull request by sunilit42**
Fixed Issues (if relevant)
#23567

Summary (*)
(Not sure where to put this "issue")
I found the term "Tear Price" in some part of the core when I was digging around. I was wondering if this is a typo for "Tier Price" or actually a special term.

Examples (*)
With a little grep, I was managed to find "Tear Price" in at least 8 files:

### CODE REVIEW

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5448](https://jira.corp.magento.com/browse/ENGCOM-5448) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by orlangur** [comment]
@sidolov not so fast. Do we really can rename constants and change their values? Can we rely on SVC in regards to backward compatible changes?

**Comment by sdzhepa** [comment]
Hello @sunilit42 
FYI: @orlangur 

I have returned 4ccf3068f612771dbc4c48969b37c7ac445b7159 old constant name due to [Backward Compatibility Policy](https://devdocs.magento.com/guides/v2.2/contributor-guide/backward-compatible-development/#php)

> **Removing or renaming constants**
> Do not remove or rename constants.

> **Changing the value of a constant** 
> Changing the value of a constant is itself a backward compatible change.

**Comment by orlangur** [comment]
@sdzhepa nice, that's what I planned to check. However, it's better to deprecate spoiled constant and introduce a new one.

**Review by orlangur — CHANGES_REQUESTED** [review]
@sunilit42 please introduce a new constant with correct value and deprecate the old one.

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

**Comment by sidolov** [comment]
@sunilit42 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
