### PR TITLE
Implemented Varnish Customised 503 Error Page

### PR DESCRIPTION
**Pull request by muthu-ziffity**
### Description
This new feature enables varnish to show a customized 503 error page instead of the Varnish default error message page. 

The feature will provide an easy way to change and customize the error page of varnish. This page will show once the server gets down  

In Magento admin under section ( **Stores --> Configuration --> Advanced --> System --> Full Page Cache** )

screenshot-local magento233 com-2020 05

Once changed the **Caching Application** field value to **Varnish Cache (Recommended)** will show **Varnish Configuration** section

Under the **Varnish Configuration** section have fields(Access list, Backend host, Backend port, etc), In those lists additionally, the field( **Customized 503 Error Message File Location** ) will be added in the section. Based on the field values export of VCL for Varnish will be generated

While Customized 503 Error Message File Location field leaves as empty. It take default path({magento-root-path}/pub/varnish/error503.html) and added in generated VCL file for varnish

This feature will be included on the below version of varnish configuration generated from Magento Admin

Varnish 4

Varnish 5

Varnish 6

**Default Varnish 503 Error Page**

default_error

**Customized Varnish 503 Error Page**

varnish_custom_msg_2_4

**Custom Varnish Error Page File Location:** {magento-root-path}/pub/varnish/error503.html

### Expected behavior
Once you generate the VCL file from Magento admin by clicking the button (Export VCL for Varnish 4 {or} 5 {or} 6) then It will download varnish.vcl file. Then replace the new VCL file with your existing VCL file in Varnish service. Once restarted the varnish service updated configuration file will be activated. If Server gets down then customized varnish 503 will be shown on the frontend.

### Benefits
Current Magento only has the option to customize Access list, Backend host, Backend port, etc.. from Magento admin. In this new feature, we can easily customize the varnish 503 error page also

This additional feature will provide Developer and DevOps to reduce the configuration time for Varnish.

The error file is located under path {magento-root-path}/pub/varnish/error503.html. It can be easily customized by UI Developer

### CODE REVIEW

**Comment by muthu-ziffity** [comment]
@magento I am working on this

**Comment by sidolov** [comment]
Risk: medium since the customer should manually update the configuration to use the new functionality.

**Comment by torhoehn** [comment]
@sidolov Doesn't have any change of the .vlc-file have the same risk?

**Comment by torhoehn** [comment]
@magento run all tests

**Comment by torhoehn** [comment]
@hostep I think this a good idea!

@muthu-ziffity Could you please rename the file and fix failing tests?

**Comment by muthu-ziffity** [comment]
> @hostep I think this a good idea!
> 
> @muthu-ziffity Could you please rename the file and fix failing tests?

@hostep @sidolov @torhoehn Thanks for review my implementation. I will update those mentioned changes. Once done will keep you posted

**Comment by hostep** [comment]
Hi @muthu-ziffity: it looks like the changes to the filename haven't been made yet. Could you rename it when you find a little bit of time? Thanks! 🙂

**Comment by muthu-ziffity** [comment]
> Hi @muthu-ziffity: it looks like the changes to the filename haven't been made yet. Could you rename it when you find a little bit of time? Thanks!

Sure @hostep. Thanks for reminding this one

**Comment by muthu-ziffity** [comment]
@magento run all tests

**Comment by muthu-ziffity** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Hello @muthu-ziffity,

Thanks for the contribution!

We request you to please resolve the conflicts so that we can move further with this PR. Till the time we are moving this PR `On Hold`.

Thanks

**Comment by muthu-ziffity** [comment]
@

> Hello @muthu-ziffity,
> 
> Thanks for the contribution!
> 
> We request you to please resolve the conflicts so that we can move further with this PR. Till the time we are moving this PR `On Hold`.
> 
> Thanks

Sure @engcom-Hotel. I will resolve this

**Comment by engcom-Hotel** [comment]
Hello @muthu-ziffity,

As this PR has some conflicts due to which we are unable to proceed further. Hence we are closing this PR for now.

Let us know when you are ready to work on it again, and we will be happy to re-open it. Thank you for your contribution!

Thanks

**Comment by peterjaap** [comment]
Besides, this is a security risk to use std.fileread here; https://github.com/magento/magento2/pull/28440/files#diff-09a0a5ee7d8c56ee87cac97b0f291d7e416a810510d2719cdff73be3b3785740R211

**Pull request closed without merging**
