### PR TITLE
Advanced-Search-layout-not-proper

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Description (*)

Advanced Search layout not proper
### Fixed Issues (if relevant)

1. #20809: Advanced Search layout not proper

### Manual testing scenarios (*)

1. Click Advanced Search link in footer

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-21611.instances.magento-community.engineering).
Admin access: [https://pr-21611.instances.magento-community.engineering/admin](https://pr-21611.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rogyar** [comment]
Hi @amol2jcommerce. Thank you for your collaboration. It's looks better now on desktop resolutions. However, if you take a look at iPad (portrait) resolution - the form is quite small. The contact us form has the same issue, so it's not the best example. However, if you check the create account form - it behaves much better in terms of responsive design. Try to compare the result of your solution and the create account form on different resolutions.

**Comment by amol2jcommerce** [comment]
Hi @rogyar, I updated branch please review.

**Comment by sanganinamrata** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sanganinamrata. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sanganinamrata, here is your [new Magento instance](https://pr-21611.instances.magento-community.engineering).
Admin access: [https://pr-21611.instances.magento-community.engineering/admin](https://pr-21611.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by amol2jcommerce** [comment]
Hi @rogyar, I updated branch as per suggestion please review.

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-21611.instances.magento-community.engineering).
Admin access: [https://pr-21611.instances.magento-community.engineering/admin](https://pr-21611.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4461](https://jira.corp.magento.com/browse/ENGCOM-4461) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4461](https://jira.corp.magento.com/browse/ENGCOM-4461) has been created to process this Pull Request

**Pull request merged**
