### PR TITLE
Remove Great Britain from EU country list

### LINKED ISSUE #31506: [Issue] Remove Great Britain from EU country list
This issue is automatically created based on existing pull request: magento/magento2#31505: Remove Great Britain from EU country list

---------
### Description (*)
Remove Great Britain from EU country list

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)
1. Go to European Union Countries configuration and check if United Kingdom is selected

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by Jeroenll**
### Description (*)
Remove Great Britain from EU country list

### Fixed Issues (if relevant)
1. Fixes magento/magento2#31506

### Manual testing scenarios (*)
1. Go to European Union Countries configuration and check if United Kingdom is selected

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31506: Remove Great Britain from EU country list

### CODE REVIEW

**Comment by JeroenVanLeusden** [comment]
@magento create issue

**Comment by okorshenko** [comment]
@magento run all tests

**Review by coderimus — CHANGES_REQUESTED** [review]
Hello @JeroenVanLeusden 
Thank you for the work you have done.

I think that at least one test has to be fixed according to the idea of this PR: `\Magento\Shipping\Test\Unit\Helper\CarrierTest::testIsCountryInEU`
or
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Shipping/Test/Unit/Helper/CarrierTest.php#L110

**Comment by coderimus** [comment]
@magento run Integration Tests

**Comment by engcom-Charlie** [comment]
Hello @JeroenVanLeusden could you please look at https://github.com/magento/magento2/pull/31505#pullrequestreview-561315640.
Thank you.

**Comment by hostep** [comment]
This change alone is probably not enough to deal with Brexit.

They made a giant mess of their deal tax-wise and gave the Northern-Ireland part of the UK [a special status](https://finance.belgium.be/en/enterprises/vat/international/brexit#q9) where it still has to abide to the old tax rules like it's still part of the EU.

So that means that when Magento needs to figure out what customer group to assign to a customer based on his residence and vat number, we need to make a special case for Northern-Ireland.

The following code should return true when the countryCode is 'GB' and when the postal code of the shipping address is set to a postal code within Northern Ireland: https://github.com/magento/magento2/blob/6f79389b63f72f7395e949e8e296c9967f6e58cd/app/code/Magento/Customer/Model/Vat.php#L299-L306

Can somebody confirm or deny this?

**Comment by sidolov** [comment]
@hostep thank you for the detailed information! We raised this question to our product organization and I'll share the feedback here once we will have a decision on how to handle these cases.

**Comment by hostep** [comment]
@sidolov: can you please also look into: https://github.com/magento/community-features/issues/317. I've heard rumours about this 135 GBP threshold in the past few weeks but never quite understood what it was about and if the claims in that ticket are also true then there are even more ways in that Magento needs to be changed to be able to handle VAT calculations now due to Brexit unfortunately.

What a mess ... Let's hope the governments won't actually enforce these new rules for all sales since 01/01/2021 and leave some transition period because otherwise all Magento shop owners doing business from Europe to the UK are completely screwed accountancy-wise.

**Comment by gwharton** [comment]
Only just seen this now. 

https://github.com/magento/magento2/issues/31746
https://github.com/magento/magento2/issues/31745

**Comment by gwharton** [comment]
Worldwide selling to the UK must register with HMRC UK and collect UK VAT at point of sale for all transactions under 135GBP unless the UK buyer provides a valid UK VAT/EORI number. This is law as of January 1st 2021. The invoice must include the sellers UK VAT Number. For sales where the buyer presents a valid UK VAT/EORI number then no VAT is charged and the invoice MUST include a declaration saying the VAT must be accounted for by the buyer by reverse charge.

Worldwide selling to the EU must register with an EU VAT office and collect the appropriate EU VAT for the buyers country at point of sale for all transactions under 150EUR unless the EU buyer provides a valid EU VAT/EORI number. This will be law as of July 1st 2021. The invoice must include the sellers EU VAT Number. For sales where the buyer presents a valid EU VAT/EORI number then no VAT is charged and the invoice MUST include a declaration saying the VAT must be accounted for by the buyer by reverse charge.

It is likely that other countries systems may operate differently, so I recommend a plugin based "Tax Scheme" system where tax systems can be added.

e.g Norway VOEC, Australia GST are also law as of now, if certain sales thresholds are exceeded.

**Comment by gwharton** [comment]
Also note, that the VIES system will no longer validate UK VAT numbers, so the current system is not capable of putting UK buyers into a "No VAT" customer group. UK VAT numbers will need to be validated by https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-registered-companies-api/1.0

**Comment by PascalBrouwers** [comment]
Let's not combine removing the country from the EU list with a tax issue. @hostep make a different issue please for the tax issue.

**Comment by gwharton** [comment]
Apologies Pascal.

**Comment by gwharton** [comment]
Getting the issue back on topic, should we be patching existing installations too? If not, should we inform users via admin msg that they need to do it themselves or ensure there is something in the release notes.

**Comment by hostep** [comment]
@PascalBrouwers, noted, I've left a comment on https://github.com/magento/magento2/issues/31745 for the Northern Ireland issue and @gwharton created https://github.com/magento/magento2/issues/31746 for the 135 GBP treshhold.

**Comment by JeroenVanLeusden** [comment]
@magento run all tests

**Comment by gwharton** [comment]
Not wanting to side track this issue again, but this is a dangerous setting that should be completely removed from Magento in my opinion. The majority of use cases for this setting within Magento are in relation to taxes, customs areas, shipping services etc. The simple list of 27 EU member states is incorrect in most situations. What about Isle of Man, Gibraltar, Guernsey, Jersey, Monaco, Vatican State. I think it would be much less dangerous to let each module define what it see's as the EU depending on its use case, i.e Schengen area, EU currency zone, EEA, customs union etc.

**Comment by engcom-Foxtrot** [comment]
On hold until a discussion with the product organization is finished.

**Comment by gwharton** [comment]
Just to add a little more context to my previous comment on the use (and possible misuse) of this setting by modules, here is an uptodate graphic showing how complex the EU structure is.

**Comment by engcom-Charlie** [comment]
As per [comment](https://github.com/magento/magento2/pull/31505#issuecomment-796796333) moving this ticket in On hold for now.

Thank you!

**Comment by hostep** [comment]
Almost 10 months after the UK left the EU and there still hasn't been any progress here ...

@engcom-Foxtrot: what's the status of this discussion so far? Any chance this can happen in public as to get the community involved as well?

**Comment by engcom-Hotel** [comment]
Hello,

We have tried to reproduce the issue in the Magento 2.4-develop instance and found that the issue is still relevant:

image

Starting a discussion with PO on this issue. Will keep you updated on this further.

Thanks

**Comment by engcom-Echo** [comment]
Bot moved this from `On Hold` to `Changes Requested`. Hence moving it back.

**Comment by hostep** [comment]
> We have tried to reproduce the issue in the Magento 2.4-develop instance and found that the issue is still relevant

The question is not to remove it from the entire list, the question was to remove it as a default selected value from that list.
But that already happened in https://github.com/magento/magento2/commit/1c08100b688261e4b9bd8999fea75456f7cd3a79#diff-c1a0f6486b70a75d462b21912c7bec4a861034315eadb6067777edd50b2e10b3 like I [mentioned before](https://github.com/magento/magento2/pull/31505#issuecomment-1036510014).

So this PR can probably be closed now?

Would still be great if the tax system in Magento could be re-written to support calculating correct taxes for sales from EU countries to the UK (which changed after Brexit and Magento's system doesn't support this case anymore)

**Comment by engcom-Charlie** [comment]
Hi @hostep,

Thank you for the information and contribution!

As per the Manual steps to reproduce of this PR, this PR is only meant to "Remove Great Britain a default selected value from EU country list". I have tried to reproduce the mentioned issue in latest magento 2.4-develop and the issue is not reproducible.

image

As the issue is not reproducible now, closing this PR. Please feel free to reopen it for any further clarity.

Thank you!

**Pull request closed without merging**
