### PR TITLE
Fixed - CHANGELOG.md is reporting the incorrect issue links

### PR DESCRIPTION
**Pull request by ansari-ziyaurrahman**
Fixed - CHANGELOG.md is reporting the incorrect issue links #27049

### Description (*)
Fixed - CHANGELOG.md is reporting the incorrect issue links #27049

### Fixed Issues (if relevant)
1. magento/magento2#27049: Fixed - CHANGELOG.md is reporting the incorrect issue links #27049

### Manual testing scenarios (*)

1. check 2.3.4 changelog for #167 it redirect to wrong Issue

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Review by lbajsarowicz — APPROVED** [review]

**Comment by hostep** [comment]
@ansari-krish: this one line fix is not enough, there are a bunch more incorrect lines:
```
#773 -- problem jquery (fixed in magento/graphql-ce#797)
#271 -- Check Data should validate gallery information (fixed in magento/graphql-ce#489)
#815 -- Installation is incomplete. Check the console log for errors before trying again. (Windows 7 WAMP) (fixed in magento/graphql-ce#842)
...
```

We should also try to figure out how this file gets generated, I'm assuming some kind of script is used for this but I'm not sure if it will be in this repository, if a script is being used, the correct fix here would be to fix the script and then generate that file again.

@lbajsarowicz: do you happen to know more about this? Or do you know somebody inside Magento who can help explain this further? @sdzhepa maybe?

**Comment by lbajsarowicz** [comment]
@hostep That's actually good point from your side.
Let me call @VladimirZaets  - maybe he'll be able to provide the solution.

**Comment by engcom-Alfa** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Charlie** [comment]
Hi @ansari-krish now we're developing 2.4-develop. Please see [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details.

**Comment by lenaorobei** [comment]
@ansari-krish CHANGELOG.md is being generated by our internal tools.
I created a task to address this issue. Unfortunately `2.3.x` release line is not publicly available so I need to close this PR. We will fix it internally taking all wrong links into account.

**Pull request closed without merging**
