### PR TITLE
Removed redundant whitespace from order options

### PR DESCRIPTION
**Pull request by rickkuilman**
### Description (*)

Removed redundant whitespace so that the custom option value can be copied as a whole, instead of having to remove the whitespace every time.

A gif says more than 1000 words, before situation:

before

And after the fix:

after

### Manual testing scenarios (*)

Add a custom option to a product, long enough that it will be cut off (the dots show up) and hover over the dots. See gifs in description.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23867) <br/>All committers have signed the CLA.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5580](https://jira.corp.magento.com/browse/ENGCOM-5580) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by rickkuilman** [comment]
I've updated the failing test accordingly to the change in functionality that I made. This should fix the failing test (:

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by engcom-Foxtrot** [comment]
@magento run Functional tests

**Comment by engcom-Foxtrot** [comment]
@magento run functional tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
