### PR TITLE
PHPDoc fix non-canonical elements in Magento_AdminNotification

### PR DESCRIPTION
**Pull request by sankalpshekhar**
As per specification from PHPDoc, @var has a canonical syntax of specifying type and variable name.
### Description (*)

Refer to http://docs.phpdoc.org/references/phpdoc/tags/var.html

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @sankalpshekhar. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
@sankalpshekhar this should be fixed all over the code with automated tool and enforced with some test. Probably, `php-cs-fixer` can do this.

**Comment by sankalpshekhar** [comment]
> 
> 
> @sankalpshekhar this should be fixed all over the code with automated tool and enforced with some test. Probably, `php-cs-fixer` can do this.

@orlangur Not sure I understood this correctly, are you suggesting that we should have some tool (php-cs-fixer) to fix this all over code? I am already using a tool to inspect such issues, and auto-fix them, but unsure on how this can be done with the repo itself. I have identified where these needs to be fixed in all of the codebase, but wished to push them by module, so we can identify any issues that might arise and gets easier to revert, instead of reverting the entire PR. Let me know if i am missing anything here.

**Comment by orlangur** [comment]
> I am already using a tool to inspect such issues, and auto-fix them

@sankalpshekhar then please provide such steps, and also a test needs to be implemented to check such occurrences won't appear.

With automated tool it is easier to assure nothing is broken, no need to deliver on per-module basis.

**Comment by sankalpshekhar** [comment]
> 
> 
> > I am already using a tool to inspect such issues, and auto-fix them
> 
> @sankalpshekhar then please provide such steps, and also a test needs to be implemented to check such occurrences won't appear.
> 
> With automated tool it is easier to assure nothing is broken, no need to deliver on per-module basis.

@orlangur  I am using inspection tools in PHPStorm, that also allows to perform quick fixes on some the known trivial issues.

**Comment by orlangur** [comment]
@sankalpshekhar ok, please provide exact steps to reproduce in PhpStorm (then reviewer may just repeat them and compare diff instead of reviewing files manually) and implement or use some existing PHP Code Sniffer sniff to assure this rule is no more violated.

**Comment by sidolov** [comment]
@sankalpshekhar , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
