### PR TITLE
tooltip-dropdown-pointer :: Tooltip dropdown pointer not proper on ta…

### PR DESCRIPTION
**Pull request by ranee2jcommerce**
…blet

### Fixed Issues (if relevant)

1. magento/magento2#20487: On checkout page tooltip dropdown pointer not proper on tablet
2. ...

### Manual testing scenarios (*)

1. Add product to cart
2. On checkout page click on "question mark" icon besides Email Address field
3. Tooltip dropdown opens, pointer not points to icon

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ranee2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-20488.instances.magento-community.engineering).
Admin access: [https://pr-20488.instances.magento-community.engineering/admin](https://pr-20488.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-3938](https://jira.corp.magento.com/browse/ENGCOM-3938) has been created to process this Pull Request

**Pull request merged**
