### PR TITLE
#24353 Fix Varnish 6 Too many restarts issue

### LINKED ISSUE #24353: Magento varnish 6 Too many restarts
### Preconditions (*)

_Magento 2.4-develop;
Production mode;
Sample Data;
Php 7.3;
Varnish v. 6.2_

We tried https://github.com/magento/magento2/commit/882379061809b806fc5580729a6c9c78d782f84d#diff-2f64f6171deecba61bea147539cf72ec

However it results in too many restarts after a while.

### Steps to reproduce (*)

1. Configure Varnish and Web server (Apache 2 in my case) [devdocs](https://devdocs.magento.com/guides/v2.3/config-guide/varnish/config-varnish-configure.html);
2. Configure Magento to use Varnish

Go to Admin->Stores->Configuration->System->Full Page Cache:

- set **Cache Application** to **Varnish Cache**;
- set **TTL for public content** to **120** sec;
Screenshot from 2020-04-28 11-52-06

3. Export **Varnish 6 VCL**, configure and restart varnish service;
4. Run **_varnishlog_** in console;
5. Go to Storefront and try browsing the site for longer than 10min.

Use the VCL on production site with varnish 6.2, after a while certain objects get into a restart loop.
### Expected result (*)

We expect no 503 errors caused by restart

### Actual result (*)

 :heavy_multiplication_x: VCL keeps restarting forever resulting in: -   VCL_Error      Too many restarts after a few tries
 **503 Response** status and VCL error: **Too many restarts**
Peek 2020-04-28 11-20

**_Varnish logs_**
Screenshot from 2020-04-28 11-24-25
screenshotvar
Screenshot from 2020-04-28 11-27-17

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
This PR applies fix from https://github.com/magento/magento2/issues/24353#issuecomment-592038624, it was confirmed that it fixes issue in https://github.com/magento/magento2/issues/24353#issuecomment-620547253.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#24353

### Manual testing scenarios (*)
1. See https://github.com/magento/magento2/issues/24353

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Hanhan1989** [comment]
The functional Tests B2B failed!

**Comment by ihor-sviziev** [comment]
> The functional Tests B2B failed!

Looks like false positive

**Comment by Hanhan1989** [comment]
> > The functional Tests B2B failed!
> 
> Looks like false positive

I think so. The error was the following:

```
SUITE PRECONDITION FAILED:
Can't connect to Webdriver at http://localhost:5555/wd/hub. Please make sure that Selenium Server or PhantomJS is running.
```

**Comment by ihor-sviziev** [comment]
@lbajsarowicz maybe you could review my PR?

**Review by lbajsarowicz — APPROVED** [review]
:heavy_check_mark: According to the documentation, this change is fine.

I'd love to see review from someone who has more expertise with Varnish,.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7761](https://jira.corp.magento.com/browse/ENGCOM-7761) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

_Magento 2.4-develop;
Sample Data;
Php 7.3;
Varnish v. 6.2_

**Manual testing scenario:**

1. Configure Varnish and Web server (Apache 2 in my case) [devdocs](https://devdocs.magento.com/guides/v2.3/config-guide/varnish/config-varnish-configure.html);
2. Configure Magento to use Varnish

Go to Admin->Stores->Configuration->System->Full Page Cache:

- set **Cache Application** to **Varnish Cache**;
- set **TTL for public content** to **120** sec;
Screenshot from 2020-04-28 11-52-06

3. Export **Varnish 6 VCL**, configure and restart varnish service;
4. Run **_varnishlog_** in console;
5. Go to Storefront and try browsing the site for longer than 10min.

**Before:**   :heavy_multiplication_x: VCL keeps restarting forever resulting in: -   VCL_Error      Too many restarts after a few tries
 **503 Response** status and VCL error: **Too many restarts**
 
Peek 2020-07-09 16-19



**After:** :heavy_check_mark: No 503 errors caused by restart. Everything works as expected

**Pull request merged**
