### PR TITLE
Added "Today" to dashboard report

### LINKED ISSUE #34008: [Issue] Added "Today" to dashboard report
This issue is automatically created based on existing pull request: magento/magento2#33874: Added "Today" to dashboard report

---------
### Description (*)
Adds "Today" to the dashboard charts, so we can get a summary of sales/orders throughout the day.

image

### Manual testing scenarios (*)
1. Checkout an order as a customer
2. Log in to the backend
3. Enable Charts
4. Select "Today" From either the Orders or Amounts tab on the dashboard
5. Check the Graph and figures update accordingly

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by NetStorm84**
### Description (*)
Adds "Today" to the dashboard charts, so we can get a summary of sales/orders throughout the day.

image

### Manual testing scenarios (*)
1. Checkout an order as a customer
2. Log in to the backend
3. Enable Charts
4. Select "Today" From either the Orders or Amounts tab on the dashboard
5. Check the Graph and figures update accordingly

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#34008: Added "Today" to dashboard report

### CODE REVIEW

**Comment by NetStorm84** [comment]
@magento give me test instance

**Comment by NetStorm84** [comment]
@magento run all tests

**Comment by NetStorm84** [comment]
run Unit Tests

**Comment by NetStorm84** [comment]
@magento run Unit Tests

**Comment by NetStorm84** [comment]
@magento run all tests

**Comment by NetStorm84** [comment]
Not sure why the Functional Tests are failing, seems unrelated to my PR?

**Comment by NetStorm84** [comment]
@magento run all tests

**Review by BarnyShergold — APPROVED** [review]
Great idea and looks great too :)

**Comment by magento-engcom-team** [comment]
Hi @BarnyShergold, thank you for the review.
[ENGCOM-9194](https://jira.corp.magento.com/browse/ENGCOM-9194) has been created to process this Pull Request
:eight_spoked_asterisk: @BarnyShergold, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9194](https://jira.corp.magento.com/browse/ENGCOM-9194) has been created to process this Pull Request

**Comment by NetStorm84** [comment]
@magento give me test instance

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Have a Magento instance installed with sample data or by storing some data

**Manual testing scenario:**

1. Create a new customer and place a new order from the front end.

2. Login to admin and enable the chart from admin configurations
 
3. View Dashboard page and validate the Orders/Amounts section dropdown content.



**Before:** :heavy_multiplication_x: "Today" option was not included in the dropdown.

image


**After:** :heavy_check_mark: "Today" option is included in the dropdown.

image


Additionally checked the graph data is getting reloaded according the dropdown option we select. There is no other issue noticed and no regression is required since it has no impact on any other feature.

**Comment by ccondra** [comment]
Documentation update for this feature:  
https://github.com/magento/magento2/issues/34008

**Pull request merged**
