### PR TITLE
#26986 REST API Pagination issue

### LINKED ISSUE #26986: REST API Pagination Does not work as expected
### Preconditions (*)
1. Magento 2.3.4
2. REST API Call

### Steps to reproduce (*)
1. Fixture with 3 orders
2. Request with `page_size` = 1 and `current_page` = 99

### Expected result (*)
1. `total_count` returns 3
2. `items` returns empty array **OR** OutOfRangeException

### Actual result (*)
1. `total_count` is 3
2. `items` returns repeated last page of results

### Kudos for
@ihor-sviziev , @Vinai , @nuzil for discussion at `#appdesign` channel about this issue.
image
image
image

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
1. Covered the issue with API Functional Tests
1. Removed "feature" of overriding `currentPage` value

### Related Pull Requests
* https://github.com/magento/inventory/pull/2840

### Fixed Issues (if relevant)
1. magento/magento2#26986
2. magento/magento2#8099

### Manual testing scenarios (*)
N/A (API Functional Tests cover the change)

### Questions or comments
Discussed on Slack and GitHub issue

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Support
Solving this issue is supported by [Mediotype](mediotype.com)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
I am **not** going to fix **Semantic Version Checker** as I replaced `mixed` return types to proper ones.

**Comment by lbajsarowicz** [comment]
Fixed issue with Test passing by coincidence in MSI repository.

**Comment by lbajsarowicz** [comment]
@magento run all tests

Fixed issue with Test passing by coincidence in MSI repository.

**Comment by lbajsarowicz** [comment]
The issues for Functional Tests are actually interesting
image

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE

It's unclear for me how my change affects these tests. Investigating.

**Comment by lbajsarowicz** [comment]
Got it! The solution should be easy to provide.
Will work on it in the morning.

**Comment by lbajsarowicz** [comment]
@magento run all tests

Nailed the issue with "results found" in Admin Panel.
The reason for failure was `GROUP BY entity_id` used in `getSelectCountSql`.

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

What is interesting - the solution already worked for **MySQL**, but **ElasticSearch** was unaware of PageSize o.O

**Comment by lbajsarowicz** [comment]
@magento run all tests

Probably the issue with a changed date during test :-(

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

### WebAPI Tests
![image](https://user-images.githubusercontent.com/1639941/75210175-b1e18a00-5780-11ea-92d4-dd95aff3c188.png)

```
www-data@magento2-php-fpm:02:41 AM:/var/www/html$ vendor/bin/phpunit -c $(pwd)/dev/tests/api-functional/phpunit_graphql.xml $(pwd)/dev/tests/api-functional/testsuite/Magento/GraphQl/Swatches/ProductSearchTest.php
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

.                                                                                                                                                                                                                                                                                                                                                       1 / 1 (100%)

Time: 2.86 seconds, Memory: 81.50MB

OK (1 test, 4 assertions)

=== Memory Usage System Stats ===
Memory usage (OS):      109.93M (135.72% of 81.00M reported by PHP)
Estimated memory leak:  28.93M (26.32% of used memory)
```

### Integration tests
![image](https://user-images.githubusercontent.com/1639941/75210324-071d9b80-5781-11ea-94a4-b127cd9d6420.png)
![image](https://user-images.githubusercontent.com/1639941/75210393-3a602a80-5781-11ea-979f-ba1a0d028e2a.png)

```
www-data@magento2-php-fpm:02:41 AM:/var/www/html$ vendor/bin/phpunit -c $(pwd)/dev/tests/integration/phpunit.xml $(pwd)/dev/tests/integration/testsuite/Magento/Catalog/Model/Indexer/Product/Price/                   
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

.....                                                                                                                                                                                                                                                                                                                                                   5 / 5 (100%)

Time: 1.33 minutes, Memory: 161.00MB

OK (5 tests, 19 assertions)

=== Memory Usage System Stats ===
Memory usage (OS):      193.46M (120.16% of 161.00M reported by PHP)
Estimated memory leak:  32.46M (16.78% of used memory)

```

**Comment by lbajsarowicz** [comment]
@magento run all tests

Functional Tests should pass now.
Investigating Integration Tests, as they pass locally.

**Comment by lbajsarowicz** [comment]
@magento run all tests
Looking for a solution, have no idea how to reproduce Integration Tests failure locally.

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests CE
I have no idea why something was passing `pageSize = 0`, but latest change fixed the issue and the rest works as expected.

**Semantic Version Checker** fails due to `mixed` change to specific types (`string|int` etc).

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests CE

Inventory modules have flaky tests. I'm going to fix them in separate PR.
image

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6979](https://jira.corp.magento.com/browse/ENGCOM-6979) has been created to process this Pull Request

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
SVC failure should be approved

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6979](https://jira.corp.magento.com/browse/ENGCOM-6979) has been created to process this Pull Request

**Comment by buskamuza** [comment]
SVC:
- approving for `Magento\Framework\Data\Collection::getItemByColumnValue()`, `Magento\Framework\Data\Collection::_getItemId()`, `Magento\Framework\Data\Collection::getItemById()`

All other methods do not change. @ihor-sviziev, please create a ticket to fix SVC validation - it should not fail on namespace being imported.

**Comment by lenaorobei** [comment]
Internal ticked for false positive SVC failure created https://jira.corp.magento.com/browse/MC-31882

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6979](https://jira.corp.magento.com/browse/ENGCOM-6979) has been created to process this Pull Request

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6979](https://jira.corp.magento.com/browse/ENGCOM-6979) has been created to process this Pull Request

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @lbajsarowicz.

During testing, we faced the issue

**_Problem:_** Pagination does not work as expected

**Precondition:**
 For example, have a category with products for 3 pages (26 products in this case)

**Manual testing scenario:**
1. Go to Storefront;
2. Go to the category with products;
3. Move to the last page in the category ( page 3 in this case);
4. Select **36** value from drop-down **Show per page** menu;

**Actual Result: (with fix)**

:heavy_multiplication_x: We can't find products matching this selection

after


**Expected Result: (without fix)**

:heavy_check_mark: Showing a list of 26 items

before

@lbajsarowicz Could you take a look?

Thanks!

**Comment by lbajsarowicz** [comment]
@engcom-Alfa It is **expected** behaviour, because you don't have 3rd page with 36 results.
Change `?p` argument in your URL to `=1` and this will work.

If you don't like such behaviour - create another ticket for redirect to last available page (however this behaviour is misleading from what I heard from people at `#appdesign` channel on slack). Expected behaviour was to show 404.

**Comment by lenaorobei** [comment]
@lbajsarowicz I understand you point but in this case there is no way back for customer. I believe changing url parameter is not an option for the regular user.

@naydav what do you think about it?

**Comment by lbajsarowicz** [comment]
Redirect to the first page when changing the number of items on a page is the only solution, then.

**Comment by ihor-sviziev** [comment]
@lbajsarowicz I think it should be fixed together, otherwise we'll have regression.

**Comment by lbajsarowicz** [comment]
Calling @krzksz for Code Review of `js` part.

## How it works?

### Limit change from `12` to `36`

1. page redirects to 1. page
2. page redirects to 1. page
3. page redirects to 1. page
4. page redirects to 2. page
5. page redirects to 2. page
6. page redirects to 2. page
7. page redirects to 3. page
8. page redirects to 3. page
9. page redirects to 3. page
10. page redirects to 4. page

### Limit change from `24` to `36`

1. page redirects to 1. page
2. page redirects to 1. page
3. page redirects to 2. page
4. page redirects to 2. page
5. page redirects to 3. page

### Limit change from `36` to `12`

1. page redirects to 1. page
2. page redirects to 4. page
3. page redirects to 7. page

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
Wrr... There should be confirmation for "Close" button :man_facepalming:

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

Static tests for JS should be fixed now

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

Tests were failing because for the testing purpose amount of elements displayed per page was changed, but the author of a test forgot to change default value. I also added default value and it's rollback.

<details>
<summary>Test result</summary>

image

</details>

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests CE, Integration Tests

Flaky tests (DHL + MSI)

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests CE

MSI Guys should take care of tests, finally.

**Comment by lbajsarowicz** [comment]
@magento run all tests
Merged `2.4-develop`

**Comment by lbajsarowicz** [comment]
@ihor-sviziev Ready for re-review.

**Comment by lbajsarowicz** [comment]
@krzksz Offered to provide Unit Tests for `js` changes in separate PR :-)

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
> @krzksz Offered to provide Unit Tests for `js` changes in separate PR :-)

So it is covered with basic MFTF test, but will be covered additionally with js unit test later. As for me - it’s ok

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7011](https://jira.corp.magento.com/browse/ENGCOM-7011) has been created to process this Pull Request

**Review by krzksz — APPROVED** [review]
JS part looks good to me 👍

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-7011](https://jira.corp.magento.com/browse/ENGCOM-7011) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Golf** [comment]
Need to approve new SVC failure

**Comment by ihor-sviziev** [comment]
@engcom-Golf it was already approved in https://github.com/magento/magento2/pull/26988#issuecomment-591019661

**Comment by engcom-Golf** [comment]
@ihor-sviziev yes, but not for all methods

**Comment by lbajsarowicz** [comment]
@engcom-Golf Because the rest is false-negative (don't change)

**Comment by engcom-Golf** [comment]
@lbajsarowicz 
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/service-contracts/service-to-web-service.html

**Comment by lbajsarowicz** [comment]
@engcom-Golf "All other methods do not change": https://github.com/magento/magento2/pull/26988#issuecomment-591019661

**Comment by lbajsarowicz** [comment]
@engcom-Golf Have I changed any API Interface?

**Comment by engcom-Golf** [comment]
@lbajsarowicz i'm not sure about this one 

> Note that even if the class \Magento\Customer\Api\Data\CustomerInterface is in the same namespace (or a sub-namespace) of the current class or a use statement has exists at the top of the class, the fully qualified namespace must be used or the web API throws an exception.

**Comment by lbajsarowicz** [comment]
@engcom-Golf - You have approval already for that from @buskamuza , as these imports does not affect functionality, what is confirmed with all the possible tests. 

The rule you are mentioning applies only to the interfaces exposed to WebAPI.

**Comment by engcom-Golf** [comment]
@lbajsarowicz could you please take a look at this comment https://github.com/magento/magento2/pull/26821#discussion_r382759809 ?

**Comment by lbajsarowicz** [comment]
That applies to the interfaces that can become WebAPI interfaces.
What in my PR you consider as a good candidate to become WebAPI interface?

**Comment by engcom-Golf** [comment]
as @lbajsarowicz mentioned SVC failure is approved

**Comment by ihor-sviziev** [comment]
@engcom-Golf your change was reverted by bot

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7011](https://jira.corp.magento.com/browse/ENGCOM-7011) has been created to process this Pull Request

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7011](https://jira.corp.magento.com/browse/ENGCOM-7011) has been created to process this Pull Request

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@ihor-sviziev Fixed conflicts.

**Comment by lbajsarowicz** [comment]
@magneto run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests CE, Functional Tests EE

CE: Both errors caused by failed assertions on Admin
EE: Failures related to loading mask still visible (+ 2 from CE)

**Comment by lbajsarowicz** [comment]
@magento run all tests

Still facing the issue with false negatives

**Comment by lbajsarowicz** [comment]
@magento run all tests

Still facing the issue with false negatives (failures not related to the scope of changes)

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

Updated branch to latest `2.4-develop` in hope of having all-green.

**Comment by slavvka** [comment]
@lbajsarowicz With `Other Related Pull Requests` in the description it won't be used when running tests

**Comment by lbajsarowicz** [comment]
That was changed by @lenaorobei due to your internal issues with building tools.

**Comment by lenaorobei** [comment]
As per our policy, created internal approval request [MC-32422](https://jira.corp.magento.com/browse/MC-32422).
Status - in progress.

**Comment by lenaorobei** [comment]
MC-32422 was approved, we can proceed.

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
@lbajsarowicz could you please have a look at failed static tests https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/26988/c9ab1446e911989ccfceff8ef3b92591/Statics/allure-report-b2b/index.html#suites/51d3ab4d5d77a0bc6a7ea344e9e7e6be/184a94e649ffbc26/

**Comment by lenaorobei** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by ihor-sviziev** [comment]
Looks like this PR also fixes issue from 2017: https://github.com/magento/magento2/issues/8099

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
@magento run all tests

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-7011](https://jira.corp.magento.com/browse/ENGCOM-7011) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Echo** [comment]
@magento run all tests

**Pull request merged**
