### PR TITLE
Allow daisy chaining from model setter

### PR DESCRIPTION
**Pull request by samtay**
Quick one.

### CODE REVIEW

**Comment by samtay** [comment]
@MomotenkoNatalia not sure who to tag -- originally the test wasn't passing because I forgot to update the phpdoc. Now it's all good and ready for merge.

**Comment by Vinai** [comment]
Please consider: method call chaining makes the code more cumbersome to mock and use in tests. It also makes using decorators with the class more difficult.

**Comment by adragus-inviqa** [comment]
Yeah, I can see @SamTay aiming for consistency in that class, but I'd rather not chain methods. `setHasDataChanges()` isn't used _that_ often, is it?

**Comment by samtay** [comment]
Interesting. I hadn't thought of that.. I am just used to being able to chain any "setter" methods in Magento, especially models, so it felt like the return was just forgotten on this one.

No big deal, and no it is not often used because it is a strange scenario when you need it. I will close out. Thanks for the info.

**Comment by adragus-inviqa** [comment]
@SamTay - Some info about it: https://ocramius.github.io/blog/fluent-interfaces-are-evil/

**Comment by Vinai** [comment]
@adragus-inviqa Nice link, thanks for sharing

**Pull request closed without merging**
