### PR TITLE
fix reference layout cms_noroute_index core

### LINKED ISSUE #31300: [Issue] fix reference layout cms_noroute_index core
This issue is automatically created based on existing pull request: magento/magento2#31299: fix reference layout cms_noroute_index core

---------

### Description (*)

**cms_index_noroute.xml**, It turns out the file is named incorrectly in the core, the correct file name should be **cms_noroute_index.xml**

### Manual testing scenarios (*)

1. Create Your custom theme
2. Try to override the cms_index_noroute.xml layout inside Magento_Cms.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by PierW**
### Description (*)

**cms_index_noroute.xml**, It turns out the file is named incorrectly in the core, the correct file name should be **cms_noroute_index.xml**

### Manual testing scenarios (*)

1. Create Your custom theme
2. Try to override the cms_index_noroute.xml layout inside Magento_Cms.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31300: fix reference layout cms_noroute_index core

### CODE REVIEW

**Comment by PierW** [comment]
@magento create issue

**Comment by PierW** [comment]
@magento run all test

**Comment by PierW** [comment]
@magento run all tests

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-8550](https://jira.corp.magento.com/browse/ENGCOM-8550) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Manual testing scenario:**
- Create custom module
- Try to override the cms_index_noroute.xml layout inside Magento_Cms:
```
<?xml version="1.0"?>
<!--
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="footer_links">
            <block class="Magento\Framework\View\Element\Html\Link\Current" ifconfig="contact/contact/enabled" name="contact-us-link">
                <arguments>
                    <argument name="label" xsi:type="string" translate="true">Contact Us Eddited</argument>
                    <argument name="path" xsi:type="string">contact</argument>
                </arguments>
            </block>
        </referenceBlock>
    </body>
</page>
```
:x: : **Before:**
Custom layout is not applied to `noroute/index` page

:heavy_check_mark: **After:**
Custom layout for `cms_noroute_index.xml` is applied to `noroute/index` page
#31299Pr

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Pull request merged**
