### PR TITLE
Fix Images in grid is not correctly aligned after clear filters 

### LINKED ISSUE #824: Images in grid is not correctly aligned after clear filters
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)

- Login to admin panel
- Navigate to Cms Pages
- User clicks Add New Page button
- Expand "Content" section
- User clicks "Insert Image..." button
- Click "Search Adobe Stock" button to open images grid
- Select and apply filter **Orientation=Square**
- Click **Clear All**

### Expected result (*)
Images in grid is properly aligned

### Actual result (*)
Images in grid is not correctly aligned
image

Peek 2019-12-03 16-55

### LINKED ISSUE #972: Some images on the grid are not correctly aligned if open Preview in resized browser, and then maximize the web browser
### Preconditions (*)
Magento 2.3.5-develop
Adobe-Stock-Integration 1.0.1-release

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. **(Key step )** Resize your web browser so it's on the half of the screen, for example
1. From Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**,click **Show / Hide Editor**, click **Insert Image...**
3. Click **Search Adobe Stock** and click on any image, so the Preview is displayed
4. Resize the web browser on the whole screen by double click on web browsers title bar 
grid2

### Expected result (*)
All the images on the grid are properly aligned  

### Actual result (*)
Some images in the grid are not correctly aligned
grid_align

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#824: Images in grid is not correctly aligned after clear filters
2. Fixes magento/adobe-stock-integration#972: Some images on the grid are not correctly aligned if open Preview in resized browser, and then maximize the web browser

### Manual testing scenarios (*)

- Login to admin panel
- Navigate to Cms Pages
- User clicks Add New Page button
- Expand "Content" section
- User clicks "Insert Image..." button
- Click "Search Adobe Stock" button to open images grid
- Select and apply filter **Orientation=Square**
- Click **Clear All**

### Expected result (*)
Images in grid is properly aligned

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run Database Compare

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run Static Tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magenti run Database Compare

**Comment by Nazar65** [comment]
@magento run Database Compare

**Comment by Nazar65** [comment]
@magento run Integration Tests,  Functional Tests B2B

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by Nazar65** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-7776](https://jira.corp.magento.com/browse/ENGCOM-7776) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Bravo** [comment]
✔️ QA Passed

Test on the cucumber studio - https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/4928288

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Pull request merged**
