### PR TITLE
20472 added product list price modifier

### LINKED ISSUE #20472: Special Price shown without currency symbol in magento backoffice
### Preconditions (*)
Magento 2.3.X
Magento 2.2.X

### Steps to reproduce (*)
1. Navigate to admin catalog product grid
2. Using "Columns" selection add 'Special Price' column in the grid

### Expected result (*)
Special Price will be shown with currency code

### Actual result (*)
Special Price showed without currency code. See the attached screenshot.
screenshot from 2019-01-22 14-57-27

### LINKED ISSUE #21910: Magento backend catalog "MSRP" without currency symbol
### Preconditions (*)

1. Magento 2.3.X
2. Magento 2.2.X

### Steps to reproduce (*)

1. Admin Menu > Stores > Settings > Configuration > Sales > Minimum Advertised Price = Yes
2. Navigate to admin catalog product grid
3. Using "Columns" selection, add 'Manufacturer's Suggested Retail Price'(MSRP) column in the grid

### Expected result (*)

1. "MSRP" will be shown with currency code

### Actual result (*)

Screenshot

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Added product list price modifier to modify price attributes data to price format.

### Fixed Issues
1. #20472
2. #20906
3. #21910

### Manual testing scenarios
See #20472, #20906, #21910 issues description for details.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sergiy-v** [comment]
@dmytro-ch PR is ready to review, the functional tests errors are not related to the changes.
Thank you.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7104](https://jira.corp.magento.com/browse/ENGCOM-7104) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

The currency symbol for _Special price_, _Cost_ and _MAP_ is displayed in Catalog - Products

See the screenshot made **BEFORE** switching to the PR
spec_cost_map_no currency symbol_Before PR

and **AFTER** switching to the PR
spec_cost_map_no currency symbol_After PR

**Comment by engcom-Golf** [comment]
Failed functional tests not related to the changes in this PR

**Comment by dmytro-ch** [comment]
Added "special achievement" award due to the multiple issues fixed in the scope of one PR.
@sergiy-v thank you for your efforts and the quality job done!

**Pull request merged**
