### PR TITLE
PUT /V1/products/:sku/media/:entryId does not change the file

### PR DESCRIPTION
**Pull request by Nazar65**
### Description (*)
When update product image via Api image not replaced because $entry->getFile() return null.

### Fixed Issues (if relevant)

1. magento/magento2#22402: Issue title

### Manual testing scenarios (*)
1. Send the following PUT request to "/V1/products/24-WG080/media/52"
base64_encoded_data is empty as this would bloat the issue-text

`{"entry":{"media_type":"image","label":"Label for my Image":1,"disabled":false,"types":["image","small_image","thumbnail"],"content":{"base64_encoded_data":"...","type":"image/jpeg","name":"luma-yoga-kit-2"},"id":52}}`

1. Everything provided by the request is updated for the media entity
2. The actual file-content is replaced with what is provided in the base64_encoded_data
3. The endpoint returns true

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4786](https://jira.corp.magento.com/browse/ENGCOM-4786) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Comment by philippsander** [comment]
PUT is idempotent, so I do not 100% agree with this fix as it creates a new entity with a new ID which prevents the same requests being called again.

**Comment by Nazar65** [comment]
@philippsander this fix does not create new entity, just updates entity id, as this worked before, i'm just added case with base64 encoded data

**Comment by philippsander** [comment]
ok. but still not idempotent ;-)

**Pull request merged**
