### PR TITLE
[Backport] #23354 : Data saving problem error showing when leave blank qty and update it

### PR DESCRIPTION
**Pull request by krishprakash**
### Original Pull Request 
 https://github.com/magento/magento2/pull/23360

### Description (*)

Error message added if qty field left empty when qty is updated in multishipping.
### Fixed Issues (if relevant)

1. magento/magento2#23354 : Data saving problem error showing when leave blank qty and update it

### Manual testing scenarios (*)

1. Front end -> Login into account
2. Add more than 2 products to the cart
3. From cart go to checkout with multiple addresses
4. Qty leave blank and click on Update Qty & Addresses
5. Error message "Qty field cannot be empty"

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by krishprakash** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [new Magento instance](https://pr-23612.instances.magento-community.engineering).
Admin access: [https://pr-23612.instances.magento-community.engineering/admin](https://pr-23612.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5422](https://jira.corp.magento.com/browse/ENGCOM-5422) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-5422](https://jira.corp.magento.com/browse/ENGCOM-5422) has been created to process this Pull Request
:eight_spoked_asterisk: @rogyar, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
