### PR TITLE
Ensure custom attributes don't get mangled in AbstractAddress

### LINKED ISSUE #37211: [Issue] Ensure custom attributes don't get mangled in AbstractAddress
This issue is automatically created based on existing pull request: magento/magento2#36066: Ensure custom attributes don't get mangled in AbstractAddress

---------
If Abstract Address is called with `->setCustomAttributes()` and is given an array of Attribute objects, it will convert them into an array.  When it does this, it turns the array from something like `['attribute' => Object]` to `['attribute' => ['attribute_code' => 'attribute', 'value' => 'value']]`

This eventually gets sent back through to AbstractExtensibleModel's `filterCustomAttributes` which sees it as an array, but does not see it as an indexed array, and so does not `flattECustomAttributesArrayToMap`, resulting in a Attribute object being made where the value is `['attribute_code' => 'attribute', 'value' => 'value']`.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by navarr**
If Abstract Address is called with `->setCustomAttributes()` and is given an array of Attribute objects, it will convert them into an array.  When it does this, it turns the array from something like `['attribute' => Object]` to `['attribute' => ['attribute_code' => 'attribute', 'value' => 'value']]`

This eventually gets sent back through to AbstractExtensibleModel's `filterCustomAttributes` which sees it as an array, but does not see it as an indexed array, and so does not `flattECustomAttributesArrayToMap`, resulting in a Attribute object being made where the value is `['attribute_code' => 'attribute', 'value' => 'value']`.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37211: Ensure custom attributes don't get mangled in AbstractAddress

### CODE REVIEW

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Charlie** [comment]
:heavy_check_mark: QA Passed

The PR is working fine as its mentioned in the description

When calling Abstract Address  with  ->setCustomAttributes() with params as array of Attribute objects, It is converting it into indexed array. Before this PR it will result as an array but not as an indexed array.

To check this implemented below code to get the result.

$attributes = $this->metadataService->getAllAttributesMetadata();
$addressDataNew = [];
foreach ($attributes as $attribute) {
    $addressDataNew['attribute'] = $attribute;
}
$address->setCustomAttributes( $addressDataNew );

PFA the screenshots of the debug points.

**Before:** :heavy_multiplication_x: 

image

**After:** :heavy_check_mark: 

image

image

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
As few tests are failing after rerun, moving PR to Extended Testing.

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B,Functional Tests EE, Functional Tests CE,Integration Tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
Functional CE test failures are different in recent 2 runs, hence considering them flakey.

Run 1:
image

Run 2:
image

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
It seems that bot moved this PR from Extended Testing to Ready for Testing, hence moving it back.

**Comment by engcom-Charlie** [comment]
Hi @navarr,

Can you please update the PR on the issue mentioned [above](https://github.com/magento/magento2/pull/36066#issuecomment-1494278852). Until then we can not proceed ahead with this PR.

Thank you!

**Comment by engcom-Charlie** [comment]
As explained in [comment](https://github.com/magento/magento2/pull/36066#issuecomment-1494278852), the implementation is not fully completed for this PR. 

Because of the inactivity on [this](https://github.com/magento/magento2/pull/36066#issuecomment-1501457893) comment, closing this PR for now.

Please feel free to reopen for any further updates.

Thank you!

**Pull request closed without merging**
