### PR TITLE
Fixed rest API products stockitem /V1/products?searchCriteria  #22737 

### LINKED ISSUE #22737: "/rest/V1/products?searchCriteria" API endpoint" does not return information about stock in the "extension_attributes" section
**Preconditions**

1. Magento 2.2.7 community Edition.
2. REST API filtering products using rest/V1/products?searchCriteria

**Steps to reproduce**
1. we have disable showing out of stock products from Magento Dashboard (Stores > Configuration > Catalog > Inventory > Display Out of stock products **No**)
2. we using this api to filtering product 
`/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=category_id&searchCriteria[filter_groups][0][filters][0][value]=35&searchCriteria[current_page]=1&searchCriteria[page_size]=40`

**Expected result**
1. The response contains infromation about stock per each product in the "extension_attributes" section

**Actual result**
1. There is no information about stock status per product in "extension_attributes" and no possibility to understand is it available on Storefront

### LINKED ISSUE #24418: Rest API missing “stock_item” in to the list of the products
Magento 2.3.0 rest API missing  `stock_item` in to the list of the products.

### Preconditions (*)

1. Magento 2.3.0

### Steps to reproduce (*)

1. Run product list API
2. Method: GET
3. URL: http://localhost/magentosample230/rest/V1/products?searchCriteria[pageSize]=10&searchCriteria[filter_groups][0][filters][0][field]=category_id&searchCriteria[filter_groups][0][filters][0][value]=4&searchCriteria[filter_groups][0][filters][0][condition_type]=eq

### Expected result (*)

1. `stock_item` should be included in API response.  

**API Expected Response:**

```
{
    "items": [
        {
            "id": 1,
            "sku": "24-MB01",
            "name": "Joust Duffle Bag",
            "attribute_set_id": 15,
            "price": 34,
            "status": 1,
            "visibility": 4,
            "type_id": "simple",
            "created_at": "2019-08-30 07:14:51",
            "updated_at": "2019-08-30 07:14:51",
            "extension_attributes": {
                "stock_item": {
                    "item_id": 1,
                    "product_id": 1,
                    "stock_id": 1,
                    "qty": 100,
                    "is_in_stock": true,
                    "is_qty_decimal": false,
                    "show_default_notification_message": false,
                    "use_config_min_qty": true,
                    "min_qty": 0,
                    "use_config_min_sale_qty": 1,
                    "min_sale_qty": 1,
                    "use_config_max_sale_qty": true,
                    "max_sale_qty": 10000,
                    "use_config_backorders": true,
                    "backorders": 0,
                    "use_config_notify_stock_qty": true,
                    "notify_stock_qty": 1,
                    "use_config_qty_increments": true,
                    "qty_increments": 0,
                    "use_config_enable_qty_inc": true,
                    "enable_qty_increments": false,
                    "use_config_manage_stock": true,
                    "manage_stock": true,
                    "low_stock_date": null,
                    "is_decimal_divided": false,
                    "stock_status_changed_auto": 0
                },
                "website_ids": [
                    1
                ],
                "category_links": [
                    {
                        "position": 0,
                        "category_id": "3"
                    },
                    {
                        "position": 0,
                        "category_id": "4"
                    }
                ]
            },
            "product_links": [
                {
                    "sku": "24-MB01",
                    "link_type": "crosssell",
                    "linked_product_sku": "24-WG086",
                    "linked_product_type": "simple",
                    "position": 1
                },
                {
                    "sku": "24-MB01",
                    "link_type": "crosssell",
                    "linked_product_sku": "24-WG083-blue",
                    "linked_product_type": "simple",
                    "position": 2
                },
                {
                    "sku": "24-MB01",
                    "link_type": "crosssell",
                    "linked_product_sku": "24-UG01",
                    "linked_product_type": "simple",
                    "position": 3
                },
                {
                    "sku": "24-MB01",
                    "link_type": "crosssell",
                    "linked_product_sku": "24-WG085_Group",
                    "linked_product_type": "grouped",
                    "position": 4
                },
                {
                    "sku": "24-MB01",
                    "link_type": "upsell",
                    "linked_product_sku": "24-MB02",
                    "linked_product_type": "simple",
                    "position": 1
                },
                {
                    "sku": "24-MB01",
                    "link_type": "upsell",
                    "linked_product_sku": "24-MB03",
                    "linked_product_type": "simple",
                    "position": 2
                },
                {
                    "sku": "24-MB01",
                    "link_type": "upsell",
                    "linked_product_sku": "24-MB05",
                    "linked_product_type": "simple",
                    "position": 3
                },
                {
                    "sku": "24-MB01",
                    "link_type": "upsell",
                    "linked_product_sku": "24-MB06",
                    "linked_product_type": "simple",
                    "position": 4
                },
                {
                    "sku": "24-MB01",
                    "link_type": "upsell",
                    "linked_product_sku": "24-UB02",
                    "linked_product_type": "simple",
                    "position": 5
                },
                {
                    "sku": "24-MB01",
                    "link_type": "upsell",
                    "linked_product_sku": "24-WB03",
                    "linked_product_type": "simple",
                    "position": 6
                },
                {
                    "sku": "24-MB01",
                    "link_type": "upsell",
                    "linked_product_sku": "24-WB04",
                    "linked_product_type": "simple",
                    "position": 7
                },
                {
                    "sku": "24-MB01",
                    "link_type": "upsell",
                    "linked_product_sku": "24-WB07",
                    "linked_product_type": "simple",
                    "position": 8
                }
            ],
            "options": [],
            "media_gallery_entries": [
                {
                    "id": 1,
                    "media_type": "image",
                    "label": "Image",
                    "position": 1,
                    "disabled": false,
                    "types": [
                        "image",
                        "small_image",
                        "thumbnail"
                    ],
                    "file": "/m/b/mb01-blue-0.jpg"
                }
            ],
            "tier_prices": [],
            "custom_attributes": [
                {
                    "attribute_code": "image",
                    "value": "/m/b/mb01-blue-0.jpg"
                },
                {
                    "attribute_code": "small_image",
                    "value": "/m/b/mb01-blue-0.jpg"
                },
                {
                    "attribute_code": "thumbnail",
                    "value": "/m/b/mb01-blue-0.jpg"
                },
                {
                    "attribute_code": "url_key",
                    "value": "joust-duffle-bag"
                },
                {
                    "attribute_code": "required_options",
                    "value": "0"
                },
                {
                    "attribute_code": "has_options",
                    "value": "0"
                },
                {
                    "attribute_code": "category_ids",
                    "value": [
                        "3",
                        "4"
                    ]
                },
                {
                    "attribute_code": "description",
                    "value": "<p>The sporty Joust Duffle Bag can't be beat - not in the gym, not on the luggage carousel, not anywhere. Big enough to haul a basketball or soccer ball and some sneakers with plenty of room to spare, it's ideal for athletes with places to go.<p>\n<ul>\n<li>Dual top handles.</li>\n<li>Adjustable shoulder strap.</li>\n<li>Full-length zipper.</li>\n<li>L 29\" x W 13\" x H 11\".</li>\n</ul>"
                }
            ]
        },
        {
            "id": 2,
            "sku": "24-MB04",
            "name": "Strive Shoulder Pack",
            "attribute_set_id": 15,
            "price": 32,
            "status": 1,
            "visibility": 4,
            "type_id": "simple",
            "created_at": "2019-08-30 07:14:52",
            "updated_at": "2019-08-30 07:14:52",
            "extension_attributes": {
                "stock_item": {
                    "item_id": 2,
                    "product_id": 2,
                    "stock_id": 1,
                    "qty": 100,
                    "is_in_stock": true,
                    "is_qty_decimal": false,
                    "show_default_notification_message": false,
                    "use_config_min_qty": true,
                    "min_qty": 0,
                    "use_config_min_sale_qty": 1,
                    "min_sale_qty": 1,
                    "use_config_max_sale_qty": true,
                    "max_sale_qty": 10000,
                    "use_config_backorders": true,
                    "backorders": 0,
                    "use_config_notify_stock_qty": true,
                    "notify_stock_qty": 1,
                    "use_config_qty_increments": true,
                    "qty_increments": 0,
                    "use_config_enable_qty_inc": true,
                    "enable_qty_increments": false,
                    "use_config_manage_stock": true,
                    "manage_stock": true,
                    "low_stock_date": null,
                    "is_decimal_divided": false,
                    "stock_status_changed_auto": 0
                },
                "website_ids": [
                    1
                ],
                "category_links": [
                    {
                        "position": 0,
                        "category_id": "3"
                    },
                    {
                        "position": 0,
                        "category_id": "7"
                    },
                    {
                        "position": 0,
                        "category_id": "4"
                    }
                ]
            },
            "product_links": [
                {
                    "sku": "24-MB04",
                    "link_type": "crosssell",
                    "linked_product_sku": "24-UG03",
                    "linked_product_type": "simple",
                    "position": 1
                },
                {
                    "sku": "24-MB04",
                    "link_type": "crosssell",
                    "linked_product_sku": "24-UG05",
                    "linked_product_type": "simple",
                    "position": 2
                },
                {
                    "sku": "24-MB04",
                    "link_type": "crosssell",
                    "linked_product_sku": "24-WG080",
                    "linked_product_type": "bundle",
                    "position": 3
                },
                {
                    "sku": "24-MB04",
                    "link_type": "crosssell",
                    "linked_product_sku": "24-UG04",
                    "linked_product_type": "simple",
                    "position": 4
                },
                {
                    "sku": "24-MB04",
                    "link_type": "upsell",
                    "linked_product_sku": "24-MB01",
                    "linked_product_type": "simple",
                    "position": 1
                },
                {
                    "sku": "24-MB04",
                    "link_type": "upsell",
                    "linked_product_sku": "24-MB02",
                    "linked_product_type": "simple",
                    "position": 2
                },
                {
                    "sku": "24-MB04",
                    "link_type": "upsell",
                    "linked_product_sku": "24-MB03",
                    "linked_product_type": "simple",
                    "position": 3
                },
                {
                    "sku": "24-MB04",
                    "link_type": "upsell",
                    "linked_product_sku": "24-MB05",
                    "linked_product_type": "simple",
                    "position": 4
                },
                {
                    "sku": "24-MB04",
                    "link_type": "upsell",
                    "linked_product_sku": "24-MB06",
                    "linked_product_type": "simple",
                    "position": 5
                },
                {
                    "sku": "24-MB04",
                    "link_type": "upsell",
                    "linked_product_sku": "24-UB02",
                    "linked_product_type": "simple",
                    "position": 6
                },
                {
                    "sku": "24-MB04",
                    "link_type": "upsell",
                    "linked_product_sku": "24-WB03",
                    "linked_product_type": "simple",
                    "position": 7
                },
                {
                    "sku": "24-MB04",
                    "link_type": "upsell",
                    "linked_product_sku": "24-WB04",
                    "linked_product_type": "simple",
                    "position": 8
                },
                {
                    "sku": "24-MB04",
                    "link_type": "upsell",
                    "linked_product_sku": "24-WB06",
                    "linked_product_type": "simple",
                    "position": 9
                },
                {
                    "sku": "24-MB04",
                    "link_type": "upsell",
                    "linked_product_sku": "24-WB07",
                    "linked_product_type": "simple",
                    "position": 10
                }
            ],
            "options": [],
            "media_gallery_entries": [
                {
                    "id": 2,
                    "media_type": "image",
                    "label": "Image",
                    "position": 1,
                    "disabled": false,
                    "types": [
                        "image",
                        "small_image",
                        "thumbnail"
                    ],
                    "file": "/m/b/mb04-black-0.jpg"
                },
                {
                    "id": 3,
                    "media_type": "image",
                    "label": "Image",
                    "position": 2,
                    "disabled": false,
                    "types": [],
                    "file": "/m/b/mb04-black-0_alt1.jpg"
                }
            ],
            "tier_prices": [],
            "custom_attributes": [
                {
                    "attribute_code": "image",
                    "value": "/m/b/mb04-black-0.jpg"
                },
                {
                    "attribute_code": "small_image",
                    "value": "/m/b/mb04-black-0.jpg"
                },
                {
                    "attribute_code": "special_price",
                    "value": "32.0000"
                },
                {
                    "attribute_code": "thumbnail",
                    "value": "/m/b/mb04-black-0.jpg"
                },
                {
                    "attribute_code": "special_from_date",
                    "value": "2019-08-30 07:14:52"
                },
                {
                    "attribute_code": "options_container",
                    "value": "container2"
                },
                {
                    "attribute_code": "url_key",
                    "value": "strive-shoulder-pack"
                },
                {
                    "attribute_code": "required_options",
                    "value": "0"
                },
                {
                    "attribute_code": "has_options",
                    "value": "0"
                },
                {
                    "attribute_code": "tax_class_id",
                    "value": "2"
                },
                {
                    "attribute_code": "category_ids",
                    "value": [
                        "3",
                        "7",
                        "4"
                    ]
                },
                {
                    "attribute_code": "description",
                    "value": "<p>Convenience is next to nothing when your day is crammed with action. So whether you're heading to class, gym, or the unbeaten path, make sure you've got your Strive Shoulder Pack stuffed with all your essentials, and extras as well.</p>\n<ul>\n<li>Zippered main compartment.</li>\n<li>Front zippered pocket.</li>\n<li>Side mesh pocket.</li>\n<li>Cell phone pocket on strap.</li>\n<li>Adjustable shoulder strap and top carry handle.</li>\n</ul>"
                },
                {
                    "attribute_code": "activity",
                    "value": "11,21,23,18"
                },
                {
                    "attribute_code": "style_bags",
                    "value": "27,29,30"
                },
                {
                    "attribute_code": "material",
                    "value": "32,33,36,38"
                },
                {
                    "attribute_code": "strap_bags",
                    "value": "61,62,65,66,67"
                },
                {
                    "attribute_code": "features_bags",
                    "value": "72,74,75,78"
                },
                {
                    "attribute_code": "erin_recommends",
                    "value": "1"
                },
                {
                    "attribute_code": "sale",
                    "value": "1"
                }
            ]
        }
    ]
}
```

### Actual result (*)

1. Missing `stock_item` in the API response.

**API Actual Response:**

```
{
    "items": [
        {
            "id": 1,
            "sku": "24-MB01",
            "name": "Joust Duffle Bag",
            "attribute_set_id": 15,
            "price": 34,
            "status": 1,
            "visibility": 4,
            "type_id": "simple",
            "created_at": "2019-08-30 07:14:51",
            "updated_at": "2019-08-30 07:14:51",
            "extension_attributes": {
                "website_ids": [
                    1
                ],
                "category_links": [
                    {
                        "position": 0,
                        "category_id": "3"
                    },
                    {
                        "position": 0,
                        "category_id": "4"
                    }
                ]
            },
            "product_links": [
                {
                    "sku": "24-MB01",
                    "link_type": "crosssell",
                    "linked_product_sku": "24-WG086",
                    "linked_product_type": "simple",
                    "position": 1
                },
                {
                    "sku": "24-MB01",
                    "link_type": "crosssell",
                    "linked_product_sku": "24-WG083-blue",
                    "linked_product_type": "simple",
                    "position": 2
                },
                {
                    "sku": "24-MB01",
                    "link_type": "crosssell",
                    "linked_product_sku": "24-UG01",
                    "linked_product_type": "simple",
                    "position": 3
                },
                {
                    "sku": "24-MB01",
                    "link_type": "crosssell",
                    "linked_product_sku": "24-WG085_Group",
                    "linked_product_type": "grouped",
                    "position": 4
                },
                {
                    "sku": "24-MB01",
                    "link_type": "upsell",
                    "linked_product_sku": "24-MB02",
                    "linked_product_type": "simple",
                    "position": 1
                },
                {
                    "sku": "24-MB01",
                    "link_type": "upsell",
                    "linked_product_sku": "24-MB03",
                    "linked_product_type": "simple",
                    "position": 2
                },
                {
                    "sku": "24-MB01",
                    "link_type": "upsell",
                    "linked_product_sku": "24-MB05",
                    "linked_product_type": "simple",
                    "position": 3
                },
                {
                    "sku": "24-MB01",
                    "link_type": "upsell",
                    "linked_product_sku": "24-MB06",
                    "linked_product_type": "simple",
                    "position": 4
                },
                {
                    "sku": "24-MB01",
                    "link_type": "upsell",
                    "linked_product_sku": "24-UB02",
                    "linked_product_type": "simple",
                    "position": 5
                },
                {
                    "sku": "24-MB01",
                    "link_type": "upsell",
                    "linked_product_sku": "24-WB03",
                    "linked_product_type": "simple",
                    "position": 6
                },
                {
                    "sku": "24-MB01",
                    "link_type": "upsell",
                    "linked_product_sku": "24-WB04",
                    "linked_product_type": "simple",
                    "position": 7
                },
                {
                    "sku": "24-MB01",
                    "link_type": "upsell",
                    "linked_product_sku": "24-WB07",
                    "linked_product_type": "simple",
                    "position": 8
                }
            ],
            "options": [],
            "media_gallery_entries": [
                {
                    "id": 1,
                    "media_type": "image",
                    "label": "Image",
                    "position": 1,
                    "disabled": false,
                    "types": [
                        "image",
                        "small_image",
                        "thumbnail"
                    ],
                    "file": "/m/b/mb01-blue-0.jpg"
                }
            ],
            "tier_prices": [],
            "custom_attributes": [
                {
                    "attribute_code": "image",
                    "value": "/m/b/mb01-blue-0.jpg"
                },
                {
                    "attribute_code": "small_image",
                    "value": "/m/b/mb01-blue-0.jpg"
                },
                {
                    "attribute_code": "thumbnail",
                    "value": "/m/b/mb01-blue-0.jpg"
                },
                {
                    "attribute_code": "url_key",
                    "value": "joust-duffle-bag"
                },
                {
                    "attribute_code": "required_options",
                    "value": "0"
                },
                {
                    "attribute_code": "has_options",
                    "value": "0"
                },
                {
                    "attribute_code": "category_ids",
                    "value": [
                        "3",
                        "4"
                    ]
                },
                {
                    "attribute_code": "description",
                    "value": "<p>The sporty Joust Duffle Bag can't be beat - not in the gym, not on the luggage carousel, not anywhere. Big enough to haul a basketball or soccer ball and some sneakers with plenty of room to spare, it's ideal for athletes with places to go.<p>\n<ul>\n<li>Dual top handles.</li>\n<li>Adjustable shoulder strap.</li>\n<li>Full-length zipper.</li>\n<li>L 29\" x W 13\" x H 11\".</li>\n</ul>"
                }
            ]
        },
        {
            "id": 2,
            "sku": "24-MB04",
            "name": "Strive Shoulder Pack",
            "attribute_set_id": 15,
            "price": 32,
            "status": 1,
            "visibility": 4,
            "type_id": "simple",
            "created_at": "2019-08-30 07:14:52",
            "updated_at": "2019-08-30 07:14:52",
            "extension_attributes": {
                "website_ids": [
                    1
                ],
                "category_links": [
                    {
                        "position": 0,
                        "category_id": "3"
                    },
                    {
                        "position": 0,
                        "category_id": "7"
                    },
                    {
                        "position": 0,
                        "category_id": "4"
                    }
                ]
            },
            "product_links": [
                {
                    "sku": "24-MB04",
                    "link_type": "crosssell",
                    "linked_product_sku": "24-UG03",
                    "linked_product_type": "simple",
                    "position": 1
                },
                {
                    "sku": "24-MB04",
                    "link_type": "crosssell",
                    "linked_product_sku": "24-UG05",
                    "linked_product_type": "simple",
                    "position": 2
                },
                {
                    "sku": "24-MB04",
                    "link_type": "crosssell",
                    "linked_product_sku": "24-WG080",
                    "linked_product_type": "bundle",
                    "position": 3
                },
                {
                    "sku": "24-MB04",
                    "link_type": "crosssell",
                    "linked_product_sku": "24-UG04",
                    "linked_product_type": "simple",
                    "position": 4
                },
                {
                    "sku": "24-MB04",
                    "link_type": "upsell",
                    "linked_product_sku": "24-MB01",
                    "linked_product_type": "simple",
                    "position": 1
                },
                {
                    "sku": "24-MB04",
                    "link_type": "upsell",
                    "linked_product_sku": "24-MB02",
                    "linked_product_type": "simple",
                    "position": 2
                },
                {
                    "sku": "24-MB04",
                    "link_type": "upsell",
                    "linked_product_sku": "24-MB03",
                    "linked_product_type": "simple",
                    "position": 3
                },
                {
                    "sku": "24-MB04",
                    "link_type": "upsell",
                    "linked_product_sku": "24-MB05",
                    "linked_product_type": "simple",
                    "position": 4
                },
                {
                    "sku": "24-MB04",
                    "link_type": "upsell",
                    "linked_product_sku": "24-MB06",
                    "linked_product_type": "simple",
                    "position": 5
                },
                {
                    "sku": "24-MB04",
                    "link_type": "upsell",
                    "linked_product_sku": "24-UB02",
                    "linked_product_type": "simple",
                    "position": 6
                },
                {
                    "sku": "24-MB04",
                    "link_type": "upsell",
                    "linked_product_sku": "24-WB03",
                    "linked_product_type": "simple",
                    "position": 7
                },
                {
                    "sku": "24-MB04",
                    "link_type": "upsell",
                    "linked_product_sku": "24-WB04",
                    "linked_product_type": "simple",
                    "position": 8
                },
                {
                    "sku": "24-MB04",
                    "link_type": "upsell",
                    "linked_product_sku": "24-WB06",
                    "linked_product_type": "simple",
                    "position": 9
                },
                {
                    "sku": "24-MB04",
                    "link_type": "upsell",
                    "linked_product_sku": "24-WB07",
                    "linked_product_type": "simple",
                    "position": 10
                }
            ],
            "options": [],
            "media_gallery_entries": [
                {
                    "id": 2,
                    "media_type": "image",
                    "label": "Image",
                    "position": 1,
                    "disabled": false,
                    "types": [
                        "image",
                        "small_image",
                        "thumbnail"
                    ],
                    "file": "/m/b/mb04-black-0.jpg"
                },
                {
                    "id": 3,
                    "media_type": "image",
                    "label": "Image",
                    "position": 2,
                    "disabled": false,
                    "types": [],
                    "file": "/m/b/mb04-black-0_alt1.jpg"
                }
            ],
            "tier_prices": [],
            "custom_attributes": [
                {
                    "attribute_code": "image",
                    "value": "/m/b/mb04-black-0.jpg"
                },
                {
                    "attribute_code": "small_image",
                    "value": "/m/b/mb04-black-0.jpg"
                },
                {
                    "attribute_code": "special_price",
                    "value": "32.0000"
                },
                {
                    "attribute_code": "thumbnail",
                    "value": "/m/b/mb04-black-0.jpg"
                },
                {
                    "attribute_code": "special_from_date",
                    "value": "2019-08-30 07:14:52"
                },
                {
                    "attribute_code": "options_container",
                    "value": "container2"
                },
                {
                    "attribute_code": "url_key",
                    "value": "strive-shoulder-pack"
                },
                {
                    "attribute_code": "required_options",
                    "value": "0"
                },
                {
                    "attribute_code": "has_options",
                    "value": "0"
                },
                {
                    "attribute_code": "tax_class_id",
                    "value": "2"
                },
                {
                    "attribute_code": "category_ids",
                    "value": [
                        "3",
                        "7",
                        "4"
                    ]
                },
                {
                    "attribute_code": "description",
                    "value": "<p>Convenience is next to nothing when your day is crammed with action. So whether you're heading to class, gym, or the unbeaten path, make sure you've got your Strive Shoulder Pack stuffed with all your essentials, and extras as well.</p>\n<ul>\n<li>Zippered main compartment.</li>\n<li>Front zippered pocket.</li>\n<li>Side mesh pocket.</li>\n<li>Cell phone pocket on strap.</li>\n<li>Adjustable shoulder strap and top carry handle.</li>\n</ul>"
                },
                {
                    "attribute_code": "activity",
                    "value": "11,21,23,18"
                },
                {
                    "attribute_code": "style_bags",
                    "value": "27,29,30"
                },
                {
                    "attribute_code": "material",
                    "value": "32,33,36,38"
                },
                {
                    "attribute_code": "strap_bags",
                    "value": "61,62,65,66,67"
                },
                {
                    "attribute_code": "features_bags",
                    "value": "72,74,75,78"
                },
                {
                    "attribute_code": "erin_recommends",
                    "value": "1"
                },
                {
                    "attribute_code": "sale",
                    "value": "1"
                }
            ]
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by kirtinariya1**
### Description (*)

Magento 2.3 This pull request (PR) will be merge the added stock item extension_attributes in product list rest API /rest/V1/products?searchCriteria

### Fixed Issues (if relevant)

1. Fixes #22737,  : "/rest/V1/products?searchCriteria" API endpoint" does not return information about stock in the "extension_attributes" section
2. Fixes #24418

### Manual testing scenarios (*)

1. Open the Postman
2. Add the API URL: {baseurl}/rest/V1/products?searchCriteria[filterGroups][0][filters][0][field]=category_id& searchCriteria[filterGroups][0][filters][0][value]=3& searchCriteria[filterGroups][0][filters][0][conditionType]=eq&searchCriteria[sortOrders][0][field]=price& searchCriteria[sortOrders][0][direction]=ASC

3. Method: GET
4. Authorization "Use Admin Token"
5. Check in response There is a "stock_item": object added in extension_attributes section.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — CHANGES_REQUESTED** [review]
It looks like the mentioned extension attribute is being loaded only upon the product model load

https://github.com/magento/magento2/blob/4b5626478af59cc427d76024c459bd3109ec91b9/app/code/Magento/CatalogInventory/Model/Plugin/AfterProductLoad.php#L15

and for quote items collection load

https://github.com/magento/magento2/blob/dfe3b3da39083a4159f13671d7597a809cfd2a2a/app/code/Magento/CatalogInventory/etc/events.xml#L44

I'm not sure if the provided solution is the best way since it will work only on the repository level and introduce one more dependency with the CatalogInventory module (we already have it, but nevertheless).

A more "universal" solution would be to create a separate observer in the CatalogInventory module for the product collection load. But this approach might be harmful from the performance perspective. @sidolov we definitely need your advice here. 

In the meantime @kirtinariya1 could you cover your solution by API-functional test, please? Even if we change the approach in the implementation the result will be the same and the test will suit the final solution. 

Thank you.

**Comment by kirtinariya1** [comment]
> It looks like the mentioned extension attribute is being loaded only upon the product model load
> 
> https://github.com/magento/magento2/blob/4b5626478af59cc427d76024c459bd3109ec91b9/app/code/Magento/CatalogInventory/Model/Plugin/AfterProductLoad.php#L15
> 
> and for quote items collection load
> 
> https://github.com/magento/magento2/blob/dfe3b3da39083a4159f13671d7597a809cfd2a2a/app/code/Magento/CatalogInventory/etc/events.xml#L44
> 
> I'm not sure if the provided solution is the best way since it will work only on the repository level and introduce one more dependency with the CatalogInventory module (we already have it, but nevertheless).
> 
> A more "universal" solution would be to create a separate observer in the CatalogInventory module for the product collection load. But this approach might be harmful from the performance perspective. @sidolov we definitely need your advice here.
> 
> In the meantime @kirtinariya1 could you cover your solution by API-functional test, please? Even if we change the approach in the implementation the result will be the same and the test will suit the final solution.
> 
> Thank you.

I have test API and it is working fine.

**Comment by rogyar** [comment]
Hi @kirtinariya1. I mean, according to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html). All changes should be covered by automated tests. So you need to create a new API-functional test that will perform `/V1/products` request and check that the `stock_item` is present in the response (basically, the automated test will emulate actions described in "Steps to reproduce").
Also, you may extend an [existing](\Magento\Catalog\Api\ProductRepositoryInterfaceTest) test instead of creating a new one.

**Comment by sidolov** [comment]
@rogyar , @kirtinariya1 it's not a good approach to load stock items for products, most scenarios do not require information about stock and moreover it's the responsibility of another module. We need to separate stock management and catalog, right now we have stock extension attribute for product but it's legacy approach and I prefer do not use it anymore. 

@kirtinariya1 If you need stock information you should load products with repository and load stock data in the separate request.

**Comment by jeffmowens** [comment]
We have an active support case open for this, so we're monitoring this issue as well.

> @kirtinariya1 If you need stock information you should load products with repository and load stock data in the separate request.

@sidolov ... the real world issue for us is that we sync product inventories with our internal ERP system on a 15m internal.  The REST API response is too slow when designed to iterate as you've suggested ... for performance reasons, we need to pull all relevant product data in a batch.  We can appreciate the design approach concern you mentioned... so, with that said, do you recommend a better way to pull all managed_stock = true that included stock data and product attribute information?

**Comment by gabrieldagama** [comment]
Risk is set to medium since it may affect other areas, ProductRepository is being used widely throughout the platform.

**Comment by engcom-Charlie** [comment]
Hi @kirtinariya1, please sign CLA. Otherwise, we can't proceed with your PR.
Thank you.

**Comment by engcom-Charlie** [comment]
Hi @kirtinariya1, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
