### PR TITLE
Fix Admin Customizable Options Dropdown sort_order issue

### PR DESCRIPTION
**Pull request by omiroshnichenko**
### Description (*)
Admin Customizable Options Dropdown sort_order issue

### Fixed Issues (if relevant)

1. magento/magento2#20989: Admin Customizable Options Dropdown sort_order issue

### Manual testing scenarios (*)
1. Go to Catalog > Products
2. Edit/New Product
3. Expand Customizable Options and click on Add Option
4. Choose Drop Dowm as New Option Type
5. Add 1 or 2 Values 
6 . Now , Change Option type from drop down to field or area
7. Now again choose Drop Dowm as Option Type
8. Add 1 or 2 Values 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @omiroshnichenko. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4373](https://jira.corp.magento.com/browse/ENGCOM-4373) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @omiroshnichenko , thanks for the pull request! Can you please update the branch and check if the issue is still actual, looks like it was fixed in https://github.com/magento/magento2/pull/20990

**Comment by omiroshnichenko** [comment]
Hi @sivaschenko. PR, that you mentioned, not fully fixed the problem. Empty space still present for the cell in dynamic rows. My fix will completely hide the column.

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-4373](https://jira.corp.magento.com/browse/ENGCOM-4373) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
✔️ QA passed

**Pull request merged**
