### PR TITLE
Fix #25907 - CatalogSpecialPriceStorage API delete does not delete by store id

### LINKED ISSUE #25907: CatalogSpecialPriceStorage API delete does not delete by store id
### Preconditions (*)

1. Magento 2.2.8
M 2.3.3

### Steps to reproduce (*)

1. Create multiple websites
2. Set Catalog Price Scope to Website
3. Create special price for a product on one of the websites (or both)
4. Call `V1/products/special-price-delete` API specifying one of the store_id's
price2

### Expected result (*)

1. Expect only the price with the store_id specified to be removed

### Actual result (*)

1. All special prices for that sku are removed from all stores
s-price

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#25907

### Manual testing scenarios (*)

Please check fixed issue for testing scenario

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Bartlomiejsz** [comment]
@magento run all tests

**Comment by Bartlomiejsz** [comment]
@magento run WebAPI Tests, Functional Tests EE

**Comment by swnsma** [comment]
@magento run WebAPI Tests, Functional Tests EE

**Comment by swnsma** [comment]
Hi @Bartlomiejsz,
It looks like that failed WebAPI Tests are related to current PR.
Could you check it?

**Comment by Bartlomiejsz** [comment]
Sure, I'll check that

**Comment by Bartlomiejsz** [comment]
@magento run all tests

**Comment by Bartlomiejsz** [comment]
@magento run WebAPI Tests

**Comment by Bartlomiejsz** [comment]
@magento run WebAPI Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by swnsma** [comment]
Hi @Bartlomiejsz,
Are you planing to continue to work with current PR?

**Comment by swnsma** [comment]
Hi @Bartlomiejsz,

I am closing PR due to inactivity.
Please feel free to re-open it and continue your work.
Thank you!

**Pull request closed without merging**
