### PR TITLE
fixed - Old categories are not removed at CSV import

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)
There was an issue regarding csv import in Admin. When we select update option then first it should remove the old categories.
There was a check in code if (Import::BEHAVIOR_APPEND != $this->getBehavior()) at line 1367 in class Magento\CatalogImportExport\Model\Import\Product.
I think this check is not required because if it is new product then there will be no category assigned to product and if it is existing product then we should remove old categories first then assign new categories.

### Fixed Issues (if relevant)

1. magento/magento2#15273: Old categories are not removed at CSV import

### Manual testing scenarios (*)

1. Assign 2 or 3 categories to product in Admin.
2. choose add/update in product import section
3. In CSV file assign only some new category.
4. Now there should be new categories on product but you will see old and new categories on product.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by slavvka** [comment]
Hey @rahulwebkul Thank you for the contribution! We want all issues to be fixed firstly in 2.3 so please create the up-port to 2.3. After it is delivered we will process this one.

**Comment by ghost** [comment]
@slavvka - i already created a pull request for 2.3 issue
https://github.com/magento/magento2/pull/18898

**Comment by ghost** [comment]
@slavvka - is there any update required from my end?

**Comment by slavvka** [comment]
@rahulwebkul Please fix the failing integration tests

**Comment by ghost** [comment]
@slavvka @VladimirZaets - I will check the integration test and fix it.

**Comment by slavvka** [comment]
Closed due to inactivity. Please feel free to reopen once you decide to proceed.

**Pull request closed without merging**
