### PR TITLE
fix: #14495 Allow custom varchar attributes for customer grid

### LINKED ISSUE #14495: Customer export not work with custom attribute
### Preconditions

Version 2.0.18:
php 5.6 & 7.0;
Mysql Ver 14.14 Distrib 5.1.73;

Version 2.1.12:
php 5.6 & 7.0;
Mysql Ver 14.14 Distrib 5.1.73;

Version 2.2.3:
php 7.0 & 7.1;
Mysql Ver 14.14 Distrib 5.1.73;

Version 2.3.0-dev:
php 7.0 & 7.1;
Mysql Ver 14.14 Distrib 5.1.73;

### Steps to reproduce

1. Create customer custom attribute with type int [like there](https://github.com/nans/MagentoBug/blob/master/Setup/InstallData.php) 
2. Add field to customer grid by [customer_listing.xml](https://github.com/nans/MagentoBug/blob/master/view/adminhtml/ui_component/customer_listing.xml)
3. Create customers (2 or more) with new attributes (check table customer_entity_int on records);
4. Try to export
4.1 Do not check customer ids checkboxes and press on button Export -> CSV -> Export
Actual result: bug
Expected result: csv file with data
4.2 Select some customers and press on button Export -> CSV -> Export
Actual result: bug
Expected result: csv file with data
4.3 Choose all customers and press on button Export -> CSV -> Export
Actual result: csv file with data;
Expected result: csv file with data

### Bug reports
[ver. 2.0.18](https://github.com/nans/MagentoBug/blob/master/doc/Magento%20ver.%202.0.18.txt)  
[ver. 2.1.12](https://github.com/nans/MagentoBug/blob/master/doc/Magento%20ver.%202.1.12.txt)  
[ver. 2.2.3](https://github.com/nans/MagentoBug/blob/master/doc/Magento%20ver.%202.2.3.html)  
[ver. 2.3.0-dev](https://github.com/nans/MagentoBug/blob/master/doc/Magento%20ver.%202.3.0-dev.html)

### PR DESCRIPTION
**Pull request by amenk**
See the issues #14495 for details

### Fixed Issues (if relevant)

1. Fixes magento/magento2#14495
2. 
### Manual testing scenarios (*)

1. ...
3. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [no] All new or changed code is covered with unit/integration tests (if applicable)
 - [no] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [t.b.d] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by amenk** [comment]
@magento run all tests

**Comment by swnsma** [comment]
@magento run all tests

**Review by swnsma — CHANGES_REQUESTED** [review]
Hi @amenk,
Thank you for your contribution!

Could you please check failed test, seems it may have relation to functionality you are changing.

**Comment by amenk** [comment]
Failing test: https://github.com/magento/magento2/blob/1c553ec1de9774c3eca4e94c815f11c9e70c50b8/app/code/Magento/Customer/Test/Unit/Ui/Component/Listing/ColumnsTest.php#L160

**Comment by amenk** [comment]
@magento run Unit Tests

**Comment by amenk** [comment]
Unit test are green now
@magento run all tests

**Comment by amenk** [comment]
@magento run Functional Tests CE

**Comment by swnsma** [comment]
@magento run Functional Tests B2B,Functional Tests CE

**Comment by swnsma** [comment]
@magento run Functional Tests B2B

**Review by swnsma — APPROVED** [review]

**Comment by engcom-Echo** [comment]
@amenk @swnsma 
Thanks for the collaboration & contribution!


:heavy_check_mark: QA Passed
fix: #14495 Allow custom varchar attributes for customer grid

**Manual Scenario Steps**
[Steps to Reproduce ](https://github.com/magento/magento2/issues/14495#issuecomment-919028336)
1. Add new customer attribute whose code is varchar_attribute, Input Type => Text Field, Add to Column Options => Yes, Use in Filter Options => Yes.
2. Define the varchar_attribute in the customer_listing.xml  in sample module
3. Flush cache and reindex 
4. Export the customer data at the Customer listing page.


**Before:** :heavy_multiplication_x: 
image


**After:** :heavy_check_mark: 
Able to export customers.
image

Hence moving to `Merge In Progress`

**Comment by engcom-Charlie** [comment]
It seems bot moved this PR from Merge in Progress to Ready for Testing hence moving it back.

**Pull request merged**
