### PR TITLE
Adds missing return value in afterSave plugin.

### LINKED ISSUE #29034: Missing return value in Magento\CmsUrlRewrite\Plugin\Cms\Model\Store\View::afterSave can cause saving a storeview to crash
### Preconditions (*)
1. Tested on a vanilla Magento 2.3.5 and 2.4-develop (commit 735579d8aa14f7275d92818848f4a405191e7cb2) instance 

### Steps to reproduce (*)
1. Setup a vanilla Magento installation
2. In the backend, go to Stores > All Stores
3. Open the 'Default Store View'
4. Save the storeview, no need to change anything, notice that this works fine
5. Now simulate we installed a bunch of custom modules which changes the sort order of certain Magento modules in the `app/etc/config.php` file, so manually change that file so `Magento_CatalogUrlRewrite` comes later then `Magento_CmsUrlRewrite`:
```diff
--- app/etc/config.php	2020-07-08 11:42:38.000000000 +0200
+++ app/etc/config2.php	2020-07-08 11:42:35.000000000 +0200
@@ -30,7 +30,6 @@
         'Magento_Payment' => 1,
         'Magento_CatalogRuleGraphQl' => 1,
         'Magento_CatalogRule' => 1,
-        'Magento_CatalogUrlRewrite' => 1,
         'Magento_StoreGraphQl' => 1,
         'Magento_Widget' => 1,
         'Magento_Quote' => 1,
@@ -39,6 +38,7 @@
         'Magento_CmsGraphQl' => 1,
         'Magento_EavGraphQl' => 1,
         'Magento_CmsUrlRewrite' => 1,
+        'Magento_CatalogUrlRewrite' => 1,
         'Magento_CmsUrlRewriteGraphQl' => 1,
         'Magento_User' => 1,
         'Magento_Msrp' => 1,
```
6. Flush the caches: `bin/magento cache:flush` (do **not** run `bin/magento setup:upgrade` because it will revert the changes you just did)
7. In the backend, go to Stores > All Stores and open the 'Default Store View' again
8. Save the storeview again and notice it throws the following error:
```
TypeError: Argument 2 passed to Magento\CatalogUrlRewrite\Model\Category\Plugin\Store\View::afterSave() must be an instance of Magento\Store\Model\ResourceModel\Store, null given, called in lib/internal/Magento/Framework/Interception/Interceptor.php on line 146 and defined in app/code/Magento/CatalogUrlRewrite/Model/Category/Plugin/Store/View.php:103 Stack trace:
#0 lib/internal/Magento/Framework/Interception/Interceptor.php(146): Magento\CatalogUrlRewrite\Model\Category\Plugin\Store\View->afterSave(Object(Magento\Store\Model\ResourceModel\Store\Interceptor), NULL, Object(Magento\Store\Model\Store\Interceptor))
#1 lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Store\Model\ResourceModel\Store\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Store\Model\Store\Interceptor))
#2 generated/code/Magento/Store/Model/ResourceModel/Store/Interceptor.php(86): Magento\Store\Model\ResourceModel\Store\Interceptor->___callPlugins('save', Array, Array)
#3 lib/internal/Magento/Framework/Model/AbstractModel.php(654): Magento\Store\Model\ResourceModel\Store\Interceptor->save(Object(Magento\Store\Model\Store\Interceptor))
#4 lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\Model\AbstractModel->save()
#5 lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Store\Model\Store\Interceptor->___callParent('save', Array)
...
```

### Expected result (*)
1. Storeview gets saved without errors
2. All after plugins should return a value, in this case [Magento\CmsUrlRewrite\Plugin\Cms\Model\Store\View::aftersSave](https://github.com/magento/magento2/blob/2.3.5/app/code/Magento/CmsUrlRewrite/Plugin/Cms/Model/Store/View.php#L73-L80) is missing one

### Actual result (*)
1. Saving a storeview results in an error
2. The after plugin is missing a return value

### Discussion
Error was introduced in Magento 2.3.4 by [MC-18561](https://github.com/magento/magento2/commit/3696290a2e9c90ac48dca6c2020135a067f79538)

Following patch seems to resolve the issue:
```diff
--- vendor/magento/module-cms-url-rewrite/Plugin/Cms/Model/Store/View.php   2020-01-10 06:20:40.000000000 +0100
+++ /vendor/magento/module-cms-url-rewrite/Plugin/Cms/Model/Store/View.php   2020-07-08 11:25:17.000000000 +0200
@@ -67,16 +67,18 @@
      * @param ResourceStore $object
      * @param ResourceStore $result
      * @param ResourceStore $store
-     * @return void
+     * @return ResourceStore
      * @SuppressWarnings(PHPMD.UnusedFormalParameter)
      */
-    public function afterSave(ResourceStore $object, ResourceStore $result, AbstractModel $store): void
+    public function afterSave(ResourceStore $object, ResourceStore $result, AbstractModel $store): ResourceStore
     {
         if ($store->isObjectNew() || $store->dataHasChangedFor('group_id')) {
             $this->urlPersist->replace(
                 $this->generateCmsPagesUrls((int)$store->getId())
             );
         }
+
+        return $result;
     }

     /**
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

(Not sure if S0 is correct here, creating a storeview feels like critical functionality, but I'm fine with S2 as well ...)

### PR DESCRIPTION
**Pull request by hostep**
### Description (*)
All after plugins should always return a value, so other plugins which follow them in the stack get the correct input parameters instead of `null`.
It appears that in [MC-18561](https://github.com/magento/magento2/commit/3696290a2e9c90ac48dca6c2020135a067f79538) this was forgotten and this can cause crashes when the sort order of default Magento modules are different then in a vanilla installation (which can happen after installing certain custom modules)

See #29034 for more information

The bug was introduced in Magento 2.3.4, so it makes sense if this PR is considered to be backported to 2.3 as well

I have no interest in adding additional automatic tests for this and wouldn't even know how to approach this, so if this is required, somebody else will need to take care of this.

Thanks!

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/29034

### Manual testing scenarios (*)
See https://github.com/magento/magento2/issues/29034

### Questions or comments
Not sure if this is possible, but having a static analyser test to detect after plugins without return values could have prevented this mistake to have entered the code base

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hostep** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @hostep,
Your changes looks good. Could you cover them with unit test?

**Comment by hostep** [comment]
Hi @ihor-sviziev, please re-read my opening post, sorry I simply don't have the time for tests.

**Comment by ihor-sviziev** [comment]
@hostep got it, I just missed point related to tests.

@engcom-Charlie @engcom-Kilo @engcom-Golf could you help covering this case with unit tests?

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7814](https://jira.corp.magento.com/browse/ENGCOM-7814) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Setup a vanilla Magento installation
2. In the backend, go to Stores > All Stores
3. Open the 'Default Store View'
4. Save the storeview, no need to change anything, notice that this works fine
5. Now simulate we installed a bunch of custom modules which changes the sort order of certain Magento modules in the `app/etc/config.php` file, so manually change that file so `Magento_CatalogUrlRewrite` comes later then `Magento_CmsUrlRewrite`:
```diff
--- app/etc/config.php	2020-07-08 11:42:38.000000000 +0200
+++ app/etc/config2.php	2020-07-08 11:42:35.000000000 +0200
@@ -30,7 +30,6 @@
         'Magento_Payment' => 1,
         'Magento_CatalogRuleGraphQl' => 1,
         'Magento_CatalogRule' => 1,
-        'Magento_CatalogUrlRewrite' => 1,
         'Magento_StoreGraphQl' => 1,
         'Magento_Widget' => 1,
         'Magento_Quote' => 1,
@@ -39,6 +38,7 @@
         'Magento_CmsGraphQl' => 1,
         'Magento_EavGraphQl' => 1,
         'Magento_CmsUrlRewrite' => 1,
+        'Magento_CatalogUrlRewrite' => 1,
         'Magento_CmsUrlRewriteGraphQl' => 1,
         'Magento_User' => 1,
         'Magento_Msrp' => 1,
```
6. Flush the caches: `bin/magento cache:flush` (do **not** run `bin/magento setup:upgrade` because it will revert the changes you just did)
7. In the backend, go to Stores > All Stores and open the 'Default Store View' again
8. Save the storeview again 

**Before:** :heavy_multiplication_x: Throws the following error:

Screenshot from 2020-07-10 09-51-49

After: :heavy_check_mark: Store view gets saved without errors and plugin returns a value, in this case Magento\CmsUrlRewrite\Plugin\Cms\Model\Store\View::aftersSave is missing one

Screenshot from 2020-07-10 11-40-56

**Pull request merged**
