### PR TITLE
Fixed saving asset keywords links with db prefix

### LINKED ISSUE #1810: Asset keywords links are not saved with database prefix
### Preconditions (*)
Install Magento with database prefix

### Steps to reproduce (*)
Upload asset with keywords in metadata
Save asset from adobe stock (preview/licensed)
Edit uploaded asset and add keywords

### Expected result (*)
Operations should be performed successfully. Keywords for asset as saved and displayed in View Details panel.

### Actual result (*)
Asset keywords links are not saved.

### PR DESCRIPTION
**Pull request by sivaschenko**
### Description (*)

Fixed saving asset keywords links with db prefix

### Fixed Issues (if relevant)

Fixes https://github.com/magento/adobe-stock-integration/issues/1810

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sivaschenko** [comment]
The scenarions are covered with autotests, but the builds with db prefix are not currently running on the PRs.

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Tested the basic functionality on a Magento instance installed with `--db-prefix`
- saving image preview from Adobe Stock
- Uploading images containing metadata
- View Image Details
- Edit image Tate, Description, Add Keywords
- Create and Delete folders
- Delete images
- Switching between Old and New Media Gallery

No issues found

**Comment by sivaschenko** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8151](https://jira.corp.magento.com/browse/ENGCOM-8151) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
@magento run Static Tests

**Pull request merged**
