### PR TITLE
Fix incorrect php version check in bootstrap

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
In the bootstrap, we have a wrong check that potentially allows running Magento on PHP 7.3 that isn't supported.
My PR fixes this issue.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by andrewbess — APPROVED** [review]
Hello @ihor-sviziev 
Thank you for your contribution
Great catch

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, thank you for the review.
[ENGCOM-9347](https://jira.corp.magento.com/browse/ENGCOM-9347) has been created to process this Pull Request
:eight_spoked_asterisk: @andrewbess, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests CE

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Have Magento already installed.

2. Make sure php 7.3 version is running


**Manual testing scenario:**

1. Just for better error message visibility- place the echo message and die statement in the bootstrap class as shown in below screenshot.
Screenshot 2022-01-05 at 4 09 58 PM


2. Run flush command from Magento root folder and check the error message
 
3. Pull the PR changes and re execute the same flush command and cross check the error message


**Before:** :heavy_multiplication_x: There was no PHP version support message defined

**After:** :heavy_check_mark: There is a PHP version support message displayed appropriately

Screenshot 2022-01-05 at 4 15 25 PM

Since it is a fix relevant to PHP version support, there is no additional regression testing required.

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests CE

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests CE

**Pull request merged**
