### PR TITLE
magento/magento2#: Remove a redundant PHP5 directives from .htaccess

### PR DESCRIPTION
**Pull request by atwixfirster**
### Description (*)

PR removes directives for `mod_php5.c` from `.htaccess` file since Magento 2 supports > PHP 7.x.x

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7012](https://jira.corp.magento.com/browse/ENGCOM-7012) has been created to process this Pull Request

**Review by lbajsarowicz — APPROVED** [review]
Nice catch. Thanks for contribution.
Could you also check other projects (PageBuilder / EE / B2B) for such entries in .htaccess files?

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7012](https://jira.corp.magento.com/browse/ENGCOM-7012) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
