### PR TITLE
The loader blocks the shipping methods after the postcode is changed, shipping rates validation rules

### LINKED ISSUE #38742: [Issue] The loader blocks the shipping methods after the postcode is changed, shipping rates validation rules
This issue is automatically created based on existing pull request: magento/magento2#38726: The loader blocks the shipping methods after the postcode is changed, shipping rates validation rules

---------

### Description (*)
In instance where we have custom shipping methods without shipping rates validation rules, the loader blocks the shipping methods after the postcode is changed in the shipping address during checkout and does not disappear.

**File:** `vendor/magento/module-checkout/view/frontend/web/js/model/shipping-rates-validator.js`

image

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by mattkrupnik**
### Description (*)
In instance where we have custom shipping methods without shipping rates validation rules, the loader blocks the shipping methods after the postcode is changed in the shipping address during checkout and does not disappear.

**File:** `vendor/magento/module-checkout/view/frontend/web/js/model/shipping-rates-validator.js`

image

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38742: The loader blocks the shipping methods after the postcode is changed, shipping rates validation rules

### CODE REVIEW

**Comment by mattkrupnik** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hello,

Internal team has started to work on it.

Thanks.

**Comment by hostep** [comment]
For some reason, this PR wasn't marked as merged, even though the code was merged (via [cherry-picking](https://github.com/magento/magento2/commit/341f8c0a51938414c32bf5d28a3a84b353f87b65)) recently as part of this bigger merge: https://github.com/magento/magento2/commit/1bafc5712abd635395f0bcfe24ea3f198c18f615

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-11993 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-11993&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta1.

Thanks

**Pull request closed without merging**
