### PR TITLE
make magento framework LoggerProxy comaptible with psr/log

### LINKED ISSUE #36083: Cannot set custom filename for \Psr\Log\LoggerInterface
### Preconditions and environment

- 2.4.3-p1

### Steps to reproduce

1. Create a helper class that is used for example on a cli command or a cron job that requires a custom logger filename

```php
use Magento\Catalog\Model\Product\Attribute\Source\Status;
use Magento\Catalog\Model\ResourceModel\Product\CollectionFactory;
use Magento\Framework\App\Area;
use Magento\Framework\App\Filesystem\DirectoryList;
use Magento\Framework\DB\Select;
use Magento\Store\Model\App\Emulation;
use Monolog\Handler\StreamHandler;
use Psr\Log\LoggerInterface;

class Product
{
    protected $collectionFactory;
    protected $directoryList;
    protected $emulation;
    /** @var LoggerInterface */
    protected $logger;
    protected $productResource;

    public function __construct(CollectionFactory                            $collectionFactory,
                                Emulation                                    $emulation,
                                LoggerInterface                              $logger,
                                DirectoryList                                $directoryList,
                                \Magento\Catalog\Model\ResourceModel\Product $productResource)
    {
        $this->directoryList = $directoryList;
        $this->emulation = $emulation;
        $this->collectionFactory = $collectionFactory;
        $this->productResource = $productResource;
        $this->logger = $logger;
        $logger->info("Initializing logger");
        $this->logger->pushHandler(
            new StreamHandler($this->directoryList->getRoot() . '/var/log/ioweb_product_number.log')
        );
    }

    /**
     * @return LoggerInterface
     */
    public function getLogger(): LoggerInterface
    {
        return $this->logger;
    }

}
```

In your cli command or cron job try to invoke this logger 

```php
                $this->productHelper->getLogger()->info(
                    sprintf(
                        "Saving product %s: %s with product number %s",
                        $item->getId(),
                        $item->getSku(),
                        $paddedNumber
                    )
                );
```

You face an exception 

```php
PHP Fatal error:  Uncaught Error: Call to undefined method Magento\Framework\Logger\LoggerProxy::pushHandler() in /httpdocs/app/code/Ioweb/ProductAutomation/Helper/Product.php:41
Stack trace:
#0 /httpdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Ioweb\ProductAutomation\Helper\Product->__construct()
#1 /httpdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#2 /httpdocs/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#3 /httpdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(170): Magento\Framework\ObjectManager\ObjectManager->get()
#4 /httpdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(276): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument()
#5 /httpdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(239): Magento\Framework\Obje in /httpdocs/app/code/Ioweb/ProductAutomation/Helper/Product.php on line 41
```

By looking at the generated code for the proxy 

```php
<?php
namespace Psr\Log\LoggerInterface;

/**
 * Proxy class for @see \Psr\Log\LoggerInterface
 */
class Proxy implements \Psr\Log\LoggerInterface, \Magento\Framework\ObjectManager\NoninterceptableInterface
{
    /**
     * Object Manager instance
     *
     * @var \Magento\Framework\ObjectManagerInterface
     */
    protected $_objectManager = null;

    /**
     * Proxied instance name
     *
     * @var string
     */
    protected $_instanceName = null;

    /**
     * Proxied instance
     *
     * @var \Psr\Log\LoggerInterface
     */
    protected $_subject = null;

    /**
     * Instance shareability flag
     *
     * @var bool
     */
    protected $_isShared = null;

    /**
     * Proxy constructor
     *
     * @param \Magento\Framework\ObjectManagerInterface $objectManager
     * @param string $instanceName
     * @param bool $shared
     */
    public function __construct(\Magento\Framework\ObjectManagerInterface $objectManager, $instanceName = '\\Psr\\Log\\LoggerInterface', $shared = true)
    {
        $this->_objectManager = $objectManager;
        $this->_instanceName = $instanceName;
        $this->_isShared = $shared;
    }

    /**
     * @return array
     */
    public function __sleep()
    {
        return ['_subject', '_isShared', '_instanceName'];
    }

    /**
     * Retrieve ObjectManager from global scope
     */
    public function __wakeup()
    {
        $this->_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    }

    /**
     * Clone proxied instance
     */
    public function __clone()
    {
        $this->_subject = clone $this->_getSubject();
    }

    /**
     * Get proxied instance
     *
     * @return \Psr\Log\LoggerInterface
     */
    protected function _getSubject()
    {
        if (!$this->_subject) {
            $this->_subject = true === $this->_isShared
                ? $this->_objectManager->get($this->_instanceName)
                : $this->_objectManager->create($this->_instanceName);
        }
        return $this->_subject;
    }

    /**
     * {@inheritdoc}
     */
    public function emergency($message, array $context = [])
    {
        return $this->_getSubject()->emergency($message, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function alert($message, array $context = [])
    {
        return $this->_getSubject()->alert($message, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function critical($message, array $context = [])
    {
        return $this->_getSubject()->critical($message, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function error($message, array $context = [])
    {
        return $this->_getSubject()->error($message, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function warning($message, array $context = [])
    {
        return $this->_getSubject()->warning($message, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function notice($message, array $context = [])
    {
        return $this->_getSubject()->notice($message, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function info($message, array $context = [])
    {
        return $this->_getSubject()->info($message, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function debug($message, array $context = [])
    {
        return $this->_getSubject()->debug($message, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function log($level, $message, array $context = [])
    {
        return $this->_getSubject()->log($level, $message, $context);
    }
}
```

I notice that the pushHandler method is not availble. 
However on the actual subject the method is available 

Moreover by checking previous Magento versions like 2.3.2 this was possible because of this preference 

```xml
<preference for="Psr\Log\LoggerInterface" type="Magento\Framework\Logger\Monolog" />
```

Now this has been changed to 

```xml
    <preference for="Psr\Log\LoggerInterface" type="Magento\Framework\Logger\LoggerProxy" />
```

Forcing us to use the proxy thus disabling the ability to set custom filenames for logs 

### Expected result

We can use pushHandler to set the filename for the log. Custom logs are important. 

### Actual result

We can no longer use custom log filenames with Monolog and have to use a workaround by using Zend_Logger

```php
        $writer = new \Zend_Log_Writer_Stream(BP . '/var/log/filename.log');
        $logger = new \Zend_Log();
        $logger->addWriter($writer);
```

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### LINKED ISSUE #38583: LoggerProxy breaking contract with Psr\Log\LoggerInterface
### Preconditions and environment

- Magento version 2.4.7-beta3

The class `\Magento\Framework\Logger\LoggerProxy` is not compatible with the interface, it is implementing (`Psr\Log\LoggerInterface`). In `2.4.7-beta3`, types were added to the arguments of the implemented functions. This breaks the contract and we get a fatal error. I'm not 100% sure, when the error comes up. For me, it occurs when running `bin/magento setup:upgrade`. But it could be, that something needs to be logged during this, to occur.

### Steps to reproduce

1. run `bin/magento setup:upgrade` 

### Expected result

Command runs without error.

### Actual result

Command breaks with error:
```
Fatal error: Declaration of Magento\Framework\Logger\LoggerProxy::emergency(Stringable|string $message, array $context = []): void must be compatible with Psr\Log\LoggerInterface::emergency($message, array $context = []) in /var/www/html/vendor/magento/framework/Logger/LoggerProxy.php on line 110
```

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Bashev**
### Description (*)
Issue comes if some of the third-party modules have requirements limited only to version `^1.0` of the `psr/log` module. Correct way is if magento not support it, to define it in the proper way in the composer.json as requirement, not leave this option to the installer.

Most of the time issue will comes if you are updating magento from previous version (for example 2.4.7-beta2) where changes from commit https://github.com/magento/magento2/commit/28d2a5bf4bd3588dfe6f0d3d0fc2036c6fcc9ef7 are not applied.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36083
2. Fixes magento/magento2#38583

### Manual testing scenarios (*)

1. Install magento 2.4.7-beta2 or earlier version.
3. Add `"psr/log": "^1.0"` in the project composer.json file.
4. Update to version 2.4.7-beta3
5. Open magento in the browser. Probably needs to see something which need to be logged. (debug.log is good to be enabled).

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Bashev** [comment]
@magento run all tests

**Comment by Bashev** [comment]
@magento run Functional Tests B2B Functional Tests EE WebAPI Tests

**Comment by Bashev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by Bashev** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by Bashev** [comment]
@magento run Functional Tests B2B

**Comment by Bashev** [comment]
@magento run Functional Tests B2B

**Comment by hostep** [comment]
Thanks @Bashev, good spotted.

Also ran into this problem when trying out 2.4.7-beta3 on one of our shops. This contraint will significantly help in exposing 3rd party modules that aren't compatible with 2.4.7
Priority of this PR should be increased to P1 in my opinion and this PR should get included in Magento 2.4.7 GA preferably.

I think we will also have to add this same contraint in `lib/internal/Magento/Framework/composer.json`, for modules requiring the framework module for CI systems that don't install a full magento installation.

**Comment by Bashev** [comment]
Thank you for suggestion, @hostep 
I'm absolutely agree this must be part of the framework and I already added there also.

**Comment by Bashev** [comment]
@magento run all tests

**Comment by Bashev** [comment]
@magento run all tests

**Comment by hostep** [comment]
It looks like this did get merged in 2.4.7 GA: https://github.com/magento/magento2/commits/2.4.7/lib/internal/Magento/Framework/composer.json

It just hasn't been merged in the `2.4-develop` branch yet, otherwise this PR would already have been shown as merged.

Thanks again @Bashev!

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Thanks @hostep,

Since this PR has been merged with version 2.4.7 but has not yet been synced with 2.4-develop, we're placing it 'On Hold'. We'll proceed to close this PR once the merge between 2.4.7 and 2.4-develop occurs.

Thank you.

**Comment by hostep** [comment]
[The merge](https://github.com/magento/magento2/commit/e6fc0ca2d4f380951f606f15715c904b25ec9002) did happen a couple of days ago and contains this fix, so I guess we can close this now?

**Comment by engcom-Hotel** [comment]
Thanks @hostep,

We have verified the merge, hence closing this PR.

**Pull request closed without merging**
