### PR TITLE
A configurable product will not have a parent.

### PR DESCRIPTION
**Pull request by sheepfy**
As title says: A configurable product should not have a parent, only children. Unless Magento wants to add this new feature of configurable product with configurable children.

If you take a look at the code changes, everything should be straight forward.

What's happens in current version:
On product listing, we have the cache tags. And we only add the parent cache tag in requests.

What's happens in after this PR:
On product listing, we now have cache tags of parent product + it's children.

Impact? Edit & save from admin children of the configurable. Cache invalidation request will contain only cache tags of the edited child product => cache will not be invalidated to the parent product.

### CODE REVIEW

**Review by Den4ik — CHANGES_REQUESTED** [review]
Hi @sheepfy 
Thanks for your PR.
Update make sense but could you please add description where you faced with the problem?
Also it would be good to have some tests for this changes

**Comment by sheepfy** [comment]
@Den4ik try edit a child product then check listing cache invalidation. It will never happen, cache tag will never be added, because configurable product have children, not parents.

**Comment by sdzhepa** [comment]
@sheepfy 

Could you please update the **ticket Description section** with:
- detailed problem explanation and impact on user flows
- steps to reproduce this issue

Without this information, we are not able to process and merge this Pull Request

Thank in advance

**Comment by sheepfy** [comment]
@sdzhepa  I've updated PR description

**Comment by sidolov** [comment]
@megento run tests

**Comment by sidolov** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by sheepfy** [comment]
> Hi @sheepfy
> Thanks for your PR.
> Update make sense but could you please add description where you faced with the problem?
> Also it would be good to have some tests for this changes

Test case:
Edit configurable product, wait for scheduled reindex, check changes on a cached page. 
Cache is never invalidated because configurable product will never have a parent product
... :|

**Pull request closed without merging**
