### PR TITLE
[MFTF] StorefrontReorderAsGuestCustomerTest refactoring

### PR DESCRIPTION
**Pull request by AnnaAPak**
This PR is to refactor StorefrontReorderAsGuestCustomerTest according to the best practices

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by AnnaAPak** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by sidolov** [comment]
@magento run Functional Tests CE

**Comment by sidolov** [comment]
@magento run Functional Tests CE

**Review by sidolov — APPROVED** [review]

**Pull request merged**
