### PR TITLE
FIX ISSUE 34086

### PR DESCRIPTION
**Pull request by sheepfy**
FIX ISSUE 34086 FIX ISSUE 34086

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
If this is being deleted then any reference to the class must also surely be removed?

This processor is included in the module di.xml at line 204 - section 
`<type name="Magento\ConfigurableProduct\Model\ResourceModel\Product\Indexer\Price\Configurable">`

I won't run all the tests yet as I suspect we will get fails.

**Comment by sheepfy** [comment]
@BarnyShergold, yes, indeed.
That's not all of it, so this can be picked up by anyone to continue. 
That class is needed to be removed, also the one from multi inventory. Also from di, and so on.

I will remove them sometime in the future. Untill then, if someone else got the time, can proceed.


Also, this class vendor/magento/module-catalog-inventory/Model/Indexer/ProductPriceIndexFilter.php is not working for configurable products, here is a code snippet to create a new modifier under configurable products module after removing that processor.

`    /**
     * @inheritdoc
     */
    public function modifyPrice(IndexTableStructure $priceTable, array $entityIds = []): void
    {
        if ($this->stockConfiguration->isShowOutOfStock()) {
            return;
        }

        if (!$entityIds) {
            $this->doDelete($priceTable);
            return;
        }

        foreach (array_chunk($entityIds, $this->batchSize) as $chunk) {
            $this->doDelete($priceTable, $chunk);
        }
    }

    /**
     * @param IndexTableStructure $priceTable
     * @param int[] $entityIds
     * @throws LocalizedException
     * @throws \Zend_Db_Statement_Exception
     */
    private function doDelete(IndexTableStructure $priceTable, array $entityIds = []): void
    {
        $connection = $this->resourceConnection->getConnection($this->connectionName);
        $select = $this->selectOutOfStockConfigurableProducts($connection, $entityIds);
        $productIds = [];
        $result = $connection->query($select)->fetchAll() ?: [];
        foreach ($result as $row) {
            $productIds[] = $row['parent_id'];
        }

        if ($productIds) {
            $where = [$priceTable->getEntityField() . ' IN (?)' => $productIds];
            $connection->delete($priceTable->getTableName(), $where);
        }
    }

    /**
     * @param AdapterInterface $connection
     * @param int[] $entityIds
     * @return Select
     * @throws LocalizedException
     */
    private function selectOutOfStockConfigurableProducts(AdapterInterface $connection, array $entityIds = []): Select
    {
        $select = $connection->select();
        $select->from(
            ['stock_item' => $this->stockItem->getMainTable()],
            ['l.parent_id', 'MAX(stock_item.is_in_stock) as max_is_in_stock']
        );

        $select->joinInner(
            ['l' => $connection->getTableName('catalog_product_super_link')],
            'l.product_id = stock_item.product_id',
            []
        );

        if ($this->stockConfiguration->getManageStock()) {
            $select->where('stock_item.use_config_manage_stock = 1 OR stock_item.manage_stock = 1');
        } else {
            $select->where('stock_item.use_config_manage_stock = 0 AND stock_item.manage_stock = 1');
        }

        if ($entityIds) {
            $select->where('l.parent_id in (?)', $entityIds, \Zend_Db::INT_TYPE);
        }

        $select->where('l.parent_id > 0');
        $select->group('l.parent_id');
        $select->having('max_is_in_stock = 0');

        return $select;
    }`

**Comment by sheepfy** [comment]
@BarnyShergold also, a quicker way could be to revert this one:
https://github.com/magento/magento2/commit/7ee934df7e141f0b9285fc8ec3f1532e6f8f95ef

**Comment by orlangur** [comment]
@magento run Functional Tests CE, Integration Tests, Magento Health Index, Static Tests, Unit Tests, WebAPI Tests, Semantic Version Checker

**Comment by orlangur** [comment]
Hm, ok, looks like this logic wasn't even covered with a test.

**Review by orlangur — CHANGES_REQUESTED** [review]
You cannot just remove part of a code.

Such change will cause a regression of problem where this code was introduced https://github.com/magento/magento2/commit/7ee934df7e141f0b9285fc8ec3f1532e6f8f95ef

Please develop a proper fix which covers both old case and the new broken scenario you have reported.

**Comment by sheepfy** [comment]
As i previously mentioned: That commit needs to be reverted: https://github.com/magento/magento2/commit/7ee934df7e141f0b9285fc8ec3f1532e6f8f95ef

But never mind, I'm closing this

**Comment by orlangur** [comment]
@sheepfy,

>  That commit needs to be reverted: 7ee934d

Nope, it doesn't as it solves a particular problem which was tested. Good luck with future bugfixes in a proper way.

**Pull request closed without merging**
