### PR TITLE
multiple category relation fix.

### PR DESCRIPTION
**Pull request by senders**
It seems to me that "relation.category_id = ?" is wrong.
In circumstances there could be more than on category_id and so I am getting the following error:
Cardinality violation: 1241 Operand should contain 1 column(s).

For example without that patch I am getting the following error which produces that error:
SELECT url_rewrite.*, relation.category_id, relation.product_id FROM url_rewrite LEFT JOIN catalog_url_rewrite_product_category AS relation ON url_rewrite.url_rewrite_id = relation.url_rewrite_id WHERE (url_rewrite.entity_id IN ('17643')) AND (url_rewrite.entity_type IN ('product')) AND (url_rewrite.store_id IN (4)) AND (relation.category_id = '9', '21')

After applying my patch, I am getting this sql which is working fine:
SELECT url_rewrite.*, relation.category_id, relation.product_id FROM url_rewrite LEFT JOIN catalog_url_rewrite_product_category AS relation ON url_rewrite.url_rewrite_id = relation.url_rewrite_id WHERE (url_rewrite.entity_id IN ('17643')) AND (url_rewrite.entity_type IN ('product')) AND (url_rewrite.store_id IN (4)) AND (relation.category_id IN ('9', '21'))

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by BarnyShergold** [comment]
@magento run all tests
@senders - Thanks for your first submission - can you please sign the Adobe CLA? You only need to do this once.

**Comment by BarnyShergold** [comment]
@senders - Seems the code sniff is now complaining about the class description being too short and just describing itself.

Whilst this is not your issue - if you could add a short sentence in the comment (lines 14-16) describing the model then we should get the tests passed

**Comment by Den4ik** [comment]
@senders please sign cla

**Comment by BarnyShergold** [comment]
@senders - If you don't sign the CLA or add the comment to the class in the next few days, we'll have to close this PR for inactivity....

**Pull request closed without merging**
