### PR TITLE
[MFTF] Updating with AdminOpenCreateBundleProductPageActionGroup

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
Tests have been updated with AdminOpenCreateBundleProductPageActionGroup

https://github.com/magento/magento2/pull/33526

Please, note: the test is dependent on https://github.com/magento/magento2/pull/33526

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Semantic Version Checker, Functional Tests CE

**Comment by AnnaAPak** [comment]
@magento run Semantic Version Checker, Functional Tests CE

**Comment by AnnaAPak** [comment]
@magento run all tests

**Review by sidolov — CHANGES_REQUESTED** [review]
@AnnaAPak please, resolve merge conflicts

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Comment by engcom-Charlie** [comment]
Hi @AnnaAPak,

Thank you for your contribution!

I am looking into the build failure.

Thank you

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
I have merged latest 2.4-develop into this PR branch.

The Functional B2B test which is in broken state now, is not part of the PR changes or not failing because of any PR related change. Hence moving the PR in Merge in Progress.

Below test is failing

app/code/Magento/PageBuilder/Test/Mftf/Test/AdminPageBuilderSlideItemAppearanceCollageCenterTest/SlideItemCollageCenterCanInlineEditContentWhenIn25PercentWidthColumnTest.xml

Thank you!

**Pull request merged**
