### PR TITLE
Fix exception handling inconsistency between developer and production modes

### LINKED ISSUE #38639: [Issue] Fix exception handling inconsistency between developer and production modes
This issue is automatically created based on existing pull request: magento/magento2#37712: Fix exception handling inconsistency between developer and production modes

---------
### Description (*)
During developing our custom module was found an issue in the developer mode, for example, after implementing `\Magento\Customer\Controller\AccountInterface` class into the custom controller we got redirected to the login page (as was expected), but on the production on the same flow we got an `internal server error 500`.
It happened because the redirect URL was set to the response before the trigger exception and as a result `Location` header was sent to the browser and the browser redirect to the login page instead of the page with an exception message.
It's not expected flow between developer and production modes and can cause some issues for production.

### Preconditions and environment
- Magento 2.4.5 
- Controller, which sets a redirect and throws an exception

### Steps to reproduce
1. Create a module:
 
`app/code/Vendor/Module/registration.php`: 
```php
<?php

use Magento\Framework\Component\ComponentRegistrar;

ComponentRegistrar::register(ComponentRegistrar::MODULE, 'Vendor_Module', __DIR__);

``` 
`app/code/Vendor/Module/etc/module.xml`:
```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="Vendor_Module"/>
</config>

```
`app/code/Vendor/Module/etc/frontend/routes.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:App/etc/routes.xsd">
    <router id="standard">
        <route id="vendor" frontName="vendor">
            <module name="Vendor_Module"/>
        </route>
    </router>
</config>

```
`magento2/app/code/Vendor/Module/Controller/Example/Index.php`:
```php
<?php

namespace Vendor\Module\Controller\Example;

use LogicException;
use Magento\Customer\Model\Session;
use Magento\Framework\App\Action\HttpGetActionInterface;
use Magento\Framework\App\ResponseInterface;
use Magento\Framework\Controller\ResultInterface;
use Magento\Framework\Exception\SessionException;

class Index implements HttpGetActionInterface
{
    public function __construct(private readonly Session $customerSession,)
    {
    }

    /**
     * Execute action based on request and return result
     *
     * @return ResultInterface|ResponseInterface
     * @throws LogicException
     * @throws SessionException
     */
    public function execute()
    {
        // Here, you will be redirected to the login page when not logged in.
        $this->customerSession->authenticate();

        throw new LogicException(__('Some exception text'));
    }
}

```
2. Go to `www.domain.com/vendor/example`

### Expected result

- Page with exception text like this one:

Capture 2023-07-04 at 14 15 49

### Actual result

- Redirect to the login page

Unfortunately, I don't have enough experience with test coverage, will be great if someone covers this case by test.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by iGerchak**
### Description (*)
During developing our custom module was found an issue in the developer mode, for example, after implementing `\Magento\Customer\Controller\AccountInterface` class into the custom controller we got redirected to the login page (as was expected), but on the production on the same flow we got an `internal server error 500`.
It happened because the redirect URL was set to the response before the trigger exception and as a result `Location` header was sent to the browser and the browser redirect to the login page instead of the page with an exception message.
It's not expected flow between developer and production modes and can cause some issues for production.

### Preconditions and environment
- Magento 2.4.5 
- Controller, which sets a redirect and throws an exception

### Steps to reproduce
1. Create a module:
 
`app/code/Vendor/Module/registration.php`: 
```php
<?php

use Magento\Framework\Component\ComponentRegistrar;

ComponentRegistrar::register(ComponentRegistrar::MODULE, 'Vendor_Module', __DIR__);

``` 
`app/code/Vendor/Module/etc/module.xml`:
```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="Vendor_Module"/>
</config>

```
`app/code/Vendor/Module/etc/frontend/routes.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:App/etc/routes.xsd">
    <router id="standard">
        <route id="vendor" frontName="vendor">
            <module name="Vendor_Module"/>
        </route>
    </router>
</config>

```
`magento2/app/code/Vendor/Module/Controller/Example/Index.php`:
```php
<?php

namespace Vendor\Module\Controller\Example;

use LogicException;
use Magento\Customer\Model\Session;
use Magento\Framework\App\Action\HttpGetActionInterface;
use Magento\Framework\App\ResponseInterface;
use Magento\Framework\Controller\ResultInterface;
use Magento\Framework\Exception\SessionException;

class Index implements HttpGetActionInterface
{
    public function __construct(private readonly Session $customerSession,)
    {
    }

    /**
     * Execute action based on request and return result
     *
     * @return ResultInterface|ResponseInterface
     * @throws LogicException
     * @throws SessionException
     */
    public function execute()
    {
        // Here, you will be redirected to the login page when not logged in.
        $this->customerSession->authenticate();

        throw new LogicException(__('Some exception text'));
    }
}

```
2. Go to `www.domain.com/vendor/example`

### Expected result

- Page with exception text like this one:

Capture 2023-07-04 at 14 15 49

### Actual result

- Redirect to the login page

Unfortunately, I don't have enough experience with test coverage, will be great if someone covers this case by test.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38639: Fix exception handling inconsistency between developer and production modes

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by ihor-sviziev** [comment]
Test failures look not related

**Comment by ihor-sviziev** [comment]
https://github.com/magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @iGerchak,

Thank you for your contribution!

In order to proceed further on this PR, I have followed the mentioned steps on 2.4-develop but it seems that issue is not reproducible now.
1. Created a custom module "testmodule"
2. Added routes.xml, modules.xml and new controller app/code/Magento/TestModule/Controller/Example/Index.php 
3. Browsed http://mag.local/testmodule/example/  
As per Expected Result, we can see the page with exception text like below

image

Can you please check the issue on latest 2.4-develop and confirm once. Till then moving this to On Hold.

Thank you!

**Comment by engcom-Charlie** [comment]
Hi [@iGerchak](https://github.com/iGerchak),

Thank you for your contribution!

In order to proceed further on this PR, I have followed the mentioned steps on 2.4-develop on developer mode
	1	Created a custom module "testmodule"
	2	Added routes.xml, modules.xml and new controller app/code/Magento/TestModule/Controller/Example/Index.php
	3	Browsed http://mag.local/testmodule/example/ 

### :heavy_check_mark: QA Passed

**Before:** :heavy_multiplication_x: 
- Redirecting to the login page
image


**After:** :heavy_check_mark:  
- Getting exception on the page 

image

Since the build is failing, currently moving it further in Extended Testing.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by engcom-Charlie** [comment]
The functional B2B and EE failures have the known failures.

**Functional B2B:** 
**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37712/9132d7e4a49068c8a0a2977a4d826d01/Functional/allure-report-b2b/index.html
image

**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37712/9c7b16036658f8d75502389e3fd473a0/Functional/allure-report-b2b/index.html#categories/e89a2ef77b192fa659586970627a6e4a/a1eea1172de15ef4/
image

1. [ACQE-6438](https://jira.corp.adobe.com/browse/ACQE-6438) - StorefrontPropertiesOfAProductAttributeTest
2. [ACQE-6350](https://jira.corp.adobe.com/browse/ACQE-6350) - AdminCreateDraftQuoteFromQuoteGridPageWithMultipleStoresTest

**Functional EE:** 
**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37712/a4e316f92a3a2031c745d9d1dcd0d888/Functional/allure-report-ee/index.html#categories
image

**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37712/c2604ac0673482dd549faf0c62ae530e/Functional/allure-report-ee/index.html#categories/a7df4cfd57312ca5beb274709fcea00b/51dd779f96f52de0/

image

1. [ACQE-6349 ](https://jira.corp.adobe.com/browse/ACQE-6349)- AdminContentHierarchyDisabledScopeWebsiteFilterTest
2. [ACQE-6438](https://jira.corp.adobe.com/browse/ACQE-6438) - StorefrontPropertiesOfAProductAttributeTest
3. [ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331) - StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest

**Comment by engcom-Charlie** [comment]
@magento run WebAPI Tests

**Comment by engcom-Charlie** [comment]
The WebAPI test failures in recent 2 runs are different. Also the test failure in recent run is a known failure. It is not failing because of this PR changes hence moving it to Merge in Progress.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37712/7d714a34f5249ec2ef21cbdf52987c1f/WebApi/console-error-logs.html
image

image

**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37712/6cc33d3a0fd45b539562081ff8412aa5/WebApi/console-error-logs.html
image

[AC-11750 ](https://jira.corp.adobe.com/browse/AC-11750)- testGetCustomerDescendingSortedOrders

**Comment by engcom-Charlie** [comment]
@magento create issue

**Pull request merged**
