### PR TITLE
#25300 Mobile view issue on category page - Sort By label overlaps

### PR DESCRIPTION
**Pull request by akartavtsev**
### Description (*)

The changed margin of sorter for mobile view.

### Fixed Issues (if relevant)

1. magento/magento2#25300: Mobile view issue on category page - Sort By label overlaps with Shop By button

### Manual testing scenarios (*)

1. Create one category
2. Assign 2, 3 products in the category.
3. Now in mobile view open category page on frontend
Note:
- View category page in iPhone 5 or on 320px screen size.
- If shop by option is not appearing on the category page then try to add more product and attribute in products to activate the layered navigation.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by nuzil** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @nuzil. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @nuzil, here is your [new Magento instance](https://pr-26381.instances.magento-community.engineering).
Admin access: [https://pr-26381.instances.magento-community.engineering/admin](https://pr-26381.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by nuzil — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-6607](https://jira.corp.magento.com/browse/ENGCOM-6607) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@akartavtsev thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
