### PR TITLE
Unselect multiselect on product edit view

### PR DESCRIPTION
**Pull request by syno-dlr**
Fix for issue #8577 : https://github.com/magento/magento2/issues/8577

Preconditions
Install Magento 2
Create a product with a multiselect attribute AND selected values.
Save It

Steps to reproduce
Unselect ALL values
Save product again

Expected result
All values should be unselected.

Actual result
Previous values are still selected.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=8578) <br/>All committers have signed the CLA.

**Comment by vrann** [comment]
@damien-synolia cannot reproduce, it works as expected on the latest mainline. Which version your fix is for?

**Comment by syno-dlr** [comment]
Hey vrann !

I tested on the community edition 2.1.4 with sample data (from Magento Website).

Damien.

**Comment by vrann** [comment]
@damien-synolia can you please verify do you observe the issue on the latest develop branch? Please attach screenshots if you do.

Just checked with the sample data installed and the following result is consistent with the expected.
screen shot 2017-03-02 at 1 54 10 pm

**Comment by vrann** [comment]
@damien-synolia closing this PR, please feel free to open a new one if issue is reproducible on the mainline

**Comment by vrann** [comment]
@damien-synolia there is related issue #7687, it was fixed in the mainline and being backported to the 2.1

**Comment by redelschaap** [comment]
This issue is still present in 2.1.5 and not fixed by the solution given in the commit referenced in #7687.

**Pull request closed without merging**
