### PR TITLE
Fixed use inconsistently viewModels in codebase

### LINKED ISSUE #31525: [Issue] Fixed use inconsistently viewModels in codebase
This issue is automatically created based on existing pull request: magento/magento2#31503: Fixed use inconsistently viewModels in codebase

---------

### Description (*)

Replace viewModel by view_model in codebase! Somewhere in code developers use both approach view_model and viewModel. This can lead to inconsistent and make more noise for dev experience
Just refactor a little code

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

CC @dmytro-ch pr update related docs update

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Replace viewModel by view_model in codebase! Somewhere in code developers use both approach view_model and viewModel. This can lead to inconsistent and make more noise for dev experience
Just refactor a little code

For make consistently in code we should refactor both in code base and devdocs! To guide developers/3rd-party extensions providers following standards and reduce confusing. We already have PR for devdocs in here

https://github.com/magento/devdocs/pull/8459

This PR refactor inconsistenly parts from codebase

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

No issue available

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

CC @dmytro-ch pr update related docs update

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31525: Fixed use inconsistently viewModels in codebase

### CODE REVIEW

**Comment by dmytro-ch** [comment]
Related PR in DevDocs: https://github.com/magento/devdocs/pull/8459

**Comment by sidolov** [comment]
@magento create issue

**Comment by hostep** [comment]
This is a backwards-incompatible change in my opinion. If you use the `breadcrumbs.phtml` template provided by Magento in your own xml layout for a new custom block, it will crash after the change of this PR is applied because you'd first need to update your own xml as well with this new name.

Consistency is good, but these are just names, in my opinion the first one should even be called `breadcrumbs_view_model` and not `view_model` which is too generic, I think we should leave these as-is and close the PR.

@nathanjosiah: have you guys already decided BiC rules around these sort of changes?

**Comment by nathanjosiah** [comment]
Yes this is now considered BiC under our new policy. Unfortunately this hasn't been documented yet and has historically been a grey area. We have very large policy changes coming that would even further block this kind of change but at least for now this definitely wouldn't be allowed.

ℹ️  For internal reference this was decided in the dev guild in https://github.com/magento-commerce/development-guild/issues/23 we also have a related issue here https://github.com/magento-commerce/development-guild/issues/80

**Comment by mrtuvn** [comment]
re-target to 2.5-develop

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi,
Can we add the same argument with 2 keys - as `viewModel` and as `view_model` for backward compatibility reasons? I think in such a case, it could be targeted even to 2.4-develop.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Review by dmytro-ch — APPROVED** [review]
The functional test failures are not related to the changes introduced by this PR.

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-8712](https://jira.corp.magento.com/browse/ENGCOM-8712) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
Hi @mrtuvn,

We are closing this PR.The PR is in Draft since longtime.

Once you are ready Please feel free to reopen it to process the PR further.

Thanks

**Pull request closed without merging**
