### PR TITLE
REVERT for public PR:22917

### PR DESCRIPTION
**Pull request by VladimirZaets**
### Description (*)
This PR reverts #22917 as it caused regression. More details in test report https://github.com/magento/magento2/pull/28380#issuecomment-634634953

Purpose for revert
During internal regression testing for future 2.4.0 release Core team found two regression bugs
1. [MC-34245] Adding a Product with Customizable Option to Wish List results in a fatal error
2. [MC-34322] Adding a Product with Customizable Option to a "Gift Registry" results in a fatal error when loading shared Gift Registry page

Root cause analysis defined that changes from #22917  brought these regression bugs.

After multiple discussion and several attempts to fix consequences was decided to revert this PR #22917

As soon as PR will be reverted related Issue https://github.com/magento/magento2/issues/22856 will be reopened, confirmed again. The internal Jira ticket will be reopened/created for 2.4.x as well.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

### Case 1 
**_[MC-34245] Adding a Product with Customizable Option to Wish List results in a fatal error_**

**Preconditions:**

-  Magento 2.4-develop CE;
-  A Simple Product with Customizable option is created:
   (for example, `Option Title = Test, Option Type = Text, Field, Max Characters = 100`);
-  A Customer account is created;

**Manual testing scenario:**

1. Go to Storefront as the created Customer;
2. Go to the created Product page;
3. Enter some valid text into the `Test` input field ;
4. Click the “**Add to Wish List**” button ;

**Before:** :heavy_multiplication_x: Error: Maximum function nesting level of "250"...

Screenshot from 2020-05-27 14-10-33

**After:** :heavy_check_mark: The created product was added to Wish List 

Screenshot from 2020-05-27 14-03-31

### _Case 2 [MC-34322] Adding a Product with Customizable Option to a "Gift Registry" results in a fatal error when loading shared Gift Registry page_ 

**Preconditions:**

-  Magento 2.4-develop EE;
-  A Customer account is created; 
-  A Gift Registry is created;
-  A Simple Product with Customizable option is created
(for example, `Option Title = Test, Option Type = Text, Field, Max Characters = 100`) 
-  Add the created Product to the Gift Registry;

**Manual testing scenario:**

1. Go to Storefront as the created Customer;
2. Go to the created Gift Registry (My Account -> Gift Registry); 
3. Click the “**Share**” link;
4. Fill all required fields with valid data; 
5. Click on the “**Share Gift Registry**” button;
6. Open the message sent to the email, used to share Gift Registry; 
7. Click the “**Registry Location**” link;

**Before:** :heavy_multiplication_x: Error: Maximum function nesting level of "250"...

Screenshot from 2020-05-27 12-56-34

**After:** :heavy_check_mark: “**Gift Registry Items**” grid contain the created Product 

Screenshot from 2020-05-27 13-50-02

**Review by sdzhepa — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, thank you for the review.
[ENGCOM-7595](https://jira.corp.magento.com/browse/ENGCOM-7595) has been created to process this Pull Request
:eight_spoked_asterisk: @sdzhepa, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by ihor-sviziev** [comment]
Hi @VladimirZaets @sdzhepa,
Could you next time write some meaningful description? Motivation of this PR isn't clear at all.

**Comment by sdzhepa** [comment]
Hi @ihor-sviziev 

Sorry, its my bad. I will add additional information to the description today.
But in general, you are right - this fix leads to the new bugs.  These bugs were found by Core team during regression. After several discussions and review was decided to revert this PR

**Comment by lenaorobei** [comment]
Delivered to 2.4.0-develop.

**Pull request closed without merging**
