### PR TITLE
Fixed LayeredNavigation color filter show only loader for out of stock product

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

Fixed LayeredNavigation color filter show only loader for out of stock product
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
color filter with LayeredNavigation show only loader for out of stock product

### Manual testing scenarios (*)

1. magento 2.3 with sample data
2. set configurable product out of stock, make sure child is in stock
3. Display Out of Stock Products set to Yes
4. select color witch available in configurable product

###Actual result (*)
color filter show  loader for out of stock product and give  console error
 "swatch-renderer.js:1264 Uncaught TypeError: $(...).AddFotoramaVideoEvents is not a function"
Screenshot from 2019-09-25 19-39-12

###Expected result (*)
listing page not showing swatch for out of stock product same as a product detail page
and loader not showing with filter
Screenshot from 2019-09-25 19-52-24

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5954](https://jira.corp.magento.com/browse/ENGCOM-5954) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by ihor-sviziev** [comment]
Hi @ravi-chandra3197,

Seems like solution isn't fully correct as it prevents rendering product details even if it's not "color swatches". The issue appeared in the color swatches module, so we have to fix the issue in it by adding such change to the following file https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Swatches/view/frontend/templates/product/listing/renderer.phtml.

**Comment by ihor-sviziev** [comment]
Just created issue for this improvement https://github.com/magento/magento2/issues/29286

**Pull request merged**
