### PR TITLE
Rest API, endpoint products-render-info and image generation

### PR DESCRIPTION
**Pull request by okolya**
### Description (*)
This issue is relevant when products are listed using **Rest API** and endpoint **"products-render-info"**

When searchCriteria contains several SKUs for searching then only the 1st image has correct source url. 

All other images have wrong image url, such as: *static/version1569935518/frontend/_view/de_DE/Magento_Catalog/images/product/placeholder/.jpg*

The line with setting DesignTheme should be before image iteretion, otherwise parent theme would be lost during frontend emulation.

#### Steps
1. Prepare Rest API call with more than two SKU.

> https://domain.com/rest/V1/products-render-info?searchCriteria[filterGroups][0][filters][0][field]=sku&searchCriteria[filterGroups][0][filters][0][value]=11111,22222&searchCriteria[filterGroups][0][filters][0][conditionType]=in&storeId=1&currencyCode=EUR

2. Only the 1st product would have the correct image urls.

#### Result

Other products have wrong images

Rest API Answer

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by okolya** [comment]
@magento give me test instanc

**Comment by okolya** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @okolya. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @okolya, here is your [new Magento instance](https://pr-24810.instances.magento-community.engineering).
Admin access: [https://pr-24810.instances.magento-community.engineering/admin](https://pr-24810.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sidolov** [comment]
Hi @okolya  please, sign CLA, otherwise, we can't process your pull request

**Comment by okolya** [comment]
@sidolov CLA is signed. Should pull request be closed and created againg?

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-6030](https://jira.corp.magento.com/browse/ENGCOM-6030) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@okolya thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA passed

**Comment by VladimirZaets** [comment]
Hi @okolya, thanks for collaboration. I reverted your last commit with doc block because:
1) We don't need to declare doc block because interface already contain doc block with full required data
2) According to the interface ( and implementation also), the method returns void

**Comment by magento-engcom-team** [comment]
@okolya thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by okolya** [comment]
@VladimirZaets Without comment it is not possible to pass all Static Tests

**Pull request merged**
