### PR TITLE
Add path verification to Mediagallery uploader plugin

### LINKED ISSUE #30649: Cannot Import Products when Enable Old Media Gallery is set to No
### Preconditions (*)

1. Magento 2.4.1 CE
2. PHP 7.4

### Steps to reproduce (*)

1. Set Enable Old Media Gallery to "NO" in STORES > CONFIGURATION > SYSTEM > ADVANCED
2. Go to System > Import
3. Import valid CSV of products (no images defined)

### Expected result (*)

1. Products to be validated and imported successfully

### Actual result (*)

1. Validation fails - exception "The file cannot be uploaded".
2. CSV is uploaded to var/importexport
3. Products are not imported
Screenshot from 2020-10-26 16-20-42

### When Enable Old Media Gallery is set to "YES"
1. Import the same, valid csv product file
2. Products are validated and imported successfully
Screenshot from 2020-10-26 16-03-09

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#30649

### Manual testing scenarios (*)

1.     Set Enable Old Media Gallery to "NO" in STORES > CONFIGURATION > SYSTEM > ADVANCED
2.     Go to System > Import
3.     Import valid CSV of products (no images defined)
4. 

    Products to be validated and imported successfully

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the pull request @Nazar65 ! Can you please add an integration test covering the `\Magento\Framework\File\Uploader::save` with media and non-media destionation

**Comment by Nazar65** [comment]
I'm still working on test coverage :)

**Comment by engcom-Charlie** [comment]
@Nazar65 I will take care of test coverage.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8467](https://jira.corp.magento.com/browse/ENGCOM-8467) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Set Enable Old Media Gallery to "NO" in STORES > CONFIGURATION > SYSTEM > ADVANCED
2. Go to System > Import
3. Import valid CSV of products (no images defined)

**Before:** :heavy_multiplication_x: Validation fails - exception "The file cannot be uploaded".

Screenshot from 2020-11-17 11-16-52

**After:** :heavy_check_mark: Products were validated and imported successfully

Screenshot from 2020-11-17 11-21-38
Screenshot from 2020-11-17 12-16-17

_**Note:**_ @Nazar65 @sivaschenko @sidolov  We have errors in the `exception.log` file when importing products with images. 
But these errors are not caused by changes from this PR.

Screenshot from 2020-11-17 12-11-38

**Comment by sivaschenko** [comment]
@engcom-Alfa can you please open an issue describing the discovered exception

**Comment by engcom-Alfa** [comment]
@sivaschenko The issue with the description of the detected exception has been created - #30978

**Pull request merged**
