### PR TITLE
Fix typo in README file

### PR DESCRIPTION
**Pull request by shochdoerfer**
### Description (*)
Fix typo in README file.

### Manual testing scenarios (*)
No manual testing needed.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9236](https://jira.corp.magento.com/browse/ENGCOM-9236) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
Testing is not required

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. View the file \magento2\app\code\Magento\Weee\README.md

2. Check the line no 64 if that has a frontend spelled mistake

**Before:** :heavy_multiplication_x: _frantend_ text was existing

**After:** :heavy_check_mark:  _frontend_ text was existing

The PR just has an update relevant to the spelling mistake from the README.md file, hence no other additional testing is required.

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9236](https://jira.corp.magento.com/browse/ENGCOM-9236) has been created to process this Pull Request

**Pull request merged**
