### PR TITLE
Additional condition in getRegion() method

### LINKED ISSUE #22556: VatValidator::validate returns error if region in quoteAddress is not set
There is an issue in \Magento\Quote\Observer\Frontend\Quote\Address\VatValidator::validate method.
Magento adds additional data to $quoteAddress object and throws an error during $quoteAddress->save(); if regionId in the address is not set.

### Preconditions (*)

1. Magento 2.3.0+
2. Configured taxes for EU
3. Enable Automatic Assignment to Customer Group is set to "Yes" and configured
4. Allow to Choose State if It is Optional for Country is set to "Yes"

### Steps to reproduce (*)

1. Configure taxes in the admin panel (e.g. for Germany and Austria)
2. Enable Automatic Assignment to Customer Group
3. Create a test customer account
4. Set customer address, region field should be empty, enter valid vat number
5. Add any product to cart
6. Go to the checkout

### Expected result (*)

1. Magento should validate the vat number and display the proper information (shipping methods, totals)

### Actual result (*)

1. Magento throws error in the checkout: "Internal Error. Details are available in Magento log file. Report ID: webapi-5cc8155d027de"
2. Report in logs: "Notice: Array to string conversion in /{path}/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3102"

### PR DESCRIPTION
**Pull request by Leone**
### Description (*)

Fixes #22556, #12612

Added additional condition in getRegion() method to prevent Magento from throwing error in VatValidator::validate method.

### Fixed Issues (if relevant)

1. magento/magento2#22556: VatValidator::validate returns error if region in quoteAddress is not set
2. magento/magento2#12612: Array to String conversion error on checkout page when changin country

### Manual testing scenarios (*)

1. Configure taxes in the admin panel (e.g. for Germany and Austria)
2. Enable Automatic Assignment to Customer Group
3. Create a test customer account
4. Set customer address, region field should be empty, enter valid vat number
5. Add any product to cart
6. Go to the checkout

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22558) <br/>All committers have signed the CLA.

**Review by orlangur — CHANGES_REQUESTED** [review]
@Leone please cover corresponding case with automated test.

**Comment by hostep** [comment]
@Leone: could you verify if this would also fix https://github.com/magento/magento2/issues/12612?
Steps to reproduce can be found in https://github.com/magento/magento2/issues/12612#issuecomment-364233451

If this PR fixes that issue as well, then you may edit your initial post and add that ticket to the list of Fixed Issues.

Thanks!

**Comment by Leone** [comment]
@orlangur thank you for feedback, I added automated test to this PR.

@hostep you're right. I have checked #12612 issue and this PR will fix that issue as well. I updated the first post.

**Review by orlangur — APPROVED** [review]
Great @Leone!

Thanks for your attention to existing issues, @hostep 😉

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-5026](https://jira.corp.magento.com/browse/ENGCOM-5026) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@Leone thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5026](https://jira.corp.magento.com/browse/ENGCOM-5026) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Comment by Leone** [comment]
This Travis fail is false-positive

**Pull request merged**
