### PR TITLE
Add $data array as property to Magento\Backend\App\Action\Plugin\Authentication

### PR DESCRIPTION
**Pull request by nickolasburr**
### Description (*)

Add $data array property to Magento\Backend\App\Action\Plugin\Authentication. This makes it easier to use DI to extend the class.

### Fixed Issues (if relevant)

1. N/A

### Manual testing scenarios (*)

1. Create basic module with class that extends `Magento\Backend\App\Action\Plugin\Authentication`
2. Add `output` method to subclass, which will `var_dump` the `$data` array
3. Add subclass `<preference>` in `etc/di.xml`
4. Add subclass `<type>` with arbitrary arguments given to `$data` in `etc/di.xml`
5. Call `output` method to display the given DI arguments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20152) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @nickolasburr. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by kandy** [comment]
Your change doesn't make any sense for me. Can you explain what you try to achieve?
Also, pay attention that we do not recommend to extend core classes

**Comment by nickolasburr** [comment]
In certain situations where you may need to change the mode of authentication for an admin user, it is necessary to override this class. The proposed change is to allow overriding this class without having to also override the constructor by allowing the passing of arbitrary data via the `$data` property.

**Comment by kandy** [comment]
But why you do not want to override constructor?

**Comment by nickolasburr** [comment]
Overriding the constructor unnecessarily requires additional overhead code, and makes the inheritance brittle and susceptible to breakage. Constructor method signatures change frequently in Magento, and the proposed changes provide two key benefits (especially for extension developers):

1. Allow arguments to be given via `di.xml`, making it more manageable to extend the class
2. Prevent subclasses of `Magento\Backend\App\Action\Plugin\Authentication` from breaking if there's a backward-incompatible change made in a future release

There are several examples of this done elsewhere in Magento, such as:

https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Tax/Model/Calculation.php#L232
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Shipping/Model/Order/Track.php#L54
https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Shipping/Model/Order/Pdf/Packaging.php#L71

Albeit, each of these classes inherit from `Magento\Framework\DataObject`. If that's a more desirable approach, I'm more than happy to make the change and send another pull request.

**Pull request closed without merging**
