### PR TITLE
Don't cache private content in Varnish, only 200 and 404 responses. A…

### LINKED ISSUE #36492: Default V6 VCL Template Logic
### Preconditions and environment

v2.4.5

### Steps to reproduce

Navigate to a page that does a 301 redirect or has "private" in cache-control header with a status code of 200. 

### Expected result

I would think anything (200, 404, 301 etc) that has "private" in Cache-Control header would not get cached.

### Actual result

https status 200 with private in Cache-Control header is now cached and a 301 is also now cached unless it has private in Cache-Control header. 

### Additional information

From #https://github.com/magento/magento2/commit/615023186303ce22f976d11a0fb0c80b477bcee0    File: app/code/Magento/PageCache/etc/varnish6.vcl

Previous versions of generated VCL
```
# cache only successfully responses and 404s
    if (beresp.status != 200 && beresp.status != 404) {
        set beresp.ttl = 0s;
        set beresp.uncacheable = true;
        return (deliver);
    } elsif (beresp.http.Cache-Control ~ "private") {
```

New V6 generated VCL
```
# cache only successfully responses and 404s that are not marked as private
    if (beresp.status != 200  &&
            beresp.status != 404 &&
            beresp.http.Cache-Control ~ "private") {
        set beresp.uncacheable = true;
        set beresp.ttl = 86400s;
        return (deliver);
```

The logic changed on v6. Perhaps I misunderstand but shouldn't it be 
`if ((beresp.status != 200 && beresp.status != 404)  || (beresp.http.Cache-Control ~ "private")) {`

Im running into an issue with a 3rd party module where it no longer works correctly due to this change.

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by hostep**
…lso fixes some whitespace inconsistencies.

### Description (*)
https://github.com/magento/magento2/pull/28927 accidentally added a bug, where it allows any response that doesn't have a 200 or 404 status code to become cached. Unless the Cache-Control header contains `private`.

This is incorrect, it should only cache 200 or 404 responses, unless they contains Cache-Control header `private`, not any other status codes.

I've also noticed some whitespace inconsistencies where indentation used 3 spaces instead of 4, so those got fixed as well here. Append [`?w=1` to the url of this PR](https://github.com/magento/magento2/pull/36524/files?w=1) to see only the relevant changes.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#36492

### Manual testing scenarios (*)
1. Setup Magento with Varnish and configure Varnish with the VCL file that Magento generates in the backoffice
2. Test if a response with HTTP status 200 or 404 gets cached
3. Test if a response with HTTP status 301 or 302 does not get cached
4. Test if a response which contains header `Cache-Control: private` and HTTP status 200 or 404 does not get cached
5. Test if a response which contains header `Cache-Control: private` and HTTP status 301 or 302 does not get cached

### Questions or comments
@icecactus: I hope I understood your report correctly, feel free to correct me or give better steps of how to test this fix

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hostep** [comment]
It probably does not make sense to run tests for this PR, not sure if there are automated tests that use Varnish?

But let me trigger it just once ...

@magento run all tests

**Comment by hostep** [comment]
This PR will have some conflicts once https://github.com/magento/magento2/pull/38052 and https://github.com/magento/magento2/pull/36796 get approved and merged, but let's see which one will make it first (probably none of the 3 ones, if we see how Adobe has handled similar PR's in the past)

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Unit Tests,Static Tests,Functional Tests EE

**Comment by engcom-Echo** [comment]
@hostep ,

Thank you for your contribution.
We have tried to reproduce the issue but the issue is not reproducible on `2.4-develop`.

Below are the steps we have followed.

1. Setup clean Magento `2.4-develop` instance with Varnish and configure Varnish with the VCL file that Magento generates in the backoffice
2. Test - response with HTTP status 200 or 404 gets cached 
3. Test -  response with HTTP status 301  does not get cached
4. Test -  response with  Cache-Control header `private` with HTTP status 301  does not get cached

Can you please let us know if the issue still exists or we are missing any step.

**Comment by hostep** [comment]
@engcom-Echo: it sounds like you only tested 3 out of the 4 cases. You forgot to test:
- Test if a response which contains header Cache-Control: private and HTTP status 200 or 404 does not get cached

Can you try that one as well?

If that still works as expected, I think we'll need to pull in the help of a Varnish expert (which I'm certainly not myself unfortunately) to verify if there is still a bug or not in the VCL file.

**Comment by icecactus** [comment]
@engcom-Echo, @hostep is correct, you missed the test for the private header.

**Comment by engcom-Echo** [comment]
> If that still works as expected, I think we'll need to pull in the help of a Varnish expert (which I'm certainly not myself unfortunately) to verify if there is still a bug or not in the VCL file.

@hostep We have verify on `2.4-develop` and `PR branch ` but the behavior is same for below case

- Test if a response which contains header `Cache-Control: private` and HTTP status 200 or 404 get cached

Let us know if we are missing something here.

**Comment by engcom-Echo** [comment]
@hostep can you please have a look on above [comment](https://github.com/magento/magento2/pull/36524#issuecomment-1893083166) and suggest us if we have missed any steps?

**Comment by gquintard** [comment]
hi @hostep!

I think that PR is correct, I did break that caching behavior in https://github.com/magento/magento2/pull/28927 .
Let me get you a `vtc` going so we can lock that down and avoid manual testing

**Comment by engcom-Echo** [comment]
@gquintard Have you had an opportunity to review the mentioned [comment](https://github.com/magento/magento2/pull/36524#issuecomment-1900422807) ?

**Comment by gquintard** [comment]
the one I answered to? Yes. I will write the `varnishtest` case when I have some time, hopefully this week

**Comment by gquintard** [comment]
@hostep, I've opened https://github.com/hostep/magento2/pull/2 on your fork. I just adds a `vtc` that, like for #38211 and #28944, you can run with:

``` shell
varnishtest dev/tests/varnish/*.vtc
```

You'll notice the test failing before your patch is applied, and passing after.

The test case will be cleaner if/once #28944 is merged, but it will do for now.

**Comment by hostep** [comment]
Awesome!

I've cherry-picked your commit and added it to this PR here.

I can confirm the test passes with the fixes provided here and fails without them.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
:heavy_check_mark: QA Passed

**Before:** :heavy_multiplication_x:
Screenshot 2024-01-30 at 3 48 26 PM


**After:** :heavy_check_mark:  
Screenshot 2024-01-30 at 3 34 22 PM

As some builds are failing hence moving it to `Extended Testing`

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests B2B,Integration Tests

**Comment by engcom-Echo** [comment]
Functional Tests B2B failures are different on last two run on same commit.
Run1
Screenshot 2024-01-30 at 6 20 48 PM

Run2
`StorefrontPrintListItemsFromRequisitionListTest`

Hence Moving it to `Merge in progress`

**Pull request merged**
