### PR TITLE
Remove Varnish 4/5 support

### LINKED ISSUE #38304: [Issue] Remove Varnish 4/5 support
This issue is automatically created based on existing pull request: magento/magento2#38052: Remove Varnish 4/5 support

---------
### Description (*)
Varnish 6.0 is half a decade old. 4.x and 5.x have been EOL'd years ago and there shouldn't be any more distribution carrying those, there's no good reason to keep them around.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by gquintard**
### Description (*)
Varnish 6.0 is half a decade old. 4.x and 5.x have been EOL'd years ago and there shouldn't be any more distribution carrying those, there's no good reason to keep them around.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38304: Remove Varnish 4/5 support

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
LGTM, but let's run the tests
@magento run all tests

**Comment by gquintard** [comment]
missed at least one occurrence
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @gquintard,
Could you please fix SVC failure by reverting constant removal and instead marking them as deprecated with an explanation that Varnish 4 and 5 has reached EOL?
Also, could you pls fix failing static tests?

**Comment by gquintard** [comment]
Sure, do you have an example on how to mark constant deprecated?

**Comment by hostep** [comment]
@gquintard: here are some examples: https://github.com/magento/magento2/blob/bc1c7bac0b2d5b25491f34b17c055149780435fc/app/code/Magento/Usps/Model/Carrier.php#L36-L49

**Comment by hostep** [comment]
@magento run all tests

**Comment by gquintard** [comment]
@ihor-sviziev, I saw that tests complained about missing `@see` comments so I just added them, however, that made me notice that `VARNISH_SUPPORTED_VERSION_X` and `VARNISH_X_CONFIGURATION_PATH` constants exist in both `app/code/Magento/PageCache/Model/Varnish/VclTemplateLocator.php` and `app/code/Magento/PageCache/Model/Config.php`, which feels a bit redundant

**Comment by gquintard** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by gquintard** [comment]
hi @ihor-sviziev, thank you for approving this, what are the next steps to get this in?

**Comment by ihor-sviziev** [comment]
@engcom-Charlie, could you please try moving this PR forward?

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento create issue

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Integration Tests,Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Functional Tests B2B

**Comment by engcom-Echo** [comment]
We have raise internal approval [JIRA](https://jira.corp.adobe.com/browse/AC-10735). Once we get approval we will move this PR forward.
Till the time Moving it to `Pending Approval`

**Comment by engcom-Echo** [comment]
Functional Tests B2B failure are flaky based on [comment](https://github.com/magento/magento2/pull/38052#issuecomment-1864545479).
 We have got approval for [JIRA](https://jira.corp.adobe.com/browse/AC-10735).
Hence moving it to `Merge In Progress`.

**Pull request merged**
