### PR TITLE
magento/magento2#26766: GraphQL. Query: categoryList. Returns wrong category image URL

### LINKED ISSUE #26766: GraphQL. Query: categoryList. Returns wrong category image URL
### Preconditions (*)

1. Create a new category on the back-end side
2. Upload an image for this category. Use the next image name - `Screen_Shot_2019-09-08_at_1.11.46_PM.png`

### Steps to reproduce (*)

1. Open any GraphQl tool
2. Run the next query to retrieve a category image:

```
{
    categoryList(
      filters : {
        ids: {eq: "ENTITY_ID_OF_CATEGORY"}
      }
    )
    {
        image
    }
}

```
### Expected result (*)

1. Category image URL is correct: 

expected

### Actual result (*)

1. Category image URL is incorrect: 

actual

Thank you!

### PR DESCRIPTION
**Pull request by atwixfirster**
### Description (*)

PR fixes https://github.com/magento/magento2/issues/26766.

### Fixed Issues (if relevant)

1. magento/magento2#26766: GraphQL. Query: categoryList. Returns wrong category image URL

### Manual testing scenarios (*)

1. Open any GraphQl tool
2. Run the next query to retrieve a category image:

```
{
    categoryList(
      filters : {
        ids: {eq: "ENTITY_ID_OF_CATEGORY"}
      }
    )
    {
        image
    }
}

```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by treestonemedia** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @treestonemedia. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @treestonemedia, here is your [new Magento instance](https://pr-26767.instances.magento-community.engineering).
Admin access: [https://pr-26767.instances.magento-community.engineering/admin_58e3](https://pr-26767.instances.magento-community.engineering/admin_58e3)
Login: `4f670e81` Password: `82834b309329`
Instance will be terminated in up to 3 hours.

**Comment by treestonemedia** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @treestonemedia. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @treestonemedia, here is your [Magento instance](https://i-26767-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26767-2-4-develop.instances.magento-community.engineering/admin_3dfb](https://i-26767-2-4-develop.instances.magento-community.engineering/admin_3dfb)
Login: `531b3dcb` Password: `0063c17cdc79`
Instance will be terminated in up to 3 hours.

**Comment by treestonemedia** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @treestonemedia. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by treestonemedia** [comment]
@magento give me 2.3 instance

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @atwixfirster. Could I kindly ask you to cover your solution with an automated test, please? I believe we may extend the existing API-functional test. 

Thank you!

**Comment by atwixfirster** [comment]
Dear, @rogyar !

> Could I kindly ask you to cover your solution with an automated test, please?

API-functional test for this part already exists in [Magento\GraphQl\Catalog\CategoryTest::testCategoryImage()](https://github.com/magento/magento2/blob/2.3.4/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/CategoryTest.php#L598).

Could you please approve this PR such all work is done.

Thank you!

**Comment by fooman** [comment]
@atwixfirster I guess @rogyar might be concerned that the existing test didn't fail prior to your fix. If you could add a test that a.) fails before your fix and b.) passes after the changes in this PR that be grand.

**Comment by atwixfirster** [comment]
Hi, @fooman !

> I guess @rogyar might be concerned that the existing test didn't fail prior to your fix.

The existing test successfully covered the categoryList before my changes but again that was a lucky data.

**Comment by rogyar** [comment]
Hi @atwixfirster. Kristof is right. I mean, all changes to the core introduced in PRs should be covered by autotests which are:

- red without the fix
- green with the fix

The current test does not meet the first criteria. So it does not test the current fix somehow. So we need to figure out how to cover this fix. 

I have doubts about a strict rule regarding introducing new fixtures. About [editing the existing](https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/#magento-functional-and-integration-tests) fixtures I agree. But as for the new fixtures, maybe @lenaorobei will advocate the right solution. 

Thank you!

**Comment by atwixfirster** [comment]
Looks my fix is not actual anymore due to MC-29519:

```
Index: app/code/Magento/CatalogGraphQl/Model/Resolver/Category/Image.php
===================================================================
diff -u -N -r4745f33bf938c45252edf0156e8c9becb21c94ff -r460f1070ccd44f2a4d01324aff07e5a0f64f59a6
--- app/code/Magento/CatalogGraphQl/Model/Resolver/Category/Image.php	(.../Image.php)	(revision 4745f33bf938c45252edf0156e8c9becb21c94ff)
+++ app/code/Magento/CatalogGraphQl/Model/Resolver/Category/Image.php	(.../Image.php)	(revision 460f1070ccd44f2a4d01324aff07e5a0f64f59a6)
@@ -13,6 +13,8 @@
 use Magento\Framework\Exception\LocalizedException;
 use Magento\Store\Api\Data\StoreInterface;
 use Magento\Framework\Filesystem\DirectoryList;
+use Magento\Catalog\Model\Category\FileInfo;
+use Magento\Framework\GraphQl\Exception\GraphQlInputException;
 /**
  * Resolve category image to a fully qualified URL
@@ -22,12 +24,18 @@
     /** @var DirectoryList  */
     private $directoryList;
+    /** @var FileInfo  */
+    private $fileInfo;
+
     /**
      * @param DirectoryList $directoryList
      */
-    public function __construct(DirectoryList $directoryList)
-    {
+    public function __construct(
+        DirectoryList $directoryList,
+        FileInfo $fileInfo
+    ) {
         $this->directoryList = $directoryList;
+        $this->fileInfo = $fileInfo;
     }
     /**
@@ -45,21 +53,38 @@
         }
         /** @var \Magento\Catalog\Model\Category $category */
         $category = $value['model'];
-        $imagePath = $category->getImage();
+        $imagePath = $category->getData('image');
         if (empty($imagePath)) {
             return null;
         }
         /** @var StoreInterface $store */
         $store = $context->getExtensionAttributes()->getStore();
-        $baseUrl = $store->getBaseUrl('media');
+        $baseUrl = $store->getBaseUrl();
-        $mediaPath = $this->directoryList->getUrlPath('media');
-        $pos = strpos($imagePath, $mediaPath);
-        if ($pos !== false) {
-            $imagePath = substr($imagePath, $pos + strlen($mediaPath), strlen($baseUrl));
+        $filenameWithMedia =  $this->fileInfo->isBeginsWithMediaDirectoryPath($imagePath)
+            ? $imagePath : $this->formatFileNameWithMediaCategoryFolder($imagePath);
+
+        if (!$this->fileInfo->isExist($filenameWithMedia)) {
+            throw new GraphQlInputException(__('Category image not found.'));
         }
-        $imageUrl = rtrim($baseUrl, '/') . '/' . ltrim($imagePath, '/');
-        return $imageUrl;
+        // return full url
+        return rtrim($baseUrl, '/') . $filenameWithMedia;
     }
+
+    /**
+     * Format category media folder to filename
+     *
+     * @param string $fileName
+     * @return string
+     */
+    private function formatFileNameWithMediaCategoryFolder(string $fileName): string
+    {
+        return '/'
+            . $this->directoryList->getUrlPath('media')
+            . '/'
+            . ltrim(FileInfo::ENTITY_MEDIA_PATH, '/')
+            . '/'
+            . basename($fileName);
+    }
 }
```

@cpartica , could you please confirm?

Thank you!

**Comment by lenaorobei** [comment]
@atwixfirster yes, this issue is already fixed for the `2.3.x` release line and `2.4.x` is in progress. Internal team come up with different solution. Sorry for late response. 

Unfortunately need to close this PR.

**Pull request closed without merging**
