### PR TITLE
[backport] Improve swatch table overflow handling

### PR DESCRIPTION
**Pull request by Cyanoxide**
### Description (*)
Updates swatches.css to add overflow:auto to the three swatch tables (text, dropdown & visual) to allow for scrolling if the amount of inputs exceeds the available space and increase the min width of inputs (150px) within the table for better usability. 

Intentionally left original input width (50px) as a fallback and updated .col-swatch-min-width to be consistent with 2.3.

### Fixed Issues (if relevant)

1. magento/magento2#21421: Improve swatch table overflow handling (original)
2. magento/magento2#19932: Fix Swatch Overflow issue
3. magento/magento2#19933: [backport] Fix Swatch Overflow issue

### Manual testing scenarios (*)

1. Add multiple store view and languages to your store (Our store has 19 but you should be able to reach replicate the issue with less)
2. Open an attribute page within the Admin area to configure (Stores > Product > Any attribute).
3. Table inputs at the bottom for languages should be too small to to use effectively
4. If 3. isn't true add more store views, the more that are added the smaller the input fields get.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Cyanoxide. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by Cyanoxide** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Cyanoxide. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Cyanoxide, here is your [new Magento instance](https://pr-21661.instances.magento-community.engineering).
Admin access: [https://pr-21661.instances.magento-community.engineering/admin](https://pr-21661.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by dmytro-ch** [comment]
Hi @Cyanoxide,
thank you for your contribution.

The original pull request is marked as a cleanup.
Unfortunately, we can't accept this Pull Request to 2.2 release line, all code cleanup should be delivered to 2.3 release line. For more information, please, refer to [Magento Code Contributions Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules).

According to the latest changes in contribution guide, the minor style/design fixes are considered as Code Cleanup. [Magento Code Contributions Guide - Base achievements](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#base-achievements)

Thank you!

**Comment by Cyanoxide** [comment]
@dmytro-ch You'd know better than me so if that's your final decision then no problem but I'm not sure that that's the correct category. The guide says clean up is for "typos, inline documentation, coding style, remove unused code, minor style/design fixes" However this and the original pull request resolve a functional issue that stops swatches from being usable. Without this fix it is impossible to use swatches with more than 15 storeviews without inspecting and adding these styles manually.

**Comment by dmytro-ch** [comment]
@Cyanoxide, thank you for the details.
I would also consider the original PR as a bug fix/improvement and reopen the backport.

cc @sidolov @sivaschenko

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4547](https://jira.corp.magento.com/browse/ENGCOM-4547) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
✔️ QA passed

**Pull request merged**
