### PR TITLE
[32033][To 2.4-develop] Marked Framework Setup interfaces as API

### LINKED ISSUE #32033: Mark Framework Setup interfaces as API
The following interfaces should be marked as API

1. lib/internal/Magento/Framework/Setup/ConfigOptionsListInterface.php
1. lib/internal/Magento/Framework/Setup/DataCacheInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/DataSavior/DataSaviorInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/DataSavior/DumpAccessorInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Db/DDLTriggerInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Db/DbDefinitionProcessorInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Db/DbSchemaReaderInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Db/DbSchemaWriterInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Declaration/ValidationInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Diff/DiffInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Dto/Columns/ColumnDefaultAwareInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Dto/Columns/ColumnIdentityAwareInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Dto/Columns/ColumnNullableAwareInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Dto/Columns/ColumnUnsignedAwareInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Dto/ElementDiffAwareInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Dto/Factories/FactoryInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/Dto/TableElementInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/OperationInterface.php
1. lib/internal/Magento/Framework/Setup/Declaration/Schema/SchemaConfigInterface.php
1. lib/internal/Magento/Framework/Setup/Patch/DataPatchInterface.php
1. lib/internal/Magento/Framework/Setup/Patch/DependentPatchInterface.php
1. lib/internal/Magento/Framework/Setup/Patch/NonTransactionableInterface.php
1. lib/internal/Magento/Framework/Setup/Patch/PatchInterface.php
1. lib/internal/Magento/Framework/Setup/Patch/PatchRevertableInterface.php
1. lib/internal/Magento/Framework/Setup/Patch/SchemaPatchInterface.php
1. lib/internal/Magento/Framework/Setup/SampleData/InstallerInterface.php
1. lib/internal/Magento/Framework/Setup/SampleData/StateInterface.php
1. lib/internal/Magento/Framework/Setup/SchemaListenerDefinition/DefinitionConverterInterface.php
1. lib/internal/Magento/Framework/Setup/SchemaListenerHandlers/SchemaListenerHandlerInterface.php
1. lib/internal/Magento/Framework/Setup/UpToDateValidatorInterface.php

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixes #32033
### Related Pull Requests

https://github.com/magento/magento2/pull/32166
### Fixed Issues (if relevant)

1. Fixes magento/magento2#32033>

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by danielrussob** [comment]
@magento run WebAPI Tests

**Comment by aleron75** [comment]
Hello @Usik2203 
I've verified that this PR contains all the changes requested in related issue #32033 plus the following:

- `lib/internal/Magento/Framework/Setup/Declaration/Schema/Db/StatementAggregator.php `
- `lib/internal/Magento/Framework/Setup/Declaration/Schema/Dto/Schema.php`
- `lib/internal/Magento/Framework/Setup/Declaration/Schema/Dto/Table.php`
- `lib/internal/Magento/Framework/Setup/Declaration/Schema/ElementHistory.php`

can you please explain where do these additional files come from?

Thanks!

**Comment by Usik2203** [comment]
> Hello @Usik2203
> I've verified that this PR contains all the changes requested in related issue #32033 plus the following:
> 
> * `lib/internal/Magento/Framework/Setup/Declaration/Schema/Db/StatementAggregator.php `
> * `lib/internal/Magento/Framework/Setup/Declaration/Schema/Dto/Schema.php`
> * `lib/internal/Magento/Framework/Setup/Declaration/Schema/Dto/Table.php`
> * `lib/internal/Magento/Framework/Setup/Declaration/Schema/ElementHistory.php`
> 
> can you please explain where do these additional files come from?
> 
> Thanks!

Hi @aleron75 
These classes were marked based on these comments for preventing failed static tests
https://github.com/magento/magento2/pull/32166#pullrequestreview-595117283
https://github.com/magento/magento2/pull/32172#pullrequestreview-593490771
Thanks

**Review by danielrussob — APPROVED** [review]

**Review by aleron75 — APPROVED** [review]

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama the branch with code successfully imported into`magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-32733`.

**Pull request merged**
