### PR TITLE
Fix HTML tags in meta description

### PR DESCRIPTION
**Pull request by vseager**
### Description
Fixes issue with HTML tags in meta description if no meta description is provided.

### Fixed Issues (if relevant)
1. HTML tags in meta description

### Manual testing scenarios
1. Ensure a product has no meta description
2. Visit product on frontend and view page source

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14436) <br/>All committers have signed the CLA.

**Comment by larsroettig** [comment]
@vseager can you sign our Contributor License Agreement. 

Best regards,

Lars

**Review by larsroettig — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @larsroettig, thank you for the review.
[ENGCOM-1172](https://jira.corp.magento.com/browse/ENGCOM-1172) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@vseager thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by vseager** [comment]
@magento-engcom-team Thanks, I have signed the agreement.

**Comment by vseager** [comment]
@magento-engcom-team can you also port this fix to 2.2+

**Comment by larsroettig** [comment]
@vseager you can you open a ticket for it 😄somebody will take it and port to 2.2 and 2.3

**Comment by davidwindell** [comment]
@larsroettig please see #14529

**Pull request merged**
