### PR TITLE
Fix setup wizard on php8-develop branch

### PR DESCRIPTION
**Pull request by hws47a**
### Description (*)

There is an issue in php8-develop branch with setup wizard not working after updating of laminas-servicemanager.
This PR fixes is

### Manual testing scenarios (*)

Open setup wizard and wait for content to appear.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32551: Fix setup wizard on php8-develop branch

### CODE REVIEW

**Comment by hws47a** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Unit Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]

**Comment by sivaschenko** [comment]
@magento create issue

**Pull request merged**
