### PR TITLE
extra-space-detailed-ratings:: extra space detailed ratings on edit r…

### PR DESCRIPTION
**Pull request by nainesh2jcommerce**
…eview page

### Description (*)

Edit review page in admin, detailed rating having extra space between label and rating stars.

### Manual testing scenarios (*)

1. Login to admin
2. Marketing --> Reviews --> edit any review
3. check for detailed ratings

### Actual result (*)
image

### Expected result (*)
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sdzhepa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [new Magento instance](https://pr-20960.instances.magento-community.engineering).
Admin access: [https://pr-20960.instances.magento-community.engineering/admin](https://pr-20960.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sdzhepa** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-20960-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20960-2-3-develop.instances.magento-community.engineering/admin](https://i-20960-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
Hello @nainesh2jcommerce 

During testing, I faced a new design issue only on PR branch with the fix.

Could you please have a look and fix it?


- **Problem:** _Default lengths for a title was changed that leads to new design issue even with default labels._


**Current result on '2.3-develop' branch**
2_3_develop_review

**Result on branch PR beranch with fix**
pr_20960


Thank you for contribution and collaboration!

**Comment by nainesh2jcommerce** [comment]
Hi @sdzhepa, I have keep length as per default for label and reduce for rating starts which reduce space between label and rating stars, can you please review.

Thanks!

**Comment by nainesh2jcommerce** [comment]
Hi @sdzhepa, can you please review.

**Comment by sdzhepa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [new Magento instance](https://pr-20960.instances.magento-community.engineering).
Admin access: [https://pr-20960.instances.magento-community.engineering/admin](https://pr-20960.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @nainesh2jcommerce can you please fix commit authorship for this pull request as well?

**Comment by sidolov** [comment]
@nainesh2jcommerce , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
