### PR TITLE
Let Swagger return the correct error codes

### PR DESCRIPTION
**Pull request by michielgerritsen**
### Description (*)
When the Swagger schema is generated, not all error codes are included. When in the interface is described that a method can throw a `NoSuchEntityException` exception, we can expect that the schema should include the 404 error response.

This error is caused due to the way `is_subclass_of` works. This checks if the exception is a subclass of `NoSuchException` for example, but when exactly that exception is thrown it will never return true:
https://3v4l.org/s4ZoO

When checking the schema for `directoryCountryInformationAcquirerV1`, the first one that throws a 404 in the list, only examples for the 200 and 400 statuses are returned. With this change also the 404 status is returned.

### Related Pull Requests
I did not find any.

### Fixed Issues (if relevant)
I did not find any.

### Manual testing scenarios (*)

1. Go to `m2-example.test/swagger`.
2. Click on `directoryCountryInformationAcquirerV1`.
3. Click on `/V1/directory/countries/{countryId}`

The list with responses contains a 200, a 400, and the default code. With this PR also the 404 code is included.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by michielgerritsen** [comment]
@magento run all tests

**Comment by michielgerritsen** [comment]
@magento run all tests

**Comment by michielgerritsen** [comment]
@magento run all tests

**Comment by nuzil** [comment]
@magento run WebAPI Tests

**Review by nuzil — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-9182](https://jira.corp.magento.com/browse/ENGCOM-9182) has been created to process this Pull Request

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
Hi @michielgerritsen ,

Thanks for your contribution and collaboration.

As you mentioned in the description in the Swagger list, responses contain a 200, a 400, and the default code. With this PR also the 404 code is included. But after taking PR changes 400 code is not getting displayed. Below is the screenshot for your reference **(After PR changes):**
Swagger-UI_after_PR


**Before PR changes:**
image

Could you please provide information on whether the 400 code is removed from the Swagger response area in this PR?

Thanks

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
Hi @michielgerritsen ,

Please provide us information asked in this [comment](https://github.com/magento/magento2/pull/33475#issuecomment-1673311545).

Thanks

**Comment by engcom-Lima** [comment]
Hi @michielgerritsen ,

Thanks for your contribution and collaboration.

We are closing this PR as there is no update from long time. Please feel free to reopen this PR incase if you are facing any issue.


Thanks

**Pull request closed without merging**
