### PR TITLE
Category page should scroll to top to view success message

### PR DESCRIPTION
**Pull request by saphaljha**
### Description (*)
After adding product to cart page should scroll to top to view success message.

### Manual testing scenarios (*)

1. scroll category page to last and added a product into cart.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @saphaljha. Thank you for this suggestion. Your edit makes sense, but let's look at the solution from another perspective. As a customer, once I've clicked the "Add to cart" button, I want to proceed from where I am and browse/add to cart other products. Especially it applies to mobile devices. If the page will jump to the top after every successful adding to the shopping cart it might be confusing from UX point of view.

I hope it makes sense.

**Comment by tanghongtanghong** [comment]
from remote to recently

**Comment by tanghongtanghong** [comment]
以人为维度去评论

**Comment by tanghongtanghong** [comment]
> from remote to recently

噢噢噢噢噢

**Comment by lenaorobei** [comment]
This is the expected behavior in Magento. If you observe user experience issues with that approach, please consider opening an issue to describe the business impact. Thank you!

**Pull request closed without merging**
