### PR TITLE
Added Fix for issue 26168

### PR DESCRIPTION
**Pull request by divyajyothi5321**
### Fixed Issues (if relevant)

1. magento/magento2#26168: Input Checkbox Alignment Issue at checkout page in Safari Browser

### Manual testing scenarios (*)

1. Go to Front end, add any product to Cart.
2. Go to Checkout Page.
3. Fill all the shipping details
4. Then go to Review and payments
5. With this fix the checkbox is aligned properly as shown below
checkbox-expected

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](https://i-26169-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26169-2-4-develop.instances.magento-community.engineering/admin](https://i-26169-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rogyar** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-26169.instances.magento-community.engineering).
Admin access: [https://pr-26169.instances.magento-community.engineering/admin](https://pr-26169.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-6521](https://jira.corp.magento.com/browse/ENGCOM-6521) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [Magento instance](https://i-26169-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26169-2-4-develop.instances.magento-community.engineering/admin](https://i-26169-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [new Magento instance](https://pr-26169.instances.magento-community.engineering).
Admin access: [https://pr-26169.instances.magento-community.engineering/admin](https://pr-26169.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by kanthy-i95dev — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [Magento instance](https://i-26169-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26169-2-4-develop.instances.magento-community.engineering/admin](https://i-26169-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [new Magento instance](https://pr-26169.instances.magento-community.engineering).
Admin access: [https://pr-26169.instances.magento-community.engineering/admin](https://pr-26169.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
