### PR TITLE
magento/magento2#: GraphQl. Remove a redundant logic in “SetShippingMethodsOnCart” mutation resolver

### LINKED ISSUE #28262: [Issue] magento/magento2#: GraphQl. Remove a redundant logic in “SetShippingMethodsOnCart” mutation resolver
This issue is automatically created based on existing pull request: magento/magento2#27349: magento/magento2#: GraphQl. Remove a redundant logic in “SetShippingMethodsOnCart” mutation resolver

---------

### Description (*)

PR removes a redundant logic in the `SetShippingMethodsOnCart` mutation resolver because `Webonix` covers the next cases:
- `shipping_methods`.`carrier_code` does not exist

- `shipping_methods`.`method_code` does not exist

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### LINKED ISSUE #28427: [Issue] magento/magento2#: GraphQl. Remove a redundant logic in “SetShippingMethodsOnCart” mutation resolver
### Summary (*)

PR removes a redundant logic in the `SetShippingMethodsOnCart` mutation resolver because `Webonix` covers the next cases:
- `shipping_methods`.`carrier_code` does not exist

- `shipping_methods`.`method_code` does not exist

### PR DESCRIPTION
**Pull request by atwixfirster**
### Description (*)

PR removes a redundant logic in the `SetShippingMethodsOnCart` mutation resolver because `Webonix` covers the next cases:
- `shipping_methods`.`carrier_code` does not exist

- `shipping_methods`.`method_code` does not exist

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28262: magento/magento2#: GraphQl. Remove a redundant logic in “SetShippingMethodsOnCart” mutation resolver

### Resolved issues:
1. [x] resolves magento/magento2#28427: magento/magento2#: GraphQl. Remove a redundant logic in “SetShippingMethodsOnCart” mutation resolver

### CODE REVIEW

**Comment by atwixfirster** [comment]
@rogyar , could you please review this PR because failed static tests are not tie to the provided changes. 

Thank you!

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7216](https://jira.corp.magento.com/browse/ENGCOM-7216) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**After:**    
### Case 1
**_method_code_** doesn't exist

Request:
```graphql
mutation {
setShippingMethodsOnCart(input: {
  cart_id: "IIHXzIYP2HelB7xerWpZN1h4EZU7wxk4"
  shipping_methods:
  [
    {
      carrier_code: "ups"
    }
  ]
}) {
  cart {
    shipping_addresses {
      selected_shipping_method {
        carrier_code
        method_code
        carrier_title
        method_title
      }
    }
  }
}
}
```
Response:
```graphql
{
  "errors": [
    {
      "message": "Field ShippingMethodInput.method_code of required type String! was not provided.",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 2,
          "column": 100
        }
      ]
    }
  ]
}
```

### Case 2
**_carrier_code_** doesn't exist

Request:
```graphql
mutation {
setShippingMethodsOnCart(input: {
  cart_id: "IIHXzIYP2HelB7xerWpZN1h4EZU7wxk4"
  shipping_methods:
  [
    {
      method_code: "GND"

    }
  ]
}) {
  cart {
    shipping_addresses {
      selected_shipping_method {
        carrier_code
        method_code
        carrier_title
        method_title
      }
    }
  }
}
}
```
Response:

```graphql
{
  "errors": [
    {
      "message": "Field ShippingMethodInput.carrier_code of required type String! was not provided.",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 2,
          "column": 100
        }
      ]
    }
  ]
}
```

**Comment by slavvka** [comment]
@magento create issue

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @atwixfirster, thanks for collaboration. Can you please cover your fix with API functional test?

**Comment by atwixfirster** [comment]
Hi, @VladimirZaets !

> Hi @atwixfirster, thanks for collaboration. Can you please cover your fix with API functional test?

There is nothing to cover!

`Required parameter "carrier_code" is missing.` is covered in:
- https://github.com/magento/magento2/blob/2.4-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/SetShippingMethodsOnCartTest.php#L199
- https://github.com/magento/magento2/blob/2.4-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/SetShippingMethodsOnCartTest.php#L192

`Required parameter "method_code" is missing.` is covered in:
- https://github.com/magento/magento2/blob/2.4-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/SetShippingMethodsOnCartTest.php#L213
- https://github.com/magento/magento2/blob/2.4-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer/SetShippingMethodsOnCartTest.php#L206

P.S. Could you please reopen https://github.com/magento/magento2/pull/26576

Thank you!

**Comment by slavvka** [comment]
@atwixfirster we cannot repone #26576 as GitHub says that the branch was force-pushed or recreated. Please open a new one

**Comment by VladimirZaets** [comment]
@atwixfirster thanks, I thought this endpoint is not covered, sorry for that.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7216](https://jira.corp.magento.com/browse/ENGCOM-7216) has been created to process this Pull Request

**Comment by VladimirZaets** [comment]
@magento create issue

**Review by avattam06 — APPROVED** [review]

**Comment by avattam06** [comment]
Please merge the mainline and run the tests again.

**Comment by avattam06** [comment]
@magento run all tests

**Comment by avattam06** [comment]
@magento run all tests

**Comment by avattam06** [comment]
@magento run integration tests

**Comment by avattam06** [comment]
@magento run all tests

**Pull request merged**
