### PR TITLE
magento/magento2#15775: [Forwardport] Incorrect return type getList() in CustomerRepository.

### PR DESCRIPTION
**Pull request by p-bystritsky**
### Fixed Issues (if relevant)

1. magento/magento2#15775: Incorrect return type getList() in CustomerRepository

### Manual testing scenarios

1. Install attached module.
[test-module.zip](https://github.com/magento/magento2/files/2745987/test-module.zip)
2. Execute command `bin/magento foo:bar:test`
3. Command output should be `Passed`

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @p-bystritsky. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
@p-bystritsky do we really need to create real classes instead of virtual types?

**Comment by p-bystritsky** [comment]
> @p-bystritsky do we really need to create real classes instead of virtual types?

@orlangur I have no idea how to use virtual types in this case.

**Comment by sivaschenko** [comment]
@orlangur we cannot make virtual types to implement an interface.

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3855](https://jira.corp.magento.com/browse/ENGCOM-3855) has been created to process this Pull Request

**Comment by p-bystritsky** [comment]
Waiting for the architect's approvement.

**Comment by orlangur** [comment]
@p-bystritsky please add a link to architecture issue or something.

**Comment by orlangur** [comment]
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

**Comment by sivaschenko** [comment]
Pull request was approved to be merged to 2.3-develop at Public Architectural Discussion meeting https://github.com/magento/architecture/issues/165#issuecomment-497011809

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-5183](https://jira.corp.magento.com/browse/ENGCOM-5183) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Review by orlangur — CHANGES_REQUESTED** [review]
@p-bystritsky please check failed build.

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

**Comment by orlangur** [comment]
@magento run all tests

**Review by sidolov — CHANGES_REQUESTED** [review]
@p-bystritsky , we got compilation error during the build preparation. Could you please take a look? 
```

Repositories code generation... 1/7 [==>-----------------]  14% < 1 sec 67.0 MiBPHP Fatal error:  Cannot inherit previously-inherited or override constant KEY_ITEMS from interface Magento\Quote\Api\Data\CartSearchResultsInterface in /var/www/html/app/code/Magento/Quote/Model/CartSearchResults.php on line 16
```

**Comment by orlangur** [comment]
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.
Thanks for collaboration!

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-5964](https://jira.corp.magento.com/browse/ENGCOM-5964) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Pull request merged**
