### PR TITLE
Issue 23521

### PR DESCRIPTION
**Pull request by aleromano89**
### Description (*)
Using a mock function for get_headers() as the existing mock used for HttpTest class.

### Fixed Issues (if relevant)
1. magento/magento2#23521: Unable to run \Magento\Downloadable\Test\Unit\Helper\DownloadTest without internet connection / dns resolution

### Manual testing scenarios (*)
1. Simply try to run the involved unit tests. 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lbajsarowicz — APPROVED** [review]
In my opinion - These tests need to be rewritten.
Your change is good enough as a temporary solution :-)

Thank you for your contribution!

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-6542](https://jira.corp.magento.com/browse/ENGCOM-6542) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@aleromano89 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
QA not applicable

**Pull request merged**
