### PR TITLE
#29496 :- UI : Time field element in admin

### LINKED ISSUE #29496: UI : Time field element in admin
The CSS class for limited width doesn't gets applied after CSP port.

Tested on :
1. Google Chrome : Version 84.0.4147.125 (64-bit)
2. Firefox : 79.0 (64-bit)

### Preconditions (*)

1. Magento 2.4 Installed with Sample data
2.

### Steps to reproduce (*)

1. Install M2.4.0 with Sample Data
2. Login to Admin/Backend.
3. Navigate to following path Store > Configuration > Catalog > XML Sitemap > Generation Settings
4. Switch the value on 'Enabled' field to 'Yes'

### Expected result (*)

image

### Actual result (*)

image

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by konarshankar07**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#29496

### Manual testing scenarios (*)

1. Install M2.4.0 with Sample Data
2. Login to Admin/Backend.
3. Navigate to following path Store > Configuration > Catalog > XML Sitemap > Generation Settings
4. Switch the value on 'Enabled' field to 'Yes'

### Expected Result

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by konarshankar07** [comment]
@magento run all tests

**Comment by konarshankar07** [comment]
@magento run Unit Tests

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8007](https://jira.corp.magento.com/browse/ENGCOM-8007) has been created to process this Pull Request

**Comment by swnsma** [comment]
@magento run all tests

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-8007](https://jira.corp.magento.com/browse/ENGCOM-8007) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Log in to Admin/Backend;
2. Navigate to following path Store > Configuration > Catalog > XML Sitemap > Generation Settings;
3. Switch the value on 'Enabled' field to 'Yes'

**Before:** :heavy_multiplication_x:  



**After:** :heavy_check_mark:

**Pull request merged**
