### PR TITLE
Fixed-20246: Pagination overlapping when user hover last product

### PR DESCRIPTION
**Pull request by suryakant-krish**
### Description (*)

Frontend: Pagination overlapping when user hover last product list page.
This is a reference: https://github.com/magento/magento2/pull/20246

### Fixed Issues (if relevant)

1. This is direct pr as per suggest magento reviewer.

### Manual testing scenarios (*)

1. Go to frontend > navigate nay sub category hover on last product. which is first.
2. Actual Result.
actual
3. Expected Result.
expected

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20633) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=20633) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by suryakant-krish** [comment]
@sivaschenko,
please review this pull request. original pull request of https://github.com/magento/magento2/pull/20246.
because there is unnecessary commits so I have created a new pull request.

**Comment by sivaschenko** [comment]
Hi @suryakant-krish , can you please sign the [CLA](https://cla.dev.magento.com/magento/magento2?pullRequest=20633) before we can process the PR.

**Comment by suryakant-krish** [comment]
@sivaschenko,

I have signed in the CLA. please proceed.

**Comment by sivaschenko** [comment]
@suryakant-krish the CLA is still marked as not signed, but I see what the issue is:
The commit was not made under your account. Can you please update the commit author to match your github username.

**Comment by suryakant-krish** [comment]
@sivaschenko,
I have signed in the CLA. please check is it correct?

**Comment by sivaschenko** [comment]
Hi @suryakant-krish the author of commit https://github.com/magento/magento2/pull/20633/commits/1d54f4c082d298396745dae655872f09844e49fb in this pull request is @smakawana .
So for CLA check to pass either @smakawana should sign the CLA or you should commit under your github account.

**Comment by sidolov** [comment]
Hi @suryakant-krish , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
