### PR TITLE
Replace repetitive actions with Action Groups in AdminUpdateSimpleProductWithRegularPriceInStockVisibleInCatalogOnlyTest

### LINKED ISSUE #32568: [Issue] Replace repetitive actions with Action Groups in AdminUpdateSimpleProductWithRegularPriceInStockVisibleInCatalogOnlyTest
This issue is automatically created based on existing pull request: magento/magento2#32539: Replace repetitive actions with Action Groups in AdminUpdateSimpleProductWithRegularPriceInStockVisibleInCatalogOnlyTest

---------

### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run the test in the local environment and verified that it run successfully

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run the test in the local environment and verified that it run successfully

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32568: Replace repetitive actions with Action Groups in AdminUpdateSimpleProductWithRegularPriceInStockVisibleInCatalogOnlyTest

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Review by edenduong — APPROVED** [review]
Thank you for your contribution !

**Comment by magento-engcom-team** [comment]
Hi @edenduong, thank you for the review.
[ENGCOM-8961](https://jira.corp.magento.com/browse/ENGCOM-8961) has been created to process this Pull Request

**Comment by edenduong** [comment]
@magento create issue

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @kate-kyzyma, can you resolve conflicts? Thanks!

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
Hi, @gabrieldagama!
I have resolved a merge conflict.

Thanks.

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests EE, Unit Tests

**Pull request merged**
