### PR TITLE
Fixed Issue #24990 - Admin Panel logo link is not directing to admin dashboard page

### PR DESCRIPTION
**Pull request by vikalps4**
Fixed Issue **#24990**

### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Go to magento admin  -> System -> Web Setup Wizard page.
2. Click on magento admin logo

### Expected result (*)

1. On click magento admin panel logo, It should redirect to admin dashboard page

### Actual result (*)

1. 
admin_panel_logo

2. Logo link is not redirecting to magento admin dashboard page upon click

### CODE REVIEW

**Comment by davidverholen** [comment]
@magento run all tests

**Comment by davidverholen** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @davidverholen. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @davidverholen, here is your [new Magento instance](https://pr-24998.instances.magento-community.engineering).
Admin access: [https://pr-24998.instances.magento-community.engineering/admin](https://pr-24998.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by davidverholen** [comment]
@vikalps4 I tried to test it but the link still does not seem to work

**Comment by VladimirZaets** [comment]
@vikalps4, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Pull request closed without merging**
