### PR TITLE
[vcl] don't manually interfere with compression

### LINKED ISSUE #38309: [Issue] [vcl] don't manually interfere with compression
This issue is automatically created based on existing pull request: magento/magento2#38211: [vcl] don't manually interfere with compression

---------
### Description (*)

Varnish already has [default compression handling](https://varnish-cache.org/docs/trunk/users-guide/compression.html#default-behaviour). This code only kicks into gear in case of a `miss` or a `pass`, and in those cases, the backend should be responsible for these.

### Manual testing scenarios (*)

automated testing should do the job

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by gquintard**
### Description (*)

Varnish already has [default compression handling](https://varnish-cache.org/docs/trunk/users-guide/compression.html#default-behaviour). This code only kicks into gear in case of a `miss` or a `pass`, and in those cases, the backend should be responsible for these.

### Manual testing scenarios (*)

automated testing should do the job

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38309: [vcl] don't manually interfere with compression

### CODE REVIEW

**Comment by hostep** [comment]
This was also proposed in https://github.com/magento/magento2/pull/36796, but since it [lacked feedback from Adobe people](https://github.com/magento/magento2/pull/36796#issuecomment-1493796859) it got closed.

Maybe taking things in smaller steps will have a bigger chance of being accepted (but knowing Adobe, it will still take months if not years 🙁 )

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Echo** [comment]
@magento create issue

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
Hello @gquintard,

Thanks for the contribution!

We need a testing scenario to check this PR manually. Please provide us with the same.

Thanks

**Comment by gquintard** [comment]
Happy new year, I've just pushed a test, using the same logic as in #28944, I omitted the README to avoid conflicts, hoping the other PR will land before.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Hello @gquintard,

As the changes happened in the PR moving back this PR into review.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@gquintard can you please provide manual step for reproduction of the issue.

**Comment by gquintard** [comment]
hi @engcom-Delta, there's no bug per se, but the current code is redundant and can be taken out without changing behavior.

You can run the added tests using `varnishtest dev/tests/varnish/*.vtc`

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @gquintard,

Thanks for the contribution!

We have tried to run the varnishtest on our local with the PR changes. But it is showing failed. Please find the attached log for the same.

[test.log](https://github.com/magento/magento2/files/13884743/test.log)

Please review it.

**Comment by gquintard** [comment]
well, that's unexpected: `pwd=<PATH>38211` What kind of platform are you running this on?

the "extra characters at the end of h command" error message makes no sense to me at the moment but I expect the `>` and `<` in the path are messing us up, so I did something very stupid to debug: I replicated the command multiple time, adding more and more arguments with every line, to see which argument causes the problem. If you could grab the latest version and share the new logs, it would be great.

(I've also quoted the path to avoid more issue, and it could solve the problem entirely, I'm unsure)

**Comment by engcom-Hotel** [comment]
@gquintard Thanks for the quick workaround!

We are using Mac OS and set up the instance in our local machine. 

After taking the latest pull, the test is still failing. Please refer to the updated log below:

[test.log](https://github.com/magento/magento2/files/13898552/test.log)

We have just replaced our folder path with `/DummyPath/` in the log file.

Thanks

**Comment by gquintard** [comment]
@engcom-Hotel , thank you for your patience. I was able to get access to a mac thanks to the awesome @briiians, and it looks like on it, `sed FILE -e EXPRESSION` doesn't work (`FILE` is interpreted as an expression).

So, normally, this should be fixed, please have another look

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Review by engcom-Hotel — APPROVED** [review]
The failed `Functional Tests B2B` test seems flaky to me.

Hence approving this PR.

**Comment by engcom-Hotel** [comment]
:heavy_check_mark: QA Passed

Varnish already has [default compression handling](https://varnish-cache.org/docs/trunk/users-guide/compression.html#default-behaviour). This code only kicks into gear in case of a miss or a pass, and in those cases, the backend should be responsible for these.

**Preconditions:**

Varnish should be enabled as `Full Page Cache`

**Manual testing scenario:**

Run the below command to check the test result:
`varnishtest dev/tests/varnish/compression.vtc`

**Actual Result:** :heavy_check_mark:
The test should pass:
image

This PR is just an improvement.

**Tested all the manual scenarios, no impact on regression testing.**

**Pull request merged**
