### PR TITLE
Remove unwanted styles for email preview

### LINKED ISSUE #27543: Previewing email templates in admin loads admin area CSS
### Preconditions (*)

1. Magento 2.3.4, but this happens to other versions too

### Steps to reproduce (*)

1. In the admin, navigate to Marketing -> Email Templates
2. Load a template and hit Preview Template

### Expected result (*)

1. Email looks as "true" as possible, without any interference of CSS unrelated to the actual email

### Actual result (*)

1. Admin CSS interferes with how the email looks

The issue is simply that admin CSS is loaded when previewing email templates, which could interfere with how the emails show up as. With the Luma emails this difference is not much, some minor typography changes. However, when designing email templates from scratch, this could have a big effect — making the Preview Template functionality useless.

See screenshot below. Essentially there are two pages, one is the outer page (preview), and one is the inner page/iframe (popup). The iframe exists supposedly to isolate CSS changes. However, that's rendered moot as admin CSS is also loaded inside the iframe.

image

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Remove unrelated css from layout when preview email template

### Fixed Issues (if relevant)

1. magento/magento2#27543: Previewing email templates in admin loads admin area CSS

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lbajsarowicz — DISMISSED** [review]
I approve that change - verified on mailhog and e-mails seem to be fine
This needs advanced QA tests.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7350](https://jira.corp.magento.com/browse/ENGCOM-7350) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by lbajsarowicz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7350](https://jira.corp.magento.com/browse/ENGCOM-7350) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by mrtuvn** [comment]
@lbajsarowicz can u update label tests for QA tests

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Before:
#27828Main

After:
Preview Luma theme
#27828PR
Email Luma Theme
#27828PREmailLuma
Preview Blank theme
#27828PRBlank
Email Blank Theme
#27828PREmailBlank

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Pull request merged**
