### PR TITLE
Ensure integer values are not quoted as strings

### PR DESCRIPTION
**Pull request by udovicic**
### Description

In cases where indexers does a filtering in the style of `WHERE entity_id IN (...)` there is a performance penalty if IDs are passed as strings, rather than integer values. This is especially visible on larger data sets. This pull request should cover some common occurrences of this.

### Fixed Issues (if relevant)

1. n/a

### Manual testing scenarios

1. n/a

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18287) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @udovicic. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by miguelbalparda** [comment]
Hi @udovicic! I really like this PR, would you mind changing the target branch to 2.3? We are trying to have everything in 2.3 before other branches. Thanks!

**Comment by miguelbalparda** [comment]
Hey @udovicic were you able to review this and submit the PR to the 2.3 branch? To keep things in order, we are trying to have everything merged there before accepting the PR to other branches. Besides that, everything looks good!

**Comment by udovicic** [comment]
Hi @miguelbalparda , I have tested this only on 2.2, but yes, I can adjust for 2.3 as well. Do you want me to make to open a separate request for that one, as this branch was forked of 2.2 develop...

**Comment by miguelbalparda** [comment]
A separated pull request will work. Million thanks!!

**Comment by udovicic** [comment]
@miguelbalparda Please see #18611 for `2.3-develop` branch

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3298](https://jira.corp.magento.com/browse/ENGCOM-3298) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @udovicic. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
