### PR TITLE
Let `bin/magento catalog:images:resize` continue running on exception

### PR DESCRIPTION
**Pull request by k4emic**
Allows the `catalog:images:resize` command to be run even if one or more images may be missing. Any encountered exception will have its message printed, to make developers/maintainers aware of the problem while still allowing the process to finalize for other images.

Before: https://cl.ly/fd2e6adf199a
After: https://cl.ly/c3507cff74bb

Also removed some unused properties/arguments.

### Fixed Issues 

1. magento/magento2#22808: php bin/magento catalog:image:resize error if image is missing

### Manual testing scenarios (*)

1. Create product
2. Upload image for product
3. Move/remove uploaded image
4. Run `php bin/magento catalog:images:resize`

### Questions or comments

Please let me know if there are any objections to the way exceptions are handled. I did not see any reason to keep returning the previous `$count` value and decided to replace it with something more useful.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by dmytro-ch** [comment]
Hi @k4emic,
thank you for your contribution!

Please note, the current PR is on hold.
There is another solution already available. #23005

Thank you!

**Comment by k4emic** [comment]
Hi @dmytro-ch 
Please note that while the two PRs makes changes to similar files, they are addressing different problems.

**Comment by k4emic** [comment]
Note that #22847 is an alternative to this PR, while #23005 solves a different problem.

**Comment by dmytro-ch** [comment]
Hi @k4emic, sorry for late reply and thanks for your patience!
Could you please update your working branch with the latest changes from mainline and resolve merge conflicts?

**Comment by k4emic** [comment]
Hi @dmytro-ch 
Sure thing. It might take a few days before I get around to this, but I expect to begin progress on this before the end of next week.

**Comment by k4emic** [comment]
@dmytro-ch the mainline has been merged into this PR

**Review by markshust — APPROVED** [review]

**Comment by markshust** [comment]
@k4emic your PR looked good, unfortunately there are a couple new conflicts. if you can resolve once again i think we can merge this in.

**Comment by k4emic** [comment]
@markshust Conflicts have been resolved. Let me know if a cleanup in the commits is needed.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5613](https://jira.corp.magento.com/browse/ENGCOM-5613) has been created to process this Pull Request
:eight_spoked_asterisk: @dmytro-ch, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @k4emic .
Unfortunately, we are not able to reproduce the [issue](https://github.com/magento/magento2/issues/22808) on fresh 2.3-develop instance.

**Manual testing scenario:**
1. Magento 2.3 + sample data
2. Move/remove images from `pub/media/catalog/product`;
3. Run `php bin/magento catalog:images:resize`;

**Actual Result:**
The process finalize for other images even if we had some error messages. And at the end of the resize process, we get a list of errors.
before

@k4emic Could you take a look, please?

Thanks!

**Comment by k4emic** [comment]
Obsolete with the other fix. Thanks for waiting 23 days before reviewing!

**Pull request closed without merging**
