### PR TITLE
Refactor code that were reported by phpcs and improve tests [Part 2]

### PR DESCRIPTION
**Pull request by karyna-t**
### Description (*)
This PR refactors a piece of code that was missed previously.
Several testcases from Unit tests were removed because they were false-positive and duplicate another (integration test) functionality.

### Related Issues
1. https://github.com/magento/magento2/issues/34056

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by karyna-tsymbal-atwix** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests with env PHP 8.0

**Comment by karyna-tsymbal-atwix** [comment]
@magento run all tests

**Comment by karyna-tsymbal-atwix** [comment]
@magento run  WebAPI Tests with env PHP 8.0

**Pull request merged**
