### PR TITLE
[MFTF] Updating with AdminClickUpdateChangesOnCreateOrderPageActionGroup

### LINKED ISSUE #33689: [Issue] [MFTF] Updating with AdminClickUpdateChangesOnCreateOrderPageActionGroup
This issue is automatically created based on existing pull request: magento/magento2#33662: [MFTF] Updating with AdminClickUpdateChangesOnCreateOrderPageActionGroup

---------
### Description (*)
Tests have been updated with AdminClickUpdateChangesOnCreateOrderPageActionGroup

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
Tests have been updated with AdminClickUpdateChangesOnCreateOrderPageActionGroup

### Resolved issues:
1. [x] resolves magento/magento2#33689: [MFTF] Updating with AdminClickUpdateChangesOnCreateOrderPageActionGroup

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by edenduong — APPROVED** [review]
Thank you for your contribution !

**Comment by magento-engcom-team** [comment]
Hi @edenduong, thank you for the review.
[ENGCOM-9175](https://jira.corp.magento.com/browse/ENGCOM-9175) has been created to process this Pull Request

**Comment by eduard13** [comment]
@magento create issue
@magento run all tests

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9175](https://jira.corp.magento.com/browse/ENGCOM-9175) has been created to process this Pull Request

**Comment by Den4ik** [comment]
@magento run Functional Tests B2B, Integration Tests

**Comment by engcom-Charlie** [comment]
✔️ QA Passed

All the test cases are working fine and green in build. Please find the Allure report for the same.

image

**Pull request merged**
