### PR TITLE
local themes should be added to git repo

### PR DESCRIPTION
**Pull request by torhoehn**
Removed local-themes.js from .gitignore

### Description (*)

Since local-themes.js is always created manually by copying themes.js it should be added to git. So themes.js could also be a .js.dist-file which has to be copied and would be added to git, too.

### Fixed Issues (if relevant)

1. magento/magento2#18949: dev/tools/grunt/configs/themes.js gets replaced after update magento

### Manual testing scenarios (*)

1. Copy dev/tools/grunt/configs/themes.js to dev/tools/grunt/configs/local-themes.js
2. local-themes.js should be found by git now

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-3338](https://jira.corp.magento.com/browse/ENGCOM-3338) has been created to process this Pull Request

**Comment by VladimirZaets** [comment]
Hi @torhoehn. Thanks for collaboration. Make `local-themes.js` as dist file doesn't have a sense, it will be the same with the case if we make the origin `themes.js` file as dist. Currently, we don't depend to name of custom theme file at all, we can provide any name and any path to custom theme file in the grunt-config.json file that provided out of the box with Magento as `dist` file. 

[There is the documentation ](https://devdocs.magento.com/guides/v2.2/frontend-dev-guide/tools/using_grunt.html)

If you have some concerns or question feel free to ask. Thanks.

**Comment by torhoehn** [comment]
@VladimirZaets I don't want to add .dist-file. It was just an example that the themes.js will be copied to local-themes.js, just like a .dist-file, which has to be copied to be in version control. So my commit will only change that the local-themes.js will be in version control.

**Comment by ihor-sviziev** [comment]
@VladimirZaets we don't want to add this file to magento2 repo, but when it's m2 project - for this project you should be able to commit local-themes.js file into own repo, it shouldn't be ignored.

**Review by josefbehr — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @josefbehr, thank you for the review.
[ENGCOM-3338](https://jira.corp.magento.com/browse/ENGCOM-3338) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.

**Pull request merged**
