### PR TITLE
Align minicart edit and remove icons

### PR DESCRIPTION
**Pull request by brandonsabino**
### Description (*)
Adjusted the margin for minicart edit and remove icons so they may align properly with the quantity info box. 

1. In the minicart edit and remove icon is not aligned. #26652

### Manual testing scenarios (*)
1. Deploy sample data or create a product in the admin panel. 
2. Add a product to the cart.
3. Click on the mini-cart icon.
4. View margins and position with browser developer tools. 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by brandonsabino** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @brandonsabino. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @brandonsabino, here is your [new Magento instance](https://pr-27037.instances.magento-community.engineering).
Admin access: [https://pr-27037.instances.magento-community.engineering/admin_f84d](https://pr-27037.instances.magento-community.engineering/admin_f84d)
Login: `94a0e024` Password: `43072cfedc9a`
Instance will be terminated in up to 3 hours.

**Comment by brandonsabino** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @brandonsabino. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @brandonsabino, here is your [Magento instance](https://i-27037-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27037-2-4-develop.instances.magento-community.engineering/admin_ef6e](https://i-27037-2-4-develop.instances.magento-community.engineering/admin_ef6e)
Login: `a040e16c` Password: `29cd1aa34d4a`
Instance will be terminated in up to 3 hours.

**Comment by brandonsabino** [comment]
@magento I was able to reproduce the changes successfully in each test environment.

**Comment by lenaorobei** [comment]
This PR fixes the same issue as https://github.com/magento/magento2/pull/26654.

Closing this one, because https://github.com/magento/magento2/pull/26654 was opened earlier and the issue is assigned to @chirag-wagento.

**Pull request closed without merging**
