### PR TITLE
Fix to allow use decimals less then 1 in subproducts qty.

### PR DESCRIPTION
**Pull request by likemusic**
Quick fix to allow use decimals less then 1 in subproducts qty.

The same as https://github.com/magento/magento2/pull/14693 but from fork.

### Description

There is impossible to place order from grouped product where subproducts qty less then one.

### Fixed Issues (if relevant)

1. magento/magento2#14692: 'validate-grouped-qty' validation is meaningless

### Manual testing scenarios

1. Set "Qty Uses Decimals" = Yes and Minimum Qty Allowed in Shopping Cart" = 0.01 for all products on any grouped product.
2. Go to groped product page on frontend.
3. Put for all suproducts qty less than 1.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @likemusic. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

**Comment by likemusic** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @likemusic. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @likemusic, here is your [Magento instance](https://i-14752-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-14752-2-3-develop.instances.magento-community.engineering/admin](https://i-14752-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by likemusic** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @likemusic. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @likemusic, here is your [Magento instance](https://i-14752-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-14752-2-3-develop.instances.magento-community.engineering/admin](https://i-14752-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Pull request merged**
