### PR TITLE
Use semantic theme color variables, including global primary/secondary colors

### PR DESCRIPTION
**Pull request by Brengineer**
### Description (*)

This PR updates instances of the predominant blue and orange colors in the Blank and Luma themes to use more semantic variables.
Additionally, it implements global primary and secondary theme colors to make basic global theme changes much easier and more reliable.
There are no visual changes to the default themes on the frontend (except a couple fixes for minor inconsistencies in Luma), and all existing variables (such as button colors) can still be redefined just as before.
However, setting new brand colors in child themes is now much easier and requires fewer code changes.

#### Preconditions
1. Magento 2.x
2. A custom theme which extends from either Magento/blank or Magento/luma

#### Steps to reproduce
1. In the custom theme, create web/css/source/_theme.less
2. Redefine `@active__color`

#### Expected result
1. All elements which use `@color-orange-red1` for their active state should be updated to use the new active color.

#### Actual result
1. In many instances, the orange color persists. Examples: Active item border in account sidebar, active thumbnail in PDP image gallery, active checkout step. (This includes obscure places, such as the selected address for a user with multiple addresses in the shipping step in checkout.)

### Manual testing scenarios (*)

1. Create a custom theme which extends from either Magento/blank or Magento/luma
2. In the custom theme, create web/css/source/_theme.less
3. Redefine `@theme__color__primary`, `@theme__color__primary-alt`, and `@theme__color__secondary`.
4. Redeploy static content
5. Confirm that all instances of default blue and orange have been updated to use new colors (e.g. active item border in account sidebar, active thumbnail in PDP image gallery, active checkout step, etc.)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19467) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @Brengineer. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3596](https://jira.corp.magento.com/browse/ENGCOM-3596) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@Brengineer thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @Brengineer. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
