### PR TITLE
Fix REST controller resulting in a redirection to /checkout/noroute/ when payment exception is thrown during virtual only checkout

### LINKED ISSUE #38020: Very specific header set in main REST controller resulting in a redirection to /checkout/noroute/
Hello, we've found a well-hidden bug in checkout, when paying for a quote containing only virtual products gives an error.

**Steps to reproduce:**
1. Checkout a virtual quote order (Only virtual products) At this point, the only tab is the payment one. The shipping tab does not exist since there is no product to ship.
2. Obtain a payment error
3. The page displays the error, then redirects to /checkout/noroute/

**We've found the source of the problem:**

1. The place-order.js file redirects if the ajax call fails, depending on a request header:  
```
...
).fail(
    function (response) {
        errorProcessor.process(response, messageContainer);
        redirectURL = response.getResponseHeader('errorRedirectAction');
  
        if (redirectURL) {
            setTimeout(function () {
                errorProcessor.redirectTo(redirectURL);
            }, 3000);
        }
    }
...
```
4. The `Magento\Webapi\Controller\Rest` controller adds the value '#shipping' systematically. In the case of a virtual quote, the "shipping" tab does not exist. This line is questionable because it adds a header specific to checkout APIs in a context that is too general:
```
...
} catch (CouldNotSaveException $e) {
     $maskedException = $this->_errorProcessor->maskException($e);
    $this->_response->setException($maskedException);
    $this->_response->setHeader('errorRedirectAction', '#shipping'); // Should be done differently
 } 
...
``` 
5. The step-navigator.js file that manages tabs navigation does not find "#shipping" so redirects to "noroute":
```  
 if ($.inArray(hashString, this.validCodes) === -1) {
    window.location.href = window.checkoutConfig.pageNotFoundUrl;

    return false;
}
``` 

**Reference:**
https://github.com/magento/magento2/blob/c22a9db44a704b892b81746dc5f707fd87f6e5bf/app/code/Magento/Webapi/Controller/Rest.php#L206C7-L206C77

### Additional Steps to reproduce

- Enable PayPal Advance. (I have invalid PayPal credentials but as long as it throws an Exception, it should redirect).
- Add a virtual product.
- Go to checkout.
- Select Payflow Advanced.
- Enter the billing address.
- Click Continue to initial the PayPal Advance. (Receive 400 status on payment-information).
- Redirected to no route.

### PR DESCRIPTION
**Pull request by MoT3rror**
Fix REST controller resulting in a redirection to /checkout/noroute/ when payment exception is thrown during virtual only checkout #38020

### Description (*)
Steps to reproduce:

1. Checkout a virtual quote order (Only virtual products) At this point, the only tab is the payment one. The shipping tab does not exist since there is no product to ship.
2. Obtain a payment error
3. The page displays the error, then redirects to /checkout/noroute/

### Fixed Issues (if relevant)
1. Fixes magento/magento2#38020

### Manual testing scenarios (*)
1. Checkout a virtual quote order (Only virtual products) At this point, the only tab is the payment one. The shipping tab does not exist since there is no product to ship.
2. Obtain a payment error
3. The page displays the error, then redirects to /checkout/noroute/

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by MoT3rror** [comment]
@magento run all tests

**Comment by MoT3rror** [comment]
@magento run Unit Tests

**Comment by MoT3rror** [comment]
@magento run all tests

**Review by Den4ik — COMMENTED** [review]
Bug presented during [AC-2701:: Roll back and Fixed the static tests](https://github.com/magento/magento2/commit/fd7e45e945796afcb39ef96c57121f494d651754) that don't provide any real information why changes changes applied to `Rest.php`
I'm sure that this block shouldn't be presented in `Rest.php`, because changes are related to checkout but presented in webapi module and affect to all api requests. It looks strange.
Could some one from Magento Core Team provide details from AC-2701?

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@glo71317 we need your attention on this comment https://github.com/magento/magento2/pull/38031#pullrequestreview-1732739372. Please take a look.

**Comment by glo71317** [comment]
> @glo71317 we need your attention on this comment [#38031 (review)](https://github.com/magento/magento2/pull/38031#pullrequestreview-1732739372). Please take a look.

@engcom-Hotel and @Den4ik I went through the details and found there is no changes are delivered in `Rest.php` to address this [AC-2701:: Roll back and Fixed the static tests](https://github.com/magento/magento2/commit/fd7e45e945796afcb39ef96c57121f494d651754). Changes are made to address below github issue
https://github.com/magento/magento2/issues/33697 under this jira - https://jira.corp.adobe.com/browse/AC-937

Thanks

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Review by engcom-Hotel — APPROVED** [review]
Failed tests does not related to PR changes. Hence approving the PR.

**Comment by Den4ik** [comment]
As we discussed in Slack it would be good remove not related to Webapi module code from the `Rest.php`
Currents implementation just hide real bug.

**Comment by Den4ik** [comment]
I'll have time on the next week for accurate research this changes and I beloved that I can give suggestion for it

**Comment by engcom-Hotel** [comment]
Hello @Den4ik,

Have you got a chance to check this one? We are waiting for your suggestions.

Thanks

**Comment by engcom-Hotel** [comment]
As per the discussion with @Den4ik on this PR in Slack, he will provide some suggestions on this PR.

**Comment by engcom-Hotel** [comment]
Hello @Den4ik,

Did you get a chance to look into this PR?

Thanks

**Review by Den4ik — APPROVED** [review]
@MoT3rror Thanks for contribution.
@engcom-Hotel I have checked git history about introduced changes and I think that we should move with this PR as is and refactoring the changes introduced for https://github.com/magento/magento2/issues/33697 as separate PR.

**Comment by Den4ik** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
Hi @MoT3rror,

Thank you for your contribution!

After following the given Manual testing scenario, the issue is not reproducible on magento 2.4-develop. 

The checkout/#payment page is not getting redirected to /checkout/noroute/ page for the virtual product chekcout.

Please find the attached video for the same.

As the linked issue is not reproducible, closing this PR. Please feel free to reopen if any other updates are there or we are missing anything.

https://github.com/magento/magento2/assets/51680850/7609aacb-f975-4b1e-8014-e27561ef9e33



Thank you!

**Pull request closed without merging**
