### PR TITLE
Fix for issue #21510: Can't access backend indexers page after creating a custom index

### PR DESCRIPTION
**Pull request by ccasciotti**
### Description (*)

This PR is a fix for issue #21510.

### Fixed Issues (if relevant)

1. magento/magento2#21510: Can't access backend indexers page after creating a custom index

### Manual testing scenarios (*)

1. Implementation of a custom index as the guide: https://devdocs.magento.com/guides/v2.2/extension-dev-guide/indexing-custom.html
2. Login to backend
3. Go to System > Index Management

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ccasciotti. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4440](https://jira.corp.magento.com/browse/ENGCOM-4440) has been created to process this Pull Request

**Review by super-user-test-tool — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-4440](https://jira.corp.magento.com/browse/ENGCOM-4440) has been created to process this Pull Request

**Comment by soleksii** [comment]
Hi @ccasciotti! I cannot reproduce the issue #21510 on 2.3-develop instance.
Please, re-check.
**Manual testing scenario:**
1. Implementation of a custom index as the guide: https://devdocs.magento.com/guides/v2.2/extension-dev-guide/indexing-custom.html
2. Login to backend
3. Go to System > Index Management
:heavy_check_mark: A successful response with the list of indexers
screen

**Comment by ccasciotti** [comment]
Hi @stoleksiy,
I can confirm the issue with the above steps, I can also add that you don't have to run a reindex nor the `setup:upgrade` command. 
The ideal scenario would be to add a new custom index to an existing module following the steps in the official guide.

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed 

Manual testing scenario:

1. Implementation of a custom index as the guide: https://devdocs.magento.com/guides/v2.2/extension-dev-guide/indexing-custom.html;
2. Login to backend;
3. Go to System > Index Management

**Result:**
after

**Pull request merged**
