### PR TITLE
Static versioning and styles minification break email fonts styles #8241

### PR DESCRIPTION
**Pull request by xmav**
Static versioning and styles minification break email fonts styles #8241

### Description
With old version of pelago/emogrifier minified css is not applied to html document(but works fine with normal css). This leads to broken styles in email notifications

### Fixed Issues (if relevant)
1. magento/magento2#8241: Static versioning and styles minification break email fonts styles

### Manual testing scenarios
1. Create an order for user with valid email
2. Check order details email
Actual result:  
Minified inline css is not applied (added by {{inlinecss file="css/email-inline.css"}}) to html document (or applied partially)

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=10638) <br/>All committers have signed the CLA.

**Comment by miguelbalparda** [comment]
This seems to fix only the minification issue but I would still like to process this since the version of this extension is really outdated. Do you foresee any issues in any other parts of the app with this change? Adding @Igloczek to the loop for extra comments.

**Comment by xmav** [comment]
@miguelbalparda No I don't foresee problems with this change

**Comment by xmav** [comment]
https://github.com/magento/magento2/issues/4737
https://github.com/magento/magento2/issues/6946
https://github.com/magento/magento2/pull/9327

**Comment by xmav** [comment]
@miguelbalparda Could you please re-run Travis build? Looks like random failure

**Comment by miguelbalparda** [comment]
Restarted

**Comment by miguelbalparda** [comment]
I'll wait for a reply in https://github.com/magento/magento2/issues/4737 before accepting this PR.

**Review by davidalger — APPROVED** [review]
@miguelbalparda This looks good to me. I see no reason to hold off on merging it.

**Comment by xmav** [comment]
@miguelbalparda Any updates?

**Pull request merged**
