### PR TITLE
Add cache of configuration files list

### PR DESCRIPTION
**Pull request by otakarmare**
Performance result:

| command | before | after |
| --- | --- | --- |
| setup:uninstall | 3s | 0.9 s |
| setup:install | 32s | 16s |

### CODE REVIEW

**Comment by danslo** [comment]
+1 on this. Natively on linux (on an SSD) there is no problem, but when installing via a vagrant box that gets files over a share, there's a lot of this:



And that repeats over and over.

**Comment by robbieaverill** [comment]
Looks like a great improvement to me. +1

**Comment by vancoz** [comment]
Hi @otakarmare, this approach has no cache invalidation, and Reader is questionable place to implement this caching, also it looks inconstant with other methods - getComposerJsonFiles, getActionFiles

**Comment by vancoz** [comment]
Hi @otakarmare, cache invalidation should not be an issue, have a question about getComposerJsonFiles, getActionFiles methods, probably is it good idea to add caching for them too?

**Comment by danslo** [comment]
Indeed cache validation doesn't seem like an issue because this cache is per-request.

**Comment by otakarmare** [comment]
@vancoz I agree that getComposerJsonFiles, getActionFiles copy/paste part of logic with getConfigurationFiles and Magento/Framework/Module/Dir/Reader class has too many responsibilities, but it's another issue and I do not plan to do it in this pull request

**Comment by magento-cicd** [comment]
We have automated a Magento Contributor License Agreement verifier for contributions sent to our GitHub projects.
Please see the CLA agreement in the Pull Request comments.

**Comment by otakarmare** [comment]
I sign CLA
any updates from magento team?

**Comment by vrann** [comment]
Can you please fix Travis builds?

**Comment by Vinai** [comment]
@otakarmare Can you please rebase onto the current develop branch and sign the licence cla agreement? Thanks!

**Comment by mazhalai** [comment]
@otakarmare can you please merge the latest develop and restart builds?

**Comment by mazhalai** [comment]
Internal ticket MAGETWO-50778

**Pull request merged**
