### PR TITLE
Prevent multiple quotations of the same word

### LINKED ISSUE #30104: Elastic Search issue with Synonyms
### Preconditions (*)

1. Magento 2.3.*. 
2. Elasticsearch 6+

Also reproducible on 2.4-develop with Elasticsearch7

### Steps to reproduce (*)

1. Enable Elasticsearch 6+
2. Add a product with a long name with a slash / in it.
Example: LSS 3/8"X3/4"X25' EZ-PULL 1/2" INS SWEAT LINESET W/90 END BEND SUCTION LINE INSULATED
3. Add Search Synonyms with a word belongs to the product name.
Example: center end boot,torpedo boot,horn boot,register boot center end,register boot torpedo
4. Search in the frontend for that exact product.

### Expected result (*)
1. Find that particular product without errors.

### Actual result (*)
1. Error report: {"0":"Warning: preg_match(): Unknown modifier '8' in \/vendor\/magento\/module-search\/Model\/SynonymAnalyzer.php on line 96","1":"#1 preg_match() called at [vendor\/magento\/module-search\/Model\/SynonymAnalyzer.php:96]\n#2 Magento\\Search\\Model\\SynonymAnalyzer->findInArray() called at [vendor\/magento\/module-search\/Model\/SynonymAnalyzer.php:71]

### Additional info
1. Create a product with below product name as mentioned earlier:
image

2. Create a Search Synonyms (Marketing -> Search Synonyms) and clear the cache as mentioned earlier:
image

3. Copy the entire product name and search in frontend.
image

4. Hit enter
image

5. Here is the message from the report:
image

6. Here is my configuration:
image

### PR DESCRIPTION
**Pull request by denchev**
### Description (*)
When there is a long search phrase and some of the words in that phrase has quotes in it, the algorithm for creating a search with synonyms will create multiple scenarios of that phrase. But for each scenario the quoted word would be escaped over and over again. For a long phrase that builds a very large number of escape \ and reaches a limit for the regular expression. 

This fix makes sure that the escape happens only once per scenario.

This also seems to be a regression introduced by this commit 38c4a3e01ebc3dd0d18286efba20d03373deb830 because when reverted to ce1263da089d5b8ca28bc8689480092db0924d33 the functionality works even without the fix from this PR.

### Related Pull Requests
None

### Fixed Issues (if relevant)
1. Fixes magento/magento2#30104

### Manual testing scenarios (*)

1. Enable Elasticsearch 6+
2. Add a product with a long name with a slash / in it.
    Example: LSS 3/8"X3/4"X25' EZ-PULL 1/2" INS SWEAT LINESET W/90 END BEND SUCTION LINE INSULATED
3. Add Search Synonyms with a word belongs to the product name.
    Example: center end boot,torpedo boot,horn boot,register boot center end,register boot torpedo
4. Search in the frontend for that exact product.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by denchev** [comment]
@magento run all tests

**Review by swnsma — CHANGES_REQUESTED** [review]
Hi @denchev,

Please check failed static tests.
I believe, in this case you can use:
        // phpcs:disable Magento2.Functions.DiscouragedFunction

**Comment by denchev** [comment]
@magento run all tests

**Comment by denchev** [comment]
@magento run <Integration Tests>

**Comment by denchev** [comment]
@magento run Integration Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8466](https://jira.corp.magento.com/browse/ENGCOM-8466) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked case from Manual testing scenarios
:x: **Before:**
image

:heavy_check_mark: **After:**
image

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Pull request merged**
