### PR TITLE
Filter config values on testSuiteStart

### PR DESCRIPTION
**Pull request by bcerban**
### Fixed Issues (if relevant)

1. magento/magento2#22370: Filtering ignored config values in test framework causes error

### Manual testing scenarios (*)

1. Set `compiled_config => 1` in `app/etc/env.php` cache types. 
2. Then run the integration test suite. 

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22386) <br/>All committers have signed the CLA.

**Comment by bcerban** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @bcerban. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @bcerban, here is your [Magento instance](https://i-22386-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22386-2-3-develop.instances.magento-community.engineering/admin](https://i-22386-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by bcerban** [comment]
It seems the issue is only affecting version 2.2, and not 2.3. I will proceed to close this PR and open a new one for that branch. Thanks!

**Pull request closed without merging**
