### PR TITLE
[Fixed] - resolve issue with filter visibility with column visibility in grid

### LINKED ISSUE #30345: [Issue] [Fixed] - resolve issue with filter visibility with column visibility in grid
This issue is automatically created based on existing pull request: magento/magento2#28385: [Fixed] - resolve issue with filter visibility with column visibility in grid

---------

### Description (*)

Magento 2.4-develop
I found one common issue which is available with most of the grid was Filter visibility does not work with column visibility.
So I have debugged and Found this solution.
I have checked and changed almost all relevant grid.

I found and applied this changes for the below files.
```
app/code/Magento/Search/view/adminhtml/ui_component/search_synonyms_grid.xml
app/code/Magento/GroupedProduct/view/adminhtml/ui_component/grouped_product_listing.xml
app/code/Magento/Bundle/view/adminhtml/ui_component/bundle_product_listing.xml
app/code/Magento/Sales/view/adminhtml/ui_component/sales_order_invoice_grid.xml
app/code/Magento/Sales/view/adminhtml/ui_component/sales_order_view_invoice_grid.xml
app/code/Magento/Sales/view/adminhtml/ui_component/sales_order_creditmemo_grid.xml
app/code/Magento/Sales/view/adminhtml/ui_component/sales_order_view_creditmemo_grid.xml
app/code/Magento/Sales/view/adminhtml/ui_component/sales_order_shipment_grid.xml
app/code/Magento/Sales/view/adminhtml/ui_component/sales_order_grid.xml
app/code/Magento/Sales/view/adminhtml/ui_component/sales_order_view_shipment_grid.xml
app/code/Magento/Cms/view/adminhtml/ui_component/cms_page_listing.xml
app/code/Magento/Cms/view/adminhtml/ui_component/cms_block_listing.xml
app/code/Magento/ConfigurableProduct/view/adminhtml/ui_component/configurable_associated_product_listing.xml
```
### Steps to reproduce (*)
1. Verify filter visibility for pages where ui component from **Description** is used

### Expected Result
 - Filter visibility should be toggle with column visibility as the same for all columns.

### Actual Result
- On Admin Sales Order grid purchase point filter visibility does not toggle with purchase point column visibility. 

ezgif com-optimize

### PR DESCRIPTION
**Pull request by niravkrish**
### Description (*)

I found one common issue which is available with most of the grid was Filter visibility does not work with column visibility.
So I have debugged and Found this solution.
I have checked and changed almost all relevant grid.

I found and applied this changes for the below files.
```
app/code/Magento/Search/view/adminhtml/ui_component/search_synonyms_grid.xml
app/code/Magento/GroupedProduct/view/adminhtml/ui_component/grouped_product_listing.xml
app/code/Magento/Bundle/view/adminhtml/ui_component/bundle_product_listing.xml
app/code/Magento/Sales/view/adminhtml/ui_component/sales_order_invoice_grid.xml
app/code/Magento/Sales/view/adminhtml/ui_component/sales_order_view_invoice_grid.xml
app/code/Magento/Sales/view/adminhtml/ui_component/sales_order_creditmemo_grid.xml
app/code/Magento/Sales/view/adminhtml/ui_component/sales_order_view_creditmemo_grid.xml
app/code/Magento/Sales/view/adminhtml/ui_component/sales_order_shipment_grid.xml
app/code/Magento/Sales/view/adminhtml/ui_component/sales_order_grid.xml
app/code/Magento/Sales/view/adminhtml/ui_component/sales_order_view_shipment_grid.xml
app/code/Magento/Cms/view/adminhtml/ui_component/cms_page_listing.xml
app/code/Magento/Cms/view/adminhtml/ui_component/cms_block_listing.xml
app/code/Magento/ConfigurableProduct/view/adminhtml/ui_component/configurable_associated_product_listing.xml
```

### Expected Result
 - Filter visibility should be toggle with column visibility as the same for all columns.

### Actual Result
- On Admin Sales Order grid purchase point filter visibility does not toggle with purchase point column visibility. 

ezgif com-optimize

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30345: [Fixed] - resolve issue with filter visibility with column visibility in grid

### CODE REVIEW

**Comment by niravkrish** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @niravkrish. Thank you for your request. I'm working on Magento instance for you

**Comment by niravkrish** [comment]
@magento run all tests

**Comment by niravkrish** [comment]
@magento run Functional Tests CE
@magento run Functional Tests EE
@magento run Functional Tests B2B

**Comment by niravkrish** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @niravkrish. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @niravkrish, here is your [new Magento instance](https://pr-28385.instances.magento-community.engineering).
Admin access: [https://pr-28385.instances.magento-community.engineering/admin_2e30](https://pr-28385.instances.magento-community.engineering/admin_2e30)
Login: `4110fac9` Password: `535307138d0a`
Instance will be terminated in up to 3 hours.

**Comment by sidolov** [comment]
@magento run all tests

**Review by sidolov — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8211](https://jira.corp.magento.com/browse/ENGCOM-8211) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @sidolov . Could you put an appropriate label for test coverage?
Thanks!

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked that

- `Status` fields can be added/removed from Filters on Add Products to Option tab for Bundle product
- `Store View` can be added/removed from Filters on Blocks page
- `Store View` can be added/removed from Filters on Pages page
- `Status` can be added/removed from Filters on Select Associated Product tab for Configurable product
- `Status` can be added/removed from Filters on Add Products to Group tab for Grouped product
- `Purchased From` can be added/removed from Filters on Orders, Invoices, Shipments, Credits Memos pages
- `Store View` and `Website` can be added/removed from Filters on Search Synonyms page

Peek 2020-09-23 15-13

**Review by engcom-Delta — CHANGES_REQUESTED** [review]
Hi @niravkrish Could cover those changes by MFTF tests?

**Comment by engcom-Echo** [comment]
I will take care of test coverage.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8211](https://jira.corp.magento.com/browse/ENGCOM-8211) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Result:**
Filter visibility is toggled with column visibility as the same for all columns.
Peek 2020-09-23 15-13

**Comment by engcom-Delta** [comment]
@magento create issue

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Pull request merged**
