### PR TITLE
Added correction for og:type content value

### PR DESCRIPTION
**Pull request by atishgoswami**
Added correction to the `og:type` meta tag content value.

Before:
`<meta property="og:type" content="og:product" />`

After:
`<meta property="og:type" content="product" />`

References:
[Facebook Open Graph](https://developers.facebook.com/docs/reference/opengraph/object-type/product/)
[Pinterest](https://developers.pinterest.com/docs/rich-pins/products/)

### CODE REVIEW

**Comment by vkublytskyi** [comment]
@atishgoswami, Thank you for your contribution. Please accept the contributors license agreement so this PR can be further processed. This can be done by clicking the "Details" link next to the "license/cla" check below.

**Comment by atishgoswami** [comment]
@vkublytskyi This "licence/cla" is not working, tried it a hundred times, still shows "not signed yet"

**Comment by hostep** [comment]
@atishgoswami: your commit was made with the user @atish-perficient
You should sign the CLA while logged in into github with that user I believe.

**Comment by atishgoswami** [comment]
@hostep Nope still doesn't work

**Comment by atishgoswami** [comment]
I am closing this pull request seems that the `licence/cla` is never going to work for me

**Pull request closed without merging**
