### PR TITLE
Improve product edit page loading speed

### LINKED ISSUE #29409: [Performance] Slow product edit page with big amount of custom options
### Preconditions (*)
1. Magento 2.3.5-p2 or 2.4-develop

### Steps to reproduce (*)
1. Create simple product  OR  import following file:
[export_catalog_product_20200805_133448.zip](https://github.com/magento/magento2/files/5028739/export_catalog_product_20200805_133448.zip)
- Add 8 custom options, each of them with option type "Drop-Down", values - 12 month names (Jan - Dec)
image
image
-  Save the product
2. Open "Cusomizable options" section

### Expected result (*)
1. Browser should load custom options quite fast, 1-2 seconds.

### Actual result (*)
1. Browser becomes really crazy with high CPU load, it loads just this section for at least **5 seconds** and whole page is quite slow during load.

Here is performance profile from Google Chrome extension: 
[Profile-20200805T162549.zip](https://github.com/magento/magento2/files/5028701/Profile-20200805T162549.zip)

### Use case
We would like to provide our customers an ability to customize amount and colors of stones on the product (up to 8 stones, in example each color named as month for simplicity of example).

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by densen45**
### Description (*)

Page loading speed for products with many custom options or bundle products with multiple options with many selections is slow.
The more custom options a product has and the more options and selections a bundle product has, the slower the speed becomes.

In the issue addressed below, several experiences were shared about how slow this can get.

With the changes included in this Pull Request, I was able to reduce the page load time for one of my bundle products (10 options, approx. 160 selections in total) from about 1min 20sec to 35sec.

### Related Pull Requests
https://github.com/magento-gl/magento2-page-builder/pull/53

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29409

### Manual testing scenarios (*)

1. Create a bundle product with one option and add one selection
2. Load the edit page and measure the time until the page becomes fully responsive (JavaScript finishes)
3. Add more options (about 5) and several selections (about 20) to each option
4. Load the page and measure the time again

Another scenario would be to add more and more custom options to a product and note that it takes longer to load the edit page.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by densen45** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Static Tests, WebAPI Tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @densen45,
Looks like your changes caused regression according to functional test results. Could you please double-check it?

**Comment by densen45** [comment]
Hey @ihor-sviziev,
the error (it's the same for all three functional test suites) refer to the PageBuilder. Unfortunately I don't have an environment running PageBuilder to check this.

Can someone else please check this?

**Review by ihor-sviziev — APPROVED** [review]

**Review by ihor-sviziev — APPROVED** [review]

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
So for now I'm approving pull request, and someone please help with fixing test failures

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
Hi @densen45 ,

Thanks for your contribution and collaboration.

After taking PR changes I have observed that performance is improving only 1 sec. But according to the description, It should reduce the loading time more. Below are the steps which I have followed:

1. Installed the latest **MAG2 2.4-develop**
2. Ran data fixtures of [small profile](https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/cli/generate-data.html).
3. Created a bundle product with 3 options 1st option having 2 products, 2nd having 50 products, 3rd having 6 products.
4. Ran `bin/magento indexer:reindex && bin/magento c:f`
5. Used performance measuring tool **lighthouse of chrome** and clicked on **Analyse Page Load**.
6. Observed the result.
Below are screenshots for your reference:

**Before PR changes:**
Screenshot 2023-06-28 at 2 50 21 PM

**After PR changes:**
Screenshot 2023-06-28 at 2 59 23 PM

Can you please provide more information if we are missing anything?

Thanks

**Comment by Quazz** [comment]
This also significantly speeds up inline bulk editing in grids. Without this patch, each additional record takes more time to load. When dealing with large grids, this patch is essential to make it somewhat usable.

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:*

1. Create a bundle product with one option and add one selection
2. Add more options (about 5) and several selections (about 20) to each option
3. Load the page and measure the time.

**Before:** :heavy_multiplication_x: 
**Run1:**
Screenshot 2023-07-11 at 3 24 09 PM

**Run2:**
Screenshot 2023-07-11 at 3 25 43 PM

**Run3:**
Screenshot 2023-07-11 at 3 27 47 PM

**After:** :heavy_check_mark:  _Observed some performance improvement after the PR changes._
**Run1:**
Screenshot 2023-07-11 at 3 32 32 PM

**Run2:**
Screenshot 2023-07-11 at 3 38 31 PM


No additional manual test cases are required as part of regression as this PR is related to performance improvement.

Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Unit Tests,Integration Tests,Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Static Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests CE ,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Echo** [comment]
WebAPI Tests failure are not related to PR. Functional Tests B2B failure are different on last two run on same commit.
Functional Tests B2B
Run1
Screenshot 2023-09-08 at 11 01 42 AM

Run2
Screenshot 2023-09-08 at 11 01 46 AM

Hence moving to `merge in progress`

**Comment by Nuranto** [comment]
@densen45 We just applied your fix, and it makes a huge difference (loading time divided by more than 3 in our test case). All our backend team and myself thank you for that !

**Comment by Nuranto** [comment]
Got it : 

Capture d’écran 2023-12-12 à 14 36 31

With foreach, the `return` was terminating the foreach callback function. But now with `for` it's terminating the whole `processAdded` function :/

**Comment by ihor-sviziev** [comment]
@Nuranto, can you please create pull request for this change?

**Comment by ihor-sviziev** [comment]
Onfortunately, this change caused regression, see https://github.com/magento/magento2/issues/38622 (related fixes https://github.com/magento/magento2/pull/38276 https://github.com/magento/magento2/pull/38623)

**Pull request merged**
