### PR TITLE
Fix for admin shipment, creditmemo, invoice pdf emulation

### PR DESCRIPTION
**Pull request by ksz2013**

### CODE REVIEW

**Comment by NadiyaS** [comment]
Hi @ksz2013 ,
Please follow [Magento coding Standarts](http://devdocs.magento.com/guides/v2.0/coding-standards/code-standard-php.html) in your code:
- property names [SHOULD NOT be prefixed with a single underscore](http://www.php-fig.org/psr/psr-2/#4-2-properties) to indicate protected or private visibility. 
- All non-public properties and methods SHOULD be private
- backward incompatible changes are not allowed: 
  If you need to change constructor signature to inject new dependency within existing class, please make it in next way:
  - Introduce a private getter for the new dependency (getNewDependency() in the example below).
  - Within getNewDependency() method, use Magento\Framework\App\ObjectionManager::getInstance() to obtain the new dependency and initialize the member variable accordingly. 
  - Use $this->getNewDependency() where ever that dependency is needed within the class
  - In unit tests use Reflection to make the member variable accessible and inject a mocked object
  - In the unit test class, as part of setUp(), inject the appropriate mock object for the new dependency ($newDependencyMock in the example below).
  - To discourage the use of the getter method else where outside the capacity of this specific fix, please mark it as @deprecated
  - E.g. https://github.com/magento/magento2/blob/79c551bea7ea14c38d6f7620a6c6fbadd2f9fd2e/lib/internal/Magento/Framework/Reflection/TypeProcessor.php#L68

**Comment by aakimov** [comment]
Hi @ksz2013,

Unfortunately we cannot accept your pull request as is.
It will be closed.

Thank you for your understanding and interest in Magento.

**Comment by gabrieldagama** [comment]
Hi @ksz2013. Thank you for your report. 
The issue has been fixed in magento/magento2#31369 by @chiranjeevi-cj in 2.4-develop branch
Related commit(s):
 - [628a1e4247dabe95ed2e343a37ed945a39811b7f](https://github.com/magento/magento2/commit/628a1e4247dabe95ed2e343a37ed945a39811b7f)
 - [c16f995ae5a10e037841f2624ebf1e6987f5cba9](https://github.com/magento/magento2/commit/c16f995ae5a10e037841f2624ebf1e6987f5cba9)
 - [cfbc08c8957ab7a23fc3a6c074303950c93e126c](https://github.com/magento/magento2/commit/cfbc08c8957ab7a23fc3a6c074303950c93e126c)
 - [6cb297ba167aa95aaa0f2f9fa000292dcfaabd1a](https://github.com/magento/magento2/commit/6cb297ba167aa95aaa0f2f9fa000292dcfaabd1a)
 - [8584f85dbb74fd6b4a014d6f2199849446302d96](https://github.com/magento/magento2/commit/8584f85dbb74fd6b4a014d6f2199849446302d96)
 - [ee667ff1e80c685b27bbe129bce1e4ff43d887bb](https://github.com/magento/magento2/commit/ee667ff1e80c685b27bbe129bce1e4ff43d887bb)
 - [af5765d2af52f59d364f7b2b0d035387ad8733bc](https://github.com/magento/magento2/commit/af5765d2af52f59d364f7b2b0d035387ad8733bc)
 - [7cf765776bec638224b4a3ea1c1bf51def4249d7](https://github.com/magento/magento2/commit/7cf765776bec638224b4a3ea1c1bf51def4249d7)
 - [db1be3fd789c37aaa4642f4c49e5fd48e84dc1c8](https://github.com/magento/magento2/commit/db1be3fd789c37aaa4642f4c49e5fd48e84dc1c8)
 - [0b5401fa48ae61878f7a250ab589baf3c05b5070](https://github.com/magento/magento2/commit/0b5401fa48ae61878f7a250ab589baf3c05b5070)
 - [2a50bef5f0de67af8523634152d82ab6d3dc1ee5](https://github.com/magento/magento2/commit/2a50bef5f0de67af8523634152d82ab6d3dc1ee5)
 - [f786e391d55ab74766746a11d38f7ced7b191e30](https://github.com/magento/magento2/commit/f786e391d55ab74766746a11d38f7ced7b191e30)
 - [427e14bb26708814b5da86762859cb66a539f5cf](https://github.com/magento/magento2/commit/427e14bb26708814b5da86762859cb66a539f5cf)
 - [2610382271595e0f949fb589fe808a1a31733961](https://github.com/magento/magento2/commit/2610382271595e0f949fb589fe808a1a31733961)
 - [350ba942405e61fd94c4da9651d140dfc8a9a69b](https://github.com/magento/magento2/commit/350ba942405e61fd94c4da9651d140dfc8a9a69b)
 - [a57297cd8badc7d9828e3a447b1925bdc6eb52e9](https://github.com/magento/magento2/commit/a57297cd8badc7d9828e3a447b1925bdc6eb52e9)
 - [200771d68166d4e43e1c4b843659174295828c91](https://github.com/magento/magento2/commit/200771d68166d4e43e1c4b843659174295828c91)
 - [01a656ff2a318edbcc179231e31ad9b3c8565066](https://github.com/magento/magento2/commit/01a656ff2a318edbcc179231e31ad9b3c8565066)
 - [ed701258ce3d061899cf8d1e7143b67ca77830f9](https://github.com/magento/magento2/commit/ed701258ce3d061899cf8d1e7143b67ca77830f9)
 - [4f4b98aed68992d1c1ae3850274ebf877bd6fcb8](https://github.com/magento/magento2/commit/4f4b98aed68992d1c1ae3850274ebf877bd6fcb8)
 - [54d95d0dd537d03777677d608b46d0f44a99d606](https://github.com/magento/magento2/commit/54d95d0dd537d03777677d608b46d0f44a99d606)
 - [447f3c6cae9e9d1b4b97b5850d138bf6e0b02723](https://github.com/magento/magento2/commit/447f3c6cae9e9d1b4b97b5850d138bf6e0b02723)
 - [f5fde08d6962184cea558ce97f06dacb767aebf5](https://github.com/magento/magento2/commit/f5fde08d6962184cea558ce97f06dacb767aebf5)
 - [7728961a7d8a5dee0ce6f3567e3f6dd768ade793](https://github.com/magento/magento2/commit/7728961a7d8a5dee0ce6f3567e3f6dd768ade793)
 - [354d3f6c07ee7f192ae14a3d40b1507045f045b6](https://github.com/magento/magento2/commit/354d3f6c07ee7f192ae14a3d40b1507045f045b6)
 - [6c1e76eece3b822165a87e20bdf177c68a8f0612](https://github.com/magento/magento2/commit/6c1e76eece3b822165a87e20bdf177c68a8f0612)
 - [13f32b63cb06459f11718d734c96fc5541548e4e](https://github.com/magento/magento2/commit/13f32b63cb06459f11718d734c96fc5541548e4e)
 - [0b09f8ce5dc8bd5d381a8041b09770a0f44270aa](https://github.com/magento/magento2/commit/0b09f8ce5dc8bd5d381a8041b09770a0f44270aa)
 - [c95fee989c7e22e868d0d3a2b84f613881ffa975](https://github.com/magento/magento2/commit/c95fee989c7e22e868d0d3a2b84f613881ffa975)
 - [bdf967d701edfbf2d334bcb30f5bbc382c9480d3](https://github.com/magento/magento2/commit/bdf967d701edfbf2d334bcb30f5bbc382c9480d3)

The fix will be available with the upcoming 2.4.3 release.

**Comment by gabrieldagama** [comment]
Hi @ksz2013. Thank you for your report. 
The issue has been fixed in magento/magento2#31938 by @ProkopovVitaliy in 2.4-develop branch
Related commit(s):
 - [98e089e2b3a29a481a999eac3f0e39815047e002](https://github.com/magento/magento2/commit/98e089e2b3a29a481a999eac3f0e39815047e002)
 - [4b0bf14cbaef041ae6dea0f6e341ef08a12c2b17](https://github.com/magento/magento2/commit/4b0bf14cbaef041ae6dea0f6e341ef08a12c2b17)
 - [017de9a326d18eb624b69fd9a4f67650bcfe1c8c](https://github.com/magento/magento2/commit/017de9a326d18eb624b69fd9a4f67650bcfe1c8c)
 - [3682d87461e55ec6b25d04e64dcb1bff3740f76f](https://github.com/magento/magento2/commit/3682d87461e55ec6b25d04e64dcb1bff3740f76f)
 - [67e3881581e81f01b777d0db53945c94e68d27f7](https://github.com/magento/magento2/commit/67e3881581e81f01b777d0db53945c94e68d27f7)
 - [e7b3b4d3c63849dbebf26491021eba53bc7b8b50](https://github.com/magento/magento2/commit/e7b3b4d3c63849dbebf26491021eba53bc7b8b50)
 - [8916deeaab1dfad091b43bca0797cd9f72f1a0de](https://github.com/magento/magento2/commit/8916deeaab1dfad091b43bca0797cd9f72f1a0de)

The fix will be available with the upcoming 2.4.3 release.

**Comment by gabrieldagama** [comment]
Hi @ksz2013. Thank you for your report. 
The issue has been fixed in magento/magento2#31809 by @vlmed in 2.4-develop branch
Related commit(s):
 - [b01435e75ef8a7a9daa045944988243669dac24f](https://github.com/magento/magento2/commit/b01435e75ef8a7a9daa045944988243669dac24f)
 - [7f1dd3f32e0dc50d041a051d422b18983dbe63ba](https://github.com/magento/magento2/commit/7f1dd3f32e0dc50d041a051d422b18983dbe63ba)

The fix will be available with the upcoming 2.4.3 release.

**Comment by gabrieldagama** [comment]
Hi @ksz2013. Thank you for your report. 
The issue has been fixed in magento/magento2#31969 by @vlmed in 2.4-develop branch
Related commit(s):
 - [fad5e616c2c28be1ca7c10456bbc87d88720232e](https://github.com/magento/magento2/commit/fad5e616c2c28be1ca7c10456bbc87d88720232e)

The fix will be available with the upcoming 2.4.3 release.

**Comment by sidolov** [comment]
Hi @ksz2013. Thank you for your report. 
The issue has been fixed in magento/magento2#33124 by @vlmed in 2.4-develop branch
Related commit(s):
 - [ff21e6db5d1efc0492e043addd5d201f040a06a3](https://github.com/magento/magento2/commit/ff21e6db5d1efc0492e043addd5d201f040a06a3)
 - [52c72cd5a4f7f37d30407f7feccb2c1f8047776f](https://github.com/magento/magento2/commit/52c72cd5a4f7f37d30407f7feccb2c1f8047776f)

The fix will be available with the upcoming 2.4.3 release.

**Comment by sidolov** [comment]
Hi @ksz2013. Thank you for your report. 
The issue has been fixed in magento/magento2#34620 by @ravi-chandra3197 in 2.4-develop branch
Related commit(s):
 - [f2daffdc95a9cf1f7220b08c8f887e1d049350ea](https://github.com/magento/magento2/commit/f2daffdc95a9cf1f7220b08c8f887e1d049350ea)

The fix will be available with the upcoming release.

**Pull request closed without merging**
