### PR TITLE
[Ui] Fixing the changing state of dropdown's icon

### PR DESCRIPTION
**Pull request by eduard13**
### Description (*)
This PR fixes the state changing of the dropdown items, and a small styling issue related to the dropdown options.

### Fixed Issues (if relevant)

1. magento/magento2#21196: [UI] The dropdown state doesn't change if the dropdown is expanded or not
2. ...

### Manual testing scenarios (*)
1. Check task's steps
2. 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by sdzhepa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4270](https://jira.corp.magento.com/browse/ENGCOM-4270) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [new Magento instance](https://pr-21197.instances.magento-community.engineering).
Admin access: [https://pr-21197.instances.magento-community.engineering/admin](https://pr-21197.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sdzhepa** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-21197-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21197-2-3-develop.instances.magento-community.engineering/admin](https://i-21197-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Pull request merged**
