### PR TITLE
Add loading lazy for also for ko templates

### PR DESCRIPTION
**Pull request by in-session**
### Description (*)
Add lazy loading images on supported browsers for ko templates minicart/order summary and admin products grid 

Ashampoo_Snap_Dienstag, 7  Dezember 2021_12h40m59s_006_
Ashampoo_Snap_Dienstag, 7  Dezember 2021_12h40m28s_005_
Ashampoo_Snap_Dienstag, 7  Dezember 2021_12h41m29s_007_
Ashampoo_Snap_Dienstag, 7  Dezember 2021_12h42m52s_008_

### CODE REVIEW

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@magento run Semantic Version Checker, Functional Tests EE, Functional Tests CE, Unit Tests

**Comment by ihor-sviziev** [comment]
@magento create issue
@sidolov I set priority to P2 as this change improves performance by lazy loading images [on supported browsers](https://caniuse.com/loading-lazy-attr)

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests look not related to changes from this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9333](https://jira.corp.magento.com/browse/ENGCOM-9333) has been created to process this Pull Request

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9333](https://jira.corp.magento.com/browse/ENGCOM-9333) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE, Unit Tests

**Comment by in-session** [comment]
The other question about the adaptation is whether it would not make sense to integrate a Lazyload libary? 99% of the lazyload libary triggers the images with the class name lazyload. I would also suggest lazysizes here in combination with Pagebuilder.
We have had the best experience with this.

https://github.com/magento-devdocs/pagebuilder-examples/tree/master/Image/LazyLoading
https://github.com/aFarkas/lazysizes

```
<script>
    if ('loading' in HTMLImageElement.prototype) {
        const images = document.querySelectorAll('img[loading="lazy"].lazyload');
        images.forEach(img => {
            if(img.dataset.src !== ''){
                img.src = img.dataset.src;
                img.classList.add("lazyloaded");
                img.classList.remove("lazyload"); 
            }
        });
    }
    window.lazySizesConfig = window.lazySizesConfig || {};    
    window.lazySizesConfig.init = false;
    lazySizesConfig.loadHidden = false;
    lazySizesConfig.expand = 0;
    lazySizesConfig.loadMode = 1;
</script>
```

```
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

var config = {
    paths: {
        'lazysizes': 'lib/lazysizes/lazysizes.min',
        'lazysizesAttrchange': 'lib/lazysizes/plugins/attrchange/ls.attrchange.min',
    },
    deps: [
       'lazysizesAttrchange'
    ],
    shim: {
        'lazysizes': {
            exports: 'lazySizes'
        },
        'lazysizesAttrchange': {
            deps: ['lazysizes']
        }
    }
};

```

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @in-session and @ihor-sviziev 
Thanks for your contribution and collaboration!

There is no description/information in which are the UI pages the lazy loading have been applied. By looking into the code changes, I tried to see the lazy load feature in _Admin>Catalog>Products list_ page and _front end> Product Details page_. But the lazy load not reflected successfully in the mentioned UI pages.

Below is the screenshot of _Admin>Catalog>Products list_ page where it shows all the images are loaded in the first request only (I had selected to display 200 products in the grid in one page)!

Screenshot 2021-12-07 at 4 27 34 PM


@in-session Request you to kindly check once if there is any additional code changes required, or should I validate in difference UI pages?

**Comment by in-session** [comment]
@engcom-Alfa 
The changes in PR only affect to the frontend: https://github.com/magento/magento2/pull/34558/files

**Comment by in-session** [comment]
@magento give me test instance

**Comment by in-session** [comment]
@engcom-Alfa
I changed the PR it is also working on admin section: (Gridsettings 200 products)
Ashampoo_Snap_Dienstag, 7  Dezember 2021_12h30m03s_003_

**Comment by in-session** [comment]
@magento run all tests

**Comment by in-session** [comment]
@ihor-sviziev 
Failing tests look not related to changes from this PR.

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9333](https://jira.corp.magento.com/browse/ENGCOM-9333) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Alfa** [comment]
@magento give me test instance

**Comment by engcom-Alfa** [comment]
> @engcom-Alfa I changed the PR it is also working on admin section: (Gridsettings 200 products)
> 
> Ashampoo_Snap_Dienstag, 7 Dezember 2021_12h32m23s_004_

Thanks for the reply @in-session 
Using a cloud test instance I am able to notice the difference, and it is reflected! Thanks :)

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9333](https://jira.corp.magento.com/browse/ENGCOM-9333) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests EE

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests EE

**Review by engcom-Alfa — APPROVED** [review]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Should have Magento latest clean instance installed with Sample data


**Manual testing scenario:**

1. Navigate to Admin > Catalog > Products

2. Select the 200 products to be displayed per page instead of default value 20
 
3. Inspect the element network tab with img section filtered with searched label product.

4. Refresh the page and check the logged image requests

5. After loading the page, start scrolling down the grid and check more image requests are being processed


**Before:** :heavy_multiplication_x: All 200 images used to be requested in the first page load request only


**After:** :heavy_check_mark: Only limited image requests are being made, further images are getting requested however the grid scrolls down further.

There is no further testing is required on this or additional regression is required since it is just a part of lazy loading issue!

**Comment by engcom-Alfa** [comment]
There is an auto-test failing @magento run Functional Tests EE and so moving it to Extended testing, else bot keeps automatically moving it back to Ready For Testing!

**Comment by in-session** [comment]
@magento run Functional Tests EE

**Comment by ihor-sviziev** [comment]
@engcom-Alfa, the tests are passing, so I'm moving it to ready for merge

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests EE

**Pull request merged**
