### PR TITLE
Update Frontend Development Workflow type's comment to be clearer

### PR DESCRIPTION
**Pull request by navarr**
### Description (*)
An implementor expressed confusion, thinking that the comment applied to the value displayed in the setting as opposed to the setting itself.

This commit makes the meaning of the comment clearer - in that, rather than the setting not being available, it has no effect.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
Functional test failures not related to changes from this PR

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7079](https://jira.corp.magento.com/browse/ENGCOM-7079) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

The comments are modified

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Pull request merged**
