### PR TITLE
Fix issue #4470: allow numbers in vendor and class names

### PR DESCRIPTION
**Pull request by nhp**
As there are many companies that use numbers in their name it would be good to allow those to use them in their classes and vendor names.

### Description
To enable a widely used naming scheme, with numbers, the xsd files needed to be adapted else the names could not be validated

### Fixed Issues (if relevant)
1. magento/magento2#4470: import.xsd doesn't allow numbers in vendor name and class name

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by orlangur** [comment]
Any idea why we need underscore allowed?

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=11062) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=11062) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: nhp<br/>:x: paliarush<br/>:x: viktym

**Comment by vkublytskyi** [comment]
@nhp thank you for this contribution.

Provided regex allows invalid value such as `1invalidClassName`. As Model name potentially could be any valid PHP class name (FQCN to be precise) and according to [PHP documentation ](http://php.net/manual/en/language.variables.basics.php) full regexp should looks like:
```
(?:\\?[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*)+
```

**Comment by magento-engcom-team** [comment]
Hi @nhp 
We are closing this Pull Request now due to inactivity. Additionally, some misplaced commits are present in changeset at the moment. 

If you wish to proceed please create a new PR or reopen this one fixing up the history.

Thank you.

**Pull request closed without merging**
