### PR TITLE
WIP: FIX #8897: "Use default" mechanism for Admin GUI and APIs

### LINKED ISSUE #8897: Saving product with non-default store scope causes untouched attributes to become store scoped if loaded using ProductRepository
This is related to #7720 and #7879 and #9486 
### Preconditions
1. Magento 2.4-develop

### Steps to reproduce
1. Create a simple product that belongs to multiple websites.
2. In a script, change the current store to non-default store
3. Load the product using the ProductRepository class
4. Change an attribute value for the loaded product
5. Save the product either using the ProductRepository class or calling $product->save() (deprecated)
```
$this->storeManager->setCurrentStore(2);
$product = $this->productRepository->getById(1, true, 2);
$product->setShortDescription('Setting short desc');
$this->productRepository->save($product); // or $product->save();
```

### Expected result
1. The value for `short_description` should be overridden, all other attributes should remain as **Use default value**

### Actual result
1. All store scoped eav attributes are overridden. Values other than `short_description` are copied over from the default store scope values.

You can see the results of this by checking the `catalog_product_entity_text` table and seeing that new values for not just `short_description`, but `description` and `meta_keyword` as well. Checking the `catalog_product_entity_{varchar,int,decimal,etc}` tables will also show new entries for store scope 2 even though none of that was modified.

Checking the how the admin backend handles this, it seems the Save controller requires passing in values for whether to use default values in a param `use_default`. (https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/Controller/Adminhtml/Product/Initialization/Helper.php#L171) 
This makes it tightly coupled to the admin ui, and so it is hard to replicate proper save behaviour in code.

The use case is that products are being pushed externally via the Magento api, but this makes it so that doing store scoped save operations means anytime something is changed in default scope, it needs to also update in all store scopes independently rather than inheriting from default scope like it should.

### LINKED ISSUE #9186: REST API catalogProductRepositoryV1 overwriting default values
# Preconditions

1. Magento 2
### Steps to reproduce

This demonstration is only with a single storeview, but can be reproduced with multiple storeviews or multiple websites like already mentioned by a bunch of other reporters above

1. Setup a clean Magento installation using the 2.2-develop branch (I used commit eb84c5393da)
2. Go into the backend
3. Make a note of the default storeview code, it's `default` (we'll need this later when we create an API request)
4. Create a new product:
    - name: "Base"
    - SKU: "base"
    - price: 100
    - description: "Base"
    - short description: "Base"

5. Look at the various `catalog_product_entity_int`, `catalog_product_entity_text`, `catalog_product_entity_varchar` tables in the database, they contain only values for store_id = 0, this is **good so far**!
6. Still in the backend, go to System > Integrations and add a new integration with full access
7. Activate the new integration and take a note of the 'access token' (example: `abc`)
8. Execute the following curl command, which only updates the "name" attribute, using the storeview code from 3, and the access token from 7:
```
curl -k -X PUT -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer abc" -d "{ \"product\": { \"name\": \"New name on storeview level\" }}" https://domain/rest/default/V1/products/base
```

9. Go back in the backend and take a look at the product, but switch to the 'Default Store View' scope.
10. It is expected that the 

11. Also take a look at the database again, to the `catalog_product_entity_int`, `catalog_product_entity_text`, `catalog_product_entity_varchar` tables, it is expected you'll only see one entry for store_id = 1, but there are like 10 entries, **not good**!

# Expected result

Only attribute where the checkmark "Use Default Value" is unchecked is for the attribute "name"

# Actual result

All the following attributes now also have a value on storeview level, which is not what is expected:
    - status
    - tax class
    - visibility
    - description
    - short description
    - url key
    - meta title
    - meta keywords
    - meta description
    - display product options in

### LINKED ISSUE #17186: REST API Category translation
### Additional information

test case steps description : https://github.com/magento/magento2/issues/17186#issuecomment-528501666

### Preconditions

1. Magento 2.2.3 & 2.3.x

### Steps to reproduce

1. Send REST PUT request to translate category name in specific store view : {{BaseURL}}rest/{{codeStoreView}}/V1/categories/{id}

`{
	"saveOptions": true,
	"category": {
		"id": 3,
		"name": "New Category Name Translated"
	}
}`

### Expected result

1. It should only update the category name field and create only one row in database for the specific store view

### Actual result

1. The request uncheck Enable Category, Include in Menu, Category Image, etc... attributes and create multiple rows in database for the specific store view

### LINKED ISSUE #26484: Updating a product through the API unchecks "Use Default Value" on a bunch of attributes
When you update a product. For example adding an image using the API. Which is totally unrelated to anything else, such as editing price.

The checkbox "Use Default Value" becomes unchecked on a bunch of attributes, such as price.

This turns into a problem when you want to edit the product later, update the price, or the description etc. and nothing happens. So you have to change store view scope to that particular store, check the box "Use Default Value" and save to be able to change the price.

This should not happen in the first place.

### Preconditions (*)

1. Magento 2.3.3
2. 2 store views

### Steps to reproduce (*)

1. Create 2 store views
2. Add a new product with a price
3. Change store view on the product. You can see "Use Default Value" for price is checked.
4. Update the product using the API, for example uploading an image
5. View the product again and change store scope
6. Notice the "Use Default Value" on price is now unchecked (amongst other attributes)

### Expected result (*)

Checkbox "Use Default Value" should remain checked until a user actually unchecks it.

### Actual result (*)

Checkbox "Use Default Value" unchecks itself when you update the product using the API for all store views.

### Additional info 
I just re-produced it on 2.4-dev.

Seems to be a problem with scopes.

In addition to the steps above, do the following:

1. Stores > All Stores. Click "Main Website Store" and change "Default Store View" to the second store view

image

2. Open "Default Store View" and change to status to disabled
3. Go into product, select scope "Default store view" (first store) Click "Use Default Value" on everything. Save.
4. Change store scope to second store view. Click "Use Default Value" on everything. Save.
5. Change scope to second store view again. A bunch of "Use Default Value" are unchecked.

image

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
1. Address the issue
1. Cover with tests (Integration and API Functional)
1. Fix the issue

### Fixed Issues (if relevant)
1. magento/magento2#8897
1. magento/magento2#4952
1. magento/magento2#9186
1. magento/magento2#26484
1. magento/magento2#17186

### Manual testing scenarios (*)
TBD

### Questions or comments
Side effects:
1. Reduced EAV tables size, due to the removal of duplicated data.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Support
Solving this issue is supported by [Mediotype](mediotype.com)

### CODE REVIEW

**Comment by hostep** [comment]
Thanks for working on this @lbajsarowicz!

Is this going to fix https://github.com/magento/magento2/issues/9186 & https://github.com/magento/magento2/issues/26484 as well? (those are duplicates btw, there are probably a lot more tickets in github mentioning the same issue)

**Comment by lbajsarowicz** [comment]
@hostep Yes, my changes are going to fix most of these.

**Comment by lbajsarowicz** [comment]
@magento run all tests

I have no idea why it hasn't started o.O

**Comment by lbajsarowicz** [comment]
I've extracted `url_key` / `url_path` part from this PR to separate one https://github.com/magento/magento2/pull/27291

**Comment by lbajsarowicz** [comment]
I'm really sorry to disappoint you, as - due to limited time - I was unable to fix that before 2.4 feature freeze. I'm going to fix that before 2.5

**Pull request closed without merging**
