### PR TITLE
Updated colinmollenhour/cache-backend-redis to ^1.14

### PR DESCRIPTION
**Pull request by drpayyne**
### Description (*)

Updated composer dependency colinmollenhour/cache-backend-redis to ^1.14

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/558

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32871

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by drpayyne** [comment]
@magento run all tests

**Review by Den4ik — APPROVED** [review]
✅ Approved

Failed tests is not related to PR

**Comment by Den4ik** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by Den4ik** [comment]
@magento run Functional Tests CE

**Review by Den4ik — APPROVED** [review]

**Comment by sivaschenko** [comment]
@drpayyne thanks for the pull request! Can you please also create a related EE PR?

**Comment by Den4ik** [comment]
@drpayyne Could you please resolve merge conflict?

**Comment by drpayyne** [comment]
Done, @Den4ik!

@sivaschenko - https://github.com/magento/partners-magento2ee/pull/558

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]

**Comment by Den4ik** [comment]
@magento run Functional Tests B2B

**Pull request merged**
