### PR TITLE
Fixed the condition rule for simple and configurable

### LINKED ISSUE #37487: Cart Price Rule is applied while it should not be applied when using the condition 'If an item is NOT FOUND  in the cart with ALL  of these conditions true'
### Preconditions and environment

Magento version 2.4.5-p1

### Steps to reproduce

1. Create a Cart Price Rule with any discount and with the condition 'If an item is NOT FOUND  in the cart with ALL  of these conditions true':
image
2. Go to the storefront and add sku aaa111bbb222 to the shopping cart
3. Go to the shopping cart and notice that the discount is **not applied**. So far, so good (conditions were not met)
4. Add any other sku to the cart and notice that the discount is **applied**. 

### Expected result

The discount should **not be applied**, since the conditions are not met. sku aaa111bbb222 is still in the cart and the rule should only be applied if this product is not found.

### Actual result

The discount is **applied**.

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Vasudev-22**
### Description (*)

1. Create a Cart Price Rule with any discount and with the condition 'If an item is NOT FOUND in the cart with ALL of these conditions true':
Screenshot 2023-06-21 at 5 23 32 PM
Screenshot 2023-06-21 at 5 26 33 PM

2. Go to the storefront and add sku MJ09 to the shopping cart (which is configurable and tried with simple as well)
3. Go to the shopping cart and notice that the discount is not applied.
Screenshot 2023-06-21 at 5 27 15 PM 
4. Add any other sku to the cart and notice that the discount is applied. -> Fixed, it won't apply.
Screenshot 2023-06-21 at 5 28 20 PM

### Related Pull Requests
https://github.com/magento/magento2/issues/37487

### Fixed Issues (if relevant)

1. Fixes magento/magento2#37487

### Manual testing scenarios (*)

1. Tested by adding simple products in rule and frontend, it works
2. Tested by adding configurable products in rule and frontend, it works

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Vasudev-22** [comment]
@magento run all tests

**Comment by Vasudev-22** [comment]
@magento run all tests

**Comment by Vasudev-22** [comment]
@magento run Sample Data Tests B2B

**Comment by Vasudev-22** [comment]
@magento run Sample Data Tests B2B, Sample Data Tests EE, Sample Data Tests CE

**Comment by Vasudev-22** [comment]
@magento run Integration Tests

**Comment by Vasudev-22** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @Vasudev-22,

Thanks for the contribution!

But it seems the fix is already been merged with the 2.4-develop branch in this commit https://github.com/magento/magento2/commit/abf434f3f84bd14bc3c0011949aa0c80b16fb620

We request you to please resolve the conflicts so that we can move further with this PR.

Thanks

**Comment by engcom-Charlie** [comment]
As per this, closing [this](https://github.com/magento/magento2/pull/37648#pullrequestreview-1536380515) PR now. Please feel free to reopen for any further updates.

**Pull request closed without merging**
