### PR TITLE
Update registration files formatting

### PR DESCRIPTION
**Pull request by davidalger**
Adding a simple use statement to tighten up the code :)

### CODE REVIEW

**Comment by orlangur** [comment]
There is a failure in integration tests after these changes:
https://travis-ci.org/magento/magento2/jobs/87774509
```
There was 1 failure:
1) Magento\Setup\Console\Command\DependenciesShowFrameworkCommandTest::testExecute
Failed asserting that '"Dependencies of framework:","Total number"
,2
"Dependencies for each module:",
"Magento\A",1
" -- Magento\Framework",2
"Magento\B",1
" -- Magento\Framework",2
' contains ""Magento\A",1
" -- Magento\Framework",3
".
/home/travis/build/magento/magento2/dev/tests/integration/testsuite/Magento/Setup/Console/Command/DependenciesShowFrameworkCommandTest.php:77
```

**Comment by davidalger** [comment]
@orlangur I'll run the test locally to see what's setting it off and post back when I figure it out.

**Comment by davidalger** [comment]
@orlangur This should be taken care of in bbede1146. The issue was `DependenciesShowFrameworkCommandTest` relied on an assumption that there were two references to `Magento\Framework` in the mock modules' registration.php files. Since I removed one of them by introducing the use directive, the test was operating under an incorrect assumption. I updated the test to make the correct assertion and it ran successfully for me on local.

**Comment by orlangur** [comment]
Good :+1: I supposed it was a fragile test rather than a new problem introduced by changes.

**Comment by dsikkema-magento** [comment]
Internal ticket created: MAGETWO-46377

**Comment by dsikkema-magento** [comment]
Thank you for your willingness to contribute, but I don't think we'll accept this right now, for the simple reason that it would be more consistent to make the corresponding changes to dozens of other modules in other packages (such as EE modules), and only internal developers have access to that.

**Comment by davidalger** [comment]
@vrann / @ishakhsuvarov 

Any chance this might be re-looked at if I took the time to resolve the conflicts that have cropped up since it was closed in 2016?

**Comment by orlangur** [comment]
@davidalger could you provide an automated way to reproduce such changes?

I don't think it is reasonable to resolve conflicts, we just need an automated way to do it quickly in ce/ee/b2b.

Generally, I'm going to replace all FQCN with aliases, which will cover those `registration.php` files as well, do you still think we should merge this change separately?

**Comment by davidalger** [comment]
@orlangur I will see what I can do.

**Comment by ishakhsuvarov** [comment]
Hi @davidalger 
Any progress on this? Do you need any assistance?

**Comment by okorshenko** [comment]
Hi @davidalger Do you need some help?

**Comment by davidalger** [comment]
@okorshenko / @ishakhsuvarov 

Sorry it took me so long to get back to this. I've updated the branch and applied the change to all the new registration.php files.

Here is how I did it:

```
find . -type f -name registration.php | xargs -n 1 \
    perl -0777 -pi -e 's#(.*)::register\(\n.*(ComponentRegistrar::.*),\n\s+(.*),\n\s+(.*)\n#\nuse $1;\n\nComponentRegistrar::register($2, $3, $4#'

find . -type f -name registration.php | xargs -n 1 php -l | grep -v 'No syntax errors detected'

git status -s
```

**Comment by Ctucker9233** [comment]
@magento-team I don't see this PR in 2.2 as of 2.2.7. Should it be ported?

**Comment by orlangur** [comment]
@Ctucker9233 no, it shouldn't, and it cannot be actually according to current rules as it is just some cleanup.

**Pull request merged**
