### PR TITLE
[MFTF] AdminAddBundleItemsTest refactoring

### LINKED ISSUE #34432: [Issue] [MFTF] AdminAddBundleItemsTest refactoring
This issue is automatically created based on existing pull request: magento/magento2#33526: [MFTF] AdminAddBundleItemsTest refactoring

---------
This PR is to refactor AdminAddBundleItemsTest according to the best practices

### PR DESCRIPTION
**Pull request by AnnaAPak**
This PR is to refactor AdminAddBundleItemsTest according to the best practices

### Resolved issues:
1. [x] resolves magento/magento2#34432: [MFTF] AdminAddBundleItemsTest refactoring

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run all tests

**Comment by AnnaAPak** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Review by sidolov — CHANGES_REQUESTED** [review]
@AnnaAPak please, resolve merge conflicts

**Comment by engcom-Charlie** [comment]
Hi @AnnaAPak,

Thanks for the contribution!

I am looking into resolving conflicts.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by engcom-Charlie** [comment]
Below failed test cases from the previous build are working fine on local environment.

vendor/bin/mftf run:test AdminAddBundleItemsTest --remove
vendor/bin/mftf run:test QuickSearchAndAddToCartVirtualTest --remove

image

For now I have merged 2.4-develop into this branch again and running the build now.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Database Compare, Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
I have merged 2.4-develop into this branch and fixed the failed test case.

Below tests which are failing now are not part of this PR or not failing because of this PR changes. Hence moving this PR to Merge in Progress now.

**Functional Tests EE:**
SlideItemCollageRightCanInlineEditContentWhenIn25PercentWidthColumnTest.xml

**Functional Tests CE:**
StorefrontSalableQuantityOnNonDefaultStockForConfigurableProductWithDropDownAttributeAfterPlacingOrderCountedCorrectlyTest.xml


Thank you!

**Pull request merged**
