### PR TITLE
[MFTF] Added assertion to AssertAdminSuccessLoginActionGroup

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR adds assertion to `AssertAdminSuccessLoginActionGroup`
### Scenario:
We run `AdminLoginSuccessfulTest` and we didn't see any assertions
Screenshot 2020-04-13 at 17 56 00
### Actual result 
Screenshot 2020-04-13 at 17 57 51

### CODE REVIEW

**Review by lbajsarowicz — APPROVED** [review]
It's OK :-) However funny, because this `waitForElementVisible` is also kind of assertion.
Thanks for making that explicit.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7404](https://jira.corp.magento.com/browse/ENGCOM-7404) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by slavvka** [comment]
@magento run Functional Tests CE

**Pull request merged**
