### PR TITLE
Updated Ga.php file

### PR DESCRIPTION
**Pull request by dchaykas**
Removed unused if/else statement containing $address variable which is not part of the returned result or any processing.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=6107) <br/>All committers have signed the CLA.

**Comment by okorshenko** [comment]
@dchaykas thank you for your contribution. This fix already delivered to develop branch https://github.com/magento/magento2/commit/3eee6ea71f1f1e024337fdacd4aeeddb6685ae99

**Comment by dchaykas** [comment]
Thank you @okorshenko for the follow up. Is there a reason why a 3 month old commit takes priority over an 8 month old pull request for the same issue?

**Comment by okorshenko** [comment]
@dchaykas there is no specific preferences. We are trying to process newer PRs as soon as possible because on newer PRs we have higher chances to get a response from the contributor faster.

**Pull request closed without merging**
