### PR TITLE
Magento#25894: fixed issue when "insert image window" didn't refresh after removing folder

### LINKED ISSUE #25894: The added image does not disappear from "Insert File" window if the image containing folder has been Deleted
### Preconditions (*)
1. Magento 2.3-develop 

### Steps to reproduce (*)
1. From Magento Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**, click **Show/Hide Editor**, click **Insert Image**
3. Click **Create Folder** type a folder name and click **OK**
4. Select the previously created folder, click **Choose Files**
5. Browse for any image file from your computer and **Open **
6. In _Insert File..._ window select the previously created folder and click **Delete Folder**, confirm deleting by clicking **OK**

### Expected result (*)
The image should be deleted together with the folder 
### Actual result (*)
The previously added image doesn't disappear from _Insert File..._ window 
image not deleted_folder removed

### PR DESCRIPTION
**Pull request by andrewbess**
### Description (*)

I am only fixed this issue.
I am continuing with tests

### Fixed Issues (if relevant)

1. Fixes magento/magento2#25894: The added image does not disappear from "Insert File" window if the image containing folder has been Deleted

### Manual testing scenarios (*)

1. Create CMS Page or Edit CMS Page
2. Click "Show / Hide Editor" to disable WYSIWYG
3. Click "Insert Image..." to open "Insert File Modal window"
4. Create new folder
5. Select created folder
6. Add file to created folder
7. Remove created folder

"Upload Images" should be refreshed, file(s) should be removed form server.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by krzksz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-6428](https://jira.corp.magento.com/browse/ENGCOM-6428) has been created to process this Pull Request
:eight_spoked_asterisk: @krzksz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by krzksz — CHANGES_REQUESTED** [review]
> I am continuing with tests

I'm sorry, I didn't notice you're still working on this. Please let me know when it's finished.

**Comment by lenaorobei** [comment]
Hey @andrewbess. Are you still working on this PR?

**Comment by andrewbess** [comment]
Hello @lenaorobei 
I cannot add the tests.
I cannot add a file to a created folder using tests.
Could you please help me with this.
Thank you in advance

**Comment by sidolov** [comment]
@engcom-Charlie could you please help @andrewbess with test?

**Review by sidolov — DISMISSED** [review]
Changes will be covered on `Changes Requested` state

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @andrewbess .

Could you resolve merge conflicts?
Thanks!

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
Hello @engcom-Alfa 
I have resolved the conflicts.
Please check.

Thank you in advance.

**Comment by andrewbess** [comment]
@magento run Functional Tests CE Functional Tests EE Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@andrewbess can you please cover your changes by some kind of autotests?
Thank you.

**Comment by engcom-Charlie** [comment]
@andrewbess  can you please look at https://github.com/magento/magento2/pull/25945#issuecomment-707064591? Otherwise, we can't proceed with your PR.
Thank you.

**Comment by andrewbess** [comment]
Hello @engcom-Charlie 
I will try to cover it by tests, but I still know how to do it. Please wait.

**Comment by engcom-Charlie** [comment]
@andrewbess do you have any updates about test coverage?
Thank you.

**Comment by andrewbess** [comment]
Hello @engcom-Charlie 
Not yet.
I will try to do it this week.

**Comment by sidolov** [comment]
@andrewbess  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
