### PR TITLE
[Theme] Replace deprecated class in mockobject unit test LoadDesignPluginTest

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Unit test previously used $actionMock = $this->createMock(Action::class); 
This class has deprecated. We should use `Magento\Framework\App\ActionInterface` instead

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run WebAPI Tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes from this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8975](https://jira.corp.magento.com/browse/ENGCOM-8975) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Comment by engcom-Bravo** [comment]
Hi @mrtuvn,

We are closing this PR.The PR is in Draft since longtime.

Once you are ready Please feel free to reopen it to process the PR further.

Thanks

**Pull request closed without merging**
