### PR TITLE
[Forwardport] Grid filtration doesn't work for mysql special characters

### PR DESCRIPTION
**Pull request by serhii-balko**
### Original Pull Request 
 https://github.com/magento/magento2/pull/12749

### Manual testing scenarios

1. Create several products
2. Open product grid
3. Open filters block
4. Enter % or _ to name field
5. Do filter

###Expected result

Grid shows only products with the symbol

###Actual result

Grid shows all products
 
### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
Hi @serhii-balko,
Thank you for your work. Unfortunately we have older PR https://github.com/magento/magento2/pull/13780 with the same changes, so we can't accept your one.

I'll mark your PR as duplicate

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[MAGETWO-88260](https://jira.corp.magento.com/browse/MAGETWO-88260) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@serhii-balko Looks like testing was started, so it's better to accept your PR. I'm re-opening it

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-591](https://jira.corp.magento.com/browse/ENGCOM-591) has been created to process this Pull Request

**Pull request merged**
