### PR TITLE
Catalog graphql aggregation

### LINKED ISSUE #27657: 2.3.4 GraphQl Aggregation Attribute labels and attribute option labels are not or incorrectly translated.
### Preconditions (*)

1. Magento 2.3.4
2. 2 Storeviews
3. Demo data

### Steps to reproduce (*)

1. Pick an attribute and configure it so its available as an aggregation in graphql (I chose "size")
2. Set the attribute label for both storeviews
Screenshot from 2020-04-08 17-01-43
3. Set the attribute option labels for both storeviews
Screenshot from 2020-04-08 17-01-49
4. Run the following GraphQl query for both storeviews:
```
query products {
    products (filter: {
      category_id: {eq: "2"}
    } 
    ) {
        aggregations {
          attribute_code
          label
          options{
            count
            label
            value
          }
        }
    }
}
```
### Expected result (*)

For default storeview
 ```
...
              {
                    "attribute_code": "size",
                    "label": "default",
                    "options": [
                        {
                            "count": 1,
                            "label": "55 cm default",
                            "value": "5518"
                        },
                        {
                            "count": 1,
                            "label": "65 cm default",
                            "value": "5519"
                        },
                        {
                            "count": 1,
                            "label": "default",
                            "value": "5520"
                        },
                        {
                            "count": 2,
                            "label": "default",
                            "value": "5521"
                        },
                        {
                            "count": 2,
                            "label": "default",
                            "value": "5522"
                        },
                        {
                            "count": 2,
                            "label": "default",
                            "value": "5523"
                        },
                        {
                            "count": 97,
                            "label": "XS default",
                            "value": "5594"
                        },
                        {
                            "count": 98,
                            "label": "default",
                            "value": "5595"
                        },
                        {
                            "count": 98,
                            "label": "default",
                            "value": "5596"
                        },
                        {
                            "count": 98,
                            "label": "default",
                            "value": "5597"
                        },
                       {...}
                    ]
                },
...
```

### Actual result (*)

For default storeview
```
...
               {
                    "attribute_code": "size",
                    "label": "Size",
                    "options": [
                        {
                            "count": 1,
                            "label": "55 cm notdefault",
                            "value": "5518"
                        },
                        {
                            "count": 1,
                            "label": "65 cm notdefault",
                            "value": "5519"
                        },
                        {
                            "count": 1,
                            "label": "notdefault",
                            "value": "5520"
                        },
                        {
                            "count": 2,
                            "label": "notdefault",
                            "value": "5521"
                        },
                        {
                            "count": 2,
                            "label": "notdefault",
                            "value": "5522"
                        },
                        {
                            "count": 2,
                            "label": "notdefault",
                            "value": "5523"
                        },
                        {
                            "count": 97,
                            "label": "XS notdefault",
                            "value": "5594"
                        },
                        {
                            "count": 98,
                            "label": "notdefault",
                            "value": "5595"
                        },
                        {
                            "count": 98,
                            "label": "notdefault",
                            "value": "5596"
                        },
                        {
                            "count": 98,
                            "label": "notdefault",
                            "value": "5597"
                        },
                       {...}
                    ]
                },
...
```
What is happening is that the attribute label is never translated. And the attribute option labels pick the last entry in the database for each label. In my case "notdefault" because I entered those last.
I checked the code and at no point is the $storeId checked in the queries that gather the results.

### PR DESCRIPTION
**Pull request by bharat1811**
### Description (*)
Fixed this issue for product graphql query result aggregation data for attribute labels and their option values which are not translated store view language-wise. 

### Fixed Issues (if relevant)
1. Fixes magento/magento2#27657

### Manual testing scenarios (*)

1. I created two stores English and the Arabic language on my website and have added some product attributes data in both language store view wise.

2. When I trigger a product query with passing store code (en) of the English store in the header it is perfect but when I trigger a product query with passing store code(ar) of Arabic store in the header, then also aggregation result attribute data not translated to expected language-wise.

**NOTE:-** I used the postman tool to test the issue.

Below is the product query of grpahql to test the result for aggregation data,
-----------------------------------------------------
query products {
    products (filter: {
      category_id: {eq: "9"}
    } 
    ) {
        aggregations {
          attribute_code
          label
          options{
            count
            label
            value
          }
        }
    }
}
-----------------------------------------------------

### Questions or comments

In my fixed PR request, I have managed that if it's not set store wised attribute and option label  then it will be fall back and returns default label.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by bharat1811** [comment]
**Reason of fix:** I have fixed this issue for product graphql query result aggregation data for attribute labels and their option values which are not translated store view language-wise. 

Means I have two stores English and the Arabic language in my website and have added some product attributes data in both language store wise and when I trigger a product query with passing store code (en) of English store in the header it is perfect but when I trigger product query with passing store code(ar) of Arabic store in the header, then also it is coming aggregation attribute data for the category in English only. 
**NOTE:-** I used the postman tool to test the issue.

Below is the product query of grpahql to test the result for aggregation data,
-----------------------------------------------------
query products {
    products (filter: {
      category_id: {eq: "2"}
    } 
    ) {
        aggregations {
          attribute_code
          label
          options{
            count
            label
            value
          }
        }
    }
}
-----------------------------------------------------
In my fixed committed solution, I have even managed that if it's not set attribute and option label store wised then it will be fall back and returns default label.

**Comment by danielrenaud** [comment]
Hi @bharat1811, thanks for the contribution. It looks like your branch has some conflicts. Could you update your PR to resolve conflicts?

**Comment by bharat1811** [comment]
Hi @danielrenaud, thanks for the update. I have resolved the conflicts please do the needful.

**Comment by nrkapoor** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
Hi @bharat1811 @Hexmage can you confirm if this issue still present on 2.4-develop? It seems this was fixed on issue #28568

Thanks

**Comment by cpartica** [comment]
> Hi @bharat1811 @Hexmage can you confirm if this issue still present on 2.4-develop? It seems this was fixed on issue #28568
> 
> Thanks

Confirmed, this has been fixed

**Pull request closed without merging**
