### PR TITLE
Order grid - Sort by Purchase Date Desc by default

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description
As a customer I expect to see new orders at the top of the grid, however during migration from M1 to M2 - order number length changed, as result new orders are NOT located at the top of grid.

In order to fix this issue for all cases - we're changing default sorting order to "Purchase Date" desc.

As we discussed with @okorshenko in https://github.com/magento/magento2/issues/10185#issuecomment-340531557 sorting order grid by Increment is not good idea. I'm proposing change default sorting from increment_id column to created_at.

Sorting issue happens only in following cases:
- Orders were migrated from Magento 1
- Used prefix/suffix for order number
- Customized order ID generation
- Etc.

NOTE: Order grid sorting saves in ui_bookmark table, so before testing need to execute following SQL:
```sql
TRUNCATE table ui_bookmark;
```

### Fixed Issues (if relevant)
1. 

### Manual testing scenarios
1. Create three orders as example 1000000001, 1000000002 and 1000000003
2. Go to order grid (sorting is correct)
capture 2017-10-02 at 17 58 47
3. Change 1000000001 order number to 100000001 (remove one 0 in the center) to emulate that order was migrated from M1 & Go to Order grid: (last created order became NOT first)
capture 2017-10-02 at 18 01 04
3. Create new Order & go to order grid (latest order is not at the top)
capture 2017-10-02 at 18 04 09

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by okorshenko** [comment]
Hi @tkacheva 
By this Pull Request, we will change default state of Orders Grid. In the current implementation, default sorting is by ID descending. But there is no guaranty that newest orders will be on top. ID may have alphanumeric symbols.

This Pull Request changes default sorting to by Purchase Date descending, so new orders will appear on the top.

Please, confirm such changes in default behavior.

**Comment by ihor-sviziev** [comment]
Please let me know if you will accept this PR. If yes - I will prepare backport PRs to other branches and looks like we have similar issues with another sales grids.

**Comment by tkacheva** [comment]
@ihor-sviziev  thank you for the contribution, one question related to that: The default sorting order will look like this? 
screen shot 2017-11-01 at 12 18 58 pm

If yes, the changes is approved.

**Comment by ihor-sviziev** [comment]
@tkacheva yes

**Pull request merged**
