### PR TITLE
MC-18543: Fix schedule currency_rates_update cron job

### PR DESCRIPTION
**Pull request by krzysztofkuzniar**
### Description (*)

Fix schedule currency_rates_update cron job
### Fixed Issues (if relevant)

1. magento/magento2#23846: Schedule currency_rates_update cron job not working

### Manual testing scenarios (*)

See "Steps to reproduce" section in issue 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23873) <br/>All committers have signed the CLA.

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-5515](https://jira.corp.magento.com/browse/ENGCOM-5515) has been created to process this Pull Request
:eight_spoked_asterisk: @swnsma, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@krzysztofkuzniar thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Delta** [comment]
Hi @krzysztofkuzniar I have tested PR changes and currency_rates_update cron job was not created with your fix in my case.
**Manual testing scenario:**

- Go to admin panel
- Stores > Configuration > General Tab > Currency Setup > Scheduled Import Setting section
- Set values:
-- Enable -> Set Yes
-- Service -> Fixer.io
-- Start Time -> Fill 00 : 00 : 00 (or {current time + 5 min} )
-- Frequency -> Choose Daily
- Run php bin/magento cron:run from command line 
- :x: currency_rates_update cron job not exist in cron_schedule table

Could you take a look?

**Comment by sidolov** [comment]
@krzysztofkuzniar , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
