### PR TITLE
Fix #10417

### LINKED ISSUE #10417: Wysywig editor shows broken image icons
### Preconditions

1. Magento 2.1.7
2. PHP 7.0

### Steps to reproduce

1. Add image in Wysywig editor

### Expected result

1. Image is shown in editor

### Actual result

1. Broken image icon
2. Url is ``

### PR DESCRIPTION
**Pull request by PieterCappelle**
When adding images in CMS Pages / Blocks or Catalog and Category the path to the image is incorrect. When you insert image in 2.1.8, we get ```<p></p>``` when we insert image in 2.1.9 ```<p></p>```

The issue is also a problem in 2.2-develop. This fix is for 2.2-develop. Will create backport voor 2.1-develop branch.

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/10417

### Manual testing scenarios
1. Go to CMS Pages.
2. Add image
3. Check the path (show/hide editor)

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=11048) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=11048) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: PieterCappelle<br/>:x: paliarush<br/>:x: viktym

**Comment by PieterCappelle** [comment]
Please merge this. I will create backport for 2.1.

**Comment by PieterCappelle** [comment]
Thanks. I'll create backport to 2.1 branch.

**Comment by Vishrootways** [comment]
How to solve this error in Magento 2.1.8 version? Please help us if anyone know.

**Comment by treii28** [comment]
I'm on v2.2.2 and still experiencing this issue? What is necessary to resolve it as from what I'm reading here, it's supposed to be fixed in my version.  Furthermore, if and when these links sneak into the database, they create hung apache threads whenever a page tries to access one and the things linger in a 'closing' status on the server and eat up 100% cpu until I kill -HUP them manually. I want it fixed!

**Pull request merged**
