### PR TITLE
[Forward Port 2.3] Increase flag_data size

### PR DESCRIPTION
**Pull request by aschrammel**
This PR is a forward port of PR #13579 

The flag_data field in the flag table is too small to reimport a config generated by bin/magento app:config:dump with more than 64KB size.
Increasing this field should be considered, as exporting the config and reimporting it is the suggested way for pipeline deployment.

### Description
If a bin/magento app:config:dump produces a config.php with more than 64KB of size, the bin/magento app:config:import or bin/magento setup:upgrade will fail because of the TEXT field limitation from flag_data in the flag table.

This PR increases the flag_data field to MEDIUMTEXT accepting 16MB.

### Fixed Issues (if relevant)
magento/magento2#11657: app:config:import fails - flag column 'flag_data' is too short ?
Manual testing scenarios
Run bin/magento setup:install
Before applying the PR, the flag_data field is a TEXT field accepting 64KB
After applying the PR, the flag_data field is a MEDIUMTEXT field accepting 16MB

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by sidolov** [comment]
@aschrammel , original pull request was closed due to inactivity, if you wish to continue, please, fix and reopen original pull request and apply fixes to port.  
Thank you for collaboration!

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-5524](https://jira.corp.magento.com/browse/ENGCOM-5524) has been created to process this Pull Request
:eight_spoked_asterisk: @orlangur, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:**

before

**After:**

after

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by jeff-jk** [comment]
Will this be backported to 2.2?

**Comment by orlangur** [comment]
@jeff-jk nothing will be backported to 2.2 afaik, it is closed for contribution.

**Comment by jeff-jk** [comment]
Thanks for clarifying @orlangur

**Pull request merged**
