### PR TITLE
Change header wording to apply to other payment providers, resolves #35622

### LINKED ISSUE #35622: Replace 'PayPal Account' translation in token_list.phtml
### Summary (*)
In the **Stored Payment Methods** page, there are 2 sections, one to render the card tokens and the other to render the account tokens. However, the table header for the accounts section is titled **PayPal Account**. This is fine if only paypal account tokens are to be created.

### Examples (*)
token_list.phtml:
```
<?php if (count($tokens) !== 0) : ?>
    <div class="table-wrapper my-credit-cards">
        <table class="data table table-credit-cards" id="token-list-table">
            <thead>
            <tr>
                <th scope="col" class="col"><?= $block->escapeHtml(__('PayPal Account')) ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($tokens as $token) : ?>
                <?= /* @noEscape */ $block->renderTokenHtml($token) ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif; ?>
```

### Proposed solution
However we are currently working on functionality to add other tokenizable account payment methods (such as GooglePay). Hence, since this section represents all tokens with `type=Account` we think it would be more representative if the section was titled **Account** instead of **PayPal Account**.

If we can get some confirmation for this, we can also submit a PR ourselves for it.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by cjnewbs**
### Description (*)
In issue #35622 it has been identified that that the core template only refers to PayPal, however this functionality is being utilised by other payment providers. This PR changes the text and translations for `PayPal Account` to `Account` so that other providers can use this functionality without having to override the core template.

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
1. [Fixes magento/magento2#35622](https://github.com/magento/magento2/issues/35622)

### Manual testing scenarios (*)
1. Log-in as a customer with payment accounts stored in the `Magento_Vault` module
2. The header that the token shows under should read `Account` instead of `PayPal Account`

### Questions or comments
N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by cjnewbs** [comment]
@magento run all tests

**Comment by cjnewbs** [comment]
@magento run all tests

**Comment by cjnewbs** [comment]
@magento run Functional Tests EE

**Comment by cjnewbs** [comment]
@magento run Functional Tests B2B,Unit Tests,WebAPI Tests

**Comment by cjnewbs** [comment]
@magento run all tests

**Comment by cjnewbs** [comment]
@magento run Functional Tests CE,WebAPI Tests,Sample Data Tests CE,Sample Data Tests EE,Sample Data Tests B2B

**Comment by cjnewbs** [comment]
@magento  run Functional Tests CE

Dear God these tests are flaky

**Comment by cjnewbs** [comment]
@magento run WebAPI Tests

**Comment by cjnewbs** [comment]
FFS.

@magento run all tests

**Comment by cjnewbs** [comment]
Is anyone from @magento/commerce-maintainers able to review as this is currently flagged as "pending review"? Although this is not a high-priority change more and more modules are coming out that use vaulting so is a fairly simple fix that is useful for others. Once thats done I can try update the branch and re-run the tests until they eventually decide to work.

**Comment by cjnewbs** [comment]
@magento run Functional Tests B2B, Integration Tests, WebAPI Tests, Sample Data Tests B2B, Sample Data Tests CE,Sample Data Tests EE

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @cjnewbs,

Thanks for the contribution!

Changes seem good to me, but please look into the failed tests.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B , Functional Tests CE, Integration Tests, WebAPI Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Failing Test are not related to PR changes.
Hence moving it to `Pending Review`

**Review by engcom-Hotel — APPROVED** [review]

**Comment by cjnewbs** [comment]
GitHub has not been notifying me of updates to this PR so missed the progress made. As noted by @engcom-Echo the failing tests are unrelated the the changes but if it would be useful I can update the PR to make use of the updated escaper `$escaper` instead of `$block`, or would it be better to leave as-is because the PR has been approved?

I took a look at the failing tests and see that a number of them are failing because a date with 11PM as the time does not match the expected value of the date the next day, is it possible this is due to a DST timezone issue or is that just a coincidence and the tests are just incredibly flaky?

**Comment by engcom-November** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
Hi @cjnewbs,

Thank you for the contribution!

It makes sense to change the sub heading of Stored Payment Methods from `PayPal Account` to `Account`, so that other providers can use this functionality without having to override the core template.
Steps followed to reproduce this:
1. Configure Braintree with Paypal or ACH, and turn on vault
2. Purchase a Product through braintree service
3. Go to MyAccount on frontend
4. Check stored Payment Methods Sections

### ✔️ QA Passed
**Before: ✖️**
* The sub heading was `PayPal Account`
image

**After: ✔️**
* Sub heading is `Account`
image

Since the builds are failing, moving it to Extended Testing.

Thank you.

**Comment by engcom-November** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by engcom-November** [comment]
Repeating Functional Tests are falky and are known issues, these are not related to PR changes.

**Functional Tests B2B**
**1st run:**
image

**2nd run:**
image

Known issues:
[ACQE-6438](https://jira.corp.adobe.com/browse/ACQE-6438)

**Functional Tests EE**
**1st run:**

**Comment by engcom-Charlie** [comment]
Hi @engcom-November, as per [this](https://github.com/magento/magento2/pull/37959#issuecomment-2074317673) comment, I can see that for B2B, B2b-2690 is repeatative failure and also CE, AC-6951 have failed in both successive builds so please check once again and provide more information on them. Till then moving it to Extended Testing.

**Comment by engcom-November** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
@engcom-Charlie, In the latest build for CE, AC-6951 has passed, and for B2B I have updated the open jira in comment. And also in the recent run web api test has failed but it was passed in last two runs, hence moving it back to Merge in Progress.

**Comment by engcom-November** [comment]
@magento run WebAPI Tests

**Comment by engcom-November** [comment]
@engcom-Charlie, for B2B-2690 I have updated the comment with open jira, and CE, AC-6951 has passed in the latest run.
Hence moving it back to Merge in Progress.

**Pull request merged**
