### PR TITLE
Changed name of dispatched object in delete event

### PR DESCRIPTION
**Pull request by clementbeudot**
in catalog_category_delete_after_done event dispatch in delete method (:1020)
changed dispatched object name from "product" to "category"

### CODE REVIEW

**Comment by ishakhsuvarov** [comment]
@clementbeudot Hi! Thank you for your contribution.
Unfortunately we can not accept this kind of change, since some extension or customization potentially may rely on that naming convention. In this case such rename may cause unexpected behavior or errors.

**Comment by clementbeudot** [comment]
Ok thank you. I know that it could potentially break something. But it is really strange to obtain a "product" when expecting a "category".

Maybe something to change later.

**Comment by ishakhsuvarov** [comment]
@clementbeudot 
Thats true, however too risky for now. Thanks for understanding.

**Comment by fooman** [comment]
Maybe it could add the product additionally as that would not break existing and add a deprecation notice on the category?

**Comment by clementbeudot** [comment]
hey @fooman, good idea as it would not break anything and people who are trying to use this event won't be stuck finding out why there is no "category" object passed in the event.

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by vrann** [comment]
@clementbeudot  Thank you for the contribution!

**Pull request merged**
