### PR TITLE
Fixed-20243: Backend: Widget option alignment issue.

### PR DESCRIPTION
**Pull request by suryakant-krish**
### Description (*)

Backend: Widget option alignment issue.

### Fixed Issues (if relevant)

1. magento/magento2 #20243: Backend: Widget option alignment issue.

### Manual testing scenarios (*)

1. Login into admin panel > Content > Widgets > Click on Widget Options. Look at alignment Block name.

2. Actual Result
actual

3. Expected Result
expected

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20424) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=20424) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-20424.instances.magento-community.engineering).
Admin access: [https://pr-20424.instances.magento-community.engineering/admin](https://pr-20424.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rogyar** [comment]
Hi @suryakant-krish. Thank you for your contribution. After the change, the element looks more aligned but it's still not aligned properly.

screenshot 2019-01-20 at 11 37 21

**Comment by sidolov** [comment]
Hi @suryakant-krish , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
