### PR TITLE
Fix elastic alias doubled index if exception was thrown

### PR DESCRIPTION
**Pull request by VaD1ke**
### Description 
Problem appears when Magento runs few cron-jobs in one process. When you have few actual "indexer_reindex_all_invalid" jobs with pending status in cron_schedule table.
And after failured cron-jobs you have few indices in ElasticSearch alias, magento get products from all of them that causes "Item ... with the same ID ... already exists." exception.

### Fixed Issues (if relevant)
1. magento/magento2#24550: ElasticSearch doubled indices in alias trouble if exception was thrown 

### Manual testing scenarios
Described in [issue](https://github.com/magento/magento2/issues/24550).
1. You need few pending cron-jobs for invalid reindex
2. You need invalid catalogsearch index
3. Start cron jobs. For debugging on local environment I used `bin/magento cron:run --group=index --bootstrap=standaloneProcessStarted=1`.
4. Magento [prepares](https://github.com/magento/magento2/blob/320aac0d8715d7de3201488afaf2cfcaa268e1a4/app/code/Magento/Elasticsearch/Model/Adapter/Elasticsearch.php#L207-L217) new incremented index
5. You need to get exception in [saveIndex](https://github.com/magento/magento2/blob/2e036c4097f8101320dabda56332e6f0fcdf21c1/app/code/Magento/CatalogSearch/Model/Indexer/Fulltext.php#L137). So first reindex job will be end up with failure. But it already has created new incremented index and send some docs to it.
6. Then \Magento\Cron\Observer\ProcessCronQueueObserver::processPendingJobs starts next reindex cron job in the same process. 
7. Then adapter [uses](https://github.com/magento/magento2/blob/320aac0d8715d7de3201488afaf2cfcaa268e1a4/app/code/Magento/Elasticsearch/Model/Adapter/Elasticsearch.php#L301) prepared index (with some docs), that was created in previous reindex and it [write](https://github.com/magento/magento2/blob/320aac0d8715d7de3201488afaf2cfcaa268e1a4/app/code/Magento/Elasticsearch/Model/Adapter/Elasticsearch.php#L310) it to alias without deleting old index. So now we have two indices in alias.
8. And then we got an error on category page

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — APPROVED** [review]

**Review by ihor-sviziev — APPROVED** [review]

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @VaD1ke,
Could you sign CLA? otherwise we can't accept your changes 😢 

As a check - at the end of page now you can see "pending" status near "CLA":
image

Also currently for file changed by you static tests are failing. Could you also fix them?

Thank you!

**Comment by VaD1ke** [comment]
> Hi @VaD1ke,
> Could you sign CLA? otherwise we can't accept your changes 😢
> 
> As a check - at the end of page now you can see "pending" status near "CLA":
> image
> 
> Also currently for file changed by you static tests are failing. Could you also fix them?
> 
> Thank you!

Hi, Ihor.

I have signed CLA.

Also I've checked static test error [report](https://testing-service.magento-community.engineering/reports/magento/magento2/pull/24552/45285dd1dede1f82203a10c1302ce8cd/Statics/allure-report-ce/index.html#categories/f4064cb0730f7318fd41ecf2630c4157/aab179e6c100e8b3/), and it's not due to my code :)
Whatever I've fixed this violations in [second commit](https://github.com/magento/magento2/pull/24552/commits/fcc38ef4d445d96cb108e62eb0f8d17cf421347d).

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5834](https://jira.corp.magento.com/browse/ENGCOM-5834) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@VaD1ke thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by kokoc — APPROVED** [review]

**Comment by engcom-Delta** [comment]
Hi @VaD1ke Unfortunately, I cannot reproduce issue on 2.3-develop.
**Manual testing scenario:**
- Elasticsearch is installed (version 6.5.4 in my case)
- Make  catalogsearch index invalid
#24552MainIndexer
- Add exception to `\Magento\Elasticsearch\Model\Indexer\IndexerHandler::saveIndex`
- Run `bin/magento cron:run --group=index --bootstrap=standaloneProcessStarted=1`
#24552MainFirstCron
- Delete exception from `\Magento\Elasticsearch\Model\Indexer\IndexerHandler::saveIndex`
- Run `bin/magento cron:run --group=index --bootstrap=standaloneProcessStarted=1`
#24552MainSecondRun
- Go to category page on frontend

**Result:**
:heavy_check_mark: Page is successfully loaded

Could you take a look if my steps are correct?

**Comment by VaD1ke** [comment]
Hi.

There are some misunderstandings in your scenario:
1. You need to run cron (`bin/magento cron:run --group=index --bootstrap=standaloneProcessStarted=1`) only one time, because error reproduces only after second iteration in same process.
You need few pending rows in cron_schedule to do this.
First exception is being catched here
image
And then new iteration (with second `invalid index` cron job) is started.
2. It's not neccessary to remove exception for second cron run.
3. Insert exception right after `$this->adapter->addDocs(...)` line in `saveIndex` method. You need some product docs in your second index to reproduce the bug with doubled ids
image

---

So final steps are:
1. First of all you need a correct index in your Elastic. For this you should run your full reindex of catalog search - 
`bin/magento indexer:reindex catalogsearch_fulltext`, or do it with invalid status and cron.
2. Than do all steps to reproduce this bug.  
3. After this look at your elastic's alias. You can do it via  
`curl '<host>:<port>/_alias/<prefix>_product_1'`  
where  
`<host>` - elastic host  
`<port>` - elastic port  
`<prefix>` - index prefix 
You can get this values from _Stores > Configuration > Catalog > Catalog search_ : _Elasticsearch Server Hostname_, _Elasticsearch Server Port_, _Elasticsearch Index Prefix_.
If you have two or more indices in alias, then bug was reproduced and situation is unstable :)
Because Magento loads products by alias (not directly from current index), it gets products from two or more indices, so doubled IDs appear.
Next go to category page. And you will see something like that (in developer mode):
image
or a report number in production mode.

---

As a result my fix forbids this second index (that end up with error) to be in alias. So we have only one index in alias and no ID doubles on category page.

**Comment by VaD1ke** [comment]
Hi everybody. What should I do now? :)
Should I wait for next tests or do something else?

**Comment by ihor-sviziev** [comment]
Hi @engcom-Delta,
Please review response

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
