### PR TITLE
Update column start for price column in PDF print

### PR DESCRIPTION
**Pull request by MoT3rror**
Make changes in https://github.com/magento/magento2/pull/8454/files to develop branch

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Hi @MoT3rror. The referenced PR is closed. Could you please elaborate the issue and add steps to reproduce it. Thanks.

**Comment by MoT3rror** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @MoT3rror. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @MoT3rror, here is your [Magento instance](https://i-27437-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27437-2-4-develop.instances.magento-community.engineering/admin_eb43](https://i-27437-2-4-develop.instances.magento-community.engineering/admin_eb43)
Login: `ccc03439` Password: `0812dda7be6e`
Instance will be terminated in up to 3 hours.

**Comment by MoT3rror** [comment]
1. Create a simple product.
2. Create a order and invoice the order.
3. Print the invoice PDF.
Annotation 2020-03-26 092251

Also, should fix this issue (https://github.com/magento/magento2/issues/12856).
Example of issue with bundle
Annotation 2020-03-26 092808

**Comment by MoT3rror** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @MoT3rror. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @MoT3rror, here is your [new Magento instance](https://pr-27437.instances.magento-community.engineering).
Admin access: [https://pr-27437.instances.magento-community.engineering/admin_54a0](https://pr-27437.instances.magento-community.engineering/admin_54a0)
Login: `1541c4e6` Password: `65153ad42840`
Instance will be terminated in up to 3 hours.

**Comment by MoT3rror** [comment]
This issue fixes the simple product. 
Annotation 2020-03-26 093806

Will have to look at bundle again.

**Comment by lenaorobei** [comment]
Thanks for the explanation. Could you please check failed static test?

**Comment by MoT3rror** [comment]
Looks like the static tests are complaining about nesting in the draw function. Those functions are quite large but probably be out of scope to refactor in this PR.

**Comment by lenaorobei** [comment]
Let's suppress it for now. Thanks.

**Comment by MoT3rror** [comment]
Not very familiar with the suppress options. Those functions already have PHPMD.CyclomaticComplexity, PHPMD.NPathComplexity and PHPMD.ExcessiveMethodLength suppressed. What one should I add to suppress nesting?

**Comment by lenaorobei** [comment]
Following annotation can be used `phpcs:disable Generic.Metrics.NestingLevel`. Please see example `\Magento\CatalogImportExport\Model\Import\Product\Option::_getNewOptionsWithTheSameTitlesErrorRows`.

**Comment by lenaorobei** [comment]
Closing this PR due to inactivity. Please feel free to reopen if you are going to continue working on it.
Thank you.

**Pull request closed without merging**
