### PR TITLE
Fix problem actions dropdown positioned incorrect

### LINKED ISSUE #31379: Actions dropdown positioned against the last column, not against "Actions" colum
### Preconditions (*)

1. Reproduced on Magento  2.4.1
2. Reproduced on  Magento 2.4.2 beta 1

### Steps to reproduce (*)
1. Change the columns order in Admin Grid
2. Click on any "Select" in "Actions" column

### Expected result (*)
image

### Actual result (*)
image

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by mrtuvn**
Issue seem related with styles code. Before this patch dropdown position always show in right of grid and not correct position anymore when we move action to left.
Annoying issue when owner store move action column to near center of grid and grid have lot of columns
Issue can reproduce at cms page listing page with draggable actions column with some extra additional column

Before the fix
Screen Shot 2020-12-23 at 14 06 22

After apply this fix
Screen Shot 2020-12-23 at 14 07 02

Only small problem but i think this can acceptable
at the last item row. When click on actions link, downdown show but come with scroll vertical overlap some parts of dropdown content. May require user have to scroll down a bit to view entire all actions. 

Here is example grid in product variants configurable product page in admin
action

Test case 1
Actions column drag to middle of grid have multiple columns
Previously: When user click active action, dropdown moved to far right side, unaccessable to click require scroll to last column to visible
Current: dropdown show in correct position right below action link

Test case 2
Re-test  in smaller screen (1200px)
Actions column at last position when active dropdown display correct without jump of of block

Test case 3 
No overflow with table have long width. Scrollbar horizontal will auto-show on demand at small screen resolution

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31379

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

As long as this action column at the last of table this issue will not able to happen. Dropdown will show correct as we expected
Should we allow admin can draggable this column ? In some case we will drag it to the end 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Static Tests

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by mrtuvn** [comment]
code rebased

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @mrtuvn,
It seems like this change caused a regression - some links became not clickable. Could you double-check and fix that?

**Comment by mrtuvn** [comment]
Can you share any screenshot ? 
From my setup actions link can clickable

**Comment by ihor-sviziev** [comment]
@mrtuvn as you can see in test results - the issue appears for the latest element:
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/31413/8ceded9f681dd8029b5056e3928fff89/Functional/allure-report-ce/index.html#categories/c6c6553a02a7680a5874353a75791825/ab4ba1e873f6ce24/
image

**Comment by mrtuvn** [comment]
i will check that again

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
i just wonder is there somewhere else have data-grid ? May in modal or popup ?

**Comment by ihor-sviziev** [comment]
TBH I don't think so, but let's wait for the test results

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8626](https://jira.corp.magento.com/browse/ENGCOM-8626) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@sivaschenko @gabrieldagama, can we increase priority for this PR? It significantly improves user experience, when you're working with long-width grids.

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Unit Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1.   Go to Admin >> CMS >> Pages section or any grid 
2.  Try to see the position of Action column's options when Action column is  dragged to almost center of grid or towards left side.
3.  Try to see the position of Action column's options when grid have lot of extra columns in it and Action column is  dragged to almost center of grid or towards left side.

**Actual Result:** :heavy_check_mark:
 
1.  Action Column moved to left side with original grid settings.

**After:** :heavy_check_mark:  

image
**Before:** :heavy_multiplication_x: 

image

2.  Action Column moved to left side with lots of extra columns added to grid.

**After:** :heavy_check_mark:  

image
**Before:** :heavy_multiplication_x: 

image

3.  See the Action drop down in smaller screens

**After:** :heavy_check_mark:  

image

image

4.  The Action Option's link are working fine. Ex. Click on Delete of Enable Cookies record.

**After:** :heavy_check_mark:  
image

**Tested all the manual scenarios, no impact on regression testing.**

**Pull request merged**
