### PR TITLE
#26847: Added 'enterKey' event handler to prompt widget

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Added event handler for enter key to the prompt widget in order to do 'confirm' action by hitting enter key.

### Fixed Issues
1. #26847

### Manual testing scenarios
See issue description from #26847.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6993](https://jira.corp.magento.com/browse/ENGCOM-6993) has been created to process this Pull Request

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @sergiy-v.

During testing, we faced the issue.

**_Problem:_** The folder is saved even when you press "Esc"

**Manual testing scenario:**

1. Log in to Admin;
2. Go to Catalog->Categories;
3. Go to **Content** tab and click on **Select from Gallery** button;
4. Click on **Create Folder** button;
5. Fill field and click the "**Enter**" button on the keyboard

**Actual Result:** :heavy_check_mark:  The folder has been saved

6. Click on **Create Folder** button again;
7. Fill field and click the "**Esc**" button on the keyboard;

**Actual Result:**

:heavy_multiplication_x: The folder was saved at the click of the "Esc" button
after

@sergiy-v Could you take a look?

Thanks!

**Comment by sergiy-v** [comment]
@engcom-Alfa thank you for details, I'll check it.

**Comment by sergiy-v** [comment]
@engcom-Alfa nice catch!)
@dmytro-ch please check the changes once you will have a chance.
Thanks.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6993](https://jira.corp.magento.com/browse/ENGCOM-6993) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by eduard13** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @eduard13, here is your [new Magento instance](https://pr-27029.instances.magento-community.engineering).
Admin access: [https://pr-27029.instances.magento-community.engineering/admin_cd7e](https://pr-27029.instances.magento-community.engineering/admin_cd7e)
Login: `78ebeb15` Password: `ef7a337748e5`
Instance will be terminated in up to 3 hours.

**Pull request merged**
