### PR TITLE
Emogrifier update to latest version

### LINKED ISSUE #6946: Outdated pelago/emogrifier package
I'm providing just one example of possible bugs here. The problem is that version of pelago/emogrifier package that Magento 2 uses was released almost 1,5 year ago.
### Preconditions
1. Magento 2.1.1
### Steps to reproduce
1. Custom email-inline styles, compressed (i.e. by sass compiler)
2. `parent > children` selector used in styles (in compressed file it looks `parent>children`)
### Expected result
1. Styles should be applied correctly (description in `_email-base.less` file says that descendant is supported.
### Actual result
1. Styles are not applied due to Emogrifier bug, that was already fixed and correct version is available.

When do you plan to update this package?

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
New version of #7110 made from develop branch.
Fixes #6946 and #4737

### CODE REVIEW

**Review by orlangur — APPROVED** [review]

**Comment by ishakhsuvarov** [comment]
Hi @Bartlomiejsz 
Please check the unit tests fail.

**Comment by Bartlomiejsz** [comment]
@ishakhsuvarov I'm not sure what is wrong here. Running `phpunit -c dev\tests\static .` locally ends without errors. Also I don't think my changes broke something here. Maybe you should try rerunning travis?

**Comment by ishakhsuvarov** [comment]
@Bartlomiejsz I've restarted the Travis job, however I am pretty sure issue is going to persist.
You referred to the `dev/tests/static` however the job for unit tests was failed, try running a whole scope of unit tests.
Sadly, due to error, currently Travis would not show exact tests which were failed, I am working on a fix for this issue.

**Comment by Bartlomiejsz** [comment]
@ishakhsuvarov I've tried to run a whole scope of tests, and it failed. But it returned me following error:
`Fatal error: Class 'Magento\TestFramework\TestCase\WebapiAbstract' not found in ...\dev\tests\api-functional\testsuite\Magento\Analytics\Api\LinkProviderTest.php on line 20`<br />
But when I tried to run tests on develop branch, it also failed, returning exactly same error.

**Comment by ishakhsuvarov** [comment]
@Bartlomiejsz Looks like the unit which fails is 
`Magento\Email\Test\Unit\Model\Template\FilterTest::testApplyInlineCss`
Please check

**Comment by okorshenko** [comment]
@Bartlomiejsz would you like to proceed with this PR or we can close it?

**Comment by Bartlomiejsz** [comment]
@okorshenko yes, I would, but unfortunately right now I have some problems with my computer. So any help here would be appreciated

**Comment by okorshenko** [comment]
@Bartlomiejsz thank you for your contribution. Please create new PR when ready. Closing this PR for now

**Pull request closed without merging**
