### PR TITLE
[Backport] Use route ID when creating secret keys in backend menus instead of route name #17650

### PR DESCRIPTION
**Pull request by lfolco**
Original PR https://github.com/magento/magento2/pull/17650

### Description

If you use a different route ID and front name in the _adminhtml/routes.xml_ file, you will get redirected to the dashboard when clicking on the menu link.

This is because the route front name is used to generate the secret key when creating the menu, and route ID is used to generate the secret key for key validation.

The method `\Magento\Backend\Model\Url::getSecretKey()` takes three parameters: route ID, action path, and action. When creating links for the menu, `Magento\Backend\Block\Menu::_callbackSecretKey($match)` is reading the URL paths from XML, which are using front names. I have injected `\Magento\Framework\App\Route\ConfigInterface` in order to use `getRouteByFrontName($routeName)` in order to get the proper route ID.

### Fixed Issues (if relevant)
1. magento/magento2#7557: Backend Security key broken for controllers with front name not equal to route ID

### Manual testing scenarios

1. Create a module with an _adminhtml/routes.xml_ file that has a different route ID and front name.
2. Add an _adminhtml/menu.xml_ file that uses the front name in the `action` attribute.
3. Click on the new menu link; you will be taken to the correct admin page.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @lfolco. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-2958](https://jira.corp.magento.com/browse/ENGCOM-2958) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @lfolco. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Comment by magento-engcom-team** [comment]
Hi @lfolco. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Comment by citrus3000psi** [comment]
I recently updated to 2.2.8 and this commit killed some of my items in my admin panel

Stores -> Configuration, 
Cache Mangentment, 
Users
etc

I was able to fix the links by reverting back to the previous Menu.php

**Comment by paalsoberg** [comment]
Likewise, killed a site I've been working on as well after upgrading to 2.2.8

**Comment by gwharton** [comment]
Here too. Had to turn off the url secret keys for whole site.

**Comment by alfonso-eusebio** [comment]
Same here. There are some sections that can't be accessed at all. However, in my case I've noticed that this only happens when admin users have custom ACLs. For users with full admin access this doesn't seem to be a problem (except being redirected to dashboard every now and then).

In my particular case, access to Currency Rates was being blocked due to wrong secret key. After some investigation I noticed that the secret key for the menu entry was being generated for **sales**/currency_rates, rather than **admin**/currency_rates. I noticed that I could fix the issue by changing the menu.xml configuration to `action="admin/system_currency"`, instead of `action="adminhtml/system_currency"`.

When the code looks for a route name for _adminhtml_ it doesn't find anything, which reverts to using the route name from the request referrer: _sales_. (?)

I hope this helps somewhat.

**Comment by santhoshnsscoe** [comment]
Upgraded to 2.2.8, and now most of my admin url are getting redirected to dashboard. Checked with changing the id and frontName to same and it works. If different, it is not working.

These modules are working fine in 2.2.7.

**Comment by djamps** [comment]
Ditto, in 2.2.8 we are randomly redirected to dashboard when going to Stores -> Configuration.

**Comment by olivertar** [comment]
elvinristi found where the problem is:
https://github.com/magento/magento2/issues/22366

**Pull request merged**
