### PR TITLE
Current password autocomplete for admin login

### PR DESCRIPTION
**Pull request by flancer64**
Browsers have an autocomplete functionality with permissions for every site separately. It is a user's decision - enable/disable autocomplete for the certain site, not developer's is.

image

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @flancer64. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by ihor-sviziev** [comment]
Autocomplete was disabled in following commit https://github.com/magento/magento2/commit/5748f3a90b88ce788796849e8fc67152f6b0a479.
I think it was done due to security issues.
@sidolov could you check it?

**Comment by osrecio** [comment]
As per your [Mozilla link](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion), browsers now ignore `autocomplete="off"`

> If a site sets autocomplete="off" for a \<form\>, and the form includes username and password input fields, then the browser will still offer to remember this login, and if the user agrees, the browser will autofill those fields the next time the user visits the page.

> If a site sets autocomplete="off" for username and password \<input\> fields, then the browser will still offer to remember this login, and if the user agrees, the browser will autofill those fields the next time the user visits the page.

**This is the behavior in Firefox (since version 38), Google Chrome (since 34), and Internet Explorer (since version 11).**

**Comment by sidolov** [comment]
Hi @flancer64 , unfortunately, we can't accept this pull request, as @ihor-sviziev said, autocomplete was disabled due to security issues,  because with autocompletion enabled, some browsers retain user input across sessions, which could allow someone using the computer after the initial user to see information previously submitted.
Thank you for the collaboration!

**Comment by flancer64** [comment]
Thanks, @sidolov .

I understand that security & convenience are on the different sides. `autocomplete="off"` - it is OK, but `autocomplete="new-password"` for regular password field is a dirty hack that confuses end users (me, for example).

image

**Comment by ihor-sviziev** [comment]
@flancer64 so maybe let's update PR to update in all places ```autocomplete="off"```?

**Comment by flancer64** [comment]
@ihor-sviziev , done.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-2977](https://jira.corp.magento.com/browse/ENGCOM-2977) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @flancer64. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
