### PR TITLE
TypeError: this.trigger is not a function

### PR DESCRIPTION
**Pull request by daim2k5**
code is taken from @dfediuk #2270

### CODE REVIEW

**Comment by daim2k5** [comment]
@vkublytskyi any update on this?

**Comment by vkublytskyi** [comment]
@daim2k5, Sorry that processing this PR takes so much time. GitHub issues and PRs are processed according to priority in same queue with internal tickets. But be sure that this PR will be merged

**Comment by valibus** [comment]
Still present in magento 2.0.7. Last comment 28 says ago ? any news on this PR ?

**Comment by MomotenkoNatalia** [comment]
Hi @daim2k5 !
Thanks for contributing! Our internal ticket - MAGETWO-55217

**Pull request merged**
