### PR TITLE
Resolve Duplicate Records when sorting column in Content->Themes Grid issue25925

### LINKED ISSUE #25925: Dupplicate Records when sorting column in Content->Themes Grid
### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Go to backend
2. Content->Themes
3. Click Theme Title to sort
4. Click Theme title to sort again
sort
=> Dupplicate Records

### Expected result (*)

image

### Actual result (*)

=> Dupplicate Records

image

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#25925: Duplicate Records when sorting column in Content->Themes Grid

### Fixed Issues (if relevant)

1. magento/magento2#25925: Duplicate Records when sorting column in Content->Themes Grid

### Manual testing scenarios (*)

1. Go to backend
2. Content->Themes
3. Click Theme Title to sort
4. Click Theme title to sort again
=> Doesn't duplicate records

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @edenduong
Unfortunately, we only accept Pull Requests to the following branches: 2.2-develop, 2.3-develop.
Please create a new Pull Request and use one of those as a target.

Thank you.

**Review by sudheers-kensium — APPROVED** [review]

**Comment by dmytro-ch** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request.
Unfortunately, I can only deploy instances for `2.2-develop` and `2.3-develop` base branches

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6425](https://jira.corp.magento.com/browse/ENGCOM-6425) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
