### PR TITLE
Feature/fix product alert non logged

### PR DESCRIPTION
**Pull request by igor-imaginemage**
Hi, this is an issue that I reproduced today in 2 of our customers that are running Magento 2.3.2 and also in a vanilla Magento installation.

Magento has a core module **Magento_ProductAlert** that allow us to enable links to customers subscribe when a product is back in stock and also when price goes down (https://docs.magento.com/m2/ce/user_guide/catalog/inventory-product-alerts.html).

This module stores the customer_id when a customer subscribes, so, they have to be logged to proceed with this action. If a customer isn't logged Magento will show the login page and after the customer is logged, he/she will be redirected to the product page, with a message saying he/she was subscribed to be notified when the product come back in stock or when the price goes down (Depending of which link he/she is using).

### Preconditions (*)
- Magento 2.3.2 (Open Source or Commerce)
- Out of stock products visible in the frontend (https://prnt.sc/p1vi3t)
- "Allow Alert When Product Comes Back in Stock" or "Allow Alert When Product Price Changes" enabled (https://prnt.sc/p1vhzq).
- An out of stock product.

### Steps to reproduce (*)
Test scenario 1:
- Access the out of stock product in the storefront as a guest customer (not logged).
- Click in the "Notify me when this product is in stock" link (https://prnt.sc/p1viun).
- Provide your correct customer credentials and submit the form.

Test scenario 2:
- Access the out of stock product in the storefront as a guest customer (not logged).
- Click in the "Notify me when this product is in stock" link (https://prnt.sc/p1viun).
- Provide incorrect customer credentials and submit the form.

### Expected result (*)
- Be redirected to the product page with the appropriate message, a message saying the customer was subscribed to be notified (scenario 1), a message saying the provided credentials are incorrect (scenario 2).

### Actual result (*)
- The customer is redirect to a 404 page (https://prnt.sc/p1vkvh).

This is happening on Magento 2.3.2, I tried on Magento 2.2 but I wasn't able to reproduce same issue.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24453) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=24453) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: igor-imaginemage<br/>:x: magento-team<br/>:x: pdohogne-magento

**Comment by igor-imaginemage** [comment]
I also created an issue about this problem -> https://github.com/magento/magento2/issues/24454

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Please look at your branch. Your branch contains 1474 changed files.

**Comment by igor-imaginemage** [comment]
Hi @VladimirZaets , I created my branch from 2.3 and not from 2.3-develop, is this the problem?

**Comment by igor-imaginemage** [comment]
@VladimirZaets I created a new branch from 2.3-develop, now I don't have all the other files that you mentioned. Do you want me to close this PR and create from this new branch?
The branch is https://github.com/igor-imaginemage/magento2/tree/feature/fix-product-alert-non-logged-23develop.

**Comment by igor-imaginemage** [comment]
Magento eng team confirmed this issue is fixed on 2.3-develop, so we don't need this PR.

**Pull request closed without merging**
