### PR TITLE
Fixes price index on partial update

### PR DESCRIPTION
**Pull request by alepane21**
Backport to 2.2 of #19878

When $entityIds is passed to the function, the where does a BETWEEN, but that's wrong because it will set to zero all the products between the min($entityIds) and max($entityIds).

### Description (*)

I have just replaced the "BETWEEN" SQL condition to "IN", like has been suggested by gavinlimely in https://github.com/magento/magento2/issues/7367#issuecomment-447921233 and tested and verified it.

### Fixed Issues (if relevant)

1. magento/magento2#19877: Wrong partial price reindex with two or more products 

### Manual testing scenarios (*)

1. put two or more products to be re-indexed in the catalog_product_price_cl, without contiguous ids;
2. launch indexer_update_all_views;
3. all the products between min($entityIds) and max($entityIds) will be set with price, min_price and max_price to zero.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @alepane21. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by alepane21** [comment]
Could you mark this pull request as made by Hevelop? Thanks!

**Comment by alepane21** [comment]
> Could you mark this pull request as made by Hevelop? Thanks!

I already did as specified in https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#partners

**Review by aleron75 — APPROVED** [review]
"Go" for me, provided #19878 is approved as well

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-3723](https://jira.corp.magento.com/browse/ENGCOM-3723) has been created to process this Pull Request

**Comment by okorshenko** [comment]
Hi @alepane21 
We don't see Hevelop in the partners directory. 
https://partners.magento.com/portal/directory/?_token=g8HHIoHZru9BS_zVZJ5TzTs2LcBRlRPn&query=Hevelop

Please contact us at engcom@adobe.com if you would like to enroll Hevelop team in the contribution program.

**Comment by alepane21** [comment]
> Hi @alepane21
> We don't see Hevelop in the partners directory.
> https://partners.magento.com/portal/directory/?_token=g8HHIoHZru9BS_zVZJ5TzTs2LcBRlRPn&query=Hevelop
> 
> Please contact us at [engcom@adobe.com](mailto:engcom@adobe.com) if you would like to enroll Hevelop team in the contribution program.

:'(
ok thanks!

**Comment by okorshenko** [comment]
Hi @alepane21 you may consider Magento Community Insider Program https://info2.magento.com/CommunityInsiderProgram.html

**Comment by alepane21** [comment]
> Hi @alepane21 you may consider Magento Community Insider Program https://info2.magento.com/CommunityInsiderProgram.html

Thanks, but Hevelop (my employer) is a Partner. We already wrote to them, but they are really really slow to answer...

**Comment by okorshenko** [comment]
Hi @alepane21 thank you for update. Please send us an email engcom@adobe.com and will follow up on this

**Comment by sidolov** [comment]
Hi @alepane21  I'm closing this PR because original was closed due to inactivity. Please, reopen original PR if you wish to continue.
Thank you!

**Pull request closed without merging**
