### PR TITLE
[Backport] bundle-product-table-data-grouped-alignment :: Bundle product table d…

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Original Pull Request 
 https://github.com/magento/magento2/pull/20963
…ata grouped alignment in mobile view

### Description (*)

1. Go to bundle product then alignment is not proper on product page in mobile view

### Manual testing scenarios (*)

1. Go to bundle product
2. See on product page

Actual result (*)
bundle-product

Expected result (*)
bundle-2

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4282](https://jira.corp.magento.com/browse/ENGCOM-4282) has been created to process this Pull Request

**Comment by sdzhepa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [new Magento instance](https://pr-21242.instances.magento-community.engineering).
Admin access: [https://pr-21242.instances.magento-community.engineering/admin](https://pr-21242.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Pull request merged**
