### PR TITLE
#10207 Fix Validator Exception creation in AbstractModel and remove duplicated error messages in AbstractValidator.

### PR DESCRIPTION
**Pull request by valentinboyanov**
### Description
Fix creation of Magento\Framework\Validator\Exception in function validateBeforeSave() on the Magento\Framework\Model\AbstractModel and remove duplicated error messages in multi-dimensional array of error messages in Magento\Framework\Validator\AbstractValidator

### Fixed Issues (if relevant)

1. magento/magento2#10207: Magento\Framework\Model\AbstractModel::validateBeforeSave error notice (Array to string conversion)

### Manual testing scenarios
1. Programmatically save a quote with an invalid email address.
2. Catch the error, try another save of the quote with an still invalid email address.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=12181) <br/>All committers have signed the CLA.

**Comment by fooman** [comment]
hey @valentinboyanov Thanks for working on this pull request. Would you mind taking a look at the tests that are still highlighted as failing after your changes are applied.

**Comment by valentinboyanov** [comment]
Hi @fooman, I'm working on it!

**Comment by fooman** [comment]
@valentinboyanov thanks for continuing to work on this. I will close this Pull Request for now. Feel free to re-open it once you have added the changes to the tests.

Please ping myself or anyone on the the community engineering team if you have any questions we can help with.

**Pull request closed without merging**
