### PR TITLE
[MFTF] Use actionGroup go to CatalogRulePage

### PR DESCRIPTION
**Pull request by Usik2203**
This PR use `AdminOpenCatalogPriceRulePageActionGroup` to go to `CatalogRulePage` instead 
 `<amOnPage stepKey="goToPriceRulePage" url="{{CatalogRulePage.url}}"/>`

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests EE

**Comment by Usik2203** [comment]
Seems failed Functional EE test is not related with my changes.

**Comment by rogyar** [comment]
Hi @Usik2203. You haven't touched this test. So most likely it's a temporary issue. Thank you

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7784](https://jira.corp.magento.com/browse/ENGCOM-7784) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Pull request merged**
