### PR TITLE
Mark Cron, Csp, Customer and Deploy interfaces as API

### PR DESCRIPTION
**Pull request by vlmed**
### Description (*)
The following interfaces marked as API:

1. app/code/Magento/Cron/Model/DeadlockRetrierInterface.php
2. app/code/Magento/Csp/Api/CspAwareActionInterface.php
3. app/code/Magento/Csp/Api/CspRendererInterface.php
4. app/code/Magento/Csp/Api/Data/ModeConfiguredInterface.php
5. app/code/Magento/Csp/Api/Data/PolicyInterface.php
6. app/code/Magento/Csp/Api/InlineUtilInterface.php
7. app/code/Magento/Csp/Api/ModeConfigManagerInterface.php
8. app/code/Magento/Csp/Api/PolicyCollectorInterface.php
9. app/code/Magento/Csp/Api/PolicyRendererInterface.php
10. app/code/Magento/Csp/Model/Collector/Config/PolicyReaderInterface.php
11. app/code/Magento/Csp/Model/Collector/MergerInterface.php
12. app/code/Magento/Csp/Model/Policy/SimplePolicyInterface.php
13. app/code/Magento/Customer/Api/AccountDelegationInterface.php
14. app/code/Magento/Customer/Api/SessionCleanerInterface.php
15. app/code/Magento/Customer/Block/Address/Renderer/RendererInterface.php
16. app/code/Magento/Customer/Controller/AccountInterface.php
17. app/code/Magento/Customer/CustomerData/JsLayoutDataProviderPoolInterface.php
18. app/code/Magento/Customer/CustomerData/SectionPoolInterface.php
19. app/code/Magento/Customer/Model/Customer/Attribute/Source/GroupSourceLoggedInOnlyInterface.php
20. app/code/Magento/Deploy/Collector/CollectorInterface.php
21. app/code/Magento/Deploy/Console/Command/App/SensitiveConfigSet/CollectorInterface.php
22. app/code/Magento/Deploy/Package/BundleInterface.php
23. app/code/Magento/Deploy/Package/Processor/ProcessorInterface.php
24. app/code/Magento/Deploy/Source/SourceInterface.php
25. app/code/Magento/Deploy/Strategy/StrategyInterface.php

**Marked as API to fix static test**
26.  app/code/Magento/Deploy/Package/Package.php
### Fixed Issues (if relevant)

1. Fixes magento/magento2#32016

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by coderimus — CHANGES_REQUESTED** [review]
@vlmed thank you for the adjustments. There is one point explained to me: the @since will be set automatically during the merge. So, please, remove it :)

**Comment by vlmed** [comment]
@coderimus  Thanks for the explanation. `@since` sections removed

**Comment by coderimus** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by vlmed** [comment]
@magento run all tests

**Comment by vlmed** [comment]
@magento run Static Tests

**Comment by coderimus** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
Hi @vlmed, can you recreate this PR to the `api-changes-develop` branch instead? Just make sure to create a new branch from this one and cherry-pick your commit.

Thanks!

**Comment by vlmed** [comment]
Hi, @gabrieldagama. Done https://github.com/magento/magento2/pull/33104

**Pull request closed without merging**
