### PR TITLE
Bugfix - Customer emails are not being sent from admin if customer is from store "0"

### PR DESCRIPTION
**Pull request by matheusgontijo**
### Description (*)
Emails are not being sent to customers assigned to store id "0". Actually, store id "0", in the following context should be considered as a valid store id, since it's "admin". The `if` conditions should be actually checking if the store id is `null`: `if ($storeId === null) {` instead of `if (!$storeId) {`.

### Manual testing scenarios (*)
In order to reproduce the issue:
- Create a customer from admin (then customer will have `store_id = 0`)
- Go to customer edit page on admin and try to click `Reset Password`
- The email will not get and will throw an error.

### CODE REVIEW

**Comment by nuzil** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @nuzil. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @nuzil, here is your [Magento instance](https://i-26293-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26293-2-4-develop.instances.magento-community.engineering/admin](https://i-26293-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by nuzil** [comment]
On Vanilla 2.4 Magento I cannot create customer with Admin scope

Screen Shot 2020-01-07 at 17 09 27

**Comment by matheusgontijo** [comment]
Anyways, let consider we created a customer programmatically through an integration, and the customer was assigned to store id `0` to be globally used among several stores. This customer will not receive any email notifications.

**Review by nuzil — CHANGES_REQUESTED** [review]
Ok, by the core logic it's possible to have such behaviour.
But I will ask you to change this types:
https://github.com/magento/magento2/pull/26293/files#diff-216320d539f904af6160bad485978341L365

Cause your implementation is assume that storeId can be also null.

**Comment by matheusgontijo** [comment]
there we go @nuzil — modification done!

Could we merge now? Thank you!

**Comment by nuzil** [comment]
Hi @matheusgontijo can you please cover with tests your changes?

**Comment by engcom-Echo** [comment]
I will take care of test coverage.

**Comment by nuzil** [comment]
@magento run all tests

**Comment by nuzil** [comment]
@engcom-Echo can you please merge 2.4 one more time?

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by nuzil — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-7445](https://jira.corp.magento.com/browse/ENGCOM-7445) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**
1. Programmatically create a new customer (`test user` for ex.) (will have `store_id = 0`)
screenshot23;

2. Go to Admin -> Customers -> All Customers;
3. Click on **edit** link for created before customer;
4. Click on **`Reset Password`** button;

**Before:** 
:heavy_multiplication_x: an error has been occured
Screenshot from 2020-04-17 12-42-19

**After:**
:heavy_check_mark: The password reset email was sent
Screenshot from 2020-04-17 13-23-30
Screenshot from 2020-04-17 13-36-23

**Pull request merged**
