### PR TITLE
[Backport] Using interface instead of model directly

### PR DESCRIPTION
**Pull request by mage2pratik**
### Original Pull Request 
 https://github.com/magento/magento2/pull/17124
https://github.com/magento/magento2/pull/17263
### Description
Using interface instead of model directly

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by sidolov** [comment]
@magento-engcom-team combine 17263

**Comment by magento-engcom-team** [comment]
Hi @sidolov. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
@mage2pratik all pull requests have been successfully combined together: 
 - merged https://github.com/magento/magento2/pull/17263: [Backport] #17163: Add meta NOINDEX,NOFOLLOW to admin scope to avoid accidental crawling

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your contribution. 
We will aim to release these changes as part of 2.1.15. 
Please check the release notes for final confirmation.

**Pull request merged**
