### PR TITLE
[Forwardport] Fixed tierprice discount not calculated correctly if has specialprice

### PR DESCRIPTION
**Pull request by torhoehn**
### Original Pull Request 
 https://github.com/magento/magento2/pull/18743

### Description (*)
Added tierprice discount on speacial price, Check below link
**Before:** https://www.screencast.com/t/NyBdfLCb
**After:** https://www.screencast.com/t/na7rpDoKPvN

### Fixed Issues (if relevant)

1. magento/magento2#18652: Tierprice discount not calculated correctly if has specialprice

### Manual testing scenarios (*)

1. Add new product with price $100
2. Add special price $80
3. Add tier price with qty=2, type = "Discount" and value = "%12"
4. Add tier price with qty=300, type = "Discount" and value = "%25"
4. Add tier price with qty=1000, type = "Discount" and value = "%50"
6. Save the product

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3450](https://jira.corp.magento.com/browse/ENGCOM-3450) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Comment by nathanjosiah** [comment]
@torhoehn Thank you for your contribution! Unfortunately this PR had to be reverted for 2.3.1 as it created a new bug where a bundled product cannot be added to the cart on storefront with a special price applied.

**Pull request merged**
