### PR TITLE
[forwardport] Admin user auth controller refactor

### PR DESCRIPTION
**Pull request by AnshuMishra17**
### Original Pull Request 
https://github.com/magento/magento2/pull/16560

**Description**
Refactor the code by removing the direct use of ObjectManager and includes the dependencies using Constructor Dependency Injection

**Manual testing scenarios**
1. Created a new admin user
2. Login and logout using new admin user
3. Clicked on forgot password and provided new admin user email id.
4. Clicked on reset password link in email.
5. Created new password from reset password page.
6. Login using new password.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @AnshuMishra17. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by AnshuMishra17** [comment]
@arnoudhgz I have created new PR for changes done under https://github.com/magento/magento2/pull/16560

**Comment by arnoudhgz** [comment]
@AnshuMishra17 I think you are almost there, please solve the issues found with the Codacy and TravisCI automated checks.

At the moment the TravisCI check `TEST_SUITE=integration INTEGRATION_INDEX=2` will fail because  of a timeout. This is not resolvable at the moment I think.

The other checks you can probably resolve.

**Comment by AnshuMishra17** [comment]
@arnoudhgz I can see following issues that I am not sure how to rectify.
It would be nice if you can take a look and guide me with correct steps to fix the issues.

1. The property $_userFactory is not named in camelCase.
How to change this?
2. Avoid using static access to class '\Zend_Validate' in method 'execute'.
What is the recommended way to fix this?
3. Avoid excessively long variable names like $userCollectionFactory. Keep variable name length under 20.
What should be the variable name here, according to Magento coding standards?

**Comment by ihor-sviziev** [comment]
@AnshuMishra17 ping me in Slack, I'll help you to finalize both PRs.

**Comment by ihor-sviziev** [comment]
Hi @AnshuMishra17,
Unfortunately due to mistake and not full list of changes from original PR @sidolov merged forwardport PR from another author https://github.com/magento/magento2/pull/17140. Sorry for that.
I'm closing this PR as not relevant anymore

**Pull request closed without merging**
