### PR TITLE
Backend: Widget option alignment issue.

### PR DESCRIPTION
**Pull request by suryakant-krish**
### Description (*)

Backend: Widget option alignment issue.
This is direct pr as per suggest magento reviewer.

### Fixed Issues (if relevant)

1. Actual result.
actual-result
2. Expected Result
expected-result

### Manual testing scenarios (*)

1. Login into admin panel > Content > Widgets > Click on Widget Options. Look at alignment Block name.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by suryakant-krish** [comment]
Please consider only this commit 743ebfd

**Comment by sidolov** [comment]
Hi @suryakant-krish , unfortunately, we can't process only a few commits from the pull request. Please, put only mentioned commit to the branch and force push the current branch.
Thank you!

**Comment by suryakant-krish** [comment]
Hello  sidolov,

I have forcefully pushed branch please review it.

**Comment by suryakant-krish** [comment]
@sidolov,

Hello sivaschenko,
Created new pull request due to other commits.
here is the reference for the new pull request.
https://github.com/magento/magento2/pull/20424

**Pull request closed without merging**
