### PR TITLE
Removed duplicate line and added comment on variable

### PR DESCRIPTION
**Pull request by gelanivishal**
### Description

Removed duplicate code and added comment on variable.

### Fixed Issues (if relevant)

1. N/A

### Manual testing scenarios

1. N/A

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by mzeis** [comment]
Hi @vgelani, thank you for your PR!

I would say we can also remove the second comment `$_template` line. What do you think?

**Comment by gelanivishal** [comment]
@mzeis Yes. I also think about it. Let me remove it.

**Review by mzeis — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @mzeis, thank you for the review.
[ENGCOM-1592](https://jira.corp.magento.com/browse/ENGCOM-1592) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @vgelani. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

Please, consider porting this solution across release lines.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
