### PR TITLE
Add required fields to templates

### PR DESCRIPTION
**Pull request by miguelbalparda**
### Description
Developers submit PRs and issues without the template. This PR adds required fields.

### Fixed Issues (if relevant)

1. Not relevant

### Manual testing scenarios

1. Create a PR or issue
2. New text reads "Fields marked with (*) are required. Please don't remove the template."

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x]  All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@sidolov will it be correctly validated by engcom bot?

**Comment by magento-engcom-team** [comment]
@miguelbalparda thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by sidolov** [comment]
@ihor-sviziev it should work correctly with such changes, but we need to verify after the PR will be merged.

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
