### PR TITLE
Fix .lib-font-face mixin src format string

### LINKED ISSUE #26888: font filetype src format in .lib-font-face mixin is not wrapped with quotation marks
When using the `.lib-font-face()` mixin with an explicit `@font-format` like "woff" set, will not work. The font won't render (at least in chrome) because the filetype in the css src format is not wrapped in single quotation marks.

compiled CSS SHOULD look like this
```css
 @font-face {
        ...
        src: url('FONTPATH/FONTFILE.woff') format('woff');
        ....
    }
```

compile css how the mixin will generate it (look at format quotation marks):
```css
 @font-face {
        ...
        src: url('FONTPATH/FONTFILE.woff') format(woff);
        ....
    }
```

This could easily be fixed, by using less variable interpolation.

### Preconditions (*)
1. Magento 2.3.4 Community
2. Google Chrome  79.0.3945.130

### Steps to reproduce (*)
1. Setup a custom theme that has blank/luma as parent
2. Extend or override `/app/design/frontend/NAMESPACE/THEMENAME/web/css/source/_typography.less`
3. Add a local woff font i.e. like this:
3.a create the files in`app/design/frontend/NAMESPACE/THEMENAME/web/fonts/myfont/myfont.woff`
3.b link the static font file by adding `app/design/frontend/NAMESPACE/THEMENAME/Magento_Theme/layout/default_head_blocks.xml with the following content
```xml
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <head>
        <!-- Add custom font -->
        <font src="fonts/myfont/myfont.woff"/>
    </head>
</page>
```
4. use the `.lib-font-face()` mixin with explicit *woff* filetype set by  *using the variable* `@font-format: woff`. ie. in `_typography.less` file and 
```less
& when (@media-common = true) {
    .lib-font-face(
        @family-name:'OfficinaSerifBook',
        @font-path: '@{baseDir}fonts/myfont/myfont',
        @font-format: woff
    );
}
5. compile less files (i.e. using grunt/gulp)
```
### Expected result (*)
Because you want to use an explicit filetype (in the example "woff") the mixin from issue #4628 will be used. 

1. in the src format ([line 38](https://github.com/okorshenko/magento2/blob/05ea82c772fb6e3b2ebc4d33b43f2da387f382a4/lib/web/css/source/lib/_typography.less#L38)) the "woff" extension should be inserted *within a single quotation marks string* using variable interpolation
2. after compiling the font should be available when referenced by name in the css 

### Actual result (*)
1. in the src format ([line 38](https://github.com/okorshenko/magento2/blob/05ea82c772fb6e3b2ebc4d33b43f2da387f382a4/lib/web/css/source/lib/_typography.less#L38)) the "woff" extension will be inserted directly (not within a single quotation marks string)
2. the font is not available when referenced - or to be more concrete, it will not be rendered (instead the fallback will be used)

please see my pull request here:
https://github.com/magento/magento2/pull/26890

### PR DESCRIPTION
**Pull request by emanueljacob**
because the string in the font src format is not
wrapped in quotation marks, the font file will not be
rendered, when using the font-format parameter in the
less mixin. of course you could pass a string
wrapped with single quotation marks as parameter,
but in this case the url file extension wouldnt be
correct any longer...

see issue #26888
https://github.com/magento/magento2/issues/26888

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/26888 : font filetype src format in .lib-font-face mixin is not wrapped with quotation marks
### Manual testing scenarios (*)
see description in #26888 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by slashplusweb** [comment]
@magento give me test instance
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @slashplusweb. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @slashplusweb, here is your [new Magento instance](https://pr-26890.instances.magento-community.engineering).
Admin access: [https://pr-26890.instances.magento-community.engineering/admin_be0b](https://pr-26890.instances.magento-community.engineering/admin_be0b)
Login: `cf2708bc` Password: `58971d75e519`
Instance will be terminated in up to 3 hours.

**Comment by mrtuvn** [comment]
Failing tests are not related to changes from this PR
@Karlasa can you review this

**Comment by slashplusweb** [comment]
@magento-engcom-team 

can you please review my changes? probably enough to just assign another reviewer, because @Karlasa  seems not really contributing to the project according to his stats on github.

The diff is just ONE line of code. should be easily reviewed :(

**Comment by mrtuvn** [comment]
Hi Can we have any update on this ?
Quite important for deploy theme used font custom

**Comment by mrtuvn** [comment]
@ptylek @krzksz Hi can you guys review this ?

**Review by krzksz — APPROVED** [review]
Looks good to me, thanks for your first time contribution @slashplusweb!

**Comment by krzksz** [comment]
@magento run all tests

**Comment by krzksz** [comment]
There is no way to write an automatic test for this with our current stack I think, so I'm giving it an appropriate label.

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-7684](https://jira.corp.magento.com/browse/ENGCOM-7684) has been created to process this Pull Request
:eight_spoked_asterisk: @krzksz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@slashplusweb thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request closed without merging**
