### PR TITLE
Solution for User role issue with customer group #16499

### PR DESCRIPTION
**Pull request by ghost**
Solution for User role issue with customer group #16499

### Description

Now the “customer group” menu is displayed under "customers" menu on the admin side and store menu is invisible for new user. issue was is ACL file.
In ACL file 'Customer group should be in 'Magento_Customer::customer' instead of 'Magento_Backend::stores_other_settings'.
### Fixed Issues (if relevant)

1. magento/magento2#16499: User role issue with customer group #16499

### Manual testing scenarios

1 .System > Permission > User Roles.
2. Create a user role with 'customer group' permission which is specified in issue steps.
3. Login with new user credential. now only customer menu is enabled and store menu is not visible for new user.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @emiprotech. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by sidolov** [comment]
Hi @emiprotech , please, resolve merge conflict

**Comment by ghost** [comment]
Hi sidolov, 
**app/code/Magento/Catalog/Block/Product/ImageBuilder.php**
        This is unnecessary file for this pull request so please ignore this file from this pull request.

 **app/code/Magento/Customer/etc/acl.xml**
In above file there is a solution for User role issue with customer group #16499

**Comment by ihor-sviziev** [comment]
Hi @emiprotech,
Unfortunately we can't accept PR with conflict, also it's really hard to guess what changes you wanted propose.
Please fix conflict with 2.2-develop branch and we'll try to process your PR

**Comment by ghost** [comment]
I have created new pull request and I am closing this PR.
New PR is https://github.com/magento/magento2/pull/17515.

**Pull request closed without merging**
