### PR TITLE
[Backport] #16079 translation possibility for moreButtonText

### PR DESCRIPTION
**Pull request by Karlasa**
### Description

Added translation possibility for moreButtonText

### Fixed Issues (if relevant)

1. magento/magento2#16079: Need information about translating issue (Magento Swatches Js)

### Manual testing scenarios
You need a Configurable Product with a Swatch Product Attribute in Attribute Set
Swatch attribute have color or image attached to each swatch attribute value
This Parent Product have more than three children configured with the Swatch Attribute
In configuration, you need to have in Catalog > Storefront > Swatches per Product defined to 2
In configuration, you need to have in Catalog > Storefront > Show Swatches in Product List defined to Yes
Swatches have "more" text that can be translated

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### Original PR:
https://github.com/magento/magento2/pull/16190

### CODE REVIEW

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-2036](https://jira.corp.magento.com/browse/ENGCOM-2036) has been created to process this Pull Request

**Comment by orlangur** [comment]
@Karlasa could you please check that fix actually works for `2.1-develop`? According to report from QA engineers it is not working.

**Comment by Karlasa** [comment]
@orlangur thanks for the info, will check it in beginning of july.

**Comment by Karlasa** [comment]
@orlangur  i double checked and only mistake i did was i did not add new phrase into i18n folder, but otherwise it works for me. Could you specify if that was it?

**Comment by orlangur** [comment]
@Karlasa not sure if it was it as it worked on other Magento versions, let's trigger recheck with your new change.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-2036](https://jira.corp.magento.com/browse/ENGCOM-2036) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @Karlasa. Thank you for your contribution. 
We will aim to release these changes as part of 2.1.15. 
Please check the release notes for final confirmation.

**Pull request merged**
