### PR TITLE
[MFTF] Use action group for QuickSearch

### PR DESCRIPTION
**Pull request by Usik2203**
This PR use `StoreFrontQuickSearchActionGroup` for Quick Search on StoreFront

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests B2B

**Comment by rogyar** [comment]
The failing test is not related to the current change somehow since the failing test has not been changed within the scope of current PR.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7789](https://jira.corp.magento.com/browse/ENGCOM-7789) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
**Notice:** QA not applicable

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Pull request merged**
