### PR TITLE
magento/magento2#18256: Reset password throws error since 2.2.6.

### PR DESCRIPTION
**Pull request by p-bystritsky**
### Fixed Issues (if relevant)

1. magento/magento2#18256: Reset password throws error since 2.2.6.

### Manual testing scenarios (*)

1. Setup clean Magento 2 installation
2. Create a new account in the frontend
3. Logout
4. Go to the password reset page
5. Enter your email address and the captcha
6. Click on the link you've received
7. Enter a new password in the two fields
8. Password is successfully changed and the user can login with the new password

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @p-bystritsky. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3387](https://jira.corp.magento.com/browse/ENGCOM-3387) has been created to process this Pull Request

**Comment by TomashKhamlai** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai, here is your [Magento instance](http://34.228.235.121/i-19026-2-3-develop/).
Admin access: [http://34.228.235.121/i-19026-2-3-develop//admin](http://34.228.235.121/i-19026-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by TomashKhamlai** [comment]
@magento-engcom-team, @ishakhsuvarov I haven't got any email in inbox and spam folders after registering customer, order completion and resetting password.

Sometimes, the main cause of it is the offset between timezone in PHP ini configuration and timezone in Magento locale settings. But order completion notification works immediately and doesn't depends on timezone.

**Comment by magento-engcom-team** [comment]
Hi @p-bystritsky. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
