### PR TITLE
task/AC-12878 Tracking API Keys option added

### LINKED ISSUE #38859: Fedex integration doesn't support Track API being a separate Project in FedEx account
### Preconditions and environment

- Magento 2.4.7
- New FedEx account (created after Oct '23) that offers to choose between `Ship, Rate & Other APIs` and `Track API`

### Steps to reproduce

1. Enable FedEx shipping method by entering API credentials from a FedEx Project of a type `Ship, Rate & Other APIs`.
2. Place an order and enter enter a FedEx tracking number when creating a shipment.
3. Click Track Order to view tracking details.

### Expected result

Tracking details listed

### Actual result

Tracking information is currently not available. Please contact us for more information or email us at example@example.com

### Additional information

select-project
It is not possible to select both `Ship, Rate & Other APIs` and `Track API` for a FedEx Project. So there should be additional config for Track API under the FedEx settings in the Magento Admin.

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Mohamed-Asar**
### Description (*)
Added Fedex Tracking API keys configuration section

### Fixed Issues (if relevant)

1. Fixes #38859 

### Manual testing scenarios (*)

1. Configure Fedex Tracking API Keys in fedex config
2. place one order using fedex shipping method
3. Ship the order and add tracking number
4. verify the tracking info from either admin or frontend

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Mohamed-Asar** [comment]
@magento run all tests

**Comment by df2k2** [comment]
PR works for me. Thanks

**Comment by Mohamed-Asar** [comment]
@magento run all tests

**Review by engcom-Hotel — COMMENTED** [review]
Hello @Mohamed-Asar,

Please resolve the conflicts so that we proceed with this PR further. Meanwhile we are moving the PR `On Hold` bucket.

**Comment by Mohamed-Asar** [comment]
Hello @engcom-Hotel,

I reviewed the conflicts and noticed that the Adobe team addressed this issue in a [commit](https://github.com/magento/magento2/commit/28d239a6f59a2f4c85efc026ce06dc3b5ce41175), which has already been merged.

**Comment by engcom-Hotel** [comment]
Thanks for the confirmation @Mohamed-Asar.

We appreciate your contribution. As the main issue has been fixed, we are closing this PR.

Thanks again 👍

**Pull request closed without merging**
