### PR TITLE
#768 - fix Missing acl.xml for the Magento_Checkout module

### PR DESCRIPTION
**Pull request by tzyganu**
I added the `acl.xml` file in the checkout module.  
As a result, you can see the Checkout Section from the stores->configuration as an element in the user roles resources tree and you can allow or restrict access to it to any admin.

### CODE REVIEW

**Comment by davidalger** [comment]
@tzyganu Please rebase on latest develop to resolve the failing tests. Thanks!

**Comment by strajeru** [comment]
@davidalger Rebased. Now something else fails `The command "phpenv global 5.6" failed and exited with 1 during .`. Can you please restart this?

**Comment by davidalger** [comment]
@strajeru Rebooted. These (currently beta) trusty builds on Travis GCE infrastructure seem to be very finicky as of late…

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-54587

**Pull request merged**
