### PR TITLE
[Backport] Issue #20380 fixed for 2.2

### PR DESCRIPTION
**Pull request by mahesh-rajawat**
Fixed issue #20380 for Magento 2.2.

### Description (*)

Reference PR #20381
### Fixed Issues (if relevant)

1. magento/magento2#20381
2. ...

### Manual testing scenarios (*)

1. Create a downloadable or virtual product.
2. Place an order with this product.
3. In custom controller or anywhere load order with id.
`$order = $this->orderFactory->create()->load($orderId); //your order id`
4. Now get shipping method as object.
`$order->getShippingMethod(true)->getMethod();`
It returns Null now.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by VladimirZaets** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, here is your [Magento instance](https://i-20866-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20866-2-3-develop.instances.magento-community.engineering/admin](https://i-20866-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4361](https://jira.corp.magento.com/browse/ENGCOM-4361) has been created to process this Pull Request

**Pull request merged**
