### PR TITLE
Initialize toolbar.js once

### LINKED ISSUE #25934: chrome initiate two times toolbar.js
### Preconditions (*)
1. vanilla Magento CE 2.3.*
2. chrome browser
3. vanilla with sample data

### Steps to reproduce (*)
1. got to product list, search or advance search page
2. open **developer tools -> network(tab)**(Chrome browser)
3. Select/click any of the toolbar option like Grid/List, Sort By, or show X per page
4. **Network**(Chrome Browser) selected/clicked link triggering two time and because of two time trigger backed doing twice process after canceled one also.
(for verify put any log in to catalog->product->list controller).

image

### Expected result (*)
1. Link should trigger once only or binding of  event make once with 
`vendor/magento/module-catalog/view/frontend/web/js/product/list/toolbar.js`

### Actual result (*)
1. On click/change link trigger two times 

### Solution

> File: vendor/magento/module-catalog/view/frontend/web/js/product/list/toolbar.js::_create(

```
 _create: function () {
	if(window.isToolbarLoaded)
		return;

	this._bind($(this.options.modeControl), this.options.mode, this.options.modeDefault);
	this._bind($(this.options.directionControl), this.options.direction, this.options.directionDefault);
	this._bind($(this.options.orderControl), this.options.order, this.options.orderDefault);
	this._bind($(this.options.limitControl), this.options.limit, this.options.limitDefault);

	window.isToolbarLoaded = true;
},
```

### PR DESCRIPTION
**Pull request by ptylek**
### Description (*)

Continue work that was done by @Nagamaiah007 in #26097.
I changed approach to set events with proper scope of toolbar that javascript is initialized with in order not to process events twice. Previously _bind function was adding events for data-role selectors that were not assigned to this.element scope, so if we had two toolbars on the page (toolbar top and bottom), all events were incorrectly assigned with first toolbar initialization. This change fixes scope for these data-role selectors and won't trigger specific functions to be run twice.

### Related Pull Requests

magento/magento2#26097: Update toolbar.js #25934

### Fixed Issues (if relevant)

1. Fixes magento/magento2#25934

### Manual testing scenarios (*)

1. Got to product list, search or advance search page
2. Open developer tools -> Network tab (Chrome browser)
3. Select/click any of the toolbar option like Grid/List, Sort By, or show X per page
4. Network(Chrome Browser) selected/clicked link triggering two time and because of two time trigger backed doing twice process after canceled one also. (for verify put any log in to catalog->product->list controller).

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ptylek** [comment]
@magento run all tests

**Comment by ptylek** [comment]
@magento run all tests

**Comment by ptylek** [comment]
@magento run all tests

**Comment by ptylek** [comment]
@magento run all tests

**Review by krzksz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-7834](https://jira.corp.magento.com/browse/ENGCOM-7834) has been created to process this Pull Request
:eight_spoked_asterisk: @krzksz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Got to the product list, search or advance search page;
2. Open developer tools -> Network tab (Chrome browser);
3. Select/click any of the toolbar options like Grid/List, Sort By, or show X per page;
4. Network(Chrome Browser) selected/clicked link triggering two time and because of two time trigger backed doing twice process after canceled one also. (for verify put any log in to catalog->product->list controller).

**Before:** :heavy_multiplication_x: On click/change link trigger two times



**After:** :heavy_check_mark: Link triggered once



Toolbar functionality is still working as previously (expected).

**Pull request merged**
