### PR TITLE
magento-engcom/import-export-improvements#51: fix for uploader filepath

### PR DESCRIPTION
**Pull request by staniag**
### Description (*)

Move call to _setUploadFile to after the initation of `$this-> _directory`

### Fixed Issues (if relevant)

1. magento-engcom/import-export-improvements#51

### Manual testing scenarios (*)

1. Using the factory pattern you instantiate the class `Magento\CatalogImportExport\Model\Import\Uploader` with `$filePath` defined

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18810) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @sawebvisum. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by VladimirZaets** [comment]
Hi @sawebvisum, please, sign CLA, otherwise, we can't process your pull request

**Comment by staniag** [comment]
@VladimirZaets already assigned.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3274](https://jira.corp.magento.com/browse/ENGCOM-3274) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@sawebvisum thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @sawebvisum. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
