### PR TITLE
Added possiblity to remove breadcrumbs and add them after/before others

### PR DESCRIPTION
**Pull request by sreichel**
### Description

In M1 `addCrumb($crumbName, $crumbInfo, $after = false)`  had a 3rd parameter that wasn't used. In M2 `$after` has been removed instead of adding functionality.

This PR adds 4 methods:

- `addCrumbAfter($crumbName, $crumbInfo, $after)`
- `addCrumbBefore($crumbName, $crumbInfo, $before)`
- `removeCrumb($crumbName)`
- `getCrumbs()`

(last one was mainly for UnitTests)

"Forward-Port":

1. OpenMage/magento-lts#336
2. netz98/N98_LayoutHelper#10

### Fixed Issues (if relevant)

1. n/a

### Manual testing scenarios

1. add XML layout updates to products to add/remove crumbs (e.g. after/before `home`-crumb)
2. programatically ...

```
 $block->addCrumbAfter(
     'my_crumb',
     ['label' => label, 'title' => title],
     'home'
);
```

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @sreichel. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sreichel** [comment]
Reopen later ...

**Comment by sreichel** [comment]
Re-opend .... 

I'v not so much time for atm, maybe someone else want to finish this ...

**Comment by sreichel** [comment]
I'd like to re-open ....

I'v not so much time for atm, maybe someone else want to finish this ...

**Pull request closed without merging**
