### PR TITLE
[Framework][Translate] Changed translation order to allow language

### PR DESCRIPTION
**Pull request by JSchlarb**
Pull request is already done by #4783 but he didn't update the test. 

Issues: #6563, #6753

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=7142) <br/>All committers have signed the CLA.

**Comment by sippsolutions** [comment]
+1

**Comment by PascalBrouwers** [comment]
@piotrekkaminski Care to take a look at this one and get it merged? This one is a bit better than https://github.com/magento/magento2/pull/4783 I think.

**Comment by schmengler** [comment]
Thank you for your contribution, this is a very valuable PR! I confirmed with the Magento team that we can accept the change :+1:

**Comment by vrann** [comment]
@JSchlarb PR is merged, thanks for the contribution!

**Comment by shyamranpara** [comment]
@magento-team 
if this is fixed then why document is not updated ?
https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/translations/theme_dictionary.html
this still show wrong order of translation priority.

**Comment by alexadvance** [comment]
Doc is wrong. It's confusing.

**Pull request merged**
