### PR TITLE
Prevent saving upload media files in root directory

### PR DESCRIPTION
**Pull request by kenboy**
### Description (*)

If it is impossible to save pictures to the "media" directory, the save goes to the root directory

### Manual testing scenarios (*)

1. Make a ban on writing to the "pub/media/catalog/product" directory
2. Start importing goods containing media information

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @kenboy. Thank you for your collaboration. 
Could you provide a little bit more information regarding the main idea of your PR, please? From the PR title/description I see that the goal is to save files to the root (it would be great if you could clarify the "root" definition here since it's completely relative) if the media directory is not writable. However, I see that the following statement:

```php
$destinationDir = "catalog/product";
$destinationPath = $dirAddon . '/' . $this->_mediaDirectory->getRelativePath($destinationDir);
```

stays unchanged. So, the destination path will be the same as previously. Could you clarify this part, please? 

Thank you!

**Comment by kenboy** [comment]
Hi @rogyar 
When the path formed by the following statement:
```
$destinationDir = "catalog/product";
$destinationPath = $dirAddon . '/' . $this->_mediaDirectory->getRelativePath($destinationDir);
```
and not available for write, an exception is thrown:
```
if (!$this->_fileUploader->setDestDir($destinationPath)) {
  throw new LocalizedException(
    __('File directory \'%1\' is not writable.', $destinationPath)
  );
}
```
setting the "\Magento\CatalogImportExport\Model\Import\Uploader::$_destDir" properties does not occur, the object is not fully formed.

But since it is already stored in the property "\Magento\CatalogImportExport\Model\Import\Product::$_fileUploader", when the function is called again, an incomplete object is used.

**Comment by rogyar** [comment]
Hi @kenboy. Got it, now it makes sense, thank you! 

May I kindly ask you to cover the proposed change by a simple unit test, please? The test will invoke `getUploader()` method a couple of times. 
On the very first invocation, we mock throwing the "not writable" exception. 
On the second invocation, we assert that the routine for uploader initialization is being executed (not skipped as in case of the current implementation with `$this->_fileUploader === null`).

Thank you!

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-6297](https://jira.corp.magento.com/browse/ENGCOM-6297) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@kenboy thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
