### PR TITLE
2.3 develop fix issue 20527 - [Admin] Configurable product variations table cell labels wrong position

### PR DESCRIPTION
**Pull request by Mayur1510**
### Description (*)

Magento 2.3-develop
Configurable product with variations

### Fixed Issues (if relevant)

https://github.com/magento/magento2/issues/20527 : Configurable product variations table cell labels wrong position

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Mayur1510. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
Hi @Mayur1510. Thank you for your collaboration. There's already one PR created earlier for this issue 
https://github.com/magento/magento2/pull/20528.

**Comment by sivaschenko** [comment]
Hi @Mayur1510 , thank you for the pull request, however, I have to close it as a duplicate. Feel free to contact me if you have any comments or questions

**Comment by ghost** [comment]
Hi @Mayur1510, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+magento2+20573), it will take less than a minute. </br>Your feedback will help us to improve contribution process.

**Pull request closed without merging**
