### PR TITLE
[Forwardport] fixed Quote Item Prices are NULL in cart related events. #18685

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)
before these two observers checkout_cart_product_add_after, checkout_cart_product_update_after cart item is not saved into the database the object is only created and in the object price was not set but custom price was set so there was no issue of custom price, we could have added the price in the item from two files:
app/code/Magento/Quote/Model/Quote/Item/Processor.php and
app/code/Magento/Quote/Model/Quote.php
I have added the price in this file app/code/Magento/Quote/Model/Quote/Item/Processor.php

### Fixed Issues (if relevant)

1. magento/magento2#18685: Quote Item Prices are NULL in cart related events

### Manual testing scenarios (*)

1. create a module which has observers for these two events checkout_cart_product_add_after, checkout_cart_product_update_after cart
2. now in the observer try to get the added item price by calling $observer->getEvent()->getQuoteItem()->getPrice()

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

Backport for: https://github.com/magento/magento2/pull/18808

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ashutoshwebkul. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by ghost** [comment]
#squashtoberfest

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3272](https://jira.corp.magento.com/browse/ENGCOM-3272) has been created to process this Pull Request

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @ashutoshwebkul. Why your port contains more code changes than original Pull Request? What the reason for that?

**Comment by VladimirZaets** [comment]
Hi @ashutoshwebkul, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Pull request closed without merging**
