### PR TITLE
magento/magento2#33422: Fixed excel writer produces invalid files for numbers preceded by spaces

### LINKED ISSUE #33422: Excel writer produces invalid files for numbers preceded by spaces
### Preconditions (*)
Encountered in production with Magento 2.4.1, but this will happen with any Magento2 version, since the code hasn't changed in 7 years.

### Steps to reproduce (*)
1. Create an instance of `Magento\Framework\Convert\Excel` with an `ArrayIterator` over an array containing a field with a value like `␣123` (i.e. space followed by digits, read `␣` as space).
2. Call `convert` or `write` on the object.
3. Try opening the resulting file with a current version of Microsoft Excel or LibreOffice Calc. They will refuse to open the file or display `NaN` for the value respectively.

### Expected result (*)
The Excel XML should encode field as a `String`:

```xml
<Data ss:Type="String"> 123</Data>
```

### Actual result
The value is encoded as `Number`:

```xml
<Data ss:Type="Number"> 123</Data>
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Note:** For Microsoft Excel users this can be problematic, as Excel does not report the actual error. The Excel file needs to be opened as an XML file, and the value of `ss:Type` needs to be fixed manually to be able to import the file at all. LibreOffice Calc _does_ open the file, but doesn't show a warning and silently replaces the cell's value with `NaN`, so people may not even be aware that some data is actually missing.

### Cause

The Magento2 class mainly relies on PHP's `is_numeric` function to determine the `ss:Type`, which causes the bug: https://github.com/magento/magento2/blob/bf4cdad2b1d0436be831c1f5c89c1adc77bfd1fc/lib/internal/Magento/Framework/Convert/Excel.php#L153

### Workaround

From a developer's perspective, the issue can be circumvented by `trim`ing all numeric values before passing them to the `Excel` class.

### PR DESCRIPTION
**Pull request by hutychivan**
### Description (*)

When creating Excel, the is_numeric function is used to determine the cell type. The is_numeric function returns true for strings of the type "123", "\t123" etc. Then the cells are given the Number type, which when viewed leads to an error and the data is displayed as NaN.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33422

### Manual testing scenarios (*)

1. Create an instance of Magento\Framework\Convert\Excel with an ArrayIterator over an array containing a field with a value like ␣123 (i.e. space followed by digits, read ␣ as space).
2. Call convert on the object.
3. Try opening the resulting file with a current version of Microsoft Excel or LibreOffice Calc. Previously the value was NaN, now the column type is changed to String and the value is displayed correctly.

### Questions or comments

Although the is_numeric and ctype_space functions change their behavior in 8.1, these changes should work correctly on both 7.4 and 8.1.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hutychivan** [comment]
@magento run all tests

**Comment by hutychivan** [comment]
@magento run all tests

**Comment by hutychivan** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by hutychivan** [comment]
@magento run  Functional Tests B2B

**Comment by hutychivan** [comment]
@magento run Functional Tests B2B

**Comment by hutychivan** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Echo** [comment]
:heavy_check_mark: QA Passed
Fixed excel writer produces invalid files for numbers preceded by spaces

**Manual testing scenario:**
1. Create an instance of Magento\Framework\Convert\Excel with an ArrayIterator over an array containing a field
2. Call convert or write on the object.
3. Open the generated file, should contain the encoded value as string but it is coming as number
Sample code
```
    $data[] = ['message' => " 1233"];
    $convert = new \Magento\Framework\Convert\Excel(new \ArrayIterator($data));
    $file = $convert->convert('single_sheet');
    $fileName = "test_without_space.xml";
    return $this->_fileFactory->create($fileName, $file, DirectoryList::VAR_DIR, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');

```
**Before:** :heavy_multiplication_x:  
Generated file should contain the encoded value as string but it is coming as number
`<Data ss:Type="Number"> 1233</Data>`
image

**After:** :heavy_check_mark:  
Generated file should contain the encoded value as string but it is coming as number
`<Data ss:Type="String"> 1233</Data>`
image

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Pull request merged**
