### PR TITLE
Fix #27985 CMS page link active on current page

### LINKED ISSUE #27985: Privacy and Cookie Policy link not display as active on current page.
### Preconditions (*)

Install Magento 2.3.4

### Description (*)
Go to the footer and click on the "**Privacy and Cookie Policy**" link. After the redirect, It's not displayed as active link as like other footer links.

### Steps to reproduce (*)
Go to footer and click on the "**Privacy and Cookie Policy**" link

### Expected result (*)

It should be displayed as an active link when the "**Privacy and Cookie Policy**" page is open.

### Actual result (*)

It's not displayed as an active link when the "**Privacy and Cookie Policy**" page is open.

### PR DESCRIPTION
**Pull request by srsathish92**
### Description (*)
This PR helps to address issue #27985 , Added additional condition to check current page URL & link URL are equal.

### Fixed Issues (if relevant)

1. magento/magento2#27985: Privacy and Cookie Policy link not display as active on current page

### Manual testing scenarios (*)
1. Click "privacy and cookie policy" link in footer -> After opening the page "privacy and cookie policy" should be active.
2. Enter "baseurl/privacy-policy-cookie-restriction-mode/?test" -> After opening the page "privacy and cookie policy" should be active.
3. vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist lib/internal/Magento/Framework/View/Test/Unit/Element/Html/Link/CurrentTest.php

### Questions or comments
If any please let me know your feedbacks.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by srsathish92** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @srsathish92. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @srsathish92, here is your [new Magento instance](https://pr-28004.instances.magento-community.engineering).
Admin access: [https://pr-28004.instances.magento-community.engineering/admin_2107](https://pr-28004.instances.magento-community.engineering/admin_2107)
Login: `5220cb9f` Password: `b3a2a07d57d1`
Instance will be terminated in up to 3 hours.

**Comment by dmytro-ch** [comment]
@magento run all tests

**Review by VladimirZaets — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7514](https://jira.corp.magento.com/browse/ENGCOM-7514) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Before:**
image

**After:**
image

**Comment by engcom-Kilo** [comment]
Failed functional test not related to the changes in this PR

**Review by slavvka — CHANGES_REQUESTED** [review]
@srsathish92 please resolve conflicts and re-run tests after upgrade to PHP 7.4

**Comment by srsathish92** [comment]
@slavvka I have fixed the conflicts, please review the same

**Comment by slavvka** [comment]
@magento run all tests

**Comment by srsathish92** [comment]
@magento run Database Compare

**Review by slavvka — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @slavvka, thank you for the review.
[ENGCOM-7514](https://jira.corp.magento.com/browse/ENGCOM-7514) has been created to process this Pull Request

**Pull request merged**
