### PR TITLE
Display correctly "Add" button label for the block class \Magento\Con…

### PR DESCRIPTION
**Pull request by sylvainraye**
…fig\Block\System\Config\Form\Field\FieldArray\AbstractFieldArray

### CODE REVIEW

**Comment by ishakhsuvarov** [comment]
Hi @diglin 
Could you please specify the issue you are fixing with this PR more clearly? (e. g. some steps to reproduce, actual / expected result, etc.)
Thank you!

**Comment by sylvainraye** [comment]
Hi @ishakhsuvarov 

There are only two lines of code changed and if you read them, you will directly see that the implementation of the "Add" button is duplicated in the original code and that a third party developer cannot set up the label without overwriting the template.

However concretely, the class filename `app/code/Magento/Config/Block/System/Config/Form/Field/FieldArray/AbstractFieldArray.php` is a backend configuration form field which allows to create a kind of grid with a mapping of content.
The label of the button "Add" is initialized by the constructor of the class with the value  `$this->_addButtonLabel = __('Add');` but in the template `app/code/Magento/Config/view/adminhtml/templates/system/config/form/field/array.phtml` there is call to a missing method `getAddButtonLabel()`. If a developer extends the class and wants to change the label name, he can't do it via the protected variable `_addButtonLabel` because it has no effect on the template.

I just the possibility to a developer to customize this button label in a proper way

**Comment by ishakhsuvarov** [comment]
@diglin Thank you for the clarification.

**Comment by okorshenko** [comment]
Thank you for contribution to Magento 2 project!

**Comment by Ctucker9233** [comment]
@magento-engcom-team This appears to still not be included in 2.1.10. what version will have this simple fix?

**Pull request merged**
