### PR TITLE
Fix ftp_nlist for empty folders returns false

### LINKED ISSUE #31288: FileSystem IO Ftp connection ls() method error for empty folders
### Preconditions (*)

1. Magento 2.4-develop
2. Use the FTP connection by `Magento\Framework\Filesystem\Io\Ftp`

Regarding to the PHP documentation `ftp_nlist() `method can return as array and the false,
and in case of empty folder it returns false.
https://github.com/magento/magento2/blob/ad2945209811dc9fb5cd531af8f2a2bace8647f3/lib/internal/Magento/Framework/Filesystem/Io/Ftp.php#L316

Need to add additional check for the (false) case ad not put  result of` ftp_nlist()` directly to the foreach loop

### Steps to reproduce (*)

1. Try to execute ls method of Magento\Framework\Filesystem\Io\Ftp::ls() on empty folder

### Expected result (*)

1. [Screenshots, logs or description]
2.. empty array returned

### Actual result (*)

1. [Screenshots, logs or description]
2. Exception Returned
` Invalid argument supplied for foreach() in vendor/magento/framework/Filesystem/Io/Ftp.php on line 319`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#31288

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-8549](https://jira.corp.magento.com/browse/ENGCOM-8549) has been created to process this Pull Request
:eight_spoked_asterisk: @swnsma, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

Try to execute ls method of Magento\Framework\Filesystem\Io\Ftp::ls() on an empty folder

**Before:** :heavy_multiplication_x: Exception Returned `Invalid argument supplied for foreach() in vendor/magento/framework/Filesystem/Io/Ftp.php on line 319`

Screenshot from 2020-12-28 10-08-58

**After:** :heavy_check_mark: An empty array returned

**Pull request merged**
