### PR TITLE
Fotorama gallery styles moved from lib/web to Blank theme

### PR DESCRIPTION
**Pull request by Igloczek**
`lib/web` directory seems to not be the best place to keep non-vendor code related only to frontend themes (it's the same story as `js` directory in M1 which contains everything and developers were scary to touch it), because it's not possible to change any styles on theme level and developers need to create dummy modules to overwrite styles or manually move all code to own theme.

It will be a breaking change for themes that use Fotorama gallery, but are not children of Blank theme.

### CODE REVIEW

**Comment by Igloczek** [comment]
Issues reported by Jasmine tests on CI seems to not be related to this PR.

```
 Magento_Braintree/js/view/payment/method-renderer/cc-form
   - Check if payment code and message container are restored after onActiveChange call....X Check if payment code and message container are restored after onActiveChange call.
     Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL. (1)
     TypeError: undefined is not an object (evaluating 'braintreeCcForm.messageContainer') in http://localhost:8000/dev/tests/js/jasmine/tests/app/code/Magento/Braintree/frontend/js/view/payment/method-renderer/cc-form.test.js (line 57) (2)
```

**Comment by vrann** [comment]
@Igloczek are you working on the Jasmine test issue?

**Comment by Igloczek** [comment]
Nah, sorry.

**Comment by okorshenko** [comment]
Hi @Igloczek 
We are closing this PR due to inactivity. Feel free to reopen it once ready

**Comment by Igloczek** [comment]
@okorshenko as I mentioned before, these issues are not related to the code changes I made, but issues inherited from develop branch

I was even pinging you on slack, that tests are continuously failing, but no one responded

**Pull request closed without merging**
