### PR TITLE
Remove configuration options from useless scopes

### PR DESCRIPTION
**Pull request by fredden**
### Description
These four settings are advertised as being able to be set at `store scope`, however there is no sense in trying to set these at this level. Also, the relevant section isn't visible at those scopes anyway.
- Admin Account Sharing
- Password Reset Protection Type
- Max Number of Password Reset Requests
- Min Time Between Password Reset Requests

Screenshot_2022-04-22_19-21-42

### Manual testing scenarios
1. Navigate in the admin to Stores -> Settings -> Configuration -> Advanced -> Admin -> Security
1. Notice the scope hint next to each option. This is `[global]` for most, but `[store view]` for others.
1. Change the scope to something non-global.
1. Notice that the configuration path no longer exists / isn't visible in the admin.
1. Apply the changes in this pull request.
1. Navigate in the admin to Stores -> Settings -> Configuration -> Advanced -> Admin -> Security
1. Notice the scope hint next to each option. This is now `[global]` for all.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests B2B

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests B2B

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests B2B

**Pull request merged**
