### PR TITLE
[Forwardport] add error message in else condition

### PR DESCRIPTION
**Pull request by gelanivishal**
### Original Pull Request
https://github.com/magento/magento2/pull/17982

### Description

STORES > Settings > Configuration > Sales > Shipping Methods > Free Shipping > Enabled > select Yes > > Minimum Order Amount > Enter 50 > Show Method if Not Applicable > Select Yes > Save Config

By configuring above settings Free shipping method should show in frontend with the error message if it is not applicable.

But the shipping is only displayed when it is applicable no matter what the option "Show Method if Not Applicable" value is set to.

### Fixed Issues (if relevant)

1. magento/magento2#17977: Show Method if Not Applicable for Free Shipping doesn't work.

### Manual testing scenarios

1. Show Method if Not Applicable > Select Yes in this case if free shipping not applied then it should show error message
2. Show Method if Not Applicable > Select No in this case if free shipping not applied then it shouldn't show free shipping method

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3144](https://jira.corp.magento.com/browse/ENGCOM-3144) has been created to process this Pull Request

**Comment by gelanivishal** [comment]
@vaibhavahalpara Why do you close this PR? Are you maintainer?

**Comment by gelanivishal** [comment]
@vaibhavahalpara What's your problem? Have you checked my above message?

**Comment by sidolov** [comment]
Hi @gelanivishal , as original PR author @vaibhavahalpara have priority for port creation. So, I'm closing this PR as duplicate for https://github.com/magento/magento2/pull/18507. @vaibhavahalpara , if you worry about points for the PR, we are trying to be fair with all community members and you will receive points anyway (in case when you port PR by yourself and if someone from community will port your PR). You can read information about contribution points in our [DevDocs page](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#points)
Thanks!

**Pull request closed without merging**
