### PR TITLE
Continuation of #27270 regarding moving JS scripts before `</body>`

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
I think that @krzksz has done tremendous and amazing job with #27270 . That's why I want it to be finally merged to the mainline, no longer modify code there (as it's really great bugfix and performance improvement).

My PR is a result of noticing that defer plugin is attached to all HTTP responses:
```
        self::TYPE_JSON     => Result\Json::class,
        self::TYPE_RAW      => Result\Raw::class,
        self::TYPE_REDIRECT => Result\Redirect::class,
        self::TYPE_FORWARD  => Result\Forward::class,
        self::TYPE_LAYOUT   => \Magento\Framework\View\Result\Layout::class,
        self::TYPE_PAGE     => \Magento\Framework\View\Result\Page::class,
```
Which is much too much. I verified very thoroughly the bet point to attach the Plugin to affect only Layout and Pages generated by Magento and moved the plugin there, modifying it the way, that would work as expected.

In the meantime - @sshymko came with amazing hints to reduce the overhead by counting the position from the end, instead of from the beginning - so I included hist changes into my PR.

### Fixed Issues (if relevant)
1. magento/magento2#27270

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
someone buy for this man a cup of coffee pls :) and cookies of course

**Comment by lbajsarowicz** [comment]
Just in case https://ko-fi.com/m2tips

**Comment by ihor-sviziev** [comment]
I put this PR on hold till https://github.com/magento/magento2/pull/27270 will be merged

**Comment by lbajsarowicz** [comment]
@ihor-sviziev you can review this, maybe they gonna merge that together

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7474](https://jira.corp.magento.com/browse/ENGCOM-7474) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
Code review - Approved ✔

MHI fails as this PR https://github.com/magento/magento2/pull/27270 wasn't merged yet, on which based this PR.

**Comment by lbajsarowicz** [comment]
Squashed to original PR

**Pull request closed without merging**
