### PR TITLE
Add translatable text in address renderers

### LINKED ISSUE #36942: Translation VAT in address renderer
### Summary

Version: Magento 2.4.5

You are unable to translate the text "VAT", "T", "F" in the address renderers.

### Examples

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/view/adminhtml/web/template/default-address.html#L47
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/view/frontend/web/template/billing-address/details.html#L20
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/view/frontend/web/template/shipping-address/address-renderer/default.html#L18
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/view/frontend/web/template/shipping-information/address-renderer/default.html#L18

### Proposed solution

Change it to `<translate args="'VAT'"></translate>` instead so you are able to translate it.

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by vacla**
### Description (*)
Added translate tags around text that was not able to translate yet for address renderers

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36942

### Manual testing scenarios (*)

1. Add translations for "VAT" other than English and switch store to that language.
2. Add product to cart
3. Go to the checkout fill in your address including VAT.
4. In the payment/billing step you will see that VAT has the translation that you have set

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by vacla** [comment]
@magento run all tests

**Comment by vacla** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B,Integration Tests

**Comment by vacla** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B,Integration Tests

**Comment by vacla** [comment]
@magento run all tests

**Comment by vacla** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by vacla** [comment]
@magento run Functional Tests EE

**Comment by vacla** [comment]
@magento run Functional Tests EE

**Comment by vacla** [comment]
@magento run Functional Tests EE

**Comment by vacla** [comment]
@magento run Functional Tests EE

**Comment by vacla** [comment]
@magento run Functional Tests EE

**Comment by vacla** [comment]
@magento run Functional Tests EE

**Comment by vacla** [comment]
@magento run Functional Tests EE

**Comment by vacla** [comment]
@magento run Functional Tests EE

**Comment by vacla** [comment]
@magento run Functional Tests EE

**Comment by vacla** [comment]
@magento run all tests

**Comment by vacla** [comment]
@magento run Functional Tests CE,Functional Tests EE,Integration Tests

**Comment by vacla** [comment]
@magento run Functional Tests CE,Functional Tests EE

**Comment by vacla** [comment]
@magento run Functional Tests EE,Functional Tests CE

**Comment by vacla** [comment]
@magento run Functional Tests EE,Functional Tests CE

**Comment by vacla** [comment]
@magento run all tests

**Comment by vacla** [comment]
@magento run all tests

**Review by mrtuvn — APPROVED** [review]
Looks good at me

**Comment by engcom-Lima** [comment]
@magento run all tests

**Review by engcom-Lima — CHANGES_REQUESTED** [review]
Hi @vacla ,

Thanks for the collaboration & contribution!

### :x: QA not Passed

After taking PR changes still VAT is not translated to specific language (German in my case)

**Manual testing scenario:**

1. Add translations for "VAT" other than English and switch store to that language.
2. Add product to cart
3. Go to the checkout fill in your address including VAT.
4. In the payment/billing step you will see that VAT has the translation that you have set

**Before:** :heavy_multiplication_x: 
Screenshot 2023-06-15 at 6 27 52 PM


**After:** :heavy_check_mark:  
Screenshot 2023-06-15 at 6 33 18 PM

Kindly recheck the PR.

Thanks

**Comment by vacla** [comment]
@engcom-Lima I retested my changes on my local 2.4.6 machine and it works fine there, see following screenshots:
Screenshot from 2023-06-16 00-49-43
Screenshot from 2023-06-16 00-49-33
Screenshot from 2023-06-16 00-46-19

For me, I created in the i18n folder a file nl_BE.csv (dutch belgium) and put the following for example in it to see what happened, and ran setup upgrade and it just worked out of the box:

`VAT,VATtingen`

**Comment by mrtuvn** [comment]
@engcom-Lima previously you can't translate that text via csv. It's hard-coded as english text. So basically if you used DE language and want to translate you have no choice to copy that template contain VAT text and replace with correct translate in DE

**Comment by engcom-Lima** [comment]
Hi @vacla ,

Thanks for your contribution and collaboration.

Verified this PR and it is working fine for **normal checkout**. Below is the screenshot for your reference:
Screenshot 2023-06-20 at 12 36 31 PM




But it is not working for the **order via multi-shipping**. Below is the screenshot for your reference:
Screenshot 2023-06-20 at 12 38 29 PM

Kindly recheck the issue. If we are missing anything please inform to us.

Thanks

**Comment by vacla** [comment]
@engcom-Lima These seems to be translated thru the Admin already if you go to Configurations > Customers > Customer Configuration > Address Templates > HTML

**Comment by mrtuvn** [comment]
can we add translate for text as well in config ?

**Review by engcom-Lima — APPROVED** [review]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**
- Create 2 store views.
- Add translations to 2nd store of any language like German.

**Manual testing scenario:**

1. Add translations for "VAT" other than English and switch store to that language.
2. Add product to cart
3. Go to the checkout fill in your address including VAT.
4. In the payment/billing step, you will see that VAT has the translation that you have set


**Before:** :heavy_multiplication_x: "VAT" was not translated to the specific language.
Screenshot 2023-06-15 at 6 27 52 PM



**After:** :heavy_check_mark:  
Screenshot 2023-06-21 at 11 25 39 AM
Screenshot 2023-06-21 at 11 26 24 AM


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by vacla** [comment]
Closed and reopened for update labels

**Comment by vacla** [comment]
@engcom-Lima is it possible to move this back to the correct dashboard

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Unit Tests

**Comment by engcom-Charlie** [comment]
The functional B2B failures are not consistent in latest 2 builds. The test failures are not related to the PR changes as failing tests are known issues, below is list of open JIRAs for the same.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36943/5027c0dddb8601b3641e826d20623dc4/Functional/allure-report-b2b/index.html#categories
image

**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36943/b65427096fe3ebd66c575dbf1f161e4b/Functional/allure-report-b2b/index.html#categories
image

**Known issues:**
[ACQE-6309](https://jira.corp.adobe.com/browse/ACQE-6309) - AdminCreateDraftQuoteFromQuoteGridPageTest
[ACQE-6774](https://jira.corp.adobe.com/browse/ACQE-6695) - StorefrontCashOnDeliveryPaymentForSpecificCountryTest

**Comment by engcom-Charlie** [comment]
The functional CE failures are not consistent in latest 2 builds. The test failures are not related to the PR changes as failing tests are known issues, below is list of open JIRAs for the same.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36943/6cfc77012f63989dd6e35a06e54c9f69/Functional/allure-report-ce/index.html#categories/a644910ae0cb11e839a98baa21929b76/49ac69609d300b00/
image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36943/21d6aa3caeaef87ec87d299c2b7bed9e/Functional/allure-report-ce/index.html#categories/8f0831c1d06562890f5ec21062dae309/5c0d4cf99254d45c/
image


**Known issues:**
[ACQE-6786](https://jira.corp.adobe.com/browse/ACQE-6786) - StorefrontAddBundleDynamicProductToShoppingCartWithDisableMiniCartSidebarTest
[ACQE-6695](https://jira.corp.adobe.com/browse/ACQE-6695) - TierPricingWhenPriceScopeIsWebsiteWorkingProperlyWithMultipleCurrenciesConfiguredTest

**Comment by engcom-Charlie** [comment]
The Functional EE failures are not consistent in latest 2 builds. The test failures are not related to the PR changes as failing tests are known issues, below is list of open JIRAs for the same. Hence moving this PR to Merge in Progress.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36943/a7dae76d0d87afc93fd7d7080ecc3eb5/Functional/allure-report-ee/index.html#categories
image



**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36943/b2d15d0898fec4e48697079faf70ff47/Functional/allure-report-ee/index.html#categories/a644910ae0cb11e839a98baa21929b76/814ac8467de6ba13/
image


**Known issues:**
[ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331) - StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest
[ACQE-6695](https://jira.corp.adobe.com/browse/ACQE-6695) - TierPricingWhenPriceScopeIsWebsiteWorkingProperlyWithMultipleCurrenciesConfiguredTest
[ACQE-6774](https://jira.corp.adobe.com/browse/ACQE-6774) - StorefrontCashOnDeliveryPaymentForSpecificCountryTest

**Comment by vacla** [comment]
Any idea why this got reverted here @engcom-Charlie : https://github.com/magento/magento2/commit/52fa63814eaaa6c0278a1a90bd1a723fe83af253

**Comment by engcom-Charlie** [comment]
Hi @vacla,

Thank you for your contribution!

We were facing some consistent build failure on mainline PR hence reverted this change. Currently we have moved the PR back in Merge, will be merging this PR changes soon in the upcoming PR.

Thank you!

**Pull request merged**
