### PR TITLE
`cms_index_noroute` does not exist

### PR DESCRIPTION
**Pull request by AntonEvers**
Based on `\Magento\Cms\Controller\Noroute\Index` I believe it should be `cms_noroute_index`

### CODE REVIEW

**Comment by piotrekkaminski** [comment]
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/cms-index-noroute-does-not-exist/idi-p/45063).

**Comment by AntonEvers** [comment]
@piotrekkaminski @vkorotun this is a bug

**Comment by AntonEvers** [comment]
@piotrekkaminski @vkorotun could you please remove the improvement tag and mark it as a bug? This is a malfunction and clearly a mistake or typo.

**Comment by vrann** [comment]
@ajpevers can you please provide steps to reproduce the issue? I haven't found where it is actually used.

**Comment by vrann** [comment]
@ajpevers closing, as far as the goal of the PR is unclear. Feel free to re-open with more information.

**Comment by AntonEvers** [comment]
Hi @vrann,

Sorry for the delay. Without this PR, if you create a widget instance on the "CMS No-Route Page", it does not appear on the 404 page. After applying the PR it does.

screen shot 2017-04-13 at 09 22 14

Can you reopen the PR?

Thanks!

**Comment by AntonEvers** [comment]
@vrann can you reopen this PR based on my latest comment?

**Comment by AntonEvers** [comment]
@vrann bump

**Pull request closed without merging**
