### PR TITLE
PHPDocs fixes [Sales module]

### PR DESCRIPTION
**Pull request by ghost**
### Description
- Small PHPDocs fixes in Sales module

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by osrecio — APPROVED** [review]
Thanks for your PR @SikailoISM .

I checked manually and seems to be OK to merge.

**Comment by magento-engcom-team** [comment]
Hi @osrecio, thank you for the review.
[ENGCOM-3907](https://jira.corp.magento.com/browse/ENGCOM-3907) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @SikailoISM. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Comment by magento-engcom-team** [comment]
Hi @SikailoISM. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
