### PR TITLE
Changed misunderstanding title

### LINKED ISSUE #29416: [Issue] Changed misunderstanding title
This issue is automatically created based on existing pull request: magento/magento2#29410: Changed misunderstanding title

---------

### Preconditions: (*)

In order failure page "We received your order!" is not appopriate as the title of the page.

### Steps to reproduce: (*)

1. Checkout an order with Paypal and then click cancel and return to the site
2. Read at the title of the failure page

**Actual Result:** :heavy_multiplication_x: 

Screenshot from 2020-08-10 16-05-03

**Expected Result:** :heavy_check_mark: The user is notified that the order failed

Screenshot from 2020-08-11 16-52-40

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by angelo983**
### Description (*)

In order failure page "We received your order!" is not appopriate as the title of the page.

### Manual testing scenarios (*)

1. Checkout an order with Paypal and then click cancel and return to the site
2. Read at the title of the failure page

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29416: Changed misunderstanding title

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@angelo983 
Would be good to cover this chenge with MFTF or integration test. Could you do that?

**Comment by ihor-sviziev** [comment]
@magento create issue

**Comment by angelo983** [comment]
> @angelo983
> Would be good to cover this chenge with MFTF or integration test. Could you do that?

Ihor, I'm sorry but I'm not confident with MFTF, anyway how would be useful integration test for a label change?

**Comment by ihor-sviziev** [comment]
I just double checked - seems like we don't really need any test coverage as it will be much-much harder to cover it than the fix itself.

I'll put there no need to cover this change with any type of tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7967](https://jira.corp.magento.com/browse/ENGCOM-7967) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Simulate an order failure in checkout
2. Read at the title of the failure page

**Before:** :heavy_multiplication_x: 

Screenshot from 2020-08-10 16-05-03

**After:** :heavy_check_mark: The user is notified that the order failed

Screenshot from 2020-08-11 16-52-40

**Pull request merged**
