### PR TITLE
MC-41852: issue with product image cache

### LINKED ISSUE #32699: issue with product image cache
If you add a new image to the product with an image name that contains '.'  dot, then save the product and clean image cache, a new cache will not be generated

### Preconditions (*)

1. Magento 2.4.2

### Steps to reproduce (*)

1.Create a new product or go to the existing one.
2. Add image to product (image name should contain dot '.'). For e.g. 'i.mage.jpg'
3. Save product (on this step, image cache will be generated and all is fine)
4. Go to System -> Cache Management and click by button "Flush Catalog Image Cache"
5. Find your product on frontend

### Expected result (*)

 Image cache for product image generated successfully

### Actual result (*)

Image cache is not generated  (showed placeholder)
image

---

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

### PR DESCRIPTION
**Pull request by temptask**
### Description (*)
This PR fixes issue when product image that contains dot in image name at first or second position (e.g. "i.mage.png") is not showing on frontend after flushing catalog image cache.

This happened because when uploading product image magento uses files dispersion setting and saving image to path generated by `\Magento\Framework\File\Uploader::getDispersionPath` which consists of two directories defined by two first letters of filename (e.g. path for "image.png" will be /i/m/image.png). But, in case when there is dot in first two letters of filename, directory name with underscore will be used (e.g. path for filename "i.mage.png" will be /i/_/image.png).

When catalog image cache is flushed and frontend product image is requested magento tries to create new cache file in `\Magento\MediaStorage\App\Media::createLocalCopy` and tries to retrieve original image location by calling `\Magento\MediaStorage\App\Media::getOriginalImage`.

This function is using regexp to get from path like _"media/catalog/product/cache/838ef3af6b51df9f635b7eb110d280c6/i/m/image.png"_ original image path _"/i/m/image.png"_. 
This regexp was changed in https://github.com/magento/magento2/commit/362eba826be3a7aff9ce9de579893e639ffc2cfd from `|^.*((?:/[^/]+){3})$|` to `|^.*?((?:/([^/])/([^/])/\2\3)?/?[^/]+$)|`. New regexp (`|^.*?((?:/([^/])/([^/])/\2\3)?/?[^/]+$)|`) is not taking into consideration cases when original filename contained dot in first two letters and therefore path with underscore instead of dot is generated.

In this PR old regexp (`|^.*((?:/[^/]+){3})$|`) was restored since its working correctly with all filenames.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32699

### Manual testing scenarios (*)

1. Create a new product or go to the existing one
2. Add image to product (image name should contain dot in first or second position, e.g. "i.mage.png")
3. Save product
4. Go to System -> Cache Management and click button "Flush Catalog Image Cache"
5. Open product on frontend

**Actual result:** (before this PR)
Placeholder showed instead of product image

**Expected result:** (after this PR)
Product image is showed

### Questions or comments

Since commit https://github.com/magento/magento2/commit/362eba826be3a7aff9ce9de579893e639ffc2cfd that changed working regexp to not correctly working with all filenames regexp was introduced with "[performance]" text in commit message, it was probably fixing some performance issues of older regexp.
In this PR it was decided not to modify this not fully working regexp but rather restore old one because it was not very clear what performance changes is was making and because of possible risks of introducing new regexp.
So, reviewer probably should take a close look at deleted regexp before accepting this PR.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
Can you cover your changes with automation tests

**Comment by temptask** [comment]
@magento run all tests

**Comment by temptask** [comment]
@mrtuvn Looks like it's not possible to create mftf test for this PR, because product page html with product image loaded succesfully is same as page with product page not loaded since instead of product image placeholder is loaded from same url.
Test will need to compair contents of image and looks like its not possible with mftf.

**Comment by temptask** [comment]
@magento run all tests

**Comment by temptask** [comment]
@magento run all tests

**Comment by temptask** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Review by duhon — APPROVED** [review]

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9095](https://jira.corp.magento.com/browse/ENGCOM-9095) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
Hi @sidolov @sivaschenko,
I changed the priority to P2 because some product images are shown as a default Magento image as if there is no image uploaded. For instance, it also works incorrectly when the image has an underscore in the filename (which is quite frequent).

PS: I believe we should cover this replace with some unit tests and add multiple data samples.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9095](https://jira.corp.magento.com/browse/ENGCOM-9095) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Have Magento installed with latest version


**Manual testing scenario:**

1. Create a new product in the admin side.

2. Upload image files to the same product and save it. (Where image file names should be involved with dots as like - a.asd.sads.png, a1.cds22.12.jpeg etc)
 
3. Go to System -> Cache Management and click button "Flush Catalog Image Cache"

4. View the product details page in the front end and validate images are displayed


**Before:** :heavy_multiplication_x: Image were not getting displayed in the product details page.

image


**After:** :heavy_check_mark: Images are getting displayed in the product details page.

image


Tried to delete the uploaded files , and tried to replace with new image files as such. No issues noticed. There is no additional testing is required as part of regression since there is MTFT already covered with this PR.

**Pull request merged**
