### PR TITLE
Fixed 19371-Attribute Heading border misaligned. 

### PR DESCRIPTION
**Pull request by suryakant-krish**
### Description (*)

Attribute Heading border misaligned. 
### Fixed Issues (if relevant)

1. magento/magento2#19371: Attribute Heading border misaligned.

### Manual testing scenarios (*)

1. Login to admin panel > Stores > Attribute sets > choose any attribute.
2. Edit Attribute set name heading border.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by orlangur** [comment]
@suryakant-krish please squash changes into a single commit. Also, note, that nowadays any changes must be delivered to `2.3-develop` first.

**Comment by sivaschenko** [comment]
@suryakant-krish please [port](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting) this pull request to 2.3-develop branch.

**Comment by sidolov** [comment]
Hi @suryakant-krish , please, resolve merge conflicts

**Comment by suryakant-krish** [comment]
@sidolov,

I have resolved conflicts. please review that.

**Comment by sivaschenko** [comment]
Hi @suryakant-krish thanks for the update! This pull request contains much more changes than https://github.com/magento/magento2/pull/19414, is it intentional? Also can you please check if test fixes applied to 2.3-develop PR should be applied to this pull request as well.

Finally, it would be great to squash changes into a single commit.

**Comment by sivaschenko** [comment]
Closing this pull request due to inactivity, feel free to reopen if you'd like to continue progress on in

**Comment by amol2jcommerce** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  amol@twojay.in
    Domain 2jcommerce.in has exceeded the max emails per hour (251/250 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o10.sgmail.github.com ([167.89.101.201]:45579)
	by mail.2jcommerce.co.uk with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-d057-amol=2jcommerce.in@sgmail.github.com>)
	id 1gwnx5-000Azv-78
	for amol@2jcommerce.in; Thu, 21 Feb 2019 12:59:47 +0000
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=v0c/pgI2i1plM0rIhD4Aft36xn4=; b=XHgAkBxhxFNfvKfu
	3l+2qZUWGZCkbry5F57ARfB+6iA8hOd2Tye2SeyExfMw0e97JD2SkXoONfF4ElwE
	ssfZI0S7Wn7N8BL3cQEjqJ4ewOBCUV1ydu9pVu9K/qvcqfxy+7clLWQiL9oMNstJ
	UtdDPzNLSA3HgXNmdm117OZfXYY=
Received: by filter0251p1iad2.sendgrid.net with SMTP id filter0251p1iad2-12155-5C6EA098-43
        2019-02-21 12:59:04.897951725 +0000 UTC m=+1355378.240859507
Received: from github-lowworker-dcd58f3.cp1-iad.github.net (unknown [192.30.252.33])
	by ismtpd0050p1iad1.sendgrid.net (SG) with ESMTP id fT-VCyHlSCOUP7fgijKBkQ
	for <amol@2jcommerce.in>; Thu, 21 Feb 2019 12:59:04.769 +0000 (UTC)
Received: from github.com (localhost [127.0.0.1])
	by github-lowworker-dcd58f3.cp1-iad.github.net (Postfix) with ESMTP id BA21624089F
	for <amol@2jcommerce.in>; Thu, 21 Feb 2019 04:59:04 -0800 (PST)
Date: Thu, 21 Feb 2019 12:59:04 +0000 (UTC)

**Comment by dipti2jcommerce** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dipti@twojay.in
    Domain 2jcommerce.in has exceeded the max emails per hour (250/250 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o10.sgmail.github.com ([167.89.101.201]:45038)
	by mail.2jcommerce.co.uk with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-73f1-dipti=2jcommerce.in@sgmail.github.com>)
	id 1gwnx5-000Azs-3J
	for dipti@2jcommerce.in; Thu, 21 Feb 2019 12:59:47 +0000
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=l3uIzmzmFYvbc/5frXwvfU78mM4=; b=fiITTfGqrw9klkwH
	HR/x6IfpkTaoj0prnA05lZYgM/ARKBYuVtJJdg5Tg70ixwI8uP4J1fWuYh/GIwFU
	ZmtWqJiAovMQ9Pw5BBgzf2XBrePGIXNd7mlQEEaYQlNH6pvmPgoUW6N6cohvSV7F
	hVJr9KNpKxFBrE0mfYgbNu/LgGc=
Received: by filter0130p1iad2.sendgrid.net with SMTP id filter0130p1iad2-20608-5C6EA098-28
        2019-02-21 12:59:04.867892011 +0000 UTC m=+1355739.180095097
Received: from github-lowworker-dcd58f3.cp1-iad.github.net (unknown [192.30.252.33])
	by ismtpd0012p1iad1.sendgrid.net (SG) with ESMTP id QB0rv6k-S1yEmINsd68ZaA
	for <dipti@2jcommerce.in>; Thu, 21 Feb 2019 12:59:04.799 +0000 (UTC)
Received: from github.com (localhost [127.0.0.1])
	by github-lowworker-dcd58f3.cp1-iad.github.net (Postfix) with ESMTP id C1A0324089F
	for <dipti@2jcommerce.in>; Thu, 21 Feb 2019 04:59:04 -0800 (PST)
Date: Thu, 21 Feb 2019 12:59:04 +0000 (UTC)

**Pull request closed without merging**
