### PR TITLE
Customer-data is not updates after login when full page cache disabled

### PR DESCRIPTION
**Pull request by ihor-sviziev**
If you disable full page cache (tested with built-in) - after login 
### Preconditions
1. Magento 2.1.1
2. Full page cache is in "Disabled" state (via php bin/magento cache:disable full_page)
3. Google Chrome latest
### Steps to reproduce
1. Go to magento website
2. Try to login
3. See welcome message
### Expected result
1. Welcome message should be "Welcome, <username>!"
2. Customer data should contains customer information
### Actual result
1. Welcome message is "Default welcome msg!"
   image
2. Customer data isn't contains customer information

### CODE REVIEW

**Comment by erikhansen** [comment]
I just tested @ihor-sviziev's patch and I can verify that it fixed the described issue. Although I did not test to ensure there are no unintended consequences.

**Comment by JstrzAtW2M** [comment]
Have you been able to get this to work with you start with nothing in local storage? It seems like just removing the check for private_content_version would work all the time

**Comment by ihor-sviziev** [comment]
@jstrez77 yes, as I remember I had this issue even iin incognito mode

**Comment by ihor-sviziev** [comment]
Any updates?

**Comment by vrann** [comment]
Hi, @ihor-sviziev, thank you for the contribution.
I was not able to reproduce it for the latest develop branch. Does it exists only in 2.1?
If so, please create pull request against 2.1-develop branch instead.

**Comment by ihor-sviziev** [comment]
@vrann I found that this issue was fixed in develop branch inside https://github.com/magento/magento2/issues/4170, however it wasn't ported to 2.1.


take a look on these commits: https://github.com/magento/magento2/commit/861f596371825d9e24672cd613229ae9486c635f https://github.com/magento/magento2/commit/9efb5ad263fe07204a1c5b21afdeda012b0b1b3d

**I don't think that it's a good idea to set up the private version cookie even if built in full page cache is disabled.**

My fix fixing the same issue even when private version cookie is not set (in case when built in full page cache disabled).

I see there two options:
1. revert commits https://github.com/magento/magento2/commit/861f596371825d9e24672cd613229ae9486c635f https://github.com/magento/magento2/commit/9efb5ad263fe07204a1c5b21afdeda012b0b1b3d and apply my changes
2. Prepare backport pull request with changes from these two commits

I can update pull request according to your chose . What do you think?

**Comment by vrann** [comment]
@ihor-sviziev reviewed commits and I see that the VarnishPlugin was not changed so presumably has the same issue as the BuiltinPlugin.

Plan 1 makes sense:
1. as a part of PR to develop revert commits 861f596 9efb5ad and apply your changes changes
2. create PR to 2.1-develop with the backport

**Comment by ihor-sviziev** [comment]
@vrann I updated my pull request. Could you review it and if it ok - i'll create backport PR  to 2.1-develop branch based on this one.

**Comment by vrann** [comment]
@ihor-sviziev thank you.

Testing this PR, doesn't seem like working at the moment:
screen shot 2017-05-23 at 6 24 54 pm

Does it work for you? Do you know where the prolem could be?

**Comment by ihor-sviziev** [comment]
It worked for me. I will check it again and provide you an answer

**Comment by ihor-sviziev** [comment]
Hi @vrann I just checked, it works good for me.
After logging it executes following code:
image

And if few seconds we have following result:
image

**Comment by vrann** [comment]
@ihor-sviziev sorry, forgot to mention, I deleted ``private_content_version`` cookie first, then logged in. Please see screenshot above, the cookie is not set and the message says "Default.."

**Comment by ihor-sviziev** [comment]
@vrann looks like my fix isn't cover all cases. Will test it more carefully and provide you an update. For now I'm closing this PR.

**Pull request closed without merging**
