### PR TITLE
Add escapeQuote and fix error on js addGroup function

### PR DESCRIPTION
**Pull request by Imaginaerum**
Add escapeQuote and fix error on js addGroup function.

### CODE REVIEW

**Comment by vkublytskyi** [comment]
@Imaginaerum, thank you for contribution.

Please note that your fix removes translation. Even if these strings are translated later by JavaScript we can not remove PHP translation now as this will be breaking incompatible change.

Also for escaping inside JavaScript strings `escapeJsQuote` instead of `escapeQuote` should be used.

So the correct code will be:
`'<?php /* @escapeNotVerified */ echo $block->escapeJsQuote(__('...')) ?>'`

Please correct your code and we will merge PR

**Comment by Imaginaerum** [comment]
@vkublytskyi thanks for your reply.

I change my code.

**Comment by vrann** [comment]
@Imaginaerum please sync the PR with the latest develop branch.

**Comment by vrann** [comment]
@Imaginaerum also, ``escapeJsQuote`` method was deprecated. Please use ``escapeJs`` method instead.
Doing so, please remove `` /* @escapeNotVerified */`` comment next to the method call. It is needed to highlight unescaped string to static tests, which will not be the case anymore.

**Comment by vrann** [comment]
@Imaginaerum please feel free to re-open PR once the changes are made.

**Pull request closed without merging**
