### PR TITLE
Replaced all escape functions from $block object to $escaper object as a part of Magento coding standards.

### PR DESCRIPTION
**Pull request by sanganinamrata**
### Description (*)

Replaced all escape functions from `$block` object to `$escaper` object as a part of Magento coding standards.

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @sanganinamrata. Thank you for the refactoring. I believe it would be a good idea if we perform the replacement everywhere in the system and not only in particular modules. What do you think about that?

**Comment by sanganinamrata** [comment]
Sure @rogyar,

Right now I've covered blank and luma themes, but I'll cover Magento individual modules as well in 2-3 days.

**Comment by hostep** [comment]
@rogyar:
> Hi @sanganinamrata. Thank you for the refactoring. I believe it would be a good idea if we perform the replacement everywhere in the system and not only in particular modules. What do you think about that?

I really don't like this to happen in minor releases (2.4.2 for example), it generates a lot of changes in frontend code which causes a whole lot of unnecessary noise when reviewing such an update and extra work when you need to upgrade to a new minor release and adjust your own custom frontend theme to follow the new changes. I prefer if big changes in hundreds or thousands of different phtml files only happen in major releases (like 2.5.0).

(This comment is irrelevant if only 10 or 20 files will be affected, but please if this affects more then 20 files, consider to only ship this in Magento 2.5.0)

----

The same thing happened in Magento 2.3.3, where a bunch of new coding standards got applied to all the phtml files and it caused just soo much overhead and extra work, I really like to not have this happen in minor releases in the future any longer, because it makes upgrades to a minor release really expensive, we should try to make minor releases easy and effortless so people will actually want to invest the time to upgrade to them.

Thanks for considering this! :)

**Comment by ihor-sviziev** [comment]
Hi @rogyar,
I do agree with @hostep - in case if all the files will be refactored at once - please postpone these changes to 2.5.
Such consistency cleanups are very welcomed in case if someone will fix some issue in the file, but cleanup all together should be not in a patch versions.

**Comment by sanganinamrata** [comment]
Hi @ihor-sviziev,

So Should I update this PR affected changes to Magento core modules as requested by @rogyar at https://github.com/magento/magento2/pull/30639#pullrequestreview-516268405 ?

**Comment by ihor-sviziev** [comment]
I don't mind.
@rogyar what do you think?

**Comment by hostep** [comment]
It can probably be done, but just make sure the PR is **not** merged in `2.4-develop`, we should wait until `2.5-develop` becomes available before merging.

**Comment by sanganinamrata** [comment]
@hostep Sure, I would love to do that.

**Comment by rogyar** [comment]
@hostep @ihor-sviziev totally agree.
@sanganinamrata I would suggest closing this PR and creating a new one with all the replacements once we have `2.5-develop` branch created. 

Thanks

**Comment by hostep** [comment]
Hi @sanganinamrata: Since the [2.5-develop branch](https://github.com/magento/magento2/tree/2.5-develop) is now open, could you change the target branch of this PR to `2.5-develop` (or open a new PR targeting that branch if that's easier) and then try to update all offending code in the Magento codebase?
Thanks!

**Comment by ihor-sviziev** [comment]
Hi @sanganinamrata,
We have a PR that already targeted to 2.5-develop https://github.com/magento/magento2/pull/31663 that doing the same.
I'm closing this PR.

**Pull request closed without merging**
