### PR TITLE
Fix incorrect empty cart button behavior

### PR DESCRIPTION
**Pull request by wojtekn**
### Description

PR changes order of cart form submit elements to have Update Shopping Cart first in the DOM, to make sure it is used as submit button when Enter key is pressed. There is also change to the theme styling to adjust Clear Shopping Cart position after changing buttons order.

### Fixed Issues

1. magento/magento2#21499

### Manual testing scenarios

1. Add any product to cart
2. Navigate to the cart
3. Un-hide "Clear Shopping Cart" button which is hidden in Luma by default by running this in browser console:
  `jQuery("#empty_cart_button").show();`
4. Change item quantity in the input
5. Press "Enter"

Expected result is to have product quantity updated.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @wojtekn. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21500) <br/>All committers have signed the CLA.

**Comment by wojtekn** [comment]
* @magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @wojtekn. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @wojtekn, here is your [new Magento instance](https://pr-21500.instances.magento-community.engineering).
Admin access: [https://pr-21500.instances.magento-community.engineering/admin](https://pr-21500.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by wojtekn** [comment]
I can't reproduce problem anymore on provided test instance.

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-21500.instances.magento-community.engineering).
Admin access: [https://pr-21500.instances.magento-community.engineering/admin](https://pr-21500.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4396](https://jira.corp.magento.com/browse/ENGCOM-4396) has been created to process this Pull Request

**Comment by VladimirZaets** [comment]
Hi @wojtekn. Thanks for collaboration. We have another [PR](https://github.com/magento/magento2/pull/21509) that resolve the same issue. 
According to fix, we prefer that PR because that PR resolve the problem in JS code that gives more flexibility and scalability.
Thank for your work.

**Pull request closed without merging**
