### PR TITLE
Removed double occurrence of  keywords from sentences.

### PR DESCRIPTION
**Pull request by sanganinamrata**
### Description

Removed double occurrence of keywords "to, the" from sentences.

### Fixed Issues (if relevant)

N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @NamrataChangani. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on Pull Request changes
- `@magento-engcom-team give me new test instance` - deploy **NEW** test instance based on Pull Request changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy Vanilla Magento instance for Issue or Pull Request

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by orlangur — APPROVED** [review]
Nice! @NamrataChangani how did you find these occurrences? Is there some automation for spellchecking available probably? :)

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-2018](https://jira.corp.magento.com/browse/ENGCOM-2018) has been created to process this Pull Request

**Comment by sanganinamrata** [comment]
@orlangur  Hello,

While working with theme/module, I saw some double occurrence of the same keywords, So I find in the whole directory for the same double occurrence(Using PhpStorm), and replaced it with a single occurrence where necessary.

Thank you :)

**Comment by magento-engcom-team** [comment]
Hi @NamrataChangani. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.6 release.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
