### PR TITLE
Replaced deprecated methods.

### PR DESCRIPTION
**Pull request by tiagosampaio**
Replaced deprecated methods.

### Description
Replaced deprecated methods below:
 - addSuccess() by addSuccessMessage()
 - addException() by addExceptionMessage()
 - addError() by addErrorMessage()

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @tiagosampaio. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by ihor-sviziev** [comment]
@magento-engcom-team combine 17036 17039 17048 17058

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on combining the pull requests for you

**Comment by magento-engcom-team** [comment]
@tiagosampaio all pull requests have been successfully combined together: 
 - merged https://github.com/magento/magento2/pull/17036: Replaced deprecated methods for AdvancedPricingImportExport module.
 - merged https://github.com/magento/magento2/pull/17039: Replacing deprecated methods to Magento_Backend.
 - merged https://github.com/magento/magento2/pull/17048: Replacing deprecated methods in Magento_Backup module.
 - merged https://github.com/magento/magento2/pull/17058: Replacing deprecated methods in Magento_CatalogRule module.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi,

I merged 5 PRs into single one in order to process them faster.

I see two builds on PRs were failing. Could you review the builds and adjust your code?
Links to failed builds:
- https://github.com/magento/magento2/pull/17039 - https://travis-ci.org/magento/magento2/builds/407247207
- https://github.com/magento/magento2/pull/17035 - https://travis-ci.org/magento/magento2/jobs/407202442

**Comment by tiagosampaio** [comment]
Hi @ihor-sviziev,

Changes were applied.

Thanks.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi,
Integration tests are failing. Could you fix your code  or adjust tests if needed?

**Comment by ihor-sviziev** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, here is your [new Magento instance](https://pr-17035.engcom.dev.magento.com).
Admin access: [https://pr-17035.engcom.dev.magento.com/admin](https://pr-17035.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`

**Comment by ihor-sviziev** [comment]
I checked following test cases manually:
1. Mass action "refresh" for not existing cache type 👍 
2. Mass action "disable" for not existing cache type 👍 
3. Mass action "enable" for not existing cache type 👍 
image

Looks like on UI everything is good, need just update integration tests assert.
@tiagosampaio  could you do that?

---
**Edit:** Never mind, I'll fix it myself

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-2553](https://jira.corp.magento.com/browse/ENGCOM-2553) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @tiagosampaio. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.6. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
