### PR TITLE
Fixed Model box overlapping issue 

### PR DESCRIPTION
**Pull request by abrarpathan19**
### Description (*)

1. Model box popup text overlapping on the close icon 
2. Reproduce on 2.3

### Fixed Issues (if relevant)

This is the Direct PR owing to small design change.

### Manual testing scenarios (*)

1. Admin - Catalog - category - click on  "All Store Views" dropdown select "Default Store View"
2. Then you can view the Model box popup 
3. Actual result: http://prntscr.com/ml2grg
4. Expected result: http://prntscr.com/ml2g2j

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @abrarpathan19. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by Karlasa** [comment]
@abrarpathan19 
duplicated issues #21075 
I would suggest that issue is more related to that it's missing title. 
Could you provide bit better solution to increase UX :)

**Comment by sidolov** [comment]
@abrarpathan19 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by abrarpathan19** [comment]
@sidolov Thank you !!!

**Pull request closed without merging**
