### PR TITLE
[Fixed] Checkout Section: Shipping step is getting skipped when customer hitting direct payment step URL

### PR DESCRIPTION
**Pull request by niravkrish**
### Description (*)

Checkout Section: Shipping step is getting skipped when customer hitting direct payment step URL

### Fixed Issues (if relevant)

1. magento/magento2#21596: Checkout Section: Shipping step is getting skipped when customer hitting direct payment step URL

### Manual testing scenarios (*)

1. Product Add To Cart and go to checkout page
2. hit payment url without adding shipping address

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @niravkrish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by cscd98** [comment]
Please merge this :+1:

**Comment by omiroshnichenko** [comment]
Hi @niravkrish, current solution is too fragile. If someone will create required custom customer address attributes this fix will not work. Additionally, it may cause unexpected behavior.

Feel free to create another PR or reopen this one with a more stable approach.

**Comment by niravkrish** [comment]
Hello @omiroshnichenko,

I got only fields with value in quote. and not getting something like shipping address is blank and valid or not.
If Customer or developer create custom shipping address attribute. then he should be required to validate that field also.

Thanks
Nirav Patel

**Comment by sidolov** [comment]
Hi @niravkrish , Magento Commerce edition contains functionality that provides an ability to add custom address attributes on the backend. With provided solution this functionality is broken. 
Anyway, hardcoded attribute names in the code is not a good idea because it's hard to extend and modify such component and this approach goes against out Technical Guidelines.

**Review by sidolov — CHANGES_REQUESTED** [review]
Please, provide another solution for the issue.

**Comment by sidolov** [comment]
@niravkrish , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
