### PR TITLE
Remove @author annotation from Magento framework

### PR DESCRIPTION
**Pull request by diazwatson**
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Hi @diazwatson! Thanks for this contribution. Please address static build failures.
Magento health index failure is not related to your changes. We are investigating it internally.

**Review by lenaorobei — APPROVED** [review]
Functional failures not related to the changes.

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-7066](https://jira.corp.magento.com/browse/ENGCOM-7066) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
