### PR TITLE
26343 : Bundle product options deleted incorrectly

### PR DESCRIPTION
**Pull request by sunilit42**
Fix issue :- https://github.com/magento/magento2/issues/30347

### CODE REVIEW

**Comment by vijay-wagento** [comment]
#dmcdindia2020

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @sunilit42. Thank you for your contribution. According to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered by autotests. Could I ask you to cover your changes with an MFTF test, please?

Thank you!

**Comment by sunilit42** [comment]
@magento run all tests

**Comment by sunilit42** [comment]
@rogyar  
one of biggest issue

e.g let's example if you assign 10 pages options and you want to delete one option from middle of page then from that page all options remove

**Comment by sunilit42** [comment]
@rogyar  any update?

**Comment by rogyar** [comment]
Hi @sunilit42. That totally makes sense. We are still waiting for the autotests from your end. Please, check [my comment](https://github.com/magento/magento2/pull/30418#pullrequestreview-506098482) above.

Thanks.

**Comment by sunilit42** [comment]
@rogyar 
Could I ask you to cover your changes with an MFTF test, please? : can you please help on this, i m not sure what i need to here

**Comment by sunilit42** [comment]
@rogyar test case fail into B2B and EE version

**Comment by sunilit42** [comment]
@rogyar https://i.imgur.com/eKDEyyv.png already test case there

**Comment by rogyar** [comment]
Hi @sunilit42. The test case you've mentioned looks related. However, it's green even without the fix. It means that this test does not cover the case fixed in this PR. Your fix needs to be covered with a similar test case that will go through steps to reproduce from the [original issue](https://github.com/magento/magento2/issues/30347) and assert that there's no issue after the fix. 

Hope it will help.

**Comment by sunilit42** [comment]
@rogyar  i ill try but not sure i will do it or not

**Comment by rogyar** [comment]
> In test case may be work because delete is working but some js error showing into console, due to this js error all options after that removed so.
I see the point. So we need to create a test that will do the following:

- Create a bundle product
- Add more than 20 product options (important for getting multiple pages)
- Add one product to each option (choose random simple product from sample data)
- Save the bundle product
- Go to the second page of bundle options
- Click on the remove icon for removing the product of the option
- Click on the remove icon of the option itself
- Save the product
- Check that **only one** option is deleted

We still don't have test coverage for the described scenario. 

Hope it will help

**Comment by aredridel** [comment]
@rogyar  You probably meant to tag someone else, I'm not involved in this PR.

**Comment by sunilit42** [comment]
Hello @rogyar 

Thanks for your reply 

I did not created test case but i will try it, but if created such a case for each and every thing how many test case will be there

so bettert to check with manually

**Comment by engcom-Charlie** [comment]
Hello @sunilit42, thank you for your contribution.
Due to [Magento Definition of Done](https://devdocs.magento.com/contributor-guide/contributing_dod.html) the changes should be covered by tests.
Could you please cover your fix by an automated test? 
Thank you.

**Comment by engcom-Charlie** [comment]
Hello @sunilit42, please look at failed tests and cover your changes by an automated test. Otherwise, we can't proceed with your PR.
Thank you.

**Comment by sunilit42** [comment]
@engcom-Charlie it is b2b test case, how i do b2b test case?

**Comment by engcom-Charlie** [comment]
@sunilit42 looks like the issue is reproducible on CE version so you can add test coverage to your PR.
Thank you.

**Comment by engcom-Charlie** [comment]
Hello @sunilit42, please cover your changes by an automated test. Otherwise, we can't proceed with your PR.
Thank you.

**Comment by engcom-Delta** [comment]
@sunilit42 I will take care of test coverage

**Comment by sunilit42** [comment]
@engcom-Delta Thanks

**Pull request closed without merging**
