### PR TITLE
[Backport] Fixed an issue where Quantity column of admin product listing grid is always displaying "In Stock" value

### PR DESCRIPTION
**Pull request by XxXgeoXxX**
Original PR: https://github.com/magento/magento2/pull/19077

#### Preconditions
Magento 2.2.4

#### Steps to reproduce
Go to Magento 2 admin => Stores => Attributes => Product => Search attribute code "quantity_and_stock_status".
Change "Advanced Attribute Properties" settings Scope => "Store view/Global", "Add to Column Options" to "Yes" and set "Use in Filter Options" to "Yes".
Now product attribute Quantity(quantity_and_stock_status) will be visible in to the catalog product settings Columns section and checked it to yes.
Make Product "Out of Stock" and Save it Flush/Refresh the Cache And also re-indexing it.
Check quantity_and_stock_status display result in product Grid and edit this product and check stock status.
#### Expected result
quantity_and_stock_status display result "Out of stock" if product is Stock status "Out of stock" in product Grid.

#### Steps to reproduce
1. Go to Magento 2 admin => Stores => Attributes => Product => Search attribute code "quantity_and_stock_status".
2. Change "Advanced Attribute Properties" settings Scope => "Store view/Global", "Add to Column Options" to "Yes" and set "Use in Filter Options" to "Yes".
3. Now product attribute Quantity(quantity_and_stock_status) will be visible in to the catalog product settings Columns section and checked it to yes.
4. Make Product "Out of Stock" and Save it Flush/Refresh the Cache And also re-indexing it.
5. Check quantity_and_stock_status display result in product Grid and edit this product and check stock status.

### Fixed issue
added column "Stock Status" which collect data about product status

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
Thanks for your contribution, @XxXgeoXxX . According to our policy this change should be first introduced to 2.3-develop branch (see the [rules](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#rules) section of the contributor guide for more details).

Please port the pull request to 2.3-develop branch (see the [porting](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting) section of the contributor guide for more details).

Also, please avoid "@api" annotation, as API should not actually be introduced in patch releases.

**Comment by XxXgeoXxX** [comment]
Hi, @sivaschenko , thank you for for your commit and comment. I ported the pull request to 2.3-develop branch. And I' m working on resolving errors in test now.

**Comment by sivaschenko** [comment]
@XxXgeoXxX thank you! As I can see there is simply one small issue with the method signature, please let me know if you need a hand on it.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19017) <br/>All committers have signed the CLA.

**Comment by XxXgeoXxX** [comment]
merge conflict was resolved

**Comment by to8gal** [comment]
Hello,  I have an issue where in layered navigation the same attribute generate really non sense results, so to filter product in stock will always give a strange array of result,

is this solution gonna help layered navigation as well?

thanks

L

**Comment by XxXgeoXxX** [comment]
Hi, @to8gal 
This solution only related to show correct data in admin grid. Quantity_and_stock_statust attribute is only key for array where product storeged data. And that why for use  correct this attribute in Layer navigation you need write custom model/plugin where you will update condition to collection.

**Comment by VladimirZaets** [comment]
Hi @XxXgeoXxX . The branch `2.2-develop` will be closed for contribution from **July 15, 2019**. Please finish all your Pull Requests till this date, otherwise, they will be closed.
Thanks for collaboration.

**Comment by orlangur** [comment]
Closing as 2.3 PR is still not merged.

**Pull request closed without merging**
