### PR TITLE
#26314: fixed logic for updating map price for selected swatch

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Fixed logic for updating map price for selected swatch option on product list

### Fixed Issues
1. #26314 

### Manual testing scenarios
1. Enable MAP (Stores -> Configuration -> Sales -> Sales -> Minimum Advertised Price -> Enable MAP).
1. Enable 'Show Swatches in Product List', enabled by default (Stores -> Configuration -> Catalog -> Catalog -> Storefront -> Show Swatches in Product List).
1. The product attribute uses for configurable products should be visible on Product List (Stores -> Attributes -> Product -> select attribute -> Storefront Properties -> Used in Product Listing) in order to show attribute swatches for Product List.
1. Create few configurable products for the attribute with 'swatch' (Visual Swatch, Text Swatch) type with associated products:
   - Configurable A:
      - Black A: price 1, MAP 11. (ex: 'black' color)
      - White A: price 2, MAP 12. (ex: 'white' color)
   - Configurable B:
      - Black B: price 10, MAP 110. (ex: 'black' color)
      - White B: price 20, MAP 120. (ex: 'white' color)
1. Create category, assign created products.
Expected result

### Questions or comments
Better to test once the changes from the #26240 will be merged.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello @sergiy-v, could you please check the failing unit test `tests/js/jasmine/tests/app/code/Magento/Msrp/frontend/js/msrp.test.js`?
Thank you! :)

**Comment by sergiy-v** [comment]
> Hello @sergiy-v, could you please check the failing unit test `tests/js/jasmine/tests/app/code/Magento/Msrp/frontend/js/msrp.test.js`?
> Thank you! :)

Hello @dmytro-ch, I'll check it, thank you!

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6685](https://jira.corp.magento.com/browse/ENGCOM-6685) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @sergiy-v,

During testing, we faced the issue

**_Problem:_** The minimum advertised price does not change after the swatches have been selected

**Manual testing scenario:**

1.  Enable MAP (Stores -> Configuration -> Sales -> Sales -> Minimum Advertised Price -> Enable MAP).
2.  Enable 'Show Swatches in Product List', enabled by default (Stores -> Configuration -> Catalog -> Catalog -> Storefront -> Show Swatches in Product List).
3.  The product attribute uses for configurable products should be visible on Product List (Stores -> Attributes -> Product -> select attribute -> Storefront Properties -> Used in Product Listing) in order to show attribute swatches for Product List.
4.  Create few configurable products for the attribute with 'swatch' (Visual Swatch, Text Swatch) type with associated products and assign created products to category :
     Configurable A:
Black A: price 1, MAP 11. (ex: 'black' color)
White A: price 2, MAP 12. (ex: 'white' color)
     Configurable B:
Black B: price 10, MAP 110. (ex: 'black' color)
White B: price 20, MAP 120. (ex: 'white' color)

**Actual Result:**
When we switch between swatches, MAP should change too
after

@sergiy-v Could you take a look?

Thanks!

**Comment by sergiy-v** [comment]
Hello @engcom-Alfa,
I'm sorry for that. Unfortunately we have related bug here as I mentioned in the 'Questions or comments' section.
> Better to test once the changes from the #26240 will be merged.

As I see from your testing results the prices are not duplicates anymore because of fix from the current PR.
But the prices are incorrect because of the #26240 and fixed in scope of #26241
@engcom-Alfa could you please to check the final result once the changes from the #26241 will be merged?

Thank you.

**Comment by engcom-Alfa** [comment]
@sergiy-v Thank you for your clarification. Sorry for the inattention.

We will check this PR changes immediately after the [#26241](https://github.com/magento/magento2/pull/26241) will be merged.

Thank you!

**Comment by sergiy-v** [comment]
> @sergiy-v Thank you for your clarification. Sorry for the inattention.
> 
> We will check this PR changes immediately after the [#26241](https://github.com/magento/magento2/pull/26241) will be merged.
> 
> Thank you!

Hello @engcom-Alfa,
FYI, the changes from the #26241 has been merged.

Thank you!

**Comment by engcom-Alfa** [comment]
Hi @dmytro-ch. Could you review the latest changes? Thanks!

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6685](https://jira.corp.magento.com/browse/ENGCOM-6685) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @sergiy-v.
The issue described in my [comment](https://github.com/magento/magento2/pull/26317#issuecomment-578653539) can still be reproduced with PR changes

**Actual Result:**
after3

And the problem #26240   that has been resolved in #26241  is returned

**Actual Result:**
after4

@sergiy-v Could you take a look?

Thanks!

**Comment by sergiy-v** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sergiy-v. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sergiy-v, here is your [new Magento instance](https://pr-26317.instances.magento-community.engineering).
Admin access: [https://pr-26317.instances.magento-community.engineering/admin_ad24](https://pr-26317.instances.magento-community.engineering/admin_ad24)
Login: `ea183482` Password: `b85c18f4d7d2`
Instance will be terminated in up to 3 hours.

**Comment by sergiy-v** [comment]
> Hi @sergiy-v.
> The issue described in my [comment](https://github.com/magento/magento2/pull/26317#issuecomment-578653539) can still be reproduced with PR changes
> 
> **Actual Result:**
> after3
> 
> And the problem #26240 that has been resolved in #26241 is returned
> 
> **Actual Result:**
> after4
> 
> @sergiy-v Could you take a look?
> 
> Thanks!

Hello @engcom-Alfa,
The changes works fine on my the local environment and created test environment (see credentials above). Maybe I missed something.
Could you please check it one more time?

Thank you.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Actual Result:**
screen222

**Pull request merged**
