### PR TITLE
[Backport : Changed password placeholder text in checkout page]

### PR DESCRIPTION
**Pull request by hitesh-wagento**
### Description
Summary of the issue: Wrong placeholder for password field in the checkout page

### Fixed Issues (if relevant)

1. magento/magento2https://github.com/magento/magento2/issues/16378: Wrong placeholder for password field in the checkout page

### Steps to reproduce
1. Add a product to cart and go to checkout page.
2. Enter any registered email so that the password field appears. 
3. The password field shows the placeholder **Optional**, but when we click on Login button without filling password, it shows the validation error.

### Actual result
1. The password field in the checkout page is currently seeming conflicting in nature. It is showing Optional in a placeholder, but after validation, it is showing validation error **This is a required field.**

validation-password

### Expected result
1. Since the password is a required field, the placeholder for the password field should not be **Optional**.
screenshot-127 0 0 1-2018-06-25-17-44-21

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### Original PR 
https://github.com/magento/magento2/pull/16379

### CODE REVIEW

**Comment by miguelbalparda** [comment]
Can you please add the CSV translation and use the same string you used in the original PR? Password instead of password.

**Comment by hitesh-wagento** [comment]
Hi @miguelbalparda

I have added  CSV translation and changed Password instead of password.

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-2306](https://jira.corp.magento.com/browse/ENGCOM-2306) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @hitesh-wagento. Thank you for your contribution. 
We will aim to release these changes as part of 2.1.15. 
Please check the release notes for final confirmation.

**Pull request merged**
