### PR TITLE
added ext-json as requirements of project to composer

### LINKED ISSUE #29944: [Issue] added ext-json as requirements of project to composer
This issue is automatically created based on existing pull request: magento/magento2#29024: added ext-json as requirements of project to composer

---------
### Description (*)
we use `json_*` functions in this project but we miss add this dependency in composer

### Related Pull Requests
none

### Fixed Issues (if relevant)
none

### Manual testing scenarios (*)
not necessary, if CI passes this code is good, it's only technical improvement.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by rvitaliy**
### Description (*)
we use `json_*` functions in this project but we miss add this dependency in composer

### Related Pull Requests
none

### Fixed Issues (if relevant)
none

### Manual testing scenarios (*)
not necessary, if CI passes this code is good, it's only technical improvement.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29944: added ext-json as requirements of project to composer

### CODE REVIEW

**Comment by rvitaliy** [comment]
@magento run all tests

**Comment by rogyar** [comment]
It's required by other packages, but I guess it's a good idea to highlight it in the root config. 
Also, I would add it on the framework level since `json_encode` and other functions are in active use there. What do you think? 

https://github.com/magento/magento2/blob/c45cd925c60cd3d694bc8afe532b6e6e9a096309/lib/internal/Magento/Framework/composer.json#L12

**Comment by sidolov** [comment]
@magento create issue

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @rvitaliy,
Could you also add such dependency to framework, as requested earlier in https://github.com/magento/magento2/pull/29024#issuecomment-655454728?

**Comment by engcom-Golf** [comment]
Hi @rvitaliy, would you be able to proceed with the required changes in this PR? Also could you please update the branch with the latest changes and resolve conflicts?

**Comment by sidolov** [comment]
@rvitaliy  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
