### PR TITLE
Log InvalidRequestException from FrontController validation failure to debug log

### PR DESCRIPTION
**Pull request by marcusirgens**
### Description (*)
Logs the exception that occurs when the FrontController validation fails.

### Manual testing scenarios (*)
Invoke any controller that causes request valiation to fail. Observe debug logs.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rodrigowebjump — APPROVED** [review]
Hi @marcusirgens 

Thanks for your contribution.

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-6289](https://jira.corp.magento.com/browse/ENGCOM-6289) has been created to process this Pull Request
:eight_spoked_asterisk: @rodrigowebjump, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@marcusirgens thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

**Before:**
before

**After:**
after

**Comment by VladimirZaets** [comment]
Covered by automated tests in the scope of PR https://github.com/magento/magento2/pull/25704

**Pull request merged**
