### PR TITLE
Fix disappearing navigation arrows in fotorama zoom

### PR DESCRIPTION
**Pull request by luukschakenraad**
### Description (*)
Fix for dissapearing navigation arrows in Fotorama zoom

### Fixed Issues (if relevant)
magento/magento2#18585: Navigation arrows zoomed fotorama disappear

### Manual testing scenarios (*)
1. Go to category Women -> Tops -> Jackets
2. Open product "Olivia 1/4 Zip Light Jacket"
3. Click on the large product image on the left
4. Check that navigation arrows are visible
5. Click on a thumbnail
6. Check that navigation arrows keep visible

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18590) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @luukschakenraad. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by hostep** [comment]
I might be wrong about this, but it could be that this is trying to fix the same issue as https://github.com/magento/magento2/pull/18440 is trying to fix (but that one is for a lot more options of fotorama)

**Comment by luukschakenraad** [comment]
> I might be wrong about this, but it could be that this is trying to fix the same issue as #18443 is trying to fix (but that one is for a lot more options of fotorama)

That one seems to be unrelated to this issue. This one has nothing to do with any settings. It's just a bug in Fotorama which causes wrong behaviour of the previous and next buttons.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3198](https://jira.corp.magento.com/browse/ENGCOM-3198) has been created to process this Pull Request

**Comment by sidolov** [comment]
Hi @luukschakenraad , we cannot reproduce this issue on the vanilla 2.3-develop instance. 
We can confirm that issue was reproduced on the 2.2-develop branch and we merged corresponded PR: https://github.com/magento/magento2/pull/18595
Maybe you have additional steps for reproducing on the 2.3-develop? 
Thank you!

**Comment by luukschakenraad** [comment]
@sidolov I think you cannot reproduce it because of this commit: https://github.com/magento/magento2/commit/163d4cc63d19c3a3bd94697dd02c0d96696df799#diff-49a84585354f5715382cc2b014a3d961

That one changes the value of "arrows" from "1" to "true" which is another way to solve this issue.

Even with that fix already applied, I think it's a good idea to implement this fix, as it is also in Fotorama's source-code: https://github.com/artpolikarpov/fotorama/blob/master/src/js/fotorama.js#L273

Secondly, these two fixes won't conflict and this one solves overridden templates as well.

**Comment by magento-engcom-team** [comment]
Hi @luukschakenraad. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
