### PR TITLE
Fixed Catalog Product - Customizable Options label alignment issue

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)

Magento 2.3-develop
Catalog Product - Customizable Options 2nd and third label alignment issue
### Fixed Issues (if relevant)

1. magento/magento2#19492: Catalog Product - Customizable Options label alignment issue
2. ...

### Manual testing scenarios (*)

1.Not Required for designing alignment issue
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19496) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @emiprotech. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
@emiprotech please fix branch history (looks like this one was based on `2.2-develop` while it should on `2.3-develop`).

**Comment by sivaschenko** [comment]
@emiprotech thank you for the contribution! This pull request seems to be a duplicate to https://github.com/magento/magento2/pull/19493 that is already opened for 2.3-develop , if it is, please close it.
cc @speedy008

**Comment by ghost** [comment]
@sivaschenko,
 My changes and exsting pull request changes are different. both changes are working. I am closing this pull request because of code conflicting in my pull request. I have submitted new pull request to resolve confiction issue.

**Pull request closed without merging**
