### PR TITLE
Resolve indexer.xml & mview.xml not allowing numbers in vendor and class name

### PR DESCRIPTION
**Pull request by Jason-Sy**
### Fixed Issues (if relevant)

1. magento/magento2#24323: indexer.xml & mview.xml doesn't allow numbers in vendor name and class name

### Manual testing scenarios (*)

1. Create a simple module with a vendor name which contains at least one number (ex. Mage2Vendor)
2. Add a custom indexer to the module just like on the devdocs
3. setup:upgrade

### Questions or comments

Is based of [#8037](https://github.com/magento/magento2/pull/8307) but added a \ check so it's still possible to start with \. 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24324) <br/>All committers have signed the CLA.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-5724](https://jira.corp.magento.com/browse/ENGCOM-5724) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@Jason-Sy thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
