### PR TITLE
#9139 Unable to set negative product's quantity fixes

### PR DESCRIPTION
**Pull request by poongud**
### Fixed Issues (if relevant)
1. magento/magento2#9139: Unable to set negative product's quantity #9139

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=9678) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=9678) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: poongud<br/>:x: magentoabu

**Comment by avoelkl** [comment]
Hi @poongud, thanks for the Pull Request!
It seems you did not sign the Contributor License Agreement (CLA) yet, can you please do this to continue with this PR?

**Comment by poongud** [comment]
Hi @avoelkl  I have click CLA button and goes to CLA document page from the I click the agree with signup button. But again showing "CLA not signed yet" button.

Kindly advice me.

**Comment by avoelkl** [comment]
Hi @poongud,
You have to ensure that you use the same email addresses set up in local git config and in your github profile. Can you please check and update the email address and try again?

**Comment by poongud** [comment]
HI @avoelkl 

Now I have updated email is into my local systems and anything else want to do ?

**Comment by poongud** [comment]
Hi @avoelkl 

I have this close this Pull Request and create a new Pull Request : https://github.com/magento/magento2/pull/9770

**Comment by avoelkl** [comment]
Thanks for the update @poongud, will have a look at the new PR!

**Pull request closed without merging**
