### PR TITLE
Apply review suggestion to the media modules

### LINKED ISSUE #1725: Apply review suggestion to the media modules
- Remove `Magento\MediaContentSynchronizationApi\Api\SynchronizerInterface`
 - Remove try-catch block from \Magento\MediaGalleryMetadata\Model\File\ExtractMetadata::extractMetadata
 - Remove `GetContentHashInterface`
 - Remove DI configuration of `Magento\MediaGalleryUi\Ui\Component\Listing\Filters\Options\UsedIn`

### PR DESCRIPTION
**Pull request by sivaschenko**
### Description (*)
Removed Magento\MediaContentSynchronizationApi\Api\SynchronizerInterface
Removed try-catch block from \Magento\MediaGalleryMetadata\Model\File\ExtractMetadata::extractMetadata
Removed GetContentHashInterface
Removed DI configuration of Magento\MediaGalleryUi\Ui\Component\Listing\Filters\Options\UsedIn

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/adobe-stock-integration/issues/1725

### Preconditions
1. Enable Enhanced Media Gallery in Stores -> Configuration -> System -> Advanced
2. Several images are added from media gallery to Page, Product, Category, Block entities

### Testing (*)
1. Should be verified in two instances of media gallery: `Content -> Media Gallery`, Media Gallery opened from any wysiwyg
2. Verify Used in filter functionality
3. Verify Uploading the save image under a different name, saving image from AdobeStock twice (possible after removing the db record from `adobe_stock_asset` table) and applying Duplicates filter
4. Verify `media-content:sync` command

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sivaschenko** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]
Hi @sivaschenko, thanks for the pull request. The changes are approved.

**Comment by sivaschenko** [comment]
Changed functionality areas are covered by MFTF tests

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

Tested the following functionality:
- Added images from media gallery to Page, Product, Category, Block entities
- opened Media Gallery from `Content -> Media Gallery` 
- opened Media Gallery  from any wysiwyg
- work of Used in filter functionality
- uploading the save image under a different name 
- saving image from AdobeStock twice 
- work of 'Show Duplicates' filter
- media-content synchronization

All the changes are covered with Manual Testing Scenarios

**Comment by sivaschenko** [comment]
@magento run Unit Tests

**Pull request merged**
