### PR TITLE
Spelling mistake in the comment

### PR DESCRIPTION
**Pull request by sudhanshu-bajaj**
### Description (*)

Spelling mistake in the comment
### Fixed Issues (if relevant)

1. Not Applicable 

### Manual testing scenarios (*)

1. Not Applicable

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @sudhanshu-bajaj. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
Hi @sudhanshu-bajaj. Thank you for your contribution. Since September 17, 2018, the code cleanup is not allowed in the 2.2 mainline (https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules)

**Comment by DanielRuf** [comment]
> Hi @sudhanshu-bajaj. Thank you for your contribution. Since September 17, 2018, the code cleanup is not allowed in the 2.2 mainline ([devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules))

Not really code cleanup imo.

**Comment by DanielRuf** [comment]
> Contribution contains code cleanup such as typos, inline documentation, coding style, remove unused code, minor style/design fixes, and so on.

No mention of comments.

**Pull request closed without merging**
