### PR TITLE
[Forwardport]Fix issue 19902 - Store View label and Dropdown misaligned 

### PR DESCRIPTION
**Pull request by SyntaxKay**
### Description (*)

Magento 2.3-Develop
Store View label and Dropdown misaligned
### Fixed Issues (if relevant)

1Store View label and Dropdown misaligned 

### Expected result (*)

1. http://prntscr.com/lxgjmd

### Actual result (*)

1. http://prntscr.com/lxgja4

### Manual testing scenarios (*)

1.N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by osrecio** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @osrecio. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @osrecio, here is your [new Magento instance](https://pr-19904.instances.magento-community.engineering).
Admin access: [https://pr-19904.instances.magento-community.engineering/admin](https://pr-19904.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by osrecio — APPROVED** [review]
Thanks for your contribution @speedy008 .

I checked your PR in Vanilla env and PR env and it works.

**Comment by magento-engcom-team** [comment]
Hi @osrecio, thank you for the review.
[ENGCOM-3726](https://jira.corp.magento.com/browse/ENGCOM-3726) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
