### PR TITLE
Update Api functional test install-config-mysql file template

### LINKED ISSUE #31019: [Issue] Update Api functional test install-config-mysql file template
This issue is automatically created based on existing pull request: magento/magento2#30995: Update Api functional test install-config-mysql file template

---------
Elasticsearch config is required for 2.4 installation

The api functional tests install-config-mysql.php.dist file template is outdated without elasticsearch params which are required for magento installation in 2.4-develop. Added essential es config params
### Description (*)

The magento installation config api functional tests updated with now required elasticsearch parameters from 2.4-develop

### Fixed Issues (if relevant)

1. Fixes the config-mysql template 

### Manual testing scenarios (*)

1. Change this config template to PHP file
2. Run api-functional tests with 'test-magento-installation' option enabled in 2.4-develop branch 

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [X] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by dani97**
Elasticsearch config is required for 2.4 installation

The api functional tests install-config-mysql.php.dist file template is outdated without elasticsearch params which are required for magento installation in 2.4-develop. Added essential es config params
### Description (*)

The magento installation config api functional tests updated with now required elasticsearch parameters from 2.4-develop

### Fixed Issues (if relevant)

1. Fixes the config-mysql template 

### Manual testing scenarios (*)

1. Change this config template to PHP file
2. Run api-functional tests with 'test-magento-installation' option enabled in 2.4-develop branch 

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [X] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31019: Update Api functional test install-config-mysql file template

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8482](https://jira.corp.magento.com/browse/ENGCOM-8482) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Change `install-config-mysql.php.dist` config template to PHP file
2. Run api-functional tests with 'test-magento-installation' option enabled in 2.4-develop branch 
```xml
<const name="TESTS_MAGENTO_INSTALLATION" value="enabled"/>
```

**Actual Result:** :heavy_check_mark: Api-functional tests were successfully run and completed

**Comment by dani97** [comment]
@engcom-Alfa is there anything needed from my side to get this merged also looks like these failures are not because of this PR.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Pull request merged**
