### PR TITLE
magento/magento2#35810: Integrity constraint violation error when saving product without sku

### LINKED ISSUE #35810: SQLSTATE[23000]: Integrity constraint violation error when saving product without sku
### Preconditions and environment

2.4.4 and 2.4-develop

### Steps to reproduce

1. Admin - Stores - Attributes - Product - Search for sku - edit - set "Values Required" - No and save
2. Clear cache
3. Create product without sku - save. - Invalid error message displayed to the user.
**Error in 2.4-develop branch:**  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sku' cannot be null, query was: INSERT INTO `catalog_product_entity` (`entity_id`, `attribute_set_id`, `type_id`, `sku`, `has_options`, `required_options`, `created_at`, `updated_at`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
4. Create product with sku value and save
5. Edit product - remove sku and save - User is able to save the product without sku

### Expected result

Valid below error message will be displayed to the user.
"The "sku" attribute value is empty""

### Actual result

On 2.4.4 Project-community-edition, below php error is returned on creating product without SKU
Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/mg244/project-community-edition/vendor/magento/module-eav/Model/Entity/AbstractEntity.php on line 932

### Additional information

User is able to save the product without price (If configured "not required" in attribute configuration) even though it is mandated with " * " in admin configuration
image

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by KrasnoshchokBohdan**
Fix saving product without sku.

### Description (*)

Change sku value of object from null to '' in method \Magento\Catalog\Model\Product\Attribute\Backend\Sku::beforeSave to prevent mistake SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sku' cannot be null.

### Related Pull Requests

--

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35810

### Manual testing scenarios (*)

1. Admin - Stores - Attributes - Product - Search for sku - edit - set "Values Required" - No and save
2. Clear cache
3. Create product without sku - save.

Before fix:
Invalid error message displayed to the user.
Error in 2.4-develop branch: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sku' cannot be null, query was: INSERT INTO catalog_product_entity (entity_id, attribute_set_id, type_id, sku, has_options, required_options, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)

After fix:
Invalid error/exception should not be displayed.
Product successfully created.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
https://github.com/magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run Functional Tests EE

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run Integration Tests

**Comment by ishakhsuvarov** [comment]
It looks like there is a pending discussion in the https://github.com/magento/magento2/issues/35810 on this.

I'll move this PR to `on hold` while it's not done.

**Comment by engcom-November** [comment]
Hi @KrasnoshchokBohdan ,
After internal discussions with Product Owner and team, it has been concluded that a proper error message (The "sku" attribute value is empty") will be displayed to the end user when trying to create or save a product without SKU for the time being. This is the approved [PR](https://github.com/magento-gl/magento2ce/pull/525) having the changes related to the same and target version for the fix is 2.4.6. Display error message in a generic way for all such mandatory / predefined attributes (Ex: Name, price etc) will be soon implemented in coming future.
Thank you.

**Comment by ishakhsuvarov** [comment]
Closing this PR for now per comment above. Please feel free to reopen if you believe this is an error.

**Pull request closed without merging**
