### PR TITLE
Bugfix: Sort multiline form elements by given array keys before imploding.

### LINKED ISSUE #37973: [Issue] Bugfix: Sort multiline form elements by given array keys before imploding.
This issue is automatically created based on existing pull request: magento/magento2#37970: Bugfix: Sort multiline form elements by given array keys before imploding.

---------
### Description (*)
When you change the display order of the street field customer account edit address form it will save the fields incorrectly. Even when you set the names of the first field as street[3], second field street[2] and the last field as street[1].

This is a real world scenerio when you have multiple stores and want to change the sort order of the address fields for 1 specific store, because of how that country uses addresses (house number before street, instead of the other way around). 

This PR will make sure that the street fields are sorted by the given keys in the form first before imploding making sure that they are stored in the correct order in the DB. 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by dverkade**
### Description (*)
When you change the display order of the street field customer account edit address form it will save the fields incorrectly. Even when you set the names of the first field as street[3], second field street[2] and the last field as street[1].

This is a real world scenerio when you have multiple stores and want to change the sort order of the address fields for 1 specific store, because of how that country uses addresses (house number before street, instead of the other way around). 

This PR will make sure that the street fields are sorted by the given keys in the form first before imploding making sure that they are stored in the correct order in the DB. 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37973: Bugfix: Sort multiline form elements by given array keys before imploding.

### CODE REVIEW

**Comment by dverkade** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
@magento create issue

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @dverkade,

Thanks for the contribution!

Please add some automated tests in accordance with [DoD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1) to cover the code changes.

Thanks

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Integration Tests,Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

**Review by engcom-Hotel — APPROVED** [review]
Failed tests seems flaky to me. Hence approving the PR.

**Comment by engcom-Delta** [comment]
Hi @dverkade , 

We couldn't able to reproduce this issue with the mentioned description. Can you please provide the steps to reproduce for this ?

Thanks,

**Comment by engcom-Delta** [comment]
Hi @dverkade,

We are waiting for your reply to proceed further.

Thanks,

**Comment by engcom-Echo** [comment]
@magento run  Functional Tests CE

**Comment by engcom-Echo** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

1. Change sort order of street field in customer street address template. Set the names of the first field as street[2] and the last field as street[1].

**Before:** :heavy_multiplication_x: 
beforeee


**After:** :heavy_check_mark:  
aftere

**Comment by engcom-Echo** [comment]
Functional Tests CE are different on last two run on same commit.
Run1
Screenshot 2023-10-30 at 6 08 42 PM

Run2
Screenshot 2023-10-30 at 6 08 49 PM

Hence moving it to `merge in progress`.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Pull request merged**
