### PR TITLE
If stock is bellow OutOfStock Threshold, a negative qty is displayed in Product List Page

### PR DESCRIPTION
**Pull request by khodu**
### Description (*)

If stock is bellow OutOfStock Threshold, a negative qty is displayed in Product List Page
### Fixed Issues (if relevant)

1. magento/magento2#9130: If stock is bellow OutOfStock Threshold, a negative qty is displayed in Product List Page

### Manual testing scenarios (*)

1. Set qty to 5 for a product, and Out of Stock threshold to 10. Save the product
When browsing that product in the frontend a "Only -5 left" is displayed under "Out of Stock" message.
2. Remove the block if qty is negative.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @khodu. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [Magento instance](http://34.228.235.121/i-19206-2-3-develop/).
Admin access: [http://34.228.235.121/i-19206-2-3-develop//admin](http://34.228.235.121/i-19206-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
@khodu thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @khodu. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
