### PR TITLE
magento/magento2#15255 unlock customer after password reset

### PR DESCRIPTION
**Pull request by andreagaspardo**
Unlock customer after password reset

### Fixed Issues (if relevant)

1. magento/magento2#15255: unlock customer after password reset

### Manual testing scenarios

1. After x customer failed login, customer get locked
2. From backend, it's sent a reset password main
3. User changes his password
4. User is still locked

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15534) <br/>All committers have signed the CLA.

**Comment by miguelbalparda** [comment]
@andreagaspardo thanks for your contribution! Please remember to sign the CLA so we can process this.

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-1987](https://jira.corp.magento.com/browse/ENGCOM-1987) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@andreagaspardo thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @andreagaspardo. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.6 release.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
