### PR TITLE
Fixed customer back redirect navigate from edit product review

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

Fixed customer back redirect navigate from edit product review
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: N/A

### Manual testing scenarios (*)

1. Marketing -> All Reviews

2. edit any review -> edit any customer 

3. click on back redirect 

### Expected result (*)
back redirect to edit review

### Actual result (*)
back redirect to  customer/index/index

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ravi-chandra3197** [comment]
Hello @rogyar 
any suggestion ?

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @ravi-chandra3197. Thanks for collaboration. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

**Comment by ravi-chandra3197** [comment]
> Hi @ravi-chandra3197. Thanks for collaboration. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

Hello @VladimirZaets 
All automated tests have passed
can you review PR.

**Comment by VladimirZaets** [comment]
@ravi-chandra3197 the tests were green before your fix, it means that this part of the functionality is not covered by tests, so according to our rules (DoD) we should cover this functionality to avoid the issue in this part in the feature. So, I ask you to write a new automated test that will cover this functionality

**Comment by sidolov** [comment]
@ravi-chandra3197  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
