### PR TITLE
Added Review APi

### PR DESCRIPTION
**Pull request by ghost**
The core Magento 2 does not provide the REST API for the Reviews Extention of the products. So we have written Api for reviews and rating of a product.

We are attaching Documentation file based on Swagger .

[swaggerapi.txt](https://github.com/magento/magento2/files/320388/swaggerapi.txt)

### CODE REVIEW

**Comment by vkublytskyi** [comment]
@ajay-ipragmatech, Thank you for your contribution. Please accept the contributors license agreement so this PR can be further processed. This can be done by clicking the "Details" link next to the "license/cla" check below.

**Comment by ghost** [comment]
Hello Magento Team,

We have tried so many times to accept CLA but every time it fails. I do
complete all the steps but again when I go to my account it shows that
"Contributor
License Agreement is not signed yet."

So could you guys provide the solution that how can I sign the CLA?

## 

Thanks & Regards

Ajay Kumar | Sr.Software Engineer
iPragmatech Solutions - www.ipragmatech.com
*Email Id *ajay.kumar@ipragmatech.com noopur.virmani@ipragmatech.com
Skype ajay.bhardwaj87
Tweet iPragmatech https://twitter.com/iPragmatech  | Facebook iPragmatech
http://www.facebook.com/ipragmatech
socialfoxhosting.com - Optmized hosting for Socialengine

**Comment by ghost** [comment]
@vkublytskyi - I am not able to sign the contributor License Agreement. Could you suggest how could I sign it as it's not working after several attempts.

**Comment by ghost** [comment]
We are not able to sign the CLA cause of different user commit so i am going to take a new pull and no need for this request.

**Pull request closed without merging**
