### PR TITLE
Improve csv getdata method

### PR DESCRIPTION
**Pull request by dvynograd**
Current implementation of \Magento\Framework\File\Csv::getData first read all the content in the array and keeps it in memory, that might crash PHP when processing big files.
I suggest using a generator that gives an opportunity to process CSV files chunk by chunk instead.

I've decided do not change the original method for backward compatibility and create a new method.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16718) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @dvynograd. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
@dvynograd thanks for a nice idea.

1) Such contribution has no sense without actually refactoring core usages
2) Please mark old method as deprecated due to described observations
3) Please choose a better name for new method, something like `getDataChunk` or simply `get` would be more clear as you don't actually return stream

**Comment by orlangur** [comment]
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.

**Pull request closed without merging**
