### PR TITLE
Fixed deprecated method usages of MessageManager

### PR DESCRIPTION
**Pull request by drpayyne**
### Description

- Replaced deprecated method usages of MessageManager in `Magento_Review`
- Fixed appropriate PHPUnit tests

### Manual testing scenarios

- ONLY code modifications

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hi @drpayyne, could you please check and apply the static test recommendations?

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6175](https://jira.corp.magento.com/browse/ENGCOM-6175) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by engcom-Golf** [comment]
Failed functional tests, not related to the changes as a job cannot be restarted

**Pull request merged**
