### PR TITLE
[MFTF] use ActionGroup for navigation to checkout page

### LINKED ISSUE #29843: [Issue] [MFTF] use ActionGroup for navigation to checkout page
This issue is automatically created based on existing pull request: magento/magento2#29832: [MFTF] use ActionGroup for navigation to checkout page

---------
This PR use `StorefrontOpenCheckoutPageActionGroup` for navigation to CheckoutPage

### PR DESCRIPTION
**Pull request by Usik2203**
This PR use `StorefrontOpenCheckoutPageActionGroup` for navigation to CheckoutPage

### Resolved issues:
1. [x] resolves magento/magento2#29843: [MFTF] use ActionGroup for navigation to checkout page

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

Looks like an unrelated failure.
image

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by sidolov — APPROVED** [review]

**Pull request merged**
