### PR TITLE
[Backport] 2.1 develop pr port 15566

### PR DESCRIPTION
**Pull request by gelanivishal**
### Original Pull Request
#15566

Fix for #15565 

### Description
Simple Fix

### Fixed Issues (if relevant)
Fix for #15565 

### Manual testing scenarios
See Ticket

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-2000](https://jira.corp.magento.com/browse/ENGCOM-2000) has been created to process this Pull Request

**Comment by sidolov** [comment]
Hi @vgelani , we can't reproduce the described issue on vanilla 2.1-develop. Please, verify issue steps and update PR description if needed.

**Comment by gelanivishal** [comment]
@sidolov Yes. I can't produce issue but this PR also fixed the coding standard issue.

**Comment by sidolov** [comment]
@vgelani , I'm closing this PR as not relevant. Please, deliver coding standards fixes in the scope of another pull request or create new. Thank you for collaboration!

**Pull request closed without merging**
