### PR TITLE
update-button-issue-while-updating-billing-and-shipping-address

### PR DESCRIPTION
**Pull request by priti2jcommerce**
### Description (*)
Update button issue while updating billing and shipping-address on tablet and mobile view.
Magento 2.3.0

### Manual testing scenarios (*)

1. Go to checkout 
2. fill the  information
3. select shipping method and 
4. click on next button
5. click on checkbox ( My billing and shipping-address are the same)
6. check on tab and mobile

### Actual Screenshot (*)
2019-01-15_12-29_checkout 2

### Expected Screenshot (*)
2019-01-15_12-29_checkout

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by priti2jcommerce** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce, here is your [Magento instance](https://i-20297-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20297-2-3-develop.instances.magento-community.engineering/admin](https://i-20297-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by sidolov — APPROVED** [review]

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3867](https://jira.corp.magento.com/browse/ENGCOM-3867) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@priti2jcommerce thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
