### PR TITLE
small performance improvement on product listing

### PR DESCRIPTION
**Pull request by apasare**
### Description (*)

Get rid of unnecessary reviews queries on product listing:
"select review_entity_summary.* from review_entity_summary where (review_entity_summary.entity_pk_value = ?) and (store_id = ?)" 
This query was executed for each product on listing which didn't have a review summary(@see: `Magento\Review\Model\Review::appendSummary` and `Magento\Review\Block\Product\ReviewRenderer::getReviewsSummaryHtml`)

### Manual testing scenarios (*)

1. Use a profiler(e.g. blackfire)
2. Go to any product listing page(category page)
3. After profiling the product listing page you should notice that for each product which doesn't have a review an additional sql query is executed: "select review_entity_summary.* from review_entity_summary where (review_entity_summary.entity_pk_value = ?) and (store_id = ?)"

E.g.: if on your product listing page you are listing 20 products, and 3 products have reviews, you will see 17 x "select review_entity_summary.* from review_entity_summary where (review_entity_summary.entity_pk_value = ?) and (store_id = ?)"

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18773) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @godvsdeity. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-3437](https://jira.corp.magento.com/browse/ENGCOM-3437) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@godvsdeity thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @godvsdeity. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
