### PR TITLE
Update Media.php

### LINKED ISSUE #33349: Issue with image cache generation
### Preconditions (*)

1. Magento 2.4.2
2.

### Steps to reproduce (*)

1. Image cache generation issue. Placeholer image generation in product page
2.

### Expected result (*)

1. Image generation correct
2.

### Actual result (*)

1. No error in log
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by ghost**
Issue #33349

### Description (*)

Above syntax explaing that it will find the whole name in image url, And it's can't find the full name instead it was just taking single charchater, e.g if url have icecatproducts/a/b/product image.jpg then it was just taking the i/a/b/product image. and they consider wrong url. So he replace the right string syntax inbetween
### Fixed Issues (if relevant)

1. Fixes magento/magento2#33349

### Manual testing scenarios (*)

1. Image cache generation show correct image and not placeholder in product page
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by achatpc** [comment]
@magento run all tests

**Comment by achatpc** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@duhon Do you remember why changes https://github.com/magento/magento2/commit/362eba826be3a7aff9ce9de579893e639ffc2cfd was implemented?

**Comment by achatpc** [comment]
> @duhon Do you remember why changes [362eba8](https://github.com/magento/magento2/commit/362eba826be3a7aff9ce9de579893e639ffc2cfd) was implemented?

I am sorry, but no.

**Review by Den4ik — APPROVED** [review]
In my opinion rollback make sense.

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9163](https://jira.corp.magento.com/browse/ENGCOM-9163) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by Den4ik** [comment]
@achatpc Thanks for the contribution.
I'm close this PR prior to https://github.com/magento/magento2/pull/32768

**Pull request closed without merging**
