### PR TITLE
Make sure 'last' class is set on top menu

### PR DESCRIPTION
**Pull request by arnoudhgz**
Original PR: #13323 (was accidentally closed)

### Description
The counter in the foreach loop was not being calculated correctly. This resolved in the 'last' css class not being set on the output when one or more parent items are not active.

With this PR the items will be filtered first before they are being processed for the html output.

### Fixed Issues (if relevant)
1. magento/magento2#13266: Topmenu 'last' class not being set if the a parent is inactive

### Manual testing scenarios
1. Do a clean install of Magento 2.2 with sample data
2. Set a level 1 category (e.g. Gear or Gift Cards) inactive
3. Refresh the appropriate cache
4. Inspect the menu and see there is a class last on the **last** active top menu item

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-22071.instances.magento-community.engineering).
Admin access: [https://pr-22071.instances.magento-community.engineering/admin](https://pr-22071.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4623](https://jira.corp.magento.com/browse/ENGCOM-4623) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed 

**Before:**

before

**After:**

after

**Pull request merged**
