### PR TITLE
Removed CliCacheFlushActionGroup usage for Checkout module

### LINKED ISSUE #32072: [Issue] Removed CliCacheFlushActionGroup usage for Checkout module
This issue is automatically created based on existing pull request: magento/magento2#32071: Removed CliCacheFlushActionGroup usage for Checkout module

---------
### Description
Removed CliCacheFlushActionGroup usage for Checkout module

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Removed CliCacheFlushActionGroup usage for Checkout module

### Resolved issues:
1. [x] resolves magento/magento2#32072: Removed CliCacheFlushActionGroup usage for Checkout module

### CODE REVIEW

**Comment by sergiy-v** [comment]
@magento create issue

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Semantic Version Checker

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @sergiy-v, could you please check the failed tests, it seems to be related to PR's changes?
Thank you.

**Comment by sergiy-v** [comment]
> Hi @sergiy-v, could you please check the failed tests, it seems to be related to PR's changes?
> Thank you.

@eduard13 will check it, thank you.

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE

**Comment by sergiy-v** [comment]
@magento run WebAPI Tests, Unit Tests, Static Tests, Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B, Magento Health Index, Integration Tests, Database Compare

**Comment by sergiy-v** [comment]
> Hi @sergiy-v, could you please check the failed tests, it seems to be related to PR's changes?
> Thank you.

Looks like it was temporary issues, now all tests are green, @eduard13 please proceed with review.
Thank you.

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8756](https://jira.corp.magento.com/browse/ENGCOM-8756) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Pull request merged**
