### PR TITLE
Improve error messaging when merged XML is invalid

### PR DESCRIPTION
**Pull request by fredden**
### Description
When dealing with XML in Magento, the error messages are not always most helpful. When each XML document is individually valid, but the result of merging these isn't, the error message does not help a developer identify the issue.

This pull request adds the filename causing a problem to the error message output.

<details open><summary>Before and after pictures</summary>

The following two pictures show the output from `bin/magento setup:upgrade` where the problem shows up.

Before:

Screenshot_2022-10-04_15-59-12

After:

Screenshot_2022-10-04_15-57-42

</details>

### Manual testing scenarios
Note that if you fix/merge https://github.com/magento/magento2/pull/36240 before this, then you will need to find alternative steps to reproduce.
1. Ensure Magento is in "developer" mode with `bin/magento deploy:mode:set developer`
1. Create a new local module in `app/code/`
1. Create a valid `etc/db_schema.xml` file changing the 'type' of an existing column from 'int' (with 'padding') to 'varchar'. For example, https://github.com/magento/magento2/blob/447c613c86ea655d94f511b495fcc5d1273072c3/app/code/Magento/AsynchronousOperations/etc/db_schema.xml#L20-L21 and
   ```xml
   <?xml version="1.0"?>
   <schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="urn:magento:framework:Setup/Declaration/Schema/etc/schema.xsd">
       <table name="magento_bulk">
           <column xsi:type="varchar" name="operation_count" />
       </table>
   </schema>
   ```
1. Run `bin/magento setup:upgrade`
1. Witness error message

Before this change, it is very difficult to identify the location of the error.

### Questions or comments
All unit tests pass both before and after this change, suggesting that the code coverage isn't ideal. Perhaps we need a separate task to improve code coverage of this class.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@fredden Great job! Do you feel it's possible to cover with any type of automated tests?

**Comment by fredden** [comment]
> Do you feel it's possible to cover with any type of automated tests?

I don't know how to reliably cover this with a test. We could write a test using the given example, but the underlying problem is being fixed in https://github.com/magento/magento2/pull/36240, so we'd need another test case that will reliably break. I'm open to suggestions.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
Yeah, looks like it will be too hard to cover it with test, let's skip it

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE

**Comment by engcom-Lima** [comment]
Hi @fredden ,

Thanks for your contribution and collaboration.

I have tried to reproduce the issue but issue is not reproducible to me. I have followed steps given in the above comment.
I am getting some other kind of error as given in the screenshot:
I have found this error in new module which I have created as well as tried to check in  pre-existing module(changing db_schema.xml).
Screenshot 2022-10-26 at 3 54 15 PM

Kindly provide more information in order to reproduce the issue.

Thanks

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@engcom-Lima please can you remove the 'needs update' label from this pull request.

**Comment by fredden** [comment]
@engcom-Delta with the supplied module (after removing all the MacOS files), I get the expected result:

Screenshot_2022-11-18_13-59-19

**Comment by engcom-Delta** [comment]
@fredden,
We have tried to reproduce this issue as per the main description 
1. Created custom module
2. Created the db_schema.xml file (app/code/Magento/AsynchronousOperations/etc/db_schema.xml) as per the main description.
Here is the custom module and the db_schema.xml file,please have a look
[custom.zip](https://github.com/magento/magento2/files/10055569/custom.zip)
3. Run bin/magento setup:upgrade.
Still we are not getting any error and module is upgraded properly and in table also int is changed to varchar.
Screenshot 2022-11-21 at 3 59 35 PM
Screenshot 2022-11-21 at 4 01 45 PM

Please let us know ,if we are missed any steps.

Thanks.

**Comment by fredden** [comment]
@engcom-Delta thanks for the feedback. I don't understand why you aren't able to reproduce the error. Please can you confirm the commit that you are testing with? I wonder if you have perhaps applied the changes from https://github.com/magento/magento2/pull/36240 which resolves the cause of the error. Note that's intentionally a different pull request than this.

I have tested with the new module you have supplied. I can confirmed that the original error shows up with 39f0be8226abd6036afccfc012a6a14dcb828b20 (current HEAD of `2.4-develop` branch) and the improved error message shows up with c7b2d47b8730e4d0c84c289f58c31e3624e059ce (current HEAD of this branch / pull request).

**Comment by hostep** [comment]
I've seen strange circumstances where xml file validation didn't happen in the past. Not exactly sure in what conditions it can be skipped, but maybe one of them is the developer vs production mode of Magento? Never really looked it up what environment specific settings can influence this xml structure validation, but I'm pretty sure they exist...

**Comment by fredden** [comment]
Thank you, @hostep. I have tested now with deploy-mode is set to "production": no error messages are displayed. I'll add `bin/magento deploy:mode:set developer` to the prerequisites / steps to reproduce.

**Comment by fredden** [comment]
@engcom-Delta with @hostep's help, I've updated the manual testing notes section in the pull request description. Please can you try again.

**Comment by engcom-Delta** [comment]
@fredden @hostep 
Thanks for providing the information and update.

**Comment by engcom-Delta** [comment]
@fredden 

**Preconditions:**
- Install fresh Magento `2.4-develop`


**Manual testing scenario:**

1. Enabled developer mode with bin/magento deploy:mode:set developer.
2. Created custom module in app/code directory
3. Created valid schema file (db_schema.xml) for the app/code/Magento/AsynchronousOperations/etc/db_schema.xml
    and changed the type int to varchar as below
    
Screenshot 2022-11-22 at 12 00 50 PM
4. Run bin/magento setup:upgrade.

**Before:PR changes** :heavy_multiplication_x: 
Screenshot 2022-11-22 at 10 56 37 AM



**After:PR changes**:heavy_multiplication_x: 
Screenshot 2022-11-22 at 11 19 30 AM
Hence, moving this PR to Changes requested.
Thanks.

**Comment by fredden** [comment]
@engcom-Delta thanks for testing. I can see that you have successfully verified the change. What changes would you like to be made to this pull request? Perhaps you meant to confirm/approve this and picked the wrong option?

**Comment by engcom-Delta** [comment]
@fredden My apologies for that. I have updated and will move it to the appropriate column.

**Comment by engcom-Delta** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Delta** [comment]
@magento run Functional Tests EE

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento run Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Pull request merged**
