### PR TITLE
[MFTF] MoveRecentlyViewedBundleFixedProductOnOrderPageTest refactoring

### LINKED ISSUE #34280: [Issue] [MFTF] MoveRecentlyViewedBundleFixedProductOnOrderPageTest refactoring
This issue is automatically created based on existing pull request: magento/magento2#34249: [MFTF] MoveRecentlyViewedBundleFixedProductOnOrderPageTest refactoring

---------
The test is refactored according to the best practices

### PR DESCRIPTION
**Pull request by AnnaAPak**
The test is refactored according to the best practices

### Resolved issues:
1. [x] resolves magento/magento2#34280: [MFTF] MoveRecentlyViewedBundleFixedProductOnOrderPageTest refactoring

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, Semantic Version Checker

**Review by edenduong — APPROVED** [review]
Thank you for your contribution!

**Comment by magento-engcom-team** [comment]
Hi @edenduong, thank you for the review.
[ENGCOM-9244](https://jira.corp.magento.com/browse/ENGCOM-9244) has been created to process this Pull Request

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run  Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by Den4ik — APPROVED** [review]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9244](https://jira.corp.magento.com/browse/ENGCOM-9244) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by engcom-Alfa** [comment]
@magento run WebAPI Tests, Unit Tests, Static Tests, Sample Data Tests EE, Sample Data Tests B2B, Magento Health Index, Integration Tests, Database Compare

**Comment by engcom-Alfa** [comment]
@magento run Sample Data Tests CE

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

This PR is relevant to the MFTF test code factoring as per the description and as looked into the files changed.
Since the auto-test jobs are successfully running with this PR, moving to _Merge In Progress_.
Thanks for the contribution and collaboration all.

**Pull request merged**
