### PR TITLE
MC-39521: Random deadlocks during setting email sent flag

### LINKED ISSUE #31090: Random deadlocks during setting email sent flag
During Black Friday we found random deadlocks during trying to send new order emails.
Analyzing of these cases a bit not obvious - Magento actually saves whole order object, and it saves all the order items JUST FOR setting flag that email was sent for the order. As result under high load we're having deadlocks like this:
```
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: UPDATE `sales_order_item` SET `order_id` = ?, `parent_item_id` = ?, `quote_item_id` = ?, `store_id` = ?, `created_at` = '2020-11-28 23:33:44', `product_id` = ?, `product_type` = ?, `product_options` = ?, `weight` = ?, `is_virtual` = ?, `sku` = ?, `name` = ?, `description` = ?, `applied_rule_ids` = ?, `additional_data` = ?, `is_qty_decimal` = ?, `no_discount` = ?, `qty_backordered` = ?, `qty_canceled` = ?, `qty_invoiced` = ?, `qty_ordered` = ?, `qty_refunded` = ?, `qty_shipped` = ?, `base_cost` = ?, `price` = ?, `base_price` = ?, `original_price` = ?, `base_original_price` = ?, `tax_percent` = ?, `tax_amount` = ?, `base_tax_amount` = ?, `tax_invoiced` = ?, `base_tax_invoiced` = ?, `discount_percent` = ?, `discount_amount` = ?, `base_discount_amount` = ?, `discount_invoiced` = ?, `base_discount_invoiced` = ?, `amount_refunded` = ?, `base_amount_refunded` = ?, `row_total` = ?, `base_row_total` = ?, `row_invoiced` = ?, `base_row_invoiced` = ?, `row_weight` = ?, `base_tax_before_discount` = ?, `tax_before_discount` = ?, `ext_order_item_id` = ?, `locked_do_invoice` = ?, `locked_do_ship` = ?, `price_incl_tax` = ?, `base_price_incl_tax` = ?, `row_total_incl_tax` = ?, `base_row_total_incl_tax` = ?, `discount_tax_compensation_amount` = ?, `base_discount_tax_compensation_amount` = ?, `discount_tax_compensation_invoiced` = ?, `base_discount_tax_compensation_invoiced` = ?, `discount_tax_compensation_refunded` = ?, `base_discount_tax_compensation_refunded` = ?, `tax_canceled` = ?, `discount_tax_compensation_canceled` = ?, `tax_refunded` = ?, `base_tax_refunded` = ?, `discount_refunded` = ?, `base_discount_refunded` = ?, `free_shipping` = ?, `gift_message_id` = ?, `gift_message_available` = ?, `weee_tax_applied` = ?, `weee_tax_applied_amount` = ?, `weee_tax_applied_row_amount` = ?, `weee_tax_disposition` = ?, `weee_tax_row_disposition` = ?, `base_weee_tax_applied_amount` = ?, `base_weee_tax_applied_row_amnt` = ?, `base_weee_tax_disposition` = ?, `base_weee_tax_row_disposition` = ?, `osc_gift_wrap_amount` = ?, `base_osc_gift_wrap_amount` = ?, `mp_reward_earn` = ?, `mp_reward_spent` = ?, `mp_reward_base_discount` = ?, `mp_reward_discount` = ? WHERE (item_id='1644918')
```

The stack trace was following:
```
/path/to/magento2/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:613
/path/to/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php:635
/path/to/magento2/vendor/magento/module-sales/Model/ResourceModel/EntityAbstract.php:182
/path/to/magento2/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php:419
/path/to/magento2/vendor/magento/module-sales/Model/Order/ItemRepository.php:176
/path/to/magento2/vendor/magento/module-sales/Model/ResourceModel/Order/Relation.php:74
/path/to/magento2/vendor/magento/framework/Model/ResourceModel/Db/VersionControl/RelationComposite.php:48
/path/to/magento2/vendor/magento/framework/Model/ResourceModel/Db/VersionControl/AbstractDb.php:57
/path/to/magento2/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php:424
/path/to/magento2/vendor/magento/module-sales/Model/ResourceModel/Order.php:178
/path/to/magento2/vendor/magento/module-sales/Model/EmailSenderHandler.php:113
/path/to/magento2/vendor/magento/module-sales/Cron/SendEmails.php:46
/path/to/magento2/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:350
/path/to/magento2/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:809
/path/to/magento2/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:776
/path/to/magento2/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:267
/path/to/magento2/vendor/magento/framework/Event/Invoker/InvokerDefault.php:88
/path/to/magento2/vendor/magento/framework/Event/Invoker/InvokerDefault.php:74
/path/to/magento2/vendor/magento/framework/Event/Manager.php:66
/path/to/magento2/generated/code/Magento/Framework/Event/Manager/Proxy.php:95
/path/to/magento2/vendor/magento/framework/App/Cron.php:86
/path/to/magento2/vendor/magento/module-cron/Console/Command/CronCommand.php:117
/path/to/magento2/vendor/symfony/console/Command/Command.php:255
/path/to/magento2/vendor/magento/framework/Interception/Interceptor.php:58
/path/to/magento2/vendor/magento/framework/Interception/Interceptor.php:138
/path/to/magento2/vendor/magento/framework/Interception/Interceptor.php:153
/path/to/magento2/generated/code/Magento/Cron/Console/Command/CronCommand/Interceptor.php:26
/path/to/magento2/vendor/symfony/console/Application.php:1005
/path/to/magento2/vendor/symfony/console/Application.php:271
/path/to/magento2/vendor/magento/framework/Console/Cli.php:115
/path/to/magento2/vendor/symfony/console/Application.php:147
/path/to/magento2/bin/magento:23
```

Potentially such behavior might cause issues with double sending new order emails.

### Preconditions (*)
1. Magento 2.3.6,  2.4-develop
2. Enabled async email sending

### Steps to reproduce (*)
1. Disable cron jobs
2. Place an order
3. Set breakpoint at https://github.com/magento/magento2/blob/d7ab99d8ba8914ffc9e47e396cda238c825712ce/app/code/Magento/Sales/Model/EmailSenderHandler.php#L111 and https://github.com/magento/magento2/blob/d7ab99d8ba8914ffc9e47e396cda238c825712ce/app/code/Magento/Sales/Model/ResourceModel/Order/Relation.php#L69
4. Run `php bin/magento cron:run`

### Expected result (*)

1. We should have just tiny SQL for updating one column, not the whole object and all related objects 
- so our debug should stop only on 1st breakpoint

### Actual result (*)

1. We have saving of whole object and all their related objects that causing deadlocks under the load
- so our debug stopping on 1st and 2nd breakpoints

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by engcom-Golf**
Removed extra save sales entity that causes load on database
### Fixed Issues (if relevant)

1. Fixes magento/magento2#31090
### Manual testing scenarios (*)

Use following scenario to test order, invoice, shipment and credit memo creation
1. Configure email sending
2. Enable async email send in Stores->Configuration->Sales->Sales Emal
3. Create Order on FE
4. Perform PHP bin/magento cron:run command
#### Expected result:
Email sent and sales entity has set flag email_sent & send_email in database
Email is not sent a second time if cron:run is performed again

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
In general looks good. Let's wait for test results

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8528](https://jira.corp.magento.com/browse/ENGCOM-8528) has been created to process this Pull Request

**Review by zakdma — APPROVED** [review]

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31189`.

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

### Manual testing scenarios

Use the following scenario to test order, invoice, shipment and credit memo creation

1. Configure email sending
2. Enable async email send in Stores->Configuration->Sales->Sales Email
3. Create Order on FE
4. Perform PHP bin/magento cron:run command

**Actual Result:**
Email sent and sales entity has set flag email_sent & send_email in database
Email is not sent a second time if cron:run is performed again

Before cron:run
Before cron run

After cron:run
After cron run

Also, before applying the changes provided in the PR, **debug stopped on 1st and 2nd breakpoints** after `bin/magento cron:run`
https://github.com/magento/magento2/blob/d7ab99d8ba8914ffc9e47e396cda238c825712ce/app/code/Magento/Sales/Model/EmailSenderHandler.php#L111 and https://github.com/magento/magento2/blob/d7ab99d8ba8914ffc9e47e396cda238c825712ce/app/code/Magento/Sales/Model/ResourceModel/Order/Relation.php#L69

After switching to the PR, debug stops only once

**Pull request merged**
