### PR TITLE
Issue 36309: Undefined value sets in the variant's sku

### LINKED ISSUE #36309: Undefined value sets in the variant's sku
### Preconditions and environment

- Magento version: 2.4.5
- Add sample data by using this command _bin/magento sampledata:deploy_

### Steps to reproduce

1. Go to the Stores menu -> select 'Attribute set' under the Attributes section.
2. Select any one attribute set from the list and it will open.
3. Move any group to the top above the 'Product Details' group in the group section like in the below image.
Bag-Attribute-Sets-Attributes-Stores-Magento-Admin

4. Open any product from that attribute set in which you move the group (In my case I have taken one product as marked in the below image where the attribute set is 'Bag').
Products-Inventory-Catalog-Magento-Admin

5. Now go to the 'Configurations' tab and create a simple product by clicking the 'Create Configurations' as in the below image.
Joust-Duffle-Bag-Products-Inventory-Catalog-Magento-Admin

6. Now follow the steps mentioned below:
- **Step 1:** Select Attributes - select any attribute from the list and click next.
- **Step 2:** Attribute Values - Select options and click on the next.
- **Step 3:** Bulk Images, Price, and Quantity - Don't do anything and click on the next.
- **Step 4:** Summary - you can see the grid of the products you are about to create. But in the 'SKU' column, you can see it sets the undefined text instead of the parent SKU's text as in the below image.

Variant-Products-Inventory-Catalog-Magento-Admin

### Expected result

when we create variants of the product while the other tab is on the top above the 'Product Details', it should create variants with the proper SKU names like in the image.
Correct-Variant-Products-Inventory-Catalog-Magento-Admin

### Actual result

It sets the undefined value to the SKU as shown in step 6 of Steps to reproduce.

### Additional information

As I checked the file -
> _**/vendor/magento/module-configurable-product/view/adminhtml/web/js/variations/steps/summary.js**_

in this file, there is a function name '**calculate()**' at line 93 as in image.

summary-file-calculate

In this function getting productSku by calling function **getProductValue()** with passing argument 'sku'. This function is defined in the file -

> _**/vendor/magento/module-configurable-product/view/adminhtml/web/js/variations/variations.js**_

at line 132 as in the image.

variation-file-getProductValue

in the getProductValue() function, there is a code to get the value of the SKU at line 135. Here, if the 'Product Details' tab is not open by default in the product edit page in the admin then it can't able to get the value for the SKU. Because if the 'Product Details' tab is not opened then their elements don't load.

By default, the first tab will be open. So, if we add another tab to the top above the 'Product Details' tab then this tab will collapse (not open) by default. And the elements of this tab will not load. And we will get the undefined text instead of the proper SKU name for the variants. The same thing happens with the product name also.

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rogerdz**
### Description (*)

Return product attribute value when input field not render

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36309

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by ishakhsuvarov** [comment]
Current failures in functional and integration tests are unrelated to PR content.

**Comment by engcom-Lima** [comment]
@magento run Functional Tests CE, Functional Tests EE, Integration Tests

**Comment by engcom-Lima** [comment]
@magento give me test instance

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:*
- Install fresh Magento `2.4-develop`

**Manual testing scenario:**

1. Go to the Stores menu -> select 'Attribute set' under the Attributes section.
2. Select any one attribute set from the list and it will open.
3. Move any group to the top above the 'Product Details' group in the group section.
4. For ex- SEO
5. Edit any product from that attribute set in which you move the group .For ex - attribute set Bag.
6. Now go to the 'Configurations' tab and create a simple product by clicking the 'Create Configurations'
7. Select Attributes - select any attribute from the list and click next.
8. Attribute Values - Select options and click on the next.
9. Bulk Images, Price, and Quantity - Don't do anything and click on the next.
10. On Summary page check for the sku is displayed proper or not.

**Before:** :heavy_multiplication_x: 
image

image


**After:** :heavy_check_mark: 
image

image


Builds are failed. Hence, moving to extended testing.

**Comment by engcom-Lima** [comment]
@magento run Functional Tests CE, Integration Tests

**Comment by engcom-Lima** [comment]
@magento run Functional Tests CE, Integration Tests

**Comment by engcom-Lima** [comment]
@magento run Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Integration Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

**Pull request merged**
