### PR TITLE
Removed closing module tag and modified to single line

### LINKED ISSUE #28139: [Issue] Removed closing module tag and modified to single line
This issue is automatically created based on existing pull request: magento/magento2#28002: Removed closing module tag and modified to single line

---------

### Description (*)

Removed module close tag`</module>`, Alternatively optimize the tag in single line.

### PR DESCRIPTION
**Pull request by gokulra92**
### Description (*)

Removed module close tag`</module>`, Alternatively optimize the tag in single line. 

### Resolved issues:
1. [x] resolves magento/magento2#28139: Removed closing module tag and modified to single line

### CODE REVIEW

**Review by lbajsarowicz — CHANGES_REQUESTED** [review]
Personally I'd prefer to list real dependencies of the modules. Eg. `Usps` depends on `Shipping`.
Could you review the dependencies on the Database schema and actually configuration changes introduced by other modules, to make sure that we are not hiding the real issue there?

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7515](https://jira.corp.magento.com/browse/ENGCOM-7515) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@gokulra92 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VladimirZaets** [comment]
@lbajsarowicz I approved cause this PR it's just typo fixes. I understand that you ask to check is really those modules haven't any dependencies, but it's really not in the scope of this PR

**Review by lbajsarowicz — APPROVED** [review]
Approval (Need to investigate the real dependencies, @VladimirZaets )

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7515](https://jira.corp.magento.com/browse/ENGCOM-7515) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Charlie** [comment]
The failing functional tests are not related to the change in this pr.

**Comment by slavvka** [comment]
@magento create issue

**Comment by slavvka** [comment]
@gokulra92 Thank you for the submission but we cannot accept it since we have no rules that prohibit the usage of empty tags and hence there's no reason to change that. Thank you again for your interest and please keep on going to contribute more.

**Pull request closed without merging**
