### PR TITLE
Expiration period is now hours instead of days

### LINKED ISSUE #36895: [Issue] Expiration period is now hours instead of days
This issue is automatically created based on existing pull request: magento/magento2#36798: Expiration period is now hours instead of days

---------

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. In a custom module, compare the result of \Magento\Customer\Model\Customer::isResetPasswordLinkTokenExpired with \Magento\Customer\Model\AccountManagement::isResetPasswordLinkTokenExpired
2. Results are differents
3. Beside that there is no manual tests because the method is no more used within the Magento core

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by thomas-kl1**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. In a custom module, compare the result of \Magento\Customer\Model\Customer::isResetPasswordLinkTokenExpired with \Magento\Customer\Model\AccountManagement::isResetPasswordLinkTokenExpired
2. Results are differents
3. Beside that there is no manual tests because the method is no more used within the Magento core

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36895: Expiration period is now hours instead of days

### CODE REVIEW

**Comment by thomas-kl1** [comment]
@magento run all tests

**Review by Den4ik — CHANGES_REQUESTED** [review]
Hi @thomas-kl1 
This is great update. The changes looks good for me, but due to requirements of [Definition of Done criteria](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1) could you please cover changes with unit test and fix failed static tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Integration Tests,Functional Tests CE

**Comment by mahesh-singh-rajawat** [comment]
Hi @Den4ik,
Static failure fixed, and updated function is marked as `@deprecated` , do you think we require these changes to be covered with automation tests?

**Comment by thomas-kl1** [comment]
In my opinion it doesn't make sens to cover a deprecated method. It's not used in the core and is going to be removed. Clients that use this method does it at their own risk once it's deprecated

**Comment by mahesh-singh-rajawat** [comment]
@magento run Functional Tests CE

**Comment by mahesh-singh-rajawat** [comment]
@magento run Functional Tests CE

**Comment by mahesh-singh-rajawat** [comment]
Failing Functional Tests CE is not related to fix.
@Den4ik can you please review it comments and code?

**Review by Den4ik — APPROVED** [review]
✅  all looks good

**Comment by engcom-Charlie** [comment]
As per both above [comment](https://github.com/magento/magento2/pull/36798#issuecomment-1431012999), moving it to Ready for Testing.

Thank you!

**Comment by mahesh-singh-rajawat** [comment]
Function Tests CE is Flaky
[Run1](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36798/6f497299436b805a194d3f852cbe7534/Functional/allure-report-ce/index.html)
[Run2](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36798/715f4b454ada43db881b85f7a60ed679/Functional/allure-report-ce/index.html)

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

**Comment by engcom-Echo** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Expiration period is now hours instead of days

**Manual testing scenario:**

   1. In a custom module, compare the result of \Magento\Customer\Model\Customer::isResetPasswordLinkTokenExpired with \Magento\Customer\Model\AccountManagement::isResetPasswordLinkTokenExpired
   2. Verify the results are different
   
**Before:** :
\Magento\Customer\Model\Customer::isResetPasswordLinkTokenExpired  _returns_ **false**

**After:** :
\Magento\Customer\Model\Customer::isResetPasswordLinkTokenExpired  _returns_ **true**


Moving it to `Merge In Progress` as the Functional Tests CE failure are different as per the **comment**

**Pull request merged**
