### PR TITLE
Fix for sales PDFs to support more characters

### PR DESCRIPTION
**Pull request by rossmc**
### Description

The sales PDFs use the Libertine font which is not a unicode font and therefore it does not have full support of characters. It does not support Arabic, Russian, Greek, Indian or Thai alphabets and many more. For example it does not support the Indian ruppe currency symbol ( ₹ ) and displays _tofu_ boxes instead, which makes the PDF invoice totals illegible.

It's better if we use a [unicode font](https://en.wikipedia.org/wiki/Unicode_font) to support more languages and characters.  So I've added the open source [Noto-Serif](https://www.google.com/get/noto/) font to fix this issue.

### Fixed Issues (if relevant)

1. magento/magento2#9666: Magento 2.1.6 - Invoice PDF doesn't support Thai
2. magento/magento2#12323: Magento 2.1.3 - Invoice and shipment PDF doesn't support Arabic

### Manual testing scenarios

1. Set the [store currency](http://docs.magento.com/m2/ce/user_guide/stores/currency-symbols.html) to use the ruppe currency symbol ( ₹ ) .
2. [Print an invoice](http://docs.magento.com/m2/ce/user_guide/sales/invoice-print-multiple.html).

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=13016) <br/>All committers have signed the CLA.

**Comment by miguelbalparda** [comment]
Hi @rossmc! Thanks for your contribution. I really like the PR, let me check internally about the font you choose and I'll report back!

**Comment by rossmc** [comment]
Thanks @miguelbalparda 

Actually, I don't think the _Noto_ font I chose is the best. Noto doesn't support all writing systems with a single font file, but rather with a collection of different font files. [Their docs](https://twardoch.github.io/noto-docs/FAQ/#could-you-provide-a-single-font-file-that-covers-every-language-or-at-least-as-many-scripts-as-possible) point out...
> A single file is not possible, because there are many more glyphs in Noto than can fit into a single font.

I think a better alternative is [GNU Free Font](https://www.gnu.org/software/freefont/) which supports much more writing systems.  There could be others, like [Arial](https://www.microsoft.com/typography/fonts/font.aspx?FMID=1705). But GNU Free Font is the best I could find.

I updated this PR to use the GNU Free Font instead.

**Comment by sidolov** [comment]
Hi @rossmc , I will request information regarding font license and come back with updates. 
Thank you for the contribution!

**Comment by mgomma** [comment]
Arabic chars separated 2.1.5

**Comment by magento-engcom-team** [comment]
@rossmc thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by mgomma** [comment]
I think we should remove Zen_pdf totally as it'not supported and replace it with other php libraries that creates pdf from html/css.

The still exist with Unicode languages especially Arabic letters are displayed separated and reversed

**Comment by magento-engcom-team** [comment]
Hi @rossmc. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

**Comment by rossmc** [comment]
Hi @magento-engcom-team, 

I submitted similar PRs for 2.3-develop (#14710) and 2.1-develop (#14711).

Thanks,
Ross

**Pull request merged**
