### PR TITLE
Fixed the wrong behavior for a prompt modal when a user clicks on the modal overlay

### PR DESCRIPTION
**Pull request by serhiyzhovnir**
### Description (*)
The prompt modal performs the confirm action when a user clicks on the modal overlay.
This PR fixes this issue and adds the `false` argument for `closeModal()` method when a user clicks on the modal overlay.

### Related Pull Requests

The issue starts reproducing after the changes from this https://github.com/magento/magento2/commit/6167b0cf306689cae3f2309e65ab9653e1e69252 commit.

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1002: Confirm Save Preview is performed if click outside of the Search Adobe Stock when File Name window is opened

### Manual testing scenarios (*)
The manual testing scenarios and how to reproduce this issue is described in this issue magento/adobe-stock-integration#1002.

Also, it could be checked quickly with the following JS code via a browser console.

```javascript
require(['jquery', 'Magento_Ui/js/modal/prompt'], function ($, prompt) {
    prompt({
        title: 'Prompt Title',
        content: $('.prompt-modal-content'),
        modalClass: 'prompt',
        value: 'Value by default',
        validation: true,
        promptField: '[data-role="promptField"]',
        attributesForm: {
            novalidate: 'novalidate',
            action: ''
        },
        actions: {
            always: function() {
                // do something when the modal is closed
            },
            confirm: function () {
                alert('Confirmation');
            },
            cancel: function () {
                // do something when the cancel button is clicked
            }
        }
    });

    jQuery('.prompt + .modals-overlay').click()
})
```
This code creates the Prompt popup and clicks on overlay.
In 2.4-develop you will see the alert with "Confirmation" that is triggered by the confirm action.

This issue is fixed in this PR and the prompt popup will be closed after clicking on the modal overlay.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by nuzil** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @nuzil. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @nuzil, here is your [new Magento instance](https://pr-27399.instances.magento-community.engineering).
Admin access: [https://pr-27399.instances.magento-community.engineering/admin_f275](https://pr-27399.instances.magento-community.engineering/admin_f275)
Login: `1e782097` Password: `f59789959763`
Instance will be terminated in up to 3 hours.

**Review by nuzil — CHANGES_REQUESTED** [review]
Hi @serhiyzhovnir 
Please have a look at failed test, looks like it caused by your change:

[NO TESTCASEID]: Admin should be able to cancel and close 'create folder' modal window using ESC key and to add image to new folder (using enter key) for WYSIWYG content of Block

**Comment by sivaschenko** [comment]
Static test failure is not related to the changes in the pull request.

The same functional test is currently failing on other pull requests as well (i.e. https://github.com/magento/magento2/pull/25360 [Allure Report](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/25360/374a74b5ec0e4a2366ce5c7b03a7ba95/Functional/allure-report-ce/index.html#categories/4a0825ef59a053f6acce56734f3fe550/44f616ca60b3476b/)) so I assume it's not caused by the changes in this PR as well

**Review by sivaschenko — APPROVED** [review]

**Comment by sivaschenko** [comment]
@serhiyzhovnir could you cover the changes by jasmine or MFTF test?

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-7195](https://jira.corp.magento.com/browse/ENGCOM-7195) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by nuzil** [comment]
Hi @sivaschenko 
I meant this functional test: 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/27399/080f44f286f5263211409ffc95dc6e3f/Functional/allure-report-ce/index.html#suites/8187718e2fd144987673ef34ee62b41b/f6ed43ce96fd1909/

For me looks like related to Modal windows issue

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

When clicking outside of the Search Adobe Stock area, the _"Save Preview"_ window is closed, and the image is not saved into Media Gallery
PR_27399

**Comment by sivaschenko** [comment]
@nuzil updating branch to rerun the tests

**Review by nuzil — APPROVED** [review]
Failed tests green now. Looks good

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-7195](https://jira.corp.magento.com/browse/ENGCOM-7195) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE

**Comment by engcom-Echo** [comment]
Failed integration tests not related to the changes in this PR

**Pull request merged**
