### PR TITLE
Implement ActionInterface for /checkout/sidebar/removeItem

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This is a part of the process of introducing implementations of `ActionInterface`.

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @Bartlomiejsz. Thank you, good job. I would suggest rebuilding the unit test and use data providers since we have a plenty of duplicated lines there. However, overcomplicating such PRs with unit tests refactoring is not necessary.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7221](https://jira.corp.magento.com/browse/ENGCOM-7221) has been created to process this Pull Request

**Comment by rogyar** [comment]
Failing functional tests are not related to the current PR

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
