### PR TITLE
Base price storage website price mode

### LINKED ISSUE #30132: [Issue] Base price storage website price mode
This issue is automatically created based on existing pull request: magento/magento2#30126: Base price storage website price mode

---------

Fix V1/products/base-prices endpoint to update prices for Catalog Price Mode - Website

### Description (*)
V1/products/base-prices endpoint does not work with Catalog Price Mode - Website
Function was added to affect prices for all store views inside changed website

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by wassuupp**
### Fix V1/products/base-prices endpoint to update prices for Catalog Price Mode - Website
V1/products/base-prices endpoint does not work with Catalog Price Mode - Website
Function was added to affect prices for all store views inside changed website

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/30132

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by wassuupp** [comment]
@magento run all tests

**Comment by wassuupp** [comment]
@magento run WebAPI Tests

**Comment by nuzil** [comment]
@magento run WebAPI Tests

**Comment by nuzil** [comment]
@magento run WebAPI Tests

**Comment by nuzil** [comment]
@magento run WebAPI Tests

**Comment by nuzil** [comment]
@magento run WebAPI Tests

**Comment by nuzil** [comment]
@magento run WebAPI Tests

**Comment by nuzil** [comment]
@magento run WebAPI Tests

**Comment by nuzil** [comment]
@magento run WebAPI Tests

**Comment by nuzil** [comment]
@magento run WebAPI Tests

**Comment by nuzil** [comment]
@magento run all tests

**Comment by nuzil** [comment]
@magento run all tests

**Review by nuzil — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-8907](https://jira.corp.magento.com/browse/ENGCOM-8907) has been created to process this Pull Request
:eight_spoked_asterisk: @nuzil, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@wassuupp thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VladimirZaets** [comment]
@adobe give me 2.4-develop instance

**Comment by VladimirZaets** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
@wassuupp Some tests are failing for e.g static tests. Please look into that.

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Bravo** [comment]
@wassuupp @nuzil @engcom-Hotel Thanks for your contribution!
I will work on failed static test for this issue.

**Comment by engcom-Bravo** [comment]
@magento run Static Tests

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi @nuzil  ,

I have updated PR.
Requesting you for review.

Thank You!

**Comment by nuzil** [comment]
Looks good, thanks!

**Review by nuzil — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-8907](https://jira.corp.magento.com/browse/ENGCOM-8907) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@wassuupp thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
Hi @wassuupp & @nuzil Thanks for your contribution and collaboration!

I have tried to identify the issue in multiple ways, but couldn't reproduce.

**Scenario 1 :** 
1. Kept the default setting catalog price set to _Website_ and with one default website.
2. Created a new simple product set the price to one particular value
3. Executed the request as shown in below screenshot to change the price of the product to 999
image
4. Re indexed, cleaned & flushed properly.
Observation: Checked the reflected price of the product in Product Catalog and Product Details pages. Updated price thru API request has been updated successfully. No issues noticed

**Scenario 2 :** 
1. Kept the default setting catalog price set to _Website_ and with two websites having different domains (One default website and other created as French store like _local.magento2.com_ and _local.magento2.fr_).
2. Created a new simple product set the price 2 different prices to each websites
3. Executed the same above screenshot requests as shown in above screenshots changing their store id and unique prices for each websites

Observation: Checked the reflected prices in both the websites' Product Catalog and Product Details pages. Updated prices thru API request have been updated successfully. No issues noticed

Kindly tell me what is the issue noticed exactly and how do I reproduce it please!

**Comment by engcom-Alfa** [comment]
> Hi @wassuupp & @nuzil Thanks for your contribution and collaboration!
> 
> I have tried to identify the issue in multiple ways, but couldn't reproduce.
> 
> **Scenario 1 :**
> 
> 1. Kept the default setting catalog price set to _Website_ and with one default website.
> 2. Created a new simple product set the price to one particular value
> 3. Executed the request as shown in below screenshot to change the price of the product to 999
>    image
> 4. Re indexed, cleaned & flushed properly.
>    Observation: Checked the reflected price of the product in Product Catalog and Product Details pages. Updated price thru API request has been updated successfully. No issues noticed
> 
> **Scenario 2 :**
> 
> 1. Kept the default setting catalog price set to _Website_ and with two websites having different domains (One default website and other created as French store like _local.magento2.com_ and _local.magento2.fr_).
> 2. Created a new simple product set the price 2 different prices to each websites
> 3. Executed the same above screenshot requests as shown in above screenshots changing their store id and unique prices for each websites
> 
> Observation: Checked the reflected prices in both the websites' Product Catalog and Product Details pages. Updated prices thru API request have been updated successfully. No issues noticed
> 
> Kindly tell me what is the issue noticed exactly and how do I reproduce it please!

Also tried executing post request kept the store_id = 0 and there are 2 websites, where the default price value properly updated only in case of _All stores views_ scope without disturbing other store level prices.

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Since the PR changes not fixed the issue mentioned in the [above-comment](https://github.com/magento/magento2/pull/32371#issuecomment-947348211), moving it to _Changes Requested_

**Comment by engcom-Charlie** [comment]
Hi @wassuupp,

Thank you for your contribution!

@engcom-Alfa, will look into [this](https://github.com/magento/magento2/pull/32371#pullrequestreview-784023629) issue.

Thank you!

**Comment by engcom-Charlie** [comment]
Hi @engcom-Alfa,

Since there is no description present in this PR as well as in issue, I had a look on the committed versions.

On the basis of the PR code changes below is the aim of this PR.

**Steps to Reproduce:**
1. Setup magento 2.4-develop 
2. Create multiple stores and store views against one website. Store1, Store2 and storeview1, storeview2 respectively
3. Create one product and set its price. Or take any product from Sample product. Eg. sky: LEDTV Price: 4000
4. Execute rest/default/V1/products/base-prices endpoint 
{
  "prices": [
    {
      "price": 4001,
      "store_id": 1,
      "sku": "LEDTV",
      "extension_attributes": {}
    }
  ]
}
5. Go to product edit page in admin
6. The price is getting reflected only on the storeview which is mentioned in endpoint. It is not getting reflected on the other 2 stores which created in point 2 against the same website.

Eg. Main Website is having Default store view. Create 2 more stores. After executing base-prices endpoint the price is getting updated only the on Default store view"store_id": 1,

**Expected Result:**
After following steps till point 6, The new prices should get reflected on all the stores which are present under the website of store id passed in endpoint

**Before Fix:**
I have tried this scenario on 2.4-develop branch the price is getting updated only on provided store. 

**Actual result After Fix**
I have tested the PR branch. PR branch is showing the behaviour of Expected Result.

image


image

image

**Comment by engcom-Charlie** [comment]
As per the process, since the PR raised and approved by same community contributor ie. @nuzil, requesting other community members to review the PR again.

So moving this PR to Pending Review.

Thank you!

**Comment by wassuupp** [comment]
@engcom-Charlie , @engcom-Alfa . Excuse for the lack of description. 
1. Switch price mode to "Website".
2. Create at least one additional store view inside website which you would like to be tested.
3. Change price for website product using API request.
4. Open this product using admin for one store view, then for another store view.
You`ll observe that price was changed only for default store view, despite on checkbox "Use Default Value" value.

**Comment by nuzil** [comment]
@engcom-Charlie  @engcom-Alfa 
Hey guys, can I ping you and ask for update here?

**Comment by engcom-Alfa** [comment]
> @engcom-Charlie @engcom-Alfa Hey guys, can I ping you and ask for update here?

HI @nuzil Delayed due to various reasons and apologise please!
It is being discussed and will be progressed faster tomorrow
Thanks for your patience

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Have a Magento installed with latest 2.4-develop code updates
2. Make sure to create multi stores, and 1 store having at least 2 store views as shown in below screenshot (make sure store websites are working fine!).
image

**Manual testing scenario:**

1. Admin login: Stores> Configuration> Catalog> Catalog> Price : Set Catalog Price Mode - Website

2. Create a new product that is linked to all 3 websites
 
3. View the product edit pages in admin side and check given price is set with all websites scope.

4. Rest API - Request a Post call with rest endpoints - **_{{MagentoInstance}}/rest/default/V1/products/base-prices_**; Where the request body has to be like: `{
"prices": [
{
"price": 22,
"store_id": 2,
"sku": "BasePrice12",
"extension_attributes": {}
}
]
}` Where the store_id should be as per the store_id available for created 2 store views' store.

5. Admin : Product edit page> Change the scope of the store view 1 i.e under one store, and check the updated price.

6. Change the scope of the store view 2 i.e under same one store, and check the updated price.


**Before:** :heavy_multiplication_x: Price was not getting updated in both the store views under one store.

**After:** :heavy_check_mark: Price is getting updated in both the store views under one store.

**Review by ishakhsuvarov — APPROVED** [review]

**Pull request merged**
