### PR TITLE
Add validation in catalog rule and shopping cart rule form

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

Some fields in Catalog Rule and Shopping Cart Rule form should have more validations (Priority, Uses per Coupon, Uses per Customer, Discount Amount, Maximum Qty Discount is Applied To,  Discount Qty Step (Buy X))

### Manual testing scenarios (*)

1. Go to backend
2. Marketing-> Cart Price Rule -> Add New Rule
  Marketing-> Catalog Price Rule -> Add New Rule
3. Check validation in some fields (Priority, Uses per Coupon, Uses per Customer, Discount Amount, Maximum Qty Discount is Applied To,  Discount Qty Step (Buy X))

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rodrigowebjump** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [new Magento instance](https://pr-25172.instances.magento-community.engineering).
Admin access: [https://pr-25172.instances.magento-community.engineering/admin](https://pr-25172.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rodrigowebjump — APPROVED** [review]
Hi @edenduong 

Thanks for your contribution.

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-6143](https://jira.corp.magento.com/browse/ENGCOM-6143) has been created to process this Pull Request
:eight_spoked_asterisk: @rodrigowebjump, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @edenduong,
during testing, we faced the issue. We think that the validation for "Priority" should be "`validate-digits`" instead "`validate-numbers`" because after saving the rule, the value (2,36 for example) trimmed to an integer (2) for "Priority".

And due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

@edenduong Could you take a look?

Thanks!

**Comment by edenduong** [comment]
@engcom-Alfa: I have changed the source code and Cover my fix with MFTF Test. Please check it again. Thanks.

**Review by VladimirZaets — APPROVED** [review]

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6143](https://jira.corp.magento.com/browse/ENGCOM-6143) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
