### PR TITLE
 Blank line found at start of control structure 

### PR DESCRIPTION
**Pull request by mayankzalavadia**
Blank line found at start of control structure 

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by orlangur** [comment]
Please force push a branch so that there is no invalid https://github.com/magento/magento2/pull/11117/commits/cd11191c095e6e0d46fc2074b731413f41bfd4f5 commit.

> Blank line found at start of control structure

Please provide more details on this into PR description - is this some PhpStorm inspection?

**Comment by mayankzalavadia** [comment]
I have use magento-coding-standard tool for check.

**Comment by orlangur** [comment]
Some of https://github.com/magento-ecg/coding-standard https://github.com/magento/marketplace-eqp?

Changes related to "Blank line found at start of control structure" look useful to me, not sure if there are any plans to enforce core with this set of sniffs.

**Comment by mayankzalavadia** [comment]
I have use https://github.com/magento/marketplace-eqp tool for testing.
Can you please let me know this changes is okey or not.? So, next time I'll take care of this things before commit.

**Comment by orlangur** [comment]
It looks like you continued work from branch related to other PR.

Please squash changes into single commit with `Blank line found at start of control structure` message not touching the `phtml` file I mentioned.

I can assist you with exact `git` commands if needed.

**Comment by mayankzalavadia** [comment]
Yes, Can you please assist me with exact `git` commands. I have also tried to force push a branch.

**Comment by orlangur** [comment]
1. `git checkout develop`
2. Assure there are no changes in working tree with `git status`
3. `git checkout -b develop-old`
4. `git branch -D develop`
5. `git checkout mainline/develop` - or however you call the https://github.com/magento/magento2/ remote instead of "mainline"
6. `git checkout -b develop`
7. `git merge --squash develop-old`
8. `git reset app/code/Magento/LayeredNavigation/view/frontend/templates/layer/filter.phtml` so that it will not be a part of new commit
9. `git commit -m"Clean up code but getting read of 'Blank line found at start of control structure' coding standard violations"`
10. `git push -f my` - where "my" is the name of remote corresponding to your repo

**Comment by mayankzalavadia** [comment]
I have done as you mention. Now is it okay or I need do any other thing?

**Comment by orlangur** [comment]
> Commits 4

I don't see the changes, there should be only one commit after you did mentioned steps.

Please post CLI commands you entered together with their output here.

**Comment by mayankzalavadia** [comment]
root@mayank:/var/www/html/contribution/m220$ git checkout develop
Already on 'develop'
root@mayank:/var/www/html/contribution/m220$ git status
On branch develop

It took 5.05 seconds to enumerate untracked files. 'status -uno'
may speed it up, but you have to be careful not to forget to add
new files yourself (see 'git help status').
nothing to commit, working directory clean
root@mayank:/var/www/html/contribution/m220$ git checkout -b develop-old
fatal: A branch named 'develop-old' already exists.
root@mayank:/var/www/html/contribution/m220$ git branch -D develop
error: Cannot delete the branch 'develop' which you are currently on.
root@mayank:/var/www/html/contribution/m220$ git checkout -b develop--old
Switched to a new branch 'develop--old'
root@mayank:/var/www/html/contribution/m220$ git branch -D develop
Deleted branch develop (was 81134b7).
root@mayank:/var/www/html/contribution/m220$ git checkout origin/develop
Note: checking out 'origin/develop'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 81134b7... Blank line found at start of control structure
root@mayank:/var/www/html/contribution/m220$ git checkout -b develop
Switched to a new branch 'develop'
root@mayank:/var/www/html/contribution/m220$ git merge --squash develop--old
 (nothing to squash)Already up-to-date.
root@mayank:/var/www/html/contribution/m220$ git merge --squash develop-old
 (nothing to squash)Already up-to-date.
root@mayank:/var/www/html/contribution/m220$ git merge --squash develop--old
 (nothing to squash)Already up-to-date.
root@mayank:/var/www/html/contribution/m220$ git reset app/code/Magento/LayeredNavigation/view/frontend/templates/layer/filter.phtml
root@mayank:/var/www/html/contribution/m220$ git commit -m "Clean up code but getting read of 'Blank line found at start of control structure' coding standard violations"
On branch develop

It took 10.01 seconds to enumerate untracked files. 'status -uno'
may speed it up, but you have to be careful not to forget to add
new files yourself (see 'git help status').
nothing to commit, working directory clean
root@mayank:/var/www/html/contribution/m220$ git push -f origin develop
Everything up-to-date
root@mayank:/var/www/html/contribution/m220$

**Comment by mayankzalavadia** [comment]
Please check above my last comment. Is it okay or I need to do anything else?

**Comment by orlangur** [comment]
> root@mayank:/var/www/html/contribution/m220$ git checkout origin/develop
Note: checking out 'origin/develop'.

It looks like `origin` is name of your repository remote. You need to add https://github.com/magento/magento2.git as another remote.

`git remote add mainline https://github.com/magento/magento2.git`
`git fetch mainline`
`git remote rename origin my`

And then repeat steps using "mainline" and "my" remotes names.

**Comment by orlangur** [comment]
Great! 👍 Seems like it worked now.

**Comment by mayankzalavadia** [comment]
Thank you for assisting me.

**Comment by orlangur** [comment]
@mayankzalavadia please use another branch than `develop` for unrelated changes.

`git checkout -b NEW-BRANCH` to keep unrelated commit in another branch and then

`git checkout develop`
`git reset --hard 3fa78fd`
`git push -f my`

**Pull request merged**
