### PR TITLE
FIX for issue #21916 - Elasticsearch6 generation does not exist

### PR DESCRIPTION
**Pull request by phoenix128**
Magento was not checking concrete class while applying plugins

### Description (*)
If the pluginized class was virtualtyped by a class with name ending with an autogenerated suffix and without the implementation of the base concrete class, the di compile was failing.

This PR prevents code generation for VirtualTypes.

### Fixed Issues
1. magento/magento2#21916: Elasticsearch6 generation does not exist
2. magento/magento2#21976: Magento doesn't work after upgrade from 2.3.0 to 2.3.1

### Additional
- Added test coverage for autogeneration on virtual types
- Fixed too broad tests check not verifying the successful exit of `generateClass`
- Small test codestyle adjustments

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4620](https://jira.corp.magento.com/browse/ENGCOM-4620) has been created to process this Pull Request

**Comment by hostep** [comment]
Hi @phoenix128 

I'm currently upgrading a shop of ours to Magento 2.3.1, this shop has the particular Amasty Shopby module installed, currently version 2.11.1 (not updated to 2.11.2 yet which is supposed to fix this problem, even though that's probably a workaround?).

I then tested this fix you are proposing, but I'm still seeing the same error:
```
$ bin/magento setup:di:compile
Compilation was started.
Interceptors generation... 4/7 [================>-----------]  57% 10 secs 124.0 MiB
In Generator.php line 218:

  Source class "\Magento\Elasticsearch6\Model\Adapter\FieldMapper\ProductField" for "Magento\Elasticsearch6\Model\Adapter\FieldMapper\ProductFieldMapper" generation does not exist.


setup:di:compile
```

I thought we didn't need to upgrade the Amasty module and only apply this fix as a patch to circumvent the problem, but that doesn't seem to be the case?

If you need more info from me for this particular problem, I will gladly provide it :)

**Comment by phoenix128** [comment]
@hostep, @rogyar , this is a WIP PR, the issue is divided in two different phases and I only fixed the first one. I am almost finished.

**Comment by hostep** [comment]
Nice one @phoenix128!

I can confirm this fixes the problem with the amasty/shopby module (version 2.11.1).

It also looks like `setup:di:compile` runs a couple of seconds faster due to this change, so that's also nice.

Just an observation, not sure if this is a problem or not, but before this change, the following files got generated, and after the change this no longer happens (tested on Magento OS 2.3.1 - developer mode):
- `generated/code/Magento/MysqlMq/Model/Driver/Bulk/ExchangeFactory.php`
- `generated/code/Magento/Ui/Config/Converter/StorageConfig/Proxy.php`
- `generated/code/Magento/Ui/Config/Converter/Buttons/Proxy.php`
- `generated/code/Magento/Ui/Config/Converter/Item/Proxy.php`
- `generated/code/Magento/Ui/Config/Converter/Actions/Proxy.php`

**Comment by phoenix128** [comment]
Hello @hostep,
I know and I expected this, IMO the previous behaviour was wrong.

If you take for example `Magento\Ui\Config\Converter\Item\Proxy` you will see it is a virtual type defined in `Magento/Ui/etc/di.xml`.

So, since my patch prevents the code generation of VirtualTypes ending with a generation suffix (`Proxy` in our case), this should be the expected behaviour.

I would like some Magento architect to confirm this aspect anyway.

**Comment by phoenix128** [comment]
I added test coverage for virtual types code generation.
I also fixed a couple of too broad tests not checking the exit status of `generateClass` method.

Seems like we also had a small performance boost while DI compiling as a side effect.

**Review by melnikovi — APPROVED** [review]

**Pull request merged**
