### PR TITLE
Fix 22085

### PR DESCRIPTION
**Pull request by geet07**
### Fixed Issues (if relevant)

1. magento/magento2#<22085>: Not focusable moreButton on Catalog page using Tab

### Manual testing scenarios (*)

1. You need to have a product with more than 3 swatches option
Option in
Stores -> Configuration -> Catalog / Catalog -> Swatches per Product set to 3
Show Swatches in Product List set to Yes
2.  In the products list hover on more link, now it is focusable  

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by davidverholen** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @davidverholen. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @davidverholen, here is your [new Magento instance](https://pr-23166.instances.magento-community.engineering).
Admin access: [https://pr-23166.instances.magento-community.engineering/admin](https://pr-23166.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by davidverholen — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @davidverholen, thank you for the review.
[ENGCOM-5231](https://jira.corp.magento.com/browse/ENGCOM-5231) has been created to process this Pull Request

**Comment by soleksii** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @stoleksiy. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @stoleksiy, here is your [new Magento instance](https://pr-23166.instances.magento-community.engineering).
Admin access: [https://pr-23166.instances.magento-community.engineering/admin](https://pr-23166.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by soleksii** [comment]
Hi @geet07 ! According to the magento documentation, the styles for the links should be underlined (see [here](https://devdocs.magento.com/guides/v2.3/pattern-library/navigation/links/links.html)).
Should be like this:

screen

With PR changes actual result is:

screen2

@VladimirZaets  Is this the expected result?

Thanks!

**Review by orlangur — CHANGES_REQUESTED** [review]
Please squash changes into a single commit so that we have perfectly clean history 😉

Also, no unrelated tickets must be present in commit history in the first place.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-5313](https://jira.corp.magento.com/browse/ENGCOM-5313) has been created to process this Pull Request
:eight_spoked_asterisk: @orlangur, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
Hi, @geet07. I think the problem is still not fixed 
according to @stoleksiy comment. Actual result:
te
Could you take a look?

**Comment by geet07** [comment]
> Hi, @geet07. I think the problem is still not fixed
> according to @stoleksiy comment. Actual result:
> te
> Could you take a look?

Hi @engcom-Delta, @stoleksiy 
Thank for your message.

I have checked with this, but More button is not a link, it is not containing any URL for the redirect. it's using for the only javascript. So as my understanding it is correct. Please let me know if you have any concern here.

**Comment by geet07** [comment]
Hi @engcom-Delta,  @engcom-Golf :
Can you please test this issue. And also check my last comment and let me know if I am wrong here.

**Review by orlangur — CHANGES_REQUESTED** [review]
@geet07, as per Slack discussion

https://devdocs.magento.com/guides/v2.3/pattern-library/controls/buttons/buttons.html
> When Not to Use
> Do not use buttons to indicate a link to more information or to a task not related to primary flow.

I believe we should treat “More” as a link here and thus make it underlined.

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

**Comment by geet07** [comment]
> @geet07, as per Slack discussion
> 
> https://devdocs.magento.com/guides/v2.3/pattern-library/controls/buttons/buttons.html
> 
> > When Not to Use
> > Do not use buttons to indicate a link to more information or to a task not related to primary flow.
> 
> I believe we should treat “More” as a link here and thus make it underlined.
> 
> After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history

Hi @orlangur, 

Finally I have done git squash :-) , Can you please review and let me know if there is an issue or any changes required

**Comment by geet07** [comment]
Hi @orlangur 

Can you please review the change request.

**Comment by geet07** [comment]
Hi @orlangur,

As per you requested, can you please review the changes

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-5313](https://jira.corp.magento.com/browse/ENGCOM-5313) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
