### PR TITLE
Webapi Swagger schema generation fail in case when Get endpoint has param with Extension Attributes [Case#2]

### PR DESCRIPTION
**Pull request by swnsma**
### Description (*)
Apply fix refactoring of already applied fix.

### Fixed Issues (if relevant)
1. magento/magento2#24626: Webapi Swagger schema generation fail in case when Get endpoint has param with Extension Attributes [Case#2]

### Manual testing scenarios (*)
See issue description.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @swnsma. Thank you for your collaboration. Could you cover this fix with automated tests, please? 
The unit test within a scope of the [existing](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Webapi/Test/Unit/Model/Rest/Swagger/GeneratorTest.php) test will work perfectly. 

Thank you!

**Comment by swnsma** [comment]
HI @rogyar,
Thank you for your review!
I have added test case to check scenario to test the case which this PR fix.

**Review by novikor — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @novikor, thank you for the review.
[ENGCOM-5853](https://jira.corp.magento.com/browse/ENGCOM-5853) has been created to process this Pull Request
:eight_spoked_asterisk: @novikor, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:**
before

**After:**
after

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-5853](https://jira.corp.magento.com/browse/ENGCOM-5853) has been created to process this Pull Request

**Pull request merged**
