### PR TITLE
Use English consistently for the Swiss regions names

### LINKED ISSUE #32602: [Issue] Use English consistently for the Swiss regions names
This issue is automatically created based on existing pull request: magento/magento2#32553: Use English consistently for the Swiss regions names

---------
### Description

Some of the Swiss regions are using a name that is not in English nor in the official language of the Canton. [Source](https://en.wikipedia.org/wiki/Cantons_of_Switzerland#List).

### Manual testing scenarios

1. On the address create/edit form, select Switzerland as country;
2. There is no `Geneve` in the regions list.

### Questions or comments

Disclaimer: I am not Swiss neither live in the country, I just happen to have a few customers mentioning that the region names weren't straight forward.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kassner**
### Description

Some of the Swiss regions are using a name that is not in English nor in the official language of the Canton. [Source](https://en.wikipedia.org/wiki/Cantons_of_Switzerland#List).

### Manual testing scenarios

1. On the address create/edit form, select Switzerland as country;
2. There is no `Geneve` in the regions list.

### Questions or comments

Disclaimer: I am not Swiss neither live in the country, I just happen to have a few customers mentioning that the region names weren't straight forward.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32602: Use English consistently for the Swiss regions names

### CODE REVIEW

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
Removed assignee, as the month already passed, and this is high priority PR

**Review by orlangur — APPROVED** [review]
✅ All Swiss regions checked as per https://en.wikipedia.org/wiki/Cantons_of_Switzerland#Names_in_national_languages

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-9115](https://jira.corp.magento.com/browse/ENGCOM-9115) has been created to process this Pull Request
:eight_spoked_asterisk: @orlangur, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @kassner , @orlangur 
Thanks for the contribution!

:x: QA not Passed

_Replaced region names of Swiss are not reflected_

**Manual Scenario Steps**

1. Upgraded to the PR request;
2. Logged into the application front-end;
3. Navigated to the My Account Edit Address;
4. Selected the Switzerland country;
5. Tried to select the state/region;

**:x: Actual result**
- image

- Found **Genf**; But not Geneva
- 

**:heavy_check_mark: Expected result**
- Should be replaced to Geneva
- Other updated names also not reflected

And the comment to ask for fix
Can you please cross check once about it if it is reflecting from your end @kassner , Or anything more required to update in the code!

**Comment by kassner** [comment]
Well, this should only work for a fresh install with the code changes. I don't think it's a good idea to create a patch to update already running installations, but you tell me.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Require to have this fresh PR fix instance to be installed with sample data.
2. Create a new front end user.

**Manual testing scenario:**

1. Login to the front end user, and navigate to the My account > Address book section.

2. Select country as "Switzerland" and check all the renamed states
 
3. Add product to cart and  navigate to Shipping address page > Add new shipping address

4. Select country as "Switzerland" and check all the renamed states


**Before:** :heavy_multiplication_x: State names "Freiburg", "Genf", "Luzern", "Neuenburg", "Tessin" and "Waadt" were existing by selecting the country "Switzerland"
> image


**After:** :heavy_check_mark:  State names "Friburg", "Geneva", "Lucerne", "Neuchâtel", "Ticino" and "Vaud" are existing by selecting the country "Switzerland"
> image

**Comment by ihor-sviziev** [comment]
@engcom-alfa, does it works for installations, when we installed Magento on clean 2.4-develop branch, and then switched to this branch?

**Comment by engcom-Alfa** [comment]
Hi @ihor-sviziev 
It works only if we install PR branch directly.
If we first install 2.4-develop working instance and then if we remote-fetch to the PR fix branch, fixed code is still does not work.

**Comment by ihor-sviziev** [comment]
@engcom-Alfa, I think it should be fixed, as it won’t work for existing magento installations

**Comment by engcom-Alfa** [comment]
HI @kassner  As @ihor-sviziev suggested above, it should be fixed even by switching to the PR fix version from 2.4-develop instance. So, I am moving the PR to _changes requested_. Kindly take a look on it.
Well, even the PR fix should have all the automated scripts passed. Request you to take a look at it as well.

**Comment by kassner** [comment]
I don't have the energy to deal with this, so closing.

If anyone else wants to work on it, feel free to build on top of my current PR.

**Comment by engcom-Alfa** [comment]
Thanks for for your contribution @kassner!
Thank you for carrying it forward @ihor-sviziev , I will look into that new PR.

**Pull request closed without merging**
