### PR TITLE
Added missing aclResource attribute to Backend Header AdminNotification Toolbar Block

### LINKED ISSUE #29067: [Issue] Added missing aclResource attribute to Backend Header AdminNotification Toolbar Block
This issue is automatically created based on existing pull request: magento/magento2#28343: Added missing aclResource attribute to Backend Header AdminNotification Toolbar Block

---------
### Preconditions: (*)
Admin notification toolbar entry (bell) is visible despite admin user does not have role resource permissions to see it.

### Steps to reproduce (*)
1. Create Admin Role with Resource Access set to Custom;
2. Edit Resources Tree so that System->Other Settings->Notifications->Show Toolbar is unchecked;

3. Save Role;
4. Refresh caches and re-login;

**Actual Result:** :heavy_multiplication_x: The admin notification bell icon is still visible

**Expected Result:** :heavy_check_mark: As admin user you should not see admin notifications bell icon 

Screenshot from 2020-07-10 10-09-01

### Questions or comments
n/a

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by denysbabenko**
### Description (*)
Admin notification toolbar entry (bell) is visible despite admin user does not have role resource permissions to see it.

### Related Pull Requests
n/a

### Fixed Issues (if relevant)
n/a

### Manual testing scenarios (*)
1. Create Admin Role with Resource Access set to Custom
2. Edit Resources Tree so that System->Other Settings->Notifications->Show Toolbar is unchecked
3. Save Role
4. Refresh caches and re-login
Expected result: as admin user you should not see admin notifications bell icon 
Actual result: it is visible 

### Questions or comments
n/a

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29067: Added missing aclResource attribute to Backend Header AdminNotification Toolbar Block

### CODE REVIEW

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @denysbabenko. Thank you for your collaboration. 
According to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered by automated tests. 

Could I kindly ask you to cover your change using MFTF test? 

There's a [documentation](https://devdocs.magento.com/mftf/docs/introduction.html) of the framework itself. 

You can also check some examples from the recently merged PRs:

https://github.com/magento/magento2/pull/27371/files
https://github.com/magento/magento2/pull/27343/files
https://github.com/magento/magento2/pull/27029/files

Here's also a shortlist of best practices for creating MFTF tests. 

https://github.com/magento/magento-functional-tests-migration/wiki/Best-practices

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7777](https://jira.corp.magento.com/browse/ENGCOM-7777) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@denysbabenko thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Create Admin Role with Resource Access set to Custom;
2. Edit Resources Tree so that System->Other Settings->Notifications->Show Toolbar is unchecked;



3. Save Role;
4. Refresh caches and re-login;

**Before:** :heavy_multiplication_x: The admin notification bell icon is still visible



**After:** :heavy_check_mark: The admin notification bell icon isn't visible

Screenshot from 2020-07-10 10-09-01

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi, @sidolov can you please help to understand why tests failed without reports?
Thank you.

**Comment by sidolov** [comment]
@engcom-Charlie the build results were removed from the history, I have merged latest changes and started builds, let's wait and take a look ar the latest run.

**Comment by sidolov** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi, @sidolov can you please take a look at failed builds?
Thank you.

**Comment by sidolov** [comment]
@engcom-Charlie here is the build output:
```
09:26:37 [Build Functional CE]  MFTF Annotations Static Check: Errors found across 1 file(s). Error details output to /var/www/html/dev/tests/acceptance/tests/_output/static-results/mftf-annotations-static-check.txt
09:26:37 [Build Functional CE]  Total execution time is 0.080599069595337 seconds.
09:26:37 [Build Functional CE] 
[Pipeline] [Build Functional CE] echo
09:26:37 [Build Functional CE] FAILURE: Mftf tests static check -> exit code=1
```

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
@denysbabenko thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request merged**
