### PR TITLE
magento/magento2#23481: Billing/Shipping Address edit form design update from order backend

### PR DESCRIPTION
**Pull request by alexey-rakitin**
### Description (*)
- Form wrapper html tag changed from 'fieldset' to 'div' to avoid standard fieldset tag borders
- Added 'admin__fieldset' class to form for standard admin styles to work properly

### Fixed Issues (if relevant)

1. magento/magento2#23481: Billing/Shipping Address edit form design update from order backend
2. magento/magento2#19805: Sales order Address Information edit form layout design improvement.

### Manual testing scenarios (*)

1. Go to Admin -> Sales -> Invoices -> Click on View -> Address Information section -> Billing Address/Shipping Address 
2. Click on Edit
3. Address form should look according to Magento 2 Admin form pattern library (labels to the left of inputs)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by vsevolod-tarasov — APPROVED** [review]

**Review by krzksz — CHANGES_REQUESTED** [review]
This PR duplicates work done within https://github.com/magento/magento2/pull/25548

**Comment by krzksz** [comment]
Hey @alexey-rakitin, after reviewing your changes I'm actually leaning towards your solution to this styling problem but let me compare the looks of the forms first.

**Comment by krzksz** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @krzksz. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @krzksz, here is your [new Magento instance](https://pr-25699.instances.magento-community.engineering).
Admin access: [https://pr-25699.instances.magento-community.engineering/admin](https://pr-25699.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by krzksz — CHANGES_REQUESTED** [review]
Everything looks good, but the margin between notice and form title is missing:
obraz

**Comment by alexey-rakitin** [comment]
Hi, @krzksz, please check amended commit. I added messages container, now margin is ok.

**Review by krzksz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-6328](https://jira.corp.magento.com/browse/ENGCOM-6328) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Foxtrot** [comment]
Hello, @alexey-rakitin. Thank you for contribution. Unfortunately, we cannot merge your PR until changes are covered with tests.

**Comment by alexey-rakitin** [comment]
Hello, @engcom-Foxtrot . With which tests should I cover this PR? MFTF?

**Review by VladimirZaets — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
