### PR TITLE
Navigation dropdown caret icon.

### PR DESCRIPTION
**Pull request by tejash-wagento**
### Fixed Issues (if relevant)

1. magento/magento2#15220: 2.2.4: navigation dropdown caret icon missing (jQuery UI) #15220

### Manual testing scenarios

1. Add icon in navigation

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16082) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=16082) before we can accept your contribution.<br/><hr/>**tejash** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by magento-engcom-team** [comment]
Hi @tejash-wagento. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on Pull Request changes
- `@magento-engcom-team give me new test instance` - deploy **NEW** test instance based on Pull Request changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy Vanilla Magento instance for Issue or Pull Request

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by VladimirZaets** [comment]
Hi, @tejash-wagento, I took your PR into processing, thank you for collaboration.

**Comment by magento-engcom-team** [comment]
@tejash-wagento thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @tejash-wagento. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.6 release.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Comment by jhruehl** [comment]
@magento-engcom-team @VladimirZaets  Can you please tell me why this got merged? I don't even see a reason given here. The only thing I see that the menu in our store have stupid "ui-icon-carat-1-e" icons now shown right next to the submenu entries.

You don't merge a simple if-clause and make a huge fuss about it, which just prevents empty strings as url keys on import, but merge this without any doubt.

But compared to the other accepted merge, I checked today and had to clean up with a core patch, this actually could have a valid reason. So please tell me.

**Comment by jhruehl** [comment]
@tejash-wagento @magento-engcom-team @VladimirZaets  Sooo. What was the reason for this pull request? Please. I'm curious.

**Pull request merged**
