### PR TITLE
Fixed#18508 collect-totals API call not updating the selected shippingMethod

### PR DESCRIPTION
**Pull request by ramkishansuthar**
Update repository with latest changes

### Description (*)

Replaced $this->quoteRepository->save($quote->collectTotals()); with $quote->collectTotals() at set method function in Magento\Quote\Model\ShippingMethodManagement.

### Fixed Issues (if relevant)

1. magento/magento2#18508: collect-totals API call not updating the selected shippingMethod in collect-total request
2. ...

### Manual testing scenarios (*)

1. Tested it with multiple shipping methods.
2. Checked it with different payment methods in request payload.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ramkishansuthar. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by ramkishansuthar** [comment]
@magento-engcom-team give me test instance - deploy test instance based on PR changes

**Comment by magento-engcom-team** [comment]
Hi @ramkishansuthar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @ramkishansuthar, here is your [new Magento instance](https://pr-20945.instances.magento-community.engineering).
Admin access: [https://pr-20945.instances.magento-community.engineering/admin](https://pr-20945.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by ghost** [comment]
Hi @ramkishansuthar, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+magento2+20945), it will take less than a minute. </br>Your feedback will help us to improve contribution process.

**Pull request closed without merging**
