### PR TITLE
Improvement: Magento\Sales\Helper\Guest refactoring and bugfix

### PR DESCRIPTION
**Pull request by coderimus**
Dear Magento2,

This PR consists of several improvements and bug fixes. The main goal of it is to increase performance and logic side of the Magento\Sales\Helper\Guest. Please, review Description section for more information.

Looking forward to your reply,
Alex

### Description
The main improvements here are in the `Magento\Sales\Helper\Guest::getOrderRecord($incrementId)`  

1. Added `store_id` as filter to search criteria to improve logic/performance and due to this fact the `Magento\Sales\Helper\Guest::validateOrderStoreId($orderStoreId)` can be removed.

1. Replaced
```
        if ($records->getTotalCount() < 1) {
            throw new InputException(__($this->inputExceptionMessage));
        }
        $items = $records->getItems();
        return array_shift($items);
```
with
```
        $items = $records->getItems();
        if (empty($items)) {
            throw new InputException(__($this->inputExceptionMessage));
        }

        return array_shift($items);
```
This allows Magento to reduce the number of database queries because every time when the `getTotalCount()` is called it initiates the `getSize()` method which checks the `$this->_totalRecords` value but in this case it equals to `null` every new call because every new call begins after page load.

3. Moved `$this->hasPostDataEmptyFields($post)` to ternary operator because this is good to have all conditions according to order in one place.

4. Fixed typo `compareSoredBillingDataWithInput` to `compareStoredBillingDataWithInput`

5. Removed underscore `private $_storeManager;` to `private $storeManager;` (PSR-2: Property names SHOULD NOT be prefixed with a single underscore to indicate protected or private visibility.)

### Fixed Issues (if relevant)
No relevant issue.

### Manual testing scenarios
Those changes didn't change business logic. Only code improvement and, as a result, no manual testing scenarios.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=12893) <br/>All committers have signed the CLA.

**Comment by coderimus** [comment]
Hello @orlangur !

Thank you for your attention to my PR and self-assigned. Could you please update me with a possible date when you will have time to check it?

Looking forward to your reply,
Alex

**Comment by coderimus** [comment]
Hi @orlangur ,
Just want to send you a friendly reminder about this PR :) I see that you have a lot of work and you always review latest changes but when you will have a time, pls, check it.

**Review by orlangur — APPROVED** [review]
Hi @Coderimus,

> 3. Moved $this->hasPostDataEmptyFields($post) to ternary operator because this is good to have all conditions according to order in one place.

This changed logic a bit actually loading from cookie when it didn't load from cookie before but I didn't find any negative consequences of this.

No objections from implementation side, LGTM, small note on

> Those changes didn't change business logic. Only code improvement and, as a result, no manual testing scenarios.

actually, we need to perform manual testing to assure the changes didn't change the logic unless we determined it is covered with some automated tests.

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[MAGETWO-86399](https://jira.corp.magento.com/browse/MAGETWO-86399) has been created to process this Pull Request

**Pull request merged**
