### PR TITLE
[GraphQL] Fixed exposing special price

### PR DESCRIPTION
**Pull request by rogyar**
### Description (*)

This PR contains a fix for the scenario when GraphQL API exposes product special price when the special price period set for the future. 

### Fixed Issues (if relevant)

1. #30210 : Magento 2.4.0 graphql leak data on special price
2. #29631 : GraphQl Special Price Ignore's special price from to dates

### Manual testing scenarios (*)
1. Create a product with a special price
2. Set the special price From and To date for the far future
3. Use the following query to retrieve the information about special price (change the filter parameters for your setup)

```graphql
{
  products(filter: {name: {match: "Simple"}}) {
    items {
      name
      special_price
    }
  }
}
```

### Expected result 

```json
{
  "data": {
    "products": {
      "items": [
        {
          "name": "Simple",
          "special_price": null
        }
      ]
    }
  }
}
```

The `special_price` should be `null` in case if the current date is not in the period set for the special price.

### CODE REVIEW

**Comment by rogyar** [comment]
Working on the test coverage

**Comment by rogyar** [comment]
@magento run all tests

**Comment by rogyar** [comment]
I will get back to this PR tomorrow.

**Comment by rogyar** [comment]
@magento run all tests

**Comment by rogyar** [comment]
The failing tests don't seem to be related to the current change. We may proceed with the review.

**Review by eduard13 — APPROVED** [review]
Good job 👍

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8477](https://jira.corp.magento.com/browse/ENGCOM-8477) has been created to process this Pull Request

**Comment by eduard13** [comment]
@magento run Integration Tests, Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by eduard13** [comment]
@magento run Functional Tests EE

**Comment by eduard13** [comment]
@magento run Functional Tests EE

**Comment by cpartica** [comment]
@magento run all tests

**Review by cpartica — APPROVED** [review]

**Comment by cpartica** [comment]
@magento run all tests

**Pull request merged**
