### PR TITLE
Add missing index on "cms_block" table.

### PR DESCRIPTION
**Pull request by Wohlie**
### Description (*)
The table `cms_block` miss an index for the column `identifier` which is used to load CMS blocks out of the database:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Cms/Model/GetBlockByIdentifier.php#L47

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Wohlie** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9077](https://jira.corp.magento.com/browse/ENGCOM-9077) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@Wohlie thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by Den4ik — APPROVED** [review]
@Wohlie, thanks for contribution 👍

**Comment by Den4ik** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by Den4ik** [comment]
@sidolov I think this PR should be available as quality patch

**Pull request merged**
