### PR TITLE
Added patch for the upgrade issue from 2.4.2 to 2.4.3

### PR DESCRIPTION
**Pull request by konarshankar07**
### Description (*)

This PR will add the patch for the upgrade issue from 2.4.x to 2.4.3
### Related Pull Requests

https://github.com/magento/quality-patches/pull/60
### Release Notes

Fixes Upgrade Issue, While upgrade from Magento 2.4.2-p1 to Magento 2.4.3 for PayPal data patch

### Categories

Payments

### Manual testing scenarios (*)

1. Try to upgrade from magento 2.4.2 to 2.4.3

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by konarshankar07** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by m2-github-services** [comment]
@ihor-sviziev thank you for the review! We have changed pull request base branch in order to provide ability to merge current pull request and schedule quality patch delivery job.

**Comment by ihor-sviziev** [comment]
@sidolov the functional test is constantly failing. Could you help with it?

**Comment by ihor-sviziev** [comment]
image


Ok, test failure caused by down service:
https://www.currencyconverterapi.com/server-status
image

**Comment by sidolov** [comment]
@magento run Functional Tests CE

**Comment by m2-github-services** [comment]
@ihor-sviziev quality patch delivery job is successfully scheduled! Link to the quality patch tool pull request will be provided as soon as it's created

**Comment by m2-github-services** [comment]
Pull request with quality patch was successfully created, available by the link: magento/quality-patches#61

**Pull request merged**
