### PR TITLE
Fix Filter Customer Report Review

### PR DESCRIPTION
**Pull request by osrecio**
Remove `where` part from SelectCountSql when grid is filtered

### Description
When customer is filtered in `Reports -> Review -> By Customer`, Grid tries to get number of rows but how you add a custom name  that concats `customer.firstname` and `customer.lastname` and you need remove where from SelectCountSql

### Fixed Issues (if relevant)
1. magento/magento2#10301: Customer review report search Bug in 2.1.x, 2.2

### Manual testing scenarios
1. Go to Admin
2. Reports -> Review -> By Customer
3. Filter customer

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by ishakhsuvarov** [comment]
Hi @osrecio 
Please change target branch to `2.3-develop` instead of develop for this PR.

**Comment by osrecio** [comment]
Changed

**Comment by ishakhsuvarov** [comment]
@osrecio 
Thank you for fast response. It would be also nice to include tests for the updated behavior or update existing ones. Do you need any help with that?

**Comment by osrecio** [comment]
I will work on it

**Comment by osrecio** [comment]
@ishakhsuvarov Added test to test functionality of `getSelectCountSql`

**Comment by ishakhsuvarov** [comment]
Hi @osrecio
I've changed the included test to the integration one, as initial unit test tested the mock object and was always green, regardless of fix presence.
Please let me know if you have any concerns regarding this.

Thank you.

**Comment by osrecio** [comment]
Seems like is ok. Thanks @ishakhsuvarov

**Pull request merged**
