### PR TITLE
Cache Elasticsearch field mappers per entity

### PR DESCRIPTION
**Pull request by aapokiiso**
### Description (*)

Currently the Elasticsearch FieldMapperResolver caches the first resolved field mapper into a private class property called `$fieldMapperEntity`. All subsequents calls to the `getEntity` method in the resolver will return the field mapper which was initialized first, regardless of the supplied `$entityType` argument. This prevents different entity types (say, manufacturer names or categories) from using their own field mapper. 

### Manual testing scenarios (*)

1. Create a custom search indexer for Elasticsearch in Magento 2:
```
<indexer id="analysis_certificate_search_fulltext" view_id="analysis_certificate_search_fulltext" class="MyCompany\AnalysisSearch\Model\Indexer\FulltextAnalysisIndexer">
    <title translate="true">Analysis Certificate Search</title>
    <description translate="true">Rebuild analysis certificate fulltext search index</description>
</indexer>
```
2. Specify relevant configuration, but especially the custom field mapper for the indexer through `di.xml`:
```
<type name="Magento\Elasticsearch\Model\Adapter\FieldMapper\FieldMapperResolver">
    <arguments>
        <argument name="fieldMappers" xsi:type="array">
            <item name="analysis_certificate_search_fulltext" xsi:type="string">MyCompany\AnalysisSearch\Model\Elasticsearch\Adapter\AnalysisFieldMapper</item>
        </argument>
    </arguments>
</type>
```
3. Run the indexer in the same command with the product search index first:
```
$ bin/magento indexer:reindex catalogsearch_fulltext analysis_certificate_search_fulltext
```
4. Notice (through Kibana or otherwise) that the ES analysis certificate index is erroneously using the product index mapping. Get the mapping with:
```
GET /magento2_analysis_certificate_search_fulltext_1/_mapping
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by aapokiiso** [comment]
Should I mark the PR checkboxes, or do you maintainers do it?

**Comment by aapokiiso** [comment]
Hi, the static code style check is failing on things unrelated to my changes (as far as I understand). Am I expected to fix those?

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5317](https://jira.corp.magento.com/browse/ENGCOM-5317) has been created to process this Pull Request

**Comment by engcom-Foxtrot** [comment]
QA passed.

**Pull request merged**
