### PR TITLE
Add missing city class to form field

### PR DESCRIPTION
**Pull request by dusnoki**

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=6666) <br/>All committers have signed the CLA.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=6666) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=6666) before we can accept your contribution.<br/>

**Comment by dusnoki** [comment]
@magento-cicd2 I did sign the CLA. But it says i still haven't

**Comment by tkacheva** [comment]
internal issue MAGETWO-59824

**Comment by vasiliyseleznev** [comment]
Hi @dusnoki,

Could you please explain what particular issue/task you solve with this classes in place?

Thanks!
Vasiliy

**Comment by Igloczek** [comment]
I'd say that it's not necessary to add these classes, b/c they are not used anywhere. Adding them, just, b/c every other element in form follow a similar approach, isn't a good option.

**Comment by vrann** [comment]
@dusnoki closing based on the earlier comments.

**Pull request closed without merging**
