### PR TITLE
"Save Product" with the invalid data must scroll to the error message issue24241

### LINKED ISSUE #24241: "Save Product" with the invalid data must scroll to the error message
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Create New Product
3. Fill all required field
4. Scroll down to "Schedule Design Update", fill date of "From" is greater than date of "To"
5. Click Save

### Expected result (*)

1. Scroll to the error message "Make sure the To Date is later than or the same as the From Date." so user can see the error message

### Actual result (*)

1. Nothing happen. User can not see anything and don't know the product isn't saved

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#24241: "Save Product" with the invalid data must scroll to the error message

Solution: Use ScrollTop to the error message in app/code/Magento/Ui/view/base/web/js/form/client.js

### Fixed Issues (if relevant)

1. magento/magento2#24241: "Save Product" with the invalid data must scroll to the error message

### Manual testing scenarios (*)

1. Go to backend
2. Create New Product
3. Fill all required field
4. Scroll down to "Schedule Design Update", fill date of "From" is greater than date of "To"
5. Click Save

#### Expected result

1. Scroll to the error message "Make sure the To Date is later than or the same as the From Date." so user can see the error message

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-24242.instances.magento-community.engineering).
Admin access: [https://pr-24242.instances.magento-community.engineering/admin](https://pr-24242.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-24242.instances.magento-community.engineering).
Admin access: [https://pr-24242.instances.magento-community.engineering/admin](https://pr-24242.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by kalpmehta — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, thank you for the review.
[ENGCOM-5679](https://jira.corp.magento.com/browse/ENGCOM-5679) has been created to process this Pull Request
:eight_spoked_asterisk: @kalpmehta, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Actual Result:**
after

**Pull request merged**
