### PR TITLE
Guest print order form fixes

### LINKED ISSUE #29337: [Issue] Guest print order form fixes
This issue is automatically created based on existing pull request: magento/magento2#29309: Guest print order form fixes

### Preconditions (*)
1. Magento 2.4

### Steps to reproduce (*)

1. Place an order as a guest
2. Go to the page "sales/guest/form/" on the storefront as a guest.
3. Fill in the print order form:
4. Try to search for an order by email
5. Try to search for an order by zip code
6. Try to input data with trailing/leading spaces
7. In all cases, you should be able to print the order.

### Expected result (*)
The expected result is that spaces are trimmed and order printed successfully.
It also improves Unit tests and Functional tests to cover cases when zip code is used to search for an order on the print guest order page.

### Actual result (*)
issue with guest print order form when a customer inputs data with trailing/leading spaces. 

Peek 2020-09-02 11-22

### PR DESCRIPTION
**Pull request by kodubovik**
### Description (*)

This pull request fixes an issue with guest print order form when a customer inputs data with trailing/leading spaces. The expected result is that spaces are trimmed and order printed successfully.
It also improves Unit tests and Functional tests to cover cases when zip code is used to search for an order on the print guest order page.

### Manual testing scenarios (*)

1. Place an order as a guest
2. Go to the page "sales/guest/form/" on the storefront as a guest.
3. Fill in the print order form:
   -  Try to search for an order by email
   -  Try to search for an order by zip code
   -  Try to input data with trailing/leading spaces

In all cases, you should be able to print the order.

### Related Pull Requests
https://github.com/magento/magento2/pull/30102

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29337: Guest print order form fixes

### CODE REVIEW

**Comment by kodubovik** [comment]
@magento run all tests

**Comment by edenduong** [comment]
Hi @kodubovik: Thank you for your contribution. Please solve the problem about static test.

**Comment by VladimirZaets** [comment]
@magento create issue

**Comment by kodubovik** [comment]
@magento run all tests

**Comment by kodubovik** [comment]
@magento run all tests

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-8044](https://jira.corp.magento.com/browse/ENGCOM-8044) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Place an order as a guest;
2. Go to the page "sales/guest/form/"  **Orders and Returns** on the storefront as a guest;
3. Fill in the print order form with spaces in each field:

**_Try to search for an order by email:_**

**Before:** :heavy_multiplication_x: You entered incorrect data. Please try again

Peek 2020-09-02 11-22

**After:** :heavy_check_mark: Order information was successfully displayed

Peek 2020-09-02 11-28

**_Try to search for an order by zip code:_**

**After:** :heavy_check_mark: Order information was successfully displayed

Peek 2020-09-02 11-50

Also, was tested Orders and Returns widget and everything works as expected.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Hi, @kodubovik. Can you please resolve the conflict?

**Comment by engcom-Echo** [comment]
@magento run all tests

**Pull request merged**
