### PR TITLE
#14663 Updating Customer through rest/all/V1/customers/:id resets group_id if group_id not passed in payload

### PR DESCRIPTION
**Pull request by MaxRomanov4669**
### Description (*)
While updating customer through api customer group is changed to 1 if there no customer group in the body

### Fixed Issues (if relevant)
https://github.com/magento/magento2/issues/14663

### Manual testing scenarios (*)
1. Update any customer who's group_id isn't the first group_id in the source list
2. Pass the customer payload with email, firstname, lastname, website_id, id

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6500](https://jira.corp.magento.com/browse/ENGCOM-6500) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Charlie** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Charlie** [comment]
Hi @MaxRomanov4669 

Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

Thanks!

**Comment by MaxRomanov4669** [comment]
Hi @VladimirZaets  @engcom-Charlie 
Can you please clarify/help how can I cover my fix with tests? 
function setCustomerGroupId - private function.
$customerModel - created inside save function
$customerArr - created inside save function
$prevCustomerDataArr - created inside save function 

Thanks!

**Comment by engcom-Golf** [comment]
All changes covered by unit test

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by engcom-Golf** [comment]
Functional test fails on 2.4-develop branch, fix in -> https://github.com/magento/magento2/pull/26225

**Pull request merged**
