### PR TITLE
Fix for Textarea element cols and rows #675

### PR DESCRIPTION
**Pull request by tzyganu**
This should allow developers to set the number of cols and rows for a textarea in the admin forms. PR for issue #675

### CODE REVIEW

**Comment by tzyganu** [comment]
it seams this failed because the tests ran for too long: *Your test run exceeded 50 minutes.*. Should I close this and reopen it again to restart the tests?

**Comment by vpelipenko** [comment]
@tzyganu, if you want to restart it, you can click on "Restart build" button on this page https://travis-ci.org/magento/magento2/builds/56015517.

**Comment by tzyganu** [comment]
@vpelipenko Either I'm blind or there is no such button there. please help a blind guy out :smile:

**Comment by vpelipenko** [comment]
Sorry for confusing. Probably it depends on permissions. Could you see such button as on attached screen?
restart

**Comment by tzyganu** [comment]
@vpelipenko I don't see it. That's because I don't have [write access to the repository](http://stackoverflow.com/a/17624403).  
So can you please click it? or give me write access to the repo. what ever is easier :smile: .

**Comment by vpelipenko** [comment]
Ok. I've restarted build.

**Comment by tzyganu** [comment]
@vpelipenko This might be my unlucky day. The tests failed again. [This time because of github](https://status.github.com/messages).

**Comment by vpelipenko** [comment]
Restarted again.

**Comment by vpelipenko** [comment]
CR: passed
Builds: green
Resolution: OK to merge

**Pull request merged**
