### PR TITLE
 Property "ShowDefaultNotificationMessage" does not have accessor method 

### PR DESCRIPTION
**Pull request by ityetti**
### Description (*)
If you want create queue which will triggered whem you will save product in the admin (I created plugin afterSave for the Magento\Catalog\Model\ResourceModel\Product::save()), you will get critical error - Property "ShowDefaultNotificationMessage" does not have accessor method "setShowDefaultNotificationMessage" in class "Magento\CatalogInventory\Api\Data\StockItemInterface". Even if you do not use this interface in your extension, you still get an error.

### Manual testing scenarios (*)
1. Create simple rabbitmq queue extension
2. Create plugin afterSave for the Magento\Catalog\Model\ResourceModel\Product::save()
3. Set up consumer
4. Save product in the admin panel
5. Run php bin/magento queue:consumers:start YourConsumerName
6. Got error)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ityetti** [comment]
@magento run all tests

**Comment by rogyar** [comment]
HI @ityetti. Thank you for your contribution. Adding public methods to API interfaces is a backward-incompatible change. Please refer to the [documentation](https://devdocs.magento.com/contributor-guide/backward-compatible-development/#php) for more details. 
The main problem is, there might be other implementations in 3rd-party extensions that rely on the interface. After bringing the change proposed by you, all systems with the mentioned 3rd party extensions will be broken. 

So, we need to be very careful with such fixes and think about the value/consequences. The missing accessor is definitely an issue but the current Magento extensibility system prevents us from fixing such issues easily. 

Hope it makes sense.

**Comment by ityetti** [comment]
@magento  run all tests

**Comment by ityetti** [comment]
@rogyar Hello. Thanks for your answer in my PR. I'll recheck this issue, and if I got this error again, I'll find another way how to fix this issue. 🙂

**Comment by sivaschenko** [comment]
Hi @ityetti , thanks for the pull request. The interface changed in this pull request `\Magento\CatalogInventory\Api\Data\StockItemInterface` is deprecated. Can you please check if you can use the replacement from Multi Source Inventory and close this pull request?

**Pull request closed without merging**
