### PR TITLE
Add note to setCustomer on quote about quote addresses removal

### LINKED ISSUE #37400: [Issue] Add note to setCustomer on quote about quote addresses removal
This issue is automatically created based on existing pull request: magento/magento2#35773: Add note to setCustomer on quote about quote addresses removal

---------
### Description (*)

While working on one of the features, we noticed that the method `\Magento\Quote\Model\Quote::setCustomer` not only sets the customer but also **copies data from the customer to quote** AND **REMOVES QUOTE ADDRESSES**, which is not obvious at all.

Removing of this behavior probably will cause the issue for the code that relies on this behavior, so I think we can't do that in the class and interface marked with `@api` tag.

The last thing caused a pretty big issue for us on checkout, as we missed checking the details of the implementation for the `setCustomer` method and thought it was just a regular setter.

I would like to deprecate it, but I didn't find any alternative to replace it fully w/o doing the only needed thing, so don't do that now. 
Also, I can't add a new method to this class since it's marked with `@api` tag that will cause the SVC failure, require additional approval process, etc.

Just an idea - Maybe we should deprecate the `getCustomer` and `setCustomer` methods with `getCustomerId` and `getCustomerId` alternatives?

Note: the methods `getCustomer` and `setCustomer` also declared in `\Magento\Quote\Api\Data\CartInterface`, I belive we should deprecate them as well.

### Fixed Issues (if relevant)
1. N/A

### Manual testing scenarios (*)
1. 
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)

While working on one of the features, we noticed that the method `\Magento\Quote\Model\Quote::setCustomer` not only sets the customer but also **copies data from the customer to quote** AND **REMOVES QUOTE ADDRESSES**, which is not obvious at all.

Removing of this behavior probably will cause the issue for the code that relies on this behavior, so I think we can't do that in the class and interface marked with `@api` tag.

The last thing caused a pretty big issue for us on checkout, as we missed checking the details of the implementation for the `setCustomer` method and thought it was just a regular setter.

I would like to deprecate it, but I didn't find any alternative to replace it fully w/o doing the only needed thing, so don't do that now. 
Also, I can't add a new method to this class since it's marked with `@api` tag that will cause the SVC failure, require additional approval process, etc.

Just an idea - Maybe we should deprecate the `getCustomer` and `setCustomer` methods with `getCustomerId` and `getCustomerId` alternatives?

Note: the methods `getCustomer` and `setCustomer` also declared in `\Magento\Quote\Api\Data\CartInterface`, I belive we should deprecate them as well.

### Fixed Issues (if relevant)
1. N/A

### Manual testing scenarios (*)
1. 
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37400: Add note to setCustomer on quote about quote addresses removal

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@sidolov @maghamed, I put the p1 priority as it is a real big issue that caused a pretty big problem on production just because of this stupid and not documented behavior.
Please let me know if you have some ideas of a replacement for this method in order to add deprecation notice to it.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@ihor-sviziev good point.
Also due to `todo` comment I believe that this method **should** be marked as deprecated and created task for refactoring logic.

**Comment by ihor-sviziev** [comment]
@Den4ik, since we don't have a direct replacement yet, I wouldn't mark it as deprecated.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @ihor-sviziev,

Thanks for the contribution. But we need to fix the Static test failure to process this PR further.

Thanks

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@engcom-Hotel, fixed

**Review by engcom-Hotel — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

Manual testing not required. Moving this PR to **Merge in progress.**

**Pull request merged**
