### PR TITLE
Implement ActionInterface for /version/

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
This is a part of the process of introducing implementations of `ActionInterface`.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]
Failing functional test are not related to changes from this PR

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7198](https://jira.corp.magento.com/browse/ENGCOM-7198) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Echo** [comment]
Failing functional test are not related to changes from this PR - [comment](https://github.com/magento/magento2/pull/27425#pullrequestreview-380887146)

**Pull request merged**
