### PR TITLE
Image resize issue fixed

### PR DESCRIPTION
**Pull request by ajithkumar-maragathavel**
### Description (*)

This PR will fix the image resize issue occurs in the configurable product image upload.

### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/27019

### Manual testing scenarios (*)

1. Uploaded higher resolution images for configurable products and verified the image is getting resized based on the configuration values.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @ajithkumar-maragathavel. Thanks for collaboration. 
Please fix static tests.
Also, due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

**Comment by ajithkumar-maragathavel** [comment]
> Hi @ajithkumar-maragathavel. Thanks for collaboration.
> Please fix static tests.
> Also, due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.

@VladimirZaets I have checked the Magento 2.4-develop code base and find that the file **Magento\Catalog\Controller\Adminhtml\Product\Gallery\Upload.php** does not have an existing unit test case.
Do you want me to create a new unit test file for this class? 
Please advise me.

**Comment by VladimirZaets** [comment]
hi @ajithkumar-maragathavel. Yes, you should create a new test that will cover this specific case

**Comment by ajithkumar-maragathavel** [comment]
@VladimirZaets I have covered the code changes with the unit test. Please review it.

**Comment by ajithkumar-maragathavel** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
Hi @ajithkumar-maragathavel. Can you please look is this case covered by integration tests?

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by ajithkumar-maragathavel** [comment]
> Hi @ajithkumar-maragathavel. Can you please look is this case covered by integration tests?

@VladimirZaets I will check it  and get back to you.

**Comment by engcom-Charlie** [comment]
Hi @ajithkumar-maragathavel, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Pull request closed without merging**
