### PR TITLE
[Validator] Fix wrong behaviour of validation scroll

### PR DESCRIPTION
**Pull request by Den4ik**
### Description (*)

If page have validating elements page scrolling down and up instead of focusing on non valid element

### Fixed Issues (if relevant)

1. magento/magento2#23034: Wrong behaviour of validation scroll

### Manual testing scenarios (*)

1. Open create order page in admin panel
2. Click Add Product button
3. Click Submit Order button

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5176](https://jira.corp.magento.com/browse/ENGCOM-5176) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Before:**

before

**After:**

after

**Comment by ihor-sviziev** [comment]
@Den4ik FYI this PR did regression on iPhone X, more info https://github.com/magento/magento2/pull/26327

**Comment by Den4ik** [comment]
@ihor-sviziev thanks for reference

**Pull request merged**
