### PR TITLE
Ability to configure the initial product position in category value

### PR DESCRIPTION
**Pull request by Nika-Valkyria**
### Description (*)
*Issue:* When adding a new category-product link, "position" value for a product is set to "0". Also, when importing products from file, "position" value is set to "1". As a result - new (and in some cases - not yet prepared) products appear in the beginning of the category.
*Solution:* Added an ability to configure the initial product position value in the Admin Panel. The default value for this config is "0".

### Fixed Issues (if relevant)
n/a

### Manual testing scenarios (*)
*Configuration:*
1. Go to Stores -> Configuration
2. Select tab Catalog -> Catalog, then expand Storefront
3. Set up a new value for "Product Position in Category Default Value" and save the config

*Adding new category to the product:*
1. Go to "Edit" page of any existing product
2. Add a category to the product
3. Save changes
4. Check "position" value for the product in the added category

*Importing products:*
1. Go to the Import page, choose "Entity Type -> Products" and "Import Behavior -> Add / Update"
2. Upload a file with new products ("categories" column must be filled)
3. Check "position" values for the imported products in corresponding categories

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19362) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @Valkyria68. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by VladimirZaets** [comment]
Hi @Valkyria68, please, sign CLA, otherwise, we can't process your pull request.

**Comment by oleksandr-butenko** [comment]
Hi 
It looks like some dependencies are missing.  
If I will install import/export and don't update Catalog - I'll get an error during import/export

@VladimirZaets, how we can properly prepare this request? 
Or what are the next steps here?

Thx

**Review by orlangur — CHANGES_REQUESTED** [review]
@Nika-Valkyria please report an issue separately so that it can be verified for both `2.2-develop` and `2.3-develop`.

After that, it needs to be fixed in `2.3-develop` first.

**Comment by sidolov** [comment]
@Nika-Valkyria , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
