### PR TITLE
Removing the deprecated files with prototype usages

### PR DESCRIPTION
**Pull request by eduard13**
### Description (*)
This PR aims to remove the deprecated files since 2.2.0 with PrototypeJS usages

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33532 - Removing the deprecated files with prototype usages

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by eduard13** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Functional Tests B2B, WebAPI Tests

**Comment by andrewbess** [comment]
@magento run Functional Tests B2B

**Comment by eduard13** [comment]
@magento run all tests

**Review by andrewbess — APPROVED** [review]
Hello @eduard13 
Thank you for your contribution.
Your changes are approved.

**Review by Den4ik — APPROVED** [review]
✅ Approved

**Pull request merged**
