### PR TITLE
[Backport] added config for catalog review in frontend

### PR DESCRIPTION
**Pull request by torhoehn**
### Original Pull Request 
 https://github.com/magento/magento2/pull/18895

### Description

Until now there wasn't a config field to hide product review elements from frontend. I orientated at the wishlist module, because for wishlist it was already possible.

### Manual testing scenarios

1. Open Backend
2. Go to Stores -> Configuration -> Catalog -> Catalog -> Product Reviews
3. Set 'Enabled' to 'No'
4. Newsletter will be hidden from catalog product view, customer account, customer account sidebar, ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
Hi @torhoehn. Thank you for your collaboration. Please, consider fixing failing unit tests.

**Comment by torhoehn** [comment]
@rogyar So for PHP 7.0 the return type should be removed?

**Comment by rogyar** [comment]
Yes, void return type is supported since PHP 7.1

**Comment by torhoehn** [comment]
@rogyar Looks good for me now.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4131](https://jira.corp.magento.com/browse/ENGCOM-4131) has been created to process this Pull Request

**Pull request merged**
