### PR TITLE
Removed laminas/laminas-config from config.json

### PR DESCRIPTION
**Pull request by ProkopovVitaliy**
### Description (*)

Removed laminas/laminas-config dependency from config.json
### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/468

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31082

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by coderimus** [comment]
@magento run all tests

**Review by coderimus — APPROVED** [review]
Thank you @ProkopovVitaliy for the upgrade! 👍

**Comment by sivaschenko** [comment]
@ProkopovVitaliy thanks for the PR! Can you please create a related PR to https://github.com/magento/partners-magento2ee/ repository

**Comment by ProkopovVitaliy** [comment]
@sivaschenko  created related PR https://github.com/magento/partners-magento2ee/pull/468

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Pull request merged**
