### PR TITLE
Fix compare link anchor uncrawlable

### LINKED ISSUE #31138: [Issue] Fix compare link anchor uncrawlable
This issue is automatically created based on existing pull request: magento/magento2#31096: Fix compare link anchor uncrawlable

---------

### Description (*)

Fix anchor compare link uncrawlable (anchor not have href)
Improve Lighthouse SEO Score metrics

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Fix anchor compare link uncrawlable (anchor not have href)
Improve Lighthouse SEO Score metrics

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31138: Fix compare link anchor uncrawlable

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Comment by mrtuvn** [comment]
rebased upstream branch code to PR branch

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE

**Comment by mrtuvn** [comment]
CC @ihor-sviziev this quite fast easy check and merge to codebase. Not big change

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8585](https://jira.corp.magento.com/browse/ENGCOM-8585) has been created to process this Pull Request

**Comment by mrtuvn** [comment]
Same purpose this PR can increase score lighthouse metrix

**Comment by engcom-Bravo** [comment]
Hi @mrtuvn,

We are closing this PR.The PR is in Draft since longtime.

Once you are ready Please feel free to reopen it to process the PR further.

Thanks

**Pull request closed without merging**
