### PR TITLE
Fix print invoice issue #33800

### LINKED ISSUE #33800: Issue with print invoice
### Preconditions (*)

1. Magento 2.3, 2.4

### Steps to reproduce (*)

1. Login by user account
2. Create new order by checkout (order id 11)
3. Go to https://domain.com/sales/order/printInvoice/invoice_id/11/

### Expected result (*)

1. If the invoice doesn't exist, Error handling should be done for better user experience.
### Actual result (*)

1. Showing error:
```
There has been an error processing your request
Exception printing is disabled by default for security reasons.

Error log record number: 1a010b4dc79669c5758ea8eed7d18e4a4901fd402b6734616e693dfedb4c0cbd
```
Var/log/exception.log: 
[2021-08-16 12:00:54] main.CRITICAL: The entity that was requested doesn't exist. Verify the entity and try again. {"report_id":"5aade6c95721635595e8acabec9909a13f5cf2ca4212e0313cd3e939ba435167","exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): The entity that was requested doesn't exist. Verify the entity and try again. at /var/www/html/magento2.4/magento2/app/code/Magento/Sales/Model/Order/InvoiceRepository.php:75)"} []

Note: There is no issue for the Orders having invoice generated from admin and navigated to /sales/order/printInvoice/invoice_id/7/

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Kannakiraj123**
### Description (*)
1.Fix print invoice no such entity exception
2.Fix print Shipment no such entity exception
     
### Related Pull Requests
1.I added code try catch for no such entity for invoice id.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#33800

### CODE REVIEW

**Comment by Kannakiraj123** [comment]
@magento give me test instance

**Comment by Kannakiraj123** [comment]
@magento run all tests

**Comment by Kannakiraj123** [comment]
@magento run all tests

**Comment by Kannakiraj123** [comment]
@magento run all tests

**Comment by bgorski** [comment]
@Kannakiraj123 You used the object manager directly, which is a code smell - you're not supposed to do that ever unless you're writing tests using the Integration Test Framework (in which case it's usually the recommended way). I know that direct object manager usage was already there, but adding more of that is extending the technological debt of the project - it's just more code to fix later. One of the issues of using the object manager directly is that this may break the application on read-only environments like Adobe Commerce Cloud. 
I'm going to close this PR for now. You'll welcome to create another one, but please keep in mind that it's addressing a P4 issue - and P4 means "no current plan to fix". This mean that the effort you put in fixing the issue may be greatly deferred or even wasted if the plan to fix (once/if there is one) doesn't include merging the PR as it is. 
If you do plan to introduce a new PR despite the fact that it may wait a long time for a merge or never be merged, I'll be happy to review it for you. 
Despite the fact that I'm closing the issue, the effort you put in your contributions is still greatly appreciated - keep doing the good work you do! Thanks!

**Pull request closed without merging**
