### PR TITLE
Fix CheckCartCheckoutAllowance when getCustomerIsGuest is returning i…

### PR DESCRIPTION
**Pull request by codynguyen1**
### Description (*)
Fix CheckCartCheckoutAllowance when getCustomerIsGuest is returning int (smallint from DB).

### Manual testing scenarios (*)

1. I disabled guest checkout from admin.
2. Then I use pwa-studio venia to checkout with logged in customer. 
3. The cart API is returning 'Guest checkout is not allowed.' even when I logged in.
The issue is because it's checking isAllowedGuestCheckout from quote, which returned 0 (not guest, but not === false, then still marked the quote as a guest quote)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @codynguyen1. Nice catch, thank you! 
Could I ask you to cover this fix with an API-functional test, please? You may extend one of the existing tests and add scenario for asserting the fact that checkout is possible with the logged-in user when guest checkout is disabled. 

Thanks

**Comment by codynguyen1** [comment]
@magento run all tests
@rogyar  I have added a function to test the scenario that "allow guest checkout" is enabled.
Thanks!

**Comment by codynguyen1** [comment]
@magento run all tests

**Comment by codynguyen1** [comment]
@rogyar the testing is returning admin issue, which is from another feature, could you please help me with this?

**Comment by codynguyen1** [comment]
@magento run Functional Tests B2B

**Comment by rogyar** [comment]
Hi @codynguyen1. Thanks for providing the test. Great job! 
The failing functional tests are not related to your changes.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8313](https://jira.corp.magento.com/browse/ENGCOM-8313) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Alfa** [comment]
Thanks for your contribution & collaboration @codynguyen1 and @rogyar !
I tried to reproduce the issue in 2.4-develop instance, using GraphQL queries and as well Rest API requests. Couldn't get the issue reproduced.

1. Set the guest checkout - no;
2. Created a GraphQL query cart ID and added a product into it.
3. Queried Get Cart items GraphQL request and couldn't get the issue defined in the description. Below is the screenshot of it.
Screenshot 2021-11-17 at 7 43 55 PM

4. Queried Customer cart graphQL request and couldn't get the issue defined in the description. Below is the screenshot of it.
Screenshot 2021-11-17 at 7 44 07 PM

5. Queried Ready for Checkout GraphQL request and couldn't get the issue defined in the description. Below is the screenshot of it.
Screenshot 2021-11-17 at 7 44 10 PM
 
Kindly let me know if I have to follow any other GraphQL request please ?

6. Later, performed complete order flow of customer starting from creating a new customer and then adding product to the cart, checkout and placing an order. Didn't get any issue in that complete flow of Rest API execution. Below is the screenshot of successful order placement.
Screenshot 2021-11-17 at 8 25 10 PM


The above PR description has 3rd point saying _The cart API is returning 'Guest checkout is not allowed.'_
Can you please give me the details of that API request completely if the issue is still reproducible in your end. @codynguyen1 
Thanks in advance!

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
This PR is getting conflicted and the conflicts need to be resolved. Hence moving it to _Changes Requested_.
Also, need additional details as requested in the [above-comment](https://github.com/magento/magento2/pull/30242#issuecomment-971661375).

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
Hi @codynguyen1 
Thank you for your contribution,

I tried to reproduce the same on 2.4-develop, But its not reproducible.
Also after merging the PR with 2.4-develop, the change is no more required as the issue was fixed.

Hence closing this PR
You can try the same on mainline 2.4-develop, If still its reproducible, Please reopen and update if you wish to continue.

Thanks

**Pull request closed without merging**
