### PR TITLE
Fix compatibility with phpunit 9.3 in integration and api functional tests

### LINKED ISSUE #30146: Integration Test Framework do not work out the box. Not compatible with PhpUnit 9.3.x
### Preconditions
1. Magento 2.4.0

### Steps to reproduce
1. Run Integration Test Framework on a new test or existing Magento 2 test.
2. cd into the following folder: `dev/tests/integration`
3. `../../../vendor/phpunit/phpunit/phpunit --configuration phpunit.xml`

### Expected Result
1. Tests run.

### Actual Result
```
PHP Fatal error:  Uncaught Error: Class 'PHPUnit\TextUI\Configuration\Registry' not found in /var/www/dev/tests/integration/testsuite/Magento/IntegrationTest.php:32
Stack trace:
#0 [internal function]: Magento\IntegrationTest::suite('Magento\\Integra...')
#1 /var/www/vendor/phpunit/phpunit/src/Framework/TestSuite.php(476): ReflectionMethod->invoke(NULL, 'Magento\\Integra...')
#2 /var/www/vendor/phpunit/phpunit/src/TextUI/XmlConfiguration/TestSuite/TestSuiteMapper.php(65): PHPUnit\Framework\TestSuite->addTestFile('/var/www/dev/te...')
#3 /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php(389): PHPUnit\TextUI\XmlConfiguration\TestSuiteMapper->map(Object(PHPUnit\TextUI\XmlConfiguration\TestSuiteCollection), '')
#4 /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php(116): PHPUnit\TextUI\Command->handleArguments(Array)
#5 /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php(101): PHPUnit\TextUI\Command->run(Array, true)
#6 /var/www/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#7 {main}

Next PHPUnit\T in /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php on line 103

Fatal error: Uncaught Error: Class 'PHPUnit\TextUI\Configuration\Registry' not found in /var/www/dev/tests/integration/testsuite/Magento/IntegrationTest.php:32
Stack trace:
#0 [internal function]: Magento\IntegrationTest::suite('Magento\\Integra...')
#1 /var/www/vendor/phpunit/phpunit/src/Framework/TestSuite.php(476): ReflectionMethod->invoke(NULL, 'Magento\\Integra...')
#2 /var/www/vendor/phpunit/phpunit/src/TextUI/XmlConfiguration/TestSuite/TestSuiteMapper.php(65): PHPUnit\Framework\TestSuite->addTestFile('/var/www/dev/te...')
#3 /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php(389): PHPUnit\TextUI\XmlConfiguration\TestSuiteMapper->map(Object(PHPUnit\TextUI\XmlConfiguration\TestSuiteCollection), '')
#4 /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php(116): PHPUnit\TextUI\Command->handleArguments(Array)
#5 /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php(101): PHPUnit\TextUI\Command->run(Array, true)
#6 /var/www/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#7 {main}

Next PHPUnit\T in /var/www/vendor/phpunit/phpunit/src/TextUI/Command.php on line 103
PHP Fatal error:  Uncaught Exception: sh: tasklist.exe: not found in /var/www/vendor/magento/framework/Shell.php:63
Stack trace:
#0 /var/www/dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php(92): Magento\Framework\Shell->execute('tasklist.exe /f...', Array)
#1 /var/www/dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php(58): Magento\TestFramework\Helper\Memory->_getWinProcessMemoryUsage(47150)
#2 /var/www/dev/tests/integration/framework/Magento/TestFramework/MemoryLimit.php(127): Magento\TestFramework\Helper\Memory->getRealMemoryUsage()
#3 /var/www/dev/tests/integration/framework/Magento/TestFramework/MemoryLimit.php(59): Magento\TestFramework\MemoryLimit->_getUsage()
#4 /var/www/dev/tests/integration/framework/Magento/TestFramework/Bootstrap/Memory.php(50): Magento\TestFramework\MemoryLimit->printStats()
#5 [internal function]: Magento\TestFramework\Bootstrap\Memory->displayStats()
#6 {main}

Next Magento\Framework\Exception\LocalizedException: Command returned non-zero exit code:
`ta in /var/www/vendor/magento/framework/Shell.php on line 64

Fatal error: Uncaught Exception: sh: tasklist.exe: not found in /var/www/vendor/magento/framework/Shell.php:63
Stack trace:
#0 /var/www/dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php(92): Magento\Framework\Shell->execute('tasklist.exe /f...', Array)
#1 /var/www/dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php(58): Magento\TestFramework\Helper\Memory->_getWinProcessMemoryUsage(47150)
#2 /var/www/dev/tests/integration/framework/Magento/TestFramework/MemoryLimit.php(127): Magento\TestFramework\Helper\Memory->getRealMemoryUsage()
#3 /var/www/dev/tests/integration/framework/Magento/TestFramework/MemoryLimit.php(59): Magento\TestFramework\MemoryLimit->_getUsage()
#4 /var/www/dev/tests/integration/framework/Magento/TestFramework/Bootstrap/Memory.php(50): Magento\TestFramework\MemoryLimit->printStats()
#5 [internal function]: Magento\TestFramework\Bootstrap\Memory->displayStats()
#6 {main}

Next Magento\Framework\Exception\LocalizedException: Command returned non-zero exit code:
`ta in /var/www/vendor/magento/framework/Shell.php on line 64
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
Fixes compatibility with phpunit 9.3 and keeping backward compatibility with phpunit <9.3, similar what was done in symfony https://github.com/symfony/phpunit-bridge/commit/9a87dd7e6074107ebc36ae96c231f79e8eb3fa59

✔ Before my changes on phpunit 9.1:
❌ Before my changes on phpunit 9.3:
image

✔ After my changes on phpunit 9.1:
image
✔ After my changes on phpunit 9.3:
image

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/30146

### Manual testing scenarios (*)

1. Try to run integration tests
2. Try to run api functional tests
3. Upgrade to phpunit 9.3
4. Try to run integration tests again
5. Try to run api functional tests

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Seems like similar changes should be done in https://github.com/magento/magento2/blob/d8ca81c51f2f9871a00f269f6537f40b5b7ae0a6/dev/tests/api-functional/testsuite/Magento/WebApiTest.php#L14-L16.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by lbajsarowicz — APPROVED** [review]
✔️  Verified locally and works as expected both with 9.3 and 9.1

Personally, I'm super happy with you proceeding the PHPUnit upgrades! Awesome job.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-8266](https://jira.corp.magento.com/browse/ENGCOM-8266) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

### Case 1. Integration tests

**Manual testing scenario:**
1. _`cd /dev/tests/integration`_;
2. Run in console: `../../../vendor/phpunit/phpunit/phpunit --configuration phpunit.xml`

**Before:**

:heavy_check_mark: PhpUnit 9.1
Screenshot from 2020-09-25 09-27-56

:heavy_multiplication_x: PhpUnit 9.3

Screenshot from 2020-09-25 09-56-57

**After:** 

:heavy_check_mark: PhpUnit 9.1

Screenshot from 2020-09-25 10-13-08


:heavy_check_mark: PhpUnit 9.3

Screenshot from 2020-09-25 10-08-01

### Case 2. Api-functional tests

1. _`cd /dev/tests/api-functional`_;
2. Run in console: `../../../vendor/phpunit/phpunit/phpunit --configuration phpunit_rest.xml testsuite/Magento/Sales`

**After:** 

:heavy_check_mark: PhpUnit 9.1

Screenshot from 2020-09-25 11-53-28

:heavy_check_mark: PhpUnit 9.3

Screenshot from 2020-09-25 11-57-41

**Pull request merged**
