### PR TITLE
fix issue with PHP Fatal error:  '\self' is an invalid class name in …

### PR DESCRIPTION
**Pull request by igortregub**
…generated/code/Magento/Indexer/Model/Indexer/DependencyDecorator/Interceptor.php on line 137

### Description (*)

Issue is described at https://github.com/magento/magento2/issues/11905
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21775) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @igortregub. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
`self` return type is perfectly valid from PHP perspective.

Interceptor generation mechanism must be fixed instead.

**Comment by igortregub** [comment]
I think if interface declares some type, you must follow it. Because in other case you will break Liskov substitution principle

**Comment by orlangur** [comment]
@igortregub please read at least a definition of LSP

> Substitutability is a principle in object-oriented programming stating that, in a computer program, if S is a subtype of T, then objects of type T may be replaced with objects of type S (i.e. an object of type T may be substituted with any object of a subtype S) without altering any of the desirable properties of the program (correctness, task performed, etc.).

Review note remain unchanged.

**Comment by igortregub** [comment]
@orlangur Yes, I wasn't correct about Liskov, but I mean following: if you implement an interface, please return declared type on the interface.

**Comment by orlangur** [comment]
@igortregub,

> if you implement an interface, please return declared type on the interface.

Such restriction goes against LSP actually. Declared type or its subtype should be returned.

Are you going to apply the fix in a proper place?

**Comment by igortregub** [comment]
@orlangur I will try to debug this issue from other side.

**Comment by ihor-sviziev** [comment]
Hi @igortregub,
Looks like this issue was fixed in https://github.com/magento/magento2/pull/19398 and was included into 2.2.8.

Could you double check?

**Comment by ihor-sviziev** [comment]
Hi @igortregub,
QA team already re-checked, this issue was already fixed in 2.3-develop and in 2.2-develop branches by https://github.com/magento/magento2/pull/19398
I'm closing this PR.

Thank you  for contribution!

**Pull request closed without merging**
