### PR TITLE
Use the correct way to make the page title translatable

### PR DESCRIPTION
**Pull request by arnoudhgz**
### Description
The page title always showed English, because the wrong method was being used to make it translatable.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @arnoudhgz. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-2815](https://jira.corp.magento.com/browse/ENGCOM-2815) has been created to process this Pull Request

**Comment by VladimirZaets** [comment]
Hi @arnoudhgz. 
After manual testing we found the next problem:
Problems: customer/account/forgotpassword is shown as page title instead of translated phrase "Forgot Your Password" and tag title is empty.
Manual testing scenario:

Install and apply language pack.
Clear cache.
Go to customer/account/forgotpassword/ page.
Tag title is empty.

**Comment by VladimirZaets** [comment]
@arnoudhgz, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Pull request closed without merging**
