### PR TITLE
2.3 develop resolve wrong variable in parameter for phpDoc IN DataBuilder, closes #19974 

### LINKED ISSUE #19974: Wrong variable in parameter for phpDoc IN DataBuilder
### Summary (*)
1. You can find it in any Magento 2.1.x, 2.2.x AND 2.3
2. File path `vendor/magento/module-catalog/Model/Layer/Filter/Item/DataBuilder.php` OR `app/code/Magento/Catalog/Model/Layer/Filter/Item/DataBuilder.php`.

### Examples (*)
```
/**
     * Add Item Data
     *
     * @param string $label
     * @param string $value
     * @param int $count
     * @return void
     */
    public function addItemData($label, $value, $count)
    {
        $this->_itemsData[] = [
            'label' => $label,
            'value' => $value,
            'count' => $count,
        ];
    }
```

### Proposed solution
```
 /**
     * Add Item Data
     *
     * @param string $label
     * @param string $label
     * @param int $count
     * @return void
     */
    public function addItemData($label, $value, $count)
    {
        $this->_itemsData[] = [
            'label' => $label,
            'value' => $value,
            'count' => $count,
        ];
    }
```

### PR DESCRIPTION
**Pull request by kunj1988**
### Fixed Issue #19974 (if relevant)

1. magento/magento2#19974: Wrong variable in parameter for phpDoc IN DataBuilder

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19976) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @kunj1988. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by DanielRuf** [comment]
Please sign the CLA and update the issue title. `2.3-develop` as title is not sufficient.

**Comment by VladimirZaets** [comment]
Hi @kunj1988, thanks for collaboration. Looks like your branch contains changes that are not related to the fix issue.

**Comment by kunj1988** [comment]
> Please sign the CLA and update the issue title. `2.3-develop` as title is not sufficient.

@DanielRuf, I have updated it please review it.

**Comment by kunj1988** [comment]
> Hi @kunj1988, thanks for collaboration. Looks like your branch contains changes that are not related to the fix issue.

@VladimirZaets, So do I need to commit it with the new branch?

**Comment by DanielRuf** [comment]
@VladimirZaets which changes do you mean? I think he just used two logins to contribute (shell / bash and GitHub).

**Pull request closed without merging**
