### PR TITLE
magento/magento2#: Magento_User module. Replace replace deprecated message functions

### PR DESCRIPTION
**Pull request by atwixfirster**
PR replaces deprecated message functions in the `Magento_User` module.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

Thank you!

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @atwixfirster,
Please review failing static & integration tests and update your code/tests accordingly.

Thank you!

**Comment by atwixfirster** [comment]
@ihor-sviziev 
> Hi @atwixfirster,
> Please review failing static & integration tests and update your code/tests accordingly.
> 
> Thank you!

sure, sir

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @atwixfirster,
There still failing integration tests, please check them

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @atwixfirster,
There still failing integration tests, please check them

**Comment by atwixfirster** [comment]
> Hi @atwixfirster,
> There still failing integration tests, please check them

yes, thank you @ihor-sviziev ! I know... Still can not fix them :(

**Comment by ihor-sviziev** [comment]
@atwixfirster I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
