### PR TITLE
Fix/issue 18761

### PR DESCRIPTION
**Pull request by DenisSaltanahmedov**
### Fixed Issues
1. magento/magento2#18761: Bug with REPLACE method in Advanced Prices in CSV Import 

### Manual testing scenarios 

1. Define bunch size as e.g 100 (probably 100 is default)
2. Prepare CSV with over 100 records (I had 2012) and different SKU! E.g 4-5 prices for one SKU
3. Select the "Replace" method
4. Make an import

### Contribution checklist (*)
 - [*] Pull request has a meaningful description of its purpose
 - [*] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @DenisSaltanahmedov. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-21189.instances.magento-community.engineering).
Admin access: [https://pr-21189.instances.magento-community.engineering/admin](https://pr-21189.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4281](https://jira.corp.magento.com/browse/ENGCOM-4281) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
