### PR TITLE
[GraphQL] Add possibility to filter categories by parent_id

### LINKED ISSUE #30624: [GraphQL] Add parent_id to filters for subcategory pagination
Our use case is basically to paginate through all subcategories of a common parent category. For example to display all top level categories in a shop (men, women, etc.), we currently get the root category by ID and via the children attribute, retrieve all first level children. Pagination isn’t possible here. Depending on the customer, first level children categories might be hundreds or even more. Memory is not the issue but AEM wants to keep the request payload small and response times short (especially when GraphQL API is consumed client-side). 

Would like to add the parent ID to the possible filters so you can directly get all first level children of the root category and pagination through it.
  
 Adding parent_id to the filters should solve the issue. 

<https://devdocs.magento.com/guides/v2.4/graphql/queries/categories.html]

 

Additions to schema: 

```
input CategoryFilterInput

{      parent_id: FilterEqualTypeInput }
```

Expected Scenario:

```
{
 categories(filters: {
 parent_id: {
 eq: "2"
 }
 }) {
 items {
 id
 }
 }
}
```

Response should return all the child categories belonging to the parent with id: "2".

### PR DESCRIPTION
**Pull request by rogyar**
### Description (*)
This PR introduces a possibility to filter the result set of categories by `parent_id`

### Fixed Issues (if relevant)

1. #30624 : Add parent_id to filters for subcategory pagination

### Manual testing scenarios (*)
1. Create a set of categories and subcategories for your Magento installation
2. Use the following queries to filter categories by `parent_id` (change the ID's to the actual values for your setup)

```graphql
{
  categories(filters: {parent_id: {eq: "2"}}) {
    items {
      name
    }
  }
}
```

```graphql
{
  categories(filters: {parent_id: {in: ["2", "3"]}}) {
    items {
      name
    }
  }
}
```

### CODE REVIEW

**Comment by rogyar** [comment]
@magento run WebAPI Tests

**Comment by keharper** [comment]
@rogyar Will you/Atwix be updating the documentation, or should I do it?

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-8373](https://jira.corp.magento.com/browse/ENGCOM-8373) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by rogyar** [comment]
@andrewbess would you cover the documentation, please?

**Comment by andrewbess** [comment]
@rogyar 
Thank you. I will do it ASAP

**Comment by cpartica** [comment]
We also have to update architectural repo. I'l do it. @rogyar .. so parent id just works? no other code needed?

**Comment by cpartica** [comment]
@magento run all tests

**Comment by rogyar** [comment]
Hi @cpartica. Yep, `parent_id` works since it's in the collection. I've covered this part with a test.

**Pull request merged**
