### PR TITLE
Update bootstrap.js

### PR DESCRIPTION
**Pull request by LuciferStrome**
Typo in bootstrap.js file

### Description (*)
Typo Corrected

### Fixed Issues (if relevant)

Typo in bootstrap.js

### Manual testing scenarios (*)
Not Needed

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19766) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @LuciferStrome. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by milindsingh — COMMENTED** [review]
This will create issues everywhere the index is used.

**Comment by VladimirZaets** [comment]
Hi @LuciferStrome. Thanks for collaboration. 
@milindsingh Yes, you are right. Currently, I found usage only correct afterRender in Magento. KnockoutJS that is used as a core of the bindings has the native afterRender method that currently uses in all places. With this fix, we will override the native KnockoutJS binding. 

I looked the code of our custom afterRender binding and looks like it works like original afterRender and only passes additional param. I think, we should check manually this case

**Comment by LuciferStrome** [comment]
Hi @VladimirZaets , Have you or someone from your team checked this case manually?

**Comment by VladimirZaets** [comment]
Hi @LuciferStrome. We already check this case. I was right and our custom afterRender implementation works as native.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3719](https://jira.corp.magento.com/browse/ENGCOM-3719) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@LuciferStrome thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @LuciferStrome. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
