### PR TITLE
[Forwardport-2.3] fix typo for setCateroryIds

### PR DESCRIPTION
**Pull request by neeta-wagento**
### Original Pull Request
https://github.com/magento/magento2/pull/15621

### Description
Browsing through the source code, we found occurences of the word "Caterory" in tests, which seemed as if it would be a typo. Please have a look - and just close it, if we are wrong. ;) Thank you!!!

### Fixed Issues (if relevant)

1. magento/magento2#15590: tests / setCateroryIds
2. ...

### Manual testing scenarios

Browse to https://github.com/magento/magento2/search?q=setcateroryids&unscoped_q=setcateroryids
### Expected result

1. I would expect to see no function calls for "setCateroryIds"

### Actual result

1. I see several occurrences of "setCateroryIds":
screen shot 2018-05-30 at 2 13 39 pm

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @neeta-wagento. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by neeta-wagento** [comment]
@magento-engcom-team give me test instance - deploy test instance based on PR changes
@magento-engcom-team give me {$VERSION} instance - deploy vanilla Magento instance

**Comment by magento-engcom-team** [comment]
Hi @neeta-wagento. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @neeta-wagento, here is your [new Magento instance](https://pr-16353.engcom.dev.magento.com).
Admin access: [https://pr-16353.engcom.dev.magento.com/admin](https://pr-16353.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Please make sure you are PR **author** or **assignee** to access the instance.

**Comment by orlangur** [comment]
@neeta-wagento there are 5 commits in this PR and none of them is https://github.com/magento/magento2/pull/15621/commits/1d47b28cbaf42b7cc024ad4c04b32080e61fe0e1. Please check contents of diff prior to PR creation.

Note that commits like `Merge pull request #1 from neeta-wagento/2.3-develop-PR-port-15349` MUST NOT be present at all. I noticed such merges in a lot of pull requests produced by Wagento fellows, please adjust your git processes in such a way that they correspond to Magento 2 repo usual workflow. Cc: @chirag-wagento @vijay-wagento

**Pull request closed without merging**
