### PR TITLE
Initialize inline translations module only when they are enabled

### LINKED ISSUE #29553: [Issue] Initialize inline translations module only when they are enabled
This issue is automatically created based on existing pull request: magento/magento2#27696: Initialize inline translations module only when they are enabled

---------

### Description (*)

This PR is a part of my effort to improve Magento 2 frontend performance.

The focus point of this PR was to remove downloading of inline translations JavaScript modules when they are not enabled. This was happening because they were defined in `deps`, which is completely redundant because they are properly initialized in https://github.com/krzksz/magento2/blob/98e04e174906799b941011a9fb1b5890a5e7cae9/app/code/Magento/Translation/view/frontend/templates/translate_inline.phtml#L57

While I was touching the files anyway I took the liberty to:

- Move `escapeHTML` to utilities (it is not used anywhere else and there is already an `unescape` counterpart).
- Fixed utilities dependency for `serialize` method.
- Simplify logic and variables in few places.

#### Performance improvement

Tested on Magento 2.4-develop with Luma and sample data.

- 207 → 203 JS requests (-1.93%).
- 794.39kB → 773.44kB JS transferred (-2.64%).

### Manual testing scenarios (*)

1. When inline translations are disabled there is no request for `translate-inline` JS file.
2. When inline translations are enabled, they work as expected.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by krzksz**
### Description (*)

This PR is a part of my effort to improve Magento 2 frontend performance.

The focus point of this PR was to remove downloading of inline translations JavaScript modules when they are not enabled. This was happening because they were defined in `deps`, which is completely redundant because they are properly initialized in https://github.com/krzksz/magento2/blob/98e04e174906799b941011a9fb1b5890a5e7cae9/app/code/Magento/Translation/view/frontend/templates/translate_inline.phtml#L57

While I was touching the files anyway I took the liberty to:

- Move `escapeHTML` to utilities (it is not used anywhere else and there is already an `unescape` counterpart).
- Fixed utilities dependency for `serialize` method.
- Simplify logic and variables in few places.

#### Performance improvement

Tested on Magento 2.4-develop with Luma and sample data.

- 207 → 203 JS requests (-1.93%).
- 794.39kB → 773.44kB JS transferred (-2.64%).

### Manual testing scenarios (*)

1. When inline translations are disabled there is no request for `translate-inline` JS file.
2. When inline translations are enabled, they work as expected.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29553: Initialize inline translations module only when they are enabled

### CODE REVIEW

**Comment by krzksz** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @krzksz. Thank you for your request. I'm working on Magento instance for you

**Comment by krzksz** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krzksz. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krzksz, here is your [new Magento instance](https://pr-27696.instances.magento-community.engineering).
Admin access: [https://pr-27696.instances.magento-community.engineering/admin_370d](https://pr-27696.instances.magento-community.engineering/admin_370d)
Login: `f761e507` Password: `3eb2cb42c5e1`
Instance will be terminated in up to 3 hours.

**Comment by krzksz** [comment]
@magento give me 2.4-develop instance

**Comment by krzksz** [comment]
@magento run all tests

**Comment by krzksz** [comment]
@magento run all tests

**Comment by krzksz** [comment]
@magento run all tests

**Comment by krzksz** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @krzksz. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @krzksz, here is your [new Magento instance](https://pr-27696.instances.magento-community.engineering).
Admin access: [https://pr-27696.instances.magento-community.engineering/admin_c5e1](https://pr-27696.instances.magento-community.engineering/admin_c5e1)
Login: `7370547e` Password: `b01752ce655a`
Instance will be terminated in up to 3 hours.

**Comment by krzksz** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @krzksz. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @krzksz, here is your [Magento instance](https://i-27696-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27696-2-4-develop.instances.magento-community.engineering/admin_7a64](https://i-27696-2-4-develop.instances.magento-community.engineering/admin_7a64)
Login: `490409ef` Password: `3f1e3eaa8fc8`
Instance will be terminated in up to 3 hours.

**Comment by krzksz** [comment]
@magento run Functional Tests EE,Functional Tests CE

**Comment by krzksz** [comment]
@magento run Functional Tests EE,Functional Tests CE

**Comment by krzksz** [comment]
@magento run Functional Tests EE,Functional Tests CE

**Comment by krzksz** [comment]
@magento run Functional Tests EE,Functional Tests CE

**Comment by krzksz** [comment]
@magento run all tests

**Comment by krzksz** [comment]
It seems that failed tests are not connected with this PR, but I'm not 100% sure. Anyway feel free to review 🥳

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests, Static Tests

**Review by adifucan — COMMENTED** [review]
Nice to eliminate redundant requests. Looks good to me!

**Comment by sidolov** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8018](https://jira.corp.magento.com/browse/ENGCOM-8018) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

Tested on Magento 2.4-develop with Luma and sample data.

205 → 201 JS requests (-1.96%).
794kB → 779kB JS transferred (-1.89%).

When inline translations are disabled there is no request for translate-inline JS file.
When inline translations are enabled, they work as expected.

Was tested and on the **Blank** theme.

**Pull request merged**
