### PR TITLE
Feature to Update SKU on Configurable products

### PR DESCRIPTION
**Pull request by fernandofauth**
### Description
    This is a simples update in two files that improve a new feature to possibilite update of SKUS when variations are changed. 

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16982) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @fernandofauth. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by orlangur** [comment]
@fernandofauth please fix builds.

**Comment by fernandofauth** [comment]
@orlangur okay, i'll do it .

**Comment by fernandofauth** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @fernandofauth. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @fernandofauth, here is your [new Magento instance](https://pr-16982.engcom.dev.magento.com).
Admin access: [https://pr-16982.engcom.dev.magento.com/admin](https://pr-16982.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`

**Comment by fernandofauth** [comment]
Hi @orlangur , after @rafaelstz make changes travis does not worked yet.
It's okay with that?

**Comment by rafaelstz** [comment]
Hi @fernandofauth, the CI are showing the issue message bellow when ran:

> 1) Magento\ConfigurableProduct\Test\Unit\Block\Product\View\Type\ConfigurableTest::testGetJsonConfig
> Trying to configure method "getOptionSkus" which cannot be configured because it does not exist, has not been specified, is final, or is static.

**Comment by orlangur** [comment]
Unfortunately, we can't accept such Pull Requests to 2.2 release line, new features should be delivered to 2.3 release line. For more information, please, refer to [Magento Code Contributions Guide](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#rules).

**Pull request closed without merging**
