### PR TITLE
[TEST] DO NOT TOUCH!

### PR DESCRIPTION
**Pull request by slavvka**
### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/123
https://github.com/magento/partners-magento2b2b/pull/39
https://github.com/magento/partners-magento2-infrastructure/pull/2
https://github.com/magento/inventory/pull/2902

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — APPROVED** [review]

**Review by VladimirZaets — APPROVED** [review]

**Review by VladimirZaets — APPROVED** [review]

**Review by VladimirZaets — DISMISSED** [review]

**Review by VladimirZaets — APPROVED** [review]

**Review by VladimirZaets — APPROVED** [review]

**Review by VladimirZaets — DISMISSED** [review]

**Review by VladimirZaets — DISMISSED** [review]

**Review by VladimirZaets — APPROVED** [review]

**Review by VladimirZaets — APPROVED** [review]

**Review by VladimirZaets — APPROVED** [review]

**Review by VladimirZaets — APPROVED** [review]

**Review by VladimirZaets — DISMISSED** [review]
111

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
dsdsds

**Review by VladimirZaets — DISMISSED** [review]
ddsds

**Review by VladimirZaets — APPROVED** [review]

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6948](https://jira.corp.magento.com/browse/ENGCOM-6948) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7300](https://jira.corp.magento.com/browse/ENGCOM-7300) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by slavvka** [comment]
@magento run all tests

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-7538](https://jira.corp.magento.com/browse/ENGCOM-7538) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Hi @slavvka @sidolov,
Do you still need this PR?

**Comment by slavvka** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
Hi @ihor-sviziev, we are still using it for testing purposes. We will close it once it's done. Thank you!

**Pull request closed without merging**
