### PR TITLE
magento/magento2#38845:"Area code not set" after update to 2.4.5-p8

### LINKED ISSUE #38845: "Area code not set" after update to 2.4.5-p8
### Preconditions and environment

- Magento version 2.4.5-p8 or 2.4-develop
- Deployment mode - production
- Magento_CSP module is enabled
- "dev/js/translate_strategy" is set to "embedded"

### Steps to reproduce

Enable Magento_CSP, and set "dev/js/translate_strategy" to "embedded". Than run bin/magento setup:static-content:deploy

### Expected result

Successful finish

### Actual result

Error: Area code not set

image (12)

### Additional information

Exception is triggered in class vendor/magento/framework/Translate.php

```
 /**
     * Initialize translation data
     *
     * @param string|null $area
     * @param bool $forceReload
     * @return $this
     */
    public function loadData($area = null, $forceReload = false)
    {
        $this->_data = [];
        if ($area === null) {
            $area = $this->_appState->getAreaCode();
        }
```

Stack trace 
image (11)

Possible solution -  emulate area code in vendor/magento/module-deploy/Service/DeployRequireJsConfig.php

```
/**
     * @param string $areaCode
     * @param string $themePath
     * @param string $localeCode
     * @return bool true on success
     */
    public function deploy($areaCode, $themePath, $localeCode)
    {
        /** @var \Magento\Framework\View\Design\ThemeInterface $theme */
        $theme = $this->themeList->getThemeByFullPath($areaCode . '/' . $themePath);
        /** @var \Magento\Theme\Model\View\Design $design */
        $design = $this->designFactory->create()->setDesignTheme($theme, $areaCode);
        /** @var ResolverInterface $locale */
        $locale = $this->localeFactory->create();
        $locale->setLocale($localeCode);
        $design->setLocale($locale);

        $assetRepo = $this->assetRepoFactory->create(['design' => $design]);
        /** @var \Magento\RequireJs\Model\FileManager $fileManager */
        $fileManager = $this->fileManagerFactory->create(
            [
                'config' => $this->requireJsConfigFactory->create(
                    [
                        'assetRepo' => $assetRepo,
                        'design' => $design,
                    ]
                ),
                'assetRepo' => $assetRepo,
            ]
        );

        \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\App\State::class)->emulateAreaCode(
            $areaCode,
            [$fileManager, 'createRequireJsConfigAsset']
        );
        
        //$fileManager->createRequireJsConfigAsset();

        $fileManager->createMinResolverAsset();

        return true;
    }
```    
    

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by quterorta**
- fixed issue by providing needed area code as a function argument

### Description (*)
This issue is caused because, during deployment of the static content, the plugin Magento\Csp\Plugin\GenerateAssetIntegrity from the Magento_Csp module generates integrity for the RequireJs config by loading the file content and hashing them. The main reason for this issue is that static content deployment is executing via CLI so the area wasn't set. But the changed class has in the constructor _code param with the needed area code, so all my fix is providing the needed area code as an argument (instead of a null value).

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38845

### Manual testing scenarios (*)

**Steps to reproduce:**
1. Set deployment mode as production (bin/magento deploy:mode:set production)
2. Enable the Magento_Csp module (bin/magento module:enable Magento_Csp, if module status changes, run bin/magento setup:upgrade)
3. Set "dev/js/translate_strategy" config to "embedded" (bin/magento config:set dev/js/translate_strategy embedded)
4. Flish caches (bin/magento cache:flush)
5. Run bin/magento setup:static-content:deploy

**Expected result:**
Successful finish
image

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by quterorta** [comment]
@magento run all tests

**Comment by quterorta** [comment]
run all tests

**Comment by quterorta** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Review by engcom-Hotel — APPROVED** [review]
Failed builds seem flaky to me. Hence approving this PR.

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi @quterorta,

Thanks for the collaboration & contribution!

:heavy_check_mark: QA Passed

**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Set deployment mode as production (bin/magento deploy:mode:set production)
- Enable the Magento_Csp module (bin/magento module:enable Magento_Csp, if module status changes, run bin/magento setup:upgrade)
- Set "dev/js/translate_strategy" config to "embedded" (bin/magento config:set dev/js/translate_strategy embedded)
- Flish caches (bin/magento cache:flush)
- Run bin/magento setup:static-content:deploy


**Before:** :heavy_multiplication_x: 

Screenshot 2024-07-22 at 11 16 43




**After:** :heavy_check_mark: 

Screenshot 2024-07-22 at 11 33 52



Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Unit Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

**Comment by engcom-Charlie** [comment]
Few test failures in recent 2 builds for functional B2B, CE and EE are not consistent and remaining are known issues. Hence moving it to Merge in Progress.

**Functional B2B: Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38922/f650d14f2d58c8d31a246153acd95e45/Functional/allure-report-b2b/index.html
image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38922/649ed7430a2cacff2acd6407f610f203/Functional/allure-report-b2b/index.html#categories/a644910ae0cb11e839a98baa21929b76/59a1de34ab4fa393/
image


**Functional CE: Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38922/84611a16475bb144ef443b0cc46aed7a/Functional/allure-report-ce/index.html
image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38922/2cd6911ab7e420c9ccff104f4f4c59ce/Functional/allure-report-ce/index.html#categories/a62c3d6db6631ba28c4130df03eca285/dad6ed895aaca664/
image

**Functional EE: Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38922/167e929e6a24b779007beef46bb130d2/Functional/allure-report-ee/index.html#categories
image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38922/f13306c4b7769c2f988d2241c5896358/Functional/allure-report-ee/index.html#categories/8f0831c1d06562890f5ec21062dae309/81cc980a7baa9646/
image

**Known issues in CE, EE, B2B:**
1. StorefrontAddBundleDynamicProductToShoppingCartWithDisableMiniCartSidebarTest: [#ACQE-6786](https://jira.corp.adobe.com/browse/ACQE-6786)
2. StorefrontCashOnDeliveryPaymentForSpecificCountryTest: [#ACQE-6774](https://jira.corp.adobe.com/browse/ACQE-6774)
3. StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest: [#ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331)
4. StorefrontLoginFormCheckDuplicateValidateMessageTest: [#ACQE-6799](https://jira.corp.adobe.com/browse/ACQE-6799)
5. TierPricingWhenPriceScopeIsWebsiteWorkingProperlyWithMultipleCurrenciesConfiguredTest: [#ACQE-6695](https://jira.corp.adobe.com/browse/ACQE-6695)

**Pull request merged**
