### PR TITLE
#29686: Fix no cross-sells on shopping cart page

### LINKED ISSUE #29686: No Cross-Sells on cart page
### Preconditions (*)

1. Magento Cloud 2.3.5. **Please note** the bug is in the Magento_Catalog module from Magento Open Source which is a part of Magento Cloud, see Source Code section below.
2. **Important**: make sure `row_id` <> `entity_id` for all records in the `catalog_product_entity` table

### Steps to reproduce (*)

1. Back Office: Choose a product (e.g. SKU-01), add a Cross-Sell to it (e.g. SKU-02).
2. Storefront: Add the chosen product (SKU-01) to cart
3. Go to cart page

### Expected result (*)

1. The SKU-02 product in the Cross Sell block

### Actual result (*)

1. The Cross-Sell block is not shown

### Source Code
https://github.com/magento/magento2/blob/18da36b7640c8fd25ccafbbad33454bd6e21a5a6/app/code/Magento/Catalog/Model/ResourceModel/Product/Link/Product/Collection.php#L260

The `$identifierField` = `row_id` on Magento Cloud but should be `entity_id`.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by andresams**
### Description (*)
The FK on table **catalog_product_link::product_id** was updated to use **catalog_product_entity::row_id** instead of entity_id, but an array in the Crosssell.php block from Magento_Checkout and Magento_TargetRule modules was not updated accordingly. Cross-sells won't show-up unless the entity_id and row_id are the same, which will happen if we add more products after creating and deleting Scheduled Updates to a product.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29686

### Manual testing scenarios (*)

1. Create Product "Test A"
2. Edit "Test A" and add 2 or more Scheduled Updates to it. 
3. Edit "Test A" again and delete all Scheduled Updates.
4. Create Product "Test B"
5. Edit Product "Test A" and add product "Test B" as a Cross-sell
6. Go to the frontend and add "Test A" to the shopping cart. The Shopping Cart will display no cross-sells.

### Questions or comments

The module Magento_TargetRule is from Magento EE and has the exact same issue. How can I provide an update for it?

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @andresams. Please, sign [Adobe CLA](http://opensource.adobe.com/cla.html) so we can proceed with the review of current PR. 

Thank you.

**Comment by andresams** [comment]
Hi @rogyar, it is done. Thank you.

**Comment by andresams** [comment]
@magento run all tests

**Review by sidolov — CHANGES_REQUESTED** [review]
@andresams could you please cover changes with automated test?

**Comment by rogyar** [comment]
Hi @andresams. I would suggest covering your fix with a simple MFTF test that will check that the system has the correct behavior.

There's a [documentation](https://devdocs.magento.com/mftf/docs/introduction.html) of the MFTF framework itself. 

You can also check some examples from some merged PRs:

https://github.com/magento/magento2/pull/27371/files
https://github.com/magento/magento2/pull/27343/files
https://github.com/magento/magento2/pull/27029/files

Here's also a shortlist of best practices for creating MFTF tests. 

https://github.com/magento/magento-functional-tests-migration/wiki/Best-practices

Thank you!

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Hi, @rogyar. In your opinion, will the coverage that already exists be sufficient.
dev/tests/integration/testsuite/Magento/Checkout/Block/Cart/CrosssellTest.php

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by rogyar** [comment]
Hi @engcom-Echo. I believe it might be sufficient. But we still need to extend it to reflect the scenario described in the "Steps to reproduce" section of the original issue.

**Comment by engcom-Echo** [comment]
Hi, @andresams. Unfortunately, can't reproduce this scenario. Please provide more detail. Accordingly, we cannot create a test for coverage.

**Comment by engcom-Echo** [comment]
Hi, @andresams. 
Step to reproduce
1. Create Product A
2. Create "Schedule update" for Product A
3. Detele Product A
Note :
After are steps we get results for the catalog_product_entity table. For new created products will is row_id <> entity_id .
4. Create Product B
5. Create Product C and cross-shell Product B
6. Go to Storefront and add to cart Product C
7. Go to "cart"  and "More Choices:" is present on the page and Product C appears in the block.
image
image

**Comment by engcom-Charlie** [comment]
@andresams could you please look at https://github.com/magento/magento2/pull/29899#issuecomment-701363146? Otherwise, we can't proceed with your PR.
Thank you.

**Comment by rogyar** [comment]
Hi @engcom-Echo. I just want to double-check we get all details into account. The original issue says that the problem reproduces only for Magento Commerce (Cloud). 
Have you tried to reproduce it using the Commerce version? 

Thanks. 

[original comment](https://github.com/magento/magento2/issues/29686#issuecomment-678059206)

**Comment by gabrieldagama** [comment]
Hi, @rogyar @engcom-Charlie I've tried to reproduce the issue and looked at the fix on this PR.

From what I can see, once the EE (Magento Commerce) version is installed, the fix proposed on this PR won't be effective since the block is replaced by `Magento\TargetRule\Block\Checkout\Cart\Crosssell`, so the fix has no effect.

Also tried to reproduce the issue following the steps and wasn't able to. 

@andresams your fix would be relevant if the EE module is installed and the `Magento\Checkout\Block\Cart\Crosssell` block had still being used.

I will be closing the PR for now, please, feel free to provide more details on how to reproduce the issue on a vanilla Magento and we can review it again.

**Pull request closed without merging**
