### PR TITLE
Remove improper unit test

### PR DESCRIPTION
**Pull request by orlangur**
it shall not pass code review as object under test is mocked and thus it does not test anything.

### Fixed Issues (if relevant)

Improper test introduced in https://github.com/magento/magento2/pull/13716

### Manual testing scenarios
Not needed.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by larsroettig — APPROVED** [review]

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-1105](https://jira.corp.magento.com/browse/ENGCOM-1105) has been created to process this Pull Request

**Comment by alepane21** [comment]
Hi there @orlangur,
actually the check that I made was on method joinUrlRewrite that is not mocked, so it checks that the conditions passed to joinUrl uses the right store_id.

**Comment by orlangur** [comment]
@alepane21 object under test shall not be mocked. In unit test "unit" is a whole object and not one method.

**Comment by alepane21** [comment]
Ok, thanks for the explanation.
To have the pull request accepted I had to add a unit test and this was the fastest way I found to di it, sorry!

**Comment by orlangur** [comment]
@alepane21 no problem 👍 You implemented an integration test also which fits perfectly for this type of change. Appreciate that!

**Pull request merged**
