### PR TITLE
Fixed issue 19628

### PR DESCRIPTION
**Pull request by mahendra1988**
### Description (*)
Admin Navigation menu should show a icon if it have a sub-menu

### Fixed Issues (if relevant)

1. magento/magento2#19628: Admin Navigation menu should show a icon if it have a sub-menu

### Manual testing scenarios (*)

1. login into the magento admin
2. You will not able to identify which menu have sub menu and which have direct link
For Example: Dashboard menu have direct link but sales, catalog and etc have sub-menu.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19629) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=19629) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: mahendra1988<br/>:x: advanipunit

**Comment by magento-engcom-team** [comment]
Hi @mahendra1988. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
@mahendra1988 Thanks for the contribution, however, I like the current appearance more, to be honest. The change overloads the UI, from my point of view.

**Comment by mahendra1988** [comment]
> @mahendra1988 Thanks for the contribution, however, I like the current appearance more, to be honest. The change overloads the UI, from my point of view.


@sivaschenko Yes, you are right that the current appearance is good but as Magento have modified the front menu design for indicate the submenu, so we should have same thing in admin, so it will be more user friendly.

Please let me know your thoughts for the same.
Design suggestions are also welcome.

**Comment by sivaschenko** [comment]
@mahendra1988 I think that there is no need to introduce the design changes to admin panel based on fronted, as these are completely different areas. The current appearance is more user-friendly from my point of view.

**Comment by ihor-sviziev** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, here is your [new Magento instance](https://pr-19629.instances.magento-community.engineering).
Admin access: [https://pr-19629.instances.magento-community.engineering/admin](https://pr-19629.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by ihor-sviziev** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, here is your [Magento instance](https://i-19629-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19629-2-3-develop.instances.magento-community.engineering/admin](https://i-19629-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ihor-sviziev** [comment]
**Before:**
https://i-19629-2-3-develop.instances.magento-community.engineering/admin
image


**After:**
https://pr-19629.instances.magento-community.engineering/admin
image

I think _before_ version looks much clear and understandable.

**Comment by sivaschenko** [comment]
Hi @mahendra1988 thanks for the pull request once again!

After the discussion between maintainers, we agreed that the current UI looks better and is more clear. Also, the issue that this pull request is fixing was closed as not a bug.

Considering the above, I am closing this pull request. Please feel free to contact me if you would like to discuss the case and have any additional updates/details that you think we did not take into account.

**Pull request closed without merging**
