### PR TITLE
Fix spelling in GQL schema comments

### PR DESCRIPTION
**Pull request by brendanfalkowski**
### Description (*)

Fix spelling.

### Manual testing scenarios (*)

None, affects comments.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19864) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @brendanfalkowski. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by osrecio — APPROVED** [review]
Thanks for your contribution @brendanfalkowski !

**Comment by magento-engcom-team** [comment]
Hi @osrecio, thank you for the review.
[ENGCOM-3714](https://jira.corp.magento.com/browse/ENGCOM-3714) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@brendanfalkowski thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by orlangur** [comment]
@osrecio such contributions should be placed in https://github.com/magento/graphql-ce I believe.

**Comment by osrecio** [comment]
@orlangur My fault, sorry.

@brendanfalkowski We talk internally and I need close this ticket. Can you create it in [graphql-ce](https://github.com/magento/graphql-ce) repo, please.

Thanks and sorry for the inconveniences.

**Comment by brendanfalkowski** [comment]
@orlangur + @osrecio — You're going to have to do more than that to stop me :)

Recreated the PR in the other repo here: https://github.com/magento/graphql-ce/pull/302

**Comment by brendanfalkowski** [comment]
Any chance at getting the PR reviewed and approved in the other repo?

**Comment by osrecio** [comment]
Hello @brendanfalkowski Maybe @naydav can help with the PR: magento/graphql-ce#302

**Pull request closed without merging**
