### PR TITLE
Update Layout.php

### PR DESCRIPTION
**Pull request by Maddesto**
trigger layout_render_before before layout rendering

### CODE REVIEW

**Comment by daim2k5** [comment]
Thank you for your contribution. Please accept the contributors license agreement so this PR can be further processed. This can be done by clicking the "Details" link next to the "license/cla" check below.

**Comment by piotrekkaminski** [comment]
@Maddesto can you update to latest develop branch and rerun Travis?

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-54160

**Comment by smdevdk** [comment]
Why is this still an issue?

**Comment by orlangur** [comment]
@smdevdk maybe it's not released yet and present only in `develop` branch?

**Comment by smdevdk** [comment]
It's been almost a year. Can someone get this thing moved along to production?

**Comment by orlangur** [comment]
@smdevdk, totally agree. I see a lot of such remarks these days and it looks like it's easier to release `2.2.0` than cherry-pick to `2.1.5` from `develop` all the fixes people need. Hope with current increased GitHub processing activity `2.2.*` releases will not fall behind so much.

**Comment by danslo** [comment]
This bug is still present in 2.1.9, so I guess this won't land in 2.1 anymore.

**Comment by orlangur** [comment]
Fix for this issue is only available on Magento 2.2.0 branch currently.

Anyone, do not hesitate to create a backport to `2.1-develop` if needed, see https://community.magento.com/t5/Magento-DevBlog/Pull-Requests-for-2-1-x-Patch-Releases/ba-p/65630 for details.

**Pull request merged**
