### PR TITLE
Fixes typo

### PR DESCRIPTION
**Pull request by jee1mr**
Fix for `2.3-develop` in: https://github.com/magento/magento2/pull/13283

imputType ==> inputType

### Description

Fixes typo

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [X] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15053) <br/>All committers have signed the CLA.

**Comment by VladimirZaets** [comment]
Hi @jee1mr, please, sign CLA, otherwise, we can't process your pull request

**Comment by jee1mr** [comment]
@VladimirZaets Done!

**Comment by magento-engcom-team** [comment]
@jee1mr thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VladimirZaets** [comment]
@jee1mr Thanks.

**Comment by magento-engcom-team** [comment]
Hi @jee1mr. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

**Comment by mzeis** [comment]
Note: already fixed in `2.3-develop` (as part of #13283), no forwardport needed.

**Pull request merged**
