### PR TITLE
MC-36959 Remove "compareArraysRecursively" logic duplication

### PR DESCRIPTION
**Pull request by le0n4ik**
### Description (*)
The compareArraysRecursively logic is realized in:

\Magento\TestFramework\Helper\CompareArraysRecursively

and

\Magento\TestFramework\TestCase\GraphQlAbstract::compareArraysRecursively

 

Realization and usage of \Magento\TestFramework\TestCase\GraphQlAbstract::compareArraysRecursively should be removed.

### Related Pull Requests
https://github.com/magento/catalog-storefront/pull/234
https://github.com/magento/partners-magento2ee/pull/312

### Fixed Issues (if relevant)
https://jira.corp.magento.com/browse/MC-36959

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @le0n4ik. Thank you for your collaboration. Please, make sure the current PR contains only necessary commits and the target branch is `2.4-develop`.

**Comment by lbajsarowicz** [comment]
@le0n4ik I changed the base to `2.4-develop` for you.

**Comment by mslabko** [comment]
@lbajsarowicz  please, don't change target if it was created to "develop-storefront"

**Comment by lbajsarowicz** [comment]
@le0n4ik OK. Please notify us when you rebase your code to be reviewable :)

**Comment by le0n4ik** [comment]
@rogyar can you please approve review?

**Pull request merged**
