### PR TITLE
Fix typo in less button definition

### PR DESCRIPTION
**Pull request by shochdoerfer**
Fix small typo in .less file.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### Ports

Forward port to `2.3-develop`: #10404

### CODE REVIEW

**Comment by DanielRuf** [comment]
Hi @shochdoerfer, great catch 👍 and congrats for the first contribution 🎉

**Comment by VladimirZaets** [comment]
Hi @shochdoerfer  , thank you for collaboration.
The Pull Request will be merged soon.

**Comment by magento-engcom-team** [comment]
@shochdoerfer thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @shochdoerfer. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

**Comment by mzeis** [comment]
Note: has already been [fixed](https://github.com/magento/magento2/commit/7a34cb0d3614e05a5682d8e0b47d8e3ff1181c52) in `2.3-develop`, no forwardport needed.

**Pull request merged**
