### PR TITLE
Fixed Magento installation with MySQL 8.

### PR DESCRIPTION
**Pull request by akaplya**
### Description (*)
Fixed Magneto installation with MySQL 8.

### Fixed Issues (if relevant)

It was impossible to install Magento 2.3.3 with MySQL 8.
The cause of this issue was a forced indexation triggered by the DB patch.
The first time indexation may cause DDL scripts execution. At the same time, Magento wraps DB patches with the transaction.
As a result, Magento tries to open a new connection to perform DDL, and the original transaction does not see a table that created after the transaction started.

Reasonable workaround - do not invoke indexation from the patch. If necessary, the indexer can be invalidated.
This is a safe operation that does not require DDL execution and could be invoked from the patch.

### Manual testing scenarios (*)

https://github.com/magento/magento2/issues/25294

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6205](https://jira.corp.magento.com/browse/ENGCOM-6205) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Review by kokoc — APPROVED** [review]

**Comment by engcom-Golf** [comment]
@magento run all tests

**Review by novikor — APPROVED** [review]
🚀

**Comment by magento-engcom-team** [comment]
Hi @novikor, thank you for the review.
[ENGCOM-6205](https://jira.corp.magento.com/browse/ENGCOM-6205) has been created to process this Pull Request

**Pull request merged**
