### PR TITLE
Removed laminas/laminas-db composer package

### PR DESCRIPTION
**Pull request by drpayyne**
### Description (*)

Removed laminas/laminas-db composer package

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33209

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by drpayyne** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Hi @drpayyne,
TBH I think it's better to get rid of Zend_DB_* instead of Laminas\Db\*. I'm pretty sure it would be backward incompatible, not sure it's worth doing that.

@sivaschenko, what do you think?

**Comment by Den4ik** [comment]
> TBH I think it's better to get rid of Zend_DB_* instead of Laminas\Db* as ZF1 is completely not supported, and that's legacy. I'm pretty sure it would be backward incompatible, not sure it's worth doing that.

Agree with @ihor-sviziev but looks it's very big work and not sure that it's possible now.
As I see in most cases used `Expression` from laminas-db and not sure that it's could be easily replaced.
+
Definition from laminas https://git.io/JnMiJ and usage from zf1 at https://git.io/JnM6d

**Comment by ihor-sviziev** [comment]
@Den4ik maybe we can use the following class everywhere? https://github.com/magento/magento2/blob/f5776a6637b618f691abf5131684fcd961825532/lib/internal/Magento/Framework/DB/Sql/Expression.php#L11

**Comment by Den4ik** [comment]
@ihor-sviziev Use extended class from zf1 is not the best solution. I preferrer replace usage of zf1 with laminas library :)

**Comment by sivaschenko** [comment]
Hi @drpayyne, thank you for the pull request! We have changed our plans regarding laminas-db package. We are going to help laminas to provide laminas-db compatibility with PHP 8.1 early. So we are currently suspending the elimination of this package. Sorry for the inconvenience and thanks for understanding!

I will share tasks covering our help to laminas packages in the project backlog when they are ready. Hope you'll be interested in contributing to laminas-db instead of removing it from Magento :)

**Comment by drpayyne** [comment]
No problem, @sivaschenko! And I'd be happy to contribute to Laminas as well.

**Pull request closed without merging**
