### PR TITLE
Reduce TierPriceManagement class complexity by quick refactor

### LINKED ISSUE #29477: [Issue] Reduce TierPriceManagement class complexity by quick refactor
This issue is automatically created based on existing pull request: magento/magento2#29202: Reduce TierPriceManagement class complexity by quick refactor

---------
### Preconditions (*)
I had to debug the issue of removing Tier price.  I found the class complex and code style rather poor.
That is why I extracted some repeated code to separate private methods with singular responsibility and explicit types.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Steps to reproduce (*)

1. ...
2. ...

**Actual Result:**

**Expected Result:**

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
I had to debug the issue of removing Tier price.  I found the class complex and code style rather poor.
That is why I extracted some repeated code to separate private methods with singular responsibility and explicit types.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29477: Reduce TierPriceManagement class complexity by quick refactor

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
I'm going to proceed with the PR during the weekend.

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
@magento create issue

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7993](https://jira.corp.magento.com/browse/ENGCOM-7993) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

The Tier Price functionality still works as previously (expected). 
Checked Get, Post and Delete
Screenshot from 2020-08-13 13-18-12

**Pull request merged**
