### PR TITLE
Improved error message when requirejs fails to load a component.

### LINKED ISSUE #36761: Suggestion for improved error reporting for require.js loading problems
### Summary

Hi there

I recently ran into a hard to figure out problem after a Magento upgrade, where one of the custom scripts we had could not be loaded through require.js.
It showed an error like this in the browser's console:
```
Failed to load the "{customComponent}" component.
```

This error is pretty vague and I had a hard time figuring out what was the problem, so I eventually started looking if there was a way to expose more details about the error.
And that lead me to the `app/code/Magento/Ui/view/base/web/js/core/renderer/layout.js` file.
I noticed that I was able to improve the output by outputting the error itself to the console instead of only a generic message (see below for proposed solution).

Once I added that, it was immediately clear what the error was, it wasn't a problem in the `{customComponent}` but in one of its dependencies, and it was eventually an easy fix.
But the time spend on trying to locate the error was like 5 times the time it took to fix the problem. So this extra error output can really help to find hard to diagnose javascript problems.

Would Magento be open to such an improvement? I could send in a PR if I know that it would be accepted.

### Examples

Not much time at the moment to figure out an example case, maybe I'll find some time next week or even later.

### Proposed solution

```diff
diff --git a/app/code/Magento/Ui/view/base/web/js/core/renderer/layout.js b/app/code/Magento/Ui/view/base/web/js/core/renderer/layout.js
index 5240fe55f6a..d8c6e7e3088 100644
--- a/app/code/Magento/Ui/view/base/web/js/core/renderer/layout.js
+++ b/app/code/Magento/Ui/view/base/web/js/core/renderer/layout.js
@@ -118,7 +118,8 @@ define([
                 component: node.component
             });
             loaded.resolve(node, constr);
-        }, function () {
+        }, function (e) {
+            consoleLogger.error(e);
             consoleLogger.error('componentLoadingFail', {
                 component: node.component
             });
```

### Release note

We've improved the output of the error when require.js can't load a certain component so it's easier for developers to figure out the cause of the error.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by hostep**
### Description (*)
When something goes wrong when trying to load a dependency through requirejs, the error message is not very clear and it's hard to find the real problem based on the error message.

Here we improve the error message and output more detailed information about the problem, which should help frontend developers in figuring out bugs in their code.

### Related Pull Requests
N/A

### Fixed Issues (if relevant)
1. Fixes magento/magento2#36761

### Manual testing scenarios (*)
1. Manually introduce a bug in the code: open the file `app/code/Magento/Checkout/view/frontend/web/js/view/summary/abstract-total.js` and add this problematic line:
```diff
--- a/app/code/Magento/Checkout/view/frontend/web/js/view/summary/abstract-total.js
+++ b/app/code/Magento/Checkout/view/frontend/web/js/view/summary/abstract-total.js
@@ -13,6 +13,8 @@ define([
     'use strict';

     return Component.extend({
+        problem: window.unexistingProp.unexistingProp,
+
         /**
          * @param {*} price
          * @return {*|String}
```
2. Have a Magento shop setup with at least one saleable product in the database
3. On the frontend, put the product in your cart and go to the checkout
4. Look at your browsers inspector

Before the changes, not clear what the problem is:
Screenshot 2024-07-24 at 19 44 48

After the changes: a lot more clearer what the problem is:
Screenshot 2024-07-24 at 19 51 01

### Questions or comments
There are almost no automated tests around this functionality, so I'm not bothering adding a test, because I don't know how I should do this.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hostep** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-November** [comment]
Hello @hostep,

Thank you for the collaboration and contribution!

### ✔️ QA Passed

Steps to reproduce:
1. Manually introduce a bug in the code: open the file `app/code/Magento/Checkout/view/frontend/web/js/view/summary/abstract-total.js` and add this problematic line:
```
--- a/app/code/Magento/Checkout/view/frontend/web/js/view/summary/abstract-total.js
+++ b/app/code/Magento/Checkout/view/frontend/web/js/view/summary/abstract-total.js
@@ -13,6 +13,8 @@ define([
     'use strict';

     return Component.extend({
+        problem: window.unexistingProp.unexistingProp,
+
         /**
          * @param {*} price
          * @return {*|String}
  ```
2. Go to frontend and add a product to cart.
3. Open console on checkout page.

### Before: ✖️
Log was not pointing to exact problem.
image

### After: ✔️
Getting clear log of where the problem lies.
image

Since the issue linked to pr is marked as feature request moving this to on hold till we get PO confirmation on the same.

Thank you.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Unit Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Unit Tests

**Comment by engcom-Charlie** [comment]
The Functional EE failures are not consistent in recent 2 builds on same code. They are not part of PR or not failing because of PR changes. The tests failures seems to be flaky.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38971/da6b0d2b4ccb1b88e9d59cde4cf41d87/Functional/allure-report-b2b/index.html#categories/6e0f61c8b67b0f191eaf93c92554bd16/51fb71bd452ddc80/

image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38971/a6bc715eb2f9825ebd2187f75e3a972b/Functional/allure-report-ee/index.html#categories

image

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
The Functional B2B failures are not consistent in recent 2 builds on same code. They are not part of PR or not failing because of PR changes. The tests failures seems to be flaky.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38971/c9baa554ca4955a06ec35f6fc9c18caf/Functional/allure-report-b2b/index.html#categories
image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38971/0817dc7a1a44928fdc648e96df33e321/Functional/allure-report-b2b/index.html#categories

image

**Pull request merged**
