### PR TITLE
Fixed-20788: Listing page no equal spacing in product in list view.

### PR DESCRIPTION
**Pull request by suryakant-krish**
### Description (*)

Listing page no equal spacing in product in list view #20788

### Fixed Issues (if relevant)

1. magento/magento2#20788: Listing page no equal spacing in product in list view.

### Manual testing scenarios (*)

1.Frontend -> open any product category Listing page

Expected result (*)
1.http://prntscr.com/me4gel

Actual result (*)
1.http://prntscr.com/me4grr

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by SyntaxKay** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @speedy008, here is your [Magento instance](https://i-20789-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20789-2-3-develop.instances.magento-community.engineering/admin](https://i-20789-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by SyntaxKay — APPROVED** [review]

**Comment by milindsingh** [comment]
@suryakant-krish Can you use less variable, rather than a fixed value for margin?
Thanks

**Comment by suryakant-krish** [comment]
@milindsingh,

I have replaced the hardcoded value with a variable.

**Comment by suryakant-krish** [comment]
@magento-engcom-team

Please review this PR.

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-4216](https://jira.corp.magento.com/browse/ENGCOM-4216) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi, @suryakant-krish can you please make the change applicable only for list view and only for configurable products.

Currently, the change is negatively affecting grid view especially for simple products:
image

**Comment by sidolov** [comment]
@suryakant-krish , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
