### PR TITLE
Resolve No validation "Minimum Qty" on "Minimum Qty Allowed in Shopping Cart" field 

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. magento/magento2#23895: No validation "Minimum Qty" on "Minimum Qty Allowed in Shopping Cart" field 

Solution: Add class "required-entry validate-number validate-greater-than-zero" to _prepareToRender of "Magento\CatalogInventory\Block\Adminhtml\Form\Field\Minsaleqty"

### Fixed Issues (if relevant)

1. magento/magento2#23895: No validation "Minimum Qty" on "Minimum Qty Allowed in Shopping Cart" field 

### Manual testing scenarios (*)

1. Go to "Store->Configurations->Catalog->Inventory"
2. Uncheck "Use system value" on "Minimum Qty Allowed in Shopping Cart" (Product Stock Options)
3. "Add Minimum Qty", leave them empty
image
4. Save configuration
5. Fill "Five" to field
6. Save configuration
=> Can not save with empty and not number qty

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by XxXgeoXxX** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX, here is your [Magento instance](https://i-23896-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23896-2-3-develop.instances.magento-community.engineering/admin](https://i-23896-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by XxXgeoXxX** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX, here is your [new Magento instance](https://pr-23896.instances.magento-community.engineering).
Admin access: [https://pr-23896.instances.magento-community.engineering/admin](https://pr-23896.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by XxXgeoXxX — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @XxXgeoXxX, thank you for the review.
[ENGCOM-5513](https://jira.corp.magento.com/browse/ENGCOM-5513) has been created to process this Pull Request
:eight_spoked_asterisk: @XxXgeoXxX, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @edenduong ! 

During testing We faced with some issues.

**_Problem 1:_**  Missing asterisk sign (*) in "Minimum Qty" title

**_Problem 2:_**  After entering valid data, the JS error does not disappear ( only after click "Save" button)

**Note:** You will be able to see the right behavior in section "Advanced Pricing" when creating product
test

@edenduong  Could you take a look?

Thanks!

**Comment by edenduong** [comment]
Hi @engcom-Alfa:
Thank you for your reply. However:

**All the field in SYSTEM -> CONFIG don't have asterisk sign.** 
**All the field in SYSTEM -> CONFIG :  After entering valid data, the JS error does not disappear.** 
Please check

I think it is **another issue**. And or simply it doesn't have the feature. It is not support in the SYSTEM->CONFIG now.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by edenduong** [comment]
@magento-engcom-team: Could I receive the "Award: bug fix" ? Thank you :)

**Comment by edenduong** [comment]
@sidolov : Could I receive the "Bugfix award" for this PR? Thank you :)

**Pull request merged**
