### PR TITLE
[MFTF] add AdminOpenCustomersGridActionGroup

### PR DESCRIPTION
**Pull request by Usik2203**
This PR add `AdminOpenCustomersGridActionGroup` and set `NavigateToAllCustomerPage` action group as deprecated

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/346
https://github.com/magento/partners-magento2b2b/pull/352

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @Usik2203. Thank you for your contribution. Please, take a look at the failing tests.

**Comment by Usik2203** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by Usik2203** [comment]
Hi @rogyar  
This PR is ready for review.
Thanks

**Review by rogyar — DISMISSED** [review]
The failing media gallery tests are not related to the current changeset

**Comment by Usik2203** [comment]
Hi @rogyar  
Could I kindly ask you to review related PRs for this one. 
Thanks !

**Comment by rogyar** [comment]
Hi @Usik2203, already did 😉

**Review by gabrieldagama — APPROVED** [review]

**Comment by gabrieldagama** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8275](https://jira.corp.magento.com/browse/ENGCOM-8275) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by ihor-sviziev** [comment]
@gabrieldagama thx for fixing PR status.

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
