### PR TITLE
Backend: Widget option alignment issue

### PR DESCRIPTION
**Pull request by suryakant-krish**
### Description (*)

1. This is direct PR.
2. Ref : https://github.com/magento/magento2/pull/20424
### Fixed Issues (if relevant)

1. magento/magento2#20424: Backend: Widget option alignment issue.

### Manual testing scenarios (*)

1. Login into admin panel > Content > Widgets > Click on Widget Options. Look at alignment Block name.

2. Actual Result.
actual-result

3. Expected Result.
expected-result

### Contribution checklist (*)
 - [yes ] Pull request has a meaningful description of its purpose
 - [yes ] All commits are accompanied by meaningful commit messages
 - [yes] All new or changed code is covered with unit/integration tests (if applicable)
 - [yes ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sidolov** [comment]
Hi @suryakant-krish , your [original PR](https://github.com/magento/magento2/pull/20424) was closed due to inactivity, please, reopen and update PR to 2.3-develop first.

**Comment by suryakant-krish** [comment]
@sidolov,
I have created this PR for 2.3.

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-21061.instances.magento-community.engineering).
Admin access: [https://pr-21061.instances.magento-community.engineering/admin](https://pr-21061.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rogyar** [comment]
@suryakant-krish now it looks much better. Thank you

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4306](https://jira.corp.magento.com/browse/ENGCOM-4306) has been created to process this Pull Request

**Comment by abrarpathan19** [comment]
It looks better. Thank you

**Comment by sivaschenko** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [Magento instance](https://i-21061-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21061-2-3-develop.instances.magento-community.engineering/admin](https://i-21061-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sivaschenko** [comment]
Hi @suryakant-krish I wasn't able to reproduce the issue on 2.3-develop:

image

Please check if the issue is still actual

**Comment by sidolov** [comment]
@suryakant-krish , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
