### PR TITLE
Prevent opcache invalidation on every request

### PR DESCRIPTION
**Pull request by barryvdh**
The app/etc/env.php and app/etc/config.php files are invalidated on each request. This is not efficient and undermines the opcache.
1. Those files are not cached
2. It wastes memory by invalidating these each request
3. By increasing wasted memory, opcache is restarted too often or uses memory for wasted items.

Opcache should be refreshed by deployments if required, not every request. Otherwise the cache flush operations should clear the opcache files, but not on every request. Also described https://twitter.com/_jribas_/status/1415962210803896322?s=19 and https://magentocommeng.slack.com/archives/C9QB05WJG/p1626427975031400

You can verify this by running `opcache_get_status()` on the webserver you also use for Magento. You will see an increase in wasted_memory on every request. When disabling the line, you will see it remain 0.

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
Most of my Clients have immutable deployment in place. I believe the "feature" introduced in Magento should be configurable in `env.php`, so this way if you have immutable deployment in place, you should be able to completely turn this off.

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by sshymko** [comment]
The issue is only reproducible with the php.ini setting `opcache.validate_timestamps = Off`.
More details and workarounds: https://twitter.com/SergiiShymko/status/1416133428638937088?s=20

**Comment by barryvdh** [comment]
Yes it doesn't seem to match the description on the PHP documentation in that case. It is however the best setting performance wise, so probably most common.

**Comment by barryvdh** [comment]
For reference, this basically reverts https://github.com/magento/magento2/commit/1bc5818c363b750d9c0fa923066ce5d5ec9537ea
I don't really see why this is essential for a test. If the runtime configuration changes in a test, it shouldn't have to impact production code to work around it.

**Comment by ihor-sviziev** [comment]
@xmav do you remember why the use case for that fix?

**Comment by xmav** [comment]
@ihor-sviziev there were issues with Web-API tests. Please run them few times to confirm they are stable

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests B2B, WebAPI Tests (1st trial to make sure they’re not failing)

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE, WebAPI Tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @barryvdh,
Could you fix WebAPI test failures?
Maybe, there is a way to do these invalidations only for WebAPI requests?

**Comment by barryvdh** [comment]
The error is `{"message":"Sample URL's domain is not in list of downloadable_domains in env.php."}` on the Rest API for EE. So I assume the test is adding something to the env.php file. I don't have access to EE, so hard for me to tell, but I would add an fpm reload in the rest, after changing the config. Or change the opcache configuration for the test to disable opcache for the env.php file.

**Comment by Den4ik** [comment]
@barryvdh @ihor-sviziev I just runned 23ee tests and could confirm @xmav comment. Current failed WebAPI tests related to changes.
In this case I completely agree with @lbajsarowicz and believe that we can improve it

**Comment by Den4ik** [comment]
I believe that we can use similar solution for fixing WebAPI tests that used int https://github.com/magento/magento2/blob/2.4-develop/dev/tests/api-functional/testsuite/Magento/Catalog/Api/ProductRepositoryInterfaceTest.php#L113-L129

**Comment by Den4ik** [comment]
@barryvdh Could you please update PR?

**Comment by barryvdh** [comment]
Sorry not really what to fix. I don't really how those tests are relevant to the API, but maybe you can fix that separately or append my PR.

**Comment by ihor-sviziev** [comment]
@Den4ik, could you help with fixing tests?

**Comment by Den4ik** [comment]
@magento run all test

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE, Functional Tests B2B, Functional Tests CE, Integration Tests, Unit Tests, WebAPI Tests

**Comment by ihor-sviziev** [comment]
Note web api tests are passing now (restarted to make sure it's not fake), everything else looks not related

**Comment by ihor-sviziev** [comment]
@Den4ik, looks like it didn't help. The `testCreateSavesTitleInStoreViewScope` is failing on 2nd run https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/33505/e482fa7c975244f510db8ac06a09f1d7/WebApi/console-error-logs.html

**Comment by Den4ik** [comment]
> @Den4ik, looks like it didn't help. The `testCreateSavesTitleInStoreViewScope` is failing on 2nd run https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/33505/e482fa7c975244f510db8ac06a09f1d7/WebApi/console-error-logs.html

@ihor-sviziev  I'll check it on we today

**Comment by Den4ik** [comment]
@ihor-sviziev soap tests are passed locally

2021-08-17-17-04-36@2x

Let's try to rerun it

**Comment by Den4ik** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9185](https://jira.corp.magento.com/browse/ENGCOM-9185) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
Let's re-run the WebAPI tests again to make sure that was temporary issue
@magento run WebAPI Tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@Den4ik 
re-running of web api tests again failed on the same test
https://github.com/magento/magento2/pull/33505/checks?check_run_id=3359219984
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/33505/[…]19cad2/WebApi/console-error-logs.html
feels like the suggested solution isn't working
could you check it?

**Comment by Den4ik** [comment]
I think that it should check some one from core team with all configurations that used on CI because locally it always passed on 23EE.

@sdzhepa Could you assist forward it to correct person

**Comment by thlassche** [comment]
Can we get some movement on this one? 

Looks like changes requested is not the proper lane for this one right now.

@magento run WebAPI Tests

**Comment by Den4ik** [comment]
@sidolov @gabrieldagama Could you assist? Without access to EE we could not figure out issue with tests, that passed on 2.3  EE

**Comment by sidolov** [comment]
@Den4ik to be honest it's not clear what assistance is required, could you please explain? I see failed test on CE edition and it's probably possible to reproduce it locally

**Comment by Den4ik** [comment]
> @ihor-sviziev soap tests are passed locally
> 
> 
> 
> 2021-08-17-17-04-36@2x
> 
> 
> 
> Let's try to rerun it

@sidolov  tests are passed locally. For some runs it passed here, and failed for another one

**Comment by Den4ik** [comment]
@magento run WebAPI Tests

**Comment by sidolov** [comment]
@Den4ik it's an indication of bad tests isolation, they are running in batches and depending on tests count (CE, EE, or B2B has a different amount of test) will be allocated to different batches. In this case some test that are using the same fixture causing the issue in the fixed test

**Comment by choussamaster** [comment]
same bug with magento 2.3.7-p1 Cloud even with opcache.memory_consumption=2048 we arrive at saturation and opcache reboot

**Comment by xmav** [comment]
Hopefully following diagram will explain what happens with tests:

```TestA Start -> add domains to app/etc/env.php from fixture -> app/etc/env.php cached -> TestBody -> Rolback domains from app/etc/env.php in rollback fixture -> app/etc/env.php cached -> TestB Start -> add domains to app/etc/env.php from fixture -> TestBody -> Failure```

As you may see TestB use cached app/etc/env.php after rollback and that cause "domain is not in list of downloadable_domains in env.php" error.
So having some delay between affected tests or in corresponding data fixture should solve the problem. I belive opcache.revalidate_freq is set to default value which is 2s

**Comment by thlassche** [comment]
Can't we just add the opcache clear for the env file on init of these tests? Probably faster than introducing delays

**Comment by xmav** [comment]
Tests are running as CLI process, SUT is running as web server. So you need a way to reset Opcache for web as they are in different processes

**Comment by ihor-sviziev** [comment]
@xmav Can we create some controller that will be available only during running tests and do the invalidation? If so, we can send a request to this controller from the tests.

**Comment by Den4ik** [comment]
> @xmav Can we create some controller that will be available only during running tests and do the invalidation? If so, we can send a request to this controller from the tests.

For me It looks like masking the problem

**Comment by barryvdh** [comment]
I don't think the config is supposed to be changed on the fly, so resetting it before tests makes sense imho. Or maybe validate timestamps in opcache.

**Comment by ihor-sviziev** [comment]
What is the reason for storing these domains in the env.php file?

**Comment by torhoehn** [comment]
Finally it was merged! 🥳

**Pull request merged**
