### PR TITLE
add sourceMap generation for less files in developer mode

### LINKED ISSUE #38982: [Issue] add sourceMap generation for less files in developer mode
This issue is automatically created based on existing pull request: magento/magento2#38977: add sourceMap generation for less files in developer mode

---------

### Description (*)

Currently when running magento 2 in developer mode with server-side less compilation it's very hard to detect where a style is coming from. The only workaround is to use Grunt. 
However the underlying library for less compilation supports sourcemap generation with a flag that can be toggled based on the mode magento is in. 

### Manual testing scenarios (*)

1. Switch magento 2 in developer mode 
2. Let it regenerate css from the less files
3. Check inspector to see the source file responsible for the code 

image
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ioweb-gr**
### Description (*)

Currently when running magento 2 in developer mode with server-side less compilation it's very hard to detect where a style is coming from. The only workaround is to use Grunt. 
However the underlying library for less compilation supports sourcemap generation with a flag that can be toggled based on the mode magento is in. 

### Manual testing scenarios (*)

1. Switch magento 2 in developer mode 
2. Let it regenerate css from the less files
3. Check inspector to see the source file responsible for the code 

image
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38982: add sourceMap generation for less files in developer mode

### CODE REVIEW

**Comment by ioweb-gr** [comment]
@magento run all test

**Comment by ioweb-gr** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento create issue

**Review by Eddcapone — COMMENTED** [review]
Not working.
I tried your change and then called `grunt refresh` to regenerate the less files, but it still does not generate source maps. I enabled source maps in the browser dev tools.

EDIT: Hold up! It works after I deleted my whole static files first with

```
rm -rf pub/static/frontend/* pub/static/adminhtml/*
```
and then running: `php bin/magento setup:static-content:deploy -f`

I need to check if it works with and without your solution applied.

**Comment by ioweb-gr** [comment]
> Not working.
> I tried your change and then called `grunt refresh` to regenerate the less files, but it still does not generate source maps. I enabled source maps in the browser dev tools.
> 
> EDIT: Hold up! It works after I deleted my whole static files first with
> 
> ```
> rm -rf pub/static/frontend/* pub/static/adminhtml/*
> ```
> and then running: `php bin/magento setup:static-content:deploy -f`
> 
> I need to check if it works with and without your solution applies.

Actually my patch was just for server side compilation not for grunt.

**Comment by Eddcapone** [comment]
@ioweb-gr Grunt is also running on server side.

**Comment by ioweb-gr** [comment]
True it's in server side compilation mode but uses external tool to process the less files and not the library https://github.com/wikimedia/less.php/ that Magento uses in the default server side compilation.

Forgive my wrong use of the server side compilation term, I mean the Magento's internal server side compilation tool and not grunt

**Comment by Eddcapone** [comment]
Ok, I can confirm that the source map generation does work with your change, and it does not work without your change!

But the problem is, that in magento 2 you would not develop with `php bin/magento setup:static-content:deploy -f`, this would take way too much time. We would rather need a solution to fix grunt not generating any source files anymore.

But I would add your change nevertheless. It is better than status quo. At the moment we have no source maps at all...

Good job!

**Review by Eddcapone — APPROVED** [review]

**Comment by ioweb-gr** [comment]
With some third party themes in the market you can't use grunt as they override the default generation of static files to optimize things. You can't avoid it some times. 

Moreover in developer mode, the static files get generated dynamically so on a good server it's not that much of an issue. 

Grunt sometimes takes the same time to generate a new build. If it was webpack it would be a different story but with grunt it's not so much faster in most cases :(

**Comment by Eddcapone** [comment]
@ioweb-gr I would never buy such a theme, because developing with setup:static-content:deploy would take a huge amount of time. You would need to call it each time you make a tiny change and want to test it.

> Moreover in developer mode, the static files get generated dynamically so on a good server it's not that much of an issue.

Initially the files are getting generated, but it does not detect changes in the code. Let's say you want to change the background color of a container and need to change code in a less file, then it wont be enough to just reload the site. You need to recompile everything, which takes alot of time. Thats were grunt comes into play. Grunt will detect the change in that file and recompiles that file only and it only takes a few seconds.

**Comment by ioweb-gr** [comment]
Nonetheless it's very common in the themes especially those that provide some custom css sections inside of the configuration files.

Also for grunt I've seen some other preventive cases

1. Some times it's handing //magento_import directive differently
2. Some times live reload isn't able to connect especially in some hosting environments preventing effective use

All I'm saying is sometimes it's not worth the trouble when you can simply run n98-magerun2 d:a:c and hit reload other than that I totally agree with you. 

Personally I think that M2 needs a better system overall for frontend processing other than require and grunt / less which will help with extracting critical css, chunk properly and deliver in a proper way only the necessary bundles to the client optimizing it overall

**Comment by ioweb-gr** [comment]
I'd also like to say that even with Luma and a child theme, sometimes grunt doesn't provide the same result as just clearing all static files and letting the system regenerate them, especially if you've enabled minification and critical path. 

Generally I see grunt producing inconsistent results to what appears in production when running a full deployment therefore sometimes I feel it's actually making me slower than just deleting the generated files on demand in developer mode and letting the system regenerate them. 

Frankly I wish the system would use one tool for compilation for both development and production and stick to that (preferrably outside of the internal php framework)

**Comment by engcom-November** [comment]
Hello @ioweb-gr,

Thank you for the collaboration and contribution!

### ✔️ QA Passed

**Steps to reproduce:**
1. Switch magento 2 in developer mode
2. Let it regenerate css from the less files
3. Check inspector to see the source file responsible for the code

### Before: ✖️
Cannot see the source map of the files.
image

### After: ✔️
Able to see the sorce map of the files.
image

**Comment by engcom-November** [comment]
@ioweb-gr, please update the branch so we can move ahead with the pr.

**Comment by ioweb-gr** [comment]
How about now?

**Comment by engcom-November** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
Since there are build failures moving this to **Extended testing**.

**Comment by engcom-November** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Static Tests, Unit Tests

**Comment by engcom-November** [comment]
@ioweb-gr, It looks like the repo is blocked for us to commit fixes, could you please look into the failures and fix it.

**Comment by ioweb-gr** [comment]
Hi @engcom-November 

I see in the tests two errors 

1. Missing class description and 
2. State::getMode is used twice (fixed by https://github.com/magento/magento2/pull/38977/commits/a7f95885e8ac6b2a94ffad4c6da22da33d7f734f) 

What description do you want to add in the class, as it's not related to my PR ?

Anything else you need me to modify? 

PS: Is it possible to allow write access to my fork?

**Comment by engcom-November** [comment]
Hi @ioweb-gr,

For the static failure you can give a short class description such as `Processes LESS files into CSS`.

It is possible to give maintainers write access to the fork, you can follow this [documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for the same.

**Comment by ioweb-gr** [comment]
It seems I can't allow the edit from maintainers due to the fork residing in an organization

https://github.com/orgs/community/discussions/5634

Anyways here it is https://github.com/magento/magento2/pull/38977/commits/52da6505fb34b23a47fe9db5e930a15d26557711

**Comment by engcom-November** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
@ioweb-gr, there is still a unit test failure, please fix it.

**Comment by ioweb-gr** [comment]
I'm not sure what this error means, could you offer some guidance please?

**Comment by engcom-November** [comment]
The `ProcessorTest::testProcessContentNotEmpty` is a genuine failure, you can ignore the rest, they seem to be flaky.

It looks like `testProcessContentNotEmpty` test is asserting only the css, but as you have added sourceMap to the parser, the assertion is failing. If you could run the same test on your end you can see the difference in actual and expected result.

**Comment by hostep** [comment]
I took a look at the failed unit test out of curiosity, but then I noticed that it expects the sourcemap to contain absolute path's on a file system, which will be different for everybody running the tests, so that's not good. No idea how to fix this, if somebody has an idea?

But then I noticed something worse, in that the feature introduced here is not working correctly at all. If you take a look at the screenshot from 2 days ago, you'll notice that the path to the source starts with `https://` and then halfway suddently also contains a absolute path to a filesystem directory `/opt/homebrew/var/www/...`
This means that clicking the link in your browser will never work.

After some fiddling around myself I found a possible workaround for that last thing:
```diff
diff --git a/lib/internal/Magento/Framework/Css/PreProcessor/Adapter/Less/Processor.php b/lib/internal/Magento/Framework/Css/PreProcessor/Adapter/Less/Processor.php
index 8f40ab044c0..a27b594de49 100644
--- a/lib/internal/Magento/Framework/Css/PreProcessor/Adapter/Less/Processor.php
+++ b/lib/internal/Magento/Framework/Css/PreProcessor/Adapter/Less/Processor.php
@@ -66,10 +66,14 @@ class Processor implements ContentProcessorInterface
     {
         $path = $asset->getPath();
         try {
+            $mode = $this->appState->getMode();
             $parser = new \Less_Parser(
                 [
                     'relativeUrls' => false,
-                    'compress' => $this->appState->getMode() !== State::MODE_DEVELOPER
+                    'compress' => $mode !== State::MODE_DEVELOPER,
+                    'sourceMap' => $mode === State::MODE_DEVELOPER,
+                    'sourceMapRootpath' => '/',
+                    'sourceMapBasepath' => '/absolute/path/to/var/view_preprocessed/pub/',
                 ]
             );
```

However, this is now using a hardcoded path, so we need to find some code that dynamically inserts `'/absolute/path/to/var/view_preprocessed/pub/'` somehow.

Just my 2 cents after some debugging, will leave it be for now as I have other things planned for this evening :)

**Comment by ioweb-gr** [comment]
DirectoryList should provide the path to var dir I think. Is there any chance the view_preprocessed/pub path will be changed in any scenario?

**Comment by ioweb-gr** [comment]
I've tested with 

```
            $mode = $this->appState->getMode();
            $parser = new \Less_Parser(
                [
                    'relativeUrls' => false,
                    'compress' => $mode !== State::MODE_DEVELOPER,
                    'sourceMap' => $mode === State::MODE_DEVELOPER,
                    'sourceMapRootpath' => '/',
                    'sourceMapBasepath' => $this->directoryList->getPath(DirectoryList::TEMPLATE_MINIFICATION_DIR),
                ]
            );
```

Both constants could be used

image


And the logged path is like this from CLI which is the filesystem root 

[2024-09-06T05:58:03.231610+00:00] main.INFO: sourceMapBasepath: /var/www/vhosts/<mydomain>/httpdocs/var/view_preprocessed [] [] but the system stores in 

However this path is actually not usable either in the browser context which displays 

image


Moreover, as I was experimenting with writing a userscript lately, I noticed browsers nowdays restrict local filesystem access by default when loading websites for security reasons unless you toggle a flag in their configuration options. So I don't think it can load them from the filesystem anyways.  

So unless the sources are available from the domain actually serving the website, is it even possible to make it work out of the box to link directly to the file?

**Comment by ioweb-gr** [comment]
Basically to make the link work, the less files themselves would need to be deployed in their position in pub/static dir to make them accessible as I see it in developer mode

**Review by Eddcapone — APPROVED** [review]

**Comment by hostep** [comment]
Hey @ioweb-gr, can you try it with the following?

```
'sourceMapBasepath' => $this->directoryList->getPath(DirectoryList::TEMPLATE_MINIFICATION_DIR) . '/pub/',
```

With my short testing from yesterday, this appeared to work and the map files got symlinked from `var/view_preprocessed` to `pub` and were accessible from my browser.

**Comment by ioweb-gr** [comment]
`'sourceMapBasepath' => $this->directoryList->getPath(DirectoryList::TEMPLATE_MINIFICATION_DIR) . '/pub/',`

this worked for me but the constant is deprecated

**Comment by ioweb-gr** [comment]
I've added the change as it's one step forward nonetheless

**Review by Eddcapone — APPROVED** [review]

**Comment by Eddcapone** [comment]
@magento run all tests

**Comment by Eddcapone** [comment]
@engcom-November Which further steps are necessary so you can proceed with this ticket?

**Comment by hostep** [comment]
Well, we will need to fix the Static & Unit tests at least.

Here's a proposal for fixing the static tests:
```diff
diff --git a/lib/internal/Magento/Framework/Css/PreProcessor/Adapter/Less/Processor.php b/lib/internal/Magento/Framework/Css/PreProcessor/Adapter/Less/Processor.php
index 82925a01f53..f1f2192a9a6 100644
--- a/lib/internal/Magento/Framework/Css/PreProcessor/Adapter/Less/Processor.php
+++ b/lib/internal/Magento/Framework/Css/PreProcessor/Adapter/Less/Processor.php
@@ -6,6 +6,7 @@
 namespace Magento\Framework\Css\PreProcessor\Adapter\Less;
 
 use Magento\Framework\App\Filesystem\DirectoryList;
+use Magento\Framework\App\ObjectManager;
 use Magento\Framework\App\State;
 use Magento\Framework\Css\PreProcessor\File\Temporary;
 use Magento\Framework\Phrase;
@@ -41,6 +42,10 @@ class Processor implements ContentProcessorInterface
      * @var Temporary
      */
     private $temporaryFile;
+
+    /**
+     * @var DirectoryList
+     */
     private DirectoryList $directoryList;
 
     /**
@@ -50,19 +55,20 @@ class Processor implements ContentProcessorInterface
      * @param State $appState
      * @param Source $assetSource
      * @param Temporary $temporaryFile
+     * @param ?DirectoryList $directoryList
      */
     public function __construct(
         LoggerInterface $logger,
         State $appState,
         Source $assetSource,
         Temporary $temporaryFile,
-        DirectoryList $directoryList
+        ?DirectoryList $directoryList = null,
     ) {
         $this->logger = $logger;
         $this->appState = $appState;
         $this->assetSource = $assetSource;
         $this->temporaryFile = $temporaryFile;
-        $this->directoryList = $directoryList;
+        $this->directoryList = $directoryList ?: ObjectManager::getInstance()->get(DirectoryList::class);
     }
 
     /**
@@ -73,13 +79,18 @@ class Processor implements ContentProcessorInterface
         $path = $asset->getPath();
         try {
             $mode = $this->appState->getMode();
+            $sourceMapBasePath = sprintf(
+                '%s/pub/',
+                $this->directoryList->getPath(DirectoryList::TEMPLATE_MINIFICATION_DIR)
+            );
+
             $parser = new \Less_Parser(
                 [
                     'relativeUrls' => false,
                     'compress' => $mode !== State::MODE_DEVELOPER,
                     'sourceMap' => $mode === State::MODE_DEVELOPER,
                     'sourceMapRootpath' => '/',
-                    'sourceMapBasepath' => $this->directoryList->getPath(DirectoryList::TEMPLATE_MINIFICATION_DIR) . '/pub/'
+                    'sourceMapBasepath' => $sourceMapBasePath,
                 ]
             );
```

Additionally I made it more backwards compatible by injecting the `DirectoryList` dep as optional, like [recommended over here](https://developer.adobe.com/commerce/contributor/guides/code-contributions/backward-compatibility-policy/#adding-a-constructor-parameter)

**Comment by hostep** [comment]
And here's my proposal to fix unit tests, it involves having a different resulting test css file for production or developer module. In case of developer mode, I'm doing some source map normalisation to make the output more readable and removing the absolute file paths, so it should (hopefully) work the same on every machine:

```diff
diff --git a/lib/internal/Magento/Framework/Css/Test/Unit/PreProcessor/Adapter/Less/ProcessorTest.php b/lib/internal/Magento/Framework/Css/Test/Unit/PreProcessor/Adapter/Less/ProcessorTest.php
index 4e50808ea02..26ffa78abdd 100644
--- a/lib/internal/Magento/Framework/Css/Test/Unit/PreProcessor/Adapter/Less/ProcessorTest.php
+++ b/lib/internal/Magento/Framework/Css/Test/Unit/PreProcessor/Adapter/Less/ProcessorTest.php
@@ -7,6 +7,7 @@ declare(strict_types=1);
 
 namespace Magento\Framework\Css\Test\Unit\PreProcessor\Adapter\Less;
 
+use Magento\Framework\App\Filesystem\DirectoryList;
 use Magento\Framework\App\State;
 use Magento\Framework\Css\PreProcessor\Adapter\Less\Processor;
 use Magento\Framework\Css\PreProcessor\File\Temporary;
@@ -23,8 +24,8 @@ class ProcessorTest extends TestCase
     const ASSET_PATH = 'test-path';
 
     const TMP_PATH_LESS = '_file/test.less';
-
-    const TMP_PATH_CSS = '_file/test.css';
+    const TMP_PATH_CSS_PRODUCTION = '_file/test-production.css';
+    const TMP_PATH_CSS_DEVELOPER = '_file/test-developer.css';
 
     const ERROR_MESSAGE = 'Test exception';
 
@@ -52,6 +53,10 @@ class ProcessorTest extends TestCase
      * @var Temporary|MockObject
      */
     private $temporaryFileMock;
+    /**
+     * @var DirectoryList|MockObject
+     */
+    private $directoryListMock;
 
     /**
      * Set up
@@ -69,12 +74,16 @@ class ProcessorTest extends TestCase
         $this->temporaryFileMock = $this->getMockBuilder(Temporary::class)
             ->disableOriginalConstructor()
             ->getMock();
+        $this->directoryListMock = $this->getMockBuilder(DirectoryList::class)
+            ->disableOriginalConstructor()
+            ->getMock();
 
         $this->processor = new Processor(
             $this->loggerMock,
             $this->appStateMock,
             $this->assetSourceMock,
-            $this->temporaryFileMock
+            $this->temporaryFileMock,
+            $this->directoryListMock,
         );
     }
 
@@ -89,7 +98,7 @@ class ProcessorTest extends TestCase
 
         $this->appStateMock->expects(self::once())
             ->method('getMode')
-            ->willReturn(State::MODE_DEVELOPER);
+            ->willReturn(State::MODE_PRODUCTION);
 
         $this->assetSourceMock->expects(self::once())
             ->method('getContent')
@@ -120,7 +129,7 @@ class ProcessorTest extends TestCase
 
         $this->appStateMock->expects(self::once())
             ->method('getMode')
-            ->willReturn(State::MODE_DEVELOPER);
+            ->willReturn(State::MODE_PRODUCTION);
 
         $this->assetSourceMock->expects(self::once())
             ->method('getContent')
@@ -141,7 +150,7 @@ class ProcessorTest extends TestCase
     }
 
     /**
-     * Test for processContent method (not empty content)
+     * Test for processContent method in production mode (not empty content)
      */
     public function testProcessContentNotEmpty()
     {
@@ -149,7 +158,7 @@ class ProcessorTest extends TestCase
 
         $this->appStateMock->expects(self::once())
             ->method('getMode')
-            ->willReturn(State::MODE_DEVELOPER);
+            ->willReturn(State::MODE_PRODUCTION);
 
         $this->assetSourceMock->expects(self::once())
             ->method('getContent')
@@ -170,11 +179,46 @@ class ProcessorTest extends TestCase
 
         $clearSymbol = ["\n", "\r", "\t", ' '];
         self::assertEquals(
-            trim(str_replace($clearSymbol, '', file_get_contents(__DIR__ . '/' . self::TMP_PATH_CSS))),
+            trim(str_replace($clearSymbol, '', file_get_contents(__DIR__ . '/' . self::TMP_PATH_CSS_PRODUCTION))),
             trim(str_replace($clearSymbol, '', $this->processor->processContent($assetMock)))
         );
     }
 
+    /**
+     * Test for processContent method in developer mode (not empty content)
+     */
+    public function testProcessContentNotEmptyInDeveloperMode()
+    {
+        $assetMock = $this->getAssetMock();
+
+        $this->appStateMock->expects(self::once())
+            ->method('getMode')
+            ->willReturn(State::MODE_DEVELOPER);
+
+        $this->assetSourceMock->expects(self::once())
+            ->method('getContent')
+            ->with($assetMock)
+            ->willReturn(self::TEST_CONTENT);
+
+        $this->temporaryFileMock->expects(self::once())
+            ->method('createFile')
+            ->with(self::ASSET_PATH, self::TEST_CONTENT)
+            ->willReturn(__DIR__ . '/' . self::TMP_PATH_LESS);
+
+        $assetMock->expects(self::once())
+            ->method('getPath')
+            ->willReturn(self::ASSET_PATH);
+
+        $this->loggerMock->expects(self::never())
+            ->method('critical');
+
+        $clearSymbol = ["\n", "\r", "\t", ' '];
+        self::assertEquals(
+            trim(str_replace($clearSymbol, '', file_get_contents(__DIR__ . '/' . self::TMP_PATH_CSS_DEVELOPER))),
+            trim(str_replace($clearSymbol, '', $this->normalizeInlineSourceMap($this->processor->processContent($assetMock))))
+        );
+    }
+
     /**
      * @return File|MockObject
      */
@@ -186,4 +230,34 @@ class ProcessorTest extends TestCase
 
         return $assetMock;
     }
+
+    /**
+     * - find json part of sourcemap
+     * - url decode it
+     * - replace \/ with / in source filenames
+     * - remove absolute path in filename, make it a relative path
+     */
+    private function normalizeInlineSourceMap(string $css): string
+    {
+        $regexBegin = 'sourceMappingURL=data:application/json,';
+        $regexEnd = '*/';
+        $regex = '@' . preg_quote($regexBegin, '@') . '([^\*]+)' . preg_quote($regexEnd, '@') . '@';
+
+        if (preg_match($regex, $css, $matches) === 1) {
+            $inlineSourceMapJson = $matches[1];
+            $inlineSourceMapJson = urldecode($inlineSourceMapJson);
+            $inlineSourceMapJson = json_decode($inlineSourceMapJson, true, 512, JSON_UNESCAPED_SLASHES);
+
+            $relativeFilenames = [];
+            foreach ($inlineSourceMapJson['sources'] as $filename) {
+                $relativeFilenames[] = str_replace(sprintf('%s/', BP), '', $filename);
+            }
+            $inlineSourceMapJson['sources'] = $relativeFilenames;
+            $inlineSourceMapJson = json_encode($inlineSourceMapJson, JSON_UNESCAPED_SLASHES);
+
+            $css = preg_replace($regex, sprintf('%s%s%s', $regexBegin, $inlineSourceMapJson, $regexEnd), $css);
+        }
+
+        return $css;
+    }
 }
diff --git a/lib/internal/Magento/Framework/Css/Test/Unit/PreProcessor/Adapter/Less/_file/test-developer.css b/lib/internal/Magento/Framework/Css/Test/Unit/PreProcessor/Adapter/Less/_file/test-developer.css
new file mode 100644
index 00000000000..41ebde91304
--- /dev/null
+++ b/lib/internal/Magento/Framework/Css/Test/Unit/PreProcessor/Adapter/Less/_file/test-developer.css
@@ -0,0 +1,20 @@
+/**
+ * Copyright © Magento, Inc. All rights reserved.
+ * See COPYING.txt for license details.
+ */
+body {
+   background: #333333;
+   color: #454545;
+}
+a {
+   color: #ff9900;
+}
+h1,
+h2,
+h3,
+h4,
+h5,
+h6 {
+   color: #333333;
+}
+/*#sourceMappingURL=data:application/json,{"version":3,"sources":["lib/internal/Magento/Framework/Css/Test/Unit/PreProcessor/Adapter/Less/_file/test.less"],"names":[],"mappings":";;;;AASA;EACE,mBAAA;EACA,cAAA;;AAEF;EACE,cAAA;;AAEF;AAAI;AAAI;AAAI;AAAI;AAAI;EAClB,cAAA"}*/
diff --git a/lib/internal/Magento/Framework/Css/Test/Unit/PreProcessor/Adapter/Less/_file/test-production.css b/lib/internal/Magento/Framework/Css/Test/Unit/PreProcessor/Adapter/Less/_file/test-production.css
new file mode 100644
index 00000000000..f8236f0d974
--- /dev/null
+++ b/lib/internal/Magento/Framework/Css/Test/Unit/PreProcessor/Adapter/Less/_file/test-production.css
@@ -0,0 +1,15 @@
+body {
+   background: #333333;
+   color: #454545
+}
+a {
+   color: #ff9900
+}
+h1,
+h2,
+h3,
+h4,
+h5,
+h6 {
+   color: #333333
+}
diff --git a/lib/internal/Magento/Framework/Css/Test/Unit/PreProcessor/Adapter/Less/_file/test.css b/lib/internal/Magento/Framework/Css/Test/Unit/PreProcessor/Adapter/Less/_file/test.css
deleted file mode 100644
index d6eaa03c103..00000000000
--- a/lib/internal/Magento/Framework/Css/Test/Unit/PreProcessor/Adapter/Less/_file/test.css
+++ /dev/null
@@ -1,19 +0,0 @@
-/**
- * Copyright © Magento, Inc. All rights reserved.
- * See COPYING.txt for license details.
- */
-body {
-   background: #333333;
-   color: #454545;
-}
-a {
-   color: #ff9900;
-}
-h1,
-h2,
-h3,
-h4,
-h5,
-h6 {
-   color: #333333;
-}
```


Can we try this out in this PR @ioweb-gr?

**Comment by ioweb-gr** [comment]
Thank you I'll check it in the upcoming days and update the PR :) 

I was out of office for some days

**Comment by engcom-November** [comment]
Till the tests are fixed, for the time being moving this to **Changes Requested**.

**Comment by ioweb-gr** [comment]
Hi @hostep I've applied the two patches you provided. 

Thanks for providing the diffs so that I can apply them directly. 

@engcom-November can you follow up on this?

**Comment by hostep** [comment]
Okay nice, the unit tests work perfect even on another machine then my own, very good!

However, I didn't check the unit test itself for coding standards checks, so those still fail.
Here's my suggestion to fix those:

```diff
diff --git a/lib/internal/Magento/Framework/Css/Test/Unit/PreProcessor/Adapter/Less/ProcessorTest.php b/lib/internal/Magento/Framework/Css/Test/Unit/PreProcessor/Adapter/Less/ProcessorTest.php
index 26ffa78abdd..0afa14ea86a 100644
--- a/lib/internal/Magento/Framework/Css/Test/Unit/PreProcessor/Adapter/Less/ProcessorTest.php
+++ b/lib/internal/Magento/Framework/Css/Test/Unit/PreProcessor/Adapter/Less/ProcessorTest.php
@@ -19,15 +19,15 @@ use Psr\Log\LoggerInterface;
 
 class ProcessorTest extends TestCase
 {
-    const TEST_CONTENT = 'test-content';
+    private const TEST_CONTENT = 'test-content';
 
-    const ASSET_PATH = 'test-path';
+    private const ASSET_PATH = 'test-path';
 
-    const TMP_PATH_LESS = '_file/test.less';
-    const TMP_PATH_CSS_PRODUCTION = '_file/test-production.css';
-    const TMP_PATH_CSS_DEVELOPER = '_file/test-developer.css';
+    private const TMP_PATH_LESS = '_file/test.less';
+    private const TMP_PATH_CSS_PRODUCTION = '_file/test-production.css';
+    private const TMP_PATH_CSS_DEVELOPER = '_file/test-developer.css';
 
-    const ERROR_MESSAGE = 'Test exception';
+    private const ERROR_MESSAGE = 'Test exception';
 
     /**
      * @var Processor
@@ -179,8 +179,16 @@ class ProcessorTest extends TestCase
 
         $clearSymbol = ["\n", "\r", "\t", ' '];
         self::assertEquals(
-            trim(str_replace($clearSymbol, '', file_get_contents(__DIR__ . '/' . self::TMP_PATH_CSS_PRODUCTION))),
-            trim(str_replace($clearSymbol, '', $this->processor->processContent($assetMock)))
+            trim(str_replace(
+                $clearSymbol,
+                '',
+                file_get_contents(__DIR__ . '/' . self::TMP_PATH_CSS_PRODUCTION)
+            )),
+            trim(str_replace(
+                $clearSymbol,
+                '',
+                $this->processor->processContent($assetMock)
+            ))
         );
     }
 
@@ -214,8 +222,16 @@ class ProcessorTest extends TestCase
 
         $clearSymbol = ["\n", "\r", "\t", ' '];
         self::assertEquals(
-            trim(str_replace($clearSymbol, '', file_get_contents(__DIR__ . '/' . self::TMP_PATH_CSS_DEVELOPER))),
-            trim(str_replace($clearSymbol, '', $this->normalizeInlineSourceMap($this->processor->processContent($assetMock))))
+            trim(str_replace(
+                $clearSymbol,
+                '',
+                file_get_contents(__DIR__ . '/' . self::TMP_PATH_CSS_DEVELOPER)
+            )),
+            trim(str_replace(
+                $clearSymbol,
+                '',
+                $this->normalizeInlineSourceMap($this->processor->processContent($assetMock))
+            ))
         );
     }
 
```

**Comment by ioweb-gr** [comment]
@hostep I applied your latest patch :) Let's see how it goes now

**Comment by hostep** [comment]
@magento run all tests

**Review by hostep — APPROVED** [review]

**Comment by hostep** [comment]
Looks good, failing functional tests don't seem related to the changes from this PR.

**Comment by engcom-November** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-November** [comment]
The repeating failure in Functional Tests B2B is flaky and known issue.

**Functional Tests B2B:**
**Run 1:**
image

**Run 2:**
image

**Known issue:**
[ACQE-5677](https://jira.corp.adobe.com/browse/ACQE-5677) - StorefrontQuoteCanBeRenamedUntilLockedTest

Hence moving this to **Merge in progress**.

**Comment by engcom-Dash** [comment]
We have seen static failures(related to copyright tag) in mainline PR after merging this PR into that. Hence for further analysis; for now moving this PR to Extended testing.

**Comment by engcom-Dash** [comment]
Hello @ioweb-gr,

Thanks for the contributions!

It seems that we don't have permission to commit fixes to the repository. Could you please address the static failures listed below in your PR? We are trying to merge this PR into the mainline PR but noticed the following failures. Please take the necessary action so we can proceed further.

image



**To fix these errors, could you please replace the following copyright tag:**
```
 /**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
```
With this one:
```
/**
 * Copyright 2015 Adobe
 * All Rights Reserved.
 */ 
```

Thanks!

**Comment by engcom-Dash** [comment]
@magento run Static Tests

**Comment by ioweb-gr** [comment]
How about now? :)

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
> How about now? :)

Thanks @ioweb-gr. Changes look good. Let's wait for the build result.

**Comment by engcom-Dash** [comment]
@magento run Unit Tests

**Comment by engcom-Dash** [comment]
Got a green build so moving it to merge in progress.
image

**Comment by hostep** [comment]
This changes from this PR got merged in `2.4-develop` branch today via https://github.com/magento/magento2/commit/651928c52166941ca64bfaec0bcaaf58ba8ab814 together with a bunch of other stuff, but this PR isn't marked as merged. @engcom-Dash can you investigate how that happened?

**Comment by engcom-Dash** [comment]
> The changes from this PR got merged in `2.4-develop` branch today via [651928c](https://github.com/magento/magento2/commit/651928c52166941ca64bfaec0bcaaf58ba8ab814) together with a bunch of other stuff, but this PR isn't marked as merged. @engcom-Dash can you investigate how that happened?

Hello @hostep, Thank you for pointing that out. It looks like the changes from this PR were merged into the 2.4-develop branch today via [651928c](https://github.com/magento/magento2/commit/651928c52166941ca64bfaec0bcaaf58ba8ab814), but we missed one of the merge commits into our mainline PR, which is why it's not showing as merged.

We will make sure to add the missing commit https://github.com/magento/magento2/pull/38977/commits/7fc0a30d8661bd869f46cd6dd19e78f31986813a in our next mainline PR. Apologies for the oversight, and thank you for your understanding.

**Pull request merged**
