### PR TITLE
Backport footer responsive

### PR DESCRIPTION
**Pull request by chirag-wagento**
### Original Pull Request 
 https://github.com/magento/magento2/pull/15353
Solved footer issue for mobile view

### Description
Solved footer issue for mobile view

### Fixed Issues (if relevant)

1. magento/magento2#15118: Responsive Design, Footers do not snap to bottom of screen on mobile devices
2. ...

### Manual testing scenarios

1. Check footer in mobile

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by chirag-wagento** [comment]
@VladimirZaets Could you please check what cause failed travis?

Thanks,

**Comment by VladimirZaets** [comment]
Hi @chirag-wagento. This PR looks the same as the PR [15890](https://github.com/magento/magento2/pull/15890). I closed this one and will process  [15890](https://github.com/magento/magento2/pull/15890)

**Comment by chirag-wagento** [comment]
@VladimirZaets Can you please check both  PR are  different you can see ticket title.

**Comment by VladimirZaets** [comment]
@chirag-wagento As I see the changes comparing with [15890](https://github.com/magento/magento2/pull/15890) are only in one file (app/design/frontend/Magento/luma/Magento_Theme/web/css/source/_module.less). Please commit this changes to PR [15890](https://github.com/magento/magento2/pull/15890) or apply the fix to wishlist (app/code/Magento/Wishlist/CustomerData/Wishlist.php) from PR [15890](https://github.com/magento/magento2/pull/15890) to this.

**Comment by chirag-wagento** [comment]
@VladimirZaets  There are both  different issue ticket so i was do work with different branch you can check issue ticket.

You can see below URL both tickets issue is different.
https://github.com/magento/magento2/issues/15118  
OR 
https://github.com/magento/magento2/issues/13636

**Comment by VladimirZaets** [comment]
The changes of code in this two 2 PRs different only in one file. I understand this PRs fixed two different issue. Please, merge they're to one PR and add the description of all issues fixed in the PR. 
We will add additional rewards (for all issues that will be fixed) when PR will be merged.

**Comment by orlangur** [comment]
Commit history is incorrect. Please check it prior to PR creation.

**Pull request closed without merging**
