### PR TITLE
Optimize QuoteIdToMaskedQuoteId model

### PR DESCRIPTION
**Pull request by ihor-sviziev**
Port https://github.com/magento/magento2/pull/33324 to 2.3.7

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>
2. 

### Release Notes

Improve performance by using direct SQL queries

### Categories

Performance, Shopping Cart

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE

**Review by andrewbess — DISMISSED** [review]

**Comment by m2-github-services** [comment]
@andrewbess thank you for the review! We have changed pull request base branch in order to provide ability to merge current pull request and schedule quality patch delivery job.

**Review by sidolov — APPROVED** [review]

**Comment by m2-github-services** [comment]
@sidolov thank you for the review! We have changed pull request base branch in order to provide ability to merge current pull request and schedule quality patch delivery job.

**Comment by m2-github-services** [comment]
@ihor-sviziev quality patch delivery job is successfully scheduled! Link to the quality patch tool pull request will be provided as soon as it's created

**Comment by m2-github-services** [comment]
Pull request with quality patch was successfully created, available by the link: magento/quality-patches#55

**Pull request merged**
