### PR TITLE
Update laminas-crypt to PHP8 compatible version

### PR DESCRIPTION
**Pull request by hws47a**
### Description (*)

Update laminas-crypt to ^3.4.0 for PHP8 compatibility

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32162

### Related pull requests
https://github.com/magento/partners-magento2ee/pull/499

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hws47a** [comment]
@magento run all tests

**Comment by hws47a** [comment]
@magento run all tests

**Comment by hws47a** [comment]
@magento run Static Tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Could you fix failing static tests?

**Comment by hws47a** [comment]
Hi @ihor-sviziev,

They are failing in B2B and EE. And they are fixed in the related PR (see description)

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Static Tests

**Comment by ihor-sviziev** [comment]
@sidolov @sivaschenko could you help to link the related PR correctly, it's not getting detected now

**Comment by sivaschenko** [comment]
@ihor-sviziev thanks, updated. @hws47a the format of related PR link should be precise as it is parsed from the description for the tests: https://devdocs.magento.com/contributor-guide/pull-request-tests.html#related-pull-requests

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by hws47a** [comment]
@magento run Functional Tests EE

**Review by ihor-sviziev — APPROVED** [review]

**Comment by hws47a** [comment]
@ihor-sviziev @sivaschenko all fixed now

**Pull request merged**
