### PR TITLE
issue/34180 - Order status set to blank if no status passed in order comment REST API

### LINKED ISSUE #34180: RestAPI add order comment without providing status sets status to NULL, preventing from showing in order grid
### Preconditions (*)

1. Magento 2.3.x, 2.4.x
2. Existing order to add comments to

### Steps to reproduce (*)

1. Using the orders/{id}/comments endpoint, POST a new comment, but exclude "status" field (as is not required)
2. Check the order in the sales_order, sales_order_grid database tables
3. Check the order in the admin > Sales > order grid and Front-end -Customer login > My Orders page

### Expected result (*)

1. Order should maintain existing status
2. Order should appear in adminhtml order grid and Front-end - My Orders page

### Actual result (*)

1. Order gets status set to NULL
2. Order no longer appears in adminhtml order grid
3. Order no longer appears in front-end - My Orders page
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by yogesh-valiya**
### Description (*)

Set current order status to the order history object if it don't have any order status.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#34180

### Manual testing scenarios (*)

1. Follow steps provided in the issue description - magento/magento2#34180
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by yogesh-valiya** [comment]
@magento run all tests

**Comment by yogesh-valiya** [comment]
@magento run Static Tests

**Comment by yogesh-valiya** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Test B2B, Static Tests

**Comment by yogesh-valiya** [comment]
@magento run Static Tests Functional Tests B2B

**Comment by yogesh-valiya** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Test B2B, Static Tests

**Comment by yogesh-valiya** [comment]
@magento run Functional Tests B2B

**Comment by yogesh-valiya** [comment]
@magento run Static Tests

**Comment by yogesh-valiya** [comment]
@magento run Static Tests, Functional Tests B2B, Functional Tests EE Functional Tests CE

**Comment by yogesh-valiya** [comment]
@magento run Static Tests, Functional Tests B2B, Functional Tests EE Functional Tests CE

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Seems that automated tests are failing due to PR changes. Need to take care of the failed tests.

**Comment by glo05363** [comment]
@yogesh-valiya thanks for working on the issue, This is already been taken care of in internal [JIRA](https://jira.corp.magento.com/browse/AC-1342). Once PR is merged, we will update the same.

**Comment by engcom-Bravo** [comment]
Hi @yogesh-valiya,


As I can see this issue got fixed in the scope of the internal Jira ticket AC-1342 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-1342&type=commits

Based on the Jira ticket, the target version is 2.4.7-beta1.

Thanks

**Pull request closed without merging**
