### PR TITLE
Modal content in admin area is under the close button

### PR DESCRIPTION
**Pull request by vasilii-b**
### Description (*)

Fix issue with "Modal content in admin area is under the close button"

### Fixed Issues (if relevant)

1. magento/magento2#19733

### Manual testing scenarios (*)
Provided in #19733 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by nuzil** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @nuzil. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @nuzil, here is your [new Magento instance](https://pr-19734.instances.magento-community.engineering).
Admin access: [https://pr-19734.instances.magento-community.engineering/admin](https://pr-19734.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by nuzil** [comment]
screen shot 2018-12-12 at 20 55 16

Currently looks correct

**Review by nuzil — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-3681](https://jira.corp.magento.com/browse/ENGCOM-3681) has been created to process this Pull Request

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3681](https://jira.corp.magento.com/browse/ENGCOM-3681) has been created to process this Pull Request

**Comment by VladimirZaets** [comment]
Hi @vasilii-b. Thanks for the collaboration. This issue is already fixed on the current 2.3-develop branch and will be available on the next 2.3.1 release.

**Pull request closed without merging**
