### PR TITLE
Issue 36196: Customer attribute and customer address attribute alway …

### LINKED ISSUE #36196: Customer attribute and customer address attribute alway require when select 'Use Default' in config
### Preconditions and environment

- Magento version 2.4-develop

### Steps to reproduce

1. Go Admin - Stores - Configuration - Customers - Customer Configuration
2. Untick 'Use system value' and set value Required for Show Date of Birth, Show Tax/VAT Number, Show Gender, Show Telephone, Show Company, Show Fax
3. Save config
4. Reindex and flush cache
5. Go edit 1 customer, the fields above are all required 
6. Go Admin - Stores - Configuration - Customers - Customer Configuration
7. Tick 'Use system value' for Show Date of Birth, Show Tax/VAT Number, Show Gender, Show Telephone, Show Company, Show Fax
8. Save config
9. Reindex and clear cache
10. Go edit 1 customer, the fields above are still required

### Expected result

Field  Date of Birth, Tax/VAT Number, Gender, Telephone, Company, Fax must display required based on default configuration value

### Actual result

Field  Date of Birth, Tax/VAT Number, Gender, Telephone, Company, Fax still required

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rogerdz**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#36196

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Review by bgorski — APPROVED** [review]
While in some cases I would say that it's better to add a default value instead of removing `canRestore`, in this case there's core logic that would get broken if the default value was "No", which is a string that evaluates to `1` or `true` when cast to integer and boolean respectively. Not to mention any 3rd party logic that could break because of that. So removal of `canRestore` is definitely a safer and better option. 
Approved. Thank you for the contribution!

**Comment by bgorski** [comment]
To whom it may concern - this PR introduced no data or logic changes to out-of-the-box magento installation (it only affects admins' ability to go back to the initial config - a possibility that in this case never worked anyway) and therefore is not a cause of any test failures. Because of that, failures of integration and functional tests can be disregarded.

**Comment by bgorski** [comment]
@magento run Integration Tests, Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by bgorski** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by bgorski** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

**Review by engcom-Lima — CHANGES_REQUESTED** [review]
Hi @rogerdz ,

Thanks for your contribution and collaboration.

During testing it has been observed that "Use default value" check box is missing from the configuration.
**`Admin - Stores - Configuration - Customers - Customer Configuration`>>`Name and Address Options`** Kindly provide more information whether in this PR check box will get removed?and If not kindly fix it.

**Screenshot for your reference:**
**Before PR changes:**
image

**After PR changes:**
image

Also, several builds also getting failed even after running mutilple times those are below:

1.  Functional Tests CE
2.  Functional Tests EE
3.  Functional Tests B2B

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
> Hi @rogerdz ,
> 
> Thanks for your contribution and collaboration.
> 
> During testing it has been observed that "Use default value" check box is missing from the configuration. **`Admin - Stores - Configuration - Customers - Customer Configuration`>>`Name and Address Options`** Kindly provide more information whether in this PR check box will get removed?and If not kindly fix it.
> 
> **Screenshot for your reference:** **Before PR changes:** image
> 
> **After PR changes:** image
> 
> Also, several builds also getting failed even after running mutilple times those are below:
> 
>     1. Functional Tests CE
> 
>     2. Functional Tests EE
> 
>     3. Functional Tests B2B

- Yes, my PR removed "Use default value" check box some field in Admin - Stores - Configuration - Customers - Customer Configuration>>Name and Address Options.
- Cause by when tick 'Use system value'  for Show Date of Birth, Show Tax/VAT Number, Show Gender, Show Telephone, Show Company, Show Fax fields and press save, the logic that handles it runs to function afterDelete() in \Magento\Customer\Model\Config\Backend\Show\Customer
AT5B8FW
You can see it alway save is_required and is_visible is required . I also can't get the default value for config here, so removal of canRestore is a safer and better option :)
- Also I fixed Functional Tests, please review again @engcom-Lima

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Review by bgorski — CHANGES_REQUESTED** [review]
@rogerdz please don't comment-out steps in MFTF tests. If they're not necessary anymore then please remove them entirely.

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
> @rogerdz please don't comment-out steps in MFTF tests. If they're not necessary anymore then please remove them entirely.

thanks for your advice ^^

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
Hi @rogerdz ,

Thanks for your contribution and collaboration.

As you explained in last [comment PR](https://github.com/magento/magento2/pull/36197#issuecomment-1263795067) is removing the **`Use System Value`** checkbox.
For this we have discussed internally & came to conclusion that It should not be removed as explained below :
1. **`Use System Value`** checkbox is in every configuration page of Magento. So, It will break the consistency.
2. In users perspective this will led to confusion. For example-> If any user changes the configuration frequently then,he/she may want to set the configuration to default. Then it is not possible if we remove the checkbox as this checkbox sets the data to Magento default configuration. 
3. If only two points in the dropdown is there then, it is fine but here more number of options are there in dropdown. For ex- optional/no/required.
4. On a fresh instance of Magento, when the admin user visits customer creation page for 1st time, all these options like Field - Date of Birth, Tax/VAT Number, Gender, Telephone, Company, Fax fields by default are not mandatory. If user is changing this configuration and restoring back again to default, our expectation is that customer creation page / edit page should be as it was been initially (Customer creation is allowed without these fields. All the default values which were not mandatory initially should be restored back as is)

Also actual issue was reported was that -> After changing the configuration to 'required' for all those options and save it .All mentioned field become mandatory and then, if reporter want to change to system default then, it is not happening by clicking on **`Use System Value`**

Please provide your input how to fix it by not removing checkbox.

Thanks

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
Hi @engcom-Lima,  thank you for your response.
I found the way to resolve issue without remove 'Use System Value' 
Can you check it ?

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B , Functional Tests CE, Functional Tests EE, Integration Tests

**Comment by engcom-Lima** [comment]
Hi @bgorski ,

As discussed with @rogerdz all necessary changes had been completed. Now, I am moving this PR to Pending Review status. Kindly review it.

Thanks

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by mahesh-singh-rajawat** [comment]
@rogerdz Thank you fixing this issue.

It will be taken care into one of the Internal [JIRA ticket](https://jira.corp.adobe.com/browse/AC-6748). Once Internal PR will get merged, we will notify.

Thank you!

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-6748 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-6748&type=commits

Based on the Jira ticket, the target version is 2.4.7-beta1.

Thanks

**Pull request closed without merging**
