### PR TITLE
Add to cart ajax not working on Simple product page with custom option type - date

### PR DESCRIPTION
**Pull request by ghost**
Solution for Add to cart ajax not working on Simple product page with custom option type - date

### Description

This solution is for add to cart ajax while product has custom options.
### Fixed Issues (if relevant)

1. magento/magento2#17460: Add to cart ajax not working on Simple product page with custom option type - date #17460

### Manual testing scenarios

1. Create simple product.
2. Add custom option with option type Date > Date
3. Add price (Price Type Fixed) and option sku.
4. Go to product page and  add to cart.
5. Product will added without page reload.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @emiprotech. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-2742](https://jira.corp.magento.com/browse/ENGCOM-2742) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@emiprotech thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by sivaschenko** [comment]
Hi @emiprotech , thanks for your contribution! Sorry for slow response, we suggest to adjust the fix:

Remove the added block and anothe last 7 lines from the end of `app/code/Magento/Catalog/view/frontend/templates/product/view/addtocart.phtml`

    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
    </script>

Update the script tag at the end of `app/code/Magento/Catalog/view/frontend/templates/product/view/options/type/date.phtml`

             <script type="text/x-magento-init">
             {
                "#product_addtocart_form": {
                    "validation": {
                        "ignore": ":hidden:not(input[name^='validate_datetime_'])"
                    },
                    "catalogAddToCart": {
                        "bindSubmit": true
                    }
                }
            }
         </script>

Please let me know what you think!

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=17518) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=17518) before we can accept your contribution.<br/>**5** out of **11** committers have signed the CLA.<br/><br/>:white_check_mark: sidolov<br/>:white_check_mark: magento-engcom-team<br/>:white_check_mark: arhiopterecs<br/>:white_check_mark: vpodorozh<br/>:white_check_mark: iancassidyweb<br/>:x: slopukhov<br/>:x: mastiuhin-olexandr<br/>:x: KevinBKozan<br/>:x: svitja<br/>:x: nikita-shcherbatykh<br/>:x: serhii-balko

**Comment by sivaschenko** [comment]
Hi @emiprotech we found an issue while testing the PR: if validation fails, the page is reloaded.
Is there a way to avoid page reload in case of failed validation?

**Comment by ghost** [comment]
Hi @sivaschenko
let me check issue and give you update for that.

**Comment by ghost** [comment]
Hi @sivaschenko,
We are not reproduce your issue in our updated Magento.
Can you give me steps to reproduce same issue which you have face?

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [new Magento instance](https://pr-17518.instances.magento-community.engineering).
Admin access: [https://pr-17518.instances.magento-community.engineering/admin](https://pr-17518.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sivaschenko** [comment]
Hi @emiprotech , I launched a test instance: Please open https://pr-17518.instances.magento-community.engineering/simple.html and try to add a product to cart without specifying the date: the page will be reloaded

**Comment by sivaschenko** [comment]
@emiprotech would you like to continue work on this pull request?

**Comment by VladimirZaets** [comment]
@emiprotech , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Comment by ghost** [comment]
Hi @emiprotech, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+magento2+17518), it will take less than a minute. </br>Your feedback will help us to improve contribution process.

**Pull request closed without merging**
