### PR TITLE
Move Source filter to MediaGalleryUi module

### LINKED ISSUE #1731: Move Source filter to the MediaGalleryUi module
### Preconditions (*)
Source filter in MediaGallery Should be moved to the MediaGalleryUi module

### Steps to reproduce (*)
1. `Magento\AdobeStockImageAdminUi\Ui\Component\Listing\Columns\Source\Options` should be moved to the MediaGalleryUi module with only Local option
2. Source filter from UI component should be removed from AdobStockIMageAdminUi module and declarated in MediaGalleryUi module
3. Plugin should be added in AdobStockImageAdminUi module to add AdobeStock Source option to the Source filter

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1 . Fixes https://github.com/magento/adobe-stock-integration/issues/1731

### Manual testing scenarios (*)
1. Open  new enhanced media gallery
2. Expand Filters  tab
3. Apply Source filter

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by sivaschenko** [comment]
Please test together with https://github.com/magento/adobe-stock-integration/pull/1734

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-7957](https://jira.corp.magento.com/browse/ENGCOM-7957) has been created to process this Pull Request

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

**Without** Adobe Stock Modules the **Source** filter exist with one - _Uploade Locally_ option
source

**With** Adobe Stock modules and PR - https://github.com/magento/adobe-stock-integration/pull/1734, an _Adobe Stock_ option appeared
sourceasi

The Filter works correctly

Test on Cucumber Studio - https://studio.cucumber.io/projects/131313/test-plan/folders/1337102/scenarios/4760144

**Pull request merged**
