### PR TITLE
[Changed password placeholder text in checkout page]

### PR DESCRIPTION
**Pull request by hitesh-wagento**
### Description
Summary of the issue: Wrong placeholder for password field in the checkout page

### Fixed Issues (if relevant)

1. magento/magento2https://github.com/magento/magento2/issues/16378: Wrong placeholder for password field in the checkout page

### Steps to reproduce
1. Add a product to cart and go to checkout page.
2. Enter any registered email so that the password field appears. 
3. The password field shows the placeholder **Optional**, but when we click on Login button without filling password, it shows the validation error.

### Actual result
1. The password field in the checkout page is currently seeming conflicting in nature. It is showing Optional in a placeholder, but after validation, it is showing validation error **This is a required field.**

validation-password

### Expected result
1. Since the password is a required field, the placeholder for the password field should not be **Optional**.
screenshot-127 0 0 1-2018-06-25-17-44-21

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @hitesh-wagento. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by ishakhsuvarov** [comment]
@hitesh-wagento This field is only required when the user decides to login. In the other scenario, where user decides to continue as a guest this field is optional.
Solution may be adjusted to support this case.

**Comment by Jeroenll** [comment]
Can you also update the `.csv` file so it can be correctly translated in other languages?

**Comment by hitesh-wagento** [comment]
Hi @JeroenVanLeusden 

I have added **Password** text in `.csv` file

**Comment by magento-engcom-team** [comment]
Hi @hitesh-wagento. Thank you for your contribution. 
The changes from your Pull Request should be available with the upcoming 2.2.6 release. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Comment by hitesh-wagento** [comment]
@VladimirZaets Do we need to create backport and forwardport ?

**Pull request merged**
