### PR TITLE
update jquery validate method  and removal of jquery migrate

### LINKED ISSUE #21406: remove jQuery Migrate
### Preconditions (*)
jQuery Migrate should never be used in production as this is just meant to migrate from an older version to the used one (for which the Migrate version is).

https://github.com/magento/magento2/blob/2.3-develop/lib/web/jquery/jquery-migrate.js

See https://github.com/jquery/jquery-migrate/tree/1.x-stable#readme

The same applies to underscore, moment.js and other unnecessary libraries and scripts.

This is a big file and just for debugging purposes.

### Expected result (*)

1. jQuery Migrate should not be loaded
2.

### Actual result (*)

1. jQuery Migrate is loaded
2.

### PR DESCRIPTION
**Pull request by jordanvector**
### Description (*)

Removes jQuery Migrate,
Updates Jquery validate method from event.handle to event.dispatch

Builds upon https://github.com/magento/magento2/pull/25847

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/587

### Fixed Issues (if relevant)
Fixes #21406 : remove jQuery Migrate

### Manual testing scenarios (*)
None

### Contribution checklist (*)
 Pull request has a meaningful description of its purpose
 All commits are accompanied by meaningful commit messages
 All new or changed code is covered with unit/integration tests (if applicable)
 All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by jordanvector** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Let's wait for test results

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
It feels like this is not a full solution, as we still getting functional test failures. Could you check those test failures?
Also TBH I don't think it's a good solution to fix the validation library, maybe upgrading it will be much better. What do you think?

**Comment by jordanvector** [comment]
@ihor-sviziev fair enough, updating the validation library is probably better than updating the methods within.  I am gonna go take a look and see where jquery validation is these days and try to swap.

If it works I will update this PR..or make a new one

**Comment by ihor-sviziev** [comment]
@jordanvector I would recommend starting from checking test failures, that might be not in the validation library at all

**Comment by jordanvector** [comment]
@ihor-sviziev I did take a look at the test results and those look like maybe a network issue with the test rather than a code problem.  Can we rerun the failed to confirm?

**Comment by ihor-sviziev** [comment]
We had similar issue on the previous PR. Could you check that case manually on test instance?
@magento give me test instance

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by jordanvector** [comment]
updated the jquery validate library to its latest version.

@magento run all tests

**Comment by ihor-sviziev** [comment]
@jordanvector seems like updateing jquery validate broke much more tests. I believe we should rever your latest changes and work on fixing other issues, like failing tests on checking order totals

**Comment by mrtuvn** [comment]
While update jquery to 3.6.0 in local for side project i still have use jquery.migrate along with jquery for resolve issue "Uncaught TypeError: r.getClientRects is not a function". My workarounds only update jquery and add new version jquery mobile + remove patches jquery only

**Comment by ihor-sviziev** [comment]
@mrtuvn i believe that right now some of functionality sill using functions that is older than available in used in magento jquery version. It’s fine to use latest jquery migrate version with latest jquery version, but it doesn’t make any sense to use old jquery version with old jquery migrate version

**Comment by Den4ik** [comment]
> * delete jquery migrate
> * fix broken functionality due to used old functions
> * upgrade jquery to latest version + add latest jquery migrate version (in order to keep compatibility)

Totally agree. Some time ago @kirmorozov opened PR of upgrading JQuery, but unfortunately it was not finally finished and merged.
https://github.com/magento/magento2/pulls?q=is%3Apr+is%3Aclosed+%22Upgrading+JQuery%22+in%3Alabel

**Comment by jordanvector** [comment]
@ihor-sviziev yep no problem, working on this today.

**Comment by jordanvector** [comment]
@magento run all tests

**Comment by jordanvector** [comment]
@magento run static tests

**Comment by jordanvector** [comment]
@magento run WebAPI Tests

**Comment by jordanvector** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@jordanvector Could you merge mainline into your branch?

**Comment by jordanvector** [comment]
@Den4ik just merged from 2.4 develop.  Retesting now

**Comment by jordanvector** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
Hi @jordanvector Can you fix conflict file ?

**Comment by sivaschenko** [comment]
@fascinosum please pay attention to this PR

**Comment by sivaschenko** [comment]
Changed target branch to `platform-health`

**Comment by eduard13** [comment]
Hi @jordanvector, thank you for working on this. I've also done some investigation on this area (more related to jQuery.validate), and it doesn't seem that we can easily update it. The main reason, being jQuery.metadata which is still used by core code, and not supported by the latest jQuery.migrate version. As result, we'll have the frontend validation not working for form fields that are still using the `data-validate="{required:true}"` approach.

Is it required to update the `jQuery.validate` on `jQuery.migrate` removal?

Thank you.

**Comment by eduard13** [comment]
@magento run Static Tests, Unit Tests, Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by jordanvector** [comment]
> Hi @jordanvector, thank you for working on this. I've also done some investigation on this area (more related to jQuery.validate), and it doesn't seem that we can easily update it. The main reason, being jQuery.metadata which is still used by core code, and not supported by the latest jQuery.migrate version. As result, we'll have the frontend validation not working for form fields that are still using the `data-validate="{required:true}"` approach.
> 
> Is it required to update the `jQuery.validate` on `jQuery.migrate` removal?
> 
> Thank you.

@eduard13 that is exactly right and thank you for writing this up, the incompatibility specifically comes from the jquery validate function.  And to also answer your question no updating jquery validate is not required to remove jquery migrate however if we do not upgrade jquery validate, there are 2 functions in the current version of jquery validate that use old deprecated jquery methods that need updating.

Specifically here

https://github.com/magento/magento2/pull/32364/commits/8fa540d22130a8d762dfa8583cf82a5e2dccbcd4#diff-ba3cf3f1b621df49d92f6733738b560443aafaff3f0d13ddbf414838e0a5fc0c

Depending on time and effort of updating jquery validate to the latest version, maybe its worth reverting back to the old version and fixing the deprecated methods, then a new ticket to update the jquery validate package in the future?

**Comment by eduard13** [comment]
Hi @jordanvector thank you for your comment. Indeed, I've reverted the jQuery.validate, however we still have some incompatibility issues with `jQuery.multiselect` library, which is the reason of failing the functional tests Tax related, as it still using the deprecated `.attr('selected', flag)` approach.

Regarding fixing the deprecated methods, if they are inside of some libraries, we should try to update it instead of directly changing it.

Will keep you updated if anything.

**Comment by eduard13** [comment]
Hi @jordanvector, after investigating possible issues, looks like removing jQuery-migrate, at the moment will cause more problems with the existing libraries. Moreover, keeping it, will allow us easily update jQuery to the latest version which is planned for the near future.

Putting it on hold for now.

Thank you for understanding.

**Comment by eduard13** [comment]
Closing this PR for now, as it is planned to proceed updating the jQuery-migrate.
Thank you @jordanvector for your input here.

**Pull request closed without merging**
