### PR TITLE
[Backport] 20484 - Fix performance leak in salesrule collection

### PR DESCRIPTION
**Pull request by david-fuehr**
### Original Pull Request
https://github.com/magento/magento2/pull/20484

### Description
Refactored sql query that created a huge temporary table for each request, when a greater amount of salesrules and coupon codes exists in database. The sorting of this table took a lot of cpu time.
The statement now consists of two subselects that drill down the remaining lines as far as possible, so that the remaining temporary table is minimal and easily sorted.

### Fixed Issues
1. magento/magento2#19117: High Database Load for Sales Rule Validation

### Manual testing scenarios
1. Create an active salesrule with no coupon code (`A`)
1. Create an inactive salesrule with no coupon code (`B`)
1. Create an active salesrule with `coupon_type = 'autogenerated'` and generate 5000 codes (`C`)
1. Create an active salesrule with `coupon_type = 'specific'` (`D`)
1. Create an inactive salesrule with coupon code (`E`)
1. Add a product to the cart (qualified for all active salesrules)
1. Go to checkout/cart
    1. The subtotal for salesrules only lists label `A`
1. Add one of the coupon codes of `C` to the cart
    1. the coupon code can be applied
    1. The subtotal for salesrules lists label `A,C`
1. Remove the applied coupon code
    1. the coupon code can be removed
1. Add the coupon code `D` to the cart
    1. the coupon code can be applied
    1. The subtotal for salesrules lists label `A,D`
1. Add the coupon code `E` to the cart
    1. the coupon code can not be applied
1. Check out the order
    1. checkout succeeds
1. Configure rule `A` to `priority =  1`
1. Configure rule `D` to `priority =  2`
1. Add the product to a new quote 
    1. The subtotal for salesrules only lists label `A`
1. Apply Coupon for salesrule `D`
    1. The subtotal for salesrules lists label `A,D`
1. Configure rule `A` to `priority =  3`
1. Update cart items quantity
    1. The subtotal for salesrules lists label `D,A`

### Additional Information
We use this fix in a magento commerce environment

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Hi @david-fuehr,
I just added few fixes that were missing from original PR, now everything looks good. Let's wait for Travis results

**Comment by david-fuehr** [comment]
Hi @ihor-sviziev,

thanks for fixing. Those lines somehow got lost ...

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-4485](https://jira.corp.magento.com/browse/ENGCOM-4485) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
