### PR TITLE
Checkout agreements - not only first input required and multiple payment validation fix

### LINKED ISSUE #5632: checkout_agreement Magento 2.1 only first entry is required
I have made 3 Entries under store->"Terms and Conditions"
after upgrade from magento 2.0.6 to 2.1 there is only the first one an required checkbox.
On Magento 2.0.6 every Enty were required checkboxes. 
I think this must be a bug on Magento 2.1

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
It fixes #5632 and #6224 issues.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=6390) <br/>All committers have signed the CLA.

**Comment by vrann** [comment]
@Bartlomiejsz please update your code with the latest develop branch

**Comment by okorshenko** [comment]
@Bartlomiejsz please update your code with the latest develop branch

**Comment by Bartlomiejsz** [comment]
@vrann @okorshenko I will do it today evening.

**Comment by Bartlomiejsz** [comment]
@vrann, @okorshenko, since this PR makes no sense according to https://github.com/magento/magento2/commit/4d89955ed19884df308fbecedb612b782bf0a88d I'm closing it

**Pull request closed without merging**
