### PR TITLE
Fix for Magnifier in inside mode

### PR DESCRIPTION
**Pull request by kacperchara**
### Fixed Issues
1. magento/magento2/issues/4977: Magnifier doesn't work with mode set to inner

### Manual testing scenarios
You need to change the magnifier's configuration options in the file: app/design/frontend/Magento/luma/etc/view.xml

Set the following values ​​for these lines:
><var name=\"enabled\">true<\/var>
><var name=\"mode\">inside<\/var>

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15382) <br/>All committers have signed the CLA.

**Comment by kacperchara** [comment]
There is a problem with the license, although I signed it, it is still visible that the license has not been signed.

**Comment by dmanners** [comment]
Hi @kacperchara it seems you committed with one user (https://github.com/kcharadivante) but are logged in and so signed the cla with another user (https://github.com/kacperchara)

**Comment by magento-engcom-team** [comment]
Hi @kacperchara. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Comment by boostify-pro** [comment]
I am on 2.2.6 and still having this issue

**Pull request merged**
