### PR TITLE
2.1 develop

### PR DESCRIPTION
**Pull request by angelo983**
Inserts specified item into container at a specified position.

### Description
Wrong evaluating check of position param (Position at which item should be inserted.)
let hang Checkout Page

### Fixed Issues (if relevant)
lib/web/mage/utils/arrays.js
Line 105
from
            if (typeof position === 'undefined') {
to
            if (typeof position === 'undefined' || position == null) {

### Manual testing scenarios
May happens while buying simple products of configurable products

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=9966) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=9966) before we can accept your contribution.<br/>**0** out of **4** committers have signed the CLA.<br/><br/>:x: OlgaVasyltsun<br/>:x: lestare<br/>:x: RomaKis<br/>:x: zakdma<hr/>**lestare** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by ishakhsuvarov** [comment]
@angelo983 Looks like you have selected wrong branches by mistake (from `develop` into `2.1-develop`). Please update and reopen if you wish to continue.
Thanks!

**Comment by angelo983** [comment]
I found the bug in the 2.1-develop. Am I missing something I have to know about committing here instead of develop branch?

**Comment by ishakhsuvarov** [comment]
@angelo983 Maybe you have mixed up the repositories or branches for the Pull Request, as currently, this PR is set up to merge `2.1-develop` branch of `magento/magento2` repository to the `develop` branch of the same `magento/magento2` repository.

**Pull request closed without merging**
