### PR TITLE
Added translation fixes

### LINKED ISSUE #28311: [Issue] Added translation fixes
This issue is automatically created based on existing pull request: magento/magento2#26855: Added translation fixes

---------

### Description (*)
- Added translation for `<comment>` tag
- Fixed translation string issue inside `en_US.csv` file.

### Fixed Issues (if relevant)

1. N/A

### Manual testing scenarios (*)

1. N/A

### PR DESCRIPTION
**Pull request by yogeshsuhagiya**
### Description (*)
- Added translation for `<comment>` tag
- Fixed translation string issue inside `en_US.csv` file.

### Fixed Issues (if relevant)

1. N/A

### Manual testing scenarios (*)

1. N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28311: Added translation fixes

### CODE REVIEW

**Comment by yogeshsuhagiya** [comment]
@magento-engcom-team Hello guys, 
Is there any one who can review this PR? Already 5 days passed but still there is no reply on it.

**Comment by lenaorobei** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, here is your [Magento instance](https://i-26855-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26855-2-4-develop.instances.magento-community.engineering/admin_b566](https://i-26855-2-4-develop.instances.magento-community.engineering/admin_b566)
Login: `8c795645` Password: `d7eff7a9d776`
Instance will be terminated in up to 3 hours.

**Review by lenaorobei — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-7235](https://jira.corp.magento.com/browse/ENGCOM-7235) has been created to process this Pull Request

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @yogeshsuhagiya.
Could you add label `Enable Frontend Resize` and comment` Resize performed via javascript before file upload.` to the translation file?
Thanks!

**Comment by yogeshsuhagiya** [comment]
Hi @engcom-Alfa 
I've updated file as per your requirement, please take a look.

**Review by lenaorobei — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-7235](https://jira.corp.magento.com/browse/ENGCOM-7235) has been created to process this Pull Request

**Comment by lenaorobei** [comment]
@yogeshsuhagiya please address builds failure.

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-7235](https://jira.corp.magento.com/browse/ENGCOM-7235) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Comment by lenaorobei** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, here is your [Magento instance](https://i-26855-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26855-2-4-develop.instances.magento-community.engineering/admin_6c83](https://i-26855-2-4-develop.instances.magento-community.engineering/admin_6c83)
Login: `c66b40f2` Password: `bdea3931431e`
Instance will be terminated in up to 3 hours.

**Comment by slavvka** [comment]
@magento run all tests

**Comment by sdzhepa** [comment]
@magento create issue

**Comment by sdzhepa** [comment]
It seems functional tests fail are not related to changes in this PR

**Review by sdzhepa — APPROVED** [review]

**Comment by slavvka** [comment]
@yogeshsuhagiya please don't touch your PR when it is in delivery

**Pull request merged**
