### PR TITLE
32030 - Mark interfaces as api

### PR DESCRIPTION
**Pull request by AndreyChorniy**
### Description (*)

This PR created to adjust interfaces, mark them as api
### Fixed Issues (if relevant)

1. Fixes magento/magento2#32030

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by AndreyChorniy** [comment]
@magento run all tests

**Comment by BarnyShergold** [comment]
@magento run Database Compare Functional Tests EE

**Comment by BarnyShergold** [comment]
@magento run Database Compare,Functional Tests EE

**Review by BarnyShergold — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @BarnyShergold, thank you for the review.
[ENGCOM-8770](https://jira.corp.magento.com/browse/ENGCOM-8770) has been created to process this Pull Request
:eight_spoked_asterisk: @BarnyShergold, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by BarnyShergold** [comment]
@AndreyChorniy The Database Compare & one Functional Test keep failing but I can't see why what you've added would cause these issues - this maybe a false positive. Can you check?

**Comment by AndreyChorniy** [comment]
@BarnyShergold Sure, I will check this

**Comment by AndreyChorniy** [comment]
@magento run Database Compare,Functional Tests EE

**Comment by AndreyChorniy** [comment]
@magento run Functional Tests EE

**Comment by gabrieldagama** [comment]
Hi @AndreyChorniy, can you recreate this PR to the `api-changes-develop` branch instead? Just make sure to create a new branch from this one and cherry-pick your commit.

Thanks!

**Comment by gabrieldagama** [comment]
Closed in favour of https://github.com/magento/magento2/pull/33177

**Pull request closed without merging**
