### PR TITLE
Fixed special characters issue on product name 

### LINKED ISSUE #38146: Special characters in configurable associate product name are  being Converted to HTML Entities.
### Preconditions (*)
I have tested it only below mentioned magento versions,and issue is reproducible.
1. Magento – 2.4.6-p1
2. Magento – 2.4.6-p2

### Description (*)
 When we are using special character " " in configurable product name (screenshot-1) and create configuriotion and save the product then associated varient name is showing perfectly  but second time when we edit that associate product then special character is being change into '&quot'; in associate Product name (screenshot-2).

**Screenshot-1**
image

**Screenshot-2**
image

image

### Steps to reproduce (*)
1. Create Configurable Product.
2. Add product name Like Test "config"
3. Create Configuration and Add attribute (color/size) Attributue then select any attribute (color/size) and save the configurable product.
4. Edit the associte product and then observe.

### Expected result (*)
 Special character in Product Name should be not change to html entities when we edit the associate product.

### Actual result (*)
 Special characters in configurable associate product names are  being Converted to html entities.

### Additional Information (*)
As I have checked When Saving a Configurable Product for the First Time then this file is being called Magento\ConfigurableProduct\Block\Adminhtml\Product\Edit\Tab\Variations\Config\Matrix.php as on line no 377 (Screenshot-3) where escapeHtml is not implemented for name and when second time while editing associated for the same configurable product then this file  Magento\ConfigurableProduct\Ui\DataProvider\Product\Form\Modifier\Data\AssociatedProducts.php (Screenshot-4) is being called where on line 308 the escapeHtml method is implemented for the product name.

**Screenshot-3**
image

**Screenshot-4**
image

### PR DESCRIPTION
**Pull request by Bansiravaliya7**
### Fixed Issues

1. Fixes: https://github.com/magento/magento2/issues/38146

### Manual testing scenarios (*)
1. ...
2. ...

### Additional Information
As I've checked, when saving a configurable product for the first time, the file responsible for saving product data is Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper.php (screenshot-1), where escapeHtml is not implemented for name and that's why it is not escape product name for the first time and Magento\ConfigurableProduct\view\adminhtml\web\js\variations\steps\summary.js (screenshot-2) is responsible for setting product variant names. It takes the base product name and appends the attribute.

After saving the product, it redirects to the edit page (screenshot-3). When we edit the configurable product variant, the file being called is Magento\ConfigurableProduct\Ui\DataProvider\Product\Form\Modifier\Data\AssociatedProducts.php, where escapeHtml is implemented for the name(screenshot-4). That is why when we edit the variant names, they are being converted to HTML entities.

I found the commit where escapeHtml is implemented: https://github.com/magento/magento2/commit/f15f42dd6727b44afbc25593e7c8d7030904cf50. escapeHtml is implemented for Cross-Site Scripting, and I noticed that it's not implemented on creating any type of product or creating configurable product variants, it is only implemented when configurable variantes are edited. 

For example, if you're creating a configurable product named 'Test "config"&lt;h1&gt;'and you associate it with the attribute 'red', the base product name 'Test "config"&lt;h1&gt;' will be used as part of the variant names. The 'red' attribute value will then be appended to this base name to create variant names such as 'Test "config"&lt;h1&gt;-red'. And it is saved in the database as 'Test "config"&lt;h1&gt;-red'(screenshot-5). When we edit the configurable variants and save, it will updates the name in the database with 'Test &quot;config&quot;&lt;h1&gt;-red'(screenshot-6) using escapeHtml, and without escapeHtml when we edit configurable variants and save, it will save as it is ('Test "config"&lt;h1&gt;-red'). Also, with or without escapeHtml in the frontend, it will show the name as 'Test "config"&lt;h1&gt;-red', so if we remove the escapeHtml, then also cross-site scripting issues will not occur. 

So if we remove that escapeHtml from Magento\ConfigurableProduct\Ui\DataProvider\Product\Form\Modifier\Data\AssociatedProducts.php file can solve the issue.

**Screenshot-1**
image

**Screenshot-2**
image

**Screenshot-3**
image

**Screenshot-4**
image

**Screenshot-5**
image

**Screenshot-6**
image

### Solution
To resolve this issue, we need to remove “escapeHtml” from Magento\ConfigurableProduct\Ui\DataProvider\Product\Form\Modifier\Data\AssociatedProducts.php (Screenshot-7).

**Screenshot-7**
image

### Contribution checklist (*)

- [ ] Pull request has a meaningful description of its purpose
- [ ]  All commits are accompanied by meaningful commit messages
- [ ]  All new or changed code is covered with unit/integration tests (if applicable)
- [ ]  README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
- [ ]  All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Bansiravaliya7** [comment]
@magento run all tests

**Comment by Bansiravaliya7** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @Bansiravaliya7,

Thanks for the contribution!

Code changes seem good to me but add some automated tests in accordance to [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1).

Thanks

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Automated test coverage has been added.
Hence moving it to `merge in progress`

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Review by engcom-Hotel — APPROVED** [review]
Thanks @engcom-Echo for adding the automated test.

Failed tests seem flaky to me hence approving this PR.

**Comment by engcom-Delta** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

1. Login to magento admin
2. Create Configurable Product
3. Add product name Like Test "product"
4. Create configuration and add attribute (color/size) attribute then select any attribute (color/size/brand) and 
5. Save the Configurable product
6. Click on Edit Configurations and save
7. Verify the Configuration name and product name


**Before:** :heavy_multiplication_x: 


Screenshot 2024-03-22 at 8 07 16 PM

Screenshot 2024-03-22 at 8 08 12 PM

Screenshot 2024-03-22 at 8 09 35 PM

Screenshot 2024-03-22 at 8 09 44 PM

Screenshot 2024-03-22 at 8 09 51 PM

Screenshot 2024-03-22 at 8 10 31 PM

Screenshot 2024-03-22 at 8 10 36 PM

Screenshot 2024-03-22 at 8 11 02 PM

Screenshot 2024-03-22 at 8 14 31 PM

Screenshot 2024-03-22 at 8 14 50 PM

Screenshot 2024-03-22 at 8 15 10 PM

Screenshot 2024-03-22 at 8 16 03 PM

Screenshot 2024-03-22 at 8 21 45 PM

Screenshot 2024-03-22 at 8 22 05 PM

Screenshot 2024-03-22 at 8 22 24 PM

Screenshot 2024-03-22 at 8 22 29 PM

Screenshot 2024-03-22 at 8 22 37 PM

Screenshot 2024-03-22 at 8 22 47 PM


**After:** :heavy_check_mark:  


Screenshot 2024-03-22 at 9 07 48 PM

Screenshot 2024-03-22 at 9 08 02 PM

Screenshot 2024-03-22 at 9 08 18 PM

Screenshot 2024-03-22 at 9 08 33 PM

Screenshot 2024-03-22 at 9 08 41 PM

Screenshot 2024-03-22 at 9 09 07 PM

Screenshot 2024-03-22 at 9 09 25 PM

Screenshot 2024-03-22 at 9 09 32 PM

Screenshot 2024-03-22 at 9 09 44 PM

Screenshot 2024-03-22 at 9 11 01 PM

Screenshot 2024-03-22 at 9 11 11 PM

Screenshot 2024-03-22 at 9 11 19 PM

Screenshot 2024-03-22 at 9 11 35 PM

Screenshot 2024-03-22 at 9 11 45 PM

Screenshot 2024-03-22 at 9 12 10 PM

Screenshot 2024-03-22 at 9 12 17 PM

Screenshot 2024-03-22 at 9 12 24 PM

Screenshot 2024-03-22 at 9 13 07 PM


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests ,Integration Tests,Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run  Functional Tests EE

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
Functional Tests EE build failure having known failure `StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest`. Related JIRA for failure is [ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331).

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests

**Pull request merged**
