### PR TITLE
Update AccountLock.php

### PR DESCRIPTION
**Pull request by klict**
fix for "Notice: Undefined index: lock_expires in vendor/magento/module-customer/Ui/Component/Listing/Column/AccountLock.php on line 44"

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=6952) <br/>All committers have signed the CLA.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by slavvka** [comment]
@klict, please cover your change with unit test.

**Comment by klict** [comment]
i can't perform unit test right now. if you want to add the small fix you can do it but i really don't care if you don't add it.

**Comment by Ctucker9233** [comment]
Still not included in 2.1.10

**Comment by ihor-sviziev** [comment]
@Ctucker9233 this fix included to release 2.2.0. You could prepare backport PR to ```2.1-develop``` branch if you want to see it fixed in one of next 2.1.x releases

**Pull request merged**
