### PR TITLE
Added grunt tasks autoloading (Issue #3491)

### PR DESCRIPTION
**Pull request by ravbetsky**
Simple change to the grunt configuration which enable autoloading tasks from `dev/tools/grunt/tasks/` folder

### CODE REVIEW

**Comment by hshar7** [comment]
Hi @ravbetsky could you please sign the CLA agreement? It is required for this PR to be processed.

**Comment by ravbetsky** [comment]
Hi, it's done.

**Comment by hshar7** [comment]
Internal MAGETWO-50273 created to process this PR

**Comment by arkadiych** [comment]
@ravbetsky, please merge the latest code base and resolve conflicts

**Comment by okorshenko** [comment]
@ravbetsky Thank you for contribution. Your Pull Request merged to develop branch.

**Comment by ravbetsky** [comment]
Hi! Sorry for the silence( And thank you for the good product!

**Pull request merged**
