### PR TITLE
Add new flexbox mixins

### LINKED ISSUE #30669: [Issue] Add new flexbox mixins
This issue is automatically created based on existing pull request: magento/magento2#30666: Add new flexbox mixins

---------

### Description (*)

This Pr is only improvement add some new flexbox mixins for reuse while developments
So frontenders can reuse it while modify or customise themes

Example when in less arrange layout 
we can use .lib-flex-center(); for get flexbox basic styles instead write multiple line like before

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

This Pr is only improvement add some new flexbox mixins for reuse while developments
So FE devs can reuse it while modify or customise themes

Example when in less arrange layout 
we can use .lib-flex-center(); for get flexbox basic styles instead write multiple line like before

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30669: Add new flexbox mixins

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Comment by mrtuvn** [comment]
Can we have new proceed on this

**Comment by mrtuvn** [comment]
Can we have proceed on this

**Comment by mrtuvn** [comment]
@magento run Static Tests

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
Rebased PR branch with mainline magento code branch

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Magento Health Index

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8619](https://jira.corp.magento.com/browse/ENGCOM-8619) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run 
Functional Tests EE, 
Functional Tests CE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE

**Comment by engcom-Bravo** [comment]
Hi @mrtuvn,

We are closing this PR.The PR is in Draft since longtime.

Once you are ready Please feel free to reopen it to process the PR further.

Thanks

**Pull request closed without merging**
