### PR TITLE
Replace deprecated constructs from Magento_Newsletter PHPUnit.

### PR DESCRIPTION
**Pull request by AndreyChorniy**
### Description (*)

Added compatibility PHPUnit8 for Magento Newsletter module
### Fixed Issues (if relevant)

1. magento/magento2#27500

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello @AndreyChorniy, could you please fix the same issues as already mentioned in your adjacent PR #27615.
Thank you! :)

**Review by lbajsarowicz — DISMISSED** [review]
:heavy_check_mark: Huge amount of work, congratulations!

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7269](https://jira.corp.magento.com/browse/ENGCOM-7269) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
The tests still fail.
```
PHP Fatal error:  Declaration of Magento\Newsletter\Test\Unit\Block\Adminhtml\Queue\PreviewTest::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /home/dev/sites/bravo/app/code/Magento/Newsletter/Test/Unit/Block/Adminhtml/Queue/PreviewTest.php on line 174
```

**Comment by AndreyChorniy** [comment]
Hello @dmytro-ch,
I am in progress with this, it will be fixed in a couple of hrs.

**Comment by dmytro-ch** [comment]
@magento run all tests

**Review by slavvka — CHANGES_REQUESTED** [review]
@AndreyChorniy please fix the static test:
```
PHP Code Mess has found error(s):
/var/www/html/app/code/Magento/Newsletter/Test/Unit/Block/Adminhtml/Template/PreviewTest.php:28	The class PreviewTest has a coupling between objects value of 13. Consider to reduce the number of dependencies under 13.
```

**Comment by slavvka** [comment]
And please resolve the conflicts

**Review by slavvka — APPROVED** [review]

**Pull request merged**
