### PR TITLE
MFTF: Replace repetitive actions with Action Groups for AdminCheckSubCategoryIsNotVisibleInNavigationMenuTest and ProductAvailableAfterEnablingSubCategoriesTest

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
AdminCheckSubCategoryIsNotVisibleInNavigationMenuTest and ProductAvailableAfterEnablingSubCategoriesTest are refactored according to the best practices followed by MFTF.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
Run AdminCheckSubCategoryIsNotVisibleInNavigationMenuTest and ProductAvailableAfterEnablingSubCategoriesTest in the local environment and verified the tests run successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by dmytro-ch** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7708](https://jira.corp.magento.com/browse/ENGCOM-7708) has been created to process this Pull Request

**Comment by dmytro-ch** [comment]
@magento run Semantic Version Checker

**Comment by engcom-Delta** [comment]
**Notice:** QA not applicable

**Pull request merged**
