### PR TITLE
Bugfix issue 17523

### PR DESCRIPTION
**Pull request by maximbaibakov**
### Description
Increasing number of cookies to 180 as supported by popular browsers.

### Fixed Issues (if relevant)
1. magento/magento2#17523

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @maximbaibakov. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by VladimirZaets** [comment]
Hi @maximbaibakov. Thanks for the collaboration. As I know, IE currently supports only 50 cookies. Currently, according to [https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements_browsers.html](browser support) document, Magento supported IE browsers.

**Comment by orlangur** [comment]
This does not solve any issue in fact as 180 cookies limit may be reached just like 50 until https://github.com/magento/magento2/issues/17195 is fixed properly.

**Comment by maximbaibakov** [comment]
Hi @orlangur and @VladimirZaets 

Thanks for taking time to review this PR. 

I do agree on some of your statements and disagree on the others.

**In regards to "IE currently supports only 50 cookies"**
It does not mean that Magento should limit functionality for other browsers. Sometimes certain extension or tracking systems aka Facebook Pixel could set cookies differently depends on a browser, country, OS and etc.

Also, the rfc6265 is setting limits to a browser, it is setting minimum requirements to a browser.  
Magento should not fail with an exception if the cookie size exceeded, it should still keep working.

**This does not solve any issue in fact**
@orlangur tend to disagree, it does solve issue for users who are using modern browsers like Edge, Chrome, Firefox and etc and the website still operating well in case of cookies limit increased

**Why more then 50 cookies could be presented on the website?**
- The website could have number of tracking systems aka Facebook, GA, GTM, Hotjar and etc.
- While each of the tracking systems could have 2-5 cookies as a group they could go above 50, especially, if your website has number of subdomains and cookies could be defined on top domain
- For example, Magento website together with Magento Marketplace website sometimes could have almost 50 cookies.

I think, increasing cookies should not harm to Magento as a platform and / or cookies limit should not get website down. 

What do you think? 

Regards,
Maxim

**Comment by VladimirZaets** [comment]
Hi @maximbaibakov. 
**In regards to "IE currently supports only 50 cookies"**
I agree that Magento shouldn't limit functionality for other browsers, but we can't simply just raise cookies to the limit of the new browsers, we should have some fallback to provide the correct system functionality

**Comment by orlangur** [comment]
> it does solve issue for users who are using modern browsers like Edge, Chrome, Firefox and etc and the website still operating well in case of cookies limit increased

No, it does not. Please check https://github.com/magento/magento2/issues/17195 and just repeat steps more times then to reach 50 limit.

> The website could have number of tracking systems aka Facebook, GA, GTM, Hotjar and etc.

You shouldn't have all of them enabled for one site. Having such amount of cookies is not good from any perspective, what is amount of cookies with vanilla Magento 2 installation?

Some browsers supporting 150+ cookies should not be a reason to increase limit ignoring RFC: http://browsercookielimits.squawky.net/
It's better to fix buggy implementation / improve by removing unnecessary cookies.

**Comment by sidolov** [comment]
Hi @maximbaibakov , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
