### PR TITLE
[Backport] Fixed Minicart close button overlapping

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Original Pull Request 
 https://github.com/magento/magento2/pull/20615

### Description (*)

Minicart close button overlapping in shipping address section whenever any user open minicart in mobile view on the checkout page
### Fixed Issues (if relevant)

1. magento/magento2#20614: Minicart close button overlapping in shipping address section whenever any user open minicart in mobile view on the checkout page

### Manual testing scenarios (*)

Steps to reproduce
Note : Testing should be in responsive view
Step 1: Go to frontend
Step 2: Login as customer
Step 3: Now add any product to cart and go to checkout
Step 4: In shipping address steps, open minicart

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by torhoehn** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your request. I'm working on Magento instance for you

**Comment by amol2jcommerce** [comment]
@mage2pratik Why you close?

**Comment by mage2pratik** [comment]
Hi @amol2jcommerce, I'm closing this PR as a duplicate #20844. Because I'm author of the original PR #20615.
Please refer Magento Code Contributions Guide for more detail. Thanks :)

**Pull request closed without merging**
