### PR TITLE
[Forwardport2.2] Fix incorrect type hinting in PHPDocs

### PR DESCRIPTION
**Pull request by chirag-wagento**
### Original Pull Request 
 https://github.com/magento/magento2/pull/15619

### Description
Incorrect PHPdoc causes warnings in IDE.

Changes applied:

1. Changed the return type for **setQty** method to the type it actually returns.
2. Removed the hint for newer thrown LocalizedException in PHPDocs of **register** and **setQty** methods.

### Fixed Issues
1. magento/magento2#13992: Incorrect phpdoc should be Shipment\Item not Invoice\Item

### Manual testing scenarios
1. This is not necessary, this just resolves warnings in the IDE. 

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @chirag-wagento. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by chirag-wagento** [comment]
As per this tickets comment https://github.com/magento/magento2/pull/16118#issuecomment-397261174 (comment) created new pull request.

**Comment by orlangur** [comment]
Hi @chirag-wagento, when porting pull requests author of the original commit must be preserved: https://github.com/magento/magento2/pull/15619/commits/ab64a2c39358c6f37d27206a16272cc176a33abe

Please cherry-pick this commit into your branch instead of doing a new commit from scratch and force push into the same branch.

**Comment by chirag-wagento** [comment]
Hi @orlangur  

Do you want cherry-pick https://github.com/magento/magento2/pull/15619/commits/ab64a2c39358c6f37d27206a16272cc176a33abe in to  **forwordport2.2-incorrect-type-hinting** branch and commit push?

In https://github.com/magento/magento2/pull/15619/commits/ab64a2c39358c6f37d27206a16272cc176a33abe  changed 2.1-develop. How can I cherry pick in 2.2-develop branch ?

**Comment by orlangur** [comment]
@chirag-wagento into the same branch: `chirag-wagento:incorrect-type-hinting-forwordport2.3`

> In ab64a2c changed 2.1-develop. How can I cherry pick in 2.2-develop branch ?

`git checkout 2.2-develop`
`git checkout -b incorrect-type-hinting-forwordport2.3`
`git cherry-pick ab64a2c`

**Comment by orlangur** [comment]
Closing due to inactivity. Feel free to reach me out anytime later if you wish to continue work on this pull request and it will be reopened.

**Pull request closed without merging**
