### PR TITLE
Accept any throwable exceptions in newrelic wrapper

### LINKED ISSUE #35854: NewRelic Wrapper is not allowing to capture TypeError
### Summary (*)
In the current newrelic wrapper class, we are can capture only the `\Exception` however when we try to capture any TypeError it's giving the below exception

NewRelic agent supports capturing any kind of Throwable errors ref: https://docs.newrelic.com/docs/apm/agents/php-agent/php-agent-api/newrelic_notice_error, so upgraded the NewRelicWrapper class to support any throwable type exceptions.

### Examples (*)
```
[2022-07-26T17:21:39.757093+00:00] report.CRITICAL: TypeError: Argument 1 passed to Magento\NewRelicReporting\Model\NewRelicWrapper::reportError() must be an instance of Exception, instance of TypeError given
```
### Proposed solution
In `\Magento\NewRelicReporting\Model\NewRelicWrapper::reportError`
```
    public function reportError(\Throwable $exception)
    {
        if ($this->isExtensionInstalled()) {
            newrelic_notice_error($exception->getMessage(), $exception);
        }
    }
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rmsundar1**
### Description (*)

In the current newrelic wrapper class, we are can capture only the \Exceptions however when we try to capture any TypeError it's giving the below exception

```
[2022-07-26T17:21:39.757093+00:00] report.CRITICAL: TypeError: Argument 1 passed to Magento\NewRelicReporting\Model\NewRelicWrapper::reportError() must be an instance of Exception, instance of TypeError given
```

NewRelic agent supports capturing any kind of Throwable errors ref: https://docs.newrelic.com/docs/apm/agents/php-agent/php-agent-api/newrelic_notice_error, so upgraded the NewRelicWrapper class to support any throwable type exceptions.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35854

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rmsundar1** [comment]
@magento run all tests

**Comment by rmsundar1** [comment]
@magento run Functional Tests CE

**Review by Den4ik — APPROVED** [review]
Hi @rmsundar1 
Thanks for you contribution.
✅ PR looks good for me

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Descrption:** NewRelic Wrapper is not allowing to capture TypeError
**Preconditions:**
Fresh Magento should be installed

**Manual testing scenario:**

1. Go to `app/code/Magento/NewRelicReporting/Model/NewRelicWrapper.php` in code base.
2. Check the function:`reportError`

**Before:** :heavy_multiplication_x: 
image



**After:** :heavy_check_mark:
image

**Pull request merged**
