### PR TITLE
Update TableBuilder.php

### PR DESCRIPTION
**Pull request by redelschaap**
Fixes an issue where attributes overwritten in the website scope were ignored when using flat product tables, because `$joinCondition` was always selecting attribute values from `store_id` `0`.

### CODE REVIEW

**Comment by okorshenko** [comment]
@redelschaap thank you for your contribution. It will be very helpful if you can provide information how we can test your fix. What was the issue and what is current/expected behavior.
Also, please, try to cover this fix the the auto test. 
Having this information I will be able to accept this PR faster. Thank you

**Comment by okorshenko** [comment]
Hi @redelschaap 
Could you please review my previous comment?

**Comment by redelschaap** [comment]
@okorshenko I will as soon as I have some free time :)

**Comment by okorshenko** [comment]
@redelschaap sure. Thank you for your time

**Comment by okorshenko** [comment]
Hi @redelschaap please open new PR once ready for delivery. Closing this PR for now.

**Pull request closed without merging**
