### PR TITLE
Fix issue #10565

### PR DESCRIPTION
**Pull request by thlassche**
Fix: Creation of a new product with custom attribute set now works again

### Description
https://github.com/magento/magento2/commit/85db4c87491d43fa4d4de59c6fe3d6cc1486835b#diff-620105b6e833499c14f4eb74ce8a4532 introduced some changes wich broke the add new product screen when choosing a custom attribute set with a multiselect attribute in it. This pull request fixes that

### Fixed Issues 
1. magento/magento2#10565: Magento ver. 2.1.8 New Product with Custom attribute set not workink

### Manual testing scenarios
1. Create a new product from admin, select a non-default attribute set
2. Check that the product form loads without JS errors

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by thlassche** [comment]
Please also backport this in the 2.1.x branch. This is also broken on the production release 2.1.8

**Comment by ishakhsuvarov** [comment]
@thlassche It would be nice to cover this case with a JS test. You may just update the existing one.

**Comment by thlassche** [comment]
@ishakhsuvarov Ok, will try to find some time this evening

**Comment by ishakhsuvarov** [comment]
@thlassche Thanks a lot. Please let us know if you need any help with it.

**Comment by thlassche** [comment]
@ishakhsuvarov Just added the tests

**Comment by ishakhsuvarov** [comment]
@thlassche Thank you

**Pull request merged**
