### PR TITLE
#2228; Encode xml entities in tag attributes

### PR DESCRIPTION
**Pull request by sergey-solo**
### Description (*)
Xml attributes needed to be encoded to allow special symbols such as `&amp;`.

### Fixed Issues (if relevant)
1. magento/magento2#2228 Problem with adding google fonts with ampersand into default_head_blocks.xml

### Manual testing scenarios (*)
1. Per #2228, add the following to add a link to a page using the following code. The exception shouldn't be thrown.
```
<link src="//fonts.googleapis.com/css?family=Open+Sans|Roboto+Condensed|Open+Sans+Condensed:400,300,300italic,400italic,600,600italic,700italic,700&amp;subset=latin,cyrillic" src_type="url" />
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by VladimirZaets** [comment]
@magento run all tests

**Comment by rodrigowebjump** [comment]
Hi @sergey-solo 

Please could you check the failing test?

Regards

**Review by rodrigowebjump — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-5761](https://jira.corp.magento.com/browse/ENGCOM-5761) has been created to process this Pull Request
:eight_spoked_asterisk: @rodrigowebjump, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
