### PR TITLE
Fix wrong merge result in afterMethods billing-address-form

### PR DESCRIPTION
**Pull request by ilnytskyi**
### Description (*)

Form xml components are not merged correctly in `afterMethods` part of `billing-address-form` on payment step in checkout
1. Customize form 
Selection_181

2. See that `sortOrder` and `component` is an array now, not an overriden value
Selection_180

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. Modify fields in `checkout_index_index.xml` `afterMethods.billing-address-form`
2. See that values are changed correctly  

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello @ilnytskyi, thank you for your contribution. Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) the changes should be covered by tests. Could you please cover your fix by automated tests?
Thank you!

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6226](https://jira.corp.magento.com/browse/ENGCOM-6226) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
Hello @ilnytskyi. Thank You for contribution. In order for us to be able to further process Your PR please cover it with appropriate Auto-Tests. Thank You.

**Comment by VladimirZaets** [comment]
@ilnytskyi , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Pull request closed without merging**
