### PR TITLE
[Customer] Fixing the code style for account edit template and Integration test

### PR DESCRIPTION
**Pull request by eduard13**
### Description (*)
While working on https://github.com/magento/partners-magento2ee/issues/100, I've noticed that we aren't able to adjust the code styles for the following template: `Magento_CustomerCustomAttributes::customer/form/edit.phtml`.
The main reason is that the `\Magento\Customer\Controller\AccountTest::testChangePasswordEditAction` checks the exactly html input tag, which fails if we update the template by moving some attribute values to a new line (for fixing the `Line exceeds 120 characters`).

So, the goal of this PR is to adjust the code styles for the customer account template (`Magento_Customer::customer/form/edit.phtml.`), fix the related integration tests and give the possibility to fix the static tests in `Magento_CustomerCustomAttributes::customer/form/edit.phtml`.

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/134

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by eduard13** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @eduard13, here is your [new Magento instance](https://pr-26710.instances.magento-community.engineering).
Admin access: [https://pr-26710.instances.magento-community.engineering/admin_f1d8](https://pr-26710.instances.magento-community.engineering/admin_f1d8)
Login: `2c9a436c` Password: `ed9ad4fcc263`
Instance will be terminated in up to 3 hours.

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run all tests

**Comment by eduard13** [comment]
Hi @lenaorobei, do you have any clue why these tests are never ending?

**Comment by lenaorobei** [comment]
@eduard13 let's try one more time and ask @slavvka for help.

**Comment by lenaorobei** [comment]
@magento run all tests.

**Comment by slavvka** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
@slavvka magic 🎉

**Comment by eduard13** [comment]
Thank you @lenaorobei and @slavvka.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-6836](https://jira.corp.magento.com/browse/ENGCOM-6836) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by engcom-Charlie** [comment]
Failed functional test not related to the changes in this PR test fails in 2.4-develop with MSI modules.
image

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@magento run all tests

**Pull request merged**
