### PR TITLE
avoid using deprecated escape* methods from AbstractBlock

### PR DESCRIPTION
**Pull request by sergiynezbritskiy**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sergeynezbritskiy** [comment]
@magento run all tests

**Comment by hostep** [comment]
Nice, great job, thanks!
But please target the [2.5-develop](https://github.com/magento/magento2/tree/2.5-develop) branch instead. Reasoning is explained in this sort-of duplicated PR: https://github.com/magento/magento2/pull/30639

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @sergeynezbritskiy,
Could you re-target your PR to the 2.5-develop branch?

**Comment by sergeynezbritskiy** [comment]
@magento run functional tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Review by ihor-sviziev — APPROVED** [review]

**Comment by gabrieldagama** [comment]
Hi @sergeynezbritskiy, thanks for working on this track! We've discussed this during the Public Community Triage meeting and we believe this can be delivered to `2.4-develop` instead since it's risk seems quite small.

Therefore, the amount of files on this PR makes it hard to review, so we would like to recommend the breakdown of this PR into several pull requests, the idea would be split it per module.

Hope that makes sense, thanks!

**Comment by hostep** [comment]
@gabrieldagama: I strongly disagree, please see my comments on https://github.com/magento/magento2/pull/30639#issuecomment-716181145

**Comment by gabrieldagama** [comment]
Hi @hostep, thanks for highlighting your concern.

Usually, we decide on which version something should be delivered based on backward compatibility, not on the number of changes, mostly because that is relative to how long that development cycle is and how much contribution/work is being done during that time.

Such changes have a small risk of breaking a custom theme, and I believe we are not removing the `escapeJs` method from `AbstractBlock`, so in this case, it is not mandatory for the custom theme to update all its template files, you would still be able to upgrade to next patch version without having a big cost of updating all the files.

However, I do understand your concern, having that many files to be reviewed would be hard and time-consuming (as this PR, that is why we recommended to split it into multiple PRs, per module). I will bring this up for the team once more and we can further discuss it.

From my personal point of view, I don't see any problem to 'postpone' such changes to 2.5 instead. 

Cc: @sidolov @sivaschenko @sdzhepa

**Comment by hostep** [comment]
Thanks for considering this @gabrieldagama 

Just to explain a bit more, when we compare a frontend file of an old magento version with a new version and if it contains a lot of these changes like used in this PR, it's hard to find **other** changes which could actually be important, because there is a lot of noise.

The exact same problem happened with Magento 2.3.3 where this gigantic change got accepted: https://github.com/magento/magento2/commit/8698a6959f5163ee26b4a900e8749e24ca33e319. All these changes are only cleanup but made it a lot more complex to figure out which other changes next to these were included in the frontend files.

Therefore, big cleanups in frontend files should only happen while working on a new major version in my opinion. Every new major version has a chance to cleanup or apply new coding standards to the entire code base (we recently had a discussion about this on Slack in the #coding-standard channel btw, see screenshot below).
However, we should really try to avoid doing these sort of things in minor versions, it costs too much time and is very frustrating to deal with when you want to perform a "simple" minor version bump as an end user.

If it is already hard to review these many changes for you guys, image that a lot of your end users also have to go through this review phase, it's not only you who are doing this.

Also, there are some reason why we try to apply all changes from core files to our custom themes:
- reducing of technical debt, the more our custom theme is up2date with core files, to less chances of some unexpected bugs which could appear one day
- being able to easily compare our custom theme with the core theme of Magento to figure out what changes we made, this helps a lot with debugging stuff, the less they differ, the better, so we try to apply all changes in the core to our custom theme on every single Magento upgrade

----

Screenshot 2021-01-15 at 11 47 23

**Comment by sergeynezbritskiy** [comment]
Hi @gabrieldagama I've split this PR onto smaller ones, one module - one PR.
Here is the list of related PRs:

https://github.com/magento/magento2/pull/31662
https://github.com/magento/magento2/pull/31663
https://github.com/magento/magento2/pull/31664
https://github.com/magento/magento2/pull/31665
https://github.com/magento/magento2/pull/31666
https://github.com/magento/magento2/pull/31667
https://github.com/magento/magento2/pull/31668
https://github.com/magento/magento2/pull/31669
https://github.com/magento/magento2/pull/31670
https://github.com/magento/magento2/pull/31671
https://github.com/magento/magento2/pull/31672
https://github.com/magento/magento2/pull/31673
https://github.com/magento/magento2/pull/31674
https://github.com/magento/magento2/pull/31675
https://github.com/magento/magento2/pull/31676
https://github.com/magento/magento2/pull/31677
https://github.com/magento/magento2/pull/31678
https://github.com/magento/magento2/pull/31679
https://github.com/magento/magento2/pull/31680
https://github.com/magento/magento2/pull/31681
https://github.com/magento/magento2/pull/31682
https://github.com/magento/magento2/pull/31683
https://github.com/magento/magento2/pull/31684
https://github.com/magento/magento2/pull/31685
https://github.com/magento/magento2/pull/31686
https://github.com/magento/magento2/pull/31687
https://github.com/magento/magento2/pull/31688
https://github.com/magento/magento2/pull/31689
https://github.com/magento/magento2/pull/31690
https://github.com/magento/magento2/pull/31691
https://github.com/magento/magento2/pull/31692
https://github.com/magento/magento2/pull/31693
https://github.com/magento/magento2/pull/31694
https://github.com/magento/magento2/pull/31695
https://github.com/magento/magento2/pull/31696
https://github.com/magento/magento2/pull/31697
https://github.com/magento/magento2/pull/31698
https://github.com/magento/magento2/pull/31699
https://github.com/magento/magento2/pull/31700
https://github.com/magento/magento2/pull/31701
https://github.com/magento/magento2/pull/31702
https://github.com/magento/magento2/pull/31703
https://github.com/magento/magento2/pull/31704
https://github.com/magento/magento2/pull/31705
https://github.com/magento/magento2/pull/31706
https://github.com/magento/magento2/pull/31707
https://github.com/magento/magento2/pull/31708
https://github.com/magento/magento2/pull/31709
https://github.com/magento/magento2/pull/31710
https://github.com/magento/magento2/pull/31711
https://github.com/magento/magento2/pull/31712
https://github.com/magento/magento2/pull/31713
https://github.com/magento/magento2/pull/31714
https://github.com/magento/magento2/pull/31715
https://github.com/magento/magento2/pull/31716
https://github.com/magento/magento2/pull/31717
https://github.com/magento/magento2/pull/31718
https://github.com/magento/magento2/pull/31719
https://github.com/magento/magento2/pull/31720
https://github.com/magento/magento2/pull/31721
https://github.com/magento/magento2/pull/31722
https://github.com/magento/magento2/pull/31723
https://github.com/magento/magento2/pull/31724
https://github.com/magento/magento2/pull/31725
https://github.com/magento/magento2/pull/31726
https://github.com/magento/magento2/pull/31727
https://github.com/magento/magento2/pull/31728

Hence closing this PR

**Comment by sivaschenko** [comment]
@hostep @ihor-sviziev we don't see enough risk of these changes to postpone them to 2.5.

The only BIC risks that I can see is extended or plaginized escape methods of blocks in extensions or customization.

Do you agree that is very unlikely and we should target these PRs to 2.4-develop branch?

**Comment by hostep** [comment]
Hi @sivaschenko, this is **not** about BIC, please see reasoning above...

**Comment by sivaschenko** [comment]
@hostep I see, that's about time to review the changes of patch release. Makes sense, thanks for bringing up this point.

**Comment by hostep** [comment]
Exactly. Magento should try to reduce the number of changes in between minor versions (especially for frontend related files) so these minor updates are as easily as possible and people are encouraged to perform them. Cleanup like suggested here or new coding styles should preferably only be applied to the entire codebase just before a new major version is released. Until a new major version is then released, no cleanup or new coding styles should be allowed, so we only see see significant changes and no unnecessary noise in between minor versions as they will make it easier to deal with as an end-user.

I completely understand that switching to this escaper in phtml files is recommended and make the codebase cleaner and more consistent, but that should have been done by the magento core-devs when they released this feature in 2.4.0, and they didn't. It's a bit annoying this happened, hopefully this sort of thing can be avoided in the future 🙂

**Pull request closed without merging**
