### PR TITLE
Remove unneccessary `overflowed` class from minicart sidebar widget

### LINKED ISSUE #29160: [Issue] Remove unneccessary `overflowed` class from minicart sidebar widget
This issue is automatically created based on existing pull request: magento/magento2#28963: Remove unneccessary `overflowed` class from minicart sidebar widget

---------

### Summary (*)
Magento 2.4-develop
After investigating minibasket sidebar widget I've noticed `isOverflowed` function that applies `overflowed` class to one of minibasket elements.

Searching further, it seems that the class or even the word `overflowed` in any case is not used anywhere in magento2 repository.

As I'm seeking any performance improvements for my personal Magento 2 project I thought it will be worth to submit the changes.

### Examples (*)
Can't think of any real testing scenarios. All I've done is I've kept adding products to basket to see if it changes at all the look and behaviour of minibasket

### Questions or comments
- Do I check the checklist below now, later, or wait for some maintainer to check them for me?
- This may break custom themes that expect `overflowed` class. However, I believe if custom theme want's this behaviour, then it should extend the JS widget.

### PR DESCRIPTION
**Pull request by lumnn**
### Description (*)
After investigating minibasket sidebar widget I've noticed `isOverflowed` function that applies `overflowed` class to one of minibasket elements.

Searching further, it seems that the class or even the word `overflowed` in any case is not used anywhere in magento2 repository.

As I'm seeking any performance improvements for my personal Magento 2 project I thought it will be worth to submit the changes.

### Manual testing scenarios (*)
Can't think of any real testing scenarios. All I've done is I've kept adding products to basket to see if it changes at all the look and behaviour of minibasket

### Questions or comments
- Do I check the checklist below now, later, or wait for some maintainer to check them for me?
- This may break custom themes that expect `overflowed` class. However, I believe if custom theme want's this behaviour, then it should extend the JS widget.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29160: Remove unneccessary `overflowed` class from minicart sidebar widget

### CODE REVIEW

**Comment by lumnn** [comment]
@magento run all tests

**Comment by ptylek** [comment]
Seems that test fails are not related to this PR. Nice catch!

**Review by ptylek — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-7771](https://jira.corp.magento.com/browse/ENGCOM-7771) has been created to process this Pull Request
:eight_spoked_asterisk: @ptylek, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked that minicart works as before on luma and blank themes
**Luma:**
#28963PrDesktop
#28963PRMobile
#28963Mobile1
#28963PRtab


**Blank:**
#28963PRBlankDesk
#28963PrBlankMobile
#28963PRBlankMobile1
#28963PRBlankTab

**Comment by engcom-Kilo** [comment]
@ptylek Please write issue number, if exist.

**Comment by engcom-Kilo** [comment]
@lumnn  Please write issue number, if exist.

**Comment by VladimirZaets** [comment]
@magento create issue

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
Failed Functional Tests B2B - not related to changes in this Pull Request.

**Pull request merged**
