### PR TITLE
#1684: Login failed error contains HTML tags

### LINKED ISSUE #1684: Login failed error contains HTML tags
### Preconditions

1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Provided _API Key (Client ID)_ . **Not** provided _Client Secret_
client_key

### Steps to reproduce (*)

1. Go to **Content - Media Gallery**, click **Search Adobe Stock**
2. Save an _Unlicensed image_ Preview
(_the image appeared in Media Gallery_)
3. Select the previously saved Unlicensed image
4. Click "three dots" and select **License**

### Expected result (*)
Propper error message, like _"Login failed. Please check if the Secret Key is set correctly and try again."_

### Actual result (*)
The message contains HTML tags. _Login failed. Please check if `<a href="https://magento2/admin/admin/system_config/edit/section/system/">the Secret Key</a> is set correctly and try again.`_
Selection_031

### PR DESCRIPTION
**Pull request by yolouiese**
### Need to verify (*)
- if error messages no longer contain HTML tags
- error messages are rendered as HTML

### Description (*)
- added a function to format and render error/success messages as HTML

### Fixed Issues (if relevant)
1. Fixes magento/adobe-stock-integration#1684: Login failed error contains HTML tags

### Manual testing scenarios (*)
1. Go to Content - Media Gallery, click Search Adobe Stock
2. Save an Unlicensed image Preview
3. (the image appeared in Media Gallery)
4. Select the previously saved Unlicensed image
5. Click "three dots" and select License

### Expected result (*)
Proper error message, like "Login failed. Please check if the Secret Key is set correctly and try again."

### CODE REVIEW

**Comment by yolouiese** [comment]
@magento run all tests

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the pull request @yolouiese , can you please cover the `messages` component with jasmine tests

**Comment by yolouiese** [comment]
@magento run all tests

**Comment by yolouiese** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-7981](https://jira.corp.magento.com/browse/ENGCOM-7981) has been created to process this Pull Request

**Review by sivaschenko — APPROVED** [review]

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-7981](https://jira.corp.magento.com/browse/ENGCOM-7981) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
@magento run all tests

**Pull request merged**
