### PR TITLE
Fix Issue 15679 : max length varchar

### PR DESCRIPTION
**Pull request by julienanquetil**
### Description

Update the const DB_MAX_VARCHAR_LENGTH to allow 1024 char instead of 256

### Fixed Issues (if relevant)

1. magento/magento2#15679: Attribute image exceeded max length

### Manual testing scenarios

1. import a file with content  of base_image column is:
https://images-na.ssl-images-amazon.com/images/I/61btlFPdvBL._SL1000_.jpg,https://images-na.ssl-images-amazon.com/images/I/51I%2Bhf88F7L._SL1000_.jpg,https://images-na.ssl-images-amazon.com/images/I/51y0P8C5-2L._SL1000_.jpg,https://images-na.ssl-images-amazon.com/images/I/51uwDQfaHrL._SL1000_.jpg,https://images-na.ssl-images-amazon.com/images/I/61Wh7FkyNYL._SL1000_.jpg
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@dmanners  could you review this PR?

**Comment by kokoc** [comment]
@julienanquetil  Standalone changes in import constants are not enough for this case. The import validation will probably pass such values, but these values will not fit into database, because DB is capable to accept only 255 chars. I believe the default behavior of DB is to trim the values, so data will be inconsistent.

**Comment by kokoc** [comment]
Changing DB column size may also trigger changes in elasticsearch and other system which are accepting varchars.

**Comment by dmanners** [comment]
Hi @julienanquetil I am going to close this PR at the moment because of inactivity. If you would like to work on this further please have a look at the comments from @kokoc and feel free to re-open when you have made some progress on this.

Thank you.

**Pull request closed without merging**
