### PR TITLE
Allow anonymous API reading access to CMS

### PR DESCRIPTION
**Pull request by real34**
for pages and blocks only.

So CMS content can be embedded in a SPA or another system

### CODE REVIEW

**Comment by Vinai** [comment]
Thank you for your contribution! Currently we are waiting for the travis builds to be fixed before we can further process you PR. Thanks for your patience.

**Comment by mazhalai** [comment]
@real34 Please merge latest from develop and rerun builds.

**Comment by real34** [comment]
@mazhalai I finally could find time to do it

**Comment by choukalos** [comment]
Thanks this looks great - please merge @mazhalai !

**Comment by vancoz** [comment]
Hi @real34, thank you for your contribution. Internal ticket number is MAGETWO-47940

**Comment by choukalos** [comment]
Linking to #3786 ; rolling back to requiring registered access

**Comment by KrystynaKabannyk** [comment]
Hello @real34, the bug is fixed now. Thanks for finding and reporting the issue!

**Pull request merged**
