### PR TITLE
Add ability to use tree-massactions ("sub-menus") for mass actions on…

### PR DESCRIPTION
**Pull request by sebastian-enz**
… grids

Just like in the Magento_Catalog ui components for the "Products" grid, the sales grids should also be able to use the tree-massactions component to realize "sub menus" for bulk actions. See: https://github.com/magento/magento2/blob/develop/app/code/Magento/Catalog/view/adminhtml/ui_component/product_listing.xml#L194

image

### CODE REVIEW

**Comment by sebastian-enz** [comment]
Any update, @NadiyaS? Simple change! :+1: Thank you! :)

**Comment by NadiyaS** [comment]
Hi @ikk0 ,
thank you for contribution and we are sorry for delay.
Please synchronize with develop branch and rerun builds, and then we can accept your PR.
Internal ticket number is MAGETWO-46673.

**Comment by sebastian-enz** [comment]
Hi @NadiyaS,

thanks! Just opened a new pull request: #4450

Hope that works.

**Comment by NadiyaS** [comment]
Hi @ikk0 ,
ok, thank you. I changed our internal ticket to process your new PR. This ticket is closed.

**Pull request closed without merging**
