### PR TITLE
Replace repetitive actions with Action Groups in AdminCreateSimpleProductZeroPriceTest

### LINKED ISSUE #32377: [Issue] Replace repetitive actions with Action Groups in AdminCreateSimpleProductZeroPriceTest
This issue is automatically created based on existing pull request: magento/magento2#32295: Replace repetitive actions with Action Groups in AdminCreateSimpleProductZeroPriceTest

---------

### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)

Run the test in the local environment and verified that it run successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)

Run the test in the local environment and verified that it run successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32377: Replace repetitive actions with Action Groups in AdminCreateSimpleProductZeroPriceTest

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by edenduong** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Review by edenduong — APPROVED** [review]
Thank you for your contribution !

**Comment by magento-engcom-team** [comment]
Hi @edenduong, thank you for the review.
[ENGCOM-8943](https://jira.corp.magento.com/browse/ENGCOM-8943) has been created to process this Pull Request
:eight_spoked_asterisk: @edenduong, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @kate-kyzyma, can you resolve conflicts? Thanks!

**Comment by kate-kyzyma** [comment]
Hi, @gabrieldagama 

The merge conflict is resolved.

Thanks.

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by edenduong** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Unit Tests

**Pull request merged**
