### PR TITLE
[TEST] 2.4

### PR DESCRIPTION
**Pull request by slavvka**
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by slavvka** [comment]
@magento run all tests with PHP 7.2

**Comment by slavvka** [comment]
@magento run all tests with PHP 7.3

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@magento run all tests with PHP 7.3

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@magento run all tests with PHP 7.3

**Review by VladimirZaets — APPROVED** [review]

**Review by VladimirZaets — APPROVED** [review]
ll

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7584](https://jira.corp.magento.com/browse/ENGCOM-7584) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by slavvka** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @slavvka. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @slavvka, here is your [Magento instance](https://i-28144-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28144-2-4-develop.instances.magento-community.engineering/admin_b007](https://i-28144-2-4-develop.instances.magento-community.engineering/admin_b007)
Login: `60c9469c` Password: `3008e08bd9f4`
Instance will be terminated in up to 3 hours.

**Pull request closed without merging**
