### PR TITLE
Removed 'cache:flush' command from tests

### LINKED ISSUE #31056: [Issue] Removed 'cache:flush' command from tests
This issue is automatically created based on existing pull request: magento/magento2#30996: Removed 'cache:flush' command from tests

---------
### Description
Remove 'cache:flush' command from tests to improve execution time for the following modules:
- Catalog
- CatalogUrlRewrite
- LoginAsCustomer

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Remove 'cache:flush' command from tests to improve execution time for the following modules:
- Catalog
- CatalogUrlRewrite
- LoginAsCustomer

### Resolved issues:
1. [x] resolves magento/magento2#31056: Removed 'cache:flush' command from tests

### CODE REVIEW

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE

**Comment by ihor-sviziev** [comment]
@lbajsarowicz you would love it!

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Comment by ihor-sviziev** [comment]
Hi @sergiy-v,
Now functional tests are passing, so seems like your changes are good. Are you going to do something more in this PR?

**Comment by rogyar** [comment]
Hi @sergiy-v. Thank you for grabbing this idea. Could you, please, specify in the description what modules were updated within the scope of this task? 

Thanks.

**Comment by sergiy-v** [comment]
> Hi @sergiy-v,
> Now functional tests are passing, so seems like your changes are good. Are you going to do something more in this PR?
Hello @ihor-sviziev. Thank you for re running 'Functional Tests EE'! I'm done with the changes in scope of this PR.

> Hi @sergiy-v. Thank you for grabbing this idea. Could you, please, specify in the description what modules were updated within the scope of this task?
Hello @rogyar. Thank you for the suggestion, I have added the module list for this changes to the PR description.

Thank you.

**Review by ihor-sviziev — APPROVED** [review]
Good job!
✔ Approved from my side

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8484](https://jira.corp.magento.com/browse/ENGCOM-8484) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8484](https://jira.corp.magento.com/browse/ENGCOM-8484) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests B2B

Ridiculous o.O

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run all tests

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Pull request merged**
