### PR TITLE
Fix/issue 21564 2.3

### PR DESCRIPTION
**Pull request by DenisSaltanahmedov**
### Description (*)
Admin order not enough quantity for item

### Fixed Issues (if relevant)
1. magento/magento2#21564: agento 2.2 Admin order not enough quantity for item

### Manual testing scenarios (*)
1. Login To magento backend
2. Go to Sales
3. Create new order
4. Select any customer.
5. select a product which have only one item remaining in stock (ex T-shirt)
6. a notification appears "We don't have as many "T-Shirt" as you requested. "
7. Press Update items and quantity, then this notification disappears

### Contribution checklist (*)
 - [*] Pull request has a meaningful description of its purpose
 - [*] All commits are accompanied by meaningful commit messages
 - [*] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @DenisSaltanahmedov. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by ghost** [comment]
@DenisSaltanahmedov unfortunately, only members of the maintainers team are allowed to assign developers to the pull request

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-21601.instances.magento-community.engineering).
Admin access: [https://pr-21601.instances.magento-community.engineering/admin](https://pr-21601.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4449](https://jira.corp.magento.com/browse/ENGCOM-4449) has been created to process this Pull Request

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @DenisSaltanahmedov thanks for the pull request!

I think the point of the changed method is to accumulate the quantity of product that can be represented by different quote items.

Considering the conditions, I don't think the quantity of a single quote item can be duplicated here (unless quote item is passed without an id first).

Can you please check if the problem is further in quantity validation process?

**Comment by DenisSaltanahmedov** [comment]
Hi @sivaschenko I have double checked the changes with different use cases on the admin part and the storefront, the changes work well, I did not note any problems.

**Comment by DenisSaltanahmedov** [comment]
Hi @sivaschenko, please let me know can proceed with the issue

**Comment by sivaschenko** [comment]
@DenisSaltanahmedov I would like to discuss this PR with peers this week, I'll let you know the outcome

**Comment by rogyar** [comment]
Hi @sivaschenko. Did you have a chance to discuss this PR? Thank you

**Comment by sivaschenko** [comment]
@DenisSaltanahmedov @rogyar Yes I did, thanks for your patience

**Review by sivaschenko — CHANGES_REQUESTED** [review]
I believe that product quantity accumulation should not be eliminated as that looks to be the only purpose this class exists. 

Instead, in my opinion, the root cause of the issue is `$quoteItemId` that is passed as `null` before it is passed having the correct numerical value.

I believe that `$this->_checkedQuoteItems` should not be updated if `$quoteItemId` is `null. 

So I would suggest adding the corresponding condition instead of removing quantity accumulation

**Comment by DenisSaltanahmedov** [comment]
Thanks @sivaschenko
I will add the changes as soon as possible.

**Comment by fvadev** [comment]
Hello @DenisSaltanahmedov,
I think your solution is not correct. I think such changes can have issues if you will have for example 2 different configurable/bundle products with the same associated simple product in the cart. I think the issue in the Magento\Sales\Block\Adminhtml\Order\Create\Items\Grid class, in the getItems() method. There is $item->setQty($item->getQty()) call which generate the error message. I am not fully sure why it is here. I have tried to comment this and login in admin area seems correct (for in stock/out of stock items)

**Comment by sidolov** [comment]
@DenisSaltanahmedov , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
