### PR TITLE
hide cookie notice instead of reloading site

### PR DESCRIPTION
**Pull request by torhoehn**
### Description

Instead of reloading the whole site when a use accepts the cookie notice, it should be accpetable to close the cookie notice only.

### Manual testing scenarios

1. Set Cookie Restricton Mode to 'Yes'
2. Open the Homepage and click on 'Allow Cookies'
3. The Cookie Notice will be closed immediately

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.6. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Comment by nuzil** [comment]
Hello @torhoehn 
We discovered the next feature with this PR: 
Currently if you only will hide this box, Google Analytic cookie still will not be set on this page and it will be created only if you will go to some other or refresh current. 
From Marketing point of view its a problem, cause then we cannot collect statistic about which page what the first one user visited. 
Maybe you can check the solution and align it in a correct way that Google Analytics cookie is set back, or revert your changes in case if its impossible to realise.
Thanks a lot!

**Comment by torhoehn** [comment]
Hi @nuzil. I did review it again. For me it looks like that the pageview will be recognized and it doesn't matter if the cookie notice will be closed by the user or not. So it's just a hint without any functionality in the background.

**Pull request merged**
