### PR TITLE
store labels is undefined if "Single-Store Mode" is on in Magento

### PR DESCRIPTION
**Pull request by cauliturtle**
Hi there,

I don't know if this is correct fix. I have an issue there would be exception when changing the status label in "Store" > "Order Status" if I turn on "Single-Store Mode".

### CODE REVIEW

**Comment by Vinai** [comment]
Thank you for your contribution! We have to wait for the travis build infrastructure to be fixed before we can continue to process your PR.

**Comment by vancoz** [comment]
Hi @cauliturtle please pull latest changes, we have fixed travis builds.

Thank you.

**Comment by KrystynaKabannyk** [comment]
Hello @cauliturtle, can you please update the code and cover it by Travis tests?

**Comment by NadiyaS** [comment]
Hi @cauliturtle ,
Internal ticket MAGETWO-52648 was created to process your PR.
Notice about your fix: $label is undefined when $data does not have 'store_labels'.
Please fix this and fix [failing builds](https://travis-ci.org/magento/magento2/builds/92298100).
Thanks

**Comment by SerhiyShkolyarenko** [comment]
Closing PR as not updated more than 14 days.

**Pull request closed without merging**
