### PR TITLE
Fixed #24840 Drop down icon invisible for a moment if not select value and click on Load Template

### LINKED ISSUE #24840: Drop down icon invisible for a moment if not select value and click on Load Template
### Preconditions (*)
M 2.3

### Steps to reproduce (*)
1. admin - email template - add new template
2. without select template click on Load Template

### Expected result (*)
drop down icon should be visible when click on Load Template

### Actual result (*)
image

### PR DESCRIPTION
**Pull request by gaurav-473**
Fixed magento/magento2#24840
### Preconditions (*)
M 2.3

### Steps to reproduce (*)
1. admin - email template - add new template
2. without select template click on Load Template

### Expected result (*)
drop down icon should be visible when click on Load Template

### Actual result (*)
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by gaurav-473** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @gauravagarwal1001. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @gauravagarwal1001, here is your [new Magento instance](https://pr-25022.instances.magento-community.engineering).
Admin access: [https://pr-25022.instances.magento-community.engineering/admin](https://pr-25022.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hi @gauravagarwal1001,
unfortunately, the current solution is rather a workaround and it does not seem to be solving the real issue.
The bug is related to the particular case for the specific form. I think it should not be fixed globally and especially using the force state for CSS rule.

Thank you!

**Comment by gaurav-473** [comment]
> Hi @gauravagarwal1001,
> unfortunately, the current solution is rather a workaround and it does not seem to be solving the real issue.
> The bug is related to the particular case for the specific form. I think it should not be fixed globally and especially using the force state for CSS rule.
> 
> Thank you!

Hi @dmytro-ch 
This issue will occurred with every dropdown field in every form whenever dropdown field is required in form because on click mage-error will set background-image none that's why I made dropdown background properties important.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6114](https://jira.corp.magento.com/browse/ENGCOM-6114) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by drpayyne** [comment]
Will be reverting this PR according to: https://github.com/magento/magento2/issues/24840#issuecomment-554867668

**Pull request merged**
