### PR TITLE
Fix inconsistent visual labels form login in theme blank

### LINKED ISSUE #28059: Missaligned fields on the Customer Login form
### Preconditions (*)

1. Magento CE 2.3.5-p1 vanilla without sample data is installed.
2. Magento Blank Theme is used.
3. Screen/Browser width >= 768px.

### Steps to reproduce (*)

1. Login to the admin panel.
2. Navigate to the Content -> Design -> Configuration.
3. Open the Global Store and set the applied theme to 'Magento Blank'.
4. Clean the cache(s).
5. Open the storefront and navigate to the 'Sign In' page (/customer/account/login/)
6. See the input fields on the Customer Login form are not stroking with the design of all other forms on the default Blank Theme.

### Expected result (*)

The input fields on the form should be inline with the labels (Like all other forms in the Blank Theme).

| Expected Result |
| ------------- |
| Schermafbeelding 2020-04-30 om 11 41 36  |

### Actual result (*)

The input fields are shown below the labels and not aligned.

| Actual Result |
| ------------- |
| Schermafbeelding 2020-04-30 om 11 48 50 |

### Additional information
On the Magento 2.4-develop instance the issue looks fixed. But this is not stroking with the styling of all the other form fields design of the Magento Blank theme.

| Result on 2.4-develop |
| ------------- |
| Schermafbeelding 2020-04-30 om 12 00 23 |

On the Magento 2.3.5-p1 the issue is probably caused by the following css line:

Schermafbeelding 2020-04-30 om 12 02 45

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

After this patch apply will have
#1 Remove unnecessary styles set width for container control wrap input fields
#2 Make login form visual look consistently like other form in blank theme (previous fix not good for UX)

### Related Pull Requests

#27544

### Fixed Issues (if relevant)

1. fixes magento/magento2#28059: Missaligned fields on the Customer Login form

### Manual testing scenarios (*)

1. Magento CE 2.3.5+
2. Magento Blank Theme is used.
3. Screen/Browser width >= 768px.
4. Go to account login page

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ptylek** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @ptylek. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @ptylek, here is your [new Magento instance](https://pr-28084.instances.magento-community.engineering).
Admin access: [https://pr-28084.instances.magento-community.engineering/admin_0017](https://pr-28084.instances.magento-community.engineering/admin_0017)
Login: `276123b3` Password: `a9eaee57d73f`
Instance will be terminated in up to 3 hours.

**Review by ptylek — APPROVED** [review]

**Comment by ptylek** [comment]
Functional Tests B2B fails not related to PR

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-7507](https://jira.corp.magento.com/browse/ENGCOM-7507) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual tesing scenario:**

1. Login to the admin panel;
2. Navigate to the _Content -> Design -> Configuration_.
3. Open the Global Store and set the applied theme to 'Magento Blank'.
4. Clean the cache(s).
5. Open the storefront and navigate to the 'Sign In' page (Screen/Browser **width >= 768px**)

**Before:** :heavy_multiplication_x: Input fields on the form aren't inline with the labels

Screenshot from 2020-05-05 09-49-05
 
**After:** :heavy_check_mark: Input fields on the form inline with the labels

Screenshot from 2020-05-05 09-54-38

The design of all other forms on the default Blank Theme is the same. Like this:
Screenshot from 2020-05-05 10-21-57

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
The failing functional tests are not related to the change in this pr.

**Pull request merged**
