### PR TITLE
Fix anchor without href attribute

### LINKED ISSUE #30723: skiptarget.phtml is a broken anchor
### Preconditions (*)
No preconditions, I have observed this in Magento versions 2.3.5 to 2.4.0
Magento 2.4-develop

### Steps to reproduce (*)
Browse to the homepage of site, inspect the source code and look for the following markup under maincontent:
app/code/Magento/Theme/view/frontend/templates/html/skiptarget.phtml
`<a id="contentarea" tabindex="-1"></a>`

### Expected result (*)
The rendered anchor should have a href attribute, I've not been able to determine the purpose of this code but at the very least it should be:
<a id="contentarea" href="#" tabindex="-1"></a>
or a suitable URL for the purpose it is designed to serve.

### Actual result (*)
The href attribute is not rendered.
image

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

#1 Replace `a` tag with `span` for solve problem missing href
Lighthouse report complained about not having href on <a> tag and lowered score for SEO metric.
#2 Clean up unneccesary block class defined in layout
https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/layouts/xml-instructions.html#fedg_layout_xml-instruc_ex_block

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30723

### Manual testing scenarios (*)

1. View page source in homepage
2. Search anchor with attribute tabindex but not have href 
3. Verify html tag change from a to span

### Questions or comments

CC @alex-james
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
From first look - looks good. Let's wait for test results

@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Integration Tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8487](https://jira.corp.magento.com/browse/ENGCOM-8487) has been created to process this Pull Request

**Comment by mrtuvn** [comment]
Rebased code only not change anything

**Comment by ptylek** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Database Compare, Functional Tests B2B, Functional Tests EE

**Comment by mrtuvn** [comment]
Screen Shot 2020-12-10 at 17 44 13
fails tests not related with changes in PR

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8487](https://jira.corp.magento.com/browse/ENGCOM-8487) has been created to process this Pull Request

**Review by ptylek — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-8487](https://jira.corp.magento.com/browse/ENGCOM-8487) has been created to process this Pull Request

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B

**Comment by mrtuvn** [comment]
@ihor-sviziev Also this pr should test and merge soon. Simple change and can approve fast

**Comment by ihor-sviziev** [comment]
@mrtuvn the QA team is testing PRs according to priority. This PR has P4 which is the lowest one, that's why it's not getting tested for so a long time.

**Comment by mrtuvn** [comment]
Thanks you for the infor

**Comment by mrtuvn** [comment]
@sidolov @gabrieldagama I think this small PR valid for increase priority since this PR can affect to a lot store online when benchmark with lighthouse. With increase a little score after apply this patch

**Comment by gabrieldagama** [comment]
Hi @mrtuvn, would you like to participate in our Public Triage meeting tomorrow? I will bring this up for discussion, it would be nice to have you there.

More details here: https://github.com/magento/magento2/wiki/Public-Triage-Meeting

**Comment by mrtuvn** [comment]
In my location time maybe around midnight new Wednesday

**Comment by mrtuvn** [comment]
@gabrieldagama

**Comment by mrtuvn** [comment]
I think we can stay with priority P4 when this not impact directly to functionality

**Comment by vandijkstef** [comment]
So this element is solely used for a target, to navigate to, from the skip-to-content link. 

Please consider:

- Removing tabindex attribute (a span-element is not focusable by default. It was intended to make the a element non-focusable, and this target should not be 'targetable' nor 'clickable') [MDN Tabindex](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex)
- Completely removing 'skiptarget.phtml' and targeting to #maincontent (Though this might conflict based on the theme used)

**Comment by engcom-Bravo** [comment]
Hi @mrtuvn,

We are closing this PR.The PR is in Draft since longtime.

Once you are ready Please feel free to reopen it to process the PR further.

Thanks

**Pull request closed without merging**
