### PR TITLE
fix: prevent inline-block issue in name form due to space and font-size

### PR DESCRIPTION
**Pull request by DanielRuf**
### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/16047

### Manual testing scenarios

1. open a page where the name form is eg /customer/account/edit/
2. compare the space between asterisk / required field indicator to other fields with the required field indicator

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by VladimirZaets** [comment]
Hi, @DanielRuf, I took your PR into processing, thank you for collaboration.

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.6 release.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Comment by hitesh-wagento** [comment]
Hi @DanielRuf 

Could you please advice me why are you change Magento2 coding standard ?

Thanks

**Comment by DanielRuf** [comment]
> Hi @DanielRuf
> 
> Could you please advice me why are you change Magento2 coding standard ?
> 
> Thanks

Sorry but I do not understand what you mean.

**Comment by DanielRuf** [comment]
> Could you please advice me why are you change Magento2 coding standard ?

This is not a coding standard. Check the other fields. inline-block adds an empty space when you have a space in the HTML, which can be removed with hacks like font-`size:0` or by removing spaces between the tags. The second approach is used in the other parts of the form and so this is consistent with the rest.

I did not change any coding standard.

**Comment by DanielRuf** [comment]
See https://css-tricks.com/fighting-the-space-between-inline-block-elements/

**Comment by hitesh-wagento** [comment]
Hi @DanielRuf

Thanks for clarification :)

**Pull request merged**
