### PR TITLE
MFTF: Extract Action Groups to separate files - magento/module-user

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Extract each Action Group to separate file, to follow MFTF Best Practices.

### Fixed Issues (if relevant)
1. magento/magento2#22853

### Questions or comments
Had to extract the changes per-module. The previous try failed, because of conflicts.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6357](https://jira.corp.magento.com/browse/ENGCOM-6357) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by lbajsarowicz** [comment]
@VladimirZaets / @okorshenko / @okolesnyk / @dmytro-ch 

Dear Maintainers, due to your concerns about **backward compatibility**, I provided the `_Deprecated_ActionGroup.xml` that provides the deprecated ActionGroups that will be loaded like before, but extra **comment** was added to notify about **depreciation**.

Hope that will let you merge that sooner than with `2.4`

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6357](https://jira.corp.magento.com/browse/ENGCOM-6357) has been created to process this Pull Request

**Pull request merged**
