### PR TITLE
chore: remove old JavaScript fixes and workarounds for IE

### PR DESCRIPTION
**Pull request by DanielRuf**
### Description (*)

This PR removes old fixes and workarounds for IE.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by VladimirZaets** [comment]
Hi @DanielRuf thanks for collaboration.  I think we shouldn't remove the code from external libraries, As for me, the updating of libraries the right solution in the current case

**Comment by DanielRuf** [comment]
@VladimirZaets so shall I revert it just for jQuery and knockout but keep the other changes?

**Comment by VladimirZaets** [comment]
@DanielRuf Yes, revert it only for jQuery and Knockout. Thanks

**Comment by DanielRuf** [comment]
> @DanielRuf Yes, revert it only for jQuery and Knockout. Thanks

Done.

**Comment by VladimirZaets** [comment]
@DanielRuf thanks.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3547](https://jira.corp.magento.com/browse/ENGCOM-3547) has been created to process this Pull Request

**Comment by DanielRuf** [comment]
Seems there is an issue with the unit tests. I'll check this

**Comment by DanielRuf** [comment]
Fixed, CI produced timeouts.

**Comment by DanielRuf** [comment]
@magento-engcom-team give me 1.4.0 instance

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your request. I'm working on Magento 1.4.0 instance for you

**Comment by DanielRuf** [comment]
@magento-engcom-team give me 2.0.0 instance

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your request. I'm working on Magento 2.0.0 instance for you

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3547](https://jira.corp.magento.com/browse/ENGCOM-3547) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
Hi @DanielRuf during testing PR changes I found issue with products grid on category edit page
#19330Pr
Looks like else block is necessary in if-else statement as [transport.responseText.is JSON()](https://github.com/magento/magento2/blob/900fdb79a25e488584976e3102e878867babf38b/lib/web/mage/adminhtml/grid.js#L247) return false and its used not only with IE(I tested on Chrome).
Could you take a look?

**Comment by DanielRuf** [comment]
Hi @VasylShvorak,

Thanks for the feedback. I think I'll revert the change in the grid.

**Comment by DanielRuf** [comment]
> I think I'll revert the change in the grid.

**Review by sivaschenko — CHANGES_REQUESTED** [review]
@DanielRuf thanks for the update! I think it could be a good idea to update comment for reverted code block so that nobody attempt to remove it later. Is that code block required for all browsers?

**Comment by DanielRuf** [comment]
> Is that code block required for all browsers?

Seems so, at least for IE11 which is still supported by MS.

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3547](https://jira.corp.magento.com/browse/ENGCOM-3547) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
Hi @DanielRuf I have tested PR changes and in result quick search in admin doesn't work: we can't navigate to any option from proposed dropdown list. Looks like one of the removed functions(mousedown: function) is running also on Chrome and Firefox, and is necessary for quick search in admin.

**Comment by DanielRuf** [comment]
Well then the comments are not correct in general. Then let's close this PR.
But interesting that I've got two review approvals and now the issues are found ;-)

**Comment by DanielRuf** [comment]
Might be some good parts where code can be refactored or the comments be removed.

**Pull request closed without merging**
