### PR TITLE
Fix typo in PHPDoc block

### LINKED ISSUE #38961: [Issue] Fix typo in PHPDoc block
This issue is automatically created based on existing pull request: magento/magento2#38940: Fix typo in PHPDoc block

---------

### Description (*)

This PR remove a unknown referenced variable in PHPDoc for `$helper` variable declaration.

### Manual testing scenarios (*)

This fix has no testing scenario, because is a code typo.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by jlnarvaez**
### Description (*)

This PR remove a unknown referenced variable in PHPDoc for `$helper` variable declaration.

### Manual testing scenarios (*)

This fix has no testing scenario, because is a code typo.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38961: Fix typo in PHPDoc block

### CODE REVIEW

**Comment by jlnarvaez** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento create issue

**Review by edenduong — APPROVED** [review]
Thank you for your contribution!

**Comment by engcom-Dash** [comment]
QA is not required for this change since it only updates the property annotation for $helper. 

Builds are failing so moving it to extended testing.

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Unit Tests, Integration Tests, Functional Tests EE, Functional Tests B2B

**Comment by engcom-Dash** [comment]
Functional test EE failures are different in the last two runs. Additionally, B2B build failure contains one known issue.
(Issues 1)[https://jira.corp.adobe.com/browse/ACP2E-3314]

Function test B2B
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38940/38eb68aab93361bb013f820264130726/Functional/allure-report-b2b/index.html#categories/33b16da120eda74024a2e0f513c01ac4/70ec1976d2d60cac/
image

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38940/940e631d01d50c07e05b2d24e4ea3cc0/Functional/allure-report-b2b/index.html#categories/6f15b2b039379618445a7d928f9735df/54f0b7fb2360e01b/
image

Functional EE

Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38940/302b362edf5f92bb9abe90764f72fb08/Functional/allure-report-ee/index.html#categories/fa4393da515eaa6ecde572b60691d27d/6da05487bb65132a/
image

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38940/0624c439a571e823cdc01e0592fd9d81/Functional/allure-report-ee/index.html#categories/75b40a63f79830217aae704c6d6af940/fa606581008098c9/
image

Hence moving to merge in progress.

**Comment by engcom-Dash** [comment]
We have seen static failures in mainline PR after merging this PR into that. Hence for now moving this PR to Extended testing.

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Pull request merged**
