### PR TITLE
[MFTF] Create AdminOpenCartPriceRulesPageActionGroup

### PR DESCRIPTION
**Pull request by Usik2203**
This PR introduce new `AdminOpenCartPriceRulesPageActionGroup`

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/349

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by Usik2203** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Comment by rogyar** [comment]
@magento run Functional Tests B2B

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8297](https://jira.corp.magento.com/browse/ENGCOM-8297) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8297](https://jira.corp.magento.com/browse/ENGCOM-8297) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Pull request merged**
