### PR TITLE
WIP: Cleanup ObjectManager usage - Magento_Catalog

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This PR cleanups ObjectManager usage in Magento_Catalog, adds additional dependencies with backward compatibility to api classes, and removes object manager instantiation from non-api classes

### Fixed Issues (if relevant)

N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @Bartlomiejsz,
Could you update your PR and let me know when I can review it?

**Comment by Bartlomiejsz** [comment]
Hi @ihor-sviziev, once it will be ready for review I'll change it from draft. At this stage I'm not even sure if it will be possible to cover all catalog with single PR.

**Comment by ihor-sviziev** [comment]
No problem, let’s split to few parts, it will be much easier to deliver it
quickly

**Comment by ihor-sviziev** [comment]
Hi @Bartlomiejsz,
I see that you've started creating smaller PRs instead of this big one, so I'm closing this PR.

**Pull request closed without merging**
