### PR TITLE
Fixed shipping method block alignment issue

### PR DESCRIPTION
**Pull request by vishal-7037**
### Description (*)
Fixed shipping method block alignment issue at sales order page

### Fixed Issues (if relevant)

1. magento/magento2#21962: Magento Sales Order: Design Align issue

### Manual testing scenarios (*)

1. Login to admin
2. Go to Sales > Order, Open any order.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21963) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @vishal-7037. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4594](https://jira.corp.magento.com/browse/ENGCOM-4594) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
✔️ QA passed

**Comment by p-bystritsky** [comment]
@vishal-7037 
We can not accept this PR as it brokes page layout and makes "Get shipping methods and rates" hyperlink unclickable.
Peek 2019-04-03 15-04

**Comment by vishal-7037** [comment]
Hi @dmytro-ch,
I've updated the requested changes.

**Comment by p-bystritsky** [comment]
@vishal-7037 we still have multiple functional test failures:

MAGETWO-94470: Checking availability of 'Credit memo' button for order with no payment required
[NO TESTCASEID]: Create Order in Admin and update bundle product configuration
[NO TESTCASEID]: Fields validation is required to create an order from Admin Panel
MAGETWO-61001: Free Shipping is not available in Admin if Minimum Order Amount does not match 
MAGETWO-92925: Admin order is not restricted by 'Minimum Order Amount' configuration.
MAGETWO-92980: Email is required to create an order from Admin Panel
MAGETWO-93677: Create order using Braintree payment
MAGETWO-94472: Admin should be able to open a New Credit Memo Page from Invoice Page for Order with tax and discount and payed using online payment method
MAGETWO-95175: Checking Credit memo Totals
MC-6029: UI validation for Payment methods when creating an order from admin

**Comment by vishal-7037** [comment]
Hi @p-bystritsky,
Thanks for quick reply. I've made changes regarding the design issue.
I don't think so above listed functional test failure because of these changes.

Can you please verify once?

Thanks.

**Comment by p-bystritsky** [comment]
@vishal-7037, I've fixed functional tests.

**Comment by vishal-7037** [comment]
Hi @p-bystritsky,
Okay. I've got it. 
Thank you.

**Pull request merged**
