### PR TITLE
API annotate IoInterface

### PR DESCRIPTION
**Pull request by navarr**
IoInterface needs to be @api annotated in order to be useful to third party developers

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by sidolov** [comment]
Hi @navarr , can you describe the scenario when you need to use IoInterface directly? 
I think it would better to use `\Magento\Framework\Filesystem\DriverInterface` for scenarios with the file system, and it's already marked as API.

**Comment by navarr** [comment]
@sidolov DriverInterface is important for a class that expects an instance of \Magento\Framework\Filesystem\Io\Ftp or \Magento\Framework\Filesystem\Io\Sftp (which I would also like to see annotated and will create a PR for if this one is accepted)

**Comment by navarr** [comment]
@sidolov Is my previous description satisfactory?

**Comment by magento-engcom-team** [comment]
Hi @navarr. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Pull request merged**
