### PR TITLE
Replace repetitive actions with AdminCreateConfigurableProductWithDisabledChildrenProductsTest

### LINKED ISSUE #33775: [Issue] Replace repetitive actions with AdminCreateConfigurableProductWithDisabledChildrenProductsTest
This issue is automatically created based on existing pull request: magento/magento2#32112: Replace repetitive actions with AdminCreateConfigurableProductWithDisabledChildrenProductsTest

---------

### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run the test in the local environment and verified that it run successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
The test is refactored according to the best practices followed by MFTF.

### Manual testing scenarios (*)
Run the test in the local environment and verified that it run successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#33775: Replace repetitive actions with AdminCreateConfigurableProductWithDisabledChildrenProductsTest

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run@magento run Functional Tests B2B, Functional Tests CE

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run Functional Tests B2B

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-8919](https://jira.corp.magento.com/browse/ENGCOM-8919) has been created to process this Pull Request

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests B2B

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-8919](https://jira.corp.magento.com/browse/ENGCOM-8919) has been created to process this Pull Request

**Comment by eduard13** [comment]
@magento create issue

**Comment by engcom-Charlie** [comment]
✔️ QA Passed

The provided MFTF test case is working fine and green in build. Please find the Allure report for the same.

image

image

**Pull request merged**
