### PR TITLE
Increase redis session max_concurrency limit from 6 to 32

### LINKED ISSUE #17310: session_start(): Failed to read session data: user (path: /var/lib/php/sessions)
While viewing the orders page in the admin area and opening several orders I'm facing an error message.

### Preconditions
1. PHP 7.1.17-1
2. Redis server v=3.0.6
3. set redis as the session handler in env.php
3.1 see session config:
```
`'session' => [
        'save' => 'redis',
        'redis' => [
            'host' => '<IP>',
            'port' => '<PORT>',
            'password' => '',
            'timeout' => '2.5',
            'persistent_identifier' => '',
            'database' => '0',
            'compression_threshold' => '2048',
            'compression_library' => 'gzip',
            'log_level' => '1',
            'max_concurrency' => '6',
            'break_after_frontend' => '5',
            'break_after_adminhtml' => '30',
            'first_lifetime' => '600',
            'bot_first_lifetime' => '60',
            'bot_lifetime' => '7200',
            'disable_locking' => '0',
            'min_lifetime' => '60',
            'max_lifetime' => '2592000'
        ]
    ],`
```
2. have orders in your system

### Steps to reproduce
1. Browse the order pages in the admin area
2. click on an order
3. go back to the order list
4. click on an other order again
5. retry several times
6. see error message in the admin area:
image

### Expected result
1. Browsing pages in the admin area shouldn't throw an error

### Actual result
Message in step 6 of reproduction appears, in the log I can find the following:
```
{"0":"Warning: session_start(): Failed to read session data: user (path: /var/lib/php/sessions) in /vendor/magento/framework/Session/SessionManager.php on line 193","1":"#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'session_start()...', '/home/cloudpane...', 193, Array)\n#1 /vendor/magento/framework/Session/SessionManager.php(193): session_start()\n#2 /generated/code/Magento/Backend/Model/Session/Interceptor.php(63): Magento\Framework\Session\SessionManager->start()\n#3 /vendor/magento/framework/Session/SessionManager.php(130): Magento\Backend\Model\Session\Interceptor->start()\n#4 /generated/code/Magento/Backend/Model/Session/Interceptor.php(14): Magento\Framework\Session\SessionManager->__construct(Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Session\SidResolver\Proxy), Object(Magento\Backend\Model\Session\AdminConfig), Object(Magento\Framework\Session\SaveHandler), Object(Magento\Framework\Session\Validator), Object(Magento\Framework\Session\Storage), Object(Magento\Framework\Stdlib\Cookie\PhpCookieManager), Object(Magento\Framework\Stdlib\Cookie\CookieMetadataFactory), Object(Magento\Framework\App\State))\n#5 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Magento\Backend\Model\Session\Interceptor->__construct(Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Session\SidResolver\Proxy), Object(Magento\Backend\Model\Session\AdminConfig), Object(Magento\Framework\Session\SaveHandler), Object(Magento\Framework\Session\Validator), Object(Magento\Framework\Session\Storage), Object(Magento\Framework\Stdlib\Cookie\PhpCookieManager), Object(Magento\Framework\Stdlib\Cookie\CookieMetadataFactory), Object(Magento\Framework\App\State))\n#6 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Backend...', Array)\n#7 /vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Backend...')\n#8 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Backend...')\n#9 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'session', 'Magento\\Store\\A...')\n#10 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Store\\A...', Array, Array)\n#11 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Store\\A...', Array, Array)\n#12 /vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Store\\A...')\n#13 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Store\\A...')\n#14 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Framewo...', NULL, 'redirect', 'Magento\\Backend...')\n#15 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Backend...', Array, Array)\n#16 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Backend...', Array, Array)\n#17 /vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Backend...')\n#18 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(144): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Backend...')\n#19 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(230): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Magento\\Backend...', NULL, 'context', 'Magento\\Ui\\Cont...')\n#20 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Magento\\Ui\\Cont...', Array, Array)\n#21 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Magento\\Ui\\Cont...', Array, Array)\n#22 /vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Ui\\Cont...', Array)\n#23 /vendor/magento/framework/App/ActionFactory.php(40): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Ui\\Cont...')\n#24 /vendor/magento/framework/App/Router/Base.php(297): Magento\Framework\App\ActionFactory->create('Magento\\Ui\\Cont...')\n#25 /vendor/magento/framework/App/Router/Base.php(158): Magento\Framework\App\Router\Base->matchAction(Object(Magento\Framework\App\Request\Http), Array)\n#26 /vendor/magento/framework/App/FrontController.php(50): Magento\Framework\App\Router\Base->match(Object(Magento\Framework\App\Request\Http))\n#27 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))\n#28 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)\n#29 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))\n#30 /generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)\n#31 /vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))\n#32 /generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()\n#33 /vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()\n#34 /pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))\n#35 {main}","url":"/admin/mui/index/render/key/[MASKED]/order_id/[MASKED]]?namespace=payone_sales_order_view_transactionstatus_grid&sorting%5Bfield%5D=sequencenumber&sorting%5Bdirection%5D=asc&isAjax=true","script_name":"/index.php"}
```

The path `/var/lib/php/sessions` was never set anywhere. I actually can't understand why Magento is trying to use the path when redis is configured. It may be related to `SessionManager->registerSaveHandler()`?

### PR DESCRIPTION
**Pull request by marvinhinz**
# Description (*)

The default redis session concurrency limit is fairly low. This sometimes triggers error pages for customers who might have opened multiple links in new tabs. 

I see no real drawback increasing this default value from 6 to 32. 
For us this solved the problem completely in production systems. 

Additional investigation is described in https://github.com/magento/magento2/issues/17310#issuecomment-410333850 and https://github.com/magento/magento2/issues/17310#issuecomment-410672582

### Fixed Issues (if relevant)
1. Fixes magento/magento2#17310 that was wrongly closed by a now deleted user.

### Manual testing scenarios (*) copied from @chris-pook 
1. Using Google Chrome, login to the admin area
2. Open 10 or more browser tabs with the orders grid page
3. Click the left most tab
4. Hold shift and click the right most tab (this selects all tabs)
5. Right click the right most tab and select "reload"
6. Check the tabs after they have all reloaded, only ~6 will successfully load, the rest will exhibit this error *
7. Check the var/report folder for the start_session error report relating to the tabs that failed.
8. Now modify the max_concurrency to a value greater than the number of tabs, reload them all again and none will fail.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by marvinhinz** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@marvinhinz this case looks really strange and not sure if we really need to fix it.
Could you describe what the **real** issue you on production? I don't think anyone from customers will reload 10 tabs at once.

**Comment by marvinhinz** [comment]
> @marvinhinz this case looks really strange and not sure if we really need to fix it.
> Could you describe what the **real** issue you have on production? I don't think anyone from customers will reload 10 tabs at once. Is there any use case when it's needed?

Thats actually a real issue. When testing our production systems its not uncommon to open many links with the ctrl key pressed, or using the mouswheelbutton. Also personally some customers tend to do this for e.g. comparing products/prices etc.

> Also not clear - do we have such issue in case if we use for instance session in files instead of redis? What behavior we have in this case?

No, afaik this happens only with redis session enabled.

**Comment by ihor-sviziev** [comment]
@marvinhinz thank you for the info! will be really useful!

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7852](https://jira.corp.magento.com/browse/ENGCOM-7852) has been created to process this Pull Request

**Comment by fritzmg** [comment]
> I don't think anyone from customers will reload 10 tabs at once. Is there any use case when it's needed?

The problems arise because Magento will cause several AJAX requests to be executed after the initial request. E.g. for loading customer sections, or JavaScript modules. And depending on the theme and extensions you have installed, this number may increase drastically.

**Comment by marvinhinz** [comment]
> In our instances even `32` was not enough. Why not set it even higher by default? Is there a drawback?

What value was sufficient for your projects? I dont think there would be drawbacks increasing it to for example 128? 


@ihor-sviziev what do you think?

**Comment by ihor-sviziev** [comment]
I think it was set to such small value by default in order to prevent
single customer to send too much requests and causing big load on
production instance

**Comment by fritzmg** [comment]
@marvinhinz we used `64` in the end.

@ihor-sviziev but does that make much sense? The requests are not prevented by this. And even if you want to reduce the load on the Redis server, then the fallback needs to work, which it currently does not (see #17310). And even if the fallback would work, it would simply increase the I/O load on the server - which is something that using the Redis Session Cache is supposed to avoid.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

Redis server;
Use Redis for session storage [devdocs](https://devdocs.magento.com/guides/v2.4/config-guide/redis/redis-session.html)

```
'session' =>
    array (
      'save' => 'redis',
      'redis' =>
      array (
        'host' => '127.0.0.1',
        'port' => '6379',
        'password' => '',
        'timeout' => '2.5',
        'persistent_identifier' => '',
        'database' => '2',
        'compression_threshold' => '2048',
        'compression_library' => 'gzip',
        'log_level' => '4',
        'max_concurrency' => '6',
        'break_after_frontend' => '5',
        'break_after_adminhtml' => '30',
        'first_lifetime' => '600',
        'bot_first_lifetime' => '60',
        'bot_lifetime' => '7200',
        'disable_locking' => '0',
        'min_lifetime' => '60',
        'max_lifetime' => '2592000'
      )
    ),

```
**Manual testing scenario:**

1. Using Google Chrome, login to the admin area;
2. Open 16 tabs with the orders  page for example
3. Click the left most tab;
4. Right click the right most tab and select "reload"
5. Check the tabs after they have all reloaded;

**Before:** :heavy_multiplication_x: Only ~6 will successfully load and others will have errors

Screenshot from 2020-07-21 13-56-38

Check the var/report folder for the start_session error report relating to the tabs that failed.

Screenshot from 2020-07-21 14-00-31

**After:** :heavy_check_mark:  Browsing pages in the admin area didn't throw an error

**Comment by marvinhinz** [comment]
Will this be included in the 2.4 release? :)

**Comment by fritzmg** [comment]
> Will this be included in the 2.4 release? :)

This is something you can already do yourself. It does not fix the original issue.

**Comment by marvinhinz** [comment]
> > Will this be included in the 2.4 release? :)
> 
> This is something you can already do yourself. It does not fix the original issue.

I know, but it would be nice if newly installed shops dont run into this issue in the first place.

**Comment by ihor-sviziev** [comment]
I just found that this PR was discussed on the public triage meeting in https://www.youtube.com/watch?v=knegmLW94z4&t=1575s 
but it still requires review from dev. side.

The issue appears _not_ only with requests to the pages itself, but also to AJAX requests on the pages you're just opened opened, so sometimes you don't really need to open 6 pages, but just 2-3.

Real use case when this issue reproducing:
For marketing manager this is quite typical situation when you need to review multiple orders, you're opening few orders in a row, and it fails. You have to refresh the pages that failed.

Another use case - on frontend some customers opening few products in a new tab (usually from desktop) people doing that.

About limiting session concurrency - sessions is not the thing for decreasing load on the servers, we should have this limitation on the nginx/phpfpm or even on the WAF level.

**Comment by ihor-sviziev** [comment]
@marvinhinz just an idea - what if we'll implement postponed sending of AJAX calls while tab is not active? As result - we'll send less requests in such cases to the backend and this issue probably will be also much less reproducible. We can use for that https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

**Comment by Nazar65** [comment]
@ihor-sviziev just in case -> https://xumulus.com/magento-2-and-ajax-with-optimistic-session-locking/

**Comment by Nazar65** [comment]
@ihor-sviziev this pr will not resolve the issue, with 32 number 
Screenshot_2020-10-15 https madobe24dev vg

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @marvinhinz,
As we discussed with @Nazar65 - this PR actually masks the issue, instead of fixing it.

Proper solution will be introducing optimistic session locking mechanism, as described here https://github.com/magento/magento2/pull/29140#issuecomment-709153018. That's definitely will be much bigger effort than this PR.

Will you be able to update your PR by introducing optimistic session locking mechanism?

**Comment by ihor-sviziev** [comment]
@marvinhinz I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

Note: @Nazar65 you can take this issue

**Pull request closed without merging**
