### PR TITLE
[32144][To 2.4-develop] fix API product search with price order for default store

### LINKED ISSUE #32144: Magento 2.3.x and 2.4.x API product search with sort by price does not work properly
https://github.com/magento/magento2/blob/53ad434d78cd2d357203fb82e5ea059883f403b8/app/code/Magento/Catalog/Model/ResourceModel/Product/Collection.php#L1740

and

https://github.com/magento/magento2/blob/53ad434d78cd2d357203fb82e5ea059883f403b8/app/code/Magento/Elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php#L81

Order by **price_index.min_price = 0** cause issue on API requests when we have store ID > 0: 
Any product with price = 0 will be sorted in the end of the list. So, when we request products list with API we have all free products in the end of the list. API call for all stores are fine.

Affected versions:
 - Magento CE 2.3.x
 - Magento CE: 2.4.x
 - Magento CE: 2.5.x-dev

**Update**
Issue can be visible on frontend when user applies sorting by price for any of categories that has free and paid products. All free products appears in the end of the list

### PR DESCRIPTION
**Pull request by OxCom**
### Description
There is invalid SQL query that make not possible to use ordering by price in API for default store. Same issue can be reproduced on frontend, when used is triggering sort functionality by price on a list of product for specific category.

```sql
SELECT ...
FROM   ...
ORDER BY field = 0
```

The ```field = 0``` will be interpreted as as TRUE when the price is zero, and as we have no provided order direction then it will be sorted in ascending order by default.

Order by price_index.min_price = 0 cause issue on API requests when we have store ID > 0:
Any product with price = 0 will be sorted in the end of the list. So, when we request products list with API we have all free products in the end of the list. API call for all stores are fine.

### Affected versions:

Magento CE: 2.3.x
Magento CE: 2.4.x
Magento CE: 2.5.x-dev

### Fixed Issues
1. Fixes magento/magento2#32144

### Updateds
- 03.05.2021 - description

### CODE REVIEW

**Comment by mrtuvn** [comment]
@magento run Integration Tests, Database Compare, WebAPI Tests

**Comment by mrtuvn** [comment]
@magento run Unit Tests, Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run WebAPI Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by mrtuvn** [comment]
@magento run WebAPI Tests, Functional Tests B2B

**Comment by Den4ik** [comment]
This PR affect commit https://github.com/magento/magento2/commit/32b92d7f047b8a47ac5b237935b61f16f3316718 
It would be good to know why it was added due to `MC-32430: [Magento Cloud] - Order / Invoice / Sales Order Report Discrepancy`
@magento-engcom-team Could you assist with description of internal ticket?

@OxCom Can you also check https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php#L81 that contain same changes?

**cc:** @gabrieldagama @sidolov @sivaschenko

**Comment by OxCom** [comment]
@Den4ik I can confirm that [SearchResultApplier.php#L81](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php#L81) also affected by issue.
I extended the fix for pull request

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Functional Tests CE

**Comment by gabrieldagama** [comment]
Hi @Den4ik,

Here is the description of the internal issue:

```
ISSUE:

Price sorting doe not work correctly for out of stock configurable products.

STEPS TO REPLICATE:

Set Display Out of Stock Products: YES (Stores > Configuration > Catalog > Inventory)
Set a configurable product status to "Out of Stock" (Catalog > Product > Edit)
For example, edit "Taurus Elements Shell" product as in the attached screenshot out_of_stock_product.png
Set the Quantity = 0 for all simple products of this configurable product
Navigate to PLP: Men > Top > Jackets
Click on sort by price low to high.
ACTUAL RESULTS:
The product sorting is incorrect actual_result.png

EXPECTED RESULTS:

Products should be sorted in the correct order.

NOTES:
Is issue reproducible in the 2.3.4 as well as 2.3-develop
```

**Comment by Den4ik** [comment]
@OxCom could you verify scenario https://github.com/magento/magento2/pull/32795#issuecomment-831914353 ?

**Comment by OxCom** [comment]
@Den4ik yep, I confirm that "out of stock" items are in the end of the list when user sorting by price.

Also I can confirm case when any product with price = 0 (admin -> products -> edit product price and set zero) will be located in the end of the list of products:
1. Change price for any visible product to 0
2. Sort by price ASC

Example we have 3 products with price $1, $2, $3 and 3 with price 0. On frontend and API you will have next order:
ASC: $1, $2, $3, 0, 0 ,0
DESC: $3, $2, $1, 0, 0, 0

Also I can confirm that issue reproducible in magento versions 2.3.x, 2.4.x and I saw issue in code of 2.5.x.

**Comment by Den4ik** [comment]
@OxCom Thanks for check. Could you investigate and fix this issue?

**Comment by OxCom** [comment]
@Den4ik fix already done in this pull request.

Looks like person who did a bug had thought to move all products that are out of stock to the end of the list. It make sense, but should be done in another way.

**Comment by mrtuvn** [comment]
Is this issue related similar with specific case https://github.com/magento/magento2/issues/33022
outstock show first in the list

**Comment by OxCom** [comment]
@mrtuvn I can confirm that issue came from the idea that out of stock items should be moved to the end of the list and looks like developer who did this changed tried to achieve this, but instead of this he introduced another issue.

**Comment by mrtuvn** [comment]
That changed come from internal development. Don known internal process approve that

**Comment by Den4ik** [comment]
In my opinion issue that we rollback by this changes should be fixed in this PR. It's bad that fixes for one issue produce another one issue, but we should not roll back changes and wait when rolled issue will be fixed.
@gabrieldagama what do you think? Should we roll back and open another issue?

**Comment by OxCom** [comment]
Any update on the issue? Should I implement feature for items that are out of stock in this ticket?

**Comment by Den4ik** [comment]
> Any update on the issue? Should I implement feature for items that are out of stock in this ticket?

@OxCom It would be great, because as I commented above we should prevent rolling back issues.

**Comment by Den4ik** [comment]
@OxCom Do you plan to finish this PR?

**Comment by OxCom** [comment]
@Den4ik yes, I'm looking into to find best solution. Also I have to learn how to cover this with tests.

**Comment by mrtuvn** [comment]
Seem internal team already changed some, maybe included your solution at latest commit
CC: @OxCom

**Comment by OxCom** [comment]
@mrtuvn correct, they just did the same as in this pull request.

**Comment by tuna2smc** [comment]
Can we close this
@OxCom have you check latest code updated solve your problem ?

**Comment by OxCom** [comment]
@tuna2smc as I wrote the magento team did same changes that are in my pull request. so, yes my cases are working as expected

**Comment by Den4ik** [comment]
@mrtuvn This PR has 0 changed files and as you mentioned in https://github.com/magento/magento2/pull/32795#issuecomment-883034029 2.4-develop already contain needed changes

**Pull request closed without merging**
