### PR TITLE
Removed CliIndexerReindexActionGroup action group usage for Customer module

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Remove CliIndexerReindexActionGroup action group usage or change value for it from tests to improve execution time for the Customer and GroupedProduct modules.

### CODE REVIEW

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B,Semantic Version Checker

**Comment by sergiy-v** [comment]
Looks like all issues in functional tests are related to 'vimeo video'.
PR is ready to review.

**Comment by ihor-sviziev** [comment]
@sergiy-v could you merge recent changes from 2.4-develop? The vimeo issues were already fixed.

**Comment by sergiy-v** [comment]
> @sergiy-v, your changes look good to me.
> The Vimeo issues were already fixed. Could you merge recent changes from 2.4-develop?

@ihor-sviziev thank you for the hint, I'll update all opened PRs today.
Thank you.

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B,Semantic Version Checker

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8699](https://jira.corp.magento.com/browse/ENGCOM-8699) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by sergiy-v** [comment]
@magento run WebAPI Tests, Unit Tests, Static Tests, Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B, Magento Health Index, Integration Tests, Database Compare

**Comment by ihor-sviziev** [comment]
@sidolov @sivaschenko, should we put here s2 p2 labels similar to https://github.com/magento/magento2/pull/31864?

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Pull request merged**
