### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by Gemorroj**
upd symfony packages
see https://github.com/magento/composer/commit/7fadf1404ea221d8935003e75ad490b31f28bf34#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Gemorroj. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16478) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=16478) before we can accept your contribution.<br/>

**Review by orlangur — APPROVED** [review]

**Review by orlangur — CHANGES_REQUESTED** [review]
@Gemorroj Travis builds must be fixed.

**Comment by Gemorroj** [comment]
As far as I can see, the issues are not related to this update.
The only thing that needs to be updated is `composer.lock`. But probably not me (IMHO `composer.lock` should not be in VCS at all).

**Comment by orlangur** [comment]
@Gemorroj they are caused by this update. It does not really matter what you think about `composer.lock` under VCS, here it is essential.

PR review is only possible after the builds are green in CLA is signed.

**Pull request closed without merging**
