### PR TITLE
Fixed configurable product price indexer issue

### LINKED ISSUE #14443: Final min_price and max_price calculation on configurable product with special price
### Preconditions

1. Magento 2.3 or Magento 2.1
2. Have a configurable product with all associated product prices 288 and add for each associated simple product special price 98. Set a special date from lower than current date.

### Steps to reproduce

1. Reindex catalog_product_price indexer
2. 
3. 

### Expected result

1. Sort by price should work on category page with product list

### Actual result

1. Sort by price doesn't work because it uses negative values from min_price column.
max_price column is broken too (-92 value)
SELECT * FROM `catalog_product_index_price` WHERE `entity_id` = [configurable product ID].

There is a weird line of code in:
vendor/magento/module-configurable-product/Model/ResourceModel/Product/Indexer/Price/Configurable.php,
function _applyConfigurableOption:

```
$select->columns(
            [
                'min_price' => new \Zend_Db_Expr('i.min_price - i.orig_price + io.min_price'),
                'max_price' => new \Zend_Db_Expr('i.max_price - i.orig_price + io.max_price'),
                'tier_price' => 'io.tier_price',
            ]
);
```

If I'm reading this:
final min price = min_price_1 + min_price_2 - normal/original price.
On my example min price = 98 + 98 - 288 = **- 92**

### LINKED ISSUE #15609: Magento 2.2.4 Product sorting list by price on category page wrong when configurable product has special price set by mass action.
### Preconditions

1.  Magento 2.2.4

### Steps to reproduce

1. Add a special price to configurable product using mass action.
2. Re-index price

### Expected result

1. It is expected that catalog category page show products sorted by price correctly, taking account that special price of the configurable product should not make difference to price indexer process

### Actual result

1. Indexer process is using configurable product special price to update `catalog_product_index_price` letting the category page sorting products in the wrong way.
issue_magento

### LINKED ISSUE #24535: Negative prices in layered navigation
### Preconditions (*)

1. 2.3.0

### Steps to reproduce (*)

1. Re-reporting https://github.com/magento/magento2/issues/14443 as this has been closed but is not fixed.
2. Multi store setup, different discounts for different stores.

### Expected result (*)

1. Layered navigation shows correct price ranges

### Actual result (*)

1. Layered navigation shows negative price ranges

```
mysql> select * from catalog_product_index_price where min_price < 0 limit 10;
+-----------+-------------------+------------+--------------+---------+-------------+-----------+-----------+------------+
| entity_id | customer_group_id | website_id | tax_class_id | price   | final_price | min_price | max_price | tier_price |
+-----------+-------------------+------------+--------------+---------+-------------+-----------+-----------+------------+
|     44489 |                 2 |          3 |            2 | 69.0000 |     30.5000 |   -8.0000 |   -8.0000 |    30.5000 |
|     44489 |                 6 |          3 |            2 | 69.0000 |     30.7200 |   -7.5600 |   -7.5600 |    30.7200 |
|     34227 |                 2 |          1 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
|     34227 |                 2 |          3 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
|     40003 |                 2 |          1 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
|     40003 |                 2 |          3 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
|     40005 |                 2 |          1 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
|     40005 |                 2 |          3 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
|     40011 |                 2 |          1 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
|     40011 |                 2 |          3 |            2 | 59.0000 |     26.0000 |   -7.0000 |   -7.0000 |    26.0000 |
+-----------+-------------------+------------+--------------+---------+-------------+-----------+-----------+------------+
10 rows in set (0.01 sec)
```

### PR DESCRIPTION
**Pull request by ananth-iyer**
### Description (*)

Configurable products price indexer save min_price in negative number i.e. -0.010000.

### Related Issues (if relevant)

1. Fixes #24535
2. Fixes #15609
3. Fixes #14443

### Manual testing scenarios (*)

1. Migrate Magento 1.9.4.2 > Magento 2.3.4
2. After the migration process - run full re-indexer
3. Then check the `catalog_product_index_price` as per the screenshot attached the min_price is incorrect.
Selection_007

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
`Risk: high` since the configurable indexation process os affected

The same as for https://github.com/magento/magento2/pull/24962

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @ananth-iyer,
Seems like your solution breaks some functionality. Could you review failing test results and adjust your solution?

**Comment by ihor-sviziev** [comment]
@ananth-iyer will you be able to update your PR?

**Comment by ananth-iyer** [comment]
> @ananth-iyer will you be able to update your PR?

Yes, I will sync the PR with `magento:2.4-develop` branch

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @ananth-iyer,
Unfortunately tests are still failing after your last changes. Could you fix them?

**Comment by ananth-iyer** [comment]
@ihor-sviziev Sure, I will check the issues reported in the tests and fix accordingly soon.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by luci0130** [comment]
Configurable products that have the "NULL" value for the price attribute in the catalog_product_entity_decimal table, the new rule will generate index with price, special_price, min_price, max_price = 0.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Hello @ananth-iyer .
Could you please let me that you working on it?
Thank you.

**Comment by ihor-sviziev** [comment]
@engcom-Hotel I believe you can continue working on this PR

**Comment by sidolov** [comment]
Changing priority to P2 since a lot of issues fixed by proposed changes. @engcom-Hotel please, proceed with stabilization.

**Comment by ananth-iyer** [comment]
@engcom-Hotel Please continue work on this PR

**Comment by engcom-Hotel** [comment]
Hello @ananth-iyer.
Will check it soon.
Thank you.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Tests failures looks not related
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8481](https://jira.corp.magento.com/browse/ENGCOM-8481) has been created to process this Pull Request

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE, Integration Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Unit Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by ihor-sviziev** [comment]
@engcom-Hotel seems like something is really broken in ee and b2b. Could you check that?

**Comment by engcom-Hotel** [comment]
Sure, will check it soon.

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved! 
Finally, tests are passing

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8481](https://jira.corp.magento.com/browse/ENGCOM-8481) has been created to process this Pull Request

**Review by engcom-Delta — CHANGES_REQUESTED** [review]
@ananth-iyer I tested PR according [scenario](https://github.com/magento/magento2/issues/24953) from related issue that should be fixed by these changes, but issue is still reproducible
**Manual testing scenario:**

- Create configurable product with three childs
image

- Set `Price=10` on configurable product from mass action grid
- Run `cron:run`
- See the price from attributes appeared on product grid
Screenshot from 2020-12-11 14-18-01

- See the price from attributes in columns `price` and `final_price` in the table `catalog_product_index_price`
Screenshot from 2020-12-11 14-17-39

- Then save configurable product from admin edit page
- See `null` value saved for price attribute in `catalog_product_entity_decimal`
Screenshot from 2020-12-11 14-19-09

- Run `cron:run`
- Check columns `price` and `final_price` in the table `catalog_product_index_price`

**Result:**
:x: See `0` saved in columns `price` and `final_price` for edited configurable product
Screenshot from 2020-12-11 14-19-41

:x: Still possible to save `price` and for configurable product in `catalog_product_entity_decimal` table


Could you take a look?

**Comment by ananth-iyer** [comment]
@engcom-Delta **Set Price=10 on configurable product from mass action grid**
**x See 0 saved in columns price and final_price for edited configurable product**

In Magento 2, as per my knowledge the price field is disabled on configurable product edit pages. So this issue is related to mass action functionality.

This PR is related to indexing issues that take lot of time and price sorting issues on product listing page after migrating from Magento 1.

So I think we have to skip price update if the product type in configurable for the mass action and we need to create a new issue for it.

**x Still possible to save price and for configurable product in catalog_product_entity_decimal table**
I think this code is copied from Magento 1 as is and causing repetitive issues in Magento 2.

**Comment by ihor-sviziev** [comment]
@engcom-Delta do we have the listed issues on 2.4-develop branch? If no - that might be a bit different issues

**Comment by ananth-iyer** [comment]
@engcom-Delta Do you have information how to reproduce issue with negative number in min_price without migration magento from 1.9.4.2 to 2.4.x?
No

We should remove the #24953 from this PR because it is related to Mass action page and product mass action functionality needs to get fixed. Indexing issue is fixed in this PR. While submitting this fix I never thought of mass action issue exists or not.

**Comment by engcom-Hotel** [comment]
Hello @ananth-iyer,
The issue which is not covered via your fix has been removed from the description.
Unfortunately, we can't test the migration process from m1 to m2 and we need to perform the test only on m2.
Maybe you have some ideas about how to do it?

**Comment by ananth-iyer** [comment]
@engcom-Hotel I have migrated the default M1 to M2 and found no issue there. But this issue occurs with the existing M1 project, here the admin adds price in configurable products by mistake.

**Comment by ihor-sviziev** [comment]
Hi @ananth-iyer,
If you could reproduce this issue without migration from m1 to m2 - please provide steps to reproduce. 
Otherwise, we won't fix potential issues caused by the issue during the migration or maybe some old issue in Magento.

If there no steps to reproduce this issue w/o migration - I believe we can't accept such PR. What do you think about it?

**Comment by ihor-sviziev** [comment]
@ananth-iyer I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
