### PR TITLE
Magento Customer optional prefix/suffix displays random zeros

### LINKED ISSUE #32177: M2.4.2 Customer Name Prefixes Showing as numbers not Mr., Mrs., Ms. etc
After upgrading Magento from 2.4.1 to 2.4.2, customer orders are coming through with numbers instead of Name Prefixes such as Mr., Mrs. etc. No settings have been changed since the upgrade.

### Preconditions (*)

1. Magento CE 2.4.2
2. Magento 2.4-develop

### Steps to reproduce (*)

1. Enable customer prefix
image
2. Go to Sales->Orders
3. Click Create New Order
4. Click Create New Customer
5. Fill required fields and choose **Name Prefix** from dropdown
6. Click Submit Order

### Expected result (*)

1. The name will show in the order summary page as [Name Prefix] [First Name] [Surname]

### Actual result (*)

1. The name shows as [Number] [First Name] [Surname]. This also replicated in the transactional emails.

image
image

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
The issue is caused by Magento using the POST value as a prefix/suffix. As the keys are numbers, not the actual numbers, you end up with random numbers used as suffix / prefix.

image

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32177

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hostep** [comment]
I have the feeling this might fix: https://github.com/magento/magento2/issues/32177, could that be?

**Comment by lbajsarowicz** [comment]
Hey @hostep - Yes, it is the fix for the mentioned issue.

**Comment by likearocket** [comment]
So to confirm, in file vendor/magento/module-customer/Model/Options.php

Changing line 110 fixes the prefix issue I reported 18 months ago?

**Comment by lbajsarowicz** [comment]
> Changing line 110 fixes the prefix issue I reported 18 months ago?

You can just apply Composer Patch: https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/36003.diff

More info: https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/patches/apply.html

You are welcome.

**Comment by hostep** [comment]
Looks like Adobe decided to approve another fix: https://github.com/magento/magento2/pull/35060
So this one is probably no longer needed?

**Pull request closed without merging**
