### PR TITLE
magento/magento2#12075: Customer Email with diacritics isn't allowed

### LINKED ISSUE #12075: Customer Email with diacritics isn't allowed
Magento2 doesn't allow E-Mails with diacritics in CURL Requests.
According to [wikipedia](https://en.wikipedia.org/wiki/Email_address#Internationalization) this should be allowed, but Magento is restricting it. 

Is there a Fix or Workaround or something?

### Preconditions
1. Magento Version 2.1.8

### Steps to reproduce
1. get email address with diacritics (pepé@emailtest.com)
2. create json data object with email 
`$data = [
                    'customer' =>
                    [
                        'email' => pepé@emailtest.com
                     ]
]`
3. create user using curl via /index.php/rest/V1/customers

### Expected result
1. User should be created with correct email address

### Actual result
1.` {"message":"\"Email\" ist keine g\u00fcltige E-Mail-Adresse."` (roughly translated: Email isn't a valid E-Mail-Address)

### Additional Notes
Reproduced it via Swagger with using the following query  /swagger#/customerAccountManagementV1/customerAccountManagementV1CreateAccountPost
swagger_create customer
The response is : 
```
{
  "message": "\"Email\" is not a valid email address."
}
```
But this is also reproducible if try to create a customer from Magento Admin
email_from admin

### PR DESCRIPTION
**Pull request by Alexander-Khohklov**
- fixed customer email with diacritics validation when create from admin panel or by curl request

### Description (*)

Added converting of text attribute string from UTF-8 to ASCII if string with diacritics symbols.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#12075

### Manual testing scenarios (*)
1. Go to the admin panel ->  Menu Customers -> Add a new customer -> add email address with diacritics like ĝôńâŕýçðæñ@gmail.com -> click save action.
2. Create user using curl via /index.php/rest/V1/customers with email ĝôńâŕýçðæñ@gmail.com.
3. Or Use steps from https://github.com/magento/magento2/issues/12075#issue-271795385

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Alexander-Khohklov** [comment]
@magento run all tests

**Comment by Alexander-Khohklov** [comment]
@magento run all tests

**Comment by Alexander-Khohklov** [comment]
@magento run all tests

**Comment by sila7dyxa** [comment]
@magento run Functional Tests B2B

**Comment by Alexander-Khohklov** [comment]
@magento run all tests

**Comment by Alexander-Khohklov** [comment]
https://github.com/magento run all tests

**Comment by Alexander-Khohklov** [comment]
@magento run Functional Tests B2B, Integration Tests

**Comment by Alexander-Khohklov** [comment]
@magento run Functional Tests B2B, Integration Tests

**Comment by Alexander-Khohklov** [comment]
@magento run Integration Tests

**Comment by Alexander-Khohklov** [comment]
@magento run Integration Tests

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by Alexander-Khohklov** [comment]
@magento run all tests

**Comment by sila7dyxa** [comment]
@magento run Unit Tests

**Comment by Alexander-Khohklov** [comment]
@magento run Functional Tests B2B

**Comment by Alexander-Khohklov** [comment]
@magento run Unit Tests

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B

**Comment by Alexander-Khohklov** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Alfa** [comment]
@magento run all tests

**Comment by Alexander-Khohklov** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B, Static Tests

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests CE

**Comment by mischabraam** [comment]
This change seems to be not backwards compatible with existing customer data coming from an earlier Magento version. 

This change validates input with transliteration. However, this is done on every value. Also on values which are not transliterable (is that a word?). Anyway... if we use the Magento API to change an existing customer per following REST API, this translit breaks on the existing `rp_token`.

```
PUT https://www.magento.com/rest/all/V1/customers/:id
```

With body to update the customer including the password like per example.

```
{
  "customer": {
    "email": "onno@example.com",
    "Gender": 1,
    "Lastname": "Testing",
    "Store_id": 1,
    "Firstname": "Önno",
    "addresses": [
      {
        "street": [
          "Somewhere street"
        ],
        "Lastname": "Testing",
        "Postcode": "1231 EC",
        "Telephone": "0",
        "firstname": "Önno",
        "Middlename": " ",
        "country_id": "NL",
        "Default_billing": true,
        "Default_shipping": true,
        "custom_attributes": [
          {
            "value": "236",
            "attribute_code": "house_number"
          },
          {
            "value": "D",
            "attribute_code": "house_number_addition"
          }
        ],
        "city": "TEST CITY"
      }
    ],
    "Middlename": " ",
    "Website_id": 1,
    "custom_attributes": [
      {
        "value": null,
        "attribute_code": "sales_representative"
      },
      {
        "value": "5682",
        "attribute_code": "customer_group"
      },
    ],
    "id": 12345
  },
  "password": "passwordChangeLater@11"
}
```

Error in logging.

```
[2023-03-30T13:16:19.193625+00:00] report.CRITICAL: Exception: Notice: iconv(): Detected an incomplete multibyte character in input string in /var/domains/magento.shop/magento2_staging/releases/1680163528/vendor/magento/module-ea
v/Model/Attribute/Data/Text.php on line 190 in /var/domains/√.shop/magento2_staging/releases/1680163528/vendor/magento/framework/App/ErrorHandler.php:62
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(8, 'iconv(): Detect...', '/var/domains/...', 190)
#1 /var/domains/magento.shop/magento2_staging/releases/1680163528/vendor/magento/module-eav/Model/Attribute/Data/Text.php(190): iconv('UTF-8', 'ASCII//TRANSLIT...', 'b\xA85\xBA:\xA9s\x01p\x83Pn\xA9\xE3\xEF...')
#2 /var/domains/magento.shop/magento2_staging/releases/1680163528/vendor/magento/module-eav/Model/Attribute/Data/Text.php(83): Magento\Eav\Model\Attribute\Data\Text->encodeDiacritics('b\xA85\xBA:\xA9s\x01p\x83Pn\xA9\xE3\xEF...')
```

Screenshot_2023-03-31_at_11_31_25

**Pull request merged**
