### PR TITLE
[Fixed] Category Update without "name" cannot be saved in scope "all" with REST API

### PR DESCRIPTION
**Pull request by niravkrish**
### Description (*)
- Category update API threw error for required field "name".

### Fixed Issues (if relevant)

1. magento/magento2#22309: Category Update without "name" cannot be saved in scope "all" with REST API

### Manual testing scenarios (*)

1. Manual Testing

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by orlangur — CHANGES_REQUESTED** [review]
@niravkrish why it works on scope "default" without such change and does not work on "all" scope?

**Comment by niravkrish** [comment]
> @niravkrish why it works on scope "default" without such change and does not work on "all" scope?

Hello @orlangur ,
In this solution the key name is not sent.
If not set in data Body required to update.
So this solution is working fine with all and default as well.

**Comment by orlangur** [comment]
@niravkrish why "default" scope update works _without_ such change?

We cannot add `null` as allowed value as proper category name cannot be null.

**Comment by niravkrish** [comment]
> @niravkrish why "default" scope update works _without_ such change?
> 
> We cannot add `null` as allowed value as proper category name cannot be null.

This can not allow to add or set null value to Category name.
It is used to get Category Name as a string or if not then null.

This is not pass null on save the data to database or anywhere.

If we are not passing the name from request body the name key is set with null before and after applying this solution the key is set when there is name key is available with value.

please let me know for further changes.

Thanks 
Nirav Patel

**Review by orlangur — APPROVED** [review]
@niravkrish ow, we allow `null` value for any other getter here.

Still don't get why the bug is in "all" scope only but fix seems reasonable.

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4771](https://jira.corp.magento.com/browse/ENGCOM-4771) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed 

**Before:**

before

**After:**

after

**Pull request merged**
