### PR TITLE
Act better on existing input focus instead of removing it

### LINKED ISSUE #13988: Mini search field looses focus after its JavaScript is initialized
### Preconditions

1. Any Magento 2.x.x installation, e.g. http://magento2-demo.nexcess.net/

### Steps to reproduce

1. Open Magento 2 shop.
2. Focus mini search field before JavaScript manages to load and optionally start writing some query there.

### Expected result

1. The focus is maintained when the component is initialized.

### Actual result

1. After mini search component's JavaScript loads and initializes, search input loses focus and user has to focus it again.

As far as I understand this part of the code is responsible for above behavior: https://github.com/magento/magento2/blob/36bfa583f12ccf79c754920d6b6288e67fcc9961/app/code/Magento/Search/view/frontend/web/form-mini.js#L101
I suspect it was added to correctly toggle active classes attached to `focus` event by forcing the user to reselect input field. I'm creating PR which will make code check current active element and triggers `setActiveState` method if it is our component's input.

### PR DESCRIPTION
**Pull request by krzksz**
The focus of the input field is maintained, proper classes are added and autocomplete fires once the component is initialized. Fixes #13988.

### Description

As already mentioned in issue referenced above this change proposes better approach when the user is already focused on the search input by detecting it and triggering appropriate methods.

### Fixed Issues (if relevant)

1. magento/magento2#13988 Mini search field looses focus after its JavaScript is initialized

### Manual testing scenarios

1. Load Magento 2 shop.
2. Focus on mini search form field.
3. Check that input no longer loses focus once its JavaScript is initialized.
4. Check that proper active classes are applied when the user is focused on the search field and JavaScript gets initialized.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=13989) <br/>All committers have signed the CLA.

**Review by okorshenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, thank you for the review.
[ENGCOM-889](https://jira.corp.magento.com/browse/ENGCOM-889) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@krzksz thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
@krzksz thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request merged**
