### PR TITLE
ESLint errors fix

### PR DESCRIPTION
**Pull request by Igloczek**
It's part of #9089.

This PR contains only safe changes generated using `--fix` flag for ESLint.
I manually excluded all of 3rd party code from `lib/web`, overwriting them after fixing process. Unfortunatly 3rd party code is mixed with Magento code within `lib/web`, so there isn't a quick way to use eslint against only custom code, without blacklisting 3rd party manually.

### Manual testing scenarios
1. Install ESLint globally (`yarn global add eslint` / `npm install -g eslint`)
2. `eslint -c dev/tests/static/testsuite/Magento/Test/Js/_files/eslint/.eslintrc --fix lib/**/*.js`
3. `eslint -c dev/tests/static/testsuite/Magento/Test/Js/_files/eslint/.eslintrc --fix app/**/*.js`

### CODE REVIEW

**Review by omiroshnichenko — COMMENTED** [review]
We don`t have practice to modify 3rd party libraries, for static test we have [blacklist](https://github.com/magento/magento2/blob/develop/dev/tests/static/testsuite/Magento/Test/Js/_files/blacklist/magento.txt) that exludes these files. Most of your fixes is in libraries. Can you please revert this changes?

**Comment by Igloczek** [comment]
Looks like I have to redo everything, but I have some concerns about your current blacklist and whitelist content. IMO it doesn't cover all of your custom code, that's why tests currently are passing.
First lines of blacklist cleairly contains your custom modules, not 3rd party libs:
```
app/code/Magento/Authorizenet/view/adminhtml/web/js/direct-post.js
app/code/Magento/Catalog/view/adminhtml/web/catalog/product/composite/configure.js
app/code/Magento/ConfigurableProduct/view/adminhtml/web/js/options/price-type-handler.js
app/code/Magento/Rule/view/adminhtml/web/rules.js
app/code/Magento/Sales/view/adminhtml/web/order/create/giftmessage.js
app/code/Magento/Sales/view/adminhtml/web/order/create/scripts.js
app/code/Magento/Shipping/view/adminhtml/web/order/packaging.js
```
Varien code also is your custom solution, but is blacklisted:
```
lib/web/mage/adminhtml/tools.js
lib/web/mage/adminhtml/varienLoader.js
```

Also when we take a look on whitelist, few dirs are missing, i.e. we have `lib/web/mage/**/*.js`, but the custom code can be found in`lib/web` too:
- `lib/web/css/docs/source/js/dropdown.js`
- `lib/web/extjs/defaults.js`
- `lib/web/less/config.less.js`
- `lib/web/fotorama` (it's 3rd party, but customized 🙄 )
- `lib/web/magnifier`
- `lib/web/varien`

**Comment by omiroshnichenko** [comment]
@Igloczek About blacklisted files(not 3rd party), we already have internal ticket to refactor these files, because most of them didn`t support strict mode.

About files that you change, please, exclude these files:
- app/code/Magento/Customer/view/frontend/web/js/zxcvbn.js
- app/code/Magento/Swagger/view/frontend/web/swagger-ui/js/lib/backbone-min.js
- app/code/Magento/Swagger/view/frontend/web/swagger-ui/js/lib/handlebars-2.0.0.js
- app/code/Magento/Swagger/view/frontend/web/swagger-ui/js/lib/highlight.7.3.pack.js
- app/code/Magento/Swagger/view/frontend/web/swagger-ui/js/lib/jquery-1.8.0.min.js
- app/code/Magento/Swagger/view/frontend/web/swagger-ui/js/lib/jquery.ba-bbq.min.js
- app/code/Magento/Swagger/view/frontend/web/swagger-ui/js/lib/jquery.slideto.min.js
- app/code/Magento/Swagger/view/frontend/web/swagger-ui/js/lib/jquery.wiggle.min.js
- app/code/Magento/Swagger/view/frontend/web/swagger-ui/js/lib/marked.js
- app/code/Magento/Swagger/view/frontend/web/swagger-ui/js/lib/swagger-oauth.js
- app/code/Magento/Swagger/view/frontend/web/swagger-ui/js/lib/underscore-min.js
- lib/web/extjs/ext-tree-checkbox.js
- lib/web/es6-collections.js
- lib/web/fotorama/fotorama.js
- lib/web/fotorama/fotorama.min.js
- lib/web/jquery/colorpicker/js/colorpicker.js
- lib/web/jquery/editableMultiselect/js/jquery.editable.js
- lib/web/jquery/editableMultiselect/js/jquery.multiselect.js
- lib/web/jquery/fileUploader/canvas-to-blob.js
- lib/web/jquery/fileUploader/cors/jquery.postmessage-transport.js
- lib/web/jquery/fileUploader/cors/jquery.xdr-transport.js
- lib/web/jquery/fileUploader/jquery.fileupload-fp.js
- lib/web/jquery/fileUploader/jquery.fileupload-ui.js
- lib/web/jquery/fileUploader/jquery.fileupload.js
- lib/web/jquery/fileUploader/jquery.iframe-transport.js
- lib/web/jquery/fileUploader/load-image.js
- lib/web/jquery/fileUploader/main.js
- lib/web/jquery/fileUploader/vendor/jquery.ui.widget.js
- lib/web/jquery/jquery-migrate.js
- lib/web/jquery/jquery-ui-1.9.2.js
- lib/web/jquery/jquery-ui-timepicker-addon.js
- lib/web/jquery/jquery-ui.js
- lib/web/jquery/jquery.ba-hashchange.min.js
- lib/web/jquery/jquery.cookie.js
- lib/web/jquery/jquery.details.js
- lib/web/jquery/jquery.hoverIntent.js
- lib/web/jquery/jquery.metadata.js
- lib/web/jquery/jquery.min.js
- lib/web/jquery/jquery.mobile.custom.js
- lib/web/jquery/jquery.storageapi.min.js
- lib/web/jquery/jquery.tabs.js
- lib/web/jquery/jquery.validate.js
- lib/web/jquery/jstree/jquery.jstree.js
- lib/web/knockoutjs/knockout-es5.js
- lib/web/knockoutjs/knockout-fast-foreach.js
- lib/web/knockoutjs/knockout-repeat.js
- lib/web/knockoutjs/knockout.js

Most of them not under Magento license.
Thanks.

**Comment by Igloczek** [comment]
@omiroshnichenko I had to redo everything. I updated blacklist and whitelists to cover more files and clearly mark why some of them are blacklisted, b/c need serious refactoring.

Also instead of blacklisting whole files, I added some ESLint and JSCS ignores inside files.

BTW. [JSCS has merged with ESLint](https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2#.x0o1xqkk9), are you open to updates in this area?

**Comment by omiroshnichenko** [comment]
@Igloczek Looks good. About linters merging, I made small investigation about that and I think we can make update in nearest future.

**Review by omiroshnichenko — APPROVED** [review]

**Comment by magento-team** [comment]
@Igloczek Thank you for the contribution

**Pull request merged**
