### PR TITLE
[MFTF] add new AdminOpenAdminThreeDSecurePageActionGroup

### LINKED ISSUE #29845: [Issue] [MFTF] add new AdminOpenAdminThreeDSecurePageActionGroup
This issue is automatically created based on existing pull request: magento/magento2#29830: [MFTF] add new AdminOpenAdminThreeDSecurePageActionGroup

---------
This PR add `AdminOpenAdminThreeDSecurePageActionGroup` we will able to use it in future for navigation to `AdminThreeDSecurePage`

### PR DESCRIPTION
**Pull request by Usik2203**
This PR add `AdminOpenAdminThreeDSecurePageActionGroup` we will able to use it in future for navigation to `AdminThreeDSecurePage`

### Resolved issues:
1. [x] resolves magento/magento2#29845: [MFTF] add new AdminOpenAdminThreeDSecurePageActionGroup

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by lbajsarowicz** [comment]
@Usik2203 If you add at least one test that uses it, I can add extra points for you for Test Coverage.

**Comment by sidolov** [comment]
@magento create issue

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Review by lbajsarowicz — APPROVED** [review]
✔️  Thank you for your contribution

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-8115](https://jira.corp.magento.com/browse/ENGCOM-8115) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Pull request merged**
