### PR TITLE
Fixed : Additional addresses DataTable Pagination count displaying wrong

### PR DESCRIPTION
**Pull request by Dharmeshvaja91**
### Description (*)

My Account > My addresses > additional address DataTable Pagination count displaying wrong.

### Fixed Issues (if relevant)

1. magento/magento2#21396: Additional addresses DataTable Pagination count displaying wrong

### Manual testing scenarios (*)

1. Go to My account >> Address book
2. Add more than 2 additional address.
3. Select different Shipping and Billing Address. 
4. Review Additional Address Data Table pagination count.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Dharmeshvaja91. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
Hi @Dharmeshvaja91. Please, consider fixing failing unit tests

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-21399.instances.magento-community.engineering).
Admin access: [https://pr-21399.instances.magento-community.engineering/admin](https://pr-21399.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4523](https://jira.corp.magento.com/browse/ENGCOM-4523) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
✔️ QA passed

**Pull request merged**
