### PR TITLE
[MFTF] Create StorefrontClickRefundTabCustomerOrderViewActionGroup

### LINKED ISSUE #30032: [Issue] [MFTF] Create StorefrontClickRefundTabCustomerOrderViewActionGroup
This issue is automatically created based on existing pull request: magento/magento2#30030: [MFTF] Create StorefrontClickRefundTabCustomerOrderViewActionGroup

---------
This PR add new `StorefrontClickRefundTabCustomerOrderViewActionGroup`

### PR DESCRIPTION
**Pull request by Usik2203**
This PR add new `StorefrontClickRefundTabCustomerOrderViewActionGroup` 

### Resolved issues:
1. [x] resolves magento/magento2#30032: [MFTF] Create StorefrontClickRefundTabCustomerOrderViewActionGroup

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8203](https://jira.corp.magento.com/browse/ENGCOM-8203) has been created to process this Pull Request

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8203](https://jira.corp.magento.com/browse/ENGCOM-8203) has been created to process this Pull Request

**Comment by sidolov** [comment]
@magento import to magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
Pull request successfully imported into `magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-30030`.

**Comment by magento-engcom-team** [comment]
Pull request successfully imported into `magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-30030`.

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Pull request merged**
