### PR TITLE
Static Content Deploy - Get rid of in_array(array_keys($array))

### PR DESCRIPTION
**Pull request by andrey-legayev**
### Description (*)
Performance fix - Replace in_array(array_keys($array)) by isset($array)

### Fixed Issues (if relevant)
None

### Manual testing scenarios (*)
None

### Questions or comments
I understand that adding public methods isn't great, but doing in_array(array_keys($array)) isn't cool from performance point of view.
If it's absolutely not possible to add it to 2.3 then please take it to 2.4.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — APPROVED** [review]
Hi @andrey-legayev. Thanks for collaboration. It's not API class, so we can add new public method here, this is ok. 

Can you please che

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6035](https://jira.corp.magento.com/browse/ENGCOM-6035) has been created to process this Pull Request

**Comment by andrey-legayev** [comment]
@VladimirZaets you didn't finish sentence: Can you please che...

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
