### PR TITLE
Remove duplicated US-AE regions

### LINKED ISSUE #30131: [Issue] Remove duplicated US-AE regions
This issue is automatically created based on existing pull request: magento/magento2#30127: Remove duplicated US-AE regions

---------
### Description

[According to USPS](https://faq.usps.com/s/article/How-Do-I-Address-Military-Mail), only `AA`, `AE`, and `AP` regions might be used to address Armed Forces deployments outside the US.

### Manual testing scenarios (*)

1. Create an address and `Armed Forces Canada` as region;
2. After the address is saved, it shows as `Armed Forces Africa` on the address view.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kassner**
### Description

[According to USPS](https://faq.usps.com/s/article/How-Do-I-Address-Military-Mail), only `AA`, `AE`, and `AP` regions might be used to address Armed Forces deployments outside the US.

### Manual testing scenarios (*)

1. Create an address and `Armed Forces Canada` as region;
2. After the address is saved, it shows as `Armed Forces Africa` on the address view.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30131: Remove duplicated US-AE regions

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Comment by BarnyShergold** [comment]
@magento run all tests

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
There are a lot of tests failing due to this change - these need to be addressed before the review can be passed.

**Comment by kassner** [comment]
Seems like most of the issues are related to `region_id` shifting, given the items were not created. :shrug:

**Comment by engcom-Golf** [comment]
Hi @kassner, could you please fix test failures caused by your changes? Thank you.

**Comment by sidolov** [comment]
@kassner  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
