### PR TITLE
The best practices for SEO meta sequence.

### PR DESCRIPTION
**Pull request by vaseemishak**
### Description (*)
The best practices for SEO meta sequence is the title and then description.

### Manual testing scenarios (*)
Render any page meta tag title should come before meta description.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23425) <br/>All committers have signed the CLA.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5363](https://jira.corp.magento.com/browse/ENGCOM-5363) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@vaseemishak thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
