### PR TITLE
Set visibility for product's option according to current website

### LINKED ISSUE #28291: Configurable shows simple products which are no longer assigned to the website
### Preconditions (*)
1. Magento 2.4-develop testinstance

### Steps to reproduce (*)

1. Create additional website, store, storeview "other" in backend
2. Create Configurable with Options, assign to both websites

i-28291-2-4-develop instances magento-community engineering_admin_0154_catalog_product_new_set_4_type_configurable_ (1)

3.  Set Quantity and in stock for each option in backend
4. Check that all 3 options are there in the frontend as expected

image

5. Disable option 1 in the "main website"

image

6. Flush caches

### Expected result (*)

1. The option 1 should disappear in the Frontend

### Actual result (*)
1. Option 1 is still there

image

### Remarks

I do not know how to reindex the test instance, so I am not sure if it is a indexer problem

### Additional information 
 >  I do not know how to reindex the test instance, so I am not sure if it is a indexer problem

Tested on local env. Was done full reindex and flush cache = option 1 still available on website 1

### PR DESCRIPTION
**Pull request by ProkopovVitaliy**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#28291. Configurable shows simple products which are no longer assigned to the website

### Manual testing scenarios (*)

1. Create additional website, store, storeview "other" in backend
2. Create Configurable with Options, assign to both websites
3. Set Quantity and in stock for each option in backend
4. Check that all 3 options are there in the frontend as expected
image
5. Disable option 1 in the "main website"
6. Flush caches

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
I will cover it by MFTF test.

**Comment by dmytro-ch** [comment]
@magento run all tests

**Comment by ProkopovVitaliy** [comment]
@magento run all tests

**Comment by ProkopovVitaliy** [comment]
@magento run all tests

**Comment by ProkopovVitaliy** [comment]
@magento run all tests

**Comment by ProkopovVitaliy** [comment]
@magento run all tests

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @ProkopovVitaliy. Thanks for collaboration. 
This is P2/S1 scenario, and it must be covered by mftf (functional) tests.
@kate-kyzyma Hi, due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) we can't merge it without mftf coverage. If you can please cover it now. You can create separate PR with coverage and link it to this PR

**Comment by kate-kyzyma** [comment]
Hi @VladimirZaets
Thank you for suggestions. I will handle it soon.

**Comment by kate-kyzyma** [comment]
Hello @VladimirZaets @dmytro-ch 
I have covered changes from this PR with MFTF test.
Please, check my PR https://github.com/magento/magento2/pull/28545

Thanks.

**Comment by ProkopovVitaliy** [comment]
@magento run all tests

**Comment by ProkopovVitaliy** [comment]
@magento run Functional Tests EE

**Comment by ProkopovVitaliy** [comment]
@magetno run Functional Tests B2B

**Comment by ProkopovVitaliy** [comment]
@magento run Functional Tests B2B

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7672](https://jira.corp.magento.com/browse/ENGCOM-7672) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Create an additional website, store, store view  in the backend (_Second Website_ - _Second Store_ - _Second website storeview_ for ex.);
2. Create Configurable with Options, assign to both websites;
Screenshot from 2020-06-12 12-42-46

3. Set Quantity and in stock for each option in backend and save product;
4. Go to Storefront and open configurable product page;
5. Check that all 3 options are there in the frontend as expected
image
**Actual Result:** :heavy_check_mark: all 3 options are shown

Screenshot from 2020-06-12 12-47-17

6. Disable the option "**red**" for the "Main website" for ex.;
7. Flush caches;
8. Go to Storefront and open configurable product page again;

**Before:** :heavy_multiplication_x: Option "**red**" is still there

screenshot_55

**After:** :heavy_check_mark: The option "**red**" disappeared in the Frontend

screenshot_54

Checked also with Visual and Text swatch attributes.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7672](https://jira.corp.magento.com/browse/ENGCOM-7672) has been created to process this Pull Request

**Comment by dmytro-ch** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by ProkopovVitaliy** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by ProkopovVitaliy** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by engcom-Charlie — CHANGES_REQUESTED** [review]
Hi @ProkopovVitaliy, please fix falling functional tests.

**Comment by ProkopovVitaliy** [comment]
@magento run Functional Tests CE

**Comment by ProkopovVitaliy** [comment]
@magento run Functional Tests CE

**Comment by ProkopovVitaliy** [comment]
@magento run all tests

**Comment by ProkopovVitaliy** [comment]
@magento run Functional Tests B2B

**Comment by dmytro-ch** [comment]
Hello @ProkopovVitaliy, unfortunately, I have to close this PR due to inactivity.
Please reopen and update if you wish to continue.
Thank you!

**Pull request closed without merging**
