### PR TITLE
[Fixed Radio alignment issue]

### PR DESCRIPTION
**Pull request by hitesh-wagento**
### Related Pull Requests
https://github.com/magento/partners-magento2b2b/pull/41

### Description (*)
Fixed Radio alignment issue

### Fixed Issues (if relevant)

1. magento/magento2#25962: Radio alignment issue

### Manual testing scenarios (*)

1. Add any product in Cart.
2. Go to Checkout Page.

### Expected result

1. Radio should be aligned.
expected

### Actual result

1. Radio little bit up.
actual

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by miguelbalparda** [comment]
Hi @hitesh-wagento! Any chance you can check the failing tests? Looks like something you should be able to fix. Thanks!

**Comment by hitesh-wagento** [comment]
Hi @miguelbalparda,

I can see **Static Tests**  is failed but don't know how to resolve it can you please suggest me.

Thanks

**Review by krzksz — CHANGES_REQUESTED** [review]
Hey @hitesh-wagento, test sais that `input[type="radio"] {` should use single apostrophes instead.

**Comment by hitesh-wagento** [comment]
Hi @miguelbalparda,

I have changed as per suggestion

Thanks

**Review by krzksz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-6480](https://jira.corp.magento.com/browse/ENGCOM-6480) has been created to process this Pull Request

**Comment by engcom-Charlie** [comment]
:heavy_check_mark: QA Passed

**Comment by VladimirZaets** [comment]
Please fix the b2b tests.

**Comment by hitesh-wagento** [comment]
> Please fix the b2b tests.

Hi @VladimirZaets

I can't see error like b2b tests can you please suggest me how can I found and fix it ?

Thanks

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by krzksz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-6480](https://jira.corp.magento.com/browse/ENGCOM-6480) has been created to process this Pull Request

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by engcom-Golf** [comment]
@magento run all tests

**Review by ptylek — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-6480](https://jira.corp.magento.com/browse/ENGCOM-6480) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Comment by hitesh-wagento** [comment]
#MM20IN

**Pull request merged**
