### PR TITLE
Item resolvers should be optional

### LINKED ISSUE #30860: [Issue] Item resolvers should be optional
This issue is automatically created based on existing pull request: magento/magento2#30823: Item resolvers should be optional

---------
Item resolvers should be optional. If we remove configurable and grouped product, checkout is broken because this argument is mandatory. Only the grouper and configurable product add item resolver.

### Preconditions (*)

1. Customer created
2. Simple Product created

### Steps to reproduce (*)

1. Execute:
```
bin/magento module:disable Magento_GroupedImportExport
bin/magento module:disable Magento_GroupedCatalogInventory
bin/magento module:disable Magento_GroupedProductGraphQl
bin/magento module:disable Magento_MsrpGroupedProduct
bin/magento module:disable Magento_GroupedProduct
bin/magento module:disable Magento_CatalogRuleConfigurable
bin/magento module:disable Magento_MsrpConfigurableProduct
bin/magento module:disable Magento_NewRelicReporting
bin/magento module:disable Magento_ConfigurableProductGraphQl
bin/magento module:disable Magento_ConfigurableProductSales
bin/magento module:disable Magento_ConfigurableImportExport
bin/magento module:disable Magento_SwatchesGraphQl
bin/magento module:disable Magento_Swatches
bin/magento module:disable Magento_ConfigurableProduct
bin/magento setup:upgrade
```
2. Login on storefront.
3. Add Simple Product to cart.
4. Go to Checkout.
5. Create an Order.

### Expected result (*)

1. Product added to Cart.
2. Order Created.

### Actual result (*)

1. Error on adding Product.
2. Error on Checkout page.

### PR DESCRIPTION
**Pull request by thomas-kl1**
Item resolvers should be optional. If we remove configurable and grouped product, checkout is broken because this argument is mandatory. Only the grouper and configurable product add item resolver.

### Resolved issues:
1. [x] resolves magento/magento2#30860: Item resolvers should be optional
### Preconditions (*)

1. Customer created
2. Simple Product created

### Steps to reproduce (*)

1. Execute:
```
bin/magento module:disable Magento_GroupedImportExport
bin/magento module:disable Magento_GroupedCatalogInventory
bin/magento module:disable Magento_GroupedProductGraphQl
bin/magento module:disable Magento_MsrpGroupedProduct
bin/magento module:disable Magento_GroupedProduct
bin/magento module:disable Magento_CatalogRuleConfigurable
bin/magento module:disable Magento_MsrpConfigurableProduct
bin/magento module:disable Magento_NewRelicReporting
bin/magento module:disable Magento_ConfigurableProductGraphQl
bin/magento module:disable Magento_ConfigurableProductSales
bin/magento module:disable Magento_ConfigurableImportExport
bin/magento module:disable Magento_SwatchesGraphQl
bin/magento module:disable Magento_Swatches
bin/magento module:disable Magento_ConfigurableProduct
bin/magento setup:upgrade
```
2. Login on storefront.
3. Add Simple Product to cart.
4. Go to Checkout.
5. Create an Order.

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Hi @thomas-kl1,
Could you add some steps to reproduce, actual and expected result?
Unfortunately it's not clear how to important to fix the issue.

**Comment by thomas-kl1** [comment]
Take a look on the implementation of the method:

    /**
     * {@inheritdoc}
     */
    public function getFinalProduct(ItemInterface $item) : ProductInterface
    {
        $finalProduct = $item->getProduct();
        foreach ($this->itemResolvers as $resolver) {
            $resolvedProduct = $this->getItemResolverInstance($resolver)->getFinalProduct($item);
            if ($resolvedProduct !== $finalProduct) {
                $finalProduct = $resolvedProduct;
                break;
            }
        }
        return $finalProduct;
    }

Default case should return the item product. Then it iterates over resolvers for specific type of products. However in this case it requires that itemResolvers is an array. But if the grouped and configurable products module is not there, it's breaking the checkout.. By design the catalog module should works regardless other product type implementation

**Comment by ihor-sviziev** [comment]
@thomas-kl1 I see that in constructor we have defined type - array, so we shouldn't have any other options. Empty array should be by default.

Could you provide more info, what exception do you have? What value are you getting in the `$itemResolvers` are you getting when the grouped and configurable products module is not there?

**Comment by thomas-kl1** [comment]
I got this: Invalid argument supplied for foreach(), value is null

**Comment by ihor-sviziev** [comment]
Hi @thomas-kl1,
It doesn't seems to me logical.

Do you have some custom extension that changes this part? Could you provide full output of exception? 

Still not clear where do you having this issue, on some frontend page or during some CLI command run?

**Comment by thomas-kl1** [comment]
The issue occurs on the checkout and cart page. What does not seems logical there? You can edit composer json and replace both module, or create your own metapackage with magento2-base and catalog modules.
There is no third party modules. Only magento2 official modules

**Comment by ihor-sviziev** [comment]
@thomas-kl1 thx for explanation, I'll check it myself and will give you my feedback a bit later.

**Comment by thomas-kl1** [comment]
My bad I still had some debug trace. The actual error message was different and not that value null is used in foreach. I can post the actual exception later. Sorry

**Comment by thomas-kl1** [comment]
Here the exception message:

[2020-11-06 16:04:57] main.CRITICAL: Missing required argument $itemResolvers of Magento\Catalog\Model\Product\Configuration\Item\ItemResolverComposite. [] []

**Comment by sidolov** [comment]
@magento create issue

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @thomas-kl1,
Seems your solution isn't really right. The issue there that argument definition is missing in the di.xml.
Could you try to add the following code in the di.xml in the Magento/Catalog module instead of doing the argument optional, something like this?
```xml
...
    <type name="Magento\Quote\Model\Quote\Item\RelatedProducts">
        <arguments>
            <!-- Define this argument as empty array by default -->
            <argument name="relatedProductTypes" xsi:type="array"/>
        </arguments>
    </type>
```

**Comment by thomas-kl1** [comment]
This would be better I agree, didn't think about it (empty array in di).
I update the PR tonight.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8453](https://jira.corp.magento.com/browse/ENGCOM-8453) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by thomas-kl1** [comment]
@ihor-sviziev any ETA for this one?

**Comment by ihor-sviziev** [comment]
Hi @thomas-kl1,
So far this PR has a low priority, it will be processed after high priority PRs.
If you feel the priority set incorrectly - please let us know.

**Comment by mrtuvn** [comment]
@thomas-kl1 Can you update for resolve conflicts in di.xml

**Comment by thomas-kl1** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Unit Tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8453](https://jira.corp.magento.com/browse/ENGCOM-8453) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Foxtrot** [comment]
QA passed.

**Pull request merged**
