### PR TITLE
Fixed blank amdin page after install magento 2.3.0 in Windows 10

### PR DESCRIPTION
**Pull request by iamdylanngo**
### Description (*)

Fixed blank amdin page after install magento 2.3.0 in Windows 10

### Fixed Issues (if relevant)

1. magento/magento2#20084: Blank admin page after install magento 2.3.0 on Windows 10

### Manual testing scenarios (*)

1. I go to folder \lib\internal\Magento\Framework\View\Element\Template\File\Validator.php
2. Change code in line 140
```bash
if (0 === strpos($realPath, $directory)) {
    return true;
}
```
To
```bash
if (0 === strpos($realPath, $directory) || 0 === strpos($path, $directory)) {
    return true;
}
```

### Result
I ran successfully on windows
screenshot_5
screenshot_6

Maybe this is the solution you need 💯

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @jundat95. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20085) <br/>All committers have signed the CLA.

**Comment by sivaschenko** [comment]
Hi @jundat95 thanks for your contribution, have you got a chance to figure out what is the root cause of the issue? What is the difference between `$realPath` and `$path`? Is it the problem described here: https://bugs.php.net/bug.php?id=61933

**Comment by iamdylanngo** [comment]
@sivaschenko  Yes, problem like https://bugs.php.net/bug.php?id=61933
I think this problem is a big barrier for people who start learning magento, we fix it in time
Thank!!

**On the Windows 10 operating system the path, realpath of the file it looks like this:**

Path: C:/xampp/htdocs/magento2/app/code/Magento/Backend/view/adminhtml/templates/page/js/require_js.phtml
RealPath: C:\xampp\htdocs\magento2\app\code\Magento\Backend\view\adminhtml\templates\page\js\require_js.phtml
Directories:
Array ( [0] => C:/xampp/htdocs/magento2/var/view_preprocessed/pub/static/ ) 

**Log $path and $realdPath in Windows 10 Environment, PHP 7.2:**

screenshot_10
screenshot_2

**Comment by rodrigowebjump** [comment]
Hi @jundat95 I do not think that use $path is a solution. The purpose of this method is to check if dir is included in the path. Realpath function can resolve ".", "..", symbolic paths and translate it in a full path. Use $path could create security-breaches depending on the use of this method.

Please, check the line 114 of method isValid. What you think in replace the "\\" by "/"?

**Comment by orlangur** [comment]
Hi @jundat95, unfortunately we cannot accept this contribution as Windows is not a supported platform, please check https://github.com/magento/magento2/pull/9492#issuecomment-310778904 for more details.

Also, you can check https://github.com/magento/magento2/issues/19471#issuecomment-443195351 for an easiest solution to deploy under Windows 10.

**Comment by ghost** [comment]
Hi @jundat95, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+magento2+20085), it will take less than a minute. </br>Your feedback will help us to improve contribution process.

**Pull request closed without merging**
