### PR TITLE
Fill data_hash from BULK response with correct data

### PR DESCRIPTION
**Pull request by silyadev**
Description (*)

Added hash for imported data and return it in response
Copy of https://github.com/magento/async-import/pull/63

#23 Fill data_hash from BULK response with correct data
Manual testing scenarios (*)

    Make call to bulk API
    Check response

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21815) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @silyadev. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by nuzil — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-4531](https://jira.corp.magento.com/browse/ENGCOM-4531) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@silyadev thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed 

**Result:**

after

**Pull request merged**
