### PR TITLE
[Backport-2.1] Trim username on customer account login page

### PR DESCRIPTION
**Pull request by dankhrapiyush**
### Original Pull Request 
 https://github.com/magento/magento2/pull/15365

Trim email address on customer account login page generally when copy and paste.

### Description

Trim email address by remove leading or trailing space on the customer account login page email field.

### Fixed Issues (if relevant)

1. magento/magento2#6058: IE11 user login email validation fails if field has leading or trailing space

### Manual testing scenarios

1. Open customer account login page in Firefox or IE browser.
2. Try to add space before entering an email address in the Email field.
3. Copy `" johndoe@domain.com "` and paste in the Email field. It will automatically remove leading or trailing space.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
I closed and re-opened PR in order to restart build on travis

**Comment by dankhrapiyush** [comment]
@ihor-sviziev Okay
In original PR, it was not completed as well.
- Reference comment: [issuecomment-393120908](https://github.com/magento/magento2/pull/15365#issuecomment-393120908)

Thank you.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-1930](https://jira.corp.magento.com/browse/ENGCOM-1930) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @dankhrapiyush. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.1.15 release.

**Pull request merged**
