### PR TITLE
Navigation menu 4th level/category does not appear consistently #25589

### PR DESCRIPTION
**Pull request by fabriciosobral**
ISSUE LINK https://github.com/magento/magento2/issues/25589

### Description (*)
When the submenu was created in the third stage follow, the focus function does not work and submenu doesn't work
Fixed js in UI_MODULES calling lost function

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rodrigowebjump** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [new Magento instance](https://pr-25613.instances.magento-community.engineering).
Admin access: [https://pr-25613.instances.magento-community.engineering/admin](https://pr-25613.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rodrigowebjump** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [Magento instance](https://i-25613-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25613-2-3-develop.instances.magento-community.engineering/admin](https://i-25613-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by rodrigowebjump — APPROVED** [review]
Hi @fabriciosobral 

Thanks for your contribution.

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-6291](https://jira.corp.magento.com/browse/ENGCOM-6291) has been created to process this Pull Request
:eight_spoked_asterisk: @rodrigowebjump, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6291](https://jira.corp.magento.com/browse/ENGCOM-6291) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:**
before

**After:**
after

**Comment by VladimirZaets** [comment]
Covered by automated tests in the scope of PR https://github.com/magento/magento2/pull/25704

**Pull request merged**
