### PR TITLE
Grammatical mistake in the comments

### PR DESCRIPTION
**Pull request by sudhanshu-bajaj**
### Description (*)

Grammatical mistake in the comments.

**Then** is commonly used to express a sense of time or what comes next or used to be.

**Than** is used to form comparisons between two things.

### Fixed Issues (if relevant)

1. N/A

### Manual testing scenarios (*)

1. N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22858) <br/>All committers have signed the CLA.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5108](https://jira.corp.magento.com/browse/ENGCOM-5108) has been created to process this Pull Request

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5108](https://jira.corp.magento.com/browse/ENGCOM-5108) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
**Notice:** QA not applicable

**Pull request merged**
