### PR TITLE
Move including "_extend.less" in css root files; fixes #11098, fixes #16989

### LINKED ISSUE #11098: Mobile media query inside _extend.less, wrong order in styles-m.css and styles-l.css
### Preconditions
1. Magento ver. 2.1.8
2. Custom theme with `<parent>Magento/luma</parent>`

### Steps to reproduce
When using media queries inside `_extend.less`:
```
// normal
.logo {
    border-bottom: 4px solid #cccccc; // should be overwritten with media queries styles
}
& when (@media-common = true) {
    .logo {
        border: 1px solid #cccccc; // should be overwritten with media queries styles
        .lib-css(background, @link__color);
    }
}
// mobile media query
.media-width(@extremum, @break) when (@extremum = 'max') and (@break = @screen__m) {
    .logo {
        border: 1px solid #ff00ff;
    }
}
// tablet media query
.media-width(@extremum, @break) when (@extremum = 'min') and (@break = @screen__m) {
    .logo {
        border: 1px solid #ff0000;
    }
}
```

### Expected result
1. Styles specificity order: compiled styles-m.css and styles-l.css "// normal" before media queries styles.

### Actual result
1. The media queries styles compiled inside styles-m.css and styles-l.css appear before the "// normal" style, so it has lesser specificity, and it's overridden by the "// normal" styles.

### Fix
Inside styles-m.less and styles-l.less you need to put `//@magento_import 'source/_extend.less';` before `@import 'source/lib/_responsive.less';`

```
//
//  Extend for minor customisation
//  ---------------------------------------------

//@magento_import 'source/_extend.less';

//
//  Media queries collector
//  ---------------------------------------------

@import 'source/lib/_responsive.less';
```

### LINKED ISSUE #16989: Less variables defined in theme "_extend.less" can't be overridden in "_theme.less"
### Summary
Less variables defined in theme `<Module>/_extend.less` can't be overridden in `_theme.less`

### Steps to reproduce
1.  Create new theme
2.  Add `Magento_Theme/web/css/source/_extend.less`  with this content:
```
@test: red;

& when (@media-common = true) {
    body {
        background-color: @test;
    }
}
```
3. Try to override `@test` in `web/css/source/_theme.less`:
```@test: green;```

### Expected result
`body` has `green` background

### Actual result
`body` has `red` background

### Solution
In `web\css\styles-m.less` and `web\css\styles-l.less` move `@import 'source/_theme.less';` below  `//@magento_import 'source/_extend.less';`

### PR DESCRIPTION
**Pull request by denistrator**
# This PR fixes two issues #16989 and #11098

### Summary
Less variables defined in theme `<Module>/_extend.less` can't be overridden in `_theme.less`

### Steps to reproduce
1.  Create new theme
2.  Add `Magento_Theme/web/css/source/_extend.less`  with this content:
```
@test: red;

& when (@media-common = true) {
    body {
        background-color: @test;
    }
}
```
3. Try to override `@test` in `web/css/source/_theme.less`:
```@test: green;```

### Expected result
`body` has `green` background

### Actual result
`body` has `red` background

### Solution
In `web\css\styles-m.less` and `web\css\styles-l.less` move `@import 'source/_theme.less';` below  `//@magento_import 'source/_extend.less';`

### Summary

Styles in `_extend.less` declared for mobile (`.media-width(@extremum, @break) when (@extremum = 'max') and (@break = @screen__m) { ... }`) are overridden by common styles (`& when (@media-common = true) { ... }`)

###  Illustration of the issue:

`_module.less`
screenshot_167

`_extend.less`
screenshot_166

On desktop styles have expected priority
screenshot_163

But on mobile common styles have higher priority than mobile-specific styles which is not expected result screenshot_164

After the fix applied mobile styles have expected order
screenshot_165

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16991) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @denistrator. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by orlangur** [comment]
Cc: @vkublytskyi @VladimirZaets @MomotenkoNatalia, see https://github.com/magento/magento2/issues/11098#issuecomment-334392989

**Comment by denistrator** [comment]
Created new PR #17012 to change source branch

**Pull request closed without merging**
