### PR TITLE
[Backport] Fix disappearing navigation arrows in fotorama zoom

### PR DESCRIPTION
**Pull request by luukschakenraad**
### Description (*)
Fix for dissapearing navigation arrows in Fotorama zoom

### Fixed Issues (if relevant)
magento/magento2#18585: Navigation arrows zoomed fotorama disappear

### Manual testing scenarios (*)
1. Go to category Women -> Tops -> Jackets
2. Open product "Olivia 1/4 Zip Light Jacket"
3. Click on the large product image on the left
4. Check that navigation arrows are visible
5. Click on a thumbnail
6. Check that navigation arrows keep visible

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### Original PR 
https://github.com/magento/magento2/pull/18590

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @luukschakenraad. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by hostep** [comment]
I might be wrong about this, but it could be that this is trying to fix the same issue as https://github.com/magento/magento2/pull/18443 is trying to fix (but that one is for a lot more options of fotorama)

**Comment by luukschakenraad** [comment]
> I might be wrong about this, but it could be that this is trying to fix the same issue as #18443 is trying to fix (but that one is for a lot more options of fotorama)

That one seems to be unrelated to this issue. This one has nothing to do with any settings. It's just a bug in Fotorama which causes wrong behaviour of the previous and next buttons.

**Comment by hostep** [comment]
Well, actually they are related :)

I just played around a bit with this, if I take a clean Magento 2.2.6 installation, then apply the changes from: 
- https://github.com/magento/magento2/commit/0255ce3d64865b25417606713b438b5f78543b97
- https://github.com/magento/magento2/pull/18443/files

And then re-test, all the issues you mention in #18585 are fixed.

Here's why, these are the configuration values outputted in the html for the fotorama library:

Vanilla 2.2.6:
```json
{
    "fullscreen": {
        "arrows": 1,
        "loop": 1,
        "nav": "thumbs",
        "navdir": "horizontal",
        "navtype": "slides",
        "transition": "slide",
        "transitionduration": 500
    },
    "options": {
        "allowfullscreen": 1,
        "arrows": 1,
        "height": 560,
        "keyboard": 1,
        "loop": 1,
        "nav": "thumbs",
        "navarrows": 1,
        "navdir": "horizontal",
        "navtype": "slides",
        "thumbheight": 110,
        "thumbwidth": "88",
        "transition": "slide",
        "transitionduration": 500,
        "width": "700"
    }
}
```

After applying two fixes mentioned above:
```json
{
    "fullscreen": {
        "arrows": true,
        "loop": true,
        "nav": "thumbs",
        "navarrows": false,
        "navdir": "horizontal",
        "navtype": "slides",
        "showCaption": false,
        "transition": "slide",
        "transitionduration": 500
    },
    "options": {
        "allowfullscreen": true,
        "arrows": true,
        "height": 560,
        "keyboard": true,
        "loop": true,
        "nav": "thumbs",
        "navarrows": true,
        "navdir": "horizontal",
        "navtype": "slides",
        "showCaption": false,
        "thumbheight": 110,
        "thumbwidth": 88,
        "transition": "slide",
        "transitionduration": 500,
        "width": 700
    }
}
```

You'll notice that in the fixed code, a lot of values `1` changed to the more correct value `true`.
For some reason, if you pass on `1` to the `toggle` function from jQuery, it will switch on and off and on and off, don't ask me why, my javascript knowledge isn't what it used to be. You can find a demo in https://jsfiddle.net/ot0adbhv/ (click the button a couple of times to see its behavior)

I'll leave this open for now, so a community maintainer can decide what to do with it, but in my opinion there is already a proper fix for the issue in #18443.

**Comment by luukschakenraad** [comment]
You are absolutely right @hostep, very well spotted. It's my double not operator that transforms the number into a boolean and in #18443 the setting is directly set as boolean.

In my opinion, both fixes can be applied as:
- they won't conflict
- The `!!` is also in Fotorama's source-code
- gallery.phtml may be overwritten by a theme or module in which case a user can not get the advantages of fix #18443.

**Comment by hostep** [comment]
> - The !! is also in Fotorama's source-code

Ah yes, you are correct, I wasn't aware of this!

Did it little more research, so just for some extra context:
- It was added in Fotorama in: https://github.com/artpolikarpov/fotorama/commit/097e27ebbf83f96b0357a1f2ae651a266bae81c4#diff-a8ba3933459ba275512d8b6c005bea21L269
- It was removed again in Magento's fork in: https://github.com/magento/magento2/commit/3840124c4427144c053189a188afcb4d4feaec7f#diff-86f4d0a1cbadb052fcfe8b0f21cff058L2413

Not sure why it got removed in Magento though ...

But if we have to get it back in Magento, I suggest you also edit the [`fotorama.min.js` file](https://github.com/magento/magento2/blob/c9d1bec/lib/web/fotorama/fotorama.min.js), I believe this file should be edited manually, I don't think there is some automatic process to generate the minified version.

**Comment by luukschakenraad** [comment]
I now changed the minified version as well. I did the same for pull request https://github.com/magento/magento2/pull/18590

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3200](https://jira.corp.magento.com/browse/ENGCOM-3200) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @luukschakenraad. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
