### PR TITLE
magento/magento2#32596: Category Update API resets available_sort_by to use config value.

### LINKED ISSUE #32596: Category Update API resets available_sort_by to use config value
### Preconditions (*)

1. Magento 2.4

### Steps to reproduce (*)

1. Create a Category in the admin and specify a value for available_sort_by
2. Execute the following api (change the id based on your created category)
```php
<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://example.com/rest/all/V1/categories/1321',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'PUT',
  CURLOPT_POSTFIELDS =>'{
    "category": {
        "name": "Example Category",
        "parent_id": "25",
        "id": "1321",
        "custom_attributes": [
            {
                "attribute_code": "url_key",
                "value": "example-category"
            }
        ]
    }
}',
  CURLOPT_HTTPHEADER => array(
    'Content-Type: application/json',
    'Authorization: Bearer xxxxxxxxxxx',
    'Cookie: PHPSESSID=2kansl4q65fupe9jn1ptrl6j2q; XDEBUG_SESSION=PHPSTORM'
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;
```

### Expected result (*)

image

### Actual result (*)

image

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by engcom-Foxtrot**
### Description (*)

Re-creation of https://github.com/magento/magento2/pull/32597.

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/32596

### Manual testing scenarios (*)

See https://github.com/magento/magento2/issues/32596

### Questions or comments

See https://github.com/magento/magento2/issues/32596

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run WebAPI Tests, Functional Tests EE, Functional Tests B2B

**Comment by Den4ik** [comment]
@magento run WebAPI Tests

**Comment by Den4ik** [comment]
@magento run WebAPI Tests

**Comment by Den4ik** [comment]
@magento run WebAPI Tests

**Comment by Den4ik** [comment]
@engcom-Foxtrot Thanks for PR. Failed WebAPI test related to changes in PR, could you please update it.

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Functional Tests EE, Functional Tests B2B, Unit Tests

**Review by Den4ik — APPROVED** [review]
✅ Approved

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9100](https://jira.corp.magento.com/browse/ENGCOM-9100) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Have a fresh Magento 2 instance with sample data.
2. Have a admin token created to utilize in the below executable API requests


**Manual testing scenario:**

1. Create a new category from Admin > Catalog, with "Available Product Listing Sort By" drop down with 2 options only as shown in below screen shot
        image

2. Make a PUT call using /rest/all/V1/categories/<above_created_category_id> with below given sample payload.
       {  
         "category":{  
            "id":"41",
            "name":"mks",
            "is_active":"true",
            "include_in_menu":"true",
            "parent_id":"2",
             "customAttributes":[  
               {  
                  "attributeCode":"description",
                  "value":"updated through api"
               }
            ]
         }
      }
3. Navigate to Admin > Category page and view it


**Before:** :heavy_multiplication_x: "Available Product Listing Sort By" drop down was getting selected with all the options and was keeping the "Use All" checkbox checked
> image


**After:** :heavy_check_mark:  "Available Product Listing Sort By" drop down is being with the same options that was set prior the PUT request
> image


There is no other regression is required on this, since it is a part of WebAPI fix. Also the relevant api-functional and integration API auto tests have been updated and the results are passed.

**Pull request merged**
