### PR TITLE
[Forwardport] [Correct code formatting]

### PR DESCRIPTION
**Pull request by hitesh-wagento**
### Original Pull Request 
 https://github.com/magento/magento2/pull/15811
### This PR is a:

- [ ] Bug fix or improvement

### Summary
Correct Code formatting.

### Additional information
NA

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @hitesh-wagento. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on Pull Request changes
- `@magento-engcom-team give me new test instance` - deploy **NEW** test instance based on Pull Request changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy Vanilla Magento instance for Issue or Pull Request

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by ishakhsuvarov** [comment]
Hi @hitesh-wagento 
This Pull Request contains 4 commits with no message. This is not acceptable.
Please squash all of the changes into a single commit and accompany it with a message

**Comment by hitesh-wagento** [comment]
@ishakhsuvarov

I have created forwardport using Port tool didn't commit different files.

**Comment by ishakhsuvarov** [comment]
@hitesh-wagento Porting tool was created only to assist in some cases, however, it's not guaranteed to produce correct result. It is considered to be PR author's responsibility to fix anything which may be incorrect.

**Pull request closed without merging**
