### PR TITLE
Removed lonely <br> tags in payment.html template, when invisible captcha is enabled or completely disabled

### LINKED ISSUE #33820: Lonely <br> tags in payment.html template
### Summary (*)
When checkout reCaptcha is not visible or visible and configured to use invisible reCaptcha, there are two lonely `<br>` tags inside `payment.html` file:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/view/frontend/web/template/payment.html

### Examples (*)

```
                </legend><br />
                <!-- ko foreach: getRegion('place-order-captcha') -->
                    <!-- ko template: getTemplate() --><!-- /ko -->
                <!-- /ko -->
                <br />
```

### Proposed solution

I suggest to remove them completely or move them to reCaptcha templates.

```
                </legend>
                <!-- ko foreach: getRegion('place-order-captcha') -->
                    <!-- ko template: getTemplate() --><!-- /ko -->
                <!-- /ko -->
```

---

Please leave me a feedback on what is the desired solution, so I can prepare PR for this.

- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by dudzio12**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#33820

### Manual testing scenarios (*)

1. Magento `2.4-develop` with `blank`/`Luma` theme enabled.

### Questions or comments
I need help with proposed stylesheet changes. Is it ok as there is now?

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by dudzio12** [comment]
@magento give me test instance

**Comment by dudzio12** [comment]
@magento run all tests

**Comment by dudzio12** [comment]
image

**Comment by dudzio12** [comment]
image

I think there is completely no point to adding any additional styles.

**Review by BarnyShergold — APPROVED** [review]
Looks great but for some reason some tests are failing

**Comment by magento-engcom-team** [comment]
Hi @BarnyShergold, thank you for the review.
[ENGCOM-9193](https://jira.corp.magento.com/browse/ENGCOM-9193) has been created to process this Pull Request
:eight_spoked_asterisk: @BarnyShergold, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@dudzio12 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by dudzio12** [comment]
@BarnyShergold - thanks for approval, tests are failing because of something else 👎

**Comment by BarnyShergold** [comment]
@magento run Unit Tests

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9193](https://jira.corp.magento.com/browse/ENGCOM-9193) has been created to process this Pull Request

**Comment by BarnyShergold** [comment]
@magento run Functional Tests CE

**Comment by BarnyShergold** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by BarnyShergold** [comment]
@dudzio12 - Finally all tests have passed!

**Comment by andrewbess** [comment]
This PR has already been merged

**Pull request merged**
