### PR TITLE
No validation "Sort Order" in "New Rating" form issue 23984

### LINKED ISSUE #23984: No validation "Sort Order" in "New Rating" form
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Stores-> Rating
2. Add New Rating
3. Fill All information, "Sort Order" fill "one"
4. Save Rating 

### Expected result (*)

1. Can not save

### Actual result (*)

1. Still save

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#23984: No validation "Sort Order" in "New Rating" form

Solution : Add class "validate-not-negative-number" to sort order field

### Fixed Issues (if relevant)

1. magento/magento2#23984: No validation "Sort Order" in "New Rating" form

### Manual testing scenarios (*)

1. Go to Stores-> Rating
2. Add New Rating
3. Fill All information, "Sort Order" fill "one"
4. Save Rating 
=> Can not save

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5538](https://jira.corp.magento.com/browse/ENGCOM-5538) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by edenduong** [comment]
Could I receive “bug fix award” ? Thank you ! :)

**Comment by VladimirZaets** [comment]
@edenduong sorry for that, I will add the award points to this PR

**Pull request merged**
