### PR TITLE
Code cleanup, add more visibility

### PR DESCRIPTION
**Pull request by thomas-kl1**
See previsous PR: pull/14607

@orlangur I've applied your suggestions in this new PR.

### Description
I was reading some piece of code when I see te "foreach" and "break" statements. I know that the "break" should be avoided, so here my suggestion to retrieve the key of the first element of the array.
Is there a goal to do it via a foreach and break?

I've fixed also some useless "else" statements and add some ternary operators to replace the conditions where there's only a value assignment.

### CODE REVIEW

**Comment by thomas-kl1** [comment]
Hi @orlangur , any news ?

**Comment by VladimirZaets** [comment]
Hi @thomas-blackbird  We took this PR in progress. PR will be merged in the nearest time.

**Comment by magento-engcom-team** [comment]
@thomas-blackbird thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @thomas-blackbird. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

**Pull request merged**
