### PR TITLE
Fix #26992 Add new rating is active checkbox alignment issue

### LINKED ISSUE #26992: Add New ratings Is active and checkbox alignment issue
Add New ratings Is active and checkbox alignment issue

### Preconditions (*)
Magento: 2.3.4

### Steps to reproduce (*)
- Admin -> Stores -> Attributes -> Ratings -> Add new ratings

### Expected result (*)
It should display in same line

### Actual result (*)
image

### PR DESCRIPTION
**Pull request by srsathish92**
### Description (*)
This PR fix #26992, Added Style in Magento_Review module itself.

### Fixed Issues (if relevant)
1. magento/magento2#26992: Add New ratings Is active and checkbox alignment issue

### Manual testing scenarios (*)

- GoTo Admin -> Stores -> Attributes -> Ratings -> Add new ratings -> Rating Visibility Section
- Checkbox alignment should be in same line

### Questions or comments
If any please let me know the feedback's

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages

### CODE REVIEW

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @srsathish92, thank you for your contribution, however could you please refactor your implementation, in order to fix the alignment for other checkboxes as well?
Please check the following settings: 
- `Stores / Tax Zones and Rates / New Tax Rate / Zip/Post is Range`
- `Stores / Tax Rules / New Tax Rule / Additional Settings / Calculate Off Subtotal Only`

Also, please take into account this issue #24761.
Thank you.

**Comment by srsathish92** [comment]
@eduard13 Good Catch, Thanks for the feedback. I believe this PR #24761 only reason for all checkbox alignment issue, So I reverted & added fix for alone. correct me If I am wrong.

**Test Scenarios:**
- Stores / Tax Zones and Rates / New Tax Rate / Zip/Post is Range
- Stores / Tax Rules / New Tax Rule / Additional Settings / Calculate Off Subtotal Only
- Customer / Edit / Newsletter Tab / Subscribed to Newsletter
- Catalog / Product / Action Attribute/ Edit / checkbox with change

**Comment by eduard13** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @eduard13. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @eduard13, here is your [new Magento instance](https://pr-27014.instances.magento-community.engineering).
Admin access: [https://pr-27014.instances.magento-community.engineering/admin_4e8c](https://pr-27014.instances.magento-community.engineering/admin_4e8c)
Login: `2f85e46b` Password: `42fd08b0749c`
Instance will be terminated in up to 3 hours.

**Review by eduard13 — APPROVED** [review]
Looks good.
Thank you.

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-7015](https://jira.corp.magento.com/browse/ENGCOM-7015) has been created to process this Pull Request
:eight_spoked_asterisk: @eduard13, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by ptylek — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-7015](https://jira.corp.magento.com/browse/ENGCOM-7015) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
