### PR TITLE
Optimized topological sorting of modules.

### LINKED ISSUE #31611: Optimized topological sorting of modules
Wrong way of sorting is not environmentally friendly, let's make an optimization and save energy.
I believe it would be great to revisit all locations of topological sorting.
After cache flush or other related events part of the code significantly slows down processing.

### Preconditions (*)

1. Magento 2.3.5
2. run bin/magento

### Steps to reproduce (*)

1. run bin/magento
2.

### Expected result (*)

1. Nice and clean
```
 102  array_fill
1049  array_filter
 121  array_flip
  11  array_intersect
7529  array_key_exists
2218  array_keys
 387  array_map
4179  array_merge
   2  array_merge_recursive
 366  array_pop
 368  array_push
   5  array_replace
```

### Actual result (*)

1. Fancy topological sorting.
2. array_merge and array_unique triggered over 60000 times for 300+ modules.
```
 108  array_fill
2054  array_filter
 763  array_flip
  12  array_intersect
7406  array_key_exists
4329  array_keys
 773  array_map
68348  array_merge
   4  array_merge_recursive
 411  array_pop
 427  array_push
   8  array_replace
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by kirmorozov**
### Description (*)

Optimization of topological sorting, can be used as an example for other Magento functionality.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31611

### Manual testing scenarios (*)

1. bin/magento
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by kirmorozov** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
Hi @kirmorozov, thanks for contributing! Can you provide some extra information on execution time improvement? Ideally, we need to see the difference between your solution and vanilla Magento.

Can you provide that information?

Thanks!

**Comment by kirmorozov** [comment]
@gabrieldagama please read https://github.com/magento/magento2/issues/31611,
Memory complexity of current implementation is insane.

**Comment by kirmorozov** [comment]
As I see, some modules got used to result sequence.
Given that unit tests passed, and were not changed, look like there are missing dependencies between some modules.

**Comment by mrtuvn** [comment]
@kirmorozov can you recheck file conflicts and test coverage as well ?

**Comment by ishakhsuvarov** [comment]
Hi

I am closing this PR for now as it seems like it has become stale and still needs work.

Please feel free to reopen if you wish to continue.

Thanks!

**Pull request closed without merging**
