### PR TITLE
Update `indexer:reset` to call `$indexer->invalidate()`

### LINKED ISSUE #34988: [Issue] Update `indexer:reset` to call `$indexer->invalidate()`
This issue is automatically created based on existing pull request: magento/magento2#34582: Update `indexer:reset` to call `$indexer->invalidate()`

---------
I was recently debugging something that was invalidating the indexers. 

I added some logging using a before plugin on the `invalidate` function

```php
public function beforeInvalidate(\Magento\Framework\Indexer\IndexerInterface $subject)
{
    $this->logger->info(
        "Invalidating index",
        [
            'indexer_id' => $subject->getId(),
            'trace' => str_replace(PHP_EOL, '|', (new \Exception())->getTraceAsString())
        ]
    );
}
```

But this use case isn't caught in my logs. 

It seems to me that this command should just call the function that invalidates the indexer rather than repeating the work itself. I'm sorting out my own logging / debugging internally, but this seems sensible to fix here.

https://github.com/magento/magento2/blob/227cf9229152ed4332c607796cf476055ef9ec4f/app/code/Magento/Indexer/Model/Indexer.php#L345-L355

### Manual testing scenarios (*)
1. Call `indexer:reset` and see the indexer was invalidated

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by convenient**
I was recently debugging something that was invalidating the indexers. 

I added some logging using a before plugin on the `invalidate` function

```php
public function beforeInvalidate(\Magento\Framework\Indexer\IndexerInterface $subject)
{
    $this->logger->info(
        "Invalidating index",
        [
            'indexer_id' => $subject->getId(),
            'trace' => str_replace(PHP_EOL, '|', (new \Exception())->getTraceAsString())
        ]
    );
}
```

But this use case isn't caught in my logs. 

It seems to me that this command should just call the function that invalidates the indexer rather than repeating the work itself. I'm sorting out my own logging / debugging internally, but this seems sensible to fix here.

https://github.com/magento/magento2/blob/227cf9229152ed4332c607796cf476055ef9ec4f/app/code/Magento/Indexer/Model/Indexer.php#L345-L355

### Manual testing scenarios (*)
1. Call `indexer:reset` and see the indexer was invalidated

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#34988: Update `indexer:reset` to call `$indexer->invalidate()`

### CODE REVIEW

**Comment by convenient** [comment]
@magento run all tests

**Comment by convenient** [comment]
@magento run all tests

**Comment by convenient** [comment]
@magento run all tests

**Comment by convenient** [comment]
@magento run all tests

**Comment by convenient** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by convenient** [comment]
@magento run Functional Tests B2B

**Review by andrewbess — APPROVED** [review]
Hello @convenient 
Thank you for your contribution here.
Good work

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, thank you for the review.
[ENGCOM-9342](https://jira.corp.magento.com/browse/ENGCOM-9342) has been created to process this Pull Request
:eight_spoked_asterisk: @andrewbess, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
Thanks for your collaboration and contribution @convenient  and @andrewbess .

1. Created before plug-in Model as shown in the below screenshot.(beforeInvalidate method code also updated as per above description)
image
2. Upgraded & static deployed in the local magento instance
3. Enabled the debugging mode
4. Ran the indexer reset command
5. Verified in the system log & debugging logs.

**Expected before PR Changes** :
As per the above issue comments & descriptions we should  not expect in the logs
**Expected after PR Changes**:
We should expect in the logs.

Observation: Not found any logs after PR changes made.

Please lets know if we have to modify anything in the above execution steps

**Comment by convenient** [comment]
I can see your class isn't being constructed with the logger property? so I would expect a PHP fatal error to be logged?

However if no fatal error is occurring it suggests you dont have the plugin hooked in correctly?

If you're adding a plugin you'll need to clear the relevant generated directories and caches 
https://devdocs.magento.com/guides/v2.4/howdoi/php/php_clear-dirs.html

This is what I have running in production...

```diff
diff --git a/src/Plugin/Indexer.php b/src/Plugin/Indexer.php
new file mode 100644
index 0000000..9aa35d1
--- /dev/null
+++ b/src/Plugin/Indexer.php
@@ -0,0 +1,32 @@
+<?php
+namespace Ampersand\MviewIndexerLogger\Plugin;
+
+class Indexer
+{
+    /** @var \Psr\Log\LoggerInterface */
+    private $logger;
+
+    /**
+     * Action constructor.
+     * @param \Psr\Log\LoggerInterface $logger
+     */
+    public function __construct(
+        \Psr\Log\LoggerInterface $logger
+    ) {
+        $this->logger = $logger;
+    }
+
+    /**
+     * @param \Magento\Framework\Indexer\IndexerInterface $subject
+     */
+    public function beforeInvalidate(\Magento\Framework\Indexer\IndexerInterface $subject)
+    {
+        $this->logger->info(
+            "Invalidating index",
+            [
+                'indexer_id' => $subject->getId(),
+                'trace' => str_replace(PHP_EOL, '|', (new \Exception())->getTraceAsString())
+            ]
+        );
+    }
+}
diff --git a/src/etc/di.xml b/src/etc/di.xml
index 8867f14..4d07f02 100644
--- a/src/etc/di.xml
+++ b/src/etc/di.xml
@@ -4,4 +4,7 @@
     <type name="Magento\Framework\Mview\ActionInterface">
         <plugin name="Ampersand\MviewIndexerLogger\Plugin\Action" type="Ampersand\MviewIndexerLogger\Plugin\Action"/>
     </type>
+    <type name="Magento\Framework\Indexer\IndexerInterface">
+        <plugin name="log-invalidate-indexer-trace" type="Ampersand\MviewIndexerLogger\Plugin\Indexer"/>
+    </type>
 </config>
```

**Comment by convenient** [comment]
Also @engcom-Delta the main thing that needs tested is that calling `indexer:reset` still actually resets the indexer.

The plugin was just a bit of background why we don't want to have duplicated code, explaining my use case, it's just gravy.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1.We should have fresh installation of Magento 2.4 Develop. 
2. Magento instance should be run in debug mode

**Manual testing scenario:**

1. Create before plug-in Model as shown in the below screenshot.(beforeInvalidate method code also updated as per above description)
image
2. Remove the temporary files by using command 
   rm -rf var/* generated/* pub/static/*
3. Perform upgrade, static deploy ,cache flush
4. Run Indexer::reset command
5. Verify the logs updated with before plug-in messages.


**Before:** :heavy_multiplication_x: Logs were not getting updated

**After:** :heavy_check_mark:  Logs  are getting updated.

Screenshot 2022-01-18 at 7 15 38 AM

Since this PR is relevant to before -plugin code fixes in order to update the log files only ,this PR has no impact any other functional issues.Hence there is no additional regression is required.

**Comment by engcom-Delta** [comment]
@magento create issue

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Pull request merged**
