### PR TITLE
[GraphQl][34546] Add product name to error message

### LINKED ISSUE #34546: [GraphQl] Cart error messages are faulty
### Preconditions (*)

1. Magento 2.4.2+

### Steps to reproduce (*)

1. Create a cart
2. Add 2 products to the cart with at least 4 quantities each.
3. Set the quantity of added products below the quantity in the cart.
4. Retrieve cart through graphql 
```
{
  cart(cart_id: "RQg4YPcQX1htp47j6GMpTKRshfY6SVm6") {
    items {
      id
      product {
        name
        sku
        stock_status
      }
      quantity
    }
  }
}
```

### Expected result (*)

1. A error message which tells me which item in the cart causes the error. So that we can give correct feedback to the Customer.
2. A cart with valid values for items.
3. An error message for each issue with the cart.

### Actual result (*)

1.
```
{
  "errors": [
    {
      "message": "The requested qty is not available",
      "extensions": {
        "category": "graphql-input"
      },
      "locations": [
        {
          "line": 7,
          "column": 5
        }
      ],
      "path": [
        "cart",
        "items",
        0
      ]
    }
  ],
  "data": {
    "cart": {
      "items": [
        null,
        {
          "id": "32",
          "product": {
            "name": "Strive Shoulder Pack",
            "sku": "24-MB04",
            "stock_status": "IN_STOCK"
          },
          "quantity": 3
        },
        {
          "id": "33",
          "product": {
            "name": "Joust Duffle Bag",
            "sku": "24-MB01",
            "stock_status": "IN_STOCK"
          },
          "quantity": 4
        }
      ]
    }
  }
}
```
2. In the items node there is a null entry, this only shows up when there is an error. In default Venia this breaks the cart page.
3. I assume the path node in the error node should reference the item it's affecting. It currently points to the above null value.
4. Only the first error of the cart shows up.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR provide more correct feedback message to the Customer for which cart item requested qty is not available

Screenshot 2021-12-15 at 13 58 12

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/34546

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by coderimus** [comment]
@magento run all tests

**Review by glo82145 — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento give me test instance

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B , Functional Tests CE , Functional Tests EE

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Lima** [comment]
Hi @Usik2203 ,

Thanks for your contribution and collaboration.

I have tried to reproduce the issue in `2.4-develop` but issue is not reproducible to me.

Followed below steps :

1. Create a cart
2. Add 2 products to the cart with at least 4 quantities each.
3. Set the quantity of added products below the quantity in the cart from admin.
4. Get cart  details through graphql query:
```
query {
  
  customerCart {
    id
    items {
      uid
      product {
        name
        sku
      }
      quantity
    }
  }
}
```
After running above query I am not getting any error message **`"message": "The requested qty is not available",`** as you have reported.
Below is the screenshot for your reference:
image
If anything missing in above steps kindly provide the information.
Please note that I did PR changes but the response of step 4 was same.

Please test it in latest `2.4-develop` if you are facing any issue kindly provide the information.

Thanks

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Lima** [comment]
@magento run Funcitonal Tests B2B

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Lima** [comment]
Hi @Usik2203 ,

Thanks for your contribution and collaboration.

Kindly provide more information inorder to reproduce the issue.

Thanks

**Comment by engcom-Lima** [comment]
Hi @Usik2203 ,

Thanks for your contribution and collaboration.

Please provide information mentioned in this [comment](https://github.com/magento/magento2/pull/34818#issuecomment-1222056146).

Thanks

**Comment by engcom-Lima** [comment]
Hi @Usik2203 ,

Thanks for your contribution and collaboration.

Closing this PR as there is no update for period of last 14 days. Please feel free to re-open it.

Thanks

**Pull request closed without merging**
