### PR TITLE
[Backport] Changed the mb_convert_encoding in order to allow unescaped ampersands

### PR DESCRIPTION
**Pull request by joris-ati4**
### Description (*)
This fix was discussed in the following issue : https://github.com/magento/magento2/issues/13269
The exception is thrown every time a string with an unescaped & is passed to the escapeHtml method. This exception is written to the exception.log file and floods the logs.

### Fixed Issues (if relevant)

1. magento/magento2#13269: Magento Framework Escaper - Critical log with special symbols

### Manual testing scenarios (*)

1. Create an order comment with an &
2. On the page load an exception is written into the exception.log file
3. The exception is thrown every time a string with an unescaped & is passed to the escapeHtml method.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19884) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @jojotjebaby. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by orlangur** [comment]
@jojotjebaby,
Nowadays all changes must be applied to `2.3-develop` first (see https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules). Please prepare a new pull request, this one should be `on hold` until the latter is merged.

@ihor-sviziev what do you think about such fix?

**Comment by joris-ati4** [comment]
> @jojotjebaby,
> Nowadays all changes must be applied to `2.3-develop` first (see https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules). Please prepare a new pull request, this one should be `on hold` until the latter is merged.
> 

Sorry, I created the Pr for the 2.3-develop branch. https://github.com/magento/magento2/pull/19907

**Comment by ihor-sviziev** [comment]
Hi @jojotjebaby,

As I wrote in https://github.com/magento/magento2/pull/19907#issuecomment-449921679 that this issue was already fixed in `2.3-develop` branch.

Would be great to create backport of that solution to `2.2-develop` branch instead of adding another implementation.

Could you make cherry-pick of original commits and force push your branch?

**Comment by joris-ati4** [comment]
> Hi @jojotjebaby,
> 
> As I wrote in [#19907 (comment)](https://github.com/magento/magento2/pull/19907#issuecomment-449921679) that this issue was already fixed in `2.3-develop` branch.
> 
> Would be great to create backport of that solution to `2.2-develop` branch instead of adding another implementation.
> 
> Could you make cherry-pick of original commits and force push your branch?

Hi @ihor-sviziev ,

I will cherry pick the 2 commits to implement this change to the 2.2 develop branch.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3752](https://jira.corp.magento.com/browse/ENGCOM-3752) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@jojotjebaby thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by sivaschenko** [comment]
Hi @jojotjebaby thanks for the contribution, however, this fix have already been applied to 2.2-develop. Please see https://github.com/magento/magento2/commit/15c7b1ba6db51af92b77896c547d2bc0a60c64a6

Closing the pull request as not actual, please feel free to contact me in case of any questions/comments.

**Pull request closed without merging**
