### PR TITLE
[Fixed-30537] - Bug in the Captcha extension #30537

### LINKED ISSUE #30537: Bug in the Captcha extension
I found a bug in this file : 
vendor/magento/module-captcha/view/frontend/web/js/view/checkout/defaultCaptcha.js
Line 59 : 
`!_.isEmpty(captchaData)[formId] `
It should be 
 `!_.isEmpty(captchaData[formId])`

### Preconditions (*)
Magento 2.4.1
:warning: **Note:** Issue cannot be reproduced on magento 2.4-develop (git version)

### Steps to reproduce (*)
1. Configure CAPTCHA for Checkout/Placing Order
#30537IssueCaptchaSettings
2. Create customer and login
3. Place order
4. Add product cart again
5. Go to checkout page
6. Click on Place Order button
 
### Expected result (*)
1. Order is placed successfully

### Actual result (*)
1. Validation message "Please provide CAPTCHA code and try again" is shown
2. Order cannot be placed
Peek 2020-10-20 14-07

### PR DESCRIPTION
**Pull request by chiranjeevi-cj**
### Description (*)

Replaced the misplaced bracket in the defaultCaptcha.js file

### Fixed Issues (if relevant)
1. Fixes magento/magento2#30537

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @chiranjeevi-cj,
1. According to issue description - this issue isn't reproducing on 2.4-develop branch (info was added during issue verification). Is that correct? Could you check that?
2. In case if issue still reproducing on 2.4-develop - could you also cover your change with automated test?
3. Could you sign Adobe CLA in order to allow accepting PRs from you?


PS: The fix seems correct to me, just not clear why it's not reproducing

**Comment by engcom-Charlie** [comment]
@chiranjeevi-cj could you please provide steps to reproduce the issue on the latest 2.4-develop?
Thank you

**Comment by chiranjeevi-cj** [comment]
Hello @ihor-sviziev,
This issue isn't producing on the 2.4-develop branch.

**Comment by engcom-Charlie** [comment]
@chiranjeevi-cj I have to close this PR because the issue mentioned above doesn't exist on 2.4-develop.
Thank you for your collaboration.

**Comment by ihor-sviziev** [comment]
@chiranjeevi-cj it's really interesting... Could you investigate why it's not reproducing? How it was solved? 
I still believe the following code is not correct and should be fixed:
https://github.com/chiranjeevi-cj/magento2/blob/d483e889d0147611118fa314cdad37bac3b6bd71/app/code/Magento/Captcha/view/frontend/web/js/view/checkout/defaultCaptcha.js#L59

**Pull request closed without merging**
