### PR TITLE
[Forwardport] Refactory to Magento_Backend module class.

### PR DESCRIPTION
**Pull request by tiagosampaio**
Refactory of a class in Magento_Backend module.

### Description
Simple refactory to Magento_Backend module class.
- Turning protected properties into private ones.
- Using dependency injection rather than using Object Manager directly.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### Original PR:
https://github.com/magento/magento2/pull/17101

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @tiagosampaio. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by ihor-sviziev** [comment]
FYI It's better to create up ports just after your PR was merged because original PR might contains some additional fixes and you have to add them. Also forward ports might be easy created by special tool (only when original PR was merged): https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically

**Comment by ihor-sviziev** [comment]
Hi @tiagosampaio,
Please cherry-pick following commit https://github.com/magento/magento2/commit/9ff89837e9f418770d4f468faccab7e146ad60e2

**Comment by tiagosampaio** [comment]
Hi @ihor-sviziev. I had to cherry-pick the commit a1339ba5eba4af7705ccbbaa8c1b2b666f878219 before yours.

That should be fine now.

Thanks.

**Comment by ihor-sviziev** [comment]
@tiagosampaio thx, will review this PR just when original PR will be merged

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-2714](https://jira.corp.magento.com/browse/ENGCOM-2714) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @tiagosampaio. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Pull request merged**
