### PR TITLE
Correct setting "@tab-content__border-top-status" variable in Blank t…

### LINKED ISSUE #14999: Changing @tab-content__border variable has no effect in Blank theme
### Preconditions
Any Magento 2
FE theme inherited from Magento/Blank

### Steps to reproduce
In `Custom/theme/web/css/source/_theme.less` set less variables to:
@tab-content__border-top-status: false;
@tab-content__border: 1px solid #000;

### Expected result
Tabs content has border

### Actual result
Tabs content has no border

### What causes the issue
[web/css/source/_sections.less](https://github.com/magento/magento2/blob/2.2-develop/app/design/frontend/Magento/blank/web/css/source/_sections.less#L24) calls `.lib-data-tabs()` mixin with `@_tab-content-border-top-status: true` argument, so `@tab-content__border-top-status` variable isn't used in  `.lib-data-tabs()`

### Solution
1. Remove `@_tab-content-border-top-status: true` argument in [web/css/source/_sections.less](https://github.com/magento/magento2/blob/2.2-develop/app/design/frontend/Magento/blank/web/css/source/_sections.less#L24) (as it's done in [Magento/Luma](https://github.com/magento/magento2/blob/2.2-develop/app/design/frontend/Magento/luma/web/css/source/_sections.less#L66));
2. Add `@tab-content__border-top-status: true` in [web/css/source/_variables.less](https://github.com/magento/magento2/blob/2.2-develop/app/design/frontend/Magento/blank/web/css/source/_variables.less)

### Workaround
[Create](https://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-guide/css_quick_guide_approach.html#structured_changes) `Custom/theme/web/css/source/_sections_extend.less` with:

```
.media-width(@extremum, @break) when (@extremum = 'min') and (@break = @screen__m) {
    .product.data.items {
        > .item.content {
            ._lib-tab-content-border(
                @_tab-content-border-top-status: @tab-content__border-top-status
            );
        }
    }
}
```

### PR DESCRIPTION
**Pull request by denistrator**
…heme, fixes #14999

### Fixed Issue

magento/magento2 #14999: Changing @tab-content__border variable has no effect in Blank theme

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15000) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=15000) before we can accept your contribution.<br/>

**Comment by sidolov** [comment]
Hi @denistrator  , please, sign CLA, otherwise, we can't process your pull request

**Comment by denistrator** [comment]
@sidolov hello, I signed. Does the task still need update?

**Comment by ihor-sviziev** [comment]
Hi @denistrator,
This issue was [already fixed](https://github.com/magento/magento2/issues/14999#issuecomment-397028511) in `2.2-develop` branch. I'm closing this PR as not actual anymore.

**Pull request closed without merging**
