### PR TITLE
2.0

### PR DESCRIPTION
**Pull request by mikeshatch**
### Description 

I fixed the broken link to Bugcrowd's Researcher Account and edited the text link for clarity. 

**Changes:**

1. https://bugcrowd.com/magento ==> https://bugcrowd.com/user/sign_up
2. there ==> Bugcrowd Researcher Account

### Contribution checklist 
 - [x ] Pull request has a meaningful description of its purpose
 - [x ] All commits are accompanied by meaningful commit messages

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21905) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=21905) before we can accept your contribution.<br/>**0** out of **7** committers have signed the CLA.<br/><br/>:x: ameysar<br/>:x: RomaKis<br/>:x: rganin<br/>:x: OlgaVasyltsun<br/>:x: wert2all<br/>:x: sergiosemov<br/>:x: zakdma

**Comment by magento-engcom-team** [comment]
Hi @mikeshatch

Unfortunately, we cannot accept Pull Requests from branches created in `magento2` repository.
Please use your own fork as a base for this Pull Request.

Thank you.

**Comment by magento-engcom-team** [comment]
Hi @mikeshatch. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by mikeshatch** [comment]
Whoa. I don't know what happened here. But it wasn't accepting my pull request, and then it combined my pull request with everyone else's.

**Pull request closed without merging**
