### PR TITLE
#13685: Upgrading compatibility jQuery with 3.3.1

### PR DESCRIPTION
**Pull request by kirmorozov**
### Description
Cherry-picked changes for jQuery 3 compatibility from https://github.com/magento/magento2/pull/14556

### Fixed Issues (if relevant)

1. magento/magento2#13685: Incompatibilies with jQuery 3
2. ...

### Manual testing scenarios
1. I can checkout without any problems
2. I can use admin without any problems

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14637) <br/>All committers have signed the CLA.

**Review by omiroshnichenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @omiroshnichenko, thank you for the review.
[ENGCOM-1259](https://jira.corp.magento.com/browse/ENGCOM-1259) has been created to process this Pull Request

**Comment by kirmorozov** [comment]
Is there way to run Travis?

**Comment by magento-engcom-team** [comment]
Hi @kirmorozov. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.3.0 release.

**Pull request merged**
