### PR TITLE
32846: Remove modernizr library from lib

### PR DESCRIPTION
**Pull request by karyna-t**
### Description (*)
Removing modernizr.js library and related files.

The only file which uses modernizr.js lib file is _lib/web/modernizr/modernizr.details.js_
In this file, there is an additional function for Modernizr which checks the availability of the _&lt;details&gt;_ feature support.
At present time, [&lt;details&gt;](https://caniuse.com/details) is supported by all [browsers that Magento 2.4 supports](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#supported-browsers).
Considering this, the library can be removed as there are no more usages of _lib/web/modernizr/modernizr.js._

### Fixed Issues (if relevant)
1. Fixes magento/magento2#32846

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by karyna-tsymbal-atwix** [comment]
@magento run all tests

**Comment by karyna-tsymbal-atwix** [comment]
@magento run Unit Tests

**Comment by karyna-tsymbal-atwix** [comment]
@magento run all tests

**Comment by karyna-tsymbal-atwix** [comment]
@magento run WebAPI Tests

**Comment by karyna-tsymbal-atwix** [comment]
@magento run all tests

**Comment by karyna-tsymbal-atwix** [comment]
@magento run Functional Tests B2B

**Comment by karyna-tsymbal-atwix** [comment]
@magento run Unit Tests, Functional Tests B2B

**Comment by karyna-tsymbal-atwix** [comment]
@magento run WebAPI Tests

**Review by andrewbess — APPROVED** [review]
Hello @karyna-tsymbal-atwix 
Your changes are approved.
Thank you for your job.

**Review by Den4ik — APPROVED** [review]

**Pull request merged**
