### PR TITLE
[Backport] Add/update newsletter messages in translation file

### PR DESCRIPTION
**Pull request by arnoudhgz**
### Original Pull Request 
 https://github.com/magento/magento2/pull/19050
Original PR: #18932 (was closed by me because of out-of-sync fork) 

### Description (*)
The messages in the Newsletter module were update, but the messages in the translation files have been forgotten.

### Manual testing scenarios (*)
Compare the messages in app/code/Magento/Newsletter/Controller/Manage/Save.php with the i18n file

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @arnoudhgz. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by arnoudhgz** [comment]
I know it is a cleanup, but we really need these translations in 2.2 :+1:

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3414](https://jira.corp.magento.com/browse/ENGCOM-3414) has been created to process this Pull Request

**Comment by orlangur** [comment]
@arnoudhgz I would rather treat it as a bug - inability to localize something is a severe issue.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3414](https://jira.corp.magento.com/browse/ENGCOM-3414) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @arnoudhgz. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.

**Pull request merged**
