### PR TITLE
Backend: User Role Checkbox alignement.

### PR DESCRIPTION
**Pull request by suryakant-krish**
### Description (*)

Backend: User Role Checkbox alignement.
### Fixed Issues (if relevant)

This is direct pull request as per Magento reviewer suggested,

### Manual testing scenarios (*)

1.  Login into admin panel > System > User Roles > Click on Adminstrator User > Role User > Look checkbox alignment.

2. Actual Result
actual-result

3. Expected Result
expected-result

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @suryakant-krish. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by SyntaxKay** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @speedy008, here is your [Magento instance](https://i-20237-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20237-2-3-develop.instances.magento-community.engineering/admin](https://i-20237-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3870](https://jira.corp.magento.com/browse/ENGCOM-3870) has been created to process this Pull Request

**Review by SyntaxKay — APPROVED** [review]

**Comment by suryakant-krish** [comment]
@magento-engcom-team,

Please review this PR.

**Pull request merged**
