### PR TITLE
33337: eliminated laminas-i18n and laminas-filter dependency

### PR DESCRIPTION
**Pull request by korovitskyi**
### Description (*)

Eliminated laminas-i18n and laminas-filter dependency
Also it was created the private `filter` method to proceed with the native logic process.
Reopened by https://github.com/magento/magento2/pull/33362
### Fixed Issues (if relevant)

1. Fixes magento/magento2#33337

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/557
https://github.com/magento/partners-magento2b2b/pull/578

### CODE REVIEW

**Comment by korovitskyi** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@korovitskyi Looks like it was bug with branches tracking. As I see now builds showing correct in original PR. I'm close this PR

**Review by Den4ik — APPROVED** [review]

**Review by eduard13 — APPROVED** [review]

**Review by andrewbess — APPROVED** [review]
Hello @korovitskyi 
Thank you for your contribution.
Your changes are approved ✅

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@andrewbess As I see failed unit tests related to changes and look like require related PRs

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@andrewbess @korovitskyi, I see in the https://github.com/magento/magento2/commit/1e494a801adab41a910e822bf06e19307aad6a61 was introduced special wrapper class for the `\NumberFormatter`. I think we should NOT use such a wrapper in all cases. What do you think?

**Comment by andrewbess** [comment]
Hello @ihor-sviziev 
Thank you for your notice.
Personally I'm not sure that this is a good idea to use this wrapper.

**Pull request merged**
