### PR TITLE
Product should be assigned to option while option is assigned to product.

### PR DESCRIPTION
**Pull request by p-bystritsky**
### Description (*)

Product is assigned to option while using Product::addOption method 
https://github.com/magento/magento2/blob/2d09485b8e00d149e936412dc0f7baa78a928931/app/code/Magento/Catalog/Model/Product.php#L1977-L1984
Meanwhile Product::addOption method has no such assignment https://github.com/magento/magento2/blob/2d09485b8e00d149e936412dc0f7baa78a928931/app/code/Magento/Catalog/Model/Product.php#L2032-L2036 

### Fixed Issues (if relevant)

1. None

### Manual testing scenarios (*)

1. None

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, here is your [new Magento instance](https://pr-28301.instances.magento-community.engineering).
Admin access: [https://pr-28301.instances.magento-community.engineering/admin_f478](https://pr-28301.instances.magento-community.engineering/admin_f478)
Login: `8ece0f81` Password: `7ea740f95290`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by p-bystritsky** [comment]
@magento run all tests

**Comment by p-bystritsky** [comment]
@magento run all tests

**Comment by p-bystritsky** [comment]
@magento run Functional Tests B2B

**Comment by lenaorobei** [comment]
Closing in favor of https://github.com/magento/magento2/pull/22917 revert.

**Pull request closed without merging**
