### PR TITLE
 Show exception message during SCD failure

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
Add full exception message when SCD fails

### Fixed Issues (if relevant)
1. magento/magento2#22882: Static content deploy - Don't shows error message, just stack trace 

### Manual testing scenarios (*)
1. see magento/magento2#22882

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @ihor-sviziev. Thanks for collaboration. Please fix static tests.

**Comment by ihor-sviziev** [comment]
Hi @VladimirZaets,
Static tests complains about lines that I didn't changed. I think it could be fixed during processing PR.

**Comment by ihor-sviziev** [comment]
Hi @VladimirZaets,
I fixes static tests. Please re-check it again.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5184](https://jira.corp.magento.com/browse/ENGCOM-5184) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
