### PR TITLE
Replace repetitive actions with Action Groups in StorefrontConfigurableProductGridViewTest and StorefrontConfigurableProductListViewTest

### LINKED ISSUE #34311: [Issue] Replace repetitive actions with Action Groups in StorefrontConfigurableProductGridViewTest and StorefrontConfigurableProductListViewTest
This issue is automatically created based on existing pull request: magento/magento2#34051: Replace repetitive actions with Action Groups in StorefrontConfigurableProductGridViewTest and StorefrontConfigurableProductListViewTest

---------

### Description (*)
Tests are refactored according to the best practices followed by MFTF.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
Tests are refactored according to the best practices followed by MFTF.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#34311: Replace repetitive actions with Action Groups in StorefrontConfigurableProductGridViewTest and StorefrontConfigurableProductListViewTest

### CODE REVIEW

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests CE

**Comment by kate-kyzyma** [comment]
@magento run Functional Tests CE

**Review by Den4ik — APPROVED** [review]
✅ Looks good

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9232](https://jira.corp.magento.com/browse/ENGCOM-9232) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by eduard13 — APPROVED** [review]

**Pull request merged**
