### PR TITLE
[Forwardport] "Multiple Select" product attributes do not render HTML tags on the storefront view

### PR DESCRIPTION
**Pull request by nmalevanec**
### Original Pull Request
https://github.com/magento/magento2/pull/15687

Issue fix for: https://github.com/magento/magento2/issues/15393
1. Fixed the check for allowed HTML tags OR wysiwyg for textarea attribute types.
2. Fix for options so that they can be rendered as HTML as well.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @nmalevanec. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by ishakhsuvarov** [comment]
Hi @nmalevanec 
Original Pull request seems to include updates to the test which are not part in this port. Could you please make sure that test coverage isn't decreased?

Thanks

**Comment by nmalevanec** [comment]
@ishakhsuvarov these test changes already exist in 2.3-develop.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-2887](https://jira.corp.magento.com/browse/ENGCOM-2887) has been created to process this Pull Request

**Comment by sidolov** [comment]
Hi @nmalevanec , we cannot reproduce this issue on 2.3-develop.

**Manual testing scenario:**

1. Create a dropdown / multiselect attribute
2. One or more of the values contain html tags (<strong>test value</strong>)
3. "allow HTML on frontend" and "use in product listing" are set to "Yes"
4. Add this new attribute to an attribute set
5. Create a product based on this attribute set and select at least one of the values containing HTML tags
6. Open Product Page on the frontend.

**Result**
Attribute option didn't contain HTML tags and is displayed as test value



I'm closing this PR as not relevant.
Thank you for the contribution!

**Pull request closed without merging**
