### PR TITLE
Add unique key on eav_attribute_option_value table

### LINKED ISSUE #24718: Missing unique key on eav_attribute_option_value table
This is similar to #24581 but for the table `eav_attribute_option_value`
### Summary (*)
The table `eav_attribute_option_value` does not have a unique index on the column pair (`option_id`, `store_id`).  
There is no reason for an option to have 2 values for the same store so this should be restricted.  

_Also layered navigation disappears on frontend._

**Relates issues:**
https://github.com/magento/magento2/issues/24581 
https://github.com/magento/magento2/issues/24718

### Examples (*)
Same as #24581, if by any faulty code an option gets 2 values for the same store view this causes a lot of issues when editing product / attributes / maybe others.
### Proposed solution
add a unique key on the column pair (`option_id`, `store_id`) on the table `eav_attribute_option_value`

```
    <table name="eav_attribute_option_value">
       ......
        <constraint xsi:type="unique" referenceId="EAV_ATTRIBUTE_OPTION_VALUE_OPTION_ID_STORE_ID_UNIQUE">
            <column name="store_id"/>
            <column name="option_id"/>
        </constraint>
    </table>
```

### PR DESCRIPTION
**Pull request by ihor-sviziev**
This PR re-adds changes from https://github.com/magento/magento2/pull/24720 after they [were reverted due to missing approval for backward incompatible changes](https://github.com/magento/magento2/issues/28703#issuecomment-645357575).

### Description (*)

I believe we SHOULD add this index even if it's backward incompatible change as duplicated data in this table causing a lot of issues, we're having report page when trying to load attribute option values, explanation is here:
https://github.com/magento/magento2/issues/24718#issuecomment-723689533
image

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/24718

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by davidverholen — DISMISSED** [review]

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Before:**
:x: Error is shown when retrieving duplicate values of attribute options 
image
image

**After:**
:heavy_check_mark: No possibility to set duplicate values for attribute options 
image
:heavy_check_mark: Was checked saving attribute option values for different store views works as before
image
image

**Comment by engcom-Charlie** [comment]
**Semantic Version Checker** failed because of Unique key was added. It needs to approve.

**Comment by ihor-sviziev** [comment]
Seems like this is big change, we need to accept it in 2.5 release line

**Comment by gabrieldagama** [comment]
Approval ticket - https://jira.corp.magento.com/browse/MC-37068

**Comment by ihor-sviziev** [comment]
Just removed the 2.5 milestone due to clear description that website will be broken in case of duplicated values.
Here is quite good and clear explanation that should be reviewed during approval process: 
https://github.com/magento/magento2/issues/24718#issuecomment-723689533

**Comment by ihor-sviziev** [comment]
Moved back to correct status

**Comment by sidolov** [comment]
Hi @ihor-sviziev , yes, we will proceed with PR according to the priority, please, notice that the current PR has P3 priority and will be postponed until all high priority PRs will be processed.

**Comment by ihor-sviziev** [comment]
@sidolov @sivaschenko looks like when bot changes priority/severity labels - bot moves PR automatically to wrong status. Could you check that?

Note: i moved it back

**Comment by ihor-sviziev** [comment]
Added "Risk: low" label as in case if we have duplicated data - Magento fails with an exception (report page in production mode)

**Comment by engcom-Alfa** [comment]
@magento run Semantic Version Checker

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests, Integration Tests, Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Echo** [comment]
For SVC approval we have raised internal [JIRA](https://jira.corp.adobe.com/browse/AC-6984). Hence we are moving it to pending approval.

**Comment by engcom-Charlie** [comment]
We have got the approval for our approval [JIRA](https://jira.corp.adobe.com/browse/AC-6984) for Semantic Version Checker failure. 

Moving it to back to Extended Testing to get the latest code merge and get the QA done again.

Thank you!

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento Functional Tests B2B

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B , Functional Tests CE

**Comment by engcom-Lima** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**
- Verify in the `eav_attribute_option_value` table the duplicate value of the `option_id`

**Before:** :heavy_multiplication_x: 
Screenshot 2023-09-13 at 11 25 39 AM
**Frontend:**
Screenshot 2023-09-13 at 11 24 55 AM

**After:** :heavy_check_mark:  
Screenshot 2023-09-13 at 12 02 03 PM

Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Unit Tests,Static Tests,Integration Tests,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Unit Tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Echo** [comment]
Functional Tests B2B failure are different on last two run on same commit.
Run1
36976-ce

Run2
28796-b2b2


We have got the approval for our approval [JIRA](https://jira.corp.adobe.com/browse/AC-6984) for **`Semantic Version Checker failure`**.

**Pull request merged**
