### PR TITLE
Solution for other options values delete issue.

### PR DESCRIPTION
**Pull request by mayankzalavadia**
### Description

A solution for other options values deletes issue.

### Fixed Issues (if relevant)

1. magento/magento2#13425: Delete one value from Select type custom option and it's deleted all other custom option values which are bottom of that custom option.

### Manual testing scenarios

1.  Create a new product or edit existing product Add multiple Custom options having the type (Dropdown, multiple select, Radio Button, CheckBox)
2.  Save the Product
3. Open the product, delete one value from first select type custom option.
4. save the product
5. Check all other custom options values are not deleted which are bottom of that custom options.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by Jeroenll** [comment]
Isn't this already fixed in https://github.com/magento/magento2/commit/ff422002cd2d977c3b10ac512c557f58e1cba5c6 ?

**Comment by okorshenko** [comment]
Hi @JeroenVanLeusden 
Thank for pointing to the commit. Our QA confirmed that the issue already fixed. 
Closing this PR

**Comment by oleksii-lisovyi** [comment]
Hi @JeroenVanLeusden. if you see the commit https://github.com/magento/magento2/commit/ff422002cd2d977c3b10ac512c557f58e1cba5c6 you mentioned more carefully, you can find a bug with missed opening bracket for the foreach structure, so that fix definitely couldn't work correctly for @okorshenko if it was used without modifications as a patch, for example.

I already tried to fix the issue with it and we got an error because of the missed bracket. Currently fixing the issue with overriding related model with a corrected fix from https://github.com/magento/magento2/commit/ff422002cd2d977c3b10ac512c557f58e1cba5c6.

**Comment by ihor-sviziev** [comment]
@oleksii-lisovyi there was another commit: https://github.com/magento/magento2/commit/aa7da3084d17f27b4f44c8b816a1ffa4c3666682 together

**Pull request closed without merging**
