### PR TITLE
Fix order date format in admin grid

### LINKED ISSUE #5651: Purchase date on admin screen is always *:07:00
1. Go to the admin screen and view the first page of Orders.
2. Note that the date/time under the heading Purchase Date is always *:07:00
3. Time stamp appears correct in REST API return values ('created_at' attribute).

### PR DESCRIPTION
**Pull request by mikeymike**
Resolves #5651 where the date format was showing the two digit month for the minutes.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=6785) <br/>All committers have signed the CLA.

**Comment by PascalBrouwers** [comment]
Can you resubmit this pull request? Perhaps then it will go through the build successfully.

**Comment by mikeymike** [comment]
@PascalBrouwers Ideally when a Magento core dev reviews the PR (hopefully soon) they will just hit rebuild in Travis 

@vasiliyseleznev you have any timescales of when someone will take a look at this?

**Comment by vrann** [comment]
The same contribution is being accepted under #8336

**Comment by nigelcopley** [comment]
have this issue in 2.15 after upgrade from 2.14

**Pull request closed without merging**
