### PR TITLE
Fix issue #29932 "only_x_left_in_stock returns null if inventory is 0"

### LINKED ISSUE #29932: only_x_left_in_stock returns null if inventory is 0
### Preconditions (*)
1. 2.4.0
2.

### Steps to reproduce (*)
1. Set only_x_left_in_stock to 3
2. Configure one product with 0 inventory but stock status in_stock

### Expected result (*)
1. only_x_left_in_stock = 0
2.

### Actual result (*)
1. only_x_left_in_stock = null
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by codynguyen1**
### Description (*)

Fix issue with OnlyXLeftInStockResolver when quantity is 0.

Also fix to return the right quantity value.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29932

### Manual testing scenarios (*)

1. Set only_x_left_in_stock to 3
2. Configure one product with 0 inventory but stock status in_stock

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by codynguyen1** [comment]
@magento run all tests

**Comment by codynguyen1** [comment]
@magento run all tests

**Comment by codynguyen1** [comment]
@magento run all tests

**Comment by rogyar** [comment]
Hi @codynguyen1. Thank you for your fix. All changes and bug fixes we provide to the GraphQL API we usually cover by API-functional tests. It's awesome that you've created the unit test, it's very useful as well. But I would ask you to create a simple API-functional test that emulates "steps to reproduce" and checks the final result.

Thank you!

**Comment by codynguyen1** [comment]
@rogyar I have added a function test for this scenario.
Thanks!

**Comment by codynguyen1** [comment]
@magento run all tests

**Comment by codynguyen1** [comment]
@magento run all tests

**Comment by codynguyen1** [comment]
@magento run all tests

**Comment by codynguyen1** [comment]
@magento run all tests

**Comment by codynguyen1** [comment]
@magento run all tests

**Comment by codynguyen1** [comment]
@magento run WebAPI Tests

**Comment by codynguyen1** [comment]
@magento run all tests

**Comment by codynguyen1** [comment]
Hi @rogyar, the source code passed testing, but it's showing error from somewhere else (customer image upload), please help me with this, thank you!

**Review by rogyar — APPROVED** [review]
The failing tests are not related to the changes in this PR.

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8238](https://jira.corp.magento.com/browse/ENGCOM-8238) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests CE, Functional Tests EE, Unit Tests

**Pull request merged**
