### PR TITLE
Fix issue 21126 : Import design break issue resolved

### PR DESCRIPTION
**Pull request by SyntaxKay**
### Description (*)

Backend Import behavior design break
### Fixed Issues (if relevant)

1.magento/magento2#21126:  Import design break issue resolved

### Manual testing scenarios (*)

1.Login to backend > system > import
2.select any > Entity Type and without selecting any option click on check data

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by torhoehn** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @torhoehn, here is your [new Magento instance](https://pr-21128.instances.magento-community.engineering).
Admin access: [https://pr-21128.instances.magento-community.engineering/admin](https://pr-21128.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by torhoehn — APPROVED** [review]
✅ Checked manually in Backend.

**Comment by magento-engcom-team** [comment]
Hi @torhoehn, thank you for the review.
[ENGCOM-4255](https://jira.corp.magento.com/browse/ENGCOM-4255) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @speedy008 there are multiple issues introduced by this pull request:

1. Asterisk signs are missing on the Import page:
image
2. Asterisk signs are shifted to the bottom on other admin pages, i.e. "Add new customer"
image
3. "Fields enclosure" checkbox and "Select File to Import" button are shifted to the top on Import page:
image

Please ensure that selectors you are using to fix a specific issue are as specific as possible to avoid global impact in the admin panel.

**Comment by SyntaxKay** [comment]
@sivaschenko The solution I have provided is not affected the UI screenshot you have provided. I have check into my local instance. This issue are separate from my issue.

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [new Magento instance](https://pr-21128.instances.magento-community.engineering).
Admin access: [https://pr-21128.instances.magento-community.engineering/admin](https://pr-21128.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sivaschenko** [comment]
Hi @speedy008 , please check at the test instance that I've launched

**Comment by sivaschenko** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [Magento instance](https://i-21128-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21128-2-3-develop.instances.magento-community.engineering/admin](https://i-21128-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by SyntaxKay** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @speedy008, here is your [new Magento instance](https://pr-21128.instances.magento-community.engineering).
Admin access: [https://pr-21128.instances.magento-community.engineering/admin](https://pr-21128.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by abrarpathan19** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @abrarpathan19. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @abrarpathan19, here is your [new Magento instance](https://pr-21128.instances.magento-community.engineering).
Admin access: [https://pr-21128.instances.magento-community.engineering/admin](https://pr-21128.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by abrarpathan19** [comment]
> Hi @speedy008 there are multiple issues introduced by this pull request:
> 
> 1. Asterisk signs are missing on the Import page:
>    image
> 2. Asterisk signs are shifted to the bottom on other admin pages, i.e. "Add new customer"
>    image
> 3. "Fields enclosure" checkbox and "Select File to Import" button are shifted to the top on Import page:
>    image
> 
> Please ensure that selectors you are using to fix a specific issue are as specific as possible to avoid global impact in the admin panel.

Hello @sivaschenko, Please review below screenshot and I have tested there is no issue with design as per your above screenshots. 
http://prntscr.com/mnnr8b 
http://prntscr.com/mnnrls

**Comment by SyntaxKay** [comment]
@sivaschenko i have resolved the issue please review .

**Comment by omiroshnichenko** [comment]
Hi @speedy008, the problem was not in styles. The real problem is in [validation.js](https://github.com/magento/magento2/blob/2.3-develop/lib/web/mage/validation.js#L1845-L1872) in method errorPlacement. You can see that the error message appears right after the field element. To fix this problem correctly, you should update errorPlacement method and add 
```
//logic for select with tooltip in after element
if (element.next().find('.tooltip').length) {
    errorPlacement = element.next();
}
```
before 
```
errorPlacement.after(error);
```

**Comment by sidolov** [comment]
@speedy008 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-5376](https://jira.corp.magento.com/browse/ENGCOM-5376) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
