### PR TITLE
issue -#22591

### PR DESCRIPTION
**Pull request by irajneeshgupta**
### Fixed Issues (if relevant)

1. magento/magento2#22591: Orders not set to complete after order shipped

### Manual testing scenarios (*)

Magento Open Source 2.2.8
After order processing we have a custom status PostNL (processing), this status will remain until we fully shipped the order.
Update order shipment and tracking by API
Order not set to complete
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by irajneeshgupta** [comment]
#dmcindia1

**Comment by dmytro-ch** [comment]
The related issue is not confirmed and pending updates.

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [Magento instance](https://i-22730-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22730-2-2-develop.instances.magento-community.engineering/admin](https://i-22730-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dmytro-ch** [comment]
Hi @irajneeshgupta, the current solution looks like a workaround.
Could you please provide some details about your solution?
e.g. What is the root reason of the issue?
How does your solution fix the problem?



Thank you!

**Comment by VladimirZaets** [comment]
Hi @irajneeshgupta. The branch `2.2-develop` will be closed for contribution from **July 15, 2019**. Please finish all your Pull Requests till this date, otherwise, they will be closed.
Thanks for collaboration.

**Comment by sivaschenko** [comment]
Hi @irajneeshgupta can you please forward port the pull request to 2.3-develop branch.

**Comment by orlangur** [comment]
Closing as there is no corresponding PR targeting `2.3-develop` branch created.

**Pull request closed without merging**
