### PR TITLE
Fix first day of week in dob customer field

### PR DESCRIPTION
**Pull request by joachimVT**
### Description
The frontend datepicker control for the DOB field is not localized: month names, day names and week start date are all using en_US. This pull request fixes this using the first day of the week set in the back office (core_config_data)

### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/6350

### Manual testing scenarios

1. Admin > Settings > Configuration > Customer > Customer Configuration > "Show Date of Birth: Require"
2. Admin > Settings > Configuration > General > Locale Options > "First Day of Week: Monday"
3. clear cache / rebuild static assets if needed
4. In the frontend, edit or create your account and use the datepicker of the DoB control

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=11057) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=11057) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: joachimVT<br/>:x: paliarush<br/>:x: viktym

**Comment by dmanners** [comment]
@joachimVT it looks like you have 2 extra commits on this branch that I dont think relate to the bug fix. (c3ea1f55aa21ca14796118128a302d4f4b139450, 0c0393d4ebe9dd216911c773e4e5d274f973d716) Can you clean these off the PR or are they suppose to be there?

**Comment by joachimVT** [comment]
@dmanners I don't know why these 2 extra commits are on my branch. How could I clean these off ?

**Comment by dmanners** [comment]
@joachimVT running `git reset --hard HEAD~2` and then doing a forced pushed should be enough for you. Just make sure you are on the right branch before you do it. If that does not do it for you a rebase will work but the reset is probably the better option here. See https://stackoverflow.com/a/1338744/1141023 for some more information on the topic.

**Comment by dmanners** [comment]
Actually is this branch created from develop or develop2.2? The PR is for the 2.2 branch so if the branch was created from develop you might get some different commits. Options would be either to recreate the branch from 2.2 and cherry-pick your commit onto your new branch or running a git reset to remove the two other commits.

**Comment by joachimVT** [comment]
@vrann @dmanners git reset hard isn't working for me. Should I create a new pull request with the same modifications ? So that the 2 extra commits are gone in my new pull request ?

**Comment by vrann** [comment]
@dmanners @joachimVT sorry for the confusion, two additional commits appeared because of the issue in our infrastructure (branch was force-pushed at some point) Now it is resolved and we can accept your fix as is.

**Comment by okorshenko** [comment]
Hi @joachimVT could you please accept the invite in the GitHub to join magento team?

**Comment by joachimVT** [comment]
Hi @okorshenko I didn't receive any invite in Github ?

**Pull request merged**
