### PR TITLE
Fix Argument 6 missing in SaveImageInformation

### LINKED ISSUE #31167: Argument 6 missing in SaveImageInformation
### Preconditions (*)
1. Magento 2.4.1 with PHP 7.4

### Steps to reproduce (*)
1. Use module (Firebear import) to import images with the command line

### Expected result (*)
1. Images are imported

### Actual result (*)
Type Error occurred when creating object: Magento\MediaGalleryIntegration\Plugin\SaveImageInformation, Argument 6 passed to Magento\MediaGalleryIntegration\Plugin\SaveImageInformation::__construct() must be of the type array, null given, called in /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121

### Cause
https://github.com/magento/magento2/pull/29399

### Solution
The imageExtensions argument is defined in the Magento/MediaGalleryIntegration/etc/adminhtml/di.xml file while the SaveImageInformation class could also be used in CLI. Therefore the imageExtensions argument should be moved to Magento/MediaGalleryIntegration/etc/di.xml (without the adminhtml)

CC @firebearstudio

### PR DESCRIPTION
**Pull request by JosephMaxwell**
### Description (*)
When triggering product imports by CLI (or any area outside of the `adminhtml` area), an error was thrown:
```
Type Error occurred when creating object: Magento\MediaGalleryIntegration\Plugin\SaveImageInformation, Argument 6 passed to Magento\MediaGalleryIntegration\Plugin\SaveImageInformation::__construct() must be of the type array, null given, called in /srv/releases/build-907238634/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121
```

This was because the `imageExtensions` value was _only_ set in the `adminhtml` area. Moving to `global` will solve the problem.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31167

### Manual testing scenarios (*)

1. Import a CSV file (this should work from the admin panel before and after the change).
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by gabrieldagama** [comment]
@magento run all tests

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @JosephMaxwell, thanks for your contribution! Since all our changes must be covered with some kind of automated tests, can we try to cover this one as well? Maybe Integration tests would be suitable in this case.

Thanks!

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
Hi @JosephMaxwell, will help with the test coverage.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by sidolov** [comment]
Hi @JosephMaxwell , could you please provide more details on the issue? 
It looks weird to me since the plugin and its configuration is declared in scope of adminhtml area and in case you call any method from `Magento\Framework\File\Uploader` outside of it you should not get any error.

**Comment by engcom-Foxtrot** [comment]
@JosephMaxwell PR closed due to inactivity. Feel free to reopen it if you have any updates.

**Comment by ashvinimarwal** [comment]
Thanks @JosephMaxwell 
Problem solved by adding the following code on the global di.xml file.

`    <type name="Magento\MediaGalleryIntegration\Plugin\SaveImageInformation">
        <arguments>
            <argument name="imageExtensions" xsi:type="array">
                <item name="jpg" xsi:type="string">jpg</item>
                <item name="jpeg" xsi:type="string">jpeg</item>
                <item name="gif" xsi:type="string">gif</item>
                <item name="png" xsi:type="string">png</item>
            </argument>
        </arguments>
    </type>`

**Pull request closed without merging**
