### PR TITLE
Fix page cache controller block renderer error handling

### LINKED ISSUE #29665: [Issue] Fix page cache controller block renderer error handling
This issue is automatically created based on existing pull request: magento/magento2#28836: Fix page cache controller block renderer error handling

---------
### Description (*)
Private content handling page cache controller has poor error handling. It does not handle invalid JSON and undefined offset errors. This may not be a problem normally as this controller has limited usage but it may generate a large number of exceptions in case, for example, a security scanner generates requests with random parameters string.
* When "originalRequest" parameter has invalid JSON, the controller returns an empty array. No errors are logged.
* When "originalRequest" parameter does not have a required parameter, "Undefined index" unhandled exception is thrown.

The fix includes the next:
* Improvement to the JSON decoding. In case of an invalid JSON, an error is logged to the exception log and request forwarded to "noroute".
* Improvement to the original request parameters handling. In case of any parameter missing, the request is forwarded to "noroute".
### Manual testing scenarios (*)
1. Try to pass the parameter string with the missing required parameter for the original request.
a. Request the next URL in your browser `www.your_magento_domain/page_cache/block/render/id/111/?ajax=true&blocks=["csblock_category_content_top","csblock_category_menu_bottom","csblock_category_menu_top","csblock_category_page_bottom","csblock_category_sidebar_top","user.links.template"]&handles=["default","catalog_category_view","catalog_category_view_type_layered","catalog_category_view_id_2863","restriction_privatesales_mode"]&originalRequest={"route":"catalog","controller":"category","action":"view"}&version=df28718726589060aaf9bb4f61f5e923`
b. You'll get an exception "Notice: Undefined index: uri"
c. Expected result - an error is logged to the exception log and you get redirected to the "noroute" (404 Not Found) page.
2. Try to pass invalid JSON string in originalRequest parameter
a. Request the next URL in your browser `www.your_magento_domain/page_cache/block/render/id/111/?ajax=true&blocks=["csblock_category_content_top","csblock_category_menu_bottom","csblock_category_menu_top","csblock_category_page_bottom","csblock_category_sidebar_top","user.links.template"]&handles=["default","catalog_category_view","catalog_category_view_type_layered","catalog_category_view_id_2863","restriction_privatesales_mode"]&originalRequest={"route":"catalog","controller":"category","action"%%%&&&&:"view"}&version=df28718726589060aaf9bb4f61f5e923`
b. You'l get an empty array as a response. No errors are logged to the exception.log
c. Expected result - an error is logged to the exception log and you get redirected to the "noroute" (404 Not Found) page.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by kodubovik**
### Description (*)
Private content handling page cache controller has poor error handling. It does not handle invalid JSON and undefined offset errors. This may not be a problem normally as this controller has limited usage but it may generate a large number of exceptions in case, for example, a security scanner generates requests with random parameters string.
* When "originalRequest" parameter has invalid JSON, the controller returns an empty array. No errors are logged.
* When "originalRequest" parameter does not have a required parameter, "Undefined index" unhandled exception is thrown.

The fix includes the next:
* Improvement to the JSON decoding. In case of an invalid JSON, an error is logged to the exception log and request forwarded to "noroute".
* Improvement to the original request parameters handling. In case of any parameter missing, the request is forwarded to "noroute".
### Manual testing scenarios (*)
1. Try to pass the parameter string with the missing required parameter for the original request.
a. Request the next URL in your browser `www.your_magento_domain/page_cache/block/render/id/111/?ajax=true&blocks=["csblock_category_content_top","csblock_category_menu_bottom","csblock_category_menu_top","csblock_category_page_bottom","csblock_category_sidebar_top","user.links.template"]&handles=["default","catalog_category_view","catalog_category_view_type_layered","catalog_category_view_id_2863","restriction_privatesales_mode"]&originalRequest={"route":"catalog","controller":"category","action":"view"}&version=df28718726589060aaf9bb4f61f5e923`
b. You'll get an exception "Notice: Undefined index: uri"
c. Expected result - an error is logged to the exception log and you get redirected to the "noroute" (404 Not Found) page.
2. Try to pass invalid JSON string in originalRequest parameter
a. Request the next URL in your browser `www.your_magento_domain/page_cache/block/render/id/111/?ajax=true&blocks=["csblock_category_content_top","csblock_category_menu_bottom","csblock_category_menu_top","csblock_category_page_bottom","csblock_category_sidebar_top","user.links.template"]&handles=["default","catalog_category_view","catalog_category_view_type_layered","catalog_category_view_id_2863","restriction_privatesales_mode"]&originalRequest={"route":"catalog","controller":"category","action"%%%&&&&:"view"}&version=df28718726589060aaf9bb4f61f5e923`
b. You'l get an empty array as a response. No errors are logged to the exception.log
c. Expected result - an error is logged to the exception log and you get redirected to the "noroute" (404 Not Found) page.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29665: Fix page cache controller block renderer error handling

### CODE REVIEW

**Comment by kodubovik** [comment]
@magento run all tests

**Comment by kodubovik** [comment]
@magento run all tests

**Comment by kodubovik** [comment]
@magento run all tests

**Comment by kodubovik** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento create issue

**Review by aleron75 — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-8073](https://jira.corp.magento.com/browse/ENGCOM-8073) has been created to process this Pull Request

**Review by engcom-Alfa — COMMENTED** [review]
.

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @kodubovik . 
During testing, we faced the issue.

**_Problem:_** An error isn't logged to the **exception.log** when tried to pass the parameter string with the missing required parameter

**Manual testing scenario:**

Try to pass the parameter string with the missing required parameter for the original request.
**a.** Request the next URL in your browser www.your_magento_domain/page_cache/block/render/id/111/?ajax=true&blocks=["csblock_category_content_top","csblock_category_menu_bottom","csblock_category_menu_top","csblock_category_page_bottom","csblock_category_sidebar_top","user.links.template"]&handles=["default","catalog_category_view","catalog_category_view_type_layered","catalog_category_view_id_2863","restriction_privatesales_mode"]&originalRequest={"route":"catalog","controller":"category","action":"view"}&version=df28718726589060aaf9bb4f61f5e923

**Actual Result:** :heavy_check_mark: get redirected to the "noroute" (404 Not Found) page.

Screenshot from 2020-08-31 14-18-09

but :heavy_multiplication_x:  an error isn't logged to the **exception.log** file


If we try to pass invalid JSON string in originalRequest parameter
a. Request the next URL in your browser www.your_magento_domain/page_cache/block/render/id/111/?ajax=true&blocks=["csblock_category_content_top","csblock_category_menu_bottom","csblock_category_menu_top","csblock_category_page_bottom","csblock_category_sidebar_top","user.links.template"]&handles=["default","catalog_category_view","catalog_category_view_type_layered","catalog_category_view_id_2863","restriction_privatesales_mode"]&originalRequest={"route":"catalog","controller":"category","action"%%%&&&&:"view"}&version=df28718726589060aaf9bb4f61f5e923

**Actual Result:** :heavy_check_mark: get redirected to the "noroute" (404 Not Found) page.

Screenshot from 2020-08-31 14-18-09


and :heavy_check_mark: an error is logged to the **exception.log** file.

Screenshot from 2020-08-31 14-27-15


@kodubovik Could you take a look?

Thanks!

**Comment by gabrieldagama** [comment]
The risk was set to`high` due to: the suggested changes are considerable and are made on a critical feature.

**Comment by kodubovik** [comment]
@magento run all tests

**Comment by kodubovik** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@kodubovik please let know when PR will be ready for review.
Thank you.

**Comment by kodubovik** [comment]
@engcom-Charlie it's ready for review

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-8073](https://jira.corp.magento.com/browse/ENGCOM-8073) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
Hi @kodubovik, Thanks for your contribution.Please resolve the conflicts to move on this PR

**Comment by engcom-Dash** [comment]
Hello @kodubovik,

Thanks for the contributions!

Please resolve the conflict so we can proceed with this PR.

Thanks.

**Comment by engcom-Dash** [comment]
Closing this PR since it has not been updated in a long time. Please feel free to reopen it if needed.

**Pull request closed without merging**
