### PR TITLE
Fixed 23230 : Sticky header floating under top when there is no buttons in the toolbar

### PR DESCRIPTION
**Pull request by konarshankar07**
### Description (*)
Admin grid Sticky header is not showing properly when we remove the primary button from the admin grid 

### Fixed Issues (if relevant)

1. magento/magento2#23230: Sticky header floating under top when there is no buttons in the toolbar

### Manual testing scenarios (*)

1.Create listing grid without "button" node:
```
<listing ...>
    <settings>
        <!--<buttons></buttons>-->
    </settings>
</listing>
```
2.Set listingToolbar Sticky value:
```
<listing>
    <listingToolbar>
        <settings>
            <sticky>true</sticky>
        </settings>
    </listingToolbar>
</listing>
```
3. Open admin grid page and scroll down for toolbar sticking to top

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23247) <br/>All committers have signed the CLA.

**Review by OleksiiBulba — APPROVED** [review]
Works perfectly. Thanks!

**Comment by OleksiiBulba** [comment]
> Works perfectly. Thanks!

Small addition: Because the height of sticky header is less than height of sticky header with toolbar we have doubled table head (see screenshot)
image

**Comment by konarshankar07** [comment]
@OleksiiBulba 
I'll fix the mentioned issue and update you soon.
Thanks

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5321](https://jira.corp.magento.com/browse/ENGCOM-5321) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @konarshankar07 !

I've checked PR changes and faced with problem described in comment above.

**Actual Result:**

screen

Could you take a look?

Thanks!

**Comment by konarshankar07** [comment]
@engcom-Alfa 
Yes, I also found this issue which was mention by @OleksiiBulba and I'm working on it to fix and will update you ASAP.

Thanks

**Comment by konarshankar07** [comment]
Hello @OleksiiBulba  and @engcom-Alfa,
Can you please tell me you Magento version in which you are testing?
Thanks

**Comment by OleksiiBulba** [comment]
Hi @konarshankar07 
I'm using Magento EE 2.3.1

**Comment by konarshankar07** [comment]
Hello @OleksiiBulba ,

I'm now not able to reproduce this issue in Magento 2.3-develop lol. Can anyone help me to reproduce this issue?

Thanks

**Comment by engcom-Alfa** [comment]
Hi @konarshankar07 !

The issue provided in  https://github.com/magento/magento2/pull/23247#issuecomment-504389642 ,  reproduce on branch with fix.

Thanks!

**Comment by konarshankar07** [comment]
Hello @engcom-Alfa 

I checked in my local and I'm not getting this issue. You can check this video https://www.loom.com/share/e121239a6af74a949cbd5df61310c3ae

Thanks

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

**Actual Result:**

after2

**Pull request merged**
