### PR TITLE
Skip is_scalar for null values when imploding multiline address

### LINKED ISSUE #35160: 2.4.3-p1 - Magento\Customer\Model\Address\AbstractAddress::_implodeArrayValues($value)
### Preconditions (*)

1. Magento 2.4.3-p1
2. PHP 7.4

### Steps to reproduce (*)

1. To reproduce, simply try to set an address through graphql with a non scalar attribute (null) for second street.<br>
image
```
mutation {
 setShippingAddressesOnCart(
  input: {
   cart_id: "{{cart}}"
   shipping_addresses: [
    {
     address: {
      country_code: "FR"
      street: ["Lorem ipsum dolor sit ame", null]
      telephone: "0601020304"
      postcode: "56590"
      city: "PARIS"
      firstname: "B"
      lastname: "C"
      save_in_address_book: false
     }
    }
   ]
  }
 ) {
  cart {
   shipping_addresses {
    firstname
    lastname
    company
    street
    city
    postcode
    country {
     code
     label
    }
    telephone
   }
  }
 }
}
```

### Expected result (*)

1. While analysing this issue, I found out that `magento/vendor/magento/module-customer/Model/Address/AbstractAddress.php` is responsible of this.
2. Left side is 2.4.3-p1, right side is 2.3.5, by simply reading the code you can understand the issue: **if one of the value in the array is non-scalar, values will never be trimmed and exploded as expected.** see related commit: https://github.com/magento/magento2/commit/876c8052f96d6770254277ff4dd39bce5e935d50 <br>
image
3. By putting back the 2.3.5 code, this work as expected:
<br>image

### Actual result (*)

1. By setting null in secondary address field, an exception is thrown: _"The address failed to save. Verify the address and try again."_<br>
image
2. Due to the scalar condition, the street field is never imploded and his value is an array instead of a string, the class `magento/framework/DB/Adapter/Pdo/Mysql.php` logicly throw when trying to cast the value in string, and we can find this in logs: ```[2022-03-03 09:42:03] report.CRITICAL: Notice: Array to string conversion in /home/bcalef/src/zv/ecom/magento/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3170 {"exception":"[object] (Exception(code: 0): Notice: Array to string conversion in /home/bcalef/src/zv/ecom/magento/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 3170 at /home/bcalef/src/zv/ecom/magento/vendor/magento/framework/App/ErrorHandler.php:61)"} []```

---
Due to multiple impact and side effects on quote/customer addresses, I think this is a S0 priority.

- [x] Severity: **S0**

### PR DESCRIPTION
**Pull request by Zaahed**
### Description (*)

A conditional is added to skip the is_scalar check for null values. Null values are treated as an empty string by implode() anyway. Allows a null value for the second street line in API requests.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35160

### Manual testing scenarios (*)

1. Create an empty guest cart with GraphQL.
image

2. Set the shipping address using the cart_id that was returned from the previous request (see [DevDocs](https://devdocs.magento.com/guides/v2.4/graphql/tutorials/checkout/checkout-shipping-address.html)). Use null as the second value in the street array.
image

Before the change it will return `The address failed to save. Verify the address and try again.`, after the change it will work as usual.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Zaahed** [comment]
@magento run all tests

**Comment by Zaahed** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by Zaahed** [comment]
@magento run Functional Tests CE

**Comment by Zaahed** [comment]
@magento run all tests

**Comment by Zaahed** [comment]
@magento run Functional Tests B2B

**Comment by Zaahed** [comment]
@magento run Functional Tests B2B

**Review by engcom-Hotel — APPROVED** [review]

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Please resolve the failed tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by abhattGlo** [comment]
@magento run WebAPI Tests,Functional Tests EE

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Functional Tests EE failures are different on last two run on same commit.
Run1 
Screenshot 2023-03-31 at 4 56 47 PM

Run2
Screenshot 2023-03-31 at 4 56 42 PM

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

- Create empty cart [devdocs](https://devdocs.magento.com/guides/v2.4/graphql/tutorials/checkout/checkout-shipping-address.html).
- Set the shipping address using the cart_id that was returned from the previous request (see [DevDocs](https://devdocs.magento.com/guides/v2.4/graphql/tutorials/checkout/checkout-shipping-address.html)). Use null as the second value in the street array.
For ex- `street: ["Lorem ipsum dolor sit ame", null]` in the mutation.
```
mutation {
 setShippingAddressesOnCart(
  input: {
   cart_id: "{{cart}}"
   shipping_addresses: [
    {
     address: {
      country_code: "FR"
      street: ["Lorem ipsum dolor sit ame", null]
      telephone: "0601020304"
      postcode: "56590"
      city: "PARIS"
      firstname: "B"
      lastname: "C"
      save_in_address_book: false
     }
    }
   ]
  }
 ) {
  cart {
   shipping_addresses {
    firstname
    lastname
    company
    street
    city
    postcode
    country {
     code
     label
    }
    telephone
   }
  }
 }
}
```

**Before:** :heavy_multiplication_x: Adding null in the street array giving error in the response **`The address failed to save. Verify the address and try again.`**
Screenshot 2023-04-03 at 12 23 31 PM


**After:** :heavy_check_mark:  No error in the response.
Screenshot 2023-04-03 at 12 38 42 PM

**Additionally tested:**
Placed order using guest from graphQL by giving "null" in the street array.

**Pull request merged**
