### PR TITLE
Update laminas server to php 8.1 compatible version

### LINKED ISSUE #34240: Provide PHP 8.1 support for laminas/laminas-server
To unblock the implementation of PHP 8.1 support for Magento Open Source, we need to help upgrade other Open Source libraries (Magento OS composer dependencies).

 

Implementation steps:
* check if the work has already started ([https://github.com/orgs/laminas/projects/16](https://github.com/orgs/laminas/projects/16)  and [https://github.com/laminas/laminas-server/pulls](https://github.com/laminas/laminas-server/pulls) )
* create an issue to the corresponding repo and start work on it, or join the active ticket if possible
* you may also need to update the dependencies of this library. Please follow the same procedure

See the upgrade example for another Laminas library [https://github.com/laminas/laminas-mail/pull/166](https://github.com/laminas/laminas-mail/pull/166)

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/627

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/34240

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by andrewbess — CHANGES_REQUESTED** [review]
Hello @ihor-sviziev 
Thank you for your contribution here.
I think we also need to update composer.json
How do you think about it?

**Comment by ihor-sviziev** [comment]
@andrewbess, I think we don't need to increase the minimum required version since PHP 8.1 will be available anyway.

**Comment by xmav** [comment]
Hi! changes to composer.lock could be easily lost once someone will try to regenerate it. We primarily looking into versions in composer.json. Lets update constrain to ~2.11.0 in composer.json for this dependency

**Comment by xmav** [comment]
Sure you can do composer update and get fresh versions. When Magento installed from composer packages composer.lock file completely ignored and composer takes into account versions declared in composer.json. With existing constrain composer also will install v2.11.0 but lets try to keep constrains updated

**Comment by ihor-sviziev** [comment]
@andrewbess thx for updating

**Review by eduard13 — APPROVED** [review]

**Review by andrewbess — APPROVED** [review]

**Pull request merged**
