### PR TITLE
Add compare list link to success message after adding a product

### PR DESCRIPTION
**Pull request by avstudnitz**
### Description
If I add a product to the compare list, I want to go the compare list directly after that in many cases without having to search for a link. Thus, the link has been added to the success message now.

### Manual testing scenarios
1. Go to a product view page
2. Click "Add to compare"
3. Check if the success message contains a link to the compare list:
grafik

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by PieterCappelle** [comment]
Very good PR. The same should be done when you add a product to your basket. (add link directly to checkout) :)

**Comment by avstudnitz** [comment]
@PieterCappelle Thanks for the hint, I'll work on it :-)

**Comment by avstudnitz** [comment]
@PieterCappelle Thanks for the hint, I'll work on it :-)

**Comment by osrecio** [comment]
Hi @avstudnitz , Thanks for your contribution. I will work to process it. I'll keep you informed.

**Comment by PieterCappelle** [comment]
Hi, when will this be merged?

**Comment by osrecio** [comment]
Hi, Sorry, I lost this PR in my timeline.

Now is Ready for Delivery. And soon will be merged.

**Comment by magento-engcom-team** [comment]
Hi @avstudnitz. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.6 release.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
