### PR TITLE
[Forwardport] CSS load order incorrect using default_head_blocks.xml #1821

### PR DESCRIPTION
**Pull request by torhoehn**
### Original Pull Request 
 https://github.com/magento/magento2/pull/14290
Added new attribute 'order' for set loading order .
Those attribute resolve issue about render files for some order.

### Fixed Issues (if relevant)
1. magento/magento2#1821: CSS load order incorrect using default_head_blocks.xml #1821

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by sidolov** [comment]
Hi @torhoehn , please, take a look at failed test

**Comment by sidolov** [comment]
Hi @torhoehn , tests still failing, will continue progress with this PR?

**Comment by torhoehn** [comment]
@sidolov Sorry, I don't know exactly what to fix here.

```
PHP Code Mess has found error(s):
/home/travis/build/magento/magento2/lib/internal/Magento/Framework/View/Page/Config/Reader/Head.php:69	The method interpret() has a Cyclomatic Complexity of 12. The configured cyclomatic complexity threshold is 10.
/home/travis/build/magento/magento2/lib/internal/Magento/Framework/View/Test/Unit/Page/Config/Generator/HeadTest.php:63	The method testProcess() has 114 lines of code. Current threshold is set to 100. Avoid really long methods.
```
I think complexity and lines of code in a method has been the same in 2.2. Proof me wrong.

**Comment by sidolov** [comment]
@torhoehn you can suppress warning regarding excessive method length in the test but it would be better refactor it. 
Cyclomatic complexity should be refactored in the current class by extracting logic to separate methods.

**Comment by sidolov** [comment]
Hi @torhoehn , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
