### PR TITLE
Removed CliIndexerReindexActionGroup action group usage for Catalog module

### LINKED ISSUE #31327: [Issue] Removed CliIndexerReindexActionGroup action group usage for Catalog module
This issue is automatically created based on existing pull request: magento/magento2#31320: Removed CliIndexerReindexActionGroup action group usage for Catalog module

---------
### Description
Remove CliIndexerReindexActionGroup action group usage or change value for it from tests to improve execution time for the Catalog module.

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Remove CliIndexerReindexActionGroup action group usage or change value for it from tests to improve execution time for the Catalog module.

### Resolved issues:
1. [x] resolves magento/magento2#31327: Removed CliIndexerReindexActionGroup action group usage for Catalog module

### CODE REVIEW

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE

**Comment by eduard13** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Comment by sergiy-v** [comment]
Hello @eduard13,
Just FYI, all Functional Tests are green, so please proceed with checking.
Thank you.

**Review by eduard13 — APPROVED** [review]
Good job 👍

**Comment by eduard13** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** Functional Tests B2B and Functional Tests EE are failed

**Comment by eduard13** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by eduard13** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8558](https://jira.corp.magento.com/browse/ENGCOM-8558) has been created to process this Pull Request

**Comment by eduard13** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run all tests

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE,Functional Tests B2B,Static Tests,Integration Tests

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE

**Comment by sergiy-v** [comment]
@magento run all tests

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@sergiy-v MFTF tests are green, rerunning all to have whole green builds.

**Comment by sergiy-v** [comment]
@magento run Functional Tests B2B

**Pull request merged**
