### PR TITLE
Mass attribute update fails with E_WARNING #17592

### PR DESCRIPTION
**Pull request by Dmutryk**
### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/17592

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18068) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @Dmutryk. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
Hi @Dmutryk. Thank you for your contribution. Unfortunately, we cannot accept this change as it is. In some cases, the `min_sale_qty` default value is provided as an array. So, by removing the multiplier we face with an attempt to "echo" the array.
To avoid workarounds we need to investigate such scenarios and output the correct default value for `min_sale_qty`

**Comment by sidolov** [comment]
Hi @Dmutryk , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
