### PR TITLE
Updated PHP versions in composer files

### PR DESCRIPTION
**Pull request by andrewbess**
### Description (*)

This pull request provides the update of the PHP version in require section to "~7.4.0||~8.0.0" into all composer files.
Also, this PR provides the update composer dependencies.
Builds of this PR should run with PHP 7.4 environment.

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/602
https://github.com/magento/partners-magento2b2b/pull/587
https://github.com/magento/magento2-sample-data/pull/169
https://github.com/magento/inventory/pull/3323
https://github.com/magento/adobe-stock-integration/pull/1867
https://github.com/magento/security-package/pull/305
https://github.com/magento/magento2-page-builder/pull/774
https://github.com/magento/magento2-page-builder-ee/pull/191
https://github.com/magento/adobe-ims/pull/11

### Fixed Issues (if relevant)

1. Fixes magento/magento2#34009

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by Bashev** [comment]
What is the idea to add php requirements in every composer.json file, is not enough to put it in magento-framework version >x.x.x all of them requires magento-framework? Is this way will be most easy for support?

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Review by eduard13 — APPROVED** [review]

**Comment by andrewbess** [comment]
@magento run all tests

**Review by xmav — APPROVED** [review]

**Comment by andrewbess** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Pull request merged**
