### PR TITLE
Fixed issue #18337

### PR DESCRIPTION
**Pull request by geet07**
### Description (*)

**Search input is missing required attribute aria-expanded:** For this issue I have made changes in mediaCheck exit function because the exit function is using only for desktop vestion and it was using isExpandable=>false.   

### Fixed Issues (if relevant)

1. magento/magento2#18337: Search input is missing required attribute aria-expanded.
2. ...

### Manual testing scenarios (*)

1. Check home page in W3C html validator or open home page check with inspect element 
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Karlasa** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Karlasa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Karlasa, here is your [Magento instance](https://i-22942-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22942-2-3-develop.instances.magento-community.engineering/admin](https://i-22942-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by VladimirZaets — APPROVED** [review]

**Comment by dmytro-ch** [comment]
Hi @geet07,
I guess it should be enough to remove the following line in order to solve the mentioned issue.
```
this.element.removeAttr('aria-expanded');
```
And looks like it has been already fixed by this commit: 679d8a542dedf330ee899332fd46a7d701c44071

Thank you!

**Comment by geet07** [comment]
> Hi @geet07,
> I guess it should be enough to remove the following line in order to solve the mentioned issue.
> 
> ```
> this.element.removeAttr('aria-expanded');
> ```
> 
> And looks like it has been already fixed by this commit: [679d8a5](https://github.com/magento/magento2/commit/679d8a542dedf330ee899332fd46a7d701c44071)
> 
> Thank you!

Hi  @dmytro-ch,

Thank You for your message

I am newbie here, Can You please assist me what next step I should take?

**Comment by geet07** [comment]
> Hi @geet07,
> I guess it should be enough to remove the following line in order to solve the mentioned issue.
> 
> ```
> this.element.removeAttr('aria-expanded');
> ```
> 
> And looks like it has been already fixed by this commit: [679d8a5](https://github.com/magento/magento2/commit/679d8a542dedf330ee899332fd46a7d701c44071)
> 
> Thank you!

Hi @dmytro-ch,

I have checked according to your comment. We need to do this both changes
`this.isExpandable = true;`
if this is true then attribute showing in desktop version.

**Comment by VasylShvorak** [comment]
@dmytro-ch  issue [#18337](https://github.com/magento/magento2/issues/18337) is still reproducible on 2.3-develop as commit [679d8a5](https://github.com/magento/magento2/commit/679d8a542dedf330ee899332fd46a7d701c44071) somehow is not fully merged. 
[form.mini.phtml](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Search/view/frontend/templates/form.mini.phtml) on 2.3-develop branch

**Comment by dmytro-ch** [comment]
@geet07 @VasylShvorak, you are right, thank you for the details!

@geet07 could you please merge the `2.3-develop` into your working branch and resolve a merge conflict?

**Comment by geet07** [comment]
> @geet07 @VasylShvorak, you are right, thank you for the details!
> 
> @geet07 could you please merge the `2.3-develop` into your working branch and resolve a merge conflict?

How can I merge the 2.3-develop into my working branch? There is no merge option enable for me. Can you please guide me

Fixed issue  18337 by geet07 · Pull Request  22942 · magento magento2

**Comment by dmytro-ch** [comment]
@geet07 you need to do it locally, then push your working branch to the remote repository.

**Comment by geet07** [comment]
> @geet07 you need to do it locally, then push your working branch to the remote repository.

Hi @dmytro-ch,

Thank you for reply.

I have resolved conflicts can u pls check and let me know if there is another changes required.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5135](https://jira.corp.magento.com/browse/ENGCOM-5135) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
Hi @geet07  I have tested PR changes and issue [#18337](https://github.com/magento/magento2/issues/18337) is reproduced as input field doesn't have **aria-expanded** attribute
#22942PR

**Comment by geet07** [comment]
> Hi @geet07 I have tested PR changes and issue [#18337](https://github.com/magento/magento2/issues/18337) is reproduced as input field doesn't have **aria-expanded** attribute
> #22942PR

Hi @VasylShvorak, 

Thank you for testing.

You are right, This issue is reproduced, I have checked with search element on clicked and for this case it is working correct. I have not done any code for default show **aria-expanded** tag. So Now I have added code for mobile and desktop version and created a commit to resolved this issue. 

Please check and let me know if there is another chages required

**Comment by geet07** [comment]
Hi @dmytro-ch,

As per QA issue I have added some more code, Can u please review and merge it.

**Comment by VasylShvorak** [comment]
Hi @geet07 Unfortunately, your latest commit doesn't fix issue. W3C html validator is still showing error:  "Element input is missing required attribute aria-expanded"

**Comment by geet07** [comment]
Hi @VasylShorak

Thank you for your reply.

I think my latest commit not merge yet.

Can you please help me change label accordingly.

**Comment by VasylShvorak** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @VasylShvorak. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @VasylShvorak, here is your [new Magento instance](https://pr-22942.instances.magento-community.engineering).
Admin access: [https://pr-22942.instances.magento-community.engineering/admin](https://pr-22942.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by VasylShvorak** [comment]
@geet07 PR was tested with your latest commit [bf4fbf029681851104d95695e11aa22022adb69b](https://github.com/magento/magento2/pull/22942/commits/bf4fbf029681851104d95695e11aa22022adb69b).

**Comment by geet07** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @geet07. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @geet07, here is your [new Magento instance](https://pr-22942.instances.magento-community.engineering).
Admin access: [https://pr-22942.instances.magento-community.engineering/admin](https://pr-22942.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by geet07** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @geet07. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @geet07, here is your [new Magento instance](https://pr-22942.instances.magento-community.engineering).
Admin access: [https://pr-22942.instances.magento-community.engineering/admin](https://pr-22942.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by geet07** [comment]
> @geet07 PR was tested with your latest commit [bf4fbf029681851104d95695e11aa22022adb69b](https://github.com/magento/magento2/pull/22942/commits/bf4fbf029681851104d95695e11aa22022adb69b).
> 

Hi @VasylShvorak,

Thank you, I have resolved this issue. Please check and let me know if there is another changes required.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5135](https://jira.corp.magento.com/browse/ENGCOM-5135) has been created to process this Pull Request
:eight_spoked_asterisk: @dmytro-ch, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
