### PR TITLE
Add developer mode example to .htacess

### PR DESCRIPTION
**Pull request by JamesAnelay**
After years on M1 I allmost allways still google "Magento set developer mode" to get the Developer Mode snippet. I figure it would be nice to just have it there in .htacess as an example as 99% of the time that is why I am going to this file.

### CODE REVIEW

**Comment by avoelkl** [comment]
:+1:

**Comment by vpelipenko** [comment]
@JamesAnelay, thank you for good suggestion. Could you also add this to .htaccess.sample and pub/.htaccess?

**Comment by vrann** [comment]
@JamesAnelay thanks for update!
Internal tracking number is MAGETWO-35355. It will be merged soon.

**Comment by snohe** [comment]
@JamesAnelay, this has been merged in 0.74.0-beta1.  Thank you again for your valuable contribution!  We highly appreciate your continued support in Magento!

**Pull request merged**
