### PR TITLE
[Backport] Fixed-Configurable-product-options-are-misaligned-2.2

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Fixed Issues (if relevant)

1. magento/magento2#20521: Configurable product options are misaligned
2. Magento 2.2-develop

### Manual testing scenarios (*)

1. Go to admin area
2. Go to Sales -> Orders
3. Press create a new order button
4. Press Add Products button
5. From the list, choose a configurable product and press "Configure"

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by VladimirZaets** [comment]
Hi @amol2jcommerce. Please note that changes to 2.2-develop branch can be accepted only if these changes are present in the 2.3-develop branch (https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html). Please, create a pull request to the 2.3-develop branch and rename this one as backport.

**Comment by SyntaxKay** [comment]
@amol2jcommerce This issue pull request already has been created https://github.com/magento/magento2/issues/19380

**Comment by cmtickle** [comment]
#19381 was closed as #19382 was created. #19382 is closed due to inactivity. Reopening this Pull Request.

**Comment by SyntaxKay** [comment]
@amol2jcommerce Duplicate Pull request

**Comment by ghost** [comment]
Hi @amol2jcommerce, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+magento2+20533), it will take less than a minute. </br>Your feedback will help us to improve contribution process.

**Pull request closed without merging**
