### PR TITLE
MFTF: Refactoring AdminGenerateUrlRewritesForProductInCategoriesSwitchOffTest

### PR DESCRIPTION
**Pull request by kate-kyzyma**
### Description (*)
AdminGenerateUrlRewritesForProductInCategoriesSwitchOffTest is refactored according to the best practices followed by MFTF.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
Run the AdminGenerateUrlRewritesForProductInCategoriesSwitchOffTest in the local environment and verified the test runs successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by dmytro-ch** [comment]
@magento run all tests

**Review by dmytro-ch — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7620](https://jira.corp.magento.com/browse/ENGCOM-7620) has been created to process this Pull Request

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @kate-kyzyma . Could you resolve merge conflicts? Thanks!

**Comment by kate-kyzyma** [comment]
Hi @engcom-Alfa 

The merge conflict is resolved.

**Comment by kate-kyzyma** [comment]
@magento run all tests

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7620](https://jira.corp.magento.com/browse/ENGCOM-7620) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by slavvka** [comment]
@magento run all tests

**Pull request merged**
