### PR TITLE
update dealerdirect/phpcodesniffer-composer-installer dependency from ^0.5.0 to ^0.7.0

### PR DESCRIPTION
**Pull request by sergiynezbritskiy**
update dealerdirect/phpcodesniffer-composer-installer package from ^0.5.0 to ^0.7.0

### Description (*)

update dealerdirect/phpcodesniffer-composer-installer dependency from ^0.5.0 to ^0.7.0

### Fixed Issues

1. Fixes magento/magento2#31175

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sergeynezbritskiy** [comment]
@magento run all tests

**Review by coderimus — APPROVED** [review]
Hello @sergeynezbritskiy !
Thank you for the upgrade 👍

**Comment by coderimus** [comment]
@magento run Unit Tests

**Comment by coderimus** [comment]
Just a note: no BIC changes in the range of releases from 0.5.0 till 0.7.0. Checked original repository and release notes.

**Comment by coderimus** [comment]
@sivaschenko this PR is ready to be reviewed and test: I checked changes and looks like there is no BIC or deleted functionality in the 3rd party module.

**Comment by hostep** [comment]
@sivaschenko, @coderimus : be aware that this dependency's constraint is already updated in Magento 2.4.2 to `^0.7.0` in order to provide support for composer v2

Don't ask me why this hasn't been merged yet in `2.4-develop` but maybe we should wait on that to have happened before proceeding with this PR?

Also maybe you should (if possible) communicate a bit better with core devs, since they already did the BiC checking before.

**Comment by sivaschenko** [comment]
Thanks for information @hostep ! We still need to deliver this change to php8-develop branch as there may be delays with merging 2.4.2 to 2.4-develop

**Comment by coderimus** [comment]
Hello @sergeynezbritskiy 
Thank you for the provided upgrade and all work you have done in the scope of this issue. But we have to close it because of the fact that this version was already merged to the mainline. Thank you @hostep for pointing this out.

**Pull request closed without merging**
