### PR TITLE
Updating link to Adobe CLA in contributing.md

### PR DESCRIPTION
**Pull request by filmaj**

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7161](https://jira.corp.magento.com/browse/ENGCOM-7161) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@filmaj thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Bravo** [comment]
:heavy_check_mark:  QA Passed
pr7161_link

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Pull request merged**
