### PR TITLE
#27962 Migrate Plugin out of Framework (to Theme module)

### LINKED ISSUE #27962: Plugins in \Magento\Framework namespace
### Preconditions (*)
One of Magento Architects contacted me in private message blaming me for [introducing Plugin to the Core](https://github.com/magento/magento2/tree/2.3.4/lib/internal/Magento/Framework/App/Action/Plugin) that is not allowed in Magento and couldn't have been done by Magento Employees due to Quality Standards.

https://github.com/magento/magento2/blob/5f3b86ab4bd3e3b94e65429fed33f748d29c1bbe/lib/internal/Magento/Framework/App/Action/Plugin/Design.php#L6-L10

lol.

As I've introduced another 2 plugins and renamed existing one to follow the naming convention, there are 3 plugins in the `\Magento\Framework` namespace. As the architect wasn't so nice to tell me where outside \Magento\Framework` I should put these plugins, I create issue to satisfy "Quality Standards" of Magento.

The plugins to be moved:
https://github.com/magento/magento2/tree/2.4-develop/lib/internal/Magento/Framework/App/Action/Plugin

#### Before you continue, please remember that plugins in `\Magento\Framework` were never allowed!

:facepalm: :man_facepalming: :woman_facepalming: :facepalm: :man_facepalming: :woman_facepalming: :facepalm: :man_facepalming: :woman_facepalming: :facepalm: :man_facepalming: :woman_facepalming: 

https://github.com/magento/magento2/blob/5f3b86ab4bd3e3b94e65429fed33f748d29c1bbe/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php#L6-L18
https://github.com/magento/magento2/blob/892dee45e4f80ae7df04b4ce550971e5a0453eff/app/etc/di.xml#L1805-L1807
https://github.com/magento/partners-magento2ee/blob/6d49dacca99f5276f09bbddd50866440f3d3fccc/app/code/Magento/ScalableCheckout/etc/di.xml#L34-L36
https://github.com/magento/magento2/blob/ae9962561509ff5e0c74b17551f90640e155db2b/app/code/Magento/Amqp/etc/di.xml#L9-L17
https://github.com/magento/magento2/blob/4b66b00c574a0e092597f1603ede7bfcb8a95ed2/app/code/Magento/Eav/etc/di.xml#L108-L110
https://github.com/magento/magento2/blob/d938e7bcab3f4620d5d0facb23a05ab81304e988/app/code/Magento/Store/etc/di.xml#L36-L38

### Steps to reproduce (*)
N/A

### Expected result (*)
Magento Framework shouldn't contain any plugins

### Actual result (*)
1. Magento Framework contains plugins, that should be misplaced in different modules, see description

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
During my recent changes related to Controllers decomposition, I renamed the existing plugin. Some random Magento Architect says that it was never allowed to add Plugin to `\Magento\Framework` namespace and it was never allowed:

image

I had no idea about that (is there information missing in DevDocs / coding standards / static checks?). So I'm moving plugin out of `\Magento\Framework` area, as it's against Magento Best Practices.

(If it was never allowed, why it's there since 2016?)
https://github.com/magento/magento2/blob/5f3b86ab4bd3e3b94e65429fed33f748d29c1bbe/lib/internal/Magento/Framework/App/Action/Plugin/Design.php#L6-L10

### Fixed Issues (if relevant)
1. fixes magento/magento2#27962

### Manual testing scenarios (*)
N/A

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7484](https://jira.corp.magento.com/browse/ENGCOM-7484) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @lbajsarowicz,
Could you review failing MHI test and update your PR?

Also I see that you moved just one plugin, could you move all plugins to corresponding modules at once?

**Review by ihor-sviziev — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7484](https://jira.corp.magento.com/browse/ENGCOM-7484) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked that Luma theme is applied and loaded without errors
Was checked that Blank theme is applied and loaded without errors
Was checked that different themes are applied and loaded without errors on different store views
**Result:**
image

image

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Review by slavvka — CHANGES_REQUESTED** [review]
@lbajsarowicz please resolve the conflicts and re-run the tests after the upgrade to PHP 7.4

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7484](https://jira.corp.magento.com/browse/ENGCOM-7484) has been created to process this Pull Request

**Review by slavvka — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @slavvka, thank you for the review.
[ENGCOM-7484](https://jira.corp.magento.com/browse/ENGCOM-7484) has been created to process this Pull Request

**Comment by lbajsarowicz** [comment]
@magento run all tests

I'd like to verify if there are no issues with current mainline.

**Pull request merged**
