### PR TITLE
MAG-251090-26590: Fixed Customer registration multiple form submit

### PR DESCRIPTION
**Pull request by princeantil90**
### Fixed Issues (if relevant)

1. magento/magento2#26590: Customer registration multiple form submit

### Manual testing scenarios (*)

1. From the Storefront, Create a new account (customer/account/create/ URL)
2. Fill in all the required fields.
3. Click the "Create an Account" button multiple times really fast.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by princeantil90** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @princecb. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @princecb, here is your [new Magento instance](https://pr-26642.instances.magento-community.engineering).
Admin access: [https://pr-26642.instances.magento-community.engineering/admin_a8f1](https://pr-26642.instances.magento-community.engineering/admin_a8f1)
Login: `37da9acf` Password: `d7ceb8a6eea7`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment]
@magento run Functional Tests CE

**Comment by sdzhepa** [comment]
@magento run Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, here is your [new Magento instance](https://pr-26642.instances.magento-community.engineering).
Admin access: [https://pr-26642.instances.magento-community.engineering/admin_f218](https://pr-26642.instances.magento-community.engineering/admin_f218)
Login: `33a97d88` Password: `5a806ec3f5bb`
Instance will be terminated in up to 3 hours.

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
I think it will be really hard to cover these changes with tests, so I put "auto-test: not required" label

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7034](https://jira.corp.magento.com/browse/ENGCOM-7034) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@princecb thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
