### PR TITLE
Fixed #16929 - Incorrect displaying Product Image Watermarks on Magento 2.2.5

### LINKED ISSUE #16929: Incorrect displaying Product Image Watermarks on Magento 2.2.5
### Summary
Background of Product Image Watermarks is displayed incorrect if it is transparent.

### Preconditions
1. Magento 2.2.5 CE with sample data
2. PHP 7.0.30

### Steps to reproduce
1. Login to Admin Panel
2. Create a simple product with any configuration and upload any product image (the image that I uploaded below)
mb01-blue-0
3. Go to Content -> Design -> Configuration 
4. Click on the edit action on the Global Magento Luma theme
5. Go to the Product Image Watermarks section
6. Upload any PNG image with a transparent background for example in the small category (the image that I uploaded below)
58480ecccef1014c0b5e492c
7. Set Image Opacity to 10
8. Set Image Size to 40x50
9. Set Image Position Tile 
10. Save Configuration
11. Go to the product view on store front and look at the result

### Expected result
1. Product Image Watermarks are displayed over a product image
2. Image Watermarks size is 40x50
3. Image Watermarks position is tile
4. Image Watermarks opasity is 10
5. Background of Image Watermarks is transparent as it is transparent on an uploaded image

### Actual result
1. Product Image Watermarks are displayed over a product image
2. Image Watermarks size is 40x50
3. Image Watermarks position is tile
4. Image Watermarks opacity is 10
5. Background of Image Watermarks **IS NOT** transparent.
screenshot from 2018-07-19 10-35-21

### PR DESCRIPTION
**Pull request by ronak2ram**
### Description
Not needed to call function imagealphablending() when resize watermark size.

### Fixed Issues
1. magento/magento2#16929: Incorrect displaying Product Image Watermarks on Magento 2.2.5

### Manual testing scenarios
1. Login to Admin Panel
2. Create a simple product with any configuration and upload any product image (the image that I uploaded below)
mb01-blue-0
3. Go to Content -> Design -> Configuration
4. Click on the edit action on the Global Magento Luma theme
5. Go to the Product Image Watermarks section
6. Upload any PNG image with a transparent background for example in the small category (the image that I uploaded below)
58480ecccef1014c0b5e492c
7. Set Image Opacity to 10
8. Set Image Size to 40x50
9. Set Image Position Tile
10. Save Configuration
11. Go to the product view on store front and look at the result

### Result
screenshot4

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ronak2ram. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by ronak2ram** [comment]
@magento-engcom-team 
Have you checked this solution?

**Comment by magento-engcom-team** [comment]
Hi @ronak2ram. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.7. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Comment by peterjaap** [comment]
Backward patch for 2.2.6;

```
diff --git a/Image/Adapter/Gd2.php b/Image/Adapter/Gd2.php
index 33d7376..e04ecc3 100644
--- a/Image/Adapter/Gd2.php
+++ b/Image/Adapter/Gd2.php
@@ -425,7 +425,6 @@ class Gd2 extends \Magento\Framework\Image\Adapter\AbstractAdapter
             $col = imagecolorallocate($newWatermark, 255, 255, 255);
             imagecolortransparent($newWatermark, $col);
             imagefilledrectangle($newWatermark, 0, 0, $this->getWatermarkWidth(), $this->getWatermarkHeight(), $col);
-            imagealphablending($newWatermark, true);
             imagesavealpha($newWatermark, true);
             imagecopyresampled(
                 $newWatermark,
@@ -450,7 +449,6 @@ class Gd2 extends \Magento\Framework\Image\Adapter\AbstractAdapter
             $col = imagecolorallocate($newWatermark, 255, 255, 255);
             imagecolortransparent($newWatermark, $col);
             imagefilledrectangle($newWatermark, 0, 0, $this->_imageSrcWidth, $this->_imageSrcHeight, $col);
-            imagealphablending($newWatermark, true);
             imagesavealpha($newWatermark, true);
             imagecopyresampled(
                 $newWatermark,
-- 
2.17.1


```

**Pull request merged**
