### PR TITLE
Add trim filter to first, middle and lastname.

### PR DESCRIPTION
**Pull request by wardcapp**
### Description
The additional trim form field data filter was created and added as
input filter to the firstname, lastname and middlename fields
of the customer_address and customer entities.

### Fixed Issues (if relevant)

1. magento/magento2#10415: Customer First and Last names not being trimmed of leading and trailing spaces on save.

### Manual testing scenarios

1. Create a new customer from the Customers > All Customers > Create New Customer window
2. Create First name: "John " Last name: " Doe ", add a fake email address.
3. Click save
4. Search and edit the contact "John Doe "
5. Take note that the spaces are no longer in the users first, middle and last names. Same goes for the customer names set on the customer addresses.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by wardcapp** [comment]
Comments made above do not seem to relate to the initial pull request I set up, but maybe I did something wrong? The PR only contained commit 8593966 at first.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=11051) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=11051) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: wardcapp<br/>:x: paliarush<br/>:x: viktym

**Comment by wardcapp** [comment]
Not sure what happened to suddenly have the commits by paliarush and viktym included into this PR some months ago, maybe I should re-create the PR to ease the review process?

**Comment by wardcapp** [comment]
Deleted the earlier set up branch by accident, my bad. The pull request was re-created, making sure the fix can still be merged (see https://github.com/magento/magento2/pull/12964).

**Pull request closed without merging**
