### PR TITLE
Fixed #23852 Magento 2.3 Customer Configuration in the Online Customer Options have not proper validation

### LINKED ISSUE #23852: Magento 2.3 Customer Configuration in the Online Customers Options field have not proper validation
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

`Customer Configuration` in the `Online Customers Options` have `Online Minutes Interval` and `Customer Data Lifetime` two field and that field have used for minutes interval. But issue is that two field taking any of the value. There should be take proper validation. 
1. Login to the Magento 2 admin.
2. Go to the STORES >> Settings >> Configuration >> CUSTOMERS >> Customer Configuration >> Online Customers Options: 
3. Online Minutes Interval: add any text value
4. Customer Data Lifetime: add any text value
5. Save Config

### Expected result (*)

1. There should be allow only digit. Validation is missing
2. Correct-Validation

### Actual result (*)

1. There is a taking all the value like text and string as well.
2. Wrong-Validation

### PR DESCRIPTION
**Pull request by kirtinariya1**
Magento 2.3 Customer Configuration in the Online Customer Options have resolved proper validation.

### Description (*)

Fixed proper validation of Customer Configuration in the Online Customers Options in `Online Minutes Interval` and `Customer Data Lifetime` field.

### Fixed Issues (if relevant)

1. #23852: Magento 2.3 Customer Configuration in the Online Customers Options field have not proper validation

### Manual testing scenarios (*)

1. Login to the Magento 2 admin Go to the STORES >> Settings >> Configuration >> CUSTOMERS >> Customer Configuration >> Online Customers Options:
2. Online Minutes Interval: add any value
3. Customer Data Lifetime: add any value
4. Save Config
5. There should be allow only digits

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=23856) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=23856) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: kirtinariya1<br/>:x: Kirti Nariya<hr/>**Kirti Nariya** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by sidolov** [comment]
Hi @kirtinariya1  looks like you made some commits with an email different than in your GitHub profile, please, add email from commits to your profile!
Thank you!

**Comment by kirtinariya1** [comment]
> Hi @kirtinariya1 looks like you made some commits with an email different than in your GitHub profile, please, add email from commits to your profile!
> Thank you!

**Comment by kirtinariya1** [comment]
> Hi @kirtinariya1 looks like you made some commits with an email different than in your GitHub profile, please, add email from commits to your profile!
> Thank you!

@sidolov Thank for your guide. I appreciate you, I am using same github account email id but it's something cause of showing notice.

**Review by josefbehr — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @josefbehr, thank you for the review.
[ENGCOM-5611](https://jira.corp.magento.com/browse/ENGCOM-5611) has been created to process this Pull Request
:eight_spoked_asterisk: @josefbehr, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
