### PR TITLE
WIP - Update README.md

### PR DESCRIPTION
**Pull request by lyndonwright**
### Description
PLEASE IGNORE

This is a test pull for training.  I am at Meet Magento London 2018-06-12 learning how to contribute to Magento.

LJW: I just edited the README.md file so I could test spinning up an instance of Magento on Magento cloud servers and run their tests.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16059) <br/>All committers have signed the CLA.

**Comment by lyndonwright** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @2buy1click. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @2buy1click, here is your [Magento instance](https://pr-16059.engcom.dev.magento.com).
Admin access: [https://pr-16059.engcom.dev.magento.com/admin](https://pr-16059.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Please make sure you are PR **author** or **assignee** to access the instance.

**Comment by ihor-sviziev** [comment]
Hi @2buy1click what is purpose of this PR? Can it be closed?

**Comment by lyndonwright** [comment]
@ihor-sviziev I'm at Meet Magento London #MM18UK learning how to contribute to Magento Core. So just need this for next 2 days for testing. Then I'll close it. (I'll update my pull comment to say this)

**Comment by 2buy1click** [comment]
@magento-engcom-team give me 2.3-develop

**Comment by 2buy1click** [comment]
@magento-engcom-team give me 2.2 instance

**Comment by lyndonwright** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @2buy1click. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @2buy1click, here is your [Magento instance](https://i-16059-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-16059-2-3-develop.engcom.dev.magento.com/admin](https://i-16059-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by orlangur** [comment]
@ihor-sviziev let's just allow experimenting, I believe author will close it by himself if needed 😉

**Pull request closed without merging**
