### PR TITLE
magento/magento2#37812: Fixed creating submenu if containing more tha…

### LINKED ISSUE #37812: Backend menu gets too long and not generating proper columns
### Preconditions and environment

- Magento version 2.4.4-p4
- Firefox
- Having a first submenu containing more than 12 items.

Example : the first submenu of the Sales menu has got 13 items.

image

### Steps to reproduce

1. Access the backend.

### Expected result

The system should add a column brake so the submenus are correctly displayed

### Actual result

Unable to access submenus below the 12+ submenu because the column brake isn't behaving correctly.

Attached is a screenshot of the problem. I'm already scrolled down at the very bottom of the page and there's still items below "Shipments" and "Credit memos"

image

### Additional information

I have investigated and managed to fix the issue with the following code. Problem comes from the fact that if the first submenu exceeds the hardcoded 12 items limit, the next submenu does not automatically include a column brake.

```
diff --git a/magento/module-backend/Block/Menu.php b/magento/module-backend/Block/Menu.php
--- a/magento/module-backend/Block/Menu.php
+++ b/magento/module-backend/Block/Menu.php
@@ -333,10 +333,16 @@ class Menu extends \Magento\Backend\Block\Template
         }
         $result[] = ['total' => $total, 'max' => ceil($total / ceil($total / $limit))];
         $count = 0;
+        $itemCount = 0;
+        $nextColBrake = false;
         foreach ($items as $item) {
+            $itemCount++;
             $place = $this->_countItems($item->getChildren()) + 1;
             $count += $place;
-            if ($place - $result[0]['max'] > $limit - $result[0]['max']) {
+            if ($nextColBrake) {
+                $colbrake = true;
+                $count = $place;
+            } elseif ($place - $result[0]['max'] > $limit - $result[0]['max']) {
                 $colbrake = true;
                 $count = 0;
             } elseif ($count - $result[0]['max'] > $limit - $result[0]['max']) {
@@ -345,6 +351,12 @@ class Menu extends \Magento\Backend\Block\Template
             } else {
                 $colbrake = false;
             }
+
+            $nextColBrake = false;
+            if ($itemCount == 1 && $colbrake) {
+                $nextColBrake = true;
+            }
+
             $result[] = ['place' => $place, 'colbrake' => $colbrake];
         }
         return $result;
```

Test evidence after fix : 

image

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by hutychivan**
### Description (*)
If the first submenu contains more than 12 items, the column alignment is incorrect, and this prevents access to items below.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#37812

### Manual testing scenarios (*)

1. Fill the first submenu's first column with more than 12 items. For example, the Content submenu. 
image
```
<add id="Magento_Cms::test1" title="Test 1"
             translate="title" module="Magento_Cms" sortOrder="100"
             action="test/test/test"
             parent="Magento_Backend::content_elements" resource="Magento_Cms::page"/>
        <add id="Magento_Cms::test2" title="Test 2"
             translate="title" module="Magento_Cms" sortOrder="100"
             action="test/test/test"
             parent="Magento_Backend::content_elements" resource="Magento_Cms::page"/>
        <add id="Magento_Cms::test3" title="Test 3"
             translate="title" module="Magento_Cms" sortOrder="100"
             action="test/test/test"
             parent="Magento_Backend::content_elements" resource="Magento_Cms::page"/>
        <add id="Magento_Cms::test4" title="Test 4"
             translate="title" module="Magento_Cms" sortOrder="100"
             action="test/test/test"
             parent="Magento_Backend::content_elements" resource="Magento_Cms::page"/>
        <add id="Magento_Cms::test5" title="Test 5"
             translate="title" module="Magento_Cms" sortOrder="100"
             action="test/test/test"
             parent="Magento_Backend::content_elements" resource="Magento_Cms::page"/>
        <add id="Magento_Cms::test6" title="Test 6"
             translate="title" module="Magento_Cms" sortOrder="100"
             action="test/test/test"
             parent="Magento_Backend::content_elements" resource="Magento_Cms::page"/>
        <add id="Magento_Cms::test7" title="Test 7"
             translate="title" module="Magento_Cms" sortOrder="100"
             action="test/test/test"
             parent="Magento_Backend::content_elements" resource="Magento_Cms::page"/>
        <add id="Magento_Cms::test8" title="Test 8"
             translate="title" module="Magento_Cms" sortOrder="100"
             action="test/test/test"
             parent="Magento_Backend::content_elements" resource="Magento_Cms::page"/>
        <add id="Magento_Cms::test9" title="Test 9"
             translate="title" module="Magento_Cms" sortOrder="100"
             action="test/test/test"
             parent="Magento_Backend::content_elements" resource="Magento_Cms::page"/>
```
2. Lost access to the Design column in this example.

### Questions or comments

After the fixes, it looks like this.
image

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hutychivan** [comment]
@magento run all tests

**Review by swnsma — CHANGES_REQUESTED** [review]
Hello @hutychivan,

Thank you for your contribution!

I would like to ask and discuss with you a few points.
Let's start from discussion.
Would this code do the same as your changes?
If so, I would ask to refactor the PR a bit, so we could keep the code better readable and avoid unneeded variables in the method.
```
protected function _columnBrake($items, $limit)
    {
        $total = $this->_countItems($items);
        if ($total <= $limit) {
            return;
        }
        $result[] = ['total' => $total, 'max' => ceil($total / ceil($total / $limit))];
        $count = 0;
        foreach ($items as $item) {
            $place = $this->_countItems($item->getChildren()) + 1;
            $count += $place;
            if ($place - $result[0]['max'] > $limit - $result[0]['max']) {
                $colbrake = true;
                $count = 0;
            } elseif ($count - $result[0]['max'] > $limit - $result[0]['max']) {
                $colbrake = true;
                $count = $place;
            } else {
                $colbrake = false;
            }
            $result[] = ['place' => $place, 'colbrake' => $colbrake];
        }

        if (isset($result[1]) && $result[1]['colbrake'] === true && isset($result[2])) {
            $result[2]['colbrake'] = true;
        }

        return $result;
    }
 ```   
 
 
 May I also ask you:
 1) According to Definition of Done, new changes should be covered with automatic tests. May I ask you to extend \Magento\Backend\Block\MenuTest::testRenderNavigation to cover the case that right now cause an issue ?
 2) Please fix failed static tests (I know that failed test is not related to your changes, but it's a part of the process + changes are small).

Thank you!

**Comment by engcom-Hotel** [comment]
Hello @hutychivan,

Have you got chance to check this review comment https://github.com/magento/magento2/pull/38078#pullrequestreview-1737263911?

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Unit Tests

**Comment by engcom-Echo** [comment]
Static Tests failure is not related to this PR and its known failures and Functional Tests B2B build are green.
Functional Tests CE failure are different on last two run.
Run1
Screenshot 2023-12-07 at 9 58 59 AM

Run2
Screenshot 2023-12-07 at 9 59 24 AM

Moving it to `Pending Review`

**Review by swnsma — APPROVED** [review]

**Comment by engcom-Echo** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

1. We have follow steps from [comment](https://github.com/magento/magento2/pull/38078#issue-1942063578)


**Before:** :heavy_multiplication_x: 
Screenshot 2023-12-11 at 12 06 02 PM


**After:** :heavy_check_mark:  
Screenshot 2023-12-11 at 12 23 28 PM




Hence moving it to `Merge In Progress`

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run Integration Tests,Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Echo** [comment]
Static Tests failure are known failure.
Functional Tests EE,Functional Tests CE,Functional Tests B2B failure are different on last two run on same commit.
Functional Tests B2B
Run1
B@B


Run2
Screenshot 2023-12-11 at 8 01 35 PM

Functional Tests CE
Run1
CE

Run2
ce-2

Functional Tests EE
Run1
EE

Run2
ee-2

Hence moving it to `merge in progress`

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run Semantic Version Checker

**Comment by engcom-Charlie** [comment]
This PR got merged in 015b8dd48e80de606fe15b70ea67aa1b9c157322 commit hence closing this PR now.

**Pull request closed without merging**
