### PR TITLE
Php 5.5 support was removed

### PR DESCRIPTION
**Pull request by ghost**
Removal of php 5.5 support should be reflected in the composer.json.

### CODE REVIEW

**Comment by mazhalai** [comment]
@fooman unfortunately this is not the only composer.json

**Comment by vkublytskyi** [comment]
@fooman Thanks for your commit. We will utilize it. As was pointed by @mazhalai there is another tasks that should be done for removal PHP 5.5 support. Internal ticket MAGETWO-53293 is created for processing this job.

**Comment by mazhalai** [comment]
@vkublytskyi can  you please post the internal ticket number?

**Comment by vkublytskyi** [comment]
Sure. MAGETWO-53293

**Comment by adragus-inviqa** [comment]
Should this be `"~5.6.0|7.0.2|^7.0.6"`?

/cc https://github.com/magento/magento2/issues/4615

**Comment by fooman** [comment]
@adragus-inviqa indeed - have updated the change

@mazhalai I am currently guessing you will need to change this internally as well for all the Enterprise modules so will not update the PR for now to cover the individual module `composer.json`s. Unless you think it makes sense to do so.

**Comment by orlangur** [comment]
@vkublytskyi, please process https://github.com/magento/magento2/pull/4175 together with this PR to have relevant information in all places.

**Pull request merged**
