### PR TITLE
\Error object not handled properly in numerous areas.

### LINKED ISSUE #30149: \Error object not handled properly in numerous areas.
### Preconditions (*)

1. Magento Open Source 2.4-develop

### Steps to reproduce (*)

1. Install fresh copy of Magento 2.4-develop
2. Create new module that has an event observer which listens for the `cms_page_save_after` event. Contents:

```php
<?php

declare(strict_types=1);

namespace VendorName\ModuleName\Observer

class CmsPageSaveAfter
{
    public function execute(Observer $observer)
    {
        if (rand(0, 1)) {
            throw new \Error('this is an instance of \Error and will cause many problems');
        } else {
            $this->causeTypeError(1); // will also break.
        }
    }

    private function causeTypeError(string $foo): void
    {
        // dummy for purposes of reproducing bug
    }
}

```

3. Log into the admin, open a cms page (or begin creating new page) for editing, make any change, and save page.

### Expected result (*)
1. Since `\Magento\Cms\Controller\Adminhtml\Page\Save::execute()` is written to catch objects of `\Throwable`, it should pass to `\Magento\Framework\Message\ManagerInterface` an object that will be accepted.

### Actual result (*)
1. The Save controller catches `\Throwable`, and passes to `ManagerInterface::addExceptionMessage()` an instance of `\Error` (or `\TypeError`, which extends `\Error`), and since `addExceptionMessage()` only accepts objects which are an instance of `\Exception` rather than `\Throwable`, yet another `\TypeError` is thrown. This `\TypeError` trickles up to the catch statement in `\Magento\Framework\App\Bootstrap::run()` which catches objects of `\Throwable`, and the application is terminated.

#### Original expected result:
1. If updating an existing page, `\Magento\Framework\EntityManager\Operation\Update::execute()` should roll back the mysql transaction
2. If creating a new page, `\Magento\Framework\EntityManager\Opteration\Create::execute()` should roll back the mysql transaction
3. On the same note, if this were to happen on a entity where it's ResourceModel still performed CRUD operations using `\Magento\Framework\Model\ResourceModel\Db\AbstractDb::save()`, the transaction should be rolled back here as well.
4. Since `\Magento\Cms\Controller\Adminhtml\Page\Save::execute()` is written to catch objects of `\Throwable`, it should pass to `\Magento\Framework\Message\ManagerInterface` an object that will be accepted.

---

Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

Since this requires customization to the application to occur, I will not mark any of the Severity issues, as I have not found any occurrences where this issue is able to be reproduced from native stock code. However, I believe there to clearly be areas in the core code where revisions are appropriate to handle these situations more properly.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by engcom-Kilo**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/30149

### Manual testing scenarios (*)

1. https://github.com/magento/magento2/issues/30149

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8883](https://jira.corp.magento.com/browse/ENGCOM-8883) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by dmitriyprime** [comment]
:heavy_check_mark:  QA passed

**Before:**
before

**After:**
after

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-32363`.

**Pull request merged**
