### PR TITLE
Fix simple product update not invalidating configurable cache tags

### LINKED ISSUE #36726: [Issue] Fix simple product update not invalidating configurable cache tags
This issue is automatically created based on existing pull request: magento/magento2#36529: Fix simple product update not invalidating configurable cache tags

---------
### Summary

For some stores and setups, when you update a simple product via the REST api all the necessary configurable cache tags are not cleared. This leads us to display stale prices in some parts of the frontend until the caches are manually cleared.

### Description 

This issue was introduced in 2.4.2 https://github.com/magento/magento2/commit/e9b2930401111f7f7ed75ca1e5747d414677492d

The plugin which is meant to add the configurable cache tag when we save the associated simple is broken. It is currently gated so that it only allows configurable products through

https://github.com/magento/magento2/blob/ffeb0a08cd7851d897f849bd25860e3338bcb6b6/app/code/Magento/ConfigurableProduct/Model/Plugin/ProductIdentitiesExtender.php#L44-L58

This means we can only try to look for parents of the parent in `catalog_product_super_link` when a product is saved, I think this does not make sense and we should be looking for simple products to plug into this function.

If a configurable product goes through this `afterGetIdentities` function the query it ends up doing is like this
```sql
SELECT `e`.`entity_id` FROM `catalog_product_super_link` AS `l`
 INNER JOIN `catalog_product_entity` AS `e` ON e.row_id = l.parent_id AND (e.created_in <= '1654849320' AND e.updated_in > '1654849320') WHERE (l.product_id IN(configurable_id_here))
```

Which doesn't make sense based on the schema, because we are looking at `product_id` and not `parent_id`
```sql
mysql> desc catalog_product_super_link;
+------------+------------------+------+-----+---------+----------------+
| Field      | Type             | Null | Key | Default | Extra          |
+------------+------------------+------+-----+---------+----------------+
| link_id    | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| product_id | int(10) unsigned | NO   | MUL | 0       |                |
| parent_id  | int(10) unsigned | NO   | MUL | 0       |                |
+------------+------------------+------+-----+---------+----------------+
```

If a simple product enters this `afterGetIdentities` function, it currently exits early because it doesn't pass the first check.

### Some tech details

On the frontend for our affected instance there are 3 cache entries that need purged for up to date prices to be visible

- `getUsedProductsCache`   
    -  a `collection` cache type
    - has the cache tag like `cat_p_configurable_entity_id`
    - by default has no lifetime, [in new world has 1 year lifetime](https://github.com/magento/magento2/commit/cfa468e7ad2a7e472224cb4591979cc33d6c61d9)
    - Contains the simple products price on the simple product level
- `\Magento\Swatches\Block\Product\Renderer\Configurable` which holds `product_addtocart_form` and `spConfig` 
    - a `block_html` cache type
    - has the cache tag like `cat_p_configurable_entity_id`
    - has a shortish lifetime, maybe 1 hour or 45 mins on this instance? assuming thats default
    - Contains simple product prices
- `\Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox`
    - a `block_html` cache type
    - has the cache tag like `cat_p_configurable_entity_id`
    - has a 24 hour life time
    - contains the simple products price

So when we do a REST API update of the simple product to change the price, we have nothing to trigger a cache tag purge of `cat_p_configurable_entity_id` so the previous frontend values stay.

With this patch in place, when we update the simple product we will trigger a cache tag purge of `cat_p_simple_entity_id` and also `cat_p_configurable_entity_id` so updating prices appear right on my frontend with no interaction.

## To reproduce

I reproduced this on a build of the `2.4-develop` branch.

1. Some config setup

```
# To make seeing this in a the logs a bit clearer
#  we use varnish in prod for full_page
# and we use redis in prod for cache, so doing this emulates that separateness
php bin/magento cache:disable full_page 

# best practice
php bin/magento indexer:set-mode schedule 

# To allow the following curl command to work easily
php bin/magento config:set oauth/consumer/enable_integration_as_bearer 1
```

2. Create an integration token

In the admin panel go `System -> Integrations` and create a new integration with full privs. 
Activate it to get the access token.

3. Create a configurable product

Catalog -> products 
add configurable product, by default you have `color` so I created a `some-product-red` simple sku.

I have products like
```sql
mysql> select entity_id, attribute_set_id, type_id, sku from catalog_product_entity;
+-----------+------------------+--------------+------------------+
| entity_id | attribute_set_id | type_id      | sku              |
+-----------+------------------+--------------+------------------+
|         1 |                4 | simple       | some-product-red |
|         2 |                4 | configurable | some-product     |
+-----------+------------------+--------------+------------------+
2 rows in set (0.01 sec)
```

4. Clear your logs, update the product, see what was invalidated

⚠️  This only works in developer mode for this test ⚠️ 

```
rm var/log/debug.log
```

Replace the following with your own `Bearer` token from above, and your own URL and run it
```
curl -X "POST" "https://example.com/rest/default/V1/products" \
     -H 'Authorization: Bearer ABC123' \
     -H 'Cookie: XDEBUG_SESSION=PHPSTORM' \
     -H 'Content-Type: application/json' \
     -d $'
     {
  "product": {
    "sku": "some-product-red",
    "name": "SOME PRODUCT REC TEST",
    "attribute_set_id": 4,
    "price": 234.56,
    "status": 1,
    "visibility": 1,
    "type_id": "simple",
    "weight": "0.5"
  }
}'; 
'
```

See the results of the `cache_invalidate` logs in `./var/log/debug.log`, see that it only clears the simple product `cat_p_1`

```
$ grep invalidate ./var/log/debug.log  | cut -d',' -f2-
"url":"https://magento-contribution-github.ampdev.co/rest/default/V1/products","invalidateInfo":{"tags":["cat_p_1"],"mode":"matchingAnyTag"}} []
"url":"https://magento-contribution-github.ampdev.co/rest/default/V1/products","invalidateInfo":{"tags":["cat_p_1"],"mode":"matchingAnyTag"}} []
"url":"https://magento-contribution-github.ampdev.co/rest/default/V1/products","invalidateInfo":{"tags":["cat_p_1"],"mode":"matchingAnyTag"}} []
```

With my patch in place we get these results, we can see that it is clearing both `cat_p_2` and `cat_p_1` so both the config and simple.

```
$ grep invalidate ./var/log/debug.log  | cut -d',' -f2-
"url":"https://magento-contribution-github.ampdev.co/rest/default/V1/products","invalidateInfo":{"tags":["cat_p_1","cat_p_2"],"mode":"matchingAnyTag"}} []
"url":"https://magento-contribution-github.ampdev.co/rest/default/V1/products","invalidateInfo":{"tags":["cat_p_1","cat_p_2"],"mode":"matchingAnyTag"}} []
"url":"https://magento-contribution-github.ampdev.co/rest/default/V1/products","invalidateInfo":{"tags":["cat_p_1","cat_p_2"],"mode":"matchingAnyTag"}} []
```

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by convenient**
### Summary

For some stores and setups, when you update a simple product via the REST api all the necessary configurable cache tags are not cleared. This leads us to display stale prices in some parts of the frontend until the caches are manually cleared.

### Description 

This issue was introduced in 2.4.2 https://github.com/magento/magento2/commit/e9b2930401111f7f7ed75ca1e5747d414677492d

The plugin which is meant to add the configurable cache tag when we save the associated simple is broken. It is currently gated so that it only allows configurable products through

https://github.com/magento/magento2/blob/ffeb0a08cd7851d897f849bd25860e3338bcb6b6/app/code/Magento/ConfigurableProduct/Model/Plugin/ProductIdentitiesExtender.php#L44-L58

This means we can only try to look for parents of the parent in `catalog_product_super_link` when a product is saved, I think this does not make sense and we should be looking for simple products to plug into this function.

If a configurable product goes through this `afterGetIdentities` function the query it ends up doing is like this
```sql
SELECT `e`.`entity_id` FROM `catalog_product_super_link` AS `l`
 INNER JOIN `catalog_product_entity` AS `e` ON e.row_id = l.parent_id AND (e.created_in <= '1654849320' AND e.updated_in > '1654849320') WHERE (l.product_id IN(configurable_id_here))
```

Which doesn't make sense based on the schema, because we are looking at `product_id` and not `parent_id`
```sql
mysql> desc catalog_product_super_link;
+------------+------------------+------+-----+---------+----------------+
| Field      | Type             | Null | Key | Default | Extra          |
+------------+------------------+------+-----+---------+----------------+
| link_id    | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| product_id | int(10) unsigned | NO   | MUL | 0       |                |
| parent_id  | int(10) unsigned | NO   | MUL | 0       |                |
+------------+------------------+------+-----+---------+----------------+
```

If a simple product enters this `afterGetIdentities` function, it currently exits early because it doesn't pass the first check.

### Some tech details

On the frontend for our affected instance there are 3 cache entries that need purged for up to date prices to be visible

- `getUsedProductsCache`   
    -  a `collection` cache type
    - has the cache tag like `cat_p_configurable_entity_id`
    - by default has no lifetime, [in new world has 1 year lifetime](https://github.com/magento/magento2/commit/cfa468e7ad2a7e472224cb4591979cc33d6c61d9)
    - Contains the simple products price on the simple product level
- `\Magento\Swatches\Block\Product\Renderer\Configurable` which holds `product_addtocart_form` and `spConfig` 
    - a `block_html` cache type
    - has the cache tag like `cat_p_configurable_entity_id`
    - has a shortish lifetime, maybe 1 hour or 45 mins on this instance? assuming thats default
    - Contains simple product prices
- `\Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox`
    - a `block_html` cache type
    - has the cache tag like `cat_p_configurable_entity_id`
    - has a 24 hour life time
    - contains the simple products price

So when we do a REST API update of the simple product to change the price, we have nothing to trigger a cache tag purge of `cat_p_configurable_entity_id` so the previous frontend values stay.

With this patch in place, when we update the simple product we will trigger a cache tag purge of `cat_p_simple_entity_id` and also `cat_p_configurable_entity_id` so updating prices appear right on my frontend with no interaction.

## To reproduce

I reproduced this on a build of the `2.4-develop` branch.

1. Some config setup

```
# To make seeing this in a the logs a bit clearer
#  we use varnish in prod for full_page
# and we use redis in prod for cache, so doing this emulates that separateness
php bin/magento cache:disable full_page 

# best practice
php bin/magento indexer:set-mode schedule 

# To allow the following curl command to work easily
php bin/magento config:set oauth/consumer/enable_integration_as_bearer 1
```

2. Create an integration token

In the admin panel go `System -> Integrations` and create a new integration with full privs. 
Activate it to get the access token.

3. Create a configurable product

Catalog -> products 
add configurable product, by default you have `color` so I created a `some-product-red` simple sku.

I have products like
```sql
mysql> select entity_id, attribute_set_id, type_id, sku from catalog_product_entity;
+-----------+------------------+--------------+------------------+
| entity_id | attribute_set_id | type_id      | sku              |
+-----------+------------------+--------------+------------------+
|         1 |                4 | simple       | some-product-red |
|         2 |                4 | configurable | some-product     |
+-----------+------------------+--------------+------------------+
2 rows in set (0.01 sec)
```

4. Clear your logs, update the product, see what was invalidated

⚠️  This only works in developer mode for this test ⚠️ 

```
rm var/log/debug.log
```

Replace the following with your own `Bearer` token from above, and your own URL and run it
```
curl -X "POST" "https://example.com/rest/default/V1/products" \
     -H 'Authorization: Bearer ABC123' \
     -H 'Cookie: XDEBUG_SESSION=PHPSTORM' \
     -H 'Content-Type: application/json' \
     -d $'
     {
  "product": {
    "sku": "some-product-red",
    "name": "SOME PRODUCT REC TEST",
    "attribute_set_id": 4,
    "price": 234.56,
    "status": 1,
    "visibility": 1,
    "type_id": "simple",
    "weight": "0.5"
  }
}'; 
'
```

See the results of the `cache_invalidate` logs in `./var/log/debug.log`, see that it only clears the simple product `cat_p_1`

```
$ grep invalidate ./var/log/debug.log  | cut -d',' -f2-
"url":"https://magento-contribution-github.ampdev.co/rest/default/V1/products","invalidateInfo":{"tags":["cat_p_1"],"mode":"matchingAnyTag"}} []
"url":"https://magento-contribution-github.ampdev.co/rest/default/V1/products","invalidateInfo":{"tags":["cat_p_1"],"mode":"matchingAnyTag"}} []
"url":"https://magento-contribution-github.ampdev.co/rest/default/V1/products","invalidateInfo":{"tags":["cat_p_1"],"mode":"matchingAnyTag"}} []
```

With my patch in place we get these results, we can see that it is clearing both `cat_p_2` and `cat_p_1` so both the config and simple.

```
$ grep invalidate ./var/log/debug.log  | cut -d',' -f2-
"url":"https://magento-contribution-github.ampdev.co/rest/default/V1/products","invalidateInfo":{"tags":["cat_p_1","cat_p_2"],"mode":"matchingAnyTag"}} []
"url":"https://magento-contribution-github.ampdev.co/rest/default/V1/products","invalidateInfo":{"tags":["cat_p_1","cat_p_2"],"mode":"matchingAnyTag"}} []
"url":"https://magento-contribution-github.ampdev.co/rest/default/V1/products","invalidateInfo":{"tags":["cat_p_1","cat_p_2"],"mode":"matchingAnyTag"}} []
```

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36726: Fix simple product update not invalidating configurable cache tags

### CODE REVIEW

**Comment by convenient** [comment]
@magento run Integration Tests, Functional Tests EE

```
There was 1 error:

1) Magento\CustomerSegment\Model\SegmentMatchConsumerTest::testGetCustomerWebsiteSegmentsAccountSharingEnabled
Magento\TestFramework\MessageQueue\PreconditionFailedException: No asynchronous messages were processed.

/var/www/html/dev/tests/integration/framework/Magento/TestFramework/MessageQueue/PublisherConsumerController.php:212
/var/www/html/dev/tests/integration/testsuite/Magento/CustomerSegment/Model/SegmentMatchConsumerTest.php:116
/var/www/html/dev/tests/integration/testsuite/Magento/CustomerSegment/Model/SegmentMatchConsumerTest.php:174

ERRORS!
Tests: 62, Assertions: 151, Errors: 1.

```

```
MAGETWO-91893: Product attribute is not visible on storefront if it is empty
```

**Comment by convenient** [comment]
@magento run Functional Tests B2B

**Comment by convenient** [comment]
@magento run Functional Tests B2B

**Comment by convenient** [comment]
@magento run Functional Tests B2B

```
AC-3635: Verify that Local cache storage is retained for the expected period.
```

**Comment by convenient** [comment]
Deployed this to production and it is working well, we are no longer seeing stale prices and similar oddities.

**Comment by andrewbess** [comment]
@magento run all tests

**Review by andrewbess — APPROVED** [review]
Hello @convenient 
Thank you for your contribution.

Changes look good for me

**Comment by convenient** [comment]
@andrewbess checks finally gone green 😆 🎉

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento `2.4-develop`

**Manual testing scenario:**

1. Updated the product using rest api.

**Before:** :heavy_multiplication_x:  Cache were not getting cleared for both the products.
Screenshot 2023-01-10 at 7 54 26 PM


**After:** :heavy_check_mark:  Now it is happening.
Screenshot 2023-01-10 at 8 06 33 PM

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by andrewbess** [comment]
> @andrewbess checks finally gone green 😆 🎉

Thank you.
It were random failures of MFTF

**Comment by engcom-Charlie** [comment]
It seems bot moved this PR to Ready for Testing from Merge In Progress, hence moving it back.

Thank you!

**Comment by manhtranisobar** [comment]
Hello,
There is an issue after apply code from this pull request. These is reproduce steps:

- Create 2 website: w1 and w2 
- Create 2 admin users: user1 have full permission, user2 have permission at website w2 only 
- Login with user1 
- Create a simple product sp1 and assign to both of w1 and w2 
- Create a configurable product with single child is simple product sp1 and assign configurable product to website w1 only 
- Logout user1 and login with user2 
- Edit simple product sp1 at website scope (w2), change product name and save 

**Expectation**: User2 save simple product sp1 successfully 
**Actual**: Error message appear: More permissions are needed to view this item.

**Pull request merged**
