### PR TITLE
Fixed set template syntax issue

### PR DESCRIPTION
**Pull request by gelanivishal**
### Description

I have added module name on a template file as per Magento standard coding format.

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios

I have changed all Magneto Backend module template. so You can check after login on Magento Dashboard. 

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by miguelbalparda** [comment]
Can you please edit the PR and complete the template? This is not going to be processed until then. Thanks!

**Comment by gelanivishal** [comment]
@miguelbalparda I'm not getting you. Can you please elaborate?

**Comment by miguelbalparda** [comment]
There is a template you didn't complete when you submitted the PR.

> Description
> 
> Fixed set template syntax in block file
> Fixed Issues (if relevant)
> 
> N/A
> Manual testing scenarios
> 
> N/A

Please edit the description and fill in the details. Thanks!

**Comment by miguelbalparda** [comment]
@vgelani please remember to fill the template so we can proceed with the merge. Thanks!

**Comment by gelanivishal** [comment]
@miguelbalparda I have updated. Let me know if you want to change or update anything. 
Thank you

**Comment by magento-engcom-team** [comment]
Hi @vgelani. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

Please, consider porting this solution across release lines.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
