### PR TITLE
Fix failing / warnings in unit tests

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
`2.4.1-develop` branch contains failing Unit tests - I've fixed that in scope of PR
Also - On 5th of June new version (`9.2` of PHPUnit was released) I've upgraded it.

```
OK, but incomplete, skipped, or risky tests!
Tests: 15243, Assertions: 45840, Skipped: 87, Incomplete: 40.
```

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Review by rogyar — DISMISSED** [review]
@lbajsarowicz good job!

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7632](https://jira.corp.magento.com/browse/ENGCOM-7632) has been created to process this Pull Request

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @lbajsarowicz . Could you resolve merge conflicts?
 Thanks!

**Comment by lbajsarowicz** [comment]
I see that Magento Functional Testing Framework RC4 is coming, so probably we will need to resolve `composer.lock` a few more times.

```bash
composer update --with-dependencies allure-framework/allure-phpunit dealerdirect/phpcodesniffer-composer-installer friendsofphp/php-cs-fixer lusitanian/oauth magento/magento-coding-standard pdepend/pdepend phpcompatibility/php-compatibility phpmd/phpmd phpstan/phpstan phpunit/phpunit sebastian/phpcpd squizlabs/php_codesniffer
```

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Another upgrade - PHPUnit 9.2.5**

```
  - Removing braintree/braintree_php (3.35.0)
Removing Braintree/Braintree_php
  - Updating laminas/laminas-dependency-plugin (1.0.3 => 1.0.4): Loading from cache
  - Updating react/promise (v2.7.1 => v2.8.0): Loading from cache
  - Updating elasticsearch/elasticsearch (v7.6.1 => v7.7.0): Loading from cache
  - Updating laminas/laminas-zendframework-bridge (1.0.3 => 1.0.4): Loading from cache
  - Updating magento/zendframework1 (1.14.3 => 1.14.4): Loading from cache
  - Updating symfony/css-selector (v5.0.8 => v5.1.0): Loading from cache
  - Updating symfony/polyfill-ctype (v1.15.0 => v1.17.1): Loading from cache
  - Updating symfony/filesystem (v5.0.8 => v5.1.0): Loading from cache
  - Updating symfony/polyfill-php72 (v1.15.0 => v1.17.0): Loading from cache
  - Updating symfony/polyfill-php73 (v1.15.0 => v1.17.0): Loading from cache
  - Updating doctrine/lexer (1.2.0 => 1.2.1): Loading from cache
  - Updating doctrine/annotations (1.10.2 => 1.10.3): Loading from cache
  - Updating doctrine/cache (1.10.0 => 1.10.1): Loading from cache
  - Updating league/flysystem (1.0.67 => 1.0.69): Loading from cache
  - Installing symfony/polyfill-php80 (v1.17.0): Loading from cache
  - Updating symfony/polyfill-mbstring (v1.15.0 => v1.17.0): Loading from cache
  - Updating symfony/polyfill-intl-idn (v1.15.0 => v1.17.0): Loading from cache
  - Updating symfony/mime (v5.0.8 => v5.1.0): Loading from cache
  - Updating symfony/finder (v5.0.8 => v5.1.2): Loading from cache
  - Installing thecodingmachine/safe (v1.1.1): Loading from cache
  - Installing paragonie/constant_time_encoding (v2.3.0): Loading from cache
  - Installing beberlei/assert (v3.2.7): Loading from cache
  - Installing spomky-labs/otphp (v10.0.1): Loading from cache
  - Updating monolog/monolog (1.25.3 => 1.25.4): Loading from cache
  - Installing symfony/deprecation-contracts (v2.1.2): Loading from cache
  - Updating symfony/yaml (v5.0.8 => v5.1.0): Loading from cache
  - Updating sebastian/type (2.0.0 => 2.1.0): Loading from cache
  - Updating sebastian/resource-operations (3.0.0 => 3.0.1): Loading from cache
  - Updating sebastian/recursion-context (4.0.0 => 4.0.1): Loading from cache
  - Updating sebastian/object-reflector (2.0.0 => 2.0.1): Loading from cache
  - Updating sebastian/object-enumerator (4.0.0 => 4.0.1): Loading from cache
  - Updating sebastian/exporter (4.0.0 => 4.0.1): Loading from cache
  - Updating sebastian/environment (5.1.0 => 5.1.1): Loading from cache
  - Updating sebastian/diff (4.0.0 => 4.0.1): Loading from cache
  - Updating sebastian/comparator (4.0.0 => 4.0.2): Loading from cache
  - Updating sebastian/code-unit (1.0.2 => 1.0.3): Loading from cache
  - Updating phpunit/php-timer (3.1.4 => 5.0.0): Loading from cache
  - Updating phpunit/php-text-template (2.0.0 => 2.0.1): Loading from cache
  - Updating phpunit/php-invoker (3.0.0 => 3.0.1): Loading from cache
  - Updating phpunit/php-file-iterator (3.0.1 => 3.0.2): Loading from cache
  - Updating sebastian/code-unit-reverse-lookup (2.0.0 => 2.0.1): Loading from cache
  - Updating phpunit/php-token-stream (4.0.1 => 4.0.2): Loading from cache
  - Updating phpunit/php-code-coverage (8.0.1 => 8.0.2): Loading from cache
  - Updating webmozart/assert (1.8.0 => 1.9.0): Loading from cache
  - Updating phpdocumentor/type-resolver (1.1.0 => 1.2.0): Loading from cache
  - Updating doctrine/instantiator (1.3.0 => 1.3.1): Loading from cache
  - Updating phpunit/phpunit (9.1.4 => 9.2.5): Loading from cache
  - Updating codeception/codeception (4.1.4 => 4.1.5): Loading from cache
  - Updating codeception/module-webdriver (1.0.8 => 1.1.0): Loading from cache
  - Updating aws/aws-sdk-php (3.137.5 => 3.140.2): Loading from cache
  - Updating symfony/http-foundation (v5.0.8 => v5.1.0): Loading from cache
  - Updating magento/magento2-functional-testing-framework (dev-3.0.0-RC2 b525101 => 3.0.0-RC5): Loading from cache
  - Downgrading sebastian/phpcpd (5.0.2 => 2.0.1): Loading from cache
  - Updating symfony/polyfill-php70 (v1.15.0 => v1.17.0): Loading from cache
```

The sad part is that I had to downgrade 
```
  - Downgrading sebastian/phpcpd (5.0.2 => 2.0.1): Loading from cache
```
 as Sebastian Bermann does not care ( https://github.com/sebastianbergmann/phpcpd/issues/180 ) about compatibility

**Comment by lbajsarowicz** [comment]
@magento run Sample Data Tests CE, Functional Tests CE

**Comment by lbajsarowicz** [comment]
I am unable to resolve conflicts anymore.

I mean there is something introduced with regular dependencies which causes set of conflicts during `composer update` or `composer require` I'll revert the changes to `composer.json` and `composer.lock` leaving only fixes to tests.

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

Fun fact: My PR is hanging for 2 months already, but most of the same changes performed last week (https://github.com/magento/magento2/pull/29244/files) were already merged.

What is more fun: The Magento 2.4 was released with the Unit Test bugs, even though the fix was already there :clap:

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7632](https://jira.corp.magento.com/browse/ENGCOM-7632) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Echo** [comment]
@magento run all tests

**Pull request merged**
