### PR TITLE
Om debuginfo

### PR DESCRIPTION
**Pull request by kandy**
### Description (*)
Improve developer experience by avoiding dump unneeded information

### Manual testing scenarios (*)
Run php scipt
```
<?php
use Magento\Framework\App\Bootstrap;
require __DIR__ . '/app/bootstrap.php';

$bootstrap = Bootstrap::create(BP, $_SERVER);
$om = $bootstrap->getObjectManager();

$state = $om->get('Magento\Framework\App\State');
$state->setAreaCode('frontend');
$pc = $om->get(\Magento\Catalog\Model\ResourceModel\Product\Collection::class)
    ->setPageSize(10)
    ->load();
var_dump($pc);
```
Script output only 60kb of text

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6909](https://jira.corp.magento.com/browse/ENGCOM-6909) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @ihor-sviziev. Could you review the latest changes?
 Thanks

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @kandy,
Could you fix static test failures?

**Comment by ihor-sviziev** [comment]
@kandy still tests failing...

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6909](https://jira.corp.magento.com/browse/ENGCOM-6909) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Review by ihor-sviziev — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6909](https://jira.corp.magento.com/browse/ENGCOM-6909) has been created to process this Pull Request

**Comment by slavvka** [comment]
There are multiple performance degradations:
```
Process categories ids                                           1.00ms     +0.0%      (+0ms)     ok
API - Get color values ids                                       55.00ms    -1.8%      (-1ms)     ok
Query multiple products                                          150.00ms   -0.7%      (-1ms)     ok
Query simple product                                             116.00ms   +0.0%      (+0ms)     ok
Query configurable product                                       155.00ms   +0.0%      (+0ms)     ok
Query products with full text search and filter                  2277.00ms  +3.1%      (+69ms)    DEGRADATION
Query products with full text search and filter last page        746.00ms   +2.6%      (+19ms)    ok
Query products with full text search only                        2266.00ms  +3.1%      (+69ms)    DEGRADATION
Query products with full text search and filters                 2131.00ms  +3.2%      (+66ms)    DEGRADATION
Query products with full text search and aggregations            2105.00ms  +3.1%      (+64ms)    DEGRADATION
Query bundle product                                             165.00ms   +0.0%      (+0ms)     ok
Query downloadable product                                       120.00ms   -0.8%      (-1ms)     ok
Query virtual product                                            113.00ms   -0.9%      (-1ms)     ok
Query grouped product                                            173.00ms   +0.0%      (+0ms)     ok
Query Category                                                   97.00ms    -1.0%      (-1ms)     ok
Query CategoryList                                               97.00ms    +1.0%      (+1ms)     ok
Get Cms Page by id                                               49.00ms    +0.0%      (+0ms)     ok
```

**Comment by lenaorobei** [comment]
Running performance build for this branch.

**Comment by lenaorobei** [comment]
@kandy I see that no other that merge commits were added. Could you please address performance degradation?

**Review by lenaorobei — CHANGES_REQUESTED** [review]
@kandy I see no other than merge commits were added. Could you please address performance degradation?

**Comment by lenaorobei** [comment]
Here is the most resent performance build:
```
Query products with full text search and filter                  2210.00ms  +3.7%      (+79ms)    DEGRADATION
Query products with full text search only                        2204.00ms  +3.6%      (+76ms)    DEGRADATION
Query products with full text search and filters                 2084.00ms  +3.3%      (+67ms)    DEGRADATION
Query products with full text search and aggregations            2064.00ms  +3.8%      (+75ms)    DEGRADATION
```

**Comment by lenaorobei** [comment]
@kandy are you going to continue working on it?

**Comment by lenaorobei** [comment]
Closing this PR due to inactivity. Please feel free to reopen if you are going to continue working on it.
Thank you.

**Pull request closed without merging**
