### PR TITLE
[Backport] Fixed-Bundle-Product-add-to-cart-button-misaligned-2.2

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Description (*)

#20193
### Fixed Issues (if relevant)

1. magento/magento2#20195: Bundle Product add to cart button misaligned on tab portrait view
2. Magento 2.2

### Manual testing scenarios (*)

1. In product detail page on "Bundle Product" click "Customize and Add to Cart" show bundle option check "add to cart" button.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

Backport for: https://github.com/magento/magento2/pull/20195

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by amol2jcommerce** [comment]
Hi @magento-engcom-team please review.

**Comment by amol2jcommerce** [comment]
@magento-engcom-team please review.

**Comment by amol2jcommerce** [comment]
@magento-engcom-team please review.

**Comment by torhoehn** [comment]
@magento-engcom-team give me test instanc

**Comment by torhoehn** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @torhoehn. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @torhoehn, here is your [new Magento instance](https://pr-20554.instances.magento-community.engineering).
Admin access: [https://pr-20554.instances.magento-community.engineering/admin](https://pr-20554.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by torhoehn — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @torhoehn, thank you for the review.
[ENGCOM-4143](https://jira.corp.magento.com/browse/ENGCOM-4143) has been created to process this Pull Request

**Pull request merged**
