### PR TITLE
Fix Report date doesn't matching in configuration setting

### PR DESCRIPTION
**Pull request by Priya-V-Panchal**
### Description (*)
Report Value doesn't matching - "Year-To-Date Starts" in reports configuration

### Fixed Issues (if relevant)

1. magento/magento2#27086: Report Value doesn't matching - "Year-To-Date Starts"

### Manual testing scenarios (*)

1. Login to Adminpanel.
2. Go to Stores >> Configuration >> General >> Reports
3. From Dashboard tab >> Select "Year-To-Date Starts".

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @Priya-V-Panchal. Thank you for your contribution. According to the last updates to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#tests) all changes should be covered by automated tests. 
Could I kindly ask you to cover your changes by an MFTF test?

Thank you.

**Comment by eduard13** [comment]
Hi @Priya-V-Panchal, are you willing to continue working on this one?

**Review by eduard13 — APPROVED** [review]
Looks good.
Thank you @engcom-Charlie for the adjustments.

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-7110](https://jira.corp.magento.com/browse/ENGCOM-7110) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Pull request merged**
