### PR TITLE
Fixed magnifier issue.

### PR DESCRIPTION
**Pull request by nimitaemipro**
### Fixed Issues (if relevant)

1. magento/magento2#5129: Product details page zoom issue when dropdown menu have overlap area with it.

### Manual testing scenarios

1. Modify app/design/Magento/luma/etc/view.xml to enable product gallery zoom,
2. Please follow issue number #5129 .

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=13035) <br/>All committers have signed the CLA.

**Comment by omiroshnichenko** [comment]
Hi, @nimitaemipro. Thanks for fix. But, can you change from `$($box).on()` to `$box.on()`, because `$box` is already jQuery object.

**Comment by ishakhsuvarov** [comment]
@omiroshnichenko @nimitaemipro I've updated code per review and will now proceed with the manual testing and merging.
Thank you.

**Comment by okorshenko** [comment]
closing this PR. Head branch should be created in the fork but not in the magento2 repository

**Pull request closed without merging**
