### PR TITLE
WIP: [Ui] Clear date range filter by Clear button

### LINKED ISSUE #32456: Admin Grid date range filter not working as expected
### Preconditions (*)

1. Magento 2.4.1

### Steps to reproduce (*)

1. In Backend select "Sales/Orders".
2. Click on "Filters" and add a date range filter for "purchase date" and apply this filter. The filtered grid will appear as expected.
3. Click on "Clear all" to remove this filter
filter2

### Expected result (*)

After removing the filter the date range should be cleared when you click next time on "Filters". 

### Actual result (*)

The date range is still filled out. Even worse, if you click next time on "Apply filters" (without modifying the date range), this date range is not applied.

filter

- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Den4ik**
### Description (*)

Recreation of https://github.com/magento/magento2/pull/33027

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/32456

### Manual testing scenarios (*)

1. See https://github.com/magento/magento2/issues/32456

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Den4ik** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Please fix failing tests

**Comment by Den4ik** [comment]
@ihor-sviziev working on fix

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@engcom-Bravo  I'll recheck and update this PR to main line today

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run WebAPI Tests

**Comment by ihor-sviziev** [comment]
@Den4ik,
Will you be able to finalize your PR?

**Comment by Den4ik** [comment]
Hi @ihor-sviziev 
I plan to finish next PRs in this month:
1. https://github.com/magento/magento2/pull/32090
2. https://github.com/magento/magento2/pull/33591
3. https://github.com/magento/magento2/pull/33135
4. https://github.com/magento/magento2/pull/33249

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Unit Tests

**Comment by Den4ik** [comment]
@magento run WebAPI Tests, Static Tests, Semantic Version Checker, Sample Data Tests EE, Sample Data Tests B2B, Sample Data Tests CE, Magento Health Index, Integration Tests, Database Compare

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

**Comment by Den4ik** [comment]
@magento run Functional Tests CE

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @Den4ik,

Thank you for your contribution!

In order to proceed with this PR, first tried to reproduce the issue on latest magento 2.4-develop.

Followed mentioned reproduction steps in PR and found that the issue is not reproducible in the latest magento code base.

1. In Backend selected Sales > Orders section.
2. Clicked on "Filters”. Applied the date range filter on "purchase date”. 
image

3. Clicked on "Clear all" to remove this filter

After removing the filter, when clicked on Filters again, found that the date range is cleared. 
image

The issue is not reproducible as the applying and removing of the filter is working fine, closing this PR.

Please reopen and update if you wish to continue.

Thank you for your contribution.

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Comment by Den4ik** [comment]
@engcom-Charlie Thanks for the update. Yep, issue was fixed

**Pull request closed without merging**
