### PR TITLE
Resolve Coupon code text field not display in proper width in Internet Explorer/EDGE browser issue26133

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. magento/magento2#26133: Coupon code text field not display in proper width in Internet Explorer/EDGE browser

### Fixed Issues (if relevant)

1. magento/magento2#26133: Coupon code text field not display in proper width in Internet Explorer/EDGE browser

### Manual testing scenarios (*)

Review the coupon code section in IE or Edge browser

#### Expected result
It should display same as per chrome/firefox browsers

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by aleron75** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @aleron75. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @aleron75, here is your [new Magento instance](https://pr-26144.instances.magento-community.engineering).
Admin access: [https://pr-26144.instances.magento-community.engineering/admin](https://pr-26144.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by aleron75** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @aleron75. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @aleron75, here is your [Magento instance](https://i-26144-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26144-2-4-develop.instances.magento-community.engineering/admin](https://i-26144-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by aleron75 — APPROVED** [review]
I verified on edge 18.0 (latest) on Win 10 that the bug disappeared (screenshot attached below). 
Good job!

Selection_008

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-6516](https://jira.corp.magento.com/browse/ENGCOM-6516) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
Hi @edenduong I have checked PR changes and there is issue with placeholder for discount input field when resolution is 800x1280
**2.4-develop ( Before )**
#26144Main

**PR ( After )**
#26144PR

Could you take a look?

**Comment by ptylek** [comment]
@edenduong, I am closing this PR now due to inactivity. Please reopen and update if you wish to continue.Thank you for collaboration

**Comment by edenduong** [comment]
I will continue to fix this issue :)

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-26144.instances.magento-community.engineering).
Admin access: [https://pr-26144.instances.magento-community.engineering/admin_c90e](https://pr-26144.instances.magento-community.engineering/admin_c90e)
Login: `9c3ed7cc` Password: `b1af671c7971`
Instance will be terminated in up to 3 hours.

**Comment by edenduong** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [Magento instance](https://i-26144-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26144-2-4-develop.instances.magento-community.engineering/admin_191c](https://i-26144-2-4-develop.instances.magento-community.engineering/admin_191c)
Login: `0b967a16` Password: `6dd837e6c47a`
Instance will be terminated in up to 3 hours.

**Comment by edenduong** [comment]
I will close this PR because I am not sure about my solution.

**Pull request closed without merging**
