### PR TITLE
Major Quote Bugfix

### PR DESCRIPTION
**Pull request by christopher-silvey**
Logged in customer was returning null for $customerId. See Issue #24391 for more details.

### CODE REVIEW

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi, @beckindesigns. Thanks for collaboration. Please use short syntax `?:`

**Comment by christopher-silvey** [comment]
> Hi, @beckindesigns. Thanks for collaboration. Please use short syntax `?:`

No problem and I did already :)

`$this->doValidate($address, $cart->getCustomer()->getId() ? $cart->getCustomer()->getId() : false);`

Unless you are asking me to move it outside of the call to the doValidate() function.

**Comment by southerncomputer** [comment]
might want to check if $cart is valid too

**Comment by christopher-silvey** [comment]
> might want to check if $cart is valid too

I made another commit here and tested it very heavily. Everything seems to be good. 

Also, I accidentally created a separate patch. How in the world can I delete it? (https://github.com/beckindesigns/magento2/blob/patch-2/app/code/Magento/Quote/i18n/en_US.csv) I don't need the patch-2 branch b/c I figured out how to do add those changes inside this same pull request. This pull request should contain two files now :)

**Comment by christopher-silvey** [comment]
Any update on this? Anything I need to do?

**Comment by sidolov** [comment]
Hi @magentoman2009  , looks like you made some commits with email different than in your GitHub profile, please, add email from commits to your profile!
Thank you!

**Comment by christopher-silvey** [comment]
> Hi @magentoman2009 , looks like you made some commits with email different than in your GitHub profile, please, add email from commits to your profile!
> Thank you!

I'm not 100% sure which email that was but I just added another email to my account that I think was probably the one you are talking about. Let me know if that looks right now.

Thanks!

**Comment by sidolov** [comment]
@magentoman2009 in this case you can soft reset your branch, make a new commit with email saved in GitHub account and force push the branch. CLA is mandatory for all contributions and we are not allowed to process your PR without it. 
Thank you!

**Comment by christopher-silvey** [comment]
I think there may be some confusion on your end b/c I have already accepted the CLA when I created the PR. I also just confirmed the same account/email made all 4 commits. I did change my username recently but my email address and etc remained the same.

Screen Shot 2019-09-21 at 11 13 11 AM

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24465) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=24465) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: magentoman2009<br/>:x: Christopher Silvey<hr/>**Christopher Silvey** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by christopher-silvey** [comment]
I moved this PR to here: https://github.com/magento/magento2/pull/24685 in order to fix CLA issues.

**Pull request closed without merging**
