### PR TITLE
[MFTF] add new  AdminOpenCatalogSearchTermIndexPageActionGroup

### LINKED ISSUE #29844: [Issue] [MFTF] add new  AdminOpenCatalogSearchTermIndexPageActionGroup
This issue is automatically created based on existing pull request: magento/magento2#29831: [MFTF] add new  AdminOpenCatalogSearchTermIndexPageActionGroup

---------
This PR add new `AdminOpenCatalogSearchTermIndexPageActionGroup` and use this one instead 
`<amOnPage url="{{AdminCatalogSearchTermIndexPage.url}}" stepKey="openAdminCatalogSearchTermIndexPage"/>`
           ` <waitForPageLoad stepKey="waitForAdminCatalogSearchTermIndexPageLoad"/>`

### PR DESCRIPTION
**Pull request by Usik2203**
This PR add new `AdminOpenCatalogSearchTermIndexPageActionGroup` and use this one instead 
`<amOnPage url="{{AdminCatalogSearchTermIndexPage.url}}" stepKey="openAdminCatalogSearchTermIndexPage"/>`
           ` <waitForPageLoad stepKey="waitForAdminCatalogSearchTermIndexPageLoad"/>`

### Resolved issues:
1. [x] resolves magento/magento2#29844: [MFTF] add new  AdminOpenCatalogSearchTermIndexPageActionGroup

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run Functional Tests CE , Functional Tests EE , Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8128](https://jira.corp.magento.com/browse/ENGCOM-8128) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Pull request merged**
