### PR TITLE
Resolved issue coupon codes don't work anymore #18183

### PR DESCRIPTION
**Pull request by this-adarsh**
### Fixed Issues (if relevant)

1. magento/magento2#18183: Issue title
2. coupon codes don't work anymore

### Manual testing scenarios (*)

1. Create a coupon code.
2. Set from & to date 2018  to 2088 respectively.
3. Apply coupon code.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by this-adarsh** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @this-adarsh. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22718) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @this-adarsh, here is your [new Magento instance](https://pr-22718.instances.magento-community.engineering).
Admin access: [https://pr-22718.instances.magento-community.engineering/admin](https://pr-22718.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by ronak2ram** [comment]
Hi @this-adarsh, please, sign CLA, otherwise, we can't process your pull request

**Comment by rogyar** [comment]
@ronak2ram please note that changing a DB column type is backward incompatible change

**Comment by rogyar** [comment]
For QA. 
I've mentioned that changing the DB column is a backward incompatible change. However, in this case technically it should not bring problems since the timestamp -> datetime types in MySQL are almost identical. In terms with Magento persistence layer, there's no difference as well.

Timestamps in MySQL are generally used to track changes to records the coupon expiration date is not the case. So I believe we should use datetime here. Especially considering the fact that this change fixes the future date issue.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-5086](https://jira.corp.magento.com/browse/ENGCOM-5086) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
