### PR TITLE
Removed CliCacheFlushActionGroup usage for Customer module

### LINKED ISSUE #32079: [Issue] Removed CliCacheFlushActionGroup usage for Customer module
This issue is automatically created based on existing pull request: magento/magento2#32078: Removed CliCacheFlushActionGroup usage for Customer module

---------
### Description
Removed CliCacheFlushActionGroup usage (or changed value) for Checkout, CurrencySymbol and Customer modules.

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Removed CliCacheFlushActionGroup usage (or changed value) for Checkout, CurrencySymbol and Customer modules.

### Resolved issues:
1. [x] resolves magento/magento2#32079: Removed CliCacheFlushActionGroup usage for Customer module

### CODE REVIEW

**Comment by sergiy-v** [comment]
@magento create issue

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Semantic Version Checker

**Comment by sergiy-v** [comment]
Will check failed tests.

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE

**Comment by sergiy-v** [comment]
@magento run WebAPI Tests, Unit Tests, Static Tests, Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B, Magento Health Index, Integration Tests, Database Compare

**Comment by sergiy-v** [comment]
Looks like it was temporary issues, now all tests are green, @coderimus please proceed with review.
Thank you.

**Review by coderimus — APPROVED** [review]
@sergiy-v thank you for the adjustments. Approve 👍

**Comment by magento-engcom-team** [comment]
Hi @coderimus, thank you for the review.
[ENGCOM-8788](https://jira.corp.magento.com/browse/ENGCOM-8788) has been created to process this Pull Request
:eight_spoked_asterisk: @coderimus, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Bravo** [comment]
Manual QA not applicable. Moving this PR to the _Extended Testing_ column

**Pull request merged**
