### PR TITLE
Fix split button in order view page

### LINKED ISSUE #39080: [Issue] Fix split button in order view page
This issue is automatically created based on existing pull request: magento/magento2#39078: Fix split button in order view page

---------

### Description (*)
This PR adds a fix for split buttons used in layout `admin-2columns-left.xml`
The bug was added by [6ed18327](https://github.com/magento/magento2/commit/6ed183273dd5bc9ae48c73dc9bfc27122b9c8bee) so this is a rollback of changes.
Admin Panel is not for mobile so no need to add any changes to fix issues on mobile/tablet.
Here is the video of the issue:

https://github.com/user-attachments/assets/84420833-ac5e-4172-93fe-173fa445bd8a

### Related Pull Requests
None

### Fixed Issues (if relevant)
None

### Manual testing scenarios (*)
1. Create a custom split button on order view page.
2. Go to Frontend and place an order
3. Go to Admin Panel -> Sales -> Orders
4. Go to the order view page.

### Questions or comments
None

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by SerhiiMandrykin**
### Description (*)
This PR adds a fix for split buttons used in layout `admin-2columns-left.xml`
The bug was added by [6ed18327](https://github.com/magento/magento2/commit/6ed183273dd5bc9ae48c73dc9bfc27122b9c8bee) so this is a rollback of changes.
Admin Panel is not for mobile so no need to add any changes to fix issues on mobile/tablet.
Here is the video of the issue:

https://github.com/user-attachments/assets/84420833-ac5e-4172-93fe-173fa445bd8a

### Related Pull Requests
None

### Fixed Issues (if relevant)
None

### Manual testing scenarios (*)
1. Create a custom split button on order view page.
2. Go to Frontend and place an order
3. Go to Admin Panel -> Sales -> Orders
4. Go to the order view page.

### Questions or comments
None

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#39080: Fix split button in order view page

### CODE REVIEW

**Comment by SerhiiMandrykin** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
@engcom-Hotel, could you please share what is the issue was fixed in ACP2E-2083?

**Comment by engcom-Hotel** [comment]
Hello @ihor-sviziev,

JIRA ACP2E-2083 contains the fix for the "Login as customer" button in the admin panel when accessing it via tab/phone. 

Before fix it looks something like this:

image

Thanks

**Comment by ihor-sviziev** [comment]
So, the scrolling has to be only horizontal, right?

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-November** [comment]
Hello @SerhiiMandrykin,

Looks like the issue is fixed on the latest 2.4-develop branch, could you please check on your end and let us know if the issue still persist.
Till then moving this to on hold.

Thank you.

**Comment by engcom-Hotel** [comment]
Hello @SerhiiMandrykin,

We have attempted to reproduce the issue in the latest 2.4-develop branch, and it appears the issue is no longer reproducible. It seems the issue has already been resolved. Please refer to the screencast below for reference:

[Products-Inventory-Catalog-Magento-Admin.webm](https://github.com/user-attachments/assets/063f199e-336f-4a17-a855-7ead244742f0)

Based on this, we will proceed to close this PR. However, we sincerely appreciate your contribution and look forward to more contributions from you in the future.

thanks

**Pull request closed without merging**
