### PR TITLE
magento/magento2#37953: Attribute getStoreLabel wrong behavior

### LINKED ISSUE #37953: Attribute getStoreLabel wrong behavior
### Preconditions and environment

- Magento version 2.4.6-p2

### Steps to reproduce

1. Create any attribute, with a default label
2. Set a different label for store id = X
3. load attribute on admin area, and dump `$attribute->getStoreLabel(X)`

### Expected result

Store label is dumped

### Actual result

Default label is dumped

### Additional information

The problem is quite obvious when watching the first method lines : 

https://github.com/magento/magento2/blob/3cc15fbed80c1f75c77c7cfeeaaba3ca25fe81b8/app/code/Magento/Eav/Model/Entity/Attribute.php#L490-L495

A fix could be : 

`if (null === $storeId && $this->hasData('store_label')) {` instead of `if ($this->hasData('store_label')) {`

But it's probably a bit more complicated than that, we probably want to use default value if store label is empty or not set

Workaround : `$attribute->unsetData('store_label')->getStoreLabel($storeId);`

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Kiraberos**
- reworked the logic in the method, if storeId is not passed (it is null), we get the current store ID through the store manager.

### Description (*)
In accordance with https://github.com/magento/magento2/issues/37953, an additional check for a null store ID has been added

### Related Pull Requests
No.

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/37953

### Manual testing scenarios (*)

1. Reproduced the problem
image
2. Debugged the method \Magento\Eav\Model\Entity\Attribute::getStoreLabel
3. Made sure that the fix worked
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Kiraberos** [comment]
@magento run all tests

**Comment by Kiraberos** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @Kiraberos,

Thanks for the contribution!

Please look into the build failures, especially, the Unit tests, it is failing due to the code changes.

Thanks

**Comment by Kiraberos** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by Kiraberos** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by Kiraberos** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Unit Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

**Comment by engcom-Hotel** [comment]
The failed tests are either known issues (which are not related to this PR change) or flaky test failures. Hence moving it further.

Thanks

**Comment by engcom-November** [comment]
Hello @Kiraberos,

Thanks for the collaboration & contribution!

### ✔️ QA Passed

**Steps to reproduce:**
- Create a product attribute, with a default label
- Set a different label for store id = X
- load attribute on admin area, and dump $attribute->getStoreLabel(X)

**Before: ✖️**
image
image

**After: ✔️**
image
image

Since the builds are failed moving this to **Extended Testing**.

**Comment by engcom-November** [comment]
@magento run all tests

**Comment by engcom-November** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-November** [comment]
The repeating failure in Functional Tests EE is falky and known issues.

**Functional Tests B2B**
**Run 1:**
image

**Run 2:**
image

**Functional Tests EE**
**Run 1:**
image

**Run 2:**
image

**Known issues:**
[ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331) - StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest

Hence moving this to **Merge in prrogress**.

**Comment by engcom-Charlie** [comment]
We have seen PAT failures in mainline PR after merging this PR into that. Hence for further analysis; for now moving this PR to Extended testing.

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
Hello @Kiraberos,

Thank you for your contribution.

After merging this PR into the mainline, we’ve observed some performance degradations introduced by the changes. As a result, we will be closing this PR for now. We suggest revisiting the changes to address the performance issues, and we look forward to reviewing an updated version in the future.

Thanks again for your efforts and understanding.

Below are the results of the performance degradation:
```
Job: Xhprof measurement, Edition - ee - FAILURE
Data: hudson.AbortException: There was a issue with measurement 
cache-load
Open Category (Catalog Browsing By Customer): 16.3% (mainline = 86 | team = 100) -> DEGRADATION
Open Category (Catalog Browsing By Guest): 19.7% (mainline = 71 | team = 85) -> DEGRADATION
Open Category (Add To Cart By Guest): 19.7% (mainline = 71 | team = 85) -> DEGRADATION
Open Category (Compare Products): 19.7% (mainline = 71 | team = 85) -> DEGRADATION
Open Category (Checkout By Guest): 19.7% (mainline = 71 | team = 85) -> DEGRADATION
Open Category (Checkout By Customer): 16.5% (mainline = 85 | team = 99) -> DEGRADATION
Open Category (Add To Cart By Customer): 16.5% (mainline = 85 | team = 99) -> DEGRADATION
New Configurable Product Save (Admin Create Product) - Another one: 19.2% (mainline = 73 | team = 87) -> DEGRADATION
Edit Configurable Product (Admin Edit Product): 64.8% (mainline = 91 | team = 150) -> DEGRADATION
Edit Configurable Product Save (Admin Edit Product) - Another one: 60.2% (mainline = 98 | team = 157) -> DEGRADATION

xhprof-redis-get-requests-count
Open Category (Catalog Browsing By Customer): 14.5% (mainline = 110 | team = 126) -> DEGRADATION
Open Category (Catalog Browsing By Guest): 17.9% (mainline = 78 | team = 92) -> DEGRADATION
Open Category (Add To Cart By Guest): 19.7% (mainline = 71 | team = 85) -> DEGRADATION
Open Category (Compare Products): 19.7% (mainline = 71 | team = 85) -> DEGRADATION
Open Category (Checkout By Guest): 19.7% (mainline = 71 | team = 85) -> DEGRADATION
Open Category (Checkout By Customer): 16.5% (mainline = 85 | team = 99) -> DEGRADATION
Open Category (Add To Cart By Customer): 16.5% (mainline = 85 | team = 99) -> DEGRADATION
New Configurable Product Save (Admin Create Product) - Another one: 18.2% (mainline = 77 | team = 91) -> DEGRADATION
Edit Configurable Product (Admin Edit Product): 63.4% (mainline = 93 | team = 152) -> DEGRADATION
Edit Configurable Product Save (Admin Edit Product) - Another one: 60.4% (mainline = 101 | team = 162) -> DEGRADATION

xhprof-redis-set-requests-count
Open Category (Catalog Browsing By Customer): 8.3% (mainline = 24 | team = 26) -> DEGRADATION
Configurable Product 1 View (Catalog Browsing By Customer): 16.7% (mainline = 6 | team = 7) -> DEGRADATION
Configurable Product 1 View (Checkout A Large Bulk Of Products By Guest): 33.3% (mainline = 6 | team = 8) -> DEGRADATION
Edit Configurable Product Save (Admin Edit Product) - Another one: 66.7% (mainline = 3 | team = 5) -> DEGRADATION



Job: Server Side measurement, Edition - b2b, API Import Products  - FAILURE
Data: There was a issue with measurement 
Process categories ids                                                                         1.00ms     +0.0%      (+0ms)     ok
Import 1000 Products JSON                                                                      2476.00ms  +3.7%      (+88ms)    DEGRADATION


Job: Server Side measurement, Edition - b2b, API Import Products - FAILURE
Data: hudson.AbortException: There was a issue with measurement 
Process categories ids                                                                         1.00ms     +0.0%      (+0ms)     ok
Import 1000 Products JSON                                                                      2476.00ms  +3.7%      (+88ms)    DEGRADATION
```

**Pull request closed without merging**
