### PR TITLE
 Meassage icon is not proper aligned

### PR DESCRIPTION
**Pull request by SyntaxKay**
### Description (*)

Meassage icon alignment issue resolved
Magento 2.3-develop

### Manual testing scenarios (*)

1. Login to Backend -> report -> Under sale : order
2.Check Message icon vertically alignment

### Actual Screenshot (*)
actual__screenshot

### Expected Screenshot (*)
expacted_screenshot

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by saphaljha** [comment]
@magento-engcom-team give me 2.3-develop instance

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-3851](https://jira.corp.magento.com/browse/ENGCOM-3851) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
