### PR TITLE
Fix ElasticSearch issue over secure connection

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
Add protocol to hostname even when auth is not enabled. Updated all ElasticSearch clients

### Fixed Issues (if relevant)
1. magento/magento2#22297: Elastic search issue over Secure Connection

### Manual testing scenarios (*)
See in #22297 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by arendarenko — APPROVED** [review]

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-5861](https://jira.corp.magento.com/browse/ENGCOM-5861) has been created to process this Pull Request

**Comment by engcom-Golf** [comment]
:heavy_check_mark: QA Passed

**Comment by sdzhepa** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Pull request merged**
