### PR TITLE
 #28802: Fix typo retires => retries

### LINKED ISSUE #28802: typo: setup:config:set  --session-save-redis-sentinel-connect-retires (instead of retries)
### Preconditions (*)

1. 2.3.5-p1
2. 2.4-develop -- in git: https://github.com/magento/magento2/blob/2.4-develop/setup/src/Magento/Setup/Model/ConfigOptionsList/Session.php#L43

`     const INPUT_KEY_SESSION_REDIS_SENTINEL_CONNECT_RETRIES = 'session-save-redis-sentinel-connect-retires';`

### Steps to reproduce (*)

```
$ php bin/magento --help setup:config:set | grep retires
      --session-save-redis-sentinel-connect-retires=SESSION-SAVE-REDIS-SENTINEL-CONNECT-RETIRES  Redis Sentinel connect retries.
```

### Expected result (*)

the command parameter ought to be named "retries" instead of "retires"

### Actual result (*)

```
$ php bin/magento --help setup:config:set | grep retires
      --session-save-redis-sentinel-connect-retires=SESSION-SAVE-REDIS-SENTINEL-CONNECT-RETIRES  Redis Sentinel connect retries.
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### Note: 

Not 100% sure if it hinders or not the functionality. Didn't test that, on a first glance in the code, I suppose -retires="..." works as expected.

The default sentinel_connect_retries seems to be set correctly and the `constant CONFIG_PATH_SESSION_REDIS_SENTINEL_CONNECT_RETRIES` is correct (without the typo): https://github.com/magento/magento2/blob/2.4-develop/setup/src/Magento/Setup/Model/ConfigOptionsList/Session.php#L67

### PR DESCRIPTION
**Pull request by medigeek**
#28802: Fix typo retires => retries

### Description (*)

#28802: Fix typo retires => retries

It would fix a typo of bin/magento command line setup:config:set argument/option

```
$ php bin/magento --help setup:config:set | grep retires
      --session-save-redis-sentinel-connect-retires=SESSION-SAVE-REDIS-SENTINEL-CONNECT-RETIRES  Redis Sentinel connect retries.
```

### Fixed Issues (if relevant)

1. Fixes magento/magento2#28802

### Questions or comments

1. checked for other "retires" occurences. not found.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by medigeek** [comment]
@magento run all tests

**Review by lbajsarowicz — DISMISSED** [review]
Thank you for your contribution!

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7716](https://jira.corp.magento.com/browse/ENGCOM-7716) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@medigeek thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Before:**
- :x: Match with incorrect word `retires`

#28819Main

**After:**

- :heavy_check_mark: No match with incorrect word `retires`
#28816PRWithTypo

- :heavy_check_mark: Match with correct word `retries`
#28816PRWithCorrect

**Comment by sdzhepa** [comment]
It looks like BIC changes. Moved to "To Approve" column for review

**Comment by ihor-sviziev** [comment]
Seems like bot moved this PR to wrong status. moved back.

**Review by ihor-sviziev — APPROVED** [review]

**Pull request merged**
