### PR TITLE
Fix-issue: 26022 - Admin attributes Advanced Attribute Properties icon doesn't change while collapsing block 

### PR DESCRIPTION
**Pull request by SyntaxKay**
2.3-update

### Description (*)

Admin attributes Advanced Attribute Properties icon doesn't change while collapsing block fixed

### Fixed Issues (if relevant)

1. magento/magento2#26022: Admin attributes Advanced Attribute Properties icon doesn't change while collapsing block

### Manual testing scenarios (*)

1. Login to admin
2. Store -> Attributes -> products -> properties -> Advanced attribute properties
3. check the icon of Advanced attribute properties block

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by kalpmehta** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, here is your [new Magento instance](https://pr-26024.instances.magento-community.engineering).
Admin access: [https://pr-26024.instances.magento-community.engineering/admin](https://pr-26024.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by kalpmehta — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, thank you for the review.
[ENGCOM-6462](https://jira.corp.magento.com/browse/ENGCOM-6462) has been created to process this Pull Request
:eight_spoked_asterisk: @kalpmehta, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Charlie** [comment]
Hi @speedy008  .

Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated tests.
Thanks!

**Comment by abrarpathan19** [comment]
@sankalpshekhar @speedy008 
Please review: https://prnt.sc/qejxsk 
if you use this type of fix, It might create an issue in some places.

**Comment by lenaorobei** [comment]
Closing this PR due to inactivity. Please feel free to reopen if you are going to continue working on it.
Thank you.

**Pull request closed without merging**
