### PR TITLE
Selected configurable product attribute options are not displaying in wishlist page. #24091

### LINKED ISSUE #24091: Selected configurable product attribute options are not displaying in wishlist page.
### Preconditions (*)

1. Magento 2.3.2 with sample data
2. Product listing page should have 2 or more configurable products with swatches.

### Steps to reproduce (*)

1. Log into the customer account.
2. Navigate to product listing page.
3. Choose the configurable product and select preferred color and size options of any product expect last product which is listed in Product listing page ( It is working fine for last product of the listing page).
4. Click on the wishlist icon of the product.

### Expected result (*)

1. On the Wishlist page, the selected configurable product options color and size should be visible. (See Details is available on the product, see this gif below
SeeDetails
)

### Actual result (*)

1. The selected color and size is not visible in wishlist page.

plp
wishlist

### PR DESCRIPTION
**Pull request by venugopal-codilar**
Selected configurable product attribute options are not displaying in wishlist page. #24091

### Description (*)

1. Resolve #24091 :Selected configurable product attribute options are not displaying in wishlist page.

Solution : Added a if condition to check elementValue is empty or not in app/code/Magento/Wishlist/view/frontend/web/js/add-to-wishlist.js

### Fixed Issues (if relevant)

1. magento/magento2#24091: Selected configurable product attribute options are not displaying in wishlist page

### Manual testing scenarios (*)

1. Go to customer frontend.
2. Log into the customer account.
3. Navigate to product listing page.
4. Choose the configurable product and select preferred color and size options of any product in Product listing page.
5. Click on the wishlist icon of the product.

### Expected result
1. On the customer wishlist page, the selected configurable product options color and size should be visible. 

### Questions or comments

1. If any test case is required, please let me know.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24110) <br/>All committers have signed the CLA.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5601](https://jira.corp.magento.com/browse/ENGCOM-5601) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Foxtrot** [comment]
@venugopal-codilar, thank you for contribution.
Unfortunately, your code change introduces a new bug. You can reproduce it by following next steps:
1. Create a configurable Product.
2. Login as Customer.
3. Open the Product page on a storefront.
4. Choose some configuration.
5. Choose no configuration.
6. Add the Product to Wishlist.
7. Open Wishlist page.
8. Observe added Product.
Expected result:
Product in Wishlist should not have any configuration.
Actual result:
Product in Wishlist has configuration chosen at step 4.

**Comment by sidolov** [comment]
@venugopal-codilar , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
