### PR TITLE
Empty block rendering in My Account page sidebar fixed using designing changes.

### PR DESCRIPTION
**Pull request by mage2pratik**
### Description (*)

Empty block rendering in My Account page sidebar fixed using designing changes.
### Fixed Issues (if relevant)

1. magento/magento2#19139: Empty block rendering in My Account page sidebar

### Manual testing scenarios (*)

1. Create an Account or Sign In
2. Review left sidebar in My Account section

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by sdzhepa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [new Magento instance](https://pr-20630.instances.magento-community.engineering).
Admin access: [https://pr-20630.instances.magento-community.engineering/admin](https://pr-20630.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sdzhepa** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [Magento instance](https://i-20630-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20630-2-3-develop.instances.magento-community.engineering/admin](https://i-20630-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by sdzhepa — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, thank you for the review.
[ENGCOM-3981](https://jira.corp.magento.com/browse/ENGCOM-3981) has been created to process this Pull Request

**Pull request merged**
