### PR TITLE
Mark classes and interfaces as API part 5

### LINKED ISSUE #32673: Mark classes and interfaces as API part 5
The following interfaces should be marked as API

1. lib/internal/Magento/Framework/App/Config/ValueInterface.php - Also, remove the comments related to not marking it as @api.
2. lib/internal/Magento/Framework/MessageQueue/ConsumerConfigurationInterface.php
3. lib/internal/Magento/Framework/View/DesignInterface.php
4. lib/internal/Magento/Framework/Webapi/CustomAttributeTypeLocatorInterface.php

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Marked following classes,  interfaces as API

lib/internal/Magento/Framework/App/Config/ValueInterface.php
lib/internal/Magento/Framework/MessageQueue/ConsumerConfigurationInterface.php
lib/internal/Magento/Framework/View/DesignInterface.php
lib/internal/Magento/Framework/Webapi/CustomAttributeTypeLocatorInterface.php

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32673

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8991](https://jira.corp.magento.com/browse/ENGCOM-8991) has been created to process this Pull Request

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama the branch with code successfully imported into`magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-32680`.

**Comment by gabrieldagama** [comment]
@magento import pr to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama the pull request successfully imported.

**Pull request merged**
