### PR TITLE
[MFTF] Updating with SaveCmsPageActionGroup

### LINKED ISSUE #31574: [Issue] [MFTF] Updating with SaveCmsPageActionGroup
This issue is automatically created based on existing pull request: magento/magento2#31568: [MFTF] Updating with SaveCmsPageActionGroup

---------
### Description (*)
Test have been updated with SaveCmsPageActionGroup

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
Test have been updated with SaveCmsPageActionGroup

### Resolved issues:
1. [x] resolves magento/magento2#31574: [MFTF] Updating with SaveCmsPageActionGroup

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Comment by sidolov** [comment]
@magento create issue

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Comment by eduard13** [comment]
@magento run all tests

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8683](https://jira.corp.magento.com/browse/ENGCOM-8683) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
Manual QA is not applicable for MFTF Refactoring PR-s. Moving the PR to _Extended Testing_ column

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @AnnaAPak, thanks for contributing! Can you resolve the conflicts on this one?

**Comment by engcom-Charlie** [comment]
Hello @AnnaAPak could you please resolve the conflicts?
Thank you.

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Functional Tests B2B

**Review by eduard13 — APPROVED** [review]

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8683](https://jira.corp.magento.com/browse/ENGCOM-8683) has been created to process this Pull Request

**Pull request merged**
