### PR TITLE
Updated ternary operator to null-coalescing operator in lib files

### PR DESCRIPTION
**Pull request by mage2pratik**
### Description (*)

Updated lib files to convert operator from ternary to null-coalescing.

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mage2pratik. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by davidverholen — APPROVED** [review]

**Review by orlangur — DISMISSED** [review]
Hi @mage2pratik, please update code according to this comment: https://github.com/magento/magento2/pull/18676#pullrequestreview-172324572

**Comment by orlangur** [comment]
@mage2pratik please squash changes into a single commit.

**Comment by mage2pratik** [comment]
@orlangur : please review updated code.

**Comment by sivaschenko** [comment]
Hi @mage2pratik , in order to merge pull request to mainline we'll need to ensure static tests are passing on the pull request. Static tests are running only for changed files.

Can you please run magento static tests for changed files to ensure they are passing.

**Comment by sidolov** [comment]
@mage2pratik , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
