### PR TITLE
Fix for footer newsletter input field length in IE/Edge

### PR DESCRIPTION
**Pull request by divyajyothi5321**
### Fixed Issues (if relevant)

1. magento/magento2#26176: Footer Newsletter input field width is not identical in Internet Explorer/EDGE browser compared with chrome

### Manual testing scenarios (*)

1. Go to Front-end footer section
2. With this fix the newsletter input field width is identical in Internet Explorer/Edge Browser as shown below
search-expected

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-26182.instances.magento-community.engineering).
Admin access: [https://pr-26182.instances.magento-community.engineering/admin](https://pr-26182.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-6525](https://jira.corp.magento.com/browse/ENGCOM-6525) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Delta. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Delta, here is your [new Magento instance](https://pr-26182.instances.magento-community.engineering).
Admin access: [https://pr-26182.instances.magento-community.engineering/admin](https://pr-26182.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
