### PR TITLE
Fix wrong position of button list when load "New Attribute" page

### LINKED ISSUE #29597: [Issue] Fix wrong position of button list when load "New Attribute" page
This issue is automatically created based on existing pull request: magento/magento2#27574: Fix wrong position of button list when load "New Attribute" page

### Preconditions (*)

1. Magento 2.4-develop

### Steps to reproduce (*)

1. Go to backend, create new product
2. Fill required field, go to "Create Configurations"
3. Create New Attribute
4. Look at the position of the button "Reset" and "Save Attribute"

### Expected result (*)
:heavy_check_mark: The position of the button list should be correct when loading the "New Attribute" page

image

### Actual result (*) 
:heavy_multiplication_x: after 1 seconds, the button list re-arranged.

wrong_position

We can see, after 1 seconds, the button list re-arranged. 

image

to

image

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

Let check this gif:

wrong_position

We can see, after 1 seconds, the button list re-arranged. 

image

to

image

### Manual testing scenarios (*)

1. Go to backend, create new product
2. Fill required field, go to "Create Configurations"
3. Create New Attribute
4. Look at the position of the button "Reset" and "Save Attribute"
5, It should be:

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29597: Fix wrong position of button list when load "New Attribute" page

### CODE REVIEW

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-27574.instances.magento-community.engineering).
Admin access: [https://pr-27574.instances.magento-community.engineering/admin_cdfb](https://pr-27574.instances.magento-community.engineering/admin_cdfb)
Login: `7828b783` Password: `75d6f0532437`
Instance will be terminated in up to 3 hours.

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-27574.instances.magento-community.engineering).
Admin access: [https://pr-27574.instances.magento-community.engineering/admin_c8e7](https://pr-27574.instances.magento-community.engineering/admin_c8e7)
Login: `a2ee2be9` Password: `1bf3c0f1526d`
Instance will be terminated in up to 3 hours.

**Comment by sidolov** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8288](https://jira.corp.magento.com/browse/ENGCOM-8288) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Go to backend, create new product
2. Fill required field, go to "Create Configurations"
3. Create New Attribute
4. Look at the position of the button "Reset" and "Save Attribute"

**Before:** :heavy_multiplication_x: after 1 seconds, the button list re-arranged.

Peek 2020-10-09 13-48

**After:** :heavy_check_mark: The position of the button list is correct when loading the "New Attribute" page

Peek 2020-10-09 13-56

**Pull request merged**
