### PR TITLE
Improve html markup thumbnail image

### LINKED ISSUE #29468: [Issue] Improve html markup thumbnail image
This issue is automatically created based on existing pull request: magento/magento2#28642: Improve html markup thumbnail image

---------

### Description (*)

Magento 2.4-develop
Improve markup thumbnail image for easier customise 
Previous only use img tag for some case impossible add style without touch directly to img tag. Add wrapper tag around img instead

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Improve markup thumbnail image for easier customise 
Previous only use img tag for some case impossible add style without touch directly to img tag. Add wrapper tag around img instead
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29468: Improve html markup thumbnail image

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7691](https://jira.corp.magento.com/browse/ENGCOM-7691) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked image in product grid is displayed as before
**Before:**
#28642Main

**After:**
#28642PR

**Comment by engcom-Delta** [comment]
@magento create issue

**Comment by slavvka** [comment]
@magento run all tests

**Pull request merged**
