### PR TITLE
Added and removed unnecessary translation for label/comment tags

### PR DESCRIPTION
**Pull request by yogeshsuhagiya**
### Description
Added translation for label and/or comment tags.
Removed unnecessary translation for label and/or comment tags.

### Fixed Issues (if relevant)
1. N/A

### Manual testing scenarios
1. N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16090) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @Yogeshks. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on Pull Request changes
- `@magento-engcom-team give me new test instance` - deploy **NEW** test instance based on Pull Request changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy Vanilla Magento instance for Issue or Pull Request

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by yogeshsuhagiya** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Yogeshks. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Yogeshks, here is your [Magento instance](https://pr-16090.engcom.dev.magento.com).
Admin access: [https://pr-16090.engcom.dev.magento.com/admin](https://pr-16090.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Please make sure you are PR **author** or **assignee** to access the instance.

**Comment by yogeshsuhagiya** [comment]
Hello @magento-engcom-team, I've reviewed the test instance but it's not required because almost my changes are in `system.xml` files of different modules for language translations.

**Comment by yogeshsuhagiya** [comment]
@magento-engcom-team Hello team, will you please review this PR? And please let me know, is it valid PR or not. 6 days passed but still no response.

**Comment by mzeis** [comment]
Hi @Yogeshks, actually it improves speed of processing when you don't assign somebody yourself. Maintainers do the work in their free time and for example I'm on vacation currently.

Vlad now unassigned us because then you have a chance that somebody else picks up this PR. Please allow some time though for processing for the reasons mentioned above.

Thanks for understanding!

**Comment by yogeshsuhagiya** [comment]
Hi @mzeis ,  Not an issue, I not aware of it. 
Anyway, enjoy your vacation.

**Comment by yogeshsuhagiya** [comment]
@magento-engcom-team Hello team, any update?

**Comment by magento-engcom-team** [comment]
Hi @Yogeshks. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.6. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Pull request merged**
