### PR TITLE
ProductToolbarTypoFix: Grit Typo Fix

### PR DESCRIPTION
**Pull request by sanchit-cueblocks**
### Description (*)

Typo spell correction from Grit to Grid
### Fixed Issues (if relevant)

Typo spell correction
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-6783](https://jira.corp.magento.com/browse/ENGCOM-6783) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@sanchit-cueblocks thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed
The "grit" is renamed to "grid"
pr_grid

**Comment by engcom-Charlie** [comment]
Failures of functional tests, not related to the changes in this PR, tests failing on 2.4-develop branch
image
image

**Pull request merged**
