### PR TITLE
Update color code to lowercase follow less standards

### LINKED ISSUE #31843: [Issue] Update color code to lowercase follow less standards
This issue is automatically created based on existing pull request: magento/magento2#31831: Update color code to lowercase follow less standards

---------

### Description (*)

https://devdocs.magento.com/guides/v2.4/coding-standards/code-standard-less.html#hexadecimal-notation
Small change in less code base in order to make code following magento less standards

In scope of this PR only change in less file only! While in magento code base someother place (file css, phtml..) still mix between uppercase and lowercase for color string

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Run deploy content
2. View output file css and search color string related change

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

https://devdocs.magento.com/guides/v2.4/coding-standards/code-standard-less.html#hexadecimal-notation
Small change in less code base in order to make code following magento less standards

In scope of this PR only change in less file only on Frontend area! While in magento code base someother place (file css, phtml..) still mix between uppercase and lowercase for color string

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Run deploy content
2. View output file css and search color string related change

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31843: Update color code to lowercase follow less standards

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8706](https://jira.corp.magento.com/browse/ENGCOM-8706) has been created to process this Pull Request

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Review by ptylek — APPROVED** [review]

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-8706](https://jira.corp.magento.com/browse/ENGCOM-8706) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
Hi @mrtuvn,

We are closing this PR.The PR is in Draft since longtime.

Once you are ready Please feel free to reopen it to process the PR further.

Thanks

**Comment by engcom-Bravo** [comment]
Hi @mrtuvn,

We are closing this PR.The PR is in Draft since longtime.

Once you are ready Please feel free to reopen it to process the PR further.

Thanks

**Pull request closed without merging**
