### PR TITLE
[2.3] Update the Emogrifier dependency to ^2.0.0

### PR DESCRIPTION
**Pull request by oliverklee**
### Description
Emogrifer 2.0.0 does not introduce any backwards-compatibilty-breaking
API changes. This version adds new features, fixes bugs and improves
the resulting HTML. So the update should be reasonably safe.

This is the 2.3-develop port of https://github.com/magento/magento2/pull/13132.

### Manual testing scenarios
1. have Magento send an HTML email
2. see that the generated email still looks okay

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by oliverklee** [comment]
I'll take care of the rebase to resolve the merge conflict.

**Comment by oliverklee** [comment]
Rebased and repushed.

**Comment by oliverklee** [comment]
Oh, and another merge conflict. I'll take care of it.

**Comment by oliverklee** [comment]
The build failure does not seem to be related to the changes in this PR - the 2.3-develop branch itself also is red.

**Comment by oliverklee** [comment]
Rebased and repushed.

**Review by orlangur — APPROVED** [review]

**Pull request merged**
