### PR TITLE
fix for #37957 issue (Image uploader does not work inside dynamic rows)

### LINKED ISSUE #37957: Image uploader does not work inside dynamic rows
### Preconditions and environment

- Magento 2.4.5

### Steps to reproduce

1. Create a dynamicRows component with field of type "imageUploader"
```
<fieldset name="top_icons_list" sortOrder="20">
        <settings>
            <label translate="true">Top Icons List</label>
            <collapsible>true</collapsible>
            <opened>false</opened>
            <dataScope>ui_config.top_icons_list</dataScope>
        </settings>
        <container name="top_icons_list_items_container">
            <dynamicRows name="items">
                <argument name="data" xsi:type="array">
                    <item name="config" xsi:type="array">
                        <item name="template" xsi:type="string">ui/dynamic-rows/templates/default</item>
                        <item name="componentType" xsi:type="string">dynamicRows</item>
                        <item name="recordTemplate" xsi:type="string">record</item>
                        <item name="addButton" xsi:type="boolean">true</item>
                        <item name="deleteProperty" xsi:type="boolean">true</item>
                        <item name="dndConfig" xsi:type="array">
                            <item name="enabled" xsi:type="boolean">true</item>
                        </item>
                        <item name="additionalClasses" xsi:type="array">
                            <item name="action-per-product-table" xsi:type="boolean">true</item>
                        </item>
                    </item>
                </argument>
                <container name="record">
                    <argument name="data" xsi:type="array">
                        <item name="config" xsi:type="array">
                            <item name="component" xsi:type="string" translate="true">Magento_Ui/js/dynamic-rows/record</item>
                            <item name="isTemplate" xsi:type="boolean">true</item>
                            <item name="is_collection" xsi:type="boolean">true</item>
                            <item name="showFallbackReset" xsi:type="boolean">false</item>
                        </item>
                    </argument>
                    <field name="icon" sortOrder="40" formElement="imageUploader">
                        <argument name="data" xsi:type="array">
                            <item name="config" xsi:type="array">
                                <item name="source" xsi:type="string">page_ui_config</item>
                            </item>
                        </argument>
                        <settings>
                            <elementTmpl>ui/form/element/uploader/image</elementTmpl>
                            <dataType>string</dataType>
                            <label translate="true">Image</label>
                            <visible>true</visible>
                            <required>true</required>
                        </settings>
                        <formElements>
                            <imageUploader>
                                <settings>
                                    <required>false</required>
                                    <uploaderConfig>
                                        <param xsi:type="url" name="url" path="cms_page_ui_config/cmsPageUiConfig_image/homePageUpload"/>
                                    </uploaderConfig>
                                    <isMultipleFiles>false</isMultipleFiles>
                                    <previewTmpl>Magento_Catalog/image-preview</previewTmpl>
                                    <openDialogTitle>Media Gallery</openDialogTitle>
                                    <initialMediaGalleryOpenSubpath>my_path/my_path</initialMediaGalleryOpenSubpath>
                                    <allowedExtensions>jpg jpeg gif png</allowedExtensions>
                                    <maxFileSize>4194304</maxFileSize>
                                </settings>
                            </imageUploader>
                        </formElements>
                    </field>
                    <field name="label" sortOrder="50" formElement="input">
                        <argument name="data" xsi:type="array">
                            <item name="config" xsi:type="array">
                                <item name="source" xsi:type="string">page_ui_config</item>
                            </item>
                        </argument>
                        <settings>
                            <dataType>text</dataType>
                            <label translate="true">Label</label>
                            <dataScope>label</dataScope>
                        </settings>
                    </field>
                    <field name="description" sortOrder="60" formElement="textarea">
                        <argument name="data" xsi:type="array">
                            <item name="config" xsi:type="array">
                                <item name="source" xsi:type="string">page_ui_config</item>
                            </item>
                        </argument>
                        <settings>
                            <dataType>text</dataType>
                            <label translate="true">Description</label>
                            <dataScope>description</dataScope>
                        </settings>
                    </field>
                    <actionDelete>
                        <argument name="data" xsi:type="array">
                            <item name="config" xsi:type="array">
                                <item name="componentType" xsi:type="string">actionDelete</item>
                                <item name="dataType" xsi:type="string">text</item>
                                <item name="fit" xsi:type="boolean">false</item>
                                <item name="label" xsi:type="string">Actions</item>
                                <item name="additionalClasses" xsi:type="string">data-grid-actions-cell</item>
                                <item name="template" xsi:type="string">Magento_Backend/dynamic-rows/cells/action-delete
                                </item>
                            </item>
                        </argument>
                    </actionDelete>
                </container>
            </dynamicRows>
        </container>
    </fieldset>
```
2. Try to upload an image
3. See this error:
Selection_648

### Expected result

The images are uploaded correctly when sent as multinational array

### Actual result

The Uploader class gets an undefined index error due to input name referring file id as multinational array and sent via `$_FILES` as multinational array as well. But the reader does not handle this case.

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rostilos**
### Description (*)

The reason for the error described in the issue was that in the `_setUploadFileId` method of the specified file an attempt was made to get the value of an array item (the path to the uploaded picture), but the path to access the array keys was written in a variable as a string ( ex. "[top_icons_list][items][0][icon]" ), so on line 701 ( `$tmpVar[$attributeName] = $attributeValue[$file[1]];` ) the following happened : 
`$tmpVar[$attributeName] = $attributeValue["[top_icons_list][items][0][icon]"];`
And it should be like this : 
`$tmpVar[$attributeName] = $attributeValue[top_icons_list][items][0][icon];`

This PR fixes this behavior, and allows you to correctly retrieve the value by the specified keys.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#37957

### Manual testing scenarios (*)

1. Described in the original issue

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rostilos** [comment]
@magento run all tests

**Comment by rostilos** [comment]
https://github.com/magento run all tests

**Comment by rostilos** [comment]
@magento run all tests

**Comment by swnsma** [comment]
@magneto run Unit Tests, Static Tests, Functional Tests CE , Functional Tests B2B

**Review by swnsma — CHANGES_REQUESTED** [review]
Hi @rostilos,

Thank you for your contribution!
I should ask you for a few things before Pull Request can be processed further:
1) Could you please have a look into Static and Unit Tests and make sure that PR will pass the automatic testing.
2) That would be really nice of you could create auto-tests coverage for this specific use-case

**Comment by rostilos** [comment]
Thank you. Yeah, I can do that in my spare time, I'll let you know.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Functional Tests EE and Functional Tests B2B failure are different on last two run.
Also Moving this PR to `Pending Review` as automated test coverage we can not add as the changes are made in  private function  ` private function _setUploadFileId($fileId)`

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Review by engcom-Hotel — APPROVED** [review]
Changes looks good to me, failed tests are flaky. Hence approving this PR.

Thanks

**Comment by engcom-Echo** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

1. We have follow steps from [comment](https://github.com/magento/magento2/issues/37957#issue-1881331689)


**Before:** :heavy_multiplication_x:  File uploading failed
Screenshot 2023-12-19 at 2 09 36 PM


**After:** :heavy_check_mark:  File uploaded successfully
Screenshot 2023-12-19 at 2 33 48 PM

Builds are failing, Hence moving to `Extended Testing`

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE

**Comment by engcom-Echo** [comment]
Functional Tests EE failure are different on last two run on same commit.
Run1
Screenshot 2023-12-19 at 4 43 42 PM

Run2
Screenshot 2023-12-19 at 4 43 46 PM

Hence moving it to `Merge In Progress`

**Pull request merged**
