### PR TITLE
changes for paypal_affect_core_config_fields_with_tooltip

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Description (*)

#21974: Changes for PayPal affect core config fields with tooltip
### Fixed Issues (if relevant)

1. Magento 2.3.x

### Manual testing scenarios (*)

1. create an config field, type time with a tooltip in a group in a section (#21974)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by VladimirZaets** [comment]
Hi @amol2jcommerce. Thanks for collaboration. Are you investigate the reason why font-size was set to 0, `font-size: 0` very specific setting, so I think we had some reason to do it

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @amol2jcommerce. Thanks for collaboration. Are you investigate the reason why font-size was set to 0, font-size: 0 very specific setting, so I think we had some reason to do it

**Comment by amol2jcommerce** [comment]
Hi @VladimirZaets I checked but no idea about font-size: 0, I cross check with 2.2 instance but not found font-size and issue not generated. It's occurs only 2.3, fixed in 2.2

**Comment by VladimirZaets** [comment]
Hi @amol2jcommerce. The style `font-size: 0` was added because of not input fields (select as an example) in the system configuration wasn't aligned by the center of the page.
Please check that case and fix it in a compatible way

**Comment by VladimirZaets** [comment]
@amol2jcommerce, I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Pull request closed without merging**
