### PR TITLE
Include Constructor to be a part of `CommandListInterface` API, extend inline documentation

### LINKED ISSUE #31102: [Issue] Include Constructor to be a part of `CommandListInterface` API, extend inline documentation
This issue is automatically created based on existing pull request: magento/magento2#29762: Include Constructor to be a part of `CommandListInterface` API, extend inline documentation

---------
### Description (*)
~In my personal opinion using `CommandListInterface` is invalid way of adding new Commands to interface.
It is because Constructor is not a part of Interface (Service Contract), thus it is not "guaranteed" part of Interface.~

~Using `CommandList` is against Magento rules, thus it's implementation is not guaranteed and can change in backwards-incompatible way.~

~I'm extending the `CommandList` with `@api` to ensure developers that this class won't change backwards-incompatible way and this way - they can either add new classes using:~
- ~Argument injection to `CommandList` class~
- ~Plugin on `getCommands` on `CommandListInterface`.~

~I'd love to get your feedback there.~

After discussion with @kandy I decided to add the `__construct()` to the API.

Answering the main concerns: https://3v4l.org/8ug8i
image

As it affects you (community) I need your 👍🏻 or comments to pass the change:
image

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Thanks

- @jissereitsma for inspiration

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Based on above [comment](https://github.com/magento/magento2/pull/29762#issuecomment-1639538619) we have created new PR targeting to 2.4-develop.
Link for the new PR: https://github.com/magento/magento2/pull/37901

~In my personal opinion using `CommandListInterface` is invalid way of adding new Commands to interface.
It is because Constructor is not a part of Interface (Service Contract), thus it is not "guaranteed" part of Interface.~

~Using `CommandList` is against Magento rules, thus it's implementation is not guaranteed and can change in backwards-incompatible way.~

~I'm extending the `CommandList` with `@api` to ensure developers that this class won't change backwards-incompatible way and this way - they can either add new classes using:~
- ~Argument injection to `CommandList` class~
- ~Plugin on `getCommands` on `CommandListInterface`.~

~I'd love to get your feedback there.~

After discussion with @kandy I decided to add the `__construct()` to the API.

Answering the main concerns: https://3v4l.org/8ug8i
image

As it affects you (community) I need your 👍🏻 or comments to pass the change:
image

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Thanks

- @jissereitsma for inspiration

### Resolved issues:
1. [x] resolves magento/magento2#31102: Include Constructor to be a part of `CommandListInterface` API, extend inline documentation

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by BarnyShergold** [comment]
@shiftedreality - Tests are failing on this but no errors are appearing in the reports - eg the Unit Tests - can you advise?

**Comment by BarnyShergold** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@lbajsarowicz I saw the discussion in the Slack channel regarding this pull request, as far as I remember, @maghamed proposed to deprecate the interface and add @api annotation to the class itself, is that right? (I cannot add a screenshot of the original conversation since it was removed from the history)

**Comment by jissereitsma** [comment]
@lbajsarowicz @sidolov My reaction would be that marking the class as API is maybe actually the best approach of all.

**Comment by lbajsarowicz** [comment]
@magento run all tests
@jissereitsma / @BarnyShergold / @sidolov I changed approach to turn the class into `@api`

**Comment by sidolov** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
Moved to correct status, as this PR waiting for 2.5-develop branch creation

**Comment by lbajsarowicz** [comment]
@ihor-sviziev Thanks.

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by lbajsarowicz** [comment]
Thanks @ihor-sviziev !

**Review by BarnyShergold — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @BarnyShergold, thank you for the review.
[ENGCOM-8620](https://jira.corp.magento.com/browse/ENGCOM-8620) has been created to process this Pull Request
:eight_spoked_asterisk: @BarnyShergold, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by lbajsarowicz** [comment]
Any updates or we can close this one?

**Comment by ihor-sviziev** [comment]
@lbajsarowicz, all the pull requests to the 2.5-develop branch are still on hold... :(

**Comment by lbajsarowicz** [comment]
Anniversary 🥳

**Comment by engcom-Charlie** [comment]
As this PR's milestone is 2.5, moving it to On Hold.

Thank you!

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@sinhaparul, can this PR be moved to 2.4-develop release line?

**Comment by engcom-Charlie** [comment]
As the PR's milestone is 2.5, we will confirm [this](https://github.com/magento/magento2/pull/29762#issuecomment-1614187888) with @sinhaparul and proceed as per that. Till that time moving it to On Hold.

Thank you!

**Comment by engcom-Charlie** [comment]
Hi @lbajsarowicz,

Thank you for your contribution!

Its a value added PR and we really want to take it further. 

Can you please update it towards 2.4-develop branch instead of 2.5-develop so that we can proceed further.

Thank you!

**Comment by lbajsarowicz** [comment]
I'll handle it by August 1st

**Comment by engcom-Charlie** [comment]
> I'll handle it by August 1st

Hi @lbajsarowicz, did you get chance to do the needful.

**Comment by engcom-Echo** [comment]
Based on above [comment](https://github.com/magento/magento2/pull/29762#issuecomment-1639538619) we have created new PR targeting to 2.4-develop.
Link for the new PR: https://github.com/magento/magento2/pull/37901

Hence closing this PR.

**Pull request closed without merging**
