### PR TITLE
fix issue : [2.4.6-p1] Import Error - HTML is not rendered #37699

### LINKED ISSUE #37699: [2.4.6-p1] Import Error - HTML is not rendered
### Preconditions and environment

- Magento 2.4.6-p1
- PHP 8.2

### Steps to reproduce

1. Use any CSV file that will fail
To make a failing CSV file:
- Create a category
- Rename that category (just rename the title not the URL key)
- In CSV file use the category name previous to renaming it. So if you created "Category A" then renamed to "Category B", put "Category A" in CSV file. 
- The system will fail to import due to duplicate URL keys

That is just one way to have a failing CSV import file and is just an example. Any failing CSV file should work to demonstrate the HTML is not being rendered correctly.

### Expected result

When the CSV file fails it should show the HTML rendered, not the actual HTML code

### Actual result

It shows the error with the HTML code showing, not rendered.

Here is a screenshot of what it looks like. It has also been like this for years (I think since at least 2.4.0) and I think it's time to finally report it and hope it gets fixed.

magento-import-fail-shows-html-code-instead-of-rendering-it

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by dekiakbar**
### Description (*)
- Fix issue : [[2.4.6-p1] Import Error - HTML is not rendered #37699](https://github.com/magento/magento2/issues/37699)
- Error message rendered as HTML tags.
- [video before fix](https://www.loom.com/share/4530c94b3041451dafe0f78659be7d7b?sid=157d3008-1f99-40d2-9c3f-579c67f65a28) 
- [video after fix](https://www.loom.com/share/79133077a09d4601addf6181e6aa8138?sid=d0829429-1bb9-4423-a937-1d2a812b62e2) 

### Related Pull Requests
-

### Fixed Issues (if relevant)

1. Fixes [magento/magento2#<issue_number>](https://github.com/magento/magento2/issues/37699)

### Manual testing scenarios (*)

- Use any CSV file that will fail
- To make a failing CSV file:
- Create a category
- Rename that category (just rename the title not the URL key)
- In CSV file use the category name previous to renaming it. So if you created "Category A" then renamed to "Category B", put "Category A" in CSV file.
- The system will fail to import due to duplicate URL keys

### Questions or comments
-
### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by dekiakbar** [comment]
@magento run all tests

**Comment by dekiakbar** [comment]
@magento run Unit Tests

**Comment by dekiakbar** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE,Sample Data Tests B2B,Sample Data Tests CE,Sample Data Tests EE

**Comment by FadedOut** [comment]
Much appreciate you working on this @dekiakbar 

It's interesting to see what it looks like working correctly - I've been using Magento since 2.4.0 and it has never looked like that (your video clip showing it working properly). It will be nice to have it looking correct finally 🙂👍. Now we won't have to decipher the error messages with all that extra code showing.

**Comment by dekiakbar** [comment]
@FadedOut Thank you 🙂

@magento run Functional Tests B2B

**Comment by dekiakbar** [comment]
@magento run Sample Data Tests B2B,Sample Data Tests CE,Sample Data Tests EE

**Comment by dekiakbar** [comment]
@magento run Functional Tests B2B

**Pull request closed without merging**
