### PR TITLE
Fix #7200 - Configurable Products dropdown not showing pricing

### LINKED ISSUE #7200: Configurable Products dropdown not showing pricing
I have a configurable product and the configurations all have different prices.  The dropdown on my configurable product does not show pricing information (like it did in Magento 1.9).
### Preconditions

Magento ver 2.1.2 up to 2.3.1
### Steps to reproduce

1. Create a configurable product with two attributes and that the second attribute (second in the list, never the first one - it's essential for reproduction) has pricing differences.
2. Go to the Frontend and watch the second attribute dropdown.

### Expected result

1. Second attribute drop-down reflects pricing differences like on the screenshot below
image

### Actual result

1. No pricing information is shown in the second drop-down.
backend
frontend

 The pricing differences would be shown only in the first attribute dropdown if they were set for it.

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

Fix for #7200 

### Fixed Issues (if relevant)

1. magento/magento2#7200: Configurable Products dropdown not showing pricing

### Manual testing scenarios (*)

1. Create a configurable product with two attributes and that the second attribute (second in the list, never the first one - it's essential for reproduction) has pricing differences.
2. Go to the Frontend and watch the second attribute dropdown.
3. It should contain price diff based on option selected at first select.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5693](https://jira.corp.magento.com/browse/ENGCOM-5693) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

**Before:**

before

**After:**

fter

**Comment by Bartlomiejsz** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Bartlomiejsz. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Bartlomiejsz, here is your [Magento instance](https://i-24255-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-24255-2-4-develop.instances.magento-community.engineering/admin_e2d4](https://i-24255-2-4-develop.instances.magento-community.engineering/admin_e2d4)
Login: `5378a2c3` Password: `35c6fece1ea6`
Instance will be terminated in up to 3 hours.

**Pull request merged**
