### PR TITLE
Curl - allow setting HTTP version

### PR DESCRIPTION
**Pull request by ghost**
### Description
Added allow for setting curl http version

### Fixed Issues (if relevant)
1. magento/magento2#19442: Magento/Framework/HTTP/Adapter/Curl.php doesn't allow setting HTTP version

### Manual testing scenarios (*)
1. Create new ZendClient $client
2. Set HTTP version $client->setConfig(['httpversion' => CURL_HTTP_VERSION_1_1])
3. Make a request $client->request()

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19445) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @SikailoISM. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by engcom-backlog-nazar** [comment]
Hi @SikailoISM, were the constant CURLOPT_HTTP_VERSION is defined ?

**Comment by VladimirZaets** [comment]
Hi @SikailoISM, please, sign CLA, otherwise, we can't process your pull request

**Review by ghost — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
Hi @SikailoISM , looks like source branch was removed. We can't process this PR without it. 
I'm closing this PR now, please, restore branch and reopen PR if you wish to continue!

**Comment by ghost** [comment]
https://github.com/magento/magento2/pull/19845
restored pull request

**Pull request closed without merging**
