### PR TITLE
fixed Notification page Select Visible items issue 

### PR DESCRIPTION
**Pull request by shikhamis11**
Fixed issue - magento#19285
On Notification page Select All and Select Visible both works same

### Description (*)
Fixed issue [#19285](https://github.com/magento/magento2/issues/19285) On Notification page Select All and Select Visible both works same

### Fixed Issues (if relevant)
[#19285](https://github.com/magento/magento2/issues/19285) On Notification page Select All and Select Visible both works same

### Manual testing scenarios (*)
1. Login to Magento Admin.
2. Select Notifications (Bell Icon from right top of the screen).
3. Click on "See All".
4. Default paging is set to 20 rows per page.
5. Make sure you have more than 20 notifications so that you can have paging available and some notification are on next pages.
6. Now from Mass Action dropdown select "Select All" action. This will select only visible notifications (currently 20, as 20 rows per page is setup) instead of all available records.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sivaschenko — CHANGES_REQUESTED** [review]
@shikhamis11 Thanks for the contribution! I don't think we should neglect the configurable mass action id field. The root cause of the issue is "LIMIT 20" that is added to collection selec. So to fix an issue, either this limit should not be added to the collection or it should be reset:

        if ($allIdsCollection instanceof AbstractDb) {
            $allIdsCollection->getSelect()->limit();
        }

**Comment by shikhamis11** [comment]
@sivaschenko Thanks for your concern I got your point . I have done changes as per your request so that It also consider others columns in massaction grid other than primary keys

**Comment by sivaschenko** [comment]
@shikhamis11 I am concerned about changing the behaviour of the `getColumnValues` original function. It may be used intentionally without resetting the select. It will be more safe to add a new function i.e. `getAllColumnValues`. What do you think about it?

**Comment by shikhamis11** [comment]
@sivaschenko yes I agree with you. We can add new specific function for this purpose so that it may not affect anywhere else.

I have committed changes please have a look

**Comment by shikhamis11** [comment]
@sivaschenko Please look into the changes

**Comment by shikhamis11** [comment]
@magento-engcom-team and @sivaschenko 
please review changes as I have updated code as per request

**Comment by sivaschenko** [comment]
@shikhamis11 sorry for slow response, I needed to discuss the update of AbstractCollection with colleagues. The thing is that:

- AbstractCollection is a framework API class, there is a probability that this class is extended and a method with the same name is already implemented, so adding a method can be backward incompatible
 - The added method currently have only one client call and considering the specificity of the method I am not sure that it is enough for it to be added to the framework

Considering the above, I think that it might be better to move the method out of framework or go with the solution that was already mentioned by me:

    if ($allIdsCollection instanceof AbstractDb) {
        $allIdsCollection->getSelect()->limit();
    }

Probably `instanceof` is not the absolute best approach, but I think in this case it is better than adding a method to `AbstractCollection`

**Comment by shikhamis11** [comment]
if ($allIdsCollection instanceof AbstractDb) {
    $allIdsCollection->getSelect()->limit();
}
@sivaschenko since the above code seems not working I made changes with a raw query which actually resets limit on the collection and provides all values. I also removed changes from Framework made changes only into the current one. 
so Please have a look at it.

**Comment by sivaschenko** [comment]
@shikhamis11 yes you are right, it doesn't work because the cloned collection is already loaded, it has to be cleared to reload data using new select without limit. I missed the `clear` call in the example. Please try the following

        if ($allIdsCollection instanceof AbstractDb) {
            $allIdsCollection->getSelect()->limit();
            $allIdsCollection->clear();
        }

**Comment by shikhamis11** [comment]
@sivaschenko Thanks for your suggestion. I have updated code Please check

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3588](https://jira.corp.magento.com/browse/ENGCOM-3588) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@shikhamis11 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by shikhamis11** [comment]
@sivaschenko and @magento-engcom-team when this Pull Request will be merged ?? 
I also want to Port this changes on lower release lines

**Comment by sivaschenko** [comment]
@shikhamis11 sorry for slow processing and any related inconvenience. This pull request is currently in process of delivery to mainline.

**Comment by shikhamis11** [comment]
alright @sivaschenko I am eagerly waiting for this to be merged

**Comment by magento-engcom-team** [comment]
Hi @shikhamis11. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
