### PR TITLE
Issue/26520 catalog search query error

### PR DESCRIPTION
**Pull request by ramesh-durairajaram**
### Description (*)
- Earlier Catalog Search was not working
- During a fresh installation of Magneto, this patch will now create `catalogsearch_fulltext_scope1` table in MySQL DB. Which was missing earlier.

### Fixed Issues (if relevant)

1. magento/magento2#26520: Search query throwing error in all case

### Manual testing scenarios (*)

1. After a fresh installation of this patch.
2. Search products using catalog search will work properly and show the catalog search result page.
3. Please find the below Postfix screenshot
catalogsearch_result

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ramesh-durairajaram** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @ramesh-durairajaram. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @ramesh-durairajaram, here is your [new Magento instance](https://pr-26803.instances.magento-community.engineering).
Admin access: [https://pr-26803.instances.magento-community.engineering/admin_0634](https://pr-26803.instances.magento-community.engineering/admin_0634)
Login: `43032806` Password: `52208f4b3d50`
Instance will be terminated in up to 3 hours.

**Comment by ramesh-durairajaram** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @ramesh-durairajaram. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @ramesh-durairajaram, here is your [Magento instance](https://i-26803-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26803-2-4-develop.instances.magento-community.engineering/admin_074f](https://i-26803-2-4-develop.instances.magento-community.engineering/admin_074f)
Login: `45946594` Password: `9ddd31676138`
Instance will be terminated in up to 3 hours.

**Comment by novikor** [comment]
Hi, @ramesh-durairajaram .

Thank you for your research and contribution, - it is highly appreciated.

So, [regarding your reply](https://github.com/magento/magento2/issues/26520#issuecomment-581881220) in #26520 :
The changes provided in https://github.com/magento/magento2/commit/c4c36dcc48c4e74a70aaf83cee760cc5ffa34d29 are intended to fix 2 problems:
1. Data patches are wrapped into transactions. The DDL operations caused by reindexing cause implicit commit and break the transactions. Such behavior is not acceptable.
2. Incompatibility with MySQL 8 that is related to point 1.

Because of these 2 points the solution provided in the current PR is not acceptable: there still are DDL operations in a Data Patch.

That's why I should close the PR.

**Comment by novikor** [comment]
I have already discussed the problem and its possible solutions with the Magento Maintainers team.

More likely the best solution is to add the full reindex to the very end of the Magento installation process. 

I am going to describe the issue and create a poll in [`appdesign` channel of MagentoCommeng Slack](https://magentocommeng.slack.com/archives/CBSL1DF8B)
to decide which solution is final.

Please don't hesitate to visit the channel and contact me via Slack if you are interested in solving the problem.

**Comment by speedupmate** [comment]
> More likely the best way is to add the full reindex to the very end of the Magento installation process.

how can this be a sane idea? 

* installation process should cover all aspects of installing the application (including schema) 
* proposed indexer run after installation is like installing a application in fault/broken state and running it on fault state (and pray that it will) to complete the installation

**Comment by novikor** [comment]
Hi, @speedupmate .
Please check the poll in https://magentocommeng.slack.com/archives/CBSL1DF8B

Proposed indexer run after installation means in should be executed automatically, not manually, - like when installing sample data, for example.

**Comment by speedupmate** [comment]
Sorry  if I sound rude and my bad english but I'm not sure if any of you have taken logics course or really got what it tried to teach you. Making indexers run automatically after installation to solve installation dependencies  is pure nonsense. Please refer to https://en.wikipedia.org/wiki/Square_of_opposition 

Related to this poll: We can vote on bad solutions and agree that we have a majority of bad solution supporters. But under the hood after installation the application is broken without followup maintenance commands to execute . 

The issue you are trying to solve is related to missing entities in DB and you are about to solve it by executing functionality of  installed application as followup procedure and praying that it would fix the issue. In addition by adding this you then  have another **dependency of indexers to be able to run in broken app installation state.** Please try to debug that in your mind before you implement it for your audience. 

The actual  logic that you are purposing with this is actually adding another installation routine (does not matter if executed manually or automatically). Like running X after installation to finish the installation and soon we probably would have Y to satisfy the missing features index don't include etc. Although it seems like easy way out then it is definitely not. Search (or whatever component depending on temp or tables created on runtime should estimate the need of such tables on installation time and satisfy its dependencies.

**Pull request closed without merging**
