### PR TITLE
[2.2] multiselect attribute options wrong translation on add product page 19388

### PR DESCRIPTION
**Pull request by novikor**
### Description (*)

- Set correct store for adminhtml area by default. The problem was that store with id=1 was used previously in admin panel which is wrong.
### Fixed Issues (if relevant)

1. magento/magento2#19388: Multiselect attribute options wrong translation on Add Product page

### Manual testing scenarios (*)

1. See #19388 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @novikor. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3556](https://jira.corp.magento.com/browse/ENGCOM-3556) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
@novikor thanks for the contribution! Can you please fix the failed tests on travis.

**Comment by novikor** [comment]
> @novikor thanks for the contribution! Can you please fix the failed tests on travis.

ok

**Comment by novikor** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @novikor. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @novikor, here is your [new Magento instance](https://pr-19397.instances.magento-community.engineering).
Admin access: [https://pr-19397.instances.magento-community.engineering/admin](https://pr-19397.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by novikor** [comment]
@sivaschenko , well, I failed to find an adequate solution.
It seems that the tests were developed using bug/feature with store_id I fixed in this PR: for example, flat collections are used (which is impossible for store 0).

**What is interesting:** I tried to run the same test (`\Catalog\Controller\Adminhtml\Product\Action\AttributeTest::testSaveActionChangeVisibility`) on 2.3-develop to understand the difference (it was passed OK in #19396 ). However it failed in the same way as it was with M2.2-develop. I am fully dissapointed about that.

Probably, there was a mistake during the travis environment initialization in scope of #19396?

**Comment by sivaschenko** [comment]
Hi @novikor , considering the major impact of this change and potentially a large scope of tests/functionality that has to be updated, I would ask you to close this pull request and work on delivering in to `2.3-develop` only.

Also, see my comment in 2.3 pull request: https://github.com/magento/magento2/pull/19396#issuecomment-445771689

**Pull request closed without merging**
