### PR TITLE
Update AddDataForItaly.php

### LINKED ISSUE #29582: [Issue] Update AddDataForItaly.php
This issue is automatically created based on existing pull request: magento/magento2#28248: Update AddDataForItaly.php

---------

### Description (*)

Updated italian provinces with last data

### Questions or comments

Data from Wikipedia (https://it.wikipedia.org/wiki/Province_d%27Italia)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by Delgraf**
### Description (*)

Updated italian provinces with last data

### Questions or comments

Data from Wikipedia (https://it.wikipedia.org/wiki/Province_d%27Italia)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29582: Update AddDataForItaly.php

### CODE REVIEW

**Comment by gwharton** [comment]
Will this actually get processed on upgrades from previous versions?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @Delgraf,
Unfortunately this fix will work only for new magento installations, but it will not work for upgraded installations.

In order to fix - could you create new data patch that will have dependency to this one?

Also please sign the Adobe CLA, otherwise we will not be able to accept your PR.

Thank you!

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@Delgraf will you be able to sign Adobe CLA and update your PR according to my feedback https://github.com/magento/magento2/pull/28248#pullrequestreview-461465286?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento create issue

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@Delgraf are you going to continue with the PR?

**Pull request closed without merging**
