### PR TITLE
[#25963] Fixed grids export: option labels are taken from grid filters and columns now.

### PR DESCRIPTION
**Pull request by novikor**
Grid Export rendered data is not reflecting in the exported File, Displayed ID instead of Rendered Label #25963.
Fixed grids export: option labels are taken from grid filters and columns now.

### Description (*)
A universal solution has been provided: now all the exported grids (Magento's and custom as well) should have option labels instead if option values for all the columns with type Select of Multiselect.

### Fixed Issues (if relevant)

1. magento/magento2#25963: Grid Export rendered data is not reflecting in the exported File, Displayed ID instead of Rendered Label

### Manual testing scenarios (*)
See #25963

### Questions or comments

A bunch of classes that acts as workaround for the issue should be deprecated/removed:
`\Magento\Customer\Ui\Component\DataProvider\Document`
`\Magento\Sales\Ui\Component\DataProvider\Document`

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by nuzil — CHANGES_REQUESTED** [review]
@novikor 
Can you please check failed tests?

**Comment by novikor** [comment]
Thank you for your review, @nuzil.
Will do.

**Comment by novikor** [comment]
Checked: `\Magento\Customer\Ui\Component\DataProvider\Document` can not be removed or deprecated. 
`\Magento\Sales\Ui\Component\DataProvider\Document` was safely deleted.

**Comment by novikor** [comment]
@nuzil  - done, please review. 
The failed functional test is reproduced on 2.4-develop: https://github.com/magento/magento2/issues/26607

**Comment by novikor** [comment]
@magento run all tests

**Comment by novikor** [comment]
@magento run functional tests

**Comment by novikor** [comment]
@magento run Functional Tests

**Comment by novikor** [comment]
@magento run Functional Tests CE
@magento run Functional Tests EE

**Comment by novikor** [comment]
@magento run Functional Tests EE

**Comment by novikor** [comment]
It seems that the PR will never be approved because of flaky tests

**Review by nuzil — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-6901](https://jira.corp.magento.com/browse/ENGCOM-6901) has been created to process this Pull Request
:eight_spoked_asterisk: @nuzil, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
