### PR TITLE
[SalesRule] Covering the CouponCodeValidation class by Unit Tests

### PR DESCRIPTION
**Pull request by eduard13**
### Description (*)
This PR covers the `\Magento\SalesRule\Observer\CouponCodeValidation` observer class by Unit Tests, that is used for validating the newly provided coupon code before using it while calculating totals.

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Good job, @eduard13!
Could you please fix minor recommendations reported by Static Test?
Thank you!

**Comment by eduard13** [comment]
Hi @dmytro-ch, the Static Tests were fixed.
Thank you.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5812](https://jira.corp.magento.com/browse/ENGCOM-5812) has been created to process this Pull Request
:eight_spoked_asterisk: @dmytro-ch, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
**Notice:** QA not applicable

**Pull request merged**
