### PR TITLE
25344: My Wish List items should not display in left side bar from Cu…

### LINKED ISSUE #25344: My Wish List items should not display in left side bar from Customer Dashboard My Wish List page
### Preconditions (*)

1. Magento 2.3.3
2.

### Steps to reproduce (*)

1. Login customer in front-end.
2. Add products to wish-list
3. Go to Customer My Account -> My Wish List.

### Expected result (*)

1. My Wish List items should not display in left side bar.
image

### Actual result (*)

1. My Wish List items displaying in left side bar.
image

### PR DESCRIPTION
**Pull request by sudheers-kensium**
#25344: My Wish List items should not display in left side bar from Customer Dashboard My Wish List page - fixed

### Description (*)

Fixes magento/magento2#25344: My Wish List items should not display in left side bar from Customer Dashboard My Wish List page

### Fixed Issues (if relevant)

1. magento/magento2#25344: My Wish List items should not display in left side bar from Customer Dashboard My Wish List page

### Manual testing scenarios (*)

1. Login customer in front-end.
2. Add products to wish-list
3. Go to Customer My Account -> My Wish List.
4. My Wish List items should not display in left side bar.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sudheers-kensium** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [new Magento instance](https://pr-25345.instances.magento-community.engineering).
Admin access: [https://pr-25345.instances.magento-community.engineering/admin](https://pr-25345.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sudheers-kensium** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-25345-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25345-2-3-develop.instances.magento-community.engineering/admin](https://i-25345-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by torhoehn** [comment]
@sudheers-kensium Thanks for your contribution! Please sign Adobe CLA.

**Comment by torhoehn** [comment]
@sudheers-kensium Please fix failing Functional Test.

**Comment by torhoehn** [comment]
@magento run all tests

**Comment by krzksz** [comment]
Hello @sudheers-kensium, are you still willing to continue working on this issue?

**Comment by sdzhepa** [comment]
Hello @sudheers-kensium

Could you please provide more information on why you consider it as bug or incorrect behavior that should be changed?
Probably you have links to official documentation where described expected result? Or you have examples when the current result block other functional user flows?

**Comment by sidolov** [comment]
Risk: medium since the changes are backward-incompatible and can affect 3d party developers.

**Comment by lenaorobei** [comment]
I'm closing this PR since this is an expected behaviour, please see https://github.com/magento/magento2/issues/25344#issuecomment-689028117.

**Comment by sdzhepa** [comment]
Hello @sudheers-kensium

After a couple of discussions was found the additional potential value of issue.
It can remove not only block/view but also improve performance. As I understood not two requests happen to get  Wishlist items. One for the widget and one for page content

**Comment by ihor-sviziev** [comment]
Moving this PR to "on hold" as it could be accepted only in 2.5

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @sudheers-kensium,
Could you re-target your PR to 2.5-develop branch?

**Comment by denchev** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
Hi 

I am closing this PR for now as it seems like it has become stale and still needs work.

Please feel free to reopen if you wish to continue.

Thanks!

**Pull request closed without merging**
