### PR TITLE
added an option to exclude cache types while cleaning and flushing

### LINKED ISSUE #35847: Add optionnal parameter to cache:clean and cache:flush to exclude type(s)
### Description (*)

In some occasions (deployment of a new version for instance), we may want to purge all cache except Full page cache.
This forces us to run `cache:clean` or `cache:flush` with the list of all types except `full_page`. Would be nicer to be able to exclude a type in those commands.

### Benefits

Simpler syntax, no need to change deployment code when a new type of cache is added by some extension.

### Example

At the moment we use : 
`./magento cache:flush config layout block_html collections reflection db_ddl compiled_config eav customer_notification config_integration config_integration_api config_webservice translate adyen fishpig_wordpress`

This feature request would allow to use : 
`./magento cache:flush --exclude full_page`

### PR DESCRIPTION
**Pull request by sandy6666**
Provided the feature to exclude cache type while cleaning the cache.

### Description (*)
In order to facilitate the admin to clear all caches excluding a particular cache, added a input option to take from admin and exclude it from available types using the below command.

#### Getting option from admin
`        $this->addOption(self::EXCLUDE_KEY_TYPES, '-e', InputOption::VALUE_OPTIONAL);
`
#### Excluding from cache type
`unset($cacheTypes[array_search($input->getOption(self::EXCLUDE_KEY_TYPES), $cacheTypes)]);
                $cacheTypes = array_values($cacheTypes);`

### Fixed Issues (if relevant)
1. Fixes magento/magento2#35847

### Manual testing scenarios (*)
1. Run the command ` bin/magento c:c --exclude config` or shorthand notation using  `bin/magento c:c -e config` to exclude the cache from not being cleared

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sandy6666** [comment]
@magento run all tests

**Comment by sandy6666** [comment]
@magento run all tests

**Comment by sandy6666** [comment]
@magento run all tests

**Comment by sandy6666** [comment]
@magento run all tests

**Comment by sandy6666** [comment]
@sdzhepa / @edenduong can you please review the PR.

**Review by edenduong — CHANGES_REQUESTED** [review]
Hi, 
Thank you for contribution. Could you please check Semantic Test? It is failed.

**Comment by sandy6666** [comment]
@magento run all tests

**Comment by sandy6666** [comment]
@magento run all tests

**Comment by sandy6666** [comment]
@magento run all tests

**Comment by sandy6666** [comment]
> Hi, Thank you for contribution. Could you please check Semantic Test? It is failed.

@edenduong I have updated the semantic issue.

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento run Functional Tests EE

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento run Functional Tests B2B, Integration Tests, Unit Tests

**Comment by engcom-Delta** [comment]
@edenduong, could you please review the changes.

**Review by edenduong — APPROVED** [review]

**Comment by engcom-Lima** [comment]
Hi @sandy6666 

Thanks for your contribution and collaboration.

It is oberved following observations:
1. After running command with multiple arguments it is not working as expected. When I run the command with multiple cache types **`bin/magento c:c --exclude config translate`** I can only see only **config** in the Excluded list and not for the translate. 
2. And in **Cleaned cache type** I can only see translate cache type not others. Screenshot is for your reference:
Screenshot 2023-04-27 at 5 56 19 PM

Please provide us information whether command will work for multiple arguments as we can see in [document](https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/cli/manage-cache.html#enable-or-disable-cache-types) , we can disable the multiple cache types by giving multiple values with command and also provide us information about Why after giving second argu in the command , we are getting only 2nd argument in **Cleaned Cache type** ?



Thanks

**Comment by engcom-Lima** [comment]
Hi @sandy6666 

Please provide the information asked in above [comment](https://github.com/magento/magento2/pull/36166#issuecomment-1525729304).

Thanks

**Comment by sandesh-nsight** [comment]
Hi @engcom-Lima i will check that issue and update the PR

**Comment by sandy6666** [comment]
Hello @engcom-Lima I will check this issue and update the PR

**Comment by sandy6666** [comment]
@engcom-Lima https://github.com/magento/magento2/pull/37498 update this here

**Pull request closed without merging**
