### PR TITLE
Fixed Issue #35899: Filtering with out of stock products, limited only to products in…

### LINKED ISSUE #35899: Catalog shown entire catalog items count if show_of_stock_option enabled
### Preconditions and environment

- 2.4-develop Vanila instance

### Steps to reproduce

1. Take Vanila instance by magento give me 2.4-develoop instance
2. Go to Stores->Configuration->Catalog->Inventory and Enable Display Out of Stock Products
3. Clear cache
4. Go to catalog Women->Tops->Bras & Tanks
5. Apply Filter Style->Bra that show 5 items

### Expected result

Total catalog items should show 5 items and 5 as total value

### Actual result

1. Shown 12 items in catalog
2. Shown 14 as total items
2022-08-09-17-15-35@2x

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### LINKED ISSUE #35960: Filters not working on category pages in 2.4.5
### Preconditions and environment

- Magento version - 2.4.5 

### Steps to reproduce

Set **Display Out of Stock Products** to **Yes** in the configuration under _Store > Configuration > Catalog > Inventory_ in the admin.

### Expected result

Filters should only show matching results on the category pages
[
Screenshot 2022-08-17 at 9 11 07 am
](url)

### Actual result

Instead it shows all the products in that category and works fine if I set **Display Out of Stock Products** to **No** 

Screenshot 2022-08-17 at 9 20 04 am

### Additional information

This seems to be the **getProductsIdsBySaleability** function resetting the filtered products items added in the SearchResultApplier file.

https://github.com/magento/magento2/blob/2.4.5/app/code/Magento/Elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php
Screenshot 2022-08-17 at 9 24 39 am

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### LINKED ISSUE #36055: Magento 2.4.5: Show Out Of Stock option outputs all available products during search
### Preconditions and environment

- Magento version 2.4.5
- PHP 8.1
- ES 7.17.0

On website I'm working on to upgrade to 2.4.5 from 2.4.3, the Catalog Search ouputs the whole Enabled Catalog:

image

Instead of only ouputting the search results which should be 664 items:

image

Sorry bad screenshots because I was pulling the store apart to try to understand where it's coming from.

This can sort of be replicated on Vanilla Magento 2.4.5 with test data.

Here are the settings:

**Catalog - > Inventory**
This is the main culprit (Display Out Of Stock Products = YES)
image

I believe there are some settings in the Catalog section that are also affecting the issue:

**Catalog - > Catalog**
image
image
image
image
image
image
image
image

### Steps to reproduce

1.  Login as admin.
2.  Go to Stores >> configuration >> Catalog >> Inventory >> Display Out Of Stock Products = YES)
3. On Vanilla 2.4.5 storefront Search for "ryker" it should output two items

/catalogsearch/result/?q=ryker

### Expected result

Two items are shown:
image

### Actual result

But it shows two items and toolbar shows "181 items":
image

### Additional information

On my site this is creating a problem because each search instead of 2 seconds, becomes a 22 second search. HELP!

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Bashev**
… result.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35899
2. Fixes magento/magento2#35960
3. Fixes magento/magento2#36055

### Manual testing scenarios (*)

see #35899
1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Bashev** [comment]
@magento give me test instance

**Comment by Bashev** [comment]
@magento run all tests

**Comment by Bashev** [comment]
@magento run WebAPI Tests

**Comment by Bashev** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by Bashev** [comment]
@magento run Integration Tests, Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by Bashev** [comment]
@magento run Functional Tests EE

**Comment by i6media** [comment]
@Bashev your PR still gives slow loading times, I'm even getting timeouts because all products are still loaded, and filtered by PHP afterwards, like @pmonosolo already mentioned [here](https://github.com/magento/magento2/issues/36055#issuecomment-1232191559).

It's kind of strange that this issue is closed and merged, since it doesn't resolve the issue in a clean matter imho.

**Comment by i6media** [comment]
Issue doesn't seem resolved by merged commit, please refer to: https://github.com/magento/magento2/issues/35899#issuecomment-1277717191

**Comment by i6media** [comment]
For people looking for a hotfix: https://github.com/plumrocket/module-layered-navigation-fix-magento-2.4.5

**Comment by FadedOut** [comment]
> For people looking for a temporary hotfix: https://github.com/plumrocket/module-layered-navigation-fix-magento-2.4.5

Awesome, this seemed to do it for me. The count is correct as well as the filtering. 

For anyone else coming across this and wants to use that file, there aren't any instructions. So in case anyone might be slightly confused this is what I did (there might be other ways, like maybe composer require, but this I found worked for me):

- I downloaded the zip of that file (Code > Download ZIP)
- Navigate to ./app/code/ and make a folder called: Plumrocket
- Go into newly created folder (Plumrocket)
- Make new folder called: ProductFilterFixMagento245
- Add contents of downloaded ZIP into that folder (contents: etc, Model, registration.php)

Run your normal commands

for example:
```
php bin/magento setup:upgrade ; php bin/magento setup:di:compile ; php bin/magento setup:static-content:deploy ; php bin/magento cache:flush ; php bin/magento cache:clean
```

Thanks to the great help out there fixing up these constant regressions during these "updates". Every update there is always serious regressions. I wonder who _tests_ these "updates"...

**Comment by mobweb** [comment]
> For people looking for a temporary hotfix: https://github.com/plumrocket/module-layered-navigation-fix-magento-2.4.5

This helped me fix the issue on regular category pages, but on a category page where a filter is applied, the sorting by "is_salable" is lost.

However, the fix proposed in this issue does not solve the issue at all, at least for me.

**Pull request merged**
