### PR TITLE
Fix issue where address extension attributes would be set as an array

### LINKED ISSUE #26682: Magento 2.3.4 Quote Address Extension Attribute Issue
### Preconditions (*)

1. Using Magento 2.3.4
2. USing a custom extension attribute on `Magento\Quote\Api\Data\AddressInterface` Example module here: https://github.com/NathMorgan/module-test-module

### Steps to reproduce (*)
1. Sending a post request to `estimate-shipping-methods` containing a `extension_attributes`

For example a post request to `/rest/default/V1/guest-carts/{cartId}/estimate-shipping-methods` with the following example data `{"address":{"street":["Example High Street"],"city":"Example City","region_id":null,"region":null,"country_id":"GB","postcode":"TES 01","company":"Example Company","telephone":"0000 00000","fax":null,"extension_attributes":{"test_attribute":"2"}}}`

### Expected result (*)
1. Above action completed successfully

### Actual result (*)
1. 500 Error with the message `Uncaught Error: Call to a member function setDiscounts() on array in /var/www/html/vendor/magento/module-sales-rule/Model/Quote/Discount.php: 117`

This issue seems to be introduced with this commit: https://github.com/magento/magento2/commit/6900c38941850706d9bff3aae76a428afae1343c

This seems to effect any extension attribute set on `Magento\Quote\Api\Data\AddressInterface` that is not a object

### PR DESCRIPTION
**Pull request by NathMorgan**
### Description (*)

This PR fixes a issue where the extension attributes in the `$address` parameter being sent to https://github.com/magento/magento2/blob/606c3e870013058b29398b2260fb76f05d5e9594/app/code/Magento/Quote/Model/ShippingMethodManagement.php#L308 will get converted to an array. This causes an issue on https://github.com/magento/magento2/blob/6900c38941850706d9bff3aae76a428afae1343c/app/code/Magento/SalesRule/Model/Quote/Discount.php#L106 where it tries to access the extension attribute on the address as a object.

This fix sets the extension attribute back as a object after the `addData()` function gets called.

### Fixed Issues (if relevant)
1. Fixes #26682 : Magento 2.3.4 Quote Address Extension Attribute Issue 

### Manual testing scenarios (*)
1. Create a custom extension attribute on the address field using this example module https://github.com/NathMorgan/module-test-module
2. Call the `estimate-shipping-methods` passing the extension attribute. For example: `{"address":{"street":["Example High Street"],"city":"Example City","region_id":null,"region":null,"country_id":"GB","postcode":"TES 01","company":"Example Company","telephone":"0000 00000","fax":null,"extension_attributes":{"test_attribute":"2"}}}`

### Questions or comments

Sadly I'm a bit unsure how to cover this with unit tests if anyone can provide assistance that would be much appericated

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
can you coverage your changes with tests
method getShippingMethods in corressponding class

**Comment by Swahjak** [comment]
@NathMorgan I think this could be easily covered by adding the 'discount' extension attribute to `dev/tests/api-functional/testsuite/Magento/Quote/Api/GuestShipmentEstimationTest.php` like:

```
            $data = [
                AddressInterface::KEY_ID => (int)$address->getId(),
                AddressInterface::KEY_REGION => $address->getRegion(),
                AddressInterface::KEY_REGION_ID => $address->getRegionId(),
                AddressInterface::KEY_REGION_CODE => $address->getRegionCode(),
                AddressInterface::KEY_COUNTRY_ID => $address->getCountryId(),
                AddressInterface::KEY_STREET => $address->getStreet(),
                AddressInterface::KEY_COMPANY => $address->getCompany(),
                AddressInterface::KEY_TELEPHONE => $address->getTelephone(),
                AddressInterface::KEY_POSTCODE => $address->getPostcode(),
                AddressInterface::KEY_CITY => $address->getCity(),
                AddressInterface::KEY_FIRSTNAME => $address->getFirstname(),
                AddressInterface::KEY_LASTNAME => $address->getLastname(),
                AddressInterface::KEY_CUSTOMER_ID => $address->getCustomerId(),
                AddressInterface::KEY_EMAIL => $address->getEmail(),
                AddressInterface::SAME_AS_BILLING => $address->getSameAsBilling(),
                AddressInterface::CUSTOMER_ADDRESS_ID => $address->getCustomerAddressId(),
                AddressInterface::SAVE_IN_ADDRESS_BOOK => $address->getSaveInAddressBook(),
                ExtensibleDataInterface::EXTENSION_ATTRIBUTES_KEY => [
                    'discounts' => []
                ],
            ];
...
            $requestData = [
                'address' => [
                    'country_id' => "US",
                    'postcode' => null,
                    'region' => null,
                    'region_id' => null,
                    ExtensibleDataInterface::EXTENSION_ATTRIBUTES_KEY => [
                        'discounts' => []
                    ]
                ],
```
The 'discounts' extension is part of the `SalesRule` module so I'm not sure if you have to modify the existing test or create a new test in the `SalesRule` test directory. Maybe @mrtuvn has a _useful_ comment on that.

**Comment by NathMorgan** [comment]
I've got another change to make to the code in this PR as I've noticed this fix currently breaks logged in customers with saved addresses

**Comment by ihor-sviziev** [comment]
Hi @NathMorgan,
The issue was already fixed, more info in https://github.com/magento/magento2/issues/26682#issuecomment-639294312
I'm closing your PR.

**Pull request closed without merging**
