### PR TITLE
Move default session lifetime from encryption module to security module

### LINKED ISSUE #30859: [Issue] Move default session lifetime from encryption module to security module
**Preconditions:**

This issue is automatically created based on existing pull request: magento/magento2#30825: Move default session lifetime from encryption module to security module

**Steps to reproduce:**

1. Go to Admin -> Stores -> Configuration -> Advanced -> Admin -> Security and set 
**_Admin Session Lifetime (seconds)_** to **_60_** sec;

Screenshot from 2020-11-10 14-56-14
2. Save settings and clear cache;
3. Wait 60 sec and click on the Dashboard;

**Expected Result:** :heavy_check_mark: The user admin has been logged out

Screenshot from 2020-11-10 14-58-32
---------
Move default session lifetime from encryption module to security module

### PR DESCRIPTION
**Pull request by thomas-kl1**
Move default session lifetime from encryption module to security module

### Resolved issues:
1. [x] resolves magento/magento2#30859: Move default session lifetime from encryption module to security module

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento create issue

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8445](https://jira.corp.magento.com/browse/ENGCOM-8445) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Go to Admin -> Stores -> Configuration -> Advanced -> Admin -> Security and set 
**_Admin Session Lifetime (seconds)_** to **_60_** sec;

Screenshot from 2020-11-10 14-56-14
2. Save settings and clear cache;
3. Wait 60 sec and click on the Dashboard;

**After:** :heavy_check_mark: The user admin has been logged out

Screenshot from 2020-11-10 14-58-32

**Pull request merged**
