### PR TITLE
Fixed-Product-page-tabbing-content-misalignment-in-mobile-view :: Pro…

### PR DESCRIPTION
**Pull request by parag2jcommerce**
…duct Page tabbing Content Misaligned in mobile view

### Fixed Issues (if relevant)

1. magento/magento2#20468: On Product Page Tabings Content Misaligned on Mobile View
2. ...

### Manual testing scenarios (*)

1. Any product page
2. Issue find in mobile view (below 768 resolution)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20469) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @parag2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by priti2jcommerce — APPROVED** [review]

**Comment by sdzhepa** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [new Magento instance](https://pr-20469.instances.magento-community.engineering).
Admin access: [https://pr-20469.instances.magento-community.engineering/admin](https://pr-20469.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by sdzhepa — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, thank you for the review.
[ENGCOM-4031](https://jira.corp.magento.com/browse/ENGCOM-4031) has been created to process this Pull Request

**Pull request merged**
