### PR TITLE
Fix for extremely slow query in deleteOldUrls method

### PR DESCRIPTION
**Pull request by HanakJakub**
### Description

We have 300 000+ products in catalog and 5 websites and when we want to change for example url of category in administration for even not that big category, around 500 products, it was impossible to complete this request. After debugging I found out that query in DbStorage.php in deleteOldUrls is taking for this change in small category 1 hour to finish. It is quite a long time to finish a query. After small updates in code this query is taking 0.15 seconds.

### Manual testing scenarios

1. Create big catalog with 10000+ products with multiple store
2. Try to change data for category, for example url and compare queries generated in deleteOldUrls

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18456) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=18456) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: HanakJakub<br/>:x: Jakub Hanák<hr/>**Jakub Hanák** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by sidolov** [comment]
Hi @HanakJakub , thank you for your contribution! Looks like your commits were made with email different than in your GitHub profile. Please, add email from commits to your profile and sign CLA. 
Thank you!

**Comment by HanakJakub** [comment]
@sidolov sorry for late response.. it is done now

**Comment by sidolov** [comment]
Hi @HanakJakub , few commits with different email still present in the PR, please, take a look 
Thank you!

**Comment by sidolov** [comment]
Hi @HanakJakub , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
