### PR TITLE
fix currency in new widget

### LINKED ISSUE #37898: Currency code not change in New product widget
### Preconditions and environment

- Magento version 2.4-develop
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

1. Setup multi currency in admin in Stores -> Configuration -> General -> Currency Setup
2. Add new product widget in homepage cms: {{widget type="Magento\Catalog\Block\Product\Widget\NewWidget" display_type="new_products" show_pager="0" products_count="10" template="product/widget/new/content/new_grid.phtml"}} 
3. Change value attribute Set Product as New From with current date for some random product
4. In frontend change currency in header

### Expected result

Currency code product in widget displays the same as the currency selected in frontend

### Actual result

Currency code not change when change currency in frontend

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rogerdz**
### Description (*)
Currency code in new product widget not change

### Fixed Issues (if relevant)

1. Fixes #37898  

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run  Unit Tests, Integration Tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run WebAPI Tests, Unit Tests, Integration Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by rogerdz** [comment]
@magento run Unit Tests, WebAPI Tests, Functional Tests EE, Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE

**Review by andrewbess — APPROVED** [review]
Hello @rogerdz 
Thank you for your contribution
The changes look good for me
Approved

**Comment by andrewbess** [comment]
@magento run WebAPI Tests

**Comment by engcom-Bravo** [comment]
@magento give me test instance

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi @rogerdz,

Thanks for the collaboration & contribution!

:heavy_check_mark: QA Passed

**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Setup multi currency in admin in Stores -> Configuration -> General -> Currency Setup
- Add new product widget in homepage cms: {{widget type="Magento\Catalog\Block\Product\Widget\NewWidget" display_type="new_products" show_pager="0" products_count="10" template="product/widget/new/content/new_grid.phtml"}}
- Change value attribute Set Product as New From with current date for some random product
- In frontend change currency in header


**Before:** :heavy_multiplication_x: 


Screenshot 2024-04-18 at 12 46 34




**After:** :heavy_check_mark:  


Screenshot 2024-04-18 at 13 14 19



Builds are failed. Hence, moving this PR to **Extended Testing.**


Thanks.

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B ,Functional Tests EE

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B,Functional Tests EE

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Unit Tests,Integration Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by engcom-Echo** [comment]
Functional Tests B2B,Functional Tests CE, Functional Tests EE failure are different on last two run on same commit. Also it contains few known failure.

Functional Tests B2B 
Run1
37899-b2b

Run2
Screenshot 2024-05-20 at 4 47 10 PM

Functional Tests CE
Run1
37899-ce

Run2
Screenshot 2024-05-20 at 4 47 17 PM

Functional Tests EE
Run1
37899-ee

Run2
Screenshot 2024-05-20 at 4 47 26 PM

WebApi Tests contains known failure.
Screenshot 2024-05-20 at 4 50 21 PM

Hence moving it to `merge in progress`

**Pull request merged**
