### PR TITLE
Solved Customer Prefix not saved while guest order

### LINKED ISSUE #27849: Customer Prefix is not saved in guest orders
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Set `customer/address/prefix_show` to required
2. Go to the frontend and purchase an order as guest
3. During the checkout process make sure, that the prefix is required and this way filled

### Expected result (*)

1. I would expect that the prefix is saved in the database and is shown in the order view in the backend.

### Actual result (*)

1.The prefix is not saved and not shown in the backend order view.

### PR DESCRIPTION
**Pull request by chirag-d-wagento**
### Description (*)
Customer Prefix filed in the sales_order table is not getting saved when place order as a guest customer.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#27849

### Manual testing scenarios (*)

1. Go To Backend Admin > Stores > Configuration > Customers > Customer Configuration > Name and Address Options and make Show Prefix Required and saved it.
2. Go to the frontend and place the order as a guest. While entering the billing address fill the Name Prefix text box.
3. After successful order placement check filed sales_order.customer_prefix in the database. It should be filled up.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by vijay-wagento** [comment]
dmcdindia2020

**Comment by vijay-wagento** [comment]
#dmcdindia2020

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @chirag-d-wagento. Thank you for your collaboration. According to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered by autotests. Could I ask you to cover your changes with an integration test, please?

You may extend the [existing](https://github.com/magento/magento2/blob/cf795895f671938b76fe2eebac24baca3d6e282f/dev/tests/integration/testsuite/Magento/Quote/Model/QuoteManagementTest.php#L32) test to save some time.

Thank you!

**Comment by chirag-d-wagento** [comment]
@rogyar yes I will add.

**Comment by chirag-d-wagento** [comment]
@rogyar Can you help me to write an integration test? QuoteManagementTest.php does not contain the method in which I have made the change. So should I add that method in the same class? Or do I need to create a new class?  sorry I never write an integration test.

**Comment by rogyar** [comment]
Hi @chirag-d-wagento. That's right, you need to create a new method in the existing class. The method will place the order and check the customer prefix is there after placing the order. 
You may copy some parts of the [existing test](https://github.com/magento/magento2/blob/cf795895f671938b76fe2eebac24baca3d6e282f/dev/tests/integration/testsuite/Magento/Quote/Model/QuoteManagementTest.php#L94) and assert that the prefix exists in the order. 

I hope it will help

**Comment by chirag-d-wagento** [comment]
Thanks @rogyar for help. Will do it.

**Comment by sidolov** [comment]
@chirag-d-wagento  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
