### PR TITLE
Removed CliCacheFlushActionGroup usage for CatalogRule

### LINKED ISSUE #31860: [Issue] Removed CliCacheFlushActionGroup usage for CatalogRule
This issue is automatically created based on existing pull request: magento/magento2#31859: Removed CliCacheFlushActionGroup usage for CatalogRule

---------
### Description
Removed usage or changed value of CliCacheFlushActionGroup action group for CatalogRule, Backend, Bundle and BundleImportExport modules.

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Removed usage or changed value of CliCacheFlushActionGroup action group for CatalogRule, Backend, Bundle and BundleImportExport modules.

### Resolved issues:
1. [x] resolves magento/magento2#31860: Removed CliCacheFlushActionGroup usage for CatalogRule

### CODE REVIEW

**Comment by sergiy-v** [comment]
@magento create issue

**Comment by sergiy-v** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B,Semantic Version Checker

**Comment by sergiy-v** [comment]
@magento run Functional Tests EE

**Comment by sergiy-v** [comment]
@magento run WebAPI Tests, Unit Tests, Static Tests, Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B, Magento Health Index, Integration Tests, Database Compare

**Review by eduard13 — APPROVED** [review]
Good job 👍

**Comment by engcom-Bravo** [comment]
Manual QA not applicable for MFTF refactoring PR. Moving this PR to _Extending Testing_ column

**Pull request merged**
