### PR TITLE
Exception in getMediaGalleryImages()

### PR DESCRIPTION
**Pull request by angelo983**
Trying to access a member function count() on array result in this error:
PHP Fatal error: Uncaught Error: Call to a member function count() on array in /vendor/magento/module-catalog/Model/Product.php:1533
Stack trace:
#0 /vendor/magento/module-configurable-product/Block/Plugin/Product/Media/Gallery.php(62): Magento\Catalog\Model\Product->getMediaGalleryImages()
#1 /vendor/magento/module-configurable-product/Block/Plugin/Product/Media/Gallery.php(49): Magento\ConfigurableProduct\Block\Plugin\Product\Media\Gallery->getProductGallery(Object(Magento\Catalog\Model\Product\Interceptor))
#2 /vendor/magento/framework/Interception/Interceptor.php(146): Magento\ConfigurableProduct\Block\Plugin\Product\Media\Gallery->afterGetOptionsMediaGalleryDataJson(Object(Magento\ProductVideo\Block\Product\View\Gallery\Interceptor), Array)

### CODE REVIEW

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Hi @angelo983, could you please provide use case when you are experiencing this issue and steps to reproduce? Thank you.

**Comment by angelo983** [comment]
> Hi @angelo983, could you please provide use case when you are experiencing this issue and steps to reproduce? Thank you.

Hello, no need of reproducing it. It's a typo in the code

**Comment by lenaorobei** [comment]
@angelo983 please elaborate the steps to reproduce this issue. How are you getting the described fatal error?

**Comment by lenaorobei** [comment]
Closing this PR due to inactivity. Please feel free to reopen if you are going to continue working on it.
Thank you.

**Comment by udovicic** [comment]
I can't agree this is a typo, just to line above the change, the same value is set to the collection. But in some cases, this ends up as an array causing the mentioned array. Not sure about the steps to reproduce, but it is definitely there.

**Pull request closed without merging**
