### PR TITLE
Use $escaper for XSS prevention

### PR DESCRIPTION
**Pull request by mageprince**
### Description (*)

Use $escaper variable instead of $block as it's deprecated

### Questions or comments

As now with Magento 2.4.x XSS prevention functions like `escapeHtml` `escapeJs` `escapeHtmlAttr` etc. of class `\Magento\Framework\View\Element\AbstractBlock` deprecated
More info: https://devdocs.magento.com/guides/v2.4/extension-dev-guide/xss-protection.html

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hostep** [comment]
This is more or less a duplicate of https://github.com/magento/magento2/pull/30639, in which we decided not to replace the escaper yet just willy-nilly. We would wait just before Magento 2.5.0 is to be released to update it in all the frontend-related files.

**Comment by ihor-sviziev** [comment]
@hostep thank you! Moved to on hold status

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @mageprince,
Branch 2.5-develop was already created. Could you re-target this PR to it?

**Comment by ihor-sviziev** [comment]
Hi @mageprince,
We have better PR that fixes this issue for the whole catalog module, https://github.com/magento/magento2/pull/31684.
I'm closing this PR.

**Pull request closed without merging**
