### PR TITLE
Order-view-invoices :: Order view invoices template not display prope…

### PR DESCRIPTION
**Pull request by ranee2jcommerce**
…r on ipad

### Fixed Issues (if relevant)

1. magento/magento2#20373: Order view invoices template not display proper on ipad

### Manual testing scenarios (*)

1. In admin Go to Sales -> Orders ->click on view -> check invoices tab under Order view

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20374) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @ranee2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3894](https://jira.corp.magento.com/browse/ENGCOM-3894) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@ranee2jcommerce thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by ghost** [comment]
Hi @ranee2jcommerce, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+magento2+20374), it will take less than a minute. </br>Your feedback will help us to improve contribution process.

**Comment by magento-engcom-team** [comment]
Hi @ranee2jcommerce. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Comment by magento-engcom-team** [comment]
Hi @ranee2jcommerce. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
