### PR TITLE
Typo Mistake

### PR DESCRIPTION
**Pull request by mayankzalavadia**
### Typo Mistake in core code.

1. app/code/Magento/Sales/Block/Adminhtml/Order/Creditmemo/Create/Adjustments.php

### Manual testing scenarios (*)

1. Open file from **app/code/Magento/Sales/Block/Adminhtml/Order/Creditmemo/Create/Adjustments.php** and check line number 63 and find `'code' => 'agjustments'` spelling is wrong.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lbajsarowicz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-6726](https://jira.corp.magento.com/browse/ENGCOM-6726) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Charlie** [comment]
Hi @mayankzalavadia, please sign CLA.

**Comment by engcom-Charlie** [comment]
Failure of functional test, not related to the changes in this PR , test failing on 2.4-develop branch
73529028-a23f8180-441e-11ea-8642-6d0f12b8b6de

**Pull request merged**
