### PR TITLE
Improve developer experience: RuntimeException thrown by AbstractFactory::createObject now contains the reason.

### LINKED ISSUE #26550: Any reason for not printing Exception Message in ObjectManager\Factory\AbstractFactory::createObject?
### Summary (*)
When debugging an error that prevents object creation, the original exception message is not printed, its just logged. I think it would improve the developer experience when working on cli code, to see the message instantly and not having it to look up in the log.

Source of the RuntimeException:
magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php::createObject

### Examples (*)
CLI Output: 
```
In AbstractFactory.php line 124:
  [Magento\Framework\Exception\RuntimeException]                               
  Type Error occurred when creating object:   
  Leonex\Import\Model\Transformer\ProductData\Categories
  Exception trace: [...]
```      
system.log:
                                                  
`[2020-01-27 11:36:15] main.CRITICAL: Type Error occurred when creating object: Leonex\Import\Model\Transformer\ProductData\Categories, Too few arguments to function Leonex\ETL\Logger\AbstractLog::__construct(), 0 passed in /srv/projects/rb/htdocs/magento/app/code/Leonex/Import/Model/Transformer/ProductData/Categories.php on line 63 and exactly 1 expected [] []`
                                                                

### Proposed solution
Printing the exception message too.

### PR DESCRIPTION
**Pull request by marvinhinz**
This implements feature request #26550

When debugging an error that prevents object creation, the original exception message is not printed, its just logged. I think it would improve the developer experience when working on cli code, to see the message instantly and not having it to look up in the log.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#26550: Any reason for not printing Exception Message in ObjectManager\Factory\AbstractFactory::createObject?

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x ] Pull request has a meaningful description of its purpose
 - [x ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by marvinhinz** [comment]
@kandy @buskamuza are tests needed to merge this? thank you!

**Comment by marvinhinz** [comment]
*bump*

**Comment by marvinhinz** [comment]
@kandy @buskamuza ? :)

**Comment by thampe** [comment]
Hi,

is there any progeress on this?

**Comment by marvinhinz** [comment]
@ihor-sviziev maybe you could take a look at this too? I still encounter this problem often while developing. It would be really nice to have this merged! :)

**Review by kandy — APPROVED** [review]

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7532](https://jira.corp.magento.com/browse/ENGCOM-7532) has been created to process this Pull Request

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
@marvinhinz  Could you fix the failed static tests? Thanks!

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7532](https://jira.corp.magento.com/browse/ENGCOM-7532) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:**
Screenshot from 2020-05-14 14-28-08

**After:** :heavy_check_mark: with exception message
Screenshot from 2020-05-14 14-29-49

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @ihor-sviziev, please review the test coverage.

**Review by ihor-sviziev — APPROVED** [review]
Looks good. Approved ✔

Thx for covering it, I thought it will be too hard

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7532](https://jira.corp.magento.com/browse/ENGCOM-7532) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
