### PR TITLE
 Replaced @escapeNotVerified annotations

### PR DESCRIPTION
**Pull request by istiahailo**
### Description
There were added the escape functions to prevent XSS issues.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=16091) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @istiahailo. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on Pull Request changes
- `@magento-engcom-team give me new test instance` - deploy **NEW** test instance based on Pull Request changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy Vanilla Magento instance for Issue or Pull Request

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
I don't think it's a good idea to escape translations, like `__('SKU')`.

**Comment by YevSent** [comment]
@orlangur, translations also should be escaped. It's possible when translation would contain HTML tags for different languages. You can't guarantee that, for example, a French (or any other) translation for `SKU` will be without HTML.

**Comment by magento-engcom-team** [comment]
@istiahailo thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
Hi @istiahailo. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.6 release.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Comment by istiahailo** [comment]
The "Porting tool" can't  port commits automatically to 2.3 release line.These commits need the manual porting.

**Pull request merged**
