### PR TITLE
ui select list visible even though it is disabled

### LINKED ISSUE #29098: [Issue] ui select list visible even though it is disabled
This issue is automatically created based on existing pull request: magento/magento2#27896: ui select list visible even though it is disabled

---------

**Preconditions:**

Magento 2.4-develop

This PR fixes the following bug,
If we disable the UI select component by using this.disabled(true). still its options are visible when we click it. please see the below image for reference.

**Steps to reproduce:**

1. Navigate to the product edit page;
2. Disable any one of the UI select using the following code:

```js
this.disabled(true);
```
3. Now click on the UI select;

**Actual Result:** :heavy_multiplication_x: after disabling the options are still visible

Peek 2020-09-08 12-29

**Expected Result:** :heavy_check_mark: list options shouldn't be visible when it's disabled

Peek 2020-09-08 12-57

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by Mohamed-Asar**
### Description (*)
This PR fixes the following bug,
If we disable the UI select component by using this.disabled(true). still its options are visible when we click it. please see the below image for reference.

**Before:**

before

**After:**

after

### Manual testing scenarios (*)
Navigate to the product edit page. 
Disable any one of the UI select using the following code (this.disabled(true))
Now click the UI select, list options are not visible anymore when it's disabled

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29098: ui select list visible even though it is disabled

### CODE REVIEW

**Comment by Mohamed-Asar** [comment]
@lenaorobei please review it.

**Comment by Mohamed-Asar** [comment]
@magento run Functional Tests CE

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Hi @Mohamed-Asar. From the description it is hard to understand the actual issue and and the value of fix. Could you please provide more information?

**Comment by Mohamed-Asar** [comment]
Hi, @lenaorobei I have updated the issue description. please check. let me know if you need more information.

**Comment by engcom-Echo** [comment]
Could you please cover these changes with autotests.
It is required according to the Definition of Done

**Comment by engcom-Charlie** [comment]
Hi @Mohamed-Asar, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Comment by Mohamed-Asar** [comment]
@engcom-Charlie Please re-open this PR

@engcom-Echo  I could n't able to cover mftf for this case. because this issue exists only when the ui-select dropdown is disabled, Not able to disable the ui-select by mftf.

**Comment by VladimirZaets** [comment]
@magento create issue

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @Mohamed-Asar, thanks for the pull request, it looks good! The propose of the changes are clear now, would you be able to cover this change with tests?

Thanks!

**Comment by Mohamed-Asar** [comment]
Hi @gabrieldagama, I couldn't able to cover MFTF for this issue. Which tests do I need to cover?

**Comment by gabrieldagama** [comment]
Hi, @Mohamed-Asar I think we can use MFTF tests to make sure when the user clicks on the select, if the field is disabled the underneath window doesn't open, what do you think?

**Comment by engcom-Echo** [comment]
Hi, @Mohamed-Asar. It may be easier for you to cover this with Jasmine test.
Look file dev/tests/js/jasmine/tests/app/code/Magento/Ui/base/js/form/ui-select.test.js

**Comment by Mohamed-Asar** [comment]
@engcom-Echo Sure Will do.

**Comment by Mohamed-Asar** [comment]
@magento run tests

**Comment by Mohamed-Asar** [comment]
@magento run all tests

**Comment by Mohamed-Asar** [comment]
@engcom-Echo @gabrieldagama  covered this change with the jasmine test. please review

**Review by gabrieldagama — APPROVED** [review]
Thanks for the updates @Mohamed-Asar, the changes are approved.

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8152](https://jira.corp.magento.com/browse/ENGCOM-8152) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Navigate to the product edit page;
2. Disable any one of the UI select using the following code:

```js
this.disabled(true);
```
3. Now click on the UI select;

**Before:** :heavy_multiplication_x: after disabling the options are still visible

Peek 2020-09-08 12-29

**After:** :heavy_check_mark: list options are not visible anymore when it's disabled

Peek 2020-09-08 12-57

**Pull request merged**
