### PR TITLE
Fix issue 19380 - Sales admin new order with configurable product selection of options design issue

### PR DESCRIPTION
**Pull request by SyntaxKay**
### Description (*)

Sales admin new order with configurable product selection of options design issue
### Fixed Issues (if relevant)

1. magento/magento2#19380 : Sales admin new order with configurable product selection of options design issue

### Manual testing scenarios (*)

1. N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2.3 pull request: https://github.com/magento/magento2/pull/19382

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by SyntaxKay** [comment]
Hi @sivaschenko 
I have updated code in 2.2-develop branch.

**Comment by sivaschenko** [comment]
@speedy008 Thank you!

**Comment by sivaschenko** [comment]
Hi @speedy008 closing this pull request as https://github.com/magento/magento2/pull/19382 is closed

**Comment by SyntaxKay** [comment]
@sivaschenko I have done changes into both pull request https://github.com/magento/magento2/pull/19382 and this https://github.com/magento/magento2/pull/19381

**Comment by SyntaxKay** [comment]
@sivaschenko i have resolved catalog design issue as well

**Comment by sivaschenko** [comment]
Closing this pull request as we do not accept minor style changes to 2.2-develop (see [Contribution Guide](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for details)

**Pull request closed without merging**
