### PR TITLE
MFTF: Reset Admin Password With Enabled Captcha

### PR DESCRIPTION
**Pull request by DmitryTsymbal**
This PR contains a test for reseting customer password with enabled captcha

**Steps to reproduce:**

1 - Navigate to admin reset password page

2 - Try to reset the password with incorrect captcha values

3 - Reset admin password with correct captcha values

4 - Perform Assertions

### CODE REVIEW

**Comment by DmitryTsymbal** [comment]
@magento run all tests

**Comment by dmytro-ch** [comment]
@magento run Unit Tests

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-9046](https://jira.corp.magento.com/browse/ENGCOM-9046) has been created to process this Pull Request

**Review by Den4ik — APPROVED** [review]
Hi @DmitryTsymbal 
Good job :+1:

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9046](https://jira.corp.magento.com/browse/ENGCOM-9046) has been created to process this Pull Request

**Comment by dmitriyprime** [comment]
:heavy_check_mark: QA passed

**Comment by Den4ik** [comment]
@magento run all tests

**Pull request merged**
