### PR TITLE
Removed State/Province of shipping address when not added in billing address by customer

### LINKED ISSUE #31608: Shipping address region leaking into billing address
### Preconditions

1. Magento 2.4;

### Steps to reproduce

1. Create a purchase with billing address in the UK and Shipping address in Croatia. Make sure the `State/Province` field for the billing address is empty.

### Expected result

1. Billing address does not have a region name.

### Actual result

1. Billing address has a region name.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by saphaljha**
### Description (*)
Removed State/Province of shipping address when not added in billing address by customer

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31608

### Manual testing scenarios (*)

1. manually tested

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by saphaljha** [comment]
@magento run all tests

**Comment by saphaljha** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by saphaljha** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by saphaljha** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by saphaljha** [comment]
@magento run Functional Tests CE

**Comment by saphaljha** [comment]
@magento run Functional Tests CE

**Comment by saphaljha** [comment]
@magento run Functional Tests CE

**Comment by saphaljha** [comment]
Hello @coderimus ,
Could you please review the PR?

**Review by coderimus — APPROVED** [review]
Hello @saphaljha 
Thank you for the fix 👍 

About the solution: take into account that the method should return an object with the specific data filtered by country I think that unset data looks valid. This allowed being sure that the object will have only filtred data.
@sivaschenko can you, please, validate this PR also?

**Comment by engcom-Alfa** [comment]
@coderimus Could you put an appropriate label for test coverage?
Thanks!

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @saphaljha .
Due to the [Magento Definition of Done](https://devdocs.magento.com/contributor-guide/contributing_dod.html), all code changes must be covered by automated tests and it's required part of code contribution.
Could you cover your changes with some automated test?
Thanks!

**Comment by engcom-Hotel** [comment]
Hello @saphaljha,
I'll help with the test.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by saphaljha** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Review by coderimus — CHANGES_REQUESTED** [review]
@saphaljha after discussion with @sivaschenko we think that the provided change looks risky because there is a possibility to have 3rd party vendors and customisations relay on the object data.
As a next step, I could suggest reviewing `what is the reason `_loadByCountry` method is applied to already populated Region? Can we ensure this method is applied only to new objects?` - cc @sivaschenko

**Comment by eduard13** [comment]
Hi @saphaljha thank you for the PR, however there is another PR #32187 that provides a better and less risky implementation. Closing this one as not being actual anymore.

Thank you for your contribution.

**Pull request closed without merging**
