### PR TITLE
Fix: Attribute Option with zero at the beginning does not work if there is already option with the same number without the zero [REST API]

### PR DESCRIPTION
**Pull request by ghost**
### Description
Fix: Attribute Option with zero at the beginning does not work if there is already option with the same number without the zero

### Fixed Issues
1. magento/magento2#19436: Attribute Option with zero at the bigining does not work if there is already option with the same number without the zero (REST API)

### Manual testing scenarios
1. Create an attribute (select or multiselect) from the backend (example: attribute_code = brand_number)
2. add new Option to this attribute from the backend (12345)
3. Add new Option to this attribute by the REST API (endpoint : /V1/products/attributes/brand_number/options), json = {"option":{"label":"012345"}}
4. expected result to have two options (12345 and 012345).

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19451) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @SikailoISM. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by VladimirZaets** [comment]
Hi @SikailoISM, please, sign CLA, otherwise, we can't process your pull request.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3592](https://jira.corp.magento.com/browse/ENGCOM-3592) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @SikailoISM. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
