### PR TITLE
Fix #30296 - Wrong ip value in sendfriend_log table

### LINKED ISSUE #30296: Wrong ip value in send friend_log table
**Proconditions:**
* Create a product
* Email to Friend set to "Enabled" in configurations
* Limit Sending By set to "IP address"
* Allow for Guests set to "Yes" (not nessesary but if you don't you have create customer before.)

**Steps To Reproduce:**
* Go to storfront to the product page
* Click on send email to friend icon
* Fill all required fields and click "Send" button
* Check sendfriend_log table

(/) **Expected Result:**
Ip value should be converted to biginteger value

(x) **Actual Result:**
Ip value is not converted properly and it cuted. F.e. If your ip value 127.0.0.1 it will be cutted to 1270.

(!) **Notice:**
It can cause problems with sendFriend IP validation if different customers will have similar IP addresses  

(!) **Issue caused by:**
\Magento\Framework\HTTP\PhpEnvironment\RemoteAddress::getRemoteAddress method does not work corectly. Because if it cahced the value one time it will always return cached value despite input parameter

(!)**Notice:** 
Bug blocked this test \Magento\SendFriend\Model\SendFriendTest::testisExceedLimitByIp please unskip after bug fixing

Note from comments:
{quote}Once issue with 'Magento\Framework\HTTP\PhpEnvironment\RemoteAddress::getRemoteAddress' will be fixed please remove ip2long conversion in \Magento\SendFriend\Model\ResourceModel\SendFriend::addSendItem and make sure this case covered with integration tests{quote}

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This PR fixes incorrect behavior of `Magento\Framework\HTTP\PhpEnvironment\RemoteAddress::getRemoteAddress` method when it's called twice in a row with `true` passed, and removes "hacks" added to sendfriend module because of this issue.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30296

### Manual testing scenarios (*)

Steps to reproduce in issue fixed are not correct.

**Preconditions:**
- Create a product
- Email to Friend set to "Enabled" in configurations
- Limit Sending By set to "IP address"
- Allow for Guests set to "Yes" (not nessesary but if you don't you have create customer before.)

**Steps To Reproduce:**
- Go to storefront to the product page
- Click on send email to friend icon
- Fill all required fields and click "Send" button
- Check sendfriend_log table

**Expected result**
Ip saved in the database should be valid int value.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Bartlomiejsz** [comment]
@magento run all tests

**Comment by rogyar** [comment]
Hi @Bartlomiejsz. Thanks for your work, good job. Could I ask you, to check the failing tests, please, and also make sure that this case is covered by an integration test. Extending the existing integration `testisExceedLimitByIp` should be sufficient. 

Thank you!

**Comment by Bartlomiejsz** [comment]
@magento run all tests

**Comment by Bartlomiejsz** [comment]
@magento run Functional Tests CE

**Comment by Bartlomiejsz** [comment]
@magento run Functional Tests EE

**Comment by Bartlomiejsz** [comment]
Hi @rogyar, failing test is not related to my changes, so this is ready for review now

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8326](https://jira.corp.magento.com/browse/ENGCOM-8326) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
Hello @Bartlomiejsz 

Thank you for your Pull request

I can not reproduce the original issue with the steps provided in the issue:
**Proconditions:**
* Create a product
* Email to Friend set to "Enabled" in configurations
* Limit Sending By set to "IP address"
* Allow for Guests set to "Yes" (not nessesary but if you don't you have create customer before.)

**Steps To Reproduce:**
* Go to storfront to the product page
* Click on send email to friend icon
* Fill all required fields and click "Send" button
* Check sendfriend_log table

(/) **Expected Result:**
Ip value should be converted to biginteger value

(x) **Actual Result:**
Ip value is not converted properly and it cuted. F.e. If your ip value 127.0.0.1 it will be cutted to 1270.

I'm getting the same converted IP `sendfriend_log` table
**Before** applying changes provided in this PR
ip_1

and **After** switching to this PR
ip_2

Can you please correct my steps if I'm processing incorrectly?
 Thank you in advance

**Comment by Bartlomiejsz** [comment]
Hello @engcom-Bravo, funny thing here is that whole issue and steps to reproduce were added here by Magento team from your internal system :) 
I believe steps are not exactly valid, issue that was fixed here was incorrect behavior of `Magento\Framework\HTTP\PhpEnvironment\RemoteAddress::getRemoteAddress` method. Before fix, when this method was called twice time in a row with passed `true` as parameter, it was returning incorrect result second time - first was integer value (as it should when `true` is passed), but second was string with ip.

It's not possible to reproduce issue on Magento instance, because there was some dirty fix added in send friend module - instead of fixing original one, value returned from `getRemoteAddress` method was again passed to `ip2long` method in `getSendCount` and `addSendItem`.

So I believe there are two things that should be verified here:
- `Magento\Framework\HTTP\PhpEnvironment\RemoteAddress::getRemoteAddress` method called twice in a row with `true` passed should return int result (it is covered with a test btw)
- Ip saved from send friend module should still work correctly after all the changes

**Comment by engcom-Bravo** [comment]
@Bartlomiejsz 
Thank you for the quick response.
I've tried to check the issue as described in the comment above _Magento\Framework\HTTP\PhpEnvironment\RemoteAddress::getRemoteAddress method called twice in a row with true passed should return int result_ 

In my case, the method returns false for `ipToLong`, and a string `"127.0.0.1"`. And it is called several times, not twice.
remote_address

In order to proceed correctly, can you please update the PR Description, and provide exact steps?

Thank you in advance

**Comment by Bartlomiejsz** [comment]
Hi @engcom-Bravo, I updated steps to reproduce.
As I mentioned, you can't expect any change in how this ip is saved into database, because there were hacks added - `ip2long` method was called inside sendfriend module.
So you need to verify if after all the changes sendfriend module still works correctly without those hacks.

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

### Manual testing scenario
1. From Admin go to _Stores - Configuration - Catalog -Email to a Friend_ and set the following settings
_Enabled - **Yes**_
_Allow for Guests - **Yes**_
_Limit Sending By - **IP Address**_
2. Save Config and clear Magento cache
3. From Storefront, open any product page and click **Email** button
email_button
4. Fill in all the required fields and click **Send Email**
send email
5. Assert that _"The link to a friend was sent."_ message appears
friend_was_sent
6. Open database table `sendfriend_log`and assert that the IP value is saved as a valid INT value

### Actual result
IP is saved as a valid INT value
Selection_068
Selection_067

**Pull request merged**
