### PR TITLE
Fix issue #4470: import.xsd doesn't allow numbers in vendor name and class name

### LINKED ISSUE #4470: import.xml doesn't allow numbers in vendor name and class name
## Preconditions

1. Magento 2.

## Steps to reproduce
1. Create a simple module with a vendor name which contains at least one number (ex. test123) which creates an import entity
2. etc/import.xml will look something like:

```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_ImportExport:etc/import.xsd">
<entity name="catalog_product" label="Products test" model="test123\somename\Model\Something" behaviorModel="Magento\ImportExport\Model\Source\Import\Behavior\Basic" />
</config>
```
3. Enable module, clear the cache and open the Magento backend Import page

## Expected result
1. It should load the import page

## Actual result
1. The site will die with an error message similar to this:

Invalid XML in file <path_to_website_root>/app/code/test123/somename/etc/import.xml:
Element 'entity', attribute 'model': [facet 'pattern'] The value 'test123\somename\Model\Something' is not accepted by the pattern '[A-Za-z_\\]+'.
Line: 3

Element 'entity', attribute 'model': 'test123\somename\Model\Something' is not a valid value of the atomic type 'modelName'.
Line: 3

The same happens also for export.xml.

### PR DESCRIPTION
**Pull request by nhp**
It was possible to have model definitions that were not parsable
in the xml because it validated the xsd specificatons.
There was no Problem in adding those Models and use them but
not with that .xsd file.

### CODE REVIEW

**Comment by pquerner** [comment]
Probably needs some fixing in test files aswell..?

**Comment by nhp** [comment]
will do that asap. They did not pop up for me because of beeing from 5.6 tests it looks like.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=5420) <br/>All committers have signed the CLA.

**Comment by tkn98** [comment]
I suggest to do the fix similarly to https://github.com/magento/magento2/pull/8307/commits/ced639a616629ffdc682087d7128684f676dacad `<xs:pattern value="[a-zA-Z]+[a-zA-Z0-9\\]+" /` and also to check the other incarnations of this flaw.

We have digits in the vendor name `N98` for Netz98 GmbH and also some of our customers or shops have digits in the vendor name which is perfectly valid so I would consider this blocking.

**Comment by okorshenko** [comment]
@nhp thank you for your contribution. Could you please resolve the conflicts so that I can proceed with PR acceptance if this PR is still relevant.
Thank you

**Comment by okorshenko** [comment]
Closing this PR due to inactivity

**Pull request closed without merging**
