### PR TITLE
Extend importer exception message

### PR DESCRIPTION
**Pull request by orozcodiaz**
Update exception messages to provide more detailed information

### CODE REVIEW

**Review by edenduong — CHANGES_REQUESTED** [review]
Could you please update `.csv` file for translation?

**Comment by orozcodiaz** [comment]
> Could you please update `.csv` file for translation?

done

**Review by edenduong — CHANGES_REQUESTED** [review]
Please add translation for group and store message to .csv file. Thanks.

**Comment by orozcodiaz** [comment]
> Please add translation for group and store message to .csv file. Thanks.

done

**Review by edenduong — CHANGES_REQUESTED** [review]
According to Magento DOD, could you please cover your changes by Automation Test ? Thanks.

**Comment by orozcodiaz** [comment]
> According to Magento DOD, could you please cover your changes by Automation Test ? Thanks.

Unfortunately, I don't have enough experience to do tests

**Comment by lenaorobei** [comment]
Unfortunately we are ton able to accept this PR because of security side of this. We don't want to add any additional info to that is already provided in order to not to increase XSS possibility.

**Pull request closed without merging**
