### PR TITLE
Fixing swatch style issue on product attribute form

### PR DESCRIPTION
**Pull request by DenisSaltanahmedov**
### Description (*)
Styles for the swatch input are broken

### Fixed Issues (if relevant)
1. magento/magento2#20513: Create a new product attribute form. Styles for the swatch input looks broken

### Manual testing scenarios (*)
1. In Admin go to Stores > Attributes > Product > Add New Attribute
2. In "Attribute Properties" > Catalog Input Type for Store Owner > Choose "Text Swatch"
3. In Manage Swatch (Values of Your Attribute) > Add Swatch

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @DenisSaltanahmedov. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20515) <br/>All committers have signed the CLA.

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-20515.instances.magento-community.engineering).
Admin access: [https://pr-20515.instances.magento-community.engineering/admin](https://pr-20515.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-3943](https://jira.corp.magento.com/browse/ENGCOM-3943) has been created to process this Pull Request

**Comment by ghost** [comment]
Hi @DenisSaltanahmedov, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+magento2+20515), it will take less than a minute. </br>Your feedback will help us to improve contribution process.

**Comment by magento-engcom-team** [comment]
Hi @DenisSaltanahmedov. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
