### PR TITLE
save() in customerRepository runs two times when create the customer with subcription

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

 In the CreatePost class, now, it saved 2 times if subscribe = TRUE

```
$customer = $this->accountManagement
                ->createAccount($customer, $password, $redirectUrl);
```
```
            if ($this->getRequest()->getParam('is_subscribed', false)) {
                $extensionAttributes = $customer->getExtensionAttributes();
                $extensionAttributes->setIsSubscribed(true);
                $customer->setExtensionAttributes($extensionAttributes);
                $this->customerRepository->save($customer);
            }
```

**Solution:** We need to save only one time by change the code to :

```
            $extensionAttributes = $customer->getExtensionAttributes();
            $extensionAttributes->setIsSubscribed($this->getRequest()->getParam('is_subscribed', false));
            $customer->setExtensionAttributes($extensionAttributes);

            $customer = $this->accountManagement
                ->createAccount($customer, $password, $redirectUrl);
```

### Manual testing scenarios (*)

Check the save() function in customerRepository should run 1 times instead of run 2 times.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-5530](https://jira.corp.magento.com/browse/ENGCOM-5530) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @edenduong !

I'm not able to reproduce the issue on fresh 2.3-develop following by steps, provided in #23729 .

**Actual Result:**
1. We received two emails (welcome email and the email for confirming their newsletter subscription);
2. After subscription was confirmed, we received the appropriate email.

Maybe I missed something?

@edenduong Could you take a look?

Thanks!

**Comment by edenduong** [comment]
@engcom-Alfa : Thank you for your feedback. Now I can not reproduce. Maybe it is fixed.

But I think the code should optimize like that. Because now it save two times at the same function and it is not good about the performance. 

I will change the description and the title of Pull request. The purpose is we need to save the account of customer only 1 time instead of 2 times.

Thank you !

**Comment by engcom-Alfa** [comment]
Hi @aleron75 ! Could you review again, please?

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-5530](https://jira.corp.magento.com/browse/ENGCOM-5530) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
