### PR TITLE
[Forwardport] Admin Login Form > Aliging Label

### PR DESCRIPTION
**Pull request by mage2pratik**
### Original Pull Request 
https://github.com/magento/magento2/pull/18400

### Description

Aligning the form label used on admin login form.

### Fixed Issues (if relevant)

**before:**

screenshot 2018-10-05 10 20 53

**after:**

screenshot 2018-10-05 10 21 01

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento-engcom-team give me test instance

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-3140](https://jira.corp.magento.com/browse/ENGCOM-3140) has been created to process this Pull Request

**Comment by sidolov** [comment]
Hi @mage2pratik , we cannot reproduce issue on the 2.3-develop.

**Manual testing scenario:**

1. Install Magento 2.3-develop
2. Navigate to admin login page.

**Result**
The form labels are correctly aligned.

**Comment by sidolov** [comment]
Hi @mage2pratik , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
