### PR TITLE
WIP: Return non-secure URL if explicitly requested

### PR DESCRIPTION
**Pull request by Zifius**
### Description

Take _secure => false flag into account before checking if the request is secure

### Fixed Issues

#6175: Unable to generate unsecure URL if current URL is secure

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by miguelbalparda** [comment]
@Zifius is there anything I an do to help here?

**Comment by Zifius** [comment]
@miguelbalparda yeah, got quite busy to be able to continue on it right now. Would you like to connect via Skype and work together?

**Comment by okorshenko** [comment]
Hi @Zifius do you have any progress on that or should we un-assign #6175 from you? Thank you

**Comment by Zifius** [comment]
@okorshenko Please unassign, unfortunately I don't have time atm, I spoke with Miguel though and can offer further help in testing / reviewing

**Comment by okorshenko** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
