### PR TITLE
7399-clickableoverlay-option-doesnot-work

### PR DESCRIPTION
**Pull request by mak0605**
### Description
Fix has been tested  in Magento 2.1, Magento 2.2, Magento 2.3. Also tested in Mobile Device for same.

### Fixed Issues (if relevant)

1. magento/magento2#7399: Clickable Overlay option doesn't work has been fixed

### Manual testing scenarios

1. Make the changes in the file modal.js via PR
2. Perform php bin/magento s:s:d
3. Perform php bin/magento c:f
5. Run script to check

```
require(['jquery','Magento_Ui/js/modal/modal'],` function($, modal) {
   $('<div>Overlay content</div>').modal().modal('openModal');
});
```

6. Now when you click on overlay it will close the modal as default `clickableOverlay` value is `true`.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=13060) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=13060) before we can accept your contribution.<br/>**15** out of **16** committers have signed the CLA.<br/><br/>:white_check_mark: Coderimus<br/>:white_check_mark: vasilii-b<br/>:white_check_mark: miguelbalparda<br/>:white_check_mark: adrian-martinez-interactiv4<br/>:white_check_mark: fooman<br/>:white_check_mark: osrecio<br/>:white_check_mark: vkublytskyi<br/>:white_check_mark: ishakhsuvarov<br/>:white_check_mark: orlangur<br/>:white_check_mark: dverkade<br/>:white_check_mark: robbie-thompson<br/>:white_check_mark: avstudnitz<br/>:white_check_mark: mak0605<br/>:white_check_mark: avoelkl<br/>:white_check_mark: okorshenko<br/>:x: magento-team

**Comment by osrecio** [comment]
Hi @mak0605 , Thanks for your contribution,

Can you squash your commit for has only one?. I'm working on this PR for to be processed.

**Comment by mak0605** [comment]
Hi @osrecio can you please cancel this pull request, as i have done something wrong that's why other commits are also listed here.
I can generate a new pull request with my changes only.

**Comment by osrecio** [comment]
Hi @mak0605. I close this PR. 

Create new one with your changes. When you add new PR ping me and I will assign it to me.
tip: You should create a new branch from `2.2-develop` and add your commits.

**Comment by mak0605** [comment]
Hi @Oscar,

Thanks for your help, i'll add a new PR in new branch and will mail you for
same.

**Pull request closed without merging**
