### PR TITLE
[BUGFIX] Flat Category reindexList of AllChildren if the url_key of t…

### PR DESCRIPTION
**Pull request by lewisvoncken**
When Flat Category is enabled and you change the url_key of a category which has children the url_paths of the children won't be updated.

This can be reproduced by following these steps:

**1.** Enable Flat Catalog Category 
Stores > Settings > Configuration > Catalog  > Catalog > Storefront > Use Flat Catalog Category
**2.** Reindex through the console 
bin/magento indexer:reindex
**3.** Open the flat table which is generated after the first reindex of Flat Catalog Category
**4.** Search for an example category which has children
In the example data _Women_ category with ID 20 .  
**5.** List the url_paths of the sub children
`SELECT url_path, path FROM catalog_category_flat_store_1 WHERE path LIKE '%20%'`
**6.** Open the example category in the Magento Admin Panel
**7.** Change the Url Key of the category and Save the category
**8.** Check the database again and you will see the following result

image

But the children should also be updated, after the fix the result will be like this:

image

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=10557) <br/>All committers have signed the CLA.

**Comment by ishakhsuvarov** [comment]
Hi @lewisvoncken 
Thank you for the Pull Request. Please sign the CLA so that we could proceed with the processing.

**Comment by ishakhsuvarov** [comment]
@lewisvoncken I assume `develop` branch may also be affected by this issue. Do you plan to implement it for up-to-date version as well? Would you like to cover changes with some kind of tests?

**Comment by vkublytskyi** [comment]
@ishakhsuvarov PR to develop branch was created as magento-partners/magento2ce#7

**Comment by okorshenko** [comment]
waiting for develop branch PR. Once it is merged, we will proceed with this PR

**Comment by lewisvoncken** [comment]
@vkublytskyi updated this pull request according to the feedback on the develop branch pr

**Pull request merged**
