### PR TITLE
Update Readme file for magento2 repository

### PR DESCRIPTION
**Pull request by sidolov**
Port for: https://github.com/magento/magento2/pull/14790
### Description
Updated readme.md
- Added Maintainers section 
- Added Contributors section 
- Changed links to documentation

### Fixed Issues (if relevant)
none

### Manual testing scenarios
none

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by okorshenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, thank you for the review.
[ENGCOM-1350](https://jira.corp.magento.com/browse/ENGCOM-1350) has been created to process this Pull Request

**Comment by didactic-umbrella** [comment]
@magento-engcom-team give me test instance

**Comment by didactic-umbrella** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella, here is your [Magento instance](http://i-14787-2-3-develop.engcom.dev.magento.com).
Admin access: [http://i-14787-2-3-develop.engcom.dev.magento.com/admin](http://i-14787-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by didactic-umbrella** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella, here is your [Magento instance](http://i-14787-2-2-develop.engcom.dev.magento.com).
Admin access: [http://i-14787-2-2-develop.engcom.dev.magento.com/admin](http://i-14787-2-2-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by didactic-umbrella** [comment]
@magento-engcom-team give me new test instance

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella, here is your [new Magento instance](http://pr-14787.engcom.dev.magento.com).
Admin access: [http://pr-14787.engcom.dev.magento.com/admin](http://pr-14787.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`

**Comment by didactic-umbrella** [comment]
@magento-engcom-team give me new test instance

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella, here is your [new Magento instance](http://pr-14787.engcom.dev.magento.com).
Admin access: [http://pr-14787.engcom.dev.magento.com/admin](http://pr-14787.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Please make sure you are PR author or assignee to access the instance.

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by didactic-umbrella** [comment]
@magento-engcom-team give me new test instance

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella, here is your [new Magento instance](http://pr-14787.engcom.dev.magento.com).
Admin access: [http://pr-14787.engcom.dev.magento.com/admin](http://pr-14787.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Please make sure you are PR author or assignee to access the instance.

**Comment by didactic-umbrella** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by didactic-umbrella** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by didactic-umbrella** [comment]
@magento-engcom-team give me new test instance

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella, here is your [new Magento instance](http://pr-14787.engcom.dev.magento.com).
Admin access: [http://pr-14787.engcom.dev.magento.com/admin](http://pr-14787.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Please make sure you are PR author or assignee to access the instance.

**Comment by didactic-umbrella** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella, here is your [Magento instance](http://i-14787-2-3-develop.engcom.dev.magento.com).
Admin access: [http://i-14787-2-3-develop.engcom.dev.magento.com/admin](http://i-14787-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by didactic-umbrella** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella, here is your [Magento instance](http://i-14787-2-2-develop.engcom.dev.magento.com).
Admin access: [http://i-14787-2-2-develop.engcom.dev.magento.com/admin](http://i-14787-2-2-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by didactic-umbrella** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @didactic-umbrella, here is your [Magento instance](http://i-14787-2-3-develop.engcom.dev.magento.com).
Admin access: [http://i-14787-2-3-develop.engcom.dev.magento.com/admin](http://i-14787-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by okorshenko** [comment]
@magento-engcom-team give me 2.2.3 instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.2.3 instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [Magento instance](http://i-14787-2-2-3.engcom.dev.magento.com).
Admin access: [http://i-14787-2-2-3.engcom.dev.magento.com/admin](http://i-14787-2-2-3.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
Hi @sidolov. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.3.0 release.

**Pull request merged**
