### PR TITLE
Fix language in cookie_status.phtml

### LINKED ISSUE #34524: [Issue] Fix language in cookie_status.phtml
This issue is automatically created based on existing pull request: magento/magento2#33742: Fix language in cookie_status.phtml

---------
The cookie disabled message contains a poorly-worded sentence. This is a suggested fix to the sentence. Dropped "in the case".

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by sean-breeden**
The cookie disabled message contains a poorly-worded sentence. This is a suggested fix to the sentence. Dropped "in the case".

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#34524: Fix language in cookie_status.phtml

### CODE REVIEW

**Review by nuzil — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-9179](https://jira.corp.magento.com/browse/ENGCOM-9179) has been created to process this Pull Request

**Review by ptylek — APPROVED** [review]

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9179](https://jira.corp.magento.com/browse/ENGCOM-9179) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by andrewbess** [comment]
This PR has already been merged

**Pull request merged**
