### PR TITLE
PageCache / Layout: Avoid multiple calls and config fetch

### LINKED ISSUE #29159: [Issue] PageCache / Layout: Avoid multiple calls and config fetch
This issue is automatically created based on existing pull request: magento/magento2#28992: PageCache / Layout: Avoid multiple calls and config fetch

---------
### Description (*)
Reduce the number of calls to Cache config.

### Expected behavior (*)
Should not be changed after fix

### Benefits
Reduce the number of calls to Cache config.

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Reduce the number of calls to Cache config.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29159: PageCache / Layout: Avoid multiple calls and config fetch

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7780](https://jira.corp.magento.com/browse/ENGCOM-7780) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked pages are loaded without errors and number of calls to Cache config was reduced (execution time from `0.051918983459473` to `0.044523000717163`) on catefory page
**Before:**
#28992Main

**After**
#28992PRtime

**Comment by ihor-sviziev** [comment]
@engcom-Delta wow. Quite significant diff!

**Comment by VladimirZaets** [comment]
@magento create issue

**Pull request merged**
