### PR TITLE
fixed issue #23024

### PR DESCRIPTION
**Pull request by Shubham0492**
### Description (*)

If grid action column position change then multi action box not align with action.

### Fixed Issues (if relevant)

1. #23024 : Grid Action Column Design Issues

### Manual testing scenarios (*)

1 . Open any Grid that action column has more than one action like CMS Block grid.
2. Programmatically change the position of an action column.
3. Comment updated_time column flush cache and reload grid.
4. Now remove comment and flush cache and reload the grid. now action column will at second last position. https://prnt.sc/ntyan7
5. Now select action, you will see the column popup always at last position. But after updating it will display with action column.

https://prnt.sc/ntybge

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @Shubham-Webkul, please, sign CLA, otherwise, we can't process your pull request

**Comment by Shubham0492** [comment]
Due to Adobe CLA Signed

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-6048](https://jira.corp.magento.com/browse/ENGCOM-6048) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @Shubham-Webkul !

During testing, we faced the issue

**_Problem:_** Column popup goes beyond the grid

**Steps to reproduce:**
1. Programmatically change the position of an action column (CMS page grid);
2. Log in to Admin;
3. Go to Content->Elements->Pages;
4. You should have about 15 pages in the grid;
5. In Action column click on "select" dropdown menu;
6. Scroll down the page;

**Actual Result:**
problem

@Shubham-Webkul Could you take a look?

Thanks!

**Comment by Shubham0492** [comment]
@VladimirZaets  Please let me know if there is any changes needed.

**Comment by dmytro-ch** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-24914.instances.magento-community.engineering).
Admin access: [https://pr-24914.instances.magento-community.engineering/admin](https://pr-24914.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hi @Shubham-Webkul, changing the positioning property for the wrapper leads to incorrect behavior.
The opened dropdown should not affect the block's height.

**Expected Result**
Screen Recording 2019-10-17 at 12 26 11

**Actual Result**
Screen Recording 2019-10-17 at 12 25 23

Thank you!

**Comment by Shubham0492** [comment]
@dmytro-ch I have fixed positioning property for the wrapper leads. Please check

**Comment by dmytro-ch** [comment]
Hi @Shubham-Webkul, please note, the functional test failures caused by the changes provided in this PR. Most of the issues are relevant to the child product grid of configurable product edit form.

**Comment by dmytro-ch** [comment]
Hi @Shubham-Webkul, I'm closing this PR now due to inactivity.
Feel free to reopen and update if you wish to continue.
Thank you!

**Pull request closed without merging**
