### PR TITLE
24152 : fixed spacing issue

### PR DESCRIPTION
**Pull request by sunilit42**
Fix issue:- #24152

### CODE REVIEW

**Comment by kalpmehta** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, here is your [Magento instance](https://i-24159-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24159-2-3-develop.instances.magento-community.engineering/admin](https://i-24159-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by kalpmehta — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, thank you for the review.
[ENGCOM-5654](https://jira.corp.magento.com/browse/ENGCOM-5654) has been created to process this Pull Request
:eight_spoked_asterisk: @kalpmehta, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by kalpmehta** [comment]
Thanks @sunilit42 for the contribution.

This PR removes margin left on some admin screens as it is not consistent. 
@sidolov Can you please check if extra margin is required or it's ok to remove as there is already a padding? Thanks!

**Comment by engcom-Foxtrot** [comment]
Hello, @sunilit42. Thank you for your contribution.
Unfortunately, we cannot accept your PR. We should not remove the left margin for support text. Instead of it, we need to add such margin for cases we don't have it (for UI component grids).

**Comment by sunilit42** [comment]
Hello @engcom-Foxtrot 
can you please give one example where it will use? so i can do css based on that

**Comment by sunilit42** [comment]
@engcom-Foxtrot  any update here?

**Comment by engcom-Foxtrot** [comment]
@sunilit42 please see magento/magento2#24359

**Pull request closed without merging**
