### PR TITLE
Added table install to Magento Test Framework sequence builder

### PR DESCRIPTION
**Pull request by ldusan84**
Currently the Test Framework's sequence builder class doesn't install the sequence tables and the regular one does. 

I think that these tables should be created so that orders can be made on different stores in integration tests.

### CODE REVIEW

**Comment by daim2k5** [comment]
Thank you for the PR! We are currently waiting for the travis builds to work again, which should happen in a few days. Once that is running and the tests are green we can continue to process your contribution.

**Comment by mazhalai** [comment]
@ldusan84 Please sync with develop and rerun builds.

**Comment by ldusan84** [comment]
@mazhalai done.

**Comment by okorshenko** [comment]
Internal ticket: MAGETWO-52761

**Comment by okorshenko** [comment]
@ldusan84 thank you for your contribution.  Could you please let me know what particular tables are missed? I tested the issue on my local with latest code from develop branch. It works as expected. Could you please provide steps to reproduce? Thank you

**Pull request closed without merging**
