### PR TITLE
[Backport] Fixed-checkout-tooltip-dropdown

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Description (*)
Original PR: https://github.com/magento/magento2/pull/20488

### Fixed Issues (if relevant)

1. magento/magento2#20488: On checkout page tooltip dropdown 
2. Magento 2.2.x

### Manual testing scenarios (*)

1. Add product to cart
2. On checkout page click on "question mark" icon besides Email Address field
3. Tooltip dropdown opens, pointer not points to icon

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by amol2jcommerce** [comment]
Hi @rogyar ,

Our pull request for 2.2-develop branch same changes are present in the 2.3-develop & pull request is #20488

**Comment by rogyar** [comment]
Hi @amol2jcommerce. We need to wait until the original PR is merged to 2.3-develop branch. The original PR is still in review.

**Comment by amol2jcommerce** [comment]
Hi @rogyar @magento-engcom-team please review.

**Comment by amol2jcommerce** [comment]
@magento-engcom-team please review.

**Comment by amol2jcommerce** [comment]
@magento-engcom-team please review

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4133](https://jira.corp.magento.com/browse/ENGCOM-4133) has been created to process this Pull Request

**Pull request merged**
