### PR TITLE
Change HTTP Endpoint according to the USPS future release

### PR DESCRIPTION
**Pull request by EvheniiaKolkhiieva**
### Description (*)

Effective June 24th, 2021, USPS Web Tools will remove support for all unsecure HTTP endpoints.
Gateway URL in Magento setting should change to https. 

This PR changes the link in the Gateway URL field from `http://production.shippingapis.com/ShippingAPI.dll` to `https://production.shippingapis.com/ShippingAPI.dll`

*Proof Link:* https://www.usps.com/business/web-tools-apis/2021-web-tools-release-notes.pdf

image

### Manual testing scenarios (*)

1. Login into Magento Admin
2. On the Admin sidebar, go to Stores > Settings > Configuration.
3. In the left panel, expand Sales and choose Delivery Methods.
4. Expand Expansion selector the USPS section.
5. Pay attention to the **Gateway URL**

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by EvheniiaKolkhiieva** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9070](https://jira.corp.magento.com/browse/ENGCOM-9070) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@gabrieldagama @sivaschenko, I think this PR should have priority P1

**Comment by sdzhepa** [comment]
@EvheniiaKolkhiieva @ihor-sviziev 
cc: @gabrieldagama

Thank you for raising this issue! It looks like really critical 

I am not sure but looks like after such changes Magento will have by default 2 fields with the same URL inside
- Gateway URL = http://production.shippingapis.com//ShippingApi.dll
- Secure Gateway URL = http://production.shippingapis.com//ShippingApi.dll

Please let me know if I missed something. 

**IMHO:** 
- 2 different fields with the same data(url). It looks like not the best user experience. It could confuse users. 
- Taking into account expected changes, probably Magento no need anymore Unsecure HTTP Endpoint _Gateway URL_ field at all

**Next steps:**
- we will discuss and review this issue at the next public triage meeting
- and I assume we will need Product Manager approval before merging this PR

**Review by Den4ik — APPROVED** [review]

**Comment by Den4ik** [comment]
@magento run WebAPI Tests, Integration Tests, Functional Tests

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9070](https://jira.corp.magento.com/browse/ENGCOM-9070) has been created to process this Pull Request

**Comment by gabrieldagama** [comment]
We discussed this at Public Triage meeting and it was decided to accept this PR, in the future we need to look at removing one of the two URLs available on configuration.

**Comment by EvheniiaKolkhiieva** [comment]
@magento run Functional Tests B2B

**Comment by dmitriyprime** [comment]
:heavy_check_mark: QA passed

**Comment by ihor-sviziev** [comment]
@sivaschenko @sidolov @gabrieldagama why this PR isn't getting merged?

**Pull request merged**
