### PR TITLE
Removed unused session class from wishlist controller 2.3

### PR DESCRIPTION
**Pull request by mageprince**
Removed unused session class

### Description

The class `use Magento\Customer\Model\Session` is not being used, so its declaration is not necessary
### Fixed Issues (if relevant)

use Magento\Customer\Model\Session;
### Manual testing scenarios

N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mageprince. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by miguelbalparda** [comment]
We are trying to have the PRs first merged in 2.2, can you open this very same PR against that branch please? Thanks.

**Comment by mageprince** [comment]
Hi @miguelbalparda I have created new PR for 2.2 develop please check https://github.com/magento/magento2/pull/16967

**Comment by miguelbalparda** [comment]
Closing this one per https://github.com/magento/magento2/pull/16967#issuecomment-406822822

**Pull request closed without merging**
