### PR TITLE
Cleanup Mage bootstrap dependencies

### PR DESCRIPTION
**Pull request by krzksz**
### Description (*)
This PR is a part of my effort to improve Magento 2 frontend performance.

In this PR I'm cleaning-up both `common` and `dataPost` modules and moving them from `deps` to normal dependencies so it is possible to create mixins for them. I'm also moving some of the dependencies from top-level definition to the moment when they are actually needed so we are not loading and waiting for redundant files.

### Manual testing scenarios (*)

1. Links with `data-post` are still submitted properly (e.g. add to wishlist links).
2. I'm not sure how to test `mage/common`, but I'll try to check when it is applied.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @krzksz,
I see to many test failures, looks like your solution breaks some functionality. Please review test results and update your solution / or tests itself.

**Comment by ihor-sviziev** [comment]
Hi @krzksz,
Will you be able to update your PR?

**Comment by krzksz** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@krzksz  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
