### PR TITLE
[Backport] Fix Broken Tax Rate Search Filter Admin grid #21521

### PR DESCRIPTION
**Pull request by tuyennn**
### Description (*)

Inside Tax Rate admin, while search criteria with main table `tax_calculation_rule` **code** and `tax_calculation_rate` **code** will caused where clause is ambiguous

### Fixed Issues (if relevant)

1. [magento/magento2#21521](https://github.com/magento/magento2/issues/21521):  Broken Tax Rate Search Filter - SQLSTATE[23000] #21521 

### Manual testing scenarios (*)

1.  Go to Admin -> Stores -> Taxes -> Tax Rules

2. Add a tax rule

3. Search tax rule using both **Name** and **Tax Rate** fields
  eg. _Name = Alabama_ & _Tax Rate = US-AL_

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

Backport for: https://github.com/magento/magento2/pull/21701

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21535) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @tuyennn. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by tuyennn** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @tuyennn. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @tuyennn, here is your [new Magento instance](https://pr-21535.instances.magento-community.engineering).
Admin access: [https://pr-21535.instances.magento-community.engineering/admin](https://pr-21535.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by tuyennn** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @tuyennn. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @tuyennn, here is your [Magento instance](https://i-21535-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21535-2-2-develop.instances.magento-community.engineering/admin](https://i-21535-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-4434](https://jira.corp.magento.com/browse/ENGCOM-4434) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@tuyennn thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VasylShvorak** [comment]
✔️ QA passed

**Review by sidolov — CHANGES_REQUESTED** [review]
Hi @tuyennn , in order to keep consistency between versions we accepting pull requests to 2.3-develop first. Please, create pull request with the same changes to 2.3-develop

**Comment by tuyennn** [comment]
@sidolov New pull request base on 2.3-develop was created here #21701

**Comment by tuyennn** [comment]
Duplicate #21758

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-4434](https://jira.corp.magento.com/browse/ENGCOM-4434) has been created to process this Pull Request

**Pull request merged**
