### PR TITLE
Fix incorrect DHL Product codes

### PR DESCRIPTION
**Pull request by gwharton**
There are three DHL product codes in the DHL Shipping module that are incorrect. 

### Description
Product Code "1" changed from "Customer Services" to "Domestic express 12:00"
Product Code "I" changed from "Break bulk economy" to "Domestic express 9:00"
Product Code "O" changed from "Others" to "Domestic express 10:30"

DHL product codes are now inline with those published in latest DHL products and services guide.

See [DHLIS1 - Products and Services](http://www.dhl.co.uk/content/dam/downloads/uk/Express/PDFs/developer_centre/dhlis1_products_and_services.pdf)

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios
N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by sidolov** [comment]
Hi @gwharton , in provided link to documentation I found records for: 
I => 'Domestic express 9:00'
1 => 'Domestic express 12:00'

but I can't find information about: 
O =>Domestic express 10:30'
in document code 'O' matching with 'Express 09:00'

Please, help me understand why record with code 'O' has changed.

**Comment by gwharton** [comment]
@sidolov Yes, you are quite correct. I missed the fact that the product code "O" is not listed in the documents. I have reverted the change to product code "O", as certainly in the UK, there is no such service "Domestic Express 10:30"

I had incorrectly found the change to the "O" product code in the code base for another shopping cart application and copied it over into this update. My mistake. Perhaps in the US, where there may be a domestic express 10:30 service, that code "O" is indeed used, but I can't find any evidence for it in the docs.

I have double checked my test data from the DHL test environment and product codes "1" and "I" are both being returned from DHL with the correct updated product description, as per this PR. No product with code "O" is present in any returns.

**Comment by sidolov** [comment]
@gwharton thanks for quick response!

**Comment by sidolov** [comment]
Changes covered with unit test

**Comment by gwharton** [comment]
Thanks all for a speedy merge. 

@sidolov I'm not sure on what process to follow to get this backported into 2.3-develop aswell. Is that a process where the same commits can be merged into the different branch through some automated process, or do I need to branch 2.3-develop and manually make the same changes again and generate another PR.

**Pull request merged**
