### PR TITLE
Align configurable product options to select while creating new order from admin area

### PR DESCRIPTION
**Pull request by vasilii-b**
### Description (*)
Fixes field misalignment issue for product options while adding a configurable product to the order from admin area.

### Fixed Issues (if relevant)
1. magento/magento2#20521

### Manual testing scenarios (*)
Reported in issue description 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @vasilii-b. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-20523.instances.magento-community.engineering).
Admin access: [https://pr-20523.instances.magento-community.engineering/admin](https://pr-20523.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-3944](https://jira.corp.magento.com/browse/ENGCOM-3944) has been created to process this Pull Request

**Comment by amol2jcommerce** [comment]
@vasilii-b This issue pull request is already created #19380

**Comment by vasilii-b** [comment]
Hey @amol2jcommerce , why do you close this PR if the mentioned one by you is closed as well and there is no activity for some time ? 🤔

**Comment by rogyar** [comment]
@amol2jcommerce, please do not close pull requests. Especially approved by maintainers.

**Comment by VladimirZaets** [comment]
Hi @vasilii-b. Please resolve merge conflict. Thanks.

**Comment by vasilii-b** [comment]
Thank you @VladimirZaets, I've solved conflicts, but it turns out that this issue was fixed already in some other PR merged recently. https://github.com/magento/magento2/commit/7495afbc8c78e9a27292a5f358a243363b9c6050
That's sad a little. But thank you! :)

**Comment by vasilii-b** [comment]
The PR https://github.com/magento/magento2/pull/20558 that solved was created 20 days ago, mine 21 days ago. Is some priority taken into account, or?

**Comment by VladimirZaets** [comment]
Hi @vasilii-b. Sorry, it's our mistake, usually, if we have two PRs that resolve the same issue we merge PR that was created early.

**Pull request closed without merging**
