### PR TITLE
Issue #35133 prevent DeleteObseleteRewrites function to pass empty array values in  variable and create Mysql syntax errors

### PR DESCRIPTION
**Pull request by neddy236**
### Description (*)
Issue is found on app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php line:107

if ((int)$product->getVisibility() === Visibility::VISIBILITY_NOT_VISIBLE) { $isGlobalScope = $product->getStoreId() == Store::DEFAULT_STORE_ID; $storesToRemove[] = $isGlobalScope ? $product->getStoreIds() : $product->getStoreId(); }

basicly $storesToRemove has this value with every website removed with my tests Array ( [0] => 1 [1] => 2 [2] => 3 [3] => 4 [4] => Array ( ) )

Also I don't find anypoint of assigning default store view id which is 0 to the array (which by the way works fine) because url_rewrites do not get generated in store_id 0

Simple proposal is to array_filter the $storesToRemove variable on itself to remove any possible empty values from the array as they are not needed

Sql query result AFTER proposed fix.

'SELECT url_rewrite.* FROM url_rewrite WHERE (entity_id IN ('1')) AND (entity_type IN ('product')) AND (store_id IN ('1', '2', '3', '4'))'

Sql query result BEFORE proposed fix.

'SELECT url_rewrite.* FROM url_rewrite WHERE (entity_id IN ('1')) AND (entity_type IN ('product')) AND (store_id IN ('1', '2', '3', '4', ))'

### Related Pull Requests
-

### Fixed Issues (if relevant)
1. Fixes magento/magento2#[35133]

### Manual testing scenarios (*)
1. Created 4 Websites with stores and stores views.
2. Added simple product as described in issue #35133 
3. Manually added value 0 in $storesToRemove and checked for behaviour
4. After nothing happended because url_rewrites do not store urls in store_id 0 I tried removing some stores and everything worked correctly
5. Created a simple product that was visible in catalog,search and assigned it to all websites
6. Removed it from website 3 and 4 while in all store views and noticed url_rewrites were removed as expected
7. Re-added and url_rewrites were created as expected
8. Removed it from all websites and all url rewrites associated with that product were removed.

### Questions or comments
-

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by neddy236** [comment]
@magento give me test instance

**Comment by neddy236** [comment]
https://github.com/magento give me test instance

**Comment by neddy236** [comment]
@magento give me test instance

**Comment by neddy236** [comment]
@magento give me test instance

**Comment by neddy236** [comment]
@magento run all tests

**Comment by neddy236** [comment]
@magento run Functional Tests CE Functional Tests B2B Integration Tests Static Tests

**Comment by neddy236** [comment]
https://github.com/magento run Functional Tests CE,Functional Tests B2B,Integration Tests,Static Tests

**Comment by neddy236** [comment]
@magento run Functional Tests CE,Functional Tests B2B,Integration Tests,Static Tests

**Comment by neddy236** [comment]
@magento run all tests

**Comment by neddy236** [comment]
@magento run all tests

**Comment by hostep** [comment]
Looks like this got fixed by Magento core devs in:
- https://github.com/magento/magento2/commit/288beb34f55d292da00768406931f404144f92f0
- https://github.com/magento/magento2/commit/fdd2518bc68283f56557fbfcbf06f07dd8f01acb

**Comment by neddy236** [comment]
@hostep thanks for the info on the issue. I think this pull request can get Closed since it's already taken care of. Hope to see it on 2.4.5. Will leave it on until next release and validate if its fixed.

**Comment by hostep** [comment]
@neddy236: yes it can be closed. Could you do that yourself? I don't have the power to do this. Thanks 🙂

**Comment by neddy236** [comment]
Closing this PR since it has been fixed by Magento team

**Pull request closed without merging**
