### PR TITLE
Graphql Playground support added

### PR DESCRIPTION
**Pull request by dani97**
Graphql Playground integration with magento 2.
Accessible in default mode and developer mode.
### Description (*)

    Graphql Playground integration with magento 2.
    Created a route with id graphql.
    Accessible in default mode and developer mode as {BASE_URL/graphql} in modern browsers.
    Removed all default magento styles from the page.
    Implemented as independent module like swagger so can be removed or disabled in production.

### Fixed Issues (if relevant)

https://github.com/magento/graphql-ce/issues/783

### Manual testing scenarios (*)

    In developer or default mode access {BASE_URL}/graphql

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)
https://github.com/magento/graphql-ce/pull/992 - Original Pull Request

### CODE REVIEW

**Review by lenaorobei — COMMENTED** [review]
Hi @dani97. We had an internal discussion regarding this PR and creating new application is not an option. Code duplication will lead to improper behaviour in future and will cause the lack of extensibility. Could you please use existing application and `GraphQL` area. And then in controller emulate `frontend`, see `Magento\Framework\App\State::emulateAreaCode`.

**Comment by dani97** [comment]
@lenaorobei  I will change the implementation 👍 .

**Comment by VladimirZaets** [comment]
@dani97 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Comment by hnsr** [comment]
If anyone is still looking for an embedded GraphQL IDE, I have created a small (freely available) module that embeds Apollo Sandbox IDE under {{base_url}}/graphql-sandbox: https://github.com/ho-nl/magento2-ReachDigital_ApolloSandbox

Screenshot 2023-09-04 at 13 43 04

**Pull request closed without merging**
