### PR TITLE
Implement ActionInterface for UI/Index

### LINKED ISSUE #29594: [Issue] Implement ActionInterface for UI/Index
This issue is automatically created based on existing pull request: magento/magento2#27498: Implement ActionInterface for UI/Index

---------

### Description (*)

This is a part of the process of introducing implementations of `ActionInterface`.

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by dxx004**
### Description (*)

This is a part of the process of introducing implementations of `ActionInterface`.

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29594: Implement ActionInterface for UI/Index

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @dxx004. Please, take a look at the failing tests

**Comment by dxx004** [comment]
@magento run all tests

**Comment by dxx004** [comment]
@magento run all tests

**Comment by dxx004** [comment]
@magento run all tests

**Comment by dxx004** [comment]
@magento run all tests

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7797](https://jira.corp.magento.com/browse/ENGCOM-7797) has been created to process this Pull Request

**Comment by sidolov** [comment]
@magento create issue

**Comment by engcom-Delta** [comment]
**Note:** Dev experience needed to test PR changes

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by rogyar** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Review by rogyar — APPROVED** [review]
The code looks good for me. The randomly failing tests don't seem to be related to the current change

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7797](https://jira.corp.magento.com/browse/ENGCOM-7797) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Dev experience is required for testing this PR. Please note that Manual testing has not been performed.

**Comment by engcom-Charlie** [comment]
:heavy_check_mark: QA Passed

**Actual Result**
Сustom frontend UI grid and all grid filters work as before.

**Comment by engcom-November** [comment]
@dxx004, please resolve the conflicts so we can move ahead with this pr.

**Pull request closed without merging**
