### PR TITLE
Prevent Varnish from creating cache variations of static files

### PR DESCRIPTION
**Pull request by PHOENIX-MEDIA**
In the vcl_hash routine cookie values are read to create cache variations of the same URL which makes only sense for HTML pages. Static files will never change and therefore shouldn't be stored in variations.
The VCL change removes schema and cookies for static files before calling vcl_hash to ensure only one cache element is created.

### CODE REVIEW

**Comment by kokoc** [comment]
@PHOENIX-MEDIA Thank you for contribution.
Seems like pull request is based on Magento 1 code base, that has different directory structure for static resources. Could you please fix it and also add woff and svg files to the list?

Related issue - #721

**Comment by PHOENIX-MEDIA** [comment]
Right, I've fixed the file path for /pub/.

**Comment by kurtinge** [comment]
Shouldn't the regexp be something like this ?
```
if (req.url ~ "^/(pub/)?(media|static)/.*\.(png|jpg|jpeg|gif|css|js|swf|ico|woff|svg)$") {
```
To allow that the pub directory can be your docroot ?

**Comment by kokoc** [comment]
@kurtinge Yes, regexp looks great.

**Comment by kokoc** [comment]
@PHOENIX-MEDIA Regexp without "media" and "static" parts can possibly lead to session loss on 404's pages. See #721 for details

**Comment by PHOENIX-MEDIA** [comment]
@kurtinge thanks for heads up!
Updated RegEx. Of course cookie must only be removed to static files.

**Comment by kokoc** [comment]
:white_check_mark: CR: passed
:white_check_mark: Builds: green
:white_check_mark: Resolution: ready to merge
:white_check_mark: Internal reference: MAGETWO-32938

**Pull request merged**
