### PR TITLE
Add ReadFactory and WriteFactory to Magento's public API

### PR DESCRIPTION
**Pull request by navarr**
### Description

These classes are necessary/useful for creating instances of
ReadInterface and WriteInterface using the public API.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @navarr. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by navarr** [comment]
@slavvka Hi - why is this PR on hold?  Is there anything I can do to move it along?

**Comment by slavvka** [comment]
@navarr because it should be delivered to 2.3 release and 2.3-develop isn't a release branch anymore. I am going to deliver it there together with #17296 where I asked you to make changes according to our decision.

**Review by slavvka — APPROVED** [review]
@navarr thank you for your valuable contribution! Your changes was cherry-picked and delivered to 2.3.0 release branch. This PR is also accepted and will be delivered to 2.3.1 release

**Comment by magento-engcom-team** [comment]
Hi @slavvka, thank you for the review.
[ENGCOM-3222](https://jira.corp.magento.com/browse/ENGCOM-3222) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @navarr. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
