### PR TITLE
Fix Wrong ratings at second Catalog Product List at cms page widget #33867

### LINKED ISSUE #33867: Wrong ratings at second Catalog Product List
### Preconditions (*)

1.Magento 2.4.3
 

### Steps to reproduce (*)

1.Insert two Catalog Product List on homepage.

### Expected result (*)

1.The product ratings should be correct at second Catalog Product List.

### Actual result (*)

1.
2.The product ratings display incorrect at second Catalog Product List.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Kannakiraj123**
### Description (*)
1.In review phtml use "queryselector".its pointing first element only.Thats why this issue happened.
2.I changed "queryselector" to "queryselectorAll" .its pointing to all element of each product.So at second catalog list have same data like first catalog list

### Related Pull Requests
Fixed Wrong ratings at second Catalog Product List at cms page widget

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33867

### CODE REVIEW

**Comment by Kannakiraj123** [comment]
@magento give me test instance

**Comment by Kannakiraj123** [comment]
@magento give me test instance

**Comment by Kannakiraj123** [comment]
@magento give me test instance

**Comment by Kannakiraj123** [comment]
> Hi @Kannakiraj123, here is your Magento Instance: https://28f4bec5bce4f03ef7bbdbf9c4f479dc.instances.magento-community.engineering
> Admin access: https://28f4bec5bce4f03ef7bbdbf9c4f479dc.instances.magento-community.engineering/admin_5fe1
> Login: 72486a9a
> Password: e9c7f13e873f

hi,This is not correctly fixed.I updated another one commit.@magento give me test instance

**Comment by bgorski** [comment]
@Kannakiraj123 thank you for the contribution! In the meantime, can you sign the Adobe Contributor License Agreement? You can find it here: https://opensource.adobe.com/cla.html
It's the necessary 1st step to process your pull request.

**Comment by Kannakiraj123** [comment]
@bgorski I signed.but it's not updated here

**Comment by Kannakiraj123** [comment]
@magento run all tests

**Comment by Kannakiraj123** [comment]
@magento give me test instance

**Comment by Kannakiraj123** [comment]
@magento run Functional Tests EE

**Comment by vpodorozh** [comment]
@magento give me test instance

**Comment by vpodorozh** [comment]
@magento give me 2.4.1 instance

**Comment by bgorski** [comment]
@magento give me test instance

**Comment by bgorski** [comment]
@magento run Adobe CLA Signed?

**Comment by bgorski** [comment]
Looks like this is working now and the code looks good as well. In order to make the CLA check run again I need to close and reopen the PR and then I can approve it. 
As for functional tests that fail, none of them seems to be failing because if this PR.

**Comment by bgorski** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Review by bgorski — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @bgorski, thank you for the review.
[ENGCOM-9196](https://jira.corp.magento.com/browse/ENGCOM-9196) has been created to process this Pull Request
:eight_spoked_asterisk: @bgorski, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by Kannakiraj123** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests CE

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests EE

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed - Automation jobs failing!

**Preconditions:**

1. Have a fresh Magento Instance with sample data installed.


**Manual testing scenario:**

1. Navigate to Admin > Content > Blocks > Home Page Block - edit.

2. Add a new Widget exactly same as already existing hot sellers titled widget (as shown in below screenshot)
   image

3. Open the Home page in the front end and check the products ratings

**Before:** :heavy_multiplication_x: Same product's ratings were different in each blocks
   image


**After:** :heavy_check_mark:  Same product's ratings are retained same in each blocks
   image


Additionally the automation jobs are getting failed continuously in this PR, and hence moving it to _Extended Testing_

**Comment by bgorski** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by bgorski** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by bgorski** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B, Functional Tests CE, 
Functional Tests EE

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by engcom-Lima** [comment]
Hi @Kannakiraj123, thanks for your contribution!
Seems like the failures in the build are not due to the changes in this PR hence moving it ahead.
Thanks!

**Comment by sidolov** [comment]
@engcom-Lima functional tests are permanently failed, I'm moving PR to extended testing. Failures are related to the changes and should be addressed

**Comment by engcom-Lima** [comment]
Will look into the build failures and work accordingly
Thanks!

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B, WebAPI Tests

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B, WebAPI Tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Pull request merged**
