### PR TITLE
[MFTF] Refactoring AdminCheckingCreditMemoTotalsTest

### LINKED ISSUE #31403: [Issue] [MFTF] Refactoring AdminCheckingCreditMemoTotalsTest
This issue is automatically created based on existing pull request: magento/magento2#31394: [MFTF] Refactoring AdminCheckingCreditMemoTotalsTest

---------
### Description (*)
The test is refactored according to the best practices

### Manual testing scenarios (*)
1. Place order
2. Invoice order
3. Start creating Credit Memo
4. Set the Shipping field to 0
5. Click the Update Credit Memo Totals button
6. Submit Credit Memo
7. Check Credit Memo Total in grid

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
The test is refactored according to the best practices

### Manual testing scenarios (*)
1. Place order
2. Invoice order
3. Start creating Credit Memo
4. Set the Shipping field to 0
5. Click the Update Credit Memo Totals button
6. Submit Credit Memo
7. Check Credit Memo Total in grid

### Resolved issues:
1. [x] resolves magento/magento2#31403: [MFTF] Refactoring AdminCheckingCreditMemoTotalsTest

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by sidolov** [comment]
@magento create issue

**Comment by eduard13** [comment]
@magento run Semantic Version Checker, Integration Tests, Magento Health Index

**Comment by eduard13** [comment]
@magento run Semantic Version Checker

**Comment by eduard13** [comment]
@magento run Database Compare, Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE, Static Tests, Unit Tests, WebAPI Tests

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8606](https://jira.corp.magento.com/browse/ENGCOM-8606) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
Manual QA is not applicable for MFTF Refactoring PR. Moving it to _Extended Testing_ column

**Pull request merged**
