### PR TITLE
fixes-for-schedule-in-admin:: Schedule Update From (Schedule Design U…

### PR DESCRIPTION
**Pull request by nadim2jcommerce**
### Description (*)

  In 2.3.0 version Schedule Update From (Schedule Design Update) not saving When switch store view from admin

### Fixed Issues (if relevant)

1.magento/magento2#20377: Schedule Update From (Schedule Design Update) not saving When switch store view from admin

### Manual testing scenarios (*)

   1. Go to admin panel
   2. Admin=>Catalog=>Categories=>Navigate any category=>Schedule Design Update
   3. Switch store to "default store view"
   4. Click on checkbox (Checked) and save.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20431) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @nadim2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by Stepa4man — APPROVED** [review]
Hi @nadim2jcommerce, Thanks for your contribution.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @nadim2jcommerce can you please update your branch and resolve conflicts

**Comment by engcom-Foxtrot** [comment]
@sivaschenko resolved.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by Stepa4man** [comment]
@sivaschenko @engcom-Foxtrot resolved conflicts as I can see. Could you please merge?

**Pull request merged**
