### PR TITLE
Enable single store mode by default

### PR DESCRIPTION
**Pull request by therouv**
### Description

 make single-store mode default

### Fixed Issues (if relevant)

1. magento/magento2#1843: make single-store mode default
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by vancoz** [comment]
Internal ticket for this PR is MAGETWO-43040

**Comment by magento-cicd** [comment]
We have automated a Magento Contributor License Agreement verifier for contributions sent to our GitHub projects.
Please see the CLA agreement in the Pull Request comments below.

**Comment by therouv** [comment]
CLA signed.

**Comment by daim2k5** [comment]
@therouv please try again to sign the CLA

**Comment by daim2k5** [comment]
Restart Travis to see if you broke some test ;-)

**Comment by KrystynaKabannyk** [comment]
Hello @therouv, can you please update code of the PR and cover it by Travis tests?

**Comment by therouv** [comment]
@KrystynaKabannyk Updated the code and fixed some failing integration tests. Yet, it seems that travis has some problems during testing (system reboot)?

**Comment by therouv** [comment]
@KrystynaKabannyk Code is updated and tests are now all passing in travis.

**Comment by okorshenko** [comment]
Hi @therouv 
Thank you for your contribution. Unfortunately we can not accept this PR in current state. The code is very outdated and a lot of tests are broken by this change. If you are interested in this contribution, please, create new PR based on latest develop branch. 
Please note that current tests are designed for multi-store mode. So updating the tests for single store is not good approach. We just changing scope of the tests. What we need to do instead - add new tests or variations to test single store mode to the failed tests. We don't want to loose code coverage for multi-store mode 
Thank you

**Comment by ihor-sviziev** [comment]
@okorshenko in Magento 1.x we had a lot of issues with 3rd party modules because they didn't supported multi store configurations that we used (in m1 single store mode was _disabled by default_). As result - we were needed to adjust such modules. If single store more will be enabled by default - we will have **much** more modules that not support multi stores configuration. Is it really good idea?

**Pull request closed without merging**
