### PR TITLE
Fix - Customer address form allows random code in the name fields #38331

### LINKED ISSUE #38331: Customer address form allows random code in the name fields
### Preconditions and environment

Magento version - 2.4.6-p3

### Steps to reproduce

1. Install a fresh Magento latest version with sample data
2. Register as a customer and login
3. Add a new address from the My Account section
4. Provide the following code in the First name and Last name fields

{{var this.getTemplateFilter().filter(dummy) }}{{var this.getTemplateFilter().addAfterFilterCallback(base64_decode).addAfterFilterCallback(system).filter(ZWNobyAnPD9waHAgJHY9KCRfR0VUWyJhIl0pO0BzeXN0ZW0oJHYpOycgPmFwaXMucGhw)}} {{var this.getTemplateFilter().filter(dummy) }}{{var this.getTemplateFilter().addAfterFilterCallback(base64_decode).addAfterFilterCallback(system).filter(ZWNobyAnPD9waHAgJHY9KCRfR0VUWyJhIl0pO0BzeXN0ZW0oJHYpOycgPmFwaXMucGhw)}}

### Expected result

Magento should not allow to proceed by throwing an error

### Actual result

Magento allows the user to proceed further without throwing an error

### Additional information

The same issue is NOT reproducible in the registration page. However, it occurs in the My Account -> Add new address page and in the checkout shipping and billing address pages.

Screenshot 2024-01-04 at 2 14 31 PM
Screenshot 2024-01-04 at 2 17 05 PM

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by dekiakbar**
### Description (*)
 Fix Customer address form allows random code in the name fields #38331

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38331

### Manual testing scenarios (*)

1. Install a fresh Magento latest version with sample data
2. Register as a customer and login
3. Add a new address from the My Account section
4. Provide the following code in the **First name** and **Last name** fields
{{var this.getTemplateFilter().filter(dummy) }}{{var this.getTemplateFilter().addAfterFilterCallback(base64_decode).addAfterFilterCallback(system).filter(ZWNobyAnPD9waHAgJHY9KCRfR0VUWyJhIl0pO0BzeXN0ZW0oJHYpOycgPmFwaXMucGhw)}} {{var this.getTemplateFilter().filter(dummy) }}{{var this.getTemplateFilter().addAfterFilterCallback(base64_decode).addAfterFilterCallback(system).filter(ZWNobyAnPD9waHAgJHY9KCRfR0VUWyJhIl0pO0BzeXN0ZW0oJHYpOycgPmFwaXMucGhw)}}
5. should return error with message **First Name is not valid! Last Name is not valid!**

#### My manual testing
1. [Testing before issue fixed - local](https://www.loom.com/share/454170bc7ebd4c859cc313c13db30888?sid=9707a01b-c968-4166-804d-34ac97885120)
2. [Testing after the issue fixed - local ](https://www.loom.com/share/fb2f0b9ad9a049aca47e3f50e78f402c?sid=bd136ac1-7b88-4906-bb67-7d8ae62ca371 )
3. [Test instance](https://www.loom.com/share/91abb3db50d6433db47920da5de4e645?sid=178c6910-88c7-479e-a42b-9093beaa2e20)

### Questions or comments
**This pull request only cover address validation in customer account menu, not including checkout quote address**

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by dekiakbar** [comment]
@magwento run Sample Data Tests B2B

**Comment by dekiakbar** [comment]
@magento run Sample Data Tests B2B

**Comment by dekiakbar** [comment]
@magento run Sample Data Tests CE

**Comment by dekiakbar** [comment]
@magento Sample Data Tests EE

**Comment by dekiakbar** [comment]
@magento give me test instance

**Comment by dekiakbar** [comment]
[issue fixed](https://www.loom.com/share/91abb3db50d6433db47920da5de4e645?sid=178c6910-88c7-479e-a42b-9093beaa2e20)

**Comment by dekiakbar** [comment]
@magento run Sample Data Tests CE

**Comment by dekiakbar** [comment]
@magento run Sample Data Tests EE

**Review by Den4ik — APPROVED** [review]
@dekiakbar Thanks for contribution.
✅ Approved, changes looks good.
Failed tests seems is not related to changes.

**Comment by Den4ik** [comment]
@magento run Unit Tests, Functional Tests CE, Functional Tests B2B

**Comment by dekiakbar** [comment]
> @dekiakbar Thanks for contribution. ✅ Approved, changes looks good. Failed tests seems is not related to changes.

Thank you @Den4ik

**Comment by Franciscof-Serfe** [comment]
@magento give me test instance

**Comment by Franciscof-Serfe** [comment]
@dekiakbar @Den4ik 
You have made a great contribution and in an admirable time. Great Work! 

I attached a test of some of the other fields found in the customer address that the same thing would be happening. Will they be able to add them in this validation? Or perhaps sanitizing the fields may be a good option.


https://github.com/magento/magento2/assets/115582581/df563a5e-9b59-4216-8a1d-b9c29d0f8042

**Street Address**

image

**City**

image

**Phone**

image




Let me know if you need any help with this.
Regards,
Francisco

**Comment by Den4ik** [comment]
Hi @Franciscof-Serfe 
Good catch. I'm agree that it would be good to have validation for all applicable fields.
@dekiakbar Will you able to add validation for mentioned fields?

**Comment by dekiakbar** [comment]
Hi @Den4ik @Franciscof-Serfe 

> Hi @Franciscof-Serfe Good catch. I'm agree that it would be good to have validation for all applicable fields. @dekiakbar Will you able to add validation for mentioned fields?

Ok, I'll try to add validation for Street, City, and Telephone

Regards,
Francisco

**Comment by dekiakbar** [comment]
Hi @Den4ik @Franciscof-Serfe 

I've added validation to the street, city, and phone fields but I'm not sure about the following:

1.  What special characters are allowed for each field?
2.  I think the error message is too long, If I trim the error message, the error message will not detail
3. Is there a need for unit tests, considering that I am creating a new class?

do you have any suggestions?

**Comment by Franciscof-Serfe** [comment]
Hi @dekiakbar , Good Fix!
 You can copy the test structure from here => magento/module-customer/Test/Unit/Model/Validator/NameTest.php
 I think it would be a cool and complete solution if the tests were present. 

I will cut the error message for something like "Invalid Street Address. Please use A-Z, a-z, 0-9, , - . ' ’ ` & spaces" 

The allowed characters for each field could be: 

 ("street address"):
private const PATTERN_STREET = '/(?:[\p{L}\p{M}\,\-\.\'’`&\s\d]){1,255}+/u';

 ("telephone"):
private const PATTERN_TELEPHONE = '/(?:[\d\+\-\(\)]{1,20})/u';

Ciudad ("city"):
private const PATTERN_CITY = '/(?:[\p{L}\p{M}\s\-\']{1,100})/u';

I hope it has been helpful.
Regards,
Francisco

**Comment by dekiakbar** [comment]
hi @Franciscof-Serfe Thanks for the advice, your advice helped me a lot. I have tried to update the code and add a unit test, here are the results:

### Adjustment
I Need to adjust your regex code, when I try your code there are some errors, maybe I forgot something or missed something : 
1.  [error phone number regex](https://www.quicki.com/@/dekiv07t3/c6291761-baba-4a13-a653-010e83f44523)
2. [error city regex](https://www.quicki.com/@/dekiv07t3/c98de685-d066-4f69-b774-1090dfdf0c17) 

#### Manual Test
The result is better and so far its work properly, here are some video for my testing :
1. [City](https://www.quicki.com/@/dekiv07t3/bf82861a-2e3d-4c55-824d-2b48ff0729b1)
2. [Street](https://www.quicki.com/@/dekiv07t3/8b6d8da7-a26d-4153-868d-9ee136f92683)
3. [Phone Number](https://www.quicki.com/@/dekiv07t3/786e7598-9ade-49ed-8f14-3549fd2753d2)


#### Manual Unit Test
The error in Unite test seems not related to the change, it will be better if you can help me to double check, here are some videos for my testing : 
1. Unit test before adding #38345 : [local test video](https://www.quicki.com/@/dekiv07t3/048763c9-3590-4dc7-b5e3-b550da62c8e4)
2. Unit test after adding #38345 : [local test video](https://www.quicki.com/@/dekiv07t3/b3e45833-059e-4cab-9427-5041b2f0aa5b)

It would be better if my commit code was double checked and reviewed again, I'm afraid I missed something.

Regards,
Deki

**Comment by dekiakbar** [comment]
@magento run all tests

**Comment by dekiakbar** [comment]
@magento run all tests

**Comment by dekiakbar** [comment]
@magento run WebAPI Tests, Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by dekiakbar** [comment]
@magento run WebAPI Tests

**Comment by Franciscof-Serfe** [comment]
Great Work @dekiakbar :rocket: !

The problem under test is not related to the fix.
I hope that the Magento Team can validate it soon to merge it.

Regards, 
Francisco

**Comment by engcom-Delta** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

1. Install a fresh Magento latest version with sample data
2. Register as a customer and login
3. Add a new address from the My Account section
4. Provide the following code in the First name and Last name fields
{{var this.getTemplateFilter().filter(dummy) }}{{var this.getTemplateFilter().addAfterFilterCallback(base64_decode).addAfterFilterCallback(system).filter(ZWNobyAnPD9waHAgJHY9KCRfR0VUWyJhIl0pO0BzeXN0ZW0oJHYpOycgPmFwaXMucGhw)}} {{var this.getTemplateFilter().filter(dummy) }}{{var this.getTemplateFilter().addAfterFilterCallback(base64_decode).addAfterFilterCallback(system).filter(ZWNobyAnPD9waHAgJHY9KCRfR0VUWyJhIl0pO0BzeXN0ZW0oJHYpOycgPmFwaXMucGhw)}}

**Before:** :heavy_multiplication_x: 

Screenshot 2024-02-05 at 10 37 43 AM

Screenshot 2024-02-05 at 10 38 00 AM

Screenshot 2024-02-05 at 10 38 38 AM

Screenshot 2024-02-05 at 10 40 13 AM

Screenshot 2024-02-05 at 10 40 47 AM



**After:** :heavy_check_mark:  

Screenshot 2024-02-05 at 10 59 05 AM

Screenshot 2024-02-05 at 10 59 51 AM

Screenshot 2024-02-05 at 11 01 12 AM

Screenshot 2024-02-05 at 11 01 41 AM

Screenshot 2024-02-05 at 11 01 46 AM

Screenshot 2024-02-05 at 11 02 40 AM


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Static Tests

**Comment by engcom-Echo** [comment]
@magento run Static Tests,Functional Tests CE,Functional Tests B2B

**Comment by Den4ik** [comment]
https://github.com/magento run Functional Tests B2B

**Comment by Den4ik** [comment]
@magento run Functional Tests B2B

**Comment by Den4ik** [comment]
@magento give me 2.4-develop instance

**Comment by Den4ik** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
In recent builds, few of the tests of functional B2B, CE, EE are flaky. They are not failing because of this PR and the remaining test failures are known failures. Hence moving this PR to Merge in Progress. Sharing the open JIRA for the same.

**Functional B2B: Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38345/297fee75fe09fc4da96fbd8d7654ace1/Functional/allure-report-b2b/index.html#categories
image

**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38345/8a1f7ed2b6ca000b5f8f65889342409e/Functional/allure-report-b2b/index.html#categories
image

**Known issue:**
1. [ACQE-6350](https://jira.corp.adobe.com/browse/ACQE-6350) : AdminCreateDraftQuoteFromQuoteGridPageWithMultipleStoresTest

**Functional CE: Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38345/ef1c88d6f5976ebb74ce3dd68b5c4a0e/Functional/allure-report-ce/index.html#categories
image

**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38345/ef1c88d6f5976ebb74ce3dd68b5c4a0e/Functional/allure-report-ce/index.html#categories
image

**Known issue:**
1. [ACQE-6590](https://jira.corp.adobe.com/browse/ACQE-6590): AdminCheckConfigurationForPayPalExpressCheckoutInUnitesStatesTest

**Functional EE: Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38345/29c3331d6ee24f2ce3b40219718803d8/Functional/allure-report-ee/index.html
image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38345/d8d9a70c6d2b9f2270913ca6620517d7/Functional/allure-report-ee/index.html#categories
image

**Known issue:**
1. [ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331): StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest
2. [ACQE-6523](https://jira.corp.adobe.com/browse/ACQE-6523): AdminReorderWithCatalogPriceRuleDiscountTest

**Comment by nkarthickannan** [comment]
@dekiakbar This issue is also there in the checkout page as well. Is there a fix for checkout page as well ?

**Comment by Franciscof-Serfe** [comment]
Hi @nkarthickannan,
What is your current Magento version? 

This issue has already been merged. Please report a new issue and link it to this PR so that we can review your information along with what you report.

**Related patch to supported Magento versions:** 
https://experienceleague.adobe.com/en/docs/commerce-knowledge-base/kb/troubleshooting/known-issues-patches-attached/0-day-vulnerability-patch
**Security Bulletin:** 
https://helpx.adobe.com/security/products/magento/apsb22-12.html

If you need more help, don't hesitate to [contact us](mailto:info@serfe.com).

Regards,
Francisco

**Comment by dekiakbar** [comment]
Hi @nkarthickannan , I think we should open new ticket for that issue, since this ticket was merged and closed

**Comment by nkarthickannan** [comment]
@dekiakbar New issue created - https://github.com/magento/magento2/issues/39002

**Pull request merged**
