### PR TITLE
Fix #21684 - Currency sign for "Layered Navigation Price Step" is not according to default settings

### LINKED ISSUE #21684: Currency sign for "Layered Navigation Price Step" is not according to default settings
### Preconditions (*)

1. Magento CE 2.7 or 2.3
2. Please set Base Currency = Euro
3. Please set Default Currency = Euro
4. Please set Allow Currency = Euro

### Steps to reproduce (*)

1. Go to catalog --> Categories --> Add Sub Category
2. Expand Display Settings
3. Check currency symbol in Layered Navigation Price Step 
 
### Expected result (*)

With these settings the currency displayed in Layered Navigation Price Step must be euro sign (€).

### Actual result (*)

With these settings the currency displayed in  Layered Navigation Price Step is incorrect: displays dollar sign ($), but expected euro sign (€):
image

### Note (*) 

currency displayed in product (Price, Customizable Options → Option → Price) are correct.

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This is fix for #21684 

### Fixed Issues (if relevant)

1. magento/magento2#21684: Currency sign for "Layered Navigation Price Step" is not according to default settings

### Manual testing scenarios (*)

1. Set Base Currency, Default Currency, Allow Currency to EUR
2. Go to catalog --> Categories --> Add Sub Category
3. Expand Display Settings
4. Check currency symbol in Layered Navigation Price Step - it should be EUR symbol

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
Hi @Bartlomiejsz 

During testing we faced with the issue

**_Problem:_** We cannot add images to the category and delete them

**Steps to reproduce:**
1. Login to Admin;
2. Go to Catalog->Categories;
3. Click on Default Category;
4. In "Content" tab add some image;
5. Click on "Save" button;

**Actual result:** error occurs: 'Call to undefined method Magento\Framework\Filesystem::isExist()'
after

@Bartlomiejsz Could you take a look, please?

Thanks!

**Comment by Bartlomiejsz** [comment]
Hi @engcom-Alfa,
right, by accident I imported incorrect class. Fixed it now, please retest.

Thank you

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5986](https://jira.corp.magento.com/browse/ENGCOM-5986) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Review by VladimirZaets — COMMENTED** [review]
Hi @Bartlomiejsz. Thanks for collaboration. Can you please resolve conflicts with mainline?

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @Bartlomiejsz. Thanks for collaboration. Can you please resolve conflicts with mainline?

**Comment by Bartlomiejsz** [comment]
Hi @VladimirZaets, done :)

**Comment by slavvka** [comment]
Hwy @Bartlomiejsz Could you please resolve conflicts?

**Comment by Bartlomiejsz** [comment]
Hi @slavvka, done

**Pull request merged**
