### PR TITLE
Delete tests images after tests execution

### LINKED ISSUE #1650: Fix AdminEnhancedMediaGalleryDeleteImagesInBulkTest
AC:
- unskip test
- test must pass

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/adobe-stock-integration/issues/1650

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
The error in B2B MFTF tests `Test StorefrontConfigurableProductSwatchUpdateCartItemTierPriceTest is missing the required annotations: stories, title, description, severity` is not related to changes in the PR

**Comment by sivaschenko** [comment]
@magento run Functional Tests B2B, Sample Data Tests B2B

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7923](https://jira.corp.magento.com/browse/ENGCOM-7923) has been created to process this Pull Request

**Pull request merged**
