### PR TITLE
Resolve Email address mismatch with text in iPad(768) view issue25935

### LINKED ISSUE #25935: Email address mismatch with text in iPad(768) view
Email address mismatch with text in iPad view

### Preconditions (*)
Magento : 2.3.3

### Steps to reproduce (*)
1. Front end 
2. Register with email like "renard1.abcdefgtest56hijklm@gmail.com"
3. Review the my account dashboard in iPad view

### Expected result (*)
Email should not be mismatch with edit link

### Actual result (*)
image

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#25935: Email address mismatch with text in iPad(768) view

### Fixed Issues (if relevant)

1. magento/magento2#25935: Email address mismatch with text in iPad(768) view

### Manual testing scenarios (*)

1. Front end 
2. Register with email like "renard1.abcdefgtest56sdfsdfsdfsdfsdssshijklm@gmail.com"
3. Review the my account dashboard in iPad view

#### Expected result 
Email should not be mismatch with edit link

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request.
Unfortunately, I can only deploy instances for `2.2-develop` and `2.3-develop` base branches

**Review by krzksz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-6423](https://jira.corp.magento.com/browse/ENGCOM-6423) has been created to process this Pull Request
:eight_spoked_asterisk: @krzksz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

**Before:**
before

**After:**
after

**Comment by sdzhepa** [comment]
@magento give me test instance

**Comment by sdzhepa** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, here is your [new Magento instance](https://pr-25942.instances.magento-community.engineering).
Admin access: [https://pr-25942.instances.magento-community.engineering/admin](https://pr-25942.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Pull request merged**
