### PR TITLE
Bugfix #27601: Allow products with MSI to wishlist with no default stock inventory source

### LINKED ISSUE #3018: Unable to add product with multi-source inventory to wishlist with
### Preconditions (*)

1. Magento Commerce 2.3.4, vanilla 

### Steps to reproduce (*)

1. Create a new inventory source -named 'new-source'-  in the Magento Admin
2. Create a new stock inventory -named 'new-stock'- the Magento Admin, assign 'new-source' and default website to the 'new-stock'. Ensure that the setup is similar to:
Screenshot 2020-04-04 at 23 40 40
3. Create a simple product and only assign "new-stock" as in inventory:
Screenshot 2020-04-04 at 23 48 56
4. Visit the the simple product product detail page in frontend.
5. Add the product to the wishlist.
6. The following error shows:
Screenshot 2020-04-05 at 00 00 50

### Expected result (*)

1. The product should be added to the wishlist.

### Actual result (*)

1. The product is not added to the wishlist.

### LINKED ISSUE #29595: [Issue] Bugfix #27601: Allow products with MSI to wishlist with no default stock inventory source
This issue is automatically created based on existing pull request: magento/magento2#27527: Bugfix #27601: Allow products with MSI to wishlist with no default stock inventory source

---------

### Description (*)
When a product has multiple inventory sources excluding a "default stock", it is possible to add the product to a wishlist, although the product is saleable. If we try to add such a product to the wishlist we get the error: "Cannot add product without stock to wishlist". 

To overcome the problem, we only need to check the stock if a product is not saleable.

### Related Pull Requests
Pull request does not relate to any other PR

### Fixed Issues (if relevant)

1. Fixes magento/magento2#27601

### Manual testing scenarios (*)
1. Setup MSI with multiple sources . 
2. Remove the "default stock" source from a product
3. Add the product to the wishlist.

### Questions or comments
- None

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [-] All new or changed code is covered with unit/integration tests (if applicable)
 - [X] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by FrankStappers**
### Description (*)
When a product has multiple inventory sources excluding a "default stock", it is possible to add the product to a wishlist, although the product is saleable. If we try to add such a product to the wishlist we get the error: "Cannot add product without stock to wishlist". 

To overcome the problem, we only need to check the stock if a product is not saleable.

### Related Pull Requests
Pull request does not relate to any other PR

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/inventory/issues/3018

### Manual testing scenarios (*)
1. Setup MSI with multiple sources . 
2. Remove the "default stock" source from a product
3. Add the product to the wishlist.

### Questions or comments
- None

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [-] All new or changed code is covered with unit/integration tests (if applicable)
 - [X] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29595: Bugfix #27601: Allow products with MSI to wishlist with no default stock inventory source

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8054](https://jira.corp.magento.com/browse/ENGCOM-8054) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@FrankStappers thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Review by engcom-Oscar — CHANGES_REQUESTED** [review]
Hi @FrankStappers! I can't reproduce described issue by steps provided in the ticket  https://github.com/magento/inventory/issues/3018 on latest 2.4-develop branch with MSI 1.2-develop. Can you please recheck it?

**Comment by gabrieldagama** [comment]
Closing this PR due to contributor inactivity and issue not being reproducible, please feel free to reopen it anytime.

**Pull request closed without merging**
