### PR TITLE
Feature south america country regions

### LINKED ISSUE #31169: [Issue] Feature south america country regions
This issue is automatically created based on existing pull request: magento/magento2#31158: Feature south america country regions

---------

### Description (*)
Add states/regions for Argentina, Bolivia, Chile, Ecuador, Guyana, Paraguay, Peru, Suriname and Venezuela.

### Manual testing scenarios (*)

1. Install Magento
2. Check table directory_country_region for Argentina, Bolivia, Chile, Ecuador, Guyana, Paraguay, Peru, Suriname and Venezuela states/regions.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by nikolalardev**
### Description (*)
Add states/regions for Argentina, Bolivia, Chile, Ecuador, Guyana, Paraguay, Peru, Suriname and Venezuela.

### Manual testing scenarios (*)

1. Install Magento
2. Check table directory_country_region for Argentina, Bolivia, Chile, Ecuador, Guyana, Paraguay, Peru, Suriname and Venezuela states/regions.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31169: Feature south america country regions

### CODE REVIEW

**Comment by nikolalardev** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento create issue

**Comment by nikolalardev** [comment]
@magento run all tests

**Comment by nikolalardev** [comment]
@magento run WebAPI Tests

**Comment by nikolalardev** [comment]
@magento run all tests

**Comment by nikolalardev** [comment]
@magento run Functional Tests EE

**Comment by nikolalardev** [comment]
@sidolov Hi can you merge it?

**Comment by nikolalardev** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8685](https://jira.corp.magento.com/browse/ENGCOM-8685) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**After:** :heavy_check_mark: Added states/regions for Argentina, Bolivia, Chile, Ecuador, Guyana, Paraguay, Peru, Suriname and Venezuela
Screenshot from 2021-01-22 14-19-04
Screenshot from 2021-01-22 14-19-20
Screenshot from 2021-01-22 14-19-34
Screenshot from 2021-01-22 14-19-45
Screenshot from 2021-01-22 14-19-56
Screenshot from 2021-01-22 14-20-08
Screenshot from 2021-01-22 14-20-19
Screenshot from 2021-01-22 14-20-32
Screenshot from 2021-01-22 14-20-42

**Comment by kassner** [comment]
@nikolalardev where did the list of regions came from? I am looking into Argentina and their short codes don't really say anything. There is some ISO definitions but they don't match either. Can you clarify? Thanks!

**Comment by nikolalardev** [comment]
@kassner https://en.wikipedia.org/wiki/ISO_3166-2:AR

**Pull request merged**
