### PR TITLE
[Fixed-30452] - Design issue in minicart item remove confirmation modal

### LINKED ISSUE #30452: Design issue in minicart item remove confirmation modal.
Design issue in minicart item remove confirmation modal.

### Preconditions (*)
1.magento version - magento2-2.4-develop
2.php version - PHP 7.4.11
3.view - mobile view

### Steps to reproduce (*)
1) open magento base url.
2) open product and add to cart
3) now open minicart in top right corner.
4) click on delete button side to edit button
5) check the modal content design in mobile view. 

### Expected result (*)
Screenshot_2020-10-12_15-29-53

### Actual result (*)
Screenshot(16)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by niravkrish**
### Description (*)

Design issue in minicart item removes confirmation modal.

### Preconditions (*)
1. magento version - magento2-2.4-develop
2. php version - PHP 7.4.11
3. view - mobile view

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30452

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ptylek** [comment]
This padding was added in order to fix #19263 Can you also check how to fix it for both cases?

**Review by ptylek — CHANGES_REQUESTED** [review]
This padding was added in order to fix #19263 Can you also check how to fix it for both cases?

**Comment by niravkrish** [comment]
@magento give me test instance

**Comment by niravkrish** [comment]
Hi @ptylek ,

Please check in the test instance now the older workaround not needed. Please check the attached screenshot.

screenshot-e4789e4d32ed4a73aa5c52c21c06a8bc instances magento-community engineering-2020 10 13-09_37_41


also, check the below PR.
https://github.com/magento/magento2/pull/19986/files

Thanks & Regards,
Nirav Patel

**Comment by niravkrish** [comment]
@magento run all tests

**Review by ptylek — APPROVED** [review]
Thanks for checking @niravkrish 

Failed test is not related to this PR.

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-8336](https://jira.corp.magento.com/browse/ENGCOM-8336) has been created to process this Pull Request
:eight_spoked_asterisk: @ptylek, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. open magento base url.
2. open product and add to cart
3. now open minicart in top right corner.
4. click on delete button side to edit button
5. check the modal content design in mobile view.

**Before:** :heavy_multiplication_x: 

Screenshot from 2020-10-13 11-41-51

**After:** :heavy_check_mark: 

Screenshot from 2020-10-13 11-42-07

**Pull request merged**
