### PR TITLE
'On-shopping-cart-in-summary-shipping-options-missalinged' :: add cha…

### PR DESCRIPTION
**Pull request by nainesh2jcommerce**
…nges for On shopping cart in summary shipping options missalinged

### Fixed Issues (if relevant)

1. magento/magento2#20131: On shopping cart in summary shipping options missalinged
2. ...

### Manual testing scenarios (*)

1. Ad product to cart
2. and go to cart page, check summary block for shipping options

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20133) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @nainesh2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by miguelbalparda — APPROVED** [review]

**Comment by miguelbalparda** [comment]
Thank you @nainesh2jcommerce! Can you please port this changes to 2.2?

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-3816](https://jira.corp.magento.com/browse/ENGCOM-3816) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@nainesh2jcommerce thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request closed without merging**
