### PR TITLE
[Backport] missing use statement in layout generator

### PR DESCRIPTION
**Pull request by gelanivishal**
### Original Pull Request
https://github.com/magento/magento2/pull/19009

### Description (*)
 
Simple change. LocalizedException was used in class \Magento\Framework\View\Layout\Generator\Block, but it were missing in use section. It were not causing any fatal errors because of the way how it was used in method \Magento\Framework\View\Layout\Generator\Block::handleRenderException:
```
 $message = ($cause instanceof LocalizedException) ? $cause->getLogMessage() : $cause->getMessage();
```

### Manual testing scenarios (*)

1.force any block to throw LocalizedException during generation, and check error message in logs. It ought to be message from the \Magento\Framework\Exception\LocalizedException::getLogMessage method

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3530](https://jira.corp.magento.com/browse/ENGCOM-3530) has been created to process this Pull Request

**Review by rodrigowebjump — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, thank you for the review.
[ENGCOM-3530](https://jira.corp.magento.com/browse/ENGCOM-3530) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.

**Pull request merged**
