### PR TITLE
MC-35725: Price range of a Bundle Product is displayed incorrectly in the case of options with tier price

### LINKED ISSUE #30284: Price range of a Bundle Product is displayed incorrectly in the case of options with tier price
**Preconditions:**
* Magento CE, EE 2.3.5-p1, CE, EE 2.4.0-beta1
* Two Simple Products are created:

               -TEST SIMPLE 1, Price = $100; Advanced Pricing: Quantity =2, Price = Discount = 50%;
                -TEST SIMPLE 2, Price = $200; Advanced Pricing: Quantity =2, Price = Discount = 50%;
* A Bundle Product is created:

Dynamic SKU = Yes, Dynamic Price = Yes, Ship Bundle Items = Together, Option Title = OPTION 1, Input Type = Drop-down, Required; use TEST SIMPLE 1 and TEST SIMPLE 2, Default Quantity = 2
* A Category is created
* All created products are assigned to the Category

**Steps to Reproduce:**
* Go to the Storefront as the guest
* Go to the created Category
* Go to the created Bundle Product page

**(/) Expected results:**

The price range of the Product should be: From **$100.00* To *$200.00**

**(x) Actual results:**

The price range of the Product is: From **$200.00* To *$400.00**

**(i)  NOTE1:**  The price of the option is displayed correctly  in the Shopping Cart

### PR DESCRIPTION
**Pull request by SmVladyslav**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#30284 (MC-35725)

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by SmVladyslav** [comment]
@magento run all tests

**Review by engcom-Kilo — APPROVED** [review]

**Comment by engcom-Oscar** [comment]
:heavy_check_mark: QA passed
Tested by next scenario:
Magento EE 2.4-develop installed
Two Simple Products are created:
-TEST SIMPLE 1, Price = $100; Advanced Pricing: Quantity =2, Price = Discount = 50%;
-TEST SIMPLE 2, Price = $200; Advanced Pricing: Quantity =2, Price = Discount = 50%;

A Bundle Product is created:
Dynamic SKU = Yes, Dynamic Price = Yes, Ship Bundle Items = Together, Option Title = OPTION 1, Input Type = Drop-down, Required; use TEST SIMPLE 1 and TEST SIMPLE 2, Default Quantity = 2

A Category is created
All created products are assigned to the Category
Go to the Storefront as the guest
Go to the created Category
Go to the created Bundle Product page
:x: **Before:**
The price range of the Product is: From $200.00 To $400.00

:heavy_check_mark: **After:**
Screenshot from 2020-12-21 15-27-04

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31352`.

**Pull request merged**
