### PR TITLE
Fix #11175 - i18n:collect-phrases -m can't find many important magento phrases

### LINKED ISSUE #11175: i18n:collect-phrases -m can't find many important magento phrases
**Summary**
This is continuation of thread https://github.com/magento/magento2/issues/2630
Magento 2.2 clear installation using script http://apps.scholtz.sk/magento.install.script.txt
### Preconditions

1. Magento 2.4-develop
2. PHP 7.1, Nginx, Mysql 5.7

### Steps to reproduce
1. Install Magento and download SK language pack
2. do collect phrases php bin/magento i18n:collect-phrases -o "$VER.csv" -m
3. translate phrases
4. Check translations in admin

(I have full translation of magento to slovak language, so i skip step 2 i install it through the script listed above)

### Expected result
I expect all texts to be localised

### Actual result
Some phrases are not translated.. Btw, i can see some progress in the 2 years work now, but still some are missing..

obrazok
obrazok
obrazok
obrazok
obrazok
obrazok

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#11175

### Manual testing scenarios (*)

Please check fixed issue for testing scenario

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Bartlomiejsz** [comment]
@magento run all tests

**Comment by Bartlomiejsz** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8304](https://jira.corp.magento.com/browse/ENGCOM-8304) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8304](https://jira.corp.magento.com/browse/ENGCOM-8304) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Install Magento and download SK language pack
2. Collect phrases `php bin/magento i18n:collect-phrases -o "$VER.csv" -m`
3. Translate phrases
4. Check translations in admin
 
**Before:** :heavy_multiplication_x: Many phrases are missing from the CSV file after collection (for example, "Items in Cart", "Items in Cart", and more)

**After:** :heavy_check_mark: Now in the generated CSV file we can find many important Magento phrases that were missing.
And all texts localized.

**Pull request merged**
