### PR TITLE
Third level category menu issue fix

### LINKED ISSUE #28198: Frontend 3rd level of submenu not accessible
### Preconditions (*)
1. Magento 2.4-develop

### Steps to reproduce (*)
1. Install Magento 2.4-develop with sample data;
2. Go to Catalog - Categories;
3. Go to Women / Tops / Brass & Tanks;
4. Ad a new subcategory (_**Test**_ for example);
5. Save;
6. Go to Homepage;
7. Main Menu -> Woman >Tops  Brass & Tanks;

### Expected result (*)
The new submenu is next to Brass & Tanks
Example 2nd level:  [Image link](https://user-images.githubusercontent.com/15693687/82024545-3e209080-9690-11ea-8048-92035c58b48c.png)

### Actual result (*)
The new submenu is at the top and cannot be reached.
Screenshot from 2020-05-18 15-29-21

### Additional Information
Example: https://github.com/magento/magento2/issues/28198#issuecomment-629092922

### PR DESCRIPTION
**Pull request by kishorenagalingam**
### Description (*)

In menu, third level menu is accessible now when hovering the second level menu

### Related Pull Requests

Before 
Third-level-before-fix

After
Third-level-after-fix

### Fixed Issues (if relevant)

1. Fixes magento/magento2#28198: Frontend 3rd level of submenu not accessible 

### Manual testing scenarios (*)

1. Magento 2.4
2. Theme Luma and Blank
3. Create Third level category

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by kishorenagalingam** [comment]
@magento give me test instance - deploy test instance based on PR changes

**Comment by magento-engcom-team** [comment]
Hi @kishorenagalingam. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @kishorenagalingam, here is your [new Magento instance](https://pr-28260.instances.magento-community.engineering).
Admin access: [https://pr-28260.instances.magento-community.engineering/admin_e729](https://pr-28260.instances.magento-community.engineering/admin_e729)
Login: `5c26b3ab` Password: `5c7bf2b48110`
Instance will be terminated in up to 3 hours.

**Review by mrtuvn — CHANGES_REQUESTED** [review]
can you add new line before &.parent

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
Failed tests not related with changes

**Comment by kishorenagalingam** [comment]
@magento re-run all tests

**Comment by kishorenagalingam** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Database Compare, Functional Tests B2B

**Review by mrtuvn — APPROVED** [review]
new changes ok with me

**Comment by mrtuvn** [comment]
Can we proceed next step with QA/QC verify

**Review by ptylek — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ptylek, thank you for the review.
[ENGCOM-7652](https://jira.corp.magento.com/browse/ENGCOM-7652) has been created to process this Pull Request
:eight_spoked_asterisk: @ptylek, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @ptylek @mrtuvn .
Could you put an appropriate label for test coverage?
Thanks!

**Comment by mrtuvn** [comment]
@engcom-Alfa i don't have permissions for this
In my opinions we don't need auto tests for such case

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Install Magento 2.4-develop with sample data;
2. Go to Catalog - Categories;
3. Go to Men / Tops / Tanks;
4. Ad a new subcategory (_**Category**_ for example);
5. Save;
6. Go to Storefront;
7. Main Menu -> Men ->Tops -> Tanks;

**Before:** :heavy_multiplication_x: The new submenu is at the top and cannot be reached.

Peek 2020-06-11 11-29

**After:** :heavy_check_mark: The new submenu is next to  **Tanks**

Peek 2020-06-11 11-25

**Pull request merged**
