### PR TITLE
magento/magento2#38659: Change order status issue

### LINKED ISSUE #38659: [Issue] Cannot update Order status in 2.4.7
### Preconditions and environment

- Magento version 2.4.7

### Steps to reproduce

1. Try to update status from admin order page view

### Expected result

Status updated

### Actual result

Status not updated

### Additional information

I don't understand this change introduced in 2.4.7 : 
https://github.com/magento/magento2/issues/36562

```
private function getOrderStatus(string $orderStatus, string $historyStatus): string
    {
        return ($orderStatus === Order::STATE_PROCESSING || $orderStatus === Order::STATUS_FRAUD) ? $historyStatus
            : $orderStatus;
    }
```

Why would we be able to change status only if current status is processing or fraud ? (Also, `Order::STATE_PROCESSING` instead of `Order::STATUS_PROCESSING` )

If I understand correctly the issue #36562, the fix should be something like this instead : 
```
private function getOrderStatus(OrderInterface $order, string $historyStatus): string
    {
        $statuses = $this->orderConfig->getStateStatuses($order->getState());
        
        if (!in_array($status, array_keys($statuses))) {
            return $order->getStatus();
        }
        return $historyStatus;
    }
```

Or am I missing something ?

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### LINKED ISSUE #38917: Cannot change intermediate custom status in admin using add comment form
### Preconditions and environment

- Magento version 2.4.7-p1 (latest)

### Steps to reproduce

1. Install vanilla Magento
2. Go to admin Stores => Order Status
3. Create two statuses "Sent" and "Ready for Pickup" and bind them to "Processing" state
4. Create product and register customer
5. Place order on front using this product and customer and default shipping and payment methods
6. Go to admin Sales => Orders
7. Open previously placed order
8. Create invoice by clicking Invoice button on top
9. See order changed status to "Processing"
10. Go to "Add Comment" form change status to "Sent" and add any comment
11. Reload order form and see status changed to "Sent"
12. Go to "Add Comment" form again and change status to "Ready for Pickup" and add any comment
13. Reload order form

### Expected result

See status is changed to "Ready for Pickup"

### Actual result

See status is still "Sent"

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by BeggiNN**
- Fixed issue with changing order status

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38659
2. Fixes magento/magento2#38917

### Manual testing scenarios (*)

1. Install vanilla Magento
3. Go to admin Stores => Order Status
4. Create two statuses "Sent" and "Ready for Pickup" and bind them to "Processing" state
5. Create product and register customer
6. Place order on front using this product and customer and default shipping and payment methods
7. Go to admin Sales => Orders
8. Open previously placed order
9. Create invoice by clicking Invoice button on top
10. See order changed status to "Processing"
11. Go to "Add Comment" form change status to "Sent" and add any comment
12. Reload order form and see status changed to "Sent"
13. Go to "Add Comment" form again and change status to "Ready for Pickup" and add any comment
14. Reload order form

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by BeggiNN** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @BeggiNN,

Thanks for your contribution!

It seems that the build failures are due to PR changes, please look into it.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run Static Tests, Unit Tests, Integration Tests

**Comment by BeggiNN** [comment]
@engcom-Hotel Yes, I will rework the unit tests soon.

**Comment by engcom-Hotel** [comment]
@magento run Unit Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento give me test instance

**Comment by engcom-Bravo** [comment]
Hi @BeggiNN,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

As per the Description


**Before:** :heavy_multiplication_x: 


https://github.com/user-attachments/assets/44b40e2a-9256-426d-ac9e-0ae0d43e422d


**After:** :heavy_check_mark: 


https://github.com/user-attachments/assets/1314ea99-ed2d-4d00-bb73-4e10c9b38eb8




Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Charlie** [comment]
Functional B2B failures in recent 2 builds are not constant and one consistent failure is a known issue.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38923/5117af6736482c83543b2e44c9abaa46/Functional/allure-report-b2b/index.html#categories

image

**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38923/021f7465a77ed23032494110c40e7e8d/Functional/allure-report-b2b/index.html#categories/bdbf199525818fae7a8651db9eafe741

image

**Known issues :**
AdminCreateDraftQuoteFromQuoteGridPageTest: [#ACQE-6309](https://jira.corp.adobe.com/browse/ACQE-6309)

**Comment by engcom-Charlie** [comment]
Some build failures from functional EE are not constant in recent 2 builds, seems to be flaky. One failure is constant and its a  known issue. Hence moving this PR to Merge in Progress.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38923/5103f08befc51821ce422671547d4228/Functional/allure-report-ee/index.html#categories

image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38923/6247a086b89182e6ce8ce256eb1a73fb/Functional/allure-report-ee/index.html#categories

image



**Known issues :**
StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest: [#ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331)

**Comment by hostep** [comment]
Was fixed by internal Adobe devs in https://github.com/magento/magento2/commit/18dee3d979ed8ee68a44324e892e6b7f570c987c, so we can probably close this PR?

**Comment by engcom-Charlie** [comment]
> Was fixed by internal Adobe devs in [18dee3d](https://github.com/magento/magento2/commit/18dee3d979ed8ee68a44324e892e6b7f570c987c), so we can probably close this PR?

Seems to be fixed in https://github.com/magento/magento2/commit/18dee3d979ed8ee68a44324e892e6b7f570c987c under [ACP2E-3178](https://jira.corp.adobe.com/browse/ACP2E-3178) hence closing it now.

**Pull request closed without merging**
