### PR TITLE
[update] return valid json

### PR DESCRIPTION
**Pull request by AurelienLavorel**
Return valid json in each case

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
@AurelienLavorel thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by orlangur** [comment]
@AurelienLavorel could you describe scenario in which empty `$content` does really make sense? I would rather throw `InvalidArgumentException` in case it is empty.

**Comment by AurelienLavorel** [comment]
It's a bug, it shouldn't happen. You may have it in a debug window.
I got that when something wrong happening in setup:static-content:deploy step. With that fix, you can continue using back office. Without that, you can't change page. If we raise an exception, user will have the same error.

**Comment by orlangur** [comment]
> something wrong happening in `setup:static-content:deploy` step

We need precise steps in order to reproduce the issue and assure the fix is really necessary. Could you please provide those? Probably we need some kind of preventer right there in `setup:static-content:deploy`.

> If we raise an exception, user will have the same error.

That's the point, see https://en.wikipedia.org/wiki/Fail-fast. Only if we discover that issue is unavoidable for end user, it should be circumvented the way this PR is implemented.

**Comment by AurelienLavorel** [comment]
I haven't found the root cause of that issue yet.

I agree with the Fail fast logic but in this case, the user cannot make anything on the website. I think testing variables before using it is a good practice.

**Comment by orlangur** [comment]
In this place it could hide a more severe problem so we should be really careful with such condition.

Could you maybe find out what was wrong with your installation after `setup:static-content:deploy`? Then we can try to guess steps further trying to understand what went wrong.

**Comment by AurelienLavorel** [comment]
Understood, I remove the PR for the moment

**Pull request closed without merging**
