### PR TITLE
[Forwardport] fixed - Magento 2.2.6 Default values are not rendering on Wishlist product edit page

### PR DESCRIPTION
**Pull request by davidverholen**
### Original Pull Request 
 https://github.com/magento/magento2/pull/18967

### Description (*)
While editing wishlist item that has configuration, it will not visible selected on configuration page. But after applying this fix it will work.

### Fixed Issues (if relevant)

1. magento/magento2#18555: Magento 2.2.6 Default values are not rendering on Wishlist product edit page

### Manual testing scenarios (*)

1. Add any configurable product with configured attributes to wishlist
2. Now edit the item from wishlist to change the configuration.
3. On Item configuration page the previously opted option will get selected automatically.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @davidverholen. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by rodrigowebjump — APPROVED** [review]
Hi @davidverholen Thanks for your contribution

**Comment by sidolov** [comment]
@davidverholen , we found an issue with the provided solution: 

Manual testing scenario:

1. Create Configurable product with configurations;
2. Create a customer and login to Storefront;
3. Navigate to configurable product page on the frontend;
4. Select the options and add the product to Wishlist;
5. Navigate to My Wishlist page;
6, Click on "Edit" link given in wishlist item.

**Actual result:** 
Pre-selected options did not save.

**Comment by sidolov** [comment]
@davidverholen , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
