### PR TITLE
magento/magento2#38059 Fix issue with product in cart's removed after…

### LINKED ISSUE #38059: Product in cart's removed after reorder multiple times
### Preconditions and environment

- Magento version: 2.4.5-p1
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

1. Navigate to Admin -> Catalog -> Product -> Choose a product -> Advanced Inventory -> set Maximum Qty Allowed in Shopping Cart to a small number -> Save product.
2. Navigate to Shop page -> Login -> Order history page -> Reorder the order which contains the above product
3. Reorder this order until the quantity of the above product reaches the Maximum Qty Allowed in Shopping Cart number 

### Expected result

- Navigates to Shopping cart page
- Keep all the cart items as before the last click
- Show error message ( Ex: Reaches the Maximum Qty Allowed in Shopping Cart )

### Actual result

- Navigates to Shopping cart page
- The product that reaches the Maximum Qty Allowed in Shopping Cart will be removed
- Show error message ( Ex: Reaches the Maximum Qty Allowed in Shopping Cart )

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by BeggiNN**
Fix issue with product in cart's removed after reorder multiple times

### Related Pull Requests
https://github.com/magento-gl/magento2b2b/pull/102

### Description (*)

Product in cart's removed after reorder multiple times if reorder this order until the quantity of the above product reaches the Maximum Qty Allowed in Shopping Cart number

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38059

### Manual testing scenarios (*)

1. Navigate to Admin -> Catalog -> Product -> Choose a product -> Advanced Inventory -> set Maximum Qty Allowed in Shopping Cart to a small number -> Save product.
2. Navigate to Shop page -> Login -> Order history page -> Reorder the order which contains the above product
3. Reorder this order until the quantity of the above product reaches the Maximum Qty Allowed in Shopping Cart number
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by BeggiNN** [comment]
@magento run all tests

**Comment by BeggiNN** [comment]
@magento run Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @BeggiNN,

Thanks for the contribution!

Failed tests seem flaky to me. But in accordance with [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1), please cover these changes with some automated tests.

Thanks

**Comment by BeggiNN** [comment]
@engcom-Hotel Hello!
My changes do not affect the admin panel, below are screenshots of controllers and what they use:
Admin Reorder Controller
image
Front Controller
image
image
I just don't allow you to save the cart when it has some errors
image
And the tests are broken in the admin panel
image
Thanks

**Comment by engcom-Hotel** [comment]
Hello @BeggiNN,

I think you misunderstood my comment [here](https://github.com/magento/magento2/pull/38069#pullrequestreview-1687207531), I am also saying the same thing that the failed tests are not related to the PR changes.  

I just asked you to cover the changes with some automated tests like Unit tests, Functional tests, etc.

Thanks

**Comment by engcom-Echo** [comment]
@BeggiNN did you get chance to have look on above [comment](https://github.com/magento/magento2/pull/38069#issuecomment-1772194066)

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Unit Tests,Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Functional Tests B2B

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @BeggiNN, thank you for your contribution. Could you please double check your MFTF failing test within Functional Tests B2B?

Thank you.

**Comment by engcom-Echo** [comment]
> Could you please double check your MFTF failing test within Functional Tests B2B?

@eduard13 I will take care

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE,Functional Tests EE

**Review by eduard13 — APPROVED** [review]

**Comment by engcom-Delta** [comment]
Moving this PR to On hold as per the comment from contributor below https://github.com/magento/magento2/pull/38069#issuecomment-1836505199

**Comment by bgorski** [comment]
@magento give me 2.4-develop instance

**Review by bgorski — CHANGES_REQUESTED** [review]
We aligned internally yesterday and we agreed that the expected result would be that if a product cannot be reordered with the requested quantity, it should still be added to cart with the maximum allowed quantity, and it also shouldn't prevent other products from being added to cart if the reorder action is trying to add more than one. 
Additionally, this shouldn't change the current behavior when a product is disabled or out of stock.

Whenever a product is added with a quantity lower than expected, a message should appear and it should inform the customer that the product got added with a quantity X instead of Y, because X is the max allowed in cart.

Example 1:
The cart already contains 10 pieces of Product A. We're trying to reorder 10 pieces of Product B and 10 pieces of Product C. However, product B got modified in the meantime and now its max qty allowed in cart is 5.
The expected result is that the cart contains 10 pieces of Product A, 5 pieces of Product B and 10 pieces of Product C

Example 2: 
The cart is empty. We're trying to reorder Product A, Product B and Product C, with a quantity of 10 each. However, Product B got modified in the meantime and now its max qty allowed in cart is 5, Also, Product C is out of stock.
The expected result is that the cart contains 10 pieces of Product A and 5 pieces of Product B .

**Comment by engcom-Bravo** [comment]
We are waiting for PO confirmation.Hence we are moving this PR to ON HOLD.

**Comment by engcom-Bravo** [comment]
As Per the PO Confirmation We are proceeding with this PR.

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
@magento give me test instance

**Review by engcom-Bravo — CHANGES_REQUESTED** [review]
Hi @BeggiNN,

Thanks for your Contribution.

The issue has been confirmed here https://github.com/magento/magento2/issues/38059#issuecomment-1757262711 now the issue is not reproducible.Kindly refer the attached video.




https://github.com/magento/magento2/assets/51680745/366fe7aa-1108-4c01-8af5-3423d51a0f1f




But we have observed a new issue that while reordering when the product exceeds maximum quantity it is giving an error but the product is added to the cart more than maximum quantity and there is no proceed to checkout option.




Screenshot 2024-05-14 at 15 42 50





Screenshot 2024-05-14 at 15 43 11


We have verified this issue with the PR changes it is not fixing the issue.Could you please check the behaviour and let us know if we are missing anything.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @BeggiNN,

Thank you for your contribution!

As mentioned [here](https://github.com/magento/magento2/pull/38069#issuecomment-2121829336), please have a look and let us know if we are missing anything.

Till then closing this PR. Please feel free to reopen it as you want to update further.

Thank you!

**Pull request closed without merging**
