### PR TITLE
[MFTF] Refactoring MoveLastOrderedSimpleProductOnOrderPageTest

### PR DESCRIPTION
**Pull request by AnnaAPak**
The test is refactored to improve execution time

### Related Pull Requests

https://github.com/magento/magento2/pull/33662

Please, note: the test is dependent on https://github.com/magento/magento2/pull/33662

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-9351](https://jira.corp.magento.com/browse/ENGCOM-9351) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Pull request merged**
