### PR TITLE
[Forwardport] [Correct code formatting]

### PR DESCRIPTION
**Pull request by hitesh-wagento**
### Original Pull Request 
 https://github.com/magento/magento2/pull/15811
### This PR is a:

- [ ] Bug fix or improvement

### Summary
Correct Code formatting.

### Additional information
NA

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @hitesh-wagento. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on Pull Request changes
- `@magento-engcom-team give me new test instance` - deploy **NEW** test instance based on Pull Request changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy Vanilla Magento instance for Issue or Pull Request

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by ihor-sviziev** [comment]
Hi @hitesh-wagento,
You have commits without commit message. Could you fix it and force push this PR?

**Comment by hitesh-wagento** [comment]
Hi @ihor-sviziev

I have created Forwardport using port tool. how can I add commit message in it ?

Thanks

**Comment by ishakhsuvarov** [comment]
@hitesh-wagento You may checkout out this branch locally and do a reword for the commit messages.
Here is a reference on the process: https://help.github.com/articles/changing-a-commit-message/

**Comment by hitesh-wagento** [comment]
Hi @ishakhsuvarov 

I have force pushed my commit. Why this showing conflicts ? Why this showing conflicts ?

**Comment by ishakhsuvarov** [comment]
@hitesh-wagento Looks like you had some errors with the rebase process. Also, commits with empty messages are still present. Please verify your procedure and try again.

**Comment by hitesh-wagento** [comment]
Hi @ishakhsuvarov 

I have run follow commands :
git commit --amend
git push --force

image


I have created Forwardport using Port tool. Can I create again ?

**Comment by orlangur** [comment]
@hitesh-wagento it looks like you are doing something very wrong, merge commits cannot appear by themselves.

**Comment by hitesh-wagento** [comment]
Hi @orlangur 

As per your yesterday's suggestion I have created Forwardport using Port tool https://github.com/magento/magento2/pull/15813#issuecomment-397440337. I didn't do any manually changes.

**Comment by orlangur** [comment]
@hitesh-wagento this PR was initially consisting of four commits with empty messages. Now I see a lot of merge commits. So, obviously something is going on on your side.

**Comment by hitesh-wagento** [comment]
Hi @orlangur

Can I create again new PR with port tool ?

**Comment by orlangur** [comment]
@hitesh-wagento surely.

**Comment by hitesh-wagento** [comment]
Hi @orlangur 

I have created again Pull request using port tool but it's showing me 39 Files changes.

Can you please check once : https://github.com/hitesh-wagento/magento2/pull/19

Thanks

**Comment by orlangur** [comment]
@hitesh-wagento I believe you are not supposed to create porting PR in your own fork. As you see other changes from origin `2.3-develop` are appearing in your fork PR as a result.

**Pull request closed without merging**
