### PR TITLE
Fixed typo error in sales grid at admin

### PR DESCRIPTION
**Pull request by vishal-7037**
### Description (*)

Fixed typo issue at sales shipment grid, sales credit memo grid at Magento admin.
### Fixed Issues (if relevant)

1. magento/magento2#22030: Typo issue: Magento admin sales order shipment header typo issue

### Manual testing scenarios (*)

1. Login to Magento admin
2. Open Sale > Shipment
3. Check header title of Order column.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @vishal-7037. Thank you for your contribution.
Did you make sure that the new title is translated correctly in case if a different language is used?

**Comment by vishal-7037** [comment]
Hi @rogyar ,
Thank you for your quick response.

I've already checked it a translation package and it seems working fine with different language.
I've fixed this typo issue using reference of sales invoice grid. you can review [app/code/Magento/Sales/view/adminhtml/ui_component/sales_order_creditmemo_grid.xml](https://github.com/magento/magento2/blob/08fbdf1c1c7d6c3474186de77276004777d31b1c/app/code/Magento/Sales/view/adminhtml/ui_component/sales_order_invoice_grid.xml#L96) file.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4606](https://jira.corp.magento.com/browse/ENGCOM-4606) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed 
In the Sales->Invoice grid, the header title of a column is "Order #". This was done to better Semantic for UI Components in  [commit](https://github.com/magento-engcom/magento2ce/commit/14ab068cf57a2741caa0b251f787e826563d25d6).

**Pull request merged**
