### PR TITLE
[Backport] Fixed #22506: Search suggestion panel overlapping on advance reporting button 

### LINKED ISSUE #22506: Search suggestion panel overlapping on advance reporting button
### Preconditions (*)
1. Admin panel magento 2.3

### Steps to reproduce (*)
1. Log into the admin panel 
2. Click on search icon form the dashboard
3. Enter any Search keyword (Email Id)  
4. Search result pop-up overlapping on advanced reporting button 

### Expected result (*)
1. After entering sample data in the search box then the system should not be overlapped pop-up on advanced reporting button.

### Actual result (*)
1. Search result pop-up should not be overlapped on advanced reporting.

search

### PR DESCRIPTION
**Pull request by krishprakash**
### Original Pull Request 
 https://github.com/magento/magento2/pull/22520

Search suggestion panel overlapping on advance reporting button Fixed.

### Description (*)

In this PR is have fixed Search suggestion panel overlapping on advance reporting button.
### Fixed Issues (if relevant)

1. #22506 
2. ...

### Manual testing scenarios (*)

1. Log into the admin panel
2. Click on search icon form the dashboard
3. Enter any Search keyword (Email Id) or Long text.
4. Search result pop-up is now not overlapping on advanced reporting button.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by krishprakash** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @krishprakash. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @krishprakash, here is your [new Magento instance](https://pr-23151.instances.magento-community.engineering).
Admin access: [https://pr-23151.instances.magento-community.engineering/admin](https://pr-23151.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by krishprakash** [comment]
Issue fixed in given instance.

**Review by ronak2ram — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ronak2ram, thank you for the review.
[ENGCOM-5214](https://jira.corp.magento.com/browse/ENGCOM-5214) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
