### PR TITLE
Rollback MAGETWO-96403 as it was closed as "NOT A BUG"

### LINKED ISSUE #29619: [Issue] Rollback MAGETWO-96403 as it was closed as "NOT A BUG"
This issue is automatically created based on existing pull request: magento/magento2#26392: Rollback MAGETWO-96403 as it was closed as "NOT A BUG"

---------
# Description (*)
See https://github.com/magento/magento2/issues/24422
Cannot enable "Apply to shipping amount" when you Apply "Fixed amount discount for whole cart"
It should be possible according to documentation (https://docs.magento.com/m2/ce/user_guide/marketing/price-rules-cart-create.html):
``Fixed amount discount for whole cart:
Discounts the entire cart by subtracting a fixed amount from the cart total. For example: Enter 10 in Discount Amount to subtract $10 from the cart total.By default, the discount applies only to the cart subtotal. To apply the discount to the subtotal and shipping separately, see Apply to Shipping Amount.``

According to the notes There was a ticket, MAGETWO-96403, that was closed as "NOT A BUG", however, some parts of the code made it in to the code base

### Fixed Issues
1. magento/magento2#24422: "Apply discount to Shipping Amount" disabled for "Fixed amount discount for whole cart" action

### Manual testing scenarios
From the Adminhtml:
1. Go to admin panel -> Marketing -> Cart Price Rules -> Add new rule
2. In Actions tab and set Apply to "Fixed amount discount for whole cart"
3. Set a coupon code, and set the fixed amount to a value, say $10
4. Create a flat rate shipping rate equal to #3, above. In my example $10
5. Create a product LESS with a price LESS THAN #3, above. Example: $5

From the front end:
1. add product to cart
2. Add coupon code to cart or checkout page.
3. Total should now equal price of product, $5, NOT the price of shipping

### Questions or comments
There were several other test cases included with this commit that appeared to be cleanup. I have left those, but will test to see if any of them now fail. Any insight on these is appreciated.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by justinharris1986**
# Description (*)
See https://github.com/magento/magento2/issues/24422
Cannot enable "Apply to shipping amount" when you Apply "Fixed amount discount for whole cart"
It should be possible according to documentation (https://docs.magento.com/m2/ce/user_guide/marketing/price-rules-cart-create.html):
``Fixed amount discount for whole cart:
Discounts the entire cart by subtracting a fixed amount from the cart total. For example: Enter 10 in Discount Amount to subtract $10 from the cart total.By default, the discount applies only to the cart subtotal. To apply the discount to the subtotal and shipping separately, see Apply to Shipping Amount.``

According to the notes There was a ticket, MAGETWO-96403, that was closed as "NOT A BUG", however, some parts of the code made it in to the code base

### Fixed Issues
1. magento/magento2#24422: "Apply discount to Shipping Amount" disabled for "Fixed amount discount for whole cart" action

### Manual testing scenarios
From the Adminhtml:
1. Go to admin panel -> Marketing -> Cart Price Rules -> Add new rule
2. In Actions tab and set Apply to "Fixed amount discount for whole cart"
3. Set a coupon code, and set the fixed amount to a value, say $10
4. Create a flat rate shipping rate equal to #3, above. In my example $10
5. Create a product LESS with a price LESS THAN #3, above. Example: $5

From the front end:
1. add product to cart
2. Add coupon code to cart or checkout page.
3. Total should now equal price of product, $5, NOT the price of shipping

### Questions or comments
There were several other test cases included with this commit that appeared to be cleanup. I have left those, but will test to see if any of them now fail. Any insight on these is appreciated.

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29619: Rollback MAGETWO-96403 as it was closed as "NOT A BUG"

### CODE REVIEW

**Comment by justinharris1986** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @justinharris1986. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @justinharris1986, here is your [new Magento instance](https://pr-26392.instances.magento-community.engineering).
Admin access: [https://pr-26392.instances.magento-community.engineering/admin](https://pr-26392.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by justinharris1986** [comment]
There are some UI Tweaks that should be updated. I will close and re-open once all the checks run so I know they pass for the 2nd round of revisions

**Comment by justinharris1986** [comment]
In regards to the two checks that fail:

### Functional Tests EE
It looks like this is something other than this update:
``CSS or XPath element with '//div[@class='filter-options-title' and contains(text(), 'Category')]' was not found.``

### Static Tests
Not sure about this one, It is part of a file that has been updated, however, I only updated a test value, not class descriptions. Need some direction here on where/what needs to be updated.

```FILE: ...tml/app/code/Magento/SalesRule/Test/Unit/Model/ValidatorTest.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 19 | WARNING | Class description should contain additional
    |         | information beyond the name already supplies.
----------------------------------------------------------------------
```

**Comment by sidolov** [comment]
@magento create issue

**Comment by sidolov** [comment]
@justinharris1986 I'm closing this pull request since the issue mentioned in the description has been already fixed.

**Pull request closed without merging**
