### PR TITLE
[Integration] Refactoring AdminNotification fixture

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR refactores AdminNotification fixture for integration test

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run Unit Tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7601](https://jira.corp.magento.com/browse/ENGCOM-7601) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Charlie** [comment]
Failed tests not related to changes from this PR.

**Pull request merged**
