### PR TITLE
Remove sku from operators to validate condition

### PR DESCRIPTION
**Pull request by igor-imaginemage**
### Description
@AndersonAlves faced an issue with our customers running Magento 2.2. When you create a product with a sku and you use the sku as a condition to a cart rule it will use the "{}"(contains) condition, and not equals "==". We debugged the code and we found an issue available only on Magento 2.2.

### Fixed Issues
This PR will fix this issue on Magento 2.2. Magento 2.1 and 2.3 are working correctly, this fix was already applied to them.

### Manual testing scenarios
1. Create a product with a sku 123
2. Create a configurable product with sku `conf123`.
3. Create simple products for this configurable with `123` inside the skus, for example `conf-red-123` and `conf-blue-123`.
4. Create a cart rule and inside actions add a condition to apply the discount only if a product sku is **equals** to `123`.
5. You can specify a coupon code or not for this rule, it's optional.
6. Specify a discount amount or a percentage.
7. Add the configurable product to the cart and go to the cart page.
8. You will see the discount is being applied to the configurable product, and the configurable product sku is not equals to `123`, it contains `123` in the sku, but is not equal.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20412) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @igor-imaginemage. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by sivaschenko** [comment]
Hi @igor-imaginemage I see that `sku` is present in the condition changed by this pull request on 2.3-develop branch, was it fixed there using a different approach?

**Comment by igor-imaginemage** [comment]
Hi @sivaschenko, on `2.1` and `2.3-develop` this class doesn't have the `sku` inside the conditions in the `getOperatorForValidate` method. We tested and it's not happening on 2.1 and 2.3, only on 2.2 because on `2.2-develop` we have this condition on this method.

Here is the same class on `2.3-develop`: https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Rule/Model/Condition/Product/AbstractProduct.php

**Comment by igor-imaginemage** [comment]
This is the code on 2.3 and 2.1 (working correctly):
if ($this->getInputType() == "category") {

This is the code on 2.2 (not working properly with sku):
if (in_array($this->getInputType(), ["category", "sku"])) {

It's the same method (getOperatorForValidate), but only on 2.2 it's using the `sku` inside the first `if`.

**Comment by sivaschenko** [comment]
Thanks for the detailed explanation @igor-imaginemage ! 

The only my concern is the actual reason why the `sku` was added to the condition.

These two commits: https://github.com/magento/magento2/commit/8d6234124c08699e1891c121266be61946306a9f and https://github.com/magento/magento2/commit/d5b596a1c832a7919438b8711a8a048b3a7129da  were introduced to fix the issue https://github.com/magento/magento2/issues/11897 .

In order to merge this pull request, it's required to ensure that the mentioned issue for multiple SKUs will not reappear. Would you be able to add proper handling of multiple SKUs condition to this pull request?

**Comment by igor-imaginemage** [comment]
@sivaschenko, I just tested with mutiple skus and it's working correctly. I tested a cart rule with multiple skus and also a product list widget, as reported in the issue #11897. Both are working correctly.

This verifications on `getOperatorForValidate` that was including the sku attribute is not necessary, because if we want to use multiple skus we have to use the `is one of` options and not `is`. See here: https://prnt.sc/ma1ktf

This previous inclusion of sku was forcing the `is` to be a `is one of` comparator. The `is` has to compare only one item, and not multiple items.

**Comment by igor-imaginemage** [comment]
@sivaschenko, this change that I've made in this PR is already on 2.1 and 2.3. By some reason is not available only on 2.2. Maybe who fixed that forgot to create the PR to 2.2.

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-4000](https://jira.corp.magento.com/browse/ENGCOM-4000) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@igor-imaginemage thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [new Magento instance](https://pr-20412.instances.magento-community.engineering).
Admin access: [https://pr-20412.instances.magento-community.engineering/admin](https://pr-20412.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Pull request merged**
