### PR TITLE
#30388 : fix js error on edit review page

### PR DESCRIPTION
**Pull request by sunilit42**
fix issue :- https://github.com/magento/magento2/issues/30388

### CODE REVIEW

**Comment by sunilit42** [comment]
@magento run all tests

**Comment by vijay-wagento** [comment]
#dmcdindia2020

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @sunilit42. Thank you for providing the fix. According to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered by autotests. Could I ask you to cover your changes with an MFTF test, please?

Thank you!

**Comment by rogyar** [comment]
@magento run all tests

**Comment by sunilit42** [comment]
@rogyar  do i need to do any thing?

**Comment by rogyar** [comment]
Hi @sunilit42. Please, ignore my comment regarding MFTF tests. I don't think we can cover this case with auto tests. 
Could you provide, please, more info about the testing scenario? I assume that the issue is reproducible only when single store mode is enabled, is this assumption correct? 

Thanks

**Comment by sunilit42** [comment]
@rogyar it is happen with mutiple store as well

just add review and then go for edit review

https://github.com/magento/magento2/issues/30388

**Comment by rogyar** [comment]
@magento give me 2.4-develop instance

**Comment by rogyar** [comment]
@magento give me test instance

**Review by rogyar — APPROVED** [review]
Hi @sunilit42. Thanks for the clarification. The fix works well for me. 
We usually ask to cover all fixes by automated tests. But in this particular case, I'm not sure we can create coverage since I don't see a broken functionality except for the console error. So, nothing to assert, basically.

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8354](https://jira.corp.magento.com/browse/ENGCOM-8354) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Precondition:**

Have at least 1 review in the grid

**Manual testing scenario:**

1. Login to admin
2. Go to menu Marketing -> All Reivews
3. Try to edit any order

**Before:** :heavy_multiplication_x: JS console error - Uncaught TypeError: Event.observe is not a function



**After:** :heavy_check_mark: Working review edit



All functionalities, related to review, work as expected

**Pull request merged**
