### PR TITLE
Updated Switzerland regions

### LINKED ISSUE #32602: [Issue] Use English consistently for the Swiss regions names
This issue is automatically created based on existing pull request: magento/magento2#32553: Use English consistently for the Swiss regions names

---------
### Description

Some of the Swiss regions are using a name that is not in English nor in the official language of the Canton. [Source](https://en.wikipedia.org/wiki/Cantons_of_Switzerland#List).

### Manual testing scenarios

1. On the address create/edit form, select Switzerland as country;
2. There is no `Geneve` in the regions list.

### Questions or comments

Disclaimer: I am not Swiss neither live in the country, I just happen to have a few customers mentioning that the region names weren't straight forward.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by sergiy-v**
### Description
Update Switzerland regions. This PR replaces  #32553 

### Fixed Issues
Fixes #32602

### CODE REVIEW

**Comment by sergiy-v** [comment]
@magento run all tests

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9180](https://jira.corp.magento.com/browse/ENGCOM-9180) has been created to process this Pull Request

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9180](https://jira.corp.magento.com/browse/ENGCOM-9180) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Created a fresh Magento instance, switch to the PR fix branch.

2. Login to Admin - Store Configuration address - Select the Switzerland country, and validate the replaced state names
 
3. Create a customer in the front end and do login.

4. Navigate to the My Account > Address book > Add new address - Select the Switzerland country, and validate the replaced state names

5. Search any product and add do the cart and checkout. Add new shipping address- Select the Switzerland country, and validate the replaced state names

**Before:** :heavy_multiplication_x: A few state names of Switzerland were miss spelled, and are highlighted in the below screenshot.
image


**After:** :heavy_check_mark:  Miss-spelled state names of Switzerland are corrected properly as shown in below screenshot.
image
image
image




Tested in frontend and Admin side address fields.

**Pull request merged**
