### PR TITLE
Email-template-popup-blank-fixes:: Email Template Information Insert …

### PR DESCRIPTION
**Pull request by nadim2jcommerce**
### Description (*)

2.3.0
### Fixed Issues (if relevant)

1. magento/magento2 #20111: Email Template Information Insert Variable popup blank

### Manual testing scenarios (*)

1.Go to admin>>MARKETING>>Email Templates>> edit the template

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @nadim2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3996](https://jira.corp.magento.com/browse/ENGCOM-3996) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@nadim2jcommerce thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VladimirZaets** [comment]
Hi @nadim2jcommerce. Thanks for collaboration.

Your fix provides next problem:
Fatal Error message after insert variable to template
Steps to reproduce:

Login to Admin;
Go to Marketing->Communications->Email Templates;
Click on "Add New Template" button;
Select "New Account" template from the list for example;
Click on "Load Template" button;
Fill all required fields;
Click on "Save Template" button;
Click on created before template for edit;
Click on "Insert Variable..." button;
Select "Add URL" link from the list for example;
Click on "Save Template" button;
Click on "Preview" link in the template grid
 We got Fatal Error message.

**Comment by sidolov** [comment]
@nadim2jcommerce , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
