### PR TITLE
product-media-firefox-issue

### LINKED ISSUE #29175: Product Media Drag and Drop in Backend for Firefox
### Preconditions (*)

1. Product Detail Page Backend Medial Gallery Drag and Drop not perfect work in Firefox 78.0.1
2. Modal Popup open When I Drag & Drop Image
3. In other Browser Modal popup not open when I Drag & Drop

### Steps to reproduce (*)

1. Open Magento Backend in Firefox
2. Open Product Detail Page and then Open Images and Video Tab
3. Upload more than one Image
4. and then try to drag and drop

### Expected result (*)

1. when image drag and drop at that time image detail popup not needed
2. just product image drag and drop as needed

### Actual result (*)

1. Image Detail Popup open when I try to Drag and Drop Image

### PR DESCRIPTION
**Pull request by corewaysolution**
### Description (*)

This PR aims to solve this Product Media Gallery Drag and Drop Issue in Firefox
Now Modal Popup open only when clicking on Image Item as before Popup open when drag and drop Image item in Firefox

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29175

### Manual testing scenarios (*)

1. I have tested this in Firefox
2. I have also tested it in other Browser

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by corewaysolution** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @corewaysolution. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @corewaysolution, here is your [new Magento instance](https://pr-29189.instances.magento-community.engineering).
Admin access: [https://pr-29189.instances.magento-community.engineering/admin_5ec3](https://pr-29189.instances.magento-community.engineering/admin_5ec3)
Login: `321d2abf` Password: `5b814cced6a5`
Instance will be terminated in up to 3 hours.

**Comment by corewaysolution** [comment]
@magento run Database Compare

**Comment by corewaysolution** [comment]
@magento run all tests

**Comment by corewaysolution** [comment]
@magento run Static Tests

**Comment by corewaysolution** [comment]
@magento run all tests

**Comment by corewaysolution** [comment]
@magento run all tests

**Comment by corewaysolution** [comment]
@magento run Static Tests

**Comment by corewaysolution** [comment]
@magento run Sample Data Tests CE

**Comment by corewaysolution** [comment]
@magento run Sample Data Tests B2B

**Comment by corewaysolution** [comment]
@magento run Sample Data Tests EE

**Comment by corewaysolution** [comment]
@magento run Database Compare

**Comment by corewaysolution** [comment]
@magento WebAPI Tests

**Comment by corewaysolution** [comment]
@magento run WebAPI Tests

**Comment by corewaysolution** [comment]
@magento run Unit Tests

**Comment by corewaysolution** [comment]
@magento run semantic Version Checker
@magento run Magento Health Index

**Comment by corewaysolution** [comment]
@magento run Semantic Version Checker

**Comment by corewaysolution** [comment]
@magento run Magento Health Index

**Comment by corewaysolution** [comment]
@magento run Integration Tests

**Comment by corewaysolution** [comment]
@magento run Functional Tests CE

**Comment by corewaysolution** [comment]
@magento run Functional Tests EE

**Comment by corewaysolution** [comment]
@magento run Functional Tests B2B

**Comment by corewaysolution** [comment]
@magento run Functional Tests CE

**Comment by corewaysolution** [comment]
@magento run all tests

**Comment by corewaysolution** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@corewaysolution , I'm closing the PR since the issue was closed several days ago. Feel free to re-open it in case you want to continue.

**Comment by corewaysolution** [comment]
re-open

**Pull request closed without merging**
