### PR TITLE
Added call to action to compile command error

### PR DESCRIPTION
**Pull request by sammarcus**
The original informational message stated the situation but did not suggest how to resolve it. By suggesting how to rectify the situation, it is far more useful than sending the user on a goose chase.

### CODE REVIEW

**Comment by sammarcus** [comment]
An example is #2457 seems to have confusion over how to fix this, so a more informational message would be helpful.

**Comment by mazhalai** [comment]
@sammarcus please sync with the develop branch and rerun travis builds. Also, there are static test failures. https://travis-ci.org/magento/magento2/jobs/122719584#L618

**Comment by sshrewz** [comment]
Internal ticket - MAGETWO-56787

**Comment by caneraydinbey** [comment]
> caner@vegan:/var/www/html/magento/bin$ sudo magento setup:di:compile
> sudo: magento: command not found
> caner@vegan:/var/www/html/magento/bin$ sudo su
> root@vegan:/var/www/html/magento/bin# magento setup:di:compile
> magento: command not found
> root@vegan:/var/www/html/magento/bin# exit
> exit
> caner@vegan:/var/www/html/magento/bin$ magento setup:di:compile
> The file "/var/www/html/magento/var/generation/Composer/Console/ApplicationFactory.php" cannot be deleted Warning!unlink(/var/www/html/magento/var/generation/Composer/Console/ApplicationFactory.php): Permission denied#0 /var/www/html/magento/vendor/magento/framework/Filesystem/Driver/File.php(405): Magento\Framework\Filesystem\Driver\File->deleteFile('/var/www/html/m...')
> #1 /var/www/html/magento/vendor/magento/framework/Filesystem/Driver/File.php(403): Magento\Framework\Filesystem\Driver\File->deleteDirectory('/var/www/html/m...')
> #2 /var/www/html/magento/vendor/magento/framework/Filesystem/Driver/File.php(403): Magento\Framework\Filesystem\Driver\File->deleteDirectory('/var/www/html/m...')
> #3 /var/www/html/magento/setup/src/Magento/Setup/Console/CompilerPreparation.php(68): Magento\Framework\Filesystem\Driver\File->deleteDirectory('/var/www/html/m...')
> #4 /var/www/html/magento/vendor/magento/framework/Console/Cli.php(74): Magento\Setup\Console\CompilerPreparation->handleCompilerEnvironment()
> #5 /var/www/html/magento/bin/magento(22): Magento\Framework\Console\Cli->__construct('Magento CLI')
> #6 {main}
> 
> PHP Fatal error:  Class 'Cli' not found in /var/www/html/magento/bin/magento on line 31
> PHP Stack trace:
> PHP   1. {main}() /var/www/html/magento/bin/magento:0
> caner@vegan:/var/www/html/magento/bin$

**Comment by sammarcus** [comment]
@caneraydinbey what is your last comment? It looks like you're not in the right directory and have some permissions issues, but neither of those are related to this PR.

**Comment by sammarcus** [comment]
@mazhalai all set and my build now passes, can this PR please be considered for merging now?

**Comment by caneraydinbey** [comment]
I think i changed php to 7 and solved.

**Comment by sammarcus** [comment]
@caneraydinbey your problem has nothing to do with what this PR addresses. please open your own issue if you feel it warrants it.

**Comment by Ctucker9233** [comment]
Please merge

**Comment by sammarcus** [comment]
@snohe @mazhalai can this be merged?

**Comment by BaDos** [comment]
Merged.
Thank you for your contribution.

**Comment by Ctucker9233** [comment]
Still not included in 2.1.10

**Pull request merged**
