### PR TITLE
Changed return type of addToCartPostParams to array

### PR DESCRIPTION
**Pull request by LordZardeck**
### Description

\Magento\Catalog\Block\Product\ListProduct::getAddToCartPostParams incorrectly defined a string return type when in fact it's an array

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14876) <br/>All committers have signed the CLA.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-1403](https://jira.corp.magento.com/browse/ENGCOM-1403) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@LordZardeck thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by LordZardeck** [comment]
@magento-engcom-team Joined.

**Comment by magento-engcom-team** [comment]
Hi @LordZardeck. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

**Pull request merged**
