### PR TITLE
website wise child fixed for configurable product

### PR DESCRIPTION
**Pull request by sunilit42**
Fixed issue :- #24372

### CODE REVIEW

**Comment by luanalves** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @luanalves. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @luanalves, here is your [new Magento instance](https://pr-24375.instances.magento-community.engineering).
Admin access: [https://pr-24375.instances.magento-community.engineering/admin](https://pr-24375.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by luanalves** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @luanalves. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @luanalves, here is your [Magento instance](https://i-24375-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24375-2-3-develop.instances.magento-community.engineering/admin](https://i-24375-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by luanalves** [comment]
I'm realize this test and in my verification this resolution is OK

**Comment by sunilit42** [comment]
@rodrigowebjump any update?

**Comment by rodrigowebjump** [comment]
Hi @sunilit42 I am investigating the failing test. 
Maybe your fix generated a drawback in admin in some scenarios.

This could not be related directly with your change but I need to confirm.

I will keep you posted.

**Comment by sunilit42** [comment]
> Hi @sunilit42 I am investigating the failing test.
> Maybe your fix generated a drawback in admin in some scenarios.
> 
> This could not be related directly with your change but I need to confirm.
> 
> I will keep you posted.

let me know if you want to do any changes

**Comment by rodrigowebjump** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rodrigowebjump, here is your [new Magento instance](https://pr-24375.instances.magento-community.engineering).
Admin access: [https://pr-24375.instances.magento-community.engineering/admin](https://pr-24375.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by sidolov** [comment]
@magento run Functional Tests build

**Comment by VladimirZaets** [comment]
@magento run Functional Tests build

**Comment by VladimirZaets** [comment]
@magento run all tests

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Can you please take a look to failed tests and cover it with new tests accoding to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html)

**Comment by VladimirZaets** [comment]
@sunilit42 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Comment by WinstonN** [comment]
> Fixed issue :- #24372

This fix does not work in the way that I expected it too. Perhaps I am not understanding the issue correctly? If that is the case will you please correct me?

With this fix applied, I have 2 websites, each with 1 store. 
1. I navigate to the Magento Admin, select a config product, and see it's associated simple products.
2. I change the scope to store a, and remove a simple product from the config simple product sku (123)
3. I save the product
4. I navigate to store b
5. I see that the simple product with sku 123 has also been removed from the config in this scope

The issue I am highlighting here is:
https://github.com/magento/magento2/issues/26243 but seems to be similar to https://github.com/magento/magento2/issues/24372

**Pull request closed without merging**
