### PR TITLE
Fix for the Issue #25676 with method checkIsAllRequiredOptions for Bundle product

### PR DESCRIPTION
**Pull request by karyna-t**
Fix for the Issue #25676

### Description (*)
possible fix for the Issue #25676. Method checkIsAllRequiredOptions for Bundle product must not allow option without actual value.

### Fixed Issues (if relevant)
1. magento/magento2#25676: Method checkIsAllRequiredOptions for Bundle product allows option without actual value

### Manual testing scenarios (*)
Can be tested via graphql.
1. Create a bundle product with, for example, 2 required options. One of the them must have type 'Multiple Select'.
image

2. Create an empty cart
3. Add product via graphql (or any other way without front-end validation), and
pass empty string "" as a value for the Multiselect option.
```
mutation {
  addBundleProductsToCart(
    input: {
      cart_id: "UnkPkC8a6qwPbjQs0nctSmLxYZXtV9Xh"
      cart_items: {
        data: {
          quantity: 1
          sku: "issue-1039" #sku of the parent bundle 
        }
        bundle_options: [
          {
            id: 6 #multiple select Input Type id
            quantity: 1
            value: [
              "" # No option is provided      
            ]
          }
          {
            id: 5 #checkbox Input Type id
            quantity: 1
            value: [
              "10" #options id
            ]
          }
        ]
      }
    }
  ) {
    cart {
      items {
        id
        quantity
        product {
          sku
          stock_status
        }
        ... on SimpleCartItem {
          customizable_options {
            id
            label
            values {
              id
              label
              value
            }
          }
        }
      }
    }
  }
}
```
4. Expected result:
Product wasn't added to the Cart, exception with message "Please select all required options." thrown.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by karyna-t** [comment]
Hi, can someone clarify the status of the PR? It still requires a review. Thank you.

**Comment by avattam06** [comment]
> Hi, can someone clarify the status of the PR? It still requires a review. Thank you.

@karyna-tsymbal-atwix, Fix looks good, Can you add Web-API-functional tests for the fix?

**Comment by avattam06** [comment]
@magento run all the tests

**Review by avattam06 — CHANGES_REQUESTED** [review]
Need test for the fix

**Comment by avattam06** [comment]
@magentio run all tests

**Comment by avattam06** [comment]
@Magentio run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by karyna-tsymbal-atwix** [comment]
@magento run all tests

**Comment by karyna-tsymbal-atwix** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Review by andrewbess — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, thank you for the review.
[ENGCOM-9146](https://jira.corp.magento.com/browse/ENGCOM-9146) has been created to process this Pull Request
:eight_spoked_asterisk: @andrewbess, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by andrewbess** [comment]
Hello @karyna-tsymbal-atwix 
Thank you for your contribution.
I have updated your branch with the latest changes of core.
Waiting for finish tests.

**Comment by karyna-tsymbal-atwix** [comment]
@magento run Functional Tests B2B

**Comment by karyna-tsymbal-atwix** [comment]
Hi @andrewbess , thanks for the review! Tests are finished.

**Comment by engcom-Alfa** [comment]
Gone through the PR description completely and it is related to fixing the graph mutation response! The automation test has been covered as part of it. Hence approving the ticket for merging!

**Review by cpartica — APPROVED** [review]

**Comment by glo71317** [comment]
We are processing this pull request for merging

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Pull request merged**
