### PR TITLE
magento/magento2#23143: Code optimization for the offline shipping methods

### PR DESCRIPTION
**Pull request by atwixfirster**
### Description (*)

PR keeps solution for magento/magento2#23143: Code optimization for the offline shipping methods.

### Fixed Issues (if relevant)

1. magento/magento2#23143: Code optimization for the offline shipping methods.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by dmytro-ch** [comment]
Hi @atwixfirster,
once all the automated tests passed please squash all commits into a single one in order to clean up history. :)
Thank you!

**Comment by atwixfirster** [comment]
> Hi @atwixfirster,
> once all the automated tests passed please squash all commits into a single one in order to clean up history. :)
> Thank you!

@dmytro-ch , I think we can skip Static Test result here:



because `Magento\OfflineShipping\Model\Carrier\Pickup`::`collectRates` implements function declaration from the parent class.

```
/**
     * @param RateRequest $request
     * @return \Magento\Shipping\Model\Rate\Result
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function collectRates(RateRequest $request)
    {
        // Pickup shipping method is not supported in Magento2 yet.
        return false;
    }
```

Please review.

Thank you!

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5215](https://jira.corp.magento.com/browse/ENGCOM-5215) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
