### PR TITLE
PHPDoc fix redundant exception throw

### PR DESCRIPTION
**Pull request by sankalpshekhar**
Several methods has doc block indicating an exception is being thrown, but they are either caught and processed or no such exceptions are generated within the method processing.
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @sankalpshekhar. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @sankalpshekhar , thanks for the pull request! Can you please run all static tests on the pull request changes to ensure there are no other static test fails on the changed files.

**Comment by sankalpshekhar** [comment]
> 
> 
> Hi @sankalpshekhar , thanks for the pull request! Can you please run all static tests on the pull request changes to ensure there are no other static test fails on the changed files.
@sivaschenko What static tests needs to be executed, could you point me to any documentation for it?
I can see all the tests from Codacy & travis passed.

**Comment by sivaschenko** [comment]
Hi @sankalpshekhar please reset your local repository to origin (to have all changes uncommitted) and run `bin/magento dev:tests:run static`. Alternatively run `\Magento\Test\Php\LiveCodeTest`.

See [Magento Testing Guide](https://devdocs.magento.com/guides/v2.3/test/testing.html#static)

**Comment by sidolov** [comment]
@sankalpshekhar , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
