### PR TITLE
Change link text from "Report a Bug" to "Report an Issue"

### PR DESCRIPTION
**Pull request by Zifius**
Sorry to rise this again, but after discussion on contribution to Magento 2 at Mage Unconference it came to my mind that "Bug" sounds too early 200x-ish as not each issue/problem can be considered a bug, some are feature requests or a typo fix which is not really a "Bug" per definition. Besides GitHub, which is the place to report M2 issues, has its tab named as "Issues"

Thanks for considering!

### CODE REVIEW

**Comment by orlangur** [comment]
I read hundreds of official responses in this repository with remark "GitHub is for bug reports, not for improvement suggestions, questions or discussions" :)

Good to know if this changed afterall and there is no need, for instance, to use Magento Forums for feature requests.

**Comment by Zifius** [comment]
@orlangur I believe this did not change and Forums stand for collecting feature requests and detailed discussion of proposed changes

**Comment by orlangur** [comment]
> some are **feature requests** or a typo fix which is not really a "Bug" per definition

> Forums stand for collecting **feature requests**

Then I don't understand. Typo IS really a bug [per definition](https://www.utest.com/articles/yes-typos-are-bugs-too).

"Issues" section in this repository is narrowed to bugs only as clearly stated by [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines):

> If you are sure that the problem you are experiencing is caused by a bug, file a new issue in a Github issue tracker following the recommendations below.

I'm not a native speaker of English though and "Report an Issue" could sound more natural/less early 200x-ish. So, I'm not against this change, just don't want to increase confusion.

**Comment by Zifius** [comment]
Well, anyhow there are guidelines linked when reporting a new issue https://github.com/magento/magento2/issues/new as you mentioned so I believe the link title change won't create big confusion or misunderstanding

This PR is more about consistency in wording Bug vs Issue in GitHub's context of naming things. I'd prefer hearing feedback from core team about what they think about this change. Any word @maksek @okorshenko?

**Comment by okorshenko** [comment]
@Zifius thank you for this PR. We started internal discussion with TechWriters, DevDocs and UX Teams about this change

**Comment by okorshenko** [comment]
@Zifius thank you for your contribution. Your improvement has need approved!

**Comment by Zifius** [comment]
Once again my pleasure @okorshenko, thanks for approving!

**Pull request merged**
