### PR TITLE
[Fixed] First name and Last name field must not allow to enter URL and Special character's

### PR DESCRIPTION
**Pull request by meetvora69**
### Description (*)

First name and Last name field must not allow to enter URL and Special character's

### Fixed Issues (if relevant)

1. magento/magento2#23487: First name and Last name field must not allow to enter URL and Special character's

### Manual testing scenarios (*)

1. Go to Admin
2. Customers > All customers > Add New Customer
3. Enter URL details for First name Last name field

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @meetvora69,

I just reviewed your fix and found one issue - people will not be able to put non English name & surname. For instance you can't put there "Müller", or "Иван" anymore. 
So there should be some blacklist of special symbols.

Could you double check your solution?

**Comment by ihor-sviziev** [comment]
Hi @meetvora69,
Thank you for your contribution. Unfortunately we didn’t get response from you after more than 14 days, so I’m closing this PR.
Feel free to fix issues listed in my last review and reopen PR.

**Comment by cbichis** [comment]
This is the most frequent attack nowdays, we need to have a way to filter out URL's...

**Comment by ihor-sviziev** [comment]
Hi @cbichis,
Original issue was closed as not an issue, more details with explanation why you could find there.
Could you explain what attack do you mean?

**Comment by cbichis** [comment]
The spam bots are registering or signing up to the newsletter and they are using on first name/last name URL's. This would cause the registration confirmation email to include malicious URL's which of course are dangerous for anyone who clicks on them.

**Comment by ihor-sviziev** [comment]
@cbichis oh, I see. Seems like following issue contains all needed info and should be confirmed https://github.com/magento/magento2/issues/28041

**Comment by cbichis** [comment]
Yeah, but thats a bit a diff topic.

I am pointing out here that it's quite hard to understand Magento with the default settings to have such security holes... For the custom made apps I am doing I also strip out not just tags but also URL's from the fields...

**Comment by ihor-sviziev** [comment]
@cbichis, I see. Seems like this is duplicate of https://github.com/magento/magento2/issues/7266 https://github.com/magento/magento2/issues/28041.

Looks like issue is valid, should be fixable by enabling recaptcha and adding some [WAF](https://en.wikipedia.org/wiki/Web_application_firewall).

**Pull request closed without merging**
