### PR TITLE
[MFTF] Removing the Sales MFTF dependency by Paypal module

### PR DESCRIPTION
**Pull request by eduard13**
### Description (*)
The aim of this PR is to get rid of the wrong dependency of Sales module on Paypal module. This dependency leads to broken Sales MFTF tests, in case we decide to remove the Magento_Paypal module.

Tests that are failing:

- AdminSalesTransactionsNavigateMenuTest
- AdminSalesCreditMemosNavigateMenuTest
- AdminSalesInvoicesNavigateMenuTest
- AdminSalesOrdersNavigateMenuTest
- AdminSalesShipmentsNavigateMenuTest

This is happened because Magento_Sales MFTF tests are trying to reference for a Menu Item that was declared in Magento_Paypal module.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)
1. Remove the Paypal module
2. Run any test mentioned above

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by eduard13** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run Static Tests

**Comment by eduard13** [comment]
@magento run WebAPI Tests, Functional Tests CE, Functional Tests B2B.

@gabrieldagama as for the failed SVC, I think we should be fine, as we're not completely removing that Entity, just moving to another place. What do you think?

**Comment by gabrieldagama** [comment]
Hi @eduard13, thanks for contributing! Yes, I agree, that shouldn't be a problem, it is a false-positive and it should be a quick approval process.

**Comment by eduard13** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Review by rogyar — APPROVED** [review]
Good job!

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by engcom-Foxtrot** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Foxtrot** [comment]
Semantic Version Checker failure should be approved.

**Comment by gabrieldagama** [comment]
Approval ticket created here: https://jira.corp.magento.com/browse/MC-40648

**Comment by eduard13** [comment]
@magento give me 2.4.1 instance

**Comment by eduard13** [comment]
@magento run all tests

Hi @sidolov, is there any update on the approval of the internal ticket?

Thank you.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

This PR is relevant to the MFTF test code factoring as per the description and as looked into the files changed.
Along with SVC failure approvals as [mentioned above](https://github.com/magento/magento2/pull/31794#issuecomment-1095100895), the auto-test jobs are also successfully running with this PR, moving to _Merge In Progress_.
Thanks for the contribution and collaboration all.

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests B2B, WebAPI Tests

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests B2B

**Comment by eduard13** [comment]
@magento give me test instance

**Pull request merged**
