### PR TITLE
[FIX] Issue Make Laminas Filters callable, and compatible with laminas-filters >=3.5.0

### LINKED ISSUE #38589: Sales order report not being displayed, error with date formatting in UI
### Preconditions and environment

- Magento ver. 2.4.6-p4
- PHP 8.1.2
- Linux hosted apache2.4

### Steps to reproduce

Log into admin
Go to Reports -> Sales -> Orders
Select date range from 4/1/24 thru 4/8/24 using the date selector.
Click on show report

Observe logs while doing this, you should see an error as below
main.CRITICAL: PDOException: SQLSTATE[HY000]: General error: 1525 Incorrect DATE value: '04/01/2024' in /vendor/magento/framework/DB/Statement/Pdo/Mysql.php:90

Now do the same thing again, but this time type manually in MySQL format the date so 20240401 and 20240408, watch it work.... 

### Expected result

A report is pulled for the dates reported

### Actual result

Nothing happens, says the report is generated but no information is shown, there is an error in the logs with a stacktrace referencing an invalid date

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### LINKED ISSUE #38590: Sales Reports are not generated
### Preconditions and environment

- Magento 2 version 2.4.6-p5
- Magento 2 system locale Dutch
- Magento 2 admin language english

### Steps to reproduce

Go to Sales order reports
Choose any date from and to
Click on show Report button.

### Expected result

Report should be generated

### Actual result

Report is not generated

### Additional information

In this screenshot is shown that if we use calendar we get no reports
Scherm­afbeelding 2024-04-09 om 08 43 36

When we enter values manually like YYYY-m-d we get our reports
Scherm­afbeelding 2024-04-09 om 08 44 56

also after submitting the form the date is changed to formatted one:
Scherm­afbeelding 2024-04-09 om 08 45 37

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### LINKED ISSUE #38596: Invalid Date when account Local is not en-US
### Preconditions and environment

- Magento versio 2.4.6-p4

### Steps to reproduce

1 - Navigate to admin
2 - Login
3 - Create a cart price rule
4 - Save account with local fr-FR

### Expected result

Cart price rule is save succefully

### Actual result

[2024-04-09T13:41:00.255619+00:00] .CRITICAL: Exception: Failed to parse time string (18/03/2024) at position 0 (1): Unexpected character in /home/vendor/magento/module-rule/Model/AbstractModel.php:400

### Additional information

Working when i put my local in en-US
It's affetcs the product also :
image

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Bashev**
Affected versions: Magento >=2.4.6-p4, 2.4.7

With 2.4.6-p4 laminas/laminas-filters was updated to version 3.5.1, but there is introduced additional validation of the filter classes, which checks is it callable. https://github.com/laminas/laminas-filter/blob/f98ddcfe5b145d84ccfe3cddd95ba60d09231843/src/FilterChain.php#L90

Because of that filtering from magento not works (skipped). 

This PR add AbstractFilter (from laminas) where magic __invoke method is implemented. 

This also affects all other date fields (like special price from/to, news from/to date) and etc, but not only...

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38596
2. Fixes magento/magento2#38589
3. Fixes magento/magento2#38590

### Manual testing scenarios (*)

1. Change admin language to French / Bulgarian or some which have different date format then default English.
A.1 Go to Reports - Sales - Orders (for example)
A.2 Try to filter some orders select some random dates.
A.3 Generate report.

B.1 Go to Catalog - Products 
B.2 Create new product or edit existing product
B.3 Add "News from date" and/or "news to date" with random dates.
B.4 Save

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Bashev** [comment]
@magento run all tests

**Comment by Bashev** [comment]
@magento give me test instance

**Comment by Bashev** [comment]
@magento run all tests

**Comment by hostep** [comment]
Shouldn't we fix this in laminas-filter itself, in my opinion the change introduced in https://github.com/laminas/laminas-filter/pull/124/files#diff-3a6c9663e22963eb296b993e0b7cc8335c9f7f02f8364fc66385ed7175b5639dL89 is not done in a backwards compatible way and should be considered a bug that needs to be fixed.
Because they [later check again for the `is_callable`](https://github.com/laminas/laminas-filter/blob/d68ed259498303fedc9a401e91bf828ca41f474e/src/FilterChain.php#L173-L181) and if it's not the case, actually do something instead of not doing anything.

What do you think @Bashev?

**Comment by Ocramius** [comment]
Can we have an upstream test case that highlights the BC boundary, please?

If the test passes before and fails afterwards, we can act and prevent a regression too, but it meeds to be done with some structure.

**Comment by hostep** [comment]
@Ocramius: I lack the time to send in a proper PR at the moment, but after some quick testing locally, here's a way to demonstrate the problem, apply these changes and run phpunit and you'll see it fail:

```diff
diff --git a/test/FilterChainTest.php b/test/FilterChainTest.php
index 33b3df7f..8d7fc58b 100644
--- a/test/FilterChainTest.php
+++ b/test/FilterChainTest.php
@@ -6,6 +6,7 @@ namespace LaminasTest\Filter;

 use ArrayIterator;
 use Laminas\Filter\FilterChain;
+use Laminas\Filter\FilterInterface;
 use Laminas\Filter\PregReplace;
 use Laminas\Filter\StringToLower;
 use Laminas\Filter\StringTrim;
@@ -116,7 +117,7 @@ class FilterChainTest extends TestCase
     {
         return [
             'callbacks' => [
-                ['callback' => [self::class, 'staticUcaseFilter']],
+                ['callback' => new TestFilter()],
                 [
                     'priority' => 10000,
                     'callback' => static fn(string $value): string => trim($value),
@@ -250,3 +251,11 @@ class FilterChainTest extends TestCase
         ], $filters);
     }
 }
+
+class TestFilter implements Filterinterface
+{
+    public function filter($value)
+    {
+        return strtoupper($value);
+    }
+}
```


Following change fixes the bug, but not sure if this is the best way:

```diff
diff --git a/src/FilterChain.php b/src/FilterChain.php
index 4c092ed2..f776a4d5 100644
--- a/src/FilterChain.php
+++ b/src/FilterChain.php
@@ -87,7 +87,7 @@ class FilterChain extends AbstractFilter implements Countable, IteratorAggregate
                     foreach ($value as $spec) {
                         $callback = $spec['callback'] ?? false;
                         $priority = $spec['priority'] ?? static::DEFAULT_PRIORITY;
-                        if (is_callable($callback)) {
+                        if (is_callable($callback) || $callback instanceof FilterInterface) {
                             $this->attach($callback, $priority);
                         }
                     }
@@ -172,12 +172,6 @@ class FilterChain extends AbstractFilter implements Countable, IteratorAggregate
     public function attach($callback, $priority = self::DEFAULT_PRIORITY)
     {
         if (! is_callable($callback)) {
-            if (! $callback instanceof FilterInterface) {
-                throw new Exception\InvalidArgumentException(sprintf(
-                    'Expected a valid PHP callback; received "%s"',
-                    get_debug_type($callback)
-                ));
-            }
             $callback = [$callback, 'filter'];
         }
         $this->filters->insert($callback, $priority);
```

**Comment by Bashev** [comment]
@hostep it's make sense if can be fixed on laminas side, because this will help to most of the projects which using laminas-filter.

My approach is different - if i must wait on additional vendor, to find a way to fix it on my side, but in this case, we must wait magento for fix and laminas for fix ...

**Comment by Ocramius** [comment]
Fyi, if there's a patch+fix on our end it takes few seconds to tag a release, so please send a PR 😁

**Comment by hostep** [comment]
Here you go: https://github.com/laminas/laminas-filter/pull/140

Let's move the discussion over there.

**Comment by kanevbg** [comment]
@Bashev Колега, много често те мяркам тук напоследък, евала за свършената работа! :)

**Pull request closed without merging**
