### PR TITLE
fix lost currency symbol in admin product grid on Special Price and M…

### PR DESCRIPTION
**Pull request by kkorushkin**
…anufacturer`s Advertised Price

### Description (*)
Fix according #21910 for Magento 2.3.x
For the Special Price and Manufacturer's Advertised Price added corresponding processing classes for their correct presentation in Product Grid.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by orlangur** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @orlangur. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @orlangur, here is your [new Magento instance](https://pr-24874.instances.magento-community.engineering).
Admin access: [https://pr-24874.instances.magento-community.engineering/admin](https://pr-24874.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by ihor-sviziev** [comment]
Hi @kkorushkin,
I see that issue that you wanted to fix already fixed, more info https://github.com/magento/magento2/issues/21910#issuecomment-599882764.
I'm closing this PR.
Thank you for your contribution!

**Pull request closed without merging**
