### PR TITLE
Add Italy States

### PR DESCRIPTION
**Pull request by WaPoNe**
### Description (*)
Add Italy States

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello @WaPoNe, thank you for your contribution.
Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) the changes should be covered by tests. Could you please cover your fix by a functional test and also fix the static test failure?

Thank you!

**Comment by engcom-Echo** [comment]
I will take care of test coverage.

**Comment by WaPoNe** [comment]
Thanks @engcom-Echo 
Tell me how I can help you.
If you want, I can prepare the functional and static tests following your suggestions.

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7113](https://jira.corp.magento.com/browse/ENGCOM-7113) has been created to process this Pull Request

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Pull request merged**
