### PR TITLE
Adding the company and VAT Number values at OPC address.

### LINKED ISSUE #31439: [Issue] Region data fix
This issue is automatically created based on existing pull request: magento/magento2#31425: Region data fix

---------

### Description (*)

Fixed syntax error: Php variable were written without php tags

### Related Pull Requests

N/A
### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

This can be repeated only when address fields are enabled for customer signup form. Once these are enabled, just open the signup form and see js error & state/region dropdown is missing

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### LINKED ISSUE #31652: [Issue] Adding the company and VAT Number values at OPC address.
This issue is automatically created based on existing pull request: magento/magento2#31425: Adding the company and VAT Number values at OPC address.

---------

### Description (*)

Adding the company and VAT Number values at OPC address.

**Preconditions:**

1. Magento 2.4-develop
2. Have 1 created product

**Manual testing scenario:**

1. Set `Store->Configuration->Customer Configuration->Name and Address Options->Show Company` to 'Optional'
2. Set `Store->Configuration->Customer Configuration->Create New Account Options->Show VAT Number` on Storefront to 'Optional'
3. Save config
4. Run: `bin/magento cache:clean`
5. Open registration page /customer/account/create/
6. Create the customer with the company name and add VAT Number (admin->Customers->edit created customer->Addresses->Add/Update Address)
7. Add any product to the cart and go to the shipping step

**Actual Result:** :heavy_multiplication_x: Company name and VAT Id are not visible 

Screenshot from 2021-01-15 09-44-31

**Expected Result:** :heavy_check_mark: Company name and VAT Id should be visible

8. Go to the payments step

**Actual Result:** :heavy_multiplication_x: Company name and VAT Id are not visible 

Screenshot from 2021-01-15 09-44-46

**Expected Result:** :heavy_check_mark: Company name and VAT Id should be visible

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31439: Region data fix

### PR DESCRIPTION
**Pull request by rav-redchamps**
### Description (*)

Adding the company and VAT Number values at OPC address.

### Related Pull Requests
https://github.com/magento/partners-magento2b2b/pull/538

### Fixed Issues (if relevant)

N/A

### Manual testing scenarios (*)

   1. Enable showing company and VAT Number data at the front
   2. Check if it is available at OPC.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [ ] resolves magento/magento2#31439: Region data fix

### Resolved issues:
1. [x] resolves magento/magento2#31652: Adding the company and VAT Number values at OPC address.

### CODE REVIEW

**Comment by rav-redchamps** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento create issue

**Review by sidolov — CHANGES_REQUESTED** [review]
@rav-redchamps please, cover changes with an automated test. Thanks!

**Comment by engcom-Hotel** [comment]
Hello @rav-redchamps,
The fix already exists at https://github.com/magento/magento2/pull/27608
So, we may continue the current PR partially.
Like 'adding the company and VAT Id values at the checkout'.
Steps to reproduce:
Magento version: 2.4-develop
PHP version: 7.4
ElasticSearch version: 7
MySQL version: 8.0
1. Apply the fix from https://github.com/magento/magento2/pull/27608 if it is not merged yet
2. bin/magento se:up
3. Set Store->Configuration->Customer Configuration-> Name & Address Options->Show Address Information to 'Yes'
3. Set Store->Configuration->Customer Configuration->Create New Account Options->Show VAT Number on Storefront to 'Yes'
4. bin/magento c:c
5. Open registration page <domain>/customer/account/create/
5. Create the customer with the company name and VAT Id (add id from the account after creation if https://github.com/magento/magento2/pull/31321 not merged yet)
6. Add any product to the cart and check if company name and VAT Id are visible at checkout/#shipping and checkout/#payment (both payment and shipment areas)
Thank you.

PS. I will help with the test coverage

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Comment by engcom-Hotel** [comment]
Hi @sidolov,
This PR is a duplicate of https://github.com/magento/magento2/pull/27608.
We can recreate the issue for "adding the company and VAT Number values at OPC" and update the priority for it.
Could you please have a look?
Thank you.

**Comment by sidolov** [comment]
@engcom-Hotel not sure how they are related, current PR going to display fields in case the address object has them and the second one aimed to support the region selector on the page

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Unit Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8628](https://jira.corp.magento.com/browse/ENGCOM-8628) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Set `Store->Configuration->Customer Configuration->Name and Address Options->Show Company` to 'Optional'
2. Set `Store->Configuration->Customer Configuration->Create New Account Options->Show VAT Number` on Storefront to 'Optional'
3. Save config
4. Run: `bin/magento cache:clean`
5. Open registration page /customer/account/create/
6. Create the customer with the company name and add VAT Number (admin->Customers->edit created customer->Addresses->Add/Update Address)
7. Add any product to the cart and go to the shipping step

**Before:** :heavy_multiplication_x: Company name and VAT Id are not visible 

Screenshot from 2021-01-15 09-44-31

**After:** :heavy_check_mark: Company name and VAT Id are visible



8. Go to the payments step

**Before:** :heavy_multiplication_x: Company name and VAT Id are not visible 

Screenshot from 2021-01-15 09-44-46

**After:** :heavy_check_mark: Company name and VAT Id are visible

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @rav-redchamps can you fix the conflicts? Thanks!

**Comment by rav-redchamps** [comment]
> Hi @rav-redchamps can you fix the conflicts? Thanks!

Hi @gabrieldagama,

Sorry, I can't see any details in the thread about the conflicts. May you please point my to the details, I will check it out & fix.

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

**Comment by Den4ik** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by Den4ik** [comment]
@engcom-Foxtrot Looks like after creating the product we should run reindex because product page is not available

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Comment by engcom-Charlie** [comment]
Hi @rav-redchamps, 

Thank you for your contribution.

I am working on the suggested review changes.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Comment by engcom-Charlie** [comment]
Thank you everyone for your contribution!

It seems that the review changes has been taken care with new MFTF test case.

I have tested the new MFTF test case and its working fine.

Also found that the test case which is failing in this build is not part of this PR. Its failing because of customer search is not working and not because of PR changes. So kindly asking for review again.

@engcom-foxtrot, I was about to merge the 2.4-develop branch to PR branch before passing it to review, but found that you have merge 2.4-develop-mainline into this branch. Curious to know why 2.4-develop-mainline was got merged.

**Comment by engcom-Charlie** [comment]
@engcom-Foxtrot can you please provide any details on this [comment](https://github.com/magento/magento2/pull/31425#issuecomment-917903854). It will be helpful to move this issue further.

Thank you!

**Comment by Den4ik** [comment]
@magento run all tests

**Pull request closed without merging**
