### PR TITLE
Pr 24526

### PR DESCRIPTION
**Pull request by zhartaunik**
…24526)

### Description (*)

I used event "save_commit_after" to do not prevent Rule object saving if something will be wrong with quote saving (customer may have too many quotes with applied described rule)

### Fixed Issues (if relevant)

1. magento/magento2#24526: quote_item.applied_rule_ids not updated after disabling cart price rule

### Manual testing scenarios (*)

1. Create new rule
2. Add product to cart
3. Disable rule
4. Reload cart

### Contribution checklist (*)
 - [*] Pull request has a meaningful description of its purpose
 - [*] All commits are accompanied by meaningful commit messages
 - [*] All new or changed code is covered with unit/integration tests (if applicable)
 - [*] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by zhartaunik** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @zhartaunik. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @zhartaunik, here is your [new Magento instance](https://pr-24877.instances.magento-community.engineering).
Admin access: [https://pr-24877.instances.magento-community.engineering/admin](https://pr-24877.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by zhartaunik** [comment]
Will be replaced with another PR

**Pull request closed without merging**
