### PR TITLE
Removed extra line from class declaration

### PR DESCRIPTION
**Pull request by patelnimesh1988**
### Description
Removed extra line from class declaration

### Fixed Issues (if relevant)
1. N/A

### Manual testing scenarios
1. N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=15278) <br/>All committers have signed the CLA.

**Comment by orlangur** [comment]
Hi @patelnimesh1988, thanks for your contribution but it does not seem to bring significant value to justify overhead of PR processing as to me.

Such empty line is allowed by PSR-2 and additional Magento 2 coding style.

For the sake of consistency, would be really nice if you find a way to remove such lines all over the code automatically and enforce with `php-cs-fixer` or something.

**Comment by patelnimesh1988** [comment]
Hi @orlangur I will run php-cs-fixer and commit changes.
Thank You

**Comment by patelnimesh1988** [comment]
Hi @orlangur , I have installed and run php-cs-fixer command. This command fixed PSR-1 and PSR-2 issues. This a command has made changes in many files. I am currently reviewing those files.
Can I generate module wise pull request?
It will be easy for me and you to review code.
Please reply me as soon as possible. I am waiting for your reply.
That command also made changes in dev, lib, and setup folder files also. Can I generate pull request for those folder files?
Thank You.

**Comment by orlangur** [comment]
@patelnimesh1988 you don't need to fix anything besides your suggested change. So, you need to use existing tools or create a new fixer for `php-cs-fixer` which would allow to remove such empty lines.

**Pull request closed without merging**
