### PR TITLE
Fixed #18508: collect-totals API call not updating the selected shippingMethod

### LINKED ISSUE #18508: collect-totals API call not updating the selected shippingMethod
If you use the API endpoint 
```java
PUT /V1/guest-carts/{cartId}/collect-totals
{code}
 on an empty quote it all goes fine. But if you want to update the endpoint again to update the shippingMethod the old ShippingMethod is used for the totals.

### Preconditions
2.2.3

### Steps to reproduce
1. Call the PUT /V1/guest-carts/{cartId}/collect-totals endpoint with this data:
{code}
{"shippingMethodCode":"flatrate","shippingCarrierCode":"flatrate","paymentMethod":{"method":"checkmo"}}
{code}
1. Call the PUT /V1/guest-carts/{cartId}/collect-totals endpoint with this data:
{code}
{"shippingMethodCode":"freeshipping","shippingCarrierCode":"freeshipping","paymentMethod":{"method":"checkmo"}}
```

### Expected result
1. Totals are updated with the new shippingMethod

### Actual result
1. Totals are from the old shippingMethod.

It looks like it has to do that on the second call the setShippingAssignments() is not updated and this causes that the totals are using the old shippingMethod.

### PR DESCRIPTION
**Pull request by ramkishansuthar**
### Description (*)

Replaced $this->quoteRepository->save($quote->collectTotals()); with $quote->collectTotals() at set method function in Magento\Quote\Model\ShippingMethodManagement.

### Fixed Issues (if relevant)

1. magento/magento2#18508: collect-totals API call not updating the selected shippingMethod.

### Manual testing scenarios (*)

1. Checked it with multiple shipping methods.
2. Checked it with different payment methods in request payload.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ramkishansuthar. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by ramkishansuthar** [comment]
@magento-engcom-team give me test instance - deploy test instance based on PR changes

**Comment by magento-engcom-team** [comment]
Hi @ramkishansuthar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @ramkishansuthar, here is your [new Magento instance](https://pr-20988.instances.magento-community.engineering).
Admin access: [https://pr-20988.instances.magento-community.engineering/admin](https://pr-20988.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by swnsma** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @swnsma. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @swnsma, here is your [Magento instance](https://i-20988-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20988-2-3-develop.instances.magento-community.engineering/admin](https://i-20988-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by swnsma** [comment]
Hi @ramkishansuthar,
Could you please check failed tests?

**Review by swnsma — CHANGES_REQUESTED** [review]
Hi @ramkishansuthar,
Could you please check failed tests?

**Comment by sidolov** [comment]
@ramkishansuthar , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
