### PR TITLE
Fix configurable dropdown showing tax incorrectly in 2.3-develop

### PR DESCRIPTION
**Pull request by danielpfarmer**
### Description (*)

This pull request addresses an issue described in #22270 and introduced in #17695.

The issue is that the price increase calculation was previously based upon the configurable basePrice vs the optionFinalPrice rather than the configurable finalPrice vs the optionFinalPrice. This meant that the tax amount was also been added to the price difference calculation for each of the configurable options incorrectly.

### Fixed Issues (if relevant)

1. magento/magento2#22270: 2.2.8 Configurable product option dropdown - price difference incorrect when catalog prices are entered excluding tax

### Manual testing scenarios (*)all Magento 2.

2. Set prices to be entered excluding tax in the configuration.
3. Apply product tax using tax rules.
4. Create a configurable product configurable by only one dropdown attribute (e.g colour or size)
5. Ensure that the product tax is not added for a second time in the dropdown attribute

### Contribution checklist (*)

 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22466) <br/>All committers have signed the CLA.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4809](https://jira.corp.magento.com/browse/ENGCOM-4809) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@danielpfarmer thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Comment by EvaldasDau** [comment]
Well this still doesn't solve the issue. Only the first item in the configurable product drop down is gets fixed.

**Comment by danielpfarmer** [comment]
@EvaldasDau can you give more detail / Steps to replicate? Cheers

**Comment by EvaldasDau** [comment]
@danielpfarmer Hey, thanks for reply.

We applied the changes to m2 2.3.1 store local installation, ran setup upgrade and cleaned cache.

Then when checking configurable products with drop down size options, noticed that the first option value was fixed; the + tax amount value no longer was displayed, however rest of the size options still had it.

**Pull request merged**
