### PR TITLE
Backend Module Manager disable icon fix.

### PR DESCRIPTION
**Pull request by SyntaxKay**
### Description (*)

Module Manager Disable Module icon doesn't display proper.
Magento 2.3 Develop

### Manual testing scenarios (*)

1. Loign to Backend -> system -> Web Setup Wizard -> Module Manager
2. Disable any module and check disable module icon 

### Actual Result (*)
actualscreenshot

### Expactced Result (*)
expectedscreenshot

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @speedy008. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by rogyar** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-21265.instances.magento-community.engineering).
Admin access: [https://pr-21265.instances.magento-community.engineering/admin](https://pr-21265.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-4298](https://jira.corp.magento.com/browse/ENGCOM-4298) has been created to process this Pull Request

**Pull request merged**
