### PR TITLE
LESS code clean up

### PR DESCRIPTION
**Pull request by Karlasa**
### Description (*)

LESS code clean up to follow coding standards

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @Karlasa. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by DanielRuf — CHANGES_REQUESTED** [review]
Removing `.lib-css` is not a good idea.

**Comment by DanielRuf** [comment]
https://magento.stackexchange.com/questions/94185/what-is-the-purpose-of-the-less-lib-css-mixin

Which removes duplicate and overwritten rules.

**Comment by DanielRuf** [comment]
Also `Update filename` is not a clear commit message. Please rebase and reword them.

**Comment by Karlasa** [comment]
@DanielRuf  Fixed some lib-css but for @indent/@font-weight it does not make sense having it as almost everywhere else it's called without it.

**Comment by DanielRuf** [comment]
> @DanielRuf Fixed some lib-css but for @indent/@font-weight it does not make sense having it as almost everywhere else it's called without it.

Why not? It is especially meant for variables and to merge rules and overwrite them without adding strikethrough rules on the browser side.

**Comment by Karlasa** [comment]
What do you mean by merge rules? 

> Why not?

if you have it without .lib-css() in 90% then i would never change it to false as i would end up cleaning up that 10% code but with 90% of incorrect code eg. padding: false/font-weight: false 
So it would make sense to clean it up. Also not having padding in or font-weight in site is quite strange case. i get .lib-css() if it's more specific variable. 
ex: 
@minicart-padding: @indent__s;
.lib-css(padding, @minicart-padding); 
would make sense for me as there are cases where you would like to disable it but not with that general variables

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3342](https://jira.corp.magento.com/browse/ENGCOM-3342) has been created to process this Pull Request

**Comment by Karlasa** [comment]
@VladimirZaets what is needed to be updated?

**Comment by VladimirZaets** [comment]
Hi @Karlasa, I add "Need update" label because Daniel had some question according to fix. I looked the fix, and I think it is ok. Thanks for collaboration.

**Comment by magento-engcom-team** [comment]
Hi @Karlasa. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
