### PR TITLE
Update elasticsearch lib to ~7.11.0 to support PHP8

### PR DESCRIPTION
**Pull request by hws47a**
### Description (*)

Update elasticsearch lib to ~7.11.0 to support PHP8

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/502

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31341

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hws47a** [comment]
@magento run Functional Tests CE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

In the report, we can see "Something went wrong" error. It feels like false positive

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Please resolve conflict

**Comment by hws47a** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Review by ihor-sviziev — APPROVED** [review]

**Pull request merged**
