### PR TITLE
Set of improvements for LoginAsCustomer modules

### LINKED ISSUE #29689: [Issue] Set of improvements for LoginAsCustomer modules
This issue is automatically created based on existing pull request: magento/magento2#29688: Set of improvements for LoginAsCustomer modules

---------
### Summary (*)
Magento 2.4-develop
PR contains a set of improvements for LoginAsCustomer modules.

- Replaced `around` plugin with `after`
- Removed redundant code
- Correctly used `isSetFlag` instead of `(bool)->getValue()`

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
PR contains a set of improvements for LoginAsCustomer modules.

- Replaced `around` plugin with `after`
- Removed redundant code
- Correctly used `isSetFlag` instead of `(bool)->getValue()`

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29689: Set of improvements for LoginAsCustomer modules

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento create issue

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@lbajsarowicz please review & fix static tests.

**Comment by lbajsarowicz** [comment]
@magento run Static Tests

@ihor-sviziev What I find amusing in this notification is that it enforces introducing arguments that are not necessary, so it also couples the Plugin to the interface that it is attached to, even if it's not necessary at all.

**Comment by ihor-sviziev** [comment]
> @ihor-sviziev What I find amusing in this notification is that it enforces introducing arguments that are not necessary, so it also couples the Plugin to the interface that it is attached to, even if it's not necessary at all.

Agree. Could you report it as separate issue?

**Comment by ihor-sviziev** [comment]
Failing static test is false positive as `Exception` is not `\Exception` in this case, it's imported on the top of the file. 
Just created issue on that https://github.com/magento/magento-coding-standard/issues/194

@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run all tests

Put an alias on the Exception

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8052](https://jira.corp.magento.com/browse/ENGCOM-8052) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked Login as Customer is enabled by default, disable extension, login as customer with Auto Detection/Manual Selection, login as customer from order view, invoice view, ship view and credit memo view pages
enable/disable Allow remote shopping assistance option for customer in backend/frontend

**Comment by engcom-Delta** [comment]
**Note:** Automation tests are passed

**Pull request merged**
