### PR TITLE
Sorted composer requirements alphabetically and updated packages with…

### LINKED ISSUE #38515: [Issue] Sorted composer requirements alphabetically and updated packages with…
This issue is automatically created based on existing pull request: magento/magento2#38491: Sorted composer requirements alphabetically and updated packages with…

---------
… known security vulnerabilities.

### Description (*)
This performs some maintenance to composer files:
- it sorts all requirements alphabetically, which wasn't the case (so it violated the `config > sort-packages` setting)
- it updates packages with known security vulnerabilities to the latest versions:
    - Upgrading composer/composer (2.6.6 => 2.7.1)
    - Upgrading phpseclib/phpseclib (3.0.35 => 3.0.37)

### Fixed Issues (if relevant)
None

### Manual testing scenarios (*)
1. Verify that all package requirements in the `composer.json` file are in alphabetical sort order
2. Run `composer audit` and verify no package versions have known security vulnerabilities

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by hostep**
… known security vulnerabilities.

### Description (*)
This performs some maintenance to composer files:
- it sorts all requirements alphabetically, which wasn't the case (so it violated the `config > sort-packages` setting)
- it updates packages with known security vulnerabilities to the latest versions:
    - Upgrading composer/composer (2.6.6 => 2.7.1)
    - Upgrading phpseclib/phpseclib (3.0.35 => 3.0.37)

### Fixed Issues (if relevant)
None

### Manual testing scenarios (*)
1. Verify that all package requirements in the `composer.json` file are in alphabetical sort order
2. Run `composer audit` and verify no package versions have known security vulnerabilities

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38515: Sorted composer requirements alphabetically and updated packages with…

### CODE REVIEW

**Comment by hostep** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento create issue

**Comment by engcom-Bravo** [comment]
Hi @hostep,

Internal team is working and deliver this fix in scope of 2.4.7

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @hostep,

The internal PR got merged in 2.4.7. It will be available to 2.4.7-develop once it will get publish. We will mention the commit revision once it will be available.

Thanks.

**Comment by engcom-Charlie** [comment]
As per [this](https://github.com/magento/magento2/pull/38491#issuecomment-2006078910), moving this in Merge in Progress for now.

**Comment by hostep** [comment]
Closing this PR, because it already got merged in https://github.com/magento/magento2/commit/e6fc0ca2d4f380951f606f15715c904b25ec9002, no idea why this PR isn't automatically marked as merged, but whatever, it's not really important

**Pull request closed without merging**
