### PR TITLE
Fixed Issue #20631 Console error on checkout after changing the allowed countries from admin

### PR DESCRIPTION
**Pull request by GovindaSharma**
### Description (*)
Fixed Issue #20631 Console error on checkout after changing the allowed countries from admin

### Fixed Issues (if relevant)

1. magento/magento2#20631: Console error on checkout after changing the allowed countries from admin

### Manual testing scenarios (*)

    1. Add a product to cart as guest.
   2. Fill the shipping address and reload the page now shipping address must be filled already.
   3. Go to Admin->Stores->configuration->General, Change allowed countries single one that is not  filled    on checkout. like i have filled United State at checkout and change allowed countries to Libya.
    4.Now reload the checkout shipping page again.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @GovindaSharma. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by okorshenko** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [Magento instance](https://i-20634-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20634-2-3-develop.instances.magento-community.engineering/admin](https://i-20634-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by okorshenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [new Magento instance](https://pr-20634.instances.magento-community.engineering).
Admin access: [https://pr-20634.instances.magento-community.engineering/admin](https://pr-20634.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by okorshenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @okorshenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, here is your [new Magento instance](https://pr-20634.instances.magento-community.engineering).
Admin access: [https://pr-20634.instances.magento-community.engineering/admin](https://pr-20634.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by okorshenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @okorshenko, thank you for the review.
[ENGCOM-4019](https://jira.corp.magento.com/browse/ENGCOM-4019) has been created to process this Pull Request

**Pull request merged**
