### PR TITLE
[MFTF] Refactoring AdminCancelTheCreatedOrderWithCashOnDeliveryPaymentMethodTest 

### LINKED ISSUE #33692: [Issue] [MFTF] Refactoring AdminCancelTheCreatedOrderWithCashOnDeliveryPaymentMethodTest
This issue is automatically created based on existing pull request: magento/magento2#33557: [MFTF] Refactoring AdminCancelTheCreatedOrderWithCashOnDeliveryPaymentMethodTest 

---------
The test is refactored to improve execution time

### PR DESCRIPTION
**Pull request by AnnaAPak**
The test is refactored to improve execution time

### Resolved issues:
1. [x] resolves magento/magento2#33692: [MFTF] Refactoring AdminCancelTheCreatedOrderWithCashOnDeliveryPaymentMethodTest

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Semantic Version Checker, Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by AnnaAPak** [comment]
@Den4ik sorry, but I'm marking the PR as WIP as I have found some issues in it.
Thanks.

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by AnnaAPak** [comment]
It is ready for be reviewed. Thanks.

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Integration Tests, Functional Tests B2B

**Review by Den4ik — APPROVED** [review]
✅ Failed B2B test is not related to changes

**Comment by engcom-Charlie** [comment]
:heavy_check_mark: QA Passed

The test case is working fine and green in build.  Please find the Allure report for the same.

**Actual Result:** :heavy_check_mark:
 1. There is a little decrease in the execution time of the test case compare to the old one.  

**After:** :heavy_check_mark:  
image

 
**Before:** :heavy_multiplication_x: 
image

**Comment by engcom-Charlie** [comment]
@magento create issue

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,  Functional Tests EE,  Functional Tests B2B

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Pull request merged**
