### PR TITLE
magento/magento2#18840: Invalid Unit Test Annotations.

### PR DESCRIPTION
**Pull request by swnsma**
### Description (*)
Fixed invalid unit tests annotations that assert exception messages. With these changes, unit tests will assert exception messages correctly
Backport to 2.2.
Fix commit in accordance to 2.2 exception messages.

### Fixed Issues (if relevant)
1. magento/magento2#18840: Invalid Unit Test Annotations

### Manual testing scenarios (*)
No manual testing neede. All changes are covered with unit tests

### Contribution checklist (*)
 - [] Pull request has a meaningful description of its purpose
 - [] All commits are accompanied by meaningful commit messages
 - [] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @swnsma. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by orlangur — CHANGES_REQUESTED** [review]
@swnsma this should be a backport preserving original commit author. Please fix it using force push.

**Comment by swnsma** [comment]
Author has been changed.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-3410](https://jira.corp.magento.com/browse/ENGCOM-3410) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @swnsma. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.

**Pull request merged**
