### PR TITLE
Wishlist-alignment-issue-at-mobile

### PR DESCRIPTION
**Pull request by priti2jcommerce**
### Description (*)
Wishlist alignment issue at mobile view
Magento 2.3.0

### Manual testing scenarios (*)

1. Add product into wishlist
2. check on mobile view

### Actual Screenshot (*)
2019-01-11_17-13_my wish list

### Expected Screenshot (*)
2019-01-11_17-14_my wish list

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by priti2jcommerce** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @priti2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by sivaschenko** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [Magento instance](https://i-20218-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20218-2-3-develop.instances.magento-community.engineering/admin](https://i-20218-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sivaschenko** [comment]
@priti2jcommerce thanks for your contribution. Deployer was temporarily unavailable. Now you can use it, please see the instance that I launched for you.

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3909](https://jira.corp.magento.com/browse/ENGCOM-3909) has been created to process this Pull Request

**Pull request merged**
