### PR TITLE
Solve custom option dropdown issue

### PR DESCRIPTION
**Pull request by dharmendra-wagento**
### Description (*)
Admin Customizable Options Dropdown sort_order issue

### Fixed Issues (if relevant)

1. magento/magento2#20989: Admin Customizable Options Dropdown sort_order issue

### Manual testing scenarios (*)
1. Go to Catalog > Products
2. Edit/New Product
3. Expand Customizable Options and click on Add Option
4. Choose Drop Dowm as New Option Type
5. Add 1 or 2 Values 
6 . Now , Change Option type from drop down to field or area
7. Now again choose Drop Dowm as Option Type
8. Add 1 or 2 Values 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @dharmendra-wagento. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20990) <br/>All committers have signed the CLA.

**Comment by dharmendra-wagento** [comment]
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dharmendra-wagento. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dharmendra-wagento, here is your [Magento instance](https://i-20990-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20990-2-2-develop.instances.magento-community.engineering/admin](https://i-20990-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dmytro-ch** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [new Magento instance](https://pr-20990.instances.magento-community.engineering).
Admin access: [https://pr-20990.instances.magento-community.engineering/admin](https://pr-20990.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-4150](https://jira.corp.magento.com/browse/ENGCOM-4150) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@dharmendra-wagento thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request merged**
