### PR TITLE
[MFTF] Test scenario for "Apply shopping cart rule to a single bundle item" (#28921)

### LINKED ISSUE #28921: Apply shopping cart rule to a single bundle item
### Preconditions (*)
Magento ver. 2.3.5-p1

### Steps to reproduce (*)
1. Create a bundle product with two option each contain two product in it
2. Create one option as main as the title with two simple product (a&b) - (Dropdown)
3. Create the second option as a sub as the title with two simple product(c&d)- (Checkbox)
4. Create a shopping cart rule 
5. Select a "percent of product price discount" 
6. Add 10 % to the discount amount 
7. We should add the main option two product in the rule like( SKU is one of (a&b)
8. Apply the rule 
9. Go to the frontend
10. Select one SKU from the dropdown of the main simple product and checkbox one sub simple product 
11. Add to cart
12. Go to cart page
13. Check the discount is applied total of two product

### Expected result (*)
10% discount is applied ONLY on BUNDLE child product SKU001 (this behavior worked faultless on Magento 1.8.X)
The discount should be applied only for the main simple product 
### Actual result (*)
10% discount is applied on BUNDLE parent product, thus both of simple products are discounted...
bundle_issue

Additional information
more detailed steps and screens #28921 ([Comment1](https://github.com/magento/magento2/issues/28921#issuecomment-651136449)) ([comment 2](https://github.com/magento/magento2/issues/28921#issuecomment-651167895))

### PR DESCRIPTION
**Pull request by zhartaunik**
Test scenario for "Apply shopping cart rule to a single bundle item" (#28921)

### Description (*)
Test scenario for the following bug:

1. Create a bundle product with two option each contain two product in it
2. Create one option as main as the title with two simple product (a&b) - (Dropdown)
3. Create the second option as a sub as the title with two simple product(c&d)- (Checkbox)
4. Create a shopping cart rule
5. Select a "percent of product price discount"
6. Add 10 % to the discount amount
7. We should add the main option two product in the rule like( SKU is one of (a&b)
8. Apply the rule
9. Go to the frontend
10. Select one SKU from the dropdown of the main simple product and checkbox one sub simple product
11. Add to cart
12. Go to cart page
13. Check the discount is applied total of two product

### Fixed Issues (if relevant)

MFTF test for this bug
1. Fixes magento/magento2#28921 

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [*] Pull request has a meaningful description of its purpose
 - [*] All commits are accompanied by meaningful commit messages
 - [*] All new or changed code is covered with unit/integration tests (if applicable)
 - [*] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by zhartaunik** [comment]
@magento run Functional Tests CE

**Comment by zhartaunik** [comment]
@magento run all tests

**Review by lbajsarowicz — APPROVED** [review]
Already reviewed that in other PR.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7933](https://jira.corp.magento.com/browse/ENGCOM-7933) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by slavvka** [comment]
@magento run all tests

**Review by slavvka — CHANGES_REQUESTED** [review]
Hey @zhartaunik @engcom-Alfa The functional test MC-16007: Add simple product to order from shopping cart test is failing constantly with your changes. Please fix it before we can merge it

**Comment by zhartaunik** [comment]
Hi @slavvka 
Could you please clarify how the only functional test may break adding simple product to cart?
As I analyzed MC-16007 test results - it refers to insufficient indexation, as on screenshot there no created customer found on the grid in adminarea.

**Comment by engcom-Charlie** [comment]
Hi @zhartaunik, please fix the falling test and we will be able to continue with your PR.

**Review by sidolov — APPROVED** [review]

**Pull request merged**
