### PR TITLE
Fix long string display horizontal scroll in all pages in admin

### PR DESCRIPTION
**Pull request by mageprince**
### Description (*)

Search with long string display horizontal scroll in all pages in admin

## Issue Screenshot
test simple product

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @mageprince. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by phoenix128 — APPROVED** [review]
Hello @mageprince ,
thank you for your contribution and your time.

**Comment by magento-engcom-team** [comment]
Hi @phoenix128, thank you for the review.
[ENGCOM-4385](https://jira.corp.magento.com/browse/ENGCOM-4385) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
Hi @mageprince , thanks for the pull request!

On the pull request code base, the long string still does not break goes beyond the page:

image

**Comment by mageprince** [comment]
@sivaschenko I have updated PR please check and approve changes.

**Comment by sivaschenko** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, here is your [new Magento instance](https://pr-21468.instances.magento-community.engineering).
Admin access: [https://pr-21468.instances.magento-community.engineering/admin](https://pr-21468.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-4385](https://jira.corp.magento.com/browse/ENGCOM-4385) has been created to process this Pull Request

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
