### PR TITLE
Changed array creation to be in line with the class

### LINKED ISSUE #28795: [Issue] Changed array creation to be in line with the class
This issue is automatically created based on existing pull request: magento/magento2#28515: Changed array creation to be in line with the class

---------
Make the array creation consistent throughout the class.
This is mostly just a convention fix.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by litsher**
Make the array creation consistent throughout the class.
This is mostly just a convention fix.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28795: Changed array creation to be in line with the class

### CODE REVIEW

**Comment by litsher** [comment]
@magento run all tests

**Comment by rogyar** [comment]
@magento run all tests

**Comment by rogyar** [comment]
@magento run Integration Tests

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7651](https://jira.corp.magento.com/browse/ENGCOM-7651) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@litsher thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

Was tested **Print** invoice functionality and everything work as previously (expected).

**Manual testing scenario:**
1. Create order with few products;
2. Create an invoice;
3. Go to Admin->Sales->Invoices;
4. Select **view** link on created before invoice;
5. Click on **Print** button;
6. Open created pdf file

Actual Result: :heavy_check_mark: Product names are displayed correctly

screenshot_67

**Pull request merged**
