### PR TITLE
magento/magento2#32384: Unused coupon marked as used 

### LINKED ISSUE #32384: Unused coupon marked as used
### Preconditions (*)

1. Magento 2.3.6 (I've checked code version for Magento 2.4 and it's the same) and minimum order amount limit set
2. Registered user
3. Coupon code with 1 use for customer and fixed discount amount

### Steps to reproduce (*)

1. Fill the cart up to the minimum order amount
2. Put the coupon to the cart just before the last checkout step, so the new total order amount is below minimum amount
3. Submit the order in the fastest way (i.e. I used payment-information API)

### Expected result (*)
1. The order is not placed, an error about minimum amount is shown
2. The coupon is still usable

### Actual result (*)
1. The order is not placed and an error about minimum amount is shown
2. The coupon is marked as used for the customer (in `salesrule_customer` ) and cannot be used again

Hint maybe:
The coupon is marked as used by `CouponUsagesIncrement`, a plugin to `beforeSubmit` of `QuoteManagement`. The quote validation is in `submitQuote`, nested to `submit`, so it is run after, and throws uncatched exceptions up to the frontend, so the database keeps the coupon as used. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by engcom-Foxtrot**
### Description (*)

Re-creation of https://github.com/magento/magento2/pull/32486

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32384

### Manual testing scenarios (*)

1. See magento/magento2#32384

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Review by orlangur — CHANGES_REQUESTED** [review]
Is it correct to assume that this PR just moves `try` instruction to the beginning of the method?

Please cover problematic case with integration test, unit test is not really useful here.

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

**Comment by engcom-Charlie** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Charlie** [comment]
Hi, Thank you everyone for the contribution.

In order to proceed with this issue, first I have tried to reproduce the issue on 2.4 develop branch and its not reproducible.

**Steps to follow:**
1. Setup Minimum order amount in admin. I setup to 300
2. Created a Coupon code  Apply: Fix amount discount, Discount Amount: 50 and  Uses per Customer: 1 these settings
3. Fill the cart up to the minimum order amount. I have added one product of 300
4. Just before the last checkout process, applied the coupon to the cart.
5. Submit the order

**Result**
After following the above steps,  the order is not placed and an error about minimum amount is shown. Ans we can still able to reproduce the coupon as its not considered as used.

To cross check further, I have removed the product from the cart and did logout and again followed the same steps. I can successfully able to apply that the same coupon since it was not set as used and on submit the order I can see the above error message again.

Note: In any of the case no entry has been getting inserted to salesrule_customer table.

image


@gixid192  and @Thundar, can you please cross check the issue once again and confirm on above whether its still reproducible or not.

Thank you in advance!

**Comment by Thundar** [comment]
@magento give me 2.4-develop instance

**Comment by Thundar** [comment]
@engcom-Charlie I could reproduce the error. 
I used the default user with the default coupon ("H20" for the bottle) for the testing environment. I just enable minumum amount with the value of 6.

Screenshot 2021-10-04 at 22 07 46

If I go back then to the cart page, I still cannot apply the H20 code. The order is not placed.

**Comment by engcom-Charlie** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Charlie** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Charlie** [comment]
Hi @Thundar,

Thanks for your reply.

After following the steps mentioned by you in your comment, we are still not able to reproduce the issue. 

It will be helpful, if you provide video recording of steps to reproduce of this issue to us, in order to proceed further with this issue.

Thank you!

**Comment by Thundar** [comment]
@engcom-Charlie here it is.
[video](https://wetransfer.com/downloads/e91fee56cc4feabeed72dd3b6f1fb0d620211006115434/6343003c48a518c5926fd81f0aada1ea20211006115449/6c93c3)
I hope it will help.

The link will be available for 7 days. Please tell me if you need more time.

**Pull request closed without merging**
