### PR TITLE
Resolve Mass Delete Subscribers doesn't have "confirm" message issue24248

### LINKED ISSUE #24248: Mass Delete Subscribers doesn't have "confirm" message
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Go to backend
2. Marketing->Newsletter Subscribers
3. Choose some subscribers
4. Choose mass action delete
5. Submit

### Expected result (*)

image

### Actual result (*)

1. Delete with no confirmation

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#24248: Mass Delete Subscribers doesn't have "confirm" message

### Fixed Issues (if relevant)

1. magento/magento2#24248: Mass Delete Subscribers doesn't have "confirm" message

### Manual testing scenarios (*)

1. Go to backend
2. Marketing->Newsletter Subscribers
3. Choose some subscribers
4. Choose mass action delete
5. Submit

#### Expected result 

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — COMMENTED** [review]
Is it possible to add there amount of selected subscribers? Would be great to have it

**Comment by edenduong** [comment]
> Is it possible to add there amount of selected subscribers? Would be great to have it

I think it is impossible because in `newsletter_subscriber_block.xml`, there is no way to get the number of selected.

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests build

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
> I think it is impossible because in `newsletter_subscriber_block.xml`, there is no way to get the number of selected.

Ok, let's leave as is for now. Later it could be improved.


There also were functional tests failures, but they looks not related at all.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5682](https://jira.corp.magento.com/browse/ENGCOM-5682) has been created to process this Pull Request

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5682](https://jira.corp.magento.com/browse/ENGCOM-5682) has been created to process this Pull Request

**Review by kalpmehta — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, thank you for the review.
[ENGCOM-5682](https://jira.corp.magento.com/browse/ENGCOM-5682) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
