### PR TITLE
Refactor: Swatches Helper / Remove misleading aliases, refactor the class

### LINKED ISSUE #31373: [Issue] Refactor: Swatches Helper / Remove misleading aliases, refactor the class
This issue is automatically created based on existing pull request: magento/magento2#31355: Refactor: Swatches Helper / Remove misleading aliases, refactor the class

---------
### Description (*)
The Helper contains extremely misleading import aliases.
Some of the elements were refactored.

### Fixed Issues (if relevant)
* [ x ] Misleading aliases

### Manual testing scenarios (*)
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
The Helper contains extremely misleading import aliases.
Some of the elements were refactored.

### Fixed Issues (if relevant)
* [ x ] Misleading aliases

### Manual testing scenarios (*)
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31373: Refactor: Swatches Helper / Remove misleading aliases, refactor the class

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests EE

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@magento create issue

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8559](https://jira.corp.magento.com/browse/ENGCOM-8559) has been created to process this Pull Request

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
@lbajsarowicz @ihor-sviziev,

Thank you for your collaboration & contribution!


:heavy_check_mark: QA Passed
Refactor of Swatches helper class has been done also misleading aliases have been removed.

**Manual Scenario Steps**
1. Gone through the PR changes, tested Swatches module
2. Created Swatch attribute and tested product listing, detail page


**After:** :heavy_check_mark: 
image



There are some build failures hence moving to `Extended Testing`

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
Fixed the static test failures and they its working fine now.

Related to current failing functional B2B, CE and EE tests, these are not failing because of this PR changes or not part of this PR. Hence moving it further on Merge in Progress.

**Functional B2B:**
image


**Functional CE:**
image

**Functional EE:**
image

Thank you!

**Pull request merged**
