### PR TITLE
[2.1-Develop] Fix for issue #5726

### PR DESCRIPTION
**Pull request by PieterCappelle**
Was fixed in 2.0.8 branch. Never got into 2.1-develop and 2.2-develop. Cherry-pick from 9fc059bc5b5432cadfd2f1cfa3cc2516e607e068

https://github.com/magento/magento2/issues/5726

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by okorshenko** [comment]
Hi @PieterCappelle 
Could you please check failed unit tests?

**Comment by PieterCappelle** [comment]
Finally fixed all the unittests :-)

**Comment by okorshenko** [comment]
Hi @PieterCappelle 
The QA team reported that GitHub issue #5726 is still reproducible on this branch. Could you please double check your fix. Thank you

**Comment by okorshenko** [comment]
Hi @PieterCappelle we are closing this PR for now. Please, reopen it once ready

**Pull request closed without merging**
