### PR TITLE
Mark exceptions as api

### LINKED ISSUE #32039: Mark Exceptions as API
The follwoing Exceptions should be marked as API in 2.4-develop branch

1. app/code/Magento/Checkout/Api/Exception/PaymentProcessingRateLimitExceededException.php
1. app/code/Magento/SalesRule/Api/Exception/CodeRequestLimitException.php

### PR DESCRIPTION
**Pull request by vlmed**
### Description (*)
The follwoing Exceptions marked as API:

1. app/code/Magento/Checkout/Api/Exception/PaymentProcessingRateLimitExceededException.php
2. app/code/Magento/SalesRule/Api/Exception/CodeRequestLimitException.php

### Fixed Issues (if relevant)
1. Fixes magento/magento2#32039

### Questions or comments
@coderimus 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by coderimus — CHANGES_REQUESTED** [review]
@vlmed thank you for the adjustments. There is one point explained to me: the `@since` will be set automatically during the merge. So, please, remove it :)

**Comment by vlmed** [comment]
@coderimus Thanks for the explanation. `@since` sections removed

**Review by coderimus — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @coderimus, thank you for the review.
[ENGCOM-8755](https://jira.corp.magento.com/browse/ENGCOM-8755) has been created to process this Pull Request
:eight_spoked_asterisk: @coderimus, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by coderimus** [comment]
@magento run all tests

**Comment by vlmed** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
Hi @vlmed can you recreate this PR to the `api-changes-develop` branch instead? Just make sure to create a new branch from this one and cherry-pick your commit.

Thanks!

**Comment by vlmed** [comment]
Hi @gabrieldagama. Done. https://github.com/magento/magento2/pull/33103

**Pull request closed without merging**
