### PR TITLE
Mark Framework Api interfaces #8

### LINKED ISSUE #32035: Mark Framework interfaces as API part 8
The following interfaces should be marked as API in 2.4-develop branch

1. lib/internal/Magento/Framework/View/Element/ComponentVisibilityInterface.php
1. lib/internal/Magento/Framework/View/Element/Message/InterpretationStrategyInterface.php
1. lib/internal/Magento/Framework/View/Element/Message/Renderer/PoolInterface.php
1. lib/internal/Magento/Framework/View/Element/Message/Renderer/RendererInterface.php
1. lib/internal/Magento/Framework/View/Element/UiComponent/BlockWrapperInterface.php
1. lib/internal/Magento/Framework/View/Element/UiComponent/Config/DomMergerInterface.php
1. lib/internal/Magento/Framework/View/Element/UiComponent/Config/FileCollectorInterface.php
1. lib/internal/Magento/Framework/View/Element/UiComponent/Config/UiReaderInterface.php
1. lib/internal/Magento/Framework/View/Element/UiComponent/ContainerInterface.php
1. lib/internal/Magento/Framework/View/Element/UiComponent/ContentType/ContentTypeInterface.php
1. lib/internal/Magento/Framework/View/Element/UiComponent/ContextInterface.php
1. lib/internal/Magento/Framework/View/Element/UiComponent/Control/ActionPoolInterface.php
1. lib/internal/Magento/Framework/View/Element/UiComponent/Control/ButtonProviderInterface.php
1. lib/internal/Magento/Framework/View/Element/UiComponent/Control/ControlInterface.php
1. lib/internal/Magento/Framework/View/Element/UiComponent/DataProvider/FilterApplierInterface.php
1. lib/internal/Magento/Framework/View/Element/UiComponent/DataSourceInterface.php
1. lib/internal/Magento/Framework/View/Element/UiComponent/Factory/ComponentFactoryInterface.php
1. lib/internal/Magento/Framework/View/Element/UiComponent/JsConfigInterface.php
1. lib/internal/Magento/Framework/View/Element/UiComponent/LayoutInterface.php
1. lib/internal/Magento/Framework/View/Element/UiComponent/ObserverInterface.php
1. lib/internal/Magento/Framework/View/Element/UiComponent/PoolInterface.php
1. lib/internal/Magento/Framework/View/Element/UiComponent/SubjectInterface.php

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Following interfaces marked as API 

lib/internal/Magento/Framework/View/Element/ComponentVisibilityInterface.php
lib/internal/Magento/Framework/View/Element/Message/InterpretationStrategyInterface.php
lib/internal/Magento/Framework/View/Element/Message/Renderer/PoolInterface.php
lib/internal/Magento/Framework/View/Element/Message/Renderer/RendererInterface.php
lib/internal/Magento/Framework/View/Element/UiComponent/BlockWrapperInterface.php
lib/internal/Magento/Framework/View/Element/UiComponent/Config/DomMergerInterface.php
lib/internal/Magento/Framework/View/Element/UiComponent/Config/FileCollectorInterface.php
lib/internal/Magento/Framework/View/Element/UiComponent/Config/UiReaderInterface.php
lib/internal/Magento/Framework/View/Element/UiComponent/ContainerInterface.php
lib/internal/Magento/Framework/View/Element/UiComponent/ContentType/ContentTypeInterface.php
lib/internal/Magento/Framework/View/Element/UiComponent/ContextInterface.php
lib/internal/Magento/Framework/View/Element/UiComponent/Control/ActionPoolInterface.php
lib/internal/Magento/Framework/View/Element/UiComponent/Control/ButtonProviderInterface.php
lib/internal/Magento/Framework/View/Element/UiComponent/Control/ControlInterface.php
lib/internal/Magento/Framework/View/Element/UiComponent/DataProvider/FilterApplierInterface.php
lib/internal/Magento/Framework/View/Element/UiComponent/DataSourceInterface.php
lib/internal/Magento/Framework/View/Element/UiComponent/Factory/ComponentFactoryInterface.php
lib/internal/Magento/Framework/View/Element/UiComponent/JsConfigInterface.php
lib/internal/Magento/Framework/View/Element/UiComponent/LayoutInterface.php
lib/internal/Magento/Framework/View/Element/UiComponent/ObserverInterface.php
lib/internal/Magento/Framework/View/Element/UiComponent/PoolInterface.php
lib/internal/Magento/Framework/View/Element/UiComponent/SubjectInterface.php

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32035

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

CC: @sivaschenko 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run WebAPI Tests, Database Compare

**Comment by ihor-sviziev** [comment]
@magento run Database Compare

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8758](https://jira.corp.magento.com/browse/ENGCOM-8758) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by mrtuvn** [comment]
@magento run Database Compare

**Comment by ihor-sviziev** [comment]
It seems like false positive

**Comment by mrtuvn** [comment]
@magento run Database Compare

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@mrtuvn, from the issue description:
> The following interfaces should be marked as API in 2.5-develop branch

Could you re-target the PR to 2.5-develop branch?

**Comment by mrtuvn** [comment]
oh my i thought this PR may have a change to delivery soon to 2.4 ?

**Comment by ihor-sviziev** [comment]
@mrtuvn Nope. all PRs from the API Changes project will be delivered in 2.5 release line as that's all backward incompatible change

**Comment by mrtuvn** [comment]
i have changed that back like before

**Comment by mrtuvn** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes from this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8758](https://jira.corp.magento.com/browse/ENGCOM-8758) has been created to process this Pull Request

**Comment by mrtuvn** [comment]
@gabrieldagama should I recreated new PR to 2.4-develop re-branch on this ?

**Comment by mrtuvn** [comment]
Re-targeted PR branch to 2.4-develop as internal discussed with @gabrieldagama

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Unit Tests, Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama the branch with code successfully imported into`magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-32070`.

**Pull request merged**
