### PR TITLE
Revert index.php in root magento

### PR DESCRIPTION
**Pull request by rogerdz**
### Description (*)

Fix error 404 when domain site point to root magento, some 3rd integration call url with index.php (example: https://magento.local/index.php/rest/V1/customers/search?searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bfield%5D=updated_at&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bvalue%5D=2023-09-28T12%3A53%3A16&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bcondition_type%5D=gteq&searchCriteria%5Bfilter_groups%5D%5B1%5D%5Bfilters%5D%5B0%5D%5Bfield%5D=updated_at&searchCriteria%5Bfilter_groups%5D%5B1%5D%5Bfilters%5D%5B0%5D%5Bvalue%5D=2023-09-28T13%3A53%3A16&searchCriteria%5Bfilter_groups%5D%5B1%5D%5Bfilters%5D%5B0%5D%5Bcondition_type%5D=lt&searchCriteria%5BsortOrders%5D%5B0%5D%5Bfield%5D=updated_at&searchCriteria%5BsortOrders%5D%5B0%5D%5Bdirection%5D=DESC&searchCriteria%5BcurrentPage%5D=1&searchCriteria%5BpageSize%5D=50)

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by hostep** [comment]
This makes little sense, the file `pub/index.php` should be loaded by that call. Your documentroot is configured to use `pub/`, right?

**Comment by rogerdz** [comment]
I see some hosting cant point domain to pub, then there will be a 404 error when reading the index.php file. So I think re-adding index.php will cover cases like this

**Comment by hostep** [comment]
It was removed because it's a lot better security-wise to only expose files from `pub` to the webserver instead of the entire application. A lot of php frameworks and applications work like that (symfony / laravel / akeneo / ...)
There may be some info in https://github.com/magento/magento2/issues/32285 that might help you further.

But what might also help, is to symlink the document root on your hosting to the `pub/` directory (if they allow that).

Also, in my opinion, if your hosting does not support this kind of setup, they are not looking into how the industry is evolving and you'd probably want to switch to another hosting that does support this...

**Pull request closed without merging**
