### PR TITLE
[MFTF] Updating with AdminClickInsertWidgetActionGroup

### LINKED ISSUE #31626: [Issue] [MFTF] Updating with AdminClickInsertWidgetActionGroup
This issue is automatically created based on existing pull request: magento/magento2#31601: [MFTF] Updating with AdminClickInsertWidgetActionGroup

---------
### Description (*)
Tests have been updated with AdminClickInsertWidgetActionGroup

### PR DESCRIPTION
**Pull request by AnnaAPak**
### Description (*)
Tests have been updated with AdminClickInsertWidgetActionGroup

### Resolved issues:
1. [x] resolves magento/magento2#31626: [MFTF] Updating with AdminClickInsertWidgetActionGroup

### CODE REVIEW

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Comment by AnnaAPak** [comment]
@magento run Functional Tests CE,Functional Tests EE,Functional Tests B2B, Semantic Version Checker

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8614](https://jira.corp.magento.com/browse/ENGCOM-8614) has been created to process this Pull Request

**Comment by sidolov** [comment]
@magento create issue

**Comment by engcom-Delta** [comment]
**Note:** QA not applicable

**Comment by engcom-Delta** [comment]
**Note:** Some tests are waiting for status

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Pull request merged**
