### PR TITLE
chore: remove support for IE 9 and IE 10

### PR DESCRIPTION
**Pull request by DanielRuf**
### Description

IE 9 and IE 10 are quite old and there is no support from MS anymore. Just IE 11 is supported until 2025.

Also we explicitely mention that we only support IE 11 and Edge, see https://devdocs.magento.com/guides/v2.0/install-gde/system-requirements_browsers.html and https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements_browsers.html 

### Fixed Issues (if relevant)

1. ...
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by miguelbalparda** [comment]
Very interesting PR, can you please check the failing tests while I check what the consensus on this one is?

**Comment by DanielRuf** [comment]
> can you please check the failing tests

Done.
https://travis-ci.org/magento/magento2/jobs/411618035#L1090

**Comment by BenGlassAtlas** [comment]
+1 The CSS for M2 never fully loaded in IE9 anyway so it makes a lot of sense to remove it - https://github.com/magento/magento2/issues/5126

**Review by miguelbalparda — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @miguelbalparda, thank you for the review.
[ENGCOM-2678](https://jira.corp.magento.com/browse/ENGCOM-2678) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Pull request merged**
