### PR TITLE
Mark Framework Api interfaces #7

### LINKED ISSUE #32034: Mark Framework interfaces as API part 7
The following interfaces should be marked as API in 2.4-develop branch:

1. lib/internal/Magento/Framework/Stdlib/DateTime/Timezone/LocalizedDateToUtcConverterInterface.php
1. lib/internal/Magento/Framework/TestFramework/Unit/Autoloader/GeneratorInterface.php
1. lib/internal/Magento/Framework/Translate/Inline/ProviderInterface.php
1. lib/internal/Magento/Framework/TranslateInterface.php
1. lib/internal/Magento/Framework/Url/ModifierInterface.php
1. lib/internal/Magento/Framework/Url/RouteParamsPreprocessorInterface.php
1. lib/internal/Magento/Framework/Validator/Constraint/OptionInterface.php
1. lib/internal/Magento/Framework/Validator/HTML/AttributeValidatorInterface.php
1. lib/internal/Magento/Framework/Validator/HTML/TagValidatorInterface.php
1. lib/internal/Magento/Framework/Validator/HTML/WYSIWYGValidatorInterface.php
1. lib/internal/Magento/Framework/View/Asset/ContentProcessorInterface.php
1. lib/internal/Magento/Framework/View/Asset/ContextInterface.php
1. lib/internal/Magento/Framework/View/Asset/LockerProcessInterface.php
1. lib/internal/Magento/Framework/View/Asset/MergeStrategyInterface.php
1. lib/internal/Magento/Framework/View/Asset/MergeableInterface.php
1. lib/internal/Magento/Framework/View/Asset/PreProcessor/FilenameResolverInterface.php
1. lib/internal/Magento/Framework/View/Design/Fallback/Rule/RuleInterface.php
1. lib/internal/Magento/Framework/View/Design/FileResolution/Fallback/ResolverInterface.php
1. lib/internal/Magento/Framework/View/Design/Theme/Customization/ConfigInterface.php
1. lib/internal/Magento/Framework/View/Design/Theme/Customization/FileAssetInterface.php
1. lib/internal/Magento/Framework/View/Design/Theme/Customization/FileInterface.php
1. lib/internal/Magento/Framework/View/Design/Theme/CustomizationInterface.php
1. lib/internal/Magento/Framework/View/Design/Theme/File/CollectionInterface.php
1. lib/internal/Magento/Framework/View/Design/Theme/FileInterface.php
1. lib/internal/Magento/Framework/View/Design/Theme/Image/PathInterface.php
1. lib/internal/Magento/Framework/View/Design/Theme/ResolverInterface.php
1. lib/internal/Magento/Framework/View/Design/Theme/ThemeProviderInterface.php

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Following interfaces marked as API

lib/internal/Magento/Framework/Stdlib/DateTime/Timezone/LocalizedDateToUtcConverterInterface.php
lib/internal/Magento/Framework/TestFramework/Unit/Autoloader/GeneratorInterface.php
lib/internal/Magento/Framework/Translate/Inline/ProviderInterface.php
lib/internal/Magento/Framework/TranslateInterface.php
lib/internal/Magento/Framework/Url/ModifierInterface.php
lib/internal/Magento/Framework/Url/RouteParamsPreprocessorInterface.php
lib/internal/Magento/Framework/Validator/Constraint/OptionInterface.php
lib/internal/Magento/Framework/Validator/HTML/AttributeValidatorInterface.php
lib/internal/Magento/Framework/Validator/HTML/TagValidatorInterface.php
lib/internal/Magento/Framework/Validator/HTML/WYSIWYGValidatorInterface.php
lib/internal/Magento/Framework/View/Asset/ContentProcessorInterface.php
lib/internal/Magento/Framework/View/Asset/ContextInterface.php
lib/internal/Magento/Framework/View/Asset/LockerProcessInterface.php
lib/internal/Magento/Framework/View/Asset/MergeStrategyInterface.php
lib/internal/Magento/Framework/View/Asset/MergeableInterface.php
lib/internal/Magento/Framework/View/Asset/PreProcessor/FilenameResolverInterface.php
lib/internal/Magento/Framework/View/Design/Fallback/Rule/RuleInterface.php
lib/internal/Magento/Framework/View/Design/FileResolution/Fallback/ResolverInterface.php
lib/internal/Magento/Framework/View/Design/Theme/Customization/ConfigInterface.php
lib/internal/Magento/Framework/View/Design/Theme/Customization/FileAssetInterface.php
lib/internal/Magento/Framework/View/Design/Theme/Customization/FileInterface.php
lib/internal/Magento/Framework/View/Design/Theme/CustomizationInterface.php
lib/internal/Magento/Framework/View/Design/Theme/File/CollectionInterface.php
lib/internal/Magento/Framework/View/Design/Theme/FileInterface.php
lib/internal/Magento/Framework/View/Design/Theme/Image/PathInterface.php
lib/internal/Magento/Framework/View/Design/Theme/ResolverInterface.php
lib/internal/Magento/Framework/View/Design/Theme/ThemeProviderInterface.php

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32034

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

CC @sivaschenko 
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by coderimus — CHANGES_REQUESTED** [review]
@mrtuvn  thank you for the adjustments. There is one point explained to me: the `@since` will be set automatically during the merge. Please, remove it :)

**Comment by mrtuvn** [comment]
Updated as your suggestion

**Comment by mrtuvn** [comment]
@magento run all tests

**Review by coderimus — APPROVED** [review]
Thank you @mrtuvn for the adjustments.

**Comment by magento-engcom-team** [comment]
Hi @coderimus, thank you for the review.
[ENGCOM-8760](https://jira.corp.magento.com/browse/ENGCOM-8760) has been created to process this Pull Request

**Comment by mrtuvn** [comment]
@magento run Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
Re-targeted PR branch to 2.4-develop as internal discussed with @gabrieldagama

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama the branch with code successfully imported into`magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-32069`.

**Pull request merged**
