### PR TITLE
Fix JS address converter function from mutating its argument

### PR DESCRIPTION
**Pull request by vaaralav**
### Description

Don't mutate the function's argument `addrs`.

### Fixed Issues (if relevant)

1. magento/magento2#13216: `quoteAddressToFormAddressData` mutates the argument

### Manual testing scenarios

1. Require `'Magento_Checkout/js/model/address-converter'` inside any JavaScript module.
2. Call `quoteAddressToFormAddressData` method with some `address`.
3. `address.street` should remain as an array. Eg. `['Sesame Street']`

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] ~All new or changed code is covered with unit/integration tests (if applicable)~
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=13217) <br/>All committers have signed the CLA.

**Review by omiroshnichenko — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-632](https://jira.corp.magento.com/browse/ENGCOM-632) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@vaaralav thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by magento-engcom-team** [comment]
@vaaralav thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Pull request merged**
