### PR TITLE
Duplicate Order Confirmation Emails for PayPal Express checkout order

### PR DESCRIPTION
**Pull request by ghost**
### Description

Duplicate Order Confirmation Emails PayPal

### Manual testing scenarios

1. Configure payment method PayPal Payments Pro with Express Checkout
2. Set Payment Action = Sale
Basic Settings - PayPal Payments Pro -> Payment Action = Sale
Basic Settings - PayPal Express Checkout -> Payment Action = Sale 
3. Go to frontend, create order with Express Checkout
### Actual result
 Customer gets two Order confirmation emails
### Expected result
Customer should get one Order confirmation email

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14820) <br/>All committers have signed the CLA.

**Comment by ishakhsuvarov** [comment]
Hi @rocketweb @syzovao 
Could you please sign [Contributor License Agreement (CLA)](https://cla.dev.magento.com/magento/magento2?pullRequest=14820) with the github account you have used for the commit in this PR? You may use link in the [comment above](https://github.com/magento/magento2/pull/14820#issuecomment-383569668) to sign.

Thank you

**Comment by ishakhsuvarov** [comment]
Thank you for signing!

**Comment by magento-engcom-team** [comment]
Hi @rocketweb. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

**Pull request merged**
