### PR TITLE
Issues #6382 - Image Swatch size

### PR DESCRIPTION
**Pull request by srenon**
### Description (*)
Not able to change swatch image size in custom theme

### Fixed Issues (if relevant)

1. magento/magento2#6382: Image Swatch size change not working

### Manual testing scenarios (*)

1. Create a custom theme, then try to change the swatch size. Since it sort alphabetically, theme name much start with a letter before "L" eg "customtheme"  

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=19844) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=19844) before we can accept your contribution.<br/>

**Comment by magento-engcom-team** [comment]
Hi @srenon. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by VladimirZaets** [comment]
Hi @srenon  , please, sign CLA, otherwise, we can't process your pull request

**Comment by pmclain** [comment]
@VladimirZaets This is a backport of https://github.com/magento/magento2/pull/13506 to `2.2-develop`.

**Comment by sidolov** [comment]
Hi @srenon , signed CLA still missing, I'm closing this PR due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
