### PR TITLE
MFTF: Admin Deletes CMS Page

### LINKED ISSUE #28202: [Issue] MFTF: Admin Deletes CMS Page
This issue is automatically created based on existing pull request: magento/magento2#28112: MFTF: Admin Deletes CMS Page

---------
This PR contains MFTF Test for deleting CMS page as Admin User
### Steps to reproduce (*)
1 - Login As Admin
2 - Navigate to CMS Pages grid
3 - Create New CMS Page
4 - Find Created CMS Page in grid
5 - Delete Created CMS Page
6 - Perform Assertions

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

### PR DESCRIPTION
**Pull request by DmitryTsymbal**
This PR contains MFTF Test for deleting CMS page as Admin User

Steps to reproduce:
1 - Login As Admin
2 - Navigate to CMS Pages grid
3 - Create New CMS Page
4 - Find Created CMS Page in grid
5 - Delete Created CMS Page
6 - Perform Assertions

### Resolved issues:
1. [x] resolves magento/magento2#28202: MFTF: Admin Deletes CMS Page

### CODE REVIEW

**Comment by dmytro-ch** [comment]
@magento run all tests

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7525](https://jira.corp.magento.com/browse/ENGCOM-7525) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Kilo** [comment]
Failed functional tests not related to the changes in this PR.

**Comment by slavvka** [comment]
@magento create issue

**Review by sdzhepa — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sdzhepa, thank you for the review.
[ENGCOM-7525](https://jira.corp.magento.com/browse/ENGCOM-7525) has been created to process this Pull Request

**Pull request merged**
