### PR TITLE
[Backport] Fixes from magento/magento2#15947

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description
In #15947 were added small fixes, this PR just backporting them, just to have the same versions between two release lines

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios
N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev

Unfortunately, we cannot accept Pull Requests from branches created in `magento2` repository.
Please use your own fork as a base for this Pull Request.

Thank you.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by ihor-sviziev** [comment]
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, here is your [Magento instance](https://i-18112-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18112-2-2-6.engcom.dev.magento.com/admin](https://i-18112-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Pull request closed without merging**
