### PR TITLE
No alert when user "Apply empty Coupon Code" in create new order form (issue 24015)

### LINKED ISSUE #24015: No alert when user "Apply empty Coupon Code" in create new order form
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Sales->Orders->Create New Order
3. Choose Customer, go to the Create New Order form
4. Add some product to cart
5. Click "Apply Coupon Code" without filling the field.

### Expected result (*)

1. Alert the notification 

### Actual result (*)

1. No alert, still send the request, and nothing happens

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#24015: No alert when user "Apply empty Coupon Code" in create new order form

Solution: Use alert modal in the case no coupon code.

### Fixed Issues (if relevant)

1. magento/magento2#24015: No alert when user "Apply empty Coupon Code" in create new order form

### Manual testing scenarios (*)

1. Go to backend
2. Sales->Orders->Create New Order
3. Choose Customer, go to the Create New Order form
4. Add some product to cart
5. Click "Apply Coupon Code" without filling the field.

#### Expected result 
1. Alert the notification 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-24016.instances.magento-community.engineering).
Admin access: [https://pr-24016.instances.magento-community.engineering/admin](https://pr-24016.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rogyar** [comment]
Hi @edenduong. Thank you for the improvement!

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-5552](https://jira.corp.magento.com/browse/ENGCOM-5552) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
Hi @edenduong those changes produce new issue with coupon code: coupon code cannot be removed when click on Remove Coupon Code icon
**Manual testing scenario:**

- Create Cart Price Rule with coupon code
- Create simple product
- Create customer
- Go Sales->Orders->Create New Order
- Choose customer
- Add simple product
- Enter valid coupon code to Apply Coupon Code filed and click Apply icon
- Now click on Remove Coupon Code icon
- :x: Alert notification "Attention Please enter a coupon code!" is shown and coupon code cannot be removed
image

**Comment by edenduong** [comment]
@engcom-Delta: I am sorry about that. I have resolved it, you can check it again.
@rogyar: Please review my changes. 

Thank you!

**Comment by edenduong** [comment]
@rogyar: Could you please review my new changes?

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5552](https://jira.corp.magento.com/browse/ENGCOM-5552) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Pull request merged**
