### PR TITLE
 #24635 Update Allure to fix GLOB_BRACE usage

### LINKED ISSUE #24635: Use of undefined constant GLOB_BRACE in dependency "allure-framework/allure-phpunit"
### Preconditions (*)
Magento Version: 2.3.2

### Steps to reproduce (*)

`./bin/magento dev:test:run unit`

### Expected result (*)
No PHP Warnings

### Actual result (*)

several:
```
Warning: Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' (this will throw an Error in a future version of PHP) in /var/www/html/src/vendor/allure-framework/allure-phpunit/src/Yandex/Allure/Adapter/AllureAdapter.php:74.
```

### Related Informations

Problem is, GLOB_BRACE is not available in alle Unix Systems.
For example the often in Docker context used "Alpine" 
https://github.com/docker-library/php/issues/719

There is an (not merged) upstream PullRequest available in https://github.com/allure-framework/allure-phpunit/pull/44
But I did not check yet, if this is the proper solution.

### PR DESCRIPTION
**Pull request by amenk**
Fixes #24635

this updates allure to fix the confirmed issue

### CODE REVIEW

**Comment by amenk** [comment]
@magento run all tests

**Comment by kandy** [comment]
see https://github.com/magento/magento2/pull/28375

**Comment by ihor-sviziev** [comment]
Hi @amenk ,
This is duplicate of https://github.com/magento/magento2/pull/28375
I'm closing this PR.

**Comment by ihor-sviziev** [comment]
Duplicates https://github.com/magento/magento2/pull/28375

**Comment by ihor-sviziev** [comment]
Duplicate of https://github.com/magento/magento2/pull/28375

**Pull request closed without merging**
