### PR TITLE
Fill visibility in AdminCreateConfigurableProductTest.xml

### PR DESCRIPTION
**Pull request by tdgroot**
### Description

Visiblity wasn't being filled in, leaving it to 'Not visible individually'. This resulted into the test failing, because the product wouldn't be visible on the storefront.

### Manual testing scenarios

1. Run the test

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by ishakhsuvarov** [comment]
Hi @tdgroot 
Please do not create new branches in `magento/magento2` for PR. You may submit from your own fork instead.
Thank you

**Comment by tdgroot** [comment]
@ishakhsuvarov It wasn't my intention to create a new branch in this repository, it probably happened because Magento team permissions aren't strict enough. Do I need to create a new pull request?

**Comment by ishakhsuvarov** [comment]
@tdgroot That would be perfect. Sorry for the confusion.

**Comment by tdgroot** [comment]
@ishakhsuvarov will do!

**Comment by tdgroot** [comment]
Created new pull request #14288

**Pull request closed without merging**
