### PR TITLE
Update Date.php

### PR DESCRIPTION
**Pull request by Maddesto**
currently works not correct for format \IntlDateFormatter::FULL (0)

### CODE REVIEW

**Comment by daim2k5** [comment]
Thank you for your contribution. Please accept the contributors license agreement so this PR can be further processed. This can be done by clicking the "Details" link next to the "license/cla" check below.

**Comment by mazhalai** [comment]
@Maddesto please sync with develop and rerun travis tests.

**Comment by piotrekkaminski** [comment]
@Maddesto are you able to sync with develop and rerun travis?

**Comment by piotrekkaminski** [comment]
Internal issue MAGETWO-54157

**Pull request merged**
