### PR TITLE
Add missing sentence delete category in the CSV file of catalog module

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

- Just add "Are you sure you want to delete this category?" to en_US.csv of Catalog module

### Fixed Issues (if relevant)

No issue. Just improve source code.

### Manual testing scenarios (*)

- 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-5549](https://jira.corp.magento.com/browse/ENGCOM-5549) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @edenduong !

I am not able to reproduce [this](https://github.com/magento/magento2/issues/24038) issue on fresh 2.3-develop instance.

**Manual testing scenario:**

1. Set developer mode (php bin/magento deploy:mode:set developer);
2. Add the line "Are you sure you want to delete this category?","bbbbbbbbbbbbbbbbbbb" to the csv file: app/code/Magento/Catalog/i18n/en_US.csv;
3. Refresh the cache: (php bin/magento cache:flush);
4. Go to backend;
5. Go to Catalog->Categories;
6. Add SubCategory - "Shoes" for example;
7. Click category "Shoes" in the category tree;
8. Click Delete;
9. View the message;

**Actual Result:**
The message displays: "bbbbbbbbbbbbbbbbbbb"
screen

@edenduong Could you take a look?

Thanks!

**Comment by edenduong** [comment]
Hello @engcom-Alfa, @swnsma : Thank you for your feedback. It is my mistake. I am sorry about that. The problems doesn't happen in 2.3-develop because the function which has no translate is deprecated and it doesn't affect to the system.

But I think we should add the sentence to the en_US.csv so the user can know and translate to their language.

Thank you !

**Comment by edenduong** [comment]
@engcom-Alfa, @swnsma: I have changed the description of this issue. Thanks !

**Comment by swnsma** [comment]
@edenduong, could you remove changes in app/code/Magento/Catalog/view/adminhtml/web/js/edit-tree.js then?

**Comment by edenduong** [comment]
@swnsma : I have changed the source code. You can check again. Thanks.

**Review by swnsma — APPROVED** [review]

**Comment by swnsma** [comment]
@edenduong, thank you for your changes!

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-5549](https://jira.corp.magento.com/browse/ENGCOM-5549) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
