### PR TITLE
Escape not verified

### PR DESCRIPTION
**Pull request by istiahailo**
### Description
 There were added the escape functions to prevent XSS issues.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @istiahailo. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on Pull Request changes
- `@magento-engcom-team give me new test instance` - deploy **NEW** test instance based on Pull Request changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy Vanilla Magento instance for Issue or Pull Request

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Review by phoenix128 — COMMENTED** [review]
Hello @istiahailo ,
I don't think you can inject any XSS attack in this case.
We are dealing with numbers only and internal ids.

When you find `escapeNotVerified`, it usually means that intentionally there is no escape in place.

**Comment by YevSent** [comment]
@phoenix128, actually you can inject XSS in the localization `__()` method for the language different to English.

`escapeNotVerified` annotation means that this file has not been checked yet. This annotation was added in time when we added escaping in HTML and it was used to don't break our CI with a lot of not verified files.
I think, you are talking about `noEscape` annotation, which does mean - there is no any data to escape.

**Comment by orlangur** [comment]
@joni-jones you can inject some JavaScript logic if you have access to translation files. This is not an "XSS".

> actually you can inject XSS in the localization `__()`

If it was true, there would be escaping inside `__`. We should have a strict rule to not escape `__` function output so that it is clear to everyone.

**Comment by YevSent** [comment]
> This is not an "XSS".

Why is it not XSS?

> We should have a strict rule to not escape __ function output so that it is clear to everyone.

No, we don't have such rule, so translations also should be escaped as other output data.

**Comment by orlangur** [comment]
@joni-jones,
> Why is it not XSS?

Please provide more details on the attacking vector, maybe I'm missing something. Just like adding custom JavaScript into product or category description, if you have somebody with access to your project files, "XSS" is your lesser problem.

> No, we don't have such rule, so translations also should be escaped as other output data.

Definitely we don't have (yet), but we MUST have such rule. There is no need to bloat all the code with `$escaper->escapeHtml(__('Some text'))`, if translations are supposed to be escaped (which I personally don't like), then escape them within `__` function and don't bloat the code. I remember there were few places with code like `__('Please <a href="someUrl">click</a>')` but it's better to fix such places instead of having `escapeHtml` everywhere.

**Comment by YevSent** [comment]
By default, we have translation files only for US locale, but some customer might occasionally upload a translation file with javascript code instead of phrase which should be translated for a different locale, in that case, without escaping, this code will be executed.

> then escape them within __ function and don't bloat the code

Now, this function is just a helper and not a part of the framework. In my opinion, the translation should be completely reworked because, now, IMHO, it looks very ugly. I think it should have similar functionality to localization like in Symfony or Yii frameworks.

> __('Please <a href="someUrl">click</a>')

This example shows the wrong translation usage because HTML should not be a part of the translation, also the URL should be escaped separately.

**Comment by phoenix128** [comment]
Hello @joni-jones ,
an XSS means you inject something provided as external parameter.

In this case there is no security issue involved, and translations **are allowed** to use non escaped contents. There is no threat here.

**Comment by YevSent** [comment]
Hi, @phoenix128, translation also could be provided from an external source. Someone adds javascript code to the translation CSV file.

We discussed such case with escaping translation when we were adding this escaping and decided to escape translations also because can't guarantee that there is not HTML or javascript in translation files.

Below, you can see a part of the escaping output design document which was approved by the product owner for this functionality:
```php
// Echo outputs, which don't fit XSS-safe naming conventions,
// are marked by  /* @escapeNotVerified */ annotation. It has been done by the tool.
<?php /* @escapeNotVerified */ echo $block->getTitle() ?>
<?php /* @escapeNotVerified */ echo $var;?>
<?php /* @escapeNotVerified */ echo __("text");?>
<?php /* @escapeNotVerified */ echo "Title: $title" ?>
<?php /* @escapeNotVerified */ echo "some text" . $block->getHtmlId();?>
<?php /* @escapeNotVerified */ echo  $var . $block->escapeUrl($var);?>

// If output don't need escaping then replace /* @escapeNotVerified */
// by /* @noEscape */ annotation.
<?php echo $block->escapeHtml($block->getTitle()) ?>
<?php echo $block->escapeHtml($var);?>
<?php echo $block->escapeHtml(__("text"));?>
<?php echo $block->escapeHtml("Title: $title") ?>
<?php /* @noEscape */ echo "some text" . $block->getHtmlId();?>
<?php /* @noEscape */ echo  $var . $block->escapeUrl($var);?>
```

**Comment by phoenix128** [comment]
Hello @joni-jones ,
I ask you to apologize me, but I am missing the point.

You are basically saying that you can inject a JavaScript by modifying a Magento translation file. But this is not an issue, because the translation system **MUST** be allowed to use HTML tags. If you are adding a script in your translation file is a bad behaviour and bad usage of the translation mechanism.

There is not XSS here and there is not any wrong behaviour from my point of view.
An XSS occurs when (for example) you pass a HTML content via GET/POST param.

If you have access to translation files to modify them, I think the escaping issue is not a real issue since you are able to directly modifiy a Magento file.

I can agree about the `noEscape` replacement in the place of `escapeNotVerified` in some of the cases you provided.

**Comment by YevSent** [comment]
@phoenix128, could you explain why translation must allow HTML tags? Translation mechanism about different locales not about output formatting in terms how it should look (CSS or HTML markup). In such case you could have different output formatting for different languages, is it correct?

**Comment by phoenix128** [comment]
Just an example you may find in the code:

```
__('Hello <strong>%1</strong>', [...])
```
or
```
__('Click <a href="...">here</a> to go somewhere')
```

Sometimes ordering and representation may change depending on the language.

**Comment by YevSent** [comment]
But these examples show bad design, the link or formatting should not be a part of the translation.

**Comment by phoenix128** [comment]
I assume your suggestion would be:

```
__('Click') . '<a href="...">' . __('here') . '</a>'
```

But this is wrong from may aspects, because in different languages you may need to switch the order of "click" and "here", or the meaning of the single pieces of translation may change in different contexts.

You will find many examples like the ones I gave to you in the Magento CSV translations.

**Comment by orlangur** [comment]
@joni-jones why `<?= /* @escapeNotVerified */ __('System Messages:') ?>` was added in the first place then? It all should have been added as `<?= $block->escapeHtml(__('System Messages:')) ?>`.

I see less than thousand `escapeHtml.*__` in code and almost 11k of `__\(`.

Again, if such escaping is planned, it should be implemented within `__`, otherwise it bloats client code. According to my understanding, no escaping should be fine here, necessary checks for risky code can be added to translation tool (so that `&lt;` is used in messages instead of `<`).

**Comment by orlangur** [comment]
> IMHO, it looks very ugly. I think it should have similar functionality to localization like in Symfony or Yii frameworks.

@joni-jones, yeah, this was personal (poor) decision by Anton Makarenko when everybody was against it. But until this hack is reworked, let's not make situation worser.

**Comment by YevSent** [comment]
Hi, @orlangur,
> why <?= /* @escapeNotVerified */ __('System Messages:') ?> was added in the first place then?

It has been done by the tool. Because we added a static test to verify new or changed `.phtml` files and at that moment we had a lot of views in the modules which should be verified. Each responsible core team should verify their modules but I don't know why it hasn't been done.

**Comment by phoenix128** [comment]
Hello @joni-jones ,
I am closing the issue for the PR itself, but I will bring this topic internally.

**Pull request closed without merging**
