### PR TITLE
Fixed breadcrumb quote issue in product page #15037

### PR DESCRIPTION
**Pull request by jignesh-baldha**
Fixed breadcrumb quote issue in product page #15037

### Description

I've fixed quote issue in breadcrumb in product view page.

### Fixed Issues (if relevant)

1. magento/magento2#15037: Product Details Page breadcrumbs cause syntax error on products containing quotes

### Manual testing scenarios

1. Add double quote in product name and check breadcrumb in product view page.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by vovayatsyuk — COMMENTED** [review]
Please double check if your patch is still needed in develop branch. Double quote was already escaped by code that you’ve removed in this PR. (It was added in recently: https://github.com/magento/magento2/pull/15162)

Additionally, you have removed html escaping. Can you comment on this?

**Review by vovayatsyuk — APPROVED** [review]

**Comment by sidolov** [comment]
Hi @jignesh-baldha , during QA activities we found that described issue was fixed in the scope of https://github.com/magento/magento2/pull/15162. Please, verify once again your steps in latest 2.2-develop.

**Comment by jignesh-baldha** [comment]
@sidolov I've removed deprecated function escapeJsQuote() and used escapeJs() which escape javascript context

**Comment by magento-engcom-team** [comment]
Hi @jignesh-baldha. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

Please, consider porting this solution across release lines.
You may use [Porting tool](https://github.com/magento/magento2/wiki/Simple-way-to-port-your-solutions-automatically) to port commits automatically.

**Comment by DanielRuf** [comment]
It is not fixed in 2.2.5.

**Comment by ci2014** [comment]
I confirm @DanielRuf 

It is not fixed yet.

**Comment by mohsinahmed22** [comment]
I also confirm its not fixed on 2.2.5

**Comment by Ctucker9233** [comment]
Code looks different in 2.2.7 so, maybe fixed? @magento-engcom-team can you confirm the version this fix was/will be released in?

**Pull request merged**
