### PR TITLE
Fix #13915

### LINKED ISSUE #13915: Filename Collisions with downloadable products
### Preconditions

1. Magento 2.4
### Steps to reproduce

1. Create a downloadable product and add a downloadable link and upload a file for the link with a filename on the local system like 'book.pdf'
2. Create a different downloadable produdt and add a downloadable link and upload a different file with the same name on the local system like 'book.pdf'
3. Each book.pdf is a different file with different contents possibly located on different places on the users computer when it is uploaded but has the same filename.

### Expected result

1. Each downloadable product will have a different file associated with it.

### Actual result

1. The last uploaded file replaces the existing file. So both downloadable products are associated with the same file. 

The problem is the uploader does not check to see if there is an existing file at the location it is trying to upload a file to but overrides it making the unexpected result. The media uploader doesn't seem to have this problem only downloadable product links and probably samples too.

### PR DESCRIPTION
**Pull request by faguilarp87**
### Fixed Issues (if relevant)

1. magento/magento2#13915: Filename Collisions with downloadable products

### Contribution checklist
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=13932) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=13932) before we can accept your contribution.<br/><hr/>**Felipe Aguilar** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by superdav42** [comment]
I think we also need to check the file storage database. At least it is done when uploading catalog images. So the relevant could I would use is:
```php
        if ($this->_coreFileStorageDatabase->checkDbUsage()) {
            $destFile = $this->_coreFileStorageDatabase->getUniqueFilename(
                $basePath,
                $file
            );
        } else {
            $destFile = dirname($file) . '/'
                . \Magento\MediaStorage\Model\File\Uploader::getNewFileName(
                      $this->_mediaDirectory->getAbsolutePath($this->getFilePath($basePath, $file))
                 );
        }
```

**Comment by rogyar** [comment]
Hello @faguilarp87. Please, sign CLA to move forward with this PR.
Thanks

**Comment by sidolov** [comment]
@faguilarp87 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for collaboration

**Pull request closed without merging**
