### PR TITLE
[FIXES] #25674: Elasticsearch version selections in admin are overly …

### PR DESCRIPTION
**Pull request by mautz-et-tong**
…broad.

### Description (*)
This removes the X.0+ notation and replaces it with X.x notation

### Fixed Issues (if relevant)

1. magento/magento2#25674: Elasticsearch version selections in admin are overly broad

### Manual testing scenarios (*)

1. Login to Admin
2. Go to Stores -> Configuration -> Catalog -> Catalog
3. Open Catalog Search Configuration
4. Check the entries in the dropdown "Search Engine"

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by davidverholen** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @davidverholen. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @davidverholen, here is your [new Magento instance](https://pr-25838.instances.magento-community.engineering).
Admin access: [https://pr-25838.instances.magento-community.engineering/admin](https://pr-25838.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by davidverholen — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @davidverholen, thank you for the review.
[ENGCOM-6364](https://jira.corp.magento.com/browse/ENGCOM-6364) has been created to process this Pull Request
:eight_spoked_asterisk: @davidverholen, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed 

Note: @mautz-et-tong You can also create a PR on the [magento/merchdocs](https://github.com/magento/merchdocs/pulls) repository to correct the X.0+ notation for the user documentation.

Thanks!

**Comment by engcom-Foxtrot** [comment]
@mautz-et-tong, thank you for the contribution. Please, cover changes by MFTF tests.

**Comment by mautz-et-tong** [comment]
@engcom-Foxtrot tell me please: what exactly should I cover with MFTF? Have you seen the PR? I switched comments and labels and stuff like that. Are there test failing now, because the comments and labels were checked? Or should I add tests to tests if the labels are now exactly in the new notation? I really don't know what do do here...

**Review by VladimirZaets — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
@mautz-et-tong Could you resolve merge conflicts?
Thanks!

**Review by davidverholen — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @davidverholen, thank you for the review.
[ENGCOM-6364](https://jira.corp.magento.com/browse/ENGCOM-6364) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
