### PR TITLE
Reducing space when there is no message on the page

### PR DESCRIPTION
**Pull request by rodrigoobiassi**
- There is an unnecessary fixed size in the message area that leaves the title very separate from the top

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @rodrigoobiassi. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3506](https://jira.corp.magento.com/browse/ENGCOM-3506) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@rodrigoobiassi thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by rodrigoobiassi** [comment]
Thanks guys, I already accepted Community Contributors team invitation.

**Comment by magento-engcom-team** [comment]
Hi @rodrigoobiassi. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
