### PR TITLE
Update ramsey/uuid to php8 compatible version

### LINKED ISSUE #31777: Update ramsey/uuid dependency to PHP 8 compatible version
In scope of the user story MC-41383 we need to 

Update ramsey/uuid dependency to PHP 8 compatible version (Branch dev-master is compatible with PHP 8 but not released yet)

In scope of this spice we need to estimate the effort required to do this upgrade.

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)

Right now not all dependencies are ready.
Issues:
- [allure-framework/allure-php-api:1.1.8](https://packagist.org/packages/allure-framework/allure-php-api#1.1.8) depends on `ramsey/uuid: ^3.0`. 
✔ Only version [allure-framework/allure-php-api:1.3.0](https://packagist.org/packages/allure-framework/allure-php-api#1.3.0) and above allow to install `ramsey/uuid: ^3 | ^4`
- [allure-framework/allure-phpunit:1.3.1](https://packagist.org/packages/allure-framework/allure-phpunit#1.3.1) depends on `allure-framework/allure-php-api: ~1.1.0`.
✔ There is available version [allure-framework/allure-phpunit:1.4.0](https://packagist.org/packages/allure-framework/allure-phpunit#1.4.0)
- [allure-framework/allure-codeception:1.4.4](https://packagist.org/packages/allure-framework/allure-codeception#1.4.4) depends on `allure-framework/allure-php-api: ~1.1.8`.
✔ There is available version [allure-framework/allure-codeception:1.5.0](https://packagist.org/packages/allure-framework/allure-codeception#1.5.0)
- magento/magento2-functional-testing-framework:3.4.0 depends on `allure-framework/allure-codeception:~1.4.0` that isn't compatible with version 1.5.0
🟡 There no available versions that support allure-framework/allure-codeception:1.5.0; 
    - ✔Fixed by https://github.com/magento/magento2-functional-testing-framework/pull/825, available in the `php8-develop` branch
    
    ❌ There no available versions that support PHP 8 - will be fixed in https://github.com/magento/magento2-functional-testing-framework/issues/826

 For now, I get it resolved using aliases. 
I executed following commands:
```bash
composer require ramsey/uuid allure-framework/allure-codeception:"1.5.0 as 1.4.5" allure-framework/allure-phpunit:"dev-master as 1.3.2" --update-with-dependencies
composer require --dev allure-framework/allure-codeception:"1.5.0 as 1.4.5" allure-framework/allure-phpunit:"dev-master as 1.3.2"
```

Also, I replaced in all places `Yandex\Allure\Adapter\AllureAdapter` with `Yandex\Allure\PhpUnit\AllurePhpUnit`, as class was renamed between these versions: https://github.com/allure-framework/allure-phpunit/compare/1.2.4..1.3.1

Requires MFTF changes from https://github.com/magento/magento2-functional-testing-framework/pull/825

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/538

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/31777

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Static Tests, Unit Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE, Integration Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
Update of allure-framework/allure-phpunit version https://github.com/magento/magento2/pull/31296

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Finally! we can update the `allure/allure-phpunit` package!
https://github.com/allure-framework/allure-phpunit/pull/52#issuecomment-818584950
https://packagist.org/packages/allure-framework/allure-phpunit

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Basically, this PR is waiting for:
- https://github.com/magento/magento2/pull/31296 - ❌ there should be fixed failing tests caused by class rename)
- MFTF release that will contain changes from https://github.com/magento/magento2-functional-testing-framework/pull/825 - ✔ so far, we can merge this PR even with installed MFTF from php8-develop branch and later on just switch to stable versino

**Comment by sivaschenko** [comment]
https://github.com/magento/magento2/pull/31296 is merged, I will update composer.json and lock and add the EE PR

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
dev-php8-develop version for MFTF can be reverted once new MFTF version is released including the codeception update. Internal ticket MQE-2641

**Comment by sivaschenko** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Comment by Den4ik** [comment]
@ihor-sviziev could you please resolve conflict

**Comment by sivaschenko** [comment]
@ihor-sviziev MFTF 3.5.1 is released. Updated the PR and rerunning the tests

@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run WebAPI Tests

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-9073](https://jira.corp.magento.com/browse/ENGCOM-9073) has been created to process this Pull Request
:eight_spoked_asterisk: @sivaschenko, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Pull request merged**
