### PR TITLE
Fix #26427 - Admin config section not expanded when fields are required.

### LINKED ISSUE #26427: Admin config section not expanded when fields are required.
### Preconditions (*)

1. Magento 2.3.3 / 2.3.2 Open Source

### Steps to reproduce (*)

1. Create a new module that adds new system configuration
2. In this system configuration add 2 group of fields
3. For first group make all fields not required
4. For second group make at least 1 field required
5. Go to that section in admin panel 
6. Make sure both sections are *not* expanded (by default they should not be)
7. Try to save system config

### Expected result (*)

1. System should expand tab with required fields and scrolls to it / them

### Actual result (*)

1. Nothing happens, from customer  / UX point of view system hangs and there is no error message

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This is fix for #26427 

### Fixed Issues (if relevant)

1. Fixes magento/magento2#26427: Admin config section not expanded when fields are required.

### Manual testing scenarios (*)

Check fixed issue for testing steps and expected result

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Bartlomiejsz** [comment]
@magento run all tests

**Review by dmytro-ch — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7619](https://jira.corp.magento.com/browse/ENGCOM-7619) has been created to process this Pull Request

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @Bartlomiejsz .

During testing, we faced the issue.

_**Problem:**_ Second config section not expanded when the inside field is required.

**Precondition:**

 Have 3 groups in the system configuration (_Test 1_ and _Test 3_ **required** for ex.)
Screenshot from 2020-06-05 12-43-32

**Manual testing scenario:**

1. Leave the values of the 3 groups blank;
2. Click on **Save** button;

**Actual Result:** :heavy_multiplication_x: Only the first tab expanded with required fields and scrolled to it, but the second tab is not expanded

Peek 2020-06-05 12-15

_Note:_ The second (**Test 3**) expands only if we fill in the first (**Test 1**). It would be more convenient if all the tabs were opened at once.

@Bartlomiejsz @dmytro-ch Could you take a look?

Thanks!

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7619](https://jira.corp.magento.com/browse/ENGCOM-7619) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Precondition:**

 Have 3 groups in the system configuration (_Test 1_ and _Test 3_ **required** for ex.)

Screenshot from 2020-06-05 12-43-32

**Manual testing scenario:**

1. Leave the values of the 3 groups blank;
2. Click on **Save** button;

**Before:** :heavy_multiplication_x: Nothing happens, from customer / UX point of view system hangs and there is no error message

Peek 2020-07-07 11-27

**After:** :heavy_check_mark: The system has expanded all tabs with empty required fields

Peek 2020-07-07 11-39

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Pull request merged**
