### PR TITLE
Added Fix in \Magento\Framework\Data\Collection\AbstractDb::getSelectCountSql() for group by clause

### PR DESCRIPTION
**Pull request by atishgoswami**
The collection getSize() does not return proper count of records if there is a INNER JOIN with GROUP BY clause.

Example:
Table foo:

```
+--------+-------------------------------------------------------+
| foo_id | title                                                 |
+--------+-------------------------------------------------------+
|      1 | Foo                                                   |
|      2 | Foo Two                                               |
|      3 | Foo Three                                             |
|      4 | Foo Four                                              |
+--------+-------------------------------------------------------+
```

Table foo_stores:

```
+--------+----------+
| foo_id | store_id |
+--------+----------+
|      1 |        0 |
|      2 |        0 |
|      3 |        0 |
|      4 |        0 |
|      1 |        1 |
|      2 |        1 |
|      3 |        1 |
|      4 |        1 |
+--------+----------+
```

I have followed the same convention of joining the 2 tables  as used in the magento cms module

``` php
    /**
     * Perform operations before rendering filters
     *
     * @return void
     */
    protected function _renderFiltersBefore()
    {
        $this->joinStoreRelationTable('foo_store', 'foo_id');
        parent::_renderFiltersBefore();
    }
```

``` php
    /**
     * Join store relation table if there is store filter
     *
     * @param string $tableName
     * @param string $columnName
     * @return void
     */
    protected function joinStoreRelationTable($tableName, $columnName)
    {
        if ($this->getFilter('store')) {
            $this->getSelect()->join(
                ['store_table' => $this->getTable($tableName)],
                'main_table.' . $columnName . ' = store_table.' . $columnName,
                []
            )->group(
                'main_table.' . $columnName
            );
        }
        parent::_renderFiltersBefore();
    }
```

In the front end i am using pager block and toolbar

The `getTotalNum()` method of the toolbar block which calls `$this->getCollection()->getSize()`
return wrong total count.

The sql generated by `getSelectCountSql()` called by `getSize()` is:

``` sql
SELECT
  COUNT(*)
FROM
  `foo` AS `main_table`
INNER JOIN
  `foo_store` AS `store_table` ON main_table.foo_id = store_table.foo_id
WHERE
  (store_table.store_id IN('1',  0))
GROUP BY
  `main_table`.`foo_id`
```

which returns:

```
+----------+
| COUNT(*) |
+----------+
|        2 |
|        2 |
|        2 |
+----------+
```

due to the group by clause

As the final result is fetched using `$this->getConnection()->fetchOne()` the result is always first record of the result set.

The fix checks for a GROUP BY and generates sql using `COUNT()` with `DISTINCT()` and resets the `GROUP BY`

``` sql
SELECT
  COUNT(DISTINCT main_table.foo_id)
FROM
  `foo` AS `main_table`
INNER JOIN
  `foo_store` AS `store_table` ON main_table.faq_id = store_table.faq_id
WHERE (store_table.store_id IN('1', 0))
```

### CODE REVIEW

**Comment by daim2k5** [comment]
Thank you for the PR! We are currently waiting for the travis builds to work again, which should happen in a few days. Once that is running and the tests are green we can continue to process your contribution.

**Comment by atishgoswami** [comment]
@daim2k5 thanks for the update.

**Comment by mazhalai** [comment]
@atishgoswami Please sync with develop and rerun builds.

**Comment by atishgoswami** [comment]
@mazhalai  Done

**Comment by mazhalai** [comment]
@atishgoswami can you please take a look at the failing tests?

**Comment by atishgoswami** [comment]
@mazhalai Ya sure, on it.

**Comment by atishgoswami** [comment]
@mazhalai Pushed the changes in the test case. Seems like the test suite passed now !

**Comment by atishgoswami** [comment]
@mazhalai Any updates regarding this PR ?

**Comment by dsikkema-magento** [comment]
Hi @atishgoswami, we've created an internal ticket to take a look at this.
Internal ticket: MAGETWO-49870

**Comment by atishgoswami** [comment]
@dsikkema thanks for the update.

**Pull request merged**
