### PR TITLE
12183 fix special price

### PR DESCRIPTION
**Pull request by krnshah**
### Description (*)

Resolve the special price issue for configurable product 
### Fixed Issues (if relevant)

1. magento/magento2#12183: fix special price
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @krnshah. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3382](https://jira.corp.magento.com/browse/ENGCOM-3382) has been created to process this Pull Request

**Comment by VladimirZaets** [comment]
Hi @krnshah. Thanks for collaboration. We can't reproduce the original issue on the 2.2-develop branch. If you still can reproduce issue please provide more details.

**Comment by sidolov** [comment]
Hi @krnshah , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Comment by krnshah** [comment]
Hi @VladimirZaets

Step to reproduce the bug :

-- Create configurable product and assign 2 or 3 simple products.
-- Set special price to the simple product. that lowest special price from configurable product should be shown in product listing page as As low as price and there should be shown regular price of that same product as well (you can see the simple product).

-- Expected result :


-- Actual result :

screenshot-10 16 16 93-2018 11 24-11-12-51

**Comment by krnshah** [comment]
As per the PR i have changed in app/code/Magento/ConfigurableProduct/view/base/templates/product/price/final_price.phtml this file.
-- There is one condition to check isProductList from product data. and it will set false statically so i have remove that condition (we dont need to check that condition for configurable product).
-- And set the value of is_product_list in an array so this will achieve our expected result.

**Comment by krnshah** [comment]
Hi @VladimirZaets,

I am facing error in travis, can you please help me out. i can't understand the issue.

**Comment by VladimirZaets** [comment]
Hi @krnshah. I think the travis failures don't related to your PR. I restarted Travis job.

**Comment by krnshah** [comment]
Hi @VladimirZaets 

Thank You, But still i am facing error in travis. What should i do further.

**Comment by sivaschenko** [comment]
Hi @krnshah I think you can ignore the Travis build result in this case, can you please port this pull request to `2.3-develop` as we'd like to merge this fix first to 2.3

**Comment by krnshah** [comment]
Hi @sivaschenko 
I have created PR for 2.3 #20726 
can you please review it.

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4675](https://jira.corp.magento.com/browse/ENGCOM-4675) has been created to process this Pull Request

**Comment by sidolov** [comment]
Hi @krnshah , PR to 2.3-develop branch was closed due to huge performance degradation: https://github.com/magento/magento2/pull/20726. 
I'm closing this PR as not actual. Please, re-open it if you find a different solution that eliminates performance degradation. 
Thank you for the collaboration!

**Pull request closed without merging**
