### PR TITLE
Advanced-Search-layout-not-proper

### PR DESCRIPTION
**Pull request by amol2jcommerce**
### Fixed Issues (if relevant)

1. magento/magento2#20809: Advanced Search layout not proper

### Manual testing scenarios (*)

1. Click Advanced Search link in footer

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4060](https://jira.corp.magento.com/browse/ENGCOM-4060) has been created to process this Pull Request

**Comment by VladimirZaets** [comment]
Hi @amol2jcommerce. Thanks for collaboration.
We check manually this case and found that behavior (width) is inconsistent on Contact Us form and Advanced Search pages on a tablet view (768 x 1024)

**Comment by amol2jcommerce** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce, here is your [Magento instance](https://i-20810-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20810-2-3-develop.instances.magento-community.engineering/admin](https://i-20810-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by amol2jcommerce** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce, here is your [new Magento instance](https://pr-20810.instances.magento-community.engineering).
Admin access: [https://pr-20810.instances.magento-community.engineering/admin](https://pr-20810.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=20810) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2?pullRequest=20810) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: amol2jcommerce<br/>:x: amol 2jcommerce<br/>:x: Amol Chaudhari<hr/>**amol 2jcommerce, Amol Chaudhari** seem not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by amol2jcommerce** [comment]
Hi @VladimirZaets I update branch & sign CLA. please review.

**Comment by amol2jcommerce** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @amol2jcommerce, here is your [new Magento instance](https://pr-20810.instances.magento-community.engineering).
Admin access: [https://pr-20810.instances.magento-community.engineering/admin](https://pr-20810.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by VladimirZaets** [comment]
@amol2jcommerce currently I see commits from two accounts (❌ amol 2jcommerce
❌ Amol Chaudhari ) that are not signed CLA

**Comment by amol2jcommerce** [comment]
Hi @VladimirZaets,  I closed this PR due to committed from two different accounts and that account didn't sign CLA. We generate New PR #21611 for this & sign CLA account.

**Pull request closed without merging**
