### PR TITLE
Changes in generating after updating composer.

### PR DESCRIPTION
**Pull request by RomaKis**
After updating composer classes are generating with "[]" instead of "array()".

This PR make tests green after composer updating.

### CODE REVIEW

**Review by orlangur — CHANGES_REQUESTED** [review]
```
-            "time": "2017-02-16 19:59:04"		 +            "time": "2017-02-16T19:59:04+00:00"
```

Looks like you used older version of Composer? Please rewrite branch using `vendor/bin/composer` instead.

**Comment by RomaKis** [comment]
@orlangur, I updated my composer version to the latest(1.6.3) on my local environment and run `vendor/bin/composer update`. Result is the same.

**Comment by ihor-sviziev** [comment]
@orlangur looks like someone already changed composer.lock to old version format, so these changes are correct

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-1232](https://jira.corp.magento.com/browse/ENGCOM-1232) has been created to process this Pull Request

**Review by orlangur — APPROVED** [review]

**Comment by RomaKis** [comment]
Closed as not relevant.

**Pull request closed without merging**
