### PR TITLE
Update credit-card-number-validator.js

### PR DESCRIPTION
**Pull request by justin-at-bounteous**
Changes:
- Remove: erroneous leading alternation, preventing space characters from being replaced
- Add: replace each contiguous string of space characters, for good measure

Issues Addressed:
- with the leading alternation present, whitespace is not removed and the credit card number always fails validation

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22493) <br/>All committers have signed the CLA.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-4826](https://jira.corp.magento.com/browse/ENGCOM-4826) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@justin-at-bounteous thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed

**Comment by nmalevanec** [comment]
Hello @justin-at-bounteous, this PR commit looks like has email which not from GitHub user. Could you please check this and sign CLA, to process your pull request?

**Comment by justin-at-bounteous** [comment]
Hi @nmalevanec, the user is myself. I made the commit through the GitHub interface. And afterward updated my username and email. That may have caused the issue.

**Comment by sidolov** [comment]
Hi @justin-at-bounteous , unfortunately, we can't accept the pull request with a commit that not associated with GitHub user. Please, make the new commit with your current email and force push the changes. Thank you!

**Comment by justin-at-bounteous** [comment]
Hi @sidolov , how about now? The commit has been revised. The author is now this proper github account

**Comment by sidolov** [comment]
@justin-at-bounteous perfect! thank you!

**Pull request merged**
