### PR TITLE
refresh-statistics-dropdown::Misaligned Refresh Statistics select dro…

### PR DESCRIPTION
**Pull request by yashwant2jcommerce**
…pdown

### Fixed Issues (if relevant)

1. magento/magento2 #20516:  Misaligned Refresh Statistics select dropdown

### Manual testing scenarios (*)

1. In Admin >> Reports >> Statistics >> Refresh Statistics

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @yashwant2jcommerce. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-3949](https://jira.corp.magento.com/browse/ENGCOM-3949) has been created to process this Pull Request

**Comment by VladimirZaets** [comment]
Hi @yashwant2jcommerce. Thanks for collaboration. 

Cannot reproduce issue described by PR on 2.3-develop.
Manual testing scenario:

Login to Admin panel;
Go to Reports->Statistics->Refresh Statistics
Refresh Statistics select dropdown shown with correct align

image

**Comment by yashwant2jcommerce** [comment]
@VladimirZaets , Yes i can see there is no alignment issue now on 2.3-develop branch.

**Pull request closed without merging**
