### PR TITLE
Fixed Notification counter issue

### PR DESCRIPTION
**Pull request by abrarpathan19**
Fixed Notification counter issue

### Description (*)
Getting issue while counter number in two digits.

### Fixed Issues (if relevant)

1. magento/magento2#23473: Notification counter design issue

### Manual testing scenarios (*)

1. Login to Magento admin dashboard.
2. Please review the attached screenshots.3. 
3. Getting issue while counter number in two digits.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rogyar. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rogyar, here is your [new Magento instance](https://pr-23476.instances.magento-community.engineering).
Admin access: [https://pr-23476.instances.magento-community.engineering/admin](https://pr-23476.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by rogyar** [comment]
Hi @abrarpathan19. Thank you for your collaboration. I'm not sure the proposed change fixes or improves the counter somehow. Please, check my comments in the original issue:

https://github.com/magento/magento2/issues/23473#issuecomment-507352314

Thank you

**Comment by sidolov** [comment]
@abrarpathan19 , I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
