### PR TITLE
Resolve Admin panel is not accessible after limited permissions set to at least one admin account issue25881

### LINKED ISSUE #25881: Admin panel is not accessible after limited permissions set to at least one admin account
### Preconditions (*)

Magento is installed

## Steps to reproduce (*)

- Login to admin panel
- Go to System->User Roles
- Create a new role:
- In Role Resources check only Media Gallery
image
- Create a new admin user account and assign the created role to it
- Log out from admin panel
- Log in to admin panel as a newly created user
- Log in to admin panel as an admin having full permissions

### Expected result (*)
The new admin user is logged into the admin panel.
Other admin accounts are not affected.

### Actual result (*)
User is redirected to frontend page with status code 404.
Admin panel is not available for other admins with full permissions
image

### Additional Info

The issue can be reproduced if admin user role includes only ACL resources that are not associated with page/menu item in the admin panel

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1.  Resolve magento/magento2#25881: Admin panel is not accessible after limited permissions set to at least one admin account

### Fixed Issues (if relevant)

1. magento/magento2#25881: Admin panel is not accessible after limited permissions set to at least one admin account

### Manual testing scenarios (*)

- Login to admin panel
- Go to System->User Roles
- Create a new role:
- In Role Resources check only Media Gallery
image
- Create a new admin user account and assign the created role to it
- Log out from admin panel
- Log in to admin panel as a newly created user
- Log in to admin panel as an admin having full permissions

#### Expected result
The new admin user is logged into the admin panel.
Other admin accounts are not affected.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by slavvka** [comment]
@magento run all tests

**Comment by slavvka** [comment]
@magento run Database Compare

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hi @edenduong,
great job, thank you for your contribution!
Could you please cover your fix by either Integration or Functional test?

**Comment by edenduong** [comment]
Hi @dmytro-ch:

I have just covered it by MFTF. Please check it again.

Thanks!

**Comment by dmytro-ch** [comment]
@edenduong, thank you for the updates!

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-6433](https://jira.corp.magento.com/browse/ENGCOM-6433) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @edenduong thanks for the pull request! Can you please explain how adding an additional controller is resolving the flaw of ACL algorithms?

I think that `Index` controller should be executed and render a page if the admin user does not have any other permissions

**Comment by edenduong** [comment]
Hi @sivaschenko: As I inspect, the if the user doesn't have the permission to access the resource, it will redirect the page to "admin/index/denied" page. 

image


But now, this page isn't existed because it doesn't have the action file "Denied" in folder "Index". It have only Denied.php file in folder Controller/Adminhtml. So it can not be run.

**Review by sivaschenko — APPROVED** [review]
Thanks for the explanation @edenduong !

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-6433](https://jira.corp.magento.com/browse/ENGCOM-6433) has been created to process this Pull Request

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Should we change the redirect to actually use the existing `\Magento\Backend\Controller\Adminhtml\Denied` ? What do you think about this @edenduong  ?

**Comment by edenduong** [comment]
Hi @sivaschenko: I am not sure if we can call Magento\Backend\Controller\Adminhtml\Denied by the url . Because follow the route/controller/action, it should be in the sub-folder in Adminhtml.

**Comment by engcom-Golf** [comment]
@edenduong  **NOTE:** Issue present only if Secret key to urls enable, if this option disabled, everything works as expected

**Comment by edenduong** [comment]
Hi @engcom-Golf: I tested it with Secret Key is enabled. And it can work.

**Comment by Nazar65** [comment]
@edenduong yes, but i'm talking about issue without your fix, redirect proceed correctly without secret key in url, so i think issue in this configuration

**Comment by sivaschenko** [comment]
@Nazar65 can you please provide exact steps of the issue you are referring to?

**Comment by Nazar65** [comment]
I mean that if we have secret key in url disabled that issue is not exist, so i think we need to fix root problem that related to this configuration.

**Comment by Nazar65** [comment]
@edenduong @sivaschenko can we just move "Denied" to the Index Folder ?  looks like "Denied" never used because 404 is shown if secret key disabled.

**Comment by dmytro-ch** [comment]
I guess, there is no case when the `\Magento\Backend\Controller\Adminhtml\Denied` class can be instantiated.
I was thinking of making the `Magento\Backend\Controller\Adminhtml\Denied` class be abstract.
It should be the most suitable way. Such change can be rather considered as a backward-compatible than just moving the class to another namespace. So it should not be a problem, especially taking into account the new release line.

@sivaschenko, @Nazar65 what do you think?

**Comment by engcom-Golf** [comment]
@dmytro-ch Making Denied class as abstract will be a backward compatible ? i think the best way is to approve acl const` ADMIN_RESOURCE = 'Magento_Backend::admin'` to failing `ControllerAclTest`

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-6433](https://jira.corp.magento.com/browse/ENGCOM-6433) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
@paliarush can you please approve the Static test fail: I believe we need the global ACL to be set to controller in this case

**Review by sivaschenko — APPROVED** [review]
MHI fail is not valid, the protected function is extending the parent function

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-6433](https://jira.corp.magento.com/browse/ENGCOM-6433) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by slavvka** [comment]
@engcom-Golf what was the reason of marking this PR as pending approval?

**Comment by Nazar65** [comment]
@slavvka To approve failed Health index

**Comment by slavvka** [comment]
> MHI fail is not valid, the protected function is extending the parent function

**Pull request merged**
