### PR TITLE
Add availability to leave empty config for events.xml

### PR DESCRIPTION
**Pull request by lisovyievhenii**
### Description (*)
The <config> node in events.xml file cannot have no any children nodes.

### Fixed Issue

magento/magento2#15931: events.xml cant have no childrens, others can [Magento 2.2.4]

### Manual testing scenarios (*)

1. Create new module
2. Create events.xml
3. Fill with only base node "<config>" without any children
4. Run ``php bin.magento cache:flush``

### Expected result
Upgrade + Flush + Clean should run fine trough, page is loading afterwards in developer mode

### Actual result
Cache Flush triggers the error:
```Error Message:
  [Magento\Framework\Exception\LocalizedException]                               
  Invalid XML in file /var/www/html/app/code/Vendor/Modulename/etc/events.xml:  
  Element 'config': Missing child element(s). Expected is ( event ).             
  Line: 2
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

Backport for: https://github.com/magento/magento2/pull/19146

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @lisovyievhenii. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.2-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by lisovyievhenii** [comment]
The branch name was incorrectly named. Don't pay attention on it

**Comment by arnoudhgz** [comment]
@magento-engcom-team please consider that this will make the code less strict. I already mentioned that in the issue that it is not really an issue. To me it makes no sense to make the code less strict, just for debugging.

**Comment by lisovyievhenii** [comment]
@arnoudhgz all other xsd schemas support an empty configuration. So it makes sense to add this fix into events.xsd schema, to make it similar to others

**Comment by arnoudhgz** [comment]
@lisovyievhenii I think the others should be made more strict... 

But it is not my call, I just want it here as a side note for the reviewer, since Magento never replied on my issues with this in the issue.

Sorry, accidentally clicked the close button, reopened again :+1:

**Comment by lisovyievhenii** [comment]
Could you please re-run tests or say why it was failed?

**Comment by rogyar** [comment]
I'm going to re-run the tests internally.

**Comment by magento-engcom-team** [comment]
Hi @lisovyievhenii. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.

**Pull request merged**
