### PR TITLE
magento/magento2#35952 Admin Users unable to change front-end Logo in Design Config when in Single Store Mode

### LINKED ISSUE #35952: Admin Users unable to change front-end Logo in Design Config when in Single Store Mode
### Preconditions and environment

M2.4.4

php8.1
nginx
Multi website store

### Steps to reproduce
1. Setup Multi website store
2. Design Config (Content -> Design -> Config) - Edit Store view level - upload image under Header and save
3. Cache clean
4. Enable Single Store Mode
5. Design Config (Content -> Design -> Config) - Edit for Website - Upload another image under Header and save 
6. Header tab expand -> Logo
7. Upload new logo file notdefaultlogo.jpg
8. flush caches 
9. reload front end 

### Expected result

Display the new uploaded logo, notdefaultlogo.jpg

### Actual result

Displays default fallback magento svg logo

### Additional information

Related to Scope and SingleStoreMode

`vendor/magento/module-theme/ViewModel/Block/Html/Header/LogoPathResolver.php`
Logo Path Resolver explicitly passes store scope

`    /**
     * Return logo image path
     *
     * @return string|null
     */
    public function getPath(): ?string
    {
        $path = null;
        $storeLogoPath = $this->scopeConfig->getValue(
            'design/header/logo_src',
            ScopeInterface::SCOPE_STORE
        );
        if ($storeLogoPath !== null) {
            $path = Logo::UPLOAD_DIR . '/' . $storeLogoPath;
        }
        return $path;
    }`
    
    Debugged:
    
`$this->scopeConfig->getValue('design/header/logo_src','store');`
returns: "stores/1/logo_1.png"
`$this->scopeConfig->getValue('design/header/logo_src','website');`
returns: "websites/1/notdefaultlogo.jpg"
`$this->scopeConfig->getValue('design/header/logo_src');`
returns: null

I did not mark as S0 severity, but I believe it is considering it is site identity(logo) and an admin user can not resolve this without disabling single store mode - which is not a real resolution to the issue.

Additionally it looks like single store mode and scope has been an ongoing issue across many items:
https://github.com/magento/magento2/issues/22344

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by monteshot**
### Description (*)

Fixes for case when application in single/multi store mode:
- Fixed issue with logo in single/multi store mode for Theme viewmodel
- Fixed issue with logo in single/multi store mode for Sales viewmodel

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35952

### Manual testing scenarios (*)

Use steps from https://github.com/magento/magento2/issues/35952#issuecomment-1221360474

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by monteshot** [comment]
@magento run all tests

**Comment by monteshot** [comment]
@magento run all tests

**Comment by monteshot** [comment]
@magento run all tests

**Comment by monteshot** [comment]
@magento run WebAPI Tests
@magento run Functional Tests EE

**Comment by monteshot** [comment]
@magento run Functional Tests CE
@magento run Functional Tests B2B

**Comment by monteshot** [comment]
@magento run WebAPI Tests,Functional Tests EE,Functional Tests B2B

**Comment by monteshot** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Magento Health Index

**Comment by monteshot** [comment]
@magento run Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE, Magento Health Index

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @monteshot,

Thanks for the contribution!

Please resolve the failed Magento Health Index test.

Thanks

**Comment by monteshot** [comment]
> Hello @monteshot,
> 
> Thanks for the contribution!
> 
> Please resolve the failed Magento Health Index test.
> 
> Thanks

@engcom-Hotel The Registry class is used in test class for mock creation. 

image 

How can I add these error in whitelist?

**Comment by engcom-Hotel** [comment]
Thanks @monteshot for the reply!

We had a discussion internally and as per the discussion, we can ignore the `Magento Health Index` test failure for these changes.

Hence moving this PR to `Ready for testing`.

Thanks

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**
- Design Config -> add Logo to StoreView & Save & Flush Cache
- Update store config and change to Single Store Mode (enabled)
- Design Config -> Add a new logo to the Website & Save & Flush Cache (storeview unavailable)
- Check logo in the frontend.

**Before:** :heavy_multiplication_x: 
Screenshot 2023-05-22 at 4 09 41 PM
Screenshot 2023-05-22 at 4 09 47 PM

**After:** :heavy_check_mark:  
Screenshot 2023-05-22 at 4 09 47 PM
image

Builds are failing. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
Functional Tests CE and Functional Tests EE failures are different on last two run on same commit. 
Functional Tests CE
Run1
image

Run2
image

Functional Tests EE
Run1
image

Run2
image

**Comment by engcom-Echo** [comment]
We have raised new internal approval request [JIRA](https://jira.corp.adobe.com/browse/AC-8833) for MHI failure. Waiting for approvals. 
Hence moving this to `Pending Approval`

Thank you!

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Integration Tests,Functional Tests CE, Functional Tests EE

**Comment by engcom-Echo** [comment]
@magento run Integration Tests,Functional Tests CE,Functional Tests EE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Comment by Viper9x** [comment]
Although this pull request has been merged, it will not be available until the next general releases are published, I created a custom composer patch file (`diff` file) for Magento and Adobe Commerce version 2.4.5 and higher using this pull request:
```
diff --git a/vendor/magento/module-sales/ViewModel/Header/LogoPathResolver.php b/vendor/magento/module-sales/ViewModel/Header/LogoPathResolver.php
index a640526517d47..d133388e4a4c1 100644
--- a/vendor/magento/module-sales/ViewModel/Header/LogoPathResolver.php
+++ b/vendor/magento/module-sales/ViewModel/Header/LogoPathResolver.php
@@ -54,9 +54,13 @@ public function getPath(): ?string
         if ($order instanceof Order) {
             $storeId = $order->getStoreId();
         }
+        $scopeType = ScopeInterface::SCOPE_STORE;
+        if ($this->scopeConfig->getValue('general/single_store_mode/enabled') === "1") {
+            $scopeType = ScopeInterface::SCOPE_WEBSITE;
+        }
         $salesLogoPath = $this->scopeConfig->getValue(
             'sales/identity/logo_html',
-            ScopeInterface::SCOPE_STORE,
+            $scopeType,
             $storeId
         );

@@ -66,7 +70,7 @@ public function getPath(): ?string

         $headerLogoPath = $this->scopeConfig->getValue(
             'design/header/logo_src',
-            ScopeInterface::SCOPE_STORE,
+            $scopeType,
             $storeId
         );

diff --git a/vendor/magento/module-theme/ViewModel/Block/Html/Header/LogoPathResolver.php b/vendor/magento/module-theme/ViewModel/Block/Html/Header/LogoPathResolver.php
index 1a10fe9177320..5be2cf9360ed4 100644
--- a/vendor/magento/module-theme/ViewModel/Block/Html/Header/LogoPathResolver.php
+++ b/vendor/magento/module-theme/ViewModel/Block/Html/Header/LogoPathResolver.php
@@ -39,9 +39,13 @@ public function __construct(
     public function getPath(): ?string
     {
         $path = null;
+        $scopeType = ScopeInterface::SCOPE_STORE;
+        if ($this->scopeConfig->getValue('general/single_store_mode/enabled') === "1") {
+            $scopeType = ScopeInterface::SCOPE_WEBSITE;
+        }
         $storeLogoPath = $this->scopeConfig->getValue(
             'design/header/logo_src',
-            ScopeInterface::SCOPE_STORE
+            $scopeType
         );
         if ($storeLogoPath !== null) {
             $path = Logo::UPLOAD_DIR . '/' . $storeLogoPath;

```
To apply this custom composer patch, I suggest using the **Vaimo Composer Patches plugin** https://github.com/vaimo/composer-patches. This plugin can apply the patch to multiple files within a `diff` file.

**Alternatively**, if you prefer to use the **Cweagans Composer Patches plugin** https://github.com/cweagans/composer-patches, you can refer to the official Adobe Commerce documentation at https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/patches/apply.html?lang=en#composer

As the **Cweagans Composer Patches** plugin does not support applying the patch to multiple files within a `diff` file, you'll need to create 2 separate `diff` files:
- The patch file for the `magento/module-theme` module's composer package:
```
diff --git a/vendor/magento/module-theme/ViewModel/Block/Html/Header/LogoPathResolver.php b/vendor/magento/module-theme/ViewModel/Block/Html/Header/LogoPathResolver.php
index 1a10fe9177320..5be2cf9360ed4 100644
--- a/vendor/magento/module-theme/ViewModel/Block/Html/Header/LogoPathResolver.php
+++ b/vendor/magento/module-theme/ViewModel/Block/Html/Header/LogoPathResolver.php
@@ -39,9 +39,13 @@ public function __construct(
     public function getPath(): ?string
     {
         $path = null;
+        $scopeType = ScopeInterface::SCOPE_STORE;
+        if ($this->scopeConfig->getValue('general/single_store_mode/enabled') === "1") {
+            $scopeType = ScopeInterface::SCOPE_WEBSITE;
+        }
         $storeLogoPath = $this->scopeConfig->getValue(
             'design/header/logo_src',
-            ScopeInterface::SCOPE_STORE
+            $scopeType
         );
         if ($storeLogoPath !== null) {
             $path = Logo::UPLOAD_DIR . '/' . $storeLogoPath;

```
- The patch file for the `magento/module-sales` module's composer package:
```
diff --git a/vendor/magento/module-sales/ViewModel/Header/LogoPathResolver.php b/vendor/magento/module-sales/ViewModel/Header/LogoPathResolver.php
index a640526517d47..d133388e4a4c1 100644
--- a/vendor/magento/module-sales/ViewModel/Header/LogoPathResolver.php
+++ b/vendor/magento/module-sales/ViewModel/Header/LogoPathResolver.php
@@ -54,9 +54,13 @@ public function getPath(): ?string
         if ($order instanceof Order) {
             $storeId = $order->getStoreId();
         }
+        $scopeType = ScopeInterface::SCOPE_STORE;
+        if ($this->scopeConfig->getValue('general/single_store_mode/enabled') === "1") {
+            $scopeType = ScopeInterface::SCOPE_WEBSITE;
+        }
         $salesLogoPath = $this->scopeConfig->getValue(
             'sales/identity/logo_html',
-            ScopeInterface::SCOPE_STORE,
+            $scopeType,
             $storeId
         );

@@ -66,7 +70,7 @@ public function getPath(): ?string

         $headerLogoPath = $this->scopeConfig->getValue(
             'design/header/logo_src',
-            ScopeInterface::SCOPE_STORE,
+            $scopeType,
             $storeId
         );

```

**Pull request merged**
