### PR TITLE
Issue #24225 fixed: FPT / Tax Totals Sorting Not Correct

### PR DESCRIPTION
**Pull request by mahesh-rajawat**
In this PR, FPT / Tax Totals Sorting Fixed.
### Description (*)

I have Fixed FPT sorting on order view, create invoice, invoice view, create creditmemo and creditmemo view in admin
### Fixed Issues (if relevant)

1. #24225

### Manual testing scenarios (*)

1. Enabled FPT.
2. FPT Sorting while creating new order from admin. https://prnt.sc/ozo832 
3. After order placed, https://prnt.sc/ozo8yy
4. On invoice view: https://prnt.sc/ozo9ev
5. On Credit Memo view: https://prnt.sc/ozoa6o

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by WinstonN** [comment]
@magento give me 2.3.2 instance

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5919](https://jira.corp.magento.com/browse/ENGCOM-5919) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @maheshWebkul721 

During testing we faced with the issue.

_Problem:_ In Order view **Total Tax** field is located above **Grand Total Excl. Tax**

**Actual Result:**
new

The same result and with **Invoice** and **Creditmemo**

@maheshWebkul721 Could you take a look, please?

Thanks!

**Comment by mahesh-rajawat** [comment]
@engcom-Alfa , i have fixed the Tax summary issue, also i have signed Adobe CLA successfully, but still this PR rejects.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5919](https://jira.corp.magento.com/browse/ENGCOM-5919) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @maheshWebkul721 

During testing, we faced the issue

**_Problem:_**  In the confirmation email, the order totals are incorrectly sorted

**Actual Result:**
after_email
 
The same problem occurs with **Invoice** and **Credit Memo** emails for **Guests** and for **Registered customers**

_**Note:**_ For order, the problem might be in the file `app/code/Magento/Weee/view/frontend/layout/sales_email_order_items.xml` in part `<argument name="condition" xsi:type="string">tax</argument>`

@maheshWebkul721 Could you, please, fix these problems in the scope of this PR?

Thanks!

**Comment by mahesh-rajawat** [comment]
@engcom-Alfa i will update it.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5919](https://jira.corp.magento.com/browse/ENGCOM-5919) has been created to process this Pull Request

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5919](https://jira.corp.magento.com/browse/ENGCOM-5919) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Pull request merged**
