### PR TITLE
[Forwardport] Introduce Block Config Source

### PR DESCRIPTION
**Pull request by thomas-kl1**
### Original Pull Request 
 https://github.com/magento/magento2/pull/16021

Add a new OptionSource of Blocks

### Description
Pages config source is useful to create custom configuration, for example to set page. The same for the block could be useful too.
So I suggest to add the blocks config source.

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @thomas-blackbird. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me {$VERSION} instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation

**Comment by osrecio** [comment]
Hi @thomas-blackbird ,Thanks for your contribution.

Can you check the error in [Travis](https://travis-ci.org/magento/magento2/jobs/415942466). ? 

You should add  `declare(strict_types=1);` for

```
app/code/Magento/Cms/Test/Unit/Model/Config/Source/BlockTest.php
app/code/Magento/Cms/Model/Config/Source/Block.php
```

You have mor information in [Technical Guidelines](https://devdocs.magento.com/guides/v2.2/coding-standards/technical-guidelines.html#1-basic-programming-principles)

> 1.3.1. All new PHP files MUST have strict type mode enabled by starting with declare(strict_types=1);. All updated PHP files SHOULD have strict type mode enabled.

Thanks!

**Comment by thomas-kl1** [comment]
Intégration test has failed. I can't see how it can be related. Please advise,

**Comment by osrecio** [comment]
The error is not related eith your PR, I will process ASAP.

Thanks @thomas-blackbird

**Comment by magento-engcom-team** [comment]
Hi @thomas-blackbird. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.0. 
Please check the release notes for final confirmation.

**Pull request merged**
