### PR TITLE
Add input-file argument to varnish:vcl:generate

### LINKED ISSUE #37363: [Issue] Add input-file argument to varnish:vcl:generate
This issue is automatically created based on existing pull request: magento/magento2#36538: Add input-file argument to varnish:vcl:generate

---------

This pull request allows us to pass in a path to a custom modified VCL file relative to the Magento root. This way, we can add our own custom VCL to our Git repo and generate it on deploy using a default Magento command.

### Manual testing scenarios (*)

1. Install clean Magento
2. Copy the core Varnish file into `app/etc`
3. Modify the file. For testing purposes, we append `# TEST`
4. Generate the VCL using the new `input-file` argument
5. The generated VCL is shown in stdout, and you should see `# TEST` at the end of the output of the previous command.

Copy & paste;

```
cp vendor/magento/module-page-cache/etc/varnish6.vcl app/etc/varnish6.vcl
echo "# TEST" >> app/etc/varnish6.vcl
bin/magento varnish:vcl:generate --input-file=app/etc/varnish6.vcl --export-version=6
```

### Questions or comments

If someone could tell me for which scenarios to write a unit test, I'll try to do my best.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by peterjaap**
This pull request allows us to pass in a path to a custom modified VCL file relative to the Magento root. This way, we can add our own custom VCL to our Git repo and generate it on deploy using a default Magento command.

### Manual testing scenarios (*)

1. Install clean Magento
2. Copy the core Varnish file into `app/etc`
3. Modify the file. For testing purposes, we append `# TEST`
4. Generate the VCL using the new `input-file` argument
5. The generated VCL is shown in stdout, and you should see `# TEST` at the end of the output of the previous command.

Copy & paste;

```
cp vendor/magento/module-page-cache/etc/varnish6.vcl app/etc/varnish6.vcl
echo "# TEST" >> app/etc/varnish6.vcl
bin/magento varnish:vcl:generate --input-file=app/etc/varnish6.vcl --export-version=6
```

### Questions or comments

If someone could tell me for which scenarios to write a unit test, I'll try to do my best.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37363: Add input-file argument to varnish:vcl:generate

### CODE REVIEW

**Comment by peterjaap** [comment]
TODO: add a timestamp to the output file when the output file was generated and which input-file was used.

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @peterjaap,

As per Magento's definition of done [here](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1), it would be nice if we can cover these changes with some kind of automated tests.

**Comment by peterjaap** [comment]
@engcom-Hotel agreed, go ahead!

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Unit Tests,WebAPI Tests,Functional Tests EE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Unit Tests,Functional Tests EE,Functional Tests CE

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Functional Tests B2B failures are different on last two run on same commit.
Run1
b2b-36538

Run2
b2b2-36538

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

- Same as in [comment](https://github.com/magento/magento2/pull/36538#issue-1465488667).

**Before:** :heavy_multiplication_x:  Getting error in the terminal.
Screenshot 2023-04-11 at 12 12 23 PM


**After:** :heavy_check_mark:  Successfully command got executed.
Screenshot 2023-04-11 at 12 21 13 PM

Screenshot 2023-04-11 at 12 21 24 PM

Bulds are failed. Hence, moving this PR to **Extended Testing**.

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Charlie** [comment]
@magento run Semantic Version Checker

**Comment by engcom-Charlie** [comment]
As the Semantic version Checker is failing, raised internal JIRA for the approval for the same. Once we get all the required approvals, we will move this PR further. Till that time, moving it to Pending Approval.

**Comment by peterjaap** [comment]
@engcom-Charlie any update?

**Comment by engcom-Charlie** [comment]
> @engcom-Charlie any update?



> Once we get all the required approvals, we will move this PR further. Till that time, moving it to Pending Approval.

Hi @peterjaap, we are still waiting for the required approvals. Once we get all the required approvals, we will move this PR further. 

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run Semantic Version Checker

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Functional Tests B2B

**Comment by engcom-Echo** [comment]
We have got approval for `Semantic Version Checker` and `WebAPI Tests` failure are not related to PR.
Functional Tests B2B failure are different on last two run on same commit.
Run1
Screenshot 2024-01-25 at 10 39 29 AM

Run2
Screenshot 2024-01-25 at 10 39 33 AM


Hence moving it to `Merge In Progress`

**Pull request merged**
