### PR TITLE
magento/magento2#37803: Customer order filters graphql

### LINKED ISSUE #37803: customer order filters graphql
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug
2.4.4

### Steps to reproduce

1.Create a new Module CustomerOrder.
2.Create a schema.graphqls in Teeela/CustomerOrder/etc/ folder to extend the CustomerOrderFilterInput.
Put following codes in this file:
```
input CustomerOrdersFilterInput @doc(description: "Identifies the filter to use for filtering orders.") {
    number: FilterStringTypeInput @doc(description: "Filters by order number.")
    created_at: FilterRangeTypeInput @doc(description: "Filters by created at.")
    status: FilterEqualTypeInput @doc(description: "Filters by status.")
}

input FilterRangeTypeInput @doc(description: "Defines a filter that matches a range of values, such as prices or dates.") {
    from: String @doc(description: "The beginning of the range")
    to: String @doc(description: "The end of the range")
}

input FilterEqualTypeInput @doc(description: "Defines a filter that matches the input exactly.") {
    in: [String] @doc(description: "An array of values to filter on")
    eq: String @doc(description: "A string to filter on")
}
```
3.Use the following payload and {{your URL}}/graphql to query the customer token.

```
mutation {
  generateCustomerToken(email: "{{your email address}}", password: "{{your password}}") {
    token
  }
}
```
4.Put above token in Postman Headers Authorization with Bearer {{your token}}.
5.Use following payload to query the above customer's sales orders.

```
query {
    customer {
    orders(filter: {  created_at: {  from: "2023-07-22"  }  status:{ in:["Processing"]} })
 { 
            items { 
                number  
                created_at 
            }
        }
    }

}
```

### Expected result

orders from 2023-07-22 and status Processing

### Actual result

all order processing and all order created from   2023-07-22

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by serbynskyi**
### Fixed Issue

1. Fixes magento/magento2#37803

### Manual testing scenarios (*)

1.Create a new Module CustomerOrder.
2.Create a schema.graphqls in Teeela/CustomerOrder/etc/ folder to extend the CustomerOrderFilterInput.
Put following codes in this file:

input CustomerOrdersFilterInput @doc(description: "Identifies the filter to use for filtering orders.") {
    number: FilterStringTypeInput @doc(description: "Filters by order number.")
    created_at: FilterRangeTypeInput @doc(description: "Filters by created at.")
    status: FilterEqualTypeInput @doc(description: "Filters by status.")
}

input FilterRangeTypeInput @doc(description: "Defines a filter that matches a range of values, such as prices or dates.") {
    from: String @doc(description: "The beginning of the range")
    to: String @doc(description: "The end of the range")
}

input FilterEqualTypeInput @doc(description: "Defines a filter that matches the input exactly.") {
    in: [String] @doc(description: "An array of values to filter on")
    eq: String @doc(description: "A string to filter on")
}
3.Use the following payload and {{your URL}}/graphql to query the customer token.

mutation {
  generateCustomerToken(email: "{{your email address}}", password: "{{your password}}") {
    token
  }
}
4.Put above token in Postman Headers Authorization with Bearer {{your token}}.
5.Use following payload to query the above customer's sales orders.

query {
    customer {
    orders(filter: {  created_at: {  from: "2023-07-22"  }  status:{ in:["Processing"]} })
 { 
            items { 
                number  
                created_at 
            }
        }
    }

```}

Result:
orders from 2023-07-22 and status Processing

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)


### Resolved issues:
1. [x] resolves magento/magento2#38371: magento/magento2#37803: Customer order filters graphql

### Resolved issues:
1. [x] resolves magento/magento2#38372: magento/magento2#37803: Customer order filters graphql

### CODE REVIEW

**Comment by shikhamis11** [comment]
@magento run all tests

**Comment by shikhamis11** [comment]
@serbynskyi thank you for your Pull request. Can you also cover your changes with the web API function test?

**Comment by venchiarutti** [comment]
Hey! take a look at this one: https://github.com/magento/magento2/pull/36949

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run WebAPI Tests, Static Tests, Integration Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @serbynskyi,

Thanks for the contribution!

The Changes looks good to me and the failed test seems flaky to me. But please cover the changes with some automated test in accordance with [DOD](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38079/29397ec99fd989b024c9847c8a93f915/Functional/allure-report-ce/index.html#categories).

Thanks

**Comment by engcom-Charlie** [comment]
Working on web API test coverage.

**Comment by engcom-Charlie** [comment]
@magento run Static Tests

**Comment by engcom-Charlie** [comment]
@magento run WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run Static Tests

**Comment by engcom-Charlie** [comment]
@magento run Static Tests, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, WebAPI Tests

**Comment by engcom-Charlie** [comment]
In discussion with Product Owner on this feature, till then moving it to On Hold.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@engcom-Hotel, the test coverage for customer order filter is present in Sales/CustomerOrders/CustomerOrdersTest.php Can you please have a look and do the needful.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Hotel** [comment]
@magento run WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run WebAPI Tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
It seems the WebAPI tests are failing due to PR changes. Please consider the last 3 build run reports for the reference:

- [Report 1](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38079/c0d40fb9342f78e17c7ac3ec315b4f64/WebApi/console-error-logs.html)
- [Report 2](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38079/b8eb337e058734ec2196b9d8cc0815e6/WebApi/console-error-logs.html)
- [Report 3](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38079/3d3391ab145ecfba48aa5c9ae8a4f02d/WebApi/console-error-logs.html)

**Comment by engcom-Charlie** [comment]
Moving this PR to testing as the web api failure is known open bug.

**Comment by engcom-Charlie** [comment]
It seems that bot moved it to Changes Requested,, moving it to Ready for testing.

**Comment by engcom-Echo** [comment]
@magento create issue

**Review by andrewbess — APPROVED** [review]
Hello @serbynskyi 
Thank you for contribution
Looks good for me
Approved

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
> @magento create issue

Hello @engcom-Echo 
The issue has already created (https://github.com/magento/magento2/issues/37803)
Let's avoid to create redundant ones

I'll close last one

**Comment by engcom-Echo** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

1. We have follow steps from [comment](https://github.com/magento/magento2/issues/37803#issue-1823856386)
Screenshot 2024-01-23 at 1 23 14 PM


**Before:** :heavy_multiplication_x: 
Screenshot 2024-01-23 at 1 23 06 PM


**After:** :heavy_check_mark:  
Screenshot 2024-01-23 at 1 24 56 PM


Builds are failing. Hence moving it to `Extended Testing`

**Comment by andrewbess** [comment]
Hey guys.
Sorry, but I missed [one comment in this PR](https://github.com/magento/magento2/pull/38079#issuecomment-1771137377)
It looks we already have [a similar PR](https://github.com/magento/magento2/pull/36949)

Which PR we need to choice for merging?
I think it should be https://github.com/magento/magento2/pull/36949
- it was created earlier
- it is more relevant due to has fixes for graphql.schema

What do you think @engcom-Hotel @shikhamis11 about my suggestion?

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
Hi @andrewbess,

Thank you for the [information](https://github.com/magento/magento2/pull/38079#issuecomment-1905692920)

We will take [#36949](https://github.com/magento/magento2/pull/36949) PR further as the schema changes are in place.

Till then keeping this PR to On Hold until https://github.com/magento/magento2/pull/36949 will get merge.

Thank you!

**Comment by engcom-Charlie** [comment]
As mentioned in [this](https://github.com/magento/magento2/pull/38079#issuecomment-1907449037) comment, the required changes has been taken care in https://github.com/magento/magento2/pull/36949 and it got merged in https://github.com/magento/magento2/commit/0a41d1aa0d5202a5116c5ceb553cc41b0e357b91 hence closing this PR now.

**Pull request closed without merging**
