### PR TITLE
Set default indexer mode to 'schedule'

### LINKED ISSUE #36419: [Issue] Set default indexer mode to 'schedule'
This issue is automatically created based on existing pull request: magento/magento2#36347: Set default indexer mode to 'schedule'
### Description

It is recommended that indexers be in the `schedule` ("Update by Schedule") mode, and not `realtime` ("Update on Save") mode. However, when Magento is installed for the first time, all indexers are by default in the "wrong" mode. This pull request changes the default for new indexers to be in the expected / recommended mode.

This change will not impact any existing indexers and therefore existing websites should not notice any impact from this change. If a module with an indexer is installed on an existing website, it will be created with the new default mode: {{{}schedule{}}}.
### Manual testing scenarios
1. Install Magento anew
1. Navigate in the admin to System -> Tools -> Index Management
1. Notice the colour of the "Mode" column. Before this change, these were all red, indicating an error/problem; after this change these are all green, indicating that all is well.

### PR DESCRIPTION
**Pull request by fredden**
### Description
[It is recommended](https://experienceleague.adobe.com/docs/commerce-admin/systems/tools/index-management.html#:~:text=As%20a%20best%20practice%2C%20we%20recommend%20that%20you%20use%20scheduled%20indexing.) that indexers be in the `schedule` ("Update by Schedule") mode, and not `realtime` ("Update on Save") mode. However, when Magento is installed for the first time, all indexers are by default in the "wrong" mode. This pull request changes the default for new indexers to be in the expected / recommended mode.

This change will not impact any existing indexers and therefore existing websites should not notice any impact from this change. If a module with an indexer is installed on an existing website, it will be created with the new default mode: `schedule`.

### Manual testing scenarios
1. Install Magento anew
1. Navigate in the admin to System -> Tools -> Index Management
1. Notice the colour of the "Mode" column. Before this change, these were all red, indicating an error/problem; after this change these are all green, indicating that all is well.
1. Install a module which adds indexers (such as `algolia/algoliasearch-magento-2`)
1. Navigate in the admin to System -> Tools -> Index Management
1. Notice the colour of the "Mode" column. Before this change, new indexers were all red, indicating an error/problem; after this change these are all green, indicating that all is well.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36419: Set default indexer mode to 'schedule'

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Lima** [comment]
As per PO confirmation prioritizing this PR as P1.

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run Unit Tests

**Comment by hostep** [comment]
Additionally - not sure if this is in scope of this PR - it would nice if an indexer definition could specify what its default mode should be the first time it gets setup. I seem to remember a particular 3rd party module from Amasty that comes with a couple of indexers where they strongly recommend to keep them set at 'Update on Save' (I can't find that recommendation anymore at the moment..., so not sure how needed this feature would be anymore, but maybe other modules have similar requirements?)

**Comment by fredden** [comment]
@hostep that sounds like a good feature to add. I see that as separate from (but related to) this pull request and https://github.com/magento/magento2/pull/34557 (where the preferred mode is shown in the admin - I specifically made `Magento\Indexer\Block\Backend\Grid\Column\Renderer\Scheduled::isPreferRealtime()` public there so it could be adjusted via plugin, but reading from an developer-defined preferred mode makes sense too).

**Comment by ihor-sviziev** [comment]
Hi @fredden,
AFAIK when you're changing the indexer mode from real-time to scheduled, Magento also creates triggers on needed tables. Will the need triggers be created automatically with your changes?

**Comment by fredden** [comment]
@ihor-sviziev that's a great question. I've tested this just now. I started with a fresh environment, checked out this branch, and ran `php bin/magento setup:install` with all the relevant flags.
Running `php bin/magento indexer:status` shows all indexers are in 'schedule' mode. Inspecting the database I can see that these indexers do have triggers set up as expected.

For example, `mysqldump` creates the following SQL statements among others:
```sql
DELIMITER ;;
/*!50003 CREATE*/ /*!50017 DEFINER=`magento2`@`%`*/ /*!50003 TRIGGER trg_catalog_category_entity_int_after_insert AFTER INSERT ON catalog_category_entity_int FOR EACH ROW
BEGIN
INSERT IGNORE INTO `catalog_category_product_cl` (`entity_id`) VALUES (NEW.`entity_id`);
END */;;
DELIMITER ;
```

**Comment by fredden** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Need to take care of the failed tests.

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@engcom-Hotel please can you help me with these test failures?

## Database Compare
From what I can tell, the complaint here is that an 'updated' timestamp has been changed. This seems like a false alert to me.

## Functional Tests B2B
> Unfortunately there's no build reports were generated. That may be caused by either infrastructure issues or fatal errors during the build run. Please address this issue to Community Engineering Team members.

## Functional Tests EE
> Unfortunately there's no build reports were generated. That may be caused by either infrastructure issues or fatal errors during the build run. Please address this issue to Community Engineering Team members.

## Functional Tests CE
There are many test failures, but I can't find any useful error messages. What's the problem with this test-suite?

## Integration Tests
The errors related to B2B & EE seem like failures to install the application properly. I'm not sure how to diagnose this.

I've tried to fix the errors for CE by running 'bin/magento indexer:reindex', but the build-in mechanism for this does not work within the test-suite. I'll try to investigate this further, but some help here would be appreciated.

## Sample Data Tests B2B
> Unfortunately there's no build reports were generated. That may be caused by either infrastructure issues or fatal errors during the build run. Please address this issue to Community Engineering Team members.

## Sample Data Tests EE
> Unfortunately there's no build reports were generated. That may be caused by either infrastructure issues or fatal errors during the build run. Please address this issue to Community Engineering Team members.

## Unit Tests
The failures here seem related to daylight saving time. I expect these errors will go away in ~6 days as that then the time "7 days ago" will be the same. This is a failure which is unrelated to this pull request.

## WebAPI Tests
This suffers from the same problems as "Integration Tests" above.

**Comment by fredden** [comment]
I've figured out how to run the integration test suites locally (see https://github.com/magento/magento2/issues/32252). I cannot reproduce the problems that the Adobe systems are reporting. @engcom-Hotel please can you pick this up internally and report back with your findings.

**Comment by engcom-Hotel** [comment]
Sure @fredden, Let me ask someone from the team to pick this PR.

Thanks

**Comment by rimple-saini** [comment]
@fredden Thank you fixing this issue.

It will be taken care into one of the Internal [JIRA ticket](https://jira.corp.adobe.com/browse/AC-6975). Once Internal PR will get merged, we will notify.

Thank you!

CC @ihor-sviziev @hostep

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
As mentioned in [above](https://github.com/magento/magento2/pull/36347#issuecomment-1473542100,) comment internal team is working on this PR. Internal team is working on some implementation level changes. Once the JIRA will get merge will notify it here.

Thank you!

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hello,

Internal Work in progress to fix the Automation tests. So far, All 3 types of MFTFs, Integration, WebAPI Tests are fixed.


Thanks.

**Comment by fredden** [comment]
@magento run all tests

**Comment by rimple-saini** [comment]
@fredden We have raised the Mainline PRs for this issue. It is estimated to be merged soon. Once Internal PRs gets merge, we will keep you posted on this.

Thank you!

CC @ihor-sviziev @hostep

**Comment by engcom-Charlie** [comment]
As per [this](https://github.com/magento/magento2/pull/36347#issuecomment-1673641452), moving this PR to Merge In Progress.

Thank you!

**Comment by hostep** [comment]
Looks like core devs implemented this in https://github.com/magento/magento2/commit/1a5795ec7381572b2b456f099d3057f60636cdc3 (was just merged via https://github.com/magento/magento2/commit/0b410856a16acf11219512d2c691f3cd2bbe3643)

**Comment by engcom-Bravo** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-7698 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fmagento2+AC-6975&type=commits

Based on the Jira ticket, the target version is 2.4.7-beta3.

Thanks

**Comment by engcom-Bravo** [comment]
As per this comment https://github.com/magento/magento2/pull/36347#issuecomment-1729358255 We are closing this PR.

Thanks.

**Comment by fredden** [comment]
Thanks @hostep for the note that @rimple-saini has made changes which overlap significantly with this. It frustrates me that work I've done is being done in duplicate internally by Adobe, especially for work already marked as accepted / merge in progress.

@engcom-Bravo please can you re-open this pull request.

The changes in 1a5795ec7381572b2b456f099d3057f60636cdc3 do not have the same impact as the changes in this pull request. The changes there only impact the initial installation of Magento, and will have no impact on new indexers added to an existing project. The changes in this pull request cover all new indexers, regardless if they are being added as part of the initial installation or later on in a project's life-cycle. When this pull request is re-opened, I will add a revert of 1a5795ec7381572b2b456f099d3057f60636cdc3 here to avoid confusion / duplication going forward.

**Comment by engcom-Charlie** [comment]
Hi @fredden,

As conveyed [here](https://github.com/magento/magento2/pull/36347#issuecomment-1473542100) this issue has been taken care by internal jira.

As per the business/Product Owner’s approval, the team have implemented the functionality.

As  conveyed by the Product Owner, we have to set the Update on Schedule indexer mode during the first time installation only. We dont need to change the indexer mode for the existing merchants for now. Hence internal team has implemented the same in this https://github.com/magento/magento2/commit/1a5795ec7381572b2b456f099d3057f60636cdc3

Thank you!

**Comment by fredden** [comment]
@engcom-Charlie please can you re-open this pull request.

The changes introduced in https://github.com/magento/magento2/commit/1a5795ec7381572b2b456f099d3057f60636cdc3 do not set the default mode and therefore it does not fix https://github.com/magento/magento2/issues/36419. This pull request does.

**Comment by ihor-sviziev** [comment]
@fredden, if I got right, the newly installed Magento will have a "scheduled" indexes by default, which is what is explained in the task.
I do agree that this still not fixing the case when you're upgrading, but TBH I'm not sure if that's expected behavior during Magento upgrades. This looks backward incompatible.
Instead, I would expect to have some warning maybe...

For example, we're using one extension that adds a new type of index, and it actually goes to infinite loop in the "on schedule" mode, so we intentionally set it to be "realtime"

**Comment by ihor-sviziev** [comment]
oh, I actually though it will affect existing ones... In case if it affects only a new ones, I do agree with @fredden and @hostep

**Comment by fredden** [comment]
@engcom-Bravo, @engcom-Charlie please can you re-open this pull request.

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
Thanks @ihor-sviziev. I have updated the "manual testing" steps to include installing a module which adds new indexers.

**Comment by engcom-Hotel** [comment]
@magento run WebAPI Tests, Unit Tests, Static Tests, Integration Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run Integration Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@fredden looks like almost all tests fails because of these changes. I just merged recent changes and re-run tests, but it's pretty low change it will fix the failures.

**Comment by fredden** [comment]
@ihor-sviziev the current test failures look similar to the problems previously seen (see https://github.com/magento/magento2/pull/36347#issuecomment-1467952360). There were previously messages from Adobe staff saying this would be fixed internally. @rimple-saini @engcom-Hotel please can you provide an update on this? Ref https://github.com/magento/magento2/pull/36347#issuecomment-1469374010 https://github.com/magento/magento2/pull/36347#issuecomment-1473542100

The unit test failures seem to be related to PHPUnit, specifically deprecations introduced into v9 in readiness for v10. Is this something I am expected to resolve as well?

**Comment by engcom-Charlie** [comment]
Hi @fredden, 

Appreciated your contribution!!

As per your updated PR description and from recent comments thread, I am trying to summarised the points which you are taking care in this PR.

1. On the initial installation of Magento, after this PR changes, the default indexer mode will be “Update by Schedule”.
2. This PR change, will not impact any existing indexers and therefore existing websites should not notice any impact from this change.
3. If a module with an indexer is installed on an existing website, it will be get created with the new default mode i.e. "Update by Schedule"

Please let us know, if we are missing anything here.  Also requesting you to update the PR description if anything is getting missed adding from your side. Once that is done please confirm so that I will reach out to Product Owner and discuss on these points in order to proceed further.

Need some clarity on this point too that: what if the existing  merchant will be upgrading from one magento version to next version? Are you taking care of this scenario of upgrade here in this PR too. Kindly confirm once.

Thank you!

**Comment by engcom-Charlie** [comment]
Hi @fredden,

In thoughts on [this](https://github.com/magento/magento2/pull/36347#issuecomment-1767795990) one. Moving it to On hold for now until will get some input.

**Comment by fredden** [comment]
> As per your updated PR description and from recent comments thread, I am trying to summarised the points which you are taking care in this PR.
> 
> 1. On the initial installation of Magento, after this PR changes, the default indexer mode will be “Update by Schedule”.
> 2. This PR change, will not impact any existing indexers and therefore existing websites should not notice any impact from this change.
> 3. If a module with an indexer is installed on an existing website, it will be get created with the new default mode i.e. "Update by Schedule"
> 
> Please let us know, if we are missing anything here. Also requesting you to update the PR description if anything is getting missed adding from your side. Once that is done please confirm so that I will reach out to Product Owner and discuss on these points in order to proceed further.

Yes, this seems to be an accurate summary. We're omitting the fact that an Adobe staff member made a mistake and committed some changes to the main branch related to this. This pull request removes those commits, so looks a bit messy because of that.

> Need some clarity on this point too that: what if the existing merchant will be upgrading from one magento version to next version? Are you taking care of this scenario of upgrade here in this PR too. Kindly confirm once.

There are three possible cases during an upgrade:

1. An indexer used to exist, and still exists after the upgrade: there should be no change to the indexer mode because of the changes here.
1. An indexer used to exist, and is being removed as part of the upgrade: the indexer should no longer exist, so its mode is irrelevant.
1. An indexer did not exist, and is being added as part of the upgrade: the indexer should have the new default mode - that is "update by schedule".

**Comment by chernenm** [comment]
Hello @fredden, @ihor-sviziev, @hostep,

We have reviewed the PR internally one more time and agreed that since it is introducing additional risks for upgrade process, we should only go forward with the changes impacting only new installations for the time being.
So, the only change we would deliver would be:
- When doing a fresh installation of Magento / Adobe Commerce 2.4.7 or any version above, all the indexers will be set in "Update by Schedule" mode by default and appear in status "Ready" after installation is complete.
 
And for the time being we will not be changing our current behavior during upgrade process. So, changes proposed in items #3 and #6 in the list above will not be delivered for the time being.

**Comment by chernenm** [comment]
Hi @ihor-sviziev,

The main concern why we do not want to interfere upgrade flow is that by changing all the indexers into "Upgrade by Schedule" mode during the upgrade might potentially break the upgrade flow. If for example some extensions require reindex of their indexers during upgrade and we are resetting indexers state to "Update on Schedule" then before making an upgrade, all the customers need to make sure that crons are properly configured and and up and running, which is currently not a required step for patch release upgrade. Also, if crons are configured to be run every 1 minute, It additional 1 minute of delay, which might not also be expected in the extensions and customizations code, which might also cause additional issues during upgrade flow.
And since, we are trying to keep patch release upgrade process as smooth as possible for our customers, these changes which interfere upgrade flow, should not be delivered in scope of a patch version, so we would recommend to postpone this contribution at least till a minor release.

**Comment by fredden** [comment]
@chernenm it seems like you have misunderstood the changes in this pull request. You're talking about changing indexer mode during upgrade flow, which is not something that is happening here. Perhaps we can schedule a call about this if you need more information?

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
As mentioned above comment threads, the required feature has been taken care in internal JIRA. Also as per the detailed information given by @chernenm [here](https://github.com/magento/magento2/pull/36347#issuecomment-1839675961), closing this PR now.

**Comment by fredden** [comment]
@engcom-Charlie please re-open this pull request. You have misundersood the state of this task.

**Comment by fredden** [comment]
@engcom-Charlie what needs to happen so that we can get this merged in? You've marked this as "on hold" but I don't understand what the problem is here.

**Comment by hostep** [comment]
Look what just got merged in 2.4-develop today: [AC-11421:In existing Magento installation when install third party indexer module set indexers in update by schedule by default:Change default Index mode schedule](https://github.com/magento/magento2/commit/999d6b35143817e184cdcf23396e467f99e01a20)

It's a completely different implementation as the one proposed in this PR, but probably results in the same outcome. What do you think @fredden?

**Comment by engcom-Bravo** [comment]
Hi @fredden,

Thanks for your Contribution!!

As per the requirement of https://jira.corp.adobe.com/browse/AC-6975 we delivered ‘Indexer default mode was schedule after Magento installation only’ and was not working when we install third-party Indexer(Custom Indexer) as default mode was still on save with third-party Indexer(Custom Indexer)
With new changes which are delivered in scope of https://jira.corp.adobe.com/browse/AC-11421 , if we install Magento or install third party Indexer(Custom Indexer), default mode will be schedule by default. It should resolve the issue raised in https://github.com/magento/magento2/pull/36347 as well.

Related commits: https://github.com/search?q=repo%3Amagento%2Fmagento2+Arrows_Delivery_07022024&type=commits

Based on the Jira ticket, the target version is 2.4.8-beta1.

Thanks

**Pull request closed without merging**
