### PR TITLE
Update composer coding standard magento

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Bump up version package coding standard in composerlock
Need upgrade package for re-test automate allure test results . See ticket/PR below

### Related Pull Requests

https://github.com/magento/magento2/pull/35101

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
@magento run all tests

**Review by Den4ik — APPROVED** [review]
I don't see any issues with updating of coding standard

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Review by sivaschenko — APPROVED** [review]

**Comment by mrtuvn** [comment]
https://github.com/magento/magento2/commit/735a01b39779fa7ab3f83bb39c65375f88de4748#diff-f37acfaa6b11f575a9a6f41a75fa73a61d0f8ebc2c9b8cddc215d8aca10e44f5
Closed my PR since internal already made it

**Pull request closed without merging**
