### PR TITLE
Removed duplicated content from luma theme's etc/view.xml.

### LINKED ISSUE #29623: [Issue] Removed duplicated content from luma theme's etc/view.xml.
This issue is automatically created based on existing pull request: magento/magento2#26655: Removed duplicated content from luma theme's etc/view.xml.

---------
### Description (*)

Removed duplicated content of view.xml from the luma theme as its already a child of the blank theme. 
Refer below Magent 2 guidelines for view.xml workflow: - - 
- https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-inherit.html#override-viewxml-file  
- https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-create.html#fedg_create_theme_how-to-images

### Related Pull Requests

N/A

### Fixed Issues (if relevant)

N/A

### PR DESCRIPTION
**Pull request by sanganinamrata**
### Description (*)

Removed duplicated content of view.xml from the luma theme as its already a child of the blank theme. 
Refer below Magent 2 guidelines for view.xml workflow: - - 
- https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-inherit.html#override-viewxml-file  
- https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-create.html#fedg_create_theme_how-to-images

### Related Pull Requests

N/A

### Fixed Issues (if relevant)

N/A

### Resolved issues:
1. [x] resolves magento/magento2#29623: Removed duplicated content from luma theme's etc/view.xml.

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Hi @sanganinamrata. Thanks for your contribution. Could you please update your branch and resolve conflicts so we will be able to proceed with this PR. Thank you!

**Comment by gabrieldagama** [comment]
The risk was set to`low` due to: the suggested changes shouldn't affect other areas.

**Comment by lenaorobei** [comment]
Closing this PR due to inactivity. Please feel free to reopen if you are going to continue working on it.
Thank you.

**Pull request closed without merging**
