### PR TITLE
Related to (fix issue 24735) (MC-34950 - Wrong style for Product in Checkout Cart)

### PR DESCRIPTION
**Pull request by engcom-Echo**
### Description (*)

Minor change to fix MC-34950. 
MC-34950 was found during Regression Testing for 2.4.0 release

### Manual testing scenarios (*)

1. Go to Storefront and add any Simple product or other (The product must have an image)
2. Go to mini-cart
3. Click "Proceed to Checkout'
4. Check a product image on right bar "Order Summary"

**Expect result:** The product image should be placed to the left of the product description.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-7624](https://jira.corp.magento.com/browse/ENGCOM-7624) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

### Luma theme

**Manual testing scenario:**

1. Go to Storefront and add any Simple product with an image to Cart;
2. Go to mini-cart

**Actual Result:** :heavy_check_mark: Image has good quality

Screenshot from 2020-06-05 23-59-47

3. Click on "**Proceed to Checkout**" button;
4. Check a product image on right bar "**Order Summary**";

**Before:** :heavy_multiplication_x: The image has incorrect position and size

Screenshot from 2020-06-05 23-54-22

After: :heavy_check_mark: The product image placed to the left of the product description and has correct size

screenshot_37

5. Fill all required fields and click on **Next** button;

**Before:** :heavy_multiplication_x:  The image has incorrect position and size

screenshot_39


After: :heavy_check_mark: The product image placed to the left of the product description and has correct size

screenshot_38

On a mobile device: :heavy_check_mark: Image in mini cart isn't blurred on iPhone

Screenshot from 2020-06-06 00-02-08
Screenshot from 2020-06-08 13-33-27


### Blank theme

**Manual testing scenario:**

1. Go to Storefront and add any Simple product with an image to Cart;
2. Go to mini-cart

**Actual Result:** :heavy_check_mark: Image has good quality

Screenshot from 2020-06-08 13-04-35

3. Click on "**Proceed to Checkout**" button;
4. Check a product image on right bar "**Order Summary**";

**Before:** :heavy_multiplication_x: The image has incorrect position and size

screenshot_40

After: :heavy_check_mark: The product image placed to the left of the product description and has correct size

screenshot_43


5. Fill all required fields and click on **Next** button;

**Before:** :heavy_multiplication_x:  The image has incorrect position and size

screenshot_42


After: :heavy_check_mark: The product image placed to the left of the product description and has correct size

screenshot_44

On a mobile device: :heavy_check_mark: Image in mini cart isn't blurred on iPhone
Screenshot from 2020-06-08 13-29-54

Screenshot from 2020-06-08 13-28-59

**Comment by lenaorobei** [comment]
Commit was cherry-picked and will be delivered to `2.4.0`.

**Pull request closed without merging**
