### PR TITLE
Issue 21446 : Remove Commerce specific files from Open Source codebase.

### PR DESCRIPTION
**Pull request by cmtickle**
### Description (*)
Removing design files from Open source codebase which relate to Commerce Edition functionality. A separate PR will be created to add theses to Commerce edition.

### Fixed Issues (if relevant)

1. magento/magento2#21446

### Manual testing scenarios (*)

1. Validate that the files have been removed from the codebase.
2. Ensure that the frontend and admin design are unaffected.
3. In Commerce edition, link the codebases with the other PR in effect and ensure that the Commerce specific functionality still appears correctly after deploying static content.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]
Changes looks good for me, but now sure if they’ll not brake commerce version. That need to be double checked during qa

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-5106](https://jira.corp.magento.com/browse/ENGCOM-5106) has been created to process this Pull Request

**Comment by belbiy** [comment]
@eug123 , can you look at this? Make sense to remove those styles, i think.

**Comment by sdzhepa** [comment]
Hello @cmtickle

Thank you for contribution and collaboration!

I can confirm that from the first glance there is no sense to have these *.less files in Open Source Codebase.
And it is logical and obvious decision to move them to Commerce Source.

But it will have negative consequences on composer installation approach. Especially how Magento builds the packages for composer
We do not have separate theme packages(blank/luma) for Open Source and Commerce yet

To develop complex fix for this issue need to have access to "Magento Composer package builder" which is internal only.

So, unfortunately, we have to close this PR and related issue and wait for fix from Magento Core

Also, want to admit that the internal team several times tried to fix this issue by moving *.less but changes were reverted.

**Additional information**
Internal Jira ticket with this issue: 
-  `MAGETWO-50837` "Remove unused less files from backend folders"

Currently has `REOPEN` status and  blocked by another architecture ticket:
-  `MAGETWO-44582` "Theme Extension Strategy"

**Pull request closed without merging**
