### PR TITLE
Adds test for getDataUsingMethod using digits

### PR DESCRIPTION
**Pull request by ghost**
Adding a test to document the current behaviour of `Magento\Framework\DataObject::_underscore` - in particular `getDataUsingMethod('key2')` exposes the inbuilt assumption from _underscore that any digit is preceded by an underscore.

### CODE REVIEW

**Comment by fooman** [comment]
I can't see how the travis failure 

> PHP Parse error:  syntax error, unexpected '.', expecting ',' or ';' in /home/travis/build/magento/magento2/dev/tests/integration/testsuite/Magento/Framework/Search/Adapter/Mysql/AdapterTest.php on line 39
> 
> Parse error: syntax error, unexpected '.', expecting ',' or ';' in /home/travis/build/magento/magento2/dev/tests/integration/testsuite/Magento/Framework/Search/Adapter/Mysql/AdapterTest.php on line 39

would be related to the addition of a unit test.

**Comment by adragus-inviqa** [comment]
@fooman - no one can: https://github.com/magento/magento2/pull/4343

**Comment by piotrekkaminski** [comment]
@mazhalai do you know what needs to be done? resubmitted based on latest version?

**Comment by mazhalai** [comment]
@fooman  can you sync with develop branch please? It this has been fixed in develop branch already.

**Comment by fooman** [comment]
@mazhalai done

**Comment by sshrewz** [comment]
Internal ticket created - MAGETWO-56728

**Pull request merged**
