### PR TITLE
Run tests on github actions

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
You need to consider the limits of Github Actions of 1000 or 2000 minutes.

**Comment by ihor-sviziev** [comment]
@lbajsarowicz it suppose to be free for public repos: 
image

**Comment by lbajsarowicz** [comment]
@ihor-sviziev : @navarr Developed at Mediotype a Github action that checks Magento Coding Standard with PHPCS and **displays results inline** (in modified files). Please consider having a look at: https://github.com/Mediotype/phpcs-action

**Comment by ihor-sviziev** [comment]
As it was discussed on Maintainers meeting - currently all tests running on all magento versions and they are standartized across all repositories, so it doesn't make sense to introduce less tests that will be running in parallel and will test only some part.
I'm closing this PR.

Also showing test failures for static tests directly on github is planned on existing test infra.

**Comment by okorshenko** [comment]
@ihor-sviziev do we have estimate/projection on how long it takes to execute one build (for static/unit/etc) using this functionality?

CC: @gabrieldagama

**Comment by lbajsarowicz** [comment]
You can take a look at ❌ next to the commits - at the top there is a time of execution:
image

**Pull request closed without merging**
