### PR TITLE
Fix warning count parameter must be array or object implements Countable

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

This is my fix for issue 25112. Not much changes, only add empty check 

### Fixed Issues (if relevant)

1. magento/magento2#25112: Warning: count(): Parameter must be an array or an object that implements Countable

### Manual testing scenarios (*)

1. First Create New Product
2. Go to System > Export
3. Choose Entity Type: Products
### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @mrtuvn,
Your changes looks good, but they're actually fixing not the root of the issue.

It looks like the code that creating `$options` variable expected to return an array all the time.
But if this issue appeared - looks like there is the case when not array was returned, and in this case would be more correct to identify case when not array was returned and return array.

Could you adjust your code according to my feedback?

**Comment by mrtuvn** [comment]
@ihor-sviziev i should add check is_array($options) && !empty($options)

**Comment by ihor-sviziev** [comment]
Hi @mrtuvn,
Idea was to check in which case `$options` could be not an array. As for me - it's an issue that returned not array, when it was expected --> we need to fix code that returns not array, and we don't need to fix code that you touched.

**Comment by mrtuvn** [comment]
@ihor-sviziev yeah i totally agreed with your point.
I have take a look around getOptions and i see something seem not right
1. I can't find define method $attribute->getFilterOptions();
2. $options = $attribute->getSource()->getAllOptions(false); in line 244 near line my touched code have new argument false. Method getAllOptions doesn't have any argument

**Comment by ihor-sviziev** [comment]
> 1\. I can't find define method $attribute->getFilterOptions();
> 2\. $options = $attribute->getSource()->getAllOptions(false); in line 244 near line my touched code have new argument false. Method getAllOptions doesn't have any argument

This is source model for attribute, it could be defined per attribute.

I can recommend you to put breakpoint and use xdebug for undesrtanding what models and what values we're having and why

**Comment by mrtuvn** [comment]
@ihor-sviziev is valid for call $attribute->getSource()->getAllOptions(false)
The origin getAllOptions doesn't have any parameter
Magento\Eav\Model\Entity\Attribute\Source\SourceInterface

I see in someplace in magento used getAllOptions() no parameter and some used getAllOptions(false) or even getAllOptions(false, false)

**Comment by ihor-sviziev** [comment]
@mrtuvn  I am closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Pull request closed without merging**
