### PR TITLE
[Forwardport] Make necessary space. #4

### PR DESCRIPTION
**Pull request by chirag-wagento**
### Original Pull Request 
 https://github.com/magento/magento2/pull/15790

### Description
Make necessary space between media-common and css class .
### Fixed Issues (if relevant)
N/A

### Manual testing scenarios
N/A

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by sidolov** [comment]
@chirag-wagento , please, combine this pull request with another to the same release line: https://github.com/magento/magento2/pull/15798. It will be simpler to process and deliver your changes. Thank you!

**Comment by chirag-wagento** [comment]
@sidolov 

I can see my changes in 2.3-develop branch. How can I merge and push https://github.com/magento/magento2/pull/15800, https://github.com/magento/magento2/pull/15798 and https://github.com/magento/magento2/pull/15804. can you please suggest me.

Thanks

**Comment by sidolov** [comment]
Hi @chirag-wagento , it's simple: 

- Checkout to branch from https://github.com/magento/magento2/pull/15798 (2.3-develop-PR-port-15789)
- Merge branches from another PRs to `2.3-develop-PR-port-15789`
- Edit PR description: add links to all original PRs

**Comment by chirag-wagento** [comment]
Hello @sidolov 

I have already done above steps. 
1. I have checkout **2.3-develop-PR-port-15789**
2. Up to date with 2.3-develop branch.
3. Merged  **2.3-develop-PR-port-15790**
4. it's show me **Already up to date.**

Can you please check once what is issue branches.

Thanks

**Pull request closed without merging**
