### PR TITLE
Translate Action Label

### PR DESCRIPTION
**Pull request by net32**
### Description
Simply enable the ability to translate 'Action' label.

### Manual testing scenarios
It is not necessary.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose.
 - [X] All commits are accompanied by meaningful commit messages.
 - [X] All automated tests passed successfully (all builds on Travis CI are green).

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=14688) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
@net32 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by dmanners** [comment]
Thanks @net32 if you could also sign the CLA and then I can process this PR.

**Comment by magento-engcom-team** [comment]
Hi @net32. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.5 release.

**Pull request merged**
