### PR TITLE
Jquery Cookie library updated to v1.4.1

### LINKED ISSUE #34427: Update Third Party library: jquery.cookie
* Update Third Party library: lib/web/jquery/jquery.cookie
* Confirm that it is used across Magento (adminhtml/frontend)
* Check which is the latest version available and replace the current one.

## Related issues
[Migrate to new js cookie](https://github.com/magento/magento2/issues/33477)

### PR DESCRIPTION
**Pull request by wasimbajwa9**
**Jquery Cookie Library updated** 

Updated Jquery Cookie Library to 1.4.1 which is the most recent available version. Here is the reference link https://plugins.jquery.com/cookie/

### Fixed Issues (if relevant)
1. Fixes magento/magento2#34427

### Manual testing scenarios (*)
1. Confirmed the use of the updated library by looking in to Developer tools of browser
2. Browser console is clean, no errors should be there.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by in-session** [comment]
@xmav @sidolov @andrewbess @ihor-sviziev 
Wouldn't it be better to remove the dependency on jquery and integrate a more modern solution? 
https://github.com/js-cookie/js-cookie

**Comment by ihor-sviziev** [comment]
@in-session, it is. Here is a task for that https://github.com/magento/magento2/issues/33477.
PS: upgrading the library will be way more straightforward, so I think it's ok as a first step.

@magento run all tests

@wasimbajwa9, please sign the Adobe CLA.

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Review by Rrego6 — APPROVED** [review]

**Review by andrewbess — APPROVED** [review]
Hello @wasimbajwa9 
Thank you for your contribution
Approved ✔️

**Comment by andrewbess** [comment]
Hello @wasimbajwa9 
Could you please sing Adobe CLA

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, thank you for the review.
[ENGCOM-9356](https://jira.corp.magento.com/browse/ENGCOM-9356) has been created to process this Pull Request
:eight_spoked_asterisk: @andrewbess, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by wasimbajwa9** [comment]
Closed and Reopened the Pull request after signing Adobe CLA.

**Comment by xmav** [comment]
@magento import code to magento-commerce/trigger

**Comment by m2-github-services** [comment]
@xmav an error occurred during the Pull Request import.

**Comment by xmav** [comment]
@magento import code to magento-trigger/magento2ce

**Comment by m2-github-services** [comment]
@xmav the branch with the code is successfully imported into the `magento-trigger/magento2ce` repository. Branch name: `imported-wasimbajwa9-magento2-34730`.

**Pull request merged**
