### PR TITLE
fixed - can't import external http to https redirecting images by default csv import

### PR DESCRIPTION
**Pull request by ghost**
### Description (*)
I think we should handle 302 redirection. We should check the next header if there is 302 redirection with url.

### Fixed Issues (if relevant)

1. magento/magento2#18839: can't import external http to https redirecting images by default csv import 

### Manual testing scenarios (*)

1. Use any image url with redirection like http://midwest-wholesale-staging.cloud.akeneo.com/bundles/pimui/images/info-user.png
2. It will redirect to https://midwest-wholesale-staging.cloud.akeneo.com/bundles/pimui/images/info-user.png and it is valid image.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Review by aleron75 — APPROVED** [review]

**Comment by aleron75** [comment]
Hello @rahulwebkul thanks for your submission.

Unless you have already done it, don't forget that, once merged, you can easily port this PR to other branches with the Porting Tool, [read more here](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool).

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-3368](https://jira.corp.magento.com/browse/ENGCOM-3368) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @rahulwebkul. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Pull request merged**
